### ISSUE TITLE
Use large preview image when updating personas

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#10009]
### Describe the problem and steps to reproduce it:
If you install [a theme](https://addons.mozilla.org/en-US/firefox/addon/three-wolf-moon-shirt/) you will get `preview_large.jpg` for the `previewURL`. When an [update](https://versioncheck.addons.mozilla.org/en-US/themes/update-check/165163) happens however you will get `preview.jpg` as the `previewURL`.

I think this is because the [update code](https://github.com/mozilla/addons-server/blob/8daf0e5383158037253f78e2f5cee9a69df472c8/services/theme_update.py#L184) is 6 years old and the primary [search/detail API](https://github.com/mozilla/addons-server/blob/560c09c9961040d75ca030ea5969443e36aeb109/src/olympia/addons/serializers.py#L461-L466) has diverged.

I believe this is the cause of [bug 1503611](https://bugzilla.mozilla.org/show_bug.cgi?id=1503611), where @wagnerand had some old themes that were showing the smaller preview image.

**Comment by eviljeff** [comment]
I'm going to wontfix this because all the LWT will become static themes by the end of this month* (that use a different update service and the standard extension API response). 

*hopefully, depending on signing improvements in Autograph
