### ISSUE TITLE
[static-themes] colors.icons property is not previewed

### ISSUE THREAD

**Issue by nt1m** [mozilla/addons-server#10012]
### Describe the problem and steps to reproduce it:
Check the theme preview on: https://addons.mozilla.org/en-US/firefox/addon/commando_fox/

### What happened?
The `icons` property is not previewed.

**Comment by eviljeff** [comment]
After some head-scratching, it seem commando_fox doesn't even use the `icons` property

```json
{
  "manifest_version": 2,
  "name": "Commando Fox",
  "version": "0.1",
  "theme": {
    "colors": {
      "accentcolor": "#404d4d",
      "tab_background_separator": "#404d4d",
      "toolbar": "#323d3e",
      "textcolor": "#8d9aa3",
      "tab_line": "#323d3e",
      "tab_loading": "#404d4d",
      "toolbar_top_separator": "#223039",
      "toolbar_vertical_separator": "#474747",
      "toolbar_bottom_separator": "#223039",
      "toolbar_field": "#323d3e",
      "toolbar_field_text": "#8d9aa3",
      "toolbar_field_border": "#223039",
      "toolbar_field_separator": "#474747",
      "toolbar_field_focus": "#323d3e",
      "toolbar_field_text_focus": "#8d9aa3",
      "toolbar_field_border_focus": "rgba(255, 255, 255, .07)",
      "button_background_active": "rgba(255, 255, 255, .07)",
      "button_background_hover": "rgba(255, 255, 255, .07)",
      "icons_attention": "#a98e5c",
      "ntp_background": "#323d3e",
      "ntp_text": "#8d9aa3",
      "popup": "#323d3e",
      "popup_text": "#8d9aa3",
      "popup_border": "#223039",
      "popup_highlight": "rgba(255, 255, 255, .07)",
      "popup_highlight_text": "#8d9aa3",
      "sidebar": "#323d3e",
      "sidebar_text": "#8d9aa3",
      "sidebar_border": "#223039",
      "sidebar_highlight": "rgba(255, 255, 255, .07)",
      "sidebar_highlight_text": "#8d9aa3"
   }
 }
}
```

The preview should look like:
![1](https://user-images.githubusercontent.com/768592/54757471-324b5280-4be2-11e9-9fbd-cdf54c2bef93.png)
but that was just due to https://github.com/mozilla/addons-server/issues/9642 being fixed.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I verified this issue on AMO dev - FF65(Win10).
When the icon property from the manifest is set as  `"icons": "#a98e5c"`,  `"icons": "red"` the preview will reflect it now. 

AMO dev

![AMO dev the icon property](https://user-images.githubusercontent.com/33448286/54927296-8f187700-4f1a-11e9-8c44-bf5975b35e69.png)

this is how it looked before - a compared test with AMO stage

![AMO stage no icon property](https://user-images.githubusercontent.com/33448286/54927339-aa838200-4f1a-11e9-9228-137dfd9a343b.png)
