### ISSUE TITLE
Add support for static themes for Android

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10019]
They'll need categories, and changes to the manifest extractor to recognise minimum version support

**Comment by AlexandraMoga** [comment]
I've tested these changes on AMO -dev and here are the results:

1. All newly submitted static themes will have their compatibility set to Firefox for Android 65 by default
![image](https://user-images.githubusercontent.com/31961530/48841368-e5717f80-ed99-11e8-8fbd-762a75cafd6b.png)

2. The category selected in the submission flow will be used both by Firefox desktop and android
![image](https://user-images.githubusercontent.com/31961530/48841350-da1e5400-ed99-11e8-8055-13f5891adfcf.png)

3. A static theme details page opened on Android will show an incompatibility message that specifies the FF version required for the theme to work
![image](https://user-images.githubusercontent.com/31961530/48841379-eefae780-ed99-11e8-9dfa-775fbae302f7.png)


4. Static theme Installations are also working on Nightly 65
5. Compatible static themes are now returned in search results on Android - see https://addons-dev.allizom.org/api/v4/addons/search?app=android&type=statictheme

@eviljeff if you think that there should be other functionalities to be tested, please let me know. I have covered so far the areas that seemed the  most relevant. 
Also, I suppose that the existing static themes will be re-indexed before Android compatibility will be officially released.
