### ISSUE TITLE
Django admin pages can't be accessed from the frontend unless the user is already authenticated in admin tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10015]
Follow up for https://github.com/mozilla/addons-frontend/issues/6487

STR:
1. Log in to AMO frontend with an account that has `Admin:Tools` and `User:Edit` permissions
2. Go to a User profile page and select the 'Admin user' button
3. Authenticate again with the same user in order to access the Django admin domain

Actual result:
After authentication, the user receives an unauthorized error page

Expected result:
The user is able to access the requested admin user page

Notes:
- If I'm navigating manually to `/admin/models/users/` I can see that I have the required permissions
- this also happens with the 'Admin addon' links from an addon details page
- reproduced on all AMO servers with FF63, Win10x64

![2018-11-14_17-06-13](https://user-images.githubusercontent.com/31961530/48698186-1b263500-ebef-11e8-8ea1-d6e785fc48df.gif)

**Comment by AlexandraMoga** [comment]
This is still a valid issue

**Comment by eviljeff** [comment]
It's just the redirect url after logging in.  It's been broken forever but, given correcting the url manually is a 2 second task, no-one has bothered fixing it.  Wontfix.

**Comment by eviljeff** [comment]
Actually, I looked into it and have a fix, but this issue is a dupe to #3765 so leaving closed.
