### ISSUE TITLE
The examples of using signing API with curl don't work (at least in Windows) because of single quotes

### ISSUE THREAD

**Issue by zeird** [mozilla/addons-server#1001]
Both links with examples with `curl`: [in the blog post](https://blog.mozilla.org/addons/2015/11/20/signing-api-now-available/) and [in olympia docs](https://olympia.readthedocs.org/en/latest/topics/api/signing.html), use single quotes around `curl` parameters.

And it seems that at least Windows version of `curl` 7.43.0 doesn't work with single quotes, but works just fine with double. So I propose to correct this.

**Comment by andymckay** [comment]
If double quotes work everywhere, that would work for me.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or add the "needs no qa" label?
