### ISSUE TITLE
Remove sudo:false from travis.yml

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10023]
So apparently travis get's rid of container based infrastructure: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

This actually makes some things much easier for us so let's try to get this landed asap and see what the impact is.

Indeed this change makes things like #8508 and a few other things easier. I simply assume that they're now focusing on that infrastructure and make sure it's super-fast.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  Welcome back!
Also, this looks like a "qa:not needed" :wink:
