### ISSUE TITLE
Remove 'activate-basket-sync' waffle switch

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10025]
Basket integration is live since early summer now, let's remove the related waffle switch.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF63, Win10x64

The Django admin waffle switch lists has no reference to `activate-basket-sync` anymore:
https://addons-internal.dev.mozaws.net/en-US/admin/models/waffle/switch/

Subscribing/unsubscribing to the addons newsletter from the user profile page is still working.
