### ISSUE TITLE
Type and grammar issues in PR_TEMPLATE

### ISSUE THREAD

**Issue by arshadkazmi42** [mozilla/addons-server#10035]
### Describe the problem and steps to reproduce it:
`PULL_REQUEST_TEMPLATE.md`, has a typo of `the the`  two times and a small grammar mistake at `here's a`

### What did you expect to happen?
Following changes are needed
`the the` => `the`
`here's a few` => `here are a few`

**Comment by eviljeff** [comment]
`here's a few` is valid (albeit not particularly formal).

**Comment by arshadkazmi42** [comment]
@eviljeff I checked it at [grammarly](https://www.grammarly.com/grammar-check), that is shown as wrong. Are we planning to keep it as it is?
