### ISSUE TITLE
Remove collection.top_tags 

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10048]
Top tags aren't used by the new frontend so we should remove all that functionality.

I'm specifically talking about `bandwagon:tasks::collection_meta` and `bandwagon:tags::collection_detail` which is only used for the legacy site which isn't used anymore and `top_tags` being empty is being handled properly so we can simply remove it.

**Comment by caitmuenster** [comment]
Patches welcome! 

Mentor: @EnTeQuAk

**Comment by dbxnr** [comment]
I'd like to have a shot at this

**Comment by EnTeQuAk** [comment]
@dbxnr feel very welcome to do so, let me know if you need any more guidance or help figuring out what can be removed.
