### ISSUE TITLE
URL displayed text is incomplete and incorrect; formatting issue

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#10047]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
https://github.com/mozilla/addons-server/blob/master/locale/en_US/LC_MESSAGES/django.po#L6500

### What happened?
1). The URL closing tag is tagged in the wrong place. Display text should be Mozilla Support. 
2). Extra space in the 2nd part of the string.

### What did you expect to happen?
Should change to 
1). ... <a href="%(sumo_url)s">Support</a> Mozilla -> ... <a href="%(sumo_url)s">Mozilla Support</a>.
2). ... you can <a href="%(forum_url)s"> ask on our forums</a>. -> ... you can <a href="%(forum_url)s">ask on our forums</a>.

**Comment by ItielMaN** [comment]
> 1). The URL closing tag is tagged in the wrong place. Display text should be Support Mozilla.

Shouldn't it be "Mozilla Support"?

**Comment by peiying2** [comment]
You are right: https://support.mozilla.org/en-US/ - here it shows Mozilla Support on the page.  Let me update the bug report.

**Comment by arshadkazmi42** [comment]
> 2). ... you can [ ask on our forums](%(forum_url)s). -> ... you can [ask on our forums](%(forum_url)s).
I don't see any difference in these two.

If this is a confirmed issue, then I can take this up.

**Comment by ItielMaN** [comment]
> I don't see any difference in these two.

There's a white space right after the `<a href>` tag, which is unnecessary:
`<a href=\"%(forum_url)s\"> ask on our forums</a>.`

**Comment by arshadkazmi42** [comment]
Is this issue confirmed? I can work on this. If its confirmed.

**Comment by eviljeff** [comment]
These strings are on a page in our legacy frontend (that you only see if you specifically chose "View classic desktop site") so they aren't really worth fixing.  The legacy frontend has been deprecated for a while, and will be deleted very soon (January 2019).  

Although the same oddly named "Support Mozilla" link is present there (would need an issue on https://github.com/mozilla/addons-frontend/issues instead)

**Comment by arshadkazmi42** [comment]
Thanks, @eviljeff for the confirmation. I can create an issue in `addons-frontend` repo for the same.

**Comment by arshadkazmi42** [comment]
@eviljeff I was going through the `addons-server` code and found this error in this repo [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/pages/templates/pages/about.lhtml#L70)
So, the issue should be in `addons-server` repo or `addons-frontend` repo?

**Comment by eviljeff** [comment]
> I was going through the `addons-server` code and found this error in this repo [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/pages/templates/pages/about.lhtml#L70)

As I said, These strings are on a page in our legacy frontend.  The code that should be changed for addons-frontend will be in the addons-front repo.
