### ISSUE TITLE
Update olympia folder/module structure and remove sys.path hacks

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1004]
PR: https://github.com/mozilla/olympia/pull/1081

This is unfortunately a requirement for django 1.7 as well.

Right now we're doing everything we can to avoid an `apps` module for imports, this now breaks things and imho is unreasonable as well.

(breaking: ``E   RuntimeError: Conflicting 'translatedmodel' models in application 'testapp': <class 'translations.tests.testapp.models.TranslatedModel'> and <class 'apps.translations.tests.testapp.models.TranslatedModel'>.``

Thus I'd like to rename the ``apps`` module to ``olympia`` and use the new names ``olympia.abuse``, ``olympia.core``, ``olympia.devhub`` etc. everywhere.

Imho this makes it clear where a module is coming from and avoids any hacks on the PYTHONPATH.

Opinions about that?

**Comment by magopian** [comment]
I'd say go for it ;) I personally don't see any good reason to keep this hack around (even though I'm sure there would be ways to make this hack work with django 1.7). Even more, I'd rather get rid of this hack which did bite me a few times already ;)

**Comment by andymckay** [comment]
Do you need to rename `apps` to `olympia` or is that a nice to have?

**Comment by EnTeQuAk** [comment]
Generally it's nice to have but while I'm at it I'd love to update the general structure to be more django-like again and not as wild as it is right now (imho).

**Comment by EnTeQuAk** [comment]
There is a WIP branch: https://github.com/EnTeQuAk/olympia/tree/feature/restructure-modules

And this is basically what I planned:

```
 - /
 ---- olympia/
 -------------- {access,accounts,amo,addons,...}
 -------------- wsgi.py
 -------------- urls.py
 -------------- migrations/
 -------------- libs/
--------------- conf/ (past 'sites' module)
 ```

(https://github.com/EnTeQuAk/olympia/commit/0e0685ccfe4db77ec212dc8959de2a276a545db3)

**Comment by EnTeQuAk** [comment]
This will be using https://github.com/mozilla/sugardough/ as an general inspiration.

**Comment by magopian** [comment]
+1

**Comment by EnTeQuAk** [comment]
This got finally merged and will probably be deployed tomorrow.
