### ISSUE TITLE
Update text for 404 page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10051]
This issue is to update the text of this 404 message: 

![screen shot 2018-11-21 at 3 55 35 pm](https://user-images.githubusercontent.com/23342476/48874041-e8726d00-eda5-11e8-8d3a-98067deb21fd.png)

Note: this is not the error message that comes up when an add-on has been removed by its author or when it has been disabled by an admin. 

The new text should read: 

**Oops! We can’t find that page**

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by [filing an issue](https://github.com/mozilla/addons-frontend/issues/new/). Tell us where you came from and what you were looking for, and we'll get it sorted.

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

* The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it. 
* Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again. 

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available [extensions](https://addons.mozilla.org/extensions/) or [themes](https://addons.mozilla.org/themes/).

/cc @jvillalobos

**Comment by eviljeff** [comment]
@caitmuenster that's the addons-frontend 404 page.  The addons-server 404 page is a little different [[e.g.](https://addons.mozilla.org/en-US/developers/dfdfdf/)]

**Comment by caitmuenster** [comment]
Oops! I will re-file this over to the add-ons frontend repo. :)
