### ISSUE TITLE
Screenshot thumbnails should have a 640x480 size

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10069]
Follow up for #9487 

STR:
1. Upload a screenshot for an add-on in DevHub Edit information page
2. Check the thumbnail preview generated after upload - see https://addons-dev-cdn.allizom.org/user-media/previews/thumbs/129/129409.png?modified=1543233474

Actual result:
Thumbnail size is rendered at 320x240

Expected result:
Thumbnail size is rendered at 640x480

Notes:
- from the original issue:
>what do we want the thumb size as? 320x240? What size would frontend be wanting?
It looks like it would be 640x480.
- reproduced on AMO -dev with FF63, WIn10x64

**Comment by eviljeff** [comment]
pulling @jvillalobos's question from #9487 here:


>> what do we want the thumb size as? 320x240? What size would frontend be wanting?
>
> It looks like it would be 640x480. /cc @atsay @pwalm to confirm

I wonder though, is this a change that should be made now?  Doesn't current frontend uses (and expects) thumbnails around the previous 320x200?  (so 320x240 isn't going to be a massive difference).  If we suddenly start serving thumbnails with twice the height and width won't frontend either downsize (wasted bandwidth) or display full size and change (break?) the layout quite a bit?

**Comment by jvillalobos** [comment]
The content changes are a precursor for the new product page, which is in the Q1 plan. We should avoid breaking anything in the transitional period. If it's possible to have thumbnails for both the current and new product pages, I think that would be ideal. If not, then generating the new ones and downsizing them sounds like the least bad option.

**Comment by eviljeff** [comment]
Reminder from #9487: after this is done we should do:
> > should we run the task to get some larger sizes even though they are unlikely to be in the correct ratio?
> 
> We'll have to deal with images with different ratios anyway, so having some larger ones is still beneficial. So I think the followup issue is warranted.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF63, WIn10x64

Screenshot thumbnails are rendered now at a 640x480 size
![image](https://user-images.githubusercontent.com/31961530/49090772-13a60200-f267-11e8-9936-2277fbeea1e3.png)
https://addons-dev-cdn.allizom.org/user-media/previews/thumbs/129/129416.png?modified=1543330211
