### ISSUE TITLE
add-ons with long descriptions in the manifest cause problems on upload 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10079]
followup for #9243 - only a bug with `content-optimization` waffle enabled.

On upload we parse the add-on for any names and descriptions in any locales, and then use them to populate the name and description of the add-on on AMO.  We then show a single locale to the developer in the upload flow (the default locale).  If the name + summary are >70 characters then the developer is forced to change them.  But if the name + summary > 70 in _other_ locales then a validation error is raised on the form but the developer _can't_ change them.

Some options:
a) auto-crop the summary (and/or name) in other locales automatically.  We could show a warning to the developer on the form at least.
b) don't validate the lengths of the other locales.  Could show a warning on the page.  Easiest but probably causes problems down the line.
c) change devhub submit flow to support editing multiple locales (an unknown amount of engineering work + needs UX so would have to be a Q1 task.  Also would need a) or b) to happen if the waffle was to be enabled before then)

@jvillalobos

**Comment by jvillalobos** [comment]
Let's go with (a).

**Comment by AlexandraMoga** [comment]
Adding a screenshot to highlight how the issue is looking now:

![image](https://user-images.githubusercontent.com/31961530/49080418-3ecf2800-f24c-11e8-8306-f38cbc51b5cb.png)

**Comment by AlexandraMoga** [comment]
This issue doesn't seem to be fixed yet. If I'm uploading an add-on with multiple locales and the summary+name of those locales are exceeding the 70 characters limit, error messages that block submission are still thrown in the form:

![2018-12-06_14-50-50](https://user-images.githubusercontent.com/31961530/49589045-01b41580-f971-11e8-82e7-a49b7dacfd21.gif)

**Comment by EnTeQuAk** [comment]
Moving to the next milestone.

**Comment by eviljeff** [comment]
I think the problems that caused the issue to be reopened are represented in #10178 so closing this again and will fix there.
