### ISSUE TITLE
Reviewers: Admins should be able to access the admin Ratings management tool (for listed or disabled addons)

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10077]
Follow up for #9248 

STR:
1. Log in to AMO -dev with a reviewer account that also has [Admin review permissions](https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/50097/change/) 
2.  Go to a disabled add-on review page - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/blue-jeans-w
3. Click on the user reviews link in the add-on information section

Actual result:
The reviewer is redirected to the frontend ratings page which is generating a 404

Expected result:
The reviewer should land on the admin Ratings management tool - [here](https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/?addon=491739)

![2018-11-26_17-06-59](https://user-images.githubusercontent.com/31961530/49022761-50f28d00-f19e-11e8-985d-11ab8bc4d582.gif)

Notes:
@wagnerand should the user ratings link from an add-on review page always redirect to the the admin ratings management tool, or should this happen only for disabled add-ons?

**Comment by wagnerand** [comment]
@AlexandraMoga Hm, that's a good question. I think whatever we change it to will have some drawbacks for either reviewers or admins, so I think we should leave it as is.

**Comment by wagnerand** [comment]
There was some confusion around this issue since it combined two things.

I filed #10112 and #10113 as separate issues.
