### ISSUE TITLE
Make add-on popularity boost in search easier to tweak

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10071]
As explained in #9741, when we index add-ons, we store a special `boost` property that depends on the add-on popularity (number of users). #9741 is about investigating that boost, potentially lowering it, but in the meantime, we should try to move that boost to a query-time boost, because it would make things easier to debug - having to re-index every time you change the value is annoying.

**Comment by AlexandraMoga** [comment]
As stated in #10171, validating search on -dev has become extremely difficult, so, until a better solution is found, we're going to have to wait for the changes to land in prod in order to properly verify search issues.

**Comment by AlexandraMoga** [comment]
I've tried several search scenarios on prod and overall I received relevant results, unlike -dev and stage.

I'm marking this issue as verified fixed.
