### ISSUE TITLE
Remove annual content re-review

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10095]
Related to #9158. 

Let's discontinue annual content re-review for extensions submitted to AMO. There's no need to re-review content that hasn't changed and this will help us manage the queues. 

cc @wagnerand

**Comment by AlexandraMoga** [comment]
Verified fixed on stage with FF63, Win10x64

I had a look before the fix landed to see how many addons where in the Last Content review queue:

- **24 addons out of 555 waiting for annual re-review**
![image](https://user-images.githubusercontent.com/31961530/49151521-d732de80-f318-11e8-8160-5f0168398ab9.png)


After the fix, the above mentioned add-ons are no longer present: 

- **total of 531 addons left in the content review queue**
**555 - 24 = 531**
![image](https://user-images.githubusercontent.com/31961530/49151790-98e9ef00-f319-11e8-95c9-3f782f572509.png)

@wagnerand I guess it will make sense to also remove the Last Content Review column from the Content review queue, no?
I can file a follow up issue if you want to fix that later on.

**Comment by wagnerand** [comment]
@AlexandraMoga Yeah I thought about that, but wanted to keep this patch as small as possible so it can be cherry-picked. I suppose a follow-up would be good, but it's not a priority.
