### ISSUE TITLE
The 2000s wants its graphics back - drop/update the selection of default addon icons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10090]
We current allow developers to either upload a custom addon icon or select from 18 icons.  Which are, imho, quite dated - unsurprisingly as they've not been updated since they were added over 8 years [ago](https://github.com/mozilla/addons-server/commit/b8665d4d640c10fd83f9c6a9d5704347771c1a9e#diff-e8edcb422a92f23e11fd0aab389e2ec4) as category icons.

The trigger for this is #5805 makes 128x128 the new standard but we only have 32 and 64 size for them, so as a workaround I has to upscale the 64 to 128 which makes them look even worse.

~So we should either drop them, or if someone wants to replace them with a more current selection I guess that works too.~  We're going to drop the multiple icon selection and replace them with the single default icon as per https://github.com/mozilla/addons-server/issues/10090#issuecomment-533190650 (the developer can still upload their own)

@jvillalobos

**Comment by eviljeff** [comment]
I couldn't find any in the repo, but who (other than fligtar maybe) knows where the originals for those icons would be.  Though even if we do find the originals the designs are still dated.

We do have the default puzzle icon in 128 though 
![puzzle-128](https://user-images.githubusercontent.com/768592/49107064-a8672a80-f27c-11e8-8c89-4ee25ecb3895.png)

**Comment by eviljeff** [comment]
technically that's a slightly different design of puzzle piece, but close enough:
![default-64](https://user-images.githubusercontent.com/768592/49107156-e2d0c780-f27c-11e8-97c9-a351ce9bdf5a.png) vs ![puzzle-64](https://user-images.githubusercontent.com/768592/49107165-e82e1200-f27c-11e8-9510-3012c283884d.png)

**Comment by jvillalobos** [comment]
Yeah, that's fine. I think @brassy- knows about a free icon repository we might be able to mine for some other defaults. However, given the current change in plans, I think multiple default icons might not be needed as much.

**Comment by EnTeQuAk** [comment]
I wonder if this is a good candidate for consideration when we'll be talking about updating our designs to the latest Firefox branding maybe?

**Comment by eviljeff** [comment]
I was going to go with dropping the selection of icons - leaving just the default puzzle piece and the ability to upload your own icon.  The puzzle piece would probably do with an update too but I don't know if there is something already suitable for Firefox branding.  (The monochrome puzzle piece in the AOM looks a bit boring?)

**Comment by eviljeff** [comment]
From 2019-09-11 #amo:
> <@eviljeff> just to confirm, are you okay with me doing https://github.com/mozilla/addons-server/issues/10090#issuecomment-529832678 ? 
<@jvillalobos> is there any urgency to fix it?
<@eviljeff> no.  It just ended up being tagged as stale so I thought I'd do it when I have a bit of spare time.  If it's still dependant of plans, etc, I can drop it again.
<@jvillalobos> I'll ask emanuela for opinions. I think your approach should be okay, but I want to see if we have better options. We have a meeting tomorrow, so I'll let you know
<@eviljeff> changing the existing icons is much easier, fwiw.  But I'll take any chance to strip out crufty devhub code.

De-assigning for now because blocked on product decision.

**Comment by jvillalobos** [comment]
Let's go with the single icon.

**Comment by AlexandraMoga** [comment]
The pre-defined add-on icons have been removed from DevHub. The default green puzzle icon is the only one that can be selected if a custom icon is not uploaded. 

The add-ons that used the pre-defined icons still display them:
![image](https://user-images.githubusercontent.com/31961530/101642731-0027f700-3a3c-11eb-8b92-3c02abd7e8f7.png)

I understand that this might change with #16114 

Custom icons can be uploaded as well.

This issue is verified fixed on stage.

**Comment by eviljeff** [comment]
> The pre-defined add-on icons have been removed from DevHub. The default green puzzle icon is the only one that can be selected if a custom icon is not uploaded.
> 
> The add-ons that used the pre-defined icons still display them:
> ![image](https://user-images.githubusercontent.com/31961530/101642731-0027f700-3a3c-11eb-8b92-3c02abd7e8f7.png)
> 
> I understand that this might change with #16114

Yes, after #16114 the pre-defined icons will belong to the add-ons individually so there won't be a list of pre-defined icons as such - they will as is the developer had uploaded them as custom icon.
