### ISSUE TITLE
Addon validator has a 45 char limit for the add-on name while the edit details form doesn't have the same limitation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10091]
STR:

1. Log in to AMO -dev
2. Create a new add-on package and make sure that the manifest `"name"` has more than 45 characters
3. Submit your add-on through the dev hub distribution page
4. Observe the validation results 

Actual result:
An error is triggered for the "name" field which exceeds the 45 character limitation

Expected result:
Since the Name field in Dev Hub is more flexible now - it allows for an add-on name to have up to 68 characters - we should make sure that there are no inconsistencies between the validation page and the edit details form

Notes:
- reproduced on AMO -dev with FF63, Win10x64

[1] validation error
![image](https://user-images.githubusercontent.com/31961530/49088976-30d8d180-f263-11e8-8f8b-f05d3cd69204.png)

[2]
Dev Hub Edit information page
![image](https://user-images.githubusercontent.com/31961530/49089106-785f5d80-f263-11e8-9471-602553e40e98.png)

**Comment by eviljeff** [comment]
This should be an addons-linter issue.
Anyway, It's going to be difficult to do before the `content-optimization` waffle is enabled because the linter doesn't know about waffles so can't know the limit changes to 68 from 45.
