### ISSUE TITLE
Internal server error received at account registration with the '2fa-for-developers' waffle switch on

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10105]
Follow up for #10046 

Prerequisites: the '2fa-for-developers' waffle is switched on

1. Open AMO -dev - https://addons-dev.allizom.org/en-US/firefox/
2. Register a new account
3. Check the verification email received and confirm the registration
4. Return to the tab where you started the registration process 

Actual result:
The new account registration can't be completed  - an internal server error (500) is received 

Expected result:
The account is confirmed and the user is logged into AMO

Notes:
- a 500 error is received also if I try to log in with this user after the registration failure
- **with '2fa-for-developers' switched off**: - I can successfully log in to AMO with the user created with the above steps
- reproduced on AMO -dev with FF63, WIn10x64

 @diox I'm not sure if this error is on our side or on Fxa. I can move the issue there if you can confirm.

![image](https://user-images.githubusercontent.com/31961530/49161520-ad39e600-f331-11e8-8679-1bd89409ae69.png)

**Comment by diox** [comment]
Our side of things https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4985284/ I can fix that.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

Account registrations with the  `2fa-for-developers` switch on are now completed without any error.
