### ISSUE TITLE
Reviews report fails if there are no reviews

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10100]
TypeError: olympia.reviewers.management.commands.review_reports in generate_report_html

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4977154

**Comment by AlexandraMoga** [comment]
The addon review and content review reports are sent also when there is no reviewer activity for the past week:
![image](https://user-images.githubusercontent.com/31961530/49725189-cc127380-fc73-11e8-8a52-33283f22b7fb.png)
