### ISSUE TITLE
Remove the Last Content Review column form the Content review table

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10111]
Follow up for #10095 

STR:

1. Open the Content review queue in Reviewer Tools - https://reviewers.addons.allizom.org/en-US/reviewers/queue/content_review
2. Check the table layout

Actual result:
There is a  Last Content Review column present

Expected result:
Since the annual content re-review was discontinued, the Last Content Review should be removed as well

![image](https://user-images.githubusercontent.com/31961530/49207217-f5eab100-f3bc-11e8-9eef-6db68ce30182.png)

**Comment by arshadkazmi42** [comment]
As per my understanding, to fix this we need to remove `last_content_review` from here
https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/utils.py#L252

Can someone confirm this fix? Whether this is correct or not?

**Comment by Abhi-khandelwal** [comment]
@AlexandraMoga , is this issue still open? can i work on it?

**Comment by diox** [comment]
@wagnerand to confirm we can remove this column. If we can, then anyone can work on it, yes.

**Comment by wagnerand** [comment]
A question for @caitmuenster.

**Comment by caitmuenster** [comment]
This is no longer valid.
