### ISSUE TITLE
Don't show 'Your submission will be automatically signed.' for add-on types we don't sign

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1011]
## steps to reproduce:
1. Load https://addons.allizom.org/en-US/developers/addon/submit/2
2. Upload a search tool as an unlisted add-on
## observed behavior:

A developer who doesn't know that only extensions get signed may be confused by our validation message which says "Your submission will be automatically signed." even for search tools.
## screenshot:

https://www.dropbox.com/s/smcrv7jf5vg3von/Screenshot%202015-12-01%2013.16.23.png?dl=0

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF46(Win 7) and the logged issue seems not fixed.
Please see the screenshot for a search tool submission:
![search_tools](https://cloud.githubusercontent.com/assets/15685960/15738611/c2c183b0-28b4-11e6-89fe-042f8e6c20cb.png)

@eviljeff : or... we do not want to fix it?

**Comment by eviljeff** [comment]
I thought it was fixed via the other issue.

**Comment by eviljeff** [comment]
More details:
we need to change the template used for this page (search for the string "Your submission will be automatically signed") so we only show this text for certain types of add-on, i.e. ADDON_EXTENSION, ADDON_DICT, ADDON_LPAPP, ADDON_LPADDON

**Comment by eviljeff** [comment]
See https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code
You will need an amount of python skill to understand the implementation needed, though the change would be in a (jinja) template file.

**Comment by lavish205** [comment]
I would love to work on this bug. As I can understand I need to edit [this file](https://github.com/mozilla/addons-server/blob/master/static/js/common/upload-addon.js#L449)

**Comment by tofumatt** [comment]
From what @eviljeff said there is some python files to touch too, though you're right it seems the template is in the JS. If the add-on type is available in the JS maybe that is the only file that needs changing though.

**Comment by eviljeff** [comment]
> I would love to work on this bug. As I can understand I need to edit [this file](https://github.com/mozilla/addons-server/blob/master/static/js/common/upload-addon.js#L449).

Yes (I assumed the text was in a template as that's the norm, but it seems we add via javascript in this case).

If you check `results.validation.detected_type` it should contain the type of the upload.  I think the different values are the ones listed [here](https://github.com/mozilla/amo-validator/blob/master/validator/main.py#L15) - i.e `languagepack`, etc

**Comment by lavish205** [comment]
@eviljeff for which `type_choices` should we show this text?

**Comment by eviljeff** [comment]
`constants.PACKAGE_EXTENSION
constants.PACKAGE_DICTIONARY
constants.PACKAGE_LANGPACK` I think

**Comment by lavish205** [comment]
@eviljeff These `type_choices` are available in main.py file, how to access these values in upload-addon.js file?

**Comment by eviljeff** [comment]
you don't need to access any python files, the value should literally be `'extension'`, `'dictionary'`, or `'languagepack'`

**Comment by rafspiny** [comment]
is anybody still looking at this issue? @lavish205 ? @eviljeff ?

**Comment by eviljeff** [comment]
@lavish205 can clarify, but it looks like he's been too busy with other things to work on this.

**Comment by lavish205** [comment]
@eviljeff @rafspiny Sorry I've been busy , I'll provide update on this shortly

**Comment by ValentinaPC** [comment]
_**@eviljeff : shouldn't we remove the text for beta versions, also?**_

Verified as fixed  on AMO-dev FF51(Win 7) **for search tools** - the text is no longer displayed.
Postfix screenshot: 
![searchtool](https://cloud.githubusercontent.com/assets/15685960/23206812/bf92a30e-f8f7-11e6-8a36-9b7ca912185e.png)
