### ISSUE TITLE
Add 'created' column to django admin ratings page.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10126]
(Follow-up for #9248).

The django admin ratings page is missing the `created` field. Let's add it!

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/49434982-32a01900-f7be-11e8-8024-f2ba5b5d99a5.png)
