### ISSUE TITLE
JSPRINT SETUP EN VERSIONES ANTERIORES NO ENCONTRADO

### ISSUE THREAD

**Issue by Miguel9574** [mozilla/addons-server#10132]
### Describe the problem and steps to reproduce it:
En la versión Firefox 51.0.1 no encuentro el complemento JSPRINT Setup

### What did you expect to happen?
Antes lo encontraba en esa versión sin porblema
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
If the add-on isn't a webextension (compatible with Firefox Quantum) its been disabled. Firefox now uses the same extension API as Chrome browser.
