### ISSUE TITLE
The icon preview for the 128x128 section is rendered at the original picture size

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10146]
Follow up for #5805 

**STR:**
1. Log in to Developer Hub
2. Go to the Edit information page for one of your addons
3. Upload a custom icon with a height and width larger than 128px 

**Actual result:**
The icon preview is not rendered at 128x128px  -  the original image size is displayed instead

**Expected result:**
The icon preview is rendered at a height and width of 128px 

**Notes:**
Reproduced on AMO -dev with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/49377498-febbe980-f712-11e8-8186-6891a881fa13.png)

**Comment by AlexandraMoga** [comment]
Issue still valid

**Comment by Sparsh-Bansal** [comment]
@AlexandraMoga, in `static/js/zamboni/devhub.js` 
```
      $('#icon_preview_128 img').attr(
        'src',
        $('img', $parent).attr('src').replace(/32/, '128'),
      );
```
is not defined.
