### ISSUE TITLE
Wrong email address for content reviewers report

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10148]
The content reviews report is not being delivered, because I used the wrong email address 😱.

It should be addon-content-reviewers AT mozilla DOT com instead of DOT org.

**Comment by AlexandraMoga** [comment]
Content reviewers weekly report is sent to the correct address now:

![image](https://user-images.githubusercontent.com/31961530/49725741-1ea05f80-fc75-11e8-85d1-c7c1582975ff.png)
