### ISSUE TITLE
Searching for "last pass" doesn't find LastPass Password Manager highest in search results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10169]
Follow up for #10071

**STR:**

1. Open AMO -dev
2. Search for "last pass" - https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=last%20pass
3. Check the search results

**Actual result:**
A list with mostly irrelevant themes is returned  by this search query. LastPass Password Manager can be found somewhere in the middle of the first page of results: https://screenshots.firefox.com/KagIkbiFXcSG3xwy/addons-dev.allizom.org

**Expected result:**
LastPass Password Manager should be listed higher in search results

**Notes:**
- the same search query performed on stage seems to be bringing more relevant results: https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=last%20pass
-  reproduced on AMO -dev with FF63, WIn10x64

**Comment by AlexandraMoga** [comment]
https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=last%20pass&type=extension - shows that LastPass is a listed extension on -dev

**Comment by diox** [comment]
Similar to https://github.com/mozilla/addons-server/issues/10168 and https://github.com/mozilla/addons-server/issues/10167 they don't have a high enough number of users to show up.

**Comment by AlexandraMoga** [comment]
@diox so, basically, -dev search is irrelevant to us now, meaning that I'm going to be able to test this only when the changes are in prod

**Comment by diox** [comment]
Well dev search has never been particularly reliable :( We should consolidate those 3 issues into one and figure out the best way to solve this for you.

**Comment by diox** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/10171
