### ISSUE TITLE
Searching for "weather"doesn't list weather applications highest in search suggestions

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10167]
Follow up for #10071

**STR:**

1. Open AMO -dev
2. Search for "weather" - https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=weather
3. Check the search results

**Actual result:**
There are addons, mostly themes, with "weather" in their names and a few close matches with "feather" or "leather". Actual weather tools are buried in these results: https://screenshots.firefox.com/n9DeV0BnspeleVWt/addons-dev.allizom.org

**Expected result:**
Actual weather tools - extensions and search plugins - should be listed higher in search results

**Notes:**
- the same search query performed on stage seems to be bringing more relevant results: https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=weather
- also, on the assumption that misspelled words should now be better filtered, I expected that a search for **"wether"** will bring some weather applications in search results. However, this is not the case: https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=wether
- reproduced on AMO -dev with FF63, WIn10x64

**Comment by diox** [comment]
Are there actual weather add-ons on dev, that are compatible with Firefox 57+? Can you give references to the exact add-ons you were expecting to show up ?

**Comment by AlexandraMoga** [comment]
@diox  yes there are some search tools and extensions that are more relevant:

https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=weather&type=search
https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=weather&type=extension

**Comment by diox** [comment]
They are all at 0 users unfortunately.

**Comment by AlexandraMoga** [comment]
@diox even so, aren't they more relevant than a list of unrelated themes? That's what I would expect, at least, but maybe other users have different expectations...

**Comment by diox** [comment]
Well these themes do have "Weather" (or "Feather" - which we include as a possible typo) so they are deemed relevant :) I guess we could boost non-themes slightly more than the rest when not filtering by type though.

**Comment by diox** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/10171
