### ISSUE TITLE
Searching for "adblock" should list ad blocking extensions highest in search results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10168]
Follow up for #10071

**STR:**

1. Open AMO -dev
2. Search for "adblock" - https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=adblock
3. Check the search results

**Actual result:**
The returned suggestions contain mostly themes with "block" or "blocks" in their names and just a few ad blocking extensions scattered among them: https://screenshots.firefox.com/f3Q3EXZxnkg0NBvy/addons-dev.allizom.org

**Expected result:**
Add blocking extensions with names, summary, description matching the search query should be displayed highest in search results

**Notes:**
- the same search query performed on stage seems to be bringing more relevant results: https://addons.allizom.org/en-US/firefox/search/?page=1&platform=windows&q=adblock (excluding the first two examples)
- reproduced on AMO -dev with FF63, WIn10x64

**Comment by diox** [comment]
Same as https://github.com/mozilla/addons-server/issues/10167 - Are there actual non-legacy adblocking add-ons on dev? Can you give references to the exact add-ons you were expecting to show up ?

**Comment by AlexandraMoga** [comment]
@diox 
https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=adblock&type=extension - add blocking extensions, especially those present higher in the list

**Comment by diox** [comment]
Like for https://github.com/mozilla/addons-server/issues/10167 it's an issue with the number of users being too low.

**Comment by diox** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/10171
