### ISSUE TITLE
Addons with multiple locales can't have their details edited if name+summary >70 characters in some locales

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10177]
Similar to #10079 but for the Edit product page; Also happens only with the `content-optimization` waffle enabled.

**STR:**
1. Log in to the Developer Hub
2. Open the Edit product page of an add-on with multpe locales - see https://addons-dev.allizom.org/en-US/developers/addon/ublock-origin43/edit
3. Try to edit some of its details 

**Actual result:**
Addon details can't be edited because in other locales the name+summary exceed the 70 characters limit

**Expected result:**
If possible, make error messages dependent only to their corresponding locale, i.e. an error in the `de` locale should not influence the `en-US` locale

Notes:
- reproduced on AMO -dev with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/49590517-c61b4a80-f974-11e8-8f78-096d5514ff3d.png)

**Comment by AlexandraMoga** [comment]
Adding a new scenario:

#10097 made sure that addon name or summary can't contain only symbols.

In the context of addons with multiple locales, if a non-default locale has a name or summary made of symbols only, the following error is thrown:


![image](https://user-images.githubusercontent.com/31961530/51188277-5179eb00-18e6-11e9-80fd-a69ff26d8ae3.png)

I didn't file this as a separate issue because I believe this can be solved if the main issue described above is fixed one way or another.

**Comment by eviljeff** [comment]
In #10484 I've fixed this by just dropping the max-length requirements for non-default-locale properties.  There's no way (with the current implementation of the devhub edit forms) to sanely differentiate the locale the developer has just changed with all the other locales so only validating the default locale is the only fix.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF64, WIn10x64

The edit addon form for the default locale is no longer conditioned by the length of name and summary in the other locales -> no error received:

![2019-01-25_13-33-28](https://user-images.githubusercontent.com/31961530/51743929-dfa05f00-20a6-11e9-9aad-d40c1a946c20.gif)

@eviljeff if I understood correctly, you have removed the character restriction  for the other locales - i.e. Name or Summary in the other locales can be edited without any length constraint.

Can we make sure that product agrees with this approach?

**Comment by AlexandraMoga** [comment]
I'm fine with marking this as verified. I just wanted product to be aware of this behavior, until the more optimal solutions can/will be put in place.
Cc @jvillalobos ^
