### ISSUE TITLE
Most add-ons on dev have a number of users so low that search relevancy is impacted

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10171]
https://github.com/mozilla/addons-server/issues/10167 https://github.com/mozilla/addons-server/issues/10168 and https://github.com/mozilla/addons-server/issues/10169 are all the same issue: on dev, most add-ons have 0 or 1 user, while themes have thousands, so on dev we end up showing themes for a lot of searches when not filtering with type. That's a problem for QA that we should fix.

See also https://github.com/mozilla/addons-server/issues/9741 for the fact that add-on popularity is increasing the relevancy score too much *in prod*.

**Comment by eviljeff** [comment]
What's the solution here? Are -dev stats just made up? (If so how?)

**Comment by diox** [comment]
They aren't nowadays, they should be coming from actual (and therefore low, since not many install things from dev) metrics - providing the cron finishes successfully. 

I'm not sure what's the best solution. First I'd say we should investigate why some themes have such high numbers, then... either fake data, or improve the algorithm (I made it easier to tweak in #10071)

**Comment by AlexandraMoga** [comment]
This relevancy problem extends to stage as well, not just -dev.
