### ISSUE TITLE
Internal server error when save changes is clicked in Manage Status&Versions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10189]
STR:
1. Load AMO dev and go to dev hub to a submitted static theme
2. Go to Manage Status&Versions page and click on the version
3. Click on Save Changes

Expected result:
Changes successfully saved is displayed.

Actual result:
Oops! We had an error.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF63(Win10).
It is only reproducible with static themes.

![500 internal server error](https://user-images.githubusercontent.com/33448286/49743845-4e1a9080-fca4-11e8-8fcb-3daa5164285f.gif)

**Comment by wagnerand** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5020199/

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
I verified this on AMO stage with FF64(Win10) and there are no issues now when "Save changes" is clicked.

Right now the "Manage Version" page for a static theme is read only, there is nothing to edit since the "Compatibility" is no longer displayed. Add-ons also have "Version Notes" and "Notes for Reviewers" but these are not available for static themes.  
If the "Manage Version" page for static themes remains without editable fields the "Save Changes" button should be removed.  Let me know if I should file an issue for this.

![save changes2](https://user-images.githubusercontent.com/33448286/49939944-ebfd9d80-fee6-11e8-91bc-d3932f669e9c.gif)

**Comment by EnTeQuAk** [comment]
>  If the "Manage Version" page for static themes remains without editable fields the "Save Changes" button should be removed. Let me know if I should file an issue for this.

That's true, and that's indeed a separate issue. Can you file one? It's lower priority though and potentially a bit more work since that affects other packages like dictionaries as well these days and there isn't a proper common implementation yet.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I filed an issue here https://github.com/mozilla/addons-server/issues/10219
