### ISSUE TITLE
Move addons-frontend image config to seperate docker-compose.yml

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#10198]
As seen [here](https://github.com/mozilla/addons-frontend/issues/7196), moving the ```addons-frontend``` config within the base docker-compose.yml file to the docker-compose.selenium.yml file would fix that issue.

The secondary compose.yml should probably be renamed to docker-compose.ui-tests.yml or something like that.

**Comment by EnTeQuAk** [comment]
Note that with #9288 there now already is a `tests/ui/docker-compose.selenium.yml` file.

**Comment by jrbenny35** [comment]
Yup, what do you think about renaming it?

**Comment by EnTeQuAk** [comment]
I really don't have a preference, we could even drop the `.selenium` postfix and just name it `docker-compose.yml` :man_shrugging:

**Comment by jrbenny35** [comment]
Well I think it should have some kinda reference, but okay good to know.
