### ISSUE TITLE
Extra characters are present on the 404 page served by the legacy site

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10203]
STR:

1. Open AMO stage
2. Go to a page that is served only by the legacy site, i.e a dev hub page - https://addons.allizom.org/en-US/developers/addon/browserspecific/edit
3. Observe the 404 page

Actual result:
There are some extra characters - `%} ` - at the top of the error message

Expected result:
No visual issues

Notes:
- reproduced on dev and stage with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/49870521-4e3d9c00-fe1c-11e8-9961-4923881c8d86.png)

**Comment by EnTeQuAk** [comment]
This got already fixed on master by 0b60edfb8dd44c6c5ed9509c93757a64e2a77017 and 1d1e7b774a5c3e1019b9fe3b9c839fcaf7b7ec5c which I forgot to put on the cherry-pick list. On it.

**Comment by EnTeQuAk** [comment]
Should be fixed now.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage

![image](https://user-images.githubusercontent.com/31961530/49878280-d7aa9980-fe2f-11e8-9bde-78f52179c2d7.png)
