### ISSUE TITLE
Small glitch in the Statistics Dashboard when setting up a custom date to query by

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10202]
STR:

1. Go to an add-on details page with public stats - https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/statistics/?last=30
2. Select the "Custom" sort option
3. Click on a date range, then on the "Month+year" drop down to quickly change the dates

Actual result:
The date ranges appear bold for a short moment

Expected result:
No visual issues 

Notes:
- reproduced on all AMO servers with FF663, Win10x64

![2018-12-12_14-19-08](https://user-images.githubusercontent.com/31961530/49870110-1550f780-fe1b-11e8-966e-7f83bef5d3eb.gif)

**Comment by EnTeQuAk** [comment]
Personally, I really don't think we're ever going to fix this. Statistics haven't been touched in ages and the CSS/JS is crazy outdated :disappointed:
