### ISSUE TITLE
un-pin django-waffle

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10234]
Follow-up from #9882 / #10125 which pinned django-waffle below v0.15 because it broke testing.  Django-waffle's master branch now has a fix so once there's a new version (v0.16?) released we can un-pin.  

Or add `,>0.15` to the end of https://github.com/mozilla/addons-server/pull/10125/files#diff-07f1aca7e9f87eaba6c09042abd1a84aR204

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed.
Thanks
