### ISSUE TITLE
Receiving a 401 (Unauthorized) on "Notify me about new listed versions" option.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#10233]
### Describe the problem and steps to reproduce it:
Logged as an AMO reviewer, the "Notify me about new listed versions" checkbox was not getting checked when clicking on it.

I had to log myself out and log-in back again to get this feature working properly again.

Here are the console logs network logs I was able to grab : 
Failed to load resource: the server responded with a status of 401 (Unauthorized) on https://reviewers.addons.mozilla.org/api/v4/reviewers/addon/979465/subscribe/

Request headers :
POST /api/v4/reviewers/addon/979465/subscribe/ HTTP/1.1
Host: reviewers.addons.mozilla.org
...
Referer: https://reviewers.addons.mozilla.org/en-US/reviewers/review/why___sucks

Response headers :
HTTP/1.1 401 Unauthorized

Response content :
{"code":"ERROR_INVALID_HEADER","detail":"Invalid Authorization header. No credentials provided."}

### Anything else we should know?
Note that it seems that I was logged properly as the two reviews I did this morning were getting saved properly on AMO. Those reviews were done while this issue was occurring and they were performed before logging myself again on the platform.

**Comment by diox** [comment]
Yeah, it happens when the cookies for API auth and session are out of sync.
