### ISSUE TITLE
Return 400 for guids in invalid format in return to AMO feature

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10244]
In [return to AMO](https://github.com/mozilla/addons-server/issues/10228) some garbage guids lead to a 500.

This is because we can't serialize to JSON some strings that it's technically possible to decode using base64 - they are invalid unicode strings.

**Edit:** I originally filed this to handle serialization error in a generic way in the search API, but I'm re-purposing it to be just about return to AMO for now.

**Comment by diox** [comment]
An example of failure at the moment with the return to AMO feature:
https://services.addons-dev.allizom.org/api/v3/addons/search/?guid=rta:garbage

`garbage` does decode to something using `urlsafe_base64_decode`, unfortunately it decodes to `'\x81\xaa\xdbj\x07'` which is rejected by elasticsearch serializer with `UnicodeDecodeError('utf8', '\x81\xaa\xdbj\x07', 0, 1, 'invalid start byte')`.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev :

The following requests will return a 400 error when the guid is prefixed by `rta:`:

- request with invalid guid:
https://services.addons-dev.allizom.org/api/v4/addons/search/?guid=rta:rubbish
- request with multiple guids separated by comma:
https://services.addons-dev.allizom.org/api/v3/addons/search/?guid=rta:ZG9ub3R0cmFja3BsdXNAYWJpbmUuY29t,c3VwcG9ydEBsYXN0cGFzcy5jb20
