### ISSUE TITLE
Reusing the same version number breaks link to file

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1024]
A developer that is reusing an already reviewed version number will be unable to download their unlisted add-on. (The same happens for listed add-ons, but we trained editors to reject such submissions right away).

STR:
1. Submit an unlisted version.
2. ~~Approve or~~ reject it ~~(or wait for auto approval that is happening soon).~~
3. Upload another file but with the same version number.
2. Approve it (or wait for auto approval that is happening soon).
4. Try to download the new file.

(see also  https://bugzilla.mozilla.org/show_bug.cgi?id=1130585)

**Comment by wagnerand** [comment]
With the help of @jasonthomas I figured out why/how this happens:

The cronjob `hide_disabled_files` in `src/olympia/addons/cron.py`:
1. gets all disabled files for an add-on.
2. for each file gets the corresponding version
3. moves all files for each found version to the _guarded-addons_ directory.

So, if a there is more than one version with the same version number and one of them has been disabled, all files for all versions with that version number will be moved to the _guarded-addons_ directory and therefore unavailable, as the model expects that file to be outside of _guarded-addons_   because the file is pending.

**Comment by andymckay** [comment]
@diox was this a cron we were going to kill?

**Comment by diox** [comment]
@andymckay : no, we still need this one.

**Comment by wagnerand** [comment]
We no longer allow the reuse the version number.

**Comment by vcarciu** [comment]
Verified as fixed
