### ISSUE TITLE
Allow tgz files for source code bundles

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-server#10254]
### Describe the problem and steps to reproduce it:
- Try to upload a tar that is gz compressed with the file extension "tgz" as source code bundle for an extension version

### What happened?
Only "tar.gz" (among other formats) is accepted as file extension for gz compressed tars.

### What did you expect to happen?
Since "tgz" is a shorter form of "tar.gz" it would also be accepted. This is especially useful since `npm pack` produces a "tgz" archive of extension source code without any node_modules or build artifacts if ignores are configured correctly.

### Anything else we should know?
See https://docs.npmjs.com/cli/pack for the documentation of `npm pack`.

**Comment by diox** [comment]
Agreed, I should have kept it when I changed the allowed source types. Submitting a PR to fix this now. cc @wagnerand for info.

**Comment by diox** [comment]
Should reach dev shortly, will be deployed to prod January 10th.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, Win10x64

Files with `.tgz` extension can be uploaded as source code.
