### ISSUE TITLE
Stop spawning persistent spidermonkey processes from celery

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1026]
There is a feature of the validator where it opens a spidermonkey subprocess (to do javascript reflection) and [assigns it to a class variable for persistence](https://github.com/mozilla/amo-validator/blob/master/validator/testcases/javascript/jsshell.py#L87). 

We would like to fix this to address celery instability we're seeing related to the validator.

Some details: the validator assigns the process to a class variable and relies on `__del__` to terminate the instance but there are several things possibly wrong with this.
- references are very sticky in python so `__del__` might not be called as often as expected
- when a process is terminated, it is still held open (as defunct) because the parent process is still running. The parent process in this case would be the celery worker which runs forever (until restarted)

Example of a celery worker machine filling up with processes:

```
[root@ip-172-31-27-84 ~]# ps -ef | grep js
olympia  21907 21796  0 19:40 ?        00:00:01 [js] <defunct>
olympia  22405 21799  0 20:08 ?        00:00:00 [js] <defunct>
olympia  22660 21797  0 20:22 ?        00:00:00 [js] <defunct>
olympia  22751 21793  0 20:27 ?        00:00:00 [js] <defunct>
olympia  24086 21798  0 21:43 ?        00:00:00 [js] <defunct>
```

**Comment by kmaglione** [comment]
Manually killing the process should work. Or just leaving the instance around for additional validation runs.

Using a separate instance of Spidermonkey for every snippet that's parsed, like we used to do, isn't really an option, though. It nearly doubles the runtime of the validator.

**Comment by kmaglione** [comment]
(If it comes to it, though, more processes would probably lead to more zombies. I wonder if SIGCHLD is being ignored in the workers.)

**Comment by kumar303** [comment]
maybe the `terminate()` function can just kill off the process more cleanly. I haven't looked at what that does. Sadly, killing a child process from the parent is a dark art because there could be other subprocesses involved. There is a strategy here that might work http://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true

**Comment by EnTeQuAk** [comment]
Given that this is a nightmare to do and we're going to run the validator only against a very limited amount of add-ons beginning Firefox 57 I'm going to close this.
