### ISSUE TITLE
don't allow a display_name purely of non-printable|displayable charactors

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10266]
> Other than not allowing display names that are just spaces, current character restrictions to the display name should remain the same.

part of #8302 - bonus marks if it can fix #3388 too

We might want to do something like @diox said in #8302:
> I think for this, if we want to go further, my suggestion in #10097 (comment) should work - Using unicodedata.category + the Unicode Character Database properties values we can figure out whether each character is meant to be a letter in any alphabet, or punctation, space character of any kind, symbol, etc

**Comment by eviljeff** [comment]
Thinking about this, wouldn't just using `.trim()` do it, without having to iterate through the string checking character categories?  If it only contained non-displayable characters `trim()` would return `''`.  

According to the [docs](https://www.django-rest-framework.org/api-guide/fields/#charfield) `CharField` defaults to trimming whitespace and rejecting empty strings so I'm a little confused why setting ` ` as the display name doesn't result in an error (seems to result in the display_name being set to `''`)

**Comment by diox** [comment]
I assume you mean `.strip()`, not `.trim()`. `strip()` removes "whitespace", which is not exactly defined in the documentation, but does correspond to any unicode whitespace character. However, it doesn't remove control characters/non printable characters, just characters from the `Space_Separator` category.

```
>>> s = '\xa0 '  # NON BREAKING SPACE
>>> len(s)
1
>>> s.strip()  # Works
''
>>> s = u'\x7F'  # DELETE Control char
>>> print s

>>> s
u'\x7f'
>>> len(s)
1
>>> s.strip()  # Doesn't do anything
u'\x7f'
```

**Comment by eviljeff** [comment]
I did mean `.strip()`, though the question remains - shouldn't an empty or `''` value for `display_name` via the API cause a validation error?  Is the `default='', null=True, blank=True,` from the model field being pulled through to the Serializer somehow?  It's very strange.

**Comment by AlexandraMoga** [comment]
@eviljeff 
This doesn't seem to work on the frontend yet, so I've tried to verify it through the PATCH account endpoint - `PATCH /api/v4/accounts/account/user_Id/`

I have some scenarios that work as expected and some that need to be clarified.

**Working as expected:**
1. `"display_name": "\uFeFF"` 
=> response is 
 `"Must contain at least one printable character.",`
` "Ensure this field has at least 2 characters."`
2. `"display_name": "\r\nfoo\r\n"`
=> prints out user display name `foo`


**to be clarified**:
If I'm setting  `"display_name": "\u20DF"` , the response is `"Must contain at least one printable character."`
However, If i'm adding a printable character in the string. like `"display_name": "\u20DF O\u20DF"` and I check how the name is displayed in the frontend, I can see that the unicode character is actually printed.

This was a bit confusing, considering that in the previous scenario `"\u20DF"` did not pass as a printable character.


![image](https://user-images.githubusercontent.com/31961530/50839485-1832ff80-1369-11e9-90b7-a82eefe959d5.png)

**Comment by eviljeff** [comment]
`\uFeFF` is part of the 'Mark' character categories, which are supposed to be used in combination with other characters so I didn't think there would be a legitimate use case for including them on their own.  Though you're correct they technically are printable/displayable characters.

**Comment by AlexandraMoga** [comment]
@eviljeff  As far as I can tell, this restriction is working only when I'm using the api. 
Is there some further implementation to be done on the frontend to enable this restriction? At least, when I'm updating my display name in the frontend to a non-printable character,  the output is always displayed as plain text.

**Comment by AlexandraMoga** [comment]
form eviljeff on irc:
>as long as you aren't able to end up with something that looks like an empty string so the name is blank I think we're good.
