### ISSUE TITLE
use UserProfile.name instead of UserProfile.display_name everywhere

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10263]
We inconsistently use `UserProfile.name`, which has a fallback to always show something* when `.display_name` isn't set.  We should change it so we're not displaying `''`.

*something is the username until #10261 lands, then it will be a string with the user id in it.

**Comment by AlexandraMoga** [comment]
@eviljeff in #10261 I've verified that the `display_name` will not fallback to the `username` when a custom `username` is added.
The result was that the `display-name` on the frontend will be in the format `Firefox user <userId>.`

Is there anything else that needs to be verified here?

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, Win10x64:

![image](https://user-images.githubusercontent.com/31961530/50771134-5f9a8c80-1292-11e9-8dcf-2a43a9d8f4b2.png)

![image](https://user-images.githubusercontent.com/31961530/50771290-d6378a00-1292-11e9-87d3-12a3341f9908.png)
