### ISSUE TITLE
The message at upload failure should specify the strict_max_version allowed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10299]
STR:
1. Load AMO dev and login. Submit an add-on (such as a lang pack) that has a strict_max_version in the manifest. Add "strict_max_version": "100.*"  or "strict_max_version": "1000.*"
2. Observe the message displayed when the upload failed 

Expected result:
The highest supported  "strict_max_version" is 

Actual result: 
"/applications/gecko/strict_max_version" should match pattern "^[0-9]{1,3}(\.[a-z0-9*]+)+$"

Notes:
This issue is reproducible on AMO dev and AMO stage with FF64(Win10).

AMO dev

![dev](https://user-images.githubusercontent.com/33448286/50646880-e9d7ad80-0f7f-11e9-9321-df713effda1c.png)

**Comment by EnTeQuAk** [comment]
A version without the sub-version simply isn't valid. That's what the error tells you. `100.0` would be valid and continue further validation but simply `100` is not.

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#Firefox_(Gecko)_properties and https://addons.mozilla.org/en-US/firefox/pages/appversions/ for reference

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Thank you , this was helpful for testing further some scenarios for https://github.com/mozilla/addons-server/issues/10864
