### ISSUE TITLE
The dropdown menu is still displayed when navigating back 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10298]
STR:
1. Login AMO and go to Dev Hub 
2. Hover over the Menu displayed below the Dev Hub logo and then click an option
3. Navigate back 
4. Observe the screen

Actual result:
The drop down menu is still visible.

Expected result:
The drop down menu is no longer displayed.

Notes:
This issue is reproducible on all AMO servers with FF64(Win10). Also reproducible when hovering and selecting something from the Username and Tools menu.
It is not reproducible with Chrome.

Firefox

![drop down menu still opened ff](https://user-images.githubusercontent.com/33448286/50645192-995e5100-0f7b-11e9-8b21-a31b7741ba14.gif)

versus Chrome

![drop down menu chrome](https://user-images.githubusercontent.com/33448286/50645208-a7ac6d00-0f7b-11e9-90a4-9ea6b5bf8c39.gif)

**Comment by caitmuenster** [comment]
WONTFIX
