### ISSUE TITLE
While navigating using the keyboard, the rectangles that show which menu is selected look cut

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10297]
STR:
1. Using "Tab" key navigate through the Menu displayed on the right side of the screen and below the Dev Hub logo
2. Observe the rectangle

Actual result:
No display issues.

Expected result:
The rectangle is cut.

Notes:
This issue is reproducible on all AMO servers with FF64(Win10). 
Also reproducible for the first options available in the drop-down menus (for example, hover over Tools, click Tools and then use the Tab key to get to "Manage my Submissions")

![cut](https://user-images.githubusercontent.com/33448286/50642169-fb668880-0f72-11e9-9cd2-50876c6a172d.gif)

It doesn't look to good on  Chrome either, the rectangle is hardly visible - it's a light blue, look at "Documentation"

![light blue](https://user-images.githubusercontent.com/33448286/50642265-47b1c880-0f73-11e9-9be0-29de21c9a07a.png)

**Comment by championshuttler** [comment]
Hi , can i take this up , I think by adding `outline: none` to the anchor tag might resolve this issue, correct me please if i am wrong. Thanks

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by muffinresearch** [comment]
Ideally we should make sure there's still CSS that shows when this is  focused rather than just remove the outline.

**Comment by diox** [comment]
Yeah, we don't want to remove the outline entirely as it's useful for accessibility.

**Comment by LordGameleo** [comment]
Is this issue open? I would like to work on it.

**Comment by championshuttler** [comment]
@LordGameleo feel free to raise a Pull request! Thanks for your interest

**Comment by richa031** [comment]
is anybody working on this?

**Comment by LordGameleo** [comment]
@richa031 yes I am

**Comment by caitmuenster** [comment]
Hey @LordGameleo, how's it going with this issue?

**Comment by LordGameleo** [comment]
@caitmuenster I couldn't do it.

**Comment by HSR05** [comment]
Hey @diox i would like to work on this issue. Is it open? 
Can you guide me a little.
Thankyou.

**Comment by diox** [comment]
Looks like this isn't occurring anymore, it was fixed someplace else (annoyingly the outline appears to have been removed despite https://github.com/mozilla/addons-server/issues/10297#issuecomment-452819362 but we still underline the links so hopefully that's good enough).
