### ISSUE TITLE
A white rectangle is visible around the menu

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10296]
As a followup for the https://github.com/mozilla/addons-frontend/issues/7298 I've noticed the presence of the white rectangles in dev hub for the menu: Username, Tools, Back to Add-ons and also for the menu below Developer Hub logo.

STR:
1. Login to AMO prod and go to developer hub
2. Click the username then click back
3. Observe the username

Expected result:
No display issues.

Actual results:
A white rectangle around the username is visible. 

Notes:
Issue is not reproducible with Chrome and Edge. 
Reproducible with FF64 (Win10) on all AMO servers. 

Firefox 

![white rectangle visible with ff](https://user-images.githubusercontent.com/33448286/50641021-57c7a900-0f6f-11e9-8e3c-d159b5f317ac.gif)

Chrome 

![white rectangle not visible with chrome](https://user-images.githubusercontent.com/33448286/50641189-db819580-0f6f-11e9-8971-84da4a1b1a0c.gif)

**Comment by varundey** [comment]
Seems like a CSS issue. I would be interested in taking it up. /claim

**Comment by caitmuenster** [comment]
Sure, @varundey, go for it. Mentor: @eviljeff

**Comment by ioanarusiczki** [comment]
This issue is not reproducible. Verified with FF76(Win10).
