### ISSUE TITLE
Update Dev Hub content - signed out view ` 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10306]
This is a regular content update for the Dev Hub (signed out view). 

**Current content:** 

![screen shot 2019-01-04 at 9 42 45 am](https://user-images.githubusercontent.com/23342476/50702239-2699b800-1005-11e9-9656-a79f6a668b1c.png)

**Change text to:** 
[sub head] **Write one code base for many browsers** 
With the WebExtensions API, it’s easy to create extensions that will run on Firefox, Chrome, Opera, and Edge with only a few small changes. Learn more about the differences in extension development between the four major browsers and how you can make your extension cross-browser compatible. 

**Change CTA to:**
View Best Practices for Cross-Browser Development  (link to: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension)

**Comment by championshuttler** [comment]
I would love to help my friend @soniasingla to tackle this. Sonia let us know if you need any help. You can setup the project by following the docs at https://addons-server.readthedocs.io/en/latest/topics/install/docker.html

**Comment by soniasingla** [comment]
@championshuttler thanks for assigning the bug. I would raise a PR after setting up the project.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, Win10x64

![image](https://user-images.githubusercontent.com/31961530/50829709-11e35a00-134e-11e9-8fea-59247de00a0f.png)
