### ISSUE TITLE
Update Dev Hub content - signed in view 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10309]
This is a regularly scheduled update to the Dev Hub (signed in view). 

**Current view:** 

![screen shot 2019-01-04 at 12 29 36 pm](https://user-images.githubusercontent.com/23342476/50709370-6ae48280-101c-11e9-8967-6c48bff11b68.png)

**Updates:**
- Remove "create an appealing listing" text & call to action
- Move the right hand "how to get your extension featured" text and call-to-action to the left column 
- Add text to the new right hand section: "You can help users gain confidence and trust in your extension by following our best practices for onboarding users. "
- Add new CTA for right hand section: "See Best Practices " (link to: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/onboarding_upboarding_offboarding_best_practices)

**Comment by championshuttler** [comment]
I would love to help my classmate @Passionatecricketer to tackle this. Rishabh let me know if you need any help.

**Comment by Passionatecricketer** [comment]
@championshuttler I am ready to take this issue.

> I would love to help my classmate @Passionatecricketer to tackle this. Rishabh let us know if you need any help. You can setup the project by following the docs at https://addons-server.readthedocs.io/en/latest/topics/install/docker.html

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, Win10x64

![image](https://user-images.githubusercontent.com/31961530/50829097-055e0200-134c-11e9-84e9-c37c02296838.png)
