### ISSUE TITLE
Add Confirmation to "Cancel and disable version" in "Upload New Version" process

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#10314]
Since there is no undo method, it would be beneficial to add a confirmation popup for "Cancel and disable version" in case the button was clicked by mistake.

**Comment by eviljeff** [comment]
Iirc, at least when I added the button, it was reverseable because you could renominate the version for approval (not sure if you still can)

**Comment by eviljeff** [comment]
@jvillalobos thoughts?

**Comment by erosman** [comment]
> Iirc, at least when I added the button, it was reverseable because you could renominate the version for approval (not sure if you still can)

I didn't see any such option and had to ask Philipp to do it (even Andreea couldn't do it).

**Comment by jvillalobos** [comment]
If it's not reversible, it makes sense to have a confirmation prompt when the button is clicked. Having said that, resubmitting is easy, though you have to bump up the version number.

**Comment by erosman** [comment]
Resubmitting, besides the increased version number (and sometimes having to explain why version jumped), creates and stores a useless XPI on AMO that serves no purpose at all. ;)

**Comment by jvillalobos** [comment]
Still valid.

**Comment by shashwatsingh** [comment]
May I pick this? I have basic understanding of django/python.

**Comment by eviljeff** [comment]
> May I pick this? I have basic understanding of django/python.

You can, but you'll be on your own getting it working and I'm not sure how easy it will be.  I'd look at how developer hub handles popping up confirmation dialogs for other actions (e.g. deleting an addon).

**Comment by shashwatsingh** [comment]
I will give this a try, thanks for the pointers.

**Comment by shashwatsingh** [comment]
@eviljeff Does this look okay?

**Comment by AlexandraMoga** [comment]
I've verified the pages that expose the Cancel and disable button in the add-on submission process. When the button is clicked, a modal is opened where the user can confirm or cancel the request:

![image](https://user-images.githubusercontent.com/31961530/89657644-0e230b00-d8d6-11ea-915b-3accdfa626f7.png)

I think the message could use a better wording, but that can be done in a separate issue.

The other similar modal for Disabling or Deleting an add-on version is still working as before.
