### ISSUE TITLE
Reconsider/revert combining the name and summary fields

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10345]
#9243 added a restriction that name and summary combined shouldn't be longer than 70 characters.  The changes are fine for add-ons with metadata in a single locale, but have caused a lot of issues with multiple locales - especially when the translations are extracted from the xpi on upload.  

tl;dr - is the benefit worth the complexity?  @jvillalobos 

Outstanding issues with the feature are:
#10078 #10079 #10178 #10177 (and #10093 but that's UX improvements rather than bugs).  Potentially #10081 wouldn't be necessary either - or we could rename it to subtitle regardless.

**Comment by jvillalobos** [comment]
Even if we decided not to restrict the combined length of the fields, we would still want to restrict the length of each field significantly. Most if not all of the issues you brought up would still be valid in that scenario, so I don't think it gains us much to separate the restrictions.

Restricting field length is necessary for SEO and the new product page design, so I think we ("we") should deal with the complexity.

**Comment by eviljeff** [comment]
You're correct that the issues are around the more restrictive length of the summary field, but combining the fields for max-length makes the logic more involved, because of default locale fallback.

e.g.  Add-on has a name only in the default lang, en-US, but a summary in en-US and de.  The max-length for _de_ would be the length of name in _en-US_ + length of summary in de.  If you increase the length of name in en-US then you've potentially violated the max-length of summary in de also but you don't know it.

The edit details form doesn't allow you to edit fields in multiple locales either (you have to save when switching locale, which then causes the error); and the submission flow doesn't support different locales at all.

IMO the solution to all of this mess is dropping devhub editing of manifest fields and making the manifest the single-source-of-truth but that's a much larger project.

Anyway, #10078 #10079 #10178 #10177 block launch of the new requirements which was originally scheduled for November.

**Comment by jvillalobos** [comment]
My suggestion for the scenario you mentioned above is that the `en-US` name is copied over to complete the `de` translation, so you don't have to check for the restrictions across translations. The name is required, after all, so it shouldn't be empty for any locales.

Agreed that single source of truth is the real fix here, and that it's a longer-term, maybe-never kinda project.

**Comment by muffinresearch** [comment]
@jvillalobos @eviljeff I wonder if we should reconsider this being an error and moving to this being a warning at least to remove friction whilst developers adjust. This might depend on the numbers affected though.
