### ISSUE TITLE
"My Collections" should direct to the new collection page from Dev Hub

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10358]
STR:
1. Load AMO dev, login and go to Dev Hub, click on "My Collection" from the username's menu.
2. Hover over collections and click on Featured, Collections I've Made and Favorite Add-ons.

Expected result:
When "My Collection" and "Collections I've made" is clicked the new collection page is displayed.

Actual result:
When "Featured" is clicked, the list of collections (the new page) made by the user is displayed.  

Notes:
I don't think "Favorite Add-ons" is still used (it's a feature no longer available on the new pages). Perhaps it should be removed. 
This issue is reproducible on AMO dev and AMO stage with FF64(Win10). 

![collection pages on dev hub](https://user-images.githubusercontent.com/33448286/50961331-1d5e8e80-14d0-11e9-8ae9-089b678bc6e7.gif)

**Comment by diox** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/10981
