### ISSUE TITLE
Theme preview is not correctly displayed in pending theme updates Editor tools

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#1035]
Steps to reproduce:
1. Open pending themes queue in editor tools: https://addons.allizom.org/en-US/editors/themes/updates
2. Open any theme review detail page and hover over the header image.

Expected results:
The new image is previewed in browser.

Actual results:
The old image is previewed in browser.

Notes/Issues:
Verified in FF42(Win7) Issue can be reproduced in addons.allizom.org and addons-dev.allizom.org
Screencast for this issue:  http://screencast.com/t/HnIPTVyRm4Fx

**Comment by EnTeQuAk** [comment]
Is this issue still present or important? I believe we're going to touch editor tools some time later and change / fix this then too so I'm going to close this for now.

Please feel free to reopen at any time though if there's the need for it.

**Comment by AlexandraMoga** [comment]
I'm still reproducing this for themes in 'Theme updates' queue:

![theme preview](https://user-images.githubusercontent.com/31961530/35682442-67295c36-0769-11e8-90a0-5c1eb05ac278.gif)

**Comment by muffinresearch** [comment]
Theme previews are currently being re-worked for static themes which has a new preview which will replace this.
