### ISSUE TITLE
My Themes page is no longer accessible after changing add-on type to “theme” from Edit Listing->Admin Settings

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1036]
Steps to reproduce:
1. Sign in to AMO-stage with an admin account
2. Go to My Submissions page (https://addons.allizom.org/en-US/developers/addons )
3. Go to “Edit listing” for any listed addon (i.e. 4!1@4Addon-阜埼阜埼-side)
4. Scroll down to “Admin Settings” section and change the add-on type to “theme”
5. Save the changes

Expected results:
The changes cannot be saved (or the "theme" option is not available). 

Actual results:
The changes can be saved. “My Themes” page (https://addons.allizom.org/en-US/developers/themes ) returns an “Oops!” message.

Notes/Issues: 
The setting is irreversible, because, the addon, now a theme,  is no longer listed in “My Add-ons” so cannot be accessed. 
The 500 error code appears in the console when accessing “My Themes” page (from header menu also, or with direct link).
The issue is not reproducible for unlisted addon because the change cannot be saved.
Verified on FF42(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Screencast for this issue: http://screencast.com/t/81qBZH8p6Cj

**Comment by ValentinaPC** [comment]
I think that not being able to access My Themes page(from both about:addons and Public Pages) and also My Profile page, is also related to this issue.
The pages return a 500 error code in the console in AMO-stage FF43(Win 7).
please see the screenshot: 
![2015-12-18_1354](https://cloud.githubusercontent.com/assets/15685960/11896454/28c65914-a58f-11e5-912d-09cf0c85d37f.png)

**Comment by EnTeQuAk** [comment]
I don't necessarily understand why we support changing the type of an add-on, imho that information is already present in the install.rdf and changing it doesn't sound reasonable to me since it's either an extension, or a theme or a dictionary or a search add-on and that is dependent on the actual code, not what I configure on AMO.

Maybe we should remove this option alltogether?

**Comment by jvillalobos** [comment]
The setting is for admins only, and they generally know what they're doing. I don't think we need this type of check.
