### ISSUE TITLE
New auto-generated email for new static theme approvals

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10364]
Designers who submit new static themes currently receive auto-generated email for successful submission that extension that extension developers receive. We should create a new auto-generated email template for successful static theme submissions (new and updated). 

**Edited to add:** Replies to this email should go to theme-reviews@mozilla.org. 
____ 
Subject: Success! Your theme is available on addons.mozilla.org 

Body: 

Hi, 

Thanks for submitting your theme to addons.mozilla.org! Your theme {{ theme name}} has been approved and is now available in our gallery at {{ theme URL }}. 

If you'd like to share your experience creating themes or want more information about the Firefox theme community, please leave us a comment on our forum at https://discourse.mozilla-community.org/c/add-ons/themes.

Best wishes, 

The Mozilla Add-ons Team
https://addons.mozilla.org

**Comment by eviljeff** [comment]
Is this email about submission or approval?   They're two separate things for pre-approval types of add-on like themes.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/email/submission.txt is the generic add-on welcome email I thought you were talking about.

@caitmuenster , can you clarify if you're talking about an email that would be sent on the submission of the theme (when it's uploaded or created via the wizard), or after it's been approved by the theme reviewers.  Afaik for add-ons we only send an email on _submission_ the first time (otherwise they'd get two emails per theme - think about poor MaDonna's mailbox!)

**Comment by caitmuenster** [comment]
Thanks @eviljeff! Sorry, I forgotten themes were gated on review. Yes, this email should go out on approval, not on initial submission; let's not send out two emails per theme being uploaded.

**Comment by caitmuenster** [comment]
With regard to #10366: it would be awesome if we had a separate message for approved theme updates. (This is different than what is currently on the flowchart -- I will have to update it for the new flow.) 

**Subject**: Your theme has been updated on addons.mozilla.org 

**Reply-to:** theme-reviews@mozilla.org

**Body:** 
Your theme {{ name }} has been updated on addons.mozilla.org (AMO). Version {{ number }} is now available for download in our gallery at {{ addon_url }} .

Thank you!

**Comment by eviljeff** [comment]
> **With regard to #10366**: it would be awesome if we had a separate message for approved theme updates.

@caitmuenster #10366 is about rejections ... so it's _not_ in regard to it?

**Comment by eviljeff** [comment]
if @caitmuenster can clarify what's needed here we can mark it as contrib:welcome

**Comment by caitmuenster** [comment]
This template is triggered when the theme is approved from the queue. We don't email notifications when themes are submitted to the queue; that notification is built in to the last page of the theme submission flow for themes listed on AMO. 

For new and updated submissions listed on AMO, the template is: 

Subject: Success! Your theme is available on addons.mozilla.org 

Hi {{ user name}}, 

Thanks for submitting your theme to addons.mozilla.org! Your theme {{ theme name}} has been approved and is now available in our gallery at {{ theme URL }}. 

If you have any questions or want more information, please stop by the forum at https://discourse.mozilla-community.org/c/add-ons/themes and tell us what’s on your mind. 

Regards,

The Mozilla Add-ons Team
https://addons.mozilla.org

--------

I'm not recommending changes to the messages for self-distributed themes at this time.

**Comment by caitmuenster** [comment]
Note: this template should only be sent to theme designers, which means it will be a little more involved than changing the text of the current template being used. (That template currently goes to extension developers and theme designers.)

**Comment by caitmuenster** [comment]
Please keep this open. :)

**Comment by dbxnr** [comment]
I'd like to take this on

**Comment by eviljeff** [comment]
@dbxnr go ahead

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-7
