### ISSUE TITLE
New auto-generated email for static theme rejections 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10366]
It looks like designers whose static themes are rejected receive the same rejection email as extension designers. We should create a new auto-generated email for static theme rejections. 
__ 
Reply-to: theme-reviews@mozilla.org 

Subject: Unable to add {{ theme name }} {{ version # }}  to addons.mozilla.org

Body: 

Hi {{ user name}}, 

Thanks for submitting your theme, {{ theme name }}, to addons.mozilla.org. 

Unfortunately, we cannot add this version of your theme to addons.moilla.org because of the following reason:

{{ reviewer comment / rejection reason }} 

If another version of this theme have been published on the site, it will continue to appear in the gallery.

We appreciate your involvement in the theme community and encourage you to create another design that fits our Terms of Service.

If you have any questions or want more information, please reply to this email. 

Best wishes,

The Mozilla Add-ons Team 
https://addons.mozilla.org

**Comment by caitmuenster** [comment]
Thanks, Jorge. I'm going to close this out and work on it a bit before re-opening.

**Comment by caitmuenster** [comment]
Copy for the static theme rejection template has been updated; issue is now re-opened.

**Comment by eviljeff** [comment]
@caitmuenster we can make the change for theme rejections but what about theme approvals?  And should the same templates be used for both initial approvals that make the theme publicly available and subsequent approvals of new versions?

**Comment by caitmuenster** [comment]
@eviljeff, can you send me the link to the gist for theme approvals? I have a note in my [template doc](https://docs.google.com/document/d/1msQ-vvDi7GDK04bTp8P5MJgiXoejTrSZ_EOay7HCUA0/edit#) that the same approval message is fr new submissions & updates.

**Comment by eviljeff** [comment]
the generic addon approval template for the first approved version is:
https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/nominated_to_public.ltxt
then subsequent versions get:
https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/pending_to_public.ltxt

And all of the emails are based on https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/base.ltxt - so they all get the same footer about developer resources.

LWTs used to get:
https://github.com/mozilla/addons-server/blob/f3263977ea8b1cf0a15c96234df3c7d24c7df8d0/src/olympia/reviewers/templates/reviewers/themes/emails/approve.html

----
See also #10364 where the title and summary talks about _submission_, but the template is talking about _approval_.

**Comment by caitmuenster** [comment]
@eviljeff, I just commented on #10364 with copy for an approved theme update message.

**Comment by eviljeff** [comment]
> I have a note in my template doc 

@caitmuenster the template doc has different text (and subject lines) than this issue but as you've referenced it... does it supersede it? 😕

**Comment by eviljeff** [comment]
if @caitmuenster can clarify what's needed here we can mark it as contrib:welcome

**Comment by caitmuenster** [comment]
Tagging myself as a to-do 😅: 

- Finalize subject line & copy 
- Confirm what triggers it to be sent

**Comment by caitmuenster** [comment]
Apologies for all of the back and forth in this issue (I don't know if it's possible to void some of the earlier back-and-forth comments on GH). Let's handle approval messages on issue #10364. 

The following template is intended to be used for: 

- rejecting new themes (1st version) 
- rejecting newest version of an updated theme

The email text should be as follows: 

---

**Subject:** Firefox themes: unable to add {{ theme name }} {{ version # }}  to addons.mozilla.org 

Hi, 

Thanks for submitting your theme, {{ theme name}}. 

Unfortunately, we cannot publish this version of your theme to addons.mozilla.org for the following reason: 

{{ reviewer comment / rejection reason }} 

We appreciate your involvement in the theme community and encourage you to create another design that fits our Terms of Service.

If you have any questions or want more information, please reply to this email or leave us a comment on our community forum at https://discourse.mozilla-community.org/c/add-ons/themes. 

--
Mozilla Add-ons
https://addons.mozilla.org

---------

Ideally we would use a separate template when all versions of a theme are rejected and the theme is de-listed from AMO. That template would look like: 

Subject: Mozilla Add-ons: {{ Add-on name}} has been removed from addons.mozilla.org

Hello,

Due to issues discovered during the review process, your theme {{ add-on name }} has been disabled on addons.mozilla.org and no longer appears in the gallery. Users who have previously installed your theme will be able to continue using it.

Please see the user’s comments below for more information.

[eight asterisks]
Details:
{{ Comments }}
[eight asterisks]

You may address the issues raised in the review notes and inquire about any unclear items by replying to this email.

Thank you for your attention.

--
Mozilla Add-ons
https://addons.mozilla.org

**Comment by caitmuenster** [comment]
Note: this template should only be sent to theme designers, which means it will be a little more involved than changing the text of the current template being used. (That template currently goes to extension developers and theme designers.)

**Comment by ajs256** [comment]
Hi there, can I work on this? 

I can't seem to find in the codebase where these emails are sent, could someone point me there?

**Comment by eviljeff** [comment]
in the `ReviewBase` class.

**Comment by ajs256** [comment]
Ok, I found that class (`src/olympia/reviewers/utils.py` line 768). 

I'm following the docs, and I tried to run `make initialize`, but it repeatedly yells at me about this:
```py
/code/settings.py:164: UserWarning: Could not import local_settings module. Traceback (most recent call last):
  File "/code/settings.py", line 159, in <module>
    from local_settings import *  # noqa
ModuleNotFoundError: No module named 'local_settings'

  warnings.warn('Could not import local_settings module. {}'.format(
```
I figured it was just a warning, not an error, so I kept it going, and then I see this:

```py
Starting the reindexation for addons.
{"Timestamp": 1628787071477758976, "Type": "z.elasticsearch", "Logger": "http_app_addons", "Hostname": "94de8337c3c0", "EnvVersion": "2.0", "Severity": 6, "Pid": 1048, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "Unflagging the database"}, "severity": 200}
Traceback (most recent call last):
  File "/deps/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/deps/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/deps/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "/deps/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/deps/lib/python3.8/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/deps/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/deps/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/deps/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/deps/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/deps/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/deps/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fba540aa7f0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/lib/es/management/commands/reindex.py", line 167, in handle
    index = next(iter(ES.indices.get(alias)))
  File "/deps/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 101, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/deps/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 160, in get
    return self.transport.perform_request(
  File "/deps/lib/python3.8/site-packages/elasticsearch/transport.py", line 402, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/deps/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 245, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fba540aa7f0>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fba540aa7f0>: Failed to establish a new connection: [Errno -2] Name or service not known)
make: *** [Makefile-docker:83: populate_data] Error 1
make: *** [initialize] Error 2
```

Could I get a hand in figuring this out? Thanks!

**Comment by eviljeff** [comment]
One or more of the docker containers probably isn't running (`docker-compose ps`) but it's not practical to debug setup problems over github issues.  Come talk to us on Matrix in https://chat.mozilla.org/#/room/#amo:mozilla.org

**Comment by ajs256** [comment]
Sorry, but I have to leave this issue for someone else to take on.

**Comment by kplotnik** [comment]
Closing as obsolete.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-8
