### ISSUE TITLE
Need to migrate collection membership of LWT too

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10381]
LWT in anyone's collections will disappear once they are migrated to a static theme as the static theme is technically a different add-on (with a different ID).  This also applies to Mozilla's collection, including featured collections (which bestow the featured status on the theme).  We need to fix that.

**Comment by AlexandraMoga** [comment]
@eviljeff I believe you need to migrate some themes in order to test this.

Please migrate:
360491, 25001, 32245, 276880

The first two are in my collection and the last two are in the featured personas collection.

**Comment by AlexandraMoga** [comment]
@eviljeff 

It looks like there are issues with the LWT deletion again, or something similar 😟

![2019-01-15_18-23-04](https://user-images.githubusercontent.com/31961530/51194057-f7335700-18f2-11e9-93b7-6dd2c6d8fe76.gif)

![image](https://user-images.githubusercontent.com/31961530/51194077-00242880-18f3-11e9-824d-696d461a1caa.png)

Also,  https://addons-dev.allizom.org/en-US/firefox/addon/dark-blue/?src=search is no longer in the featured personas collection. 

In my collection however, I'm having only the static theme - https://addons-dev.allizom.org/en-US/firefox/collections/10640485/Collection-over-25/

**Comment by AlexandraMoga** [comment]
I have filed https://github.com/mozilla/addons-server/issues/10437 as a follow-up to isolate the issue highlighted above.

This patch managed to meet its purpose, that is to preserve a theme in a user's collection after the migration.
