### ISSUE TITLE
enhance recreate_theme_previews to only backfill missing previews

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10391]
`process_addons --task=recreate_theme_previews` either requires specific ids (`--ids=...`) or us to want all the previews to be regenerated.  In the interest of efficiency it would be good to have a similar command that only generates previews for the themes that don't have any currently (or don't have all 3? not sure)

**Comment by AlexandraMoga** [comment]
@eviljeff  as far as I understand, this patch should also handle the regeneration of a preview size, if that was missing previously.
For example, if we have a static theme that serves only two sizes, which was the case before #9419 was introduced. after the command is run, that theme should also receive the third preview size (720x92)

I guess that by verifying #9519, this additional fix is more or less confirmed.

But a double check won't hurt, so if you could migrate the following themes it would be great:
496147, 496142

**Comment by eviljeff** [comment]
ran the command with `ids=496147,496142`

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, Win10x64

https://addons-dev.allizom.org/api/v4/addons/addon/496147/  - all three previews are available now
