### ISSUE TITLE
Problems adding themes for the featured theme collections from django pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10403]
Prerequisites:
django admin pages 
The user is an Admin or Collections:Contribute

STR:
1. Go to the featured themes collection from django https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/
2. Add some themes and click "Save"
3. Go to AMO homepage observe the featured collection

Expected result:
The added themes are visible.

Actual result:
Only the second time after "Save" is clicked the collection is updated on AMO frontend.

Notes:
This issue is reproducible on AMO dev with FF64 (Win10). 

![must save twice](https://user-images.githubusercontent.com/33448286/51184259-63569080-18dc-11e9-9e57-fca9d6bfe29a.gif)

**Comment by ioanarusiczki** [comment]
@diox I could reproduce this issue on AMO stage with FF67(Win10).

Perhaps this information helps:

- I've also noticed now that after clicking the "Save" button when **[adding themes]( https://addons-internal.stage.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/ )** the message _"The collection "Featured Themes (12) was changed successfully"_ will only update the correct number of existing themes when I click "Save" one more time. 
Here's an example - I added theme number 12 and clicked "Save" but the message is "The collection "Featured Themes (11) was changed successfully". The second time it showed the correct number (12). 

![reproducible on stage1](https://user-images.githubusercontent.com/33448286/58944217-045dbf00-878a-11e9-8814-11a624d2e220.gif)

- when **[removing a theme](https://addons-internal.stage.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/)** the the message _"The collection "Featured Themes (N) was changed successfully"_  indicated again a wrong number yet on the frontend the collection is updated successfully.

**Comment by ioanarusiczki** [comment]
I can't tell if this issue is reproducible on prod or not but I see that it affects the appearance of  the `Recommended badge` for themes added in the collection in the search results, More themes by , User profile page and so on except for the detail page of the add-on.
To further explain: If I add a themes and `Save` changes the badge will be available on the detail page only and only if I `Save` changes one more time the badge will be available for all the other places. 

Perhaps @wagnerand could help to confirm if this is an issue only reproducible on the testing servers or it's also an issue on prod too.

**Comment by wagnerand** [comment]
Apart from this sounding like an odd bug, we are not recommending themes at the moment, are we?

**Comment by ioanarusiczki** [comment]
@wagnerand Not yet, but this should affect right now the featured theme collection on prod with the original problem as described [above](https://github.com/mozilla/addons-server/issues/10403#issue-399351209)
The collection should serve for making the recommended themes instead of featured (starting at the end of this week).

**Comment by wagnerand** [comment]
Yes, I can reproduce this behavior in prod as well.

**Comment by wagnerand** [comment]
Raising priority as this affects recommendations.

**Comment by eviljeff** [comment]
After looking at the code I'm pretty sure it's because in django admin the Collection instance either isn't saved when a CollectionAddon instance is created, or it's saved before the CollectionAddon is created, so things like the ES index and the featured status cache are updated too early.  

We _had_ specific methods for adding and removing add-ons that specifically saved the Collection afterwards but it appears they were only used by the legacy frontend.

**Comment by ioanarusiczki** [comment]
@eviljeff This has been fixed on -dev , once I add a theme in the collection, it will show up for the homepage, `recommended` badge is attached in search results, user profile too , no need to click `save` twice. 

While removing themes I've noticed an issue and filed a followup https://github.com/mozilla/addons-server/issues/11825
