### ISSUE TITLE
Investigate issues with the Position override function from the Discovery admin tool

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10415]
Follow up for #10174

1. Go to the admin Discovery curation tool - https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/
2. Open the details for each promoted extension and set a Position override (see Notes for the set-up I've used for this test)
3. Send a request to the discovery api endpoint by passing a `telemetry-client-id` that returns results for -dev - see https://addons-dev.allizom.org/api/v4/discovery/?telemetry-client-id=12b9377cbe7e5c94e8a70d9d23929523d14afa954793130f8a3959c7b849aca8
4. Check the results

**Actual result:**
When all the 4 extensions featured on the discopane have an override position set, I have the following results:
1. the discovery api returns only the promoted extensions (no recommendations), but the order is not the one set by the override position, or..
2. the discovery api also brings recommended extensions, ignoring the addons that have an override position set

**Expected result:**
The override position set for a discovery item should be recognized in the results returned by the discovery api

**Notes:**

The set-up I used:
Awesome Screenshot Plus - Position override = 2
AMO Admin Assistant - Position override = 3
Search by Image - Position override = 5
Tabby cat - Position override = 6
I haven't set on override position for themes.

- reproduced on AMO -dev with FF64, WIn10x64

**Comment by diox** [comment]
@AlexandraMoga the *or* in your actual results section... does that mean that for a given configuration, the results are not stable ?

**Comment by AlexandraMoga** [comment]
@diox  yes, that's what I've tried to highlight.
There are occasions when I don't see recommendations among the results, but there were situations when I had 1 or even 2 recommendations returned.

**Comment by diox** [comment]
From the logs it looks like 2. is because of taar not answering (or not answering quickly enough) some times. Not sure about 1. yet.
