### ISSUE TITLE
Local devhub not accepting upload file

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#10438]
### Describe the problem and steps to reproduce it:

- Pull latest docker images
- Start and configure server, creating dummy data
- Navigate to http://olympia.test/developers and sign in
- Go through addon upload process

### What happened?

- When you get to the page to actually upload the addon, you can select a file but the ```Continue``` button stays greyed out.

### What did you expect to happen?

- ```Continue``` button to become enabled and clickable.

**Comment by EnTeQuAk** [comment]
I seem to be able to reproduce this, I wonder if 3b2a5855e7cc0bf9f84c7786bcb1f1e71789e9f1 broke this somehow.

**Comment by diox** [comment]
Hey sorry about that. Any chance that ui tests could spit out the JavaScript errors that come up ? This would have make it more obvious.

**Comment by EnTeQuAk** [comment]
That'd be really ideal, @jrbenny35 any idea about that? I think we'd generally failures on JavaScript failures since they shouldn't occur. Especially with our well defined tests.

**Comment by jrbenny35** [comment]
Where did this error exist? We use a good log reporter that is easy to add things too so as long as it can access them, it's possible.

**Comment by EnTeQuAk** [comment]
The error was a JavaScript error raised by our scripts in the devhub. It couldn't access a function that was meant to be defined (but wasn't because another script 404'ed) and threw an exception.

**Comment by AlexandraMoga** [comment]
Could you please mark this as qa:not needed?
Thanks
