### ISSUE TITLE
The 'Latest News' link from DevHub homepage doesn't lead to the required page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10439]
STR:

1. Open the Developer Hub homepage while being logged out - https://addons.mozilla.org/en-US/developers/
2. Scroll down and click on the 'Latest News' link

Actual result:
You are prompted to Open or Save an `.xml` file

Expected result:
The link should redirect to the correct page, or if the page is no longer available the link  should be removed

Notes:
reproduced on all AMO servers with FF64, Win10x64

![2019-01-17_15-17-43](https://user-images.githubusercontent.com/31961530/51328918-0c3bf180-1a7d-11e9-87a3-3019790d3b05.gif)

**Comment by EnTeQuAk** [comment]
This is actually the result of Firefox removing it's [RSS-Feed support](https://support.mozilla.org/en-US/kb/feed-reader-replacements-firefox) - I think we should link to the actual blog instead.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, WIn10x64

The rss links have been removed from the following locations:

![image](https://user-images.githubusercontent.com/31961530/51486148-900d1b00-1da8-11e9-9945-268ce31125b5.png)
![image](https://user-images.githubusercontent.com/31961530/51486157-94393880-1da8-11e9-8450-079a205b3faa.png)
