### ISSUE TITLE
Remove old shield studies

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10448]
We have ~16 shield studies as static pages in our repository, are they still needed and used? I see in datadog ~1-5 requests to all our static pages and most certainly go to the about page.

cc @Osmose (feel free to redirect me to someone else)

**Comment by Osmose** [comment]
Redirect to @mythmon!

**Comment by EnTeQuAk** [comment]
Shield studies I'm talking about: https://github.com/mozilla/addons-server/tree/master/src/olympia/pages/templates/pages

**Comment by mythmon** [comment]
I think it is safe to call these pages obsolete now, and safe to remove.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  does this require QA?
