### ISSUE TITLE
response mocking in python3 isn't working locally (just basket)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10472]
Requests that hit the basket api are supposed to be automatically caught and a mocked response returned.  The basket API is hit each time a user's (own) profile is accessed (for notifications) so a number of accounts and users tests rely on the responses containing `token` in the JSON block response.
In python2 everything works fine; in Travis on python3 everything works fine; locally with python3 the tests fail.

**Comment by EnTeQuAk** [comment]
This sounds a lot like a bytes vs unicode error on some internal "check if this url matches ..." or something like that. Just a wild guess.

**Comment by diox** [comment]
It's because our docker is running Python 3.5, which hasn't got this bit: https://bugs.python.org/issue10976

basket-client is passing the result of `response.content` from a `requests` call directly to `json.loads()`.
