### ISSUE TITLE
“Check for Updates” are not working on the -dev server

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#10482]
### Describe the problem and steps to reproduce it:
- Install an older version of an extension. (https://addons-dev.allizom.org/en-US/firefox/addon/release01-22-2019/versions/)
- Go to about:addons at the Extensions section and update the installed extension.

### What happened?
- The update is not working and a warning in the Browser Console is displayed.
“1548163948047    addons.update-checker    WARN    HTTP Request failed for an unknown reason”

### What did you expect to happen?
- The updates to work as expected.

### Anything else we should know?
- This issue is reproducing only on the -dev server.
- Reproduced with FF66.0a1 (Nightly) on Win 7 64-bit.

![devbug](https://user-images.githubusercontent.com/15885467/51539268-4120bd80-1e5c-11e9-861d-d5232aa41cb8.gif)

**Comment by diox** [comment]
https://versioncheck-dev.allizom.org is giving me a certificate expired error and refusing to connect...

**Comment by ioanarusiczki** [comment]
@autrilla @cosminbadescuSV @diox 
I tested the version update today on AMO dev - FF64 (win10) and I did not have problems with it.

This is with check for updates 

![manual update](https://user-images.githubusercontent.com/33448286/51913155-915cca00-23de-11e9-930e-bca4dd077dfe.gif)

This is the automatic update when the browser is restarted 

![autoupdate at restart](https://user-images.githubusercontent.com/33448286/51913301-dda80a00-23de-11e9-93f6-806ca033152a.gif)
