### ISSUE TITLE
The featured-personas collection should also be Android compatible

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10480]
Refiled from https://github.com/mozilla/addons-frontend/issues/7461

STR:

1. Load AMO stage for android - https://addons.allizom.org/en-US/android/
2. Perform an empty search
3. Filter results by Themes and Featured

 Actual result:
There are no themes returned for the above filter criteria

Expected result:
Featured themes should also be returned on android

Note:
This is most likely caused by the the fact that the featured personas collection is set to be compatible with `Application = Firefox` (I've checked the set-up from admin). We should probably add the possibility for a collection to have multiple compatibilities, i.e. Firefox + Firefox for Android

https://addons-internal.stage.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/?_changelist_filters=p%3D1
![image](https://user-images.githubusercontent.com/31961530/51536487-68738c80-1e54-11e9-9a61-d4edaad4b7f7.png)

**Comment by eviljeff** [comment]
Featuring being per-application is quite a core part of how featured collections work, so it's likely going to be a non-trivial amount of work to allow featured collections to be multiple-application (all application would be the same thing now we only have two applications anyway).

Couldn't we just have two featured themes collections, one for each application?

**Comment by AlexandraMoga** [comment]
If that is the case, we will have two collections to maintain each time updates need to be made.
Maybe we should get some input from product on this.

**Comment by eviljeff** [comment]
@jvillalobos to opine

**Comment by jvillalobos** [comment]
I don't think we spend much time featuring extensions or themes for Android (@devaneymoz can weigh in on this), so I think the better solution here is to remove the Featured search filter on Android, since it won't have much utility there.

/cc @atsay

**Comment by eviljeff** [comment]
@willdurand looks like that frontend issue might have to be reopened to drop featured as a thing for Android themes.  

(Though, for the record, I still think the easiest fix all around is just to duplicate the collection for both Firefox and Android.  No code changes needed)

**Comment by willdurand** [comment]
> (Though, for the record, I still think the easiest fix all around is just to duplicate the collection for both Firefox and Android. No code changes needed)

I would prefer that too because I am super confused by all these small differences between Android and Desktop.

**Comment by willdurand** [comment]
> I don't think we spend much time featuring extensions or themes for Android (@devaneymoz can weigh in on this), so I think the better solution here is to remove the Featured search filter on Android, since it won't have much utility there.

@jvillalobos would it be possible to just duplicate the featured collections so that it just works for both Desktop and Android?

**Comment by jvillalobos** [comment]
I'd prefer not to do that because (1) it's likely many of those add-ons won't work well / at all on Android and (2) it's likely the Android collections will quickly become outdated and be of little use for users. If Scott thinks this is viable, I'm okay going this direction. Otherwise I'd rather not have it be a search filter.

**Comment by eviljeff** [comment]
>  (1) it's likely many of those add-ons won't work well / at all on Android and (2) it's likely the Android collections will quickly become outdated and be of little use for users. 

We're talking about themes here - unless you're featuring "happy new year 2019" it's probably not going to be outdated that quickly.  If one doesn't work on Android then just don't add that theme to the Android featured collection.

**Comment by devaneymoz** [comment]
I've created a distinct collection "Featured Themes for Android":

https://addons-internal.prod.mozaws.net/firefox/collections/4757633/mobile/

However I have no Android testing device so I cannot confirm each theme's compatibility.

**Comment by AlexandraMoga** [comment]
The collection does exist if you search for its details by direct URL: https://addons.mozilla.org/en-US/android/collections/4757633/mobile/

However, when you perform a search and set filters for Themes + featured, there are no results returned:

https://addons.mozilla.org/en-US/android/search/?featured=true&type=statictheme%2Cpersona

![image](https://user-images.githubusercontent.com/31961530/52063080-8343b080-257a-11e9-89d1-415647326273.png)

**Comment by eviljeff** [comment]
Mmm, yes, https://addons.mozilla.org/api/v4/addons/search/?type=statictheme&app=android&featured=true and https://addons.mozilla.org/api/v4/addons/featured/?app=android&type=statictheme confirms they're not being set as featured.

**Comment by eviljeff** [comment]
After much (**much!**) playing around in /admin @wagnerand set the collection to featured (and the slug changed to https://addons-internal.prod.mozaws.net/firefox/collections/4757633/android)

**Comment by AlexandraMoga** [comment]
Verified fixed in prod with FF65, Android 8.0.

1. Collection details:
https://addons.mozilla.org/en-US/android/collections/4757633/android/

2. Themes homepage:
![image](https://user-images.githubusercontent.com/31961530/52109094-f134ba00-2604-11e9-8354-33e5cdd3fc5f.png)

3. Featured Themes search:
![image](https://user-images.githubusercontent.com/31961530/52109101-f7c33180-2604-11e9-8b39-f8484fabadda.png)
