### ISSUE TITLE
Text incorrectly aligned in dev-hub

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#10493]
### Steps to reproduce
-- the user should have at least one add-on submited
1. Open developer hub while logged in (https://addons.allizom.org/en-US/developers/)
2. Observe the "Not yet rated" and "Last Updated" texts

### Expected result:
The 2 texts are aligned.

### Actual results:
The "Last Updated.." text is a few pixels off.

### Notes:
The issue can be reproduced in FF64 on amo-dev, amo-stage and amo-prod
Screenshot for this issue:
![textnotaligneddevhub](https://user-images.githubusercontent.com/15685441/51609267-552ef280-1f22-11e9-86b7-fadf4d37aef3.png)

**Comment by suhailsinghbains** [comment]
Hi,
Can I please work on this bug?
Thanks

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by suhailsinghbains** [comment]
Hi @diox 
I would like to give this a shot, can you please assign this issue to me
Thanks

**Comment by diox** [comment]
Ok, it's all yours @suhailsinghbains

**Comment by HSR05** [comment]
hello @diox
I would like to resolve this issue. Can you guide me a little. 
Thankyou

**Comment by suhailsinghbains** [comment]
Hi @HSR05 
I completely forgot to send the PR, I had already done the work :laughing: 
Please feel free to checkout [these issue](https://github.com/mozilla/addons-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22)
Cheers

**Comment by ioanarusiczki** [comment]
@diox I verified this on AMO dev and stage with FF65(Win10).

Strange things is that on AMO dev the text doesn't look aligned yet on AMO stage the fix is visible.

AMO dev - text still not aligned 

![amo dev](https://user-images.githubusercontent.com/33448286/53501374-b5322f00-3ab4-11e9-83a8-6630d4d4bc43.png)



AMO stage - fixed issue

![amo stage](https://user-images.githubusercontent.com/33448286/53501237-7dc38280-3ab4-11e9-92cd-3ee73201d227.png)

**Comment by diox** [comment]
> AMO dev - text still not aligned

That was a deploy issue following python3, it should be fixed now. You might need to Ctrl+shift+R to see the new version until there is a new change to the css being deployed to dev.

**Comment by ioanarusiczki** [comment]
Yes, it was a matter of reloading (override cache) thing. All good on AMO dev too.

 
![amo dev after ctrlshiftr](https://user-images.githubusercontent.com/33448286/53554371-3daddf80-3b48-11e9-8cf3-e636b53ecc1a.png)
