### ISSUE TITLE
drop amo-validator

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10502]
amo-validator is only used for legacy addons, which have long since been disallowed for general submission on AMO.  #10445 moved search plugin validator into addons-server directly which was the last remaining type of supported addon handled by amo-validator.  As python3 compatability work is highlighting problems with attempting to use a python2-only package under python3 we may as well just drop it.  The only use case for the amo-validator today is admin-submitted updates to old add-ons, and some system add-ons, both of which should be thoroughly checked for compatablity before upload anyway.

**Comment by EnTeQuAk** [comment]
QA:

This is entirely dropping support for uploading legacy add-ons.

* No legacy add-ons (install.rdf or package.json based) are allowed to upload
 * **except** if they're already signed by Mozilla, then we issue only a warning and allow them to proceed
* Add-ons targeting Seamonkey or Thunderbird will get an additional description in their validation report that these have been moved to a different site.

![screenshot from 2019-02-01 08-50-53](https://user-images.githubusercontent.com/139033/52109822-073f7c00-25ff-11e9-926d-201cd633594b.png)
![screenshot from 2019-02-01 08-50-32](https://user-images.githubusercontent.com/139033/52109823-073f7c00-25ff-11e9-9f69-4fd0a2e1d89a.png)
![screenshot from 2019-02-01 08-50-10](https://user-images.githubusercontent.com/139033/52109824-073f7c00-25ff-11e9-9c2f-bd3e1d9ad84d.png)

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I verified this on AMO dev and AMO stage with FF65 (Win10):

- all legacy add-ons I tested with that contain install.rdf cannot be uploaded. I also tested for install rdf + package.json included. I found issue https://github.com/mozilla/addons-server/issues/2564 that explains that an add-on with a package.json and no install.rdf  is built incorrectly, but I tested it anyway and I've noticed that the message has changed now, I can't tell if it's an issue worthy scenario but if you consider it let me know !

Message when uploading addon with package.json (without install.rdf) on AMO stage

![amo stage no install rdf](https://user-images.githubusercontent.com/33448286/52346376-2176c100-2a28-11e9-8b23-eff43e0a5a32.png)

Message when uploading addon with package.json (without install.rdf) on AMO prod

![amo prod package json deleted](https://user-images.githubusercontent.com/33448286/52346569-86321b80-2a28-11e9-9440-e0193df1a55f.png)

- Signed In Mozilla extensions can only be uploaded by Mozilla accounts with both distribution methods. 
Checking on prod, I could not upload the public version of a signed in sample but this should be fixed when this lands tomorrow.

![signed in on amo prod](https://user-images.githubusercontent.com/33448286/52347429-9a771800-2a2a-11e9-87e6-dcb403926715.png)

- the legacy add-ons targeting Seamonkey or Thunderbird do have an extra message about them being moved to another site.

![extramessage](https://user-images.githubusercontent.com/33448286/52347635-17a28d00-2a2b-11e9-86d7-bd4f9b152361.png)

- dictionaries and lang packs with install.rdf cannot be uploaded anymore (this was until now still possible on all amo servers). 

![legacy language pack](https://user-images.githubusercontent.com/33448286/52347891-b0d1a380-2a2b-11e9-864a-68276099508b.png)

**Comment by EnTeQuAk** [comment]
@ioanarusiczki thanks a lot for the detailed report!

> Message when uploading addon with package.json (without install.rdf) on AMO stage

This indeed shouldn't happen, I'll open an issue and fix it. I don't think it's important enough for a cherry-pick given that the end-result for the user will be the same and only the messaging changes.

> dictionaries and lang packs with install.rdf cannot be uploaded anymore (this was until now still possible on all amo servers).

Perfect, cc @jvillalobos for FYI but we don't have any install.rdf langpacks and dictionaries these days so we should be fine.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Thanks for the feedback!  👍 
I'm marking this issue verified on AMO dev and AMO stage - FF65 (Win10).

**Comment by jvillalobos** [comment]
Yes, we migrated langpacks and dictionaries to WebExtensions packaging so they shouldn't be uploaded in legacy format anymore.
