### ISSUE TITLE
Check safe-list for RTA (Return to AMO) guids

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#10504]
We'd like to check `rta` prefixed links for RTA (Return to AMO) against the list of add-ons that is used for the pool for TAARDIS (recommendations in the disco pane).

If the add-on is in the list then the response should be handed back, if it isn't the result should be a 400 error as it is for a bad guid.

**Comment by diox** [comment]
This would make the search endpoint depend on MySQL, something we've avoided up until now (unless we add the info to ES, and re-index affected add-ons when the editorial list changes) ... It has perf implications, I'm not sure how critical that would be if limited to this particular feature though.

**Comment by AlexandraMoga** [comment]
@diox I suppose that in order to test this I will have to make sure that a request to `https://services.addons-dev.allizom.org/api/v3/addons/search/?guid=rta:GUID-IN-TAARDIS` should return the addon details, while `https://services.addons-dev.allizom.org/api/v3/addons/search/?guid=rta:GUID-NOT-IN-TAARDIS` should return 400.

If the search request is not prefixed by `rta`, there shouldn't be any changes, i.e search results should behave as before.

Also, is there a complete list that I could check which has all TAARDIS addon recommendations for -dev?

**Comment by diox** [comment]
Yes, but note that the guids with rta: prefix need to be base64urlsafe encoded. In addition, the regular kill switches for the feature still apply.

The pool for the taardis recommendations is in /admin/models/discovery/discoveryitem/ ; it can also be returned the [discovery editorial API](https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#editorial-content).

**Comment by AlexandraMoga** [comment]
1. Request made with a guid which is not part of the TAARDIS curated list:
https://services.addons-dev.allizom.org/api/v3/addons/search/?guid=rta:Zm94eXByb3h5QGVyaWMuaC5qdW5n - returns 400 with error message `"Invalid RTA guid (not a curated add-on)"`

2. Request made with a guid from the TAARDIS curated list:
https://services.addons-dev.allizom.org/api/v3/addons/search/?guid=rta:YWRkb25AZGFya3JlYWRlci5vcmc - returns the addon details

3. Normal search request not affected: https://services.addons-dev.allizom.org/api/v3/addons/search/?guid=foxyproxy@eric.h.jung

@muffinresearch do you also want to test this with the kill switch on, to make sure that search requests with a guid prefixed by `rta` will return 400 in any case?

**Comment by muffinresearch** [comment]
@AlexandraMoga for completeness it would be nice, but that requires 3 releases to test due to the env var.

@diox now we have a db lookup here, does that mean for rta related search queries we could move to a db based switch?

**Comment by diox** [comment]
@muffinresearch yes, I don't love it but that makes sense. Please file an issue about it!

**Comment by AlexandraMoga** [comment]
I'm going to wait then for #10557 to be fixed, to have a more practical way of testing that the kill switch also works with the new safe list.

**Comment by AlexandraMoga** [comment]
With the `return-to-amo` switch Disabled, the server will respond with a 400 error - with the message `"RTA is currently disabled"` for search queries made by a `guid` from the TAARDIS safe list.

The previous tests are still working as before.
