### ISSUE TITLE
Translate search API error messages

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10511]
The search API can raise some errors when the parameters being passed are incorrect. For instance, if the client provides an invalid combination of app/type/category parameters, it will return `Invalid combination of "app", "type" and "category" parameters.`

Although these error messages are developer oriented, they could be surfaced by the frontend to users if they manually change query parameters in the URLs. It's fine to keep them relatively technical, but we should translate them just in case.

It's just a matter of finding the `ValueError` being raised in https://github.com/mozilla/addons-server/blob/master/src/olympia/search/filters.py and use `ugettext()` on them.

**Comment by diox** [comment]
Sure, it's all yours if you want to work on it.

**Comment by prajwalshimpi** [comment]
Hi @suhailsinghbains ,
Have you fixed this?
Thanks!

**Comment by suhailsinghbains** [comment]
Hi @prajwalshimpi 
I am still working on it.
Please feel free to checkout this [Issue](https://github.com/mozilla/addons-server/issues/10493)
