### ISSUE TITLE
Weekly content reviewer report did not get sent

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10524]
### Describe the problem and steps to reproduce it:
The weekly content reviewer report wasn't sent out, because the display name for a user was `None`.

### What happened?

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5140376/?query=is:unresolved

### What did you expect to happen?

Should use `Firefox user {user-id}` if `display_name` is `None`.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF65, Win10x64

Both the add-on and content review weekly reports were sent on Monday.
The user without a display name is tracked in the report.

![image](https://user-images.githubusercontent.com/31961530/52339508-04d18d80-2a16-11e9-9e14-d94cac9c50ab.png)
