### ISSUE TITLE
remove email devs support from /zadmin

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10521]
It hasn't been used since Product/Community started using Salesforce, i.e. since the end of 2016 so we can remove it.  There are some test fails under python3 so this would work-around them.

**Comment by AlexandraMoga** [comment]
"Email addon developers"  function removed from admin on AMO -dev:

![image](https://user-images.githubusercontent.com/31961530/51902841-97917d00-23c3-11e9-97fd-41b9c7524346.png)
