### ISSUE TITLE
Consider diff -U1 for the file diffing API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#10532]
The [react-diff-view](https://github.com/otakustay/react-diff-view) component that we're looking to use on the frontend says this:

> For best display effect, you should generate your diff text with `git diff -U1` command.

I'm not too familiar with `-U1` and I'm not sure why it suggests using it but does that sound reasonable to do on the backend?

From `git --help`:

> `-U<n>, --unified=<n>`
> `   Generate diffs with <n> lines of context instead of the usual three. Implies -p.`

**Comment by EnTeQuAk** [comment]
Yes, #10323 will already implement a unified diff which is the overall default for machine-readable diffs anyway.

I'll keep this issue open and close it separately though as a way of keeping track.

**Comment by willdurand** [comment]
Because of https://github.com/mozilla/addons-code-manager/issues/292, I believe the API should return the whole file, i.e. `-U<number of lines in the file>`.

**Comment by EnTeQuAk** [comment]
I wonder if we want to make this configurable at some point. Does react-diff-view have an option to reduce context lines on it's own or would that require a re-request on the API?

**Comment by willdurand** [comment]
> I wonder if we want to make this configurable at some point. Does react-diff-view have an option to reduce context lines on it's own or would that require a re-request on the API?

It does not look like this lib provides such a feature. It is doable and there are tools to do that, but we have to implement it (plumbing vs porcelain).

**Comment by EnTeQuAk** [comment]
> It does not look like this lib provides such a feature. It is doable and there are tools to do that, but we have to implement it (plumbing vs porcelain).

re-requesting through the API sounds more reasonable then I guess, I already have all the necessary context anyway.

In any case, this won't be needed for the MVP I think.

**Comment by willdurand** [comment]
I don't think we should even consider that feature (reduce context lines) because it is not implemented in the existing tool.

**Comment by EnTeQuAk** [comment]
Let's close this for now then and see if we need that at all.
