### ISSUE TITLE
Hide deleted users from weekly reviewer report

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10530]
Deleted users should not show up on the weekly reviewer report.

**Comment by AlexandraMoga** [comment]
Same as #10524 , I have approved/rejected addons with a user which is now deleted, but I won't be able to verify that the reviewer report skips this user until the next report is generated on Monday.

**Comment by AlexandraMoga** [comment]
Deleted users are hidden from the Add-on reviews report, but they are still listed in the Content Review report:

![image](https://user-images.githubusercontent.com/31961530/52339610-47936580-2a16-11e9-9316-baaaf7bc6640.png)

@wagnerand to you want me to file a follow up for that?

**Comment by wagnerand** [comment]
@AlexandraMoga That user is not deleted, but it doesn't have a display name set. It's the user with the user id 10641840.

**Comment by AlexandraMoga** [comment]
@wagnerand  hm...I thought it was user 10641846, which I have deleted for the purpose of this test.

Looking at the review log, there doesn't seem to be any activity for user 10641840 last week:

https://reviewers.addons-dev.allizom.org/en-US/reviewers/reviewlog?start=2019-01-28&end=2019-02-03&search=

Maybe I'm missing something?

**Comment by wagnerand** [comment]
@AlexandraMoga Since you are looking at the stats for this quarter, you need to expand your search: https://reviewers.addons-dev.allizom.org/en-US/reviewers/reviewlog?start=2019-01-01&end=2019-02-03&search=username789 (username789 is the username for user id 10641840.)

**Comment by AlexandraMoga** [comment]
Oh, I see. I misread the report. On a closer look, I'm wondering now why aren't any reviewers listed at the top?
![image](https://user-images.githubusercontent.com/31961530/52346902-5e8f8300-2a29-11e9-8208-4df058b78938.png)

Also, for the quarterly report, shouldn't we have then `Firefox user 10641840` instead of a blank space, if there is no display name set?

**Comment by wagnerand** [comment]
> Oh, I see. I misread the report. On a closer look, I'm wondering now why aren't any reviewers listed at the top?

I assume there we no reviewers who did at least 5 reviews that week.

> Also, for the quarterly report, shouldn't we have then `Firefox user 10641840` instead of a blank space, if there is no display name set?

I simplified things a bit in my previous comment. That user does in fact have a display name set but it is "" (empty string). Checking for that adds complexity to the queries I am using and I think that's something we can deal with manually by just reaching out to the reviewers and question and ask them to set a proper display name, since it will be used in other places too, like the review log for example.

**Comment by AlexandraMoga** [comment]
> I assume there we no reviewers who did at least 5 reviews that week.

That could indeed be my problem.

Obviously, you and the other reviewers are the end users of these reports, so, if you're happy with the current set-up, there's no point in adding more complexity to it,

At least, the reports are being sent now, which is good.
