### ISSUE TITLE
versioncheck theme update endpoint keeps failing after LWT migration

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#10533]
### Describe the problem and steps to reproduce it:
We have been monitoring the availability of the versioncheck theme update endpoint using the following URL:

https://versioncheck.addons.mozilla.org/en-US/themes/update-check/563188

However, this location seems to have gone after LWT migration. The monitor is now getting constant 404.

Can you recommend a different URL for us to use (to monitor the health of the `/themes/update-check/` endpoint? Or is it that with the LWT migration done, we no longer need to monitor this endpoint?

A brief glance of the access log files shows that almost all access to `https://versioncheck.addons.mozilla.org/en-US/themes/update-check/xxxxxx` returns 404.

### What happened?
LWT migration done last week. This may be related.

### What did you expect to happen?
A new end point to monitor the health of `/themes/update-check/` location. Or let us know if it no longer needs to be monitored.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by bqbn** [comment]
OK, so it sounds like `/themes/update-check/xxxxxx` is for monitoring LWTs, and since most of the LWTs are migrated, 404 is expected. Is that correct?

If that is the case, what would be a recommended endpoint for us to monitor static themes? For example, how do we monitor the availability of the static theme whose LWT ID was 563188 before the migration?

> #9941 will re-enable the update-check migration from LWT to static themes

I'm not sure what "re-enable" means. Does it mean we need to run `./manage.py process_addons --task=migrate_lwt` command again sometime later?

**Comment by eviljeff** [comment]
> OK, so it sounds like /themes/update-check/xxxxxx is for monitoring LWTs, and since most of the LWTs are migrated, 404 is expected. Is that correct?

yes

> If that is the case, what would be a recommended endpoint for us to monitor static themes? For example, how do we monitor the availability of the static theme whose LWT ID was 563188 before the migration?

static themes don't use a special endpoint - it's just the standard add-on update service.

>>  #9941 will re-enable the update-check migration from LWT to static themes

> I'm not sure what "re-enable" means. 

#9762 disabled the code added in #7976 that served details of the static theme when the LWT update service was called; #9941 will re-enable it again.

**Comment by bqbn** [comment]
OK, based on what's said, we'll stop monitoring `/themes/update-check/xxxxxx` for now. We'll continue to monitor `/update/VersionCheck.php` endpoint, which sounds like is where static themes are.

Let me know if that's OK with you guys, otherwise I'm closing the issue for now.

Thanks a lot for the info.
