### ISSUE TITLE
Redis high CPU usage for a few hours once a day

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#10531]
### Describe the problem and steps to reproduce it:
Our redis instance started to have an unusual CPU usage pattern since last Saturday (1/26). Every day at around 08:30 am UTC, the CPU usage jumps from below 1% to 20%, and last for a few hours.

https://app.datadoghq.com/dash/831458/amo?screenId=831458&screenName=amo&from_ts=1548471476417&is_auto=false&live=false&page=0&tile_size=m&to_ts=1548680357681&fullscreen_widget=326510871

<img width="1582" alt="screen shot 2019-01-28 at 10 34 18 am" src="https://user-images.githubusercontent.com/2209111/51857991-7ad44700-22e8-11e9-84ed-7138ea360d75.png">

It may be worth noting that the period of time of  20% CPU is increasing during the three days.
  * 1/26 for ~2 hours
  * 1/27 for ~5.5 hours
  * 1/28 for ~6 hours

### What happened?
It's not immediately obvious what have caused this. We suspect it might be related to the recent LWT migration, which started on 1/22, and finished on 1/26 at 14:30 UTC.

Could it be possible that the LWT migration caused some cron job [[1]](https://github.com/mozilla/addons-server/blob/master/scripts/crontab/crontab.tpl) to use more redis CPU than before?

### What did you expect to happen?
Typically, our redis CPU usage is very low, (constantly below 1% for the past 3 months). Thus this sudden increase of 20% for a few hours is definitely not normal.

Can we identify the cause to this, and hopefully bring the redis CPU usage pattern back to its normality? 

### Anything else we should know?
There wasn't infrastructure level changes last week. Only operative thing happened last week was running the LWT migration.

**Comment by bqbn** [comment]
The described CPU spike continued to happen today, and it lasted about 7.5 hours this time. It would be nice to get some help and see what's causing this.

**Comment by EnTeQuAk** [comment]
This is really interesting unless I'm mistaken redis is *only* used by celery as a result backend where task results are stored.

Do you see any spikes in tasks being created during that time?

Since when started that to happen? Do the times match our or other stats tasks maybe?

**Comment by EnTeQuAk** [comment]
![screenshot from 2019-01-30 06-59-25](https://user-images.githubusercontent.com/139033/51961502-3b7b3700-245d-11e9-93ff-5c4741b2f34e.png)

Now this matches your pattern… That's quite hard to debug now though, `index_addon` can be called by a lot of things…

**Comment by eviljeff** [comment]
> On the other hand, this seems to match lwt migration since it pauses all indexing tasks during the migration and then starts them, but that happens in batches of 100, or what batch size did we use 

we did use a batch size of 100, though we changed the celery pauses to be per iteration (the tasks are stopped just before each migration, and restarted just after each migration now; rather than stopping at the start of the 100, and restarting after the 100 finished)
