### ISSUE TITLE
Auto-approval not working on -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10543]
STR:

1. Submit a new extension
2. Check its approval status after ~5 min

Actual result:
Extension status is 'Awaiting review'

Expected result:
Extension status is 'Approved'

Notes:
- repoduced only on AMO -dev with FF65, Win10x64

@EnTeQuAk could this have anything to to with the autograph work ?

**Comment by EnTeQuAk** [comment]
Indeed, I thought I disabled it but apparently the command line interface of waffle is kinda broken so it simply didn't… 

I disabled it now, mind checking again?

**Comment by AlexandraMoga** [comment]
Yes, it's working now.
Thanks!
