### ISSUE TITLE
Remove disallow-legacy-submissions waffle-switch

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10554]
Once #10553 lands we can remove that waffle-switch. It's mostly unused then, there may still be some references in unittests so this needs checking.

**Comment by eviljeff** [comment]
there are no references to `disallow-legacy-submissions` in code at this point

**Comment by EnTeQuAk** [comment]
Should still be removed from the database, no?

**Comment by championshuttler** [comment]
Hi @EnTeQuAk I would like to work on it, can I take this up?

Here we need to remove the `disallow-legacy-submissions` column from `waffle_switch` table if I am not wrong. Please correct me if something missing. Thanks

**Comment by EnTeQuAk** [comment]
Correct, there are a few other migrations that remove waffle switches already so you can take inspiration from there.

Let us know if you have any questions.
