### ISSUE TITLE
Add-on screenshot images need a maximum width/height

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#10551]
ref: https://github.com/mozilla/addons-frontend/issues/7395

I noticed that the following add-ons have images that are shown on pop-up wider than my screen thus cropping parts of the image and no method to scroll.

Screenshot:
https://postimg.cc/4YwSNthq

More examples:
```
https://reviewers.addons.mozilla.org/reviewers/review/1022521/
https://reviewers.addons.mozilla.org/reviewers/review/1077617/
https://reviewers.addons.mozilla.org/reviewers/review/1022483/
https://reviewers.addons.mozilla.org/reviewers/review/997321/
https://reviewers.addons.mozilla.org/reviewers/review/1013926/

```

**Comment by HSR05** [comment]
is this issue still open? can i work on it? @eviljeff

**Comment by eviljeff** [comment]
@HSR05 it's still open, though it's in the reviewer tools meaning you will have to get addons-server running locally first to be able to develop the fix.  If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by RachitG001** [comment]
@eviljeff can i pick this up?

**Comment by eviljeff** [comment]
> @eviljeff can i pick this up?

If you want.  You'll need to get addons-server running locally and replicate with the reviewer tools (with an add-on submission that has an overly large screenshot set in developer tools).
