### ISSUE TITLE
Extract source files asynchronously

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10566]
We are extracting regular uploads asynchronously, we should do the same with source-file uploads.

**Comment by EnTeQuAk** [comment]
Yes correct, only source code uploads.

Feel free to post a few add-ons where you recently uploaded some source codes and I'll check on the server if everything works.

Thanks!

**Comment by AlexandraMoga** [comment]
@EnTeQuAk you can check these out:

Unlisted: https://addons-dev.allizom.org/en-US/developers/addon/eef69ee9cd234cf3bd9d/edit
Listed: https://addons-dev.allizom.org/en-US/firefox/addon/momentum-dev/
Listed: https://addons-dev.allizom.org/en-US/firefox/addon/colorzilla-dev/
Listed: https://addons-dev.allizom.org/en-US/firefox/addon/tineye-reverse-image-search/

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk you can check these out:

Perfect, I looked at them and everything worked as expected.
