### ISSUE TITLE
file PRs against dependencies that seem to be py3 compatable but don't advertise it

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10572]
follow-up from #4997
@diox said:
> As a final task, maybe we could raise pull requests against the projects that don't advertise their Python 3 support ? Adding the relevant info to the classifiers in their setup.py files ?

https://pyup.io/account/repos/github/mozilla/addons-server/

- [x] filelock ==3.0.10 - travis.yml indicates it is py3 compatible.
- [ ] futures ==3.2.0 - just a backport of py3 functionality to py2
- [ ] pathtools ==0.1.2 - pretty unmaintained but is seemingly only used by Celery, which is py3 compatible so safe to ignore.
- [ ] hawkauthlib ==2.0.0 - repo pull requests and tox.ini indicate it is py3 compatible.
- [x] PyFxA ==0.5.0 - repo pull requests and travis.yml indicate it is py3 compatible.

**Comment by EnTeQuAk** [comment]
There's a few more on the list, actually:

*  sphinxcontrib-serializinghtml 
*  sphinxcontrib-applehelp 
*  sphinxcontrib-devhelp 
*  sphinxcontrib-htmlhelp 
*  sphinxcontrib-qthelp 

Although I'm even unsure if we're using them and could maybe just remove them?

Quite interestingly ` yara-python ` isn't marked as python compatible either.

Small updates on this, `pyfxa` is now marked as python 3 compatible. `futures` isn't in our requirements anymore, and `filelock` is now marked too.

**Comment by EnTeQuAk** [comment]
`yara-python` should be fine though, there are enough tests against all versions of python 3.

As mentioned in IRC, let's just close this issue for now.
