### ISSUE TITLE
Addons installed on firefox for Android are not always able to update. 

### ISSUE THREAD

**Issue by creesch** [mozilla/addons-server#10580]
**This is *not* a duplicate of #10398 even though they reference the same bugzilla issue.** Rather they are two seperate (but related issues) that are the result of that issue. 

This is likely related to this frontend issue. 

https://github.com/mozilla/addons-frontend/issues/6136

### Describe the problem and steps to reproduce it:
The AMO frontend allows all webextensions to be installed regardless of them being marked compatible with Firefox for Android or not. 

### What happened?
This results in extensions that installed but not updated. Likely due to the backend through the update URL does not allow Firefox for Android to request incompatible extensions. (This is pure conjecture as I don't know how to properly check this). 

### What did you expect to happen?
I expect extensions to update as they are installed. Not having them update seems like a potential security issue in the making. 
Ideally they should not be installed but that did happen and I can only assume that it did happen with a lot of people due to how easy it is to install incompatible addons from AMO. As that is the case you don't want all those addons being blocked from updating. 

### Anything else we should know?
I first thought this was a Firefox for Android issue but got redirected [from this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1519725) to here.

**Comment by creesch** [comment]
Well, I'd like to see this resolved. Not sure what details can be added though.

**Comment by diox** [comment]
Fenix is going to change how [add-ons will work in Firefox for Android](https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/) and compatibility will be enforced in a stricter way.
