### ISSUE TITLE
Large addon package causes server error during signing

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10590]
Follow up for #9308 

STR:
1. Submit a large add-on package on AMO -dev  - size larger than **70Mb**
2. Opt for the unlisted distribution to better catch the error
3. Click on the `Sign Add-on` button

Actual result:
The signing process fails with a server error (500)

Expected result:
Add-on is correctly signed

Notes:
- if the add-on is submitted as listed, it will remain with status "Awaiting review" (not auto-approved)
- reproduced on AMO -dev with FF65, WIn10x64
- I have artificially incremented the size of my add-on by adding large pictures

![image](https://user-images.githubusercontent.com/31961530/52218736-f499a100-28a3-11e9-9790-01dbfdcbce93.png)

**Comment by EnTeQuAk** [comment]
We already quickly talked about that in IRC, @g-k mentioned increasing the HAWK authentication token clock skew tolerance.

**Comment by g-k** [comment]
Nice find! We ran into this signing larger APKs too.

Bumped up the hawk timestamp validity for stage and prod in hiera-sops commit 992e5e9e108a2f26da0438475711d958edc73b54. Need to redeploy to those envs.

TODO: 

- [ ] figure out how to update autograph -dev to

**Comment by g-k** [comment]
Updated dev (deploying to dev is broken) and redeployed to stage. Will deploy to prod at some point (but feel free to remind me).

Dev now has:

```
curl http://localhost/__version__
{"commit":"b361e521227c5971e71195daddd9c7c9aa08e417","version":"2.8.1","source":"https://github.com/mozilla-services/autograph","build":"https://circleci.com/gh/mozilla-services/autograph/1854"}
```

So this should be fixed in autograph -dev and -stage.

**Comment by EnTeQuAk** [comment]
Awesome, thanks @g-k for the help. I'm closing this for now then.

**Comment by AlexandraMoga** [comment]
I haven't run into signing errors anymore.

@EnTeQuAk  however, our server begins to act out a bit if I'm trying to upload larger files.
There are two intermittent errors I've run into so far, with packages between 60Mb and 130Mb: either a 502 response from nginx, either the following validation error:

![image](https://user-images.githubusercontent.com/31961530/52273368-5284c200-2952-11e9-970a-aff2afb0a71f.png)

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  sorry, yes. This is on -dev.
