### ISSUE TITLE
The legacy site is displayed if the page is refreshed after a search query 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10608]
Moved from https://github.com/mozilla/addons-frontend/issues/7547
Regression from https://github.com/mozilla/addons-server/issues/10428

STR:

1. Open AMO -dev homepage
2. Perform a blank search
3. Refresh the search results page

Actual result:
The legacy site is displayed

Expected result:
The new frontend is displayed

Notes:
- reproduced on AMO -dev with FF65, Win10x64
- I could not reproduce with other pages, just with search results

![2019-02-06_10-58-30](https://user-images.githubusercontent.com/31961530/52330553-5837e180-29fe-11e9-9ba9-243f58809f05.gif)

**Comment by bqbn** [comment]
This has to do with the changes made in https://github.com/mozilla-services/cloudops-deployment/pull/2924 that try to address https://github.com/mozilla/addons-server/issues/10428. Requests to `/<locale>/<app>/search` was routed to the legacy site.

This should have been fixed on -dev. Please verify.

**Comment by AlexandraMoga** [comment]
This is working on -dev now:

![2019-02-07_12-15-55](https://user-images.githubusercontent.com/31961530/52404671-3c057480-2ad2-11e9-872b-0b81b9acf796.gif)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF65, Win10x64
