### ISSUE TITLE
Add the `renderer` argument to the `render()` methods of our custom widgets

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10602]
We're seeing this warning:
`/home/travis/build/mozilla/addons-server/.tox/devhub/lib/python3.6/site-packages/django/forms/boundfield.py:41: RemovedInDjango21Warning: Add the `renderer` argument to the render() method of <class 'olympia.addons.widgets.CategoriesSelectMultiple'>. It will be mandatory in Django 2.1.`

It should (hopefully) be trivial to fix, and more importantly should reduce the number of warnings in tests, which in turn should help work around issues like the dreaded error 120 we've been seeing, which seem to be caused by stderr buffering problems.

**Comment by AlexandraMoga** [comment]
Please add a qa:not needed label if there is no QA required.
Thanks
