### ISSUE TITLE
Add test that makes gitignore files are ignored on our side

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10611]

**Comment by AlexandraMoga** [comment]
@willdurand should this be a qa:not needed?
Thanks

**Comment by willdurand** [comment]
> @willdurand should this be a qa:not needed?

No, you can verify this issue. More info in https://bugzilla.mozilla.org/show_bug.cgi?id=1548470

**Comment by AlexandraMoga** [comment]
Access to bug 1548470 is restricted, so I can't fully understand what I should be testing.

**Comment by AlexandraMoga** [comment]
I've verified this issue in https://bugzilla.mozilla.org/show_bug.cgi?id=1548470#c10
