### ISSUE TITLE
Reviewers/{Browse,Diff} API: Implement comments

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10621]
We have to expose comments to the API and (maybe in a second step) allow the API to send comments to the developer directly.

Given that we don't immediately replace the reviewer-tools I wonder what's the best path forward to do that step by step in regards to which tool does what, e.g when and how comments are stored.

I'm not yet sure how to implement this properly, there are two kinds of comments, one that the developer gets notified for (`process public`, `reject`, `reviewer reply`) and one that the developer doesn't (`process comment`).

Then there's the whiteboard (which can also be public or private).

Ideally, I think comments should be saved and pre-filled in the review-form so that you can review the add-on in the code-manager and only click on the relevant "save" action in the reviewer-tools to send out the information.

cc @wagnerand @diox @eviljeff for ideas

**Comment by eviljeff** [comment]
My initial thought is that _all_ the inline comments would be visible by the developer, and process_comment would remain for other comments only.  

Btw, there are additional actions (request super-review and confirm auto-approved) which are also non-developer.

**Comment by eviljeff** [comment]
The review page might need some reworking to split up the two kind of comments more clearly.

**Comment by wagnerand** [comment]
Some of those actions could also be moved into the file-viewer view, similar to what github does. For example, after I left a few comments for the developer, I'd click "Complete review" or something that lets me select the action (approve, confirm approval, reject..).

**Comment by EnTeQuAk** [comment]
Going to close this in favour of the actual project. https://github.com/orgs/mozilla/projects/79
