### ISSUE TITLE
Implement linter validation result serializer

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10620]
In #10322 I only added a link to the linter validation result but thinking about this more I think it makes sense to actually implement a serializer that can control and adjust data as we need it.

@willdurand @bobsilverberg when touching this, does it make sense for you to inline the contents `validation_url_json` into the browse API directly? Otherwise, I may make this a separate endpoint to request results (instead of exposing that URL as I did) or just inline the information. On the other hand, for bigger files, and diffs, that may end up being quite a bit of content so retrieving it in a second step sounds reasonable to me.

**Comment by bobsilverberg** [comment]
As I understand it, we'll only need this information when looking at a specific file - is that correct? If so then I think it makes sense to inline it with the API response that returns the file's contents. @EnTeQuAk and I also discussed today having a separate endpoint for an individual file (which could include its contents and this validation info) apart from an endpoint that returns the file entries used to build the file tree.

**Comment by kumar303** [comment]
@EnTeQuAk we realized that we do need to get the linter result from a separate endpoint because the compare/diff view also needs to show linter messages. Thus, we can begin using the existing `validation.json` URL. No need to prioritize a new endpoint over that one.
