### ISSUE TITLE
Add `addon` object in Browse API response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#10624]
It would be nice to have a few `addon` fields in the [Browse API response](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse). Ideally, it should be an `addon` object with the `name` and `slug` of the add-on (for now).

**Comment by EnTeQuAk** [comment]
Fixed in #10634

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

For the following request:

https://addons-dev.allizom.org/api/v4/reviewers/browse/1541783/

![image](https://user-images.githubusercontent.com/31961530/52567478-18fdfc00-2e15-11e9-93d1-72fc5b58ca38.png)
