### ISSUE TITLE
The /collections/<userId>/ page is returning a 404

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10638]
Regression from #10428 

STR:

1. Log in to AMO dev
2. Navigate to a page served by the legacy site - i.e  `/developers/`
3. Select My Collections from the user drop down menu

Actual result:
A 404 is returned because https://addons-dev.allizom.org/en-US/firefox/collections/10641755/ is not implemented in the new frontend. The link serving user collections is instead  https://addons-dev.allizom.org/en-US/firefox/collections/

Expected result:
Remove the option to navigate to My Collections from the legacy site (?)

Notes:
- reproduced on AMO -dev with FF65, WIn10x64

![2019-02-08_12-40-43](https://user-images.githubusercontent.com/31961530/52473568-cc10f000-2b9e-11e9-8d39-3d9a85e2a715.gif)

**Comment by eviljeff** [comment]
The problem here is https://addons-dev.allizom.org/en-US/firefox/collections/ on legacy frontend is a list of all collections (just featured collections now) but on new frontend it's your own collections.  But I suppose we can drop the former entirely now.  If we want old bookmarks to work we'll either need something in nginx or addons-frontend though.

**Comment by bobsilverberg** [comment]
We discussed in the standup that this should just redirect to the "My Collections" page on frontend (`/collections`) to support the case when a user is trying to look at their own list of collections. Otherwise this is just an invalid URL.

What do you think @jvillalobos?

**Comment by jvillalobos** [comment]
Agree.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos.

I think this can be done via nginx - is that correct @bqbn?

**Comment by bqbn** [comment]
I added an Nginx rule that does the redirection. Please test it.

@eviljeff do you think we should remove `/collections/<userId>/` from the legacy site all together? If so, we can drop the priority of this issue instead of closing it.

**Comment by eviljeff** [comment]
> @eviljeff do you think we should remove `/collections/<userId>/` from the legacy site all together? If so, we can drop the priority of this issue instead of closing it.

@bqbn we should remove the link but that _would_ be closing this issue - what do you mean about dropping the priority?  Also, we will still need the redirect because `/collections/<userId>` was previously a publicly accessible page so possibly linked externally.

**Comment by bqbn** [comment]
@eviljeff I was thinking if `/collections/<userId>/` is removed, then I can remove the corresponding Nginx redirection rule. Now that you mention the endpoint is publicly accessible, we should probably keep the nginx redirection rule (at least for a while).

I said "dropping the priority" because I didn't know how soon you'd like to remove `/collections/<userId>/` from legacy site. It looks like it's already happening. 👍

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO-dev with FF65, Win10x64

1. If the _signed in_ user is accessing the collections page from the user menu on the legacy site, the redirect to the new fronted `/collections/` listing page will take place [1];

2. if the _signed in_ user accesses the `/collections/<userId>/` page from a direct link - i.e a saved bookmark, the redirect to the new fronted `/collections/` listing page will take place;

3. if the _logged out_ user is accessing `/collections/<userId>/` page from a direct link - i.e a saved bookmark, the redirect to the new fronted `/collections/` takes place and the user is prompted to sign in: [2].

[1]
![2019-02-18_16-10-36](https://user-images.githubusercontent.com/31961530/52956765-caaea700-3398-11e9-9ee6-d4dc715735c7.gif)


[2]
https://addons-dev.allizom.org/en-US/firefox/collections/10640485/

![image](https://user-images.githubusercontent.com/31961530/52956747-bcf92180-3398-11e9-88a7-8a07bd2a76fd.png)
