### ISSUE TITLE
Throw better error if manifest.json is not at the root of the file

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10635]
Refs https://github.com/mozilla/addons/issues/896 and has been an issue since #10553 

We do actually throw a proper `ValidationError` but for some reason it's overwritten and not exposed to the end-user.

```
{"EnvVersion": "2.0", "Type": "z.devhub.task", "Severity": 3, "Fields": {"msg": "Unhandled error during validation: ValidationError([u'No install.rdf or manifest.json found'])", "remoteAddressChain": "", "traceback": "Uncaught exception:\n  File \"/code/src/olympia/devhub/tasks.py\", line 164, in wrapper\n    data = fn(id_or_path, **kwargs)\n  File \"/code/src/olympia/devhub/tasks.py\", line 210, in validate_file_path\n    data = parse_addon(path, minimal=True)\n  File \"/code/src/olympia/files/utils.py\", line 1087, in parse_addon\n    parsed = parse_xpi(pkg, addon, minimal=minimal, user=user)\n  File \"/code/src/olympia/files/utils.py\", line 965, in parse_xpi\n    xpi_info = Extractor.parse(xpi, minimal=minimal)\n  File \"/code/src/olympia/files/utils.py\", line 169, in parse\n    'No install.rdf or manifest.json found')\n<class 'django.core.exceptions.ValidationError'>\nValidationError([u'No install.rdf or manifest.json found'])\n", "uid": "<anon>", "error": "ValidationError([u'No install.rdf or manifest.json found'])"}, "Timestamp": 1549608531735191040, "Logger": "http_app_addons", "Hostname": "b94399f0c964", "Pid": 37}
```

Error message from addons-linter:
```
  message: i18n._('manifest.json was not found'),
  description: i18n._(oneLine`No manifest.json was found at the root of the extension.
    The package file must be a ZIP of the extension's files themselves, not of the
    containing directory. See: https://mzl.la/2r2McKv for more on packaging.`),
```

Maybe we should adapt that.

**Comment by diox** [comment]
Maybe if we don't detect a `manifest.json`, we should let the linter handle that, and it will raise its own error ?

**Comment by EnTeQuAk** [comment]
> Maybe if we don't detect a `manifest.json`, we should let the linter handle that, and it will raise its own error?

Currently, we go directly into legacy-add-ons validation (and error) when a new upload isn't a WebExtension (contains a manifest.json) which is where this problem comes from.

I wanted to explicitly not run legacy add-ons through the linter.

We do already have proper linting and error messages in case `manifest.json` can't be found, we just need to surface them to the user, which is what this issue should be about.

**Comment by wagnerand** [comment]
Given the amount of reports (see also https://github.com/mozilla/addons/issues/896), we should probably get to this sooner rather than later.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF65, Win10x64

Add-ons that are not correctly packed are throwing a clear error message now:

![image](https://user-images.githubusercontent.com/31961530/54126725-ea257680-4410-11e9-80ef-604bfdeefddd.png)
