### ISSUE TITLE
Display and layout issues in all Statistics pages after "For last" customization

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1063]
Steps to reproduce:
1. Load AMO-stage Statistics page for an addon ( i.e. https://addons.allizom.org/en-US/firefox/addon/adblock-plus/statistics/ )
2. Change the "Custom..." period from "For last" menu option
3. Go to other statistics page (i.e Downloads)

Expected results:
There are no display or layout issues.

Actual results:
No option is selected in the For last/Group by menu; there is no data or text info in the graph section.

Notes/Issues:
Verified on FF42(Win 7). Issue is reproducing on AMO-stage, dev and production.
Screencast for this issue: http://screencast.com/t/lRCugW3o8ab

**Comment by EnTeQuAk** [comment]
This works for me, maybe it's related to the very very wide timeframe you selected? I actually doubt that too though.

![screen shot 2016-07-07 at 10 18 01](https://cloud.githubusercontent.com/assets/139033/16646788/5ea10b74-442c-11e6-809a-5b448cd418ec.png)

Please feel free to reopen this issue at any time if the issue persists and is reproducible again.
