### ISSUE TITLE
Reviewers/Browse API: Expose add-on name and selected file

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10633]

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  I suppose these changes will be reflected in the [reviewers/browse api](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-browse-(int-version_id)-)

I've retrieved the details for one of the addons I've submitted on -dev:

https://addons-dev.allizom.org/api/v4/reviewers/browse/1541799/?file=background.js
 - the `selected_file` option is exposed when the `file` parameter is included
- the `addon` object is present with the `id` , `slug`, localized `name`  and `icon_url`

Regarding the `file` parameter, when I tried to retrieve a file included in a sub-folder, I received an internal server error.  Is sub-folder file browsing not supported by this parameter?

**Comment by EnTeQuAk** [comment]
> Regarding the `file` parameter, when I tried to retrieve a file included in a sub-folder, I received an internal server error. Is sub-folder file browsing not supported by this parameter?

It certainly is supported, does the file exist in the version you uploaded?

In any case, I'll file an issue to throw a proper error for keys that don't exist in the package. (https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5199132/?query=is:unresolved)

**Comment by AlexandraMoga** [comment]
There was indeed something wrong with the first add-on I've tested with.
I've re-verified with a few more examples and the results are looking good now.

https://addons-dev.allizom.org/api/v4/reviewers/browse/1541783/?file=lib/jPicker/jpicker-1.1.6.min.js

@EnTeQuAk do you want me to file a follow up for the server error received when  keys are missing from the package?
