### ISSUE TITLE
Augment abuse API with new fields for add-on reporting within Firefox

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10643]
PRD: https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit?ts=5c4b6e8d#heading=h.af3x6jga7lsy

The Firefox Add-ons Manager is going to implement an abuse report feature similar to the existing one on AMO. To that end we need to add some fields to the [current abuse API](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html) to store additional data that can be sent by Firefox. The PRD specifies we want the following fields (need to sort out how to reconcile this with the current API):

- Client ID hash
- Add-on GUID
- Add-on name
- Add-on summary (description field in manifest)
- Add-on version
- Signature state (curated, non-curated, partner, unsigned, temporary installation)
- Application (Firefox, Firefox for Android)
- Application version
- Application locale
- Operating system
- Operating system version
- Install date
- Abuse report flags (malware, spam, broken search, broken new tab, broken websites, etc.)
- Abuse report text
- Region (tbd - fwiw the current model stores the ip address directly)
- Install origin
- Install method
- Entry point (post-uninstall prompt, options menu, context menu, etc.)

**Comment by diox** [comment]
One key difference with the current API is that we really want the clients to pass the add-on guid/name because it should work with unlisted add-ons. Potentially it should be able to deal with add-ons that are not in the database for some reason (even unlisted).

**Comment by diox** [comment]
QA: make sure current abuse reporting still works using the frontend. You can also play with the new fields in [the API](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html) (see "Request JSON object") and make sure they work, but atm they are not exposed in anywhere except in the return value of the API calls.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF65, Win10x64 and Android 8.0
- addon abuse reporting is still working as expected on the frontend
- I've also played a bit with the api, to make sure that the new added request fields are not breaking anything - I've used a `null` value for those fields that still need to have their values defined

To be clarified:
1.  `application_version` is missing from the documentation, both in the Request and Response JSON objects - however, this field is returned in the response with a `null` value
2. the `client_id` doesn't have any input restrictions - should it not allow only a hashed value of the user's client id?
3.  probably an obvious answer: I suppose that most of the request fields will be populated automatically when an abuse report is posted,  the user having control over the `message` and `reason` fields?

@diox please have a look at these results and let me know if any of them needs a follow up issue.

**Comment by diox** [comment]
> `application_version` is missing from the documentation, both in the Request and Response JSON objects - however, this field is returned in the response with a `null` value

Good catch, I'll add it. It's a free-form string, any value is accepted and stored.

> the `client_id` doesn't have any input restrictions - should it not allow only a hashed value of the user's client id?

It seemed overkill. Note that it is restricted to 64 characters.

> probably an obvious answer: I suppose that most of the request fields will be populated automatically when an abuse report is posted, the user having control over the `message` and `reason` fields?

Right (reason will probably be selected with a dropdown, and message will be a text input).

**Comment by AlexandraMoga** [comment]
I've verified that `client_id` will accept no more than 64 characters. 

Since the missing `application_version` will be handled in a separate issue, I'm going to mark this one as verified fixed.
