### ISSUE TITLE
Gradually add mypy typing

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10642]
After we're done with our Python 3 migration, #9274 and our old legacy views we may want to talk/try to add [mypy](https://mypy.readthedocs.io/en/latest/) typing.

It'll make development easier in the long term and avoid easy-to-miss errors.

**Comment by eviljeff** [comment]
Does mypy typing give us much/anything over type hints in python 3.7? https://www.python.org/dev/peps/pep-0484/ https://github.com/python/typing

**Comment by EnTeQuAk** [comment]
Yes, mypy sits on top of `typing` and is actually part of PEP 0484. `typing` provides the necessary type hints and apis and mypy the actual (static) type-checking parts.

**Comment by Abhi-khandelwal** [comment]
@EnTeQuAk , Can I work on this issue ?

**Comment by eviljeff** [comment]
@Abhi-khandelwal you _can_ but it's a very undefined task, and not particularly exciting (unless you really like static typing and python).  I'd advise looking at another issue tbh.

**Comment by EnTeQuAk** [comment]
This won't be happening anytime soon, as such I'm closing it.

**Comment by Abhi-khandelwal** [comment]
Ok @eviljeff :)
