### ISSUE TITLE
URL `/addon/:slug/versions/:versionId/` is not redirected anymore

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#10645]
I found a new issue with this URL (found in the Dev Hub): https://addons-dev.allizom.org/en-US/firefox/addon/guarani-paraguay-lang-pack/versions/66.0buildid20190207161357/

The new frontend does not support URLs like this, we only support `/addon/:slug/versions/`.

@bobsilverberg @muffinresearch do you remember any decision about that? (i.e. about not supporting a URL for a specific version of an add-on).

_Originally posted by @willdurand in https://github.com/mozilla/addons-server/issues/10428#issuecomment-461726490_

**Comment by willdurand** [comment]
> @bobsilverberg @muffinresearch do you remember any decision about that? (i.e. about not supporting a URL for a specific version of an add-on).

The django view actually implements a redirect: https://github.com/mozilla/addons-server/blob/60dd98e48fb22c7b3ea04d628dacdf9bdac7db87/src/olympia/versions/views.py#L68-L71

That's why we did not have to implement a new page in addons-frontend.

The short-term fix would be to add such a redirect rule at the nginx level but ideally, having proper support in addons-frontend would be nice.

_Originally posted by @willdurand in https://github.com/mozilla/addons-server/issues/10428#issuecomment-461739005_

**Comment by bobsilverberg** [comment]
> @bobsilverberg @muffinresearch do you remember any decision about that? (i.e. about not supporting a URL for a specific version of an add-on).

It was not something that we specifically discussed. I don't think it makes sense to have an actual page that represents an individual version, but I agree that we should have something in place to redirect any of those back to the all versions page.

**Comment by eviljeff** [comment]
We can drop the link to a specific version in devhub, but this will need frontend or nginx work to handle the redirect for existing versions.  
On the other hand, if you do continue to support linking to a version (and, IMO, you should as permalinks are a good thing) then please detail what API changes you would need.  (You'll need to do mozilla/addons-frontend#7542 first)

**Comment by bobsilverberg** [comment]
I think we should just redirect any of these requests to the All Versions page, as we don't currently support a permalink for a specific version. 

What do you think @jvillalobos?

**Comment by jvillalobos** [comment]
Yes, I don't think we should keep that feature (and tbh I didn't know it was a thing), so a redirect to All Versions would be good.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos.

I think we can do this via nginx - is that correct @bqbn?

**Comment by bqbn** [comment]
I added an Nginx rule that does the redirection. Please test it.

@eviljeff do you think we should remove `/addon/:slug/versions/:versionId/` from the legacy site all together? If so, we can drop the priority of this issue instead of closing it.

(We have so many rules for Nginx now and less rules make it easy to manage and run faster.)

**Comment by eviljeff** [comment]
@bqbn sure, we can remove the view and links to the view from devhub (and anywhere else in addons-server) - I'll assign myself to this issue to do that.  

More generally though, if there's a problem in adding a growing number of redirect rules to nginx perhaps we should adopt a policy where redirects are handled in the appropriate project rather in nginx.  I.e. anything under /developers, /reviewers, or /admin should be handled in addons-server (though it may not be practical/possible to do the /reviewers to reviewers.addons.mozilla.org redirect in addons-server); anything under /users, /addons, /collections is handled in addons-frontend.

**Comment by bqbn** [comment]
@eviljeff once https://github.com/mozilla/addons-server/pull/10698 lands in -prod, can I remove the Nginx rule that redirects `/addon/:slug/versions/:versionId/` to `/addon/:slug/versions/`, or should I still keep it?

**Comment by diox** [comment]
@bqbn best to keep it for now.

**Comment by eviljeff** [comment]
Ideally we wouldn't remove them (for a long time) as they were publicly accessible links.  Devhub was the only place we _currently_ exposed them, but legacy frontend had those permalinks on each add-ons all versions page.  But, like I said above, I think perhaps they should be moved into addons-frontend so nginx has the bare minimum.

**Comment by ioanarusiczki** [comment]
@willdurand I tested on AMO dev with FF65(Win10). 
I could not make the URLs not show the version page. I tried with 
https://addons-dev.allizom.org/en-US/firefox/addon/dolphin-2011/versions/#$%^&*()#$%^&*()#$%^&*()#$%^&*()#$%^&*()#$%^&*()#$%^&*()3eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
So, whatever I tried adding after /versions/ including emojis or unicode, the version page is still displayed.

Before (such as on AMO stage), the page was displayed only if a correct version number was added.
Such as https://addons.allizom.org/en-US/firefox/addon/deutsch-de-lang-pack/versions/60.0build1
Any other attempt different than an existing version, would return We're sorry, but we can't find what you're looking for.

AMO dev 

![url on amo dev](https://user-images.githubusercontent.com/33448286/52951766-58839580-338b-11e9-948b-b9f2b2aa9122.gif)

Before - AMO stage 

![url on amo stage](https://user-images.githubusercontent.com/33448286/52951803-6afdcf00-338b-11e9-9169-c69371b9d262.gif)

**Comment by eviljeff** [comment]
@ioanarusiczki yeah that functionality doesn't exist any more - the urls are just redirected back to the versions page; there's isn't anything that looks up the version string and translates it to a page number

**Comment by willdurand** [comment]
Yep, looks good to me

**Comment by ioanarusiczki** [comment]
@willdurand @eviljeff Alright, thanks ! This is verified on AMO dev with FF65 (Win10).
