### ISSUE TITLE
The Author is no longer available for Disco Pane themes or extensions after editing the Custom Heading field from django admin

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10641]
STR:
1. With an admin account login django admin pages and go to Discovery items for Disco Pane
2. Click an extension/theme and edit the Custom Heading field then Save
3. Go to disco pane and notice the changed extension/theme

Actual result:
The edited text is displayed instead of the name (no matter if the Custom addon name is edited too) and the name of the author is no longer available.

Expected result:
The author is still visible and once it is clicked it will open it's detail page on AMO.

Notes:
This issue is reproducible on both AMO dev and AMO stage with FF65 (Win10). 

the field from django pages

![custom addon name](https://user-images.githubusercontent.com/33448286/52483645-1e610980-2bbd-11e9-98b7-ec878ea7705d.png)

and the result on Disco Pane

![disco pane with no author](https://user-images.githubusercontent.com/33448286/52483656-25881780-2bbd-11e9-99b2-2303060fd4e2.png)

**Comment by diox** [comment]
This is by design. When using custom heading, `{addon_name}` contains the dynamically created link with the add-on name (which is itself optionally custom) and author(s). If you don't use it, the author is not included.
