### ISSUE TITLE
Admin links from an addon details page pointing to /reviewers/ or /admin/ are returning a 404

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10659]
Regression from #10428 

STR:
1. Log into AMO -dev with a reviewer or admin account
2. Go to an addon details page - see https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/
3. Scroll down to see the More info card and select any of the options from the Admin Links leading to `/reviewers/` or `/admin/`

Actual result:
A page not found is returned for the following options: Admin add-on status, Admin add-on, Content review add-on, Review add-on code

Expected result:
Requested page is successfully loaded 

Notes:
- reproduced on AMO -dev with FF65, Win10x64

![2019-02-11_17-10-16](https://user-images.githubusercontent.com/31961530/52572206-f1f8f780-2e1f-11e9-8f2e-cf496a4af34d.gif)

**Comment by eviljeff** [comment]
@bqbn are the /reviewers and /admin paths in the nginx config?

**Comment by bqbn** [comment]
I pushed out an update that should have fixed this. Please re-tested it.

**Comment by AlexandraMoga** [comment]
This is working on -dev now:

![2019-02-13_14-24-07](https://user-images.githubusercontent.com/31961530/52711857-96537900-2f9b-11e9-9302-122d0e5f6bbf.gif)
