### ISSUE TITLE
Unable to submit Add-ons because of a validation error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1065]
steps to reproduce:
1. LoaD AMO-stage page https://addons.allizom.org/en-US/firefox/ 
2. Click the "Submit a New Addon" option from Tools
3. Select a valid file and wait for validation

Expected results:
The validation is completed with success. User can continue the submission process.

Actual results:
The validation returns the next error message "JS reflection error prevented validation" twice.

Notes/Issues:
Issue is also reproducing when using the Validator.
Verified on FF42(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Please see the screeshot:
![2015-12-09_1840](https://cloud.githubusercontent.com/assets/15685960/11691581/5c92ebf0-9ea4-11e5-8b35-3be3f2686916.png)
 
Used addon: 
[Simple-Add.zip](https://github.com/mozilla/olympia/files/57050/Simple-Add.zip)

**Comment by EnTeQuAk** [comment]
It appears the zip is broken, I can't unzip it on my machine too, is it double-zipped or so?

**Comment by EnTeQuAk** [comment]
It's actually a rar-file:

```
~/Downloads> file Simple-Add.zip
Simple-Add.zip: RAR archive data, v1d, os: Win32
```

**Comment by ValentinaPC** [comment]
I've used the *.xpi inside the zip/rar. I was not able to add a *.xpi file directly in GitHub.

**Comment by madalincm** [comment]
This issue is still reproducing in stage and currently blocks us from testing large portions of dev hub and  editor tools. It should be fixed as soon as possible. Can someone please have a look at it?

**Comment by andymckay** [comment]
Do you have other add-ons to try? Is this a problem to this specific add-on? I've been able to submit other add-ons successfully onto stage.

**Comment by ValentinaPC** [comment]
I can reproduce this with all my test add-ons, used without problems until this week.
Attaching another. (I've changed the .xpi file 
[Unicode.zip](https://github.com/mozilla/olympia/files/58169/Unicode.zip)

extension to .zip)

**Comment by tofumatt** [comment]
I could submit a simple Jetpack add-on no issues to stage, it seems it's related to contents of that specific add-on (Unicode.xpi); I don't know why though.

**Comment by magopian** [comment]
so @mstriemer traced it back to https://github.com/mozilla/amo-validator/commit/77310377c69b93ffbfb2a0cb3315c7ac91cacb89 which breaks sdk1.0 extensions submissions.

I'm going to tag a new release 1.10.6 which is based on 1.10.4 with @EnTeQuAk's latest changes.

**Comment by magopian** [comment]
https://github.com/mozilla/amo-validator/compare/1.10.4...1.10.6

Also bumped olympia to use this new version. Next tag will need to merge 1.10.5 and 1.10.6 to have @wagnerand's changes.

**Comment by mstriemer** [comment]
The add-on is defining a `let` that is also part of the function arguments which is no longer allowed and hence results in a syntax error.

```js
function exclude(keys, trait) {
  let exclusions = Map(keys),
      result = {},
      keys = getOwnPropertyNames(trait);
  for each (let key in keys) {
    if (!hasOwn.call(exclusions, key) || trait[key].required)
      result[key] = trait[key];
    else
      result[key] = Required(key);
  }
  return result;
}
```

Pasting that snippet into the JS error gives: `TypeError: redeclaration of formal parameter keys`. Perhaps there's a way to get the error message from spidermonkey and use that instead. If there isn't though I think we're stuck for now. Spidermonkey isn't really designed to lint code so it probably doesn't support this use case well.
