### ISSUE TITLE
Implement a management script that extracts versions into git-storage manually

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10651]
We're going to need a script that processes versions that haven't been extracted into git yet.

It should feature the following modes:

* Process all listed versions (only touching versions that haven't been extracted yet)
* Process all unlisted versions (only touching versions that haven't been extracted yet)
* Process one version explicitly (e.g when problems happen and we need manual extraction)
* Force extraction for listed or unlisted versions (e.g when a new storage format gets introduced - like in #10043)

**Comment by AlexandraMoga** [comment]
@EnTeQuAk can we test on -dev and stage that the script is working? If yes, please let me know how you'd like to proceed. 
Thanks
