### ISSUE TITLE
Fix known backwards incompatible changes in django2.0,1,2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10674]
essentially we need to read through:
https://docs.djangoproject.com/en/2.2/internals/deprecation/#deprecation-removed-in-2-0
https://docs.djangoproject.com/en/2.2/internals/deprecation/#deprecation-removed-in-2-1
https://docs.djangoproject.com/en/2.2/releases/2.0/#backwards-incompatible-changes-in-2-0
https://docs.djangoproject.com/en/2.2/releases/2.1/#backwards-incompatible-changes-in-2-1
https://docs.djangoproject.com/en/2.2/releases/2.2/#backwards-incompatible-changes-in-2-2
and identify things that may break.   Even where we appear to use the feature now changed it's possible we won't actually see any difference so probably easier to err on the side of trivial changes only unless/until we get test failures and errors.

**Comment by eviljeff** [comment]
From deprecation section:
* The __search query lookup and the DatabaseOperations.fulltext_search_sql() method will be removed.
* Support for Widget._format_value() will be removed.
* The shim for supporting custom related manager classes without a _apply_rel_filters() method will be removed.
* Model Manager inheritance will follow MRO inheritance rules and the Meta.manager_inheritance_from_future to opt-in to this behavior will be removed.
(already fixed some others with #10666)

**Comment by EnTeQuAk** [comment]
I'm not sure we'll run into backwards incompatibility but https://github.com/mozilla/addons-server/issues/8912 is something to look out for too.

**Comment by eviljeff** [comment]
https://docs.djangoproject.com/en/2.2/releases/2.0/#removed-support-for-bytestrings-in-some-places might cause some fun but there's not much we can do in advance beyond our attempts with #10471 and the fixes in #10671
> To support native Python 2 strings, older Django versions had to accept both bytestrings and unicode strings. Now that Python 2 support is dropped, bytestrings should only be encountered around input/output boundaries (handling of binary fields or HTTP streams, for example). You might have to update your code to limit bytestring usage to a minimum, as Django no longer accepts bytestrings in certain code paths. Python’s -b option may help detect that mistake in your code.
>
> For example, reverse() now uses str() instead of force_text() to coerce the args and kwargs it receives, prior to their placement in the URL. For bytestrings, this creates a string with an undesired b prefix as well as additional quotes (str(b'foo') is "b'foo'"). To adapt, call decode() on the bytestring before passing it to reverse().
```

**Comment by eviljeff** [comment]
Small fixes I'm addressing along the way, but these other things I think we will need to address
* sqlparse is required dependency https://docs.djangoproject.com/en/2.2/releases/2.2/#sqlparse-is-required-dependency
* django.utils.http.urlsafe_base64_encode() now returns a string instead of a bytestring, and django.utils.http.urlsafe_base64_decode() may no longer be passed a bytestring.

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed.
Thanks
