### ISSUE TITLE
Fix codestyle and docs jobs in travis

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10676]
After #10592 the codestyle job isn't actually doing a flake8 check because the `make` invocation is missing the `-f` to specify the correct Makefile.  (It didn't need one before because the recipe was in the primary Makefile before, and now it's in Makefile-docker).
Also the docs job is broken (for an unknown period of time) for the opposite reason - the recipe is in Makefile, not Makefile-docker.

We should fix the things.  Bonus for simplifying and making it so we don't have to do `make -f ...` everywhere in tox.ini

**Comment by EnTeQuAk** [comment]
oh man, don't trust successful outputs :eyes:

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed.
Thanks
