### ISSUE TITLE
Remove amo.utils:smart_path

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1068]
It was introduced in 576151577f57ca053313196a4a007a1b9ba39046 it seems as a python 2.6 compat patch so it could be removed I think.

**Comment by theaverageguy** [comment]
What about the places where this function is being used?

**Comment by EnTeQuAk** [comment]
I think they should use `django.utils.text:force_text` imho or simply be removed if we assume unicode at these places.

**Comment by eviljeff** [comment]
mentor @EnTeQuAk 

Can you add more detail about how to fix this?

**Comment by EnTeQuAk** [comment]
I think it should just use `django.utils.encoding:smart_text` again.
