### ISSUE TITLE
An add-on can end up being approved but not signed

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10693]
https://github.com/mozilla/addons/issues/909 is actually several bugs linked together, this issue is about the last part.

If an add-on somehow manages to get into awaiting review state with no apps (or no Firefox apps) attached to its version, here is what will happen when approving it (via reviewer tools or `auto_approve`):
- It goes through `process_public()`, which [calls `sign_file(file_)`](https://github.com/mozilla/addons-server/blob/39a6b46d894b987d402744b59c30dd4d42de837d/src/olympia/reviewers/utils.py#L641-L643).
- `sign_file(file_obj)` calls `supports_firefox(file_obj)`, finds that the add-on does not support Firefox, [returns without signing](https://github.com/mozilla/addons-server/blob/39a6b46d894b987d402744b59c30dd4d42de837d/src/olympia/lib/crypto/signing.py#L214-L218)
- `process_public()` happily ignores that and set the addon public

The moral of the story is that `process_public()` and other code calling signing should check the return value of `sign_file()`, and do /something/ if it returns `None`, keeping in mind that it can happen inside `auto_approve`, so just blindly raising an exception is wrong. In addition `sign_file()` needs to be changed to not just return `None` when a file is already signed with Mozilla cert (`is_mozilla_signed_extension`). It could return the `File` object in that case.

**Comment by diox** [comment]
QA: check that reviewers approval/auto approval still correctly signs add-ons (including search tools, which are not auto approved) and approves them. 

In addition, get a developer to help you erase an addon compatibility info right after upload (before auto-approval - can use the disable auto approval feature to make sure of this) and try getting it auto-approved: it shouldn't work, but also shouldn't leave the add-on in a weird state where it's approved but not signed.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF65, WIn10x64

I've submitted various addons making sure that all types are covered, I've checked that they are correctly signed after auto-approval or manual approval (for search tools and themes) and that they are can be installed.

@diox helped with the second scenario, which required an addon to have its compatibility erased, and the results were favorable, i.e. the addons were not auto-approved (they were not signed, and remained in Awaiting Review status)
