### ISSUE TITLE
Improve logging regarding reasons why a version would not be auto-approved

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10703]
There are currently 3 things that can cause an add-on not to be auto-approved:
- An exception because there aren't enough files or they somehow don't have validation info attached (also, soon, signing errors)
- Auto-approval is disabled for that add-on
- The add-on was locked because a reviewer had the review page opened

Although we do log that we couldn't auto-approve a version, it's not immediately obvious *why* when looking at the logs. To figure it out, someone has to look at the `AutoApprovalSummary` (which is displayed on the review page) or dig a little deeper. We should improve that and log more explicitly why we didn't approve something.

The first case is logged separately as part of the exception halding, so we only really need to improve the other 2, by logging something when `summary.verdict != self.successful_verdict`.

**Comment by DevJackSmith** [comment]
does this include accidental disabling by user? if not please include as 4th case.

**Comment by diox** [comment]
Disabled add-ons / versions are never considered for approval, so it's not relevant to this issue. You can file a new one for your suggestion - I agree it shouldn't say "by Mozilla", but this is not an entirely trivial change to make (we should have a different status for this - we don't).
