### ISSUE TITLE
remove edit LWT support from AMO

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10728]
Now all LWT have been converted to Static Themes we can drop support in the code base for them.

1st step - stop any remaining rejected LWT from being edited so they can't be resubmitted.

**Comment by ioanarusiczki** [comment]
@eviljeff I tested this issue on AMO dev - FF65(Win10). 

- the edit product page or transfer ownership for a theme artist will redirect to a disabled Edit Product Page where theme cannot be edited further except deleting the theme. 

![lw themes edit page](https://user-images.githubusercontent.com/33448286/53161681-1ba9df80-35d3-11e9-9365-f0cba23313e7.png)

- from admin tools when the link to the  edit page is clicked it's displayed with the same message that theme cannot be edited.

![admin tools redirects](https://user-images.githubusercontent.com/33448286/53161965-b0acd880-35d3-11e9-8dba-e7060dfcd1d9.gif)

- I checked the rev tools to see how the Queues are working for admins and theme reviewers. 
They cannot further process them if themes are individually clicked from the lists (pending for approval, flagged for further reviews, rejected, updated). There's an error message displayed after clicking the "Commit".

![ooops an error](https://user-images.githubusercontent.com/33448286/53162283-5bbd9200-35d4-11e9-9bf2-35d6cf636be8.gif)

The Interactive Theme Queues seem to be still working for approving or rejecting lw themes so I filed an issue here https://github.com/mozilla/addons-server/issues/10743
