### ISSUE TITLE
Stop storing ip_address in abuse reports

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10720]
Split from https://github.com/mozilla/addons-server/issues/10643 - in [the PRD for Abuse Reporting in Firefox](https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit?ts=5c4b6e8d#heading=h.af3x6jga7lsy), @jvillalobos said we should stop storing IP Addresses of abuse reports reporters. 

We should determine the region from GeoIP (assuming we have access to a reliable database for this) and store that instead.

**Comment by EnTeQuAk** [comment]
Why do we even have to store the region of the reporter?

Afaik we were storing the ip-addresses to block abuse-reports abuses.

**Comment by diox** [comment]
Not my decision but I assume it can be useful for context, when reporting add-ons that are specific to a country for instance.

**Comment by jvillalobos** [comment]
The region can be useful to identify trends in reporting, and reporting abuses, to an extent. We haven't been using the IP address at all, and it's a privacy issue to keep those stored indefinitely if we're not making use of them.

**Comment by diox** [comment]
We should have access to the GeoIP City/Country database. I'm assuming Country is enough ? Do we need to convert the ip addresses to countries in existing reports ?

**Comment by jvillalobos** [comment]
I believe country should be enough. As for existing reports, either converting or clearing the IP addresses would be good (converting is better).

**Comment by diox** [comment]
QA:
- This should be visible in the admin tool/reviewer tools, instead of the IP the country code is now shown for abuse reports. I'll fire a script to backfill existing data (and then a new issue will get rid of the `ip_address` field entirely, but at the moment it should no longer be used and be completely hidden)

**Comment by AlexandraMoga** [comment]
@diox I've checked both admin and rev tools to see if the IP address is stored anywhere:

[admin] - the Ip address field is empty
![image](https://user-images.githubusercontent.com/31961530/53251519-820f2a80-36c5-11e9-8c54-cab57e75d6a6.png)

[rev tools] - I can't see a user Ip stored anywhere in https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/search_by_image
![image](https://user-images.githubusercontent.com/31961530/53251591-b256c900-36c5-11e9-9250-01d1539be4b3.png)

However, the new Country Code field doesn't seem to be populated for any of the abuse reports that I've submitted:

![image](https://user-images.githubusercontent.com/31961530/53251778-18435080-36c6-11e9-979f-fdd5dd9d3b80.png)

**Comment by diox** [comment]
That's because I forgot a step :) @autrilla can you do your magic and inject the GeoIP country database in the addons-server container (for dev and the next stage/prod), in `/usr/local/share/GeoIP/GeoLite2-Country.mmdb` ?

**Comment by AlexandraMoga** [comment]
I can see that the country code is populated now in Abuse report admin:

![image](https://user-images.githubusercontent.com/31961530/53732191-cbaa0300-3e85-11e9-8021-69b6d720ff95.png)

I've noticed that when using certain VPNs (ex. Opera's VPN) the country code is not populated, but I guess this has to do with how the VPN works.

**Comment by wagnerand** [comment]
@diox could we use something more readable than the country *code*, please? Can we show the country name?

**Comment by diox** [comment]
@wagnerand I haven't done any work on the admin yet, I'll open a new issue for it soon.
