### ISSUE TITLE
Users without Addons:ReviewUnlisted permissions can retrieve details for an unlisted version through the reviewers browse api

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10731]
STR

1. Call the [reviewers browse](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse) api while being authenticated with an account that doesn't have `Addons:ReviewUnlisted` permissions
2. Use an unlisted version_id for `/versions/` , for example:
`https://addons-dev.allizom.org/api/v4/reviewers/addon/494866/versions/1541833/`

Actual result:
The unlisted version details are retrieved

Expected result:
Looking at the [reviewers browse](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse) documentation, I understand that in order to be able to retrieve unlisted version details, your account should also have `Addons:ReviewUnlisted` permissions

Notes:
- the account I've authenticated with had only `Addons:PostReview` permissions - see https://addons-dev.allizom.org/api/v4/accounts/account/10641527/
- by contrast, if I'm accessing the [version listing](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-) endpoint with the same user, the unlisted version id doesn't appear in the list

**Comment by wagnerand** [comment]
Marking P2 just so it's above the fold.

**Comment by EnTeQuAk** [comment]
Moving to next weeks milestone as I didn't really have the time to fix this and as mentioned in the last meeting it's not really easy to misuse this as you need at least some kind of reviewer permission. So the risk is low here.

I'll have this ready for next week though.

**Comment by EnTeQuAk** [comment]
Uhm, stupid question. Are you the author of that addon? Because we also allow authors to view their add-ons in the file-viewer (it's not exposed but supported)

**Comment by EnTeQuAk** [comment]
Nevermind, found the "issue" - the add-on has mixed listed and unlisted versions which is confused the permission checking.

**Comment by AlexandraMoga** [comment]
I've tested several scenarios to make sure that a reviewer without Addons:ReviewUnlisted permissions has the right kind of access now.

In both of the scenarios mentioned below, the user (id 10641527) doesn't have view access for unlisted files:
1. addon with mixed versions - requesting an unlisted version
`/reviewers/addon/494866/versions/1541833/`
2. addon with only unlisted versions
`/reviewers/addon/503024/versions/1541880/`

@EnTeQuAk I've noticed that the api responds with a 404 for the above examples. Is this what we want? By comparison, `/reviewers/addon/<addon_id>/versions/` responds with a 403 if the user tries to view an unlisted version without having the proper permissions. 

If the user is the owner of the unlisted version, the details will be retrieved.

**Comment by EnTeQuAk** [comment]
Yes, a 404 is correct since we actually don't want to expose that the version even exists to people who don't have permissions to view them anyway.

Similarly to the listing, we simply don't show the unlisted versions so they "don't exist".

**Comment by AlexandraMoga** [comment]
Thanks for clarifying. That does make sense.
I'm marking this issue as verified fixed on -dev.
