### ISSUE TITLE
Add 5 more EU locales to AMO 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10758]
This is a request to add locales to AMO for the following languages: 

- Croatian
- Estonian
- Latvian
- Lithuanian
- Maltese

Having these locales would be helpful to supporting EU-specific campaigns for extensions. These should be enabled by March 15, 2019 for an upcoming campaign. 

@muffinresearch had mentioned that this should involve adding config and generating a locale file. If it becomes significantly more work, please holler -- campaign scope can be negotiated. 

Thanks!

**Comment by peiying2** [comment]
Ping me once the config is done and I will add them to Pontoon, making the above locales read-only.

**Comment by diox** [comment]
A similar issue needs to be filed over addons-frontend as well.

> * Croatian
> * Estonian
> * Lithuanian

Those 3 are already set up in addons-server, just not activated yet because they didn't have enough translations done. They are ready to be translated in pontoon, we can then activate them once they have enough translations.

> * Latvian
> * Maltese

These two I need to add (and then activate as the rest once they have enough translations).

**Comment by caitmuenster** [comment]
Thanks, @diox! This corresponding issue for the front-end is #[7626](https://github.com/mozilla/addons-frontend/issues/7626). 

@peiying2, is there anything we can do to encourage Croatian, Estonian, & Lithuanian translations?

**Comment by peiying2** [comment]
@caitmuenster both AMO server and frontend are very large projects. these are all pretty small size communities, I don't think we can ask them to translate it in time for the launch, or even beyond. Lithuanian hasn't touched AMO for more than a year, and Croatian 3 months ago. Estonian doesn't have AMO server/front end: https://pontoon.mozilla.org/et/.

**Comment by diox** [comment]
I went ahead and committed the change to enable those 5 locales in addons-server, and we plan to cherry-pick that into the tag that goes in production tomorrow. This will make it possible to add add-on translations on AMO in those locales, regardless of whether the site itself is translated.

**Comment by AlexandraMoga** [comment]
@diox I'm having issues with the `et` and `lt` locales when I'm trying to access DevHub Homepage, i.e I'm landing on the following URL https://addons-dev.allizom.org/en-US/firefox/et/developers/

By comparison, https://addons-dev.allizom.org/et/developers/addons works.

**Comment by willdurand** [comment]
> @diox I'm having issues with the `et` and `lt` locales when I'm trying to access DevHub Homepage, i.e I'm landing on the following URL [addons-dev.allizom.org/en-US/firefox/et/developers](https://addons-dev.allizom.org/en-US/firefox/et/developers/)

The URL is not correct I believe. There is the locale twice (`en-US` first, then the app `firefox`, then `et`).

**Comment by willdurand** [comment]
As @diox pointed out on Twitter, there was an issue related to an invalid server redirect and this URL above looks similar. The issue has been fixed but you have to clear your browse cache to invalidate the old redirect.

**Comment by AlexandraMoga** [comment]
Reverified with a new profile and the issue is indeed not reproduced.

I'm marking this as verified fixed on AMO-dev with FF65, Win10x64

**Comment by caitmuenster** [comment]
Thanks for the update, @diox! Appreciate it.
