### ISSUE TITLE
Remove LWT reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10755]
All pending LWT have been cleared from the reviewer tools, and all approved LWT have been converted to static themes so we can remove the special LWT reviewer tools.

**Comment by wagnerand** [comment]
I still see a bunch of LWTs in the reviewer tools, and I have reached out to theme reviewers and asked for help to clear the queues before next Thursday.

**Comment by wagnerand** [comment]
There is an issue with the LWT reviewer tools that prevents us from clearing the queues. I will follow up on Monday.

**Comment by ioanarusiczki** [comment]
@eviljeff Rev Tools -> Lw Themes queues are gone - verified on both AMO dev and AMO stage for admins and theme reviewers.

That's the Menu for a theme reviewer - only static themes are available for reviews

![rev tools](https://user-images.githubusercontent.com/33448286/53505526-ab142e80-3abc-11e9-8ad2-2924608a250a.png)
