### ISSUE TITLE
 Mozilla AMO Add-ons Manager API no longer responding

### ISSUE THREAD

**Issue by mitchmoser** [mozilla/addons-server#10767]
### Describe the problem and steps to reproduce it:
View/interact with any API URL outlined in the [Add-ons Manager API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Add-ons_manager_API)

Example:
> https://services.addons.mozilla.org/en-US/api/
### What happened?
Redirected to a 'Not Found' page stating:
"We're sorry, but we can't find what you're looking for..."

### What did you expect to happen?
User is returned the results of the API query

### Anything else we should know?
I noticed the Firefox Addon badges were broken on [my project's README.md](https://github.com/mitchmoser/sputnik/blob/master/README.md). These [shields.io](https://shields.io/) badges use the Mozilla Add-ons Manager API to retrieve downloads, ratings, and the latest version number. This functionality is still working for the Chrome Store badges on [my project's page](https://github.com/mitchmoser/sputnik/) for reference.

On line `6083` of [` shields/server.js`](https://github.com/badges/shields/blob/c1a8166af26d79ec2b966a56b0d0b55920df6b8d/server.js#L6083) I noticed:

```
 var url = 'https://services.addons.mozilla.org/api/1.5/addon/' + addonId;
```

According to [Mozilla Add-ons Manager API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Add-ons_manager_API):

> This API is deprecated and we do not recommend projects use this API

It looks like all of the examples included on that page are broken as well.

There were no other posts tagged [AMO API on the MDN webdocs](https://developer.mozilla.org/en-US/docs/tag/AMO%20API)

I opened [an issue](https://github.com/badges/shields/issues/3079) on the [shields.io GitHub](https://github.com/badges/shields/) to look into this and they responded:

> Our tests picked this up about 12 hours ago as well: https://circleci.com/gh/badges/daily-tests/167
> Would you be up for reaching out to them and politely asking if there's a new API Shields could use?

Is there another API URL that would make these Mozilla badges functional again?

**Comment by diox** [comment]
Hi,

These APIs have been deprecated for a very long time and were never really meant for outside consumption ; We finally removed it during our last push after noting that there wasn't that much traffic to them anymore.

The latest, fully supported API is documented over at https://addons-server.readthedocs.io/en/latest/topics/api/index.html (use https://addons-server.readthedocs.io/en/latest/topics/api/v3_legacy/index.html if you want some stability).
