### ISSUE TITLE
drop (now unused) LWT review tables from DB

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10760]
follow-on from #10755 / #10759 - drop the following tables:
`rereview_queue_theme`
`theme_locks`

Must merge after 2019.02.28 tag so it deploys in a later push.

**Comment by wagnerand** [comment]
Might have to be delayed until the tag after, see https://github.com/mozilla/addons-server/pull/10759#issuecomment-466712169

**Comment by AlexandraMoga** [comment]
This changes doesn't seem to have caused any regressions in rev tools or with static theme reviews, so I'm marking this issue as verified fixed.
