### ISSUE TITLE
Trying to commit LWT review results in 500

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10770]
Blocks: #10755, #10760

There are a few remaining LWTs in the queue and trying to review them and commit the review decision results in a 500:

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5235767/

```
ValueError: invalid literal for int() with base 10: ''
(12 additional frame(s) were not displayed)
...
  File "olympia/amo/decorators.py", line 49, in wrapper
    return f(request, *args, **kw)
  File "olympia/amo/decorators.py", line 30, in wrapper
    return func(request, *args, **kw)
  File "olympia/reviewers/decorators.py", line 73, in wrapper
    return f(request, *args, **kw)
  File "olympia/reviewers/views_themes.py", line 279, in themes_commit
    reviewer=request.user)

ValueError: invalid literal for int() with base 10: ''
```

STR:

1. Go to a theme review page, e.g. https://reviewers.addons.mozilla.org/en-US/reviewers/themes/queue/single/blue-gray-theme
2. Click Reject and select a reason.
3. Click "Commit Review".

**Comment by wagnerand** [comment]
My asumption is that in https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/views_themes.py#L278, we try to get the theme id using `form.data[form.prefix + '-theme']`. However, the input name is different, according to the devtools:

<img width="675" alt="screenshot" src="https://user-images.githubusercontent.com/873258/53293050-16b08000-37cd-11e9-91ae-d93934431db1.png">

So, I suppose it should be `form.data['form-' + form.prefix + '-theme']` instead? I wonder, when that regressed, was it really 8 months ago when `ThemeReviewForm` switched from happyforms to django forms (https://github.com/mozilla/addons-server/commit/7407b70aa2107ede91527f93f96662612e9551d2)? That seems like too long ago, for it to be noticed only now.

@eviljeff, @EnTeQuAk what are your thoughts?

**Comment by eviljeff** [comment]
Does the interactive queue work (enough to clear them)?  QA noted in #10743 that the interactive queue is working but the single review page isn't (though they assumed neither were supposed to be)

**Comment by wagnerand** [comment]
<img width="988" alt="screenshot 2019-02-25 at 10 59 06" src="https://user-images.githubusercontent.com/873258/53329479-6c2f7e80-38ec-11e9-8bb1-7fc717f8284b.png">

🤷‍♂️

**Comment by eviljeff** [comment]
> So, I suppose it should be `form.data['form-' + form.prefix + '-theme']` instead?

mmm, but an invalid key in the `form.data` dict would throw an exception rather than return `''`.

> Also, why does the test at https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/tests/test_views_themes.py#L103 not fail?

probably because we fake too much of the data, like https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/tests/test_views_themes.py#L122

**Comment by wagnerand** [comment]
@eviljeff is going to manually recreate the ones that are not broken.

**Comment by eviljeff** [comment]
All the LWT in the updates queue have been manually recreated via the wizard as static themes and can be approved/rejected as static themes.  The single LWT in the flagged queue had no author so I deleted it.

**Comment by AlexandraMoga** [comment]
I guess there isn't much we can test here, since the LWT rev tools are gone now.

**Comment by thniig1933** [comment]
Sorry, Im just not getting it at all.

**Comment by ioanarusiczki** [comment]
The LW themes queues are no longer available in Rev Tools starting this week
https://github.com/mozilla/addons-server/issues/10755
