### ISSUE TITLE
Django model admin for versions returns 504

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10775]
### Describe the problem and steps to reproduce it:

Django model admin pages for versions seems to return 504 always. Example. https://addons-internal.prod.mozaws.net/en-US/admin/models/versions/version/1988144/change/

### What happened?

HTTP 504: Gateway Timeout

### What did you expect to happen?

Display the versions admin page.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
I'm not terribly surprised: we don't have a specific `ModelAdmin` set up for it, so any FKs on `Version` is trying to show a dropdown of all possible choices... That means at least `addon` and `license`. Some minimal work needs to be done on it before it's accessible.

**Comment by AlexandraMoga** [comment]
See also https://github.com/mozilla/addons-server/issues/9304 , which reports the same issue when trying to open the version edit page from the Files tool.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF65, WIn10x64.

The admin version edit page is now displayed to admin users (I've tried with full admins and advanced admins)

https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1541886/change/

![image](https://user-images.githubusercontent.com/31961530/53813049-662d4380-3f65-11e9-9a15-bd9a3c60bc84.png)
