### ISSUE TITLE
remove LWT support from devhub

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10785]
might have to split up into stages/separate issues.  reviewer tools was already removed in #10755

**Comment by eviljeff** [comment]
tasks remaining before we can fully remove support:
- run the full migration on LWT on -dev (stage and prod had the full migration runs)
- delete remaining (i.e. unmigrated) LWT.  For -dev and stage this will include approved but broken LWT; prod was manually fixed prior so only rejected LWT remain.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/issues/9941#issuecomment-480162001 was suggesting we wait until 67 was release, which was a few weeks ago, so no blocker on this now afaik

**Comment by ioanarusiczki** [comment]
@eviljeff I checked with 2 accounts which had submitted lw themes. 
My Themes tab - from [Manage my Submission](https://addons-dev.allizom.org/en-US/developers/themes) page in dev hub won't display them anymore. I only see a list of static themes right now.  Looks like they've been deleted.
Accounts I tested with: irusiczki@mozilla.com and rusiczki.ioana@gmail.com

If there's something else I could check on please let me know.
