### ISSUE TITLE
Received an empty response from the server; status: 503

### ISSUE THREAD

**Issue by zdenop** [mozilla/addons-server#10782]
I need to upload new version of my addon, but I got error message:
![image](https://user-images.githubusercontent.com/574156/53331466-3e006d80-38f1-11e9-9157-1a7375ccc970.png)

Here is my file (I just need to add ".zip" to upload it here):
[sk@dictionaries.addons.mozilla.org.xpi.zip](https://github.com/mozilla/addons-server/files/2900092/sk%40dictionaries.addons.mozilla.org.xpi.zip)

**Comment by wagnerand** [comment]
Please see the yellow box in that screenshot.

**Comment by EnTeQuAk** [comment]
Add-on submissions are currently disabled due do a planned server migration. Please see the yellow warning box on the page.
