### ISSUE TITLE
No error message on frontend when logging in during read only mode

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#10787]
### Describe the problem and steps to reproduce it:

When `addons.mozilla.org` is in read-only mode, logging in looks like this:

* Click on *Register or Log in* from the header
* Enter in username and password on Firefox Accounts

### What happened?

You get redirected to `addons.mozilla.org` but you are not logged in. The button in the header says *Register or Log in* just like before you started logging in.

### What did you expect to happen?

You should see a notice saying that the site is in read-only mode.

### Anything else we should know?

The request from Firefox Accounts to `addons-server` seemed to behave just like normal: `GET https://addons.mozilla.org/api/v3/accounts/authenticate/?config=amo&code=...&state=...&action=signin` -> `302 Found`, `Location=/en-US/firefox/`. It didn't set a login cookie, though.

Maybe it should add a query string parameter so that the frontend knows to display a read-only message.

See https://github.com/mozilla/addons-frontend/issues/5949

**Comment by willdurand** [comment]
This is similar to https://github.com/mozilla/addons-server/issues/9723

**Comment by kumar303** [comment]
Ah, yes, I updated this issue title because it's only about the frontend

**Comment by kumar303** [comment]
seems legit

**Comment by eviljeff** [comment]
Once #11493 is done will there be anything specific to do here on the server side?  We _could_ have the auth flow return something different on login when the site is read-only but once frontend is handling the read-only status anyway it seems (to me) easier to prevent login rather than adding more code to handle an error code after letting the user login when we know it's going to fail.

**Comment by eviljeff** [comment]
closing this as per my thoughts in the previous comment.  Now the read-only status can (and is) discoverable by frontend it's a much better user experience, imo, to prevent login from frontend when the site is read only (e.g. hide/disable the buttons).
