### ISSUE TITLE
An extension with 250+ chars made of letters and emojis in the summary field can be submitted 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#10794]
This is an edge case I've noticed while investigating the uploads of add-ons that contain emojis in their names and summaries

STR:
1. Login AMO stage and submit an extension that has a summary of 250 chars (make sure to insert as many emojis as possible). 
2. Submit the file

Expected result:
The extensions submission cannot be done until the summary field is not edited (to make sure the summary is under 250 chars).

Actual result:
Submission is completed. 

Notes:
This issue is reproducible on all AMO servers (AMO dev is restricted to max. 70 chars for Name+Summary) with FF65(Win10). 
I could not reproduce this issue if the text from the description (summary) field is numbers and letters only. Also, not reproducible with the "Name" which at validation is restricted at maximum 45 chars.

![summary minus](https://user-images.githubusercontent.com/33448286/53418168-d6751b80-39df-11e9-97df-90b26b2d1201.gif)

I'm attaching the samples I used here
[manifest bug2.zip](https://github.com/mozilla/addons-server/files/2905821/manifest.bug2.zip)
[manifest bug1.zip](https://github.com/mozilla/addons-server/files/2905824/manifest.bug1.zip)

**Comment by diox** [comment]
Python, JavaScript and MySQL disagree about the length of emojis...

```
MySQL [***]> SELECT LENGTH('👻');
+-------------+
| LENGTH('?') |
+-------------+
|           4 |
+-------------+
1 row in set (0.00 sec)
```

```javascript
>> '👻'.length
2
```

```python
>>> len(b'👻')
4
>>> len(u'👻')
1
```
```

**Comment by ioanarusiczki** [comment]
Forgot to add that the issue is reproducible for unlisted add-ons too, in this case even for a summary of 250+ composed of chars and numbers (no emojis).

**Comment by ioanarusiczki** [comment]
This issue is still reproducible on AMO stage - FF69(Win10).
