### ISSUE TITLE
Remaining test fails under django2.2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10804]
https://travis-ci.org/mozilla/addons-server/jobs/498900845#L4465
**________________ TestAddonManager.test_filter_for_many_to_many _________________**
```
src/olympia/addons/tests/test_models.py:345: in test_filter_for_many_to_many
    assert collection.addons.count() == 0
E   AssertionError: assert 1 == 0
```

~https://travis-ci.org/mozilla/addons-server/jobs/498900846#L3695
**______________ TestEditMedia.test_edit_media_shows_proper_labels _______________**
/devhub/tests/test_views_edit.py:888: in test_edit_media_shows_proper_labels~

https://travis-ci.org/mozilla/addons-server/jobs/498900846#L3702
**_ TestAddonSubmitAgreementWithPostReviewEnabled.test_read_dev_agreement_captcha_active_error _**
```
src/olympia/devhub/tests/test_views_submit.py:228: in test_read_dev_agreement_captcha_active_error
    response = self.client.get(reverse('devhub.submit.agreement'))
.tox/devhub/lib/python3.6/site-packages/django/test/client.py:535: in get
    response = super().get(path, data=data, secure=secure, **extra)
.tox/devhub/lib/python3.6/site-packages/django/test/client.py:347: in get
    **extra,
.tox/devhub/lib/python3.6/site-packages/django/test/client.py:422: in generic
    return self.request(**r)
.tox/devhub/lib/python3.6/site-packages/django/test/client.py:503: in request
    raise exc_value
.tox/devhub/lib/python3.6/site-packages/django/core/handlers/exception.py:34: in inner
    response = get_response(request)
.tox/devhub/lib/python3.6/site-packages/django/core/handlers/base.py:115: in _get_response
    response = self.process_exception_by_middleware(e, request)
.tox/devhub/lib/python3.6/site-packages/django/core/handlers/base.py:113: in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
/opt/python/3.6.7/lib/python3.6/contextlib.py:52: in inner
    return func(*args, **kwds)
src/olympia/amo/decorators.py:30: in wrapper
    return func(request, *args, **kw)
src/olympia/devhub/views.py:1199: in submit_addon
    render_captcha=waffle.switch_is_active('addon-submission-captcha')
src/olympia/devhub/views.py:1742: in render_agreement
    return render(request, template, context)
src/olympia/amo/utils.py:68: in render
    rendered = loader.render_to_string(template, ctx, request=request)
.tox/devhub/lib/python3.6/site-packages/django/template/loader.py:62: in render_to_string
    return template.render(context, request)
.tox/devhub/lib/python3.6/site-packages/django_jinja/backend.py:106: in render
    return mark_safe(self.template.render(context))
conftest.py:114: in instrumented_render
    return old_render(self, *args, **kwargs)
.tox/devhub/lib/python3.6/site-packages/jinja2/asyncsupport.py:76: in render
    return original_render(self, *args, **kwargs)
.tox/devhub/lib/python3.6/site-packages/jinja2/environment.py:1008: in render
    return self.environment.handle_exception(exc_info, True)
.tox/devhub/lib/python3.6/site-packages/jinja2/environment.py:780: in handle_exception
    reraise(exc_type, exc_value, tb)
.tox/devhub/lib/python3.6/site-packages/jinja2/_compat.py:37: in reraise
    raise value.with_traceback(tb)
src/olympia/devhub/templates/devhub/addons/submit/start.html:1: in top-level template code
    {% extends "devhub/addons/submit/base.html" %}
src/olympia/devhub/templates/devhub/addons/submit/base.html:6: in top-level template code
    {% set title = _('Submit a New Add-on') %}
src/olympia/devhub/templates/devhub/base.html:45: in top-level template code
    {% set hide_mobile_link=True %}
src/olympia/templates/base.html:133: in top-level template code
    {% block main_content %}
src/olympia/templates/base.html:136: in block "main_content"
    {% block content %}{% endblock %}
src/olympia/devhub/templates/devhub/addons/submit/base.html:25: in block "content"
    {% block primary %}{% endblock %}
src/olympia/devhub/templates/devhub/addons/submit/start.html:9: in block "primary"
    {% include "devhub/agreement.html" %}
src/olympia/devhub/templates/devhub/agreement.html:20: in top-level template code
    {{ agreement_form.recaptcha }}
.tox/devhub/lib/python3.6/site-packages/django/utils/html.py:389: in <lambda>
    klass.__html__ = lambda self: str(self)
.tox/devhub/lib/python3.6/site-packages/django/utils/html.py:388: in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
.tox/devhub/lib/python3.6/site-packages/django/forms/boundfield.py:33: in __str__
    return self.as_widget()
.tox/devhub/lib/python3.6/site-packages/django/forms/boundfield.py:93: in as_widget
    renderer=self.form.renderer,
E   TypeError: render() got an unexpected keyword argument 'renderer'
```

**_ TestAddonSubmitAgreementWithPostReviewEnabled.test_read_dev_agreement_captcha_active_success _**
```
src/olympia/devhub/tests/test_views_submit.py:244: in test_read_dev_agreement_captcha_active_success
(same as last traceback)
```

~https://travis-ci.org/mozilla/addons-server/jobs/498900846#L3836
**_____________________ TestAddonSubmitSource.test_no_source _____________________**
src/olympia/devhub/tests/test_views_submit.py:830: in test_no_source
(same exception repeated in a number of following tests)~

https://travis-ci.org/mozilla/addons-server/jobs/499409208#L3698
**_________________________ TestDelete.test_post_lwtheme _________________________**
```
src/olympia/devhub/tests/test_views.py:479: in test_post_lwtheme
    assert pq(response.content)('.notification-box').text() == (
E   AssertionError: assert '<h2> Theme deleted. </h2>' == 'Theme deleted.'
E     - <h2> Theme deleted. </h2>
E     + Theme deleted.
```
( + 6 more in TestDelete )

https://travis-ci.org/mozilla/addons-server/jobs/499296540#L3831
**_ TestVersionSubmitUploadListed.test_same_version_if_previous_is_awaiting_review _**
```
src/olympia/devhub/tests/test_views_submit.py:1924: in test_same_version_if_previous_is_awaiting_review
    assert pq(response.content)('ul.errorlist').text() == (
E   AssertionError: assert 'Version 0.1 ... instead?</a>' == 'Version 0.1 a...load instead?'
E     - Version 0.1 already exists. <a href="/en-US/developers/addon/a3615/versions/submit/81551/details">Continue with existing upload instead?</a>
E     + Version 0.1 already exists. Continue with existing upload instead?
```
(it's essentially the same problem as the TestDelete test fails - html is being escaped and returned as text)

https://travis-ci.org/mozilla/addons-server/jobs/499296540#L3838
**_ TestVersionSubmitUploadUnlisted.test_same_version_if_previous_is_awaiting_review _**
```
src/olympia/devhub/tests/test_views_submit.py:1924: in test_same_version_if_previous_is_awaiting_review
(same as last traceback)
```

**Comment by HSR05** [comment]
I'd also like to work on this. Can you guide me? @eviljeff

**Comment by diox** [comment]
@HSR05 this is not a good first bug, and it's already assigned to someone anyway.

**Comment by HSR05** [comment]
Well, I might be able to get something from it (In a good way). Like learn something. 👍 
But yeah i get that it'll be difficult. Thanks for the guidance @diox . Can you help me in my first few contributions. I would be more than thankful :)

**Comment by eviljeff** [comment]
taking them one at a time:
https://travis-ci.org/mozilla/addons-server/jobs/498900845#L4465
**________________ TestAddonManager.test_filter_for_many_to_many _________________**

```
src/olympia/addons/tests/test_models.py:345: in test_filter_for_many_to_many
    assert collection.addons.count() == 0
E   AssertionError: assert 1 == 0
```
Needs further investigation - it could be something trivial like needing a `Collection.reload()`; it could be a significant problem in the way we load models and related objects.

**Comment by eviljeff** [comment]
https://travis-ci.org/mozilla/addons-server/jobs/498900846#L3702
**_ TestAddonSubmitAgreementWithPostReviewEnabled.test_read_dev_agreement_captcha_active_error _**
and _ TestAddonSubmitAgreementWithPostReviewEnabled.test_read_dev_agreement_captcha_active_success _

A problem with the upstream dependency, nobot.  Filed an issue - EnTeQuAk/nobot#7 but we could hack it by subclassing `HumanCaptchaWidget` and adding a render method that accepts renderer but then discards it.

**Comment by eviljeff** [comment]
https://travis-ci.org/mozilla/addons-server/jobs/499409208#L3698
**_________________________ TestDelete.test_post_lwtheme _________________________**

```
src/olympia/devhub/tests/test_views.py:479: in test_post_lwtheme
    assert pq(response.content)('.notification-box').text() == (
E   AssertionError: assert '<h2> Theme deleted. </h2>' == 'Theme deleted.'
E     - <h2> Theme deleted. </h2>
E     + Theme deleted.
``` 
* 7

Initially I thought it was a bug with pquery but now it seems the html content such as `<h2>` is being escaped by `django.contrib.messages` (which it shouldn't as we go through the effort of marking it safe).

**Comment by eviljeff** [comment]
https://travis-ci.org/mozilla/addons-server/jobs/499296540#L3831
**_ TestVersionSubmitUploadListed.test_same_version_if_previous_is_awaiting_review _** and **_ TestVersionSubmitUploadUnlisted.test_same_version_if_previous_is_awaiting_review _**
```
src/olympia/devhub/tests/test_views_submit.py:1924: in test_same_version_if_previous_is_awaiting_review
    assert pq(response.content)('ul.errorlist').text() == (
E   AssertionError: assert 'Version 0.1 ... instead?</a>' == 'Version 0.1 a...load instead?'
E     - Version 0.1 already exists. <a href="/en-US/developers/addon/a3615/versions/submit/81551/details">Continue with existing upload instead?</a>
E     + Version 0.1 already exists. Continue with existing upload instead?
```

Similar to the `TestDelete` test fails - html is being escaped and returned as text - but this time the message is passed via a `forms.ValidationError` in `NewUploadForm.clean()`

**Comment by eviljeff** [comment]
logged TestAddonManager.test_filter_for_many_to_many fail as https://github.com/mozilla/addons-server/issues/10843

**Comment by eviljeff** [comment]
logged TestDelete fails as #10845

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed.
Thanks
