### ISSUE TITLE
'users.admin_edit' url is inconsistent with addons-frontend

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10828]
`'users.admin_edit'` should be `/user/<user-id>/edit` - it was `/users/edit/<user-id>` on legacy frontend.  It's only referenced in reviewer tools and admin so it seems safe to just update it to the current correct url

**Comment by AlexandraMoga** [comment]
@eviljeff every `/users` page on the legacy site is throwing a 500 error, so I'm not sure how I could access a user edit page to make sure that the url is correct.

**Comment by eviljeff** [comment]
@AlexandraMoga there is no legacy frontend site for users.  https://addons-dev.allizom.org/en-US/firefox/user/10641829/ wfm as does https://addons-dev.allizom.org/en-US/firefox/user/10641829/edit/

**Comment by AlexandraMoga** [comment]
@eviljeff normally you could land on the legacy view of a user profile through django admin (see https://addons-internal.dev.mozaws.net/en-US/firefox/user/10641829/). My attempt was to verify that the edit URL will be smth like https://addons-internal.dev.mozaws.net/en-US/firefox/user/10641829/edit/ , but as mentioned in https://github.com/mozilla/addons-server/issues/10830#issuecomment-469649498 these pages are now throwing a 500 error
