### ISSUE TITLE
Remove RSS Feeds

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10824]
Given https://github.com/mozilla/addons-server/issues/7182 and the fact that we're not really re-implementing / linking to RSS feeds we should just remove them entirely.

**Comment by eviljeff** [comment]
and more importantly mozilla/addons-frontend#7650 - they don't work anyway now

**Comment by caitmuenster** [comment]
Mentor: @eviljeff

**Comment by eviljeff** [comment]
The fix for this will probably end up touching a number of files.  I'd remove the urls that mention rss from the `urls.py` file(s), and then the views (in `views.py`).  Then see what tests fails and remove them also.

**Comment by Patil2099** [comment]
Can I work on this issue?

**Comment by eviljeff** [comment]
@Patil2099 sure.

**Comment by Patil2099** [comment]
@eviljeff  can you please tell me the possible names of RSS feed Views ?

**Comment by eviljeff** [comment]
the views used by the urls with rss in them

**Comment by Patil2099** [comment]
@eviljeff  I searched RSS keyword in every Views.py File that is present in /src/olympia/ and I didn't find it anywhere. Can you please guide me a little bit?

**Comment by eviljeff** [comment]
> url(r'^addons/versions/(\d+)/format:rss$',
lambda r, id: redirect('addons.versions.rss', id, permanent=True)),

Good find on that one - it's a redirect to another url that we already removed.  You can delete that `url(...)` statement.  But it does seem the underlying view was already cleaned up so there's not much to do in this issue now, just drop that redirect url.

**Comment by Patil2099** [comment]
@eviljeff  I made a pr that removes this code I also found some code that has RSS in it.
 def test_rss(self):
        self.log_creates(5)
        # This will give us a new RssKey
        self.get_response()
        key = RssKey.objects.get()

        assert isinstance(key.key, uuid.UUID)

        res = self.get_response(privaterss=key.key)
        assert res['content-type'] == 'application/rss+xml; charset=utf-8'
        assert b'<title>Recent Changes for My Add-ons</title>' in res.content

    def test_rss_accepts_verbose(self):
        self.log_creates(5)
        self.get_response()
        key = RssKey.objects.get()
        res = self.get_response(privaterss=str(key.key))
        assert res['content-type'] == 'application/rss+xml; charset=utf-8'
        assert b'<title>Recent Changes for My Add-ons</title>' in res.content

    def test_rss_single(self):
        self.log_creates(5)
        self.log_creates(13, self.addon2)

        # This will give us a new RssKey
        self.get_response(addon=self.addon.id)
        key = RssKey.objects.get()
        res = self.get_response(privaterss=key.key)
        assert res['content-type'] == 'application/rss+xml; charset=utf-8'
        assert len(pq(res.content)('item')) == 5
        assert '<title>Recent Changes for %s</title>' % self.addon in (
            force_text(res.content))

    def test_rss_unlisted_addon(self):
        """Unlisted addon logs appear in the rss feed."""
        self.make_addon_unlisted(self.addon)
        self.log_creates(5)

        # This will give us a new RssKey
        self.get_response(addon=self.addon.id)
        key = RssKey.objects.get()
        response = self.get_response(privaterss=key.key)
        assert len(pq(response.content)('item')) == 6

this is present in src/olympia/devhub/tests.py

also this code 
  urls = (
            # Add-on Category RSS Feed
            '/{language}/firefox/extensions/alerts-updates/format:rss',
            '/{language}/firefox/extensions/appearance/format:rss',
            '/{language}/firefox/extensions/bookmarks/format:rss',
            '/{language}/firefox/extensions/language-support/format:rss',

            # App Version RSS Feed
            '/{language}/{app}/pages/appversions/format:rss',

            # Collection RSS Feed
            '/{language}/firefox/collections/Vivre/ploaia/format:rss',

            # Featured Add-ons
            '/{language}/{app}/featured/format:rss',

            # Search tools RSS Feed
            '/{language}/{app}/search-tools/format:rss',
        )

        self.client.get(self.get_url(random.choice(urls), app))

    @task(1)
    def test_browse_appversions(self):
        app = self.get_app()

        self.client.get(self.get_url(
            '/{language}/{app}/pages/appversions/', app))
present in  tests/performance/tasks/user.py

**Comment by eviljeff** [comment]
@Patil2099 we're going to keep those RSS feeds - they're developer facing and still work.  It's just that broken redirect.

**Comment by Patil2099** [comment]
@eviljeff  Please Check the PR that I made.
