### ISSUE TITLE
Add better validation of HTML in release notes on the way in.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#10832]
This nasty rendering bug https://github.com/mozilla/addons-frontend/issues/7653 was caused by a missing opening `<ul>` in the release notes for a popular add-on.

Looking through the release notes on this add-on there's a lot of missing closing tags too.

It would handy if we're going to stick with HTML for release-notes if we can carry out a basic validation and make sure tags are not missing.

**Comment by diox** [comment]
Might need that for more than release notes... I was thinking of doing it purely client-side for convenience (it's not a security check - we run things through `bleach` eventually), but maybe that's not enough. Plus, it wouldn't work for https://github.com/mozilla/addons-server/issues/7811

**Comment by willdurand** [comment]
I think more control on the server would be useful.
