### ISSUE TITLE
start removing legacy UI code from addons-server - /users

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10830]
We may as well start on a fairly self-contained chunk of code - users - and remove it from the codebase now nginx changes mean no-one can access a /users/... url.

**Comment by eviljeff** [comment]
Note: https://github.com/mozilla/addons-server/issues/10827 and https://github.com/mozilla/addons/issues/930 mean we can't just delete every view straight away

**Comment by AlexandraMoga** [comment]
@eviljeff there is a function in django users admin that allowed admins to view the public profile for a certain account on the legacy site, i.e. https://addons-internal.dev.mozaws.net/en-US/firefox/user/10641829/

This page is now throwing a server error (500):

 
![2019-03-05_13-00-14](https://user-images.githubusercontent.com/31961530/53801384-b1385e00-3f47-11e9-81aa-72109dd4e860.gif)

This could be filed as a follow up issue, though.

**Comment by AlexandraMoga** [comment]
I could not find other regressions concerning user profiles, except what I mentioned above and filed in #10862 
I'm marking the issue as verified fixed.
