### ISSUE TITLE
Fix/workaround django.contrib.messages losing the safe-ness in django2.0+

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10845]
Highlighted by tests such as:
https://travis-ci.org/mozilla/addons-server/jobs/499409208#L3698
_________________________ TestDelete.test_post_lwtheme _________________________
```
src/olympia/devhub/tests/test_views.py:479: in test_post_lwtheme
    assert pq(response.content)('.notification-box').text() == (
E   AssertionError: assert '<h2> Theme deleted. </h2>' == 'Theme deleted.'
E     - <h2> Theme deleted. </h2>
E     + Theme deleted.
```
See olympia.devhub.views.delete for where the usage for the test is but the (broken?) code is in olympia.amo.messages.

**Comment by eviljeff** [comment]
I _think_ the bug is caused by django switching from `force_text` to `str` here https://github.com/django/django/blob/2.2b1/django/contrib/messages/storage/base.py#L7:L40 in https://github.com/django/django/commit/f87256b15e375c6c57fe425c33ae23e116da3e84 

From what I read in https://github.com/django/django/blob/2.2b1/django/contrib/messages/storage/cookie.py#L32:L45 `mark_safe` is re-applied.  Maybe that's not good enough for jinja2 templates?  jinja2.Markup (or https://github.com/pallets/markupsafe/blob/master/src/markupsafe/__init__.py#L31) is different?

**Comment by eviljeff** [comment]
I think I've identified the underlying cause while looking into `TestVersionSubmitUploadListed.test_same_version_if_previous_is_awaiting_review` fails - `django.utils.safestring.mark_safe` doesn't do anything if the object already contains the `__html__` attribute, like `jinja2.Markup` adds, but there are some places where django treats a string wrapped in `SafeData` differently than one just with a `__html__` attribute.

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed.
Thanks
