### ISSUE TITLE
Source viewer is empty

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1084]
For https://addons.mozilla.org/en-US/editors/review/save-selected-text the source viewer fails to show 1.2.1-signed https://addons.mozilla.org/en-US/firefox/files/browse/297810/ . 1.4 works: https://addons.mozilla.org/en-US/firefox/files/browse/305474/

This is not a single occurrence. I have more examples if needed.

**Comment by andymckay** [comment]
This is working for me now. This is most likely related to the jquery upgrades and cleaning that @muffinresearch and @magopian did in Jan. Closing for now, please re-open if it re-occurs.
