### ISSUE TITLE
Flaky test TestRatingViewSetPost.test_throttle

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10854]
```
_____________________ TestRatingViewSetPost.test_throttle ______________________
[gw0] linux -- Python 3.6.7 /home/travis/build/mozilla/addons-server/.tox/accounts-users-and-ratings/bin/python
src/olympia/ratings/tests/test_views.py:2418: in test_throttle
    assert response.status_code == 429
E   AssertionError: assert 201 == 429
E     -201
E     +429
```

**Comment by diox** [comment]
I've seen this happen intermittently on travis, but I fired the test 20 times locally, with and without other tests, didn't get a single failure. Looking at the code I can't quite see why this would fail, unless somehow the cache backend would be empty despite it being locmem and having been set just before. We're even using `freeze_time` ...
