### ISSUE TITLE
Trying to access a public profile from django admin Users will result in a 500 error

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10862]
This looks like a regression from https://github.com/mozilla/addons-server/pull/10833

STR:
1. Log in to AMO -dev with an admin account
2. Access the User profiles management tool
3. Open the details of a user from the list - i.e. https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641829/change/
4. Click on `View on site` button on the top right corner

Actual result:
A server error (500) is received

Expected result:
The public profile of the user is opened

Notes:
- the link should be pointing to the new frontend profile page
- reproduced on AMO -dev with FF65, Win10x64

![2019-03-05_13-00-14](https://user-images.githubusercontent.com/31961530/54112565-22b45880-43ef-11e9-90e5-a27c72f64d17.gif)

**Comment by eviljeff** [comment]
what is the link?

**Comment by AlexandraMoga** [comment]
@eviljeff here is one - https://addons-internal.dev.mozaws.net/en-US/firefox/user/10641829/
This should be a public developer profile.

**Comment by eviljeff** [comment]
It's because addons-internal.dev.mozaws.net doesn't have a frontend instance.

@autrilla can we add nginx rules for addons-internal too?  Only the addons-server urls should go to django

**Comment by autrilla** [comment]
> It's because addons-internal.dev.mozaws.net doesn't have a frontend instance.
> 
> @autrilla can we add nginx rules for addons-internal too? Only the addons-server urls should go to django

We can, but I'm not sure what exactly you want. https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/amo_proxy/templates/nginx.internal.conf.erb is the config file the NGINX server on the internal olympia instance uses.

**Comment by eviljeff** [comment]
I'm thinking either there would be a working frontend under addons-internal or there would be a redirect for everything that didn't match the addons-server urls to normal addons-dev frontend.

In general, that file looks a little dated now (doesn't even reference the v4 api) so there might be other changes needed.

**Comment by autrilla** [comment]
> I'm thinking either there would be a working frontend under addons-internal

So if I understand this correctly, we'd need a new proxy, new frontend, and the existing addons-server setup, all internal-only, in order to fix this?


> or there would be a redirect for everything that didn't match the addons-server urls to normal addons-dev frontend.

Hmm, I suppose we could use the "normal" NGINX config here with some minor modifications.

cc @bqbn

**Comment by bqbn** [comment]
The "admin/internal" site is only supposed to be used by a few people via VPN (per https://bugzilla.mozilla.org/show_bug.cgi?id=1244224), besides it is located in a different domain. I'd prefer just redirecting `<locale>/<app>/user/<uid>/` to the frontend domain.

Also I think we can add the redirection rules on needed basis instead of adding them all at once because I don't think the "admin/internal" site need all those routes.

And another thought is maybe the `View on site` button should be disabled or removed from that page, because django admin isn't aware that we're serving the model details pages from a different domain anyways.

**Comment by eviljeff** [comment]
> And another thought is maybe the View on site button should be disabled or removed from that page, because django admin isn't aware that we're serving the model details pages from a different domain anyways.

Yeah I think that's the cleaner solution than adding more nginx rules.

**Comment by AlexandraMoga** [comment]
@eviljeff I'm still reproducing this and #11014  on -dev

**Comment by eviljeff** [comment]
it needs some extra config from ops but I submitted a follow-up to fix it a better way

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF66, Win10x64

![2019-04-10_11-54-24](https://user-images.githubusercontent.com/31961530/55865680-8dd88280-5b87-11e9-8fe3-310953121f87.gif)
