### ISSUE TITLE
Invalid strict_min_version is not caught

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10864]
### Describe the problem and steps to reproduce it:

STR:
Submit an add-on that defines a `strict_min_version` like:

```
"browser_specific_settings": {
    "gecko": {
      "id": "invalid@min_version",
      "strict_min_version": "65.0.2"
    }
  }
```

### What happened?

Neither the standalone linter, nor validation process on the server complains that this appversion is invalid/unknown. You'll end up on `developers/addon/prekey/submit/details`. That page doesn't show categories (because of missing appversion), which in turn causes you to be stuck on that page because clicking "Submit" will just redirect to the same page again, as categories are mandatory. 

### What did you expect to happen?

Failed validation?

### Anything else we should know?

Same goes for `strict_max_version`, probably.

**Comment by diox** [comment]
We're currently ignoring unknown versions (provided they still look like a version). This was done to support https://github.com/mozilla/addons-server/issues/7160, because sometimes people would submit add-ons with versions too far in the future.

I think the fix is to ignore unknown /max/ versions (setting `*` instead), while still throwing an error for unknown /min/ versions. That would mean you can't submit an add-on that targets a nightly version we haven't yet enabled, though. Is that a problem, @jvillalobos ? I don't see many other ways around it, AMO /needs/ a known version to function properly.

**Comment by jvillalobos** [comment]
> I think the fix is to ignore unknown max versions (setting * instead), while still throwing an error for unknown min versions. That would mean you can't submit an add-on that targets a nightly version we haven't yet enabled, though. Is that a problem, @jvillalobos ?

That sounds like a good fix to me.

**Comment by diox** [comment]
Can you link the upload that failed with `Sorry, we couldn't load your WebExtension`? Everything else looks correct (we're allowing everything listed under https://addons-dev.allizom.org/en-US/firefox/pages/appversions/)

**Comment by ioanarusiczki** [comment]
@diox Testing again with "72.0" "72.0.1" or "72.0a1" there's one message for all  `Unknown"strict_min_version" 72.0a1 for Firefox`.  I tried to reproduce the other message but without any success and I've been going through the samples I tested with and saved from yesterday too. 


<img width="767" alt="Unknown strict min version" src="https://user-images.githubusercontent.com/33448286/54744058-a1b74700-4bce-11e9-9a10-8790da399ca4.png">

I only received another warning message when max_version is too far in the future such as 1000.*

<img width="759" alt="max version too far in the future" src="https://user-images.githubusercontent.com/33448286/54744196-f35fd180-4bce-11e9-88b8-a2d0a8f03c35.png">

**Comment by diox** [comment]
Must have been a temporary issue with dev then. `1000` is expected to cause issues yes, that's fine, we can deal with that when the time comes :)

**Comment by ioanarusiczki** [comment]
@diox Yes, I re-tested on both AMO dev and AMO stage  - FF 65(Win10) and it looks good to me.
That being said, I'm marking this as verified.
