### ISSUE TITLE
Saving changes in django admin versions triggers a 500 error

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10861]
STR:

1. Log in to AMO -dev with an admin account
2. Open the version management tool and pick a version from the list - i.e. https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1541886/change/
3. Make some changes (if you want) and hit Save 

Actual result:
An internal server error (500) is received

Expected result:
Changes are successfully saved

Notes:
- reproduced on AMO dev with FF65, Win10x64

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5316454/?query=is:unresolved

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF65, Win10x64
There are no more errors received when saving changes for add-on versions.
