### ISSUE TITLE
Add download link to the browse/diff api response

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10877]
The download url is exposed, it's just not in the docs apparently.

**Comment by bobsilverberg** [comment]
The `url` in the response is always a link to download the xpi file for the extension. It is not a link to download the file that was requested, which is what the code manager needs for the footer. I have updated the title of this issue to reflect the fact that we still need a link to download the requested file in the response.

This is something we need for the MVP, so maybe it should be a P2? I didn't want to go ahead and just change that myself.

**Comment by willdurand** [comment]
@bobsilverberg I just thought about that but is the link in the footer pointing to a specific file or is it the XPI all the time? (and only other metadata are specific to the current file)

**Comment by bobsilverberg** [comment]
> @bobsilverberg I just thought about that but is the link in the footer pointing to a specific file or is it the XPI all the time? (and only other metadata are specific to the current file)

The link in the current tool points to the specific file. For example, in this screenshot, the link "Download manifest.json" points to https://reviewers.addons.allizom.org/en-US/firefox/files/browse/327331/file-redirect/manifest.json.

![screenshot 2019-03-08 07 31 32](https://user-images.githubusercontent.com/142755/54028798-3e5ffa80-4174-11e9-9c97-f0e877796771.png)

**Comment by EnTeQuAk** [comment]
Marked as qa: not needed as it'll be moved out of the API.
