### ISSUE TITLE
move forms from addons app to devhub app

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10876]
For some historical reason we have forms that are only used in developer hub under olympia.addons.forms rather than olympia.devhub.forms.  (While most of the other forms that relate to addons are already in olympia.forms.devhub).  Lets move them all into one location.

**Comment by ioanarusiczki** [comment]
@eviljeff Should we check for some specific forms from devhub that work as expected? Please add some STR for qa.

**Comment by eviljeff** [comment]
It's the forms used for edit listing, mainly - just go into each section and change/edit some of the details, categories, tags, etc.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this issue on AMO dev - FF66(Win10). 
I did not notice regression in dev hub - Edit Product Page but I'm going to make the final validation on Thursday after completing the release testing.
Tags - they can be edited, but the new frontend won't display them. I remember them being available on the legacy frontend - the detail pages.
