### ISSUE TITLE
Link to code-manager file viewer from reviewer tools

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#10887]
Once we have https://github.com/mozilla/addons-code-manager deployed to [dev](https://github.com/mozilla/addons-code-manager/issues/327), let's add a link to the file viewer from reviewer tools. 

Let's add a link on this panel below, **in addition** to the existing *Contents* link. This will help the reviewers start testing out the new site. They will still be able to access the old file viewer if they need to.

<img width="261" alt="screenshot 2019-03-07 16 30 07" src="https://user-images.githubusercontent.com/55398/53994002-93f5c200-40f6-11e9-99bb-5f4fb8b8a23e.png">

This screenshot is from https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/couponshelper12#history

The link will obviously need a [Geocities icon](https://gifcities.org/?q=new) like:

![new3](https://user-images.githubusercontent.com/55398/53994118-ff3f9400-40f6-11e9-940e-ab9b7f546b1a.gif)

**Comment by kumar303** [comment]
When discussing this with security, we want to only show this link to one or two reviewers while testing it. Maybe we can use a waffle flag that lets us turn it on for select users.

**Comment by kumar303** [comment]
I turned on this flag to make it accessible to all users on -dev

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev

A link to the new code manager is present on an addon review page  - except for static themes
![image](https://user-images.githubusercontent.com/31961530/55312768-f2505f00-546e-11e9-8b1f-25eb30405742.png)


I found an issue with search tools for which I filed #11085 


@kumar303 @jvillalobos regarding static themes, should we consider adding a link to code-manager on the review page? I can see that we could easily support this, so it is just a matter of deciding if we want to expose this link or not. 
https://code.addons-dev.allizom.org/en-US/browse/616605/versions/1655484/

**Comment by jvillalobos** [comment]
Current theme review pages don't have source links, so let's keep it that way for now
