### ISSUE TITLE
Changes to response shape for browse/compare API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#10891]
After having worked with the API for awhile, there are some changes to the shape of the response that we would like to request to better support the code-manager front end.  These include:

- Return `entries` as a top-level property of `version`, as opposed to having them embedded in the `file` property. This is because we need them to generate the file tree, which makes sense in the context of a version, but we don't really care about them when we are looking at an individual file.
- Return the following data, which is currently returned in an `entry`, with the `file` instead: `mimetype` and `sha256`. Note that we do not need this data for an `entry` (which is just used to create the file tree), but do need it for an individual file.
- Return the following data, which is currently returned in an `entry`, with the `file` as well: `filename` and `mime_category`. Note that we need this data both for an `entry` and for the `file`.

@willdurand Can you please take a look at this and confirm whether this covers all of the changes you were hoping for?

**Comment by kumar303** [comment]
As discussed on IRC, I moved this down in priority: https://github.com/orgs/mozilla/projects/53
