### ISSUE TITLE
Enable python3 on stage (and prod)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10890]
Now python3 is "ready" need to switch over the circleci config, (etc?,) to build the tag build that goes to stage with python3 also.

**Comment by diox** [comment]
We should be building both py2 and py3 images each tag&commit, so it's up to ops to enable it for stage/prod. Moving to @autrilla.

**Comment by autrilla** [comment]
I've changed our Jenkins Dockerhub hook so it triggers from py3 builds instead of py2.

I think we might want to let this linger in stage for a few weeks before going to prod with it, though.

cc @bqbn.

**Comment by diox** [comment]
>  I think we might want to let this linger in stage for a few weeks before going to prod with it, though.

The argument against it is that we would no longer have a testing environment that is like production. We've had Python 3 on dev for a while now and haven't found issues for some time, IMHO it's unlikely we'd find more just by letting it live on stage for a few weeks.

**Comment by bqbn** [comment]
OK with pushing py3 to -prod with Dev support.

I seem to remember we experienced some static contents uploading issue in -dev environment. I also seem to remember it was said that the same issue wouldn't happen for -stage and -prod. It may be worth verifying it.

**Comment by diox** [comment]
True, that was a deployment issue, it should be fixed but that's worth double-checking once we deploy Python 3 on stage.

**Comment by ioanarusiczki** [comment]
@autrilla 
Release testing was completed [here ](https://testrail.stage.mozaws.net/index.php?/plans/view/16076) No regressions were found. 
Verified on AMO stage with FF65 (Win10).
