### ISSUE TITLE
Update circleci ubuntu version to 14.04

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#10906]
We are using a relatively (heh) old version of ubuntu to run our tests on CircleCI. I am wondering if we can update to the newest available version and if that may help speed up some jobs as well as some weird failures the UI-tests would have.

There shouldn't be any compatibility problems as we mainly use docker anyways.

Thoughts?

**Comment by EnTeQuAk** [comment]
Can we maybe use the *debian* version we are using on -dev, -stage and -prod? Which would be debian stretch.

**Comment by jrbenny35** [comment]
I don't think debian is an options. IDK how well docker-in-docker would work either...

**Comment by EnTeQuAk** [comment]
> I don't think debian is an options. IDK how well docker-in-docker would work either...

Why is it not? Are the selenium images that stuck on ubuntu images?

**Comment by jrbenny35** [comment]
@EnTeQuAk Isn't Ubuntu debian based? The only options are ubuntu 12 and 14, we are using 12 currently.
