### ISSUE TITLE
Add links to extension workshop from main header

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#10909]
UX to define placement and copy - here's a copy of the header for reference.

![Manage_My_Submissions____Developer_Hub____Add-ons_for_Firefox](https://user-images.githubusercontent.com/1514/54145465-fff16680-4425-11e9-884e-f16ea3538af4.jpg)

**Comment by caitmuenster** [comment]
@pwalm, flagging you here as well. I can help with copy. :)

**Comment by caitmuenster** [comment]
I got to this page by going from AMO --> Manage My Submissions. It looks like this page (https://addons.mozilla.org/developers/addons) is the older version of the Developer Hub (https://addons.mozilla.org/developers/). 

Rather than add a header to Extension Workshop to https://addons.mozilla.org/developers/addons, could we instead send traffic to https://addons.mozilla.org/developers/, which will be updated to include a link out to Extension Workshop as part of issue #10910? 

/cc @jvillalobos

**Comment by jvillalobos** [comment]
`/developers/addons/` and `/developers/` serve different purposes. In `/developers/`, if you click on View All Submissions, you go to `/developers/addons/`, which is the only place where you can navigate through all your add-ons. We intended to merge those pages eventually, but it hasn't happened.

**Comment by caitmuenster** [comment]
Got it. 👍

For the header, let's add "Extension Workshop" between "My Add-ons" and "Documentation." 

![Insert Extension Workshop Link - Manage My Submissions](https://user-images.githubusercontent.com/23342476/54638310-fe3c2a00-4a47-11e9-812f-e79ee331c1d0.png)

Link target should go to https://extensionworkshop.com/.

**Comment by jvillalobos** [comment]
UTM troll here. Please link to https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link

**Comment by caitmuenster** [comment]
We are hoping to land this in the next 1 - 2 weeks. @championshuttler, @suhailsinghbains, or @xu3u4, do you have any interest in picking this up?

Note: anyone is welcome to work on this! If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by championshuttler** [comment]
I am helping @anushka28 to solve it. 😄

**Comment by ioanarusiczki** [comment]
@caitmuenster @jvillalobos 
Extension Workshop link has been added to the following pages
https://addons-dev.allizom.org/en-US/developers/ logged in view
https://addons-dev.allizom.org/en-US/developers/ logged out view
https://addons-dev.allizom.org/en-US/developers/addons
All have the same utm parameters meaning they all redirect such as https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link

![extension workshop](https://user-images.githubusercontent.com/33448286/55008350-8c388780-4fe9-11e9-9a3b-6a11eaddde07.gif)


I left a longer comment in the frontend issue here https://github.com/mozilla/addons-frontend/issues/7696. I'm worried about the Register/Login button's state on this new page, and I can't tell if it's correct that from here the login/register can be made only on AMO prod so  I'm still waiting for some feedback.
Also I don't know if this is planned to go straight in production this week.

**Comment by eviljeff** [comment]
Yes, I thought the (inaccurate) Login/register button on extensionworkshop was changing to something like "Developer Hub".

**Comment by jvillalobos** [comment]
It's correct that the button should lead to Dev Hub on AMO, but I agree that changing the label to something else would be an improvement. That's up to @caitmuenster and @mconca and shouldn't block the AMO changes, though.
