### ISSUE TITLE
Version does not exist for git-extraction (after new upload)

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10900]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5327914/

```
DoesNotExist: Version matching query does not exist.
(1 additional frame(s) were not displayed)
...
  File "olympia/amo/decorators.py", line 108, in wrapper
    return f(*args, **kw)
  File "olympia/versions/tasks.py", line 118, in extract_version_to_git
    version = Version.objects.get(pk=version_id)

DoesNotExist: Version matching query does not exist.
```

**Comment by EnTeQuAk** [comment]
I checked sql.telemetry.mozilla.org and the versions for all failures actually exist.

The question is, why does this still happen. I wonder if the easiest solution would be a celery retry, we don't really care about timely extraction usually.

**Comment by eviljeff** [comment]
where is the task called from?  If it's in an atomic block (like most of our views) then the version id won't exist in the database at the time the task was created so if the task starts straight away (i.e. before the atomic block ends and the transaction is committed) then it will fail.

**Comment by diox** [comment]
We have post-request-task for this, so if it's triggered from a view it should be fine (the task should only be triggered once the request is processed, which means the transaction should have been committed)

**Comment by EnTeQuAk** [comment]
> where is the task called from? 

From `Version.from_upload` - at the same time as `generate_static_theme_preview`
