### ISSUE TITLE
Git Storage: Handle newline changes

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#10903]
We currently don't handle line-based newline changes properly.

e.g https://addons-dev.allizom.org/api/v4dev/reviewers/addon/502955/versions/1541786/compare_to/1541798/?lang=en-US

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I'm not too sure what needs to be verified for this issue.
I have tested around the new compare files api and mentioned my results in https://github.com/mozilla/addons-server/issues/10323#issuecomment-472037270 but this issue seems to be pointing to something more specific.

**Comment by EnTeQuAk** [comment]
This is fixing an issue with newline changes, e.g if the old or the new versions of a specific file (e.g manifest.json) doesn't have a newline at the end of the file.

I don't think it needs specific qa testing.
