### ISSUE TITLE
remove legacy search views

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10918]
We want to start removing more parts of the legacy frontend so search can go next.  The search templates (the search box) is only still exposed on the statistics pages (so it's being removed)

**Comment by eviljeff** [comment]
QA: just check the addons-server served parts of the site still work - in particular /statistics/ and the per-addon stats pages.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified on AMO dev and AMO stage - `Search for add-ons` and `Search for developer docs` search boxes were removed from dev hub pages. 
Final validation will be made tomorrow after completing the release testing.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev and AMO stage - FF65(Win10). Testing results are[ here](https://testrail.stage.mozaws.net/index.php?/runs/view/16281&group_by=cases:section_id&group_order=asc)
