### ISSUE TITLE
make dev, stage, and prod database schemas the same

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10916]
part of #3705 

https://bugzilla.mozilla.org/show_bug.cgi?id=1534594 for ops to get the schemas

**Comment by eviljeff** [comment]
Prod and stage were already the same (apart from the unused table removed in the PR); manually added the missing constraints and modified the columns on dev to match stage.  

I had to delete some (930) collections where the author_id didn't exist in users, but `on_delete=models.CASCADE` is specified on the model so that would have happened normally anyway.

**Comment by ioanarusiczki** [comment]
@eviljeff Anything particular qa should be investigating ? Please let us know.
Thanks!
