### ISSUE TITLE
Update logged-in /developers/ with links to extensions-workshop

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#10910]
Ux to define link copy and placement:

Currently looks like this for reference:
![Developer_Hub____Add-ons_for_Firefox](https://user-images.githubusercontent.com/1514/54145708-6bd3cf00-4426-11e9-8ca8-31083193d71e.jpg)

**Comment by caitmuenster** [comment]
@pwalm, we're also looking to add a link out to Extension Workshop somewhere in the top part of the page -- can we get your thoughts on where? 

Mid term plan: it'd be great to get a banner that goes to Extension Workshop to replace the "Welcome Back" banner. Would you have bandwidth to take that on in the next 2 - 3 weeks? If not, we can work around it. 

(We'll also add a link in the  "Documentation" section below."

**Comment by caitmuenster** [comment]
I'm going to narrow scope on this for the moment and request that we add Extension Workshop to the header between My Add-ons and Documentation."

![Dev Hub - Logged In to EW](https://user-images.githubusercontent.com/23342476/54639044-aef6f900-4a49-11e9-87cf-485233852aaa.png)

Next steps: 
- changes to the "Welcome Back" banner. I'm going to see if Turtle can design a promo banner for Extension Workshop.

**Comment by jvillalobos** [comment]
Revised link for tracking: https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link

**Comment by caitmuenster** [comment]
We are hoping to land this in the next 1 - 2 weeks.  @championshuttler, @suhailsinghbains, or @xu3u4, would any of you have any interest in picking this issue up?

**Comment by championshuttler** [comment]
@caitmuenster Sure, Let me try to take a look , in the meantime if someone else is able to raise PR, feel free to do that :)

**Comment by eviljeff** [comment]
> Revised link for tracking: https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link

Same `utm_source` for prod, dev and stage?

**Comment by caitmuenster** [comment]
Asking @jvillalobos to comment ^. :)

**Comment by jvillalobos** [comment]
Yes, it's used for keeping track of things in Google Analytics, so it shouldn't matter if it's dev, or others.

**Comment by ioanarusiczki** [comment]
This was already verified here https://github.com/mozilla/addons-server/issues/10909
with FF65(Win10).
