### ISSUE TITLE
reimplement/move/restyle statistics dashboard

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10920]
https://addons.mozilla.org/statistics/ and the per add-on statistics dashboards (e.g. https://addons.mozilla.org/firefox/addon/ublock-origin/statistics/) are the last remaining "user frontend" pages served by addons-server, complete with the legacy frontend header.  With the rest of the legacy frontend pages being deleted from addons-server we need to do something with /statistics too.  Options as I see them:

A. Re-implement fully on addons-frontend.   Probably not a huge amount of work on the addons-server side as the data is already served as json to be rendered client side; unknown amount of work on the addons-frontend side.  The "best" solution, ignoring development time needed.

B. "move" /statistics under developer hub, or at least adopt the template.  Easy-ish from a development point of view for addons-server (no addons-frontend work).  But the standard /developers template UI is a poor fit in terms of links for statistics, and pretty ugly compared to user frontend.  (The developer hub landing page is different and slightly better but is stand-alone and will likely be removed with #10911)

C. Make some changes to statistics header but otherwise keep it as is.  At the minimum we need to drop the popups that list the extensions and themes categories and the other popups, along with the search box (it's the legacy frontend search).  Probably equally easy as B) but we need a bit of UX guidance about what links to have/keep.  Biggest downside for me is it's keeping a 3rd UI style for AMO (or 4th! if you count extensionworkshop or the current devhub landing page)

@jvillalobos thoughts

**Comment by jvillalobos** [comment]
`/statistics/` should be dropped (there might a dupe issue about it).

As for individual add-on dashboards, I would prefer that they use the frontend style (A) because they can be public, so it makes sense that they look more like user pages than dev pages.

**Comment by muffinresearch** [comment]
@eviljeff @jvillalobos It would also be good to re-evaluate what impact removing /statistics/ would have on the backend and find out if there would be any opportunity to overhaul the backend. If nothing else it's worth having a conversation about it before we do a new implementation based on the existing data. IIRC there are quite a few moving parts behind stats and if there's an chance to simplify it we should take it. We'll need to talk to ops about this.

**Comment by eviljeff** [comment]
In the meantime, to unblock removing large amounts of obsolete code (and django2 rollout), we will do a minimal version of C)

**Comment by eviljeff** [comment]
Logged #11037 for dropping the site-wide Statistics dashboard and will keep this issue open for the per-add-on dashboards (for now; a reimplementation would be under a different repo).
