### ISSUE TITLE
Remove trailing `\n` in `changes[].content` (Compare API)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#10932]
The Compare API returns sets of changes with a `content` field for each `change`. This `content` field contains a line in the file. According to the undocumented `react-diff-view` API, lines should not have a trailing newline.

These newlines cause blank lines to be displayed and the rendered diff is not correct anymore. In the screenshot below, the change should be marked on the line containing the `version` JSON field.

![Screen Shot 2019-03-14 at 14 22 19](https://user-images.githubusercontent.com/217628/54360182-9a3eed80-4664-11e9-8104-42149a10287d.png)

Expected output:

![Screen Shot 2019-03-14 at 14 24 05](https://user-images.githubusercontent.com/217628/54360282-d96d3e80-4664-11e9-872d-724762e10471.png)

Could we remove that in the API? Otherwise, we'll have to do it in addons-code-manager, which is also fine but maybe it's better in the API since this API is already tailored for `react-diff-`view`.

**Comment by EnTeQuAk** [comment]
Does the same apply to the `header` field too?

**Comment by AlexandraMoga** [comment]
Newlines are no longer part of the compare file api response:

Before:
![image](https://user-images.githubusercontent.com/31961530/54808706-af7dd280-4c89-11e9-8f87-981dd8abb9fb.png)

After:
![image](https://user-images.githubusercontent.com/31961530/54808696-abea4b80-4c89-11e9-8eab-0b1040e37bc4.png)
