### ISSUE TITLE
Refactor validation tasks chaining to avoid passing results to each task

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10933]
With the way the validation tasks are chained together right now, it's difficult to add a new task to the chain, because we pass the results to the next task in the chain, meaning any addition of a new task forces us to rewrite the signature of the rest of them. We should refactor that to avoid it.

QA:
- Make sure add-on submission / validation still works, including validation of old existing versions that didn't necessarily have a validation result attached before (might need a developer to help you find/create one)
- Make sure validation *errors* are still displayed correctly, when uploading a non-zip for instance

**Comment by diox** [comment]
Related: https://github.com/mozilla/addons-server/issues/9068 would be nice as well but I've ran into some trouble when attempting to do it... see #6667.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF65, Win10x64

- listed addon submissions are working
- validation results are generated, both for new submissions and old existing addons which had their validation results erased 
- validation errors are rendered as expected; I've tried to cover as many as possible for each add-on type
