### ISSUE TITLE
Firefox disables dictionaries because they have the wrong type

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1093]
https://addons.mozilla.org/en-US/firefox/language-tools/ lists 126 dictionaries, only 60 of them specified the correct add-on type (64) so they are actually recognized as a dictionary by Firefox.

AMO correctly identified them despite the wrong type due to some magic in https://github.com/mozilla/olympia/blob/master/apps/files/utils.py#L230

Firefox on the other hand relies on the correct add-on type in `install.rdf`. This causes all add-ons that have either a different add-on type or no add-on type at all to be disabled because of a missing signature.

This issue is about two things:

- [x] We might need to repack the affected dictionaries and set the correct add-on type.
- [x] We should probably add a validator warning if we recognize a dictionary but the add-on type is wrong or missing.

**Comment by eviljeff** [comment]
> We should probably add a validator warning if we recognize a dictionary but the add-on type is wrong or missing.

If Firefox is going to misclassify them, it should probably be an error instead of a warning.

**Comment by wagnerand** [comment]
Working example (correct add-on type): https://addons.mozilla.org/en-US/firefox/addon/united-states-english-spellche/
Broken example (wrong/missing add-on type): https://addons.mozilla.org/en-US/firefox/addon/latin-dictionary/

List of affected add-on GUIDs:
´´´
af-ZA@dictionaries.addons.mozilla.org
am-ET@dellalibera.sf.net
an-ES@dictionaries.addons.mozilla.org
asturianu@dictionaries.addons.mozilla.org
az-IR@dellalibera.sf.net
be-classic@dictionaries.addons.mozilla.org
be@dictionaries.addons.mozilla.org
bg-BG@dictionaries.addons.mozilla.org
cy-GB-1@dictionaries.addons.mozilla.org
eegbe@dictionaries.addons.mozilla.org
el-GR@dictionaries.addons.mozilla.org
en-NZ@dictionaries.addons.mozilla.org
eo-EO@dictionaries.addons.mozilla.org
es-MX@dictionaries.addons.mozilla.org
es-ve@dictionaries.addons.mozilla.org
et-EE@dictionaries.addons.mozilla.org
eu@dictionaries.addons.mozilla.org
fa-IR@dictionaries.addons.mozilla.org
fa@dictionaries.addons.mozilla.org
fur-IT@dictionaries.addons.mozilla.org
gl-es@dictionaries.addons.mozilla.org
gu-IN@dellalibera.sf.net
hi-IN@dellalibera.sf.net
hr@dictionaries.addons.mozilla.org
hsb@dictionaries.addons.mozilla.org
ht-HT@dictionaries.addons.mozilla.org
hu@dictionaries.addons.mozilla.org
hunspell-ru@dictionaries.addons.mozilla.org
id@ewesewes.net
indlinux-telugu@lists.sourceforge.net
is@dictionaries.addons.mozilla.org
ko-KR@dictionaries.addons.mozilla.org
ku@dictionaries.addons.mozilla.org
la@dictionaries.addons.mozilla.org
ln-CD@dictionaries.addons.mozilla.org
manuel@elarte.coop
mg-MG@dellalibera.sf.net
mi@dictionaries.addons.mozilla.org
mk-MK@dictionaries.addons.mozilla.org
mn@dictionaries.addons.mozilla.org
mr-IN@dictionaries.addons.mozilla.org
mugunth@thamizha.com
ne-NP@dictionaries.addons.mozilla.org
nr-ZA@dictionaries.addons.mozilla.org
ns-ZA@dictionaries.addons.mozilla.org
ny-MW@dellalibera.sf.net
or_IN@dellalibera.sf.net
pa_IN@dellalibera.sf.net
pap-an@lasindias.org
roa-ES-val@dictionaries.addons.mozilla.org
sk@dictionaries.addons.mozilla.org
sq-AL@dictionaries.addons.mozilla.org
Srpski_latinica@dictionaries.addons.mozilla.org
ss-ZA@dictionaries.addons.mozilla.org
st-ZA@dictionaries.addons.mozilla.org
sw-TZ@dellalibera.sf.net
tamildic@ulagam.net
ts-ZA@dictionaries.addons.mozilla.org
ur@dictionaries.addons.mozilla.org
uz@dellalibera.sf.net
ve-ZA@dictionaries.addons.mozilla.org
xh-ZA@dictionaries.addons.mozilla.org
yi@dictionaries.addons.mozilla.org
zu-ZA@dictionaries.addons.mozilla.org
```

**Comment by andymckay** [comment]
A repack is a problem, it requires a push to prod and there's lots of risks and chances to upset people.

These lang packs are just plain wrong, can we email all the authors and tell them of the problem and ask them to re-upload.

**Comment by wagnerand** [comment]
We theoretically can, and I did a similar thing about Thunderbird langpacks in the past. Only a fraction of developers even replied. Even less of them understood what the issue is.
If we go that route, expect more than 50% of the add-ons not getting updated at all. If we are lucky and the developer decides to update their add-on it will mostly take days if not weeks.

**Comment by iant-tui** [comment]
You can do both - email the authors asking them to update, and repack for those who don't respond within a certain timescale.

**Comment by wagnerand** [comment]
What would a be reasonable timescale? I think one week would be too long given the usage numbers, also we have holidays coming up.
If we do a repack anyway, we don't need to ask them to do it themselves first. I don't expect many of them to submit a new version right away.

**Comment by andymckay** [comment]
Without ops support its going to take us a while to get them repacked, unless we just upload new ones on their behalf.

**Comment by andymckay** [comment]
We can do this manually right, get each affected langpack, alter that one field, re-upload and let the developer know. Its tedious, but doable.

**Comment by wagnerand** [comment]
I guess we could do that, yeah.

We should still warn or fail during upload if we recognized a dictionary with a wrong type, because we probably don't want to do this manual fix more than once.

**Comment by wagnerand** [comment]
All affected add-ons have been manually fixed by uploading a new version that has the correct add-on type.

I'd appreciate if we could add the validator fail for dictionaries that don't have the correct type, so we never ever have to do this again.

**Comment by iant-tui** [comment]
https://addons.mozilla.org/en-GB/firefox/addon/british-english-dictionary/ hasn't been updated

**Comment by wagnerand** [comment]
That is, because it is not part of https://addons.mozilla.org/en-us/firefox/language-tools/

I will upload a fixed version shortly.

**Comment by EnTeQuAk** [comment]
As https://github.com/mozilla/amo-validator/issues/364 is fixed now and will go out today, dos this "fix" this issue here as well?

**Comment by wagnerand** [comment]
Yes. Sorry for the late reply.
