### ISSUE TITLE
Cannot upload new version of SingleFile

### ISSUE THREAD

**Issue by gildas-lormeau** [mozilla/addons-server#10947]
### Describe the problem and steps to reproduce it:
I upload a new version of SingleFile. 

### What happened?
I see it approved, in the queue, then it disappears a few seconds after without any error or warning. 

### What did you expect to happen?
I should be able to upload new versions or an error should be displayed.

### Anything else we should know?
The page of the extension: https://addons.mozilla.org/en-US/firefox/addon/single-file/
The version should be 1.9.90, or 1.9.91, or 1.9.92.
Post on the AMO forum: https://discourse.mozilla.org/t/cannot-update-extension/37032

**Comment by diox** [comment]
Hi,

That looks like a replication issue with our MySQL replica databases. Your uploads were recorded properly, nothing is lost, but somehow the replica used for read operations (e.g. viewing pages) is out of date.

We're looking into it.

**Comment by diox** [comment]
To prove that this is a replication issue, I can see the data for a few seconds if I make a modification elsewhere (because that sets a short-lived cookie pinning reads to the primary db)

**Comment by gildas-lormeau** [comment]
@diox Thanks for the info. Is there any way for me to circumvent this issue?

**Comment by diox** [comment]
Sorry, there is no easy way around this. It looks like quite a serious desync between our primary and replica databases, best for you to wait for the issue to be resolved. I've paged our ops team, we'll update this issue when there is new information.

**Comment by diox** [comment]
The problem should have been resolved by ops (https://bugzilla.mozilla.org/show_bug.cgi?id=1535832)

**Comment by gildas-lormeau** [comment]
Yes, I confirm the version is now available. Thanks!

**Comment by blackzhen** [comment]
> 
> 
> Sorry, there is no easy way around this. It looks like quite a serious desync between our primary and replica databases, best for you to wait for the issue to be resolved. I've paged our ops team, we'll update this issue when there is new information.



> 
> 
> Hi,
> 
> That looks like a replication issue with our MySQL replica databases. Your uploads were recorded properly, nothing is lost, but somehow the replica used for read operations (e.g. viewing pages) is out of date.
> 
> We're looking into it.

I also can not upload a new version. could you help me ?

**Comment by diox** [comment]
@blackzhen : the original issue described here should be fixed. If it's still happening for you, please open a new issue for your problem, detailing what add-on it is happening with, what version you're trying to upload, etc.

**Comment by diox** [comment]
Nvm I saw that you opened https://github.com/mozilla/addons-server/issues/10949 ; it is indeed a different problem.
