### ISSUE TITLE
tidy up statistics dashboard base templates

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#10952]
#10920 has been logged to reimplement the statistics dashboards on addons-frontend but in the meantime we should remove as much of the legacy-frontend UI from the base templates used for statistics as possible (e.g. drop the "Extensions Themes Collections More…" links and popups).  The search box was removed in #10918

**Comment by ioanarusiczki** [comment]
@eviljeff Verified this on AMO dev - FF66(Win10)
1. The menu from the header of the individual statistics page - Extensions Themes Collections More is no longer available.  All the links from this menu were redirecting the user to the new AMO pages (except the Complete Themes which returned a 404).  
Let me know if it's ok as it is now.

![header removed](https://user-images.githubusercontent.com/33448286/55330429-b1217480-5499-11e9-8ada-9c37378a61db.gif)

2. The general statistics https://addons-dev.allizom.org/statistics/ redirects to AMO.
