### ISSUE TITLE
Remove "firefox57" tags from existing add-ons and associated code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10968]
Like #7189 but for the `firefox57` tag: remove the code, remove it from existing add-ons in the database. There is a catch though: there might be links for AMO search with that tag used in the wild, so we need to accept this tag during search and do no filtering with it.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF66

- `firefox57` tag was removed form existing addons (listed and unlisted)
- `firefox57` tag is no longer automatically added when a new webextension/new version is submitted
- the `firefox57` search query doesn't interfere with search results, i.e, the following queries will bring the same results:

https://addons-dev.allizom.org/en-US/firefox/search/?tag=firefox57 is the same as https://addons-dev.allizom.org/en-US/firefox/search/
