### ISSUE TITLE
Update header drop down options on Manage My Submissions

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#10966]
A few drop down options need to be updated on the header of the [Manage My Submissions](https://addons.mozilla.org/developers/addons) page. 

**Documentation:** 
- "Lightweight Themes" should be renamed to "Themes." Link target can remain the same. 

**Community & Support**
- The link target for "More Sources" should go to https://extensionworkshop.com/#connect (though @jvillalobos may want to add a UTM parameter).

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by jvillalobos** [comment]
Yup, please use this URL instead https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link#connect

**Comment by ioanarusiczki** [comment]
Documentation -> Lightweight Themes was replaced with  Themes 

<img width="461" alt="themes" src="https://user-images.githubusercontent.com/33448286/55150984-f5d5a480-5155-11e9-974d-8924d4144dbc.png">

More Resources goes to https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link#connect

verified on AMO stage - FF66 (Win10)
