### ISSUE TITLE
Remove obsolete database columns in files table

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#10977]
The database column `files.is_packaged` is not used anywhere in the code, we should be good to just drop it.

**Comment by diox** [comment]
If we wait until after the push that fixes https://github.com/mozilla/addons-server/issues/7189 we'll be able to drop `jetpack_version` and `requires_chrome` with it, minimizing the number of migrations that alter files.

**Comment by diox** [comment]
And a 4th one: `is_multi_package` once https://github.com/mozilla/addons-server/issues/10978 is pushed
