### ISSUE TITLE
Export my Legacy add-ons Collection for me

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#10985]
### Describe the problem and steps to reproduce it:
See https://discourse.mozilla.org/t/how-to-list-legacy-add-ons/36709

### What happened?
Cannot access it.

### What did you expect to happen?
I need it.

### Anything else we should know?
Please export it for me.

**Comment by eviljeff** [comment]
I replied in the discourse thread with a WBM link.  The legacy add-ons aren't available via AMO any more so they get filtered out.
