### ISSUE TITLE
Stop building python 2 images

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#10986]
The opposite of https://github.com/mozilla/addons-server/issues/10385 : now that we're running Python 3 in all environements are are not likely to switch back, let's stop building Python 3 images.

**Comment by AlexandraMoga** [comment]
Does this require any QA?

**Comment by diox** [comment]
I don't think so. We've verified that dev has been updated correctly and is using python 3 (https://addons-dev.allizom.org/__version__)
