### ISSUE TITLE
Links to download files in the Reviewers API responses don't work because of an authentication problem

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#10994]
We cannot use the `download_url` in code-manager because those links require a token-based authentication (like API calls). Yet, this URL will be given to the users in order to download files.

**Comment by EnTeQuAk** [comment]
That link will be moved out of the API instead. We discussed this in IRC and it was a bad idea :man_shrugging: 	

We'll use a regular django view that makes use of cookie-based authentication which will work given the reviewer most certainly is authenticated with the reviewer tools anyway.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev, now that the code-manager UI is available. 
Looking at the below example, there is a link that allows users to download files from the inspected addon version.

Link sharing is also possible: users with the required permissions will be prompted to download the file whereas users without the necessary access will see a 404. 

@EnTeQuAk @willdurand 
The file contents however are not rendered as expected though. For the below scenario, I expected to see the contents of the manifest in JSON:
https://code.addons-dev.allizom.org/en-US/browse/3006/versions/1541682/
![2019-04-01_16-33-47](https://user-images.githubusercontent.com/31961530/55334436-f21d8700-54a1-11e9-95fd-28c43092747b.gif)

**Comment by EnTeQuAk** [comment]
That's quite unexpected, I'll dig into that. I suspect the streaming download to may be a problem but it wasn't in local testing afair.

**Comment by willdurand** [comment]
I confirm this isn't working for me either :/

**Comment by EnTeQuAk** [comment]
Filed https://github.com/mozilla/addons-server/issues/11118 for that

**Comment by AlexandraMoga** [comment]
Given that we have #1118  as a follow up, I will mark this issue as verified fixed.
