### ISSUE TITLE
Json syntax errors in the manifest are triggering an unexpected error during validation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10992]
Potentially a regression from https://github.com/mozilla/addons-server/pull/10553

STR

1. Create an add-on package
2. Make sure that your manifest.json has a syntax error, i.e an extra `, ` (see attached example)
3. Submit the addon on AMO

Actual result:
The validation fails with an unexpected error

Expected error:
A message that mentions the JSON parsing error would be more helpful

Notes:
- reproduced on all AMO servers with FF66, WIn10x64

Example: [manifest syntax errors.zip](https://github.com/mozilla/addons-server/files/2997073/manifest.syntax.errors.zip)

![image](https://user-images.githubusercontent.com/31961530/54832603-24bac900-4cc5-11e9-9bca-ed1c1647128a.png)

**Comment by diox** [comment]
I've bisected it down locally and it's definitely a regression from that change yes. It used to say both `Could not parse the manifest file.` and `Sorry, we couldn't load your add-on.` (which wasn't awesome, but much better than what we have now).

**Comment by AlexandraMoga** [comment]
@diox I've verified this on -dev and JSON parsing errors are more relevant now. 
However, I'm receiving two errors for the same (one) invalid entry in the manifest JSON file. I'm using the same addon posted in the STRs.

https://addons-dev.allizom.org/en-US/developers/upload/28d1852040a64e189c6d343bd2b0c363
![image](https://user-images.githubusercontent.com/31961530/55168002-af467100-517a-11e9-91d2-1a124136e970.png)

**Comment by diox** [comment]
Yes, previously there were also 2 messages but it was even less useful ones :) You can file an issue over `addons-linter` for this, that's directly what it's returning. I don't think it's a high priority issue.

**Comment by AlexandraMoga** [comment]
Filed https://github.com/mozilla/addons-linter/issues/2528
