### ISSUE TITLE
Invalid archive throws an unexpected error during validation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#10993]
Potentially a regression from https://github.com/mozilla/addons-server/pull/10553

STR:

1.  Create an archive that is not accepted by AMO for upload, i.e a `.tgz`, `.tar` etc
2.  Change its extension to a type that we support, i.e `.zip` (see attached example)
3.  Upload the package on AMO and check the validation results

Actual result:
Validation fails with an unexpected error

Expected result:
A validation error that points to the fact that the archive is not valid

Notes:
- reproduced on all AMO servers with FF66, WIn10x64

Example: [tar archive renamed as zip.zip](https://github.com/mozilla/addons-server/files/2997015/tar.archive.renamed.as.zip.zip)

![image](https://user-images.githubusercontent.com/31961530/54831411-f5a35800-4cc2-11e9-87ce-4d4bac62d25f.png)

**Comment by diox** [comment]
Like https://github.com/mozilla/addons-server/issues/10992 it is indeed a regression from #10553. However, the message we had before (`Could not parse the manifest file.` and `Sorry, we couldn't load your add-on.`) was kinda bad already. It could be much better, we can say that it doesn't look like a xpi/zip archive (we just need to special case `.crx` files).

**Comment by diox** [comment]
Note: there is a slight difference with #10992: Because we're repacking zip files, we want to raise the error early, and not let the linter fire at all here (like we do now, except we're throwing a generic error message). Where as in #10992 the right solution is probably going to be letting the linter handle that.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF66, Win10x64

Invalid archives will raise the following error: `Invalid or corrupt add-on file.`
Unsupported archives are still raising the expected error - `The filetype you uploaded isn't recognized` - and valid `.crx` archives are not raising any errors.

@diox we are raising a more relevant error now, but we are still showing the old "unexpected' error next to that. Definitely not a big issue, but maybe something to be handled at some point.

https://addons-dev.allizom.org/en-US/developers/upload/50bfea0895294d66b5f5cc088fa8c06c
![image](https://user-images.githubusercontent.com/31961530/55231598-d446ec80-522b-11e9-911a-a7da5ebe0924.png)

**Comment by diox** [comment]
Yeah, we used to do that and it's a bit annoying to get right. I kept the generic error because it does give some info.
