### ISSUE TITLE
Weigh older reviews less than newer ones

### ISSUE THREAD

**Issue by bobbobob1** [mozilla/addons-server#11008]
### Describe the problem and steps to reproduce it:

A good example is the [Stylish addon](https://addons.mozilla.org/firefox/addon/stylish/reviews/).

### What happened?

It has 3.6 stars.

### What did you expect to happen?

It should have less stars because obviously it's *very* unpopular since the addon was sold to new "owners".

### Anything else we should know?

I don't have a good algorhythm proposal as it surely needs some testing, but some addons heavily profit from ratings for older versions. The parameters should include age of the extension, age of the current version, age of the rating, total number of ratings, total number of users. A two year old rating isn't worth much, except there are no newer ratings.

Offtopic: Seen from how SimilarWeb behaved in the past as owner of Stylish, I wouldn't wonder if many of the newer anonymous commentless 5-star ratings are fakes from their employees but without further user details (date of account creation, ip address, review activity, comments) this is speculation.

**Comment by Vishal19111999** [comment]
I would like to solve it as a first issue. Anyone please guide me

**Comment by diox** [comment]
Hi,

This is not a good first bug - it's more of a feature request and it doesn't have a clear fix at the moment. If you pick issue that don't have the good first bug label, please make sure you understand what the issue is about and that you can fix it yourself with little guidance.

**Comment by Vishal19111999** [comment]
@diox Ok, can you suggest me a good first bug?

**Comment by diox** [comment]
Sorry, I had not realized at the time, there aren't any good first bugs at the moment on addons-server. You can follow this query to see when we add some: https://github.com/mozilla/addons-server/labels/contrib%3A%20good%20first%20bug

In the meantime, you can still try to fix issues not assigned to anyone yet, particularly those with "contrib: welcome" label instead: https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome ; those are intended more as "good second bugs" of sorts, but depending on your skills that may still be something you can tackle.
