### ISSUE TITLE
Server error received when trying to approve a static theme

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11005]
**STR:**

1. Log in to AMO -dev with a theme reviewer account
2. Go the the static theme pending approvals queue 
3. Pick a theme to review - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/background-repeat-2
4. Try to approve it

**Actual result:**
A 500 error is received

**Expected result:**
Theme is successfully approved

**Notes:**
 - I suspect this is a signing error considering that it only happens with theme approvals, not rejections
 - possibly the same error that was reported several days ago with unlisted submissions 
 - reproduced on AMO -dev with FF66, Win10x64

**Comment by EnTeQuAk** [comment]
I asked in IRC wheather or not the autograph proxy is down.

A little bit of context: Last Friday we apparently moved to a proxy server that connects our -dev instance with the autograph staging instance.

That proxy appears to be down.

**Comment by AlexandraMoga** [comment]
I'm still having intermittent errors with theme approvals. 
Moreover, addon approvals - for listed and unlisted submissions - don't seem to be working at all.
They worked for a bit in the morning, but not anymore.

**Comment by EnTeQuAk** [comment]
This is again the autograph-proxy it seems as we are receiving `ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))` errors from the proxy now :-/

Already pinged autograph ops.

**Comment by EnTeQuAk** [comment]
This should have been fixed now, autograph-proxy got an increased file-size so that we shouldn't be running into issues like that.

Mind re-testing this again?

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I'm confirming that I haven't run into signing issues anymore. I've tested yesterday evening and again this morning.
