### ISSUE TITLE
Add a new "code-manager" FxA configuration in settings.py

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11015]
In order to allow authentication in https://github.com/mozilla/addons-code-manager, we need to add a new FxA configuration (`FXA_CONFIG`) named `code-manager` in the django settings.

**Comment by AlexandraMoga** [comment]
@willdurand as far as I can tell, the code-manager log in function is not fully set up yet because we are still waiting for #11019 and mozilla/addons-code-manager#463

I'm going to have to wait for those two issues to be closed in order to reliably test the authentication process.

**Comment by willdurand** [comment]
> @willdurand as far as I can tell, the code-manager log in function is not fully set up yet because we are still waiting for #11019 and [mozilla/addons-code-manager#463](https://github.com/mozilla/addons-code-manager/issues/463)

These two issues have been fixed actually, but there is a remaining issue here: https://github.com/mozilla/addons-code-manager/issues/486

**Comment by AlexandraMoga** [comment]
Verified on -dev with FF66, Win10x64

This is the log in request that is passed to FxA:
`https://addons-dev.allizom.org/api/v4dev/accounts/login/start/?config=code-manager`

I didn't encounter issues during log in, only at logout, which is already tracked in https://github.com/mozilla/addons-code-manager/issues/515
