### ISSUE TITLE
Does Django's `is_safe_url` accept subdomains?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11018]
Looking at the code of the `accounts/authenticate` endpoint, it looks like it is using `is_safe_url` to determine whether to send a redirect to the path specified by the client (`to` query parameter sent when starting the login dance by calling `login/start`) or redirect to the homepage.

https://github.com/mozilla/addons-server/blob/077126cd57508e6a534b5e779db436a3414d3bac/src/olympia/accounts/views.py#L355-L377

https://github.com/mozilla/addons-server/blob/077126cd57508e6a534b5e779db436a3414d3bac/src/olympia/accounts/views.py#L89-L93

In addons-frontend, we pass a relative path, e.g., `/en-US/firefox/`, to `login/start` but for code-manager, the API and the frontend don't have the same domain. I believe this can be a problem because it looks like passing a relative path in `?to=` means the API uses its own domain.

Yet, if we pass an absolute URL, e.g., `https://code.addons-dev.allizom.org/`, I believe `is_safe_url` will reject this URL because it does not have the same domain as `settings.DOMAIN`, hence the question in the title.

**Comment by EnTeQuAk** [comment]
I agree it'll reject the code.addons-dev.allizom.org redirect. But we'll be able to apply it through the `allowed_hosts` which I think should be fine.

cc @diox for an opinion though.

**Comment by diox** [comment]
Yeah `is_safe_url()` would reject it, we'll need to add it to `allowed_hosts`. While we're at it maybe add `requires_https=True` as well.

**Comment by eviljeff** [comment]
> While we're at it maybe add requires_https=True as well.

(we'll need to account for olympia.test and localhost which are just http)

**Comment by willdurand** [comment]
Given that we have the `fxa_config` in the caller, could we extend the `FXA_CONFIG` with extra hosts? Something like this:

```diff
diff --git a/src/olympia/accounts/views.py b/src/olympia/accounts/views.py
index ce4bb1390f..5a88ae86cc 100644
--- a/src/olympia/accounts/views.py
+++ b/src/olympia/accounts/views.py
@@ -86,8 +86,9 @@ LOGIN_ERROR_MESSAGES = {
 API_TOKEN_COOKIE = 'frontend_auth_token'
 
 
-def safe_redirect(url, action):
-    if not is_safe_url(url, allowed_hosts=(settings.DOMAIN,)):
+def safe_redirect(url, action, extra_allowed_hosts=()):
+    if not is_safe_url(url,
+                       allowed_hosts=(settings.DOMAIN,) + extra_allowed_hosts):
         url = reverse('home')
     log.info(u'Redirecting after {} to: {}'.format(action, url))
     return HttpResponseRedirect(url)
@@ -360,19 +361,22 @@ class AuthenticateView(FxAConfigMixin, APIView):
 
     @with_user(format='html')
     def get(self, request, user, identity, next_path):
+        fxa_config = self.get_fxa_config(request)
+        extra_allowed_hosts = fxa_config.get('extra_allowed_hosts', ())
         # At this point @with_user guarantees that we have a valid fxa
         # identity. We are proceeding with either registering the user or
         # logging them on.
         if user is None:
             user = register_user(self.__class__, request, identity)
-            fxa_config = self.get_fxa_config(request)
             if fxa_config.get('skip_register_redirect'):
-                response = safe_redirect(next_path, 'register')
+                response = safe_redirect(next_path, 'register',
+                                         extra_allowed_hosts)
             else:
-                response = safe_redirect(reverse('users.edit'), 'register')
+                response = safe_redirect(reverse('users.edit'), 'register',
+                                         extra_allowed_hosts)
         else:
             login_user(self.__class__, request, user, identity)
-            response = safe_redirect(next_path, 'login')
+            response = safe_redirect(next_path, 'login', extra_allowed_hosts)
         add_api_token_to_response(response, user)
         return response
```

Then we could add the following config to the FxA `code-manager` config:

```diff
diff --git a/src/olympia/conf/dev/settings.py b/src/olympia/conf/dev/settings.py
index 4fce737303..0df773b39b 100644
--- a/src/olympia/conf/dev/settings.py
+++ b/src/olympia/conf/dev/settings.py
@@ -138,6 +138,7 @@ FXA_CONFIG = {
         'profile_host': 'https://stable.dev.lcip.org/profile/v1',
         'redirect_url': 'https://addons-dev.allizom.org/api/v4/accounts/authenticate/?config=code-manager', # noqa
         'scope': 'profile',
+        'extra_allowed_hosts': ('code.addons-dev.allizom.org',)
     },
 }
 DEFAULT_FXA_CONFIG_NAME = 'default'
```

**Comment by willdurand** [comment]
> While we're at it maybe add `requires_https=True` as well.

If the idea above works, we could also add `requires_https` to the FxA config.

**Comment by willdurand** [comment]
FTR: two patches landed for enabling absolute URL redirects:

- https://github.com/mozilla/addons-server/pull/11056
- https://github.com/mozilla/addons-server/pull/11080

**Comment by AlexandraMoga** [comment]
@willdurand is the confirmation from https://github.com/mozilla/addons-server/issues/11015#issuecomment-479042395 enough to also consider this issue verified?

**Comment by willdurand** [comment]
> @willdurand is the confirmation from [#11015 (comment)](https://github.com/mozilla/addons-server/issues/11015#issuecomment-479042395) enough to also consider this issue verified?

Yes, I think so.
