### ISSUE TITLE
Create a new -dev OAuth client for code-manager

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11019]
Needs #11015

---

Using this console: https://oauth-stable.dev.lcip.org/console/, we need a new oauth client for the code-manager in -dev. This tool will generate a new client id/secret pair that should be given to ops to setup two environment variables in -dev:

- `CODE_MANAGER_FXA_CLIENT_ID`
- `CODE_MANAGER_FXA_CLIENT_SECRET`

According to [the addons-frontend config](https://oauth-stable.dev.lcip.org/console/client/cb6a5ba26feea430), the redirect URI should be:

```
https://addons-dev.allizom.org/api/v4/accounts/authenticate/?config=code-manager
```

**Comment by willdurand** [comment]
@autrilla @bqbn do you have access to the console? https://oauth-stable.dev.lcip.org/console/.

Could you please generate a new OAuth client for code-manager and add the ID/secret as new environment variables in -dev?

Name:

```
code-manager (latest)
```

Redirect URI:

```
https://addons-dev.allizom.org/api/v4/accounts/authenticate/?config=code-manager
```

**Comment by willdurand** [comment]
This has been done in -dev.

**Comment by AlexandraMoga** [comment]
I've confirmed in https://github.com/mozilla/addons-server/issues/11015#issuecomment-479042395 that the Log in function in code-manager is working, which, I believe, also verifies this issue.

**Comment by willdurand** [comment]
> I've confirmed in [#11015 (comment)](https://github.com/mozilla/addons-server/issues/11015#issuecomment-479042395) that the Log in function in code-manager is working, which, I believe, also verifies this issue.

Exactly, yes! Thank you.
