### ISSUE TITLE
Return absolute URLs in `validationURL` fields

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11034]
The `validationURL` field returned by the browse and compare APIs have relative URLs as values. In code-manager, we would need absolute URLs instead, mainly to fix this issue: https://github.com/mozilla/addons-code-manager/issues/480.

**Comment by willdurand** [comment]
Actually, let's not do this. This will break our nice local dev env in code-manager, forcing developers to log in locally (localhost) and on -dev.

**Comment by EnTeQuAk** [comment]
re-opening according to the discussion in #11128

**Comment by EnTeQuAk** [comment]
Sorry I stole this issue, I've been touching that part so I thought I'd just do it along the way too.
