### ISSUE TITLE
drop site-wide /statistics dashboard

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11037]
From https://github.com/mozilla/addons-server/issues/10920#issuecomment-472155187

> /statistics/ should be dropped

(per addon statistics dashboards should stay as they are)

**Comment by eviljeff** [comment]
QA:
* /statistics should be gone (and will redirect to homepage)
* per add-on statistics pages should still work as before.

**Comment by ioanarusiczki** [comment]
@eviljeff 
> per add-on statistics pages should still work as before. 

I verified it on AMO dev with FF66 (Win10) and it looks good. The individual statistics can be accessed from Manage my Submission page. If stats are public it can be accessed from the detail page of the extension or theme.

![individual statistics](https://user-images.githubusercontent.com/33448286/55240514-b2f0fb00-5241-11e9-9b9a-f46d441d8a71.gif)

> /statistics should be gone (and will redirect to homepage) 

Can you be more precise about the location of this link? I checked on AMO stage the dev hub pages, rev tools, django, I don't see an individual "statistics"

**Comment by eviljeff** [comment]
>>     /statistics should be gone (and will redirect to homepage)
> Can you be more precise about the location of this link? I checked on AMO stage the dev hub pages, rev tools, django, I don't see a general "statistics"

I'm not sure we still linked to it.  I was referring to the site-wide statistics dashboard that was removed by this patch.  Currently available at https://addons.mozilla.org/en-GB/statistics/

**Comment by ioanarusiczki** [comment]
@eviljeff I verified dropping /statistics with FF66(Win10). 
 
The following URLs will automatically redirect to AMO https://addons-dev.allizom.org/en-US/firefox/ (I also tried changing the locale or adding a period of time)

https://addons-dev.allizom.org/en-US/statistics/addons_in_use/
https://addons-dev.allizom.org/en-US/statistics/addons_created/
https://addons-dev.allizom.org/en-US/statistics/addons_downloaded/
https://addons-dev.allizom.org/en-US/statistics/addons_updated/
https://addons-dev.allizom.org/en-US/statistics/collections_created/
https://addons-dev.allizom.org/en-US/statistics/reviews_created/
https://addons-dev.allizom.org/en-US/statistics/users_created/

Acrhived Data URL from https://addons.mozilla.org/en-US/statistics/ redirects to https://addons-server.readthedocs.io/en/latest/topics/api/stats.html#archiving but it looks like it's always been that way.

**Comment by eviljeff** [comment]
> Acrhived Data URL from https://addons.mozilla.org/en-US/statistics/ redirects to https://addons-server.readthedocs.io/en/latest/topics/api/stats.html#archiving but it looks like it's always been that way.

We dropped the archived data api endpoints a while back, iirc.
