### ISSUE TITLE
ERROR: No container found for web_1

### ISSUE THREAD

**Issue by miphilomath** [mozilla/addons-server#11045]
### Describe the problem and steps to reproduce it:
While setting up the project following the steps as per https://addons-server.readthedocs.io/en/latest/topics/install/docker.html, above said error is popping up.

### What happened?
```
[philomath@cosmos addons-server]$ make initialize_docker 
docker-compose exec web make initialize
ERROR: No container found for web_1
make: *** [Makefile-os:57: initialize_docker] Error 1
[philomath@cosmos addons-server]$ vim Makefile-os
[philomath@cosmos addons-server]$ docker-compose logs | grep web_1
Attaching to addons-server_addons-frontend_1_8949804df0f8, addons-server_web_1_a6af281cab15, addons-server_rabbitmq_1_799671fa1b1a, addons-server_elasticsearch_1_5d329b7b1647, addons-server_autograph_1_1be3fa52d282, addons-server_worker_1_673a53aec5a0, addons-server_memcached_1_11a72674bcc3, addons-server_nginx_1_d33b30ec7dee, addons-server_mysqld_1_3331bcf31c90, addons-server_redis_1_75c2b67a4b2f
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
web_1              | /bin/bash: ./scripts/start-docker.sh: Permission denied
```
On running the script, 
```
[philomath@cosmos addons-server]$ sudo ./scripts/start-docker.sh
useradd: UID 1000 is not unique
id: ‘olympia’: no such user
Starting with user: 'olympia' uid: 
su: user olympia does not exist
```

### What did you expect to happen?
Run the command with success.

### Anything else we should know?
I guess, the error is related to user permission somehow, but I am not sure. If it is, we might need to update the docs as well.

**Comment by junngo** [comment]
I think that you don't run docker container. (Check docker state `docker ps`)
You should execute command `docker-compose up -d`.

**Comment by diox** [comment]
@miphilomath as @junngo said, did you execute `docker-compose up -d` first? In any case you should not try to run `./scripts/start-docker.sh` manually, it's an entry point for the docker container, not something you should run yourself.

**Comment by miphilomath** [comment]
Yes, I did. I followed all the steps as instructed [here](https://addons-server.readthedocs.io/en/latest/topics/install/docker.html).

**Comment by dsychin** [comment]
I am encountering the same problem trying to run the server locally on windows. I thought that it was a windows problem.
I can access the website at `olympia.test` but pretty much anything I do generates an error.
I haven't had the time to try it on linux yet.

**Comment by bhushan-borole** [comment]
Hello, I am running the command `docker-compose up -d`, but still I am getting this error.
Can somebody help me fix this error?
Thank you

**Comment by Mohammadnim123** [comment]
Just `docker-compose restart`

**Comment by Ssousuke** [comment]
> Just `docker-compose restart`

Thanks

**Comment by nicocasel** [comment]
If it can help, I had the same issue because my containers were not up (I thought they were, but they were not actually).
So, as other people already said, running this command solved it:
`docker-compose up -d`
