### ISSUE TITLE
Add-on name is getting prepended with Validation ID(?) in the Validation results page

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1104]
## steps to reproduce:
1. Log in and load https://addons-dev.allizom.org/en-US/developers/addon/validate
2. Validate an add-on
3. Click on the link - 'See full validation report'
4. Notice the add-on name

## observed behavior:
Add-on name is getting prepended with Validation ID(?) in the Validation results page

## screenshot:
https://www.dropbox.com/s/pwofreb2r0la52m/Screenshot%202015-12-16%2015.59.58.png?dl=0

## Notes:
behavior noticed on dev, stage and prod.

**Comment by ValentinaPC** [comment]
This was also tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1221945 .

Verified as fixed on AMO-dev FF49 (Win 7).
Postfix screenshots:
![2016-10-10_1446](https://cloud.githubusercontent.com/assets/15685960/19235174/b6e3c076-8ef8-11e6-8f18-c3be80f4885d.png)
![xpi](https://cloud.githubusercontent.com/assets/15685960/19235175/b6ea4c20-8ef8-11e6-8e25-c2a3f123518f.png)
![zip_001](https://cloud.githubusercontent.com/assets/15685960/19235184/c9a32d00-8ef8-11e6-9950-2b2f81fe88a2.png)
