### ISSUE TITLE
Add CORS headers to `validation.json` URLs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11048]
The code-manager client fetches the linter data using the `validation.json` endpoints:

```
https://addons-dev.allizom.org/en-US/developers/addon/androidadbplus2/file/252861/validation.json
```

Because we are not on the same domain (`code.a.m.o` vs` a.m.o`) and CORS are not configured, we cannot retrieve the data in -dev (and therefore stage and prod). We don't have this problem in local dev because we're using an insecure proxy.

**Comment by AlexandraMoga** [comment]
@willdurand I'm looking at the following request:

https://code.addons-dev.allizom.org/en-US/browse/616610/versions/1655489/ 

I can see that the that Origin is specified for `validation.json` and also linter messages are displayed in the UI in relation to the file that raised them.

![image](https://user-images.githubusercontent.com/31961530/55318834-575e8180-547c-11e9-9cd2-3c5f844b8a4f.png)

If you think there is something else to be verified, just let me know.

**Comment by willdurand** [comment]
@AlexandraMoga thanks, there should be CORS headers too (`Access-Control-*`):

![Screen Shot 2019-04-01 at 12 12 15](https://user-images.githubusercontent.com/217628/55320528-8de5cd80-5477-11e9-8fe7-59b9faf5cee9.png)

**Comment by AlexandraMoga** [comment]
@willdurand yes, CORS headers are present but mine were cached before:

![image](https://user-images.githubusercontent.com/31961530/55320908-0604c100-5481-11e9-972d-43676dd9c7be.png)

**Comment by willdurand** [comment]
Perfect then1
