### ISSUE TITLE
Stop using port 3000 for addons-frontend in Docker

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11054]
When running a docker image for local development of `addons-server`, `addons-frontend` is served on port 3000:

https://github.com/mozilla/addons-server/blob/9ea562f6b4ff7a58d2af69cfa6285f935660ba69/docker-compose.yml#L98-L100

This conflicts with the same port we use for local development of `addons-frontend` which runs directly from Node.js without Docker.

**Let's choose a different port for `addons-frontend` in Docker**

On macOS, this was confusing because Docker uses IPv6 to bind to localhost and that means there are no errors when Node.js starts up on the host machine. It happily binds to port 3000 and both servers run side by side on the same port. Firefox Nightly, Chrome, and curl would connect to Docker via http://localhost:3000 but my Firefox Release would connect to the locally running Node.js server.

**Comment by EnTeQuAk** [comment]
I quickly looked into this. That option can be set through environment variables so it's easy enough to do.

I'm wondering though, is `PROXY_PORT` (which defaults to 3000) the only port that needs changing? Webpack starts it's server on 3001 which sounds to me like that should be changed for the addons-frontend image too.

**Comment by willdurand** [comment]
We're not going to change the port in addons-server actually. We will update the config of addons-frontend to use a different port when used in combination with addons-server.

**Comment by ioanarusiczki** [comment]
@willdurand In case qa can check this on AMO dev please add some STR
Thanks!
