### ISSUE TITLE
Add `Access-Control-Allow-Credentials` to `validation.json` URLs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11060]
In #11048, we added CORS headers to the `validation.json` URLs but it looks like `Access-Control-Allow-Credentials` is missing.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

https://code.addons-dev.allizom.org/en-US/browse/616610/versions/1655489/

`Access-Control-Allow-Credentials` is set:

![image](https://user-images.githubusercontent.com/31961530/55321036-4e23e380-5481-11e9-9ba8-fc406efc6815.png)
