### ISSUE TITLE
Update type and category data sources to be filtered by recommended

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11067]
From the [PRD](https://docs.google.com/document/d/1fRxLy7h02tn1HBIlsTU_6h9DHmN8c3N6bg4JoxHF7J8/edit#heading=h.5kvm14zbadi2):

[Type](https://addons.mozilla.org/en-US/firefox/extensions/) and [category](https://addons.mozilla.org/en-US/firefox/extensions/appearance/) pages should only display Recommended extensions. This means that the “Top rated” and “Trending” shelves should either have their content filtered through the Recommended list (preferred), or should be replaced with different shelves. 

This might require frontend bugs to be filed to support switching data sources if required.

**Comment by diox** [comment]
Currently those blocks are built from simple calls to the search API with a specific `sort` parameter: the frontend then uses the first page of results for the blocks, and links to the corresponding searches.

So I think the following needs to happen:
- (addons-server) The search API needs to support a `is_recommended` parameter or something similar
- (addons-frontend) The frontend needs to add this parameter *only when building the blocks for the front page* (possibly adding a custom `page_size` as well)

The question that remains is what to do with the link in those blocks, that currently lead to the search. A simple way to deal with that could be to modify the search filtering interface to add a checkbox to only search through recommended content, and that way if the links are built the way they are now, it will lead to the search results as before, but with that checkbox already checked.

**Comment by jvillalobos** [comment]
Per https://github.com/mozilla/addons-server/issues/11068 and the PRD, we would be changing the meaning of the Featured only search filter so that it uses Recommended add-ons instead. So maybe it's just a matter of reusing that parameter.

**Comment by eviljeff** [comment]
@bobsilverberg can you look to see if there's any API needed to support this now?  I think `?recommended=true` to the search API would do it.

**Comment by bobsilverberg** [comment]
> @bobsilverberg can you look to see if there's any API needed to support this now? I think `?recommended=true` to the search API would do it.

Yes, that appears to be the case. We use the search API for all of the shelves on these pages.

**Comment by eviljeff** [comment]
okay, closing then as the work has been done in other issues.

**Comment by ioanarusiczki** [comment]
@eviljeff is this a "qa not needed" then?

**Comment by ioanarusiczki** [comment]
@eviljeff Looks good to me. I've tried with different categories for both extensions and staticthemes. - FF67(Win10).
Requests on AMO dev 
An example using type and category when `recommended =true`
https://addons-dev.allizom.org/en-US/firefox/search/?type=statictheme&recommended=true&category=nature&app=firefox
Then using query 
https://addons-dev.allizom.org/en-US/firefox/search/?type=statictheme&recommended=true&category=nature&app=firefox&q=bird

Also with the API 
https://addons-dev.allizom.org/api/v5/addons/search/?type=extension&recommended=true&category=social-communication&app=firefox
https://addons-dev.allizom.org/api/v5/addons/search/?type=extension&recommended=true&category=social-communication&app=firefox&q=me
