### ISSUE TITLE
Update search to prioritize recommended add-ons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11066]
Search should boost recommended add-ons above non-recommended content.

See the PRD for further details: https://docs.google.com/document/d/1fRxLy7h02tn1HBIlsTU_6h9DHmN8c3N6bg4JoxHF7J8/edit#heading=h.5kvm14zbadi2

**Comment by AlexandraMoga** [comment]
@eviljeff does this need any more re-indexing from your side?
So far, I can't seem to get the expected results. I have taken into consideration that the current search on -dev is mostly unreliable, but there are some scenarios that should work.

For example, the following requests will return only 3 recommended extensions in the first page of results:
https://addons-dev.allizom.org/api/v4/addons/search/?type=extension
According to the [curated list](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/) we should have more.


Furthermore, on -dev we are still having lots of persona themes, which are interfering with the results - the `is_recommended` parameter is `null` for them. 
For https://addons-dev.allizom.org/api/v4/addons/search/ , the first pages of results are only personas.

**Comment by eviljeff** [comment]
Mmm, yes, without a search string the search API doesn't default to relevancy as the sorting method - it uses weekly downloads.  Do searches with a search string work as expected?

Can you file a follow-up for non-relevance sorting - I need to get some input from Product about what to do.   (There aren't any recommended add-ons on AMO prod so it's harmless right now)

**Comment by AlexandraMoga** [comment]
@eviljeff when I'm adding a search string, recommended add-ons are receiving a certain boost. Here are some concrete examples:

1
**Search query:** https://addons-dev.allizom.org/en-US/firefox/search/?q=calendar/
**Target:** [Teamweek Button: Project Planning Calendar](https://addons-dev.allizom.org/en-US/firefox/addon/teamweek/)
**If recommended:** position 2 on the first page of search results
**If not recommended:** position 24 in search results

2
**Search query:** https://addons-dev.allizom.org/en-US/firefox/search/?q=sound/
**Target:** [SoundFixer](https://addons-dev.allizom.org/en-US/firefox/addon/soundfixer/?src=search)
**If recommended:** position 3 on the first page of search results
**If not recommended:** found on page 6 in search results

3
**Search query:** https://addons-dev.allizom.org/en-US/firefox/search/?q=colour/
**Target:** [Favourite colour](https://addons-dev.allizom.org/en-US/firefox/addon/favourite-colour/)
**If recommended:** position 11 on the first page of search results
**If not recommended:** found on page 12 in search results

4
**Search query:** https://addons-dev.allizom.org/en-US/firefox/search/?q=sleep/
**Target:** [Sleep Mode](https://addons-dev.allizom.org/en-US/firefox/addon/sleep-mode/)
**If recommended:** position 3 on the first page of search results
**If not recommended:** found on page 4 in search results

Even if none of the recommended extensions ended up 1st in search results, it looks like the new boost is  working. 
I'll file a follow up for the non-relevancy issue.

**Comment by eviljeff** [comment]
Yeah, the addons with users are still getting ranked above the recommended add-ons (that have no users).  Addons-dev is a little artificial but I suppose a similar thing could happen on prod too with new add-ons.

@jvillalobos what do you think?  Should we increase the multiplier amount?  It's currently just a x5 score multiplier compared to other public, non-experimental add-ons.

**Comment by jvillalobos** [comment]
I don't expect it to be common for very new add-ons to make it to the Recommended list, and being on the first page of results should correct that quickly anyway... I think it's something we'll need to gauge with real data to find the right boost. I like how it's looking now with the test data, so let's keep it at 5x for now.

**Comment by AlexandraMoga** [comment]
I will keep testing around this and if I'm going to run into any new issues I'll file them separately.

For now, I think this can be marked as verified fixed on -dev.
