### ISSUE TITLE
Disable all files pending review when a developer disables their add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1107]
When a developer decides to disable their add-on while a file is pending review, we shall disable the file to prevent review.
If the file is being reviewed while the add-on is disabled, the file will not be signed (even if the file was approved).

Example where this happened:
https://addons.mozilla.org/en-US/developers/feed/my-erp

**Comment by jvillalobos** [comment]
> If the file is being reviewed while the add-on is disabled, the file will not be signed (even if the file was approved).
I suppose this should say that reviews (approval, prelim, reject) for that file shouldn't apply at all, in that the file should remain disabled, no email should be sent, and the file shouldn't be signed. Some error message should be displayed to the reviewer.

**Comment by eviljeff** [comment]
Is the bug here that its still showing up in the queue, or the edge case where the review page is already open and the add-on is reviewed?

**Comment by jvillalobos** [comment]
There are two things:

1) If the add-on is disabled and the latest file is pending review, the file should be disabled.
2) Like you said, the edge case where the review page is already open and the add-on is reviewed.

**Comment by eviljeff** [comment]
And are both 1) and 2) happening?

**Comment by eviljeff** [comment]
1) should be happening right now https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/views.py#L1196

**Comment by eviljeff** [comment]
I've confirmed the addon doesn't show up in the review queue.  Not sure if we really need to disable the file if it doesn't show up for review anywhere (and also, since we imply that switching to hidden is an easy toggle back and forth making unrevertable changes seems harsh).  

So we're left with the edge case where the add-on is disabled during review.

**Comment by jvillalobos** [comment]
I think we need to disable the file. It should be clear to the developer that the file won't be pending review while the add-on is disabled, and they will need to post a new version when they enable it again (which could be months or years later). Reviving ancient versions is rarely a good idea. Worst case they can ask us to re-enable the version.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win7).
Postfix screenshots: 
![before_disabling](https://cloud.githubusercontent.com/assets/15685960/15239309/2608a366-18ea-11e6-99de-233dccb29e95.png)
![when_hidden-disable](https://cloud.githubusercontent.com/assets/15685960/15239310/2ba7ff60-18ea-11e6-92c5-97f6cb5cf3db.png)
