### ISSUE TITLE
Implement Recommended extensions review flow

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11074]
Part of [Review Flow for Recommended Extensions](https://docs.google.com/document/d/1kqDR2KHfbgLmaVZ-b-HgbSgpwU6eKA_D9voQkJ9M3io/edit#).

Extensions can have one of three states: Not Recommended, Pending Recommendation, or Recommended. The admin for adding and removing extensions from the Recommended list is covered in [this project](https://github.com/orgs/mozilla/projects/68). These states are independent from the review status (Approved, Disabled, Pending Review, etc.).

When an extension is added to the list, it will change from Not Recommended to Pending Recommendation. The only thing this changes is that all future versions of the extension will require pre-review (and appear in the Recommended review queue, see https://github.com/mozilla/addons-server/issues/11072).

Once a version of an extension Pending Recommendation is approved, the state changes to Recommended. This is the first version signed with the Recommended flag. New versions will still require pre-review and appear in the Recommended review queue.

Extensions in the Pending Recommendation or Recommended state cannot have auto-approval turned on, not even by an admin.

**Comment by AlexandraMoga** [comment]
This issue has been verified in close relation to #11072 and #11498 

- the new recommended states - `Not Recommended, Pending Recommendation, or Recommended` - are exposed in Discovery admin (more details in https://github.com/mozilla/addons-server/issues/11498#issuecomment-496388887)
- when a new extension is added to the list, the status changes to `Pending Recommendation` and the new version submitted will appear in the Recommended Pre-review queue
- if the new version is approved, the state of the add-on changes to `Recommended`
- all the subsequent versions will appear in the Recommended queue, until the add-on is removed from the recommended list in admin Discovery items

@jvillalobos @eviljeff there are several points that haven't been discussed in the requirements:
1. Shouldn't we expose the total weight of the new recommended versions? If, for example, a reviewer wants to investigate how an add-on weight oscillated from one version to another, they don't have a way to view this information for the versions that were recommended.
2. Should a recommended add-on review trigger any reviewer points? From what I've seen, each Approve or Reject action has generated a score of `0` in the Recent Points history
3. Once a version becomes recommended, should developers be allowed to disable or delete it from the Manage versions page in Dev hub? Maybe there should be some kind of warning to inform the developers about the risk of disabling a recommended version. 

Also, are all these changes landing behind the `api-recommendations-priority` flag?

**Comment by eviljeff** [comment]
> Shouldn't we expose the total weight of the new recommended versions? If, for example, a reviewer wants to investigate how an add-on weight oscillated from one version to another, they don't have a way to view this information for the versions that were recommended.

The points are calculated during the auto approval and it isn't attempted for recommended add-ons.

@jvillalobos to comment on the other stuff (too)

> Also, are all these changes landing behind the api-recommendations-priority flag?

No, that's just to prevent recommendations prematurely changing the API sorting and defaults.  I figured the user base that would be using the recommended addon review tools was small enough just to keep them informed directly when it was ready to use, etc.

**Comment by jvillalobos** [comment]
> Shouldn't we expose the total weight of the new recommended versions?

Yes, we should still compute the risk weight for recommended versions, before review.

> Should a recommended add-on review trigger any reviewer points?

Let's reuse the points we use for post-review, if possible.

> Once a version becomes recommended, should developers be allowed to disable or delete it from the Manage versions page in Dev hub?

Per the PRD: "it will not be allowed for a developer to disable or delete the latest approved version of a Recommended extension."

**Comment by AlexandraMoga** [comment]
I have opened follow up issues for the points addresses in https://github.com/mozilla/addons-server/issues/11074#issuecomment-496692345
