### ISSUE TITLE
Reviewers browse api returns a 500 error for search tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11085]
Prerequisites: you need to have Addons:Review permissions in order to complete this request

STR:
1. Try to retrieve version details for a search tool through the reviewers browse api:
```
GET https://addons-dev.allizom.org/api/v4/reviewers/addon/502880/versions/1541699/ 
```

Actual result:
The api responds with a 500 error

Expected result:
The search tool `.xml` details are returned

Notes:
- the error is also visible in the new code manager:
https://code.addons-dev.allizom.org/en-US/browse/502880/versions/1541699/

**Comment by kumar303** [comment]
@EnTeQuAk could you take a look?

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5344937/?query=is:unresolved

```
TypeError: 'odict_keys' object does not support indexing
  File "rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "olympia/reviewers/views.py", line 1381, in retrieve
    return Response(serializer.data)
  File "rest_framework/serializers.py", line 563, in data
    ret = super(Serializer, self).data
  File "rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "olympia/addons/serializers.py", line 177, in to_representation
    return super(SimpleVersionSerializer, self).to_representation(instance)
  File "rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "rest_framework/fields.py", line 1889, in to_representation
    return method(value)
  File "olympia/reviewers/serializers.py", line 189, in get_content
    blob_or_tree = tree[self.get_selected_file(obj)]
  File "olympia/reviewers/serializers.py", line 182, in get_selected_file
    requested_file = files.keys()[0]
```

**Comment by EnTeQuAk** [comment]
Search tools are properly tested in the git backend but I seem to have missed testing it in the API layer. I'll add tests and fix the support.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I'm still reproducing. I've tired with my previous example and with a new one:
https://addons-dev.allizom.org/api/v4/reviewers/addon/616649/versions/1655536/

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF66, WIn10x64

Search tools files can be inspected now in the code-manager:

https://code.addons-dev.allizom.org/en-US/browse/502877/versions/1541696/
