### ISSUE TITLE
Link Extension Workshop dev and stage environments to Dev Hub 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11099]
Requested here  https://github.com/mozilla/extension-workshop/issues/139#issuecomment-477933211
There is a stage environment https://extensionworkshop.allizom.org/ and dev will follow, discussions are here https://github.com/mozilla/extension-workshop/issues/131

Expected result:
When the EW is clicked from Dev Hub dev or stage from the following pages 
https://addons-dev.allizom.org/en-US/developers/
https://addons-dev.allizom.org/en-US/developers/addons

it should redirect to https://extensionworkshop-dev.allizom.org/ 
https://extensionworkshop.allizom.org/ 

Right now the landing page is the prod environment https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link

Tested with FF66(Win10).

**Comment by diox** [comment]
Requires some config work for dev/stage/prod so maybe not a good first bug.

**Comment by ioanarusiczki** [comment]
@diox We have the links for dev and stage EW on AMO homepage https://github.com/mozilla/addons-frontend/issues/7830

**Comment by willdurand** [comment]
Once https://github.com/mozilla/addons-server/pull/12703/files lands, we will be able to use `EXTENSION_WORKSHOP_URL` in the `settings`.

**Comment by ioanarusiczki** [comment]
@eviljeff

On AMO dev for https://addons-dev.allizom.org/en-US/developers/
 
- I can access https://extensionworkshop-dev.allizom.org/ from "Visit the Extension Workshop" logged in view.  
- From the Menu Bar  footer of the page (logged out view) I receive a 404. 

for https://addons-dev.allizom.org/en-US/developers/addons :
- I receive a 404 

![the dev 404](https://user-images.githubusercontent.com/33448286/68025084-9d025780-fcb4-11e9-8834-d947b2506756.gif)

**Comment by eviljeff** [comment]
trailing slash was an oversight; fixed now.

**Comment by ioanarusiczki** [comment]
@eviljeff All good now. I'll check this on stage tomorrow.

**Comment by ioanarusiczki** [comment]
Verified on dev and stage with FF70(Win10).
