### ISSUE TITLE
Expose risk weights breakdown in reviewer tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11096]
We calculate the risk of each add-on file using a number of weights specified in [this spreadsheet](https://docs.google.com/spreadsheets/d/1CZEECHHqEmK87fNiWNslAsFQBL7zxYF-c63-zZVZuqw/edit?ts=59c9d01f#gid=491359892), and currently show the final number in review pages and the review queue. This is the first step to make this breakdown more visible, per discussions with @atsay and @muffinresearch, among others.

For this issue, we need to:
- [ ] Store, for each add-on file, the value of each of the risk factors.
- [ ] Show the breakdown in the reviewer tools. I suggest a tooltip in the Weight number that appears in each item in the review history ([for example](https://reviewers.addons.mozilla.org/reviewers/review/adblock-plus#history)). The tooltip could say something like:
> Admin review flag: 0
> Size of code changes: 70
> etc.

And something like "Risk breakdown not available." for older versions.

Followup step is to have a dedicated page for it.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF66, WIn10x64

- for new addons/new versions - weights breakdown is exposed in addon version history
![image](https://user-images.githubusercontent.com/31961530/55612669-66ea0d00-5791-11e9-93dc-5a61d8ff249e.png)

- for old addons/old versions - display a `Risk breakdown not available` tooltip
![image](https://user-images.githubusercontent.com/31961530/55612705-7e28fa80-5791-11e9-834d-11ae2c454b50.png)

As a sidenote, I've also noticed that a risk breakdown is displayed for addon versions that have an auto-approval disabled flag (Pending for approval in the Updates queue).
