### ISSUE TITLE
[Reviewer-panel] Not allowed error

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-server#11103]
### Describe the problem and steps to reproduce it:
Login account with reviewer access.
Reject an addon (copy link beforehand)
Goto copied url after rejection(rejected addon review URL)

### What happened?
Should see the review details and option to reply

### What did you expect to happen?
Get an error "
Oops! Not allowed.

You tried to do something that you weren't allowed to.
"

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Production URL - https://reviewers.addons.mozilla.org/en-US/reviewers/review-listed/page-mixer

![image](https://user-images.githubusercontent.com/5318732/55399865-93f9ae00-554c-11e9-80dd-0c3668f7b39d.png)

cc @wagnerand

**Comment by diox** [comment]
What's "reviewer access" here? What kind of permissions ? I suspect this is happening for reviewers that only have `Addons:PostReview` when all versions are disabled. In which case it's a known limitation, but I'm not sure it was already filed.

**Comment by tsl143** [comment]
As an addon reviewer I have access to accept,reject, reply to addons. Does that help?
my username is `trishulgoel` if that helps you.

**Comment by eviljeff** [comment]
@wagnerand to confirm what permissions @tsl143 has

**Comment by wagnerand** [comment]
Trishul has `Addons:PostReview`.
