### ISSUE TITLE
Allow credentials to be included in cross-site HTTP requests (accounts/session endpoint)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11100]
The current CORS configuration returns `Access-Control-Allow-Origin: *` in the API responses, which makes it impossible to send credentials (cookies) along with an API call from a client hosted on a different domain.

This is problematic because code-manager cannot send credentials when it needs to. The error in Chrome or FF is:

```
Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

Code-manager needs to send credentials when logging out a user: https://github.com/mozilla/addons-code-manager/issues/515.

The CORS configuration should allow credentials for this endpoint. ~~According to the CORS middleware source code, setting `CORS_ALLOW_CREDENTIALS` to `True` will add an extra header (`Access-Control-Allow-Credentials`) and change the `Access-Control-Allow-Origin` value to the `origin` of the request.~~ Read below, we decided to only change the CORS config for the `accounts/session` endpoint.

**Comment by diox** [comment]
Not entirely sure we want this. Not allowing credentials was a great security measure... Can't you use a logout redirect page in code manager ? And btw, how do we do it in the frontend ?

**Comment by willdurand** [comment]
> And btw, how do we do it in the frontend ?

We send the credentials. But I don't think CORS are involved because both the frontend and the API are on the same domain.

**Comment by diox** [comment]
Maybe this should be added to the logout page only ?

**Comment by willdurand** [comment]
> Maybe this should be added to the logout endpoint only ?

Reading the code, I am not sure the middleware is designed to allow that: https://github.com/ottoyiu/django-cors-headers/blob/1e80ddf08c17f8ddf56bbba712378c2a7419adc2/corsheaders/middleware.py#L119-L133

Another option would be to have a white-list of allowed origins but that would not entirely solve the potential CSRF issue (if that's what you meant by `a great security measure`).

I can try to set the CORS headers in the view but I am not sure about the middleware behavior. It could override the headers set in the view.

**Comment by diox** [comment]
From a quick glance at the middleware it shouldn't override that header if the view returns it and we don't allow credentials by default.

**Comment by willdurand** [comment]
> From a quick glance at the middleware it shouldn't override that header if the view returns it and we don't allow credentials by default.

It is possible to add a new header but the value of `Access-Control-Allow-Origin` needs to be changed (from `*` to the origin of the request).

Should we exclude the `/accounts/session/` endpoint from the CORS config? Given that there is only one endpoint with one method (according to [the API docs](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#delete--api-v4-accounts-session-)), it should be okay to exclude it but that would not work if we wanted to have `GET /accounts/session/` in the future for instance.

**Comment by diox** [comment]
That seems like a good option. We can always set everything manually in that view, or change the global config later if we really need to.

**Comment by AlexandraMoga** [comment]
@willdurand I understand this was added to support https://github.com/mozilla/addons-code-manager/issues/515 which seems to be working now. 
By confirming that user log out works, can we also consider this issue as verified?

**Comment by willdurand** [comment]
>  By confirming that user log out works, can we also consider this issue as verified?

Yes
