### ISSUE TITLE
Restart docker celery as files change

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1110]
We use the Django server in reloading mode which means it restarts as files change locally. However, the celery workers do not restart and will not run new code as you make file edits. We should make the local dockerized celery do auto-reloading just like Django.

**Comment by kumar303** [comment]
We added `--autoreload` in https://github.com/mozilla/olympia/pull/1119 but it doesn't seem to be working. I can see 'task ... has been modified' in the log but it doesn't seem to actually reload the module. It seems that other people who are running supervisor [may be having this problem too](http://stackoverflow.com/questions/27511025/celery-autoreload-not-working).

**Comment by EnTeQuAk** [comment]
This appears to be not an easy fix afterall, according to https://github.com/celery/celery/issues/1025#issuecomment-237417095 we'd have to do that on our own to help support this feature.

Should we just remove `--autoreload` for now and document that celery has to be restarted? On the other hand I think there are various tools that we could use to simply restart the whole worker on any change but that sounds like overkill to me.

**Comment by kumar303** [comment]
Restarting the whole worker might be the best option here. We use this setup for development and if celery is a little slow to restart after you change some code, that's still way better than having to remember to trigger a restart command in a shell every time you change a file.

**Comment by EnTeQuAk** [comment]
That's going to be fixed via #6625

**Comment by EnTeQuAk** [comment]
This actually got fixed and merged and seems to be working fine for me. Looking forward to any kind of feedback though!
