### ISSUE TITLE
Missing environment variables break deployments

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11117]
Lately, we added two new environment variables to the settings: `CODE_MANAGER_FXA_CLIENT_ID` and `CODE_MANAGER_FXA_CLIENT_SECRET`, on all environments at once and following the existing conventions.

Simply introducing those two variables caused the following deployment issues:

- -dev deployments started to fail
- the deployment to stage after this week's tag has failed

Here is an example of the stack-trace: https://irccloud.mozilla.com/pastebin/B6YjpvEK/.

I believe addons-server should not fail that way (and should not be causing deployment breakages) but on the other hand, I learnt that throwing errors like this allows us to know when something is not correctly configured. That being said the fix has been to create the env variables with fake values in both cases (for -dev and stage, but -dev now has real values for the env vars).

Could we discuss/think about how to avoid these problems in the future? It's worth noting that prod is also affected and we already added env vars with fake values to prevent a deployment issue on Thursday.

**Comment by eviljeff** [comment]
We can define default values for settings in the python code (and do for most settings).  But for some settings (e.g. `CODE_MANAGER_FXA_CLIENT_SECRET`) there is no sensible default that we'd want to deploy with, and we can't expose the real value in the source code.  

We could add code that would handle a `None` value and make that the default, but I'm not sure what deploying with `None` and it not actually working would give us - we _want_ to know when addons-server is misconfigured.  I lean towards WONTFIX.
