### ISSUE TITLE
Make initialize_docker fails

### ISSUE THREAD

**Issue by junngo** [mozilla/addons-server#11127]
### Describe the problem and steps to reproduce it:
When I executing command `Make initialize_docker` on local, It occurred Error.

### What happened?
```
# FXA username and password for ui-tests
export UITEST_FXA_EMAIL := uitest-3c5ef95e-5626-11e9-9130-0242c0a84002@restmail.net
/bin/sh: 1: export: :: bad variable name
Makefile-docker:93: recipe for target 'populate_data' failed
make: *** [populate_data] Error 2
Makefile-os:57: recipe for target 'initialize_docker' failed
make: *** [initialize_docker] Error 2
```

### What did you expect to happen?
Success make and run server.

### Anything else we should know?
This issue has something to do with #11069. When I excuted make command before the PR, I succeeded make.

**Comment by eviljeff** [comment]
@jrbenny35 any ideas?
