### ISSUE TITLE
A white rectangle is displayed below Extension Workshop in some languages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11122]
STR:
1. Login dev hub and go to Manage my submission page 
2. Change locale into hu, de, or pl to expand the Menu below the logo on two rows 
3. Hover over Extension Workshop 

Expected result:
Extension Workshop is underlined by a white line.

Actual result:
Below the white line there's an extra white rectangle displayed. 

Notes:
Reproducible on all AMO servers with FF66(Win10). 

![ux issue](https://user-images.githubusercontent.com/33448286/55480045-0c816d00-5628-11e9-88f3-0e55e59fafa6.gif)

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by ithompson4** [comment]
Hello, can I work on this issue? Thank you.

**Comment by caitmuenster** [comment]
Sorry for the late response, @ithompson4! This one is all yours!

**Comment by ithompson4** [comment]
Hello @caitmuenster. When I tried to run the addons-server using `make initialize_docker`, I ran into issues similar to this reported [issue](https://github.com/mozilla/addons-server/issues/11127).

Please advise. Thank you.

**Comment by muffinresearch** [comment]
@ithompson4 try updating your checkout from master, a patch landed for #11127

**Comment by ithompson4** [comment]
Hello @muffinresearch and @diox. I got the latest updates from the master. I tried to run `make initialize_docker` command 2 weeks ago and again today. Each time I am asked to insert `username` and `password`. Are they generated automatically or I need to insert them manually? Thanks.

<img width="810" alt="usernameScreen" src="https://user-images.githubusercontent.com/16367007/58388221-07b6b500-7fea-11e9-8445-f6b95661febb.png">

**Comment by diox** [comment]
Choose a username and password, it doesn't matter.

**Comment by ithompson4** [comment]
I ran `make initialize_docker` command again today. I keep on getting exceptions:

<img width="875" alt="runError" src="https://user-images.githubusercontent.com/16367007/58526665-a33c5700-819d-11e9-8a7c-3eb474ebf13a.png">

**Comment by diox** [comment]
That would typically indicate that the search server failed to start. Try this: https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#connectionerror-during-initialize-docker-elasticsearch-container-fails-to-start

**Comment by caitmuenster** [comment]
Hey @ithompson4, how's it going with this issue? Were you able to get your docker running?

**Comment by brute4s99** [comment]
Here you go @402wasd Good Luck!

**Comment by rbrishabh** [comment]
If no one is working for on this currently, can I take this up?

**Comment by caitmuenster** [comment]
Go for it, @rbrishabh!

**Comment by rbrishabh** [comment]
I am unable to run addons-server with docker on my machine. Is there any other way around this?

Thanks!

**Comment by soniashvin** [comment]
Hey @caitmuenster, I cannot see the bug, is it fixed? Or I am doing it wrong?
![image](https://user-images.githubusercontent.com/35840223/62420136-07522e80-b6ab-11e9-841f-62fd935de591.png)

**Comment by eviljeff** [comment]
@soniashvin Hi, you need to have some add-ons to demonstrate this.  If you upload an add-on (any add-on - not listed on AMO will do) there's an extra menu item.

**Comment by caitmuenster** [comment]
@rbrishabh Sorry to hear you are having problems with the add-ons server Docket. :/ Unfortunately, there are a lot of things that could be causing the problems. You might want to take a look at another issue outside of the add-ons server repo.

**Comment by junngo** [comment]
Hello @diox. 
I tried to reproduce bug and I check this situation.
![issues-11122-situation](https://user-images.githubusercontent.com/29684524/63921909-9ec65980-ca7e-11e9-87a6-65abcc31e37b.png)

This problem is that **Extension Workshop menu** doesn't have sub menu.
But When I put mouse point on **Extension Workshop menu**, It happen hover effect that doesn't distinguish with the others menu.

I think that.
To solve this issue, I try to add name(`.nomenu`) to [li tag](https://github.com/mozilla/addons-server/blob/61a52953d6821b4ee01df404d4dbbcdfedd69c16/src/olympia/devhub/templates/devhub/nav.html#L37) and css effect(`display: none`) to [css file](https://github.com/mozilla/addons-server/blob/61a52953d6821b4ee01df404d4dbbcdfedd69c16/static/css/restyle/restyle.less#L454).

If this is right, Can I work on it?

**Comment by diox** [comment]
Yes, you can, it's all yours. I think you're on the right track here.

**Comment by junngo** [comment]
Thank you. I made PR.
If you have other good method or I'm wrong, I'm gonna revise code again :)

**Comment by ioanarusiczki** [comment]
This issue is not reproducible. Verified with FF76(Win10).
