### ISSUE TITLE
Indicate which git file status in compare response

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11123]
Blocks https://github.com/mozilla/addons-code-manager/issues/413

We should indicate in the compare API the added/changed/modified status of files.

**Comment by AlexandraMoga** [comment]
After verifying this on -dev I have the following results:

* the compare file api will return now a new field which indicates the current `status` of a file. So far we have:
  * `""` - for unmodified files
  * `M` - for modified files
  * `A` - for added files
  * `D` - for deleted files

![image](https://user-images.githubusercontent.com/31961530/56140007-ad661580-5fa2-11e9-8735-d37486297921.png)


It doesn't look like we've implemented a separate status for `R -  renamed` files.  The current behavior is:
 - `A` - for the renamed file
 - `D` - for the old file name
