### ISSUE TITLE
Update "All Abuse Reports" view

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11137]
Part of the the [abuse reporting project](https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit#). 

Reviewers can see a list of all abuse reports for an add-on. [For example](https://reviewers.addons.mozilla.org/reviewers/abuse-reports/adblock-plus). This needs to be updated to support the additional data logged with the new abuse reports. 

The following metadata should be shown, when available:

* Add-on name and report count (title)
* Add-on rating and active daily users

Per report:

* Version
*  Reported application, locale, operating system with versions
* Time since the add-on was installed
* Install Origin and Method
* Category (spam, malicious, etc.)
* Report text
* Report date and time
* Reporter

**Comment by ioanarusiczki** [comment]
@diox Hello Mat, I have a couple of questions regarding this new format for Abuse Reports:

1. the `Version` for which the abuse report was made -> is this going to be correctly displayed next to the addon/theme name or it requires a separate column in the new table if or when this https://github.com/mozilla/addons-server/issues/11135 lands? Right now version is not available in rev tools abuse report page or in admin tools `en-US/admin/models/abuse/abusereport/`
2. the `Locale` is mentioned as being required -> should this be a separate column in the table?
3. I Installed then reported a couple of add-ons, themes but the `Install origin` and `Install date` remained unpopulated fields in the table.  I found for a couple of add-ons though such as[ this one](https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/space-stars) a `2 months, 2 weeks ago` at `install date` and " https://addons-dev.allizom.org/en-US/firefox/addon/fvd-speed-dial/?src=featured Sideload" as `install origin`. -> Is this going to be implemented later? Also I think that when it will be available it should be the format of the `Date` (the date the addon was reported) such as `April 16, 2019, 3:11 p.m.`
4. Not all users have the country of origin next to their name in the `Reporter` column,  searching through pages all I can say is that it's pretty random meaning there are users that have that information added and users that don't have it. 
5. If the layout is fine, I can't tell, the `Report text` will be displayed for each abuse report below the rest of the information which has a table format. 

![layout of the page](https://user-images.githubusercontent.com/33448286/57298218-5a333e80-70da-11e9-81b6-48c9bb25aa87.png)

6. I don't know if on this page the `More about this add-on` and ` Image Galery` sections are of any use. The add-ons display this information again (which is also available on the Review page). 
Static themes -> they only have an empty `Theme Images` section, maybe it should be removed completely? 

Abuse-reports page for static themes versus addons 
![themes and addons](https://user-images.githubusercontent.com/33448286/57299425-31f90f00-70dd-11e9-88e6-dc1b3c6a9099.gif)

**Comment by diox** [comment]
> 1. the `Version` for which the abuse report was made -> is this going to be correctly displayed next to the addon/theme name or it requires a separate column in the new table if or when this https://github.com/mozilla/addons-server/issues/11135 lands? Right now version is not available in rev tools abuse report page or in admin tools `en-US/admin/models/abuse/abusereport/`

It should be available if it was submitted via the report.

> 2. the `Locale` is mentioned as being required -> should this be a separate column in the table?

We'll adjust if necessary but for now just inside the column that displays the application info is enough

> 3. I Installed then reported a couple of add-ons, themes but the `Install origin` and `Install date` remained unpopulated fields in the table.  I found for a couple of add-ons though such as[ this one](https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/space-stars) a `2 months, 2 weeks ago` at `install date` and " https://addons-dev.allizom.org/en-US/firefox/addon/fvd-speed-dial/?src=featured Sideload" as `install origin`. -> Is this going to be implemented later? Also I think that when it will be available it should be the format of the `Date` (the date the addon was reported) such as `April 16, 2019, 3:11 p.m.`

Like for version, the info should be there if reported in the abuse report. The challenge for testing is that at the moment, AMO doesn't submit that information. Firefox will, using the updated API (https://github.com/mozilla/addons-server/issues/10643 and similar issues, + https://bugzilla.mozilla.org/show_bug.cgi?id=1543377)

> 4. Not all users have the country of origin next to their name in the `Reporter` column,  searching through pages all I can say is that it's pretty random meaning there are users that have that information added and users that don't have it. 

Yes, but there isn't much we can do about it at the moment.

> 5. If the layout is fine, I can't tell, the `Report text` will be displayed for each abuse report below the rest of the information which has a table format. 

Yeah I came up with the UI myself and it's a little weird, but I was running out of space. The report text is indeed below the rest of the info.

> 6. I don't know if on this page the `More about this add-on` and ` Image Galery` sections are of any use. The add-ons display this information again (which is also available on the Review page). 

Yeah I used the same template. I think it can be useful for context.

**Comment by ioanarusiczki** [comment]
@diox 
It's been light now why the version numbers in the abuse reports for some addons from /en-US/admin/models/abuse/abusereport/ is `112.3` for which I filed the issue https://github.com/mozilla/addons-server/issues/11318.   The `addon_version` can be 112.3, 38.1.44556.788 or any other when I create the report using Postman.
With API testing -> I can use the `addon_version`, `app`, `addon_install_origin` and `install_date` parameters and fill in a value for these. Only `install date` requires a specific format and `app` can be either `Firefox` or `Android`. 
![Date format and the rest](https://user-images.githubusercontent.com/33448286/57360140-16940f80-7182-11e9-9e05-6b5762163084.png)

Followups filed and closing this issue, verified on AMO dev - FF66(Win10).
