### ISSUE TITLE
Update recent abuse reports in review page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11138]
Part of the the [abuse reporting project](https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit#). 

Like with the "All Abuse Reports" view (https://github.com/mozilla/addons-server/issues/11137), this abbreviated view ([for example](https://reviewers.addons.mozilla.org/reviewers/review/adblock-plus)) needs to be updated to include the new data we'll be obtaining.

**Comment by diox** [comment]
1. That hasn't changed, it's by design. Could file a follow-up to see if product agrees this should stay that way though, maybe it was an oversight.
2. Also hasn't changed here, but could be a pre-existing bug. It should show up for any auto approved listed extension.

**Comment by jvillalobos** [comment]
1 sounds like an oversight. Not a big deal, but good to have filed.
