### ISSUE TITLE
Triage tool for abuse reports

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11135]
Part of the the [abuse reporting project](https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit#). 

The abuse reporting admin needs a way to triage incoming abuse reports. It should be accessible to users with the (new) `AbuseReports:Edit` permission.

The following metadata should be shown, when available:
* Add-on name, version, author
* Add-on rating and active daily users
* Amount of abuse reports for the add-on within the last 3 months, with a link to display all reports for that specific add-on
* Amount of abuse reports for the add-on since its last version update
* Was the affected version reviewed by a human?
* Reported application, locale, operating system with versions
* Time since the add-on was installed
* Install Origin and Method
* Category (spam, malicious, etc.)
* Report text
* Report date and time
* Reporter

The following actions should be available:

* Mark report as deleted
* Mark report as triaged
* Mark report as suspicious
* Change the abuse report category
* Skip this report and go to the next
* A link to the review page

Here's a sketch of this tool (slightly outdated, so it's just a rough guide):

<img width="600" alt="Screen Shot 2019-04-03 at 3 19 36 PM" src="https://user-images.githubusercontent.com/62568/55513874-025d6f80-5624-11e9-8806-c2c961b4597f.png">

I'm thinking that this could be integrated with the list view in https://github.com/mozilla/addons-server/issues/11133. Each untriaged result could have a triage button or link that expands the item into the triage view above. When one of the buttons is clicked, the action is performed and the next item on the list is expanded. 

If that's not feasible, we'll need a separate page that lists the most recent untriaged reports, with at least filtering by category, so they can be triaged.

**Comment by tapaswenipathak** [comment]
Hello folks: Can I work on the ticket?

**Comment by diox** [comment]
No, this issue is already assigned. Please take a look at other issues that have the [contrib: welcome](https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome) label.
