### ISSUE TITLE
List and search view for abuse reports

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11133]
Part of the the [abuse reporting project](https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit#). 

The abuse reporting admin needs a list / search view. It should list all reports by default, with the most recent ones at the top. It should be accessible to users with the  (new) `AbuseReports:Edit` permission.

The following fields should describe report entries:
* Add-on name and version
* Signing state of the add-on version (signed, partner, curated. If not yet available: self-hosted, listed, featured)
* Category (spam, malicious, etc.)
* State (untriaged/valid/suspicious/deleted)
* Excerpt from the abuse report text

When searching, the following fields should be available for filtering:

* Reports for a specific add-on (by id, name, or slug)
* Search for specific text keywords in the report text
* Category
* State (untriaged/valid/suspicious/deleted)
* For reports marked valid, a time range in which the report was marked
* Minimum amount of abuse reports in a (user-specified) timeframe

The following bulk actions should be available:
* Delete all checked reports
* Mark all checked reports as suspicious
* Mark all checked reports as valid

Here's a sketch of this view (slightly outdated, so it's just a rough guide):

<img width="510" alt="Screen Shot 2019-04-03 at 3 08 06 PM" src="https://user-images.githubusercontent.com/62568/55513182-58c9ae80-5622-11e9-9cb0-c158ec5db5f0.png">

**Comment by diox** [comment]
QA:
The admin tool lives in the django admin in `/en-US/admin/models/abuse/abusereport/`.

At the moment the `AbuseReports:Edit` permission is not given to any group, so you'll have to modify the `rules` of an existing/new group to get it. Note that `Admin:Tools` or other `Admin:Something` permission is still required to access the admin tool.

One important change is that Abuse Reports are now soft-deleted, meaning once deleted, reviewers shouldn't be able to see them anymore in reviewer tools, but admin still can. The admin tool has a limited detail view which lets you delete reports (might require super permissions: this will be tweaked later on in https://github.com/mozilla/addons-server/issues/11136)

**Comment by ioanarusiczki** [comment]
@diox  Hi Mat, I have some questions, except this I already filed followup issues for what I've already noticed.  
- the table contains a column "Reason", also there is a filter button "By Reason". I believe it should be the `Category` Jorge is talking about
> Category (spam, malicious, etc.)

but I can't tell if it should be named `Category` or `Reason`, I suppose both ways it's fine.

- Jorge mentions for Search filters  
>For reports marked valid, a time range in which the report was marked

all type of reports, valid, deleted, untriaged or suspicious can be filtered "by state"  then they can be further more filtered using "By created" but I believe he refers here to the date they were marked as valid, so let me know if I should file a followup to add this too.

- Jorge says about
>Minimum amount of abuse reports in a (user-specified) timeframe

this should be the `By created` filter ?

- Please let me know if I understood correctly the last filter `By minimum reports count (grouped by guid)`  - for example I modified the table, to view only the reports from 2019 then if I type in a value 2,3 or 4 and click `Submit` it should display the addons that have at least 2,3 or 4 abuse reports made from 2019.
I tried with value "3" and for example the "SI" addon is displayed but it's abuse reports are not listed one after the other even if it's the same addon with the same guid {2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}

![last filter](https://user-images.githubusercontent.com/33448286/57126122-73fc1b00-6d94-11e9-82fd-0ed1e3aad68c.gif)

Also, I've noticed that the filter's field will allow negative values and "0" too.

**Comment by ioanarusiczki** [comment]
@diox I forgot to add - the "Add abuse report" button - I suppose this is still in progress and will become functional later, I can add reports with `None` as the name of the addon or user - so the only editable field is right now the `State`. 

![add abuse report](https://user-images.githubusercontent.com/33448286/57127314-ac055d00-6d98-11e9-87c0-1445aca01d3f.gif)

**Comment by diox** [comment]
> but I can't tell if it should be named `Category` or `Reason`, I suppose both ways it's fine.

I've named it `Reason`, from an earlier PRD. I think it's fine like that :stuck_out_tongue: 

> For reports marked valid, a time range in which the report was marked

Use the `modified on` at the top to search through those. It's less precise, we'll see if that's enough or another side filter is required. (Only time reports are 'modified' is when they are 'marked' as something)

> Minimum amount of abuse reports in a (user-specified) timeframe

Use both the minimum reports count + the by created filters to achieve this. If it's not working for you please create a specific follow-up issue it'll be easier to track down.

> Also, I've noticed that the filter's field will allow negative values and "0" too.

Good catch, please file another issue for that.

> "Add abuse report" button 

Also worth another issue please, I should have removed it.

**Comment by ioanarusiczki** [comment]
@diox Ok, thanks for the info. I will file the rest of the issues and mark this verified on AMO dev - FF66(Win10). 

For the `Minimum amount of abuse reports in a (user-specified) timeframe`   - I must add to what you said 
> Use both the minimum reports count + the by created filters to achieve this. If it's not working for you please create a specific follow-up issue it'll be easier to track down.

that after making the search with minimum reports count + by created filters it needs a filtering (clicking) on the GUID column and then the abuse reports for one addon will be listed one after another, so I think it is just fine, else the reports remain listed with the most recent ones at the top. 

![guid needed for this use case](https://user-images.githubusercontent.com/33448286/57137511-b9324400-6db8-11e9-80bb-8303ce96fd13.gif)
