### ISSUE TITLE
drop 'home' (/) as a django view

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11146]
We already removed (almost) all of the legacy frontend, including the browse and disco carousels, so the homepage ('home') is empty.  We should remove it entirely, fixing tests as needed.

**Comment by ioanarusiczki** [comment]
@eviljeff Can you give the URL for this empty homepage? Please add some specifications for qa. 
Thanks!

**Comment by ioanarusiczki** [comment]
Release testing is complete. Test results are here https://testrail.stage.mozaws.net/index.php?/plans/view/16821
Verified on AMO stage - FF66(Win10 & Android 8.0)
