### ISSUE TITLE
Allow accessing reviewer and django admin add-ons page using add-on id

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11154]
Admins constantly have to convert between the add-on ID (guid) and the AMO ID.
Could we add url handlers for the following urls?

```
/reviewers/review/<guid>
/reviewers/review-listed/<guid>
/reviewers/review-unlisted/<guid>
/reviewers/review-content/<guid>
/admin/models/addons/addon/<guid>
/admin/addon/manage/<guid>
```

Should we also add a handler for the public pages `/firefox/addon/<guid>` ?

**Comment by diox** [comment]
>  Could we add url handlers for the following urls?
> (snip)

We should! We support id and slug almost everywhere but supporting the guid as well makes sense. It should be relatively trivial everywhere except maybe the django admin (still doable, maybe just slightly harder).

> Should we also add a handler for the public pages /firefox/addon/<guid> ?

The API already supports guid lookups so this should be filed on https://github.com/mozilla/addons-frontend/ I think.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF66, WIn10x64

The following URLs are now supported:

Reviewer Tools:

1. https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/{e4469772-3064-441a-9455-66b26703198e}
2. https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/support@lastpass.com
3. https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/gmailnoads@mywebber.com
4. https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/firebug@software.joehewitt.com
=> all these links are being redirected to `/reviewers/review+queue/<slug>`

Admin tools:
1. https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/export-helpers@mozilla.test/change/
2. https://addons-internal.dev.mozaws.net/en-US/admin/addon/manage/soundfixer@unrelenting.test/
