### ISSUE TITLE
git extraction happens outside of "create new version" transaction

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11183]
To create a new version we primarily call https://github.com/mozilla/addons-server/blob/fb60d6deaba14c05c7a3a4969e329734191cc92b/src/olympia/devhub/tasks.py#L107 which called by a celery task, usually `submit_file`. That's why django-post-request-task library doesn't help us here.

We'll probably need to use Djangos on_commit hook to make this more reliable.

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5483678/

```
DoesNotExist: Version matching query does not exist.
(1 additional frame(s) were not displayed)
...
  File "celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "olympia/amo/decorators.py", line 108, in wrapper
    return f(*args, **kw)
  File "olympia/versions/tasks.py", line 120, in extract_version_to_git
    version = Version.unfiltered.get(pk=version_id)
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 380, in get
    self.model._meta.object_name

DoesNotExist: Version matching query does not exist.
```

**Comment by AlexandraMoga** [comment]
@EnTeQuAk please let me know if there is anything that should be tested by QA.
Thanks
