### ISSUE TITLE
"Please use images smaller than 4MB" red message should be displayed on edit profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11186]
This issue was fixed on the legacy frontend https://github.com/mozilla/addons-server/issues/7731 but looks like it returned on the new frontend 

STR:
1. Sign in and go to edit profile page to upload an image > 4MB 
2. Click Upload profile and observe the red message displayed on the top of the page

Expected result:
Please use images smaller than 4MB 

Actual result:
Please use images smaller than 3MB 

Notes:
Reproducible on both AMO dev and stage - FF66(Win10). 

![4MB instead of 3 MB](https://user-images.githubusercontent.com/33448286/56035100-dfbd0c00-5d31-11e9-8a91-57411b98c9bb.png)

**Comment by eviljeff** [comment]
this should be filed under addons-frontend

**Comment by eviljeff** [comment]
The error message comes from the API (despite the title and screenshot)

**Comment by dsychin** [comment]
I would like to work on this.
Am I right to think that the problem is at [this line](https://github.com/mozilla/addons-server/blob/fa4336f55015097f04d9d139b984352c84c6f651/src/olympia/accounts/serializers.py#L152)?

**Comment by eviljeff** [comment]
@dsychin that's correct.

**Comment by ioanarusiczki** [comment]
This issue was fixed. Verified with FF76(Win10). 

![Screenshot_2020-06-22 User Profile for Adminonstage – Add-ons for Firefox (en-US)](https://user-images.githubusercontent.com/33448286/85285372-7db17800-b499-11ea-8245-d5f183262671.png)
