### ISSUE TITLE
Update abuse API parameters with latest values from the PRD

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11191]
https://docs.google.com/document/d/1K5Th9UmpayfVMXadkxU6cDO3sFKOwYozQgyoN0WEGwY/edit?ts=5ca783b9 should contain the definitive values the various parameters of the abuse API need to accept. We need to update the API to support & document those

**Comment by diox** [comment]
There are a few more updates I missed.

**Comment by AlexandraMoga** [comment]
Verified on -dev with the `POST /api/v4/abuse/report/addon/`. The constant values set for `report_entry_point` , `addon_install_method`, `addon_signature` and `reason` are correctly interpreted and errors are returned if they are not sent correctly in the request. 
There were also no regressions spotted on the fronted abuse report component. 

@diox for some reason, the [addon abuse report](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#post--api-v4-abuse-report-addon-) documentation is not up to date. For my tests, I've gathered my information from https://github.com/mozilla/addons-server/pull/11192/files#diff-512866d6535ee5c5680a7349284df0faR74 and https://github.com/mozilla/addons-server/pull/11198/files#diff-512866d6535ee5c5680a7349284df0faR119

**Comment by diox** [comment]
@AlexandraMoga good catch on the docs, I fixed that (readthedocs was still building using Python 2 and not 3, and there was a syntax error in abuse.rst that I fixed in 5ced08385f0a6df6de1c55d8557f5bbf6ba31ac3)

**Comment by AlexandraMoga** [comment]
https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html are up to date now. I see a slight formatting difference compared to other unchanged components (see line spacing for example). I'm not sure if this is expected or not.
