### ISSUE TITLE
Don't make extra SQL queries when calling is_superuser multiple times

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11200]
When calling `is_superuser` property to check for super admin rights, a SQL query is made to check the groups of the user. Since that property can be called several times for the same page in the admin tools, cache it.

**Comment by diox** [comment]
QA: you can't check for SQL queries, but you can check that permission handling is working correctly, particularly in the admin.

**Comment by ioanarusiczki** [comment]
@diox I could add and remove users from the admin groups and the given permissions are applied on AMO.
 - verified on AMO dev with FF66(Win10).

If there's anything else I could check on please let me know.
