### ISSUE TITLE
Expose the original URLs when the addons API returns outgoing links

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11206]
The URLs received in [the addons API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail) response use the outgoing proxy. In order to fix https://github.com/mozilla/addons-frontend/issues/3580, we need to know the original URLs (`homepage` and `support_url` fields, at least).

Can we have that?

**Comment by willdurand** [comment]
I set p4 because the frontend issue is also p4.

**Comment by eviljeff** [comment]
In an ideal API design, what would this look like? 
- All urls being an object with both outgoing'd and raw urls?  (Though that would be a bit of a pain for consumers e.g. frontend to handle in a backwards compatible way)  
- Additional fields for homepage and support_url?
- Some sort of encoding/notation that allows both urls in a single field (e.g. comma separated)?

**Comment by diox** [comment]
In a completely backwards-incompatible way, we could, if the `wrap_outgoing_links` parameter is passed, return all those URLs as an object with `original_url` and `wrapped_url` keys or something similar.

**Comment by eviljeff** [comment]
> We could even cheat and come up with a new parameter (though I'm not a big fan)

yeah, I was hoping we could use this to drop the `wrap_outgoing_links` param rather than add another one 😐

**Comment by eviljeff** [comment]
@willdurand to play Product and tell us what would be desirable.

**Comment by eviljeff** [comment]
> I'd go for an object including the outgoing'd and raw urls. We could also drop the query parameter, all API requests sent from addons-frontend include it, so it could become the norm. Given that it would be a BC break, this should only be enabled in v5+.

for urls that are translated fields (e.g. homepage and support_url), should the data structure be:
```
"homepage": {
    "en-US": {"url": "https://usa.homepage.com/", "outgoing": "https://outgoing.mozilla/3435rgiuhuhdf"},
    "fr": {"url": "https://france.homepage.com/", "outgoing": "https://outgoing.mozilla/6756uihuh"}
}
```
or
```
"homepage": {
    "url": {"en-US": "https://usa.homepage.com/", "fr": "https://france.homepage.com/"},
    "outgoing": {"en-US": "https://outgoing.mozilla/3435rgiuhuhdf", "fr": "https://outgoing.mozilla/6756uihuh"}
}
```
?

**Comment by eviljeff** [comment]
fwiw, the latter - with a top level `url` and `outgoing` is slightly easier to handle in the API field, but either is doable

**Comment by bobsilverberg** [comment]
> fwiw, the latter - with a top level `url` and `outgoing` - is slightly easier to handle in the API field, but either is doable

I would say the latter is also preferable. That way a localized string still looks like `{[lang]: 'value'}`, whereas with the first format we are changing the way a localized string looks for these specific fields.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this on AMO dev.

"outgoing" : is present in the V5 detail API. I checked for the following addons:

https://addons-dev.allizom.org/api/v5/addons/addon/620377/

https://addons-dev.allizom.org/api/v5/addons/addon/620378/

This is the format:

"homepage": {
        "url": {
            "en-US": "https://github.com/gorhill/uBlock#ublock-origin",
            "fr": "https://github.com/gorhill.french/uBlock#ublock-origin"
        },
        "outgoing": {
            "en-US": "https://outgoing.stage.mozaws.net/v1/e75dc77f92095f4ec7abd2a81f2cd144fcf7bd2c304ca63c12ca11481ac5c48d/https%3A//github.com/gorhill/uBlock%23ublock-origin",
            "fr": "https://outgoing.stage.mozaws.net/v1/842d1d286bb42e80fad545d60c95c60d22e342e4aebd717bc5e5d1798c7aad0c/https%3A//github.com/gorhill.french/uBlock%23ublock-origin"
        }
    },

**Comment by ioanarusiczki** [comment]
@eviljeff And the same for the Website:

"support_url": {
        "url": {
            "ca": "https://cube.catala.eu",
            "en-US": "https://cube.eu"
        },
        "outgoing": {
            "ca": "https://outgoing.stage.mozaws.net/v1/1d15a5763a044881a73f4c92c4a4e80a16e48ac34d9840cac483bd50a851ccb6/https%3A//cube.catala.eu",
            "en-US": "https://outgoing.stage.mozaws.net/v1/df79edbdb8c6e691316d811dd78f7cf5ca52f985018e4399ca70b097a4632efa/https%3A//cube.eu"
        }
