### ISSUE TITLE
Make abuse report message optional if the `reason` is present

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11204]
In the new Abuse Report system the message will be optional since a lot of info will already be provided by other fields. As long as AMO is still using the old system message should be mandatory. So, to get both worlds to coexist, make `message` optional if the "new" fields (`reason` etc) are present, regardless of value.

**Comment by ioanarusiczki** [comment]
@diox I think this works now with the "message" being optional. 
- I could post abuse reports (using Postman) when `addon` is provided with the slug  and `reason` is one of the 7 values [allowed ](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#post--api-v4-abuse-report-addon-) without `message` included. 
- when `reason`: null the abuse report cannot be posted, it will require `message`. 

Here's an example
POST /api/v4/abuse/report/addon/

![request](https://user-images.githubusercontent.com/33448286/57145394-cc024400-6dcb-11e9-9853-6b34d563332b.png)

Result - 201 Created making the `message` optional

![response](https://user-images.githubusercontent.com/33448286/57145456-eb00d600-6dcb-11e9-84f0-5fbcf185af65.png)
