### ISSUE TITLE
Remove ip_address column from abuse_reports table

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11216]
Once https://github.com/mozilla/addons-server/issues/11215 is done we can add a migration to remove the column from the `abuse_reports` table in the following push.

**Comment by championshuttler** [comment]
Hi @diox is it open for contributors?

**Comment by diox** [comment]
@championshuttler it is now!

**Comment by ramkv** [comment]
Hi @diox ,Can I work on the issue ?

**Comment by diox** [comment]
You can.

**Comment by ramkv** [comment]
Where is the abuse_reports table script located ? ,I have gone through the repository and is it this one ? addons-server/src/olympia/migrations/222-abuse-reports.sql

**Comment by diox** [comment]
You need to add a new migration file to that folder, increasing the number compared to the latest migration file already present in that folder.

**Comment by ramkv** [comment]
so will this do ?

_1089-drop-ip_address-from-abuse-report-.sql_
```
/* Drop the old column. */
ALTER TABLE `abuse_reports` DROP COLUMN `ip_address`;
```

**Comment by diox** [comment]
Yep, that should do it. Submit your pull request and we'll review it.

**Comment by ramkv** [comment]
Ok thanks :)

**Comment by Patil2099** [comment]
Please, Can I work on this issue?

**Comment by championshuttler** [comment]
@Patil2099 Sure!, You need to add the file at `/src/olympia/migrations`. Feel free to ask here if you need any help
