### ISSUE TITLE
Fix theme 69 repack for themes with specified guids in manifest

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11218]
follow-up for #11205
causes an exception such as 
```
uncaught exception:
  File "/data/olympia/src/olympia/addons/tasks.py", line 782, in repack_themes_for_69
    new_version = new_theme_version_with_69_properties(version)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/statsd/client/timer.py", line 38, in _wrapped
    return f(*args, **kwargs)
  File "/data/olympia/src/olympia/versions/utils.py", line 220, in new_theme_version_with_69_properties
    parsed_data = parse_addon(upload, user=author)
  File "/data/olympia/src/olympia/files/utils.py", line 1111, in parse_addon
    parsed = parse_xpi(pkg, addon, minimal=minimal, user=user)
  File "/data/olympia/src/olympia/files/utils.py", line 1007, in parse_xpi
    return check_xpi_info(xpi_info, addon, xpi, user=user)
  File "/data/olympia/src/olympia/files/utils.py", line 1045, in check_xpi_info
    raise forms.ValidationError(ugettext('Duplicate add-on ID found.'))
<class 'django.core.exceptions.ValidationError'>
ValidationError(['Duplicate add-on ID found.'])
```

**Comment by AlexandraMoga** [comment]
@eviljeff does this require any QA?

**Comment by eviljeff** [comment]
nothing specific, though it would be useful to know about some add-ons that specify their guid in the manifest on amo stage for when we upgrade all of those - to check they were indeed upgraded.

**Comment by AlexandraMoga** [comment]
I'll have a look into my older themes to see if I find any with a custom guid. Are you going to run the upgrade for stage this week?

**Comment by eviljeff** [comment]
probably not - there are at least two issues discovered during the first 1000 themes that need fixing first.  (It's possible though)

**Comment by AlexandraMoga** [comment]
Verified fixed on stage with Fx66, WIn10x64

Themes that had a custom guid set in the manifest were successfully upgraded.

Here are some examples:
https://addons.allizom.org/en-US/developers/addon/minimalist-retrowave9/versions
https://addons.allizom.org/en-US/developers/addon/happycat/versions
https://addons.allizom.org/en-US/developers/addon/old-properties/versions
