### ISSUE TITLE
Store current add-on guid when saving an Abuse Report against an add-on in database

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11219]
In the Abuse Reporting API, when we save an abuse report against an add-on in the database, we don't save the `guid` - we only do for add-ons we don't know about.

In the admin, we want to be able to find all reports for a given guid, so we need to also store the guid that the add-on had when the report was created.

**Comment by diox** [comment]
Note: a migration was added to backfill existing abuse reports data as well.

**Comment by AlexandraMoga** [comment]
The guid field is populated in admin abuse reports for:
 - reports against add-ons that exist in our database
 - reports against add-ons that are not present in our database (i.e an add-on deleted from AMO which is still in use by some users, or for add-ons with sideload install method)

I've also looked through older reports to verify that the guid has been backfilled. 


I'm marking the issue as verified fixed on -dev
