### ISSUE TITLE
remove legacy unsubscribe notifications page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11213]
We had to leave it around while the rest of the legacy frontend pages were removed because we forgot to reimplement it on new frontend.  But it's been added to fronted now - see mozilla/addons#930 and connected issues - so we can drop it from addons-server.

**Comment by ioanarusiczki** [comment]
@eviljeff As before I guess that  qa testing should focus on dev hub regressions. Therefore I'm going to add the verified label after the release testing is completed with FF66 - Win10.
