### ISSUE TITLE
Upgrading to the new django-product details slowed things down on prod

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1121]
"I think the newest version of product details using memcached to cache the product information,
which for us, is really slow"

We had to revert this change: https://github.com/mozilla/olympia/commit/bad516af81d94d57218c51430371384ac5a0839c 

...lets see if we can HTTPS support that's fast for AMO.

**Comment by diox** [comment]
Per @EnTeQuAk in #3200: 

> We do have our own backend for django-mozilla-product-details now to restore the old behavior of having everything in-memory (and not using the cache, because network roundtrips are too expensive here) for performance reasons, see https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/product_details_backend.py for more details.
