### ISSUE TITLE
500 server error received when logging out admin tools and then log in is no longer possible

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11226]
STR:
1. try to log in to https://addons-internal.dev.mozaws.net/en-US/firefox/

Expected result:
https://addons-internal.dev.mozaws.net/en-US/admin/ loads

Actual result:
Internal Server Error 500 

Notes:
The user can login successfully from AMO dev or stage from dev hub - tools - admin tools. 
Once log out is made from https://addons-internal.dev.mozaws.net/en-US/admin/ the 500 is received.

![500 admin tools](https://user-images.githubusercontent.com/33448286/56419725-f02a3500-62a3-11e9-9e3d-9c4f7b87f5f6.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/5341582/?query=is:unresolved
