### ISSUE TITLE
Incorrect version number in repacked themes if the previous version number consists of a single digit

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11235]
Follow up for #10627 

**STR:**
1. Open the versions page for the following theme: https://addons-dev.allizom.org/en-US/firefox/addon/spring-green78/versions/
2. Compare the current  version number - the version that has been repacked - with the previous version

**Actual result:**
The version number for the re-packed theme is `3.0`

**Expected result:**
The version number for the re-packed theme is `4.0` (upgraded from version`3`)

**Notes:** 
- this can be a problem in the following scenario: if a user had version `3` installed, he won't receive an update to `3.0` because this is not interpreted as a new version during update check
- reproduced on -dev with Fx66, Win10x64

![image](https://user-images.githubusercontent.com/31961530/56582344-bcbb1380-65df-11e9-966b-37cf9948d0dc.png)

**Comment by AlexandraMoga** [comment]
@eviljeff can you run the script on individual themes? I'd like to verify that the issue is fixed for the following theme Ids: 616671, 616670

**Comment by eviljeff** [comment]
done.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Winx64

The repacked version number seems to be correct now for the given examples:

https://addons-dev.allizom.org/en-US/firefox/addon/pompas-grass-by-madonna/versions/
https://addons-dev.allizom.org/en-US/firefox/addon/fire-and-water2/versions/

![image](https://user-images.githubusercontent.com/31961530/56655762-64961700-669c-11e9-8c4e-d8fc1952d538.png)
