### ISSUE TITLE
Prohibit developers from using stars in name/description

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#11254]
Some add-on developers use tactics by adding stars/half stars in their add-on description or add-on name.

"FooBar BarFoo ★★★★★"
"BarFoo ⭐⭐⭐⭐⭐"

These should not be allowed (including variants) because it's confusing and gives the impression of five stars while the actual score might be 2 or 3 stars.

**Comment by eviljeff** [comment]
Limit 🌟 s to 3 or less? :wink:

**Comment by eviljeff** [comment]
I think this is best dealt with as misleading content and manually addressed when reviewers come across it, so closing.

@jvillalobos to 🙄. Note if we were to restrict certain emoji we'd need an exhaustive list of which ones couldn't be used (there are multiple types of star, for example). Adding more complex restrictions would be more work too and liable to edge cases.

**Comment by kewisch** [comment]
I'd be fine prohibiting certain emojis. For the specific case this came up for we've contacted the developer.

**Comment by wagnerand** [comment]
Alternative approaches:

* We could forbid any emojis in the summary (maybe a little too strict).
* We could forbid the summary to start with any or certain emojis.

**Comment by eviljeff** [comment]
It's not whether or it's desirable to not have spammy titles, but what exact set of rules would have to be applied to be worth doing, given that they'll be easy to work around if we don't want to put up a huge roadblock to submission.  Akismet was the solution to bad content.

**Comment by jvillalobos** [comment]
Sounds to me more like a content review policy than a hard rule.

**Comment by eviljeff** [comment]
assigning to @jvillalobos to close as per his comment as when I closed the issue it was reopened 😛

**Comment by jvillalobos** [comment]
Alright, let's try that.
