### ISSUE TITLE
Browsing an add-on from the reviewer API is a 500 in stage

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11256]
### Describe the problem and steps to reproduce it:

- Sign in to stage with a reviewer account
- Go to https://reviewers.addons.allizom.org/en-US/reviewers/review/remote-script-coinhive-07-02 (or any add-on)
- Or you can load this directly: https://code.addons.allizom.org/en-US/browse/1002459/versions/2091516/

### What happened?

Unexpected status for GET /reviewers/addon/1002459/versions/2091516/?lang=en-US: 500

GitError: old reference value does not match
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/5514489/?query=is:unresolved

KeyError: '0cc959419d51463ca7fc2f9e0f68073365ac3dd6'
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/5611480/?query=is:unresolved

OSError: failed to create locked file '/mnt/efs/addons.allizom.org/git-storage/9/99/763399/addon/.git/refs/heads/listed.lock': File exists
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/5515258/?query=is:unresolved

### What did you expect to happen?

The browse page should load without errors

### Anything else we should know?

This is working on dev

**Comment by wagnerand** [comment]
This affects the new code manager only, right? The old file viewer seems to be working?

**Comment by EnTeQuAk** [comment]
Correct, and this is only happening on -stage.

**Comment by EnTeQuAk** [comment]
It seems that the git mass re-extract from February didn't work properly for some versions. I'll schedule another re-extract once the static theme repack is done. In the meantime just post version ids and I'll fix them manually.

**Comment by willdurand** [comment]
This issue looks fixed.

**Comment by EnTeQuAk** [comment]
It is indeed. If you notice any other issues, just ping me and I'll schedule a re-extract.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I have run into the server error with several add-ons. Some are older, but there are also examples from 2019 that fail. 

1. March 2017 - https://code.addons.allizom.org/en-US/browse/618912/versions/1703054/
2. Oct 2017 - https://code.addons.allizom.org/en-US/browse/619415/versions/1703785/
3. Jan 2018 - https://code.addons.allizom.org/en-US/browse/619586/versions/1704034/
4. Aug 2018 - https://code.addons.allizom.org/en-US/browse/620317/versions/1706778/
5. Jan 2019 - https://code.addons.allizom.org/en-US/browse/1002434/versions/2091472/

**Comment by EnTeQuAk** [comment]
I ran extraction on all of them and double-checked that it's nothing else. They seem to work now nicely, thanks for noticing!
