### ISSUE TITLE
Previews for repacked themes are not available in search results on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11253]
**STR:**

1. Open AMO stage
2. Do a blank search and filter by recently updated

**Actual result:**
Most of the themes returned in search results do not have a preview

**Expected result:**
Theme previews are available in search results

**Notes:**
- UPDATE: for some of the themes, the preview is displayed on the theme detail page. For others, previews are missing completely (see https://addons.allizom.org/en-US/firefox/addon/happycat/)
- reproduce only on stage with Fx66, Win10x64

![2019-04-25_10-26-34](https://user-images.githubusercontent.com/31961530/56717397-42a49f00-6745-11e9-9f5c-406ffcfc389b.gif)

**Comment by eviljeff** [comment]
the previews all seem to be present now - looks like it was just celery tasks being delayed.  Git-extraction will be disabled when we run this on prod which should hopefully mean there won't be as much as a delay.
