### ISSUE TITLE
More tweaking of abuse report API parameters

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11263]
Like #10753 and #11191 but this time because Firefox has some more possible values for some of the parameters that we may want to handle. In addition, @rpl and I have agreed to change the values of a couple of the parameters to better match his patch.

**Comment by ioanarusiczki** [comment]
@diox I think this is about updating the accepted values for the `reason` parameter which I already used for testing here https://github.com/mozilla/addons-server/issues/11204. 

If I use `harmful`, `spam_or_advertising` or `browser_takeover` I cannot post the abuse report with POST /api/v4/abuse/report/addon/

`  "reason":
   "\"harmful\" is not a valid choice."  `

Let me know if there's anything else I should check on.
Thanks!
