### ISSUE TITLE
Expose canned responses for code-manager

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11276]
As part of https://github.com/orgs/mozilla/projects/79 we want reviewers to select canned responses.

For that we need to expose them through an API.

**Comment by eviljeff** [comment]
idea: replace the current database-backed canned responses models with constants defined directly in the codemanager repo.  Editing them using django admin is a bit of a pain, and is so rarely done anyway (afaik) that writing a PR to update them is a similar amount of effort.  
@wagnerand and @kewisch to contradict me here.

**Comment by kumar303** [comment]
There are some additional user stories here which will probably affect how canned comments are stored: https://github.com/mozilla/addons-server/issues/11288

**Comment by AlexandraMoga** [comment]
I think the [canned-responses](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-canned-responses-) api functionality was verified - for dev at least - in https://github.com/mozilla/addons-server/issues/11386#issuecomment-493032792 , so I'm going to mark this issue as verified fixed.
