### ISSUE TITLE
Always show a compare link in reviewer tools

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11286]
### Describe the problem and steps to reproduce it:

- As a developer, upload two add-on versions and let them get auto-approved
- As a reviewer, do not manually approve the first version
- As a reviewer, begin reviewing the second version

### What happened?

There is no *Compare* link, only a *Browse* link. Or, after https://github.com/mozilla/addons-server/issues/11285, the *Compare* link is disabled.

### What did you expect to happen?

There should always be an active *Compare* link. When viewing version two (of this scenario) in the comparison mode, it should show *all* changes for all files since there is no manually reviewed version to compare it to. 

The diff presented would mimic what already happens today: newer versions are only compared to the last manually reviewed version.

### Anything else we should know?

This would add some consistency to the workflow. You could always use the compare mode for reviewing any version, if you want to.

This might be a lot harder than https://github.com/mozilla/addons-server/issues/11285 because I'm not sure what backend changes are needed.

**Comment by diox** [comment]
The 2 blocks of code relevant for this in the current code are:

```python
    try:
        # Find the previously approved version to compare to.
        show_diff = version and (
            addon.versions.exclude(id=version.id).filter(
                # We're looking for a version that was either manually approved
                # (either it has no auto approval summary, or it has one but
                # with a negative verdict because it was locked by a reviewer
                # who then approved it themselves), or auto-approved but then
                # confirmed.
                Q(autoapprovalsummary__isnull=True) |
                Q(autoapprovalsummary__verdict=amo.NOT_AUTO_APPROVED) |
                Q(autoapprovalsummary__verdict=amo.AUTO_APPROVED,
                  autoapprovalsummary__confirmed=True)
            ).filter(
                channel=channel,
                files__isnull=False,
                created__lt=version.created,
                files__status=amo.STATUS_APPROVED).latest())
    except Version.DoesNotExist:
        show_diff = None
```

```jinja
{% if show_diff and version == latest_version_in_channel %}
      &middot;
      <a
        href="{{ code_manager_url('/compare/{}/versions/{}...{}/'.format(addon.pk, show_diff.pk, version.pk)) }}"
        title="Compare this version to the last reviewed version"
      >
        {{ _('Compare') }}
      </a>
    {% endif %}
```

Changing the conditions to always show a link is easy enough, but what should the link point to ?

**Comment by wagnerand** [comment]
I agree with @kumar303 that the link should point to the respective previous human reviewed (approved/confirmed/rejected) version.

We could probably even rename the link to "Compare to previous" to make it more clear.

**Comment by diox** [comment]
That's a different scenario - I was thinking about the case where this is no version to compare against, but your use case can probably be addressed at the same time.

**Comment by wagnerand** [comment]
If there is no version to compare to, I wouldn't show a compare link.

**Comment by kumar303** [comment]
> If there is no version to compare to...

It would be great if we could show a comparison anyway, a diff showing all files as newly added files. This would make the compare page usable in all scenarios. However, that's probably out of scope for the issue at hand.

**Comment by wagnerand** [comment]
The issue with that is that it makes reading sequentially through the code much harder as we deal with syntax highlighting on colored background.
