### ISSUE TITLE
Show a disabled compare link in the reviewer tools

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11285]
### Describe the problem and steps to reproduce it:

- As a developer, upload two add-on versions and let them get auto-approved
- As a reviewer, do not manually approve the first version
- As a reviewer, begin reviewing the second version

### What happened?

There is no *Compare* link, only a *Browse* link

### What did you expect to happen?

There should be a disabled *Compare* link with a tooltip explaining why the link is disabled

### Anything else we should know?

The reason there is no compare link is because no manual review has taken place yet. The compare link only appears when it would be possible to compare the latest version to an older version that was manually reviewed.

A better solution to this problem is described in https://github.com/mozilla/addons-server/issues/11286 but that may be harder to implement.

**Comment by kumar303** [comment]
The UI in https://github.com/mozilla/addons-code-manager/issues/758 will serve as a workaround to this problem.

**Comment by wagnerand** [comment]
> The UI in [mozilla/addons-code-manager#758](https://github.com/mozilla/addons-code-manager/issues/758) will serve as a workaround to this problem.

That is not just a workaround. It's also a shortcut when staying within the code manager, and for other workflows, for example when flipping through versions.

**Comment by kumar303** [comment]
Definitely. I just wanted to link the two since solving https://github.com/mozilla/addons-server/issues/11285 is not straight forward.
