### ISSUE TITLE
Add rate-limiting to the submission process

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11287]
Add-on submission process doesn't have rate-limiting inside the app, it's done by ops at the nginx level instead. We should move it to inside addons-server to have finer grained control over it like we do for other APIs.

We should rely on DRF's throttling classes for that, with the catch that it needs to work with devhub submissions as well, which are not API based. We probably want to modify:
- `olympia.signing.views.VersionView` (`put` and `post`)
- `olympia.devhub.views.upload_for_version`
- `olympia.devhub.views.submit_version_upload`

**Comment by AlexandraMoga** [comment]
@diox I need a bit of help with understanding what this issue is about exactly. 
At first, I thought that I should be blocked if I try to consecutively submit unlisted add-ons through `POST /api/v4/addons/` or via the add-on self distribution page in devhub, but that wasn't the case.
I've repeated the process on -dev with two accounts using the same IP.

**Comment by diox** [comment]
@AlexandraMoga currently the limits are 3/minute and 20/hour per user, 6/minutes and 50/hour per ip. All are applied at the same time. Devhub is currently not affected by this, I'm going to file a follow-up for that in a minute.

**Comment by diox** [comment]
Note: https://github.com/mozilla/addons-server/issues/11342 applies the same rate limiting to devhub.

**Comment by AlexandraMoga** [comment]
@diox I've run into the 429 error while using the signing API (`POST /api/v4/addons/`), but I'm not sure if the rate-limiting is fired correctly. Again, this could be me not fully understanding how the formula works. 

Here is what I did:

1. from the same account (ID 10641818) and the same IP
2. within one minute timeframe (which is also the duration of my JWT token)
3. sent 14 submission requests => the 429 status was fired at request 12, then request 13 and 14 were successful and finally at request 15 the limit was hit again. 

I haven't done any other submissions close to that time with this user or with others.

**Comment by diox** [comment]
In this instance this is just using the API right ? Just in case, could you try with stage (it should already be on there since we cherry-picked everything to go to prod) ? Also would help to have exact timestamps of each submission attempt.

**Comment by AlexandraMoga** [comment]
@diox I've tried with stage this morning and the results were more promising

By following the same test method as above, using only the API, I've run into the submission limit after my third submission, which is what I've expected, considering that the request was coming from the same user. 

Here is a snapshot of the requests that were sent and their response statuses:

<details>
<summary> Submission requests </summary>

POST https://addons.allizom.org/api/v4/addons/ 09:23:05.574 - status 201
POST https://addons.allizom.org/api/v4/addons/ 09:23:07.633 - status 201
 POST https://addons.allizom.org/api/v4/addons/ 09:23:08.913 - status 201
POST https://addons.allizom.org/api/v4/addons/ 09:23:10.079 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:11.153 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:12.237 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:13.308 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:14.487 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:15.554 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:18.971 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:20.659 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:21.914 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:27.047 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:29.614 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:31.080 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:32.406 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:33.419 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:34.881 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:37.286 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:38.710 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:41.448 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:43.039 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:43.913 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:44.896 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:46.421 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:49.671 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:51.231 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:52.922 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:53.938 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:55.046 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:56.175 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:57.374 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:58.482 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:23:59.482 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:00.316 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:01.095 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:01.861 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:02.509 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:03.290 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:04.065 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:04.817 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:05.755 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:06.533 - status 401
...............
POST https://addons.allizom.org/api/v4/addons/ 09:24:11.281 - status 429
POST https://addons.allizom.org/api/v4/addons/ 09:24:13.964 - status 429

</details>

The first three submissions were successful,  while those that followed, until request 42, were blocked. At request 43 my JWT has expired - hence the 401.
The weird part is that after receiving the 401, the next requests made with the expired JWT returned again a 429. 

I also have a question regarding the the response messages. For some requests, I have received the `Request was throttled. Expected available in x seconds.` message, while for most of them the response body was empty - I have a full log [here](https://pastebin.com/APnRYSzQ) if you want to check it.
I remember seeing a discussion on IRC where you mentioned that we should not display an error message, specifically, we should not mention the time limit.
