### ISSUE TITLE
'frame_inactive' theme property changed to 'frame' in theme repack

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11296]
For theme preview rendering purposes it was helpful to translate `frame_inactive` to `accentcolor` before it was supported.  Now `accentcolor` is deprecated we're translating `frame_inactive` to `frame` which is possibly wrong for theme preview purposes, but certainly wrong for the manifest.  If the developer has specified `frame_inactive` we shouldn't rewrite it as `frame`.

**Comment by AlexandraMoga** [comment]
@eviljeff I didn't know of any themes using the `frame_inactive` color property on either dev or stage. 

I've submitted two examples on -dev to test with: 616713 and 616712. Can you run the repacking script for them?

**Comment by eviljeff** [comment]
> I've submitted two examples on -dev to test with: 616713 and 616712. Can you run the repacking script for them?

Done.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

The `frame_inactive` property doesn't change to `frame` in the manifest after the repack. The preview is correct and the `frame_inactive` property is behaving as it should in the browser.

Here is the example - https://addons-dev.allizom.org/en-US/firefox/addon/frame-inactive-old-props/

![2019-05-08_13-00-41](https://user-images.githubusercontent.com/31961530/57367409-94abe280-7191-11e9-8c45-4f40c309b6ab.gif)
