### ISSUE TITLE
KeyError: '<script>alert(1)' in Reviewers/Browse API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11297]
### Describe the problem and steps to reproduce it:

* Submit an add-on with atypical filenames (example: https://github.com/mozilla/addons-server/issues/11297#issuecomment-488583369)
* Browse it in the code manager (see https://github.com/mozilla/addons-code-manager/issues/666)

### What happened?

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5469441/?query=is:unresolved

```
KeyError: '<script>alert(1)'
  File "rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "olympia/reviewers/views.py", line 1387, in retrieve
    return Response(serializer.data)
  File "rest_framework/serializers.py", line 563, in data
    ret = super(Serializer, self).data
  File "rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "olympia/addons/serializers.py", line 177, in to_representation
    return super(SimpleVersionSerializer, self).to_representation(instance)
  File "rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "rest_framework/fields.py", line 1889, in to_representation
    return method(value)
  File "olympia/reviewers/serializers.py", line 191, in get_content
    blob_or_tree = tree[self.get_selected_file(obj)]
```

### What did you expect to happen?

No errors

**Comment by kumar303** [comment]
This one may be related: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5547253/?query=is:unresolved

**Comment by psiinon** [comment]
Example add-on ZIP which should exhibit this attached.
[weird-file-names2.zip](https://github.com/mozilla/addons-server/files/3137132/weird-file-names2.zip)

**Comment by willdurand** [comment]
I uploaded the ZIP file in -dev:

- https://addons-dev.allizom.org/en-US/firefox/addon/keyerror/
- https://code.addons-dev.allizom.org/en-US/browse/616714/versions/1688036/

**Comment by willdurand** [comment]
So there should actually be an error when `<script>alert(1)` is sent to the API (without the semi-colon) because this file does not exist. That being said, it should not return a 500 but a 400 or 404.

That's a slightly different issue. Any non-existent file requested to the Browse API will result in a 500 error.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev 

the following request (made when authenticated with a user that has the necessary reviewer permissions) is throwing a 404 now instead of a 500:

https://addons-dev.allizom.org/api/v5/reviewers/addon/616822/versions/1688146/?file=<script>alert(1)
