### ISSUE TITLE
500 Internal Server Error when a 3 digit number is typed in the search field

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11305]
Followup for https://github.com/mozilla/addons-server/issues/11133

STR:
1. Go to  /models/abuse/abusereport/ on AMO dev 
2. Type in the search field "123" or "12a" or "559" then click the Search button 
3. Observe the page

Expected result:
Eventually no results are returned.

Actual result:
500 Internal Server Error. 

Notes:
Reproducible on AMO dev - FF66(Win10). 

In the Search field

![500 server error for 3 digit numbers](https://user-images.githubusercontent.com/33448286/57079749-b1f83100-6cf9-11e9-9492-9cbab1944389.gif)

I reproduced this issue every time with "By minimum reports count (grouped by guid)" filter when using the following scenario: I tried to search using a value (0 for the first attempt) and then I changed the value to "69" and clicked "Submit".

![500 server error by minimum reports count](https://user-images.githubusercontent.com/33448286/57079900-056a7f00-6cfa-11e9-806d-5331572ca0a6.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5488331/?query=is:unresolved

**Comment by diox** [comment]
Actually caused by https://github.com/mozilla/addons-server/issues/11324 - the filters are causing some old webapps to show up, and the abuse report code doesn't like that.

**Comment by ioanarusiczki** [comment]
@diox 
I tried again a couple of scenarios but I could no longer reproduce a 500. 
Verified on admin tools dev - FF66(Win10). 

![no 500 at search](https://user-images.githubusercontent.com/33448286/57286710-88a32080-70be-11e9-9136-b346c07e4a09.gif)
