### ISSUE TITLE
jpm sign: Version does not match install.rdf. ( status: 400 ) 

### ISSUE THREAD

**Issue by pnguyen-pi** [mozilla/addons-server#1130]
Hi everybody,

I tried to use "jpm sign" command to retrieve a new XPI for my add-on signed by Mozilla. But I got a strange issue regard to version number does not match install.rdf file

> JPM [info] Signing XPI: 
> JPM [error] Server response: Version does not match install.rdf. ( status: 400 )
> JPM [info] FAIL

I verified the install.rdf file and its version is 2.14.7. Also tried to installed this XPI to my FF browser and it still displayed version of 2.14.7 in the FF browser. Not sure how I got this issue and how to bypass it because I also tried to create a new submission of this XPI manually on Develop Hubs and no issue/warning is returned like above.

Please help me on this issue.

**Comment by kumar303** [comment]
I think this has been fixed as part of https://github.com/mozilla-jetpack/jpm/issues/465 . Could you test it out following these [install instructions](https://github.com/mozilla-jetpack/jpm/#install) to see if it works before we publish a release?

**Comment by andymckay** [comment]
The release has been published and I think this is fixed. If that's not the case, please re-open @pnguyen-pi
