### ISSUE TITLE
After "Delete selected abuse report" action is used the deleted reports are no longer available in the list 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11304]
Followup for  https://github.com/mozilla/addons-server/issues/11133

@diox said 
> One important change is that Abuse Reports are now soft-deleted, meaning once deleted, reviewers shouldn't be able to see them anymore in reviewer tools, but admin still can.

STR:
1. Go to en-US/admin/models/abuse/abusereport/ in admin tools 
2. Select a couple of reports and choose "Delete selected abuse report" then click "Go"
3. Observe the list

Expected result:
The state of the selected reports change to "Deleted" and they are still available in the list.

Actual result:
The reports are permanently deleted from the list and a green message is displayed 
"Successfully deleted 1 abuse report."

Notes:
When the reports are individually deleted using the red "delete" button the described issue is not reproducible, the reports remain in the list but they will no longer be available in rev tools on the review and abuse reports pages. 
This issue is reproducible on AMO dev with FF66(Win10). 

![successfully deleted ](https://user-images.githubusercontent.com/33448286/57078276-a3f4e100-6cf6-11e9-85e9-94f5912f65d5.gif)

**Comment by diox** [comment]
Can reproduce, this is because the `delete` action on the list calls `delete()` on the queryset which does a real delete. Need to customize the queryset `delete()` method like we do for ratings to avoid that.

**Comment by ioanarusiczki** [comment]
@diox I verified this in django admin dev with FF67(Win10). 
The deleted reports will remain in the list with status "deleted". They will not be available in the Rev Tool pages (which is expected). 

Only now I wish they were deleted because two reports which  have a long unbroken string in the Message excerpt field and break the layout of the pages (in admin tools and rev tools as well). - maybe I should file an issue about it.

![deleted](https://user-images.githubusercontent.com/33448286/58164241-1e79a680-7c8e-11e9-8514-1201dd6bf825.png)
