### ISSUE TITLE
Search by add-on id in abuse reports admin is not returning results

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11307]
Followup for https://github.com/mozilla/addons-server/issues/11133

> When searching, the following fields should be available for filtering:
> - Reports for a specific add-on (by id, name, or slug)

STR:
1. Load AMO dev admin tools via /en-US/admin/models/abuse/abusereport/
2. Try to make a search using an add-ons id (I tried with 6 digit ids such as 502857 or 616681)
3. Observe the results

Expected:
The addon abuse report is available.

Actual result:
404 not found

Notes:
Search can be made using the name, guid or slug of an add-on. 

![search using an id](https://user-images.githubusercontent.com/33448286/57082262-110c7480-6cff-11e9-85b9-851233bd7635.gif)

**Comment by diox** [comment]
It's trivial but I forgot to implement this.

**Comment by diox** [comment]
>  Is this alright or the Search should appear for "All" too (perhaps to search by Name if not ID).

It's by design yes, to limit performance issues with search.
