### ISSUE TITLE
Search bar ux issue when clicking "x" from the filter menu

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11309]
Followup https://github.com/mozilla/addons-server/issues/11133

STR:
1. Go to admin tools dev to abuse reports /en-US/admin/models/abuse/abusereport/
2. Make a search filtering by created - set the dates and click Submit
3. After the results are displayed click the "x" on the right side of the dates 
4. Observe the search bar on the top of the page

Expected results:
Nothing happens.

Actual results:
The search list with the previous searches is automatically opened. 

Notes:
Reproducible on admin tool dev - FF66(Win10).

![search bar ux issue](https://user-images.githubusercontent.com/33448286/57086746-5e8cdf80-6d07-11e9-8843-464308937ebb.gif)

Same thing is reproducible for "By minimum reports count (grouped by guid)" when a second search using this filter is done -> meaning that a number is already typed in and the user clicks "^" on the right side of the box to change it.

![search bar ux issue2](https://user-images.githubusercontent.com/33448286/57086766-69477480-6d07-11e9-8b4b-8a309eed5bf8.gif)

**Comment by diox** [comment]
Caused by the autofocus on the search box. Need to work around it but not a high priority issue.
