### ISSUE TITLE
An incorrect version number is displayed in the admin abuse report list

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11318]
Followup for https://github.com/mozilla/addons-server/issues/11133

STR:
1. Go on admin tools to the abuse reports list
2. Observe that there's a "112.3" associated with the Name 
3. Click the addon and observe the Addon version field (take for example foxyproxy-standard guid foxyproxy@eric.h.jung which has multiple version, the last is 6.3)

Expected result:
The correct version number is displayed next to the addons name.

Actual result:
The version is "112.3". 

Notes:
I can't tell if  the name should be associated with the version number for addons with only one version but I've noticed the issue being reproducible for these too, for example 
616668: axe - with version 3.8.0. 

![112 3](https://user-images.githubusercontent.com/33448286/57127982-b3c60100-6d9a-11e9-8cbb-39b9309d8343.gif)

**Comment by diox** [comment]
The version being displayed is the one that was submitted in the report, *not* the latest version for this add-on. This will be slightly clearer once https://github.com/mozilla/addons-server/issues/11135 lands
