### ISSUE TITLE
rename api/v4dev to api/v5 and make it generally available (on prod)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11328]
v4dev is being used by nearly-production addons-code-manager and will be the next default after v4 is frozen.  v4dev is limited to dev and stage only; v5 will be generally available (on production AMO too)

**Comment by AlexandraMoga** [comment]
@eviljeff what are the implications of this change? Are other parts of AMO, except for the code-manager, affected by it? I need to understand what QA should cover in terms of regression tests. 
Thanks

**Comment by eviljeff** [comment]
@AlexandraMoga only code-manager used v4dev (now uses v5) right now.  There shouldn't be any impact to other consumers of the v4 or v3 apis.

**Comment by AlexandraMoga** [comment]
Addons code-manager is working fine and all api requests are made to `api/v5`
