### ISSUE TITLE
Deactivate "View on site" in abuse reports admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11321]
"View on site" in abuse reports admin returns a 500 error, https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5482265/?query=is:unresolved

That link should just be deactivated.

cc @ioanarusiczki

**Comment by ioanarusiczki** [comment]
@diox I've noticed that the button "View on site" returns a 500, but also I knew the form for "Change abuse reports" is going to change so I thought this is going to be discussed when https://github.com/mozilla/addons-server/issues/11136 lands. 

Button was removed - it is no longer available on Admin Tool dev - FF66(Win10). 

![View on site dev](https://user-images.githubusercontent.com/33448286/57282274-6062f400-70b5-11e9-9efa-4f11d897813c.gif)

The "View Site" - returns a 500 too, I've checked the "View on site" for admin/models/addons/addon/id/change/ and this one is working fine. So I filed an issue for "View Site" https://github.com/mozilla/addons-server/issues/11352
