### ISSUE TITLE
All add-ons are disabled, including those released by firefox

### ISSUE THREAD

**Issue by suiahaw** [mozilla/addons-server#11336]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

All add-ons are disabled, including those released by firefox

Windows 10 1809 17763.437 x64

### What happened?

These extensions are not in line with today's Firefox standard and are therefore disabled.
[Picture1]
When I want to reinstall the plugin, I am prompted that the network connection is wrong.
[Picture2]

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

[Picture1]
![Picture1](https://user-images.githubusercontent.com/45323123/57173755-43d17c80-6e67-11e9-99ab-ba6fef95d41a.png)
[Picture2]
![Picture2](https://user-images.githubusercontent.com/45323123/57173759-4b912100-6e67-11e9-9587-4db962f7e76a.png)

**Comment by wagnerand** [comment]
This is due to a certificate issue. Our team is currently working on a fix and we'll be providing updates on this thread: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/4
