### ISSUE TITLE
Add-on name in django admin ratings page is always "None"

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11333]
### Describe the problem and steps to reproduce it:

1. Leave some user ratings for public add-ons. Note your user ID.
2. As an admin, go to `/admin/models/ratings/rating?user=<user_id>` using the user ID above.

### What happened?

Note the add-on name being `None`.

### What did you expect to happen?

The proper add-on name being shown.

### Anything else we should know?

<img width="400" alt="Screenshot 2019-05-03 at 17 38 20" src="https://user-images.githubusercontent.com/873258/57148630-4b8f1380-6dca-11e9-9b4b-b6d6a4aba1fc.png">

**Comment by eviljeff** [comment]
fwiw, I've seen this in other places too so there _may_ be a generic problem with `Addon.__str__` (or it may be an unconnected coincidence)

**Comment by diox** [comment]
Something something translations ?

**Comment by eviljeff** [comment]
Something something django2.2 something something translations also?

**Comment by ioanarusiczki** [comment]
@diox 
I verified this on django admin dev - with FF66(Win10) and I could no longer reproduce this when making a search with `/admin/models/ratings/rating?user=<user_id>`

Before - on stage 
![None - on stage](https://user-images.githubusercontent.com/33448286/57704669-093bc100-766b-11e9-9842-07a0ae863907.png)

Now - on dev 
![now on dev](https://user-images.githubusercontent.com/33448286/57704857-6df71b80-766b-11e9-822c-e0ae13ec18d8.png)
