### ISSUE TITLE
Signing API: Check Status Only works for Extensions with Multiple versions

### ISSUE THREAD

**Issue by RanjthKumar45** [mozilla/addons-server#1133]
I uploaded xpi file manually to my account and tried to get the status of it using API : https://olympia.readthedocs.org/en/latest/topics/api/signing.html#checking-the-status-of-your-upload

But it always results in 404 error.

Whereas if i upload the another version manually and tried to get the status with help of api which works fine.

Is this is expected by design or bug?

**Comment by andymckay** [comment]
It's hard to tell whats going on without know the API endpoints you hit, or the add-ons. It could be a simple hitting the wrong URL problem. I don't suppose you have that available do you?

**Comment by mstriemer** [comment]
I just tried this on stage and going through the web interface indeed requires that you have multiple versions.

I think what's happening is the `FileUpload` is created before the `Addon` so there is no `addon_id` set on the `FileUpload`. When the form is submitted through the web interface we should go back and attach the right `addon_id` (and `version` if it isn't set) to the `FileUpload`.
