### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by arnavvats** [mozilla/addons-server#11337]
### Describe the problem and steps to reproduce it:
I'm trying to setup the local repository but I am encountering a lot of erors.
### step 1: docker-compose pull
This worked fine
### step2: docker-compose up -d
This gave ModuleNotFoundError: No module named 'local_settings'
After this I created local_settings as a copy of settings.py
But after re-running command, it gives multiplte file not found errors like
FileNotFoundError: [Errno 2] No such file or directory: '/code/storage/shared_storage/tmp/tmp1dxomy4j'

### What happened?
I'm encountering a lot of errors and unable to setup the repository locallly.

### Anything else we should know?
I'm running a Mac pro with macos 10.13

**Comment by eviljeff** [comment]
`docker-compose up -d` threw those errors? Are you sure? All that does is start the containers in the background - so you wouldn't see errors in the console. 
Are you following the steps in https://addons-server.readthedocs.io/en/latest/topics/install/docker.html ?

**Comment by arnavvats** [comment]
The errors occurred in this step:
`make initialize_docker  # Answer yes, and create your superuser when asked.
# On Windows you can substitute `make initialize_docker` for the command:
docker-compose exec web make initialize`

**Comment by arnavvats** [comment]
The errors occurred in this step:
make initialize_docker  # Answer yes, and create your superuser when asked.
# On Windows you can substitute `make initialize_docker` for the command:
docker-compose exec web make initialize

**Comment by ksarthak4ever** [comment]
Has this issue been resolved ? I am also getting same errors when i enter command `make initialize_docker` . Though i can start the server simply by `docker-compose up`

**Comment by eviljeff** [comment]
It sounds like you may have file permission issues.  If you can include all the logs we can have a look.

**Comment by EnTeQuAk** [comment]
You may have to run `chown -R USER:USER ./storage` to transfer ownership back to you. That'll fix your problems.

If you run into any further problems, please let us know.
