### ISSUE TITLE
Apply rate-limiting from the signing API to devhub

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11342]
Rate-limiting added in #11287 should also affect devhub.

**Comment by AlexandraMoga** [comment]
@diox I've tried again to trigger this rate-limiting error in dev hub, but I'm still not running into it.

Here is what I did:
1. from the same account (ID 10641840) and the same IP
2. within the same hour (start time May 7, 2019, 7:35 a.m - end time May 7, 2019, 8:33 a.m)
3. submitted 53 unlisted add-ons in devhub and haven't run into an error

Here is the activity log for these actions - https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/?created__day=7&created__month=5&created__year=2019&p=0&user=10641840

Maybe I'm misinterpreting the formula -  _3/minute and 20/hour per user, 6/minutes and 50/hour per ip_ - 
Considering that the submissions were made by the same user from the same IP I was expecting to be blocked at some point.

**Comment by AlexandraMoga** [comment]
I've given it another try on stage, after seeing that the API part - #11287 - was giving promising results.

Attempting unlisted submissions in devhub:

Rule/minute
- same user, same IP  - 3 successful submissions, 4th submission blocked
- Same user, different IPs -  3 successful submissions, 4th submission blocked
- Different users (I've used 4), same IP - 6 successful submissions, 7th submission blocked

Rule/hour
 - same user, same IP - 20 successful submissions, 21st submission blocked

@diox the rate-limiting rules seem to be working in devhub.  There could be, of course, more scenarios run to cover all the variables, but I believe that doing this manually from devhub is too costly.
