### ISSUE TITLE
Delete negative ratings caused by Armagadd-on 2.0

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11348]
Let's delete all reviews and ratings under 4 stars, starting with ID: 1327807. [We're still getting lots of them](https://sql.telemetry.mozilla.org/queries/62630/source), so we still have to wait abit to figure out where to finish.

/cc @atsay

**Comment by atsay** [comment]
Between what time frame, May 3 6pm Pacific and now?

**Comment by jvillalobos** [comment]
The first one I identified was created on `2019-05-03 22:13`, not sure if that's UTC or something else. The end of the timeframe is TBD, since we're still getting lots of them.

**Comment by jvillalobos** [comment]
I think the feedback on the incident started to die off on ID: 1343394, timestamped on `2019-05-07 06:48`.

I suggest we delete all reviews and ratings under 4 stars between IDs 1327807 and 1343394 (inclusive).

**Comment by luckyrat** [comment]
For my add-on there were two more slightly outside this range: `1343436` and `1346575`. Appreciate it gets difficult to discern as more time goes by but in my case the last 1 star rating with no review text (they are typically requests for support) was in November 2017 so it does seem very likely that these recent ratings are a result of Armagadd-on.

Perhaps ratings and reviews should be given different cut off IDs? At least with the textual reviews there is an opportunity for devs to flag the review for closer inspection if a few of the more recent ones slip through the net.

**Comment by diox** [comment]
@jvillalobos do we want to add a new log activity for this, showing developers that the ratings have been deleted by us ? Or just delete the ratings silently ? Also, do we want to soft-delete as normal or hard-delete them (meaning no going back) ?

**Comment by jvillalobos** [comment]
I prefer logging and soft-deletion.

**Comment by diox** [comment]
I added a command that we'll need to run manually. It will soft-delete any ratings with a score of less than 4 posted between 2019-05-03 22:13 and 2019-05-07 06:48 UTC.

QA:
- Please create a few ratings that the command should delete/keep, and we'll alter the creation dates to test the command on dev with those.

**Comment by AlexandraMoga** [comment]
@diox here is a list you can use. Let me know if you need other info


Rating ID | Action | Add-on ID
-- | -- | --
564338 | DEL | 495971: Camand
564337 | KEEP | 495686: notification from nobody11
564336 | DEL | 497849: description add-on x4
564335 | DEL | 502718: Stylus Blue
564334 | DEL | 4578: Brief
564333 | KEEP | 261472: Ecosia - The search engine that plants trees!
564332 | KEEP | 6081: Verificador Ortográfico para Português do Brasil
564331 | DEL | 385621: DuckDuckGo Plus
564330 | DEL | 3366: British English Dictionary
564329 | DEL | 3386: Hungarian Dictionary
564328 | DEL | 7560: Webmail Ad Blocker
564327 | DEL | 496392: Aspergers Color Dance
564326 | KEEP | 287841: Awesome Screenshot Plus - Capture, Annotate & More
564325 | DEL | 496046: Eco theme
564324 | DEL | 502857: Space stars
564323 | KEEP | 491738: HYFY Screen Recorder
564322 | DEL | 325576: anonymoX
564321 | DEL | 494655: VersionTest
564320 | KEEP | 358616: DoNotTrackMe: Online Privacy Protection

**Comment by diox** [comment]
@AlexandraMoga creation date for those ratings have been altered, and I ran the script.

**Comment by AlexandraMoga** [comment]
@diox for the given ratings,  the command deleted everything with a score lower than 4:


Rating ID | Score | Deleted | Date
-- | -- | -- | --
564338 | ☆☆☆★★ | TRUE | May 3, 2019, 10:15 p.m.
564337 | ☆☆★★★ | TRUE | May 3, 2019, 10:15 p.m.
564336 | ★★★★★ | FALSE | May 3, 2019, 10:15 p.m.
564335 | ☆☆☆★★ | TRUE | May 3, 2019, 10:15 p.m.
564334 | ☆☆★★★ | TRUE | May 3, 2019, 10:15 p.m.
564333 | ☆☆☆★★ | TRUE | May 3, 2019, 10:15 p.m.
564332 | ☆☆☆☆★ | TRUE | May 3, 2019, 10:15 p.m.
564331 | ☆☆☆★★ | TRUE | May 3, 2019, 10:15 p.m.
564330 | ☆☆☆☆★ | TRUE | May 3, 2019, 10:15 p.m.
564329 | ☆☆☆★★ | TRUE | May 3, 2019, 10:15 p.m.
564328 | ☆★★★★ | FALSE | May 3, 2019, 10:15 p.m.
564327 | ☆☆☆☆★ | TRUE | May 3, 2019, 10:15 p.m.
564326 | ☆☆☆★★ | TRUE | May 3, 2019, 10:15 p.m.
564325 | ☆★★★★ | FALSE | May 3, 2019, 10:15 p.m.
564324 | ☆★★★★ | FALSE | May 3, 2019, 10:15 p.m.
564323 | ☆☆☆☆★ | TRUE | May 3, 2019, 10:15 p.m.
564322 | ☆☆☆★★ | TRUE | May 3, 2019, 10:15 p.m.
564321 | ☆☆☆☆★ | TRUE | May 3, 2019, 10:15 p.m.
564320 | ★★★★★ | FALSE | May 3, 2019, 10:15 p.m.

For deleted reviews, there is also a record of this action in the Recent activity log in Dev Hub.

**Comment by diox** [comment]
Perfect. Let me know if you want to test stage as well.

**Comment by AlexandraMoga** [comment]
@diox let's double check with stage too. Here are the ratings you can use:

716262
716261
716260
716259
716258
716257
716256
716255
716254
716253
716252

**Comment by diox** [comment]
done.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage as well:

Rating ID | Score | Deleted | Date
-- | -- | -- | --
716262 | ☆☆☆☆★ | TRUE | Mai 3, 2019, 10:13 nachm.
716261 | ☆★★★★ | FALSE | Mai 3, 2019, 10:14 nachm.
716260 | ☆☆★★★ | TRUE | Mai 3, 2019, 10:15 nachm.
716259 | ★★★★★ | FALSE | Mai 3, 2019, 10:16 nachm.
716258 | ☆☆☆☆★ | TRUE | Mai 3, 2019, 10:17 nachm.
716257 | ☆★★★★ | FALSE | Mai 3, 2019, 10:18 nachm.
716256 | ☆☆★★★ | TRUE | Mai 3, 2019, 10:19 nachm.
716255 | ☆☆☆★★ | TRUE | Mai 3, 2019, 10:20 nachm.
716254 | ★★★★★ | FALSE | Mai 3, 2019, 10:21 nachm.
716253 | ☆☆☆★★ | TRUE | Mai 3, 2019, 10:22 nachm.
716252 | ☆★★★★ | FALSE | Mai 3, 2019, 10:23 nachm.

**Comment by diox** [comment]
We ran the command today successfully.
