### ISSUE TITLE
Consider not returning wait period when rate limiting

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11347]
We return the wait period in seconds when we are rate limiting an API request. Is there a good reason to do that ? Are the throttling messages still displayed somewhere, for instance for abuse reporting or ratings ?

**Comment by willdurand** [comment]
IRC log: https://mozilla.logbot.info/amo/20190506#c16285119-c16285326

**Comment by eviljeff** [comment]
Do we think anyone misusing the API is using this information anyway, or are they just hammering away until the API accepts their request?

**Comment by diox** [comment]
They are likely just hammering. https://github.com/mozilla/addons-server/issues/11393 would help against that.
