### ISSUE TITLE
Add ability to filter ratings by score in the ratings admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11354]
The ratings admin needs the ability to filter ratings by score. This means adding an index to a table that has a 1M rows though...

This can help https://github.com/mozilla/addons-server/issues/11348

**Comment by diox** [comment]
Note: haven't added an index yet. Performance should be bad, but depending on how many times we need to do this an index might not make sense.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx66, Win10x64

The Ratings admin tools offers the ability to filter ratings by score:

https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/?deleted__exact=0&rating__exact=3&type=rating
![image](https://user-images.githubusercontent.com/31961530/57755394-8877d600-76f9-11e9-915f-7c9ddae87c66.png)

@diox just for my curiosity, how can a user rating (_not dev reply_) end up with a score of `0` or `null` ? I did figure out that most of the addons that fall within this category are actually legacy addons which we disabled a while ago, so we should probably just ignore them.

**Comment by diox** [comment]
It shouldn't be possible currently, but I didn't want to go through all the history to check if that's always been the case :)
