### ISSUE TITLE
Theme images section is empty in the abuse reports page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11365]
Followup for https://github.com/mozilla/addons-server/issues/11137

STR:
1. User needs an admin account - load an abuse report page for a static theme
2. Observe the Theme images section

Expected:
A preview of the theme is available.

Actual result:
No image.

Notes:
This issue is reproducible on AMO dev - FF66(Win10). 

![empty](https://user-images.githubusercontent.com/33448286/57358695-a768ec00-717e-11e9-82ef-fef6f61155ba.png)

**Comment by eviljeff** [comment]
the template context is missing `version`

**Comment by diox** [comment]
Coming back to this. I think we want to display the `current_version` - the most likely scenario for abuse reports against themes is not going to be themes installed in Firefox anyway, but rather themes listed on AMO and someone noticing them while browsing AMO.

**Comment by ioanarusiczki** [comment]
@diox I checked on some pages on dev such as 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/space-stars
https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/underwater-search?page=1
or
https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/sunset-over-water
I think the content has doubled and I still don't see the theme preview displayed. 
I see Abuse Reports(7) then Theme Images which is empty then again an Abuse Report section (looks to me like it's twice the same content). 

![layout problems](https://user-images.githubusercontent.com/33448286/64540624-2aff3900-d329-11e9-8c3a-2515f5d27fc4.gif)

I'm going to reopen.

**Comment by diox** [comment]
Ah, I fixed the images in the abuse report *admin* tool, not the reviewers one. Still, I'll do it there as well. The doubling is tracked in https://github.com/mozilla/addons-server/issues/11775 but I might tackle that as the same time.

**Comment by ioanarusiczki** [comment]
@diox Looks good to me - verified on AMO dev - FF69(Win10). 
Also, the doubling is fixed too. 

![images for themes](https://user-images.githubusercontent.com/33448286/64857609-afa1ce00-d62d-11e9-8e75-002e9e5bd411.gif)
