### ISSUE TITLE
Bulk-banning users

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11360]
We have a way of bulk-banning users by passing a number of IDs to `admin/models/users/userprofile/?q=`. However, that query is utterly slow and the page load times out as soon as you pass more than a handful of user IDs.

Could we improve performance of that look-up query or create a simple new page with a text-area that allows pasting user IDs (one per line) with a single "Ban all users" button?

Or something else? Whatever we do, it should be able to handle hundreds of users being banned at once.

**Comment by diox** [comment]
One challenge: if we want to disable addons from these users as part of the ban, then that can take up a lot of time... Disabling the add-on doesn't matter if the add-ons are unlisted and it's the only author, so maybe we can skip that.

**Comment by jvillalobos** [comment]
Is it a problem that it takes a long time? As long as the tool tells you that it kicked off the process, that should be good enough. It'd be good to disable the extensions so it's clear to anyone inspecting the add-ons that they were taken care of.

**Comment by jvillalobos** [comment]
This appears to be the fastest way we can react to mass add-on spammers, so I'd like to have it done soon.

**Comment by EnTeQuAk** [comment]
> One challenge: if we want to disable addons from these users as part of the ban, then that can take up a lot of time... Disabling the add-on doesn't matter if the add-ons are unlisted and it's the only author, so maybe we can skip that.

Unfortunately, we don't really have a "banned" status so we can't expose that in the changelist, if we had we could move the ban-action to a celery task and allow the user to see changes as they reload their changelist.

Maybe that's not such a bad idea to have an actual `banned` field additionally that saves the date and time of when the user got banned?

**Comment by wagnerand** [comment]
Note on performance: With the current banning algorithm, it easily takes 30s for one user with about 200 add-ons to ban.

**Comment by ioanarusiczki** [comment]
@eviljeff @diox 
I tried a couple of tests on dev and stage testing environments with FF66(Win10) and here are my results:
- the bulk banning works faster than an individual one which I've noticed it takes 10 seconds even up to 16 seconds.

Banning 24 users (most of them without submitted addons) - took ~ 3 seconds 

![24users banned](https://user-images.githubusercontent.com/33448286/57785534-9ac63400-773a-11e9-83e6-5b535d94c29a.gif)

Banning one user (with no submitted addons) - somewhere between 10 to 16 seconds 
![one user banned ](https://user-images.githubusercontent.com/33448286/57785985-6141f880-773b-11e9-863a-dae5f36dca83.gif)

- when banning a user with 185 submitted addons it took longer indeed. I could say somewhere around 25 seconds
![user with 185 addons part3](https://user-images.githubusercontent.com/33448286/57786318-ed542000-773b-11e9-87b3-bd090b7e12de.gif)

- a user which was banned can be searched or found again in the list `admin/models/users/userprofile` and the action can be repeated again, there is no indication that it's been previously banned. It's like going in circles with this process, so perhaps there should be a `banned` field or `deleted` to change into `Banned`. 

@wagnerand Please let us know if it's been an improvement with these changes.

**Comment by wagnerand** [comment]
That sounds great to me!

> a user which was banned can be searched or found again in the list admin/models/users/userprofile and the action can be repeated again, there is no indication that it's been previously banned. It's like going in circles with this process, so perhaps there should be a banned field or deleted to change into Banned.

That's not an issue at the moment. If a user is already banned, banning them again does no harm. Also, I am not sure there is another path on how a user can get deleted, besides banning them (well, other than a super admin manually deleting an account, which we never do).

Longterm, having a banned state (with a date) might make sense.

**Comment by eviljeff** [comment]
Re: the difference between banning one user and many - it's a little weird.  I didn't replace the per-user ban function (the one you'd get if you clicked the button on the detail page for a userprofile) in case the bulk one didn't work well, and it's possible django admin is routing a single id to that function instead.

If @wagnerand is happy with how the bulk function works I can replace the single user ban function too (i.e. it'd just call the bulk function with one id).

**Comment by ioanarusiczki** [comment]
@eviljeff @wagnerand 
Indeed, per-user ban works super fast, I can confirm that while testing on django admin stage env.
I filed https://github.com/mozilla/addons-server/issues/11458 as a followup.
