### ISSUE TITLE
Change the API docs experimental designation of the v4 api from "experimental"

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11361]
follow-on from comments on https://github.com/mozilla/addons-server/pull/11331

https://github.com/mozilla/addons-server/pull/11331/files/d9f7bc95d8ddeb05173dda9716606b284fe58b69#diff-ded59140eb15464d132e0a27e117219b

> @EnTeQuAk
That title is… interesting, I can't really decipher what this means to me tbh. We only have one "experimental" API now, which is V5 after merging this right?

> @eviljeff
We call the v4 experimental all over the place and I wasn't sure how we wanted to brand the v4 API at this point.

> @EnTeQuAk
V5 -> Experimental
V4 -> Default, Stable
V3 -> Deprecated
Maybe?

> @eviljeff
That's ideally where we'd be, yeah, but whether v4 is completely stable when we're changing things to support addons-frontend changes, and whether v3 can be deprecated while release Firefox is on it are open questions. #11273 has all steps.

**Comment by eviljeff** [comment]
(Also make the other docs fixes in the pr comments)

**Comment by ioanarusiczki** [comment]
@eviljeff I believe the API documentation [here ](https://addons-server.readthedocs.io/en/latest/topics/api/overview.html) was updates with information about v5 being experimental. 
Is qa needed for this ? If not, please add qa "not needed".
