### ISSUE TITLE
Edit a draft comment by ID

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11379]
After posting a comment on a specific line (https://github.com/mozilla/addons-server/issues/11378), the code manager needs a way to edit that comment by ID. I don't see a way to do that when looking at the existing [PATCH](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#patch--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-) endpoint.

**Comment by AlexandraMoga** [comment]
Verified on -dev with the [PATCH draft_comments](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#patch--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-(int-comment_id)) endpoint

- original comment:
```
{
    "id": 39,
    "filename": null,
    "lineno": null,
    "comment": "This is the original comment",
```
- patched comment:
```
{
    "id": 39,
    "filename": "manifest.json",
    "lineno": 61,
    "comment": "This is the PATCHED comment",
```
