### ISSUE TITLE
Expose draft comment data to code manager

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11374]
### Describe the problem and steps to reproduce it:

An imaginary UI flow for commenting might look like this:

- As a reviewer, click the line of a diff to enter a comment
- Type a comment, press save
- Refresh the browser page

### What happened?

n/a

### What did you expect to happen?

The UI should show the saved draft comment on the line of the diff.

### Anything else we should know?

The current [GET response](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#drafting-comments) does not return enough data to do this. We would need something like

- an array of all comments with...
  - file path
  - line number (either a normal, deleted, or added line number)
  - canned response ID (when applicable)

**Comment by AlexandraMoga** [comment]
I've verified the [GET draft_comments](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-) and [GET draft_comments by Id](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-(int-comment_id)-) endpoints on -dev and they seem too be working.

From what I observed, the comments posted for an add-on version are private, meaning that when you send a GET request, you will receive only the list of comments posted by you for that add-on version.
To put it simple, other reviewers wont be able to see the draft comments posted by your user. 

@EnTeQuAk @kumar303 is this how you expect this to work? I'm not sure if there is a scenario in which a reviewer will need to share his draft comments with another reviewer.

**Comment by EnTeQuAk** [comment]
This is how it's expected to work for now. It may potentially be opened up later on, to other reviewers and other add-on authors but last time we talked about that we wanted reviewers only to see their own comments. Especially since the primary communication tool will be the regular reviewer-tools "comment" section there.
