### ISSUE TITLE
Blank search no longer shows the admin flagged addons

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1137]
Moved from https://github.com/mozilla/amo-validator/issues/369, cc @erosman.

I have noticed (for a while) that using the search button with blank query on the queue page no longer shows the admin flagged addons.

It seems that the problems is with `searching=` parameter

For example ..... 
Shows admin flagged:
`https://addons.mozilla.org/en-US/editors/queue/nominated?searching=True&text_query=&admin_review=1&application_id=&max_version=&waiting_time_days=#review-actions`

Doesn't show admin flagged:
`https://addons.mozilla.org/en-US/editors/queue/nominated?searching=&text_query=&admin_review=&application_id=&max_version=&waiting_time_days=`

Changing the `searching=&` to `searching=true&` fixes it.

**Comment by mstriemer** [comment]
I can't reproduce this on dev or production. When I click the search button I see `searching=True` in the URL. It is [checking that it has a value set](https://github.com/mozilla/olympia/blob/d26f257d5c70c1ec745ca19047c2e1e9ee95d488/apps/editors/views.py#L404) but I don't know why it wouldn't be setting the value for you.

**Comment by erosman** [comment]
I am not an admin reviewer.

Looking at the source of the page .....

View source shows:
`<input id="id_searching" name="searching" type="hidden" value="True" />`
So far so good.

Web Developer View Generated Source shows:
`<input id="id_searching" name="searching" type="hidden" />`

Inspector shows:
`<input id="id_searching" name="searching" type="hidden">`

I have tried it with GreaseMonkey disabled (I have scripts running) and even ADB disabled.
There could be a JS on the page that removes `value="True"`, but I didnt find it.

**Comment by spoji** [comment]
I confirm that I can reproduce what erosman said.

**Comment by palant** [comment]
I can confirm as well, that text field has no value on the second page - but it does on the first.

**Comment by mstriemer** [comment]
Good catch. Works for me on initial navigation but if I go to a different page it doesn't work.

**Comment by mstriemer** [comment]
Assigning to kumar since he wrote this 4 years ago.

**Comment by kumar303** [comment]
![aziz-ansari](https://cloud.githubusercontent.com/assets/55398/11963783/c7aab634-a8ae-11e5-9d26-58775e8d02a5.gif)

**Comment by erosman** [comment]
Additional Info:

In fact the `value="True"` is missing from any page with search query string, even the first page.

    https://addons.mozilla.org/en-US/editors/queue/nominated    
    
    <input id="id_searching" name="searching" type="hidden" value="True" />
    
    https://addons.mozilla.org/en-US/editors/queue/nominated?page=1    
    https://addons.mozilla.org/en-US/editors/queue/nominated?page=2    
    
    <input id="id_searching" name="searching" type="hidden" />
