### ISSUE TITLE
Normalize SVG mimetypes to image/svg+xml

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11382]
Server-side issue of https://github.com/mozilla/addons-code-manager/issues/719

**Comment by AlexandraMoga** [comment]
The following add-on used to have some images with a `image/svg` mimetype. Now, the returned mymetype for those specific files is `image/svg+xml`:



https://addons-dev.allizom.org/api/v5/reviewers/addon/616837/versions/1688169/
![image](https://user-images.githubusercontent.com/31961530/57621463-2a7dae00-7594-11e9-8fb6-7e7b26e9112f.png)
