### ISSUE TITLE
Delete a draft comment by ID

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11380]
After posting a comment on a specific line (https://github.com/mozilla/addons-server/issues/11378), the code manager needs a way to delete that comment by ID. I don't see a way to do that when looking at the existing [DELETE](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#delete--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-) endpoint.

**Comment by AlexandraMoga** [comment]
I've verified the [DELETE draft_comments] endpoint on -dev and to me it looks to be working as expected.
 - a successful delete request returns 204
 - if the requested `comment id` doesn't exist, the api returns 404
 - if you are trying to delete a comment which wasn't created by your current authenticated user, the api responds with a 404
