### ISSUE TITLE
Alias `image/x-ms-bmp` mimetype to `image/bmp`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11383]
See also: https://github.com/mozilla/addons-code-manager/issues/718

---

We want to alias the `image/x-ms-bmp` mimetype to `image/bmp` so that code-manager does not maintain a huge list of supported mimetypes with all the weird existing mimetypes.

**Comment by AlexandraMoga** [comment]
The following add-on used to have some images with a `image/x-ms-bmp` mimetype. Now, the returned mymetype for those specific files is `image/bmp`:

https://addons-dev.allizom.org/api/v5/reviewers/addon/616837/versions/1688169/

![image](https://user-images.githubusercontent.com/31961530/57621287-b80cce00-7593-11e9-879f-c90236caa203.png)
