### ISSUE TITLE
Make our throttling classes increment action count even on failures

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11393]
With DRF throttling classes, [an action gets added to the history only on success](https://github.com/encode/django-rest-framework/blob/9811a29a5a1348f1a5de30a9a7a5d0f8d2fd4843/rest_framework/throttling.py#L130-L141). This means that additional attempts that result in a 429 response aren't considered in rate limiting checks later. 

Furthermore, DRF's behavior is also to [return the 429 for the first throttling class that fails](https://github.com/encode/django-rest-framework/blob/9811a29a5a1348f1a5de30a9a7a5d0f8d2fd4843/rest_framework/views.py#L353-L355), preventing the other throttling classes from acting on the current attempt if one results in throttling.

We should consider changing both these things and try to get that upstream as well (it's a backwards-incompatible change in a way, but I think it makes sense). See also https://github.com/mozilla/addons-server/issues/11347

**Comment by eviljeff** [comment]
> This means that additional attempts that result in a 429 response aren't considered in rate limiting checks later.

Isn't that by design though? - if you try on 19:59 of a 20 minute throttle you have to wait another 20 minutes? I could imagine that being very annoying. Especially when you don't find out there is a throttle until you hit it the first time.

> Furthermore, DRF's behavior is also to return the 429 for the first throttling class that fails, preventing the other throttling classes from acting on the current attempt if one results in throttling.

We could write something similar to the any permission class for throttles. Wouldn't this reduce the effectiveness of the throttles though? Rather than being restricted by the most restrictive throttle you'd be restricted by the least.

**Comment by diox** [comment]
>> This means that additional attempts that result in a 429 response aren't considered in rate limiting checks later.
> Isn't that by design though? - if you try on 19:59 of a 20 minute throttle you have to wait another 20 minutes? I could imagine that being very annoying. Especially when you don't find out there is a throttle until you hit it the first time.

I guess it could be annoying for low throttles yeah. But I don't think you would have to wait that long: it would just force you to wait until the first actions made in that 20 minutes window expire, which could be just a couple seconds later.

>> Furthermore, DRF's behavior is also to return the 429 for the first throttling class that fails, preventing the other throttling classes from acting on the current attempt if one results in throttling.

> We could write something similar to the any permission class for throttles. Wouldn't this reduce the effectiveness of the throttles though? Rather than being restricted by the most restrictive throttle you'd be restricted by the least.

I don't see how it would reduce effectiveness, it's meant to improve it :)

My problem here is that if you have a limit per minute and a limit per hour in that order, with the current implementation when you hit the limit per minute your attempt is never counted in the history of the limit per hour. So if you let that minute limit expire, you essentially got one extra action on the limit per hour.

**Comment by eviljeff** [comment]
> it would just force you to wait until the first actions made in that 20 minutes window expire,

Can you detail the scenario v.s. now? If the time is still based on the original action that wasn't throttled I don't see what you're suggesting be changed.

> My problem here is that if you have a limit per minute and a limit per hour in that order, with the current implementation when you hit the limit per minute your attempt is never counted in the history of the limit per hour. 

We count all successful attempts though, so how do you get an extra one? (Or do we? I thought the throttling was effectively an `and` and all throttles needed to pass)

**Comment by diox** [comment]
> Can you detail the scenario v.s. now? If the time is still based on the original action that wasn't throttled I don't see what you're suggesting be changed.

There are a lot of possible scenarios, but consider this one, using a throttle of 3 actions per 60 seconds. Each row is a request:

| Seconds | Current behavior | Proposed behavior  |
| --------| ---------------- | ------------------ |
| 0       | Pass (0)         | Pass (0)           |
| 5       | Pass (1)         | Pass (1)           |
| 10      | Pass (2)         | Pass (2)           |
| 15      | Throttled (3)    | Throttled (3)      |
| 62      | Pass (2)         | Throttled (3)      |
| 66      | Pass (2)         | Throttled (3)      |
| 76      | Pass (2)         | Pass (2)           |

The number in parenthesis is the number of requests that count towards rate limiting in the rate limit window before the request for that row is examined (DRF removes from the history any requests made from before the rate limit window before deciding to throttle).

> We count all successful attempts though, so how do you get an extra one? (Or do we? I thought the throttling was effectively an and and all throttles needed to pass)

It works in the opposite way of what you think and that's why I want to change it. The code that I linked above:
```python
        for throttle in self.get_throttles():
            if not throttle.allow_request(request, self):
                self.throttled(request, throttle.wait())
```

`self.throttled()` raises an exception that returns the 429 response. So, DRF loops over each throttle class instance and the first time it encounters a throttle that disallows the request, the 429 is returned, ignoring the other throttle classes, and therefore not adding the action to their history (which isn't shared between throttle classes).

**Comment by eviljeff** [comment]
Ah, I wasn't considering multiple requests per time period.

**Comment by diox** [comment]
https://github.com/encode/django-rest-framework/issues/6666 for the first part.

**Comment by diox** [comment]
Submitted a pull request for that in DRF: https://github.com/encode/django-rest-framework/pull/6669

**Comment by diox** [comment]
This has been rejected upstream and there is no interest to pursue this on our side anymore at the moment.
