### ISSUE TITLE
Don't return an array for `diff` in Compare API response

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#11392]
The [response to the Compare endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#compare) returns a single diff, in a property called `diff`, but that actually contains an array, which only ever contains a single diff. So let's change it to just return the diff object in the `diff` property, rather than an array with a single diff.

**Comment by ioanarusiczki** [comment]
@willdurand I think this is as expected now - I checked on dev and stage.
The `diff` property in the JSON response begins and ends with `{` (as an object) instead the way it used to be, with `[` (as an array). 

Here's an example
![diff partone-array](https://user-images.githubusercontent.com/33448286/57770590-54141200-7719-11e9-93d3-9c750f7aaf68.png)

![dif ends with no square brakets](https://user-images.githubusercontent.com/33448286/57770599-59715c80-7719-11e9-8ba9-64a980939c2f.png)
