### ISSUE TITLE
Cannot access non-public extensions via API, even with permissions

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#11407]
### Describe the problem and steps to reproduce it:
I tried to use the `filter` parameter to see non-public extensions. For example:

```
curl -v https://addons.mozilla.org/api/v4/addons/addon/crxviewer-firefox@robwu.nl/versions/?filter=all_without_unlisted -H 'Authorization: JWT xxx'
```

The example has listed versions only, but because permissions are checked first, this bug can be reproduced anyway.
For the test case, it is not necessary to input a valid JWT value, but if you want to see a successful result, replace `xxx` with a valid token, following the instructions at https://addons-server.readthedocs.io/en/latest/topics/api/auth.html

### What happened?
```
< HTTP/1.1 401 Unauthorized

{"detail":"Authentication credentials were not provided."}
```

### What did you expect to happen?
With a dummy `xxx` JWT:
```
< HTTP/1.1 401 Unauthorized

{"detail":"Error decoding signature."}
```

With a valid JWT:
```
< 200 OK

{"page_size":25,"page_count":1,"count":17,"next":null,"previous":null,"results":[ ... ]}
```

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
That's not currently open to external (JWT) auth, yes (it's mentioned at the top of https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#versions-list, arguably that's not enough)
