### ISSUE TITLE
'Mozilla Public License' renamed as 'None' in the submission details form

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11406]
**STR**

1. Submit a new listed extension in dev hub
2. Once the add-on passes validation, click on Continue to reach the submission details form
3. Scroll down to the license selection section

**Actual result:**
The first license option is 'None'

**Expected result:**
The first license option should be 'Mozilla Public License'  

**Notes:** 
- the same issue can be noted on the Manage authors and license page
- the Details link still points to the correct license info
- on the frontend, the license name is 'Custom License'
- reproduced on -dev with Fx66, Win10x64

Example: https://addons-dev.allizom.org/en-US/firefox/addon/dark-theme-for-google-news/

[1] - submission form
![image](https://user-images.githubusercontent.com/31961530/57623379-4edb8980-7598-11e9-87e9-3dbcd712d5ae.png)

[2] - Authors and license page
![image](https://user-images.githubusercontent.com/31961530/57623434-6b77c180-7598-11e9-9b08-88f902cbe168.png)

[3] - Stage (expected result)
![image](https://user-images.githubusercontent.com/31961530/57623494-89ddbd00-7598-11e9-866f-06c1bf9206eb.png)

**Comment by EnTeQuAk** [comment]
Is that happening on prod too?

**Comment by AlexandraMoga** [comment]
@EnTeQuAk no, it is only -dev.

**Comment by AlexandraMoga** [comment]
The issue can be reproduced in stage too, after the tag.

**Comment by EnTeQuAk** [comment]
> The issue can can't be reproduced in stage, after the tag so I think we are safe for now.

Perfect, thanks for verifying! I'll mark this as p4 for now till someone has time to investigate what's wrong with our -dev data.
