### ISSUE TITLE
The search after "featured add-ons only" filter will continue to display results but instead they'll be the recommended ones

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11419]
As a followup for https://github.com/mozilla/addons-frontend/issues/7794

STR:
1. Make a blank search then filter results by "Featured add-ons only" and Addon type "Extension".

Actual results:
Featured extensions are actually the new recommended extensions. 

Expected results:
Perhaps a separate filter for "recommended extensions" should be available. 

Notes:
This issue is reproducible on AMO dev - FF66(Win10). 

![search for featured](https://user-images.githubusercontent.com/33448286/57694953-b4da1680-7655-11e9-8829-f3b18b371f03.gif)

**Comment by eviljeff** [comment]
The recommendations feature from an API/backend perspective is far from done so its premature to make assumptions about what's expected at this point. I'm just going to close this.
