### ISSUE TITLE
Don't raise an exception if there isn't a `current_version` in `is_recommended()`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11410]
### Describe the problem and steps to reproduce it:
An add-on with no `current_version` (either purely unlisted or listed with all its versions deleted) that we're trying to determine the recommendation status of can cause us to raise an exception.

### Steps to reproduce
- Create a purely unlisted add-on, make it recommendable by adding a discovery item for it through the admin w/ the property checked.
- Also try with a purely listed add-on for which all versions are deleted after it has been approved & set as recommendable in discovery admin
- Try to index it, or try to call the detail API for that add-on w/ the right permissions 

### What did you expect to happen?
- It should work. Notably, once indexed the add-on should no longer show up in searches if it was listed before.

**Comment by AlexandraMoga** [comment]
For the first test:
>Create a purely unlisted add-on, make it recommendable by adding a discovery item for it through the admin w/ the property checked.

I wasn't able to add a purely unslisted add-on to the recommeded list through Discovery admin, so I used this workaround: have an add-on with both listed and unlisted versions -> add it to the recommended list using te available admin tools -> delete all the listed versions which will make the add-on a purely unlisted one.
Then, I've called the detail api for the respective add-on:
https://addons-dev.allizom.org/api/v4/addons/addon/616627/ => there are no errors triggered
 - `current_version` is `null`
- `is_recommended` is `null`

For the second test:
Created a listed add-on -> set it as recommended through discovery admin -> deleted all versions
Called the detail api for the respective add-on:
https://addons-dev.allizom.org/api/v4/addons/addon/616550/ => there are no errors triggered
 - `current_version` is `null`
- `is_recommended` is `null`

As a note, I haven't reproduced the issue when I repeated the tests on stage, so I'm guessing you have noticed this exception in your logs?
