### ISSUE TITLE
A recommended extension should appear in Featured/Recommended extensions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11417]
Followup for https://github.com/mozilla/addons-frontend/issues/7794

STR:
1. Using admin tools - make an addon recommendable. It has to be changed from admin tools - the version page of an addon `en-US/admin/models/versions/version/1655545/change/` needs the `Recommendation approved` flag and then it needs to be added in the Discovery items as `Recommendable` `en-US/admin/models/discovery/discoveryitem/`
I added this[ addon](https://addons-dev.allizom.org/en-US/firefox/addon/%E4%BA%AC%E4%BB%B7%E4%BF%9D-%E4%BA%AC%E4%B8%9C%E4%BB%B7%E4%BF%9D%E5%8A%A9%E6%89%8B/)
2. Go to AMO homepage and search the addon int the "featured extension" shelf (the future recommended shelf https://github.com/mozilla/addons-frontend/issues/8018) 

Expected result:
The addon is part of [ See more featured extensions](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension)

Actual result:
The recommended addon is not displayed in [ See more featured extensions](https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension)

Notes:
Reproducible on AMO dev with FF66(Win10).

**Comment by eviljeff** [comment]
These changes haven't been made yet - I'm going to dupe to #11067 because that's the main issue around adjusting what's shown in the shelves.
