### ISSUE TITLE
Error on upload in case reserved files get uploaded

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11425]
To implement recommendations, we will end up adding a list of reserved files which we'll have to search through the XPI and throw errors.

We already do a similar operation when we're looking for api-keys in files inside the add-on so we might be able to repurpose that one to avoid listing all files more than necessary.

We will need a linting rule in addons-linter too but doing so in addons-server allows us to react faster to changes regarding file-names or other implementation details.

**Comment by muffinresearch** [comment]
@EnTeQuAk please can we get this into next week's push?

**Comment by EnTeQuAk** [comment]
Fixed via #11530

**Comment by EnTeQuAk** [comment]
QA: The filename mentioned in https://docs.google.com/document/d/1Lcq4qNxAXXFivM93En7z_Dujxu0BzpN84jRgcKRrTaE/edit#heading=h.xyd35qkx4d87 won't be able to be submitted via an upload and result in a linter error.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk when I'm trying to submit an add-on package that contains the mentioned filename on -dev , I receive the following error message:

![image](https://user-images.githubusercontent.com/31961530/58543846-e41d8580-8208-11e9-84b4-acf69fe183f0.png)

Is this expected or should we show a more specific message?

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/219578 - looks like rabbitmq is having issues. I'll double check with ops.

**Comment by EnTeQuAk** [comment]
It's actually a bug in the linter, I'll have a fix ready in a moment.

**Comment by AlexandraMoga** [comment]
I've reverified this on -dev and stage and now we are throwing a more relevant error message if the mentioned filename is present:

https://addons-dev.allizom.org/en-US/developers/upload/918dc755db904549951905e4a1deb45a
![image](https://user-images.githubusercontent.com/31961530/58626995-cb7f9f00-82de-11e9-9dbb-930ac2d9b2fa.png)

The submisison fails aslo if the upload is made through the api

**Question**: are we only looking in the root folder for reserved filenames? If my file is included in a subfolder, the validation passes.

**Comment by EnTeQuAk** [comment]
> Question: are we only looking in the root folder for reserved filenames? If my file is included in a subfolder, the validation passes.

We are actually looking at all folders so that's a bug and in practice I have a test that tests this but I'll open an issue on the addons-linter to verify and fix if needed.

Can you share the used XPI file?

**Comment by AlexandraMoga** [comment]
There was a follow up filed on addons-linter, to fix the subfolder issue - see https://github.com/mozilla/addons-linter/issues/2618

This can be marked as verified fixed and further test results will be added in the mentioned issue.
