### ISSUE TITLE
Allow tgz files for upload new version

### ISSUE THREAD

**Issue by regseb** [mozilla/addons-server#11433]
### Describe the problem and steps to reproduce it:

Compress your extension into a _tar.gz_ file and upload it to the page to Submit a New Version. The file is refused because only zip files are allowed (_Your add-on should end with .zip, .xpi, .crx, .jar or .xml_).

### What happened?

> ✖ Your add-on failed validation with 1 error.
> * The filetype you uploaded isn't recognized.

### What did you expect to happen?

The file is allowed as a zip file.

### Anything else we should know?

The _tar.gz_ format is supported natively by Linux and Node.js. It will make it easier to create archives from these environments.

**Comment by eviljeff** [comment]
Addons (extensions, themes, etc) are packaged in zip files, they're just renamed to .xpi.  You have to submit a valid addon package to us.
