### ISSUE TITLE
Put the backend recommendation API changes behind a waffle

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11430]
Some of the things we'll be doing, like changing ranking and only exposing recommended add-ons in certain places, are only going to work when we have all the work done and have all the add-ons we want to recommended already reviewed, so we should put the changes behind a waffle.

**Comment by eviljeff** [comment]
So, major problem with this is the code that applies the ranking boost operates in real time, and we purposely don't do any database queries - we use elasticsearch to avoid it.  One query is maybe okay?

**Comment by diox** [comment]
Waffles are cached, and we have done that in the past... It's not ideal but should be ok - we can monitor performance more closely in datadog to make sure it's not a problem.

**Comment by AlexandraMoga** [comment]
@eviljeff does this require any QA specifically?

**Comment by eviljeff** [comment]
not really - you can toggle the waffle on -dev to see how the relevance boost is enabled or disabled (though I already did that).  #11432 and #11067 will be behind the waffle too.
Probably more something to be aware of for stage - it will need to be (added and) enabled to QA things there.
