### ISSUE TITLE
Search results don't boost recommended addons when searching without a query string

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11432]
[Recommended add-ons]
Follow up for #11066 

**STR:**
1. Open AMO -dev
2. Try to search for add-on without providing a query string- i.e. https://addons-dev.allizom.org/en-US/firefox/search/ or https://addons-dev.allizom.org/en-US/firefox/search/?type=extension
3. Observe the results

**Actual result:**
As per @eviljeff 's comment in https://github.com/mozilla/addons-server/issues/11066#issuecomment-492254041, when no search string is provided , the API defaults to weekly downloads. On -dev, at least, this means that recommended add-ons are not boosted in search results

**Expected result:**
Since we plan to boost recommended extensions in search results, I would expect to see the add-ons from the [curated list](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/) on the first pages of results when no search string was provided. 

**Notes:**
- the [PRD](https://docs.google.com/document/d/1fRxLy7h02tn1HBIlsTU_6h9DHmN8c3N6bg4JoxHF7J8/edit#heading=h.5kvm14zbadi2) doesn't mention an approach for this specific scenario

**Comment by eviljeff** [comment]
@jvillalobos / @atsay what you think?  For the specific case of searching with no search string?  

(And in general, about non-relevance sorting - e.g. weekly downloads, users, etc.)

**Comment by eviljeff** [comment]
I've an idea: we default to `random` sort if `?recommended` and no query string.

**Comment by jvillalobos** [comment]
The PRD mentions "If this flag is selected and there’s no search query, the default sort should be ADI."

**Comment by eviljeff** [comment]
What about when the flag isn't selected like in the urls @AlexandraMoga posted above (sorry for muddying the waters by mentioning the case when `?recommended` _is_ present).

**Comment by jvillalobos** [comment]
Users should be the default sort whenever a search doesn't have a query string and doesn't have a sort. The only exception is when searching specifically for search engines (`/search/?type=search`), which should be sorted by rating (see https://github.com/mozilla/addons-frontend/issues/7682).

**Comment by jvillalobos** [comment]
Just discussed this with @atsay and she had a good point about showing Recommended on top in these cases. So, amending my previous comment:

Default: Recommended first, sorted by users, followed by the rest, sorted by users.
Search engines: Sorted by ratings (we don't plan to recommend those).

Does that make sense, @eviljeff?

**Comment by AlexandraMoga** [comment]
I've verified this on -dev and recommended add-ons are now promoted above other search results when there is no query string provided.

Examples: 
https://addons-dev.allizom.org/api/v4/addons/search/?type=extension - first results will be recommended add-ons sorted by weekly_downloads in a descending order, followed by unrecommended extension also sorted by weekly_downloads. 
 *Note https://addons-dev.allizom.org/api/v4/addons/search/ - recommended add-ons are exposed in the same manner as described above, the only difference here being that they will be followed by persona themes which are still available on -dev. 

@eviljeff the product requested the following schema: 

>Default: Recommended first, sorted by users, followed by the rest, sorted by users.

The API default sort is `weekly_downloads` not `average_daily_users`. Should the API be changed to reflect this specification or should the sorting be applied in the request made by the frontend?

**Comment by eviljeff** [comment]
> The API default sort is weekly_downloads not average_daily_users. Should the API be changed to reflect this specification or should the sorting be applied in the request made by the frontend?

I must have overlooked that change - I'll fix it.  (fwiw, I think frontend always sends the sorting parameter)

**Comment by AlexandraMoga** [comment]
The new default sort is by `average_daily_users`.
This issue is now verified fixed on -dev.
