### ISSUE TITLE
Enable GIT_OPT_ENABLE_FSYNC_GITDIR option on pygit2

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11449]
When extracting all files into the git worktree we are calling fsync() for all files from the zip.

We don't explicitly call fsync() for our own `.git` related files.

I found that there is an option in libgit2 that forces itself to call `fsync()` for a bunch of operations.

```
* You can enable us calling `fsync` for various files inside the ".git"
  directory by setting the `GIT_OPT_ENABLE_FSYNC_GITDIR` option with
  `git_libgit2_opts()`.`
```

This should help ordering writes into EFS

Refs #11431

**Comment by AlexandraMoga** [comment]
Please add STR or a qa:not needed label.
Thanks
