### ISSUE TITLE
Admin tool for blocked IP addresses

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11440]
From the [Account Submission Restrictions PRD](https://docs.google.com/document/d/1FfFcydrcm_TC4sQHXWQfJg2_11RvvYUANDy0hqMlH7U/edit#).

We need an admin tool that lets AMO admins add IP addresses to be blocked. It should be possible to add individual IP addresses. 

If it's easy, it should also be possible to add masks to the addresses (`64.10.*.*`, for example). Otherwise it can be done in a followup.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I found the new IP restriction model in https://addons-internal.dev.mozaws.net/en-US/admin/models/users/ipnetworkuserrestriction/, but before I start testing, are there any preconditions to consider? For example, is the tool limited to certain permissions or are there any other relevant things I should know about?
Thanks

**Comment by AlexandraMoga** [comment]
Verified on stage with Fx67 WIn10x64

The Ip network user restrictions tool is located at https://addons-internal.stage.mozaws.net/en-US/admin/models/users/ipnetworkuserrestriction/ and can be accesses by users with `Admin:Advanced` permissions.
Admins can add, change or delete an IP address from the block list.

When an IP address is added to the list, it is automatically converted to a `/32` network.

Similar to #11442, the search functionality doesn't seem to be working yet, so this will require a follow up.
