### ISSUE TITLE
Admin tool for blocked email addresses

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11442]
From the [Account Submission Restrictions PRD](https://docs.google.com/document/d/1FfFcydrcm_TC4sQHXWQfJg2_11RvvYUANDy0hqMlH7U/edit#).

We need an admin tool that lets AMO admins add email addresses to be blocked. It should be possible to add individual email addresses or entire email domains (`@somethingbad.com`, for instance).

If it's easy, it should also be possible to uses masks (`*@*.somethingbad.com`, for example). Otherwise it can be done in a followup.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk @diox which admin permissions are required to access the Email/IP blocking models?
So far I have tested with a full admin account, but maybe I should also check with more specialized permissions?

**Comment by diox** [comment]
@AlexandraMoga once my fix for https://github.com/mozilla/addons-server/issues/11497 goes through (it's making its way to stage as I write this) it'll require 'Admin:Advanced'.

**Comment by AlexandraMoga** [comment]
@diox users with `Admin:Advanced` can edit an entry from the blocked emails/IPs list, but they cannot deleted or add items. Was this intended?

**Comment by diox** [comment]
Oversight on my part :(

**Comment by diox** [comment]
I'll fix and cherry-pick that as well.
