### ISSUE TITLE
Block add-on submission by email address

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11443]
From the [Account Submission Restrictions PRD](https://docs.google.com/document/d/1FfFcydrcm_TC4sQHXWQfJg2_11RvvYUANDy0hqMlH7U/edit#).

We need to block add-on submissions when they match any of the blocked email addresses in https://github.com/mozilla/addons-server/issues/11442. In the Developer Hub, the emailaddress check should happen on the first step in the flow (so, before the Developer Agreement step), and an error message shown if there's a match:

<img width="596" alt="Screen Shot 2019-05-15 at 2 28 39 PM" src="https://user-images.githubusercontent.com/62568/57807126-c38c0080-771d-11e9-9921-de894e8e0ad1.png">

Let's change the error message from the screenshot to something more general:

> The email address you used for your developer account is not allowed for add-on submission.

The error message should also be returned by the API in case that's the way the add-on is being submitted.

@caitmuenster to provide the destination for the link and to review the copy for the error message and link. None of this is blocking, however, it can ship with the current error message and no link if needed.

**Comment by diox** [comment]
How do we handle users changing their email address ? Does it unblock them ?

On a somewhat related note, I was initially thinking the right place to do this would be on the developer agreement page. Make it impossible for banned emails/ips to validate the agreement. But if their email/ip changes to something we accept, or was initially accepted, the ban wouldn't work, so I think it needs to be set deeper in the code, in the submission itself (which is a lot more annoying to do properly)

**Comment by jvillalobos** [comment]
I mentioned doing it in the first step because I wouldn't want legitimate people to do a bunch of work and then get blocked. If they change their email address, trying to submit again should work. We wouldn't be banning the account, just stopping them from submitting while the email matches something that's blocked.

**Comment by diox** [comment]
It's a lot easier for us to do it on the developer agreement step. I don't think it's going to be much of a problem, even if a legitimate user where to be caught by accident the only work they'd have to do for nothing is solving the recaptcha.

Technical implementation:
- Introduce `UserProfile.can_submit()`, it checks against both email denied list. Maybe not a `UserProfile` method and a helper somewhere instead, that is also passed the ip, or the full request ? Would help https://github.com/mozilla/addons-server/issues/11441.
- In the API, it's simple: add a permission class that calls `can_submit()`. Only difficulty is getting the right error message, we might need to tweak the method returning the error.
- In devhub, replace `has_read_developer_agreement()` checks with `can_submit()`
- In devhub `render_agreement()`, display the message if the user can't submit but   has read the developer agreement.
- In devhub `AgreementForm`, prevent the form from being valid if the user can't
  submit. Make sure they see the message when submitting that form (see previous point)

This should ensure malicious developers are stuck with the message at every step of the submission process.

**Comment by diox** [comment]
Note for QA: current implementation deviates from spec a little bit:
- When a user is restricted (email or ip, same deal) we redirect them to the agreement page
- When they (re-)submit the agreement form, they are presented with the message explaining the block

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67, Win10x64

Here are my results:

* individual email blocking:  
  * existing and new accounts are redirected to the dev agreement page when attempting to submit a new addon of any kind. The same applies to new version submissions. If the agreement is accepted, the following error is generated:
![image](https://user-images.githubusercontent.com/31961530/58159743-d060a500-7c85-11e9-83a6-0eb13e00b624.png)
  * when a blocked account tries to open the Manage  API keys page, we are showing the dev agreement. If the agreement is accepted, the submission error is generated
  * API: upload requests for a new add-on (POST) or a new add-on version(PUT) made with a blocked account will result in a 403 error along with the expected error message

@diox I understand that email domain blocking is not possible yet, correct?

**Comment by EnTeQuAk** [comment]
That's being worked on in #11483 which I'd try to cherry-pick but the PR needs some updating.

**Comment by AlexandraMoga** [comment]
Updating results after testing around domain blocking (I've tested Dev hub and the API in parallel):

* example for full domain blocking
  * I have blocked all incoming submissions from `restmail.net`. To do that, I have used the following patterns: `*restmail.net` or `*@restmail.net` . A `*` was required for both cases to make them work.
* block domains by pattern
  * I have blocked submissions coming from `@*.mailsac.com` while making sure that the parent domain `@mailsac.com` was still accepted. I was able to achieve this with either of the following patterns: `*.mailsac.com` or `*@*.mailsac.com` . The result was:
    * users  `block-me@alt.mailsac.com` and `stay-away@in.mailsac.com` weren't allowed to submit add-ons
    * user `should-work@mailsac.com` was allowed to submit add-ons

@diox  or @EnTeQuAk I I have come to the expected results, but I need to know if the patterns I used are expressed correctly.

**Comment by diox** [comment]
Looks ok yes. `*restmail.net` without the `@` would also block 'foorestmail.net`, that's why when using this tool we'll generally want admins to add 2 blocks:
- One for the domain itself `*@somewhere.com`
- One for the subdomains `*@*.somewhere.com`

Ensuring `foosomewhere.com`, a different domain entirely, isn't blocked.
