### ISSUE TITLE
Add the banned state with a date for user profiles 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11458]
As a followup for https://github.com/mozilla/addons-server/issues/11360
STR:
1. From en-US/admin/models/users/userprofile/ users can be banned.

Expected:
There is a field which indicated the banned state and the date.

Actual:
Only "Is public" and "deleted" states are available. 

Notes:
Reproducible on django admin dev and stage - FF66(win10). 

![Another state](https://user-images.githubusercontent.com/33448286/57862708-797c4b00-7801-11e9-98c1-aac37420348f.png)

**Comment by diox** [comment]
We could easily add the `is_banned` - it's essentially a special case of deletion. Not a priority for now though.

**Comment by eviljeff** [comment]
going to forward dupe this to #11876 because it'll fix it and it's a p2.
