### ISSUE TITLE
Require setting display name for all developers (or all users)

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11453]
We need developers to set a proper display name, so we don't have developer accounts with a generic "Anonymous user" label. Ideally (for me), it would be best that we require the same for all users, since it's also weird to have reviews, collections, etc. with those names.

The MVP in this case would be to just require it for developers. So, during submission we would detect the developer doesn't have a display name, and then we require it to be set (it's probably a good idea to group it with the captcha that was recently added in https://github.com/mozilla/addons-server/issues/9171).

A better approach IMO is to require the display name and captcha when a user logs in for the first time. They need to do those two things or continue without logging in. It's better because it stops new anonymous accounts from being created, and helps fight a bit more spamming on the site.

Somewhat related issue: https://github.com/mozilla/addons-server/issues/8302

**Comment by jvillalobos** [comment]
Yes, that's good.

**Comment by diox** [comment]
Can we get a little guidance about what it should look like? Just a single input field with the display name after/before the checkboxes in the agreement page? With what label?

**Comment by diox** [comment]
@jvillalobos question for you above

**Comment by jvillalobos** [comment]
Above the captcha:

> [subtitle]Display Name[/subtitle]
> Your account needs a display name set so users know who your add-on is coming from. Please enter one below.
> [bold]Display Name:[/bold] [textbox]
> [link]More information on Developer Accounts[/link]

**Comment by ioanarusiczki** [comment]
@diox I tested this issue with FF67(Win10).  
`Display Name` is available when submitting first time an addon. The same for the Manage API Keys page if no addon was submitted ( where developer agreement is available). 
Once "Accept" button is clicked the `Display Name` becomes visible in dev hub on the right side of the screen next to "Tools" and "Back to Add-ons". Then if the user wishes, the display name can be edited from Edit my Profile. 

![Display Name](https://user-images.githubusercontent.com/33448286/58877793-57783900-86da-11e9-8737-0badb2ed7272.png)

The length of the field could be a bit longer but that's a minor UX issue.  Should we leave it as it is @jvillalobos ?

**Comment by jvillalobos** [comment]
Yeah, let's leave it as it is.
