### ISSUE TITLE
401 on logging with an user which is NOT banned

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#11454]
Steps to reproduce:
1.Go to AMO Stage and log in with valid credentials - "vcarciu+1331@mozilla.com"
2.Ban the account from step 1 (vcarciu+1331@mozilla.com)
3.Refresh the AMO page -> "Not authorized" message will be displayed
4.Try to login with an user which is NOT banned(vcarciu@mozilla.com)

Expected results:
User is able to log in without any issue

Actual results:
"Not authorized" message still displayed

**Comment by diox** [comment]
Happening because you're initially still logged in with a banned account that has had its session invalidated. Not a p1.
