### ISSUE TITLE
random sort should be available for ?recommended

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11457]
We currently limit sort=random to ?featured, but as ?recommended is the new featured we need to allow that too.  (eventually featured will be removed or become an alias for recommended)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The `random` sorting option is accepting a `recommended = true` parameter
https://addons-dev.allizom.org/api/v4/addons/search/?recommended=true&sort=random
