### ISSUE TITLE
Combine pre-review extension nominated and update into a single queue

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11477]
split off from #11072 

> Instead of New and Updates, the new queues are Recommended and Other Pending Review.

> The Other Pending Review queue has everything else with a version pending review: legacy add-ons that still need pre-review and non-Recommended add-ons that had the manual review flag set (no longer split into New and Updates).

**Comment by AlexandraMoga** [comment]
Verified on -dev with with Fx67, Win10x64

The new [Other Pending Review](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/extension) queue is available under Pre-Review Add-ons and can be accessed by users with `Addons:Review` permissions.
![image](https://user-images.githubusercontent.com/31961530/58549372-0c5eb180-8214-11e9-8524-2af55e96bb3b.png)

The list contains:
- legacy extensions that haven't been reviewed - [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/united-states-dictionary)
- new search engine submissions - [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/eccellio-science)
- extensions with a Disable auto-approval flag [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/momentum-dev)
