### ISSUE TITLE
Add a metric for account creation

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11474]
So that we have a better understanding of account creations which is wrapped as part of the login view, let's add an explicit metric for that.

**Comment by AlexandraMoga** [comment]
@muffinresearch is there anything to be validated by QA for this issue?
Thanks

**Comment by muffinresearch** [comment]
@AlexandraMoga as long as sign-up continues to work this should be fine.

**Comment by AlexandraMoga** [comment]
I've verified that new account registration is working on stage

I'm marking the issue as verified fixed with Fx67, Win10x64
