### ISSUE TITLE
Adding themes in the featured themes collection doesn't work

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11487]
As a followup for [#7817](https://github.com/mozilla/addons-frontend/issues/7817) I tried with and admin account to add themes using the frontend collection URL https://addons-dev.allizom.org/en-US/firefox/collections/4757633/featured-personas/

Expected result:
All themes are displayed when See more link is clicked from AMO's homepage https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme

Actual result:
The themes are not visible here https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme

Notes:
This is not reproducible when themes are removed from the collection. - FF66(Win10)
It is not reproducible for the other Mozilla collections from the homepage such as Feed readers, VPN solutions or Change up your tabs.
There's also an admin tools issue which is similar filed for this particular collection mozilla/addons-server#10403.

![featured themes](https://user-images.githubusercontent.com/33448286/58096020-d9496c00-7bdc-11e9-9907-b35ea5c88e19.gif)

**Comment by diox** [comment]
is it working on stage? dev is unreliable for this (the frequent updates are messing up the workers that need to update the search index this uses).

**Comment by ioanarusiczki** [comment]
@diox Unfortunately it won't, I can reproduce it on AMO stage too - FF67(Win10). 

![reproducible on stage2](https://user-images.githubusercontent.com/33448286/58946171-fe69dd00-878d-11e9-9b7c-bfa7b52be7bf.gif)

**Comment by ioanarusiczki** [comment]
@wagnerand I don't know if it's being used by reviewers on prod. 
Please, take a look. 
Same as for https://github.com/mozilla/addons-server/issues/10403

**Comment by diox** [comment]
Is it still an issue following the fix in https://github.com/mozilla/addons-server/issues/10403 ?

**Comment by ioanarusiczki** [comment]
@diox I verified this on dev and stage with FF68(Win10). I don't see this issue as being reproducible any longer. 
I could easily add or remove themes using 
https://addons-dev.allizom.org/en-US/firefox/collections/4757633/featured-personas/
https://addons.allizom.org/en-US/firefox/collections/4757633/featured-personas/
