### ISSUE TITLE
Parent directories of deleted files are not recreated in compare API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11480]
### Describe the problem and steps to reproduce it:

See https://github.com/mozilla/addons-code-manager/issues/597 and https://github.com/mozilla/addons-code-manager/issues/761 for STR

### What happened?

The [compare API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#compare) returns an entry for a deleted file but not for its parent directory

### What did you expect to happen?

The API should return an entry for the parent directory. This will make it looks like any other response and the frontend won't have to treat it like a special case.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. 
The parent directory of deleted files is returned by the compare API:

https://addons-dev.allizom.org/api/v4/reviewers/addon/616548/versions/1655557/compare_to/1655558/
```
 "_locales/it/messages.json": {
                "depth": 2,
                "filename": "messages.json",
                "sha256": null,
                "mime_category": null,
                "mimetype": "application/json",
                "path": "_locales/it/messages.json",
                "size": null,
                "modified": null,
                "status": "D"
            },
            "_locales/it": {
                "depth": 1,
                "filename": "it",
                "sha256": null,
                "mime_category": "directory",
                "mimetype": "application/octet-stream",
                "path": "_locales/it",
                "size": null,
                "modified": null,
                "status": ""
            }

```
