### ISSUE TITLE
500 error received when trying to add/change email addresses in the Email user restriction admin model

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11497]
STR

1. Log in to AMO stage with an admin account
2. Open the Admin Tools and access the Email user restriction model - https://addons-internal.stage.mozaws.net/en-US/admin/models/users/emailuserrestriction/
3. Click on any of the emails from the blocked list

Actual result:
You receive a 500 server error

Expected result:
The required page can be accessed 

Notes:
- happens also when you try to add a new email to the list
- reproduced on -dev and stage with Fx66, Win10x64

![2019-05-23_10-04-02](https://user-images.githubusercontent.com/31961530/58232739-fbf59500-7d42-11e9-804f-53d8808b8264.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/5809791/?query=is:unresolved

**Comment by AlexandraMoga** [comment]
This is now fixed on both -dev and stage.
