### ISSUE TITLE
expose recommended state in admin tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11498]
Spun off from #11074

Extensions can have one of three states: Not Recommended, Pending Recommendation, or Recommended. The admin for adding and removing extensions from the Recommended list is covered in this project. These states are independent from the review status (Approved, Disabled, Pending Review, etc.).

For DiscoveryItems:
- Not recommended = `not DiscoveryItem.recommendable`
- Pending recommendation = `DiscoveryItem.recommendable and not DiscoveryItem.addon.current_version.recommendation_approved`
- Recommended = `DiscoveryItem.recommendable and not DiscoveryItem.addon.current_version.recommendation_approved`

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67 Win10x64

1. Add-on is added as a new discovery item  => status is `Not recommended`
2. Add-on is set as recommended in discovery items => status changes to `Pending recommendation`
3. Add-on receives a new version => an entry in the recommended review queue is created. If the new version is approved => status changes to `Recommended`
4. Add-on is removed from the recommended list in discovery items => status changes to `Not recommended`
