### ISSUE TITLE
remove some nonsense addons search API sort parameters combinations

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11503]
You can currently do a call to the addons search API without a query string and specify a relevance sort, which returns nonsense ordering (because there's no score to sort on) `api/v4/addons/search/?sort=relevance`.
 You can also combine recommended with relevance (`sort=recommended,relevance`), which is redundant as the relevance sort already boosts recommended add-ons (but in sensible way).  We should either fail on those combinations (breaking backwards compatibility somewhat) or silently fix them to something sensible.

**Comment by AlexandraMoga** [comment]
I have verified this  on -dev and stage. Below are some examples:

In these examples the `sort` parameter seems to be ignored:
`/addons/search/?type=extension&sort=relevance` same results as `/addons/search/?type=extension`
`/addons/search/?sort=recommended,relevance/` same results as `/addons/search/`

@eviljeff 
I don't really understand how sorting by `relevance` when a query parameter is present influences the results. 
For example: https://addons-dev.allizom.org/en-US/firefox/search/?q=youtube&sort=relevance&type=extension seems to produce the same results as https://addons-dev.allizom.org/en-US/firefox/search/?q=youtube&type=extension. I've seen the same behavior in prod, so your changes didn't have an impact on this scenario.

**Comment by eviljeff** [comment]
`sort=relevance` is the default when `q` is included, so you'll get the same results if you don't specify the sort.

The following scenarios should have changed
- `/addons/search/?sort=relevance` should be ignored so return the same as `/addons/search/` (including any other filtering parameters, apart from `q`).
- `/addons/search/?q=foo&sort=recommended,relevance` (or any sort combinations that include both `recommended` and `relevance`) should be changed to drop `recommended`.  e.g. `/addons/search/?q=foo&sort=downloads,recommended,relevance` would become `/addons/search/?q=foo&sort=downloads,relevance` (a pretty pointless combination too, but valid)

**Comment by AlexandraMoga** [comment]
> * `/addons/search/?sort=relevance` should be ignored so return the same as `/addons/search/` (including any other filtering parameters, apart from `q`).

this scenario has indeed changed. I've compared my results with prod, where sorting by `relevance` imposed a different order to search results. By comparison, -dev and stage are no longer taking into account a `sort = relevance` parameter, hence `/addons/search/?type=extension&sort=relevance` brings the same results as `/addons/search/?type=extension`

> * `/addons/search/?q=foo&sort=recommended,relevance` (or any sort combinations that include both `recommended` and `relevance`) should be changed to drop `recommended`. e.g. `/addons/search/?q=foo&sort=downloads,recommended,relevance` would become `/addons/search/?q=foo&sort=downloads,relevance` (a pretty pointless combination too, but valid)

for  `addons/search/?type=extension&q=youtube&sort=recommended,downloads,relevance` results are not sorted exactly the same as for `addons/search/?type=extension&q=youtube&sort=downloads,relevance` 
If I understand your comment correctly, you expect these search combinations to bring exactly the same results?
