### ISSUE TITLE
Link for more information about blocked Developer Accounts 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#11508]
Related to #11443 & #11441: the link to "More information on Developer Accounts" should go to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Developer_accounts. 

We'll be moving this page to Extension Workshop sometime in late July/early August.

**Comment by diox** [comment]
I have skipped the link for now, I'll add it and point to that page.

**Comment by AlexandraMoga** [comment]
A link pointing to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Developer_accounts has been added below blocked submission messages when an email or IP is restricted:
![image](https://user-images.githubusercontent.com/31961530/58863673-f6416d00-86bb-11e9-9c2b-4287e0268dca.png)

![image](https://user-images.githubusercontent.com/31961530/58863681-f9d4f400-86bb-11e9-9120-c6708da691a5.png)
