### ISSUE TITLE
New directory structure for xpis storage

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#11510]
### Describe the problem and steps to reproduce it:
Per the comment in https://github.com/mozilla/addons-server/issues/11464#issuecomment-495544507, we'd like to request change of directory structure under `guarded-addons/` and `files/` directory.

It is suggested that instead of a flat directory structure, we should have a 3-level deep structure under `guarded-addons`/`files/` that is based on the add-on id, for example, something like `/guarded-addons/9/89/789/123456789/`.

 
### What happened?
There are too many sub-directories under `guarded-addons/` and `files/`, currently more than 327K of them and keeps growing.

### What did you expect to happen?
A new directory structure for guarded-addons directory.

### Anything else we should know?
There is also https://github.com/mozilla/addons-server/issues/3598. If it can be done first, then we can probably close this one by that time.

**Edited** by @diox to reflect latest directory structure plans

**Comment by bqbn** [comment]
Assuming the work for this hasn't started, I just updated the request, changing it from a 2-level deep to 3-level deep. The reason is that given 1 million addon ids, 2-level directory structure means there could be 10,000 sub-directories at the third level, which is still too many for `ls` to handle. Besides, our site keeps growing, I suspect it'll grow into multi-million addon ids in a few years.

**Comment by bqbn** [comment]
Any chance we can make this ticket into a project and try to tackle it in year 2022?

The original request was for the `guarded-addons` directory only, however, I think the `files` and `shared_storage` directories should also be considered for using the hierarchical directory layout because they suffer the same problem as the `guarded-addons` directory and it is largely due to the flat directory layout.

**Comment by diox** [comment]
Started working on a [document](https://docs.google.com/document/d/1fn-C0nl5wFAur4yEsPiEoXAKznAxl4u1TGcvaqLD_N4/edit#) detailing the issue and potential solutions.

**Comment by diox** [comment]
Nice side-benefit of doing https://github.com/mozilla/addons-server/issues/18844 first: once files are served through addons-server instead of nginx, their path can change independently of their URL. Currently the 2 are inextricably linked, the URL is directly built from the path on EFS - With urls like `https://addons.cdn.mozilla.net/user-media/addons/<addonid>/<filename.xpi>?filehash=<hash>` pointing to a file under `files/addons/<addonid>/<filename.xpi>`.

**Comment by diox** [comment]
Additional thing to do while we're renaming files:
- In the database, rows with `is_mozilla_signed_extension=true` should also have `is_signed=true`
- By convention, non-signed files should have a filename ending in `.zip` per https://github.com/mozilla/addons-server/issues/19013 (`.xpi` is for signed files)

**Comment by diox** [comment]
QA: test https://github.com/mozilla/addons-server/issues/19207 first ; then once that issue is verified, give me pks of files you used so that I can verify they are stored where they should.

**Comment by diox** [comment]
Err, sorry meant pks == ids. But URLs are great too, I can use that.

**Comment by ioanarusiczki** [comment]
@diox I can get all ids, sure : 621537, 621533, 621536, 621539, 621540, 621541, 621538.

**Comment by diox** [comment]
Perfect, I can see all of these are stored with the new directory structure:
```
>>> from pprint import pprint
>>> pprint([f.file.name for f in File.objects.filter(version__addon__id__in=(621537, 621533, 621536, 621539, 621540, 621541, 621538))])
['33/1533/621533/decentraleyes-2.0.17.zip',
 '36/1536/621536/eneral_catalan_dictionary_test-3.0.5.xpi',
 '36/1536/621536/eneral_catalan_dictionary_test-3.0.6.xpi',
 '37/1537/621537/eval_wup-1.3.zip',
 '37/1537/621537/eval_wup__test-1.4.xpi',
 '38/1538/621538/floral_swirls_part_blue-1.0.xpi',
 '38/1538/621538/floral_swirls_part_blue-2.0.xpi',
 '39/1539/621539/undo_close_tab_test-7.5.0.xpi',
 '40/1540/621540/sidebery_test-4.10.1.xpi',
 '40/1540/621540/sidebery_test-4.10.2.xpi',
 '41/1541/621541/youtuberecommendedvideos_test-1.6.1.xpi',
 '41/1541/621541/youtuberecommendedvideos_test-1.6.2.xpi']
```

So if https://github.com/mozilla/addons-server/issues/19207 is good then we can consider this issue verified. Thanks.

**Comment by ioanarusiczki** [comment]
@diox

 I found an issue on Android, could it be related to it? https://github.com/mozilla/addons-server/issues/19232

**Comment by diox** [comment]
Mmmm those are still using the old directory structure, so probably not, but the timing is suspicious, I'll check it out, thanks.
