### ISSUE TITLE
File download is 404

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11524]
### Describe the problem and steps to reproduce it:

I am trying to download a file. (id: 2993332)

### What happened?

https://addons.mozilla.org/firefox/downloads/file/2993332/adpbe_flash_player-4.1.1-fx.xpi?src=reviewer is 404
https://addons-internal.prod.mozaws.net/en-US/admin/models/files/file/2993332/download/ is 404

### What did you expect to happen?

A file download.

### Anything else we should know?

Reviewer tools page: https://reviewers.addons.mozilla.org/en-US/reviewers/review/youtube-adblock-video

Add-on status: _Incomplete_
File status: _Disabled by Mozilla_
File location on disk: `files/2251973/adpbe_flash_player-4.1.1-fx.xpi`

**Comment by muffinresearch** [comment]
@diox is this likely to be related to the sub-directory layout issues e.g. #11510?

**Comment by diox** [comment]
Possibly. The related issue would be https://github.com/mozilla/addons-server/issues/11464

More likely I think is simply the fact that the rejection is recent, so the file hasn't been moved yet - the cron to move the files in that direction (public -> private) is only fired twice a day.

**Comment by wagnerand** [comment]
The file was rejected through normal review process. Does this rely on the cronjob as well? Could the rejection "task" move the file directly?

**Comment by diox** [comment]
Reviewer actions *should* already be moving the file directly, but I'm not sure all edge cases are covered. 

The crons are there to catch both known limitations (changing the state of the add-on without touching the files, or touching multiple through a a queryset) but also unforeseen issues (exceptions, timeouts etc).

**Comment by diox** [comment]
The cron did end up fixing the problem. So we're just left with the question of why this wasn't done by reviewer tools code when rejecting - looking at the code briefly it should definitely be done directly in theory.

**Comment by wagnerand** [comment]
Since this has been de-prioritized, can we increase the cronjob interval?

**Comment by diox** [comment]
We can probably push it to twice per hour, I need to confirm with ops though.

**Comment by diox** [comment]
Ops are ok to move increasing frequency of this cron to hourly. Because the query + filesystem operations can take a while, we'd need to change the way it works to go beyond that.
