### ISSUE TITLE
Browse API returns wrong content type for youtube-download-video

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11534]
### Describe the problem and steps to reproduce it:

* Sign into prod with a reviewer account
* Load https://code.addons.mozilla.org/en-US/browse/1482277/versions/3189741/?path=data%2Fconfig.json

It makes this API call
```
https://addons.mozilla.org/api/v5/reviewers/addon/1482277/versions/3189741/?file=data%2Fconfig.json
```

### What happened?

The API response specifies the mime type of the file `data/config.json` incorrectly as `text/html`.

### What did you expect to happen?

It should be `application/json`

### Anything else we should know?

This renders the file without syntax highlighting. See https://github.com/mozilla/addons-code-manager/issues/790

Other json files do not typically have this problem.

**Comment by lavish205** [comment]
@diox Can I work on this issue?

**Comment by diox** [comment]
Best ask @EnTeQuAk since he's assigned. In any case it's not a mentored bug so I wouldn't try it unless you're confident you can deal with it on your own. Likely involves doing some Python and debugging.

**Comment by lavish205** [comment]
I think I'll be able to fix this issue if some guidance is provided. @EnTeQuAk shall I work on this bug?

**Comment by EnTeQuAk** [comment]
@lavish205 	I don't think this is something easy you can fix to be honest. I quickly looked into it, and it seems to be related to the used `libmagic` version that is being used inside our docker image. I'm trying to figure this out, but currently it's not really a bug in our code but rather in a 3rd-party library that might not be so easy to upgrade.

Really sorry about the late reply.

**Comment by EnTeQuAk** [comment]
Some more specific investigation:

Inside docker:

```
root@7c14f4f8ad98:/code# file --version
file-5.30
magic file from /etc/magic:/usr/share/misc/magic
root@7c14f4f8ad98:/code# file src/olympia/files/fixtures/files/file_viewer_filetypes/html-containing.json 
src/olympia/files/fixtures/files/file_viewer_filetypes/html-containing.json: HTML document, ASCII text
```

On my system:
```
$ file --version
file-5.37
magic file from /usr/share/file/misc/magic
$ file src/olympia/files/fixtures/files/file_viewer_filetypes/html-containing.json 
src/olympia/files/fixtures/files/file_viewer_filetypes/html-containing.json: JSON data
```

:man_shrugging:

**Comment by EnTeQuAk** [comment]
Another investigation is, that

```json
{
   "bar": "<style>"
}
```

triggers this, other HTML tags don't seem to do that.

**Comment by EnTeQuAk** [comment]
So actually… any tag listed in https://github.com/file/file/blob/master/magic/Magdir/sgml#L57 is triggering this.

**Comment by EnTeQuAk** [comment]
So, apparently between Version 5.34 and 5.35 the `file` utility became a much more powerful JSON detection which it didn't have before. :disappointed:

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I uploaded the the addon on -dev. It's https://code.addons-dev.allizom.org/en-US/browse/616914/versions/1688318/?path=data%2Fconfig.json
And requested via Postman https://addons-dev.allizom.org/api/v5/reviewers/addon/616914/versions/1688318/?file=data/config.json

I receive in the response in `entries`
` "mime_category": "text",
                "mimetype": "text/html",`

![config](https://user-images.githubusercontent.com/33448286/60110250-76676980-9774-11e9-9ac6-ec69d522db78.png)

**Comment by EnTeQuAk** [comment]
This will be on -dev once https://github.com/mozilla/addons-server/pull/11701 lands and the next -dev deployment is triggered.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
Yes, it's returning the correct `mimetype` now. 

![the correct mimetype](https://user-images.githubusercontent.com/33448286/60160023-21236a80-97fd-11e9-9ad3-7a81c886af2d.png)

Verified on -dev with Postman.

**Comment by EnTeQuAk** [comment]
For potential future problems: In case this arises again, we might want to double-check if we can move to pygments file-detection instead which has much less dependencies and bugs are much easier to fix.
