### ISSUE TITLE
Developers shouldn't be allowed to disable/delete the latest approved version of a recommended add-on

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11535]
Follow up for https://github.com/mozilla/addons-server/issues/11074#issuecomment-496692345

**STR:**
1. Log in to developer hub with a developer account that has at least one recommended add-on
2. Open the Manage versions page of an add-on that has a recommended latest version - e.g. https://addons-dev.allizom.org/en-US/developers/addon/terms-of-service-didn-t-read/versions
3. Try to delete or disable this version

**Actual result:**
The developer is allowed to delete or disable the latest version of a recommended extension

**Expected result:**
Developers should not be allowed to delete/disable the latest version of a recommended add-on

**Notes:**
- I believe the rule should also apply when the developer tries to delete the add-on entirely

**Comment by diox** [comment]
@jvillalobos can you give us an error message for this ? Should we suggests developers to contact admins in that case ?

**Comment by jvillalobos** [comment]
This should only apply to Recommended _extensions_.

Error message:
> The latest approved version of a Recommended extension cannot be deleted or disabled. Please contact AMO Admins if you need help with this.

**Comment by diox** [comment]
> I believe the rule should also apply when the developer tries to delete the add-on entirely

It doesn't: Developers deleting recommended versions is a problem if there was no other listed recommended version. We would need to demote them, stripping them of their recommended badge, and doing that automatically can be confusing, hence the need to prevent it. On the other hand, if they delete the add-on entirely, there is no going back anyway, so we aren't in a weird state, it sucks to lose a recommended add-on but nothing would be incoherent/broken.

**Comment by diox** [comment]
Note for QA: in the case where an add-on is recommended and you're trying to delete/disable the latest version, you shouldn't see the form at all in the modal popin that appears. If you use the developer tools inspector to un-hide the form in that modal, and then submit, you should see an error message appear (and the deletion/disabling should have been prevented).

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67, Win10x64

- when a developer tries to disable or delete the latest approved recommeded version, the following message is generated:
![image](https://user-images.githubusercontent.com/31961530/58948133-1ba0aa80-8792-11e9-877e-30be95046723.png)

- if you try to enable the form from the inspector tools, when you press the Delete or Disable buttons the following message is generated and the action has no effect on the add-on version:
![image](https://user-images.githubusercontent.com/31961530/58948139-1f343180-8792-11e9-83c7-19eb299c89da.png)

- disabling/enabling versions is still working as before for unrecommended versions or add-ons

**Note:** this new process is not available for themes. I know that themes become recommended based on membership in the featured personas collection, so they are not undergoing the review process established for the rest of the add-on types. 
Do we need to block version disabling/deleting for themes too?
Cc @jvillalobos for input

**Comment by AlexandraMoga** [comment]
Given that the request was to have this restriction process on extensions only, the conclusion is that the implementation is working as expected, therefore I'm marking the issue as verified fixed.
