### ISSUE TITLE
Recommended add-on reviewers should be awarded points based on the post-review model

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11536]
Follow up for https://github.com/mozilla/addons-server/issues/11074#issuecomment-496692345

Prerequisites: log in with a user that has at least the following permissions: `Addons:Review, Addons:PostReview, Reviews:Admin`

**STR:**
1. Go to the Reviewer Tools dashboard
2. Open the Recommended queue
3. Select an add-on from the list to review
4. Approve the version
5. Verify if you received any review points

**Actual result:**
Recommended add-on reviews are all triggering `0` reviewer points

**Expected result:**
Recommended add-on reviewers should be awarded points based on the post-review model

**Notes:**
- reproduced on -dev with Fx67, Win10x64

**Comment by diox** [comment]
Depends on https://github.com/mozilla/addons-server/issues/11537

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. Reviewers are awarded points when they approve or reject a version from the Recommended queue. The reward model follows the same pattern used for auto-approved add-on reviews.
![image](https://user-images.githubusercontent.com/31961530/58962015-f4a6a080-87b2-11e9-9e98-cd24951f6cf7.png)
