### ISSUE TITLE
Set up pywatchman for local envs

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11539]
### Describe the problem and steps to reproduce it:

addons-server local env is consuming a lot of CPU doing nothing in particular

### What happened?

Buried in [Django 2.2 release notes](https://docs.djangoproject.com/en/2.2/releases/2.2/) is a short sentence that says [pywatchman](https://pypi.org/project/pywatchman/)+[Watchman](https://facebook.github.io/watchman/) replaced [pyinotify](https://pypi.org/project/pyinotify/).

Since we don't have watchman set up, that means that Django falls back to checking each file in the repos manually every second or so to support autoreloading. This has a dramatic effect on CPU usage on local envs even when idle.

### What did you expect to happen?

Not consume a lot of CPU for autoreloading.

### Anything else we should know?

pyinotify was transparent (and efficient!), watchman requires some set up, it uses a service. Need to be careful not to make things worse.

https://code.djangoproject.com/ticket/27685 has the rationale behind the change.

**Comment by diox** [comment]
This is more annoying that it looks, because:
- There is no debian package for watchman, gotta build it yourself
- Gotta start watchman before django reliably (need to hack around https://github.com/Supervisor/supervisor/issues/122)
- If watchman doesn't behave properly it may take the whole process down
- If watchman doesn't behave properly but django catches the error, it may fall back to the old stat-based reload method transparently for the rest of the life of the process (it does log an error though)

**Comment by diox** [comment]
`uwsgi` has autoreload options for local development so the better approach here would probably be to stop using `runserver` entirely and switch to uwsgi in our local envs, bringing us closer to prod (and bringing us closer to a single `Dockerfile`).

I'm not 100% sure it would work as well, particularly with jinja templates, but we can probably figure something out.

**Comment by EnTeQuAk** [comment]
I'm tackling https://github.com/mozilla/addons-server/issues/6668 and if the docker gods are with me autoreload with uwsgi "will just work" (tm)

**Comment by EnTeQuAk** [comment]
I marked this as fixed as I configured uwsgi auto-reload and it seems to work for me locally. That obviously doesn't mean that there won't be an edge-case where it doesn't so let's test this during daily business and see how that goes.
