### ISSUE TITLE
Searching abuse reports for an add-on with a longer name will return less results than it should

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11558]
Followup for #11308

STR:
1. Go on dev to /en-US/admin/models/abuse/abusereport/
2. Filter the reports by type: addons
3. Make a search for the following addons 
X-notifier (for Gmail,Hotmail,Yahoo,AOL ...)
Awesome Screenshot Plus - Capture, Annotate & More
Ecosia - The search engine that plants trees!
4. Observe the number of results
5. For the same add-on make a search using their GUID or id, observe the number of results and then compare with 4. 

Expected results:
The number of results making a search using the name is equal with the number of results when the id or GUID is used.

Actual results:
When making a search using the name the number of abuse reports is less than when making the search using an id or GUID.

Notes:
This issue is reproducible on AMO dev with FF67(Win10). 

Examples
"X-notifier (for Gmail,Hotmail,Yahoo,AOL ...)" ->130 search results using the id or GUID then 13 using it's complete Name.
"Awesome Screenshot Plus - Capture, Annotate & More"-> 122 search results using the id down to 61 when I try with the complete Name.
"Ecosia - The search engine that plants trees!" -> I get 5 results if I type in just "Ecosia" (or search it by GUID or ID), and 1 result if I use it's complete Name.

![search addon by name](https://user-images.githubusercontent.com/33448286/58710002-07d8fb00-83c4-11e9-8b5a-df3c04ed23b2.gif)

**Comment by diox** [comment]
Note: the actual problem is not that we find less results when searching for name, but rather that each result is duplicated n times when searching for guid for some reason. It's apparent in the gif, the first 10 results are the same abuse report, and 13 x 10 = 130.

**Comment by ioanarusiczki** [comment]
Yes, that I did not notice while filing the issue, but right now the duplicates are no longer displayed. 
Same number of reports for Name, GUID or ID for the examples given[ above](https://github.com/mozilla/addons-server/issues/11558#issue-450809042)
Verified on -dev with FF67(win10)
