### ISSUE TITLE
Searching a reported user by name doesn't work in abuse reports admin 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11557]
Followup for https://github.com/mozilla/addons-server/issues/11308

STR:
   1.  Go on dev to /en-US/admin/models/abuse/abusereport/
   2.  Filter the reports by type: users
   3. Type in some names. I tried with the following 
       BobsDisplayName
       UserWithNoPerms
       LexaDev
       IoanaTestingStageandDevlongstringlong
       Itsy Bitsy Spider
      Amoga-dev
     Jorge Villalobos
4. Observe the search results 

Actual result:
0 results returned.

Expected result:
The abuse reports of the reported users should be displayed. 

Notes:
Reproducible on AMO dev - FF67(Win10). 
These are some examples of Names that returned the expected result:
CosminSV
kumar_dev2
testemaildev

![search user by name](https://user-images.githubusercontent.com/33448286/58708598-eaeef880-83c0-11e9-99d9-1170d96602dc.gif)

**Comment by Patil2099** [comment]
Can I fix this problem by creating a custom search box?

**Comment by diox** [comment]
No, it's just a matter of adding the right field to the list of fields we search in, but I'm taking care of it already

**Comment by diox** [comment]
@jvillalobos do we need the ability to search abuse reports by display name too? Currently we search by id or username, since display name is not indexed. Searching by display name would be costly in terms of performance.

**Comment by jvillalobos** [comment]
I think ID should be enough. We discontinued username, and admins should be able to find the ID based on the display name.

**Comment by diox** [comment]
Ok. We have username prefix search now (and email) so I'll leave this in, we can remove it later if necessary for performance reasons.

Closing this as we don't care about display name search per previous comment.
