### ISSUE TITLE
[Abuse report detail] Links to Privacy Policy/EULA pages are not opening the corresponding pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11568]
Follow up for #11136 
Prerequisites: Log in with an admin user or with an account that has `AbuseReports:Edit` permissions

**STR:**
1. Open the Abuse report admin tool
2. Select an entry from the list to view its details - https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/24879/change/
3. Click on the View Privacy Policy link

**Actual result:**
The View Privacy Policy link doesn't have an actual reference (see screenshot), so when you click on it nothing happens

**Expected result:**
The link should open the Privacy policy details on the new frontend - https://addons-dev.allizom.org/en-US/firefox/addon/add-on-indexing/privacy/

**Notes:**
- the EULA link has the same set-up
- reproduced on -dev with Fx67, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/58795921-98058300-8604-11e9-8891-6d608229ff10.png)

**Comment by AlexandraMoga** [comment]
@diox the Privacy Policy and the EULA pages are now opened at `https://reviewers.addons-dev.allizom.org/en-US/reviewers/privacy/<addon_slug>`, respectively `https://reviewers.addons-dev.allizom.org/en-US/reviewers/eula/<addon_slug>`

I thought we are going to redirect to the new frontend, but I see that we have standalone pages under `/reviewers/` for these resources. 

Probably not a big priority, but should't we consistently redirect to the new frontend when possible? 

![2019-06-07_16-43-35](https://user-images.githubusercontent.com/31961530/59109196-4848f380-8945-11e9-8e08-01e04100b411.gif)

**Comment by diox** [comment]
The add-on might be disabled/non-public etc so it's best to use reviewer tools implementation.
