### ISSUE TITLE
Preserve IP addresses for banned users for a limited time

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11560]
### Describe the problem and steps to reproduce it:

In order to fight bad actors, we need to preserve the `last_login_ip` of a banned user for some time.

### What happened?

`last_login_ip` gets cleared on account ban.

### What did you expect to happen?

Keep `last_login_ip` for some time.

### Anything else we should know?

We should add a daily cronjob that clears IP addresses from banned users if their IP address hasn't been used by another user in 12 months (measured from the last login of the banned user. Ban date would be preferred, but that's a little harder to fetch, until we do #11458).

Legal and Trust/Security have signed-off on this. @muffinresearch can confirm if needed.

**Comment by Patil2099** [comment]
Can I work on this Issue?

**Comment by muffinresearch** [comment]
> Can I work on this Issue

@Patil2099 Thanks for asking, though unfortunately this is probably not the best kind of bug to work on as a contribution.

**Comment by AlexandraMoga** [comment]
@diox what's the best way to test this? For starters, I can't even reproduce this STR on stage:

>What happened?
last_login_ip gets cleared on account ban

I am looking in `https://addons-internal.stage.mozaws.net/en-US/admin/models/users/userprofile/<userId>/change/` to get the Last login ip of the user I've just banned, but I see that the IP is still displayed.

As for -dev, I don't have examples of banned users from one year (366 days) ago or more. Is there a way to alter the ban date for specific users?

**Comment by diox** [comment]
`last_login_ip` *used* to be cleared immediately on ban, that was changed 2 months ago in https://github.com/mozilla/addons-server/pull/11596. The change I made here was that a year after the banned user has been last modified (*), that IP will be cleared.

(*) approximation of what was originally asked for that should be good enough for us.

We can alter that modification date for specific users for testing, yes.

**Comment by AlexandraMoga** [comment]
Id | Banned | Last known activity time (ban date)
-- | -- | --
10641911 | Yes | Aug. 6, 2019, 9:55 a.m.
10641545 | Yes | Aug. 6, 2019, 9:58 a.m
10641834 | Yes | Aug. 6, 2019, 10:16 a.m.
10641830 | Yes | Aug. 6, 2019, 10:21 a.m.

@diox, if possible:
For the first Id, the last modified date should be `year - 1 day`
For the second Id, the last modified date should be `exactly one year`
For the last two Ids, the last modified date should be `> 1 year`

Also, when is the cron expected to run today?

**Comment by diox** [comment]
The cron runs at 06:01 UTC every day. I can force it to test the command but it's probably best to wait for it to fire "naturally". With that in mind, for `exactly one year` in your tests, what's the exact date & time you want ?

**Comment by AlexandraMoga** [comment]
If `year` is 365 days,  then my date should be Aug. 6, 2018, 9:58 a.m

**Comment by diox** [comment]
Updated all modified dates on dev.

**Comment by AlexandraMoga** [comment]
Looks like the cron job has run and the results seem to be correct:


ID | Banned | Modified date | IP cleared
-- | -- | -- | --
10641911 | Yes | year -1 | FALSE
10641545 | Yes | year (exact) | TRUE
10641834 | Yes | > year | TRUE
10641830 | Yes | > year | TRUE
10641912 | Yes | < year | FALSE
10641543 | No | > year | FALSE

I'm marking this as verified fixed on -dev
