### ISSUE TITLE
CircleCI builds are failing

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11565]
Moving this to addons-frontend, now that legacy frontend is gone is another thing but we should put circleci tests to green in the meantime.

```
tests/ui/test_home.py::test_category_section_loads_correct_category[Resolution: 414x738] FAILED
```

And it seems to fail because `.CategoryHeader-name` isn't present on this page: 

![index](https://user-images.githubusercontent.com/139033/58783811-2288bb00-85e2-11e9-9254-e91867ab6dee.png)

Which links to this commit on addons-frontend: https://github.com/mozilla/addons-frontend/commit/f7d85d5d88233d60cb19726c57463f13da14f0c0

**Comment by EnTeQuAk** [comment]
Since the page got removed I assume we can just remove the test too.

**Comment by jrbenny35** [comment]
I'll try and get this fixed by EOD tomorrow. Still traveling home from All-Hands

**Comment by jrbenny35** [comment]
I was able to get the frontend to load recommended extensions but I can't get recommended themes to work. Any tips @EnTeQuAk ? The recommendation system is new to me

**Comment by EnTeQuAk** [comment]
> I was able to get the frontend to load recommended extensions but I can't get recommended themes to work. Any tips @EnTeQuAk ? The recommendation system is new to me

I don't quite get what this has to do with removing this particular test? The issue here has nothing to do with #11721 imho, let's keep them separated and fix them separated.

> but I can't get recommended themes to work

Can you elaborate what is being problematic here specifically? While it's technically possible to mark themes as recommendable - it's practically unsupported and they're not supposed to be marked as recommended. They have to be added to a special collection as that's how it's exposed to the client right now.

I'd rather split the two and focus on regular extensions for now.

**Comment by jrbenny35** [comment]
> Can you elaborate what is being problematic here specifically? While it's technically possible to mark themes as recommendable - it's practically unsupported and they're not supposed to be marked as recommended. They have to be added to a special collection as that's how it's exposed to the client right now.

I'd rather split the two and focus on regular extensions for now.

Well the recommended themes still aren't being loaded on the frontend. I was able to get recommended extensions to work. It would be nice to have a fully working home page.

Do you know which collection is needed to put the themes under "Recommended Themes" on the frontend?

**Comment by jrbenny35** [comment]
Looks like there are a few categories that aren't being loaded..

**Comment by jrbenny35** [comment]
I am seeing this within the nginx logs: ```72.18.0.11 - - [28/Jun/2019:22:32:54 +0000] "GET /api/v4/accounts/account/4757633/collections/be-more-productive/addons/?lang=en-US&wrap_outgoing_links=true HTTP/1.1" 404 23 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" "-"```

It looks like I need to make a user that is numbered ```4757633```?

@kumar303 any thoughts?

**Comment by kumar303** [comment]
What page is that request being made on? Are you sure that the category tests have all been updated to reflect the site changes per https://github.com/mozilla/addons-frontend/issues/8090 ? Maybe it would help to look at the failing tests and compare that to browsing the dev site? The dev site reflects what has been verified by the QA folks after removing all category pages.

**Comment by jrbenny35** [comment]
@kumar303, this was on the homepage. I know there are a few different categories that load on the homepage, but it seems 2 (recommended extensions, recommended themes) are always trying to load.

**Comment by kumar303** [comment]
@jrbenny35 oh, I see. 

> It looks like I need to make a user that is numbered ```4757633```?

Yes, you do. You should control the account creation with the [`mozillaUserId`](https://github.com/mozilla/addons-frontend/blob/be89a2181b109a37002d3319949e95ded1e8824e/config/default.js#L359) config value. You could set that value yourself by [overriding the config](https://github.com/mozilla/addons-frontend/#local-configuration), too.

**Comment by EnTeQuAk** [comment]
That user id matches `settings.TASK_USER_ID` in addons-server.

**Comment by jrbenny35** [comment]
Okay I should be able to fix this, just had to finish up some other work.

**Comment by jrbenny35** [comment]
@EnTeQuAk this one? https://github.com/mozilla/addons-server/blob/master/settings_test.py#L52, I am not sure if we use ```settings_test.py``` or ```settings.py``` when setting up a local instance of AMO.

**Comment by jrbenny35** [comment]
How could I assign this to a user I create? The main issue is that there is no user by that task id.

**Comment by EnTeQuAk** [comment]
Correct, we're using settings.py for a local instance, not settings_test.

You could create that user in the serializer in the landfill app so that it's being created on setup maybe?
