### ISSUE TITLE
The submission success message for search tools should be updated to match the rest of the auto-approved add-ons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11572]
**STR:**
1. Log in to AMO -dev 
2. Submit a new search tool
3. Complete all the necessary steps to obtain a successful submission
4. Check the success message generated

**Actual result**
This is the message generated at search tool submissions:

_Version Submitted for Review_
_You’re done! This version has been submitted for review. You will be notified when the review has been completed, or if our reviewers have any questions about your submission._ 

**Expected result**
The message should be updated to match the rest of the auto-approved add-ons:

_Version Submitted_
_You’re done! This version will be available on our site shortly._ 

**Notes:**
- reproduced on-dev with Fx67, Win10x64

**Comment by diox** [comment]
Yeah we can probably replace this check:
`{% elif uploaded_version.is_webextension and not addon.auto_approval_disabled %}`
by
`{% elif uploaded_version.is_ready_for_auto_approval() %}`

that would also make things more correct for recommended add-ons (that are manually approved).

**Comment by Abhi-khandelwal** [comment]
Hi @diox I would like to work on it, can i take this up?

**Comment by diox** [comment]
Sure, go ahead and give it a try.

**Comment by AlexandraMoga** [comment]
Verified fixed:

![image](https://user-images.githubusercontent.com/31961530/60431291-19523480-9c08-11e9-84d4-c180654d1a5c.png)
