### ISSUE TITLE
When an add-on is already installed, it should be indicated

### ISSUE THREAD

**Issue by sarahmonster** [mozilla/addons-server#1157]
I was looking to install Firebug and ended up on a page that looked like this:

![screen shot 2015-12-30 at 11 43 51 am](https://cloud.githubusercontent.com/assets/376315/12050284/bfa933c4-aeea-11e5-98e6-077d659395bd.png)

Greasemonkey is already installed & active, but this screen seems to indicate that it isn't. I'd expect that installed add-ons would look visually different—ie, maybe a greyed-out button that reads "already installed" or something similar. This would also reinforce that an add-on had been installed successfully—ie, when Firebug has successfully installed, the button changes state.

**Comment by wagnerand** [comment]
There are a couple of comments to this feature request already like https://bugzilla.mozilla.org/show_bug.cgi?id=1194183#c3

**Comment by andymckay-limited-access** [comment]
The new discovery pane now does this, we have the APIs. All we have to do now is figure out how to make it apply to all of AMO.

**Comment by EnTeQuAk** [comment]
I believe this will be reimplemented later anyway with properly showing the installation state so maybe this should move to addons-frontend or be closed and rescheduled for when we attempt to reimplement this.

**Comment by shell15** [comment]
we are expecting to do something like this in the next overhaul.  cheers and thanks
