### ISSUE TITLE
A blocked additional author can't be removed from the list if it was added before its email became blocked

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11580]
**STR**

1. Log in to AMO with a developer account
2. Add an additional author to one of your add-ons  in `https://addons-dev.allizom.org/en-US/developers/addon/<addon-slug>/ownership`
3. With an admin account, add the additional account to the blocked email list in https://addons-internal.dev.mozaws.net/en-US/admin/models/users/emailuserrestriction/
4. Go back to the addon ownership page and change other information -  the license for example
5. Try to save your changes
6. Observe that the additional author field has an error notifying that the email is blocked
7. Remove the additional author and Save your changes

**Actual result:**
The blocked additional author is not removed. This is also reflected on the add-on detail page

**Expected result:**
The blocked additional author is successfully removed

**Notes:**
- I can't say if this is a regression because this scenario is not available on stage
- reproduced on -dev with Fx67 Win10x64

![2019-06-04_13-36-48](https://user-images.githubusercontent.com/31961530/58874791-64912a00-86d2-11e9-934f-c052f2695697.gif)

**Comment by diox** [comment]
I'd argue that this is a good thing. This prevents someone blocked to remove themselves from an add-on (by adding someone unblocked and removing themselves afterwards) so we'll easily be able to find the add-ons they were on before being blocked without them changing it.

@jvillalobos for input though.

**Comment by jvillalobos** [comment]
If we add a domain to the list, we should probably look into the list of affected developers and take action on them anyway. And we also want to add throwaway email domains to the list, which aren't necessarily used for malicious purposes, and having developers fix their own stuff instead of us would be handy.

I'd prefer that we accept the removals and log them in some way we can find later on if needed.
