### ISSUE TITLE
Accessing the taar service may log sensitive information

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#11586]
### Describe the problem and steps to reproduce it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1546132 requested that we set up HTTP basic auth when talking to taar service.

If that's enabled, the application may log sensitive information such as

`"Calling recommendation server: https://<user>:<pass>@taar.dev.mozaws.net/v1/api/recommendations/12345678-90ab-cdef-1234-567890abcdef/"` 

We should make sure no secret is logged before enabling HTTP basic auth when talking to taar service.

### What happened?
Application logs sensitive information if HTTP basic auth is used for taar service.

### What did you expect to happen?
Do not log sensitive info when talking to taar service.

### Anything else we should know?
n/a

**Comment by diox** [comment]
I think we can just remove that log statement entirely.
