### ISSUE TITLE
'dark_theme' is not identified as a theme type

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11593]
Follow up for https://github.com/mozilla/addons-linter/issues/2623#issuecomment-499384336

**STR:**
1. Log in to AMO 
2. Upload a new theme using the `dark_theme` key inside the manifest - see attached .zip example
3. Check your submission result

**Actual result:**
The `dark_theme` key is not identified as a theme type, so you end up with an extension after the submission is completed

**Expected result:**
The `dark_theme` property should be correctly identified as a theme type

**Notes:**
- reproduced on -dev and stage with Fx67, Win10x64

Examples:
https://addons-dev.allizom.org/en-US/firefox/addon/trans-blue/
https://addons-dev.allizom.org/en-US/firefox/addon/fire-and-water-68/

Example zip:
[dark_theme property.zip](https://github.com/mozilla/addons-server/files/3260551/dark_theme.property.zip)

**Comment by EnTeQuAk** [comment]
@eviljeff I quickly looked at it and making the submission detect it as a static theme is quite easy, only needs one smaller change…

```diff
diff --git a/src/olympia/files/tests/test_utils_.py b/src/olympia/files/tests/test_utils_.py
index 96f4ed975a..2cc36f7731 100644
--- a/src/olympia/files/tests/test_utils_.py
+++ b/src/olympia/files/tests/test_utils_.py
@@ -347,7 +347,7 @@ class TestManifestJSONExtractor(AppVersionsMixin, TestCase):
     def test_is_webextension(self):
         assert self.parse({})['is_webextension']

-    def test_allow_static_theme_waffle(self):
+    def test_detect_static_theme(self):
         manifest = utils.ManifestJSONExtractor(
             '/fake_path', '{"theme": {}}').parse()

@@ -355,7 +355,15 @@ class TestManifestJSONExtractor(AppVersionsMixin, TestCase):

         assert self.parse({'theme': {}})['type'] == amo.ADDON_STATICTHEME

-    def test_langpack(self):
+    def test_detect_static_theme_dark_theme(self):
+        manifest = utils.ManifestJSONExtractor(
+            '/fake_path', '{"theme": {}}').parse()
+
+        utils.check_xpi_info(manifest)
+
+        assert self.parse({'dark_theme': {}})['type'] == amo.ADDON_STATICTHEME
+
+    def test_detect_langpack(self):
         self.create_appversion('firefox', '60.0')
         self.create_appversion('firefox', '60.*')
         self.create_appversion('android', '60.0')
@@ -383,7 +391,7 @@ class TestManifestJSONExtractor(AppVersionsMixin, TestCase):
         assert apps[0].min.version == '60.0'
         assert apps[0].max.version == '60.*'

-    def test_dictionary(self):
+    def test_detect_dictionary(self):
         self.create_appversion('firefox', '61.0')
         data = {
             'applications': {
diff --git a/src/olympia/files/utils.py b/src/olympia/files/utils.py
index 8d612e72a4..3f9f607353 100644
--- a/src/olympia/files/utils.py
+++ b/src/olympia/files/utils.py
@@ -432,7 +432,9 @@ class ManifestJSONExtractor(object):
     def type(self):
         return (
             amo.ADDON_LPAPP if 'langpack_id' in self.data
-            else amo.ADDON_STATICTHEME if 'theme' in self.data
+            else amo.ADDON_STATICTHEME if any(
+                theme_type in self.data for theme_type in
+                ('theme', 'dark_theme'))
             else amo.ADDON_DICT if 'dictionaries' in self.data
             else amo.ADDON_EXTENSION
         )
```

On the other hand, this assumes that the static theme designer can be changed separately which I suppose it can and should be done in a separate issue in case product wants that?

**Comment by EnTeQuAk** [comment]
Support in Firefox got added in https://hg.mozilla.org/mozilla-central/rev/238bd73cdf0b759712c6b5ae8a73d77a930a0663 I think

**Comment by diox** [comment]
Are there docs about this? The thing that wasn't clear to me is whether you can have `dark_theme` without `theme`.

**Comment by eviljeff** [comment]
There are some other places that depend on the theme metadata being under the `theme` key though, so we'd need to change all of them to make things like the previews work.  The wizard too, as mentioned, would either have to be fixed to support the key, or throw up an appropriate error message.

(And, imo, the repack task shouldn't be left as is either - it should fixed preferably, or deleted otherwise - or we'll forget in the future about that edge case)
