### ISSUE TITLE
[Abuse report detail] A 500 error is triggered when trying to Save changes for a Deleted report

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11605]
Follow up for #11136 

**STR:**
1.  Log in to AMO with an admin account
2. Open the Abuse report model
3. Select an addon report from the list to view its details - see https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/24889/change/?_changelist_filters=modified__year%3D2019%26reason__isnull%3DTrue
4. Change the report state to Deleted and save your changes
6. Open the report detail again and hit Save

**Actual result:**
You receive a 500 error

**Expected result:**
Changes should be successfully saved
**Obs** - the list view lets you change the state of a Deleted report to Valid through the Action menu. There is no error triggered at this level, so the detail view should behave the same.

**Notes:**
- reproduced on -dev with Fx67, Win10x64

![2019-06-07_13-10-59](https://user-images.githubusercontent.com/31961530/59097363-065c8500-8926-11e9-8e6f-8547ca785a3f.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5883090/?query=is:unresolved

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

![2019-06-07_17-08-21](https://user-images.githubusercontent.com/31961530/59110143-1df83580-8947-11e9-96c0-b299cc6a584a.gif)
