### ISSUE TITLE
Change abuse report API file_uri add_install_method into file_url

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-server#11617]
Similarly to #11263, there is an additional tweak needed to match the value actually used in Firefox:

- the `file_uri` `addon_install_method` value [should actually be `file_url`](https://searchfox.org/mozilla-central/rev/0da35261b6789eec65476dbdd4913df6e235af6d/browser/base/content/browser.js#1166)
 
(QA didn't notice the mismatch yet, because installing an addon by drag and dropping an xpi file on the Firefox UI is likely not a super common scenario, and the automated tests landed on the Firefox side didn't catch this neither because they are unit tests and so they don't trigger an actual addon installation).

I filed [Bug 1558305](https://bugzilla.mozilla.org/show_bug.cgi?id=1558305) to fix the Firefox side of this issue (and we could actually translate the value from "file-url" to "file_uri" in the patch attached to that issue, but it would be likely clearer the matching between the two if we keep the two values as similar as possible).

@diox Let me know if this sounds reasonable to you too (and my apologies for not catching this when we applied the rest of the tweaks as part of  #11263)

**Comment by diox** [comment]
Totally fine, I'll change it.

**Comment by ioanarusiczki** [comment]
@diox 

<details>
<summary>file_uri - AMO stage, as it worked before </summary>


![AMO stage request and response JSON object](https://user-images.githubusercontent.com/33448286/59336767-da674800-8d07-11e9-929a-211abe43b4eb.png)


</details>

<details>
<summary>file_url, as it's been changed - AMO dev </summary> 

![AMO dev request and response JSON object](https://user-images.githubusercontent.com/33448286/59336852-05519c00-8d08-11e9-9269-6094eea7acd8.png)


</details>

Right now, file_uri is not a valid choice on both AMO dev and stage

![File  URI](https://user-images.githubusercontent.com/33448286/59336972-42b62980-8d08-11e9-8e58-5911be89ff38.png)
