### ISSUE TITLE
Support IP address masks for blocks

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11632]
From the [Account Submission Restrictions PRD](https://docs.google.com/document/d/1FfFcydrcm_TC4sQHXWQfJg2_11RvvYUANDy0hqMlH7U/edit#).

The admin tool should support using simple masks (like `127.0.0.*`) for IP address blocks.

**Comment by diox** [comment]
It (already) supports network masks instead, like /32 or /24. You can block `127.0.0.1/24` to block `127.0.0.*`.

**Comment by jvillalobos** [comment]
Okay. That should be sufficient, right? We can close this?

**Comment by diox** [comment]
I think so, though we spend a little time improving the UI if you want, to make the possibilities (and their consequences clearer - something like "You're about to ban all hosts from `127.0.0.1` to `127.0.0.254`).

**Comment by jvillalobos** [comment]
@muffinresearch mentioned that, and also the possibility of adding multiple entries in one go. I think he's going to file the missing issues.

**Comment by EnTeQuAk** [comment]
> @muffinresearch mentioned that, and also the possibility of adding multiple entries in one go. I think he's going to file the missing issues.

I'm just closing this issue then, the other issues should be separate issues then.
