### ISSUE TITLE
Port pre-fxa email domain blocks to new admin

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11633]
From the [Account Submission Restrictions PRD](https://docs.google.com/document/d/1FfFcydrcm_TC4sQHXWQfJg2_11RvvYUANDy0hqMlH7U/edit#).

We had a list of blocked email domains, which were all well known throwaway email providers. This was removed on the move to FxA (see https://github.com/mozilla/addons-server/pull/3589), and we should add them back to the new list.

**Comment by diox** [comment]
Unless we have a backup from before September 29, 2016, the data is gone. Maybe there is a static list somewhere that was used to seed the database back in the day though.

**Comment by diox** [comment]
There is a bug with the static list used to seed the database 9 years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=584490. The list is https://bug584490.bmoattachments.org/attachment.cgi?id=462909

**Comment by diox** [comment]
The table was never updated when the cod was live so the list we have is the final one we were using before we removed the table.

**Comment by diox** [comment]
https://gist.github.com/michenriksen/8710649 Also has a nice list of disposable email domains that should be more recent. @jvillalobos ok to add a migration to add all these plus our old ones into the new system ?

**Comment by jvillalobos** [comment]
Go for it!

**Comment by diox** [comment]
Note: I'm adding a new, separate model for that, to make it better for performance with thousands of entries. That model with only support domains (no need to enter the full email pattern), with no wildcards.

**Comment by AlexandraMoga** [comment]
Verified on stage  with the new [Disposable email domain restrictions](https://addons-internal.stage.mozaws.net/admin/models/users/disposableemaildomainrestriction/) tool. I've tried to submit add-ons from accounts using pre-existing domain blocks and I've also added new domain restrictions. In both scenarios, users were blocked on on the Developer agreement page.
