### ISSUE TITLE
Unlisted add-ons can't be installed because of a download failure

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11636]
**STR:**

1. Log in to AMO
2. Upload a new unlisted add-on
3. Once the submission is complete, try to install the add-on from the Manage status and versions page - see this example: https://addons.mozilla.org/en-US/developers/addon/f7cb7fff40f74f16a9c3/versions/4480185

**Actual result:**
The add-on is not installed because of a connection failure. There is a 404 in the console for `https://addons.mozilla.org/firefox/downloads/file/3024562/power_search_for_firefox-1.0.2-fx.xpi?src=devhub`
![image](https://user-images.githubusercontent.com/31961530/59409008-f2010800-8dbd-11e9-8b5b-253c93f427c4.png)

**Expected result:**
The add-on can be installed

**Notes:**
- reproduced on all AMO servers with Fx67 Win10x64 - NOT a regression from this week's (2019.06.13) milestone 

![2019-06-13_09-25-09](https://user-images.githubusercontent.com/31961530/59409098-2d033b80-8dbe-11e9-8050-1e03d7f648ca.gif)

**Comment by diox** [comment]
If you wait one hour, does it eventually work ?

**Comment by AlexandraMoga** [comment]
No, I'm still reproducing after > 4h

**Comment by diox** [comment]
The 404 in your console is weird...

In any case I can't reproduce :( I've just tried on prod and it's working fine for me with my own (fresh) unlisted upload (https://addons.mozilla.org/en-US/developers/addon/1ce3ea8f777c435cb9c1/versions/4480361). Also tried on dev and I didn't get the install because of certs but it did download ok when I chose "Save As".

**Comment by AlexandraMoga** [comment]
Did you upload a simple extension from webext generator by any chance?
I've also tried with one of those and it can be installed indeed:
https://addons.mozilla.org/en-US/developers/addon/c277e2efe2f84549bffa/versions/4480460

However, when I'm uploading a real extension with multiple files I'm getting the 404 at installation
Here is another example:
prod - https://addons.mozilla.org/en-US/developers/addon/8e280382a1124cfba524/versions/4480463
stage - https://addons.allizom.org/en-US/developers/addon/7bbd9b27a2e64d999de1/versions/2474817
