### ISSUE TITLE
Block adding new author to add-on based on display name

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11634]
From the [Account Submission Restrictions PRD](https://docs.google.com/document/d/1FfFcydrcm_TC4sQHXWQfJg2_11RvvYUANDy0hqMlH7U/edit#).

Similar to https://github.com/mozilla/addons-server/issues/11448, we should block adding authors to an add-on if they don't meet the display name requirement.

The error message (in the tooltip) should be "The account needs a display name before it can be added as an author."

**Comment by Abhi-khandelwal** [comment]
@jvillalobos Can I work on this issue ?

**Comment by jvillalobos** [comment]
I suggest you start with something from the [good first bugs list](https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt). This particular issue is part of the Q3 project, so it needs to be fixed fairly quickly. 

If you feel confident you can do it, I'm not going to stop you :), but maybe someone from the team will step in and resolve it faster.

**Comment by AlexandraMoga** [comment]
I've verified this on stage and have the following results:

1. adding a new author to an add-on is not possible unless the user has a display name set
![image](https://user-images.githubusercontent.com/31961530/62935146-00c06700-bdcf-11e9-83cf-d1717b070ff0.png)

2. authors with no display names which were added to an add-on previous to this restriction are not affected by this change. 
For example, I can have a co-author with no display name to one of my add-ons, save some changes in the `https://addons.allizom.org/en-US/developers/addon/<slug>/ownership` page and no error will be raised at the author level. 
@diox can you confirm if ^ is expected?

**Comment by diox** [comment]
Yes, the restriction only applies to new authors.
