### ISSUE TITLE
Abuse report for unlisted add-on sends nearly empty email

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11641]
The notification email I got for an unlisted add-on (https://github.com/mozilla/addons-server/issues/11640) was just this:

> An anonymous user reported abuse for TrackOFF (https://addons.mozilla.org).

We'll eventually move away from emails for this, but for the time being it'd be good that at least the URL is complete so it's possible to follow up on it. Showing the category text in the email is nice to have.

**Comment by AlexandraMoga** [comment]
Abuse reports for unlisted add-ons will trigger the following email format (as seen in Fake mail)

```
An anonymous user reported abuse for Power Search for Firefox (https://addons-dev.allizom.org/en-US/admin/models/addons/addon/502837/change/).

client_id => <reporters's client id>
addon_name => Power Search for Firefox
addon_summary => Optimized search results powered by Yahoo!
addon_version => 1.0.2
addon_signature => Signed
application => Firefox
application_version => 69.0a1
application_locale => en-US
operating_system => win
operating_system_version => 10.0
install_date => 2019-07-01 13:59:41.543000
reason => Wasn't wanted / impossible to get rid of
addon_install_origin => https://addons-dev.allizom.org/firefox/downloads/file/262307/power_search_for_firefox-1.0.2-an+fx.xpi?src=devhub
addon_install_method => Direct link
report_entry_point => Menu

abuse report for unlisted addons email
```
If the reporter in known, the display name and the email address will also be mentioned in the body.
