### ISSUE TITLE
Abuse report for unlisted extension doesn't appear in review pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11640]
I received a notification for an abuse report for an unlisted extension. I can see it in the [abuse reports page](https://reviewers.addons.mozilla.org/reviewers/abuse-reports/trackoff), but it doesn't appear in the [listed review](https://reviewers.addons.mozilla.org/reviewers/review/trackoff) or [unlisted review](https://reviewers.addons.mozilla.org/reviewers/review-unlisted/trackoff) pages. The listed review page does show the abuse report count and links to the abuse reports page, but I think it's expected for it to appear in summary form.

**Comment by jvillalobos** [comment]
Related to https://github.com/mozilla/addons-server/issues/11138

**Comment by diox** [comment]
I think it's because the summary only appears for auto-approved add-ons. Same for user ratings. I could remove that limitation if you want and have those appear all the time.

**Comment by jvillalobos** [comment]
Yes, I think it'd be best to show it all the time.

**Comment by AlexandraMoga** [comment]
The abuse report summary section is now present on an unlisted add-on review page, both for pure unlisted versions and for add-ons with mixed versions.
Theme review pages will also display the Abuse reports and the Bad User Ratings sections.

Examples:
1. pure unlisted add-on
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/2ffb1e9e78164a72b712

2. unlisted version of a mixed add-on:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/terms-of-service-didn-t-read

3. theme review page
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/the-moon-cat

@diox from what I understand, this patch should have also exposed the Bad User Ratings section on unlisted review pages. I've checked with several examples and this section was not present.
Listed review: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/terms-of-service-didn-t-read - summary of user ratings is present
Unlisted review: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/terms-of-service-didn-t-read - summary of user ratings is not present

**Comment by diox** [comment]
Forgot a code path, will fix.

**Comment by AlexandraMoga** [comment]
This looks fixed now. The ratings section is now present on the unlisted review page for the following add-ons:

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/files-compare
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/terms-of-service-didn-t-read
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/teamweek-button
