### ISSUE TITLE
Track add-on deletions in reviewer tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11652]
Part of [this project](https://docs.google.com/document/d/1pKVhUmLQck7iqrJIh67LQDD5CyCL6APPKShszqtRCHs/edit). [More details](https://docs.google.com/document/d/1p25gOexuGUgwhoOyGkWZPTfRi5yFs_JAmAiWBzR-gLY/edit).

The review page for an add-on should include a list of links to review pages for any previous add-on entries that were created for that same GUID. This probably involves creating a new column to link all entries for a GUID and backfilling that data for all add-ons that have been deleted and resubmitted.

**Comment by eviljeff** [comment]
Could of different options here:
- add an additional guid property on `Addon` (`persistent_guid` or something).
- add a new table that is an `addon`.`id` -> `guid` lookup
- add a table that is a list of `guid` and add a new foreign key on `Addon` that links to the table.  We could switch some other models that fk to `Addon` to fk to the `GUID` table instead.
- add a `duplicated_guid` table that's only used for deleted add-ons - i.e. we'd only add an add-on id to the table just before the guid was re-used by a new Addon instance.

The last option is probably the best for what we need, and doesn't need a column (or a record) for each Add-on.  The other options are probably a little more "correct" for a persistent GUID.

@wagnerand do you think any of these better or worse for redash queries?

**Comment by diox** [comment]
FWIW I'd like to avoid the extra field in `addons` table. I like the simplicity of the last option.

**Comment by wagnerand** [comment]
Could you sketch what the `duplicated_guid` table would include? How would that be different than approach 3 with FK a new table to `addon`.`id`?

**Comment by eviljeff** [comment]
`duplicated_guid`:
```
| id | guid | addon_id |
------------------------
|  1 | foo@ |      123 |
|  2 | foo@ |      456 |
[  3 | bar@ |      789 |
```
where `addons` would contain (among many others)
```
|  id | guid | status | ... |
-----------------------------
[ 123 | foo@ |     11 | ... |
[ 456 | foo@ |     11 | ... |
[ 469 | foo@ |      4 | ... |
[ 789 | bar@ |     11 | ... |
[ 790 | bar@ |      4 | ... |
```

> How would that be different than approach 3 with FK a new table to addon.id?

approach 3 is an FK on Addon, not an FK in a new table to Addon

```

**Comment by wagnerand** [comment]
Thanks. It seems approach 3 is not preferred, according to https://github.com/mozilla/addons-server/issues/11652#issuecomment-507757008.

I assume for performance reasons, we don't want to move `guid` out of `addons`. Also, using FK to `addons.guid` (being a string), is probably also not great for performance?

**Comment by eviljeff** [comment]
I'm not sure about the performance impact, but it would complicate any place where we we filter/count add-ons based on their guid.  Using a string as an FK is either something that isn't a thing in django, or something I don't want to think about being a thing :P

Perhaps if we were designing the models and devhub anew, knowing deleting and reusing guids would be possible (and common), it would make sense to have a persistent addon model containing the GUID (and maybe other fields) and then a per-instance addon model for any current details.  Or just a single non-deletable addon that properly supported things like per-version metadata.  But to fix just this issue, its arguably overkill.

**Comment by AlexandraMoga** [comment]
I've verified this on stage and the Previously deleted entries section will appear now if the `guid` of the reviewed add-on has been used in previous submissions. 

Here are some examples:
- https://reviewers.addons.allizom.org/en-US/reviewers/review/trustium-last-one
- https://reviewers.addons.allizom.org/en-US/reviewers/review/note-taker

Search tool review pages won't include this section since they do not have a `guid`

I've also found an inconsistency for which I filed #11857
