### ISSUE TITLE
Search results are not always bringing the correct 'last_updated' date

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11659]
**STR:**

1. Call the search api for the following add-on:
```
GET https://addons-dev.allizom.org/api/v4/addons/search/?guid=donottrackplus@abine.com
```
2. Check the `last_updated` date
3. Call the detail api for the same add-on:

```
GET https://addons-dev.allizom.org/api/v4/addons/addon/donottrackplus@abine.com/
```
4. Compare the `last_updated` date with the value brought by the search api

**Actual result:**
The `last_updated` dates for the detail and the search api do not match. The search api is not bringing the most recent update date:
search: ` "last_updated": "2019-06-12T08:38:58Z"`
detail: ` "last_updated": "2019-06-14T13:31:46Z"`

**Expected result:**
The search api should always bring the most recent update date

**Notes:**
- another example:
search:
`https://addons-dev.allizom.org/api/v4/addons/search/?guid=client@anonymox.net`
detail:
`https://addons-dev.allizom.org/api/v4/addons/addon/client@anonymox.net/`
search:
`https://addons-dev.allizom.org/api/v4/addons/search/?guid=gmailnoads@mywebber.com`
detail:
`https://addons-dev.allizom.org/api/v4/addons/addon/gmailnoads@mywebber.com/`

- I could reproduce this only on -dev - both with and without the recommended search waffle switch
- maybe worth mentioning that the examples provided were manually approved via the recommended review queue
- auto-approved add-ons do not seem to be affected
- on the frontend, the following search request will bring inaccurate results because of this:

https://addons-dev.allizom.org/en-US/firefox/search/?sort=updated

**Comment by diox** [comment]
This is probably just the indexing not being very reliable on dev because it has few workers and they get restarted all the time when we push new code.

**Comment by Abhi-khandelwal** [comment]
@diox Can I work on this issue ?

**Comment by diox** [comment]
This is low priority for us for now and we aren't sure what's going on yet. So if you can figure out everything entirely by yourself - both what's happening exactly and what's needed to fix it - yes. Otherwise, no.
