### ISSUE TITLE
Add-on status on DevHub doesn't reflect Recommended state

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11663]
On DevHub, a Recommended add-on only shows `Status: Approved`. It'd be good that it says `Status: Approved and Recommended` instead, so it's easier for developers to know the add-on is Recommended.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev - FF67(Win10). 

![approved and recommended](https://user-images.githubusercontent.com/33448286/60194061-56ea4280-9841-11e9-9c43-16180dc9af47.gif)
