### ISSUE TITLE
drop sort parameter for autocomplete

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11664]
we should always use relevance sort for addon autocomplete results

**Comment by ioanarusiczki** [comment]
@eviljeff 
My test results:
I tested with a couple of queries (I tried with those that would return a smaller number of results to see better if their order is different or not)
https://addons-dev.allizom.org/api/v5/addons/autocomplete/?q=iridium
https://addons-dev.allizom.org/api/v5/addons/autocomplete/?q=BDMP

Adding for -dev a [sort](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-search-sort) parameter such as 
https://addons-dev.allizom.org/api/v5/addons/autocomplete/?q=iridium&sort=hotness or any other (including `random` which previously was not available without `recommended`) will return the list of results in the same order as before (when I only used a `q`) which means that the `relevance` is always kept and the rest of the parameters are being ignored. 


dev - same order by `relevance`

![same order by relevance](https://user-images.githubusercontent.com/33448286/59931556-e5c81b00-944d-11e9-8e67-58f6d8e5333b.gif)

stage - different order depending on the sort type 

![stage - different order](https://user-images.githubusercontent.com/33448286/59931752-5d964580-944e-11e9-968a-6449b60ecc32.gif)

Let me know if there's anything else I should check on.
Thanks!
