### ISSUE TITLE
Intermittent HTTP 403 in AMO upload API

### ISSUE THREAD

**Issue by minj** [mozilla/addons-server#11675]
### Describe the problem and steps to reproduce it:
I am consuming the addon upload API manually.

```sh
amo_api_url="https://addons.mozilla.org/api/v3/addons/${FF_ADDON_ID}/versions/${VERSION}/"
curl -fg "${amo_api_url}" -XPUT --form "upload=@${XPI_PATH}" -H "Authorization: JWT $(generate_token)"
```

### What happened?
the cURL call started occasionally failing since June 18:

STDERR:
curl: (22) The requested URL returned error: 403 Forbidden

Headers:
HTTP/1.1 100 Continue
[1B blob data]

### What did you expect to happen?
the upload should just work™

### Anything else we should know?
This problem is intermittent, that is to say I am not sure why it happens only sometimes.

It failed when running builds on:
Tue Jun 18 11:06:11 UTC 2019
Thu Jun 20 11:25:04 UTC 2019

Running the command manually today failed at first as well. It then succeeded without the `-f` (fail flag), while the next try succeeded with the flag as well.

Maybe this fails only with some servers behind the load balancer, but not the others?

Normally there should be a HTTP 200 response after HTTP 100 but curl seems to fail before it is received. Presumably 403 is received instead but that is somehow not saved using header redirect? (`-D` option).

**Comment by diox** [comment]
Please look at the body of the response when you get a 403, it will indicate why you received it.

**Comment by muffinresearch** [comment]
I'm going to close this on the basis that the API response should tell you what's wrong. If you have further questions about it please re-open this issue.
