### ISSUE TITLE
Add on_commit hook for git extraction in sign_file

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11684]
Part of https://github.com/mozilla/addons-server/issues/11431

Make `sign_file` only call git-extraction when a transaction actually commits.

**Comment by EnTeQuAk** [comment]
Sentry issue: [OLYMPIA-PROD-2QW](https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5483678/)

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Please add some STR for qa or mark it qa not needed. 
Thanks!

**Comment by EnTeQuAk** [comment]
If signing works, this can be verified. The actual verification happens in production, making sure the linked sentry issue doesn't occur anymore.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I submitted an add-on on prod - https://addons.mozilla.org/en-US/firefox/addon/testing-git-extraction/
`byID: 2301517`

**Comment by EnTeQuAk** [comment]
All worked nicely and the sentry errors about https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5483678/?query=is:unresolved have completely disappeared.

So that helped and I can verify that it's working as expected.
