### ISSUE TITLE
Please add flattr.com to VALID_CONTRIBUTION_DOMAINS

### ISSUE THREAD

**Issue by da2x** [mozilla/addons-server#11680]
Please allow extension authors to solicit contributions through [Flattr](https://flattr.com).

Here are some examples of Flattr contribution links:

 * https://flattr.com/domain/noscript.net (the number #7 extension on AMO)
 * https://flattr.com/github/da2x
 * https://flattr.com/domain/fsfe.org

Here is the current whitelist:

https://github.com/mozilla/addons-server/blob/665d45df3d012a1c61003b028557dd44fc815a3c/src/olympia/constants/base.py#L218-L226

**Comment by diox** [comment]
@jvillalobos ok with that ?

**Comment by jvillalobos** [comment]
Yes!

**Comment by lavish205** [comment]
@diox can I work in this bug?

**Comment by eviljeff** [comment]
@lavish205 it's already fixed

**Comment by ioanarusiczki** [comment]
@eviljeff Verified on -dev - FF67(Win10)
flattr.com was added to Contributions URL in dev hub and works with all examples [above](https://github.com/mozilla/addons-server/issues/11680#issue-458939385)

![flattr com added](https://user-images.githubusercontent.com/33448286/60192874-55b81600-983f-11e9-9be8-e1b2fb5bd922.gif)
