### ISSUE TITLE
Submission on AMO stage cannot be completed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11694]
STR:
Go to Submit an add-on and upload an extension. 

expected result:
Uploading is validated and I can go to the next page with Continue.

actual result:
The upload is not completed. There is no validation and the Continue button stays greyed out. 

Notes:
Reproducible on AMO stage.
Not reproducible on AMO prod and dev.

![upload stage](https://user-images.githubusercontent.com/33448286/60078182-13ee7900-9734-11e9-8217-5c68ee571309.gif)

**Comment by EnTeQuAk** [comment]
I can reproduce this on -stage, one of the validation reports I produced was https://addons.allizom.org//en-US/developers/upload/f34200dddd1241f5a43628f576723037

I don't see anything in sentry so far

**Comment by bqbn** [comment]
I restarted celery processes in -stage environment. Please try it again.

Celery processes were OOM killed on one of 2 instances, and on the other instance, they died due to some underlying ec2 problem (not sure what it is yet).

**Comment by ioanarusiczki** [comment]
@bqbn Looks like it's working again.
