### ISSUE TITLE
Move frontend-only related ui-tests to addons-frontend test suite

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11691]
We discussed this in Whistler. Now that addons-frontend only serves the API, DevHub, reviewer tools and smaller other pages we should move all pure frontend related ui-tests to the addons-frontend test suite.

This should relate to `tests/ui/{test_home,test_search}` tests.

While we're at it, the `test_login` tests have been skipped for a very long time. Either revisit them and see if they can be moved and fixed or remove them altogether and create an issue to work on them separately.

`test_install` and `test_devhub` should stay in addons-server for now.

It can be done in a separate step but see if any of the test-setup data isn't needed for the remaining tests, if so, remove it.

When touching this, make sure to keep #11565 in mind and remove that test along the way (ideally this should be all separate steps / prs).

File separate issues as needed.

**Comment by suhailsinghbains** [comment]
Hi, Can I please work on this issue?
Thanks

**Comment by EnTeQuAk** [comment]
This is an assigned issue and not necessarily that is open for contributions. I'm sorry about that, but there's a whole list of other issues where contributions are very welcome! https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome

**Comment by suhailsinghbains** [comment]
Okay, thanks :)

**Comment by jrbenny35** [comment]
This depends on: https://github.com/mozilla/addons-server/issues/11565

**Comment by eviljeff** [comment]
Are there blockers on removing the ui-tests from addons-server now _before_ some subset of them have been re-added to addons-frontend? We'd lose test coverage on those tests in the mean time but it'd only be for a few weeks, right?

The code itself will remain in the git[hub] history for reference.

**Comment by jrbenny35** [comment]
@eviljeff the job on circleci can be disabled and I plan to move the tests soon. I don't think there is a problem leaving the code here for now until its moved as its pretty out of the way. If you want to disable the current job, I am okay with that

**Comment by jrbenny35** [comment]
I'll have to re-update ```pytest-xdist``` when the tests are moved.

**Comment by jrbenny35** [comment]
Done here https://github.com/mozilla/addons-frontend/pull/9018
