### ISSUE TITLE
remove lwt support in serializers

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11703]
We have specific support to return `theme_data` for LWT but with no LWT any more we can delete that code now.

**Comment by AlexandraMoga** [comment]
@eviljeff  is any QA required for this?
Thanks

**Comment by ioanarusiczki** [comment]
@eviljeff I've noticed on AMO stage that some empty previews are displayed right after making a blank search.  Clicking one returns a 404. 

![blank search ](https://user-images.githubusercontent.com/33448286/60676011-722f0080-9e86-11e9-8291-f0a8dc8ae18b.gif)

**Comment by eviljeff** [comment]
I think it just needed an ES reindex - I did dev myself and asked ops to do prod but stage wasn't reindexed after the remaining LWT were removed.
