### ISSUE TITLE
Do not bounce emails for spammers

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#11707]
### Describe the problem and steps to reproduce it:
Our email provider has reported that spammers are able to spoof sender addresses and have AMO bounce emails for them.

Please see details in https://bugzilla.mozilla.org/show_bug.cgi?id=1561413

This hurts our email reputation and can get us banned by ISPs.

### What happened?

See https://bugzilla.mozilla.org/show_bug.cgi?id=1561413 for details.

### What did you expect to happen?
We should not bounce emails from spammers. On the other hand, we should probably still allow valid email bounces to happen.

### Anything else we should know?
n/a

**Comment by muffinresearch** [comment]
Marking as P2, but if it's possible to get something in for next week that would be even better.

@eviljeff are you ok to take this on?

**Comment by muffinresearch** [comment]
"activity-email-bouncing" switch is now off in prod as a temporary measure.

**Comment by muffinresearch** [comment]
@eviljeff how viable is testing this in stage? Also presumably we need a note in the release docs to re-enable "activity-email-bouncing" assuming this tests out ok?

**Comment by eviljeff** [comment]
>how viable is testing this in stage? 

I suspect it's testing isn't viable because we don't how to force socketlabs to say an email is spammy.

> Also presumably we need a note in the release docs to re-enable "activity-email-bouncing" assuming this tests out ok?

I'll add a note.

**Comment by ioanarusiczki** [comment]
@eviljeff Can this be marked with qa not needed in this case? 
I don't think prod is accessible for qa either.
