### ISSUE TITLE
heading_text is not localized in discovery API response

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#11704]
### Describe the problem and steps to reproduce it:
The `heading_text` property of the discovery API response includes the English text.

### What happened?
Recommended extensions in about:addons are shown with an English heading and a localized description.

### What did you expect to happen?
Both the heading and description are localized.

### Anything else we should know?
https://services.addons.mozilla.org/api/v4/discovery/?lang=hsb
https://bugzilla.mozilla.org/show_bug.cgi?id=1559160

**Comment by diox** [comment]
Ah yeah, the text variant is missing the `ugettext` call when a `custom_heading` is set. I'll fix it.

**Comment by milupo** [comment]
Thank you diox. I'm the reporter of the Bugzilla bug 1559160.

**Comment by diox** [comment]
Will be fixed for production next week.

**Comment by AlexandraMoga** [comment]
@diox  on -dev, we've added several add-ons with a custom heading in [Discovery items](https://addons-internal.dev.mozaws.net/de/admin/models/discovery/discoveryitem/) over time, but those haven't been translated. 
I'm nor sure how I could properly verify this fix without some reliable data.

**Comment by diox** [comment]
You would need to add the exact strings used in prod (use what https://addons.mozilla.org/api/v4/discovery/editorial/ returns - pick a string currently being displayed in prod disco pane to have a higher chance of it being translated already)

**Comment by AlexandraMoga** [comment]
Thanks for the tip! I was able to verify with your method.

https://addons-dev.allizom.org/api/v4/discovery/?lang=de
```
"heading": "Verbessern Sie Videos <span>mit <a href=\"https://addons-dev.allizom.org/de/firefox/addon/axe-2/?utm_source=discovery.addons-dev.allizom.org&utm_medium=firefox-browser&utm_content=discopane-entry-link&src=api\">axe - DE von LexaDev</a></span>",
"description": "<blockquote>Deutsch - summary</blockquote>",
"heading_text": "Verbessern Sie Videos mit axe - DE",
"description_text": "Deutsch - summary",
```


I'm marking this issue as verified fixed on-dev.
