### ISSUE TITLE
500 errors received in Compare file for images

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11712]
Followup for https://github.com/mozilla/addons-server/issues/11639
STR:
1. Load a compare view such as 
https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/
https://code.addons.allizom.org/en-US/compare/1002795/versions/2474830...2474841
2. Open a folder that contains images and click a file such as https://code.addons.allizom.org/en-US/compare/1002795/versions/2474830...2474841?path=icon%2F176.png

Expected result:
No differences displayed 

Actual result:
Internal server error received for https://addons.allizom.org/api/v5/reviewers/addon/1002795/versions/2474830/compare_to/2474841/?file=icon/176.png&lang=en-US

Notes: 
this issue is reproducible on -dev and -stage - FF67 -Win10
I could not reproduce it with text files or in the versions page (browse view). 

![500 error compare view](https://user-images.githubusercontent.com/33448286/60162105-85482d80-9801-11e9-997f-ac6bd6ff3a07.png)

**Comment by ioanarusiczki** [comment]
I recently found another file which returns 500 
https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/?path=popup%2Ffonts%2Fglyphicons-halflings-regular.eot

**Comment by EnTeQuAk** [comment]
This will happen for all binary files. Fix is in progress

**Comment by EnTeQuAk** [comment]
This is related to https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5990131/

**Comment by EnTeQuAk** [comment]
This is heading to dev and stage, and will be cherry-picked for todays push.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Verified on -dev and -stage.

I receive a 200 Status with Postman with 
https://addons.allizom.org/api/v5/reviewers/addon/1002795/versions/2474830/compare_to/2474841/?file=icon%2F176.png
or https://addons-dev.allizom.org/api/v5/reviewers/addon/390151/versions/1688198/compare_to/1688302/?file=popup%2Ffonts%2Fglyphicons-halflings-regular.eot

No error message in code-manager either 

![the binary files ](https://user-images.githubusercontent.com/33448286/60667446-3be78600-9e72-11e9-8f36-40dba65bac6e.gif)
