### ISSUE TITLE
Add-on distribution agreement shows up for old accounts

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11729]
STR:
1. I signed in with an account that has submitted addons.
2. Clicked Submit an add-on

Expected result:
Distribution page is displayed.
https://addons.allizom.org/en-US/developers/addon/submit/distribution

Actual result:
Agreement page is displayed. 
https://addons.allizom.org/en-US/developers/addon/submit/agreement

Notes:
Reproducible on -dev and -stage FF67(Win10). 

![agreement](https://user-images.githubusercontent.com/33448286/60258510-f0673200-98dd-11e9-9d11-38b0b7778aec.png)

**Comment by diox** [comment]
That is expected since we changed the agreement last updated date.
