### ISSUE TITLE
Please return unchanged diff content starting on line 1

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#11739]
When a file has been unchanged we are now returning the entire content of the file in the `diff` of the response in the Compare API. Unfortunately the file content is starting on line 0, instead of line 1, which is causing some problems for the front end.

**Comment by kumar303** [comment]
This is causing keyboard navigation problems in addons-code-manager. Here are steps to reproduce the bug: https://github.com/mozilla/addons-code-manager/issues/887#issuecomment-506910356

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
All files I've checked on -dev  (files without changes) start their content at line one. 

Examples 
Compare API Reviewers - line one 
https://addons-dev.allizom.org/api/v5/reviewers/addon/495710/versions/1541610/compare_to/1688333/?file=src%2Fbrowse%2Fstyle.bundle.css

![First line is one](https://user-images.githubusercontent.com/33448286/60511096-d496ce00-9cd9-11e9-9b01-d633b7ef4ace.png)


Also, this is already visible in Code Manager 
https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688333/?path=src%2Fbrowse%2Fstyle.bundle.css
or
https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/?messageUid=ffde899897e94dbcb72c75c88985f5ba&path=popup%2Fjs%2Funderscore-min.js
