### ISSUE TITLE
Show add-ons pending review in content review queue

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11734]
To support https://github.com/mozilla/addons-server/issues/11653#issuecomment-506438252 we want to show add-ons pending review in the content review queue, not just auto-approved ones.

https://github.com/mozilla/addons-server/issues/11733 needs to be done beforehand so that is actually testable locally without blowing up...

**Comment by AlexandraMoga** [comment]
@diox so we want to only show the add-ons in the Content review queue, without the option to Approve or Reject content?

The reviewer will have the following options:
https://reviewers.addons.allizom.org/en-US/reviewers/review-content/project-delay-approval-no-3

![image](https://user-images.githubusercontent.com/31961530/60667492-51f54680-9e72-11e9-92ee-0b2a558d279b.png)


I've noticed that https://github.com/mozilla/addons-server/issues/11653#issuecomment-506438252 insinuates something about content rejection, but I'm not sure what was finally agreed upon.

**Comment by diox** [comment]
No, it should be possible to approve/reject content as well :(

**Comment by diox** [comment]
Handled in https://github.com/mozilla/addons-server/issues/11795
