### ISSUE TITLE
Mark reminder email about expiring information request as such

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11758]
### Describe the problem and steps to reproduce it:

It is not obvious to developers that the reminder email we send one day before information request expiry is indeed a reminder and not a separate issue.

### What happened?

The reminder email looks exactly like the original email (except the remaining number of days to reply).

### What did you expect to happen?

We should make it clear that the email is a reminder.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Vishal19111999** [comment]
Hey I am interested in solving this issue, please guide me.

**Comment by dbxnr** [comment]
Would it be sufficient to change the subject line of the email being sent, e.g. 'Reminder: Mozilla Add-ons: %s%s will be disabled on addons.mozilla.org' or would a new body template be better?

**Comment by eviljeff** [comment]
@wagnerand ^

**Comment by wagnerand** [comment]
> Would it be sufficient to change the subject line of the email being sent, e.g. 'Reminder: Mozilla Add-ons: %s%s will be disabled on addons.mozilla.org' or would a new body template be better?

Yes, that should be fine.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev.

The reminder email's subject is marked correspondingly:
- original email - [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/96107/change/)
- reminder email -  [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/96110/change/)
