### ISSUE TITLE
Normalize emails when checking restrictions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11755]
When we check an email in `EmailReputationRestriction` and `EmailUserRestriction`, we should normalize them by removing any `.` and everything after `+`. That will make restrictions more effective against variations of the same email address, since some email providers like gmail let you have multiple aliases that way.

For the reputation part, this will require the fraud pipeline to also apply the normalization before we can deploy this.

**Comment by AlexandraMoga** [comment]
@diox can this be verified only from Admin tools or do I need your help again when checking against the fraud pipeline?

**Comment by diox** [comment]
It applies to both the reputation check (using the fraud pipeline) and the email restriction check (that can be set from the admin). You can test using the latter

**Comment by AlexandraMoga** [comment]
I have verified several combinations, especially around gmail and it seems that the new restrictions are working.
Example:
If I'm blocking `parentemail@gmail.com` in admin Email user restrictions, the following variations will be also blocked:
`parent.email@gmail.com`
`parentemail+extrachars@gmail.com` 
`p.arentemail+extrachars@gmail.com`
`parent.email+extrachars+foo@gmail.com`

@diox we might run into some edge cases with other email domains that do not recognize variations from a parent email.
For example, if I'm blocking `johndoe@restmail.net`, this will automatically block `john.doe@restmail.net` as well, even though the accounts might be completely unrelated.

**Comment by diox** [comment]
>  For example, if I'm blocking johndoe@restmail.net, this will automatically block john.doe@restmail.net as well, even though the accounts might be completely unrelated.

Yes, I'm willing to live with that, we'll see how problematic it becomes. I'd like to avoid having to enable this for each email provider individually if we can.
