### ISSUE TITLE
Check each throttle class before returning a 429 response in signing view

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11765]
If a single throttling class disallows the request, the other throttling classes never see the request and it never gets added to their history. That means essentially the throttling classes after the first one that failed don't count some requests towards their limit.

I submitted an issue and pull request to DRF fixing this (https://github.com/encode/django-rest-framework/issues/6667), it was merged but hasn't been released yet, so let's backport it. 

See also #11393

**Comment by EnTeQuAk** [comment]
There is a new release that contains this fix out now.

**Comment by EnTeQuAk** [comment]
Actually, it might not be it yet… https://github.com/mozilla/addons-server/pull/11899#issuecomment-514906114

**Comment by EnTeQuAk** [comment]
https://github.com/encode/django-rest-framework/issues/6836 with upstream PR https://github.com/encode/django-rest-framework/pull/6837

**Comment by diox** [comment]
We just merged https://github.com/mozilla/addons-server/pull/12273 which updates our DRF to 3.10.3, and that should have both my patch and @EnTeQuAk 's fix.
