### ISSUE TITLE
Change email restriction error message

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11760]
Current message:
`The email address you used for your developer account is not allowed for add-on submission.`

@eviljeff's proposal:
`The email address used for your account is not allowed for add-on submission.`

**Comment by championshuttler** [comment]
Can i take this up @diox

**Comment by diox** [comment]
Sure. In addition to changing it in the class responsible for this, do look for the tests to update that try to match on the exact message.

**Comment by championshuttler** [comment]
Here you go @megha-kumarii

**Comment by wagnerand** [comment]
@megha-kumarii Hey, thank you for submitting a pull-request. Could you reply here so I can assign you, please?

**Comment by megha-kumarii** [comment]
✋ . @wagnerand thanks :)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/61274122-c5248400-a7b3-11e9-9cb8-77853aecea55.png)
