### ISSUE TITLE
The Content review queue is inaccessible on -dev and stage due to an increased number of pending items

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11767]
**STR**

1. Log in to AMO dev or stage with a reviewer account
2. Try to access the Content review queue - https://reviewers.addons.allizom.org/en-US/reviewers/queue/content_review

**Actual result:**
The content review queue has too many entries, exploring its contents is very difficult and most of the time I'm receiving a 504 when I'm trying to open it.

**Expected result:**
The content review queue is functional

**Notes:**
- it was pretty hard to check where all these new pending items where coming from, due to the 504s, but at a first glance it looks like all the migrated themes are now part of this queue - on stage, for example, there are 386052 pending items
- the regression could come from either https://github.com/mozilla/addons-server/pull/11750 or https://github.com/mozilla/addons-server/pull/11738

**Comment by diox** [comment]
Well #11738 was supposed to fix the perf issues making #11750 possible :) The increased number of items in there is expected, the 504 isn't...

**Comment by AlexandraMoga** [comment]
@diox is still don't understand why we would show migrated themes in the Content review queue, because it looks like they are the culprit for the increased number. 
This is one example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/groovy-pink

**Comment by diox** [comment]
When we migrated them, we didn't mark them has having gone through content review (content review didn't exist for LWT). Previously the queue would only show auto-approved items, but I removed that check because it's now also considering pending items. As a result, it's now showing all (public or pending) add-ons that haven't been through content review regardless of whether or not they went through auto-approval, and that includes the migrated themes.

You're right that it's causing the increase, and automatically mark them as having passed content review should work around the problem. There are still a couple issues with the query I need to look at, but that can be done later if we implement the workaround first.

**Comment by diox** [comment]
@AlexandraMoga I'm going to add a command to mark public migrated themes as content-reviewed, but I've also pushed to dev a fix for the perf issues in https://github.com/mozilla/addons-server/issues/11769 ; once this lands, can you check that dev works despite having 300k items in the queue ? Then I'll get rid of them.

**Comment by AlexandraMoga** [comment]
@diox on -dev we had only ~68k items in the the queue, because LWT were only partially migrated there. Stage has ~386k items though.

I was able to access the queue on -dev - no more 504 errors, I can switch pages, submit reviews etc. 
The loading times weren't very fast, but that might be improved (?) once you run the command to remove the themes.

**Comment by diox** [comment]
Ok I ran the script on dev, and it has reduced the number of items in the queue to ~ 26k. Loading times are still not fantastic but I think that should be enough for now.

**Comment by AlexandraMoga** [comment]
Interesting enough..the loading times, for me at least,  are even slower now that the themes have been removed.

**Comment by diox** [comment]
This is just because dev is unreliable. Database might be hot at one moment and cold at another.

**Comment by AlexandraMoga** [comment]
This can now be marked as verified fixed on both -dev and stage.
The Content review queue is functional, I haven't run into server errors and the pending items have been decreased significantly with the removal of static themes.
