### ISSUE TITLE
Most reviewer queries are going to the primary database instead of the replica(s)

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#11768]
If you monitor the processlist on both primary db and replica on stage, and load the reviewer tools, you'll notice that SQL queries made by reviewers coming from any review queue (and not the dashboard) will be made on the primary database, not the replica(s).

This is because, when you're viewing a queue, a POST is made via XHR to `/{locale}/reviewers/queue_viewing` every second, updating their page to tell them if someone is viewing specific add-ons in the queue they're looking at. That, in turn, causes us to set the `multidb_pin_writes` cookie over and over and over (`PinningRouterMiddleware` is responsible for this).

There is no good reason to continue doing this. We should set `_db_write=False` on `queue_viewing` response to prevent this from happening.

**Comment by diox** [comment]
Note: this is easily testable by looking at the storage tab of developer tools. That cookie is present, and comes back immediately after being deleted as long as you're on a queue page.

**Comment by diox** [comment]
> We should set `_db_write=False` on `queue_viewing` response to prevent this from happening.

That won't work, because the middleware always assume it should set the cookie if the method was not in `GET`, `TRACE`, `HEAD`, `OPTIONS`.

**Comment by diox** [comment]
STR:
- Log in as a reviewer and open a review queue page, like the auto approved queue
- Open developer tools

Expected results:
- `multidb_pin_writes` can be either present or absent, but its expiration date does not change while the queue is opened, and it doesn't flash yellow (which indicates it's being overwritten)

Actual results (before fix):
- `multidb_pin_writes` cookie is present, flashes yellow every second or two as it's being overwritten over and over again. Its expiration date keeps changing.

Note: in any case, if you inspect the developer tools network tab, a request should be made to `queue_viewing` every second or so approximately. You should also see in the page the lock icon for add-ons currently being viewed by another reviewer, and that icon should go away a short time after that other reviewer has closed the corresponding review page.

**Comment by AlexandraMoga** [comment]
I've verified the reviewer queues on -dev and I have the following results:
- `multidb_pin_writes` cookie is present but it's expiration date doesn't change while the queue is opened and it doesn't flash yellow
- the lock icon is present next to a queue entry if another reviewer has opened that particular review page; the lock disappears after a few seconds if the other reviewer closes the review page
- the warning messages in the add-on review page are displayed if another reviewer is watching the same add-on as your reviewer
- while a queue is opened, a GET request to `queue_viewing` is sent every ~1 second; previously this used to be a POST request

@diox I have some questions:

1. The new GET request will send all (200) add-on IDs present in the current queue page as request parameters? Is this correct?
![image](https://user-images.githubusercontent.com/31961530/74633906-64a35e00-516b-11ea-9924-086f6fcc15c4.png)

2. A POST request to `queue_viewing` is still made every ~8 seconds on an opened add-on review page. However, in this case, the  `multidb_pin_writes` cookie is not present. Should this POST request also be a GET or is this case different from the reviewer queues?

**Comment by diox** [comment]
1. Yes
2. That's different. You mean a request to `review_viewing`, not `queue_viewing` right ? That one should stay as a `POST`, because it serves both to check who's viewing and also to set yourself as the person currently reviewing this particular add-on.

**Comment by AlexandraMoga** [comment]
> You mean a request to `review_viewing`, not `queue_viewing` right ?

Yes, it's `review_viewing`. My bad.
