### ISSUE TITLE
Implement admin for Secondary Hero Shelf Blurb module

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11779]
Part of [this PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit#).

The Secondary Hero Shelf in the homepage will have a module with some text and a Call to Action on the left-hand side:

<img width="623" alt="Screen Shot 2019-07-03 at 4 22 47 PM" src="https://user-images.githubusercontent.com/62568/60628507-ee561500-9dae-11e9-840b-d64f60697694.png">

We need an admin tool for editing the contents of this module:

* Headline, up to 50 characters, localized
* Description, up to 100 characters, localized
* Call to Action, up to 20 characters, localized, optional
* URL, optional

The localization should work in the same way as the copy for Recommended extensions. The Call to Action and URL go together, so it shouldn't be possible to have one without the other.

The first version of this module will have similar content as currently on the homepage:
* Headline: "Extensions are like apps for your browser."
* Description: "They add features to Firefox to make browsing faster, smarter, or just plain fun."
* Call to Action: "See all extensions"
* URL: https://addons.mozilla.org/extensions/

**Comment by AlexandraMoga** [comment]
I've verified the Secondary hero shelf module on -dev and I've come up with the following test results:

- the module can be accessed and used  by admins and users from the Discovery Recommendations Editors group
- the `/secondaryheroshelf/add/` form follows the requirements:
  - Headline has a max length of 50 characters and is mandatory [1]
  - Description has a max length of 100 characters and is mandatory [1]
  - Call to action URL and text are optional, but you can't add one without the other for enabled shelves [2]
  - items can also be edited or deleted from the list

[1]
![image](https://user-images.githubusercontent.com/31961530/62623899-9faa1680-b92a-11e9-9ac0-dfdba3710759.png)

[2]
![image](https://user-images.githubusercontent.com/31961530/62623921-ab95d880-b92a-11e9-8d7e-4514746ffb52.png)

@eviljeff the `discovery/secondaryheroshelf/` landing page can be improved a little, so I filed #12056 as a suggestion.
