### ISSUE TITLE
Add metrics for account restrictions

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11771]
The goal here is to add metrics for when a restriction prevents an action. This way we can graph the number of restrictions over time.

**Comment by diox** [comment]
It can be useful, so I'll add it, but I think it'll be difficult to interpret. Failing a restriction check can happen at submission time, but also just when trying to get an API key. In addition, we'd log a failure every time the affected user reloads the page, re-submit their add-on, etc.
