### ISSUE TITLE
Record submission restriction failures

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11772]
We probably need to think about this rather than just implement it, but the idea here is to consider if we should store data when we're making restriction decisions so we can do other things with it later.

If we do this the data would need to be cleared out periodically but that's a separate issue.

**Comment by diox** [comment]
Doing this should help admins make decisions when they receive complaints by blocked users. There is a possibility that the tables storing the data might grow very fast, but hopefully the rate limits should prevent that from being too much of an issue.

Clearing data is covered by https://github.com/mozilla/addons-server/issues/11773

**Comment by ioanarusiczki** [comment]
@diox Is this recorded as a report in admin tools ? Please let me know if qa can verify this issue.

**Comment by diox** [comment]
Yes, it's in the admin for user profiles. When someone encountered any kind of restriction during upload they'll appear at the bottom of their user admin page (regardless of the source of the restriction - if it was something ip-based, it would appear for all accounts attempting an upload from a restricted ip)

**Comment by ioanarusiczki** [comment]
@diox I tested this issue on admin tools -dev with FF68(Win10). 

The `Developer Agreement Restriction` is always present in the reports. I've noticed that when the user is restricted the developer agreement will be displayed while making a submission every time (even if the user is not at the first submission).

I'll give an example for each scenario I've tested with:

**Ip network user restrictions (tested with 2 accounts)** https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641917/change/
**Email user restrictions** https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641915/change/
**Disposable email domain restrictions** 
https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641919/change/

My observations are:
- the ` View on site` won't direct to a page, it returns an Internal Server error (500). If it's really needed there (let me know) and then I should file an issue.

![500 error](https://user-images.githubusercontent.com/33448286/62781831-7b347280-bac1-11e9-89c8-8dd2b43aafbd.gif)

- I don't understand why the restriction type can be edited in the history. There is a drop down menu and I can replace one with another. 

![changing restriction](https://user-images.githubusercontent.com/33448286/62782908-dd8e7280-bac3-11e9-96a1-7012413078c4.gif)

- User Restriction Historys corrected to User Restriction History (it's an extra `s` there).

![historys](https://user-images.githubusercontent.com/33448286/62783045-378f3800-bac4-11e9-8405-25d32d1be318.png)

**Comment by diox** [comment]
> The Developer Agreement Restriction is always present in the reports. 

I guess we could technically skip recording that one, yeah. Can you file a follow-up?

> I've noticed that when the user is restricted the developer agreement will be displayed while making a submission every time (even if the user is not at the first submission).

This is normal / by design

> View on site won't direct to a page, it returns an Internal Server error (500). If it's really needed there (let me know) and then I should file an issue.

It's not needed, I'll fix that.

> I don't understand why the restriction type can be edited in the history. There is a drop down menu and I can replace one with another.

I forgot to make that readonly. I'll fix that.

> User Restriction Historys corrected to User Restriction History (it's an extra s there).

I noticed and figured it wasn't a big deal. It's kinda automatic, I'll fix it if I can override it but I'm not sure I can.

**Comment by ioanarusiczki** [comment]
@diox Sure, I'll file what you asked first thing Monday morning. 
Thanks for the quick review!

**Comment by ioanarusiczki** [comment]
@diox I verified this issue again on -dev with FF68(Win10). 
- The issues mentioned [above](https://github.com/mozilla/addons-server/issues/11772#issuecomment-519929293) were fixed. 
- I filed https://github.com/mozilla/addons-server/issues/12096 for no longer recording The Developer Agreement Restriction.
