### ISSUE TITLE
Support a "verified submitter" optional field to be shown in the installation doorhanger for signed add-ons

### ISSUE THREAD

**Issue by hackademix** [mozilla/addons-server#1177]
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1232311

Rationale:
1. We don't allow authors to sign their extensions anymore with their own code signature
2. The only guarantee we can make for signed add-on is that they've been submitted by an AMO account
3. We can and should, therefore, provide this information upon installation in an useful an unambiguous way (also because Chrome does provide per-developer signatures), at least for those add-ons which need it

This can be by supporting an _optional_ manifest field, e.g. "submitter", subject to the following restrictions, enforced upon signing:
a) Unique across authors in the AMO DB
b) Verified for "common sense" consistency (e.g. John Doe cannot use "Microsoft") by AMO's editorial staff
c) ASCII characters only to prevent Unicode homographic spoofing

jorgev's proposal for the "common sense" verification bit (b):
[We need] an option in the user management pages, where the user can request a submitter value, with a justification. An admin evaluates it and assigns the submitter value if everything's okay, and then the developer can use it. If a developer submits a version with an unassigned or incorrect submitter, it's auto-rejected with an explanation of how to request it.

**Comment by eviljeff** [comment]
@jvillalobos can you close this if it's not likely to be implemented in platform?

**Comment by jvillalobos** [comment]
Yeah, we can reopen if this becomes a priority on the client side.
