### ISSUE TITLE
Reviewers Browse API: Stop rendering content for binary files

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11782]
As discussed in #11759, we are currently sending content for binary files for the browse views but aren't generating fake-hunks for binary files in the compare view.

We should simply stop returning content for binary files completely and offer the user a download-link instead.

That'll also prevent us from unforeseeable security issues.

**Comment by bobsilverberg** [comment]
@EnTeQuAk Our code currently assumes that `content` will always be present as a property and also be a `string`, so if you can return an empty string for `content`, as opposed to `null` or a missing `content` property, we might not have to make any changes to the front end.

Does that sound like a reasonable approach to you?

**Comment by EnTeQuAk** [comment]
Works for me.

**Comment by bobsilverberg** [comment]
@EnTeQuAk As discussed at https://github.com/mozilla/addons-code-manager/issues/909#issuecomment-508736098, I think a server side change will resolve this for us, without requiring any front end changes, so you do not need to wait for any front-end changes to land this. I'm just going to verify that this morning, but for now assume this is unblocked.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev, both with the api and the code-manager.
The browse api is returning now an empty content - `content: ""` - for binary files:

These are some examples:
- https://addons-dev.allizom.org/api/v5/reviewers/addon/385621/versions/1655456/?file=META-INF/cose.sig
- https://addons-dev.allizom.org/api/v5/reviewers/addon/385621/versions/1655456/?file=img/FacebookLike.svg
- https://addons-dev.allizom.org/api/v5/reviewers/addon/385621/versions/1655456/?file=public/font/ProximaNova-Sbold-webfont.woff

There was an inconsistency observed in the code-manager with regards to `cose.manifest` files which seem to be rendered differently by the browse and compare api. I've filed #11856 to track this issue.
