### ISSUE TITLE
Extension appears twice when sorted by recently updated

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#1178]
The automated functional tests have picked up an issue on dev, where an extension appears twice when sorted by recently updated.

Here's a screenshot of the extension appearing on page one of the results:
https://addons-dev.allizom.org/en-US/firefox/extensions/?sort=updated&page=1

![page1](https://cloud.githubusercontent.com/assets/122800/12116268/75a3f42e-b3b0-11e5-9230-4f75fb6d3c32.png)

Here's a screenshot of the extension appearing on page two of the results:

![page2](https://cloud.githubusercontent.com/assets/122800/12116294/ae5ae6ce-b3b0-11e5-9edc-266760f69c10.png)

It appears that this has resolved itself in the time it's taken me to raise it, but I suspect the underlying issues is still present - there are now more recent extensions appearing, pushing the affected extension further down the results.

The affected automated test can be found here: https://github.com/mozilla/Addon-Tests/blob/b9cd1da7e6e649a7d144469532e1616a844df5d3/tests/desktop/test_extensions.py#L93-L106

**Comment by diox** [comment]
I think this is just a caching issue. We haven't seen it recently, so I'm going to close this bug.
