### ISSUE TITLE
Compare API returns 500

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11787]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/6015560/ for https://addons.mozilla.org/api/v5/reviewers/addon/9702/versions/2522724/compare_to/4442523/?lang=en-US (https://code.addons.mozilla.org/en-US/compare/9702/versions/2522724...4442523/)

**Comment by EnTeQuAk** [comment]
Kinda part of https://github.com/mozilla/addons-server/issues/11431 but some are separate, as such I'll keep them separate.
