### ISSUE TITLE
Themes should not be included in content review

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#11796]
Followup from #11792. Themes are now included in the content review, aside from migrated ones. As we have a different set of reviewers attending to themes, I feel it does not make sense to include themes in content review.

@jvillalobos, mat was mentioning there may have been a misunderstanding, can you confirm?

**Comment by diox** [comment]
While we're at it: do we want search engines, language packs and dictionaries in there ?

**Comment by wagnerand** [comment]
> While we're at it: do we want search engines, language packs and dictionaries in there ? I originally assumed yes, but maybe that was wrong.

I'd say yes to all of those.

**Comment by diox** [comment]
Yes we want to content review them or yes we want to exclude them from the content review queue ? :)

**Comment by wagnerand** [comment]
We want to content review:
* extensions
* dictionaries
* language packs
* search engines

We do *not* want to content review:
* themes (since they go through a different review process)

**Comment by jvillalobos** [comment]
You can remove language packs from that list, since third party ones are being discontinued.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
I've submitted a theme and a language pack and they are not listed in the Content review queue:

https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/content_review?page=30
