### ISSUE TITLE
Content review queue has too many items

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11792]
The content review queue has 437965 items. It seems the queue filter is not quite right.

We also got reports from reviewers that they can't content-reject some add-ons. Possibly because most of the entries are not actually pending content-review?

@diox

**Comment by diox** [comment]
Running `manage.py process_addons --task=content_approve_migrated_themes` should fix it.

**Comment by jvillalobos** [comment]
Looks like search engines and dictionaries (maybe other legacy types) are also showing up and weren't cleared.

**Comment by diox** [comment]
Yes, but technically if those show up it's because they should cause nobody reviewed them.

**Comment by bjherbison** [comment]
The number dropped to 6044, but has stuck in that range for a while. And the web site is still slow.

But the bigger problem now is I'm not allowed to content review.

There are a couple dozen new add-ons I'd like to reject, but I'm not allowed to reject them. The older add-ons I can reject (at all of the older add-ons I looked at), but I want to approve them and I didn't find any add-ons where the approve option was listed for me.

**Comment by kewisch** [comment]
It seems some of the themes are back, or the task has not run completely. This one shows up for example:

https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/the-beach-with-intense-sunset

I can also confirm B.J.'s comment, content reviewers are not able to reject normal add-ons. This one for example: https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/adobe-flash-player-jdek

Going to https://reviewers.addons.mozilla.org/en-US/reviewers/review/adobe-flash-player-jdek makes it reviewable.

**Comment by diox** [comment]
- Themes are now included in content review (not migrated ones). This might have been a misunderstanding, we'll clarify. There shouldn't be too many of them, only pending ones I think.
- The content rejection being impossible is weird. I'm guessing it's only for non-auto approved add-ons, but we should fix that.

Could you file separate issues for those things and close this one ?

**Comment by bjherbison** [comment]
I filed https://github.com/mozilla/addons-server/issues/11795 for content review.

**Comment by kewisch** [comment]
Thanks B.J., very helpful! Closing this issue in favor of the two we just opened.
