### ISSUE TITLE
Cannot sign my FF extensions

### ISSUE THREAD

**Issue by polarityimb** [mozilla/addons-server#11802]
Hi, starting in the beginning of June, we haven't been able to sign extensions.  Could it be related to the June 10th changes you made?

We really need to update our extensions, can you please help us figure out what's happening?  Here is the error we get:

403 Forbidden 
error: received bad response from the server while requesting ..

OR 

status: 403
response: {"detail":"Before starting, please read and accept our Firefox Add-on Distribution Agreement as well as our Review Policies and Rules. The Firefox Add-on Distribution Agreement also links to our Privacy Notice which explains how we handle your information."}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"connect-src 'self' https://sentry.prod.mozaws.net https://addons.cdn.mozilla.net; media-src https://videos.cdn.mozilla.net; default-src 'self'; font-src 'self' https://addons.cdn.mozilla.net; frame-src 'self' https://www.google.com/recaptcha/; script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://addons.cdn.mozilla.net; style-src 'self' 'unsafe-inl
ine' https://addons.cdn.mozilla.net; form-action 'self' https://developer.mozilla.org; child-src 'self' https://www.google.com/recaptcha/; object-src 'none'; base-uri 'self' https://addons.mozilla.org; img-src 'self' data: blob: https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; report-uri /__cspreport__","content-type":"application/json","date":"Fri, 05 Jul 2019 13:26:36 GMT","server":"nginx","set-cookie":["multidb_p
in_writes=y; expires=Fri, 05 Jul 2019 13:26:51 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Origin, Accept-Encoding","x-amo-request-id":"9f736f7c44ae4782bfd50ebeb334e3a8","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","content-length":"258","connection":"Close"}

The method we usually use for signing extensions is by .bat file.  
[accesoamicorreoelectronico_ntds-2.3-fx.zip](https://github.com/mozilla/addons-server/files/3367270/accesoamicorreoelectronico_ntds-2.3-fx.zip)

I am including a zip of the extension also.  What can we do?
Thank you.

**Comment by EnTeQuAk** [comment]
As the message is stating, `Before starting, please read and accept our Firefox Add-on Distribution Agreement as well as our Review Policies and Rules. The Firefox Add-on Distribution Agreement also links to our Privacy Notice which explains how we handle your information` - we changed our policies recently and that requires you to submit your next update through the developer hub and accept our updated developer agreement.

With that everything should work as expected afterwards.

I'm going to close this issue as it's not a bug but please feel free to reply and re-open anytime if there's more we can do.

**Comment by polarityimb** [comment]
Hi EnTeQuAk, thanks for your answer.
Where can we find the Firefox Add-on Distribution Agreement to accept?  We added an extension manually in our account in the developer hub, but it did not offer us the option to accept the new terms and conditions.  Can you please give me more details?  We need to be able to upload new versions of our old extension through the API, so it's not helping us to manually upload extensions through the portal.
Thank you so much and sorry if I missed something obvious.
Corina

**Comment by diox** [comment]
If you haven't agreed to the latest version, the developer agreement should be shown at upload time in devhub or when visiting the api keys page for the affected account.
