### ISSUE TITLE
Provide a way to list add-ons for a developer, including non-public add-ons

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#11803]
From a content review page for an auto-approve delayed add-on click an author name link.

Expected:
- Show a list of the add-ons for the author.

Actual:
- If all add-ons haven't been published the result is "Oops! We can’t find that page".

My current problem: The add-on I'm looking at looks like a dupe of one I approved a few hours earlier. I don't know whether the previous add-on was deleted by the author so I want to see all of the add-ons from this author to check, but I can't see any.

The individual add-on page will show me non-auto approved items with a banner "This is not a public listing. You are only seeing it because of elevated permissions.". I'd like to have something similar for authors: Here are all the add-ons, and here are the ones that aren't public.

It would also be useful if the page gave the approval status for the add-ons: Have the add-ons been content approved and have they been code approved. If an author has several new add-ons it is useful to look at them together as the problems (and corresponding requests) are often the same.

Current links (but these will change status in a day):
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/avro-plugin
https://addons.mozilla.org/en-US/firefox/addon/avro-plugin/
https://addons.mozilla.org/en-US/firefox/user/15119357/

**Comment by wagnerand** [comment]
I agree the review page should list all authors, including hidden ones.

**Comment by eviljeff** [comment]
> I agree the review page should list all authors, including hidden ones.

I'm reading the issue as a request to list all _addons_ for an author, including non-public ones, on the public account profile page.  We can't (won't) do that as it's a frontend page using the Addon API.  Potentially something could be added to the reviewer tools though?

**Comment by jvillalobos** [comment]
It might be handy to have a developer profile page for reviewers, showing all add-ons and their status, linking to their respective review pages. That's a bigger project, though, and it's not a problem that comes up often. I suggest wontfixing this.
