### ISSUE TITLE
Add canned response relationship to draft comments api

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11807]
Follow-up for https://github.com/mozilla/addons-server/issues/11374

Once draft comments are exposed we need to allow them to store relations to canned response data.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
With Postman I see that GET POST PATCH responses on dev return the "canned_response": null.

I can't tell what's the role of the `draft_comment.id` from [POST](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#drafting-comments) though. I made a POST such as
`{"comment": "testing the draft comment id",
 "draft_comment.id":29`}
The draft is created with `"id": 4` 
Is that as it should behave right now?

**Comment by kumar303** [comment]
@ioanarusiczki this appears to be a documentation error. I filed https://github.com/mozilla/addons-server/issues/12237 to fix it. I believe the correct param name is either `canned_response` or `canned_response_id`. Can you try that? Its value should be the ID of a canned response object returned by [this endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-canned-responses-).

**Comment by ioanarusiczki** [comment]
@kumar303 Sure, I'm on it today.
