### ISSUE TITLE
Support for pre-filled theme packages with Firefox Color.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#11804]
One feature Firefox Color team would like to have it to be able to open the theme submission form on AMO with the theme package already filled in for validation. That would give a very easy way for theme developers to submit their creation through AMO.

By checking https://github.com/mozilla/FirefoxColor/issues/93, some talks with the addons team was done in the past.

One solution here would be to fill those form parameters via an extension content script. Unfortunately, those are not allowed on addons.mozilla.org for security reasons. 

As such, to support this, some changed on AMO are probably required. I'm not sure however what would be the best approach to support such use-case.

Maybe this work could be done instead inside https://addons.mozilla.org/en-US/developers/addon/submit/wizard-listed . Note that this page doesn't support all the different properties that Firefox Color currently have (or will support in the future, such as sidebar theming).

**Comment by eviljeff** [comment]
There's no easy way to implement this.  Hooking directly into the developer hub flow is a very fragile solution - and would need changes to allow it.  

This _should_ be done via the signing API but a) an add-on where the first version is listed needs to be via devhub to collect extra metadata and b) submission requires a key from devhub which is impractical for a casual user of the FirefoxColor website.

@jvillalobos to decide if it's something to be considered for a secondary task in Q4.

**Comment by jvillalobos** [comment]
This is very low-priority. I think we would need to finish and ship the work from the [Content Optimization project](https://github.com/orgs/mozilla/projects/39) and consider enabling the API for first submissions, if only for Color themes. Even then it would be a stretch to think Color users would use this vs. generating and uploading an XPI.

**Comment by eviljeff** [comment]
I'm going to close this for now as it seems very unlikely we'll work on it.  It can be reopened if Product direction/priorities change.
