### ISSUE TITLE
Bulk-banning users times out

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11810]
### Describe the problem and steps to reproduce it:

Bulk-banning a bunch of users makes the admin instance respond with a timeout.

### What happened?

Timeout :(

### What did you expect to happen?

All bans go through without a timeout.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
@eviljeff if you have a chance to look at this when you're back that would be appreciated.

**Comment by eviljeff** [comment]
need some more detail here - is it any users or just specific ones?  And how many is "a bunch"?

**Comment by wagnerand** [comment]
Any users. Yesterday I tried with 80 and 120 (and for a test run even just with a dozen or so) and every time it timed out.

**Comment by muffinresearch** [comment]
@wagnerand when it times out what are you seeing? Nginx timeout or Django? Just wondering if any external config changes could have affected this?

**Comment by wagnerand** [comment]
I think it's an nginx timeout.

**Comment by muffinresearch** [comment]
I'm not seeing anything obvious in the nginx config repo, but maybe @bqbn could confirm?

**Comment by bqbn** [comment]
> Just wondering if any external config changes could have affected this?

There has no Nginx changes recently. Also we haven't touched Nginx configurations that may affect timing for a long time. Most changes we do for Nginx are route changes these days.

> I think it's an nginx timeout.

Could you provide any logs (from the browser's console for example) to help us investigate where the issue may happen? And which endpoint(s) were you hitting when you saw the timeout? Your source IP and approximate access time would be helpful too. Basically we'll need something that we can use to grep in Nginx logs to see what happens.

If as you said, even banning a dozen or so users leads to timeout, that doesn't sound to be quite efficient. Maybe we should consider doing the bulk banning in an asynchronous job (e.g. done by celery).

**Comment by eviljeff** [comment]
> If as you said, even banning a dozen or so users leads to timeout, that doesn't sound to be quite efficient. Maybe we should consider doing the bulk banning in an asynchronous job (e.g. done by celery).

I want to understand why it went from quick and efficient when it landed a few weeks to inefficient now.

**Comment by muffinresearch** [comment]
Before we try and spend time on fixing perf I think it would be good to make sure we're sure of where the problem lies.

- Is there a good way to see all sentry errors for just the admin instance?
- Is there a clear way to see metrics for just the admin instance we could also try and start adding some additional metrics to see what parts specifically are slow.
- Are we currently seeing any slow queries being logged related to these operations?

> Could you provide any logs (from the browser's console for example) to help us investigate where the issue may happen? And which endpoint(s) were you hitting when you saw the timeout? Your source IP and approximate access time would be helpful too. Basically we'll need something that we can use to grep in Nginx logs to see what happens.

@wagnerand next time you see this could provide @bqbn with some info so he can look for your logs.

**Comment by bqbn** [comment]
I'm confused how the banning-bulk-users operation is executed. Is it done by going to a specific web page (using the browser), or is it done by running a command (e.g. manage.py command) on the admin instance? If it's done via a web page, then it probably has nothing to do with the "admin instance" (at least not the "admin instance" in ops terminology). 

Assuming we're talking about the same "admin instance", then

> Is there a good way to see all sentry errors for just the admin instance?

The admin instance has the same app configs as other type of instances (such as services_web, olympia_web, versioncheck_web and etc.), so it uses the same SENTRY_DSN, which means sentry errors generated on this instance are sent to the same Sentry project as others.

> Is there a clear way to see metrics for just the admin instance we could also try and start adding some additional metrics to see what parts specifically are slow.

The admin instance has a `type` tag with the value `olympia_admin`, in datadog, you can filter metrics by that tag.

> Are we currently seeing any slow queries being logged related to these operations?

Not at this time. If ops gets a notice ahead of time next time, we can try watching the slow logs while banning operation is executed.

**Comment by wagnerand** [comment]
> Could you provide any logs (from the browser's console for example) to help us investigate where the issue may happen? And which endpoint(s) were you hitting when you saw the timeout? Your source IP and approximate access time would be helpful too. Basically we'll need something that we can use to grep in Nginx logs to see what happens.

Today at 4:33pm CEST I banned 65 users. The endpoint I am hitting was a POST request to https://addons-internal.prod.mozaws.net/en-US/admin/models/users/userprofile/ (GET parameters stripped). There are no console error messages (apart from a blocked JS by the page CSP, which should be unrelated). I am sending you the IP in private.

**Comment by bqbn** [comment]
According to the logs (which I shared in https://drive.google.com/drive/folders/1-gytPiNXs8_8PXMRqaTitXgMts0yvIy9) , it looks like the same request was tried 3 times.

```
1563287687.798 "-" "POST /en-US/admin/models/users/userprofile/?q=... HTTP/1.1" 504 176 "https://addons-internal.prod.mozaws.net" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0" 60.019 60.019 "-"
1563289017.652 "-" "POST /en-US/admin/models/users/userprofile/?q=... HTTP/1.1" 302 0 "https://addons-internal.prod.mozaws.net" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0" 7.208 7.208 "-"
1563289049.553 "-" "POST /en-US/admin/models/users/userprofile/?q=... HTTP/1.1" 403 4214 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0" 0.048 0.048 "3.66"
```

First request was 503 after 60 seconds, second request was 302 after 7.2 seconds and third request was 403 after 0.048 second.

It looks like the app was still doing its work when the second and third requests arrived.

The following errors appeared twice during the time period of the 3 requests.

```
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: Traceback (most recent call last):
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: yield
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: payload = encoder(data)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 70, in dumps
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: **dict(default_kwargs, **kwargs))
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: **kw).encode(obj)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: chunks = self.iterencode(o, _one_shot=True)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: return _iterencode(o, 0)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: return super(JSONEncoder, self).default(o)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: o.__class__.__name__)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: TypeError: Object of type 'set' is not JSON serializable
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: During handling of the above exception, another exception occurred:
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: Traceback (most recent call last):
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/django/http/response.py", line 252, in close
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: signals.request_finished.send(sender=self._handler_class)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: for receiver in self._live_receivers(sender)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: for receiver in self._live_receivers(sender)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/post_request_task/task.py", line 54, in _send_tasks_and_stop_queuing
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: task.original_apply_async(args=args, kwargs=kwargs, **extrakw)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/post_request_task/task.py", line 95, in original_apply_async
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: args=args, kwargs=kwargs, **extrakw)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 535, in apply_async
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: **options
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 728, in send_task
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: amqp.send_task_message(P, name, message, **options)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/celery/app/amqp.py", line 552, in send_task_message
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: **properties
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: compression, headers)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: body) = dumps(body, serializer=serializer)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: payload = encoder(data)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: self.gen.throw(type, value, traceback)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: reraise(wrapper, wrapper(exc), sys.exc_info()[2])
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: raise value.with_traceback(tb)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: yield
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: payload = encoder(data)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 70, in dumps
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: **dict(default_kwargs, **kwargs))
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: **kw).encode(obj)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: chunks = self.iterencode(o, _one_shot=True)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: return _iterencode(o, 0)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: return super(JSONEncoder, self).default(o)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: o.__class__.__name__)
Jul 16 14:35:14 ip-172-31-22-159 docker-addons-internal[4699]: kombu.exceptions.EncodeError: Object of type 'set' is not JSON serializable
```

It's not very clear to me why processing takes so much time by looking at the logs. It may be helpful to add more logs to help understand the progress of processing a little better.

**Comment by EnTeQuAk** [comment]
> The following errors appeared twice during the time period of the 3 requests.

Which is weird as the banning doesn't seem to make use of celery, but maybe some follow-up tasks are :thinking:

**Comment by wagnerand** [comment]
> According to the logs (which I shared in [drive.google.com/drive/folders/1-gytPiNXs8_8PXMRqaTitXgMts0yvIy9](https://drive.google.com/drive/folders/1-gytPiNXs8_8PXMRqaTitXgMts0yvIy9)) , it looks like the same request was tried 3 times.
> 
> ```
> 1563287687.798 "-" "POST /en-US/admin/models/users/userprofile/?q=... HTTP/1.1" 504 176 "https://addons-internal.prod.mozaws.net" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0" 60.019 60.019 "-"
> 1563289017.652 "-" "POST /en-US/admin/models/users/userprofile/?q=... HTTP/1.1" 302 0 "https://addons-internal.prod.mozaws.net" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0" 7.208 7.208 "-"
> 1563289049.553 "-" "POST /en-US/admin/models/users/userprofile/?q=... HTTP/1.1" 403 4214 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0" 0.048 0.048 "3.66"
> ```

@bqbn Can you double-check the GET parameters? I did several rounds of banning (different users)

**Comment by bqbn** [comment]
Oh, you can check the application logs in stackdriver BTW. Just following the instructions [here](https://mana.mozilla.org/wiki/display/SVCOPS/AMO+Dev+Resources#AMODevResources-Stackdriverlogging), go to the Prod env logging console, use `label:type:olympia_internal` as the filter, then you can see all the app logs from that instance.

Best part is you can watch the app logs in (almost) real time after submitting the banning command.

**Comment by eviljeff** [comment]
There aren't many places we use sets, but I noticed we were passing a `set` of addon ids to be re-indexed rather than a `list`.  And as celery json serializes it's parameters and json doesn't do `set`s this might be the error.  #11895

**Comment by eviljeff** [comment]
closing this for now; assuming the fix works.  Re-open if it's still timing out.
