### ISSUE TITLE
Flowchart of the submission process

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11815]
We'd like to document the full submission process and given the complexity of this process, it'd be interesting to draw a [flowchart](https://en.wikipedia.org/wiki/Flowchart).

Do we have documentation about the submission flow already? (I could not find anything).

We'd like a technical view of the submission process, like where does the upload file ends up, when it is parsed, when/how is addons-linter run, etc.

**Comment by wagnerand** [comment]
I think we do. I'll share the link with you.

**Comment by willdurand** [comment]
Thanks, I added some more info about which granularity we want.

**Comment by eviljeff** [comment]
@wagnerand are you sharing it offline?  Can we close this issue?

**Comment by willdurand** [comment]
> @wagnerand are you sharing it offline? Can we close this issue?

No, that's not exactly what we need.

**Comment by eviljeff** [comment]
https://docs.google.com/drawings/d/1zoYMuPPXad1VVgTn5NZQdHKFpcpgPHP43J5BfSLx2mY/edit

**Comment by tapaswenipathak** [comment]
Hello folks: Can I work on the ticket?

**Comment by EnTeQuAk** [comment]
Unfortunately this issue isn't really suitable for contributors. It has actually been mostly solved with https://github.com/mozilla/addons-server/issues/11815#issuecomment-516042311 and requires quite a lot of understanding of AMO and it's code.

Please take a look at other issues that have the [`contrib: welcome`](https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome) label.
