### ISSUE TITLE
Merge locales bn-BD and bn-IN into a single locale bn

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#11816]
We are going to merge the two locales into one to fully utilize the community resources. The plan is:

Dev:
- AMO creates a bn folder at repo
- Move bn-BD repo content to bn repo and confirm it's all there (bn-BD has more content in comparison)
- Remove bn-BD, bn-IN repos

Pontoon (l10n):
- Pontoon dev migrates the data to bn (this includes contributors histories)
- L10n PM confirms the update and closes this issue.

@entequak

**Comment by AlexandraMoga** [comment]
The https://addons.allizom.org/bn-BD/developers/ and https://addons.allizom.org/bn-IN/developers/ URLs are redirected to https://addons.allizom.org/bn/developers/
Also, manually selecting `বাংলা` from the languages list will load the `/bn/` locale

**Comment by peiying2** [comment]
> The https://addons.allizom.org/bn-BD/developers/ and https://addons.allizom.org/bn-IN/developers/ URLs are redirected to https://addons.allizom.org/bn/developers/
> Also, manually selecting `বাংলা` from the languages list will load the `/bn/` locale

@AlexandraMoga the same merge requests were completed for AMO linter and AMO Frontend. When all the codes are pushed to production, the behavior should be consistent.
