### ISSUE TITLE
Queue count of 'Other Pending Review' is too high.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11828]
### Describe the problem and steps to reproduce it:

The queue count of 'Other Pending Review' is 29 at the moment, but there are only 7 add-ons in that queue.

### What happened?

Wrong count of 'Other Pending Review'  in the reviewer tools

### What did you expect to happen?

Right count :)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
I thought this was left broken on purpose though - to get a warning that the auto-approve job is broken.

**Comment by wagnerand** [comment]
This is an insufficient way to check for and notice auto-approval failures. When that happened a few months ago, no one had been noticing for months and it's impossible to figure out from just that number if something is broken or not (since there can always be files that have just been submitted, waiting for auto-approval), and even if you assume something is broken, there is no way to see which add-on it is.

If we need a monitoring tool for auto-approval, it should be something else, not this.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev 
Add-ons pending for auto-approval are no longer counted in the Other pending review queue:

![image](https://user-images.githubusercontent.com/31961530/61285691-12135500-a7ca-11e9-8806-8cc2b7106c8a.png)
