### ISSUE TITLE
[Review Tools] Review Log not Loading

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#11820]
ref: `https://reviewers.addons.mozilla.org/en-US/reviewers/reviewlog`

**Review Log** has been slow-loading for a very long time, For the last couple of weeks or so, I am hardly ever able to load the page and 95% of the times I end up with a blank page.

The only time I recall it loading in recently was on the 1st of July when there were only a handful entries for the month.

HTTP response status code: 504 (119777 ms)
favicon.icon response code: 404

@wagnerand

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/11902

**Comment by diox** [comment]
It's better now, but still not great. Forward-duping to https://github.com/mozilla/addons-server/issues/12055 which would make it a lot faster.
