### ISSUE TITLE
about:addons: doesn't list all add-ons from https://addons.mozilla.org/en-US/firefox/search/?recommended=true&type=extension

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#11839]
### Describe the problem and steps to reproduce it:
Visited about:addons in Firefox 68.0.

### What happened?
Found some add-ons in the new "Recommendation"

### What did you expect to happen?
I expected all add-ons from [Recommended](https://addons.mozilla.org/en-US/firefox/search/?recommended=true&sort=users&type=extension) to be listed, at least when I hit the "Find more add-ons" button at the bottom of the page -- "Firefox only recommends that meet our standards for security and performance".

### Anything else we should know?
I think most people would find it useful if you included these add-ons should be included in the list or at the Extension tab under the "Recommended Extensions" section at about:addons if you want to keep a shorter list there:

* [Decentraleyes](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/)
* [HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) -- it's already integrated in some Firefox-based browsers.
* [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) -- Adblock Plus doesn't meet AMO's Recommendation guidelines ("Firefox only recommends that meet our standards for security and performance").
* [Zoom Page WE](https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/) -- accessibility software

**Comment by eviljeff** [comment]
The discovery pane (the first page you see on about:addons) is showing a subset of recommended add-ons (and has for a number of years) and the "Find more add-ons" button just goes to the addons.mozilla.org homepage, which is also only showing recommended add-ons.  So I'm not clear what isn't as expected.  Can you provide a screenshot and urls for the links out of about:addons?

**Comment by davidhedlund** [comment]
![Screenshot at 2019-07-15 22:59:28](https://user-images.githubusercontent.com/6416073/61248942-64b22a00-a754-11e9-8e6d-fbc0e23e4c71.png)

![Screenshot at 2019-07-15 23:00:27](https://user-images.githubusercontent.com/6416073/61248956-6a0f7480-a754-11e9-8792-bb3358b896c1.png)

![Screenshot at 2019-07-15 22:59:53](https://user-images.githubusercontent.com/6416073/61248963-6c71ce80-a754-11e9-991d-be4c8e986c10.png)

**Comment by eviljeff** [comment]
@davidhedlund what are the screenshots showing exactly?  The add-ons shown all appear to be recommened add-ons.

**Comment by davidhedlund** [comment]
The "Find more add-ons" link is
* https://addons.mozilla.org/en-US/firefox/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=find-more-link-bottom but it should be
* https://addons.mozilla.org/en-US/firefox/search/?recommended=true&utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=find-more-link-bottom (note "recommended=true")

**Comment by eviljeff** [comment]
so... the issue is that you think the "Find more add-ons" button/link should point to the search, showing recommended add-ons, rather than the homepage, which only shows recommended add-ons?

If so, the discovery pane is actually generated directly in Firefox from 69 onwards, using the AMO API, so it'd be a Firefox change rather than AMO.  Calling @atsay rather than asking the request to be refiled on bugzilla and possibly closed again.

**Comment by davidhedlund** [comment]
> so... the issue is that you think the "Find more add-ons" button/link should point to the search, showing recommended add-ons, rather than the homepage, which only shows recommended add-ons?
> 
> If so, the discovery pane is actually generated directly in Firefox from 69 onwards, using the AMO API, so it'd be a Firefox change rather than AMO. Calling @atsay rather than asking the request to be refiled on bugzilla and possibly closed again.

Thanks. The "[Find more add-ons](https://addons.mozilla.org/en-US/firefox/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=find-more-link-bottom)" link and text should be changed to "[Find more recommended add-ons](https://addons.mozilla.org/en-US/firefox/search/?recommended=true&utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=find-more-link-bottom)"

**Comment by atsay** [comment]
This is working as intended. Everything on the homepage is part of Recommended Extensions.

**Comment by davidhedlund** [comment]
> This is working as intended. Everything on the homepage is part of Recommended Extensions.

![Screenshot at 2019-07-15 23:00:27](https://user-images.githubusercontent.com/6416073/61314468-f37a8180-a7fc-11e9-9e7e-26fdd29f255a.png)

Shouldn't the text and link "[Find more add-ons](https://addons.mozilla.org/en-US/firefox/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=find-more-link-bottom)" be replaced with "[Find more recommended add-ons](https://addons.mozilla.org/en-US/firefox/search/?recommended=true&utm_source=firefox-browser&utm_medium=firefox-browser&utm_content=find-more-link-bottom)" -- it's on the "Recommendations" tab after all.

**Comment by atsay** [comment]
The intention is that everything on the tab is recommended, but if you want to find more extensions you can go to AMO. In this context it made sense to take people to the homepage so they can browse the full library. It's true that everything on the homepage is also recommended, and that's to make it more likely to discover content from the Recommended program. From there, you can find anything that's available on AMO.

**Comment by davidhedlund** [comment]
> The intention is that everything on the tab is recommended, but if you want to find more extensions you can go to AMO. In this context it made sense to take people to the homepage so they can browse the full library. It's true that everything on the homepage is also recommended, and that's to make it more likely to discover content from the Recommended program. From there, you can find anything that's available on AMO.


![Screenshot at 2019-07-15 22:59:28](https://user-images.githubusercontent.com/6416073/61324083-dbf9c380-a811-11e9-8e89-b1ba37133ca1.png)

The tab says
> "Here’s a selection Firefox recommends for exceptional security, performance, and functionality."

I think most people would find it useful if you included these add-ons should be included in the list or at the Extension tab under the "Recommended Extensions" section at about:addons if you want to keep a shorter list there:

Most people would find these add-ons very useful. Can you please list them in addition?:
* [Decentraleyes](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/)
* [HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) -- it's already integrated in some Firefox-based browsers.
* [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) -- Adblock Plus doesn't meet AMO's Recommendation guidelines ("Firefox only recommends that meet our standards for security and performance").
* [Zoom Page WE](https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/) -- accessibility software

**Comment by devaneymoz** [comment]
@davidhedlund If I'm understanding you properly, you're suggesting Decentraleyes, HTTPS Everywhere, uBlock Origin, and Zoom Page WE should be Recommended extensions? They actually in fact are already part of the Recommended program. If you were to go to each of their respective listing pages on AMO, you'll find the "Recommended" label applied to the,
