### ISSUE TITLE
Drop MonthlyPick model and zadmin integration

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11832]
Now that all the legacy pages are actually gone, we can start cleaning up some models.

Let's drop `MonthlyPick` model and it's zadmin integration accordingly.

It seems unused from what I can tell.

**Comment by Abhi-khandelwal** [comment]
HI @EnTeQuAk can I take this issue?

**Comment by EnTeQuAk** [comment]
absolutely! Let us know if you need any more hints about what should be done.

If you start working on the issue we'd appreciate you telling us so that we can assign the issue to you.

**Comment by Abhi-khandelwal** [comment]
yeah sure, i would happily like to work on this issue

**Comment by EnTeQuAk** [comment]
You're assigned, let us know if you need any help. Generally, everything regarding / using the `MonthlyPick` model should be able to be removed. Regular code and unittests.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk does this require any QA?
Thanks
