### ISSUE TITLE
Implement admin for Primary Hero Shelf

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#11830]
Part of [this PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit#).

The Primary Hero Shelf in the homepage will feature one extension, chosen from a subset of Recommended extensions:

<img width="623" alt="Screen Shot 2019-07-03 at 4 02 16 PM" src="https://user-images.githubusercontent.com/62568/60627685-16904480-9dac-11e9-8d5b-438676aeeb44.png">

Since this will only work with Recommended extensions, it seems sensible to extend the admin we already have for it.

For the admin of a Recommended extension, add:

* Featured Image, chosen from a pool of predetermined images.
* Background color, used for the gradient.
* Featured on Primary Hero Shelf, checkbox that adds or removes the extension from the set. The checkbox shouldn't be toggled on if the other two properties haven't been set, or if the extension is only in the Recommendable state. There should always be at least one extension with the checkbox turned on.

**Comment by jvillalobos** [comment]
The background color will be chosen from a fixed palette, to be provided by @brassy- here.

**Comment by jvillalobos** [comment]
It should also be possible to feature _unlisted_ Recommended extensions in the homepage (and we most likely will at launch). The Call to Action will point to the homepage URL, so having one set should be another requirement to enable the checkbox in the admin, for unlisted ones.

**Comment by eviljeff** [comment]
> It should also be possible to feature unlisted Recommended extensions in the homepage (and we most likely will at launch).

Okay, we could have an additional setting which would mark the item as referring to an unlisted-only add-on and then frontend would know to display it differently.

Unlisted versions can't be approved for recommended though, currently, so it's not possible to have an add-on without a listed version be recommended  - that's #11284.   (And we'd be referring the user to an install that wouldn't be marked in Firefox as recommended)

**Comment by eviljeff** [comment]
> The background color will be chosen from a fixed palette

would this be defined by two colours if it's for a gradient (a start and an end colour)?

**Comment by bobsilverberg** [comment]
> > The background color will be chosen from a fixed palette
> 
> would this be defined by two colours if it's for a gradient (a start and an end colour)?

What I recall from the last meeting we had is that there will always be a single color that represents the start of the gradient, and then each gradient will be defined as having a different end color. If that is the case then the user would only need to choose one color for the gradient (the end color). 

Can @jvillalobos and/or @brassy- confirm or deny this?

**Comment by eviljeff** [comment]
The start and end colours will both need to be defined somewhere though, I assume.  As the API would be returning one colour value I thought it may as well return both.  I think we're basically blocked on someone telling us at least one "gradient", and we can see how it's best represented (to the user the admin; and in the api., which may be different)

**Comment by bobsilverberg** [comment]
> The start and end colours will both need to be defined somewhere though, I assume. As the API would be returning one colour value I thought it may as well return both. I think we're basically blocked on someone telling us at least one "gradient", and we can see how it's best represented (to the user the admin; and in the api., which may be different)

It does seem like the API should return both colors, and then they only ever need to be defined in one place (the server).

**Comment by brassy-** [comment]
Meanwhile, here the 5 different gradients. The colors are coming from the new brand palette.

![ink80blue70](https://user-images.githubusercontent.com/6309827/61632831-11793380-ac8e-11e9-9f1f-0fbaf0c82425.png)
![ink80green70](https://user-images.githubusercontent.com/6309827/61632832-11793380-ac8e-11e9-8836-71297fac22c8.png)
![ink80pink70](https://user-images.githubusercontent.com/6309827/61632834-11793380-ac8e-11e9-9293-c232cf11bc7f.png)
![ink80purple70](https://user-images.githubusercontent.com/6309827/61632835-11793380-ac8e-11e9-8199-b177c3a2a848.png)
![ink80violet70](https://user-images.githubusercontent.com/6309827/61632836-1211ca00-ac8e-11e9-86ca-8c6eeec243ca.png)

**Comment by eviljeff** [comment]
alright, unblocked!

**Comment by AlexandraMoga** [comment]
I've verified on -dev the Primary Hero section added to https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/116/change/ and I have the following results:

- only add-ons with a Recommended state can be selected for the primary hero shelf; all other states will trigger the following error:
![image](https://user-images.githubusercontent.com/31961530/62125223-347e9580-b2d5-11e9-8556-f018a858ad36.png)
- primary shelf entries can be enabled, disabled or deleted by marking the corresponding checkbox
- the user can choose from a predefined pool of images and gradient colors to customize the add-on promoted
- the primary hero can't be Enabled unless an image and a gradient have been chosen
![image](https://user-images.githubusercontent.com/31961530/62126036-7d374e00-b2d7-11e9-8900-07dad37dcf58.png)
- the Discovery items list has a dedicated column which will show which add-ons are enabled at a given moment

![image](https://user-images.githubusercontent.com/31961530/62126385-39911400-b2d8-11e9-8563-e8d2d1215b00.png)
