### ISSUE TITLE
Broken locale

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11833]
```
>>> Working on: /home/travis/build/mozilla/addons-server/locale/th/LC_MESSAGES/django.po
E201: invalid variables: {collection}
753:msgid "{addon} migrated from preliminary."
754:msgstr "{addon} ถูกเอาออกจาก {collection}"
```

But that string didn't change in the latest locale commit (https://github.com/mozilla/addons-server/commit/4de2828e68708f26ff473149924f4c67745d4547#diff-f69e969b065a0a64c1d68b1b90778d89R754). Did this change in master and pontoon is using old strings?

**Comment by wagnerand** [comment]
P2 as it breaks travis.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk does this need QA?
https://addons-dev.allizom.org/th/firefox/ doesn't seem to be broken.

**Comment by EnTeQuAk** [comment]
Actually no, this has already been verified by succeeding travis and circleci tests.
