### ISSUE TITLE
Review page shows wrong previously deleted add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11848]
### Describe the problem and steps to reproduce it:

1. Submit a search plugin
2. Check the review page for that search plugin.

### What happened?

The page shows lots of unrelated entries for "previously deleted add-ons"

![](https://irccloud.mozilla.com/file/z7XFVSi8/Screenshot%202019-07-17%20at%2012.46.35.png)

### What did you expect to happen?

No unrelated entries.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This is actually causing https://github.com/mozilla/addons-server/issues/11845, so I'm bumping up priority.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage:

Search tools review pages are not displaying previously deleted versions anymore:

https://reviewers.addons.allizom.org/en-US/reviewers/review/wikipedia-ita-8

![image](https://user-images.githubusercontent.com/31961530/61434192-f761ed00-a93d-11e9-9b62-10a92d690cb4.png)
