### ISSUE TITLE
504 nginx error received when trying to open a search tool review page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11845]
**STR:**

1, Try to load the following search tools review page - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/google-video-dev

**Actual result:**
The page is not loaded and after some waiting time a 504 is received

**Expected result:**
Search tool review page can be opened

Notes:
  - reproduced constantly on -dev with every search tool review page

![image](https://user-images.githubusercontent.com/31961530/61306238-e8235800-a7f4-11e9-90eb-786d9c44f5e5.png)

**Comment by eviljeff** [comment]
might be a regression from #11843

**Comment by wagnerand** [comment]
> might be a regression from #11828

I don't believe so. Lots of pages on dev show timeout issues at the moment, for example the auto-approved queue or the review log.

**Comment by AlexandraMoga** [comment]
Reproducing in stage now. I repeat, only when I'm trying to open a search tool review page I run into constant 504s: 
https://reviewers.addons.allizom.org/en-US/reviewers/review-content/wikipedia-ita-5

Then, if I'm trying to access any other page immediately after the above request 504's, other pages will timeout too. 

Moreover, the frontend (addons.allizom.org) will not load correctly after these timeouts: sometimes it looks like it's trying to load the discopane (1st screenshot) and on other occasions it tries to open the code-manager (2nd screenshot).  Note that the frontend issues might be intermittent. 
[1]
![image](https://user-images.githubusercontent.com/31961530/61356444-0b92e500-a87f-11e9-8007-9fbe41e1361d.png)

[2]
![image](https://user-images.githubusercontent.com/31961530/61356460-151c4d00-a87f-11e9-92e1-62aeadaa1f05.png)

**Comment by wagnerand** [comment]
I am unable to reproduce this locally.

**Comment by EnTeQuAk** [comment]
So, while loading the page the mysql process list doesn't show any long running queries at least (I don't have access to the slow logs though.

**Comment by EnTeQuAk** [comment]
Theme reviews seem to be accessible properly on -stage. Also, loading the whole content-review queue is super slow - it's huge unfortunately so that might be a reason too.

**Comment by wagnerand** [comment]
This landed on -dev. The page mentioned in the original comment loads fine for me now.

**Comment by AlexandraMoga** [comment]
I've opened several search tool review pages and I can conform the error can't be reproduced anymore
I'm marking this as verified fixed on -dev.
