### ISSUE TITLE
Add param to filter the /api/v4/discovery/editorial/ to only show add-ons with a recommended status.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#11851]
See also https://github.com/mozilla/taar/issues/157

To support moving TAAR to be base of only add-ons in the Recommended Extensions (RecEx) programme, we need to add a param to the /api/v4/discovery/editorial/ so that it only shows add-ons with a recommended status. That is not just "recommendable" but add-ons that are approved and have latest recommended signed version.

For example:

 `/api/v4/discovery/editorial/?recex=true`

Would show only RecEx add-ons.

Without this param would show everything. The latter will be useful for getting a head start on translations ahead of the recommendations process being completed.

Once TAAR is using the filtered list, non-recommendable content could be cleaned up by editorial.

At the same time as fixing this bug, it would also be good to fix the documentation to reflect that this end point is used for both translations and a source for TAAR.

**Comment by mlopatka** [comment]
@crankycoder Can you make sure that when the parameter on which to filter is landed, TAAR is filtering on that parameter with as little lag as possible.

**Comment by crankycoder** [comment]
@muffinresearch i'm putting in a patch to the python_mozetl job to use the `recex` option.

**Comment by eviljeff** [comment]
We use `?recommended=true` elsewhere in the API so I'd go with that for the parameter for consistency.

**Comment by crankycoder** [comment]
@muffinresearch https://github.com/mozilla/python_mozetl/pull/334 is ready to be merged. I'd like to wait until addons-server code lands so that we can make sure that the new `recommended` parameter matches up properly.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
When calling `/discovery/editorial/?recommended=true`, only the add-ons that have a `Recommended` state in Discovery items will be returned.
