### ISSUE TITLE
 Previously deleted entries should link to review pages that match the version distribution method

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11857]
**STR:**

1. Create an add-on with a custom guid
2. Submit it on AMO as an unlisted version
3. Delete the add-on
4. Submit the same package again as a listed version
5. Open the listed review page for this add-on and look at the Previously deleted entries section - see https://reviewers.addons.allizom.org/en-US/reviewers/review/note-taker
6. Click on one of the previous unlisted entries - https://reviewers.addons.allizom.org/en-US/reviewers/review/1002861
7. Check the Add-on History section

**Actual result:**
The Add-on History is empty because the link is trying to open a listed review page - `/reviewers/review/1002861`, when, in fact, the selected entry existed only as an unlisted add-on

**Expected result:**
The entry link should point to https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1002861, where the Add-on History is populated

**Notes:**
- the Add-on history can provide valuable information, such as Validation results, access to the code-manager, Permissions etc, so it would be good to map the entry links according to the add-on distribution method
- this can also be reproduced the other way around, namely when you are trying to access the review page for a previously listed entry, while being on an unlisted add-on review page

![2019-07-18_13-11-36](https://user-images.githubusercontent.com/31961530/61449714-32741880-a95e-11e9-97a7-2497cbfa50f7.gif)

**Comment by eviljeff** [comment]
Add-ons don't have distribution methods, versions do, so an add-on could have history in both listed and unlisted channels.  The review pages should do a better job of prompting the reviewer to look at the other review page when there is history in the other channel but that's a different (and long-standing) issue
