### ISSUE TITLE
Issue separate types for ending newline related changes

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11853]
Required for https://github.com/mozilla/addons-code-manager/issues/877

We am rewriting all end of file newline change flags (GIT_DIFF_LINE_CONTEXT_EOFNL, GIT_DIFF_LINE_ADD_EOFNL, GIT_DIFF_LINE_DEL_EOFNL) to be `normal`, `insert`, `delete` instead. So there's context being lost which creates a few issues.

Let's implement separate `normal-eofnl`, `insert-eofnl`, `delete-eofnl` types for these lines instead.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Can qa verify these changes or it's a qa not needed? 

Clearly https://github.com/mozilla/addons-code-manager/issues/877 can be verified by qa when it lands.
