### ISSUE TITLE
Add a travis-ci job to prevent duplicate migration IDs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11852]
Migration ID conflicts happen frequently so we should prevent that as soon as possible. Circle-CI builds usually fail but we don't always look at it so... let's do this in Travis-CI instead.

I could be as simple as a bash script that makes sure we don't have the same migration ID listed twice, or something more involved in a python test file :)

**Comment by Abhi-khandelwal** [comment]
Can I work on this issue ?

**Comment by willdurand** [comment]
@Abhi-khandelwal sorry, I don't think this issue is open to external contributions yet. We need to plan a bit more I believe.

**Comment by Abhi-khandelwal** [comment]
ohk @willdurand

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label qa:not needed?
Thanks
