### ISSUE TITLE
Enable dependabot 

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11862]
With pyup not working anymore we should try to enable dependabot on addons-server.

**Comment by muffinresearch** [comment]
Filed request here: https://bugzilla.mozilla.org/show_bug.cgi?id=1567555 as I can only enable for sec updates only from the repo.

**Comment by EnTeQuAk** [comment]
pyup apparently started working again. But still, it'd at least be nice to get dependabot configured and have it as a fall-back - or try to figure out what happened pyup and decide accordingly.

**Comment by muffinresearch** [comment]
Ok dependabot is now configured.
