### ISSUE TITLE
Uncaught exception thrown when a zip file member is larger than the limit we set

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11861]
### Describe the problem and steps to reproduce it:

1. Create a XPI with a large text file (more than 150MB for example)
2. Submit it

### What happened?

So the error is not visible to the end user. There is a validation error page, which is expected but it does not say why the validation has failed.

In the logs, we can see an uncaught exception:

```
TypeError('__str__ returned non-string (type bytes)',)"    
   msg: "XPI parse error"    
   remoteAddressChain: "[REDACTED]"    
   traceback: "Uncaught exception:
  File "/data/olympia/src/olympia/files/utils.py", line 988, in parse_xpi
    xpi_info = Extractor.parse(xpi, minimal=minimal)
  File "/data/olympia/src/olympia/files/utils.py", line 154, in parse
    zip_file = SafeZip(xpi_fobj)
  File "/data/olympia/src/olympia/files/utils.py", line 755, in __init__
    self.is_valid = self.initialize_and_validate()
  File "/data/olympia/src/olympia/files/utils.py", line 775, in initialize_and_validate
    archive_member_validator(self.source, info)
  File "/data/olympia/src/olympia/files/utils.py", line 741, in archive_member_validator
    '%s' % (archive, filename, filesize))
<class 'TypeError'>
TypeError('__str__ returned non-string (type bytes)',)
```

### What did you expect to happen?

I don't know, but the uncaught `TypeError` exception should be handled.

### Anything else we should know?

At first glance, it looks like the log call is the culprit: https://github.com/mozilla/addons-server/blob/17d4886b14c277b238ea7925beb63be52c39e559/src/olympia/files/utils.py#L741-L743

I don't really know what we should be logging here but it has more values than placeholders and the order looks... odd too.

**Comment by EnTeQuAk** [comment]
> I don't really know what we should be logging here but it has more values than placeholders and the order looks... odd too.

There are three placeholders and values that are used to fill them. The problem more likely is that `archive`, `filename` or `filesize` is a bytes type object and the conversion is being wonky…

**Comment by EnTeQuAk** [comment]
Initially I thought that this is a regression of 2de22598bdd14b5bbd7f58d26b9d2fa6448ccdf9 but it doesn't seem likely, at least I don't see changes that may have caused it by looking at `git diff 91c882f549..703cdb9f96`

**Comment by willdurand** [comment]
> There are three placeholders and values that are used to fill them. The problem more likely is that `archive`'s `__str__` implementation returns a bytes string instead of `str` which raises that exception.

oh right, I see the third one now. I guess we should not be logging `archive`.

**Comment by EnTeQuAk** [comment]
> oh right, I see the third one now. I guess we should not be logging archive.

I think I agree, it doesn't add much information.

**Comment by tapaswenipathak** [comment]
Hello folks: Can I add a fix for the ticket?

**Comment by diox** [comment]
@tapaswenipathak it's already assigned. You can add a fix if you know what to do and can write a unit test reproducing the problem that would pass with that fix.
