### ISSUE TITLE
Allow identification of banned accounts on database level

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11876]
Currently, banned accounts are identified by the following conditions:

`users.deleted = 1 AND users.email IS NOT NULL AND users.fxa_id IS NOT NULL`.

This makes it problematic to to identify banned accounts on redash (which is needed for reasons), since we cannot expose the email to redash.

Let's add some way to identify banned users and distinguish them from users who deleted their accounts themselves.

One idea would be to add new column to the `users` table but I was told that migration would be quite expensive since the table is quite large.

**Comment by diox** [comment]
We only need to know if `email` is not empty for this query though, so can't you expose that info and just that to redash instead ?

**Comment by wagnerand** [comment]
> We only need to know if `email` is not empty for this query though, so can't you expose that info and just that to redash instead ?

We need both `email` and `fxa_id` (for some reason I forgot). We can't expose whether it's empty or not since redash is basically a user on the AMO db that has access to certain columns per table.

**Comment by diox** [comment]
I was thinking it was akin to a sql view and we could leverage that to expose "virtual" columns that represent more complex data we don't want to expose.

If it can't be done that way, then we could avoid the new column by having a separate table storing just the ban date for banned users for instance.

**Comment by diox** [comment]
Options are:
1) Field on `UserProfile` with the ban date
    - Migration would be costly (probably 2-5 minutes ?)
    - It would also have a small perf cost on every query, since Django fetches all columns by default.

2) Replace `deleted` field with `state` on `UserProfile`
    - Doesn't get us the ban date, so #11458 would still be an issue
    - Migration would be as costly as 1), and more complicated (probably best to add a new field and remove the old one later)

3) Separate model with the ban date
    - Forces a join to be made when we want to retrieve the info in redash

I'm leaning towards 3), which is simpler to implement and easy to extend if needed.

**Comment by eviljeff** [comment]
I'm going to do 1. because it's the most straightforward in code and won't require any joins in sql.  

It'll add a small perf hit but we have already have a large number of properties on `UserProfile` that aren't used for most transactions so moving _them_ to a different model would give us more gain that worrying about one more date field.  #12081 for that.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this issue on admin tools - dev and stage with FF68 (Win10).

Test results:

- the `Banned` field is available in a User Profile such as /en-US/admin/models/users/userprofile/10641919/change/, it is displayed in the `Admin` section below the `Known ip address` and it will show the date and time of the ban. 

![Banned field](https://user-images.githubusercontent.com/33448286/62930102-6824e980-bdc4-11e9-9706-2891f728b699.png)

- the `Banned` field in not available in the User profiles report en-US/admin/models/users/userprofile/ (which contains the previous `is public` and `deleted` states). 

- when the user deletes the account, the report from admin tools en-US/admin/models/users/userprofile/ won't display user's e-mail address any longer. I could ban it though.

Deleted by user and then banned 

![deleted and banned](https://user-images.githubusercontent.com/33448286/62930831-dd44ee80-bdc5-11e9-9d94-e3aeffe30104.gif)

If there's anything that won't work as expected let me know.
