### ISSUE TITLE
Remove `scripts/hash_requirements.py` and update the documentation

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11888]
### Describe the problem and steps to reproduce it:

Say you want to add a new python dependency, go to https://addons-server.readthedocs.io/en/latest/topics/development/deps.html.

### What happened?

This page mentions the `scripts/hash_requirements.py` script but it does not work. This page is outdated.

### What did you expect to happen?

A page that explains how to add a new dependency nowadays. It is super-simple:

1. install `hashin`
2. run `hashin -r <requirements file> <dependency>`

In addition to updating this documentation page, the script should likely be removed too.

**Comment by Abhi-khandelwal** [comment]
Hi @willdurand , Can I take this issue ?

**Comment by EnTeQuAk** [comment]
Absolutely @Abhi-khandelwal, just let us know when you start working on it and if you need any further guidance.

**Comment by Abhi-khandelwal** [comment]
@EnTeQuAk , you can assign this issue to me.
