### ISSUE TITLE
Large files load slowly in the compare API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#11904]
### Describe the problem and steps to reproduce it:
 
* Go to https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/
* Click on `src/js/editor-popup.js`

This makes the following API request:
```
curl 'https://addons-dev.allizom.org/api/v5/reviewers/addon/502868/versions/1541685/compare_to/1688187/?file=src%2Fjs%2Feditor-popup.js&lang=en-US'
```

### What happened?

The API response takes 2699ms.

### What did you expect to happen?

The API response should be faster.

### Anything else we should know?

This slowness exists for many large files in the compare API. The browse API does not have the same slow responses.

**Comment by bobsilverberg** [comment]
@EnTeQuAk Was it expected that #12920 would "fix" this issue? I just did some manual testing and have found that the API request to `https://addons-dev.allizom.org/api/v5/reviewers/addon/502868/versions/1541685/compare_to/1688187/?file=src%2Fjs%2Feditor-popup.js&lang=en-US` is taking:
- 3850ms
- 3497ms
- 4076ms

which is actually longer than reported above. Is this what you would have expected? Is there other work to be done to address this slowness reported in this issue?

**Comment by EnTeQuAk** [comment]
Yes, I expected #12920 to have much more impact. Why things are actually slower is something I'm looking and profiling right now.

I opened https://github.com/mozilla/addons-server/issues/13291 to investigate this further. I'll leave this one open until there's measurable impact and improvement.

**Comment by EnTeQuAk** [comment]
So, after #13291 landed it seems that the API responses are much faster now.

![Screenshot from 2020-01-29 11-21-36](https://user-images.githubusercontent.com/139033/73348401-a1c1b200-4289-11ea-8356-b50bb11e5a68.png)

I might be doing something wrong though, @bobsilverberg do you mind reevaluating your manual testing from above to see if I'm missing something?

They're still not super fast, but from what I see the time spent seemed to have been more than halved. There is indeed more room to optimize with how and when we're detecting mimetypes as we already started to discuss. I'm guessing if we end up with a good solution there the API will be a lot faster again.

Happy to be proven wrong though if I tested the wrong thing.

**Comment by EnTeQuAk** [comment]
![Screenshot from 2020-02-24 20-33-40](https://user-images.githubusercontent.com/139033/75184623-fa7b5200-5744-11ea-94f5-3c8499fb6391.png)

I'm going to close this one as processing and loading large files significantly improved with #13460 - while that's not the case for all files it's the case for the most common ones which will improve day-to-day business.

There's still #13420 but that work is tracked there.

**Comment by bobsilverberg** [comment]
@EnTeQuAk Sorry, I missed your request to redo my numbers, but I just checked now and I agree that performance is greatly improved.

**Comment by wagnerand** [comment]
@EnTeQuAk The screenshot you added indicated all requests were cached. Could you try again with a clear cache?

**Comment by bobsilverberg** [comment]
Here's what I'm seeing, and I have the "Disable Cache" checkbox checked in the Network panel:

![Screenshot 2020-02-27 09 16 38](https://user-images.githubusercontent.com/142755/75453507-fff1bb80-5941-11ea-9fad-ee2f0fa8fb5c.png)

These timings all look low to me.

However, this is what I see in Chrome's devtools for the same request:

![Screenshot 2020-02-27 09 21 47](https://user-images.githubusercontent.com/142755/75453909-9aea9580-5942-11ea-85b0-f21dd03ff6a0.png)

Notice that the reported time is much higher in Chrome for the requests that return a large amount of data. If we look at the `GET` for `https://addons-dev.allizom.org/api/v5/reviewers/addon/502868/versions/1688187/?file=src%2Fjs%2Feditor-popup.js&lang=en-US`, for example, which is reported as 5.32s, we notice that the green bar is small and the blue bar is large. Hovering over the bar, we see:

![Screenshot 2020-02-27 09 24 15](https://user-images.githubusercontent.com/142755/75454165-f452c480-5942-11ea-8da6-3d6e76e5e242.png)

which suggests to me that the "response time" for the API was around 300ms, and the time it took for the browser to download the content was 5 seconds. Perhaps this is why we are still observing large response times for large files. Is there anything we can do to speed up the time it takes to send the data to the browser, or is that just an aspect of how quickly the browser can receive it over the existing connection?

**Comment by bobsilverberg** [comment]
Further to the above, if transferring large amounts of data to the client is the main issue for API performance, then it's possible that when we're doing for truncation on the client will have less of an impact than we hoped. Unfortunately, it seems that the resource timings that I'm planning on landing in https://github.com/mozilla/addons-code-manager/issues/1450 don't take this "Content Download" into account, so they might not give us an accurate picture of this.

Therefore, I'm not sure if we're positioned to be capturing the performance metrics we want for API requests, even with https://github.com/mozilla/addons-code-manager/issues/1450, which would be unfortunate.

It does seem like we need to take the amount of data being transferred into account and possibly address this on the server side as well. Having said that, is it reasonable to expect that 572kb of data would take 5 seconds to download, and that 353kb of data would take 4 seconds to download, or is that an indication that we're having a problem sending the data from the server?

cc @diox @EnTeQuAk

**Comment by EnTeQuAk** [comment]
Happy to hear @diox' thoughts on that but assuming you do have a reasonable internet connection 5s for ~500kb is way too much imho. I have no idea what to expect though. 

We do support gzip on the API side, it doesn't look like it gets used by the code-manager at this time. Maybe that'll help for the download times?

**Comment by diox** [comment]
> Happy to hear @diox' thoughts on that but assuming you do have a reasonable internet connection 5s for ~500kb is way too much imho. I have no idea what to expect though.

I'd say it's way too much as well.

> We do support gzip on the API side, it doesn't look like it gets used by the code-manager at this time. Maybe that'll help for the download times?

gzip is enabled for all API requests by default in middleware.

**Comment by EnTeQuAk** [comment]
> gzip is enabled for all API requests by default in middleware.

Correct but the client needs to request it with the right `Accept` headers.

**Comment by diox** [comment]
All modern browsers should already make requests with the right `Accept-Encoding`. My Firefox is definitely sending that in code-manager, I see it on all API requests in the developer tools network panel.
