### ISSUE TITLE
Review page very slow

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11902]
### Describe the problem and steps to reproduce it:

Every review page takes lots of seconds (6 or much longer) to load.
Example https://reviewers.addons.mozilla.org/en-US/reviewers/review/lastpass-password-manager takes consistently almost 8s.

### What happened?

Loading a review page: 🐌

### What did you expect to happen?

Loading a review page: ⚡️

### Anything else we should know?

Maybe related to #11797, but that can't be the only reason?

**Comment by muffinresearch** [comment]
Marking as P2 so we discuss this at the stand-up this week. We can always downgrade after then.

**Comment by EnTeQuAk** [comment]
I can look at that as part of #11797, I wonder if the deleted entries might be behind this again but we'll see.

**Comment by diox** [comment]
Note that this review page has a lot of user reviews and reports. Maybe there is something to investigate there as well.

**Comment by EnTeQuAk** [comment]
Unassigning the milestone but keeping the issue open for now.

@diox and I looked into it and landed #12039 which should improve the speed already. We will file separate issues for all the other performance optimisations we may find.

**Comment by EnTeQuAk** [comment]
I'm going to close this issue in favour of #11902 which will be our meta issue to file other follow-up issues.
