### ISSUE TITLE
Received an empty response from the server; status: 403

### ISSUE THREAD

**Issue by PilzAdam** [mozilla/addons-server#11910]
### Describe the problem and steps to reproduce it:

Add-on verification fails with an error message from the server.

* Go to "Upload New Version" of an existing (private) add-on in developer hub
* Click on "Select a file..." and select .xpi of new version of the add-on

### What happened?

Verification fails with the following message:
```
Your add-on failed validation with 1 error.
* Received an empty response from the server; status: 403
```

### What did you expect to happen?

Addon verifies correctly and I can download a signed .xpi.

### Anything else we should know?

The .xpi in question is a private Firefox add-on and I am hesitant to upload it publicly. Any comments or ideas how to debug this issue without making the add-on public are greatly appreciated.

**Comment by diox** [comment]
Django's CSRF protections do include `Referer` header checking, so it's expected behavior.
