### ISSUE TITLE
All Add-ons from a collection are marked added to a chosen collection in the "Add to collection" list even if just one Add-on was added

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1191]
Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/firefox 
2. Go to any collection details page (i.e. https://addons.allizom.org/en-US/firefox/collections/ValentinaStage/012354/ )
3. Choose any addon and click “Add to collection” icon
4. Add the add-on to any collection (i.e. Summer)
5. Check another add-on “Add to collection” affiliation list (i.e. Menu Wizard)

Expected results:
The other add-on is not added to the collection that first add-on was. 

Actual results:
All add-ons from that collection are added to the collection that first addon (from step 4) was added.

Notes/Issues:
In AMO production an add-on from a collection can belong just to one collection. (don't know if this behavior is intended)
Verified on Ff43(Win 7). Issue is reproducing on AMO-stage, AMO-dev and AMO-prod.
Screencast for this issue: http://screencast.com/t/UsvPQIm7m7Nc

**Comment by ValentinaPC** [comment]
This issue can be expanded to: adding an add-on to a collection (bu clicking the "add to collection" link from add-on details page) makes all add-ons accessed afterwards appear to be added to that collection, even if, when accessing the collection, only the first add-on appears. (http://screencast.com/t/JUMRtRGvV1L)

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
