### ISSUE TITLE
Limit body of abuse reports to 10,000 characters

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#11921]
We need to limit the body of abuse reports (both on AMO and coming from Firefox) to avoid issues and prevent misuse. The limit should be 10,000 characters.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
For 10001 chars (using a nice tool https://www.blindtextgenerator.com/lorem-ipsum) I receive the message "Ensure this field has no more than 10000 characters." Right now the stage server still allows more than 10001 chars in the `message`, (as double checking). 

![100001 chars not allowed](https://user-images.githubusercontent.com/33448286/62055320-0db45680-b224-11e9-8c9e-63a0a3df420c.png)

Verified on dev server with Postman.

**Comment by wagnerand** [comment]
@ioanarusiczki Could you test this again from within Firefox once the patch lands on prod (after this Thursday), please?

**Comment by ioanarusiczki** [comment]
@wagnerand Sure, I'll update this issue on Friday.

**Comment by wagnerand** [comment]
Thank you! Note that you likely won't see much feedback inside Firefox (that will be worked on in the future), so you probably want to monitor the "Network" panel in the devtools when submitting the abuse report from Firefox. The request to AMO should respond with an HTTP status > 400.

**Comment by ioanarusiczki** [comment]
@wagnerand 
I verified on stage and prod with FF68 (Win10) and here are my results:
- for reports sent from the addon's detail pages from AMO (with more than 10000 chars) the red message
 ` Please ensure this field has no more than 10000 characters.` is displayed right above the text box.  I also see:

 in the `Console` a yellow warning ->  `Reporting add-on for abuse failed: Error: Error calling: /api/v4/abuse/report/addon/ (status: 400) BigInteger.js:101

in the `Network` - the 400 status 

![Console and Network](https://user-images.githubusercontent.com/33448286/62372409-19638e00-b540-11e9-8f9c-143edc3d04ef.gif)

- for reports sent from about:addons with more than 10000 chars I receive a red error message in the `Recommendations`, `Extensions` and  `Themes` tabs at the top of the page `There was an error sending the report` 

in the `Console` a red error is present -> `Error submitting abuse report for {9d11c1e4-0863-413b-a647-133c97089f2f} AbuseReportError: "ERROR_CLIENT - {"status":400,"responseText":"{\"message\":[\"Please ensure this field has no more than 10000 characters.\"]}"}"`

in the `Network` - there's no 400 status (which I find strange). 

![Console and Network2](https://user-images.githubusercontent.com/33448286/62373599-cb9c5500-b542-11e9-93a4-1f13f2d9a49b.gif)

**Comment by wagnerand** [comment]
Thank you @ioanarusiczki. I believe this issue can be marked as verified. I believe the reason you don't see a network request in Firefox for about:addons is that it probably won't be recorded in the network requests for that page. It should be shown in the network panel of the "Browser Toolbox" (which you can access if you have chrome and remote debugging enabled).

**Comment by ioanarusiczki** [comment]
@wagnerand Yes, this issue is verified on AMO with FF68(Win10). 
Also https://github.com/mozilla/addons-frontend/issues/8385 is marked verified.
