### ISSUE TITLE
Add specific documentation for diff structure in reviewers compare api

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11920]
In https://github.com/mozilla/addons-server/pull/11912 I mentioned it, we are going to have to document the `diff` structure to a much deeper extend than we currently do, e.g specify possible values etc.

**Comment by tapaswenipathak** [comment]
Hi @EnTeQuAk: Can I work on the ticket or is the ticket internal?

**Comment by EnTeQuAk** [comment]
Unfortunately this issue isn't really suitable for contributors.

Please take a look at other issues that have the [`contrib: welcome`](https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome) label.
