### ISSUE TITLE
Map edition=MozillaOnline to edition=china

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#11937]
In order to tailor recommendations for the China repack of Firefox, we'd like the `edition=MozillaOnline` parameter to be mapped to `edition=china`.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1564731

On Firefox's side, we would include `&edition=%DISTRIBUTION%` in the API URL for the disco pane. So `edition` would then not only contain `china` or `MozillaOnline`, but also potentially anything else that we put in `%DISTRIBUTION%`, and the parameter could become something like `edition=default`.

**Comment by muffinresearch** [comment]
@eviljeff would you be ok to take this on for release some time within the next few releases?

**Comment by eviljeff** [comment]
`edition=china` or `edition=MozillaOnline` will be both be returned as `edition=china` is today; any other value for `edition` (or omitted) will be treated as `edition=default`.

**Comment by l-hedgehog** [comment]
Thanks!

**Comment by AlexandraMoga** [comment]
Verified on -dev with the [Discovery](https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#get--api-v4-discovery-) api:

https://addons-dev.allizom.org/api/v4/discovery/?edition=china and https://addons-dev.allizom.org/api/v4/discovery/?edition=MozillaOnline will return the same alternative results for the discovery pane.

https://addons-dev.allizom.org/api/v4/discovery/, or https://addons-dev.allizom.org/api/v4/discovery/?edition=foo will return the default set-up for the discovery pane
