### ISSUE TITLE
Remove "—" entries from the content review list

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#11944]
In the content review list there are some entries with a name of "—" (U+2014, em-dash), no version, and no link.

Currently there are two of these on the first page of content review (add-on IDs 13949, 14004), and some on later pages.
https://reviewers.addons.mozilla.org/en-US/reviewers/queue/content_review#review-actions

![Screenshot_2019-07-27 Reviewer Tools Add-ons for Firefox](https://user-images.githubusercontent.com/4101902/61993262-02e89e80-b037-11e9-887e-431b5149aa59.png)

These entries display no useful information and should either be removed or fixed to have a link to the add-on.

**Comment by Patil2099** [comment]
Can I work on this ?

**Comment by wagnerand** [comment]
Hi @Patil2099. The cause of this issue is unknown to me at the moment, do you know what's causing it and what's necessary to fix it?

**Comment by diox** [comment]
Looks like those add-ons are super old and simply have no name at all in the database, causing the issue. I don't think we should change the code to remove them - it's likely that they should be rejected entirely instead (it should be impossible for new add-ons to get in this state).

**Comment by bjherbison** [comment]
The first has 14,798 downloads (and a name of None). The next has over 9000. Could someone add a name to the database?
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/gutscheinerabatte
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/tageshoroskop-das-t%C3%A4glich-f

In any case, I hacked up an URL and content-approved them. Do this is now a DB issue and not a content review issue.
