### ISSUE TITLE
The message won't show the correct number of items in a collection

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#11948]
While testing for https://github.com/mozilla/addons-server/issues/11825 I've noticed the following:
1. Load django admin admin/models/bandwagon/collection/ 
2. Click a collection and add or remove some extensions or themes 
3. Observe the number displayed by the message after the changes were saved

Expected result:
The number is correct.

Actual result:
The previous number of extensions is displayed (the one before extensions were added or removed). 

Notes:
It's reproducible on dev and stage - FF68(Win10). 
When "Save" is clicked the second time - the number of extesions/themes shown by the message is correct.

![correct number of items](https://user-images.githubusercontent.com/33448286/62035800-35da9000-b1f9-11e9-8839-e90e3ec465ed.gif)

**Comment by eviljeff** [comment]
It's just django admin constructing the success string before the save has completed.  As it's entirely admin-facing I don't think it's worth fixing.  We can re-open if one of the (few) users of admin particularly wants it correcting.
