### ISSUE TITLE
[Primary hero] Images and gradient colors are not correctly displayed

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11966]
### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev with an admin account
2. Open the details for a discovery item - see https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/116/change/
3. Scroll down to the Primary hero section
4. Observe the layout of the images and gradient colors available for selection

### What happened?
Images and gradient colors are spanning horizontally and they repeat. Also, specifically for images, there is only a small portion from the top displayed.
 
### What did you expect to happen?
Images and gradient colors are displayed with their correct sizes

### Anything else we should know?
- reproduced on -dev with Fx68, Win10x64

![image](https://user-images.githubusercontent.com/31961530/62122827-478e6700-b2cf-11e9-8948-0f84ef0fdf80.png)

**Comment by eviljeff** [comment]
wfm.  Maybe you need to force-refresh to clear the css file in the cache?

**Comment by AlexandraMoga** [comment]
Indeed, fixed by a force refresh:

![image](https://user-images.githubusercontent.com/31961530/62277350-ab8b6980-b44e-11e9-9f71-d0f7da191ffc.png)
