### ISSUE TITLE
[Primary hero] View on site option is triggering a 500 error

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#11967]
### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev with an admin account
2. Open the details for a discovery item which was selected for the primary hero shelf - see https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/116/change/
3. Scroll down to the Primary hero section
4. Click on View on site

### What happened?
You land on https://addons-internal.dev.mozaws.net/en-US/admin/models/r/145/8/ which triggers a 500 error

### What did you expect to happen?
I'm not sure what was the purpose for adding this link. Maybe it should load the homepage, to see how your customization looks (once https://github.com/mozilla/addons-frontend/issues/8305 lands)?

### Anything else we should know?
- reproduced on -dev with Fx68, Win10x64

![2019-07-30_13-42-22](https://user-images.githubusercontent.com/31961530/62123962-c2588180-b2d1-11e9-8286-4cee892b0523.gif)

**Comment by eviljeff** [comment]
> I'm not sure what was the purpose for adding this link. 

It's there by default - I overlooked removing it.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

![image](https://user-images.githubusercontent.com/31961530/62462512-4c03c580-b790-11e9-8263-df8f81fc913f.png)
