### ISSUE TITLE
Implement jinja bytecode cache

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11969]
We dropped template caching during our upgrade to django-jinja and never ended up re-implementing it.

Let's do that.

Theoretically it's just a matter of adding `django_jinja.builtins.extensions.CacheExtension` to the extensions list, and adding

```python
            "bytecode_cache": {
                "name": "default",
                "backend": "django_jinja.cache.BytecodeCache",
                "enabled": True,
            },
```

to the `OPTIONS` configuration (and `enabled: False` to the local config)

**Comment by tapaswenipathak** [comment]
Hi @EnTeQuAk: Can I take the ticket?

**Comment by EnTeQuAk** [comment]
This issue isn't really suitable for contributors. It requires lots of testing and lots of internal knowledge.

Please take a look at other issues that have the [`contrib: welcome`](https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome) label.
