### ISSUE TITLE
Re-sort content review queue by most recently updated 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#11986]
Currently the content review queue is sorted by "oldest to most recent" updates. 

We'd like to flip it to be sorted from "most recent to oldest" updates for the August 8 push.

**Comment by diox** [comment]
Didn't notice this issue so it missed the August 8th push window.

**Comment by eviljeff** [comment]
iirc from the standup, this was for content review, so #12065 would negate this.
