### ISSUE TITLE
Create a Celery chords for tasks between `repack` and `handle_upload_validation_result`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11984]
After #9068, we should create a _chord_ to run the Celery tasks of the submission process in parallel. The chord should be executed after _repack_ and should end with `handle_upload_validation_result`.

Doing this will allow us to add more tasks in parallel, such as the yara task described in #11983.

**Comment by willdurand** [comment]
@diox I suppose we could do that as soon as #11983 lands, no? It seems only the linter task would be part of the set of parallel tasks, right? Once we have that, it should be relatively easy to add the yara task (#11983).

**Comment by diox** [comment]
Yes, and in fact that'd probably be a great thing to try without adding extra features like yara, just making a (dumb) chord and see if it still works.

**Comment by tapaswenipathak** [comment]
Hello folks: Can I PR for the ticket?

**Comment by EnTeQuAk** [comment]
> Hello folks: Can I PR for the ticket?

This issue isn't really suitable for contributors as.

Please take a look at other issues that have the [`contrib: welcome`](https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome) label.

**Comment by willdurand** [comment]
We decided that running the `chord` after the linter would make sense to only run the scanners and other tools on "valid" add-ons.

**Comment by AlexandraMoga** [comment]
I've submitted samples for all the supported add-on types, I've triggered validation warnings and errors, I've submitted add-ons with many files. I haven't noticed any issues during upload and validation. 

@willdurand I've also used the upload script that uses the API signing endpoint and for a batch of 100 add-ons, one of them was created without a version. 
This is the example (you need to be an admin to see it):
https://addons-dev.allizom.org/en-US/developers/addon/e884c0b902ec4c4e8ac6/versions
I understand you observed this issue in prod as well?

**Comment by willdurand** [comment]
>  I understand you observed this issue in prod as well?

I filed https://github.com/mozilla/addons-server/issues/12572, which should be related.

**Comment by AlexandraMoga** [comment]
If the issue does exist in prod, it should not be a regression from this patch. 
I'll cover a few more submissions on stage and if everything goes well, I'm going to mark the issue as verified fixed.
