### ISSUE TITLE
Create a Django admin for `YaraResults`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#11982]
In order to view the `yara` results, we need a simple read-only Django admin. The list view should display:

- upload id (link to the detail view)
- add-on name with a link to the reviewer page
- channel
- matched rules

![Screen Shot 2019-07-31 at 11 09 24](https://user-images.githubusercontent.com/217628/62199461-d361cb00-b383-11e9-8f5d-74db1463ecc0.png)

The default detail view is probably fine, although we can probably pretty print the JSON column:

![Screen Shot 2019-07-31 at 11 09 58](https://user-images.githubusercontent.com/217628/62199465-d52b8e80-b383-11e9-97ab-80cc4b54302e.png)

**Comment by AlexandraMoga** [comment]
@willdurand is there anything that can be tested around this atm?
I was able to access the view only Yara model with an admin account but there is nothing in there.

**Comment by willdurand** [comment]
@diox @EnTeQuAk do you think we can inject fake data in -dev so that QA can verify the admin? Or should we just wait until we have real data coming from the Celery task?

**Comment by diox** [comment]
I'd inject fake data and then remove it later once QA are done or make it very clear that it's fake so that we don't end up wondering what's going on later :p

**Comment by AlexandraMoga** [comment]
Just an input: will this fake data allow an end-to-end testing of the feature? Otherwise, I'm not sure how useful it will be for us.

**Comment by willdurand** [comment]
@AlexandraMoga this will populate the database table with almost real data (or even, real data from my local setup). Given that the admin is read-only, I think it will be a pretty accurate/good way of testing this admin.

**Comment by willdurand** [comment]
@AlexandraMoga I just added some data

**Comment by vcarciu** [comment]
I verified the issue using a code sample from @willdurand (eval(function(p,a,c,k,e,d) {});) and the "dean_edwards_packer" rule was correctly identified.

Also , please see a screenshot of Django admin page : 
![yara](https://user-images.githubusercontent.com/1583842/65616749-3eb2cc80-dfc4-11e9-982f-8158a58eb5e7.png)


Marking issue as verified
