### ISSUE TITLE
Upgrade Python to 3.8

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#11980]
We are currently using Python 3.6 in our docker environment. We should fairly easy be able to upgrade to ~~3.7~~ 3.8.

Python 3.6 is already in "security fix only"-mode and doesn't receive any further bugfixes should they be needed.

Aside from many useful features, Python 3.7 is supposed to be one of the fastest releases of the CPython environment yet.

**Comment by diox** [comment]
We were (are?) blocked by https://github.com/celery/celery/issues/4849 when we migrated to Python 3 for the record, and that's why we chose Python 3.6.

**Comment by EnTeQuAk** [comment]
I know, all this can theoretically tackled once we upgraded to 4.3 as part of #9068

**Comment by eviljeff** [comment]
Celery wasn't the only python3.7 blocker during the 2.7->3.6 upgrade iirc. Have you tried 3.7 on a branch yet?

**Comment by EnTeQuAk** [comment]
> Celery wasn't the only python3.7 blocker during the 2.7->3.6 upgrade iirc. Have you tried 3.7 on a branch yet?

No, I only filed the issue :laughing:

**Comment by tapaswenipathak** [comment]
Hi folks: Can I PR for the ticket?

**Comment by EnTeQuAk** [comment]
> Hi folks: Can I PR for the ticket?

This issue isn't really suitable for contributors. It requires lots of testing and can't be solved before  #9068 has been solved.

Please take a look at other issues that have the [`contrib: welcome`](https://github.com/mozilla/addons-server/labels/contrib%3A%20welcome) label.

**Comment by diox** [comment]
#9068 is solved, so we should be able to try the upgrade to 3.7 again (maybe we'll discover other blockers)

**Comment by tapaswenipathak** [comment]
Heyo folks - unsubscribing.

**Comment by diox** [comment]
Made https://github.com/diox/olympia/tree/python3.7 let's see if that works... Follow along in https://travis-ci.org/diox/olympia/builds/589973239

**Comment by diox** [comment]
Ahah, it fails because `jingo_minify_helpers` is using an undocumented property that has been removed in Python 3.7:
```
src/olympia/lib/jingo_minify_helpers.py:54: in ensure_path_exists
    if e.errno != os.errno.EEXIST:
E   AttributeError: module 'os' has no attribute 'errno'
```

From https://docs.python.org/3/whatsnew/3.7.html :
> Several undocumented internal imports were removed. One example is that os.errno is no longer available; use import errno directly instead. Note that such undocumented internal imports may be removed any time without notice, even in micro version releases.

**Comment by diox** [comment]
https://travis-ci.org/diox/olympia/builds/589979305 is the build with that fix but I see some other failures coming...

**Comment by eviljeff** [comment]
> https://travis-ci.org/diox/olympia/builds/589979305 is the build with that fix but I see some other failures coming...

If we're lucky all 3 test fails are due to a single bug in the zip extraction function.  Not bad, considering.

**Comment by eviljeff** [comment]
> 
> 
> > https://travis-ci.org/diox/olympia/builds/589979305 is the build with that fix but I see some other failures coming...
> 
> If we're lucky all 3 test fails are due to a single bug in the zip extraction function. Not bad, considering.

I think the fails are https://bugs.python.org/issue34606

**Comment by eviljeff** [comment]
fwiw, bumping python to 3.8 doesn't seem to break any more than 3.7 https://github.com/mozilla/addons-server/tree/python38 https://travis-ci.org/github/mozilla/addons-server/builds/697159248 -  `errno` and zipfile fails.

**Comment by diox** [comment]
QA: A quick sanity check around the website would be good. Please upload an add-on in devhub and check that it still works, and also try uploading various invalid zip files and check that the error message is correct.

**Comment by ioanarusiczki** [comment]
@diox I can't see issues after uploading listed/unlisted extensions. As for invalid zip files, I tried .zip without manifest, the manifest moved from the root, images not square, a longer add-on name and I get the classic error messages as before. 
However, I'll let this be marked verified after the release testing, after some more addon upload tests on AMO stage.

**Comment by AlexandraMoga** [comment]
I've also run some tests on stage for add-on validation errors and I didn't notice any differences with regards to the error messages. I've tried the same with source code uploads errors. 
In addition to that, I've verified that Developer Hub, Rev tools and Admin tools are still working as before. 

I'm marking this issue as verified fixed on stage.
