### ISSUE TITLE
Add localization support for secondary hero shelves

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#11989]
#11779 and #11780 require the content to be localized and the "localization should work in the same way as the copy for Recommended extensions" so we need to hook into that.

**Comment by AlexandraMoga** [comment]
@eviljeff I've verified this by finding some suitable localized strings present in https://addons.mozilla,org/api/v4/discovery/editorial/ and adding them to the following fields from the secondary hero shelf form:
- Blurb:
  - Headline
  - Description
  - Cta text

- Modules:
  - Description
  - Cta text

Then, I've called the `/hero/secondary/` endpoint with different locales to verify that the above fields are localized:
- https://addons-dev.allizom.org/api/v4/hero/secondary/?lang=de (all strings localized)
- https://addons-dev.allizom.org/api/v4/hero/secondary/?lang=fr
- https://addons-dev.allizom.org/api/v4/hero/secondary/?lang=it

I think this issue can be marked as verified fixed
