### ISSUE TITLE
`YaraResult.matched_rules` should return a unique list

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12007]
It is possible to have a Yara rule that matches more than once for a given add-on, most likely because the rules are applied to all the files and it is possible that a rule gets triggered by more than one of these files.

The `matched_rules` property on the `YaraResult` model should return a unique list of rule names, instead of returning all the rule names and potentially duplicate names.

**Comment by AlexandraMoga** [comment]
Please add STR or the qa:not needed label
Thanks
