### ISSUE TITLE
Execute the `run_yara` task during submission (behind a waffle switch)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12006]
The `run_yara` task (cf. #11983) should run during submission. It should be part of the "submission" chord added in #11984. In order to enable/disable this task, we should use a waffle switch.

**Comment by willdurand** [comment]
It would probably be a good idea to time this task (with statsd).

**Comment by willdurand** [comment]
Marking this issue as blocked by https://github.com/mozilla/addons-server/issues/11984 (which is blocked by https://github.com/mozilla/addons-server/issues/9068), unless we are OK with running this task synchronously.

**Comment by AlexandraMoga** [comment]
Same as #12208, should we be able to test this in -dev as well?

**Comment by willdurand** [comment]
Added "state: blocked" since we cannot test in in -dev yet.

**Comment by vcarciu** [comment]
I verified the issue using a code sample from @willdurand (eval(function(p,a,c,k,e,d) {});) and the "dean_edwards_packer" rule was correctly identified.

Marking issue as verified
