### ISSUE TITLE
Weekly reviewer report: Content-review numbers are too low

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12019]
### Describe the problem and steps to reproduce it:

The weekly content-review numbers are lower than they should be.

### Anything else we should know?

This happens because search plugins and dictionaries that were submitted before auto-approval don't have an `AutoApprovalSummary`, but the SQL query does a full join.

**Comment by ioanarusiczki** [comment]
@wagnerand  If this issue can be verified on the testing environments can you provide some steps to reproduce for QA? 
I currently see on dev and stage a large number of add-ons in the content review queue (over 5000 on dev and over 4000 on stage).

**Comment by wagnerand** [comment]
@ioanarusiczki I don't think this can be tested before it lands on prod. If you want to test this, you would do a bunch of content-reviews for dictionaries and search plugins that were submitted before auto-approval was enabled for them (a safe bet is 2016 and earlier). Make not how many you reviewed and that number should be in the report that is generated next Monday.

**Comment by ioanarusiczki** [comment]
@wagnerand 
The problem is that I'm not the only one with access to test in rev tools and meanwhile others can make reviews too. 
I could try to approve/reject a couple from Content Review queue ( if I find search engines and dictionaries in the list submitted before 2016) Friday afternoon and then check the number on Monday morning.  

> Make note how many you reviewed and that number should be in the report that is generated next Monday.

My only question is which report should I check (I can't tell if I see such a report on dev). 

I thought it's about updating the number for the Content Review queue 

![content review](https://user-images.githubusercontent.com/33448286/62552140-d3773480-b875-11e9-9c04-524b6688aaae.png)

**Comment by wagnerand** [comment]
> @wagnerand
> The problem is that I'm not the only one with access to test in rev tools and meanwhile others can make reviews too.

That shouldn't be a problem, the report lists amount of reviews per reviewer.

> > Make note how many you reviewed and that number should be in the report that is generated next Monday.
> 
> My only question is which report should I check (I can't tell if I see such a report on dev).

The report is an email and should be in fakemail around noon your time on Monday.

> 
> I thought it's about updating the number for the Content Review queue
> 
> ![content review](https://user-images.githubusercontent.com/33448286/62552140-d3773480-b875-11e9-9c04-524b6688aaae.png)

No, this is about the weekly report email.

**Comment by ioanarusiczki** [comment]
@wagnerand I verified this in dev and stage and it seems to be working. - FF68(Win10)

I reviewed with a new content reviewer account 4 search engines on dev, 4 dictionaries  and 2 search engines on stage (I made sure they're old, submitted long before 2016).

The report on dev:
![report on dev](https://user-images.githubusercontent.com/33448286/62861738-0fdee080-bd0d-11e9-9bd6-490ff0adf64d.png)

The report on stage:
![report on stage](https://user-images.githubusercontent.com/33448286/62861622-c0001980-bd0c-11e9-8f64-35b9f22ac6f6.png)
