### ISSUE TITLE
drop the Persona model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12010]
Now we don't have any LWT we can drop the `Persona` model and all references to it.

**Comment by eviljeff** [comment]
QA: this removes an obsolete model only used for LWT, but due to the amount of code removed, and how closely it was used with the Addon model, it could break pretty much anything.  Look out for regressions in devhub and the addon API responses (search and single addon - detail - responses) in particular.

**Comment by ioanarusiczki** [comment]
@eviljeff 

- UI looks alright, I did not find regressions. Test runs and results are here:  
[AMO: Add-on Details, Buttons, Installations ](https://testrail.stage.mozaws.net/index.php?/runs/view/19550&group_by=cases:section_id&group_order=asc)
[AMO Search and Suggestions](https://testrail.stage.mozaws.net/index.php?/runs/view/19551&group_by=cases:section_id&group_order=asc) 
[AMO developer pages](https://testrail.stage.mozaws.net/index.php?/runs/view/19553&group_by=cases:section_id&group_order=asc) 
-  I did not see problems for API responses. I verified in the Network for search and addon detail page and I also did a couple of tests with Postman for [Search](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search) and [Detail](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail)

Verified on AMO stage - FF68(Win10).
