### ISSUE TITLE
Remove queue counts from most reviewer pages

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#12039]
We don't show the query counts on most of the pages in the reviewer tools anymore.

Let's remove them entirely too then.

Part of #11902

**Comment by diox** [comment]
This hasn't been useful for a long time, probably around 3636ea00bde5eb3f894a9528fcd50bc5178a1257 when I added the new dashboard and changed the nav. Recently the queues queries have changed, notably for content review, and I believe this might be the source of our slowdowns (we thought it would be https://github.com/mozilla/addons-server/issues/11797 but I'm not so sure - duplicate queries suck and we should fix them but they have always been there)

**Comment by ioanarusiczki** [comment]
I initially thought it's about removing the numbers from https://reviewers.addons-dev.allizom.org/en-US/reviewers/ but it's not :) 
@EnTeQuAk can you add some str for qa?

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I verified this issue on dev and stage

- except `All unlisted add-ons" queue all the other display the number of items.  Should I file a separate issue for this queue? 

It's shown inside the report though.
![unlisted ](https://user-images.githubusercontent.com/33448286/62713500-832edc80-ba05-11e9-89ad-5b2947f0c55f.gif)

- The review pages load and function just fine.
