### ISSUE TITLE
remove references to ADDON_PERSONA

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12030]
And other persona related code.

**Comment by eviljeff** [comment]
QA: similar to the previous LWT removal issue, it touches a lot of places, so could break anything.  In particular I'd focus on static themes in devhub - the wizard and edit sections - because it's possible some shared js/css got removed accidently.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this with FF68(Win10) on AMO stage.

- [AMO developer pages ](https://testrail.stage.mozaws.net/index.php?/runs/view/19715&group_by=cases:section_id&group_order=asc ) release tests were completed.
- I tested static theme uploads using the wizard but also with a file, upload of new versions, installing, version updates, editing information in dev hub. Looks good to me.
