### ISSUE TITLE
drop heading from primary hero serializer

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12047]
The mocks and PRD don't show heading being used for the primary hero shelf but it was included anyway because it was in the disco serializers.  Now it's going (#11817) we should remove it from the hero endpoints too.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this on dev with Postman.
For the API https://addons-dev.allizom.org/api/v4/hero/primary/ there's `addon`, `description`, ` featured image` and `gradient`. 
I do not see the `heading` displayed in the response. 

![no heading](https://user-images.githubusercontent.com/33448286/62873058-5ccfb080-bd27-11e9-8ab0-4012e17ccb89.png)
