### ISSUE TITLE
Duplicate queries caused by <Version>.compatible_apps

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12041]
Part of https://github.com/mozilla/addons-server/issues/11797

In the list of duplicate queries in the review page, we can see we're reloading the `Addon` that we already have. This is because we're displaying version compatibility information for each add-on, and that does this:
```python
def __str__(self):
        if (self.version.is_compatible_by_default and
                self.version.is_compatible_app(amo.APP_IDS[self.application])):
```

`version.is_compatible_app` does this:
```python
    def is_compatible_app(self, app):
        """Returns True if the provided app passes compatibility conditions."""
        if self.addon.type in amo.NO_COMPAT:
            return True
```

Loading `self.addon` wouldn't be a problem if it's the same addon instance, but in this case it's not, and that's causing us to reload the add-on and all its transformers when we display compatibility information.

**Comment by diox** [comment]
QA:
- Play around app version compatibility for an add-on and see if it's still returned correctly in the API and the review page. The review page should also be faster as a result of these changes, but I'm not sure you can detect that easily (well at least it shouldn't be slower)

**Comment by AlexandraMoga** [comment]
@diox I've tested around the following areas that are exposing app version compatibility (Firefox and Firefox for Android) and I did not find regressions:
-  setting `strict min/max version` compatibility in the add-on manifest  
- changing the app compatibility from dev hub manage version page
- verifying that app compatibility is correctly rendered on the add-on review page
- verifying that the api is returning the app compatibility required by the add-on for: add-on detail, version detail, search, reviewers browse and compare 

If you had anything else in mind, do let me know.
