### ISSUE TITLE
Make fewer queries when displaying activity logs

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12055]
Part of #11797

A lot of extra queries in reviewer tools (and elsewhere, like devhub) are caused by `ActivityLog`. When an `ActivityLog` is displayed, we load the json containing the representation of the arguments stored when the activity was recorded, and then fetch the corresponding instances from the database:

```python
    @property
    def arguments(self):
        try:
            # d is a structure:
            # ``d = [{'addons.addon':12}, {'addons.addon':1}, ... ]``
            d = json.loads(self._arguments)
        except Exception as e:
            log.debug('unserializing data from addon_log failed: %s' % self.id)
            log.debug(e)
            return None

        objs = []
        for item in d:
            # item has only one element.
            model_name, pk = list(item.items())[0]
            if model_name in ('str', 'int', 'null'):
                objs.append(pk)
            else:
                # Cope with renames of key models:
                if model_name == 'reviews.review':
                    model_name = 'ratings.rating'
                (app_label, model_name) = model_name.split('.')
                model = apps.get_model(app_label, model_name)
                # Cope with soft deleted models and unlisted addons.
                objs.extend(model.get_unfiltered_manager().filter(pk=pk))
        return objs
```

If there was a database relation between the object(s) the activity log is about and the activity log itself, we could try to force the object(s) to be preloaded on each activity instance, something like that. But it's not the case here, so we'll have to be more creative.

**Comment by diox** [comment]
Note that this means displaying multiple activity logs scales extremely poorly: not only do we need to load each object separately, but we also fire their transformers if they have one, causing even more queries for each activity log (most of them duplicates).

**Comment by diox** [comment]
2 things that can be done here:
- Forcing the objects to be loaded with `only_translations()`. That will bring the number of queries down by avoiding most transforms, which hopefully we don't need (it's hard to tell without looking precisely at what's displayed for each possible action). We still need translations because we display things like add-on name. We'd still get a lot of duplicate queries for the "main" objects.

- Have a transformer that parses all `arguments` for each `ActivityLog` in the queryset, and fetches all objects in there grouped by model type. So, worst case scenario we'd end up with a query for all add-ons, one for each users, etc. This is difficult to write, especially because we have to keep the arguments in the right order, but may bring huge wins for some pathological cases.

**Comment by diox** [comment]
A few places that would be improved by this:
- Developer Hub activity feed page
- Developer Hub Manage My Submissions page (because the recent activity across all your add-ons is shown on the right) 
- Reviewer tools review page (it's causing duplicate queries, we're loading activities for add-on/versions we already have)
- Reviewer tools review log (a bit like the devhub feed, except worse, plenty of different add-ons, could really gain from loading them in a single query)

**Comment by diox** [comment]
It's worse than I initially thought: in the reviewlog page, the template loads the `arguments` property of each `ActivityLog` multiple times to apply some conditions. But this property isn't cached, so every call is refetching the `Addon`, `Version`, any other instances present in arguments, their transformers... It's so bad that locally, with 25 logs, I can't display the page at all.

Applying the naive approach above of avoiding transformers except for translations, prefetching the users and adding a `@cached_property`, I can display the page and it still makes 205 queries for 25 log entries. It definitely scales with the number of logs displayed so the normal page in production must be over 400, no wonder it's slow...

**Comment by diox** [comment]
QA: places that fetch & display add-on/user activity logs in reviewer tools (review page itself, activity log page), devhub and admin should be much faster - that might not be easy to test without a reference point though. The important thing is that they still behave correctly, loading properly and showing all the relevant activity.

**Comment by ioanarusiczki** [comment]
@diox I tested Rev Tools on AMO stage with FF69 (win10). 
I did not find issues - the suite is [here](https://testrail.stage.mozaws.net/index.php?/runs/view/20898&group_by=cases:section_id&group_order=asc&group_id=181)
I remember that Add-on Review Log (or at least one log) was loading quite slow but it's not the case anymore.
