### ISSUE TITLE
Add restrictions to stop hero shelves from being disabled

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12069]
There needs to be at least one primary and one secondary hero shelf enabled for frontend (or they'll be an ugly gap - if not an error).  We should add some restrictions to the admin `clean` methods to stop enabled shelves being disabled if they're the only ones enabled.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev and I have the following results:

If there are several enabled primary and secondary shelves and you disable them one by one, at the last enabled hero from each category, you'll be blocked by the following errors:

[Primary hero]
![image](https://user-images.githubusercontent.com/31961530/63344848-0df2ce00-c35a-11e9-9596-c64843ee08b2.png)
[Secondary hero]
![image](https://user-images.githubusercontent.com/31961530/63344862-14814580-c35a-11e9-9ca9-863a14629d33.png)

@eviljeff there is one uncovered aspect here, namely, when the first primary or secondary hero is added, it won't be enabled by default. If the content editors are not aware of or they simply forget to mark the Enabled checkbox, we can end up with disabled first heroes. 
On the other hand, having disabled first heroes might be something that curators want before the project goes live.  So, this is an edge case we need to consider.

I've also filed #12154 as a follow-up
