### ISSUE TITLE
autoreload should be disabled on circleci

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#12064]
Autoreload seems to be causing Out Of Memory errors on circleci. This PR disabled it as a test: #12058 and the tests were able to run. We should disabled autoreload for CI.

**Comment by jrbenny35** [comment]
We could change this line to false: https://github.com/mozilla/addons-server/blob/master/docker/supervisor.conf#L8 and have a makefile command or something to just run ```exec web supervisorctl start olympia``` for local dev.

Thoughts @EnTeQuAk ?

**Comment by EnTeQuAk** [comment]
See https://github.com/mozilla/addons-server/pull/12058#discussion_r311970978 which might work too.

**Comment by muffinresearch** [comment]
This looks to have been fixed in https://github.com/mozilla/addons-server/pull/12058
