### ISSUE TITLE
Stop recording Developer Agreement Restriction in user restriction history

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12096]
Followup for https://github.com/mozilla/addons-server/issues/11772

STR:
1. On a user profile from admin a new report is available showing the Restriction History
2. If the user is restricted (ip , e-mail or domain restrictions) the report should not register the  Developer Agreement Restriction.

![dev agreement](https://user-images.githubusercontent.com/33448286/62862889-ea070b00-bd0f-11e9-9431-2eb401bfcafe.png)

**Comment by diox** [comment]
It might prove useful to help developers debug issues if they don't pay attention to the error message at submission so I'm lowering priority, we'll re-evaluate this in the future.
