### ISSUE TITLE
Author invitation process tweaks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12129]
https://github.com/mozilla/addons-server/commit/3aa7fd2f50f0a9dc545ae9586d6e7043d1e28493 introduced a new process to invite authors to an add-on, requiring their confirmation before they are actually added.

We've been discussing a few ideas on IRC on what little (or not so little) tweaks to make to improve this, so this issue is to to track them.

**Comment by wagnerand** [comment]
We talked about when to send the notification email to existing authors that a new author got added. The two options are:

1. Send the notification email on invitation (as it is currently). In this case, we should probably rephrase the email to reflect that a user has been invited to become an author, but is not an author yet.
2. Send the notification email on acceptance of invitation. I prefer this option as we avoid sending emails in case the invitation is never accepted. I believe, to existing authors, the relevant info is when the ownership has actually changed, which is when the invitation is accepted.

**Comment by diox** [comment]
Should we do anything to prevent users from trying to accept/decline the invitation with the wrong user account, if they have more than one ? If so, any suggestions ? I believe we talked about just customizing the error page in this case to make it obvious that they are not logged in with the correct account.

**Comment by diox** [comment]
That's already the case, but at the moment if you follow the link while being logged in with a different account, then you get a generic error page.
