### ISSUE TITLE
Remove css personas referencing non-existing files

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12130]
During the `compress_assets` task:

```
 - Could not find file /code/src/olympia/../../static/css/zamboni/../../img/personas/slideshow-nav.png
 - Could not find file /code/src/olympia/../../static/css/zamboni/../../img/zamboni/personas/theme-promo.png
 - Could not find file /code/src/olympia/../../static/css/zamboni/../../img/zamboni/personas/complete-theme-promo.png
 - Could not find file /code/src/olympia/../../static/css/zamboni/../../img/zamboni/personas/submit.jpg
 - Error finding 4 images
```

**Comment by wagnerand** [comment]
I also removed some disco-pane stuff along the way.

QA: As this removes stuff that had been used on several pages, please check in devhub for any weird styling issues.

**Comment by ioanarusiczki** [comment]
@wagnerand So far I did not noticed regressions in devhub on AMO dev with FF68(Win10). 
I will mark this issue verified on Thursday, after the release testing on stage.

**Comment by ioanarusiczki** [comment]
Verified on AMO stage- FF68(Win10). 
Release test results are [here](https://testrail.stage.mozaws.net/index.php?/runs/view/19934&group_by=cases:section_id&group_order=asc).
