### ISSUE TITLE
Consider decoupling Primary Hero Shelf data from DiscoItem

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#12134]
This came up in our AMO engineering meeting today and I am opening this issue to discuss it. Currently the `description` for the Primary Hero Shelf (PHS) as provided via the `hero` API comes from the `DiscoItem` that corresponds to the PHS. It seems, however, that there could be cases where the text we would like to see in about:addons might be different than the text we'd like to see in the PHS, in which case we would need to decouple these and store the `description` for the PHS somewhere else (i.e., in the model used for other PHS data).

Note that we are probably going to need to store cta text for the PHS (see #12133) which would be another piece of data that needs to be stored specifically for the PHS, and which would also need l10n, so that would be treated in a similar manner to the `description`.

**Comment by bobsilverberg** [comment]
Seeking opinions from @jvillalobos and @devaneymoz, thanks.

**Comment by eviljeff** [comment]
fwiw, I'm all for doing this.  Although initially it did seem there would be a lot of overlap between the discovery item and the primary hero shelf, it's currently just the `description` and it would be more convenient to have it defined separately.  The discovery pane `description` also wraps all the responses in `<blockquote>` which is probably something frontend doesn't want either.

**Comment by jvillalobos** [comment]
We decided to use the same string to keep things simple, both on the implementation side and the editorial side. It would be a lot of extra work to keep those distinct copies, if ever needed at all. The CTA inconsistency was a mistake, so I closed that issue too.
