### ISSUE TITLE
Allow for the cta text for the Primary Hero button to be dynamic

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#12133]
It was originally thought that the cta text for the Primary Hero button would just be the static text "Get the extension", but it now appears that we may want to vary this text with the content of the Primary Hero. We already have an instance of wanting the text to read "Get Started" instead.

Therefore, the `hero` API should be able to provide the cta text for the Primary Hero button, and the admin should allow for an administrator to be able to provide the cta text for a given Primary Hero shelf. This text will require l10n. This could theoretically be stored with the `DiscoItem` that corresponds to the Primary Hero shelf, but that seems possibly less helpful than being able to specify it directly for the Primary Hero Shelf. See also #TBA regarding moving the storage of all Primary Hero text into the Primary Hero model.

**Comment by bobsilverberg** [comment]
@jvillalobos Can you please confirm whether we need to make this change to support allowing the cta text for the Primary Hero shelf button to be dynamic?

**Comment by jvillalobos** [comment]
No, let's keep it static. The "Get Started" was thought out for the hard-coded version of the promo area initially, and it didn't account for the decision that the button wouldn't change. Let's stick to "Get the extension".
