### ISSUE TITLE
Replace ADDON_UPLOAD_RATE_LIMITS_BYPASS_EMAILS with a permission

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12155]
In https://github.com/mozilla/addons-server/issues/11793 I wrote:
> As a follow-up we could even remove `ADDON_UPLOAD_RATE_LIMITS_BYPASS_EMAILS` and make that check use another permission instead, giving it to the same group (gives us flexibility if we ever need to expand use of that bypass feature)

Yesterday a Firefox release had issues because the user had changed (from `release+addons@mozilla.org` which is in our setting to `release+addons@mozilla.com` which is not) so they hit the throttles. Because it was a setting we couldn't fix the problem without a new deploy. 

So let's fix that by making a permission check, and give it to the `Submit language packs (auto signed)` group (and maybe a separate one as well?).

**Comment by diox** [comment]
For the record the new user was created in https://bugzilla.mozilla.org/show_bug.cgi?id=1573246 and was made part of the Submit language packs group in that bug.

**Comment by Callek** [comment]
As added context, I reverted the user change for yesterdays beta, so the lack of this PR deploying will not harm the next beta, I'll re-land the credential swap after this does deploy.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I tested this on AMO stage with FF68(Win10):
-  with an account which I did not add in the Submit language packs group, I could not submit lang packs and I could not submit more than 3 add-ons in a minute. 

![throttle rules](https://user-images.githubusercontent.com/33448286/63438255-ac536200-c434-11e9-94d3-770b463e5aa7.png)

![cannot submit lang pack](https://user-images.githubusercontent.com/33448286/63438278-b5443380-c434-11e9-9c62-cf2d596de75b.png)

- after I added the same account in the Submit language packs group I could submit lang packs and I no longer had the 3/minute restriction.
