### ISSUE TITLE
Allow properties to be reset when a Disco item is no longer Enabled for Hero Area

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12162]
After an item is enabled for the Primary Hero Shelf, it's not possible to remove the Enabled setting _and_ reset its images using the normal Save function. You can only uncheck Enabled, but to reset the other properties there's an unintuitive Delete checkbox in the header.

Some possible solutions:
* Unchecking Enabled resets all properties.
* Allow images to be reset when Enabled is not selected.

The Delete checkbox is a bit confusing, so I would prefer if it isn't shown.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. 

The image and gradient color can be (manually!) reset if the primary hero is disabled. The Delete checkbox has been removed as well.

![2019-08-23_12-06-06](https://user-images.githubusercontent.com/31961530/63580939-82b64a00-c59e-11e9-9acd-e2ee1222649d.gif)
