### ISSUE TITLE
Change column ordering in Discovery item admin

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12163]
Maybe it's because QA try to intentionally to break stuff in dev/stage, but I've seen the text columns in the admin extend beyond the screen width.

I'd like `Recommended Status` and `Primary Hero Shelf` to be the second and third columns, respectively. The rest can remain the same.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/63579017-58fb2400-c59a-11e9-8766-6ad77d5cfb26.png)
