### ISSUE TITLE
Gradient colours specified for hero shelves aren't photon colors

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12173]
The gradient colours specified by @brassy- in https://github.com/mozilla/addons-server/issues/11830#issuecomment-513773590 aren't photon colors defined in https://github.com/FirefoxUX/photon-colors/blob/master/photon-colors.scss - we assumed they were because of the color codes written next to the hex colors.

e.g. the image says `#20123A` `INK80` but the photon color for `ink-80` is [actually ](https://github.com/FirefoxUX/photon-colors/blob/master/photon-colors.scss#L90)`#202340`

@jvillalobos should the gradients be defined with photon colors?  (If so, we need to update django admin to show the correct colours; if not there are some frontend changes needed and possibly a reversion of #12132).

cc @bobsilverberg

**Comment by brassy-** [comment]
Colors are being update with the new branding! That's way there is a mismatch between the two.

**Comment by eviljeff** [comment]
@brassy- should we rely on the colours in https://github.com/FirefoxUX/photon-colors/blob/master/photon-colors.scss as the source of truth?

**Comment by brassy-** [comment]
I don't know what the team is going to do. My guest is that we're going to either expand/update the current one or create a new one, with the same variables. It's out of my control, at the moment.

**Comment by muffinresearch** [comment]
> I don't know what the team is going to do. My guest is that we're going to either expand/update the current one or create a new one, with the same variables. It's out of my control, at the moment.

@brassy- Are you ok with us continuing to used the packaged photon styles or do we need to temporarily maintain the changed ones? My feeling would be that we should just use photon styles until the new ones solidify but that would really depend on how big the differences actually are.

**Comment by muffinresearch** [comment]
@bobsilverberg @eviljeff: @brassy- has pointed me to https://github.com/mozilla/protocol-tokens so we should be able to use that as SASS or CSS vars in the frontend. That just means we need to figure out which of those colours should be used or in other words, what is the photon -> protocol mapping.

**Comment by eviljeff** [comment]
Note: the starting gradient colour we use (`ink-80`, mentioned in opening comment) isn't listed in https://protocol.mozilla.org/fundamentals/color.html . I found it in https://github.com/mozilla/protocol-tokens/blob/master/tokens/_aliases.yml#L134 so I'm assuming it's official-ish at least.

I can trivially update the colours on addons-server though they're only defined explicitly for the django admin pages - and they're quite similar so it's unlikely anyone would particularly notice.  In the API we just expose the name (since #12132) which seems the same?  @bobsilverberg can you confirm if the names need changing, or it's still okay?  e.g. you'd need `color-ink-80` rather than `ink-80`.

**Comment by bobsilverberg** [comment]
Although it seems like a bit of a hassle, I think it would be best if the color names returned by the API match the colors in the stylesheet exactly, therefore returning `color-ink-80` rather than `ink-80` would be better. Otherwise the front end needs to assume that it's fine to always prepend the word `color` to the name, and I'd rather not make any assumptions about that. It will also keep everything consistent across projects.

**Comment by kumar303** [comment]
Can't the API just return hex values for the colors? That way the frontend wouldn't need to link the names to anything (which has synchronization issues).

**Comment by eviljeff** [comment]
> Can't the API just return hex values for the colors? That way the frontend wouldn't need to link the names to anything (which has synchronization issues).

see #12132

**Comment by kumar303** [comment]
Thanks for the link.

@bobsilverberg why can't we use hex values from the API? Couldn't we just add something like `<stop stopColor={valueFromAPI} ...>` [here](https://github.com/mozilla/addons-frontend/blob/a6fa499287246a417bcf794bd7351f875416317d/src/amo/components/HeroRecommendation/index.js#L132-L135), for example?

**Comment by AlexandraMoga** [comment]
The `/hero/` api and Discovery admin have been updated with the new color values:

API
```
"gradient": {
            "start": "color-ink-80",
            "end": "color-purple-70"
```
Discovery admin:
![image](https://user-images.githubusercontent.com/31961530/65036648-8d24f300-d954-11e9-928e-752597d03b26.png)

The color codes are the ones specified in https://protocol.mozilla.org/fundamentals/color.html with the mention that for `#20123A` which we are labeling `color-ink-80`, they are listing it as `color-off-black`. Not sure if that will have an impact for amo.

I'm marking this issue as verified fixed on -dev.
