### ISSUE TITLE
Addon submission on AMO dev is not working

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12180]
1. Load AMO dev and try to submit an add-on 

Expected results:
Submission is completed without issues.

Actual results:
Validation fails with a red error `There was a problem contacting the server.`
The network shows a 504 GATEWAY_TIMEOUT

Notes:
Issue is reproducible only on AMO dev - FF68(Win10). 

![504GATEWAY](https://user-images.githubusercontent.com/33448286/63496912-69909900-c4cb-11e9-8c75-6d2130e2ea48.png)

**Comment by diox** [comment]
Dev was having trouble speaking with rabbitmq. oremj fixed it.

```
<oremj> hmm, I added some config lines from stage and it seemed to fix it
<oremj> not sure why they weren't applied as part of the initial puppet run
<oremj> these:
<oremj>     {tcp_listen_options, [
<oremj>          binary,
<oremj>          {packet,        raw},
<oremj>          {reuseaddr,     true},
```
