### ISSUE TITLE
[Secondary hero] 'Not selected' text doesn't fit inside the default icon option

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12201]
Follow up for #12161 

### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev with an admin account
2. Go to the Discovery module -> Secondary hero shelves
3. Open one of the entries
4. Check the 'no icon selected' option

### What happened?
The 'Not selected' text is cut to the right

### What did you expect to happen?
'Not selected' text fits inside the 'no icon selected' option

### Anything else we should know?
The screenshot in https://github.com/mozilla/addons-server/pull/12185#issue-309999260 is different from what I see on -dev, with Win10 on a 1920x1080 display

![image](https://user-images.githubusercontent.com/31961530/63764199-eefeb980-c8ce-11e9-92cc-8fd16cb6571b.png)

**Comment by eviljeff** [comment]
It looks like the screenshot in #12185 - your css must be cached.

**Comment by AlexandraMoga** [comment]
@eviljeff I've hard refreshed the page and I've even created a new profile to make sure no cache was involved, but I'm having the same result.

**Comment by eviljeff** [comment]
![Screenshot 2019-08-27 14 18 57](https://user-images.githubusercontent.com/768592/63774726-c4fcc580-c8d5-11e9-8332-673c4bb5a0d8.png)

**Comment by AlexandraMoga** [comment]
Tried on another Windows 10 PC, also with a 1920x1080 resolution and the issue could be reproduced.
