### ISSUE TITLE
Add a task to run the `customs` scanner

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12208]
We need a task to run the `customs` scanner over HTTP. The task can be generic so that we can add other scanners in the future. The task should be similar to the `yara` task although it uses HTTP and `ScannersResult`, and it will only run if the linter does not report any error.

We will also need a waffle switch to enable/disable the `customs` task.

**Comment by AlexandraMoga** [comment]
@willdurand is this available on -dev as well or still just locally?

**Comment by willdurand** [comment]
> @willdurand is this available on -dev as well or still just locally?

Sorry, this is not yet available in -dev.

**Comment by willdurand** [comment]
We need QA on that but it is not enabled in -dev yet because it depends on another service that isn't deployed.. Not sure whether I should add a "qa: not needed" label here...

**Comment by AlexandraMoga** [comment]
We could add a 'state:blocked' and we can return to it when the feature is available for testing

**Comment by willdurand** [comment]
@ioanarusiczki @vcarciu @AlexandraMoga I only enabled the "Wat" scanner in -dev so far. Once other issues are verified, I'll disable the "Wat" scanner and enable the "Customs" one.

**Comment by AlexandraMoga** [comment]
@willdurand we'll be able to cover this on Friday the earliest. If that is too late, let me know and we'll try to figure out a solution.
Thanks

**Comment by willdurand** [comment]
> @willdurand we'll be able to cover this on Friday the earliest. If that is too late, let me know and we'll try to figure out a solution.
> Thanks

sounds good to me :)

**Comment by willdurand** [comment]
@vcarciu I think this can be verified too now. -dev has yara and customs enabled
