### ISSUE TITLE
Add API key when calling basket sync API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12206]
Basket sync API requires an API Key to work, so we need to add that. We already have it in our code for the `basket` python app, it's `settings.BASKET_API_KEY`. Just need to find a way to pass it down to the sync API.

**Comment by AlexandraMoga** [comment]
@diox are we able to test this on -dev? If so, could you provide some instructions?
Thanks

**Comment by diox** [comment]
@pmac are you able to give QA instructions to test basket sync integration ?

**Comment by pmac** [comment]
I guess we'll just have to cause some known data to be synced to basket, and then I can look up what data made it into salesforce and we can make sure it's what we wanted. Does that sound right? I don't know how to trigger a sync event on the AMO side.

**Comment by diox** [comment]
Any of the following should trigger a sync of an add-on:
- Change to add-on status, current listed version, default locale, slug and name, as well as the add-on being disabled/enabled by a developer (which is technically not a status change)
- The add-on being deleted
- Adding/removal of an author (for the adding part, the only thing that matters is when they confirm the invitation)

Any of the following should trigger a sync of an user:
- Change to display name, email, homepage, location
- Logging in
- Being deleted

**Comment by AlexandraMoga** [comment]
I will try to cover all the mentioned scenarios and I'm going to keep a report with all the actions done as well as their expected outcomes. 

@pmac can compare my data with the information available in Salesforce.

**Comment by AlexandraMoga** [comment]
I've covered the mentioned scenarios on -dev and tracked my expected output in [this report](https://docs.google.com/spreadsheets/d/1YHEnANqiary5SQ1hKush9UNNcotOPYnHgDu5_sKTPdA/edit#gid=0).
@pmac I hope you'll be able to follow the data provided. If you prefer and have the possibility, you can send back a report where I could cross-check my data from AMO with the data received by Salesforce.

**Comment by caitmuenster** [comment]
@AlexandraMoga Sorry to be a nudge, but I wanted to check in on the status of this. :) Are any changes required before this can be ok'd to move forward?

**Comment by AlexandraMoga** [comment]
@caitmuenster sorry for the late reply. There is still a bit of information in [my report](https://docs.google.com/spreadsheets/d/1YHEnANqiary5SQ1hKush9UNNcotOPYnHgDu5_sKTPdA/edit#gid=0) which is waiting for some input from @pmac to make sure that data between AMO and SF is correctly synced. 
I'm going to try to wrap this up this week, depending also on @pmac 's availability.

**Comment by pmac** [comment]
I've commented on all of the rest of it I think. Let's discuss the missing things there.

**Comment by AlexandraMoga** [comment]
Thanks @pmac for validating my results.

Just for clarity, the test items listed in [my report](https://docs.google.com/spreadsheets/d/1YHEnANqiary5SQ1hKush9UNNcotOPYnHgDu5_sKTPdA/edit#gid=0) were created based on the synced data present in [AMO CRM Sync](https://docs.google.com/spreadsheets/d/1WMsA9ukyLVlyiNtveVijdsbfdcDMkkhsGZ56NrGjMQQ/edit#gid=0) and the [Basket api](https://addons-server.readthedocs.io/en/latest/topics/basket.html#basket-synchronisation)
The tests have been executed on AMO -dev. 

Below you'll find a summary of the possible issues identified:

**Add-ons**
1. SFDC doesn't have a field dedicated for `is_recommended` or `is_partner` status
2. Add-on with ID 502722 was not synced. The action that should have triggered a sync was an update of its `average_rating` (@diox maybe you have some idea why this happened)
3. Add-on with ID 616987 should have the following author IDs (the second was added as an additional owner and approved the invitation): 10640485, 10641527. @pmac could you please check if this information is synced?

**Users**

4. SFDC isn't updated when a user changes his primary email address - see [more details](https://docs.google.com/spreadsheets/d/1YHEnANqiary5SQ1hKush9UNNcotOPYnHgDu5_sKTPdA/edit#gid=0&range=40:40)
5. Subscription to add-on newsletter has not been recorder - see [more details](https://docs.google.com/spreadsheets/d/1YHEnANqiary5SQ1hKush9UNNcotOPYnHgDu5_sKTPdA/edit#gid=0&range=43:43)

Unless noted above, all the rest of the actions from [my report](https://docs.google.com/spreadsheets/d/1YHEnANqiary5SQ1hKush9UNNcotOPYnHgDu5_sKTPdA/edit#gid=0) should have been successfully synced, based on @pmac 's analysis. 

@caitmuenster @diox ^

**Comment by diox** [comment]
> SFDC doesn't have a field dedicated for `is_recommended` or `is_partner` status

`is_partner` doesn't exist yet on AMO. `is_recommended` is synced, it's just a matter of handling it on the SalesForce side.

> Add-on with ID 502722 was not synced. The action that should have triggered a sync was an update of its average_rating (@diox maybe you have some idea why this happened)

This was done on purpose - `average_rating` and `average_daily_users` change very often (once a day for every add-on for the latter), so at the moment they do not cause a sync.

> Add-on with ID 616987 should have the following author IDs (...)

FWIW I do see us calling basket in the logs for that action.

> SFDC isn't updated when a user changes his primary email address

Need to investigate this one. could you file a specific follow-up bug for this ?

> Subscription to add-on newsletter has not been recorded

This isn't stored on AMO's side so we can't sync it, it's up to Salesforce/Basket.
