### ISSUE TITLE
The font color used for the image and gradient names in the primary hero module is hard to read

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12202]
### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev with and admin account
2. Go to the Discovery module -> Discovery items
3. Open one of the entries
4. Scroll down to the Pimary hero details and notice the image and gradient color names

### What happened?
The image and gradient color names are hard to read

### What did you expect to happen?
Either use a different font color or place the names above the image previews 

![image](https://user-images.githubusercontent.com/31961530/63765968-dabcbb80-c8d2-11e9-864b-041d7200c60f.png)

**Comment by eviljeff** [comment]
You don't need to be able to read it - its the colour / image that's being selected.

**Comment by eviljeff** [comment]
Unless Scott (pretty much the sole user) specifically complains about this I'm not going to change it.
