### ISSUE TITLE
Deploy yara rules in -dev, stage, prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12211]
LAST UPDATED: 2019.09.12 by @willdurand 

---

Yara is an existing tool (not something we developed) we want to run in a Celery task, as part of the submission process. It is a python lib (bindings) that requires a set of rules (a set of text files, one rule = one file) to work.

In order to execute this task, we need these rules/files. Yet, we do not want to bundle the files in addons-server itself or disclose the files publicly. We have a private repo to store them.

The yara repo builds and publishes a private Docker image for the yara rules. Now, we need to transfer the files from this private Docker image to the addons-server celery workers so that they have access to the Yara files.

**Comment by bqbn** [comment]
I don't have permission to read the flow chart. I've requested access to it on the opening page.

**Comment by willdurand** [comment]
This is now a p2.

**Comment by willdurand** [comment]
According to a discussion with @bqbn, we might not need to build private Docker images of addons-server. Instead, we will build private Docker images of addons-yara and during deployment, we'll pull this image and copy the files it contains into the addons-server celery containers.

**Comment by bqbn** [comment]
I've filed https://github.com/mozilla-services/cloudops-deployment/pull/3410.

And in -dev env, `olympia-devhub` worker containers now mount the yara files.

Please let us know when we should push this change to -stage and -prod respectively.

**Comment by willdurand** [comment]
@bqbn thanks. Yara rules are also deployed in stage, it seems. Can we set a tag that is *not* `latest`? We can use `2019.09.13`.

**Comment by bqbn** [comment]
We won't "formally" push the yara rules to -stage until https://github.com/mozilla-services/cloudops-deployment/pull/3410 is merged.

When it's merged, we'll push `2019.09.13` for those yara rules.

**Comment by willdurand** [comment]
> We won't "formally" push the yara rules to -stage until [mozilla-services/cloudops-deployment#3410](https://github.com/mozilla-services/cloudops-deployment/pull/3410) is merged.

Ah ok. We've seen an IRC message for stage, mentioning yara.

**Comment by willdurand** [comment]
Looks good to me.

**Comment by vcarciu** [comment]
I verified the issue using a code sample from @willdurand (eval(function(p,a,c,k,e,d) {});) and the "dean_edwards_packer" rule was correctly identified.

Marking issue as verified
