### ISSUE TITLE
Add guids from obsolete addons to DeniedGUID before we hard delete them

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12212]
We're getting rid of obsolete addons in #11324 but we want to keep a record of the guids (for https://bugzilla.mozilla.org/show_bug.cgi?id=1576965). 
Possible solutions:
* one-off migration to `INSERT INTO ``denied_guid`` ... SELECT ``guid`` from ``addons`` WHERE ...`
* add something to the `delete_addons` command that adds the guid to `DeniedGUID` before doing the `AddonQueryset.delete()`

**Comment by eviljeff** [comment]
we're talking about ~1500 guids here.  I'm tempted to go for 1 - do it as an sql migration.

**Comment by AlexandraMoga** [comment]
@eviljeff is there anything that we could verify here?

**Comment by eviljeff** [comment]
No, I took a look in the database and it looks as expected though.
