### ISSUE TITLE
Add `run_customs` task to the "chord" of tools that run after the linter

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12217]
Once https://github.com/mozilla/addons-server/issues/11984 has landed, we should move the `run_customs` function call from the `handle_upload_validation_result` task to the Celery chord that should run after the linter and before `handle_upload_validation_result`.

FTR: We added the `run_customs` task in https://github.com/mozilla/addons-server/pull/12191.

**Comment by vcarciu** [comment]
Verified as fixed by submitting various types of addons. Also we run the load script on AMO-dev and all entries were added.
