### ISSUE TITLE
Ideally the hero API would not return a description wrapped in <blockquote>

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#12235]
This is in response to https://github.com/mozilla/addons-frontend/issues/8521, and as discussed at https://github.com/mozilla/addons-frontend/issues/8521#issuecomment-526662494.

@eviljeff's suggestion was that the `hero` API return `description_text` from the discovery data rather than `description`, but I'm not sure if that will satisfy our goal for the Primary Hero shelf. As I understand it, we would like to be able to have *some* html included in the description, but we just don't want the whole thing to be wrapped in a `<blockquote>`. I suppose this  `<blockquote>` could be stripped on either the server (API) side, or on the front end, which is why I've opened this issue to discuss it.

@jvillalobos / @devaneymoz Is it accurate that we might want to be able to embed some html into the description for an item that is used for the Primary Hero shelf, or would limiting the description to only include text be an acceptable option?

**Comment by eviljeff** [comment]
Although we say `description_text` is just text, really it's just the raw input (i.e. unescaped and not sanitized) so could contain html, or anything else, depending on what content admins specify (and then localizers).  That would be the most general solution, and then it would be up to the consumer (frontend) to sanitize as appropriate.  

Depending on the outcome of this issue, we might want to do something about the `SecondaryHero` shelves too.  The content there is all raw input without escaping/sanitizing too.

**Comment by bobsilverberg** [comment]
> Although we say `description_text` is just text, really it's just the raw input (i.e. unescaped and not sanitized) so could contain html, or anything else, depending on what content admins specify (and then localizers). That would be the most general solution, and then it would be up to the consumer (frontend) to sanitize as appropriate.
> 

We are doing sanitization on the frontend, so I guess just sending `description_text` should work fine. That sounds like a simple solution to the issue. 

> Depending on the outcome of this issue, we might want to do something about the `SecondaryHero` shelves too. The content there is all raw input without escaping/sanitizing too.

I plan on sanitizing the secondary responses as well, so I think this would be covered by the frontend as well.

**Comment by jvillalobos** [comment]
As far as I know Scott hasn't been using HTML markup in disco pane descriptions. I don't think we're going to _need_ it, but it'd be good to know if it's a possibility or it will be stripped out by the frontend entirely.

**Comment by kumar303** [comment]
Just to be crystal clear, the description cannot be wrapped in `<blockquote>` because it breaks the layout 🔥

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. 

`description` is no longer wrapped in `<blockquote>` in the `/hero/primary` api:

```
  "description": "Do you have a ton of open tabs? Organize them in a tidy sidebar.",
  "featured_image": "https://addons-dev-cdn.allizom.org/static/img/hero/featured/teamaddons.jpg",
  "gradient": {
            "start": "ink-80",
            "end": "blue-70"
```

**Comment by bobsilverberg** [comment]
Thanks for taking care of this, @eviljeff 👍
