### ISSUE TITLE
Allow FileUpload to be downloaded (from the scanners)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12232]
While testing the customs integration in -dev with some large add-ons, I discovered that add-ons larger than 10MB are rejected by the customs cloud function. This is because GCP cloud functions have very strict and fixed limits: https://cloud.google.com/functions/quotas#resource_limits. AWS has a limit of 6MB.

Currently, it does not seem possible to upload add-ons larger than 40-50MB because of the soft time limit (and the fact that repack and linting run within the same task).

That being said, we should be able to upload add-ons with a size of 10 to 30MB without any issue, but then the customs cloud function will not be able to scan these add-ons.

Therefore, we need a different solution to pass the xpi to these scanners. The idea would be to send a download URL instead of the xpi itself and let the cloud function download the xpi.

The download URL should be authenticated. We can generate a token in the `FileUpload` (on creation) and use it, so that a download URL is bound to only one `FileUpload` and we can't retrieve other files with the same token (if the download URL leaks for example).

The cloud function will validate the download URL sent (making sure it is a valid URL with a whitelisted host). An issue will be filed in the customs repo for that.

This issue is about:

1. Generating a token when a `FileUpload` is created (this needs a new column in the database table)
2. Creating a method on `FileUpload` to return its very own authenticated download URL
3. Adding a new view/endpoint to be able to download `FileUpload`

Did I miss anything? Any suggestions?

**Comment by diox** [comment]
As mentioned on IRC, the implementation of the view, minus the auth part, should probably just be:
```python
upload = get_object_or_404(FileUpload, uuid=uuid)
return HttpResponseSendFile(request, upload.path,
    content_type='application/octet-stream')
```

**Comment by willdurand** [comment]
@ioanarusiczki @vcarciu this is now ready to test. This issue is verified if uploading an extension adds an entry in the `ScannersResult` django admin (for the `wat` scanner currently). Here are a few scenarios:

1. upload a new extension (xpi) and wait for the validation to complete, this should create a new entry in the Django admin
2. upload a new extension (xpi), wait for the validation, then continue the submission to publish a new add-on. That will add a reference to the add-on in the admin
3. try to submit an unlisted extension
4. uploading an add-on that is not an extension should not trigger the scanners

I am going to enable the "wat" scanner for now.

**Comment by willdurand** [comment]
cc @AlexandraMoga

**Comment by vcarciu** [comment]
I tested using following scenarios:

    Tested various xpis(webext, themes, dictionaries , lang packs...) in order to see if after validation an entry is created in Django admin. Also verified that no entry was added if validation is failing or if file validated is not an extension(a search tool xml file) - PASSED

    Publish various types of extensions (webext, themes, dictionaries , lang packs...) and verify if reference is added. Also, verified that a reference is added even if some mandatory fields were not added during submission(checked with @willdurand and it is expected) - PASSED

    Same verification as in second scenario, but with unlisted addons. The references were added as unlisted. - PASSED

    Uploaded addons that are not extensions (ie. Search tools xml files). Verified that no entries were added in the Django admin - PASSED

Marking issue as verified.

**Comment by vcarciu** [comment]
I tested using following scenarios:

    1. Tested various xpis(webext, themes, dictionaries , lang packs...) in order to see if after validation an entry is created in Django admin. Also verified that no entry was added if validation is failing or if file validated is not an extension(a search tool xml file) - PASSED

    2. Publish various types of extensions (webext, themes, dictionaries , lang packs...) and verify if reference is added. Also, verified that a reference is added even if some mandatory fields were not added during submission(checked with @willdurand and it is expected) - PASSED

    3. Same verification as in second scenario, but with unlisted addons. The references were added as unlisted. - PASSED

    4. Uploaded addons that are not extensions (ie. Search tools xml files). Verified that no entries were added in the Django admin - PASSED

Marking issue as verified.
