### ISSUE TITLE
Remove theme_update_counts table, model and related code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12238]
Follow-up to https://github.com/mozilla/addons-server/issues/12011

Dropping that table makes less one big table to `ALTER` to switch to django migrations. It was used for lightweight theme stats, which are no longer a thing.

**Comment by ioanarusiczki** [comment]
@diox Could this code removal affect only stats? Or should we look somewhere else too ?

**Comment by diox** [comment]
It shouldn't affect anything, it wasn't used anymore. Maybe double-check that you can see stats for a migrated lightweight theme, but that's it.

**Comment by ioanarusiczki** [comment]
@diox 
Been going through a couple of themes such as
https://addons.allizom.org/en-US/firefox/addon/sunset-over-water/?src=search
https://addons.allizom.org/en-US/firefox/addon/eco-theme/?src=search
https://addons.allizom.org/en-US/firefox/addon/the-moon-cat/
I did not see issues on the stats.
Verified on stage with FF68(win10).
