### ISSUE TITLE
Improve docs related to posting a canned response

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#12263]
Improve docs related to posting a canned response at [this POST endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#post--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-)

- When describing the `canned_response` parameter, link to [canned responses](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#canned-responses) to communicate the relationship
- The `canned_response` parameter is currently documented as a draft comment ID which is incorrect
- Document the response for this endpoint, which includes a canned response object

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
- the `canned_resonse` info was updated for all the possible actions GET, POST, PATCH.
- Sending a POST or a PATCH with `filename`:null and `lineno`:null returns a 201(created) and 200(updated) responses with `filename`:null and `lineno`:null. 
So just to be sure `filename` and `lineno` were updated in the docs with the `null` info in the GET response only.
POST and PATCH don't show the info. I can't tell if it's intended

![Screenshot (158)](https://user-images.githubusercontent.com/33448286/64528094-545f9b00-d310-11e9-9456-7a30e3f8218b.png)

**Comment by EnTeQuAk** [comment]
>  So just to be sure filename and lineno were updated in the docs with the null info in the GET response only.

For `POST` and `PATCH` they're marked as `(optional)` instead as you can easily ignore them for creating or updating records. That, then means that for `GET` requests they can be `null` and are so by default.

So that's fine.

**Comment by kumar303** [comment]
@EnTeQuAk what @ioanarusiczki is saying is it's confusing that the [POST request object](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#post--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-) is documented in a different style. The descriptions contain the word *optional* but the accepted values still look like `filename (string)`, for example. If the accepted value were `filename (string|null)` then it would be consistent with the `GET` response and this would be less confusing. I don't know if this is a byproduct of how the reST directives work or what.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Yes, it's what @kumar303 said. It's just the text in the docs inconsistent, between GET and the other two POST, PATCH (for `filename` and `lineno`).
