### ISSUE TITLE
Strings inside `{ }` brackets are causing a 500 error in discovery item details

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12260]
### Describe the problem and steps to reproduce it:
1. Log in with an admin account
2. Go to Admin tools -  Discovery module and select Discovery items
3. Try to open the following item details - https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/104/change/

### What happened?
`/admin/models/discovery/discoveryitem/<item>/change/` is throwing a 500 error because tha add-on author has the following display name: `{LexaDev}`

### What did you expect to happen?
No server error

### Anything else we should know?
- the issue reproduces also if the add-on name is inside `{ }` brackets
- I've tried other modules -  i.e. Abuse reports, Ratings - but they are not affected by this issue
- both -dev and stage are affected

![2019-09-03_15-22-35](https://user-images.githubusercontent.com/31961530/64173298-9fd0ff80-ce5f-11e9-86f3-15a02af5b286.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/5488331/?query=is:unresolved

Relevant code:
https://github.com/mozilla/addons-server/blob/343c95ca1845d40cc8be08e5ad1fe1899318596d/src/olympia/discovery/admin.py#L127-L132

The call to `format_html` here is a mistake, we don't even pass a dict, so this is an easy fix.

However, calling `<string>.format()` (which `format_html()` does) on user input is a bad idea, and I wonder if we do have this elsewhere that QA hasn't found yet. The following would fail too:
```python
'{foo}'.format({})
```

**Comment by diox** [comment]
Note for QA: when you have some time it'd be a good idea to try to insert `{foo}` in... pretty much every text input field you can find on the site. I went through all our code and couldn't find any other occurrences, but I'm curious to see if you can find something.

**Comment by AlexandraMoga** [comment]
The reported issue looks fixed on -dev and stage.

I'll try with the other text input fields once I have some time for exploratory.

**Comment by AlexandraMoga** [comment]
@diox I think I covered most of the text input fields form the site but I did not reproduce the issue in any other place. So, unless there are some more obscure fields that I'm unaware of, I believe we're safe.
