### ISSUE TITLE
Allow admins to reset API Credentials confirmation status for a developer or group of developers

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12280]
Followup for https://github.com/mozilla/addons-server/issues/11635

> After confirmation, re-generating keys shouldn't require confirmation again. However, it should be possible to reset the confirmation status of any or all developers in order to require confirmation again. By "possible" I just mean it should be visible in the user admin and it should be easy to ask ops to change this flag for a group of users if needed.

STR:
The following actions should be available in admin tools:
1. Reset the API Credentials confirmation status for developers.
2.  Reset the API Credentials confirmation status for developers.

**Comment by diox** [comment]
Note: the button I'm adding will *also* deactivate any existing api keys for affected users.

**Comment by ioanarusiczki** [comment]
@diox I tested this on AMO dev. 
As an admin you can: 
- Reset API Key for a single user from the user profile page. 
![one user](https://user-images.githubusercontent.com/33448286/64694582-a0dae000-d4a2-11e9-930e-77ef804a40f4.png)

- Reset API Keys for multiple users from the users profile page.
![all users](https://user-images.githubusercontent.com/33448286/64694590-a6d0c100-d4a2-11e9-9695-c82ad9f1b034.png)

In both cases, if the keys are reset from admin the user must go through the confirmation process again.
