### ISSUE TITLE
Use the add-on icon instead of the first screenshot in abuse details

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12303]
### Describe the problem and steps to reproduce it:
1. Log in with an admin account
2. Go to the Abuse report admin model
3. Open one of the listed entries - see https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/24878/change/
4. Observe the preview displayed in the add-on summary section

### What happened?
The summary section displays the first add-on screenshot

### What did you expect to happen?
The summary section displays the add-on icon

### Anything else we should know?
- we have a similar issue on the add-on review page - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/fvd-speed-dial - but in this case the add-on icon is displayed next to its title
- reproduced on dev and stage with Fx69, Win10x64

![image](https://user-images.githubusercontent.com/31961530/64538582-8fb89480-d325-11e9-8366-93d899af099b.png)

**Comment by Abhi-khandelwal** [comment]
Can I take this issue ?

**Comment by jvillalobos** [comment]
Sorry, @Abhi-khandelwal, we decided this isn't worth fixing. Please look for other issues with the good first bug label.
