### ISSUE TITLE
Generate initial django migrations

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12333]
part of #3705 

Once #10917 is done we can generate the django migrations that will be the base of the database definitions.  We should be applying them - and any future django migrations - at deploy time, rather than schematic.

**Comment by diox** [comment]
It's also worth coming up with some documentation about how to customize migrations to make them backwards-compatible - something we do right now when writing SQL migrations. Maybe something about what strategy to use in which case (delay committing the migration itself when removing a field, add new fields as nullable, etc) ?

**Comment by AlexandraMoga** [comment]
Please add STR or the qa:not needed label.
Thanks
