### ISSUE TITLE
Add-on django admin page for a deleted add-on is 404.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12348]
### Describe the problem and steps to reproduce it:

1. Delete an ad-don.
2. Visit the add-on django admin page for it.

### What happened?

404 Not Found

### What did you expect to happen?

Show django admin page for the add-on.

### Anything else we should know?

Regression caused by https://github.com/mozilla/addons-server/pull/11156.

**Comment by ioanarusiczki** [comment]
@wagnerand I verified this on admin tools dev with FF69(Win10). 
I don't see the issue as being reproducible anymore on dev.
I deleted an add-on/theme from dev hub and then went to admin tools to check the page. Indeed, a 404 is displayed on stage. 

dev versus stage 

![dev versus stage](https://user-images.githubusercontent.com/33448286/64941418-52955a80-d86f-11e9-8682-72722c8e0cac.gif)
