### ISSUE TITLE
Update `entries` in the docs for the Browse API 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12342]
This is a followup for https://github.com/mozilla/addons-server/issues/12275#issuecomment-530295346

Docs for the[ Browse API ](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-)need an update for:
file.entries[] (array) – The complete file-tree of the extracted XPI.

They're no longer an array [ ].

![update entries in the docs](https://user-images.githubusercontent.com/33448286/64795788-541d0500-d587-11e9-8ba6-8c7a25db89f3.png)

**Comment by sakshamb2113** [comment]
Hi @ioanarusiczki can i work on this issue?
