### ISSUE TITLE
Remove duplicate addon queries in reviewer tools caused by version history

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12344]
Part of https://github.com/mozilla/addons-server/issues/11797

On every review page, the add-on and its transformers are run multiple times. One of the culprits is the loading of the activity logs, tracked in https://github.com/mozilla/addons-server/issues/12055, but another is the fact that we end up accessing the `addon` field on every `Version` displayed in the history, but django doesn't know that it's the same `addon` it already has loaded. So every `Version` displayed in the history causes something like 8 extra queries *per version*.

**Comment by diox** [comment]
While working on this I stumbled upon the queries we make to support hard-deleted versions. Before 982e86965d84e0e589268948376d6602a81a451f (deployed in 2016-03-03) versions used to be hard-deleted. But because we wanted to be display reviewer comments left on versions that had since been deleted, a [hack had been put in place years before](https://github.com/mozilla/addons-server/commit/e4e5b977ca3903e868aa9eea80222f7af62fcd7d) to fetch the relevant activity logs and insert fake versions in the review page history.

That hack causes us to load all versions, and is getting in the way of the optimization I'm making here. Since versions have been soft-deleted for more than 3 years now, we are going to remove the hack. I looked at the data with @wagnerand and there are a few more recent logs that show up that need to be investigated first.

**Comment by diox** [comment]
There are 3 kinds of logs that appear because of the hack, that would no longer be displayed in the history once I remove it:
- Thousands of old entries from before we started soft-deleting versions (before 2016-03-03)
- 40 or so logs that appear accidentally because the hack doesn't care about the channel (hard to do with the way the query is set up) and the log actually refers to an unlisted version.
- 3 that are a bit more mysterious because the `ActivityLog` arguments point to a `Version`, but there is no corresponding `VersionLog`. It has to be a bug somewhere but I'm not seeing why. The action for those is either `REQUEST_INFORMATION` or `REVIEWER_REPLY_VERSION`. Maybe the `Version` has somehow been hard-deleted manually by us in the db.

@wagnerand said he wasn't concerned with those versions disappearing from the history, as long as the review page itself for those add-ons would continue working.

**Comment by diox** [comment]
Note: it's not just reviewer tools that would benefit from using `<Addon>.versions. The versions API would as well for instance.

**Comment by diox** [comment]
Another set of duplicate queries were caused by the `Version.transformer` being called explicitly on top of the call that is already being made by the manager in `get_queryset()`. That was causing an extra 2 useless queries per version being displayed.

**Comment by diox** [comment]
QA: not sure if you'll notice any performance difference, but at least make sure review page still displays all versions, their files, the correct links etc, even for deleted versions (*)

(*) Versions deleted before 2016 are no longer shown, by design.

**Comment by AlexandraMoga** [comment]
@diox can you please clarify what you mean by 'files' in the context of Add-on version history? Do you refer to "Contents" that links to addons-code-manager, or to source code files? Or both?

**Comment by diox** [comment]
I mean everything that appears in the left column for each version. You should see platforms, status, validation & contents links, permissions, code manager link, compatibility and weight.

**Comment by AlexandraMoga** [comment]
I didn't find new regressions in the Add-on version history. I checked public, disabled and deleted versions for both listed and unlisted add-ons.
