### ISSUE TITLE
Lower delay after which stale FileUploads are deleted

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12350]
We currently delete `FileUpload`s older than 180 days, every day. We technically don't need more than a few minutes, maybe a few hours just in case, for general submission purposes. 

We could easily lower the delay before deletion to something like a month or a week, leaving time to investigate in case of any weird error we'd want to look into, and stay safe. Let's do that. Less data in there makes any migrations on that table faster.

**Comment by AlexandraMoga** [comment]
Could you please add some STR to this issue?
Thanks.
