### ISSUE TITLE
Add-on version history should display the latest versions first

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12373]
Follow up for #12344 
### Describe the problem and steps to reproduce it:
1. Log in on stage with a reviewer account
2. Open the following add-on review page - https://reviewers.addons.allizom.org/en-US/reviewers/review/video-downloadhelper
3. Check the Add-on version history section

### What happened?
The versions are ordered from oldest to newest, the older versions being displayed first. The pagination is counter-intuitive as well because by clicking on 'Older' you are actually navigating to newer versions.
 
### What did you expect to happen?
The Add-on version history should list the latest versions first when the review page is opened

### Anything else we should know?
@diox this must be related to your changes from #12369 

![image](https://user-images.githubusercontent.com/31961530/65136596-8065d500-da10-11e9-89bd-f02227201ae6.png)

**Comment by diox** [comment]
This is nothing new though, it has always been like this. The order is correct, it's just the pagination links that are confusing ?

**Comment by AlexandraMoga** [comment]
@diox the pagination is one thing, but the main issue, for me at least, is that you have to paginate through all these old versions in order to reach the latest version, which is the one you'd most probably want to review.

**Comment by diox** [comment]
Ok, I misunderstood what you meant. Definitely a regression then, I overlooked something when I made my changes.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage

![image](https://user-images.githubusercontent.com/31961530/65241366-0440bf80-daec-11e9-84ca-d2edf8ff87f1.png)
