### ISSUE TITLE
Remove duplicate addon queries in devhub versions page

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12397]
Like in https://github.com/mozilla/addons-server/issues/12396 and https://github.com/mozilla/addons-server/issues/12344 devhub could use `<Addon>.versions()` in the versions page to make fewer database queries.

**Comment by diox** [comment]
Actually... it already does use it for the `version_list` view (though not some others). There are still some optimizations that can be made to reduce the number of queries in that view though.

**Comment by diox** [comment]
QA: make sure the devhub versions list still behaves correctly, including when you mix unlisted & listed versions, disable a version, etc.

**Comment by AlexandraMoga** [comment]
@diox does this issue have the correct milestone? I haven't seen your patch listed as a cherry-pick, hence the question.

**Comment by diox** [comment]
You're right, it missed the tag.

**Comment by ioanarusiczki** [comment]
@diox 
Looks good to me. 
I verified dev hub with FF69(Win10) - release testing results are [here](https://testrail.stage.mozaws.net/index.php?/runs/view/21097&group_by=cases:section_id&group_order=asc).
