### ISSUE TITLE
Remove duplicate addon queries in Versions API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12396]
In https://github.com/mozilla/addons-server/issues/12344#issuecomment-531979930 I wrote:
> Note: it's not just reviewer tools that would benefit from using `<Addon>.versions`. The versions API would as well for instance.

So let's do that - currently the versions API repeats the query to load add-on + its transformer for each version it returns.

**Comment by diox** [comment]
QA:
- Just make sure frontend doesn't have errors with the add-on detail, versions list & ratings list, and also when posting new ratings. You can also spot check those APIs manually to see if anything looks weird compared to the docs (particularly around add-on data in those APIs), but it might be easier to just check the frontend.

**Comment by AlexandraMoga** [comment]
No regressions found on the frontend  for the addon details, version list and ratings pages

I've also compared the responses for [addon detail](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail), [version list](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#versions-list), [version detail](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail) and the [ratings list](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#list-ratings) APIs gainst the documentation and I haven't spotted any deviations.

Marking the issue as verified fixed.
