### ISSUE TITLE
Fix second ALTER TABLE in migration 1197 (`file_validation`)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12393]
The second `ALTER TABLE` query in [migration 1197](https://github.com/mozilla/addons-server/blob/master/src/olympia/migrations/1197-db-schema-file-validation.sql) failed in prod:

```
stderr: b'ERROR 1452 (23000) at line 7: Cannot add or update a child row: a foreign key constraint fails (`addons_mozilla_org`.`#sql-e508_5bfd7ff`, CONSTRAINT `file_validation_file_id_48b46a5a_fk_files_id` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`))\n'
```

The `ALTER` is:

```
ALTER TABLE `file_validation`
    ADD CONSTRAINT `file_validation_file_id_48b46a5a_fk_files_id` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`);
```

Let's fix it!

---

FTR: we decided to skip this second `ALTER TABLE` as well as the other migrations in https://github.com/mozilla/addons-server/releases/tag/2019.09.19-4 on Thursday at 21:48 CEST. We updated the `schema_version` table to version `1212`.

**Comment by eviljeff** [comment]
We had similar problems with other tables on dev.  So I believe we can just add the following to migration 1197
```sql
/* There are some old entries in file_validation where the file has already been hard-deleted so there is no matching id in files.
As we're adding a foreign key constraint to the table we need to first delete the invalid data or the ALTER TABLE fails.*/
DELETE FROM `file_validation` USING `file_validation`
    LEFT JOIN `files` ON `file_id` = `files`.`id`
    WHERE `files`.`id` IS NULL AND `file_id` IS NOT NULL;
```

**Comment by AlexandraMoga** [comment]
Please add STR or the qa:not needed label.
Thanks
