### ISSUE TITLE
execute migrations on prod we didn't run on 2019.09.19

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12405]
- [x]  [1197-db-schema-file-validation.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1197-db-schema-file-validation.sql) - DELETE, ALTER
- [x] 	[1198-translations.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1198-translations.sql) - ALTER
- [x] 	[1199-versions.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1199-versions.sql) - ALTER with constraints
- [x] 	[1200-update-counts.sql](https://github.com/mozilla/addons-server/blob/d7ae3e57970e551dbcdd643b8037d511823a90fe/src/olympia/migrations/1200-update-counts.sql) - DELETE, ALTER with new fk constraint
- [x] 	[1201-users.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1201-users.sql) - ALTER, see #12372 about username
- [x] 	[1202-webext_permissions.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1202-webext_permissions.sql) - ALTER
- [x] 	[1203-users_tags_addons.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1203-users_tags_addons.sql) - ALTER
- [x] 	[1204-users_notifications.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1204-users_notifications.sql) - ALTER
- [x] 	[1205-users-history.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1205-users-history.sql) - ALTER
- [x] 	[1206-previews.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1206-previews.sql) - ALTER
- [x] 	[1207-migrated_personas.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1207-migrated_personas.sql) - ALTER
- [x] 	[1208-version-previews.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1208-version-previews.sql) - ALTER
- [x] 	[1209-db-schema-waffle-tables.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1209-db-schema-waffle-tables.sql)  - ALTER with constraints
- [x] 	[1210-db-schema-groups-users-2.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1210-db-schema-groups-users-2.sql) - ALTER
- [x] 	[1211-update-gradient-color.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1211-update-gradient-color.sql) - UPDATE
- [x] [1212-unique-lowercase-usernames.sql](https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations/1212-unique-lowercase-usernames.sql) (empty)

- [x] Also run this one, which was removed from [1186-db-schema-licenses.sql](https://github.com/mozilla/addons-server/blob/master/src/olympia/migrations/1186-db-schema-licenses.sql)
```sql
ALTER TABLE `licenses` ADD UNIQUE KEY `text` (`text`);
```

**Comment by eviljeff** [comment]
fwiw, any of these migrations should be able to be executed in any order, and worst case if they fail ignore it and skip to the next.  (Just mark it as complete above)

**Comment by bqbn** [comment]
Testing running [1186-db-schema-licenses.sql](https://github.com/mozilla/addons-server/blob/master/src/olympia/migrations/1186-db-schema-licenses.sql) has this error

```
mysql> ALTER TABLE `licenses`
    ->     MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    ->     MODIFY `text` int(10) unsigned DEFAULT NULL,
    ->     MODIFY `created` datetime(6) NOT NULL,
    ->     MODIFY `modified` datetime(6) NOT NULL,
    ->     MODIFY `name` int(10) unsigned DEFAULT NULL,
    ->     MODIFY `builtin` int(10) unsigned NOT NULL,
    ->     MODIFY `on_form` tinyint(1) NOT NULL,
    ->     MODIFY `some_rights` tinyint(1) NOT NULL,
    ->     MODIFY `creative_commons` tinyint(1) NOT NULL,
    ->     DROP KEY `text`,
    ->     DROP KEY `name`,
    ->     ADD UNIQUE KEY `name` (`name`),
    ->     /* ADD UNIQUE KEY `text` (`text`), - failing on prod db */
    ->     DROP FOREIGN KEY `licenses_ibfk_1`,  /* (`text`) REFERENCES `translations` (`id`),*/
    ->     DROP FOREIGN KEY `licenses_ibfk_2`,  /* (`name`) REFERENCES `translations` (`id`)*/
    ->     ADD CONSTRAINT `licenses_name_0308e4d2_fk_translations_id` FOREIGN KEY (`name`) REFERENCES `translations` (`id`),
    ->     ADD CONSTRAINT `licenses_text_1997f964_fk_translations_id` FOREIGN KEY (`text`) REFERENCES `translations` (`id`);
ERROR 1091 (42000): Can't DROP 'text'; check that column/key exists
```

**Comment by eviljeff** [comment]
> Testing running 1186-db-schema-licenses.sql has this error

we just need `ALTER TABLE `licenses` ADD UNIQUE KEY `text` (`text`);` executing from that migration - the rest of it has already been run.

**Comment by diox** [comment]
We're planning to run the last remaining migrations (the update_counts one and the original usernames one, which require some data fixing) on Tuesday, to get enough time to react if things go wrong (and not mess with Firefox release process if it does go wrong)

**Comment by bqbn** [comment]
Migrations in this issues are done.
