### ISSUE TITLE
Maybe avoid calling default transformer on models when fetching single instances ?

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12412]
We currently call the default transformer on our models through overriding `get_queryset` in the corresponding manager. This means that any queryset evaluation causes the default transformer to be called. That works reliably, everything is consistent.

But... When fetching a single instance, through `.latest()`, `.get()`, etc, what's the value of calling the default transformer ? The default transformers are there because we need the related data in 99% of the cases, and we'd rather fetch that in a single call rather than multiple ones when we're iterating over several instances - but when we just have a single instance, it brings no benefit over letting Django fetch the related data normally...

If we can be sure this doesn't introduce inconsistencies, avoiding to call the default transformer for single instances could reduce the number of useless sql queries made - while we generally need the related data brought by the transformer when fetching a list of objects, we more rarely need it for single fetches.

**Comment by diox** [comment]
I kinda did this manually in https://github.com/mozilla/addons-server/commit/965228d02c55ecb18f87b50b18d4119dcb20692d#diff-d5d4f5e227c5a588706b9e9f6879197eR825 for `find_latest_version()`. Not sure how easy it is to do this in a generic way though.

**Comment by eviljeff** [comment]
Is the reduction in queries for a single instance worth the inconsistency and extra complexity though? I'm not sure.

**Comment by diox** [comment]
Let's shelve this for now.
