### ISSUE TITLE
drop 'skip_register_redirect' in fxa configs

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12417]
to quote myself from #10487 
> after the authentication has taken place the only difference is whether we redirect users to the edit profile page... something I'm not sure we need anyway because it was originally implemented when addons-frontend was mobile only and we'd not gotten around to implementing the edit page. 🤔 

(splitting this out as an issue so we're clear on the feature removal)

The logic currently is:
- `default` fxa config (used everywhere on django served pages, and possibly frontend*) redirects for a new user everywhere (locally, addons-dev, addons-stage, addons-prod)
- `amo` fxa config (used by frontend*) redirects locally & addons-dev, but doesn't on addons-stage & addons-prod
- `local` fxa config (used for frontend local dev) redirects locally & addons-dev & addons-stage (it isn't available on addons-prod)
- `code-manager` fxa config (used for code manager app) copies the `amo` logic.

IMO, we should either stop redirecting any new user to the profile registration page, or redirect all new users.  The reason it was implemented (not having a frontend edit profile page) is long gone and it adds complexity on the server side (and means as many as 4 times as many fxa client key pairs need to be generated per environment)

@jvillalobos to decide if we want to redirect users who are first time AMO users to the account profile settings page or not.

*frontend uses `amo` on some environments and possibly not others but it's an ops env setting so a little opaque.

**Comment by eviljeff** [comment]
the internal logic is roughly:
- -server gets a `to` url passed along from frontend
- if new_user and not skip_register_redirect then ignore `to` url and edirect to /users/edit
- otherwise, redirect to `to`iss

If we want to force users and/or developers to set their display_name then we probably want to redirect all new users and prevent frontend from opting out some.

**Comment by jvillalobos** [comment]
In which cases would there be a `to` set? Is that initially set by AMO or does it come from somewhere else?

**Comment by eviljeff** [comment]
> In which cases would there be a to set? Is that initially set by AMO or does it come from somewhere else?

It's the page the user was on when they tried to login/register

**Comment by jvillalobos** [comment]
This would make the most sense to me:

- Send all users to the profile edit page.
- Have the button say `Create My Profile` instead of `Update My Profile`.
- If there's a `to` in the URL, send them there after the profile is created.

**Comment by eviljeff** [comment]
> Have the button say Create My Profile instead of Update My Profile.
> If there's a to in the URL, send them there after the profile is created.

addons-server can pass along the `to=` param to frontend - frontend will need some work to do something with it (and to show a different button).  Filed mozilla/addons-frontend#8666

**Comment by ioanarusiczki** [comment]
@eviljeff 
I tried a registration from AMO dev with a new account (from homepage) . After e-mail confirmation the user is redirected to edit profile page. There's a `to` parameter in the URL.

`https://addons-dev.allizom.org/en-US/firefox/users/edit?to=%2Fen-US%2Ffirefox%2Fusers%2Fedit`

Please add some STR for qa. Perhaps it's not enough what I've done. 
Thanks.

**Comment by eviljeff** [comment]
Hmm, well the `to=` is supposed to be the same you're on, and it's the same as the edit page, which is a little weird.  The frontend side might depend on changes there so perhaps try registering a new* account from a devhub page?  *doesn't need to be a new FxA account, just one that hasn't logged in to AMO before.
