### ISSUE TITLE
change travis irc notifications to slack notifications

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12416]
The notifications that currently go to #amo-bots (channel name could change)
https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications

**Comment by eviljeff** [comment]
maybe to riot/matrix now instead of slack? 🤷‍♂

**Comment by diox** [comment]
We've got #addons-bots on slack with the pullpanda notifications now, so maybe it'd make sense to move those here as well ?
