### ISSUE TITLE
 Remove duplicate addon queries in Review Notes API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12427]
Like https://github.com/mozilla/addons-server/issues/12396, like https://github.com/mozilla/addons-server/issues/12344, the Review Notes API is making too many database queries, it scales poorly when there are a number of them to fetch.

It seems to benefit from the fixes in those issues only partially, we need to figure out why (it's `ActivityLog`, so everything is a bit tricky :)

**Comment by diox** [comment]
One to get us started:
```diff
diff --git b/src/olympia/activity/views.py a/src/olympia/activity/views.py
index 4885e6f5e2..915b094434 100644
--- b/src/olympia/activity/views.py
+++ a/src/olympia/activity/views.py
@@ -24,7 +24,6 @@
 from olympia.addons.views import AddonChildMixin
 from olympia.api.permissions import (
     AllowAddonAuthor, AllowReviewer, AllowReviewerUnlisted, AnyOf)
-from olympia.versions.models import Version
 
 
 class VersionReviewNotesViewSet(AddonChildMixin, ListModelMixin,
@@ -43,8 +42,9 @@ def get_addon_object(self):
             permission_classes=self.permission_classes)
 
     def get_version_object(self):
+        addon = self.get_addon_object()
         return get_object_or_404(
-            Version.unfiltered.filter(addon=self.get_addon_object()),
+            addon.versions(manager='unfiltered_for_relations'),
             pk=self.kwargs['version_pk'])
 
     def check_object_permissions(self, request, obj):
```

However even with that a test with an `assertNumQueries` shows that some of the queries are duplicated and that it's scaling with the number of items returned, so more investigation is needed.

**Comment by diox** [comment]
QA: I don't think you'll be able to see the perf improvements, but make sure in devhub reviewer/developer discussion on a version still works, including highlighting of comments made by a reviewer after the last developer comment (should have a different background-color)

**Comment by ioanarusiczki** [comment]
@diox I verified on dev for a listed and then an unlisted addon. 
It works as before - the reviewer's comment is highlighted in yellow until the developer answers. 

![devhub conversation](https://user-images.githubusercontent.com/33448286/70535036-f6d42800-1b64-11ea-9e30-9198a5f899b9.png)
