### ISSUE TITLE
Remove ".jar" support

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12435]
This came up during an IRC discussion. We probably don't need to support `.jar` files anymore. We should remove this extension from `VALID_ADDON_FILE_EXTENSIONS` and remove potentially related code.

**Comment by willdurand** [comment]
It looks like `.jar` are associated with "complete themes": https://github.com/mozilla/addons-server/blob/7af5082717f8803a100ff1c6226ea99e0a7e23ca/src/olympia/files/utils.py#L287-L289

@eviljeff Can we remove more than the `.jar` support? Like everything that is related to "complete themes"? 🤔

**Comment by willdurand** [comment]
> It looks like `.jar` are associated with "complete themes":

Not always actually... https://github.com/mozilla/addons-server/blob/7af5082717f8803a100ff1c6226ea99e0a7e23ca/src/olympia/files/models.py#L162-L163

**Comment by eviljeff** [comment]
`.jar` should have only* been for xul themes, yeah.  (I think we just rewrote the file extension for so we didn't have to handle multiple file extensions elsewhere).  Lets strip it out.

*and inner zip files of really, really, old xul extensions.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage

Standalone `.jar` files are no longer accepted:

![image](https://user-images.githubusercontent.com/31961530/66107368-c3a37480-e5c8-11e9-8e45-31ae24186bdd.png)
