### ISSUE TITLE
Remove ".json" in `VALID_ADDON_FILE_EXTENSIONS`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12434]
I don't think we can submit json files anymore (webapps, poke @eviljeff) so we should probably update the `VALID_ADDON_FILE_EXTENSIONS` constant and the localized strings.

**Comment by eviljeff** [comment]
🙄- I can't even remember how submitting json files worked for webapps either.  (though, yes, it was added for webapps)

**Comment by AlexandraMoga** [comment]
`.json` is not listed among the accepted data types and submissions will fail:

![image](https://user-images.githubusercontent.com/31961530/66111257-2e58ae00-e5d1-11e9-83cd-1c890265e13c.png)
