### ISSUE TITLE
Cannot disable/delete latest version of Recommended Add-on

### ISSUE THREAD

**Issue by ericjung** [mozilla/addons-server#12432]
### Describe the problem and steps to reproduce it:
I released a version of my recommended add-on, FoxyProxy, with a major bug. I was unable to disable or delete it.

Steps:

1. Visit https://addons.mozilla.org/en-US/developers/addon/foxyproxy-standard/versions
2. Under **Listed Versions**, click the Delete/Disable "X" button in the same row as **Currently on AMO** Version 7.1, Status Approved.

3. Experience the message,

> The latest approved version of a Recommended extension cannot be deleted or disabled. Please contact AMO Admins if you need help with this

4. Hope and pray that your can fix the bug, upload new version, and find an admin reviewer to approve the new version really, really fast.

### What happened?

I could not stop hundreds of thousands of FoxyProxy users from automatically installing an update with a major bug.

### What did you expect to happen?

I expected to be able to disable or delete the buggy version in order to spare my users headaches.

### Anything else we should know?

Read more Hemingway, and don't spell his name with two Ms when typing it.

**Comment by eviljeff** [comment]
This was requested in https://github.com/mozilla/addons-server/issues/11535 (follow-up from https://github.com/mozilla/addons-server/issues/11074#issuecomment-496692345) so @jvillalobos to confirm if he wants to change his mind on it.

Perhaps we could instead stop the developer from the disabling the version if it's the only recommendation approved version left?

**Comment by jvillalobos** [comment]
It's a bit more complicated than that, because the immediately previous version could be not recommended. So, the most accurate restriction would be to not allow disabling the latest version of a recommended add-on if the previous approved version isn't recommended. I don't think we can avoid cases where manual admin intervention is needed.

I disabled 7.1 now. I suggest in the future to try contacting any of the admins for help (amo-admins AT mozilla DOT com).

**Comment by ericjung** [comment]
FWIW, the previous version (7.0) in this particular case was also recommended.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev and I obtained the following results:

1. developer _can_ disable current recommended version if the next available listed version is was also recommended
2. developer _can't_ disable the current recommended version if the next available listed version is not recommended
3. developer _can't_ disable the current recommended version if the next available listed version is recommended but disabled

The new messages:
 [pop-up]
![image](https://user-images.githubusercontent.com/31961530/68308111-f6072c80-00b4-11ea-8aa1-516bb91ee753.png)
[trying to bypass the hidden modal]
![image](https://user-images.githubusercontent.com/31961530/68308123-fdc6d100-00b4-11ea-9ca7-91654877a7bd.png)



@eviljeff There is the following scenario which is not covered by this patch, but I'm not sure if we want to support it:
For an add-on that has versions 1, 2, 3, 4, in which  2 is recommended, 3 is not recommended and 4 is recommended again, disabling 4 is not possible, i.e. the current implementation doesn't look down the line to find the next available recommended version, 2 in this case.

**Comment by eviljeff** [comment]
> here is the following scenario which is not covered by this patch, but I'm not sure if we want to support it:
For an add-on that has versions 1, 2, 3, 4, in which 2 is recommended, 3 is not recommended and 4 is recommended again, disabling 4 is not possible, i.e. the current implementation doesn't look down the line to find the next available recommended version, 2 in this case.

In that scenario disabling version 4 would mean 3 was the new Addon.current_version. As it wasn't recommended it would remove the recommended status of the addon - something we don't want.  (There are python tests that check that scenario is prevented).

**Comment by AlexandraMoga** [comment]
I understand what you mean and that this how the current implementation is expected to work. 
The case I'm referring to is indeed less probable but I was just trying to stress the point that, no matter if you had other recommended versions down the line, the code will look only at the next available listed version. If that version wasn't recommended, you won't be able to disable your current recommended version.
