### ISSUE TITLE
Use `is_webextension` from parsed data to determine whether to run Yara

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12436]
We currently determine whether a file should be scanned by looking at the `upload.path` value, checking that it ends with `.xpi`. This is technically valid but not very future-proof.

We can use the `is_webextension` prop in the `results` (coming from the linter).

**For QA:** please make sure we can get yara results for web extensions only.

**Comment by vcarciu** [comment]
Verified as fixed by submitting many types of webextensions and checking Yara results. Also we verified if non webextensions submissions will not generate entries in Yara.
