### ISSUE TITLE
Enable Yara in prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12433]
Given that https://github.com/mozilla-services/cloudops-deployment/pull/3410 has been approved, we can deploy the Yara rules in stage and prod. That is why I'd like to enable Yara in production next week (2019.10.03). In order to do that without any  risks, I'd like to use a [waffle sample](https://waffle.readthedocs.io/en/v0.9/types.html#samples) to enable Yara for 10% of the linted submissions (starting point).

Would that work for everyone? Should we keep both the switch and the sample or replace the switch with the sample? (we can disable the feature by setting `percent` to `0`).

Or maybe it does not make sense to use a sample and we can enable Yara for all linted submissions?

**Comment by diox** [comment]
I don't mind keeping the switch and enabling it for all if QA is ok with it based on the testing done on stage.

**Comment by willdurand** [comment]
cc @AlexandraMoga @ioanarusiczki @vcarciu

**Comment by muffinresearch** [comment]
cc @psiinon

**Comment by willdurand** [comment]
@AlexandraMoga @ioanarusiczki @vcarciu @psiinon I'd like to enable the Yara feature in stage tomorrow (Friday) so that QA can start verifying it in stage before next week's tag. Any objection?

**Comment by psiinon** [comment]
I'm good with that.

**Comment by willdurand** [comment]
@vcarciu confirmed that it was OK _via_ IRC.

I just enabled the Yara feature in stage. I'll update the push doc to enable the feature in prod next week.

**Comment by willdurand** [comment]
Once in production, please check the AMO Security Tools Grafana dashboard:

- select the prod env (top left corner)
- see the yara stats

Logs in stackdriver should give additional info. You can search for `YaraResult`.

**Comment by diox** [comment]
This has been verified by us directly.
