### ISSUE TITLE
Only set a version to YaraResult/ScannersResult when feature is enabled

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12448]
We currently always try to set a version to a `YaraResult`/`ScannersResult`, even when the features are not enabled. It's not a problem _per se_ but it is not needed and results in unnecessary error entries in the logs.

**For QA:** please make sure that `YaraResult` or `ScannersResult` can be linked to a version when the version gets created.

**Comment by willdurand** [comment]
I believe we can also restrict to web extensions too.

**Comment by vcarciu** [comment]
Verified as fixed with multiple webextensions. Yara and scanners results are correctly linked to a vers when created.
