### ISSUE TITLE
`log.exception()` calls are not sent to Sentry

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12446]
We use `log.exception()` to log errors in this app and we can see them in Stackdriver. Sentry is supposed to receive these errors too, but that does not seem to be the case.

For example, this part of the code logs exceptions and we can see them in Stackdriver but I was not able to find them in Sentry (I tried to find occurrences of "YaraResult" or "ScannersResult" in any of the environments): https://github.com/mozilla/addons-server/blob/998615a9892831aec3a9b94919fd672a4d5a6417/src/olympia/versions/models.py#L294-L308

**Comment by wagnerand** [comment]
Sounds like something we want to fix.

**Comment by diox** [comment]
Related, we have kind of the opposite problem in tasks now (which wasn't the case before we tweaked the logging config, I believe): https://github.com/mozilla/addons-server/issues/14355

I suspect that, to make it work outside of tasks, we need to do something specific. Maybe we should investigate switching to the sentry sdk python client to replace raven first, to be on a more supported configuration.

**Comment by eviljeff** [comment]
I fixed this in #14640
