### ISSUE TITLE
[Reviewer Leaderboard] Scores are reduced

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#12440]
ref: `https://reviewers.addons.mozilla.org/en-US/reviewers/leaderboard/`
Today I noticed that my score has been reduced greatly. It is gone back to what it was around Aug 6th.

After a closer look and comparison, it seems everyone's score has been reduced or reverted to an earlier state.

I asked @kewisch but he was unaware of any reason for reduction.

Update; There is also a Leaderboard on the thunderbird with some other figures !?
`https://addons.thunderbird.net/en-US/reviewers/leaderboard/`

**Comment by diox** [comment]
We think it's because we had not migrated the reviewer scores associated to those themes and so, when the lightweight themes that were already soft-deleted got removed for good, the scores were also deleted.

**Comment by erosman** [comment]
@diox  Personally speaking, I never review themes so my score wouldn't include theme reviews. Therefore, removing theme scores would have no effect on it.

It seems likely that the database or values reverted to an earlier date.
