### ISSUE TITLE
Individual add-on block for blocklist admin

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12452]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

Individual add-on block input. With the add-on guid, load metadata. Allow input of blocklist reason, URL (normally Bugzilla), min and max version. An additional checkbox will be needed to determine if the block should be exposed to older clients or only new ones.

The blocklist admin should be behind the VPN and accessible to Admin Reviewers only.

**Comment by eviljeff** [comment]
@jvillalobos about the version ranges - are the minimum and maximum relating to the versions on AMO, or the version _numbers_ themselves.  If the block is defined as those versions then, effectively any versions created between those minimum and maximum, regardless of the version number of the versions.  If the versions are the _numbers_ then a version created after the maximum version, but with a lower number, would be blocked.

e.g. Addon has versions:
pk=1, version="1.0"
pk=2, version="1.5"
pk=3, version="1.51"
pk=4, version="1.6"
pk=5, version="2"
pk=6, version="2.5"

a) amo versions : if the min version is "1.6", max is "2.5", then are we blocking versions 4, 5, 6.
b) numeric versions: min version is "1.6", max is "2.5", then we are blocking 3, 4, 5, 6.

Similarly if the user uploads a new version, version="2.4" it would be blocked under b) but not a).

I'm assuming Firefox currently, under the legacy blocklist, would be doing b) so we should keep that way of thinking?

**Comment by eviljeff** [comment]
@jvillalobos what permissions do "Admin Reviewers" have?  "Reviews:Admin"?  Or some other permission?

**Comment by jvillalobos** [comment]
> I'm assuming Firefox currently, under the legacy blocklist, would be doing b) so we should keep that way of thinking?

Yes, the logic should apply to version numbers, and we should stick to that.

> what permissions do "Admin Reviewers" have? "Reviews:Admin"? Or some other permission?

It should be gated by `Reviews:Admin`. That permission is granted to the ACE Team, the reviewer contractors (which I don't think have VPN access), and Stuart.

**Comment by AlexandraMoga** [comment]
I've verified the new individual add-on blocking on -dev and these are my results:
- a single guid can be added to the blocklist
- add-on metadata is loaded based on the guid provided
- a range of Min to Max versions to be blocked can be selected
- the two user input fields - URL and Reason - are also present
- block entries can be deleted

@eviljeff I didn't quite understand the logic behind _numeric_ versions: for example, if I have the following range of versions - `1.3`, `1.38`, `1.4` => `1.4` is considered smaller than `1.38`. The following set-up doesn't throw any errors:

![image](https://user-images.githubusercontent.com/31961530/68196702-a4ca4080-ffc1-11e9-99ff-9f71431d2e8c.png)

**Comment by eviljeff** [comment]
in versioning used by Firefox[1] *, 1.4 is less than 1.38, because 4 is less than 38.  Each part separated by dots is evaluated as a number.

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format
* and most other open source software, and Chrome,
