### ISSUE TITLE
Multiple add-on block entry

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12458]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

Allows entering multiple GUIDs to block at once, potentially thousands, so this will need to handle batch processing. The mocks detail the UX.

**Comment by eviljeff** [comment]
@jvillalobos what's the rationale behind the new blocks being a html list, but the other guids (existing and invalid) being in, what looks like, text areas?  I'm not clear what you're expecting to be able to do with them, and if you aren't planning to edit them, then why have them in a text area?

**Comment by jvillalobos** [comment]
The idea is that if the list is too long, it would be shown in some kind of scrollable text list rather than a huge page that could take forever to load. I didn't intend it to be editable.

**Comment by AlexandraMoga** [comment]
I've verified this on AMO -dev and have the following results:
- multiple guids can be added to the blocklist at the same time
 *Note: I've added >200 guids in a batch an the performance was quite good, but I see that #12870 will ensure that this will work with much larger numbers
- guids that are already blocked will be isolated in the "Already blocked' list
- invalid guids are isolated in the 'Not found' list
- the guids valid for blocking are sorted by number of users

![image](https://user-images.githubusercontent.com/31961530/69246154-d7bf2780-0bb0-11ea-9dc8-29b78cc2af1e.png)

@eviljeff I've tried to verify the following scenario mentioned in the mocks, but it doesn't seem to work: 
>The “already blocked” list should only show GUIDs that have been blocked for all versions. If the previous block is partial, this new one should override it.

For example, [this add-on](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/3/change/?_changelist_filters=o%3D-5) has only three versions blocked (out of 15), but if I'm adding its guid as part of a bulk blocking, it will be considered as already blocked => the override doesn't happen.

**Comment by eviljeff** [comment]
> @eviljeff I've tried to verify the following scenario mentioned in the mocks, but it doesn't seem to work:
>
>>    The “already blocked” list should only show GUIDs that have been blocked for all versions. If the previous block is partial, this new one should override it.
>
> For example, this add-on has only three versions blocked (out of 15), but if I'm adding its guid as part of a bulk blocking, it will be considered as already blocked => the override doesn't happen.

The way I wrote it was that any existing block would show up in the existing list, but they would be updated to `0` - `*` (and the other details updated).  Though it seems I didn't read that note in the mocks drawing carefully enough.   I'll have to fix it in a follow-up.

**Comment by AlexandraMoga** [comment]
Filed #12931 as a follow-up
