### ISSUE TITLE
Show blocklist actions in review history

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12456]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

When a block is added or deleted, an event should be added to the review history for the affected versions, indicating the date and who made the change. It shouldn't include the bug link or block reason, because it could contain sensitive information and this will be accessible to all reviewers.

**Comment by eviljeff** [comment]
The block is applied for the addon, within defined versions, so while there is an add-on message that could be displayed in the history there wouldn't ordinarily be a per-version event message generated.  I was going to just display the (single) block action event with the latest version at the time of the block - is that sufficient?  #12455 will already show the status for all the affected versions so is a version history too redundant?

Or do you actually want the event displayed with every affected version?  And if so do you have a preference if it's faked in the review view or actually generated?  (The former is probably more implementation work; the latter would generate potentially a lot more version history in the db)

**Comment by jvillalobos** [comment]
>  I was going to just display the (single) block action event with the latest version at the time of the block - is that sufficient?

I think that should be enough. Most blocks involve disabling the add-on too, so it's unlikely there will be more history pushing that log out of view.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

The version history in Reviewer tools will show an entry for each time a version block has been added, edited or deleted. The information present is: block action, date, versions affected and block author:

![image](https://user-images.githubusercontent.com/31961530/70043566-60828e00-15c9-11ea-93e5-d8831f9f2cb6.png)
