### ISSUE TITLE
List block entries in blocklist admin

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12454]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

Show list of blocklist entries, sorted by last updated by default. Should allow deleting entries or clicking through to edit them.

**Comment by AlexandraMoga** [comment]
I've verified the new Blocklist module list on -dev and the table includes all the required elements:

https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/
![image](https://user-images.githubusercontent.com/31961530/68130444-063bd200-ff24-11e9-8e0c-dc0d89c56c4b.png)

The list can be accessed by users that have `Admin:Tools` and `Reviews:Admin` permissions. For my test, the user belonged to the Discovery Recommendations Editors and Reviewers: Admins groups.

@jvillalobos wouldn't it be useful to have a search option in the list view, assuming that at some point there will be more than one page of items?
