### ISSUE TITLE
Display blocked status for add-on versions in reviewer tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12455]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

In the review page of an add-on, next to review status of each version (like `Approved`), we should also indicate if the version is `Blocked` per the current blocks. There shouldn't be an indication that a version _isn't_ blocked. This should be visible to all reviewers.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/69235777-d551d300-0b9a-11ea-855c-0db79eac9e3b.png)
