### ISSUE TITLE
Multiple add-on block removal

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12459]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

Enter multiple GUIDs to have their blocks cleared. Details in the mocks.

**Comment by eviljeff** [comment]
@jvillalobos is the list view where you can select blocks and chose the "delete selected" action sufficient?  Or do we need an actual view where guids can be entered by hand in a text box?

**Comment by jvillalobos** [comment]
The purpose of this view is to be able to revert a block of hundreds or thousands of IDs relatively easily. I don't _think_ we've had to do this before at this scale, but having a backup might be nice. @wagnerand and @kewisch, thoughts?

**Comment by eviljeff** [comment]
That's a risky feature though because it's oversimplifying what the blocks are (they're more than just a string of text representing a guid) - it wouldn't be a true revert of the previous add action because the blocks might have might subsequently changed; and any blocks that currently existed when you added them wouldn't be "new" blocks, but updates of the existing blocks, like it was specified in #12852

**Comment by jvillalobos** [comment]
I don't think that'll be much of a problem. Block edits should be rare and generally limited to more targeted blocks for shady but not outright malicious add-ons.

The bigger bulk blocks are more for malware and wouldn't normally be edited, just added (and maybe removed in case of error).

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

The 'Delete Multiple Blocks' option has been added to the blocklist view.
This option can be used for deleting 1 or more (tried with ~100) blocked GUIDs at a time.
![image](https://user-images.githubusercontent.com/31961530/71167020-8b711100-225c-11ea-8102-8634b7af325d.png)

If any of the input GUIDs doesn't belong to a valid block, the request is not processed:
![image](https://user-images.githubusercontent.com/31961530/71167013-87dd8a00-225c-11ea-86e0-2de2ec763db4.png)
