### ISSUE TITLE
Stop accepting OpenSearch add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12462]
Part of [this PRD](https://docs.google.com/document/d/1FQq47mNCRy1enLsN0giseD2tnS0OaHth3S5mZL9C8jY/edit).

Stop accepting new OpenSearch add-ons or new versions of existing ones. The message in the Dev Hub should say something like:

> Open Search add-ons are [no longer supported]() on AMO. You can [create a search extension instead]().

The first link should be a blog post and the second one to a documentation page, to be provided by @caitmuenster. We expect the blog post to go out early in Q4.

**Comment by jvillalobos** [comment]
The comms for this are already out, so this can ship now.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage.
Search tool uploads will generate the following error message:
![image](https://user-images.githubusercontent.com/31961530/68392907-7f7d3400-0173-11ea-9249-d1484def0406.png)

Other add-on types are still identified and validated correctly.
