### ISSUE TITLE
add more icon options to secondary hero shelf API

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#12466]
Turns out we'll need some additional icons (used in the secondary hero shelf) entered into the Discovery admin tool. All photon icons can be found here:

https://design.firefox.com/icons/viewer/#

From within that source, please add the following...

midi (in Permissions section)
Store Data (in Permissions)
Bookmark (in Places)
Mail (in General)
Sync (in General)
Help (in Alert)

**Comment by kumar303** [comment]
Also, midi! Ha. 🎹

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

The 6 new icons are available in the secondary module list:

![image](https://user-images.githubusercontent.com/31961530/65973068-6813a280-e473-11e9-8536-6f5a8aabebb1.png)
