### ISSUE TITLE
Import current blocklist data

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12460]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

This will require coordination with the admin reviewers, because many blocklist entries will need to be broken down into a format compatible with what will be stored on AMO. Please ping me in advance of this being needed.

**Comment by eviljeff** [comment]
What scale of data are we talking about here?  1k 10k 100k?  Can you point to some example data so I can look at the format, properties, etc?

**Comment by jvillalobos** [comment]
The [current XML blocklist](https://github.com/mozilla/addons-server/files/3703889/blocklist.xml.zip) is about 350 Kb. We would only need to import what's under `<emItems>`, which is the majority of its contents. It looks like there are 800+ entries, though converting them to single-block-per-id will likely push the count to double or triple that.

**Comment by jvillalobos** [comment]
Also worth noting: many of the current blocklist properties are going to be dropped, which is specified in the PRD doc. So, things like app-specific blocks or hard/soft blocking wouldn't be supported anymore.

**Comment by eviljeff** [comment]
I'm assuming there's no requirement for an ongoing feature to be able to import/query blocklist data with the existing kinto backend?  I.e. this would be something we do once to populate AMO's db with the historic blocklist.

**Comment by jvillalobos** [comment]
That's right. AMO should become the source of truth by the end of this process.

**Comment by eviljeff** [comment]
xml blocklist:
https://firefox.settings.services.mozilla.com/v1/blocklist/3/%7B3550f703-e582-4d05-9a08-453d09bdfdc6%7D/70.0/
json blocklist:
https://firefox.settings.services.mozilla.com/v1/buckets/blocklists/collections/addons/records

**Comment by wagnerand** [comment]
> xml blocklist:
> [firefox.settings.services.mozilla.com/v1/blocklist/3/%7B3550f703-e582-4d05-9a08-453d09bdfdc6%7D/70.0](https://firefox.settings.services.mozilla.com/v1/blocklist/3/%7B3550f703-e582-4d05-9a08-453d09bdfdc6%7D/70.0/)

That is the blocklist for Thunderbird. The correct link is:
https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/70.0/

**Comment by eviljeff** [comment]
that will teach me to look at https://github.com/mozilla-services/kinto-amo/ as the source of reference 🙄

**Comment by eviljeff** [comment]
Looking in the existing blocklist (the JSON version, because it's easier to read): 884 rules in the current blocklist; 30 are Thunderbird specific, so 854 Firefox applicable.  264 contain regexs though, which aren't supported in the AMO tool.  

_Some_ of the 264 regexs could potentially be automatically expanded to multiple GUIDs (where it's clearly just a list of guids in a regex) but that's quite risky; and the rest can't be anyway (e.g. they contain matching syntax which could match an indeterminate number of guids).  What should happen with those existing blocks @jvillalobos ?  

Also, is it intended that a block imported from the existing kinto blocklist could be edited like a new block, and the change reflected in the kinto blocklist?  Note in the case of the existing regex blocks that match multiple guids it won't be possible to reliably edit them if they're broken down into a number of different blocks.

**Comment by wagnerand** [comment]
> _Some_ of the 264 regexs could potentially be automatically expanded to multiple GUIDs (where it's clearly just a list of guids in a regex) but that's quite risky; and the rest can't be anyway (e.g. they contain matching syntax which could match an indeterminate number of guids). What should happen with those existing blocks @jvillalobos ?

We have https://github.com/kewisch/mozblocklist which resolves block patterns to actual GUIDs. I can provide a list of GUIDs and their block ranges if that helps.

> 
> Also, is it intended that a block imported from the existing kinto blocklist could be edited like a new block, and the change reflected in the kinto blocklist? Note in the case of the existing regex blocks that match multiple guids it won't be possible to reliably edit them if they're broken down into a number of different blocks.

Generally yes, but it depends on when we are going to move to blocklist v3. Could we live with the additional overhead in v2 for a while if we were to convert all multi or regex-blocks to single ones right now in kinto?

**Comment by eviljeff** [comment]
> We have https://github.com/kewisch/mozblocklist which resolves block patterns to actual GUIDs. I can provide a list of GUIDs and their block ranges if that helps.

After talking through the problem with Stuart we're just going to match the regex directly against the list of guids in the AMO DB to identify the appropriate guids to block.  (The only problem here is the "point in time" limitation - that the regex will only match against current guids and not future ones - but it seems that all recent regexps have just been designed to match a list of finite guids anyway)

**Comment by eviljeff** [comment]
@jvillalobos the current blocklist's detail block contains up to 4 items: "name", "who", "why", and "bug".  Not all blocks contain all the details, though most seem to contain "bug" and "name" at least.
e.g.
```JSON
 "details": {
        "bug": "https://bugzilla.mozilla.org/show_bug.cgi?id=1336635",
        "who": "All users of Firefox 52 and above who have this add-on installed.",
        "why": "This add-on breaks the Firefox user interface starting with version 52.",
        "name": "360 Internet Protection versions 5.0.0.1009 and lower"
      },
```

I'm assuming `bug` should go in `url` but which of the others should go into the single `details` property on the block?  Or include them all (e.g. `details = name + who + why`)?

**Comment by eviljeff** [comment]
@jvillalobos regarding which blocks are actually imported.  I'm assuming that we're importing **all** the blocks, except those with a target application that isn't Firefox.  (i.e. there's no age/version cut off).  What about severity though?  I know that's been dropped in v3 so are we importing both the severity 1 and 3 existing blocks?  (All new blocks pushed to the legacy blocklist would be severity=3)

**Comment by jvillalobos** [comment]
> The only problem here is the "point in time" limitation - that the regex will only match against current guids and not future ones

That's fine with me.

> I'm assuming bug should go in url but which of the others should go into the single reason property on the block? Or include them all (e.g. reason = name + who + why)?

Yes, `bug` should go to `url`. `who` and `name` can be dropped, and `why` should become `reason`. I think `name` is still required on the kinto side, and it's used to generate the title of the blocklist web pages, so we need to figure something out for when AMO becomes the source of truth.

> I'm assuming that we're importing all the blocks, except those with a target application that isn't Firefox. (i.e. there's no age/version cut off). 

Yes. And Andreas actually cleaned up a bunch of old blocks a couple of days ago.

> What about severity though? I know that's been dropped in v3 so are we importing both the severity 1 and 3 existing blocks? (All new blocks pushed to the legacy blocklist would be severity=3)

Yes, all blocks would have severity=3 moving forward.

**Comment by AlexandraMoga** [comment]
@eviljeff I don't see the data imported on -dev. Was it imported only on prod?

**Comment by eviljeff** [comment]
I ran the command and imported some of the blocks on dev.  But some of the blocks are quite complicated, and there are a lot of them, so only about half got processed before the command stopped.

It's possible to QA this to an extent therefore, but I think I'm going to have to change the processing to run in celery tasks so one large block doesn't prevent the rest from being created.  And possibly keep track of which blocks have already been processed better (which doesn't happen right now)
