### ISSUE TITLE
Edit add-on block

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12464]
Part of this [PRD](https://docs.google.com/document/d/14_Xz_r46yQF4wN7BtrgWfWBdjEqCVdY7d8T_ZjVf1OE/edit). [Mocks](https://docs.google.com/drawings/d/1K6mpb_06oB1MYpQF3gagolWoDCMEHK8Sc_LMvMH6ass/edit).

When a block already exists for an add-on, the individual add-on block page should allow admins to edit that block. Note that this restricts add-ons to only having one active block at a time.

The edit page should also display the blocklist history for that add-on, with all of the details (link, reason, time, who made the change, and whether the block applies to old clients).

**Comment by eviljeff** [comment]
@jvillalobos  In the mocks you say:
> This assumes that there only will be a single block per add-on GUID, which can be updated as needed. Historically we’ve had a few blocks that span multiple version ranges. We need to decide if that’s worth the added complexity.

Have you made a decision on that since?  It changes the model structure because we need to store a second level of block relating to the version range and not just store it all in a single model.

**Comment by eviljeff** [comment]
@jvillalobos in the mocks for add single guid and edit there's an "updated" field.  Is that the date the _block_ was updated (which would be blank for add) or the _addon_ was last updated?

**Comment by jvillalobos** [comment]
The add-on. The blocklist history should indicate creation/update dates.

**Comment by AlexandraMoga** [comment]
Verified on -dev:

- all the entries form listed in the Block module can be edited in the `/change/` view
- editable fields are:
  - min and max version
  - URL
  - Reason
  - Include in legacy checkbox 

The Block history section will show a list of changes made on the current add-on block:
![image](https://user-images.githubusercontent.com/31961530/68486814-96db2080-024a-11ea-861e-a52c3b823ed1.png)
