### ISSUE TITLE
Remove jar support in `files/utils.py` and `localepicker` code

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12478]
After #12435, there is one last occurrence of "jar" in `files/utils.py`: https://github.com/mozilla/addons-server/blob/c99ff0ad47940a4dcd1de24b14bfe8ebb9650009/src/olympia/files/utils.py#L801-L807

To quote @eviljeff, this is for "very old xul extensions" and "xul langpacks". It is related to a "locale picker" feature that we might not need anymore too.

**Comment by diox** [comment]
Could repurpose this to remove `localepicker` code entirely.
