### ISSUE TITLE
[Signing api] User with unlimited submission rights on amo is blocked by a server submission restriction

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12470]
Prerequisites: Create a test user with the following permissions in django admin:
- add the user to the Language pack submission group
- on the user admin page, flag the `Bypass upload restrictions` option

### Describe the problem and steps to reproduce it:
Try to submit  several consecutive add-ons through the [signing API](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#signing)

### What happened?
After several attempts, you'll receive a 429 error

### What did you expect to happen?
Your user should be able to do unlimited submissions 

### Anything else we should know?
- with the above set-up, the user is whitelisted on the app level, but the 429 I'm receiving is controlled by ops (this was pointed out by @diox)

**Comment by diox** [comment]
This is https://github.com/mozilla-services/cloudops-deployment/blob/6055a664c313af95eff7b0b1b88c64bf219c57c5/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L493-L504

@bqbn addons-server should handle rate-limiting of this endpoint by itself nowadays. Can we remove the nginx rule ? It can still be useful in some scenarios where we don't even want the app to be hit by requests, but I don't think that's necessary here.

**Comment by bqbn** [comment]
https://github.com/mozilla-services/cloudops-deployment/pull/3434 removes the rate limit. The change has been deployed to -dev and -stage.

**Comment by AlexandraMoga** [comment]
I've repeated the tests in -dev and stage and there is no rate limiting for unrestricted users.
The limits set at the application level are still applying for regular users.

Marking the issue as verified fixed.

**Comment by diox** [comment]
@wagnerand it should have (we still have rate limiting, but it's handled by the app)

**Comment by bqbn** [comment]
> @bqbn has this been deployed to prod as well?

Yes, PR https://github.com/mozilla-services/cloudops-deployment/pull/3434 has been deployed to -prod as of 10/2.
