### ISSUE TITLE
Remove the ability to re-validate a file

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12488]
It seems possible to revalidate a file in DevHub. I am not sure who is able to do that but is it actually needed?

This makes our validation logic quite complex, so if this is not useful/used anymore, we could probably remove it. WDYT?

**Comment by diox** [comment]
The code:
https://github.com/mozilla/addons-server/blob/9f77f21027860353b3e15d47323dff4d4a265f95/src/olympia/devhub/views.py#L671-L684

So the question is, does the `FileValidation.DoesNotExist` bit ever happens. I have a hunch it doesn't since nowadays `File` and `FileValidation` creation should always be inside transactions, but it'd be good to verify this somehow.

**Comment by wagnerand** [comment]
The idea behind revalidating files is to get an updated assessment after vlidation/linter rules have changed. I don't think we use individual revalidation too often, whenever we do bigger changes for risk-weighting of files, we do a mass revalidation.

**Comment by diox** [comment]
This is different from what we're talking about. Revalidating a file in devhub is only possible, as the code I linked above shows, if no validation already exists for the file.

**Comment by wagnerand** [comment]
Ah ok. If we can verify that the bit you mentioned can never happen, it should be safe to remove re-validation.

**Comment by diox** [comment]
Just checked: On dev, stage and prod, for extensions (*), there hasn't been a `File` without a `FileValidation` in the past 4 years approximately. I used this query to find out:

```sql
SELECT COUNT(*)
    FROM `files`
    LEFT OUTER JOIN `file_validation` ON (`files`.`id` = `file_validation`.`file_id`)
    INNER JOIN `versions` ON (`files`.`version_id` = `versions`.`id`)
    INNER JOIN `addons` ON (`versions`.`addon_id` = `addons`.`id`)
    WHERE (`files`.`created` > '2016-01-01'
    AND `file_validation`.`id` IS NULL
    AND `addons`.`addontype_id` = 1)
```

This matches with the date https://github.com/mozilla/addons-server/issues/1154 was introduced, as I suspected.

(*) Some types like search engines don't have validation results attached.

**Comment by wagnerand** [comment]
Running that query on production returns a count of 0 as well.

**Comment by EnTeQuAk** [comment]
Then this should be quite safe to remove. That particular code has been the reason for many workarounds in the past so It'll be nice to see it :fire:

**Comment by diox** [comment]
Note: because we want to keep mass revalidation possible, I think `Validator()` will have to keep the ability to validate a `File`, and we'll need to keep the `validate_file` task. Removing the synchronous calls in the devhub view is still a useful cleanup though.

**Comment by AlexandraMoga** [comment]
If I remember correctly, all the dictionaries migrated last year didn't have any validation results attached and used to have the 'Re-validate' option next to the migrated version.
Looking at this example, that option is no longer available:

![image](https://user-images.githubusercontent.com/31961530/66106011-88537680-e5c5-11e9-9a48-a211f801f158.png)

@diox should this code removal impact any other areas? I'm trying to understand if we should spend more time looking for regressions.

**Comment by diox** [comment]
No other impact, and that's fine that the migrated dictionaries don't have validation attached.
