### ISSUE TITLE
Build local development images via CircleCI

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#12490]
In the past we relied on dockerhub auto-builds to build docker images for local development. That functionality has been broken for months now.

While this is the case (and the solutions aren't simple unfortunately) we should switch to using our already running CircleCI infrastructure to push those images to dockerhub.

**Comment by diox** [comment]
Agreed. Note post posterity that we already push /deploy/ images through CircleCI, but those are different (mostly for historical reasons - but unifying the docker images might be out of scope for this issue)

**Comment by EnTeQuAk** [comment]
> but unifying the docker images might be out of scope for this issue

Way out of the scope, that's a completely different story. Unifying got easier now that we're using uwsgi locally too but it's still a lot of work imo.
