### ISSUE TITLE
Split repack and validation tasks

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12505]
This is needed for https://github.com/mozilla/addons-server/issues/11984.

**For QA:** please make sure all possible add-ons can be uploaded and validated, ignoring the problem with large add-ons, which is described in https://github.com/mozilla/addons-server/issues/12415

**Comment by vcarciu** [comment]
Verified as fixed using many types of addons(Langpacks, Searchtools, Themes, Webext ..) and validation passed .
