### ISSUE TITLE
Set `VALIDATOR_TIMEOUT` to 360s for all envs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12513]
Trying to fix #12415, we noticed that `VALIDATOR_TIMEOUT` was set to 360s in prod and 110s in dev/stage, so let's use 360s everywhere.

**Comment by vcarciu** [comment]
Verified as fixed on -dev and Stage : 
![validator](https://user-images.githubusercontent.com/1583842/66469478-935c4a00-ea90-11e9-9490-05f3baf35a9d.png)
