### ISSUE TITLE
Update SQLAlchemy

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12512]
SQLAlchemy dependency has been pinned to an old version for a while, let's try to update it.

QA: this should only affect the update service, so make sure that still works.

**Comment by ioanarusiczki** [comment]
@diox 

> QA: this should only affect the update service, so make sure that still works.

Does this mean update of an add-on to a new version or it involves all operations of updating an add-on in dev hub where it's possible (such as name, category and so on ).

**Comment by diox** [comment]
Update to a new version.

**Comment by ioanarusiczki** [comment]
@diox I'll leave the verified label for later, after the release testing is completed on Thursday but I submitted new versions on AMO dev with FF69 (Win10) without problems, the versions were auto-approved.

**Comment by diox** [comment]
The important thing to verify is that updates work on clients that had installed a previous version. That's what I meant by update to a new version.

**Comment by ioanarusiczki** [comment]
@diox I verified the update service (update to a new version of an already installed add-on) on both AMO dev and AMO stage with FF69 (Win10). Works for me. I tested both ways (manual update using "Check for updates" and then restarting the browser).
