### ISSUE TITLE
drop is_source_public property from Addon api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12514]
depends on #12418 

quoting @diox:
> The functionality is also exposed in the API under a different name, is_source_public. This needs special care as the API must keep this field for backwards-compatibility purposes. You'll need to modify the declaration of the field in src/olympia/addons/serializers.py to always return False. I suggest making it a serializerMethodField() instead of the BooleanField it is now and implementing a get_is_source_public(self, obj) in the serializer class, simply having it return False. Tests will have to be updated here as well.

**Comment by ash-13** [comment]
Hey @eviljeff I would like to work on it , can i take this up?

**Comment by eviljeff** [comment]
@ash-13 you can work on it.  Though you'll need an understanding of Django rest framework and you will need to look yourself how our `DRF_API_GATES` implementation provides shimming/removing properties from different versions of the API.  It's not a good first bug.

**Comment by ash-13** [comment]
@eviljeff Okay I will start django , then I will start good first but
Then guide me !

**Comment by junngo** [comment]
@eviljeff 
I am going to modify it according to diox guide. And It will be modified so that it can be returned only from v3 api.
If It is right, Can I work on it?

**Comment by eviljeff** [comment]
@junngo go ahead.

**Comment by eviljeff** [comment]
QA: check the API response doesn't contain the `is_source_public` property in /api/v4; but does in api/v3 - where it should always be False.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified on dev for
for https://addons-dev.allizom.org/api/v4/addons/addon/502872/
`is_source_public` is no longer available 

for https://addons-dev.allizom.org/api/v3/addons/addon/502872/
`is_source_public` is false

![source public - false](https://user-images.githubusercontent.com/33448286/68777984-2dd51d80-063b-11ea-9739-dcdcff21303c.png)
