### ISSUE TITLE
provide documented stats API

### ISSUE THREAD

**Issue by jab** [mozilla/addons-server#1251]
Hi Mozillians! I work on https://github.com/uProxy, a cross-platform (including Firefox) censorship circumvention tool. I just started looking into aggregating download stats from the various places that distribute uProxy, including the Firefox Add-ons site. Since I haven't yet found anything that does this already, I may write a script to do it myself, but currently this would mean using undocumented APIs designed for the add-ons site that might change at any time. I think there would be value in providing a documented stats API to Firefox add-on developers. What do you think?
Thanks for your consideration, and thanks for the great work over there!

**Comment by andymckay** [comment]
We hope to move all of AMO to having a back end documented API. Have to confess stats is never a huge priority and is somewhere pretty far down the order of things happening, might happen one day though :+1:

**Comment by jab** [comment]
Thanks for the quick response, @andymckay. In that case, it sounds like the quickest win would be if AMO would allow Firefox add-on developers to paste in a Google Analytics tracking ID, which if provided would be used to send download events to Google Analytics.

Some other browsers' extension sites (e.g. Chrome's) actually do this already. So developers of cross-platform browser extensions could use the same GA tracker in AMO as they use in other browsers' stores, and then more easily see how they're doing in Firefox as compared to the other platforms they support.

Would be cool if could be alternatives to GA for this too, but in practice GA is the only one I've seen used by other sites in this manner (e.g. bitbucket.org, readthedocs.org, etc.).

**Comment by andymckay** [comment]
I'm all for Mozilla doing less and maintaining less. However a couple of problems I see are: 1) daily usage data doesn't come from a webpage but rather update pings sent through version check to Mozilla servers 2) terms and conditions etc of google analytics - not everyone in the mozilla community might be happy about such tracking (although it is used on a.m.o already so the point may be moot).

**Comment by jab** [comment]
Glad there's some interest!

Re 1), would it work for tracking downloads? Usage would be nice, but even if it would only work for downloads, it could still be better than no GA integration at all for lots of add-on developers.

Re 2), I definitely appreciate those concerns. Sounds to me like it's moot if a.m.o. uses GA already, but should anyone else be pinged to make sure it's ok?

In the meantime, if this is something an open source contributor such as myself could work up a PR for, I'd be happy to take a crack at it if that could be helpful.

**Comment by andymckay** [comment]
Something very similar, but not using GA, but just making an API is happening in #1395, specifically in #1414.

**Comment by jab** [comment]
Thanks for the update @andymckay, following along over at #1414! In the meantime, could there still be interest in also supporting Google Analytics? To many add-on developers, this could actually be preferable compared to writing more code to call the new stats API. I might spend a couple hours trying to work up a PR for GA integration on spec, unless you think there's low chance it'd get merged?

**Comment by andymckay** [comment]
I would be for this if it meant that we could remove stats from AMO, but because of data coming through Firefox Telemetry, I'm not sure if that would be possible. If we could get the data from internal sources and send it to the developers GA account, that would be pretty sweet.

However, I would actually be against this because: a) it doesn't remove any code from AMO just adds in more we have maintain, support, QA, pay security bounties on etc. b) it duplicates existing functionality we've got in stats. 

Given a) and b) there isn't a clear win here.

**Comment by jab** [comment]
> If we could get the data from internal sources and send it to the developers GA account, that would be pretty sweet.

Isn't this totally possible since the upgrade to Universal Analytics? Here is a relevant blog post from a couple years ago:
https://coderwall.com/p/xpjhbw/track-server-side-events-from-rails-in-google-analytics

Would this allow you to switch to using GA as the sole back-end and front-end for tracking add-on analytics, freeing AMO from this responsibility?

**Comment by jab** [comment]
Hi @andymckay, have you had a moment to take a look at Google Analytics server side events? Is there any interest in offloading stats to GA entirely?
