### ISSUE TITLE
 Preserve IP addresses for deleted users for 6 months

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12522]
### Describe the problem and steps to reproduce it:

In order to fight bad actors, we need to preserve the `last_login_ip` of a deleted user for some time (similar to #11560, but for an account deleted by the user themselves.)

### What happened?

`last_login_ip` gets cleared on account deletion.

### What did you expect to happen?

Keep `last_login_ip` for 6 months.

### Anything else we should know?

Legal and Trust/Security have signed-off on this. @muffinresearch can confirm if needed.

**Comment by AlexandraMoga** [comment]
Verified on -dev. 
The IP address is not cleared from the admin manage profile page, if the profiles are deleted by users themselves.

 @diox, for completeness, we should probably test that the IP is cleared after six months after the account deletion or ban (also reduced from 12 to 6 months).

I have the following users which you can modify in the db:
Deleted: 10641938
Banned: 10641937
We can set back the dates for both of them at Apr. 1, 2019, 09:00 a.m

**Comment by AlexandraMoga** [comment]
The IP field was cleared for the users mentioned above.
All is working as expected, so I'm marking the issue as verified fixed.
