### ISSUE TITLE
List `YaraResult` entries with matched rules by default in admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12549]
The admin page that lists the `YaraResult` entries shows **all** the entries. I think by default we should only list the entries that have matched rules and provide a filter to show all the entries if needed (which is likely to debug rules, etc.)

**Comment by vcarciu** [comment]
Default "Yara results" entries are the ones with matched rules. However I verified if filters are working as expected :
![yarafilters](https://user-images.githubusercontent.com/1583842/66570809-fb855b80-eb76-11e9-804a-2fce121568f7.gif)


Also, maybe it will be useful to add one more filter for listing only entries with not matched rules. My suggestion is to name it "Without matched rules only" and to rename "With\without mathced rules" to "All Entries" for a better visibility.

**Comment by willdurand** [comment]
> Also, maybe it will be useful to add one more filter for listing only entries with not matched rules. My suggestion is to name it "Without matched rules only" and to rename "With\without mathced rules" to "All Entries" for a better visibility.

@diox @wagnerand what do you think? (makes sense to me)

**Comment by diox** [comment]
Yes. I'm also tempted to default to `All entries` just because it feels more natural. But that's for @wagnerand to decide
