### ISSUE TITLE
Implement "hamburger" menu in devhub landing header for mobile

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12556]
Split out from #11651 because it makes enabling #11651 in a single week more risky.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Win10x64 and Android 8.0

[Menu - logged out]
![2019-10-29_13-36-02](https://user-images.githubusercontent.com/31961530/67764529-de93c800-fa52-11e9-8b62-865d1898c92c.gif)


[Menu - logged in]
![2019-10-29_13-35-13](https://user-images.githubusercontent.com/31961530/67764537-e2bfe580-fa52-11e9-802d-3cef89c1afd0.gif)
