### ISSUE TITLE
Implement new footer for devhub landing page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12555]
#11651 specified a new footer to match extensionsworkshop but it wasn't implemented with that issue because the mocks are inconsistent: In logged out view it's the new extension-workshop style footer.  But logged in the sketch file shows the *old* footer for desktop size and no footer at all for mobile size.  

It's unclear if those were all deliberate choices or if there was no particular attention to the logged in view so just included a grab of what was there on desktop already.  That the logged in mobile view doesn't include a footer is an existing issue #4693 - we should fix it at the same time.

@jvillalobos to clarify - IMO we should be using the same footer for both logged in and logged out users, and showing it on mobile and desktop.

**Comment by jvillalobos** [comment]
Agree that we should show the same info on desktop and mobile.

The footers are a bit more involved, I think. The footer in the logged in view of DevHub has a bunch of links that aren't covered in the new footer, including some that are specific to AMO DevHub, so it would make sense to keep. I'm tempted to say that we should stick the new footer below the old one and then remove some duplicate content from the old one, in the logged in view only.

Another thing I just noticed is the language selector at the bottom of all AMO pages. That's not part of the mocks, but I think it should be added to the new footer, since it should appear at the very bottom.

/cc @caitmuenster

**Comment by caitmuenster** [comment]
The intention was to replace the footer of the logged-in view of the Dev Hub. I'm a +1 for adding in the new footer and then de-duping content from the old one in the logged in view. 

A lot of links from the old footer go to MDN; those will need to be updated to pages on EW.

**Comment by jvillalobos** [comment]
I started [this doc](https://docs.google.com/document/d/1CPZUrNxhdGIXyF6PTI5L9BMBp8jgrxuKHTSJoUvZgxk/edit) to figure out what to do with the old footer. Some sections need merging and we should figure out if we can have all of these Resource links in one row instead of two.

**Comment by birtony** [comment]
Hey,

I have followed all the discussion and it seems that there's certain unclarity regarding the final decision on what to include into the footer.  Nevertheless, I would love to contribute to this issue/add-on.

I have requested access to [the doc](https://docs.google.com/document/d/1CPZUrNxhdGIXyF6PTI5L9BMBp8jgrxuKHTSJoUvZgxk/edit) to figure out what is the situation and whether it is possible to start working on the issue. 

Please, let me know if I can be of any help here!

**Comment by jvillalobos** [comment]
@birtony I suggest you look for issues with the label "contrib: good first bug" or "contrib: welcome". This is not one of them.

**Comment by birtony** [comment]
@jvillalobos alright, thank you for the guidance!

**Comment by muffinresearch** [comment]
Before work starts on this, it would be good to make sure the design is in-line with the direction for branding and fits what is being used on other properties. It would be a pity to have to do it twice. 

Hopefully whatever is built for this can be extended (eventually - a good time will be when we can change the header too) over the rest of the django-based site to make things more consistent.

**Comment by jvillalobos** [comment]
I don't think we need to block on that. The logged out view has its down design, which aligns with workshop, and the logged in view is just using the old design. 

Whenever we make design changes on the site we rarely have the resources to make them across the board, so I don't think we win anything by holding on this.

**Comment by AlexandraMoga** [comment]
@eviljeff I've looked at the footer mock-ups and at the conversation from [this doc](https://docs.google.com/document/d/1CPZUrNxhdGIXyF6PTI5L9BMBp8jgrxuKHTSJoUvZgxk/edit#) and I have an observation:
- the mock and the doc mention that the "Connect with us " (blue) footer should  be present  both in logged in and logged out view, but I can't see it. Are we shipping the page without that?

**Comment by eviljeff** [comment]
see #12613

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage:

[Desktop - logged out]
![image](https://user-images.githubusercontent.com/31961530/66988254-e3f42880-f0ca-11e9-8abf-8942bc51cdc5.png)

[Desktop - logged in]
![image](https://user-images.githubusercontent.com/31961530/66988282-ee162700-f0ca-11e9-84b1-dd2ff1007238.png)

[Android - logged in]
![image](https://user-images.githubusercontent.com/31961530/66988299-f66e6200-f0ca-11e9-8003-10f02c4bfbfa.png)
