### ISSUE TITLE
Update emails don't have proper email headers

### ISSUE THREAD

**Issue by keganlance** [mozilla/addons-server#12551]
### Describe the problem and steps to reproduce it:
Update an add-on. An email will be sent about the updated add-on.

### What happened?
A warning stating "This email has failed its domain's authentication requirements. It may be spoofed or improperly forwarded!" pops up in my mailing software (protonmail).

### What did you expect to happen?
Having no such warning

### Anything else we should know?
Some possible relevant email headers:
Received: from s1-b166.socketlabs.email-od.com (s1-b166.socketlabs.email-od.com
  Received: from r2.sg.in.socketlabs.com (r2.sg.in.socketlabs.com [142.0.179.12]) by
 mxsg3.email-od.com with ESMTP(version=Tls12 cipher=Aes256 bits=256); Tue, 7 May 2019
 09:45:14 -0400
 Received: from ip-172-31-26-109.us-west-2.compute.internal
 (ec2-54-186-199-104.us-west-2.compute.amazonaws.com [54.186.199.104]) by
 r2.sg.in.socketlabs.com with ESMTP; Tue, 7 May 2019 09:45:14 -0400
 Authentication-Results: mail20i.protonmail.ch; dmarc=fail (p=none dis=none)
 header.from=mozilla.org
 Authentication-Results: mail20i.protonmail.ch; spf=pass
 smtp.mailfrom=35d0.10.$my_email_address@email-od.com
 Authentication-Results: mail20i.protonmail.ch; dkim=pass (1024-bit key)
 header.d=email-od.com header.i=@email-od.com header.b="Met1rwuL"
 Dkim-Signature: v=1; a=rsa-sha256; d=email-od.com;i=@email-od.com;s=dkim;
 c=relaxed/relaxed; q=dns/txt; t=1557236716; x=1559828716;
X-Spam-Status: No, score=-0.0 required=4.0 tests=DKIM_SIGNED,DKIM_VALID,
 DKIM_VALID_EF,HEADER_FROM_DIFFERENT_DOMAINS,SPF_HELO_PASS,SPF_PASS, T_DKIMWL_WL_MED
 autolearn=ham autolearn_force=no version=3.4.2
 X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on maili.protonmail.ch

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-19)

**Comment by muffinresearch** [comment]
@bqbn is there anything we should be setting with socketlabs to ensure the correct headers are sent?

**Comment by bqbn** [comment]
Given that both SPF and DKIM authentication pass, and the `header.from` and `smtp.from` domains are different, this may be due to DMARC complaining the two from address are not aligned.

We can check with Socketlabs to see if there is a configuration for that.

Besides `nobody@mozilla.org`, what other RFC5322.From addresses do we use to send emails?

**Comment by diox** [comment]
I see 2 different cases in our code. It's either:
- `ADDONS_EMAIL` (or its alias `DEFAULT_FROM_EMAIL`), which is `"Mozilla Add-ons <nobody@mozilla.org>"`
- `NOTIFICATIONS_FROM_EMAIL`, which is `"notifications@%s" % settings.INBOUND_EMAIL_DOMAIN`, where `INBOUND_EMAIL_DOMAIN` is coming from an env variable. In addition the name of the user that triggered the activity message is added before the email.

**Comment by diox** [comment]
Should have been fixed last Thursday in https://mozilla-hub.atlassian.net/browse/IO-2807

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-19
