### ISSUE TITLE
Firefox prevents FPN add-on from installing from new tabs/windows/private windows

### ISSUE THREAD

**Issue by acornestean** [mozilla/addons-server#12562]
### Describe the problem and steps to reproduce it:
Firefox will prevent the installation of FPN add-on (Firefox Private Network) when using either middle click OR right click and “Open Link in New Tab” / “Open Link in New Window” / “Open Link in New Private Window” on the “+ Add to Firefox” button from https://private-network.firefox.com while also displaying a door hanger stating this prohibition. For further details, please see the attached video (the video depicts only the middle click being performed on the button, however, the same results are obtained when performing the rest of the mentioned actions, as well).

Note: Users can properly install the add-on by left clicking the above mentioned button.

[Steps to reproduce]:
1. Install a VPN and set it to United States for the extension to be available for installation from https://private-network.firefox.com
2. Navigate to https://private-network.firefox.com
3. Locate the “+ Add to Firefox” button and middle click it OR right click it and select “Open Link in New Tab” / “Open Link in New Window” / “Open Link in New Private Window”
4. Switch to the newly opened tab/window/private window
5. Notice that a door hanger is displayed stating that Firefox prevented the add-on installation

### What happened?
The browser prohibits the installation of the add-on from new tabs/windows/private windows opened via middle click or right click and “Open Link in New Tab” / “Open Link in New Window” / “Open Link in New Private Window” performed on the “+ Add to Firefox” button while also displaying a door hanger stating this.

### What did you expect to happen?
The browser should allow the installation of the add-on from new tabs/windows/private windows opened via middle click or right click and “Open Link in New Tab” / “Open Link in New Window” / “Open Link in New Private Window” performed on the “+ Add to Firefox” button. Additionally, the door hanger should no longer be displayed. 

### Anything else we should know?
[Affected versions]:
• Firefox 71.0a1 (20191007215350)
• Firefox 70.0b13 (20191007220302)
• Firefox 69.0.2 (20191001234643)

[Affected platforms]:
• Windows 10 Pro 64-bit
• MacOS High Sierra 10.13.6

![Firefox prevents FPN installation](https://user-images.githubusercontent.com/50236075/66397269-1d9aa480-e9e4-11e9-93ba-ec6f7baee427.gif)

**Comment by jvillalobos** [comment]
Please file this issue here: https://github.com/mozilla/secure-proxy/issues. This is not an AMO problem.
