### ISSUE TITLE
Improve YaraResult admin filtering

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12564]
https://github.com/mozilla/addons-server/issues/12549 added filtering in `YaraResult` admin. It's binary for now: we allow filtering of results with matched rules and that's it.

The current way of filtering is not great for performance: it's a `WHERE NOT yara_results.matches = '[]'` in SQL. It's a simple condition at least, but the column it's matching against is a `longtext`, and is not indexed, so it's likely to cause issues.

Ideally if we only care about results with matches or not, we should add a simple boolean column, index it and use that for filtering. If we're likely to want more complex filtering however, like what results match which specific set of rules, then we'll need something else...

**Comment by diox** [comment]
Also, for performance: currently, the yara admin list number of database queries scales with the number of results being displayed, and in a bad way: it loads each version when there is one, and from there each add-on, loading the transformers too. We should improve that with some clever use of `prefetch_related()` or similar.

**Comment by diox** [comment]
QA: check that yara admin list (and filtering from https://github.com/mozilla/addons-server/issues/12549) still works. It should be faster especially with lots of results, but I'm not sure you'd see the difference on dev or stage.

**Comment by AlexandraMoga** [comment]
Yara admin filtering is still working as expected

Marking the issue as verified fixed in -dev and stage.
