### ISSUE TITLE
switch out devhub landing page get-involved.png with svg 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12589]
All of the devhub landing page graphics are .svg, apart from the get-involved illustration.  Let's replace it.

https://github.com/mozilla/addons-server/blob/acc31220403a620faed2915f24fd14de0c810f80/static/img/developers/new-landing/get-involved.png is the existing 

![Screenshot 2019-10-11 15 41 00](https://user-images.githubusercontent.com/768592/66661325-b88ebb00-ec3e-11e9-9bd9-3acbce06eba9.png)

**Comment by AlexandraMoga** [comment]
Verified on -dev:

The new image is https://addons-dev-cdn.allizom.org/static/img/developers/new-landing/get-involved.svg
![image](https://user-images.githubusercontent.com/31961530/66745240-23cace00-ee87-11e9-85e2-1fbb80a75605.png)

@eviljeff should we have something inside the `alt` attribute? Right now there's only an empty string:

![image](https://user-images.githubusercontent.com/31961530/66749300-2e3e9500-ee92-11e9-8059-15226f7ccb75.png)

**Comment by eviljeff** [comment]
> should we have something inside the alt attribute? Right now there's only an empty string

No, there's no text explanation for it - it's just page decoration.

**Comment by AlexandraMoga** [comment]
@eviljeff one more thing: I think the decoration should be on the left hand side in RTL.

![image](https://user-images.githubusercontent.com/31961530/66752310-ca1fcf00-ee99-11e9-871b-01397f8ad4ba.png)
