### ISSUE TITLE
Set `has_matches` on existing yara results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12585]
In #12564, we improved the performances of the Yara admin. We added a new field but we did not updated the existing results (in the DB). The problem is that the admin does not list all the results with matches because of that. We should set a value to all the existing yara results.

**For QA:** the Yara admin should list the results with matches by default.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
When accessing https://addons-internal.dev.mozaws.net/en-US/admin/models/yara/yararesult/, you'll see the results with matched rules by default.
