### ISSUE TITLE
Logged-in devhub content order needs switching for rtl

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#12583]
STR:

* Go to https://addons-dev.allizom.org/ar/developers/
* Log-in.

"build best-in-class extensions and themes" should be on the right hand side for RTL.

<img width="995" alt="مركز_المطورين____إضافات_فَيَرفُكس" src="https://user-images.githubusercontent.com/1514/66570606-d2100400-eb65-11e9-8597-a7677e5dda18.png">

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/66752747-de180080-ee9a-11e9-9bad-8f79ce2e78fd.png)
