### ISSUE TITLE
[DevHub] Submit a New Add-on and Theme buttons are not visible on mobile logged in view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12594]
### Describe the problem and steps to reproduce it:
1. Log in to the Developer Hub with a user that has some add-on submitted
2. Resize your screen to mobile view
3. Look for the 'Submit a New Add-on' and 'Submit a New Theme' buttons

### What happened?
The buttons are not visible

### What did you expect to happen?
The buttons should be visible

### Anything else we should know?
- the likelihood for users to submit add-ons from a mobile device is small, but we should aim for the same content on desktop and mobile
- furthermore, if a user without submitted add-ons is viewing the page, the buttons are present 

[logged in view - user with addons - buttons not visible]
![image](https://user-images.githubusercontent.com/31961530/66655654-1c1be700-ec45-11e9-84ba-ed6f7ecdbb27.png)

[logged in view - user without addons - buttons are visible]
![image](https://user-images.githubusercontent.com/31961530/66655701-30f87a80-ec45-11e9-9699-73aa5d4fa7bf.png)

**Comment by eviljeff** [comment]
That's what the mocks showed:
![0 0-developer-hub-single](https://user-images.githubusercontent.com/768592/66662915-9e0a1100-ec41-11e9-87c5-a63d46ba81f0.png)
(ignore the green box)
![0 0-developer-hub-single---mobile](https://user-images.githubusercontent.com/768592/66662919-9fd3d480-ec41-11e9-9417-96e9f0a275eb.png)

**Comment by mastizada** [comment]
@eviljeff Hi, does mocks need an update or can it be added directly? I would like to work on it.

**Comment by eviljeff** [comment]
The page has been implemented as per the mocks so until someone in Product or UX confirms the mocks are incorrect and produces a corrected mock there's nothing to be worked on.  @mastizada issues that haven't been assigned a priority are generally not ready to be worked on.

**Comment by eviljeff** [comment]
mentor @kumar303

**Comment by kunalmohan** [comment]
Hi! I would like to take this up as my first issue.
What is the exact process? Should I get it assigned first or just start working on it?

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Win10 and Android 10:

![image](https://user-images.githubusercontent.com/31961530/71899953-7f92b380-3165-11ea-9996-795ca9c466aa.png)
![image](https://user-images.githubusercontent.com/31961530/71899985-8d483900-3165-11ea-9a0f-6f4395a41484.png)
![image](https://user-images.githubusercontent.com/31961530/71900006-933e1a00-3165-11ea-87e1-3ca593130477.png)
