### ISSUE TITLE
Document `filename` limitations in the comment APIs

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12608]
STR:
1. I used Postman to send a reviewer comment on a specific line for a specific file using the [documentation provided](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#canned-responses). 
2. The Request JSON Object for a file which is inside a folder or even a sub-folder needs to contain the entire path for the file, else the POST or PATCH operations will be created but not available on the client side (code manager in out case) for that specified file.
POST 
https://addons-dev.allizom.org/api/v4/reviewers/addon/492486/versions/1529211/draft_comments/

Request JSON Object:
`{   "comment":"text now",
	"filename": "_locales/ar/messages.json",
	"lineno":5
}
 
Actual result:
The documentation does not provide this information.

Expected result:
Add for the POST and PATCH operations
filename (string) – The filename  this comment is related to (optional). - (with it's path in case the file is inside a folder)

**Comment by kumar303** [comment]
Documentation on this would definitely help but it would be even better to raise an error for invalid paths, tracked in https://github.com/mozilla/addons-server/issues/11813

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Docs have been updated. Thanks for that 👍
