### ISSUE TITLE
Delete `scanners_results`/`yara_results` entries not bound to a version after some time

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12601]
We should delete the scanner and yara results not bound to a version (when no version has been created, likely because the submission process has been aborted) after some time. We can probably do that in the "gc" CRON.

**For QA:** this will likely shorten the list of "all scanner results" but it should only delete entries with no file upload and no version attached to them.

**Comment by diox** [comment]
Maybe just delete all `YaraResult` with `upload` and `version` set to `None` - the `gc` cron already deletes `FileUpload` older than 7 days, so if both fields are set to `None` you're dealing with an aborted submission that has already been considered obsolete since its `FileUpload` has been deleted.

**Comment by AlexandraMoga** [comment]
I've looked inside scanner results and indeed the number of entries with no version attached, which are older than 7 days, have been removed.

@willdurand it looks like the [first scanner object](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/1/change/?_changelist_filters=has_matches%3Dall%26p%3D32) hasn't been removed, although there doesn't appear to be any upload or version attached to it.
Also, while verifying this issue, I figured it could be helpful to have a Creation Date column for scanner results. What do you think?

**Comment by willdurand** [comment]
> @willdurand it looks like the [first scanner object](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/1/change/?_changelist_filters=has_matches%3Dall%26p%3D32) hasn't been removed, although there doesn't appear to be any upload or version attached to it.

@AlexandraMoga yeah, I've seen this one too. It is because the add-on is marked as deleted. It will be fixed by https://github.com/mozilla/addons-server/issues/12735.

> Also, while verifying this issue, I figured it could be helpful to have a Creation Date column for scanner results. What do you think?

I don't know, maybe?

**Comment by AlexandraMoga** [comment]
> I don't know, maybe?

Well, for me it would have been helpful in this context. There might be other scenarios in which this Creation date could prove useful. 
We could also leave it for the admins to decide if they require this column or not.

**Comment by willdurand** [comment]
> Well, for me it would have been helpful in this context. There might be other scenarios in which this Creation date could prove useful.
> We could also leave it for the admins to decide if they require this column or not.

It is fine to add it I think. Could you please file an issue for it?
