### ISSUE TITLE
create new fxa clients for addons-dev

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12609]
For #10487 we change the redirect urls so we need new fxa clients with the new redirect urls defined.  (Or the existing ones updated, but as they're tied to the user who created them, more difficult).

For the fxa server that we use for addons-dev we can create them ourselves.  To do this:
- Login in to https://oauth-stable.dev.lcip.org/console/login
- Press the button to "Create a new OAuth client" (https://oauth-stable.dev.lcip.org/console/client/register)
- select "Trusted Mozilla Client"
- client name is only for you, but best to name it something descriptive.
- redirect URI is what we want to set.  See the list below.  For example, for the `default` config on addons-dev.allizom.org, we want to set `https://addons-dev.allizom.org/api/auth/authenticate-callback/`  (`DOMAIN` is the `DOMAIN` setting value in the instance)
- Press Create.
- The two things needed to be stored in the env variables are the client ID and the client secret (the client secret is _only_ shown once, on this screen).  For example, for the `default` config, the `FXA_CLIENT_ID` env would be filled with the client ID, and `FXA_CLIENT_SECRET` would contain the secret.
- repeat for the `local` config with the localhost redirect url below, storing in the `DEVELOPMENT...` env variables.  Note the `?config` param - we need it all.
- then repeat for the env files for the admin instance where the redirect uri would be `https://addons-internal.dev.mozaws.net/api/auth/authenticate-callback/` for `default`.  We possibly _could_ re-use the `local` config for both addons-dev and the admin instance, or create a new one (I'm not sure if there's any security risk with reusing tbh). 

```
    'default': {
        'client_id': env('FXA_CLIENT_ID'),
        'client_secret': env('FXA_CLIENT_SECRET'),
        # fxa redirects to https://%s/api/auth/authenticate-callback/ % DOMAIN
    },
    'local': {
        'client_id': env('DEVELOPMENT_FXA_CLIENT_ID'),
        'client_secret': env('DEVELOPMENT_FXA_CLIENT_SECRET'),
        # fxa redirects to http://localhost:3000/api/auth/authenticate-callback/?config=local
    },
````

For stage and prod we'll have to ask the FxA ops people to create them as I don't believe we have access to the dashboard for FxA prod.  (Maybe they'd give you the access as fellow ops?)

**Comment by bqbn** [comment]
I've created new oauth clients for `default` and `local` for both non-olympia_internal and olympia_internal instances, and have pushed out the new configs to -dev environment.

However, I do have one question, is it true that the `local` config (a.k.a the `DEVELOPMENT_...` env variables) is only needed for -dev environment?

And,

> We possibly could re-use the local config for both addons-dev and the admin instance, or create a new one (I'm not sure if there's any security risk with reusing tbh).

Looking at our current configuration, I think that's what we're doing nowadays, i.e. the olympia_web and olympia_internal instances are configured with the same `local` oauth client.


> For  stage and prod we'll have to ask the FxA ops people to create them as I  don't believe we have access to the dashboard for FxA prod.  

That's correct and here is a ticket that you can clone for this kind of request: https://bugzilla.mozilla.org/show_bug.cgi?id=1541346

> (Maybe  they'd give you the access as fellow ops?)

Because it's such a critical service, I think they'd rather have minimum people have access to it.

**Comment by eviljeff** [comment]
> However, I do have one question, is it true that the local config (a.k.a the DEVELOPMENT_... env variables) is only needed for -dev environment?

It's available on local-dev, addons-dev and addons-stage.  It's only used during local frontend development though (afaik).

**Comment by bqbn** [comment]
New clients are created and configured for -dev environment. Closing this issue for now.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I don't think this requires qa because the changes were verified for https://github.com/mozilla/addons-server/issues/10487 on AMO dev.
