### ISSUE TITLE
Add statsd timer to auto_approve

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12615]
A while ago in https://github.com/mozilla/addons-server/issues/5409 we added a `statsd` counter for auto approvals, let's also add a timer to monitor how long it takes to approve a version through `auto_approve`.

Helps #6512

**Comment by AlexandraMoga** [comment]
@diox do you need QA for this?

**Comment by diox** [comment]
No, we'll test that ourselves in grafana.
