### ISSUE TITLE
Adding a new file to a version

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1262]
1. Added a version, something went wrong, ended up with a version with no files.
2. Went to add in a new platform file.
3. Got an error "This field is required."

Not sure what field is required or what to do next.

![screenshot 2016-01-07 14 56 07](https://cloud.githubusercontent.com/assets/74699/12186857/64271a62-b55b-11e5-8b20-76324cdb6df6.png)

**Comment by wagnerand** [comment]
Just wait. The file will turn up in the developer hub after some waiting time.

**Comment by nikolas** [comment]
I also ran into this bug.

![2016-01-12-135207_521x369_scrot](https://cloud.githubusercontent.com/assets/59292/12273422/c1341ce2-b933-11e5-8042-585cb35a9cff.png)

**Comment by andymckay** [comment]
We think this got fixed in the AMO stability update.
