### ISSUE TITLE
Make unbanning possible

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12625]
Banning someone though the admin currently executes `ban_and_disable_related_content()`, which does the following:
- Deletes all their collections (can't be undone)
- Force-disables all add-ons they are the sole author of (can be undone, although it's difficult to separate what had already been force-disabled before banning)
- Removes them from all add-ons they are not the sole author of without touching the add-on (which can't be undone without digging through activity logs, and even then I'm not sure you can get the role back)
- Deletes all their ratings (can be undone, although it's difficult to separate what had already been deleted before banning)
- Deletes their picture (can't be undone)
- Deletes the user, which blanks a few fields - `biography`, `homepage`, `location` - and anonymizes their username (can't be undone)
- Sets a banned date on the account

Because many of these operations can't be undone, unbanning someone is technically possible, but doesn't restore the account back to their original state. We should fix this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-20)

**Comment by wagnerand** [comment]
Yes, separating the two is a good approach. Most important for admins is usually preventing future logins (and thus add-on submissions etc).

We can also evaluate what information we really need to clear. For example, if we disable all add-ons for a developer, their developer page should become unavailable (if it doesn't, we could start doing that), so we could still keep information like bio etc. The developer profile page for a user with unlisted add-ons only should probably also be unavailable (if it isn't already).

Generally, we could see what information we expose where and under what conditions and consider changing some of those, before we actually hard-delete information or change them in a way that isn't easily revertible.

**Comment by ioanarusiczki** [comment]
@diox 

I unbanned user rusiczki.ioana+35@gmail.com on -dev

I checked what's been described [above](https://github.com/mozilla/addons-server/issues/12625#issue-507771601) and I see the content back as it was so it looks good.

- the profile picture is not restored as you mentioned
- setting a ban date - did not notice it anywhere

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-20
