### ISSUE TITLE
Update cffi 1.13.0 hashes

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12627]
#12610 updated cffi to 1.13.0 but removed most of the hashes. Locally, this causes this error when trying to build the docker image:
```
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    cffi==1.13.0 from https://files.pythonhosted.org/packages/6c/e6/2ca409305c8fb797a8ac65c8f5d4955ddea892bdf49e5319755207de1120/cffi-1.13.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=853376efeeb8a4ae49a737d5d30f5db8cdf01d9319695719c4af126488df5a6a (from -r requirements/system.txt (line 17)):
        Expected sha256 8fe230f612c18af1df6f348d02d682fe2c28ca0a6c3856c99599cdacae7cf226
             Got        853376efeeb8a4ae49a737d5d30f5db8cdf01d9319695719c4af126488df5a6a
```

**Comment by EnTeQuAk** [comment]
Interesting, I wonder why this hasn't been updated properly. That's one of the cases where a circleci build would have caught it - I wonder if we're able to - instead of ui-tests - have a circleci task that builds the changes from the current PR and adds that as a test to the PR?

**Comment by diox** [comment]
Maybe, yes. I only had the issue locally though, it seems addons-server was successfully built and deployed to dev after the cffi upgrade, so maybe the hash that was there was enough for building the deploy image? Not sure why...
