### ISSUE TITLE
Use 960px wide grid consistently on devhub landing page.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#12621]
For consistency with the rest of the django site, the devhub landing page should have all content line-up with the 960px grid. 

3 column layouts should be consistent as a result.

<img width="1210" alt="misaligned" src="https://user-images.githubusercontent.com/1514/66903605-b2139100-effa-11e9-8cb8-7a7fe97313d4.png">

**Comment by muffinresearch** [comment]
Here's a rough overview of close to what this will look like after the change for the logged-in page:

![Screen Shot 2019-10-16 at 10 21 22-fullpage](https://user-images.githubusercontent.com/1514/66906024-d5403f80-effe-11e9-9bb8-85d00b53267a.png)

Note: the SVG will need to be widened in the "Build best in class..." section.

**Comment by muffinresearch** [comment]
And rough cut of what the logged-out page will look like:

![Screen Shot 2019-10-16 at 10 44 33-fullpage](https://user-images.githubusercontent.com/1514/66907915-15ed8800-f002-11e9-8577-befbfc3a9df1.png)

All the above assumes edge of content are at 960px.

**Comment by eviljeff** [comment]
> Notes: the SVG will need to be widened in the "Build best in class..." section 

I'm not sure about changing this callout box - without the 80px gap it doesn't look good at 960px.  Actually, none of the sections look particularly good with only 20px at 960px.  At 960px it looks better to change the footer padding to 80px than to change the rest of the sections to 20px.

**Comment by muffinresearch** [comment]
> > Notes: the SVG will need to be widened in the "Build best in class..." section
> 
> I'm not sure about changing this callout box - without the 80px gap it doesn't look good at 960px. Actually, none of the sections look particularly good with only 20px at 960px. At 960px it looks better to change the footer padding to 80px than to change the rest of the sections to 20px.

What's the 80px gap you refer to? Can you provide a screenshot to illustrate what you mean?

**Comment by eviljeff** [comment]
> What's the 80px gap you refer to? Can you provide a screenshot to illustrate what you mean?

the screenshots I posted in #12623 are all with an 80px gap from edge to content (at 960px).  But if that's what frontend does I suppose in cause of consistency I'll reduce to 24px (frontend uses 24px).

**Comment by willdurand** [comment]
> frontend uses 24px

@eviljeff frontend uses 10px for screen width < 720px, then 24px

**Comment by eviljeff** [comment]
Devhub used 20px for <960 (or 700?  can't remember) and 80px otherwise so I figured it may as well be 24px on all sizes.

**Comment by AlexandraMoga** [comment]
@eviljeff I have  a mismatch between -dev and stage for the grey footer in the Contribute section:

[dev] 
![image](https://user-images.githubusercontent.com/31961530/67008705-c044d880-f0f2-11e9-92ab-78a90a7885fc.png)
[stage]
![image](https://user-images.githubusercontent.com/31961530/67008712-c63ab980-f0f2-11e9-9499-c8dbcb462034.png)

I've tried both on Windows on a FHD resolution and on a mac with a 2304x1440 resolution

**Comment by eviljeff** [comment]
@AlexandraMoga looks like something went wrong when I cherry-picked the commits for the new header for stage and we lost some changes.  We decided it's not worth a new deploy.  It will fix itself the next time master is tagged and deployed to stage (and then prod)

**Comment by AlexandraMoga** [comment]
Stage has been updated and the page has the correct layout now.
