### ISSUE TITLE
[DevHub] The svg decoration from the Get involved card should be on the left side in RTL

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12626]
### Describe the problem and steps to reproduce it:
1. Open https://addons-dev.allizom.org/en-US/developers/ in logged out view
2. Switch to a RTL locale, i.e. `/ar/`
3. Notice the position of the `.svg` decoration

### What happened?
The decoration remains on the right 

### What did you expect to happen?
The decoration moves tot the left

[1] LTR
![image](https://user-images.githubusercontent.com/31961530/66917687-8a3a2280-f026-11e9-9bd4-87f27cb5a9d8.png)

[2] RTL
![image](https://user-images.githubusercontent.com/31961530/66917620-624abf00-f026-11e9-9be8-dd678c7a1120.png)

**Comment by muffinresearch** [comment]
You can use `html[dir='rtl'] ...` as the start of a selector for this.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

Mentor: @bobsilverberg

**Comment by Sirius207** [comment]
Hi ~ I can fix it and I've complete the step 1 & 2 on [Add-ons/Contribute/Code](https://wiki.mozilla.org/Add-ons/Contribute/Code).

It looks like I can find a place to put these CSS
```css
html[dir=rtl] .DevHub-callout-box {
    text-align: left;
}
```

and the block looks fine. :-)

![image](https://user-images.githubusercontent.com/7900936/67916233-065c6a80-fbd0-11e9-9594-cdfb70b92d0e.png)

**Comment by kunalmohan** [comment]
Hi! Is this issue still open? If yes, I would like to work on it.

**Comment by AlexandraMoga** [comment]
verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/68470307-7304e400-0224-11ea-8280-ffbe4fe78d8d.png)
