### ISSUE TITLE
Disallow comments submitted for a line number and a null file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#12635]
### Describe the problem and steps to reproduce it:

Post a comment with `filename: null` and `line: 123`. Example:

```
curl 'http://localhost:3000/api/v5/reviewers/addon/616959/versions/1688394/draft_comments/?lang=en-US'  \
  -H 'Authorization: Bearer eyJh...' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: sessionid=...' \
  --data '{"comment": "A comment", "filename": null, "lineno": 123}'
```

### What happened?

The comment was created.

### What did you expect to happen?

The request should be rejected with a 400 because commenting on a line number without specifying the file doesn't make sense.

### Anything else we should know?

Because the frontend pre-loads all comments for the version, it's causing this error: https://github.com/mozilla/addons-code-manager/issues/1126

**Comment by ioanarusiczki** [comment]
@kumar303 
I verified with Postman through the API for 
https://code.addons-dev.allizom.org/en-US/browse/491860/versions/1528357/
If my JSON Request is as the following:
"comment":"a text"
"filename":null
"lineno":1
I receive a 400 error message and the comment is not created.

![filename null](https://user-images.githubusercontent.com/33448286/69427631-69a56c80-0d38-11ea-9b0c-bea4c642dbfc.png)

If I try to make comments without specifying a line but with "filename":null they will be created and this is how they look in code manager:

![overall comments](https://user-images.githubusercontent.com/33448286/69427988-e59fb480-0d38-11ea-8fd0-de5c324c236f.png)

Let me know if this is as expected. Perhaps the UI in code manage should allow `overall` comments ?

**Comment by kumar303** [comment]
> Let me know if this is as expected. Perhaps the UI in code manage should allow `overall` comments ?

Yes, this is expected. The ability to add overall comments will be forthcoming in https://github.com/mozilla/addons-code-manager/issues/993
