### ISSUE TITLE
Merge `YaraResult` with `ScannersResult`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12631]
It becomes clear that both are in fact the same models (especially with customs being a new private linter), so let's merge both!

**Comment by willdurand** [comment]
@diox I think we'll have to delete the table eventually, how should we proceed to copy the existing rows from `yara_results` to `scanners_results` in the DB?

**Comment by diox** [comment]
Through a [data migration](https://docs.djangoproject.com/en/2.2/topics/migrations/#data-migrations) (that would be added before the migration that deletes the table in the db, which we don't want to do yet anyway for backwards-compatibility). When doing this, you can write python that uses old models that no longer exist.

**Comment by willdurand** [comment]
So my plan is to update `ScannerResult` to store Yara results and use that everywhere. Then, I'll add a data migration to copy the entries from `yara_results` to `scanners_results`. After that, I'll remove both the Yara admin and model.

**Comment by AlexandraMoga** [comment]
same as for #12633 
I've submitted several add-ons, using dev hub and the signing api and yara results (with match and unmatched rules) have been created in Scanners admin.  `wat` and `customs` entries were created as well.

I'm marking the issue as verified fixed

**Comment by AlexandraMoga** [comment]
same as for #12633 
I've submitted several add-ons, using dev hub and the signing api and yara results (with match and unmatched rules) have been created in Scanners admin.  `wat` and `customs` entries were created as well.

I'm marking the issue as verified fixed
