### ISSUE TITLE
Move `run_yara` task to the scanners package

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12633]
We can move the `run_yara` task to the `scanners` package as we'd like to remove the `yara` package eventually. This is because it is now clear that yara is in fact a scanner, very similar to the other ones.

**Comment by AlexandraMoga** [comment]
I've submitted several add-ons, using dev hub and the signing api and `yara` results (with match and unmatched rules) have been created in Scanners admin. , `wat` and `customs` entries were created as well. 

@willdurand  I've also run into a new issue while using the API to submit 20 consecutive large add-ons (~20 MB each): for one instance, I received a 502 from the server. In the previous weeks, I used to submit 100 consecutive large add-ons and never received a 502. However, the add-on version was created, despite the error. I'm going to try with stage tomorrow to see if I can trigger the error there.

**Comment by willdurand** [comment]
> @willdurand I've also run into a new issue while using the API to submit 20 consecutive large add-ons (~20 MB each): for one instance, I received a 502 from the server. In the previous weeks, I used to submit 100 consecutive large add-ons and never received a 502. However, the add-on version was created, despite the error. I'm going to try with stage tomorrow to see if I can trigger the error there.

Let me know if this is still an issue. I am not sure why it would be different now..

**Comment by AlexandraMoga** [comment]
@willdurand I've run a few load tests both on -dev and stage but I couldn't reproduce the error anymore.
There might have been an external factor that caused the error to appear. In any case, I will be repeating these tests in the coming days and will let you know if something changes.
