### ISSUE TITLE
Migrate `YaraResult` entries to new `ScannerResult` entries

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12648]
This issue depends on https://github.com/mozilla/addons-server/issues/12631.

**For QA:** all the existing Yara results will be available in the scanner django admin.

**Comment by AlexandraMoga** [comment]
The pre-existing yara results can be found in the Scanner module - both with matched and unmatched rules.
I don't know exactly how many entries we had on -dev before the migration, but I can make a note of  all yara entries from stage to double check if the numbers are correctly imported.

**Comment by AlexandraMoga** [comment]
I've verified with stage that all the pre-existing yara entries have been migrated to Scanner results.
