### ISSUE TITLE
Visit the Extension Workshop link won't work

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12644]
STR:
1. Log in Developer Hub https://addons.allizom.org/en-US/developers/ and try to click on "Visit the Extension Workshop" blue link

Expected result: 
EW homepage is loaded.

Actual result:
Nothing happened. 

Notes:
Reproducible on AMO dev and AMO stage - FF69(Win10). 

![nolink](https://user-images.githubusercontent.com/33448286/67013072-2f262f80-f0fb-11e9-8a56-58870fd96ec0.gif)

**Comment by eviljeff** [comment]
okay, this is me forgetting about the impact of `z-index` (the background image is affectively "above" the content).

**Comment by vcarciu** [comment]
Verified as fixed.
