### ISSUE TITLE
Remove Yara admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12654]
This issue depends on https://github.com/mozilla/addons-server/issues/12648.

**For QA:** all existing yara results should have been moved to the scanner results in #12648. For this issue, the "yara django admin" should be gone.

**Comment by AlexandraMoga** [comment]
"Yara" admin module is no longer present on -dev:

![image](https://user-images.githubusercontent.com/31961530/67264621-4dea4480-f4b4-11e9-9e14-5f2308fb07c0.png)
