### ISSUE TITLE
Implement "Delay auto-approval by x" action

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12671]
See also  #12670 which implements another base action that we'll probably want to do first.

"Delay auto-approval by 24 hours" and "Delay auto-approval indefinitely" are two actions we want to implement in the workflow of the scanners. When triggered, each of these actions should:
- Prevent future auto-approval of the add-on (including the version that triggered that action)
- Flag the entire add-on for human review in a separate queue (maybe re-using https://github.com/mozilla/addons-server/issues/12670)

As #12670 reviewers can revert this, but for now that shouldn't prevent scanners from reflagging the add-on for the same reason after a new upload.

Implementation notes:
- Add new `DateTimeField` in `AddonReviewerFlags` called `auto_approval_disabled_until`.
- Scanner action would set a datetime in the future accordingly. "Indefinitely" is implemented using the same field with a date in the far future, separate from the existing `auto_approval_disabled` which is set by reviewers.

If not re-using the flag from #12670 we'll need a separate queue to view flagged add-ons in reviewer tools. If re-using it, we could display the date where auto-approvals would resume for this add-on in that queue.

Everything should apply to both listed & unlisted, but https://github.com/mozilla/addons-server/issues/12622 is a blocker for unlisted so we may start with listed only.

Depends on #12640

**Comment by diox** [comment]
QA: You can use the instructions from https://github.com/mozilla/addons-server/issues/12749#issuecomment-551543990 to have this action be executed on submission for testing. A couple notes:
- The action only applies to listed submissions for now. https://github.com/mozilla/addons-server/issues/12622 will apply it for listed in the future
- Currently delaying auto-approval does not flag the version for human review. That will be covered by https://github.com/mozilla/addons-server/issues/12833 (not sure if we really want to do this yet)
- Add-ons that have delayed auto-approval because of scanners should show up in the extensions queue just like add-ons that have auto-approval manually disabled by admins.

**Comment by vcarciu** [comment]
Verified as fixed . The addons highlighted in yellow disappeared after 24h and the ones in red are still displayed in the list as expected  : 
![image_2019_11_12T07_45_30_275Z](https://user-images.githubusercontent.com/1583842/68768784-d9767180-062b-11ea-9c34-55896e7433bf.png)

**Comment by vcarciu** [comment]
@diox : 
I forgot to mention here that lang packs are not affected by the delay(thay are normally auto approved). Please let me know if this is intended.

**Comment by diox** [comment]
Yes, langpacks can only be submitted with proper permission now and as such should be unaffected.

**Comment by vcarciu** [comment]
Thank you
