### ISSUE TITLE
Add a Django admin for the scanner rules

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12674]
We introduced a new model named `ScannerRule` in #12656. Let's create a django admin for it so that admins can bind rules to actions.

**Comment by AlexandraMoga** [comment]
@willdurand should the entries added in Scanner rules have any effect at this point, or should we only test that the module is working as expected, i.e adding/editing/deleting rules?

**Comment by willdurand** [comment]
> @willdurand should the entries added in Scanner rules have any effect at this point, or should we only test that the module is working as expected, i.e adding/editing/deleting rules?

There is no effect at this point. You can add/edit/delete rules, but it won't be used for anything else.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
For the actions that are currently available, the scanner rules module is working as expected.
