### ISSUE TITLE
Add a `run_action` task

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12676]
We need a `run_action` Celery task in the `scanners` app so that we can trigger an action bound to a matched rule.

**Comment by willdurand** [comment]
From @diox:

> For when we start using ScannerRule to fetch/apply all rules when scanning: I was thinking matches should be a ManyToMany relationship between a ScannerResult and all the ScannerRule it matched. And the ManyToMany intermediate model would hold the meta information as well.

I like the idea but we might need to introduce a `rules` M2M field instead, no? Matched rules does not necessarily mean we have a corresponding rule in the database (and `matches` currently stores this piece of information)

**Comment by diox** [comment]
Shouldn't all rules be in the database eventually ? (I'm not sure actually...)

I like that it forces us to have the database constraints - removing a rule would mean removing the match, but isn't that what we'd want ? Admins should think twice about removing a rule and not just marking it as inactive (that does mean we'd have to make sure `has_matches` is updated but we should be able to do that through django signals).

**Comment by willdurand** [comment]
That would means admins must register the rule before we (developers) can add a new one in... customs or yara?

**Comment by diox** [comment]
Not necessarily : if means they must register the rule when they want that rule to match something. We add the rule first, and then they add it to the database (that part could maybe be automated, or removed completely for yara when the yara rules are entirely stored in database) with the desired action. Until they do it cannot match anything, but that's fine, I think.

**Comment by willdurand** [comment]
I see what you mean. The one thing that I dislike is that with Yara, we're losing the "raw yara" results (because we store a JSON array for customs and a JSON object for yara, in two different fields).

**Comment by diox** [comment]
We could still capture that separately - `results` is the "raw" result, `matches` is the m2m.

**Comment by willdurand** [comment]
If a rule matches but there is no registered rule in the DB, what should we do then? How do we know that it has happened? I kinda liked that we had a set of matched rules reported by a scanner and a list of actions bound to some of them.

**Comment by willdurand** [comment]
> We could still capture that separately - `results` is the "raw" result, `matches` is the m2m.

I am thinking about doing this anyway because it is confusing right now.

**Comment by diox** [comment]
> How do we know that it has happened? I kinda liked that we had a set of matched rules reported by a scanner and a list of actions bound to some of them.

Maybe warn somewhere... You're right that we be notified somehow that it's happening. What I don't like is relying on the raw matches to then match rules by names in the db after the match has been detected once - that's what a m2m solves. With the raw `results`, we could compare it to the m2m and warn - maybe through logging and maybe in the django admin for the scanner result as well - that it matched a rule not in database...

**Comment by willdurand** [comment]
> Maybe warn somewhere... You're right that we be notified somehow that it's happening. What I don't like is relying on the raw matches to then match rules by names in the db after the match has been detected once - that's what a m2m solves. With the raw `results`, we could compare it to the m2m and warn - maybe through logging and maybe in the django admin for the scanner result as well - that it matched a rule not in database...

I changed my WIP to add a M2M field (`rules`) between `ScannerRule` and `ScannerResult` and I updated the `save()` method of the `ScannerResult` to automatically create relationships. So both are possible.

But I think it'd make more sense to only have `results` to store the raw results.

As for `has_matches`, we might want to keep it tied to `results` and not to the M2M field but I am not sure.

**Comment by willdurand** [comment]
Marking as "qa: not needed" for now because the task is not used.
