### ISSUE TITLE
Add warning to API keys page that credentials are not to be shared

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1268]
I just got an email from a developer about an unrelated issue where they just included a full screenshot of their API keys.

We might want to add a scary warning that those credentials are not to be shared with anyone.

**Comment by EnTeQuAk** [comment]
Any suggestions for the wording on this? Maybe something like "Keep your API keys stored in a secure place and never share them with a third party." - might need somewhat better English though.

**Comment by tofumatt** [comment]
Storage of API keys shouldn't be the first callout as that matters less (I mean, don't share them, yes, but they can just regen them if they forget, so no worries there).

I'd say:

"Keep your API keys secret and **never share them with anyone**, including Mozilla contributors."

Last bit about "including Mozilla contributors" optional, but just handy to prevent social engineering ("Hi I'm a Mozilla contributor I can help send me your API keys").
