### ISSUE TITLE
Remove `matches` field (use `results` instead) in `ScannerResult`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12682]
This is needed for https://github.com/mozilla/addons-server/issues/12676.

**For QA:** it should be transparent for admins but we can notice a different in a "detail" view of a scanner result: there should be only one "Results" field (instead of "Results" and "Matches") and for Yara results, "Results" should not be empty (if "Matches" was previously not empty).

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

A scanner item will display only a "Results" section now.
All the matched rules for pre-existing yara entries  - previously available in the 'Matched' section -  have been transferred to the 'Results" section:

![image](https://user-images.githubusercontent.com/31961530/67400384-3f845180-f5b6-11e9-9bc7-566ba0887196.png)
