### ISSUE TITLE
Add `matched_rules` to `ScannerResult`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12693]
In order to work on #12688, we need to associate `ScannerRule` and `ScannerResult` entries when we can. This issue is about doing this.

**Comment by diox** [comment]
That seems reasonable - the `ScannerRule` model is going to be in prod this week so we could prepare everything on all environments before the migration gets deployed. (I like storing the number of matches rather than a boolean, too).

**Comment by willdurand** [comment]
I kept `has_matches` as a boolean field for now and updated the patch to compute its value on `save()`.

**Comment by willdurand** [comment]
See also https://github.com/mozilla/addons-server/pull/12714

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage. 
The matched rule identified for a scanner result is linking to the actual scanner rule details.
