### ISSUE TITLE
addons.mozilla.org has failed the web security baseline

### ISSUE THREAD

**Issue by mozcloudsec** [mozilla/addons-server#12699]
Site https://addons.mozilla.org has failed the web security baseline scan.

The failing tests are:

 Absence of Anti-CSRF Tokens [10202] x 1 
 * https://addons.allizom.org/en-US/developers/ (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=addons.mozilla.org) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by psiinon** [comment]
So hopefully this will be closed by the baseline scan after it runs with #12698 applied.

**Comment by psiinon** [comment]
Except that the issue was moved from another repo, which will probably mess this up :(
@willdurand @eviljeff should future issues on AMO be raised on this repo?

**Comment by eviljeff** [comment]
@psiinon no, only issues that are related to /developers/ - I assume most of the tests are on frontend urls

**Comment by eviljeff** [comment]
I guess you could file issues on mozilla/addons/issues instead.  Though tbh that repo gets less regular attention if something needs an urgent-ish response.

**Comment by eviljeff** [comment]
@psiinon this doesn't seem to have been auto-closed so I'm closing it.  Re-open if you think the tool will eventually do its thing.

**Comment by psiinon** [comment]
Interesting, according to https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=addons.mozilla.org the baseline is still failing, but for a different reason.
I would have expected this issue to have been reopened automatically :/

**Comment by psiinon** [comment]
Doh, thats because I changed to configs, so the bug the baseline is now managing is https://github.com/mozilla/addons-frontend/issues/8793
This can stay closed :)
