### ISSUE TITLE
Failed when working locally (make initialize)

### ISSUE THREAD

**Issue by junngo** [mozilla/addons-server#12704]
### Describe the problem and steps to reproduce it:
I'm working build locally. I try to command `make initialize`.
And I have met error that is `Permission denied`.

### What happened?
The error is as follows:
![error1_101023](https://user-images.githubusercontent.com/29684524/67389791-4de26580-f5d6-11e9-9ed1-d0f61e51d8e8.png)
```
python3 -m pip install -e .
Obtaining file:///code
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/code/setup.py'"'"'; __file__='"'"'/code/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /code/
    Complete output (2 lines):
    running egg_info
    error: [Errno 13] Permission denied
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Makefile-docker:113: recipe for target 'install_python_dev_dependencies' failed
make: *** [install_python_dev_dependencies] Error 1
Makefile-os:28: recipe for target 'initialize' failed
make: *** [initialize] Error 2
```

### What did you expect to happen?
It should work successfully.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
I am not sure whether it is related to this issue(#12579 ).
I wonder if I'm the only one who can't work.
Please take a look at the issue.

**Comment by EnTeQuAk** [comment]
It probably is related to #12579 but as we didn't notice any issues during our testing I'd be interested in your setup.

* Did you `docker-compose pull` the latest images before running `make initialize`?
* What operating system are you running?
* Generally, `docker-compose up -d` is working for you? (Check via `docker-compose ps` and ideally post the result)
* From inside your git checkout, can you post the results of both
  * `$ stat -c '%u' .`
  * `docker-compose exec web stat -c '%u' /code`

Thanks!

**Comment by junngo** [comment]
Thank you for your answer.
I got the latest version from master branch. And I had command `docker-compose pull`.
After `docker-compose up -d` command ran, I checked running containers using command (`docker-compose ps`). I made sure that everything(docker containers) was working.
After all checks have been completed, I was running `make initialize`.

The results of the confirmation are as follows.
`$ stat -c '%u' ` : 1000
`$ docker-compose exec web stat -c '%u' /code` : 1000
![check_1022](https://user-images.githubusercontent.com/29684524/67393074-a0268500-f5dc-11e9-9335-0f9f21ea3b6b.png)

Thanks.

**Comment by junngo** [comment]
I solved the problem.
The above error lacked the authority of the 'olympia.egg-info file'.
![egg-info-root](https://user-images.githubusercontent.com/29684524/67786189-cbfcab80-fab1-11e9-909f-e7f616f7994a.png)

So, I authorized 'olympia.egg-info file'(`chown olympia:olympia olympia.egg-info`).
'olympia.egg-info file' passed when performing the build, but other files lacked permission(e.g: css file[0], build.py[1] and so on).

I accessed directly in docker shell and directly executed the command.
(`chown -R olympia:olympia /deps/ /code/`).

It works successfully afterwards :)
Thanks.


[0]
![Screenshot from 2019-10-28 20-32-40](https://user-images.githubusercontent.com/29684524/67786789-cf446700-fab2-11e9-9b8c-44d6a20f5006.png)

[1]
![Screenshot from 2019-10-28 21-27-07](https://user-images.githubusercontent.com/29684524/67786835-e1260a00-fab2-11e9-9026-622a332f41a8.png)

**Comment by EnTeQuAk** [comment]
Ah, interesting. So you had been using (or running `make initialize`) addons-server before and that made permissions go wonky which doesn't play nicely with the new way we handle permissions.

In theory, this shouldn't happen in a completely clean checkout - or did you do that?

**Comment by junngo** [comment]
I solved this issue. I close the issue.
If someone need to open, Open the issue again.

**Comment by dbxnr** [comment]
I experienced this too on a fresh ```make initialize``` , following @junngo the solution was
```

# chown olympia:olympia /code/srcolympia.egg-info
# chown -R olympia:olympia /deps/ /code/
```

```
$ stat -c '%u' .
1000
$ docker-compose exec web stat -c '%u' /code
1000

```
