### ISSUE TITLE
Connect with us section needs some style adjustments 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12702]
Follow up for #12613 

### Describe the problem and steps to reproduce it:
The Connect with us section implemented for https://addons.allizom.org/en-US/developers/ should be adjusted to match the styling proposed in [the mock](https://projects.invisionapp.com/share/N8RQ75IP2V5#/screens/360309850) and the Extension workshop.
There are a few areas that could be improved:
- reduce the margin of the `DevHub-content-header `
- Increase the font-weight of the section headers to (I've tested with 500 and it looked closer to what we have in the mock)
[current style]
![image](https://user-images.githubusercontent.com/31961530/67370585-991f5880-f583-11e9-83f3-769ac0b6bd3a.png)
[adjusted style]
![image](https://user-images.githubusercontent.com/31961530/67370662-bbb17180-f583-11e9-82c0-864bb607ebed.png)

- reduce the distance between the `DevHub-content-header` and the `DevHub-content-copy`

Overview:

[current styling]
![image](https://user-images.githubusercontent.com/31961530/67373475-5ad86800-f588-11e9-8d52-aac2cba125f7.png)

[expected styling]
![image](https://user-images.githubusercontent.com/31961530/67373381-3086aa80-f588-11e9-82ce-47d48d011a33.png)

**Comment by eviljeff** [comment]
note the column widths of the connect with us sections won't match extensionworkshop because the connect with us columns match the footer columns, and I took the decision to go with footer styling from addons-frontend (which is 3 equal width columns) rather than extensionworkshop (where the "mozilla" column is less wide than the other columns)

**Comment by eviljeff** [comment]
we discussed this in our triage and decided it's a wontfix.
