### ISSUE TITLE
Links from the 'Twitter' section in the Connect with us footer should be opened in the same tab

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12701]
Follow up for #12613 

### Describe the problem and steps to reproduce it:
1. Open DevHub homepage - https://addons.allizom.org/en-US/developers/
2. Scroll down to the Connect with us section (blue footer)
3. Click on any link from the 'Twitter' section 

### What happened?
The link is opened in a new tab

### What did you expect to happen?
The link should be opened in the same tab as per https://github.com/mozilla/addons-server/issues/12701#issuecomment-547653754

![2019-10-30_09-48-06](https://user-images.githubusercontent.com/31961530/67838650-6d0f5480-fafa-11e9-82ff-71d491a6e11e.gif)

**Comment by eviljeff** [comment]
It's not just the "More" section - most of the external links on the page and in the header and footer don't open in a new tab.

@jvillalobos should all the links to external websites open in a new tab?  Is extensionworkshop considered an external website?  (Or do you want to go through and note each link if it should be opened externally or not?)

**Comment by jvillalobos** [comment]
The mozilla.org footer and AMO footer open all links on the same tab, so let's keep that behavior.

**Comment by AlexandraMoga** [comment]
What about links that are opened in different tabs - see links from the Twitter section for example? Should they be left as they are, or should they be changed to open in the same tab?

**Comment by jvillalobos** [comment]
Yeah, I think those two Twitter links should open in the same tab, so things are consistent. The Privacy Notice link the newsletter form makes sense as a new tab link because you're looking for context before clicking on the checkbox.

**Comment by AlexandraMoga** [comment]
I've updated the issue to match what needs to be implemented.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @EnTeQuAk

**Comment by muffinresearch** [comment]
When `target="_blank"` is removed please also remove `rel="noopener noreferrer"`.

**Comment by sayantanu-dey** [comment]
Hi,
I want to contribute in it as my first contribution. Do I need to talk to the mentor to get this issue assigned or something else?
Please assign this issue to me.

**Comment by cawfeecake** [comment]
Hello,

Could I get assigned this issue? I have a PR for the fix.

Thank you (sorry if I didn't wait long enough for current assignee to get done)

**Comment by eviljeff** [comment]
@cawfeecake unless @sayantanu-dey confirms he's not working on it any more it's not available.

**Comment by cawfeecake** [comment]
@eviljeff Apologies.

@sayantanu-dey Would you be willing to let me take care of this issue? Thank you in advance, and completely understand if you'd still like to do it.

**Comment by sayantanu-dey** [comment]
I am about to make a PR for this. I am an absolute beginner please let me resolve this issue.
@cawfeecake hope you understand.

**Comment by cawfeecake** [comment]
@sayantanu-dey Sounds good

**Comment by sayantanu-dey** [comment]
@cawfeecake thanks for understanding.

**Comment by sayantanu-dey** [comment]
Hi!
I have submitted the PR.If you are free please review it.

**Comment by eviljeff** [comment]
@muffinresearch should `noreferrer` be dropped too?

**Comment by muffinresearch** [comment]
> @muffinresearch should `noreferrer` be dropped too?

Yep, I've added a review on the PR with that info.

**Comment by AlexandraMoga** [comment]
The links are opened in the same tab now.
