### ISSUE TITLE
"Media enhancers for Firefox" link will return a 404 on production

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#12717]
Steps to reproduce:
1.Go to addons.mozilla.org and click on the link under "Media enhancers for Firefox" on homepage

Expected results:
The link will redirect to an existing collection

Actual results: 
https://addons.mozilla.org/en-US/firefox/firefox/collections/4757633/must-have-media/edit/?page=1&collection_sort=-popularity&src=homepage-secondary-hero is returning a 404.

**Comment by EnTeQuAk** [comment]
This particular instance has been fixed by @jvillalobos and @wagnerand, mind double-checking?

**Comment by vcarciu** [comment]
Verified as fixed in production
