### ISSUE TITLE
View a comparison for a deleted version in the reviewer API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#12726]
### Describe the problem and steps to reproduce it:

As a reviewer, use the review tools to craft a Code Manager comparison link between a non-deleted version and a deleted version. You would have to edit the URL to craft this URL but a UI for this will be forthcoming.

Given this crafted URL: https://code.addons.mozilla.org/en-US/compare/989342/versions/3431730...3432145/

...here is the API request made by Code Manager:

```
https://addons.mozilla.org/api/v5/reviewers/addon/989342/versions/3431730/compare_to/3432145/?lang=en-US
```

### What happened?

The API returns a 404 and Code Manager cannot display anything.

### What did you expect to happen?

The API should not return a 404 so that Code Manager can display the comparison.

### Anything else we should know?

The old File Viewer would display a comparison like this.

See https://github.com/mozilla/addons-code-manager/issues/1159

**Comment by ioanarusiczki** [comment]
@EnTeQuAk 
I tested the API responses with Postman: first I deleted a version from dev hub. The response is created with a 200 status. Also the code manager file viewer will display the compare pages. 

Examples: 
API - version 1.0 has been deleted from dev hub by the developer
https://addons-dev.allizom.org/api/v4/reviewers/addon/618648/versions/1690094/compare_to/1690242/
Code Manager view: 
https://code.addons-dev.allizom.org/en-US/compare/618648/versions/1690094...1690242/

API - version 2.0 has been deleted from dev hub by the developer
https://addons-dev.allizom.org/api/v4/reviewers/addon/618636/versions/1690078/compare_to/1690079/

Code Manager view:
https://code.addons-dev.allizom.org/en-US/compare/618636/versions/1690078...1690079/

I've noticed that:
- The user cannot post comments on deleted versions - https://code.addons-dev.allizom.org/en-US/browse/618648/versions/1690094/
- Also, if the last version (the new one) has been deleted, the user cannot post comments on the compare view either. Example: https://code.addons-dev.allizom.org/en-US/compare/618636/versions/1690078...1690079/
These could be already known issues, so I'll check the repos.

**Comment by bobsilverberg** [comment]
> @EnTeQuAk
> I tested the API responses with Postman after I deleted an add-on version from dev hub. The response is created with a 200 status. Also the code manager file viewer will display the compare pages.
> 

> I've noticed that:
> 
> * The user cannot post comments on deleted versions - [code.addons-dev.allizom.org/en-US/browse/618648/versions/1690094](https://code.addons-dev.allizom.org/en-US/browse/618648/versions/1690094/)
> 
> * Also, if the last version (the new one) has been deleted, the user cannot post comments on the compare view either. Example: [code.addons-dev.allizom.org/en-US/compare/618636/versions/1690078...1690079](https://code.addons-dev.allizom.org/en-US/compare/618636/versions/1690078...1690079/)
> These could be already known issues, so I'll check the repos.

I think that with the current design, where comments are associated with the "new" version for a compare, this makes sense. Would a reviewer ever need to comment on a deleted version? @wagnerand What do you think?

**Comment by wagnerand** [comment]
@bsmedberg Sorry for the delay here, I missed this. I think this behavior is ok for the time being. We might update it later if we identify a need for this.
