### ISSUE TITLE
Support deleted add-ons in scanners admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12735]
[This scanner result entry](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/1/change/) has a version bound to a deleted add-on. We should see the name of the add-on and a link to it in the reviewer tools, but that's not the case.

The problem is that we are using a queryset that excludes deleted add-ons by default.

**For QA:** if a scanner result is linked to a deleted add-on, we should still see its name in the list/detail view and the link should work.

**Comment by AlexandraMoga** [comment]
I've verified both with listed and unlisted entries and the add-on details are now visible in the list and in the detail view for all the three scanners - see [4389](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/4389/change/?_changelist_filters=has_matches%3Dall%26p%3D0), [4390](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/4390/change/?_changelist_filters=has_matches%3Dall%26p%3D0) and [4391](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/4391/change/?_changelist_filters=has_matches%3Dall%26p%3D0) as examples.

@willdurand even though the scanners expose a link to the add-on review page, it looks like Rev Tools don't have the capacity to display a review page for deleted add-ons - hence [this link](https://addons-internal.dev.mozaws.net/en-US/reviewers/review/618278) will 404.
I can file a follow up issue to discuss this further.

**Comment by willdurand** [comment]
> @willdurand even though the scanners expose a link to the add-on review page, it looks like Rev Tools don't have the capacity to display a review page for deleted add-ons - hence [this link](https://addons-internal.dev.mozaws.net/en-US/reviewers/review/618278) will 404.
> I can file a follow up issue to discuss this further.

This link works for me, can it be a permission issue? /cc @wagnerand or @diox

**Comment by wagnerand** [comment]
Yes, it looks like a permission issue because the linked page works for me.

**Comment by AlexandraMoga** [comment]
Seems the problem was on my end and it was related to my firefox profile somehow. Switching to a new profile allowed me to access the review page as well.
