### ISSUE TITLE
Implement "Flag for human review" as a possible scanner action

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12740]
Depends on https://github.com/mozilla/addons-server/issues/12670 and #12640

Once those 2 issues are implemented, add in the available actions one that flags the scanned version for human review.

**Comment by willdurand** [comment]
> and #12640

this one has been fixed

**Comment by diox** [comment]
Marking as qa- as QA can't really test this yet - it needs https://github.com/mozilla/addons-server/issues/12749
