### ISSUE TITLE
Use `Addon.unfiltered` manager in abuse report querysets

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12742]
In #12735, we added support for "deleted add-ons" in the scanners django admin. The optimized queryset was using the default manager (`Addon.objects`), which automatically excluded deleted add-ons, leading to entries without add-on information in the django admin.

We fixed this problem by using the `Addon.unfiltered` manager, which does not exclude the deleted add-ons.

We noticed a similar behavior in the following optimizations:
```
src/olympia/abuse/admin.py:                'addon', queryset=Addon.objects.all().only_translations()),
src/olympia/reviewers/views.py:                    'addon', queryset=Addon.objects.all().only_translations())
src/olympia/reviewers/views.py:        Prefetch('addon', queryset=Addon.objects.all().only_translations()),
```

This issue is about fixing these occurrences.

**Comment by junngo** [comment]
Hello @eviljeff 
Can I ask you about `abuse report`?
I tried to make a `abuse report` on admin[0].
But, I couldn't find to make abused user on admin site.
Should I use rest API[1] to make abused user?

[0]
http://olympia.test/en-US/admin/models/

[1]
https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#post--api-v4-abuse-report-addon-

**Comment by eviljeff** [comment]
Use the API ideally.
