### ISSUE TITLE
The report API endpoint should allow "amo" as a valid report_entry_point value

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-server#12741]
### Describe the problem and steps to reproduce it:

Submit a report to AMO fusing the mozAddonManager.reportAbuse API method ([Bug 1580561](https://bugzilla.mozilla.org/show_bug.cgi?id=1580561)):
- On a Firefox >= 71, with the following preferences to set:
  - extensions.abuseReport.amWebAPI.enable - true
  - extensions.abuseReport.url : https://addons-dev.allizom.org/api/v4/abuse/report/addon/
  - extensions.abuseReport.amoDetailsURL : https://addons-dev.allizom.org/api/v4/addons/addon/
- load "https://addons.mozilla.org" in a new tab
- open the webconsole panel
- call `await navigator.mozAddonManager.reportAbuse("worldwide@radio");
- wait for a report dialog window to be open:
  - selet any abuse reason
  - type any description
  - press "Submit"

### What happened?

An "Error submitting abuse report" error has been logged in the tab webconsole, in the Browser Console (after enabling the "Show Content Messages" checkbox), the following error is being logged:

```
ERROR_CLIENT - {"status":400,"responseText":"{\"report_entry_point\":[\"\\\"amo\\\" is not a valid choice.\"]}"} AbuseReporter.jsm:75
``` 

### What did you expect to happen?

- The AMO report API endpoint should consider "amo" a valid "report_entry_point" value
- The report should have been submitted successfully

### Screencast from QA

![abuseviaapi](https://user-images.githubusercontent.com/11484/67695316-1e03db00-f9a5-11e9-9b45-f1dd6176eeae.gif)

**Comment by rpl** [comment]
@diox it looks that the underlying issue is just that "amo" is not yet considered as a valid "report_entry_point", would you mind to look into adding it to the expected entry points so that QA can continue to QA verify Bug 1580561 (and it is also going to be needed by the AMO frontend itself too, because Bob has recently started to work on integrating the new mozAddonManager method in the AMO frontend).

**Comment by diox** [comment]
Yeah, it makes sense to have a specific `report_entry_point` for AMO. I'll leave it `null` if not specified, though, in case it's helpful to differentiate them.

**Comment by bobsilverberg** [comment]
Just a note, this blocks https://github.com/mozilla/addons-frontend/issues/8762

**Comment by vcarciu** [comment]
I am now able to submit the abuse report via mozAddonManager.reportAbuse API method . Marking issue as verified : 
![abuseapi](https://user-images.githubusercontent.com/1583842/67859972-7f52b800-fb25-11e9-8809-fba87a8a835c.gif)
