### ISSUE TITLE
DevHub profile avatar is distorted for images with a higher width or height

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12752]
### Describe the problem and steps to reproduce it:
1. Edit your user account on AMO and add a wide image as your profile picture
2. Open DevHub homepage and notice the layout of your avatar

### What happened?
The avatar is distorted

### What did you expect to happen?
We should avoid displaying a distorted avatar

### Anything else we should know?
- this styling has been introduced in #7709 as a fix for #5116

[wide picture]
![image](https://user-images.githubusercontent.com/31961530/67765529-07b55800-fa55-11e9-8d56-762511bfe3ce.png)

![image](https://user-images.githubusercontent.com/31961530/67765852-c2ddf100-fa55-11e9-9017-d67b4b21e30f.png)

[tall picture]
![image](https://user-images.githubusercontent.com/31961530/67765884-dbe6a200-fa55-11e9-9979-0354cf4575fa.png)

**Comment by eviljeff** [comment]
I can't see it's distorted, it's just small with a circular border.  If the image is the wrong shape and size there isn't much choice - you need to do some combination of scaling with or without respecting aspect ratio, and cropping or adding whitespace.

Perhaps the image should only be square but a) that'd be an API/frontend issue and b) we'd have to do something about the existing images.
