### ISSUE TITLE
[Mobile] Layout in Extensions Developers Newsletter section is broken when the invalid email error is present

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12753]
### Describe the problem and steps to reproduce it:
1. Open DevHub homepage in mobile view - https://addons.allizom.org/en-US/developers/
2. Scroll down to the Connect with us section
3. Add an invalid email in the Developer newsletter section - i.e. `abcd@efg`
4. Check the Mozilla Privacy Notice checkbox
5. Click on Sign up
6. Notice the section layout

### What happened?
The layout is broken when the invalid email error is present

### What did you expect to happen?
No layout issues

### Anything else we should know?
- also happened before #12713 was fixed

![image](https://user-images.githubusercontent.com/31961530/67775713-fcb7f300-fa67-11e9-9b0a-811efe0d3a5e.png)

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by rylancole** [comment]
I would like to take this as my first bug

**Comment by caitmuenster** [comment]
Hey @rylancole, go for it! Submit a PR when you are ready to have someone look at your patch, or ask @eviljeff if you need any help. :)

**Comment by eviljeff** [comment]
@rylancole after you've worked out what css to change to fix it, https://github.com/mozilla/addons-server/blob/master/static/css/devhub/new-landing/sections/connect.less is the file that would need to be updated.  

Locally, to see the changes you need to touch (save) https://github.com/mozilla/addons-server/blob/master/static/css/devhub/new-landing/base.less each time you make a change to any of the `.less` files in https://github.com/mozilla/addons-server/blob/master/static/css/devhub/new-landing/ to trigger the `.less` file recompilation to `.css`.  Only the `.less` file changes are submitted in the PR.

**Comment by AlexandraMoga** [comment]
@muffinresearch I've noticed you added thiis issue in the current milestone but the fix is available only on -dev.
We should probably move it to the next week's milestone.

The issue is verified fixed on -dev:

 
![image](https://user-images.githubusercontent.com/31961530/72530297-c1afa980-3877-11ea-94bb-570234f2ea31.png)

**Comment by muffinresearch** [comment]
@AlexandraMoga ah yes good catch, I missed the tag.
