### ISSUE TITLE
Loading unlisted queue times out.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12766]
### Describe the problem and steps to reproduce it:

Load https://reviewers.addons.mozilla.org/en-US/reviewers/unlisted_queue/all

### What happened?

After one minute: blank page. Response code: 504

### What did you expect to happen?

Unlisted queue. Response code: 200

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
The queue does all sort of crazy joins... all for information we don't really need anyway, as it's not really a queue but rather a big list of everything that has unlisted versions. Going to simplify the query and what's displayed.

**Comment by ioanarusiczki** [comment]
@diox 

- Compared with stage, dev is faster when it's loading 

![on dev](https://user-images.githubusercontent.com/33448286/68190071-6af33d00-ffb5-11e9-9ba6-880d7be93293.gif)


- `Last review` and `Last Update` columns are no longer available on dev 

dev 

![The table on dev](https://user-images.githubusercontent.com/33448286/68190277-c58c9900-ffb5-11e9-8da2-da7d7a85c5ed.png)

stage 

![the table on stage](https://user-images.githubusercontent.com/33448286/68190298-d5a47880-ffb5-11e9-8c19-1293f65130b8.png)

**Comment by diox** [comment]
> Last review and Last Update columns are no longer available on dev. Also id column was added. Let me know if that was intended.

It was.
