### ISSUE TITLE
'Visit the Extension Workshop` link is too close o the banner decoration on mobile view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12765]
### Describe the problem and steps to reproduce it:
1. Log in to the Developer hub on mobile  - https://addons.allizom.org/en-US/developers/
2. Notice the position of the 'Visit the Extension Workshop` link

### What happened?
There is no spacing between the link and the banner decoration (the umbrellas) 

### What did you expect to happen?
Increase the `padding-bottom` of the banner

![image](https://user-images.githubusercontent.com/31961530/67927559-90e99d80-fbc1-11e9-805e-f0a0c4e05bc8.png)

**Comment by junngo** [comment]
Hello.
I submitted PR. If you have time, please review it.

**Comment by AlexandraMoga** [comment]
Verified fixed:

![image](https://user-images.githubusercontent.com/31961530/68301162-05cc4400-00a8-11ea-92ee-bfce084b648b.png)
