### ISSUE TITLE
Get comments API is slow, even when cached

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#12779]
### Describe the problem and steps to reproduce it:

* Browse a version in Code Manager like https://code.addons-dev.allizom.org/en-US/browse/616959/versions/1688394/
* Enter 10 or more comments
* Open the Network panel
* Reload the page
* The app makes a GET request to load the saved comments. See https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-

### What happened?

The GET request is pretty slow. It's about 1 second for 10 comments and 2 seconds for 25 comments.

### What did you expect to happen?

It should be faster 🚀 

### Anything else we should know?

Curiously, the response is still slow when it's cached using an etag. Maybe this is a server bug? If you think the frontend is doing something wrong for cached requests, please file an issue.

Here are some screenshots showing me loading 26 comments, with and without cache. In the cached response, the server did respond with a 304 status.

<details>
<summary>Screenshots</summary>

<img width="1454" alt="Screenshot 2019-10-31 15 02 24" src="https://user-images.githubusercontent.com/55398/68057463-fb830200-fcc3-11e9-944b-8b81f70ec9d1.png">
<img width="1454" alt="Screenshot 2019-10-31 15 02 50" src="https://user-images.githubusercontent.com/55398/68057464-fb830200-fcc3-11e9-81cc-a2ff03fa306f.png">

</details>

**Comment by diox** [comment]
> Curiously, the response is still slow when it's cached using an etag. 

That's not surprising - we don't do any caching for ETags, so we just go through the view and avoid serving a response body.

**Comment by diox** [comment]
We haven't really done much in terms of optimizations to these APIs yet, so there are a lot of easy gains to make. I took a quick glance, here is what I found, I may have missed more:

- `get_version_object()` is called multiple time but the result isn't stored on the instance, resulting in multiple database calls for each request
- In the serializer it appears that `version` is grabbed from the context, so if that works at least we're avoiding that, that's good. I don't see a test proving that this optimization works though (see below note about lack of `assertNumQueries`)
- There is not `select_related()` for the `canned_response` or the `user`, and the model doesn't have anything to do that automatically so there will be two additional queries per item returned.
- There are no `assertNumQueries` tests covering this API

**Comment by cawfeecake** [comment]
Hello,

I'd like to contribute, but I'm not sure where to start. Is there any beginner's contribution materials? Apologies in advance if I'm in the wrong place.

This seems like it could be an easily reproducible issue with a clear end-goal that a first timer like myself could sink their teeth into. I need help reproducing the high load time issue along with setting up the project locally.

Thank you for your help and time!

**Comment by EnTeQuAk** [comment]
Indeed, the view hasn't been optimized yet for performance - I initially focused on making sure to get the security related functionality right. Thanks @diox for the analysis.

I'll look into it.

**Comment by kumar303** [comment]
> I'd like to contribute, but I'm not sure where to start. Is there any beginner's contribution materials? 

Hi @cawfeecake , thanks for your interest in contributing! The best place to start are issues labeled as [good first bug](https://github.com/mozilla/addons-server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22).

**Comment by diox** [comment]
See also: https://github.com/mozilla/addons-server/issues/12427

**Comment by diox** [comment]
Taking since I had started looking at this a while back.
