### ISSUE TITLE
Remove all references to complete themes in the code

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12777]
We still have some supporting code for XUL complete themes - lets remove it.

**Comment by ioanarusiczki** [comment]
@eviljeff 
If there are specific details we should focus on in dev hub, let me know. Else we'll verify deb hub on AMO stage during the release testing.

**Comment by eviljeff** [comment]
Nothing in particular, it should be dead code.  I'll mark it as QA-
