### ISSUE TITLE
Deterrent for abusing Review and Abuse Report System

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#12796]
Further to the previous discussion about disgruntle developers using the AMO Review and Abuse Report System to vent anger and/or retaliate against unfavourable reviews, new circumstances have come to attention where a reviewer is using the Review and Abuse Report System to not only attack but to spread specific false claims, disinformation & defamation.

Flagging & deleting the reviews does nothing to deter such behaviour. IMHO, removal of those who make false report, libel and/or defame should be considered as a deterrent.

```
https://addons.mozilla.org/en-US/firefox/addon/firemonkey/reviews/1442001/
https://reviewers.addons.mozilla.org/en-US/reviewers/abuse-reports/firemonkey
```

@caitmuenster @jvillalobos @wagnerand

**Comment by jvillalobos** [comment]
What do you mean by removal? Deleting the account isn't a much stronger deterrent than deleting a review, since both can be recreated fairly easily.

**Comment by erosman** [comment]
I thought that is still better than doing nothing. It still sends a stronger message than only deleting the review.
I couldn't think of anything else to suggest!!

**Comment by eviljeff** [comment]
I'm reading @jvillalobos's message from November as wontfix.  He can reopen if there's more to add.

**Comment by erosman** [comment]
@jvillalobos @eviljeff  That guy is again spamming the review with 1 star
`https://addons.mozilla.org/en-US/firefox/addon/firemonkey/reviews/1480945/`

Since the user has been a long time user, blocking the user would have some effect even though it wont stop the user form re-registering.

Otherwise, vindictive users should not be allowed to spam the review system and/or hold developers to ransom.
