### ISSUE TITLE
Allow unlisted reviewers to act on specific versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12792]
Contrary to listed, the notion of "latest version" doesn't make much sense for unlisted, and each version should ideally be considered a completely separate entity. The reviewer tools were built for listed and don't really handle versions besides the latest one, with the exception of the "reject multiple versions" action.

At least for #12670, but possibly for other use cases as well, we need reviewers to be able to act on a specific unlisted version (the other unlisted versions of the add-on might still matter for context).

**Comment by AlexandraMoga** [comment]
Verified fixed on dev.
The review page for unlisted add-ons gives the option to Reject or Confirm multiple versions. By selecting these options, reviewers can choose specific versions from a list to act upon.
This works both fore purely unlisted add-ons and for unlisted versions of mixed add-ons. 

![image](https://user-images.githubusercontent.com/31961530/70047733-48167180-15d1-11ea-9329-fe8a5cb71665.png)
