### ISSUE TITLE
Extract rule names from the `customs` results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12803]
This will allow us to associate a scanner rule with a customs scanner result.

**For QA:** once this is fixed (and we have customs rule names registered in the admin), new customs scanner results might be associated with customs scanner rules.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev and the "customs" scanner result will show matched rules identified in submitted add-ons.

Marking the issue as verified fixed.
