### ISSUE TITLE
Scanner rules should be unique per scanner

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12801]
### Describe the problem and steps to reproduce it:

1. Create a scanner rule `A` for scanner `X`
2. Create a scanner rule `A` for scanner `Y` (Y should not be X)

### What happened?

It is not possible because `A` is already used.

### What did you expect to happen?

`A` should be created for both scanners because they are different.

### Anything else we should know?

We should have unique rules per scanner. So it is fine to have a rule `A` for scanner `X` and a rule `A` for scanner `Y`, but we should not be able to create rule `A` two times for the same scanner.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/68287221-0a363400-008b-11ea-9efd-fce691051e3b.png)


Additionally, it is not possible to add duplicate rules for the same scanner.
