### ISSUE TITLE
Store guid in Block model and rely on it as the source of truth

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12815]
When the Block model was implemented for #12454 it was implemented with an fk to Addon.  Which works great until the developer deletes the Addon instance and we still want the GUID to not change and refer to the new Addon.  So instead the Block needs to store the GUID directly and lookup the Addon instance from the guid.

**Comment by ioanarusiczki** [comment]
@eviljeff I see on admin tools dev that the first column is the `GUID` 

![guid - first column](https://user-images.githubusercontent.com/33448286/68768363-0a09db80-062b-11ea-8108-8513b868cfac.png)

Let me know if I can test anything else for this issue. 
Thanks!

**Comment by eviljeff** [comment]
ah, sorry, I probably should have marked this QA not needed because it's a model change that should be transparent.  As long as everything works as before it's working.
