### ISSUE TITLE
Add primary hero shelf featured images (again)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12818]
Duplicate of #12184 

The primary hero shelf currently only allows a selection of 2 placeholder images. We need a wider selection, as per the PRD, for launch.

Ideally they can be attached to this issue.

**Comment by jvillalobos** [comment]
[Hero Image.zip](https://github.com/mozilla/addons-server/files/3843806/Hero.Image.zip)

Here are the final images to add.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I believe the [images](https://github.com/mozilla/addons-server/issues/12818#issuecomment-553642857) will be available in prod only ?
In admin tools dev I see the two testing placeholders as being available. 

![admin tools](https://user-images.githubusercontent.com/33448286/69063986-1a082d80-0a26-11ea-9e68-40cd93446fe2.png)

The frontend will display one (depending which was selected) such as: 

![the first placeholder](https://user-images.githubusercontent.com/33448286/69064217-7c612e00-0a26-11ea-98aa-014e3254bb27.png)

**Comment by eviljeff** [comment]
@ioanarusiczki addons-dev deploy was broken.  If you try again now it should show the new images (without the placeholder images)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I see them now being available for the discovery items on dev https://addons-internal.dev.mozaws.net/en-US/admin/ with FF70(Win10). 

I don't think that not being aligned is a problem but if that should be fixed I'll file an issue. 

![the new images](https://user-images.githubusercontent.com/33448286/69134070-a0248280-0abf-11ea-96e1-81871eca1fca.png)


- As functionality - I can select and save one of the images. 

The frontend on AMO dev will show it like this (this is fullscreen - desktop): 

![fullscreen on desktop](https://user-images.githubusercontent.com/33448286/69134244-d8c45c00-0abf-11ea-9119-b6e5112d67e0.png)

- I've noticed that right now on stage when I use responsive design mode and I resize the browser the placeholders for testing look smaller at 1000x1000 or 800x1000 pixels.  

Layout AMO stage 

![layout on AMO stage](https://user-images.githubusercontent.com/33448286/69135502-dcf17900-0ac1-11ea-82be-9bee87b9827c.png)

Layout on AMO dev 

![AMO dev layout](https://user-images.githubusercontent.com/33448286/69135615-0f02db00-0ac2-11ea-9aa5-56fac2af7158.png)

I think at a smaller size (the actual on stage) looks better. Let me know if I must file a followup.

**Comment by eviljeff** [comment]
@ioanarusiczki anything frontend related you should file an issue about there - I've not been involved with the recent UI adjustments

**Comment by ioanarusiczki** [comment]
@eviljeff Done. I filed 2 followups 
https://github.com/mozilla/addons-server/issues/12901
https://github.com/mozilla/addons-frontend/issues/8949

This issue is verified on AMO dev with FF70(Win10).
