### ISSUE TITLE
Addon has no persona

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1282]
This keeps occurring on some themes:

https://sentry.prod.mozaws.net/operations/olympia-prod/group/151490/

Bad data? Is this an add-on with no owner from the getpersonas migration? If so could we just assign them all to a reviewer or admin?

**Comment by andymckay** [comment]
Also: https://sentry.prod.mozaws.net/operations/olympia-prod/group/151588/ and https://sentry.prod.mozaws.net/operations/olympia-prod/group/151588/

**Comment by jasonthomas** [comment]
Most of this looks like bot/spider traffic. See Agent/Browser information in Sentry. Maybe search engines are looking at deleted themes?

**Comment by andymckay** [comment]
I kind of hope that a deleted or disabled theme should not be accessible
and generate a 500 at all. Even though I've disabled one theme, it still
shows up.

**Comment by andymckay** [comment]
I think this is similar to #2051. In fact so similar I'm going to dupe that to this.

**Comment by eviljeff** [comment]
I'm clearing this milestone - please add one back when there is a commit that is likely to land.

**Comment by eviljeff** [comment]
wontfixing this because the sentry links don't work any more and it's not clear what was broken.

**Comment by EnTeQuAk** [comment]
The errors are still in sentry though and are still happening. I never investigated this more though and it could very certainly be legacy + Thunderbird/SeaMonkey related

**Comment by diox** [comment]
Won't matter much with the migration to static themes. Although we do need to make sure the migration script doesn't blow up with those add-ons...
