### ISSUE TITLE
Flagged Reviews not appearing in the Moderated Review Queue

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#12829]
This issue has been present for a while. Reviews are flagged but they don't appear in the Moderated Review Queue.

Apparently the flagging process is completed and database is updated and the issue is with displaying the flagged items.

**Comment by diox** [comment]
Something weird is going on here.

The page is https://reviewers.addons.mozilla.org/en-US/reviewers/queue/reviews?page=1
`Rating.objects.all().to_moderate().order_by('ratingflag__created')` is the ORM code being executed by the view.

As I'm writing this the view returns 682 objects over 22 pages.

However, running the query using s.t.a.m.o. returns ... 722 for that query, with the caveat that I simplified it to just return the `ids` of the reviews using `str(Rating.objects.all().values('id').to_moderate().order_by('ratingflag__created').query)` ...

**Comment by eviljeff** [comment]
for the record:
```SELECT `reviews`.`created`, `reviews`.`modified`, `reviews`.`id`, `reviews`.`addon_id`, `reviews`.`version_id`, `reviews`.`user_id`, `reviews`.`reply_to`, `reviews`.`rating`, `reviews`.`text_body`, `reviews`.`ip_address`, `reviews`.`editorreview`, `reviews`.`flag`, `reviews`.`deleted`, `reviews`.`is_latest`, `reviews`.`previous_count` FROM `reviews` LEFT OUTER JOIN `reviews` T2 ON (`reviews`.`reply_to` = T2.`id`) INNER JOIN `addons` ON (`reviews`.`addon_id` = `addons`.`id`) LEFT OUTER JOIN `versions` ON (`reviews`.`version_id` = `versions`.`id`) LEFT OUTER JOIN `reviews_moderation_flags` ON (`reviews`.`id` = `reviews_moderation_flags`.`review_id`) WHERE (NOT (`reviews`.`deleted` = True) AND NOT (T2.`deleted` = True AND T2.`deleted` IS NOT NULL) AND NOT ((`reviews`.`addon_id` IS NULL OR (`versions`.`channel` = 1 AND `versions`.`channel` IS NOT NULL) OR `reviews`.`id` IN (SELECT U0.`id` FROM `reviews` U0 LEFT OUTER JOIN `reviews_moderation_flags` U1 ON (U0.`id` = U1.`review_id`) WHERE (U1.`id` IS NULL AND U0.`id` = (`reviews`.`id`))))) AND `addons`.`status` IN (3, 4) AND `reviews`.`editorreview` = True) ORDER BY `reviews_moderation_flags`.`created` ASC```

**Comment by AlexandraMoga** [comment]
Mentioned also in https://github.com/mozilla/addons-server/issues/6948#issuecomment-382392156 that flagged reviews are not appearing in the Moderation queue as they should.

**Comment by diox** [comment]
Yeah and @erosman mentioned that the review in question did eventually appear in the queue. Why is still a mystery to me though, since there is no caching on this page. The query being made is pretty weird though, so maybe it's just that the reviews are being "hidden" by a flaw in the query.

**Comment by eviljeff** [comment]
DB replication lag?

**Comment by diox** [comment]
I suspect that, but replication lag should be < 1 second at all times, and it latest for way longer than that. s.t.a.m.o. is also running on a replica AFAIK, and I could see the review there. Plus, even once the review appeared in the UI, the counts were still not in sync.
