### ISSUE TITLE
The link to the add-on details page from the Block history section is throwing a server error

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12834]
Follow up for #12464 

### Describe the problem and steps to reproduce it:
1. Log in to AMO with an admin account
2. Go to django admin and open the Blocklist module
3. Select one of the entries to open the edit page - see https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/12/change/
4. Click on the linked add-on name from one of the entries listed in Block history

### What happened?
The link points to `https://addons-internal.dev.mozaws.net/en-US/firefox/addon/{add-on_slug}/`, which triggers a server error

### What did you expect to happen?
The link should point to the add-on details page on the frontend 

![2019-11-08_15-27-48](https://user-images.githubusercontent.com/31961530/68480532-b1f36380-023d-11ea-9741-bdd35c61ddd0.gif)

**Comment by eviljeff** [comment]
Fwiw, this is a generic flaw with any ActivityLog displayed in django admin.  The addon link will be removed with the fix for #12835 so the issue will be "fixed" by that
