### ISSUE TITLE
Block history entries do not mention whether the `Include in legacy` checkbox was marked in past entries 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12835]
Follow up for #12464 

### Describe the problem and steps to reproduce it:
1. Log in to AMO with an admin account
2. Go to django admin and open the Blocklist module
3. Select one of the entries to open the edit page - see see https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/4/change/
4. Scroll down and mark the 'Include in legacy' checkbox
5. Click on Save and continue editing
6. Notice your changes in the Block history section

### What happened?
There is no menttion of the fact that the Include in legacy checkbox was marked
### What did you expect to happen?
Block history entries should mention whether the Include in legacy checkbox was marked in past blocks
### Anything else we should know?
- The requirement in https://github.com/mozilla/addons-server/issues/12464#issue-499652390 mentions that this information should be present

**Comment by eviljeff** [comment]
it wasn't in the mock so I figured it wasn't necessary 😬 

@jvillalobos to indicate how he'd want the missing information presented (`url` and `include_in_legacy` aren't shown in the log)

**Comment by jvillalobos** [comment]
Good catch. Here's a revised version:

> Aug 20, 2019. theone [blocked player@falsh.biz](), versions 0 - 1.2. Included in legacy blocklist.

The "blocked GUID" part of the log should be linkified when there's a `url` available, and the second sentence should be added when the legacy blocklist is included.

**Comment by ioanarusiczki** [comment]
Verified on admin tools dev with FF70(Win10)

![to the legacy blocklist](https://user-images.githubusercontent.com/33448286/68764568-9ca67c80-0623-11ea-80e4-c0823aa89be1.png)
