### ISSUE TITLE
When applying "Delay auto-approval by x" action, also flag the version for human review

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#12833]
"Delay auto-approval by x" (24 hours or indefinitely) implemented in https://github.com/mozilla/addons-server/issues/12671 should flag the version for human review as well.

**Comment by diox** [comment]
@wagnerand can you confirm whether we want this ?

**Comment by wagnerand** [comment]
Yes! It would be good if the queue would somehow differentiate between no delay, 24 hours and indefinitely.

**Comment by vcarciu** [comment]
Verified as fixed(When applying "Delay auto-approval by x" action, human review was added too) :
![delayedapprovalhumanreview](https://user-images.githubusercontent.com/1583842/68788541-4bf74980-064c-11ea-8503-d67b6203fd31.png)
