### ISSUE TITLE
about:addons download counter stuck in uint max

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1284]
STR:
1) Go to about:addons
2) Log out if you're logged in
3) In the top-right panel, you should see  Add-ons downloaded: 4,294,967,295.

It's been pointed out to us that this is the max value for a 32bit unsigned integer.  We hit 4B downloads almost a year ago, so this number should be much larger.

**Comment by rctgamer3** [comment]
https://services.addons.mozilla.org/discovery/pane/account

**Comment by andymckay** [comment]
![](http://www.mactrast.com/wp-content/uploads/2011/07/McDonalds.jpg)

**Comment by deadsquid** [comment]
So the proposed fix is prefacing it with "More than " ?

**Comment by wagnerand** [comment]
The screenshot says "Over"!

**Comment by deadsquid** [comment]
That's McDonald's sign 1.3. McDonald's Sign 3.1 uses "More than". If we're looking to economize space, we could just use ">".

**Comment by rctgamer3** [comment]
Bump.

**Comment by jvillalobos** [comment]
For anyone interested, adding all the totaldownloads in the addons table currently produces 4,641,665,580.

**Comment by andymckay** [comment]
This counter is going away, its not there on the new disco pane.

https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements
