### ISSUE TITLE
Block history not populated if the blocked add-on has a previous deleted block 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12840]
Follow up for #12464 

### Describe the problem and steps to reproduce it:
1. Log in to AMO with an admin account
2. Open the Blocklist module in django admin
3. Add a new add-on to the blocklist
4. Delete the add-on block
5. Add the same add-on to the blocklist again
6. Observe the Block history after you Save your changes

### What happened?
Block history is not populated

### What did you expect to happen?
Block history is populated

### Anything else we should know?
Here is an example: https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/17/change/
![image](https://user-images.githubusercontent.com/31961530/68570801-23175e80-046a-11ea-8177-a0c5821a843a.png)

**Comment by eviljeff** [comment]
the PRD didn't specify anything about Block deletion so the "correct" behaviour was undefined.

In the process of discussing the fix for #12835 it was decided to change how the logs are indexed so we will be able to display logs for deleted Blocks too.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

[This add-on](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/282/change/) has been blocked, deleted and blocked again. The block history shows a record of these actions:

![image](https://user-images.githubusercontent.com/31961530/69248961-d93f1e80-0bb5-11ea-9d27-11cdaaa3520b.png)
