### ISSUE TITLE
Drop view_source property from Addon model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12842]
follow up from #12514

**Comment by Abhi-khandelwal** [comment]
Can I pick this issue ?

**Comment by eviljeff** [comment]
@Abhi-khandelwal sure.  It's just removing the property from the model and any tests that reference it.  The django migration will have to land in a different tag/milestone.

**Comment by smishra2903** [comment]
If this is still open, can I take this issue?

**Comment by eviljeff** [comment]
It's currently assigned to @Abhi-khandelwal but I don't know if he's working on it.  If he confirms he's not, go ahead.

**Comment by hwj0418** [comment]
@eviljeff Hi I saw this issue is still open, could I take it? I have a solution already.

**Comment by eviljeff** [comment]
@hwj0418 go ahead

**Comment by junngo** [comment]
Hello eviljeff :)
I have a questions before to fix this issue.
After drop view_source property,  Should It delete all related fixtures code(e.g [2][3] ... )?
It have many related code more than I think.
It may be obvious, but I would like to proceed with confirmation.

[1]
https://github.com/mozilla/addons-server/blob/86c89eb0286f761be6f8f65a6bccdb2cd16dc564/src/olympia/addons/models.py#L414
[2]
https://github.com/mozilla/addons-server/blob/86c89eb0286f761be6f8f65a6bccdb2cd16dc564/src/olympia/addons/fixtures/addons/base_es.json#L8
[3]
https://github.com/mozilla/addons-server/blob/86c89eb0286f761be6f8f65a6bccdb2cd16dc564/src/olympia/addons/fixtures/addons/listed.json#L19

**Comment by eviljeff** [comment]
> After drop view_source property, Should It delete all related fixtures code

yes

**Comment by ioanarusiczki** [comment]
@eviljeff 
- The public source code setting from DevHub has been removed a while ago https://github.com/mozilla/addons-server/issues/12418
- When calling the v4 and v5 addon API, the response does not return `is_source_public ` property https://github.com/mozilla/addons-server/issues/12514#issuecomment-553453956

If there's anything else to check on, let me know.

**Comment by eviljeff** [comment]
it's a backend change in the models, there shouldn't be any noticeable differences.
