### ISSUE TITLE
Add actions to report feedback on the scanner results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12853]
We'd like to report feedback on the scanner results. We have two possibilities:

- false positive: scanner result was incorrect
- true positive: scanner result was correct

When marking a result as true positive, we'll simply update its state (see #12851) and return to the list.

When reporting a result as false positive, we'll create a GitHub issue _draft_ with some relevant information after having updated the state of the result.

**Comment by ioanarusiczki** [comment]
@willdurand 
- the true positive button works as expected. I can mark the add-on from the list and then if I select `By state` I can see it available in the list of add-ons marked as `true positive`. 
- for the `false positive` I receive a 404 (on dev and stage)

![404 for false positive](https://user-images.githubusercontent.com/33448286/69224463-49817c00-0b85-11ea-915c-b1c0106ecdc2.gif)

**Comment by willdurand** [comment]
@ioanarusiczki I deleted your screencast since it shows some of the rule names.

**Comment by ioanarusiczki** [comment]
@willdurand Got it! I'll avoid showing the rules.

**Comment by willdurand** [comment]
> for the `false positive` I receive a 404 (on dev and stage)

I think it is a 404 because you do not have access to the GitHub repositories. In theory, you should be on the `github.com` domain. If that is the case, then it is good.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, looks like that's the reason. Well, because I cannot complete the Github step I won't see a `false positive` instead of the `unknown` state. 
There are 5 add-ons in the list reported as `false positive` though. Looks like someone with access tested it.

**Comment by willdurand** [comment]
> @willdurand Yes, looks like that's the reason. Well, because I cannot complete the Github step I won't see a `false positive` instead of the `unknown` state.

mmm results should still be marked as false positive. The redirect happens after.

**Comment by ioanarusiczki** [comment]
@willdurand Yes they are indeed ! They're ordered after the `Created` date when I select `False positive` from the filter. 
Verified on dev with FF70(Win10).
