### ISSUE TITLE
Add a state field on the `ScannerResult`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12851]
We need a new `state` field to be able to triage scanner results. We'll have 3 choices for now:

- unknown (default)
- true positive (scanner result reported something of interest for us
- false positive

**Comment by ioanarusiczki** [comment]
@willdurand on dev with FF70(Win10):
 - The `state` field is available in the scanner results table and it can be `unknown`, `false positive` or `true positive`. 

I see the number of results at the bottom of the page. The Filter Menu is at the top. When I change the filter By state `All` to `Unknown` or `true positive` I don't see the number of items updates unless I scroll down. It would be better to see it at the top of the page. 
Let me know what you think. 

![number of results and paging](https://user-images.githubusercontent.com/33448286/69226293-931f9600-0b88-11ea-98c9-01696c0fd737.png)

**Comment by willdurand** [comment]
> I see the number of results at the bottom of the page. The Filter Menu is at the top. When I change the filter By state `All` to `Unknown` or `true positive` I don't see the number of items updates unless I scroll down. It would be better to see it at the top of the page.
> Let me know what you think.

This is the default "django admin" layout. Maybe we could change it but it is like that for all other admin pages.
