### ISSUE TITLE
Raise an error when submitting an empty comment

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#12865]
### Describe the problem and steps to reproduce it:

Make a post to the [comment API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#post--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-) with an empty comment (e.g. an empty string).

### What happened?

The API accepts the comment.

### What did you expect to happen?

The API should return a [standard 400 error response](https://addons-server.readthedocs.io/en/latest/topics/api/overview.html#bad-requests) saying that empty comments are not allowed.

### Anything else we should know?

Related: https://github.com/mozilla/addons-code-manager/issues/1106

**Comment by ioanarusiczki** [comment]
@kumar303 I receive a 400 Bad request for an empty comment.
"comment":""

![empty comment](https://user-images.githubusercontent.com/33448286/69435165-b47ab080-0d47-11ea-9f1d-8076963207ef.png)
