### ISSUE TITLE
bulk addon block entry

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12870]
splitting out the bulk case from #12458 
Where there are a large (mocks suggest 100+) number of guids the add page should only load limited amounts of data for each guid, and then create/update the blocks in a celery task rather than in the request/response.

**Comment by eviljeff** [comment]
fwiw @jvillalobos in #12458 QA report 200 guids work without issue

The actual creating of the blocks for multiple guids (i.e. more than 1 guid) will be pushed to a celery task after this issue so the 100 (or whatever) limit will just be for the page load and what addon details are displayed.

**Comment by AlexandraMoga** [comment]
I've retested the bulk add-on blocking option on -dev and the form will exclude additional add-on data (link to review page, link to previous block) when blocking more than 100 GUIDs.

![image](https://user-images.githubusercontent.com/31961530/69629375-dbd9c200-1054-11ea-8a07-5e0425344029.png)

@eviljeff I've noticed something that wasn't present before. If I'm adding a bulk of >20 GUIDs to the list, once I save my changes, I'm not seeing all the new added GUIDs in the block list.  The list is updated only after a page refresh.

**Comment by eviljeff** [comment]
>  I've noticed something that wasn't present before. If I'm adding a bulk of >20 GUIDs to the list, once I save my changes, I'm not seeing all the new added GUIDs in the block list. The list is updated only after a page refresh.

That's expected - for multiple guids the database saving is now in an asynchronous celery task so unless it's really quick it doesn't complete before the page reloads.
