### ISSUE TITLE
Fix feedback button style in scanner result admin (list)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12882]
### Describe the problem and steps to reproduce it:

1. Go to the admin > scanners > scanner results
2. Observe the buttons (in -dev)

### What happened?

<img width="355" alt="Screenshot 2019-11-15 at 13 43 26" src="https://user-images.githubusercontent.com/217628/68945556-f38d8c80-07b0-11ea-80e6-7dbc610cb289.png">

### What did you expect to happen?

Not that UI glitch.

**Comment by ioanarusiczki** [comment]
Verified on admin tools dev with FF70(Win10). 

![button UI](https://user-images.githubusercontent.com/33448286/69151452-577ec080-0ae3-11ea-803c-b70c967e0b6f.gif)

**Comment by willdurand** [comment]
> Verified on admin tools dev with FF70(Win10).

@ioanarusiczki I removed the screencast to avoid leaking sensitive data
