### ISSUE TITLE
Drop `_` from `files.tests.test_utils_`

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#12895]
This is nearly a cleanup, I don't remember why the ending underscore got added way back (or accidentally?). Let's drop it.

**Comment by diox** [comment]
This is no longer relevant, but back in the day, AMO/Marketplace used to depend on a library that is called [`test_utils`](https://github.com/Kami/python-test-utils/). To avoid clashes when you imported `test_utils` the convention to name those files with an extra underscore was adopted.

**Comment by AlexandraMoga** [comment]
Please add a 'qa:not needed' label to this issue.
Thanks
