### ISSUE TITLE
Unlisted submissions with a delay auto-approval flag are still auto-approved shortly

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12896]
Follow up for #12622 and #12671 

### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev
2. Submit a new unlisted extension that contains a [matched rule](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerrule/) configured with a Delay auto-approval action (24h or indefinite)
3. Check the add-on status after a few minutes

### What happened?
The add-on is approved

### What did you expect to happen?
The add-on is still in an awaiting review state

### Anything else we should know?
- looking at the [Flagged by scanners](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/needs_human_review) queue, the add-ons will appear in the list with the corresponding delay flags:
![image](https://user-images.githubusercontent.com/31961530/69063086-88e48700-0a24-11ea-84be-d7c7a270f7b8.png)
- both add-ons have a a scanner result with a corresponding matched rule

**Comment by eviljeff** [comment]
I don't know if we're relying on these rules working yet. If we are its a P1, otherwise I dunno @diox @willdurand

**Comment by diox** [comment]
We aren't yet, especially for unlisted, but I'll take a look.

**Comment by diox** [comment]
The `auto_approval_delayed_until` field was set properly on the `AddonReviewerFlags` instance, and the `AutoApprovalSummary` instance was created immediately after, but somehow when it ran `check_has_auto_approval_disabled()` it didn't see the delay.

I suspect somehow the `AddonReviewerFlags` instance had already been fetched and cached, as `OneToOneField` are, although I can't find what would have triggered that - it would have needed to be accessed first, but AFAIK that doesn't happen... I'll investigate.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. 

Unlisted submissions that matched a rule with a delay auto-approval action will no longer be auto-approved shortly after submission. Those with a 24h delay will be auto-approved after the flag expires.
