### ISSUE TITLE
Refactor file-locking to use fcntl instead of flufl

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#12894]
Part of #11431 

In #4441 I implemented "NFS safe file-locking" based on flufl.lock.

Unfortunately this works usually fine for a pure NFS and EFS but may fail in certain circumstances on EFS specifically. Since flufl.lock uses it's own locking mechanism this is really hard to debug and there seems to be an easier and more reliable method these days: fcntl.

We should port using `fcntl` which - since NFS 4 - works for both systems (EFS and NFS) perfectly fine and is the recommended way to do file locking.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk does this issue require verification from QA?
Thanks

**Comment by EnTeQuAk** [comment]
Marking as qa: not needed as I'm going to verify that it's working manually. Currently the actual impact on sentry exceptions isn't expected to be too extensive so there might not be much to verify.
