### ISSUE TITLE
Unlisted theme submissions are not signed through the new auto-approval flow

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12892]
Follow up for #12622 

### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev
2. Submit a new unlisted theme (package or wizard)
3. Wait for it to be approved/signed

### What happened?
The theme is not signed

### What did you expect to happen?
Theme is signed after a short while

### Anything else we should know?
@diox 
- these might happen because we do not have an auto-approval workflow for themes (?)
- I've checked with stage and unlisted themes are being signed through the old process

Example of un-signed unlisted theme:
https://addons-dev.allizom.org/en-US/developers/addon/47e5641ef28f4322a95d/versions/1689761

**Comment by diox** [comment]
Yeah forgot that unlisted themes were a thing...

**Comment by AlexandraMoga** [comment]
Verified fixed on stage. Unlisted themes are now signed in a short while after submission. Listed themes are still going through the normal manual approval flow. 

Example of a theme with both unlisted (approved) and listed (awaiting review) versions:
https://addons.allizom.org/en-US/developers/addon/mixed-version-theme/versions
