### ISSUE TITLE
Run all celery tasks on the primary database

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12905]
We have middleware that automatically runs all POST/PUT/PATCH http requests on primary db, but celery tasks that also do database writes aren't pinned to the primary, unless we specifically do `@use_primary_db`.  It will be safer to default to using `@use_primary_db` in celery tasks, and add a decorator/parameter that disables it when we have tasks we know aren't affected by it.

**Comment by EnTeQuAk** [comment]
:+1: it certainly makes things more predictable in production later - at the cost of maybe throwing a few things unnecessarily at the master but I think often we can live with that.

Maybe patch `olympia.amo.celery:AMOTask` to apply the rules by `@use_primary_db` by default?

**Comment by diox** [comment]
> Maybe patch `olympia.amo.celery:AMOTask` to apply the rules by `@use_primary_db` by default?

Yes, something like that would work.
