### ISSUE TITLE
The images for the primary hero items are not aligned

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#12901]
Followup for https://github.com/mozilla/addons-server/issues/12818

STR:
1. Load admin tools dev and go to a discovery item 
2. Observe the images added

![the new images](https://user-images.githubusercontent.com/33448286/69148324-b4c34380-0adc-11ea-9aaa-8df520e2e755.png)

Expected result:
they could use a better alignment

Notes:
Issue is reproducible on admin tools dev with FF70(Win10).

**Comment by junngo** [comment]
I submitted PR to solve this issue.
Please let me know if there is anything to modify.

**Comment by ioanarusiczki** [comment]
@eviljeff Verified on dev and stage - FF75(Win10). 

![aligned](https://user-images.githubusercontent.com/33448286/81156696-e34fb080-8f8e-11ea-82c5-4e4819e73f9e.png)
