### ISSUE TITLE
Add definition to scanner rules (Yara)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12909]
We'd like to store Yara rules in the database. We can reuse the `ScannerRule` model and add a `definition` field to it. We'll have to fill in this field only for Yara rules.

**Comment by willdurand** [comment]
@wagnerand as noted above, the definition has no effect yet but let me know if you need anything else to add/edit/delete Yara rules. This will be available in production on Thursday so that we can port all the rules from the repo to the DB before next week.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
Pre-existing yara rules have a custom Definition field. 
The field will appear automatically when you add a new `yara` rule (`customs` and `wat` don't have it).
The Definition field cannot be empty. 

![image](https://user-images.githubusercontent.com/31961530/69251364-f4139200-0bb9-11ea-981a-ba4aceb6a26d.png)

**Comment by willdurand** [comment]
FTR: I updated the Yara rules with their definitions in -dev.
