### ISSUE TITLE
Add a `category` field to the scanner rules

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12914]
We'd like to assign categories to the rules for various reasons. Each rule could optionally belong to a category. We can start with categories representing our main threats.

**Comment by willdurand** [comment]
I am not sure whether we want to have a static list of categories or a new model to store these categories in the DB. I guess we can start with a static list since there should not be too many categories and we can switch to a model in the future if we need too.

That being said, that depends on which information we'd like to store. If we are going to expose the categories to the reviewers, maybe a description could be useful too.

/cc @wagnerand for that + the initial list of categories

**Comment by diox** [comment]
> That being said, that depends on which information we'd like to store. If we are going to expose the categories to the reviewers, maybe a description could be useful too.

Even then, keeping them static should work, and be easier to translate etc. A simple `JSONField` with an array of category ids should work.
