### ISSUE TITLE
Allow sorting for all columns on admin scanner result page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12917]
Let's make all columns on the admin scanner result page sortable.

**Comment by diox** [comment]
We can already filter by state, filter by matches and by scanner, so I'm curious what the use case for additional sorting is.

Allowing sort by any field has performance implications (eventually the list will grow so large that sorting on a non-indexed field will be a bad idea), and also note that `Add-on` and `Matched Rules` are not a real fields and that makes it hard/impossible to sort on them.

**Comment by wagnerand** [comment]
Heh, those columns where the ones I was most interested in.

Sorting by add-on helps speed up triage because there can be multiple rows per add-on (for multiple versions), and in fact there are already. So, ideally a reviewer looks at them all at once, because they're already handling that add-on.

Sorting by matched rule helps with handling a particular attack or threat, or when dealing with clones of add-ons.

**Comment by diox** [comment]
So, this still has some perf implications to deal with, but maybe we can look into adding the following (optional) features:
- Grouping per add-on
- Filtering by rule (one at a time)

Would that help ?

**Comment by wagnerand** [comment]
> So, this still has some perf implications to deal with, but maybe we can look into adding the following (optional) features instead of adding sort:
> 
>     * Grouping per add-on

I was talking to @willdurand about it. If we group per add-on we will need to solve flagging (true/false positive) for each result.

> 
>     * Filtering by rule (one at a time)

That's #12918.

**Comment by willdurand** [comment]
> I was talking to @willdurand about it. If we group per add-on we will need to solve flagging (true/false positive) for each result.

That depends on how we envision this feature, I guess. We could maybe have all the scanner results for one add-on grouped in the list (as a big row, containing _N_ sub-rows for the _N_ scanner results tied to this add-on). That's just an idea though, I don't know if this is feasible or if that would be helpful.
