### ISSUE TITLE
Add filter for each rule in admin scanner result page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12918]
The admin scanner result page already supports filtering by scanner. In order to focus on specific issues, let's also add a filter for each rule of every scanner (where applicable).

**Comment by diox** [comment]
We should probably also add a link to all results from the rule change/view page (we do something similar in other admin tools, displaying a count of the number of related objects at the same time)

**Comment by AlexandraMoga** [comment]
Scanner results can now be filtered by matched rules. The filter is updated when a a rule is added or deleted.

@diox have you also implemented this:

>We should probably also add a link to all results from the rule change/view page (we do something similar in other admin tools, displaying a count of the number of related objects at the same time)

If I understand correctly, this should have added a link to each scanner rule `/change/` view.

**Comment by diox** [comment]
Ah, it got mixed up in my mind: I wanted to add the link to the results to each rule change page, but I added the link to the rules to each result view page instead :) Both are useful, going to do this.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

- link to matched scanner results in rule change page
![image](https://user-images.githubusercontent.com/31961530/70146455-d579c480-16aa-11ea-8554-7f0d7356bd68.png)

- link to rule change page in scanner result view 
![image](https://user-images.githubusercontent.com/31961530/70146460-d9a5e200-16aa-11ea-9ecf-3ee7e0f33ce0.png)
