### ISSUE TITLE
Use Yara rules stored in the DB in `run_yara()` task

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12913]
In #12909, we added a new `definition` field to the scanner results. We can now store Yara rules in the DB. This issue is about using the Yara rules stored in the DB (instead of the rules in the repo) when running Yara during the submission process.

**For QA:** in all envs, the existing (Yara) scanner rules will be updated with their definitions. Once this issue is fixed, these definitions (stored in the database as part of the scanner results) will be used instead of the definitions stored in the GitHub repo.

One use case is to be able to create new Yara rules, so one scenario could be:

1. create a new scanner rule named `match_all`, with scanner = Yara and the following definition:

    ```yara
    rule match_all { condition: true }
   ```

2. upload a new add-on
3. there should be a scanner result for scanner = Yara and this rule

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

I've created a new yara rule as described in the STR and submitted a few add-ons. 
A yara scanner result was created for all these add-ons, each matching the `match_all` rule.

The existing rules continue to work as before.
