### ISSUE TITLE
Implement delayed calculation of sha-hash in file-tree

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#12920]
This should fix problems like #11904 and maybe more by applying a delayed calculation for the sha256 hashes that get calculated for the file-tree.

Some background information: Currently we do generate a sha256 hash for every file in the file-tree on first access of that file in the code-manager. The complete file-tree information is stored for 24h in memcached for faster retrieval.

When the cache isn't populated yet this will result in very slow first-time access.

There are two ways to fix this:

1. Don't calculate the sha256 hash on first access but calculate them asynchronously and update the entry in the cache once that happened
2. Don't calculate the sha256 hash on first access but only calculate it for files where we actually retrieve the content but then we'll do it during the request. That'll still be fairly fast, even for larger files because we already have the content in-memory. That information can then be put into the cache for even faster retrieval.

Personally I like approach number 2, because that means we avoid useless calculations for files we don't need during a specific review (or just when accessing the code at a later point).

The only disadvantage would be that the code-manager needs to handle not existing hashes appropriately in the file-tree and update local information in case a hash get's provided at a later point.

Is that something we could do @kumar, @bobsilverberg?

**Comment by wagnerand** [comment]
It would be nice to have the hash for every file inside an add-on file always. I have been wanting to get an overview of identical files across all add-ons, and this would do it.

**Comment by EnTeQuAk** [comment]
> It would be nice to have the hash for every file inside an add-on file always. I have been wanting to get an overview of identical files across all add-ons, and this would do it.

You mean as a `hashes` file directly inside the repository? Similar to the files that autograph adds to have hashes for the files we signed?

**Comment by wagnerand** [comment]
I don't really mind where those hashes are stored, although it should allow aggregation across all files in the corpus. My main goal is to find files that are used in lots of add-ons.

**Comment by kumar303** [comment]
Making the UI lazy-load hashes could get complicated and viewing a file hash has been flagged as an important reviewer feature.

Could we just pre-calculate file hashes asynchronously after git extraction and store them in the DB or something?

If it's easier to ship either option 1 or 2 above then let's start with that. We could put a button on the file hash like *Not available. Refresh to Check* as a temporary solution. While inconvenient, this would probably be better than serving slow responses.

**Comment by EnTeQuAk** [comment]
Yes, we could pre-calculate the file hashes after git extraction but that'd store tons of data in the database that we won't use often enough.

While writing this though… as @wagnerand mentioned he'd something that stores the hashes anyway… so I wonder if it really makes sense to store an additional file in the XPI with the file hashes. Let me quickly prototype something and also talk to secops folks if we can use the `META-INF` folder for that. I don't think that won't be an issue but it'd be better to double check.

**Comment by kumar303** [comment]
The file hash has been identified as a key piece of data needed by reviewers so I think it would make sense to store them in the database for easy access.

**Comment by kumar303** [comment]
Also, yeah, https://github.com/mozilla/addons-server/issues/12920#issuecomment-556001083 could benefit from having file hashes in the DB.

**Comment by bobsilverberg** [comment]
Maybe I'm missing something here, but we don't actually need hashes for the tree, do we? We only need a hash for the individual file being viewed. It sounds like option 2 above would address that by not calculating hashes for all of the files in the tree, and only calculating a hash for the file being requested. I don't see the downside to just implementing that.

**Comment by EnTeQuAk** [comment]
> Maybe I'm missing something here, but we don't actually need hashes for the tree, do we? We only need a hash for the individual file being viewed. It sounds like option 2 above would address that by not calculating hashes for all of the files in the tree, and only calculating a hash for the file being requested. I don't see the downside to just implementing that.

Correct, and it'd be relatively easy to implement on my side. All we need is the frontend being able to handle `null` value for the hashes for all other files in the file-tree - which are files that aren't shown to the user.

How much effort would that be?

**Comment by bobsilverberg** [comment]
> Correct, and it'd be relatively easy to implement on my side. All we need is the frontend being able to handle `null` value for the hashes for all other files in the file-tree - which are files that aren't shown to the user.
> 
> How much effort would that be?

Virtually none. As far as I can tell the only time we show the hash is when actually viewing the file (in either compare or browse mode), so if we can continue to assume that we'll always have a `sha256` for any file that we have requested, the only thing we'd need to change are some of the type definitions for the tree entries.

**Comment by kumar303** [comment]
Oh! I probably misunderstood this part. Yes to what Bob said.

**Comment by EnTeQuAk** [comment]
Filed https://github.com/mozilla/addons-code-manager/issues/1297 for the code-manager related work. I'll get the delayed calculation landed asap.

**Comment by bobsilverberg** [comment]
Looking at the code in code-manager, I just want to make sure that this will still work when retrieving the default file for a version. I.e., when the API call is in the format of `https://addons-dev.allizom.org/api/v5/reviewers/addon/495710/versions/1688333/` (without the `file` query param), it should still return the correct sha256 (and not `null`) for the default file (which is `manifest.json`).

**Comment by EnTeQuAk** [comment]
> Looking at the code in code-manager, I just want to make sure that this will still work when retrieving the default file for a version. I.e., when the API call is in the format of https://addons-dev.allizom.org/api/v5/reviewers/addon/495710/versions/1688333/ (without the file query param), it should still return the correct sha256 (and not null) for the default file (which is manifest.json).

Yes, that's correct. So, by definition: The file that get's returned as `content` will have the correct sha256 set. Others might have a sha256 set but we should assume they can be `null`. Does that make sense?

**Comment by bobsilverberg** [comment]
> 
> Yes, that's correct. So, by definition: The file that get's returned as `content` will have the correct sha256 set. Others might have a sha256 set but we should assume they can be `null`. Does that make sense?

Yes, perfect, thanks!

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I verified the regression from code-manager https://github.com/mozilla/addons-code-manager/issues/1393
Let me know if there's anything else to check besides that for this. 
Thanks!
