### ISSUE TITLE
Allow reverting human scanner result verdict

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12939]
### Describe the problem and steps to reproduce it:

When humans happen to click on the wrong button in the scanner admin result list, they need a way to revert that decision.

### What happened?

The actions column shows `-` for triaged results.

### What did you expect to happen?

We could show a "Retriage" or similar button when a result is triaged.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

Admins have the option to revert a triaged scanner result:

![image](https://user-images.githubusercontent.com/31961530/69805961-7f101000-11ea-11ea-8455-993f769036c8.png)
