### ISSUE TITLE
remove addons/featured API endpoint and other feature stuff from v4+ api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12937]
part of #12907 - the user facing add-on featuring support should be removed in v4+ (but stay in v3).  In v3 we will just return if the add-on is recommended instead.

**Comment by AlexandraMoga** [comment]
I've verified the [featured addons](https://addons-server.readthedocs.io/en/latest/topics/api/v3_legacy/addons.html#get--api-v3-addons-featured-) endpoint both in `v4` and `v3` API versions. Below are the results:

https://addons-dev.allizom.org/api/v4/addons/featured/  - returns a 404
https://addons-dev.allizom.org/api/v3/addons/featured/ - returns a list of 10 recommended add-ons

The `is_featured` parameter is no longer present in `v4`, while `v3` still has it, in addition to the `is_recommended` parameter. 

@eviljeff I'm not sure why `/api/v3/addons/featured/` is returning only 10 results, even when I'm requesting a larger `page_size`. I was expecting to see the full list of recommended add-ons (i.e. addons with `is_recommended: true`) when this endpoint is called. 

Were you referring to something else in this comment?
>In v3 we will just return if the add-on is recommended instead.

**Comment by eviljeff** [comment]
I've no idea why it's limited to 10 either tbh.  The default is supposed to 25 (and `page_size` _does_ work if you specify a smaller size)

**Comment by AlexandraMoga** [comment]
Should we do something about this case then, or do we accept that this is how it's working now? To be fair, I don't know if there still are clients that use this endpoint to properly estimate the impact of this issue.

**Comment by AlexandraMoga** [comment]
@eviljeff do you know if the re-indexing took place? So far, the issue I've noticed above is still reproducing.

**Comment by AlexandraMoga** [comment]
Forgot to say that the issue is happening on stage as well with https://addons.allizom.org/api/v3/addons/featured/

**Comment by eviljeff** [comment]
after the ES reindexing was fixed we found out it was just broken.  #13082 should fix it.
