### ISSUE TITLE
Show add-on guid on scanner result page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12945]
### Describe the problem and steps to reproduce it:

The scanner result page should show the GUID of the add-on. This is useful for admins.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/69550313-71b51480-0fa3-11ea-9f7e-9136c90b4ebd.png)
