### ISSUE TITLE
Link to add-on on scanner result page should point to external domain, not internal admin one

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12942]
### Describe the problem and steps to reproduce it:

1. Go to the scanner result page
2. Check the link to the add-on of a result

### What happened?

The link points to `/en-US/reviewers/review/...` and that resolves to the review page on the internal domain.

### What did you expect to happen?

The link should point to `addons.mozilla.org/en-US/reviewers/review/...`

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand I verified on admin tools dev and the links points to `addons-dev.allizom.org/en-US/reviewers/review/...`
