### ISSUE TITLE
Expose MultiBlockSubmit model in django admin

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12958]
The `MultiBlockSubmit` model stores the guids that were submitted to be created as Addon Blocks in the blocklist.  It's initial purpose is to allow the guids to be efficiently passed to a celery task for the database saving and logging, but it's potentially useful as a log for later inspection (or deleting/changing some of the Blocks).

At it's most basic we could just expose the guids in a text areas.  We could also generate a list of all the Blocks created with links to the relevant django admin change page.  

Potentially we could reimplement the custom `add_multiple_view` method as the `ModelAdmin` of the `MultiBlockSubmit` and get all the functionality from there.  (We should consider the work needed to implement all this extra functionality that hasn't been requested by Product nor by the end users of the tool and check whether any of it is actually going to be used)

**Comment by eviljeff** [comment]
The alternative suggested by @diox in https://github.com/mozilla/addons-server/pull/12926#issuecomment-557511632 was to just delete the instance after the celery task has completed, allowing admins to check when the submission was finished (i.e. all the objects saved; logging done; kinto updated with the blocks).

**Comment by eviljeff** [comment]
@jvillalobos any preference for if you want to keep a permanent record of the multiple-blocks submitted, or delete it once the individual blocks have been created?

**Comment by jvillalobos** [comment]
Keeping a log of multi-blocks could be useful, so that would be my preference. Having said that, I suppose it's also possible to query individual blocks that happened at/around the same time, and we'll also have blocklist bugs as backup records, so it's not something we absolutely _need_.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

When admins are blocking >1 guid, an entry will be created in the Multi block submits list. 
The list will summarize the blocking process in terms of version range, which GUIDs were blocked, which were not found and which were already blocked:
![image](https://user-images.githubusercontent.com/31961530/70129256-0ea03d80-1687-11ea-8872-8e47c5e56687.png)

The Multiblock view shows a text list of all the GUIDs blocked at a time, a link to the actual block change view.
