### ISSUE TITLE
Disco admin needs an additional hero image

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#12950]
We recently uploaded a number of new images to be used in the AMO homepage hero area. However one image we identified to include didn't make it into the admin. Can we please add the attached image? 

![hero_worldwideradio](https://user-images.githubusercontent.com/8496249/69447983-7b711a80-0d0c-11ea-8679-4f5814b5aebf.jpg)

**Comment by eviljeff** [comment]
Next scheduled push is now after US thanksgiving - December 5th.

**Comment by ioanarusiczki** [comment]
@eviljeff The image is available in admin tools dev in .jpg format. 

Size: 180KB

![Annotation 2019-12-05 141034](https://user-images.githubusercontent.com/33448286/70237550-256e8f00-1770-11ea-8dfc-32886fac7619.png)

Verified on dev with FF70(Win10).
