### ISSUE TITLE
Call scanner admin actions with POST

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12961]
We introduced per-object admin actions in the scanner results list. Actions are triggered with a simple link but that's a mistake. We should rather use a `<form>` with CSRF and a `POST` method.

---

For QA: scanner result actions should work as before (but if you look at the network panel in the devtools, `POST` requests should be issued instead of `GET` requests).

**Comment by AlexandraMoga** [comment]
Report actions for scanner results are still working as expected and POST requests are visible in the network panel for the following actions:
`POST /admin/models/scanners/scannerresult/5382/report-true-positive/`
`POST /admin/models/scanners/scannerresult/5382/revert-report/`
`POST /en-US/admin/models/scanners/scannerresult/5382/report-false-positive/`

@willdurand Just to double check, the github repository for reporting false positive results was mapped only for `yara`, right?
If I report a false positive for a `customs` result, the nginx server responds with a 502, but I suppose this error will go away once we map a repository for `customs` as well?

**Comment by willdurand** [comment]
> If I report a false positive for a `customs` result, the nginx server responds with a 502, but I suppose this error will go away once we map a repository for `customs` as well?

It should probably work with `customs` as well. 502 is a server error, not related to github.

**Comment by AlexandraMoga** [comment]
@willdurand I'm going to file a follow up issue in that case. I've just noticed that will also reproduce with  yara results with a  `match_all`  matched rule.
