### ISSUE TITLE
Repeated problems uploading new versions of extension to AMO

### ISSUE THREAD

**Issue by proginosko** [mozilla/addons-server#1296]
I'm repeatedly experiencing problems uploading new versions of my FF extension to AMO for review. When I upload the XPI file, it gets validated, but when I click the "Add Version" button nothing happens (or nothing appears to happen). When I click the "Add Version" button a second time, I get a message telling me that version has already been uploaded. Then when I go to view all versions, the status of the new version is listed as "0 files". When I click the delete icon for that version, AMO takes a very long time to respond. It eventually responds with a completely blank page; more often than not the version hasn't been deleted.

I was directed to file a bug report here by an AMO staffer when I posted to the Mozilla developer forum.

**Comment by darktrojan** [comment]
I've seen this before too. Usually when it happens, I find the upload succeeds but the uploaded file takes an age to appear on AMO.

**Comment by proginosko** [comment]
Thanks for the reply. You're right. I uploaded the XPI of the new version one more time. Again, it appeared as "0 files". But I left it for an hour or so, and now it says "Awaiting Full Review (1 file)". I guess I just need to be more patient in future! Still, it's not how things should go.

**Comment by darktrojan** [comment]
Also, if you fill out the version notes before the file appears, you lose the version notes when the file appears. Fun.

**Comment by EnTeQuAk** [comment]
We did have quite some performance issues in January which were solved which should have solved this one too, thus closing for now.

Feel free to reopen if there are any issues.
