### ISSUE TITLE
Optimize primary Hero images

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#12973]
The images that we were given are PNGs of photographs, so they are much heavier than they should be. Let's convert them to JPEG and optimize their size.

**Comment by jvillalobos** [comment]
Here's a new set provided by @aaronrbenson 

[Hero Image.zip](https://github.com/mozilla/addons-server/files/3892771/Hero.Image.zip)

Also, please make sure the image in https://github.com/mozilla/addons-server/issues/12950 is also optimized.

**Comment by muffinresearch** [comment]
Whilst the new Jpegs are better, they're still pretty heavy (see below file sizes as reported on disk by finder). I wonder if we could optimize further by using blur in places to remove detail so that we can get the sizes down further without resorting to too much lossy file-size reduction that might cause artifacts.

It could be interesting to test how much different 2x really makes for these photos? 

This will need discussion with the frontend team, but If we aren't currently conditionally serving smaller images to clients based on support, we might want to forgo serving 2x images to everything until we can conditionally choose a reasonable image size for the client from the frontend and support that via the API?

<img width="634" alt="Png vs Jpeg" src="https://user-images.githubusercontent.com/1514/69740738-c5edff00-1131-11ea-8b96-fb0cfe3f4593.png">

**Comment by eviljeff** [comment]
The images in the zip must have quite a low lossy setting applied - they're much smaller when I ran the pngs through a generic png-jpg process (that I guess used a middling setting)

**Comment by eviljeff** [comment]
![Privacy Badger@2x](https://user-images.githubusercontent.com/768592/69746508-53cee780-113c-11ea-99c5-bc20d677cd15.jpg)
![Search By Image@2x](https://user-images.githubusercontent.com/768592/69746509-53cee780-113c-11ea-8267-d8b17a17cda0.jpg)
![Sunset Window](https://user-images.githubusercontent.com/768592/69746510-54677e00-113c-11ea-8bea-f2430e211cd9.jpg)
![Tst1@2x](https://user-images.githubusercontent.com/768592/69746512-54677e00-113c-11ea-9bcd-427b4e6646c2.jpg)
![Typing Laptop@2x](https://user-images.githubusercontent.com/768592/69746513-55001480-113c-11ea-9be7-b7ed61c687ce.jpg)
![Ubo@2x](https://user-images.githubusercontent.com/768592/69746515-55001480-113c-11ea-854c-bfa8d5040e4b.jpg)
These are the slightly lossy jpgs in the PR i'm proposing instead:

![Adnauseum@2x](https://user-images.githubusercontent.com/768592/69746516-5598ab00-113c-11ea-88ce-0734df40f45b.jpg)
![Dark Reader 2@2x](https://user-images.githubusercontent.com/768592/69746518-5598ab00-113c-11ea-9542-0f46cb418efa.jpg)
![Enhancer@2x](https://user-images.githubusercontent.com/768592/69746519-56314180-113c-11ea-9e98-3f55d168bdeb.jpg)
![Facetainer@2x](https://user-images.githubusercontent.com/768592/69746520-56c9d800-113c-11ea-8ade-ed35e3e37acf.jpg)
![Gesturefy@2x](https://user-images.githubusercontent.com/768592/69746522-56c9d800-113c-11ea-91dc-c5e2b4f62993.jpg)
![Ghostery@2x](https://user-images.githubusercontent.com/768592/69746526-57626e80-113c-11ea-846b-5a58842a5e85.jpg)
![Google Translate@2x](https://user-images.githubusercontent.com/768592/69746527-57626e80-113c-11ea-8a3f-b42f122d62fe.jpg)

**Comment by aaronrbenson** [comment]
Looks good to me

**Comment by muffinresearch** [comment]
> The images in the zip must have quite a low lossy setting applied - they're much smaller when I ran the pngs through a generic png-jpg process (that I guess used a middling setting)

Those file-sizes in the PR are a huge improvement, what lib + settings were used?

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I checked this on dev with FF70(Win10) and the images have a .jpg version.  The old .png versions are still available (I can't tell if that should be kept or removed). 

- The Dark Reader and Privacy Badger image sizes correspond with the examples [ here](https://github.com/mozilla/addons-server/issues/12973#issuecomment-559185628)

![Annotation 2019-12-05 141034](https://user-images.githubusercontent.com/33448286/70234284-00c2e900-1769-11ea-90d1-af830336be57.png)

- I filed a followup here https://github.com/mozilla/addons-server/issues/13047

**Comment by ioanarusiczki** [comment]
@eviljeff Actually if they're of no use they can be removed. I filed a separate issue https://github.com/mozilla/addons-server/issues/13048
Verified on dev with FF70(Win10).

**Comment by eviljeff** [comment]
I had to leave the .png files in place or there would be a brief period during the deploy when the homepage would still be referencing the png files - before the migration runs - but the files would have been removed from the CDN.
