### ISSUE TITLE
Submitting version detail form often times out

### ISSUE THREAD

**Issue by darktrojan** [mozilla/addons-server#1297]
If I want to change the version notes or comments for reviewers, then submit the form, Firefox sits in the "Connecting…" state for a while then shows a blank page. Usually the changes are successfully committed though, so something is failing to return a response.

**Comment by kewisch** [comment]
This happens on various pages including editor pages, as you've seen the blank page is also mentioned on #1296.

**Comment by EnTeQuAk** [comment]
We did have quite some performance issues in January which were solved which should have solved this one too, thus closing for now.

Feel free to reopen if there are any issues.
