### ISSUE TITLE
The 'Clear Auto-Approval Extra Delay' button doesn't work

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#12976]
### Describe the problem and steps to reproduce it:
1. Log in to AMO stage with an Admin Reviewer
2. Open the review page of an add-on that has a Delay auto-approval flag from scanner rules - [see this example](https://reviewers.addons.allizom.org/en-US/reviewers/review/human-review-delay-indef-rule)
3. Scroll down to the More Actions section
4. Click on the Clear Auto-Approval Extra Delay button

### What happened?
Nothing happens
### What did you expect to happen?
The auto-approval delay flag is cleared 

### Anything else we should know?
- @diox I see you've implemented this option [here](https://github.com/mozilla/addons-server/pull/12807/files#diff-43509e5196f3976fa4aa5e7b8c32a7aa) but I only noticed it now
- The issue was reproduced on -dev and stage 
- I don't see any errors in the console 

![2019-11-27_10-11-49](https://user-images.githubusercontent.com/31961530/69705657-a689ae80-10fe-11ea-8b5f-f964c55d1e09.gif)

**Comment by diox** [comment]
Oops, I had changed the name of the field but didn't update the JavaScript...

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

The Clear Auto-Approval Extra Delay button is functional now => the scanner delay flag is removed. 
The 'Flags" section from the navigation sidebar will be updated after a page refresh. 

![clear delay flag](https://user-images.githubusercontent.com/31961530/69799063-3ac94380-11db-11ea-9e8e-1e774613aa5f.gif)
