### ISSUE TITLE
allow multiple blocks to be "edited"

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#12991]
@wagnerand mentioned on irc that he believes there will be a need in the future to bulk edit blocks.

The current multiple block submission process should work as a basis for this.  It needs:
- #12936 to be done so arbitrary max/min version values can be specified
- changes to overcome (or remove) the filtering out of Blocks that are already 0 - *.  The admin may want to reduce some blocks that are currently 0 - * to cover a smaller range.

One idea I had was that the form wouldn't save but redirect back (similar to how form errors cause the instances not to save) if the min/max versions were changed from 0 - *, with a revised list of guids that would be affected.  There might be better implementations.

**Comment by AlexandraMoga** [comment]
I've tested the multiblock submit tool on -dev and noticed the following flow.

The multiblock add has two stages:
- first, the range of GUIDs provided is analyzed to decide which should be a new block, an existing block or a an invalid selection
- the initial min-max version range is `0 - *`
*Note: if one of the selected GUIDs is already fully blocked, it will appear in the "Already blocked" list
- the min-max version range receives a custom input
- the form is saved => at this step your changes are saved but _no new block_ is created
*Note: any add-on that appeared in the "Already blocked" list for versions `0 - *` will be moved to the list of add-ons to be blocked
- the form is saved the second time => actual blocks are now created according to the provided values

[1st phase - the multiblock form before Saving]
![image](https://user-images.githubusercontent.com/31961530/70803159-11eca500-1dbc-11ea-9693-3b1501473581.png)

[2nd phase - the form after Saving the input values]
![image](https://user-images.githubusercontent.com/31961530/70803225-3c3e6280-1dbc-11ea-938e-fe4255287900.png)
