### ISSUE TITLE
Default "scanner results" list view should not show the entries without a version

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#12992]
We should not show the scanner results without versions attached by default in the admin list view because there is nothing an admin can do.

We can have a filter to "show everything" if we need.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The default scanner results list view will not include entries with no version attached.
These type of records can still be viewed if you select "All" in the "By presence of a version" filter.
