### ISSUE TITLE
Improve rule creation page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#12993]
For yara rules, the rule name should in the dedicated name field should match the name in the definition, so technically we wouldn't even need to write a name, we could just extract it from the definition. On the other hand, we need it for other scanners.

Hence, let's move the scanner selection to the top of the page, hide the name field by default and only unhide it if the selected scanner is not yara.

**Comment by ioanarusiczki** [comment]
@willdurand 
When a rule for the `Yara` scanner is created it has only the `description` field available where the name of the rule can be added. 
Customs and Wat have the `Name` field.
Works as [described](https://github.com/mozilla/addons-server/pull/13033) by the pull request. 
Verified on dev with FF70(Win10).
