### ISSUE TITLE
Unlisted versions can't be manually approved

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13008]
Prerequisites: Log in with a user with Review:Unlisted permissions

### Describe the problem and steps to reproduce it:
1. Submit a new unlisted add-on that matches a rule with a delay auto-approval action - this will prevent the add-on from being auto-approved 
2. Search for your add-on in the Unlisted Review queue
3. Open the review page of your add-on and approve the version by using the 'Confirm multiple versions' option 
4. Check the status of your add-on after confirming approval

### What happened?
The add-on status is Awaiting Review (Confirmed) - see [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/135c15504d6649caaf15)
### What did you expect to happen?
Reviewers should have an option to manually Approve unlisted add-ons
### Anything else we should know?
- by contrast, a listed version that has a delay auto-approval flag will include the manually 'Approve' option in reviewer actions, which will set the add-on status as approved - see [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/human-review-delay3)
- for unlisted versions, reviewers can force auto-approval by clearing the 'Delay auto-approval` flag but don't have the option to manually approve the version
- this scenario can be reproduce both on -dev and stage

**Comment by wagnerand** [comment]
@diox did we miss updating the status to `STATUS_APPROVED` here?

**Comment by diox** [comment]
Well confirming approval wasn't meant to approve, only... confirm.

**Comment by wagnerand** [comment]
Ah, right. So, list of versions to confirm should probably not contain the currently pending version. @AlexandraMoga can you confirm that's the case?

**Comment by AlexandraMoga** [comment]
@wagnerand if by "list of versions to confirm" you refer to the [Unlisted review queue](https://reviewers.addons-dev.allizom.org/en-US/reviewers/unlisted_queue/all), I can confirm that this list will also show entries that are still pending for auto-approval / Awaiting Review.

**Comment by wagnerand** [comment]
I'm referring to the list of versions on the review page that you can select from after choosing "Confirm approval".

**Comment by diox** [comment]
It currently does, actually. Mmmm this is annoying. It's the same list used for "Reject multiple versions" (soon to be "Block multiple versions" in https://github.com/mozilla/addons-server/issues/12978, but the problem might still apply then).

**Comment by AlexandraMoga** [comment]
> I'm referring to the list of versions on the review page that you can select from after choosing "Confirm approval".

Ah, yes, the pending versions appear in this list, as @diox also confirmed.

**Comment by wagnerand** [comment]
Thanks for confirming.

I think we can remove the pending versions from both lists, since:
* a pending version that is ok cannot be confirmed, only approved.
* a pending version that is not ok does not need to be blocked, since it has not been signed yet.

**Comment by diox** [comment]
Do we want to drop the pending versions from the reject multiple versions for listed as well ?

**Comment by wagnerand** [comment]
> Do we want to drop the pending versions from the reject multiple versions for listed as well ?

No. Rejecting a pending version is still a valid use case.

**Comment by diox** [comment]
So, to sum up for QA:
> Reviewers should have an option to manually Approve unlisted add-ons

Actually, it turns out that we don't need this. Now, I think the option to manually approve the latest unlisted version *is* available for add-ons with mixed versions, but that's not important or useful. 

What is going to change here is that versions still pending approval for some reason will be excluded from the actions that affect multiple versions, for unlisted review page only.

**Comment by AlexandraMoga** [comment]
Verified fixed on dev:

The list of versions to choose from when selecting Conform multiple versions or Reject multiple versions for _Unlisted_ add-on reviews doesn't contain the versions still pending for approval.

The Reject multiple versions list for a _Listed_ add-on review will also contain the versions that are still pending approval. 

This is an example of an unlisted add-on with a version pending for review. This version does not appear in the Confirm/Reject multiple versions list:
![image](https://user-images.githubusercontent.com/31961530/70444762-186cdb00-1aa3-11ea-90c5-aeaef0319822.png)
