### ISSUE TITLE
Fix permissions required to download source code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13006]
I've tweaked the permissions required to download source code in https://github.com/mozilla/addons-server/pull/12987 but I think it's still wrong / not what I intended.

The rules should be:
- If the add-on or version is deleted: admins only
- If the add-on or file is disabled: admins only
- Otherwise: admins and developers

The channel shouldn't matter. "admins" in this case are people with `Reviews:Admin`.

**Comment by wagnerand** [comment]
In any case, only admins should be allowed to access the source code package.

**Comment by diox** [comment]
Wait, not developers ? They have a link in the devhub version edit page.

**Comment by wagnerand** [comment]
Oh, you are right, sorry.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

Reviewers with `Reviews:Admin` permissions can download Source files attached to an add-on regardless of the add-on status: approved, disabled or deleted.
Regular reviewers will not see the Download sources link in the  version history.

Developers can also download the attached source code from the manage versions page if the add-on status is Approved or Disabled.
