### ISSUE TITLE
fix TestAddonSearchView intermittent

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13005]
```
____ TestAddonSearchView.test_prevent_too_complex_to_determinize_exception _____

src/olympia/addons/tests/test_views.py:1770: in test_prevent_too_complex_to_determinize_exception

    data = self.perform_search(self.url, {'q': query})

src/olympia/addons/tests/test_views.py:1021: in perform_search

    response = self.client.get(url, data, **headers)

.tox/es/lib/python3.6/site-packages/django/test/testcases.py:85: in __exit__

    '%d. %s' % (i, query['sql']) for i, query in enumerate(self.captured_queries, start=1)

E   AssertionError: 1 != 0 : 1 queries executed, 0 expected

E   Captured queries were:

E   1. SELECT `waffle_switch`.`id`, `waffle_switch`.`name`, `waffle_switch`.`active`, `waffle_switch`.`note`, `waffle_switch`.`created`, `waffle_switch`.`modified` FROM `waffle_switch` WHERE `waffle_switch`.`name` = 'api-recommendations-priority'
```

**Comment by diox** [comment]
We haven't quite figured out why this is happening - the waffle should be cached - but we can work around this by removing the `api-recommendations-priority` switch entirely. We're unlikely to ever turn it off anyway.

**Comment by diox** [comment]
QA: can't test the original intermittent unit test failure, but make sure recommended add-ons still take priority as normal in search results.

**Comment by ioanarusiczki** [comment]
@diox I verified on dev with FF73(Win10) - the see more links from the homepage, extensions/themes tabs and categories. 
The recommended add-ons take the [priority ](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-search-sort) as before.
