### ISSUE TITLE
fix TestBlockAdminAdd intermittent test fail

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13004]
```
_____________________ TestBlockAdminAdd.test_review_links ______________________

[gw0] linux -- Python 3.6.7 /home/travis/build/mozilla/addons-server/.tox/main/bin/python3

src/olympia/blocklist/tests/test_admin.py:179: in test_review_links

    assert 'Review Unlisted' in content, content
```

**Comment by mirefly** [comment]
I could not to reproduce this problem for the latest version d491d358ce. I just ran `docker-compose exec  web pytest src/olympia/blocklist/tests/test_admin.py::TestBlockAdminAdd` more than a dozen times, and did not see errors.

**Comment by eviljeff** [comment]
I just got in locally in `TestMultiBlockSubmitAdmin.test_review_links` (which is basically the same test) today, shortly before you commented.  But it's more difficult to replicate locally, sure.

I'm wondering if an object is being cached/reused in the `ModelAdmin` for multiple tests, though I have no ideas currently what that is.

**Comment by AlexandraMoga** [comment]
Please add a qa:not needed label to this issue.
Thanks
