### ISSUE TITLE
Git: disable checking for `.keep` files

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13019]
This is a follow-up once a new pygit/libgit release has been issued with **https://github.com/libgit2/pygit2/pull/908/ landed.

This might ease stress on EFS during extraction and followed commit.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Please be more specific about " git extraction works as before.", which part of the server is affected, more exactly what needs to be tested by qa. 
Thanks!

**Comment by ioanarusiczki** [comment]
@willdurand I verified on dev with several addon uploads - listed and unlisted and then checked that codemanager displayed the files. 
If there's anything else I could check on please let me know. 
Verified on dev with FF75(Win10).

**Comment by willdurand** [comment]
@ioanarusiczki thanks, I guess it should be okay then..
