### ISSUE TITLE
"Disable auto-approval" action for admins applies to unlisted versions as well

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13027]
### Describe the problem and steps to reproduce it:

We received a report from a developer that their unlisted update was not auto-approved. Upon further inspection, I noticed that auto-approval was disabled using the "Disable auto-approval" button available to admins. In the past, this did not apply to unlisted, but that seems to have changed recently.

Since there is a number of add-ons with disabled auto-approval meant for listed submissions (but not for unlisted), we need to revert that functionality so the button will apply to listed only, again.

Assuming STR (not tested myself):

1. As a developer, submit an unlisted version.
2. Wait for auto-approval (to ensure auto-approval works)
3. As a reviewer, go to the review page and press "Disable auto-approval".
4. As the developer submit an unlisted update.

### What happened?

The unlisted update is not auto-approved.

### What did you expect to happen?

As per the requirements above, the update should have been auto-approved, as the "Disable auto-approval" button should apply to listed only.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Verified on stage.

When an add-on  has a 'disable auto-approval' flag
- new listed versions won't be auto-approved
- new unlisted versions will be auto-approved

If auto-approval is delayed by a scanner flag, auto-approval is blocked both for listed and unlisted versions which triggered that specific flag.
