### ISSUE TITLE
Clicking on "Report false positive' for a customs scanner result will trigger a 502

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13037]
### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev with an admin account
2. Open the Scanner results list and filter to see only `customs` entries - see [link](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/?scanner__exact=1)
3. Click on the 'Report false positive' button for a result of your choice

### What happened?
You receive a 502 nginx error for `/admin/models/scanners/scannerresult/<result_id>/report-false-positive/` 
### What did you expect to happen?
No 502 error

### Anything else we should know?
- the actual False positive report is created in the scanner results list
- I've also reproduced the 502 error with `yara` results that had a `match_all` matched rule - see [link](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/?matched_rules__id__exact=28&scanner__exact=3)

**Comment by willdurand** [comment]
heh, sorry I totally missed this issue :x

**Comment by willdurand** [comment]
> I've also reproduced the 502 error with `yara` results that had a `match_all` matched rule - see [link](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/?matched_rules__id__exact=28&scanner__exact=3)

Yeah, I think that's not realistic so I will not fix this for now.
