### ISSUE TITLE
Add-ons Manager not always properly labeling Recommended extensions

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#13039]
I noticed that one of the extensions I have installed is not denoted as Recommended (by the trophy badge) in my Add-ons Manager. The extension in question is Webmail Ad Blocker (version 5.2.1). Is this an isolated case, or are other Recommended extensions not reflected accurately, as well? 

<img width="936" alt="Screen Shot 2019-12-04 at 10 22 47 AM" src="https://user-images.githubusercontent.com/8496249/70170263-342a4880-1681-11ea-8c76-d2a9d0f2e0c1.png">

**Comment by jvillalobos** [comment]
I gave the file a look and it has the Recommended flag. Also, I installed it in my release Firefox profile and I see the badge. This sounds like a bug in the Add-ons Manager, not AMO.

If you still see the problem, I suggest you don't try to fix it and instead [file an Add-ons Manager bug](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons+Manager) for it.
