### ISSUE TITLE
Add a test for image assets being too large

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#13035]
As a follow-up to https://github.com/mozilla/addons-server/issues/12973

We should consider if we can easily add a basic check to ensure that images that we add to AMO aren't over a certain size. 

We don't do this a lot on the server so if this is a lot of effort we might not do it, but if there's a quick win here we should.

**Comment by ioanarusiczki** [comment]
@eviljeff The images from https://github.com/mozilla/addons-server/issues/12973 (for the primary hero addons from admin tools) have less than 200KB. 
If there's anything else I should be checking please let me know.
