### ISSUE TITLE
Trigger content review on add-on metadata changes

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#13044]
We are experiencing issues where developers are waiting for their add-ons to be approved, but then later change the description to something malicious/spammy. As a mitigation we are considering to re-content review all changes to:
* add-on name
* add-on summary
* add-on description
* screenshots
* (possibly slug?)

Here are a few things I believe should be true:
* Subsequent changes made before the content review don't trigger anything special, they just keep the content review pending (this may be obvious)
* (Optional) Debounce changes. Developers may make a number of changes in quick succession, it may make sense to wait before putting it into the queue again, up to a maximum time.
* The queue should be sorted so that newly submitted add-ons that haven't been approved show up first
* We should be able to turn re-reviewing changes to content off and on, in case this blows up or we are short staffed.

We are yet unsure what the increase in volume of content reviews would be for this, it is difficult to determine this based on current logging. Finding add-ons that have changed their description after the fact are difficult to find though, and this would help us fight spam.

@wagnerand can you expand your thoughts and coordinate?

**Comment by jvillalobos** [comment]
> add-on description
> screenshots
> (possibly slug?)

How necessary are these for a first iteration? As far as I've seen, spammers are very easy to spot by just looking at the name and summary, particularly the Flash Player ones that I think triggered this request. Limiting the fields being monitored should reduce the review volume.

**Comment by wagnerand** [comment]
I agree with Jorge, for a first iteration, just name and summary could be enough to catch those spammers. However, I see description being important as well, more important than screenshots and slug.

Also, both this issue, as well as the code is public, so bad actors might move to fields we don't cover.

**Comment by wagnerand** [comment]
For the first iteration and the scope of this issue, let's do the following:

Any change to

* add-on name
* add-on summary

will put the listing back into _content-review pending_ mode.

If possible, add a waffle switch that allows turning that feature off/on dynamically.

We can do further optimizations in follow-up issues.

**Comment by AlexandraMoga** [comment]
@eviljeff I've added and enabled the `metadata-content-review` switch in admin and I've tried to edit the name and summary for some add-ons.

For all the attempts, the following request throws a 500 error and the edit add-on form remains in a loading state:
```
POST https://addons-dev.allizom.org/en-US/developers/addon/<addon_slug>/edit_describe/edit
```

Another interesting fact is that if you trigger a hard refresh on the edit add-on page to get rid of the continuously loading form, the new values entered for name and/or summary will be visible.

However, the content review list doesn't contain an entry for the updated add-on.

**Comment by bjherbison** [comment]
When do you expect this to go live?

The latest example I found:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/mouseless-jk-pro
7640 downloads, 728 daily users, 170 abuse reports, and harvesting user data.
(Block request filed.)

**Comment by eviljeff** [comment]
See the milestone - it's the expected date the change will deploy to production AMO.

**Comment by AlexandraMoga** [comment]
Re-opening because the expected flow doesn't seem to work - see https://github.com/mozilla/addons-server/issues/13044#issuecomment-571108831

**Comment by AlexandraMoga** [comment]
I've re-verified this on -dev and came up with the following results:

- content review is re-triggered on add-ons with changed metadata only when the `metadata-content-review` switch is enabled
- content review is re-triggered for name and/or summary changes in devhub

Some observations for @eviljeff and reviewers that are following this issue:
- an add-on also reappears in the content review queue when its metadata is edited in other locales. I'm not sure how much is this helping content reviewers, assuming that most of them are reviewing only the default locale. This means that, if some spammy content is introduced in a different locale, content reviewers might not be aware of it. 
- recommended add-ons don't go through the content review flow, so their metadata updates won't be highlighted here. On the other hand, there is only a low risk for recommended add-ons to introduce spammy content.

**Comment by bjherbison** [comment]
It was decided not to worry about problems that don't affect the local of the reviewer.
https://github.com/mozilla/addons-server/issues/11516

**Comment by eviljeff** [comment]
> This means that, if some spammy content is introduced in a different locale, content reviewers might not be aware of it.

it seems (to me) right that the content review should be triggered for all locales - whether that's shown in the reviewer tools is out of scope.  #11516 as mentioned would be the place for that (stalebot closed it)

>    recommended add-ons don't go through the content review flow, so their metadata updates won't be highlighted here. On the other hand, there is only a low risk for recommended add-ons to introduce spammy content.

Yeah I don't think the recommended addons are going to turn spammy.

**Comment by AlexandraMoga** [comment]
> it seems (to me) right that the content review should be triggered for all locales - whether that's shown in the reviewer tools is out of scope. #11516 as mentioned would be the place for that (stalebot closed it)

Yes. on that I agree. What I was trying to highlight is that, since we did not provide a simple way for content reviewers to check other locales, they wouldn't know where to start looking when a content review is re-triggered due to metadata being changed in another locale.
Hopefully #11516 can help in this regard.
