### ISSUE TITLE
[not bug] question about maximum amount of uploaded web-extensions per time.

### ISSUE THREAD

**Issue by eladkarako** [mozilla/addons-server#13052]
I'm getting <code>You have submitted too many uploads recently. Please try again after some time.
</code>,
and was wondering how much time I need to wait before I can continue upload again.

also, pointing me to the section in the source code (here) will be more helpful/useful 
thanks.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/blob/fd2e3b1d0054e1780186e04c5184855564d3f2c4/src/olympia/signing/views.py#L76:L97
