### ISSUE TITLE
Convert Makefile to something windows-friendly

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1305]
We have Docker now which means contributors can run Olympia on Windows. However, they can't run the Makefile commands to get started (`make initialize_docker`, `make update_docker`) so we should port it to something cross platform like regular Python.

**Comment by mstriemer** [comment]
There might be a way to get the Makefile working on Windows. It looks like you can compile them using something called MinGW (which it seemed like was being used by the developer who reported this, perhaps we just need to compile it).

I also saw something about using `automake` and `autoconf` but I have no experience with either of those.

**Comment by andymckay** [comment]
Is anyone going to do this though? Does run on Windows? Tempted to won't fix this.

**Comment by tofumatt** [comment]
Please don't. Windows contributors are awesome and we've had a lot of success helping them contribute on localForage. Make is pretty old and weird technology anyway and we certainly don't _need_ to use it.

**Comment by kumar303** [comment]
Since we have Docker now, which is supported by Windows, it would be a shame to leave Windows contributors in the dust simply because they can't run our Makefile.

However, I'm not sure it's true that Windows users can't run our Makefile. Does it actually break somehow? I see that there is [GnuMake](http://gnuwin32.sourceforge.net/packages/make.htm) for Windows which doesn't require a full runtime like [Cygwin](https://www.cygwin.com/).

**Comment by andymckay** [comment]
I used cygwin for ages on windows with no problem. If you look at most of the commands now they are just jumping you into the docker env anyway. https://github.com/mozilla/addons-server/pull/3003

My real concern is simple, without any Windows users, no-one will work on it and anything we do will bit rot.

**Comment by tofumatt** [comment]
Switching to something like a python or node task runner would mean we’d all still be using it, but then it’s more accessible to Windows users. If there’s an edge case (in my experience they are few if using node) and someone finds/fixes it yay. If not no harm done; there shouldn’t really be Windows-specific code as much as “code that runs anywhere”.

This sort of thing is always a bit chicken and egg—we won’t get casual windows contributors without allowing them easy access, and we don’t have any so there’s no demand…

That said, the current makefile is pretty lame anyway. Especially when we’re just calling to Make inside Docker (where it perhaps IS more appropriate, I care less there), we don’t need to be using such an exclusionary tool. Plus it’s kinda lame to work with. Doing stuff like passing arguments to Make is weeeeeird as we have it. Running individual files to test using Make that then passes args looks like this: `make test ARGS='src/olympia/files/tests/test_utils_.py’`

**Comment by andymckay** [comment]
If it something we all use, that's not make, I would be totally up for that.

**Comment by EnTeQuAk** [comment]
This should be a lot easier now that almost all our makefile commands hit docker anyway.

I'd vote to use http://click.pocoo.org/5/ to write a simple python file that does what our makefile does and with `subprocess.call` we can do pretty much everything we do right now with simple APIs and better extensibility. Maybe I can give it a go on a Friday afternoon :)

**Comment by EnTeQuAk** [comment]
I'm going to close this since this probably won't happen anytime soon and we are 100% docker-based and the commands needed to run are entirely based on `docker-compose` so I'd say our Makefile can be seen as "documentation how to run things".
