### ISSUE TITLE
False positive reports for customs should not contain the raw scanner results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13060]
See also: https://github.com/mozilla/addons-server/issues/13037

---

The customs payload is often too large to be embedded in the GitHub redirect URL so we should not expose it. (a redirect URL cannot have an infinite length, usually it is 2k chars)

**For QA:** reporting a false positive for a scanner result with scanner=customs should NOT lead to a (nginx) 502 (I think you will hit a 404 but on github.com).

In https://github.com/mozilla/addons-server/issues/13037, it was mentioned a similar with Yara when a rule generates lots of matches. That's not a realistic scenario so I will not fix this problem for now.

**Comment by AlexandraMoga** [comment]
@willdurand I've also noticed this issue and filed a report earlier this week in #13037 .
In my issue notes, I've mentioned that this will also reproduce when you report a false positive for a `yara` result that has a `match_all` matched rule.

**Comment by willdurand** [comment]
thanks.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

Reporting a false positive for customs will no longer result in a 502 error.
I'm seeing a 404 on the github repo instead, but that's expected since I don't have rights to access it.
