### ISSUE TITLE
Open appropriate review page from scanner results page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13070]
### Describe the problem and steps to reproduce it:

The scanner results page includes a link to the review page, which seems to always go to the listed review page.

### What did you expect to happen?

Since the scanner knows what version was matched, we could look up the channel for that version and use the exact link instead: If an unlisted version was matched, link to the unlisted review page, if a listed version was matched, link to the listed review page.

### Anything else we should know?

If we could also replace the version id label in that link by the version string, that would be more helpful.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on dev and stage with FF71(Win10). 
- the link when a listed add-on version  is clicked looks like: https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/customs-lang-pack
- the link when an unlisted version is clicked is https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/7e9baf8e5e7e4c84bb15

Let me know if the format is alright for the unlisted add-on. 
Thanks!

**Comment by willdurand** [comment]
> Let me know if the format is alright for the unlisted add-on.

yep, that looks good I think

**Comment by ioanarusiczki** [comment]
@willdurand I think that too as long as it redirects with no errors on the expected page.
Marking it verified with FF71(Win10).
