### ISSUE TITLE
Lower "hotness" requirement for themes

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#13088]
From @diox: "the 2 conditions to have a hotness score > 0 are: number of users > 1000 and gained at least one user in the past 3 weeks".

This works okay for extensions, but it doesn't work well for themes. I suggest we lower the requirement for themes to 250 users. [66 themes created this year](https://sql.telemetry.mozilla.org/queries/66902/source) meet that bar.

**Comment by diox** [comment]
untested patch for a brave soul to test:
```diff
diff --git a/src/olympia/addons/cron.py b/src/olympia/addons/cron.py
index ffe72e785c..a8dbe73c0c 100644
--- a/src/olympia/addons/cron.py
+++ b/src/olympia/addons/cron.py
@@ -188,8 +188,9 @@ def deliver_hotness():
             this, three = thisweek.get(addon.id, 0), threeweek.get(addon.id, 0)
 
             # Update the hotness score but only update hotness if necessary.
-            # We don't want to cause unnecessary re-indexes
-            if this > 1000 and three > 1:
+            # We don't want to cause unnecessary re-indexes.
+            threshold = 250 if addon.type == amo.ADDON_STATICTHEME else 1000
+            if this > threshold and three > 1:
                 hotness = (this - three) / float(three)
                 if addon.hotness != hotness:
                     addon.update(hotness=(this - three) / float(three))
```

Note that it only takes care of the first part of the condition. The second is important to keep so that "trending" is not just the same as "popular", but I don't know how many themes match that. Still, changing the number of users threshold is a good start.

**Comment by ragnarokatz** [comment]
@jvillalobos 
Hello, I would like to give this issue a try and am currently testing out the solution suggested by @diox. however, is there a way for me to see what the query returns from https://sql.telemetry.mozilla.org/queries/66902/source?

**Comment by jvillalobos** [comment]
@ragnarokatz No, those links are internal access only. All the query shows is how many themes created this year reached over 250 users (vs. 1,000 users, which I think is 0 themes).

**Comment by ragnarokatz** [comment]
@jvillalobos I see.
PR #13122 is ready for code review. However it seems that one of the CI environments is having trouble connecting to `apt.cache.travis-ci.com`, causing it to abort.
