### ISSUE TITLE
Block delete_selected action needs dual sign-off

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13086]
In `BlockAdmin.delete_queryset` we add some extra ActivityLog logging before the delete is carried out.  This is fine, but it's also quite expensive - for each Block delete there will be 3 activity log records, plus 1 extra for each version the addon has.  To fk link the ActivityLog instance with VersionLog and AddonLog there also needs to be a query on Addon, and a query on Version.

At a minimum we should preload `Block.addon` and `Block.addon_versions` so there isn't a separate query for each Block; potentially we should batch the processing in a celery task too.

We won't know how much of a problem this will be unless the blocklist is actually used.  After #12461 adds kinto integration moving the delete to a celery task might be necessary anyway.

**Comment by eviljeff** [comment]
repurposing this issue to add dual sign off at the same time because #13089 now requires it for deletions.

**Comment by AlexandraMoga** [comment]
Here are my results after having verified the multiblock delete feature and its integration with the sign off process on -dev:

- add-ons that went trough the dual sign-off process before being published to blocks will also require sign-off when their GUIDs are deleted as part of a multiblock deletion
- add-ons that didn't require sign-off will also be deleted without further approval
- a delete request Pending for sign-off will be listed as a Delete action in Block submissions
![image](https://user-images.githubusercontent.com/31961530/75255059-0836e300-57ea-11ea-8db9-458651e125ed.png)

This is the layout of the multiblock delete request, before saving:
![image](https://user-images.githubusercontent.com/31961530/75258035-8d23fb80-57ee-11ea-9fc2-6cde572c2a7f.png)

Individual block deletions will be verified when #13555 is fixed
