### ISSUE TITLE
Provide code-manager with information about minified files

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#13081]
This is in support of https://github.com/mozilla/addons-code-manager/issues/1086. Dealing with minified files in code manager is very slow, and it's been stated that, because users do not generally review minified files, we can handle them differently by truncating and/or not highlighting them, which will boost performance.

We do not currently have a way of identifying a file as minified in code manager, but @diox pointed out that the linter already creates data about minified files (via `unknownMinifiedFiles` in validation metadata), so perhaps we could use that as a staring point. Would it be possible to include this information in the `validation.json` file that is available to code manager?

My understanding is that the list of files in `unknownMinifiedFiles` will only include "unknown" files, but there could also be minified files from known libraries. I cannot recall if we are already doing something special for known libraries and/or if data about "known" files is already available, but it's something to consider if we want to be able to deal with all minified files.

As this relates to a fairly high priority issue in the queue for code manager, it might make sense to treat this as a high priority issue as well.

cc @wagnerand and @EnTeQuAk

**Comment by diox** [comment]
We could add a new `knownMinifiedFiles` property in the linter metadata and expose both. Since nothing about this is private (it's all done by the linter) it shouldn't be a problem to return that in validation results.

**Comment by bobsilverberg** [comment]
It sounds like we might want to just deal with this in code-manager itself. We are not specifically concerned with minified files, but rather with files that cause code-manager to be slow, so defining heuristics for that in the code manager itself makes sense.

**Comment by bobsilverberg** [comment]
I'm going to close this as it sounds like we won't need it and will deal with the issue in code-manager.
