### ISSUE TITLE
The user clicks the link in confirmation email that the automated test passed, will jump to an unknown URL.

### ISSUE THREAD

**Issue by xuyuehang** [mozilla/addons-server#13097]
https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/unlisted_to_reviewed_auto.ltxt

In this part, the {{ dev_versions_url }} in email received by the user is connected with the period. Users clicking on the link will jump to an unknown URL because this URL contains a period.

It is recommended to add a space between the {{ dev_versions_url }} and the period.

**Comment by jvillalobos** [comment]
Mentor: @eviljeff

**Comment by sauntheninja2** [comment]
Has this bug been fixed?

**Comment by eviljeff** [comment]
@sauntheninja2 no

**Comment by sauntheninja2** [comment]
How to recreate the bug?

**Comment by sauntheninja2** [comment]
I want to try solving it

**Comment by eviljeff** [comment]
go ahead.

**Comment by chenaaron3** [comment]
Am I overthinking this, or is the fix just changing "{{ dev_versions_url }}." to "{{ dev_versions_url }} ."?

**Comment by LissetCuevas** [comment]
Has this bug been fixed?

**Comment by eviljeff** [comment]
Yes, twice - see the github history above. @chenaaron3 created a commit but doesn't seem to have opened a PR to allow it to be merged; and @binjolaaman10 just opened a PR without commenting.

**Comment by eviljeff** [comment]
@binjolaaman10 if you comment here I can assign you to the issue.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this on dev and it looks fixed. When There's a space between the URL and the dot now. 

![space between url and dot](https://user-images.githubusercontent.com/33448286/73451014-47028600-436f-11ea-9a56-60cd46eb2145.png)

FF72(Win10)
