### ISSUE TITLE
Grandparent folder of deleted file is missing in file.entries returned from Compare API

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-server#13092]
### Describe the problem and steps to reproduce it:
Url: https://addons-dev.allizom.org/api/v5/reviewers/addon/7560/versions/1252898/compare_to/1688305/?lang=en-US
Method: GET
### What happened?
Response.file.entries lists entries in the folder called `chrome`, but does not include `chrome` folder itself.

![image](https://user-images.githubusercontent.com/4984681/70675849-9538ba00-1c47-11ea-81df-e5c2b57c110c.png)

### What did you expect to happen?

file.entries should include entry `chrome`. The file tree is expected to complete.

### Anything else we should know?
The folder `chrome` are entirely deleted in the new version in this case.

It looks like that we added the parent folder of the deleted file to mimic the original data structure, but did not add the grandparent path. 
https://github.com/mozilla/addons-server/blob/b2c6b7eaac6815daee682e9efbe8101ff40eca01/src/olympia/reviewers/serializers.py#L328

The web app code-manager throws an error when it find that the parent folder of any entries does not exist (https://github.com/mozilla/addons-code-manager/issues/1327).

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I verified with Postman on dev the request https://addons-dev.allizom.org/api/v4/reviewers/addon/7560/versions/1252898/compare_to/1688305/
I could see the `chrome` folder in the file tree being added in the response. 

![chrome in the file tree](https://user-images.githubusercontent.com/33448286/73274668-9b322c80-41ee-11ea-904d-7494ac214abb.gif)
