### ISSUE TITLE
update usage of `set_context` in DRF default/validator classes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13102]
see for a DRF change in 3.11: https://www.django-rest-framework.org/community/3.11-announcement/#validator-default-context  - the current behaviour will be deprecated in 3.12 and removed in 3.13.

At the time of writing we only use `set_context` in one place `ThisCollectionDefault` so it should be pretty easy change.

**Comment by ragnarokatz** [comment]
@eviljeff Hello, I would like to work on this issue please.

**Comment by ragnarokatz** [comment]
@eviljeff Hello, my pull request is ready for review. Please take a look at it when you have time, thanks.

**Comment by AlexandraMoga** [comment]
@eviljef is there any QA needed for this?

**Comment by eviljeff** [comment]
The code is used when adding addons to a collection via frontend, so just make sure that works okay (and I guess editing).
thanks.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
I haven't found regressions around collections.
