### ISSUE TITLE
Links to the Review Listed/Unlisted pages present on the change block view are opened on the internal domain

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13125]
### Describe the problem and steps to reproduce it:
1. Open the change block view of a blocked add-on - see [this example](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/889/change/)
2. Click on the 'Review Listed ' link 

### What happened?
The listed review page is opened on the internal domain - `https://addons-internal.dev.mozaws.net/en-US/reviewers/review/616887`

### What did you expect to happen?
The listed review page should be opened on the reviewers domain - `https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/view-page-archive-cache`

![image](https://user-images.githubusercontent.com/31961530/70987345-5b910480-20c8-11ea-8826-7cbbb6edc74b.png)

**Comment by eviljeff** [comment]
How is this handled on the other pages in the admin that link to the review page?  Do they link to the internal domain or the reviewers domain?

**Comment by AlexandraMoga** [comment]
In the scanners module, for example, links to the add-on review pages are opened on the reviewers domain.
This was specifically requested in https://github.com/mozilla/addons-server/issues/12942, therefore I considered it to be a good practice to apply it to the blocklist module as well.

**Comment by eviljeff** [comment]
Okay, I can copy the implementation from there

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

For [this add-on block](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/982/change/), the links to the add-on [listed](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/unlisted-web-ext-sign) and [unlisted](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/unlisted-web-ext-sign) review pages are now opening on the `/reviewers/` domain
