### ISSUE TITLE
A new version of a rejected add-on should have a 24-hour delay before being approved

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#13139]
An add-on where the previous version was rejected should be treated as suspicious and given the same 24 hour delay as an add-on with no previously published version.

Steps to reproduce:
1) Create an innocent add-on.
2) Wait for 24 hours.
3) Replace the add-on with malware.
4) Get rejected.
5) Upload a new version of malware

Actual:
5) The second version of malware is put on AMO within a few minutes.

Expected:
5) Delay publication so the presence of malware (or other serious reject-able problem) can be checked for before the add-on is available.

Two current problem add-ons:

https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/send-to-media-player
(Search "ucking" in js/iframe-access.js.)

https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/web-player-wrapper
(Look at the appropriately named keylog.js.)

A variation of this proposal was previously rejected in the simpler times of 2017:
https://github.com/mozilla/addons-server/issues/6545
Auto-approval should stand down if the last version was rejected by a human.

**Comment by jvillalobos** [comment]
I think this is worth having, but I also want to point out that after an add-on is identified as malware, it should be escalated to the admins so it is disabled and no new versions can be submitted.

**Comment by bjherbison** [comment]
Yes, I file block requests regularly, but it would be better to avoid the need for block requests and the chance of downloads.

An addendum to the request: Also put it back on the content review queue to increase the chance that the is a set of eyes on the add-on within the 24 hours. (The history of the add-on should explain why an add-on with "Content Approved" is back on the content review queue.)

**Comment by bjherbison** [comment]
This add-on keeps getting new versions. I've rejected three times, but there are a total of 298 downloads from the time it is up.
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/flash-control-online

**Comment by wagnerand** [comment]
I don't think this is part of content-review, nor do I think it should be. As Jorge mentioned, such actions should be escalated to admins. There is usually more to do than just rejecting. Escalating ensures all steps are taken.

**Comment by bjherbison** [comment]
Does the comment "I don't think this is part of content-review" apply to putting back on the content review queue, or does it apply to the proposed delay?

(As far as the scope of content review: It would be nice if it didn't have to be part of content review, but I've been rejecting malware for the past week and don't see rejections on those add-ons from anyone else. The block requests sat for over a week before there was action. But that is better discussed in some other forum.)

**Comment by wagnerand** [comment]
The steps to reproduce you mention would identify the malware by

* changes in the code:

That can be easy or hard to find, track down and analyze. Thus it is not part of content review (as code is generally not part of content review).

* changes in the listing:

This is very much part of content review. I believe #13044 is the right approach to it, which puts the add-on back into the content-review queue, as you suggested.

**Comment by wagnerand** [comment]
Closing in favor of #13044.
