### ISSUE TITLE
Hide matched rules in the scanner results admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13143]
It is currently possible to disable a rule, which actually means disabling the effect of the rule (in other words, the execution of the action that is bound to it).

In case a rule flags too many things (inaccurately), we'd like to be able to hide the results for this rule in the admin list.

**Comment by willdurand** [comment]
@diox @wagnerand thinking about this again, I guess using the `is_active` boolean attribute _could_ work here too. We could check `is_active` when binding rules to the scanner results so that:

1. a disabled rule won't be seen by default because the scanner result would have `has_matches=False`
2. a disable rule won't trigger an action (current behavior)

Implementing (1) would mean that a scanner result would not be associated to a disabled rule in the database. Given that we have all the code needed to do this anyway, we could theoretically rebuild the relationships between a result and the rules if needed.

Only disabling the effect of a rule could be done by using the "no action" action, if needed.

**Comment by diox** [comment]
I like that plan, yes.

**Comment by wagnerand** [comment]
Sounds good!

**Comment by AlexandraMoga** [comment]
I've submitted add-ons that should have matched rules both for `yara` and `customs` and I have the following results:

With all rules disabled:
- no matched rules are present in scanners results list
- no matched rules are listed in scanner details 
- no review actions attached to any of the rules are executed 

With one or more rules enabled for either `yara` or `customs`:
- matched rules are present in scanners results list
- matched rules are listed in scanner details 
- review actions attached to the matched rules are executed 


@willdurand I have the following sitation:
With all rules disabled, in scanner _details_, [customs](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/6068/change/?_changelist_filters=has_matched_rules%3Dall) and [wat](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/6069/change/?_changelist_filters=has_matched_rules%3Dall) will still have the 'Results' field populated, while for [yara](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/6067/change/?_changelist_filters=has_matched_rules%3Dall) this field is empty. In `customs` case, you can even see which rules were matched as `true`. I'm not sure if this was expected or not.

**Comment by willdurand** [comment]
> @willdurand I have the following sitation:
> With all rules disabled, in scanner _details_, [customs](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/6068/change/?_changelist_filters=has_matched_rules%3Dall) and [wat](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/6069/change/?_changelist_filters=has_matched_rules%3Dall) will still have the 'Results' field populated, while for [yara](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/6067/change/?_changelist_filters=has_matched_rules%3Dall) this field is empty. In `customs` case, you can even see which rules were matched as `true`. I'm not sure if this was expected or not.

ah right, that is expected but I forgot about it.
