### ISSUE TITLE
A changed add-on name should force a new content review and a 24 delay

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#13146]
The new version of an add-on changes the name should be treated as suspicious,  given the same 24 hour delay as an add-on with no previously published version, and be placed back in the content review queue.

If that version gets rejected the next version should also be delayed and put back on the content review queue. (That is already proposed in https://github.com/mozilla/addons-server/issues/13139 .)

I'd like to say "significant change" but that's hard to program.

A message should also be added to the add-on review history explaining why the add-on was placed in the content review queue.

Steps to reproduce:

1.    Create an innocent add-on.
2    Wait for 24 hours.
3.    Replace the add-on with malware and change the name to Adobe Flash Player.

Actual:
3. The malicious version of the add-on is immediately signed, approved, and made available as Adobe Flash Player. Then a block request needs to be created and handled.

Expected:
3. The old version of the add-on should still be available (under the old or new name it doesn't matter) and the new version shouldn't be signed and made available until someone has a chance to verify it isn't malicious.

All the instances I've discovered have used Adobe Flash Player as the name, but eventually they will realize I catch Flash Player and call it Avast or VPN or something else.

This is the most recent instance:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/flash-control-online
I filed a block request for this add-on a short time ago, and for two others yesterday evening.

**Comment by jvillalobos** [comment]
Already covered in https://github.com/mozilla/addons-server/issues/13044, but won't be pushed live until next year.
