### ISSUE TITLE
Expose the ML API results to the admins (at least)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13141]
Once we have #13331, we should expose the results from the ML API to the admins.

**Comment by willdurand** [comment]
@theone The ML API will return a confidence score (%). I am thinking about adding a new column in the list of scanner results first. Would you have ideas already about what you would like to do with this score? (_e.g._, triggering a rule depending on a threshold)

**Comment by willdurand** [comment]
> Once we have #13331, we should expose the results from the ML API to the admins.

@diox one nice side-effect of using a `ScannerResult` is that this issue is fixed already. Of course we could improve the UX but admins will have access to the ML results once we enable the task.

**Comment by diox** [comment]
Yeah. We could even have them be able to mark a ML result as true/false positive in the same way they do for the "regular" scanners (we'll need to customize the endpoints obviously).

**Comment by willdurand** [comment]
> @theone The ML API will return a confidence score (%). I am thinking about adding a new column in the list of scanner results as a first step. Would you have ideas about what you would like to do with this score already? (_e.g._, triggering a rule depending on a threshold)

Erf, sorry @wagnerand, I mixed your nicknames...

**Comment by willdurand** [comment]
This is actually fixed by itself. The `score` will be displayed as part of https://github.com/mozilla/addons-server/issues/13332.

**Comment by willdurand** [comment]
marking as qa: not needed for now because it cannot be verified (yet)
