### ISSUE TITLE
Add BuyMeACoffee.com to contributors domains

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/addons-server#13163]
See also:
https://github.com/mozilla/addons-server/issues/11680

Buy me a coffee is a nice alternative as it allows one time donation without account. Also money are transferred directly to your account.

Here comparison with Patreon:
https://www.buymeacoffee.com/patreon-alternative

Ever since I've add it to my extensions, people use it more often than PayPal. I guess it feels better to actually buy something for someone (even if it's virtual) rather than send them money directly.
My link:
https://www.buymeacoffee.com/fastaddons

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @EnTeQuAk

**Comment by abhinavraj23** [comment]
@caitmuenster I would like to work on this issue.

**Comment by caitmuenster** [comment]
Go for it, @abhinavraj23!

**Comment by preetmishra** [comment]
@caitmuenster @EnTeQuAk Can I work on this?

**Comment by abhinavraj23** [comment]
@preetmishra I am already working on it, will make the PR today
