### ISSUE TITLE
Stop autoapproval of known malware

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#13174]
Hundreds of copies of easily identifiable malware have been upload to AMO in the past year, and the malware has been installed by thousands of users.

Some automatic detection of these known problems could save hundreds of hours of reviewer time over a year and prevent the infection of many users.

Steps to reproduce:

1. Upload JavaScript malware to AMO.
2. Have the malware rejected, blocked, and the author account banned.
3. Repeat steps 1 and 2 dozens of times with little or no variation.
4. Repeat steps 1 and 2 hundreds of times with little or no variation.

Expected result:
4. With help from reviewers the automated system stops auto-approving the malware.

Actual result:
4. Auto-approval keeps happening.

Proposed solution:

- Maintain a private list of file names and strings found in common malware which haven't been found in any non-malicious add-on.
- When one of the file names or strings is found auto-approval is disabled for the add-on.
- Reviewers are shown the reason auto-approval is disabled and are told who to contact if the action was inappropriate. ("String 'XYZZY' found a line 123 of pseudo.js")

Nice-to-have features:
- The ability to update the list of file names and strings at times other than a software update.
- The ability to update the list of file names and strings without restarting the service.
- Automatic logging of any approval of a suspect add-on.
- The ability to generate reports of the number of times add-ons were found with each file name or string is found over time periods and the number times those add-ons were approved.
- A check box in the UI to automatically notify administrators if an add-on was caught inappropriately.

I have a proposed list of strings and file names, but I don't want to list them here for obvious reasons.

**Comment by caitmuenster** [comment]
Thanks BJ! We'll keep this in mind as we continue to work on improving ecosystem security. (For security reasons we generally don't discuss those security measures on public repos.)
