### ISSUE TITLE
HIde "Block" button on reviewer page until new blocklisting flow has been finished

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13179]
Let's hide the "Block" button on the review page until the backend part (talking to kinto...) has been implemented.

**Comment by eviljeff** [comment]
So you're asking for https://github.com/mozilla/addons-server/issues/12457 to be reverted?
and https://github.com/mozilla/addons-server/issues/12978 too?

Given the small number of admin reviewers isn't just ignoring the button a feasible alternative?

**Comment by wagnerand** [comment]
This came up because an admin was wondering about that button. But we can probably deal with this by sending an email do admins.
