### ISSUE TITLE
Dockerfile build fails to add Geolite2 database dependency

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#13181]
This line is failing as it seems the URL is not resolving correctly.

https://github.com/mozilla/addons-server/blob/master/Dockerfile#L59

The integration tests on addons-frontend depend on this Dockerfile being built. https://circleci.com/gh/mozilla/addons-frontend/18914

**Comment by eviljeff** [comment]
I guess it's because of https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by eviljeff** [comment]
@diox because I believe this was added for #10720

**Comment by eviljeff** [comment]
The same line isn't in `Dockerfile.deploy` so I don't think it will block dev/stage/prod deployments (though I can't see how the geo db is made available in those environments)

**Comment by diox** [comment]
In dev/stage/prod it's being copied from a special ops repo using a private ansible rule.

**Comment by jrbenny35** [comment]
Is there a fix for this planned? Looks like some extra steps need to happen as far as getting a key and whatnot

**Comment by diox** [comment]
We could replace it by a dummy database. We don't really need a real one for our dev envs.

**Comment by AlexandraMoga** [comment]
Please add a qa:not needed label to this issue.
Thanks
