### ISSUE TITLE
Disable files when we disable an add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13194]
Follow-up of #13185.

There are cases when add-ons (and all their files) need to get disabled. One example is when blocking add-ons, but there have been cases of add-ons having the get disabled without blocking them.

Please add a "Disable all" button to the page that changes the add-on status and the file status of all files to `STATUS_DISABLED`.

---

**Update (for QA):** we changed the behavior of the "force disable" button to disable the add-ons as well as the files (see https://github.com/mozilla/addons-server/issues/13194#issuecomment-599491696 for more details)

**Comment by eviljeff** [comment]
@diox seemed to think this functionality belongs more in the reviewer tools, like the other admin disable action.

**Comment by wagnerand** [comment]
We can do that too, as long as we gate it by some admin permission (tbd).

**Comment by diox** [comment]
I don't mind tbh ; I was just noting that we already have a "Force disable" action, that only disables the add-on (not the files) and it lives in reviewer tools.

The nice thing about having it in the django admin it that it would be under VPN.

**Comment by willdurand** [comment]
> I don't mind tbh ; I was just noting that we already have a "Force disable" action, that only disables the add-on (not the files) and it lives in reviewer tools.

So if the "force disable" does not disable the files, how should be name the button to disable the add-on + its files then? I am thinking about adding it to the django admin, next to the "force disable" one. WDYT?

/cc @wagnerand

**Comment by diox** [comment]
So, for posterity:
- We already move the files belonging to a disabled add-on to the guarded location on filesystem, and check the add-on state in all relevant code (devhub, update service, download views)
- The reason Admins need the files to be disabled in database is for consistency, that helps with raw SQL queries.
- @wagnerand confirmed that it was ok to lose the original `status` when doing this. It makes reversing a completely manual operation that has to be performed using the django admin.
- We already have a `<Addon>.force_disable()` method so we can add `File.objects.filter(version__addon=self).update(status=amo.STATUS_DISABLED)` inside. As mentioned above we already move the files on filesystem, through a `on_change` signal handler.

**Comment by willdurand** [comment]
I updated the issue to reflect what we are going to do (explained in the comment above)

**Comment by ioanarusiczki** [comment]
@willdurand @wagnerand 
I force-disabled an add-on from the review page https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/anonymox
Admin tools shows all files as being disabled here https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/325576/change/ and also here https://addons-internal.dev.mozaws.net/en-US/admin/addon/manage/anonymox/ 

I tested this using an admin account. If I must test anything else and try it with other user than admin please let me know.

**Comment by wagnerand** [comment]
@ioanarusiczki Looks good, thanks!
