### ISSUE TITLE
Add link to review page on django add-on admin page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13199]
Admins quite often need to go to the review page from a django admin add-on page they reached using a certain use case we have. Could we please add a link to the review page (listed is fine for now) to `admin/models/addons/addon/<ID/change`?

**Comment by gabbyprecious** [comment]
Is anyone working on this, can I jump on it?

**Comment by diox** [comment]
You can, if you're familiar with how the django admin works. Our install docs are over there: https://addons-server.readthedocs.io/en/latest/topics/install/index.html

I was thinking the link would be at the top of the add-on admin change page, next to the "History" and "View on site" links. For this, you need to have a [custom `change_form.html` template](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#overriding-vs-replacing-an-admin-template) for the `addon` model inheriting from the django one, and add the link as a `<li>` in the `object-tools-items` block. The link will probably be something like `{% url reviewers.review object_id %}`.

**Comment by willdurand** [comment]
@wagnerand you wrote "listed is fine for now"–would it make sense to have 2 links instead? Maybe we could be smart and only show 2 links if there are both listed and unlisted versions (if possible)

**Comment by wagnerand** [comment]
@willdurand Yes, it would be great to show 2 links *if* there are both listed and unlisted add-ons. We should only show links to channels that we have versions for.

If we cannot determine that, it might make sense to show 2 links by default. Just keep in mind that reviewers would probably open the two links all the time, since it's cheaper to just CMD+Click on 2 links and the close one, than to click on one, realize there are no versions for that channel, go back and click the other link.

**Comment by willdurand** [comment]
@willdurand Yes, it would be great to show 2 links if there are both listed and unlisted add-ons. We should only show links to channels that we have versions for.

Cool!

> On the other hand, the review pag contains a link to the other channel if it exists, so a reviewer might not even go back and click the other link. Maybe you could reuse the code from the reviewer page for determining whether there are listed/unlisted versions?

Good idea, thanks for the tip!

**Comment by diox** [comment]
FYI there are `has_unlisted_versions() and `has_listed_versions()` helpers on the `Addon` instances. Do pass `include_deleted=True` argument in both cases.

**Comment by ioanarusiczki** [comment]
@willdurand I can navigate from en-US/admin/models/addons/addon/1002608/change/ to both: listed and unlisted review pages.

I filed an issue here https://github.com/mozilla/addons-server/issues/13778

verified on stage with FF74(Win10).
