### ISSUE TITLE
implement dual sign off for adding single guid/block

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13202]
Currently single add-on add block are created immediately.  For dual-sign (#13089) off to work we need to defer the creation of the block to after sign-off.  Most likely we can do this by reusing the Multi-block action (hopefully).

**Comment by AlexandraMoga** [comment]
@eviljeff while verifying this issue I've noticed that the ADU rule implemented for multiblock submissions doesn't apply to single guid blocks. Was this condition required only for multiblocks?

**Comment by eviljeff** [comment]
@AlexandraMoga doesn't apply as in all single guid block submissions require dual sign off or none of them do?  In either case, that's not an intended implementation detail - adding a single guid should be treated the same as adding many.

**Comment by AlexandraMoga** [comment]
@eviljeff all single guids require dual sign off right now. I've tested with listed add-ons that had 0 ADU and they ended up pending for sign off.

**Comment by eviljeff** [comment]
0 ADU requires sign-off too (because unlisted)

> any ID without stats should required dual sign-off"

from https://github.com/mozilla/addons-server/issues/13089

**Comment by AlexandraMoga** [comment]
@eviljeff So the condition for a a _listed_ add-on to be published to blocks directly is to have between >=1 and <100k users. I thought that we are processing stats for all listed add-ons regardless of the number of users, so even add-ons with 0 ADU. This is why in my previous comments I've expected to see those add-ons published to blocks.

**Comment by eviljeff** [comment]
That was a direct quote from https://github.com/mozilla/addons-server/issues/13089#issuecomment-572233744 - it wasn't conditional on the addon having unlisted versions.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev.
Single add-on blocks are going through the dual sign off process. Add-ons with >100k users or add-ons without stats (unlisted or listed with 0 users) will be Pending for Approval/Rejection. Add-ons with 1 to 100k users will be Published to Blocks directly.
