### ISSUE TITLE
Add models & tasks to run arbitrary yara rules on existing versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13205]
We want to allow searching for code patterns on existing add-ons from the admin. The idea is to use our scanners models & tasks to do this, and yara in particular.

To do this, first we need to refactor the existing models & tasks to be able to run an arbitrary rule on a `Version` (and not just a `FileUpload`) without polluting current results.

**Comment by AlexandraMoga** [comment]
@diox is there anything I could test at this point other than looking for regressions in scanner results and rules matching?

**Comment by diox** [comment]
@AlexandraMoga nothing else right now

**Comment by AlexandraMoga** [comment]
I did not find regressions on scanners functionalities. 
I'm marking the issue as verified fixed on -dev.
