### ISSUE TITLE
Add admin UI to view scanner results for arbitrary queries

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13206]
Once #13205 is done, we'll want to be able to display the results of the arbitrary yara queries separately from the automated scanner results that happen at upload time.

**Comment by wagnerand** [comment]
The admin UI should show the author(s), add-on GUID, version number, version channel, matched file(s) and matched line(s), with as many hits per page as performance allows.

Ideally, we would group those hits by add-on id/GUID, version channel, version id, matched file.

**Comment by diox** [comment]
We also discussed the fact that the actions (mark as true positive/false positive/unknown) aren't that useful:
- They are stored on `ScannerQueryResult` instances, which are *not* fed to machine learning (only `ScannerResult` are)
- Even if they were, the rules are arbitrary and not necessarily equivalent to submission rules

I'll probably remove them as part of this issue - that'll leave more space in the UI for other things we want to display.
