### ISSUE TITLE
Add counts per matched rule (statsd)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13215]
In order to have some statistics about the different rules, let's use `statsd` to count the number of time a rule matches. We will use the rule `id` as key.

**For QA:** this will affect both Yara and customs (and the other scanners) but there should be no impact on the submission or the results of the scanners in the admin (i.e. it should work as before).

**Comment by ioanarusiczki** [comment]
@willdurand I verified this issue on dev with FF72(Win10). 

Admin tools scanner results:
- all 3 scanners registered the uploads for listed and unlisted addons. 
- the matched rules are registered for yara and customs and the Actions (Report as false or true) are available next to these results.
