### ISSUE TITLE
Develper account blocking by mail is not fixable

### ISSUE THREAD

**Issue by rugk** [mozilla/addons-server#13223]
### Describe the problem and steps to reproduce it:
I used a forward-mail that is unique for AMO and apparently got blocked from uploading add-ons (and even updates!) for that reason.

Details: https://social.wiuwiu.de/@rugk/103262103418577981

### What happened?

1. I can click "publish update".
2. Then I need to accept privacy terms and end-user-agreement and pass a ReCaptcha.
3. Only (afterwards) I get the message that I am blocked, linking to https://extensionworkshop.com/documentation/publish/developer-accounts/
4. When I add a secondary mail to my Firefox account (because I literally cannot change the primary mail :roll_eyes:), and verify that this does not change anything.

### What did you expect to happen?

1. You can tell me that I am blocked _before_ I need to pass this Captcha.
2. I should be able to fix that error myself by changing my mail or by accepting this secondary mail of the FF accounts as a good one.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Your admins also do not reply for one week to the mail that is provided at that address.
So this whole thing is not solved.

Really this can be serious if there are security vulnerabilities in your add-on. Also AMO reviewers asked me to publish a new version – again a thing I cannot do.

**Comment by eviljeff** [comment]
according to @kewisch this was dealt with via amo-admins@mozilla.com a few weeks back

**Comment by rugk** [comment]
Well… yes, this _one_ issue, but I've still noticed a few technical issues that may be addressed:
> You can tell me that I am blocked before I need to pass this Captcha.

(I could actually solve the other one, but this one may still be addressed)

**Comment by diox** [comment]
I'm sorry you got caught in this, but this is done by design, to force bad actors to go through the captcha before they can know they are being blocked.
