### ISSUE TITLE
Add a new table for daily stats from airflow

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#13225]
To enable daily stats for each add-on to be entered into the AMO db we need to add a new table.

There's a separate ticket related to ops setting up the necessary access to that table [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1604849). Once this table is added please update the bugzilla bug.

**Comment by eviljeff** [comment]
Is this going to be broken down any further than addon (to version, etc)?  And is it an addon+day+users tuple every day or updating a addon+average_users pair?  (The latter would be what we currently have on `Addon` and, iirc, this was going to replace; the former would be needed for AMO to generate trending/hotness values)

**Comment by muffinresearch** [comment]
@eviljeff That's a good question, are there any details of how hotness and trending are actually calculated? 

I wonder how much usage hotness and trending get and if there's an opportunity to simplify things further? It's not clear to me what the precise differences are.

/cc @diox

**Comment by eviljeff** [comment]
hotness is calculated as
```
    a = avg(users this week)
    b = avg(users three weeks before this week)
    threshold = 250 if addon type is theme, else 1000
    hotness = (a-b) / b if a > threshold and b > 1 else 0
```
from https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/cron.py#L165-L203

**Comment by eviljeff** [comment]
Hotness is what we call trending in the codebase (because some obscure historial reason probably).  It's used on the second level of the homepage (e.g. https://addons.mozilla.org/firefox/extensions/) in the trending block.

**Comment by EnTeQuAk** [comment]
Mentioning https://bugzilla.mozilla.org/show_bug.cgi?id=1604849#c7 here, we're trying to pursue toe path of pulling data from bigquery for all the stuff we need instead of them pushing data to us.

I'll close this particular issue but will put some notes into the bugzilla bug when it makes sense and when we're talking more about the data. Thanks y'all
