### ISSUE TITLE
Keep the view filters applied when triaging a scanner result

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13221]
### Describe the problem and steps to reproduce it:

The view filters are dropped when triaging a scanner result.

STR:
1. Go the scanner results page.
2. Apply some view filters on the right hand side
3. Click on "Mark as true positive"

### What happened?

The view filter is dropped.

### What did you expect to happen?

The view filter stays active.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by willdurand** [comment]
@theone do you often use these action buttons in a scanner result "detail" page? (at the bottom of the page). I am thinking about reusing the previous/current URL in the redirect.

**Comment by wagnerand** [comment]
I use them regularly. Do you mean if I click on one of the buttons on the detail page, I just get back to the detail page? That sounds fine to me!

**Comment by AlexandraMoga** [comment]
I've verified the filter behavior from admin scanner results on -dev and I have the following results:

- for the list view: the custom filters are preserved after a Report as false positive or Mark as true positive action
- for the detail view: 
  - when Marking as true positive, the user remains on the detail view once the page is refreshed
  - when Reporting as false positive the user is redirected to the default scanner results list view, i.e. if the user had some custom filters set, they are not preserved

@willdurand I can file a follow up for the last scenario. Depending on the amount of work involved, we can decide if it is worth fixing or not.

**Comment by willdurand** [comment]
>     * when Reporting as false positive the user is redirected to the default scanner results list view, i.e. if the user had some custom filters set, they are not preserved

oops.



> @willdurand I can file a follow up for the last scenario. Depending on the amount of work involved, we can decide if it is worth fixing or not.

yes, please
