### ISSUE TITLE
Update pygit2 to 1.0.2

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13242]
There has been a few new releases looking at https://github.com/libgit2/pygit2/blob/master/CHANGELOG.rst - I don't quite know why that hasn't been handled by pyup.

At least the 1.0.0 release may need some rework of our code according to changelog but I haven't spend much time on that yet.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Please add some STR for qa. 
Thanks!
