### ISSUE TITLE
Wrong URL to the file viewer in the scanners admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13248]
The links pointing to the files matched by the rules in the scanners admin are not absolute and they are not correct in the hosted envs (-dev, etc.). The links should open the (old) file viewer.

Edit: looks like the ID is not correct either..

**Comment by AlexandraMoga** [comment]
This was verified in https://github.com/mozilla/addons-server/issues/13220#issuecomment-574633703 both on -dev and stage.
