### ISSUE TITLE
Broken pagination style in admin add-on Files section

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13250]
Follow up for #8410 

### Describe the problem and steps to reproduce it:
1. Load an admin add-on page that has many files - see https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/1865/change/
2. Scroll down to the Files section and notice the pagination style

### What happened?
The pagination has an unusual style

### What did you expect to happen?
Pagination links should be displayed inline 

![image](https://user-images.githubusercontent.com/31961530/72341010-e9fda380-36d1-11ea-8222-ec74bc5f2560.png)

**Comment by Shivansh2407** [comment]
Can I help on this issue?

**Comment by eviljeff** [comment]
@Shivansh2407 if you'd like to, but it's not particularly trivial to fix.  First you'll need to get addons-server running locally and then navigate to one of the Addon admin pages there http://olympia.dev/admin/models/addons/ to see it.  I think it just needs the appropriate css rules adding, but you'd need to create the css file and add it to the AddonAdmin class too.

**Comment by AlexandraMoga** [comment]
Verified fixed:
![image](https://user-images.githubusercontent.com/31961530/85280735-63739c00-b491-11ea-90c0-7e6744be62c9.png)
