### ISSUE TITLE
Add task to run a yara rule on all versions in database

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13256]
Follow-up to https://github.com/mozilla/addons-server/issues/13205, we need to implement a task that runs the task for a query rule on all existing versions that we might be interested in.

The default criteria, hardcoded for now, will be:
- Must belong to a webextension (and not be a static theme, only extensions are considered)
- The add-on must not have been disabled by Mozilla
- The version needs either to be unlisted or be the currently public listed version of the addon it belongs to

**Comment by AlexandraMoga** [comment]
Note: this will be verified on stage after the task run is completed. Test data relevant for the scenarios we'd like to cover has been prepared.

**Comment by AlexandraMoga** [comment]
This issue has been verified on stage by applying the following method:

1. target some specific `yara` rules then submit various add-ons that would match them
2. create a `yara` scanner query rule expected to identify the add-ons submitted in the previous step
3. run the scanner query rule and verify the scanner query results that matched the rule

**Results** - add-ons that met the following conditions were identified by the scanner query rule:
- latest public version of a _listed_ add-on (disabled and deleted add-ons/versions were excluded)
- all _unlisted_ add-ons/add-on versions, including disabled and deleted ones
- non-extensions (i.e static themes, dictionaries, lang packs) were excluded

@diox please have a look at the results mentioned above and let me know if they also match your expectations.
