### ISSUE TITLE
Add specific permissions for code search admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13268]
Currently the django admin for code search (Scanner Query Rule and Result) don't have explicit permissions set up so they are only accessible by super admins. Dedicated permissions would add flexibility.

**Comment by wagnerand** [comment]
Lets start with the following permissions (naming up to you):

1) Create, modify, delete a code-search rule. Start, stop a search.

2) View the search results.

Does the system allow to remove the search results but keep the rule?

**Comment by diox** [comment]
> Does the system allow to remove the search results but keep the rule?

My plan was to not allow for anything on results beside mark as true/false positive, like the regular scanner results, but this can be changed depending on your needs.

**Comment by wagnerand** [comment]
That should be ok, I was just curious.

**Comment by diox** [comment]
I think the permission to view results should also let you view the rules, so that you can navigate back and forth (but without changing anything). Typical use-case: me looking if a query is done :)

**Comment by diox** [comment]
Made `Admins:ScannersQueryView` and `Admins:ScannersQueryEdit`. As the name implies, having just the former should give you read-only access, the later read-write access (through results should still be read-only in any case)

**Comment by AlexandraMoga** [comment]
I've verified the new scanner query rules permissions and I have the following results:
- users with `Admin:ScannersQueryView ` can view the scanner query results list and details and the scanner query rules and details; they cannot add, edit or delete rules; they don't have access to Actions in scanner query results
-  `Admin:ScannersQueryEdit ` have view and edit access to the scanner query results list and details; they have access to Actions; they can view, run and abort a scanner query rule; they can add, edit and delete scanner query rules

I've found two issues for which I filed follow-ups.
