### ISSUE TITLE
File IDs from the admin add-on page should be linked to their corresponding files 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13262]
Follow up for https://github.com/mozilla/addons-server/issues/8410#issuecomment-574156664

### Describe the problem and steps to reproduce it:
1. Open an admin add-on page - see https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/1865/change/
2. Scroll down to the Files section
3. Notice the File Id present for each individual file

### What happened?
The Id is not linked to any resource

### What did you expect to happen?
File Ids should be linked to their corresponding files in the old file viewer, if we want to keep the same implementation used in the old manage add-on page. Another more permanent option would be to link File Ids to the admin File management tool, in the idea that the old file viewer will be deprecated at some point. 

![image](https://user-images.githubusercontent.com/31961530/72415998-664dc080-377e-11ea-9c11-20bc69d14677.png)

**Comment by eviljeff** [comment]
@wagnerand wontfix or what do you want them linked to?

**Comment by wagnerand** [comment]
Let's wontfix for now, and revisit later. Down the line we might want to link to the code manager once all files have been extracted.
