### ISSUE TITLE
Reviewers API returns a 500 error in dev

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-server#13260]
### Describe the problem and steps to reproduce it:
In local dev environment [Addons-code-manager](https://github.com/mozilla/addons-code-manager), I received 500 error from 
http://localhost:3000/api/v5/reviewers/addon/494431/versions/1532144/?lang=en-US
and http://localhost:3000/api/v5/reviewers/addon/502955/versions/1541794/compare_to/1541798/?lang=en-US

### Anything else we should know?
I guess API host should be `https://addons-dev.allizom.org`
It was working well yesterday.
It seems to blocks dev Addons-code-manager completely..

**Comment by bobsilverberg** [comment]
It looks like this is showing up in Sentry as https://sentry.prod.mozaws.net/operations/olympia-dev/issues/7077466/?query=is:unresolved, and @wagnerand pointed out that it seems to be related to the landing of https://github.com/mozilla/addons-server/issues/13236

Paging @EnTeQuAk

**Comment by bobsilverberg** [comment]
Looks like it's https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/serializers.py#L113, which needs to use `cache.get_or_set` instead of `cache_get_or_set`. This seems simple enough that I can try to fix it. 

I wonder why no tests caught this?

**Comment by bobsilverberg** [comment]
Hmm, it seems like a test did fail for the commit: https://travis-ci.org/mozilla/addons-server/jobs/636978133?utm_medium=notification&utm_source=github_status, but not for the PR. Perhaps that was just unfortunate timing?

**Comment by mirefly** [comment]
Thanks @bobsilverberg. But I still got 500 errors (the same as before)...

**Comment by diox** [comment]
Looks like dev deploy failed for that commit. We're on it.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- On AMO dev I tested the [Reviewers API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#) with Postman and they all worked for me. 
- I can access code-manage files too. 

I'll let @mirefly to confirm for the local dev environment.

**Comment by mirefly** [comment]
@ioanarusiczki  I confirmed it was fixed for the local dev.
