### ISSUE TITLE
Restrict available actions for results in code search admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13269]
Currently it's possible to add/edit/remove query results but we probably don't want any of that.

**Comment by diox** [comment]
Done as part of https://github.com/mozilla/addons-server/pull/13367

**Comment by AlexandraMoga** [comment]
I've logged in with a super admin and there is no way to add, change or delete a scanner query result. 
The only available actions are marking as True Positive, False Positive or Inconclusive.
