### ISSUE TITLE
Reviewers API responds with a 500 error when trying to view a file with blank spaces in its name

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13272]
### Describe the problem and steps to reproduce it:
1. Send the following request to the reviewers/browse API:
```
https://addons-dev.allizom.org/api/v5/reviewers/addon/618629/versions/1690063/?file=content script.js
```

### What happened?
The API responds with a 500 server error because the file name contains a blank space

### What did you expect to happen?
No server error

### Anything else we should know?
- the issue is also reproducible for the compare API and will completely prevent the compare page from loading in code-manager:

https://code.addons-dev.allizom.org/en-US/compare/618629/versions/1690062...1690063/

Update: - the issue can also happen if a folder name contains spaces - see [example](https://code.addons-dev.allizom.org/en-US/browse/618821/versions/1690254/?path=more%20rules%2Fmore%20more%20rules%2Fmore%283%29%20rules%2Fcoinhive.js)

**Comment by diox** [comment]
Assigning to @EnTeQuAk for double-checking but the issue might be on the client side if it works when escaping the query parameter. /cc @bobsilverberg

**Comment by bobsilverberg** [comment]
Looking at the network panel when testing via a local instance of code manager running at http://localhost:3000/en-US/compare/618629/versions/1690062...1690063, I see the request is being made to http://localhost:3000/api/v5/reviewers/addon/618629/versions/1690063/?file=users%20test&lang=en-US, so it appears that the front-end is already escaping the filename, but the API is still generating a 500.

**Comment by EnTeQuAk** [comment]
The issue here is with the cache-key generation:

```python
E   memcache.Client.MemcachedKeyCharacterError: Control/space characters not allowed (key=b'amo:dfde4542a94b489990dc5ebb143711fd::1:reviewers:fileentriesserializer:hashes:f7f378aa9a95090bf858e32dfc8136d9c2bd7c36:content script.js')
```

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
All the file examples mentioned above are now returning a 200 response and their contents can also be loaded in code-manager.
