### ISSUE TITLE
Don't allow editing scanner query rules once they have been triggered once

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13271]
In code search admin, once a query rule status is no longer in `New` state, we shouldn't allow admins to edit them, except to abort a `Running` query.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

- Scanner query rules fields can be updated while their State = New
![image](https://user-images.githubusercontent.com/31961530/73843057-86751a80-4826-11ea-961a-75dca4296d4c.png)

- While rules are Running, they can be Aborted but fields are no longer editable

- A rule in Aborting/Aborted/Completed state can no longer be edited

![image](https://user-images.githubusercontent.com/31961530/73843088-9856bd80-4826-11ea-908d-98a29519d924.png)
