### ISSUE TITLE
Prevent creating non-yara code search scanners rules

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13270]
STR:
- To to the Scanner Query Rule admin page to add a new query rule.

Expected results:
- Only yara is available as a scanner for query rules.

Actual results:
- All scanner types are available.

**Comment by ioanarusiczki** [comment]
@diox I went to Add scanner query rule but I only see the `Yara` scanner being available. I checked dev and stage.

**Comment by diox** [comment]
Both got my fix so that's what's expected.

**Comment by ioanarusiczki** [comment]
@diox Yes, it's quite clear in the issue :))  But my mind went the other way because I saw yara already being there from the last week. 
This issue is verified on dev and stage with FF72(Win10)
