### ISSUE TITLE
Get notified of new version when info requested flag is activated

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#13280]
Hello,

When reviewer is activating information requested flag (over 7 days for example) and the developer is submitting a new version. Reviewer is not notified and can't get informed until the information requested flag is over after these 7 days.

It would be interesting to have this new version notification when the information requested flag is ON to not miss a review and let potential add-on with vulnerabilities.

**Comment by wagnerand** [comment]
There is a setting at the end of the page _Notify me about new listed versions_. Would that work for you?

**Comment by eviljeff** [comment]
closing because no response.  We can reopen.
