### ISSUE TITLE
prevent further updates to an existing Block when it's guid is present in a BlockSubmission

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13283]
follow on from  #13201 

We should show/block further edits in existing Block page when a BlockSubmission is outstanding.  Ideally the same restriction should be shown in the GUID input view too if a matching GUID is in an outstanding BlockSubmission

**Comment by AlexandraMoga** [comment]
An existing block can no longer be updated in the following cases:
- when the single block edit is waiting for sign off
- when the blocked guid is pending for sign off as part of a multiblock submission

Additionally, guids that are pending for sign off can't be added as new blocks. The following error message is received:
`GUID {guid} is already in a pending BlockSubmission`

@eviljeff I have some questions (as usual):
- the requirements in #13089 are saying that while a block is pending for sign off, there should be a warning message displayed on the block detail view. Where you planning to implement that later on? If so, I can file an issue to keep track of that.
- a block can be deleted while it's pending for sign off. If the sign off is approved, the block entry is created again.  Should we also prevent deletions while a block sign off is pending?

**Comment by eviljeff** [comment]
>  the requirements in #13089 are saying that while a block is pending for sign off, there should be a warning message displayed on the block detail view. Where you planning to implement that later on? If so, I can file an issue to keep track of that.

There's a message shown at the bottom of the log.  As there wasn't any UX it wasn't clear how prominent (or where) the warning should be so I went with that.

>  a block can be deleted while it's pending for sign off. If the sign off is approved, the block entry is created again. Should we also prevent deletions while a block sign off is pending?

yes, I thought they were already.  Can you file a follow-up?

**Comment by AlexandraMoga** [comment]
> There's a message shown at the bottom of the log. As there wasn't any UX it wasn't clear how prominent (or where) the warning should be so I went with that.

@eviljeff I couldn't see the message you refer to. If by _at the bottom of the log_ you mean the Block history, #13489  is currently blocking the verification.

**Comment by AlexandraMoga** [comment]
Filed #13577 for the pending changes message
