### ISSUE TITLE
Update/Add logging to Block

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13282]
follow-on from #13201

When a Block is created the sign-off user should be noted in the logs

**Comment by AlexandraMoga** [comment]
@eviljeff I can see the following logs when I'm looking in the Activity log and in a Block submission History:

Activity Log (sign-off for a new add-on added to blocks and a block edit)
![image](https://user-images.githubusercontent.com/31961530/74439447-e9912d80-4e74-11ea-8530-df9190f81aac.png)


Block submission history (with sign-off)
![image](https://user-images.githubusercontent.com/31961530/74439495-0168b180-4e75-11ea-8184-2d828635b1ad.png)

Also, you might want to loo at #13489 as a potential regression.
