### ISSUE TITLE
Enable information requested flag without sending an other message

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#13281]
Hello,

It often happens that during the process of add-on review, we ask information to developers and they respond to tell us that they will take care of it by a message which results in the deactivation of the information requested flag.

The only way we have to re-enable it is to respond a generic message.

It would be interesting to be able to activate the flag without writing this message.

**Comment by wagnerand** [comment]
I think we could add that option when leaving a comment. I would prefer to have a record/statement on why a need-info was set, for other reviewers to follow up or take over the review if needed.
