### ISSUE TITLE
Pretty print the `definition` of a rule when viewed in readonly mode

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13292]
When a user can access the scanner rules in readonly mode only, it would be nice to pretty-print the definition of the rules. Currently, it is displayed as text but it is hard to read.

### Example

Current view:

![Screen Shot 2020-01-17 at 17 48 37](https://user-images.githubusercontent.com/217628/72629951-9c8f6980-3951-11ea-9a4b-9714c1af0a38.png)

Expected view:

![Screen Shot 2020-01-17 at 17 48 00](https://user-images.githubusercontent.com/217628/72629945-9600f200-3951-11ea-8a98-fe0ae9048dd4.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. 
Rule readability has been improved with the nee format:

 
![image](https://user-images.githubusercontent.com/31961530/72737809-fc338200-3ba8-11ea-99b2-4cfb9a58adcb.png)
