### ISSUE TITLE
Error in building addons-server locally

### ISSUE THREAD

**Issue by KaairaGupta** [mozilla/addons-server#13299]
### the problem and steps to reproduce it:
Follow the steps given to install addons-server with docker.
when we enter the final command in terminal "make initialize", this error was thrown up:

`PermissionError: [Errno 13] Permission denied: '/code/site-static/img' Makefile-docker:139: recipe for target 'update_assets' failed make: *** [update_assets] Error 1 Makefile-os:28: recipe for target 'initialize' failed make: *** [initialize] Error 2`

I found out that this is because 'the user' and ':user' of 'site-static' file is set to root. This prevents olympia.test from accessing it.

I worked around it by manually changing the permissions of site-static file by chown command

**Comment by muffinresearch** [comment]
This has come up before, if nothing else, it's definitely something we should add to https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#gotchas

**Comment by rubenwardy** [comment]
I get this error too. The fix is to run:

```
sudo chown 1000:1000 site-static
```

**Comment by diox** [comment]
@rubenvereecken did you run any commands needed for install as `root` ? perhaps using `sudo` ?

**Comment by rubenwardy** [comment]
I assume you've tagged the wrong user. I followed the instructions from <https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#gotchas>, I didn't use sudo

**Comment by diox** [comment]
woops not sure why github autocompleted to a different user.

Is your user id on your host machine `1000` or something different ?

**Comment by rubenwardy** [comment]
Oh weird, my user ID _is_ 1000. Could it be creating the dir as root? I didn't note down the old user

**Comment by diox** [comment]
I haven't looked in this issue in a while, but usually it happens to people doing part of the install as `root` (so the directory has the wrong owner) or with a user on the host having a uid different from 1000 (because of https://github.com/mozilla/addons-server/issues/13857, which is _terrible_ and we should fix)
