### ISSUE TITLE
Investigate pygit2 performance by iterating differently through the diffs

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13291]
This is just temporary for now till I played more with it but I found https://github.com/libgit2/pygit2/issues/736 and it seems that there might be some more performant API usage that we could use to speed up the diff api.

I'll investigate and update the issue accordingly.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Please add some str for qa in case this can be tested.
Thanks!

**Comment by ioanarusiczki** [comment]
As discussed this is a qa not needed.
