### ISSUE TITLE
Block submission pages are using the entire Submission logs as page locators

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13307]
Follow up for #13201

### Describe the problem and steps to reproduce it:
1. Log into the Admin Tolls
2. Open the Block submissions module and select one of the entries to inspect - see https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocksubmission/20/change/
3. Look in the navigation bar (breadcrumbs) and identify the current page locator

### What happened?
The page locator uses the entire 'Submission Logs' data to identify the current page, which makes the title extremely long

### What did you expect to happen?
Block submission pages should use a different locator 

### Anything else we should know?
- the same locator is used in success messages, in block history etc

[breadcrumbs]
![image](https://user-images.githubusercontent.com/31961530/72787892-7c092d00-3c39-11ea-8158-40d432125b38.png)

[success message]
![image](https://user-images.githubusercontent.com/31961530/72787908-80354a80-3c39-11ea-98e4-5d5d57c96bcf.png)

[block history]
![image](https://user-images.githubusercontent.com/31961530/72787933-888d8580-3c39-11ea-8a92-ef6446ce4a48.png)

**Comment by Abhi-khandelwal** [comment]
Can I take this issue ?

**Comment by eviljeff** [comment]
@Abhi-khandelwal if you have a good idea how to change it, sure. (I've not had the chance to think about it)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The Submission logs are trimmed now:

![image](https://user-images.githubusercontent.com/31961530/77426005-4d940380-6ddc-11ea-86c0-ef6f18168c6c.png)

![image](https://user-images.githubusercontent.com/31961530/77426038-5f75a680-6ddc-11ea-980b-ce1f8a8f6038.png)

![image](https://user-images.githubusercontent.com/31961530/77426053-63a1c400-6ddc-11ea-92ce-9e3674a30225.png)
