### ISSUE TITLE
The 'Save' button should change to 'Submit' after the changes to the multiblock form are saved

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13304]
### Describe the problem and steps to reproduce it:
1. Go to the admin blocklist module
2. Select  a few guids and add them to a new multiblock 
3. Click on Save the to confirm all your changes made in the multiblock form
4. Notice the state of the 'Save' button when you try to submit your block request

### What happened?
Having the same name for the 'Save' button both for saving the multiblock form and for actually submitting the block request is a bit confusing

### What did you expect to happen?
The button name should change to 'Submit' once the changes to the form are saved

![2020-01-20_15-47-28](https://user-images.githubusercontent.com/31961530/72732145-cc32b180-3b9d-11ea-9beb-097b1c5def26.gif)

**Comment by eviljeff** [comment]
There's only a need to press Save twice if you change the max/min versions.  (Otherwise it would submit after the first press).  Save is submit.

**Comment by eviljeff** [comment]
I'm going to change this flow with https://github.com/mozilla/addons-server/issues/13480 so there isn't a double save.  (It will either clearly error with a validation message, or save straight away).  So closing this issue.
