### ISSUE TITLE
Create an API endpoint to expose the scanner results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13317]
Refs https://github.com/mozilla/addons-server/issues/13142

---

Only authenticated users with `ADMIN_SCANNERS_RESULTS_VIEW` should be able to query this new endpoint. The new endpoint will expose the scanner results with pagination (page-based?). We can start by exposing the following properties:

- `id`
- scanner name
- (raw) `results`
- ~~label (good vs bad but values TBD)~~ see #13334 

**For QA:** please ping us so that we can temporarily enable this API endpoint in -dev (it is behind a feature flag (switch) named `enable-scanner-results-api`).

**Comment by willdurand** [comment]
> label (good vs bad but values TBD)

This will be done in https://github.com/mozilla/addons-server/issues/13334

**Comment by AlexandraMoga** [comment]
I've verified the new [scanner results api endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/scanners.html#get--api-v4-scanner-results-) on -dev and I have the following results:

- the API responds only when the `enable-scanner-results-api` is enabled
- to query this API your user needs to be either super admin or has `Admin:ScannersResultsView` permission; non-authorized users will receive a 403
- the API exposes the scanner `id`, `name` and `results` object 
- the API is paginated (25 results per page)
- the `results` object keeps a track of files scanned and their matched rules (where applicable) for each of the three scanners

@willdurand For future iterations, I think it could be useful to also expose the add-on `guid` in this API

**Comment by willdurand** [comment]
@AlexandraMoga thanks! As for the `guid`, we do not want to expose it because the clients should not be able to associate scanner results with add-ons/versions (for privacy reasons).
