### ISSUE TITLE
Don't show "Run" button for rules not saved yet in scanner query rules admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13318]
When creating a new Scanners Query Rule, the state field is readonly, and the default is `New`. Next to that field is the "Run" button, but it should only be shown for existing rules, not ones that haven't been saved yet.

(The admin is likely to change a bit and this part might end up being completely hidden, but it's best to still do the one-line change this represents to avoid confusion)

**Comment by diox** [comment]
Did that when I did https://github.com/mozilla/addons-server/pull/13367

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

Before Save
![image](https://user-images.githubusercontent.com/31961530/73649104-b4702880-4687-11ea-94dc-ca5549397a12.png)


After Save
![image](https://user-images.githubusercontent.com/31961530/73649112-b934dc80-4687-11ea-9451-173c71506a22.png)
