### ISSUE TITLE
Add a new `ml_api` scanner

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13324]
Supports https://github.com/mozilla/addons-server/issues/13140

---

We'll use a new (meta) scanner to persist the ML API results. The name of this scanner will be: `ml_api` (constant `ML_API`).

**For QA:** the new scanner will likely appear in the list of scanner results or when creating a new scanner rule. For now, we don't expect this scanner to be used.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. 
The `ml_api` scanner is present in the filter 'By scanner' in scanner results and in scanner rules admin pages. It is also available for selection in the drop down list when creating/editing a scanner rule.  

As mentioned in the issue notes, this scanner is not active yet, i.e. there will be no results created for this new scanner.
