### ISSUE TITLE
Add a `score` field to `ScannerResult`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13332]
We discussed that with @diox in Slack. We'd like to extract the different `score` values returned by the ML API and store them in the scanner results.

We'll have an aggregate score that we'll set on the `ScannerResult` created by the `call_ml_api` task (see #13140).

We'll have one score per scanner result sent to the API and we'll set this score to the corresponding `ScannerResult` (customs results will always have a score, for other scanners we'll see).

This issue is related to #13141.

**Comment by willdurand** [comment]
I requested a change in the API contract of the mad server (because this contract has changed). Once we have that, we'll be able to extract and store the score easily.

**Comment by AlexandraMoga** [comment]
There is a new 'Score' column in scanner results which is populated with `-` (yara and wat) or `n/a` (customs). By reading the conversation from the pull request, I get it that these values might change in the future.

@willdurand Is there an interpretation to this score right now or was this issue just about adding the new column?

**Comment by willdurand** [comment]
> @willdurand Is there an interpretation to this score right now or was this issue just about adding the new column?

There is nothing else for now *but* as soon as the MAD server works (and therefore returns valid results), the score of `customs` should be updated with a value that is not `n/a`.

**Comment by AlexandraMoga** [comment]
I'm marking this as verified for now and will revisit once the MAD server works.
