### ISSUE TITLE
Add-on validation fails with error 403

### ISSUE THREAD

**Issue by kir** [mozilla/addons-server#13333]
### Describe the problem and steps to reproduce it:

Cannot upload new add-on version for https://addons.mozilla.org/en-US/developers/addon/checkvist-bookmarklet/, with error:     
`Received an empty response from the server; status: 403`

The add-on was previously disabled due to usage of `eval` in the code.
Now, `eval` is not used. Also, with local validation, there are no errors, only some warnings.

![Screenshot 2020-01-20 at 13 38 20](https://user-images.githubusercontent.com/56328/72727132-77d20680-3b8a-11ea-9596-f61c35372cb2.png)

I'm afraid I'm not sure how to escalate the problem further.

**Comment by diox** [comment]
Sorry for not getting back to you sooner. I see you managed to upload a few versions since, so I'm going to close this, but let us know if we should re-investigate.
