### ISSUE TITLE
Expose `label` in the scanner results API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13334]
We added a new API endpoint to expose the scanner results in https://github.com/mozilla/addons-server/issues/13317. We need to expose a `label` in addition to the existing data per scanner result. In order to expose this `label`, we need to fix https://github.com/mozilla/addons-server/issues/13142 first.

**Note:** we'll probably only expose the scanner results with a `label` that is not `null` (or `None` or `Unknown`) because we're only interested in labelled results.

**For QA:** there should be a new `label` attribute in the JSON response (for each result entry) and we should only return labelled scanner results.

**Comment by ioanarusiczki** [comment]
@willdurand I verified with Postman on dev the scanners result[ API](https://addons-server.readthedocs.io/en/latest/topics/api/scanners.html). In the response JSON object
- results include a "label": good - for add-ons without matched rules 
- results include a "label": bad  - add-ons reported as true positive  
- there are results which also have an extra "label":null in `results` below the `filepath` 

![the label](https://user-images.githubusercontent.com/33448286/73546538-13def600-4446-11ea-9785-809b8f19db86.png)

Let me know if it's alright. 
Thanks!

**Comment by willdurand** [comment]
please don't expose the API results in public issues :)

**Comment by ioanarusiczki** [comment]
@willdurand I thought I forgot to add it. You were quick!
I'll disable the switch from admin too because I finished testing.
Noted. If it's about scanners I'll be careful in the future.

**Comment by willdurand** [comment]
> @willdurand I thought I forgot to add it. You were quick!

Fortunately :)

> Noted. If it's about scanners I'll be careful in the future.

Thanks.

As for your question, the second `label` belongs to one of the scanners and we don't really care (the content of the results is tied to the scanners).

Let me know what you found but without JSON output :p

**Comment by ioanarusiczki** [comment]
@willdurand Ok, sure. I can explain the details without adding screenshots too.
