### ISSUE TITLE
Add `call_ml_api` task to the validation chain

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13331]
In https://github.com/mozilla/addons-server/issues/13140, we added a new task to call the ML API for the sectools. This issue is about using this task in the validation chain so that we can call this API (once it is possible).

We'll likely want to use a waffle switch to control this task (similar to what we have for the scanners).

**Comment by AlexandraMoga** [comment]
@willdurand with the switch enabled, I'm currently looking for regressions in add-on submissions and scanner results linked to them. I believe this is what I'm able to test at this moment, given the fact that we are not exposing any actual `ml_api` scanner results in admin.
If you have some more specific instructions, I'll be happy to test them too.

**Comment by willdurand** [comment]
Indeed, that's the only thing we have to test right now. Once we hook up the ML API, I'll file a new issue with instructions to test the integration.

**Comment by AlexandraMoga** [comment]
I've submitted several add-ons, both from dev hub and the signing api (including load tests) and verified the scanner results tied to these submissions. I didn't notice anything out of the usual. 

I'm marking this issue as verified fixed.
