### ISSUE TITLE
Entry depth of the deleted folder is not correctly set in the compare API

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-server#13349]
### Describe the problem and steps to reproduce it:
URL: https://addons-dev.allizom.org/api/v5/reviewers/addon/7560/versions/1252898/compare_to/1688305/?lang=en-US
### What happened?
In the response JSON object, file.entries['chrome'].depth == 1

### What did you expect to happen?
The depth should be 0.

### Anything else we should know?
64846a997e36a2fcafc added all parent folders for deleted files, but did not set the depth correctly for grandparent folders.
https://github.com/mozilla/addons-code-manager/issues/1327#issue-535621803 is still not fixed due to this bug.

**Comment by ioanarusiczki** [comment]
@mirefly I verified with Postman on dev for https://addons-dev.allizom.org/api/v4/reviewers/addon/7560/versions/1252898/compare_to/1688305/ 
the depth for `chrome` is 0 

![chorme depth](https://user-images.githubusercontent.com/33448286/73538478-d1142280-4433-11ea-900e-dcb7acf435be.png)
