### ISSUE TITLE
Make it possible to share all Collections, and your user profile, with links

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#13356]
### Describe the problem and steps to reproduce it:
* I cannot share my collections with this link: https://addons.mozilla.org/en-US/firefox/collections/11536848/
* I cannot share my profile with this link: https://addons.mozilla.org/en-US/firefox/user/11536848/

### What happened?
* For https://addons.mozilla.org/en-US/firefox/collections/11536848/: ![Screenshot at 2020-01-26 01:49:02](https://user-images.githubusercontent.com/6416073/73129181-0bb62f00-3fde-11ea-8171-b67541c47335.png)
* For https://addons.mozilla.org/en-US/firefox/user/11536848/: 
![Screenshot at 2020-01-27 20:16:58](https://user-images.githubusercontent.com/6416073/73205806-03770480-4142-11ea-9450-90fcad983c62.png)

### What did you expect to happen?
* I expected the page to list all my collections so I could share them with people in the same way that I can share my individual collections, like https://addons.mozilla.org/en-US/firefox/collections/11536848/accessibility/ for example.
* I think it should be possible to share the user profile as well.

### Anything else we should know?
I think a "Collections" link should be added to
* the user pages for users that has created one ore more collections (like [me](https://addons.mozilla.org/en-US/firefox/user/11536848/).
* individual collection pages (example: https://addons.mozilla.org/en-US/firefox/collections/11536848/accessibility/) under the text "Creator".
* The user name on Collection pages which is just text for the moment, should link to the user profile.

**Comment by eviljeff** [comment]
these were deliberate changes to reduce the complexity of the collections feature.  You are still free to link to individual collections from your own website/pages.
