### ISSUE TITLE
Allow to exclude results with a given matched rule in the list of scanner results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13361]
Some rules match more often than others. We use the list of scanner results to triage these results. We'd like to exclude results that are associated with a given matched rule so that we can better see the results for the rules that don't match too often.

**For QA:** we added a new filter ("By all but this rule") that is used to hide the scanner results (not the query results) bound to the rule selected in this filter. By default no rule is excluded.

**Comment by AlexandraMoga** [comment]
I've verified the new 'By all but this rule' filter and it seems to be working as expected.
@willdurand I have one observation regarding scanner results with multiple matched rules. If one of those matched rules is filtered out, the scanner result will be hidden from view entirely. I'm not sure if we can or need to address this use case.

**Comment by willdurand** [comment]
> @willdurand I have one observation regarding scanner results with multiple matched rules. If one of those matched rules is filtered out, the scanner result will be hidden from view entirely. I'm not sure if we can or need to address this use case.

I think this is the expected behavior. I am not sure to know how we can do it otherwise. This filter isn't used by default so I guess that's fine for now. We'll see once @wagnerand starts using it.
