### ISSUE TITLE
Add a new `state` for scanner results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13360]
We need a new `state` value to describe scanner results that are technically correct but still not considered "bad" (and not "good" either). This is when a rule matches for good reasons but the use case is legit.

I am not sure what a good name would be, though. I have `inconclusive` in mind but that's generic.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
A scanner result can now be marked as `Inconclusive` from the Actions section in the scanner results list view or from a scanner result detail view. 
The Inconclusive report can also be reverted.
Users are also able to filter scanner results that have been marked with this state.
