### ISSUE TITLE
File validation returns 500 for versions

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-server#13374]
### Describe the problem and steps to reproduce it:
https://addons-dev.allizom.org/en-US/developers/addon/webmail-ad-blocker/file/237880/validation.json

### What happened?
It returns 500

### What did you expect to happen?
No errors. (Or 404 when url is incorrect)

### Anything else we should know?
I found it when visiting https://code.addons-dev.allizom.org/en-US/compare/7560/versions/124625...1508403/. It looks like it depends on the versions I chose. I am not sure why some versions have this problems, while others work well.

**Comment by diox** [comment]
We should return a 404, yeah. The `FileValidation` doesn't exist because it's an old file from 2013.

**Comment by diox** [comment]
View to fix is in `devhub/views.py`: `json_file_validation`. Gotta catch `File.validation.RelatedObjectDoesNotExist` before accessing the `file.validation`. That will need a test.

**Comment by wagnerand** [comment]
If this is your first contribution, please refer to wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by ioanarusiczki** [comment]
@mirefly https://addons-dev.allizom.org/en-US/developers/addon/webmail-ad-blocker/file/237880/validation.json returns a 404. 
Verified on dev with FF72(Win10).
