### ISSUE TITLE
Fix link to matching query rule in scanner query results admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13372]
In the admin, when looking at scanner query results, the link to matching rule is broken, it links to a Scanner Rule and not a Scanner Query Rule. The reverse works fine (Scanner Query Rule correctly links to Scanner Query Results).

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The matched rules linked in the scanner query results list and detail view are pointing now to `/scannerqueryrule/`
