### ISSUE TITLE
Validator should inform the developer if the webextension lists unsupported permissions

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1337]
## steps to reproduce:
1. Upload a webextension which lists an unsupported permission (like BookmarkTreeNodeUnmodifiable) to amo.dev

## expected behavior:
Validator warns the dev that their manifest.json lists permissions which may be unsupported on Firefox OR fails validation since it may affect firefox user experience.

## observed behavior:
Validator doesn't check for supported APIs

**Comment by andymckay** [comment]
Moving over to the js-validator, its not a blocker for WebExtensions in my opinion.

**Comment by EnTeQuAk** [comment]
Shouldn't this better be in `addons-linter` for tracking reasons too?

**Comment by andymckay** [comment]
Getting there, but added in mozilla/addons-linter#668.

**Comment by EnTeQuAk** [comment]
Correct me if I'm wrong but permissions and many other details are now being checked in addons-linter 0.4.0 and we pulled that in last week.

So I'm closing this as solved but feel free to reopen if I'm mistaken.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
Postfix screenshot: 
![2016-05-24_1049](https://cloud.githubusercontent.com/assets/15685960/15496361/69d9a66a-219d-11e6-82a2-61136cf4a20f.png)


Warning number is still incorrect and we have #2718 for this (that is still opened)
