### ISSUE TITLE
Search results return deleted plugins on AMO dev 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13382]
I am filing this because it could cause question marks and get into someone's way in the future as a followup for https://github.com/mozilla/addons-server/issues/12463#issuecomment-577054989 

STR:
1. Load AMO dev and make a plugin search such as "Eccellio" and then click on the search result or go to https://addons-dev.allizom.org/en-US/firefox/search/?type=search and just click on the results.

Actual result:
The 404 page is shown. 

Expected result:
The plugins should no longer be available in search results.

Notes:
The issue is only reproducible on AMO dev. 
Not reproducible on AMO stage or prod.

**Comment by muffinresearch** [comment]
@EnTeQuAk could the index be out of date?

**Comment by EnTeQuAk** [comment]
I'll run a re-index on -dev.

**Comment by EnTeQuAk** [comment]
re-index ran and search results are updated.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I verified AMO dev and the search results won't return plugins in autocomplete results. 
Also the search API https://addons-dev.allizom.org/api/v4/addons/search/?type=search is no longer returning results. 

The only difference with stage is in the Addon detail API, for example a deleted plugin in dev will return a 200 status and the details are available Example: https://addons-dev.allizom.org/api/v4/addons/addon/618634/ . Meanwhile, on stage for a deleted plugin the API responds with a 404 
Not Found. Example: https://addons.allizom.org/api/v4/reviewers/addons/addon/1003983/ 

I can't tell which is the right result, I'm thinking since it's been deleted it's alright to be a 404. 
So let me know what you think and if I should file a followup for this.
