### ISSUE TITLE
Deleting an user isn't reflected in Salesforce

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13392]
STR:
- Enable `basket-amo-sync` waffle switch on dev
- Create an user account
- Make sure it gets synchronized to Salesforce
- Delete the user account

Expected results:
- The user data is removed from Salesforce

Actual results:
- The user data is still in Salesforce

Note: we are sending the `deleted` property to basket, but I don't know what happens to it after that.

**Comment by eviljeff** [comment]
Should this issue be refiled under a salesforce issue tracker?  It doesn't seem there's anything to do on our side.

**Comment by diox** [comment]
It's being tracked on their side but having it around here helps as a reminder (and also if we end up having to help on our side)

**Comment by eviljeff** [comment]
is there a link to the issue?

**Comment by diox** [comment]
@caitmuenster do you know if for this and https://github.com/mozilla/addons-server/issues/12472 there is a link (presumably private, doesn't matter) to track progress on this on Salesforce side ?

**Comment by caitmuenster** [comment]
@diox Not that I'm aware of! I have a note to check in on this this week.

**Comment by diox** [comment]
https://github.com/mozmeao/basket/issues/564 should have fixed this.

**Comment by AlexandraMoga** [comment]
Test data has been created and is currently pending for verification with the Salesforce team.
