### ISSUE TITLE
Test DB generation and diffing

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#13408]
In order to support a CRLite DB for an add-ons blocklist we need to test generating it from AMO's block data.

* [x] Test [filter-cascade](https://github.com/mozilla/filter-cascade) for blocklist db generation
* [x] Test creating diffs

## Questions to answer

- What size is the DB output?
- What sSize are the diffs?
- How quickly is the main db generated?
- How quickly are diffs generated?

**Comment by eviljeff** [comment]
With some local testing based on some randomly generated guids&versions (2 million addons and 100k blocks):

> What size is the DB output?

135kb

> How quickly is the main db generate?

30 seconds for the bloom filter generation + whatever time it will take for the database query to populate the list of guids&versions (~5 seconds) + file write time (~1 second)

For diffs I added an extra 100k guids&versions to the addons list, and an extra 10k guids&versions to the blocks (10% new for each).

> What size are the diffs?

only a few kb less than the full file (filter increased to 137kb; diff was 134kb).

> How quickly are diffs generated?

didn't seem to be any significant increase over just generating the bloom filter.

**Comment by eviljeff** [comment]
If we land it on -dev we can get more realistic numbers on the db query, though as the addons and blocks are very outdated for non-production environments, probably not much better overall (there are very few blocks that are valid when importing from kinto)

**Comment by AlexandraMoga** [comment]
@eviljeff should I test this on -dev? If so, can you give me some instructions? 
Thanks
