### ISSUE TITLE
Allow admins to have a scanner-held version auto-approved without explicit removal.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13401]
(MVP of #13399).

When auto-approval is held-back for a version because of a security scanner rule action, admins would need a way to manually have that version auto-approved.

(The only way to approve currently is using the reviewer tools. This is undesirable because it indicates the version has been reviewed and follows the add-on policies, which is not necessarily the case).

**Comment by diox** [comment]
I think we want two things here:
- Moving the scanners to only delay auto-approval of the version they have scanned, not the entire add-on. Maybe create a new model to hold reviewer-specific flags for versions (and not add-ons as we already have) and create the field there. Bonus points: also move `needs_human_review` while we're at it
- Adding a button somewhere to remove that delay

**Comment by wagnerand** [comment]
@diox pointed out that we already have a way to do this. Let's close this for now and revisit later if needed.
