### ISSUE TITLE
Prefix or namespace scanners result/query rule states more

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13411]
In https://github.com/mozilla/addons-server/pull/13407#discussion_r374617288 @eviljeff wrote:
> (...) state constants are too generically named and should be either be prefixed e.g. `SCANNER_STATE_NEW` or at least namespaced. e.g. `from olympia.constants import scanners`

I agree, at the moment it's bearable because they are only used in scanners-specific code but it's already a bit confusing, so we should fix this. 

For `NEW` and other scanner query rule states, technically if we also want to differentiate them from scanner result states, the problem is that the prefix should really be `SCANNER_QUERY_RULE_NEW` which is a bit too much. Ideally we'd come up with something slightly less verbose.

Thoughts, @willdurand ?

**Comment by willdurand** [comment]
> Thoughts, @willdurand ?

I guess we should use `SCANNER_QUERY_RULE_` as a prefix. It's rather long but very accurate. I don't have a better idea..
