### ISSUE TITLE
Update MDN links to point to Extension Workshop

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#13415]
AMO has a few links that point to MDN and haven't been updated to EW. We should update the links to point to where they redirect.

Example: https://github.com/mozilla/addons-server/blob/134723e103483404636f358367d7ed3511465399/src/olympia/devhub/templates/devhub/addons/submit/source.html#L20

**Comment by caitmuenster** [comment]
Coming soon -- a list of links that need updating and the updated link targets. 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg

**Comment by junngo** [comment]
I submitted patch :)
Should I also need to change the link below[0]?

[0]
https://github.com/mozilla/addons-server/blob/dd1224e3e799d37efa17808acc2f50b445cdb6d1/src/olympia/lib/crypto/tasks.py#L42

**Comment by diox** [comment]
Yes.

**Comment by junngo** [comment]
I submitted PR again.
The URL is more than 80 characters long. Should I write less than 79 characters without exception?

**Comment by diox** [comment]
Easiest way to fix this in this instance is to replace the `'''` a few lines below by `'''  # noqa` (note the 2 spaces after the three single quotes). That will tell our linter tool to ignore that part.

**Comment by junngo** [comment]
Thanks :)
I solved lint issue and submitted PR again.

**Comment by ioanarusiczki** [comment]
@caitmuenster 

I verified this on AMO dev with FF73(Win10). The following EW are available while making an add-on submission:
[More information on Developer Accounts](https://extensionworkshop.com/documentation/publish/developer-accounts/)
[More information on Add-on Distribution and Signing](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/)
[source code submission policy](https://extensionworkshop.com/documentation/publish/source-code-submission/)
[policy requirements](https://extensionworkshop.com/documentation/publish/source-code-submission/)

If there's anything else I should check on please let me know. Thanks!
