### ISSUE TITLE
Update amo-admins email for some locales

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13412]
The amo-admins email changed quite a while ago, but some locales have not been updated to reflect that. Let's update just the email address manually in the respective locale strings.

**Comment by AlexandraMoga** [comment]
@wagnerand is this something we can verify on -dev or stage? I'm not sure what action will trigger this email.

**Comment by wagnerand** [comment]
I think the string I changed is on the devhub. You should see it when going to the devhub page for an add-on that is _Disabled by Mozilla_ and hover over the _?_ icon in the left pane:

Example on -dev: https://addons-dev.allizom.org/pt-BR/developers/addon/lolmdrasv/edit
Example on prod: https://addons.mozilla.org/pt-BR/developers/addon/a808e65c246b4e5980f8/edit

Screenshot from -dev:

<img width="505" alt="Screenshot 2020-02-05 at 11 58 30" src="https://user-images.githubusercontent.com/873258/73836110-de078c00-480e-11ea-85e4-b403d2db82a8.png">

**Comment by AlexandraMoga** [comment]
The amo admins email has been updated from `.org` to `.com` in the Status tooltip for the locales targeted in this patch.
As a note, these string are not translated on -dev and stage yet.



![image](https://user-images.githubusercontent.com/31961530/73841483-70b22600-4823-11ea-95df-5cfcca491824.png)

**Comment by wagnerand** [comment]
From a conversation on IRC I think this depends on the locale. Some locales apparently not for use. @diox can probably explain it better than me.

Could you try with the _pt-BR_ locale please?

**Comment by AlexandraMoga** [comment]
`pt-PT` and `pt-BR` both work, i.e. are localized. The rest of the locales touched by this patch (like `ja`, `tr`, `pl` and others) are not localized.

I do remember previous issues where changed strings were not translated on the spot and that was expected. It's just that in this case I could not understand why the strings were translated for `pt-PT/BR`  while for the others weren't (assuming that the strings in question were localized before ?).

**Comment by diox** [comment]
The translation is marked as fuzzy in those locales, so it's not used.
