### ISSUE TITLE
Add an API for `DeniedGuid` model

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13424]
Refs https://github.com/mozilla/addons-server/issues/13409

---

> A client tool we use might want to add GUIDs to DeniedGuid in bulk. @kewisch might have ideas on what the API should look like exactly, for now I believe it would be something like:
>
> - Check whether a single GUID is in DeniedGuid
> - Add a single GUID to DeniedGuid
> - Remove a single GUID from DeniedGuid

**Comment by willdurand** [comment]
@kewisch and @wagnerand please let us know what the exact needs for this API are

**Comment by kewisch** [comment]
Andreas' bullet points seem reasonable, though I think having a way to bulk add multiple guids would be helpful.

**Comment by diox** [comment]
For the record, I merged @willdurand's work for https://github.com/mozilla/addons-server/issues/13409 ; this will give us 2 APIs:
- `/api/v4/reviewers/addon/(int:addon_id)/allow_resubmission/`
- `/api/v4/reviewers/addon/(int:addon_id)/deny_resubmission/`

It's not exactly what was requested, but it's a start.

**Comment by diox** [comment]
@wagnerand or @kewisch : we need a spec for this API (what should it do, what parameters it should accept, what parameters it should return, who should have access) for this to move forward. Otherwise we'll remove it from the "Add-ons Q1 2020: Improve Admin Workflow" project.

**Comment by wagnerand** [comment]
@kewisch can you comment on the previous ask from Mat?
