### ISSUE TITLE
Eliminate needless and/or duplicate database queries from code-manager APIs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#13420]
This was discussed when we were talking about API performance for code-manager. I am not sure exactly what is involved here, but it was mentioned that the APIs have not been optimized, so that is something we should do to help improve API performance.

**Comment by EnTeQuAk** [comment]
What's involved here is that we need to look at database queries specifically done in the code-manager related APIs and make sure we don't issue duplicate or needless queries.

**Comment by diox** [comment]
I already did a first pass on a couple of the APIs in other issues, going to re-use this issue for the last bit I had not looked at which is the compare API. That's strictly low-hanging fruits like duplicated or useless queries, we'll re-assess after.

**Comment by diox** [comment]
QA: check that there are no regressions in code-manager compare view (you can't test for database queries, but it doesn't hurt to verify this didn't break any functionality)

**Comment by ioanarusiczki** [comment]
@diox I verified on dev with FF74(Win10) and it looks good to me: file navigation, comments, keyboard navigation.
