### ISSUE TITLE
Stop excluding non-current listed versions in code search

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13431]
For the initial implementation of Scanner query rule task, we restricted the versions it runs on, excluding non-current listed versions. Now that we have done some initial testing, we've determined we no longer want to restrict versions that much.

STR:
- Submit a listed add-on, and then submit a new version for that add-on.
- Create a Scanner Query Rule that would match something in both versions and run it

Actual Results:
- Only the currently public version is in the results

Expected Results
- The 2 versions are found

**Comment by AlexandraMoga** [comment]
I've created a scanner query rule on -dev and the submitted several add-ons that would match it. I've tried to cover the following scenarios:
- add-on with multiple listed versions, all matching the query rule => all versions were identified after the query run
- add-on with multiple listed versions, no matching rules => versions not identified after the query run
- add-on with mixed listed and unlisted versions, all matching the query rule => all versions were identified after the query run
- add-on with multiple listed versions, some with matching rules, others without => only the versions with matched rules were identified after the query run
- add-on with multiple listed versions, one of the versions disabled/deleted => all versions were identified after the query run, including deleted and disabled versions

@diox just to be clear, we do want disabled and deleted (listed)versions to be captured by scanner query rules, right?

**Comment by diox** [comment]
> @diox just to be clear, we do want disabled and deleted (listed)versions to be captured by scanner query rules, right?

Yes. We're only excluding versions that belong to add-ons that have been force-disabled by admins.
