### ISSUE TITLE
File temporarily unavailable after add-on deletion

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13433]
### Describe the problem and steps to reproduce it:

When an add-on gets deleted, the file is unavailable in the reviewer and admin tools. I believe this is temporary, until the cronjobs have run. That can take a couple of hours tough, affecting admins.

Assuming STR:
(This might depend on the time of the hour you run this, due to the cronjobs runnin at :25 and :55 each hour)
1. Submit a new add-on
2. Delete the add-on
3. As a reviewer, try to download the file in the reviewer tools, inspect the code using the file-viewer or the code-manager
4. As an admin, visit the django file admin page for the submitted file and try to download the file using the download link. 

### What happened?

I expect 3 and 4 to fail.

### What did you expect to happen?

At least 4 should work. It would be great if 3 worked as well.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
https://github.com/diox/olympia/blob/13bf7ce0e813c3250c3a33148e7975c3ad70d3d4/src/olympia/addons/models.py#L608-L612

We can't do this synchronously when the add-on is deleted but we should fire up a task at that point to do it earlier than the crons (keeping them as a fallback).

**Comment by mirefly** [comment]
I investigated this issue and found that we did not mount `/code/storage/guarded-addons` to the container at all (https://github.com/mozilla/addons-server/blob/master/docker-compose.yml#L37-L41). So the deleted files (after deleting an add-on) will not be available even after the crobjob (or I missed something?). It looks like we have to add something like:
```
    location /code/storage/guarded-addons/ {
        internal;
        alias /srv/user-media/guarded-addons/;
    }
```
into https://github.com/mozilla/addons-nginx/blob/master/addons.conf

**Comment by diox** [comment]
That looks correct - it's not something that happens often for local development so we must have overlooked it as it works fine in tests without nginx. On dev/stage/prod it works because we don't use `docker-compose` there at all.
