### ISSUE TITLE
Addons detail API responds with a 200 status for the deleted plugins on AMO dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13449]
Followup for https://github.com/mozilla/addons-server/issues/13382
STR:
1. An API request for a deleted plugin from AMO dev returns details. The Response is 200. 
An example: https://addons-dev.allizom.org/api/v4/addons/addon/618634/

Expected result:
404 - Not found. 

Notes: 
On AMO stage the Addon Detail API for the deleted plugins (the old .xml formats) return a 404.

**Comment by diox** [comment]
I got a 404 for that URL ?

**Comment by ioanarusiczki** [comment]
@diox Strange, it's 404 in the browser. 

I still get this with Postman 

![AMO dev response](https://user-images.githubusercontent.com/33448286/74415500-25fc6380-4e4c-11ea-9e2a-3c61026d0c26.png)

And the details are exposed. 

On AMO stage it's a 404 

![AMO stage - testing](https://user-images.githubusercontent.com/33448286/74415586-55ab6b80-4e4c-11ea-9a77-a1a1c1b9b96d.png)

**Comment by ioanarusiczki** [comment]
@diox So the second API on stage is incorrect - that was the reason I received a 404 in the first place. 
On both servers the API return a 200 response, details are available and "status":deleted - so I'm going to close this issue. 
Sorry for the confusion.

**Comment by diox** [comment]
If you see details + `status: deleted` you're likely using an admin account when making the API request.
