### ISSUE TITLE
Block multiple versions flow for unlisted add-ons is broken

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13444]
### Describe the problem and steps to reproduce it:
1. Log in with a super admin
2. Open the Unlisted review queue - https://reviewers.addons-dev.allizom.org/en-US/reviewers/unlisted_queue/all
3. Select an add-on from the list
4. Use the Block multiple versions option to reject one or more versions
5. When redirected to the admin `/blocksubmission/add/` view, change the version range or edit any other editable fields
6. Save your changes

### What happened?
The information changed by the user is nor saved and the block request is not processed

### What did you expect to happen?
The information added by the user is saved and the block request is successfully processed

### Anything else we should know?
- if you verify the version details in Reviewer Tools, you can see that the status is Disabled by Mozilla, so only the blocklisting flow is broken 
- this looks like a regression because the above scenario used to work; maybe it was introduced when we transitioned to the dual sign off process?
- reproduced on -dev and stage

![2020-02-10_12-12-23](https://user-images.githubusercontent.com/31961530/74141869-6071c080-4c00-11ea-816e-0e2d745d372d.gif)

**Comment by eviljeff** [comment]
I think the patch that implements dual sign off for deletes will fix this too (I changed how some of the params are handled).  If it doesn't when it closes, please re-open.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev.
The Block multiple versions flow from Reviewer Tools is now working as intended.
