### ISSUE TITLE
Errors when trying to open the files from the matched rules section

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13446]
I run quite often into a 404 or 504 when I try to open the old file viewer pages for the files with matched rules from the scanner result detail pages

Expected result:
Perhaps the listed versions could be linked to the new code viewer until the unlisted will be extracted? https://github.com/mozilla/addons-server/issues/13220#issue-548061943

Notes:
I can reproduce this issue with scanner results and scanner query results. - FF72(Win10).

**Comment by wagnerand** [comment]
I'm closing this, as we are planning to replace the links (see #13634, that mentions reviewer tools but I confirmed with @diox that all links everywhere will be changed).
