### ISSUE TITLE
Take screenshot automaticly

### ISSUE THREAD

**Issue by Dawidek990** [mozilla/addons-server#13452]
Hello, I need to know what to do so that the "take screenshot" option immediately saved a photo to disk, and did not ask every time where to save the photo. I don't have to click anything after clicking "download".

Or some firefox add-on that works like this option.

**Comment by rfk** [comment]
Cross-referencing for context since this issue was filed in multiple places: https://github.com/mozilla/application-services/issues/2608#issuecomment-584317839. Please take this question to https://support.mozilla.org and the fine folks there can help you get it resolved.

**Comment by diox** [comment]
This repository is about issues with addons.mozilla.org (the website itself) and not a forum to request addons or support for Firefox. As suggested above please take this question to https://support.mozilla.org please, thanks.

**Comment by Dawidek990** [comment]
i dont see option "ask question" there.

**Comment by rfk** [comment]
Click on the name of the relevant product (e.g. "Firefox" or "Firefox Preview" or whatever) and scroll to the bottom of the page, there should be a link to ask a question.
