### ISSUE TITLE
Add filtering of scanner query results per version/addon properties

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13459]
Scanner Query Results admin has some filtering capabilities inherited from Scanner Results but we want more/different filters:
- Filtering by version channel (listed | unlisted | all)
- Filtering by file status
- Filtering by add-on status

More ?

We also talked about grouping results per add-on but it is be a separate issue (https://github.com/mozilla/addons-server/issues/12947)

**Comment by wagnerand** [comment]
* Filtering by add-on visibility state (visible | invisible | all)
* Filtering by file signed state (yes | no | all)

**Comment by ioanarusiczki** [comment]
@diox I verified on dev with FF73(Win10) the filters. I did not find issues. Maybe one thing: the matched rules filter is now at the top of the page. If the list of rules gets longer it could make the rest of the added filters less visible. On the other hand matched rules could be the most important filter criteria for the scanner query results.

**Comment by diox** [comment]
The ordering of filters is subject to change in the future, not worrying about it now.
