### ISSUE TITLE
"matched rules" filter in Scanners Query Results refers to Scanner Rules incorrectly

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13463]
STR:
- Load scanners query results admin
- Look at the matched rules filter

Expected results:
- It references Scanner Query Rules - rules created just for code search.

Actual results:
- It references Scanner Rules - rules created for uploads. That prevents the user from filtering through rules correctly.

**Comment by ioanarusiczki** [comment]
@diox For the `by matched rules` filter I see the names of the created query rules associated with the scanner's name. 
Verified on dev with FF72(Win10).
