### ISSUE TITLE
Add to the abuse report API the new addon_install_source_url parameter 

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-server#13465]
### Describe the problem and steps to reproduce it:

As part of the changes needed for [Bug 1610844 - Include navigated page in add-on abuse report](https://bugzilla.mozilla.org/show_bug.cgi?id=1610844), we have to update the abuse reports API endpoint to allow an additional `addon_install_source_url` parameter (type: `string|null`).

The change on the Firefox side is in the following phabricator revision:
- https://phabricator.services.mozilla.com/D62265

**Comment by wagnerand** [comment]
Please make sure to update the API documentation as well, as this is a requirement originating from the data-review.

**Comment by bobsilverberg** [comment]
Do we need to update the frontend to also pass this new parameter into its calls to the API?

**Comment by diox** [comment]
@bobsilverberg it's not going to be a required field, AMO itself wouldn't have access to that information anyway. I imagine it would automatically be included for abuse reports coming from AMO through Firefox, though.

**Comment by rpl** [comment]
> Do we need to update the frontend to also pass this new parameter into its calls to the API?

@bobsilverberg I confirm what @diox just said: when AMO is reporting an abuse using the Firefox integrated report panel, the new property is going to be included in the submitted data by Firefox itself (when it is available in the addon db).

**Comment by ioanarusiczki** [comment]
@diox 
- I sent abuse reports from Postman with [Addon Abuse Report API](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#submitting-an-add-on-abuse-report) and the "addon_install_source_url": null is available in response. 

- I sent string type values such as "addon_install_source_url" :"xyz", "addon_install_source_url" :"https://addons-dev.allizom.org/en-US/firefox/" , "addon_install_source_url": " " and in all cases the response displayed them.

**Comment by vcarciu** [comment]
After talking with @diox , I am reopening this in order to add the parameter in admin review for abuse report.

**Comment by diox** [comment]
Closing in favor of #13511
