### ISSUE TITLE
Revert report action throws a 404 for users with Admin:ScannersQueryEdit

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13462]
Follow up for #13268 

### Describe the problem and steps to reproduce it:
1. Log in to AMO -dev with a user that has `Admin:ScannersQueryEdit` permissions (note that you shouldn't have any other 'scanner edit' related permissions)
2. Open the Scanner query results model
3. Mark a report as True positive, or any other action
4. Filter the results to see all States and click on Revert report for your previous action

### What happened?
You receive a 404 for `/admin/models/scanners/scannerqueryresult/<scanner-Id>/revert-report/`
### What did you expect to happen?
The Revert report action is processed successfully

![image](https://user-images.githubusercontent.com/31961530/74247801-537fca80-4cef-11ea-9fc5-72403a002909.png)

**Comment by diox** [comment]
wontfix per https://github.com/mozilla/addons-server/issues/13206#issuecomment-585304067
