### ISSUE TITLE
Implement simplified mimetype detection for code-manager APIs

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13460]
Refs https://github.com/mozilla/addons-server/issues/12924#issuecomment-579748469

We discussed during the All Hands that we're going to decide to simplify mimetype detection for the most common file-types.

The whitelist should contain the following:

`.html, .js, .json, .css`

We'll probably update that list in the future.

**Comment by bobsilverberg** [comment]
@EnTeQuAk Just wondering, can we expect a bit of a performance boost from this? I recall you saying that mimetype detection was quite expensive, and I'm guessing this will cover most of the files in an extension.

**Comment by EnTeQuAk** [comment]
Yes, I am expecting a significant performance boost. If we indeed see that, we could talk about the general code of detecting the mimetype instead of guessing it from the filename and if we really really need the content-based detection. But that's another thing, let's try it out with the most common files and if that helps we can talk about others too and what the side-effects might be.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Please add some STR for qa. 
Thanks!
