### ISSUE TITLE
refactor BlockSubmission to move DUAL_SIGNOFF_AVERAGE_DAILY_USERS_THRESHOLD to a setting

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13474]
Having it as a setting makes it easier to set for local debugging/development, and potentially we might want to have different thresholds on stage than prod (with the bonus that setting it to `0` effectively disables the bypass and forces dual signoff on all Blocks; and setting it to a super high number turns off dual signoff for all Blocks)

**Comment by AlexandraMoga** [comment]
I've verified that the sign off process still respects the threshold set up from #13285
