### ISSUE TITLE
Add-ons with invalid guids can be created on AMO by using the signing API

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13476]
### Describe the problem and steps to reproduce it:
1. Create an add-on package with an invalid guid format
2. Upload the add-on through the [signing api](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#post--api-v4-addons-) - this will create an add-on with no versions on AMO
3. Modify your add-on package by clearing the `guid` entry from the manifest
4. Go to DevHub - Manage my submissions and look for the add-on created previously
5. Upload a new version (it can be either listed or unlisted)

### What happened?
The new version is successfully created and the add-on will appear valid although it uses an invalid `guid`

### What did you expect to happen?
Ideally, we should not create the add-on if the validation detects an invalid `guid` in the manifest

### Anything else we should know?
- this is an example - https://addons-dev.allizom.org/en-US/developers/addon/98c931a866ed4a57a40f/edit
- you can also submit the new version through [this API endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#put--api-v4-addons-(string-guid)-versions-(string-version)-) if you don't want to use the developer hub; the condition remains, as mentioned in the STR, to delete the guid from the manifest

**Comment by diox** [comment]
The signing API doesn't validate the guid in the manifest, because it's the linter's job. The problem is, [the signing API creates add-on instance in database before validation occurs](https://github.com/mozilla/addons-server/issues/7135), so we can end up with an add-on instance in database with an invalid guid, and it's not re-checked afterwards - we trust the data from the db.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

The following error is raised in the following scenarios:

` "error": "Invalid Add-on ID in URL or package"`
- an add-on with an invalid `guid` declared in the manifest submitted through the signing api/webext
- an add-on with an invalid `guid` specified in the URL submitted through the signing api
