### ISSUE TITLE
Scanner query result list and detail views are not refreshed after reporting a false positive

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13471]
### Describe the problem and steps to reproduce it:
1. Open the scanner query results list - https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerqueryresult/
2. Report one of the entries as False Positive 
3. Observe the scanner query results page (ignoring the github page that opens in a new tab)

### What happened?
The scanner query results page is not refreshed. You can see that the entry Reported as False Positive is still having an Unknown state.

### What did you expect to happen?
The scanner query results page should be refreshed after Reporting a False Positive. We are already doing this for the other two Actions. 

### Anything else we should know?
- the same issue also applies when Reporting a False Positive from a scanner query detail view, i.e instead of seeing the Revert report button, all Action buttons are still being displayed.
- the normal scanner result page is refreshed after a False Positive report

**Comment by wagnerand** [comment]
@diox Should this be closed in light of https://github.com/mozilla/addons-server/issues/13206#issuecomment-585304067?

**Comment by diox** [comment]
Yeah.
