### ISSUE TITLE
upload more hero area images

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#13478]
To add more visual variety and programming flexibility to the homepage hero area, can we please upload the images found here:

https://drive.google.com/drive/folders/1wK2Fcgo2txAC4b0ZYt7wI6sCzeTpKep-

(Please note the folder also includes images that currently exist in admin)

@eviljeff

**Comment by eviljeff** [comment]
@devaneymoz what's the deadline on this?  (if any)

**Comment by devaneymoz** [comment]
> @devaneymoz what's the deadline on this? (if any)

No firm deadline but as soon as it's convenient would be great. You think we can get the images uploaded within February?

**Comment by eviljeff** [comment]
@devaneymoz some of these images are a different aspect ratio (currently they're all sized 960x460) and/or portrait.  What should be done about them?  
 - Resize to 960x460 with padding (fixed color though 😿 because no transparency on jpegs)? 
 - Crop to 960x460?
 - Resize to length 960, with a variable height depending on the image.  (Not sure how well addons-frontend will cope with oddly sized images)

**Comment by devaneymoz** [comment]
Difficult to say in the abstract what's the best path, but **crop to 960x640** feels like the optimal path. Would you agree?

**Comment by eviljeff** [comment]
they're ready to check out on addons-dev @devaneymoz (amo prod on Thursday)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- looks good to me on dev and stage - FF73(Win10). 
![new images added](https://user-images.githubusercontent.com/33448286/75347798-41368c80-58aa-11ea-801a-e7d2a6b524c9.png)

- the [docs ](https://drive.google.com/drive/u/1/folders/1wK2Fcgo2txAC4b0ZYt7wI6sCzeTpKep-) do not include 2 pics left from the other time when pictures were added but I don't think it bothers anyone. 

extrapics
![extra pics](https://user-images.githubusercontent.com/33448286/75347923-7f33b080-58aa-11ea-96f0-7fbf5862b537.png)

**Comment by eviljeff** [comment]
oh, I didn't realise some of the existing images had been dropped.  I think we're okay with leaving them (if @devaneymoz doesn't want to use them he can just not select them).  Next time we can have a tidy up.
