### ISSUE TITLE
Block history is not populated in block detail view when the add-on goes through dual sign-off

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13489]
### Describe the problem and steps to reproduce it:
1. Log in with a user that has `Blocklist:Create` permissions
2. Open the Blocklist model and add a new add-on to the list (make sure that you choose an add-on that requires sign-off - i.e. add-on with no stats or with over 100k ADU)
3. With a user that has `Blocklist:Signoff` permissions, open the Block Submissions list and look for the new block request (it should be Pending for sign off)
4. Approve the block submission request
5. Open the block detail page and check the Block history field

### What happened?
The Block history is empty
### What did you expect to happen?
The Block history should be populated in block detail pages when add-ons are going through the dual sign off process

### Anything else we should know?
- this is also valid for block edits that require sign-off
- the Block history field is populated when the add-on doesn't require dual sign-off

[Example](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/1013/change/)
![image](https://user-images.githubusercontent.com/31961530/74438690-66230c80-4e73-11ea-8acd-3ce3b1a19be7.png)

**Comment by eviljeff** [comment]
The `-` generally means there's an error generated while trying to get the value.  It's a django admin "feature" that means bad data is less likely to take down the entire admin page - the downside is when an error _does_ happen you don't know what it is.  I'll see if I can replicate locally.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. Block history is populated again:

![image](https://user-images.githubusercontent.com/31961530/75161992-6cdc3a00-5725-11ea-9194-00323ad9d7e7.png)
