### ISSUE TITLE
Add a filter By Sign-off State option to the Block Submissions list view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13484]
### Describe the problem and steps to reproduce it:
1. Log in with an admin user
2. Open the Blocklist submissions model - https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocksubmission/
3. Try to find the latest blocks Pending for sign-off

### What happened?
In the current format, there is no way to easily filter out block submission entries by their sign-off state

### What did you expect to happen?
We should have  a filter that allows admins to inspect block submissions by their sign-off state

Current page layout:

![image](https://user-images.githubusercontent.com/31961530/74425265-15ec8000-4e5c-11ea-87ef-042dbabde4fb.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The Block submissions list can now be filtered by Sign-off state:

![image](https://user-images.githubusercontent.com/31961530/75334473-9bc2ef00-5890-11ea-9ca3-c72cb3bbc632.png)

Note that the 'Approved' and 'No Sign-off' states were used only for the waffle switch that was implemented temporarily, before the condition around ADU existed.

**Comment by eviljeff** [comment]
>  the 'Approved' and 'No Sign-off' states were used only for the waffle switch that was implemented temporarily, before the condition around ADU existed.

They're still used, but only momentarily from when the approval is issued (or the determination that dual signoff is unnecessary), until the cron job has finished and the `Block` instances created.  When kinto integration is enabled the jobs will take more time to finish so admins might see those states more frequently.  (If a submission stays in those states its an indication something went wrong)
