### ISSUE TITLE
Move from debian-buster (prev testing) to rolling testing

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13487]
We do have one feature that relies on the most recent features to be available and that's our `libmagic` integration.

Another one depends on an up-to-date libgit2 library - see #13391 

Let's move from an explicit debian buster - which we're currently using - to simply using debian testing to have a rolling target.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I believe this is a qa "not needed" ?
