### ISSUE TITLE
The Input Guids field from Block submissions detail view doesn't expand when clicked 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13485]
### Describe the problem and steps to reproduce it:
1. Log in with an admin account
2. Open a block submission detail page - https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocksubmission/66/change/
3. Click on the Input Guids field at the top of the page

### What happened?
Nothing happens
### What did you expect to happen?
The field should expand to expose the original list of guids used in a block submission

**Comment by eviljeff** [comment]
This is deliberate - if you click it then it expands to show what the original list of guids were in case you want to bulk delete them or similar.

**Comment by AlexandraMoga** [comment]
@eviljeff nothing happens when I click on that field, hence my belief it was left there unintentionally. 
If the field was supposed to expand then the purpose of this issue can be changed.

![2020-02-14_08-40-26](https://user-images.githubusercontent.com/31961530/74507735-f9a51d80-4f05-11ea-8ea9-eeee58131afa.gif)

**Comment by eviljeff** [comment]
Looks like there's a javascript load failure (that doesn't occur in local development)

**Comment by eviljeff** [comment]
The problem is that `/en-US/admin/models/jsi18n/` - the javascript file that handles translations in Django - is blocked by our strict CSP that disallows javascript from outside of the CDN.  

`{% url 'admin:jsi18n' %}` is loaded on most of the django admin templates and `gettext()` from it is used in the snippet of javscript that adds the show/hide link.

Added complication - if we just add `/en-US/admin/models/jsi18n/` to the CSP definition then it won't work for non en-US locale requests.

**Comment by Abhi-khandelwal** [comment]
Hello @eviljeff, can I take this issue?

**Comment by eviljeff** [comment]
> Hello @eviljeff, can I take this issue?

what's your fix?

**Comment by diox** [comment]
For our own pages in addons-server we replaced django's dynamic js18n view by a generated file for each locale that is served by the static host, with a query string to cachebust (So it looks like `
https://addons.cdn.mozilla.net/static/js/i18n/en-US.js?b=2f8e7bf4-5e459a61`)

In the admin though... using the same strategy would require altering the templates that include that script. It's a bit tricky, but we could find a way to do that. 

Or, more simply... do we care about translations in the admin ? I'd say no, so maybe we could hack the base template to include our i18n static js, which should contain the functions we need. The django one would still not load but the page should work.

**Comment by eviljeff** [comment]
I suppose we just need to override the url django adds to the admin https://github.com/django/django/blob/2.2.10/django/contrib/admin/sites.py#L256 to a view that calls our own `jsi18n` url with a query string appended.  Or yeah, just hack a simple bit of js that has a trivial `gettext` function so it doesn't django admin's js doesn't fail.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![2020-03-04_15-21-14](https://user-images.githubusercontent.com/31961530/75883751-2cb73e80-5e2c-11ea-9069-ef663d944197.gif)
