### ISSUE TITLE
Don't force a refresh on a new BlockSubmission when changing the min/max unless nessecary

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13480]
Currently if the min/max versions are changed for a multiple guid submission we force a refresh to the page to update the list of existing Blocks that would be impacted by the change.  Instead, we should make it more intelligent and don't do that if all the guids are new guids.  (i.e. no existing Blocks are referenced).   To make it clearer we might want to explicitly show a validation error to make it clearer what's happening.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

- the block submission from requires one single Save if all added GUIDs represent new blocks even if the version range is changed
- the form needs to be Saved twice if the list of GUIDs contains an existing block which is affected by a version range change. In this case, a message is displayed to highlight why the changes to the Proposed blocks happened:

![image](https://user-images.githubusercontent.com/31961530/75249720-775b0a00-57df-11ea-9eba-9301965629ce.png)
