### ISSUE TITLE
Remove references to the 'Staff' group

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13497]
The _Staff_ group is going away, let's remove referencing it from the code.

QA:
* Test that the reviewer tools leaderboard still works. (`/reviewers/leaderboard/`)
* Test that the weekly reviewer report emails are still sent (1 for code-review, 1 for content-review, every Monday morning)

**Comment by AlexandraMoga** [comment]
I did some testing on -dev around this but I couldn't find any bad consequences after the group removal. 
I had a user that used to be in the Staff group. Apart from losing access to all the relevant tools that were being granted by this group, there were no issues observed.

The reviewer leaderbord can still be accessed and changes to reviewer points are reflected accordingly. 
The two reviewer report emails were also sent on Monday morning.

Based on these results, I'm marking the issue as verified fixed.
