### ISSUE TITLE
Cannot submit webextensions in Developer Hub

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#13491]
Steps to reproduce:
1. Go to https://addons.mozilla.org/en-US/developers/addon/submit/distribution
2. Try to submit a valid webextension

Expected results:
Validation is passed without issues

Actual results:
Validation never ends

NOTES: 
Was not reproducible on Stage today

**Comment by diox** [comment]
Fixed by #13492

**Comment by vcarciu** [comment]
Verified as fixed during sanity yesterday.
