### ISSUE TITLE
Add option to include disabled addons in code-search

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13490]
For some use cases it would be useful to have an option upfront to include disabled addons in the code-search, for example during the creation of a rule.

Since that can have significant impact on the performance, it should be off by default.

**Comment by AlexandraMoga** [comment]
I've submitted several add-ons on -dev (both listed and unlisted) and targeted a specific rule.  Then, I've Forced Disabled some of them and created a scanner query rule that would also identify disabled add-ons.
After the query run, the Forced Disabled add-ons were present in scanner query results.

I've created a second query rule, this time excluding disabled add-ons. After the query run, Forced Disabled add-ons were no longer identified.

I'm marking this issue as verified fixed on -dev.
