### ISSUE TITLE
Deleting a group fails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13508]
### Describe the problem and steps to reproduce it:

STR:
1. Create a user group
2. Add some users to it
3. Try to delete the group. 
### What happened?

```
'Cannot delete or update a parent row: a foreign key constraint fails (`addons_dev_allizom_org`.`log_activity_group`, CONSTRAINT `log_activity_group_group_id_e03ab8c8_fk_groups_id` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`))'
```

### What did you expect to happen?

Group is successfully deleted.

### Anything else we should know?

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/7296022/?query=is:unresolved

**Comment by liangyo6** [comment]
Can I work on this?

**Comment by diox** [comment]
You can but this is not a mentored bug, you'd be on your own regarding how to reproduce and fix this.
