### ISSUE TITLE
"Strange" chars in Register form for password length under 8 chars 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1351]
Steps to reproduce:
1. Load Register page in AMO-stage  https://addons.allizom.org/en-US/firefox/users/register
2. Complete all mandatory fields but type a shorter password than allowed (i.e. 5 chars)
3. Click "Register" to record the new user

Expected results:
The message "Must be 8 characters or more." is displayed under the password field in the page language. (i.e. English)

Actual results:
For some lengths (2, 5, 7 chars) the message is displayed using Japanese chars.

Notes/Issues:
Reproducible for any selected language. 
Verified on FF43(Win 7). Issue is reproducing on AMO-stage and dev.
Screencast for this issue:  
![2016-01-13_1845_001](https://cloud.githubusercontent.com/assets/15685960/12301372/492992d6-ba28-11e5-9ad6-0506084543a9.png)

**Comment by muffinresearch** [comment]
Appears to be in the POST response. So looks to be server-side.

**Comment by muffinresearch** [comment]
Looks to come from here: https://github.com/mozilla/olympia/blob/master/apps/users/forms.py#L38

**Comment by muffinresearch** [comment]
I think this is gone now with the move to FXA.
