### ISSUE TITLE
[Reviewer Tools] Fixed Generic Title isn't informative

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#13510]
It seems all the pages have the same generic `title`

`<title>Reviewer Tools :: Add-ons for Firefox</title>`

**Comment by gabbyprecious** [comment]
Has anyone worked on this? Is it still open?

**Comment by jvillalobos** [comment]
@gabbyprecious yes, the issue is open

**Comment by avgupt** [comment]
Raised a PR: https://github.com/mozilla/addons-server/pull/14035
