### ISSUE TITLE
Add addon_install_source_url to the abuse report field rendered in the related admin views

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-server#13511]
### Describe the problem and steps to reproduce it:

As a followup to #13465, the property `addon_install_source_url` of the abuse reports submitted to AMO should be rendered as part of the related admin views.

**Comment by rpl** [comment]
Hey @diox, this is the followup of #13465, @vcarciu was looking into verify [Bug 1610844 - Include navigated page in add-on abuse report](https://bugzilla.mozilla.org/1610844) today and he noticed that the property is not yet visible.

**Comment by ioanarusiczki** [comment]
@diox 
- the Addon install source url field is available in admin tools dev on /admin/models/abuse/abusereport/25466/change/ into the Abuse Report section and at the bottom of the page.
- I sent using Postman string type values and the field was populated. The maximum number of chars allowed is 255. If I'm sending some long unbroken string at one point it would break the layout of the page but I don't think this is a real scenario (there's a scroll bar that could help in that case). 
- The Abuse report from rev tools looks worse for unbroken strings, my example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/snacork5678. In case I should file an issue let me know.

**Comment by diox** [comment]
You can file a follow-up for places where we don't break strings for abuse reports - I suspect it will also happen for other fields, and we can force word-wrapping to handle that.

**Comment by ioanarusiczki** [comment]
@diox I filed the issues, one on admin tools and the other one for rev tools and I tried to give as much details as I could. 
While testing with the API the strings issues I found 2 parameters which I don't think I've seen as being added as data fields in the abuse report - detailed pages.  

addon_name (string|null) – The add-on name in the locale used by the client.
addon_summary (string|null) – The add-on summary in the locale used by the client. 

I can't tell if they're needed or not. Let me know if I should file an issue.

Thanks!

**Comment by diox** [comment]
> addon_name (string|null) – The add-on name in the locale used by the client.
> addon_summary (string|null) – The add-on summary in the locale used by the client.
> I can't tell if they're needed or not. Let me know if I should file an issue.

Currently we don't care and use what we already have in the database about the add-on. That may change in the future, but it's good enough for now.
