### ISSUE TITLE
Prevent deleting an existing block if its guid is present in a Block Submission

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13520]
Follow up for #13283 

### Describe the problem and steps to reproduce it:
1. Log in with an admin account
2. Open the list of exiting blocks in admin tools and edit one of the entries (make sure that your selection meets the criteria for sign off requirements)
3. Try to delete the block while it's still pending for sign off

### What happened?
The block can be deleted

### What did you expect to happen?
A block that is pending for sign off can't be deleted either from its detail page or the list view:
- for the detail page we should hide the Delete button
- for the list view we should show an error message when someone tries to delete the block
- for the multilock delete option we should show an error message when one of the input guids is present in a block submission

### Anything else we should know?
- if the deleted block is approved as part of the sign off process, a new entry for that block will be created in  the block list

**Comment by eviljeff** [comment]
Is this still valid?  I thought I implemented this (but so many blocklist issues...)

**Comment by AlexandraMoga** [comment]
@eviljeff yes, this is still valid now (unfortunately)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

While a block is pending for sign off, it can no longer be deleted:
- the Delete button is hidden on the block detail page
- if the guid is present in a multiblock deletion, an error is received 


![image](https://user-images.githubusercontent.com/31961530/78136490-5d3ec800-742c-11ea-8403-5584e03522d3.png)
