### ISSUE TITLE
Change delete version warning message to make it clear reviews won't be removed too

### ISSUE THREAD

**Issue by mojtabadaneshi** [mozilla/addons-server#13535]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Go to a addon listing versions
Delete a version of your addon
A popup will show include a warning that 1 file and X reviews will remove
Click on Yes button.
### What happened?
Version will remove but related reviews still remain.
### What did you expect to happen?
I except all related reviews to deleted addons remove as warning message notify about this action.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Please after fixing it, run a query to remove old reviews that should delete.
https://discourse.mozilla.org/t/bug-in-dashboard/54195/2

**Comment by jvillalobos** [comment]
The expected behavior is probably that the message should be removed, since we're no longer tying reviews/ratings to specific add-on versions. I think we stopped deleting them because of that change.

**Comment by caitmuenster** [comment]
Mentor: @willdurand

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

[Before]
![image](https://user-images.githubusercontent.com/31961530/82184561-8807b180-98f0-11ea-8def-52a0fa0e3cbe.png)

[After]
![image](https://user-images.githubusercontent.com/31961530/82184680-b5545f80-98f0-11ea-966e-2d6bc22b8125.png)

**Comment by dnutiu** [comment]
I made a PR for this: https://github.com/mozilla/addons-server/pull/14221
