### ISSUE TITLE
Submit new version: Warning sources missing

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#13534]
Hello,
I got several times this case.
Developers are submitting a new version of their add on. In past versions, they were uploading sources correctly. 
But not on the new one, it is impossible to us as reviewers to proceed to the review and have to ask the developer to upload sources of this new version. Which is slowing down the process.

It would be interesting to at least warn developers that they are not uploading sources like past versions, without blocking the workflow as it can happen.

@kewisch

**Comment by eviljeff** [comment]
thoughts @jvillalobos - I'm not sure where this warning would go (if we want one)

**Comment by jvillalobos** [comment]
I think we have a step in the upload process that reminds developers about this every time they submit a new version. Right, @wagnerand? Maybe this is about API submissions?

**Comment by wagnerand** [comment]
Correct, the devhub has this, but API does not suggest it nor does it even have an option to do it. There are a couple of open issues about it:
* https://github.com/mozilla/sign-addon/issues/409
* https://github.com/mozilla/addons-server/issues/9913

**Comment by eviljeff** [comment]
oh, I thought it was that the devhub warning was easy to miss.

**Comment by wagnerand** [comment]
> oh, I thought it was that the devhub warning was easy to miss.

It's now a separate step int he submission process that forces you to click either "yes" or "no" in order to proceed.

**Comment by jvillalobos** [comment]
Since supporting source uploads are already covered elsewhere, I think what we need is to add a reminder on `web-ext`. I don't know if there's anything filed in that repo for it. /cc @rpl

**Comment by rpl** [comment]
> Since supporting source uploads are already covered elsewhere, I think what we need is to add a reminder on `web-ext`. I don't know if there's anything filed in that repo for it. /cc @rpl

@jvillalobos I was wondering:
1. do we plan to always warn the user about that when they use `web-ext sign` to sign a new version? (maybe only if `web-ext sign` has been called with `--channel=listed`)
2. or the server is going to return something when we should be warning the user?

`1` would be something that we could easily do on the `web-ext` side, for `2` we would likely need to cover it on the `sign-addon` dependency first (and then use it in `web-ext`)

**Comment by jvillalobos** [comment]
I think doing `1` is good. I believe that step is shown regardless of the distribution channel, but @wagnerand can confirm. The message could be something like:

> Please remember that you may need to submit your source code along with your add-on file in order to meet Mozilla's source code submission policy (https://mzl.la/3bzqaTD). This applies to all add-ons with minified or generated code. You can upload your sources by navigating to your latest uploaded version in the Developer Hub (https://addons.mozilla.org/developers/).
