### ISSUE TITLE
Scanner query rule stuck in Running mode

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13533]
### Describe the problem and steps to reproduce it:
1. Create a new scanner query rule
2. Save the rule and Run it
3. Refresh the page several times until the number of identified results doesn't increment anymore
4. Check the rule State 

### What happened?
The Rule is still in a Running state
 
### What did you expect to happen?
The rule State is Completed

### Anything else we should know?
There is no guarantee that the above steps will trigger the issue. In my particular case, I was creating  query rules to verify #13490. The first two rule runs have completed successfully. At the third attempt, the rule run remained stuck. 
This is the rule in question: [link to query rule](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerqueryrule/20/change/)

**Comment by willdurand** [comment]
It's probably an issue in -dev only because we auto-deploy new `commits` on `master` all the time and that kills the celery workers and it (sometimes) breaks the existing celery tasks without any error we can cath.
