### ISSUE TITLE
Content reviewers can't review some old add-ons

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#13532]
Two add-ons have showed up recently which I, as a content reviewer, can't content-approve.

https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/soundfixer
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/turn-off-the-lights

The first was already fixed (by approval by an admin). Tthe second is currently on the content review list but the Approve Content action results in:

https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/turn-off-the-lights#review-actions
Oops! Not allowed.
You tried to do something that you weren't allowed to.

Expected result: The action to return to https://reviewers.addons.mozilla.org/en-US/reviewers/queue/content_review#review-actions an the add-on should no longer be listed.

**Comment by diox** [comment]
So you can access both pages, but it's the action that causes the error in both cases ?

**Comment by diox** [comment]
I don't have reviewer permissions anymore, so I can't reproduce the exact issue myself, but both add-ons are recommended, which I bet is where the problem is coming from.

**Comment by bjherbison** [comment]
Interesting. There was no easy way for me to see it was recommended because https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/turn-off-the-lights only includes "recommend" in the text of a bad user rating.

So the Approve Content link should be disabled and have a mouse-over that says "You aren't allowed to content-approve recommended add-ons". (Or better yet, not show it in the content review queue for users who can't review them.)

**Comment by AlexandraMoga** [comment]
The fact that a recommended add-on ends up in the Content review queue looks like a regression from https://github.com/mozilla/addons-server/pull/13192 which re-enabled content review on metadata changes.

However, it is still not very clear how a user with only Review:Content permissions was able to actually open the review page for those add-ons. I tried with a content reviewer on -dev but I received the 404 when I tried to open the add-on content review page.

**Comment by wagnerand** [comment]
The user also has `ReviewerTools:View`, which I think we added a while ago to mitigate some other access issue.

**Comment by bjherbison** [comment]
The situation has changed. They still show up on the content review queue for me, but I can't review the content review page for the add-on. My current content review queue contains impulse-blocker .

**Comment by diox** [comment]
This is specific to that add-on and is in fact the same root issue which I intend to fix (That add-on has no auto-approved non-disabled versions, so reviewers with just `Addons:PostReview` or `Addons:ContentReview` are unable to see it currently).

**Comment by diox** [comment]
@bjherbison can you still reproduce this ?

**Comment by bjherbison** [comment]
As of yesterday there were no add-ons in this state. (I'm still working through the overnight build-up.)

This isn't something I can reproduce by myself. From previous comments it recommended depends on content changes being made to recommended add-ons.

I will try to remember to add a message here if I see it again.

**Comment by AlexandraMoga** [comment]
@diox in https://github.com/mozilla/addons-server/issues/13532#issuecomment-588222982 I've identified that recommended add-ons can end up in the content review queue when their metadata is being changed. It is very likely that the issue occurred in prod comes from the same regression. I could file a separate issue with clear STR.

**Comment by diox** [comment]
No Need for STRs. Backing up for a second:

> They still show up on the content review queue for me, but I can't review the content review page for the add-on. 

https://github.com/mozilla/addons-server/issues/13566 should have fixed this sub-issue. So now, we're back to the original problem: content-reviewers are able to see the content review page of recommendable add-ons, but can't content review them. That is expected: the issue is that they shouldn't see recommendable add-ons in their queue in the first place.

**Comment by AlexandraMoga** [comment]
>  the issue is that they shouldn't see recommendable add-ons in their queue in the first place.

that's also the point I was trying to make, but probably I haven't been specific enough

**Comment by diox** [comment]
No no you're right and I got it, just wanted to clarify. *Technically* this is not a regression per se because the content review queue never excluded recommendable add-ons, it's just that before #13192 it was impossible for them to ever end up in that queue, since they had a content review at some point by just having their version manually approved.

@wagnerand Should we content review recommended add-ons as normal ? Currently content review of those addons, like regular review (which takes care of both code & content), is reserved for users with `Addons:RecommendedReview`, should we change that ?

**Comment by wagnerand** [comment]
> @wagnerand Should we content review recommended add-ons as normal ? Currently content review of those addons, like regular review (which takes care of both code & content), is reserved for users with `Addons:RecommendedReview`, should we change that ?

I don't think we need to change. It's also very unlikely that a recommended add-on would end up in the content review, since add-ons usually have been on AMO for quite some time and thus are already content-reviewed by the time they are becoming recommended extensions.

**Comment by diox** [comment]
See discussion above: because of #13192 they can end up in the content review queue if their metadata changes, and that has caused some confusion. So I can either exclude them from that queue, or let content reviewers content review them.

**Comment by wagnerand** [comment]
To keep things feasible, let's allow content-reviewers to content-review recommended add-ons. At some point we should add a prominent visual indicator so that content-reviewers can't miss that they're reviewing a recommended add-on.

**Comment by diox** [comment]
Alright, so this should be possible following changes made for https://github.com/mozilla/addons-server/issues/13566. Re-open if that's not the case.

**Comment by AlexandraMoga** [comment]
I've double checked that a regular content reviewer can indeed Approve/Reject content for an approved Recommended add-on. This should cover the metadata changes edge case discussed above.

**Comment by bjherbison** [comment]
The last reply is incorrect. A regular content reviewer can't Approve/Reject content for an approved Recommended add-on.

This morning the content review list includes https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/decentraleyes and above the action bar is an orange bar saying "This is a recommended extension. You don't have permission to review it." and the action bar doesn't include "Approve Content".

**Comment by diox** [comment]
Yes, this was changed since on purpose. See https://github.com/mozilla/addons-server/issues/13806

**Comment by bjherbison** [comment]
> Alright, so this should be possible following changes made for #13566. Re-open if that's not the case.

Based on this previous comment this issue should be reopened. Or should I create a new issue to get recommended add-ons removed from the content review queue?

**Comment by diox** [comment]
We considered that the warning you get + the action not being present was enough.

**Comment by bjherbison** [comment]
What happened this morning: I selected an add-on from the content review list, reviewed the content, looked at some of the version history, and then was given a nice orange banner telling me I had wasted my time.

And now when I review the content list I have to remember the name of the add-on I can't review from the list. I already too many things I need to remember, adding something to my memory list when a computer can handle it is an unnecessary distraction for me.

No, putting items on a work queue that don't belong on the work queue and then saying "oops. sorry" is not an acceptable solution.

**Comment by diox** [comment]
Please file an issue, we'll see what we can do.

Some background as to why we went for this instead of filtering in the queues: Because the reviewer tools are full of legacy code, with lots of edge cases everywhere, any big changes like filtering data from the queues according to various criteria has the potential to become a huge time sink for AMO developers and QA. I already spent a lot more time than I should have fixing the myriad of edge cases around permissions in https://github.com/mozilla/addons-server/issues/13566, so we tried to avoid modifying the queues for now as we have limited resources available to work on this. Evidently what we went for wasn't good enough, though, and I'm sorry, I had truly hoped the warning would do the trick.
