### ISSUE TITLE
Update links on autogenerated submission email

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#13543]
A few links on the autogenerated add-on submission email (found in the file`https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/email/submission.txt`) should be updated to point to Extension Workshop. 

* `https://developer.mozilla.org/Add-ons/AMO/Policy/Reviews` should be changed to `https://extensionworkshop.com/documentation/publish/add-on-policies/`

*  `https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Resources_for_publishers` should be changed to `https://extensionworkshop.com/documentation/manage/resources-for-publishers/`

**Comment by victorphoenix3** [comment]
Hi! I'd like to work on this issue.
