### ISSUE TITLE
Re-implement individual Block deletion

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13555]
while implementing dual sign off for deleting multiple Blocks (#13086) I decided to disable per-Block deletions because it'd bypass the dual sign-off.  It's a nice feature to have though (otherwise you have to copy&paste the guid for the Block into the multiple delete text field) so we should reimplement that in a dual-sign-off-friendly way.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The Delete button is present again on a block detail page, which enables admins to delete an individual block.
Individual block deletions are passing through the dual sign-off process the same as multiblock deletions.
