### ISSUE TITLE
Long unbroken string type values break the layout on addon review and abuse report pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13551]
Followup for https://github.com/mozilla/addons-server/issues/13511#issuecomment-588293381

STR:
1. I used the [Abuse Report API ](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#submitting-an-add-on-abuse-report)and I could populate data fields for the reviewers/review/ and reviewers/abuse-reports/ pages
The following API parameters sent with long unbroken string type values can break the layout of the page: "addon_install_origin","addon_install_source_url", "addon_version", "message", appversion"

Examples:

Review pages:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/guaill-chilleahog-dover
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/4564guaill-chilleahog-dover

Abuse report pages:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/snacork5678
https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/4564guaill-chilleahog-dover

**Comment by caitmuenster** [comment]
Note: to fix this bug, you need to install the add-ons server (described on our onboarding wiki:  https://wiki.mozilla.org/Add-ons/Contribute/Code).

**Comment by junngo** [comment]
Hello :)
Someone try to solve this issue can be easier to approach If there is screenshots.
I'm sorry to bother you. If you have a time, Could I ask you to upload the screenshot?
Thanks.
