### ISSUE TITLE
Block History should be more specific about the pending changes for a specific block

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13577]
Follow up for #13089 

### Describe the problem and steps to reproduce it:
1. Go to the admin block list view
2. Open the edit page of a block with changes pending, i.e an edited or a deleted block pending for sign off (see [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/1043/change/))
3. Check the Block History to see if there are any pending changes for this block

### What happened?
You can see that the block is pending for sign off but you can't immediately tell for what action, i.e an edit or a delete. Even if you click on the 'Changes pending' link to view the pending block submission, there is no clear indication of the action that triggered the need for sign-off
### What did you expect to happen?
The Block History should be more specific about the changes pending for a specific block
### Anything else we should know?
There are some messages proposed for each pending state in https://github.com/mozilla/addons-server/issues/13089#issue-536479859

[Current view]
![image](https://user-images.githubusercontent.com/31961530/75323897-7af19e00-587e-11ea-99e4-ab55381d0305.png)

**Comment by AlexandraMoga** [comment]
The block history will display additional details now when a block is pending for sign off, such as: changes to version ranges, reason, url and the actual pending reason (Add/Change or Delete)

Block pending for changes:
![image](https://user-images.githubusercontent.com/31961530/79959273-99de6c00-848c-11ea-9345-f27e3a4356eb.png)

Block pending for deletion:*
![image](https://user-images.githubusercontent.com/31961530/79959298-a2cf3d80-848c-11ea-9d94-2e982dc07f56.png)

*when you look at the changed fields you'll see that the values are reset. For example, `min_version` is reset to `0`, reason is reset to empty etc

**Comment by eviljeff** [comment]
> when you look at the changed fields you'll see that the values are reset. For example, min_version is reset to 0, reason is reset to empty etc

tbh, I didn't mean that to show the extra detail for deletions because we don't actually change those properties.  I don't suppose it matters too much though.

**Comment by AlexandraMoga** [comment]
> tbh, I didn't mean that to show the extra detail for deletions because we don't actually change those properties. I don't suppose it matters too much though.

yeah, at first I thought this was an issue worth for a follow up, but it's fairly minor. If admins will find that confusing, we should consider fixing it.
