### ISSUE TITLE
Make some reviewer links visible even when add-on is deleted and use new add-on admin page for status

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13580]
Some links in the right navigation bar on the review tools page are unavailable when the add-on is deleted, and they should be available:

* Listed Review Page (if there are/were listed versions)
* Unlisted Review Page (if there are/were unlisted versions)
* Admin Page: This used to link to a custom add-on status admin page, which is indeed unavailable if the add-on is deleted. However, that page is deprecated and the functionality has been added to the django admin add-on page, which is available evnn if the add-on is deleted. So, we should update the link as well.

And while we are updating the link to the admin page on the review tools page, we should update the same link on the developer hub page, which has a similar navigation bar on the left.

**Comment by ioanarusiczki** [comment]
@wagnerand 

I verified this on AMO dev with FF73(Win10):
- when the add-on is deleted from admin tools the listed and unlisted review pages will show the Actions section. This is an example of a deleted add-on which had a listed and an unlisted version:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/manthease-mosel-codcanzee2
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/manthease-mosel-codcanzee2

- the admin page link has been replaced on the review pages and dev hub menu into
/en-US/admin/models/addons/addon/618860/change/ where status can be edited by the admin.

I've tested with an admin account. If I should try with another user type, perhaps an Addon Reviewer, please let me know.
