### ISSUE TITLE
Django admin add-on page misses locale keys for fields like name

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13587]
### Describe the problem and steps to reproduce it:

When going to a django admin add-on page, all localized strings for localized fields are listed, but we're not showing what locale the localized string belongs to.

### What happened?

Missing locale key (the name of the locale for the localized string)

### What did you expect to happen?

Showing the locale key.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@diox If I understood this right, when I go to admin/models/addons/addon/503019/change/ the localized fields such as Name and Summary should show the language.  Perhaps I should re-check a little later?

![the language](https://user-images.githubusercontent.com/33448286/75450332-46add880-5977-11ea-99d2-68e6117dc528.png)

**Comment by diox** [comment]
Looks like it hasn't deployed yet. I did 2 commits in quick succession, the first one just to unbreak the test suite and the second one I merged my changes, and it looks like dev autodeploy missed the second one

**Comment by ioanarusiczki** [comment]
@diox Same today. Can I change the milestone with 05.03.2020?

**Comment by diox** [comment]
I initially intended to cherry-pick that but eventually didn't. I've corrected the milestone.

**Comment by ioanarusiczki** [comment]
@diox I verified this on dev with FF73(Win10). 
I filed a followup here https://github.com/mozilla/addons-server/issues/13599
