### ISSUE TITLE
Split translations per locale in Elasticsearch instead of per analyzer

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13591]
When storing translations in Elasticsearch, and then querying them, we store them per `analyzer`. We have different language analyzers enable, like one for english and one for french for instance, and so when an add-on has an `en-US` and a `fr` translation for its name, it's stored as `name_l10n_english` and `name_l10n_french`. We also have a field without analyzer for the translation in the default locale the developer chose for their add-on.

The problem with that approach is that it merges translations for all english-based locales we support into a single field: `en-US`, `en-CA` and `en-GB` all end up in that `english` field. That is causing various issues with relevancy.

We should have one field per locale instead.

The drawback is, if an add-on only has translations in `en-US` and `fr`, and the default locale is `fr`, if I look for it in `en-GB` I might not find it at all. Maybe there should be a special case for languages like English and Portuguese where we support different variants - we could simply store a duplicate value if there is nothing, or better yet have a fallback for those locales (could be done with a `DisMax` looking in multiple locales for those languages).

**Comment by diox** [comment]
> The drawback is, if an add-on only has translations in `en-US` and `fr`, and the default locale is `fr`, if I look for it in `en-GB` I might not find it at all. Maybe there should be a special case for languages like English and Portuguese where we support different variants - we could simply store a duplicate value if there is nothing, or better yet have a fallback for those locales (could be done with a `DisMax` looking in multiple locales for those languages).

I implemented that idea locally but in the end I don't think that's a good thing, because it would still be possible to have an exact match in en-CA that would be hidden from most users while still affecting relevancy. Furthermore, the original scenario quoted above is not correct: we always look in the default locale anyway, so it wouldn't be so bad. When we do this, we don't use a language-specific analyzer, but I don't think this would be too big of an issue.

**Comment by diox** [comment]
> The drawback is, if an add-on only has translations in en-US and fr, and the default locale is fr, if I look for it in en-GB I might not find it at all. Maybe there should be a special case for languages like English and Portuguese where we support different variants - we could simply store a duplicate value if there is nothing, or better yet have a fallback for those locales (could be done with a DisMax looking in multiple locales for those languages).

FYI I went with the fallback approach.

**Comment by diox** [comment]
**QA:** A reindex is needed to execute those scenarios. Before doing it, try various searches to see if they work. Then ask us to force a reindex, and try searching for addons with different translations set up for their name, description, summary, and make sure the addons are found as expected. In particular, test the following scenarios:
**Scenario 1:**
- Create an add-on with "Something" (*) as the name in an english locale. Add a translation for all other english locales (en-US, en-CA, and en-GB) with that same value. Add a summary and description that don't contain this word. 
- Create an add-on with "Something" (*) as the name in an english locale, but just no other translations.  Add that word in description but not summary.
- Create an add-on with "Something" (*) as the name in an english locale, but just no other translations. Add that word in summary but not description
- Search for "Something" (*). You should find the 3 add-ons, in reverse order (the first one should have the word in name and summary, the second in name & description, the third in name in all english locales).

**Scenario 2:**
- Create an add-on with name set to "Foo" (*), with default locale set to something else than english, like `ro` maybe. Then add a translation in `en-us` with value "Bar" (*).
- Search for "Foo" (*) or "Bar" (*) while in en-GB locale: you should find the add-on.

Play with translations and searches in various ways to find more edge cases I wouldn't have thought about :)

(*) Change this to a different word if you want to obviously, but ideally pick something unique so that you see those add-ons first in the results.

**Comment by AlexandraMoga** [comment]
@diox here are my results after having verified this on -dev (after re-index).

**Scenario 1** (slightly different than expected)
I've created two add-ons for each case, to make sure the results are being consistent.
This is the search query: https://addons-dev.allizom.org/en-US/firefox/search/?q=milo
1. [1st](https://addons-dev.allizom.org/en-US/firefox/addon/milo5/?src=search) and [2nd](https://addons-dev.allizom.org/en-US/firefox/addon/milo6/?src=search) position - addon with same name for `en-US`, `en-CA` and `en-GB`; term used in name _is not_ present in summary or description
2. [3d](https://addons-dev.allizom.org/en-US/firefox/addon/milo/?src=search) and [4th](https://addons-dev.allizom.org/en-US/firefox/addon/milo2/?src=search) position - both add-ons have the queried term in name and summary in the default locale (en-US)
3. [5th](https://addons-dev.allizom.org/en-US/firefox/addon/milo1/?src=search) and [6th](https://addons-dev.allizom.org/en-US/firefox/addon/milo4/?src=search) position - both add-ons have the queried term in name and description in the default locale (en-US)

**Scenario 2** (working as expected)
[Add-on](https://addons-dev.allizom.org/fr/firefox/search/?q=kodama) with default locale set to `fr` and another translation for `en-US`; name is different in these two locales -> add-on can be found from all other locales when searching by the default (`fr`) name; when searching by the name set for `en-US` , the add-on can be found only when the page is set to `en-US`, `en-CA` or `en-GB`

**Edge case:**
An add-on with default and only locale in `en-GB` or `en-CA` which has the `term` used to test Scenario 1 both in name and summary, can be found when searching from `en-US` _but_ it will change its position in search results each time the page is refreshed. This is the add-on, currently set to invisible to avoid the edge case when validating Scenario 1 - https://addons-dev.allizom.org/en-US/firefox/addon/milo3/?src=search

As for the case described in the original issue, it seems it can still be reproduced. 
For [this search query](https://addons-dev.allizom.org/en-US/firefox/search/?q=worldwide%20radio),  the second search result uses the queried term in `en-CA` as name and summary:

![image](https://user-images.githubusercontent.com/31961530/78050031-6ecc9500-7384-11ea-8756-b545a6415497.png)
