### ISSUE TITLE
Handle updating an existing block with a regex

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13598]
When we import a block from the v2 blocklist that contains a regex in the guid field we expand the regex to a separate Block instance for each matching guid.  This is correct (and what we want).  What is currently undetermined is the behaviour if that block was to be updated or deleted - if changing a single block on AMO results in changes to a block on kinto that targetted multiple guids then we're making unexpected changes; if we create a new block (for updates) then the existing block remains.

Options:  (user == the admin user making blocklist changes)
 
1.  Don't make changes on kinto to blocks imported from a regex - add a warning message and expect the change to be manually made via kinto admin webui by the user.  Simplest to implement but places an extra burden on the user; leaves kinto admin webui as a dependency until v2 blocklist is decommissioned.  (If the user didn't make the change via kinto admin, or made a mistake while doing it, then the v2 blocklist wouldn't match what was on AMO and wouldn't be a subset of v3)

2. Attempt to replace the existing regex block on kinto with multiple single guid blocks.  More complex (so more edge cases and bugs) and could make adding the blocks take a lot more time; Expanding the blocks could significantly (and inadvertently) increase the size of the v2 blocklist - e.g. a deleting a block on AMO that was imported from a kinto block that was a regex covering 100 guids would mean deleting the existing kinto block and adding 98 new block records.

I don't think adjusting the existing regex automatically from AMO is a feasible option.

(1) would be the option to choose if we think editing/deleting existing blocks in the v2 blocklist will be a rare task; (2) would ease the administrative burden if it was a frequent task - but at the cost of complexity and bloating the v2 blocklist.

**Comment by eviljeff** [comment]
@jvillalobos @wagnerand

**Comment by wagnerand** [comment]
I'm ok with doing (1) if the period where we run v2 and v3 isn't very long (say less than half a year).

I agree that (2) is too complex and probably not worth the effort given it is supposed to be of use for a transitional period only.

**Comment by jvillalobos** [comment]
Yeah, (1) sounds like the most reasonable approach, at least given the current plan of shipping v3 on ESR. If that changes we will need to re-evaluate.

**Comment by AlexandraMoga** [comment]
I've found some blocks coming from a regex submission among the guids that were batch imported on -dev.
The edit page for these blocks will show the following warning:
![image](https://user-images.githubusercontent.com/31961530/76619531-c9b45e80-6533-11ea-8ac4-0a13c45455fc.png)

The editing and sign-off part (if applicable) are still working as before.
