### ISSUE TITLE
Decide/Confirm/Set sign-off policy in AMO admin tool

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13618]
Dual sign-off has an active daily user threshold (setting `DUAL_SIGNOFF_AVERAGE_DAILY_USERS_THRESHOLD`) under (`<=` actually) which sign-off is bypassed, and over (`>`) is enforced.  An add-on with `0` adu also forces dual sign off to take into account unlisted only add-ons where statistics are absent from AMO's database (until #13123) 

Currently it's 100k. Before we launch we should confirm that 100k is the right level. If it's decided dual sign must be enforced for all submissions then it can be set to `-1`; if we don't want dual sign-off for _any_ submission on AMO (e.g. we're still going to sign-off via kinto) then it can be set to a very high number (more than 9 million would mean even every add-on today would fall under the limit)

**Comment by eviljeff** [comment]
@diox @jvillalobos I'm not sure who would make this call (or when), just filing so we're less likely to unintentionally overlook it

**Comment by jvillalobos** [comment]
100k is what was brought up a few times in our discussions with the Security people, and I think it's reasonable. I think @wagnerand has a regular meeting with them, so he can confirm they're okay with it.

**Comment by jvehent** [comment]
Is there any science to setting this limit, or are we going with gut feeling? (nothing wrong with gut feeling, but if we could sprinkle some science on it, that'd be good)

**Comment by jvillalobos** [comment]
Not super science-y, but [this chart](https://sql.telemetry.mozilla.org/queries/68987/source#174133) shows that AMO add-ons with over 100K users account for over 80% of total usage. This doesn't account for unlisted ones, but we know the distribution is similar (a small number of top add-ons take most of the users).

**Comment by jvehent** [comment]
That's actually pretty good science 👍 100k makes sense to me based on that data. r+

**Comment by eviljeff** [comment]
Looks like we're good as is then.
