### ISSUE TITLE
Investigate a/b-like handover for new stats pipeline

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13639]
This is just a thought and open for discussion but I'm wondering how we're going to proceed as part of making sure the new BigQuery-based pipeline works as we want it.

From what I see we should be able to hide the BigQuery-based pipeline behind a flag and let that run / test by QA, community and others for N days/weeks and keep our old pipeline running. Once that happened we should switch over 100% and stop the old pipeline.

**Comment by diox** [comment]
Behind a flag sounds good. The views already require auth for non-public data, so we could use a waffle flag and progressively enable that for users (maybe first staff, then people from a certain group, then all authenticated users, then everyone).

**Comment by EnTeQuAk** [comment]
Just for documentation: In one of our 1:1s we talked about implementing the views temporarily as new views as that'll make the whole comparing back and forth with old data much much easier and for stats pages I think new URLs should be bearable. Or we switch the URLs later, when testing is completed or something like that.

**Comment by willdurand** [comment]
> Just for documentation: In one of our 1:1s we talked about implementing the views temporarily as new views as that'll make the whole comparing back and forth with old data much much easier and for stats pages I think new URLs should be bearable. Or we switch the URLs later, when testing is completed or something like that.

According to this comment, I filed https://github.com/mozilla/addons-server/issues/14402
