### ISSUE TITLE
Investigate BigQuery sample data

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13638]
Just adding this issue to track the work easier.

Once https://bugzilla.mozilla.org/show_bug.cgi?id=1619492 has been setup I'll be able to investigate the sample data we already have and make sure it's what we need and then use that to figure out our process forward to see what needs to be done in addons-server to make use of that data.

**Comment by eviljeff** [comment]
clearing milestone (it's been bumped 4 times)

**Comment by willdurand** [comment]
Looks like we have pretty much everything we need, closing this issue now.
