### ISSUE TITLE
Update DevHub homepage footer links to align with the new Firefox download page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13656]
Follow up for https://github.com/mozilla/addons-frontend/issues/9089

### Describe the problem and steps to reproduce it:
1. Open Developer Hub homepage - https://addons.allizom.org/en-US/developers/
2. Check the links present in the page Footer (AMO footer)

### What happened?
The footer is still using the links used by the previous amo-frontend footer

### What did you expect to happen?
The footer should be updated to use the _Browsers_ and the _Products_ links present on the [Firefox download page](https://www.mozilla.org/en-US/firefox/new/) footer. 
![image](https://user-images.githubusercontent.com/31961530/76073941-1ed7f980-5fa3-11ea-8bdd-a2fff84e4777.png)

### Anything else we should know?
The UTM parameters used by the frontend footer links are  `utm_source=addons.mozilla.org&utm_medium=referral&utm_content=footer-link`
Also, the Footer should be aligned on three different columns.

[amo-frontend footer( _note that the Browsers column is still not updated_)]

![image](https://user-images.githubusercontent.com/31961530/76073991-3adb9b00-5fa3-11ea-9364-954ae351b5e5.png)

**Comment by AlexandraMoga** [comment]
This fix has introduced an alignment issue in the footer:

![image](https://user-images.githubusercontent.com/31961530/77055422-85183f80-69d9-11ea-923a-a126d066409d.png)

**Comment by AlexandraMoga** [comment]
The footer is back to its previous state. i.e. there are no more layout issues currently.
Keeping the issue open to wait for a proper fix.

**Comment by diox** [comment]
@championshuttler maybe you want to take another stab at this bug ? Be careful to avoid the problem @AlexandraMoga spotted by testing locally.

**Comment by championshuttler** [comment]
@diox will take a look this weekend :)

**Comment by caitmuenster** [comment]
Hey @championshuttler, just checking in on this. :)

**Comment by championshuttler** [comment]
Hi @caitmuenster , @kanurag94 is gonna create the PR. :)

**Comment by AlexandraMoga** [comment]
The footer alignment looks good now:
![image](https://user-images.githubusercontent.com/31961530/79233934-2af08a00-7e72-11ea-9505-56c8ba18e307.png)



The new added links are also redirecting correctly and have the right `utm` parameters set. 
There is a consistency issue with the footer links headers for which I've filed #13970 as a follow up.

Verified fixed on -dev on desktop and mobile.
