### ISSUE TITLE
Expose the file id for the base version in the compare endpoint

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#13650]
This is required for https://github.com/mozilla/addons-code-manager/issues/1472.

As discussed at https://github.com/mozilla/addons-code-manager/issues/1471#issuecomment-595233529, we want to be able to construct a URL to the legacy file viewer for a compare page in the new Code Manager, and in order to do so we need the file id for both versions involved in a compare operation. The file id for the head/new version is already exposed as `file.id`, but the file id for the base/old version is not currently exposed via the API response.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk The head/new version file id and base file id are available in the Compare API response. 
Verified on dev with Postman. 

![basefileid](https://user-images.githubusercontent.com/33448286/76965039-509a7a00-692c-11ea-9a27-e8d8f1f64fd0.png)
