### ISSUE TITLE
Slow query in stats_addons_collections_counts

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1366]
```
# Query_time: 39.064082  Lock_time: 0.000078 Rows_sent: 1051503  Rows_examined: 9697721
use addons_mozilla_org;
SET timestamp=1452609941;
SELECT `stats_addons_collections_counts`.`addon_id`, `stats_addons_collections_counts`.`collection_id`, SUM(`stats_addons_collections_counts`.`count`) AS `sum` FROM `stats_addons_collections_counts` GROUP BY `stats_addons_collections_counts`.`addon_id`, `stats_addons_collections_counts`.`collection_id` ORDER BY NULL;
```

39 seconds examining 9697721 rows for something. Tracker: #1244

**Comment by andymckay** [comment]
Should go away in #1395

**Comment by muffinresearch** [comment]
@diox do you know if this is still an issue?

**Comment by diox** [comment]
It is, but I'm not sure we can do much about it without a full revamp of statistics.

**Comment by EnTeQuAk** [comment]
The work in https://github.com/mozilla/addons-server/issues/5712 will probably help with this too. It's ongoing but very slowly since the migrations are quite heavy and hard to write / test. We'll get there :)

**Comment by diox** [comment]
This particular table was removed in ff235fa29298a27429ffbb371408608fea7c3b1e (model was removed in eba5e644224c832b28663142d27d107e272a792d)
