### ISSUE TITLE
Reviewers APIs now returning `null` for `addon.name`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#13665]
Both the Browse and Compare endpoints are now returning `null` for `addon.name`, whereas before they would return an object with localized strings. It seems like this started after https://github.com/mozilla/addons-server/pull/13658 landed, but maybe something else landed that caused this.

This breaks addons-code-manager on dev.

**Comment by diox** [comment]
I was a bit overzealous when it came to preventing extra queries and didn't notice those endpoints were returning the add-on name. I'll change the code to allow translations for the add-on and that should fix it.

**Comment by ioanarusiczki** [comment]
@diox For the Browse and Compare endpoints "name" returns the localized strings.

Examples: 
https://addons-dev.allizom.org/api/v5/reviewers/addon/502991/versions/1541836/
https://addons-dev.allizom.org/api/v5/reviewers/addon/503019/versions/1541869/compare_to/1690313/

- I could open and view the pages in code manager too. 

Verified on dev with FF73(Win10) with Postman.
