### ISSUE TITLE
EOL conversion should be ignored when comparing two versions

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#13662]
This compare url https://code.addons.mozilla.org/en-US/compare/920304/versions/4957090...4976235/ shows that all the codebase has been changed. This is because the dev uploaded a new version with converted EOL.

### What happened?
One example of this can be found at https://code.addons.mozilla.org/en-US/compare/920304/versions/4957090...4976235/?path=app%2Feventpages%2Fblock.html

In this file, only lines number 24 and 25 actually have real code differences. The rest is because of "0D 0A" to "0A" EOL convertions.

![image](https://user-images.githubusercontent.com/2171145/76017158-1ec8f280-5eec-11ea-8d5a-727971be0e03.png)

![image](https://user-images.githubusercontent.com/2171145/76017121-0b1d8c00-5eec-11ea-9c66-1f21377faad9.png)

### What did you expect to happen?
To have a result similar to the old review tool : https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/3520605...3501462/file/app/eventpages/block.html#top

**Comment by diox** [comment]
Yeah. I'll explore a little bit, we should be able to pass down the right flags to ignore whitespace.

**Comment by diox** [comment]
This works:
```diff
 diff --git a/src/olympia/lib/git.py b/src/olympia/lib/git.py
 index 8dfa9f2852..97df927038 100644
 --- a/src/olympia/lib/git.py
 +++ b/src/olympia/lib/git.py
 @@ -520,7 +520,9 @@ def get_raw_diff(self, commit, parent=None, include_unmodifed=False):
          """
          diff_cache = getattr(self, '_diff_cache', {})
  
 -        flags = pygit2.GIT_DIFF_NORMAL
 +        flags = (
 +            pygit2.GIT_DIFF_NORMAL | pygit2.GIT_DIFF_IGNORE_WHITESPACE_CHANGE
 +        )
  
          if include_unmodifed:
              flags |= pygit2.GIT_DIFF_INCLUDE_UNMODIFIED
```

Do we want to this enabled all the time ?

**Comment by diox** [comment]
Let's assume we want this enabled all the file for now, for parity with the old file viewer where it's not optional.

**Comment by ioanarusiczki** [comment]
@diox This issue is a bit hard for me to understand it since I don't have access in production. Could you add some STR, I believe there's something I should be looking for in the compare API?

**Comment by diox** [comment]
STR:
- Submit an add-on
- Submit another version with several changes to the existing files, including some changes that are only whitespace
- Look at the compare view for both versions in code manager

Actual:
- Whitespace changes show up

Expected:
- Whitespace changes should not show up, rest of the changes should.

**Comment by ioanarusiczki** [comment]
@diox If I leave white spaces at the end of the lines, or the last codeline they are not interpreted as changes. Also white spaces are not interpreted as changes if I inserted them before or inside the code lines.

An example: 

![The lines](https://user-images.githubusercontent.com/33448286/76511315-b3d36a80-645b-11ea-933a-44956a21f339.png)
