### ISSUE TITLE
Update strings that contain the term 'obfuscated' on the source code submission page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13677]
Follow up for #13416 

The Source code submission page - `/src/olympia/devhub/templates/devhub/addons/submit/source.html` - has two strings that still refer to 'obfuscated' code:

```
30:    <li>{% trans %}Code minifiers or obfuscators{% endtrans %}</li>
```

```
67:    Source files (aside from open-source third party libraries) cannot be transpiled, obfuscated, minified or otherwise machine-generated.
```

@wagnerand for the first occurrence, should 'obfuscators' be replaced with something else or eliminated altogether?

**Comment by wagnerand** [comment]
> Follow up for #13416
> 
> The Source code submission page - `/src/olympia/devhub/templates/devhub/addons/submit/source.html` - has two strings that still refer to 'obfuscated' code:
> 
> ```
> 30:    <li>{% trans %}Code minifiers or obfuscators{% endtrans %}</li>
> ```

Let's use `Code generators or minifiers`
