### ISSUE TITLE
Rename "ml_api" to "mad" (or "mad_api")

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13676]
This is a clean-up issue to replace the "ml_api" placeholder with the codename of the... ML API we'll be using soon.

**Comment by AlexandraMoga** [comment]
I've verified that the previous `ml_api` is now referenced as `mad` in scanner results, scanner rules and scanner rule creation. 
I've also made some add-on submissions just to verify that there are no obvious regressions on that side.
