### ISSUE TITLE
Deprecation warning htmlparser.unescape

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#13689]
```
src/olympia/activity/utils.py:246

  /home/travis/build/mozilla/addons-server/src/olympia/activity/utils.py:246: DeprecationWarning: The unescape method is deprecated and will be removed in 3.5, use html.unescape() instead.

    comments = htmlparser.unescape(comments)
```

**Comment by junngo** [comment]
I submitted PR :)

**Comment by junngo** [comment]
Hello, @eviljeff
Could I ask you about Lables?
I often solved issue on `contrib:welcome`. But, There are many `contrib: outreachy` labels now.
Can I try to solve issue on `contrib: outreachy`? Or Should I refrain from it?
I ask it for a good community.

**Comment by eviljeff** [comment]
> 
> 
> Hello, @eviljeff
> Could I ask you about Lables?
> I often solved issue on `contrib:welcome`. But, There are many `contrib: outreachy` labels now.
> Can I try to solve issue on `contrib: outreachy`? Or Should I refrain from it?
> I ask it for a good community.

No, we're reserving those issues for applicants to https://www.outreachy.org/ for now (after the selection period is over we'll likely re-label them as contrib:welcome)

**Comment by junngo** [comment]
I knew today that there was a good program.
Thanks for letting me know :)
