### ISSUE TITLE
Update auto-approval message

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13692]
We want to update the auto-approval message to reflect some updates on the policy side. The following sentence should be removed: _In that case, you will be notified again with details and next steps._

**Comment by ioanarusiczki** [comment]
@wagnerand The sentence is no longer available. Verified on dev with FF73(Win10). 

<img width="784" alt="autoapproval" src="https://user-images.githubusercontent.com/33448286/76410606-e23c4180-6398-11ea-9bf3-6511220c3407.png">
