### ISSUE TITLE
submit kinto records as `to-sign` rather than `to-review`

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13701]
according to https://bugzilla.mozilla.org/show_bug.cgi?id=1619994#c6 when there isn't dual sign-off needed we need to set a different state to allow the /stage/ bucket records to signed by kinto and propagated to the live /blocklist/ bucket

**Comment by AlexandraMoga** [comment]
@eviljeff should I verify that "no sign-off" blocks added/changed in AMO will not require additional Approval in kinto, i.e. the block is directly published and listed in https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons/records ?

**Comment by eviljeff** [comment]
if testing on kinto stage, yes.  If testing on kinto dev the records will just stay in the existing https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections/records collection but the metadata in https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections should show "status": "to-sign" instead.

**Comment by eviljeff** [comment]
testing on kinto stage is a better end-to-end solution but is blocked on https://github.com/mozilla-services/remote-settings-permissions/pull/112 being merged though.

**Comment by eviljeff** [comment]
I've realised there's a bug on dev if both submitting to legacy kinto and mlbf are enabled at the same time.  Only the first kinto update would work (I'll fix next week)

**Comment by AlexandraMoga** [comment]
Is there any progress on https://github.com/mozilla-services/remote-settings-permissions/pull/112? I don't have access to the issue to check the status myself.

Meanwhile, I've submitted a few "no sign-off" add-ons on -dev and checked the status in https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections, but I'm still seeing `"status":  "to-review"` instead of  `"to-sign"`

![2020-03-18_1050](https://user-images.githubusercontent.com/31961530/76970828-197c9680-6935-11ea-8c90-ad7b5409ec73.png)

**Comment by eviljeff** [comment]
my fix in #13735 was broken (and the tests too apparently or it would have been caught 🐼 )

**Comment by eviljeff** [comment]
> Is there any progress on https://github.com/mozilla-services/remote-settings-permissions/pull/112? I don't have access to the issue to check the status myself.

It's merged now (as of a few hours ago)

**Comment by AlexandraMoga** [comment]
I've seen that the status changed on -dev from `to-review` to `to-sign` but I guess I'll have to wait until the latest fix from #13772 is available on stage to be able to do an end to end test on kinto.

**Comment by eviljeff** [comment]
> I've seen that the status changed on -dev from `to-review` to `to-sign` but I guess I'll have to wait until the latest fix from #13772 is available on stage to be able to do an end to end test on kinto.

#13772 is dev only.

**Comment by AlexandraMoga** [comment]
@eviljeff does it mean that stage is supposed to work now? If that is the case, I'm not having the behavior described in https://github.com/mozilla/addons-server/issues/13701#issuecomment-598656329

I've added a no sign-off block on AMO stage but in kinto that record is still pending for Approval:

![image](https://user-images.githubusercontent.com/31961530/77180710-fdaef700-6ad2-11ea-81b1-407dbe05478c.png)


I thought this block should be automatically approved and directly published to https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons/records

**Comment by eviljeff** [comment]
> I thought this block should be automatically approved and directly published to https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons/records

I thought so too but apparently there's more work on the kinto side to do.  It's being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1623984

**Comment by glasserc** [comment]
The behavior in https://github.com/mozilla/addons-server/issues/13701#issuecomment-601770197 is a bit strange for having set the status to `to-sign`. It looks more like a `to-review` status. It might be worth clearing that status manually once by declining the changes.

**Comment by eviljeff** [comment]
> The behavior in [#13701 (comment)](https://github.com/mozilla/addons-server/issues/13701#issuecomment-601770197) is a bit strange for having set the status to `to-sign`. It looks more like a `to-review` status. It might be worth clearing that status manually once by declining the changes.

From https://bugzilla.mozilla.org/show_bug.cgi?id=1619994#c6 I thought that's what needed to happen.  If not this issue needs re-opening and the correct way implementing.

**Comment by eviljeff** [comment]
@leplatrem did I do this correctly? -  I'm just setting `to-sign` on the collection (like we set `to-review` for collections that need signoff) after the record has been added/updated.  https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/kinto.py#L170

**Comment by leplatrem** [comment]
It seems correct.

I'm surprised you didn't use the kinto-http.py package! It's not mandatory as you could see, but it manages a couple of things, like precondition headers etc. 

And I don't know if it's too late, but I'd recommend removing the mentions of «kinto» (the implementation) in your code and replace them with «remote settings» (the service).

**Comment by eviljeff** [comment]
> I'm surprised you didn't use the kinto-http.py package! It's not mandatory as you could see, but it manages a couple of things, like precondition headers etc.

Does it handle setting `to-sign` or `to-review` - having to handle that was the annoying part.

**Comment by leplatrem** [comment]
> Does it handle setting to-sign or to-review - 

`client.patch_collection(data={"status": "to-review"})`

>  having to handle that was the annoying part.

I don't understand. Why?

**Comment by leplatrem** [comment]
>> having to handle that was the annoying part.
>>
> I don't understand. Why?

Ok, I guess the complication comes from the fact that your code supports both cases where signoff is enabled or disabled

**Comment by leplatrem** [comment]
https://github.com/mozilla-services/remote-settings-lambdas/blob/287351f32350db48d9bdf3ceadaa4d8c132c0d54/commands/backport_records.py#L110-L122

**Comment by eviljeff** [comment]
> And I don't know if it's too late, but I'd recommend removing the mentions of «kinto» (the implementation) in your code and replace them with «remote settings» (the service).

eventually ended up doing this in #14347
