### ISSUE TITLE
Implement API to fetch details about blocks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13706]
API side of https://github.com/mozilla/addons-frontend/issues/9216

The API only needs to fetch details about a specific block, not list them. It needs to support fetching by add-on `guid` + version or legacy block ID.

**Comment by AlexandraMoga** [comment]
I've verified the [blocklist api](https://addons-server.readthedocs.io/en/latest/topics/api/blocklist.html#get--api-v4-blocklist-block-(int-block_id|string-guid)) on -dev and I have the following results:

- a block can be queried by the add-on `guid` or by our internal block `id` (exposed in the block detail URL)
- the api response exposes the internal block `id`, created and modified dates, min-max version range, add-on `guid`, block reason and URL
- when trying to fetch a deleted block, the api responds with a 404

@eviljeff  has the initial request to support fetching by the legacy block ID been dropped?

**Comment by eviljeff** [comment]
> @eviljeff has the initial request to support fetching by the legacy block ID been dropped?

yes, for now https://github.com/mozilla/addons-frontend/issues/9216#issuecomment-600303607
