### ISSUE TITLE
Improve the list of scanner results by removing some less essential information

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13717]
The list of scanner results has too many results and on small-ish screens, it is impossible to see everything. Let's see how we can improve the situation.

List of changes in the list of scanner results and in the list of scanner query results:

- the `channel` column has been removed
- the `created` date has a less verbose format
- the `channel` and `version` are displayed below the add-on name

List of changes in the list of scanner results only:

- the `state` column has been removed
- the action buttons have been renamed

List of changes in the detail page of a scanner result:

- the `channel` row has been removed
- the `channel` is below the add-on name (similar to how it is displayed in the list)
- the action buttons have been renamed

**Comment by diox** [comment]
Note: when I added authors, I tweaked the CSS a little bit, and maybe this could be adjusted as well to waste less space.

**Comment by willdurand** [comment]
> Note: when I added authors, I tweaked the CSS a little bit, and maybe this could be adjusted as well to waste less space.

This seems to only be used for the list of scanner query results.

The changes described in the description above are for both scanner results and query results.

**Comment by AlexandraMoga** [comment]
I was also going to suggest to make the Action buttons narrower by removing the "Mark as" parts.
Example:

![image](https://user-images.githubusercontent.com/31961530/76535168-1db33a80-6483-11ea-9137-6bc36facdf9b.png)

**Comment by willdurand** [comment]
That's a good idea!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The scanner results and scanner query results list view layout is more compact and easier to read, i.e there's no horizontal scrollbar on the page anymore. 

The changes to the `channel` and `Version` positions are also visible on a scanner detail page, both for normal and query results. 

![image](https://user-images.githubusercontent.com/31961530/76622208-b906e700-6539-11ea-91b5-c9ccd8be67c5.png)
