### ISSUE TITLE
Is the "1 Password X" extension for Firefox "recommended" or "not recommended"?

### ISSUE THREAD

**Issue by JonPaque** [mozilla/addons-server#13711]
I am a 1Password trial user, and was following directions to install the "1Password X" extension onto my Firefox browser.  I found, however, that Firefox states on its 1Password X extension webpage -- https://addons.mozilla.org/en-US/firefox/addon/1password-x-password-manager/ -- that "This is not a Recommended Extension".  In Firefox's initial Ad-Ons webpage -- https://addons.mozilla.org/en-US/firefox/ -- Firefox shows this app in the "Recommended password managers" grouping.  Thus, is it recommended or not?  More so, is it safe/secure?  I noted some users have been frustrated in trying to install and use the extension.  Should I expect to deal with glitches and/or security issues?  Thank you in advance for any information/guidance you might be able to provide!

**Comment by diox** [comment]
@devaneymoz this collection https://addons.mozilla.org/en-US/firefox/collections/4757633/password-managers/ should be updated to remove `1Password X` or renamed since that add-on is not recommended.

**Comment by willdurand** [comment]
@JonPaque sorry, it turns out that the issue was not technical but some sort of editorial confusion: the add-on was previously recommended but it is not anymore so we should have removed it from the list of "recommended password managers". This will be fixed shortly, thanks!

**Comment by devaneymoz** [comment]
Thank you for raising this issue! It was my oversight not removing 1Password X from the Password Managers collection when the extension was removed from the Recommended program. The collection has been updated.

**Comment by khari05** [comment]
Hi there, I haven't found any articles on this. Why was 1Password removed from the Recommended program?
