### ISSUE TITLE
Clean up unused code around opensearch plugins

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13729]
We [stopped accepting](https://github.com/mozilla/addons-server/issues/12462) and then [disabled all opensearch plugins](https://github.com/mozilla/addons-server/issues/12463).

To clean things up we should now remove all dead code related to opensearch plugins: there is a lot of special handling since they weren't extensions. 

To get started one can [set up addons-server locally](https://addons-server.readthedocs.io/en/latest/topics/install/index.html) and then try renaming `ADDON_SEARCH` constant in `src/olympia/constants/base.py` to `_ADDON_SEARCH` and see what tests break. Ultimately all code using that constant should probably be changed. Some classes, functions, tests can be entirely removed.

**Comment by ajinkabeer** [comment]
Hey @diox, I am outreachy applicant. I would like to take work on this issue if that's alright. :)

**Comment by junngo** [comment]
Can I work on it?

**Comment by ajinkabeer** [comment]
Hello, I am an outreachy applicant. If this issue is still unassigned, I would like to take a look at it, please?

**Comment by bhushan-borole** [comment]
Hello, I would like to work on this issue.

**Comment by diox** [comment]
Feel free to start working on it and submit a PR when you're ready. It should be relatively straightforward as it's mostly about removing code.

**Comment by bhushan-borole** [comment]
For running the tests, the command is `make test` right ?

**Comment by diox** [comment]
Yes.

**Comment by bhushan-borole** [comment]
> Yes.

Basically removing the part of the code, which uses this variable right?

**Comment by diox** [comment]
Per description:

> Ultimately all code using that constant should probably be changed. Some classes, functions, tests can be entirely removed.

This is a `contrib: welcome` issue and not a `contrib: good first bug` issue so while I'll be happy to review a pull request I won't go into too much more details, you'll need to exercise judgement to figure out what can be removed exactly.

**Comment by diox** [comment]
This is getting in my way so I'm taking it.

**Comment by AlexandraMoga** [comment]
@diox do you have any specific STR for verifying this issue? I was planning to verify various add-on submissions and the Developer Hub mostly.

**Comment by diox** [comment]
> I was planning to verify various add-on submissions and the Developer Hub mostly.

Yeah, just a general sanity check around add-on & versions submissions should be enough.

**Comment by AlexandraMoga** [comment]
I haven't found issues with add-ons and version submissions.

I'm marking this issue as verified fixed on stage.
