### ISSUE TITLE
Make changes to allow AMO to manage legacy blocklist with no kinto signoff

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13725]
Currently Block submissions via AMO admin are submitted to the /staging/ bucket and need to be signed off via kinto admin - even if AMO has already enforced a second sign off.  This is inefficient and inconsistent (v3 blocklist bloom filters won't require a second signoff).

On the kinto side there would need to be a change in their config to disable dual sign-off for the blocklist/addons collection (and likely prevent other users from submitting/changing blocks via kinto admin).

On AMO side it could be just passing `kinto_sign_off_needed=False` to the `KintoServer` object, but potentially we will need to sign the record first?  Confirmation TBD

**Comment by eviljeff** [comment]
If we do need signing we can reuse the aborted work in https://github.com/mozilla/addons-server/pull/13699

**Comment by eviljeff** [comment]
Because there are some types of Block (the ones with regular expressions) that AMO won't update there will still be a need for admins to be able to modify kinto records via kinto admin.  

From Slack:
> @eviljeff 
is it possible to have a collection that has sign-off disabled for some users (actually just one user - the AMO user) but still has sign-off for other users?  Or otherwise a way for AMO to push updates to a collection without signoff (e.g. push directly to the main collection) while keeping it for others (e.g. they continue to push to preview).
@glasserc 
No, I don't think so
I guess there's the concept of editors and reviewers, but I don't see how we could apply them to do what you want

This issue might end up being a wontfix

**Comment by eviljeff** [comment]
I think there are two ways this could work:
- a kinto change to allow dual sign-off to be bypassed for specific users while keeping the collection requiring dual sign-off for other users.
- a hack around dual sign-off whereby AMO has a second user account that it uses to sign-off it's own submissions.  AMO would have to be trusted to correctly apply this.

**Comment by eviljeff** [comment]
@jvillalobos thoughts?  WONTFIX?

**Comment by wagnerand** [comment]
Depending on how long we are going to support v2, I'd prefer not to wontfix, if the effort for either approach is reasonable.

We can probably use the manual workaround for a couple of months, but if we are going to support v2 past 2020, we should implement either approach.

**Comment by jvillalobos** [comment]
The [current migration plan](https://docs.google.com/document/d/12wGjFjscu2pixwt795aHAyoswHsQzztzVUzWjiQz4vg/edit#), assuming we successfully hit 78, would freeze the v2 blocklist in September 2020. If we WONTFIX it sounds like the administrative effort during that time period is equivalent to the current one. We'd just be entering the blocks on AMO instead of Kinto, and then doing the approval on Kinto as we do now.

That said, if the dual sign-off hack on AMO is feasible I would be in favor of doing it. I wouldn't consider it a high priority since we have sensible alternatives.

**Comment by eviljeff** [comment]
we aren't doing this any longer.  https://github.com/mozilla/addons-server/issues/14094 (and linked issues) will be done done instead.
