### ISSUE TITLE
Add a link to retrieve all the add-ons of a given user in the scanner result detail pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13721]
We should add the following link to retrieve all the add-ons of a given user in the scanner result detail pages (next to the user info): `/en-US/admin/models/addons/addon/?authors=<user-id>`.

**Comment by Medlineme4** [comment]
@willdurand. I would like to contribute. How do I begin or see the full code?

**Comment by junngo** [comment]
Hello @Medlineme4
You can start contributing by viewing the documents below:
https://addons-server.readthedocs.io/en/latest/topics/install/docker.html

**Comment by Medlineme4** [comment]
The action should be in the scanner result detail pages

**Comment by Medlineme4** [comment]
@junngo. Thank you

**Comment by AlexandraMoga** [comment]
I've verified this feature on stage and I have the following results:

- the '[Other add-ons by these authors]' link was added in the following locations:  scanner results, scanner query results and scanner detail pages 
- the link will redirect to `/admin/models/addons/addon/?authors=<user-id>` and will show add-ons submitted only by that user (if the add-on has only one author)

@willdurand there seems to be a problem with the link when we try to fetch results for multiple users. If we have a query of multiple user IDs separated by a comma, the redirect falls back to https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/?e=1. I'm not sure what `e=1` stands for in this case, but anyways, the entire list of add-ons is returned, not just those submitted by these users.

Here is a scanner result that reproduces the issue: https://addons-internal.stage.mozaws.net/en-US/admin/models/scanners/scannerresult/2350/change/

**Comment by willdurand** [comment]
ugh, @wagnerand do you know why this is happening by chance?

**Comment by wagnerand** [comment]
I am not sure passing multiple users to the URL is supported. Would be nice if we added that.

**Comment by AlexandraMoga** [comment]
@willdurand I'll file file a follow-up and maybe you'll find a solution to this case eventually.

**Comment by willdurand** [comment]
> @willdurand I'll file file a follow-up and maybe you'll find a solution to this case eventually.

ok cool, thanks
