### ISSUE TITLE
Force-enable an add-on should set its status to Incomplete

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13746]
### Describe the problem and steps to reproduce it:

Follow-up of https://github.com/mozilla/addons-server/pull/13739#discussion_r393689628.

The Reviewer Tools button "Force-enable add-on" currently sets the status to `STATUS_APPROVED`. With change made in the patch linked above, this would leave the add-on in an invalid status since all files are disabled.

### What happened?

Clicking `Force-enable add-on` sets the add-on status to `STATUS_APPROVED`.

### What did you expect to happen?

Clicking `Force-enable add-on` sets the add-on status to `STATUS_INCOMPLETE`.

### Anything else we should know?

We should not change the status of any files as part of this. A human needs to make a decision case-by-case which file(s) to enable.

**Comment by willdurand** [comment]
@diox wrote on Matrix:

> I don't think we should change this. update_status() should already downgrade status if necessary
> so I'd wontfix the issue
