### ISSUE TITLE
Return the add-on name in the blocklist/block API response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13757]
We need the add-on `name` in the block API response so that the frontend can display it (see: https://github.com/mozilla/addons-frontend/issues/9216). Having the `name` in the response would avoid another API call (and because add-ons are blocked, it might not be easy to retrieve such information _via_ public APIs anyway).

@jvillalobos do we need any other information on the new (upcomping) block(ed) page?

**Comment by jvillalobos** [comment]
Assuming the version range and reason are already there, I think the `name` is all that's needed.

Another bit that's maybe unusual is that the `name` can come from an unlisted add-on, which is something we normally wouldn't expose, but we want to in this case.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/77182343-449dec00-6ad5-11ea-9712-6be5266aa195.png)
