### ISSUE TITLE
'Other add-ons by these authors' link will retrieve the entire list of add-ons when multiple authors are present

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13767]
Follow up for #13721 

### Describe the problem and steps to reproduce it:
1. Open the following scanner result - https://addons-internal.stage.mozaws.net/en-US/admin/models/scanners/scannerresult/2350/change/
2. Click on 'Other add-ons by these authors' link

### What happened?
The entire list of add-ons is retrieved. 

### What did you expect to happen?
A list of add-ons belonging only to the listed  authors is retrieved 

### Anything else we should know?
The initial attempt was to fetch the add-on list by adding multiple user IDs separated by comma in the request URL. However, this request will fall back to https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/?e=1

**Comment by willdurand** [comment]
Marking as p2 so that we can discuss it during the stand-up. Main questions are:

- can we actually pass a list of author IDs? (the name `authors` suggested that it was the case but obviously I did not double check)
- should we fix the current implementation by providing one link per user instead? (cherry-pick?)

**Comment by willdurand** [comment]
We decided to fix this in the next tag. A workaround is to edit the URL manually and only add one user ID in the query string (`?authors=1,2,3` => `?authors=1` or `?authors=2`, etc.)

**Comment by willdurand** [comment]
Ha, actually changing the query parameter name from `authors` to `authors__in` fixes the issue.

**Comment by willdurand** [comment]
> Ha, actually changing the query parameter name from `authors` to `authors__in` fixes the issue.

@ioanarusiczki could you manually try that to test?

**Comment by AlexandraMoga** [comment]
@willdurand I've tried your solution and indeed it seems to work.
In my example, having the link redirect to https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/?authors__in=11685651,11686381 will show only add-ons submitted by these authors.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage
