### ISSUE TITLE
implement Block stashing so we don't need a new MLBF each time

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13762]
Similar to what crlite is doing (mozilla/crlite#53 mozilla/crlite#48) we should implement some sort of stash list of new blocks so we don't have to generate a new bloom filter - and the client doesn't have to download an entire new filter - each time a new block is added.  

things tbd:
 - How often we should build a new filter  (every x days?  every x new blocks?)
 - Should we still look to build a new filter, or update the stash list, on a 6 hour schedule or on demand each time a Block is created/updated?
 - Format: crlite creates a binary format blob containing the new items and uploads it as an attachment every day.  IMO json is more straightforward (at the cost of only a few extra bytes for `"`s and `,`s) - we could upload that either as an attachment or directly as data on the record.  Alternatively could have a record per stashed block, at the cost of extra overhead per record.
- storage location.  crlite places both the filter and the stash blobs in the same collection so the client can just download (or diff) the entrire collection.
- stash list deletion policy.  crlite's strategy is to clear the collection - both stashed items and previous filter - each time a new filter is available.

I guess we'll have to always rebuild the filter for Block deletions (and we'll need to take care with Block updates if the min/max versions change) unless we want a un-stash list too(!)

**Comment by diox** [comment]
> - How often we should build a new filter (every x days? every x new blocks?)
> - Should we still look to build a new filter, or update the stash list, on a 6 hour schedule or on demand each time a Block is created/updated?

Haven't thought this through, but how about:
- For the stash list, update either on demand or on 6 hours schedule (*)
- For the bloom filter, update every x weeks or y new blocks or blocks gets deleted/updated

I don't think we should build a new filter on schedule anymore if we do the stash list, cause we don't want clients to have to download it, right ?

(*) If we do it on demand, we need to make sure we can deal with failures

> - Format: crlite creates a binary format blob containing the new items and uploads it as an attachment every day. IMO json is more straightforward (at the cost of only a few extra bytes for "s and ,s) - we could upload that either as an attachment or directly as data on the record. Alternatively could have a record per stashed block, at the cost of extra overhead per record.
> - storage location. crlite places both the filter and the stash blobs in the same collection so the client can just download (or diff) the entrire collection.
> - stash list deletion policy. crlite's strategy is to clear the collection - both stashed items and previous filter - each time a new filter is available.

JSON + attachment sounds good. But I'm not sure I follow: CRLite has multiple stash lists, one per day ?

**Comment by eviljeff** [comment]
> I don't think we should build a new filter on schedule anymore if we do the stash list, cause we don't want clients to have to download it

If there's a release of Firefox that supports the v3 blocklist but _doesn't_ support stashing then we'll have to produce the full bloomfilter each time.  (Making that compatible will also require some thought)

> But I'm not sure I follow: CRLite has multiple stash lists, one per day ?

Yes.  (I think it's every day, it might be more frequent than that)  Each time there are new items but less than would require a new filter to be generated a new attachment is uploaded to kinto.  So the client would have to deal with multiple attachments with multiple extra blocks in.

**Comment by eviljeff** [comment]
Current thinking:
- for the collection we'll follow crlite's strategy - the collection is cleared each time a new bloomfilter is created, and stash lists are added as new records to the same collection.  This lets the client download the entire collection if needed and have an effectively up to date blocklist, and with remote-setting's diff functionality means it won't download all the records each time, only the new ones (with the extra blocks to stash)
- the stashes will be added on demand - i.e. each time some new blocks are created on AMO, a task will be fired to create a new kinto record with the new blocks as a stash.  This way the v3 blocklist (bloomfilter + stashes) will be as up-to-date as the v2 blocklist.
- if the total number of stashes (in all the records) is greater than a threshold (100? 500?) then we'll create a new bloomfilter instead. A new bloomfilter will always be needed in cases where blocks are removed (either single versions or entire addons).
- the stash will be encoded directly as JSON in the data section of the kinto record. 
```
{
  "data": {
    "blocks_stash": [
      "guid@foo",
      "guid@baa",
      ...
    ],
    ...
  }
}
```

**Comment by eviljeff** [comment]
> A new bloomfilter will always be needed in cases where blocks are removed (either single versions or entire addons).

This edge case gave me pause - if this happens frequently then we could potentially be building and uploading **a lot** more bloomfilters than our careful strategy would suggest.  And if each block is deleted one at a time, and the tasks are triggered on-demand, then we could be talking about many a day being generated.

If we care about this possibly we could:
a) throttle the new bloomfilters being created, at the expense of the bloomfilter being out of date, to one or two a day
b) delay the bloomfilter generation by X minutes (30?) to catch multiple changes being made at once.
c) something else?

**Comment by Rob--W** [comment]
> > A new bloomfilter will always be needed in cases where blocks are removed (either single versions or entire addons).
> 
> This edge case gave me pause

I immediately had the same reaction after seeing the proposed format. I was thinking of two lists in the kinto data, one with removals and one with additions (both relative to the last known MLBF data).

TLS certificates can only be revoked and not be un-revoked, that's why it doesn't make sense to have "unrevoke" functionality in crlite. Our case differs.

> If we care about this possibly we could:

Yes we do IMO.

> a) throttle the new bloomfilters being created, at the expense of the bloomfilter being out of date, to one or two a day
> b) delay the bloomfilter generation by X minutes (30?) to catch multiple changes being made at once.
> c) something else?

c. Anything against my suggestion?

**Comment by eviljeff** [comment]
spun out the stash file generation to #13945

**Comment by AlexandraMoga** [comment]
@eviljeff can you add a few guidelines on what should be tested here?
For example, where can I see the these stashes, should a new stash be created each time I'm adding/changing a block, what should happen in case blocks are deleted.
Also, how is `/collections/addons-bloomfilters/records` affected by this? Did we change the conditions and time intervals for new mlbf generation?

**Comment by eviljeff** [comment]
If there are block changes (new blocks; changes to existing blocks; block deletions) then when the next cron job runs (still every 6 hours) the following will happen:
- if there are more than 500 different versions (i.e. guid:version combinations that are either new and not in the bloom filter, or have been removed from the bloom filter) then the collection will be cleared and a single record with a bloom filter added (with the attachment-type `bloomfilter-base`).* 
- otherwise, a record will be uploaded with a `stash` property in the data that will have the guid:version additions or removals.  A separate record will be created with a bloom filter attachment too (attachment-type `bloomfilter-full`), for the scenario where we disable stashing support.

*This will also happen the first time after the code deploys and there has been a block change

Although you can see the records upload on dev, checking the records aren't cleared when stashing, etc, is probably only practical on stage because of the kinto-dev server daily clearances.

**Comment by AlexandraMoga** [comment]
> *This will also happen the first time after the code deploys and there has been a block change

I think that is the case for today's records, because I modified only a few versions and there has been only a single record with `attachment_type:  "bloomfilter-base"` generated. I'll probably need a few more days to cover the rest of the scenarios.

**Comment by AlexandraMoga** [comment]
I've checked the bloomfilter again today and I can see the two records generated, one as `"attachment_type": "bloomfilter-full"` and the `stash` record listing the new, changed or deleted blocks.

@eviljeff below are the stashed changes from today (12:30 UTC) and I have some observations:
1. looks like multiblock submissions are not recorder properly. I've submitted [this multiblock](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/226/change/) consisting of 5 new blocked guids, but the stash record includes only one of those guids - `addon@darkreader123.org` (which is also the first in the multiblock guid list)
2. for deleted blocks, should the stash record - `unblocked` section - include a separate entry for all the add-on versions that were unblocked - see `{97a711fd-3752-4481-905b-30e7078c5f29}` ?
3. regarding the `"{guid}:{version}"` combination, I notice that `{version}` refers only to the max version of the blocked add-on. If max version is not specified in the admin during the block submission, then the latest add-on version will be populated. Shouldn't the min version be included as well?

```
"stash": {
                "blocked": [
                    "jid1-NIfFY2CA8fy1tg@jetpack:3.4.1.1-signed",
                    "addon@darkreader123.org:4.9.4",
                    "{a42eb16c-2fab-4c06-b1f3-5f15adebb0e3}:8.1.1",
                    "CookieAutoDeleted@kennydo.com:3.1.1"
                ],
                "unblocked": [
                    "{97a711fd-3752-4481-905b-30e7078c5f29}:10.47",
                    "jaehkpjddfdgiiefcnhahapilbejohhj@chrome-store-foxified--1008973568:10.46",
                    "{97a711fd-3752-4481-905b-30e7078c5f29}:10.46"
                ]
            }
```

**Comment by eviljeff** [comment]
> looks like multiblock submissions are not recorder properly. I've submitted this multiblock consisting of 5 new blocked guids, but the stash record includes only one of those guids - addon@darkreader123.org (which is also the first in the multiblock guid list)

Actually, that's correct (and I'm happy it worked!) - only signed webextension files/versions within the min-max range are included.

```
rf-fireabc@siber.com
{5f01d7ac-fbfc-4f87-9a5d-cfc9d42b3de6}
{03e634e8-abc4-4e88-93c3-c33f40f7204b}
```
don't have any signed versions, and `{4f6cf33d-a455-439a-a776-d2d711325680}` only has one version, but it's outside the min-max range (min_version in the submission was 2 but the version was 1.22.2)

>    for deleted blocks, should the stash record - unblocked section - include a separate entry for all the add-on versions that were unblocked - see {97a711fd-3752-4481-905b-30e7078c5f29} ?
>
>    regarding the "{guid}:{version}" combination, I notice that {version} refers only to the max version of the blocked add-on. If max version is not specified in the admin during the block submission, then the latest add-on version will be populated. Shouldn't the min version be included as well?

The stash lists (and the bloomfilter) work on versions so there should be an entry for each version of the addon that is blocked within the min - max version range.  So if there were two versions that matched then we'd expect 2 entries; similarly with deletions - 1 entry per version that now wasn't in the blocklist.  This also means if the min/max version range of an existing Block was expanded/contracted then there could be `blocked` and `unblocked` entries.

**Comment by AlexandraMoga** [comment]
> Actually, that's correct (and I'm happy it worked!) - only signed webextension files/versions within the min-max range are included.

ah, yes. I forgot we implemented that a coupe of weeks back.

As for the version ranges, I'll try to experiment more with those.

**Comment by AlexandraMoga** [comment]
I've tested more around `"{guid}:{version}"` combinations and so far I can confirm the following:

- new block - one version, signed webextension => one entry is created in `stash - blocked`
- new block - multiple versions, signed webextension - fully blocked => one entry for each version is created in `stash - blocked`
- new block - multiple versions signed webextension - partially blocked => one entry for each version covered by the selected version range is created  in `stash - blocked`
- existing block - increasing the `max_version` => one entry for each additional versions covered by the `max_version` increase is created in `stash - blocked`
- existing block - choosing a higher `min_version` => one entry for each no longer covered versions  is created in `stash - unblocked`
- existing block - add-on is fully blocked - new version is uploaded by developer => a new entry for the submitted version is created in `stash - blocked`
- deleting a block - add-on was blocked for multiple versions => one entry for each version is created in `stash - unblocked`

These scenarios were covered both on -dev and stage. 
I'm still investigating this for other possible scenarios, so I won't mark the issue as verified fixed yet.
