### ISSUE TITLE
View product page link returns a 500 from the listed/unlisted review pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13778]
Followup for https://github.com/mozilla/addons-server/issues/13199

STR:
1. Load a page from admin tools from en-US/admin/models/addons/addon/1002608/change/
2. Click the REVIEWER TOOLS (LISTED) button 
3. Click the View Product Page link from Actions

Expected result:
The add-on detail page is loading without errors.

Actual result:
500 Internal Server Error

Notes:
This issue is reproducible on AMO dev and stage with FF74(Win10). 
If the listed review page is accessed from rev tools or the frontend the issue is not reproducible. 

the URL for listed review page accessed from admin tools:
https://addons-internal.stage.mozaws.net/en-US/reviewers/review-listed/many-weights-16-05-1

The URL from rev tools:
https://reviewers.addons.allizom.org/en-US/reviewers/review/many-weights-16-05-1

![view product page](https://user-images.githubusercontent.com/33448286/77052959-42a13380-69d6-11ea-8ad2-6c8506456998.gif)

**Comment by willdurand** [comment]
oh I see, mmm. I guess we should use `EXTERNAL_SITE_URL` in the admin.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on dev with FF74(Win10). 

![works for me1](https://user-images.githubusercontent.com/33448286/77310428-fcfea680-6d06-11ea-95e5-a178189c5338.gif)
