### ISSUE TITLE
Telegram Channel should be removed from Connect with us Section

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-server#13775]
Telegram Support is removed

https://addons.mozilla.org/en-US/developers/

**Comment by ioanarusiczki** [comment]
@championshuttler Telegram support is removed from Connect with us section for both - logged in and logged out views. - verified on AMO dev with FF74(Win10). 

![Telegram removed](https://user-images.githubusercontent.com/33448286/77299481-2dd5e000-6cf5-11ea-85f2-bf87f56e9672.png)
