### ISSUE TITLE
Broken link to other channel if add-on is deleted

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13779]
### Describe the problem and steps to reproduce it:

On the reviewer tools page, if the add-on is deleted, the "(Un)Listed Review Page" page links to `/reviewers/review/None`.

### What happened?

Broken link, see above.

### What did you expect to happen?

The link should go to the respective review page.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand I verified this on -dev with FF74(Win10). 

I tested it like this: I deleted an add-on from
https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1003947/change/

The review page:
https://reviewers.addons.allizom.org/en-US/reviewers/review/testingautoapproval has the link to "Unlisted Review Page" which redirects correctly to

https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/testingautoapproval

A couple of weeks ago there was a similar issue - I did back then the testing and I don't remember encoutering this problem so please let me know if the way I tested is alright.

**Comment by wagnerand** [comment]
@ioanarusiczki Looks good, thank you!

**Comment by ioanarusiczki** [comment]
@wagnerand Alright. I'll mark it verified on dev with FF74(Win10).
