### ISSUE TITLE
Force-enable will not change the status of the add-on correctly

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13780]
Looks like a regression caused by https://github.com/mozilla/addons-server/issues/13194

STR:
1. Go the the review page of an add-on and click the "Force disable add-on" button
2. Check in dev hub the status
3. Return to the review page and click "Force enable add-on"

Expected result:
The status will be "approved" and the versions will be enabled automatically.

Actual result:
Status remains "incomplete" with the versions disabled. 

Reproducible on dev and stage with FF74(Win10). 
The workaround would be to change the status for the add-on and the versions to "approved" from 
admin/models/addons/addon/494901/change/ page.

![force enable](https://user-images.githubusercontent.com/33448286/77059220-47b6b080-69df-11ea-9bba-818f733e00dc.gif)

**Comment by diox** [comment]
This is expected from the changes we made, this was an inconvenience @wagnerand was prepared to live with, since they don't manually re-enable often, and will manually change the affected files status first.

**Comment by ioanarusiczki** [comment]
@diox In that case, the button should be inactive and loose the "force-enable" state for good. I think it's worth filing the issue.

**Comment by diox** [comment]
No, the button is still useful: it will remove the `Disabled by Mozilla` state.

**Comment by ioanarusiczki** [comment]
@diox I've noticed that the state is "Incomplete". Is that ok?

**Comment by diox** [comment]
Yes, that is expected if all versions were disabled (on some old disabled add-ons that's not the case - for those, the add-on will become approved once re-enabled)

**Comment by ioanarusiczki** [comment]
@diox Ok. Noted. The behavior is different now, we'll change the expected result into the release test case. 
Thanks!
