### ISSUE TITLE
Remove Force-enable state from the review addon page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13781]
A followup for https://github.com/mozilla/addons-server/issues/13780
Because the force-enable state is no longer functional because of https://github.com/mozilla/addons-server/issues/13194

STR:
1. Load a review page for an add-on and force-disable the add-on
2. Observe the button

Expected result:
The button should be inactive after the operation or no longer available (like the clear add-on code review button)

Actual result:
The state turns to "force-enable" add-on.

Notes:
reproducible on dev and stage with FF74(Win10).

**Comment by diox** [comment]
As commented in https://github.com/mozilla/addons-server/issues/13780#issuecomment-601121134 the button is still useful even with its new limitations.
