### ISSUE TITLE
upgrade to latest filtercascade lib with new hashing algorithm

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13794]
blocked on ~https://github.com/mozilla/filter-cascade/pull/6~ (and releasing a new version of filtercascde to pypi)

The salt is now used directly in the bloomfilter so we don't need to prepend it to the key. We should also consider:
- stripping out some of the non-defaults when we initialize the filter too (it was based on the crlite code but probably unnecessary and causes a bug if the number of blocks exceeds the number of non-blocked addon versions - https://github.com/mozilla/filter-cascade/issues/8)
- removing the meta file save for export_blocklist (it's going anyway with https://github.com/mozilla/filter-cascade/issues/7)

**Comment by AlexandraMoga** [comment]
@eviljeff is there anything to be tested here?

**Comment by eviljeff** [comment]
nothing special.  Just make a change and see there's a kinto record with an attachment created on the normal schedule.  (the file should be roughly the same size as before)

**Comment by AlexandraMoga** [comment]
I've followed the last couple of records from https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections/addons-bloomfilters/records and I didn't notice anything out of the ordinary. I don't remember the size of past records, so I can't compare if there are any visible changes here. 
In any case, for a collection of 2 new blocks and a block edit, the size was 1857.
