### ISSUE TITLE
Restrict content review for Recommended Extensions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#13806]
Currently, all content reviewers can content review Recommended extensions. Instead, we only want this for users who also have permission to review Recommended extensions.

So, if a user has content review permission but no recommended review permission and is looking at the content review page for a Recommended extension:

* The page should not allow content review actions.
* A message should be shown: `You don't have permission to content review Recommended extensions.`

**Comment by jvillalobos** [comment]
Oh, forgot to reference the old issue that triggered this: https://github.com/mozilla/addons-server/issues/13532

**Comment by ioanarusiczki** [comment]
@diox 
 - content reviewers can't review recommended add-ons.

![cannot review recommended](https://user-images.githubusercontent.com/33448286/77551439-03358400-6ebb-11ea-8842-8f1522227fef.png)

- the recommended extension reviewers can approve or reject content for recommended addons. 

I've noticed that after approving or rejecting content the page looks contradictory, there's a confirmation of the content being approved and a 403 forbidden to https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/content_review

This category of users won't have an empty rev tools page - no queues available. 
Unlike the content reviewers these don't have the frontend "Content review add-on" link from the add-on detail page to access the content review pages.

![forbidden](https://user-images.githubusercontent.com/33448286/77552205-eb123480-6ebb-11ea-9fc2-919dfb7fe38f.gif)

**Comment by diox** [comment]
That's the typical edge case caused by users not having the right to view the queue they are redirected to, and that's fine - we don't expect recommended reviewers to not have content review permission, and we don't expect them to content review that often anyway (they should just do a full review).

**Comment by ioanarusiczki** [comment]
@diox Yes, @AlexandraMoga told me she encountered this issue and already discussed it with you. 
I'm marking this verified on AMO dev with FF74(win10).
