### ISSUE TITLE
in blocklist/block api url shouldn't be "/" if empty

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13812]
Follow up for mozilla/addons-frontend#9216 

### Describe the problem and steps to reproduce it:
1. Open the following blocked addon  page: https://addons-dev.allizom.org/en-US/firefox/addon-blocked/pt-BR-1971@dictionaries.addons.mozilla.org/
2. Click on the 'View block request' link 

### What happened?
You land on AMO homepage

### What did you expect to happen?
The 'View block request' link should be hidden in this case because the URL is empty

### Anything else we should know?
The API request for this page:
`/api/v4/blocklist/block/pt-BR-1971@dictionaries.addons.mozilla.org/`

![image](https://user-images.githubusercontent.com/31961530/77445341-a45a0700-6df5-11ea-9a27-200d63c4981d.png)

**Comment by eviljeff** [comment]
An empty string is pretty much what's expected - that's the default value.

**Comment by eviljeff** [comment]
Would you prefer `null` rather than an empty string?

**Comment by willdurand** [comment]
I don't mind the `null` vs empty string for an empty URL. The docs say it could be `null`: https://addons-server.readthedocs.io/en/latest/topics/api/blocklist.html, but empty string is fine.

The problem is that the API returns the value `/` for a block with an empty URL but only when the outgoing query param is added to the API URL.

**Comment by AlexandraMoga** [comment]
There is no trailing slash returned for `"url"` if the `wrap_outgoing_links=true` parameter is present:

` GET /api/v4/blocklist/block/gmailnoads@mywebber.com/?wrap_outgoing_links=true`

```
    "guid": "gmailnoads@mywebber.com",
    "min_version": "0",
    "max_version": "*",
    "reason": "addon with multiple locales",
    "url": ""
```

On the frontend side, the 'View block request' link is now hidden:

![image](https://user-images.githubusercontent.com/31961530/77767802-42460f80-704a-11ea-99fc-501e2c339359.png)
