### ISSUE TITLE
Block webextension files only

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13813]
Before an add-on version is added to the blocklist, AMO should check whether any files belonging to that version are both webextensions and signed.

If so, add the version to the list.
If not, skip it.

**Comment by eviljeff** [comment]
Only blocks that have a matching addon guid in the database would be imported so I assume these Addons exist in the database in some form/status.  Is this expected?

**Comment by wagnerand** [comment]
Yes, but not every single add-on/version/file that is in the database is also worth blocking.

If the file was not signed, we don't need to block it. Likewise, if the file is not a webextension, we don't need to block it either because all currently supported types of add-ons are some kind of webextension.

**Comment by eviljeff** [comment]
@jvillalobos were these addons/versions considered during the PRD stage (I couldn't remember anything but haven't re-read the docs) and does that sound reasonable?

**Comment by jvillalobos** [comment]
We should have disabled all legacy files on https://github.com/mozilla/addons-server/issues/9472, but I don't think we followed up on deleting them. Makes sense to filter by WE and being signed. Same for the unblocked versions being fed into the bloom filter, I think.

**Comment by eviljeff** [comment]
I'm going to split this issue into work on the `import_blocklist` command (not importing blocks that don't have _any_ valid versions on AMO); and work on creating the bloom filter (not including unsigned versions/files in the blocked list)  #13821 for the latter.

**Comment by AlexandraMoga** [comment]
@eviljeff has a new blocklist import been run on -dev or stage after this patch landed? Then, I could check there are no non-webext add-ons among the admin list of blocks.

**Comment by eviljeff** [comment]
I've just run it again on -dev (stage will be done sometime today).

note https://github.com/mozilla/addons-server/pull/13878 changed the collection name to match what the kinto admins had created for us.

**Comment by AlexandraMoga** [comment]
I've verified that the blocks re-imported on -dev were all webextensions.
