### ISSUE TITLE
only include signed/webext files when generating list of guid, version to block in mlbf

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13821]
split from #13813 
"not every single add-on/version/file that is in the database is also worth blocking.

If the file was not signed, we don't need to block it. Likewise, if the file is not a webextension, we don't need to block it either because all currently supported types of add-ons are some kind of webextension."

**Comment by AlexandraMoga** [comment]
@eviljeff would the following be a valid test method? 
- select a few add-ons that haven't been signed (I have several add-on with auto-approval delayed indefinitely, so It's certain they will not be signed)
- block the add-ons (making sure there are no other signed add-ons blocked in this time interval)
- verify that there is no new `/addons-mlbf/records` after the time is reset again

**Comment by eviljeff** [comment]
Mmm, I think this may be prohibitory difficult to QA.  There _will_ be a new record in `/addons-mlbf/records/` because the check is a simple one on the Block objects being updated (which they will have been) - an admin blocking an add-on with a single non-signed version is an unnecessary edge case.  The scenario it's designed for is when an add-on containing multiple versions - some unsigned - is blocked.   We can't even assert that the new bloomfilter would be the same size as the old one because it'll be rebuilt using knowledge of the all the add-ons at that point, potentially making it a different size than before.
