### ISSUE TITLE
Add links to reviewer tools on django admin add-ons by author view

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13843]
Similar to #13199, it would be helpful to admins to add a link to the listed/unlisted reviewer tools page (as applicable) to each row in the add-ons table on `admin/models/addons/addon/?authors=<id>`.

**Comment by ioanarusiczki** [comment]
@willdurand 
The listed/unlisted links are available from the mentioned page
https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?authors=10641574
Verified on admin tools dev - FF74(win10).
