### ISSUE TITLE
Hard-coded UID and GID in DockerFile causes permission error while setup

### ISSUE THREAD

**Issue by avgupt** [mozilla/addons-server#13857]
### Describe the problem and steps to reproduce it:
Follow the development setup instructions on a Linux user whose UID != 1000. 
### What happened?
On running `docker-compose up -d`, the web_1 and worker_1 containers get started and stops.
### What did you expect to happen?
All the containers should run fine.
### Anything else we should know?
Log of `docker-compose log` :
`Attaching to addons-server_web_1 web_1 | Traceback (most recent call last): web_1 | File "/deps/bin/supervisord", line 8, in <module> web_1 | sys.exit(main()) web_1 | File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 358, in main web_1 | go(options) web_1 | File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 368, in go web_1 | d.main() web_1 | File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 70, in main web_1 | self.options.make_logger() web_1 | File "/deps/lib/python3.6/site-packages/supervisor/options.py", line 1472, in make_logger web_1 | backups=self.logfile_backups, web_1 | File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 417, in handle_file web_1 | handler = RotatingFileHandler(filename, 'a', maxbytes, backups) web_1 | File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 213, in __init__ web_1 | FileHandler.__init__(self, filename, mode) web_1 | File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 160, in __init__ web_1 | self.stream = open(filename, mode) web_1 | PermissionError: [Errno 13] Permission denied: '/code/logs/supervisord.log'`

**Comment by avgupt** [comment]
@eviljeff @diox

**Comment by muffinresearch** [comment]
@avgupt how are you running docker. Are you running with a regular user with the docker group set as per these instructions https://docs.docker.com/engine/install/linux-postinstall/ ?

**Comment by diox** [comment]
This came up on Matrix, it's because we mount the repository clone in the container and to make that work we hardcode the uid of the user. That's a pretty rigid way of doing things and that is causing issues for people with multi-user setups or just a different uid than the default.

**Comment by avgupt** [comment]
@muffinresearch , as @diox pointed out the issue was due to the fact that my UID for the user for 1002. So as a workaround I did the setup on the user which had UID set as 1001 (which is hardcoded in the dockerfile), which worked for me.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/20472 fixed this - the UID/GID is set dynamically in the container depending on the host.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-32
