### ISSUE TITLE
Scanner results without matched rules, customs and MAD scores

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13861]
We will enable the MAD integration soon, which will add two things (among others):

- a new scanner named `mad` in the list of scanner results (containing the results coming from the API)
- a score will be added to the `customs` scanner results

Currently, we are not displaying the scanner results that do not have any matched rules, which means (1) `mad` results won't be listed (but that's fine for now, I guess) and (2) `customs` results won't be listed if there is no matched rule.

That's a problem because `customs` results will get a score that could be useful to admins, even if the scanner result does not have any matched rules. Admins would have to manually show scanner results without any matched rules.

One way to fix this problem would be to allow the creation of scanner rules based on the `score` field of a scanner result.

Currently, only `mad` and `customs` scanners have a `score` but the `mad` score is set to `-1` (`n/a`) because that's what the MAD service returns (and that is expected and documented). In other words, we would allow the creation of "customs scanner rules" based on the value of the `score` field.

(An alternative would be to show scanner results with a strictly positive score in the list, but we'll need some new rules to leverage the scores I believe)

WDYT?

**Comment by wagnerand** [comment]
What if we created a new queue-like page that would show add-ons sorted by score?
