### ISSUE TITLE
Content reviewers time is wasted by placing Recommended add-ons in the content review queue

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#13870]
Steps to reproduce:

1. Recommended add-on has content modified.
2. Automated process adds the recommended add-on to the content review queue.
3. Content reviewer picks item off of queue.
4. Content reviewer reviews the content and history of the add-on.
5. Content reviewer goes to the bottom of the page and sees a nice orange banner saying "you wasted your time, sucker".
6. Content reviewer goes back to the content review queue and has to remember which add-ons on the list can't be content reviewed because apparently that is too complicated for computer to handle.

Expected:
- Pretend you care about the time of content reviewers and don't put an add-on on the content review list if the add-on can't be content reviewed .

This is a long-time issue. Previous instances were reported by e-mail and eventually it was listed issue 13532 which was reportedly going to be fixed by allowing content reviewers to content review recommended add-ons ( https://github.com/mozilla/addons-server/issues/13532#issuecomment-602602990 ). But three and a half hours later someone decided to change that approach ( https://github.com/mozilla/addons-server/issues/13806 ) without updating issue 13532.

**Comment by caitmuenster** [comment]
@bjherbison I understand you're frustrated, but can you please try to be less antagonistic when you file issues? I assure you that we are trying our best with an old, complex codebase and limited resources during a challenging time.

**Comment by bjherbison** [comment]
I'm sorry. I was less antagonistic when I filed it the first time, but I was told I needed to file it again.

When can we talk?

**Comment by caitmuenster** [comment]
Thank you. :) I'm sorry you were asked to refile the issue -- that doesn't help with the frustration, for sure. 

Let me do a little bit of digging and let's try to talk on Thursday?

**Comment by jvillalobos** [comment]
@caitmuenster can you update this issue if there's anything to add? Otherwise it should be closed due to #13806.

**Comment by caitmuenster** [comment]
@jvillalobos Can we keep an issue on file to remove Recommended Extensions from the content review queue? It looks like #13806 restricts approval/rejection but doesn't remove them from the queue -- ideally, Recommended Extensions wouldn't be exposed in the queue. (I understand if we can't prioritize this issue at the moment.)

**Comment by jvillalobos** [comment]
We can keep this open if you like, but it's unlikely to ever get fixed and will be closed by stalebot eventually. The review queues are really complex and in the original issue it was already mentioned that it would be too much effort to make that change.

**Comment by eviljeff** [comment]
fwiw, we show icons for all the promoted/recommended addons on the queue page now.
