### ISSUE TITLE
Add internal function to allow running a scanner on a given version

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13871]
Similar to the work that was done for yara as part of the code search project, we'd like to have an internal function (not exposed in the admin or even a command yet) to run a given scanner on any version.

**Comment by diox** [comment]
QA: make sure customs scanner rules work as before when the waffle switch is enabled.

**Comment by ioanarusiczki** [comment]
@diox I uploaded listed and unlisted add-ons with and without matched rules for the custom scanner. The scanner works as expected.

Verified on dev with FF74(Win10).
