### ISSUE TITLE
v2 blocklist regex doesn't match all guids with import_blocklist

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13887]
Some of the blocklist regular expressions that should match guids aren't matching all the expected add-ons.  The blocks do match _some_ addon guids, just not all they would be expected to.

There may be a regex syntax incompatibility between javascript and mysql.

[missing_blocks.txt](https://github.com/mozilla/addons-server/files/4421943/missing_blocks.txt)

**Comment by eviljeff** [comment]
From the kinto records, these are the broken regexs:
### 11fd123a-e67d-44ab-909f-b776ea2e8d0a
`"/^((aapbdbdomjkkjkaonfhkkikfgjllcleb@[cC]hrome-?[sS]tore-?[fF]oxified--?((\\d+)|(unsigned)))|(blndkmebkmenignoajhoemebccmmfjib@chrome-store-foxified--?\\d+)|(bridge-translate-app@chrome-store-foxified--?\\d+)|(dephbpajmknbniclommefdlnflkfnpgh@chrome-store-foxified--?\\d+)|(generated-axbwzwbksnnig1ug9v5dly@chrome-store-foxified--?\\d+)|(icdahkkjdchifpnbebileaelbcgipepe@chrome-store-foxified--?\\d+)|(ifgljfjnflaadalpmkkgdailepedeehd@chrome-store-foxified--?\\d+)|(knpgbkpddpcepnloiijojmgbdhihkjkl@chrome-store-foxified--?\\d+)|(translate-4@chrome-store-foxified--?\\d+))$/"`

**sample missing guids**
aapbdbdomjkkjkaonfhkkikfgjllcleb@chrome-store-foxified-990648491
aapbdbdomjkkjkaonfhkkikfgjllcleb@chromeStoreFoxified-1006328831
icdahkkjdchifpnbebileaelbcgipepe@chrome-store-foxified-3944692786
ifgljfjnflaadalpmkkgdailepedeehd@chrome-store-foxified--1543114139
knpgbkpddpcepnloiijojmgbdhihkjkl@chrome-store-foxified-285094064
generated-axbwzwbksnnig1ug9v5dly@chrome-store-foxified--505607522
dephbpajmknbniclommefdlnflkfnpgh@chrome-store-foxified-1431651605
bridge-translate-app@chrome-store-foxified-2125721878
translate-4@chrome-store-foxified--1030927569
blndkmebkmenignoajhoemebccmmfjib@chrome-store-foxified-853793180

### 04c27082-2b78-4005-a6c5-8e0a13f83288
`"/^((ihmgiclibbndffejedjimfjmfoabpcke@chromeStoreFoxified--?\\d+))$/"`

**sample missing guids**
ihmgiclibbndffejedjimfjmfoabpcke@chrome-store-foxified--527308884
ihmgiclibbndffejedjimfjmfoabpcke@chrome-store-foxified-1189096297
ihmgiclibbndffejedjimfjmfoabpcke@chromeStoreFoxified-231839395

### d6b2dbad-31e9-4984-b649-19036cd38e1d
`"/^((((generated-e0yf8zkhypow3jjifkqzwo)|(iiinclagpealgnaglbmkdbfbgchjjbpg)|(jaehkpjddfdgiiefcnhahapilbejohhj))@chrome-store-foxified--?\\d+))$/"`

iiinclagpealgnaglbmkdbfbgchjjbpg@chrome-store-foxified--965105369
iiinclagpealgnaglbmkdbfbgchjjbpg@chrome-store-foxified-1076081317
jaehkpjddfdgiiefcnhahapilbejohhj@chrome-store-foxified--1008973568
jaehkpjddfdgiiefcnhahapilbejohhj@chrome-store-foxified-1007749210
generated-e0yf8zkhypow3jjifkqzwo@chrome-store-foxified--660177462

**Comment by AlexandraMoga** [comment]
@eviljeff if the import_blocklist tasks searches in our database for guids matching a particular regex, would the following test method work?
1. create a few add-ons on -dev and set their guids to any of those missing guids enumerated in https://github.com/mozilla/addons-server/issues/13887#issuecomment-609761111
2. run the import_blocklist script and look for these addons in the admin list of blocks

**Comment by eviljeff** [comment]
@AlexandraMoga yes

**Comment by AlexandraMoga** [comment]
@eviljeff I've created the add-ons. You can run the script when you have time for it.

**Comment by eviljeff** [comment]
done

**Comment by AlexandraMoga** [comment]
All the created regex guids are present in the list of blocks after the import. 
I'm marking this issue as verified fixed on -dev.
