### ISSUE TITLE
`call_mad_api()` task should be skipped when there are validation errors

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13883]
### Describe the problem and steps to reproduce it:

Upload a large add-on that will make the linter timeout (this is not 100% reproducible but it should work).

### What happened?

The `mad` scanner is called and it will fail.

### What did you expect to happen?

The `mad` scanner is not called.

### Anything else we should know?

All the tasks in the validation chain are "validation tasks" and decorated with `@validation_task`. However, the `call_mad_api` task is not strictly speaking a validation task because it is the callback of a `chord()` (yep...).

The `@validation_task` decorator prevents decorated tasks to be executed in case of a linter error, but we don't have this check in `call_mad_api()` so we have to add it.

**For QA:** I don't think you'll be able to fully verify this issue because it is not visible to users/admins. We need to look into the logs so please ask someone from the AMO team.

**Comment by AlexandraMoga** [comment]
I've uploaded a few large add-ons that would cause the linter to timeout (from logs:  `Soft time limit (360s) exceeded for olympia.devhub.tasks.validate_upload`).

@willdurand checked the logs and and there were fewer errors reported. Before the patch, the `mad` scanner was called all the time (and it failed when the linter timed out).
