### ISSUE TITLE
connection to settings-writer.stage.mozaws.net is timing out in mlbf cron

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13895]
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/7732102/

The `upload_mlbf_to_kinto` cron is failing due a connection error when trying to upload the bloomfilter as an attachment to http://settings-writer.stage.mozaws.net/v1/buckets/staging/collections/addons-bloomfilters/records/12e92ded-dd33-480c-998f-ee71a2ca88f3/attachment (the uuid between "records/" and "/attachment" is randomly generated)

**Comment by eviljeff** [comment]
The v2 blocklist update to kinto - from a celery task triggered by the BlocklistSubmission being approved/created - seems to be working though.  The legacy (v2) updates are also to settings-writer.stage.mozaws.net but to the `addons` collection rather than `addons-bloomfilters`.  

so... is it something special about the environment (cron vs. celery task) or something special about the collection ("addons-bloomfilters" vs "addons") or something special about the content (a file attachment vs basic JSON data)

**Comment by AlexandraMoga** [comment]
@eviljeff just to be sure, while this error is present, https://settings.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records will not show any records?
Also, this endpoint receives data from -dev, right?

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff just to be sure, while this error is present, https://settings.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records will not show any records?

yes

> Also, this endpoint receives data from -dev, right?

addons-dev writes to the kinto.dev.mozaws.net server so is unaffected

**Comment by bqbn** [comment]
A couple of questions:

1. The cron runs on the admin host, does the admin host need access to kinto-writer too? Currently, kinto-writer only allows celery workers to connect to it.

2. If `http://settings-writer.stage.mozaws.net/v1/buckets/staging/collections/addons-bloomfilters/records/12e92ded-dd33-480c-998f-ee71a2ca88f3/attachment ` is not a typo, then it needs to be HTTPS, not HTTP.

**Comment by eviljeff** [comment]
>     1. The cron runs on the admin host, does the admin host need access to kinto-writer too? Currently, kinto-writer only allows celery workers to connect to it.

It does, though that's an interesting point - we could rewrite the function to spin out the upload to a celery task (but we wouldn't know as easily if something was failing)

>     2. If `http://settings-writer.stage.mozaws.net/v1/buckets/staging/collections/addons-bloomfilters/records/12e92ded-dd33-480c-998f-ee71a2ca88f3/attachment ` is not a typo, then it needs to be HTTPS, not HTTP.

it's a typo

**Comment by bqbn** [comment]
> It does, though that's an interesting point - we could rewrite the function to spin out the upload to a celery task (but we wouldn't know as easily if something was failing)

OK, we thought admin just triggers the job, and real work is done on the celery workers, that's why only celery workers are allowed.

I suppose we can also allow admin. But let me know what your preference is.

> it's a typo

FYI, https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/prod/settings.py#L112 show shows HTTP. But it's unrelated, since that's for -prod.

**Comment by eviljeff** [comment]
> FYI, https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/prod/settings.py#L112 shows HTTP. But it's unrelated, since that's for -prod.

😞 good catch

**Comment by AlexandraMoga** [comment]
https://settings.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records is showing records today.
@eviljeff I see two attachments in the records, one generated today (which I expected since I've added new blocks on stage) and another attachment generated yesterday (I haven't made any changes to the stage blocklisting yesterday, so I'm not sure where that comes from).

**Comment by eviljeff** [comment]
The first record will be there because there wasn't a filter generated and (successfully) uploaded before
