### ISSUE TITLE
Listen to FXA SQS queue to process account deletions 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#13896]
Supercedes #7922

See https://docs.google.com/document/d/1hjlWVzzrSrGzMYKmxqK76MzOVQbV7sbc7padtj8xclA/edit# for details.

Once this is ready the release will need to be coordinated with landing https://github.com/mozilla/fxa/pull/4532/

**Comment by bbangert** [comment]
Is this a new integration? We have a new system for propagating these events now that is preferred over using the SQS queue:
https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events

**Comment by eviljeff** [comment]
> Is this a new integration? 

Not entirely - AMO already listens for primary email address changes via an SQS queue so ideally we'd just slightly adjust that to handle deletions too.

> We have a new system for propagating these events now that is preferred over using the SQS queue:
> https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events

switching over to a new system seems a risky move.  And an unknown more work given we'd have to work out how to integrate it first - the docs don't contain any examples out how this would be done (everything from the second sentence onwards is just about verifying the JWT keys).  Or are there implementations you can point to @bbangert ?

**Comment by eviljeff** [comment]
@muffinresearch in the data retention PRD there is detail about some delayed metadata deletion, and it's not clear from the doc if any of this is already in place or it needs to be added as part of this project (or will be added as a separate project):

> When an AMO account is deleted, all of its associated data is deleted with it. The only exception is when the account is the sole owner of an add-on, in which case:
>
> * All add-on files and their associated metadata will be retained for a total of 7 years, after which they will be permanently deleted.
> * The developer’s email address and IP addresses used to submit their add-ons will be retained for a total of 7 years, after which they will be permanently deleted.
> * All other user data will be deleted within 48 hours.
If the developer creates a new account using the same email address, no add-ons will be associated with it.

The 7 year timeline is interesting - and automatic task (cron) would likely be code-rotten before it did anything (we should have deleted all the non-webextension addons already, webextensions are less than 7 years old, so there shouldn't be any deleted addon content less than 7 years old); a manual task needs the institutional memory to trigger it - _who_ will receive the alert in 7 years time?

**Comment by jvillalobos** [comment]
Applying the deletion policy is part of the project, yes.

There's flexibility to the 7 year span (we went with something that wasn't unreasonably long but would ensure keeping the data as long as possible), so if it is implemented as a manual task that is run yearly, quarterly, something else should be okay.

**Comment by eviljeff** [comment]
In reference to the user data, we currently clear on delete:
- all the text data entered into the profile
- the profile photo*
- email address
- fxa_id

This is all done immediately*, so would be done when the notification from FxA is processed.  Immediately is "within 48 hours" so I'm assuming that's okay.  *(the profile photo delete is a task, so will actually delete from storage whenever that runs, e.g. a few minutes later)

We can also clear related content:
- Collections they own (have created)
- Ratings they left on other addons

@jvillalobos should collections and ratings be removed too, or retained and associated with a now anonymized user?  The latter is what we currently do when a user deletes their account via AMO. IMO the deletion via FxA should be the same or less strict than what a user could do directly via AMO.

**Comment by diox** [comment]
FYI; we also currently clear `last_login_ip` 6 months after deletion, via a management command.

**Comment by jvillalobos** [comment]
The goal is to retain data that could be used to investigate malicious add-on behavior, so what we need to keep for 7-ish years is email address, IP addresses (including `last_login_ip`), and associated add-ons. Anything else, including collections and ratings, can be cleared right away.

I think we should apply the same policy when an account is deleted from AMO, but if we need any extra data to revive an account that was deleted on AMO and not FxA (FxA ID, maybe?), we should consider preserving that as well.

**Comment by muffinresearch** [comment]
Running in a daily cron seems like the best plan here (as Mat notes is currently used for last_login_ip), it will only start reaping data once the data meets the age requirements.

Sounds like we need to consolidate any existing reaping that happens in order to meet the newer retention policy, we should also make sure any existing docs on this front are updated.

**Comment by eviljeff** [comment]
(Moving the post-delete cleanup after x days/months/years to #14494 and concentrating this issue on the immediate delete.)

**Comment by eviljeff** [comment]
@jvillalobos we've previously wanted to keep ratings (they're kept and linked to the anonymized user) because otherwise developers would lose ratings on their addons. (Collections should go, imo). Not sure if that affects our policy or not.

**Comment by jvillalobos** [comment]
Ratings with a review should definitely be deleted, since we need to respect the user's desire to delete everything that's public. We could keep ratings without reviews, but I don't think we're gaining much if we do that.

**Comment by eviljeff** [comment]
@jvillalobos currently if a user chooses "Delete Profile" on AMO we prevent them from deleting their account if they are a developer (sole or joint, addonuser:owner or just addonuser:developer) of any themes or extensions.  They must delete or transfer ownership of every addon first.  

Just confirming we want to change that policy and delete all the users add-ons when they choose to delete their account on AMO (either indirectly via FxA, or directly via addons-frontend/API).

**Comment by eviljeff** [comment]
On frontend we say
> Your data will be permanently removed, including profile details (picture, user name, display name, location, home page, biography, occupation) and notification preferences. Your reviews and ratings will be anonymised and no longer editable.
>
> When you use this email address to log in again to addons.mozilla.org, you will create a new Firefox Add-ons profile that is in no way associated with the profile you deleted.
>
> NOTE: You cannot delete your profile if you are the author of any add-ons. You must transfer ownership or delete the add-ons before you can delete your profile.

**Comment by jvillalobos** [comment]
> Just confirming we want to change that policy and delete all the users add-ons when they choose to delete their account on AMO (either indirectly via FxA, or directly via addons-frontend/API).

Yes, for all add-ons where they are the sole owner. For all other add-ons they should just be removed as an author.

Here's updated copy for the frontend message:

> Your data will be permanently removed, including profile details (picture, user name, display name, location, home page, biography, occupation), notification preferences, reviews, and collections.
> If you authored any add-ons they will also be deleted, unless you share ownership with other authors. In that case, you will be removed as an author and the remaining authors will maintain ownership of the add-on.
>  When you use this email address to log in again to addons.mozilla.org, you will create a new Firefox Add-ons profile that is in no way associated with the profile you deleted.

**Comment by eviljeff** [comment]
Before this feature can be enabled on prod we need:
 - mozilla/addons-frontend#9467
 - #14549
 - mozilla/fxa#5557
 - https://bugzilla.mozilla.org/show_bug.cgi?id=1644203

**Comment by AlexandraMoga** [comment]
@eviljeff could you please add some steps so I can better understand what is covered by this patch? I see there are still additional dependencies open so it will be good to know where to focus my testing at this point.

**Comment by eviljeff** [comment]
@AlexandraMoga it needs the work on the FxA side (mozilla/fxa#5557) complete before it's possible to test.

**Comment by eviljeff** [comment]
@AlexandraMoga you can test that nothing different happens if you delete your FxA account (i.e. your AMO isn't deleted) while the waffle switch (`'fxa-account-delete'`) is off.  Though right now the FxA work isn't complete so we aren't even getting the notifications.

**Comment by AlexandraMoga** [comment]
I've tested this on stage because FxA is more stable there (i.e more prod like) and the account delete process is not changed. Specifically, if a user has an active account on AMO and deletes the account from FxA, the profile content from AMO is not affected. 
I've also verified that account deletion from AMO continues to work as before.
