### ISSUE TITLE
Identify "Auto-approve confirmed" versions in the list when rejecting an add-on

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#13894]
When we are selecting the reject action, it is asking which version we want to select. But in this list there are also auto approved versions which we have to unselect when we do the reject. 
To verify this we have to consult the list and watch the status of each version one by one. When it's only on one page it's fine even if it costs a bit of time to do it. 
The problem comes from add-ons with many pages of version. It really easy to make a mistake by unselecting the wrong one, miss ones to unselect, etc...

It would be really helpful when we want to reject to show in the version list the status of these next to their number . 

@kewisch

**Comment by diox** [comment]
I don't fully understand. Why wouldn't you want to reject auto-approved versions ?

**Comment by lafonth** [comment]
In the standard process, today, we have to avoid to reject human approved versions.
From this rule, we have to check if there are versions in this status in the list of versions when we want to reject. Ad for this we have to scroll page by page and check the status of each, which is really time consuming.
