### ISSUE TITLE
Add new (redirect) URL paths to the file viewer

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13907]
Supports: https://github.com/mozilla/addons-server/issues/13634

---

We need 2 new URL paths to help code-manager construct URLs to redirect to the legacy file viewer. These URL paths will use version IDs as parameters instead of file IDs (because file IDs are not known in the code-manager).

- `/en-US/firefox/files/browse-redirect/:versionId/`
- `/en-US/firefox/files/compare-redirect/:baseVersionId...:headVersionId/`

Both URLs can take a `file` query parameter as well:

```
/en-US/firefox/files/compare-redirect/:baseVersionId...:headVersionId/?file=path/to/file.js
```

**Comment by ioanarusiczki** [comment]
@willdurand I verified the redirect URLs on dev with FF74(Win10).

- The browse-redirect and compare-redirect are working - the old file viewer is displayed and manifest.json file is available.

Examples:
https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse-redirect/1691031/
https://reviewers.addons-dev.allizom.org/en-US/firefox/files/compare-redirect/1690424...1690425/

- If I add a parameter - the path for a different file than manifest.json - the old file viewer lands on manifest.json and I think this should redirect to the file indicated by the query parameter. 

Examples:
https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse-redirect/1691031/?path=inject/index.js
https://reviewers.addons-dev.allizom.org/en-US/firefox/files/compare-redirect/1690424...1690425/?path=src%2Faction%2Fscript.js

Let me know if you need a new issue for this case.

**Comment by willdurand** [comment]
>     * I add a parameter - the path for a different file than manifest.json - the old file viewer lands on manifest.json and I think this should redirect to the file indicated by the query parameter.
> 
> 
> Examples:
> [reviewers.addons-dev.allizom.org/en-US/firefox/files/browse-redirect/1691031/?path=inject/index.js](https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse-redirect/1691031/?path=inject/index.js)
> [reviewers.addons-dev.allizom.org/en-US/firefox/files/compare-redirect/1690424...1690425/?path=src%2Faction%2Fscript.js](https://reviewers.addons-dev.allizom.org/en-US/firefox/files/compare-redirect/1690424...1690425/?path=src%2Faction%2Fscript.js)
> 
> Let me know if you need a new issue for this case.

The query parameter is named `file`.

**Comment by ioanarusiczki** [comment]
@willdurand Oh snap, I was used to path. brb!

**Comment by ioanarusiczki** [comment]
@willdurand I added `path` instead of the correct name `file`. 
The files indicated are correctly displayed.

https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse-redirect/1691031/?file=inject/index.js
https://reviewers.addons-dev.allizom.org/en-US/firefox/files/compare-redirect/1690424...1690425/?file=src%2Faction%2Fscript.js

Verified on dev with FF74(Win10).
