### ISSUE TITLE
Set default for "reply required" to 14 days 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#13915]
When reviewers request more information from an add-on developer, the notification email says the developer has 7 days to reply. The "7" is the default number that can be toggled by admins but not contributor reviewers. 

Due to the COVID-19 situation, we'd like to give developers a default of 14 days to respond to requests.

**Comment by ioanarusiczki** [comment]
@wagnerand I used an admin account and an add-on reviewer account and went to a review page. 
I went to the "Reviewer reply" section and I mark the Require developer to respond in less than… where I see as default "7"

![7 days](https://user-images.githubusercontent.com/33448286/78684036-b0b38900-78f8-11ea-885c-61def42322c0.png)

the e-mail will notify the developer about it

![the e-mail received](https://user-images.githubusercontent.com/33448286/78684125-c6c14980-78f8-11ea-9c9a-7098957a4538.png)

If I changed 7 to 14 or 21 I also received it as expected in the emails.

Perhaps there's a contributor reviewers group on prod who should only have the default 14?

**Comment by wagnerand** [comment]
Thanks, I found the issue and submitted another PR.

**Comment by ioanarusiczki** [comment]
@wagnerand I verified on dev and I see the default 14 days for admin, add-on or content reviewers. 
An admin can change the number of days from 14 to less or more than 14. The add-on and content reviewers cannot. They need to check the Require developer to respond in less than… where I see as default "14" and then the e-mail will be sent accordingly.

![default is 14](https://user-images.githubusercontent.com/33448286/78764942-f1aaac80-798f-11ea-9510-e9ef10b4dd77.png)

![the email sent](https://user-images.githubusercontent.com/33448286/78764979-fe2f0500-798f-11ea-8265-7e96ca201883.png)
