### ISSUE TITLE
Remove the hidden "What are Add-ons" panel from the disco pane.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1391]
This is a screenshot from -dev. The panel with the arrow pointing to it is loaded in the disco pane then hidden on production. If you don't blink you catch a glimpse of it before it's hidden. If it's not important we should probably just remove it entirely.

<img width="601" alt="discover_add-ons" src="https://cloud.githubusercontent.com/assets/1514/12334214/c4ef0b3a-baf0-11e5-92a9-162c9de42eaa.png">

**Comment by magopian** [comment]
Maybe @jvillalobos or @atsay would know more about that? Do we still want it, or can we simply remove it?

**Comment by jvillalobos** [comment]
That panel does show up in about:addons if you're not logged in to AMO. If it's just being hidden on AMO, we can drop it from there but not from about:addons.

**Comment by muffinresearch** [comment]
> That panel does show up in about:addons if you're not logged in to AMO. If it's just being hidden on AMO, we can drop it from there but not from about:addons.

I don't see that on prod. If I log-out from amo and then go to about:addons it's not there and it's not there when logged-in either. Do you have STR to reproduce what you're seeing?

**Comment by jvillalobos** [comment]
It should be there on about:addons in the Get Add-ons pane. You just need to be logged out, afaict.

**Comment by muffinresearch** [comment]
I get this for about:addons logged-out.

<img width="714" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/1514/12360195/698e4544-bbae-11e5-9116-8c5b0de7c439.png">

And this logged in:

<img width="604" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/1514/12360218/913fc7c0-bbae-11e5-9463-7c29997b51cf.png">

So no "What are Add-ons?" for me. It flashes up and dissappears.

**Comment by jvillalobos** [comment]
I get this, using a fairly clean profile:

![about-addons](https://cloud.githubusercontent.com/assets/62568/12360962/bf52ab6a-bb80-11e5-9962-3903b1325a45.jpg)

Maybe it's related to cookies?

**Comment by muffinresearch** [comment]
Yep - I'll investigate and try and work out on what basis it's shown - because this might affect the CSP changes.

**Comment by andymckay** [comment]
@muffinresearch does this affect the CSP?

**Comment by muffinresearch** [comment]
No, it is shown under some criteria and the origin for the video has been added. It was fixed here: https://github.com/mozilla/addons-server/issues/1601

**Comment by muffinresearch** [comment]
Going to close this issue - since we're not going to do anything now. It'll get sorted with the disco pane update.
