### ISSUE TITLE
404 is shown for the comment API on deleted versions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13913]
Followup for https://github.com/mozilla/addons-code-manager/issues/713

Prerequisites:
From dev hub - I delete a version (as the developer). 

STR:
1. Go to https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/404-bookmarks
2. Open code manager for one of the deleted files such as https://code.addons-dev.allizom.org/en-US/browse/618060/versions/1689371/
3. Notice the red warning on the top of the page
4. Try to add a reviewer comment 

Results:
A 404 is displayed at the top of the page.
When a comment is added another 404 is displayed. 

Notes:
The API responds with a 404 when I try to post a comment from Postman. 
I can't tell if deleted files should have code manger - since the version is deleted in the first place. 

![404 test](https://user-images.githubusercontent.com/33448286/66812571-d2c8e180-ef3b-11e9-88a4-e255d20adce1.gif)

**Comment by diox** [comment]
There are 2 parts to this issue:
- The permission required, which like https://github.com/mozilla/addons-server/issues/12725 is `Addons:ViewDeleted`. If you don't have that, you'll get a 404.
- Even with the permission, the API filters out deleted versions so you always get a 404 at the moment. This needs fixing.

**Comment by ioanarusiczki** [comment]
@diox I verified this issue testing with the[ API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#drafting-comments) and from code-manager too with FF74(Win10). 

- I could add comments as an admin and addon reviewer which has Addons:ViewDeleted permission.
- I receive a 404 for content reviewers which confirms that users without Addons:ViewDeleted permission can't do such operations. ( I can't tell if they have the permission or not in production, but if it will ever be needed that can be added).
