### ISSUE TITLE
Show all available translations for add-on name in review page

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13910]
Split from #11516 : as a minimal workaround we want to show all translations for the add-on name in the review page. 

This issue is exclusively about the add-on name: we'll focus on other fields like summary and description later in #11516, they require a more complex solution in terms of UX (hard to balance wanting to show all translations for reviewers to see everything at a glance with not turning the review page into a big mess with several pages of content to look at).

**Comment by ioanarusiczki** [comment]
@diox "Add-on name translations" was added to the reviewer pages - /reviewers/review-content/dark4-reader5 and /reviewers/review/dark4-reader5. Also it's available for listed and unlisted review pages.

From what I've seen, I think it looks good. The section is situated before Add-on History. I'll give two examples:

![sample one](https://user-images.githubusercontent.com/33448286/78678309-71356e80-78f1-11ea-87e4-ea3f2c7fa0c7.png)

![addon names](https://user-images.githubusercontent.com/33448286/78678444-a0e47680-78f1-11ea-90a4-2c567f7e5a21.png)

Verified on AMO dev with FF74(Win10).
