### ISSUE TITLE
TypeError in the files viewer when clicking an image

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1392]
When clicking an image you see `TypeError: t is undefined` in the console. With uncompressed src via a proxy this shows `TypeError: str is undefined`. The traceback points to https://github.com/mozilla/olympia/blob/d2427f9ec5511eb2d52ad5f690a62953ba7a5fff/static/js/zamboni/files.js#L7

Looks like `squash_space` might be called without an arg when an image is attempted to be shown.

**Comment by wagnerand** [comment]
While images are still not being displayed, I don't see this particular error anymore. Closing...
