### ISSUE TITLE
Collections' "Last updated" not working

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#13937]
I updated some collections last week (such as this [one](https://addons.mozilla.org/firefox/collections/4757633/must-have-media/?page=1&collection_sort=-added)) and discovered the "Last updated" date does not change when collections are indeed updated. 

It would be great to get this fixed so users don't feel like we're promoting abandoned collections. 

@muffinresearch

**Comment by willdurand** [comment]
> I updated some collections last week (such as this [one](https://addons.mozilla.org/firefox/collections/4757633/must-have-media/?page=1&collection_sort=-added)) and discovered the "Last updated" date does not change when collections are indeed updated.

The [API](https://addons.mozilla.org/api/v4/accounts/account/4757633/collections/must-have-media/) returns:

```json
{
  "id": 5892698,
  "uuid": "b41b87ce9abf4fcbb7c41a107e0d1115",
  "url": "https://addons.mozilla.org/en-US/firefox/collections/4757633/must-have-media/",
  "addon_count": 10,
  "author": {
    "id": 4757633,
    "name": "Mozilla Firefox",
    "url": "https://addons.mozilla.org/en-US/firefox/user/4757633/",
    "username": "mozilla"
  },
  "description": {
    "en-US": "Search images, improve your video experience, balance audio, and other fancy media tools."
  },
  "modified": "2019-10-24T17:00:22Z",
  "name": {
    "en-US": "Must-Have Media"
  },
  "slug": "must-have-media",
  "public": true,
  "default_locale": "en-US"
}
```

**Comment by AlexandraMoga** [comment]
I've looked into this and I have something to mention.
Collections have two edit phases on the frontend: 
- first edit phase - user adds or deletes add-ons
- second edit phase - user edits collection metadata

For the first edit phase, the last modified date is indeed not updated. Only when changes to the metadata are involved, the last modified date will be updated.
I think this has always been the case. 

As a note, if collection addons are added or removed from the admin tools, the last modified date will be updated.

**Comment by diox** [comment]
Yes, this is not surprising: the `modified` field is automatically updated when fields on the model change, but not adding or removing related models. This matches what @AlexandraMoga noted, and indeed it's always been the case. We do have a field with the addon count that is updated via a task, `collection_meta`, but in this task we explicitly avoid firing the signal that would update `modified` (because it would also trigger the task, so there would be an infinite loop)

Easy solution would be to manually set `modified` in the task.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev and the `modified` field in collections api is now refreshed after an add-on is added/removed (including removing all the collection addons).

One note regarding addons-frontend: the Last modified date will update only after the page is refreshed.
