### ISSUE TITLE
Add ActivityLog when a user is rate-limited

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13943]
When a user is rate-limited we should add that to an `ActivityLog` tied to the user (and the add-on, if available). We should also log those events to stackdriver.

**Comment by diox** [comment]
QA; an `ActivityLog` should be created and associated to the user that made the request when they are hitting rate limits (regardless of what rate limit was hit). That `ActivityLog` should only be visible to admins (for instance from the user admin pages, there is a link to see all activity logs) but not the developers or reviewers.

Keep in mind rate limiting is currently disabled on dev (but enabled on stage).

Rate limits around submissions for reference:
- 3 per minute per user
- 6 per minute per ip
- 20 per hour per user
- 50 per hour per ip

**Comment by diox** [comment]
Mmm yeah actually it looks like it's because the scopes are not set correctly. This doesn't prevent the rate limits from working (technical explanation for those following: this doesn't cause a cache collision only because user id and ips can never collide. But this is bad and we should fix it!), but it does make the activity log string incorrect. I'll fix that.

I'll fix the API issue in #14039

**Comment by AlexandraMoga** [comment]
I've re-verified the Activity log messages for rate limiting and now we have the following:

- for user: `throttled for scope "burst_user_addon_upload"`
- for ip: `throttled for scope "burst_ip_addon_upload"`

If there multiple consecutive rate limits hit by a user (429), the following activity log message is created: `throttled for scope "sustained_user_addon_upload"`

The activity logs are triggered also for API submissions. 

This seems to be the intended behavior.
