### ISSUE TITLE
save blocked json data; generate a stash file along with the mlbf each time

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#13945]
first part of #13762 - generate the stash file.  Remainder of #13762 will be to upload the stash file (and be selective about when it's needed vs. just a filter file)

**Comment by AlexandraMoga** [comment]
@eviljeff I'm not sure what I should be verifying here.

**Comment by eviljeff** [comment]
It's not really practical to verify on it's own - it can be done with #13762
