### ISSUE TITLE
Add more info to version creation logging

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#13942]
We'd like extra information added to this log to better monitor version creation:
https://github.com/mozilla/addons-server/blob/9a7cb04ccf31da6e5fd422f302b2ba7ada596685/src/olympia/versions/models.py#L244-L245

The following should be added:
- user email
- addon guid
- user id
- ip address of the request used to create the `FileUpload` (means storing that info on the `FileUpload` when it gets created)
- Whether or not this was created using the API

Note that we already automatically add username and ip address to all log statements, but because this can be called from a celery task, we can't rely on them.

**Comment by diox** [comment]
For the IP, I'm thinking we don't need a new field, we can just override the value stored in `threading.local()` just for the logging, through a context manager or something. Currently it's going to be empty, there is no drawback in setting it, just need to make sure it's reset back to `None` once we're done with this.

**Comment by AlexandraMoga** [comment]
@diox is there anything I should verify for this?

**Comment by diox** [comment]
Make sure uploads of new add-ons/versions still work both in API and devhub. If you give me the guids used afterwards I can look at the logs to see if the extra info is here.

**Comment by AlexandraMoga** [comment]
@diox submissions are still working both from DevHub and the API. 
You can check the logs for the following guids from stage:

**DevHub**
{6f6b1eaa-bb69-4cdb-a24f-1014493d4290} - new add-on listed
{157dcd26-1a4b-48b1-8795-7cfee6a34414} - new add-on unlisted
{895e9e51-5a7f-4c67-aa6d-0b7de4813185} - new version to existing listed add-on
{87d16d3d-0451-440f-b283-2ed798c45dc4} - new version to existing unlisted add-on
**API**
{c06fc0bd-1624-4272-bc21-98b8c11fa1a9} - new add-on unlisted
{3c53a643-226b-466f-b350-be72dc02a74d} - new version to existing add-on

**Comment by diox** [comment]
I can see the info in the logs and it looks correct. One caveat is that `uid` (which points to `username` in our setup) is not set for API requests - but `user_id` and `email` are correct. I'll follow-up, but `user_id` and `email` are more useful anyway.

**Comment by AlexandraMoga** [comment]
Re-opened by accident but I can't close it anymore :(
