### ISSUE TITLE
Show when an information request will expire

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#13955]
When viewing an add-on with an information request I used to know when the request would expire by adding seven days to the date of the request. Now that the default length has changed I don't know how long the request was for. (And it is possible the period will be reduced again in the future.)

There are two uses for this information:
1) As an add-on reviewer I can mention the end date correctly when adding a reminder about the pending information request.
2) As a developer I can know how long I have to respond before the request expires.

Steps to reproduce:
- View an add-on with a pending or expired information request.

Actual:
- The date of the information request is shown, but not the expiration date.

Expected:
- The message about the information request includes a time stamp identifying when the information request will or has expired.

Note:
- The message is only needed for an uncleared information request.
- The message is only needed for the most recent information request.
- My first thought was to place the message with the information request, but that might not always be easy to find if there has been activity after the information request was created. I'm not sure where the message should be displayed.

One current add-on with a pending information request:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/flowcite-extension

**Comment by jvillalobos** [comment]
> As an add-on reviewer I can mention the end date correctly when adding a reminder about the pending information request.

AMO already emails developers twice about need info requests, so additional reminders would be unnecessary and in some cases unwelcome.

> As a developer I can know how long I have to respond before the request expires.

The emails sent to developers indicate the expiration period, and developers don't have access to review pages anyway.

I do think it would be useful to show the time remaining in a pending request, particularly because we're making some changes to rejections and info requests related to this.

**Comment by diox** [comment]
Info requests are no longer a thing, pending rejections do show the time remaining.
