### ISSUE TITLE
Approved or Awaiting review unlisted addons show status Incomplete

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#13958]
STR:
I've noticed that approved unlisted addons which passed automatic validation or those flagged for human reviews by the scanners which are awaiting review show in admin tools an "incomplete" status. 

2 Examples:

https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?q=619670
https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?q=619638

Notes:
this issue is reproducible on dev and stage with FF75(win10). 
the correct status is shown in https://addons-internal.dev.mozaws.net/en-US/admin/addon/manage/35fe7df9f05b4bfea15d/

**Comment by diox** [comment]
That's not a bug. Add-ons with no listed versions are considered incomplete.
