### ISSUE TITLE
Add `delete()` method to `AddonGitRepository` class

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13963]
Refs https://github.com/mozilla/addons-server/issues/13590

---

This is part of our plan to solve https://github.com/mozilla/addons-server/issues/13590 and likely other (similar) git extraction issues.

**Comment by ioanarusiczki** [comment]
@willdurand I'm going to check again by uploading add-ons and then opening the uploaded files with codemanager.

**Comment by ioanarusiczki** [comment]
Verified on dev with FF75(Win10).
