### ISSUE TITLE
Run git extraction in a CRON (similar to `auto_approve`)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13964]
Refs https://github.com/mozilla/addons-server/issues/13590

---

While discussing about https://github.com/mozilla/addons-server/pull/13940, @diox and I decided to step back and see how we could avoid further issues and solve existing ones.

We believe that performing the git extraction in a CRON task would allow us to:

1. make sure versions are extracted in the right order
2. more easily re-extract all the versions of an add-on
3. recover from errors like https://github.com/mozilla/addons-server/issues/13590

Similar to `auto_approve`, we'll have a command scheduled every X minutes (5 minutes maybe). We'll use a FS lock to make sure the command is not run more than once at a time.

This command will look into a "queue" of add-on IDs to git-extract. For each add-on ID, the command will retrieve the versions that are not committed in the git repository yet (using the `git_hash` field on each version) and then extract these versions sequentially. The command will lock and then unlock the add-on once these versions have been extracted.

In https://github.com/mozilla/addons-server/pull/13940, we introduced a database lock when we re-extract all the versions of an add-on. We will keep this idea of a DB lock to guarantee the order of commits in the git repo of an add-on. If something goes terribly wrong (like a Celery worker that dies), we'll be able to unlock the add-on by deleting its DB lock.

If an add-on whose ID is in the "queue" is locked, then we won't remove the ID from the queue and next time the command runs, it will try to extract the non-extracted versions for this add-on.

During the submission process, instead of performing the git extraction, we'll push the add-on ID to the queue and that's it. An add-on ID can be present more than once in this queue.

If we detect an error like https://github.com/mozilla/addons-server/issues/13590, we can delete the repository (see #13963) and push the add-on ID to the queue. Next time the command runs, the add-on will be re-extracted.

**Comment by willdurand** [comment]
@diox did I miss anything? Unfortunately, I did not take as much notes as I wished..

**Comment by diox** [comment]
To extract extract versions sequentially, we talked about using a celery task chain with an unlock task at the end, similar to how it's done for code search. But that's an implementation detail (that we may or may not end up doing).

We also discussing needing a simple admin tool to view the queue and what's locked, so that we can force an extraction to happen again by pushing an add-on to the queue manually, and remove a lock if something went wrong.

**Comment by bobsilverberg** [comment]
> 
> This command will look into a "queue" of add-on IDs to git-extract. For each add-on ID, the command will retrieve the versions that are not committed in the git repository yet (using the `git_hash` field on each version) and then extract these versions sequentially. The command will lock and then unlock the add-on once these versions have been extracted.
> 

I thought it was possible for a `git_hash` to be recorded even if an extraction fails in some way. Is that not the case?

**Comment by diox** [comment]
It's possible in theory to have a `git_hash` and that the extraction still didn't go exactly as planned (like, maybe we only partially unzipped the xpi and didn't notice, things like that) but if it's there, as far as the extraction code knows, the extraction is done.

**Comment by bobsilverberg** [comment]
> It's possible in theory to have a `git_hash` and that the extraction still didn't go exactly as planned (like, maybe we only partially unzipped the xpi and didn't notice, things like that) but if it's there, as far as the extraction code knows, the extraction is done.

Yes, I was thinking about a situation in which only some of the files were successfully written. I guess we are assuming that doesn't happen very often? What is the fix for when that does happen?

**Comment by diox** [comment]
I don't think we have any plans to address this now. I'm not sure if we have seen it in the wild yet (we did with the old file viewer, but it was a whole different architecture)

**Comment by willdurand** [comment]
I have yet to see it happen. Among the numerous things that can go wrong, I don't think this scenario exists. The git hash is given by git once the related content is tracked/stored. If the content is somehow invalid once committed in git, we have bigger problems.

A solution would be to delete the git repo for the add-on and re-extract.

**Comment by willdurand** [comment]
So I have a patch that works locally. I am going to file new issues to land this huge feature in small pieces. Since the sources have a different repo, I am going to focus on addons git repos for now (and not the sources).

The feature will be behind a waffle switch so that I can land small patches and we can enable/disable this feature if needed (until we are confident enough).

**Comment by ioanarusiczki** [comment]
@willdurand I tested on AMO dev with FF75(Win10).

With the switch active in admin:

- for the version uploads I used Postman and I uploaded for the same add-on listed and unlisted versions as fast as possible. The files showed up in codemanager but not immediately (about 5 min, maybe less). Until they are displayed the browse view returns a 404 , and there's a 500 error for a compare view and meanwhile the only link available is the legacy viewer which can be clicked and it will redirect to the old viewer without errors. 
I repeated the version test once again and I did not encounter problems.

The unlisted versions https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/adblock-plus-free-ad-blocker
The listed versions https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/adblock-plus-free-ad-blocker

- for a new version on multiple addons I made 2 set of tests. I uploaded 15 unlisted versions and then 10 listed versions using the linter and of course clicking Submit/Sign add-on as fast as I could.

I've noticed that this version https://code.addons-dev.allizom.org/en-US/browse/619668/versions/1691152/ loaded in about 8 min after the submission. This is a larger addon so I believe it's alright. 

The following versions throw a continuous 404 error:

This is from the first round of testing with 15 unlisted versions https://code.addons-dev.allizom.org/en-US/browse/7560/versions/1691150/ 
 
These are from the 10 listed add-on uploads:
https://code.addons-dev.allizom.org/en-US/browse/619713/versions/1691169/
https://code.addons-dev.allizom.org/en-US/browse/494353/versions/1691166/
https://code.addons-dev.allizom.org/en-US/browse/619690/versions/1691167/
https://code.addons-dev.allizom.org/en-US/browse/619668/versions/1691170/

I uploaded individually for webmail-ad-blocker two more versions after I met the first 404:
https://code.addons-dev.allizom.org/en-US/browse/7560/versions/1691158/
https://code.addons-dev.allizom.org/en-US/browse/7560/versions/1691159/

I deactivated the switch and uploaded one after another a new version for the add-ons with errors and then checked codemanager for them. These versions were immediately displayed after the upload, with no errors.
https://code.addons-dev.allizom.org/en-US/browse/619668/versions/1691175/
https://code.addons-dev.allizom.org/en-US/browse/619690/versions/1691174/
https://code.addons-dev.allizom.org/en-US/browse/494353/versions/1691173/
https://code.addons-dev.allizom.org/en-US/browse/619713/versions/1691172/
https://code.addons-dev.allizom.org/en-US/browse/7560/versions/1691171/

**Comment by willdurand** [comment]
> The following versions throw a continuous 404 error:
> 
> This is from the first round of testing with 15 unlisted versions [code.addons-dev.allizom.org/en-US/browse/7560/versions/1691150](https://code.addons-dev.allizom.org/en-US/browse/7560/versions/1691150/)

Which versions throw a 404?

**Comment by willdurand** [comment]
The errors for the add-on `7560` seem to be the same: `Invalid or broken archive.`. I don't know what it means, though.
