### ISSUE TITLE
Footer links headers should use the same font style

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13970]
Follow up for #13656 

### Describe the problem and steps to reproduce it:
1. Open Developer Hub homepage - https://addons-dev.allizom.org/en-US/developers/
2. Scroll down to the footer section
3. Notice the font style used for all three Footer-links-headers

### What happened?
Browsers and Products are using a lighter font weight compared to Add-ons

### What did you expect to happen?
All headers should have the same font style

### Anything else we should know?

[Actual]
![image](https://user-images.githubusercontent.com/31961530/79234688-4d36d780-7e73-11ea-9b31-2b975a77b1ff.png)

[Expected]
![image](https://user-images.githubusercontent.com/31961530/79234725-5cb62080-7e73-11ea-8035-115448d0775f.png)

**Comment by eviljeff** [comment]
@championshuttler you need to comment in the issue to be assigned to it

**Comment by championshuttler** [comment]
Hi @eviljeff , can you please assign this issue to me 😛 lol

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO-dev:

![image](https://user-images.githubusercontent.com/31961530/80208529-16ae4900-8639-11ea-8819-c9d33a4ef2d7.png)
