### ISSUE TITLE
Allow some users to see email address of any account

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#13972]
Some (non-full) admins need to access the email address of any account.
Could we add a feature to expose that (probably in the reviewer tools?), gated by a new permission `Users:View`?

**Comment by jvillalobos** [comment]
Can't we just create a group for those two people and give them the `Edit` permission they used to have? It doesn't require code changes and wouldn't depend on reviewer permissions.

**Comment by wagnerand** [comment]
Yes, I had thought about that. The downside is that it requires a functional VPN setup (and a special VPN group iirc).

I agree that ideally, this would be outside of the reviewer tools, but we can't expose it on the public account page on the frontend, and the admin tools require VPN.

**Comment by jvillalobos** [comment]
They wouldn't need to be VPN'd to access the DevHub pages of an extension. This is what they did back when they were in the `Staff` group.

Also, this would be a temporary solution, since Salesforce would be the better replacement for this. We just need to get the sync finalized before making the switch.

**Comment by wagnerand** [comment]
Yes, I was talking about `Users:Edit`, which requires VPN.
There is also `Addons:Edit` which is probably what you meant. We removed the _Staff_ group for security reasons and I am hesitant to bring back those permissions, in particular write access to the devhub. That was the main concern that lead to removal of the _Staff_ group.

It's also unclear when Salesforce sync is fixed, since that has been defunct for a while and I am not sure there has been much progress since then or that there will be any soon. We could also resurrect https://bugzilla.mozilla.org/show_bug.cgi?id=1608817 as an alternative, but broad write access to all add-on data is a big risk, especially without VPN.

**Comment by jvillalobos** [comment]
> It's also unclear when Salesforce sync is fixed, since that has been defunct for a while and I am not sure there has been much progress since then or that there will be any soon.

It has moved slowly, but there's progress being made.

> but broad write access to all add-on data is a big risk, especially without VPN

As a temporary fix, limited to two people, I think it's acceptable and preferable to making code changes that will be later discarded.

**Comment by wagnerand** [comment]
I found a workaround that doesn't require code changes.
