### ISSUE TITLE
Update pygit2 to 1.1.1

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#13980]
Let's update `pygit2` to `1.1.1`. We cannot update to `1.2.0` yet because the `libgit2-dev` package isn't available in the deb repos yet. We should not rely on these packages but Python Wheels are currently broken so 🤷 

**For QA:** please make sure git extraction works as before (no obvious regression/breakage)

**Comment by ioanarusiczki** [comment]
@willdurand I believe it's what I said here https://github.com/mozilla/addons-server/issues/13963#issuecomment-613853992
I've been uploading and checking code manager files today but this was merged an hour ago. I guess I should re-check?

**Comment by willdurand** [comment]
it's fine

**Comment by ioanarusiczki** [comment]
@willdurand I verified on AMO stage while release testing. I did not encounter problems with code manager.
Verified with FF75(Win10).
