### ISSUE TITLE
Optimize the transmission of file entries via the reviewers APIs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#13984]
We believe, partially based on data from https://github.com/mozilla/addons-server/issues/13983, that a big factor in the performance of the reviewers APIs is the computation and transmission of file entries.

There are two issues here:
1. The file entries for a given browse or compare API request are calculated on the fly, based on the filesystem. Some add-ons have thousands of files, and this calculation can be quite expensive and time consuming.

2. Code manager only needs the file entries the first time a version is requested, but the API returns the file entry data for every API request. This is a large amount of unnecessary data being transmitted a lot of the time.

We have discussed approaches to address each of these issues:

1. The file entries for a version could be pre-calculated when the version is extracted, and stored on disk in a json file, which could then be returned via an API response. There was concern that this could be a problem for the compare API, as it needs to calculate the file entries for a combination of two versions, and we wouldn't want to do that for every possible combination of versions. A suggestion was made that we could limit the pre-calculation to a set of versions that are close to the current version.

2. In order to avoid sending file entries via the API when not needed, changes could be made to allow a consumer to specify that file entries are not needed. This could be a new API, or a switch with the existing APIs. We could either take the approach of just saying "I don't need file entries", or, perhaps better, we could design a new API which only returns information needed for the current file, and that could be called for any subsequent file for a version. This is also discussed at https://github.com/mozilla/addons-server/issues/13660#issuecomment-614245934.

Looking for feedback from @diox, @willdurand and anyone else interested.

**Comment by bobsilverberg** [comment]
There is a third issue with respect to file entries that I'd like to add.

Looking at the data needed/used by code manager, it appears that there are some properties of file entries that are not used at all, and others that are not actually needed by the file tree, but rather are used to calculate values for the current file. 

Examples of the former are `size` and `modified`, which could be eliminated from the list of properties returned via the API.

The latter are `sha256` and `mimetype`, which are cached in the file entries for the version, but are never used by the file tree. Instead, they are accessed when generating information for a file and used to calculate a value that is returned for the file. If these properties could be returned for the current file (they currently are not), then we could eliminate them as well from the list of properties of file entries returned by the API.

As long as we're looking at making changes to the way the API deals with file entries, I think we should consider making the above changes as well, which would reduce the amount of data needing to be transmitted to the client via the API for file entries.

**Comment by diox** [comment]
All good leads I think. The first deserves its own issue, the other 2 could be done together. I like the idea of a new API to fetch file info, I was never a fan of how we use the version API + a `file` query parameter for this.

**Comment by bobsilverberg** [comment]
> All good leads I think. The first deserves its own issue, the other 2 could be done together. I like the idea of a new API to fetch file info, I was never a fan of how we use the version API + a `file` query parameter for this.

Thanks @diox. I will open a separate issue for item 1. I was wondering about your second sentence, are you suggesting one API that *just* returns version info (and no file info), and then a second API that *just* returns file info? I do think that makes sense from an API design perspective, but I suspect the reason we have the current design is that code manager never needs *just* version info, and always also needs info for a file when it requests version info. If we seperate them entirely, then code manager will have to issue 2 API requests the first time it is accessing a new version, rather than 1. Perhaps that is okay, but it's something to consider.

**Comment by diox** [comment]
Yeah I don't mind returning version+file info together, it's just that version info currently is really version info + the whole list of files entries... which we only really need once for the file tree, so it doesn't make sense sending it every time as you said.

**Comment by bobsilverberg** [comment]
I believe that we've addressed all of the issues raised here in separate issues, some of which have been fixed and one that is still open (#14019), so I am going to close this issue.
