### ISSUE TITLE
Unable to access search result pages after 1000th page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#14008]
Submitting this on behalf of MaDonna. 

MaDonna had performed [this search](https://addons.mozilla.org/en-US/firefox/search/?page=1000&sort=users&type=statictheme%2Cpersona), which returns 18,430 pages of results. Once she hit page 1000, she wasn't able to advance to page 1001 of the search results. Clicking on page 1001 or "Next" resulted in this error: 

![Screen Shot 2020-04-17 at 2 23 13 PM](https://user-images.githubusercontent.com/23342476/79615189-089b7e00-80b7-11ea-8222-a02803b72c89.png)

Not sure if this is a bug but I thought I'd check.

**Comment by diox** [comment]
This is an intended limitation, designed to limit server costs. 25000 results should be enough for most cases :)

**Comment by AlexandraMoga** [comment]
There is an inconsistency here between the API behavior and what the frontend is displaying, i.e. the pagination is not blocked at the 1000th page, although there are no further results to display after that.
This has been a long standing issue and is reported in https://github.com/mozilla/addons-frontend/issues/3887
