### ISSUE TITLE
Filter out non-pending Blocklistsubmission instances from the admin list view by default

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14014]
`Blocklistsubmission` records are never deleted (currently, #13278), even after the records have been approved and the submission expanded to `Block` objects.  We should have a default filter so when users visit the page they just see the outstanding submissions that need approval.

These a the 5* states of a `Blocklistsubmission`
```
        SIGNOFF_PENDING: 'Pending',
        SIGNOFF_APPROVED: 'Approved',
        SIGNOFF_REJECTED: 'Rejected',
        SIGNOFF_NOTNEEDED: 'No Sign-off',
        SIGNOFF_PUBLISHED: 'Published to Blocks',
```

@wagnerand would you prefer the default to be filtering _out_ `SIGNOFF_PUBLISHED` or just filtering to `SIGNOFF_PENDING` ?

 *(`SIGNOFF_NOTNEEDED` and `SIGNOFF_APPROVED` are interim states used just after the instance has been saved; straight after a celery task is started and at the end of the task the state will be `SIGNOFF_PUBLISHED`.)

**Comment by wagnerand** [comment]
Let's filter to `SIGNOFF_PENDING` as the default.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The Block submissions list's default filter in now 'Pending'. 
The rest of the filters continue to work as before.
