### ISSUE TITLE
The number of followers does not change after unfollow a collection.

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#1401]
Steps to reproduce:
1.In navigation menu go to “Collections” and from drop-down menu select "Collections I've Made". ( https://addons.allizom.org/en-US/firefox/collections/mine/)
2.Follow one collection, then unfollow it.

Expected results:
The number of followers is updated accordingly 

Actual results:
No update is made in the  number of followers after unfollow.

Note/Issues:
Verified in FF 43(Ubuntu 14.04). Issue is reproducing in AMO-Stage, AMO-Dev, AMO-Prod.
User must be logged in
User must have at least one collection created

Please see the link for this issue :
https://www.dropbox.com/s/xfsunfygf2n71o5/Unfollow.mp4?dl=0

**Comment by EnTeQuAk** [comment]
I'm pretty sure this is cached somewhere somehow so a change is not visible immediately. I'm closing this as wontfix for now since it's one of the things that might be reimplemented in the near future anyway.
