### ISSUE TITLE
delete/replace unnecessary extra non-base mlbf files in collection

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14013]
followup from #13762 

when #13762 lands we will generate a new mlbf each time there is a new stash file, but the client won't ever need more than either a) the latest mlbf (if no stash support) or b) the base mlbf (if stash support).  

So we should either delete the older records with now obsolete mlbf attachments, or replace the attachments in those records with the latest filter.  imo the latter seems to be a more "correct" solution but we need to check the attachment change will result in Firefox handling the updated attachment correctly.

**Comment by Rob--W** [comment]
Note: attachments are immediately deleted when the record is deleted:
https://github.com/Kinto/kinto-attachment/blob/cd826b0dd3ca78ddcc3f35110a728d93b0f9ffc8/kinto_attachment/listeners.py#L15

In theory, the following sequence of events is possible:

1. Firefox downloads collection.
2. AMO deletes the record + attachment.
3. Firefox attempts to download the attachment, but that fails.

The MLBF loading logic in Firefox is designed to handle errors like this, by persisting the downloaded attachment and falling back to the last known good download (and ultimately falling back to the MLBF bundled with Firefox if there is no attachment).

> or replace the attachments in those records with the latest filter. imo the latter seems to be a more "correct" solution but we need to check the attachment change will result in Firefox handling the updated attachment correctly.

Firefox will be able to handle this correctly.

**Comment by Rob--W** [comment]
> Note: attachments are immediately deleted when the record is deleted:

Correction:
@leplatrem told me that attachments are never deleted from the CDN, referencing https://github.com/mozilla-services/cloudops-deployment/blob/38f1028a5224866cd87e85ecbf4fa2ae75564bdf/projects/kinto/puppet/modules/kinto/templates/kinto.ini.erb#L159 (I can't view the source, but I trust his word).

**Comment by leplatrem** [comment]
![Screenshot from 2020-05-05 16-16-21](https://user-images.githubusercontent.com/546692/81076309-cca44d80-8eeb-11ea-8e2a-d006ecc6a882.png)

**Comment by eviljeff** [comment]
Superseded by #15426 that will just stop generating non-base mlbf
