### ISSUE TITLE
Cannot reject unlisted version pending review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14024]
### Describe the problem and steps to reproduce it:

An unlisted version awaiting review cannot be rejected.

### What happened?

There is no "Reject" action.

### What did you expect to happen?

A reviewer should be able to reject a pending version.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
This turned out to be more complex than I thought. I am not sure I have time to complete a patch, but I attached a draft PR you could build upon. It should handle the actions side, and I noted down what's missing from the patch.

**Comment by diox** [comment]
QA:
- Reject Multiple Versions should now be available for unlisted. When that action is chosen, for unlisted specifically, only the pending versions should be available. Listed remains the same.

**Comment by AlexandraMoga** [comment]
I've tested this on -dev and have the following results:

for unlisted versions:
- Reject multiple versions is now available and the reviewer can select to reject only versions that are pending for review - _Awaiting Review_
- for versions that were approved, reviewers can use the Block multiple versions option to reject and also block the add-on versions
- there is also an Approve button now that can be used to approve the latest version pending for review (it wasn't requested but it's there)

for listed versions:
- Reject multiple versions can still be used for rejecting versions pending for review or versions that were (auto)approved
