### ISSUE TITLE
Allow Browse and Compare APIs to return just file data

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14020]
This is a spin off from #13984 

Code manager only needs version specific information (e.g., file entries) the first time a version is requested, but the current APIs return version info for every request, even when code manager really only needs data for the requested file.

To deal with this we should introduce a new URL param (called `file_only`) for the Browse and Compare  endpoints that can be used to request just file data and not version data.

When `file_only` is set to `true` then only file data is returned to the client. The file data is in a top-level property called `file`, and none of the other `version` properties are returned in the API response.

**Comment by willdurand** [comment]
> To deal with this we should introduce new endpoints that can be used to request just file data for both the browse and compare use cases.

Did we ever consider adding query parameters to include/exclude data instead of creating new endpoints?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I tested in Postman on dev, by sending some requests for the Browse and then the Compare API. 
- the response is more simplified, with `entries:null` and also general information about the addon (including the version number) will be excluded.
Two examples:
https://addons-dev.allizom.org/api/v5/reviewers/addon/502991/versions/1541836/?file_only=true&file=images%2Ficon128_gray.png
https://addons-dev.allizom.org/api/v5/reviewers/addon/619715/versions/1691176/compare_to/1691183/?file_only=true&file=autosave-ui.html

- without a specific `file` added the response will return information about manifest.json (as default)

- if I used `file_only:false` the information in the response returns the same data as if I use `file_only:true`. The complete (original) information is available only if I delete the parameter from request.

https://addons-dev.allizom.org/api/v5/reviewers/addon/502991/versions/1541836/?file_only=false&file=images%2Ficon128_gray.png
https://addons-dev.allizom.org/api/v5/reviewers/addon/619715/versions/1691176/compare_to/1691183/?file_only=false&file=autosave-ui.html

with false 
![fileonlyonfalse](https://user-images.githubusercontent.com/33448286/81410015-c232bf80-9148-11ea-8173-d6b8be03dfc7.png)

with true 
![true](https://user-images.githubusercontent.com/33448286/81410384-4ab16000-9149-11ea-9a04-dd58750c4f29.png)


  If I should file an issue about this let me know. Thanks!

**Comment by bobsilverberg** [comment]
@ioanarusiczki Yes, please file an issue about the `false` param not working. We should fix that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I filed a followup https://github.com/mozilla/addons-server/issues/14238
This issue is verified on dev.
