### ISSUE TITLE
Override user when creating `ActivityLog` in submission-related tasks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14039]
STR:
- Submit an add-on using the API
- Look for `ActivityLog` related to the user that did the submission

Expected results:
- You find at least one instance of `ADD_VERSION` (`{version} added to {addon}.`) linked to the user and the add-on.

Actual results:
- You don't find any instances of `ADD_VERSION` linked to the user. You do find one linked to the add-on.

This is because the `ActivityLog` is created in a task so it would be linked to the task user instead. We should pass the `user` down to `ActivityLog` creation in `Version.from_upload()`, and check if other `ActivityLog` creations are affected.

**Comment by AlexandraMoga** [comment]
@diox I've run into this issue while verifying https://github.com/mozilla/addons-server/issues/13943. There is indeed no `ActivityLog` created when a user is rate limited when submitting add-ons via the API.

**Comment by diox** [comment]
Wow, that's a good find, I forgot about throttling. I'll fix this.

**Comment by AlexandraMoga** [comment]
@diox I see the following activity log for API submissions: 
```
May 6, 2020, 11:46 a.m. | {id:username} | Version 1.0.7 added to addon-1
```
but I don't see one for the add-on being created, like we have for submissions from devhub:
```
May 6, 2020, 11:46 a.m. | {id:username} | addon-1 was created.
```




Activity logs are also created for throttled submissions (I've updated https://github.com/mozilla/addons-server/issues/13943#issuecomment-624644099 with the results as well)

**Comment by diox** [comment]
That's a different issue, this particular `ActivityLog` is probably not called from the right place. You can open a follow-up about it.
