### ISSUE TITLE
Increase limit to include more data in requests in django admin

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14038]
In django admin, for some actions, we hit `413 Request Entity Too Large` because the request body contains too much data. Splitting the actions into multiple smaller ones is not feasible, unfortunately. Can we increase the limit (for admin pages only)?

**Comment by diox** [comment]
@bqbn what's the value for `client_max_body_size` in nginx right now for the internal instance and can we bump it up ? We have a limit for this in the app already and it's at 2.5 MB (django's default).

**Comment by eviljeff** [comment]
In django the default is 2.5MB - we don't appear to override it.
https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-DATA_UPLOAD_MAX_MEMORY_SIZE

we don't want to increase it generally or we'd be opening ourselves to DOS'ing, but perhaps we could for the admin instance, or for /admin (ideally for particular AdminSite classes)

**Comment by diox** [comment]
The admin lives on a specific nginx config so we could bump it there. I don't think we're hitting django's limit (it would raise a 500), but rather nginx's.

**Comment by bqbn** [comment]
@wagnerand what is the URL when you hit the error? I basically want to see which domain and path need this.

**Comment by wagnerand** [comment]
@bqbn I'll reach out to you!

**Comment by eviljeff** [comment]
closing in preference of #14050
