### ISSUE TITLE
Some .crx files are considered corrupt/invalid erroneously

### ISSUE THREAD

**Issue by mojorero** [mozilla/addons-server#14036]
Hi, I tried to upload my Extension for the first time at approximately 13:40 hours (UTC +2). The add-on is unlisted.

The add-on is a CRX export of an already working Chrome Extension.

[dist.zip](https://github.com/mozilla/addons/files/4433547/dist.zip)

This is the URL where I submitted the extension: https://addons.mozilla.org/de/developers/addon/submit/upload-unlisted

I got the following error messages:

![image](https://user-images.githubusercontent.com/11564614/78488968-33e1ad00-7748-11ea-9a05-41790e85f251.png)

**Comment by diox** [comment]
Should be fixed by https://github.com/mozilla/addons-server/pull/15870
