### ISSUE TITLE
Do not rely on entries for file-only data

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14042]
This supports #14020 and is a follow-up to #14031.

It proposes two changes:

1. Changes to the logic for calculating `mimetype`, `sha256` and `size`, so that `entries` are not required to be calculated when just retrieving data for a single file. Note that, because code won't have been introduced which would allow for just data for a file to be requested, the serializer will still calculate and return `entries`, but these changes set the stage for requesting file data without `entries`.

2. Removal of properties from `entries` that are no longer needed, which includes `mimetype`, `sha256` and `size` (which are no longer needed because they are now returned for the file), as well as `modified`, which is never used.

Note that a change to code manager will need to land alongside this.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
@bobsilverberg 
 - I verified this issue on dev with Postman and I can confirm that `size`, `mimetype`, and `sha256` were moved from `entries` into `file`.
 
- I did not find `modified` anywhere in the API.  If that's not ok please let me know. 

I verified this issue for both - Browse and Compare APIs.
