### ISSUE TITLE
An error for the name field is shown when one of the locales passes the 50 char limit while uploading the first version

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14055]
STR:
While making addon uploads @release testing yesterday on AMO stage I encountered an add-on (I downloaded version 3.1.1 for Cookie Auto Delete from prod) which gave an error on the last page of the submission form - the "name" field. 
"Ensure this value has at most 50 characters (it has 54)."
Further investigating around the addon, I've noticed multiple locales and one of them, the "bg" has the following name into the messages.json file "Cookie AutoDelete (Автоматично изтриване на бисквитки)" which is the reason I could not go further with my submission on AMO stage.

The default locale is "en" and the Name is "Cookie AutoDelete"

![nuinteleg](https://user-images.githubusercontent.com/33448286/80193915-46058b80-8622-11ea-97c8-d2e2d7d3b0b1.png)

- this issue is only reproducible while submitting the first version of an add-on. This version has been uploaded on AMO prod without issues because it was not the first version - Cookie Auto Delete version 3.1.1- 

It is reproducible on AMO stage and AMO prod with FF75(Win10). 

On AMO dev - because of the different behavior (content optimization) the form can let you pass the error. After I try to submit the addon it won't allow me, then I can crop the text to be under 70 chars for the default locale and submit it.

There's also the warning about the other locales:
Warning: you have name/summary values in other locales that will be automatically cropped

![on AMOdev](https://user-images.githubusercontent.com/33448286/80196010-6b47c900-8625-11ea-908b-eb12cb137b14.png)

**Comment by eviljeff** [comment]
fwiw, this is a very old problem with how devhub (mis-)handles localised properties.

**Comment by danielnaber** [comment]
I just ran into this on https://addons.thunderbird.net (my Italian appName was 52 characters), would be good to have it re-opened and fixed.

**Comment by eviljeff** [comment]
> I just ran into this on https://addons.thunderbird.net (my Italian appName was 52 characters), would be good to have it re-opened and fixed.

the code that runs on addons.thunderbird.net is https://github.com/thundernest/addons-server/
