### ISSUE TITLE
"Request was throthled" error is displayed after a double click on rating stars.

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#14051]
Steps to reproduce:
1.Open any extension on addons.mozilla.org
2.Fast double click on rating stars

Expected results:
Even is the "Request was throthled" error is displayed, users should be able to write the review for first click

Actual results:
Users cannot write the review after fast double click and ""Request was throthled" error message is displayed

Reproducible also on Stage and -dev.

**Comment by willdurand** [comment]
This issue is actually a dup of https://github.com/mozilla/addons-frontend/issues/4007 and I updated the issue to reflect the problem mentioned here.
