### ISSUE TITLE
Add command to bulk add guids to the blocklist

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14050]
#14038 wasn't enough - there are bottlenecks in django and the ORM with attempting to add a BlockSubmission with a large (1000+) number of guids in single attempt. 

Instead lets add a management command to be run by ops for this one-off task.

**Comment by AlexandraMoga** [comment]
@eviljeff is there anything I could test for this issue?

**Comment by eviljeff** [comment]
I've verified on addons-dev.  We might need some QA on prod but we'll deal with that in another issue/off-github.
