### ISSUE TITLE
Show links to other channel on reviewer page for deleted add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14056]
### Describe the problem and steps to reproduce it:

For deleted add-ons, there are no _Listed Review Page_ and _Unlisted Review Page_ links in the right-hand side navigation, even if there are versions in those channels.

### What happened?

Links are not available for deleted add-ons.

### What did you expect to happen?

Links should be available even for deleted add-ons.

### Anything else we should know?

The links show up correctly for non-deleted add-ons.

**Comment by diox** [comment]
Should be a matter of passing `include_deleted=True` to the relevant `has_listed_versions()` and `has_unlisted_versions()` calls in the template.

**Comment by wagnerand** [comment]
Yep, thanks! I've had the patch ready for a few days, just didn't get around to test it.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage.
Reviewers can now navigate between listed and unlisted review pages for deleted add-ons. Of course, the navigation is available only to users who have the necessary permissions (i.e. unlisted reviewer permissions)

[1] - from listed to unlisted
![image](https://user-images.githubusercontent.com/31961530/80581300-a37c4c80-8a15-11ea-82b9-84679d1fd980.png)




[2] - from unlisted to listed
![image](https://user-images.githubusercontent.com/31961530/80580422-2c928400-8a14-11ea-927c-a14d06d5a083.png)
