### ISSUE TITLE
Update to filtercascade >= 0.4.1 and fix the logic

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#14066]
`filtercascade` has had an update to fix a typo (`filter.bitarray` -> `current_filter.bitarray`), plus some extra sanity checks (https://github.com/mozilla/filter-cascade/pull/23).

The implementation in addons-server should be updated to use this new version.
Besides that, the `fprs` calculation usage should also be adjusted: Using that logic I hit a runtime error for the sample input of 1 non-blocked and 1000 blocked add-ons. The logic should be resilient enough to not fail unexpectedly.

**Comment by Rob--W** [comment]
One way to get rid of the error is to let the library itself calculate the `error_rates`, by omitting `error_rates` from
https://github.com/mozilla/addons-server/blob/a6df8496feab52fa83228a2de894835604f39e3f/src/olympia/blocklist/mlbf.py#L89-L93

**Comment by eviljeff** [comment]
> Besides that, the fprs calculation usage should also be adjusted: Using that logic I hit a runtime error for the sample input of 1 non-blocked and 1000 blocked add-ons. The logic should be resilient enough to not fail unexpectedly.

Note this is currently a hypothetical problem with addons-server at the current time- it requires blocked addons/versions to be more than 55% of all addons/versions - even after the 1M addons have been added there will only be about 33% of addons/versions blocked.

**Comment by AlexandraMoga** [comment]
This issue didn't affect the mlbf generation and the attachment size was similar to historical records.
