### ISSUE TITLE
message typo: Firefox "on" Distribution Agreement

### ISSUE THREAD

**Issue by petercpg** [mozilla/addons-server#14067]
### Describe the problem and steps to reproduce it:
I noticed this when localizing AMO on Pontoon recently. 

### What happened?
https://github.com/mozilla/addons-server/blob/892e442ee61fe2592f19969357ed5d40a9e9fb2e/src/olympia/users/models.py#L888

Firefox `on` Distribution Agreement should be a typo.

### What did you expect to happen?
The message should be Firefox `Add-on` Distribution Agreement.

### Anything else we should know?
Just made a find and replace in my fork: https://github.com/petercpg/addons-server/commit/363cf178ea9a0cf8b0240ff37b10475f72543a91 . Not sure changing PO files directly breaks any following workflow. I can file merge request if it is alright.

**Comment by petercpg** [comment]
cc / @peiying2 to check this issue

**Comment by peiying2** [comment]
> cc / @peiying2 to check this issue

Thanks for reporting. I will ping the channel on slack to get someone to reply to this issue.

**Comment by diox** [comment]
It does look like a typo. We could modify every `.po` but just fixing `models.py` should be enough, I think. On next extraction the translation will be marked as fuzzy but that should be easy to fix and ensures translators can double-check their translation (we don't know if they saw the typo or not, and therefore we don't know what they translated exactly).

Fee free to submit a pull request with that change.

**Comment by petercpg** [comment]
Thanks @diox!

Just files the Pull Request for fixing `models.py` and `test_permissions.py`. Message files are left alone.
