### ISSUE TITLE
Add an admin to view the git extraction queue

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14063]
We have a new `GitExtractionEntry` model that is used as a git extraction queue (we add add-ons that might have versions to git-extract there). We should have a django admin to see the state of this "queue" in case something goes wrong and an add-on is locked for "git extraction" forever (we need an action to unlock the add-on in this case).

**Comment by ioanarusiczki** [comment]
@willdurand the models/git/gitextractionentry/ is available with an admin account and I also created a new group for Admin:GitExtractionEdit. Users added in this group will only have access to the git queue from admin. 

What I've noticed is that after an upload and until the files for the add-ons are extracted there's a state "In progress" with a question mark and this turns green when the extraction is successful then the entry is no longer available in the queue (if I refresh the page). I think it's the expected result.

I could also delete an entry with state "In Progress", before the files were extracted which I believe it's not ok in case the extraction fails.

**Comment by willdurand** [comment]
> What I've noticed is that after an upload and until the files for the add-ons are extracted there's a state "In progress" with a question mark and this turns green when the extraction is successful then the entry is no longer available in the queue (if I refresh the page). I think it's the expected result.

Yep, sounds good to me.

> I could also delete an entry with state "In Progress", before the files were extracted which I believe it's not ok in case the extraction fails.

So the main use case for the delete button is to delete old entries because entries should be automatically deleted. If we have entries that are older than... 24h for example, then we should manually delete them because it means something went wrong but also no other version can be extracted anymore for the related add-on.

**Comment by ioanarusiczki** [comment]
@willdurand The idea of the new extraction method is to manually extract the versions with problems and this means it's those who remain visible in this admin queue. This means there's to be implemented a way to re-extract the problematic addons by the admin. 
I hope I am right and if I am for now this issue and https://github.com/mozilla/addons-server/issues/13964 can be marked verified because there will be issues and more testing on dev for this feature the following weeks.

**Comment by willdurand** [comment]
> This means there's to be implemented a way to re-extract the problematic addons by the admin.

Yes, we are still thinking about how to do it but there will be something for that in the near future.
