### ISSUE TITLE
Add filters to the scanners API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14077]
We need some filters for https://addons-server.readthedocs.io/en/latest/topics/api/scanners.html because it would be useful to target a specific scanner or a label.

**Comment by AlexandraMoga** [comment]
I've verified the scanners api on -dev (I've enabled the `enable-scanner-results-api`) and tested around the new filter parameters added for `label` and `scanner`.

For `label`, the only accepted values are `good` or `bad`. Any other values, including `null` or `None` will return a 400 error with the message `"invalid value for label"`
For `scanner`, the only accepted values are the four scanner names we enabled so far. Any other value will return a 400 error with the message `"invalid value for scanner"`

Unfiltered requests will return only `good` or `bad` labelled result, i.e any other scanner results are ignored.
