### ISSUE TITLE
Allow The FileEntries serializer to return data for a file only

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14072]
Depends on ~~#14042~~
Supports #14020 

Allow the `FileEntries` serializer to return data without entries. Once this is in place it should be pretty easy to implement #14020 which would provide an API endpoint that can be used to request just file data, without entries.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Looking on dev the structure of the `files` is as following:
`id` ->that's the only property of the .xpi file left before `content`, the rest have been removed https://github.com/mozilla/addons-server/issues/14099 
`content`
`entries` which expose `depth`, `filename`, `mimecategory` and `path`
`selected file`
`download_url`
`uses_unknown_minified_code`
`mimetype`
`sha256`
`size` -> - which has been moved below `selected_file`. 
`mime_category`
`filename`

- the compare API also has the `status` property displayed but only in `entries`. I can't tell if it should be displayed down below `selected file` too (depends on what plans are with https://github.com/mozilla/addons-server/issues/14020)

- if there's something else I should be looking for please let me know.

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> Looking on dev the structure of the `files` is as following:
> `id` ->that's the only property of the .xpi file left before `content`, the rest have been removed #14099
> `content`
> `entries` which expose `depth`, `filename`, `mimecategory` and `path`
> `selected file`
> `download_url`
> `uses_unknown_minified_code`
> `mimetype`
> `sha256`
> `size` -> - which has been moved below `selected_file`.
> `mime_category`
> `filename`
> 
> * the compare API also has the `status` property displayed but only in `entries`. I can't tell if it should be displayed down below `selected file` too (depends on what plans are with #14020)
> 

`status` should appear in `entries` for the compare API, but not at the `file` level, so this is correct.

> * if there's something else I should be looking for please let me know.

I don't think so, it sounds verified to me.
