### ISSUE TITLE
Flag for review for some of the MAD results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14084]
We'd like to flag for review a version for which the MAD result has:

- a score equal to `0%`
- a score equal to `100%`
- a model disagreement

**Comment by diox** [comment]
Note: ideally it would live in a separate model, a bit like `AddonReviewerFlags` but for versions. Cause `ALTER` on `versions` is costly, and also extra fields we don't need 99% of the time are costly since by default Django requests them all all the time...

**Comment by willdurand** [comment]
> Note: ideally it would live in a separate model, a bit like `AddonReviewerFlags` but for versions. Cause `ALTER` on `versions` is costly, and also extra fields we don't need 99% of the time are costly since by default Django requests them all all the time...

@diox can't we reuse the flag for review action somehow? or maybe refactor it so that it contains a list of scanners that have set this flag?

**Comment by diox** [comment]
It's currently a boolean column on `versions` table, so if we want to avoid the costly `ALTER`, while still providing the extra info, it's going to be difficult... (though long-term if we do have a separate model we'll want to do the `ALTER` once to remove the current column)

**Comment by willdurand** [comment]
Ok, so I will add a `VersionReviewerFlags` (or `VersionScannerFlags`) model.

**Comment by AlexandraMoga** [comment]
@willdurand I'm not sure how I should verify these new MAD flags. There is no flag visible in rev tools for a version that had a score equal to `100%`  for example. 
In any case, I've run some tests to make sure the existing scanner flags are still working.

**Comment by willdurand** [comment]
@AlexandraMoga we need https://github.com/mozilla/addons-server/issues/14085 to have a UI on top of this issue.

**Comment by AlexandraMoga** [comment]
In that case, I'll mark this as verified, since I did not find regressions for the other scanner flags, and the MAD flags will be verified when the UI is ready.
