### ISSUE TITLE
Remove usage of `classic` similarity algorithm in elasticsearch

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14080]
We're using the `classic` similarity algorithm in elasticsearch at the moment, which isn't the default - it's there for compatibility with old elasticsearch versions, and we set that way back in https://github.com/mozilla/addons-server/issues/8867 to try to address issues we were having with search results after upgrading.

That setting has been deprecated for a while, but now [the documentation for 6.8](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/index-modules-similarity.html#classic-similarity) mentions this:
> The quality of the produced scores used to rely on coordination factors, which have been removed. It is advised to use BM25 instead.

I've noticed the quality drop in my branch as part of [the work to upgrade to 6.8](https://github.com/mozilla/addons-server/issues/8508). We should try to anticipate this and switch to the `default` algorithm and see if it's good enough for us, we've made a number of changes to search scoring since so my hope is that we don't actually need the `classic` algorithm anymore.

**Comment by diox** [comment]
Note: we've got a waffle switch for this, `es-use-classic-similarity`. A reindex needs to be done after toggling the switch. If search results are still good with the switch disabled, we can remove the associated code and adjust the tests.

**Comment by diox** [comment]
Waffle was already off on dev. I've turned it off on stage and triggered a reindex, but given dev I think we can move forward with removing the code.

**Comment by AlexandraMoga** [comment]
I've tested search functionality on stage and I did not spot obvious change in search relevancy. As a note, we should take into consideration #10171 when speaking of search relevancy on either of our test environments.
