### ISSUE TITLE
Do not call the MAD API when we don't need it

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14082]
We identified cases where it does not really make sense to call the MAD API, including:

- static themes
- search engines
- dictionaries
- language packs

We should not call the MAD API in these cases (but other scanners should run).

**Comment by willdurand** [comment]
Note: we can fix this issue by introspecting the scan map.

**Comment by AlexandraMoga** [comment]
I've tested this issue on -dev, where all the scanners are currently enabled and I have the following results:
1.  submission of dictionary, language pack, static theme _with no matching rules_  => `mad` is not running, `customs` shows `n/a` for score and all other scanners are running
2. submission of dictionary, language pack, static theme _with matching rules_  => all the scanners are running, and a score is returned both for `mad` and for `customs`
3. submitting a very simple extension, like this [example](https://code.addons-dev.allizom.org/en-US/browse/619727/versions/1691196/), will not trigger the `mad` scanner and customs shows `n/a` for score

@willdurand please have a look at these results as I'm not very sure that this is what's expected (especially for 2 and 3). 
Regarding search tools, were you referring to old `xml` formats or to search extensions?

**Comment by willdurand** [comment]
>     1. submission of dictionary, language pack, static theme _with no matching rules_  => `mad` is not running, `customs` shows `n/a` for score and all other scanners are running

Expected, good.

>     2. submission of dictionary, language pack, static theme _with matching rules_  => all the scanners are running, and a score is returned both for `mad` and for `customs`

What does that mean exactly? Can you share an example in private?

>     3. submitting a very simple extension, like this [example](https://code.addons-dev.allizom.org/en-US/browse/619727/versions/1691196/), will not trigger the `mad` scanner and customs shows `n/a` for score

Expected, good.

> @willdurand please have a look at these results as I'm not very sure that this is what's expected (especially for 2 and 3).
> Regarding search tools, were you referring to old `xml` formats or to search extensions?

search extensions

**Comment by AlexandraMoga** [comment]
Verified that is working as expected with search extensions as well.
This can be marked as verified fixed.
