### ISSUE TITLE
fix/replace pyup

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14088]
we're 6 days without any new pyup.io pull requests being created and my https://pyup.io/account/account/ doesn't show any mozilla organisation reps any longer.

It's unclear if it's a change on our side to restrict access (the application permissions page show ❌ next to organisation access) or on their side (the account page on pyup says "Please upgrade your account to the Business or Organization plan to allow organization access." - I don't know if that's new and we need to upgrade something or it's always said that and it only applies to private/commercial projects)

The alternative to fixing pyup is switching it out for another tool/service.

**Comment by bobsilverberg** [comment]
A decision was made to use Renovate for this.

**Comment by bobsilverberg** [comment]
It seems there was a problem with renovate reading our requirements files: https://app.renovatebot.com/dashboard#github/mozilla/addons-server/170702599. Here's an excerpt from the log:

```
DEBUG: Using file match: ^requirements/.*\.txt$ for manager pip_requirements
DEBUG: Matched 9 file(s) for manager pip_requirements: requirements/codestyle.txt, requirements/dev.txt, requirements/docs.txt, requirements/perftests.txt, requirements/prod.txt, requirements/prod_without_hash.txt, requirements/system.txt, requirements/tests.txt, requirements/travis_base.txt
DEBUG: Unknown comment command: <3.0
DEBUG: Unknown comment command: <4.0
DEBUG: Unknown comment command: <2
DEBUG: Unknown comment command: <6
DEBUG: Unknown comment command: <6
DEBUG: Unknown comment command: <1.2.0
DEBUG: Found pip_requirements package files
```

and then later:

```
INFO: Dependency extraction complete
{
  "stats": {
    "managers": {
      "npm": {
        "fileCount": 1,
        "depCount": 17
      },
      "pip_requirements": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 2,
      "depCount": 18
    }
  },
  "seconds": 13
}
```

and still later:

```
DEBUG: packageFiles with updates
{
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "deps": [
          {
            "depType": "dependencies",
            "depName": "addons-linter",
            "currentValue": "1.24.0",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/mozilla/addons-linter"
          },

snip...
       
        ],
        "packageJsonName": "addons-server",
        "packageJsonVersion": "0.0.17",
        "packageJsonType": "app",
        "skipInstalls": true,
        "managerPackageFileList": [
          "package.json"
        ]
      }
    ],
    "pip_requirements": [
      {
        "packageFile": "requirements/perftests.txt",
        "manager": "pip_requirements",
        "deps": [
          {
            "depName": "pyzmq",
            "currentValue": "==19.0.0",
            "datasource": "pypi",
            "fromVersion": "19.0.0",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": null,
            "homepage": "https://pyzmq.readthedocs.org"
          }
        ]
      }
    ]
  }
}
```

So it looks like it was able to process `requirements/perftests.txt` but not the other files, and I'm guessing it's related to those `Unknown comment command` messages. I will look into this further.

**Comment by bobsilverberg** [comment]
I think it may be because of the hashes in our requirements files, as discussed at https://github.com/renovatebot/config-help/issues/367#issuecomment-535868406. I've asked the question at https://github.com/renovatebot/config-help/issues/627, but I am guessing that is the issue.

**Comment by bobsilverberg** [comment]
I turned on Dependabot and it seems to be working: https://github.com/mozilla/addons-server/pull/14109.

**Comment by diox** [comment]
Looks like it's ignoring the `# pyup <{version}` comments - which makes sense, they're pyup specific, but we'll need some way of specifying which updates we don't want with Dependabot as well.

Side note: do you know why it's Dependabot-preview and not just Dependabot ?

**Comment by bobsilverberg** [comment]
> Looks like it's ignoring the `# pyup <{version}` comments - which makes sense, they're pyup specific, but we'll need some way of specifying which updates we don't want with Dependabot as well.
> 

I'll look into that.

> Side note: do you know why it's Dependabot-preview and not just Dependabot ?

I have no idea. I set everything up from what appears to be the default Dependabot site.

**Comment by diox** [comment]
Looks like the preview bit is just for the initial runs.
