### ISSUE TITLE
"IndexError: list index out of range" while trying to commit a version without files

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14098]
We do not check that `all_files` is not empty [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/git.py#L348) because that shouldn't be possible. That being said, old versions might not have any files so we should probably handle this edge case.

**Comment by ioanarusiczki** [comment]
@willdurand If qa can test the issue, please add some STR.
Thanks!
