### ISSUE TITLE
Remove unnecessary file properties from reviewers API responses

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14099]
This supports #13984 

There are a number of properties for the version file which are returned via reviewers API responses that are never used by code manager. These are mostly properties of the file uploaded for the version (i.e., the xpi file), not properties of the file being reviewed (e.g., manifest.json). As code manager never uses these properties, we can eliminate them from the API response.

The properties in question are:
-  created
-  hash
-  is_mozilla_signed_extension
-  is_restart_required
-  is_webextension
-  permissions
-  platform
-  status
-  url

Note that these are documented at https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail-object.

@wagnerand None of these are currently used by code manager, but could you please confirm that there are no future use cases that might desire these properties. Bear in mind, as discussed above, these are not properties for the specific file being reviewed (e.g., an individual js file), but rather properties of the file that was uploaded for the version (the xpi file).

**Comment by wagnerand** [comment]
If any, we might make use of _permissions_ and _status_, although I don't have concrete plans for either.

* We could expose permissions somewhere or might augment some parts based on some permissions. Generally, for just looking at permissions, a reviewer can just take a look at manifest.json.
* For status, there could be an indication in the compare widget, whether a version is approved, waiting to be reviewed or disabled. I am not sure how helpful that would be.

Generally, with the comments API a bit of the functionality might move from the reviewer tools page into code manager, but I can't think if anything else from that list that would be needed for that.

**Comment by bobsilverberg** [comment]
Thanks for the reply @wagnerand. As it's an extremely simple matter to add any of these properties back in, and as we don't have any concrete plans to use any of them right now, I think I'll just remove all of them for now.

**Comment by wagnerand** [comment]
Sounds good.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified Browse and Compare API responses on dev. 

- the properties [mentioned](https://github.com/mozilla/addons-server/issues/14099#issue-609068022) have been removed. 

My testing samples:
https://addons-dev.allizom.org/api/v5/reviewers/addon/502991/versions/1541836/
https://addons-dev.allizom.org/api/v5/reviewers/addon/619691/versions/1691091/compare_to/1691184/

- the properties are available in the addon [Version Detail](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail-object) API. 

An example:
https://addons-dev.allizom.org/api/v5/addons/addon/502991/versions/1541836/
