### ISSUE TITLE
Help reduce logging volume in production

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#14091]
### Describe the problem and steps to reproduce it:
AMO generates about 600+ GB logs per month. All those go across the Internet from AWS to GCP, and incur data transfer fees.

Can we configure the app to suppress at least DEBUG level logs for production?

The celery component in particular, seems to generate a lot DEBUG level logs.

### What did you expect to happen?

Suppress at least DEBUG level logs and/or unnecessary logs to help reduce cost and possibly improve performance.

### Anything else we should know?
n/a

**Comment by diox** [comment]
Agreed, we log too much. This is mostly for legacy reasons (some of the logs have always been there and we haven't bothered to touch them, and also on the other hand we've had to debug bizarre and complex legacy code), but we should fix this, it's even annoying to look at the sea of logs in stackdriver.

Before suppressing `DEBUG`, we should start by going through all `log.debug` calls and figure out if they are really debug logs.

**Comment by diox** [comment]
@bqbn is there a way for you to export the most common log types and severity seen (from `jsonPayload.Type` + `jsonPayload.severity`), or specific `DEBUG` messages you've seen ? That would give a different starting point that just doing through all `debug` logs to figure out if they matter (which I still want to do, but is quite painful)

**Comment by bqbn** [comment]
* for `olympia_web` component

  Please see if we can suppress this line of log

  `"download file xxxxxxx: addon/version/file not public and user None does not have relevant permissions."`

  The above line accounts for 96% of `olympia_web` logs, and it doesn't seem to be very useful to anybody. An example looks like this:

  ```
  {"Timestamp": 1589473368810223872, "Type": "z.versions", "Logger": "http_app_addons", "Hostname": "ip-172-31-44-31.us-west-2.compute.internal", "EnvVersion": "2.0", "Severity": 6, "Pid": 17, "Fields": {"uid": "<anon>", "remoteAddressChain": "159.65.67.14", "msg": "download file 563330: addon/version/file not public and user None does not have relevant permissions."}, "severity": 200}
  ```

* for `olympia_celery` component

  It looks like every task has at least 3 log messages, `Received task`, `starting task timer` and `tracking task run time`. I actually don't know how useful they are, so I'll let you decide if you want to suppress them or not, here are an example of those,
  ```
  {"Timestamp": 1589494857120089344, "Type": "celery.worker.strategy", "Logger": "http_app_addons", "Hostname": "ip-172-31-42-163.us-west-2.compute.internal", "EnvVersion": "2.0", "Severity": 6, "Pid": 1, "Fields": {"uid": "", "remoteAddressChain": "", "msg": "Received task: olympia.devhub.tasks.check_for_api_keys_in_file[110c6d40-2176-456f-aba1-f87ef9254897]  "}, "severity": 200}
  {"Timestamp": 1589494857121729280, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "ip-172-31-42-163.us-west-2.compute.internal", "EnvVersion": "2.0", "Severity": 6, "Pid": 1347, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "starting task timer; id=110c6d40-2176-456f-aba1-f87ef9254897; name=olympia.devhub.tasks.check_for_api_keys_in_file; current_dt=2020-05-14 22:20:57.121612"}, "severity": 200}
  {"Timestamp": 1589494857171916800, "Type": "z.task", "Logger": "http_app_addons", "Hostname": "ip-172-31-42-163.us-west-2.compute.internal", "EnvVersion": "2.0", "Severity": 6, "Pid": 1347, "Fields": {"uid": "<anon>", "remoteAddressChain": "", "msg": "tracking task run time; id=110c6d40-2176-456f-aba1-f87ef9254897; name=olympia.devhub.tasks.check_for_api_keys_in_file; run_time=50; current_dt=2020-05-14 22:20:57.171340"}, "severity": 200}
  ```

**Comment by willdurand** [comment]
>     * for `olympia_web` component
>       Please see if we can suppress this line of log
>       `"download file xxxxxxx: addon/version/file not public and user None does not have relevant permissions."`
>       The above line accounts for 96% of `olympia_web` logs, and it doesn't seem to be very useful to anybody. An example looks like this:
>       ```
>       {"Timestamp": 1589473368810223872, "Type": "z.versions", "Logger": "http_app_addons", "Hostname": "ip-172-31-44-31.us-west-2.compute.internal", "EnvVersion": "2.0", "Severity": 6, "Pid": 17, "Fields": {"uid": "<anon>", "remoteAddressChain": "159.65.67.14", "msg": "download file 563330: addon/version/file not public and user None does not have relevant permissions."}, "severity": 200}
>       ```

It definitely looks like a quick win!

**Comment by willdurand** [comment]
@diox given that we send everything to stackdriver, including DEBUG messages, how about we change all `debug` calls to `info` and then we stop sending DEBUG messages to stackdriver? That way, we could downgrade some log statements like the one above.

**Comment by diox** [comment]
I like that strategy, yeah.

> "download file xxxxxxx: addon/version/file not public and user None does not have relevant permissions."

I'm surprised this would come up a lot, but we can make it a `debug` log and stop sending `debug` log as @willdurand suggested

> It looks like every task has at least 3 log messages, Received task, starting task timer and tracking task run time

Yeah. I guess we could start by removing the received one but keep the rest for now - it's sometimes useful to know how much time a task we're debugging took - and whether or not it was started by a worker.

**Comment by diox** [comment]
@willdurand you have changed the 3 log messages thing for celery tasks right ? Maybe we shouldn't consider this closed until we have addressed this.

**Comment by willdurand** [comment]
> @willdurand you have changed the 3 log messages thing for celery tasks right ? Maybe we shouldn't consider this closed until we have addressed this.

I would like to file new more specific issues if possible. No, celery logs haven't been touched yet because we want to only hide one message according to the discussion above.

**Comment by willdurand** [comment]
I actually submitted https://github.com/mozilla/addons-server/pull/14333 for the Celery "received task" messages.
