### ISSUE TITLE
Only block deletions won't trigger a new mlbf

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14107]
The logic for the cron mlbf job currently relies on checking the latest modified date of the blocks in the database and skipping generation unless it's greater than (more recent) than the last generation time.  This works great for block additions and changes but wouldn't catch a block deletion because it wouldn't be in the database.

There could be some other flag we can set when blocks are deleted, though it's probably more stable to generate the list of blocked `guid:version`s and compare them to the last generation instead (at the expense of an extra database query and reading a JSON file from disk).

**Comment by AlexandraMoga** [comment]
The new mlbf will be generated when there are only block deletions:

```
"stash": {
                "blocked": [],
                "unblocked": [
                    "{9a65b905-ae6a-4105-8038-8fc62f1ef804}:1.5.1-signed",
                    "{a42eb16c-2fab-4c06-b1f3-5f15adebb0e3}:8.1.1",
                    "{e2e595ea-3c6e-4a30-ac93-8948bda1d4e8}:10.52",
                    "{9a65b905-ae6a-4105-8038-8fc62f1ef804}:1",
                    "491917@previously-invalid.guid:1.0.0.1-signed"
                ]
            }
```
