### ISSUE TITLE
GitError: reference 'refs/heads/master' not found

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14127]
It looks like we have an extra `self` here: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/git.py#L253. It usually works because `init_repository` creates the git repository and when we call `self.git_repository` on the next line, the repo is extracted so the `git_repository` method takes the "else" branch.

Yet, it does not work all the time as we can see in Sentry, likely because of timing issues/race conditions. We should remove this `self` call, it was a mistake.

We can highlight the bug in the test suite by using this patch:

```diff
diff --git a/src/olympia/lib/git.py b/src/olympia/lib/git.py
index fbe3e23541..fee329f5fd 100644
--- a/src/olympia/lib/git.py
+++ b/src/olympia/lib/git.py
@@ -263,6 +263,7 @@ class AddonGitRepository(object):
                 path=self.git_repository_path))
         else:
             git_repository = pygit2.Repository(self.git_repository_path)
+            git_repository.lookup_reference('refs/heads/master')
 
         return git_repository
```

Explanation: there must be a `master` branch when we return the already-initialized git repo.

Given that we can detect this error at runtime, we can probably raise a special error that would be handled like the `BrokenRefError` one.

---

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5525326/

```
GitError: reference 'refs/heads/master' not found
(1 additional frame(s) were not displayed)
...
  File "celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "olympia/amo/decorators.py", line 108, in wrapper
    return f(*args, **kw)
  File "olympia/versions/tasks.py", line 130, in extract_version_to_git
    version=version, author=author, note=note)
  File "olympia/lib/git.py", line 329, in extract_and_commit_from_version
    branch = repo.find_or_create_branch(BRANCHES[version.channel])
  File "olympia/lib/git.py", line 398, in find_or_create_branch
    name, self.git_repository.head.peel())

GitError: reference 'refs/heads/master' not found
```

**Comment by ioanarusiczki** [comment]
@willdurand If qa can test the issue, please add some STR.
Thanks!

**Comment by willdurand** [comment]
> @willdurand If qa can test the issue, please add some STR.
> Thanks!

@ioanarusiczki sorry. same as the other one, please upload some versions to verify the git extraction process. We cannot really simulate this particular issue in -dev.

**Comment by ioanarusiczki** [comment]
Verified on dev with FF75 (Win10). 
Test results are here https://github.com/mozilla/addons-server/issues/13932#issuecomment-624079021
