### ISSUE TITLE
Remove dependency on django-rest-framework-jwt

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14129]
We use JWTs only for the signing the API (and a couple associated APIs). We've got an authentication class that the the various views depend on.

That authentication class depends on django-rest-framework-jwt, which is essentially a wrapper around pyjwt for DRF. Unfortunately that package isn't actively maintained anymore, so we should switch away from it.

As it turns out, for the most part we're customized the authentication class to a point where we don't really need that much from django-rest-framework-jwt, so let's try to remove it entirely (keeping `pyjwt` of course - we don't want to reinvent that!). It likely means extracting a couple methods from the base authentication class django-rest-framework-jwt provides, as well as the default settings.

A few pointers:
- `JWT_AUTH` in `settings_base.py` is the dict with our custom settings on top of the default ones provided by django-rest-framework-jwt
- `api/authentication.py` contains the authentication class
- `api/jwt_auth.py` contains the decoding handler we use

**Comment by diox** [comment]
https://github.com/jpadilla/django-rest-framework-jwt has been archived and is now partially incompatible with the latest version of `pyjwt` ...

**Comment by diox** [comment]
QA: verify the API still works by submitting an add-on using your API Key as well as making an authenticated action on the frontend such as leaving a rating on an add-on.

**Comment by ioanarusiczki** [comment]
@diox 
- I made several addon and new version uploads using https://addons-dev.allizom.org/api/v4/addons/ with JWT authorization and it worked as expected.
- frontend authentificated users can leave ratings on addons. 
- using internal authentification I could create addon ratings with https://addons-dev.allizom.org/api/v4/ratings/rating/. It will return a 401 for bad auth. or when authorization is not provided.
