### ISSUE TITLE
Reject Multiple Versions: Version location: Please select one or more versions in the list above/below.

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#14128]
### Describe the problem and steps to reproduce it:
During a content review try to reject an add-on without selecting a version.

### What happened?
Above the version list this message appears:
Please select one or more versions in the list above.

### What did you expect to happen?
The message appears below the version list, or the message says:
Please select one or more versions in the list below.
![Screenshot_2020-04-30 Girlboyfriend Reviewer Tools Add-ons for Firefox](https://user-images.githubusercontent.com/4101902/80705144-e4c33980-8ab3-11ea-89bd-88d160fa1ab1.png)

https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/girlboyfriend#review-actions

**Comment by linzichao** [comment]
I will take it.

**Comment by linzichao** [comment]
#14624

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:
![image](https://user-images.githubusercontent.com/31961530/84667130-9dd9b800-af2a-11ea-8c26-e4882a38b4ff.png)
