### ISSUE TITLE
alert us somehow if import_blocklist fails

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14143]
from #14094:
> So if any part of this process fails errors should result in an alert so we know.

@muffinresearch did you have a type of alert in mind?  And is it just that the fetch fails from kinto or something else too?  e.g. is there a certain number of block removals that should trigger it?

**Comment by muffinresearch** [comment]
I was initially thinking of something around at least ensuring that if the cronjob errors because the import blew-up that we can have that email sent to a mailing list that is monitored. 

The main thing we'd like to guard against is that the blocklist stops updating without us noticing.

**Comment by eviljeff** [comment]
Grafana dashbaord created:
https://earthangel-b40313e5.influxcloud.net/d/IWZpIQgMk/blocklist

We only have metrics from stage currently which makes testing everything a little difficult.

**Comment by eviljeff** [comment]
QA: run through the same tests as for https://github.com/mozilla/addons-server/issues/14094 - we'd like to see all the metrics being recorded on the dashboard (if you can't access Grafana I can check that)

**Comment by eviljeff** [comment]
oh, and we can test the alert itself by disabling the `blocklist_auto_import` waffle switch during the window where it would normally run (05:35 utc +6,12,18hr)

**Comment by AlexandraMoga** [comment]
So, I've prepared some data for today, but the `blocklist_auto_import` waffle switch was enabled all the time. The data added in kinto was correctly imported in AMO. 
@eviljeff I don't have access to Grafana to check what's there. 

I can try again with another data set, this time making sure that the `blocklist_auto_import` is disabled.

**Comment by eviljeff** [comment]
@AlexandraMoga I saw, thanks - they showed up in grafana.

> I can try again with another data set, this time making sure that the blocklist_auto_import is disabled.

it should trigger even if there there aren't any further changes - just turning off the waffle is enough. I'll ask ops and verify that part myself.

**Comment by eviljeff** [comment]
I received an alert email.  it's pretty ugly but it works.
