### ISSUE TITLE
Tweak the logic / threshold used to replace the blocklist and MLBF

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#14145]
The collection for the blocklist is wiped and reset whenever the MLBF is generated again, and clients are forced to download the full MLBF base. This happens when the number of stash entries exceeds the treshold, [currently 500](https://github.com/mozilla/addons-server/blob/574730f05fd10351336273ed4afebc5a48b6b867/src/olympia/blocklist/mlbf.py#L21-L22). Let's evaluate whether this is the right value, and adjust it if needed.

The ideal threshold depends on the volume and frequency of blocklist updates, and the size of the individual entries.

The [currently published MLBF](https://hg.mozilla.org/mozilla-central/file/ae10e6fa5a553556fcf53f3f088b9cc8e3023f1b/services/settings/dumps/blocklists/addons-bloomfilters/addons-mlbf.bin.meta.json) is 64KB. This looks small (especially compared to the 900+ KB for the [JSON blocklists](https://hg.mozilla.org/mozilla-central/log/a00787062bfd58ab2350d63938a0df772d6689f2/services/settings/dumps/blocklists/addons.json)), but note that it covers only 38k blocks. @eviljeff mentioned that an experiment with 1M blocked entries was 713kb.

The uncompressed size for each entry is 50 bytes: An entry looks like GUID + ":" + version, and the total size of a stash entry is the sum of:
- The average GUID length is 38 (GUIDs are by far the most common ID).
- The average version length is less than 8.
- The overhead is 4 per entry (colon, 2 quotes+comma).

With the current threshold of 500, the stash size would approximately max out at 25kb. This is a reasonable value in comparison with the current blocklist size, but too low when the base MLBF becomes 700+kb (after adding 1M entries).

When we're going to grow the MLBF, we should reconsider when we're going to reset the collection.

**Comment by eviljeff** [comment]
@jvillalobos

**Comment by jvillalobos** [comment]
25kb does sound like a low maximum. I think it could be 10 times larger and acceptable in terms of download size. The other side of it is loading and processing the MLBF and stash on the client side, and there I don't know what the impact is for a much larger stash.

Looking at some recent blocklist data, we're blocking 100-200 ids per week. Most blocked add-ons have a single version, so the version counts would only be slightly higher. I believe that shipping Firefox with the latest MBF is still an open question, but it'd be great if in the future we can do that and aim for the stash to be robust enough to cover most users between major releases (so, lasting about a month).

For a different project we're thinking about some [open questions regarding blocklist timing](https://docs.google.com/document/d/1rc3c4BKFkI2Ms1wIDUaoL7kJXK2DJItocekqHewL2mk/edit#). I don't expect us to get answers soon, but they could help shape the future of some of these features.

**Comment by Rob--W** [comment]
> I believe that shipping Firefox with the latest MBF is still an open question

The current blocklist is shipped as a MLBF on desktop and Android (GeckoView-based):
- https://phabricator.services.mozilla.com/D73159 (desktop)
- https://phabricator.services.mozilla.com/D73438 (Android)

The current blocklist still has a reasonable size (64KB), and that's why it was acceptable to do so.
That does not automatically hold if we grow the MLBF to the order of 1 MB, especially not on mobile.

> The other side of it is loading and processing the MLBF and stash on the client side,

Constructing and using the MLBF at the client can be considered inexpensive, with almost no impact from an increase of blocks. The MLBF's main consideration is size of storage (for packaging with the binary) and bandwidth usage (when an update is forced).

Increasing the size of the stashes will directly impact the memory usage (think reasonably, i.e. keeping the string in memory, there is no other significant overhead). The impact on runtime is negligible (easily 10M lookups per second, tested with array size 3k, 30k, 300k on my laptop). Storage is still a concern with stashes (even though it compressed to about 30%). Updating stashes has a lower impact on bandwidth though, because only differences are propagated through RemoteSettings.

**Comment by eviljeff** [comment]
> Looking at some recent blocklist data, we're blocking 100-200 ids per week ... (so, lasting about a month).

That's where the 500 would match up.  We can increase it to 5000 if you want but then it could often be many months between new filters (a good thing?)  

If we want to force a collection reset and a new base filter on a schedule regardless that can be done too (need: the day/time of month the cron should fire on)

**Comment by jvillalobos** [comment]
> We can increase it to 5000 if you want but then it could often be many months between new filters (a good thing?)

Sounds like a good thing because of lower data transfers and low performance impact on the client side.

> If we want to force a collection reset and a new base filter on a schedule regardless that can be done too (need: the day/time of month the cron should fire on)

I'd like to time this around Firefox releases. We could generate a new base filter right before a Firefox release, so it ships with it and we can minimize the number of users who need to download the full thing. I haven't fully thought through how that would work logistically, though.

**Comment by eviljeff** [comment]
#14252 trivially increases the threshold; 
logged #14253 to allow us to override it and force a new base at an arbitrary point in the future

**Comment by AlexandraMoga** [comment]
@eviljeff to test this on -dev or stage, I should make sure that there will be 5000 or more block entries in stash before the new mlbf is generated and check that a new `bloomfilter-base` is created?

**Comment by eviljeff** [comment]
@AlexandraMoga I think it's too difficult to test on dev and stage (you'd have to find a lot of addons to block that had signed webextension versions) and it's just a change in a constant from `500` to `5000` so very low risk.  I'll mark as QA not needed.
