### ISSUE TITLE
`TestBlocklistSubmissionAdmin.test_submit_dual_signoff` is failing (sometimes?)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14140]
See: https://travis-ci.org/github/mozilla/addons-server/jobs/681880424#L4805

At the end of the stacktrace, we can also read:

```
    from wcwidth import wcswidth

ModuleNotFoundError: No module named 'wcwidth'
```

I don't quite understand why this test case starts to fail now.

**Comment by eviljeff** [comment]
I think the `wcwidth` error is a dependency we don't have installed (from pytest) but it's a codepath only used during some test fails so in those fails we get a double fail.

(not sure about the intermittent itself - it might just be that we rely on `addon_factory` generating unique data - i.e. different ADUs - and sometimes it generates two add-ons with the same value.  I've not investigated though)

**Comment by willdurand** [comment]
> I think the `wcwidth` error is a dependency we don't have installed (from pytest) but it's a codepath only used during some test fails so in those fails we get a double fail.

Yeah, I think so too, looking at the stacktrace for this particular error (and seeing it in other contexts)

**Comment by eviljeff** [comment]
I've not seen this in a while, closing for now.
