### ISSUE TITLE
Show scanner "feedback buttons" when there is no match

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14160]
Currently we hide the feedback buttons in the django admin when a scanner does not have any matched rules. It would be helpful to have the buttons even when there is no match.

**Comment by AlexandraMoga** [comment]
The feedback buttons are now available for each scanner result,  with or without matched rules. Their functionality remains unchanged.
Note that the action buttons apply only to `yara` and `customs`

**Comment by willdurand** [comment]
>  Note that the action buttons apply only to `yara` and `customs`

Yes, that's perfect. Thanks!
