### ISSUE TITLE
Prevent lookup of old statistics

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1416]
If you go to the statistics page and click on the "custom" option, you can select stats for any period. If we can, let's try and detect requests for date ranges outside of the non-archived range and raise a nice error, for example:

"Statistics over 1 year are archived, please click the link to access them."

**Comment by andymckay** [comment]
Supports: #1395

**Comment by EnTeQuAk** [comment]
This never got implemented and probably won't in the near future, looking at #1415, stats need a entirely different solution at some point that make them more scalable and usable. Archiving isn't one of them, rolling up data etc should be more future-proof.
