### ISSUE TITLE
Stop git-extraction of version sources

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14174]
We don't use the source files currently so we will remove the code to git-extract source files as well as the existing data, which means resetting the `Version.source_git_hash` values and deleting the "source" repositories on disk.

**Comment by willdurand** [comment]
@diox I am wondering how to implement the deletion of the existing git repositories on the FS (given that it will be a one-off action). Should we create a (django) command that creates some Celery tasks?

**Comment by diox** [comment]
Typically for this we use our [`process_addons`](https://github.com/eviljeff/olympia/blob/master/src/olympia/addons/management/commands/process_addons.py) command. You create your own one-off task and add it there with the queryset you want to target, setting up the task so that it can process a list of add-on ids.

We then launch the command using `manage.py process_addons --task=yourtask` (probably want `--with-deleted` in your case) and it will trigger several instances of your task, each being passed a number of add-on ids (100 by default) matching the queryset you set in the code earlier.

**Comment by diox** [comment]
(Also need to create an issue to delete the one-off task and config from `process_addons` later once we're done with it)

**Comment by willdurand** [comment]
> (Also need to create an issue to delete the one-off task and config from `process_addons` later once we're done with it)

I filed https://github.com/mozilla/addons-server/issues/14188

**Comment by willdurand** [comment]
I ran the following command in -dev:

```
./manage.py process_addons --task=delete_source_git_repositories --with-deleted
```

We'll have to run the exact same command in -stage/-prod.

**Comment by ioanarusiczki** [comment]
@willdurand Can I help here with testing?

**Comment by willdurand** [comment]
> @willdurand Can I help here with testing?

Maybe upload a new version with sources and let me know which add-on ID it was. I'll see if we have a `source_git_hash` for the latest version. If there is none, then it worked :) As for the command, I don't think we can really test anything. It removes files on disk and set some fields to an empty string in the database.

**Comment by ioanarusiczki** [comment]
@willdurand You lost me at `sources`. Could you explain or give an example?

**Comment by ioanarusiczki** [comment]
@willdurand I uploaded with source code the following: 

Version 23.0 for 619736
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/noscriptcron1

Version 1.23.7 for 619668
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/ublocktest-origintest

**Comment by willdurand** [comment]
>  Is it uploading an addon with source-code (a zip file for example) ?

Yes, when you upload a new version and its source code.

**Comment by willdurand** [comment]
> @willdurand I uploaded with source code the following:
> 
> Version 23.0 for 619736
> [reviewers.addons-dev.allizom.org/en-US/reviewers/review/noscriptcron1](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/noscriptcron1)
> 
> Version 1.23.7 for 619668
> [reviewers.addons-dev.allizom.org/en-US/reviewers/review/ublocktest-origintest](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/ublocktest-origintest)

No "source" git repository on disk, so that looks good to me :)
