### ISSUE TITLE
Avoid git-extraction loops

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14176]
It is possible to end up in a git-extraction (infinite) loop if a recoverable error occurs over and over for the same add-on.

**Comment by ioanarusiczki** [comment]
@willdurand Should I try uploading again versions for an add-on?

**Comment by ioanarusiczki** [comment]
@willdurand 
Tested on https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/noscriptcron1 version 21.0 
The admin queue did now show the extraction - which is the expected result.

Version 21.0 was broken. Right now it it visible again.
https://code.addons-dev.allizom.org/en-US/browse/619736/versions/1691239/

I also uploaded version 22.0 after 21.0 and it is also visible.
https://code.addons-dev.allizom.org/en-US/browse/619736/versions/1691240/

If results are alright I can mark it verified (you expected 21.0 to be broken).

**Comment by willdurand** [comment]
(heh, wrong button)

Looks good to me
