### ISSUE TITLE
Add creation date to some django admin pages

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14187]
### Describe the problem and steps to reproduce it:

Some django admin pages miss the creation date (and sometimes the id). They can be useful for admins, so let's add them.

I'm adding them for _UserProfile_, _Addon_, _Version_ and _File_.

### What happened?

Creation date (and sometimes even id) missing on the django admin pages for the models mentioned above.

### What did you expect to happen?

Creation date and id should be shown.

### Anything else we should know?

The following django admin pages are affected:
* /admin/models/files/file/1/change/
* /admin/models/versions/version/1/change/
* /admin/models/addons/addon/1/change/
* /admin/models/users/userprofile/1/change/

(Please replace `1` by the ID of an actual instance that exists on the environment you are testing with.)

**Comment by ioanarusiczki** [comment]
@wagnerand I verified this on admin dev and for all the pages mentioned above the `id` and `Created` field are available and the information is displayed.
