### ISSUE TITLE
Add a new model for the new add-ons "types"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14191]
We'd like to identify add-ons that are special (a bit like the recommended add-ons). We'll have some new "types" (or lists) of add-ons (better name to be determined) like:

- verified tier 1
- verified tier 2
- line add-ons
- promotional add-ons
- strategic add-ons
- recommended add-ons (that one already exists)

**Comment by eviljeff** [comment]
dupe to other issues
