### ISSUE TITLE
Return version.id with file_only data for Browse and Compare APIs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14192]
The new `file_only` version of the Browse and Compare APIs return just a `file` object, but they also need to return the `id` of the current version as well.

For QA:

After this patch, the responses to the `file_only` API requests should include both a `file` property and an `id` property, the latter of which is the `id` of the current version.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- `version id` and `file` are returned in the response when using the `file_only` parameter. 

Verified on dev for Browse and Compare endpoints.
