### ISSUE TITLE
Make only one git-extraction for a version

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14204]
Followup for:
https://github.com/mozilla/addons-server/issues/14185#issuecomment-625200114

STR:
Sometimes the git admin queue is registering two entries for the same addon version which is apparently caused by a git-extract before and after the addon signing.

Expected result is :
Git extract the version only once. 

An example:

  Version 3.2.3 on https://reviewers.addons.allizom.org/en-US/reviewers/review/release-dictionary3
  Version 4.0 on https://reviewers.addons.allizom.org/en-US/reviewers/review/%E6%9D%B1%E4%BA%AC%E3%81%A8%E5%BA%83%E5%B3%B6%E3%81%AE%E5%8E%9F%E7%88%86%E8%A8%98%E5%BF%B5%E7%A2%91testingkanji

  Admin queue: 

![entries doubled](https://user-images.githubusercontent.com/33448286/81277691-6fc8a480-905d-11ea-9391-c9a7bef85b1f.png)

**Comment by ioanarusiczki** [comment]
To add that the `sha256` is available in codemanager for each file in `Information`.

**Comment by willdurand** [comment]
This is actually a good thing because we can fix most git issues automatically.
