### ISSUE TITLE
Include the Support Site at the top of the content review page

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#14219]
### Describe the problem and steps to reproduce it:

During a content review most of the information is on the content review page, but the support site is only found on the product page.

- The URL should be checked to ensure it is a suitable link, but it is easy to forget to visit the product page to check it. (Especially as most add-ons don't list a support site.)
- When I want more information about the product and there is no Website entry it is an extra step to see if there is a support site link.

### What happened?
The content review page doesn't show the support site.

### What did you expect to happen?
If there is a support site list it on the content review page below where the Website link goes.

### Anything else we should know?

An example of an add-on with a support site but not website: https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/ray-webpage-screenshot

**Comment by linzichao** [comment]
@caitmuenster @eviljeff May I take this?

**Comment by eviljeff** [comment]
@linzichao go ahead.  It'll be adding the link to the template used in the reviewer tools (addon_details_box.html I guess).  

https://wiki.mozilla.org/Add-ons/Contribute/Code#Improve_addons.mozilla.org_.28AMO.29

**Comment by linzichao** [comment]
![support](https://user-images.githubusercontent.com/29457750/84677208-ffb51480-af60-11ea-9610-3a3415fe3729.png)

I add a support page link in the sidebar. 
Please feel free to give me any feedback. 😊

**Comment by bjherbison** [comment]
I think the support page would be better in the main column near the Website link. The website link and the support site link are closely related, and both provided by the add-on developer, while the product page and other items in the sidebar are URLs generated by Mozilla.

**Comment by eviljeff** [comment]
@linzichao yeah I agree with @bjherbison - it's better just below the addon homepage link.

**Comment by linzichao** [comment]
The commit 524782b14ee8f9ad1a7a46db5940e173d551325c shows as following:

![Screen Shot 2020-06-16 at 08 58 06](https://user-images.githubusercontent.com/29457750/84720379-7e856e00-afb0-11ea-972c-78f2f7294285.png)

**Comment by bjherbison** [comment]
That's a little better, but it still doesn't show the URL and it still isn't next to the Website link. I suggest testing using an example add-on with a Website link so you can see where that goes.

**Comment by linzichao** [comment]
@bjherbison Could you provide me the position of the Website link? Maybe because  I run on my local, I can’t find it.

**Comment by eviljeff** [comment]
A search in the addon_details_box.html file for "homepage" (or "Website") would show you.  To see it on the page you'll need to set the homepage in the addon's details in developer hub.

**Comment by bjherbison** [comment]
It's between Updated and Visibility.
![Screenshot_2020-06-16 Culture Cloud – Add-ons for Firefox](https://user-images.githubusercontent.com/4101902/84755985-3bb39e00-af90-11ea-97c3-7469c1f5c041.png)

**Comment by bjherbison** [comment]
Like the Support Site, Website is an optional field.

**Comment by linzichao** [comment]
Thanks a lot! 😊

**Comment by linzichao** [comment]
This commit 700458b6d500ec69fe14a6ae2ebc316adc999385 might fit your expecation. 😊

![Screen Shot 2020-06-16 at 22 59 14](https://user-images.githubusercontent.com/29457750/84792170-24bf8b00-b026-11ea-8ca2-be3d4da7de32.png)

**Comment by bjherbison** [comment]
Thank you. That will help me be more consistent in my reviewing.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/85132998-8c522200-b242-11ea-8824-f939c1230d15.png)


External links are also wrapped with the outgoing URL.
