### ISSUE TITLE
Unusal amount of tasks in "amo" queue

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#14213]
### Describe the problem and steps to reproduce it:
It is mentioned that the git-extraction cron job adds tasks to `addons` queue and not others. However, when we switch the feature on, we noticed that the `amo` queue started to have unusual amount of tasks.

<img width="1577" alt="Screen Shot 2020-05-07 at 4 15 40 PM" src="https://user-images.githubusercontent.com/2209111/81353631-71569480-907e-11ea-8a9e-267c2ee6d137.png">

As can be seen from the screenshot above, the `amo` queue started to have tasks at about the same time when `addons` queue started to have tasks. And if we go back to look at the historic data of this graph, the amount of tasks we see today is far more than it normally has during the same time period of any day of the week. 

From a monitoring perspective, this is definitely not normal for the `amo` queue. This queue has never had this many tasks before.

### What happened?
We switched the git-extraction feature on today after push, and we started to notice what's said above.

### What did you expect to happen?
To investigate what causes the increase of tasks in `amo` queue, and see if it's expected or it's a bug somewhere.

### Anything else we should know?
n/a

**Comment by bqbn** [comment]
This is what the queue looks like after the git-extraction job is done.

<img width="754" alt="Screen Shot 2020-05-07 at 4 59 27 PM" src="https://user-images.githubusercontent.com/2209111/81355742-42dbb800-9084-11ea-998e-238e888fda88.png">

The `amo` queue was finished almost right after the `addons` queue was finished.

**Comment by willdurand** [comment]
Here is another graph which speaks for itself:

![amo-by-wezhou](https://user-images.githubusercontent.com/217628/81394123-be3f7700-9121-11ea-8512-ee18f93c52c0.png)

**Comment by willdurand** [comment]
Last week's event only revealed the correlation between these two queues but if we look at the 30 last days or more, we also see a higher load on the `amo` queue when the `addons` queue has more tasks.

**Comment by diox** [comment]
The same workers process these queues: `priority`, `amo`, `addons`, `bandwagon`, and `users'. Since there are a limited number of workers, if there is suddenly more tasks in one of these queues to process, all the others will likely have to wait a bit and accumulate. As a result, tasks that are usually super fast and wouldn't usually appear in those graphs would show up while waiting for a worker to be free to process them.

(I don't think that's the case here, but some crons can further exacerbate this by adding a lot of tasks at specific times)

Ideally we'd redesign the queues to avoid this, but I'm not sure how practical this is...

**Comment by diox** [comment]
It happened again today, the same queues, right after we fired some tasks through `process_addons`.

**Comment by willdurand** [comment]
![amo-by-wezhou](https://user-images.githubusercontent.com/217628/81966165-628d5600-9619-11ea-8f02-34badcd11670.png)

**Comment by bqbn** [comment]
> Ideally we'd redesign the queues to avoid this, but I'm not sure how practical this is...

From ops' perspective, it seems to be easy to add a few more works to handle different queues, similar to what we're doing here: https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/olympia/manifests/celery.pp#L32-L68

But maybe you're referring to addons-server code. :)

**Comment by diox** [comment]
I'm not worried about the addons-server side, since we're already separating the queues there. My main concern is spinning up instances that would be idle for the most part. This is already an issue, but would get worse if we separate the worker queues even more.

**Comment by bqbn** [comment]
Just to clarify, in my last comment, a "worker" is not an ec2 instance, but a process running on the ec2 instance.

Most of the time in -production, there are just 3 ec2 instances in the `olympia_celery` autoscaling group. If the workers are going to be idle most of the time, the ASG won't spawn more instances.

**Comment by diox** [comment]
Ah. We can try fully splitting `olympia-priority` between several workers then - it currently deals with 5 different queues, if we had separate workers for each it could work.
