### ISSUE TITLE
prevent the `include_in_legacy` Block property from being set

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14222]
The Block property `include_in_legacy` can be set/unset currently which doesn't make any sense when legacy blocklist submission is disabled (the default).  Otherwise the Block doesn't actually get uploaded to the legacy blocklist.    It should be read-only unless `blocklist_legacy_submit` is also enabled.

**Comment by eviljeff** [comment]
I have a patch that does this https://github.com/eviljeff/olympia/commit/d5da48e5294cbb6bb812218da82b45fa1cf7b99a ... but after writing it I think I'd prefer to just drop the property on Block anyway and derive it from if `kinto_id` is set.  (the complication is we _do_ need it on BlocklistSubmission to be able to change it if legacy blocklist updates are enabled)

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and I have the following results:
- with `blocklist_legacy_submit` disabled - the include legacy checkbox is hidden in the add block form.
- with `blocklist_legacy_submit` enabled - the include legacy checkbox is displayed and can be selected

I've also run into the following edge case:
With `blocklist_legacy_submit` enabled, add a new block (with dual sign-off required) and select the include in legacy checkbox on the submission form. Then, with the switch disabled, go to [block submissions](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/299/change/?_changelist_filters=signoff_state%3D4) and approve the block (note that on the block submission form the included in legacy icon will indicate that the block is for legacy as well). After approval, open the [block detail](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26196/change/) page and notice that the included in legacy icon indicates that the block in _not_ in legacy.


@eviljeff what's your opinion on this edge case?

**Comment by eviljeff** [comment]
@AlexandraMoga I think that's fine.  Enabling and disabling the switch should be a rare event - we'll just have to be careful of any pending submissions.

**Comment by AlexandraMoga** [comment]
I'm marking this as verified fixed on -dev then.
