### ISSUE TITLE
Add a Comment field to the Approve Content action

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#14220]
### Describe the problem and steps to reproduce it:
About half of the new add-ons meet the minimum bar for appropriate content but could be significantly improved. It takes extra steps to process the review.
Steps:
- Content review an add-on. Find that the description says "Chrome" instead of "Firefox" but is otherwise reasonable.
- Add a reply noting the error or omission in the description.
- Return to the review page for the add-on.
- Scroll to the command line.
- Approve the content.

### What happened?
Extra steps are needed to review.
### What did you expect to happen?
The Approve Content option has a Comment box (like Reviewer Reply, with support for canned messages but without the option to require a response). Filling in the comment and clicking Save will add the comment and also approve the content.
### Anything else we should know?
One add-on that just took an extra step:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/ytsync

**Comment by eviljeff** [comment]
@jvillalobos

**Comment by jvillalobos** [comment]
Content review is meant to be a quick check for bad stuff like spam or deceptive content. That's why the approval action doesn't have a way to add notes. We appreciate you going the extra mile and sending additional feedback, but making that the default behavior would give other content reviewers and add-on developers an incorrect notion of what content review is supposed to be. 

If sending those notes is too much of a hassle, I would recommend not sending them anymore.

**Comment by bjherbison** [comment]
Since I only find evidence of two other volunteer reviewers in the past year the task of explaining the minimum bar for content review doesn't seem especially onerous.

And I'm not sure why the roughly one hundred suggestions I give a week (mostly to listings with no images at all) should be discouraged.

**Comment by jvillalobos** [comment]
Developer fatigue is one reason. There are a lot of emails going back and forth between AMO and developers, and the more we send the less attention they will get. We need to make sure the emails are important enough so they don't end up being ignored or sent to the junk mail folder.

I'm not saying the suggestions aren't useful, but they're not a necessary part of the process, so we're not going to invest time in changing the tooling or the process to accommodate them.
