### ISSUE TITLE
Use a setting to configure routes behind VPN

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14233]
We would like to have some routes available behind VPN only. We need a new setting configured via an environment variable.

This will be used for the scanners API (we can remove the waffle switch).

**Comment by AlexandraMoga** [comment]
The [scanners api](https://addons-server.readthedocs.io/en/latest/topics/api/scanners.html#scanners) can be accessed from an internal URL - i.e https://addons-internal.dev.mozaws.net/ - by authenticated users (amo admins) and while being connected to the VPN.
Without the VPN active, the endpoint will not respond. 

The scanners api waffle switch is no longer available.
