### ISSUE TITLE
Handle moved/deleted files better during git extraction

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14232]
We should do something like we did for code-search.

**Comment by diox** [comment]
QA: just make sure we haven't broken git extraction and code search by doing a quick test there - we'll check the rest ourselves in prod.

**Comment by AlexandraMoga** [comment]
The git extraction bit has been verified as part of other related issues, mainly in #14230 

I have verified the code search part by running a query rule on the following add-on states: listed public, unlisted, disabled add-on versions, forced disabled add-ons, deleted add-ons.

The search returned the expected results.

I'm marking the issue as verified fixed on stage.
