### ISSUE TITLE
Add add-on ID in list of git extraction entries (admin)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14231]
Let's have a new column that shows the add-on ID in the list of git extraction entries. That will be easier to see if we have the same add-on or different add-ons with the same name.

**Comment by ioanarusiczki** [comment]
@willdurand The new column is available next to `ID` and displays the add-on ID and name, it also redirects to /admin/models/addons/addon/ID/change/

![add-on id](https://user-images.githubusercontent.com/33448286/81827988-fab80c00-9541-11ea-89e3-101539310c83.png)

Verified on AMO stage with FF76(Win10).
