### ISSUE TITLE
file_only:false parameter should return complete API information

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14238]
Followup for https://github.com/mozilla/addons-server/issues/14020

When the `file_only:true` parameter is used when requesting information from the Browse or Compare API it returns only file information without version or other files.

Using `file_only:false` will return the same response as `file_only:true`. 

Expected result:
The responses with `file_only:false` should return the complete information.

Notes:
Deleting the parameter from the request will return a response with all information.

Example for https://addons-dev.allizom.org/api/v5/reviewers/addon/502991/versions/1541836/?file_only=false&file=images%2Ficon128_gray.png

![with false](https://user-images.githubusercontent.com/33448286/81651392-52b81b00-943b-11ea-9a1e-0c2be96fe49a.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg This issue is no longer reproducible. If I use the `file_only`:false it will return the complete information for the Browse and Compare API.

**Comment by bobsilverberg** [comment]
Seeing as this is verified as fixed, I guess it should be closed, too. 😉
