### ISSUE TITLE
Change git extraction CRON task to extract 10 versions at a time (no more chain)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14230]
The chain of tasks isn't reliable so let's only extract 10 versions in a row. If there are more than 10 versions to extract, we'll keep the entry in the git extraction queue (setting its `in_progress` prop to `False`). Otherwise we'll remove it from the queue (that's what we're doing already).

For QA: we don't expect a lot of changes here except that it might take more time to re-extract add-ons with lots of versions.

**Comment by ioanarusiczki** [comment]
@willdurand I uploaded:
 12 versions for https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/noscriptcron1 
and 15 versions for https://reviewers.addons.allizom.org/en-US/reviewers/review/cookie-autodeletetest2334?page=1#history - it took approximately 7 min for all versions to be displayed in code manager 

All versions were extracted successfully. 
Verified on AMO stage with FF76(Win10).
