### ISSUE TITLE
handle duplicate version strings during bloomfilter creation

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14237]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/8362254/

If an add-on has two versions with the same version string it breaks the queryset excludes() (because only one of the version ids is recorded while building up the list)

**Comment by eviljeff** [comment]
Sentry issue: [OLYMPIA-PROD-3RZ](https://sentry.prod.mozaws.net/operations/olympia-prod/issues/8362254/?referrer=github_plugin)

**Comment by AlexandraMoga** [comment]
@eviljeff how can I create an add-on with two or more versions that have the same version string? We do not allow a new version that uses the same version string as a previous one during upload, even if the previous version is deleted.

**Comment by eviljeff** [comment]
You can't create one now, but I found an add-on on -dev that has duplicate versions (that are signed, and webextensions - not that common on -dev these days)
guid = `ak-GH@dictionaries.addons.mozilla.org`.

**Comment by AlexandraMoga** [comment]
@eviljeff I don't see the mlbf from 12:30 UTC. I'm looking on -dev - https://kinto.dev.mozaws.net/v1/buckets/staging_addons_dev_allizom_org/collections/addons-bloomfilters/records

For context, I've blocked the add-on you provided and and a few others (signed webextensions)

**Comment by eviljeff** [comment]
The bucket moved to "buckets/blocklists_addons_dev_allizom_org/" recently (to match that you'd access the resulting blocks/filters on stage/prod in "buckets/blocklists"), so its:

https://kinto.dev.mozaws.net/v1/buckets/blocklists_addons_dev_allizom_org/collections/addons-bloomfilters/records

**Comment by AlexandraMoga** [comment]
Right, thanks!
There is only one entry in stash - blocked for the add-on with duplicate version strings.
