### ISSUE TITLE
Return the add-on name in the default locale in the API response

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14250]
This is in response to https://github.com/mozilla/addons-frontend/issues/9410. It has been requested that we always send the add-on name in the default locale when sending events to Google Analytics, so that it's easier to correlate events for the same add-on. We discussed a number of options for helping with this, but the feeling from product right now is that we need to use the add-on name from the default locale for every event.

As discussed in the issue, frontend could deal with this with a separate API request, but that seems sub optimal. The suggestion, therefore, is to return the add-on name for both the current locale and for the default locale from API requests to the [Add-On Detail API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail).

Does this seem like a reasonable thing to do? Also, will adding a property to the API response require a version bump for the API, and if so, how big a deal is that?

**Comment by diox** [comment]
At first glance this is going to be difficult to do without incurring a significant perf cost. The queries around translations are optimized to avoid this. If it's just for analytics, could we use the slug instead ?

**Comment by bobsilverberg** [comment]
> At first glance this is going to be difficult to do without incurring a significant perf cost. The queries around translations are optimized to avoid this. If it's just for analytics, could we use the slug instead ?

I suggested that in the issue at https://github.com/mozilla/addons-frontend/issues/9410#issuecomment-626703232 and @jvillalobos's concern was that we don't break historical data comparisons by changing the field used.

**Comment by jvillalobos** [comment]
Given the perf impact, I think it's okay to drop this and go with an alternative solution.
