### ISSUE TITLE
Allow upload_mlbf_to_kinto cron job to be manually run even when waffle is off

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14256]
For local testing, or just because we may want to in the future, it would be useful if we could trigger the `upload_mlbf_to_kinto` cron job (i.e. via `./manage.py cron upload_mlbf_to_kinto`) when the `blocklist_mlbf_submit` waffle switch is disabled.

**Comment by AlexandraMoga** [comment]
@eviljeff do you want to test this on -dev or stage?
