### ISSUE TITLE
Extraction is not completed when entries are deleted from the admin queue

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14265]
As a followup for https://github.com/mozilla/addons-server/issues/14244

1. I uploaded 2 versions for an add-on (4.0.6 and 4.0.7 in the example below)
https://reviewers.addons.allizom.org/en-US/reviewers/review/cookie-autodeletetest2334?page=1#history 
2. Immediately after the upload I went in the git admin queue and deleted the 2 entries

Result:
The last two versions of the add-on are still not extracted - 404 error 

Notes:
If I upload a new version which is extracted the previous versions with the 404 problem are extracted too and displayed.
When I let the entries in the admin queue and wait to be extracted and then delete them the issue is not reproducible.
The issue is reproducible for bulk version deletion or when a single entry is deleted reason why I don't think it's a regression. 
Another example is https://code.addons.allizom.org/en-US/browse/1004516/versions/2477589/
I tested on AMO stage with FF76(Win10).

**Comment by willdurand** [comment]
Yeah, all of that makes sense but there is no bug here, it's how the system works.

**Comment by ioanarusiczki** [comment]
@willdurand oh good to know 👍
From my perspective I was pretty sure it's a bug and that I missed it last week since I focused more on extractions only.
