### ISSUE TITLE
Unlisted add-ons are linked to the listed review page in the flagged by 'mad' review queue

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14269]
Follow up for #14085

### Describe the problem and steps to reproduce it:
1. Log in with and admin account or an Admin reviewer
2. Open the Flagged for human review queue - https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/mad
3. Identify an unlisted add-on present in the queue (any entry that has _None_ for the version string is an unlisted add-on)
4. Click on the add-on link

### What happened?
You are redirected to the listed review page, so there will be no versions to show in the add-on review history
### What did you expect to happen?
The link should point to the unlisted review page

### Anything else we should know?
- the fact that the add-on version string is _None_ instead of the actual version number is also an issue
- the 'Flagged by scanners' queue uses separate links for the listed and unlisted review pages, which could also handle cases in which an add-on has both listed and unlisted flagged versions

**Comment by willdurand** [comment]
ha oops, we should render the list just like the other existing scanner queue I guess.

**Comment by willdurand** [comment]
@AlexandraMoga I just fixed this issue and we'll push it today

**Comment by AlexandraMoga** [comment]
@willdurand looks good

![image](https://user-images.githubusercontent.com/31961530/81948469-73829b00-960a-11ea-9d14-a86de2787a71.png)

Both links are opened on the correct review page.

**Comment by AlexandraMoga** [comment]
Stage is also fixed.
