### ISSUE TITLE
The mad review queue is displaying some 'empty' entries 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14274]
Follow up for #14085 

### Describe the problem and steps to reproduce it:
1. Log in with and admin account or an Admin reviewer
2. Open the Flagged for human review queue - https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/mad
3. Examine the queue list

### What happened?
There are some 'empty' lines present in the list

### What did you expect to happen?
Only actual add-on references should be present in the list

![image](https://user-images.githubusercontent.com/31961530/81906036-47e1bf80-95ce-11ea-997f-ef412b7866e4.png)

**Comment by willdurand** [comment]
fixed by https://github.com/mozilla/addons-server/pull/14273

**Comment by AlexandraMoga** [comment]
Yes, indeed.
