### ISSUE TITLE
API stopped responding for 30 minutes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14281]
Apparently the API returned 500 errors for 30 minutes, causing https://github.com/mozilla/addons-frontend/issues/9419

these are possible causes:
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/7225411/
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5713503/
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/7225035/
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5713838/
all triggered by /api/v3/activity/mail/

And this around the same time but looked unrelated
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5404183/

**Comment by bqbn** [comment]
Only one or some specific endpoints stopped responding, right? i.e it was not the case everything stopped?

I saw the server was still spitting what seemed to be info level logs, which seemed to indicate the server was still working on other stuff.

**Comment by eviljeff** [comment]
turns out these were unrelated to the downtime.
