### ISSUE TITLE
Add-on is not removed from the mad review queue after Approval is confirmed

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14284]
Follow up for #14085 

### Describe the problem and steps to reproduce it:
1. Log in with an admin account or an Admin Reviewer
2. Open the mad review queue - https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/mad
3. Pick an auto-approved add-on from the list and Confirm Approval in the add-on review page
4. Return to the mad queue and look for the approved add-on

### What happened?
The add-on is still present in the queue

### What did you expect to happen?
Since the add-on was reviewed it should no longer be listed in the mad queue

### Anything else we should know?
- this can also happen with add-ons that have been manually Approved
- rejections will remove the add-on from the mad queue

the second entry in this list is an example of the case described:
![image](https://user-images.githubusercontent.com/31961530/81930857-d0258c00-95f1-11ea-9673-3e6f61152714.png)

**Comment by willdurand** [comment]
Looks like we don't clear the flag indeed.

**Comment by AlexandraMoga** [comment]
@willdurand this looks fixed only for auto-approved _listed_ versions for which Approval was confirmed. 

The issue is still reproducing for the following instances:
- auto-approved _unlisted_ versions for which Approval was confirmed
- versions (listed or unlisted) which have been Approved by a human (actual Approval, not just confirmation)

I can either reopen this issue or file a separate one for these remaining scenarios.
