### ISSUE TITLE
Only git-extract web extensions

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14289]
We currently git-extract everything but this isn't needed. Let's only extract addons with `type=ADDON_EXTENSION` and `is_webextension=True`.

**Comment by ioanarusiczki** [comment]
@willdurand I tested on AMO dev with FF76(Win10). 
- the static themes are not extracted anymore and won't show up in the admin queue.
- dictionaries and lang packs are no longer extracted either - are they part of the plan too?

**Comment by willdurand** [comment]
>     * dictionaries and lang packs are no longer extracted either - are they part of the plan too?

Yes

**Comment by ioanarusiczki** [comment]
@willdurand Alright, marking this verified on AMO dev with FF76(win10).
