### ISSUE TITLE
Remove `Version.source_git_hash` field

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14288]
We don't need it anymore.

**Comment by willdurand** [comment]
@diox we already have a migration on the `versions` table this week. Would it make sense to also apply the migration for this issue? Could we maybe try to merge both migrations?

**Comment by diox** [comment]
It's a bit tricky to merge the migrations since in some instances the other one has already been applied (local instances / dev).

In any case, we can't remove this database column in the next push: the field wasn't nullable, so if we remove the field & database column in next push, during the push we would get errors with the old code. We should make the database column nullable & remove the field from models this push, and remove the database column in a future push.

**Comment by willdurand** [comment]
> emove the field from models this push, and remove the database column in a future push.

Can we actually separate these two operations?

**Comment by diox** [comment]
Yes, we've done it before. Remove the field from the models but do not generate the corresponding django migration to remove the column, instead add a database migration making it nullable. Generally, to make it easier to track, we do this:
- Tag 1: Make the field nullable, generate the corresponding migration as normal, push
- Tag 2: Remove the field from models, do not generate the corresponding migration to remove the column, push
- Tag 3: Generate the database migration to remove the column, push

First step can be skipped when the column & model field was already nullable, but that's not the case here.

**Comment by willdurand** [comment]
Ha ok, I see. I was trying to find an option to `RemoveField` or something and I did not think about NOT creating the migration..

Can we do the first 2 steps in a single push given that no code uses the `source_git_hash` attribute?

**Comment by diox** [comment]
Yeah. The 3 steps variant is the safest, but generally we can merge the first two steps.

**Comment by ioanarusiczki** [comment]
@willdurand Can qa help here?

**Comment by willdurand** [comment]
> @willdurand Can qa help here?

Sure. If submitting a new version works as before (and git extracted), then it should be fine.

**Comment by ioanarusiczki** [comment]
@willdurand I uploaded several versions for https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/grammarly-for-ftest and I did not find anything unusual.
Verified on AMO dev with FF76(Win10).
