### ISSUE TITLE
Blocklist v3 is missing entries from >= 17 april

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#14301]
The v3 blocklist does not contain entries from >= 17 april. To find this date, I sorted the entries of blocklist v2, and searched for the last record that was correctly recorded in blocklist v2 but missing from blocklist v3.

* Last known good: block id 6a02c6a6-ef2e-4b46-ab67-49157ed9e49c / last_modified 1586977183602 (15 april)
  E.g. `{329fc2d4-30d7-48b7-8247-4a4bb7682da8}:2.3`

* First known bad (missing): block id 59b96bbc-20bc-4433-8596-79990aa0f670 / last_modified 1587125503251 (17 april)
  E.g. `{529b261b-df0b-4e3b-bf42-07b462da0ee8}:13.10.2`

* Last known bad (missing): block id 7790cbae-2ba6-43d9-8496-0ce311cecd00 / last_modified 1589450770496 (14 May)
  E.g. `firefox-night@mode.ubk:1.0.4`

I tested this with the latest version of the v3 blocklist (`generation_time: 1589548352624` aka 15 May) and the first ever MLBF that we [packaged with Firefox](https://hg.mozilla.org/mozilla-central/raw-file/8b4e286967c0e5b038adf4adcb9faffac5ac9c86/services/settings/dumps/blocklists/addons-bloomfilters/addons-mlbf.bin.meta.json). In both cases, all entries (that I spot-checked) as of 17 april are missing.

**Comment by Rob--W** [comment]
This has been resolved - after turning on auto import (thanks @eviljeff), the v3 blocklist is complete again.

@eviljeff Do you want to add a follow-up (e.g. a test or a feature to show the date of the most recently added entry of the v3 blocklist for easier verification), or can this issue be closed?

**Comment by eviljeff** [comment]
we're adding monitoring in #14143 so this can be closed.
