### ISSUE TITLE
Try to optimize credits page to do fewer, more predictable queries

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1430]
We have at least one for-loop that has queries in it and the other ones also seem pretty large since I'm not really sure if we have some kind of indices on them and we're doing text-matches.

This all be pretty bad.

https://github.com/mozilla/addons-server/blob/11748c0f70e5aa630bd68bb554b7a6b5106eb7b0/src/olympia/pages/views.py#L12

**Comment by eviljeff** [comment]
This page is being dropped in the new frontend, so closing this issue.
