### ISSUE TITLE
Send fxa_id, not email, in user basket sync info

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14318]
When we call the basket API to synchronize a user with our CRM, we send the `email`, but we should send the `fxa_id` instead since FxA data is also synchronized. That way we'll get more reliable email data, we'll always trust FxA data.

**Comment by diox** [comment]
This is coming from a meeting with jorgev, pmac, amorales and myself, additional notes were captured in https://github.com/mozmeao/basket/issues/522#issuecomment-630269572

**Comment by AlexandraMoga** [comment]
@diox I could make some changes that would trigger a user sync but I guess I'll need someone from the basket team to verify that the information has been updated.

**Comment by diox** [comment]
@pmac can QA test this now or do we need to wait for something on your side and/or SalesForce ?

**Comment by pmac** [comment]
We still have basket work to do to support this change. Should be soon.

**Comment by AlexandraMoga** [comment]
For background, the actions that will trigger a user sync are mentioned in https://github.com/mozilla/addons-server/issues/12206#issuecomment-527493265
