### ISSUE TITLE
Remove `extract_version_to_git.delay` calls and simplify `extract_version_to_git`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14311]
We use `extract_version_to_git.delay` before and after signing a version in order to git-extract it. We do not need to submit a celery task anymore since we have a new CRON-based extraction mechanism.

Let's define a new function that would create a `GitExtractionEntry` if the version/add-on is a web-extension.

**For QA:** please verify the git extraction process with some web extensions. There should be 2 entries per uploaded version. Uploading non-webextension add-ons should not perform extraction.

**Comment by ioanarusiczki** [comment]
@willdurand 
I verified on AMO dev with FF76(Win10):
- all uploaded [versions](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/search-by-image526) were extracted.
- [themes](https://code.addons-dev.allizom.org/en-US/browse/619781/versions/1691354/), [dictionaries](https://code.addons-dev.allizom.org/en-US/browse/619782/versions/1691356/) and [lang packs](https://code.addons-dev.allizom.org/en-US/browse/619783/versions/1691358/) are not extracted.
- I did not see 2 [entries](https://addons-internal.dev.mozaws.net/en-US/admin/models/git/gitextractionentry/) for a version yet the extractions were successful so I don't think this should be a problem.
