### ISSUE TITLE
Delete `versions.source_git_hash` column

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14312]
Once https://github.com/mozilla/addons-server/issues/14288 has been deployed, we'll be able to delete the actual DB column.

**Comment by AlexandraMoga** [comment]
I've submitted a new add-on with source files and several new versions (both listed and unlisted) for an existing add-on, each new version having a different source file. 
I didn't notice anything different in dev hub in the source file uploading and reading process. 
As for the git extraction, I was able to inspect all the new versions in code-manager, which means that the extraction was successful.
