### ISSUE TITLE
L10n: Variables in strings for localization need more context

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#14321]
### Describe the problem and steps to reproduce it:
The latest PR sent about 200 new strings to localization, many of which contain variables: https://pontoon.mozilla.org/uk/all-projects/all-resources/?string=209749 (Using Ukrainian as an example). Without context, it is difficult to understand what the string is for. In some languages, grammar rules require additional context to provide meaningful translation.

### What happened?
Variables lack context in the last released strings to localization

### What did you expect to happen?
Provide context in the string with variables in the file in the PR to localization.

### Anything else we should know?
https://pontoon.mozilla.org/uk/all-projects/all-resources/?string=209749  - using Ukrainian as an example. Scroll down the list of strings, many contain variables.

**Comment by diox** [comment]
@peiying2 can you list all strings that need context added explicitly ?
