### ISSUE TITLE
`No profile match for FxA id %s` errors on stage

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14348]
We just received a bunch of `No profile match for FxA id %s` on stage coming from `olympia.accounts.tasks.primary_email_change_event`.

Are we receiving events for all users or just AMO ?
- If it's all users, we probably shouldn't log an error - there is no matching AMO user, that's fine, FxA has plenty of non-AMO users.
- If it's not all users or if we want to keep that message, we should let logging do the formatting so that the events are nicely grouped in sentry.

https://sentry.prod.mozaws.net/operations/olympia-stage/issues/8495010/?query=is%3Aunresolved

This is so noisy that it might deserve a cherry-pick, we've got pages and pages of useless sentry events about it.

**Comment by eviljeff** [comment]
Giving the timing, it's very likely to be a regression from https://github.com/mozilla/addons-server/pull/14310

I think its
```diff
-       'z': {
+       'request': {
             'handlers': ['mozlog'],
             'level': logging.DEBUG,
             'level': logging.WARNING,
             'propagate': False
         },
```
the code in https://github.com/mozilla/addons-server/blob/master/src/olympia/accounts/tasks.py uses `z.accounts` logging namespace.

My guess is handlers is overridden to be just `['mozlog']` and there's a handler to pass all ERROR level logging to `statsd`, which I guess must end up in sentry too(?).  Though I'm not sure why `z.accounts` isn't falling back to `root` which only uses `mozlog`.  Very strange.

**Comment by eviljeff** [comment]
>If it's all users

it's all users that have changed their email address in FxA that aren't also registered with AMO (stage in this case)

**Comment by eviljeff** [comment]
#14354 changes the logging in the task to not raise ERROR so it won't get passed to sentry.  Though we should investigate what we're changed in our logging setup that caused it because we might (will) be getting other unexpected ERROR log level messages in there too.

**Comment by AlexandraMoga** [comment]
@eviljeff is any QA required for this?

**Comment by eviljeff** [comment]
no, it's just logging

**Comment by diox** [comment]
> it's all users that have changed their email address in FxA that aren't also registered with AMO (stage in this case)

Given that FxA knows whether or not an FxA account ever logged in to AMO, it's a bit disappointing that we have to listen for *all* primary email changes events and not just those that have been used for AMO, that's potentially a lot of extra events we ultimately don't care about :/ I wonder if we'll have to deal with the same thing for deletions...

**Comment by eviljeff** [comment]
> Given that FxA knows whether or not an FxA account ever logged in to AMO, it's a bit disappointing that we have to listen for all primary email changes events 

They _could_ have something on their side to filter them (I don't remember that being a thing).  Probably wouldn't work properly for amo stage - both addons.allizom.org and addons.mozilla.org use the fxa prod endpoint.

> I wonder if we'll have to deal with the same thing for deletions...

most likely!
