### ISSUE TITLE
de-kinto our remote settings integration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14346]
as noted in https://github.com/mozilla/addons-server/issues/13701#issuecomment-603377577 it's preferred that external services reference "remote settings" rather than "kinto".  The former is the product's name, the latter the codename for the current implementation.

There may be a few cases where it's not practical, but it's a sensible change (that I've been started making ad-hoc each time there's been a need to refactor).

**Comment by AlexandraMoga** [comment]
Not sure if this had an impact on the actual functionality of the feature, but I haven't noticed anything unusual. I've tested mostly on stage and I've used both AMO and kinto.
