### ISSUE TITLE
Multiple results for the same scanner ID returned when filtering by 'label'

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14344]
### Describe the problem and steps to reproduce it:
1. Send the following api request: `https://addons-dev.allizom.org/api/v4/scanner/results/?label=bad&scanner=mad`
2. Search for scanner id `10421`

### What happened?
There are three entries for the same id. This happened because the api seems to count when the block was first added and also counts each edit for that block (two edits in the case of the mentioned id)

### What did you expect to happen?
There should be only one entry for the same scanner id

### Anything else we should know?
- if you omit the `label` filter, there are no identical results returned, i.e there is only one entry per  scanner id
- the same issue can be replicated when the `label` filter is set to `good`. In this case, the same scanner id can be returned multiple times if there are multiple approval confirmations for the same version (see bug #6497 for background)
Example: `https://addons-dev.allizom.org/api/v4/scanner/results/?label=good&scanner=mad` with id `10353`

**Comment by willdurand** [comment]
We have test coverage for that in theory so I am a little surprised but I can reproduce the bug in -dev. I cannot reproduce it in a test case, though.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
There is now only one entry per scanner id when filtering by label.
