### ISSUE TITLE
handle malformed json data in legacy blocklist

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14340]
from https://sentry.prod.mozaws.net/operations/olympia-stage/issues/8370762/

> IndexError: list index out of range
  File "celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "olympia/amo/decorators.py", line 108, in wrapper
    return f(*args, **kw)
  File "python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "olympia/blocklist/tasks.py", line 75, in import_block_from_blocklist
    version_range = record.get('versionRange', [{}])[0]

**Comment by AlexandraMoga** [comment]
Idea to test this with kinto on stage:
- add a new block in kinto and omit the version range (you can do that in kinto apparently)
- enable `blocklist_auto_import` and check that the block added in kinto was imported into AMO

@eviljeff would the above test verify this issue?

**Comment by eviljeff** [comment]
yes, should do.

Also, the existing block for 
```
guid =  '{8CE11043-9A15-4207-A565-0C94C42D590D}'
id = 'e2e0ac09-6d68-75f5-2424-140f51904876'
```
should be there

**Comment by AlexandraMoga** [comment]
I've added two new blocks in kinto, without specifying a version range, and they were both imported in AMO as fully blocked add-ons (block range is `0 - *`). This is an [example](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/block/251/change/).

@eviljeff I haven't seen an entry for your guid, although I've created an [add-on](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/45dc702c32954c87b797) on stage with a matching guid.

**Comment by eviljeff** [comment]
> I haven't seen an entry for your guid, although I've created an add-on on stage with a matching guid.

It depends when you created the add-on.  The import task skips the block if there isn't a matching add-on at the time on AMO (blocking an add-on before it exists isn't a thing, so isn't supported)

**Comment by AlexandraMoga** [comment]
The add-on should have existed on stage when the latest import task ran. In any case, I can check again after the next run.

**Comment by eviljeff** [comment]
It won't be retried now - it was successfully imported at 2020-05-26 18:35 and because it didn't match any addon (your upload was on May 27) it was skipped.  That's fine though - it just needed to have not broken.
