### ISSUE TITLE
Version range can end up 'invalid' for blocked GUIDs belonging to deleted then resubmitted add-ons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14345]
### Describe the problem and steps to reproduce it:
1. As an admin, block an add-on for a fixed version range - i.e `min_version` = `0` , `max_version` = `1.1`
2. As the developer of the blocked add-on, delete the add-on from devhub
3. Submit a new add-on with the same guid (which is already blocked) and set your version string in the manifest to a value that is not covered by the existing block - i.e version can be `1.2`
4. As an admin, verify the version range of the exiting block for this particular guid 

### What happened?
The `max_version` will be `(invalid)` - see [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26197/change/)

### What did you expect to happen?
We should avoid ending up with `(invalid)` versions (I guess)

### Anything else we should know?
proposed in https://github.com/mozilla/addons-server/issues/14029#issuecomment-631499637
>I believe a better follow-up would be to prevent resubmission of a blocked add-ons after it has been deleted. We can do that by adding it to DeniedGuid.

**Comment by eviljeff** [comment]
The worse case here is _before_ an addon is blocked.  The tool only shows the versions from the current addon instance, so a range couldn't be selected that included addons uploaded before with the same guid and deleted.  (the admin could select "0" to "*" instead though)

**Comment by ioanarusiczki** [comment]
@eviljeff I could no longer reproduce the scenario on AMO stage - FF76(Win10). 

Once I resubmitted the add-on with a new version which was out of the initial range ( 0 -1.0 in my case) the [block](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/block/260/change/) showed the new version 1.2 which could be used for editing the block.
