### ISSUE TITLE
investigate our logging config and why some ERROR are going to sentry

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14355]
The underlying cause of #14348 is `log.error(...)` calls are ending up in sentry now when they weren't before.  #14310 is the likely cause because it tinkered with our logging setup though it's unclear _what_ change exactly.

**Comment by diox** [comment]
This looks slightly suspicious (for tasks specically) : https://github.com/mozilla/addons-server/blob/ac03717486f78393068b49d8e1e37d3eca9b34e6/src/olympia/amo/celery.py#L84-L94

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/pull/14310/files#diff-9a87f4a997c3c97f3e8c7768e6dc00d6L1383-L1387
```diff
-  'z.task': {
-            'handlers': ['mozlog'],
-            'level': logging.DEBUG,
-            'propagate': False
-        }
``` 
touched `z.task`'s settings.  I suppose the ` 'propagate': False` in particular stopped the errors from cascading before.
