### ISSUE TITLE
Request: Please Mark Reviewers & Ex-Reviewers 

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#1435]
Ref: `https://addons.mozilla.org/en-US/editors/leaderboard/`

Personally, I find it worthy to know who the current reviewers are. 
For example, there are occasions that I am contacted by one on the list (IRC, email etc) and I dont know if the user is still a current reviewer or an ex-reviewer.

Thank you

Bugzilla: [Leaderboard: Mark Current/Ex-Reviewers](https://bugzilla.mozilla.org/show_bug.cgi?id=1200948)

**Comment by jvillalobos** [comment]
There might a Bugzilla bug for this same purpose, but either way I agree it'd be good to fix this.

**Comment by shell15** [comment]
when we revisit this area will work out better plan than leader board.
