### ISSUE TITLE
Add statsd metrics to upload_mlbf_to_remote_settings cron too

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14359]
We added statsd metrics to the `auto_import_blocklist` job; it would be cool to have the same for `upload_mlbf_to_remote_settings` so we can add that to the dashboard too.

**Comment by AlexandraMoga** [comment]
@eviljeff is QA required for this?

**Comment by eviljeff** [comment]
I don't think there is anything you can verify, so it's fine.
