### ISSUE TITLE
Remove most version info from the response of the draft_comments API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14360]
Currently the [`draft_comments` API ](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-draft_comments-) returns a full `version` object in its response. This is a lot of data and includes the complete `file_entries` which, for add-ons with a lot of files, can be very large indeed.

Code manager does not use *any* of this data, so I suggest we remove it from the response. Although code manager doesn't need even the `versionId`, I suggest we keep that in the response as I can see it being useful, because it allows the comments to be tied back to the version to which they apply.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev by sending requests with Postman. The responses respect the specifications provided by the [docs](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#reviewers-draft-comment-detail-object) meaning that the `version` object is removed except for the `version_id`. Also the `file_entries` will no longer be present into the API responses.
