### ISSUE TITLE
Let logging do the formatting in git tasks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14379]
https://github.com/mozilla/addons-server/blob/master/src/olympia/git/tasks.py has a bunch of `log.xxx()` statements with formatting done inline instead of letting the logging module take care of it. This in turn causes the errors to not be aggregated correctly in sentry.

So instead of 
```
log.error('Git extraction failed for add-on "{}".'.format(addon_pk))
```

We want instead:
```
log.error('Git extraction failed for add-on "%s", addon_pk)
```

Of course, there are plenty more places to fix in addons-server but this one is particularly noticeable now as we do get a few extraction errors in sentry.

**Comment by AlexandraMoga** [comment]
If this is just a logging issue, could you please mark it as qa:not needed?
Thanks
