### ISSUE TITLE
olympia.activity.tasks.process_email is logging too much

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14378]
Split from https://github.com/mozilla/addons-server/issues/14355 because the `process_email` task logging in itself is an issue we might want to fix sooner.

This task is logging too much, and what's worse the logs aren't aggregated properly, so it clogs up sentry.

**Comment by diox** [comment]
Example: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/8544402/?query=is%3Aunresolved%20TextCharSet

**Comment by willdurand** [comment]
> This task is logging too much, and what's worse the logs aren't aggregated properly, so it clogs up sentry.

Do you think we should clean-up some log statements? Potentially downgrading some and so on?

**Comment by diox** [comment]
I'm removing the extra problematic `log.error()` statements in https://github.com/mozilla/addons-server/pull/14380 (we were doing `log.error(...)` followed by `log.error(message)` where we actually just wanted to include the `message` in the first statement).

I'm not sure about downgrading anything else yet, it's on a case-by-case basis. In https://github.com/mozilla/addons-server/issues/14369 we definitively want to downgrade, in other cases just making sure at least error statements need to pass their arguments correctly to allow for aggregation in sentry (less important for non-errors, since we don't aggregate them)

**Comment by AlexandraMoga** [comment]
If this is just a logging issue, could you please mark it as qa:not needed?
Thanks
