### ISSUE TITLE
Add-on still present the mad review queue after manual approval or confirming approval (for unlisted)

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14375]
Follow up for https://github.com/mozilla/addons-server/issues/14284#issuecomment-631952721

### Describe the problem and steps to reproduce it:
1. Log in with an admin account or an Admin Reviewer
2. Open the mad review queue - https://reviewers.addons.allizom.org/en-US/reviewers/queue/mad
3. Look for a listed/unlisted add-on that is still _Awaiting Review_ and manually Approve it, or confirm approval for an _unlisted_ version
4. Return to the mad queue and look for the approved add-on

### What happened?
The add-on is still present in the queue both when manually approving a version, or when confirming approval for an _unlisted_ version
### What did you expect to happen?
The add-on should no longer be in the queue

**Comment by willdurand** [comment]
mm looks like I overlooked something else :(

**Comment by AlexandraMoga** [comment]
@willdurand here are two addons that will reproduce the issues described. I've given them a suggestive name, to match the action that is expected:

https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/mad
![image](https://user-images.githubusercontent.com/31961530/82888969-b588d680-9f52-11ea-8c76-e97964587f2e.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on -stage.
Manual approvals and confirming approval for _unlisted_ versions will remove the entry from the mad queue.
