### ISSUE TITLE
Have a record of the guids and addons stored in the database in one table

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14391]
Current situation:
- [upload an xpi with guid='foo@baa']
- an addon instance with id=1 and guid = 'foo@baa' exists
- [delete addon]
- [upload a new xpi with guid='foo@baa']
- an addon instance with id=2 and guid = 'foo@baa' exists
- the addon instance id=1 has now guid = None
- there is a ReusedGUID instance that fks to addon_id=1 with guid='foo@baa'.

So if we want to search for all instances of an Addon in Addon.unfiltered with have to do `Addon.unfiltered.filter(Q(guid='foo@baa') | Q(reusedguid__guid='foo@baa'))`.  Similarly to do a values_list/values we have to do `Addon.unfiltered.filter(Q(guid='foo@baa') | Q(reusedguid__guid='foo@baa')).values_list('guid', 'reused__guid')` and process the result. (Even a reference on a single instance of Addon becomes `guid = addon.guid or addon.reusedguid.guid`)

This isn't efficient for database queries and makes code unnecessarily complex. Two options:
1. Add a second `.guid` (`.permanent_guid`?) on Addon.  Straightforward and efficient for queries.  Heavy migration needed to update the Addons table though.
2. Expand and change `ReusedGUID` to contain all Addons, even those not deleted and reused.  Would result in a 1to1 match to Addon.  Queries that needed anything _on_ Addon would still be a join though.  (Including other objects that fk to Addon, like Version)

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/pull/14389 has to use this pattern (and https://github.com/mozilla/addons-server/issues/14345 will too)

**Comment by eviljeff** [comment]
the ideal solution would be option 3:
- make `Addon.guid` non-unique and not reset it when deleted/reused.  Code changes needed in multiple places though.  Would need a `UniqueConstraint` adding (can we enforce that there is only one non-`STATUS_DELETED` addon per guid though?

**Comment by eviljeff** [comment]
@diox wdyt

**Comment by eviljeff** [comment]
> (Even a reference on a single instance of Addon becomes guid = addon.guid or addon.reusedguid.guid)

And you have to wrap this in a `try: ... except` to catch the edge case where `addon.guid is None` and there _isn't_ a `ReusedGUID` record.

**Comment by diox** [comment]
> make `Addon.guid` non-unique and not reset it when deleted/reused. Code changes needed in multiple places though. Would need a `UniqueConstraint` adding (can we enforce that there is only one non-`STATUS_DELETED` addon per guid though?)

Conditional constraints have been a thing in PostgreSQL for ages but for MySQL we'd need to upgrade to 8.0.16 or newer (or MariaDB 10.2.1 or newer).

**Comment by diox** [comment]
This seems like a fairly specific use-case, not really a fan of modifying the `Addon` model for this  - would we ever need to query against guids like this outside of the blocklist ? 

To be honest I'd prefer to try to completely prevent developers from re-using guids...

**Comment by eviljeff** [comment]
> This seems like a fairly specific use-case, not really a fan of modifying the Addon model for this - would we ever need to query against guids like this outside of the blocklist ?

Only in the reviewer tools where we currently rely on the `ReusedGUID` model, but that's even more specific (and rarely used).

Okay, seems like 2. - expanding `ReusedGUID` to be all guids - is the solution to the blocklist queries.

> To be honest I'd prefer to try to completely prevent developers from re-using guids...

That'd be a Product call 😉 
Developers can't help doing stupid things that don't fit our clean model of an addon lifecycle, like deleting them and reuploading.  We could of course just resurrect the deleted instance of the previous addon though that'd need "some changes" too.

**Comment by AlexandraMoga** [comment]
@eviljeff  Should I see anything different now when submitting an add-on with a reused guid?

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff Should I see anything different now when submitting an add-on with a reused guid?

It shouldn't affect devhub/api submission at all.  The two places where it could cause a regression are reviewer tools (the review page links to previous submissions under the same guid); and bloomfilter generation for the blocklist (not practical to verify until this hits stage on Tuesday)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I verified on AMO dev the devhub/api submission for the [mentioned](https://github.com/mozilla/addons-server/issues/14391#issue-625019068) scenario. [Rev tool](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/5f1c357086c54e33af59) pages show the previous deleted submissions under the same guid.  Another [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/addon-to-delete3) for listed versions.
- I will try tomorrow morning to add some blocks on stage and then check the bloomfilter [records](https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records) on stage in the afternoon.

**Comment by ioanarusiczki** [comment]
@eviljeff 

These are all guids I submitted, deleted, re-submitted and blocked the last submissions.

Look alright:
- `stagesubmit3-reused@guid` and `seven-reused@guid` were deleted with version `1.0` then resubmitted with version `1.0`. Both show up in the [stash-blocked](https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records).

With question marks are:
- for guid `stagesubmit-reused@guid` I see in stash-blocked versions `1.0`, `2.0`,`3.0` which were previously deleted except for [`4.0`](https://reviewers.addons.allizom.org/en-US/reviewers/review/addon-to-deletestage)  which I used when I re-submitted the addon and then blocked it on AMO.
- for guid `eight-reused@guid` I see in stash-blocked version `2` but version [`1.0`](https://reviewers.addons.allizom.org/en-US/reviewers/review/addon-to-delete2) which was deleted is not present.
- guid `stagesubmit2-reused@guid` is not present yet. This is the [block](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/99/change/)

**Comment by eviljeff** [comment]
> for guid stagesubmit-reused@guid I see in stash-blocked versions 1.0, 2.0,3.0 which were previously deleted except for 4.0 which I used when I re-submitted the addon and then blocked it on AMO.

This looks to be an edge case with timing of the auto-approval - it was signed after the block was created.  (We'd expect the admin to have manually rejected the pending version before it was blocked, but we should handle this automatically really in some way)

>    for guid eight-reused@guid I see in stash-blocked version 2 but version 1.0 which was deleted is not present.

That's fine - 1.0 wasn't signed so isn't included.

>    guid stagesubmit2-reused@guid is not present yet. This is the block

It's the same as the first case - there was a pending version when it was blocked which was signed afterwards.  It'd be picked up next time there was a Block change (_any_ change to any Block)

Thanks for finding this edge case @ioanarusiczki! I logged #14506 for follow-up.
