### ISSUE TITLE
Block refactoring - add .active_daily_user and drop FakeAddon

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14407]
splitting out some of the work from #14391

**Comment by ioanarusiczki** [comment]
@eviljeff Can qa verify this? Please add some STR
Thanks!

**Comment by eviljeff** [comment]
@ioanarusiczki there shouldn't be any change, but just check the user numbers are still there next to the guids in the blocklistsubmission add page.

**Comment by ioanarusiczki** [comment]
@eviljeff The number of users is available in the add page for a block

![the number of users](https://user-images.githubusercontent.com/33448286/83632356-c87d5580-a5a7-11ea-9154-6bb244d99e8f.png)

Verified on AMO stage with FF76(Win10).
