### ISSUE TITLE
Add a "beta" version of the stats pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14402]
In order to implement the new stats feature (powered by Big Query), we'll need new pages that look like the existing ones so that we can compare both features (the existing one and the upcoming BigQuery-based one) side-by-side.

We need a "beta" mode (like GitHub does) for that. This issue is about implementing enough logic to be able to reuse all the existing code to serve new "beta" pages.

For QA: we won't index those pages and there won't be any links to them. In order to access the "beta" version of a stats page, add `beta/` after `statistics/` in the URL:

```
# Existing URL
http://olympia.test/en-US/firefox/addon/exquisite-pizza/statistics/downloads/?last=30

# Beta URL
http://olympia.test/en-US/firefox/addon/exquisite-pizza/statistics/beta/downloads/?last=30
```

In addition, a message should be displayed:

```
You are viewing a beta feature. [...]
```

---

Once we have that, we can start querying BigQuery and change the datasource of each "beta" page (one by one if we want to).

**Comment by diox** [comment]
FWIW my initial idea for this was a waffle flag (not switch) because we could do a controlled rollout, enroll some specific users before everyone else, that kind of stuff. But beta URL works just as well for the initial phase.

**Comment by ioanarusiczki** [comment]
@willdurand I added /beta/ into the URL after /statistics/ and it works for me. I can also see a warning message saying "You are viewing a beta feature. Things might not work as expected yet. "

Example:
https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/?last=30

Verified on dev with FF76(Win10).
