### ISSUE TITLE
Remove "By Add-on Status" stats in beta mode

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14409]
According to the [PRD](https://docs.google.com/document/d/1Db0czumd_VFLOdSqsuDvlmWumqFQo8eIgGhLQ1WUPzo/edit?usp=sharing) we don't want to keep add-on status stats so let's remove it.

**Comment by ioanarusiczki** [comment]
@willdurand 
A `beta/usage/status/?last=30` page returns a 404. 

`by Add-on Status` has been removed on beta mode. 

![with beta no status](https://user-images.githubusercontent.com/33448286/83443688-d5d4fb80-a452-11ea-9688-c5ee4e3518f8.png)

Verified on AMO dev with FF76(Win10).
