### ISSUE TITLE
Add stats "by country" in beta mode

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14410]
According to the [PRD](https://docs.google.com/document/d/1Db0czumd_VFLOdSqsuDvlmWumqFQo8eIgGhLQ1WUPzo/edit?usp=sharing) we want a new page for statistics by user country. The data exists in BigQuery so it is a matter of adding new views and links.

**Comment by willdurand** [comment]
@jvillalobos the first iteration will give us short country codes (because that's what we have in Telemetry/BigQuery). Do we want to add country names instead? (I don't think we have country names in addons-server yet, so that would mean adding all the country codes + localized names).

<img width="1081" alt="Screen Shot 2020-06-02 at 10 39 48" src="https://user-images.githubusercontent.com/217628/83499311-7bbd5000-a4bd-11ea-8865-7bc6c302ae4c.png">

**Comment by jvillalobos** [comment]
Country codes are enough for an MVP, I think.

**Comment by ioanarusiczki** [comment]
@willdurand I see `by Country` being available on the left side but the beta pages seem to have a problem - a continuous loading state instead of showing the charts. 

If I switch from beta to the classic stats this issue is not reproducible. 

Please take a look https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/?last=30

**Comment by willdurand** [comment]
@ioanarusiczki yes, we have to fix https://github.com/mozilla/addons-server/issues/14484 first, but we have a patch already and we'll cherry-pickit.

**Comment by ioanarusiczki** [comment]
@willdurand The page loads for https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/usage/countries/?last=30 
or https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/beta/usage/countries/?last=30

but no data is available. I don't know if I'm using a good sample to test with or this data type is not available yet.

**Comment by willdurand** [comment]
@ioanarusiczki in -dev, you can look at this one: https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/usage/?last=30

We have only 3 GUIDs with data for beta mode, see: https://github.com/mozilla/bigquery-etl/pull/1027/files#diff-64d4d9c6969fff2608588c6366d72ac1

**Comment by ioanarusiczki** [comment]
@willdurand Yes, the [page](https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/usage/?last=30) shows the stats for 5 countries (I guess you've chosen those out of the rest of the countries)

- `group by` and `filter by` work 
- select/deselect a country from the chart works
- I could export a CSV file and json format is loaded

Thanks for the guids, I'll need those 👍
