### ISSUE TITLE
Approving a new pending add-on does not remove it from the content-review queue.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14418]
### Describe the problem and steps to reproduce it:

STR:
1. Submit a new add-on
2. Make sure it is not auto-approved.
3. Approve (not content-approve!) the add-on.

### What happened?

The add-on still shows up in the content-review queue.

### What did you expect to happen?

Since approval from code-reviewers covers content-review, it should not show up in the content review anymore.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Approving should call `AddonApprovalsCounter.increment_for_addon()` which should in turn set `last_human_review` and `last_content_review` to now, but somehow it seems that this isn't working. For the one add-on @wagnerand tried in production `last_human_review` was set correctly but `last_content_review` was null.

**Comment by diox** [comment]
Looking at the data more closely:

created          | modified         | last_human_review | counter | last_content_review
------------------|--------------------|----------------------------|-----------|-----------------------------
2020-05-27 20:36 | 2020-05-28 06:32 |  2020-05-27 20:47   | 1       |   

This is interesting: the `counter` is at 1, which indicates a creation. Yes the none of the dates match. So maybe it was created wrong, or modified after creation and that's what has blanked the `last_content_review`.

**Comment by diox** [comment]
`name` or `summary` changed this morning at 06:32 UTC, causing content-review to be reset as expected per https://github.com/mozilla/addons-server/issues/13044
