### ISSUE TITLE
Remove call to `events-xxxx.json` in stats pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14417]
It looks like we call an endpoint ending with `events-xxxx.json` in the stats pages but there is no route for it, so we redirect to `/`. This seems unnecessary so let's remove it.

**Comment by AlexandraMoga** [comment]
There is no call to `events-xxxx.json` in the stats page on -dev anymore (I've compared with stage where this call is present).
I'm not marking this issue verified yet, because the statistics page is currently broken on -dev and the root cause hasn't been identified so far.

**Comment by willdurand** [comment]
@AlexandraMoga please file a new issue for this.

**Comment by willdurand** [comment]
> @AlexandraMoga please file a new issue for this.

nevermind, I filed https://github.com/mozilla/addons-server/issues/14444

**Comment by ioanarusiczki** [comment]
@willdurand I did not see any `events-xxxx.json` call on dev while loading stats for https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/?last=365 or https://addons-dev.allizom.org/en-US/firefox/addon/terms-of-service-didn-t-read/statistics/?last=30.

Verified on AMO dev with FF76(Win10).
