### ISSUE TITLE
Use BigQuery for the "user" (updates) stats in beta mode

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14412]
Once we have #14402, we'll be able to use BigQuery. This issue is about using BigQuery for the "user" stats:

<img width="238" alt="Screen Shot 2020-05-28 at 09 26 25" src="https://user-images.githubusercontent.com/217628/83111731-539cae00-a0c5-11ea-967d-736df9b24e11.png">

**Comment by willdurand** [comment]
For QA: please reach out to me via PM for more information about how to verify this issue. I have some instructions that shouldn't be shared publicly.

**Comment by ioanarusiczki** [comment]
@willdurand Thanks for the STR.
It worked for me.
Example: 
https://addons-dev.allizom.org/en-US/firefox/addon/wollinosstest/statistics/beta/usage/?last=30
