### ISSUE TITLE
BigQuery does not return the client name (FF vs Android)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14411]
I am not sure if that's a problem but BigQuery returns client versions only, without the distinction between FF Desktop vs FF for Android (vs Fenix?).

**Comment by willdurand** [comment]
@jklukas do you know if we can have these numbers broken down by client? (instead of just per version) Is there any concept of "application" in telemetry? I only found this [page](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/update-ping.html), which seems to be about FF Desktop only so maybe we can't have stats for Android.

**Comment by jklukas** [comment]
Currently, the AMO stats queries are looking only at desktop FF (`clients_daily`). To get data from Fennec or Fenix, we would need to also reference core pings and Fenix pings. It's not obvious to me whether Fenix sends telemetry about addons.

In any case, incorporating data from mobile clients is outside of the scope I had understood for https://bugzilla.mozilla.org/show_bug.cgi?id=1633746 and would require further discussion.

**Comment by willdurand** [comment]
@jklukas thanks

@jklukas so we're good with only metrics for FF Desktop in the new pages?

**Comment by willdurand** [comment]
@jvillalobos so we're good with only metrics for FF Desktop in the new pages?

**Comment by jvillalobos** [comment]
Yes, we talked about it in bug 1572873. It's fine to exclude Fennec numbers and we'll talk to the Fenix team about adding pings on their end.

**Comment by willdurand** [comment]
Ok, cool. Closing this issue now as the data we're seeing are correct.

**Comment by jvillalobos** [comment]
FTR, it looks like adding Fenix add-ons telemetry is being tracked here: https://github.com/mozilla-mobile/fenix/issues/8920
