### ISSUE TITLE
">ÒUiR¼>ÒUiR¼>Òö¤ñª..." as platform in BigQuery data

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14420]
There is a weird platform named `>ÒUiR¼>ÒUiR¼>Òö¤ñª...` in the BigQuery DAU table.

**Comment by willdurand** [comment]
@jklukas could you please look into this? thanks

**Comment by jklukas** [comment]
There's a long tail of clients that send many odd values. We have normalization logic for OS names available, and it would likely make sense to apply that in the queries for populating these amo stats tables.

**Comment by jklukas** [comment]
Implementing os normalization in https://github.com/mozilla/bigquery-etl/pull/1014

I'm running a backfill now for 2020 data. You should only see values "Windows", "Mac", "Linux", and "Other" for backfilled days

**Comment by willdurand** [comment]
@jklukas thanks, that's indeed much better. I am still seeing `Mac OS X` and `Mac`. Is this OK? (yes according to the [`normalize_os` function](https://github.com/mozilla/bigquery-etl/blob/b68a2a7b52bbcceaad3fc13d50ebd010c8c13ce5/udf/normalize_os.sql) but why not returning `Mac` for `Mac%`)

**Comment by jklukas** [comment]
`Mac OS X` shouldn't be a possible value anymore. Can you give me the exact query you're trying?

**Comment by willdurand** [comment]
mm thanks for confirming that.

Our app aggressively cache stats data and I was looking at stale data.. Weirdly, `>ÒUiR¼>ÒUiR¼>Òö¤ñª...` was removed so I (wrongly) assumed what I was seeing was coming from BigQuery only... (I do not look at the raw BigQuery results as this datasource is already integrated in AMO).
