### ISSUE TITLE
Add a check to restrict the access to the beta stats

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14424]
Let's restrict the access to the stats beta mode to specific users first, like all users with a `mozilla.com` email address first.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on AMO dev with FF76(Win10).
- an account without `mozilla.com` doesn't have access to any beta stats (even if it's an admin) public or private.
- a `mozilla.com` account has access to beta pages without being an admin to public pages. The condition to see the beta private stats is to be an admin. 

Let me know if that's the expected for now. 
Thanks!

**Comment by willdurand** [comment]
Yes, I think it makes sense. In addition to that, a developer should be able to access their own stats in beta if and only if they have a `mozilla.com` email address.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, I tested with the developer scenario for a `mozilla.com` address.  Beta stats are visible.
