### ISSUE TITLE
Move addons-server to use beacon for Google Analytics requests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14427]
We should move to using beacon for GA requests to ensure better reliability and tighten our CSP.

To do this we need to check if we need to update from the legacy GA implementation first (we probably do since I can only find docs about configuring the transport mechanism in the newer implementation).

Doing this requires the following changes:

- Update the GA implementation on addons-server (if required)
- Configure GA to use beacon as a transport.
- Remove the GA host entry from `img-src` in the CSP
- Add an entry for a GA host to `connect-src` in the CSP.
- Test analytics are still working.

This was done for addons-frontend a few months ago in https://github.com/mozilla/addons-frontend/commit/e82335d1a6c7e5338d275531124c9fd639de7f82

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified this issue on AMO dev with FF76(Win10). 

Looks alright to me. The GA events when landing on a page look like:
![beacon collect](https://user-images.githubusercontent.com/33448286/83863092-85e48600-a72b-11ea-924f-007d85abc466.png)



I used the instructions from https://github.com/mozilla/addons-frontend/issues/8605
