### ISSUE TITLE
Reset client-side stats cache when retrieving fresh data

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14430]
I've found myself looking at stale stats data because of we cache data in the session storage. Let's make sure it won't be a problem for the beta.

**For QA:** this problem occurs when switching from old stats to beta stats for example. It can be reproduced with the following STRs:

1. navigate to: https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/usage/os/?last=30
2. open the devtools > storage > session storage
3. there should be a key named `statscache-618396`, update its value with the following json. If there is no key, please create a new one.

```
{"os":{"mindate":"2020-05-08","maxdate":"2020-06-03","2020-06-03":{"count":13,"date":"2020-06-03","end":"2020-06-03","data":{"Mac":8,"Windows":4,"Linux":1}},"2020-06-02":{"count":12,"date":"2020-06-02","end":"2020-06-02","data":{"Mac":8,"Windows":3,"Linux":1}},"2020-06-01":{"count":8794429,"date":"2020-06-01","end":"2020-06-01","data":{"Mac OS X":747992,"Linux":372116,"Solaris":56,"Android":192858,"BSD":60,"Windows":8162533}},"2020-05-31":{"count":7660861,"date":"2020-05-31","end":"2020-05-31","data":{"Windows":7064471,"Mac OS X":660435,"BSD":44,"Linux":325026,"Solaris":53,"Android":190301}},"2020-05-30":{"count":7503834,"date":"2020-05-30","end":"2020-05-30","data":{"Solaris":49,"BSD":48,"Windows":6920107,"Mac OS X":642144,"Linux":321922,"Android":188285}},"2020-05-29":{"count":9003022,"date":"2020-05-29","end":"2020-05-29","data":{"Mac OS X":754860,"Linux":380286,"Solaris":64,"Android":190963,"BSD":56,"Windows":8370906}},"2020-05-28":{"count":9405971,"date":"2020-05-28","end":"2020-05-28","data":{"Solaris":63,"Mac OS X":789509,"Linux":393028,"Android":193496,"BSD":52,"Windows":8755550}},"2020-05-27":{"count":9408804,"date":"2020-05-27","end":"2020-05-27","data":{"Solaris":62,"Mac OS X":794546,"Linux":392544,"Android":193345,"BSD":59,"Windows":8754275}},"2020-05-26":{"count":9466564,"date":"2020-05-26","end":"2020-05-26","data":{"Solaris":61,"Mac OS X":795528,"Linux":395515,"Android":193698,"BSD":66,"Windows":8812913}},"2020-05-25":{"count":9340035,"date":"2020-05-25","end":"2020-05-25","data":{"Mac OS X":768961,"Linux":388565,"Solaris":66,"Android":194179,"BSD":57,"Windows":8712136}},"2020-05-24":{"count":7942962,"date":"2020-05-24","end":"2020-05-24","data":{"Windows":7328672,"Mac OS X":686691,"BSD":50,"Linux":337092,"Solaris":55,"Android":192128}},"2020-05-23":{"count":7772811,"date":"2020-05-23","end":"2020-05-23","data":{"Solaris":55,"BSD":56,"Windows":7167937,"Mac OS X":669306,"Linux":332776,"Android":190658}},"2020-05-22":{"count":8833296,"date":"2020-05-22","end":"2020-05-22","data":{"Linux":374721,"Mac OS X":745404,"BSD":59,"Windows":8200324,"Android":193589,"Solaris":55}},"2020-05-21":{"count":8635765,"date":"2020-05-21","end":"2020-05-21","data":{"Linux":367816,"Mac OS X":738272,"BSD":53,"Windows":8001257,"Android":193525,"Solaris":56}},"2020-05-20":{"count":9376453,"date":"2020-05-20","end":"2020-05-20","data":{"Solaris":63,"Mac OS X":789091,"Linux":392612,"Android":194650,"BSD":60,"Windows":8722728}},"2020-05-19":{"count":9572585,"date":"2020-05-19","end":"2020-05-19","data":{"Solaris":61,"Mac OS X":805585,"Linux":398759,"Android":196828,"BSD":55,"Windows":8909393}},"2020-05-18":{"count":9596713,"date":"2020-05-18","end":"2020-05-18","data":{"Solaris":65,"Mac OS X":804054,"Linux":399424,"Android":195374,"BSD":68,"Windows":8940512}},"2020-05-17":{"count":8026620,"date":"2020-05-17","end":"2020-05-17","data":{"Solaris":51,"BSD":45,"Windows":7400958,"Mac OS X":698939,"Linux":339731,"Android":193220}},"2020-05-16":{"count":7811518,"date":"2020-05-16","end":"2020-05-16","data":{"Solaris":56,"BSD":50,"Windows":7195421,"Mac OS X":678620,"Linux":335933,"Android":191339}},"2020-05-15":{"count":9331509,"date":"2020-05-15","end":"2020-05-15","data":{"Mac OS X":789011,"Linux":394017,"Solaris":60,"Android":194965,"BSD":61,"Windows":8671576}},"2020-05-14":{"count":9707393,"date":"2020-05-14","end":"2020-05-14","data":{"Solaris":64,"Mac OS X":817941,"Linux":404831,"Android":196946,"BSD":59,"Windows":9036341}},"2020-05-13":{"count":9783851,"date":"2020-05-13","end":"2020-05-13","data":{"Linux":406666,"Solaris":60,"BSD":72,"Android":197475,"Windows":9111859,"Mac OS X":823972}},"2020-05-12":{"count":9833378,"date":"2020-05-12","end":"2020-05-12","data":{"Linux":408308,"Solaris":62,"BSD":59,"Android":198025,"Windows":9159191,"Mac OS X":827087}},"2020-05-11":{"count":9768615,"date":"2020-05-11","end":"2020-05-11","data":{"Solaris":63,"Mac OS X":828317,"Linux":405109,"Android":197849,"BSD":53,"Windows":9090896}},"2020-05-10":{"count":8255349,"date":"2020-05-10","end":"2020-05-10","data":{"Solaris":52,"BSD":49,"Windows":7605950,"Mac OS X":722528,"Linux":350912,"Android":197152}},"2020-05-09":{"count":8000272,"date":"2020-05-09","end":"2020-05-09","data":{"Mac OS X":699770,"Linux":343295,"Android":194653,"Windows":7362000,"Solaris":54,"BSD":52}},"2020-05-08":{"count":9172084,"date":"2020-05-08","end":"2020-05-08","data":{"Mac OS X":786462,"Linux":388310,"Solaris":60,"Android":197631,"BSD":52,"Windows":8503391}}}}
```

4. refresh the page and you should see some stats
5. now go to the same beta page: https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/usage/os/?last=30
6. you should NOT see:

<img width="461" alt="Screen Shot 2020-06-05 at 11 48 45" src="https://user-images.githubusercontent.com/217628/83862648-87f61700-a722-11ea-9ac6-4b26eee02f8a.png">

you should not see any reference to `BSD`, `Solaris`, `Mac OS X` in the table below the chart

7. instead, you should see:

<img width="270" alt="Screen Shot 2020-06-05 at 11 47 18" src="https://user-images.githubusercontent.com/217628/83862529-5b41ff80-a722-11ea-8181-52441698695f.png">

and you should only have 3 columns in the table below the chart

**Comment by ioanarusiczki** [comment]
@willdurand The Platforms look alright to me before and after page refresh. 

Interesting that after I keep refreshing the page the graph looks different for the same interval:

![the graph changes](https://user-images.githubusercontent.com/33448286/84160156-873ce800-aa76-11ea-966b-73efa2e262ee.gif)

**Comment by willdurand** [comment]
> Interesting that after I keep refreshing the page the graph looks different for the same interval:

Yeah, I noticed this too. Can you reproduce this in -stage?

**Comment by ioanarusiczki** [comment]
@willdurand I tried with this one https://addons.allizom.org/en-US/firefox/addon/bitwarden-password-manager/statistics/beta/usage/os/?last=365 but I cannot reproduce the issue.

**Comment by willdurand** [comment]
mm I think it is not so nice so I am going to reopen this issue and revert the patch for it.

**Comment by willdurand** [comment]
I'll see if I can find a fix before the tag or to cherry-pick. It's a js issue but it is tricky to understand what's causing it. It's still worth fixing because in beta, users will be able to switch back and forth between the old and beta stats.

**Comment by ioanarusiczki** [comment]
@willdurand 
- I could not reproduce the page refresh issue. 

- I've noticed that if I try to go to beta using the message if I'm on "by platform" stats (or any other except Overview) I will land on the Overview for beta.  Same case if I use the message to go from beta to deprecated statistics.
Let me know if I should file a followup.

![the URLs](https://user-images.githubusercontent.com/33448286/84361061-c6348000-abd3-11ea-95a8-83746a088b43.gif)

**Comment by willdurand** [comment]
>     * I've noticed that if I try to go to beta using the message if I'm on "by platform" stats (or any other except Overview) I will land on the Overview for beta.  Same case if I use the message to go from beta to deprecated statistics.

No, that's fine.

**Comment by willdurand** [comment]
>     * I could not reproduce the page refresh issue.

Cool!
