### ISSUE TITLE
Daily Users on Statistics Dashboard are not updated since Saturday

### ISSUE THREAD

**Issue by kyoshino** [mozilla/addons-server#14431]
### Describe the problem and steps to reproduce it:

The number of Daily Users on my extension’s Statistics Dashboard is 0 since Saturday, May 23. I also checked a couple of other extensions’ public stats, but they also had the same issue. Downloads are updated daily.

### What happened?

Daily Users are 0 for 5 consecutive days.

### What did you expect to happen?

Daily Users should be counted daily.

### Anything else we should know?

![image](https://user-images.githubusercontent.com/2929505/83222907-84bdc280-a147-11ea-9af4-03e27a5c8271.png)

**Comment by diox** [comment]
Hi,

This is tracked in https://github.com/mozilla/addons/issues/510#issuecomment-634329910
