### ISSUE TITLE
Normalize restricted email during email restriction check

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14439]
For email restriction, we compare the normalized email of the user making the request to the non-normalized email pattern in the restriction records.

This can cause restrictions not to be applied because the two do not match.

For STR, please reach out to me directly.

**Comment by AlexandraMoga** [comment]
I've tested this based on the instructions received from Andreas and the email addresses used in my tests were normalized as expected. The restrictions were also applied at submission.
