### ISSUE TITLE
Add-on Reviews should have rate-limiting controls

### ISSUE THREAD

**Issue by Standard8** [mozilla/addons-server#1444]
The other day I received 160 emails in close succession from one person who seemed to be experimenting with the review submission.

This shouldn't have happened - there should be some form of rate limiting to block multiple review comments or any public form which can nag people.

**Comment by shell15** [comment]
when we do the redesign will look over what rate limiting controls are added to which APIs

**Comment by eviljeff** [comment]
We implemented throttling for the Rating API (user reviews) at 1/minute/user so this is fixed for the new frontend now.
