### ISSUE TITLE
Call data endpoint in stats pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14444]
We introduced a regression in https://github.com/mozilla/addons-server/issues/14417, see: https://github.com/mozilla/addons-server/issues/14417#issuecomment-636021500

Stats pages are weird so I didnt notice that the charts weren't loading anymore.. and also I did not see that I was removing to API calls :|

**Comment by ioanarusiczki** [comment]
@willdurand I did not see issues while loading stats for 
https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/statistics/
or
https://addons-dev.allizom.org/en-US/firefox/addon/view-page-archive-cache/statistics/

Verified on AMO dev with FF76(Win10).
