### ISSUE TITLE
Block refactoring - addon_versions to be full versions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14451]
splitting out some of the work from #14391

`Block.addon_versions` is currently a dict of version string: tuple of some extra properties which makes it hard to maintain when the metadata is accessed in different places outside of the model and pretty unnecessary (it's only used for cases when a relatively small number of guids are being blocked.)  Lets just have it be a list of `Version` instances directly.

**Comment by ioanarusiczki** [comment]
@eviljeff Can qa verify this? Please add some STR
Thanks!

**Comment by eviljeff** [comment]
@ioanarusiczki just check in the Block edit page, and the submission page for a single guid, that the selection of versions includes all the versions of the add-on (plus "0" for min version, and "*" for max version)

**Comment by ioanarusiczki** [comment]
For the guids: `{88d58deb-97e4-45fa-85a5-98da263d4f83}` and `gmailnoads@mywebbers.com` I checked the submission page and block edit page.

- all versions are available at selection.
- 0 is available for the min version and "*" for the max.

Verified on AMO dev with FF76(Win10).
