### ISSUE TITLE
Update links in validation results to point to code manager

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14455]
This is a follow-up to https://github.com/mozilla/addons-server/issues/13634.

There are links in the validation results, when viewed by an administrator, that currently point to the legacy file viewer. These should be updated to point to the new code manager.

I am filing this as a separate issue as these links are created via JS code which might take a bit of work to update and I don't want it to block https://github.com/mozilla/addons-server/issues/13634.

Here's a screenshot showing a couple of links on the validation results page:
<img width="994" alt="Screenshot 2020-06-01 11 18 06" src="https://user-images.githubusercontent.com/142755/83423926-a9d95c00-a3f9-11ea-9ec8-de07ef5efc4a.png">

**Comment by AlexandraMoga** [comment]
@bobsilverberg since for my first observation we have #14607 as a follow up, I'll add another follow-up for my second point concerning file paths as well.

**Comment by bobsilverberg** [comment]
> @bobsilverberg since for my first observation we have #14607 as a follow up, I'll add another follow-up for my second point concerning file paths as well.

Thanks!
