### ISSUE TITLE
Do not forward review developer reply expected behavior to sentry

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14461]
The following exceptions should not be forwarded to sentry since they are expected:

https://github.com/mozilla/addons-server/blob/9a129eb7a443fe77afdf49fc439310815d8eeec9/src/olympia/activity/utils.py#L113-L115

https://github.com/mozilla/addons-server/blob/9a129eb7a443fe77afdf49fc439310815d8eeec9/src/olympia/activity/utils.py#L176-L177

**Comment by diox** [comment]
Agreed. Also, I missed them when doing https://github.com/mozilla/addons-server/pull/14380 - we shouldn't do the formatting ourselves, and let `logging` do it so that it's aggregated correctly. It matters less if we don't send them to Sentry, but it'll be more future-proof.

**Comment by diox** [comment]
I would downgrade the first to `debug`, the second to `warning`.

**Comment by wagnerand** [comment]
Thanks @diox. Could you also point me to docs or an example how to let `logging` do the formatting?

**Comment by diox** [comment]
Don't do this:
`log.something('foo %s bar %s' % (one, two))`
Do this:
`log.something('foo %s bar %s', one, two)`

Note that it doesn't matter here but `logging` only supports a specific style of formatting at a time, and we use the default `%` style, so you can't use `{}` style (like in `.format()` or `f` strings) or `$` style (like in `string.Template`).

**Comment by ioanarusiczki** [comment]
@wagnerand Without having sentry access, can qa help with some testing for this issue? If so, please add some STR.

**Comment by wagnerand** [comment]
Sorry, I don't think this needs QA.
