### ISSUE TITLE
Add model to track pending version rejection

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14462]
For https://github.com/mozilla/addons-server/issues/14454 we need a new field to track when a version is pending rejection. Since we have `VersionScannerFlags` already, let's move it to the `versions` app under `VersionReviewerFlags`, and add a `pending_rejection` field to it.

**Comment by diox** [comment]
QA: make sure the reviewers queue for addons flagged by "mad" scanner still work (like was verified in https://github.com/mozilla/addons-server/issues/14085)

**Comment by AlexandraMoga** [comment]
The `mad` review queue continues to work as before.
I'm marking the issue as verified fixed on -dev.
