### ISSUE TITLE
Make stats pages private

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14463]
According to this [PRD](https://docs.google.com/document/d/1Db0czumd_VFLOdSqsuDvlmWumqFQo8eIgGhLQ1WUPzo/edit), we would like to remove the `public_stats` setting. Developers (and admins) will be the only users who can have access to the stats pages.

**Comment by willdurand** [comment]
@jvillalobos is that accurate? Where should we display the link to the stats pages in DevHub? Do we want to keep the link in the frontend for authenticated users?

My plan would be to:

1. make sure we have links to access the stats pages
2. remove the `public_stats` setting

In the meantime, we'll have to reach out to developers who have add-ons with public stats.

**Comment by willdurand** [comment]
Also, semi-related to this: for now we'll keep the existing pages as they are currently (no UI changes). Is that OK? "Moving" the pages to the DevHub look&feel will be a bit challenging but it also sounds more like a code quality issue than a feature _per se_.

**Comment by jvillalobos** [comment]
> Where should we display the link to the stats pages in DevHub?

There are two links on DevHub that I know about: `View Statistics Dashboard` in the navigation sidebar in the edit pages of an add-on, and a `Statistics` link in the Manage My Submissions page (`/developers/addons`).

> Do we want to keep the link in the frontend for authenticated users?

Yes.

> In the meantime, we'll have to reach out to developers who have add-ons with public stats.

Let me know when you expect this change to happen and I'll coordinate comms with @caitmuenster 

> for now we'll keep the existing pages as they are currently (no UI changes). Is that OK?

Yes, that's okay for now. As I noted above, there are links in DevHub already, so the experience will be the same.

**Comment by willdurand** [comment]
> There are two links on DevHub that I know about: `View Statistics Dashboard` in the navigation sidebar in the edit pages of an add-on, and a `Statistics` link in the Manage My Submissions page (`/developers/addons`).

Oh mm, sorry. I didn't see these links for some reasons. Great!

> Let me know when you expect this change to happen and I'll coordinate comms with @caitmuenster

@jvillalobos I think next week (2020.06.11) if that's fine?

> Yes, that's okay for now. As I noted above, there are links in DevHub already, so the experience will be the same.

Perfect, thanks

**Comment by ioanarusiczki** [comment]
@willdurand 
- the "public setting" is no longer available in dev hub and addons are no longer "public". All pages I verified are displayed as "private". 

Observations:

- unlike last [week](https://github.com/mozilla/addons-server/issues/14424#issuecomment-637331704) an admin with a gmail e-mail address has access to all stats (just like an admin with a mozilla.com account).
- a mozilla.com developer account can see beta stats only for the personal addons. An edge case here is that they get a 404 for "[View Statistics Dashboard](https://addons-dev.allizom.org/en-US/developers/addon/8ece2234f10e44c4b782/edit)" link from dev hub for their unlisted add-ons.
- with admin accounts the "View Statistics Dashboard" link is accessible from "Edit product page" link for unlisted add-ons.
- the "Statistics" link from Manage my Submission page is only available for listed add-ons.

**Comment by willdurand** [comment]
>     * unlike last [week](https://github.com/mozilla/addons-server/issues/14424#issuecomment-637331704) an admin with a gmail e-mail address has access to all stats (just like an admin with a mozilla.com account).

Yeah, that's correct. The waffle "flag" allows admins too.

> a mozilla.com developer account can see beta stats only for the personal addons. An edge case here is that they get a 404 for "[View Statistics Dashboard](https://addons-dev.allizom.org/en-US/developers/addon/8ece2234f10e44c4b782/edit)" link from dev hub for their unlisted add-ons.

Does that mean developers of unlisted add-ons cannot see beta stats?

> the "Statistics" link from Manage my Submission page is only available for listed add-ons.

Yeah, that is fine.

**Comment by ioanarusiczki** [comment]
@willdurand 

> Does that mean developers of unlisted add-ons cannot see beta stats?

Yes, I think so. Developers of unlisted addons cannot see the stats. I tried for this addon from a gmail account and I get a 404 https://addons-dev.allizom.org/en-US/firefox/addon/154b2ca27eff421e93d7/statistics/beta/?last=30. I only have access as an admin.

**Comment by willdurand** [comment]
> Yes, I think so. Developers of unlisted addons cannot see the stats. I tried for this addon from a gmail account and I get a 404 [addons-dev.allizom.org/en-US/firefox/addon/154b2ca27eff421e93d7/statistics/beta/?last=30](https://addons-dev.allizom.org/en-US/firefox/addon/154b2ca27eff421e93d7/statistics/beta/?last=30). I only have access as an admin.

Indeed. Can you file a different issue for this? I've got a patch for it.

**Comment by ioanarusiczki** [comment]
@willdurand Done https://github.com/mozilla/addons-server/issues/14582
