### ISSUE TITLE
Refactor Block code

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14468]
There's a fair bit of duplicate functionality in how guids are turned into Block objects that I've been putting off landing in other patches to avoid unnecessary review noise.

**Comment by eviljeff** [comment]
QA: no functional changes here, just some code refactoring in the blocklist admin tool - make sure submitting new blocks and edits work as before.

**Comment by AlexandraMoga** [comment]
I've verified the following scenarios and they continue to work as before:
- adding new single block
- adding multiple blocks
- editing existing block
- deleting/multiple deleting blocks
- the dual sign-off process

I'm marking the issue as verified fixed on stage.
