### ISSUE TITLE
Add a button to upload an image to the primary hero image folder

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14472]
This supports #14471 

Add a button to the primary hero admin that allows a user to upload an image from their computer to be stored on the server - this will allow the admin to select the image from the photos in the shelf.

Code to resize and/or adjust the image, as well as code changes to make use of these images, will be covered in other issues.

**Comment by ioanarusiczki** [comment]
@xlisachan I verified this on AMO dev - FF77(win10):

- There's a Primary hero images section and the "+add primary hero image upload" button is available. 
- I could upload .png and .jpg files. I could also delete uploads.

- A .jpg of 1.37MB is already too large, I receive an error: 
413 Request Entity Too Large
nginx
Let me know if that's expected.

**Comment by xlisachan** [comment]
@ioanarusiczki Thanks for verifying it! I am currently working on #14475 to resize the uploads; it should fix the error. :)

**Comment by bobsilverberg** [comment]
> @ioanarusiczki Thanks for verifying it! I am currently working on #14475 to resize the uploads; it should fix the error. :)

Will that fix this error? As it's coming from nginx, I'm wondering if it's about the size of the file being too large upon upload? If so, is there anything we can do about checking that before the file even makes it to the server?

**Comment by eviljeff** [comment]
> Will that fix this error? As it's coming from nginx

1MB seems a little low for filedata in a POST, I agree.  @bqbn does that limit sound correct for the nginx settings?

**Comment by bqbn** [comment]
The proxy for addons-server has a much larger limit than 1MB. The error probably comes from a proxy for a different component of AMO. 

How do I reproduce the error so that I can pinpoint which proxy this is related?

**Comment by eviljeff** [comment]
@bqbn @ioanarusiczki would have the full details, but I believe from the comments above it'd using https://addons-internal.dev.mozaws.net/en-GB/admin/models/discovery/primaryheroimageupload/add/; choosing a custom image, and saving the form to submit the image.

**Comment by ioanarusiczki** [comment]
@eviljeff  Oh sorry, I thought @bqbn needs more info than I could provide.
So, yes, with access to[ admin dev ](https://addons-internal.dev.mozaws.net/en-US/admin/) go to [primary hero image upload](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/primaryheroimageupload/) and try uploading an image > 1 MB in size.

**Comment by bqbn** [comment]
The above PR (https://github.com/mozilla-services/cloudops-deployment/pull/3931) tries to address the nginx `413 Request Entity Too Large` error, and we have deployed it to -stage and -dev.

Please test it and let us know how it works. It'll go out to -prod tomorrow (7/2) if no regression is found.

**Comment by xlisachan** [comment]
@ioanarusiczki I don't have access to -stage/-dev yet, can you please test this? Thank you!

**Comment by ioanarusiczki** [comment]
@xlisachan I was able to upload large images - 5 MB , 23 MB.

Verified on dev and stage - FF77(Win10).
