### ISSUE TITLE
Adjust the hero API code to deliver uploaded images

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14473]
Supports https://github.com/mozilla/addons-server/issues/14471
Depends on #14472, #14474 

After #14472 and #14474 land, adjust the code for the hero API to deliver images from the location where the uploaded files are stored, as opposed to from the CDN where they are currently stored.

Question: Will that new location also be served via a CDN, and if not are there any issues with not serving the images from a CDN?

**Comment by AlexandraMoga** [comment]
@eviljeff if #15199 reverts what was done for this issue, should the milestone be moved to next week as well?

**Comment by eviljeff** [comment]
re-opened because the commit was reverted.

**Comment by eviljeff** [comment]
> I've noticed that on -dev and stage, the Promoted addons model includes only images that were added through the new Primary hero images tool. The images used previously are gone although #15176 is not yet closed?

I'm not following what the problem is, but open an issue if it's reproducible after the revert lands.

**Comment by ioanarusiczki** [comment]
@eviljeff I've noticed that the images can be attached to recommended addons from the promoted model because they show up on the frontend now but they are not resized at a standard dimension as they were before. 

![resized](https://user-images.githubusercontent.com/33448286/95996554-785aad80-0e3b-11eb-9d9f-515cdef44150.gif)

**Comment by ioanarusiczki** [comment]
@eviljeff https://github.com/mozilla/addons-server/issues/15729 is clarified so if there's anything else I should be testing here, let me know.

**Comment by ioanarusiczki** [comment]
@eviljeff Not related to this but while testing today I've noticed https://github.com/mozilla/addons-server/issues/15737
