### ISSUE TITLE
Move the existing primary hero images into the same location as uploaded images

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14474]
Supports https://github.com/mozilla/addons-server/issues/14471
Depends on #14472

After #14472 lands, we will want to be able to serve the existing images from the same location as the uploaded images. It probably makes sense to copy them first, as opposed to moving them, so the site can still work as usual until work on the API is completed.

**Comment by bobsilverberg** [comment]
@devaneymoz I understand that you had a conversation with Lisa Andrew about uploading the old images to the new location. There was an issue with the sizes from the first time you did this, so it would be best if you download the existing images first, and then upload them to the new location. If you can let us know once that's done that would be great. Thanks!

**Comment by bobsilverberg** [comment]
@devaneymoz Do you know if all of this has been done yet?

**Comment by eviljeff** [comment]
I _think_ we did this.  Either way, the new hero images are there now.
