### ISSUE TITLE
"Signed and ready to download" email is being sent even if add-on has not been signed

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1448]
We currently send the "... has been signed and is ready for download" email even if the add-on has not been signed.

This could happen if the author didn't specify compatibility to Firefox in the install manifest.

A possible solution would be to add a validator FAIL if an unlisted submission does not have Firefox as an applicationTarget in the install.rdf.
The only reason developers submit their unlisted add-on is to get a signed file for use in Firefox. If the file is not being signed (because of missing Firefox compat), we should fail and tell the developer.

**Comment by wagnerand** [comment]
Just had another inquiry by an affected developer.

**Comment by wagnerand** [comment]
STR:
1. Submit 
[no_Fx_target_app.zip](https://github.com/mozilla/addons-server/files/534193/no_Fx_target_app.zip) or [old_target_app.zip](https://github.com/mozilla/addons-server/files/534192/old_target_app.zip)
AMO.

Expected results:
Some message that the file has not been signed in either case. Also, don't send the email that we signed it.

Actual result:
After submitting, the page says:
```
Version Signed
You’re done! This version is signed and ready to for self-distribution.You can download it by clicking the button below. 
```
We also send an email saying:
`Your add-on, ..., has passed our automatic tests and is now signed and ready for you to download at ...`

Additional information on the files:
The files have a _targetApplication_ element in the install manifest, but for
* _no_Fx_target_app_, the add-on is not targeted for Firefox, which is usually (but not always) are mistake by the developer.
* _old_target_app_, the file add-on a _maxVersion_ of `<4.0`, in which case we don't sign. This is basically always a developer mistake, some just never update that value, or copy and paste it from somehwere else.

**Comment by jvillalobos** [comment]
I suppose #3673 is a dupe of this one.

**Comment by muffinresearch** [comment]
@wagnerand this is pretty old - does this problem still exist?

**Comment by wagnerand** [comment]
Technically, the problem probably still exists, but it pretty much applies to legacy (incl TB and SM) only. Since they will be moved eventually, I believe we can close this bug as wontfix.
