### ISSUE TITLE
Add a waffle flag to rollout the beta stats pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14491]
We'd like to rollout the beta stats for more users in the near future (like start with 5-10-25% of our user base). In order to do this, we'll need a waffle flag. This flag will replace the email address check introduced in https://github.com/mozilla/addons-server/issues/14424.

This flag will also add links to beta stats for _unlisted_ add-ons.

**Comment by willdurand** [comment]
@jvillalobos thinking about it, I believe we can ship this flag next week and maybe start to rollout for 5% of the users or something and target 100% on July 2nd. WDYT?

The reason why we'd like to have a flag and a progressive rollout is that we don't know how BigQuery will behave in production. It seems fine but better safe than sorry.

**Comment by willdurand** [comment]
> This flag will also add links to beta stats for _unlisted_ add-ons.

Also, I think users who will be able to see the beta stats will only see the beta stats (and not both versions of the stats). That will make the transition easier.

**Comment by jvillalobos** [comment]
We want to give developers time to export their old stats, if they want to, so they need a clear date after which they shouldn't expect the old dashboard to work. I see a couple of options: (1) do the rollout, but start later (06/18) to give devs more time, or (2) give developers control over the rollout, maybe by having a switch in the stats page (it should be fine if it's a one way switch, as long as we are clear about it).

**Comment by willdurand** [comment]
@jvillalobos ha, right. Maybe we could use the flag to enable the beta stats by default and add a link to the "old" stats from the beta pages?

**Comment by jvillalobos** [comment]
That would work!

**Comment by willdurand** [comment]
@jvillalobos so I update the messages a bit and we have two messages now:

1. When a user lands on any of the beta stats pages (if the user did not have access to the beta, it would return a 404):

<img width="1016" alt="Screen Shot 2020-06-05 at 14 21 54" src="https://user-images.githubusercontent.com/217628/83875788-07421580-a738-11ea-9438-92845cacf02d.png">

2. When a user who has access to the beta lands on any of the "old" stats pages:

<img width="1012" alt="Screen Shot 2020-06-05 at 14 22 07" src="https://user-images.githubusercontent.com/217628/83875791-08734280-a738-11ea-9b5a-fd99e5ef4bc2.png">

I'd be happy to reword these two messages if needed.. WDYT?

**Comment by willdurand** [comment]
> This flag will also add links to beta stats for _unlisted_ add-ons.

This will be implemented too but we won't have any download stats for unlisted only (empty graphs). What should be do in that case? It's tricky to think in terms of unlisted vs listed add-ons because (and you know it) channels are set on versions and not on add-ons.

**Comment by willdurand** [comment]
@jvillalobos you can get an idea of what it will look like for a user who gets access to the beta from there: https://addons-dev.allizom.org/en-US/developers/addon/some-addon/edit

The two links to the "stats dashboard" (on this page and in "manage my submission") should point to the beta directly. There is a message explaining a bit and a link to go to the old stats pages.

**Comment by jvillalobos** [comment]
> I'd be happy to reword these two messages if needed.

The messages look good. Just add a period to `Take me to the new dashboard.`

> This will be implemented too but we won't have any download stats for unlisted only (empty graphs). What should be do in that case?

I think it's okay that the download graphs don't just any data in that case. A nicer way to tackle this would be to hide all Download charts when they have no data, which should only happen when you're unlisted.

> you can get an idea of what it will look like for a user who gets access to the beta from there

Looks good!

**Comment by ioanarusiczki** [comment]
@willdurand 

I tested the regular users for:

value "unknown" and percent is 50.0 -> 2 profiles had the old stats and 2 profiles had the beta stats
value "unknown" and percent is 99.99 -> all 4 profiles had the beta stats
value "unknown" and percent is 0.0  -> all 4 profiles had the old stats (even if the value of the cookie was "True", probably  because I tested previously the 99.99 using the same profiles )

With value "unknown" and percent 50.0 I could force cookie to change from False to True (and back).

**Comment by ioanarusiczki** [comment]
@willdurand About the cookie, I tested today to see the state while also changing the beta flag percent.

Two scenarios to mention:

First scenario:

1. I created a new profile and login, beta stats flag is 0% - cookie is not available in Storage and the old stats are available.
2. Increased percent to 50% - cookie shows up and it’s value is true, beta stats are available
3. I change the flag back to 0% - old stats are back , but the value of the cookie remains “True”.

I see that the expiration date is / Max-Age:"Sun, 12 Jul 2020 12:45:10 GMT" 

Probably that is why the value is still "True".  Yet the user can't see the beta stats anymore.

Second scenario:

1. On a new profile, I login and I set the beta flag to 0% - cookie is not available yet in Storage and the old stats are displayed.
2. I changed the beta flag percent to 10% - I get the “False” value in Storage and I still see old stats. 
3.  I increased it to 99.9% - value is remains “False” and the user has access to old stats. 

 In this case the expiration date is "Session" so I think  it should go to "True" and show beta stats. I restarted the browser but I still get the "False" value with the old stats.

**Comment by willdurand** [comment]
> Probably that is why the value is still "True". Yet the user can't see the beta stats anymore.

When the flag is 0%, the cookie is not deleted but the beta is unavailable.

> In this case the expiration date is "Session" so I think it should go to "True" and show beta stats. I restarted the browser but I still get the "False" value with the old stats.

heh. The cookie expiration date (`WAFFLE_MAX_AGE`) is too far in the future (1 month) so we'll need to change that :( cc @diox

**Comment by willdurand** [comment]
So this is bad and I didn't think enough about the implications of using a cookie like this. We could reduce the default max age of the cookie but then users who had access to the beta one week might not have access to it the week after... This would also require a hotfix next week, I guess? Otherwise we won't be able to leverage this flag.

The alternative would be to set the flag to 50% or 70% next week and then complete the rollout to 100% in 2 weeks (by setting the flag to "available to everyone" instead of using the `percent` value). No code change required.

We enabled this flag for 1% of our users today for ~6h. So we can assume that most of the authenticated users who looked at their stats during this time won't have access to the beta (only the 1% of those users will have the cookie with `beta=True`).

@diox WDYT?

**Comment by willdurand** [comment]
(I deleted a comment where I was explaining things based on a misunderstanding)

Anyway, I think everything works as expected. We're using the waffle rollout mode and it seems to work fine, even if FF's behavior around session cookies is weird.

**Comment by ioanarusiczki** [comment]
@willdurand Thanks for looking into it. I'll mark this issue verified on AMO dev with FF76(Win10).
