### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14496]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/usage/
2. Open the devtools > console

### What happened?

- The charts don't load on the page.
- JavaScript errors in the console

### What did you expect to happen?

The charts load.

### Anything else we should know?

```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://addons-dev-cdn.allizom.org/static/js/impala-min.js?build=aad65070-5ed7e28e:1
impala-min.js:1:18938
    <anonymous> https://addons-dev-cdn.allizom.org/static/js/impala-min.js?build=aad65070-5ed7e28e:1
```

```
Uncaught TypeError: fe is not a function
    <anonymous> https://addons-dev-cdn.allizom.org/static/js/zamboni/stats-min.js?build=aad65070-5ed7e28e:1
    <anonymous> https://addons-dev-cdn.allizom.org/static/js/zamboni/stats-min.js?build=aad65070-5ed7e28e:1
stats-min.js:1:10460
```

**Comment by willdurand** [comment]
@bobsilverberg I added the statistics label because that's where I found the error but it works in stage so it is something new-ish on `master`.

**Comment by bobsilverberg** [comment]
I cannot reproduce this locally, although when I go to that page for an add-on it tells me there are no statistics, so I'm not sure if I need populated statistics to be able to reproduce this error. The page seems fine to me, the GA code is executing, and I don't see any errors in the console about `jQuery`. 

@eviljeff suggested it might be a problem with the pipeline not being able to handle the JS for the new analytics code, but I don't think I'm doing anything fancy in there. Is there somewhere that we might be able to see any build failures?

**Comment by bobsilverberg** [comment]
I do see an error on the devhub landing page (on dev):

```
ReferenceError: $ is not defined js-min.js:1:1
    <anonymous> https://addons-dev-cdn.allizom.org/static/js/devhub/new-landing/js-min.js?build=aad65070-5ed7e28e:1
```

which sounds similar (`$` tends to be `jQuery`), so it's not limited to the stats pages.

**Comment by bobsilverberg** [comment]
I think it's worth just putting the file I deleted back and see if that fixes it. I'll try that. I'm not sure it's testable without landing the change on dev though.

**Comment by diox** [comment]
You should be able to test this locally by using `DEBUG = False` in your `local_settings.py` and re-running assets generation (`make update_assets`, which is typically called during `make update_docker` / `make update`). From that point, your local instance would use concatenated assets just like dev/stage/prod. Just don't forget to reset `DEBUG` afterwards.

**Comment by willdurand** [comment]
well I can't reproduce locally, even with `DEBUG=False` so it might be a bug in the pipeline instead. I see JS errors during compilation.

**Comment by willdurand** [comment]
> @eviljeff suggested it might be a problem with the pipeline not being able to handle the JS for the new analytics code, but I don't think I'm doing anything fancy in there. Is there somewhere that we might be able to see any build failures?

Yeah, there is a problem related to the GA code. I think it is because of the trailing comma here: https://github.com/mozilla/addons-server/commit/43b45fdd4be32a5f48e41dc40c293bfdc3a8165b#diff-ce09cc0b979a320d261b569bd43f9669R12

**Comment by eviljeff** [comment]
mmm, if it's trailing commas then there's a second one:
https://github.com/mozilla/addons-server/commit/43b45fdd4be32a5f48e41dc40c293bfdc3a8165b#diff-ce09cc0b979a320d261b569bd43f9669R39

**Comment by willdurand** [comment]
yep, I saw that one too

**Comment by ioanarusiczki** [comment]
@willdurand I did not see those errors in Console while checking some stats pages on AMO dev.
