### ISSUE TITLE
The code manager files are not shown for a deleted addon

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14498]
Depends on https://github.com/mozilla/addons-server/issues/14607
Followup for https://github.com/mozilla/addons-server/issues/13634#issuecomment-638219693

STR:
When an add-on is uploaded (I waited for extraction and I could open the files) and then deleted the API responds with a 404 

Examples:
https://code.addons-dev.allizom.org/en-US/browse/619895/versions/1691482/
https://code.addons-dev.allizom.org/en-US/browse/619894/versions/1691481/

Expected:
Maybe the files should be visible for the deleted addons - the legacy viewer shows them. 
Probably needs a discussion. 

This is reproducible on AMO dev with FF76(Win10).

**Comment by bobsilverberg** [comment]
@wagnerand Do we have any idea if this is a new regression, or if this never worked?

**Comment by wagnerand** [comment]
> @wagnerand Do we have any idea if this is a new regression, or if this never worked?

I am not sure. We fixed issues around deleted versions, but I don't know whether we included or tested deleted add-ons at the time.

**Comment by bobsilverberg** [comment]
@wagnerand I've got a fix for the fact that the API for the browse information returns a 404, but I noticed, after fixing that, that I'm now seeing a 404 for the `validation.json` file and the draft comments API request, so I guess those too are not set up to work with deleted add-ons. I assume that everything should "just work" for deleted add-ons?

Also, the code is currently set up so that a user needs to have the `Addons:ViewDeleted` permission in order to be able to have the Browse API return data (and not just a 404) for a deleted add-on. Should we keep that requirement in place? Will reviewers who need to be able to review code for deleted add-ons have the `Addons:ViewDeleted` permission?

**Comment by wagnerand** [comment]
> @wagnerand I've got a fix for the fact that the API for the browse information returns a 404, but I noticed, after fixing that, that I'm now seeing a 404 for the `validation.json` file and the draft comments API request, so I guess those too are not set up to work with deleted add-ons. I assume that everything should "just work" for deleted add-ons?

It would be cool if we validation messages worked. We probably don't need to write comments to deleted add-ons (however, retrieving existing comments should work).
 
> Also, the code is currently set up so that a user needs to have the `Addons:ViewDeleted` permission in order to be able to have the Browse API return data (and not just a 404) for a deleted add-on. Should we keep that requirement in place? Will reviewers who need to be able to review code for deleted add-ons have the `Addons:ViewDeleted` permission?

Yes, we should keep that as is.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I'll wait for the fix of https://github.com/mozilla/addons-server/issues/14655
I found a couple of files that load, an [example ](https://code.addons-dev.allizom.org/en-US/browse/619881/versions/1691458/). But most of them don't load content.

**Comment by ioanarusiczki** [comment]
@bobsilverberg The deleted addons are available now:
- an admin has access to listed/unlisted deleted addons.
- addon reviewers and content reviewers can see the files for deleted listed addons. The Addons:ViewDeleted permission is required.
- unlisted addon reviewers have access to the deleted unlisted addons. The Addons:ViewDeleted permission is required.

Verified on AMO stage - FF76(Win10).
