### ISSUE TITLE
refactor UserProfile

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14511]
It's got an amount of redundant code for handling banning and deleting users that could be cleaned up to make #13896 more straightforward.

**Comment by eviljeff** [comment]
QA: this should only affect the admin - check that single user deletes work, and single and multi user ban actions correctly ban the users and delete their content.

**Comment by AlexandraMoga** [comment]
Using the admin User profiles model, I've tested user deletions, single and multiple user banning and all these actions are working as expected:
- account is deleted => user created content is cleared
- account is banned => users are deleted and their content is cleared 
- account with add-ons is banned => user is deleted, content is cleared, add-ons are disabled

I'm marking the issue as verified fixed on -dev.
