### ISSUE TITLE
Add ips from user restriction history in knowns ips field in the user admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14518]
The user admin has a knowns ips fields listing, well, known ips. The source for this are `Ratings` and `last_login_ip` on the `UserProfile`. There is another source available though, and that's `UserRestrictionHistory`, so it would be good to use it.

Maybe we should do a `UNION DISTINCT` in MySQL to deal with that while we're at it. Something like (need to see if there is a less verbose way of doing this with the ORM, and also exclude empty string / nulls):
```python
Rating.objects.filter(user=obj).values_list('ip_address', flat=True).order_by().union(
UserRestrictionHistory.objects.filter(user=obj).values_list('last_login_ip', flat=True).order_by(),
UserRestrictionHistory.objects.filter(user=obj).values_list('ip_address', flat=True).order_by(),
UserProfile.objects.filter(user=obj).values_list('last_login_ip', flat=True).order_by(),
)

**Comment by diox** [comment]
Note that a better way to deal with this would be to add to the `IPLog` created for https://github.com/mozilla/addons-server/issues/16636 when a user creates a rating, logs in, is restricted, and just run a query against that model.

**Comment by diox** [comment]
> Maybe we should do a `UNION DISTINCT` in MySQL to deal with that while we're at it. Something like (need to see if there is a less verbose way of doing this with the ORM, and also exclude empty string / nulls):

From testing on stage, MySQL isn't super efficient when doing that. It makes a bunch of temporary tables...

> Note that a better way to deal with this would be to add to the `IPLog` created for #16636 when a user creates a rating, logs in, is restricted, and just run a query against that model.

That's a more promising approach but would require a gigantic data migration to backfill the `IPLog`, so let's skip for now.

**Comment by ioanarusiczki** [comment]
@diox I think testing from https://github.com/mozilla/addons-server/issues/14547#issuecomment-884095845 covers this too but if not, let me know.
