### ISSUE TITLE
Send an email to user after their account is deleted

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14512]
We've wanted to send an email to users when their account is deleted but never got around to do it. The copy for the email exists and had been validated at the time: https://docs.google.com/document/d/1Zuos9dZINSaX4vj4eNu0jT18DMc_HkB_Nm84x3iL5_g/edit

Open questions:
- Should we do this for banned users as well ? Even users banned in bulk ?
- Should we send it when we're deleting the AMO account because the FxA account is deleted after doing https://github.com/mozilla/addons-server/issues/13896 ?

**Comment by jvillalobos** [comment]
@caitmuenster might want to give that copy a second look, since it's very old.

> Should we do this for banned users as well ? Even users banned in bulk ?

No. 

> Should we send it when we're deleting the AMO account because the FxA account is deleted after doing #13896 ?

Yes.

**Comment by diox** [comment]
@eviljeff the bug was originally assigned to me way back then, and it fell through the cracks. If you want to tackle this as part of https://github.com/mozilla/addons-server/issues/13896 feel free, otherwise someone will pick it up eventually, it should be rather straightforward, especially with the refactor you just landed in https://github.com/mozilla/addons-server/issues/14511

**Comment by AlexandraMoga** [comment]
This is the copy of the email sent when users delete their accounts from AMO. I'll retest this on stage with accounts deleted from FxA once the code lands there. 

```

Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Subject: Your account on https://addons-dev.allizom.org has been deleted
From: Mozilla Add-ons <nobody@mozilla.org>
To: some-email@mail.com
Date: Fri, 26 Jun 2020 12:51:30 -0000
Message-ID:
<123456789>
X-Auto-Response-Suppress: RN, NRN, OOF, AutoReply
Auto-Submitted: auto-generated

Hello,

You’re receiving this message because your user account Firefox user 10642046 on https://addons-dev.allizom.org has been deleted.

If you didn’t do this or believe an unauthorized person has accessed your account, please reply to this email. Otherwise, there’s no further action to take.

Regards,

The Firefox Add-ons Team
```

@eviljeff The [doc](https://docs.google.com/document/d/1Zuos9dZINSaX4vj4eNu0jT18DMc_HkB_Nm84x3iL5_g/edit) mentions an `amo-admins` email where users can reply to.  Should there also be a `Reply-to:` field in the email header with that `amo-admins` address? Since Fake mail does not support replies, I can't practically test that part.

**Comment by eviljeff** [comment]
> The doc mentions an amo-admins email where users can reply to. Should there also be a Reply-to: field in the email header with that amo-admins address? 

😞  yeah it should include the reply-to address (or have it set as the "from")

**Comment by AlexandraMoga** [comment]
Oh, I've just filed #14797 as follow up for that issue 😅
