### ISSUE TITLE
Clearing theme admin review flag does not work

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14523]
### Describe the problem and steps to reproduce it:

1. Have a theme that is pending admin review
2. Click _Clear Admin Static Theme Review Flag_ at the bottom of the review page

### What happened?

Nothing

### What did you expect to happen?

The flag should be unset and the button should disappear.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![2020-06-09_11-58-20](https://user-images.githubusercontent.com/31961530/84128570-6b6f1d00-aa49-11ea-8f3a-817c7ced5631.gif)
