### ISSUE TITLE
Website field from app detail page crashes with "[" or "]" in textfield

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#1452]
Steps to reproduce:
1.Load My Submissions page https://addons.allizom.org/en-US/developers/addons
2.Open a free app and from Edit Listing , click Edit button from the right side of Support Information field.
3.Type https://test.[com and save changes

Expected results:
Website field should display a warning message.

Actual results:
Waiting spinner wheel is continuously displayed and updates are not saved.

Note/Issues:

This issue is reproducing in AMO stage -dev and production servers
Here is the video  http://screencast.com/t/x4euvUA3iQLe

**Comment by andymckay** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/group/207278/
 
```
  File "django/core/validators.py", line 60, in __call__
    scheme, netloc, path, query, fragment = urlsplit(value)
  File "python2.7/urlparse.py", line 213, in urlsplit
    raise ValueError("Invalid IPv6 URL")
```

**Comment by EnTeQuAk** [comment]
I'll see if this is something we can fix upstream and backport to olympia. Looks like catching this `ValueError` is a good idea anyway.

**Comment by EnTeQuAk** [comment]
Working on an upstream solution in https://code.djangoproject.com/ticket/26119 - once there's a patch that's good for upstream we can backport this to olympia.

**Comment by EnTeQuAk** [comment]
This is now merged into django master, https://github.com/django/django/commit/a9e188ccd6315d278795355a53bce6c1a63f5a50 I'll see if I can backport this for the time being.

**Comment by EnTeQuAk** [comment]
Hmm, I wonder if I could just copy the validator but it's so huge. @diox any ideas here?

**Comment by cosminbadescuSV** [comment]
This issue is not reproducing anymore, video of this issue: 
![test](https://cloud.githubusercontent.com/assets/15885467/16833695/17aed286-49b9-11e6-9b13-872b41548b4a.gif)
