### ISSUE TITLE
Date range in statistics pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14532]
All stats pages have a date picker to select a custom range in addition to the pre-defined ranges (like 7, 30 and 365 days). Yet, it looks like the code won't return more than 365 days in any case, even if users select a date range greater than a year: https://github.com/mozilla/addons-server/blob/7ed687d082dc16a57e3f4a258bed7a8d618ba485/src/olympia/stats/views.py#L54-L59

Is that OK? I am asking because the beta stats (BigQuery) also have this limit of 365 days.

**Comment by willdurand** [comment]
cc @jvillalobos (based on a Slack thread)

**Comment by jvillalobos** [comment]
Is the BigQuery limit of 365 days for a single query, or is the limit that it only stores data up to 365 days old (or both)?

I'm okay with either case, fwiw. Developers looking for more detailed analysis should export the data and do that themselves.

**Comment by willdurand** [comment]
> Is the BigQuery limit of 365 days for a single query, or is the limit that it only stores data up to 365 days old (or both)?
> 
> I'm okay with either case, fwiw. Developers looking for more detailed analysis should export the data and do that themselves.

The limit is on the query itself.

I think @jklukas backfilled data since January 1st, 2019. If we need data before that and assuming it's possible, we'll have to backfill more data.

**Comment by jklukas** [comment]
> I think @jklukas backfilled data since January 1st, 2019. If we need data before that and assuming it's possible, we'll have to backfill more data.

Yes, we can backfill further back in history if needed. I believe it should be possible to go back as far as mid-2016.

**Comment by jvillalobos** [comment]
I think starting in 2019 is more than enough.
