### ISSUE TITLE
Reviewer cannot approve admin-flagged theme

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14534]
A reviewer tried to access https://reviewers.addons.mozilla.org/en-US/reviewers/review/foxstrike . They end up on https://reviewers.addons.mozilla.org/en-US/reviewers/queue/content_review#review-actions and yet see the content-review page for that theme (instead of the regular review page, or the queue page, as the url points to that).

The theme was admin-flagged, although I don't know whether that is relevant.

@diox says he has an idea. Maybe he also knows about better STR.

**Comment by diox** [comment]
This is because of https://github.com/mozilla/addons-server/commit/4a6b2695a22, which was done for content-reviewers to fix https://github.com/mozilla/addons-server/issues/6936

I missed the case where an user has `Addons:ThemeReview` but not other add-on review permissions.

**Comment by diox** [comment]
STR:
- Give someone `Addons:ThemeReview` and `Addons:ContentReview`, plus any other permissions you want as long as they don't get `Addons:Review`, `Addons:PostReview` or `Addons:RecommendedReview`.
- Have them access a review page for a theme

Expected results:
- They can see the review page for that theme

Actual results:
- They are redirected to the content-review page for that theme

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

Reviewers with only `Addons:ThemeReview` and `Addons:ContentReview` permissions will no longer be redirected to the content review page of a theme when trying to access a theme review page. 

The redirect applied to cover the case described in #6936 continues to work. 

![2020-06-09_12-19-22](https://user-images.githubusercontent.com/31961530/84131568-61e7b400-aa4d-11ea-8596-9b7426f129cc.gif)
