### ISSUE TITLE
Reset zoom is still active after the grey dot is used

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14541]
STR:
1. Go to stats such as https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/statistics/?last=90 and zoom in the graphic
2. Click the grey dot to zoom out and observe the `rest zoom` on the left side of the screen

Expected result:
`reset zoom` should be greyed out

Actual result:
`reset zoom` is highlighted (blue) Once clicked -nothing happens.

Notes:
This is reproducible on all AMO servers with FF76(Win10) - and with beta stats 

![reset zoom2](https://user-images.githubusercontent.com/33448286/83874077-9a317e80-a73d-11ea-896e-bfe94cb8d1a4.gif)

**Comment by willdurand** [comment]
Yeah, not sure what's going on here. Both buttons are not fully in sync, but it works and I think it was always like this because we didn't touch this part.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, it was always like this. It's simply a UX issue, so is https://github.com/mozilla/addons-server/issues/14540
I thought that now that statistics are in focus maybe they'll get a fix.
