### ISSUE TITLE
Have the account delete method also delete appropriate associated content the user created

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14549]
Spun off from #13896 to make the changes to the API delete endpoint for accounts so we're deleteing the same thing both from account deletion requests from FxA and from AMO directly.

addons-frontend issue for copy change - mozilla/addons-frontend#9467

**Comment by eviljeff** [comment]
Forgot about the restriction we specifically added in the API

**Comment by AlexandraMoga** [comment]
I've verified the user account deletion from AMO and from FxA (with the `fxa-account-delete` waffle enabled) and, for both cases, the following user data is deleted*:
- profile data - display name, homepage, location, picture, biography, notification preferences
- ratings
- collections
- addons

*except for the content mentioned in issue #14701 and #14711
