### ISSUE TITLE
 Admin interface to find add-ons by IP address

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14548]
Admins could use an interface where they enter an IP address and get a list of add-ons, where at least one file of that add-on was signed with the IP address that was entered, or other activity from that IP address.

**Comment by eviljeff** [comment]
we store the ip address on the FileUpload. Is there other "activity" you would want searched at the same time?

**Comment by diox** [comment]
See https://github.com/mozilla/addons-server/issues/14547#issuecomment-697876700
