### ISSUE TITLE
Firefox warning on cookie multidb_pin_writes

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14543]
Firefox 78 warns:

Cookie “multidb_pin_writes” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Example page: https://reviewers.addons.mozilla.org/en-US/reviewers/review/password-boss

**Comment by diox** [comment]
This is confusing. Django defaults to not pass `samesite` here, so why is that a problem ?

There is [a ticket in django about letting developers set an explicit `samesite=none`](https://code.djangoproject.com/ticket/30862), which will land in 3.1, but even then, the default would still be not to send anything, like we do now.

Ideally we'd set both `samesite=Lax` and `Secure` on that cookie, but it's set by `PinningRouterMiddleware` from https://github.com/jbalogh/django-multidb-router/blob/master/multidb/middleware.py - I could patch it in this app, but some people might use it in non-secure contexts (so we can't forcibly set `Secure` flag) or need it with cross-origins somehow (so we can't forcibly set `sameSite=Lax`)... Maybe this needs to be a setting (or two)...
