### ISSUE TITLE
Admin interface to find users by IP address

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14547]
Admins could use a view that allows them to find all users accounts that match a certain IP address.

**Comment by eviljeff** [comment]
is this just searching for a matching `UserProfile.last_login_ip`?

**Comment by diox** [comment]
IMHO this should be more than that. We should look in anything where we store the IP in database - ratings, file uploads, restrictions being hit and return any user that match.

**Comment by wagnerand** [comment]
It would be useful if the interface provided support for specifying a network range, because simple substring matching is not always sufficient, as lots of providers own subnets smaller or larger than the typical class A/B/C size.

**Comment by diox** [comment]
We need at least: 

- User ID
- User Created
- User Banned
- User Last Login
- User Last Login IP (used in the search)
- Restriction History Last Login IP (used in the search)
- Restriction History IP (used in the search)
- Rating IP (used in the search)
- Activity IP (used in the search)

In the future we'll want to consolidate pretty much all ip address logging to `IPLog` and storing it as a binary in MySQL but we're not there yet, the admin is a first step so that we can stop doing it via custom SQL queries.

**Comment by diox** [comment]
> Activity IP (used in the search)

This will have to wait until https://github.com/mozilla/addons-server/issues/17504 is implemented cause it's currently quite slow.

**Comment by diox** [comment]
This is implemented with the regular search input box in the admin changelist, searching for an IP will switch to a different UI that displays various sources of IP addresses that we search against. Multiple IPs can be entered, separated by a comma with no spaces.

There is also some buttons next to each IP shown to add/remove them from the search - the search has to be ran manually after you make changes, there will be a different border color on IPs that are not in the input search box yet, as well as a different border color on the input box itself if it contains a different value than what the page started with.

**Comment by ioanarusiczki** [comment]
@diox I verified this on django dev and stage:

- I could enter an ip address and search using models/users/userprofile/?q=`ip address` 
 
- the table returns information into the following columns:

![data](https://user-images.githubusercontent.com/33448286/126477087-bfcadaa2-6aca-45c8-be2e-fc81caa97876.png)

- I could add and remove IPs using the buttons next to them and continue with a new search.
- there is a different border color (pink) for IPs that were not in the input search box.
- there is a different border color (blue) for other IPs than what the page started with.
