### ISSUE TITLE
The grey dot stays visible after reset zoom

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14540]
STR:
1. Go to stats such as https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/usage/?last=30 and zoom in.
2. Click reset zoom and observe the graphic

Expected result:
The dot is no longer visible

Actual result:
The grey dot is still displayed

Notes:
Reproducible on all AMO servers (and on beta stats too) with FF76(win10). 

![reset zoom](https://user-images.githubusercontent.com/33448286/83873619-c8fb2500-a73c-11ea-9484-6c3e7af6b6a8.gif)

**Comment by willdurand** [comment]
Looks like this was there forever. I don't see any problem, though. The zoom is reset and the small dot does not hide any information.
