### ISSUE TITLE
Add Ko-fi.com to contributors domains

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/addons-server#14551]
See also:
https://github.com/mozilla/addons-server/issues/13163
https://github.com/mozilla/addons-server/issues/11680

**Ko-fi stands out because of it's "No platform fee".** See more info about the Ko-fi here:
https://ko-fi.com/about

They have a "Gold" version that has some bonus features like monthly subscriptions.
However the free version has enough features, including:
- setting up a goal
- posting posts
- donation without registration
- donation with Credit Card (when connected through Stripe) and PayPal
- money goes directly to your account

Example page (yes, that's me!):
https://ko-fi.com/fastaddons

**Comment by eviljeff** [comment]
@jvillalobos to decide

**Comment by jvillalobos** [comment]
Looks good to me.

**Comment by jvillalobos** [comment]
Mentor: @eviljeff

**Comment by Tintinator** [comment]
Can I take this?

**Comment by eviljeff** [comment]
@Tintinator sure

**Comment by AlexandraMoga** [comment]
The new domain  can be used in dev hub to set up a contribution URL for an an add-on listing:
Users will be redirected to this domain when they click on the Contribute button in the add-on detail page. 
![image](https://user-images.githubusercontent.com/31961530/84663424-d32fd700-af25-11ea-8276-d92a81ea54aa.png)
