### ISSUE TITLE
Handle new version uploads while an add-on has versions pending rejections

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14577]
Parent issue: #14454

After an add-on has his versions on a delayed rejection...
- [x] If a new version is uploaded by the developer, it won’t be automatically approved and the reviewer will be notified.
  - [x] ~~A new delayed rejection resets the grace period.~~ See discussion below
  - [x] If another new version is submitted while this version is awaiting review, the new version will take its place and the previous one will be disabled. For example: version 1.0 gets a delayed rejection, 2.0 is uploaded and awaiting review, then 3.0 is uploaded before 2.0 is reviewed. The end state is: 1.0 is still on delayed rejection, 2.0 is disabled and 3.0 is pending review.
  - [x] ~~If the new version is rejected with a delay, it takes the place of the previous versions: the previous versions are disabled and the new one is signed and placed in a new delayed rejection..~~ See discussion below

**Comment by diox** [comment]
Actually blocked by #14454 - there isn't much to do here, most of it should happen automatically once the other bits are done.

**Comment by diox** [comment]
@jvillalobos I found this bit from the PRD surprising:
> If the new version is rejected with a delay, it takes the place of the previous versions: the previous versions are disabled and the new one is signed and placed in a new delayed rejection..

If 1.0 is on a delayed rejection, 2.0 is pending review, this would mean that when 2.0 is rejected with a delay, 1.0 is disabled, leaving the add-on with no public versions. In addition it would mean the grace period would end sooner than advertised.

Do we really need this? With the implementation I've done so far, if 2.0 is rejected with a delay, both delays apply independently, potentially leaving time for the developer to submit a 3.0 fixing issues raised with both 1.0 and 2.0 before 1.0 is rejected.

**Comment by jvillalobos** [comment]
> this would mean that when 2.0 is rejected with a delay, 1.0 is disabled, leaving the add-on with no public versions

In the quote above, 2.0 would be signed (approved) and _then_ rejected with a delay, so 2.0 would be the public version. What you describe for the current implementation sounds similar, except that 1.0 would be disabled later, and before 2.0. My only concern there would be confusing messaging to the dev. Would the dev get messages about 1.0 going away, even if 2.0 sticks around?

And agree that this is an unlikely scenario, so we shouldn't worry too much about it.

**Comment by diox** [comment]
> Would the dev get messages about 1.0 going away, even if 2.0 sticks around?

TBD in https://github.com/mozilla/addons-server/issues/14814, which will implement the reminder notification. We can avoid sending the reminder in some cases like this one.

**Comment by diox** [comment]
@jvillalobos re-reading the PRD... Could you clarify `A new rejection resets the grace period` ? I thought I understood what this means but I'm not 100% sure now. In which scenario would this apply, and what would happen exactly ?

**Comment by jvillalobos** [comment]
It's connected to what I said above:

> 2.0 would be signed (approved) and then rejected with a delay, so 2.0 would be the public version

The idea is that we would never have overlapping rejections. So, if a new submission is rejected with a delay, the old one would be cleared (along with disabling those versions). The new submission, and only that one, would be pending rejection.

**Comment by diox** [comment]
Ok so like https://github.com/mozilla/addons-server/issues/14967 this is all connected to how we want to deal with delayed rejections of versions awaiting review.
