### ISSUE TITLE
Filter out add-ons pending rejection from reviewers queues

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14576]
See parent issue: https://github.com/mozilla/addons-server/issues/14454

- [ ] Add-ons pending rejection are filtered out of their respective queue.
- [ ] Add-ons pending rejection are shown in their own queue.

**Comment by diox** [comment]
Note: per https://github.com/mozilla/addons-server/issues/14578#issuecomment-641612736 regular reviewers can't perform approval/rejections if any version of the add-on is pending rejection, so to match this add-ons with any version pending rejection won't be shown in the regular queues, while they have a pending rejection at least.

**Comment by diox** [comment]
@jvillalobos just to confirm: technically, add-ons are not pending rejection : versions are. This means, it's not possible to hide add-ons pending rejections (whether or not the add-on would end up being completely rejected is computed when the version is rejected for real), so, we've got 2 options here:
- Hide add-ons that have *any* version pending rejection from the queues, matching as mentioned above the fact that reviewers can't approve/reject an add-on with *any* version pending rejection
- Hide add-ons that have their latest approved public version pending rejection - and only this version.

I'm leaning towards the former, but let me know if you prefer the latter.

**Comment by jvillalobos** [comment]
Per the other thread, once a new version is submitted by the developer, the new version is pending review and this should unlock the ability to review it, so it should show up in a queue. That sounds like the second option to me.

**Comment by diox** [comment]
Yeah, you're right. Ok, so, I'll only hide add-ons with their latest approved public version pending rejection.

**Comment by diox** [comment]
@jvillalobos : who should be able to see the Add-ons pending rejection queue ? Technically, most reviewers wouldn't be able to do much with add-ons in that queue, but maybe it'd be useful for them to be able to view the queue anyway ?

**Comment by jvillalobos** [comment]
I would prefer to only show it to people who can do something about it (admins). I know there's been some negative feedback when there's a queue you can do nothing on, but I think @wagnerand should have final say on this.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev with the add-ons used for verifying issue #14578 

Here are my test results:
- the new 'Add-ons Pending Rejection' queue can be found under the Admin Tools section on the reviewers dashboard
- the queue is accessible only to Admin Reviewers
- only add-ons with their latest approved public version pending rejection will be listed in this queue (for example, if an add-on is  in the Pending rejection queue and a new listed version is submitted, the addon will be removed from the Pending rejection queue)
- add-ons listed in the Pending rejection queue can't be found in their regular review queues, unless a new version is submitted

@diox unlisted versions with Pending rejections are not present in the new queue. Was this intended?

**Comment by diox** [comment]
> @diox unlisted versions with Pending rejections are not present in the new queue. Was this intended?

Yes for now, because they don't have the concept of "latest approved public version" and that delaying rejection for an unlisted version makes less sense : the version is either waiting for manual approval and you can just message the developer without rejecting, or already signed and out there in the wild so rejecting is pointless.
