### ISSUE TITLE
Let admins modify delayed version rejections

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14579]
- [ ] Admin reviewers can undo a pending rejection by submitting an approval confirmation.
- [ ] Admin reviewers can clear a pending rejection in the same way they can clear a pending need info.

The PRD also mentions this:
> Admin reviewers can immediately reject versions of add-ons pending rejection. Those versions are disabled immediately, even if they were previously pending rejection. If all versions pending rejection are disabled, the pending rejection state is cleared (but auto-approval should continue to be off).

But this will have to be done last, in https://github.com/mozilla/addons-server/issues/14454, once reviewers can actually submit delayed rejections - essentially it will be done for free almost, by just letting admins (immediately) reject while there is a pending rejection already.

**Comment by diox** [comment]
> Admin reviewers can undo a pending rejection by submitting an approval confirmation.

@jvillalobos should it clear *all* pending rejections or just the latest public approved version ?

>  Admin reviewers can clear a pending rejection in the same way they can clear a pending need info.

Should it be per version (meaning I would add an action that uses the version dropdown list) or just a single button that clears everything ?

**Comment by jvillalobos** [comment]
Both actions should clear the pending rejection for all affected versions.

**Comment by AlexandraMoga** [comment]
@diox could you please add a Pending rejection status on the following versions? The previous set we used are no longer usable for testing this part.

These are all from -dev:
1691596 1691597 1691598 1691603 1691599 1691605 1691611

**Comment by diox** [comment]
Done

**Comment by AlexandraMoga** [comment]
@diox I can clear Pending rejections for one or more versions by Confirming Approval with an Admin Reviewer, so this covers the first option.
For the second option, I expected to see a button in More Actions section which clears the Pending rejection flag, similar to what we have currently for pending Information Requests, but there isn't one. 

Another thing that came to mind: developers now have the option to clear a pending Information Request when they submit a new version. Will this still be possible for pending review rejections?

**Comment by diox** [comment]
>  For the second option, I expected to see a button in More Actions section which clears the Pending rejection flag, similar to what we have currently for pending Information Requests, but there isn't one.

Ugh, I implemented the API but forgot to add the button. I filed https://github.com/mozilla/addons-server/issues/14816

> Another thing that came to mind: developers now have the option to clear a pending Information Request when they submit a new version. Will this still be possible for pending review rejections?

Yes, that's covered by other issues: per discussion in https://github.com/mozilla/addons-server/issues/14799 versions will stay "on hold" if they are approved but pending rejection and a new version is posted. Then once a reviewer decides what to do with the new version the delayed rejection (https://github.com/mozilla/addons-server/issues/14454) will apply or be cancelled.
