### ISSUE TITLE
Show pending rejection status for versions in reviewer tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14578]
Parent issue: #14454 

- [ ] Versions pending rejection should have a “Pending Rejection” status in reviewer pages.
  - [ ] The number of days remaining for the rejection should be shown next to the status (#13955).
- [ ] Unless there’s a new version pending review, regular reviewers can’t perform approval or rejection actions on add-ons that have a pending rejection.

(I want all the sub-issues to be done before actually delaying rejections in reviewer tools, so, to verify this, ping me so that I can see it manually on the versions you want to test)

**Comment by diox** [comment]
@jvillalobos regarding this:
> Unless there’s a new version pending review, regular reviewers can’t perform approval or rejection actions on add-ons that have a pending rejection.

Do we want to be that strict ? I'm thinking we might want to keep the possibility of rejecting/approving *other* versions that aren't pending rejection rather than disallowing it on the whole add-on. It could be helpful if we realize there are more versions that just the ones scheduled for rejection that are problematic, for instance.

**Comment by jvillalobos** [comment]
I think @wagnerand also brought this up in the PRD. The idea here is to avoid having overlapping pending rejections or incorrect rejection reversals. This forces the delayed rejection to be addressed before other actions are taken, and if there's a need for something different it would be escalated.

It's a situation where I prefer to keep things simple, and if they become a nuisance we can change it to something else.

**Comment by AlexandraMoga** [comment]
@diox please set the Pending rejection status on the following versions:

1691540 1691542 1691543 1691544 1691545 1691546 1691549 1691548 1691550 1691551 1691562 1691559 1691560 1691561

For 1691542 if you can add a pending expiration date of 1 day, please add it, otherwise just add the status.

**Comment by diox** [comment]
Done.

**Comment by diox** [comment]
Note that we don't handle dates in the past - it will show something like `in 0 minutes`. But that's fine, it's the theoretical date :)

**Comment by AlexandraMoga** [comment]
@diox Here are my test results:

The new Pending rejection status is visible in the version details on an add-on review page. Reviewers can also see the actual time when the pending rejection is scheduled to expire (see screenshot). 

Items for discussion:
1. Speaking of auto-approved versions, regular reviewers are able to Confirm approval on a new version submitted _after_ a Pending rejection has been added on the exiting versions. What about situations in which all available versions, except for the latest (current) one are selected for Pending rejection? Should regular reviews still be able to Confirm approval on the latest version? Looking at https://github.com/mozilla/addons-server/issues/14576#issuecomment-643346179, I'd say this is expected, but I'd better be sure. 
2. For an add-on with only one available [version](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/pndrj-single-version) which is also Pending rejection, regular reviewers don't have the option to Reject multiple versions. They do have this option if the add-on has multiple versions with a Pending rejection. 
3. When a version with an ongoing Pending rejection is rejected through the Reject multiple versions option, the "Scheduled for rejection in..." status is not cleared
4. If the developer [deletes](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/dev-disables-version-pndrej) a version that has an ongoing Pending rejection, the "Scheduled for rejection in..." status is not cleared. 
5. Content reviewers can Approve content for a version that is Pending rejection - see [this addon](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/pndrej-multiple-versions), version 1.2
6. Shouldn't Admins/Admin reviewers have the option to Confirm Approval for a version (auto-approved) with an ongoing Pending rejection? I've only seen the Reject multiple versions option, same as for regular reviewers.

**Comment by diox** [comment]
1. Yeah, it's expected
2. Yeah, it's kind of an edge case but that's fine. The multiple versions rejection isn't very useful in this case, and the add-on wouldn't be in the regular reviewer queue anyway once https://github.com/mozilla/addons-server/issues/14576 is done
3. Yeah, that's something you can keep in mind and retest when https://github.com/mozilla/addons-server/issues/14454 is done
4. Same as 3.
5. Can you open a follow-up issue to discuss this further ?
6. Mmm yeah. Please also open a follow-up for this, it will be easier to track that way.
