### ISSUE TITLE
Developers of unlisted add-ons cannot see their stats 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14582]
STR:
1. I tried to access the beta stats for an unlisted addon with a developer account (the author of the unlisted addon): 
https://addons-dev.allizom.org/en-US/firefox/addon/154b2ca27eff421e93d7/statistics/beta/?last=30

Expected result:
Page should be available.

Actual result:
I receive a 404

Notes:
This is also reproducible for mozilla.com developer accounts.

**Comment by ioanarusiczki** [comment]
@willdurand This issue is no longer reproducible on AMO dev - FF76(Win10). 

I've noticed that:
- "Statistics" link on the Manage my submission page is not present for unlisted addons. Maybe this should be added too. 
- On AMO stage only admins can access stats for unlisted addons.

**Comment by willdurand** [comment]
> On AMO stage only admins can access stats for unlisted addons.

Only for unlisted add-ons?

**Comment by ioanarusiczki** [comment]
@willdurand On AMO stage with a developer account I can see my stats for listed add-ons but for unlisted add-ons I don't have the "View Statistics Dashboard" link on the left. 
With an admin account I have access to all stats. For my unlisted addon I am redirected to the beta stats.
