### ISSUE TITLE
Add add-on GUID to DeniedGuid if Addon.delete(hard=True)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14581]
Because we normally soft-delete addon instances we keep a record of the guid, blocking other developers from re-using it (and upgrading users to a different add-on).  If we choose to _hard_ delete addons though, then the guid is lost and it would be available.  Hard deleting isn't triggerable by users/developers but it's admins can.  

We should add code that adds an add-on guid to `DeniedGuid` if they are hard deleted.

**Comment by wagnerand** [comment]
Do we want to add an optional _Reason_ field that would be filled with a warning message to make admins aware of the risks before removing an entry that was added this way?

**Comment by diox** [comment]
`DeniedGuid` has a `comments` field for this, that would be ideal.

**Comment by wagnerand** [comment]
Thanks, Andrew, for the analysis. The approach you mention sounds good to me.

**Comment by ioanarusiczki** [comment]
@eviljeff Should I upload some addons and then let you know the guids? Looks like I cannot hard delete them as an admin.

**Comment by eviljeff** [comment]
the command that uses code was last used for deleting old themes but they're all gone  so there's nothing to test this with right now.  I expect it'll be next used when we finally hard delete old legacy add-ons (there's no footgun general delete addons command).
