### ISSUE TITLE
Only allow Reviewers and Admins access to Code Manager APIs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#14607]
### Describe the problem and steps to reproduce it:
Add-on authors can access APIs for the new Code Manager, but it is not currently designed to properly handle that.

STR:
1. Sign on as an add-on developer.
2. Access Code Manager for one of your add-ons/versions.
3. You can see the review in Code Manager, and can add/edit/delete comments.

### What happened?

As a developer you can access reviews in Code Manager and add/edit/delete your own comments.

### What did you expect to happen?

You should not be able to view reviews in Code Manager.

### Anything else we should know?

Only Reviewers and Admins should have access to Code Manager APIs.

**Comment by AlexandraMoga** [comment]
Add-on authors can no longer access code-manager - they will see a 403 error message (which could be improved as mentioned in https://github.com/mozilla/addons-code-manager/issues/518)

Add-on reviewers and site administrator can access code-manager same as before. 

Verified fixed on -dev.
