### ISSUE TITLE
Remove stats pages for dictionaries and language packs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14608]
See: https://github.com/mozilla/addons-server/issues/14533

---

We want to remove stats pages for langpacks and dictionaries (temporarily) in beta mode only (because the beta will become the default after July 9, 2020).

The idea is therefore to:

- remove beta stats pages for langpacks and dictionaries
- hide links to beta in "Manage my submission" and the DevHub "edit" add-on pages
- link to old stats pages in "Manage my submission" and the DevHub "edit" add-on pages (because users need access to these pages before we sunset the old stats)
- hide "beta" message shown on old stats pages for langpacks and dictionaries

**Comment by ioanarusiczki** [comment]
@willdurand I verified the statistics links for lang packs and dictionaries on AMO dev:
- the beta stats are not available for developers or an admin. 
- old stats can be accessed from edit and manager my submission page without messages about beta.

Is it alright that the frontend link "Visit stats dashboard" is not available for the developers or the admin?

**Comment by willdurand** [comment]
> Is it alright that the frontend link "Visit stats dashboard" is not available for the developers or the admin?

Yes, because, as soon as beta becomes the default, there won't be stats for langpacks and dicts for some time.

**Comment by ioanarusiczki** [comment]
@willdurand Ok, I am marking this issue verified. - FF76(Win10).
