### ISSUE TITLE
Don't clear email and fxa_id from UserProfile on delete

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14613]
We currently clear the email address and fxa_id from a UserProfile instance on delete, and rely on logging to keep track of them.  It will make querying easier if we just retain the email address and fxa_id, and only clear them later in line with our data retention policies.

**Comment by AlexandraMoga** [comment]
The email address and the FxA id are still visible in the admin user profile page when an account is deleted. 

This issue is verified fixed on dev.
