### ISSUE TITLE
Usage breakdowns under pie charts show incorrect percentages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#14623]
This was reported today on Matrix. The statistics dashboard for [this extension](https://addons.mozilla.org/addon/tgfixer/) has some data glitches. Here's the screenshot that was reported:

<img width="249" alt="Снимок+экрана+2020-06-12+в+22 58 12" src="https://user-images.githubusercontent.com/62568/84544088-d1fa7200-acb9-11ea-9cc0-4690ce76b613.png">

And here's what I saw when I checked it myself (changing the language didn't change the numbers, FWIW):

![Screenshot_2020-06-12 TgFixer (Telegram unblock) Statistics Dashboard Add-ons for Firefox](https://user-images.githubusercontent.com/62568/84544128-e63e6f00-acb9-11ea-9f3c-e9c003d258ed.png)

In both cases the percentages for the specific languages are wrong. I see the same problem in the Top Applications breakdown. It's also worth noting that this problem occurs both in the old and new dashboards, so it doesn't appear to be a problem with the switch to telemetry. But, since we're poking at these dashboards already, I think it's worth taking a look :)

**Comment by willdurand** [comment]
Is the problem the fact that we have round numbers and percentages seem wrong according to these round numbers?

I am not entirely sure but if we have say `0.9` for a language, it is possible that it represents `5%` of all the languages, yet the legend would show `0` because we truncate the numbers in the legend.

I'll take a look, thanks!

**Comment by jvillalobos** [comment]
Yes, it looks like the problem is that those numbers are rounded averages and it isn't very clear. Adding decimals could break the already very brittle layout, so we should probably avoid that, or only do it for single-digit results.

Or how about showing more precise numbers in a tooltip if you hover over the rounded numbers?

**Comment by willdurand** [comment]
> Yes, it looks like the problem is that those numbers are rounded averages and it isn't very clear. Adding decimals could break the already very brittle layout, so we should probably avoid that, or only do it for single-digit results.
> 
> Or how about showing more precise numbers in a tooltip if you hover over the rounded numbers?

I did both. Single-digit values will have a digit after the comma and we have HTML titles with the raw values. It should be more accurate after that.

**Comment by ioanarusiczki** [comment]
@willdurand I could hover over the numbers, there is a tooltip showing a lot of digits after the comma. 
There is no `0` as value -> there's `0.0` or `0.5`. 
Two digit numbers such as  `46` will show in the tooltip a number with digits after the comma too.
I looked over beta and classic stats - FF76(Win10). 

![two and one digit ](https://user-images.githubusercontent.com/33448286/85548681-de6ebb00-b627-11ea-82d0-f2788cffb8ba.gif)
