### ISSUE TITLE
Handle no `.git/description` file in `AddonGitRepository`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14637]
The `.git/description` file should be present because git creates it (and it's an internal git file) but we noticed a few errors with potentially old git repos that did not have this file (or maybe something else prevented this file to be written on disk).

We should handle this case to avoid "file not found" errors.

**Comment by ioanarusiczki** [comment]
@willdurand If there's something qa can test for this issue, let me know.
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki it is tricky to verify so I am marking the issue as "qa: not needed"

**Comment by willdurand** [comment]
@ioanarusiczki actually, the only "thing" to verify is to ensure that git extraction still works as before.
