### ISSUE TITLE
Add API to create new `AppVersion` instances

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14649]
We need to automate `AppVersion` creation. Our idea is to provide an API that would be called by Firefox release management when a new version (beta or release) is released. That API would require a specific permission we would give their user.

**Comment by diox** [comment]
Ideally this would be called even earlier than beta/release date, during merge day, when https://hg.mozilla.org/mozilla-central/file/tip/browser/config/version.txt is updated. That way we'd have the appversions ready for use as soon as a Nightly is released for a given version.

I'm thinking the API would look something like this:
`PUT https://addons.mozilla.org/api/v4/applications/firefox/appversion/79.0a1/` -> AMO would create (ignoring those that already exist) 79.0, 79.0a1, 79.* for Firefox
`PUT https://addons.mozilla.org/api/v4/applications/android/appversion/79.0a1/` -> AMO would create (ignoring those that already exist) 79.0, 79.0a1, 79.* for Firefox for Android

@eviljeff thoughts ? I've talked to releng and it seems doable on their side, they want more details (and a bug) before committing though, so I want to flesh out the API more before filing the bug for them.

**Comment by eviljeff** [comment]
> PUT https://addons.mozilla.org/api/v4/applications/firefox/appversion/79.0a1/ -> AMO would create (ignoring those that already exist) 79.0, 79.0a1, 79.* for Firefox

so, `/79.0a1/` creates version "79.0a1" (major=79, minor1=0, alpha='a', alpha_ver=1) - the actual version, plus "79.1" ("major.minor1") and "79.*" ("major.*")?  Makes sense.  

`/79.1a2/` would try to generate "79.1a2", "79.1" and "79.*"?

**Comment by diox** [comment]
Yeah, that's what I was thinking.

**Comment by diox** [comment]
Re-opening because I just changed my mind on the authentication mechanism, we're going to use the external JWT-based auth with API keys instead.

**Comment by diox** [comment]
QA: this API is documented over at https://addons-server.readthedocs.io/en/latest/topics/api/applications.html

You need a user with the`AppVersions:Create` permission, and more importantly, you need to use [API key authentication](https://addons-server.readthedocs.io/en/latest/topics/api/auth.html) which I'm not sure you're familiar with outside of tools like `web-ext` - it's a bit tricky to use with `curl` for instance, as you need to generate a short-lived token and use it. Let me know if you need help verifying.

**Comment by AlexandraMoga** [comment]
@diox I've verified this new api endpoint on -dev and the results seem to be as expected (I've used the external JWT auth before when testing API add-on submissions, so authentication for this new endpoint was not a problem).

After each request, I've verified if the new values were added to https://addons-dev.allizom.org/en-US/firefox/pages/appversions/

Results:
- `/api/v4/applications/firefox/84.0a1/` => versions created are `84.0a1, 84.0, 84.*`
- `/api/v4/applications/firefox/84.0a2/` => version created is `84.0a2` (the other versions in this range were created before, hence they were skipped)
- `/api/v4/applications/firefox/86.0/` => versions created are `86.0` and `86.*`
- `/api/v4/applications/firefox/87.0.2/` => versions created are `87.0, 87.0.2, 87.*`
- invalid/missing authentication credentials => 401
- user doesn't belong to the `AppVersions:Create` group => 403
- the application version number already exists => 202
- invalid application or version number => 400

Some minor issues:
- the `/appversions/` page wasn't always immediately updated after an API request. Sometimes I had to wait several minutes for the new versions to appear on the page. I'm not sure if this happens only on -dev though. 
- the version number will accept any combination of digits and letters and the API will try to figure out how to create a range of versions from that. So, if the version in the request is `860b123a`, the resulted versions will be `860b123a, 860.0, 860.*`. In any case, I don't think this is a real problem, considering who will be the end users of this API.

**Comment by diox** [comment]
> the /appversions/ page wasn't always immediately updated after an API request. Sometimes I had to wait several minutes for the new versions to appear on the page. I'm not sure if this happens only on -dev though.

Ah, forgot there is caching on this page. It should be ok, the version should be available for use in manifests regardless of what this page says, which is the important point.

> the version number will accept any combination of digits and letters and the API will try to figure out how to create a range of versions from that. So, if the version in the request is 860b123a, the resulted versions will be 860b123a, 860.0, 860.*. In any case, I don't think this is a real problem, considering who will be the end users of this API.

Yeah, there is some limited checking through a regexp that we already used elsewhere for version validation, apart from that I think it will have to be up to releng scripts to submit correct version numbers.
