### ISSUE TITLE
Handle nested special git files

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14652]
We should better handle nested special git files, especially when special git files are located inside other special git files:

```
/.git/.gitmodules
```

**Comment by wagnerand** [comment]
Also `.git/.git/`

**Comment by ioanarusiczki** [comment]
@willdurand Please add some STR for qa if we can help here.
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki sorry about that, added now. thanks

**Comment by ioanarusiczki** [comment]
@willdurand I deleted the extension of the file (.txt for example) and uploaded the following:

for .git/.gitattributes

https://code.addons-dev.allizom.org/en-US/browse/619945/versions/1691571/
https://code.addons-dev.allizom.org/en-US/browse/619948/versions/1691574/

for .git/.git/.gitconfig

https://code.addons-dev.allizom.org/en-US/browse/619946/versions/1691572/
https://code.addons-dev.allizom.org/en-US/browse/619947/versions/1691573/

**Comment by willdurand** [comment]
@ioanarusiczki looks good
