### ISSUE TITLE
Errors while updating average daily users (when bigquery waffle is turned on)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14650]
While testing the cron task, I noticed two errors:

- BigQuery can return `null` (count) values
- We have add-ons without GUIDs, which should be excluded

**Comment by ioanarusiczki** [comment]
@willdurand I left a comment here https://github.com/mozilla/addons-server/issues/14428#issuecomment-645288854

If there's anything else I can check for this issue please let me know.
