### ISSUE TITLE
Remove `content-optimization` waffle dependency for trademark checks.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14656]
### Describe the problem and steps to reproduce it:

The trademark check in https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/utils.py#L32-L40 allows "... for Firefox" if the waffle switch `content-optimization` is turned off. We'd like to change that so it's disallowed regardless of the waffle switch.

STR:
1. Have an existing add-on.
2. Go to the developer hub and change the name to "Something for Firefox" or "Something for Mozilla".

### What happened?

The add-on is successfully renamed.

### What did you expect to happen?

An error should occur: _Add-on names cannot contain the Mozilla or Firefox trademarks._

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Confirming that we're just closing the loop on the work done in https://github.com/mozilla/addons-linter/issues/2158

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

With the `content-optimization` waffle switch off, users are not able to submit an add-on that contains the terms `(for) Mozilla` or `(for) Firefox` in their names. The restriction also applies on the dev hub submission form[1] and in Edit product page[2] 

[1]
![image](https://user-images.githubusercontent.com/31961530/85031833-d1654e00-b187-11ea-8f76-1bc357fe3e52.png)
[2]
![image](https://user-images.githubusercontent.com/31961530/85031892-de823d00-b187-11ea-8816-58b018d752df.png)

**Comment by willdurand** [comment]
@jvillalobos @wagnerand we should probably update the various policy pages because `XXX for Firefox` is still allowed according to https://extensionworkshop.com/documentation/publish/add-on-policies/ or https://www.mozilla.org/en-US/foundation/trademarks/policy/
