### ISSUE TITLE
Loading validation.json from code-manager is generating a CORS error

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14655]
### Describe the problem and steps to reproduce it:

1. With a reviewer account, open the browse page for any add-on - see for example https://code.addons-dev.allizom.org/en-US/browse/619739/versions/1691228/

### What happened?
The code overview is not loaded - i.e. it's stuck on  _Loading linter information..._

### What did you expect to happen?
The code overview is loaded 

### Anything else we should know?
- reproduced only on -dev with both the browse and the compare views
 
![image](https://user-images.githubusercontent.com/31961530/84771518-4434c480-afe2-11ea-971d-64e38d257f90.png)

**Comment by bobsilverberg** [comment]
This is not actually fixed. I thought I fixed it but a redirect is still causing a problem. I am working on a new fix.

**Comment by bobsilverberg** [comment]
@AlexandraMoga This is now fixed on dev and stage and will be going out with tomorrow's push, so if you can verify it as soon as you have a chance that would be great. Thanks!

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've opened several browse and compare pages and the error can no longer be reproduced on either -dev or stage.
I'm marking this issue as verified fixed.
