### ISSUE TITLE
Add blocklist information to add-on admin page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14675]
We should add block information about an add-on to its admin page, so that admins can see whether add-on versions are blocked.

Note that this should show the block-range somehow, in addition to the matched versions, to cover open-ended blocks.

**Comment by eviljeff** [comment]
@wagnerand 
![Screenshot 2020-07-13 13 20 15](https://user-images.githubusercontent.com/768592/87303806-a8787480-c50b-11ea-8860-28a8b62b49f0.png)
![Screenshot 2020-07-13 13 18 52](https://user-images.githubusercontent.com/768592/87303725-82eb6b00-c50b-11ea-85fe-d97a02f5ff8e.png)
![Screenshot 2020-07-13 13 17 38](https://user-images.githubusercontent.com/768592/87303714-8121a780-c50b-11ea-83d4-7bab59c2dc26.png)

**Comment by wagnerand** [comment]
Looks great, thank you!

**Comment by AlexandraMoga** [comment]
The admin add-on page displays the Blocked status next to each version covered by the block range:

![image](https://user-images.githubusercontent.com/31961530/87433924-8ad20a80-c5f2-11ea-94fe-3f37a0bb61a1.png)
