### ISSUE TITLE
The year can take invalid values for the Custom Date Range

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14679]
STR:
1. Go to stats for https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/beta/?last=365 and open the Custom Date Range 

Expected result:
Maybe it should only allow to select a year (starting 2004 or since stats are available on AMO) 

Notes:
I could add more than a 4 digit number for the year. 
The graph is generated and looking like the image below.
The date and month work as expected. 

![invalid years](https://user-images.githubusercontent.com/33448286/85024442-bfcb7880-b17e-11ea-8c59-833480e1f33d.png)

![graph](https://user-images.githubusercontent.com/33448286/85025369-f9e94a00-b17f-11ea-9cde-333030fbe361.png)

**Comment by ioanarusiczki** [comment]
@willdurand The issue reproducible on beta too.

**Comment by willdurand** [comment]
Ha, that's not really nice but I don't think we'll fix it because this might require a lot of effort for too little value. This would involve updating the jQuery code, which is untested. Theoretically, we have min/max date constraints, not sure what's going on with the `input` field.
