### ISSUE TITLE
Keep a permanent record of which users were an addon owner/developer

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14681]
When a user is removed from an Addon we just remove it from the AddonUsers table, which means tracking down previous users means having to query via other data sources (logs, ActivityLog, etc).  

We should either soft-delete AddonUser, or add a further role of "Deleted" (and generally filter it out).  Either way needs to be done with care in regards to only exposing the non-deleted addonusers publicly, and handling a user being re-added back to an addon (which would effectively undelete).

**Comment by eviljeff** [comment]
So, this turned out to be a lot more complicated than first assumed.  Just adding a custom Manager on AddonUser that filters out some AddonUser instances doesn't work because `Addon.objects.get(id=99).authors.filter(foo=baa)` is, effectively,  `UserProfile.objects.filter(addons__id=99).filter(foo=baa)` - i.e. AddonUser.objects isn't used at all.  (similarly with `UserProfile.objects.get(...).addons`).

We either need to write a fair amount of custom code that hooks into the model internals in django, or find another way to do this.    If we _don't_ rely on the manager/queryset filtering out the deleted addonusers directly we need to be very careful **everywhere** we access Addon.authors (or Addon.addonuser_set or UserProfile.addons or UserProfile.addonuser_set) that we are excluding deleted authors.

**Comment by AlexandraMoga** [comment]
@eviljeff I began to test this but it looks like there is an issue with the implementation, namely the additional author is still present on the add-on listing page and the additional user's profile page will still display the add-on.  Also, the additional author can still see the add-on on in DevHub, Manage my submissions, but they can't access any subsequent pages, such as Edit product page, Manage versions etc. 


Examples:
- add-on ownership as seen by the original owner after the additional author was removed - https://addons-dev.allizom.org/en-US/developers/addon/shared-owner/ownership
- admin add-on page - the additional author will appear with status (Deleted) - https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/619976/change/
- add-on listing - https://addons-dev.allizom.org/en-US/firefox/addon/shared-owner/
![image](https://user-images.githubusercontent.com/31961530/87169311-7501d400-c2d8-11ea-90b0-33c9fe273eaf.png)


The removed author's ID is 10642070.

**Comment by eviljeff** [comment]
@AlexandraMoga I hope(!) I've fixed all the places now - but I've marked it as qa:extra because I underestimated the changes needed the first time and I'm not 100% confident everywhere is covered.

**Comment by eviljeff** [comment]
Note, deleted addon owners showing up:
- in admin tools, good (desirable - but not a blocker if they don't everywhere)
- in reviewer tools, okay (but unexpected - not a blocker if they show up, but ideally we'd at least indicate they are deleted and not current owners)
- in developer tools and frontend, no.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev again and the results are looking good now. I've tested both with removing the additional author from devhub ownership page and by deleting the user account entirely. 

Actual results after removing/deleting an author:
- the user no longer appears on the add-on listing page or other places where the add-on authors are displayed
- the additional author's profile page will no longer display the add-on 
- the additional author can no longer see the add-on in devhub
- the user will not be present in reviewer tools as an additional author
- the admin add-on page will list the additional author with status (Deleted)

Examples:
- add-on with removed additional owner - https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/619966/change/
- add-on with deleted additional owner account - https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/619938/change/
