### ISSUE TITLE
 Handle guid updates or prevent updating guids entirely

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14700]
As a followup for https://github.com/mozilla/addons-server/issues/13123#issuecomment-648024427

Admins can edit the existing guid of an addon from the /change page in admin tools and  the AddonGUID model is not being updated. 

Expected result:
Handle that when the admin updates the guid, or prevent updating guids entirely. 

Please note:
Changing the guid can cause errors such as in the [blocklisting](https://github.com/mozilla/addons-server/issues/13123#issuecomment-646626421) feature. 
This is an edge case - in my case used on testing servers to import stats data from prod.

**Comment by eviljeff** [comment]
@wagnerand how often do you (or other admins) edit the guid of an Addon instance via django admin?  If this is a super rare occurrence it'd be safer to just remove support from the admin. (if it's more common that I think then we need to handle AddonGUID instances)

**Comment by wagnerand** [comment]
I can't recall that have ever used that. I am ok with making that field read-only.

**Comment by ioanarusiczki** [comment]
@eviljeff Guid field is read only on admin dev. 
Verified with FF78(Win10).
