### ISSUE TITLE
Add a management command that raises an uncaught exception

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14715]
To be able to test exception handling from tasks, we've got `gen_celery_error` which triggers a celery tasks that just raises an exception. It'd be helpful if, instead, it was called `generate_error` and it would either directly raise the exception from the management command, or through a celery task like it does now if `--celery` argument or something similar is passed. That way we'd be able to test both management command error handling and celery handling with the same simple command.

**Comment by AlexandraMoga** [comment]
Could you please add a qa:not needed label if there is noting to be tested by QA?
Thanks
