### ISSUE TITLE
Addons with shared ownership are still visible on the profile page of a deleted user who logs back in with the same email

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14711]
Follow up for #14549 

### Describe the problem and steps to reproduce it:
1. Log in on AMO -dev with a developer account
2. Add another author to some of your add-ons 
3. Delete your account
4. Log back in with the same email address
5. Go to your profile page and check the available content

### What happened?
All the add-ons that had a shared ownership are visible on the profile page, although your user is no longer listed as an author.
Your account is also publicly visible.

### What did you expect to happen?
There shouldn't be any add-ons present on the profile page

### Anything else we should know?
- Example of a deleted user who logged back in with the same email - account is publicly visible although this user is not listed as a developer to any of the listed add-ons: https://addons-dev.allizom.org/en-US/firefox/user/10641975/
- on the Manage my submissions page in devhub, there are no add-ons displayed for this user

**Comment by AlexandraMoga** [comment]
@eviljeff I'm still seeing the shared add-ons the user created before deleting the account - see [another example](https://addons-dev.allizom.org/en-US/firefox/user/10642047/)
On the plus side, the user's profile page is no longer publicly viewable, so the remaining issue seems to be related only to the search API. 

![image](https://user-images.githubusercontent.com/31961530/86120521-220c6d80-badd-11ea-976f-51afe0db1233.png)

**Comment by eviljeff** [comment]
#14800 tries to fix it again

**Comment by AlexandraMoga** [comment]
I've re-verified this on -dev and add-ons are no longer present on the profile page after the user reactivates the account.

I'm marking the issue as verified fixed on -dev.
