### ISSUE TITLE
Delete PrimaryHeroImages files when instance is deleted 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14729]
When a `PrimaryHeroImage` instance is deleted we should delete the file(s) on disk that correspond to it too.  This would include any resized or thumbnail copies.

**Comment by ioanarusiczki** [comment]
@xlisachan 
I verified on dev - FF78(Win10):

I did not have problems deleting images from `admin/models/discovery/primaryheroimageupload/`. So technically and visually there are no issues.

I've noticed two things in the Console and Network which maybe worth to be mentioned:
- when I select an image (check the square), every time the Console throws an error Uncaught ReferenceError: interpolate is not defined.
- when I delete (or upload) images the Network shows 2 blocked GET methods for https://addons-internal.dev.mozaws.net/en-US/admin/models/jsi18n/

![blocked](https://user-images.githubusercontent.com/33448286/86768021-8ab39700-c055-11ea-821a-261f2b90c494.gif)

**Comment by eviljeff** [comment]
@ioanarusiczki do these things only happen on this model page?  (It doesn't do anything javascript related so it should be pretty standard)

**Comment by ioanarusiczki** [comment]
@eviljeff Yes, good point. Well, I see the check box issue also reproducible in abuse reports `/en-US/admin/models/abuse/abusereport/` and the blocked methods are present in secondary hero shelves.  Same on AMO stage, I believe it's always been there.

**Comment by eviljeff** [comment]
it might have been introduced during a django upgrade at some point.  If it's not affecting anything functionally I'd ignore it.
