### ISSUE TITLE
JavaScript files are broken since upgrade to Uglify-js 3.10.0

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14726]
### Describe the problem and steps to reproduce it:
1. Log in to the developer hub
2. Try to upload an add-on

### What happened?
The 'Select a file' button is missing and the upload can't be triggered [1]

### What did you expect to happen?
The button should be displayed and the upload triggered

### Anything else we should know?
- there are other forms and buttons in devhub that do not respond  (for example, the 'Delete' addon button)
- reviewer tools are also affected (see screencast)

[1] 'Select a file' button missing on the submission form
![image](https://user-images.githubusercontent.com/31961530/85713261-df6c1f00-b6f1-11ea-8ca7-454ad685c6e7.png)

[2] reviewer actions not responding
![weird](https://user-images.githubusercontent.com/31961530/85713284-e430d300-b6f1-11ea-865e-0ca7ad087a2e.gif)

**Comment by diox** [comment]
We've got a deploy failure on dev that may be related.

**Comment by AlexandraMoga** [comment]
There has been a successful server deploy in the meantime but the issue is still reproducing.

**Comment by AlexandraMoga** [comment]
This is still happening and might block some issues from being verified on -dev.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev.
