### ISSUE TITLE
Invalid ADU for langpacks/dicts after task is executed

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14732]
The ADU value of langpacks/dictionaries is computed based on the total number of downloads but something is wrong in -prod right now. We have very low values.

This is the django query we do for computing the total downloads in the ADU update task: https://github.com/mozilla/addons-server/blob/917825b911533a6600d79cf02a5fdb6f9a21b7d5/src/olympia/addons/cron.py#L46-L51

This is the django query used in a different task: https://github.com/mozilla/addons-server/blob/917825b911533a6600d79cf02a5fdb6f9a21b7d5/src/olympia/addons/cron.py#L82-L85

**Comment by willdurand** [comment]
cc @diox

**Comment by diox** [comment]
That's going to be a fun one... At first glance the query looks ok, and in redash I see the correct results... I wonder if somehow we do have some data in bigquery overriding the data from AMO's database.

**Comment by ioanarusiczki** [comment]
@willdurand In case qa can help here, please add some STR.

**Comment by willdurand** [comment]
@ioanarusiczki I am not sure this is doable but would you be able to try to:

1. create a langpack OR dict with a GUID from this list: https://github.com/mozilla/bigquery-etl/blob/6c59168b0d45c333bc0c97525a343d740dbc232c/sql/amo_dev/amo_stats_dau_v2/query.sql#L14-L16 (if it already exists on AMO, try to "free" it first)
2. take a look at this query: https://sql.telemetry.mozilla.org/queries/72343 and note the value for the GUID you used
3. ask an engineer to run the `update_addon_average_daily_users` cron task in -dev (`./manage.py cron update_addon_average_daily_users`)
4. the "Downloads" count on the detail page should NOT be the value noted before (because that would mean the value has veen updated with the BigQuery data instead of the "download count" data)

The value for the "Downloads" count can be retrieved by an AMO engineer with this django query:

```
Addon.objects.filter(guid="<GUID>").annotate(count=Coalesce(Sum('downloadcount__count'), 0)).values_list('guid', 'count')
```

**Comment by ioanarusiczki** [comment]
@willdurand I'll have to wait for https://github.com/mozilla/addons-server/issues/14726 to be fixed first. Mat said he's looking into that.

**Comment by ioanarusiczki** [comment]
@willdurand The [lang pack](https://addons-dev.allizom.org/en-US/firefox/addon/lang-pack-with-statistics/) with guid: close-tabs-by-pattern@virgule.net, value:8.08
The [dictionary ](https://addons-dev.allizom.org/en-US/firefox/addon/release-dictionary-with-stats/) with guid: {0ec56aba-6955-43fb-a5cf-ed3f3ab66e7e}, value 6.75

On the detail pages I see "no Downloads" right now. 

Could you run the cron task?

**Comment by willdurand** [comment]
> Could you run the cron task?

@ioanarusiczki it's running :)

**Comment by ioanarusiczki** [comment]
@willdurand I don't see changes yet.

**Comment by ioanarusiczki** [comment]
@willdurand 

Lang pack: 136 downloads 
Dictionary: 551 downloads

Looks like they mean a total number of downloads.
