### ISSUE TITLE
ADU update and LWT

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14731]
It looks like we have data for LWT in BigQuery because we have GUIDs of the form `9999@personas.mozilla.org` where `9999` is a numeric value. We noticed this during the ADU update CRON task execution.

AMO does not have add-ons with such GUIDs anymore, so we don't update anything in those cases (because we are unable to retrieve an `Addon` based on the `guid`).

@jvillalobos what should we do for such add-ons? Skip/ignore?

**Comment by eviljeff** [comment]
It's theoretically possible to lookup the equivalent the static theme of a LWT via the `MigratedLWT` model (if we knew what the 9999 was - addon.id I guess?  getpersonas_id?)

**Comment by diox** [comment]
I don't remember how that worked, but I'm pretty sure it's not an necessarily a numeric value - and when it is, I don't think it's the `addon` id from AMO.

**Comment by jvillalobos** [comment]
We can ignore them. These are legacy add-ons used in unsupported versions of Firefox.

**Comment by willdurand** [comment]
> We can ignore them. These are legacy add-ons used in unsupported versions of Firefox.

Ok, cool.

@diox do you think it'd be worth filtering out GUID ending with `@personas.mozilla.org`?

**Comment by diox** [comment]
The issue is, this suffix is free to use, you can't guarantee nobody is using it for them stuff, now or in the future. Ideally we'd get rid of the old data and don't do any filtering on our side, I think.

**Comment by willdurand** [comment]
> The issue is, this suffix is free to use, you can't guarantee nobody is using it for them stuff, now or in the future.

That's what I was thinking too recently. Although it isn't ideal to process a bunch of GUIDs for nothing, it's harmless (we support this edge case), so let's do nothing for now.
