### ISSUE TITLE
Allow auth via JWT token for Scanners API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14740]
We'd like to allow authentication to the scanners API using JWT tokens because this endpoint will likely be used as part of an automated mechanism.

**Comment by willdurand** [comment]
Marking as P2 because it blocks the data team.

**Comment by ioanarusiczki** [comment]
@willdurand I could make a call to the scanner [API](https://addons-internal.dev.mozaws.net/api/v4/scanner/results/) on dev with both methods of authentication: internal (the bearer token) and external (with JWT token) for an admin user and a user with `Admin:ScannersResultsView` permission. 

Are both methods expected?

**Comment by willdurand** [comment]
> @willdurand I could make a call to the scanner [API](https://addons-internal.dev.mozaws.net/api/v4/scanner/results/) on dev with both methods of authentication: internal (the bearer token) and external (with JWT token) for an admin user and a user with `Admin:ScannersResultsView` permission.
> 
> Are both methods expected?

Yes, awesome. Thanks!

**Comment by ioanarusiczki** [comment]
@willdurand Ok, then this is verified on dev.
