### ISSUE TITLE
Optimize the storage in mlbf directory

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#14749]
### Describe the problem and steps to reproduce it:
Currently dumped blocked/notblocked json files are saved in `<storage_root>/mlbf` directory. In chatting with @eviljeff [[1]](https://mozilla.slack.com/archives/C4MTGNZ7S/p1589560549015900), we think that there are two possible issues with the current design.

First is that there is no hierarchy under `mlbf/`, thus this directory can grow very big, and cause the same management headache as the `files/` directory does (e.g. nearly impossible to do `ls`; hard to find files, and etc.).

Second is that the directory can grow very big given each dump is over 150 MB, and at a maximum rate of 28 dumps per week. This puts pressure on costs and backup operations.

### What happened?
As above.

### What did you expect to happen?
As mentioned in the slack thread [[1]](https://mozilla.slack.com/archives/C4MTGNZ7S/p1589560549015900), there are two things we can do to improve this:

One is to delete old dumps periodically and keep only dumps that are X days/months old on the disk.

Two is to implement a hierarchical directory structure under `mlbf/` similar to  what's in `<storage root>/git-storage/` directory. That will make management of this directory much easier.

Out of the two, if we don't keep too many days worth of dumps, then I think the second measure is probably optional. Because if we prune the `mlbf/` directory periodically, then the sub-directories won't grow to a unmanageable level anyways.

 
### Anything else we should know?
n/a

**Comment by eviljeff** [comment]
@bqbn how many folders do we have now, out of interest (iirc it's been about 6 weeks since the `import_blocklist` job was enabled on prod and we started regularly building filters.)

**Comment by eviljeff** [comment]
related: #14505 (though this calls for automatic storage management and #14505 would be manual)

**Comment by bqbn** [comment]
> how many folders do we have now, ...

As of today, 25 folders, and 4 GB in total size.

**Comment by AlexandraMoga** [comment]
@eviljeff will this require some regression testing on `mlbf` generation?

**Comment by eviljeff** [comment]
@AlexandraMoga it shouldn't affect the generation itself.  I implemented the option "delete old dumps periodically and keep only dumps that are X days/months old on the disk." - After a successful blocklist update (either a new base, or an partial/stash) there is a task fired that deletes data older than 6 months.  

Might be difficult to QA though - I can't recall when we started generating the bloomfilters (I think it was about 6 months ago, but could be less) and seeing what folders still exist is an ops thing.  I'll check with ops.

**Comment by AlexandraMoga** [comment]
So, if I'm looking at the `mlbf` history for stage in https://settings.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records , the oldest `bloomfilter-base` record is from Friday, April 24, 2020, so ~5 months ago. Everything else is more recent. 

If there's indeed nothing I could help with, please add a 'qa:not needed' label.
Thanks

**Comment by eviljeff** [comment]
oh, it's nothing to do with remote-settings/kinto - that's cleared each time there's a new base filter.  It's files we store on addons-server - copies of the bloomfilters and the data that was used to build them.

**Comment by eviljeff** [comment]
I've looked on -dev and the earliest files are from April 21 (i.e. less than 6 months ago) so we wouldn't be expecting anything to happen yet.  A new mlbf was created since the code landed and logging shows the task executed (and didn't go wild and delete all the folders) so I guess that's success.

If @bqbn is able to rename one of the older folders to a timestamp for a date after 6 months then we could verify that the folder is deleted.  e.g. `/mnt/efs/addons-dev.allizom.org/mlbf/1587472510231` to `1583020800000`.

I don't think there's anything for QA to do here though.

**Comment by bqbn** [comment]
I've run the command as said,

```
$ sudo mv -v /mnt/efs/addons-dev.allizom.org/mlbf/1587472510231 /mnt/efs/addons-dev.allizom.org/mlbf/1583020800000
‘/mnt/efs/addons-dev.allizom.org/mlbf/1587472510231’ -> ‘/mnt/efs/addons-dev.allizom.org/mlbf/1583020800000’
```

What should we be expecting to happen next?

**Comment by eviljeff** [comment]
> What should we be expecting to happen next?

The next time there was a new blocklist triggered `1583020800000` would have been deleted because the timestamp (the folder name) is older than 6 months.  So I went into the dev admin; deleted a block; and triggered the cron job to run manually.  It worked - the folder is deleted. (and there's a new folder for the recent blocklist generation).  

Thanks.
