### ISSUE TITLE
Upgrade Uglify-js to 3.10.0 or higher and fix our assets tests coverage

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14779]
Upgrading to uglify-js 3.10.0 caused https://github.com/mozilla/addons-server/issues/14726. It didn't break any tests.
We are reverting this upgrade, but then we should:
- Figure out why this didn't work and fix the issue
- Figure out why this didn't break any tests and fix the tests

**Comment by diox** [comment]
UglifyJS improved their handling of command-line options, it now raises an error for invalid options. Furthermore, it also aliased `-v` to `--version`. We pass `-v` thinking it was an alias for `--verbose`, but in truth, it wasn't doing anything at all... And now it prints the version instead of doing anything :)

**Comment by diox** [comment]
QA: Re-verify https://github.com/mozilla/addons-server/issues/14726

**Comment by AlexandraMoga** [comment]
I'm not reproducing #14726 anymore and there are no 404 or other errors in the console. 

Verified fixed on -dev.
