### ISSUE TITLE
Merge `Addons:Review` and `Addons:PostReview` permissions together

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14782]
A significant source of complexity in reviewer tools is the different kind of actions a reviewer can perform depending on whether they have `Addons:PostReview` and `Addons:Review`. The former allows only confirming auto-approval and multiple rejections of auto-approved add-ons, the latter allows for manual approval/rejection of add-ons that haven't been auto-approved.

Do we still need that distinction ? I'm convinced there are subtle bugs lying around depending on the add-on state limiting what actions are available to users that only have one of the two in some situations. We could simplify the code around permissions quite a bit if it was just a single permission.

cc @jvillalobos @wagnerand for input.

**Comment by jvillalobos** [comment]
I'm okay with merging them. In theory one is for pre-review and the other for post-review, but in practice they are assigned to the same users, and privileged stuff can be gated on `Reviews:Admin` instead.

**Comment by wagnerand** [comment]
Sounds good to me. Soon, we will also have the add-on review categories to have more control over who can review which add-on, regardless of whether it's been auto-approved or not.

**Comment by ioanarusiczki** [comment]
@eviljeff 

"Addons:PostReview" permission was available for "Reviewers: Add-ons" group. A user belonging to that group had no longer access to rev tools on AMO dev. So I replaced "Addons:PostReview" with "Addons:Review". 

@wagnerand Let me know if that's how you expected it. Right now on dev a user from "Reviewers: Add-ons" has access to:

- Other Pending Review Queue : user can Approve or Reject add-ons belonging in this queue. 
- Flagged by Scanners Queue: user can Confirm Approval or Reject Multiple versions for listed add-ons. The unlisted add-ons are not available.
- Flagged for Human Review: the user can view the queue but has no available action buttons (listed versions). Unlisted versions are not displayed. 
- Auto Approved add-ons: user can Confirm Approval or Reject Multiple versions. 

this is the group before (Stage)

![as before](https://user-images.githubusercontent.com/33448286/92228412-80c0df80-eeb0-11ea-8f01-801c9b06e468.png)

now on dev

![after](https://user-images.githubusercontent.com/33448286/92228533-b796f580-eeb0-11ea-9a3d-dd96d7811162.png)

**Comment by ioanarusiczki** [comment]
This has been confirmed that it looks good.
Verified on dev - FF80(Win10).
