### ISSUE TITLE
Error when dowloading stats as CSV: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14796]
See: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/8912735/?referrer=github_plugin

**Comment by willdurand** [comment]
The error occurs because we have column names that are `null` (or `None`).

**Comment by ioanarusiczki** [comment]
@willdurand I could generate the .csv reports, open and view them for beta and legacy stats on AMO dev.

One thing noticed when choosing a custom interval:

If I select an interval, let's say 12.04.2020 - 05.06.2020 the csv report is generated with an extra day 12.04 -06.06 and if 06.06 has data this is displayed too. That's reproducible for both beta and legacy so I assume it's always been this way.

**Comment by ioanarusiczki** [comment]
@willdurand Should I file an issue for what I've described above?

**Comment by willdurand** [comment]
> @willdurand Should I file an issue for what I've described above?

Yes, why not. I think it's a p4.
