### ISSUE TITLE
Upgrade linter to v2

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14791]
Let's upgrade `addons-linter` to v2: https://github.com/mozilla/addons-linter/releases/tag/2.0.0

**For QA:** it would be nice to make sure the validator works as expected when uploading new versions (it should work as before). We support new syntax too, so verifying that would be great too. The link above has links to the new syntaxes.

**Comment by ioanarusiczki** [comment]
@willdurand

-  I uploaded listed/unlisted versions for an add-on, a lang pack, dictionary and theme and I did not get errors from the linter.

- I used the new syntaxes mentioned by the [opened issues](https://github.com/mozilla/addons-linter/releases/tag/2.0.0). I added them into [test.js](https://code.addons-dev.allizom.org/en-US/browse/619970/versions/1691607/?path=test.js) and [test1.js](https://code.addons-dev.allizom.org/en-US/browse/619970/versions/1691607/?path=test1.js). No errors at upload while on prod I saw that it throws "Error: There is a JavaScript syntax error in your code; validation cannot continue on this file." for these two files.

Verified on AMO dev - FF77(Win10).
