### ISSUE TITLE
New stats dashboard: "null" in data, and this prevents CSV export

### ISSUE THREAD

**Issue by psimonyi** [mozilla/addons-server#14790]
### Describe the problem and steps to reproduce it:
On the beta version of the statistics dashboard, in the "daily users by add-on version" view, records before 22 Nov 2019 have the add-on version "null".  The number of users with version null looks as if it's probably the total number of users of any version, though that's hard to tell for sure.  The shape of the graph is similar to the outgoing dashboard, except that before 22 Nov 2019 there is only the "null" version.

In the "by country" view, there are some records with "null" for the country.  These records are still occurring up to the present.

There is an error exporting the statistics to CSV if the selection would include a column for "null" values (versions or countries).

### What happened?
If the selected time range goes back to 22 Nov 2019 or before, and thus includes the "null" versions, clicking the CSV export link goes to the "Oops! We had an error." page.

### What did you expect to happen?
Ideally the data would include the actual values instead of null, but even if there are nulls, I should get a CSV file with a column labelled "null".

### Anything else we should know?
The 22 Nov 2019 date is not related to a release date for my extension, as far as I can tell.  I released the latest version around late August.  Also I checked two extensions that both have the same problem with the same date.

The second extension is far less popular and doesn't have any users from the null country though, and I can download the CSV for that report.

Extensions whose stats I checked:
- https://addons.mozilla.org/en-CA/firefox/addon/open-bookmarks-slowly/
- https://addons.mozilla.org/en-CA/firefox/addon/show-titletext/

**Comment by willdurand** [comment]
I see two issues here. One is about CSV export not supporting `null` values for some reasons, and the second issue is about data containing `null` values.

For the second issue, @jklukas: would you know why we would get `null` values? Should we normalize them to something like `others` or `unknown` maybe?

**Comment by willdurand** [comment]
Looks like the first issue is not about `null` values after all. It is this error in sentry: [OLYMPIA-PROD-9N0](https://sentry.prod.mozaws.net/operations/olympia-prod/issues/8912735/?referrer=github_plugin)

**Comment by willdurand** [comment]
Looks like the first issue is this error in sentry: [OLYMPIA-PROD-9N0](https://sentry.prod.mozaws.net/operations/olympia-prod/issues/8912735/?referrer=github_plugin)

**Comment by willdurand** [comment]
@psimonyi do JSON exports work by chance?

**Comment by willdurand** [comment]
> I'll file an issue for the CSV export.

I filed https://github.com/mozilla/addons-server/issues/14796

**Comment by jklukas** [comment]
The underlying main ping data contains null values for addon version for some addons prior to 2020. See for example: https://sql.telemetry.mozilla.org/queries/72388/source

It's possible that something in desktop firefox code changed to make addon version reporting more reliable, or it's possible that this is due to limitations on the import of legacy heka data from AWS to BigQuery. In either case, the null values that we're seeing in the derived tables are reflecting real null values in the raw data, so there is no way to recover the addon version in these cases.

> Should we normalize null values to something like `others` or `unknown` maybe?

You can either handle that app-side or we can update the view in BQ to make the transformation. The argument for doing it app-side would be that you have control on your side to alter what value is displayed without needing data engineering in the loop.

**Comment by willdurand** [comment]
@jvillalobos what should we do? Should we "hide" those values or create some sort of "unknown" category?

**Comment by jvillalobos** [comment]
I think having an `Unknown` category makes sense.

**Comment by psimonyi** [comment]
@willdurand wrote:
> @psimonyi do JSON exports work by chance?

Yeah, they work as expected, with `null` where the graph and table show null.


@jvillalobos wrote:
> I think having an `Unknown` category makes sense.

I agree; if you omit the null values the version data will be okay (just cut off in time) but the country data won't add up to the expected total.

**Comment by willdurand** [comment]
> I think having an `Unknown` category makes sense.

@jklukas would it be possible to group/normalize `null` values as `unknown` in the ETL pipeline? We do have normalization for OSes so I guess that would work here too.

**Comment by jklukas** [comment]
@willdurand - The following PR will replace `null` keys with "Unknown" as part of the query-time view logic: https://github.com/mozilla/bigquery-etl/pull/1114

Does that look good to you?

**Comment by willdurand** [comment]
> Does that look good to you?

Yes, that looks like what we want. Thanks!

**Comment by willdurand** [comment]
This issue should be fully fixed now (or will be fixed once we update the existing data with `unknown` instead of `null`). Later today, we'll deploy the fix for the CSV export too.

@psimonyi thank you for reporting this issue!

**Comment by psimonyi** [comment]
I've just tried it out and it's working fine.  Thank you!
