### ISSUE TITLE
Add management command applying the delayed reviewers rejections

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14799]
Background: https://github.com/mozilla/addons-server/issues/14454 will be about implementing delayed rejections as an action for reviewers. https://github.com/mozilla/addons-server/issues/14577 is about the developers side. 

We're going to need a cron job that does the rejections, regularly looking at pending versions to reject. https://github.com/mozilla/addons-server/issues/14454 will automate this, for now we want the command without automating it, to ease testing.

From the PRD:
- [ ] If the grace period ends and there’s no version pending review, the rejection is applied and the versions are disabled.

**Comment by diox** [comment]
@jvillalobos in the PRD, there is this:
>  If another new version is submitted while this version is awaiting review, the new version will take its place and the previous one will be disabled. For example: version 1.0 gets a delayed rejection, 2.0 is uploaded and awaiting review, then 3.0 is uploaded before 2.0 is reviewed. The end state is: 1.0 is still on delayed rejection, 2.0 is disabled and 3.0 is pending review.

But the PRD also says:
> If the grace period ends and there’s no version pending review, the rejection is applied and the versions are disabled.

If in that scenario 1.0 is "still on delayed rejection", what happens when the grace period ends, while there is 3.0 pending review ?

**Comment by jvillalobos** [comment]
1.0 should stay on delayed rejection until some action is taken on 3.0.

**Comment by diox** [comment]
So, the deadline is essentially ignored for that version while waiting for something to happen to 3.0 ?

**Comment by jvillalobos** [comment]
Correct. I may be missing some edge case(s), but as far as I know the deadline stops mattering once the new version (2.0) is uploaded. At that point 1.0 is basically "on hold" for what happens to the version pending review and when that happens depends on the reviewers.

**Comment by diox** [comment]
Ok. It's just that the concept of "on hold" doesn't really exist in the code. I'll handle that in the cron, and probably hide the deadline where we're showing it in the reviewer tools if it's not in the future.

**Comment by diox** [comment]
An edge case I see with this however:
- Developer submits 1.0, it's approved
- Developer submits 2.0, it's approved
- Reviewer rejects 1.0 with a delay.

Should 1.0 be rejected when the delay is up ? Same question if 2.0 is somehow not approved yet (but the reviewer doesn't touch it).

**Comment by jvillalobos** [comment]
> Should 1.0 be rejected when the delay is up ?

I don't think there's a realistic case where an old version would be rejected with a delay. If 2.0 is already approved, a rejection should include it. If not, it should be an immediate rejection because the point of the delay is to give a developer time to react when there's an impact to their current version. My preference in that case would be to not allow delayed rejection.

> Same question if 2.0 is somehow not approved yet (but the reviewer doesn't touch it).

So, 1.0 is approved and 2.0 is pending review. If only 2.0 is being rejected, the rejection should be immediate because that version hasn't been approved (so, don't allow delayed rejection, like in the previous case). If 2.0 and 1.0 are being rejected with a delay, the delay should only apply to 1.0, and 2.0 should be disabled.

**Comment by diox** [comment]
> So, 1.0 is approved and 2.0 is pending review. If only 2.0 is being rejected, the rejection should be immediate because that version hasn't been approved (so, don't allow delayed rejection, like in the previous case). If 2.0 and 1.0 are being rejected with a delay, the delay should only apply to 1.0, and 2.0 should be disabled.

The case I was concerned about is when 1.0 is approved, 2.0 is pending review, and 1.0 (and only 1.0) is rejected with a delay, and 2.0 left untouched.

**Comment by diox** [comment]
Another question: we'll be sending an email when the reviewer sets the delayed rejection, and another to remind developers like we do with pending info requests. Do we also need to email them when we're actually applying the rejection ?

**Comment by jvillalobos** [comment]
> The case I was concerned about is when 1.0 is approved, 2.0 is pending review (for instance it has been triggering something causing it not to be auto-approved), and then, 1.0 (and only 1.0) is rejected with a delay, and 2.0 left untouched.

I see. I think this is similar to the case where 2.0 is already approved. It shouldn't happen because it doesn't make sense to reject and old version with a delay if there's already a newer version. Ideally we wouldn't allow this to happen, and old versions can only be rejected immediately if the rejection doesn't cover the latest version.

> Another question: we'll be sending an email when the reviewer sets the delayed rejection, and another to remind developers like we do with pending info requests. Do we also need to email them when we're actually applying the rejection ?

IIRC, the reminder email is sent like a day before the deadline, so I don't think we need a third message.

**Comment by AlexandraMoga** [comment]
@diox I have some add-on versions with expired delayed review rejections from my previous testing - I have add-ons with an expired delayed review rejection for all their versions and also add-ons with their first versions under an expired delayed rejection and their latest versions Awaiting review. 

Also, to make sure that the cron runs only on versions with an expired delayed rejection, we should add an ongoing Pending rejection status on some new versions: 1691487, 1691446, 1691623, 1691320, 1691321

**Comment by diox** [comment]
Added the pending rejection to those versions and fired the command. 

For future reference if needed, here is the edited output explaining the decisions:
```
olympia@ip-172-31-9-19:/data/olympia$ ./manage.py auto_reject
{"Type": "z.files.utils", "Fields": {"msg": "Acquiring lock auto-reject.lock."}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619928: delayed rejection expired versions 1691542 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619928/delayed_rejection_expired-1.0-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619928/delayed_rejection_expired-1.0-fx.xpi"}}
{"Type": "z.addons", "Fields": {"msg": "Changing add-on status [619928]: 4 => 0 (no listed version with valid file)."}}
{"Type": "z.users", "Fields": {"msg": "Not changing 10641527.is_public from True"}}
{"Type": "z.addons", "Fields": {"msg": "Triggering a sync of addon 619928 with basket because of attribute change"}}
{"Type": "z.amo.activity", "Severity": 4, "Fields": {"msg": "Activity log called with no user: 12"}, "severity": 400}
{"Type": "z.addons", "Fields": {"msg": "Version changed from current: 1.0 to None for addon 619928: delayed rejection expired"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619930: new version while PndRj versions 1691546, 1691549 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619930/new_version_while_pndrj-1.0-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619930/new_version_while_pndrj-1.0-fx.xpi"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619930/new_version_while_pndrj-1.1-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619930/new_version_while_pndrj-1.1-fx.xpi"}}
{"Type": "z.reviewers.auto_reject", "Fields": {"msg": "Skipping rejections for add-on 619932 until lock from user 10641527 has expired"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619938: mixed - unlisted pending rej versions 1691559 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619938/mixed_unlisted_pending_rej-1.1-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619938/mixed_unlisted_pending_rej-1.1-fx.xpi"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619939: PndRj unlisted version versions 1691560 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619939/pndrj_unlisted_version-1.0-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619939/pndrj_unlisted_version-1.0-fx.xpi"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619940: pending rejection versions 1691561 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619940/pending_rejection-1.0-an+fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619940/pending_rejection-1.0-an+fx.xpi"}}
{"Type": "z.addons", "Fields": {"msg": "Changing add-on status [619940]: 3 => 0 (no listed version with valid file)."}}
{"Type": "z.users", "Fields": {"msg": "Not changing 10641527.is_public from True"}}
{"Type": "z.addons", "Fields": {"msg": "Triggering a sync of addon 619940 with basket because of attribute change"}}
{"Type": "z.amo.activity", "Severity": 4, "Fields": {"msg": "Activity log called with no user: 12"}, "severity": 400}
{"Type": "z.addons", "Fields": {"msg": "Version changed from current: 1.0 to None for addon 619940: pending rejection"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619941: PndRj first version versions 1691562 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619941/pndrj_first_version-1.0-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619941/pndrj_first_version-1.0-fx.xpi"}}
{"Type": "z.reviewers.auto_reject", "Fields": {"msg": "Skipping rejections for add-on 619966 until version 1691621 has been reviewed"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619967: NEW PndRej multiple vers - clear versions 1691598, 1691603 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619967/new_pndrej_multiple_versions-1.3-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619967/new_pndrej_multiple_versions-1.3-fx.xpi"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619967/new_pndrej_multiple_vers_clear-1.4-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619967/new_pndrej_multiple_vers_clear-1.4-fx.xpi"}}
{"Type": "z.addons", "Fields": {"msg": "Changing add-on status [619967]: 4 => 0 (no listed version with valid file)."}}
{"Type": "z.users", "Fields": {"msg": "Not changing 10641527.is_public from True"}}
{"Type": "z.addons", "Fields": {"msg": "Triggering a sync of addon 619967 with basket because of attribute change"}}
{"Type": "z.amo.activity", "Severity": 4, "Fields": {"msg": "Activity log called with no user: 12"}, "severity": 400}
{"Type": "z.addons", "Fields": {"msg": "Version changed from current: 1.4 to None for addon 619967: NEW PndRej multiple vers - clear"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619968: NEW CLEAR PndRej multiple versions versions 1691599, 1691605 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619968/new_pndrej_multiple_versions-1.3-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619968/new_pndrej_multiple_versions-1.3-fx.xpi"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619968/new_clear_pndrej_multiple_versions-1.4-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619968/new_clear_pndrej_multiple_versions-1.4-fx.xpi"}}
{"Type": "z.mailer", "Fields": {"msg": "Making 619972: PndRj unlisted version versions 1691611 disabled"}}
{"Type": "z.files", "Fields": {"msg": "Moving disabled file: /mnt/efs/addons-dev.allizom.org/files/619972/pndrj_unlisted_version-1.0-fx.xpi => /mnt/efs/addons-dev.allizom.org/guarded-addons/619972/pndrj_unlisted_version-1.0-fx.xpi"}}
{"Type": "z.files.utils", "Fields": {"msg": "Releasing lock auto-reject.lock."}}
```

**Comment by AlexandraMoga** [comment]
I've verified the results on -dev and they appear to be as expected. 

A couple of examples:
[619966](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/new-pndrj-first-version) - delayed rejection not removed from version 1691597 (version not rejected) because the add-on's latest listed version is Awaiting review
[619967](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/new-pndrej-multiple-vers-clear) - had two listed versions pending rejection => both versions are fully rejected now

The versions that had an ongoing delayed rejection will keep their status after the cron runs. 

![image](https://user-images.githubusercontent.com/31961530/86928655-82cf2200-c13d-11ea-9032-f4afce6c7dce.png)

@diox  from the logs above, I get that add-on 619932 was skipped by the cron because it was locked by a reviewer (me). With this add-on, I intended to test what happens when a listed version has an expired delayed rejection and an unlisted version is Awaiting review. I didn't find any mentioning of this scenario in any of the comments.

**Comment by diox** [comment]
If you unlock the add-on by closing the relevant tab the rejection should take place (unlisted version shouldn't be affected).

**Comment by AlexandraMoga** [comment]
@diox I've closed the tab. The cron should pick the add-on now.

**Comment by diox** [comment]
Done

**Comment by AlexandraMoga** [comment]
All good. The listed version has been automatically rejected and the unlisted versions are unaffected.
