### ISSUE TITLE
Make beta stats the default stats (and remove legacy stats)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14807]
Let's remove the legacy stats pages and replace them with the beta pages. We're going to get rid of the beta waffle flag and there won't be any way to access the legacy stats anymore.

The beta flag won't be used but it won't be deleted now to avoid potential issues during deployment.

**Comment by ioanarusiczki** [comment]
@willdurand On dev - FF78(Win10):

- there's no longer a beta URL - it's 404 (even if the beta cookie is true). And for the [samples](https://addons-dev.allizom.org/en-US/firefox/addon/amo-info-with-extra-dirs/statistics/usage/countries/?last=365) available the stats are displayed (what used to be beta before).

- lang packs and dicts no longer have stats of any type. The stats URLs from dev hub have been removed. I don't know if that's expected to be temporary or permanent?

**Comment by willdurand** [comment]
> lang packs and dicts no longer have stats of any type. The stats URLs from dev hub have been removed. I don't know if that's expected to be temporary or permanent?

Expected. There was no beta for langpacks/dicts.
