### ISSUE TITLE
Add admin-only button in reviewer tools to clear all delayed version rejections

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14816]
Was supposed to be done in https://github.com/mozilla/addons-server/issues/14579 but I implemented the API forgetting to add the button calling it.

**Comment by AlexandraMoga** [comment]
A 'Clear pending rejections' button will appear in the the Admin actions section if the add-on has one or more versions Pending rejection. The Pending rejection status is removed from all the affected versions when the button is selected*. 
The button is exposed only to Admin reviewers. 

![image](https://user-images.githubusercontent.com/31961530/86801499-bc8c2400-c07c-11ea-916a-1952e7ac59a1.png)

*Note that to actually verify that the Pending rejection status was cleared, a page refresh is required.

Verified fixed on -dev.
