### ISSUE TITLE
Delete `UpdateCount` model and everything related to it

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14811]
We don't need this model anymore so let's drop the code related to it and the model itself. We'll remove the DB table in a different patch and tag.

**For QA:** this should not have any noticeable impact from a user/admin perspective.

**Comment by ioanarusiczki** [comment]
@willdurand I verified on AMO dev:
- a user can only view the personal stats (for the submitted add-ons).
- an admin can see stats for all add-ons. 
- none of the users can see stats for dicts or lang packs.
- URLs no longer redirect to beta.
