### ISSUE TITLE
Upgrade travis to use Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14828]
Travis currently uses 16.04 LTS.
Let's update to 18.04 which is the latest LTS supported by travis, because why not. All tests pass.

**Comment by diox** [comment]
> because why not.

Because 16.04 LTS is the closest version to the Debian version we're using in production.

**Comment by diox** [comment]
> Because 16.04 LTS is the closest version to the Debian version we're using in production.

That's not true actually, 18.04 is closer now that our docker images are built from Debian Buster (https://github.com/mozilla/addons-server/issues/13985)
