### ISSUE TITLE
csv reports are generated within the chosen interval plus one extra day

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#14826]
From https://github.com/mozilla/addons-server/issues/14796#issuecomment-652378499

STR:
1. Go to an addon with stats such as https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/usage/?last=30
2. Generate a report with a custom date range  let's say 12.04.2020 - 05.06.2020 and export it in .csv format. 
3. Open the report and observe the intervals.

Actual result:
 the csv report is generated with an extra day 12.04 -06.06 and if 06.06 has data this is displayed too. 

Expected:
report should be for 12.04.2020 - 05.06.2020

Notes:
That's reproducible for both beta and legacy - FF77(win10).

**Comment by ioanarusiczki** [comment]
@willdurand I tried with more intervals for the usage stats but I still get am extra day in the report.

I also see that Custom date allows selection of invalid intervals, meaning I can choose From 2020.07.10 to May 2020.05.21. In this case the graph displays" No data available.", a .csv is generated with 20200710-20200521 and of course it is empty. -> In case I should file an issue, not to allow this type of selection, let me know.

**Comment by AlexandraMoga** [comment]
I've re-verified the .`csv` report downloads on -dev and the custom date intervals are correct now.
