### ISSUE TITLE
Delete ES index for "update counts"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14823]
Once https://github.com/mozilla/addons-server/issues/14811 lands, we'll be able to delete the ES index for the usage stats (update counts). We think that it can be done as a one-off command run by ops (after the push).

@bqbn could you see how to do this? We'll be able to test in -dev and -stage before -prod next week I believe.

**Comment by bqbn** [comment]
I think we also need to delete the alias, yes?

I think the commands will be similar to the following,

```
to_remove_alias=<to remove alias name>
to_remove_index=<to remove index name>

curl -X POST "localhost:9200/_aliases?pretty" -H 'Content-Type: application/json' -d"
{
    \"actions\" : [
        { \"remove\" : { \"index\" : \"$to_remove_index\", \"alias\" : \"$to_remove_alias\" } }
    ]
}"

curl -XDELETE "http://localhost:9200/$to_remove_index/"
```

**Comment by willdurand** [comment]
> I think we also need to delete the alias, yes?

Yes

**Comment by willdurand** [comment]
@bqbn you should be able to try that in -dev and -stage.

**Comment by bqbn** [comment]
I have removed the "update count" index in -dev and -stage environments.

Please test it and if OK, we'll delete it tomorrow in -prod.

**Comment by willdurand** [comment]
> Please test it and if OK, we'll delete it tomorrow in -prod.

I looked at the -dev instance and I don't see the update counts index anymore.

**Comment by bqbn** [comment]
The "update count" index in -prod has been deleted as well.
