### ISSUE TITLE
Error "Someone tried deleting something they shouldn't"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14831]
I noticed this error in -prod:

```
Someone tried deleting something they shouldn't: /mnt/efs/addons-internal.prod.mozaws.net/shared_storage/uploads/userpics/5/5345/5345XXX.png
```

It is logged here: https://github.com/mozilla/addons-server/blob/9a129eb7a443fe77afdf49fc439310815d8eeec9/src/olympia/users/tasks.py#L20-L23

**Comment by diox** [comment]
We pass the full path of the file to the task, but what we should pass a path relative to the mountpoint, or some identifier from which the task would reconstruct the path.
