### ISSUE TITLE
Lots of UnicodeEncodeErrors going to sentry

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14849]
We are getting lots of UnicodeEncodeErrors going to sentry, apparently with a custom format, so each is added a separate entry: https://sentry.prod.mozaws.net/operations/olympia-prod/?query=is%3Aunresolved+UnicodeEncodeError

Can we try and identify the source of that error and update the error handling so sentry can group these correctly?

**Comment by diox** [comment]
This is essentially requests with malformed data. They were previously not recorded because we didn't capture `log.exception()`. 

IMHO we should try to avoid them entirely.

**Comment by diox** [comment]
This would be typical for some automated vulnerability scanning to try to inject specific characters like a null character in the query string and we have some of that, but weirdly, we also have a lot of different requests with the same `鎈` character at different positions. They look like this:
- `'currentAppVersion[1]': '3鎈\'"\\('`
-  `'reqVersion': '2鎈\'"\\(',`
- `'updateType[0]': '=2鎈\'"\\(and 3 in '`

**Comment by diox** [comment]
QA: test that the update service still works ; Then play with the URL (like https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=2&id=%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D&version=3.5.2&maxAppVersion=77.%2A&status=userEnabled%2Cincompatible&appID=%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D&appVersion=78.0.112&appOS=Linux&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=78.0.112&updateType=49&compatMode=normal) adding special characters in various places, you should still get a valid json response.

**Comment by ioanarusiczki** [comment]
@diox I'll try to update to the latest version some addons and themes - check they do well with manual and automatic update (after restarting the browser). (so far it's going well)

About the json above, depends very much of the "various places" because I already broke it. Could you be a bit more specific?

**Comment by ioanarusiczki** [comment]
@diox Results:
- the [specified](https://github.com/mozilla/addons-server/issues/14849#issuecomment-654788608) URL works as expected, returning `{}` as a response.
- I verified the update service on AMO dev and AMO stage - works fine.
