### ISSUE TITLE
Addon.MultipleObjectsReturned: get() returned more than one Addon -- it returned 155!

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14853]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9020417/?referrer=github_plugin

```
Addon.MultipleObjectsReturned: get() returned more than one Addon -- it returned 155!
  File "olympia/addons/tasks.py", line 92, in update_addon_average_daily_users
    addon = Addon.objects.get(**{kw['id_field']: addon_id})
  File "django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
```

This is because we have empty rows in BigQuery. It shouldn't happen and I asked the Data team to take a look but the patch to protect AMO against this error is small, so it's worth fixing this issue in our code too.

**Comment by ioanarusiczki** [comment]
@willdurand If I can verify this on dev please let me know. 
Thanks!
