### ISSUE TITLE
Refactor recommended add-ons to be a PromotedAddon (rather than a type of DiscoveryItem)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14859]
>Initial backend work to refactor DiscoveryItem.recommendable + Version.recommendation_approved into separate models with different promotion states (both in database+elasticsearch)

depends on #14858 to add the new models

**Comment by bobsilverberg** [comment]
@eviljeff Will this include changes to the API to return the promoted category type in the response? Do you have any thoughts about what that might look like? I imagine we could just have a field called something like `promotedCategory` which would either be `null`, if the add-on does not belong to a category, or an expected value for the category.

**Comment by eviljeff** [comment]
Exposing new fields in the API won't be part of this issue.  `recommended` will still exist as a field and sort (and etc), with probably some backend changes.

**Comment by bobsilverberg** [comment]
Thanks @eviljeff. Is there an issue to expose the new categories via an API? That's needed to support front-end changes. Once the models and refactoring is done, that is something that I could perhaps work on.

**Comment by eviljeff** [comment]
QA: this changes how recommended is implemented, so everywhere that recommeneded status is exposed should be checked to confirm it still works as expected (primarily the frontend but also in devhub - stopping developers from deleting the current version if the previous version isn't recommeneded - and in reviewer tools - not auto approving).

recommended status is now set in /admin/models/promoted/promotedaddon rather than /admin/models/discovery/discoveryitem - the existing recommenditems should have been migrated over.  

PrimaryHero management as part of the DiscoveryItem is gone in this issue, and will reappear as part of PromotedAddon in #15028

**Comment by ioanarusiczki** [comment]
@eviljeff I've been testing around admin, rev tools and dev hub. I think the new model works as expected, so I won't add all my testing results, I'm only writing down the question marks. 

What I can't tell if it's alright (expected): 

- removing a recommended version from admin - "Promoted Approvals" section removed the badge (as expected). I don't have the option to add it back. The previous model had a check box which allowed the operation. 

- when I add a new add-on to the list, "promoted approval section" always displays a list of 8 add-ons with their recommended versions. I think that should be empty. 

- a deleted add-on from dev hub is not deleted from the list of promoted add-ons. (should be expected, still not 100% sure)

- there's some add-ons left in the old model admin/models/discovery/discoveryitem/ which I've found being transferred in the new one.

**Comment by ioanarusiczki** [comment]
@eviljeff One thing I forgot to add : I remember the static themes used to have a collection in which when they were added - the recommended badge was added on the frontend. Is that still available or the new model is going to be used for themes too? Or both?

**Comment by eviljeff** [comment]
> removing a recommended version from admin - "Promoted Approvals" section removed the badge (as expected). I don't have the option to add it back. The previous model had a check box which allowed the operation.

I debated about being able to delete either - changing the approval status doesn't generally make sense as the xpi will have specific content added when signing so changing it via admin doesn't affect what the Firefox user would see on install.  Removing approval from a version can be used to temporarily remove the group until the next version is approved though, which seems like a possible use-case.

> when I add a new add-on to the list, "promoted approval section" always displays a list of 8 add-ons with their recommended versions. I think that should be empty.

Yes, that's weird.  Maybe there's some old odd data in the database on -dev.

>  a deleted add-on from dev hub is not deleted from the list of promoted add-ons. (should be expected, still not 100% sure)

That's fine - I think.  It works that way on stage for recommended now, right?

> there's some add-ons left in the old model admin/models/discovery/discoveryitem/ which I've found being transferred in the new one.

They should all still be there.  DiscoveryItems are still powering the discovery pane in Firefox (that will probably change in the future, but mozilla/addons-frontend#9379 is a blocker-ish there)

**Comment by eviljeff** [comment]
> I remember the static themes used to have a collection in which when they were added - the recommended badge was added on the frontend. Is that still available or the new model is going to be used for themes too? Or both?

themes should continue to use the collection, as now.  (Though, as now also, they can technically be added to a Promoted group too)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- stage works the same way for deleted add-ons.
- I believe the reason why promoted contains more add-ons compared to the discovery is because of the testing. I can’t check it right now because I can’t access the promoted model right now - 500 error
