### ISSUE TITLE
Sort by `in_progress` too in `git_extraction` cron task

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14854]
@wagnerand noticed a weird behavior when all entries have the exact same date: order isn't guaranteed by MySQL so we can end up with more than one entry with `in_progress=False` for the same entry. We think that we could fix this by adding `in_progress` in the `order()` call.

Note: This is an edge case that only occurred while git-extracting very large add-ons.

**For QA:** this might be tricky to reproduce so verifying that the git extraction works as expected should be enough.

**Comment by ioanarusiczki** [comment]
@willdurand I uploaded new [versions ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/12roboform-password-manager) and [add-ons](https://addons-dev.allizom.org/en-US/developers/addons?sort=created) (~25 consecutive uploads), all have been extracted on AMO dev - FF78(Win10).
