### ISSUE TITLE
restrict review actions for Promoted Addons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14864]
> All add-ons in the Line, Strategic, and Spotlight lists will have review actions restricted to admin reviewers. Regular reviewers can only Comment or Request Super Review.

 > [P2] Make admin reviewer-only restriction a configuration option per list.

**Comment by AlexandraMoga** [comment]
I've verified the review rules for the all the promoted add-on groups and these are my results:

- Regular reviewers (permissions used: `Addons:PostReview`, `Addons:Review`)
  - can Approve/Reject add-ons belonging to the Verified - Tier 1 and Tier 2 groups
  - can only Comment and Request super review for add-ons belonging to the Line, Strategic and Spotlight groups
- Admin reviewers (permissions used: `Addons:PostReview`, `Addons:Review`, `Reviews:Admin`) 
  - can perform any review actions for all promoted groups, except for Recommended (`Addons:RecommendedReview` is required) 

Based on the requirements laid out in this [sheet](https://docs.google.com/spreadsheets/d/1ENbv1CuLDd25Sk0XAwgbWTl9is5rV12OxJD6g1kUi48/edit#gid=1788006942) the results are correct. 

I've also found an issue with Strategic add-ons - filed #15268 as a follow up.
