### ISSUE TITLE
Keep the Review log for deleted addons

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#1486]
ref: `https://addons.mozilla.org/en-US/editors/reviewlog`

From what it appears, once an addon is reviewed if it is then deleted, its entry in 'reviewlog' is also deleted.

It would be really helpful if the 'reviewlog' entries were kept.

For example, in cases where we have to revisit rejection reasons, or when a developer re-uploads the same rejected addon, after deleting the original and starting a new addon, etc

I recently was looking for an exact rejection reason that I had come across but couldn't find it since the addon was deleted.

PS. Off-Topic: I also have a suspicion that the review points for deleted addons may be vanishing.

**Comment by eviljeff** [comment]
I can't replicate this and I can see review comments for deleted add-ons in the review log.
e.g. https://addons.mozilla.org/en-US/editors/reviewlog?start=2016-03-01&end=&search=versionone shows the original add-on that was deleted (with the slug of `none`), and the replacement listing.
