### ISSUE TITLE
Pre-review for Promoted addons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14862]
> When an add-on is added to either of the Verified, Spotlight, or Line lists, it won’t be fully added until its next version passes review, like it’s done with Recommended Add-ons.

> [P2] Make auto-approval a configuration option per list.

**Comment by eviljeff** [comment]
@jvillalobos  were you expecting the "Recommended" queue to expand to include the other pre-review groups of promoted add-ons, be part of "Other Pending Review", or be in a new queue of promoted-but-not-recommended add-ons?

**Comment by jvillalobos** [comment]
The "Other Pending Review" sounds like the most appropriate to me. @wagnerand, thoughts?

**Comment by eviljeff** [comment]
Okay, this is going to happen by default with pr #15122 (auto approval will be disabled, so it'll end up in the "Other Pending Review" queue).  If a different queue is needed please file an issue detailing the name; any special permissions; expected review actions; etc.

**Comment by wagnerand** [comment]
That sounds fine for me.

On the queue page, can an icon indicate which promoted category the add-on belongs to?
On the review page, can the category also be exposed, like we do for recommended at the moment?

**Comment by eviljeff** [comment]
> On the queue page, can an icon indicate which promoted category the add-on belongs to?

filed #15124

> On the review page, can the category also be exposed, like we do for recommended at the moment?

I'll do that with #15123

**Comment by AlexandraMoga** [comment]
@eviljeff here are my test results after having verified this issue on -dev. There are a few issues and questions (I've tried to mark them accordingly).

- [recommended](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/universal-bypass) add-ons - the review and approval process work as before

- **works**: new versions for add-ons belonging to [Verified-Tier 1](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/perms-and-optional-perms), [Verified-Tier 2](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/more-optional-permissions), [Line](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/devhub-listed-ext-04-30) or [Spotlight](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/shared-owner) will not be auto-approved and the review page will include the following message next to these versions: 'Is in a promoted addon group that requires pre-review'
- **not working**:  neither of these add-on shows up in the [Other Pending Review](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/extension) queue (I've verified with an admin account so this shouldn't be related to permissions)

- **Q**: new versions for add-ons belonging to the [Strategic](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/shared-developer-this-owner) group are auto-approved normally. I've noticed this category was not mentioned in the [requirements list](https://github.com/mozilla/addons-server/issues/14862#issue-651724319) as requiring pre-review, but the comments in the [PRD](https://docs.google.com/document/d/1QpEfiiAnfoEGsJuDbYe69WfYoQ_f_9DqPhK3VKWv9kc/edit#bookmark=id.915bgay5q3xx) mention something about a permanent admin flag - so shouldn't they be automatically flagged for admin review?

- **works**: If an add-on is no longer promoted, the next submitted version will be auto-approved normally.

- **Q**: Unlisted versions are not bound by these rules, i.e. if a Promoted add-on receives a new unlisted version, that version will be auto-approved. I haven't seen references to unlisted add-ons being in scope (currently) for the Promoted add-ons program, so I believe this behavior is expected?

**Comment by eviljeff** [comment]
> not working: neither of these add-on shows up in the Other Pending Review queue (I've verified with an admin account so this shouldn't be related to permissions)

Can you file a follow-up?  I thought they'd show up there automatically when they weren't auto-approved.

> Q: new versions for add-ons belonging to the Strategic group are auto-approved normally. I've noticed this category was not mentioned in the requirements list as requiring pre-review, but the comments in the PRD mention something about a permanent admin flag - so shouldn't they be automatically flagged for admin review?

it will be done in/with #14864

> Q: Unlisted versions are not bound by these rules, i.e. if a Promoted add-on receives a new unlisted version, that version will be auto-approved. I haven't seen references to unlisted add-ons being in scope (currently) for the Promoted add-ons program, so I believe this behavior is expected?

The PRD only mentions listed versions, (unlisted wasn't implemented for recommended either in the older implementation) Any unlisted versions shouldn't have the PromotedApproval created for that version. (if the approval was created it'd be shown in the admin page for that PromotedAddon)
