### ISSUE TITLE
Add admin tooling to manage Promoted addons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14861]
> Admin tool to manage the lists of add-ons. Any add-ons (regardless of type, status, or distribution method) can be added to or removed from these lists.

> An add-on can only belong to a single list at any time.

**Comment by ioanarusiczki** [comment]
@eviljeff Test results on dev:
- the promoted model is available, `+add promoted addon` button is functional, I could  add all types of add-ons in all states (except for the deleted ones, but I think that's expected), listed and unlisted.
- addons can be removed from the list by deleting them individually. A deleted add-on from the list can be added back without errors.
- when trying to add an add-on that already exists in the list I receive a warning ` Promoted addon with this Addon already exists.` - probably it should say with this id (I'm going to file an issue)
- filter by group works as expected.

**Comment by eviljeff** [comment]
> "Promoted addon with this Addon already exists."

It's a django admin generated message.  The model is called "PromotedAddon" and the field that links it to an Addon is called "Addon", so it's just using those and prettifying the names a little in the message.
