### ISSUE TITLE
Add details of promoted status to xpi when signing

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14863]
> When an add-on is added to either of the Verified or Line lists (not Spotlight), it should be reflected in the mozilla-recommendations.json file when signed, under “states” (values: “sponsored” for Verified tier 1, “verified” for Verified tier 2, “line” for Line).

**Comment by eviljeff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1657419 for autograph work

**Comment by AlexandraMoga** [comment]
@eviljeff I don't see the `mozilla-recommendations.json` file being created after approving an add-on belonging to the promoted categories mentioned above. 
Example of a Verified - Tier 1 approved add-on:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/cancel-and-disable1

The fie is being created for recommended add-ons, as before.

**Comment by eviljeff** [comment]
sorry, forgot to mention there's a waffle `autograph_promoted_signer` - and it relies on upstream config changes I added in autograph (which have landed in their repo... but I'll need to check their deployment schedule and what server we use on addons-dev)

**Comment by eviljeff** [comment]
@AlexandraMoga the autograph changes are live. If the waffle is enabled on AMO it should work

**Comment by AlexandraMoga** [comment]
Add-ons from the categories enumerated below will receive the `mozilla-recommendations.json` file when they are signed and will have the following states:

- [Recommended add-ons](https://addons-dev.allizom.org/en-US/developers/addon/email-new-version-while-pndrej/edit) - `"states":["recommended"]`
- [Verified - Tier 1 add-ons](https://addons-dev.allizom.org/en-US/firefox/addon/perms-and-optional-perms/) - `"states":["sponsored"]`
- [Verified - Tier 2 add-ons](https://addons-dev.allizom.org/en-US/firefox/addon/more-optional-permissions/) - `"states":["verified"]`
- [Line add-ons](https://addons-dev.allizom.org/en-US/firefox/addon/devhub-listed-ext-04-30/) - `"states":["line"]`

The `mozilla-recommendations.json` is not created for unlisted versions belonging to these promoted add-ons. 

Strategic and Spotlight add-ons will be signed normally, i.e. they won't receive a `mozilla-recommendations.json` file.

I'm marking this issue as verified fixed on -dev.
