### ISSUE TITLE
Build an API endpoint for shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#14873]
Supports #14871

Build an API endpoint (`/api/v4/shelves/`) that represents a list of shelves from the previous issue ( #14872).

**Comment by AlexandraMoga** [comment]
@xlisachan a request to https://addons-dev.allizom.org/api/v4/shelves/ returns a `500 Internal server error` response. I've tried both with an authenticated and an unauthenticated user.

**Comment by xlisachan** [comment]
@eviljeff I am not quite sure what I missed in the process of getting this to work on dev. Can you please point me in the right direction when you have a moment? Thank you!

**Comment by eviljeff** [comment]
> I am not quite sure what I missed in the process of getting this to work on dev. Can you please point me in the right direction when you have a moment? Thank you!

@xlisachan 
```
UnboundLocalError: local variable 'url' referenced before assignment
  File "rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "rest_framework/serializers.py", line 677, in to_representation
    return [
  File "rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "rest_framework/fields.py", line 1905, in to_representation
    return method(value)
  File "olympia/shelves/serializers.py", line 29, in get_url
    return url
```
I would assume `obj.endpoint` isn't `search` or `collections` so it's not set.  Might be some old data on -dev from when there were more endpoint options.  Either initialize `url` to `None` at the top of the method or add an `else: url = None` after the `elif`

**Comment by xlisachan** [comment]
Thanks for the insight, Andrew! I see... I need to remember my `else` statements. Could `url` be set to an empty string as well or is `None` preferable?

**Comment by AlexandraMoga** [comment]
@xlisachan Initially I believed this API was meant to return a list of all the shelves added through the [/shelfmodule/](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/) but after testing it again I see that it actually represents a list of all the enabled [/homepageshelves/](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/). 

The endpoint is functional now and, as mentioned above, it will return a list of all the homepage shelves Enabled in the admin. I've enabled several shelves that contained varied data to make sure that the API responds well. 

I'm marking this issue as verified fixed on -dev.
