### ISSUE TITLE
Disabled addons belonging to deleted/banned users should be hard deleted too

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14875]
Follow up for #14809 

### Describe the problem and steps to reproduce it:
1. Have a user account deleted more than 7 years ago that also has an associated disabled add-on version - see [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641822/change/)
2. Once the cron that clears user data (including hard deleting add-ons) runs on this account, verify if the disabled add-on is still available

### What happened?
The add-on is still available - see [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/498514/change/?_changelist_filters=authors%3D10641822)

### What did you expect to happen?
The add-on should have been deleted

### Anything else we should know?
- In https://github.com/mozilla/addons-server/issues/14809#issuecomment-654733147, I'm mentioning that this case might occur when dealing with banned users
- @eviljeff in the case of banning, both the add-on and the version statuses will be `Disabled by Mozilla`. I think an add-on can also end up with the same statuses when an admin reviewer Force disables an add-on from reviewer tools, so this doesn't have to be caused necessarily by a ban.
There is also another type of add-on that has an `Incomplete` status and all its versions `Disabled by Mozilla`. I guess these should be hard deleted too?

**Comment by eviljeff** [comment]
> I think an add-on can also end up with the same statuses when an admin reviewer Force disables an add-on from reviewer tools, so this doesn't have to be caused necessarily by a ban.
> There is also another type of add-on that has an Incomplete status and all its versions Disabled by Mozilla. I guess these should be hard deleted too?

Those addons would be set to AMO.STATUS_DELETED during a normal delete (and the Incomplete addon disabled with a ban), so it's just that banning a user sets their add-ons to Disabled rather than deleting them.

**Comment by AlexandraMoga** [comment]
I've verified that there aren't any add-ons available anymore for the user I've given as example in the STR.
@eviljeff Just to be sure that we have enough examples to verify this properly, could you please set the modified date for the following users to > 7 years?

10642075
10642070

**Comment by eviljeff** [comment]
> could you please set the modified date for the following users to > 7 years?
> 
> 10642075
> 10642070

done

**Comment by AlexandraMoga** [comment]
The add-on for the two mentioned user have been hard deleted too (if they were the sole owners of those add-ons).
