### ISSUE TITLE
Add the ability to reorder or change the shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#14874]
Supports #14871

Add the ability to manage the shelves that will appear below the hero area on the AMO homepage. This will includes determining which shelves will appear on the homepage as well as reordering the order of each shelves if necessary.

**Comment by AlexandraMoga** [comment]
@xlisachan I've tested around the https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/ tool and these are the results I have so far:

- for `/homepageshelves/add/`:
  - I can select from the list of available Shelves, Enable and set a Position for the shelf selected
  - the tool will generate an error - 'Shelf management with this Shelf already exists.' - if I'm trying to add a shelf that was already selected for display 
- for `/homepageshelves/`:
  - I can reorder shelves by changing their current position
  - I can Enable/Disable each shelf from the list 
  
I've also noticed that there is no validation for the Position field that would prevent shelves from occupying the same position. 
As seen in the example below, I can set all the shelves with Position 1:
![image](https://user-images.githubusercontent.com/31961530/90029414-8701d880-dcc3-11ea-9aa5-9cf1ee06f4ab.png)

I think it would be a good idea to have some validation on shelves position as well.
