### ISSUE TITLE
Update userprofile.modified when an user gets deleted or banned

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14870]
When a user gets deleted or banned, we should update the `modified` property for that user.

**Comment by wagnerand** [comment]
As a ride-along, can we consider adding the `modified` field to the userprofile django admin page?

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. The Modified date is displayed on the user admin profile page and the date is updated when a user is deleted or banned. 

Example of a banned user: https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642073/change/

![image](https://user-images.githubusercontent.com/31961530/87537359-228f3180-c6a3-11ea-9ee0-3b7198837ca1.png)
