### ISSUE TITLE
Add the ability to create, update, and delete shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#14872]
Supports #14871 

Add the ability to create, update, and delete the shelves that will appear on the AMO homepage by creating a Shelf model. Each shelf will contain fields such as title, type, criteria, footer text, footer link, etc.

**Comment by ioanarusiczki** [comment]
@xlisachan 
The new `shelfmodule` is available in admin dev:
- `add shelf module` button is available and I could add data.
- `title` and `type` are mandatory fields.
- for[ all the fields available](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/) I could add all type of chars without warning messages or errors. 
- `delete` button is also functional. 

I cannot see these new shelves on the frontend yet. Let me know if that's expected for now. 
Thanks!

**Comment by xlisachan** [comment]
@ioanarusiczki, yes that's all that is expected for this issue. Warning messages/errors and displaying shelves on the frontend will be covered in upcoming issues. Thank you!
