### ISSUE TITLE
Uploaded hero images aren't always stored as PNGs after resize

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14886]
### Describe the problem and steps to reproduce it:

1. Go to the admin to upload hero images
2. Upload a JPEG and save

### What happened?

The filename ends with `.jpeg` (or `.jpg`).

### What did you expect to happen?

The filename ends with `.png`.

### Anything else we should know?

The code behind this feature uses [`resize_image()`](https://github.com/mozilla/addons-server/blob/1c224b7742a4a2c6f52088fc17ec4b45675e7541/src/olympia/amo/utils.py#L627), which expects `destination` to be a PNG file (although there is no check and no docs...). This is for both the main image and its thumbnail.

I also noticed the use of temporary files and their names don't have any extension.

**Comment by ioanarusiczki** [comment]
@xlisachan I verified on admin dev:
- the thumbnails for uploaded .jpg files are saved as `png` in `discovery/primaryheroimageupload/` and `discovery/discoveryitem/68/change/` models.
- I also see that the custom image path is saved in `png` format now. 
- I could upload large image files without errors but the task is taking a while (it's ~1 min for a 5 MB file). For a 23 MB file it takes quite some time. (I'm adding it as a note, in case there's something that needs to be done/improved).
