### ISSUE TITLE
Don't list 'Deleted' as a possible author role in devhub

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14885]
followup for #14681 - the `(Deleted)` role is special and shouldn't be exposed to developers in devhub.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

`(Deleted)` is no longer exposed as a role in DevHub ownership page. This role is still available in the admin add-on page.

![image](https://user-images.githubusercontent.com/31961530/87316213-29e0fe80-c52e-11ea-887e-419aa7b5cf3e.png)
