### ISSUE TITLE
Record and store add-on ADU at the time of its block

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14884]
When we block an add-on, we need to record and store its ADU at the time of block approval (if applicable).

The ADU should also be shown on the block information admin page.

**Comment by eviljeff** [comment]
We do actually store this, on the BlocklistSubmission instance, at the point the submission was created.  Though we don't expose it after the submission has been approved and published to Blocks.  Is exposing it on the BlocklistSubmission sufficient, or do you want it shown on the Block page too?  (In cases where a Block has been changed there will be different ADUs from subsequent submissions)

**Comment by wagnerand** [comment]
Ah I see. It's a little cumbersome to extract the data from the JSON blob (in `to_block`) and group it by add-on across multiple blocks. I would prefer if we could store the ADU for each add-on as a separate numerical field in `blocklist_block`.

Questions I need to answer commonly and regularly are among:
* How many add-ons did we block in a given timeframe and how many users were affected by that?
* What are the most impactful add-ons in a block or timeframe?

With that, we should also expose it in the django admin page for a Block, since that is probably the place to go to after blocks have been approved.

**Comment by eviljeff** [comment]
I want to highlight:

>In cases where a Block has been changed there will be different ADUs from subsequent submissions

Should the ADU always be from the latest change?  Or retain the ADU from the when it was first created?

**Comment by wagnerand** [comment]
> I want to highlight:
> 
> > In cases where a Block has been changed there will be different ADUs from subsequent submissions
> 
> Should the ADU always be from the latest change? Or retain the ADU from the when it was first created?

Each option has its pros and cons, and for the sake of simplicity, we have to make some sacrifices. Let's keep/use the ADU from the most recent update.

**Comment by eviljeff** [comment]
So, the use-case for this issue is that people sometimes ask you about how many users we affected by blocks?  And collating that information from the existing data structures in the database takes too long?

**Comment by wagnerand** [comment]
Besides one-off cases, the numbers go into regular reports on add-on security.

**Comment by wagnerand** [comment]
This issue blocks making the AMO block frontend the default, which will happen in a couple of months.

**Comment by eviljeff** [comment]
> This issue blocks making the AMO block frontend the default, which will happen in a couple of months.

How?  The existing legacy tool doesn't show it either.

**Comment by wagnerand** [comment]
Yep, that's why we capture it manually in a spreadsheet.

**Comment by ioanarusiczki** [comment]
@eviljeff This [sample](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/355/change/?_changelist_filters=signoff_state%3Dall) shows on the [blocklistsubmission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/355/change/?_changelist_filters=signoff_state%3Dall) page the number of users (5) which is the same on the [detail page](https://addons-dev.allizom.org/en-US/firefox/addon/amo-info-with-extra-dirs/), [stats](https://addons-dev.allizom.org/en-US/firefox/addon/amo-info-with-extra-dirs/statistics/?last=30) and same on the [block](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26223/change/) page (in the User field)
Before updating this block (I changed the max version) the number was 0 (it had an older block). So I think that proves that ADU is taken at the most recent block update. 

This is before making an edit
![none2](https://user-images.githubusercontent.com/33448286/91558503-215a5100-e93f-11ea-8b20-e1633b0f907f.png)

 If I remember correctly, 5 should be the weekly average, here's the daily users on [stats](https://addons-dev.allizom.org/en-US/firefox/addon/amo-info-with-extra-dirs/statistics/usage/?last=30), I can't tell if that's only a dev issue  but it doesn't look like being updated.

If there's anything else I should be testing let me know.
