### ISSUE TITLE
Ratings for "invisible" addons persist on developer profile pages

### ISSUE THREAD

**Issue by adakaleh** [mozilla/addons-server#14895]
I have 2 extensions. One of them received a rating. Later, I marked that extension as "invisible". However, its rating is still displayed in my profile, under "Average rating of developer’s add-ons". I don't think this is the intended behavior.

See https://addons.mozilla.org/en-US/firefox/user/15596255/

**Comment by AlexandraMoga** [comment]
I've verified with several developer accounts that had both listed public and listed invisible or disabled add-ons, all rated. In all cases, only the rating for the listed public add-on was taken into account on the developer profile page. 

[addons in devhub]
![image](https://user-images.githubusercontent.com/31961530/87532981-9ed24680-c69c-11ea-8c12-4512fc199561.png)

[profile page]
![image](https://user-images.githubusercontent.com/31961530/87533055-b8738e00-c69c-11ea-9bc2-a13fb1b261c1.png)
