### ISSUE TITLE
Add `@mozillaonline.com` to the list of restricted GUIDs

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#14916]
In order to have better control of internally-developed add-ons, we should add `@mozillaonline.com` to the [list of system add-on guids](https://github.com/mozilla/addons-server/blob/9f5a1a06a06f5ce11c1170cca3a8d9ca2ee5e85b/src/olympia/constants/base.py#L393).

**Comment by luckyvs1** [comment]
@jvillalobos I created a PR #14917 for this issue, would you be able to take a look when you have time? Thanks

**Comment by ioanarusiczki** [comment]
Verified on dev and stage - FF78(Win10).
