### ISSUE TITLE
Add addon reviewer flag to disable auto-approval until the next manual approval

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14910]
For #14454 we need a way to disable auto-approval for an add-on until the next manual reviewer approval. I was hoping to re-use the existing flag but we want something separate to avoid re-enabling auto-approval when it's been disabled explicitly by an admin.

That new flag will, as the title suggests, disable auto-approval and automatically be reset when the next version of the add-on is manually approved. Like the other flag that disables auto-approval entirely, it will only affect/be reset by listed versions approvals.

Later, it will be set automatically in #14454 for delayed rejections.

**Comment by AlexandraMoga** [comment]
I've verified the new `Disable auto-approval until next manual approval` flag/button on -dev and I have the following results:

- the button is accessible to admin reviewers who can use it to disable auto-approval for the next listed version; unlisted versions are not affected by it
- the flag is automatically removed when a manual Approval is submitted. Alternatively, auto-approval can be switched on again by enabling the button
- when submitting a delayed review rejection, the flag is set automatically and auto-approval is disabled until the flag is removed or a manual Approval is submitted
- if a version is fully rejected, the flag will not be set
- if the version is fully rejected while having an ongoing pending rejection, the flag will not be cleared and auto-approval continues to be switched off
- the normal Disable listed auto-approval flag is still working as before

@diox currently the new flag can be removed only by a manual Approval, which will probably be the most common use case after delayed review rejections are enabled. There is a scenario however in which Confirming Approval could remove the flag as well: a reviewer submits a delayed review rejection for the latest auto-approved version; the add-on is moved to the Pending rejections queue where an admin reviewer picks it up and Confirms Approval; the pending rejection status is removed but auto-approval remains disabled. This [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/testfxa) shows how this scenario could happen. 

Another case where the flag is not removed is when and Admin reviewer clears the Pending rejection status. Unless the reviewer remembers to enable listed auto-approval as well, new add-on versions will not be approved.

**Comment by diox** [comment]
> There is a scenario however in which Confirming Approval could remove the flag as well: a reviewer submits a delayed review rejection for the latest auto-approved version; the add-on is moved to the Pending rejections queue where an admin reviewer picks it up and Confirms Approval; the pending rejection status is removed but auto-approval remains disabled. 
> Another case where the flag is not removed is when and Admin reviewer clears the Pending rejection status. Unless the reviewer remembers to enable listed auto-approval as well, new add-on versions will not be approved.

I'm not too worried about either cases, because eventually a manual approval will clear the flag. @jvillalobos is that ok for you too or should we do something specific here ?

**Comment by jvillalobos** [comment]
It sounds okay to me.
