### ISSUE TITLE
Update assertion message relating to submission using an invalid GUID

### ISSUE THREAD

**Issue by luckyvs1** [mozilla/addons-server#14918]
### Describe the problem and steps to reproduce it:
I think this assertion message should be updated:

```
            'You cannot submit an add-on using an ID ending with '
            '"@mozilla.com" or "@mozilla.org" or "@pioneer.mozilla.org" or '
            '"@search.mozilla.org" or "@shield.mozilla.org" or "@mozillaonline.com"'
```

to:

```
            'You can only submit an add-on using an ID ending with '
            '"@mozilla.com" or "@mozilla.org" or "@pioneer.mozilla.org" or '
            '"@search.mozilla.org" or "@shield.mozilla.org" or "@mozillaonline.com"'
```

it's rendered from:

https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L1077

And is thrown when the user uses an invalid (one not in the list) of system GUIDs: https://github.com/mozilla/addons-server/blob/9f5a1a06a06f5ce11c1170cca3a8d9ca2ee5e85b/src/olympia/constants/base.py#L393

### What happened?

It currently says:

`ugettext('You cannot submit an add-on using an ID ending with '
                     '%s' % guids))`

### What did you expect to happen?

And should say something which signifies:

`ugettext('You can only submit an add-on using an ID ending with '
                     '%s' % guids))`

### Anything else we should know?

The challenge is this message is also localized and is referenced there as well in addition to the test assertions.

Usages in repository (excluding the localized messages):
- Source: https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L1077
- Assertion: https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/tests/test_views.py#L1404
- Assertion: https://github.com/mozilla/addons-server/blob/master/src/olympia/signing/tests/test_views.py#L330

**Comment by eviljeff** [comment]
How would such a sentence be constructed given an add-on can have an ID of anything, except those specific strings?  Please provide a full alternative sentence to `'You cannot submit an add-on using an ID ending with '
            '"@mozilla.com" or "@mozilla.org" or "@pioneer.mozilla.org" or '
            '"@search.mozilla.org" or "@shield.mozilla.org" or "@mozillaonline.com"'`

**Comment by luckyvs1** [comment]
Thanks @eviljeff, while looking for a more verbose error message and checking the logic it allows you to submit an add-on using an ID ending with if the user has a `@mozilla.com` email -- https://github.com/mozilla/addons-server/blob/647a0f09b893bff7ffe4140cbee7e319d65de3e5/src/olympia/users/utils.py#L57.

I missed both assertions utilize a non `@mozilla.com` user email and hence they are correct.

Will close this issue.
