### ISSUE TITLE
Highlight versions to be reviewed for MAD

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14932]
We'd like to highlight versions that needs human review in the reviewer tools. It's similar to what we currently have for versions flagged by scanners. Let's use some green color to better identify such versions.

If a version is flagged by scanners and flagged for human review, we only show this version as flagged by scanners.

**Comment by AlexandraMoga** [comment]
Versions that have been Flagged for human review are now highlighted in green in the add-on history. If the version is Flagged by scanners and Flagged for human review as well, the scanners flag takes precedence. 

![image](https://user-images.githubusercontent.com/31961530/87797854-f0710180-c853-11ea-84df-7f4d1e1c1cf8.png)

There's a small issue with rejections for which I've filed #14985.
