### ISSUE TITLE
Expose model version in scanners API response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14931]
We'd need the model version to be returned in the scanners API response.

**Comment by willdurand** [comment]
cc @dzeber

**Comment by AlexandraMoga** [comment]
The `model_version` field is exposed in scanners api results with value `null` for `mad`, `yara` and `wat`. The field will have a string value for `customs`. 
Note that `customs` will have a `model_version` value only for new submitted add-ons. Older `customs` results will have `model_version: null` 

Verified fixed on -dev.
