### ISSUE TITLE
Show MAD score in reviewer tools (detail page)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14933]
Above the "Weight" in the add-ons history, let's show the MAD score and add some help text too.

**Comment by AlexandraMoga** [comment]
The Scanner score is displayed in the add-on history*
![image](https://user-images.githubusercontent.com/31961530/87763590-b2f18180-c81d-11ea-9d61-061d4848155f.png)


*Note: versions without a score or older versions that were submitted before the score was implemented will still display the Scanner score field with `n/a` as value
Verified fixed on -dev.
