### ISSUE TITLE
Raise errors in scanner tasks to abort the submission process

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14942]
We'd like to abort the submission process when a scanner raises an error so we should re-raise errors we handle in the different tasks.

**Comment by AlexandraMoga** [comment]
@willdurand do you have some STR for this?

**Comment by willdurand** [comment]
> @willdurand do you have some STR for this?

I think uploading a web extension in -dev would be a good start. It should likely fail because of one of our scanners (which seems to often fail lately). After that, you can ping me and I'll disable this scanner, and re-uploading the same extension should work.

**Comment by AlexandraMoga** [comment]
I wasn't able to reproduce unexpected upload errors in -dev so I'm not sure how we can verify this.

**Comment by AlexandraMoga** [comment]
I've verified this on with an add-on example and I was able to reproduce the upload error. If I'm submitting the same add-on with the problematic scanner disabled, the error is gone.

I think this can be marked as verified fixed on -dev.
