### ISSUE TITLE
Have AMO dev use FxA staging environment

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14949]
AMO dev is currently using stable.dev.lcip.org. We want to use accounts.stage.mozaws.net to be on something closer to production.

**Comment by diox** [comment]
QA: dev should have switched to accounts.stage.mozaws.net, logging in should work, everyone might need to be asked to recreated their FxA account on first login though.

Email change and FxA account deletion on dev needs some special attention and we'll look into that separately.

**Comment by AlexandraMoga** [comment]
> Email change and FxA account deletion on dev needs some special attention and we'll look into that separately.

@diox are you saying that this can't be tested at the moment?

**Comment by diox** [comment]
I suspect it doesn't work at the moment and I need to look into it (it's a separate system)

**Comment by AlexandraMoga** [comment]
As mentioned in https://github.com/mozilla/addons-server/issues/14949#issuecomment-658969829 all existing accounts on -dev had to be recreated in FxA at the first log in. Apart from that, I did not notice issues with log ins, log outs or new account registrations.
