### ISSUE TITLE
Add application support to Promoted models

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14941]
from the prd comments

> We  expect to have two distinct lists of Recommended add-ons for desktop  and mobile... Since an add-on could belong to both lists and so far promoted lists are exclusive, I  think it might be better to have a single Recommended list and then a  per-recommended-add-on application setting, but that's an engineering  decision.

**Comment by bobsilverberg** [comment]
Is the idea here that each add-on can have one Promoted Category, and then for each Promoted Category there can be multiple applications to which it applies? If so, is the `android` application going to be reused for Fenix, or are we looking at adding another application for that?

**Comment by eviljeff** [comment]
> Is the idea here that each add-on can have one Promoted Category, and then for each Promoted Category there can be multiple applications to which it applies?

the PromotedAddon would be specific to an application, or to all applications (it would need reworking in the future if we have more than 2 applications and we want more than 1 but not all applications to be promoted for a category)

> If so, is the android application going to be reused for Fenix, or are we looking at adding another application for that?

Fenix changes aren't in scope for this issue (or project) but coincidentally I was asking about Fenix on Slack just now and it's the same GUID so I guess the same application.

**Comment by ioanarusiczki** [comment]
@eviljeff If I can help with some testing for this issue, please add some STR for qa.
Thanks!

**Comment by eviljeff** [comment]
It's not possible to test until the admin is there, so the testing can be done with #14861 I think

**Comment by ioanarusiczki** [comment]
@eviljeff When an add-on is added to the list there's the choice for `Application`. I could choose `All`, `Firefox` or `Firefox for Android`. 
Verified on -dev with FF78(Win10).
