### ISSUE TITLE
Cannot upload sources together with the xpi

### ISSUE THREAD

**Issue by pavelstudeny** [mozilla/addons-server#1494]
steps:
1. Upload new version
2. Select xpi (about 1 MB), it gets validated
3. attach source files (about 14 MB)
4. submit the full form

result:
nothing happens, form stays open

workaround:
submit the xpi without source files, attach source package later

**Comment by andymckay** [comment]
Do you see a JavaScript error in the console when you try this?

**Comment by muffinresearch** [comment]
Testing locally I can't reproduce this. I can successfully upload src and a new version at the same time.

@pavelstudeny could you provide a copy of the xpi + src you're trying upload so we can investigate please?

**Comment by muffinresearch** [comment]
Also which version of FF were you using? There's a bug in FF46 affecting uploads see https://github.com/mozilla/olympia/issues/1503

**Comment by pavelstudeny** [comment]
I'll try to open JS console the next time I'm uploading something. It seems to be a server issue - happens on both Firefox 43 (and 42 before) and Chrome. The xpi in question is https://addons.mozilla.org/cs/developers/addon/avast-passwords/versions/1780044, if you can get there.

**Comment by pavelstudeny** [comment]
I observe this at least from the beginning of November 2015.

**Comment by pavelstudeny** [comment]
A change at AMO from the last week is 'Add-ons built with "cfx" are no longer accepted', so the console log might take me a few hours more.

**Comment by shell15** [comment]
please re-open if still happening.  really appreciate the bug, but we can't reproduce on latest versions
