### ISSUE TITLE
Store uploaded hero images as JPGs

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#14948]
Store primary hero images to .jpg instead of .png, as png images may be too large and impact the size of homepage assets.

**Comment by ioanarusiczki** [comment]
@xlisachan I verified on -dev with FF78(Win10):

- all the uploaded files I've tested with .png, .bmp, .webp, .gif, .tiff and of course .jpg are stored in .jpeg format.
- .svg format is not supported (let me know if I should file an issue for that, in case it should be added).

**Comment by xlisachan** [comment]
@ioanarusiczki We currently do not need this to support .svg format. Thank you for verifying!!
