### ISSUE TITLE
Clear reviewer flags when reviewer approves an unlisted version

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14943]
It's possible for a reviewer to approve an unlisted version (not confirm approval) if the version was not auto-approved because of a scanner rule. We currently don't clear the flags (`needs_human_review` and `needs_human_review_by_mad`) for this version but we should.

**Comment by diox** [comment]
Note: I also cleared it for each version affected by Block Multiple Versions, per discussion in the PR.

**Comment by AlexandraMoga** [comment]
I've verified this on -dev with several unlisted versions - Flagged by scanners, Flagged for human review or with both flags - and made sure the flags were cleared when performing the following reviewer actions: manual Approval (for versions Awaiting review), Reject multiple versions, Block multiple versions, Confirm Approval.

I've also made a quick check for listed versions to make sure that flags are still cleared.
