### ISSUE TITLE
move/copy description_text from DiscoveryItem to PrimaryHero

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14947]
in the serializer for `PrimaryHero` we return details about the addon, and `description_text` from `DiscoveryItem`.  When `PrimaryHero` links to a `PromotedAddon` instead we won't have that data so we should move/copy* it to the `PrimaryHero` model.  *not sure if it's used for the discovery serializer too currently or not.

**Comment by eviljeff** [comment]
@ioanarusiczki the description field is in `models/discovery/discoveryitem/` (for now, anyway).   Previously the custom_description for the discovery item was also used for the primary hero shelf (the primary hero shelf is editable and shown on the same page as the discovery item in django admin)
QA steps:
- see that any existing discoveryitems that have a defined custom_description have that same string copied to description below for the primary hero shelf.
- make a change to the description for the primary hero shelf (or add one if there isn't one defined)
- check the api (/api/v4/hero/primary/) and see that the description returned in the response is the one defined for the primary hero shelf **not** the discovery item custom_description.
- clear the description in primary hero shelf and see that the description returned in the api response is the addon's summary instead.

**Comment by ioanarusiczki** [comment]
@eviljeff Test results from django admin dev - FF78(Win10):

- the discoveryitems with a defined `custom_description` had the same string copied below in the `description` field from the primaryhero section. 

- changes can be saved for the `description` field. Also the frontend will display these changes. 

- the api (/api/v4/hero/primary/) returns the content of the `description` field from the primary hero section.  

- when the `description` is cleared, the api response returns the addon's summary instead.
