### ISSUE TITLE
refactor tests that rely on recommended to use addon_factory(recommended=True)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14966]
we have a lot of tests that create a DiscoveryItem just to set recommended status and for #14859 that won't be the way to define recommended.  Lets make those changes ahead of time so we don't need to change so many tests in the PR for #14859

**Comment by ioanarusiczki** [comment]
@eviljeff Looks like a qa not needed but maybe not. Let me know if I can test here.
Thanks!
