### ISSUE TITLE
Disallow delayed review rejections for versions pending review, except for admins

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14967]
Follow-up for https://github.com/mozilla/addons-server/issues/14454

- [ ] For add-on versions pending review (not signed yet) delayed rejection isn’t an option, so only immediate rejection applies.
    This includes all themes, Recommended extensions, and other add-ons with auto-approval turned off.
- [ ] Admin reviewers can immediately reject versions of add-ons pending rejection. Those versions are disabled immediately, even if they were previously pending rejection. If all versions pending rejection are disabled, the pending rejection state is cleared (but auto-approval should continue to be off).

**Comment by diox** [comment]
@jvillalobos regarding this:
> For add-on versions pending review (not signed yet) delayed rejection isn’t an option, so only immediate rejection applies.

The problem is, the reject multiple versions action lets you select both pending review and approved versions in the dropdown indiscriminately. So for the same action, we could end up immediately disabling some versions, and delaying the rejection of others - we don't really know in advance.

If we modify the action to immediately reject versions pending review and delay the rest when the option to delay is chosen by the reviewer, then we could end up sending an email saying there will be a delay, but some (or all!) of the versions will actually be immediately disabled. The only way to avoid this that I see would be to split the versions into two different categories when processing the action, and depending on whether we have both pending and approved versions, send two separate emails instead of just one. That seems clunky and overly complicated.

Do we really need to disallow the ability to reject a pending version with a delay ? It currently works fine as-is - the fact that the version was approved or not doesn't matter.

**Comment by jvillalobos** [comment]
Okay, let's stick to the current implementation and see if any problems crop up.

**Comment by diox** [comment]
Wontfix for now.
