### ISSUE TITLE
Add `@shield.mozilla.com` to `SYSTEM_ADDON_GUIDS`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14961]
We need to add `@shield.mozilla.com` to `SYSTEM_ADDON_GUIDS` as well. Add-ons that use a GUID ending in these patterns are only allowed to be submitted by users having an email address that ends in `@mozilla.com`.

**Comment by vcarciu** [comment]
Verified as fixed in AMO Stage
