### ISSUE TITLE
Don't hard-delete add-ons for users that have been banned

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#14976]
As mentioned in the standup, maybe we should consider not hard-deleting add-ons for banned users.

**Comment by eviljeff** [comment]
I don't remember this discussion.  What did/does @jvillalobos say?  Is a 7 year old add-on really that useful, even if the user was banned?

**Comment by jvillalobos** [comment]
All I remember from the discussion is that I didn't care much one way or another :). An add-on that has been deleted/disabled for 7 years is certainly of no use to anyone.

**Comment by eviljeff** [comment]
I'm reading that as WONTFIX :)

**Comment by wagnerand** [comment]
By the way, I only filed this issue after Jorge said in the standup this might be worth revisiting 🤷

**Comment by wagnerand** [comment]
But I don't have a super strong opinion on it either. It just felt like the right thing to do.
