### ISSUE TITLE
Set a default model version for some customs results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#14986]
We added a `model_version` field to `ScannerResult` for #14931. It'd be useful to set a default model version to the existing customs results.

**Comment by AlexandraMoga** [comment]
I've verified this issue with the scanners api on -dev and older `customs` results have a default value (not null) for `model_version` now. The `model_version` for the other scanners is still `null`.

@willdurand there is something I've missed in #14931: `customs` scanner results for language tools and themes are still returning `null` for  `model_version` (this includes new submissions too). By contrast, older `customs` scanner results will have the backfilled `model_version` for these add-on types as well.

Example for new results with `null` for `model_version`: https://addons-internal.dev.mozaws.net/api/v4/scanner/results/?scanner=customs - look for Id 12189, 12186
Example for older scanner results with default `model_version`: https://addons-internal.dev.mozaws.net/api/v4/scanner/results/?scanner=customs&page=54 - look for Id 140

**Comment by willdurand** [comment]
> @willdurand there is something I've missed in #14931: `customs` scanner results for language tools and themes are still returning `null` for `model_version` (this includes new submissions too). By contrast, older `customs` scanner results will have the backfilled `model_version` for these add-on types as well.

Yeah, that's fine. We do not run the MAD scanner for those add-on types, see https://github.com/mozilla/addons-server/issues/14082
