### ISSUE TITLE
Give more JWT expiry leeway to API clients with unsynchronized clocks

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1498]
JWT authentication requires a client clock that is close to the server's clock otherwise it's harder to protect against request replay attacks.

A couple people have run into this problem. See: https://github.com/mozilla/olympia/issues/1461 https://github.com/mozilla/olympia/issues/1071 https://github.com/mozilla/olympia/issues/1072

**Comment by kumar303** [comment]
To increase the leeway without adverse affects on security we need nonce checking first: https://github.com/mozilla/olympia/issues/1501

**Comment by kumar303** [comment]
No one has complained about this for a while so I think it's not so important

**Comment by kumar303** [comment]
for the record, we got more complaints: https://github.com/mozilla-jetpack/jpm/issues/517#issuecomment-227974068

**Comment by EnTeQuAk** [comment]
@kumar303 @rpl did you hear anything on this from web-ext since this got opened? We never changed anything afaik but I wonder if people still have problems.

**Comment by kumar303** [comment]
I haven't heard any complaints so it's probably safe to close this.

**Comment by muffinresearch** [comment]
Base on https://github.com/mozilla/addons-server/issues/1498#issuecomment-350045369 I'm going to close this.
