### ISSUE TITLE
expand addon search api to filter by multiple extension types

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#14997]
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v4-addons-search- lets you filter results by type, but only a single type (or no filter, so all types).  For https://github.com/mozilla/addons-frontend/issues/9469 we'd like to be able to have extensions+dictionaries.  

We do similar things with comma-seperated values with other api parameters so it's technically feasible.

**Comment by junngo** [comment]
Hello @eviljeff :)
Should It change `ReverseChoiceField` to `SerializerMethodField`?
Can I ask for a rough guide?

[0]
https://github.com/mozilla/addons-server/blob/5b6fd22dee2045aaa5ba6abfc8773df63ee4bc1c/src/olympia/addons/serializers.py#L318

**Comment by eviljeff** [comment]
I just looked again at the relevant code (https://github.com/mozilla/addons-server/blame/master/src/olympia/search/filters.py) and it's already implemented! (by me, in 2008 🤯)  It's just not documented in the API docs.  So there's nothing to do here unfortunately, apart from a one line change to the documentation.  

Thanks for the interest anyway.

**Comment by eviljeff** [comment]
@junngo it's https://github.com/mozilla/addons-server/blob/master/src/olympia/search/filters.py#L211:L231 fwiw

**Comment by junngo** [comment]
It's interesting about using filter.
Thanks :)
