### ISSUE TITLE
The email sent to developers for delayed review rejections is missing some information

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#14996]
Follow up for #14454 

### Describe the problem and steps to reproduce it:
1. Open an email sent for delayed review rejections -see [example](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/94524/change/)
2. Read the email

### What happened?
There are some words and links missing from the email body (see  highlights in screenshot)

### What did you expect to happen?
The email should have all the necessary information 

### Anything else we should know?
- specifically, the missing information is: `days` after the number of days remaining to respond and a link to the addon versions page in devhub (my guess).
- as a note, the line that specifies the versions that are affected says: "Version(s) affected _and disabled_". Since the versions are not actually disabled yet, maybe we should eliminate that second part to avoid any possible confusion.

![image](https://user-images.githubusercontent.com/31961530/87960411-f0276f00-cabc-11ea-881f-5da72b7a3d16.png)

**Comment by AlexandraMoga** [comment]
@diox the `{{ url }}` part is still not populated. Shouldn't the copy point to `{{ dev_versions_url }}` instead of `{{ url }}` in [this line](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/reject_multiple_versions_with_delay.ltxt#L18)?

![image](https://user-images.githubusercontent.com/31961530/88077692-34ca0d80-cb84-11ea-8822-1d3b0e57e328.png)

**Comment by diox** [comment]
Yeah good catch.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/88187013-abc3dc80-cc3e-11ea-85e8-ee00c57c8b45.png)
