### ISSUE TITLE
Show add-ons with auto-approval disabled until next approval in `Other Pending Review` reviewer queue

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14995]
Follow-up from https://github.com/mozilla/addons-server/issues/14910 I just noticed: The `Other Pending Review` reviewer queue should include extensions for which auto-approval is disabled until next manual approval only.

**Comment by AlexandraMoga** [comment]
The Other Pending Review queue includes the add-ons with a 'Disabled listed auto-approval until next manual approval' as well

Verified fixed on stage.
