### ISSUE TITLE
Frozen add-ons should be deleted when add-on is deleted

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15004]
It looks like frozen add-ons aren't updated/deleted when the add-on is updated. We're using `FrozenAddon` in the `deliver_hotness` CRON task, and it relies on add-on GUIDs. When we delete an add-on, the GUID is cleared, which can cause issues.

We should probably delete the `FrozenAddon` entry when the add-on is deleted.

**Comment by wagnerand** [comment]
We don't clear the GUID anymore when deleting files. Also, a GUID can be reused, so we would have to remember the frozen state somewhere else and re-add it when the add-on gets resubmitted.

Overall, I think just not deleting the add-on from FrozenAddon would be easier.

**Comment by willdurand** [comment]
> Overall, I think just not deleting the add-on from FrozenAddon would be easier.

GUID could be reused for another add-on, though?

**Comment by wagnerand** [comment]
Since it has the same GUID, it would generally be considered the same add-on. Users of the add-on before it was deleted would be updated to a newer version after re-submission etc.

**Comment by willdurand** [comment]
mm I see. Well let's close this issue then
