### ISSUE TITLE
Add logic to query the `amo_stats_installs` view

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15011]
See also: https://github.com/mozilla/bigquery-etl/pull/1190

---

Similar to what we have for usage stats, we'll need pretty much the same functions (`utils.py`) for download stats.

**Comment by ioanarusiczki** [comment]
@willdurand I checked the usage data for 2 addons with BigQuery data on dev and I don't see the numbers being different from stage so I think it should be alright. 
Verified on dev - FF78(Win10).
