### ISSUE TITLE
Remove all usage of the now deprecated `src` URL param

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15014]
According to the [PRD](https://docs.google.com/document/d/1TuMqhEWNlCNDQRgqFywpJvDHTTNjnAq7-3BAXtoFLQ4/edit#), AMO use of the `src` parameter should be replaced to use UTM instead.

> For instance, a homepage link should replace src=homepage-primary-hero with utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-primary-hero (the content param is the only one that would change depending on the circumstance)

We'll need a similar issue in addons-frontend.

**Comment by willdurand** [comment]
@jvillalobos when would be a good time to land this change? Do we need to feature flag it?

**Comment by jvillalobos** [comment]
I suggest landing this as early as possible, so the new dashboard has more useful data. This will break some of the data in the old dashboard, but we can live with a few weeks of that.

**Comment by willdurand** [comment]
> I suggest landing this as early as possible, so the new dashboard has more useful data.

Ok so I suggest we fix https://bugzilla.mozilla.org/show_bug.cgi?id=1653020 in FF first, and then we change the params?

**Comment by willdurand** [comment]
> This will break some of the data in the old dashboard, but we can live with a few weeks of that.
I take it as we don't need a feature flag.

**Comment by jvillalobos** [comment]
> Ok so I suggest we fix https://bugzilla.mozilla.org/show_bug.cgi?id=1653020 in FF first, and then we change the params?

> I take it as we don't need a feature flag.

Yes, and yes.

**Comment by willdurand** [comment]
> We'll need a similar issue in addons-frontend.

See: https://github.com/mozilla/addons-frontend/issues/9547

**Comment by willdurand** [comment]
Patch landed. I am not sure we have much `src` parameters in addons-server these days, though.

**Comment by willdurand** [comment]
> Patch landed. I am not sure we have much `src` parameters in addons-server these days, though.

I don't see any. Closing this issue now and I'll let QA perform a quick check.

**Comment by AlexandraMoga** [comment]
I've browsed around the server side pages (i.e DevHub, RevTools, Statistics) and I couldn't see any side effects of the `src` removal. 

I'm marking this issue as verified fixed on -dev.
