### ISSUE TITLE
Update the documentation in the “About tracking external sources” popup

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15013]
According to the [PRD](https://docs.google.com/document/d/1TuMqhEWNlCNDQRgqFywpJvDHTTNjnAq7-3BAXtoFLQ4/edit#), the link should appear in all download stats pages.

**Comment by willdurand** [comment]
We'll have this popup in all "By XYZ" download stats pages (see #15012). We would need a new copy for each page I suppose or have one copy that would work for each page (i.e. each tracking dimension).

**Comment by willdurand** [comment]
> We'll have this popup in all "By XYZ" download stats pages (see #15012). We would need a new copy for each page I suppose or have one copy that would work for each page (i.e. each tracking dimension).

cc @jvillalobos

**Comment by jvillalobos** [comment]
@caitmuenster What do you think? We could either have something in EW explaining how to use UTM params or link to a generic doc about it.

**Comment by caitmuenster** [comment]
@jvillalobos I like the idea of having a page on EW explaining how to use the UTM params! 

Would we be getting rid of the popups on those pages and directly linking to the EW article?

**Comment by jvillalobos** [comment]
> Would we be getting rid of the popups on those pages and directly linking to the EW article?

Yes, the link would open the EW page in a new tab.

**Comment by caitmuenster** [comment]
Ok, cool. I'll get a draft of the page for your review soon.

**Comment by willdurand** [comment]
> Ok, cool. I'll get a draft of the page for your review soon.

Awesome, thanks. Let me know when we have something to review/link to. Also, we might need to display a banner saying that we're not yet collecting the attribution data using UTM parameters. That's the plan but not something we are currently doing (and we'll likely enable the new download stats without a lot of attribution data at the very beginning).

**Comment by AlexandraMoga** [comment]
All the Downloads by... options will include the "About tracking external sources" link which points to https://extensionworkshop-dev.allizom.org/documentation/manage/monitoring-extension-usage-statistics/

![2020-08-07_18-09-07](https://user-images.githubusercontent.com/31961530/89659986-58f25200-d8d9-11ea-9f7b-a569f354b66e.gif)

**Comment by caitmuenster** [comment]
Not sure if this needs to be called out but `/documentation/manage/monitoring-extension-usage-statistics/` won't be live on EW prod until we release the new version, which will hopefully be this week. The prod URL will be `https://extensionworkshop.com/documentation/manage/monitoring-extension-usage-statistics/`.
