### ISSUE TITLE
Add new "By" download stats pages 

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15012]
According to the [PRD](https://docs.google.com/document/d/1TuMqhEWNlCNDQRgqFywpJvDHTTNjnAq7-3BAXtoFLQ4/edit#), we want the following pages for the new download stats:

- By Medium
- By Content
- By Campaign

We'll keep the "By Source" page.

**Comment by ioanarusiczki** [comment]
@willdurand 

I tested with an admin and a regular account on dev - the waffle active. 

When the users mentioned above are added to `bigquery-download-stats` the [new](https://github.com/mozilla/addons-server/issues/15012#issue-663276455) classification is displayed, including `by Source` and the same data from the general "Downloads" is everywhere, with "unknown" on the right side of the detailed daily stats.
