### ISSUE TITLE
Values in "By" download pages, allowed values and translations

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15027]
Do we want to translate UTM values in the different "By" pages? I guess it might not be possible for all of them, though.

In the legacy system (which relies on a unique parameter named `src`), we restrict the list of allowed values and we translate them: https://github.com/mozilla/addons-server/blob/95cd6007d9c038284f6290247d95e074221c1868/static/js/impala/stats/csv_keys.js#L41

How should we handle the new UTM values? There could be any values, really. FF will likely truncate long string values but apart from that, what do want to do? It seems tricky to maintain a list of allowed values (+ translations) for each dimension (source, content, campaign, medium).

@jvillalobos WDYT?

**Comment by jvillalobos** [comment]
Yeah, UTM values can be arbitrary, so it's best to just show them as-is.

**Comment by willdurand** [comment]
Ok, good. Thanks!
