### ISSUE TITLE
Reimplement PrimaryHero admin tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15028]
The PR for #14859 removes the PrimaryHero from DiscoveryItem.  We need it back!

**Comment by ioanarusiczki** [comment]
@eviljeff I tested on dev:
- the primary hero section has been added to the new promoted model admin.
- if the add-on is not recommended it cannot be added to the primary hero shelf (as in the previous model). 
- I was able to add/remove images from the first Image section (that is expected, the other custom image section will be implemented by Lisa), change the gradient color. 
- once a primary hero add-on is removed (deleted) from the promoted model it will not be displayed on the frontend. 
- I filed https://github.com/mozilla/addons-server/issues/15127
