### ISSUE TITLE
Expose optional permissions in the Addon API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#15036]
This supports the quarterly goal "Display Optional Permissions" ([PRD](https://docs.google.com/document/d/1px08vsGEbI3dggO8xj-6CVAJsh1MAk9IFROBfv3mT6Y/edit?usp=sharing)). In order to display optional permissions on AMO, we'll need them to be returned in the API response. 

We currently return `permissions` in [`current_version.files[].permissions`](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail), so it might make sense to return optional permissions in a similar way. A couple of options are:
- We could expand `permissions` to be an object with `required` and `optional` keys, each of which contains an array of permissions.
- We could rename `permissions` to `required_permissions` and include a new `optional_permissions` array as well.

**Comment by bobsilverberg** [comment]
@diox You are currently listed in the spreadsheet along with me under "Who", but I am willing to work on both the server and frontend parts of this goal. I was going to do some digging into how we currently deal with permissions. Is it okay if I start on this?

**Comment by diox** [comment]
I was thinking of doing the addons-server part, but we can chat about this tomorrow.

**Comment by bobsilverberg** [comment]
After doing a bit of digging, it looks like we can easily just pick up `optional_permissions` from `manifest.json` in the [`ManifestJSONExtractor`](https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L357). We currently have [`WebextPermission`](https://github.com/mozilla/addons-server/blob/master/src/olympia/files/models.py#L663) which stores permissions, so I guess we'd either need to enhance that to be able to store both required and optional permissions, or introduce something like a `WebextOptionalPermission`. We'd also need to adjust the serializer, and I'm sure there are some other places we'd need to make changes, but overall it seems pretty straightforward.

Was there a reason you thought it would be better for you to work on it, or was it just something on your TODO list?

**Comment by AlexandraMoga** [comment]
The addon detail api is returning the new `optional_permissions` field.

Example of an add-on with optional permissions set in its manifest:
https://addons-dev.allizom.org/api/v4/addons/addon/620052/

@bobsilverberg besides the add-on detail page, `optional_permissions` should also be displayed in reviewer tools (this is a request from the PRD). I did not see an issue filed for this, so I'm going to open a follow-up.

**Comment by bobsilverberg** [comment]
> 
> @bobsilverberg besides the add-on detail page, `optional_permissions` should also be displayed in reviewer tools (this is a request from the PRD). I did not see an issue filed for this, so I'm going to open a follow-up.

Thanks, yes, we should have an issue for that.
