### ISSUE TITLE
Skip `update_addon_download_totals()` cron task when `use-bigquery-for-download-stats-cron` waffle switch is active

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15033]
~~Let's update the `update_addon_download_totals()` cron task to use BigQuery. We could use a waffle switch to enable/disable the use of BigQuery and we'll remove it once we are confident enough.~~

We decided to remove the `total_downloads` instead as it is difficult to compute and maintain over time, and it gives very little value to end users so let's not run this cron task when we switch to the BigQuery-based system.

For QA: there isn't really anything to verify here. We prevent the cron task that updates `total_downloads` on each add-on from running when a waffle switch is enabled.

**Comment by willdurand** [comment]
@diox this is going to be interesting because I don't think we have data since the beginning of AMO in Telemetry, which we should have in the `download_count` table (more or less).

Maybe we should change the CRON task to not compute the total downloads but rather increment `addon.total_downloads` with the number of downloads from the day before?

**Comment by diox** [comment]
Could we backfill the data in bigquery maybe ? Or have a special table with the total for each add-on without taking telemetry data into account ? I'm concerned about the fact that if we change the cron to just increment day by day, it becomes harder to fix any problems like a missing day or something.

**Comment by willdurand** [comment]
> Could we backfill the data in bigquery maybe ?

All other usage and download stats features should be fine with only 365 days of data, which is interesting because we could control the costs over time. So `addon.total_downloads` is kinda special here and it would be a good idea to find a solution that does not force us to keep data forever since 2006.

> Or have a special table with the total for each add-on without taking telemetry data into account ?

Yeah, I like the idea. We'd need to keep data in BQ forever, though.

> I'm concerned about the fact that if we change the cron to just increment day by day, it becomes harder to fix any problems like a missing day or something.

Could we have a date field storing the last update of `total_downloads`?

**Comment by diox** [comment]
> Yeah, I like the idea. We'd need to keep data in BQ forever, though.

Or in MySQL on our side somewhere, doesn't matter. But yes, it'd need to stay there forever - and the trick would be, if we don't want to keep more than 365 days of data, to update the data from time to time.

> Could we have a date field storing the last update of `total_downloads`?

That seems more fragile: even if you know the last update, you wouldn't be able to re-compute the data if you realize afterwards a single day is problematic, for instance.

**Comment by willdurand** [comment]
@jvillalobos do we actually need to store the total downloads of add-ons? I know we're doing it right now but it's not very often exposed. I see it somewhere in the reviewer tools and in the stats overview. In both places, we could maybe use the weekly downloads instead? WDYT?

**Comment by jvillalobos** [comment]
I think we can drop it, yes. It's mostly a very large number people can use to brag, but as long as we notify people that the change is coming they can figure out a way to compute it themselves.
