### ISSUE TITLE
Remove everything related to `DownloadCount`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15032]
Once we enable the new download stats for everyone, we can remove all the code related to the `DownloadCount` model as well as the ES indexer, cron tasks, etc. This might need more than one issue but this is the starting point (or meta issue).

For QA: there should be no visible impact on the stats.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me. 
Verified on dev - FF81(Win10).
