### ISSUE TITLE
Use BigQuery in `weekly_downloads()` cron task

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15034]
Let's update the `weekly_downloads()` cron task to use BigQuery. We could use a waffle switch to enable/disable the use of BigQuery and we'll remove it once we are confident enough.

**Comment by ioanarusiczki** [comment]
@willdurand If this requires qa, let me know.

**Comment by willdurand** [comment]
@ioanarusiczki yes, we can enable the waffle and run the cron task? This should update the `weekly_downloads` of each add-on (although most will see their value set to `0`)

**Comment by ioanarusiczki** [comment]
@willdurand 
Weekly downloads field is `0` in rev tools and admin tools because it's been `0` for each day since July 21st.  
Is that going to be updated in the future weeks?
