### ISSUE TITLE
Content Review Need Info broken after July 23 push 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#15048]
Filing this on behalf of B.J., who reported that after the July 23 push he can no longer send a need info request. 

@bjherbison, can you add more details and/or include a screenshot?

**Comment by bjherbison** [comment]
![image](https://user-images.githubusercontent.com/4101902/88365139-19f9c380-cd53-11ea-8868-c55d9bd212b8.png)
Based on the comment for https://github.com/mozilla/addons-server/pull/14968 the change was intentional:
> This removes the ability to have an info request with a deadline, and instead makes it possible to delay review rejections when using the reject multiple versions action.

**Comment by diox** [comment]
Yes, that is expected, as delayed review rejections replaces the need info deadline feature. You can still make inquiries by simply submitting a reply.

**Comment by bjherbison** [comment]
The problem with "simply submitting a reply" is that the add-on is still in the list of add-ons needing content review without a visual indication that a request is pending. That makes the job of content reviewing much harder.
