### ISSUE TITLE
Replace "Addon" with `id` in the warning message generated in promoted model

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15057]
From https://github.com/mozilla/addons-server/issues/14861#issuecomment-662554152

STR:
1.  Add an add-on to the list of promoted addons - in the admin model 
2. Try to add it again
3. Observe the message

Expected result:
Promoted addon with this id already exists.

Actual result:
Promoted addon with this Addon already exists.

Notes:
Reproducible on dev with FF78(Win10).

**Comment by bhushan-borole** [comment]
Hello @ioanarusiczki.
I would like to work on this issue.

**Comment by eviljeff** [comment]
Although it reads a little weirdly, it's correct - there does already exist a PromotedAddon instance with the chosen Addon.  Django admin has prettyfied "PromotedAddon" to "Promoted addon", that's all.  Given it will involve delving into the django admin internals for no actual benefit, I'm wontfixing.

**Comment by bhushan-borole** [comment]
> Although it reads a little weirdly, it's correct - there does already exist a PromotedAddon instance with the chosen Addon. Django admin has prettyfied "PromotedAddon" to "Promoted addon", that's all. Given it will involve delving into the django admin internals for no actual benefit, I'm wontfixing.

Oh Okay, No worries!
