### ISSUE TITLE
Drop obsolete lightweight themes update endpoint

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15059]
The ` /<locale>/themes/update-check/` endpoint (`services/theme_update.py`) is no longer necessary. We may want to keep the `MigratedLWT` model a little longer, but we can drop the code serving the updates.

**Comment by diox** [comment]
@bqbn we'll want to drop the associated nginx config as well from versioncheck.

**Comment by ioanarusiczki** [comment]
@diox I believe I should check that themes version updates work as expected in about:addons ?

**Comment by diox** [comment]
Nothing to check really as this was the endpoint for lightweight themes, which should have been migrated a long time ago.

**Comment by diox** [comment]
**Edit:** actually just to be safe... you can check that an update for a static theme works. It shouldn't have been affected at all.

**Comment by ioanarusiczki** [comment]
@diox Doulbe check - the update service works for me on dev and stage. Verified with FF78 unbranded - Win10
