### ISSUE TITLE
Hide "about external sources" when (bigquery) waffle flag is active

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15063]
While we're waiting for new content for https://github.com/mozilla/addons-server/issues/15013, let's hide the "about external sources" link/popup in the "By source" page. Other "By [XYZ]" pages don't have that so it will be more consistent.

**Comment by ioanarusiczki** [comment]
@willdurand "About external sources" URL is not available on By Source page or any other download stats page on dev - FF78(Win10).
