### ISSUE TITLE
'Unknown client' error when trying to log into admin tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15061]
Prerequisites: user is logged out from Admin tools

### Describe the problem and steps to reproduce it:
1. Open https://addons-internal.dev.mozaws.net/en-US/admin/models/ with an admin account 
2. Try to log in

### What happened?
You receive an 'Unknown client' error as soon as you are redirected to the FxA log in page.
From the console: `https://oauth.stage.mozaws.net/v1/client/b8b08a562fb83f37` is returning a 400

### What did you expect to happen?
Log in should be possible

### Anything else we should know?
@diox could this be caused by the transition of our -dev server to the FxA staging environment? I'm reproducing this only on -dev. 

![image](https://user-images.githubusercontent.com/31961530/88402972-849f1380-cdd4-11ea-9ca5-e355fae4582f.png)

**Comment by diox** [comment]
Yes. Looks like we need another client added for the internal admin instance.

**Comment by diox** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1655416 to take care of this. Once the credentials are created on FxA staging I'll ask ops to configure the new secret for it in the internal admin instance environment.

**Comment by diox** [comment]
New credentials have been created but it looks like the admin instance is using the wrong secret, we're debugging this in the bug linked above.

**Comment by diox** [comment]
Looks ok now. Maybe it just needed a re-deploy.

**Comment by AlexandraMoga** [comment]
I'm able to log in to Admin tools now.
