### ISSUE TITLE
Update `extract_permissions` to use for backfilling optional_permissions

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#15062]
This is a follow-up to https://github.com/mozilla/addons-server/pull/15047.

The existing `extract_permissions` command should be updated to be used to backfill optional permissions. It no longer needs to be able to deal with required permissions so can be changed to deal with optional permissions only. It was also pointed out that we should "make it filter its queryset to only consider ADDON_EXTENSION type to limit the number of xpis it's going to look at".

**Comment by diox** [comment]
Also modify the queryset to order by pk. That way, we can have a rough idea of when the tasks are completed by looking at the logs, because the task will log the ids and length of the chunk it's processing.

**Comment by bobsilverberg** [comment]
Changed my mind about the priority. We should try to land this along with #15047, but nothing terrible will happen if we don't, as these new permissions are not exposed anywhere.

**Comment by AlexandraMoga** [comment]
I've found an older add-on with `optional_permissions` on stage and I was able to see this field exposed in the addon detail api response - https://addons.allizom.org/api/v4/addons/addon/5890/

I'm marking this issue as verified fixed on stage.
