### ISSUE TITLE
port 9200: Connection refused intermittent

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#15077]
I've seen this a few times on Travis. [This time](https://travis-ci.org/github/mozilla/addons-server/jobs/712253479) was in the ES job, but I'm not sure if that's always been the case.

Console messages:
```
$ if [ $TOXENV == "es" ]; then
      sleep 10;
      curl -v http://localhost:9200/;
  fi
  
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 9200 failed: Connection refused
* Failed to connect to localhost port 9200: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 9200: Connection refused
The command "if [ $TOXENV == "es" ]; then
      sleep 10;
      curl -v http://localhost:9200/;
  fi
  " failed and exited with 7 during .

Your build has been stopped.
```

**Comment by bobsilverberg** [comment]
FYI, I am seeing this quite frequently. I know @diox commented on Matrix that there's not much we can do about this, but is it worth bumping up the sleep time?

**Comment by diox** [comment]
I'd rather find a proper solution to this - there has to be a better way. IMHO the other intermittent ES failures are more important to fix though.
