### ISSUE TITLE
Display issues after browser resize

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1509]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Resize the browser (under 1000px)
3. Restore the browser to its full dimensions 

Expected results:
There are no display or layout issues.

Actual results:
There is a white padding on the right side of the page (can be seen only after scrolling horizontally). 

Notes/Issues:
The white padding disappears after maximizing the browser back to its full dimensions.
Issue is also reproducing using Chrome or Nightly.
Verified on FF43(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Please see the screencast: http://screencast.com/t/y7G0VNR6wL57

**Comment by andymckay** [comment]
Given the redesigns that are coming for all this, calling this a "wont fix".

**Comment by ValentinaPC** [comment]
Mark this verified-fixed based on #2152
