### ISSUE TITLE
Errors from the extract_optional_permissions command

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#15090]
When running this command on stage, there are a number of errors.

There are a large number like these:

```
"Failed to extract: 1095759, error: ['The add-on ID in your manifest.json or install.rdf ({a42eb16c-2fab-4c06-b1f3-5f15adebb0e3}) does not match the ID of your add-on on AMO (guid-reused-by-pk-1004426)']"
"Failed to extract: 1095758, error: ['The add-on ID in your manifest.json or install.rdf ({a42eb16c-2fab-4c06-b1f3-5f15adebb0e3}) does not match the ID of your add-on on AMO (guid-reused-by-pk-1004425)']"
"Failed to extract: 1096004, error: ['The add-on ID in your manifest.json or install.rdf (first-reused@guid) does not match the ID of your add-on on AMO (guid-reused-by-pk-1004544)']"
"Failed to extract: 1095319, error: ['The add-on ID in your manifest.json or install.rdf (borderify@example01.com) does not match the ID of your add-on on AMO (guid-reused-by-pk-1004067)']"
"Failed to extract: 1094913, error: ['The add-on ID in your manifest.json or install.rdf (mirunatest@mail.com) does not match the ID of your add-on on AMO (guid-reused-by-pk-1003720)']"
 "Failed to extract: 328871, error: ['The add-on ID in your manifest.json or install.rdf (will@drnd.me) does not match the ID of your add-on on AMO ({2aaafe41-ec16-4212-852a-a9c20126c8a6})']"
"Failed to extract: 327413, error: ['The add-on ID in your manifest.json or install.rdf (1addon@id.me) does not match the ID of your add-on on AMO (guid-reused-by-pk-620540)']"
"Failed to extract: 248453, error: ['The add-on ID in your manifest.json or install.rdf (addononetab@example.com) does not match the ID of your add-on on AMO (addononetab123@example.com)']"
 "Failed to extract: 247985, error: ['The add-on ID in your manifest.json or install.rdf (j8d0-fgh-amckay-32@jetpack) does not match the ID of your add-on on AMO (j8d0-fgh-krupa-32@jetpack)']"
```

There are also a few like these:

```
Failed to extract: 1095367, error: ['You cannot submit this type of add-on']
Failed to extract: 706480, error: ['You cannot submit this type of add-on']
```

And a few like these:

```
Failed to extract: 319751, error: ['Lowest supported "strict_min_version" is 42.0.']
Failed to extract: 319711, error: ['Lowest supported "strict_min_version" is 42.0.']
```

I've already discussed the first set with @diox, and I'll record some findings in a comment below. I haven't looked into the second or third error yet.

**Comment by bobsilverberg** [comment]
The second error, "You cannot submit this type of add-on", is coming from https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L1070-L1072, which is checking to see if the current user is allowed to submit an experiment. This is important when processing a submission, but in this case I don't think we need to exclude the add-on from the extraction process.

@diox Do you think this is something we need to address, and alter the code to allow add-ons being caught by this to be extracted?

**Comment by bobsilverberg** [comment]
The third error, "Lowest supported "strict_min_version" is 42.0.", is coming from https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L480-L487, which validates that if a minimum strict version is specified, it needs to be higher than the version when Firefox started supporting WebExtensions.

It seems to me that we are okay excluding these from the extract process as they would be invalid anyway.

**Comment by bobsilverberg** [comment]
Regarding the first error, checking the status of each of the add-ons referenced by the guids in the error message, I found the following:

- guid-reused-by-pk-1004426: Incomplete
- guid-reused-by-pk-1004425: Incomplete
- guid-reused-by-pk-1004544: Incomplete
- guid-reused-by-pk-1004067: Incomplete
- guid-reused-by-pk-1003720: Incomplete
- {2aaafe41-ec16-4212-852a-a9c20126c8a6}: Not found
- guid-reused-by-pk-620540: Incomplete
- addononetab123@example.com: Not found
- j8d0-fgh-krupa-32@jetpack: Not found

I used the AMO Admin to look these up, and I'm not sure why some are not found. The message indicates that the guid exists on AMO, but maybe I'm looking in the wrong place?

**Comment by diox** [comment]
> The second error, "You cannot submit this type of add-on", is coming from https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L1070-L1072, which is checking to see if the current user is allowed to submit an experiment. This is important when processing a submission, but in this case I don't think we need to exclude the add-on from the extraction process.
>
> @diox Do you think this is something we need to address, and alter the code to allow add-ons being caught by this to be extracted?

I would say we can ignore those - there won't be many of them anyway. Same for the ones with a low `strict_min_version`.

If we wanted to be fancy we could pass a different user to `parse_xpi`, or rewrite the extraction code to avoid `parse_xpi` entirely and just open the zip, look at the `manifest.json`, extract the optional permissions from there. But I don't think it's worth it.

**Comment by bobsilverberg** [comment]
The command has been run on prod and I looked through the errors and none of them seemed like anything to particularly worry about. Hence, I am going to close this issue.
