### ISSUE TITLE
Code Manger fails on .ts

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#15101]
Example:
```
https://code.addons.mozilla.org/en-US/compare/764197/versions/2266957...4859565/?allowSlowPages=true&path=scripts%2FInputArea%2FContentEditable.ts
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/3403941/file/scripts/InputArea/ContentEditable.ts#top
```

Code manger displays:
```
Syntax highlighting was disabled for performance
+++ 0--- 0
```

Legacy File Viewer displays:

```
module GhostText.InputArea {
--
  | /**
  | * Implementation for a contenteditable element.
  | *
  | * @licence The MIT License (MIT)
  | * @author Guido Krömer <mail 64 cacodaemon 46 de>
  | */
  | export class ContentEditable implements IInputArea {

.....
```

Same file without compare:
```
https://code.addons.mozilla.org/en-US/browse/764197/versions/4859565/?path=scripts%2FInputArea%2FContentEditable.ts
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/3403941/file/scripts/InputArea/ContentEditable.ts
```

Code manger displays: (nothing, blank)
```
  
```

Legacy File Viewer displays:

```
module GhostText.InputArea {
--
  | /**
  | * Implementation for a contenteditable element.
  | *
  | * @licence The MIT License (MIT)
  | * @author Guido Krömer <mail 64 cacodaemon 46 de>
  | */
  | export class ContentEditable implements IInputArea {

.....
```

**Comment by wagnerand** [comment]
In the API response `hunks` is empty. Also
```
mimetype | "video/MP2T"
mime_category | "binary"
```

**Comment by ioanarusiczki** [comment]
@willdurand I could view the .ts files on dev - FF78(Win10). 
[Browse](https://code.addons-dev.allizom.org/en-US/browse/620063/versions/1691753/?path=scripts%2FInputArea%2FAceCodeEditor.ts) view
[Compare](https://code.addons-dev.allizom.org/en-US/compare/620063/versions/1691753...1691754/?path=scripts%2FInputArea%2FCodeMirror.ts) view

The [API response](https://addons-dev.allizom.org/api/v5/reviewers/addon/620063/versions/1691753/?file_only=true&file=scripts%2FInputArea%2FContentEditable.ts) returns MIME type: text/javascript and so does code-manager as information. 
Also: "mime_category": "text"
