### ISSUE TITLE
optimize queryset in PromotedAddon admin

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15108]
it's currently causing 1 query per PromotedAddon that's recommended!

**Comment by AlexandraMoga** [comment]
@eviljeff the [Promoted Addons](https://addons-internal.dev.mozaws.net/en-US/admin/models/promoted/promotedaddon/) model is down now - a 500 server error is returned.
The model used to work earlier today. Could this patch have caused this issue?

**Comment by eviljeff** [comment]
I just saw it while looking into another problem and logged it as https://github.com/mozilla/addons-server/issues/15132

**Comment by AlexandraMoga** [comment]
I've used the Promoted addons admin tool to add and modify promoted items and tested the filters available in the list view. I didn't see any errors and the functionality as a whole hasn't been broken.

I'm marking this issue as verified fixed on -dev.
