### ISSUE TITLE
approve versions for promotion in reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15123]
We need to generate the PromotedApproval instances for promoted addons when an applicable version is approved via reviewer tools.

@jvillalobos with Strategic promoted add-ons, will only future versions be approved for Strategic (like the other groups where a manual pre-review takes place), or will all versions immediately be seen as "approved" for Strategic once the addon is added to that promotion group? (and not approved once the addon is removed from the Strategic group)

**Comment by eviljeff** [comment]
> On the review page, can the category also be exposed, like we do for recommended at the moment?

**Comment by jvillalobos** [comment]
The only different treatment Strategic add-ons get is that they need to be reviewed by admins, so that should apply to all versions right away. Exposing the category makes sense (for all categories).

**Comment by AlexandraMoga** [comment]
Similar to #14862, I've added an add-on to all the Promoted add-on groups available. Once the new version gets submitted and Approved (pre-reviewed), the promoted add-on admin detail view will display a list with all the versions covered by a particular category. This add-on example covers all categories: https://addons-internal.dev.mozaws.net/en-US/admin/models/promoted/promotedaddon/224/change/

The Promoted Approvals list does not cover unlisted versions and any other version submitted while the add-on is not promoted.

@eviljeff If I understand correctly what was discussed in the previous comments, add-ons belonging to the Strategic group will not display the list of all the promoted versions? [This add-on](https://addons-internal.dev.mozaws.net/en-US/admin/models/promoted/promotedaddon/223/change/) belongs to the Strategic group and has no promoted versions listed on the admin page.

**Comment by eviljeff** [comment]
> @eviljeff If I understand correctly what was discussed in the previous comments, add-ons belonging to the Strategic group will not display the list of all the promoted versions? 

Yes, Strategic promoted add-ons don't have pre-review or specific approval of versions - being in the group is enough to be "approved"
