### ISSUE TITLE
review queue icons for promoted grops

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15124]
> On the queue page, can an icon indicate which promoted category the add-on belongs to?

@wagnerand do we have icons?  mozilla/addons-frontend#9538 has some badges but they'd be too obscure without the text and some of the groups are missing so it's not enough.

**Comment by wagnerand** [comment]
Ah, too bad, I was hoping we could use those. I' not aware of other existing icons.

**Comment by wagnerand** [comment]
We might have to create new ones then.

**Comment by eviljeff** [comment]
Is one icon enough then?  Otherwise it's blocked on someone creating 4 or 5* tiny 16x16 visually distinct and identifiable icons.  *(depending whether you want verified tier 1 and 2 to have different icons)  I can probably create/find/repurpose one.

**Comment by wagnerand** [comment]
These entries should be distinguishable, so we need one icon per category.
Alternatively, we can revise our decision and create separate queues for each category.

**Comment by eviljeff** [comment]
#15506 will close this with a single icon, but with unique css classes so once we have distinct icons it's just a matter of updating the sprite graphic (and the line offsets in the css file).

**Comment by eviljeff** [comment]
my graphical skillz amounted to a "P" for the icon 😛

**Comment by eviljeff** [comment]
follow-up for distinct icons: #15520

**Comment by AlexandraMoga** [comment]
Add-ons belonging to the Recommended, Verified, Sponsored, By Firefox and Spotlight groups will be marked with a dedicated icon in their respective review queues. Until the distinct icons become available, there is a tooltip which indicates the group name. 

![image](https://user-images.githubusercontent.com/31961530/93771971-e76f2880-fc26-11ea-9f17-dbe7c976c3ad.png)

@eviljeff Add-ons from the Strategic group do not have this icon. Was that intentional or an oversight?

**Comment by wagnerand** [comment]
@eviljeff why couldn't we use the same icons that Firefox uses as badges in the add-ons manager?

**Comment by eviljeff** [comment]
> @eviljeff why couldn't we use the same icons that Firefox uses as badges in the add-ons manager?

301 to #15520

**Comment by wagnerand** [comment]
Ah, I didn't see that, thanks!

**Comment by eviljeff** [comment]
> @eviljeff Add-ons from the Strategic group do not have this icon. Was that intentional or an oversight?

That's odd.  There's nothing that particularly filters out any group - do you have a link to a review queue that contains a strategic addon?  (strategic add-ons don't have pre-review so wouldn't necessarily show up in the pre-review extension queue with other promoted addons)

**Comment by AlexandraMoga** [comment]
@eviljeff this is the [review page](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/a-test-for-promoted-addons) for the strategic add-on.

Here is the strategic add-on in the Auto-approved queue:
![image](https://user-images.githubusercontent.com/31961530/93784319-8c90fd80-fc35-11ea-9bdc-d8c918d67057.png)

**Comment by eviljeff** [comment]
@AlexandraMoga oh.  It's not that it's a strategic addon, it's the queue - there are two different implementations of review queues (roughly, the older, pre-review queues; and the newer queues for post-review) and I only added the icons for one of the implementations.  I think the pre-review queues are the main use-case but I'll handle the other queues in a follow-up.
