### ISSUE TITLE
[RevTools] Hide the Optional permissions field if the add-on doesn't have any optional permissions

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15125]
### Describe the problem and steps to reproduce it:
1. Open the review page of an add-on that doesn't have optional permissions - see https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/many-weights-05-09b
2. Check the information present in the Version details

### What happened?
The Optional permissions field with value `None` is displayed
### What did you expect to happen?
The Optional permissions field should be hidden

![image](https://user-images.githubusercontent.com/31961530/89032436-53c35f00-d33d-11ea-9d32-3ad843d4704b.png)

**Comment by bobsilverberg** [comment]
I'm not sure this is an issue. I'm using the exact same code as we use for Permissions. If there are no required permissions we display "Permissions: None", so it made sense to me that we'd do the same for optional permissions.

WDYT @wagnerand and/or @jvillalobos?

**Comment by wagnerand** [comment]
I like the explicitness of the current behavior. I'd wontfix this.
