### ISSUE TITLE
Promoted approval should be empty when a new addon is added to the list

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15130]
From https://github.com/mozilla/addons-server/issues/14859

STR:
1. Add a new add-on to the list of promoted add-ons and observe the Promoted Approval section

Expected result:
There are no entries.

Actual result:
The section shows 8 entries - addons and their versions. 

Reproducible on admin dev - FF78(Win10).

**Comment by eviljeff** [comment]
btw, is this reproducible on stage?  I think it may be bad-data related.

**Comment by AlexandraMoga** [comment]
@eviljeff I can reproduce on stage too, but in this case there is just one unrelated entry under Promoted Approvals.

**Comment by eviljeff** [comment]
So, it's picking up the approvals for versions where there isn't currently a matching `PromotedAddon` instance* (i.e. it's been deleted).  Won't be difficult to fix.

*(it's the  `qs.filter(version__addon__promotedaddon=self.instance)` that's doing `qs.filter(version__addon__promotedaddon=None)` when `self.instance` is `None`.)

**Comment by AlexandraMoga** [comment]
The Promoted approvals section is empty now when a new promoted add-on is created.
For existing promoted add-ons, the section continues to show the versions that have a promoted approval. 

Verified fixed on -dev.
