### ISSUE TITLE
Daily cron jobs causing high CPU usage for database replicas

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#15135]
### Describe the problem and steps to reproduce it:
Starting from 7/17 (after the `2020.07.16` push) the daily cron jobs `update_addon_total_downloads` and `update_addon_weekly_downloads` started to cause high CPU usage on the database replicas. Please see the attached screenshot.

<img width="675" alt="Screen Shot 2020-07-31 at 11 54 37 AM" src="https://user-images.githubusercontent.com/2209111/89068745-bc531180-d326-11ea-8591-8ca0adf6a71b.png">

 
### What happened?

We know this started to happen after the `2020.07.16` push from looking at the monitoring panel.

<img width="677" alt="Screen Shot 2020-07-31 at 12 16 46 PM" src="https://user-images.githubusercontent.com/2209111/89069292-bb6eaf80-d327-11ea-92d9-42c40dc99417.png">

It is not clear what change introduced this kind of behavior.

We also notice that the high CPU usage happens on the replicas only. It is likely because the READ requests are waiting for the replication to finish.

### What did you expect to happen?

The cron jobs should avoid causing CPU usage this high (over 90%) and for this long (close to one hour). This brings risk of instability to the system.

### Anything else we should know?
n/a

**Comment by bqbn** [comment]
One more piece of info, if we separate the run times for `update_addon_total_downloads` and `update_addon_weekly_downloads` by half an hour, the spike would disappear.

Below is the screenshot for running `update_addon_total_downloads` at 12:30 UTC and `update_addon_weekly_downloads` at 13:00 UTC yesterday (Time on the screenshot is in PDT).

<img width="678" alt="Screen Shot 2020-07-31 at 12 46 25 PM" src="https://user-images.githubusercontent.com/2209111/89071792-481b6c80-d32c-11ea-8b3d-7ab7e3d0e186.png">

We'll leave the two jobs running at those times over the weekend and report back whether or not the CPU usage spikes come back or not.

**Comment by diox** [comment]
Note: we're planning to completely remove `total_downloads`. The cron no longer does anything when `use-bigquery-for-download-stats-cron` waffle switch is active.

**Comment by bqbn** [comment]
I assume removing `total_downloads` and activating `use-bigquery-for-download-stats-cron` waffle switch are two separate tasks?

When are they going to happen respectively?

**Comment by diox** [comment]
Should happen in September. In the meantime you can completely remove the `update_addon_total_downloads` cron from the crontab and nobody should notice :)

**Comment by bqbn** [comment]
@diox should we turn `use-bigquery-for-download-stats-cron` on and remove the `update_addon_total_downloads` cron now, or wait till September?

The `use-bigquery-for-download-stats-cron` is currently create but set to `off`.

```
$ ./manage.py waffle_switch -l 2>/dev/null |egrep use-bigquery-for-download-stats-cron
use-bigquery-for-download-stats-cron: off
```

**Comment by diox** [comment]
We're not ready to turn it on yet (see https://github.com/orgs/mozilla/projects/137 for an idea of what's missing). Our plan was to remove the `total_downloads` later, but if the cron is problematic today, we can remove it in advance, the value is only shown in a couple places and if it doesn't update for a few weeks before we completely remove it it should be fine.

**Comment by bqbn** [comment]
Instead of removing `total_downloads` cron now, we can also delay its run time by 25 minutes to 13:00 UTC. We've been manually doing that for the past a couple of weeks. What do you think?

In either case, before we reach the goals in https://github.com/orgs/mozilla/projects/137, we need a way to work around the high database CPU usage issue.

**Comment by diox** [comment]
Either works for me.
