### ISSUE TITLE
Allow fallback to Addon.summary for all addon types for PrimaryHeroShelf

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15134]
We currently only fall back to the addon.summary for extensions, so in the absence of a defined description for the primary hero shelf, it returns `""`.  It doesn't really make sense any longer so we'll remove that condition.

**Comment by ioanarusiczki** [comment]
@eviljeff I removed text from primary hero description field, even from `summary` for all add-on types. There are no visual issues. 

An example: 
![testing description](https://user-images.githubusercontent.com/33448286/91534157-b9454400-e919-11ea-87c2-08f7c874d2b4.png)

Verified on dev - FF79(Win10).

**Comment by eviljeff** [comment]
@ioanarusiczki your screenshot seems to show the opposite! of what the issue was trying to solve.  It doesn't work?  Addon summaries aren't shown in the hero shelves?

**Comment by ioanarusiczki** [comment]
@eviljeff The example above is when there is no text in both fileds: description or summary. In case I have a summary - that is displayed. In case I have the description then that will be available on frontend.
