### ISSUE TITLE
promotedaddon changelist raises when one of the addons doesn't have a current_version

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15132]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/9292307/

**Comment by AlexandraMoga** [comment]
I've added an [add-on](https://addons-internal.dev.mozaws.net/en-US/admin/models/promoted/promotedaddon/225/change/) with no `current_version` to  Promoted addons and the tool is loaded without errors.

I'm marking this issue as verified fixed on -dev.
