### ISSUE TITLE
Use Prettier for JS files

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15148]
We'd like to experiment with code formatters like Black (https://github.com/mozilla/addons-server/issues/8617) but it's tricky to setup given that most of the codebase is python. Let's start small with Prettier for JS files first. We could probably use Prettier for other files in the future (like CSS).

It'd be great to use Prettier to have a uniform code style, without actually having to check code style during reviews. It works great on all addons/* frontend/js projects, so let's use the same config here, too.

For QA: this impacts the entire site but things shouldn't break. JS is used in may different places and I cannot list them all, but doing a tour of the website like an admin or a developer would do should be enough.

**Comment by AlexandraMoga** [comment]
I've tested the Statistics page, Developer hub, Reviewer tools and Admin tools on -dev and stage and I haven't run into functional or JS related issues anymore.
