### ISSUE TITLE
Add migration to remove info request related fields 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15153]
The following push after https://github.com/mozilla/addons-server/issues/14899 goes to production, we should be able to add a migration to remove the  `notified_about_expiring_info_request` and `pending_info_request` from `AddonReviewerFlags`, as the database column should have been set to `nullable` and the fields removed from the models already.

**Comment by Sparsh-Bansal** [comment]
@diox I have generated the migration file , Should I land a PR ?

**Comment by diox** [comment]
You can, yes.

**Comment by Sparsh-Bansal** [comment]
I noticed , you had already pushed the migrations https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/migrations/0025_auto_20201028_1647.py related to this issue.

**Comment by diox** [comment]
Ah, hadn't noticed that, sorry. This issue should be closed.

Duplicate of https://github.com/mozilla/addons-server/issues/15853
