### ISSUE TITLE
Scanner rule match exclusion should exclude matches if the excluded rule is the only match

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15154]
### Describe the problem and steps to reproduce it:

Assume a scanner matches rules A and B in add-on file. When an admin excludes showing matches for rule A, the page should still show matches for a file that matches both A and B.

### What happened?

The file is excluded from the view.

### What did you expect to happen?

The file should be included, since it matches another rule as well.

**Comment by AlexandraMoga** [comment]
This was verified on -dev and stage with several rules and add-ons that were targeted by those rules.

Test method:
- Create an an add-on that matches rule A.
- Create another add-on that matches rules A and B.
- Open the scanner results and verify that both those add-ons are included in the list
- Use the exclude rule filter to hide results that matched rule A
- Verify that the add-on matching only rule A is not in the list, while the add-on matching rules A and B can still be found in the results list.
