### ISSUE TITLE
Stats are not loading

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15173]
### Describe the problem and steps to reproduce it:
1. Open the Statistics page for an add-on that with stats - see https://addons-dev.allizom.org/en-US/firefox/addon/some-addon/statistics/downloads/

### What happened?
Several page elements are not loading

### What did you expect to happen?
Stats are loaded

### Anything else we should know?
I have the following errors in the console:

![image](https://user-images.githubusercontent.com/31961530/89314217-0834ec00-d682-11ea-9227-0220d82fd8e1.png)

@willdurand could this be a regression from #15129 ?

**Comment by willdurand** [comment]
This is still a major problem.

**Comment by willdurand** [comment]
Looks like it was actually fixed on -dev and cherry-picking the patch on -stage worked too

**Comment by AlexandraMoga** [comment]
I've monitored the stats pages since yesterday and I could not reproduce the JS errors anymore.

I'm marking this issue as verified fixed on stage.
