### ISSUE TITLE
Remove legacy file viewer

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15171]
The legacy file viewer is no longer used. Let's remove it.

**Comment by wagnerand** [comment]
QA: This is quite a large patch. Please test general stuff like file uploading and downloading (from public pages, devhub, reviewer tools, admin tools). If you can think of other file-handling features, it would be good to test these as well.

**Comment by AlexandraMoga** [comment]
I've tested the following actions that involve files handling:
- add-on uploads
- installing an add-on from its public listing page
- file downloads from dev hub (including Approved or Disabled files)
- file downloads from reviewer tools and admin tools  (including Approved, Disabled or Deleted files)
- individual file downloading from code-manager (including Approved, Disabled or Deleted files)

I haven't noticed any issues with any of the above mentioned actions. 

These actions will be tested again on stage once the code lands there.
