### ISSUE TITLE
Delay rejection deadline email is sent for add-ons with a one day grace period from start

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15170]
Follow up for #14814 

### Describe the problem and steps to reproduce it:
1. With an admin reviewer, submit a delayed rejection for an add-on version - make sure the grace period is set to 1 day
2. Open the Fake mail tool and look for the initial delayed rejection email sent to the developer
3. Wait for ~1 hour and verify the Fake mail entries again

### What happened?
In addition to the [initial delay email](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/94709/change/) there is a new identical email which serves as [deadline reminder](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/94710/change/)

### What did you expect to happen?
If the delay rejection grace period is set to 1 day from start, there should be no deadline reminder sent

### Anything else we should know?
Add-on used in this example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/email-expired-delayed-reject

**Comment by diox** [comment]
I don't think this would happen / be annoying enough to fix. Thoughts @jvillalobos ? Ultimately I assume admins setting a 1 day grace period is an unlikely scenario...

**Comment by jvillalobos** [comment]
Realistically, deadlines will be at least a few days long.
