### ISSUE TITLE
Don't set Display Name field to "Anonymous" for new users

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1518]
## steps to reproduce:
1. Create a brand new AMO account using FxA
2. Look at the Display Name for that account

## observed behavior:
The Display Name is set to "Anonymous". Since this field is not a required field, we will have many new accounts with "Anonymous" as their display name which is not great for reviews. Instead, let us used the email id to pre-fill this field with the option for the user to edit it.

 example: If the user's email id is agrajag+42@gmail.com, then the pre-filled display name would be "agrajag+42"

**Comment by andymckay** [comment]
We were hoping to use the display name from FxA which depends upon mozilla/fxa-content-server#2477

The email id leaks the first half of a users email and doesn't meet the username rules on AMO.

**Comment by mstriemer** [comment]
We should add a message at the top of the account settings page when the account is created telling the user to set their username and/or display name. Don't mention that it's "optional". Something like "Please set your username and display name to complete the registration process."
