### ISSUE TITLE
Themes as promoted addons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15188]
Currently, themes are able to be recommended by being in a special collection too.  (The logic is check if the theme is recommended normally, if not check it's in the collection).  This code remains for `Addon.is_recommended` but when the frontend switches to relying on promoted classes exposed via the API the logic will be bypassed so something needs to be re-implemented. 

@jvillalobos should the special recommended theme collection remain (an additional) way of a theme being recommended?  And if so I assume it'll be just for recommended group?  There's nothing special about themes now so they can otherwise be a PromotedAddon like any other type of addon.

**Comment by jvillalobos** [comment]
IIRC, we use the collection because it's maintained by theme designers, so we should keep that working as it does now, and only for the Recommended category. /cc @caitmuenster

**Comment by eviljeff** [comment]
Thinking about this, it needs to be done as close to the API level as possible, so it needs to be done after #14923 in the `Addon.promoted` @cached_property the PR adds.

**Comment by bobsilverberg** [comment]
This was fixed via https://github.com/mozilla/addons-server/pull/15222

**Comment by AlexandraMoga** [comment]
Recommended themes are returned by the detail and search APIs under the new `promoted` property with category `recommended`.
Example: https://addons.allizom.org/api/v4/addons/addon/theme-for-reelease
