### ISSUE TITLE
expose promotion status in reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15197]
We expose that an addon is recommended (well, in the recommended group) in reviewer tools.  We should also indicate membership of _other_ promoted groups too.

**Comment by AlexandraMoga** [comment]
Promoted add-ons, from each of the promoted groups, will be marked accordingly on the add-on review page:

[1] - simple message
![image](https://user-images.githubusercontent.com/31961530/90404660-5fd44e00-e0ab-11ea-82ec-fbc471c9e233.png)


[2] - message + permissions restriction
![image](https://user-images.githubusercontent.com/31961530/90404673-64006b80-e0ab-11ea-940a-8b74226d4cd0.png)

I've filed #15316 as a follow-up.
