### ISSUE TITLE
expose promoted groups in devhub

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15196]
We show "Approved and recommended" for recommended addons (once approved) in developer hub.  I guess we want to show the same for other promoted groups?  

@jvillalobos to confirm which other group memberships (if any) should be exposed in devhub to developers.

**Comment by jvillalobos** [comment]
Yes, we should have:

- Approved and Recommended
- Approved and Verified
- Approved and Sponsored
- Approved and By Firefox

The other groups shouldn't be exposed.

**Comment by AlexandraMoga** [comment]
The promoted category for add-ons belonging to the Recommended, Sponsored (Verified - Tier 1), Verified (Verified - Tier 2) and By Firefox (Line) groups is exposed in Developer Hub:

[1] - Dev hub homepage
![image](https://user-images.githubusercontent.com/31961530/90402662-72995380-e0a8-11ea-8645-6eb3263c692b.png)


[2] - Edit product page
![image](https://user-images.githubusercontent.com/31961530/90402519-3e259780-e0a8-11ea-8f61-3c30cb01d04f.png)


[3] - Manage submissions page
![image](https://user-images.githubusercontent.com/31961530/90402724-89d84100-e0a8-11ea-86e6-506aefabe197.png)



The Disable/Delete version restriction message was also updated to with the additional promoted categories: 
![image](https://user-images.githubusercontent.com/31961530/90402495-3534c600-e0a8-11ea-8a43-419e5dd99c82.png)


Other promotion groups (Spotlight and Strategic) are not being exposed.
