### ISSUE TITLE
re-organise other promoted-type admin tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15194]
We show all the shelf related admin tools under /discovery, but the PrimaryHero shelves have moved to /promoted, inside PromotedAddon, so it will be cleaner to move them all in the same place,

**Comment by eviljeff** [comment]
Actually, in the short term, PromotedAddon is best under discovery, until we have a chance to tidy up and move all the tests/admin code to the new (correct) location

**Comment by AlexandraMoga** [comment]
The Promoted addons model is located under https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/ and the tool continues to work as before.
