### ISSUE TITLE
Set `null=False` to `AddonGUID.hashed_guid` once it lives in production

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15192]
We added a new field to the `AddonGUID` model in https://github.com/mozilla/addons-server/issues/15189. Once this field exists in production and we run a backfill script, we'll want to change the `null` attribute to make this field non-nullable.

**Comment by ioanarusiczki** [comment]
@willdurand Please add some STR for qa.
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki added, sorry

**Comment by AlexandraMoga** [comment]
I've submitted listed and unlisted extensions, themes, language tools and I didn't find any issues.

I'm marking this as verified fixed on stage.
