### ISSUE TITLE
Addon signing error: "Received an empty response from the server; status: 0"

### ISSUE THREAD

**Issue by gigelu** [mozilla/addons-server#1519]
I'm trying to sign an addon for private use and I get this error after uploading the file:

![amo](https://cloud.githubusercontent.com/assets/270697/12575429/097497ca-c415-11e5-9f66-03cf23e07e92.png)

The addon is a modified version of JSView which is discontinued.

I've tried now to submit the addon with Chromium and the status is 504.

Here is the file:

[{cf15270e-cf08-4def-b4ea-6a5ac23f3bca}.zip](https://github.com/mozilla/olympia/files/104609/cf15270e-cf08-4def-b4ea-6a5ac23f3bca.zip)

**Comment by jvillalobos** [comment]
I tried validating the add-on on prod and dev:

https://addons.mozilla.org/en-US/developers/addon/validate -> stuck at "validating", looks like it will timeout.

https://addons-dev.allizom.org/en-US/developers/addon/validate -> finishes correctly, almost immediately.

**Comment by jvillalobos** [comment]
A second try on prod yields the expected result, so maybe it's a temporary problem.

@gigelu can you try again and let us know if the problem is still occurring?

**Comment by gigelu** [comment]
Still the same for me on the first link, it timeouts after ~4 minutes.

**Comment by gigelu** [comment]
I tried posting directly with the API and I get the same results, it timeouts after 1 minute with error 504 `GATEWAY_TIMEOUT`

**Comment by gigelu** [comment]
Any news on this?

**Comment by EnTeQuAk** [comment]
We fixed quite a few things in January and more recently, does this issue still occur to you?

**Comment by gigelu** [comment]
Hello

It's fixed now, I just signed it and it's all OK.

Thank you.

**Comment by EnTeQuAk** [comment]
Awesome, thanks for the feedback!

**Comment by mori-goh** [comment]
![Capture](https://user-images.githubusercontent.com/71404994/108107840-c6b3dd80-70b5-11eb-8fee-13c6ad70f0e9.PNG)
I am trying to submit an add on but it's showing an error. I have tested the zip file using addons-linter it is not showing any error only warnings are shown.
