### ISSUE TITLE
Adjust account deletion email to mention FxA deletion

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#15201]
Since Firefox Account deletion can trigger an AMO account deletion, and that in turn can notify the account owner, let's adjust the text to make it less surprising.

I think it should be good enough to update [this line](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/templates/users/emails/user_deleted.ltxt#L3) to: 

> You’re receiving this message because your user account {{ name }} on {{ site_url }} has been deleted. This could have been done automatically if you recently deleted your Firefox Account.

**Comment by jvillalobos** [comment]
Mentor: @eviljeff

**Comment by AlexandraMoga** [comment]
The new  email copy is sent when an account is deleted:

```
Hello,

You’re receiving this message because your user account <display_name> on https://addons-dev.allizom.org has been deleted. This could have been done automatically if you recently deleted your Firefox Account.

If you didn’t do this or believe an unauthorized person has accessed your account, please reply to this email. Otherwise, there’s no further action to take.

Regards,

The Firefox Add-ons Team
```
