### ISSUE TITLE
Update shelf model/form

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#15202]
Supports #14871

1. As the shelf types categories, extension, recommendations, search, and themes all use the `search` endpoint, revise `shelf_type` to  `endpoint`. Endpoints to only include `collections` and `search`.
2. Fix `search` endpoint to raise a validation error if `criteria` is incorrectly set (e.g., `recommended=true` - missing `?`)
3. Fix `collections` endpoint
  - Successly saves when all fields are correct (`criteria` set to a collection slug e.g., `password-managers`)
  - Raise validation error if `criteria` is incorrectly set (e.g, `passwordmanager`)

**Comment by AlexandraMoga** [comment]
I think I covered this issue when verifying #14952, so the test results added in https://github.com/mozilla/addons-server/issues/14952#issuecomment-673418777 are also applying to this issue.
