### ISSUE TITLE
Update "Flagged for human review" queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15200]
The "Flagged for human review" queue should be updated to show add-ons the following, and the following only:

* Any unlisted version that has the `needs_human_review_by_mad` flag
* If listed the latest auto-approved version (if it has the `needs_human_review_by_mad` flag). (This should be `addon.current_version` if I am not mistaken?) It can also be generally just the latest approved version, but in practice, the flag is set before a human looks at it, and cleared when a human has reviewed it.

/cc @willdurand

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and have the following results:

- The Flagged for human review queue will include the following add-ons/versions:
  - all unlisted versions for pure unlisted add-ons or add-ons with mixed listed and unlisted versions - [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/b15b41765b1e4ea8955b)
  - listed add-ons with their current (latest approved) versions flagged by mad - [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/new-version-while-pndrj)
- The Flagged for human review queue will _not_ include the following add-ons/versions:
  - add-ons with their current listed version not flagged by mad - [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/ghosttext)

@wagnerand when an add-on has mixed listed and unlisted versions, the rule about showing an entry for listed versions _only_ if the current version has been flagged by mad doesn't seem to apply. 
For this add-on [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/unlisted-example-08-06), the latest approved version is not flagged by mad, but you'll be able to see this add-on in the [mad queue](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/mad) with an entry for 'Listed version'.

**Comment by wagnerand** [comment]
Thanks, I found the culprit.

**Comment by AlexandraMoga** [comment]
I've re-verified the [mad queue](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/mad) on -dev and I can no longer see an entry for 'Listed version' for this [addon example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/unlisted-example-08-06) with mixed listed and unlisted versions. All the other test results are still valid. 

This issue can be marked as verified fixed on -dev.
