### ISSUE TITLE
Remove `local-statistics-processing` waffle switch

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15216]
We don't need this `local-statistics-processing` waffle switch anymore so let's remove it.

**Comment by sarathsomana** [comment]
Hi @willdurand , Can I work on this ?

**Comment by willdurand** [comment]
I think so yeah

**Comment by AlexandraMoga** [comment]
Stats are loaded both on -dev and stage, so there were no regressions from this waffle switch removal. 

I'm marking this issue as verified fixed.
