### ISSUE TITLE
Update the documentation for "How are downloads counted?"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15215]
The "Downloads" stats page has the following link/modal:

<img width="811" alt="Screen Shot 2020-08-06 at 14 59 36" src="https://user-images.githubusercontent.com/217628/89535041-27548a80-d7f6-11ea-8307-f8cb64bab43c.png">

We currently hide it in the new stats page.

@jvillalobos What should we do? Keep it and therefore update its content or remove it?

**Comment by jvillalobos** [comment]
Let's remove it.

**Comment by willdurand** [comment]
Fixed by #15214

**Comment by AlexandraMoga** [comment]
The link that opened the Downloads count information modal has been removed on -dev:

[Before - stage]
![image](https://user-images.githubusercontent.com/31961530/89659181-2c8a0600-d8d8-11ea-9650-a9a77a5af624.png)

[After - dev]
![image](https://user-images.githubusercontent.com/31961530/89659191-30b62380-d8d8-11ea-9b51-67e027b69d13.png)
