### ISSUE TITLE
Use `hashed_guid`/`hashed_addon_id` for the download stats

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15213]
BQ will expose a `hashed_addon_id` column instead of the currently exposed `addon_id`. We introduced a `hashed_guid` field on the `AddonGUID` model in #15189. This issue is about using hashes to query the download stats (in `stats/utils.py`) as well as updating the CRON job for the weekly downloads.

For QA: this issue should make the new download stats work again in -dev and it would be great to have extensive verification so that we can enable the new download stats in prod by the end of this month (September 2020).

**Comment by ioanarusiczki** [comment]
@willdurand I found 4 testing samples where I can see daily downloads and the weekly downloads in the overview. 
https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/?last=7
https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/?last=30
https://addons-dev.allizom.org/en-US/firefox/addon/private-relay/statistics/?last=90

The forth one below is the one I deleted for https://github.com/mozilla/addons-server/issues/15189 and resubmitted. There was 0 weekly downloads but now it's been updated, ADU is still 0 but I think that will be updated too after a cron task run. (i'll re-check)
https://addons-dev.allizom.org/en-US/firefox/addon/statistics-reloaded/statistics/?last=365

**Comment by ioanarusiczki** [comment]
@willdurand What is the difference between the weekly downloads and the last 7 days? Shouldn't they show the same numbers?
It's similar for ADU too.

An example, https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/?last=7

![7 days](https://user-images.githubusercontent.com/33448286/93177752-f132f080-f73b-11ea-8fc4-2b7af4cf898a.png)

**Comment by ioanarusiczki** [comment]
@willdurand the [PRD](https://docs.google.com/document/d/1TuMqhEWNlCNDQRgqFywpJvDHTTNjnAq7-3BAXtoFLQ4/edit) says that the tracking is not desired for the unlisted addons. [The stats](https://addons-dev.allizom.org/en-US/firefox/addon/a636b7e141c14ccca7d4/statistics/?last=7) for unlisted add-ons also display the Downloads and it's sub-categories. Is that expected? (because it will never provide any information)

**Comment by willdurand** [comment]
> What is the difference between the weekly downloads and the last 7 days? Shouldn't they show the same numbers?
> It's similar for ADU too

Weekly downloads and ADU are updated once a day using a cron task. For ADU, there is a formula. I think "last 7 days" is the sum of all values for the last 7 days until **now** so this is maybe why there are small differences.

**Comment by willdurand** [comment]
> @willdurand the [PRD](https://docs.google.com/document/d/1TuMqhEWNlCNDQRgqFywpJvDHTTNjnAq7-3BAXtoFLQ4/edit) says that the tracking is not desired for the unlisted addons. [The stats](https://addons-dev.allizom.org/en-US/firefox/addon/a636b7e141c14ccca7d4/statistics/?last=7) for unlisted add-ons also display the Downloads and it's sub-categories. Is that expected? (because it will never provide any information)

Maybe we could hide this section in the future yeah. This isn't super high priority because we won't have data to display and that won't break anything.

**Comment by willdurand** [comment]
@ioanarusiczki I filed #15487

**Comment by ioanarusiczki** [comment]
@willdurand 

- So yes, in the afternoon I checked again the numbers and the weekly downloads is equal with the downloads in the last 7 days. 
ADU still has differences, I did not find equal values for the 2 fields below, a different formula could be causing it.

![in the afternoon](https://user-images.githubusercontent.com/33448286/93306432-87344d00-f808-11ea-9383-60c185aa063d.png)

- For all the samples [above](https://github.com/mozilla/addons-server/issues/15213#issuecomment-691072964) I can see daily data being available for downloads and also for the 4 sub-categories. 
- csv/json reports are available.

- I did not find data for dictionaries on dev (as expected). Lang packs look alright, 2 examples:
https://addons-dev.allizom.org/en-US/firefox/addon/asturianu-language-pack/statistics/?last=7
https://addons-dev.allizom.org/en-US/firefox/addon/czech-cz-language-pack/statistics/?last=30

The sub-categories show only one source/category which is (none). 

- I do see an interesting thing: when I tried generating custom reports, I tried to select some older dates, at one point the calendar's days cannot be selected (I can select from the upper calendar though). I could reproduce it with all the addons except for the lang packs.

![selectable2](https://user-images.githubusercontent.com/33448286/93322370-e8b1e700-f81b-11ea-8d5e-28e24bb2f027.gif)
