### ISSUE TITLE
The xpi file signed value is false (after signing the addon)

### ISSUE THREAD

**Issue by arieljannai** [mozilla/addons-server#1522]
I checked the status of the upload, to see if my addon has already been signed, and got [this](https://gist.github.com/arieljannai/20500b3f0ad86bb8f880#file-status-amo-result-json), or in short:
```json
"active":true,
   "automated_signing":true,
   "url":"https://addons.mozilla.org/api/v3/addons/%%%UPLOADER_MOZILLA_DEV_MAIL%%%/versions/%%%ADDON_VERSION%%%/uploads/%%%UPLOAD_PK%%%/",
   "files":[  
      {  
         "hash":"sha256:HASH_VALUE",
         "signed":false,
         "download_url":"https://addons.mozilla.org/api/v3/file/%%%FILE_ID%%%/my_extension-0.0.1.xpi?src=api"
      }
   ],
   "passed_review":true,
   "pk":"%%%UPLOAD_PK%%%",
   "processed":true,
   "reviewed":true,
   "valid":true,
```

All the values point that the addon was signed, except the `signed` value inside `files`, that is still false.

I asked about it in the `#amo-editors` irc channel, and been told it's a bug :bug:- so I'm opening that issue.

I've also asked about it on SO, Here's the question: http://stackoverflow.com/questions/35015746/signing-a-firefox-add-on-with-mozilla-api-and-download-signed-xpi

**Comment by jvillalobos** [comment]
For reference, [this is the unlisted add-on](https://addons.mozilla.org/en-US/developers/addon/walkme-extension1/edit).

**Comment by arieljannai** [comment]
Is it a bug, or I just don't understand how it works?

**Comment by arieljannai** [comment]
Now it's working for me.
I think the problem was that I had problems in the `install.rdf` file - I had a wrong targetApplication id, which I believe resulted that result.

I'll leave the issue open in case you want to verify it, and I guess that maybe notify about that/fail the sign/etc.
(I'll be happy to know if that was really the problem, or I just had good luck the last time :smile:)

**Comment by arieljannai** [comment]
@jvillalobos Maybe it will be good to just notify it as a suggestion, if you don't have time to implement the checking itself.
Like, if that's false, add a comment field to the result json, with a link to the documentation of install.rdf

**Comment by andymckay** [comment]
Based on the fact that the targetApplication was wrong, closing.
