### ISSUE TITLE
rm unused admin settings|env|es views

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15232]
From https://github.com/mozilla/addons-server/issues/12903#issuecomment-667123326

> are:
> 
>     /admin/elastic/
>     /admin/env/
>     /admin/settings/
> 
> still used? I can't remember ever checking them locally (or on dev/stage)

> I've used all 3 in the past couple months... once each. But generally they are not that useful (ops can give similar info) and we could remove them.

**Comment by AlexandraMoga** [comment]
The above mentioned views are no longer available under the main `/admin/` page. The `/models/` page can still be accessed from the Site Settings and Environment menu.
