### ISSUE TITLE
remove old admin addon manage 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15234]
It was replaced in https://github.com/mozilla/addons-server/issues/8410 over 6 months ago so I think its safe to remove the old one now.

**Comment by AlexandraMoga** [comment]
The `admin/addon/manage` is no longer listed as a tool in admin. There is also no link to this tool from either Dev Hub or Reviewer Tool.

The frontend still has a reference to `admin/addon/manage`  in the links exposed to Admin users on an add-on detail pages. I'll file a follow up on addons-frontend up to remove that link.

**Comment by eviljeff** [comment]
@AlexandraMoga there's a replacement tool at `admin/models/addons/addon/<addon-id>/change/
