### ISSUE TITLE
Code Manager fails on compare

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#15262]
Example:
```
https://code.addons.mozilla.org/en-US/compare/895053/versions/4838262...5044502/?path=background.js
https://code.addons.mozilla.org/en-US/compare/895053/versions/4838262...5044502/?path=options.js
```

Code manger displays:

```
Syntax highlighting was disabled for performance
+++ 0--- 0
```

It works fine if viewed without compare.
```
https://code.addons.mozilla.org/en-US/browse/895053/versions/4838262/?path=background.js
https://code.addons.mozilla.org/en-US/browse/895053/versions/4838262/?path=options.js
```

**Comment by bobsilverberg** [comment]
Looking at the API responses for the compare views, I see:

```
{
  ...
  file: {
    ...
    diff: {
      ...
      hunks: [],
      ...
    }
    ...
  }
  ...
}
```

and `hunks` should contain all of the changes in the diff. So an empty `hunks` explains why we have nothing to show in the compare view.

This doesn't explain why we're getting `[]` returned for `hunks` though. I'll open an issue on addons-server for that.

**Comment by bobsilverberg** [comment]
Oops, I assumed this issue was on `addons-code-manager`, but I see it's already opened on `addons-server`. :-P

**Comment by bobsilverberg** [comment]
The API call which returns `hunks` as `[]` is `https://addons.mozilla.org/api/v5/reviewers/addon/895053/versions/4838262/compare_to/5044502/?file=background.js&lang=en-US`.  Note that comparing an earlier version (e.g., `0.9.7`) does return a valid value for `hunks` (URL is `https://addons.mozilla.org/api/v5/reviewers/addon/895053/versions/2608642/compare_to/5044502/?file=background.js&lang=en-US`).

**Comment by bobsilverberg** [comment]
I'm not sure if this remains an issue or not. @erosman and/or @wagnerand is this something that has been seen in more instances that just the one reported here?

**Comment by erosman** [comment]
I have not noticed it recently.

**Comment by erosman** [comment]
Just now, I noticed something strange.

`https://code.addons.mozilla.org/en-US/browse/2666547/versions/5183213/`
![image](https://user-images.githubusercontent.com/6458876/108111855-8864f100-70aa-11eb-8ea2-a7c5d8f45f84.png)


`https://code.addons.mozilla.org/en-US/compare/2666547/versions/5181960...5183213/`
![image](https://user-images.githubusercontent.com/6458876/108112060-d4b03100-70aa-11eb-8b64-013c90306741.png)


Why does the compare show those files as deleted?
