### ISSUE TITLE
The Admin code review flag is not cleared when an add-on is removed from the Strategic group

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15268]
Follow up for #14864 

### Describe the problem and steps to reproduce it:
1. Add a new add-on to the Strategic promoted group
2. Submit a new version for that add-on
3. Verify that the new version has been marked for admin review, as it is the rule for Strategic add-ons
4. Remove the add-on from the Strategic group (set it as Not Promoted)
5. Submit a new version for this add-on
6. Verify the review status of the last version

### What happened?
The new version is still flagged for admin review because the flag is not cleared automatically when an add-on is removed from the Strategic group. Regular reviewers are still restricted from reviewing the add-on.

### What did you expect to happen?
The admin review flag should be cleared when an add-on is removed from the Strategic group

### Anything else we should know?
Examples: 
former strategic add-on - https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/223/change/
add-on review page - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/shared-developer-this-owner

**Comment by eviljeff** [comment]
does the flag only persist until it's been cleared once?  (after it's been removed from the strategic group)

**Comment by AlexandraMoga** [comment]
Oh, sorry, I noticed now that the add-on used for this test was flagged for admin review before being added to the Strategic group, hence the persisting flag (which was never removed).
