### ISSUE TITLE
add promoted sorting to addons search api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15274]
We can currently sort by recommended status (and it's the default).  We want to expand that to be promoted, which will be largely the same, but also bump the search ranking of some non-recommend promotional add-ons somewhat (https://docs.google.com/spreadsheets/d/1ENbv1CuLDd25Sk0XAwgbWTl9is5rV12OxJD6g1kUi48/edit#gid=1788006942 specifies the Verified Tier 1 group - aka Sponsored - to have a search boost)

**Comment by eviljeff** [comment]
note this isn't strictly blocked by #15272 but that's the simple case for using promoted in ES queries - it'll be easier to implement this once #15272 is done.

**Comment by eviljeff** [comment]
@jvillalobos there are two slightly different features that need to be updated here:
 - one is the relevance sort used for search queries.  Currently we boost recommended by `* 5`.  The PRD mentions that verified tier 1 (sponsored) gets a boost but doesn't specify what - `* 2`? more?  Change the recommended boost?  It's difficult to say what affect that will have (tinkering with boosts can end up with some oddities, [like prioritizing "bl_ock_" or "st_ock_" when you're literally searching for "stock"](https://discourse.mozilla.org/t/amo-search-relevance-ranking/65862))
- the second is the `?sort=recommended,<other-sort>` sorting filter.  This is a combination filter used with non-relevance (non search queries) results to force all recommended add-ons on top of another sort, e.g. `?sort=recommended,users` (the default if no query string, and used on category pages).  What's the plan with how promoted add-ons would be shown in that scenario - would we expect to have _any_ promoted add-on above non-promoted?  A subset of the promoted groups?  Show recommended; then verified tier 1; (then verified tier 2 and so on)?, ending with non-promoted?

**Comment by jvillalobos** [comment]
- Let's keep the Recommended boost as-is and use `* 3` for Sponsored.
- No changes to those other filters for now. Recommended on top and the rest sorted normally.

**Comment by jvillalobos** [comment]
@eviljeff sorry for the last minute change, but we just decided to extend the search boost to both Sponsored _and_ Verified. My previous comment applies to both groups.

**Comment by eviljeff** [comment]
> @eviljeff sorry for the last minute change, but we just decided to extend the search boost to both Sponsored _and_ Verified. My previous comment applies to both groups.

:shakes-fist:

same boost (`* 3`) for both?

**Comment by jvillalobos** [comment]
> same boost (* 3) for both?

Yes, please.

**Comment by jvillalobos** [comment]
@eviljeff So... After further discussion with Amy and others, we've decided to not provide the search boost to Verified and Sponsored add-ons for now. We might in the future, so if there's already work done here maybe we can put it behind a flag?

SORRY

**Comment by ioanarusiczki** [comment]
@eviljeff 

Test results:
- making search queries the recommended addons are visible at the top of the page (as before), so I don't think anything is changed in the behavior.
- I don't think sponsored and verified have a boost while making search queries. Recommended are at the top of the page followed by not promoted addons then one is strategic followed by a theme which is not promoted, then sponsored and so on. 
Example: https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=bubbles%20for%20mozilla

For now:
- `reviewed` is not available yet https://github.com/mozilla/addons-server/issues/15272#issuecomment-685941863
- the frontend is not returning results for requests with promoted filter yet, example: `?promoted=line&app=firefox`. This was added only in the API https://github.com/mozilla/addons-server/issues/15272

An observed issue:
- The request https://addons-dev.allizom.org/api/v5/addons/search/?promoted=recommended&app=android returns 38 addons. But if I look in [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?all=&group_id__exact=1), right now there are 5 addons compatible with Android. Perhaps the changes from https://github.com/mozilla/addons-server/issues/15313 caused the differences?

**Comment by ioanarusiczki** [comment]
@eviljeff I forgot to add yesterday that the Application field from admin does not depend on what the version page from dev hub shows for a version.  
To be more clear -> [Cookie AutoDelete ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/210/change/?_changelist_filters=application_id__exact%3D1%26group_id__exact%3D1) shows `Firefox` Application in admin but the add-on is submitted for [Android](https://addons-dev.allizom.org/en-US/developers/addon/cookie-autodelete54/versions/1691974).

**Comment by eviljeff** [comment]
>     * The request https://addons-dev.allizom.org/api/v5/addons/search/?promoted=recommended&app=android returns 38 addons. But if I look in [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?all=&group_id__exact=1), right now there are 5 addons compatible with Android. Perhaps the changes from #15313 caused the differences?

#15313 updated the promoted groups but should have triggered an ES reindex of those addons too...

**Comment by ioanarusiczki** [comment]
@eviljeff I think it has to do with what I mentioned [above](https://github.com/mozilla/addons-server/issues/15274#issuecomment-689357366) for most of the add-ons the admin shows one platform (firefox) but I see in the search API and dev hub that many have  
"compatibility": {
                    "firefox": {
                        "min": "48.0",
                        "max": "*"
                    },
                    "android": {
                        "min": "48.0",
                        "max": "*"
                    }
                },
AMO stage too. The [promoted ](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/promotedaddon/?application_id__exact=1&group_id__exact=1)list has `Firefox` only but the [search](https://addons.allizom.org/api/v4/addons/search/?promoted=recommended&app=android) or addon detail API returns both platform.

**Comment by eviljeff** [comment]
@ioanarusiczki I think you're talking about two separate things.  One is that the ES index (used in search response) has stale data compared to the database (used in detail response) - I'm addressing that with #15449.  The second is that the promoted application settings are independent of the current version of the addon's application compatibility - a known limitation/feature.

**Comment by ioanarusiczki** [comment]
@eviljeff Thanks, I understand it now. 
Then I can mark this verified on dev - FF80(Win100).
