### ISSUE TITLE
drop `is_recommended` from addon api; shim in v4.

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15271]
We don't need `is_recommended` any longer - `is_promoted` has the same information as recommended addons are now a subset of promoted addons.  Let's remove it from the api and add a shim for the property in api/v4 (it could exist in v3 too, but it was only added after v4 was launched so is undocumented in v3).  Or maybe just drop entirely once addons-frontend has switched over?

Dropping the data from the ES index depends on us replicating the the `recommended` filter and sort, or at least rewriting them to rely on promoted data in the ES index instead.

--edited after https://github.com/mozilla/addons-server/issues/15368 dropped the model property

**Comment by eviljeff** [comment]
blocked by #15272 and #15274 that rely on `is_recommended` in the ES index.

**Comment by eviljeff** [comment]
@bobsilverberg https://github.com/mozilla/addons-frontend/issues/9579 removed references to `is_recommended` in the API, right?  So we're okay to drop the property from the api.

**Comment by bobsilverberg** [comment]
> @bobsilverberg [mozilla/addons-frontend#9579](https://github.com/mozilla/addons-frontend/issues/9579) removed references to `is_recommended` in the API, right? So we're okay to drop the property from the api.

Actually, no. As I was working on the next patch I realized it’s still being used by the code that calls the autocomplete API.

**Comment by eviljeff** [comment]
@bobsilverberg issue link?

**Comment by bobsilverberg** [comment]
> @bobsilverberg issue link?

Oops, I lied. That's what I get for replying to a GitHub issue first thing in the morning on my day off. Even the code for the autocomplete API has been moved away from `is_recommended`. We no longer rely on `is_recommended` in the API response. Sorry for the confusion.

**Comment by ioanarusiczki** [comment]
@eviljeff 'is_recommended` property which had boolean true/false values, is no longer present in the [Addon API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail). I verified for an addon, lang pack, dictionary and static theme submitted on AMO dev. 

An example:
https://addons-dev.allizom.org/api/v3/addons/addon/495924/
https://addons-dev.allizom.org/api/v4/addons/addon/495924/
https://addons-dev.allizom.org/api/v5/addons/addon/495924/

I've noticed `is_featured` is still present in the API but maybe there's a reason for that.
