### ISSUE TITLE
Include the contents of the shelves in the API

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#15284]
Supports #14871

Add the contents of the shelves to the API endpoint that represents the list of shelves that will appear on the AMO homepage.

* Please note the linked pull request only returns the addons based on `search` criteria. The addons based on `collections` will be addressed in #15614

**Comment by ioanarusiczki** [comment]
@xlisachan I made several requests for the search criteria:
- the API returns the list of addons (the search result added into the criteria field). I tried with all "See more..." links that are already available on the frontend and I did not see issues. 
- there's a case when the API returns a 400 bad requests with the message  "Invalid \"category\" parameter." Right now the 3 shelves that cause the problem are enabled in  [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/?o=-2). 

![the problem](https://user-images.githubusercontent.com/33448286/95200600-5469ed00-07e7-11eb-9bf7-c03fb77b9287.png)

Let me know if I should file an issue for further investigations.

**Comment by xlisachan** [comment]
@ioanarusiczki Thanks for the update! I no longer have access to dev, can you please share what's listed in the endpoint and criteria fields for the three shelves that are causing the problem? Thank you!

**Comment by ioanarusiczki** [comment]
@xlisachan Yes, the enabled shelves have the following criteria:

?category=holiday&sort=recommended%2Cusers&type=statictheme&app=firefox
?category=alerts-updates&sort=recommended%2Cusers&type=extension&app=firefox
?promoted=recommended&sort=random&type=extension

To add: when I replaced for the last criteria type=extension with type=statictheme I received a 200 response but with no results for the shelf "addons": []

**Comment by xlisachan** [comment]
@ioanarusiczki Thanks for providing the criteria fields!

@bobsilverberg, @eviljeff - after pulling the latest master branch and running `make update_docker`, I am no longer able to produce the error mentioned above. I also was not able to locally create/save shelves with the following criteria because none of them had any addons associated with them (which makes sense):
* ?category=holiday&sort=recommended%2Cusers&type=statictheme&app=firefox
* ?promoted=recommended&sort=random&type=extension
* ?promoted=recommended&sort=random&type=statictheme

e.g. [http://olympia.test/api/v4/addons/search/?promoted=recommended&sort=random&type=statictheme](url)

Have the parameters for recommended extensions and/or recommended themes changed? Please note, there is no error when the following shelves were created and enabled:
* ?category=alerts-updates&sort=recommended%2Cusers&type=extension&app=firefox
* ?sort=users&type=extension

In addition, I am no longer able to create a shelf with a collections endpoint, has this changed too? (Before I was able to save a shelf with `password-managers` in the criteria field that generated the following URL:
[http://olympia.test/api/v4/accounts/account/10968/collections/password-managers/addons/](url))

Please advise when you have a moment. Thank you!

**Comment by ioanarusiczki** [comment]
@xlisachan Hi Lisa, I tested this a bit more today to clarify my question marks. I am going to close this issue because I filed 2 followups:
https://github.com/mozilla/addons-server/issues/15688
https://github.com/mozilla/addons-server/issues/15689

So this is verified on dev.

**Comment by eviljeff** [comment]
> In addition, I am no longer able to create a shelf with a collections endpoint, has this changed too? (Before I was able to save a shelf with `password-managers` in the criteria field that generated the following URL:
> http://olympia.test/api/v4/accounts/account/10968/collections/password-managers/addons/

Its not changed.  If you've reset your database perhaps the account and/or collection doesn't exist though.

I've commented on the follow-up issues Ioana logged.
