### ISSUE TITLE
Broken admin activity log

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15291]
### Describe the problem and steps to reproduce it:

1. Open `/admin/models/activity/activitylog/`

### What happened?

Oops! We had an error.

### What did you expect to happen?

No oops!

### Anything else we should know?

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9394553/

Likely a regression from #15180.

**Comment by eviljeff** [comment]
> Likely a regression from #15180.

It is.

"Reverse for 'files.list' not found. 'files.list' is not a valid view function or pattern name." - one of the urls removed is still referenced.  (should check for other removed urls being referenced in the code when this is fixed)

**Comment by wagnerand** [comment]
> (should check for other removed urls being referenced in the code when this is fixed)

Done. That was the only one.

**Comment by AlexandraMoga** [comment]
I can open the admin activity log on -dev - https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/

This issue is verified fixed.
