### ISSUE TITLE
rm addon and user search fields from /admin landing page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15292]
the admin page currently has two obsolete search fields on the landing page.  

Addon search does a simple name query via the Addon manager and returns the results on a page (that then link to the django admin Addon change page).  Alternative is using the search field on the Addon changelist.

User search does an ajax request to get users (the endpoint actually django admin's UserProfile changelist search) and displays an inline div using javascript to show matches.  Clicking on the result appears to go to a broken link to a frontend page so I'm pretty sure it's not used.  Alternative is using the search field on the UserProfile changelist (that returns the same results, but with working links).

We should remove them both.

**Comment by AlexandraMoga** [comment]
The add-on and user search fields are no longer present on the admin homepage -  https://addons-internal.dev.mozaws.net/en-US/admin/.
