### ISSUE TITLE
Multiple Homepage shelves can occupy the same shelf Position at the same time

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15309]
Follow up for #14874 

### Describe the problem and steps to reproduce it:
1. Open the [Homepage shelves](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/add/) admin tool with an admin account
2. Select one of the available shelves from the list and set a Position
3. Save this homepage shelf and add another one, selecting the same Position as for the previous shelf
4. Save the second homepage shelf

### What happened?
The second shelf is successfully saved 

### What did you expect to happen?
The form should not allow for the enabling of multiple homepage shelves with the same Position

example of multiple [homepage shelves](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/), all with Position 1

![image](https://user-images.githubusercontent.com/31961530/90377620-e58ed400-e080-11ea-95ec-b2bccee0596a.png)

**Comment by ioanarusiczki** [comment]
@xlisachan I verified on dev - FF79(Win10). The issue is no longer reproducible. 

![ERROR](https://user-images.githubusercontent.com/33448286/90611472-74315b80-e20f-11ea-9ddd-79a6d4fe4d65.png)
