### ISSUE TITLE
set all the existing recommended addons to be desktop Firefox only (?)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15313]
The previous recommendation implementation was application agnostic on addons-server, but assumed to be desktop Firefox specific on addons-frontend.  When recommendation add-ons were transitioned to the promoted addons models they were similarly set without a specific application.  I believe all the existing addons were assessed for desktop only so we should update them to be just for desktop Firefox so frontend can fully support promoted add-ons for different applications.

@jvillalobos @devaneymoz can you confirm if all the existing recommended add-ons are indeed only supposed to be recommended for desktop Firefox?  If so we can run a db migration to fix them (if it's a partial thing you might have to do it manually)

**Comment by jvillalobos** [comment]
There are 9 recommended extensions that we currently support on Fenix, but they are identified through a collection and not their recommended state. For now I think it's fine to keep the Recommended for Android set empty. We can fill it up once we're ready to switch to the Recommended state as the source of truth for Fenix.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- all the recommended add-ons from dev `admin/models/discovery/promotedaddon/` had `Firefox` application set.
- for a recommended add-on, as an admin I could still change the Application from "Firefox" to "All Applications" or "Android" but I understand from Jorge's comment that it should stay as an available option.
