### ISSUE TITLE
Remove custom admin landing page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15310]
The custom admin landing page is no longer needed since all custom views have been removed.

**Comment by ioanarusiczki** [comment]
@wagnerand I verified on AMO dev - FF81(Win10):
- when I access admin tools from dev hub with an admin account I am redirected to [Models](https://addons-internal.dev.mozaws.net/en-US/admin/models/) page. 
- the [Admin](https://addons-internal.dev.mozaws.net/en-US/admin/) URL redirects to [Models](https://addons-internal.dev.mozaws.net/en-US/admin/models/).
