### ISSUE TITLE
support autograph signing for promoted for specific applications

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15315]
#14863 added support for signing other non-recommend promoted groups, but without considering applications.  So the possible states are `['recommended', 'verified', 'sponsored', 'line']`.  

After talking with @Rob--W and @mixedpuppy we're going to interpret `['recommended', 'verified', 'sponsored', 'line']` as being just for desktop Firefox, and add `['recommended-android', 'verified-android', 'sponsored-android', 'line-android']` to support Fenix.

**Comment by eviljeff** [comment]
Note: we need to consider PromotedApproval - it doesn't current track approval by application (because approval and signing is application agnostic right now) but it probably should be changed to record applications once the signing breaks it down.

**Comment by jvillalobos** [comment]
We decided to drop `sponsored` as a signing state. Verified and Sponsored will both be signed as `verified`.

We expect `verified` and `line` to be application-agnostic. Are the app-specific signing states being added just in case we decide to change that?

**Comment by eviljeff** [comment]
I don't have any preference, so I'll leave to @mixedpuppy to say what he'd prefer the signing states to be.

**Comment by mixedpuppy** [comment]
I don't think we need app specific for line and verified.  Anything outside of line, verified and recommended is simply ignored on desktop.  It will be up to specific apps as to what states they support, but I'd possibly prefer state-AppName over state-Platform.

**Comment by mixedpuppy** [comment]
After getting a couple more opinions, recommended-android is fine.

**Comment by eviljeff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1661230 for the autograph bug tracking

**Comment by eviljeff** [comment]
QA: the autograph side changes this relies on has landed but won't be deployed to autograph stage -that we use on addons-dev- until next week some time (w/c 31st August).  Until that's landed the `autograph_promoted_signer` must be disabled (I didn't add a new waffle switch from the original promoted signing changes because it's not been enabled on prod yet)

**Comment by ioanarusiczki** [comment]
@eviljeff I tested on dev with the switch `autograph_promoted_signer` enabled:
-  `mozilla-recommendations.json` file has "states":["verified"] for verified and sponsored add-ons, "states":["line"] for By Firefox add-ons, no matter of the application, wheter is All, Firefox or Android.

-  `mozilla-recommendations.json` file has "states":["recommended"] for a recommended add-on for Firefox Application. I could not test for Android or All because I have an error -> filed it https://github.com/mozilla/addons-server/issues/15371 

- not promoted, spotlight or strategic add-ons don't have the `mozilla-recommendations.json` file.

**Comment by eviljeff** [comment]
>     * `mozilla-recommendations.json` file has "states":["recommended"] for a recommended add-on for Firefox Application. I could not test for Android or All because I have an error -> filed it #15371

see earlier comment https://github.com/mozilla/addons-server/issues/15315#issuecomment-680936873 - this depends on autograph changes being deployed to autograph stage.

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if I got it right:
- on dev the signing must be tested with `autograph_promoted_signer` enabled
- while switch is enabled, and the add-on is signed, the mozilla-recommendations.json will show the states from https://github.com/mozilla/addons-server/issues/14863 with 2 exceptions (changes): sponsored add-ons are signed with "states":["verified"] and the recommended for android should have "states":["recommended-android"]. This also means I must wait a while until I can check the scenario.

**Comment by eviljeff** [comment]
@ioanarusiczki yes.

**Comment by eviljeff** [comment]
@ioanarusiczki the changes have (apparently) been deployed to autograph now, so it should be possible to verify this issue with the `autograph_promoted_signer` switch enabled.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- Examples for the recommended category:
[Recommended -android](https://code.addons-dev.allizom.org/en-US/browse/620079/versions/1691993/?path=mozilla-recommendation.json) has "states":["recommended-android"]
[All platforms ](https://code.addons-dev.allizom.org/en-US/browse/620115/versions/1692001/?path=mozilla-recommendation.json) is "states":["recommended","recommended-android"], I think it's as expected.

- [Sponsored](https://code.addons-dev.allizom.org/en-US/browse/620127/versions/1692002/?path=mozilla-recommendation.json) have now "states":["verified"] no matter of the platform.

- I'm going to complete testing for all categories tomorrow to make sure it's all good.

**Comment by ioanarusiczki** [comment]
Looks good to me. Verified on dev - FF80(Win10).
