### ISSUE TITLE
The Promoted status should be better highlighted in reviewer tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15316]
Follow-up for #15197 

### Describe the problem and steps to reproduce it:
1. Open the review page of an add-on belonging to a Promoted category - see [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/lang-pack-with-statistics)
2. Scroll down to the bottom of the Version history and check the the add-on Promoted status

### What happened?
The promoted status message is a bit hard to spot 

### What did you expect to happen?
The promoted status should be better highlighted 

[1] - example from -dev:
![image](https://user-images.githubusercontent.com/31961530/90405481-7b8c2400-e0ac-11ea-994f-527ba2eab10e.png)

[2] - example from stage:
![image](https://user-images.githubusercontent.com/31961530/90405533-91014e00-e0ac-11ea-83a3-fb7fa7a2dc4e.png)

**Comment by wagnerand** [comment]
Yes, please!

**Comment by eviljeff** [comment]
🙄 I must have broken the css.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this issue on dev with FF79(Win10) for all the categories and the previous style is back.

An example:
![by Firefox addon](https://user-images.githubusercontent.com/33448286/90606999-49dc9f80-e209-11ea-9183-aa4b9334b1a5.png)
