### ISSUE TITLE
The developer should not be able to delete/disable a promoted version 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15326]
@eviljeff Testing around the add-on admin categories and dev hub I've noticed the following:

STR:
1. Submit and approve an add-on for one of the categories that require approval (recommended, sponsored, verified)
2. From admin tools change the category, for example from Verified to Sponsored 
3. Go to the version page from dev hub and try to delete/disable the first version

Expected result:
The developer should not be able to delete/disable the first version. 

Actual result:
The first approved and verified version can be disabled/deleted.  Also, "approved and verified" state becomes "approved" in dev hub. 

Notes:
The developer is able to delete the current version until the next version is uploaded and approved (as a sponsored version in this case) when the category is changed from admin tools.

**Comment by eviljeff** [comment]
This wasn't a requirement from the PRD.  The restriction is _only_ when an add-on is approved for a promotion.  When the promoted group is changed the add-on is no longer approved for that promotion so the developer is free to delete any versions as before.    

I asked about moving between promoted groups and how this would be handled in the PRD and was told it would be a rare case and handled manually.  https://docs.google.com/document/d/1QpEfiiAnfoEGsJuDbYe69WfYoQ_f_9DqPhK3VKWv9kc/edit?disco=AAAAGtBkiic

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, thanks for the info. I did not want this to cause problems later (I read that it's going to be rare)
