### ISSUE TITLE
Profile info is not being imported from FxA to AMO

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1532]
## steps to reproduce:
1. On FxA, create an account with a profile pic and a display name
2. Register on AMO using the account created in #1
3. Navigate to Account Settings
## expected behavior:

Profile pic and display name added to FxA is imported to AMO 
## observed behavior:

Profile info is not being imported from FxA to AMO

**Comment by andymckay** [comment]
Won't be in for the initial release, depends upon mozilla/fxa-content-server#2477

**Comment by mstriemer** [comment]
We get this data from FxA if it is set on the user's account already since we are requesting the `profile` scope. If the values aren't set then they aren't returned (missing not blank) but if they are set they look like:

```py
{
  u'displayName': u'Mark',
  u'email': u'mark@example.com',
  u'avatar': u'https://secure.gravatar.com/avatar/5f16891827398127371eae37?s=600',
  u'uid': u'fab6e0de0219283198273918236f10712'
}
```

rfk pointed out in an email:

> Since AMO is a trusted relier, you don't get the standard oauth
> permission prompt asking whether the user wants to share their profile
> data.  If you'd like to trigger it explicitly to get the UX shown in
> this issue:
> 
>   https://github.com/mozilla/fxa-content-server/issues/2477
> 
> Then please pass "prompt=consent" as a query parameter when kicking off
> the oauth dance.  We don't have the code for showing that view in
> production yet, but this will ensure we can switch it on for you when
> it's ready.

**Comment by mstriemer** [comment]
It's mentioned above but we should ensure that we send `prompt=consent` when we start importing data.
