### ISSUE TITLE
Sort pending rejections queue by time until rejection, not weight

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#15333]
The pending rejections queue seems to be sorted by weight currently. It would be great to sort this by deadline for rejection, with the closest deadline first.

**Comment by diox** [comment]
It's actually sorted by add-on creation date. I'll change it to rejection deadline.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage:

![image](https://user-images.githubusercontent.com/31961530/92576205-e5ee4980-f291-11ea-83e1-090c27ed5589.png)
