### ISSUE TITLE
The search endpoint allows saving a shelf when hash or slash are used for criteria

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15349]
@xlisachan 
Followup for https://github.com/mozilla/addons-server/issues/14952

1. Go to the shelves module to "+add shelf module"
2. Give, a title, select the `search` endpoint 
3. Add "#" or "/" into the Criteria field

Expected result:
Check criteria - No data found

Actual result:
The shelf is saved

Notes:
This is reproducible with: "#?recommended=true&sort=random&type=extension" or "/?recommended=true&sort=random&type=extension" also with multiple "#####" or "/////////////" and combinations of "#/" or "#/text".
I could not reproduce it with the collections endpoint.
I could not reproduce this issue using other special chars.???????????//

**Comment by xlisachan** [comment]
@ioanarusiczki As the patch should now catch when the value entered for `criteria` does not start with `?` when 'search' is selected for the endpoint, please note it was mentioned in #15351 that as the tool is not user/developer facing, we will not need to catch errors such as `?####`, `?///////`, or any combinations of `?#/` or `?#/text`. Please let us know if you have any questions. Thank you!

**Comment by xlisachan** [comment]
@eviljeff please assign me to this when you have moment. Thanks!

**Comment by ioanarusiczki** [comment]
@xlisachan Then maybe the previous validation method implemented in https://github.com/mozilla/addons-server/issues/14952 (an incorrect search parameter could not be saved) would help better the admin? Patch could be reverted (it is how you decide it to be, so let me know)

**Comment by xlisachan** [comment]
@ioanarusiczki Let's keep it in its current state as the patch addresses the internal server error mentioned in #15350 Thanks!

**Comment by ioanarusiczki** [comment]
@xlisachan Issue is verified on dev - FF80(Win10).
