### ISSUE TITLE
Deleting reviewed file causes huge extra effort in reviewing

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1534]
This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1130585

Scenario:

1) Developer uploads version 1.0, gets rejected.
2) Developer fixes issues, reuploads version 1.0, validator says "Reusing an already used version number is not allowed".
3) Developer goes to developer hub, deletes file from version 1.0.
4) Developer reuploads version 1.0, gets the same error from validator again. (At this point the developer is probably annoyed.)
5) Developer increases version number to 1.1 and reuploads, add-on gets into the queue.

At this point, version 1.0 is lost and review has to start from scratch, instead of a reviewer being able to diff 1.0 against 1.1 and do a much quicker review.

How this is supposed to be solved, is tbd.

**Comment by erosman** [comment]
An option would be to disallow developer from deleting an addon and only give them the option to disable the addon.

**Comment by wagnerand** [comment]
This is about deleted versions, not add-ons. Anyway, I proposed disallowing deleting versions, which was rejected.

**Comment by erosman** [comment]
I meant to say versions .... I will correct my previous post.

**Comment by wagnerand** [comment]
For reference, relevant bugs are https://bugzilla.mozilla.org/show_bug.cgi?id=1130585#c6 .

**Comment by wagnerand** [comment]
I analyzed which cases already work fine and what needs to be corrected.

Todo:

- [ ] Keep allowing to delete version, but disallow to re-use the version number for a deleted version and keep the deleted file accessible to reviewers (soft-deletion).
- [ ] Disallow the re-use of the version number if a disabled version with the same version number exists.

**Comment by eviljeff** [comment]
Is it **all** versions we want soft-deleted, or just reviewed ones?  If we end up keeping every version, even ones that exist for only a few minutes, it might get quite messy.

**Comment by wagnerand** [comment]
I think it's reasonable to keep reviewed ones only.

**Comment by eviljeff** [comment]
note if we don't keep (soft delete) a version we lose the version number so that version number could be re-used.

**Comment by wagnerand** [comment]
Imho, those are two different things. We could and maybe should still keep a minimal record in the database for deleted unreviewed versions, but throw away the file.

**Comment by eviljeff** [comment]
Technically, its not two different things - its a binary thing.  The Version is either hard deleted or soft deleted. If its hard-deleted then we remove the record in the database; if its soft deleted then the records still there.
So, we now do want all Versions to be soft-deleted. But the File should be removed?  Or just the xpi on storage?

**Comment by wagnerand** [comment]
So, if it's a binary thing, we should try to keep it as simple as possible and just have all versions soft-deleted instead of having different logic depending on the review state.
