### ISSUE TITLE
Enable admin block view access for an add-on using its GUID

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15344]
Similar to django admin views for add-ons instances, admins need to be able to access an add-on block given an add-on GUID.

There is a workaround to go through the reviewer tools page, but for convenience, important and often used pages should have a way to directly access them using the official identifier, which is the add-on GUID.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified on dev - FF79(Win10). 
An URL such as https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/GUID redirects to the block change page.
