### ISSUE TITLE
CSP warning 'frame-src' has been deprecated

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1535]
Relates to #995 

Getting the following warning when accessing dev or stage home page in Firefox 45.0a2:

`Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.`
(unknown source)

**Comment by muffinresearch** [comment]
Yep that's a known issue. django-csp doesn't yet support child-src.

**Comment by wagnerand** [comment]
Ah, sorry then. I was using github search and couldn't find anything. Feel free to close this at your convenience.

**Comment by muffinresearch** [comment]
@wagnerand np, it's good to have this issue filed to catch additional reports and it reminds us that we ideally should try and get django-csp updated too.
