### ISSUE TITLE
Two dots used in the criteria field with the search endpoint produce a server error

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15350]
@xlisachan 
Followup for https://github.com/mozilla/addons-server/issues/14952

STR:
1. Go to the new shelf model 
2. Add a new shelf, select the search endpoint and use for Criteria two dots before a valid criteria "..?recommended=true&sort=random&type=extension"or simply two dots in this field ".."

result:
internal server error - 500

Notes:
I could not reproduce a server error for the collection endpoint with this scenario. Also I tested other special char combinations and I did not reproduce the error. - FF79(Win10).

**Comment by xlisachan** [comment]
@eviljeff please assign me to this when you have moment. Thanks!

**Comment by ioanarusiczki** [comment]
@xlisachan This is no longer reproducible on dev, the warning " Check criteria field." is displayed - FF80(Win10).
