### ISSUE TITLE
Add an API for releng to submit entirely new locales

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15353]
The current signing API does not support submission of the first listed add-on version, due to required extra meta-data. To remove the obstacles and avoid breakage in the release process, we could add an API that support this specifically for langpack submissions from the releng account.

When a the first listed version gets submitted through the API, AMO will set the required metadata to some hard-coded defaults, for example setting the license etc.

/cc @escapewindow

**Comment by diox** [comment]
I'd have to take a closer look at the existing signing API but I think it could be added there. See also https://github.com/mozilla/addons-server/issues/7811#issuecomment-373204608 which describes the missing data we'd need a default value for.

**Comment by eviljeff** [comment]
I still think like I said in #7811, we should take the opportunity to build basic support for creating via /api/addons (e.g. /api/addons/upload to handle the upload, then a POST|PUT on /api/addons to create the addon, with necessary metadata)

**Comment by diox** [comment]
Note that currently, we don't automatically set `target_locale` for langpacks - this would need to be added as well, from the manifest `langpack_id` property (+ some conversion ? I don't remember)

**Comment by jvillalobos** [comment]
Creating a new API would be kind of defeating the purpose, no? It means that you need to know in advance that you need to do something different for new langpacks, and at that point you could as well just submit it manually. I think it makes sense to  create a langpack listing if we get something we didn't have before via the current API. Langpack listings aren't particularly distinctive and they could be edited to something nicer later on if needed.

**Comment by MihaiTabara** [comment]
This hit us in 91.0b2, it's still important for RelEng to get fixed on AMO side. Every time this breaks, it requires RelEng to perform the manual fix. It impacts RelMan as well if we're not around.

**Comment by MihaiTabara** [comment]
Note to self: TIL https://github.com/mozilla/addons-server/issues/7811 will be a good starting point to fixing this issue.

**Comment by wagnerand** [comment]
> Note to self: TIL #7811 will be a good starting point to fixing this issue.

The two issues should be fairly distinct. The API requested here is to make new Firefox versions known to AMO, so add-ons (mostly langpacks these days) can set the right compatibility for their (already) uploaded versions.

**Comment by wagnerand** [comment]
(Please ignore my earlier comment in case you got an email notification).

I'd like to understand why you were hit by this recently. Until this API has been implemented, we have an established process to get new langpacks added manually. /cc @flodolo 

Could you expand what went wrong or why that didn't work this time?

**Comment by escapewindow** [comment]
Per [this issue's description](https://github.com/mozilla/addons-server/issues/15353#issue-684788449), the API requested is to add new locales (i.e., new langpacks), so we don't have to submit them manually. Requiring manual steps in an otherwise automated release blocks releases on a handful of individuals. The manual steps are a considerable pain point.

**Comment by flodolo** [comment]
> Could you expand what went wrong or why that didn't work this time?

While I don't have any visibility over what happens on the RelEng's side, I don't think the problem happened only this time, it happens every time there's new locale (which is not frequent, possibly making things even worse).

There are some manual steps I need to do [once the langpack is available](https://mozilla-l10n.github.io/documentation/products/firefox_desktop/adding_release.html#update-language-pack-settings-on-amo), but that's acceptable on my side, given everything is manual to get to that point.

**Comment by eviljeff** [comment]
#7811 would be the base for any support for lang packs to be submitted entirely automatically, but we'll keep this issue open because langpacks will certainly need some special support adding - if not a separate endpoint.  (In particular, you need the ability to submit an xpi without knowing if it's a new add-on or a new version, which is something that ends up being problematic for add-ons in general.)

**Comment by eviljeff** [comment]
#19342 will allow an upload to be sent as a PUT request to `/api/v5/addons/addon/<addon-guid>/`

Some things to note:
- it's not just limited to langpacks or releng (but the existing restriction about who can submit langpacks is still in place) - any add-on can be submitted this way by any add-on developer.
- there isn't any automatic metadata for langpacks as suggested in comment0, but categories and license can specified in the JSON postdata (and summary if there isn't a description in the manifest).
- the guid must be defined in the manifest, and match the guid in the url
- this is a v5+ api feature (along with the rest of the add-on submission api work) so it's still a little experimental/work-in-progress.  We can help with some more detailed guidance on the move over from the old signing api once releng is ready to switch (and is comfortable with the experimental-ness)

**Comment by ioanarusiczki** [comment]
@eviljeff I'm stuck with a 400 response even if I add version as form-data. Am I doing something wrong? 

![version is required](https://user-images.githubusercontent.com/33448286/173583569-f95fb059-4844-4968-a5b3-b1801bbe1231.png)

**Comment by eviljeff** [comment]
@ioanarusiczki it looks like you're sending for data that would be sent for a version create request, but PUT needs the addon create request data.

**Comment by ioanarusiczki** [comment]
@eviljeff If I take version out it would throw the same error -> that version is required

**Comment by ioanarusiczki** [comment]
@eviljeff Ah, I thought the whole idea is to make one request and skip the upload , I got confused reading the discussions around it. Alright , then I know what to do, thanks!

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified this on -dev:
- using PUT I could create and upload new versions for all addon types.
- I could not submit a lang pack without the lang pack permission.
- filed https://github.com/mozilla/addons-server/issues/19366 for an issue noticed.
- when I create a new upload for the PUT request but the manifest has an id and version which was used to create before - I get at first an error such as ""Upload is not valid." . Then I repeat the PUT request (with the same upload as before) and the message changes to ""Version 1.45 already exists." - > perhaps it should throw only "Version 1.45 already exists." from the first attempt ?
