### ISSUE TITLE
Store Promoted approval by application

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15363]
spun out from https://github.com/mozilla/addons-server/issues/15315

> we need to consider PromotedApproval - it doesn't current track approval by application (because approval and signing is application agnostic right now) but it probably should be changed to record applications once the signing breaks it down.

**Comment by eviljeff** [comment]
some decisions needed here:
1) a) do we store application as a single value, like `PromotedAddon`, where `none` is interpreted as "all applications" and an approval for a specific application is stored as the app id; or 
  b) create a `PromotedApproval` record per application as `PromotedApproval` already supports one->many approvals for a single `Version`.  Leaning towards the latter.
2) a) Should we match the autograph signing states in the xpi, where only `Recommended` group has separate states for desktop and android, and all other groups just have a single state (i.e. it's a reflection of how the xpi was signed); or 
  b) or create multiple `PromotedApproval` instances for all groups even though the signing isn't distinct for the others (i.e. it's a reflection of what `PromotedAddon.application` was at the time of approval).
3) What about existing data?  There was a migration a few weeks ago that set all existing `Recommended` addons to desktop only, and some addons have recently been added for android for `Recommended` (or changed to `all`).  So the current state of `PromotedAddon.application` isn't necessarily the same for previous approvals (especially if we consider the approval to match what was signed in the xpi - the waffle switch to enable `recommended-android` state to be added to the xpi was only enabled ~18th September).

**Comment by eviljeff** [comment]
And possibly a follow-up, but should `Addon.promoted_group` take `application` into account?  So there needs to be an approval existing for the current application of the `PromotedAddon` (what about when the current `.application` is `None`, i.e. all, and there exists a `PromotedApproval` for desktop Firefox but not Android?).

Also when the `application` kwarg is passed?  (I don't think `application=` kwarg is actually used in live code anyway, so may be best to just remove it)

**Comment by eviljeff** [comment]
@jvillalobos @diox thoughts on this issue to point me in a particular direction?

Note: this issue is really only ever going to be a problem if the supported application is changed _after_ an addon has been added as a `PromotedAddon` and approved the first time.  I.e. it's the potential difference between what `PromotedAddon.application` is, and the signing state in the xpi of a version on that addon.

**Comment by jvillalobos** [comment]
I think that if an add-on is Recommended in only one application, say, Desktop, and then is changed to be Recommended for both, or only Android, an approval is needed to make that change. Otherwise the signing state in the latest file will be inconsistent with the state in the DB and the front-end.

**Comment by eviljeff** [comment]
> some decisions needed here:

I'm going to go with 1b) 2b) and 3) assume the current application state of the group is the same for all approvals.

`Addon.promoted_group(application=None)` will return the group if there are approvals matching the current application(s) for the `PromotedAddon` (i.e. 2 approvals if `all`).  If `Addon.promoted_group(application=amo.FIREFOX)` then it'll just check for the firefox desktop approval (and similarly for Android)

**Comment by eviljeff** [comment]
spun off:

> `Addon.promoted_group(application=None)` will return the group if there are approvals matching the current application(s) for the `PromotedAddon` (i.e. 2 approvals if `all`). If `Addon.promoted_group(application=amo.FIREFOX)` then it'll just check for the firefox desktop approval (and similarly for Android)

into #15569 because it was getting complicated.

**Comment by ioanarusiczki** [comment]
@eviljeff 
Once the addon is signed the mozilla-recommendation.json file shows the states as described in https://github.com/mozilla/addons-server/issues/15315. 

Also the Application for a recommended addon (or other promoted category) can be changed from the admin before submitting a new version, from Firefox to All or Android. mozilla-recommendation.json shows these changes correctly for the new recommended and approved version.

If there's anything else I should check, please let me know.

**Comment by eviljeff** [comment]
@ioanarusiczki just that the approvals show up in django admin (on a promotedaddon page under /admin/models/promoted/promotedaddon/ )

**Comment by ioanarusiczki** [comment]
@eviljeff The [promoted approvals](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/240/change/) show up in django admin: all versions approved in the past and the versions approved today.
