### ISSUE TITLE
drop Addon.is_recommended

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15368]
it's unnecessary now we have Addon.promoted_groups (and Addon.promoted cached_property for ES)

**Comment by ioanarusiczki** [comment]
@eviljeff Should I check that `/admin/models/discovery/promotedaddon/` works as before?

**Comment by eviljeff** [comment]
@ioanarusiczki most of the changes ended up being in the API so I'd check that all still works as expected (including making a change to the add-on name/summary to trigger an ES reindex)

**Comment by ioanarusiczki** [comment]
@eviljeff So far I have not encountered problems in [the admin feature](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/), the addon/search API, or when updating name/summary (which is shown everywhere correctly), promoted category changes and so on. 
Verified on dev - FF80(Win10).
