### ISSUE TITLE
500 Error when trying to approve recommended add-ons

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15371]
STR:
1.  Set the `Application` from `/admin/models/discovery/promotedaddon/` is set to `All Applications` or `Firefox for Android` for a recommended addon
2. Submit a new version 
3. Try to approve the version

Results:
500 error

Notes:
It is not reproducible with `Firefox` application. 
Here are my [examples ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/recommended) of add-ons I could not approve.

**Comment by eviljeff** [comment]
depends on autograph side changes called out here https://github.com/mozilla/addons-server/issues/15315#issuecomment-680936873
