### ISSUE TITLE
evaluate drop/replace use of pyOpenSSL/cryptography

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15370]
We don't use https://github.com/pyca/cryptography directly, apart from in a test (just to check the version)

It's a dependency of https://pypi.org/project/pyOpenSSL/ ... that we don't seem to use directly anywhere either.  (There's a reference in https://github.com/mozilla/addons-server/blob/master/src/olympia/core/apps.py#L30 but it's loading a package from `urllib3`.  urllib3, however, only mentions having to use cryptography in reference to python2 https://urllib3.readthedocs.io/en/latest/user-guide.html#certificate-verification-in-python-2 so... maybe we don't need it any more in python3?

Another oddity is the warning at the top of the pyOpenSSL project saying " Note: The Python Cryptographic Authority strongly suggests the use of pyca/cryptography where possible. If you are using pyOpenSSL for anything other than making a TLS connection you should move to cryptography and drop your pyOpenSSL dependency."

**Comment by diox** [comment]
- `cryptography` is also required by at least `m2secret-py3` (which is required by `django-aesfield`) and `PyFxA`. So we need to keep it.
- `pyOpenSSL` does look obsolete - it was used by... app-validator, back in the Marketplace days: https://github.com/mozilla/zamboni/commit/74e0059b0f745dcd1a4a89611fa9ab30b9e77e84
- `ndg-httpsclient` and `pyasn1` are likely obsolete as well.
-  Our code in `core/apps.py` you mentioned, `enable_urllib_certificate_checking()` uses `urllib3`'s vendored copy of `pyopenssl` - but as you noted it's also obsolete with Python 3 so it should go.
