### ISSUE TITLE
Review is submitted for latest version even if previous version was being reviewed

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#1542]
I had not noticed this issue before so I am guessing it is related to the latest push.

Example: `https://addons.mozilla.org/en-US/editors/review/search-toolbar-twitter`
-  I was reviewing **Version 1.1 · January 28, 2016** as it was the latest version due for the review.
- It seems as I was reviewing, the developer had uploaded a new **Version 1.2 · January 28, 2016**
- The review for v1.1 was posted. Previously, under these circumstances, the review page would reload to show that the posted review is no longer applicable, but in this case, the review was attached to the v1.2 which is fact had NOT been reviewed and/or inspected.

This can cause a serious security flaw as any new upload, while the previous is being reviewed, can get approved even if they were not reviewed.

**Comment by wagnerand** [comment]
This is another case where you accesses the review too early when the submission process was not complete yetl

**Comment by erosman** [comment]
Not the case.. since a new addon with a new version number was uploaded.

**Comment by wagnerand** [comment]
And that new version was still in the submission process...

**Comment by erosman** [comment]
Once again.. you are missing the point
v1.1 was uploaded
v1.1 was reviewed

- Do you think reviews are psychic to know if the dev is uploading a new version?
- Do you think the speed of my reviews are by far superior to AMO computers?
- Or is it just like always that you object to anything that I post or say?
- **Do you have any issues with my ethnic background? It sure feels that way.**

Nonetheless. it is a security flaw ..... whatever the circumstances. 
It is prudent to fix it instead making biased arguments.

**Comment by wagnerand** [comment]
I will ignore and not address any personal comments because they are irrelevant to this case and unobjective.

AMO will automatically deactivate old versions if new versions have been submitted. If the submission process of a new version has not been finished yet, AMO cannot deactivate the old version just yet.

**Comment by erosman** [comment]
Once again, your comments are irrelevant since the issue did occur.

I spent my time and effort reporting the bag.
If you dont want to fix it, then that is your choice.
You can do whatever you wish with the information provided.

**Comment by wagnerand** [comment]
I was being mislead by 
> The review for v1.1 was posted.
and
> v1.1 was uploaded
> v1.1 was reviewed

That's indeed a problem.

Just to be clear, I've just seen the issue the other way around where the review was attached to the previous version, that should have been attached to the current pending one.

**Comment by erosman** [comment]
As I said.. this is the first time I have seen this issue.
I had seen the issue that the review ended up on the previous upload but never this one.

**Comment by EnTeQuAk** [comment]
Has this issue occurred more often recently or was that really just this one time?

**Comment by erosman** [comment]
It is a very specific issue which occurred on specific circumstances (not common).
To test it, a test situation has to be created.

**Comment by EnTeQuAk** [comment]
Do we have clear steps to reproduce this?

**Comment by wagnerand** [comment]
STR iirc:
1. Upload a new version or a new add-on. Let's assume the version is 0.1.
2. Open the review page for that add-on in a new tab. 0.1 will be shown as the latest version and the one to be reviewed.
3. Upload a new version, say 0.2.
4. WIthout refreshing the review page, submit the review form.

Actual results:
The review decision is applied to 0.2

Expected result:
Not sure, at least the review should not applied to 0.2. We could show an error.

---

I think a solution would be to have the server include the reviewed version (`latest_version`) at that time when constructing the form. The client should send it back as a form field when the form is submitted. On the server-side we could then just check whether the transmitted `latest_version` is still the actual `latest_version` and fail if it's not.

**Comment by wagnerand** [comment]
Note that the server should not trust that version entry submitted by the client. Ie, it should not be used other than in the condition to avoid (un)intentional review of the wrong version.

**Comment by spoji** [comment]
I can confirm the steps Andreas posted on https://github.com/mozilla/addons-server/issues/1542#issuecomment-231039105 are correct. I just had the same results with a review this morning.
