### ISSUE TITLE
Tweak rejection scheduled deadline message in review page when a new version has been submitted since

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15429]
Per design, when a new version is submitted, this "pauses" the scheduled rejections of previous versions. This has caused some confusion, particularly because we end up showing a `Approved · Scheduled for rejection in 0 minutes` message next to each version scheduled for rejection.

In https://github.com/mozilla/addons-server/issues/15261#issuecomment-683922240 @jvillalobos suggested a new copy for this message in that particular scenario - "Approved · Pending Rejection on review of new version".

**Comment by AlexandraMoga** [comment]
I've verified the Pending rejection messaging for add-ons with delayed rejections in different states:

Pending rejection message before a new version is submitted:
![image](https://user-images.githubusercontent.com/31961530/93313418-1f363480-f811-11ea-8b88-aaecf5ba37ec.png)


Pending rejection message after a new version is submitted:
![image](https://user-images.githubusercontent.com/31961530/93313449-278e6f80-f811-11ea-823c-7369cb7f2bb0.png)

If the new version is approved, the pending rejection message changes back to displaying "Scheduled rejection in..." 

I'm marking this as verified fixed on -stage.
