### ISSUE TITLE
Remove reviewers/sql_models.py / RawSQLModel

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15431]
For the longest time reviewer tools in AMO have depended on a custom pseudo-ORM implemented in 
https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/sql_model.py.

The main purpose was to work around limitations of the Django ORM 10 years ago, but now this is a pain to maintain and can make things harder to optimize (like counts) or force code duplication. We should remove it and replace it with nice manager methods and querysets to fetch reviewer queues that are still using it.

**Comment by diox** [comment]
The main things the query is currently doing that can be annoying with the ORM:

- **Filter add-ons with versions awaiting review, and return the latest version awaiting review.**
Technically, the current query cheats and the "latest" bit for the first point is not guaranteed - it just picks up the `version` column from the `JOIN`, and it works because there is a `GROUP BY` on `addon.id` and we only allow a single listed version to be awaiting review at any given time for each add-on. For unlisted we don't display the latest version, though we still group by add-on.
Reproducing this with the ORM is a bit annoying but doable. `annotate(latest_version=F('versions__version')` doesn't work because it would add the column to the `GROUP BY`, which we don't want. But we can cheat and wrap it in a `Func()` to avoid that: `.annotate(latest_version=Func(F('versions__version'), function='LOWER')` should work. Alternatively, we can drop to raw SQL with a bit of `extra()` : `.extra(select={'latest_version': 'versions.version'})`. Both these solutions assume there is only one join to `versions`, but if that's not the case we're in trouble anyway...

- **Group results by add-on**  
Because we need to fetch extra data from the joins (see previous point), `distinct()` won't work. To address this, the current query has an arbitrary `GROUP BY id`. This is also not as easy to do in the ORM that we'd like, but doing an `annotate()` with an aggregation function should do the trick and force Django to do it for us.

- **Retrieve waiting time since nomination**
The current query retrieves waiting time in a convoluted way, calling `TIMESTAMPDIFF()` multiple times to get the time spend in days, hours and minutes, using the same trick used for `latest_version` to simply pick up the column from the join. Since we need an arbitrary aggregation anyway, and we'd like unlisted support as well, we can replace that with `oldest_nomination=Min('versions__nomination')` (`created` instead of `nomination` for unlisted) and then use Django's `naturaltime()`.

- **Fetch the add-on name translation**
Because it doesn't care about translations other than the name, and because it's raw SQL, the current query does a inner join directly on the translations table with the add-on default locale, bypassing all our logic around translations and avoiding the typical second query used to fetch translations. It's certainly more efficient, but it's a bit tricky to do in the ORM. The closest thing I can think of is to use `defer()` on all translation fields except `name` - we'll still have a separate query for translations, but at least it would only fetch the names. That'd be `.only_translations().defer(*[x.name for x in Addon._meta.translated_fields if x.name != 'name'])`.

I've used https://github.com/mozilla/addons-server/issues/17248 as a testing ground for the ORM-based approach, and it seems to work. Now all that remains is applying all of this to the current queues and finally get rid of `RawSQLModel` ...

**Comment by diox** [comment]
QA: check that queues in reviewer tools work as before, paying special attention to the ordering, if flags and latest version information shows up correctly, as well as links. Also, there shouldn't be any performance regressions, including for unlisted queue, which hopefully is marginally faster (though it may not be apparent on dev)

**Comment by ioanarusiczki** [comment]
@diox I filed an issue https://github.com/mozilla/addons-server/issues/17766 
Except for that it should be good. I think there's a better performance in loading the queues overall, compared to stage.
