### ISSUE TITLE
Not Strictly Olympia Issue: Please announce the changes that affect reviewing

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#1543]
As the issues directly affects Olympia, and Olympia devs know of such changes, and there isn't any other channels that I am aware of to post it, please announce the changes that affect reviewing.

Example:
[AMO wrongly identifies JPM addons as Jetpack Add-on](https://github.com/mozilla/olympia/issues/1540)

Additional reference:
[MyFastBooking 5.2.1 didn’t pass review](https://discourse.mozilla-community.org/t/myfastbooking-5-2-1-didnt-pass-review/6785)

**Comment by wagnerand** [comment]
Those changes did not affect reviewing at all.

**Comment by wagnerand** [comment]
Well, I'll reopen this as it is still valid, just the example is wrong.

Usually we do announce changes that affect reviewers using the -internal mailing list. What other channels do you think would be useful?

**Comment by erosman** [comment]
I do read all emails.
I also read the notices that sometimes appear on top the queue pages.
Any notification would be good.
I made the review mistake (quickly corrected with the help of Noitidart) and felt bad about making such mistake and the developer inconvenience.

**Comment by andymckay** [comment]
I'm not sure what to do with this or even figure out how a change affects reviewers to be honest.

**Comment by jvillalobos** [comment]
This is mostly on us (admins), to communicate changes that affect reviewers. I don't think there's anything to do on the site, so I'm closing.
