### ISSUE TITLE
Handle review for minified submissions that lack source code

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15434]
Some minified submissions are not automatically approved. For those, there should be a way for reviewers to request sources with a deadline attached that would either automatically reject the submission if the deadline expires (like delay rejection), or put this again on the reviewer's table to reject manually.
The action of requesting source code could also be automated.

**Comment by jvillalobos** [comment]
Why can't delayed rejection be used in this case?

**Comment by wagnerand** [comment]
> Why can't delayed rejection be used in this case?

Delayed rejections are not available for unlisted submissions. There might also be listed edge-cases that could be affected.
