### ISSUE TITLE
allow API to filter by multiple promoted groups at once

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15432]
from https://github.com/mozilla/addons-server/issues/15272#issuecomment-685924200

> In order to be able to search for "Reviewed", as discussed above, we would need to be able to specify ?promoted=recommended,verified,line

Note it'd be `?promoted=recommended,sponsored,verified,line` because the sponsored and verified are still differentiated in the api (if there is a request to actually combine the groups rather than just hide the difference in addons-frontend for now please file an issue)

There was an alternative suggestion from @bobsilverberg too:
> We could probably implement a ?promoted=reviewed argument, which the server would understand to be the same as ?promoted=recommended,verified,line

Effectively that's allowing filtering by promoted group _feature_ rather than the group itself (all groups where `.pre_review is True`) which is an interesting idea.  It's doable?  Not sure how much benefit there would be for consumers of the API though - they wouldn't need a change if the groups which were reviewed was changed... but there would probably be other changes needed so 🤷 

@jvillalobos in the issue (and PRD) you've said "Reviewed" is Recommended, Verified (& Sponsored), and Line, but Spotlight is also reviewed, it's just not badged.  Is this an oversight, or is "Reviewed" more "Badged"?

**Comment by jvillalobos** [comment]
It's more like "Badged", yeah. Spotlight isn't exposed to users in any way, and it's meant to be more temporary than the other groups, so it's intentionally excluded from the filter.

**Comment by eviljeff** [comment]
#15448 is just going to add comma separated support to the filter - we can add support for meta-groups like "badged" in a follow-up if it's needed by frontend (rather than passing `?promoted=recommended,sponsored,verified,line` directly)

**Comment by eviljeff** [comment]
#15468 will add support for a meta group

**Comment by ioanarusiczki** [comment]
@eviljeff Making requests with any of the promoted categories in any order will return a 200 response and display add-ons.

An example:
https://addons-dev.allizom.org/api/v5/addons/search/?promoted=sponsored,spotlight,strategic,line,verified,recommended&page=3&app=firefox
