### ISSUE TITLE
Use weekly downloads in stats overview

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15440]
See: https://discourse.mozilla.org/t/downloads-statistics/66949

This change was planned but we had to stop the execution of the cron task that updates total downloads to fix https://github.com/mozilla/addons-server/issues/15135 last month, so let's hide total downloads.

**Comment by ioanarusiczki** [comment]
@willdurand From the [Bigquery samples](https://github.com/mozilla/bigquery-etl/blob/3cefa96e15cebbded340633bed240db36bb8cff5/sql/amo_dev/amo_stats_dau_v2/query.sql) I verified, all show in the [Overview ](https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/?last=90)below the chart a blue link with "Weekly Downloads" but there is no daily download data for them in the last 30 days. There is some data for the last 90 days.  

![weekly](https://user-images.githubusercontent.com/33448286/92714414-ddb30e80-f364-11ea-80bb-1f0fdd8d6d49.png)

**Comment by willdurand** [comment]
@ioanarusiczki ok, thanks. -stage doesn't use BQ data yet but we should now have "Weekly downloads" on this page as well.

**Comment by ioanarusiczki** [comment]
@willdurand I checked for both dev and stage using the same guids and it's the same data displayed on both servers.
