### ISSUE TITLE
Remove `total_downloads` DB column in addons table

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15446]
Once https://github.com/mozilla/addons-server/issues/15444 lands, we can add a migration to remove the actual DB column but it should be done in a different patch.

For QA: there should be NO noticeable changes. This value was only used in the stats overview but this has been changed last week to show Weekly Downloads instead.

**Comment by ioanarusiczki** [comment]
@willdurand Nothing broken, download stats are loading on AMO dev - FF80(Win10). 
I've noticed some issues with the custom ranges so I'll test around that tomorrow.
