### ISSUE TITLE
Don't rely on resolve(url).func comparison in get_absolute_url()

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15459]
sentry-sdk 0.16.4 wraps views returned by django's url resolver with its own to add some instrumentation. This breaks any direct comparisons between `resolve(url).func` and the function. We had that in our `<ModelBase>.get_absolute_url()` implementation, and this breaks with that version of the sentry sdk (or higher).

See https://github.com/mozilla/addons-server/pull/15453

**Comment by AlexandraMoga** [comment]
I didn't find issues with the links pointing to to add-on detail pages from DevHub, Rev Tools or Admin tools.

I'm marking this issue as verified fixed on -dev.
