### ISSUE TITLE
Remove `?src=` in download urls (files)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15454]
We append a `src` query parameter to all file urls. We don't need this anymore as we are going to use UTM query params instead but not on the file urls themselves.

**Comment by AlexandraMoga** [comment]
I was able to download files from DevHub, Rev Tools and Admin tools, which, I think, are the areas affected by this issue.
I filed #15479 as a follow up, but I'm not sure that it is indeed a regression from this patch.
