### ISSUE TITLE
Use `(none)` instead of `Unknown` in download stats

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15461]
We'd like to use `(none)` instead of `Unknown` in download stats data.

**Comment by ioanarusiczki** [comment]
@willdurand 

- I found an example where I have both "none" and "Unknown" in all of the Downloads categories: by Source, Medium, Content and Campaign. 

https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/downloads/sources/?last=7

- The other samples look good meaning that only (none) is displayed: 

https://addons-dev.allizom.org/en-US/firefox/addon/statistics-reloaded/statistics/downloads/campaigns/?last=30
https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/downloads/sources/?last=30
https://addons-dev.allizom.org/en-US/firefox/addon/private-relay/statistics/downloads/mediums/?last=30

**Comment by willdurand** [comment]
>     * I found an example where I have both "none" and "Unknown" in all of the Downloads categories: by Source, Medium, Content and Campaign.
> 
> 
> [addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/downloads/sources/?last=7](https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/downloads/sources/?last=7)

mm, maybe hard-refresh this page? Looks like a caching issue.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, I reloaded the page this morning. There's just (none) displayed. 
Verified on dev - FF80(Win10).
