### ISSUE TITLE
add meta promoted=badged group in addons api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15468]
Currently if a consumer of the addons api (e.g. addons-frontend) wants to filter by all add-ons that are supposed to badged (exposed as being reviewed by Mozilla) it has to know which promoted groups have that property and then specify all of those groups as `?promoted=recommended,verified,sponsored,line`.  If we have a `?promoted=badged` filter then the consumer of the api can make a simpler query that isn't dependent on identical logic being maintained on addons-server and addons-frontend.

**Comment by ioanarusiczki** [comment]
@eviljeff I receive a 200 status for the requests:
https://addons-dev.allizom.org/api/v5/addons/search/?appversion=80.0.1&app=firefox&promoted=badged

https://addons-dev.allizom.org/api/v5/addons/search/?appversion=80.0.1&app=firefox&promoted=recommended,verified,sponsored,line

with the same number of compatible addons. 
Verified on dev.
