### ISSUE TITLE
Update the logic for random sort to use promoted rather than recommended

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#15462]
There is some logic in [`filter_queryset` in `SortingFilter`](https://github.com/mozilla/addons-server/blob/master/src/olympia/search/filters.py#L900-L926) which is designed to protect against a sort of `random` being requested without an accompanying `featured` or `recommended` param. This logic should be updated to look for the `promoted` param, rather than the `recommended` param.

**Comment by ioanarusiczki** [comment]
@eviljeff I did not start to verify this issue yet but I see on frontend errors, homepage won't load. It throws an error 

![error on frontend](https://user-images.githubusercontent.com/33448286/93055119-1c9dd880-f673-11ea-8136-02687b17464b.png)

Could this be causing it?

**Comment by eviljeff** [comment]
@ioanarusiczki the `recommended=True` param was removed with #15467 - @bobsilverberg said it wasn't used so maybe there's a PR that's just waiting to be merged on the addons-frontend side?

(Looks like I forgot to to update the error message to not mention `recommended` though)

**Comment by ioanarusiczki** [comment]
@eviljeff I think the frontend depends on https://github.com/mozilla/addons-frontend/issues/9615 so we're waiting for now. 

The API response returns a 200 status for the following requests: 

https://addons-dev.allizom.org/api/v4/addons/search/?promoted=recommended&sort=random&type=extension
https://addons-dev.allizom.org/api/v4/addons/search/?promoted=recommended&sort=random&type=statictheme

I also tested the responses for all promoted categories and I received a 200 response. 

Examples:
https://addons-dev.allizom.org/api/v4/addons/search/?promoted=line&sort=random&type=extension
https://addons-dev.allizom.org/api/v5/addons/search/?promoted=strategic&sort=random&type=extension
https://addons-dev.allizom.org/api/v5/addons/search/?promoted=sponsored&sort=random
https://addons-dev.allizom.org/api/v4/addons/search/?promoted=verified&sort=random&type=language

**Comment by bobsilverberg** [comment]
Now that https://github.com/mozilla/addons-frontend/pull/9621 has landed, the homepage issues should be fixed.
