### ISSUE TITLE
remove recommended=true filter from addons api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15467]
we have a `?promoted=recommended` filter (#15272) to replace `?recommended=true` filter, and we've already removed `is_recommended` from the detail response (#15271).  If/once addons-frontend has stopped relying on the recommended=true filter we can drop this too.

**Comment by eviljeff** [comment]
@bobsilverberg is anything blocking this on addons-frontend currently?

**Comment by bobsilverberg** [comment]
> @bobsilverberg is anything blocking this on addons-frontend currently?

https://github.com/mozilla/addons-frontend/pull/9621 removes our dependence on `recommended=true`, and its two dependencies are fixed, so other than awaiting review I don't think there's anything else blocking this.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- requests such as 
https://addons-dev.allizom.org/api/v4/addons/search/?recommended=true&sort=random&type=statictheme
https://addons-dev.allizom.org/api/v4/addons/search/?recommended=true&sort=random&type=extension 
return a 400 bad request with the message 
`The \"sort\" parameter \"random\" can only be specified when the \"featured\", \"promoted\", or \"recommended\" parameter is also present, and the \"q\" parameter absent.` (the message is going to be updated)

- requests with the other sort parameters such as 
https://addons-dev.allizom.org/api/v4/addons/search/?recommended=true&sort=users&type=extension (same with sort=rating updated or hotness) will return a 200 response but the number of add-ons listed is 3029 (should be ~46). It looks like the recommended=true is being ignored. 
Let me know if that's expected or it should be a 400 with a message instead?

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff
> 
>     * requests such as
>       https://addons-dev.allizom.org/api/v4/addons/search/?recommended=true&sort=random&type=statictheme
>       https://addons-dev.allizom.org/api/v4/addons/search/?recommended=true&sort=random&type=extension
>       return a 400 bad request with the message
>       `The \"sort\" parameter \"random\" can only be specified when the \"featured\", \"promoted\", or \"recommended\" parameter is also present, and the \"q\" parameter absent.` (the message is going to be updated)

yep, it's a 400 because it's now an invalid use of `sort=random`

>     * requests with the other sort parameters such as
>       https://addons-dev.allizom.org/api/v4/addons/search/?recommended=true&sort=users&type=extension (same with sort=rating updated or hotness) will return a 200 response but the number of add-ons listed is 3029 (should be ~46). It looks like the recommended=true is being ignored.
>       Let me know if that's expected or it should be a 400 with a message instead?

it's expected - once it's removed it should be the same as passing any other unknown parameter `?foo=baa` to the search api - i.e. it's silently ignored.
