### ISSUE TITLE
Admin activity log is broken (again)

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15479]
### Describe the problem and steps to reproduce it:
Open the Admin activity log at https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/

### What happened?
A 500 server error

### What did you expect to happen?
The activity log page is opened

### Anything else we should know?
Last time the activity log was broken it had something to do with files and the removal of the legacy file viewer - see #15291. The only closed issue that touched files now is #15454 I think?

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/9584766/

It *is* caused by the removal of the `src` parameter. Annoyingly, we didn't have a test covering that error - we should!

**Comment by AlexandraMoga** [comment]
The activity log can be opened now. This issue is verified fixed.
