### ISSUE TITLE
Hide download stats links when add-on is purely unlisted

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15487]
We don't have download stats data for purely unlisted add-ons (or any unlisted versions). Let's hide those links when add-on is purely unlisted because they are not very useful. When an add-on has some listed versions (at least one), then we should display the links.

**Comment by ioanarusiczki** [comment]
@willdurand 

2 aspects noticed:

- for an unlisted add-on there are no downloads shown but there's still the URL which redirects to them in the overview. 

![no url](https://user-images.githubusercontent.com/33448286/93325725-68da4b80-f820-11ea-8f74-89c5ae2d2260.gif)

- the scenario: when the listed version is deleted and the unlisted remains the downloads will be shown. 

Example: https://addons-dev.allizom.org/en-US/firefox/addon/statistics-reloaded/statistics/?last=7

**Comment by willdurand** [comment]
> for an unlisted add-on there are no downloads shown but there's still the URL which redirects to them in the overview.

yeah, that's normal. It does not really matter in this case.

> the scenario: when the listed version is deleted and the unlisted remains the downloads will be shown.

Yes because there could be data from the past.

**Comment by ioanarusiczki** [comment]
@willdurand Ok, then it is verified on dev - FF80(Win10).
