### ISSUE TITLE
Show advanced properties in theme review queue 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#15491]
Pam mentioned that since Firefox Color now supported advanced theme properties, she is seeing more themes submitted to AMO that look like duplicates except for tweaks to advanced properties (such as sidebar colors), which she can't see in the review queue. Theme reviewers look for duplicate submissions to make sure designers aren't spamming AMO with multiple submissions of the same theme, so the reviewers are seeing a lot of false positive duplicates.

I'd like to add this issue to future work updating the AMO theme generator to handle more properties. It'd be great if the reviewers could see changes to those properties in the queue. 

In the meantime, is there anything we can do to help the theme reviewers tell when a theme's advanced properties have been modified?

**Comment by jvillalobos** [comment]
The sidebar example you gave demonstrates how the preview can't really cover everything. Trying to show a whole browser window, popups, etc. wouldn't work with the current design of the preview image.

One possible solution would be to list all non-default properties in the review tools, so reviewers can at least compare review pages. The other would be to be more lenient about duplicates.

**Comment by caitmuenster** [comment]
> One possible solution would be to list all non-default properties in the review tools, so reviewers can at least compare review pages. 

That sounds good to me! Agreed that we won't be able to cover all of the advanced properties in the preview.
