### ISSUE TITLE
Add GitHub Sponsor to contributors domain

### ISSUE THREAD

**Issue by conema** [mozilla/addons-server#15497]
As discussed in PR #15471, it will be a nice thing if GitHub Sponsor was added to the list of accepted contributors domain. As noted by @eviljeff and @jvillalobos , it's annoying that there isn't a specific (sub)domain for GitHub Sponsor, since it could lead to phishing attempt. 
So, other than adding the domain to the accepted contributors list, there is also the need to expand the list of domains to require specific paths and not only specific domains.

**Comment by jvillalobos** [comment]
The easy/ugly way out of this would be to special-case the github domain and only allow it to be used if it matches `github.com/sponsors/`. The more robust solution would be to switch to regular expressions for the URL matching. That makes the messaging in DevHub a bit less user-friendly, but it shouldn't be too bad.

@diox do you have a preference? We can make this `contrib: welcome` if we have a preferred approach.

**Comment by diox** [comment]
Current validation for reference:
https://github.com/mozilla/addons-server/blob/7350c6e6eb73e4641b0088e32ab7111cb9f58ecc/src/olympia/devhub/forms.py#L343-L350

I think the path validation special-case for github, while not the most elegant, is going to be the simplest to implement for a contributor. They can add `github.com` to the domains and then validate the `path` from `urlsplit`.

**Comment by rochisha0** [comment]
I'll like to work on this @jvillalobos @diox !

**Comment by jvillalobos** [comment]
@rochisha0 feel free to take it

**Comment by ioanarusiczki** [comment]
@bobsilverberg Works for me - verified on AMO dev with FF81(Win10). 

![github added at contrib](https://user-images.githubusercontent.com/33448286/94920288-b01e3880-04be-11eb-8b54-9d0987c3a126.gif)
