### ISSUE TITLE
User with removed 2FA enforcement is still asked for 2FA code at login

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15505]
### Describe the problem and steps to reproduce it:
1. Add a user to one of the active Reviewer groups (choose a user that is not also a developer)
2. Add the user Id to the list of users with enforced 2FA via this [waffle flag](https://addons-internal.dev.mozaws.net/en-US/admin/models/waffle/flag/20/change/)
3. Log in with this user account and complete the 2FA set up
4. Make sure that you are logged in successfully and then Log out
4. Remove the user from the Reviewer group
5. Log in again with this user

### What happened?
You are asked to enter a 2FA code to proceed to log in

### What did you expect to happen?
2FA should no longer be required since the user doesn't belong to any restricted group

### Anything else we should know?
- I've also removed the user from the [waffle flag](https://addons-internal.dev.mozaws.net/en-US/admin/models/waffle/flag/20/change/) but 2FA enforcement still persisted at log in 
- users: [10642099](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642099/change/), [10642098](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642098/change/) 
- this will also reproduce with former developer accounts, for example a user who transferred add-on ownership to another user

@diox I understand that the 2FA requirement is stored at the FxA level, so even if I remove the enforcement from AMO, this will not also remove it from FxA. I suppose this is still something that needs to be implemented, or will we continue to ask 2FA from users that are no longer meeting the enforcement conditions, i.e. are not developers and do not belong to a special group?

**Comment by diox** [comment]
This is fine. The enforcement requires developers (and "special" users) to set it up on their FxA account, but it's then applied to the FxA account regardless of the situation, even if they are not an AMO developer/special user anymore. In fact it would continue to apply even if they delete their AMO account.
