### ISSUE TITLE
Replace URLValidatorBackport with URLValidator

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15507]
We have a class called `URLValidatorBackport` which is a backport of django's `URLValidator` from a time a change we wanted wasn't in the version of django we were using. It's been integrated into django releases a while ago, so we should remove our custom class and use django's `URLValidator` instead.

**Comment by rochisha0** [comment]
Hi! I would like to work on this issue. Can you give more details on it?

**Comment by diox** [comment]
The description should give you enough details, provided you're familiar with Python. [Install addons-server]( https://addons-server.readthedocs.io/en/latest/topics/install/index.html), look for `URLValidatorBackport` in the code and remove that class, changing all code referencing it so that it uses `URLValidator` from django instead (don't forget to change the imports)

**Comment by diox** [comment]
QA: make sure places in devhub where developers set URLs (homepage, support url, contributions url) still work and handle errors correctly.

**Comment by ioanarusiczki** [comment]
@diox Looks good to me. I verified on AMO stage - FF80(Win10).
