### ISSUE TITLE
Received an empty response from the server; status: 0

### ISSUE THREAD

**Issue by ebkhalilzadeh** [mozilla/addons-server#15517]
I tried submitting the new version of my extension for signing but got a strange error in response. Tried it multiple times and got the same response. There were some warnings and 1 notice in the lint report, but no error. There also were two warnings related to a bug in linter which I reported separately.

I also tried to re-submit the old version of my extension that was submitted successfully. I got the same error for that one as well.

Here is my extension:
[swash-1.1.6.zip](https://github.com/mozilla/addons-linter/files/5176998/swash-1.1.6.zip)

and the linter log file:
[lint.log](https://github.com/mozilla/addons-linter/files/5177002/lint.log)

And also the screenshot of the error I see every time I try:
![Snag_7ba96e1f](https://user-images.githubusercontent.com/58162558/92285918-cfa35f00-ef1a-11ea-8163-4f736273c878.png)

**Comment by willdurand** [comment]
This could be a problem with your Internet connection (because of the "status: 0"). Is this still a problem for you @ebkhalilzadeh?

**Comment by eviljeff** [comment]
closing because it's been a month.  Please comment/reopen if it's still a problem
