### ISSUE TITLE
Addon validation not completing on -dev when post-request-task is enabled

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1552]
We found that add-on validation was not completing on -dev when there were no errors. We made a wild guess that it was related to https://github.com/mozilla/olympia/issues/1449, any chance you could check this is the case before we push this up to stage?

**Comment by diox** [comment]
post-request-task has been disabled as a result, need to find a solution for this to re-enable it.

It was working fine locally, but on -dev the validation task never seems to triggered normally. Because of the way post-request-task works and does things once the request is finished the error is not shown in sentry, but appears in newrelic:

```
exceptions:AttributeError: 'NoneType' object has no attribute 'prepare_message'

Traceback (most recent call last):
"/data/olympia/venv/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 753, in close
"/data/olympia/venv/lib/python2.7/site-packages/django/http/response.py", line 305, in close
"/data/olympia/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
"/data/olympia/venv/lib/python2.7/site-packages/post_request_task/task.py", line 54, in _send_tasks_and_stop_queuing
"/data/olympia/venv/lib/python2.7/site-packages/post_request_task/task.py", line 95, in original_apply_async
"/data/olympia/venv/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
"/data/olympia/venv/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
"/data/olympia/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
"/data/olympia/venv/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
"/data/olympia/venv/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
"/data/olympia/venv/lib/python2.7/site-packages/kombu/messaging.py", line 178, in _publish
```

**Comment by EnTeQuAk** [comment]
@diox I wonder, given that we didn't tackle that for quite some time now, if we'd delay that till we upgrade to Django 1.11 and just use the official signals?

**Comment by diox** [comment]
Even with `on_commit` we'll need some kind of wrapper around tasks... that wrapper will probably be post-request-task and will have the same issues we ran into earlier, I think.

**Comment by diox** [comment]
Also, I suspect the lack of post-request-task is causing weird bugs like https://github.com/mozilla/addons-server/issues/5588

**Comment by diox** [comment]
We successfully enabled post-request-task in dev/stage/prod in #5999, not running into this bug, which we suspect was something wrong with the version of kombu we were using at the time.
