### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15525]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9179328/?referrer=github_plugin

```
TypeError: 'NoneType' object is not subscriptable
  File "olympia/amo/decorators.py", line 108, in wrapper
    return f(*args, **kw)
  File "olympia/addons/tasks.py", line 273, in update_addon_hotness
    this = average['avg_this_week']
```

---

Looks like the `addon` does not have a GUID for some reasons..

**Comment by willdurand** [comment]
I see two add-ons that are affected:

- https://addons.mozilla.org/api/v4/addons/addon/659430/
- https://addons.mozilla.org/api/v4/addons/addon/3036/

**Comment by eviljeff** [comment]
> Looks like the `addon` does not have a GUID for some reasons..

those addon's have GUIDs in the API detail response (which are database fetched) - where are you seeing a none value for `.guid`?  

I'm more confused how the `Addon.objects.filter(guid__in=averages.keys())` can return addons that don't have guids in `averages.keys` - id 3036 is in addons but doesn't have a matching GUID.  And there's only 9 items in `averages` but more than 9 objects in addons before sentry snips the ouput.

**Comment by willdurand** [comment]
> those addon's have GUIDs in the API detail response (which are database fetched) - where are you seeing a none value for `.guid`?

In Sentry. Hopefully we'll see some more info in the logs next week.

**Comment by eviljeff** [comment]
> In Sentry. Hopefully we'll see some more info in the logs next week.

link?  The link in the first comment doesn't show an `addon.guid` being `None`.

**Comment by willdurand** [comment]
> I'm more confused how the `Addon.objects.filter(guid__in=averages.keys())` can return addons that don't have guids in `averages.keys` - id 3036 is in addons but doesn't have a matching GUID. And there's only 9 items in `averages` but more than 9 objects in addons before sentry snips the ouput.

Is Sentry accurate? There should be more than 9 objects in `averages` and I thought it was because of Sentry. I kinda hate that we don't see everything...


> link? The link in the first comment doesn't show an `addon.guid` being `None`.

Right, I cannot find why I thought there was no GUID anymore..

**Comment by willdurand** [comment]
Part of the issue has been fixed last week by adding more logs and a `continue` in case of a missing `average` entry. We can now see that only one add-on has been impacted since then: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9659368/events/. Looking at the BigQuery data for this add-on, we have the same GUID with different cases, which would explain the underlying problem.

**Comment by willdurand** [comment]
It seems to be only one add-on so far and BigQuery has a GUID for it that has a different case than the one we store in our DB. Not sure why BigQuery has this kind of GUID, though.

**Comment by eviljeff** [comment]
@willdurand is this fixable?

**Comment by eviljeff** [comment]
Sentry issue: [OLYMPIA-PROD-NBS](https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9659368/?referrer=github_plugin)
