### ISSUE TITLE
Integrate curlylint for template linting

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15535]
https://pypi.org/project/curlylint/

We don't have any linting for templates currently so we're dependant on functional tests not returning template errors in their response which is fine... but something specific would be better.  Curlylint also claims to check for accessibility which is worthwhile to add.

I gave it a quick try and it found 15 errors in our templates - mainly in devhub.

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa. 
Thanks!

**Comment by eviljeff** [comment]
QA:
there have been fixes to a number of templates but they're mainly trivial (like adding a closing html tag).  Some places I had to rewrite the template slightly so are worth double-checking:
- addon submission flow "upload" step - the compatible app selector widget
- addon submission flow "describe" step for listed submission - for both themes and non-themes - particularly the license selector
- addon submission flow "done" step - the go to submissions link - for both themes and non-themes
- submission theme wizard - the theme properties
- ratings link (with stars) shown on devhub and reviewer tools review page
- "About tracking external sources"  link on stats dashboard

**Comment by ioanarusiczki** [comment]
@eviljeff I did not finish testing all the areas but I see at the theme wizard some changes: 

Now on dev/stage 

![the wizard on stage](https://user-images.githubusercontent.com/33448286/94689465-930b2d80-0337-11eb-8aad-16e3cf4454d5.png)

Before

![the wizard on prod](https://user-images.githubusercontent.com/33448286/94689493-9acad200-0337-11eb-97ad-00936ef614d7.png)

**Comment by ioanarusiczki** [comment]
@eviljeff I filed https://github.com/mozilla/addons-server/issues/15603 for my comment above and I've been going through all the features you've mentioned but except what I've already noticed the rest should be fine. 
I'm going to take one more look tomorrow at the dev hub release testing.
