### ISSUE TITLE
remove `autograph_promoted_signer` waffle switch

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15536]
we added `autograph_promoted_signer` while autograph support for the new promoted states was awaiting deployment.  Now Autograph support the new states, and we've enabled it on AMO prod, there's no reason we'd want to go back.

**Comment by ioanarusiczki** [comment]
@eviljeff Looks like regression testing to me. I'll take a look at the signatures. It should be the results from https://github.com/mozilla/addons-server/issues/15315

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this on AMO stage with FF80(Win10). 
- Recommended addons: "states":["recommended-android"], "states":["recommended","recommended-android"] or 
 "states":["recommended"]
- Sponsored  and Verified addons: "states":["verified"]  
- By Firefox addons: "states":["line"]
- Not Promoted, Spotlight or Strategic add-ons don't receive a `mozilla-recommendations.json` file.
