### ISSUE TITLE
Remove Send from Dev Hub's footer

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15547]
As a followup for https://github.com/mozilla/addons-frontend/issues/9649

`Send` should be removed from Dev Hub's footer too, see https://github.com/mozilla/addons-frontend/issues/9649#issue-702919138

![the dev hub send](https://user-images.githubusercontent.com/33448286/93877749-9bcd8500-fce1-11ea-9fee-9d1c32e7d4ba.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg Hah, I filed it on frontend :)) Thanks for the transfer 👍

**Comment by rochisha0** [comment]
Hi @ioanarusiczki ! I have created a patch, please check!

**Comment by rochisha0** [comment]
@eviljeff I'm having trouble rebasing my repository and removing old commits. Can you point me to a few resources for the same?

**Comment by diox** [comment]
@rochisha0 you didn't need to close the pull request. What you want to look for to remove old commits is tutorials about "squash".

**Comment by bobsilverberg** [comment]
@imsahil007, thanks for the patch! It looks like @rochisha0 was already working on this, so we should let them have a chance to finish it off, if they wish to do so.

@rochisha0 Would you like to open another PR to address this issue, or can @imsahil007 take it on?

**Comment by rochisha0** [comment]
It is okay, he can take on.

**Comment by bobsilverberg** [comment]
> It is okay, he can take on.

Ok, thanks @rochisha0!

**Comment by imsahil007** [comment]
> It is okay, he can take on.

Thanks @rochisha0

**Comment by ioanarusiczki** [comment]
@bobsilverberg Send URL has been removed from dev hub. Verified on AMO stage - FF81(Win10).

![Send URl removed](https://user-images.githubusercontent.com/33448286/95325873-74aeb000-08aa-11eb-95e7-b764d4678bba.png)
