### ISSUE TITLE
Number of Daily Users is almost zero despite evidence of a large user base (possibly mobile-specific)

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#15557]
### Describe the problem and steps to reproduce it:
The [statistics dashboard](https://addons.mozilla.org/en-US/firefox/addon/google-search-fixer/statistics/?last=365) (as well as the displayed number of users on the add-on detail page) of https://addons.mozilla.org/en-US/firefox/addon/google-search-fixer/ seems to be entirely off. There are 890 reviews (including recent ones) and almost 150k reported downloads over the past year, yet the number of "daily users" has been hovering around a few dozen, with small bumps in August (coinciding with the Fenix release, possibly due to add-ons being disabled at the initial migration) and a steep ongoing climb since the begin of September (possibly because it was added to [the collection for Fenix Nightly](https://addons.mozilla.org/api/v4/accounts/account/mozilla/collections/83a9cccfe6e24a34bd7b155ff9ee32/addons/)?).

### What happened?
The statistics page shows between 10 - 60 daily users until 1 aug, and a spike in number of users since 1 sep.

### What did you expect to happen?
I expect a realistic number of users.

### Anything else we should know?
This add-on is specific to Firefox for Android. It might be that telemetry data from Fennic is missing. I'm reporting this in case it's a wider issue. Also note that almost every add-on is disabled on mobile, and the "Daily user" only tracks enabled add-ons. So if any add-on author wants to make decisions on support for mobile add-ons based on historical data in the statistics dashboard, then they don't have any way to do so because of this bug.

Screenshot of https://addons.mozilla.org/en-US/firefox/addon/google-search-fixer/statistics/?last=365 :
![Screenshot](https://user-images.githubusercontent.com/1365071/94013648-a99b0d00-fdaa-11ea-9cfd-f30ee688bbe3.png)

**Comment by jvillalobos** [comment]
As discussed on Slack and mentioned in the [announcement](https://blog.mozilla.org/addons/2020/06/10/improvements-to-statistics-processing-on-amo/), Fennec isn't being counted in the usage stats. We also don't intend to change that, so I don't think we can do anything here. You can find a relatively recent number in [the Wayback Machine](https://web.archive.org/web/20200206035232/https://addons.mozilla.org/en-US/firefox/addon/google-search-fixer/), if that helps.
