### ISSUE TITLE
Upgrade to django's JSONField

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15559]
django 3.1 introduces a built-in JSONField (replacing the many JSONField packages out there, including the one we use -`django_extensions.db.fields.json.JSONField`).  It's available as back-port https://github.com/laymonage/django-jsonfield-backport so we can upgrade this feature now before we upgrade addons-server to the next django LTS (3.2).

**Comment by ioanarusiczki** [comment]
@eviljeff In case I can test around, please add some str. 
Thanks!

**Comment by eviljeff** [comment]
@ioanarusiczki it should be a transparent change so I don't think there's any specific STR here.  

Tables/models updated include previews (for both extensions and themes); blocklist submissions (not the blocks); permissions for files; auto-approvals; scanner results - so something to bear in mind during general/other testing.
