### ISSUE TITLE
Take PromotedApproval.application into account when determining if an add-on is promoted

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15569]
spun off from #15363

Taking application into account makes the logic in a few places more complicated because on some occasions we're asking "is this addon promoted for a specific group and approved for any application", in others it's "is this addon promoted for a specific group and approved for a specific application" or it could be "is this addon promoted for a specific group and approved for all applications that we've defined in when making the addon promoted".

The main entry point to promoted status is `Addon.promoted_group` which supports an `application` kwarg (that will possibly need enhancing to differentiate between "all" and "any"), but there other places where Addon.promotedaddon is queried directly (e.g. the API indexing/serializer) so care needs to be taken there too.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I don't think the promoted admin functionality has been affected. 
- the issues reported https://github.com/mozilla/addons-server/issues/15654 are no longer reproducible. 

If there's any specific detail I should check on, please let me know.
