### ISSUE TITLE
Store and expose scanner query result start and finished date

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15567]
For admins, it's sometimes useful to see when a scanner query rule was started and when it finished. It would be great if we could store that for each scanner query rule and expose it on the django admin scanner query rule page.

**Comment by ioanarusiczki** [comment]
@diox I can see in admin a new column on the scannerqueryrule page "Created". Should I also see a "Completed" or Finished" column?

**Comment by diox** [comment]
It's not a new column, it will be displayed next to the state when the state is "Completed".

**Comment by ioanarusiczki** [comment]
@diox Thanks, I ran a [task](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerqueryrule/39/change/). 
There's a "Created" column available and also the date and time of the completed task available in "State". 
Verified on dev - FF81(Win10).
