### ISSUE TITLE
Pass bytes to yara instead of string

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15574]
We are decoding the bytes in add-on files before sending them to yara. That can lead to problems. Let's not decode them and send the bytes to yara directly.

**Comment by ioanarusiczki** [comment]
@wagnerand Can qa test around this issue? Please add some str

**Comment by wagnerand** [comment]
I am not sure how to properly test this beyond what I already did to develop this patch. If anyone has ideas, please add them here.

**Comment by wagnerand** [comment]
@ioanarusiczki is testing this, based on the automated test that came with the patch.

**Comment by ioanarusiczki** [comment]
@wagnerand I sent my test results via Element. Let me know if there's anything else I can do. 
Thanks!
