### ISSUE TITLE
Collections Depreciation in Python 3.10

### ISSUE THREAD

**Issue by Metropass** [mozilla/addons-server#15577]
An example of where Collections is used:
https://github.com/mozilla/addons-server/blob/b3a9b1f297dccc9b9408905e8f0e050c638a8262/src/olympia/constants/permissions.py#L1

Python will completely remove `collections` when Python 3.10 is released, we should talk about alternatives so that the Python scripts won't crash.

[Here's the notice, on the `collections` documentation](https://docs.python.org/3/library/collections.html)

**Comment by diox** [comment]
The way I understand it, the only classes that will no longer be available through `collections` are the [Collection Abstract Base Classes](https://docs.python.org/3.6/library/collections.abc.html#collections-abstract-base-classes) and they just moved to `collections.abc`. I haven't checked thoroughly, but I don't think we use any of those, so this is likely not going to cause any problems.

**Comment by eviljeff** [comment]
I can't see we use any abstract collections classes - only the concrete ones (namedtuple, defaultdict, OrderedDict, Counter).

Please follow-up if I've missed something during the code search though.
