### ISSUE TITLE
Incorrect points are added after server timeout

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#1557]
This is not a new bug at all and has been present for a longish time.

When posting the first review for a Full Review (120 points) if the server times out, no points will be added and addon will remain unreviewed. However, when reposting the review, Olympia adds 80 points (ie as a Pending Update).

This is a separate bug from the bug that causes loss of points altogether, or the bug the deducts points (both of which are still outstanding). 
[Review Points System deducting](https://github.com/mozilla/olympia/issues/1554)
[Review Points System deducting](https://bugzilla.mozilla.org/show_bug.cgi?id=1205986)

**Comment by EnTeQuAk** [comment]
adding this to "triaged" since I believe this is a bug that should be fixed but isn't that easy so it might take some time before anyone can actually look deep enough into that since we're working on quite a few other things currently.

**Comment by EnTeQuAk** [comment]
Is this still a problem? Might it have been fixed with our activation of django-post-request-task and other fixes to the reviewer tools? Did you notice this recently?

**Comment by erosman** [comment]
I haven't noticed it recently.

**Comment by muffinresearch** [comment]
> I haven't noticed it recently.

Closing based on this.
