### ISSUE TITLE
Import include() function from django.urls 

### ISSUE THREAD

**Issue by Sparsh-Bansal** [mozilla/addons-server#15616]
Import include() function from new django.urls instead of old django.conf.urls in all the required urls.py files

This will remove one extra line from all the files(more consistent code) and also use the new way to import the include() function in Django-2.x
https://docs.djangoproject.com/en/3.1/ref/urls/#include

**Comment by eviljeff** [comment]
if the old location of `include` is deprecated in Django 3.2 then we'll have to do this before then.  We'd appreciate a link to documentation that mentions the deprecation timeline though.

**Comment by Sparsh-Bansal** [comment]
https://docs.djangoproject.com/en/2.1/ref/urls/#include (This may be useful) . The older version django.conf.urls.include() (BEFORE DJANGO 2.1) still works for backward compatibility but would be removed anytime . It is better to use the new django.urls.include() for DJANGO >= 3.x.

**Comment by imsahil007** [comment]
Do I need to be assigned for this or is it open for everyone?

**Comment by Sparsh-Bansal** [comment]
@imsahil007  I am working on it . Thank you
