### ISSUE TITLE
Include add-ons based on the collections endpoint/criteria in the homepage shelves API

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#15614]
Supports #14871

Implement collections type in the homepage shelves API to include add-ons based on the collections endpoint/criteria

**Comment by ioanarusiczki** [comment]
@xlisachan 
On AMO dev: 
I could add Mozilla collections to /admin/models/discovery/shelfmodule/
I could attach them to admin/models/discovery/homepageshelves/

Then I verified the response for https://addons-dev.allizom.org/api/v5/shelves/ and the enabled collections were returned into the response - each collection shows 4 add-ons but that's been discussed into https://github.com/mozilla/addons-server/issues/16367#issuecomment-768971779
