### ISSUE TITLE
No Exception handling in olympia.zadmin.models.set_config() method

### ISSUE THREAD

**Issue by Sparsh-Bansal** [mozilla/addons-server#15613]
Bug in olympia.zadmin.models.set_config() method
https://github.com/mozilla/addons-server/blob/master/src/olympia/zadmin/models.py

If model Config does not exist , it raises an Model.DoesNotExist error
https://docs.djangoproject.com/en/3.0/ref/models/class/#doesnotexist

Exception handling can be used to overcome this error.

Changed Code :->
```
def set_config(conf, value, *, json_value=False):
    try:
        cf, created = Config.objects.get_or_create(key=conf)
        cf.value = (value if not json_value else json.dumps(value))
        cf.save()
    except Config.DoesNotExixst:
        print('Config object does not exist')
```

**Comment by diox** [comment]
We're using `get_or_create` precisely to avoid this already. Unless you have specific steps to reproduce this, I don't see a bug here.
