### ISSUE TITLE
Add proxy for Adzerk click URLs

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15619]
Like #15618 but for click URLs.

**Comment by diox** [comment]
Per https://github.com/mozilla/addons-frontend/issues/9721#issuecomment-704144211 it will likely need to behave like this:
- Accept `POST` with the URL somewhere in post data
- Request that URL via `GET`
- Don't need to return anything (client won't follow that redirect, the response can be discarded)

**Comment by ioanarusiczki** [comment]
@eviljeff 
I made a POST request on https://addons-dev.allizom.org/api/v4/shelves/sponsored/click/. I tested it for all 6 add-ons returned by GET https://addons-dev.allizom.org/api/v4/shelves/sponsored/ and the response is a 202 Accepted for processing status.

The click_data generated expires after one hour -> I get a 400 Bad request with "Bad click_data: Signature age 4777.010764360428 > 3600 seconds" which is the expected in this case. The same happens with impression_data after 60 seconds (verified in https://github.com/mozilla/addons-server/issues/15618)
