### ISSUE TITLE
Add API documentation for homepage shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#15615]
Supports #14871
Dependent on #15614

Add API documentation for homepage shelves that outlines the data returned upon enabling a shelf to appear on the AMO homepage.

**Comment by eviljeff** [comment]
fwiw, it should be added to https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html with the other shelf related apis.

**Comment by ioanarusiczki** [comment]
@eviljeff

- The -dev API https://addons-dev.allizom.org/api/v4/shelves/ is returning the list of [enabled ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/) shelves as described https://github.com/mozilla/addons-server/pull/16087#issuecomment-744572067

- I don't see the description [mentioned](https://github.com/mozilla/addons-server/pull/16087#issuecomment-744572067) of the homepage shelf available in the docs https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html# and I can't tell if that's ok.

**Comment by eviljeff** [comment]
>     * I don't see the description [mentioned](https://github.com/mozilla/addons-server/pull/16087#issuecomment-744572067) of the homepage shelf available in the docs https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html# and I can't tell if that's ok.

the readthedocs build process is currently broken, so that's expected for now.

**Comment by eviljeff** [comment]
@ioanarusiczki readthedocs builds are working again fwiw
