### ISSUE TITLE
Add proxy for Adzerk impression URLs

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15618]
As mentioned in https://github.com/mozilla/addons-server/issues/15617 we'll want to proxy Adzerk's impression and click URLs through addons-server views we control, hiding client IPs from Adzerk.

**Comment by diox** [comment]
Open questions to check:
- Validate that the call came from a sponsored shelf, by including a token in sponsored shelf API and checking it? I don't think we need to do that, it's probably Adzerk responsibility.
- One API call for a single shelf or separate ones ? If a single call, it then needs to call multiple Adzerk impressions. Partially driven by how impressions are going to be implemented in addons-frontend

**Comment by bobsilverberg** [comment]
Personally, I think having frontend make one call, with a payload of multiple ids/urls, and then having the server make multiple calls to the Adzerk API, is preferable.

**Comment by diox** [comment]
IMHO we shouldn't store anything on addons-server to handle the single call - maybe just passing around the URLs is fine, we could add a signature on top to make sure we generated that (we could even verify the date it was generated)

**Comment by eviljeff** [comment]
> IMHO we shouldn't store anything on addons-server to handle the single call

Agreed.  We don't want to have to store and manage some sort of "session" that somehow relates to what addons we served.  If someone particularly wanted to abuse the feature they could just call the sponsored shelf api multiple times rather than calling the impression api.

**Comment by bobsilverberg** [comment]
Fair enough. So the impressionURL that frontend receives from the API will still be a single proxy URL, and it will contain enough data to allow addons-server to subsequently make the 6 impression URL calls back to Adzerk?

**Comment by eviljeff** [comment]
> 
> 
> Fair enough. So the impressionURL that frontend receives from the API will still be a single proxy URL, and it will contain enough data to allow addons-server to subsequently make the 6 impression URL calls back to Adzerk?

that'd be the idea.  Might have to be POST data if we don't want really long urls though - a single impression url is 745 characters long so that's 4,470 for 6 of them (there's a common server and path we could trim off the start but if we add a signature it's more again so it'll still be way over 4k characters long)

**Comment by bobsilverberg** [comment]
We can send data along with a URL using `sendBeacon`, so that sounds like the route to go. I suppose in that case the API response should contain both `impressionURL` and `impressionData`.

**Comment by eviljeff** [comment]
are we ever going to want to return a subset of the impression urls/data?  I.e. does `impressionData` be a JSON list of 6 strings (+ signatures) or can it be any old blob of data that will just be returned as is?

**Comment by bobsilverberg** [comment]
I don't see any reason why it cannot simply be a blob of data that is then used as is in the call to `sendBeacon`. The server will be sending it, and receiving it, so if something else needs to be done with any of the data the server should be able to do it.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I made a POST request for https://addons-dev.allizom.org/api/v4/shelves/sponsored/impression/ using the "impression_data" as form-data with Postman (I took the impression_data from a GET request for https://addons-dev.allizom.org/api/v4/shelves/sponsored/). 

The result is 202:Accepted for processing status, with no other information provided in the body of the response. 

Please let me know if that's the expected result. 
Thanks!

**Comment by eviljeff** [comment]
that's the expected result.  I expect they'll be some further end-to-end testing at some point to make sure the whole system works though
