### ISSUE TITLE
Remove the modifiable actions from the homepage shelves api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15627]
/api/shelves/ is implemented with `viewsets.ModelViewSet` which by default allows create, update, and destroy actions (in addition to listing and retrieving a single shelf).  It's not clear if creating, updating or deleting shelves would work anyway because we've not developed the serializer for those use cases but it's dangerous to have them available.

We should use `viewsets.ReadOnlyModelViewSet` instead, which only provides list and retrieve.  The api feature is still under development and not used on production so no current risk.

cc @xlisachan

**Comment by xlisachan** [comment]
Thanks for the insight, Andrew! I'll make the updates and let you know if I have any questions.

**Comment by eviljeff** [comment]
I can fix this as part of the work I'm doing for #15617 - I'm going to add a `api/v4/shelves/sponsored` endpoint on top of shelves.

**Comment by eviljeff** [comment]
I fixed this with #15617 so closing it.

**Comment by ioanarusiczki** [comment]
@eviljeff Is this also covered by testing for https://github.com/mozilla/addons-server/issues/15617#issuecomment-708289590 ?

**Comment by eviljeff** [comment]
> @eviljeff Is this also covered by testing for [#15617 (comment)](https://github.com/mozilla/addons-server/issues/15617#issuecomment-708289590) ?

not entirely, but it's going to be hard to craft manual inputs to test it.  I'll mark QA-
