### ISSUE TITLE
XPI link in code-search should trigger download, not install

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15646]
Follow-up of #15628, very similar to #8426.

The link to the XPI file in thest code-search result list should trigger a download, instead of an install, for both security and convenience reasons.

If we could fix #8426 together with this issue, it would be of great benefit for all reviewers.

**Comment by AlexandraMoga** [comment]
Also similar to #9303

**Comment by AlexandraMoga** [comment]
The Download file link from the scanner query results is triggering an actual file download now. 

This is verified fixed on -dev.
