### ISSUE TITLE
Cache bust stats data for new download stats

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15657]
Let's update the `STATS_VERSION` to cache bust the stats data when we enable the new download stats in prod.

For QA: this should reset the session cache, which should be updated with the fresh stats data from BigQuery.

**Comment by ioanarusiczki** [comment]
@willdurand 
- there's a statscache key in the session storage displayed.
-  I see data being available for downloads and daily users. 

If there's anything else to check, let me know.
