### ISSUE TITLE
"strict_min_version" strings between "100.0" and "419.0" are considered lower than "42.0"

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15659]
### Describe the problem and steps to reproduce it:
1. Create a new extension with `"strict_min_version"` set to a value between  `100.0` and `419.0` (inclusive) 
2. Submit it on AMO
3. Check the version compatibility in Manage versions page for the add-on after submission

### What happened?
The min version is set to `42.0`

### What did you expect to happen?
The min version should be the one defined in the manifest

### Anything else we should know?
Examples:
https://addons-dev.allizom.org/en-US/developers/addon/min_max_appversion-over-100/versions/1692143
https://addons-dev.allizom.org/en-US/developers/addon/min_max_appversion419/versions/1692145

![image](https://user-images.githubusercontent.com/31961530/95219127-b1709d80-07fd-11eb-9ae1-441931234676.png)

**Comment by diox** [comment]
QA: would be nice to do another round of testing around version numbers in general, trying to see what else you can find now that we made several changes that should make things more robust.

**Comment by AlexandraMoga** [comment]
I've retested around application versions with various version string combinations and couldn't find new issues.
`strict_min_version` is also being correctly detected now.

Some examples:

`strict_min_version`  set to `100.0`
![image](https://user-images.githubusercontent.com/31961530/97297485-ca97c780-185a-11eb-8db2-fdb2fd079255.png)

default `strict_min_version`  if not specified in manifest:
![image](https://user-images.githubusercontent.com/31961530/97298170-b6a09580-185b-11eb-8d8a-dccbca6d905b.png)

@diox  you mentioned in https://github.com/mozilla/addons-server/issues/10864#issuecomment-475174698 that an appversion 
 set to `1000.*`  is expected to fail during validation. Does this still apply, even if the version exists in https://addons-dev.allizom.org/en-US/firefox/pages/appversions/?

**Comment by diox** [comment]
`1000` is beyond the acceptable range the linter has, even if the version exists. That comment still applies.
