### ISSUE TITLE
Replace email based checks for add-ons with permission checks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15655]
We have 3 different checks done at submission time that are tied to the email address of the user uploading the add-on:
- `system_addon_submission_allowed()`, which allows you to submit an add-on with a `guid` ending with a reserved suffix
- `mozilla_signed_extension_submission_allowed()`, which allows you to submit an add-on already signed with an internal Mozilla certificate
- `skip_trademark_check` inside `verify_mozilla_trademark()` which allows you to submit an add-on with a name that violates certain rules about trademarks around Mozilla and Firefox.

All these are based on the user having a @mozilla.com (or, for trademarks, @mozilla.org) email. We want to replace them with permission checks that we would then give to different groups of people that may need them.

**Comment by diox** [comment]
The new permissions:
- `SystemAddon:Submit` allows you to submit add-ons with reserved guids and xpis already signed with internal certificate
- `Trademark:Bypass` allows you to bypass trademark checks

**Comment by AlexandraMoga** [comment]
I've verified the two new permissions on -dev and these are my results:

- users without a "@mozilla.com" address
  -  with `Trademark:Bypass` submissions of add-ons with the `mozilla` or `firefox` strings in their names are allowed
  - with `SystemAddon:Submit` submissions of add-ons with [these guid suffixes](https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/base.py#L395) are allowed
- users with a "@mozilla.com" address
  - can no longer submit restricted add-ons if they don't have the `SystemAddon:Submit` or the `Trademark:Bypass` permissions
  - with the new permissions, they can submit add-ons with trademarks in their names (`Trademark:Bypass`), or reserved guids (`SystemAddon:Submit`)
- for users that don't have either of these permissions but already own an add-on that contains a trademark or a reserved guid, the upload restriction don't apply when they submit a new version

@diox I was not able to submit an add-on signed with an internal certificate ([like this example](https://addons.mozilla.org/en-US/firefox/addon/firefox-voice/)) with either of the above account patterns. I'm receiving this error:

![image](https://user-images.githubusercontent.com/31961530/95997836-e18ef080-0e3c-11eb-960e-d556d0494e3c.png)
