### ISSUE TITLE
FxA config for stage and production

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1565]
We need Firefox Accounts config setup for the stage and production servers. We'll need to get the FxA team to generate this and have jason add it to the private config.

**Comment by mstriemer** [comment]
Fixed in https://github.com/mozilla/addons-server/commit/c899910a84bdc2fe407f89da34c4834f5a0e4797, https://github.com/mozilla/addons-server/commit/49d58905c89307ea2bcff57387526539b4a9bed5 and secret puppet config place.

**Comment by ValentinaPC** [comment]
Please add some STR for us to verify it or mark this qa- .
Thank you!
