### ISSUE TITLE
Remove the feature to Share an add-on

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1566]
On add-on details page, we have the ability for users to share an add-on via multiple social media sites like facebook, twitter etc. This feature is hidden and doesn't work well. Example: upon sharing an add-on via facebook, the user ends up on a blank page. 

We should get rid of this feature if stats indicate that they are not oft-used.

**Comment by andymckay** [comment]
This is gone now.

**Comment by ValentinaPC** [comment]
@andymckay : Should the "share" option be removed from add-on details inside a collection?
Please see the screenshot: 
![2016-05-04_1147](https://cloud.githubusercontent.com/assets/15685960/15009238/1040da88-11ee-11e6-9104-01afc700e8f9.png)

**Comment by EnTeQuAk** [comment]
@ValentinaPC see andy's answer in https://github.com/mozilla/addons-server/issues/2131#issuecomment-216629388 - let's use 2131 to track the removal.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
Postfix screenshots: 
![collection](https://cloud.githubusercontent.com/assets/15685960/15355716/0fa9f9fa-1cfd-11e6-8531-c0bc4ffc64e9.png)
![favorites](https://cloud.githubusercontent.com/assets/15685960/15355722/1ba2dae2-1cfd-11e6-8c9b-d6d628418136.png)
![coll-add-on](https://cloud.githubusercontent.com/assets/15685960/15355729/233d6362-1cfd-11e6-8490-36e00fb8c12f.png)
