### ISSUE TITLE
Stick to Celery 4.x LTS

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15677]
Celery 5 has been released, and the 4.x branch has been designated a LTS https://docs.celeryproject.org/en/stable/whatsnew-5.0.html#long-term-support-policy. Celery 5 has breaking changes from 4.x, like most releases (and some point releases), so it will be easier, at least in the short term, to stick with Celery 4.x. 

The docs state the 4.x branch will be supported until August 2021 (by which time I guess the next release of celery, 6, will be available? - it's not clear they have a scheduled release policy). Note, as their LTS policy seems a new thing too, we will have to wait to see how security/bug fixes are backported from the 5.x release branch.  There are also dependent packages (kombu and vine) that we wouldn't be able to upgrade - they also managed by the celery project so although they don't have a LTS policy specifically we can probably assume they would have a 4.x fix if required.

**Comment by AlexandraMoga** [comment]
@eviljeff If I understand this issue correctly, there shouldn't be any functional changes involved. Unless there is indeed something to be tested, please add a qa:not needed label.
Thanks.
