### ISSUE TITLE
"addons": [] is empty for theme categories in the shelf API

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15688]
STR:
1. Enable the following homepage shelves from[ admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/) 
"See more recommended extensions" with criteria ?promoted=recommended&sort=random&type=extension
with a theme category:
"Scenery"(theme category) criteria: ?category=scenery&sort=recommended%2Cusers&type=statictheme&app=firefox
or 
"Holiday (theme category)" criteria: ?category=holiday&sort=recommended%2Cusers&type=statictheme&app=firefox

2. Make an API request
https://addons-dev.allizom.org/api/v4/shelves/

Expected result:
there are results for "addons" in both shelves.

Actual result:
The theme shelf won't display results. It's "addons": []

This issue is also reproducible if one of the theme shelves from above is associated with 
[Recommended extensions sorted by rating](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/14/change/) : ?promoted=recommended&sort=rating&type=extension

I wrote this as a followup for https://github.com/mozilla/addons-server/issues/15284
The issue mentioned as a [comment](https://github.com/mozilla/addons-server/issues/15284#issuecomment-704231174) is no longer reproducible.

**Comment by eviljeff** [comment]
pretty sure https://github.com/mozilla/addons-server/issues/15689#issuecomment-707266683 applies here too.

**Comment by xlisachan** [comment]
Please assign this issue to me when you have a moment, @eviljeff - thanks!

**Comment by ioanarusiczki** [comment]
@xlisachan The content of the shelves are displayed. 
Verified with the dev API.
