### ISSUE TITLE
Remove happyforms with django 1.9

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1569]
With Django 1.9 adding (default on) support for stripping whitespaces, happyforms is not useful anymore: https://docs.djangoproject.com/en/1.9/ref/forms/fields/#django.forms.CharField.strip

**Comment by andymckay** [comment]
Noting that happyforms is no longer in AMO, was done in #2964.

**Comment by andymckay** [comment]
Sorry, its still there: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/happyforms.py, just got removed from requirements.

**Comment by eviljeff** [comment]
@EnTeQuAk are you doing this during the 1.11 update?

**Comment by EnTeQuAk** [comment]
Yes, it's actually already done there 


On Wed, Jan 31, 2018, at 7:06 AM, Andrew Williamson wrote:
> @EnTeQuAk[1] are you doing this during the 1.11 update?


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 

Links:

  1. https://github.com/entequak
  2. https://github.com/mozilla/addons-server/issues/1569#issuecomment-361833652
