### ISSUE TITLE
Handle Adzerk returning `null` for it's decisions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15692]
If duplicates are disabled in the adzerk campaign then it's possible to get `null` for one or more requested advertising slots.  This breaks the response processing logic.

**Comment by eviljeff** [comment]
if https://addons-dev.allizom.org/api/v4/shelves/sponsored/ isn't throwing an error but contains less than 6 addons it's working

**Comment by ioanarusiczki** [comment]
@eviljeff 
Right now the requests returned 6, as I mentioned in https://github.com/mozilla/addons-server/issues/15617#issuecomment-708289590
I always received a 200 ok status, never errors.
