### ISSUE TITLE
GET request may return NONE , which may raise an error.

### ISSUE THREAD

**Issue by Sparsh-Bansal** [mozilla/addons-server#15694]
### Describe the problem and steps to reproduce it:
In code like ```obj = request.GET.get('string_a')```
if 'string_a' is not valid , it will return NONE in obj.
In that case , HTTP404 Error should be raised .

In the file [src/olympia/addons/views.py](https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/views.py)
Line no. 271 , 322 , 449 , 689 , 690 ,
This should be done . 
```
 obj = request.GET.get('string_a')
 if not obj:
     raise http.Http404
```

**Comment by diox** [comment]
Please try to actually reproduce this by calling the API before concluding this will raise a 404 just by looking at a few lines of code in isolation.
