### ISSUE TITLE
Remove settings hacks from services.utils

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1570]
I feel like this doesn't work anymore either way and I'm not sure who `freddo` is.

Can someone enlighten me here, can we get rid of this and simply use `from django.conf import settings` here? Or do we have a explicit `settings_local` file that get's somehow put into the `services` folder during deployment?

@jasonthomas @magopian @andymckay

**Comment by magopian** [comment]
Since at least recently (before the move to AWS), the `settings_local` file was present during the deployment. I'm not sure if this has changed, but @jasonthomas will know ;)

**Comment by jasonthomas** [comment]
`freddo` is a code deployment tool we no longer use [1]

`settings_local` is still present and we also set `DJANGO_SETTINGS_MODULE` env variable to it.

[1] https://github.com/oremj/freddo

**Comment by EnTeQuAk** [comment]
This code cleanup isn't neccessary worth it so maybe let's stay with "never touch a running system unless you have to"
