### ISSUE TITLE
Receive mail at upload source code

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#15708]
### Describe the problem and steps to reproduce it:
When sending a delayed rejection and the developer makes changes, without adding a comment, I, as the reviewer, don't receive an email. In this way some add-ons get auto-reject, even though they responded to my request.

### What happened?
I sent a delayed rejection with the canned response for minified code. The developer uploaded the source code. I didn't receive an email so I didn't go back to that add-on and after 2 weeks it was auto-rejected, even if the developer responded to my request.

### What did you expect to happen?
I was expecting to receive an email that the developer uploaded the source code on that add-on.

**Comment by diox** [comment]
2 things need to happen here:
- We need to automatically subscribe the reviewer to notifications when they submit a delayed rejection (in the same channel)
- That notification needs to be sent also when the developer submits source code of an existing version (maybe with a different template)

**Comment by wagnerand** [comment]
> 2 things need to happen here:
> 
>     * We need to automatically subscribe the reviewer to notifications when they submit a delayed rejection (in the same channel)
> 
>     * That notification needs to be sent also when the developer submits source code of an existing version (maybe with a different template)

Note that this does not mean we should subscribe the reviewer to notification for new version submissions. This is just about subscribing to the conversation to the specific version(s) the reviewer rejected.

**Comment by diox** [comment]
That makes it a little trickier, but ok. I guess I'll have to extend how reviewer subscriptions work a bit more...

**Comment by diox** [comment]
Thinking about this more, I think this should be done through the activity log utils in the same way we notify relevant people when a reviewer/author responds to some comments. We already have an activity log event, we just need to notify users about it.

**Comment by wagnerand** [comment]
> Thinking about this more, I think this should be done through the activity log utils in the same way we notify relevant people when a reviewer/author responds to some comments. We already have an activity log event, we just need to notify users about it.

Yes, that was the path I had in mind.

**Comment by diox** [comment]
Do we also want to notify staff in `Activity Mail CC` group ? Other authors on the add-on ? (we do both these things for other actions for which we send an email notification)

**Comment by wagnerand** [comment]
> Do we also want to notify staff in `Activity Mail CC` group ? Other authors on the add-on ? (we do both these things for other actions for which we send an email notification)

Whatever is easiest. Notifying staff would be nice, I don't have a preference for notifying other developers. For the sake of consistency, it would make sense to do both, like for other actions. If that's more complicated, we can do things differently (although I would assume doing the same is easier).

**Comment by diox** [comment]
Other authors of the add-on, reviewers of the corresponding version, and members of the `Activity Mail CC` group will receive an email notification for source code upload.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev.

When a developer uploads source code for a particular version, the following users will be notified by email:
- all reviewers that reviewed that particular version in the past
- all members of the Activity mail CC group
- additional add-on authors 

I've uploaded source files in Dev Hub Manage versions page.
This applies both to listed and unlisted versions.
