### ISSUE TITLE
Remove ES data/indices/etc. related to the legacy stats

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15709]
After the push of October 15th (2020.10.15), no addons-server code will depend on the legacy (download) stats. It'll be safe to remove everything related to those legacy stats. Technically, we stopped relying on the data in the previous push (2020.10.08).

**Comment by bqbn** [comment]
What does "everything" include? I know the `addons_stats_download_counts_prod` is one, anything else?

It would be nice if everything can be listed explicitly.

**Comment by willdurand** [comment]
I don't know exactly which ES "stats" indices we have but we don't use them anymore. As for the rest I have no idea, I thought there was a pipeline with Hadoop, log files, s3, etc.? We don't need any of that anymore.

Sorry for being vague but I don't really know what is involved.

**Comment by bqbn** [comment]
We have deleted the `addons_stats_download_counts_prod-20200604184835` index and its alias.
