### ISSUE TITLE
Remove prefix for Fenix versions

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15715]
We introduced a prefix to Fenix stats data in https://github.com/mozilla/addons-server/issues/15070 because we were using Fenix build IDs instead of the gecko versions (we didn't have the correct versions back then). This has been fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1669516 so we can get rid of that feature.

**Comment by ioanarusiczki** [comment]
@willdurand

I've noticed an  "Android 81.1" and "Android 82.0" in /statistics/usage/applications/ page. 

![Android and versions](https://user-images.githubusercontent.com/33448286/96421404-6728ec80-11ff-11eb-8528-e3c073399f7f.png)
