### ISSUE TITLE
Add a django admin to onboard candidates

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15723]
From the PRD:

> The admin enters the ID of the add-on that will be onboarded and the Promoted group (Verified or Sponsored), and that generates an AMO URL that will be sent to the developer to set up payment.

For QA: this should allow admins (or users with the `Discovery:Edit` permission) to create subscriptions for an add-on and a promoted group. The generated link will point to nowhere until we close #15726.

Note: this admin will be inlined in the existing promoted admin and only revealed (in read only mode) once a promoted addon has been created (verified or sponsored only).

**Comment by ioanarusiczki** [comment]
@willdurand I went on dev with an admin account to these pages `models/discovery/promotedaddon/250/change/`  for a verified/sponsored addon but I don't see anything added for subscription. I tried with a new add-on added in sponsored group - I've checked before and after the a version approval too, still no subsription fields.

**Comment by willdurand** [comment]
> @willdurand I went on dev with an admin account to these pages `models/discovery/promotedaddon/250/change/` for a verified/sponsored addon but I don't see anything added for subscription. I tried with a new add-on added in sponsored group - I've checked before and after the a version approval too, still no subsription fields.

Can you save this promoted add-on without changing anything?

**Comment by willdurand** [comment]
mm nevermind, there is an issue with -dev and the code is not up-to-date.

**Comment by ioanarusiczki** [comment]
@willdurand Ok, I'll get back to it later.

**Comment by ioanarusiczki** [comment]
@willdurand The read only Promoted Subscriptions section is now visible for verified and sponsored addons. 

Fields available:

Onboarding URL: some addons have a URL such as https://addons-dev.allizom.org/a-test-for-spotlight-addons/onboarding but most of them have "None".
Link visited at: -
Payment cancelled at: -
Paid at: -

Could this issue https://github.com/mozilla/addons-server/issues/15795 be caused by this deployment? After it landed I could not add back to Sponsored the shelf addons.

**Comment by willdurand** [comment]
> Onboarding URL: some addons have a URL such as [addons-dev.allizom.org/a-test-for-spotlight-addons/onboarding](https://addons-dev.allizom.org/a-test-for-spotlight-addons/onboarding) but most of them have "None".

Most should have `None` by default but after saving the promoted add-on, the link should appear.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, it worked, I only have to "save" and the URL is displayed.

**Comment by ioanarusiczki** [comment]
@willdurand I've asked @wagnerand about permissions in admin more exactly to what group should I add Discovery:Edit and see if access is available besides an admin. I'm going to check that too.

**Comment by ioanarusiczki** [comment]
@willdurand I verified the permissions on dev - FF82(Win10), the Discovery:Edit is enough to have access and edit the Discovery module (with the condition it's a mozilla e-mail account).
