### ISSUE TITLE
Add a model to store onboarding/payment/subscription information

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15724]
We need a model/db table to store information about payment for promoted add-ons.

**Comment by willdurand** [comment]
@diox I'm thinking about create a model named `PromotedSubscription` in the `promoted` app, which will contain the following (for now):

- addon
- (promoted) group (limited to VERIFIED_ONE and VERIFIED_TWO)
- link opened (the idea is to set this flag when the developer has opened the onboarding page)
- stripe session ID (needed to double-check the success/cancel events)
- payment_cancelled (needed to know that the developer didn't pay with Stripe and went back to AMO)
- paid_at (date set when the developer has successfully paid)

The onboarding URL is generated once the subscription has been created in the admin.

I suppose we should have some constraints like having one subscription for an `(addon, promoted_group)` but that can be added later because it might depend on how we want to handle cancellation (or pauses) in the future.

**Comment by eviljeff** [comment]
At what point does the `PromotedSubscription` instance get created?  Is it manually by an admin?  And when does the `PromotedAddon` instance get created now?  
Generally I would have thought the model would fk to `PromotedAddon` rather than `Addon` directly but that's (obviously) only possible if the `PromotedAddon` exists before the `PromotedSubscription`.

We probably want datetime fields rather the booleans for things like visiting links and payment cancelled.

**Comment by willdurand** [comment]
> At what point does the `PromotedSubscription` instance get created? Is it manually by an admin? And when does the `PromotedAddon` instance get created now?

According to the PRD, the add-on might or might not be in a promoted group yet. I don't know if that changes anything regarding `PromotedAddon` but that's why I fk'ed the subscription to an add-on.

> We probably want datetime fields rather the booleans for things like visiting links and payment cancelled.

Good idea.

**Comment by eviljeff** [comment]
> > At what point does the `PromotedSubscription` instance get created? Is it manually by an admin? And when does the `PromotedAddon` instance get created now?
> 
> According to the PRD, the add-on might or might not be in a promoted group yet. I don't know if that changes anything regarding `PromotedAddon` but that's why I fk'ed the subscription to an add-on.

If there wasn't a `PromotedAddon` instance (or, more accurately, a `PromotedAddon` with either group sponsored or verified- other groups or not promoted could be updated) until the subscription payment had succeeded then there wouldn't need to be any changes in the logic around if an addon is approved for promoted groups.  It'd need to be created after the subscription is done.  Otherwise the approval logic needs to take `PromotedSubscription` into account.

**Comment by willdurand** [comment]
> Otherwise the approval logic needs to take `PromotedSubscription` into account.

How so?

I think it's possible to have a `PromotedAddon` instance before a `PromotedSubscription`: that will be the case for the add-ons participating in the pilot.

Once the payment has succeeded, we can check whether there is a `PromotedAddon` for the add-on and group of the `PromotedSubscription` (with `addon.promoted_group(currently_approved=False)` and create the `PromotedAddon` if it does not exist.

After that, we would need to do what the PRD states:

> The current version of the extension will be repackaged, version-bumped, and auto-approved, to be used as the first Promoted version.

(easier said than done)

**Comment by eviljeff** [comment]
> > Otherwise the approval logic needs to take `PromotedSubscription` into account.
> 
> How so?
> 
> I think it's possible to have a `PromotedAddon` instance before a `PromotedSubscription`: that will be the case for the add-ons participating in the pilot.
> 
> Once the payment has succeeded, we can check whether there is a `PromotedAddon` for the add-on and group of the `PromotedSubscription` (with `addon.promoted_group(currently_approved=False)` and create the `PromotedAddon` if it does not exist.

I was thinking more generally, after the pilot.  If the `PromotedAddon` instance is created with group=verified and the developer uploads a new version, and it's approved in reviewer tools, then the addon will be promoted as group verified, regardless of what the state of `PromotedSubscription` is.  Solution is to either not create the PromotedAddon instance until after the payment has been made, or take `PromotedSubscription` into account when approving versions.

**Comment by willdurand** [comment]
Right, I have the feeling that we should create a `PromotedSubscription` when a `PromotedAddon` for a verified tier (1 or 2) is created. Is that possible?

**Comment by willdurand** [comment]
Given that the flow has slightly evolved, it makes sense to have a FK to `PromotedAddon`, not `Addon`. In addition to that, a `PromotedSubscription` will be created when a `PromotedAddon` is created if its group is one of `PROMOTED_GROUPS_FOR_SUBSCRIPTION`.

**Comment by eviljeff** [comment]
> In addition to that, a `PromotedSubscription` will be created when a `PromotedAddon` is created if its group is one of `PROMOTED_GROUPS_FOR_SUBSCRIPTION`.

Note: a `PromotedAddon` can change groups after it's created.

**Comment by ioanarusiczki** [comment]
@willdurand I see that UI in the promoted admin will land on dev with https://github.com/mozilla/addons-server/issues/15723

If this does not require qa please add a label. 
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki this issue should not have an impact on the current promoted add-ons. A quick check would be enough to verify this issue.
