### ISSUE TITLE
Deleted/disabled addons continue to be displayed on the frontend - the primary hero shelf

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15737]
STR:
1. An addon is recommended and enabled for the primary hero shelf 
2. Delete it from dev hub/ or disable it from the rev tool page
3. Check the frontend

Expected result:
The addon should not be displayed

Actual result:
The addon is still displayed and Get Extension button redirects to a 404 page

Notes:
As a workaround for the disabled addons: the admin can go to the promoted model and remove the `Enabled` checkbox from the primary hero section. It won't let me remove it for the deleted addons because it throws an error "Select a valid choice. That choice is not one of the available choices", so the workaround is to delete it from the promoted model.

Reproducible on AMO dev and stage - FF81(Win10). 

![deleted addons](https://user-images.githubusercontent.com/33448286/96107218-d4c5d780-0ee4-11eb-8e36-18d528a726a0.gif)

**Comment by eviljeff** [comment]
I feel like this is something we've come across before as a possibility, but I can't remember what the decision was about what should happen.  @jvillalobos what would you expect to happen?

**Comment by jvillalobos** [comment]
My expectation is that non-visible add-ons shouldn't appear in the primary hero. We might have left this open-ended because at some point we had considered having unlisted add-ons show up there and the "Get the extension" button would point to a different URL in that case. I don't see us doing that anytime soon.

**Comment by ioanarusiczki** [comment]
@eviljeff The addons are no longer displayed on the frontend when they're deleted or disabled. - it's verified on AMO dev FF82(Win10). 

There's a UI admin model issue left, when the addon is deleted the states for "Is Approved" and "Primary Hero shelf" are:
![Deleted addons](https://user-images.githubusercontent.com/33448286/96848870-9c327a80-145d-11eb-8191-f20af6fe480b.png)

For disabled there's no clue it's no longer approved:

![The disabled](https://user-images.githubusercontent.com/33448286/96848932-b0767780-145d-11eb-916f-094df28bbc13.png)

So I'm thinking to file an issue, because it can cause confusion.
