### ISSUE TITLE
Unify ugettext, ugettext_lazy and variants usage

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1574]
Unify `ugettext`, `ugettext_lazy` and variants usage. It's not always used correctly (e.g non-lazy ugettext on module-level) and sometimes `_` references to the lazy variant and vice versa. We need a clear guideline.

I'd propose:
- `ugettext_lazy` -> `_` (as this is used most often, e.g in models, forms and constants)
- explicit `ugettext` (and others) calls to make sure one sees the differences

Opinions?

**Comment by eviljeff** [comment]
from a quick search of module imports, it looks like
50 * ugettext as _ 
17 * ugettext_lazy as _lazy
14 * ugettext_lazy as _

So just pointing out if those are the guidelines it's reversing the current norm in the code.

**Comment by EnTeQuAk** [comment]
Short note here, my proposal is also based on what Django uses itself (`ugettext_lazy` -> `_`) and many other django packages.
