### ISSUE TITLE
The hero endpoint needs to return `promoted` for the `addon`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#15741]
In order to support https://github.com/mozilla/addons-frontend/issues/9764, we need to have access to the `promoted` property in the `addon` in the API response to the `hero` endpoint, but unfortunately that is not currently available.

**Comment by bobsilverberg** [comment]
I'm bumping this up to a P2 as it blocks https://github.com/mozilla/addons-frontend/issues/9764, and hence the feature. Do you think you'll have time to take this on @eviljeff?

**Comment by ioanarusiczki** [comment]
@eviljeff The endpoint https://addons-dev.allizom.org/api/v4/hero/primary/ returns the `promoted` property for addons. 

"promoted": {
                    "apps": [
                        "firefox"
                    ],
                    "category": "recommended"
