### ISSUE TITLE
"Describe your theme" field is marked as mandatory in edit theme page even if is not

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1575]
Steps to reproduce:
1. Load edit page for any theme on AMO-dev (i.e. https://addons-dev.allizom.org/en-US/developers/theme/octo-pods/edit)
2. Observe the "Describe your theme" field

Expected results:
The field is not marked as mandatory.

Actual results:
The field is marked as mandatory even if changes can be made with that field empty.

Notes/Issues:
The field is marked as "optional" at submission.
Verified on FF43(Win 7). Issue is reproducing on AMO-stage, dev and production.
Please see the screenshot:
![2016-02-02_1028](https://cloud.githubusercontent.com/assets/15685960/12743702/2043bc82-c998-11e5-9851-ad694fb5fab8.png)

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

Mentor: me (@wagnerand)

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
Postfix screenshot: 
![mandatory](https://cloud.githubusercontent.com/assets/15685960/19030219/edb76ed0-8954-11e6-9f5b-e6db663875aa.png)
