### ISSUE TITLE
"Register" page has "Log in" title on Android

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1576]
Steps to reproduce:
1. Load AMO-dev on your Android device
2. Tap the "Register" link

Expected results:
E-mail field together with a "Continue" button is displayed.

Actual results:
Page title is "Log in". Both email and password fields are displayed.

Notes/Issues:
This can be misleading for a normal user.
Verified on FF43(Android 5.0.1). Issue is reproducing on AMO-dev.
Screenshot for this issue: 
![2016-02-02_1001](https://cloud.githubusercontent.com/assets/15685960/12743960/311ea38a-c99a-11e5-89f9-98b2e8bd1ca7.png)

**Comment by mstriemer** [comment]
This was because the login flow wasn't properly implemented on mobile. Closing in favour of #1660.

**Comment by ValentinaPC** [comment]
I know it is a very small issue, but, no matter what link I chose to click on Android (Register or Log in), page title is "Log in". Maybe the desktop page "format" should apply here too.
Please see the screenshot: 
![2016-02-18_1639](https://cloud.githubusercontent.com/assets/15685960/13146397/3b230468-d65e-11e5-99a9-7ff54596d8a5.png)

**Comment by mstriemer** [comment]
On desktop it says "Enter your email". This should probably say that too.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage FF44(Android 5.0.1)
Postfix screenshot: 
![2016-02-24_1544](https://cloud.githubusercontent.com/assets/15685960/13287060/a48bb590-db0d-11e5-9d3b-946a5c0ef271.png)
