### ISSUE TITLE
Expose `needs_human_review` and `needs_human_review_by_mad` in admin

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15779]
We should expose the `needs_human_review` and `needs_human_review_by_mad` flags in the version admin, so admins can manually set or unset it if needed.

**Comment by AlexandraMoga** [comment]
@wagnerand I've verified the [admin version manage](https://addons-internal.stage.mozaws.net/en-US/admin/models/versions/version/2478172/change/) with versions that triggered a scanners or mad flag and these are my results:

- functionality:
  - the "Needs human review" checkboxes are automatically checked if the version triggered a scanner or mad flag
  - if the versions are approved/rejected - i.e. actions that clear the scanner flags - the "Needs human review"/ "Needs human review by mad" check will be cleared
  - if the admin checks/unchecks one or both the "Needs human review" checkboxes, the changes will be reflected in the Flagged by scanners, respectively Flagged for human review queues, i.e. the versions will appear/disappear from the queues
- layout:
  - the two checkboxes are separated in two sections: 'Flags' for the 'Needs human review' checkbox and 'Version reviewer flags' for 'Needs human review by mad' - should they not both be in the same section? [1]
  - there is also a 'Delete' checkbox next to 'Needs human review by mad' which appears to be deleting the `VersionReviewerFlags` object [2]
- some small issues:
  - the `VersionReviewerFlags object` for the mad flag has a View on site link that is not functional => triggers a 500 error
  - there is a typo in the in the 'Version reviewer flags' title (double 's' at the end) [2]

[1]
![image](https://user-images.githubusercontent.com/31961530/96700497-2dd7b480-1398-11eb-9b95-5869cedc7415.png)
[2]
![image](https://user-images.githubusercontent.com/31961530/96701071-dbe35e80-1398-11eb-9fc0-0c2f9bb098e9.png)

**Comment by wagnerand** [comment]
@AlexandraMoga thank you for testing!

>       * the two checkboxes are separated in two sections: 'Flags' for the 'Needs human review' checkbox and 'Version reviewer flags' for 'Needs human review by mad' - should they not both be in the same section? [1]

I would prefer to, but I am not sure it's possible without a ton effort (probably not worth it).

>       * there is also a 'Delete' checkbox next to 'Needs human review by mad' which appears to be deleting the `VersionReviewerFlags` object [2]
>       * the `VersionReviewerFlags object` for the mad flag has a View on site link that is not functional => triggers a 500 error

@diox I probably need to set 
```
can_delete = False
view_on_site = False
```
for the inline, right?

>       * there is a typo in the in the 'Version reviewer flags' title (double 's' at the end) [2]

I believe that is done by django automatically, it's attaching an `s` for the plural form, but the model `VersionReviewerFlags` is already plural. I can live with it, but maybe there is a trivial fix, @diox?

**Comment by diox** [comment]
> I probably need to set
> ```
> can_delete = False
> view_on_site = False
> ```

Yes.

**Comment by wagnerand** [comment]
@AlexandraMoga Fixed for the mentioned issues should be on -dev soon.

**Comment by AlexandraMoga** [comment]
The issues mentioned have been fixed:

![image](https://user-images.githubusercontent.com/31961530/96731706-38a63f80-13c0-11eb-8a03-92975003a40e.png)
