### ISSUE TITLE
Promoted subscription when a promoted add-on is set to a new group

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15783]
We can set a different group to a promoted add-on and in the case of subscriptions, that might have an impact:

1. promoted add-on was in a group that didn't require payment: no problem, if the new group requires payment, a subscription will be created.
2. promoted add-on was in a group that required payment and...
   2.1. new group does not require payment: the subscription still exists but we hide its data in the django admin
   2.2. new group requires payment: we would need a new subscription and likely archive the old one if we want to keep track of that in our DB. Otherwise, we could reset the existing subscription (i.e. we reset the `first_visited_at` and `paid_at` dates)

WDYT? (we might not need to handle this right now but it would be good to know)

**Comment by willdurand** [comment]
I am unassigning myself not because I don't want to work on that anymore but rather because we need to understand what to do in terms of cancellation first.

That being said, at the very least, we should probably prevent changes to a promoted add-on with an active subscription. @diox WDYT?

**Comment by diox** [comment]
Yeah, probably. One question for product is what should happen to the promoted state and the subscription in those scenarios and  what to automate / what to leave to be handled manually.

**Comment by willdurand** [comment]
cc @jvillalobos

**Comment by jvillalobos** [comment]
Does Stripe provide a way to cancel a subscription automatically?

My understanding is that the user can't do it on their own, so if our only option is to do it manually, then this will be a largely manual process.

**Comment by willdurand** [comment]
> Does Stripe provide a way to cancel a subscription automatically?

We can do pretty much everything with their API.

> My understanding is that the user can't do it on their own, so if our only option is to do it manually, then this will be a largely manual process.

Indeed! Users cannot unsubscribe.

**Comment by jvillalobos** [comment]
If we can cancel the subscription via the API, then I think we should do that automatically when an add-on is no longer in a paid group.

Changing between paid groups is the tricky case. Not sure if Stripe supports an update flow or we should cancel and then onboard again. We could have the admin generate a new onboarding URL when the group is changed, with the relatively safe assumption that the dev will complete the update process. If they don't we can follow up manually.

**Comment by eviljeff** [comment]
I think we can close this (at least for now)
