### ISSUE TITLE
Release a new version of an add-on after payment

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15784]
Once the payment flow has been completed (successfully) and iff there is no version pending for review, we should create a new version automatically and sign it so that the add-on becomes promoted (if not done already).

**Comment by willdurand** [comment]
For QA: we're going to truncate the promoted subscription table in -dev so all existing subscriptions will be deleted.

**Comment by ioanarusiczki** [comment]
@willdurand Test results on dev:

Steps:
- the admin is adding the ID into the[ promoted list ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon) as verified or sponsored
- the onboarding URL is generated automatically
- the admin sends the URL via e-mail (a manual step, this has not been automated) to the developer
- the developer uses the URL to make the payment
- when the final step with "You're done" is displayed the addon is already signed for the last approved version of the add-on 

![step one](https://user-images.githubusercontent.com/33448286/97429608-53c50200-1920-11eb-8ed3-3eb8a432e28c.png)

("There is no further action needed, thank you" has been removed) - is that alright?
![final step](https://user-images.githubusercontent.com/33448286/97429619-57f11f80-1920-11eb-98f8-c21d76d68f0c.png)

So right now:
- for a verified/sponsored add-on with an already approved version after the payment is done the approved version is re-signed, the add-on gets the badge and becomes automatically verified/sponsored. 
- when the add-on is awaiting review - as the first version has not been approved yet, it can be manually approved by the admin or it could be re-signed. I am waiting to see autoapproval for this [addon](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/279/change/ )
- in the admin promoted model - promoted approval section, these re-signed versions are displayed. 
- a new submitted version after the add-on is verified/sponsored and paid will require manual review from the admin.

Notes:
- the review pages for the add-ons show for the approved verified/sponsored a "Version 3.0.1-signed" if originally it was "Version 3.0" but the date of the approval is still the original one. Also, if the version has been approved manually in the past, the info about the reviewer stays the same (it is not changed into Approved By Mozilla).  I'm thinking of filing these issues on server.

![the date](https://user-images.githubusercontent.com/33448286/97431022-60e2f080-1922-11eb-88eb-29e8bf97caa4.png)

**Comment by willdurand** [comment]
> ("There is no further action needed, thank you" has been removed) - is that alright?

Yes.

**Comment by willdurand** [comment]
>     * for a verified/sponsored add-on with an already approved version after the payment is done the approved version is re-signed, the add-on gets the badge and becomes automatically verified/sponsored.

approved version but not yet promoted, right? Otherwise there should be no re-signing.

**Comment by willdurand** [comment]
> the review pages for the add-ons show for the approved verified/sponsored a "Version 3.0.1-signed" if originally it was "Version 3.0" but the date of the approval is still the original one. Also, if the version has been approved manually in the past, the info about the reviewer stays the same (it is not changed into Approved By Mozilla). I'm thinking of filing these issues on server.

cc @eviljeff

**Comment by ioanarusiczki** [comment]
@willdurand The rev tools pages do not show a "signed" last version for already promoted add-ons after making the payment:
A sponsored : https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/a-test-for-spotlight-addons
A verified: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/more-optional-permissions
Same on the promoted model [page ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/238/change/). 

I think it should be alright in these cases.

**Comment by eviljeff** [comment]
> > the review pages for the add-ons show for the approved verified/sponsored a "Version 3.0.1-signed" if originally it was "Version 3.0" but the date of the approval is still the original one. Also, if the version has been approved manually in the past, the info about the reviewer stays the same (it is not changed into Approved By Mozilla). I'm thinking of filing these issues on server.

we don't really want to lose the information about the original approval but maybe we need some extra (review activity) logging.  Not sure.

**Comment by ioanarusiczki** [comment]
@willdurand 

> when the add-on is awaiting review - as the first version has not been approved yet, it can be manually approved by the admin or it could be re-signed. I am waiting to see autoapproval for this addon

An add-on with ["awaiting review" ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/test4sponsoredverified) status needs manual approval. But that's the expected result. The idea was to re-signed already approved versions. 

@eviljeff I'll file an issue about the review page for further discussion.
