### ISSUE TITLE
500 error when making an addon sponsored/verified

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15795]
I was trying to add back the promoted shelf on the frontend from the promoted model - admin, I have to change the Group from "Not promoted" into "Sponsored" and Save.

Result:
I receive a 500 server error

Notes:
I could reproduce the issue - when changing the group to Sponsored or Verified. It is not reproducible for the other groups.
Ids in this situation: 496379, 620026, 620031, 502855

**Comment by willdurand** [comment]
@ioanarusiczki once this is verified on -dev, we will cherry-pick the patch for it because -stage is affected too.

**Comment by ioanarusiczki** [comment]
@willdurand Alright! first thing tomorrow morning.

**Comment by ioanarusiczki** [comment]
@willdurand I checked on dev and I can't reproduce the issue. - FF82(Win10).

**Comment by ioanarusiczki** [comment]
Verified on AMO stage - FF82(Win10).
