### ISSUE TITLE
Subscription onboarding success page should have a "manage add-on" button

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15806]
According to the PRD, the success page should have a button Manage add-on" that links to the Edit page of the add-on.

**Comment by ioanarusiczki** [comment]
@willdurand verified on dev - FF82(Win10):

![edit addon page](https://user-images.githubusercontent.com/33448286/97146819-2e45c600-1771-11eb-9fab-365fa127109f.gif)
