### ISSUE TITLE
Do not require version approval for an add-on to be added to the Spotlight group

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#15801]
Because Spotlight add-ons generally come up unexpectedly and we don't necessarily have a fast connection with the developer, it's best if we don't require a new version to be approved for the changes in a Spotlight add-on to apply. Operationally, we will always perform a pre-review on the current version before making the change in the admin, and nothing needs to change in the file, so it should be okay to apply the change right away.

/cc @devaneymoz @kewisch

**Comment by eviljeff** [comment]
Does this apply to the add-on as a whole, or just the current version at the time the add-on was added the the Spotlight group?

I.e. should we stop tracking per version approvals for Spotlight (but keep the requirement to pre-review new versions)

**Comment by eviljeff** [comment]
if it's just the current version at the time it becomes a similar thing to https://github.com/mozilla/addons-server/issues/15784 (albeit without the need to repack the xpi and resign because Spotlight doesn't have special signing)

**Comment by jvillalobos** [comment]
I think it should only apply to the current version at the time the add-on was added, given that previous versions won't be looked at.

**Comment by eviljeff** [comment]
btw @jvillalobos this could be extended to other groups (e.g. Line) - please file a follow-up issue if it's required.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified on dev the following scenarios:

- an already approved [add-on](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/spotlight-2) is added to the promoted model into the Spotlight group. The add-on becomes a Spotlight addon (the Promoted approvals from admin displays the version), it can be enabled on the primary hero shelf too, and no new version is required for submission. 
- the addon is already a "spotlight" addon and a new version is submitted: the new version is locked and needs manual approval.
Same situation for the first version of an [add-on](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/spotlight3) that has been added to the spotlight group. 

I think this works as expected.  But if I'm wrong, please let me know.
