### ISSUE TITLE
Handle subscription cancellation after initial payment

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15805]
We should determine how to handle the following scenario:

1. developer has a promoted add-on that requires payment
2. developer successfully sets up payment _via_ Stripe Checkout
3. ...after some time...
4. developer wants to cancel their subscription

I thought Stripe would allow the developer to cancel the subscription on Stripe directly, but it does not seem possible, which is good for us because it means we have to implement the cancellation feature and we can design it the way we want.

**Comment by willdurand** [comment]
Cancellation will be handled manually in Stripe. AMO should listen to events in order to update the promoted group after cancellation. We should also add a warning when an AMO admin wants to update a promoted add-on in the django admin.

**Comment by jvillalobos** [comment]
One more thing: when an add-on is removed from a paid promoted group (either through Stripe or an AMO override), a new version should be generated so that it is signed without any promoted flags.

**Comment by willdurand** [comment]
> One more thing: when an add-on is removed from a paid promoted group (either through Stripe or an AMO override), a new version should be generated so that it is signed without any promoted flags.

cc @eviljeff

**Comment by eviljeff** [comment]
> One more thing: when an add-on is removed from a paid promoted group (either through Stripe or an AMO override), a new version should be generated so that it is signed without any promoted flags.

mmm, why?  If it's not in the promoted group (or group is not promoted) it won't show as promoted in the api/frontend.

**Comment by jvillalobos** [comment]
So that users are updated to a version that isn't badged anymore and the action on AMO is consistent in Firefox.

**Comment by eviljeff** [comment]
We don't do this for the other promoted groups that have special signing - should those be treated similarly?

imo, the version *is* verified - stopping making further payments doesn't rewrite history so it wasn't manually reviewed by us and verified at the time it was installed.  Is "consistency" the only user benefit to this?

**Comment by jvillalobos** [comment]
> We don't do this for the other promoted groups that have special signing - should those be treated similarly?

I think so, yes, I just didn't want to add extra work to this request.

> imo, the version is verified - stopping making further payments doesn't rewrite history so it wasn't manually reviewed by us and verified at the time it was installed. Is "consistency" the only user benefit to this?

Cancellation can stem from a number of reasons, including a developer being uncooperative, an add-on being taken over by someone less responsible than the previous owner, etc. I expect lack of payment to be the less likely one. I would prefer that we have a way to remove add-ons from the program that brings them back to their previous state in every way.

**Comment by eviljeff** [comment]
filed https://github.com/mozilla/addons-server/issues/15921 to support resigning when an add-on is removed from a promoted group

**Comment by ioanarusiczki** [comment]
@willdurand Looking at [Customer Portal](https://stripe.com/docs/billing/subscriptions/customer-portal) perhaps I should see a "Cancel plan" button after I go to manage billing on stripe?

![cancel plan](https://user-images.githubusercontent.com/33448286/98823039-40468a80-243a-11eb-8f9f-0c0f2c4f71a6.png)

**Comment by willdurand** [comment]
> @willdurand Looking at [Customer Portal](https://stripe.com/docs/billing/subscriptions/customer-portal) perhaps I should see a "Cancel plan" button after I go to manage billing on stripe?

No, we don't want that. Only Stripe admins will be able to perform this action so you'd have to tell me which (promoted) subscription you want to cancel and I'll do it. After that, you should see some changes.

**Comment by ioanarusiczki** [comment]
@willdurand Verified add-on ID: 620296, Review page: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/a-test-to-cancel-payment

**Comment by willdurand** [comment]
> @willdurand Verified add-on ID: 620296, Review page: [reviewers.addons-dev.allizom.org/en-US/reviewers/review/a-test-to-cancel-payment](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/a-test-to-cancel-payment)

I cancelled the subscription on Stripe.

**Comment by ioanarusiczki** [comment]
@willdurand 
- [promoted model ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/329/change/) shows the time and date of cancellation in "Cancelled at:" field. 
- the promoted model and the review page shows the version as being signed - but we'll see what happens after https://github.com/mozilla/addons-server/issues/15921
- the addon has a "not promoted" status in admin and it is approved and available for installation but no badge is shown on the add-on detail page.
