### ISSUE TITLE
Mismatch in importing files 

### ISSUE THREAD

**Issue by Sparsh-Bansal** [mozilla/addons-server#15818]
### Describe the problem and steps to reproduce it:
`olympia.constants.base` is imported as `.base` In `olympia.constants.application` and as `olympia.constants.base` in `olympia.constants.categories` 

Both works fine, but the code should stick to one.

**Comment by eviljeff** [comment]
There's inconsistencies all over the codebase - it's over a decade old with many different contributors - and it's not worth the noise or effort to change them unless you're doing other work on the same code at the same time, especially not manually.
