### ISSUE TITLE
Return `null` for the primary hero shelf when no add-ons are enabled

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#15811]
This is a spin-off from https://github.com/mozilla/addons-frontend/issues/9795, ans also blocks fixing that issue.

Currently, when no add-ons are enabled for the primary hero shelf, the API response contains the following for the primary shelf:

```json
{
	"primary": {
		"addon": {
			"authors": [],
			"average_daily_users": null,
			"current_version": {
				"files": []
			},
			"guid": "",
			"name": null,
			"previews": [],
			"slug": "",
			"type": null,
			"promoted": {
				"category": null
			}
		},
		"external": {
			"guid": "",
			"homepage": null,
			"name": null,
			"type": null
		},
		"featured_image": ""
	},
	...
}
```

The `hero` endpoint is supposed to return either `addon` or `external`, but not both, which causes an issue for the frontend logic. As well, the values returned above for `addon` and `external` aren't really valid. It would be better if the `hero` endpoint simply returned `primary: null` when there are no add-ons enabled.

**Comment by ioanarusiczki** [comment]
@eviljeff The content of the response for https://addons-dev.allizom.org/api/v4/hero/primary/ when no addon is enabled is:

{
    "results": []
}

is this the expected? or it's supposed to be "results": null ?

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff The content of the response for https://addons-dev.allizom.org/api/v4/hero/primary/ when no addon is enabled is:
> 
> {
> "results": []
> }
> 
> is this the expected? or it's supposed to be "results": null ?

the change was to the `/hero/` endpoint that combines primary and secondary results; `/hero/primary/` is unchanged (`"results": []` is consistent with other list style endpoints, so is fine)

**Comment by ioanarusiczki** [comment]
@eviljeff The "primary": null is returned for https://addons-dev.allizom.org/api/v4/hero/ when there's no addon enabled for the primary hero shelf.
