### ISSUE TITLE
Fix content in onboarding template

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15824]
From @jvillalobos:

1. Use bold instead of italics for the add-on name.
2. Copy tweak for error message: “If you’re experiencing problems with this process,” -> “If you’re experiencing problems with this process or you’ve changed your mind,”

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on dev - FF82(Win10):

![step one](https://user-images.githubusercontent.com/33448286/97289542-fd888e00-184f-11eb-9997-33135fb66735.png)


![The error message](https://user-images.githubusercontent.com/33448286/97288744-f745e200-184e-11eb-823c-45d303335d81.png)

![Set up payment](https://user-images.githubusercontent.com/33448286/97288717-ee551080-184e-11eb-8d75-09a9792882fa.png)
