### ISSUE TITLE
Handle failed subscription payments

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15837]
https://github.com/mozilla/addons-server/issues/15783#issuecomment-715562845 said that users cannot unsubscribe from subscription payments on Stripe but the payments could still end.  Eg. if the payment method expired (credit card expiry date passed), or was cancelled on the bank side (card cancelled) or otherwise failed (payment bounced).

Not sure how this needs to be handled or if it's possible to automate, so logging it while I remember.

**Comment by willdurand** [comment]
We'll handle that manually assuming Stripe sends emails to Stripe admins. If that's not the case, we'll have to listen to some Stripe events and send notifications _via_ AMO.

**Comment by willdurand** [comment]
> We'll handle that manually assuming Stripe sends emails to Stripe admins. If that's not the case, we'll have to listen to some Stripe events and send notifications _via_ AMO.

FWIW, we listen to `charge.failed` Stripe events and send an email to admins.

**Comment by ioanarusiczki** [comment]
@willdurand ID:620297, Sponsored addon: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/a-test-of-failed-payment

**Comment by ioanarusiczki** [comment]
@willdurand I received an e-mail 
From: Mozilla Add-ons <nobody@mozilla.org> 
To: verified-addons@mozilla.com

Content: 

![failed subscription](https://user-images.githubusercontent.com/33448286/99230522-1b666480-27f8-11eb-816a-a99090b614a4.png)

**Comment by ioanarusiczki** [comment]
@willdurand I'll mark this verified but please take a look at the e-mail content, looks incomplete at the end.

**Comment by willdurand** [comment]
@ioanarusiczki no, it's alright
