### ISSUE TITLE
Make sure we only consider "active" add-on developers when determining whether 2FA is required

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15848]
We should make sure that only _active_ add-on developers are considered when we require a 2FA protected account during login. Internally, when an author gets removed from an add-on, the relationship _add-on ←→ user_ stays, but is marked as "_Deleted_". We should exclude such relations when checking add-on ownership.

//cc @diox

**Comment by diox** [comment]
`cached_developer_status` (and therefore `is_developer` / `is_extension_developer` / `is_theme_developer`) should likely check whether or not the user is an active author.

**Comment by diox** [comment]
I've checked : `<user>.addons`, `<user>.addonuser_set`, `<addon>.authors` and `<addon>.addonuser_set` automatically filter out deleted relationship (the `AddonUser` manager defaults to filtering them out), so `cached_developer_status` (and therefore `is_developer` / `is_extension_developer` / `is_theme_developer`) are already doing the filtering as well.

**Comment by AlexandraMoga** [comment]
I've tried to cover again the multiple statuses a developer account can have, to confirm that the expected 2FA scenario is triggered:

2FA is not required in the following situations:
- the user is removed from an add-on additional authors list
- the user deleted all owned add-ons
- the user is banned

2FA is still required in the following situations:
- developer add-ons are set to Invisible
- developer add-ons have been disabled\force-disabled

@diox just to reconfirm, theme developers should still not be required to set-up 2FA right?

**Comment by diox** [comment]
> @diox just to reconfirm, theme developers should still not be required to set-up 2FA right?

Correct.
