### ISSUE TITLE
Django admin for version claims license is mandatory

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15850]
### Describe the problem and steps to reproduce it:

I am trying to edit a version on the django admin page for versions, for exmaple setting or unsetting the `needs_human_review` flag.

### What happened?

I can't save the page because django complains that the _License_ field is required.

### What did you expect to happen?

Page should save even if the license is not set.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand I could save the [Version](https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1655434/change/) page without any License added - verified on dev with FF82(Win10).
