### ISSUE TITLE
Add confirmation page when changing a promoted group in the django admin

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15863]
With the new subscription system, changing the group of a promoted add-on might have implications.

For groups that require payment, we should change a few things in Stripe (like cancelling the subscription when we remove an add-on from a promoted group).

This issue is about adding a confirmation ~~page~~ message when the group of a promoted add-on is changed.

**Comment by ioanarusiczki** [comment]
@willdurand There's a confirmation message displayed when trying from admin to change the group from verified or sponsored to any other:

![admin message](https://user-images.githubusercontent.com/33448286/99543910-63ce7f80-29bc-11eb-9d41-81e5f317703d.png)

This shows up for already paid addons but also for those that did not go through the process yet. Let me know so I can mark this issue verified.
