### ISSUE TITLE
Review pages don't show a complete information about the resign

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15869]
A followup for https://github.com/mozilla/addons-server/issues/15784#issuecomment-717883465

The review pages for the add-ons show for the approved verified/sponsored a "Version 3.0.1-signed" if originally it was "Version 3.0" but the date of the approval is still the original one. 

![sample one](https://user-images.githubusercontent.com/33448286/97588841-901e5e00-1a05-11eb-9971-de81f2a7071f.png)

When the version has been approved manually in the past, the info about who reviewed the addon won't change.  Approved by Mozilla should be also displayed at resign because it's an auto-approval.

![sample2](https://user-images.githubusercontent.com/33448286/97589095-d1167280-1a05-11eb-85d7-5a7bce9bbc43.png)

**Comment by eviljeff** [comment]
I'm thinking I'll fix this by adding an activity log entry for the resign - that way it'll show up in the review history that it happened, and by the task user.

**Comment by ioanarusiczki** [comment]
@eviljeff There's one problem, I see the resign. But instead of "Mozilla", the name of the developer(owner of the verified/sponsored addon) is displayed. 

![the developer](https://user-images.githubusercontent.com/33448286/98820113-6cf8a300-2436-11eb-86e6-84e74215222b.png)
