### ISSUE TITLE
Expose the version we're re-signing to the developer in the subscription payment page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15867]
We tell the developer we'll resign the current version of the addon but we don't make clear which version that is (and that'll be version bumped slightly)

**Comment by willdurand** [comment]
We have new content in the PRD: https://docs.google.com/document/d/1cohRp8JRlv7h41I0MxFUK1oBk70th71Fa7g4sGruzpM/edit?ts=5f99ddbd

**Comment by ioanarusiczki** [comment]
@eviljeff I did not see a version number in the subscription flow, at the beginning or after making the payment I get "You're done" and the button that redirects to edit product page (as before). I checked for addons with an already approved version.

**Comment by eviljeff** [comment]
Btw, this isn't working because we rely on `addon_already_promoted` to determine what to show in the template - specifically to check that the add-on wasn't grandfathered in from the trial so was already promoted at the point the subscription was made; but _that_ relies on checking if there are existing approved versions.  We then approve the version before rendering the template so `addon_already_promoted` is always true at that point.

**Comment by ioanarusiczki** [comment]
@eviljeff 
1. Verified re-signed 

![verified resigned](https://user-images.githubusercontent.com/33448286/99383681-e4b34b80-28d6-11eb-9ffb-26dc5e83197f.png)

Sponsored re-signed

![sponsored resigned](https://user-images.githubusercontent.com/33448286/99383707-eda41d00-28d6-11eb-844c-be93248c3dea.png)

2. When the add-on was signed for an approved version and has a newer version that is pending review: 

![Scenario2](https://user-images.githubusercontent.com/33448286/99385139-35c43f00-28d9-11eb-9376-278bdbb147e9.png)


3. When the add-on is in awaiting review and has no other versions approved, the message is "You're done" (as it used to be).  I think the PRD mentions a different content:

![Scenario3](https://user-images.githubusercontent.com/33448286/99385668-fba76d00-28d9-11eb-8cea-1cd997d2d12c.png)

I filed https://github.com/mozilla/addons-server/issues/16020

**Comment by eviljeff** [comment]
> When the add-on is in awaiting review and has no other versions approved, the message is "You're done" (as it used to be). I think the PRD mentions a different content:

Can you elaborate?  The PRD mentions when there are _no_ versions, and prompts the developer to upload one "Please upload a new public version in order to complete this process." but this wouldn't be the case if there was already a version awaiting review - there isn't anything for them to do (hence, they're done).

**Comment by ioanarusiczki** [comment]
@eviljeff Yeah, you're right, when there's a version in "awaiting review" , "You're done" is the expected message.

I tested around and I have the following results:

- deleted addons cannot be added to the promoted model.

- disabled addons can be added to the promoted model: 
1. when an [addon](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/disabled-first-version1) is disabled from dev hub and then the id is added to the promoted model, a payment is completed, the success page shows:

![Scenario3](https://user-images.githubusercontent.com/33448286/99533113-092e2700-29ae-11eb-8ca1-21cc54695e16.png)

2. when the addon is disabled from the review page I don't get the above message.  So perhaps, this scenario should be filed.
This is an [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/disabled-first-version1)

      In this case, the Success message is: 
"You're done! A new version 1.0.1-signed of your add-on Disabled first version will be published as Sponsored and should become available shortly. If you have any questions, don’t hesitate to contact us. " even if the disabled version was not re-signed.

- blocked addons can be added to the promoted model. Success message displayed is the one described at disabled 1.
