### ISSUE TITLE
Add Stripe Customer Portal to manage billing

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15878]
We could use [Stripe Customer Portal](https://stripe.com/docs/billing/subscriptions/customer-portal) to offload billing management to Stripe. This portal would allow us to have a nice webpage to update the card information or email for example (we can do more).

@jvillalobos I think we need this to allow our customers to update their card information in the future. If there is a payment issue, we could tell them to go back to the onboarding page and click the "Manage billing" button:

update: see below (link/button moved to DevHub edit page)

Then they would see this page (on Stripe):

<img width="1619" alt="Screenshot 2020-10-30 at 15 53 11" src="https://user-images.githubusercontent.com/217628/97720018-0aafb200-1ac8-11eb-9dd1-c4de5c846f07.png">

Stripe Customer Portal requires 2 URLs, though:

- a Privacy Policy URL
- a Terms of Service URL

---

For QA: only add-ons that are verified or sponsored should have the link to "manage billing on Stripe". In addition to that, the link should only appear when the subscription is active, which means it has been paid once (when the onboarding flow has been completed).

It shouldn't be possible to change the subscription or cancel it. It should be possible to change the email address or the billing information (credit card).

**Comment by willdurand** [comment]
Yes, it is configurable. The second screenshot shows no way to cancel as we discussed.

**Comment by jvillalobos** [comment]
Okay, that sounds good.

> If there is a payment issue, we could tell them to go back to the onboarding page and click the "Manage billing" button:

I would add a link to the sidebar in the extension edit page instead, below Manage Status & Versions.

> Stripe Customer Portal requires 2 URLs, though:
>    a Privacy Policy URL

https://www.mozilla.org/privacy/websites/

>    a Terms of Service URL:

https://extensionworkshop.com/documentation/publish/firefox-add-on-distribution-agreement/

**Comment by willdurand** [comment]
> I would add a link to the sidebar in the extension edit page instead, below Manage Status & Versions.

Okay, something like this then?

<img width="1046" alt="Screenshot 2020-11-03 at 14 31 32" src="https://user-images.githubusercontent.com/217628/97991251-7b651000-1de1-11eb-92f3-735d7b7031de.png">

**Comment by jvillalobos** [comment]
Yes, but with an upper case "B" in "Billing", please.

**Comment by ioanarusiczki** [comment]
@willdurand 

On AMO dev with FF82(Win10). I could test this only with new addons (as expected). I have 404 for the older subscritions when the Billing URL is clicked:

- the Billing URL is available on edit product page after a first payment is done. Changing information about the card and e-mail address is possible. Navigating back and forth to this page is possible.

![Billing Add-ons](https://user-images.githubusercontent.com/33448286/98379178-aeacd680-204f-11eb-8ac6-d0b799451f33.gif)

Other things noticed:
- the verified standard fee is 10$ per month. sponsored is 60$ per year. So right now I can set a custom onboarding rate per month for verified addons and per year for sponsored addons. 

- when making a first payment and try to cancel it: if I use the browser's back button to navigate back to dev hub from the Stripe page I won't see the error message so I always use the button displayed on that page. I think the gif below explains it better: 

![error with the back button](https://user-images.githubusercontent.com/33448286/98380442-43640400-2051-11eb-8113-60465cb591b8.gif)

- also in this scenario when the user cancels, but then repeats the payment steps and completes payment the admin offers details only about when payment was completed. "Link visited at" will is empty. If it's a problem with that let me know. 

![cancellation](https://user-images.githubusercontent.com/33448286/98380953-ec126380-2051-11eb-9c34-0f087a451f02.png)

- should I see somewhere Privacy Policy and Terms of Service URL from https://github.com/mozilla/addons-server/issues/15878#issuecomment-719771977 ?

**Comment by willdurand** [comment]
>     * the verified standard fee is 10$ per month. sponsored is 60$ per year. So right now I can set a custom onboarding rate per month for verified addons and per year for sponsored addons.

This will be fixed soon (it should actually be fixed already

>     * when making a first payment and try to cancel it: if I use the browser's back button to navigate back to dev hub from the Stripe page I won't see the error message so I always use the button displayed on that page. I think the gif below explains it better:

yeah, that's normal.


>    should I see somewhere Privacy Policy and Terms of Service URL from #15878 (comment) ?

Yes, somewhere in the Customer Portal.

**Comment by ioanarusiczki** [comment]
@willdurand 

>  should I see somewhere Privacy Policy and Terms of Service URL from #15878 (comment) ?

> Yes, somewhere in the Customer Portal.

Terms is https://stripe.com/en-ro/customer-portal/legal
Privacy is https://stripe.com/en-ro/privacy

![Terms and Privacy](https://user-images.githubusercontent.com/33448286/98674604-b88d4d00-2361-11eb-80b9-a3d5ed526da5.png)

**Comment by willdurand** [comment]
@ioanarusiczki I think it's somewhere else then :p Maybe when you update your information?

**Comment by ioanarusiczki** [comment]
@willdurand Ah, yes! It's in Add payment method: "By adding a payment method, you agree to Ad ons - Dev's Terms of Service and Privacy Policy." The URLs redirect as expected.
