### ISSUE TITLE
add validation to prevent `*` in a block min_version

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15877]
Using `*` in a min_version produces unexpected behaviour, because `*` in a version string isn't strictly a wildcard (it's an infinitely high number so as a _maximum_ version it's always highest).  In a min_version `0` is what is needed instead.  So we should prevent `*` from being accidentally used with validation.

See https://github.com/mozilla/addons-server/issues/15798#issuecomment-718947625 for some more detail.

**Comment by AlexandraMoga** [comment]
This issue is Verified fixed on -dev:

`*` no longer allowed:
![image](https://user-images.githubusercontent.com/31961530/98128906-2993b700-1ec1-11eb-9b92-88584928fa91.png)
