### ISSUE TITLE
Default locales are not really changed in Account settings

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1588]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Login to AMO and go to your Account Settings
2.Change default locale to any other language (ie. Francais) and save the changes
3.Open the "Localize For" drop down menu
4.Observe the "Default Locale" field

Expected results:
"Defalult Locale" field from "Localize for" dropdown menu is the one set at Step 2

Actual results:
"Default Locale" field from "Localize for" dropdown menu is still English

Please see screencast for this bug : http://screencast.com/t/Cs5Ke12URUw

**Comment by EnTeQuAk** [comment]
I think this will be changed somewhere in the far future with our bigger revamp of things so I'm closing this for now since I believe a reimplementation will either remove this feature or fix it cleanly.
