### ISSUE TITLE
Changing an archive extension to .crx will trigger a server error at validation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#15889]
### Describe the problem and steps to reproduce it:
1. Have a valid add-on archive - an `.xpi` or `.zip` 
2. Change the archive extension to `.crx`
3. Submit the archive on AMO -dev

### What happened?
A 500 validation error:
![image](https://user-images.githubusercontent.com/31961530/97870130-2fe82e80-1d1b-11eb-8a5b-2d8ded18aa24.png)

### What did you expect to happen?
The validation should not fail with a server error

### Anything else we should know?
- probably a regression from #15849 
- this used to work before as a workaround to avoid the `.crx` validation error - see https://github.com/mozilla/addons-server/issues/14036#issuecomment-609663818

**Comment by diox** [comment]
We should not 500, but this was never supposed to work. It should raise a proper error indicating to the user that it's not a valid crx file.

**Comment by AlexandraMoga** [comment]
I've verified this issue on dev and the 500 error for `.zip` archives renamed as `.crx` is no longer reproducible. 

@diox I was under the impression that the validation should now error with an "Invalid archive" message, but from what I've seen, there was no error raised. The renamed archive produces the same validation results as the original one.

**Comment by diox** [comment]
That depends on the file.
- Renaming `.zip` to `.crx` should now work (we attempt to parse it as a CRX, fail, fall back to normal zip)
- Renaming a random file like a `.png` to `.crx` should raise `Invalid or corrupt add-on file.`.
- Submitting a `.png` or other non-extension file type directly should raise `Unsupported file type, please upload a supported file (...)` with the accepted extensions list.

Obviously, submitting a valid .zip, .xpi or .crx should still work as normal.

**Comment by AlexandraMoga** [comment]
Yes, when a non-supported file is being renamed as an apparently valid file (i.e .`zip`, `.xpi`, `.crx`) the "Invalid or corrupt add-on file" error message is received. Directly submitting a non-supported file type (i.e `.png`, `.xml` etc) will result in an "Unsupported file type" message. 

Valid add-on files are behaving the same as before.

This isssue is verified fixed on -dev.
