### ISSUE TITLE
CI with github actions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15899]
Given the recent changes at travis-ci we want to investigate if github actions is a viable alternative

**Comment by diox** [comment]
We'll need to check with Mozilla Github ops, as it's disabled org-wide at the moment. There were security concerns initially, which I think can be addressed with some configuration, but more importantly some cost questions (because of the plan Mozilla is under for Github)

**Comment by eviljeff** [comment]
re: cost, https://github.com/pricing (and other pages) state "Free for public repositories" - that may be something that conflicts with our (legacy) org settings on github though.

**Comment by eviljeff** [comment]
progress with https://github.com/eviljeff/olympia/blob/actions-investigation-flat/.github/workflows/test.yml
6 of 9 jobs passing.  The following tests are still failing:

### reviewers-and-zadmin - test fails
FAILED src/olympia/reviewers/tests/test_utils.py::TestReviewHelperSigning::test_nominated_to_public_recommended
FAILED src/olympia/reviewers/tests/test_utils.py::TestReviewHelperSigning::test_nomination_to_public

### amo-lib-locales-and-signing - errors
___________________________ TestMonitor.test_signer ____________________________
________________________ TestSigning.test_call_signing _________________________
__________ TestSigning.test_call_signing_on_file_in_guarded_file_path __________


### main - test fails
FAILED src/olympia/git/tests/test_utils.py::test_temporary_worktree - Asserti...
FAILED src/olympia/git/tests/test_utils.py::test_get_mime_type_for_blob[entry19-foo.ts-text-text/javascript]

the 2 fails and 3 errors appear to be autograph related.  The main test fail causes are unclear.

**Comment by eviljeff** [comment]
progress with https://github.com/eviljeff/olympia/blob/actions-investigation-flat/.github/workflows/test.yml - a single failing test remains:
- FAILED src/olympia/git/tests/test_utils.py::test_temporary_worktree

**Comment by eviljeff** [comment]
Apart from the last remaining failing test, there are no other blockers on CI side.  

Re: security concerns - it's possible to limit actions to just github provided ones, or by wildcard, so I don't know if that would assuage some of the concerns.

Improvements:
- We should add caching to improve performance (there's a github provided cache action); 
- It's possible we could gain some performance, or complexity, improvements by having elasticsearch/autograph as services rather than setting them up ourselves.
- We might be able to get details of the failing tests output as annotations to be shown on the run summary page (they're all just `Process completed with exit code 1.` currently which is a bit pointless)
- I'm not sure we strictly need tox any longer with the ability to add conditionals in the workflow directly.  It'd be a non-trivial task to convert the setup but the end configuration would be more flat and probably more easily manageable (though we would end up with a much larger workflow file)
- Notification to Slack support?

**Comment by willdurand** [comment]
We switched to circle-ci so we probably don't need this issue anymore? at least, not until circle-ci goes crazy?

**Comment by eviljeff** [comment]
Afaik the position on github actions (which may have shifted while I was off) was that it was the desirable end solution, but we didn't want to jump into it while the security and org-operational aspects were still up in the air.  Switching to Circle-ci in the mean-time was forced on us by travis-ci.
