### ISSUE TITLE
Disable addons-linter's XPI auto-close feature

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15909]
Let's try to disable the linter's XPI auto-close feature to see if it improves the overall performances.

For QA: there should be no noticeable impact. Submission and validation should work just fine.

**Comment by willdurand** [comment]
Auto-close feature disabled on -dev (i.e. switch is active)

**Comment by AlexandraMoga** [comment]
I've submitted several add-ons on -dev and stage using DevHub and the signing API and I did not find issues with the validation and submission.

I'm marking this issue as verified fixed.
