### ISSUE TITLE
Excluded deleted authorship on django pages

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#15906]
### Describe the problem and steps to reproduce it:

STR:
1. Submit a new add-on using a new account A.
2. In the devhub for the add-on, add author B (and accept the invite)
3. Remove account A from authorship.
4. With XXXXX being the user id for account A:
  a) Go to `/admin/models/users/userprofile/XXXXX/change/`
  b) Go to `/admin/models/addons/addon/?authors=XXXXX`

### What happened?

a) Under add-ons, the count is 1.
b) In the list, the add-on submitted in step 2 is shown.

### What did you expect to happen?

a) Under add-ons, the count is 0.
b) In the list, no add-ons are shown.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
We settled on an implementation in https://github.com/mozilla/addons-server/pull/16133 that deals with this in slightly different way:
a) Deleted authors are included when showing the count, but using a separate count from the regular one
b) All add-ons are shown in the list, even if the user is no longer an author, but we show the list of authors and their current role, so it's possible to distinguish between authors that have been removed and active ones

**Comment by ioanarusiczki** [comment]
@diox I verified this on AMO dev, FF84(Win10) - and I think it works as expected:
- Deleted roles  from the [addon detail page](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10642158/change/) have separate count and redirect to https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?authors=10642158 where the Author column shows that the user has been deleted.
