### ISSUE TITLE
Add logging around discrepancies between Adzerk and Elasticsearch in sponsored helves API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15919]
The [Sponsored Shelves API](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#sponsored-shelf) uses Adzerk to retrieve which add-ons to show (Adzerk returns the ids) and then fetches the data from Elasticsearch, forcing add-ons that are returned to be promoted and public.

If somehow an add-on is present in the Adzerk data but not returned when we perform the Elasticsearch query, something weird is going on and we should log that to investigate later.

**Comment by eviljeff** [comment]
is standard logging in stackdriver sufficient, or is something extra needed?  (e.g. counting occurrences with statsd)

**Comment by diox** [comment]
I was thinking standing logging initially, and we could set up some alerting in stackdriver, but looking back maybe we should do both standard logging _and_ statsd and use grafana for email alerting like we do elsewhere.

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa in case this can be tested. 
Thanks!
