### ISSUE TITLE
Create grafana dashboard for Adzerk integration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#15935]
We're recording metrics various metrics but not displaying anywhere currently.  We need to create a grafana dashboard, preferably with a selector to switch between dev, stage, and prod (only dev is likely to have data currently).

We may want alerts adding for more than X fails or es misses from the results.

**Comment by eviljeff** [comment]
https://earthangel-b40313e5.influxcloud.net/d/-H3fPX2Gz/adzerk

alert added for prod elasticsearch misses >0

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some STR. 
Thanks!

**Comment by eviljeff** [comment]
I don't think you have access to grafana so marking as not needed
