### ISSUE TITLE
Use verified-addons list for any promoted add-ons communications

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#15931]
We created a new list, verified-addons AT mozilla DOT com, that we'll use for any related messaging. Let's use this list instead of amo-admins as the support contact in the onboarding flow, as well as for any messaging that comes from Stripe.

For QA: the email address displayed when the user returns from Stripe Checkout without completing the process (i.e. they click on "Back" in Stripe Checkout) should be this new address.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev - FF82(Win10): 

![new email address](https://user-images.githubusercontent.com/33448286/98675949-9ac0e780-2363-11eb-9aca-5680737fb4cd.png)
