### ISSUE TITLE
Don't redirect to django users that don't have a mozilla e-mail address

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#15930]
Followup for https://github.com/mozilla/addons-server/issues/10113#issuecomment-722292203

1. I've added to the Add-ons Reviewer group a user with an e-mail address different than mozilla.com and added the Ratings:Moderate permission. 
2. Go to a disabled addon review page -> https://reviewers.addons.allizom.org/en-US/reviewers/review/facebook-container88
3. Click the rating URL

Expected result:
it should be read only 

Actual result:
It's throws a 403 Forbidden error

Notes:
reproducible on AMO stage - FF82(Win10).

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by tushar912** [comment]
I am new to contributing here. I would like to work on this @caitmuenster @eviljeff can u help me get started !

**Comment by caitmuenster** [comment]
Hey @tushar912, welcome! 🙌 Make sure you start off by reading our [onboarding documentation](https://wiki.mozilla.org/Add-ons/Contribute/Code). If you have any specific questions, you can tag @eviljeff in a comment. 

We'll assign you to the issue once you have submitted a PR. 

Happy bug fixing!

**Comment by eviljeff** [comment]
The fix is just a matter of making `acl_is_review_moderator` be defined as `request.user.is_staff()` too.  The test changes are more work - `test_review_moderator_addon_rating_present` will fail so it will have to fixed.

**Comment by tushar912** [comment]
Should I change <code>acl_is_review_moderator</code> as <code> acl_is_review_moderator=acl.action_allowed(
            request, amo.permissions.RATINGS_MODERATE
        ) and request.user.is_staff </code>

**Comment by tushar912** [comment]
@eviljeff

**Comment by eviljeff** [comment]
> Should I change `acl_is_review_moderator` as ` acl_is_review_moderator=acl.action_allowed( request, amo.permissions.RATINGS_MODERATE ) and request.user.is_staff `

yes

**Comment by shehrozkapoor** [comment]
Hi i am new in open source and want to contribute i want fix this error.how i can get started i have already completed the step 1 and step 2.can somebody guide me how i can get assigned for this error.
Thanks

**Comment by caitmuenster** [comment]
Hi @shehrozkapoor, welcome! You'll want to make sure that you have read our [onboarding documentation](https://wiki.mozilla.org/Add-ons/Contribute/Code#Improve_addons.mozilla.org_.28AMO.29) to set up your dev environment, then follow [eviljeff's instructions](https://github.com/mozilla/addons-server/issues/15930#issuecomment-728816320) to create a patch. Once you have submitted a PR, we will assign you to the issue.

**Comment by shehrozkapoor** [comment]
Hi  @caitmuenster  thanks for your response can you please specify what is PR?

**Comment by caitmuenster** [comment]
Sure thing @shehrozkapoor! It's a pull request. :) Github has some good documentation about pull requests here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by shehrozkapoor** [comment]
Thanks!

**Comment by shehrozkapoor** [comment]
@eviljeff  @caitmuenster can you help me with this error it is coming after i run make initialize command
![Screenshot 2020-12-10 at 5 40 58 AM](https://user-images.githubusercontent.com/59894229/101706158-57fd4700-3aaa-11eb-81bb-7b72d9792634.png)

**Comment by eviljeff** [comment]
> @eviljeff @caitmuenster can you help me with this error it is coming after i run make initialize command

Github issues are not the place to debug setup problems - see the links to discourse/Matrix in the [onboarding documentation](https://wiki.mozilla.org/Add-ons/Contribute/Code#Improve_addons.mozilla.org_.28AMO.29) @caitmuenster provided.

**Comment by renancleyson-dev** [comment]
Can I work on this?

**Comment by eviljeff** [comment]
> 
> 
> Can I work on this?

doesn't look like anyone is currently working on this, so go ahead.

**Comment by ioanarusiczki** [comment]
@eviljeff Verified on AMO dev - FF85(Win10). 

![readonly](https://user-images.githubusercontent.com/33448286/106153715-82ed4880-6187-11eb-84ef-5a3eec54738b.png)
