### ISSUE TITLE
Restrict add-on detail/versions API and download views for add-ons in specific regions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15942]
addons-server companion to https://github.com/mozilla/addons-frontend/issues/9842, we need some add-ons to be restricted in some specific regions.

addons-frontend and nginx (*) will pass a `X-Country-Code` header to API requests to the add-on detail and versions API requests indicating the region the client request is originating from, in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format. We need to add a table containing add-on region exclusions for a given add-on, probably just stored as flat json list of country codes. When an add-on is requested from a restricted country, we need to return a HTTP 451 response instead of the normal detail page response.

This same logic also needs to be added to download views.

As a follow-up, we'll likely need something to be added to be able to bypass this if logged in as an admin, while adding something to the response to indicate to the frontend that we bypassed the restriction, but this doesn't have to be implemented right away.

(*) We will have to let clients override the header, because of addons-frontend server side rendering. We may have some config in nginx to only allow that under specific circumstances though, to prevent clients from playing with this.

**Comment by eviljeff** [comment]
As another follow-up, I think we should expand this to /search queries (any elastic-search based response really).  Returning a match and _then_ telling the user they can't have it seems a poor experience.

**Comment by diox** [comment]
It should be a super rare occurrence, so I would prefer not to do that if we can. If do we end up filtering out searches then IMHO we'll need something in the response also indicating that a particular search queries was filtered out because of geo-restrictions - making it explicit that it happened. Otherwise it will be a pain to debug user issues (who are already complaining about search ranking sometimes).

**Comment by diox** [comment]
QA: there is no admin to add the georestrictions yet, so when you're ready to test this, ask us to set some on specific add-ons and we'll do that and give more instructions. Ideally you'd have some VPN available to test from different countries.

**Comment by AlexandraMoga** [comment]
@diox I've selected a few add-ons and added several country restrictions (based on the connections my VPN allows) to each of them. I've listed the data in this [spreadsheet](https://docs.google.com/spreadsheets/d/1z_8396CysghGNGK0XPPaVArITYddpu-dzGW8LvEezHs/edit?usp=sharing) for better tracking. Let me know if you need more details from me.

I'm waiting for test instructions once the test data is set-up.

**Comment by diox** [comment]
I've set up the data.

Regarding testing: in this issue you can focus on the API & download endpoints only. You can test the full behavior in the frontend issues.
- add-on detail, version list and version detail for add-ons excluded in your region should return a 451 error response explaining the add-on is not available for legal reasons
- add-on search endpoint should not be affected
- Links to download the add-on XPIs (those starting with https://addons-dev.allizom.org/ that you can find in the API responses, *not* links starting with https://addons-dev-cdn.allizom.org/user-media/) should also return a 451 response when requested from an excluded region
- Reviewers and add-on owners should still be able to download even from an excluded region
- If the add-on is deleted or disabled this should take precedence: we shouldn't return a 451 response in those cases, but a 404/403/401 instead.

**Comment by AlexandraMoga** [comment]
@diox I've verified this on -dev by using the API and the frontend in parallel. Here are my test results:

- the Detail, version list and version detail API of a public add-on will throw a `451 - Unavailable For Legal Reasons` when accessed from an excluded region for every user group; for non-excluded regions, the endpoints will return the add-on/version details
- the Detail, version list and version detail API of a Disabled add-on will throw a 401 for unauthenticated users and a 403 for authenticated regular users - the frontend will display a 404 page in this case; this applies both to excluded and non-excluded regions
- for Deleted add-ons, the endpoints will throw a 404 when accessed by regular users or previous owners; this applies both to excluded and non-excluded regions
- the download file URL of a public add-on will throw a 451 when accessed from an excluded region for every user group - filed #16006 as a follow up to address the issue about reviewers and owners; the file is downloaded when accessed from non-excluded regions
- for Disabled add-ons, the download file URL can be accessed by admins, reviewers and owners both from excluded and non-excluded regions; regular users will receive a 404
- for Deleted add-ons, the download file URL can be accessed by admins and reviewers both from excluded and non-excluded regions; regular users and previous owners will receive a 404
- the search endpoint is not affected - the excluded add-ons are still returned in search and autocomplete APIs while their detail pages will return a 451

Question:
- for Deleted or Disabled add-ons, the Detail and version detail endpoints will return a 451 when viewed from an excluded region by admins, reviewers or owners(for disabled). These users could normally access the endpoints, but the region exclusion will block their access. Let me know if I should file a follow up issue for this case.

**Comment by AlexandraMoga** [comment]
@eviljeff  for the issue I've raised above

> * for Deleted or Disabled add-ons, the Detail and version detail endpoints will return a 451 when viewed from an excluded region by admins, reviewers or owners(for disabled). These users could normally access the endpoints, but the region exclusion will block their access. Let me know if I should file a follow up issue for this case.

it looks like #16014 might fix it.  Maybe you can confirm that this is indeed the case?

**Comment by eviljeff** [comment]
@AlexandraMoga it should address that, yes.  (From the issue conversation so far, looks like it'll just be admins that won't get the 451)

**Comment by AlexandraMoga** [comment]
I will mark this issue as verified fixed for now. We can file an issue afterwards if it is decided that the 451 should be bypassed for reviewers and owners as well.
