### ISSUE TITLE
Investigate removal of `compat_with_app` and `compat_with_appver` fields on `FileUpload`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15945]
`compat_with_app` and `compat_with_appver` fields on `FileUpload` don't seem to be used. Investigate if there is somehow some code using it hidden somewhere and if not, remove them. They are already nullable, but we would still need to do it in two steps:
1. Remove from the models
2. One week after, commit the migration removing the fields entirely from the database.

**Comment by Sparsh-Bansal** [comment]
In the property `processed_validation`, compatibility of the file is checked by the `compat_with_app` field 
(`is_compatibility = self.compat_with_app is not None`). On removing the field , process_validation will always takes its default value (`is_compatibility = False`). So should I remove the field or there are some more changes regarding to variable `is_compatibility`.

**Comment by diox** [comment]
Remove `is_compatibility` argument from `process_validation()` entirely as well as the `mangle_compatibility_messages()` function.

**Comment by caitmuenster** [comment]
We're marking this as a good first bug and are expecting Sparsh-Bansal's PR to be reviewed soon. :)

**Comment by Sparsh-Bansal** [comment]
@diox Should i commit the migrations in the current PR only or land a new PR for it .
