### ISSUE TITLE
Allow reviewers to Approve and Reject add-ons set to invisible

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#15958]
Hello, 
on this review page: https://reviewers.addons.mozilla.org/en-GB/reviewers/review/tatkalplus
Approve and Reject action are not visible.
We don't know why.

Regards,
Hubert LAFONT

**Comment by eviljeff** [comment]
@wagnerand

**Comment by diox** [comment]
It's marked as needing admin code review.

**Comment by lafonth** [comment]
I am an admin reviewer. All the rest of the admin review team does not see Approve and Reject action buttons

**Comment by wagnerand** [comment]
I *assume* it's because the add-on status is invisible.

**Comment by diox** [comment]
Same, I just noticed that. It's by design (the add-on shouldn't even be in a queue as a result), but I suppose we don't want to keep that ?

**Comment by wagnerand** [comment]
I was thinking the same thing. Even if invisible, reviewers should probably still be able to reject an approved version. (It shouldn't be possible to have a pending version in an invisible add-on, although it happens occasionally due to unidentified bugs.)
