### ISSUE TITLE
Investigate how to create a second PromotedSubscription for a promoted add-on

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15967]
Once https://github.com/mozilla/addons-server/issues/15805 lands, we'll handle subscription cancellation but it won't be possible to create a new promoted subscription for the same promoted add-on.

I think we should keep all `PromotedSubscription` records in an "archived" state or something. It should be possible to see past promoted subscriptions for an add-on (maybe with a new admin?).

Let's see how we can do that.

**Comment by willdurand** [comment]
see also https://github.com/mozilla/addons-server/pull/15947#discussion_r520556353

**Comment by eviljeff** [comment]
Can we just have multiple `PromotedSubsubscription` records per `PromotedAddon`?  (the fk would have to be changed from `OneToOneField`.  Would also probably need a constraint to keep the data sane).

**Comment by willdurand** [comment]
> Can we just have multiple `PromotedSubsubscription` records per `PromotedAddon`? (the fk would have to be changed from `OneToOneField`. Would also probably need a constraint to keep the data sane).

Yes, I think that's the plan but we'll have to make sure we can only have one active subscription at a time.

Can we delete promoted add-on records? If so, we'll have to make sure we don't delete promoted subscriptions I think or prevent deletion of promoted add-ons.

**Comment by eviljeff** [comment]
afaik, yes, you can delete PromotedAddon records.  (At the time the model was added, deleting them was exactly the same as setting them to NOT_PROMOTED)

**Comment by eviljeff** [comment]
I think we can close this (at least for now)
