### ISSUE TITLE
Add admin for georestrictions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15968]
https://github.com/mozilla/addons-server/issues/15942 will initially land without an admin, but we should have one. It should be implemented as a regular django admin, with an email notification going out for every addition/modification/deletion that includes the details of the changes because it's so sensitive.

**Comment by willdurand** [comment]
Did we consider dual signoff?

> an email notification going out for every addition/modification/deletion that includes the details of the changes because it's so sensitive.

Who will receive such emails?

**Comment by diox** [comment]
Dual signoff doesn't seem appealing given that all admins can silently disable or even delete add-ons without dual signoff right now.

amo-admins@ should receive the notification email.

**Comment by eviljeff** [comment]
@diox I started working on this while you were away 😉 - the email functionality is split into #16022 so we can get the core admin into the tag.

**Comment by AlexandraMoga** [comment]
@eviljeff I've verified the new [Addon Regional Restrictions](https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addonregionalrestrictions/) admin on stage and I have the following results:

- add-ons can be restricted for one or multiple regions, the exclusions being reflected in the API and when the detail page is accessed on the frontend
- the exclusion is removed when the addon restriction is deleted in the admin
- admins can add or remove country codes for an existing addon restriction 



Some observations:

- the help text for the Addon input field mentions that admins can enter a slug and that will be automatically converted to the addon id. I have entered several slugs but each time I receive an error message:
![image](https://user-images.githubusercontent.com/31961530/99545657-4bf7fb00-29be-11eb-9bb1-1beb0904a865.png)


- #16023 will enforce uppercase input for Excluded regions. Shouldn't there also be a note or message of some kind to specify that the region codes need to be in [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) format?

**Comment by eviljeff** [comment]
>     * the help text for the Addon input field mentions that admins can enter a slug and that will be automatically converted to the addon id. I have entered several slugs but each time I receive an error message:
>       ![image](https://user-images.githubusercontent.com/31961530/99545657-4bf7fb00-29be-11eb-9bb1-1beb0904a865.png)

Looks like I forgot to copy over that functionality (Or I shouldn't have copied over the help text)

>     * #16023 will enforce uppercase input for Excluded regions. Shouldn't there also be a note or message of some kind to specify that the region codes need to be in [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) format?

#16023 adds help text too.

**Comment by AlexandraMoga** [comment]
> Looks like I forgot to copy over that functionality (Or I shouldn't have copied over the help text)

Maybe #16023 can update that help text as well, as a bonus 😋
