### ISSUE TITLE
Revert MySQL changes in `2020.11.12` tag

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#15975]
-stage does not seem alright and Sentry shows lots of MySQL errors, mostly about unicode, e.g., https://sentry.prod.mozaws.net/operations/olympia-stage/issues/10006401/?query=is%3Aunresolved or https://sentry.prod.mozaws.net/operations/olympia-stage/issues/10006128/?query=is%3Aunresolved

QA says homepage, DevHub and reviewer tools are affected so it's very likely caused by the changes to the `Dockerfile` in:

- https://github.com/mozilla/addons-server/commit/09030e01bb5118ad21ee20852db7ab58c5d0dd6d
- https://github.com/mozilla/addons-server/commit/374b3ec84e9a5ee0957d76b59680d6c7e2415138

-dev and local dev aren't affected because we're using MySQL 8 but -stage does not AFAIK.

Reverting the commits above will allow us to push this week as usual and have some more time to fix the problems. This is going to be tricky given that we're now using MySQL 8 for local dev.

**Comment by willdurand** [comment]
@eviljeff was able to reproduce the problem in a django shell using this snippet (ssh'ed on -stage):

```
Translation.objects.filter(id__in=(5312,))
```

We reverted the two commits mentioned above in `2020.11.12-1`

**Comment by willdurand** [comment]
Looks like -stage is back now.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, no errors on dev hub, admin tools or frontend.
