### ISSUE TITLE
Addons-server requires increasing amount of instances starting from August

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#15995]
### Describe the problem and steps to reproduce it:

During last week and this week's pushes, we noticed that the AMO website threw a bunch of 5xx errors for a short period of time, right after we promoted the new instances.

Upon investigation, we have found the following:

Historically, and for the past 4-5 years, the amo_olympia component (a.k.a. the addons-server) has never needed more than 12 instances. Thus, we set the initial number of instances in the ASG to 12, and that has never been a problem in all these years. However, starting from around 8/27, the component has started to demand more and more instances. And nowadays, it requires at least 22 instances just for normal operations. As a result, when we switch to a new stack that only has 12 instances, the capacity is far blow what the component needs, which causes the 5XX right after the promotion of the new stacks, then ASG autoscaling kicks in, which adds more instances, and 5XX goes away.

Below is a chart that shows the increasing number of instances needed by the addons-server ELB for the past 6 months:

<img width="1083" alt="Screen Shot 2020-11-12 at 10 58 29 AM" src="https://user-images.githubusercontent.com/2209111/98998221-a4288c00-24ea-11eb-9ef2-748d42c0b24b.png">

### What happened?
It is unclear what the root cause is at the moment. However, we looked at the number of incoming requests for the a.m.o domain for the past 6 months, and it doesn't look like that has increased at all.

<img width="1473" alt="Screen Shot 2020-11-12 at 1 47 10 PM" src="https://user-images.githubusercontent.com/2209111/99000163-afc98200-24ed-11eb-963a-67ea38931d06.png">

### What did you expect to happen?
We should figure out and fix what has caused the olympia_web component needing more computing resources, assuming the increased demand is not due to the organic growth of our user base.

There are a few drawbacks I can think of if we let the number of instances grow continuously,

* increased pressure on olympia_web's downstream components, the database in particular has seen CPU usage increased by almost 4 times over the same period of time.

<img width="1480" alt="Screen Shot 2020-11-12 at 1 55 41 PM" src="https://user-images.githubusercontent.com/2209111/99000859-c6bca400-24ee-11eb-9a36-f3b73fa44e21.png">

* increased deployment time (since as a temporary workaround, we need to spin up at least 22 instances for the new stack)

* increased operation cost

### Anything else we should know?
n/a

**Comment by bqbn** [comment]
According to https://mozilla.slack.com/archives/C4MTGNZ7S/p1598433399007600, we pushed scanner v1.11 to -prod on 8/26. Other than that, I don't think we push any other code to -prod in the last 2 weeks of August.

**Comment by bqbn** [comment]
In newrelic, it looks like the response time for olympia_web component is increasing overtime as well.

https://chart-embed.service.newrelic.com/herald/ff705b12-2939-4afe-ab88-cfded93a9b29

This seems to indicate the component is becoming slower processing requests. The slowness could explain the increase of CPU usage (a.k.a. cpu load), which triggers the auto-scale-up events.

And, when we check the nginx logs for a random day (11/18 for example), the average response time for the `/api/` end point is about 200 ms with the 50th percentile being 236 ms.

**Comment by eviljeff** [comment]
can we see if it's _more_ database queries being made in the (same number of) requests, or a similar number of database requests taking more time?  (I'm assuming it's database related - but is that true either?)

**Comment by bqbn** [comment]
RDS doesn't have a metric to measure how many queries it receives over time. It has a metric that shows how many connections have been made to it, the trend of which looks increasing over a period of 4 months, but not as dramatically as the trend of the number of app instances.

The CPU usage of the db replicas has been increasing a lot as shown above.

**Comment by bqbn** [comment]
We notice that the olympia_web instances can slowly use up all the memory and when that happens it stops responding and ASG will take it out and replace it with a new instance. The ASG will log an event like below:

<img width="1033" alt="Screen Shot 2020-11-20 at 2 34 25 PM" src="https://user-images.githubusercontent.com/2209111/99856300-850aa980-2b3d-11eb-8a46-affb5bd284e0.png">

And the memory usage for the past 6 hours looks like below

<img width="710" alt="Screen Shot 2020-11-20 at 2 30 11 PM" src="https://user-images.githubusercontent.com/2209111/99856352-a8cdef80-2b3d-11eb-8cd7-21348a6f994e.png">

It can be seen that starting from 1:30pm quite a few instances reached 100% memory usage and was terminated by ASG and replaced with new instances.

**Comment by bqbn** [comment]
This past weekend wasn't very peaceful. In Friday night (between 22:00pm and 1:00 am), a lot of instances reached 100% memory usage, stopped responding and were then replaced by ASG. 

<img width="702" alt="Screen Shot 2020-11-23 at 5 41 09 PM" src="https://user-images.githubusercontent.com/2209111/100035564-61509900-2db3-11eb-87b7-d08bba59c1af.png">

We had to put in a temporary uWSGI config change in order to stabilize the ASG (thus the number of healthy instances in the ELB). We had to set the uWSGI [max-requests](https://uwsgi-docs-additions.readthedocs.io/en/latest/Options.html#max-requests) to a lower value. Historically, its value has been set to 5000, meaning a uWSGI worker is recycled after it has handled 5000 requests. An instance would reach 100% memory usage before a uWSGI worker can handle that many requests. So we now set this value to 1000, and the memory usage has been kept in 50-55% range. 

However, we now need at least **36** ec2 instances during peak hours.

**Comment by diox** [comment]
> And, when we check the nginx logs for a random day (11/18 for example), the average response time for the /api/ end point is about 200 ms with the 50th percentile being 236 ms.

It would be interesting to dig in into which endpoints exactly are slower. Can you help us do that with nginx logs ? We do have [a grafana dashboard showing performance for most APIs ](https://earthangel-b40313e5.influxcloud.net/d/kiTC7XDZz/amo-prod-frontend-apis-usage-performance?orgId=1&from=now-6M&to=now) and while there are increases in certain APIs recently it's hard to say if it's related, as none start at the date we noticed the problem started occurring.

(Also, from a quick look the recent slowness is not things tied to code changes on our part - it's collections being (ab)used by Fenix and TAAR being slower/errorring more, for the most part)

**Comment by diox** [comment]
I've filed 2 issues:
- https://github.com/mozilla/addons-server/issues/16062 for collections add-ons list endpoint related slowdown
- https://github.com/mozilla/addons-server/issues/16063 for taar-related slowdown

The first one is more and more likely to be related. Fenix has been requesting that endpoint to fetch the list of recommended add-ons available for mobile, and the beginning of our issues coincides with the release of Fenix. We can also see the endpoint being slower and slower over time as more add-ons are added to the collection(s) Fenix uses, as well as another increase when they started bumping the number of add-ons returned in a single request from 25 to 50.

![Screenshot_2020-11-30 AMO Prod frontend APIs usage performance - Grafana](https://user-images.githubusercontent.com/187006/100601723-3ca07800-3303-11eb-835e-77a68784facc.png)
![Screenshot_2020-11-30 AMO Prod frontend APIs usage performance - Grafana(3)](https://user-images.githubusercontent.com/187006/100608071-2e0a8e80-330c-11eb-94ae-98cb654adba2.png)

**Comment by bqbn** [comment]
We enabled "[Performance Insights](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.html)" for the replicas, which is a feature of AWS RDS (see https://www.youtube.com/watch?v=yOeWcPBT458 for an introduction of it).

<img width="1129" alt="Screen Shot 2020-11-30 at 11 19 20 PM" src="https://user-images.githubusercontent.com/2209111/100711708-87071080-3366-11eb-8d8a-be3a1226d2f7.png">


It looks like the query that puts the most load on the database is,

```
SELECT `translations` . `created` , `translations` . `modified` , `translations` . `autoid` , `translations` . `id` , `translations` . `locale` , `translations` . `localized_string` , `translations` . `localized_string_clean` FROM `translations` WHERE ( `translations` . `id` = ? AND `translations` . `localized_string` IS NOT NULL ) 
```

The next two queries are,
```
SELECT `licenses`.id, IF(!ISNULL(t1_name.localized_string), t1_name.created, t2_name.created)
            AS name_created,IF(!ISNULL(t1_name.localized_string), t1_name.modified, t2_name.modified)
            AS name_modified,IF(!ISNULL(t1_name.localized_string), t1_name.autoid, t2_name.autoid)
            AS name_autoid,IF(!ISNULL(t1_name.localized_string), t1_name.id, t2_name.id)
            AS name_id,IF(!ISNULL(t1_name.localized_string), t1_name.locale, t2_name.locale)
            AS name_locale,IF(!ISNULL(t1_name.localized_string), t1_name.localized_string, t2_name.localized_string)
            AS name_localized_string,IF(!ISNULL(t1_name.localized_string), t1_name.localized_string_clean, t2_name.localized_string_clean)
            AS name_localized_string_clean,IF(!ISNULL(t1_text.localized_string), t1_text.created, t2_text.created)
            AS text_created,IF(!ISNULL(t1_text.localized_string), t1_text.modified, t2_text.modified)
            AS text_modified,IF(!ISNULL(t1_text.localized_string), t1_text.autoid, t2_text.autoid)
            AS text_autoid,IF(!ISNULL(t1_text.localized_string), t1_text.id, t2_text.id)
            AS text_id,IF(!ISNULL(t1_text.localized_string), t1_text.locale, t2_text.locale)
            AS text_locale,IF(!ISNULL(t1_text.localized_string), t1_text.localized_string, t2_text.localized_string)
            AS text_localized_string,IF(!ISNULL(t1_text.localized_string), t1_text.localized_string_clean, t2_text.localized_string_clean)
            AS text_localized_string_clean FROM `licenses` LEFT OUTER JOIN translations t1_name
          ON (t1_name.id=`licenses`.name AND t1_name.locale='en-us')
LEFT OUTER JOIN translations t2_name
          ON (t2_name.id=`licenses`.name AND t2_name.locale='en-US')
LEFT OUTER JOIN translations t1_text
          ON (t1_text.id=`licenses`.text AND t1_text.locale='en-us')
LEFT OUTER JOIN translations t2_text
          ON (t2_text.id=`licenses`.text AND t2_text.locale='en-US')
             WHERE `licenses`.id IN (6) 
```
and
```
SELECT COUNT ( * ) AS `__count` FROM `reviews` WHERE ( NOT ( `reviews` . `deleted` = ? ) AND `reviews` . `reply_to` IS NULL AND `reviews` . `addon_id` = ? AND `reviews` . `is_latest` = ? ) 
```

It's not clear why most of the load has to do with "sending data" and "sending to client" though, but it might be because the client isn't fetching the results all at once.

**Comment by bqbn** [comment]
> It would be interesting to dig in into which endpoints exactly are slower. Can you help us do that with nginx logs ?

I can if it is still needed. However, it looks like the Collection API has been identified as having to do with this? The timing in the screenshot matches the timing in the first comment.

**Comment by eviljeff** [comment]
> It looks like the query that puts the most load on the database is,
> 
> ```
> SELECT `translations` . `created` , `translations` . `modified` , `translations` . `autoid` , `translations` . `id` , `translations` . `locale` , `translations` . `localized_string` , `translations` . `localized_string_clean` FROM `translations` WHERE ( `translations` . `id` = ? AND `translations` . `localized_string` IS NOT NULL ) 
> ```

That's used to retrieve all user translated fields so it's expected it'll be very frequently called.

> The next two queries are,
> 
> ```
> SELECT `licenses`.id, IF(!ISNULL(t1_name.localized_string), t1_name.created, t2_name.created)
>             AS name_created,IF(!ISNULL(t1_name.localized_string), t1_name.modified, t2_name.modified)
>             AS name_modified,IF(!ISNULL(t1_name.localized_string), t1_name.autoid, t2_name.autoid)
>             AS name_autoid,IF(!ISNULL(t1_name.localized_string), t1_name.id, t2_name.id)
>             AS name_id,IF(!ISNULL(t1_name.localized_string), t1_name.locale, t2_name.locale)
>             AS name_locale,IF(!ISNULL(t1_name.localized_string), t1_name.localized_string, t2_name.localized_string)
>             AS name_localized_string,IF(!ISNULL(t1_name.localized_string), t1_name.localized_string_clean, t2_name.localized_string_clean)
>             AS name_localized_string_clean,IF(!ISNULL(t1_text.localized_string), t1_text.created, t2_text.created)
>             AS text_created,IF(!ISNULL(t1_text.localized_string), t1_text.modified, t2_text.modified)
>             AS text_modified,IF(!ISNULL(t1_text.localized_string), t1_text.autoid, t2_text.autoid)
>             AS text_autoid,IF(!ISNULL(t1_text.localized_string), t1_text.id, t2_text.id)
>             AS text_id,IF(!ISNULL(t1_text.localized_string), t1_text.locale, t2_text.locale)
>             AS text_locale,IF(!ISNULL(t1_text.localized_string), t1_text.localized_string, t2_text.localized_string)
>             AS text_localized_string,IF(!ISNULL(t1_text.localized_string), t1_text.localized_string_clean, t2_text.localized_string_clean)
>             AS text_localized_string_clean FROM `licenses` LEFT OUTER JOIN translations t1_name
>           ON (t1_name.id=`licenses`.name AND t1_name.locale='en-us')
> LEFT OUTER JOIN translations t2_name
>           ON (t2_name.id=`licenses`.name AND t2_name.locale='en-US')
> LEFT OUTER JOIN translations t1_text
>           ON (t1_text.id=`licenses`.text AND t1_text.locale='en-us')
> LEFT OUTER JOIN translations t2_text
>           ON (t2_text.id=`licenses`.text AND t2_text.locale='en-US')
>              WHERE `licenses`.id IN (6) 
> ```

I'm hoping this and the translations query will be at least partially fixed by https://github.com/mozilla/addons-server/issues/16081 because both of them were occurring _a lot_ with the collection/addons api endpoint (currently used by Fenix)

**Comment by diox** [comment]
Note that fetching license text is always going to be somewhat slow just because of the amount of data being transferred compared to a "regular" database query. All of that would go away if Fenix switched to the search endpoint...

**Comment by bqbn** [comment]
It has been discussed in the slack channel, but today's push didn't fix the issue, and the CPU usage of the web instances remains the same level as before.

<img width="708" alt="Screen Shot 2020-12-03 at 12 11 27 PM" src="https://user-images.githubusercontent.com/2209111/101130012-87e2b100-35b7-11eb-8490-23601d1b1d72.png">

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/16081 should make the collection API scale better and https://github.com/mozilla/addons-server/issues/16102 should hopefully fix the cache issues. Because of the large amount of traffic driven by Fenix to their collection though, even that might not be enough. We're looking at:
- (short term) Having Fenix use services.a.m.o domain so that we can cache things on nginx or move that domain to being served by a CDN
- (medium/long term) Having Fenix request a single language at once. That should dramatically improve things
- (medium/long term) Having Fenix use the search endpoint.

Bonus: currently Fenix makes a request to the API endpoint without a trailing slash, forcing us to serve a redirection. We're hoping they can change that short-term as well - it's literally a one-character fix.

**Comment by bqbn** [comment]
Are there tickets created for Fenix to do the above? If we've reached an agreement with them, hopefully there is a way for us to track the progress of the ideas.
