### ISSUE TITLE
Review History in Manage versions page is broken when viewed from a region where the add-on is restricted 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16005]
Follow up for #15942 

### Describe the problem and steps to reproduce it:
1. Sign in to AMO-dev with a developer account that has some add-ons submitted
2. With an admin account, restrict one of the developer's add-ons in a specific country
3. With the developer account, open the add-on Manage versions page in Dev-hub while being connected from the region in which the add-on has been restricted
4. Click on the version Review History

### What happened?
An error message with a broken layout is being displayed (see screenshot). The message displays the 451 error response returned by the `/api/v4/addons/addon/620244/versions/1692213/reviewnotes/` endpoint. 

### What did you expect to happen?
We can either show the review notes to add-on owners and reviewers, or display a nicer error message.

### Anything else we should know?
- Reviewer notes are being displayed on the add-on review page, but I think that's because we do not rely on the version detail API there to retrieve those notes.
- This [addon](https://addons-dev.allizom.org/en-US/developers/addon/search-extensionggff/versions) is restricted in FR and the issue should be visible when logged in with an admin account

![image](https://user-images.githubusercontent.com/31961530/99086124-c0532880-25d1-11eb-8d49-5141816eeafb.png)

**Comment by eviljeff** [comment]
This is a variation on the need to be able to override the restrictions as an admin/owner of the add-on - currently any sub endpoint under addons/addon/ ends up undergoing the same permission checks.  
(We might want to prioritize fixing this separately if enhancing the API generally is a larger task)

**Comment by AlexandraMoga** [comment]
The add-on Review History is now being displayed in excluded regions to admins, reviewers and users listed as Owners or Developers of the add-on.

![image](https://user-images.githubusercontent.com/31961530/99803085-7c1bd700-2b41-11eb-9ff7-76a3b809de61.png)


I'm marking this issue as verified fixed on -dev.
