### ISSUE TITLE
Force AddonRegionalRestrictions.excluded_regions to be uppercase

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16023]
follow-up from #15968 - due to how we match the results we need the country codes to be uppercase but we don't enforce (or inform about) that requirement.

**Comment by AlexandraMoga** [comment]
The country codes entered in the Excluded regions field are now automatically converted to uppercase. The help text was also updated to mark that the codes need to be in  ISO 3166-1 alpha-2 format. Note that this does not mean there is an actual validation on the input field to ensure that the user has provided a valid code. 

![image](https://user-images.githubusercontent.com/31961530/99819870-b47adf80-2b58-11eb-874d-095984bccee2.png)

I'm marking this issue as verified fixed on dev.
