### ISSUE TITLE
email amo-admins when AddonRegionRestrictionsAdmin is used

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16022]
follow-up for #15968 to add the email functionality

**Comment by AlexandraMoga** [comment]
An email is received by amo-admins when an add-on region restriction is [added](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/95672/change/), [changed](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/95673/change/) or [deleted](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/95674/change/).

I'm marking this issue as verified fixed on dev.
