### ISSUE TITLE
change adzerk integration to use multi-winner placement

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16038]
https://dev.adzerk.com/reference/multi-winner-placements

It's apparently more efficient to ask use multi-winner placements than specifically request 6 placements.  the `count` is a maximum rather than a specified count, but normal placements don't always return 6 responses either so 🤷

**Comment by ioanarusiczki** [comment]
@eviljeff Currently, I did not edit anything with Adzerk or django admin meaning there should be the old 6 available addons added for dev and stage:
- the the dev API is returning a set of 3, 4, 5 addons in the Sponsored shelf and so does the frontend.
- the stage API is returning constantly 6 addons and so does the frontend. 

Let me know if testing for this issue involves changing something and then observe behavior, such as maybe adding new addons in Adzerk. 

Thanks!

**Comment by eviljeff** [comment]
it doesn't seem to be any better or worse for getting 6 results than before - if stage is working then I think we'd good.
