### ISSUE TITLE
An addon with disabled version should have a different success message displayed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16039]
STR:

1. An addon has a first version approved but then it's disabled by a reviewer - with the Force disable add-on button
2. In case the id is added to the promoted add-ons and a developer completes the payment the success message is:

![wrong message](https://user-images.githubusercontent.com/33448286/99817480-a7102600-2b55-11eb-8fd2-5f208f443a9d.png)

Expected message:

![Scenario3](https://user-images.githubusercontent.com/33448286/99533113-092e2700-29ae-11eb-8ca1-21cc54695e16.png)

Notes:
I don't think that's a scenario which will be applied in production but technically the success message is incorrect.
It is reproducible on AMO dev - FF83(Win10). 
The issue is not reproducible in case the addon is disabled by the developer (as mentioned here https://github.com/mozilla/addons-server/issues/15867#issuecomment-729682484)

**Comment by eviljeff** [comment]
payment integration is being removed so we can close this
