### ISSUE TITLE
Moving with arrow keys between app results when creating a collection will not highlight the selected addon

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1605]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Go to MP and create a new collection
2.Write a searchterm in "Add to collection" section
3.Move with UP\DOWN arrow keys between search results

Expected results:
Selected addons are underlined

Actual results:
Selected addon is not underlined

Please see screencast for this bug : http://screencast.com/t/vK9FB7EWq

NOTES:
When hovering the results with the mouse, the selected addons are correctly underlined

**Comment by andymckay** [comment]
Given the likelihood that collections are going to be removed in the future, I'm marking this as "won't fix".
