### ISSUE TITLE
Sort scanner results by `-pk` instead of `-created`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16068]
See: https://github.com/mozilla/addons-server/issues/15970#issuecomment-726064548

**Comment by AlexandraMoga** [comment]
@willdurand should this have an impact on how the [admin scanner results](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/) are actually sorted? For the record, the list is still sorted by Creation date, as it was expected before.

**Comment by willdurand** [comment]
> @willdurand should this have an impact on how the [admin scanner results](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerresult/) are actually sorted? For the record, the list is still sorted by Creation date, as it was expected before.

No it should not have any impact. It should load faster but the order should be the same (because pk is auto-incremented)

**Comment by AlexandraMoga** [comment]
The scanner results ordering and filtering is the same as before. I could not say that I've noticed faster loading, but maybe this si not that much noticeable on the numbers we have on -dev and stage. 

This issue is verified fixed on -dev and stage.
