### ISSUE TITLE
Listen to successful payments

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16070]
As recommended by Security, we should send an email to AMO admins when a successful payment has been made.

---

For any payment, there should be an email sent to admins.

**Comment by willdurand** [comment]
@diox looks like my implementation from 3 weeks ago ignores expected succesful payments (i.e. payments are bound to a known promoted subscription). I was thinking that it would send less emails that way. WDYT?

**Comment by diox** [comment]
I think we want a notification even for those bound to a known promoted subscription. That way if a promoted subscription has been erroneously created for some reason admins would get a chance to catch that as well.

**Comment by willdurand** [comment]
works for me, I am a bit afraid of spamming the email but it is simpler to implement so 🤷

**Comment by ioanarusiczki** [comment]
@willdurand I verified on AMO dev - I think this is about the payment message only, meaning that another message when making an addon promoted as mentioned https://github.com/mozilla/addons-server/issues/16070#issuecomment-736642000 is not available yet. 

Successful payment for a verified/sponsored addon: 

![successful payment](https://user-images.githubusercontent.com/33448286/101348826-f7e18780-3894-11eb-8b93-3fbe20635094.png)

E-mail is sent to verified-addons@mozilla.com

**Comment by willdurand** [comment]
> @willdurand I verified on AMO dev - I think this is about the payment message only, meaning that another message when making an addon promoted as mentioned [#16070 (comment)](https://github.com/mozilla/addons-server/issues/16070#issuecomment-736642000) is not available yet.

@ioanarusiczki this comment means we want to get an email for _any_ successful payment, not that we'll get an email when an add-on is promoted.

**Comment by ioanarusiczki** [comment]
@willdurand Ah ok, then work is complete here.
