### ISSUE TITLE
Add list of interesting accounts in local dev login page

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16084]
For people like me who have a bunch of different accounts locally with different sets of permissions, it's always a pain to remember which account has what and what email address I used.

If `settings.DEBUG` and `settings.USE_FAKE_FXA_AUTH` are `True` we have a completely fake login page anyway, so we should suggest interesting accounts there, for instance listing those that have any special permissions, making it easier to juggle through different accounts locally.

**Comment by eviljeff** [comment]
While you're at it, can some copy be added explaining that it's unconnected to a "real" login so can be any email address - and a `@mozilla.com` is needed to access /admin?  (It could be in the docs, but the page is there and pretty empty so why not explain at the point it's useful information)
