### ISSUE TITLE
"By Firefox" extensions should receive weighted search

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#16086]
Similar to Recommended extensions, "By Firefox" extensions should also receive the benefit of weighted search on AMO. Indeed in most cases our own Mozilla line extensions would be Recommended if not for the "By Firefox" designation (e.g. Facebook Container). 

@jvillalobos

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified on AMO dev- FF83(Win10), I added the same name for multiple addons - from all promoted categories and not promoted. 

"UBlock Origin" - from homepage

![uBlock](https://user-images.githubusercontent.com/33448286/101774515-e4355b80-3af6-11eb-87f3-8c50a900bc34.png)

"open image in a new tab" inside an addon category

![category search](https://user-images.githubusercontent.com/33448286/101775292-eb109e00-3af7-11eb-8da5-0d47f31f75d9.png)
