### ISSUE TITLE
optimize CollectionAddonViewSet queryset performance

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16081]
follow on from #8831 (that added caching).

A single list request for CollectionAddonViewSet makes a large number of queries, and some of them are per addon, so it doesn't scale well.  We should change the queries so that at least all the results are retrieved in a single query - a collection with 100 addons should have the same number of queries as a collection with 1 addon inside.

**Comment by eviljeff** [comment]
The fix in the PR makes the query scale, but there is still some redundancy/excess that could be cleared up for more performant responses.  Largely they are
- a request without `?lang` loads all the translations at once, but the default querysets include transforms which load a single translation (in the default locale) too - those are redundant queries.  Unfortunately the querys are often within other transforms so it will be a challenge to pass down the signal to not load the default translations.
- the CollectionAddonSerializer includes a full AddonSerializer so there is a lot of potentially unnecessary data retrieved (dropping tags and version licenses alone would save 4 queries)

**Comment by eviljeff** [comment]
QA: to test performance improvements a collection with a significant number of add-ons needs to be used.  Essentially, before: the response time would get worse and worse with the number of add-ons in a collection; and now: the response time should be similar-ish (it'll still get slower as the amount of data returned increased, but not to the same degree)

Ideally you'd compare dev vs. stage performance with collections with a similar number of add-ons to confirm the patch improves the situation.

To skip the caching added in #8831 either be logged in to AMO (if testing via frontend) or append some random params to the url (if testing by calling the underlying API call)

**Comment by ioanarusiczki** [comment]
@eviljeff 

results for dev versus stage, collections each made of 100 addons:

https://addons-dev.allizom.org/api/v4/accounts/account/10641566/collections/testingthecollections/addons/?sort=popularity
time: 335ms, 390ms, 357ms
https://addons.allizom.org/api/v4/accounts/account/11686381/collections/list/addons/?sort=popularity
time: 813 ms, 1548 ms, 1118 ms

https://addons-dev.allizom.org/api/v4/accounts/account/10641566/collections/testingthecollections/addons/?sort=added
time: 1271ms, 616 ms, 414 ms
https://addons.allizom.org/api/v4/accounts/account/11686381/collections/list/addons/?sort=added
time: 1011mms, 1257 ms, 993 ms

https://addons-dev.allizom.org/api/v4/accounts/account/10641566/collections/testingthecollections/addons/?sort=name
time: 472ms, 614 ms, 518 ms
https://addons.allizom.org/api/v4/accounts/account/11686381/collections/list/addons/?sort=name
time: 1342ms, 795 ms, 741 ms

I've checked the frontend too and I think that dev responds quicker than stage. 
The dev collection: https://addons-dev.allizom.org/en-US/firefox/collections/10641566/testingthecollections/?page=1&collection_sort=added
Stage collection: https://addons.allizom.org/en-US/firefox/collections/11686381/list/?page=2&collection_sort=added

**Comment by diox** [comment]
I cherry-picked on stage and ran some tests before and after in https://gist.github.com/diox/0c32eafa80c449abb0ef339379eca5cb but the data appears to be inconsistent, I'm seeing slightly better numbers now...

**Comment by ioanarusiczki** [comment]
AMO stage results:

- on frontend, user is logged in, navigates from a page to another from page 1 to page 4, the network timing is: 424 ms, 470 ms, 401 ms. 
- on frontend, user is logged in, on page 1 changes the sort parameters. Oldest first: 435 ms,  Name: 448 ms, Popularity: 339 ms. 

AMO dev results:
- first scenario: 451 ms, 486 ms, 471 ms.
- second scenario: Newest first: 339 ms, Name: 336 ms, Popularity: 355 ms.

Postman results on AMO dev:
- changing pagination, page 2:366 ms, page 3: 400 ms, page 4: 305 ms
- changing sort parameters, popularity : 327 ms, name: 343 ms

Postman results on AMO stage:
- changing pagination, page 1:1052 ms, page 2: 351 ms, page3: 316 ms.
- changing sort parameters, popularity : 400 ms, name: 381 ms 

The network timing looks similar with the time returned by Postman and dev similar with stage.
