### ISSUE TITLE
Show amount of matched add-ons in scanner query rules list

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16092]
The scanner query rules list already shows the amount of matched results. It would be helpful if it also showed the amount of matched add-ons.

**Comment by diox** [comment]
We could add some denormalized fields for the results count and add-on count for perf. But we could also just start with the query and see how that goes.

For posterity, note that in the ORM there are 2 ways to do it:
- `rule.results.values_list('version__addon').distinct().count()`, which generates a subquery + a temporary table
- `rule.results.aggregate(count=Count('version__addon', distinct=True))['count']` which uses the more straightforward (and more optimized) `SELECT COUNT(DISTINCT versions.addon_id)`

**Comment by ioanarusiczki** [comment]
@diox I checked the scanner query rule table on AMO dev - FF84(Win10): matched results column displays the amount of matched add-ons too.
