### ISSUE TITLE
Synchronize FxA email changes to keep communication up to date

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1609]
We can use FxA's new [service tokens](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/service-clients.md) feature to retrieve email addresses from FxA as they might change (which could happen externally in FxA). This will help in communicating with developers since AMO sometimes sends out emails.

**Comment by mstriemer** [comment]
Currently the user's email address is copied over when they log in. I don't think FxA currently supports changing your email address.

It might make sense to stop treating AMO email as 1:1 with the FxA email and allow users to change their email on AMO without copying it over. I'm not sure how this would work in that case.

**Comment by kumar303** [comment]
>  I don't think FxA currently supports changing your email address

Huh, I didn't know that. This feature probably isn't very useful until FxA supports changing email addresses.

**Comment by rfk** [comment]
> I don't think FxA currently supports changing your email address

That's correct, but it's on our roadmap to allow this at some point.

**Comment by EnTeQuAk** [comment]
It's fixed (but not yet enabled on -prod) via https://github.com/mozilla/addons-server/issues/6451

**Comment by vcarciu** [comment]
Can you please add some STRs to this issue?

**Comment by kumar303** [comment]
Someone can correct me if I'm wrong but I think these are some STR:

* Log into AMO for the first time with an email like `first-email@gmail.com`
* Go To Firefox Accounts and change your email to `second-email@gmail.com`
* Do something on AMO that will send you an email. All I can think of is:
  * Create an add-on, upload it to Devhub, publish it
  * Sign in as a different user
  * Rate the add-on from its detail page
  * (This should send an email like *A user has left a review for your add-on...*. However, I think emails might be disabled in dev/stage. Do we still have an admin tool to see what emails would have been sent?)
* The email notification should have been sent to `second-email@gmail.com`, not `first-email@gmail.com`

**Comment by vcarciu** [comment]
Verified as fixed using the steps from @kumar303 and I found an issue related to the fact that a logout\login is needed in AMO in order to update the primary email, but logged a different issue for that.
