### ISSUE TITLE
Investigate cache issues in production

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16102]
We deployed 2020.12.03 yesterday as normal, expecting the [cache added for the Collections Add-ons API endpoint](https://github.com/mozilla/addons-server/issues/16062) to help with the [scaling issues](https://github.com/mozilla/addons-server/issues/15995) we noticed recently.

Unfortunately, that did not work as expected. We can see on this graph the endpoint remains slow:
![Screenshot_2020-12-04 AMO Prod frontend APIs usage performance - Grafana](https://user-images.githubusercontent.com/187006/101154117-98ca0b80-3625-11eb-8d81-8942cd248b55.png)

When testing manually via `curl`, we can see we're being served a cache response when the `Expires` points to a date that's less than one hour in the future. Here is what it can look like on stage, where it does work as expected:

```
% curl -s https://addons.allizom.org/api/v4/accounts/account/4760859/collections/f2b87cb7-9a00-1c0d-64d0-0911e7/addons/ -I
# Wait 2 minutes...
% curl -s https://addons.allizom.org/api/v4/accounts/account/4760859/collections/f2b87cb7-9a00-1c0d-64d0-0911e7/addons/ -I | egrep 'Date|Expires'
Date: Fri, 04 Dec 2020 10:46:46 GMT
Expires: Fri, 04 Dec 2020 11:44:21 GMT
```

We did see that happening in prod, but not often as we'd like. Most of the time we appear to be served fresh content. We asked Wei for some sample URLs from nginx and they all looked normal.
```
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210472 "-" "Mozilla/5.0 (Android 10; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210339 "-" "Mozilla/5.0 (Android 9; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210339 "-" "Mozilla/5.0 (Android 8.1.0; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210447 "-" "Mozilla/5.0 (Android 10; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210447 "-" "Mozilla/5.0 (Android 10; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210315 "-" "Mozilla/5.0 (Android 10; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210315 "-" "Mozilla/5.0 (Android 10; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
"GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 210321 "-" "Mozilla/5.0 (Android 5.0.1; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
```

There are some minor variations in the `User-Agent`, which would cause the cache key to be different (we `Vary` on it, which we shouldn't do but that's a topic for another day), but not that many.

Because local envs, dev & stage appear to be working normally, we suspect there is something wrong with prod.

**Comment by diox** [comment]
Digging into memcached graphs, we can see:

### Increased CPU usage & connections on memcached servers
![Screenshot_2020-12-04 amo by wezhou - Grafana(1)](https://user-images.githubusercontent.com/187006/101155508-88b32b80-3627-11eb-961e-fa4f175ecfa2.png)
![Screenshot_2020-12-04 amo by wezhou - Grafana](https://user-images.githubusercontent.com/187006/101155511-894bc200-3627-11eb-9f3b-d967949f1b5d.png)

IMHO, this is expected: we weren't using memcached intensively before, and now we're using it for an endpoint that receives a lot of traffic. It's the entire point. That shouldn't be a problem.

### Cache misses higher than cache hits

We never had a very good cache hit ratio, again because we didn't cache a lot of things. But now, we'd expect the cache to be hit quite a lot, as we're caching the collection API for 1 hour, for a given set of query parameters + some specific headers. This is not what we're seeing on the graph:
![Screenshot_2020-12-04 amo by wezhou - Grafana(2)](https://user-images.githubusercontent.com/187006/101155881-10993580-3628-11eb-8153-bf3b07e4c068.png)

### Memory usage and number of items

It's a little hard to see on those screenshots, but the graphs show something weird: number of items and used/free memory on the 3 memcached nodes is wildly different. Our nodes are extremely overkill for our usage, but we should have relatively uniform distribution. What we see is that 003 has a lot more items and more used (and almost no free) memory:
![Screenshot_2020-12-04 amo by wezhou - Grafana(4)](https://user-images.githubusercontent.com/187006/101156536-0d527980-3629-11eb-9986-77223fd906b8.png)
![Screenshot_2020-12-04 amo by wezhou - Grafana(3)](https://user-images.githubusercontent.com/187006/101156541-0deb1000-3629-11eb-8e0f-63322792271d.png)

### Evictions and reclaimed space

Eviction graph confirms something weird is going on with node 0003. It keeps evicting (turquoise line) and reclaiming (blue spikey line) keys, especially after the push:

![Screenshot_2020-12-04 amo by wezhou - Grafana(5)](https://user-images.githubusercontent.com/187006/101156754-5acee680-3629-11eb-993e-0202e9e79841.png)

**Comment by diox** [comment]
Some things it'd be interesting to look at:
- Find out the exact keys django is using for the cache we're interested in.
- Compression should be enabled at the client level, so we should always be able to store the API responses we want to cache even though they are quite large. But it'd be interesting to see exactly how large they are.
- Related to that, slab stats are likely going to be relevant. Maybe we're just storing too many things in a single slab somehow and that's causing our evictions.

**Comment by diox** [comment]
> Related to that, slab stats are likely going to be relevant. Maybe we're just storing too many things in a single slab somehow and that's causing our evictions.

While we still don't know why the distribution is so skewed, I suspect the most likely scenario is that the slab(s) that we'd want to use for collections API responses caching on node 0003 are completely full and memcached is struggling to adapt to the new data that's all coming in to that/those slab(s). If that's the case, just restarting the node (pulling it out of the cluster first, which requires a redeploy to do cleanly I think) would be enough. If we go that route we might want to consider the `lru_crawler` and  `lru_maintainer` parameters, which can help with this kind of situation.

**Comment by bqbn** [comment]
We rebooted node 0003 at around 11 am PST and will give it some time and see how it goes.

**Comment by bqbn** [comment]
So 5 hours after we rebooted 0003, the eviction situation seems to have improved.

<img width="709" alt="Screen Shot 2020-12-04 at 3 57 41 PM" src="https://user-images.githubusercontent.com/2209111/101226528-98dc0280-3649-11eb-8784-3df28039751e.png">

But the hits vs misses hasn't improved,

<img width="715" alt="Screen Shot 2020-12-04 at 3 57 56 PM" src="https://user-images.githubusercontent.com/2209111/101226590-cde85500-3649-11eb-964d-79da79a2bea0.png">

The number of misses are still much more than the number of hits. I think that's probably why we still see high CPU usage in the web instances and in the database.

Almost all hits are GET hits, and misses are GET misses and DELETE missis (about half and half each).

**Comment by diox** [comment]
I've been investigating this and found something interesting.

We're using django's `@cache_page` decorator, applied to the `list()` method. So when we're calling `list()` because of a `GET` request on the API, we're supposed to check the cache first, return the cached response if any, or generate the response, store it in the cache, and return it as normal. 

The "thing" we store in the cache is a full `HttpResponse` object, pickled. For regular django's `HttpResponse`s most of the time it wouldn't matter that much - the response needs to be rendered first (which generates the `_container` attribute that is used by the `content` property), there would be some overhead but not that much. In our case though, it's a rest_framework's `Response`, not a django's `HttpResponse`. It initially contains a `data` attribute with a dictionary containing all the data to be returned, but once rendered it *also* contains the bytes content in the `_container` attribute. So the size of the pickled response is roughly twice as big as the returned content.

It matters here because the uncompressed size of the json is around 673K - because Fenix requests the collection without passing a language, so we return all known translations for those add-ons. So the pickled response is about 1.3 MB which is too big to store in memcached by default - the default limit is 1MB. `python-memcached` silently fails storing the data in memcached, and we never get a cache hit the next time around - the data has never been stored in the cache.

This would explain the cache hits/miss : while we do have a long tail of add-ons and collections, the hit/miss ratio was weird because it was so consistent. You'd expect that eventually, even with a super long tail, we'd end up successfully caching something and improving the ratio. But we likely aren't because the vast majority of cache requests are for that specific response we aren't managing to store in the cache.

The one thing this theory does *not* explain though, is that we've seen cached responses from prod a few times, so there is still something we are missing.

**Comment by diox** [comment]
> The one thing this theory does not explain though, is that we've seen cached responses from prod a few times, so there is still something we are missing.

I think that's because when we tested, we looked at collections in general, not the specific one Fenix is using, so it worked (sometimes, when the data didn't get evicted from the cache) because the collection used wasn't as large.

**Comment by diox** [comment]
QA: try https://github.com/mozilla/addons-server/issues/16062#issuecomment-736394318 again, especially with collections with lots of add-ons (which themselves contain lots of data if possible, we want to test with larger size responses - large translations in multiple languages is the best way to bump up the size)

**Comment by AlexandraMoga** [comment]
@diox I've created two large collections [[1]](https://addons-dev.allizom.org/en-US/firefox/collections/10642146/collection-with-restricted-add/) [[2]](https://addons-dev.allizom.org/en-US/firefox/collections/10642146/Large-collection-2/) on -dev and tried o include add-ons with multiple translations as much as possible.

For the caching part, I have the same conclusions as in  https://github.com/mozilla/addons-server/issues/16062#issuecomment-737219872

I've also monitored the response times and these are the numbers that I obtained:

https://addons-dev.allizom.org/api/v4/accounts/account/10642146/collections/collection-with-restricted-add/addons/
- Response times at application start time (in my case the request is made from Postman) - no cache: between 1300 - 1800 ms
- Response times when repeating the same request (sort params not added/changed): between 200 and 700 ms; ~400 ms was the most common
- Response time when changing sort parameters: between 500 - 900 ms

https://addons-dev.allizom.org/api/v4/accounts/account/10642146/collections/Large-collection-2/addons/
- Response times at application start time (in my case the request is made from Postman) - no cache: between 1200 - 1600 ms
- Response times when repeating the same request (sort params not added/changed): between 200 and 700 ms; ~400 ms was the most common
- Response time when changing sort parameters: between 700 - 900 ms

If the data used is still not large enough, please let me know and I will bump the translation sizes some more.

**Comment by diox** [comment]
That looks ok. The first collection is right around the size we want to check, and the numbers do indicate caching is working so that's good. Maybe bump the size slightly (if you download the json it's currently at 507K, having it at 600K would be closer to production and give us slightly more confidence) and retest.

**Comment by AlexandraMoga** [comment]
I've tried to increase the collection size a bit and repeated the API request while also monitoring timings. The response times were still in the range mentioned in the comment above.
