### ISSUE TITLE
Collection add-ons list returns a 500 error when certain add-ons are included in the collection

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16129]
### Describe the problem and steps to reproduce it:

Make the following request:
https://addons-dev.allizom.org/api/v4/accounts/account/10642146/collections/500/addons/

### What happened?
You receive a 500 error

### What did you expect to happen?
Collection add-ons are returned 

### Anything else we should know?
There are some particularities to reproducing this issue, at least from what I've noticed after trying different scenarios:
- I encountered the issue only with some dictionaries; in the first example, the dictionary that causes the 500 is https://addons-dev.allizom.org/api/v4/accounts/account/addons/addon/3627/
- a few other collection examples where the issue can be reproduced:
  - https://addons-dev.allizom.org/api/v4/accounts/account/10640485/collections/collection-create-10/addons/ => caused by add-on 204312, also a dictionary
  -  https://addons-dev.allizom.org/api/v4/accounts/account/10642146/collections/500-error/addons/ => caused by add-on 10391, also a dictionary
- if you add a `lang=` parameter to these requests, the error disappears, so this could be somehow related to translated fields, although, the addon detail API for the problematic add-ons doesn't seem to be affected

**Comment by eviljeff** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/10215023/?query=is%3Aunresolved

**Comment by eviljeff** [comment]
it's related to translated fields, correct.  Specifically, when a version doesn't have a license (so looking up the translated name for that license fails) - I don't know if there's something particular about dictionaries not having licenses but it should be handled.

**Comment by AlexandraMoga** [comment]
I'm no longer receiving 500 errors for the mentioned collections or any other collection that had the problematic add-ons in the list.

I'm marking this issue as verified fixed on -dev.
