### ISSUE TITLE
Add transformer to prefill has_listed_versions / has_unlisted_versions for a queryset

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16132]
In a few places we call `has_listed_versions` / `has_unlisted_versions` for each add-on in a list. This is super inefficient because it will generate 1 or 2 queries (that just do a `.exists()`) for each add-on (for listed we have a shortcut that'll return `True` when there is a `current_version`, but we don't have that possibility for unlisted)

We should have a transformer to do that on a list, supporting the optional `include_deleted` argument as well (which the admin/reviewer tools need). It would prefill some kind of cache the method could then use.

**Comment by diox** [comment]
This is less useful than I'd like - in reviewer tools, this doesn't help the Scanners & MAD queues, because they used a different query, filtering also on the presence of an additional field (`needs_human_review` or `reviewerflags__needs_human_review_by_mad`) and displaying a count. On the review page, we're only dealing with a single add-on so it doesn't matter.

The one place that would benefit though, is the add-on changelist admin. Not as important, but it's used in popup mode to select an add-on so it does matter a bit.

**Comment by diox** [comment]
QA: addon list/detail in admin pages and reviewer tools queues (particularly flagged by scanners/need human review) should still work correctly after this. It's unlikely you'd notice the perf difference on dev/stage.

**Comment by ioanarusiczki** [comment]
@diox
I verified on -dev - FF84(Win10) and it looks good to me.
- the django admin list has an extra column "Authors" but it's probably expected.
- rev tools pages look alright, Flagged for Human Review takes some time to load on both dev and stage (-dev is loading a bit faster but still takes a while).
