### ISSUE TITLE
URL's throw a 500 in Activity logs

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16131]
1. Go to an entry such as https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4003686/change/ and click on URLs

Results:
500 - server error 

Notes:
- reproducible on dev and stage - FF83(Win10).

**Comment by wagnerand** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/8469912/

**Comment by diox** [comment]
This is because in `ActivityLog.to_string()`, we're linkifying items assuming we're on the frontend, without specifying a domain. But we're on the internal domain, where the frontend views don't exist.

So when clicking on the link (which points to https://addons-internal.dev.mozaws.net/en-US/firefox/addon/project-delay-approval-no-3/ in QA's example) you get:
```
ViewDoesNotExist: null
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "olympia/amo/views.py", line 154, in frontend_view
    return _frontend_view(*args, **kwargs)
  File "olympia/amo/views.py", line 148, in _frontend_view
    raise ViewDoesNotExist()
```

Instead of using `get_url_path()` on the various cases `ActivityLog.to_string()` is handling, we need to use `get_absolute_url()`.

**Comment by ioanarusiczki** [comment]
@diox I verified this on dev:
1. the URLs for some activities where I found URLs now redirect to frontend. Examples:
- properties edited https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4005629/change/?_changelist_filters=p%3D2
- an addon added to a collection https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4005734/change/?_changelist_filters=p%3D1
- user banned https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4005678/change/?_changelist_filters=p%3D1
- a review has been updated https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4005677/change/?_changelist_filters=p%3D1

2. "View on site" button on the top right is having the same issue - throws a 500. I could file an issue for that too in case it's needed. Let me know.

**Comment by diox** [comment]
The view on site is a different issue, please file separately.

**Comment by ioanarusiczki** [comment]
@diox Done https://github.com/mozilla/addons-server/issues/17179
