### ISSUE TITLE
consolidate setup config (and tox.ini) into pyproject.toml

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16149]
Since https://www.python.org/dev/peps/pep-0518/ `pyproject.toml` is a standard-ish for specifying python project config.  We still have some tool settings in setup.cfg however.   And some more in tox.ini (tox apparently supports `pyproject.toml` too) It would be better if everything could be specified in one place (I've not investigated if every tool can support `pyproject.toml`, though pytest and tox state they can at least, and that's a big chunk of config).

Bonus if we can get rid of any other random config files!

**Comment by willdurand** [comment]
Looks like flake8 does not support `pyproject.toml` https://gitlab.com/pycqa/flake8/-/issues/428

**Comment by eviljeff** [comment]
> Looks like flake8 does not support `pyproject.toml` https://gitlab.com/pycqa/flake8/-/issues/428

🐼 your regular reminder that 3rd party projects are dictatorships rather than democracies.

I still think it's worth moving as much as possible into pyproject.toml so it's the default source of config.

**Comment by eviljeff** [comment]
isort can use pyproject.toml too

Though it's not clear to me how we actually use isort these days (it's not referenced in the Makefiles or in another config), or if any of the config is actually needed beyond enabling `profile = "black` https://pycqa.github.io/isort/docs/configuration/black_compatibility/

**Comment by willdurand** [comment]
> Though it's not clear to me how we actually use isort these days (it's not referenced in the Makefiles or in another config), or if any of the config is actually needed beyond enabling `profile = "black` [pycqa.github.io/isort/docs/configuration/black_compatibility](https://pycqa.github.io/isort/docs/configuration/black_compatibility/)

I don't think we're actually using it. It was introduced in https://github.com/mozilla/addons-server/commit/57915e248080bafdf5b3a3d3f95b78d64bd0c278, without any tool. Maybe we should remove it then?
