### ISSUE TITLE
Error calling notifications endpoint on dev and stage

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#16147]
Calling the notifications endpoint on dev and stage is generating a 500 response. An example API request is `https://addons.allizom.org/api/v4/accounts/account/6321049/notifications/?lang=en-US&wrap_outgoing_links=true`. The problem does not appear to exist on prod.

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/10192335/?query=is%3Aunresolved

```
BasketException/api/v4/accounts/account/{user_pk}/notifications/
errorUsing lookup_user with `email`, you need to pass a valid `api-key` or FxA OAuth Autorization header.
```

We *are* passing an `api-key`, maybe it somehow not valid ? We seem to using the correct basket domain (basket-dev.allizom.org) for dev.

**Comment by diox** [comment]
@pmac you fixed the original issue December 14th, but now we're getting another error when trying to fetch the newsletter subscription info for an user on dev (just logging in to https://addons-dev.allizom.org/ and going to edit your user profile triggers it):

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/9599485/?query=is%3Aunresolved
```HTTPSConnectionPool(host='basket-dev.allizom.org', port=443): Read timed out. (read timeout=5)```

**Comment by pmac** [comment]
Not sure why that is. I can't reproduce. Maybe a temporary hiccup? I just deployed a fix for another issue I found though, can you try again and see if perhaps that has things working better?

**Comment by diox** [comment]
It's working for me now, yeah.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev and AMO stage the notifications API and I get a 200 status. 
It's working for me too.
