### ISSUE TITLE
Drop collection add-ons API endpoint caching if collection author isn't mozilla

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16151]
The caching we added in https://github.com/mozilla/addons-server/pull/16064 for the collection add-ons API endpoint is now working, but it's a little dumb, as there is no invalidation mechanism. We only really need it for the official Fenix collections, so let's try droping it if the author isn't the mozilla user.

**Comment by willdurand** [comment]
Should we consider a lower ttl instead of no cache at all?

**Comment by diox** [comment]
I don't think it's going to be worth it. Soon Fenix will be using services.a.m.o. for all requests and that has a 3 minutes nginx cache by default already (before it even hits the app).

**Comment by pcgeek86** [comment]
+1 When I add an extension to a collection, it doesn't appear in Fenix right away. To work around this, I changed the collection user ID, quit Firefox Nightly, and changed the user ID back to mine, and quit again. After launching Firefox Nightly again, it re-cached the extension collection from AMO.

I would recommend leaving the caching in place, to reduce bandwidth and battery usage. 

An alternative implementation would be to provide a force-refresh UI mechanism (ie. pull down to force refresh, as is de facto standard in Android).

**Comment by diox** [comment]
> To work around this, I changed the collection user ID, quit Firefox Nightly, and changed the user ID back to mine, and quit again. After launching Firefox Nightly again, it re-cached the extension collection from AMO.
> I would recommend leaving the caching in place, to reduce bandwidth and battery usage.

To be clear, we're talking about a server side cache here. Your workaround does nothing to this (it's pure luck that it worked for you - might be the data was evicted from the cache, or you accidentally waited long enough for it to expire), and this wouldn't have an impact on reducing bandwidth and battery usage either.

**Comment by diox** [comment]
This is fixed on our `master` branch, it will land in production on January 7th.

**Comment by ioanarusiczki** [comment]
@diox I verified this issue on AMO dev - FF84(Win10):
- unauthenticated users will be able to see the changes to a collection's add-ons list (additions or removals) after ~1h when the collection is made by Mozilla.  For other collections, these changes are immediately visible.
