### ISSUE TITLE
Deletion of a review does not affect overall rating and review count

### ISSUE THREAD

**Issue by sblask** [mozilla/addons-server#1618]
I reported a review of my addon (https://addons.mozilla.org/en-US/firefox/addon/bookmark-dial/) and it got deleted. Now there is still a link "1 user review" and the rating that is only based on the deleted review. I think there should be neither?

**Comment by sblask** [comment]
I got a new review yesterday and now I got:

Not yet rated
0 user reviews

Seems like it's one review behind?

**Comment by atsay** [comment]
This bug is impacting users who have been rated by spam accounts. We can delete the spam comment, but the bad rating remains.

**Comment by wagnerand** [comment]
This seems like a celery issue. I removed the celery delay for `addon_review_aggregates` on my local testing instance and review stats were updated immediately when deleting both flagged and unflagged add-ons.

**Comment by diox** [comment]
If that's the case then my guess is that the celery task is called too soon before the transaction has been committed. I have a patch for this, I just haven't been able to push it yet because of general instability with celery in the recent past. I just need to find the time to test it more.

**Comment by erosman** [comment]
So ..... what is happening with the bug?
Has it been fixed?
Is it going to be fixed?
Would it update previous rate count once it is fixed?

**Comment by diox** [comment]
It has not been fixed yet. I can't give you a timeframe, it depends on a quite complex issue.

Review average will automatically be fixed - in fact it does adjust itself automatically after some time (and more reviews).

**Comment by vcarciu** [comment]
This is affecting sorting by rating also. Basically , if we have an addon in my submissions with a deleted review , it will be still seen as reviewed and sorted accordingly. 
@diox  : should I open a separate issue on this?

**Comment by diox** [comment]
This is probably the same issue.

**Comment by diox** [comment]
Should be fixed (or at least much, much improved) in 0fc37b2d5453188049e970469343860befaf2068 that was pushed to production a couple weeks ago.

Add-ons that were affected by this will be automatically fixed once a new review is posted (or deleted).

**Comment by davidhedlund** [comment]
https://addons.mozilla.org/en-US/firefox/addon/sky-timer/ is rated but there's no Review. Can you please re-open this issue @diox?

**Comment by davidhedlund** [comment]
@sblask Thank you for starting this issue.

**Comment by diox** [comment]
No need to re-open:
> Add-ons that were affected by this will be automatically fixed once a new review is posted (or deleted).

We'll recalculate the reviews count for all add-ons next week anyway, we need that for another issue.

**Comment by davidhedlund** [comment]
@diox Do you mean that ratings without reviews are deleted weekly?

**Comment by diox** [comment]
No.
