### ISSUE TITLE
Incorrect language URLs returned in API response from services.addons.mozilla.org

### ISSUE THREAD

**Issue by csadilek** [mozilla/addons-server#16214]
### Describe the problem and steps to reproduce it:
Fenix recently switched from `addons.mozilla.org` to `services.addons.mozilla.org` for fetching its add-on collection to help address scalability concerns. Since switching to `services.addons.mozilla.org` the links (`url`, `review_url`, etc.) returned in the response point to incorrect (seemingly random) languages.

Request:
https://services.addons.mozilla.org/api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity

Headers:
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-CA,de-DE;q=0.7,fr-CA;q=0.3
Connection: keep-alive
Host: services.addons.mozilla.org
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Android 11; Mobile; rv:86.0) Gecko/86.0 Firefox/86.0
```

### What happened?

Add-on links in response were Spanish:
```
...
url: https://addons.mozilla.org/es/android/addon/ublock-origin/
edit_url: https://addons.mozilla.org/es/developers/addon/ublock-origin/edit
...
```

### What did you expect to happen?

Add-on links in response are based on `Accept-Language` header:
```
...
url: https://addons.mozilla.org/en-CA/android/addon/ublock-origin/
edit_url: https://addons.mozilla.org/en-CA/developers/addon/ublock-origin/edit
...
```

### Anything else we should know?
This worked fine using `addons.mozilla.org` directly, but regressed after switching to `services.addons.mozilla.org`. The change to `services.addons.mozilla.org` is currently in Nightly and Beta, but not Release (which is therefore not yet affected).

Fenix is not (and has never) specified the `lang` parameter so it's fetching all translations. This is on our TODO list to fix https://github.com/mozilla-mobile/android-components/issues/8148.

The upstream Fenix ticket for this problem is: https://github.com/mozilla-mobile/fenix/issues/17156

**Comment by jvillalobos** [comment]
I don't know if this helps, but FWIW you can remove the language segment of the URL (e.g. `https://addons.mozilla.org/android/addon/ublock-origin/`) and AMO will do the right thing. Just in case you want to mitigate the issue before the year is over.

**Comment by diox** [comment]
Weirdly, we don't `Vary` on `Accept-Language` in the API. That's likely the issue - our own cache does depend on the language passed (including `Accept-Language`) but because we don't include `Accept-Language` in the `Vary` header, the nginx level cache ops have set up on `services.a.m.o.` doesn't depend on it, and returns cached results that may be in a different language.

The quick fix would be to add `Accept-Language` to `Vary` headers in `APIRequestMiddleware.process_response()` - it might be overkill, but I don't think it's too bad.

**Comment by diox** [comment]
STRs on dev:
1. Make a request to a mozilla collection (technically any would do, but might as well be specific) through the API on services.a.m.o. dev domain:
`curl -s https://services.addons-dev.allizom.org/api/v4/accounts/account/4757633/collections/privacy/addons/ | jq '.results[] | .addon.url'`
2. Immediately after, make a second request with an `Accept-Language`:
`curl -s -H 'Accept-Language: fr' https://services.addons-dev.allizom.org/api/v4/accounts/account/4757633/collections/privacy/addons/ | jq '.results[] | .addon.url'`
3. Then, go back to the first 
`curl -s https://services.addons-dev.allizom.org/api/v4/accounts/account/4757633/collections/privacy/addons/ | jq '.results[] | .addon.url'`

Expected results:
- At step 1, the URLs should contain `/en-US/`
- At step 2, the URLs should contain `/fr/` (*not* `/en-US/`)
- At step 3, the URLs should contain `/en-US/`

Actual results:
- The URLs contain `/en-US/` at all steps, at least until the cache expires (3 minutes)

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev with various collections and transitions between requests that contained or did not contain an `Accept-Language` header. In all cases, where a specific language is specified, the `.addon.url` returned matches the `Accept-Language` header, while a request that doesn't include a specific language defaults to `en-US`.

Also, if the specified language is invalid or not in the list of accepted AMO localizations, the `.addon.url` will default to `en-US` as well.
