### ISSUE TITLE
New listed version submissions do not trigger an add-on sync with Salesforce 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16224]
**Prerequisites:**
AMO developer account exists in Salesforce

### Describe the problem and steps to reproduce it:
1. Log into AMO -dev with a synced developer account (see Prerequisites)
2. Upload a new listed add-on 
3. Approve the add-on with a reviewer account
4. Make sure the new add-on is listed under the developer's account info in Salesforce - make a note of the 'AMO Current Version' in the add-on details
5. Upload a new listed version for this add-on on AMO
6. Once the version is auto-approved, verify if the new version string is reflected in Salesforce 'AMO Current Version' field

### What happened?
Salesforce is still showing the previous version number

### What did you expect to happen?
Salesforce should be displaying the current listed version number

### Anything else we should know?
- the issue does not apply to unlisted add-ons/unlisted versions
- the new listed version number is updated only when certain add-on fields (name, summary etc) are manually updated on AMO

Example: https://addons-dev.allizom.org/en-US/firefox/addon/test-for-listed-sf/

1. Add-on details on AMO:
![image](https://user-images.githubusercontent.com/31961530/103010112-6e8eae00-4540-11eb-8724-d732b1fa53e1.png)

2. Add-on details in Salesforce:
![image](https://user-images.githubusercontent.com/31961530/103010150-7e0df700-4540-11eb-93c8-042aaa982263.png)

**Comment by AlexandraMoga** [comment]
@diox I've reverified the issue on -dev but it doesn't look fixed.
Example:
https://addons-dev.allizom.org/en-US/developers/addon/second-test-fix-version-sync/versions

Current version on AMO:
![image](https://user-images.githubusercontent.com/31961530/103655193-9255e900-4f6f-11eb-92a0-dc9573f6a316.png)

Current version in Salesforce:
![image](https://user-images.githubusercontent.com/31961530/103655244-a1d53200-4f6f-11eb-8cf2-97aacc4b5f93.png)

There is one thing that I did not observe in my previous tests, so I'm not sure if this was the case even before the current patch: with the [new add-on example](https://addons-dev.allizom.org/en-US/developers/addon/second-test-fix-version-sync/versions), I've submitted several subsequent versions. As in my initial tests, the second listed version was not synced, but with each new version, a sync seems to be triggered, but Salesforce is still one version behind AMO (as seen in the comparison screenshots).

**Comment by diox** [comment]
@AlexandraMoga could you try again, but disabling auto-approval for that add-on, and manually performing the approval in reviewer tools for the new listed version ?

**Comment by AlexandraMoga** [comment]
@diox the sync seems to happen in case of a manual approval. I've verified with the previous example - https://addons-dev.allizom.org/en-US/developers/addon/second-test-fix-version-sync/versions and with a new submission - https://addons-dev.allizom.org/en-US/developers/addon/manual-approval-sync/versions

**Comment by diox** [comment]
Ok thanks, I think I've got a good idea about where it's coming from.

**Comment by diox** [comment]
QA: please test with both manual and auto-approvals scenarios.

**Comment by AlexandraMoga** [comment]
The issue looks fixed now. I've verified both with manual and auto-approval scenarios for listed and unlisted versions. 

Example with auto-approval: https://addons-dev.allizom.org/en-US/developers/addon/fix-2-version-sync/versions
[AMO]
![image](https://user-images.githubusercontent.com/31961530/104034085-17900680-51d9-11eb-9c69-c1d1104275c0.png)

[Salesforce]
![image](https://user-images.githubusercontent.com/31961530/104034100-1e1e7e00-51d9-11eb-8fd3-937047b88df9.png)
