### ISSUE TITLE
Fix less v4 breakage

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16250]
identified in https://github.com/mozilla/addons-server/pull/16205#issuecomment-753931483 by @diox

less v4 makes a number of [changes](https://github.com/less/less.js/pull/3573), one of which is less/less.js@67ce103 "Require parens after mixin call" - this is causing the less compilation step to fail.  We don't fail during the assets build for this so it doesn't trigger a fail in CI; it's unclear what the actual result of this is on AMO either because there's *a lot* of cruft from the legacy frontend so it may be an unused file anyway.  

It will be safer to fix the syntax failure in the less file for now.

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa. 
Thanks!
