### ISSUE TITLE
Can't add a new add-on to the featured collection

### ISSUE THREAD

**Issue by magopian** [mozilla/addons-server#1626]
When trying to add a new add-on to the featured collection (using [this link](https://addons.mozilla.org/en-US/firefox/collections/mozilla/featured-add-ons/edit/#addons-edit)), there's a js error in the console, which prevents doing it:
```
TypeError: this._renderItem(...) is undefined
._renderItemData() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
._renderMenu/<() common-min.js:3
.each() preload-min.js:1
._renderMenu() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
._suggest() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
.__response() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
e.widget/</l[t]</r() common-min.js:2
.__response() common-min.js:3
e.widget/</l[t]</<() common-min.js:2
._response/<() common-min.js:3
.proxy/i() preload-min.js:1
n() common-min.js:1
p.Callbacks/u() preload-min.js:1
p.Callbacks/l.fireWith() preload-min.js:1
k() preload-min.js:3
.send/n() preload-min.js:3
```

Maybe an issue with the js bundle that doesn't include static/js/impala/formset.js?

**Comment by ValentinaPC** [comment]
I've tried to add an add-on to a featured collection in AMO-dev FF45(Win 7) and there was no js error in the console.
There is a **js warning**: _"Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead."_ when clicking the "Edit Collection" link or the "Save changes" button (after adding an add-on to the collection)

Is this something notable, @magopian  ?
