### ISSUE TITLE
Show "Block add-on" for deleted add-ons in reviewer tools

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16264]
### Describe the problem and steps to reproduce it:

Non-deleted add-ons have a "Block add-on" button in the admin section at the bottom of the review page.

### What happened?

Deleted add-ons are missing that button.

### What did you expect to happen?

Deleted add-on should show that button as well.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand 
I've tested the scenario for:
Deleted listed https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620381
Deleted unlisted https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/620382

"Block add-on" and "Update add-on block" are present on the review pages for deleted addons. 
Verified on AMO dev - FF84(Win10).
