### ISSUE TITLE
Add scanner score to auto-approval queue table and order by it

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16263]
To help with prioritization efforts, let's add the security scanner score to the auto-approval review queue and also order by it (descending).

We should keep the current weight column as well. Optional: If it's easy to do, could we provide a way to load that queue ordered by weight, e.g. by passing a GET parameter? If not, no big deal, we can skip that.

**Comment by ioanarusiczki** [comment]
@diox I verified on AMO dev and AMO stage - a new column was added into the auto approved queue and the default is ordered by the scanner score.
