### ISSUE TITLE
upgrade python version to 3.9

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16269]
It's been released for a few months so we may as well look to upgrading from 3.8.

**Comment by eviljeff** [comment]
a quick and dirty attempt to just change 3.8 -> 3.9 in the Dockerfiles and circleci config led to:
"ERROR: Failed building wheel for pygit2" so we may need to install [libgit2](https://github.com/libgit2/pygit2/issues/1038#issuecomment-719999510)

**Comment by eviljeff** [comment]
Changes were minimal to fix our codebase but celery4.x only supports python3.8.x so this is blocked on upgrading celery to 5.0.2+ 

https://github.com/mozilla/addons-server/issues/15677 was when we decided to stay on Celery4 because it was a LTS release (python support is likely counted as a "feature" update rather than bug/security fix so I don't think we can count on them backporting python3.9 support to the 4.x branch.)

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/tree/16269-python39 for progress.

**Comment by eviljeff** [comment]
Going to pause work on this until we make a decision on Celery upgrades (at least)

**Comment by diox** [comment]
While tests pass, `pygit2`, which we've [pinned to < 1.2.0](https://github.com/mozilla/addons-server/blob/68d8a820a1924e1c4a95f6351010d2c21fed5a61/.github/dependabot.yml#L24-L26), have this in their docs:

<p>The table below summarizes the latest pygit2 versions with the supported versions
of Python and the required libgit2 version.</p>
<div class="wy-table-responsive">

pygit2 | Python | libgit2
-- | -- | --
1.4 - 1.6 | 3.6 - 3.9 | 1.1.x
1.2 - 1.3 | 3.6 - 3.8 | 1.0.x
**1.1** | **3.5 - 3.8** | **0.99.x, 1.0.x**
1.0 | 3.5 - 3.8 | 0.28.x
0.28.2 | 2.7, 3.4 - 3.7 | 0.28.x

</div>

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/tree/16269-python39 (and the more recent attempt https://github.com/eviljeff/olympia/commit/98b81cee6c891846591ee2b1871a93520e82a018) upgrades pygit2 to 1.4 at the same time.  iirc, tests failed otherwise.

**Comment by AlexandraMoga** [comment]
@eviljeff should we do a general regression on the site for this issue?

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff should we do a general regression on the site for this issue?

yes.  The only significant thing I had to change (upgrade) was a dependency used during git extraction - the task that runs to extract the xpi contents to be exposed in addons-code-manager - but a python upgrade could potentially affect any part of the codebase.

**Comment by AlexandraMoga** [comment]
We've done a general regression on -dev and stage and no issues were found.
With regards to git-extraction specifically, I've made sure that the add-on code was present in code-manager after submission. I've also verified that the git-(re)extraction functionality from admin addon pages is still working.
