### ISSUE TITLE
Update source code policy link in Step 2 of add-on submission

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1627]
STR:
1) Go to https://addons.mozilla.org/en-US/developers/addon/submit
2) Accept developer agreement and upload an XPI

This shows a paragraph of text saying:

> If your add-on contains binary or obfuscated code other than known libraries, upload its sources for review.
> Read more about the source code review policy.

The second line is a link to https://addons.mozilla.org/en-US/developers/docs/policies/reviews#section-binary. 

This should be updated to point to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews#Source_Code_Submission

Note the en-US part of the URL should be hardcoded, since those docs are rarely translated and MDN doesn't handle missing translations very well.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/LaW5CD0Fz
