### ISSUE TITLE
Link to blocklist admin from reviewer page for blocked add-ons

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#16280]
When on a review page for an add-on that is blocked, I'd like to be able to switch over to the blocklist admin to edit/view the block.

In the simplest case it would be great to expose the id of the respective block somewhere in the DOM so that I can add links with my extension. While we are at it, we might as well just provide a link to the blocklist admin directly for users that have sufficient permissions.

**Comment by wagnerand** [comment]
There should already be an "Update block" at the end of the page in the block that holds all the admin buttons.

**Comment by kewisch** [comment]
Thanks, don't know how I missed it!
