### ISSUE TITLE
Do not override add-on status when blocking a deleted add-on.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16283]
### Describe the problem and steps to reproduce it:

When an add-on gets blocked with range 0-*, we set it's status to `DISABLED_BY_MOZILLA` to prevent further submissions.
However, when an already deleted add-on gets blocked, we shouldn't change the status but instead deny resubmission (add the GUID to `DeniedGuid`)

STR:
1. Delete an add-on.
2. Block it.

### What happened?

Add-on status is `DISABLED_BY_MOZILLA`

### What did you expect to happen?

Add-on status is `DELETED`, and add-on GUID has been added to `DeniedGuid`.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand 
I verified this issue on AMO -dev with FF84(Win10): 
- when the addon is deleted and it's been blocked with range 0-* the GUID is added to [Denied guids](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/deniedguid/?p=0). 
- The status of the add-ons is "[Deleted](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/620383/change/)".

These are the testing samples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620381
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620383
