### ISSUE TITLE
tidy up MDN search field in devhub base templates that's no longer used

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16294]
When the base templates were [cleaned up](https://github.com/mozilla/addons-server/pull/10926/files#diff-520fc674741702badfb6599cea9cce0f5a93e5bec543bf24caeb834d99989aa3L100 (edited) ) as part of the legacy frontend removal the search field was (knowingly) dropped from the devhub pages too.  But the code in the devhub base templates wasn't.  That should be removed.

**Comment by ankushduacodes** [comment]
Hi @eviljeff!... I would love to work on this. What know of clean up are we talking about here? same as base template?

Thank you :)

**Comment by eviljeff** [comment]
@ankushduacodes it's just a matter of deleting the `{% block search_form %}` blocks from the templates, plus the search.html template referenced inside those blocks.  There _might_ be some test fails that need fixing but I doubt it (the code hasn't been rendered in a few years and nothing failed)

**Comment by eviljeff** [comment]
Also, you can delete the `CSP_FORM_ACTION` tuple from `lib/settings_base.py`

**Comment by ankushduacodes** [comment]
@eviljeff Should I also delete tests concerning `CSP_FORM_ACTION`?
