### ISSUE TITLE
Freeze v4 API (& make it clear that v5 is the current version)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16300]
This is mainly a documentation issue.  We just need to make it clear in the API docs that v4 is frozen, and so safe for use, and v5 will be where future development will be.

v3 deprecation is connected but with a few more moving parts so we'll track in a different issue.

**Comment by ioanarusiczki** [comment]
@eviljeff Changes are available in the [docs](https://addons-server.readthedocs.io/en/latest/topics/api/overview.html#api-versions)
