### ISSUE TITLE
Add "kill-switch" for BigQuery

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16301]
We don't have a waffle switch to temporarily disable BigQuery but we probably should in case GCP goes crazy again.

For QA: there should be a new `disable-bigquery` switch. When this switch is turned **on**, the stats pages should be empty (no data available) and there should be a banner.

**Comment by ioanarusiczki** [comment]
@willdurand 
- I made `disable-bigquery` active -> the data is no longer available - only numbers  from the blue URLs in the overview pages are available (in case that's unexpected, let me know). 

![numbers are available](https://user-images.githubusercontent.com/33448286/105045744-efbe5f80-5a70-11eb-8a49-a4bb319c3039.png)

- After I disabled the switch, the banner is no longer present but I could not get the data back. 
Do you see anything for :

https://addons-dev.allizom.org/en-US/firefox/addon/amo-info-with-extra-dirs/statistics/
https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/statistics/
https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/statistics/
https://addons-dev.allizom.org/en-US/firefox/addon/private-relay/statistics/

I opened the pages in a new profile but I still don't see data displayed.

**Comment by willdurand** [comment]
> I opened the pages in a new profile but I still don't see data displayed.

Possibly a different issue: current -dev JavaScript is broken

**Comment by ioanarusiczki** [comment]
@willdurand Ok, then I'll re-check this later.

**Comment by ioanarusiczki** [comment]
@willdurand Looks like it's broken on both -dev and -stage, I get 503 Service Unavailable errors, when the switch is enabled. 

![js errors on both servers](https://user-images.githubusercontent.com/33448286/105179872-899a1100-5b32-11eb-9a1c-7bada3632353.gif)

I don't get errors when the switch is disabled.

**Comment by willdurand** [comment]
@ioanarusiczki By "broken", do you mean the loading indicators aren't hidden? I noticed this too, which is odd because that's not what I saw locally. It's not a huge problem but you can certainly create a new p4 issue for that.

**Comment by ioanarusiczki** [comment]
@willdurand  
Sometimes they even show data so I filed https://github.com/mozilla/addons-server/issues/16366
