### ISSUE TITLE
Remove yara-read-binary waffle switch

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16308]
`yara-read-binary` waffle switch should always be on, we should remove that waffle switch and the code that tries to decode file content if the switch is not active.

**Comment by diox** [comment]
It's relatively straightforward:
- remove the condition on `yara-read-binary` switch and code inside the condition in `src/olympia/scanners/tasks.py`
- adjust tests in `src/olympia/scanners/tests/test_tasks.py` accordingly
- add a migration to remove the waffle switch (create an empty migration using `makemigrations --empty`, change the migration to delete the switch like `src/olympia/scanners/migrations/0033_delete_waffle_switch.py` does.

**Comment by eviljeff** [comment]
mentor @diox :)

**Comment by Rishabh-Kumar-07** [comment]
Hi. I would like to work on it. Will follow-up with a PR soon.

**Comment by osamamagdy** [comment]
@diox Hi, is this still availabe for me to work on?

**Comment by diox** [comment]
We haven't heard back from @Rishabh-Kumar-07 in more than 10 days, so yes, it is.

**Comment by osamamagdy** [comment]
@diox  I will be delighted to start working on it now so can you assign it to me?

**Comment by eviljeff** [comment]
> can you assign it to me?

We will assign the issue once your pr is ready.

**Comment by osamamagdy** [comment]
> 
> 
> It's relatively straightforward:
> 
>     * remove the condition on `yara-read-binary` switch and code inside the condition in `src/olympia/scanners/tasks.py`
> 
>     * adjust tests in `src/olympia/scanners/tests/test_tasks.py` accordingly
> 
>     * add a migration to remove the waffle switch (create an empty migration using `makemigrations --empty`, change the migration to delete the switch like `src/olympia/scanners/migrations/0033_delete_waffle_switch.py` does.

I started to do the steps mentioned above and removed the code in >def _run_yara_for_path(scanner_result, path, definition=None) function
but for the second step i came over two methods >test_run_in_binary_mode and >test_run_in_non_binary_mode_with_binary 
both of them uses @override_switch and i think that i should remove the whole second method in non binary mode and also the override for the first one 
Is my assumption correct?

**Comment by diox** [comment]
Yes, exactly.

**Comment by osamamagdy** [comment]
I created a pull request for this changes could you review it? 
https://github.com/mozilla/addons-server/pull/16424

**Comment by diox** [comment]
QA: retest https://github.com/mozilla/addons-server/issues/15574

**Comment by AlexandraMoga** [comment]
@diox I think #15574 was tested based on [this rule](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerrule/40/change/), which was supposed to match when the `yara-read-binary` switch was on and not match when the switch was off.

If `yara-read-binary` is always on now, the mentioned rule should always be matching (if the add-on meets the conditions) - which is what is happening now.

Other active rule are still working as before.
