### ISSUE TITLE
return hero shelves data under /shelves/

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16309]
We have a new /shelves/ api endpoint but to get the primary and secondary hero shelves you have to make a separate call to /hero/.  Given the end objective to have a single API request to populate the homepage with content it makes sense to return everything at once in a single call.

**Comment by ioanarusiczki** [comment]
@eviljeff The API docs have been updated, after making several requests: 
- primary and secondary objects have been added and the API returns the enabled shelves and a single randomly selected primary/secondary hero shelf. When all=true parameter is used in the request the primary and secondary shelves return enabled/disabled results.

A questions:
- should `count` also take into account the two added objects? To give an example: if I enabled [two](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/) homepage shelves "count" is 2, it ignores the primary and secondary which were now added.

**Comment by eviljeff** [comment]
> * should `count` also take into account the two added objects? To give an example: if I enabled [two](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/) homepage shelves "count" is 2, it ignores the primary and secondary which were now added.

count is the count for the shelf results, so, imo, no.  @bobsilverberg might prefer otherwise?

fwiw, I was actually thinking about changing the structure of the response to drop the pagination stuff, and just have the `results` because we'll always want all the shelves (and if we end up with more then 25 shelves the homepage is going to be a little full!).  This would be work in a follow-up issue.

**Comment by bobsilverberg** [comment]
> > * should `count` also take into account the two added objects? To give an example: if I enabled [two](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/) homepage shelves "count" is 2, it ignores the primary and secondary which were now added.
> 
> count is the count for the shelf results, so, imo, no. @bobsilverberg might prefer otherwise?
> 
> fwiw, I was actually thinking about changing the structure of the response to drop the pagination stuff, and just have the `results` because we'll always want all the shelves (and if we end up with more then 25 shelves the homepage is going to be a little full!). This would be work in a follow-up issue.

I agree that we don't really need pagination for this, which means that count is pretty much irrelevant anyway.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @eviljeff I filed https://github.com/mozilla/addons-server/issues/16342

This is verified on dev.
