### ISSUE TITLE
Add `themes` property to homepage shelf data

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#16312]
When the homepage starts consuming the [API for homepage shelves](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#homepage-shelves), it will need to know whether the shelf is for themes or extensions. This is required because theme shelves are handled differently (e.g., we show 3 themes, but for extensions we show 4 extensions).

This means that we need a property added to the model to indicate if the shelf is for themes, we need the admin updated to allow this property to be specified, and we need the API updated to expose this property.

We did discuss a possible hack which would use the `criteria` returned from the API and inspect it to guess whether it is returning themes or not, but this feels like a hack and probably not the best way to go to solve this.

@eviljeff @diox What do you think about the hack idea, and do you agree it's not a good solution?

**Comment by bobsilverberg** [comment]
@xlisachan If you can comment on this issue I can assign it to you. Also, @eviljeff has offered to take this issue if you'd rather continue to focus on the frontend, so please let us know if you'd like him to take it.

**Comment by xlisachan** [comment]
Thanks for the update, @bobsilverberg! I'd like to continue focusing on what we discussed yesterday on the frontend - please take this issue, @eviljeff. Thank you!

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev by creating several new shelves in [/shelfmodule/](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/add/) admin for each of the available endpoints: `search`, `search-themes` and `collections`. The shelf creation form will trigger a validation error if the Endpoint is combined with an invalid criteria parameter, i.e. using `search` as Endpoint with a `type=statictheme` in Criteria and the other way around. 

Then, I've checked the results returned by the shelves API: https://addons-dev.allizom.org/api/v5/shelves/
The `endpoint` property marks weather the add-ons returned are extensions, themes or part of a collection:

```
"title": "Extensions Shelf - Users",
"url": "https://addons-dev.allizom.org/api/v5/addons/search/?sort=users&type=extension",
"endpoint": "search",
"criteria": "?sort=users&type=extension",

"title": "Themes Shelf - Recent",
"url": "https://addons-dev.allizom.org/api/v5/addons/search/?sort=updated&type=statictheme",
"endpoint": "search-themes",
"criteria": "?sort=updated&type=statictheme",

"title": "Collection Shelf - Large",
"url": "https://addons-dev.allizom.org/api/v5/accounts/account/4757633/collections/Large-collection-2/addons/",
"endpoint": "collections",
"criteria": "Large-collection-2",
```

@eviljeff I have a question regarding the number of add-ons returned by each shelf: extensions (`search`) and themes (`search-themes`) are both returning a fixed number of 10 add-ons (if the search criteria contains >=10 results). I didn't see any explanation in the API docs that mentions how this fixed number has been decided.
Collection shelves, on the other hand, will return all the add-ons included in the collection.

**Comment by eviljeff** [comment]
> @eviljeff I have a question regarding the number of add-ons returned by each shelf: extensions (`search`) and themes (`search-themes`) are both returning a fixed number of 10 add-ons (if the search criteria contains >=10 results). I didn't see any explanation in the API docs that mentions how this fixed number has been decided.
> Collection shelves, on the other hand, will return all the add-ons included in the collection.

Interesting.  Do you remember if we put a limit in @xlisachan ?  tbh 10 is might be a little too high anyway for the homepage shelves given how they're rendered on the frontend - 4 or 8 might be enough?

**Comment by xlisachan** [comment]
@eviljeff, a limit was not placed on either endpoint within the serializer, but there's a limit set within the CollectionViewSet itself - I don't see one in AddonSearchView though. I'll work on updating the serializer (tests and API doc) to return up to 8(?) add-ons.

**Comment by eviljeff** [comment]
>  I'll work on updating the serializer (tests and API doc) to return up to 8(?) add-ons.

I wouldn't jump into makes changes just yet - it's not clear the best way for the count to be specified per shelf (and what the default/maximum would be).

**Comment by AlexandraMoga** [comment]
I've filed #16367 as a follow-up to continue this discussion.
