### ISSUE TITLE
have shelves api addons data be always the an addon serialized response

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16310]
Under then shelves API we return /addons/, which are the addons that should appear on the shelf.  For collections though, we currently return `CollectionAddon`s instead, which wrap the addon data with a note for the collection.  To allow an api consumer to ignore the type of shelf it would be better to always return the addon directly.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified on dev an API response https://addons-dev.allizom.org/api/v5/shelves/ that returned a collection. 
"addons" returns  an array of add-ons

 "results": [
        {
            "title": "Collection",
            "url": "https://addons-dev.allizom.org/api/v5/accounts/account/4757633/collections/featured-personas/addons/",
            "endpoint": "collections",
            "criteria": "featured-personas",
            "footer_text": "",
            "footer_pathname": "",
            "addons": [
                {
                    "id": 497916,
...
