### ISSUE TITLE
'Report a bug' link from AMO footer leads to a 404 page in dev hub

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16320]
As a followup for https://github.com/mozilla/addons-frontend/issues/9923
It looks like this is also broken on https://addons.allizom.org/en-US/developers/ 

![404 on Report a bug](https://user-images.githubusercontent.com/33448286/104599908-2e958500-562d-11eb-99fb-4d87610034df.png)

This is reproducible on AMO stage - FF84(win10).

**Comment by eviljeff** [comment]
could be a duplicate to #16265 as that's about replacing all the MDN links in addons-server.  (Or dealt with separately if we decide it's a higher priority)

**Comment by NegiAkash890** [comment]
I can help fixing this issue . But need to know where the user should be directed to on clicking the `Report a Bug` Link .

**Comment by eviljeff** [comment]
> 
> 
> I can help fixing this issue . But need to know where the user should be directed to on clicking the `Report a Bug` Link .

it's explained in the linked issue https://github.com/mozilla/addons-frontend/issues/9923#issuecomment-745633486

**Comment by NegiAkash890** [comment]
Thanks @eviljeff for responding . Can you please direct me to the file in the repository  where i need to fix . Thanks

**Comment by eviljeff** [comment]
this hasn't been triaged as a good first bug so we aren't offering step by step guidance.  It should be easy to find by searching the codebase.

**Comment by ioanarusiczki** [comment]
@eviljeff Verified on AMO dev - FF85(Win10)

![link on dev hub](https://user-images.githubusercontent.com/33448286/107050984-8fe7e880-67d4-11eb-8ad5-712e409b0319.gif)
