### ISSUE TITLE
Handle when `version` in manifest is not a string more gracefully

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16338]
STR:
- Upload an add-on with `version` in manifest as an integer instead of a string (like: `"version": 3` instead of `"version": "3"` - anything other than a string will cause the same problem, but using an integer is a common error)

Expected results:
- A proper validation error is shown, explaining that `version` should be a string.

Actual results:
- A generic "There was a problem contacting the server." error is shown

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/10290844/?query=is%3Aunresolved
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/9453682/?query=is%3Aunresolved

**Comment by eviljeff** [comment]
is this a linter issue?  What does the spec say?  (and Chrome/Edge, etc)

**Comment by willdurand** [comment]
> is this a linter issue? What does the spec say? (and Chrome/Edge, etc)

+1

**Comment by diox** [comment]
The linter does the right thing, giving you a message about `version` not being a string. The problem is, we raised an exception before even reaching the linter. My fix avoids that exception, and the linter error is raised normally.

**Comment by AlexandraMoga** [comment]
If the `version` property in the manifest is not a string, the following validation error is raised:

![image](https://user-images.githubusercontent.com/31961530/105200174-392dae00-5b48-11eb-998b-481dfc0fc24f.png)

This issue is verified fixed on stage.
