### ISSUE TITLE
Drop pagination, count for the shelf API

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16342]
Making the https://addons-dev.allizom.org/api/v4/shelves/ API request, it returns page_size, page_cont (with next/previous) - which became irrelevant and it should be dropped. 

 "page_size": 25,
    "page_count": 1,
    "count": 2,
    "next": null,
    "previous": null,

expected:
only return the results.

**Comment by eviljeff** [comment]
QA: this also drops the api/shelves/ endpoint from v3/v4

**Comment by ioanarusiczki** [comment]
@eviljeff 

- I don't see a "page_size" or "page_count" returned by https://addons-dev.allizom.org/api/v5/shelves/ 

- https://addons-dev.allizom.org/api/v3/shelves/  and https://addons-dev.allizom.org/api/v4/shelves/ respond with a 404, which now it's expected.
