### ISSUE TITLE
Issue signing multiple .xpi

### ISSUE THREAD

**Issue by molclicklearn** [mozilla/addons-server#1635]
I have tried to sign an extension using the following command:

jpm sign --api-key xxx --api-secret yyy --xpi myExtension1.xpi

This worked, and I went ahead to sign my next extension using the same key and secret:

jpm sign --api-key xxx --api-secret yyy --xpi myExtension2.xpi

This failed with the following error: JPM [error] Server response: Version already exists. ( status: 409 )

I then went to the Developers Hub and deleted my first extension, to see if that would solve the issue.
That didn't help.
I then revoked and regenerated my credentials and tried to sign the first extension again.
I am now unable to sign anything ;(

Can someone please help?

/Michael

**Comment by andymckay** [comment]
Please send an email to amo-admins AT mozilla DOT org and tell them the ids of the add-ons that you've tried to sign.
