### ISSUE TITLE
Add logging statement at login time back

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16369]
In e10f985cb2344e0e61140ee32a704c1e0304d7ac we removed the `Got profile {...}` log statement, but it turns out it's actually useful for the foxsec-pipeline, so let's add it back.

**Comment by AlexandraMoga** [comment]
@diox is there anything to be verified for this issue?

**Comment by diox** [comment]
No thanks, it'll be easier for us to just monitor the impact with security folks
