### ISSUE TITLE
Set an appropriate number of add-ons to be returned by the shelves API

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16367]
Follow up for #16312

### Describe the problem and steps to reproduce it:
The shelves API - https://addons-dev.allizom.org/api/v5/shelves/ - is currently returning a fixed number of 10 addons for extensions (`search`) and themes (`search-themes`) shelves. This number is too high for the current homepage requirements, so a more appropriate number should be decided.

### Anything else we should know?
Collection shelves, on the other hand, will return all the add-ons included in the collection. I'm not sure if this is expected or it should also be reconsidered.

**Comment by eviljeff** [comment]
We currently only display 4 (or 3 for themes) addons on each shelf, so I'm tempted to say that should be the default.  

I don't know if it should be overridable though?  Allow the count to specified in the criteria*?  An api param to the shelves api itself?  A specific setting on the shelf (i.e. stored on the model; set in the admin).

@bobsilverberg @xlisachan thoughts?

* /me would go with being able to specify the count in the criteria.

**Comment by bobsilverberg** [comment]
> We currently only display 4 (or 3 for themes) addons on each shelf, so I'm tempted to say that should be the default.
> 
> I don't know if it should be overridable though? Allow the count to specified in the criteria*? An api param to the shelves api itself? A specific setting on the shelf (i.e. stored on the model; set in the admin).
> 
> @bobsilverberg @xlisachan thoughts?
> 
> */me would go with being able to specify the count in the criteria.

Yes, I think that's the best approach. That way, if the requirements for the frontend change, the frontend can simply request a different number of add-ons.

**Comment by bobsilverberg** [comment]
> > We currently only display 4 (or 3 for themes) addons on each shelf, so I'm tempted to say that should be the default.
> > I don't know if it should be overridable though? Allow the count to specified in the criteria*? An api param to the shelves api itself? A specific setting on the shelf (i.e. stored on the model; set in the admin).
> > @bobsilverberg @xlisachan thoughts?
> > */me would go with being able to specify the count in the criteria.
> 
> Yes, I think that's the best approach. That way, if the requirements for the frontend change, the frontend can simply request a different number of add-ons.

Actually. I just changed my mind!

The frontend will no longer be requesting the add-ons for each shelf individually, but rather issuing a single API request for the whole lot. We already have a case where we only show 3 add-ons for a theme shelf, but 4 add-ons for an extension shelf, so I think it makes more sense for it to be a property on the shelf itself, managed in the admin. That way each shelf can express how many add-ons it expects.

**Comment by eviljeff** [comment]
Should we show the `page_count=x` parameter on the `url` field in the [response](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#homepage-shelves) too?  (I'm not super clear on the use case for the `url` field)

**Comment by AlexandraMoga** [comment]
The shelves API - https://addons-dev.allizom.org/api/v5/shelves/ - is now returning 4 add-ons for extensions (`search` endpoint) and 3 for themes (`search-themes` endpoint).

@eviljeff for Collection shelves we are also returning 4 add-ons, same as for extension shelves. I suppose this will be remedied by  #16397 ?

**Comment by eviljeff** [comment]
> @eviljeff for Collection shelves we are also returning 4 add-ons, same as for extension shelves. I suppose this will be remedied by #16397 ?

It could be - the collections endpoint can't really be filtered by add-on type (currently) so I defaulted to 4.  Once #16397 happens an admin could override it though.
