### ISSUE TITLE
The buttons from More actions section on the review page are not functional

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16368]
STR:
1. I tried to click notify me about listed versions on a review page such as https://reviewers.addons.allizom.org/en-US/reviewers/review/%E5%83%8D-%E3%81%A9%E3%81%86-d%C5%8D-%E3%81%AF%E3%81%9F%E3%82%89-%E6%A6%8A-%E3%81%95%E3%81%8B%E3%81%8D55

Expected result:
I should be able to check the box. 

Actual result: 
it's greyed out 
With an API error:

https://reviewers.addons.allizom.org/api/v5/reviewers/addon/1003954/subscribe_unlisted/

This is reproducible on AMO stage - FF84(Win10). 

![notify me about](https://user-images.githubusercontent.com/33448286/105372576-65136700-5c0e-11eb-98c9-27c6a2adc940.gif)

**Comment by ioanarusiczki** [comment]
Further checking More Actions section - none of the buttons seem to be working. 
Force disable addon
and the two yellow Disable Listed Auto Approval 

Block add-on worked for me. - it redirects to django

**Comment by wagnerand** [comment]
The API responds with 403 Forbidden.

**Comment by diox** [comment]
Fixed by ops in https://github.com/mozilla-services/cloudops-deployment/pull/4178

**Comment by ioanarusiczki** [comment]
403 Forbidden - API errors are no longer displayed and the buttons are functional now. - AMO stage FF84(Win10).
