### ISSUE TITLE
Statistics pages continue to show the loading indicators or data on the pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16366]
Statistics pages continue to show the loading indicators and 503 Service Unavailable errors in the Network, when the switch is enabled.

![js errors on both servers](https://user-images.githubusercontent.com/33448286/105179872-899a1100-5b32-11eb-9a1c-7bada3632353.gif)

The issue is not reproducible when the switch is disabled. 
Verified on AMO dev - FF84(Win10).

**Comment by willdurand** [comment]
Looks like "sub-"pages aren't handled correctly but it's fine because the banner says stats are disabled anyway and nothing is broken.

**Comment by ioanarusiczki** [comment]
@willdurand The 503s are present in the Network but visually the loading indicators are no longer present. 

I see that the case when the banner and the stats are both visible is reproducible only when the stats pages were opened in a tab and after that I enable the switch. 

![when tab was open](https://user-images.githubusercontent.com/33448286/106141426-bd9bb480-6178-11eb-91be-08e9ead1f5ff.png) 

If that would be an issue, let me know.

This is verified on AMO dev - FF85(Win10).
