### ISSUE TITLE
Robots.txt has invalid collections defined as Allow directives

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#16378]
### Describe the problem and steps to reproduce it:

See https://addons.mozilla.org/robots.txt 

Here's a sample from robots.txt at time of writing:
```
# robots.txt file for Mozilla Add-ons, addons.mozilla.org
User-agent: *
Allow: /

Disallow: /firefox/downloads/
Disallow: /android/downloads/

Allow: /af/firefox/collections/4757633/
Disallow: /af/firefox/search/
Disallow: /af/firefox/collections/
Disallow: /af/android/search/
Disallow: /af/android/collections/

Allow: /ar/firefox/collections/4757633/
Disallow: /ar/firefox/search/
Disallow: /ar/firefox/collections/
Disallow: /ar/android/search/
Disallow: /ar/android/collections/
```

`/[LOCALE]/firefox/collections/4757633/` 301s to https://addons.mozilla.org/[LOCALE]/firefox/collections/ so it probably doesn't make sense as an Allow: directive any more.

Also I'm wondering if we could consider using wildcards for locales and app names? See https://developers.google.com/search/reference/robots_txt?hl=en&authuser=1#url-matching-based-on-path-values for the reference as to what matches. 

If it helps the (source for the current robots.txt is here: https://github.com/mozilla/addons-server/blob/63ee3ebdbd96d4cbd5765c58b11c17055f6dd314/src/olympia/amo/templates/amo/robots.html

**Comment by eviljeff** [comment]
Ah, yeah, we removed the list of collections for a user - even for the mozilla user - a while back.  (this template was probably overlooked because it builds the url manually rather than using a proper url name)

**Comment by eviljeff** [comment]
> Also I'm wondering if we could consider using wildcards for locales and app names? See https://developers.google.com/search/reference/robots_txt?hl=en&authuser=1#url-matching-based-on-path-values for the reference as to what matches.

We could?  At that point it'd basically be a static file and probably best relocated to addons-frontend where any crawlable pages live, imo.

**Comment by eviljeff** [comment]
/recommend repurposing this issue into "reimplement robots.txt on addons-frontend"

**Comment by eviljeff** [comment]
> 
> 
> /recommend repurposing this issue into "reimplement robots.txt on addons-frontend"

Although... maybe the SEO work might end up with needing some dynamic content from the DB again?

**Comment by diox** [comment]
Yeah we might not need to tweak it all that much, but it's probably best to stay in addons-server in case we need some extra dynamic stuff in there. 

I don't recall why we didn't use wildcards, but I don't see a problem with the flat list - it's all generated by a loop anyway, so if it's safer, why not... We should remove the obsolete stuff though.
