### ISSUE TITLE
Check for valid email address before kicking the user off to FxA

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1637]
## steps to reproduce:
1. Load https://addons.allizom.org/en-US/firefox/users/login?to=%2Fen-US%2Ffirefox%2F
2. Enter "test" for Email Address
3. Click Continue

## expected behavior:
There is frontend validation to make sure that users are entering a valid email address before we send them to FxA.

## actual behavior:
The user ends up on FxA page even on entering an invalid email address.

**Comment by ValentinaPC** [comment]
A warning is displayed now if user is entering just a text in the email field, blocking the user to go forward.
I don't know if "test@1" can be a valid email address, but user ends up to FxA page.
Is this the intended behavior, mstriemer?

Please see the screencast: http://screencast.com/t/T88mWyziu4Bs

**Comment by mstriemer** [comment]
I think it might technically be valid. There are all sorts of weird valid email addresses so I think it just checks that there's an `@` and it doesn't end in a `.`.

The validation is in Firefox so I'm fine with whatever it comes up with as long as we stop the user from entering their username and going to FxA which this does.
