### ISSUE TITLE
Tidy up predefined icon_type support in Addon / devhub

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16379]
Now #16114 has turned all predefined icons into custom icons, there are no add-ons remaining that have a predefined icons selected - only custom icons or the default puzzle piece.  

So we can remove all code that relies on `icon_type` starting with `icon/`; the icons themselves in /static/; and the js/template support for selecting an icon from a list.  (some of this could be spun out into separate issues)

**Comment by rajpratyush** [comment]
hi @eviljeff Is this issue open for work? I would like to work on it.

**Comment by eviljeff** [comment]
> hi @eviljeff Is this issue open for work? I would like to work on it.

It is available yes.  Note: it's not a good first bug (good first bugs are suitable for new contributors who are starting in python/django where we'll help and explain exactly what code changes to make; for contrib:welcome issues you will work out what needs to be changed.).    That said, let us know if you have questions on the scope of the issue.

**Comment by rajpratyush** [comment]
@eviljeff I just just like to know what are files associated with this change and their location.

**Comment by eviljeff** [comment]
the icons are in static/img/addon-icons/ (keep default though); the python changes will be in the Addon model in src/olympia/addons/models.py and possibly src/olympia/devhub/forms.py + whatever tests there are that fail and/or seem like they set `icon_type` to a `icon/...` string.  

There is some javascript code in static/js/<somewhere> too but that can be left to a follow-up issue (it's a bit fragile and we don't have any CI testing for it!)

**Comment by eviljeff** [comment]
@rajpratyush are you still working on this?

**Comment by rajpratyush** [comment]
Yes i am but actually i have been caught up in semester exams thaty unable to complete it

**Comment by Mitrajit** [comment]
@eviljeff I would like to work on this issue. I have found 2 conditional blocks in src/olympia/addons/models.py and src/olympia/devhub/forms.py that checks if `icon_type` starts with `icon/` or not. https://github.com/mozilla/addons-server/blob/e746ef6517adca2c04162e516095932aff3908ad/src/olympia/addons/models.py#L1082-L1085 https://github.com/mozilla/addons-server/blob/e746ef6517adca2c04162e516095932aff3908ad/src/olympia/devhub/forms.py#L323-L327 Shall I remove these 2 conditional blocks?

Also, I found /src/olympia/addons/tests/test_commands.py tests on `icon_type` with `icon/..` like https://github.com/mozilla/addons-server/blob/d9467f6030b3a3e4642950e415ed118fc823b74a/src/olympia/addons/tests/test_commands.py#L623 Let me know if I have to make any changes to this.

**Comment by eviljeff** [comment]
@Mitrajit seems right, but I'll check when the pull request is ready.  You'll see what (if any) other tests need changing when you run the tests and they cfail (locally running `pytest src/olympia/devhub/tests/` will probably catch most problem areas, or just rely on circleci CI tests after you upload to github)

`create_custom_icon_from_predefined` can go entirely - I wrote it to convert the predefined icons.

` if not addon.icon_type or addon.icon_type.split('/')[0] == 'icon':` wouldn't be removed entirely - `addon.icon_type` can still be falsey.

**Comment by AlexandraMoga** [comment]
I've verified that add-ons using the old predefined icons are still being rendered and checked that custom icons can be uploaded and changed. 

This issue is verified fixed on -dev.
