### ISSUE TITLE
Start testing with django 3.2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16380]
We stick to the LTS track for django releases, and we're currently on 2.2.  The next LTS, 3.2, is available in alpha release form (https://docs.djangoproject.com/en/3.2/releases/3.2/) so it's a good time to see what work we'll need to do to upgrade.  

There's no rush - 3.2 won't be released until at least April 2021, and 2.2 will be supported until April 2022.

First step will be to get the test suite running (not necessarily all tests passing)

**Comment by jcoombes** [comment]
Hi there, I would be interested in taking this on.

**Comment by eviljeff** [comment]
> Hi there, I would be interested in taking this on.

This isn't a good issue for outside contribution - we don't know the scope and it's likely to require (a lot) of experience with django to debug the problems, (plus knowledge of tox and circleci config to get the additional tests running the in the meantime).  

See https://wiki.mozilla.org/Add-ons/Contribute/Code#Improve_addons.mozilla.org_.28AMO.29 for details of how to contribute - there are a few good first bugs, and we have quite a few contrib:welcome issues if you are experienced in django (or React,etc for frontend)

**Comment by eviljeff** [comment]
#16405 is from reading django release notes for 3.0, 3.1, and 3.2 - addressing some or all of the breaking changes may be necessary to get a reasonably passing test suite.

**Comment by AlexandraMoga** [comment]
@eviljeff is there any QA needed for this issue?
