### ISSUE TITLE
Too many requests to one url causing periodic connection spikes

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#16381]
### Describe the problem and steps to reproduce it:
Recently we started to see periodic connection spikes on proxy and olympia_web instances. Here is what it looks like when it happens.

<img width="803" alt="Screen Shot 2021-01-23 at 12 59 00 AM" src="https://user-images.githubusercontent.com/2209111/105619825-3bdc0d80-5dab-11eb-8eff-7ce9491e1b39.png">

When the spikes happen, we see olympia_web takes longer to respond (response time can be tens of seconds) and then ELB surge queue can quickly overflow and 50Xs are thrown.

### What happened?
The above screenshot shows one occurrence of such an event. It happened on 1/22 from 6:30 to 12:30 UTC. When we investigated the issue, we found it might have to do with too many requests for a particular URL during that period of time.

The URL in question is `/api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity`. 

During the 6 hours we received about 16.8 million requests and about 8.5 million were for the said URL, in other words, it counts for ~50% of the incoming traffic the server received.

We counted about 2.3+ million unique IPs for the 8.5 million requests and no IPs had sent too many repeated requests either. Judging by that, it is unlikely that this was some intentional DoS attack.

Some example log lines look like this:

```
1611295207.529 "156.190.71.185" "GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 209684 "-" "Mozilla/5.0 (Android 7.0; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0" 1.384 1.384 "-"
1611295207.531 "177.228.185.202" "GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 209575 "-" "Mozilla/5.0 (Android 10; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0" 0.035 0.035 "-"
1611295207.537 "178.115.129.34" "GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 209570 "-" "Mozilla/5.0 (Android 10; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0" 0.588 0.588 "-"
1611295207.540 "217.254.198.38" "GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 209684 "-" "Mozilla/5.0 (Android 10; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0" 0.247 0.247 "-"
1611295207.546 "90.248.45.144" "GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1" 200 209709 "-" "Mozilla/5.0 (Android 6.0; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0" 0.194 0.194 "-"
``` 

### What did you expect to happen?

I think we should avoid a single URL being called so heavily in a short period of time but rather spread the calls over a longer period of time.

Do we know what is about collection `7dfae8669acc4312a65e8ba5553036`, and why so many clients try to access it periodically?

The api that's called is `v4`. I'm not sure if that helps determine the cause or not (I think we released `v5` on 1/21).
### Anything else we should know?
n/a

**Comment by diox** [comment]
This is the collection used to determine [which add-ons are available for Fenix](https://addons.mozilla.org/en-US/firefox/collections/4757633/7dfae8669acc4312a65e8ba5553036/). It's cached both on our end and on the clients, but eventually all Fenix clients periodically fetch it again.

**Comment by diox** [comment]
Note: at the moment for server-side caching we rely on in-app caching. When Fenix 85 is released (which should happen very soon) it should use services.addons.mozilla.org for its API requests, to we'll get caching at a slightly higher level from nginx config, which should help. 

That version will also contain a fix for requests made without a trailing slash (which is causing an extra round-trip as we answer with a redirect to the proper URL with the trailing slash)

**Comment by bqbn** [comment]
There were 1,004,725 requests that took more than 1 second to respond (the normal respond time is in milliseconds). Out of the 1 million requests here are the top 10 URLs that appeared most:

```
 567302 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1
  50018 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons?page_size=50&sort=-popularity HTTP/1.1
  38142 GET /api/v5/site/ HTTP/1.1
  31504 GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons/ HTTP/1.1
  27140 GET /api/v4/accounts/account/mozilla/collections/3204bb44a6ef44d39ee34917f28055/addons/ HTTP/1.1
  17264 GET /api/v4/accounts/account/mozilla/collections/83a9cccfe6e24a34bd7b155ff9ee32/addons/ HTTP/1.1
  16444 GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1
   3426 GET /api/v4/accounts/account/mozilla/collections/3204bb44a6ef44d39ee34917f28055/addons HTTP/1.1
   1827 GET /api/v4/accounts/account/mozilla/collections/83a9cccfe6e24a34bd7b155ff9ee32/addons HTTP/1.1
   1518 GET /api/v5/hero/?lang=en-US HTTP/1.1
```

The leading number is how many times a url was hit (out of that 1 million requests).

During the 6 hours, even 301 redirect took tens of seconds. For example,

```
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 32.216
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 28.660
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 28.071
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 27.418
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 27.355
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 26.925
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 26.275
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 25.909
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 25.351
GET /api/v4/accounts/account/mozilla/collections/16f6e5d9a40448b8955db57ced6d75/addons HTTP/1.1" 25.347
```

The trailing numbers are the response times.

**Comment by diox** [comment]
I filed https://github.com/mozilla/addons-server/issues/16406 for the perf aspect to collections add-ons endpoint, which should help us answer those requests.

**Comment by bqbn** [comment]
We had another 6-hour connection spike for `olympia_web` component last night (1/29/2021), and not surprisingly it's because of the many requests to the `collections/` endpoints. Here are the top 10 URLs that appeared most.

```
 845158 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 10; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
 239242 GET /api/v5/site/ HTTP/1.1"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
 230470 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 9; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
 110511 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 8.0.0; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
 108515 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 10; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
 101521 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 11; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
  82156 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 8.1.0; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
  74000 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 7.0; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
  44459 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons/?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 6.0.1; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
  36623 GET /api/v4/accounts/account/mozilla/collections/7dfae8669acc4312a65e8ba5553036/addons?page_size=50&sort=-popularity HTTP/1.1"Mozilla/5.0 (Android 9; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
```

**Comment by diox** [comment]
We're trying to determine the reason behind the 6 hours window. In the meantime:

- Fenix 85 has been released and users are slowly going to upgrade. This release has switched to services.a.m.o. - so we'll have caching at the nginx level - and added the extra slash so we don't have to serve an extra redirect.
- Currently Fenix is making a request to that endpoint every 24 hours no matter what. Starting from Fenix 86 (to be released at the end of the month), this delay will be bumped to 48 hours https://github.com/mozilla-mobile/fenix/pull/17737
