### ISSUE TITLE
allow shelf addon count to be customizable

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16397]
#16367 will limit the addons returned to 4 per shelf (3 for search-themes shelves) but admins may want some shelves to return a different number for some reason.  So there should be an admin setting in the Shelf to override the default to another value.

**Comment by AlexandraMoga** [comment]
The shelfmodule admin includes now the Add-on count field that allows the number of add-ons returned per shelf to be customizable. 

Here are some examples:
- Add-on count set to 0 - the default number of add-ons is retuned (4 for extensions and collections and 3 for themes)
- Add-on count set to a custom number - the set number of add-ons will be returned for that shelf; if the search criteria provided doesn't include enough add-ons to satisfy the the custom number, the total number of extensions/themes within that search criteria will be returned

@eviljeff For the second point, it would be nice to have some validation to show the actual number of add-ons that will be returned if the set custom number is too high, but I'm not sure of the actual value it would bring to the end-users of this feature.

**Comment by eviljeff** [comment]
> Here are some examples:
> 
>     * Add-on count set to 0 - the default number of add-ons is retuned (4 for extensions and collections and 3 for themes)
> 
>     * Add-on count set to a custom number - the set number of add-ons will be returned for that shelf; if the search criteria provided doesn't include enough add-ons to satisfy the the custom number, the total number of extensions/themes within that search criteria will be returned
> 
> 
> @eviljeff For the second point, it would be nice to have some validation to show the actual number of add-ons that will be returned if the set custom number is too high, but I'm not sure of the actual value it would bring to the end-users of this feature.

It would be difficult to know what the user would consider an invalid number of add-ons to return though (e.g. if it's set as `6`, returning a validation error if only `5` are available at the current time seems overkill).  And that validation would execute every time the shelf was saved - so you wouldn't be able to edit an existing shelf either, if it had less than the count at the exact point you saved it.  We just have to trust the admin would set a custom cont for a particular reason and if it's less then they're aware of it.
