### ISSUE TITLE
Remove Adzerk integration

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#16390]
As part of cleaning up after the discontinuation of the Promoted Add-ons pilot, we should remove any Adzerk integration code we have on the server.

**Comment by bobsilverberg** [comment]
We might need a similar issue for addons-frontend, although I know a lot of the Adzerk-related code was removed with the Sponsored shelf was removed. I'll double check if we need one and open one if necessary.

**Comment by ioanarusiczki** [comment]
@eviljeff Can you add some str for qa?
Thanks!

**Comment by eviljeff** [comment]
there isn't really much to verify - the /api/v5/shelves/sponsored/ endpoint is gone.

**Comment by ioanarusiczki** [comment]
@eviljeff 
/api/v5/shelves/sponsored/ returns a 404.
