### ISSUE TITLE
Remove Stripe integration

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#16391]
As part of cleaning up after the discontinuation of the Promoted Add-ons pilot, we should remove any Stripe / payment integration code we have on the server.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified on AMO dev the following:
- admin promoted model - the sponsored/verified add-ons no longer have the subscription section available.
- I could add new add-ons as sponsored/verified and approve them as admin ( they require manual approval and I receive the rev tools message "Is in a promoted addon group that requires pre-review") 
- the re-sign of an approved version is no longer possible. 
- The verified badges are displayed on the frontend as before.
- I could change categories. From sponsored to verified, or to recommended and then approve a new version. 
- the categories available don't seem to be affected, but I'll test around a bit more. In case there's something I did not include in my testing please let me know.

**Comment by eviljeff** [comment]
Yes, all the promoted categories (and the logic around which need preview, etc) are still there as before - it's just the payments integration that's gone.  The promoted categories themselves will adjusted at some later point once we're clear what functionality is still worth keeping.
