### ISSUE TITLE
File hash isn't updated after duplicate version upload

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1639]
STR:
1) Upload new version for an existing add-on.
2) Have it approved or rejected by a reviewer.
3) Delete version.
4) Upload a different file with the same version number.
5) Have it approved again.

Result:
The add-on page offers the new file, but the file hash will correspond to the old one, causing a hash mismatch error if a user tries to install it.

Expected:
The new hash should be used, and the installation of the new file should work.

**Comment by wagnerand** [comment]
> 2) Have it approved or rejected by a reviewer.
A reviewer needs to approve it to produce this issue.

Also, this is a stop-gap until #1534 gets fixed which will make this impossible to occur.

**Comment by wagnerand** [comment]
This should no longer be possible due to rev982e8696

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win7).
Please see the screenshot: 
![2016-03-14_1205](https://cloud.githubusercontent.com/assets/15685960/13741143/390ad1aa-e9dd-11e5-98e1-9e39aa104f63.png)
