### ISSUE TITLE
Include shasum in file upload logging message for foxsec-pipeline

### ISSUE THREAD

**Issue by kkleemola** [mozilla/addons-server#16399]
We use this log statement in the foxsec-pipeline:
https://github.com/mozilla/addons-server/blob/b5eab7cc58aa319c35b7710bdc327becf5e87075/src/olympia/files/models.py#L545-L549

Recently we had a false positive and would like change the heuristic so instead of matching on the same file name being submitted by multiple users, it matches on the same file being submitted.

Please add the shasum as a field to this log statement so we can use it in the pipeline. Thank you!

**Comment by diox** [comment]
@kkleemola to confirm, adding it as part of the extra fields that get added to the json data is enough, no need to change the log message itself ?

**Comment by kkleemola** [comment]
Yes please.
If you change the logging message itself, I need to change a regex and it's quite brittle. I tested adding the field won't break our current parsing.

**Comment by diox** [comment]
Extra field containing the hash will be called `upload_hash` and be available starting from this Thursday around 9-10am Pacific Time.
