### ISSUE TITLE
Weight breakdown has the same values for both Code and Metadata

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16398]
Follow up for #16274

### Describe the problem and steps to reproduce it:
1. Log in on AMO-dev with a reviewer account
2. Open the review page of an add-on that has some risk weight associated - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/remote-script-coinhive
3. Hover over Code Weight then over Metadata Weight

### What happened?
The same weight breakdown is displayed for both categories

### What did you expect to happen?
Weight breakdown should be calculated based on the category it belongs to

![tt25kHzAZk](https://user-images.githubusercontent.com/31961530/105865680-d5016300-5ffb-11eb-9141-3fca16c501cf.gif)

**Comment by diox** [comment]
Yeah, the tooltip shows everything, I didn't think it was very important to break it down further yet.
