### ISSUE TITLE
potential issues with django 3.2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16405]
### Breaking changes/removals

* [ ] ForeignKey.validate() now uses _base_manager rather than _default_manager to check that related instances exist.
  * See comments below for discussion

* [x] The compatibility import of django.core.exceptions.FieldDoesNotExist in django.db.models.fields is removed.

* [x] The compatibility import of django.forms.boundfield.BoundField in django.forms.forms is removed.

* [x] The STATIC_URL and MEDIA_URL settings set to relative paths are now prefixed by the server-provided value of SCRIPT_NAME (or / if not set). This change should not affect settings set to valid URLs or absolute paths.
  * In dev, stage, prod, (and testing) we set these to a fully qualified URL; in settings_base (i.e. local dev) we use an absolute path `/static/` and `/user-media/` so, (unless I'm misintepretting the docs), we arne't affected.

* [x] Meta.ordering and Meta.unique_together options on models in django.contrib modules that were formerly tuples are now lists.
  * I don't think having models declared with tuples will cause a problem unless we have code that explicitly expects, for example, the super class `.ordering` to be a list. 

* [x] Model.save() when providing a default for the primary key. Model.save() no longer attempts to find a row when saving a new Model instance and a default value for the primary key is provided, and always performs a single INSERT query. In older Django versions, Model.save() performed either an INSERT or an UPDATE based on whether or not the row exists.

* [x] urlencode() now encodes iterable values as they are when doseq=False, rather than iterating them, bringing it into line with the standard library urllib.parse.urlencode() function.

### Deprecations (not removals but potentially worth fixing while we're at it)

* [x] The smart_text() and force_text() aliases (since Django 2.0) of smart_str() and force_str() are deprecated

* [x] django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() are deprecated in favor of the functions that they’re aliases for: django.utils.translation.gettext(), gettext_lazy(), gettext_noop(), ngettext(), and ngettext_lazy().

* [ ] To avoid possible confusion as to effective scope, the private internal utility is_safe_url() is renamed to url_has_allowed_host_and_scheme().
  * https://github.com/mozilla/addons-server/issues/16491

* [ ] The HttpRequest.is_ajax() method is deprecated as it relied on a jQuery-specific way of signifying AJAX calls, while current usage tends to use the JavaScript Fetch API. Depending on your use case, you can either write your own AJAX detection method, or use the new HttpRequest.accepts() method if your code depends on the client Accept HTTP header. If you are writing your own AJAX detection method, request.is_ajax() can be reproduced exactly as request.headers.get('x-requested-with') == 'XMLHttpRequest'.
  * https://github.com/mozilla/addons-server/issues/16490

* [x] Calling django.utils.crypto.get_random_string() without a length argument is deprecated.

* [x] django.conf.urls.url() alias of django.urls.re_path() is deprecated.

* [ ] The django.core.cache.backends.memcached.MemcachedCache backend is deprecated as python-memcached has some problems and seems to be unmaintained. Use django.core.cache.backends.memcached.PyMemcacheCache or django.core.cache.backends.memcached.PyLibMCCache instead.
  * https://github.com/mozilla/addons-server/issues/16489

**Comment by diox** [comment]
> `ForeignKey.validate()` now uses `_base_manager` rather than `_default_manager` to check that related instances exist.

This might have implications for handling of soft-deleted things - particularly when changing something (through a `ModelForm` or the admin) that has a relation to a soft-deleted instance... At the very least we should look if the lengthy comment around `base_manager_name` in soft-deletable models is still valid.

**Comment by eviljeff** [comment]
> 
> 
> > `ForeignKey.validate()` now uses `_base_manager` rather than `_default_manager` to check that related instances exist.
> 
> This might have implications for handling of soft-deleted things - particularly when changing something (through a `ModelForm` or the admin) that has a relation to a soft-deleted instance... At the very least we should look if the lengthy comment around `base_manager_name` in soft-deletable models is still valid.

Yeah, the reference to base and default managers made me suspicious - I've not investigated yet to see if it will affect us or how/when `.validate` is called.

**Comment by eviljeff** [comment]
Failing tests currently:

FAILED src/olympia/activity/tests/test_models.py::TestActivityLog::test_xss_arguments_and_escaping
FAILED src/olympia/bandwagon/tests/test_admin.py::TestCollectionAdmin::test_can_do_limited_editing_with_admin_curation_permission
FAILED src/olympia/bandwagon/tests/test_admin.py::TestCollectionAdmin::test_can_edit_with_collections_edit_permission
FAILED src/olympia/api/tests/test_exceptions.py::TestExceptionHandlerWithViewSet::test_view_exception
FAILED src/olympia/api/tests/test_exceptions.py::TestExceptionHandlerWithViewSet::test_view_exception_debug
FAILED src/olympia/blocklist/tests/test_admin.py::TestBlocklistSubmissionAdmin::test_add_and_edit_with_different_min_max_versions
FAILED src/olympia/blocklist/tests/test_admin.py::TestBlocklistSubmissionAdmin::test_add_single
FAILED src/olympia/blocklist/tests/test_admin.py::TestBlocklistSubmissionAdmin::test_edit_with_blocklist_create
FAILED src/olympia/blocklist/tests/test_admin.py::TestBlocklistSubmissionAdmin::test_signoff_approve
FAILED src/olympia/blocklist/tests/test_admin.py::TestBlocklistSubmissionAdmin::test_signoff_reject
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_ban - djang...
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_ban_button_in_change_view
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_can_edit_with_users_edit_permission
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_delete_picture
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_delete_picture_button_in_change_view
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_reset_api_key
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_reset_api_key_button_in_change_view
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_reset_session
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_session_button_in_change_view
FAILED src/olympia/users/tests/test_helpers.py::test_user_link_xss - assert M...
FAILED src/olympia/translations/tests/test_models.py::TranslationMultiDbTests::test_translations_queries
FAILED src/olympia/translations/tests/test_models.py::TranslationMultiDbTests::test_translations_reading_from_multiple_db
FAILED src/olympia/translations/tests/test_models.py::TranslationMultiDbTests::test_translations_reading_from_multiple_db_pinning
ERROR src/olympia/translations/tests/test_models.py::TranslationMultiDbTests::test_translations_reading_from_multiple_db
ERROR src/olympia/translations/tests/test_models.py::TranslationMultiDbTests::test_translations_reading_from_multiple_db_pinning

FAILED src/olympia/devhub/tests/test_views_submit.py::TestAddonSubmitDetails::test_submit_slug_invalid
FAILED src/olympia/devhub/tests/test_views_submit.py::TestStaticThemeSubmitDetails::test_submit_slug_invalid
FAILED src/olympia/devhub/tests/test_views_submit.py::TestVersionSubmitDetailsFirstListed::test_submit_slug_invalid

FAILED src/olympia/ratings/tests/test_models.py::TestRefreshTest::test_created
FAILED src/olympia/ratings/tests/test_models.py::TestRefreshTest::test_deleted
FAILED src/olympia/ratings/tests/test_models.py::TestRefreshTest::test_edited
FAILED src/olympia/shelves/tests/test_serializers.py::TestShelvesSerializer::test_addon_count

FAILED src/olympia/amo/tests/test_amo_utils.py::test_no_jinja_autoescape - As...
FAILED src/olympia/amo/tests/test_views.py::TestOtherStuff::test_opensearch
FAILED src/olympia/amo/tests/test_views.py::TestVersion::test_version_json - ...
FAILED src/olympia/amo/tests/test_views.py::TestContribute::test_contribute_json

**Comment by eviljeff** [comment]
from a quick look at some of the failing tests I've a feeling something about post_save stuff isn't working as before

**Comment by eviljeff** [comment]
updated failing test list to reflect what is passing/failing on my local branch.  tl;dr just the 4 failing tests in the elasticsearch job to address (and 3 of them are the same problem with bayesian averages with Ratings)

**Comment by eviljeff** [comment]
> > `ForeignKey.validate()` now uses `_base_manager` rather than `_default_manager` to check that related instances exist.
> 
> This might have implications for handling of soft-deleted things - particularly when changing something (through a `ModelForm` or the admin) that has a relation to a soft-deleted instance... At the very least we should look if the lengthy comment around `base_manager_name` in soft-deletable models is still valid.

The django3.2 [code](https://github.com/django/django/blob/3.2a1/django/db/models/fields/related.py#L921:L922):
> qs = self.remote_field.model._base_manager.using(using).filter(
            **{self.remote_field.field_name: value}
        )

rather than django2.2: 
> qs = self.remote_field.model._default_manager.using(using).filter(
            **{self.remote_field.field_name: value}
        )

From re-reading the docs/comments about managers, we always have `unfiltered = ...` before `objects = ...` because the first manager declared* becomes the `default_manager`, and we specifically call out that this is done because `default_manager` is used for validating foreign keys.  So... maybe we don't need to do this any longer in 3.2?  I can't think right now of another place that would use `default_manager`.  It's not clear to me if there any changes we _need_ to do for 3.2 (v.s clean-up we could do after 2.2 support is dropped)

*(really we should explicitly specify `default_manager_name` in `Meta` rather than rely on ordering magic)

The [docs](https://docs.djangoproject.com/en/dev/topics/db/managers/#django.db.models.Model._base_manager) seem contradictory though (new text bolded)
> Base managers aren’t used when querying on related models, **or when accessing a one-to-many or many-to-many relationship.**

**Comment by eviljeff** [comment]
filed https://github.com/mozilla/addons-server/issues/16492 for the tricky last few tests in the ES job.

**Comment by eviljeff** [comment]
Filed #16506 for any follow-up for base_manager changes.

**Comment by eviljeff** [comment]
QA: this issue mainly represents test fixes and things that aren't testable until we upgrade addons-dev to django3.2 (April at the earliest).  There were minor changes to 2 admin pages though -  User and Collection.

**Comment by AlexandraMoga** [comment]
I've used the Users and Collections admin tools and I haven't noticed any issues.

I'm marking this issue as verified fixed on dev and stage.
