### ISSUE TITLE
Make the easy/bulk django3.2 changes in the codebase

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16413]
part of #16405 - make the following easy find&replace-ish changes:

* [x] The compatibility import of django.core.exceptions.FieldDoesNotExist in django.db.models.fields is removed.

* [x] The compatibility import of django.forms.boundfield.BoundField in django.forms.forms is removed.

* [x] The smart_text() and force_text() aliases (since Django 2.0) of smart_str() and force_str() are deprecated

* [x] django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() are deprecated in favor of the functions that they’re aliases for: django.utils.translation.gettext(), gettext_lazy(), gettext_noop(), ngettext(), and ngettext_lazy().

* [x] Calling django.utils.crypto.get_random_string() without a length argument is deprecated.

* [x] django.conf.urls.url() alias of django.urls.re_path() is deprecated.

**Comment by willdurand** [comment]
For QA: the patch for this issue will affect many parts of the codebase. That being said, the patch looks fairly low risk so we don't have any particular things to verify. As far as there is no 500 (from the API, DevHub or admin), we should be good.

**Comment by AlexandraMoga** [comment]
I've verified many parts of the site and the API on -dev and I haven't found issues. I'm going to continue looking to make sure I cover as much as possible.

**Comment by AlexandraMoga** [comment]
No issues have been found on stage either. 

I'm marking this issue as verified fixed.
