### ISSUE TITLE
Allow API authentication with Bearer tokens

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1642]
In https://github.com/mozilla/addons-server/issues/1551 we would like to be able to create user accounts from the command line. It appears as though the easiest way to support this would be through the use of `Bearer` tokens.

The [PyFxa](https://github.com/mozilla/pyfxa) library has a requests plugin to support making requests with a Bearer token.

This could be used to make authentication with `jpm` easier as the user could enter the email and password on the command line and send a Bearer token the AMO's login endpoint to get an API key or use the Bearer token in place of the API key.

**Comment by muffinresearch** [comment]
We're working on solutions to related issues separately now so closing this one.
