### ISSUE TITLE
URL parsing bug (maybe, I dunno)

### ISSUE THREAD

**Issue by PELock** [mozilla/addons-server#16422]
Look at the description of my extension at (polish translation):

https://addons.mozilla.org/pl/firefox/addon/social-media-bot-auto-clicker/

At the end of the description you can read:

> Darmowa wersja pozwala na przetestowanie funkcjonalności rozszerzenia, jednak posiada ograniczenia m.in.

The **m.in.** is a polish abbreviation of "między innymi" (eng. among other things) and it's turned into a link because the inner **m.in** seems like a valid Indian domain name:

```html
<a href="https://outgoing.prod.mozaws.net/v1/055df171647633b00da859ede66ab3e8ee5d28056d96985d550d63d91639384c/http%3A//m.in" rel="nofollow">m.in</a>
```

I'm not sure if this is a bug or expected behavior to parse the "m.in." as a domain name (especially if the dot is at the end). I'm not sure if strings without protocol in front of them should be parsed as HTML hyperlinks. Let's see how GitHub parses those

m.in
m.in.
https://m.in
https://m.in.

**Comment by eviljeff** [comment]
Urls having `.` at the end is a legitimate thing if the url is in a sentence so there's not really a good way to differentiate `m.in` as a domain v.s. `m.in` as a word.  I think trying to fix this would introduce more edge cases - and "word.word." is a pretty unusual thing to write in normal language.  The description could be changed by the developer to `m. in` or `m .in` to workaround it (if they wanted to)
