### ISSUE TITLE
Show block reason on reviewer tools page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16444]
### Describe the problem and steps to reproduce it:

When an add-on is blocked, we show an entry in the version history on the reviewer tools page. That entry should also include the reason for blocking.

### What happened?

<img width="692" alt="blocka" src="https://user-images.githubusercontent.com/873258/106614799-0c2bc300-656c-11eb-903f-8319e26c0442.png">

### What did you expect to happen?

Reason should be included, like so:

<img width="545" alt="blockb" src="https://user-images.githubusercontent.com/873258/106614873-24034700-656c-11eb-9354-e435709b6e70.png">

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
The block reason is now visible in the add-on review page version history:

![image](https://user-images.githubusercontent.com/31961530/106751872-7a3abd80-6632-11eb-87c0-80e7ec3eba11.png)

This issue is verified fixed on stage.
