### ISSUE TITLE
Keep only a single file for each version

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16464]
Part of the removal of the `platform` field. #16448

Once ability to filter on `platform` is gone, we should remove the extra files and only keep one per version. The remaining file should be set for all platforms.

Note that this issue is just about removing the extra files, not rewriting the code/API to expose the remaining file differently.

**Comment by wagnerand** [comment]
As a first step, we can delete all but one file of a version that have the same `original_hash`.

**Comment by diox** [comment]
Ran the cleanup successfully on dev.

**Comment by diox** [comment]
Ran the cleanup successfully on stage & prod as well.
