### ISSUE TITLE
Remove platform field from API v5, shim it in previous versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16466]
Part of the removal of the `platform` field. #16448

We want to remove `platform` entirely in API v5, and shim it as `all` in earlier versions.

**Comment by diox** [comment]
Moving this to next milestone to keep things backwards-compatible in v5 for this week (otherwise at push time we may get errors from previous frontend code requesting new API without the field)

**Comment by ioanarusiczki** [comment]
@diox I verified on AMO stage - the detail, version detail, search, shelves APIs
- "platform": "all" has been removed from v5
-  "platform": "all" is available on v3/v4
