### ISSUE TITLE
calculate grouped ratings in addon_rating_aggregates task?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16467]
We currently calculate grouped ratings (counts of ratings with a particular score) on demand and store the result in cache per addon.  If this is something we regularly need it may be a better solution to calculate once per add-on asynchronously in a task and store in the database (and elasticsearch?) like we do with average rating, count, and bayesian average.

**Comment by diox** [comment]
I think that's a good idea. It's a better solution than what we do right now, and it makes sense since we already do that for the averages.

**Comment by eviljeff** [comment]
model options:

1. a JSONField on Addon with a dict for the counts
2. ~a new model, with fk to Addon, containing a single JSONField~
3. a new model, with fk to Addon, containing score_1, score_2, score_3, score_4, score_5
4. ~a new model with fk to Addon, containing score, count - i.e. up to 5 records per addon~

I'm discounting 2 as wasteful for only a single field and 4 as vast overkill for our use-case.  Leaning towards 3 - we could move over `average_rating`, `bayesian_rating`, `total_ratings`, and `text_ratings_count` in a follow-up if we wanted.  1. would be easiest to implement at the cost of an extra field on all addons.

**Comment by eviljeff** [comment]
#16522 went with 3.

**Comment by AlexandraMoga** [comment]
@eviljeff I've verified #16507 and the rating process (submitting, editing, deleting reviews, developer replies). I didn't find issues with any of these and the ratings count.
I've also had a quick look at the Ratings admin model.

Let me know if there is anything else to be verified.
