### ISSUE TITLE
Remove ability to filter by platform from the search/autocomplete APIs

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16463]
Part of the removal of the `platform` field. https://github.com/mozilla/addons-server/issues/16448

We need to remove ability to filter by platform from the search/autocomplete APIs and decide what to do about backwards-compatibility.

**Comment by diox** [comment]
Note: frontend will stop exposing that filter in https://github.com/mozilla/addons-frontend/issues/10047

**Comment by diox** [comment]
Regarding backwards-compatibility: https://github.com/mozilla/addons-server/pull/16524 will make it so there will only be one file per version, with the platform always set to `all`. So just ignoring the filter parameter should be enough - if there were filtering applied, it would have the exact same result.

**Comment by AlexandraMoga** [comment]
The `?platform` query parameter is ignored in the `/search/` and `/autocomplete/` APIs, namely the same number of search results is returned  no matter if the parameter is present or not. 

This issue is verified fixed on stage.
