### ISSUE TITLE
time out error when tried uploading source code in the version page of add-on

### ISSUE THREAD

**Issue by sugupta427** [mozilla/addons-server#16476]
I am trying to upload the source code on the version page of the add-on as suggested but on submitting the form I keep on getting timeout error shown below. Please assist me in uploading the source code as this is a required step for version update.
 
![image](https://user-images.githubusercontent.com/64141775/106998103-f6a3dc80-67a9-11eb-9e62-82e1e1c82678.png)
link to add-on -  https://addons.mozilla.org/en-US/firefox/addon/onenote-clipper/

**Comment by wagnerand** [comment]
@sugupta427 Can you please fill out the issue template and provide more context, such as a link to your add-on, timestamp of upload and sources file if possible?
