### ISSUE TITLE
Strategy for handling replies to deletion notification emails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16470]
### Describe the problem and steps to reproduce it:

When an AMO account gets deleted, either directly or through FxA, we send a [notification email](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/templates/users/emails/user_deleted.ltxt) to the user. Some of these users take us up and reply to amo-admins, saying they didn't their account.

### What happened?

These replies are not actionable to AMO admins, we have no insights on 
* how the account got deleted
* who deleted the account
* whether the person sending the email is the person who deleted the account
* whether the person sending the email has intentionally deleted their FxA account
* whether the FxA has potentially been taken over by a third party without the user noticing

### What did you expect to happen?

We need a strategy how to respond to such emails that usually say "I did not delete my account.", sometimes adding "Please restore it." or remove the sentence about replying to amo-admins.

### Anything else we should know?

@jvillalobos pointed out that some users probably don't read the warning when deleting their FxA account. That sounds plausible to me, but there is still not much AMO admins can do. The notification email already reiterates that it could have been caused by the FxA account deletion.
In the case where users forgot they even had an AMO account, I would expect their reply to be something along "I do not have an AMO account." (vs "I did not delete my account.")

Also, if I read the [code](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/admin.py#L207:L207) right, if an admin deletes an account, we send the email as well, which we might not want to.

**Comment by diox** [comment]
Context: https://github.com/mozilla/addons-server/issues/14512 and https://bugzilla.mozilla.org/show_bug.cgi?id=1466776

**Comment by jvillalobos** [comment]
@diox Bug 1466776 mentions logging for deleted accounts. Do those logs say how the account was deleted, particularly if it was auto-deleted via FxA? And are these logs easily accessible? If so, I think it'd be useful to look at the people who have emailed us to see if all/most of them deleted their account through FxA and maybe are just not reading the warnings.

**Comment by diox** [comment]
We do have logs that are specific to [deletion caused by FxA](https://github.com/mozilla/addons-server/blob/ff467054107eaa366b955c06a304796346b4e4bc/src/olympia/accounts/tasks.py#L51-L63), yes.

**Comment by wagnerand** [comment]
We received another email:

> I did not (at least not intentionally) delete ny Forefox account. Can we restore this?

Did we reach a conclusion what the next steps are? Can we update this email with more helpful copy? Also, can we either give admins guidance on how to respond or deactivate the amo-admins reply-to?

**Comment by eviljeff** [comment]
> 
> 
> We received another email:
> 
> > I did not (at least not intentionally) delete ny Forefox account. Can we restore this?
> 
> Did we reach a conclusion what the next steps are? Can we update this email with more helpful copy? 

Do you have suggestions for changes to the email that would lead to more users understanding it so they don't need help, or have the reply be actionable to admins?  I.e. what extra things can we include in the email template?

> Also, can we ... deactivate the amo-admins reply-to?

imo, making it harder to actually get to us isn't fixing the problem (of users not understanding), it will just lead to ill will towards us.

**Comment by wagnerand** [comment]
> imo, making it harder to actually get to us isn't fixing the problem (of users not understanding), it will just lead to ill will towards us.

I don't believe putting the burden on amo admins without guidance on what or how to reply encourages them to follow up timely, which will as well lead to ill will.
