### ISSUE TITLE
Show the FxA prompt on Developer hub

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1647]
## steps to reproduce:
1. Sign in to https://addons.allizom.org/en-US/developers/ using your old AMO login
2. Skip the option to switch to FxA

## observed behavior:
On public pages, we show "Add-ons is switching to Firefox Accounts for login. Sign in now to transfer your account." which we don't show on developer hub. We should prombably show that prompt on devhub as well.

**Comment by tofumatt** [comment]
This is still in the 47.3 milestone, but should likely be moved. Did it get fixed or should it be moved to 48.2?

**Comment by mstriemer** [comment]
I moved this to 48.3, I'm guessing I won't have time to look at it next week.

From what I recall this wasn't as trivial to add to the developer pages as it was to the regular frontend since I don't think it has any similar banners right now.

**Comment by mstriemer** [comment]
I won't have time to do this before London, and I'll be removing the migration after that so I guess this isn't going to happen.
