### ISSUE TITLE
Replace MemcachedCache backend with PyMemcacheCache or PyLibMCCache (post django3.2 fix)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16489]
from django release notes:
> The django.core.cache.backends.memcached.MemcachedCache backend is deprecated as python-memcached has some problems and seems to be unmaintained. Use django.core.cache.backends.memcached.PyMemcacheCache or django.core.cache.backends.memcached.PyLibMCCache instead.

**Comment by diox** [comment]
I've long be concerned about the fact that python-memcached was seemingly abandoned, so I'm not surprised. PyMemcacheCache is probably the best option for us - depends on https://github.com/pinterest/pymemcache which is also pure Python, supposed to be fast and well maintained.

**Comment by AlexandraMoga** [comment]
@eviljeff does this require QA?

**Comment by eviljeff** [comment]
I can't think of any specific QA here, so marking as QA not needed

**Comment by z4forzubair** [comment]
For anyone, who is not familiar with it. `pymemcache` has to be installed for the said change.
