### ISSUE TITLE
Eventually redirect new users to the page they were on before the signed up

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1648]
## steps to reproduce:
1. User is not signed in
2. Go to https://addons.allizom.org/en-US/firefox/addon/zenmate-security-privacy-vpn/?src=hp-dl-featured
3. Click on the 'Write a review' button
   ----> Note that the URL has a redirect to the review page after signing in
4. Register for a new FxA account
5. Complete the sign in process
## expected behavior:

User is eventually redirected to the review page so that they can add a review
## observed behavior:

After registration, user ends up in the profile page where they  can add a display name. This means, we never take them back to the review page. The user needs to search for the add-on again.

**Comment by mstriemer** [comment]
@designakt any thoughts on the flow here? I can think of two things we can do, could do both or just one or leave it as is (this is how it always worked before but clearly isn't ideal).

1. User attempts to perform action that requires authentication, redirect to FxA.
2. User registers for FxA.
3. User lands on account settings page.
  i) We show a link to continue to where you were.
  ii) We update the message to say "Please set your display name or username to continue." and submitting the form successfully redirects you to the last page.

<img width="762" alt="screenshot 2016-10-25 13 02 32" src="https://cloud.githubusercontent.com/assets/211578/19698170/cb64b00c-9ab3-11e6-85fc-d1645a8e5643.png">
> Current banner, for reference

**Comment by designakt** [comment]
@mstriemer Why do we need them to set a display name or username?
Let's use the name they set on FxA, not go to the settings page but instead back to the page they started on. (If they want to change their display name later on, they always can.)

**Comment by mstriemer** [comment]
If someone signed up for FxA the first time they most likely won't have a display name.

The reason we redirect to the account settings page is essentially just to get them to fill it in so we don't have an endless stream of reviews by **Anonymous user de131aba**.

Skipping the account page sounds good to me but we might want to come up with a way to prompt users to set a username or display name first. Here's what a user would see if we added a prompt for display name and profile photo on initial sign up:

![prompt-signin-short mov](https://cloud.githubusercontent.com/assets/211578/20367152/ee46e5ce-ac13-11e6-9f2a-7da4cf48fde3.gif)

**Comment by mstriemer** [comment]
If were fine with potentially more people having one of the **Anonymous user foo** names then skipping account settings is totally cool.

**Comment by designakt** [comment]
Thank you for the explanation and the demo. Great to see, and probably not as easily fixed as I had hoped. I will mention @pwalm so that we might consider improving that flow for the new AMO, or he already did, I don't know.

Maybe a popup on AMO sayin, 
**one last step** before we get you to do what you intended to do: 
**create a user name**, *how do you like the one we created for you?*

I do not think we need to solve this for the current AMO.
