### ISSUE TITLE
Replace NullBooleanField with BooleanField(null=True) (django3.2)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16498]
`BooleanField(null=True)` has been an alternative for `NullBooleanField` for a while, and is deprecated in django3.2 (to be removed in 4.0).  Because of its upcoming deprecation there's a(n annoying) system check warning about it whenever you launch a django shell, etc.  As it's already supported in django2.2 and a no-op at the database level we should just make the change to stop the complaining. 

https://docs.djangoproject.com/en/2.2/ref/models/fields/#nullbooleanfield

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by BenDeBrasi** [comment]
Hi, would I be able to work on this?

**Comment by patil2097** [comment]
If this issue is still available I would love to work on this. @eviljeff

**Comment by eviljeff** [comment]
> Hi, would I be able to work on this?

Yes.
It's just changing the fields as described in the issue summary, then creating the django migrations (`./manage.py makemigrations`)

**Comment by eviljeff** [comment]
> If this issue is still available I would love to work on this. @eviljeff

@BenDeBrasi already asked so it's not available right now.

**Comment by BenDeBrasi** [comment]
Is the idea to replace every instance of ```BooleanField(null=True)```  in the repository with ```NullBooleanField```  and then running the command you gave me? 

Also, I was trying to install add ons and Docker on my computer and I'm getting some errors. Would you be able to help with that?

**Comment by eviljeff** [comment]
> Is the idea to replace every instance of `BooleanField(null=True)` in the repository with `NullBooleanField` and then running the command you gave me?

yes

> Also, I was trying to install add ons and Docker on my computer and I'm getting some errors. Would you be able to help with that?

come speak to use in the AMO room on chat.mozilla.org

**Comment by BenDeBrasi** [comment]
I kept getting an error when I attempted to the site you linked. I looked at the documentation and made an account for matrix and found some Mozilla chat rooms. Will update once I've made progress.

**Comment by BenDeBrasi** [comment]
Apparently there is a bug in add ons that is being investigated. Once, it's been fixed and I have it installed I will begin work on the change.

**Comment by caitmuenster** [comment]
Hey @BenDeBrasi, we think that the bug you encountered might have been fixed. Have you been able to try again?

**Comment by BenDeBrasi** [comment]
Hey @caitmuenster I have been posting in the addons matrix channel for help installing add ons as my installation hasn't worked. I have had two issues so far, one which required an update to add ons code which worked and one where so far no one has been able to help me beyond things I have already tried. I have posted there again and hopefully will be able to get it working so I can make the change and test it.

**Comment by caitmuenster** [comment]
Sorry to hear that, @BenDeBrasi. If you're not able to set up the AMO server dev environment, no worries. Would you be interested in working on other Python bugs for other Mozilla projects? There's a list on [Codetribute](https://codetribute.mozilla.org/languages/python) for other projects that don't require the AMO server set up. :) 

If you'd prefer to work on an add-ons project, we also have other issues open that don't require the server set up: https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt

Please feel welcome to jump in to one of these issues! We're going to open this one up to other folks, though.

**Comment by ssudheerk99** [comment]
hey @eviljeff I've created a PR  #17057 for this issue, please let me know if that's all good or would it require any more fixes or changes

**Comment by diox** [comment]
Fixed by https://github.com/mozilla/addons-server/pull/17057
