### ISSUE TITLE
Fix ES test job under django3.2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16492]
All the CI tests are passing under django3.2 with the exception of 4 tests in the elasticsearch job:

> FAILED src/olympia/ratings/tests/test_models.py::TestRefreshTest::test_created
FAILED src/olympia/ratings/tests/test_models.py::TestRefreshTest::test_deleted
FAILED src/olympia/ratings/tests/test_models.py::TestRefreshTest::test_edited
FAILED src/olympia/shelves/tests/test_serializers.py::TestShelvesSerializer::test_addon_count

the 3 ratings/models tests are all failing in the same place (`test_created` - the other two call `test_created` to set up objects).  On the surface the fail is that the bayesian rating is different, but from digging further it appears that's there is an extra Addon instance in the database at the point the bayesian rating job in run (skewing the overall averages).  I.e. it's not strictly an elasticsearch problem.  I can't replicate locally currently (though I'm sure did earlier, when there were still a larger number of failing jobs/tests).  We can likely fix by clearing the database in `TestRefreshTest.setUp` but that shouldn't be necessary - all the tests are supposed to be run in isolation with database transactions so the extra `Addon` instance shouldn't _be_ there.

`TestShelvesSerializer::test_addon_count` could be a similar problem; also can't replicate locally.

**Comment by eviljeff** [comment]
The error has been narrowed down to `TestIndexCommand` - _sometimes_ an Addon remains in the database after the transaction has been rolled back

```diff
------------------ src/olympia/lib/es/tests/test_commands.py ------------------
index 55b8fb5fad..819a176070 100644
@@ -12,12 +12,23 @@ from django.test.testcases import TransactionTestCase
 from celery import group, task
 from celery.canvas import _chain
 
-from olympia.amo.tests import addon_factory, ESTestCase, reverse_ns
+import olympia.core.logger
+from olympia.addons.models import Addon
+from olympia.amo.tests import addon_factory as afactory, ESTestCase, reverse_ns
 from olympia.amo.utils import urlparams
 from olympia.lib.es.management.commands import reindex
 from olympia.lib.es.utils import is_reindexing_amo, unflag_reindexing_amo
 
 
+log = olympia.core.logger.getLogger('z.elasticsearch.tests')
+
+
+def addon_factory(*args, **kwargs):
+    addon = afactory()
+    log.info(f"'id': {addon.id}, 'slug': {addon.slug}")
+    return addon
+
+
 @task
 def dummy_task():
     return None
@@ -59,6 +70,15 @@ class TestIndexCommand(ESTestCase):
                 self.es.indices.delete(index, ignore=404)
         super(TestIndexCommand, self).tearDown()
 
+    @classmethod
+    def tearDownClass(cls):
+        super().tearDownClass()
+        try:
+            assert not Addon.objects.exists(), Addon.objects.values('id', 'slug')
+        except AssertionError as ae:
+            Addon.objects.all().delete()
+            raise ae
+
     def check_settings(self, new_indices):
         """Make sure the indices settings are properly set."""
``` 
(https://github.com/eviljeff/olympia/commit/504709f57c0b94a769092a054b67d15fe0ad1071)

The above commit exposes this by checking for Addons _after_ tearDownClass has rolled back the transaction and has supposedly tidied up all the add-ons creates within the test, and then deleting them so it doesn't pollute subsequent tests.

**Comment by eviljeff** [comment]
In `_test_reindexation` I'm suspicious of 
```
connection._commit()
connection.clean_savepoints()
```

**Comment by eviljeff** [comment]
fwiw, this is still broken on django 3.2RC1

**Comment by eviljeff** [comment]
I've been playing around with the superclass of `TestIndexCommand` and making it a `TransactionTestCase` rather than `TestCase` (so all the data would be rolled back, even if a transaction was committed) but `test_reindexation_starting_from_one_addon` fails, for an unclear reason, even on django2.2.

**Comment by eviljeff** [comment]
On the plus side, changing to `TransactionTestCase` _does_ fix the general brokenness in the ES tests under django 3.2.

error:
```
src/olympia/lib/es/tests/test_commands.py:176: in test_reindexation_starting_from_one_addon
    self._test_reindexation()
        self       = <olympia.lib.es.tests.test_commands.TestIndexCommand testMethod=test_reindexation_starting_from_one_addon>
src/olympia/lib/es/tests/test_commands.py:152: in _test_reindexation
    assert 'Reindexation done' in stdout, stdout
E   AssertionError: Starting the reindexation for test_amo_addons.
E     Building the task chain
E     Running all indexation tasks
E
E   assert 'Reindexation done' in 'Starting the reindexation for test_amo_addons.\nBuilding the task chain\nRunning all indexation tasks\n'
```

Another piece of debugging info: `print()`ing ` self.get_indices_aliases()` at various points in `_test_reindexation` shows it to be `[]` with `TransactionTestCase` but populated under a `TestCase` superclass.

**Comment by diox** [comment]
I thought I had fixed that by using a `TransactionTestCase` as @eviljeff pointed out above, but it was actually still broken, just intermittently passing... I added a simple `time.sleep(1)` in the loop that waits for the database to be flagged and suddenly it breaks even more consistently...

I think the way to go might be to completely remove these tests, which are just too broad and too fragile (they are really integration tests), and instead add more tests to ensure the proper indices and aliases are set up, and more tests covering what the code in `lib/es/utils.py` is doing, to ensure indexing works when there are multiple indices because of a reindexation is currently taking place etc.

**Comment by diox** [comment]
Note: it's probably a good idea to ensure the tests are finally stable and reliable before doing https://github.com/mozilla/addons-server/issues/17389
