### ISSUE TITLE
Change index & constraint names to be unique amongst models (post django3.2)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16497]
in django3.2 there are additional system checks which enforce that constraint and indexes have unique names, even accross different apps/models.

```
SystemCheckError: System check identified some issues:

ERRORS:
?: (models.E030) index name 'addon_id' is not unique among models: addons.Preview, bandwagon.CollectionAddon, ratings.Rating, tags.AddonTag, versions.Version.
?: (models.E030) index name 'application_id' is not unique among models: applications.AppVersion, bandwagon.Collection.
?: (models.E030) index name 'created_idx' is not unique among models: abuse.AbuseReport, activity.ActivityLog, addons.Addon, bandwagon.Collection, bandwagon.CollectionAddon, files.File.
?: (models.E030) index name 'listed' is not unique among models: addons.AddonUser, bandwagon.Collection.
?: (models.E030) index name 'status' is not unique among models: addons.Addon, files.File.
?: (models.E030) index name 'user_id' is not unique among models: bandwagon.CollectionAddon, users.UserNotification.
?: (models.E032) constraint name 'addon_id' is not unique among models: addons.AddonCategory, addons.AddonUser.
```

**Comment by eviljeff** [comment]
note, we can disable these checks (with no obvious impact) with:
```
SILENCED_SYSTEM_CHECKS = (
    'models.E030',
    'models.E032',
)
```

**Comment by eviljeff** [comment]
This seems to have come about from an edge-case with indexes/constraints on subclasses of models https://code.djangoproject.com/ticket/30362 (the subclass would inherit the index/constraint but then would cause an error because the database table would contain duplicate index/constraints with the same name).  

AFAIK we don't have any subclasses of models in addons-server so we wouldn't hit the bug.  

Because this prevents addons-server from even starting under django 3.2 I'm going to silence the system checks for now, but I think we should still look to make this change (imo) - it's a django rule now and we should aim to adhere as close as possible to the norms.

**Comment by willdurand** [comment]
What would we have to do to resolve this issue? Is it about renaming the indexes/constraints? If so, how costly is it? (e.g. does it take 1s or 1h to perform the changes in prod?)

I am asking because I don't understand why we'd prefer to silent these checks (vs. fixing the actual problems)

**Comment by eviljeff** [comment]
> What would we have to do to resolve this issue? Is it about renaming the indexes/constraints?

yes

> If so, how costly is it? (e.g. does it take 1s or 1h to perform the changes in prod?)

No idea - it's normally only possible to get an estimation by either seeing it run on stage or having ops run the migration on a replica.  Because it involves a lot of models - including Addon and File - it will block the database during the deploy (so ops will have to take steps to switch around the replicas), if not fully put the site in read-only mode for a period.

> I am asking because I don't understand why we'd prefer to silent these checks (vs. fixing the actual problems)

Laziness 😉 Skipping the checks for now unblocks further testing and development on django3.2 and doesn't cost us anything because we aren't affected by the bug.

**Comment by AlexandraMoga** [comment]
@eviljeff does this require QA?

**Comment by eviljeff** [comment]
No, it's purely database related.
