### ISSUE TITLE
define DEFAULT_AUTO_FIELD in settings (django3.2)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16499]
In django3.2 there's a system check warning to set a new property `DEFAULT_AUTO_FIELD` to whatever the default autofield class we want.  The default is probably what we want ('django.db.models.AutoField') - that's the current default if a primary key isn't manually defined.  (`DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'`).  

Though we do use `PositiveAutoField` for a few older models so the alternative it we manually specify an `AutoField` for the current models that don't use `PositiveAutoField` and specify `DEFAULT_AUTO_FIELD = 'olympia.amo.field.PositiveAutoField' to default to that going forward 🤷

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa.
Thanks!
