### ISSUE TITLE
"Only with Firefox — Get Firefox Now!" button for Firefox Developer Edition

### ISSUE THREAD

**Issue by jnachtigall** [mozilla/addons-server#1650]
I use Fx Dev Ed on Windows, still I get the message that I would not use Firefox on AMO. 

User-Agent is:

`User-Agent:"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0"`

![2016-02-09 09_37_42-tab groups __ add-ons for firefox - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/12911182/d85b6afe-cf10-11e5-804d-7a3da14f3741.png)

Happens for *all* addons on AMO.

BTW (do not know if related), but I also get "You're not using Firefox!" on http://fasezero.com/addons/ @Quicksaver FYI

**Comment by muffinresearch** [comment]
I can't reproduce using just that UA string on OSX or with that UA string with windows 10 with the current Firefox dev edition .

Would it be possible for you to try with a clean profile and see if that makes any difference?

Here's a document that has the details on how to start Firefox with the profile manager: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Quicksaver** [comment]
FYI fasezero.com/addons looks for "Firefox" in the useragent string as well. So just from that it should also work.

**Comment by jnachtigall** [comment]
@muffinresearch With a clean profile I can't reproduce either. Back with the normal default profile firefox is not detected again. Strange. What can cause this? Maybe an addon? I got the UA string from the network panel of the ffdev tools, so this should be what is sent to the server, I assume.

**Comment by muffinresearch** [comment]
@jnachtigall it's possible. You could try disabling addons in the affected profile to find one that might be the culprit.

A quicker way than turning off addons one by one is to bisect which addon is causing the problem. To do this disable half the addons then try. If the problem stops disable half of the previous set of add-ons you disabled - if the problem is gone, focus on the other set. Repeat the process until you get down to the one that is causing the problem.

**Comment by muffinresearch** [comment]
First you could disable all add-ons in the affected profile because if the problem is still there its not an add-on causing it.

**Comment by jnachtigall** [comment]
Disabled all addons: The problem remains! 

@Quicksaver I started wireshark to capture what is actually sent over the network to the server. The UA string that wireshark shows is: 
`User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0\r\n`

![2016-02-09 11_48_27-_ethernet](https://cloud.githubusercontent.com/assets/3307404/12914190/320c865c-cf23-11e5-87d7-e0f38a786d76.png)


Anything else to try?

**Comment by Quicksaver** [comment]
That is the request header that is sent to the server, it's irrelevant in fasezero.com, and I'm guessing the same is also true for AMO in this case. Instead of the network panel, go to the console (Ctrl+Shift+K) and insert ```navigator.userAgent``` in there to check if it also reports the same UA as that's what the website actually uses.

**Comment by jnachtigall** [comment]
`navigator.userAgent` gives me:
`Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:46.0) Gecko/20100101 /"` 

Still all addons disabled. Looks truncated (Firefox is missing at the end). Seems like this is the culprit.

**Comment by Quicksaver** [comment]
You could try [resetting your user agent](https://support.mozilla.org/kb/how-reset-default-user-agent-firefox).

If that works but after re-enabling your add-ons it happens again then one of them is causing the issue and fails to deinitialize properly (not reverting the changes) when it disables.

The worst case scenario may be to use a new profile. Maybe @muffinresearch will have better suggestions to fix things without resorting to that.

**Comment by jnachtigall** [comment]
Ok, I searched on about:config for useragent. Only field I could reset was `devtools.devices.url_cache`. It was the only user-set field. Afterwards the useragent was corrent again :-)

I enabled all addons again. Then useragent was truncated again :-( Going back to about:config, but now there are no user set fields, so nothing to reset:

![2016-02-09 13_15_52-about_config - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/12916008/66a0946a-cf2f-11e5-9ec2-473350982e78.png)

**Comment by wagnerand** [comment]
What add-ons are installed?

Maybe a dump of about:support helps more.

**Comment by jnachtigall** [comment]
Ok, I went to about:support. Clicked "Restart in Safe Mode" first. Then restarted in safe mode, I copied the config dump: https://pastee.org/wf6ng (all addons disabled)

Fun fact:
On websites `navigator.userAgent` is truncated. On all `about` pages (`about:config`, `about:support`) it is correct.

**Comment by jnachtigall** [comment]
Let's close this as its same wierd Fx Dev Ed thing... Seems to be unrelated to AMO. If anybody still has an idea, then let me know. Probably I'll just delete the profile and start with a new one.

**Comment by ValentinaPC** [comment]
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
Verified on old and new profile on AMO-dev and the issue is fixed or not reproducible anymore.
Screenshot for this issue: 
![2016-03-10_1821](https://cloud.githubusercontent.com/assets/15685960/13676088/0a780f26-e6ed-11e5-932e-5be9d74916fb.png)

**Comment by ValentinaPC** [comment]
@jnachtigall My job is (among other things) to verify bugs and trust nobody. ;)
