### ISSUE TITLE
Total ratings count includes ratings with a score of 0 for some old addons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16507]
### Describe the problem and steps to reproduce it:
1. Send the following request to the ratings api:
https://addons.mozilla.org/api/v5/ratings/rating/?addon=3006&show_grouped_ratings=true
2. Make a note of the total ratings `count` and then add up the `grouped_ratings`
3. Send the request again, but this time add a `score=0` parameter
4. Compare your results

### What happened?
At the time of this request: total ratings count is 26115; sum of grouped ratings is 26102; number of ratings with `score=0` is 12 (one rating still unaccounted for in this example). This discrepancy between total ratings and sum of grouped ratings is visible on the frontend.

### What did you expect to happen?
Total ratings and sum of `grouped_ratings` should always match. Ratings with `score = 0` should be excluded.

### Anything else we should know?
Another example:
https://addons.mozilla.org/api/v5/ratings/rating/?addon=adblock-plus&show_grouped_ratings=true
Total ratings=13,623; sum of grouped ratings=13612; ratings with `score=0`=11

For these examples, the `score=0` ratings are very old. I don't think this issue will happen with more recent addons/ratings.

**Comment by eviljeff** [comment]
I coincidentally noticed a similar thing yesterday when writing #16522.  It's an edge case because they're super old.
@jvillalobos do you have an opinion on if we:
a. include ratings without score in the total count (wontfix)
b. exclude ratings without a score total count.  `text_count` would still include them(?)
c. delete the ratings because they're old bad data

`select count(*) from reviews where rating=0 and reply_to is null;` == 1,002 on prod - newest is from 2008-04-16

**Comment by eviljeff** [comment]
fwiw, I just pushed a 1 line addition to #16522 that will affectively do b.

**Comment by jvillalobos** [comment]
I'm fine with `c` and `b`.

**Comment by AlexandraMoga** [comment]
@eviljeff the `grouped_ratings` are showing a count of `0` for all scores:

https://addons-dev.allizom.org/api/v5/addons/addon/3006/?show_grouped_ratings=true
```
    "ratings": {
        "average": 4.3619,
        "bayesian_average": 4.361576634593846,
        "count": 4110,
        "text_count": 4104,
        "grouped_counts": {
            "1": 0,
            "2": 0,
            "3": 0,
            "4": 0,
            "5": 0
```
For https://addons-dev.allizom.org/api/v5/ratings/rating/?addon=3006&show_grouped_ratings=true the total ratings `count` is `1` while the `grouped_ratings` are showing `0` overall.

Another example: 
Detail API: https://addons-dev.allizom.org/api/v5/addons/addon/adblock-plus/?show_grouped_ratings=true
Ratings API: https://addons-dev.allizom.org/api/v5/ratings/rating/?addon=adblock-plus&show_grouped_ratings=true

These aren't the only examples. Most of the add-ons with ratings have this issue - total count and `grouped_ratings` count are not matching: https://addons-dev.allizom.org/en-US/firefox/search/?sort=rating&type=extension

I think those old ratings have been deleted with the 'hard-delete legacy add-on versions' task - #16478

**Comment by diox** [comment]
> I think those old ratings have been deleted with the 'hard-delete legacy add-on versions' task - #16478

That task should delete ratings attached to legacy versions, yes. Those versions should already have been deleted or disabled long ago through, so the ratings attached to those should not count towards the totals.

**Comment by eviljeff** [comment]
> @eviljeff the `grouped_ratings` are showing a count of `0` for all scores:

There was a command to back-fill the rating counts - I've done that now.

**Comment by AlexandraMoga** [comment]
I've verified several add-ons and I couldn't find discrepancies anymore.

Example:
https://addons-dev.allizom.org/api/v5/addons/addon/adblock-plus/?show_grouped_ratings=true
```
    "ratings": {
        "average": 4.25,
        "bayesian_average": 4.216066391272007,
        "count": 8,
        "text_count": 6,
        "grouped_counts": {
            "1": 0,
            "2": 0,
            "3": 1,
            "4": 4,
            "5": 3
        }
    },
```

I'm marking this issue as verified fixed on -dev.
