### ISSUE TITLE
Force authentication for certain account views

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1652]
It would be nice to require the user the enter their password to perform certain actions like deleting an add-on or deleting their account, perhaps even changing their email address. Since this isn't as straightforward with FxA as it was with regular username/password login we should come up with a generic solution that can be used as a decorator or form mixin.

Decorator example:

``` py
@force_auth_required(timeout=timedelta(minutes=5))
def delete_addon(request, addon):
    # Same old delete_addon view with a form, etc but before
    # the user can view this page they must authenticate with FxA.
    # This should work very similarly to the @login_required decorator.
```

**Comment by Abhi-khandelwal** [comment]
hey @mstriemer , I want to work on this issue as my first contribution

**Comment by mstriemer** [comment]
Hi, I no longer work on this project and I'm not sure if this is a good first bug but someone else on the team can help you out. I think @diox has looked at the authentication code some since then.

**Comment by diox** [comment]
@Abhi-khandelwal please pick something else as your first contribution, this is complex work, requiring knowledge of FxA and coordination with the team responsible for it. (https://bugzilla.mozilla.org/show_bug.cgi?id=1432189 has more information for people interested)
