### ISSUE TITLE
Expose `versions_url` in API response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16534]
FF needs the URL to the "Version History" for https://bugzilla.mozilla.org/show_bug.cgi?id=1688045 so we need to expose it in the API response for an add-on. The property will be named `versions_url` and we'd need it in API v4 too.

For QA: the new field should appear for all API versions.

**Comment by willdurand** [comment]
@eviljeff given that it's a new property, do we still need a gate? (without a gate, it will be added to all API versions)

**Comment by eviljeff** [comment]
> @eviljeff given that it's a new property, do we still need a gate? (without a gate, it will be added to all API versions)

It's not necessary - it won't break existing users. If it needs to be available in v4 for Firefox it'd only be hidden from (the deprecated) v3 anyway so even less reason.

**Comment by ioanarusiczki** [comment]
@willdurand 

v3,v4,v5 addon detail API returns the versions_url property into the response:
"versions_url": "https://addons-dev.allizom.org/en-US/firefox/addon/bitwarden/versions/"

Verified on -dev.
