### ISSUE TITLE
Switching email address during FxA migration silently fails?

### ISSUE THREAD

**Issue by rfk** [mozilla/addons-server#1655]
(Originally filed in https://github.com/mozilla/fxa/issues/118, surfacing here for broader context and input)

When migrating from an existing AMO account, if I choose an FxA email address that's:
* different to the one I use in AMO, and
* already exists in AMO as a separate user account

Then the migration seems to silently fail.  STR:

1) On AMO, choose "log in" and enter an account that exists but has not yet been migrated.
2) You're prompted for your existing AMO password, enter it.
3) You're prompted to migrate to Firefox Accounts, choose "continue".
4) On the FxA signin form, change the email address and sign in as a different account, one that already exists in AMO and has been migrated
5) You're redirected back to AMO and are still logged in as the original user.  (This is OK, because you entered the password for that user back in step 2.  But it was definitely surprising!)
6) Log out, and log back in to AMO as the same user.  You're again prompted to migrate to Firefox Accounts.

If in step (4) you choose an email that *doesn't* exist in AMO, the migration appears to succeed.

**Comment by mstriemer** [comment]
The user is being redirected to the login view to be shown an error but since the user is already logged in they get redirected to the homepage. This should instead redirect back to the migration view to display the error if the user is logged in.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-03-14_1117](https://cloud.githubusercontent.com/assets/15685960/13739930/a0f7b76c-e9d6-11e5-87d4-b125a7892f8d.png)
