### ISSUE TITLE
Do not expose who blocked an add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16551]
### Describe the problem and steps to reproduce it:

When an add-on gets blocked, we trigger a rejection for all affected files in order to disable them. 

### What happened?

The reviewer name of this rejection action is exposed in the developer hub.

### What did you expect to happen?

We should use the "task user" for the rejection.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
QA:

* In the reviewer tools, the user logged for the rejection action should be "Mozilla Firefox". (The user logged for block action should be the real human user.)
* In the developer hub, the recent changes/activity page (`/developers/feed/<slug>`) should list the rejection action with the "Mozilla Firefox" user, not the real human user.
* There should no rejection email be sent to the developer.

**Comment by ioanarusiczki** [comment]
@wagnerand 
I verified on AMO dev - FF85(Win10): 
- the rev tools detail pages display the name of the user (display name) for the block action and Mozilla for the rejection
 
![block and rejection](https://user-images.githubusercontent.com/33448286/108053213-cab01300-7055-11eb-8205-1d157dfd2dde.png)

- dev hub feed shows Mozilla at rejection
![rejected by Mozilla](https://user-images.githubusercontent.com/33448286/108053046-98061a80-7055-11eb-993e-c542240029a5.png)

- I did not see an e-mail being sent to the developers, in [fakemail](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/).
