### ISSUE TITLE
"Cancel and Disable Version" from the source code page should be removed for unlisted addons

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16562]
1. A developer uploads a file - using the unlisted channel (a new addon or version) and clicks Sign add-on
2. The Source Code page is the next step where there's "Continue" or "Cancel and Disable Version" buttons
3. Click "Cancel and Disable Version" and confirm "Yes, cancel"

Actual result:
The submitted version is in awaiting review state - it will be automatically signed. 

Expected result:
The red button should not be displayed - it has no role since the add-on is already signed. 

Notes:
This is reproducible on all AMO servers - FF85(Win10).

**Comment by wagnerand** [comment]
I think listed and unlisted versions are auto-approved the same way these days, so this would equally apply to listed (except if it's the first version of an add-on).

I think the right solution here is to wait until the submissions process has completed before signing the add-on.

**Comment by ioanarusiczki** [comment]
@wagnerand A new listed version gets "Disabled by Mozilla" when Cancel and Disable Version is used same way as a first submitted version. At least, this is what I see in dev hub when I'm redirected

![new disabled version](https://user-images.githubusercontent.com/33448286/108180985-0c04f900-7110-11eb-99ac-6c56e2665c30.png)

**Comment by diox** [comment]
The code behind `Cancel and Disable Version` only disables for the listed, yes. I think this is because at the moment it doesn't receive the channel, so it doesn't know which version to disable.

In fact, there is probably another bug hidden there. I haven't tried it, but looking at the code, I think this would be:
- Submit a listed version
- Before it has the chance to be auto-approved, submit an unlisted versions and immediately use `Cancel and Disable Version` at the end of the flow

Actual result:
- *listed* version that was waiting for approval gets disabled
- unlisted version is untouched and is eventually approved

Expected result:
- *unlisted* version that was waiting for approval gets disabled
- listed version is untouched and is eventually approved

**Comment by diox** [comment]
So we should either completely change the `cancel` view to fully support unlisted or remove it for unlisted as it's currently doing more harm than good.

**Comment by diox** [comment]
QA: the "Cancel and Disable Version" functionality should still be present in both channels but it should only affect the channel of the version that was just submitted.

**Comment by AlexandraMoga** [comment]
@diox I don't think "Cancel and Disable Version" works as expected for listed submissions if you follow these steps:

1. Submit a new listed add-on
2. Click on "Cancel and Disable Version" in the Source code upload page

Results: you land on the [submission/detail](https://addons-dev.allizom.org/en-US/developers/addon/devhub-listed-ext-05133/submit/details) form
Expected: you land on the Manage versions page where the version status is Disabled by Mozilla

**Comment by diox** [comment]
Wow, that's weird...

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage for the following scenarios:

- uploading a listed add-on and selecting "Cancel and Disable Version" in the Source code upload page => user lands on the Manage versions page where the version status is "Disabled by Mozilla"
- uploading a listed add-on and selecting "Cancel and Disable Version" in the submission detail form => user lands on the Manage versions page where the version status is "Disabled by Mozilla"
- uploading an unlisted add-on and selecting "Cancel and Disable Version" in the Source code upload page => user lands on the Manage versions page where the version status is "Disabled by Mozilla"
- uploading a new listed add-on, completing the submission process and confirming that the version is "Awaiting review"; immediately submit a new unlisted version and select "Cancel and Disable Version" in the Source code upload page => user lands on the Manage versions page where the _unlisted_ version status is "Disabled by Mozilla"
- uploading a new unlisted add-on, completing the submission process and confirming that the version is "Awaiting review"; immediately submit a new listed version and select "Cancel and Disable Version" in the Source code upload page => user lands on the Manage versions page where the _listed_ version status is "Disabled by Mozilla"

This issue can be marked as verified fixed.
