### ISSUE TITLE
Allow unlisted auto-approval to be manually disabled

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16560]
Reviewers can manually disable listed auto-approval for any add-on in the reviewer tools.

It would be helpful for admins if there was a separate option for disabling unlisted auto-approval per add-on as well.

**Comment by AlexandraMoga** [comment]
I've verified the new Disable/Enable Unlisted auto-approval and the existing Disable/Enable Listed auto-approval on stage and these are my results:

- Disabling Unlisted auto-approval will block auto-approval for new unlisted version submissions; listed version submissions for the same add-on will be auto-approved as usual
- Disabling Listed auto-approval will block auto-approval for new listed version submissions; unlisted version submissions for the same add-on will be auto-approved as usual
- if Unlisted auto-approval is enabled back, all the versions that were Awaiting review will be auto-approved
- the Disable Listed Auto-Approval Until Next Manual Approval button is also working as before

![image](https://user-images.githubusercontent.com/31961530/112321598-d75d0200-8cb8-11eb-991e-127bcf65d2eb.png)

**Comment by wagnerand** [comment]
@diox Hm, could that button be yellow, like the listed one?

**Comment by AlexandraMoga** [comment]
I've also noticed the difference in color, but then I thought this would better distinguish it from the listed Disable button, to avoid an accidental misuse. 

If the color symmetry makes more sense, then I have nothing against that.
