### ISSUE TITLE
Change homepage shelf api response to use similar CTA style object

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16575]
https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#homepage-shelves returns `footer_text` and `footer_pathname`
```
results[].footer_text (string|null) – The optional text in the footer of the shelf.
results[].footer_pathname (string|null) – The optional pathname of the URL for the footer’s text.
```
Which are really pretty similar to the `cta` object returned in the secondary hero shelf (and modules).  For code reuse (both in addons-server and addons-frontend) lets change the homepage shelf response to be
```
results[].footer (object|null) – The optional footer link and text for the shelf.
results[].footer.url (string) – The url the call to action would link to.
results[].footer.outgoing (string) – url wrapped with outgoing (See Outgoing Links)
results[].footer.text (object|null) – The call to action text. 
```
(bonus outgoingifying if we ever want to allow external linking)

cc @bobsilverberg @xlisachan

**Comment by bobsilverberg** [comment]
That sounds like a good idea to me!

**Comment by bobsilverberg** [comment]
@xlisachan Thanks for jumping on this issue and opening a PR. It was actually Andrew's intention to work on this himself, and he'd be happy to do so, and then you can focus on the frontend stuff. Are you happy to let him take it on, or would you prefer to continue to work on the PR? If the latter, Andrew has a number of suggestions for changes to the approach. Please let us know!

**Comment by xlisachan** [comment]
Not a problem! I'll focus on the frontend stuff :) Thanks for the update!

**Comment by ioanarusiczki** [comment]
@eviljeff 
I tested using a translated string such as "They add features to Firefox to make browsing faster, safer, or just plain fun." for footer "text" and adding an internal/external url into the [Footer pathname](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/55/change/) field.

On dev, "footer" is returned as an object with "url", "text" and "outgoing".
