### ISSUE TITLE
Return the default language in the API response for the primary hero description field

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16576]
Followup for https://github.com/mozilla/addons-server/issues/16515#issuecomment-781256926

I used for testing sample addon "id":7560, with "fr" set as default language.
The primary "description" field with a custom description set in the admin:

Actual result:
for v4,v5 API when lang is not specified or invalid, unsupported - the response returns the description admin field for en-US. 

Expected result:
the response should return the default language `fr`.  (because there is a custom description in `fr` available)

**Comment by eviljeff** [comment]
well, in #16515 I said it was implemented that way purpose because that's what I thought @bobsilverberg wanted 😃 

He can confirm and/or wontfix this as appropriate.

**Comment by ioanarusiczki** [comment]
@eviljeff Sorry, I understood that he would prefer it this way.
@bobsilverberg If it's a won't fix please add the label. 
Thanks!
