### ISSUE TITLE
Update `jszip` (js dep)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16577]
For QA: please verify that the static theme wizard works. This dependency is related to the ZIP export feature (if that is a thing?)

**Comment by willdurand** [comment]
fixed by #16521

**Comment by ioanarusiczki** [comment]
@willdurand I verified on AMO dev and I did not see issues.
- I could use the theme wizard and create new themes and versions. 
- I could install the submitted themes.
