### ISSUE TITLE
Can't submit OpenSearch plugin (502 Bad Gateway)

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1659]
STR:
1) Submit a new add-on (I tried on -dev: https://addons-dev.allizom.org/en-US/developers/addon/submit/)
2) Upload XML file located here: https://www.sendspace.com/file/oy2qr4
3) The validation finishes correctly. Click on Continue.

Observed:
Long wait until a 502 Bad Gateway error page appears.

Expected:
Edit page should appear to add add-on details.

**Comment by andymckay** [comment]
Is this a problem that's occuring on prod and is reproducible on dev? A 502 is a gateway error and occurs when we are deploying. That happens a lot on dev.

**Comment by andymckay** [comment]
Ah its a different problem, i'm getting this on stage as well with that file.

POST 
https://addons.allizom.org/en-US/developers/addon/submit/2 [HTTP/1.1 504 GATEWAY_TIMEOUT 119345ms]

**Comment by EnTeQuAk** [comment]
We're deploying something on stage to fix #1653 and I feel like this could be related. Let's see.

**Comment by EnTeQuAk** [comment]
This is unrelated to #1653, it appears that the problem was introduced by 0f72414f7 (stop blacklisting guids and allow developers to re-use their GUIDs bug 1200777) and here's a traceback from @andymckay that shows the traceback where the timeout might happen (this is locally but on dev/stage the `52` probably turns into quite a high number that get's queried)

**Comment by ValentinaPC** [comment]
Verified on AMO-stage using the attached xml and worked for me as expected - > 
![searchtool-stage] (https://cloud.githubusercontent.com/assets/15685960/13740603/61b0e4c6-e9da-11e5-9e78-9edf588be1fc.png)

Verified on AMO-dev using the same xml and was hanging at validation (for 1-2 minutes), but after that... was successfully submitted. ( ![dev](https://cloud.githubusercontent.com/assets/15685960/13740769/1bf36b1a-e9db-11e5-949a-7d322229c1f1.png)

Attaching the used xml.
[firefox_add_ons-20130124.zip](https://github.com/mozilla/addons-server/files/171680/firefox_add_ons-20130124.zip)

I guess I can mark this verified.
