### ISSUE TITLE
Error when running `category_totals` CRON task

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16591]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

- run `make initialize`

### What happened?

An error is thrown near the end (assuming #16589 is fixed):

```
[...]
django.db.utils.ProgrammingError: (1146, "Table 'olympia.categories' doesn't exist")
```
### What did you expect to happen?

No error.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I see we deleted the `Category` model so maybe that's related.

**Comment by diox** [comment]
Per discussion on Matrix: we should remove `category_totals` code and reference from the crontab entirely.
