### ISSUE TITLE
Don't try to insert empty guids in DeniedGuid

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16602]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/10662093/?query=is%3Aunresolved

Note that there are 2 paths from `delete_addons` task:
- The first one is when `with_deleted` is `True`, we do a hard-delete. In that case, we exclude `guid=None` before doing a `bulk_create` of `DeniedGuid`s. That one should be fine.
- The second one is when we soft-delete. It's just a loop calling `addon.delete()`, which in turn calls `deny_resubmission()`. This method doesn't check that the `guid` is `None`, because it's a little surprising, but I guess we have some weird data floating around...

**Comment by diox** [comment]
QA:
- Get an add-on disabled and somehow ensure it has an empty `guid` (might require help from someone with shell access)
- Delete that add-on
- Ensure the add-on is soft-deleted properly

**Comment by AlexandraMoga** [comment]
@diox I couldn't find a way to set-up add-ons with empty guids, not even from admin. Can you please delete the guids for these addons: 620419, 620421?

**Comment by diox** [comment]
Yeah, we have some old add-ons in the prod db in that state, but it shouldn't possible for new add-ons to do that. I've updated those 2 add-ons on dev.

**Comment by AlexandraMoga** [comment]
I've deleted the add-ons from DevHub and their status visible in Admin and Reviewer tools is 'Deleted'. 

![image](https://user-images.githubusercontent.com/31961530/109020004-392e4a00-76c2-11eb-8ebc-c0ca53d231b4.png)
