### ISSUE TITLE
Email address field is not correctly aligned on Android

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1661]
Prerequisites:
Android device(Used a Nexus 5, Android 6.1)

Steps to reproduce:
1.On your Android device's FF browser, go to MP Stage
2.Open an app to its detail page, where login link is displayed
3.Observe email address and password fields

Expected results:
Both fields are displayed alligned and with the same size

Actual results:
Email address field is not displayed as expected

Please see screencast for this bug : http://screencast.com/t/gywbYFxJngRm

NOTES:
Reproducible on MP-dev

**Comment by adarshrnair** [comment]
I think it is Android 6.0.1

**Comment by EnTeQuAk** [comment]
We're going to reimplement quite a few things also mobile first in the near future with the new addons-frontend so I'm going to close this as wontfix since it will be shiny in the future anyway and might not be worth the effort fixing.
