### ISSUE TITLE
Extensions without ratings are returned among the first results when sorting by top rated

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16622]
### Describe the problem and steps to reproduce it:
1. Send the following request: https://addons-dev.allizom.org/api/v5/addons/search/?type=extension&sort=rating
2. Check the first items returned in the list

### What happened?
Extensions without any ratings are returned among the first results. This is because those extensions still have a `bayesian_average` attributed to them:

```
         "ratings": {
                "average": 0.0,
                "bayesian_average": 4.8951897621154785,
                "count": 0,
                "text_count": 0
```

### What did you expect to happen?
Extensions without ratings shouldn't be available on the first page of results

### Anything else we should know?
- the affected extensions used to have legacy files which have been hard deleted in the meantime. The `bayesian_average` comes from those deleted versions I believe and it should be cleared as well.
- this issue can be easily spotted on -dev and stage, but I'm not sure how this might impact prod

**Comment by diox** [comment]
It looks like this is just in ES - the `bayesian_average` is correctly set to 0 in the database.

**Comment by diox** [comment]
I reindexed dev & stage to fix this. We'll reindex prod shortly.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev and stage.
