### ISSUE TITLE
Store IP address for submissions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16636]
At the moment, we store the IP address for submissions temporarily. For security reasons, it should be attached to the submission permanently.

The same clearing rules that apply for other IP address retaining should apply here as well.

This was approved by the Mozilla Legal and Privacy teams.

**Comment by diox** [comment]
QA: at the moment there is no UI exposing this, but you can create a bunch of versions from different scenarios (devhub, api, new add-on, new version of an add-on, etc) and I can check later that it was stored properly.

**Comment by AlexandraMoga** [comment]
@diox I've submitted a few add-ons using different scenarios and tracked the test data [here](https://docs.google.com/spreadsheets/d/10FuXGyTG0-kZdH7rUdaswM1kZ2tmj9OiIRybyfCdkrk/edit?usp=sharing). Please have a look and let me know if you need more info.

**Comment by diox** [comment]
I've verified that the IP in the spreadsheet match the values in the db (added another column in the spreadsheet for posterity :)
