### ISSUE TITLE
stop generating and cleanup additional theme preview sizes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16638]
we started generating a 720 wide theme preview in 2018 (#9419), but continued to generate other sizes because addons-frontend was still using them.  mozilla/addons-frontend#6507 made the change in addons-frontend in early 2019 but we never cleaned up addons-server so we're still generating 3 sizes (`header`=680w, `list`=760w, `single`=720w)

We should stop doing that and delete the extra previews.

**Comment by eviljeff** [comment]
`about:addons` (in-Firefox addon manager) uses 680x92 previews, seemingly deliberately (the css includes a calculation for 680*92).   So we're going to have to keep that size around - `list` size seems still worthy of being deleted though.

**Comment by ioanarusiczki** [comment]
@eviljeff I look around on AMO dev where themes are displayed.

On server side:
- at the final step of the theme submission and on the edit theme page size is 680x92
- the theme review page shows 2 images, one at 680x92 and another one at 720x92. I've noticed that the one at 760x92 is no longer displayed in the theme image section.

On the frontend:
- on the detail page and search results it's 720x92
- homepage, extension tab, user profile and more themes section use a version preview of 501x64

In all cases the image format is .png (as I could see from src="https://addons-dev-cdn.allizom.org/user-media/version-previews/thumbs/184/184120.png?modified=1555593193" 

Let me know if there's anything else I can check on. 
Thanks!

**Comment by eviljeff** [comment]
(the format should be JPEG for one of the thumbnails, but this issue is about the overall different rendering sizes so, leaving that potential problem for #16639)

I've just run the cleanup command - there shouldn't be any 760x92 previews referenced in the API response (search or detail) now - and the files should be gone too (but that won't be possible to prove if the API responses are clean as expected).

For our reference, `./manage.py process_addons --task=delete_list_theme_previews` took ~30 minutes on dev to complete.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I verified on dev with some theme ids and search results and I did not find a reference to a 760x92 size into the API responses.

- I 've noticed on AMO dev Homepage into "See more popular themes" an unusual theme preview that looks smaller than the other two themes from this shelf, it's been submitted by me in 2018, the id is 495604 and the generated thumbnail is 200x29. 
I did not find another one in this situation. Also this theme seems to have only a 680x100 size displayed on it's theme review page.

![See more popular themes](https://user-images.githubusercontent.com/33448286/110329335-1b97a380-8025-11eb-9785-6315ca73e2ac.gif)

**Comment by eviljeff** [comment]
>     * I 've noticed on AMO dev Homepage into "See more popular themes" an unusual theme preview that looks smaller than the other two themes from this shelf, it's been submitted by me in 2018, the id is 495604 and the generated thumbnail is 200x29.
>       I did not find another one in this situation. Also this theme seems to have only a 680x100 size displayed on it's theme review page.

that's super weird. I think it must have been something generated during the development of the static themes feature - we've never (to my recollection) purposely generated a 200x29 thumbnail for themes.  The resizing is to do with the hover card functionality for the rating scores.  addons-frontend shouldn't react like that to a misshapen image, imo, but I doubt it's worth fixing if it's just affecting some old test data on dev.
