### ISSUE TITLE
generate smaller thumbnail for theme previews

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16639]
We generate a thumbnail for theme previews of 501w x 65h, but addons_frontend* displays the image at 375w x 48h (-ish - there are a few other places that have different -smaller- sizes because we generally scale the image to the space available in the layout).  If we scaled the thumbnail to 48h there would be file size savings. Bonus would be to generate the thumbnail directly from the svg xml template at a smaller scale so UI elements would be cleanly scaled and look better (and also save file size because less antialiasing means better compression)

*(currently we don't know of any api consumer that displays thumbnails for theme previews, after mozilla/addons-frontend#10095 closes addons_frontend will)

**Comment by diox** [comment]
Note: we can also play with t[he algorithm used for the scaling](https://pillow.readthedocs.io/en/stable/handbook/concepts.html?highlight=linear#filters) to remove the antialiasing, but I don't think it's worth it: we *want* anti-aliasing for the most part, for things like the background.

**Comment by diox** [comment]
Also consider: even at 501x65, but even more at 375 x 48, I'm not sure users would notice the difference between PNG and JPG, but the file size would likely be a lot smaller.

**Comment by eviljeff** [comment]
After starting to play around with this, I'm not sure we want/need to render the thumbnail from the svg directly _and_ save as jpeg rather than png - the only* advantage of rending the svg again is no anti-aliasing, but jpeg (being lossly) will reintroduce the anti-aliasing.

**Comment by diox** [comment]
I would agree we don't necessarily need to start from the SVG directly but it might be worth checking first: would we want to also generate the preview itself in JPG ? Or would that *really* be ugly ? If we generated the preview in JPG then generating the thumbnail from the preview might result in greater loss of details on the thumbnail.

**Comment by eviljeff** [comment]
`rsvg-convert` only outputs in PNG (or other lossless formats) so there will be an interim PNG file anyway

**Comment by ioanarusiczki** [comment]
@eviljeff 
If I check using Inspector a theme from the homepage or extension tab I see:
src="https://addons-dev-cdn.allizom.org/user-media/version-previews/thumbs/184/184164.png?modified=1555593202"
which has a 501x64 dimension. 
The homepage or the themes tab display is ~ 375x48

You said something about changing the thumbnail at 48h, is it alright it's still 501x64?

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff
> If I check using Inspector a theme from the homepage or extension tab I see:
> src="https://addons-dev-cdn.allizom.org/user-media/version-previews/thumbs/184/184164.png?modified=1555593202"
> which has a 501x64 dimension.
> The homepage or the themes tab display is ~ 375x48
> 
> You said something about changing the thumbnail at 48h, is it alright it's still 501x64?

Is this for a new upload or an existing one?  

A new theme should be serving a jpg for the thumbnail, but at full 720x92 size (It was a discussion we had on Slack and I forgot to update it here.)  So, actually, we should be generating a _larger_ thumbnail, but when the browser rescales the jpeg on the page it'd look the same as a smaller png, but at a much smaller filesize.

**Comment by ioanarusiczki** [comment]
@eviljeff The themes recently uploaded such as the [Moon Cat](https://addons-dev.allizom.org/en-US/firefox/addon/the-moon-cat-generated/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured) or [Matte Black](https://addons-dev.allizom.org/en-US/firefox/addon/matte-black-red/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured) are generated on homepage/themes tab from a 720x92 size .jpg file 

https://addons-dev-cdn.allizom.org/user-media/version-previews/thumbs/279/279749.jpg?modified=1615203207
https://addons-dev-cdn.allizom.org/user-media/version-previews/thumbs/279/279747.jpg?modified=1614952935

which is the expected.
