### ISSUE TITLE
Static. Permission denied

### ISSUE THREAD

**Issue by ihaskin76** [mozilla/addons-server#16641]
Hi there!
After running the command "[root@localhost addons-server]# make initialize", I get the error:

for dest in @claviska/jquery-minicolors/jquery.minicolors.css @claviska/jquery-minicolors/jquery.minicolors.png  ; do cp /deps/node_modules/$dest static/css/node_lib/ ; done
cp: cannot create regular file 'static/css/node_lib/jquery.minicolors.css': Permission denied
cp: cannot create regular file 'static/css/node_lib/jquery.minicolors.png': Permission denied
make: *** [Makefile-docker:127: copy_node_js] Error 1

![Снимок](https://user-images.githubusercontent.com/65661705/109329456-a3362300-786b-11eb-9ff5-c9dba4de5f4c.PNG)

**Comment by eviljeff** [comment]
it's difficult to debug via github issue.  Come speak to use on https://chat.mozilla.org/ (Matrix) in the AMO room
