### ISSUE TITLE
Update links on legacy DevHub

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#16649]
Splitting out parts of #16265 into a new issue. :) 

The header in the legacy DevHub currently looks like this: 
![image](https://user-images.githubusercontent.com/23342476/109540102-e7494380-7a76-11eb-87d0-749b84b1d6f8.png)

The following updates need to be made: 

* Extension Development should link to https://extensionworkshop.com/documentation/develop?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link
* Themes should link to https://extensionworkshop.com/documentation/themes/develop?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link
* Developer Policies should link to https://extensionworkshop.com/documentation/publish/add-on-policies?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by Mitrajit** [comment]
I think the Themes link  https://extensionworkshop.com/documentation/themes/develop?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link 
should be  
https://extensionworkshop.com/documentation/themes?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link
as I am getting a 404 error.
![image](https://user-images.githubusercontent.com/55190574/109640604-b5b7a180-7b76-11eb-9b0d-aa79d10d15cc.png)

**Comment by caitmuenster** [comment]
Thank you for the catch and correction, @Mitrajit! 🙏 Yes, the updated link target should be https://extensionworkshop.com/documentation/themes?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link.

**Comment by Mitrajit** [comment]
Can I work on this and send a PR? @caitmuenster

**Comment by caitmuenster** [comment]
@Mitrajit Sure! I know you already have another PR for a good-first-issue in the works, so after you submit a PR for this issue, perhaps you'd like to work on something a little more challenging? Those issues are labeled `contrib:welcome.` (In particular, we could use help with [this one](https://github.com/mozilla/addons-server/issues/16379).)

**Comment by Mitrajit** [comment]
@caitmuenster Thanks a lot for guiding. Surely I will check those issues too.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I verified on AMO dev with FF96(Win10): 

The Extension Workshop URL on the left side of Documentation will redirect to
https://extensionworkshop-dev.allizom.org/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=devhub-menu-link -> the utm parameters are present in the address bar.

I can see the utm parameters being present for "Extension Development", "Themes" and "Developer Policies" when I'm hovering over the URLs but when I click to open them -> ?utm parameters are not present in the address bar. Is it ok like this?

**Comment by eviljeff** [comment]
mmm, looks like extensionworkshop has a 301 on `/develop` to `/develop/` (i.e. without the slash to with slash) which loses the utm params.  @caitmuenster do you know if the UTM parameters are still recorded before the redirect?

**Comment by eviljeff** [comment]
actually probably more a question for @muffinresearch as I think it may be an eleventy thing

**Comment by muffinresearch** [comment]
As 11ty is just a static generator it doesn't serve anything itself. All files are built as index.html files in a directory so any URLs for EW should have a trailing slash.

As for why the 301 is dropping the query params I'll need to look into that, it's probably something related to how s3 is serving the content. There might be an option to fix that.

**Comment by eviljeff** [comment]
@Mitrajit would you be able to submit a follow-up patch to add `/` to the urls?
