### ISSUE TITLE
Show the total amount of affected users on the blocklist page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16674]
### Describe the problem and steps to reproduce it:

When blocking several add-ons in bulk, there is a nice list of add-ons involved in the block, along with usage numbers for each.

### What happened?

I can't easily see how many affected users there are in total.

### What did you expect to happen?

That page could also show the total number of users.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand Verified on AMO Dev - FF86(Win10) 

![total of users for bulk blocking](https://user-images.githubusercontent.com/33448286/112137275-bc1ac580-8bd8-11eb-8250-481ecc6c894e.png)
