### ISSUE TITLE
A warning saying that addons are unverified is displayed on Android for verified addons

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1669]
Prerequisites:
Android device,FF Nightly or Release installed

Steps to reproduce:
1.On your device, go to https://addons.allizom.org/
2.Open any verified addon(ie. adblock plus)
3.Try to install it

Expected results:
Addon is installed without any warnings

Actual results:
A warning saying that addons are unverified is displayed

Please see screencast for this bug : http://screencast.com/t/kaG5S5KQ

NOTES:
If you continue the installation ,the addon is correctly installed
Not reproducible on Prod

**Comment by andymckay** [comment]
The flag has been flipped on that signing is required and add-ons have been signed on prod. But not on stage. I think this is expected.
