### ISSUE TITLE
recreate theme preview thumbnails for existing content

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16691]
#16639 will start generating jpeg thumbnails (the thumbnail is actually full size, but should be displayed at half size) so we should do something about the existing themes too.  There's possibly a few existing tasks that can be reused/adapted.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I checked on AMO dev - FF86(Win10):
- the user profile, homepage and themes tab display  theme icons at ~ 356x45, 370x48 which are generated from 720x92 JPEG thumbnails and their quality was set to 35. 

I don't think you ran the task on AMO stage yet. Let me know when.

**Comment by eviljeff** [comment]
I found some flaws that I'll address with #16704 so I won't be running the command on stage until that issue is closed.  Stage can be verified with that issue.
