### ISSUE TITLE
Make sure submission.html and submission.txt templates have the same content

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16693]
### Describe the problem and steps to reproduce it:

In #13561 the [submission.txt](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/emails/submission.txt) template has been updated to include new support links. In #16654 the [submission.html](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/emails/submission.html) template the links have also been updated, but a  line has been removed as well.

The [submission.txt](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/emails/submission.txt) template needs to be updated to match its html version.

**Comment by caitmuenster** [comment]
Need-info'ing myself @caitmuenster.

**Comment by caitmuenster** [comment]
The submission.txt should have this sentence removed:  "If you are interested in getting more involved with Mozilla and want to help keep the add-ons ecosystem safe and healthy, please consider becoming a volunteer add-on reviewer. You can learn more at https://wiki.mozilla.org/Add-ons/Reviewers" 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by anik31** [comment]
Please assign this issue to me @eviljeff

**Comment by AlexandraMoga** [comment]
`submission.html` and `submission.txt` content is now identical.

This issue is verified fixed on -dev.
