### ISSUE TITLE
followup for recreate_theme_previews changes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16704]
#16691 made it so existing theme previews could be resized without fully generating the entire preview, where only the thumbnail size/format was different.  After running the command on dev there are some flaws:

- we don't log.info when we're just doing a resize, making keeping track of the progress difficult in stackdriver
- we don't delete the old .png for the "amo" thumbnail, so wasting disk space
- we don't trigger an elastic search reindex afterwards, meaning a search query would be out of date compared to a database query and serve the old, larger, file (which would 404 if we had actually deleted the .png file - see previous)

**Comment by ioanarusiczki** [comment]
@eviljeff I re-checked on AMO dev the results from https://github.com/mozilla/addons-server/issues/16691#issuecomment-795136651

I did not find issues - icons are displayed on homepage, theme tab or user profile page.

In case there's anything else I could check on AMO dev let me know.

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if you run the task for the .jpg thumbnails on AMO stage.

**Comment by ioanarusiczki** [comment]
@eviljeff 
On AMO stage:
- the user profile page has .jpg thumbnails
- homepage Popular themes shelf has .png thumbnails. I've also noticed .png thumbnails in the Theme tab in Top rated and Trending themes shelves.  (I cannot reproduce this on AMO dev)

![themes with png](https://user-images.githubusercontent.com/33448286/111605459-ffdb8c80-87de-11eb-8261-1b4aaff8de9f.png)

**Comment by eviljeff** [comment]
I looked into this and it appears that some of the addons failed (because I redeployed stage just before I ran the command, and forgot to double-check it was finished, so some tasks got lost/killed during the switchover).  I'm going to run the command again and (🤞) it will work the second time.

**Comment by ioanarusiczki** [comment]
@eviljeff Yes, right now, it looks good on AMO stage too 👍

**Comment by ioanarusiczki** [comment]
@eviljeff I forgot to mention the case of the 2 themes on a shelf. They are larger than they should:

![2 themes on a shelf](https://user-images.githubusercontent.com/33448286/111794058-86bb6280-88ce-11eb-8d48-3ed48633dc6d.png)

or AMO dev right now -> https://addons-dev.allizom.org/en-US/firefox/

that's when it's less than 3 recommended themes - which on prod is not a real scenario - if that should be filed, let me know.

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff I forgot to mention the case of the 2 themes on a shelf. They are larger than they should.
> 
> that's when it's less than 3 recommended themes - which on prod is not a real scenario - if that should be filed, let me know.

oh, yeah, that seems unintentional - can you log a frontend issue to always display at the same width/height
