### ISSUE TITLE
Always return an array in `results` from the `shelves` endpoint

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#16701]
It is currently possible for the [`shelves` endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html) to return `null` for `results`. This happens when invalid data is present for the `endpoint`. The frontend doesn't really need to know this, and the code is simpler in the frontend if `results` is always an array, so this issue is about changing the default so that `results` is an empty array if there is an issue generating the shelf data, rather than a `null`.

Also note that the docs should be updated to indicate that both `primary` and `secondary` can be `null`.

**Comment by adityaofficial10** [comment]
@bobsilverberg 
Can I work on this issue?

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> Can I work on this issue?

@adityaofficial10 This is something that needs to be addressed within the next week or so, so if you think you can commit to getting it done in that timeframe, then please feel free to do so.

**Comment by adityaofficial10** [comment]
@bobsilverberg 
Sure, I'll abide by the timeframe.
I just have to ensure that it returns empty array instead of null.Right?

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> Sure, I'll abide by the timeframe.
> I just have to ensure that it returns empty array instead of null.Right?

Correct.

**Comment by ioanarusiczki** [comment]
@eviljeff I sent some API requests for https://addons.allizom.org/api/v5/shelves/
- for a random-tag shelf or a collection I could see "addons": [] when there are no results, so it's not "null" which proves that there's always a list returned.
- primary and secondary hero shelves always return at least one result - I could not disable all results using the admin.

Verified on AMO dev with Postman.
