### ISSUE TITLE
Create a mobile edit account view

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1671]
We should enable a mobile view for the edit account page. New users will land on this page and it isn't mobile optimized. Once the mobile page exists we should update the username in the header to link to the edit account page.

![Not too nice...](https://cloud.githubusercontent.com/assets/211578/12983642/be151cbc-d0af-11e5-8af0-168af697d96c.png)

**Comment by andymckay** [comment]
I think should be part of the redesign which should be responsive instead of having a completely seperate mobile flow.

**Comment by muffinresearch** [comment]
Going to close this as it will be handled by the new amo mobile pages.
