### ISSUE TITLE
DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16711]
The following `DeprecationWarning` is thrown when you start addons-server:
```
DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release
```
This is because we import `defusedxml.lxml` in [`src/olympia/lib/safe_lxml_etree.py`](https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/safe_lxml_etree.py) which triggers the deprecation notice because of https://github.com/tiran/defusedxml/issues/38.

Need to find out if we can remove the `defusedxml.lxml` import to get rid of that `DeprecationWarning` and what should we do about it. A couple pointers:
- In `safe_lxml_etree.py` (which is imported from [`src/olympia/lib/safe_xml.py`](https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/safe_xml.py), which is imported in `src/olympia/__init__.py` to hopefully quite early) we already provide a patched `XMLParser` where the default is not to resolve entities. But would that be active when using `fromstring()` as well if we didn't have `defusedxml` monkeypatch ?
- Beside tests, we only really use `lxml` via `fromstring()` in [`src/olympia/versions/utils.py`'](https://github.com/mozilla/addons-server/blob/master/src/olympia/versions/utils.py)s `encode_header()` function to find the `width` and `height` of SVG backgrounds in static themes. Maybe it can all be replaced by something else, although even if we did that we'd need to be careful to stay protected in the future if we introduce more stuff depending on XML parsing later

**Comment by eviljeff** [comment]
also, #16697 bump if we're doing this soon-ish

**Comment by eviljeff** [comment]
fwiw, I just used the lxml parser to get the svg width/height because it was already in use at the time within the codebase - it could probably be switched out for something much simpler (it only needs the 2 integer values so there's not really much risk there)

Other than that, is XML parsing still used for anything with non-webextension install.rdfs and search plugins gone?

**Comment by diox** [comment]
> Other than that, is XML parsing still used for anything with non-webextension install.rdfs and search plugins gone?

I haven't doubled-check this, but don't we technically still support non-webextensions for mozilla signed extensions ?

Also, behind the scenes, we fetch blog entries to show them in devhub, and that `feedparser.parse()` on the Atom feed

**Comment by eviljeff** [comment]
> I haven't doubled-check this, but don't we technically still support non-webextensions for mozilla signed extensions ?

🤷‍♂️ - we allow admin overrides for some of checks around what you can upload, so it's possible (whether we _should_, this long after xul addons stopped being a thing, is another question)
 
> Also, behind the scenes, we fetch blog entries to show them in devhub, and that `feedparser.parse()` on the Atom feed

Maybe we can replace that with something json based soon with the new blog?

**Comment by diox** [comment]
> Maybe we can replace that with something json based soon with the new blog?

We could do this now, in fact - the Rest API is currently active with no authentication for read-only purposes: https://blog.mozilla.org/addons/wp-json/wp/v2/posts

**Comment by eviljeff** [comment]
filed 3 issues for the remaining (non-test) usage.  I suppose we can remove defusedxml.lxml after they're fixed.
