### ISSUE TITLE
change blog import to use JSON api rather than xml feed

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16724]
spun off #16711 

>>> Also, behind the scenes, we fetch blog entries to show them in devhub, and that feedparser.parse() on the Atom feed

> >Maybe we can replace that with something json based soon with the new blog?

> We could do this now, in fact - the Rest API is currently active with no authentication for read-only purposes: https://blog.mozilla.org/addons/wp-json/wp/v2/posts

**Comment by AlexandraMoga** [comment]
@eviljeff does this issue refer to the Mozilla Add-ons Community Blog imports we use in DevHub in various places? If that is the case, those links and sections are still working as before.

An example:
![image](https://user-images.githubusercontent.com/31961530/129574018-88b65107-8e56-4bb8-a7d3-cbcf68ff28a6.png)

**Comment by eviljeff** [comment]
@AlexandraMoga it does.
