### ISSUE TITLE
Remove support for parsing install.rdf

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16726]
spun off #16711 

We currently have support for parsing install.rdf - rdf is a type of xml - but install.rdf was a thing for legacy xul addons, and we've removed all them.  If we remove support it will be impossible for AMO to parse an upload without a manifest.json, effectively making it impossible (admin overrides or not) for a non-webextension add-on to be uploaded.  

The upside is we get to remove a lot of old code (including an xml parser that relies on a deprecated library to be safe - see #16711)

@jvillalobos to give the [👍 on the fate](https://www.thevintagenews.com/2016/08/03/ancient-rome-thumbs-up-thumbs-down-meant-the-opposite-of-what-many-think/) of this elderly feature

**Comment by jvillalobos** [comment]
The last time I recall us uploading a legacy add-on was [2 years ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1552218) during Armagadd-on. It wasn't that long ago, but those old versions of Firefox should be much rarer now and there's no possibility of another one of those for a few years (fingers crossed).

I think it's okay to move forward with this and remove support for install.rdf

**Comment by eviljeff** [comment]
QA: there shouldn't be any practical changes*, because we've not allowed legacy add-ons to be uploaded in years anyway.  Please check uploads of non-legacy add-ons work as expected.  

* one minor difference is if someone tries to upload a legacy add-on then the error message will be a generic "can't find the manifest.json" type of error, rather than specifically recognising they're trying to upload an add-on with an install.rdf and saying it's unsupported.

**Comment by AlexandraMoga** [comment]
I've verified add-on uploads and validation results on -dev and I didn't find issues. 

With regards to validation results for legacy add-on uploads, the error message received on dev is:
![image](https://user-images.githubusercontent.com/31961530/125467088-c693e8a6-78d7-4c27-b177-e2cafe22f9c2.png)

Previously, the message for legacy add-on submissions was:
![image](https://user-images.githubusercontent.com/31961530/125467175-3fdf2f5a-4f62-4437-beb2-e5d83f7888d8.png)
