### ISSUE TITLE
Add IP throttling to Ratings and Abuse Reports

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16722]
We already rate-limit ratings and abuse reports per user (which falls back to IP for non-identified requests), we decided in https://bugzilla.mozilla.org/show_bug.cgi?id=1502206 to apply the same limit (1 / minute for ratings, 20 / day for abuse reports) per IP as well.

**Comment by AlexandraMoga** [comment]
I've verified the user and API throttling for the ratings and abuse report APIs and these are my results:

- abuse reports:
  - unauthenticated requests => API IP throttling after 20 subsequent requests
  - User1 submits an authenticated request from the same IP => requests are throttled (IP is restricted for 24h)
  - User1 submits an authenticated request from a different IP => request is posted successfully 
  - User1 continues to submit 20 subsequent requests => requests are throttled (User1 is restricted for 24h)
  - User1 tries to submit requests from a  different IP => requests are throttled (User1 is restricted for 24h)
 - ratings:
   -  User1 posts a rating then immediately posts another => request is throttled for 60s (user restriction)
   - User2 posts a rating from the same IP address as User1 => request is throttled  (IP restriction)
   - User2 posts a rating from a different  IP address => review is posted successfully
  
@diox I found the following behavior when testing the ratings API throttling:
1. User1 posts a rating
2. From the same IP, User2 posts a rating => request is IP throttled
3. User2 waits for the throttling (i.e. the remaining seconds mentioned in the error message) to expire and posts the rating again => request is still throttled, but this time the restriction is for the user, not the IP, I think
4. User2  waits for the throttling to expire and tries to post the rating again => request is still throttled, this time the IP throttling hits again?

The point I'm trying to make here is, if  users calculate the remaining throttling time based on the seconds displayed in the error message, they risk being stuck in a IP/user throttling loop

![g27Cf9jkeo](https://user-images.githubusercontent.com/31961530/111449828-6e094c00-8718-11eb-9ef2-eabf6a2d9d39.gif)

**Comment by diox** [comment]
I think this is fine as an edge-case, this is why I never liked exposing the delay... Each throttle is independent, they don't see the failure from the other(s). 

Note: we never did https://github.com/mozilla/addons-server/issues/11393 so the possibility of being stuck forever is a bit limited, but it's still possible if being restricted by a different throttle every time.
