### ISSUE TITLE
Extension Workshop URLS must end with a trailing slash to not lose query params

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#16744]
Related to https://github.com/mozilla/extension-workshop/issues/935 and https://github.com/mozilla/addons-server/issues/16649 

Query params are being lost in the redirection to add a slash. Since there doesn't appear to be a way to fix the redirection on s3, for now our best mitigation will be to ensure all extension workshop URLS have a trailing slash to avoid the redirection.

To fix this we'll need to search for extension workshop urls and update accordingly.

Here's a [repo search](https://github.com/mozilla/addons-server/search?q=extensionworkshop.com), but a code search locally should also be checked.

**Comment by eviljeff** [comment]
From a local search, it's looks like it's just the devhub links from #16649 that were added without the trailing slash:
```
olympia • src\olympia\devhub\templates\devhub\nav.html:
  36        <ul>
  37:         <li><a href="https://extensionworkshop.com/documentation/develop?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link">
  38            {{ _('Extension Development') }}</a></li>
  39:         <li><a href="https://extensionworkshop.com/documentation/themes?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link">
  40            {{ _('Themes') }}</a></li>
  41:         <li><a href="https://extensionworkshop.com/documentation/publish/add-on-policies?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=dev-hub-legacy-menu-link">
  42            {{ _('Developer Policies') }}</a></li>
```

We also have an `EXTENSION_WORKSHOP_URL` setting (I just checked and all the use with that setting ends in a `/` already) - it'd be more consistent if those links above were changed to use the setting, imo.

**Comment by eviljeff** [comment]
Also logged #16752 for the urls without UTM params currently

**Comment by championshuttler** [comment]
@siddhi523 looks interesting?

**Comment by siddhi523** [comment]
I will try this thanks @championshuttler

**Comment by caitmuenster** [comment]
To fix this issue, a `/` needs to be added before the `?` mark in the URL. 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

@siddhi523, would you be interested in fixing this? :)

**Comment by siddhi523** [comment]
Thanks @caitmuenster I got engaged with some other issues, On it!!

**Comment by AlexandraMoga** [comment]
UTM parameters are now preserved when navigating to Extension Workshop from the Documentation menu in the legacy DevHub:

![lqw4UMomwP](https://user-images.githubusercontent.com/31961530/115232673-ad63f780-a11f-11eb-9f7f-0fedd579beeb.gif)

This issue is verified fixed on -dev.
