### ISSUE TITLE
The 'Forced disabled/enabled' link in Add-on review log redirects to the unlisted review page for all add-ons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16743]
Follow up for #16637 

### Describe the problem and steps to reproduce it:
1. Log in with an Admin reviewer
2. Open the review page for a listed add-on 
3. Force-disable the add-on
4. Open the Add-on review log and look for the Forced-disable action recorded there
5. Click on the 'Force disabled' link in the Event description 

### What happened?
You land on the add-on unlisted review page

### What did you expect to happen?
You should land on the add-on listed review page

### Anything else we should know?
- reviewers that do not have Review:Unlisted permissions will not see the Force disable/enable action in the Add-on review log because of this issue
- the same applies to the Force enable link 

Add-on used in this example:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/webext-test-1ab1c1

![9HmItyOT7p](https://user-images.githubusercontent.com/31961530/111162802-29a96f00-85a5-11eb-9bb6-5ff90f03ce09.gif)

**Comment by diox** [comment]
In the review log, when rendering the link for an action that didn't affect a version, we default to unlisted. Force disable/enable are such actions: they affect the entire add-on, no version is recorded, so we don't know which channel to use an default to unlisted.

I don't see a good reason to continue to default to unlisted in review log. Defaulting to listed makes a lot more sense to me. Thoughts, @wagnerand ?

**Comment by wagnerand** [comment]
Redirecting to listed sounds ok to me.

**Comment by wagnerand** [comment]
> reviewers that do not have Review:Unlisted permissions will not see the Force disable/enable action in the Add-on review log because of this issue

That is a bit surprising though. I'd expect to also see the link if you have `ReviewerTools:ViewUnlisted`.

**Comment by diox** [comment]
That's also something to address in this issue: on top of the link, if you don't have unlisted review permission, the only actions the review log will show you are actions attached to a version. These actions aren't attached to a version and are therefore excluded.

This made sense to be consistent with the way the link is handled, but I'll revisit this logic as well when inverting the behavior for the link. (I'll double-check all possible actions to see why we did this...)

**Comment by AlexandraMoga** [comment]
I've verified this on stage and these are my results:

- the links for Force disable/enable actions are now redirecting strictly to the listed add-on review page, both for listed and pure unlisted add-ons
- the other links present in the review log (like Approved, Rejected, Commented) are redirecting to the corresponding add-on review page (listed, if the add-on is public and unlisted if the add-on is self distributed)
- in order to be able to open a 'Force disable/enable' link for a pure unlisted add-on, users with primarily listed review permissions (`Addons:Review`, `Addons:ContentReview`) also need to have `Addons:ReviewUnlisted` or at least `ReviewerTools:ViewUnlisted` permissions

@diox with regards to the following comment:

> That's also something to address in this issue: on top of the link, if you don't have unlisted review permission, the only actions the review log will show you are actions attached to a version. These actions aren't attached to a version and are therefore excluded.

A user that has only listed review permissions (`Addons:Review`, `Addons:ContentReview`) will be able to see a Force disable/enable event pertaining to a purely unlisted add-on in the review log. However, if they click on the link, they'll see a 404 page. From your comment, I understood that this event should not be visible at all (since it isn't attached to aversion), unless the reviewer also has some unlisted review permissions.

**Comment by diox** [comment]
I purposely fixed it, making those actions visible, but yes, as you pointed out, for a purely unlisted add-on someone without unlisted review permission will get a 404. Can't do much about that without making additional queries which I'd like to avoid, so I think this is fine.
