### ISSUE TITLE
Remove the platform field from the Files model

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16740]
Once https://github.com/mozilla/addons-server/issues/16466 is done we can remove the `platform` field from the `Files` model. Then, in a follow-up push, remove the column entirely when closing https://github.com/mozilla/addons-server/issues/16448

**Comment by diox** [comment]
Note: double-check `landfill` code still works after this.

**Comment by diox** [comment]
Maybe it would also be a good occasion to replace any code looping over `<Version>.all_files` or `<Version>.files` with `<Version>.current_file`, since we've removed the ability for a version to have multiple files.

**Comment by diox** [comment]
> Maybe it would also be a good occasion to replace any code looping over `<Version>.all_files` or `<Version>.files` with `<Version>.current_file`, since we've removed the ability for a version to have multiple files.

I ended up not doing that because the patch was already pretty big.

**Comment by diox** [comment]
QA: this should be a transparent change. Please perform a quick sanity check around uploads and review page.

**Comment by AlexandraMoga** [comment]
I've verified add-on and version uploads and I did  not find issues. I've also checked the Reviewer Tools (queues, review pages, logs) and didn't find regressions.

I'm marking this issue as verified fixed on stage.
