### ISSUE TITLE
Can't get to Step 2

### ISSUE THREAD

**Issue by wbt** [mozilla/addons-server#1675]
When trying to upload a new add-on, I usually get past Step 1: Upload file.  I see the message "**Your add-on was validated with no errors or warnings.** Your submission will be automatically signed."  I then click Continue.  The page loading icon spins, counterclockwise, for a few minutes before loading either a completely white page (no content, no source) or less often a 502 Bad Gateway with the following source:
```
     <html>
     <head><title>502 Bad Gateway</title></head>
     <body bgcolor="white">
     <center><h1>502 Bad Gateway</h1></center>
     <hr><center>nginx</center>
     </body>
     </html>
```
Sometimes it says 500 Internal Server Error instead.

Underneath the "unlisted" checkbox is a note:
_Warning: Submission of unlisted add-ons for signing is currently in an open beta. Please report any bugs that you encounter._ 
"Report any bugs" has a link to this Issues page, so I'm reporting it here.  However, the issue is still observed when the checkbox is deselected.

I observe the same behavior in both Firefox and the latest Chrome, so I don't think this is an issue with my browser.

**Comment by EnTeQuAk** [comment]
This is probably a duplicate of #1659 since you're talking about our live environment I think.

**Comment by andymckay** [comment]
@wbt #1659 refers to a specific kind of add-on, what kind of add-on is yours? Do you have a link to it?

**Comment by wbt** [comment]
I agree, this looks like a dupe of #1659.  Will reopen if the fix for that bug doesn't address this one.
