### ISSUE TITLE
Remove FxA secrets for local development instance and document manually generating secrets

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16757]
Local development instances no longer use FxA auth by default, so we can remove the secrets defined in https://github.com/mozilla/addons-server/blob/de18ebf5c804b8600620206551a36e494c1939fa/settings.py#L99-L122

Additionally, we should add documentation on how to manually create secrets in case a developer needs to test local workflows involving FxA.

@eviljeff Would you mind taking this one, since you seem to have some insights on generating secrets?

Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1649835

**Comment by eviljeff** [comment]
between us last needing the tool on stable.dev.lcip.org to generate our own credentials (2019) and now, the tool was removed by the FXA team https://github.com/mozilla/fxa-dev/pull/508 so the idea of removing the predefined credentials and documenting how anyone on the team can generate new ones themselves as needed seems to be moot now.

If we remove the credentials from the repo we'd need to work with FxA operations to revoke them; and each time anyone needed to work on FxA integration on AMO they'd need to request credentials from the FxA team again (we have no service level agreement with the FxA team to facilitate our requests - i.e. it might take a while and/or require follow-ups if they are busy).

If we go down that route it may be as equally practical to use their staging server instead, which is considerably more stable.

**Comment by eviljeff** [comment]
putting this issue down again because the original plan to document using the self-service tool isn't possible now.

Maybe having the credentials specified elsewhere that's externally private but public within the team (e.g. mana) is a sufficient workaround.

**Comment by eviljeff** [comment]
I guess given the fxa dev environment is semi-permanently broken we may as well drop the hard-coded secrets from the settings files?  Just needs some comments/documentation explaining how to get valid auth credentials for fxa stage if needed.

**Comment by diox** [comment]
Yeah. And then we can rotate out those old credentials.
