### ISSUE TITLE
extensionworkshop.com links without UTM params

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16752]
From searching for #16744 I realised we have a number of links to extensionworkshop.com that don't have any UTM param

@caitmuenster should they be added to all of these?  And if so, can you provide them?
```
olympia • src\olympia\devhub\templates\devhub\agreement.html:
  41  </form>
  42: <p><a href="https://extensionworkshop.com/documentation/publish/developer-accounts/">{{ _('More information on Developer Accounts') }}</a></p>

olympia • src\olympia\lib\crypto\tasks.py:
  44  ---
  45: [1] https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/  # noqa
  46  [2] https://wiki.mozilla.org/Release_Management/Calendar

olympia • src\olympia\devhub\templates\devhub\emails\submission.txt:
   4  
   5: For more information about the review process and policies, please visit https://extensionworkshop.com/documentation/publish/add-on-policies/
   6  

  12  
  13: To learn how to help users discover your extension, stay up-to-date with news from the add-ons community, or contact the add-ons team, please visit https://extensionworkshop.com/documentation/manage/resources-for-publishers/
  14  


olympia • src\olympia\devhub\templates\devhub\addons\submit\describe_minimal.html:
  26              <span class="req">{{ _('Remember') }}</span>:
  27:             {% trans policy_requirements_open='<a href="https://extensionworkshop.com/documentation/publish/source-code-submission/">'|safe, policy_requirements_close='</a>'|safe %}
  28              If you submitted source code, but did not include instructions, you must provide them here.

olympia • src\olympia\devhub\templates\devhub\addons\submit\describe.html:
  222                <span class="req">{{ _('Remember') }}</span>:
  223:               {% trans policy_requirements_open='<a href="https://extensionworkshop.com/documentation/publish/source-code-submission">'|safe, policy_requirements_close='</a>'|safe %}
  224                If you submitted source code, but did not include instructions, you must provide them here.

olympia • src\olympia\devhub\templates\devhub\addons\submit\distribute.html:
  16      <p>{{ distribution_form.channel.errors }}</p>
  17:     <p><a href="https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/"
  18            target="_blank" rel="noopener noreferrer">

olympia • src\olympia\devhub\templates\devhub\addons\submit\source.html:
  19          <p class="list-header">
  20:         {% trans a_attrs = 'href="https://extensionworkshop.com/documentation/publish/source-code-submission/" target="_blank" rel="noopener noreferrer"'|safe %}
  21              Please review the <a {{ a_attrs }}>source code submission policy</a>.

  53          <p class="instruction-emphasis list-header">
  54:         {% trans a_attrs = 'href="https://extensionworkshop.com/documentation/publish/source-code-submission/" target="_blank" rel="noopener noreferrer"'|safe %}
  55              The source code must meet <a {{ a_attrs }}>policy requirements</a>, which includes:

olympia • src\olympia\devhub\templates\devhub\emails\submission.html:
   4  
   5: <p>For more information about the review process and policies, please visit <a href="https://extensionworkshop.com/documentation/publish/add-on-policies/">https://extensionworkshop.com/documentation/publish/add-on-policies/</a>.</p>
   6  

  12  
  13: <p>To learn how to help users discover your extension, stay up-to-date with news from the add-ons community, or contact the add-ons team, please visit <a href="https://extensionworkshop.com/documentation/manage/resources-for-publishers/">https://extensionworkshop.com/documentation/manage/resources-for-publishers/</a>.</p>>
  14  

olympia • src\olympia\devhub\templates\devhub\new-landing\components\banner.html:
  12          </p>
  13:         <a href="{{ settings.EXTENSION_WORKSHOP_URL }}">{{ _('Visit the Extension Workshop') }}</a>
  14        </div>olympia • src\olympia\devhub\templates\devhub\new-landing\components\overview.html:
  10      </p>
  11:     <a href="{{ settings.EXTENSION_WORKSHOP_URL }}" class="Button Button--primary">{{ _('Learn how to make an extension') }}</a>
  12    </div>

olympia • src\olympia\stats\templates\stats\reports\campaigns.html:
  5  {% block stats_note_link %}
  6:   <a href="{{ settings.EXTENSION_WORKSHOP_URL }}/documentation/manage/monitoring-extension-usage-statistics/" target="_blank" rel="noopener noreferrer">
  7      {{ _('About tracking external sources...') }}

olympia • src\olympia\stats\templates\stats\reports\contents.html:
  5  {% block stats_note_link %}
  6:   <a href="{{ settings.EXTENSION_WORKSHOP_URL }}/documentation/manage/monitoring-extension-usage-statistics/" target="_blank" rel="noopener noreferrer">
  7      {{ _('About tracking external sources...') }}

olympia • src\olympia\stats\templates\stats\reports\mediums.html:
  5  {% block stats_note_link %}
  6:   <a href="{{ settings.EXTENSION_WORKSHOP_URL }}/documentation/manage/monitoring-extension-usage-statistics/" target="_blank" rel="noopener noreferrer">
  7      {{ _('About tracking external sources...') }}

olympia • src\olympia\stats\templates\stats\reports\sources.html:
  5  {% block stats_note_link %}
  6:   <a href="{{ settings.EXTENSION_WORKSHOP_URL }}/documentation/manage/monitoring-extension-usage-statistics/" target="_blank" rel="noopener noreferrer">
  7      {{ _('About tracking external sources...') }}
```

Note the mix of `settings.EXTENSION_WORKSHOP_URL` and the literal url.  IMO we should update all the links to use the setting if we're taking the time to make a change.

**Comment by caitmuenster** [comment]
Yes, let's add some UTM params. :) 

**olympia • src\olympia\devhub\templates\devhub\agreement.html:**
?utm_source=addons.mozilla.org&utm_medium=submission&utm_content=more-information/

**olympia • src\olympia\lib\crypto\tasks.py:**
Question for @eviljeff - where do these links show up? wasn't sure if was on page one of the submission flow

**olympia • src\olympia\devhub\templates\devhub\emails\submission.txt:**
I'd prefer to not include a UTM on plain text emails, so I think we can disregard this one. (Let me know if I am wrong!) 

**olympia • src\olympia\devhub\templates\devhub\addons\submit\describe_minimal.html:**
"Please review the source code submission policy. Do you use any of the following? should have the parameters: ?utm_source=addons.mozilla.org&utm_medium=submission&utm_content=source-code-submission-policy/

"The source code must meet policy requirements, which includes:" should have the parameters:
?utm_source-addons.mozilla.org&utm_medium=submission&utm_content=policy-requirements/

**olympia • src\olympia\devhub\templates\devhub\addons\submit\describe.html:**
?utm_source=addons.mozilla.org&utm_medium=submission&utm_content=describe-build-instructions/

**olympia • src\olympia\devhub\templates\devhub\addons\submit\distribute.html:**
I'm not sure where this displays, but the UTM parameters can be: 
?utm_source=addons.mozilla.org&utm_medium=submission/

**olympia • src\olympia\devhub\templates\devhub\emails\submission.html:**
Policies: ?utm_source=email&utm_medium=submission-email/

Resources for publishers: ?utm_source=email&utm_medium=submission-email/

**olympia • src\olympia\devhub\templates\devhub\new-landing\components\banner.html:**
?utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=banner/

**About tracking external sources** 
Let's use the same UTM parameters for the /reports subpages (campaigns, content, medium, sources): 
?utm_source=addons.mozilla.org&utm_medium=stats-dashboard&utm_content=about-tracking-external-sources

_(side note, just want to call out how meta it feels to be adding a UTM parameter to a link that describes UTM parameters...)_

**Comment by eviljeff** [comment]
> **olympia • src\olympia\lib\crypto\tasks.py:**
> Question for @eviljeff - where do these links show up? wasn't sure if was on page one of the submission flow

It's referenced in an email we are/were planning to send when add-ons are bulk-resigned with a new signature
https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/crypto/tasks.py#L26-L52  (I don't know if this email will ever actually be sent, and if we'll ask for the copy to be revised before it is, but it's all set up and ready to go so I included it)

**Comment by caitmuenster** [comment]
Got it. We don't need to add UTM params to that.

**Comment by kanish671** [comment]
@caitmuenster I would like to contribute to this issue. 

I think the below mentioned ones are meant for `src\olympia\devhub\templates\devhub\addons\submit\source.html`
 and not `src\olympia\devhub\templates\devhub\addons\submit\describe_minimal.html`
> olympia • src\olympia\devhub\templates\devhub\addons\submit\describe_minimal.html:
"Please review the source code submission policy. Do you use any of the following? should have the parameters: ?utm_source=addons.mozilla.org&utm_medium=submission&utm_content=source-code-submission-policy
 "The source code must meet policy requirements, which includes:" should have the parameters:
?utm_source-addons.mozilla.org&utm_medium=submission&utm_content=policy-requirements


Also, what UTM params need to be added to links in `src\olympia\devhub\templates\devhub\addons\submit\describe_minimal.html`?

**Comment by caitmuenster** [comment]
Hi @kanish671, I am so sorry for the late response! 

Yes, you've got the right idea about the UTM params for `submit\source.html` 

I don't need anything for `/describe_minimal.html` because I don't see that link in the submission flow based on this screenshot from the AMO-dev environment: 

![Screen Shot 2021-08-02 at 9 32 47 AM](https://user-images.githubusercontent.com/23342476/127894421-b13189ab-e1b1-4267-b0e9-db27392748c7.png)

**Comment by caitmuenster** [comment]
I'm closing this issue because I'm not sure what pieces have been done and what still needs to be fixed. 🙃 I'll open new issues if/when we find UTMs that need to be added.
