### ISSUE TITLE
Broken "Add-ons developers mailing list" link

### ISSUE THREAD

**Issue by tublitzed** [mozilla/addons-server#16750]
### Describe the problem and steps to reproduce it:
Looks like there is a broken link on [this page](https://addons.mozilla.org/en-US/developers/) in the social banner above the footer (titled 'connect with us') - the `Add-ons developers mailing list` links to a list that doesn't exist [here](https://mail.mozilla.org/listinfo/dev-addons).

### What happened?

Dead link. 

### What did you expect to happen?

Working link :)

### Anything else we should know?

![Screen Shot 2021-03-15 at 10 13 31 PM](https://user-images.githubusercontent.com/1756056/111245877-b3742f00-85db-11eb-94d4-96f72f19b1b2.png)

**Comment by sourabhsingh282** [comment]
@caitmuenster @willdurand  can i send PR here? 🙂

**Comment by caitmuenster** [comment]
Welcome @sourabhsingh282! Yes, you can pick this one up. :) If you haven't done so already, be sure you read through our [onboarding documentation](https://wiki.mozilla.org/Add-ons/Contribute/Code#Improve_addons.mozilla.org_.28AMO.29). We'll assign you to this issue once you submit a PR.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg

**Comment by kanish671** [comment]
@caitmuenster can I raise a PR against this if it is still not fixed?

**Comment by caitmuenster** [comment]
Hi @kanish671, go for it!

**Comment by AlexandraMoga** [comment]
This issue is verified fixed  on -dev:

![RFfhnmONf8](https://user-images.githubusercontent.com/31961530/115882445-6cd4e880-a455-11eb-9b6e-7689897036f4.gif)
