### ISSUE TITLE
Use Node 12 in AWS Lambda

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16766]
There is no action in addons-server, this is issue is primarily for QA. Node 12 has been configured on AWS Lambda for -dev and -stage, and I updated the scanners for Node 12 as well (there was no code change involved).

For QA: please verify that the different scanners work on -dev. When submitting a new version, we should have scanner results for all of them. (please don't paste actual results in this issue)

**Comment by ioanarusiczki** [comment]
@willdurand I did not find anything unusual - verified on dev -FF86(Win10). 
The addons submitted for testing today are visible in scanner results - created 2021-03-22.
