### ISSUE TITLE
Show average daily users on django admin add-ons list

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16768]
The django admin add-ons list (`/admin/models/addons/addon/`) should show a column with the average daily users data for each add-on in the list so admins can see easily which add-ons (usually of a particular user, using the `authors` parameter) have the most users.

**Comment by ioanarusiczki** [comment]
@wagnerand The column was added to https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/
I've been using ?authors as parameter to check some data, I see the ADU in `/admin/models/addons/addon/` being available - same number as the [frontend](https://addons-dev.allizom.org/en-US/firefox/search/?sort=users) is displaying for the addons with data imported from prod. 

**Note:** I see numbers with a lot of decimals in the Average Rating column such as 3.4507999420166016
More examples [here ](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?authors=4757633)
Perhaps that can be formatted.

**Comment by wagnerand** [comment]
@ioanarusiczki Yes, we can probably add number formatting in lots of places. It's low priority though. Might make sense to just update it when we touch the code anyway, not sure if it warrants a separate task just for updating the format.

Specifically, for the average rating, it's also not that interesting on the django admin page, so we could potentially just remove that column, but I haven't though further about it yet.
