### ISSUE TITLE
Fix MySQL init error

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#16779]
See the recent Circle CI builds, almost all the jobs fail with the following error:

```
[ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_PASSWORD cannot be used for the root user
```

**Comment by willdurand** [comment]
it's likely https://github.com/docker-library/mysql/pull/749

**Comment by willdurand** [comment]
There is nothing to do, the circle folks have patched their base image in https://github.com/circleci/circleci-images/pull/540, new image versions should be built and published soon...

**Comment by eviljeff** [comment]
I guess this is fixed now?  I restarted all the broken CI builds yesterday.

**Comment by willdurand** [comment]
ah yep, sorry, I forgot to comment. It's fixed by upstream.
