### ISSUE TITLE
Update links on /developers

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#16773]
The following links need to be updated on https://addons.mozilla.org/developers/ : 

<img width="1024" alt="Links to be updated" src="https://user-images.githubusercontent.com/23342476/111544813-4cb55980-8732-11eb-8151-8fe5b73d394f.png">

"Documentation" should be: https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions?utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=header _(note: our section of MDN is getting re-organized soon, so just a heads up that this might change again in a month or so)_

"Support" should be: https://wiki.mozilla.org/Add-ons#Get_in_touch

"Visit the Extension Workshop" should change to "Visit the Firefox Extension Workshop" and link to https://extensionworkshop.com/?utm_source=addons.mozilla.org&utm_medium=devhub&utm_content=banner

**Comment by NegiAkash890** [comment]
I can fix this!

**Comment by nayaldivya** [comment]
I want to work on this issue.

**Comment by nayaldivya** [comment]
Hey @caitmuenster, Since I'm a beginner in Open Source, I'd like to ask for some help. Can you please hint me which file need the changes. Codebase is so big and confusing to me although I did some research, Is it the templates in devhub directory that need changes? But which one?

**Comment by ioanarusiczki** [comment]
@eviljeff the "Documentation" URL is not passed with the utm parameters on AMO dev.
The rest looks good.

**Comment by eviljeff** [comment]
> @eviljeff the "Documentation" URL is not passed with the utm parameters on AMO dev.

looks like the link is as specified, but MDN does a 302 because the `/locale/` isn't included in the URL.  I don't know how GA is set up on MDN or if we care (and if we're okay with always to linking to the en-US page if we want it changing).  Questions for @caitmuenster who specified the URL 😄

**Comment by caitmuenster** [comment]
Thanks for the heads up. I need to look into GA for MDN, but I'm fine if this doesn't pass the UTM parameter as the link might be changing. (It looks like there's going to be a folder re-org in MDN's future to phase out `/Mozilla/`.)
