### ISSUE TITLE
Developer Policies URL must be replaced to redirect to EW

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16787]
As described on the frontend https://github.com/mozilla/addons-frontend/issues/10223 the old Developer Policies URL from the footer should be replaced with https://extensionworkshop-dev.allizom.org/documentation/publish/add-on-policies/?utm_source=addons.mozilla.org&utm_medium=photon-footer on server side too.

**Comment by eviljeff** [comment]
I think this link is covered in #16753
