### ISSUE TITLE
Problem with donations to addon authors

### ISSUE THREAD

**Issue by Eccenux** [mozilla/addons-server#1679]
Steps:

1. Visit https://addons.mozilla.org/pl/firefox/addon/tab-groups-panorama/
2. Click on the donation button.
3. Choose donation (either default or custom quantity).
4. Click on a donation submit button.

Results:

1. The donation window disappears (the mask element stays).
2. Console shows: Load denied by X-Frame-Options: https://www.paypal.com/us/cgi-bin/webscr?cmd=_dispatch-failed does not permit cross-origin framing

Browser: Firefox 44.0.2.

**Comment by muffinresearch** [comment]
This appears to be intermittent. Sometimes it works sometimes it doesn't. 

Sometimes the iframe created is framing a paypal url with x-frame-options headers that disallows loading of the content in the frame causing this error.

Not sure if this is a temporary issue paypal's end as now I can't seem to reproduce it.

**Comment by Eccenux** [comment]
I can still reproduce this in FF 44, but not in the FF dev.

**Comment by muffinresearch** [comment]
Earlier I could repro in FFdev but not stable. But then FF dev stopped doing it.

**Comment by andymckay** [comment]
This a problem on Paypals code though? We've had this intermittently occur for a while though, for example: https://bugzilla.mozilla.org/show_bug.cgi?id=896653

I think this falls into the bucket of "we need to move away from Paypal", which we've got several bugs on already. Given that there's not a lot we can do about this other than use another service, I'm going to close this and mark it for consideration during the upcoming rewrite.
