### ISSUE TITLE
404 for Report a bug URL from footer - on manage my submission page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16820]
Instead of 404 -> it should redirect to 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us

This is not reproducible on the frontend or dev hub login/logout views. 

this is reproducible for submit a new addon/submit a new theme pages - they have the same footer 

Notes:
reproducible on all AMO servers - FF87(Win10).

**Comment by eviljeff** [comment]
can you include the url that the page shows - that's currently a 404 - for reference?

**Comment by ioanarusiczki** [comment]
@eviljeff Sure, it's https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Contact

**Comment by eviljeff** [comment]
This should be covered by #16753 (it's the photon-footer.html link, iirc, but I searched through and highlighted all the devhub urls so either way is in there)
