### ISSUE TITLE
Accept beta add-ons through the API

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1683]
From https://github.com/mozilla/addons/issues/25:

We need to update [`devhub.tasks.create_version_for_upload`](https://github.com/mozilla/olympia/blob/96b670d3a0be3d1462182f0793d25346bef5bb56/apps/devhub/tasks.py#L101) to pass `is_beta` like in [`devhub.views.version_add`](https://github.com/mozilla/olympia/blob/96b670d3a0be3d1462182f0793d25346bef5bb56/apps/devhub/views.py#L1288).

When uploading through the UI the validation results return whether it [looks like a beta](https://github.com/mozilla/olympia/blob/96b670d3a0be3d1462182f0793d25346bef5bb56/apps/devhub/views.py#L836) and then it provides a checkbox if it looks like one. We could either update the API to accept a  `beta` boolean or do the detection and automatically call it a beta.

Perhaps we could put the beta-ness in the URL and this can start looking like the new proposed listed/unlisted/beta changes but I'm not sure if that makes sense.

**Comment by jvillalobos** [comment]
I'd be in favor of having a boolean flag for beta-ness, rather than automatically detect it, since that detection has been problematic in the past.

**Comment by andymckay** [comment]
An explicit flag means changes to tools like jpm.
