### ISSUE TITLE
Some maliciousness score in reviewer queues differs from the score displayed on the review page or in scanners admin

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#16830]
### Describe the problem and steps to reproduce it:
1. Open the Auto-approved review queue - https://reviewers.addons.allizom.org/en-US/reviewers/queue/auto_approved
2. Check the Maliciousness score for the add-on highlighted in the first screenshot below
3. Check the score displayed on the add-on review page - https://reviewers.addons.allizom.org/en-US/reviewers/review/score_in_revtools (second screenshot)

### What happened?
The review queue reports a score of 99%, while the add-on review page says it's 100%. I've also verified the scanner result for this add-on and the score is 100%.

### What did you expect to happen?
Scanners score should be the same everywhere

### Anything else we should know?
I could not find another example for this issue through the add-ons we currently have on -dev and stage review queues, so I'm not sure if there's something particular about this add-on or if this issue may manifest in other circumstances. I've submitted this add-on several times and I'm always seeing this inconsistency. The score difference is very low, but it would be good to know why it happens. 

[reviewer queue]
![image](https://user-images.githubusercontent.com/31961530/112649963-9baa6f80-8e53-11eb-8b1e-ef15a5d108d8.png)

[add-on review page]
![image](https://user-images.githubusercontent.com/31961530/112650554-2d19e180-8e54-11eb-94da-c2843d415431.png)

**Comment by wagnerand** [comment]
Could this be a rounding error?
