### ISSUE TITLE
switch django-babel to enmerkar

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16839]
https://github.com/python-babel/django-babel appears unmaintained - no commits since 2017 and the owner hasn't responded to any issues/prs since the end of 2017 either.  https://github.com/Zegocover/enmerkar is a fork of django-babel that has testing/fixes for modern django versions.

We currently install cgrebs' fixed fork https://github.com/EnTeQuAk/django-babel/tree/django2-compat

**Comment by diox** [comment]
commits from cgreb's fork as included: https://github.com/python-babel/django-babel/compare/master...Zegocover:master

**Comment by AlexandraMoga** [comment]
@eviljeff is QA required for this issue?
