### ISSUE TITLE
support svgs in --task=create_missing_theme_previews

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16846]
#16755 adds support for generating theme previews in svg format but there are a few places that expect `VersionPreview.image_path` to be always a png - create_missing_theme_previews in particular.  Because that might bite us later we should fix that.  The full fix is fixing the our generic image manipulation function `resize_image` to handle svg -> png/jpg conversion, really.

**Comment by eviljeff** [comment]
QA: 2 things here -
1) is the update to the `create_missing_theme_previews` process_addons task.  I've not run it on -dev yet, so that'll only be verifiable afterwards. (Not sure when I'll execute - I'll update the issue afterwards)
2) more important is there are changes to the `resize_image` function which is used everywhere we resize or reformat images - theme previews, screenshots, etc.  The changes should be entirely backwards compatible.  Because that's going out in the tag please check I didn't break anything with that.

**Comment by ioanarusiczki** [comment]
@eviljeff Right now on AMO dev:
- only the new submitted themes have .svg version preview on the detail page and search results
- I don't see anything broken on pages where themes are present - nothing has changes since I checked and added results for https://github.com/mozilla/addons-server/issues/16755

**Comment by eviljeff** [comment]
I thought about how the code is written and realized it had a flaw, so filed #16920 to address it.  I'll run the task only after that's fixed and _that issue_ can be verified so I don't think there's anything else to verify with this issue.
