### ISSUE TITLE
UI: mismatched API key names

### ISSUE THREAD

**Issue by kousu** [mozilla/addons-server#1685]
https://addons.mozilla.org/en-US/developers/addon/api/key/ has "JWT Issuer" and "JWT secret" while "jpm sign" has "--api-key" and "--api-secret". These should be labelled the same.

**Comment by yash14123** [comment]
A link to the html file please. :)

**Comment by kousu** [comment]
Can't you search? I just did and it looks like the source is https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/api/key.html

But it might be better to change `jpm`, because teeeeechnically speaking it *is* a JSON Web Token pair, not just any old "API" pair. That choice should be up to whoever fixes this.

**Comment by yash14123** [comment]
Sorry I just started understanding the structure of the code so I asked for the html file reference. Next time I will do the searching. I am fixing this issue.

**Comment by kousu** [comment]
Ah, I see the "good first bug" tag. That makes sense then.

Well then yash, I don't know what is best here, so consider it. I just want them to be the same.

You'll also need to get https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm updated (and I don't know how to edit that any better than you do).

Happy hacking!

**Comment by mstriemer** [comment]
It is definitely a little weird that these strings are different. I wonder if it makes sense to update jpm instead though.

@kumar303 what do you think about supporting `--jwt-issuer` and `--jwt-secret` in jpm instead of `--api-key` and `--api-secret`?

**Comment by kumar303** [comment]
I'd rather not change it, here's why.

On the AMO developer hub, we want to make it clear that you are authenticating with a JWT. We use official JWT terminology such as "issuer" and "secret."

In `jpm`, it's interacting with the signing service at a lower level so the details are not so important. It uses generic API access terminology such as "API key" and "API secret". In the future, if AMO decides to switch away from JWT authentication then (hopefully!) it would still make sense in `jpm` to ask for an "API key" and an "API secret."

Thanks for taking the time to submit an issue!

**Comment by crankycoder** [comment]
I think this is worth reopening.  

It's at least confusing enough that I didn't understand what was going on today - so I just guessed.  

Guessing the right thing to do isn't a greate developer experience.

In the near term, the terms "API key" and "API secret" are simply confusing.  There is no alternate access methodology other than using JWT issuer and secret.

Not updating this means that we are trading ease of understanding what to do *today* for our addon developers in exchange for reduced documentation work for Mozilla in the future.  This seems like the wrong choice to me.  

We should update jpm and the documentation over at https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign

**Comment by kousu** [comment]
On March 10, 2016 6:05:36 PM EST, Victor Ng <notifications@github.com> wrote:.
>
>Not updating this means that we are trading ease of understanding what
>to do *today* for our addon developers in exchange for reduced
>documentation work for Mozilla in the future.  This seems like the
>wrong choice to me.  

Thank you. These are my thoughts put eloquently.

**Comment by theaverageguy** [comment]
So what is the final call? Maybe I can do the necessary changes?

**Comment by kumar303** [comment]
The original bug report called to rename JPM's options (or AMO's terminology) which I disagree with -- someone will have to convince me of the value in doing this. The bug report did not mention anything about lacking documentation. What is unclear about either parts of the documentation? The relevant sections are:

* https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign
* http://addons-server.readthedocs.org/en/latest/topics/api/auth.html

Also, both of these docs can be modified by anyone so if you'd like to make changes, please do. The MDN docs are easier to edit because it is a wiki.
