### ISSUE TITLE
Upgrade cssutils

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1686]
Upgrading to cssutils==1.0.1 fixes [bug 1244644](https://bugzilla.mozilla.org/show_bug.cgi?id=1244644), this will need to be tested in the python validator too

**Comment by Mogztter** [comment]
Thanks @andymckay

**Comment by EnTeQuAk** [comment]
amo-validator part in https://github.com/mozilla/amo-validator/pull/393 - once this lands I'll upgrade amo-validator and `cssutils` for olympia too.
