### ISSUE TITLE
Category sorting by most users not working

### ISSUE THREAD

**Issue by tublitzed** [mozilla/addons-server#16872]
### Describe the problem and steps to reproduce it:
I went to [this page](https://addons.mozilla.org/en-US/firefox/extensions/category/social-communication/?sort=recommended%2Cusers) and expected to see the default sort applied (by "most users") - scrolling down the list, I see add-ons like Facebook Container and Grammarly both have 1M+ users and are displayed below items like LastPass (~800k users) and  RoboForm Password Manager (~75k users).

### What happened?
Sorting not working

### What did you expect to happen?
Sorting working :)

### Anything else we should know?
![Screen Shot 2021-04-05 at 10 32 34 AM](https://user-images.githubusercontent.com/1756056/113585793-b40c4e00-95fa-11eb-9f3a-7d00f1b330b8.png)

**Comment by AlexandraMoga** [comment]
Category pages are using a special `?sort=recommended%2Cusers` parameter, which means we are first displaying all the recommended add-ons within the selected category _sorted by users_ followed by all other add-ons from the same category also _sorted  by users_.

The implementation was done in https://github.com/mozilla/addons-frontend/pull/8103

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga! That is correct and this is the expected behaviour. I'm going to close this for now, but please let me know if you have any questions about it, @tublitzed.

**Comment by jvillalobos** [comment]
I think there's a good argument to be made that the Sort label is confusing. If you change the sort to something else and then back to Most Users, the end result will be different than where you started.

Perhaps we should add a Sort option called `Most Users, Recommended First` that is chosen in this case. I'm aware that the special Recommended sorting can be mixed up with all other sort options, but I believe Most Users is the only one we mix it up with on the site, so we can make an exception for it.

**Comment by eviljeff** [comment]
>  If you change the sort to something else and then back to Most Users, the end result will be different than where you started.

I'm not following, can you include STR for this - changing the filters and then changing back shows the same results for me.

> Perhaps we should add a Sort option called `Most Users, Recommended First` that is chosen in this case. I'm aware that the special Recommended sorting can be mixed up with all other sort options, but I believe Most Users is the only one we mix it up with on the site, so we can make an exception for it.

We do recommend first for _all_ the sort by options (like @AlexandraMoga mentions)
