### ISSUE TITLE
Tag webextensions add-ons

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1688]
Somewhere in AMO there is code that detects if an add-on is jetpack and adds in jetpack as reserved tag on the add-on. Well I think that's what I wrote anyway.

Would be nice if we could do the same with webextensions add-ons, over the next 6 months or so as we ramp up webextensions it will give us a nice simple way to find those add-ons.

**Comment by wagnerand** [comment]
Looks like this is being done in `src/olympia/tags/cron.py`. Do you prefer to tag webextensions in the same run as jetpack ones or have a separate cronjob for them?

That cronjob looks disabled though, at least I can't find any reference to it in `scripts/crontab/crontab.tpl`.

**Comment by andymckay** [comment]
I think there's a better way to do this and I'm not sure of the value here to be honest.

**Comment by devaneymoz** [comment]
There's value for Editorial! 

In the short term, we have plans to feature good examples of webextensions to serve as a guiding light to developers and users. The first such collection should appear in early August. 

We'll also want to highlight good webextensions in the blog and on other platforms to keep the momentum and guidance moving along.

Over the long haul, we've discussed that at some point making webextensions a requirement to be featured. Would be great to have a way to easily check.

**Comment by tofumatt** [comment]
We flag things as web extensions already https://github.com/mozilla/addons-server/blob/master/src/olympia/editors/models.py#L98

Not sure if it's propagated to the add-on itself or just the review? But AMO knows when something is a web extension; it needs to know when to use the linter.

**Comment by andymckay** [comment]
The internal search tool should be able to tell you this information (and
that's the place to put it if it's not there), rather than explicitly
tagging things.
