### ISSUE TITLE
Update links in base.ltxt email to developers

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#16888]
The links in the [base.ltxt](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/base.ltxt) file, which is used in some emails, could use updating. 

Get in touch with us using these channels --> https://wiki.mozilla.org/Add-ons#Contact_us

Tips for updating your add-on's listing --> https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/

Learn more about the review process --> https://extensionworkshop.com/documentation/publish/add-on-policies/

**Comment by elyse0** [comment]
Hi, I'll make a PR to fix this!
