### ISSUE TITLE
Quote identifiers (tables and columns) in direct sql queries made by the translations app

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16892]
There might be others elsewhere, but I noticed that the SQL queries the translations app is making (not done through the ORM) aren't fully quoted properly.

https://github.com/mozilla/addons-server/blob/efb5b165bff41ac73f37ce122dd5a43bcc4a540b/src/olympia/translations/models.py#L133-L152

https://github.com/mozilla/addons-server/blob/efb5b165bff41ac73f37ce122dd5a43bcc4a540b/src/olympia/translations/query.py#L70-L78

https://github.com/mozilla/addons-server/blob/efb5b165bff41ac73f37ce122dd5a43bcc4a540b/src/olympia/translations/query.py#L156

https://github.com/mozilla/addons-server/blob/efb5b165bff41ac73f37ce122dd5a43bcc4a540b/src/olympia/translations/transformer.py#L62-L69

**Comment by diox** [comment]
In the case of `translations/query.py`, this actually matches django's behavior of not quoting table aliases. I'm not a big fan for for consistency's sake, I'll follow that because most of the code is lifted from django's ORM.

**Comment by diox** [comment]
QA : check that add-on translations continue to work correctly in devhub / reviewer tools / frontend

**Comment by ioanarusiczki** [comment]
@diox I did encounter problems changing the language - translations are available. 

Verified on AMO stage, FF88(win10).
