### ISSUE TITLE
Add unique database constraint to prevent duplicate versions for a given add-on

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16901]
`version` string should be unique per add-on. We enforce that in code, but we should have a database constraint, when the [task to remove existing duplicates](https://github.com/mozilla/addons-server/issues/14332) has been run in prod.

**Comment by ioanarusiczki** [comment]
@diox Can qa check this issue? Please add some str
Thanks!

**Comment by diox** [comment]
It's difficult to reproduce the issue this fixes - we already had code to prevent duplicate versions from being posted, this just makes it make robust by adding a constraint at the database level.
