### ISSUE TITLE
Include mozilla collections in the sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16908]
follow-up for #16508 

We want to include pages for mozilla collections

**Comment by AlexandraMoga** [comment]
@eviljeff can this be verified individually in any way or should it be covered when testing for #16508 becomes available?

**Comment by eviljeff** [comment]
@AlexandraMoga ops deployed the nginx change so it can be tested now.

**Comment by AlexandraMoga** [comment]
The https://addons-dev.allizom.org/sitemap.xml includes a `?section=collections` which in turn contains all the collections created by mozilla - https://addons-dev.allizom.org/sitemap.xml?section=collections.
