### ISSUE TITLE
Add per- add-on subpages to the sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16907]
follow-up for #16508 

We currently just generate the detail page for each add-on, i.e. `/en-US/firefox/addon/<slug>/` - we probably want to include the privacy policy, license, and eula pages too.

**Comment by AlexandraMoga** [comment]
@eviljeff from what I've noticed, the new per-addon subpages (license, privacy, eula) have been added  in https://addons-dev.allizom.org/sitemap.xml?section=addons&p=2&debug after the individual detail pages. Each subpage is sorted in a descending order based on the last modified date.

Some questions: 
- are these pages supposed to surface in `?section=addons&p=2` or should they have separate sections?
- currently there are only a few subpages returned (privacy - 155, eula - 136, license - 72 after my counting). I don't think I have the means to verify if these numbers are correct. Regarding license though, are we taking into account only the Custom License added from this DevHub form?
![image](https://user-images.githubusercontent.com/31961530/116255335-d10beb00-a77a-11eb-96ad-4713f083fa1c.png)

**Comment by eviljeff** [comment]
> Some questions:
> 
>     * are these pages supposed to surface in `?section=addons&p=2` or should they have separate sections?

at the moment, with the addons section (I re-used the same database query for efficiency... if this turns out to overwhelm the cron job creating it on addons-dev I'll have to refactor).

>     * currently there are only a few subpages returned (privacy - 155, eula - 136, license - 72 after my counting). I don't think I have the means to verify if these numbers are correct. 

cherry-picking 1 or 2 that have an entry in the sitemap and checking that the url does lead to a eula/privacy policy is probably enough.

> Regarding license though, are we taking into account only the Custom License added from this DevHub form?

yes.  Built-in licenses don't have AMO pages/urls (we link directly off-site to the license)

**Comment by AlexandraMoga** [comment]
@eviljeff I found that quite a large number of `/privacy/` and `/eula/` pages are empty. I've double-checked the add-ons in DevHub and noticed that indeed they do not have a Privacy or Eula agreement set. 

Here are a few examples:
https://addons-dev.allizom.org/en-US/firefox/addon/wollinosstest/eula/
https://addons-dev.allizom.org/en-US/firefox/addon/404-bookmarks/eula/
https://addons-dev.allizom.org/en-US/firefox/addon/search-by-image519/eula/
https://addons-dev.allizom.org/en-US/firefox/addon/pndrj-single-version/eula/

https://addons-dev.allizom.org/en-US/firefox/addon/2-28-mb/privacy/
https://addons-dev.allizom.org/en-US/firefox/addon/search_by_image/privacy/
https://addons-dev.allizom.org/en-US/firefox/addon/dark4-reader5/privacy/

**Comment by eviljeff** [comment]
From looking at database, they _do_ have eula or privacy policy set ... it's just `''`, unfortunately.  At least in the locale of the request, `en-US`, because they're translated fields. 

(In an ideal world translations instances of `''` wouldn't exist.  It's near-impossible to get an accurate number of how many eula or privacy policy _specifically_ this has happened for, but addons-dev has 1.6M translations set to `''`, for all translated fields, including some old deleted content).

I'll investigate if there's a way to efficiently take this edge-case (that isn't that edge-y)  in account.

**Comment by eviljeff** [comment]
logged #17046 for follow-up
