### ISSUE TITLE
include localized urls in the sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16909]
followup for #16508 

We currently generate all pages for the sitemap as `/en-US/` but we should have localized urls too.  

There is some level of support in this already in the django sitemaps app but in django2.2 it's a bit too naive - it doesn't support the alternatives syntax to group the urls together, and mis-paginates them meaning we'd end up with more than 50,000 urls per file (the google search limit) unless we manually calculate how much lower it should be (`50000/<however many languages we support>`).  We need the django3.2 implementation.  If we really need this before we're ready to upgrade we can copy over the code from django3.2 to support django2.2 (it's not that much)

Other comments:
- we should prioritize/default to the addon's default locale, rather than `en-US`
- It's unclear what "list" of languages/locales we want to use - I think supported languages differs on addons-frontend and addons-server, and some of those locales have quite minimal coverage.

**Comment by eviljeff** [comment]
ref for canonical/alternate url discussion https://github.com/mozilla/addons-frontend/issues/6644

**Comment by AlexandraMoga** [comment]
@eviljeff I've noticed two things since this issue was closed:

- the sitemap https://addons-dev.allizom.org/sitemap.xml?debug has become super slow - it took for me ~ 2 minutes to load
- sitemap sections are no longer organized as an `.xml`? For example, when I'm loading https://addons-dev.allizom.org/sitemap.xml?section=amo&debug, I'm seeing only a sequence of URLs.

**Comment by eviljeff** [comment]
>     * the sitemap https://addons-dev.allizom.org/sitemap.xml?debug has become super slow - it took for me ~ 2 minutes to load

I've logged #17178 to address this - the way django iterates through the locales is inefficient

>     * sitemap sections are no longer organized as an `.xml`? For example, when I'm loading https://addons-dev.allizom.org/sitemap.xml?section=amo&debug, I'm seeing only a sequence of URLs.

it's still valid sitemap xml (at least from the validators I could find on the web), but Firefox doesn't seem to like the extra `xhtml` tags (or gets confused) and tries to render it as html.

**Comment by AlexandraMoga** [comment]
> it's still valid sitemap xml (at least from the validators I could find on the web), but Firefox doesn't seem to like the extra `xhtml` tags (or gets confused) and tries to render it as html.

so does Chrome too, which makes sections even harder to analyze now.

**Comment by eviljeff** [comment]
yep.  But that's how it's supposed to be implemented, apparently https://developers.google.com/search/docs/advanced/crawling/localized-versions#expandable-3

**Comment by AlexandraMoga** [comment]
So, I was able to see the 10 localizations served by the sitemap for each page in this alphabetical order: `de, en-GB, en-US, es, fr, ja, pl, pt-BR, ru, zh-CN`.

@eviljeff has the following comment ended up being implemented and, if so, how can this be verified?
>we should prioritize/default to the addon's default locale, rather than en-US

**Comment by eviljeff** [comment]
> @eviljeff has the following comment ended up being implemented and, if so, how can this be verified?
> 
> > we should prioritize/default to the addon's default locale, rather than en-US

No, there wasn't a way to define it per add-on in the django implementation so I left off the default url entirely.  It can be implemented in a follow-up if it's deemed worth the extra hassle.
