### ISSUE TITLE
add `write_sitemaps` to crontab

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16906]
follow-up for #16508 

when we're ready and happy to have the sitemaps generated on a schedule we need to add `write_sitemaps` to `crontab.tpl`

**Comment by eviljeff** [comment]
<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMCAyMCIgd2lkdGg9IjIwIiBoZWlnaHQ9IjIwIiBmaWxsPSJibHVlIiBmaWxsLW9wYWNpdHk9ImNvbnRleHQtZmlsbC1vcGFjaXR5Ij4KICA8cGF0aCBkPSJNMTUuNSA1IDEzIDVsMC0yLjVhMi41IDIuNSAwIDEgMC01IDBMOCA1IDQuNSA1QTIuNSAyLjUgMCAwIDAgMiA3LjVsMCAxLjkuNi42IDEuODkzIDBhMiAyIDAgMCAxIDAgNEwyLjYgMTRsLS42LjYgMCAyLjlBMi41IDIuNSAwIDAgMCA0LjUgMjBsMTEgMGEyLjUgMi41IDAgMCAwIDIuNS0yLjVsMC0xMEEyLjUgMi41IDAgMCAwIDE1LjUgNXoiLz4KPC9zdmc+">

**Comment by AlexandraMoga** [comment]
Same as for #17273, I did not find issues with the sitemap on -dev.

**Comment by eviljeff** [comment]
(sorry, forgot to write QA notes).

verification for this would be to check the sitemap available at https://addons-dev.allizom.org/sitemap.xml (and the linked urls within it) are updated every 24 hours.   Easiest way would be to make a change to an addon or upload a new one and check the changes are reflected in the sitemap xml files.

**Comment by AlexandraMoga** [comment]
@eviljeff so https://addons-dev.allizom.org/sitemap.xml?debug (I've seen you omitted `debug` in the link you referred - not sure if it was intentional)  seems to be loading faster now and all the sitemap sections URLs are there. 
I've also checked the update interval by updating an add-on and a user profile and the changes have been reflected in the xml files.

**Comment by eviljeff** [comment]
> @eviljeff so https://addons-dev.allizom.org/sitemap.xml?debug (I've seen you omitted `debug` in the link you referred - not sure if it was intentional)

It was intentional.  `?debug` was just for debugging the content is correct during development and bypasses entirely what the cron job generates.

**Comment by AlexandraMoga** [comment]
All right then. In that case, I suppose I have to wait until tomorrow to check if the updates will be present in the xml files, because now they're only reflected in the `&debug` version.

**Comment by AlexandraMoga** [comment]
The sitemap has been updated with the new data.
