### ISSUE TITLE
add all (remaining) frontend pages to sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16905]
follow up for #16508

addons-server doesn't "know about" every frontend page so the pr for #16508 just added the ones we already had defined in urls.pys (the vast majority of the urls in addons-server are behind auth, or apis).  

~Pages with pagination/filters are a problem - e.g. category pages - because we a) don't know how many pages there are without either attempting to replicate the same query that the API would run in elasticsearch, or actually calling the API, and b) filters cause a potential explosion in the number of pages (if the default filter is effectively filtering nothing out I think we can avoid the filtered results).~

~As we exclude search result this wasn't previously a concern, but category pages are effectively search pages and inherit the same difficulties that caused us to exclude them.~
(spun out category pages to #16959)

Also, a future problem will be keeping everything in sync on addons-server when pages are added/removed to addons-frontend.

**Comment by eviljeff** [comment]
> Also, a future problem will be keeping everything in sync on addons-server when pages are added/removed to addons-frontend.

If this becomes an actual problem we could have frontend generate it's own sitemap and then the index sitemap.xml would link to it.  But right now the fixed pages on frontend are very few and their urls don't change frequently.

**Comment by AlexandraMoga** [comment]
@eviljeff can this be verified individually in any way or should it be covered when testing for #16508 becomes available?

**Comment by eviljeff** [comment]
@AlexandraMoga ops deployed the nginx change so it can be tested now.

**Comment by AlexandraMoga** [comment]
I believe this PR refers only to the pages added under https://addons-dev.allizom.org/sitemap.xml?section=amo&debug. I've checked all the links included in this section and they are directed to the correct frontend pages.

@eviljeff I have an observation for the `/categories` links. In the sitemap they appear without an trailing slash:

```
<loc>https://addons-dev.allizom.org/en-US/firefox/extensions/categories</loc>
```

On the frontend, however, `/categories/` are expecting a trailing slash - https://addons-dev.allizom.org/en-US/firefox/extensions/categories/. This means that the category pages linked in the sitemap will trigger a 301.

In https://github.com/mozilla/addons-server/issues/16508#issuecomment-785841459, the guidelines specifies that only pages that trigger a 200 should be served:

>Include only urls that are 200 (no redirects, 404s etc. so https://addons.mozilla.org wouldnt be included, as its always redirected)

**Comment by eviljeff** [comment]
can you file a follow-up?  There might be a few more too - we've never really paid that much attention previously to slashes because they get corrected, but now we should.
