### ISSUE TITLE
Include /android/ pages in the sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16910]
followup for #16508 

We currently generate all urls with the app in them as `/firefox/`.  We should also include `/android/` pages too - the landing pages are different but the detail pages are essentially the same (slightly different header, with some extra warnings about compatibility)

Questions:
- Should add-ons that only support desktop Firefox have an `/android/` page?  Should purely Android compatible add-ons have a `/firefox/` page?  They do exist if navigated to but we don't link to them as they're invalid, really.
- If we have both /firefox/ and /android/ urls, should one be an "alternative" of the other or included separately?

**Comment by eviljeff** [comment]
@rraue ^ should we generate /android/ and /firefox for all addon detail pages?

**Comment by rraue** [comment]
It can be in one or two split sitemaps. Doesnt matter. Important is only that all pages we want indexed are in the sitemaps.

**Comment by willdurand** [comment]
See: https://github.com/mozilla/addons-server/pull/17004#discussion_r620967007

**Comment by bobsilverberg** [comment]
@eviljeff Before I review this, did anything from today's meeting change anything about how we want to handle `android` URLs? It sounds like we only need to include pages that we actually want indexed, so we should probably exclude categories, and it also seems like it would make sense to only include detail pages for add-ons that actually work on Android.

**Comment by willdurand** [comment]
> @eviljeff Before I review this, did anything from today's meeting change anything about how we want to handle `android` URLs? It sounds like we only need to include pages that we actually want indexed, so we should probably exclude categories, and it also seems like it would make sense to only include detail pages for add-ons that actually work on Android.

Is it really about "all pages we want indexed" or is it "all pages that are actually indexed"? Because I am not sure those two sets are the same.

**Comment by eviljeff** [comment]
> @eviljeff Before I review this, did anything from today's meeting change anything about how we want to handle `android` URLs? It sounds like we only need to include pages that we actually want indexed, so we should probably exclude categories, 

we do exclude categories - there's a code comment about it.

> and it also seems like it would make sense to only include detail pages for add-ons that actually work on Android.

I asked that above, but I suppose the answer wasn't explicit.  The patch is blocking remaining work so any changes can be in a follow-up.

The general answer from the meeting - that I understood - was that the sitemap should reflect the pages we want indexed, but it's the meta tags in the page itself that defines it.  I.e. _just_ dropping pages from the sitemap doesn't help if they happen to be linked elsewhere; the meta tags in the html have to exclude the page.

**Comment by willdurand** [comment]
> The general answer from the meeting - that I understood - was that the sitemap should reflect the pages we want indexed, but it's the meta tags in the page itself that defines it. I.e. _just_ dropping pages from the sitemap doesn't help if they happen to be linked elsewhere; the meta tags in the html have to exclude the page.

Thanks. Are you or we aware of pages that are currently indexed but should not? And same questions for pages currently not crawled because the `robots.txt` prevents crawling but we don't have a `<meta name="robots" content="noindex, follow" />`?

AFAIK we only render `<meta name="robots" content="noindex, follow" />` on the following pages:

- the new-ish block pages
- the custom license/eula/privacy policy pages
- the review pages when a single review is highlighted, e.g., https://addons.mozilla.org/en-US/firefox/addon/amo-info/reviews/1600618/

**Comment by eviljeff** [comment]
> Are you or we aware of pages that are currently indexed but should not? 

potentially any of the /android/ pages we don't expose (category pages, etc).  Maybe even the /android/ detail pages for non-android compatible add-ons?  (the same for android only addons on desktop?)  

My thinking right now is: we should move this discussion to a frontend issue, and then sitemap should contain the pages that don't have `<meta name="robots" content="noindex, follow" />`, omitting pages that do.   (I'm open to alternative ideas)

> AFAIK we only render `<meta name="robots" content="noindex, follow" />` on the following pages:
...
>     * the custom license/eula/privacy policy pages

we have those in the sitemap currently - it seemed like valid content?

**Comment by rraue** [comment]
No need to include pages in the sitemap we do NOT want indexed. Only the ones that should be indexed. And its totally fine to exclude some pages from the sitemap but set noindex. follow later. The sitemap is the recommendation what to crawl, so lets include the pages we want.

**Comment by willdurand** [comment]
> added in #16984 😬

Yeah, sorry about that. I only remembered today while reviewing `noindex` meta tags.

**Comment by eviljeff** [comment]
logged #17111 to drop custom policies again; please log issues for anything else that needs changing/removing from the sitemap.

**Comment by AlexandraMoga** [comment]
AMO pages that are served for `/android/` have been included in the sitemap. Pages that are not included are: `/extensions/`, `/themes/`, `/language-tools/` and `/categories/` since we don't directly link to them on android.

@eviljeff a question about the `app_name=` parameter which determines the `/firefox/` or `/android/` sections: as far as I can see, this parameter accepts any value, so, for example, I can pass https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=foo&debug and the sitemap will format the links in this section as https://addons-dev.allizom.org/en-US/foo/addon/min-max/, which, of course, is an invalid url. I'm not sure if this might be problematic in the future.

**Comment by eviljeff** [comment]
> @eviljeff a question about the `app_name=` parameter which determines the `/firefox/` or `/android/` sections: as far as I can see, this parameter accepts any value, so, for example, I can pass https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=foo&debug and the sitemap will format the links in this section as https://addons-dev.allizom.org/en-US/foo/addon/min-max/, which, of course, is an invalid url. I'm not sure if this might be problematic in the future.

It's only really a problem when using `?debug` - normally the parameter would resolve into a filename that would just 404 if the app didn't exist.

**Comment by eviljeff** [comment]
filed #17143 to discuss only including pages for add-ons that are compatible with that app
