### ISSUE TITLE
README.rst should say to file security bugs on Bugzilla

### ISSUE THREAD

**Issue by marumari** [mozilla/addons-server#1691]
Could you please update the README.rst document with directions on where and how to file bugs in security bugs in Bugzilla?  Since GitHub doesn't let you have private issues, we need to file security bugs there.

Thanks!

**Comment by muffinresearch** [comment]
Looks like this is the right link:

https://bugzilla.mozilla.org/enter_bug.cgi?product=addons.mozilla.org&component=Administration&groups=mozilla-employee-confidential&groups=client-services-security

Just wondering if we should have a better component as I can see people changing the bug report to point to `Add-on Security` even though that's not what we want.

**Comment by yash14123** [comment]
I would like to work on this. Please provide me with the details to mention in the doc about bugzilla issues.

**Comment by andymckay** [comment]
Let's fix up the docs that get pushed to read the docs too please.

**Comment by amuntner** [comment]
<https://bugzilla.mozilla.org/form.web.bounty>

You can point them there, they get triaged quickest and all the right
security flags will be set. Here's text to use:


This code and it’s associated production website are included in Mozilla’s
web and services bug bounty program.[1] If you find a security
vulnerability, please submit it via the process outlined in the program and
FAQ[2] pages. Further technical details about this application are
available from the Bug Bounty Onramp page.[3]

Please submit all security-related bugs through Bugzilla using the web
security bug form. Never submit security-related bugs through a Github
Issue or by email.

1. https://www.mozilla.org/en-US/security/web-bug-bounty/
2. https://www.mozilla.org/en-US/security/bug-bounty/faq-webapp/
3. https://wiki.mozilla.org/Security/BugBountyOnramp/

**Comment by yash14123** [comment]
Got it.
On it. :)

**Comment by amuntner** [comment]
Not sure if you were reading in email or on github, I made an edit to the prev post to add a #4 that I don't see in the email thread for this issue.

**Comment by muffinresearch** [comment]
@yash14123 hi are you still planning to work on this? Let me know if you need any help. 

Also if you don't have time it's not a problem just let us know.

**Comment by yash14123** [comment]
Hey. 
Sorry for the delay. I am working on it. Will be done today.

**Comment by muffinresearch** [comment]
@theaverageguy how's it going? Let me know when you've got something ready for a review or if you need any help.

**Comment by muffinresearch** [comment]
@theaverageguy I'm going to take this one since it's been a while and it's important that we have this info available so security bugs are going to the right places.
