### ISSUE TITLE
recreate_theme_previews shouldn't delete old VersionPreview before firing task

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16920]
`recreate_theme_previews` function (used by `process_addons` tasks create_missing_theme_previews or recreate_theme_previews) deletes the old `VersionPreview` instances for the version, and then calls `generate_static_theme_preview.delay`, meaning if there's a backlog in the task queue (likely if we're regenerating 500k themes) there will be an extended period where there are no preview images available for some themes.  Instead we should delete the old previews in the `generate_static_theme_preview` task itself.

**Comment by ioanarusiczki** [comment]
@eviljeff Themes I submitted with .svg version previews or other themes with .png version previews,  are not affected - on detail pages or in search results on AMO dev.

**Comment by eviljeff** [comment]
I gave this a trial run on addons-dev this morning with 15000 themes.  
Pros: it worked great and I couldn't find any broken theme previews after it had finished; 
Cons: there a period of time where the search results shows an empty/broken preview - I think because the es reindex task got stuck behind other preview generation tasks in the same celery task queue.

Time: 35 minutes for 15k themes (so ~ 18 hours for 450k themes on prod, assuming same throughput)

two tracebacks I need to investigate further:
- https://sentry.prod.mozaws.net/operations/olympia-dev/issues/10802333/?query=is%3Aunresolved
- https://sentry.prod.mozaws.net/operations/olympia-dev/issues/10802334/?query=is%3Aunresolved
