### ISSUE TITLE
remove some cruft from bandwagon/models.py

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16935]
Most of the custom `CollectionManager` class appears unused.

**Comment by eviljeff** [comment]
The PR ended up removing a lot more than just `CollectionManager` methods, fwiw.  `application`, `nickname` and `type` went from the `Collection` model too.  None of this was exposed/used in the API.

**Comment by AlexandraMoga** [comment]
I've checked the collection model in django admin and also checked collections functionality on the frontend and I haven't found any issues.

I'm marking this as verified fixed.
