### ISSUE TITLE
Update character limit for `title` and `footer_text` within Shelf Module

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#16930]
Per [#9996](https://github.com/mozilla/addons-frontend/issues/9996), the character limit for `title` and `footer text` fields from the [shelfmodule](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/) may need to be adjusted. The screenshot below displays both fields at 100 characters:

![114384010-dbcd5a00-9b96-11eb-80e9-4cc2c8417a3d](https://user-images.githubusercontent.com/28129806/114649399-779db980-9cae-11eb-9326-21d7f367e48b.png)

The maximum text length that the UI supports need to be determined.

**Comment by bobsilverberg** [comment]
@devaneymoz We would like to implement a character limit for the Shelf Title and Footer Text (which actually is not a footer at all, but is the text on the right-hand side that links to more extensions from the shelf), in an attempt to mitigate this problem. Do you have any suggestions for what we can use that will still give you enough room for a shelf title and footer text?

**Comment by bobsilverberg** [comment]
@devaneymoz bump

> @devaneymoz We would like to implement a character limit for the Shelf Title and Footer Text (which actually is not a footer at all, but is the text on the right-hand side that links to more extensions from the shelf), in an attempt to mitigate this problem. Do you have any suggestions for what we can use that will still give you enough room for a shelf title and footer text?

**Comment by devaneymoz** [comment]
Tricky one because we should account for languages with typically longer character words (e.g. German). Could we do something in the range for 40 - 50 character max?

**Comment by bobsilverberg** [comment]
> Tricky one because we should account for languages with typically longer character words (e.g. German). Could we do something in the range for 40 - 50 character max?

You're the one who needs to answer that question @devaneymoz 😉 We can do whatever you are comfortable with.

**Comment by jvillalobos** [comment]
I would like to propose that the title wraps if it collides with the link, since we can't anticipate how long some of these strings will be. This in addition of setting a character limit.

On the current homepage, "Recommended password managers" and "See more recommended password managers" are the longest title and footer text, respectively, at 29 and 38 characters. In German I see strings that are as long as 55 characters. I think a reasonable limit with this in mind is about 70 characters for each. Unfortunately, the title and link tend to have similar text, so if one is long, the other one will be similarly long and may still fill up the box.

**Comment by eviljeff** [comment]
#17376 will fix this in the models/db on addons-server - if we still want wrapping a follow-up needs filing on addons-frontend.

@devaneymoz can you check that none of the existing shelves have a title that's longer than that in English?  (they will be auto-trimmed on June 24th)

Note: we can only limit the length in English - translators will still be able to create localisations which are longer than this.  (we _could_ trim the localized strings to 70 in the API before they are returned but this seems undesirable.)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- the [admin shelf module](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/62/change/) allows a maximum of 70 chars into the "title" and "footer text" fields.
- at a max. of 70 chars (for both fields) at 1228 px they start overlapping ( less realistic, but I'm adding it as a note):
 
![overlap](https://user-images.githubusercontent.com/33448286/123102557-dc5b5a00-d43d-11eb-8275-94a908e0c520.png)

Verified on AMO dev - FF89(Win10).
