### ISSUE TITLE
Instagram should replace Facebook on dev hub footer

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#16938]
Same as for https://github.com/mozilla/addons-frontend/issues/10304 

The footer on dev hub - has Twitter, Facebook and Youtube icons which redirect to Mozilla pages on these platforms

On frontend Facebook has been replaced with Instagram and redirects to https://www.instagram.com/firefox/

The footer on Dev Hub page https://addons.allizom.org/en-US/developers/ should have Instagram too.

**Comment by nayaldivya** [comment]
I would like to work on this.

**Comment by championshuttler** [comment]
> I would like to work on this.

Go ahead and raise the PR, feel free to ask if you have questions

**Comment by nayaldivya** [comment]
Hey @championshuttler , Can you help me locate the file in which I have to make changes?

**Comment by championshuttler** [comment]
> Hey @championshuttler , Can you help me locate the file in which I have to make changes?

https://github.com/mozilla/addons-server/blob/d9467f6030b3a3e4642950e415ed118fc823b74a/src/olympia/templates/photon-footer.html#L46
