### ISSUE TITLE
Don't show the prompt to switch to FxA after the switch

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1693]
Don't show the prompt to switch to FxA after the switch

https://www.dropbox.com/s/s4vg5yvo9e3oxdm/Screenshot%202016-02-16%2012.04.44.png?dl=0

**Comment by mstriemer** [comment]
We had some redis issues right when we turned this on and I believe this has been resolved. Please reopen if it is still happening.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-03-07_1742](https://cloud.githubusercontent.com/assets/15685960/13574256/02c5fcf6-e48c-11e5-95ee-b4879a6d8893.png)
