### ISSUE TITLE
Username is not getting updated.

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1694]
##steps to reproduce:
1. Register to AMO with a new FxA account
2. Go to Account Settings and set up your Username
3. Save changes

## observed behavior:
username is not getting updated.
screenshot: https://www.dropbox.com/s/h0wtnhc6ev9zyn4/Screenshot%202016-02-16%2012.07.30.png?dl=0

**Comment by andymckay** [comment]
This was likely a redis problem that was fixed by @jasonthomas

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/O7q9MQhD
