### ISSUE TITLE
License name isn't returned as an object at all times for requests with `lang`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#16952]
I found this when investigating https://github.com/mozilla/addons-frontend/issues/10329. A call to the add-on detail endpoint, which passes a `lang` can return a non-localized value for `license.name`. See this example:

Response to http://localhost:3000/api/v5/addons/addon/ublock-origin/?lang=en-US (just a snippet):
```
{
...
    "current_version": {
        "license": {
            "id": 6,
            "is_custom": false,
            "name": {
                "en-US": "GNU General Public License, version 3.0"
            },
            "url": "http://www.gnu.org/licenses/gpl-3.0.html"
        },
	},
...
}
```

http://localhost:3000/api/v5/addons/addon/strict-compat-addon/?lang=en-US (just a snippet):
```
{
...
	"current_version": {
	      "license": {
	          "id": 5045,
	          "is_custom": false,
	          "name": "All Rights Reserved",
	          "url": null
	      },
	    },
	},
...
}
```

Note how the second response includes simple text for `license.name`.

Note also that if I leave the `?lang=en-US` off the URL then I *do* get back a localized string for `license.name` in both responses.

**Comment by diox** [comment]
Nice one. `LicenseSerializer` has a special handling for `name` because of the builtin licenses. It should emulate what `TranslationSerializerField` but it looks like it doesn't completely, which is bad...

**Comment by AlexandraMoga** [comment]
The license name is now returned as an object:

https://addons-dev.allizom.org/api/v5/addons/addon/dark22reader/?lang=en-US
```
"license": {
            "id": 4055,
            "is_custom": false,
            "name": {
                "en-US": "All Rights Reserved"
            },
```

https://addons-dev.allizom.org/api/v5/addons/addon/sleep-mode/?lang=en-US
```
"license": {
            "id": 13,
            "is_custom": false,
            "name": {
                "de": "GNU General Public License, Version 2.0"
            },
```

This issue is verified fixed on -dev.
