### ISSUE TITLE
add category pages to sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16959]
spun out from #16905

Pages with pagination/filters are a problem - e.g. category pages - because we a) don't know how many pages there are without either attempting to replicate the same query that the API would run in elasticsearch, or actually calling the API, and b) filters cause a potential explosion in the number of pages (if the default filter is effectively filtering nothing out I think we can avoid the filtered results).

**Comment by AlexandraMoga** [comment]
The sitemap contains the new categories section (including only categories for app /firefox/ for now) - https://addons-dev.allizom.org/sitemap.xml?section=categories&debug

To test this, I focused mainly on checking that all the supported categories for themes and extensions are present in the sitemap and the pagination matches what we see in the frontend.

@eviljeff I found out that the following extension category page listed in the sitemap doesn't actually exist. I've also checked in the API and we don't seem to have a `page=11` for `/extensions/category/games-entertainment/`:
https://addons-dev.allizom.org/en-US/firefox/extensions/category/games-entertainment/?page=11 - does not exist

**Comment by eviljeff** [comment]
we seem to have slightly different counts for some addons in catergories from a search (elasticsearch) vs. a db query.  Possibly across all categories but `games-entertainment` is noticeable because ES says 248 results and the query says 254, so it's pushed it over into another page.  

2 of them are because frontend sends the browser version on Firefox (if you look in non-firefox it's 250 results) so I'm not worried about.  The other 4 "missing" addons are:
```
 618232,
 619938,
 619968,
 620117
```
I'm still investigating but initially it seems they are Android only addons that have Firefox categories - a bit of an edge case but still something that should have been taken into account.

**Comment by eviljeff** [comment]
This is roughly what the sitemap code is doing, filtered to just that category:
```
AddonCategory.objects.filter(
    category_id=142,
    addon___current_version__isnull=False,
    addon__disabled_by_user=False,
    addon__status__in=amo.REVIEWED_STATUSES,
    addon__type=amo.ADDON_EXTENSION,
).values('category_id').annotate(count=Count('addon_id'))
```
or 
```
Addon.unfiltered.filter(
    addoncategory__category_id=142,
    _current_version__isnull=False,
    disabled_by_user=False,
    status__in=amo.REVIEWED_STATUSES,
    type=amo.ADDON_EXTENSION,
).values_list('id', flat=True).count()
```
to replicate in a django shell on addons-dev.  (strip off the `.count()` to get the ids)

**Comment by eviljeff** [comment]
@AlexandraMoga fix merged now

**Comment by AlexandraMoga** [comment]
Category pagination appears to be correct now.

This issue is verified fixed on -dev.
