### ISSUE TITLE
Dropdown menu is hidden behind the success message

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1695]
## steps to reproduce:
1. Migrate one of your AMO accounts to FxA
2. Notice the success message on the homepage after the successful transition
3. Hover on the menu items

## observed behavior:
Dropdown menu is hidden behind the success message

screenshot: https://www.dropbox.com/s/wxgwl0bxdmxfqmz/Screenshot%202016-02-16%2012.23.56.png?dl=0

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/3hYJYVENy
