### ISSUE TITLE
Temporarily disable auto-approval when instant-rejecting

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#16962]
### Describe the problem and steps to reproduce it:

For a delayed reject, we disable auto-approval until the next manual approval and automatically subscribe the user to submission notifications of the channel for which they rejected versions.

We should do the same for instant-rejects.

STR:
1. Have a public add-on.
2. Instant-reject ("Reject immediately") a version.

### What happened?

0. (Note you need to go back to or reload the review page for the add-on to see potential changes.)
1. "Notify me about new <listed|unlisted> versions" is not checked
2. "Disable Listed Auto-Approval Until Next Manual Approval" is not changed to "Enable Listed Auto-Approval Until Next Manual Approval"

### What did you expect to happen?

0. (Note you need to go back to or reload the review page for the add-on to see potential changes.)
1. "Notify me about new <listed|unlisted> versions" got checked automatically
2. "Disable Listed Auto-Approval Until Next Manual Approval" has changed to "Enable Listed Auto-Approval Until Next Manual Approval"

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and I have the following results:

- for listed versions - immediate rejection:
  - the 'Notify me about new listed versions' is checked automatically
  - the 'Disable Listed Auto-Approval Until Next Manual Approval' button changes to 'Enable Listed Auto-Approval Until Next Manual Approval'
  - reviewers are notified when a new version is uploaded
  - new uploaded listed versions are not auto-approved
  - the delay rejection functionality remains unchanged

- for unlisted versions - only immediate rejection being available in this case:
  - the 'Notify me about new unlisted versions' is checked automatically
  - the 'Disable Listed Auto-Approval Until Next Manual Approval' button changes to 'Enable Listed Auto-Approval Until Next Manual Approval' => if a listed version will be submitted, it won't be auto-approved - see [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/93d6247d2e4e4b33b91f). @wagnerand is this the behavior you expect for unlisted add-on rejections?

**Comment by wagnerand** [comment]
I forgot to reply here, I filed #17249 as a followup. Thank you @AlexandraMoga for calling that out!
