### ISSUE TITLE
500 error on pages showing Activity Log for a Rating posted before October 2017

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#16964]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/11085753/?referrer=github_plugin

```
LookupError: No installed app with label 'reviews'

KeyError: 'reviews'
  File "django/apps/registry.py", line 155, in get_app_config
    return self.app_configs[app_label]

LookupError: No installed app with label 'reviews'.
(8 additional frame(s) were not displayed)
...
  File "olympia/amo/models.py", line 54, in _fetch_all
    func(self._result_cache)
  File "olympia/activity/models.py", line 233, in default_transformer
    ActivityLog.arguments_builder(logs)
  File "olympia/activity/models.py", line 442, in arguments_builder
    model = apps.get_model(app_label, model_name)
  File "django/apps/registry.py", line 205, in get_model
    app_config = self.get_app_config(app_label)
  File "django/apps/registry.py", line 162, in get_app_config
    raise LookupError(message)
```

Regression https://github.com/mozilla/addons-server/pull/16893, which seems fairly uncommon: my guess is that it will only happen if you have extremely old activity in your feed (from before the reviews -> ratings renaming)

**Comment by eviljeff** [comment]
#6761 for the reviews->ratings change.  Would potentially 500 any page where we show the activity log to the user?  or just /developers/feed/<addon> ?

**Comment by diox** [comment]
Possibly any page showing an activity log from before October 2017 because I messed up the way it's translated:
https://github.com/mozilla/addons-server/pull/16893/files#diff-473099b78767e3b276d5318cfc57013234fbd9653c1368e053bda0674484125fR440

It's more likely to affect developer feed, but technically can happen anywhere.

**Comment by diox** [comment]
Bumping priority as a result. It should be simple to fix (but we can't just revert that bit: it's important that `key` is translated as well)

**Comment by diox** [comment]
QA: 
- Post a rating for an add-on
- Check that "recent changes" in devhub dashboard for the developer of the add-on works and shows that activity. Same for the recent changes on the add-on itself in devhub, as well as review log in reviewer tools.
- Contact me on Matrix to test further (the original problem can only be reproduced with the data in the database in a specific state)

**Comment by AlexandraMoga** [comment]
We've tested with a few ratings and confirmed that the following areas are working as expected:
- the Recent changes section in DevHub - Manage my submissions page (entry for the rating posted is displayed)
- the Recent activity for all developer add-ons page (entry for the rating posted is displayed)
- the Recent changes for a particular add-on (entry for the rating posted is displayed)
- the Add-on Review Log in Reviewer Tools can be loaded when it includes an entry for the add-ons used in these tests 

This issue is verified fixed on -dev.
