### ISSUE TITLE
Expose (some) account profile pages to sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16960]
users who are developers (have >0 public addons) have a visible account profile page that links to their extensions/themes, so we should expose those pages in the sitemap too.

(double!) pagination for users who have many addons is a complication (which could be added in a follow-up)

**Comment by eviljeff** [comment]
@mozilla/addons-amo-engineering was there a deliberate decision to have in-page pagination for users who have >10 extensions or >12 themes?  (double pagination possible too)  Rather than some sort of generic `search?type=extension&author=xxx` page?

**Comment by willdurand** [comment]
> @mozilla/addons-amo-engineering was there a deliberate decision to have in-page pagination for users who have >10 extensions or >12 themes? (double pagination possible too) Rather than some sort of generic `search?type=extension&author=xxx` page?

Yes, and there are rules around pagination and canonical URLs: https://github.com/mozilla/addons-frontend/blob/09c10da237835a6f1a9d829a053d3e01822456df/src/amo/components/UserProfileHead/index.js#L27-L64

**Comment by eviljeff** [comment]
> 
> 
> > @mozilla/addons-amo-engineering was there a deliberate decision to have in-page pagination for users who have >10 extensions or >12 themes? (double pagination possible too) Rather than some sort of generic `search?type=extension&author=xxx` page?
> 
> Yes, and there are "rules" around pagination and canonical URLs: https://github.com/mozilla/addons-frontend/blob/09c10da237835a6f1a9d829a053d3e01822456df/src/amo/components/UserProfileHead/index.js#L27-L64

What are the rules around pagination and canonical URLs that lead to having a paginated user profile page rather than linking to a paginated search page?  (I don't see anything in the JS implementation that explains understand the decision or rules)

**Comment by willdurand** [comment]
> What are the rules around pagination and canonical URLs that lead to having a paginated user profile page rather than linking to a paginated search page? (I don't see anything in the JS implementation that explains understand the decision or rules)

User profiles have "paginated cards" as per Product decision, see: https://github.com/mozilla/addons-frontend/issues/4809

This predates the introduction of canonical URLs for/indexation of those pages, though. User profile pages are now indexed and therefore canonical URLs had to be predictable, this has been implemented in https://github.com/mozilla/addons-frontend/issues/6527

**Comment by AlexandraMoga** [comment]
The sitemap exposes user profile pages for both `firefox` and `android` - the exact same pages for both applications, regardless of add-on compatibility. 

@eviljeff these are a few inconsistencies I've found:

Users with (apparently) incorrect pagination:
In this [sitemap page](https://addons-dev.allizom.org/sitemap.xml?section=users&app_name=firefox&debug):
1.  user 10641574 => https://addons-dev.allizom.org/en-US/firefox/user/10641574/?page_e=15 not found; on the frontend, this user only has 14 pages with extensions; in django admin, there are [146 approved extensions](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?all=&authors=10641574%20&status__exact=4&type__exact=1) by this user, so I'm guessing the sitemap pagination takes this number into account;
2. user 10641527 => https://addons-dev.allizom.org/en-US/firefox/user/10641527/?page_e=18 not found; on the frontend, this user only has 17 pages with extensions; in django admin, there are [179 approved extensions](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?all=&authors=10641527&status__exact=4&type__exact=1) by this user, so I'm guessing the sitemap pagination takes this number into account;
3. user 10641572 => https://addons-dev.allizom.org/en-US/firefox/user/10641572/?page_e=9 not found: on the frontend, this user only has 8 pages with extensions; in django admin, there are [85 approved extensions](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?all=&authors=10641572&status__exact=4&type__exact=1) by this user, so I'm guessing the sitemap pagination takes this number into account;

I don't have a clear visibility on the add-ons that are not counted on the frontend. I guess they could be incompatible for some reason.

Some other issues:
On the last [sitemap page with users](https://addons-dev.allizom.org/sitemap.xml?section=users&app_name=firefox&p=43&debug), the last entries do not have a `lastmod` date and when I've tried to open some of those profiles I've found:
1. Users without content (extensions or themes), profile page is loaded:
https://addons-dev.allizom.org/en-US/firefox/user/10641975/
https://addons-dev.allizom.org/en-US/firefox/user/7725178/
2. Profile page returns a 404 on the frontend(*):
https://addons-dev.allizom.org/en-US/firefox/user/10642071/
https://addons-dev.allizom.org/en-US/firefox/user/10642003/

(*) for this set, django admin shows these users as Deleted, but the 'Is Public' flag is still on. I'm not sure why the flag hasn't changed when those users were deleted, or banned.

**Comment by eviljeff** [comment]
ah, I didn't realise that the addons listed were actually filtered by app compatibility per page - the count is 145 extensions from the query I'm using, which is the same as https://addons-dev.allizom.org/api/v5/addons/search/?author=10641574&page_size=10&sort=users&type=extension&lang=en-US (i.e. without the `app=firefox`)

**Comment by eviljeff** [comment]
> On the last [sitemap page with users](https://addons-dev.allizom.org/sitemap.xml?section=users&app_name=firefox&p=43&debug), the last entries do not have a `lastmod` date and when I've tried to open some of those profiles I've found:
> 
>     1. Users without content (extensions or themes), profile page is loaded:
>        https://addons-dev.allizom.org/en-US/firefox/user/10641975/
>        https://addons-dev.allizom.org/en-US/firefox/user/7725178/
> 
>     2. Profile page returns a 404 on the frontend(*):
>        https://addons-dev.allizom.org/en-US/firefox/user/10642071/
>        https://addons-dev.allizom.org/en-US/firefox/user/10642003/
>
> (*) for this set, django admin shows these users as Deleted, but the 'Is Public' flag is still on. I'm not sure why the flag hasn't changed when those users were deleted, or banned.

can you log a follow-up issue?  Sounds like bad dev data but I should catch it anyway.
