### ISSUE TITLE
Accepting the TOS (dev agreement) shouldn't be a step in the submission flow

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1696]
From [bug 1216527](https://bugzilla.mozilla.org/show_bug.cgi?id=1216527).

Following [bug 1209226](https://bugzilla.mozilla.org/show_bug.cgi?id=1209226) we now only need to accept the agreement once. Accepting the agreement should therefore not be part of the add-on submission flow anymore. It's currently "step 1", but it should be taken out of those steps, and instead just be a requirement to submitting a new add-on.

So when clicking on the "submit a new add-on" link, it should display this dev agreement if it wasn't accepted yet, and then only the first step of the submission "Upload your add-on".
If the agreement was already accepted, then it should display the first step straight away.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF45(Win 7).
Accepting TOS page in AMO-dev looks like in stage (still Step 1, don't know if intended).
Please see the screenshots: 
![untitled](https://cloud.githubusercontent.com/assets/15685960/14012530/ebcc45e8-f1ae-11e5-8ce1-7629369db09c.png)

But, when trying to accept the dev-agreement, I cannot=> I cannot submit an add-on if my account is new. :(
Please see the screencast: http://screencast.com/t/jGMPqyDm7FJb
Nothing in the console.

**Comment by mstriemer** [comment]
I reverted the old commit. I'll look into why this is regressed shortly.

**Comment by mstriemer** [comment]
This is still regressed on -dev. It appears to be a caching issue. I created a new account and could reproduce and a few minutes later it redirects to step 2.

**Comment by ValentinaPC** [comment]
Verified as fixed after mstriemer ' s scenario using AMO-dev FF45(Win 7) and a new account.
Please see the screenshot: 
![2016-04-12_1720](https://cloud.githubusercontent.com/assets/15685960/14463289/1d09fdf2-00d3-11e6-91b7-4e877e9abda3.png)
