### ISSUE TITLE
run the theme preview regeneration tasks in a different task queue

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16973]
follow up for #16920

we generate theme previews in the priority queue because normally we want to display them to the theme developer straight away. But if we do this for `recreate_theme_previews` the priority queue ends up full of themes, which blocks other priority tasks from completing (including elasticsearch reindex tasks leading to a stale index).

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know when to check this on AMO dev.  (I still see .png format on detail pages or search results)
Thanks!

**Comment by eviljeff** [comment]
@ioanarusiczki I've run it on dev.  All the theme previews should be converted now.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I checked on AMO dev - theme previews for detail pages, search results, categories are now .svg. 

One exception - this [theme](https://addons-dev.allizom.org/en-US/firefox/addon/the-moon-cat/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-collection-featured) left as .png.
 That's the only one found with .png preview https://addons-dev-cdn.allizom.org/user-media/version-previews/full/14/14309.png?modified=1615314373

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff
> I checked on AMO dev - theme previews for detail pages, search results, categories are now .svg.
> 
> One exception - this [theme](https://addons-dev.allizom.org/en-US/firefox/addon/the-moon-cat/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-collection-featured) left as .png.
> That's the only one found with .png preview https://addons-dev-cdn.allizom.org/user-media/version-previews/full/14/14309.png?modified=1615314373

that one didn't regenerate because of a manifest error (the xpi failed to load - I can't see why though as I can download the xpi fine). I'll see if running it again just on that addon fixes it.

**Comment by eviljeff** [comment]
seemed to work time 🤷
