### ISSUE TITLE
API v3 views do not have access to request.groups

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1697]
There is some ancient code that sets request.groups in [middleware](https://github.com/mozilla/addons-server/blob/master/src/olympia/access/middleware.py#L24). For some reason, the new-ish API v3 views (such as [signing views](http://addons-server.readthedocs.org/en/latest/topics/api/signing.html)) do not get a request with `.groups`. This causes calls like `acl.action_allowed(request, ...)` to always fail.

I can't figure out why these views don't have `request.groups`. Anyway, it is possible to use `acl.action_allowed_user(request.user, ...)` as a workaround if you know that the user will always be authenticated.

**Comment by diox** [comment]
e171c5a99caad4218a117c9a7034911598ebfd08 got rid of `request.groups` entirely, precisely to fix these kind of issues.
