### ISSUE TITLE
add ratings to sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16986]
follow on from #16907 

we need to add pages for ratings for addons, but we've got the same pagination problem that we have with categories (#16959) (and to a less common extent, user account profiles)

**Comment by AlexandraMoga** [comment]
@eviljeff I found add-on ratings added to https://addons-dev.allizom.org/sitemap.xml?section=addons&p=3&debug and `?section=addons&p=4&debug`. All add-on review pages seem to be present in the sitemap, including those with no ratings at all.  Is this expected?

As for the rating pages themselves, I've randomly opened a few of them to see if they exist, but I focused mostly on those with pagination. Here, same as in the case of categories, I found an inaccuracy. 

Inaccurate pagination:
https://addons-dev.allizom.org/en-US/firefox/addon/lastpass-password-manager/reviews/ - 16 pages of reviews in the sitemap while only 6 reviews are returned by the ratings API.

**Comment by eviljeff** [comment]
> @eviljeff I found add-on ratings added to https://addons-dev.allizom.org/sitemap.xml?section=addons&p=3&debug and `?section=addons&p=4&debug`. All add-on review pages seem to be present in the sitemap, including those with no ratings at all. Is this expected?

it's how I wrote it... but I assumed the review page would always be present even for addons without any ratings.  Now I'm not sure about that.  Do we not display the page for addons with 0 ratings?  Do non-textual ratings count?

> As for the rating pages themselves, I've randomly opened a few of them to see if they exist, but I focused mostly on those with pagination. Here, same as in the case of categories, I found an inaccuracy.
> 
> Inaccurate pagination:
> https://addons-dev.allizom.org/en-US/firefox/addon/lastpass-password-manager/reviews/ - 16 pages of reviews in the sitemap while only 6 reviews are returned by the ratings API.

That's a weird one - the [API reports](https://addons-dev.allizom.org/api/v5/addons/addon/support@lastpass.com/) there are 386 ratings (385 text), so that's where the 16 pages comes from.  But there aren't actually that many.

**Comment by AlexandraMoga** [comment]
> it's how I wrote it... but I assumed the review page would always be present even for addons without any ratings. Now I'm not sure about that. Do we not display the page for addons with 0 ratings? Do non-textual ratings count?

We do display the ratings page for add-ons with 0 ratings, but it's just an empty page. So the page exists, but doesn't contain any useful information:

![image](https://user-images.githubusercontent.com/31961530/117261922-641ee200-ae59-11eb-8e92-8150be7fc9ea.png)

Also, the frontend does count ratings without a written review and those ratings will appear on the all reviews page like this:

![image](https://user-images.githubusercontent.com/31961530/117262616-22426b80-ae5a-11eb-91bb-0756d9da0402.png)

**Comment by eviljeff** [comment]
> 
> 
> > it's how I wrote it... but I assumed the review page would always be present even for addons without any ratings. Now I'm not sure about that. Do we not display the page for addons with 0 ratings? Do non-textual ratings count?
> 
> We do display the ratings page for add-ons with 0 ratings, but it's just an empty page. So the page exists, but doesn't contain any useful information:

if the page exists and we link to it then we have to include it (unless we take a decision to exclude it entirely from search engines with robots.txt but that'd be a different, more difficult, change)

**Comment by eviljeff** [comment]
> That's a weird one - the [API reports](https://addons-dev.allizom.org/api/v5/addons/addon/support@lastpass.com/) there are 386 ratings (385 text), so that's where the 16 pages comes from (not actually the API, but the underlying denormalized field in the db). But there aren't actually that many ratings returned from an API request for ratings.

the counts weren't up to date (it's dev... so anything could have happened).  I've reset them so they're accurate now. If we see this happening on prod we need to look into it further (the problem and fix would be to ensure the counts are up to date, rather than the sitemap specifically)

**Comment by AlexandraMoga** [comment]
The page count for https://addons-dev.allizom.org/en-US/firefox/addon/lastpass-password-manager/reviews/ is now correct in the sitemap.
