### ISSUE TITLE
stream sitemap files with FileResponse 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16985]
We're just using standard `HttpResponse` currently and that can be slow with large files, according to docs.  (It's unclear what is "large" but our sitemap files may multiple MB)

**Comment by AlexandraMoga** [comment]
As mentioned in https://github.com/mozilla/addons-server/issues/16508#issuecomment-823226187, I've noticed slowness with the `?section=addons` pages before. When I'm loading them now, they do seem to load a bit faster. For example, previously, even if the document appeared to be loaded, when I scrolled down through the returned items, I've noticed that they weren't actually loaded yet. Now, after the document is loaded, I can see all the available items when I'm scrolling down.

@eviljef I'm not sure if there is anything else I could verify for this issue.

**Comment by eviljeff** [comment]
I think that's all - as long as the content is the same as before.
