### ISSUE TITLE
Update shelves - collections shelves with themes

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-server#16997]
Admin is unable to create collection homepage shelves when 'Theme (Static)' is selected in `addon_type`.

The admin receives a validation error directing them to check the form fields as 'Theme (Static)' is selected for `addon_type`. However, as the criteria field for collections is the slug, it would not include `type=statictheme` in its field. 

Note: admin is able to create the following shelves:
- `search` endpoint with `addon_type` extension
- `search` endpoint with `addon_type` statictheme
- `collections` endpoint with `addon_type` extension

**Comment by ioanarusiczki** [comment]
@xlisachan I was able to create and add to homepage [shelf](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/63/change/) on AMO dev using the module, with endpoint:collections and Themes(Static) as Addon type. 

It is visible on frontend and I added the problems that occur with it into https://github.com/mozilla/addons-frontend/issues/10438
