### ISSUE TITLE
migration needed for existing `Shelf`s

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17005]
#16967 changed what values of `endpoint` were valid, but didn't include a migration for existing data, and added a new column for addon type that should have varied depending on the value of `endpoint`.  

e.g. a `Shelf` with `endpoint=search-themes` is now still `endpoint=search-themes` (`search-themes` is no longer a valid value for endpoint so returns `addons=None`), with an `addon_type=amo.ADDON_EXTENSION` (rather than `ADDON_STATICTHEME`).  We need a db migration that updates those records.

**Comment by eviljeff** [comment]
This **needs** to be fixed before the next prod deploy or the homepage will have empty shelves.

**Comment by eviljeff** [comment]
QA: because addons-dev was already fixed this won't be testable until the code is on stage.  (if you see this beforehand it might be good to double-check there is a `search-themes` shelf on there already, so it can be verified it's migrated correctly)

**Comment by AlexandraMoga** [comment]
We currently have two shelves active on AMO stage homepage which rely on the `search-themes` endpoint - the Popular themes and Recommended themes shelves. We'll check them when the new code lands on stage next week (it will be Wednesday for us).

**Comment by AlexandraMoga** [comment]
@eviljeff both the Recommended themes and the Popular themes shelves are being rendered on AMO stage homepage (with the functional issue that is currently handled in https://github.com/mozilla/addons-frontend/pull/10497).
In /shelfmodule/ admin they seem to have been switched to the new `endpoint` + `addon_type` format - i.e. `search` + `statictheme`. 
I assume this means that the migration took place?

**Comment by eviljeff** [comment]
@AlexandraMoga yes.
