### ISSUE TITLE
Transparency in user generated content should be converted to the same colour as the details page background

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#17028]
### Describe the problem and steps to reproduce it:

If you upload a `png` screenshot which is nothing but a black or dark outline with transparency, when the image is converted to jpeg the png's transparent background becomes solid black by default. 

### What happened?

The preview shows the image uploaded as a png with a transparent background. However post conversion this turns into a completely black image.

### What did you expect to happen?

Ideally we'd change the conversion to use a background for the jpeg that is equivalent to the transparency. Which should be possible by "pasting" the image onto a fill of our chosen colour via the image api.

An alternative would be to have the preview match the output of the jpeg conversion, but I would think a light background for transparency would  better reflect what's been happening prior to the png -> jpeg conversion.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Screenshot of edit screen after selecting image:

<img width="680" alt="Edit_Product_Page____favicon-customizer____Add-ons_for_Firefox" src="https://user-images.githubusercontent.com/1514/116264184-ffd19380-a771-11eb-97cf-68a702bae444.png">

Screenshot of details page post conversion:

<img width="1389" alt="favicon-customizer_–_Get_this_Extension_for_🦊_Firefox__en-US_" src="https://user-images.githubusercontent.com/1514/116264088-e92b3c80-a771-11eb-97c8-c990fe75b189.png">

**Comment by willdurand** [comment]
I'd like us to run `process_addons --task=recreate_previews` in order to fix the affected previews.

@mozilla/addons-amo-engineering thoughts?

**Comment by AlexandraMoga** [comment]
@eviljeff I've uploaded several transparent `.png`s to [this addon](https://addons-dev.allizom.org/en-US/firefox/addon/min-max/) but I'm still seeing a black background for each of them:

[devhub]
![image](https://user-images.githubusercontent.com/31961530/117465741-ab40cc00-af5a-11eb-97c1-e9a37b3e9180.png)

[detail page]
![image](https://user-images.githubusercontent.com/31961530/117465903-d1666c00-af5a-11eb-8733-6de11259e708.png)

**Comment by eviljeff** [comment]
it worked for the test image https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/tests/images/transparent.png 😞 

Can you attach some of the broken images because it's seemingly some subset of pngs it's not working for.  (256 colors vs.  not?)

**Comment by AlexandraMoga** [comment]
@eviljeff the test image worked for me as well.
Here are some of the images I've used:
[transparent background.zip](https://github.com/mozilla/addons-server/files/6450001/transparent.background.zip)

**Comment by AlexandraMoga** [comment]
I think this issue should be re-opened until a fix for the rest of the images is implemented.

**Comment by eviljeff** [comment]
(Eventually) found the bug.  We were testing if the white background was needed based on source file ending `.png` but the preview upload is stored as a temporary file at that point, without any file extension, so it didn't actually trigger.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/118670759-92100900-b7ff-11eb-9de3-9e69a03c7fdf.png)

https://addons-dev.allizom.org/en-US/firefox/addon/something-simple/
![image](https://user-images.githubusercontent.com/31961530/118670775-963c2680-b7ff-11eb-9961-03248c6a10fa.png)

**Comment by willdurand** [comment]
@AlexandraMoga do you have an add-on on -dev or -stage where the preview isn't correct? (because of this issue). I would like to run a command to fix the existing previews.

**Comment by willdurand** [comment]
@AlexandraMoga I ran the command to fix those add-ons in -dev and -stage.

**Comment by AlexandraMoga** [comment]
The images for those add-ons look fixed now.
