### ISSUE TITLE
Add button for theme isn't aligned in search results if name is longer thant one line

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1703]
STR:
1) Open a theme results page with themes that have long names. [This one should do](https://addons.mozilla.org/en-US/firefox/search/?q=madonna&cat=themes).
2) Hover over a search result that has a name that spans more than one line.

Result:
The Add button isn't aligned with the bottom left of the theme preview, and overlaps with the theme name. This can make you accidentally install a theme when you just wanted to go to its page.

**Comment by ValentinaPC** [comment]
Issue is also reproducing for long usernames.
Please see the screencast: http://screencast.com/t/2ghyJuxal

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-02-24_1847](https://cloud.githubusercontent.com/assets/15685960/13293133/17a2f9bc-db27-11e5-9b18-5817d8aef8be.png)
