### ISSUE TITLE
Blocking a deleted version should not cause a rejection action

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17035]
### Describe the problem and steps to reproduce it:

I noticed on prod that a version that had already been deleted received a rejection action when it got blocked.

Anticipated STR:
1. Submit a version
2. Delete it from the devhub
3. Block the deleted version.

### What happened?

On the reviewer tools page that a _Rejected_ action was recorded as part of the block.

### What did you expect to happen?

No _Rejected_ action since the file has already been deleted.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

@ioanarusiczki or @AlexandraMoga wouuld you mind checking if you can confirm this on -dev using the STR above, please?

**Comment by AlexandraMoga** [comment]
@wagnerand I confirm that the above steps can be reproduced on -dev. Here are some examples:

1. Add-on with version deleted in DevHub and block submitted for the deleted version:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/read-binary-png
2. Add-on deleted in DevHub and then fully blocked:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/493768

**Comment by AlexandraMoga** [comment]
In similar terms - https://github.com/mozilla/addons-server/issues/16455

**Comment by wagnerand** [comment]
@AlexandraMoga Sorry, I didn't see you had already filed an issue. Feel free to close one :)

**Comment by AlexandraMoga** [comment]
Yes, they are just similar. I've referenced it in the idea that it might be addressed when your issue is fixed, or the other way around.

**Comment by eviljeff** [comment]
@wagnerand are you going to take this too?  Seems like it'd be the same fix as #16455 (add a condition on rejecting versions so only approved + pending versions are rejected)

**Comment by AlexandraMoga** [comment]
Deleted versions - as well as disabled versions, will no longer be Rejected when a block is submitted:

![image](https://user-images.githubusercontent.com/31961530/181018354-a55edc13-2f2a-40f9-98b5-1e6de991485b.png)


Approved and Awaiting Review versions will continue to be Rejected when a block is submitted.

This issue is verified fixed on -dev.
