### ISSUE TITLE
Update API docs for the homepage shelve endpoint

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17038]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#homepage-shelves

### What happened?

We can see:

> results[].headline (object|null) – The title of the shelf. (See translated fields. Note: when lang is not specified, not all locales will be returned, unlike other translated fields).

and

> results[].cta.text (object|null) – The optional text in the footer of the shelf. (See translated fields. Note: when lang is not specified, not all locales will be returned, unlike other translated fields).

### What did you expect to happen?

The API returns the following response:

```json
{
  "title": {
    "en-US": "Recommended extensions"
  },
  "url": "https://addons.allizom.org/api/v5/addons/search/?promoted=recommended&sort=random&type=extension",
  "endpoint": "search",
  "addon_type": "extension",
  "criteria": "?promoted=recommended&sort=random&type=extension",
  "footer": {
    "url": null,
    "text": {
      "en-US": "See more recommended extensions"
    },
    "outgoing": null
  }
  // ...
}
```

**Comment by kanish671** [comment]
Hi! If I understand correctly, I need to update the API documentation to reflect the actual API response that is being returned. 
I would like to pick this up if my understanding is right.
