### ISSUE TITLE
Suggestion: Add source code link on add-on pages

### ISSUE THREAD

**Issue by DarkTrick** [mozilla/addons-server#17047]
### Abstract
On the page to install an add-on, add an link to the zip file containing the sources of that add-on. This way, users can check the source code easily and check if they trust it.

### Problem:
Getting the source code of an add-on is no obvious task. One has to explicitly download the xpi file and rename it to to *.zip. This is a problem for "untrusted" add-ons, that are not verified by Mozilla. The install page of these add-ons show a warning like: "make sure you trust the source..."; However, the site does not provide obvious means to check, if one trusts the source (i.e. a link to the source code).

### Suggestion
- Show a link to the *current source code* (i.e. a link to the zip file, that is identical to the xpi file) of an addon. 
- Placement: In case of an "untrusted add-on", place the link very close to the warning message "make sure you trust the source of this add-on".

### Distinction to other reports
This is not a duplicate of [Add DevHub and API support for URL to source code repository](https://github.com/mozilla/addons-server/issues/15174), which requests a URL to the source code repository (which might be not in sync to what is inside the xpi file). Opposing, this report requests a URL to the actual current code, that is contained inside the add-on.

**Comment by jvillalobos** [comment]
As @eviljeff mentioned on your conversation on Matrix, this is targeting a very slim audience: not only is this person willing and able to inspect the code of the add-on package, but they also wouldn't trust a source code repo, **and** they wouldn't be able to figure out an XPI is just a ZIP. I don't think this is worth the effort, so I'm closing it. https://github.com/mozilla/addons-server/issues/15174 is a better approach, and even that has gotten very little attention from the community.
