### ISSUE TITLE
don't include sitemap eula/privacy pages for empty policies

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17046]
follow-up for #16907 

the sitemap adds a page for each addon that has a `.eula` or `.privacy_policy` set.  As these are translated fields the code currently just checks if the field_id has a non-`None` value, i.e. it has been set.  This turned out to be a bit naive as we have less than ideal data in a our database - some of the translations are set to `''`.

(In an ideal world translations instances of '' wouldn't exist. It's near-impossible to get an accurate number of how many eula or privacy policy specifically this has happened for, but addons-dev has 1.6M translations set to '', for all translated fields, including some old deleted content)

**Comment by AlexandraMoga** [comment]
The missing `eula` and `privacy` pages I've listed in https://github.com/mozilla/addons-server/issues/16907#issuecomment-828235103 are no longer present in the sitemap (these pages are now pushed to https://addons-dev.allizom.org/sitemap.xml?section=addons&p=3&debug)

I've also picked a few more random eula and privacy pages and I didn't find empty entries.
