### ISSUE TITLE
Update API docs for the Homepage Shelves Editorial Content endpoint

### ISSUE THREAD

**Issue by kanish671** [mozilla/addons-server#17055]
### Describe the problem and steps to reproduce it:
Go to https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#homepage-shelves-editorial-content

### What happened?

We can see 
> 
        results (array) – The array of shelves displayed on the AMO Homepage.

        results[].headline (string|null) – The title of the shelf.

        results[].url (string) – The configured URL using the shelf’s endpoint and criteria; links to the shelf’s returned add-ons.

        results[].endpoint (string) – The endpoint type selected for the shelf.

        results[].criteria (string) – The criteria for the addons in the shelf.

        results[].footer_text (string|null) – The optional text in the footer of the shelf.

        results[].footer_pathname (string|null) – The optional pathname of the URL for the footer’s text.

### What did you expect to happen?

The [API](https://addons.mozilla.org/api/v5/shelves/editorial/) returns the following response

```
{
  "results": [
    {
      "title": "Recommended extensions",
      "footer_text": "See more recommended extensions"
    },
    {
      "title": "Popular themes",
      "footer_text": "See more popular themes"
    },
    {
      "title": "Enhanced privacy extensions",
      "footer_text": "See more enhanced privacy extensions"
    },
    {
      "title": "Popular extensions",
      "footer_text": "See more popular extensions"
    },
    {
      "title": "Recommended themes",
      "footer_text": "See more recommended themes"
    },
    {
      "title": "Recommended password managers",
      "footer_text": "See more recommended password managers"
    }
  ]
}
```

**Comment by AlexandraMoga** [comment]
The API docs for `/shelves/editorial` are showing the correct JSON response structure.
