### ISSUE TITLE
Update generic extension icon

### ISSUE THREAD

**Issue by htwyford** [mozilla/addons-server#17080]
### Describe the problem and steps to reproduce it:
Firefox 89 will update the generic icon for add-ons that don't define an icon. We should update the equivalent icons on AMO so Firefox and AMO are in sync. The AMO icons are https://addons.cdn.mozilla.net/static/img/addon-icons/default-64.png and friends. 

### Anything else we should know?
Please see https://phabricator.services.mozilla.com/D114008 for context. The new icon is [here](https://searchfox.org/mozilla-central/source/toolkit/themes/shared/extensions/extensionGeneric.svg). That icon is optimized for display at 16px. We also have a slightly different icon for display at 20px:
```
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="20" height="20" fill="context-fill" fill-opacity="context-fill-opacity">
  <path d="M15.5 5 13 5l0-2.5a2.5 2.5 0 1 0-5 0L8 5 4.5 5A2.5 2.5 0 0 0 2 7.5l0 1.9.6.6 1.893 0a2 2 0 0 1 0 4L2.6 14l-.6.6 0 2.9A2.5 2.5 0 0 0 4.5 20l11 0a2.5 2.5 0 0 0 2.5-2.5l0-10A2.5 2.5 0 0 0 15.5 5z"/>
</svg>
```
cc @muffinresearch

**Comment by htwyford** [comment]
Firefox 89 releases June 1, so it would be good to time this change for around then.

**Comment by willdurand** [comment]
> Please see [phabricator.services.mozilla.com/D114008](https://phabricator.services.mozilla.com/D114008) for context. The new icon is [here](https://searchfox.org/mozilla-central/source/toolkit/themes/shared/extensions/extensionGeneric.svg). That icon is optimized for display at 16px. We also have a slightly different icon for display at 20px:

@htwyford would you have a version for 32px and 64px by chance?

**Comment by jvillalobos** [comment]
As I understand it, we use the generic extension icon in two cases:
* As a fallback when an icon is loading or not available
* As the default icon when a developer doesn't have a custom icon for their listing. Like in [this case](https://addons.mozilla.org/addon/close-tabs-left/).

I agree that we should update the shape of the icon on AMO to maintain consistency, but I think the monochrome version doesn't fit the style of the site very well. We should either use the cyan version that `about:addons` uses when the extensions pane is selected, or a green version that matches the color we've been using for many years now.

**Comment by eviljeff** [comment]
we can edit the svg to be a different colour easily enough.  The green puzzle piece is ~ #59b106 and the cyan we use for the favicon on AMO is #66c5d4 (Not sure if that's the exact same as the `about:addons` cyan)

**Comment by jvillalobos** [comment]
Great. I'd like to see 64px version for those colors to get a better idea of how it would look.

**Comment by eviljeff** [comment]
Using the svg provided:
![extensionGeneric-green](https://user-images.githubusercontent.com/768592/117270517-33d34580-ae51-11eb-8894-61bbec12b209.png)
![extensionGeneric-amocyan](https://user-images.githubusercontent.com/768592/117270511-333aaf00-ae51-11eb-8016-ebcfa67e13ec.png)
![extensionGeneric-fxcyan](https://user-images.githubusercontent.com/768592/117270515-33d34580-ae51-11eb-874e-2f0fedd43e0a.png)

(I don't know if there's a more detailed svg available?  This one is pretty simplistic)

**Comment by jvillalobos** [comment]
I think the bottom one looks good for the general style of the site. In a way it's good that the default icon isn't so appealing since it should encourage developers to set a custom one.

**Comment by htwyford** [comment]
> @htwyford would you have a version for 32px and 64px by chance?

Unfortunately not. UX prioritized icon-sized images for Fx89. I can ask them if this size is okay to use or if we should wait for a larger, more detailed image.

**Comment by willdurand** [comment]
> I can ask them if this size is okay to use or if we should wait for a larger, more detailed image.

@htwyford thanks. I think we need to know if (1) this is the icon for larger sizes or if we need a more detailed one and (2) if the last icon in https://github.com/mozilla/addons-server/issues/17080#issuecomment-83335734 looks good for AMO (given that the monochrome version wouldn't look good on AMO)

**Comment by htwyford** [comment]
From KatieC on Proton UX:

> [the current icon] sort of a candy gloss icon with a drop shadow, wasn’t the exact same as shape the extensions icon we just replaced from Photon, it’s much more illustrative in style, it’s mirrored and chunkier. While I think it would be ok to replace with the new icon, it may be more of a branding/product conversation about the intention of the placeholder version?  (Ex: in release now, you can see 2 distinct puzzle images are present: Fx - ui element in sidebar navigation and generic placeholder image. There may be value in having them look different?)
![image(2)](https://user-images.githubusercontent.com/1606496/117374226-c3511680-ae9a-11eb-8d51-82c1cda099f0.png)

So you may want to consult with AMO product/UX. Making the icon a different color may be enough, but I'm not sure.

**Comment by willdurand** [comment]
@jvillalobos if I understand correctly, you're OK with the new icon shape with a different color (cyan) so from a Product perspective, we do have an answer.

Could we get UX approval on this then? It looks like there are two questions:

- is the icon shape OK for larger icons (32/64px)?
- is the cyan color OK?

Thanks!

**Comment by jvillalobos** [comment]
Yes, I'm okay using the same icon consistently across the board, given that it's meant to be a default and most extensions (at least the ones we care most about) have their own custom icon. I'll ask for UX confirmation on these questions.

**Comment by jvillalobos** [comment]
Got confirmation from UX that we can move forward with changing the icon, but we should stick to the green color.

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO stage with FF88 and Chrome (Win10):

Dev hub:

![icon on manage my submission](https://user-images.githubusercontent.com/33448286/120475645-7d368800-c35e-11eb-9d34-a1edbc60d816.png)

![icons images](https://user-images.githubusercontent.com/33448286/120476060-02ba3800-c35f-11eb-9f88-1d816faf1819.png)

![icon on dev hub](https://user-images.githubusercontent.com/33448286/120476372-5e84c100-c35f-11eb-9c84-0cdb50825fba.png)

![review page](https://user-images.githubusercontent.com/33448286/120476625-a4418980-c35f-11eb-8ddf-40a337f39d01.png)

**Comment by ioanarusiczki** [comment]
@eviljeff Looking again, maybe on /developers page the icon could be better aligned, so I filed https://github.com/mozilla/addons-server/issues/17255
