### ISSUE TITLE
Have nginx serve sitemap files directly

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17092]
Our sitemap views serve a file pre-generated by a crontab and stored on EFS. That is currently being done [in django](https://github.com/mozilla/addons-server/blob/e04977041557680a8f978c1ff0e6fddaea8f138b/src/olympia/amo/views.py#L201-L223): we open the file, read it, return the contents (and set `Last-Modified`).

To speed things up, we could try 2 different approaches:
- The first one to try is using our `HttpResponseXSendFile` to let nginx read the file through `X-Accel-Redirect`. We'd need to also not set `Last-Modified` ourselves and ensure nginx does it for us (to avoid even the `os_stat` call on the file in django)
- If that turns out not to be enough, we could rework the way we store the files and store them in S3 instead of EFS, and have nginx directly serve the sitemap from S3 like we do for the blog (completely bypassing django: we wouldn't even need a django view at all).

**Comment by willdurand** [comment]
> If that turns out not to be enough, we could rework the way we store the files and store them in S3 instead of EFS, and have nginx directly serve the sitemap from S3 like we do for the blog (completely bypassing django: we wouldn't even need a django view at all).

When we discussed this on Slack, @eviljeff mentioned that sitemap urls have query parameters that are used to load the right files from disk in the django view. This makes the setup a bit more complex than for addons-blog but it should be possible to port [the existing](https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/sitemap.py#L321) logic to the nginx config.

**Comment by eviljeff** [comment]
it may be possible to compose a suitably complex regex in the nginx for the filename that would do away with need for query parameters. The need is just that the number of files we wills serve is undefined at the point the nginx config is written (e.g. we don't know how many pages will be generated by the cron)

**Comment by diox** [comment]
I think it would be really beneficial to avoid that call to spend the least amount of time in Django. If that means simplifying the logic behind the `cache-control`/`expires` let's do it.

**Comment by bqbn** [comment]
How are the sitemap files generated and in what frequency?

**Comment by eviljeff** [comment]
> How are the sitemap files generated and in what frequency?

they will be generated with the `write_sitemaps` cron job #16906 - planned to be every 24 hours.

**Comment by AlexandraMoga** [comment]
@eviljeff is there something more specific that should be verified for this issue? I've verified that the various sitemap sections are still loading as before and I did notice that, if `&debug` is omitted - like in this example https://addons-dev.allizom.org/sitemap.xml?section=collections&app_name=firefox - a 404 from nginx is triggered.

**Comment by eviljeff** [comment]
@AlexandraMoga that all the urls are still working as before is enough - hopefully the files are slightly faster to download too.
