### ISSUE TITLE
amo-lib-locales-and-signing CI job is super slow, holding up other test verification

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17102]
the amo-lib-locales-and-signing job became super slow after we moved to circleci - the locale compilation step alone takes 10+ (15+ is not uncommon) minutes, which blocks you from seeing that your patch hasn't broken tests under `amo` or `lib` that don't require locale extraction.  

The actual solution is to work out why the extraction become so slow, and fix it, if possible.  In the interim, let's move the tests that don't need to wait for the extraction to other jobs.

**Comment by willdurand** [comment]
> the amo-lib-locales-and-signing job became super slow after we moved to circleci

This isn't accurate, it was quite fast when we moved to Circle. We found out that the patch to remove `tox` was actually the culprit: https://github.com/mozilla/addons-server/issues/16445
