### ISSUE TITLE
drop custom eula/privacy polices from sitemap (revert #16984 -ish)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17111]
as per #16910

> > we have those in the sitemap currently - it seemed like valid content?
>
> Valid content yes but apparently not useful enough to be indexed, see:
>
>    mozilla/addons-frontend#5758
>    mozilla/addons-frontend#1828 (comment)
>    mozilla/addons-frontend#3697 (comment)

**Comment by AlexandraMoga** [comment]
I've looked through the `/firefox/` and `/android/` add-on pages in the sitemap and I did not find entries for `/license/`, `/eula/` or `/privacy/`

This issue is verified fixed on -dev.
