### ISSUE TITLE
Delete fake emails after X months

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17122]
On -dev, I noticed that we still have fake emails from 2017. We should probably delete them after a few months (maybe 2-3 months or even 1?). @diox suggested to remove these fake emails in the `gc` CRON.

**Comment by iamvaishnav** [comment]
I'd like to work on this one. However, I don't know how to get started.

**Comment by diox** [comment]
Fake emails are stored in the database through the `FakeEmail` model. Like (almost) all our models, it has a `created` field, so you should be able to build a queryset to retrieve any fake emails older than 3 months. From there, you can use that queryset to delete them in the `gc` function of `src/olympia/amo.cron`. It's launched every date automatically.

The `gc` function also has a nice `days_ago()` helper to help you build the query, as well as examples of other things we delete after some time.

**Comment by iamvaishnav** [comment]
Thanks. I'm working on it

**Comment by ioanarusiczki** [comment]
@diox I verified fake e-mails on dev and stage. e-mails older than 3 months have been deleted
