### ISSUE TITLE
The sitemap throws a 500 error if the requested resource doesn't exist

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17121]
### Describe the problem and steps to reproduce it:
Open the following sitemap page: https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=android&p=250&debug

### What happened?
You get a 500 error

### What did you expect to happen?
A 404 error, since the requested page - `section=addons&app_name=android&p=250` - doesn't exist

### Anything else we should know?
Another way to reproduce the error is by requesting an non-existent section: https://addons-dev.allizom.org/sitemap.xml?section=category&app_name=firefox&debug

**Comment by eviljeff** [comment]
note, because only `?debug` generates the sitemap in real-time this is only possible locally or on addons-dev.

We should probably do what django's sitemap view does and catch the page error and raise it as Http404 https://github.com/django/django/blob/3.2/django/contrib/sitemaps/views.py

**Comment by AlexandraMoga** [comment]
The sitemap is now triggering a 404 error, displaying the corresponding not found page:

![image](https://user-images.githubusercontent.com/31961530/118622643-2f534900-b7d0-11eb-960a-9cf346a59605.png)


This issue is verified fixed on -dev.
