### ISSUE TITLE
Layout issue for long caption screenshot preview

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1712]
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/firefox/
2. Go to Edit Listing -> Images for any submitted listed add-on (i.e. https://addons.allizom.org/en-US/developers/addon/unlimited-free-vpn-test2/edit)
3. Add a long caption for an add-on screenshot and save
4. Click the  "View Listing" link 
5. Click on the screenshot with long caption

**Expected results:**
There are no display or layout issues.

**Actual results:**
There is a layout issue in what concerns the screenshot caption.

Notes/Issues:
Verified on FF44(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue: 
![2016-02-18_1219](https://cloud.githubusercontent.com/assets/15685960/13140311/def938e8-d639-11e5-9815-568ce6edc583.png)

**Comment by designakt** [comment]
Let's do this:

#lightbox .caption {
    font-size: 16px;
    margin: auto 50px;
    height: 64px;
    overflow-y: auto;
    line-height: 56px;
}
#lightbox .caption span {
    line-height: 21px;
    display: inline-block;
    vertical-align: middle;
}
#lightbox .control, 
.previews .control {
    width: 50px;
}

Which results in a (not so nice) scroll-bar for text longer than 3 lines, but at least keeps all text readable and prevents the prev/next buttons from covering text.

![capture2](https://cloud.githubusercontent.com/assets/8145891/14560646/501843b2-0311-11e6-91e0-8e18ad473b86.PNG)
![capture1](https://cloud.githubusercontent.com/assets/8145891/14560645/500e587a-0311-11e6-99a8-eae2d3812589.PNG)

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

Mentor: @tofumatt 

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by VishalCR7** [comment]
@eviljeff I would like to work on this !

**Comment by eviljeff** [comment]
@VishalCR7 This is for our legacy frontend, so it's not worth working on.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
