### ISSUE TITLE
`TestTasks.test_sign_mail_cose_subject` failed

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17137]
There was no code change involved, which is super weird.

```
src/olympia/lib/crypto/tests/test_signing.py:680: in test_sign_mail_cose_subject
    assert 'stronger signature' in mail.outbox[0].message().as_string()
E   IndexError: list index out of range
        mock_sign_file = <MagicMock name='sign_file' id='140032883969040'>
        self       = <olympia.lib.crypto.tests.test_signing.TestTasks testMethod=test_sign_mail_cose_subject>
```

See: https://app.circleci.com/pipelines/github/mozilla/addons-server/17211/workflows/af2da5e2-5e58-451b-bc6a-42bdea15e03b/jobs/70163

**Comment by eviljeff** [comment]
I've not seen this or #17138 since this was logged (or previously).  If it's not happening any more we can probably close these?  (which is usually the trigger for it to happen again!)
