### ISSUE TITLE
Stop exposing license text in versions API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17163]
The versions list API exposes the license text for each version returned, which is wasteful. We should only return it for the version detail endpoint. This would speed up the add-on versions page endpoint as mentioned in https://github.com/mozilla/addons-frontend/issues/10446.

For backwards-compatibility we should only do this in v5, at least for now. Ideally we should also `defer` the field in the ORM to avoid even fetching the text from the database.

**Comment by bobsilverberg** [comment]
Do we need a related issue for addons-frontend to deal with the fact that this will be missing?

**Comment by diox** [comment]
I *think* it should already work:
And the various types defined have `text` as optional, and we have this:
https://github.com/mozilla/addons-frontend/blob/8ad42e516ff9dd81c5a05d35b44b36f16b644ff8/src/amo/reducers/versions.js#L138-L141

In addition, it looks like the `text` property is never accessed by the `AddonVersions` page or its components (which makes sense, given we only seem to display it when the user visits the special link to display the text of a custom license).

Let me know if I'm wrong though.

**Comment by bobsilverberg** [comment]
> I _think_ it should already work:
> And the various types defined have `text` as optional, and we have this:
> [mozilla/addons-frontend@`8ad42e5`/src/amo/reducers/versions.js#L138-L141](https://github.com/mozilla/addons-frontend/blob/8ad42e516ff9dd81c5a05d35b44b36f16b644ff8/src/amo/reducers/versions.js#L138-L141)
> 
> In addition, it looks like the `text` property is never accessed by the `AddonVersions` page or its components (which makes sense, given we only seem to display it when the user visits the special link to display the text of a custom license).
> 
> Let me know if I'm wrong though.

It does look like we indeed do not use `text` on the `AddonVersions` page, so that's good. I notice, however, that that code in the reducer is specifically looking for `undefined`. Will we be getting `undefined` back from the API now, or might it be `null`?

**Comment by diox** [comment]
You'll get `undefined`, the key won't even exist in the object in the JSON.

**Comment by bobsilverberg** [comment]
> You'll get `undefined`, the key won't even exist in the object in the JSON.

Prefect! Thanks.

**Comment by diox** [comment]
QA:
- License `text` should be gone for the [version list API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#versions-list) in v5
- It should still be present in v3/v4
- It should still be present in the version detail API (single version as opposed to a list of multiple versions) for v3/v4/v5
- The add-on versions list page should continue to work, displaying all versions and the links to their licenses (with their names) correctly
- The version license page (linked from the add-on versions list for custom licenses) should still work and display the license text
- Translations of those pages should still work correctly.

**Comment by ioanarusiczki** [comment]
@diox 
- `text` is no longer available in version list API for v5. 
- v3/v4 are still displaying `text`.
- the version detail API displays `text` for v3/v4 and v5.
- add-on version list looks good.
- I found an issue about the custom license - filed it https://github.com/mozilla/addons-frontend/issues/10597. Text is displayed when page is opened. 
- translations look alright.
