### ISSUE TITLE
optimize Sitemap.items and how it's used

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17178]
django's Sitemap class generates the l10n variants of urls by repeatedly calling `.items`, which executes a database query each time.  This is very inefficient  (In theory the query would be internally cached by the django ORM; in practise it doesn't appear to be happening - or it's being cached by still slow because of other stuff that happens to generate the return contents of `.items`)

**Comment by AlexandraMoga** [comment]
@eviljeff I've been loading various sitemap sections and now the load times are looking a bit better - between 4 sec and 5 sec.

The root sitemap - https://addons-dev.allizom.org/sitemap.xml?debug -  is still a bit slow - around 13 sec in my case.

**Comment by eviljeff** [comment]
Note we only care about how fast the eventual static files are served (by nginx these days) which is more a function of file size, and that we can generate the files in a cron job in a reasonable-ish amount of time each day.  The `?debug` urls are only for debugging on addons-dev or locally - though if those requests are super slow then it's likely that the cron job would also be super slow.
