### ISSUE TITLE
View on site button is not working on django activity log entries

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17179]
STR:
1. Go to an activity entry such as https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4003686/change/ and click "View on site"

Results:
500 server error 

This is reproducible on AMO dev and stage - FF88(Win10).

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/11363925/?query=is%3Aunresolved

`view_on_site = False` in `ActivityLogAdmin` should fix it.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox 

@diox, could you also add some details on how to test the solution?

**Comment by diox** [comment]
Using the fix I propose the "View on Site" button should disappear from the activity log admin page, when viewing a single activity log. No need to include an unit test for this.

**Comment by rock420** [comment]
Hi @diox, I would like to fix this bug.
I need to do the change in this [class](https://github.com/mozilla/addons-server/blob/master/src/olympia/activity/admin.py#L6) right? please correct me if I am wrong

**Comment by diox** [comment]
Yes.
