### ISSUE TITLE
EW links are incomplete into emails sent to developers

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17188]
Checking 
https://github.com/mozilla/addons-server/issues/16753

These links have been updated:

    "https://developer.mozilla.org/Add-ons/Listing" should be:
    ** text-only version: "https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/"
    ** HTML version: "https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/?utm_source=email&utm_medium=submission-email"

    "https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews" should be:
    ** text-only version: "https://extensionworkshop.com/documentation/publish/add-on-policies/"
    ** HTML version: "https://extensionworkshop.com/documentation/publish/add-on-policies/?utm_source=email&utm_medium=submission-email"

The e-mails sent to developers look like:

![addon version update](https://user-images.githubusercontent.com/33448286/118932099-50db3e80-b950-11eb-9e04-f2d46e7a8b28.png)

**Comment by eviljeff** [comment]
as #16753 was reopened we don't need a separate tracking issue, so closing this.

**Comment by eviljeff** [comment]
fwiw, the problem here was that the emails are django templates (rather than jinja2 templates that we mainly use) and django templates don't have the `settings` object freely available in all templates -  any variable that's being referenced needs to be explicitly passed into the context.
