### ISSUE TITLE
The `absolutify` utility from `jinja_helpers` doesn't take into account https protocol

### ISSUE THREAD

**Issue by sergeyklay** [mozilla/addons-server#17189]
Hello,

As topic said, the `absolutify` utility from `jinja_helpers` doesn't take into account https scheme. Please take a look at the code (`'http://'` twice):

https://github.com/mozilla/addons-server/blob/6b0bac1e73f3579f115932517230adc9b40d6600/src/olympia/amo/templatetags/jinja_helpers.py#L186-L192

Also, I have to admit that the tests look somewhat cryptic to me. They don't cover all possible cases and incorrectly use the second form of `assert`:

https://github.com/mozilla/addons-server/blob/6b0bac1e73f3579f115932517230adc9b40d6600/src/olympia/amo/tests/test_helpers.py#L391-L395

**Comment by diox** [comment]
Thanks for the patch, @sergeyklay !

**Comment by sergeyklay** [comment]
You're welcome :)
