### ISSUE TITLE
Broken URLs for source code - when submitting an addon

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17181]
Followup for https://github.com/mozilla/addons-server/issues/16753

while making an addon submission - "source code submission policy" and "policy requirements" URLs are broken - it's a 404 for both of them on AMO dev and stage

this is what they open:
https://addons.allizom.org/en-US/developers/addon/a-patch/submit/%7B%7B%20settings.EXTENSION_WORKSHOP_URL%20%7D%7D/documentation/publish/source-code-submission/

**Comment by kanish671** [comment]
Looking into this now.

**Comment by kanish671** [comment]
https://github.com/mozilla/addons-server/issues/16753#issuecomment-844167502

I am trying to get the variable value there. I currently am not able to figure out how though. 
I think I will revert those two lines and look into fixing them later. Would that work?

**Comment by eviljeff** [comment]
as #16753 was reopened we don't need a separate tracking issue, so closing this.
