### ISSUE TITLE
Lang picker box could be wider a bit 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17197]
I've noticed the other days, the lang picker is pretty compact in dev hub too and it's been fixed for frontend https://github.com/mozilla/addons-frontend/issues/10524. Maybe it should be the same on server.

![langpicker](https://user-images.githubusercontent.com/33448286/119132806-d2f85f80-ba43-11eb-88a2-797ab7e8ba93.png)

**Comment by eviljeff** [comment]
fwiw, we've not changed any fonts or css on addons-server (we're still using Fira Sans on that page) - so if it's too narrow, it's likely been that way for a while.
