### ISSUE TITLE
The browser preview does not display the color into the tab

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17212]
Testing with the theme wizard I've noticed that while making a submission the preview generated does not exactly look like the final preview. 

I changed the Toolbar area background into a color (I picked green) -> 

The browser preview does not generate the green color into the tab:

![green](https://user-images.githubusercontent.com/33448286/119355815-8c308280-bc5a-11eb-86bb-06b12e82b42d.png)

at the end of the submission the tab is green:

![as it should be](https://user-images.githubusercontent.com/33448286/119355737-76bb5880-bc5a-11eb-852c-ce84bceb6576.png)

**Comment by eviljeff** [comment]
if someone takes this before I'm back: I think it's just a matter of adding `data-fallback="toolbar"` attribute to the `id="svg-selected-tab"` element. (not tested)

**Comment by ioanarusiczki** [comment]
@eviljeff Verified on AMO dev - FF89(WIn10). 

![theme preview is correct](https://user-images.githubusercontent.com/33448286/121015528-f283cd80-c74f-11eb-84e7-47c534449ed4.png)
