### ISSUE TITLE
You should be able to remove yourself as a developer from an add-on

### ISSUE THREAD

**Issue by mkaply** [mozilla/addons-server#1724]
I was added as a developer by the owner of an add-on and a few years later ended up no longer working on the add-on.

When I went into the authors/licenses for the add-on, I was unable to remove myself. I would have had to contact the owner (I ended up contacting AMO).

So the request is that if you are added as a developer on an add-on and you are not the only developer, you should be able to remove yourself.

**Comment by EnTeQuAk** [comment]
I feel like that's a feature that could get more complex and maybe there's a need for it or maybe not.

**Comment by eviljeff** [comment]
I agree it's a sensible request to be able to remove yourself, but at the same time I can't imagine it's that common where contacting another owner isn't an option - and amo-admins can handle those cases manually.  Short of evidence of a significant need I'd close.

**Comment by mkaply** [comment]
That's fine with me. Just wanted to make sure I reported it.
