### ISSUE TITLE
Disable auto-approval temporarily when an unlisted version is rejected.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17249]
For listed, we already temporarily disable auto-approval when a version was rejected, until the next manual approval. We should do the same for unlisted too.

**Comment by diox** [comment]
@wagnerand I don't remember where we left the discussion: should we follow `auto_approval_disabled_until_next_approval` like we do for listed, or make a new flag for unlisted?

**Comment by wagnerand** [comment]
> @wagnerand I don't remember where we left the discussion: should we follow `auto_approval_disabled_until_next_approval` like we do for listed, or make a new flag for unlisted?

Let's have a separate flag.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and these are my results:

Unlisted version rejections:
- the "Disable Unlisted Auto-Approval Before Next Manual Approval"  button changes to "Enable Unlisted Auto-Approval Before Next Manual Approval" when a version is rejected;
- "Notify me about new unlisted versions" is  automatically checked
- manually Approving an unlisted version will clear the flag - i.e. the "Enable Unlisted Auto-Approval Before Next Manual Approval" changes back to "Disable Unlisted Auto-Approval Before Next Manual Approval"

@diox it looks like this issue caused a regression with the "Listed Auto-Approval Before Next Manual Approval" button; I can no longer see this button being displayed on a listed review page; only the button for Unlisted is present; the functionality is still working for listed versions, it's just an issue with the buttons as far as I can tell:

[dev]
![image](https://user-images.githubusercontent.com/31961530/121200214-3c69d200-c87c-11eb-99ec-28ab190c422e.png)

[stage]
![image](https://user-images.githubusercontent.com/31961530/121200381-5b686400-c87c-11eb-9c60-66b7a451c43a.png)


Some observations regarding Unlisted version reviews:
- Block multiple versions 
  - this review action can be used to block and reject unlisted versions that have been Approved; 
  - the "Disable Unlisted Auto-Approval Before Next Manual Approval"  button changes to "Enable Unlisted Auto-Approval Before Next Manual Approval"
  - "Notify me about new unlisted versions" is _not_ automatically checked
  
- Reject multiple versions
  -  can be performed only on versions that are still Awaiting review; 
  - versions that are Approved will not be available for selection in the Reject multiple versions section, so this option doesn't have much use when all versions are already Approved

**Comment by diox** [comment]
@AlexandraMoga could you link the page where the button is missing ? The logic should be, the button should be shown for the review page on the corresponding channel (previously the button for listed was shown on both unlisted and listed review page)

**Comment by AlexandraMoga** [comment]
@diox this is one example - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/test-test-test-33 - but the same thing applies to any other listed review page.

**Comment by diox** [comment]
I see the problem, I'll submit a fix

**Comment by AlexandraMoga** [comment]
The "enable/disable auto-approval until next manual approval" buttons seem to be correct now:

[button for listed review pages]
![image](https://user-images.githubusercontent.com/31961530/121324012-fe6ebb80-c918-11eb-9acd-8d840b0120a3.png)

[button for unlisted review pages]
![image](https://user-images.githubusercontent.com/31961530/121324032-03336f80-c919-11eb-9753-d4389b1bab49.png)

Looking at this, I was wondering if the same logic could be applied to the Disable/Enable Auto-approval button. Right now, both buttons, for Listed and for Unlisted, will be displayed for each channel. @wagnerand what's your opinion on this as a possible follow up issue?
