### ISSUE TITLE
addon icon could be moved a bit higher

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17255]
This is how it looked before (could have been better aligned with the text here too):

![now on production](https://user-images.githubusercontent.com/33448286/120486322-c93afa00-c369-11eb-97af-5374cc4882c3.png)

This is how it looks like now:

![icon on dev hub](https://user-images.githubusercontent.com/33448286/120486410-e079e780-c369-11eb-978e-c7cfc1b41606.png)

with a custom icon:

![custom icon too](https://user-images.githubusercontent.com/33448286/120486692-2171fc00-c36a-11eb-8658-e0ee1a9d4547.png)

**Comment by eviljeff** [comment]
We discussed this in our good first bugs meeting and have decided to wontfix it
