### ISSUE TITLE
optimize Sitemap generation

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17258]
After executing the sitemap generation cron on addons stage the timings were:
~2 minutes to generate the sitemap.xml (index), where all 7 database queries were executed and the processed results cached.
~10 seconds for each addons page.

The sitemap.xml generation isn't fast (and should/could be optimized), but the real problem is the 10 seconds per page.  There should be ~22k pages on stage (according to the index), so to generate all the pages would take 36 hours!  (and we're planning to generate these files every _24_ hours...)

Optimization is a must.

**Comment by AlexandraMoga** [comment]
@eviljeff is there anything I could verify for this issue?

**Comment by eviljeff** [comment]
I guess just check the `?debug` urls on dev still work as before - they might be slightly faster but that's not the aim and probably not noticeable per request.

**Comment by AlexandraMoga** [comment]
The `?debug` sitemap urls seem to be working as before on -dev.
