### ISSUE TITLE
enable Sitemap.x_default option

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17251]
We'd like to enable `the Sitemap.x_default` property to write a `x-default` sitemap entry alternative but the django implementation is a bit simplistic - it just defines it as `settings.LANGUAGE_CODE` (`en-US` in our case) when we'd ideally want to have it defined per addon for addons (i.e. the x-default for a particular addon would be it's default_locale).

**Comment by eviljeff** [comment]
tempted to wontfix this, because I'm not sure we need the extra content in the xml.

On the implementation, if we want the `x-default` to always be `en-US` then it's a trivial fix but otherwise I can't see a way of implementing it other than copying the whole `_urls` method and changing just that part to retrieve it per add-on.

**Comment by willdurand** [comment]
> On the implementation, if we want the `x-default` to always be `en-US` then it's a trivial fix but otherwise I can't see a way of implementing it other than copying the whole `_urls` method and changing just that part to retrieve it per add-on.

I don't think we are ready for a `x-default` value other than `en-US`, see: https://github.com/mozilla/addons-frontend/blob/a693ec38fa245bacaed1250c863d124a58ad8c53/config/default.js#L251

**Comment by eviljeff** [comment]
oh, even less reason to generate the links then, I guess.

**Comment by eviljeff** [comment]
closing this for now.
