### ISSUE TITLE
Cache bust default icon

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17262]
I don't see the new icon on -dev (or -stage):

<img width="1552" alt="Screenshot 2021-06-02 at 18 13 53" src="https://user-images.githubusercontent.com/217628/120515118-4ac47380-c3ce-11eb-99c5-02f0a590655e.png">

This is because the default icon URL does not have a `modified` query parameter (or any other param) for cache busting. We should have something because even a hard refresh does not fix this problem.

**Comment by willdurand** [comment]
This is on Chrome:
<img width="1552" alt="Screenshot 2021-06-02 at 18 18 25" src="https://user-images.githubusercontent.com/217628/120515779-f2da3c80-c3ce-11eb-8db4-7935a619bb92.png">

**Comment by ioanarusiczki** [comment]
@willdurand 
I checked on FF88, Chrome, Edge - AMO dev and AMO stage display the new icon. 
I tried for FF with old/new profiles, they all display the new icon.
