### ISSUE TITLE
allow cron write_sitemaps to generate only a subset of sitemaps

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17273]
Currently `./manage.py cron write_sitemaps` generates and writes all the sitemaps.  Ideally, at least for debugging purposes, we'd want to be able to generate only a subset of these - e.g. only certain classes of sitemaps/apps  (maybe even an individual page?)

**Comment by AlexandraMoga** [comment]
I did some exploratory on the sitemap and I did not find issues.

I suppose this is all I could verify for this issue. If not, do let me know.
