### ISSUE TITLE
Add some more GUID patterns to system guid list

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17271]
There is at least one privileged extension with an ID ending in "@mozillafoundation.org", so we should add that pattern to the `SYSTEM_ADDON_GUIDS` list.

Edit: We need to add `@rally.mozilla.org` as well for future rally studies.

**Comment by ioanarusiczki** [comment]
- uploads for non-admin users are not possible when the GUIDs specified above are used:

![nonffuser](https://user-images.githubusercontent.com/33448286/121030272-019b6780-c7b2-11eb-8e7c-ff61c86a3a4c.png)

The condition is a Mozilla e-mail address and admin rights, which should be expected here. 

Verified on AMO dev - FF89(Win10).
