### ISSUE TITLE
Green to encourage add-on installation and yellow-and-black to discourage, not the other way around

### ISSUE THREAD

**Issue by wbt** [mozilla/addons-server#1727]
Creating a new issue per [this comment](https://github.com/mozilla/addons-server/issues/1726#issuecomment-186881578), with contents from [this one](https://github.com/mozilla/addons-server/issues/1726#issuecomment-186737579). 

[That GitHub issue](https://github.com/mozilla/addons-server/issues/1726#issuecomment-186648343) [encourages](https://github.com/mozilla/addons-server/issues/1726#issuecomment-186721166) readers to use the ["revived" version](https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager-revived/) of an add-on, but the the AMO interface encourages people to use [the original](https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager/) which is labeled "signed" and has the green Add to Firefox button, while "revived" has a cautionary black-and-yellow scheme as a warning indicating it might not be safe, and doesn't indicate it's signed. That kind of UI design encourages behavior that seems opposite the goal.

**Comment by amuntner** [comment]
+1 agree

**Comment by wbt** [comment]
"I understand what the different colors are trying to communicate and that's still something we need to communicate" - can you please elaborate on that, to make it easier to suggest something that might work?

**Comment by jvillalobos** [comment]
Green means fully reviewed, which yellow means preliminarily reviewed. They are different review levels held to different standards. The [Review Policies doc](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews) explains this in detail.

The "revived" variant of the add-on doesn't have full review yet. It's up to the developer to meet the full review bar and submit the add-on for that level of review so it gets the green button.

**Comment by amuntner** [comment]
Thanks Jorge. It sounds like the addon reported about is an edge case.
Probably 99% of grandfathered add-ons could be signed and still work fine
because they don't modify signed files. It wouldn't make sense to alter the
entire system for such edge cases since doing so would be a lot of work and
only exchange one trade-off for another.

On Mon, Feb 22, 2016 at 11:44 AM, Jorge Villalobos <notifications@github.com

**Comment by eviljeff** [comment]
This will be implemented on addons-frontend so closing this on addons-server.
