### ISSUE TITLE
SixOrNot extension's -128.png icon is 404 on addons.cdn.mozilla.net

### ISSUE THREAD

**Issue by cpeterso** [mozilla/addons-server#17288]
### Describe the problem and steps to reproduce it:

I installed an extension ("SixOrNot") from AMO: https://addons.mozilla.org/en-US/firefox/addon/sixornot/.

In my regular Firefox profile, about:addons fails to load this extension's icon. The devtools inspector says about:addons thinks the icon is `<img class="card-heading-icon addon-icon" alt="" src="https://addons.cdn.mozilla.net/user-media/addon_icons/309/309978-128.png?modified=1575646887">`, but that icon URL is 404.

In a new Firefox profile, the extension's icon loads correctly and about:addons thinks the icon is `<img class="card-heading-icon addon-icon" alt="" src="jar:file:///Users/chris/Library/Application%20Support/Firefox/Profiles/2atwgsif.default-nightly-1615273989379/extensions/sixornot@entropy.me.uk.xpi!/images/sixornot_icon_64.png">`.

### What happened?

https://addons.cdn.mozilla.net/user-media/addon_icons/309/309978-128.png is 404 because the 128 icon was not generated on the server.

### What did you expect to happen?

https://addons.cdn.mozilla.net/user-media/addon_icons/309/309978-128.png icon should have been generated on the server, just like https://addons.cdn.mozilla.net/user-media/addon_icons/309/309978-64.png was generated and not 404.

### Anything else we should know?

If I set my regular profile's `extensions.getAddons.cache.enabled` pref  = false and load about:addons, then the extension's icon (-64.png) was then correctly loaded from the jar. If I then reset `extensions.getAddons.cache.enabled` = true, then the extension's icon (-128.png) is missing again.

**Comment by diox** [comment]
The icon for this extension was generated more than 10 years ago, so a number of things could have happened... It'll probably be easier to get the developer to re-upload it than to track the source of the problem...

**Comment by diox** [comment]
FWIW we only started properly supporting 128x128 icons in December 2018 (https://github.com/mozilla/addons-server/issues/5805).
