### ISSUE TITLE
consider dropping version pages from sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17289]
We include `https://addons.mozilla.org/<locale>/firefox/addon/<slug>/versions/` for every addon in the sitemap, but the versions page is of questionable value for search engines - it's unclear if anyone is searching for a specific version of an add-on.  If we drop /versions/ pages we'll save a big chunk of the sitemap - ~25% - and that means less time to generate (and file space)

**Comment by jvillalobos** [comment]
Would the savings be much smaller if we only indexed the first versions page?

**Comment by eviljeff** [comment]
> Would the savings be much smaller if we only indexed the first versions page?

We already do that - there is only one versions page on frontend anyway since legacy frontend went away (mozilla/addons-frontend#7542 / mozilla/addons-frontend#7533)

(issue comment0 updated to fix markdown formatting)

**Comment by willdurand** [comment]
> Ah. 25% is a lot, and the benefit of indexing those pages is questionable, so I'm okay with doing this.

The fact that an URL is excluded from the sitemap does not mean it won't be indexed. If we don't want version pages to be indexed, we will need an issue in addons-frontend.

**Comment by jvillalobos** [comment]
Yeah, I consider that a positive. Excluding them from the sitemap just signals that they're not the most important content for us, but they can still be indexed. If they add noise to tools like the Search Console, then we could consider making them `noindex`.

**Comment by AlexandraMoga** [comment]
The add-on versions URLs are no longer present in the sitemap. 

This issue is verified fixed on -dev.
