### ISSUE TITLE
Remove statsd environment prefixing for Data Dog

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1730]
If we remove the environment prefixing (e.g. `addons_prod`) from statsd pings then we can take full advantage of Data Dog's environment drop-downs. This would allow us to use one dashboard for all site environments.

Sounds great, what's the catch? All historic data will be in a separate namespace so we'd have to use an old dashboard to view trends and phase it out eventually. Not a big deal, just annoying.

**Comment by diox** [comment]
Just thinking out loud: If there is a way to migrate the old data that's not too painful, maybe it's worth it ?

**Comment by EnTeQuAk** [comment]
You could potentially migrate old data via their [API](http://docs.datadoghq.com/api/) or maybe just roll-up some old data and push that to the new names to at least get a summary of old data to see trends and stuff but keep the other ones around for more detailed data?

**Comment by diox** [comment]
OTOH the switch to the new module layout broke a lot of the old pings (the ones generated by the statsd middleware) and it was painful but we got through it anyway, so maybe it's not worth doing.
