### ISSUE TITLE
Normalize `manifest.json` file

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17302]
We would like to normalize the `manifest.json` file at upload time to make sure it is correctly formatted. The normalization will remove comments, too. We think that this step could be performed in the "repack" task.

**Comment by ioanarusiczki** [comment]
@willdurand I uploaded [Search by image ](https://addons-dev.allizom.org/en-US/firefox/addon/search-by-image-test3/)- as a test on AMO dev - and it passed validation.

The manifest.json format contained all the information in a row https://code.addons-dev.allizom.org/en-US/browse/620598/versions/1692763/ plus I added a comment "_comment": "comment text goes here..."

Nothing changed in manifest.json as format and the comment is available as shown by codemanager.

I don't know if that's expected. If I should be testing more around it , let me know.

**Comment by willdurand** [comment]
@ioanarusiczki could you retry now? The feature was not deployed and not enabled.

**Comment by ioanarusiczki** [comment]
@willdurand I tried again and the manifest is looking now like this: https://code.addons-dev.allizom.org/en-US/browse/620599/versions/1692765/ which is different than before - looks good

I can see the comment on line 2.

**Comment by ioanarusiczki** [comment]
@willdurand 
1. Switch is active now on stage - I tested again with //comment. These are deleted after uploads.

Example: 
https://code.addons-dev.allizom.org/en-US/browse/620603/versions/1692771/

2. I tried adding a comment into a manifest with all data in a row:

The linter on stage throws this error: 

![message on stage](https://user-images.githubusercontent.com/33448286/121500003-91c1f280-c9e6-11eb-8f0d-d69c27b69abb.png)

On production the message is:

![linter on prod](https://user-images.githubusercontent.com/33448286/121500170-bcac4680-c9e6-11eb-95f5-62fecb4d431c.png)

I believe it is not expected to pass but the message has changed.

**Comment by willdurand** [comment]
> I tried adding a comment into a manifest with all data in a row:

Can you share the content of the file? I don't understand.

**Comment by ioanarusiczki** [comment]
@willdurand 

I modified the json like that: 

![comment](https://user-images.githubusercontent.com/33448286/121507950-ca18ff00-c9ed-11eb-870e-032446645477.png)

**Comment by willdurand** [comment]
ah ok, well this is clearly not valid so I guess that makes sense.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, what I said is that the linter message is different for the same error on stage versus prod. 

I hope it's fine. 

Verified on AMO dev and AMO stage - FF89(Win10).
