### ISSUE TITLE
Remove reviewer pseudonyms and no longer expose reviewer names

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17318]
### Describe the problem and steps to reproduce it:

The reviewer pseudonyms shown in review emails and on devhub were a nice idea but revealed some issues that at least in some parts don't really address the root problem and can (and has) cause additional confusion for developers.

Let's remove the pseudonyms altogether.

The pseudonym is not helpful to the developer. Also, some reviewers have been mistaken as bots due to their pseudonym. There are more issues on the reviewer privacy side.

### What happened?

Reviewer pseudonyms are shown on devhub and in review emails, potentially in other places as well.

### What did you expect to happen?

Don't expose reviewer pseudonyms (or real names).

Review email can just refer to "a reviewer", or "a human reviewer".

Attributions to reviewers on devhub can say "Add-ons Review Team" pr similar.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
Needs an issue to remove support on frontend too.

**Comment by bobsilverberg** [comment]
> Needs an issue to remove support on frontend too.

I don't think we expose anything about reviewers on frontend. Was there something in particular you were thinking of, @eviljeff?

**Comment by AlexandraMoga** [comment]
@bobsilverberg we have a field in the Edit profile page that allows users with reviewer permissions to set a Reviewer Name:

![image](https://user-images.githubusercontent.com/31961530/148026777-b734d5f5-5f2a-4b48-98f7-1d2e37efb76a.png)

**Comment by bobsilverberg** [comment]
Ah, thanks @AlexandraMoga! I thought the concern was that the reviewer names were being exposed to someone other than the reviewer themselves. I hadn't thought about the profile.

**Comment by bobsilverberg** [comment]
I wonder if it makes sense to break this into two parts; one part to remove the exposure of reviewer names in the places we want to do so (e.g., the changes to the email templates), and a second part to remove the `reviewer_name` feature and deal with places where we want to display "Firefox Add-on Review Team" instead. The first part would be much simpler, and separating it out would make the second part a smaller patch.

WDYT @diox / @eviljeff?

**Comment by dessant** [comment]
I've just noticed the reviews "by Add-ons Review Team" in the activity feed, and my first thought was that they were made by the AMO review team, I had to click on the review to understand what's going on.

**Comment by dessant** [comment]
Activities such as adding an extension to a collection are also attributed to the same placeholder name, so masking names with "User" may be a better fit.

**Comment by eviljeff** [comment]
> I've just noticed the reviews "by Add-ons Review Team" in the activity feed, and my first thought was that they were made by the AMO review team, I had to click on the review to understand what's going on.

as I understand it, those items (rating, adding to a collection) in the activity feed should still have their real name shown, but @bobsilverberg can clarify

**Comment by dessant** [comment]
Regarding the usefullness of pseudonyms attached to reviews, they are actually helpful to both users and other developers. We all have an easier time assessing reviews with pseudonyms, and can identify abuse without the involvement of a Mozilla employee.

With this change a user can go and leave false reviews on all your extensions without needing to create new accounts, and we end up wasting time trying to identify and remedy the issue, because we could not spot that the reviews came from the same user.

Users will also have a harder time to notice and ignore reviews from problematic reviewers, because the review section of extensions will now be similar to a 4chan thread.

Pseudonyms or usernames are a feature of mostly all major app stores and extension stores, and at the very least they should be replaced by an automatic pseudonym attached to the user, if you don't want to allow customization.

**Comment by eviljeff** [comment]
There are reviews by Mozilla for add-on approval, and ratings by users (some containing text) and I think you're talking about the latter.  (this issue, and the connected issues, are about the former)

**Comment by dessant** [comment]
The feed looks like this at the moment:

<img width="334" src="https://user-images.githubusercontent.com/7513068/151525706-c3271545-affa-48b6-9c69-83399163ae39.png">

**Comment by dessant** [comment]
@eviljeff, I thought you were referring to users that have submitted reviews, then this is just a bug.

**Comment by bobsilverberg** [comment]
Thanks for flagging this, @dessant.  We need to add some actions to the whitelist to have their users appear in the activity feed. I have opened https://github.com/mozilla/addons-server/issues/18717 for this. Feel free to comment there if it doesn't seem to cover what's needed.

**Comment by bobsilverberg** [comment]
With the landing of https://github.com/mozilla/addons-server/issues/18701, this issue can be considered closed.
