### ISSUE TITLE
Node 14

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17331]
With Node 16 already available, we can switch from Node 12 to Node 14 in the coming weeks. This issue is about doing it.

**Comment by willdurand** [comment]
cc @bqbn

**Comment by AlexandraMoga** [comment]
@willdurand do you have some test instructions for this?

**Comment by ioanarusiczki** [comment]
@willdurand Dev Hub addon uploads passed all release test cases.  Verified on AMO stage - FF89(Win10).
