### ISSUE TITLE
Manifest normalization breaks signature of privileged add-ons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17344]
Versions of privileged add-ons (and other add-ons that are already signed when submitted to AMO) might be broken because of the manifest normalization we introduced in #17302. We should skip normalization for these add-ons.

**Comment by ioanarusiczki** [comment]
@willdurand 

For a mozilla signed addon : comments are still displayed 

https://code.addons-dev.allizom.org/en-US/browse/620610/versions/1692788/

Manifest on a single row:

https://code.addons-dev.allizom.org/en-US/browse/620611/versions/1692792/

Verified on AMO dev - FF89(Win10).
