### ISSUE TITLE
Ensure Cache-Control headers are correct for addons-server

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17340]
addons-server variant of https://github.com/mozilla/addons-frontend/issues/10678

To prepare for having the main domain behind a CDN, we need to make sure to return the proper `Cache-Control: s-maxage`. Technically, addons-server should already do the right thing (contrary to the frontend it never had `Cache-Control: no-store` on all pages), but double-check anyway. 

It might be a good thing to just set `Cache-Control: s-maxage=0` as soon as we see a `sessionid` cookie or `Authorization` header in the request to be explicit. In that case the `APICacheControlMiddleware` would need to be renamed and moved to a more central location like in the `amo` app.

**Comment by diox** [comment]
From testing the dev CDN so far everything seems to be working as expected without requiring any changes. We don't set `Cache-Control` outside of the API, but that's fine and the CDN just never caches the devhub pages for instance.

**Comment by diox** [comment]
QA: on top of testing https://github.com/mozilla/addons-server/issues/17721 please make sure logging in and out multiple times with different users in quick succession with the same browser work fine.

**Comment by AlexandraMoga** [comment]
I've tried multiple login/logouts on -dev, with different users in the same browser and I haven't run into issues.

I know there was an issue which was mostrly reeproducible on stage  - #17546 - so I'll double check with stage when this patch lands there.

**Comment by AlexandraMoga** [comment]
I did not run into login issues on stage either. 

I'm marking this issue as verified fixed.
