### ISSUE TITLE
Remove StopWatch logging from sitemap generation

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17349]
it's super noisy and (hopefully) now unnecessary

**Comment by iamvaishnav** [comment]
Can I work on this?

**Comment by eviljeff** [comment]
> 
> 
> Can I work on this?

thanks for the other but it's time sensitive so I'm going to work on it.  

There are good-first-bugs here:
https://addons-pm.herokuapp.com/contrib/good-first-bugs/
and contrib:welcome issues which are a bit more complicated:
https://addons-pm.herokuapp.com/contrib/contrib-welcome/?dir=desc&sort=updatedAt
