### ISSUE TITLE
render template xml with jinja2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17353]
We currently force the sitemap.xml to be rendered with django template engine as the file is the exact version in django3.2 and there are minor syntax differences between jinja2 and django flavor templates.  Jinja2 is faster though, and the template rendering time is the last big chunk of time in sitemap generation we would like to optimize (down from ~0.35s per 2000 item addon sitemap file)

**Comment by AlexandraMoga** [comment]
I've checked the sitemap.xml sections on -dev and stage and they are still rendered as before but with faster load times. 

If there is something more specific to be verified, do let me know.
