### ISSUE TITLE
"Duplicate keys in JSON file" error not caught during validation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17371]
### Describe the problem and steps to reproduce it:
1. Prepare an add-on for upload by inserting duplicate keys in the manifest - i.e. double entry for `"name"`, `"manifest-version"` etc
2. Submit the add-on on AMO

### What happened?
Add-on successfully passes validation

### What did you expect to happen?
The following error is raised: "Duplicate keys are not allowed in JSON files."

### Anything else we should know?
- reproduced in all AMO environments
- the correct error is raised when I'm validating the add-on through `addons-linter` CLI

[duplicate-keys.zip](https://github.com/mozilla/addons-server/files/6668417/duplicate-keys.zip)

**Comment by willdurand** [comment]
> The following error is raised: "Duplicate keys are not allowed in JSON files."

I don't think this is a regression. The normalization merges the duplicate keys before linting the file and that's expected as the normalization is designed to produce valid JSON manifest files.
