### ISSUE TITLE
'Unexpected error' during validation if manifest is not at the root of the extension 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17370]
### Describe the problem and steps to reproduce it:
1. Prepare an extension archive where the the `manifest.json` file is not at the root - for example by creating an archive from the extension directory rather than archiving the files directly
2. Submit the add-on on -dev or stage

### What happened?
The following validation error is triggered: "Error: Validation was unable to complete successfully due to an unexpected error."

### What did you expect to happen?
The following error: "Error: No manifest.json was found at the root of the extension. The package file must be a ZIP of the extension's files themselves, not of the containing directory. See: https://mzl.la/2r2McKv for more on packaging."

### Anything else we should know?
Not reproduced on prod

[manifest-root.zip](https://github.com/mozilla/addons-server/files/6668109/manifest-root.zip)

**Comment by willdurand** [comment]
> Not reproduced on prod

mm so that rules out the manifest normalization I guess?

**Comment by willdurand** [comment]
Oh wait, no. It's because we're using `parse_xpi()` but it should only be used if there is a manifest file at the root of the xpi.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/122929901-211abe80-d374-11eb-98e5-d88941ffdd4a.png)
