### ISSUE TITLE
Upgrade Elasticsearch to 7.1.x

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17389]
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html

Some changes on our side are required, need to figure out how much and if we can make them in a backwards-compatible way.

**Comment by diox** [comment]
So for starters, [the `standard` filter has been removed](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#standard-filter-removed). This is trivial to fix, it should be a no-op.

Indexing after that is fixed still fails with a `Root mapping definition has unsupported parameters` exception that doesn't specify which fields are problematic...

**Comment by diox** [comment]
Started to work on this to evaluate how much effort it'd take. https://github.com/diox/olympia/tree/elasticsearch-7.x should address most of it, still need to check backwards-compatibility and determine an upgrade strategy for dev/stage/prod (probably based on the rolling upgrade link above)

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/pull/17457 was 99% of the way there, but it has rotten a bit. We would need to pick this up again, fix conflicts, and determine a solid transition plan together with ops that ensures there is no downtime.

**Comment by diox** [comment]
QA: check that searching still works on the site :)

**Comment by ioanarusiczki** [comment]
@diox 

I verified on AMO dev with FF102(Win10) the homepage shelves, the search results for the extensions and themes tabs , extensions and themes categories, query searches, submitted a new addon , changed the addon name -> I did not find problems.

**Comment by ioanarusiczki** [comment]
@diox 
P.S. Also search results on user profile page and autocomplete for collections work as expected.
