### ISSUE TITLE
Add display name and group access to super-creation API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#1738]
QA has required some features to http://addons-server.readthedocs.org/en/latest/topics/api/accounts.html#super-creation

- Show display name in API response
- Specify group access for the user (such as 'reviewer')

**Comment by davehunt** [comment]
@kumar303 I'd like to use this in https://github.com/mozilla/Addon-Tests/issues/818, do you have an ETA?

**Comment by davehunt** [comment]
To clarify, it's the display name part that I'd like to use in the referenced test suite changes.

**Comment by kumar303** [comment]
I got wrapped up in some web-ext work but let me try and find time today or early next week.

**Comment by kumar303** [comment]
@davehunt it should be landing on dev shortly. Let me know how it goes.

**Comment by davehunt** [comment]
@kumar303 works perfectly, thanks!
