### ISSUE TITLE
Remove is_restart_required from API responses

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#17390]
Depends on https://github.com/mozilla/addons-frontend/issues/10716

After https://github.com/mozilla/addons-frontend/issues/10716 is fixed, addons-frontend will no longer be using ~either~ `is_restart_required` ~or `is_webextension`~ from API responses. Therefore, we can remove them from `v5` of the API.

--edited to limit scope of the issue to `is_restart_required`.  `is_webextension` to be dealt with in #17658

**Comment by willdurand** [comment]
It'd be nice to have to separate patches for the two properties. It'll be easier to review.

**Comment by eviljeff** [comment]
I guess they can go from the model too (`is_restart_required`, at least)

**Comment by bhushan-borole** [comment]
Hello @eviljeff @willdurand @bobsilverberg 
I would like to work on this issue.
Could you tell me how to proceed with this?

**Comment by eviljeff** [comment]
@bhushan-borole Hi, it's not a super simple issue, to be honest.  Unless you're already confident with python & pytest tests it's not a great good "first" bug.

Like Will said, it should probably be split into two issues for the two properties.  And then it's a matter of replacing the field with a `SerializerMethodField` and returning a fixed response (`False` for `is_restart_required`; `True` for `is_webextension`), which is then dropped again in `to_representation` if the api gate is disabled.  See `AddonSerializer.to_representation` for a good example.  Next there needs to be tests that check both cases - when the api date is enabled, and when it's disabled.

**Comment by bhushan-borole** [comment]
I am pretty confident with Python, but will get the hang of pytest, that's not an issue.
So basically, first step is to change the fields to `True` or `False` based on if it is `is_webextension` or `is_restart_required`.
Am I correct?

**Comment by caitmuenster** [comment]
Hey @bhushan-borole! We talked about this internally and realized this is not a good first bug. :) Could you try patching one of our other issues tagged 'good-first-bug'? Once you've landed a few patches to the server and have a better sense for how this API works, you might be able to come back to this issue. :)

**Comment by ioanarusiczki** [comment]
@eviljeff  
- "is_restart_required" was removed into addon detail, version and search APIs - v5
- it is still available in v4 

Verified on AMO dev with Postman.
