### ISSUE TITLE
Reviewers Dashboard for users with ReviewerTools:ViewUnlisted includes redundant sections

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17394]
### Describe the problem and steps to reproduce it:
1. Create a user with `ReviewerTools:ViewUnlisted` permissions
2. Open the Reviewers dashboard - https://reviewers.addons.allizom.org/en-US/reviewers/

### What happened?
The dashboard contains links to all the review queues and sections, instead of showing access only for the Unlisted Add-ons section. Trying to access a page that falls outside the permission coverage will trigger a 404.

### What did you expect to happen?
The dashboard should include only the Unlisted Add-ons section

### Anything else we should know?
View Unlisted group created in admin - https://addons-internal.stage.mozaws.net/en-US/admin/models/access/group/50105/change/

[Reviewers Dashboard for users with ReviewerTools:ViewUnlisted]
![image](https://user-images.githubusercontent.com/31961530/123116471-9c9a6f80-d449-11eb-94bc-a08d0cb85c94.png)

**Comment by diox** [comment]
Yeah, this is not a huge deal since nobody should have just that permission.

**Comment by eviljeff** [comment]
wontfix'ing this as just having that permission without the other review permissions isn't a use case we've ever come across.
