### ISSUE TITLE
CORS the API

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1741]
We aren't sure where the admin API is going to be living. We do know that the disco pane is going to be on services.addons.mozilla.org, let's ensure the API is CORS'd so that's not going to be a problem.

In the marketplace we started off setting this explicitly on each API. I think CORS by default might be the way to go.

**Comment by diox** [comment]
Is there any part of the *site* that we would not want to enable CORS for ? I'm thinking we could simply add it as a middleware, using https://github.com/ottoyiu/django-cors-headers/

**Comment by andymckay** [comment]
On the marketplace I was always nervous about CORS'ing APIs that should only be used by the admin endpoints. But authentication should take care of that and I don't think the defence by depth is worth it.

**Comment by diox** [comment]
We can add specific exceptions where needed. Do we have anything that lives on AMO, not just APIs, that we would not want to allow the outside world access to via CORS ?

**Comment by andymckay** [comment]
I don't know if anyone can answer that question truthfully, there's a lot on AMO. Please limit it to the API if possible.
