### ISSUE TITLE
drop /android/ collections from sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17433]
We don't expose them on the /android/ website, and block them in robots.txt anyway

**Comment by AlexandraMoga** [comment]
Collections for `app_name=android` are no longer listed in the sitemap on -dev:  https://addons-dev.allizom.org/sitemap.xml

@eviljeff I can still access the list of collections for android if I go by a direct URL - https://addons-dev.allizom.org/sitemap.xml?section=collections&app_name=android. Is this expected?

**Comment by eviljeff** [comment]
> @eviljeff I can still access the list of collections for android if I go by a direct URL - https://addons-dev.allizom.org/sitemap.xml?section=collections&app_name=android. Is this expected?

yeah, we don't delete old generated sitemap files so loading them still works.  We perhaps should but once they're not referenced by the primary sitemap.xml file they won't be attempted by search engine crawlers anyway.
