### ISSUE TITLE
Update the "unexpected error" message for validation  

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#17439]
Some developers see this error message when their add-on doesn't get validated: 

<img width="983" alt="Screen Shot 2021-06-29 at 4 29 03 PM" src="https://user-images.githubusercontent.com/23342476/124674651-023a2300-de70-11eb-8e47-27c4629094ab.png">

We should find or make another page where developers can learn more about what may have caused an error during the validation process.

**Comment by eviljeff** [comment]
@caitmuenster is there an existing page we can link to?  Otherwise this is blocked on that content being written (on extensionworkshop.com?)

**Comment by caitmuenster** [comment]
@eviljeff I think we're going to need to make a new page on EW for this, yeah. 

Because a couple of things can throw the "unexpected error," @mat and I were talking about how to best handle this. One option is we could make an FAQ page with a couple of causes/mitigations for the unexpected error message. Another option is that we make a new error message for validator/linter time-outs separate from the catch-all "unexpected error." I think @mat was also looking for other ideas from folks. 

(In any case, we do need to change 'Check https://developer.mozilla.org... to ensure your webextension is valid` to something a bit more helpful. I'm not sure what the original intend of referring them to MDN was. Did we want them to make sure they had a valid manifest? Or make sure they were packaging their extension correctly?)

**Comment by diox** [comment]
Note that on GitHub I'm @diox, not mat :)
