### ISSUE TITLE
enable django3.2 on addons-dev

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17449]
CI tests pass and locally during development we've found no problems.

**Comment by eviljeff** [comment]
QA: we upgraded the version of django that addons-server uses (jumped from the previous LTS release).  Any part of addons-server (devhub, reviewer tools, admin tools, API) could potentially be affected, but tests pass and we've no noticed anything locally.  No specific STR - just a through check.

We are aiming to also deploy to stage & prod for the 2021-07-15 tag&deploy but the config will be changed next week to allow that, so right now it's limited to addons-dev.

p.s. you'll notice a changed UI in admin tools.

**Comment by ioanarusiczki** [comment]
@eviljeff I filed an issue - about the django admin, because I am unable to access it's content right now https://github.com/mozilla/addons-server/issues/17453

**Comment by AlexandraMoga** [comment]
I've run a regression on the pages served by addons-server - DevHub, Reviewer tools, Admin tools - and the API (internal and external, for add-on submissions). I haven't found any issues.

I'm marking this issue as verified fixed on dev and stage.
