### ISSUE TITLE
Stop filtering elasticsearch queries with doc type

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17447]
We currently pass `doc_type=AddonIndexer.get_doctype_name()` to our Elasticsearch queries, and also pass it in the mapping at index creation time. We only have a single type in our indices right now : addons.

But document types are a deprecated feature, and [Elasticsearch 7.x will remove types completely](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html), so that would break for us. We need to  stop passing it at index creation in the mapping and at indexing  time, and stop passing it when searching.

Because we are still currently passing it to search queries, if we were to remove it right away from index creation/bulk indexing,    search would break and never find any results, since the version we're currently using still supports filtering by type. So the first step to remove it from search queries (since we only have one type it shouldn't have any impact), and then later remove it from everywhere else too.

Prerequisite for #17389

**Comment by diox** [comment]
QA: this should be a transparent change, just check that search still works as before.

**Comment by AlexandraMoga** [comment]
I didn't find issues with the search functionality on -dev.
