### ISSUE TITLE
DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17459]
This deprecation warning comes up in a few of our jinja helpers:
```DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1```

A straight search & replace of `@jinja2.contextfunction` by `@jinja2.pass_context` should fix it.

**Comment by NegiAkash890** [comment]
HI @diox , should all the instances be of  `@jinja2.contextfunction` be replaced with  `@jinja2.pass_context` .
I searched them and found more than just one instance.

ScreenShot :


![Screenshot (2)](https://user-images.githubusercontent.com/55234838/125152998-64e03700-e16e-11eb-9f22-74a0cdaff272.png)

**Comment by diox** [comment]
All of them, yes (I count 25 instances in 8 files at the moment).
