### ISSUE TITLE
Unable to view and use the admin modules 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17453]
STR:
On -dev (regression of https://github.com/mozilla/addons-server/issues/17449)

I've been working with the shelf module on -dev (while investigating https://github.com/mozilla/addons-frontend/issues/10721)  but now if I click the Homepage shelves or Shelf modules I see the URLs redirect correctly but instead of seeing their content the homepage is again displayed mixed with shelf content, a sample:

![a sample](https://user-images.githubusercontent.com/33448286/124906313-9c74a500-dfef-11eb-800d-5f163628f6f3.png)

I see it reproducible for all admin modules.

**Comment by willdurand** [comment]
@ioanarusiczki what's your OS and FF version?

There is now a left-side panel with the other admin modules, and it should look like this:

<img width="1552" alt="Screen Shot 2021-07-08 at 12 58 27" src="https://user-images.githubusercontent.com/217628/124910738-320e3580-dfec-11eb-9b6e-a7cafab4f6dc.png">

**Comment by eviljeff** [comment]
also, try a hard refresh - there might be conflicts with cached scripts (it's all django admin code, so they don't have cache busting, iirc)

**Comment by ioanarusiczki** [comment]
@eviljeff Thanks, it worked, I can see the new UI on -dev without problems now.
