### ISSUE TITLE
Remove queue position from Dev Hub

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#17451]
The Dev Hub displays an extension's position in the review queue. Since we don't always review the queue by positional order, we should remove this display from the Dev Hub so we don't set false expectations around estimated wait time.

**Comment by diox** [comment]
Could be a good first bug. The idea would be to remove the whole `{% with position ... ` block from `src/olympia/devhub/templates/devhub/includes/addon_details.html` as well as the `get_position()` import and use from `src/olympia/devhub/views.py`.

**Comment by zhanghuishun** [comment]
Is this issue still open? I am new to open source and I can take it.

**Comment by Atharva-Shinde** [comment]
I am working on it.

**Comment by dante381** [comment]
Hey, is the issue resolved? If not, i would like to work on it and could you guide me through the process. I have gone through the
through the documentation and i have a few queries regarding the setup of docker.

**Comment by bhushan-borole** [comment]
Hey @diox 
I would like to take up this issue if anyone is not working on it.

**Comment by diox** [comment]
As you can see several people have express interest but we haven't seen anything yet so it's still opened to anyone that wants to work on it.
