### ISSUE TITLE
set min version compatibility for mv3 addons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17473]
We want to set a minimum version compatibility for add-ons that use manifest version 3, equal to the version of Firefox that supports it.  (Need a target version of Firefox, or a guess for now - won't matter if it moves until we enable the submission switch)

@mixedpuppy want to estimate a target release?  98?

**Comment by eviljeff** [comment]
Going with Firefox 100 but we can change this closer to the launch (i.e. when the waffle switch is enabled)

**Comment by eviljeff** [comment]
QA: I'm not sure how testable this is on addons-dev this far in advance - Firefox 100 won't have been added as a version yet...?  Interested to know what happens though!

**Comment by AlexandraMoga** [comment]
@eviljeff here are a few of the test scenarios I've tried on -dev (btw, new firefox versions can be added via the [applications api](https://addons-server.readthedocs.io/en/latest/topics/api/applications.html))

- [MV3 extension](https://addons-dev.allizom.org/en-US/developers/addon/mv3-firefox-versions-/versions/1692842) without compatibility set in the manifest => defaults to min `100.0` - max `*` in devhub manage versions page
- [MV3 extension](https://addons-dev.allizom.org/en-US/developers/addon/mv3-firefox-versions-3/versions/1692846) - with compatibility <100 set in the manifest => defaults to min `100.0` - max `*` in devhub manage versions page
- [MV3 extension](https://addons-dev.allizom.org/en-US/developers/addon/mv3-firefox-versions-4/versions/1692847) - with compatibility >100 set in the manifest => same compatibility threshold is displayed in devhub after submission - for example min `110.0` - max `110.*` if this is what the manifest specifies
- [MV2 extension](https://addons-dev.allizom.org/en-US/developers/addon/mv2-firefox-versions-/versions/1692844) without compatibility set in the manifest => defaults to min `48.0` - max `*` in devhub manage versions page
- [MV2 extension](https://addons-dev.allizom.org/en-US/developers/addon/mv2-firefox-versions-3/versions/1692850) with compatibility <100 set in the manifest => compatibility specified in the manifest is displayed in devhub after submission
- [MV2 extension](https://addons-dev.allizom.org/en-US/developers/addon/mv2-firefox-versions-4/versions/1692852) with compatibility >100 set in the manifest => same compatibility threshold is displayed in devhub after submission - for example min `110.0` - max `110.*`
- [MV3 language pack](https://addons-dev.allizom.org/en-US/developers/addon/mv3-lang-pack/versions/1692843) compatibility in manifest set to min `100.0` - max `100.*` => compatibility specified in the manifest is displayed in devhub after submission
- [MV3 language pack](https://addons-dev.allizom.org/en-US/developers/addon/mv3-lang-pack-99/versions/1692853) with compatibility <100 set in the manifest => defaults to min `100.0` - max `100.0` in devhub manage versions page
- [MV2 language pack](https://addons-dev.allizom.org/en-US/developers/addon/rom%C3%A2n%C4%83-rom%C3%A2nia-language-pack/versions/1692855) with compatibility <100 set in the manifest => compatibility specified in the manifest is displayed in devhub after submission

The results seem to be as expected.
