### ISSUE TITLE
Bogus 'olympia' database is being created

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#1747]
After setting up a test instance, run the following command:

    echo 'SHOW DATABASES' | docker exec -i addonsserver_mysqld_1 mysql

In addition to the "real" `olympia` database (created by the `make initialize_db`) this will also show a database called `'olympia'` (yes, with quotation marks). That's because of the quotation marks [here](https://github.com/mozilla/addons-server/blob/b1c2111/docker-compose.yml#L49) apparently - these aren't interpreted as quotation marks but rather make it into the name of the database. I'm fairly certain that the quotation marks [here](https://github.com/mozilla/addons-server/blob/b1c2111/docker-compose.yml#L18) aren't meant to be there either.

**Comment by wagnerand** [comment]
Thanks for the exact code links. I was just showing this issue to @kewisch this morning.

**Comment by EnTeQuAk** [comment]
Awesome, thanks for the report! I just fixed them in https://github.com/mozilla/addons-server/pull/1752
