### ISSUE TITLE
Add error message on upload for mv3 addon

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17478]
while the waffle switch (#17450) is disabled we want to display an explicit error message about mv3 being unsupported, rather than just having the linter report that an unsupported manifest version was specified.

**Comment by eviljeff** [comment]
@jvillalobos for copy and @caitmuenster for url to link to

**Comment by jvillalobos** [comment]
`Manifest v3 is currently not supported for upload. You can read more about the support timeline [here].`

**Comment by eviljeff** [comment]
we're going to use https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/ for now.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I disabled the switch `enable-mv3-submissions` and tried to submit a couple of add-ons that contain "manifest_version": 3 in manifest.json. 

I get the following linter error message:

![error in mv3](https://user-images.githubusercontent.com/33448286/127332806-a508bd61-a933-47b0-b48c-b0cf305224a8.png)

[here] - redirects to https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/ in the same tab

**Comment by jvillalobos** [comment]
@eviljeff It looks like there are some extra `[]` on the link.

**Comment by eviljeff** [comment]
> @eviljeff It looks like there are some extra `[]` on the link.

Yeah... I implemented literally what you wrote in https://github.com/mozilla/addons-server/issues/17478#issuecomment-880067957 😬

**Comment by ioanarusiczki** [comment]
@eviljeff Sorry at this week's pace I did not realize they're not really necessary those brackets, I will file a followup if needed.

**Comment by eviljeff** [comment]
@wagnerand had thoughts about the wording of the message in general (not using "here" in the sentence) too.  But a separate issue will be easier to manage - it doesn't seem like it needs to be a cherry pick so it'll be landing in a subsequent tag.
