### ISSUE TITLE
store manifest version on File model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17472]
we may need to filter or get information on compatibility later.

**Comment by eviljeff** [comment]
QA: the `manifest_version` field is visible via django admin

**Comment by ioanarusiczki** [comment]
@eviljeff I can see `Manifest version:` field being available in `admin/models/files/file/fileid/change/` model. 

With an admin account, I could increase the value from 2 (-> maximum allowed is 32767) , or decrease it to negative values so I filed https://github.com/mozilla/addons-server/issues/17519
