### ISSUE TITLE
drop unused properties from Tag model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17479]
We currently define a `restricted` (only settable by admins) and a `denied` (hidden, for abusive tag text) properties for a `Tag`.  

Now all tags are staff defined we don't need `denied`, but do we need `restricted` still? We currently only have 2 restricted tags - `restartless` (from many years ago where most legacy add-ons needed to restart Firefox to work); and `dynamic theme` (added automatically when a developer uploads a dynamic theme).

Do we want to continue to add `dynamic theme` automatically?  If we drop support for `restricted` then a developer would be able to add that tag to arbitrary non-dynamic-theme add-ons (or remove it from an add-on that was a dynamic theme).

Either way, if we _do_ want to continue to support `restricted` in some way, are there preferences how this is exposed?  
- Just hidden from devhub entirely (i.e. not settable by admins either).  It would be possible to set via django admin but a bit messy
- settable by admins in devhub but hidden from non-admins
- visible by normal developers but with the checkbox disabled (or similar)

**Comment by eviljeff** [comment]
@jvillalobos to opine ^

**Comment by bobsilverberg** [comment]
Looking at the existing list of proposed tags at https://docs.google.com/document/d/1QJ5PSHJJn5ruvhITlTMongePpZggsrTYKdmmBO0Wbk4/edit#heading=h.kn3nkelyc86, it doesn't seem like we'd need `restricted` anymore.

**Comment by eviljeff** [comment]
I asked because the use case isn't called out in the doc either way, and `dynamic theme` may have been overlooked (I forgot all about it, and I added it!)

**Comment by diox** [comment]
Note: we have the ability to find dynamic themes in database by looking at the `theme` permission, so we don't need to keep the `dynamic theme` tag if that's just for our own benefit (and even for the outside world, we could expose some kind of search on permissions in the future)

**Comment by eviljeff** [comment]
it was primarily to be able to point users to them https://github.com/orgs/mozilla/projects/31

**Comment by jvillalobos** [comment]
I think it should be fine to drop `restricted`. Dynamic themes used to be a complicated subject because we thought they could become a big deal and we weren't sure how we would classify them on the site. Turns out it's not a huge deal and they're fine as extensions.

**Comment by eviljeff** [comment]
@jvillalobos just to confirm, we should drop the "dynamic theme" tag entirely - i.e. delete it from the list of available tags, so remove it from existing add-ons that are tagged with it, and stop setting it if a developer uploads a dynamic theme.

**Comment by jvillalobos** [comment]
Yes, confirmed.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- dynamic theme has been removed from Tags 
- the search API returns 13 addons tagged with "dynamic theme" on stage and 34 on -dev.

https://addons.allizom.org/api/v5/addons/search/?appversion=90.0&app=firefox&tag=dynamic theme
maybe it has not been updated in search results yet?

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff
> 
>     * dynamic theme has been removed from Tags
> 
>     * the search API returns 13 addons tagged with "dynamic theme" on stage and 34 on -dev.
> 
> 
> https://addons.allizom.org/api/v5/addons/search/?appversion=90.0&app=firefox&tag=dynamic theme
> maybe it has not been updated in search results yet?

I forced a full ES reindex and, after some delays with caching, the tags seem to be reset

**Comment by ioanarusiczki** [comment]
@eviljeff 
Yes, on -stage I don't get results. "results": []
-dev still returns those 34. 

Marking it verified, in case you're thinking of reindexing -dev too , let me know.

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff
> Yes, on -stage I don't get results. "results": []
> -dev still returns those 34.
> 
> Marking it verified, in case you're thinking of reindexing -dev too , let me know.

just did.  

And thanks for noting this - when it was just stage I assumed it was a regular ES mishap but when you mentioned dev too I realised the way the tags were updated in the migration bypassed the normal triggers to update the index.  We're going to have ops also run a full reindex on prod after the push.
