### ISSUE TITLE
"Hacking on the Docker image" documentation section names the image incorrectly

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#1748]
[Documentation](https://github.com/mozilla/addons-server/blob/f4e9badac9634657068dfbd4733ab5d17798e3f6/docs/topics/install/docker.rst#hacking-on-the-docker-image) will currently suggest to run the following command:

    docker build -t addons/olympia .

If I understand this correctly, it should rather be:

    docker build -t addons/addons-server .

**Comment by EnTeQuAk** [comment]
Awesome, thanks for the report! I just fixed them in https://github.com/mozilla/addons-server/pull/1753
