### ISSUE TITLE
Make sure blocklisting can't get stuck and a submission can't end up in a locked state

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17490]
On top of #17489, we should make sure that blocks can't get stuck in a phase we can't recover from. I am not sure what the best approach to this is, maybe verify and handle all exceptions, or wrap individual block stages in a transaction so they are rolled back and can be restarted by an admin manually?

**Comment by eviljeff** [comment]
I guess this is a QA- unless @wagnerand has ideas.

**Comment by willdurand** [comment]
I also think we cannot come up with good STR for QA.

**Comment by AlexandraMoga** [comment]
I did not find regressions in the blocklisting functionality. This issue is verified fixed on stage.
