### ISSUE TITLE
drop `criteria` from shelf API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17498]
`criteria` is a weird property, because it means different things for different types of shelf - and the client has to know the logic and how to use it with an appropriate url (selected based on `endpoint`).  The `url` property already has a complete url using `criteria` so that should be sufficient.  blocked on mozilla/addons-frontend#10776

**Comment by ioanarusiczki** [comment]
@eviljeff 
`criteria` has been removed from the shelf API endpoint.

Verified on -dev and -stage with Postman.
