### ISSUE TITLE
Optimize IP address query performance

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17504]
Searching for users by ip address is currently a bit slow, the data is scattered on different tables, IPs are stored in string form as a `varchar(45)`, and not always indexed.

One fix to investigate would be to store them as `blob` or `varbinary`, using `INET6_ATON()` and friends in MySQL, or `ipaddress.ip_address().packed` in python) and indexing that.  That's blocked by https://github.com/mozilla/addons-server/issues/14547 because we currently do manual SQL queries with `FIND_IN_SET()`, which would definitely not work anymore with that approach.

**Comment by wagnerand** [comment]
We should either fix this or remove the feature again.

**Comment by diox** [comment]
Biggest issue with the query right now seems to be the `OR` + multiple tables search. MySQL ends up doing a full table scan on `users`. So even though optimizing storage of the IPs in a binary column would help, I don't think that would solve it.

Couple ideas to fix this:
- Rewrite the query to use a `UNION DISTINCT` instead of `DISTINCT` + multiple `OR` - the `UNION DISTINCT` would be costly, but if we don't have that many results most of the time, certainly less costly than a full table scan.
- Stop searching through various tables - consolidate all IP logging into `log_activity_ip` (`IPLog` model) and only use that. Would require a massive data migration to backfill the table.

**Comment by diox** [comment]
Going to try consolidating all IP logging  into `log_activity_ip`, that seems to be the more promising approach.

**Comment by ioanarusiczki** [comment]
@diox 

I've noticed on -dev and -stage that if I make a query with multiple ips, (~ 6 ips in a row) it returns 0 results. 
It also takes a while  until the results are displayed.

**Comment by ioanarusiczki** [comment]
@diox It looks like I left spaces between -> it broke the search results. I'll mark this verified.

**Comment by diox** [comment]
I filed https://github.com/mozilla/addons-server/issues/19635 as a follow-up to make this kind of errors less confusing.
