### ISSUE TITLE
Outdated repository link in contribute.json

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#1750]
https://addons.mozilla.org/contribute.json (a.k.a https://github.com/mozilla/addons-server/blob/master/contribute.json) currently links to https://github.com/mozilla/olympia, should be https://github.com/mozilla/addons-server.

**Comment by EnTeQuAk** [comment]
Awesome, thanks for the report! I just fixed them in https://github.com/mozilla/addons-server/pull/1753
