### ISSUE TITLE
Don't allow negative numbers for manifest version

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17519]
Followup for https://github.com/mozilla/addons-server/issues/17472

I've noticed that I can enter and save negative numbers for the `Manifest version` field from `admin/models/files/file/413488/change/`

**Comment by eviljeff** [comment]
I think that's fine - you can break all kinds of stuff in django admin, generally without any guard rails (with the exception of the few django admin pages we've specifically designed to be used operationally as tools.  File is not one of them)

**Comment by ioanarusiczki** [comment]
@eviljeff I understand. It's a won't fix.
