### ISSUE TITLE
devhub addon edit sections 403 - CDN regression

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17525]
editing a section in addon edit in devhub is broken (on addons-dev, at least).
e.g. https://addons-dev.allizom.org/en-GB/developers/addon/crosswarpex-%ED%99%95%EC%9E%A5/edit

looking in devtools shows the XHR returns a 403.  Logs show error was:
"Forbidden (Referer checking failed - no Referer.): /en-GB/developers/addon/crosswarpex-확장/edit_additional_details/edit"

**Comment by eviljeff** [comment]
This isn't replicable locally (with default settings).  Bizarrely, I can't replicate on stage though (that, at this moment, has exactly the same code on it)

**Comment by diox** [comment]
Might be because addons-dev is now behind a CDN - https://github.com/mozilla/addons-server/issues/17521

Might be some missing configuration in the CDN to allow the Referer header to be passed.

**Comment by diox** [comment]
I tried to fix this in the CdnRequestPolicy:
- First by adding `Referer` and `Origin` headers to the list of forwarded headers. That resulted in 504s for the pages I was testing (devhub, logged in)
- Then I tried a different approach, setting it to forward all headers (instead of limited list) + `CloudFront-Viewer-Country`, also resulted in 504s

I reverted the changes so the original problem (403s on pages checking for the `Referer`) remains.

**Comment by bqbn** [comment]
I added the `Referer` header to the list of forwarded headers (see https://github.com/mozilla-services/cloudops-deployment/pull/4309/commits/d0fba7f71ab8e4c7cd128669a9c54bc293f6ba86). The `Origin` header is always forwarded. Thus, there is no need to add it.

I then watched the traffic between the origin (nginx) and the app server. I saw that both the `Referer` and the `Origin` headers were passed to the app server, but the app server did still return 403.

Below are the headers the origin server passed to the app server (credentials obfuscated):

```
QUERY_STRING....REQUEST_METHOD..POST..CONTENT_TYPE0.application/x-www-form-urlencoded; charset=UTF-8..CONTENT_LENGTH..412..REQUEST_URII./en-GB/developers/addon/crosswarpex-%ED%99%95%EC%9E%A5/edit_describe/edit       .PATH_INFO=./en-GB/developers/addon/crosswarpex-....../edit_describe/edit
.DOCUMENT_ROOT../data/olympia/default/webroot..SERVER_PROTOCOL..HTTP/1.1..REMOTE_ADDR..130.176.100.97..REMOTE_PORT....SERVER_PORT..81..SERVER_NAME..amo.dev.mozaws.net..Host..amo.dev.mozaws.net        .X-Real-IP..130.176.100.97..HTTPS..on..HTTP_X_COUNTRY_CODE..US  .HTTP_HOST..amo.dev.mozaws.net..HTTP_ACCEPT_ENCODING..gzip, deflate, br..HTTP_ACCEPT_LANGUAGE..en-US,en;q=0.9..HTTP_CACHE_CONTROL..no-cache..HTTP_CLOUDFRONT_VIEWER_COUNTRY..US..HTTP_CONTENT_TYPE0.application/x-www-form-urlencoded; charset=UTF-8..HTTP_COOKIEn._ga=GA1.2.1251312412.1609953873; _gat=1; _gid=GA1.2.1345714110.1626827444; frontend_auth_token=*****; sessionid=*****..HTTP_ORIGIN..https://addons-dev.allizom.org..HTTP_PRAGMA..no-cache..HTTP_REFERERY.https://addons-dev.allizom.org/en-GB/developers/addon/crosswarpex-%ED%99%95%EC%9E%A5/edit..HTTP_USER_AGENTy.Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36..HTTP_VIA@.2.0 e9c8cd6cad69627cb7c9d88123e6e2cd.cloudfront.net (CloudFront)..HTTP_X_AMZ_CF_ID8.DQi7xmsU-vAPyM0q-aPzjUUglFEAQA0XcW1pgC_zQ2__7hO2I-hTFQ==..HTTP_X_FORWARDED_FOR..199.58.97.46, 130.176.100.97..HTTP_X_FORWARDED_PORT..443..HTTP_X_FORWARDED_PROTO..https..HTTP_CONTENT_LENGTH..412..HTTP_CONNECTION
.keep-alive

```

I think the problem may not have to do with the `Referer` header.

Would it be the `x-csrftoken` header?

**Comment by diox** [comment]
Good call! I didn't think to re-check the logs after I added `Referer`, and indeed, the problem was that the `x-csrftoken` header was not forwarded. I added it and now it works.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I could not reproduce this issue, I verified the edit addon page on -dev and -stage with FF90(Win10). Editing worked for me.
