### ISSUE TITLE
Update tooltip text for tag input on Developer Hub

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#17524]
Current text:
`Tags help users find your add-on and should be short descriptors such as tabs, toolbar, or twitter. You may have a maximum of 10 tags.`
Proposed text:
`Tags help users find your add-on. You may have a maximum of 10 tags. Only choose tags that are relevant to your add-on.`

**Comment by ioanarusiczki** [comment]
@eviljeff 

The new tooltip is displayed - verified on AMO stage - FF90(Win10):

![new tooltip](https://user-images.githubusercontent.com/33448286/127324222-c23a1af1-cc7a-4fc6-8d63-a48c92735789.png)
