### ISSUE TITLE
Move AMO-dev main domain behind CDN

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17521]
ops work tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1714429 but this issue is for QA to test -dev specifically.

It should be a transparent change, but it affects the whole site so a complete check of the site is needed.

Notable things to try:
- Georestrictions
- Logging in and out
- Browsing the site logged in and out
- Browsing with different browsers, making sure the notice appears for non Firefoxes

Each time, make sure to do repeat views to ensure caching works and is correctly segmented (you shouldn't see a cached response from a different browser/country/user)

**Comment by ioanarusiczki** [comment]
@diox 

Frontend caching: 

- if I change edit the summary or description of an addon and then I log out - the details edited are not available for a logged out user for a while. Only after a couple of minutes the new content becomes available. Same happens for a logged out user into a different browser.  - I think it works as expected 

I can't conclude on Georestrictions:
 - if I load a detail page in a country where the addon is not restricted and then I reload in the same tab from a country where it is restricted (using VPN) - I will get a 451. - I think it works as expected
 
- I loaded an addon page, in my case from RO and then restricted it for my region using django admin.  When I am logged in, I see the immediately the 451 page. But logged out if I reload the page multiple times even after 2 hours, sometimes I will get the detail page displayed and sometimes there's the 451 loading. This is not happening into a different FF profile while being logged out, I get a 451 permanently.  - I don't know if it's expected

![georestricted2](https://user-images.githubusercontent.com/33448286/126621592-6cedc2c2-3421-4428-ae48-09b55d4313cb.gif)

- other areas of the site seem to be working fine but I'm going to take one more look over the dev hub and rev tools tomorrow on AMO dev.

**Comment by ioanarusiczki** [comment]
@diox 

I repeated the geolocation test and got different results:
- an unauthenticated  loading the detail page of an add-on into a country where it is not restricted, I have a 200 response. Then the addon becomes restricted (I restricted it into a different profile, with an admin account). I reload the page into the same tab and I get a 451 immediately, not after 3 min (or 6).  I get the same results on stage too. Let me know if this is expected in this case or should I see the 451 response only after a while?
- the addon submission on -dev is not working right now (same was on Friday) but I filed https://github.com/mozilla/addons-server/issues/17566. Also, I don't think it's related to this issue.

**Comment by diox** [comment]
You should eventually see a 451, but how much time it takes for that depends on a lot of factors. It can be immediate if the cache was expired or simply not popular enough (in which case the cached response could be dropped to make more space for popular items).

**Comment by ioanarusiczki** [comment]
@diox Ok, now I understand. I'll mark this issue verified on AMO dev - FF90(Win10).

**Comment by diox** [comment]
This is now on stage as well.
