### ISSUE TITLE
Flag usernames from reviews for spam and abuse

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-server#17527]
Since user profiles have been removed for regular users, it's difficult to report people that engage in spam, when they do it over a username. Consider this review which has no text: https://addons.mozilla.org/en-US/firefox/addon/search_by_image/reviews/1735066/

The username is a shady site for earning money by viewing ads, and all the user has to do to receive regular traffic is to rate popular extensions. One option would be to also allow flagging reviews which do not contain text for inappropriate language or spam, with the implication that the reported content is the username.

**Comment by eviljeff** [comment]
We decided against allowing non-textual ratings to be flagged previously, because it was almost impossible to make a decision that it was spam with any content, but I'm not sure we considered this case.  Summoning @jvillalobos 

(technical note: it's a `.display_name` rather than a `.username`)

**Comment by jvillalobos** [comment]
Spamming through the display name is very rare, and unlikely to be successful, so setting up a reporting mechanism just for that use case seems excessive. It would also create lots of noise from developers who don't agree with a negative rating.

I took care of that user. In the future you can message amo-admins AT mozilla DOT com to report those users, or use one of our Matrix channels. I know it's not a great reporting flow, but I think it's a rare enough occurrence that it doesn't warrant direct support.
