### ISSUE TITLE
correct some tags

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17538]
Followup for https://github.com/mozilla/addons-server/issues/17474
This is the list of [tags](https://docs.google.com/document/d/1QJ5PSHJJn5ruvhITlTMongePpZggsrTYKdmmBO0Wbk4/edit#heading=h.kn3nkelyc86)

1. the list has an "ad blocker", meanwhile dev hub displays an "adblock"
2. the list has 2 separate tags "image search" and "search". These should be separated in dev hub as well
3. There's a "dynamic theme" tag into dev hub which I did not see in the list

![tags](https://user-images.githubusercontent.com/33448286/126486836-42343aa5-6e91-4cbb-86d2-7498ab2f8422.png)

**Comment by eviljeff** [comment]
>     1. the list has an "ad blocker", meanwhile dev hub displays an "adblock"

the list in the doc was updated after I copied it 😄  @jvillalobos can update the tags on prod via django admin

>     2. the list has 2 separate tags "image search" and "search". These should be separated in dev hub as well

my bad - I had to manually tinker with the list when I copied it from the doc.  @jvillalobos do you want me to land a migration to fix this or will you be okay doing it via django admin too?  (i.e. rename "image searchsearch" tag to "image search"; add a new tag called "search")

>     3. There's a "dynamic theme" tag into dev hub which I did not see in the list

the "dynamic theme" tag will be removed with #17479

**Comment by jvillalobos** [comment]
I can deal with the updates, yes.

**Comment by ioanarusiczki** [comment]
@eviljeff I corrected them using admin on -dev. Since the dynamic theme was handled in a different issue, I'm going to close this one.

**Comment by eviljeff** [comment]
@jvillalobos were the tags on prod updated?  (and if the new tags are still under discussion do you need this issue left open?)

**Comment by jvillalobos** [comment]
The tags in prod were reviewed and updated.
