### ISSUE TITLE
last_human_review attribute

### ISSUE THREAD

**Issue by lafonth** [mozilla/addons-server#17530]
The review team is using a list of add-ons on telemetry and it appears that even after a human review, add-ons are staying in the list.
I made some research on the query and it appears that it is filtering the add-ons which get addons_addonapprovalcounter -> last_human_review at 0.
I made some verification and the add-ons that are reviewed by humans are still flagged at 0 which explains why they are still on the list.

It is supposed to switch to 1 if a human review is performed.

**Comment by diox** [comment]
`last_human_review` and `counter` in the `addons_addonapprovalcounter` table are set when a human approves or confirms approval of an add-on from the listed review page. `counter` is incremented, and `last_human_review` set to the current date. In addition though, `counter` gets reset to 0 for auto-approvals (`last_human_review` stays as-is).

Do you have examples of add-on ids where it's not working ?

**Comment by diox** [comment]
@lafonth:
>  Do you have examples of add-on ids where it's not working ?
