### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/addons-server#17546]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
Android 11

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://addons.allizom.org/en-US/firefox/ and log in using an existing account.

**Actual result:**
The user is not logged in.

**Expected result:** 
The user is logged in.

**Note:**
The issue is intermittent. It is not always reproducible.

![log in issue](https://user-images.githubusercontent.com/79697848/126617639-6d1a2ba3-b5ab-4e13-bf33-a5edf0e1f311.gif)

**Comment by diox** [comment]
I can't reproduce after several tries. Anything in your devtools console or network panel that could help ?

**Comment by vcarciu** [comment]
I can see this in browser console :
![browserconsoleerror](https://user-images.githubusercontent.com/1583842/126622980-b0bf2c5b-debd-4ed5-bfa0-9d070dfe9e0f.PNG)

**Comment by ioanarusiczki** [comment]
I could also reproduce it today on AMO stage - I made lots of logins today

![Console](https://user-images.githubusercontent.com/33448286/126623957-89972d14-f726-449f-b3a8-e2a6a31e1a80.png)

![Network](https://user-images.githubusercontent.com/33448286/126623988-d965016e-1b3f-4c81-8fa4-bddee8b4d7d4.png)

**Comment by vcarciu** [comment]
After trying more logins, the issue was intermittently reproducible and I can see more errors in console: 
![morebrowserconsolelogs](https://user-images.githubusercontent.com/1583842/126624580-4005a519-73c0-40d1-a2fb-dbaa17a6df73.PNG)

**Comment by diox** [comment]
We debugged this with @vcarciu on Matrix, and there is something weird going on on our side: when they reproduce the failure (which I still can't do myself!) the `/api/v3/accounts/authenticate/?code=...` call doesn't set the `sessionid` or `frontend_auth_token` cookies! So when they are redirected to the homepage at the end, naturally they are not considered logged in.

I couldn't find anything in the logs, so I'm not sure what's going on yet, but at least this is progress...

**Comment by diox** [comment]
Progress: there _is_ something in the logs: a State mismatch. So they end up in that case:
https://github.com/mozilla/addons-server/blob/6d3afc88fd562a90e22444ff1bf230c2c7572cc2/src/olympia/accounts/views.py#L259-L271

That explains why they are not successfully logged in. The source of the mismatch appears to be that the `sessionid` cookie is not present in the request, so the session never exists, never contains the state, so we fail log in.

So there must be an issue right at the beginning of the flow preventing the session cookie from being sent by addons-server or recorded on the client.

**Comment by diox** [comment]
So what I think happened:
- Somehow, at some point, `/api/v5/accounts/login/start/?config=amo&to=%2Fen-US%2Ffirefox%2F` (which is a `GET` request, annoyingly) doesn't return a fresh session cookie. I don't know how that's possible, but that causes the request to be cached.
- That makes the whole flow fail at the end with the state mismatch
- Because it's cached it can happen again later for users with the same browser/accept-language/country.

**Comment by diox** [comment]
Finally have STRs. The prerequisites are:
- Visit `/api/v5/accounts/login/start/?config=amo&to=%2Fen-US%2Ffirefox%2F`, note the `sessionid` cookie in the response. Don't follow the rest of the flow
- Visit `/api/v5/accounts/login/start/?config=amo&to=%2Fen-US%2Ffirefox%2F` again with the `sessionid` cookie you got from the first visit. It should redirect you to the flow as normal, but, crucially, it should not set a cookie.

Once this is done once, if you're unlucky enough, the response from that second visit will have been cached, and that will break logging in for clients sharing the same cache key (same user-agent/accept-language/country).

The solution is to prevent caching of the accounts API `GET` requests entirely.

**Comment by ioanarusiczki** [comment]
@diox Can't reproduce the issue on -dev or -stage. I could not reproduce this on -dev before but I tested several times on -stage with the accounts I had issues with and this time looks good.
