### ISSUE TITLE
add migration to drop restricted and denied columns from `tags` db table

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17545]
follow on from #17540 - needs to be merged in a subsequent tag than https://github.com/mozilla/addons-server/pull/17540

**Comment by ioanarusiczki** [comment]
@eviljeff 
- same number of tags displayed in dev hub
- I could edit tags
- frontend search results with tags redirect as expected
- random-tag shelf functions as before
- the dynamic theme search results returns 0 addons on both -dev and -stage
