### ISSUE TITLE
always return shelf footer url - generate fallback

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17544]
Currently, a Shelf has an optional footer.url, which is the link that is displayed on the homepage to see more addons from that Shelf, and a footer.text to accompany it.  Both are optional, and if not provided default to `See more {shelf.title}` for the latter, and either `/collections/{MOZILLA_USER_ID}/{shelf.criteria}/` for collections or `/search/{shelf.criteria}` otherwise for the former.  This means that frontend needs to duplicate the logic about how each shelf works to be able to generate the footer if not provided.  

Instead, lets generate this in the API and always return the footer content so the logic only needs to be in once place, and adding new types in server doesn't (necessarily) mean adjusting the supporting code in frontend.

**Comment by eviljeff** [comment]
limiting this issue to just the url because that's the blocker currently

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this on -dev:
- making several API requests I've noticed that the footer url is always returned. (it is "null" on -stage when the footer pathname was not edited from django admin)
- for the new-random endpoint now I've noticed the presence of the tag that's been used, an example:
"url": "https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=rating&type=extension&tag=adblock"
