### ISSUE TITLE
Update FxA clients to stop using /api/v3/authenticate

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17553]
We thought we had changed all FxA clients to using `/api/auth/authenticate` but we're still seeing a `/api/v3/authenticate` request at least when logging in through the frontend (and possibly more). It may be because we consolidated all FxA configuration (there were a lot of different clients configured for no good reason) at some point and we consolidated on an old one or something.

We want to identify where this is happening, why, and fix it to use `/api/auth/authenticate`

**Comment by diox** [comment]
Also seems to be happening when logging in from addons-server, not just addons-frontend.

**Comment by eviljeff** [comment]
see https://bugzilla.mozilla.org/show_bug.cgi?id=1589330 - the bug was opened to do this but it's not been completed

**Comment by diox** [comment]
This should be fixed now. On all envs, upon successful FxA login, you should see a request to `/api/auth/authenticate` on AMO that redirects you to the page you were on when you tried to log in. We shouldn't use `/api/v3/authenticate` anymore.

**Comment by eviljeff** [comment]
/api/auth/authenticate-callback (I forgot it was changed)

**Comment by ioanarusiczki** [comment]
@diox I checked all envs and I see /api/auth/authenticate-callback being present at a successful login. I tried to login from the frontend, dev hub, code-manager and admin tools.
