### ISSUE TITLE
Simplify "error" handling in authentication view

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17552]
Error handling in our authentication code is a little weird. We have this `render_error` function, but it has a couple issues:
- 1) It doesn't really render an error. Rather it returns a redirect, logs something in our logs (which is a recent addition, that made this issue more visible *) and logs something for the user in the messages framework... that they might not ever see, because those are only displayed in addons-server templates. And even if they do see it, it's too late and not very useful for them.
- 2) Some of these cases are not really errors. When someone is already authenticated, we end up going through error logging etc, but it's not really an error, and we handle that just fine.

The caller of `render_error` already logs, and we have another function to do a safe redirect, so we should refactor this to avoid code duplication and make it more clear we aren't really rendering an error.

(*) sentry https://sentry.prod.mozaws.net/operations/olympia-prod/issues/11970796/events/

**Comment by diox** [comment]
QA: Make sure authentication still works, and you don't get errors trying to go to the authentication flow while being already logged in (either by going manually to /api/v5/accounts/login/start/?config=amo&to=%2Fen-US%2Ffirefox%2F while logged in, or by trying to log in from an unauthenticated page while having already logged in from a different tab).

**Comment by ioanarusiczki** [comment]
@diox 
- I've noticed that while being authentificated in multiple tabs on different AMO pages and I manually go to https://addons-dev.allizom.org/api/v5/accounts/login/start/?config=amo&to=/en-US/firefox/ in a new tab and I reset the password from here, after changing password I will be asked to login with the new password. Meanwhile, on the other tabs opened I'll stay logged in before and after I Sign in with the new password. - maybe I should be logged out in the other tabs since the password is no longer the one used at the initial login? 

- I did not encounter other issues.

**Comment by ioanarusiczki** [comment]
@diox I forgot to add: the only place I'm asked to login again is in admin tools but that's been happening for a while. 
I login using frontend or dev hub and than click the Admin Tools from Tools menu ->

![accounts stage](https://user-images.githubusercontent.com/33448286/127322433-8f2aad8c-ed32-4f84-933a-b0b6c7dda2b1.png)

I must take the above step again, this is happening when I log out from dev hub or frontend , login again and I try to access the admin.

**Comment by diox** [comment]
Because FxA is technically an external service for us, you keep your AMO session even when changing your FxA password at the moment. Logging you out of AMO should log you out of all your existing AMO sessions though.

**Comment by ioanarusiczki** [comment]
@diox It's working fine then. 
Verified on AMO dev - FF90(Win10).
