### ISSUE TITLE
HTML tags visible in Editor Tools->Themes page after a blank search

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1755]
Steps to reproduce:
1. Log in to AMO-stage with an admin account https://addons.allizom.org/
2. Go to Editor Tools - Themes https://addons.allizom.org/en-US/editors/themes
3. Go to any queue and make a blank search

**Expected results:**
All themes (searched theme) are listed or a "no results.." message is displayed. 

**Actual results:**
The search does not work. 

Notes/Issues:
HTML tags are visible in Updates queue. (in AMO-dev html tags are visible in every Theme queue after a search)
Verified on FF44(Win 7). Issue is reproducing in AMO-stage and AMO-dev.
Screencast for this issues: http://screencast.com/t/gDjxcpTDbuW

**Comment by krupa** [comment]
On prod, I see the JS error 
ReferenceError: reviewer is not defined
 editors-min.js:5:7788

**Comment by muffinresearch** [comment]
This line is the problem: https://github.com/mozilla/addons-server/blob/a1117995d295895cb6e7471353a2849c1eb8617a/static/js/zamboni/themes_review_templates.js#L68

**Comment by muffinresearch** [comment]
So it looks like the cause of the JS error is an anonymous theme: https://addons.allizom.org/en-US/editors/themes/queue/single/testtheme09123 since this is the one that causes the error. The data object doesn't have a reviewer property.

**Comment by muffinresearch** [comment]
Ok this is a regression from 4e110e5906ce2f503f14959d3f62897b22746c75

**Comment by muffinresearch** [comment]
I'm not sure this fixes the HTML tags being displayed - but this fixes the JS error from https://github.com/mozilla/addons-server/issues/1755#issuecomment-188913722

**Comment by ValentinaPC** [comment]
1. Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/N9x4z1mmxq

2. I cannot check the JS error from AMO-prod because I don't have rights. Maybe Krupa can take a look, just to be sure.

3. I am not sure if themes search is working as expected. When searching for a specific theme=> nothing is displayed. Maybe this is how it suppose to work, muffinresearch?

**Comment by muffinresearch** [comment]
> I cannot check the JS error from AMO-prod because I don't have rights. Maybe Krupa can take a look, just to be sure.

It's not on prod yet. Use -dev.

> I am not sure if themes search is working as expected. When searching for a specific theme=> nothing is displayed. Maybe this is how it suppose to work, muffinresearch?

Where is that? It should be working on -dev but no-where else yet.

**Comment by ValentinaPC** [comment]
1. No JS error in AMO-dev when making a search
2. I've made a specific theme search in AMO-dev - this is what happened: http://screencast.com/t/oIfyMTTkKT

**Comment by muffinresearch** [comment]
Hmm, that seems odd. It's working for me. Are you sure there's no JS error still for you - that behaviour looks like the broken version? 

It might be you are still running cached JS. Can you try again having cleared your cache?

**Comment by muffinresearch** [comment]
Oh nevermind - I can reproduce that. It's the server returning no search results. That's unrelated - probably related to that item not being indexed yet. 

Try something simlper like 't'

**Comment by muffinresearch** [comment]
Fwiw I've added this issue for the lack of a nice error message. https://github.com/mozilla/addons-server/issues/1794

**Comment by ValentinaPC** [comment]
Yeah "t" is working as expected. Some other chars too. Not all searched themes are being displayed if searched....maybe are not indexed... as you said. (http://screencast.com/t/iBgncOb0bKF)

Thanks for filling. 

Based on last comments I'll mark this verified.
