### ISSUE TITLE
Enable CSP on addons.cdn.mozilla.net

### ISSUE THREAD

**Issue by marumari** [mozilla/addons-server#1756]
Nothing (presumably?) should be viewed directly on addons.cdn.mozilla.net.  As such, could we implement a CSP policy along the lines of:

default-src 'none'

Alternatively, if things *are* supposed to be viewed directly, maybe:

default-src 'self'; script-src 'none'

**Comment by muffinresearch** [comment]
Thanks April I've re-filed this as a ops ticket here: https://bugzilla.mozilla.org/show_bug.cgi?id=1250974 and CC'd you.

**Comment by marumari** [comment]
Ahh, my apologies.  It's one of those bugs where it's a bit ambiguous as to where it should go.  Thanks!
