### ISSUE TITLE
AMO dev addon submission is not working 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17566]
STR:
1. Been trying on Friday and today with extensions to make submissions 

It's always this error:

![Always this error](https://user-images.githubusercontent.com/33448286/126963921-cc05cfe5-b672-4ef1-b762-f23cec7ed584.png)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/11827748/?query=is%3Aunresolved

Looks like a `customs` scanner issue preventing all uploads.

**Comment by willdurand** [comment]
The error below is present a lot in the Lambda logs:

```
ERROR	{
  error: 'failed to download file',
  extra_info: 'Response code 404 (Not Found)'
}
```

**Comment by diox** [comment]
Given the following upload: `932e3b0e29324a2e8fb606016072fa2f`, the download URL for the scanners to run on should be 
`https://addons-dev.allizom.org/uploads/file/932e3b0e29324a2e8fb606016072fa2f/?access_token={redacted}` which redirects to `https://addons-dev.allizom.org/en-US/firefox/uploads/file/932e3b0e29324a2e8fb606016072fa2f/?access_token={redacted}`. That part works fine.

What doesn't work is that this should return a response with a `X-Accel-Redirect` that nginx intercepts and serves internally. It doesn't, and instead the CDN (and clients) end up seeing a 301 to `/en-US/firefox/mnt/efs/addons-dev.allizom.org/files/temp/2ee56f3bc9444017ac63311eb7ff20a1.xpi` which is very weird... Maybe something broken in the nginx config on dev ?

**Comment by willdurand** [comment]
cc @bqbn for help on the nginx side

**Comment by bqbn** [comment]
There was a misconfig in nginx which got fixed in the above commit.

I now see 200 from this link:

```
$ curl -I "https://addons-dev.allizom.org/en-US/firefox/uploads/file/932e3b0e29324a2e8fb606016072fa2f/?access_token=..."
HTTP/2 200
content-type: application/octet-stream
content-length: 234
accept-ranges: bytes
date: Mon, 26 Jul 2021 18:58:46 GMT
last-modified: Mon, 26 Jul 2021 12:11:08 GMT
server: nginx
x-backend-server: ip-172-31-43-163
x-cache: Miss from cloudfront
via: 1.1 6a6653dfb47ccc5082f2a5b9d0d168ce.cloudfront.net (CloudFront)
x-amz-cf-pop: SEA19-C1
x-amz-cf-id: Hi92GLyVqCXfRiERyEZUcbMkQlDIJEh5vfMQUS6EK7MzCVulZRwyIQ==
```

**Comment by diox** [comment]
That fixed it

**Comment by ioanarusiczki** [comment]
@diox I tested several addon submissions for https://github.com/mozilla/addons-server/issues/17478
Looks like it's working.
