### ISSUE TITLE
use pyupgrade to freshen our code?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17571]
https://github.com/asottile/pyupgrade can rewrite python code to use newer syntax.  Doesn't really help any more than any linting tool does, but may as well have a consistent newer style of python rather than a mishmash depending on how many years ago it was originally written.

I've played around with it and it's not a drop in command line tool because it seems to expect to be used as a [pre-commit](https://github.com/pre-commit/pre-commit) hook mainly - e.g. you can't just give it a directory and it'll walk through the structure - it needs single files.  I hacked something together to work around that to be used as one-off though, it would just need a little polish to use permanently (and possibly submitted as a patch upstream)

**Comment by eviljeff** [comment]
behold #17603

**Comment by ioanarusiczki** [comment]
@eviljeff Can qa check on this?

**Comment by eviljeff** [comment]
there's nothing specific to test here - it was all syntax changes.
