### ISSUE TITLE
Deny new add-ons that use an ID ending in @temporary-addon

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17579]
### Describe the problem and steps to reproduce it:

IDs ending in `@temporary-addon` are reserved for temporarily loaded add-ons in Firefox. We should not accept such IDs for signing (and thus submission).

Since we already have a few add-ons on AMO with that ID, we can't deny any submissions yet, so we are limiting this issue to new add-ons first.

Submitting a new add-on with an ID ending in `@temporary-addon`...

### What happened?

...is accepted by AMO.

### What did you expect to happen?

...should not be accepted by AMO.

### Anything else we should know?

As mentioned above, submission of updates to existing add-ons using such IDs should not be denied for now.

**Comment by eviljeff** [comment]
for background, what's the risk/problem if an add-on with a guid ending `@temporary-addon` is signed and installed in Firefox?

**Comment by wagnerand** [comment]
Add-ons using that suffix are special-cased in Firefox in that certain APIs like `localstorage` are not supported (and will throw exceptions if you try to access them). Also, I saw some devtools code checking for that suffix.

We also don't know what future special handling we'd want or have to do for temporarily loaded add-ons, so it's better to be on the safe side and restrict submission for them.

**Comment by diox** [comment]
We've restricted submission of add-ons with IDs ending with that suffix to users with the `SystemAddon:Submit` permission

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and these are my results:

- users _without_ `SystemAddon:Submit` are not allowed to upload new add-ons with an ID ending with `@temporary-addon`
![image](https://user-images.githubusercontent.com/31961530/127878383-f25c0d50-b19e-483c-9b2c-5867cab4c493.png)

- users _without_ `SystemAddon:Submit`, which already have an add-on with an ID ending with `@temporary-addon` available on the site, are still allowed to add new versions to it
- users _with_  `SystemAddon:Submit` are allowed to upload new add-ons with an ID ending with `@temporary-addon`
