### ISSUE TITLE
500 errors when I try to delete shelves that have been enabled then disabled

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17581]
STR:
1. From the homepage shelves module I tried to delete some shelves but I run into 500 errors every time:

["Random tag test2" ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/70/change/) which currently is disabled 

![server error at delete2](https://user-images.githubusercontent.com/33448286/127310006-ec0da59e-f9b4-4562-b75d-39ea8f7757a1.gif)

2. Another example with recommended extensions, themes - I tried with the shelf enabled then disabled, same result -> 500 

![server error at delete](https://user-images.githubusercontent.com/33448286/127309979-de016a8e-8c79-4a6a-ba7a-3df0066c02e2.gif)

Note:
I could delete other enabled/disabled shelves while I tried to reproduce this issue - I can't conclude what's causing this.

**Comment by eviljeff** [comment]
I know what's causing this - the old `ShelfManagement` table still exists (we don't delete it straight away to avoid failures during the deploy window) and it has a constraint that stops shelves from being deleted while they're linked to a `ShelfManagement` record.

Two solutions:
- land a late patch to just drop the constraint on the `shelves_shelfmanagement` table
- wait until next week and just drop the table entirely as planned.

If we do the latter then @devaneymoz won't be able to delete shelves in the meantime (but they can be set to disabled).

**Comment by eviljeff** [comment]
error is 
```
IntegrityError(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`addons_dev_allizom_org`.`shelves_shelfmanagement`, CONSTRAINT `shelves_shelfmanagement_shelf_id_01308ad2_fk_shelves_shelf_id` FOREIGN KEY (`shelf_id`) REFERENCES `shelves_shelf` (`id`) ON DEL)')
```

**Comment by ioanarusiczki** [comment]
@eviljeff I just deleted without problems the shelves I mentioned into this issue.
Verified on -dev FF90(Win10).
