### ISSUE TITLE
Allow more people to edit the DevHub submission announcement text

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#17593]
The Developer Hub can display an announcement message on the submission page that informs developers about issues related to migrations, service interruptions, etc.

<img width="948" alt="Screen Shot 2021-07-28 at 11 21 28 AM" src="https://user-images.githubusercontent.com/62568/127367916-30b53851-7c6e-4ca9-974c-a8f7917202d2.png">

It's currently only editable as a Config in the django admin, which limits who can edit it. @caitmuenster is one of the people who generally manages this message, so we should find a way to make it more accessible. @eviljeff suggested we could make the whole Config section more accessible to others. Alternatively we could have a simple admin page that edits this message. I have no strong preference either way.

**Comment by wagnerand** [comment]
We already have a special page and permission for updating the reviewers MOTD. We could just clone that?

**Comment by eviljeff** [comment]
> 
> 
> We already have a special page and permission for editing the reviewers MOTD. We could just clone that?

We could.  IMO this is an admin-like task that belongs in the admin tools though (and the special page for just updating the reviewers MOTD should be removed)

**Comment by diox** [comment]
> IMO this is an admin-like task that belongs in the admin tools though (and the special page for just updating the reviewers MOTD should be removed)

Agreed.

**Comment by eviljeff** [comment]
These are the Configs we set/reference in AMO code:
- `site_notice`
- `reviewers_review_motd`
- `submit_notification_warning`
- `last_dev_agreement_change_date`
- `blocklist_mlbf_generation_time`
- `blocklist_mlbf_base_id`

Before relaxing permissions, to be explicit on risks:
- The first 3 are announcement messages (entire site; reviewers; devhub submission) that have high visibility (site_notice the most) but low risk of inadvertent breakage - they're just text strings where even if bad markup managed to break something we'd notice straight away.  Deleting is no problem as the message would go away.
- `last_dev_agreement_change_date` could be broken with an invalid format (breaking all submissions, potentially), and if deleted would trigger all developers to have to re-accept the agreement.  But it's unlikely anyone would accidentally change it.
- `blocklist_mlbf_generation_time` and `blocklist_mlbf_base_id` are used by the blocklist generation code to keep track of bloom filters that are then downloaded by Firefox.  These shouldn't be touched even by admins and changing/deleting them could cause breakage in the tasks we wouldn't notice until we got grafana alerts, and/or trigger full bloom filter downloads (MBs per Firefox user).  Again, very unlikely anyone would decide to touch these Config instances though.

**Comment by wagnerand** [comment]
> last_dev_agreement_change_date could be broken with an invalid format (breaking all submissions, potentially), and if deleted would trigger all developers to have to re-accept the agreement. But it's unlikely anyone would accidentally change it.

This has a hard-coded fallback, deleting this shouldn't break submission, but can cause us skipping agreement prompts when we shouldn't skip.

> blocklist_mlbf_generation_time and blocklist_mlbf_base_id are used by the blocklist generation code to keep track of bloom filters that are then downloaded by Firefox. These shouldn't be touched even by admins and changing/deleting them could cause breakage in the tasks we wouldn't notice until we got grafana alerts, and/or trigger full bloom filter downloads (MBs per Firefox user). Again, very unlikely anyone would decide to touch these Config instances though.

Do they need to be configs? Could that live in a global variable or so that is available to the respective code but not exposed to humans?

**Comment by eviljeff** [comment]
> Do they need to be configs? Could that live in a global variable or so that is available to the respective code but not exposed to humans?

Configs are the global variables 😃
