### ISSUE TITLE
Remove [] and maybe change "here" in the message

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17601]
Followup for https://github.com/mozilla/addons-server/issues/17478#issuecomment-889167245

MV3 error linter message must be edited:

![error in mv3](https://user-images.githubusercontent.com/33448286/127332806-a508bd61-a933-47b0-b48c-b0cf305224a8.png)

Reproducible on AMO -dev when the switch is disabled from admin.

**Comment by eviljeff** [comment]
@jvillalobos said
> It looks like there are some extra [] on the link.

and then @wagnerand said:
> Can't we just drop the "here" and linkify "support timeline"? or "You can read more about the support timeline on our blog"
> ...also the link should probably open in a new tab?

**Comment by jvillalobos** [comment]
> Manifest V3 is currently not supported for upload. [Read more about the support timeline](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/).

I think that's the right link, don't take it literally 😛

**Comment by ioanarusiczki** [comment]
@eviljeff 
The link is opening in a new tab https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/ 
![linter message](https://user-images.githubusercontent.com/33448286/128170409-ff2f74ac-df95-465a-a8f6-a70c445388a4.png)
