### ISSUE TITLE
Circle CI failure in `release-master` job

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17605]
Looks like we are not able to deploy commits merged on the `master` branch anymore. There is an `apt` error while building the Docker image:

```
[...]

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Depends: libgcc-s1 (>= 3.4) but it is not installable
E: Unable to correct problems, you have held broken packages.

[...]
```

See: https://app.circleci.com/pipelines/github/mozilla/addons-server/18275/workflows/45ad373a-2700-4b63-997e-1010864cb813/jobs/85560

**Comment by diox** [comment]
https://github.com/nodesource/distributions/issues/1241

**Comment by diox** [comment]
This is now fixed. https://app.circleci.com/pipelines/github/mozilla/addons-server/18277/workflows/79b27285-3c6f-4774-9809-20459b4e2e73/jobs/85583
