### ISSUE TITLE
Fix jinja2 deprecation warnings

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17613]
These 2 warnings come up a lot in addons-server codebase:

- `DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.`
- `DeprecationWarning: 'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.`

It's almost a straight search&replace through the code, adding an `import markupsafe` where needed

**Comment by diox** [comment]
To find them all `egrep 'jinja2\.escape|jinja2\.Markup' src -r` should probably be enough. Gives me 12 results right now.

**Comment by bhushan-borole** [comment]
Hey @diox 
I would like to work on this issue.

**Comment by diox** [comment]
@bhushan-borole if you want to fix it, I found another one: `src/olympia/amo/urlresolvers.py` uses `jinja2.utils.Markup` which should be replaced in the same way.

**Comment by bhushan-borole** [comment]
Sure I will fix it.
