### ISSUE TITLE
The Abuse Reports table on the add-on review page no longer displays the add-on name

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17630]
Follow up for #17507

### Describe the problem and steps to reproduce it:
1. Open the review page for an add-on which has some abuse reports submitted - see https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/re-re-reused-guid-abuse
2. Examine the first column in the Abuse Reports table

### What happened?
The column has an entry for the add-on version only 

### What did you expect to happen?
The column should also display the add-on name

[current layout]
![image](https://user-images.githubusercontent.com/31961530/128017274-48363b2f-83e1-4c7a-8afb-99658acbb7ac.png)

[before]
![image](https://user-images.githubusercontent.com/31961530/128017299-855d7ed8-6818-4335-8112-8c29da7e01b5.png)

**Comment by diox** [comment]
Similar to https://github.com/mozilla/addons-server/issues/17629 : because we no longer link to the add-on when it's submitted by guid, we only have the name that was submitted with the report (Firefox should include it when using the built-in abuse report function). If no name was submitted it doesn't appear here.

**Comment by diox** [comment]
We'll now display the addon name as submitted in the report - which can be empty if the report didn't come for Firefox.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and the Abuse report table will now display the addon name if the report comes from AMO or addons manager. If I'm using the API directly without specifying an `addon_name` in the request JSON object the addon name is not populated, which is expected.

![image](https://user-images.githubusercontent.com/31961530/181210308-18ed7feb-f399-4917-87a3-5873299f6b0f.png)
