### ISSUE TITLE
HTML tags visible on Editor Tools landing page

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1764]
## steps to reproduce:
1.  Load Editor tools
2. Approve an add-on awaiting review
3. Notice the section where your  "All Time" points are listed.

## observed behavior:
HTML tags visible on Editor Tools landing page

## screenshot: 
https://www.dropbox.com/s/gepb0hcz5tw6qdm/Screenshot%202016-02-24%2013.30.09.png?dl=0

**Comment by EnTeQuAk** [comment]
fixed in e4969bcecee402eb9879afc62ceebe9a135b8a29

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-02-29_1020](https://cloud.githubusercontent.com/assets/15685960/13389120/2360f4b6-dece-11e5-8853-bdfeac56cfce.png)
