### ISSUE TITLE
Make the AMO add-on ID the canonical identifier in the reviewer tools

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17644]
Currently, the slug is the canonical identifier for various parts on AMO. For the reviewer tools, we want to change that to the numerical AMO add-on ID to avoid loss of access when add-ons get deleted (which clears the slug) or the developer changes the slug.

It also removes ambiguity for add-ons that are reusing the GUID across several AMO add-on instances.

Accessing the page using GUID/slug should redirect to the numerical ID.

**Comment by wagnerand** [comment]
QA:

Please give the reviewer tools some general testing. Links to review pages should work, both from queues are from "external" pages like devhub or public listing page. Approving/rejecting/... should also still work. The notable difference is that for reviewer tools pages, the AMO numerical ID is now used in review urls, if you pass an add-on slug or an add-on GUID, it should redirect to the numerical ID (prior, we redirected to the slug).

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev for the following areas:
- Reviewer tools: queues, review actions (Approve, Reject, Replies, Comments etc), admin actions
- DevHub - links to the listed and unlisted add-on review page available to users with the required permissions
- admin tools - I've verified that the add-on review page linked in emails triggered by actions from reviewer tools (like reviewer replies) is using the add-on ID

Additionally, all the add-on review URLs that contain the add-on slug are now being redirected (301) to the add-on ID if accessed directly. 

Addon review page URLs that are using the add-on guid are not being redirected to the add-on ID - filed #17687 with more details.
