### ISSUE TITLE
Add the possibility to bypass API throttling for specific users on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17659]
### Describe the problem and steps to reproduce it:
We need a way to bypass the API throttling for specific users to avoid test failures in the automated release tests - https://github.com/mozilla/addons-release-tests.
Since tests are running quite fast on CI, the ratings test suite is currently failing as it hits the API throttling.
According to @diox this should be a pretty straightforward implementation.

**Comment by diox** [comment]
Note: we already have a way to bypass throttling for add-on submission (have the `Langpack:Submit` permission - but we could make a new one and give it to the same group). We'd need to extend that to other APIs like ratings.

**Comment by diox** [comment]
QA: users part of a group that has the `Ratings:BypassThrottling` permission will bypass ratings API throttling once this lands. This is going to be available in all environments.

**Comment by AlexandraMoga** [comment]
Users that have the `Ratings:BypassThrottling` permission will not run into the API throttling while interacting with the ratings functionality. Once the permission is removed, throttling applies as before. 

This is verified fixed on stage. Thanks Mat!
