### ISSUE TITLE
Replace django.utils.http.urlquote() with urllib.parse.quote()

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17668]
We want to fix this deprecation warning:

`RemovedInDjango40Warning: django.utils.http.urlquote() is deprecated in favor of urllib.parse.quote().`

It shows up in a few places in our code, the `urlquote()` calls need to be replaced and the import updated accordingly.

**Comment by bhushan-borole** [comment]
Hey @diox 
I can take a look at this.

**Comment by bhushan-borole** [comment]
I believe the changes should only occur in:

`src/olympia/reviewers/views.py`
`src/olympia/versions/tests/test_views.py`
`src/olympia/amo/context_processors.py`

**Comment by diox** [comment]
That looks right.
