### ISSUE TITLE
Implement unlisted add-on review tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1766]
At the moment we're doing minimal monitoring of unlisted submissions, but we need a robust set of tools so we can be effective fighting malware being submitted for signing. I'll just list what I think we need initially, and maybe this should be broken down into individual bugs.

1. Unlisted submissions: a paginated table of all unlisted add-ons. Columns: ID (linking to review page), name, guid, latest version number, latest version timestamp, authors, % sideloaded, latest review. Sorted by default by latest version timestamp (latest first). Should be searchable by name, author, and guid. Should be sortable by name, guid, and % sideloaded. The authors column would be a list of usernames (linking to their user pages). The latest review column would show something like "Version 1.1 on 2016-03-20", indicating that this was the last version that had some manual review activity (like a comment, needinfo, or rejection by a reviewer), and hovering over that text would show the reviewer name and text of that review. This way reviewers can tell each other which unlisted add-ons have been looked at recently. It would also be useful to have a checkbox to filter out entries with "latest review" set after a given date.
2. Unlisted authors: a paginated table of all authors that are owners or developers of an unlisted add-on. Columns: ID (linking to user page), username, latest version timestamp, number of versions submitted, number of add-ons submitted. Sorted by default by latest version timestamp (latest first). Should be searchable by username. Should be sortable by username, number of versions submitted, and number of add-ons submitted. Note we need a more useful user page for reviewers, which is explained in #979.

These tools should be available from the reviewer tools, for users with the Addons:ReviewUnlisted permission.

**Comment by eviljeff** [comment]
how would % sideloaded be defined?

**Comment by jvillalobos** [comment]
The initial version of the Telemetry report of add-on sideloading is being tracked on [bug 1248638](https://bugzilla.mozilla.org/show_bug.cgi?id=1248638), but it appears to have stalled.

**Comment by ValentinaPC** [comment]
I don't know how far you guys want to go with this implementation. :)

There are some minor things, that could be solved, but your choice.
1. Because many GIUD's have long dimension, the page looks broken (http://screencast.com/t/DIn8qPuOK)
2. It would be useful if search would work here too (http://screencast.com/t/efbhh7BYj)
3. The option is not listed in the unlisted queues menu (http://screencast.com/t/sH0JCE4uFNao)

Thanks!

**Comment by eviljeff** [comment]
> 1. Because many GIUD's have long dimension, the page looks broken (http://screencast.com/t/DIn8qPuOK)

Yeah.  I think its more apparent because stage has lots of test apps with purposely long GUIDs but I'm going to fix it anyway.
> 2. It would be useful if search would work here too (http://screencast.com/t/efbhh7BYj)

It /did/ work during development, so maybe I broke it while trying to fix something else.
> 3. The option is not listed in the unlisted queues menu (http://screencast.com/t/sH0JCE4uFNao)

I wasn't sure if anyone was that interested, but I can add it.

Can you log an issue for 2. at least?  (The others if you want to, too)

**Comment by ValentinaPC** [comment]
1. Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-07_1608](https://cloud.githubusercontent.com/assets/15685960/14352027/1d274dae-fcdb-11e5-9698-2237bbf2d3eb.png)

3. Verified as fixed on AMo-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-07_1611_001](https://cloud.githubusercontent.com/assets/15685960/14352107/7b9dcb24-fcdb-11e5-92f6-7027c4eb148e.png)

Sorry for my delay. Without labels this bugs are hard to track.
I'll log a separate issue for 2. Thanks.

**Comment by eviljeff** [comment]
I think I fixed 2. in another commit - if you still get an error please file.
