### ISSUE TITLE
HTML tags visible in Themes listing page

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1767]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/themes/?sort=up-and-coming
2. Notice the metadata for each of the listed themes

## observed behavior:
HTML tags visible in Themes listing page

## screenshot:
https://www.dropbox.com/s/2r7kcodh8tbkz3s/Screenshot%202016-02-24%2015.13.50.png?dl=0

**Comment by EnTeQuAk** [comment]
fixed in e4969bcecee402eb9879afc62ceebe9a135b8a29

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-02-29_1016](https://cloud.githubusercontent.com/assets/15685960/13389045/adb46eaa-decd-11e5-8e8e-ee6390d0aa1c.png)
