### ISSUE TITLE
Add `Access-Control-Allow-Origin: *` to `/__version__`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17674]
Similar to https://github.com/mozilla/addons-frontend/issues/10822, adding the header `access-control-allow-origin: *` to the `/__version__` endpoint would allow anyone to fetch the content of this file.

**Comment by AlexandraMoga** [comment]
The `access-control-allow-origin:  *` response header is now present in https://addons-dev.allizom.org/__version__
