### ISSUE TITLE
Remove all references to `hide_mobile_link`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17685]
https://github.com/mozilla/addons-server/blob/1866acfb854069c63ed23487cbd5bb291ff130f8/src/olympia/templates/copyright.html#L14-L16 contains a reference to the "new site" behind a `if not hide_mobile_link` condition.

That variable should always be `True`, the link should never be shown, it hasn't been useful in years. Let's remove that block, and all code related to that variable everywhere (other templates set it too)

**Comment by snifhex** [comment]
I would like to work on this, Can you assign it to me ?
