### ISSUE TITLE
Remove reviewers "performance" view

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17692]
The Add-on Reviewers Performance view (https://reviewers.addons.mozilla.org/en-US/reviewers/performance/) shows a graph of the number of reviews done by a reviewer (yourself if you don't have special permissions, with `REVIEWS_ADMIN` you get a list of reviewers to choose from) over time. It also shows a breakdown of reviewer point scores for the user.

The graph in particular has never been updated with post-review, content review, weights etc, so it's a bit meaningless on its own - the quaterly reports are more useful. On top of that, it uses `RawSQLModel`, [which we want to get rid of.](https://github.com/mozilla/addons-server/issues/15431).

So... let's remove that view completely. @caitmuenster and @wagnerand can confirm it's ok.

**Comment by AlexandraMoga** [comment]
The Performance page is no  longer present on the reviewers dashboard and the page will 404 if accessed by direct link - https://reviewers.addons-dev.allizom.org/en-US/reviewers/performance/

This issue is verified fixed on -dev.
