### ISSUE TITLE
Recommended queue is not shown for users with `ReviewerTools:View`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17708]
### Describe the problem and steps to reproduce it:

User has `ReviewerTools:View` permission.

### What happened?

https://reviewers.addons.mozilla.org/en-US/reviewers/ does not show "Recommended".

### What did you expect to happen?

https://reviewers.addons.mozilla.org/en-US/reviewers/ shows "Recommended".

cc @tublitzed

**Comment by AlexandraMoga** [comment]
Users with `ReviewerTools:View` can now access the Recommended queue in view only mode.

[before fix]
![image](https://user-images.githubusercontent.com/31961530/129560642-c2c5a2dc-f29a-4b75-9eb0-aa90570ad967.png)


[after fix]
![image](https://user-images.githubusercontent.com/31961530/129560756-651835df-92cf-446d-9b52-9f378a35859b.png)
