### ISSUE TITLE
/shelves/ api response is a 500 on addons-dev for non- en-US locales

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17710]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/12405566/

regression from https://github.com/mozilla/addons-server/commit/0fb83d53e58af4d9d455e98c1b9ee6164ce72545

Needs to be fixed before next release.

**Comment by eviljeff** [comment]
The cause is the dict of locales for title / footer.text can have `none` values if a request is made for translations in a locale that we don't have yet.

**Comment by AlexandraMoga** [comment]
The shelves API is now returning results when the `lang` parameter is present -  https://addons-dev.allizom.org/api/v5/shelves/?lang=pt-BR

The frontend homepage is also loading - there is no 500 error anymore.

This issue is verified fixed on -dev.
