### ISSUE TITLE
Remove the t-shirt form

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1771]
There's currently a form [1][2] on AMO that is used to allow contributors to request a t-shirt when their add-on or theme reaches certain criteria. 

Hopefully we will soon be specifying form-src in our CSP policy. Ideally it would be nice to be able to lock down form posts to just the main origin of a.m.o rather than additionally allow posts to google (the t-shirt form sends the data to docs.google.com).

Is this used - and can we consider removing this feature and doing this some other way?

[1] https://github.com/mozilla/addons-server/blob/e66197c915d5b260645fd73fec04ab22b5db7a22/src/olympia/users/views.py#L263
[2] https://github.com/mozilla/addons-server/blob/76f1143fc1409dbfed4f94f5bba2b6961c0efefd/src/olympia/users/templates/users/t-shirt.html#L49

**Comment by jvillalobos** [comment]
This was a one-off, so it can be removed. Amy should be able to confirm.

**Comment by atsay** [comment]
Yes, it can be removed. It might even be from before my time.

**Comment by yash14123** [comment]
The python function is to be removed completely right?

**Comment by muffinresearch** [comment]
@yash14123 yep, you're looking to remove the view, the url pointing at the view, the template and anything that's solely related to the t-shirt form.

**Comment by lavish205** [comment]
I would love to work on this issue, please assign mentor.

**Comment by lavish205** [comment]
@muffinresearch I think this[1] template should be completely removed instead of removing `<form>` part as it's not being used anywhere else.
[1] https://github.com/mozilla/addons-server/blob/76f1143fc1409dbfed4f94f5bba2b6961c0efefd/src/olympia/users/templates/users/t-shirt.html#L49

**Comment by wagnerand** [comment]
This has not been triaged as a good first bug yet. Feel free to keep working on this, but for guided issues, you might want to stick to https://github.com/mozilla/addons-server/labels/good%20first%20bug.

**Comment by lavish205** [comment]
@wagnerand yeah, but I think I can work on this bug, can you please review this PR and let me know what else has to be done.

**Comment by eviljeff** [comment]
thanks @lavish205 !
