### ISSUE TITLE
Extract client IP from request headers when behind the CDN

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17727]
When behind the CDN, we can no longer use `REMOTE_ADDR` directly as nginx is passing it, because it will be the CDN's. Instead we need to use `HTTP_X_FORWARDED_FOR`, but only if the request actually came from the CDN - if it was a direct request to the origin (which can happen as the origin is public, though we don't advertise its domain) we want to continue using `REMOTE_ADDR`.

This is important for rate limiting and proper ip addresses logging to work (geolocation should already be ok thanks to us using the headers provided by the CDN).

**Comment by diox** [comment]
Quick & dirty summary for future reference:

When we're behind the CDN, the actual client IP is in `HTTP_X_FORWARDED_FOR`... second to last. The last being the IP of the CDN server that made the request to the origin, because we also have a load balancer between nginx and the CDN.

When we're dealing with the origin directly, we only go through the load balancer, so the client IP is in  `HTTP_X_FORWARDED_FOR`, in the last position. In that particular case though, `REMOTE_ADDR` is already the client IP.

**Comment by diox** [comment]
QA: verify that your IP is recorded properly when you make requests to endpoints that record it (add-on upload, ratings, logging in)

**Comment by diox** [comment]
(Re-opening temporarily because the secret necessary for this to work isn't on dev yet. Note that this shouldn't affect stage or prod at the moment even when it lands there.)

**Comment by AlexandraMoga** [comment]
I've verified the IP records on -dev and these are my results (I've switched IPs to make sure that the changes are properly recorded in such scenarios as well):

- the IP is correctly recorded when a user logs in - I've checked the Last login ip filed in users admin
- the IP is correctly recorded when a submission restriction is hit, like `DeveloperAgreementRestriction` or `IPNetworkUserRestriction`
- the IP is correctly recorded when a rating is posted

There are still some activity logs recorded when an add-on upload rate limit is reached, but rate limiting is not active on dev, so I'll have to check those later on stage.

I've also made a quick check on add-on regional restrictions to make sure those continue to work as well.
