### ISSUE TITLE
Remove reviewers queue search functionality

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17725]
Some old reviewer tools queues allow searching through them, but that functionality isn't actually used at the moment according to @wagnerand and makes #15431 more difficult. Let's remove it.

**Comment by AlexandraMoga** [comment]
The search filed has been removed from the following queues: Recommended, Other Pending Review, Themes (New and Updates), Unlisted.

The queues are still loading and working as before. 

This issue is verified fixed on -dev.
