### ISSUE TITLE
HTML tags visible in Step 1 of add-on submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1773]
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Click Tools->Submit a new add-on
3. Observe Step 1 of the submission process

Expected results:
There are no display or layout issues. An agreement is displayed.  

Actual results:
HTML tags are visible near "I Accept this Agreement" button.

Notes/Issues:
Verified on FF44(Win 7). 
Screenshot for this issue: 
![2016-02-25_1630](https://cloud.githubusercontent.com/assets/15685960/13322868/4dbffd16-dbdf-11e5-9274-5e03790d9d67.png)

**Comment by EnTeQuAk** [comment]
fixed in e4969bcecee402eb9879afc62ceebe9a135b8a29

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-02-29_1013](https://cloud.githubusercontent.com/assets/15685960/13388977/3fc52042-decd-11e5-8e5b-da88bdea74a1.png)
