### ISSUE TITLE
IP search times out

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17734]
### Describe the problem and steps to reproduce it:

Follow up of #14547.

### What happened?

`models/users/userprofile/?q=<IP>` times out with 504.

### What did you expect to happen?

No timeout, results are displayed.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
We have plans to improve perf in https://github.com/mozilla/addons-server/issues/17504 but we were hoping to have the admin search work - even if slow - before doing that.

Maybe an alternative would be to implement a new binary field side by side with the existing string field instead, leaving the possibility for manual queries...

**Comment by diox** [comment]
Closer inspection of the query reveals that... none of the columns are indexed (!). For some reason I thought they were. So there is some hope...

**Comment by ioanarusiczki** [comment]
@diox I tried on both testing severs reproducing a timeout with models/users/userprofile/?q=<IP> , with a single and then multiple IPs.

I've noticed that it takes some time for the queries to return the page with results but I never ran into a timeout.

Maybe @wagnerand will confirm it for prod.

**Comment by diox** [comment]
Still failing in production, we'll have to fix https://github.com/mozilla/addons-server/issues/17504 to address this properly.
