### ISSUE TITLE
HTML visible tags in Search Tools page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1774]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org
2. Click More...-Search Tools (https://addons-dev.allizom.org/en-US/firefox/search-tools/)

**Expected results:**
The page has no display or layout issues.

**Actual results:**
Some HTML tags are visible in "Additional Resources" section.

Notes/Issues:
Verified on FF44(Win 7). 
Screenshot for this issue: 
![2016-02-25_1712](https://cloud.githubusercontent.com/assets/15685960/13323882/2738344c-dbe4-11e5-962f-5aa2e3155f03.png)

**Comment by EnTeQuAk** [comment]
fixed in e4969bcecee402eb9879afc62ceebe9a135b8a29

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-02-29_1008](https://cloud.githubusercontent.com/assets/15685960/13388903/915a34a2-decc-11e5-9ab4-b72316660025.png)
