### ISSUE TITLE
reviewer queues throw a 500 server error when trying to sort by ?sort=addon_type

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#17766]
Followup for https://github.com/mozilla/addons-server/issues/15431

Queues with ?sort=addon_type such as Recommended or Other pending review, recently introduced into /reviewers/unlisted_queue/pending_manual_approval - return a 500 server error when the sorting option is used

![500inqueues](https://user-images.githubusercontent.com/33448286/130598260-b1f2c8a9-6c92-4a45-aeaf-6828d717f26c.gif)

This is only reproducible on AMO dev

**Comment by diox** [comment]
QA: I'm going to completely disable this sort option as it doesn't make much sense in prod.

**Comment by ioanarusiczki** [comment]
@diox The filter has been disabled for all queues. Verified on AMO dev - FF91(Win10).
