### ISSUE TITLE
Reviews are displayed in user profile page for add-ons changed to unlisted

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#1776]
**Steps to reproduce:**
1. Open AMO-stage https://addons.allizom.org/en-US/firefox/
2. Submit a review for a random add-on.
3. The author marks that add-on as Hidden/Unlisted.
4. Go to your user profile and try to edit/delete the comment.

**Expected results:**
Add-on reviews should not appear if the add-on is unlisted.

**Actual results:**
Add-on reviews appears and can’t be edited or deleted.

**Notes/Issues**
Issue is also reproducing when a user enters your user profile and tries to report the review left for the unlisted add-on.
Verified in FF44(Win7) Issue can be reproduced in AMO stage
Screencast for this issue: http://screencast.com/t/panMvZUhj43F

**Comment by EnTeQuAk** [comment]
This might be a bug but I feel like it's edge-case enough to be revisited if we're going to reimplement this some time in the near future with the new addons-frontend.

Closing as wont-fix for now unless someone else disagrees.
