### ISSUE TITLE
Clicking "Cancel and Disable Version" in the submit details form after receiving a form error will trigger a 404

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17774]
### Describe the problem and steps to reproduce it:
1. Upload a new listed add-on
2. Proceed with the submission until you reach the submit details form
3. Edit the add-on name in the submission form (this will also determine the add-on slug)
4. Trigger a form error by leaving some mandatory fields empty (i.e. Summary, Category, License)
5. Click on Submit Version and observe the form error being triggered
6. Click on "Cancel and Disable Version" and confirm

### What happened?
A 404 error is triggered. In my case, the page URL was `https://addons.allizom.org/en-US/developers/addon/{addon-slug}/cancel-latest-listed`

### What did you expect to happen?
You should be landing on the Manage versions page where the version status is "Disabled by Mozilla'

### Anything else we should know?
- I can reproduce this in all environments, so it's not a new issue
- note that the issue reproduces only if you change the add-on name in the submission detail form; if that field stays untouched, the expected flow will take place

![xpNwyIGYaC](https://user-images.githubusercontent.com/31961530/130772842-f93ed3d8-3b46-4369-a6c7-892fd4db32e0.gif)

**Comment by diox** [comment]
Should be an easy fix, using the addon `id` instead of the `slug`... assuming we deal with the redirection correctly (since it's a `POST`)

**Comment by oreo2107** [comment]
> Should be an easy fix, using the addon `id` instead of the `slug`... assuming we deal with the redirection correctly (since it's a `POST`)
I want to work on this issue can you please guide me where should I start with?
