### ISSUE TITLE
Allow tags to be enabled/disabled for shelf rotation

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17772]
We want to be able create tags for developers to choose from, but stop them from being randomly chosen for homepage inclusion (until there are enough add-ons tagged with the tag, etc)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- using `admin/models/tags/tag/` I could disable/enable tags, so far frontend looks good - it returns into the random-tag shelves only the enabled tags (I left on dev the first 10 tags in descending order after the number of addons). 
- as a note: tags can be enbled or disabled one by one - multiple selections for enabling/disabling actions is not possible (at least not yet)
- the addons displayed into the frontend on random-tag shelves also depend on the `Criteria` set into `models/discovery/homepageshelves/` which is expected.

**Comment by eviljeff** [comment]
>     * as a note: tags can be enbled or disabled one by one - multiple selections for enabling/disabling actions is not possible (at least not yet)

can you expand on this point?  Locally I see check boxes next to each Tag and I can change multiple and press the save button to enable/disable multiple.

**Comment by ioanarusiczki** [comment]
@eviljeff Sorry that came out the wrong way. What I meant was a check-box to select/deselect all (such as other admin models have, for example in user profile).  To select/deselect multiple choices is possible, the checkboxes are available.
