### ISSUE TITLE
rm blocklist legacy import integration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17782]
We have integration that imports the legacy, v2, blocklist from remote settings, Now the import cron job is disabled and no longer used we can remove all the code.

**Comment by eviljeff** [comment]
split publishing sync to https://github.com/mozilla/addons-server/issues/17840

**Comment by AlexandraMoga** [comment]
@eviljeff I was going to test the blocklist functionality in admin and I've noticed that we still have a `blocklist_legacy_submit` switch that, when enabled, is supposed to also publish the v3 blocks in kinto (if I remember correctly).
Is this functionality still needed and should it be tested?

**Comment by eviljeff** [comment]
> @eviljeff I was going to test the blocklist functionality in admin and I've noticed that we still have a `blocklist_legacy_submit` switch that, when enabled, is supposed to also publish the v3 blocks in kinto (if I remember correctly).
> Is this functionality still needed and should it be tested?

that's #17840 - I'm just about to merge the patch that will close that too if it's easier to QA them both together.

**Comment by AlexandraMoga** [comment]
I've submitted a few blocks in on AMO -dev (using the admin blocklist model and reviewer tools) and I didn't find issues with the submission flow. The same goes for editing and deleting blocks. I've also verified that the changes were reflected in the new mlbf - https://kinto.dev.mozaws.net/v1/buckets/blocklists_addons_dev_allizom_org/collections/addons-bloomfilters/records.

I could not directly check if imports from kinto are indeed no longer taken into account on -dev, but I'll try to verify that with stage tomorrow.

**Comment by AlexandraMoga** [comment]
@eviljeff is https://kinto.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records still valid for verifying that  new blocks in stage have been properly recorded?

**Comment by eviljeff** [comment]
I think it's moved to https://settings.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records

(or maybe https://settings-cdn.stage.mozaws.net/v1/buckets/blocklists/collections/addons-bloomfilters/records - not sure the difference)

**Comment by AlexandraMoga** [comment]
This is verified is stage as well.
