### ISSUE TITLE
add tag pages to sitemap

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17783]
Lets expose tag pages to the sitemap now they're launched on frontend and linked in the addon details pages.

**Comment by AlexandraMoga** [comment]
https://addons-dev.allizom.org/sitemap.xml?section=tags&app_name=firefox and https://addons-dev.allizom.org/sitemap.xml?section=tags&app_name=android have been added to the sitemap, containing all the 45 tags currently applicable. 

This issue is verified fixed on -dev.
