### ISSUE TITLE
Remove `binary` and `binary_components` fields from `File`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17792]
`binary_components` and `binary` are fields that amo-validator used to set on legacy add-ons when they had... binary components/extension content, which used to be a thing you could do with XUL add-ons

This is not applicable to webextensions, addons-linter never sets these flags, and as a result we don't have any add-ons in the database anymore with those fields set to `True`, they should be removed.

Since the fields aren't currently nullable, first we need to remove them from the model and commit a migration making the columns nullable, then remove the columns entirely in a follow-up migration in a future push.

**Comment by ioanarusiczki** [comment]
@diox If I can verify this issue please add some str.
