### ISSUE TITLE
Dead code: "Read more" link on truncated review

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#1779]
The mobile AMO version will truncate lengthy reviews. There is also a "Read more" link but it is hidden - apparently it was never really implemented. The implementation bits that exist (review truncation code in static/js/zamboni/mobile.js) look like an XSS issue so it's a good thing that they were never used.

For reference, the code landed with [this commit](https://github.com/mozilla/addons-server/commit/05208a2ca710d4b5012615338a403260a6a95d2c) and still seems to be largely unchanged. There was CSS code from the very beginning applying `display: none` to the `.readmore` link. The handler for this link will read out `oldtext` attribute but there is nothing setting it.

**Comment by EnTeQuAk** [comment]
I think this is mostly removing stuff and testing nothing broke. mentor @eviljeff

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by andymckay** [comment]
Given the fact that we've got a completely new front end coming for mobile views any day now (checkout the dev server) recommend just won't fixing this. Hoping mobile.js goes away too :)
