### ISSUE TITLE
Extraction issues in the strings for AMO localization

### ISSUE THREAD

**Issue by kitsunenosaraT** [mozilla/addons-server#1782]
**Steps to reproduce:**
- Go to Pontoon > AMO > (any locale) > LC_MESSAGES/django.po ( https://pontoon.mozilla.org/it/amo/LC_MESSAGES/django.po/ )
- Filter strings using "Missing" parameter
- Notice that newly imported strings are littered with double spaces and unusual strings of white spaces

**Comment by diox** [comment]
Yes, the switch from tower to puente lead to that. We need to fix all our strings to not have multiple spaces as we are no longer automatically collapsing them. We did that for Marketplace.

**Comment by muffinresearch** [comment]
@diox sounds like you know what we need to do. Any chance you file a new issue with what's required to fix extraction?

**Comment by diox** [comment]
IMHO there is no need for a new issue, we can just use this one.

Following the tower -> puente migration, we lost a feature of tower where it was automatically collapsing whitespace. We need to fix our strings to do that collapsing ourselves for all affected strings in templates / python code.

**Comment by MikkCZ** [comment]
What's the status of this issue? I am waiting with translating those string until they are fixed. And of some of them, I think they were translated before - will they be reverted back to the previous translation?

**Comment by EnTeQuAk** [comment]
The whitespaces have been fixed in code and translation-files have been updated accordingly. So there's nothing that will update or change in the near future so that you can safely translate missing strings again.

**Comment by zelitomas** [comment]
> translation-files have been updated accordingly

I've checked it out, but those faulty string still seem to be at least in Czech translation files - for example here - https://github.com/mozilla/addons-server/blob/48f05c7/locale/cs/LC_MESSAGES/django.po#L5514

**Comment by MikkCZ** [comment]
The double %% too https://github.com/mozilla/addons-server/blob/48f05c7/locale/cs/LC_MESSAGES/django.po#L940.

**Comment by EnTeQuAk** [comment]
The double `%%` is required for escaping reasons so this is expected. Ah, we didn't exctract any new strings yet it seems, @davehunt does that regularly afair.

**Comment by diox** [comment]
@ddurst is doing the extractions actually. A new one should be made tomorrow I think.

**Comment by zelitomas** [comment]
Any new updates about this issue? There still are faulty strings on Pontoon... (at least for cs locale)

**Comment by mathjazz** [comment]
Indeed, it seems like /templates were not updated as part of this fix, so original strings still contain unnecessary whitespace:
https://github.com/mozilla/addons-server/commit/48550b4797310e016ffd00d3d5963f093feba9f2

That's causing a discrepancy between source and locale files:
https://github.com/mozilla/addons-server/blob/master/locale/templates/LC_MESSAGES/django.pot#L11810

**Comment by EnTeQuAk** [comment]
I'm about to start the extraction in a few minutes.

**Comment by EnTeQuAk** [comment]
https://github.com/mozilla/addons-server/commit/674052c41d6c76bc85924eda06f61254ca6bd8dc should fix all remaining issues I hope. Please let me know if something's still missing / horribly wrong.

**Comment by mathjazz** [comment]
It seems like only templates and .mo files got updated this time.

Again, there's a discrepancy between source and locale files:
https://github.com/mozilla/addons-server/blob/master/locale/templates/LC_MESSAGES/django.pot#L11655
https://github.com/mozilla/addons-server/blob/master/locale/de/LC_MESSAGES/django.po#L10626

**Comment by mathjazz** [comment]
It would be great if this could be fixed soon, because dozens of strings are now exposed to localizers as untranslated by mistake.

**Comment by EnTeQuAk** [comment]
that's weird, I'm looking into that - specifically what you linked should have been fixed by the commit where we restored the translation messages. Maybe I messed up extraction, I'll take a look.

**Comment by EnTeQuAk** [comment]
@mathjazz sorry it took a while to figure out on how to tackle this properly. Mind giving https://github.com/mozilla/addons-server/pull/2427 a look?

**Comment by EnTeQuAk** [comment]
I feel quite confident that finally fixes things but having as many eyes as possible looking at it is probably a good idea to make sure we're not missing anything.

**Comment by mathjazz** [comment]
@EnTeQuAk I gave it a quick look and from what I can see the strings look OK.

There's one thing you probably need to change in order to not break anything in production, which is plural forms in headers. They seem to be gone.

Current:
https://github.com/mozilla/addons-server/blob/6de6a4594c71fb827adec7e6a0c638d562ca7598/locale/sl/LC_MESSAGES/djangojs.po#L14

PR:
https://github.com/mozilla/addons-server/blob/extract-and-restore-translations-20160416-2/locale/sl/LC_MESSAGES/djangojs.po#L12

**Comment by EnTeQuAk** [comment]
good catch, I'll see to restore the current headers of those files.

**Comment by EnTeQuAk** [comment]
Thanks @mathjazz, fixed those and merged into master.

The plan now is for people to pick up the files and maybe get some feedback or fixed translations and compile them during the next deploy to make sure we didn't break too much.

Please let me know if something's still missing / horribly wrong and feel free to reopen the ticket.

**Comment by mathjazz** [comment]
Thanks @EnTeQuAk!

Some files still lack plural headers, e.g.:
https://raw.githubusercontent.com/mozilla/addons-server/master/locale/de/LC_MESSAGES/django.po
https://raw.githubusercontent.com/mozilla/addons-server/master/locale/sl/LC_MESSAGES/djangojs.po

And there are still some double spaces between sentences in django.po. Search for ".  " and "!  " (punctuation followed by double space).

I guess this one is intentionally?
https://github.com/mozilla/addons-server/blob/master/locale/templates/LC_MESSAGES/djangojs.pot#L564

**Comment by mathjazz** [comment]
I found more problems - there seem to be only 2 plural forms in the file, even if locale supports more forms:
https://raw.githubusercontent.com/mozilla/addons-server/master/locale/sl/LC_MESSAGES/django.po

**Comment by EnTeQuAk** [comment]
@mathjazz some files didn't have them originally afair but I'll check older versions in a bit. 

Oops regarding the two plural forms, I'll fix them.

Regarding a few remaining double spaces: I mostly fixed invasive whitespaces, there might be some left but we'll fix them step by step as we find them. I'll open a separate ticket for that.

**Comment by EnTeQuAk** [comment]
@mathjazz regarding "I found more problems - there seem to be only 2 plural forms in the file, even if locale supports more forms" -> I copied them from how they were so I assumed they were correct. If those are wrong, can we open separate issues for them with a bit more context on what's wrong?

**Comment by mathjazz** [comment]
Before https://github.com/mozilla/addons-server/commit/a6c83a426e0140aaf48b4b16bde2f689dfc31932 landed, this is how e.g. Slovenian `djangojs.po` looked like:
https://github.com/mozilla/addons-server/blob/6de6a4594c71fb827adec7e6a0c638d562ca7598/locale/sl/LC_MESSAGES/djangojs.po

In line 14, you can see the `Plural-Forms` header, which keeps information on how many plural forms are needed for the language (`nplurals=4`) and how are they calculated in production.

In line 18, you can see an example of a pluralized string, where `msgstr` is an array with length 4 (one variant for each plural form).

After https://github.com/mozilla/addons-server/commit/a6c83a426e0140aaf48b4b16bde2f689dfc31932 was merged, the file looked differently:
https://github.com/mozilla/addons-server/blob/a6c83a426e0140aaf48b4b16bde2f689dfc31932/locale/sl/LC_MESSAGES/djangojs.po

The `Plural-Forms` header is gone and the pluralized string mentioned above (now in line 94) only has two translation variants. The 3rd and the 4th one are deleted.

**Comment by EnTeQuAk** [comment]
I see, I'll have another look at those. I thought I restored all of them but possible I failed especially for the plural forms.
