### ISSUE TITLE
Expose a single File for each Version in the API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17839]
follow-up from #16465 - we've dropped multiple files per version at the model/database level and should do the same in the API.  
Note:
- it will be tricky to deploy without breaking anything. Might want to continue exposing files and file initially, deploy that, then following push start using file, then following push remove files.
- v3/v4 must continue to expose a list of files for backwards compatibility.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I made some API requests on the detail/versions/version detail APIs:
- v5 exposes :"file":{} and "files":[] as a list 
- v3,v4 expose only "files":[]

Verified on AMO dev with Postman
