### ISSUE TITLE
Version.files -> Version.file followups

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17837]
follow-up from #16465 with some tidy-ups and changes now we always have a single File for each version.

* [x] Everytime we use prefetch_related() on file (or file__validation), or use transformers to fetch file for a version, we can select_related() to make a join instead now that there is only one file per version
* [x] current_file, all_files etc can go
* [x] find_latest_version() can be simplified
* [x] Devhub code still has some bits expecting multiple files for a version that can be simplified
* [x] There might be some places where we do a distinct() that is no longer necessary. That would be good news for performance of the pages that do that.

Some of this could be split into further smaller issues

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know what to check for this. Thanks!

**Comment by eviljeff** [comment]
@ioanarusiczki there we minor adjustments throughout the code (pretty much anywhere that deals with addons, versions or files) but shouldn't be any noticeable changes.  I'd check devhub submitting and deleting versions works as expected with regards to what is the current version.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- submission, deleting/disabling versions worked for me.
- promoted version cannot be deleted/disabled if previous versions were not promoted versions. 

Verified on AMO stage - FF92(Win10).
