### ISSUE TITLE
HTML tags visible in serch results page on mobile

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1783]
Steps to reproduce:
1. Load AMO-dev on you Android device
2. Make a search

Expected results:
There are no display or layout issues.

Actual results:
Some HTML tags are visible.

Notes/Issues:
Verified on Android 5.0.1 (FF44). 
Screenshot for this issue: 
![2016-02-26_1630](https://cloud.githubusercontent.com/assets/15685960/13354870/4b19e712-dca6-11e5-84dd-c0de9a26e825.png)

**Comment by EnTeQuAk** [comment]
This is already fixed in https://github.com/mozilla/addons-server/pull/1780 which should land soon on -dev.

**Comment by EnTeQuAk** [comment]
fixed in e4969bcecee402eb9879afc62ceebe9a135b8a29

**Comment by ValentinaPC** [comment]
Verified as fixed on FF44(Android 5.0.1)
Postfix screenshot: 
![2016-02-29_1006](https://cloud.githubusercontent.com/assets/15685960/13388851/2bd097e8-decc-11e5-986e-ad68e6df64c2.png)
