### ISSUE TITLE
Update copy for submission flow

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#17831]
We are updating the copy on the submission flow pages to help better set expectations about what happens after a new version has been submitted. 

Copy updates are included in this issue. To see my formatting recommendations and a comparison of current version/updated version, see [this doc](https://docs.google.com/document/d/1U6MfvPUuXF4qOaIiKU1yRBDfxptWqDkzaOYNOu_jS5M/edit#).

---

## Step 1 - distribution step - (for listed and self-distributed submissions)

**Copy updates:**

How to distribute this version

To get started, select how you would like to distribute this version. 

[] **On this site**. Your submission is publicly listed on addons.mozilla.org.

[] **On your own**. After your submission is signed by Mozilla, you can download the .xpi file from the Developer Hub and distribute it to your audience. Please make sure the add-on manifest’s [update_link](https://developer.mozilla.org/docs/Mozilla/Add-ons/Updates) is provided, as this is the URL where Firefox finds updates for automatic deployment to your users.

You can learn more about these options by reading [Add-on Distribution and Signing](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission) on Firefox Extension Workshop.

All add-ons must comply with Mozilla’s [Add-on Policies](https://extensionworkshop.com/documentation/publish/add-on-policies??utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission) and are subject to manual review at any time after submission. 

---

## Step 2 - upload step - (for listed and self-distributed submissions)

No changes. 

---

## Step 3 - source step - (for listed and self-distributed submissions)

**Updated copy:**

Do you need to submit source code? 
Mozilla’s add-on reviewers need to be able to read and reproduce the code in your extension. If they can’t, your extension may be rejected. 

**Do you use any of the following in your extension?**
- Code generators or minifiers
- Tools that combine multiple files into a single file, such as webpack
- Web template engines, both for HTML and CSS
- Any other tool that takes code or files, applies processing, and generates code or file(s) to include in the extension

[] **Yes**  [] **No**

### "Yes" flow

You must submit your extension’s source code. 

**Your source code must include:** 
- Step-by-step build instructions for creating an exact copy of the add-on code. 
- A build script that executes all necessary technical steps. 
- Operating system and build environment requirements. 
- The required version and installation instructions of any programs used in the build process (such as _node_ and _npm_)

Source files (aside from open-source third party libraries) cannot be transpiled, concatenated, minified, or otherwise machine-generated. 

**You can include build instructions in a README file in your source code**, or in the reviewer notes on the next page. 

For more information, please read [Source Code Submission](https://extensionworkshop.com/documentation/publish/source-code-submission?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission) on Firefox Extension Workshop. 

Add source code to your submission
Upload source code: [Browse…] No file selected

### "No" flow
No updates. 

---

### Step 4 - details step - (listed only)
No changes needed. 

---

### Step 4 - finish step - (self-distributed only)

Version signature pending 
You’re done! ✨ You will be notified by email when the signed file is ready to be downloaded from the [Developer Hub](https://addons.mozilla.org/developers?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission). If you do not see an email after 24 hours, please check your spam folder. 

As a reminder, your add-on is subject to manual review at any time. 

[Go to My Submissions button]

--- 

### Step 5 - finish step - (listed only) 

Version submitted
You’re done! ✨ You will receive a confirmation email when this version is published on addons.mozilla.org. Note that it may take up to 24 hours before publication occurs, or longer if your add-on is selected for manual review. If you do not see an email after 24 hours, please check your spam folder. 

As a reminder, your add-on is subject to manual review at any time. 

You can attract users to your extension by adding a detailed description and screenshots to your listing. Get help [creating an appealing listing](https://extensionworkshop.com/documentation/publish/create-an-appealing-listing?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission) on Firefox Extension Workshop.  

[Manage Listing button]

You can also edit this version to add version notes, or source code if your submission includes minified, concatenated, or otherwise machine-generated code. 

[Edit version button] 

[Go to My Submissions button]

--- 

### Notes
The link to "Create an appealing listing" is dependent on [this change](https://github.com/mozilla/extension-workshop/pull/1090) going live on EW.

**Comment by eviljeff** [comment]
(added the step names used in the urls/view functions)

**Comment by diox** [comment]
@caitmuenster should we keep step 2 (upload) as is for unlisted ? See this screenshot where I've highlighted differences with listed submission process:
![your-submission-will-be-automatically-signed](https://user-images.githubusercontent.com/187006/132332901-71565d10-28f7-4d8d-b2e0-dbdb182e68b1.png)

The listed submission process doesn't have the extra text after "Your add-on was validated" and the button is labelled "Continue" instead of "Sign Add-on". To keep the spirit of these clarifications I wonder if we should remove those differences and use the same text for both listed and unlisted for this step.

**Comment by caitmuenster** [comment]
Thanks for flagging, @diox! Yes, I'm in favor of using the same text for listed and unlisted. Let's remove "Your submission will be automatically signed" and change the text on the button to read "Continue."

**Comment by ioanarusiczki** [comment]
@diox My notes are below, after checking this on AMO dev - FF92(Win10):

Step 1 - distribution step - (for listed and self-distributed submissions) - the link is all over "Add-on Distribution and Signing on Firefox Extension Workshop". Should it be only over "Add-on Distribution and Signing"?

![The URL from step one](https://user-images.githubusercontent.com/33448286/133271013-552a39a4-11b1-4089-90b9-55e35f2a7f90.png)


Step 3 - source step "yes" - (for listed and self-distributed submissions) - the last part after "For more information, please read Source Code Submission on Firefox Extension Workshop. " is left as it was before but looking above I am not sure it's ok like this:

![step3 source code last part](https://user-images.githubusercontent.com/33448286/133270545-9e7a6707-1612-4733-8b68-ad3092f2367a.png)

Step 4 - finish step - (self-distributed only) - there's no URL to "Developer Hub" 

![dev hub url step4](https://user-images.githubusercontent.com/33448286/133271647-f7736690-b220-4219-a3d9-0f688abec854.png)


Step 5 - finish step - (listed only) - "As a reminder, your add-on is subject to manual review at any time." is not present in the form on AMO dev. "Creating an appealing listing" URL goes to https://extensionworkshop-dev.allizom.org/documentation/publish/create-an-appealing-listing?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission which right now is a 404. 

_Note:_ Step2(unlisted) - "Your submission will be automatically signed." was removed and "Sign addon" button replaced with "Continue" - that's an expected result.

**Comment by diox** [comment]
> "Creating an appealing listing" URL goes to https://extensionworkshop-dev.allizom.org/documentation/publish/create-an-appealing-listing?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=submission which right now is a 404.

Looks like the correct link is /documentation/develop/create-an-appealing-listing/ :(

Agreed about the rest, it's relatively minor details but we should fix this before it goes to prod.

**Comment by caitmuenster** [comment]
Gagh, thank you. I tried to move it to a different URL but I messed that up... might as well keep it now. Thanks @diox!

**Comment by ioanarusiczki** [comment]
@diox 

I've noticed the fixes on -dev only for now (stage still uses the old forms), 2 questions remain:
Step 3 - source step "yes" -> the phrase "Add source code to your submission" is not present but "Upload source code: [Browse…] No file selected" is there now, maybe expected, can't tell. 
Step 5 - finish step - (listed only) - "As a reminder, your add-on is subject to manual review at any time." is not present

**Comment by diox** [comment]
- For step 3 I simplified it when removing extra duplicate text, it looked a bit weird with the heading followed by the input field directly
- For step 5 I forgot it for listed... can you file a follow-up for that ?

**Comment by ioanarusiczki** [comment]
@diox 
done https://github.com/mozilla/addons-server/issues/17915

I've seen a stage deploy and then checked again - it's also available here. 

The new text from the final steps of a submission Step 4 - finish step - (self-distributed only) and Step 5 - finish step - (listed only) is also available when a new version is submitted. 

Verified on AMO stage - FF92(Win10).
