### ISSUE TITLE
rm blocklist legacy update integration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17840]
We have integration that imports that synchronises back Blocks created/edited on AMO that are marked as legacy to the legacy v2 blocklist. The waffle switch to enable the feature has been disabled for a while now and the feature is no longer needed so we can remove the code.

**Comment by eviljeff** [comment]
@wagnerand is there any value in keeping the data about if a block was in the v2 blocklist (either was imported from it, or was created on AMO and synced back to it), or was originally part of regex block there?

It'd be easier to just remove everything to do with `legacy_id` and forget all about the v2 blocklist but if it's required we can keep the checkbox and messaging around, but set as read-only.

**Comment by wagnerand** [comment]
> @wagnerand is there any value in keeping the data about if a block was in the v2 blocklist (either was imported from it, or was created on AMO and synced back to it), or was originally part of regex block there?
> 
> It'd be easier to just remove everything to do with `legacy_id` and forget all about the v2 blocklist but if it's required we can keep the checkbox and messaging around, but set as read-only.

That can go away.

**Comment by AlexandraMoga** [comment]
I've created a few blocks on AMO -dev with the `blocklist_legacy_submit` switch enabled and the submission form doesn't include the "Include in legacy xml blocklist" checkbox anymore. Also, the Block history doesn't mention the fact that the block was "Included in legacy blocklist." as it use to.

When this lands in stage, I can also double check with kinto that the updates are indeed no longer received.
