### ISSUE TITLE
Allow admins to see all stats pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17858]
### Describe the problem and steps to reproduce it:

1. Log in with a user who has the `STATS_VIEW` permission
2. Access the stats pages of a **deleted** add-on

### What happened?

Users with the `STATS_VIEW` cannot access the stats pages.

### What did you expect to happen?

Users with the `STATS_VIEW` should be able to access the stats pages.

Note that stats pages for non-deleted add-ons should work just fine already.

**Comment by ioanarusiczki** [comment]
@willdurand 

I went with an admin account after I deleted an add-on to this page:
https://addons-dev.allizom.org/en-US/firefox/addon/620747/statistics/?last=30 

It shows the page into a continuous loading state with 404s in the network

![lots of 404s](https://user-images.githubusercontent.com/33448286/132524300-b0cf36ea-41fe-45c1-adeb-80629d32ba87.png)

If I try to click another link, it's a 404 again https://addons-dev.allizom.org/en-US/firefox/addon/None/statistics/downloads/

Statistic Viewers group (with Stats:View permission) - don't see the deleted addon above.

**Comment by willdurand** [comment]
> If I try to click another link, it's a 404 again [addons-dev.allizom.org/en-US/firefox/addon/None/statistics/downloads](https://addons-dev.allizom.org/en-US/firefox/addon/None/statistics/downloads/)

Ugh, for deleted add-ons we don't have a GUID anymore.

**Comment by willdurand** [comment]
I was thinking about using the add-on ID.

**Comment by ioanarusiczki** [comment]
@willdurand Ok, then could you reopen the issue or move it to the next milestone ?

**Comment by ioanarusiczki** [comment]
@willdurand If I manually replace for each URL `None`  with a deleted addon ID I can view the page as an admin. 
https://addons-dev.allizom.org/en-US/firefox/addon/620747/statistics/downloads/sources/?last=30 loads but if I click it from the overview https://addons-dev.allizom.org/en-US/firefox/addon/620747/statistics/?last=30 I still get a 404 because the ID is replaced by `None`. 
I checked for an unlisted deleted addon too - in this case it is not working.

**Comment by willdurand** [comment]
> [addons-dev.allizom.org/en-US/firefox/addon/620747/statistics/downloads/sources/?last=30](https://addons-dev.allizom.org/en-US/firefox/addon/620747/statistics/downloads/sources/?last=30) loads but if I click it from the overview [addons-dev.allizom.org/en-US/firefox/addon/620747/statistics/?last=30](https://addons-dev.allizom.org/en-US/firefox/addon/620747/statistics/?last=30) I still get a 404 because the ID is replaced by `None`.

That is expected but could you please file an issue to fix that? The problem is that the links in the menu are incorrect. I'd like to fix this problem for next week (it isn't critical but nice to have).

>  I checked for an unlisted deleted addon too - in this case it is not working.

Unlisted do not have download stats but you should be able to access the overview and the usage stats.

**Comment by ioanarusiczki** [comment]
Done https://github.com/mozilla/addons-server/issues/17880
Verified on AMO dev - FF91(Win10).
