### ISSUE TITLE
Failed addon installation if specific contribution option is set

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1785]
See https://bugzilla.mozilla.org/show_bug.cgi?id=901787 for more details.

STR: 

- Add an addon
- Setup contributions.
- Set contributions to "Ask before users can download this add-on"
- On Android try to install the addon.

What happens:

Installation fails.

What should happen:

The contributions options should be shown prior to download.

**Comment by muffinresearch** [comment]
So I don't know what the answer is here. The roadblock page doesn't have a mobile version. 

Presumably we're doing something wrong in terms of handing a the roadblock link to FF Android when it can only handle a download.

<img width="522" alt="meet_the_muffinresearch_developer____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/13362897/a54dc9a2-dcbe-11e5-9e1a-5f4d8ed14cd3.png">

**Comment by muffinresearch** [comment]
Also even if you just ask for normal contributions (not before or after download) there's no contribution UI for the mobile view at all.

**Comment by muffinresearch** [comment]
So from the discussion with Andy on irc - the next steps are going to be to see how we can just make sure FF android always gets handed a download.

I'll look into doing that next week. 

Assuming that's viable we'll make FF Android bypass the contributions entirely and update the UI on "Manage Payments" to reflect it's desktop only.

**Comment by muffinresearch** [comment]
QA Notes for the patch in #1796:

On android / mobile layout regardless of the contributions settings under payments you should:
 * be able to download and install an addon

On Desktop 
  * Contributions should work as before with all settings. If necessary compare with prod to see how things work now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7, Android 5.0.1).
Postfix screencast for desktop: http://screencast.com/t/W4kAhRTVI
On Android the add-on can be downloaded and installed without any issues.
Postfix screenshots: 
![2016-03-10_1602](https://cloud.githubusercontent.com/assets/15685960/13671617/90c96ffc-e6d9-11e5-87f6-0d6fe3fd7738.png)
