### ISSUE TITLE
500 page should not query the database

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17861]
### Describe the problem and steps to reproduce it:

When a 500 page is displayed, it queries the database (looking for a site notice
in `Config`) but if the 500 is initially caused by MySQL, then we'll end up with
a many errors until the stack is exhausted.

### What did you expect to happen?

We should not query the database when we display a 500 page, which means:

- no configuration should be retrieved from the DB
- no authentication stuff should be involved
- the 500 page should be as static as possible

### Anything else we should know?

The issue with `Config` is that the 500 template inherits a "base" template,
which is where the site notice is displayed.

**Comment by willdurand** [comment]
We updated the 500 page in https://github.com/mozilla/addons-server/pull/14285

**Comment by eviljeff** [comment]
> 
> 
> We updated the 500 page in #14285

500 handing was last updated then, but we've been querying the db for the site notice for a [_lot_ longer](https://github.com/mozilla/addons-server/commit/8f3c496470048db2e2a69ce658c564afdfba8a29)
