### ISSUE TITLE
Add-ons with ID > 80 chars

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17863]
We're going to enforce a new limit on the length of add-on IDs, see: https://github.com/mozilla/addons-linter/issues/3896. There are a few existing add-ons with IDs > 80 chars. Most of them seem disabled/deleted/unused.

Is there anything we should do on these add-ons? Like having a migration to truncate their IDs and/or get in touch with developers to update the IDs?

**Comment by diox** [comment]
Since they are all deleted/disabled we're in no rush to do anything - we don't have to change the database definition yet.

**Comment by willdurand** [comment]
Alrighty, the new restriction has been deployed on prod last night. If there is nothing else to do right now, we can close this issue.
