### ISSUE TITLE
Uploading an add-on with a GUID in non string format triggers a server error

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#17874]
### Describe the problem and steps to reproduce it:
1. Submit an add-on with a GUID in non string format, for example:
```
"browser_specific_settings": {
  "gecko": {
    "id": 12345
```
2. Check the validation results

### What happened?
"There was a problem contacting the server" error message is received with a 500 response
![image](https://user-images.githubusercontent.com/31961530/132530234-33e445ea-4fec-4d10-affc-2a51bb77ab53.png)

### What did you expect to happen?
The error message should mention that the GUID needs to be in string format and no server error should be triggered

### Anything else we should know?
- reproduced on all AMO servers
- the linter already handles this exception and has an error message for it:

```
Code                     Message                 Description                                 File            Line   Column
MANIFEST_FIELD_INVALID   "/browser_specific_s…   See https://mzl.la/1ZOhoEN (MDN Docs) for   manifest.json              
                         ettings/gecko/id"       more information.                                                      
                         should be string                                                                               
```

**Comment by willdurand** [comment]
That could be a problem during manifest normalization.

**Comment by willdurand** [comment]
mm this looks more like a deserialization issue. I guess we don't have tests for this. We call `.lower()` on the GUID but if its value is an int, the method does not exist.

**Comment by diox** [comment]
Good catch. Anything that is done with the manifest before validation needs to be extra careful about type & presence of keys we want to read from the manifest...

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/133086421-cb55a46e-6b1b-4aa0-a449-f915955150d9.png)
