### ISSUE TITLE
Link to AMO stats in review page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17883]
Once https://github.com/mozilla/addons-server/issues/17880 is fixed, we'll have fully functional stats pages on AMO for deleted add-ons, which might be useful to reviewers with privileged access.

Let's add a link to the review detail page to easily access these stats pages on AMO: this is needed because, for deleted add-on, we need to use the add-on ID instead of slug in all the URLs.

**Comment by ioanarusiczki** [comment]
@willdurand 

- Statistics URL is available for deleted addons into Actions section on a review page only for admins, users from Statistics Viewers cannot access deleted review pages ( which I believe it's intended)

- I could access stats from the reviews pages below: 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/620727
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620638
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620740
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/620740
