### ISSUE TITLE
Git error raised on fresh/new celery workers

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17897]
See: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/7896507/?referrer=github_plugin

---

I do wonder why we seem to have Git errors (`PicklingError`, specifically) on what seem to be fresh Celery workers (according to the "breadcrumb" in Sentry). This error does not happen too often but this is weird.

Why would there be a pickle error here? 

```
MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: GitError('failed to insert entry: invalid object specified - <SOME_FILE>')>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'_pygit2.GitError\'>: import of module \'_pygit2\' failed")''.
  File "billiard/pool.py", line 366, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
```

**Comment by diox** [comment]
Note that it's trying to pickle a `GitError`, and that fails, but the fact that we get a `GitError` in the first place is a problem...
