### ISSUE TITLE
replace `FileUpload.automated_signing` with `channel`

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#17911]
the `FileUpload` model has a field called `automated_signing` that nowadays is just the channel - `automated_signing` is `True` when the channel is unlisted, `False` otherwise.  We should change it to channel to be consistent with the `File` model.

Note: this field is exposed in the signing api serializer where we will want to keep it, at least for v3/v4 api endpoints.

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa.
Thanks!

**Comment by eviljeff** [comment]
QA: constants were renamed all over the code-base, but any regressions are most likely going to come from:
* the api responses for uploads from the signing api, or the addon submission api, or
* actions that create uploads - so submitting a new addon/version via devhub, or the signing api, or the submission api.

There shouldn't be any change in functionality.

**Comment by AlexandraMoga** [comment]
I've verified add-on uploads for:
- new addon uploads - with the signing api, submissions api and Devhub
- new version uploads - with the signing api, submissions api and Devhub

I haven't noticed any differences in behavior on -dev. I'll also quickly check stage once the code lands there as well.

**Comment by AlexandraMoga** [comment]
I haven't found issues on stage either.
