### ISSUE TITLE
Review statistics emails are broken

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#17927]
Add-on review statistics emails are no longer sent.

Reason: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/13213508/
Caused by: https://github.com/mozilla/addons-server/commit/8a841dd461f642131b075890b36dc0ad7626097c

Marking this as a P1, so it gets fixed this week and we can re-run the task to have the email sent before the end of the week. (Email is sent weekly so next week would be too late.)

/cc @eviljeff

**Comment by ioanarusiczki** [comment]
@wagnerand 
I don't remember e-mails related to stats when checking the fake e-mails on dev or stage.  
Could this be related with https://github.com/mozilla/addons-server/issues/17925 ? I checked ratings/reviews feature - on dev/stage it's working but the issue might not refer to ratings e-mails.

**Comment by eviljeff** [comment]
This is a weekly report of reviewer activity, rather than user ratings.  

I'm not sure if it's testable on dev/stage tbh - @wagnerand if I triggered the cron job manually on addons-dev, would it be reviewer activity in the previous week from that point, or always Monday-Monday?

**Comment by wagnerand** [comment]
> I'm not sure if it's testable on dev/stage tbh - @wagnerand if I triggered the cron job manually on addons-dev, would it be reviewer activity in the previous week from that point, or always Monday-Monday?

It's always the last seven days (+ current quarter). Unfortunately that also means we can't just re-run the task on prod after the push :(

**Comment by wagnerand** [comment]
I misspoke. Past me was smart enough to make this Monday-Monday always!

**Comment by eviljeff** [comment]
I've just triggered the report generation on addons-dev

**Comment by ioanarusiczki** [comment]
@eviljeff 
2 e-mails arrived:
one to  [addon-content-reviewers@mozilla.com ](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/96897/change/)
the other one to  [addon-reviewers@mozilla.org](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/96896/change/)
both with a weird format, it's a lot of HTML.

**Comment by eviljeff** [comment]
it's supposed to be html but I wouldn't know if it's any more weird than before.  @wagnerand is this something you could confirm?  Or are you happy with waiting for it to hit prod?

**Comment by wagnerand** [comment]
I checked the HTML, looks good to me.
