### ISSUE TITLE
No longer receiving email notifications for AMO reviews

### ISSUE THREAD

**Issue by ghostwords** [mozilla/addons-server#17925]
### Describe the problem and steps to reproduce it:
I stopped getting notified about [new reviews for Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/reviews/) a few weeks ago.

### What happened?
No more review emails.

### What did you expect to happen?
I get an email when there is a new review.

### Anything else we should know?
The latest review notification is from 8/28/2021. The review emails must have stopped some time shortly afterwards.

**Comment by ghostwords** [comment]
When might this be fixed?

**Comment by AlexandraMoga** [comment]
I've checked the [Fake mail logs](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/67470/change/) on stage and, as far as I can see, ratings notifications are still being sent.

@ghostwords just to be sure, could you please confirm that:
- you checked that these emails aren't in your spam folder
- you've enabled ratings notifications in your account details:
![image](https://user-images.githubusercontent.com/31961530/134865104-34460ec8-b81d-4ca0-8515-ad66cb9b3c13.png)

**Comment by ghostwords** [comment]
Ahh, thank you! The "someone writes a review of my add-on" checkbox was unchecked.

But! I never visited this page before, and I have been getting emails up until the end of August. Something changed. Are other AMO users similarly affected?

**Comment by ghostwords** [comment]
@AlexandraMoga So this happened again, "someone writes a review of my add-on" got unchecked sometime inbetween now and when I last re-enabled it on September 27th. Is this the right repository for this bug?

**Comment by AlexandraMoga** [comment]
@ghostwords so far, I haven't run into such an issue with my test users and there were no other reports of its occurrence. 
That being said, could you please re-enable the notification in your profile page and keep a closer look at the emails you receive when someone rates your add-on? If you notice the issue again, we might be able to narrow down the timeframe in which it happened and identify what caused it.

**Comment by ghostwords** [comment]
Sure thing, I'll let you know when I notice it next.

**Comment by diox** [comment]
If you notice that again, please don't change your notification preferences so that we can investigate a little bit more in the database (notably we store the date of the last modification so that would be helpful to see what it is when that problem occurs for you - but it's too late if you make another change to set it back)
