### ISSUE TITLE
Switching to any language, text for "Enter your Email" does not change

### ISSUE THREAD

**Issue by yash14123** [mozilla/addons-server#1792]
![b](https://cloud.githubusercontent.com/assets/9817962/13390671/e0e353d6-def5-11e5-8ca4-187b2d0b5b27.png)

**Comment by muffinresearch** [comment]
Looks like the string is correctly wrapped in the necessary translation function, but since it's a fairly recent addition it's not yet been extracted. Once that's been done it should get translated correctly.

**Comment by muffinresearch** [comment]
This will be fixed in due course - so on that basis I'm going to close this.

**Comment by ValentinaPC** [comment]
Based on previous comments and verified on AMO-dev FF44(Win 7) => the "Enter your Email" is translated.
Please see the screencast: http://screencast.com/t/VUeGi9D8y
