### ISSUE TITLE
Expose addons-linter version on __version__ endpoint

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#17939]
In order to quickly identify which version of the linter is currently used by
AMO, it would be handy to expose its version (taken from the `package.json`
file) in the `/__version__` response.

**Comment by AlexandraMoga** [comment]
The `addons_linter` (current) version is displayed in the `__versions__` endpoint:

![image](https://user-images.githubusercontent.com/31961530/134633513-b4af063e-8cfa-45aa-8699-768cf9c65ea7.png)
