### ISSUE TITLE
Bad UX when no results are returned in the theme queue search

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1794]
The theme queue search show nothing when there's no results. 

A nicer error message should be shown.

<img width="553" alt="editor_tools____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/13394860/f7643ffc-dee2-11e5-97db-c896b92f7b44.png">

**Comment by muffinresearch** [comment]
Interestingly this bug only appears if you directly do a search with no results. If you get some results first and then do a search that returns nothing the correct error is shown.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/03Zexw96
