### ISSUE TITLE
Users is not able to upload - Gets oops page after validation

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons-server#1797]
A user is trying to update his addon. He is succesfully able to get through validation. However when he clicks "Add" he gets a "Oops" page. The addon is here - https://addons.mozilla.org/en-US/firefox/addon/si%C5%ABlyk-antra%C5%A1t%C4%99/

This a screenshot of his issue:

![](http://i.imgur.com/dv7Qkol.png)

**Comment by eviljeff** [comment]
It would be best to have the offending .xpi to try to replicate.

**Comment by DavidBruant** [comment]
Possibly the same error than https://bugzilla.mozilla.org/show_bug.cgi?id=1252394

**Comment by aemdy** [comment]
XPI attached.
[firefox-release.xpi.zip](https://github.com/mozilla/addons-server/files/156202/firefox-release.xpi.zip)

**Comment by andymckay** [comment]
I can no long reproduce this on -dev, there have been a few changes since this bug, @aemdy could you retry please? If it still occurs then we can re-open.
