### ISSUE TITLE
Move to node 4.x LTS for addons-linter integration.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1799]
Since we're looking to use node 4.x and above for the addons-frontend it might make sense to update the node version we're proposing to use for the linter.

/cc @EnTeQuAk

**Comment by EnTeQuAk** [comment]
Let's cc @jasonthomas on this so he can start working on packaging up node 4.x for our servers. Should we open a bugzilla ticket separately for this?

**Comment by muffinresearch** [comment]
Yeah you'll want an ops bug in bugzilla for that.

**Comment by EnTeQuAk** [comment]
Does the linter theoretically work on 4.x already or is there more work needed?

**Comment by jasonthomas** [comment]
We are mirroring nodesource 4.x already, https://github.com/mozilla-services/puppet-config/blob/0f92cc8a9d1ca3f635908f7d36f89c14df5a20a9/common/modules/yum/manifests/repos/nodesource_4x.pp

**Comment by EnTeQuAk** [comment]
I don't have access to that repo but that's awesome then. Since I can't see the link, can you give me the correct mirror? Our current mirror is:

`baseurl=https://s3-us-west-2.amazonaws.com/net-mozaws-prod-us-west-2-ops-rpmrepo-mirror/nodesource/0.12/7/x86_64/`

Same mirror but only `4.x` instead of `0.12`?

**Comment by jasonthomas** [comment]
Yes, replacing 0.12 with 4.x should work.

**Comment by EnTeQuAk** [comment]
Supports https://github.com/mozilla/addons-linter/issues/62

**Comment by EnTeQuAk** [comment]
added https://bugzilla.mozilla.org/show_bug.cgi?id=1254553 to upgrade nodejs on dev, stage and prod
