### ISSUE TITLE
User can re-submit a deleted add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1800]
Steps to reproduce:
1. Log in to AMO-dev https://addons-dev.allizom.org/
2. Submit an add-on 
3. Delete that add-on
4. Re-submit the deleted add-on

**Expected results:**
User cannot submit the same add-on.

**Actual results:**
User can submit the same add-on.

Notes/Issues:
**This reproducing for the same user and for different users.**
Verified on FF44(Win 7). Issue is reproducing on AMO-stage, dev, and prod.
Screencast for this issue: http://screencast.com/t/VvNxDvNgPlHU

**Comment by wagnerand** [comment]
This is intended behavior. The same user should be able to resubmit the add-on, however other users should not.

**Comment by wagnerand** [comment]
It seems like we don't prevent re-usage of deleted GUIDs for other users if the deleted add-ons had the status `INCOMPLETE`.

Adding @eviljeff to confirm, and discuss about whether we want to change that.

**Comment by ValentinaPC** [comment]
After talking on irc, we concluded that: an INCOMPLETE add-on is hard-deleted... so there are two cases when above issue is reproducing:
1. Submitting an add-on but not completing the submission process (add-on status is incomplete) and after that deleting the add-on.
2. Submitting the add-on - deleting its version (add-on status is incomplete) and after that deleting the add-on.

**Comment by eviljeff** [comment]
going to change the check to be INCOMPLETE & no versions.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF44(Win 7) the following cases:
a) submit add-on, delete all versions (add-on is incomplete), delete add-on - another user receives "duplicate ID" when trying to submit the deleted add-on.
b) submit add-on, disable all versions (add-on is incomplete), delete add-on - another user receives "duplicate ID" when trying to submit the deleted add-on.
c) start the submission but stop at step 3 in the submission process (add-on is incomplete), delete add-on - another user receives "duplicate ID" when trying to submit the deleted add-on. 
d) submit add-on (add-on status is complete), delete the add-on - another user receives "duplicate ID" when trying to submit the deleted add-on.

Closing bug.
