### ISSUE TITLE
Clean up / tighten addons-server CSP config

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18012]
When #18010 is fixed and the dust has settled, we can clean up and tighten down the CSP a little bit:
- Remove `https://addons.mozilla.org` from `CSP_BASE_URI`
- Remove references to `PROD_CDN_HOST`
- Remove (hardcoded) reference to `https://static.addons.mozilla.net`
- Remove `CSP_CONNECT_SRC` customization in each env setting file (just need to connect to self, sentry, google analytics)
- Set `CSP_DEFAULT_SRC` to `'none'`
- Remove `'self'` from CSP_CHILD_SRC ? I don't think we need it
- Remove `data:` from `CSP_IMG_SRC ? I don't think we need it either nowadays (`blob:` is required for image uploads)
- Remove `'self'` from `CSP_STYLE_SRC` ? Having the static URL should be enough.

**Comment by diox** [comment]
In the CSP config, we can also:
- Remove `https://addons.mozilla.org` from `CSP_BASE_URI`
- Remove references to `PROD_CDN_HOST`
- Remove (hardcoded) reference to `https://static.addons.mozilla.net`

**Comment by AlexandraMoga** [comment]
I couldn't find any other regressions in Dehub, Revtools, Statistics page caused by this CSP change. 

I'm marking this issue as verified fixed on stage.
