### ISSUE TITLE
Replace geoip with CDN headers

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18022]
We use geoip to record the country of the reporter in abuse reports. Now that we're behind a CDN, requests should already be coming through with a header containing that information, no need to look it up ourselves from the IP through geoip.

We should make the header name configurable to make it easier to change CDNs in the future. On Cloudfront the header name is `CloudFront-Viewer-Country`.

**Comment by ioanarusiczki** [comment]
@eviljeff I checked abuse reports on admin/rev tools on AMO dev -> the country of the reporter is displayed. 

If there's anything else I should check , let me know.
