### ISSUE TITLE
Review page for add-on with only deleted versions shows 404.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1802]
This is related to #1585.

STR:
1. Upload an add-on.
2. Delete all versions.
3. Access its review page.

Expected results:
The review page should be shown.

Actual results:
A 404 is shown.

**Comment by eviljeff** [comment]
Doesn't the same logic that @jvillalobos gave in #1585 apply here though?  I.e. it's no big problem because there isn't anything you can do on the page anyway.

**Comment by wagnerand** [comment]
We already make sure that reviews cannot be submitted if no file is in a pending state.
You could do several things on that page:
* Inspect files
* Send info requests
* Attach comments
* Update the whiteboard

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-03-10_1719](https://cloud.githubusercontent.com/assets/15685960/13674017/870e335c-e6e4-11e5-9188-9b11883c496d.png)
