### ISSUE TITLE
implement full license selection/definition for addon submission api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18034]
follow-up for #7811 

currently you can only select from pre-defined licenses - and only by specifying a numeric license id. 

So worked needed to:
- implement the ability to create a custom license
- ~select from predefined licenses by slug or some other mnemonic~ #18361
- ~maybe make the field optional (for listed versions only?) and default to all rights reserved, or the previous license for subsequent versions~ #18367

**Comment by ioanarusiczki** [comment]
@eviljeff I tested on -dev  that built-in licenses match the add-on type part with PATCH requests using the versions endpoint -> I can no longer send a non-theme license to a theme or a non-extension license to webextensions.

About the custom license, could you give a model of the JSON I should be using?

**Comment by eviljeff** [comment]
It's set as `"custom_license": {"name": {"en-US": "foo"}, "text": {"en-US": "baa"}}` https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#post--api-v5-addons-addon-(int-addon_id|string-addon_slug|string-addon_guid)-versions-

**Comment by ioanarusiczki** [comment]
@eviljeff Ups, I forgot about that docs were updated, however I did not think this would be there already. Thanks!

**Comment by ioanarusiczki** [comment]
@eviljeff I could add the custom license at : addon creation, version submission and make changes on specific versions using patch requests. 

Some JSON examples:

PATCH with {"custom_license": {"name": {"en-US": "foo"}, "text": {"en-US": "baa"}}}

POST with  {"categories": {"firefox": ["other"]}, "version": {"upload": "0604d513159246f2b982d41f0d28220d","custom_license": {"name": {"en-US": "foo", "ro":"licenta"}, "text": {"en-US": "baa" , "ro": "avem licenta de test"}}}

POST with {"upload": "056ba4502ba34ca2a7a9791e952a5766", "custom_license": {"name": {"en-US": "foofighters", "ro":"licenta pentru un test"}, "text": {"en-US": "babablackship" , "ro": "avem licenta de test"}}}

**Comment by ioanarusiczki** [comment]
@eviljeff To add:  "Both `license` and `custom_license` cannot be provided together." is a 400 - as expected.
