### ISSUE TITLE
Add-on admin page does not show deleted versions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1803]
STR:

1. Upload an add-on.
2. Delete the version.
3. Go to: .../admin/addon/manage/<slug>

Expected results:
Page should show deleted versions.

Actual results:
Page does not show deleted versions.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screencast: http://screencast.com/t/pymhKgHS4
