### ISSUE TITLE
Add-on review page says the file of a deleted version is pending review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1804]
STR:

1. Upload an add-on.
2. Delete the first version.
3. Upload a second version to that add-on. (so that the review page is available)
4. Go to the review page.

Expected results:
Entry for deleted version on review page should not say "Pending ... review" for that file.

Actual results:
![screen shot 2016-03-01 at 12 32 56](https://cloud.githubusercontent.com/assets/873258/13425814/956051d4-dfa9-11e5-8a72-7052c8025572.png)

**Comment by eviljeff** [comment]
The status of the file is still STATUS_PENDING, so I just indicated the Deleted in the Version line at the top instead.  I thought we'd want to retain that information even for deleted versions/files.  I can change though?

**Comment by wagnerand** [comment]
Should we change the status of the file to `STATUS_DISABLED`?

**Comment by eviljeff** [comment]
> Should we change the status of the file to STATUS_DISABLED

Why?

**Comment by wagnerand** [comment]
Because we do that as well if a developer uploads an update to their already pending submission. If a developer deletes a version, the attached files are not pending review, so we should set their state correctly.
Additionally I am almost sure that at least some code relies on there being only one file or set of files for one version in a pending state.

**Comment by eviljeff** [comment]
All the existing django code ignores deleted versions as the default `objects` manager filters them out (I had to change the queries in the few places we want them exposed) so I'm more concerned about something not being triggered because they're not really deleted than them tripping up some other function.  But we can set the files to STATUS_DISABLED if you think that's most appropriate.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-03-02_1246](https://cloud.githubusercontent.com/assets/15685960/13458257/04155798-e075-11e5-89b7-920af7444132.png)
