### ISSUE TITLE
Make File.manifest_version required

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18048]
currently we have a default for File.manifest_version of `2` for new File instances, and if there are any stray non-webextension File records in the database, some with a `null` value.  Once all files are webextensions and the `is_webextension` property is gone we can make the field required and non-null - if the manifest_version hasn't been parsed from the manifest something has gone wrong and it's better we error.

**Comment by eviljeff** [comment]
Most of the work for this will likely be in updating some of the ancient fixtures that don't define `manifest_version`, fwiw

**Comment by Taffyqueen83** [comment]
Luisana Ayers

**Comment by ioanarusiczki** [comment]
@eviljeff In case this can be tested by qa, pls add some str.

**Comment by eviljeff** [comment]
@ioanarusiczki QA: just check the standard uploading of a new addon or version works.  

Also try to upload an manifest_version = 3 manifest on dev and stage.  I believe the waffle switch for mv3 submission is enabled on dev (i.e. can submit) but disabled on stage.  (If you let me know the ids of the submissions afterwards I can double-check the database records too - it's not exposed otherwise, iirc)

**Comment by ioanarusiczki** [comment]
@eviljeff On AMO dev: 622088 with MV2
622090 and 622089 for MV3

I'll wait until tomorrow then try again on AMO stage too.

**Comment by eviljeff** [comment]
> @eviljeff On AMO dev: 622088 with MV2 622090 and 622089 for MV3

> File.objects.filter(version__addon_id__in=(622088,622089,622090)).values('version__addon_id', 'id', 'manifest_version')
> {'version__addon_id': 622088, 'id': 415372, 'manifest_version': 2}, 
> {'version__addon_id': 622088, 'id': 415373, 'manifest_version': 2}, 
> {'version__addon_id': 622088, 'id': 415374, 'manifest_version': 2}, 
> {'version__addon_id': 622089, 'id': 415375, 'manifest_version': 2}, 
> {'version__addon_id': 622090, 'id': 415376, 'manifest_version': 3}, 
> {'version__addon_id': 622090, 'id': 415377, 'manifest_version': 3},

i.e. I'm seeing that only the two files for 622090 were `manifest_version=3` (_not_ 622089) - can you confirm?

**Comment by ioanarusiczki** [comment]
@eviljeff Hmm, strange, 622089 is not good, so I submitted another one 622091 - a theme with MV3

**Comment by eviljeff** [comment]
> {'version__addon_id': 622091, 'id': 415378, 'manifest_version': 3}

That's coming back as manifest_version=3 :+1:

Oh, I realized this field is exposed in django admin in the File page if you need to check yourself in the future.

**Comment by ioanarusiczki** [comment]
@eviljeff I see it now, it's "Manifest version": 
Let me know if I should re-test it on -stage too.

**Comment by eviljeff** [comment]
> @eviljeff I see it now, it's "Manifest version": Let me know if I should re-test it on -stage too.

It's fine - now I think about it the waffle switch gating mv3 is checked before where I made the change (in the `File` model) so it won't be affected - no need to recheck on stage.
