### ISSUE TITLE
Remove/simplify reviewer scoring feature

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18049]
Long ago we started a volunteer reviewer programme on AMO, and created a way of scoring actions in the reviewer tools to be able to incentive and then reward individuals based on their contributions. Over time the mix of paid and volunteer reviewing has changed, and the types of actions are very different now when almost all "reviews" are post-approval checking of webextensions.

At a minimum the ReviewerScore code needs updating to reflect the main use cases nowadays (it currently focuses on pre-review add-ons, which are the exception and handled by paid mozilla staff); perhaps even removed entirely if it's not used by a significant number of users.

cc @caitmuenster for input on how reviewer incentive scores are currently used and her thoughts on what should change

**Comment by wagnerand** [comment]
I suppose we can delete it.

**Comment by wagnerand** [comment]
> @wagnerand so, it seems like all the review reports are built around the reviewer incentives (they all join on reviewer_scores) so they're empty with no scores - at least in the tests anyway. Do they have any value beyond that or can they be removed too?

The reviewer reports have value and while we could remove the reference to scores there, the join is used on purpose as that was the only way I could find to identify a single review. A review can span one or more versions, and the same add-on could be reviewed multiple times a day. Do we have a good replacement to detect a single review?

**Comment by eviljeff** [comment]
> > @wagnerand so, it seems like all the review reports are built around the reviewer incentives (they all join on reviewer_scores) so they're empty with no scores - at least in the tests anyway. Do they have any value beyond that or can they be removed too?
> 
> The reviewer reports have value and while we could remove the reference to scores there, the join is used on purpose as that was the only way I could find to identify a single review. A review can span one or more versions, and the same add-on could be reviewed multiple times a day. Do we have a good replacement to detect a single review?

Mmm, not really - originally reviews were always for a single version so the `ActivityLog` record for version/add-on _was_ the review, and when the reviewer tools were changed to review multiple versions there wasn't a requirement to log an additional `ActivityLog` for the review itself.  

So, looks like we need something to track reviews. (Which, imo, we should be adding anyway if there's a need for it, rather than ~mis~re-using the reviewer score records, even if it weren't a blocker here).

**Comment by eviljeff** [comment]
From some investigation:
- For just the purpose of building the reviewer reports we should be able to re-use the ActivityLogs we already create and group reviews involving multiple version by timestamp (they're logged with _exactly_ the same timestamp)
- Not all reviewer tools actions create reviewer scoring records currently (so some reviews won't have been counted in the reports) - it was aimed at volunteer reviewers so any reviews that were never historically undertaken by volunteers didn't get scored. Such as:
  - processing super review requests
  - unrejecting versions
  - any unlisted version reviews

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-59
