### ISSUE TITLE
Remove note about review delay from version deletion dialog.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1805]
If a developer deletes a version, a dialog appears that among other information contains the following paragraph:

`Deleting a version which has already been reviewed may also cause a significant delay in the review of your next update.`

We should delete that paragraph now that we have soft-deletion for versions to unclutter that dialog.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF44(Win 7).
Postfix screenshot: 
![2016-03-02_1237](https://cloud.githubusercontent.com/assets/15685960/13458065/1072d57a-e074-11e5-948a-917603de4fee.png)
