### ISSUE TITLE
drop all support in codebase for ADDON_PLUGIN type

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18050]
we've not had plugins for years but the constant is still referenced in a few places - lets drop that and deprecate like we did `ADDON_SEARCH`, etc.  (`ADDON_LPADDON` can probably go too)

**Comment by rpl** [comment]
mentor: @eviljeff 

Andrew, would you mind to put some guidance in a comment.

**Comment by dante381** [comment]
Hello, Can i be assign

**Comment by dante381** [comment]
Hello, Can I be assigned to this issue?

**Comment by eviljeff** [comment]
> Can I work on this?

Hi, yes, go ahead.

**Comment by ioanarusiczki** [comment]
@eviljeff I'm not sure how this code removal could affect the server. Could you add some str?
