### ISSUE TITLE
Remove D2C_MIN_VERSIONS and associated code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18074]
`D2C_MIN_VERSIONS` was created to handle the differences in behavior between Firefox 4.0 and previous versions - Firefox 4.0 is when we started ignoring max compatibility for add-ons, unless the `strictCompatibility` property was enabled. (D2C means Default To Compatible).

We obviously haven't cared about Firefox < 4.0 for a long time, and we switched to WebExtensions anyway, so we can remove all code left related to "d2c" and consider everything is "default to compatible" - there isn't much left, but there are still some traces, like `D2C_MIN_VERSIONS`. The notion of strict compatibility needs to stay for now though, we still need it for some cases.

**Comment by dojutsu-user** [comment]
@diox 
Got it. Thank you.
