### ISSUE TITLE
Move the blocklist views to Kinto

### ISSUE THREAD

**Issue by tarekziade** [mozilla/addons-server#1808]
We're going to move the blocklist views to grab the data from Kinto instead of the Django Database. This bug is a place holder for this work

cc @andymckay @magopian

**Comment by andymckay** [comment]
Please ensure this is behind a waffle flag, so we can flip it when kinto is good to go.

**Comment by andymckay** [comment]
The only thing I think we need to do here is set up redirects to the Kinto pages when they land.

**Comment by eviljeff** [comment]
This is done, afaik.
