### ISSUE TITLE
Remove page caching that uses memcached

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18083]
We cache 2 views using `@cache_page` (collections add-ons list and language tools APIs), which uses the default cache backend (memcached in our case). With the CDN and nginx caching that shouldn't be necessary anymore, just returning `Cache-Control` header should be enough.

**Comment by diox** [comment]
For reference, as of today, here is the full usage of memcached in addons-server if we remove views caching:
- `amo/celery.py`: cache start time for each task in order to compute total task time when it ends
- `amo/utils.py`: a cache namespacing utility, that uses an intermediary cache key to be able to clear an entire key space (e.g. be able to clear all cache keys for a specific feature). Only used in reviewer tools score cache, so if that
  goes we could remove it entirely.
- `lib/cache.py`: `memoize` and friends, to be removed, see https://github.com/mozilla/addons-server/issues/18085
- `ratings/tasks.py`: cache all rating/total ratings aggregates for all valid add-ons for 60 hours. Not sure how useful that is, yes the task is called often but the query is super fast. Could be ran on a replica though, and should probably be limited to
  public add-ons.
- `devhub/tasks.py`: cache the validation task id for a given file upload, so that we don't validate the same thing twice. We should investigate whether that's really useful, cause it should not happen - this was from a time when we could have unvalidated uploads  laying around and reviewers could manually trigger validation (https://bugzilla.mozilla.org/show_bug.cgi?id=1191603)
- `users/models.py`: cache denied names for default duration (500 seconds)
- `applications/views.py`: cache list of applications versions for default duration
- `reviewers/models.py` and `reviewers/views.py`:
  - cache addon id being reviewed to "lock" it for a short period
  - cache a bunch of reviewer score related things (user score, recent points awarded, breakdown for a user, breakdown for a user since a certain date, leaderboard). https://github.com/mozilla/addons-server/issues/18049 might remove that.

**Comment by diox** [comment]
That would solve https://sentry.io/organizations/mozilla/issues/3724633388/?project=6224627&query=is%3Aunresolved&referrer=issue-stream (only seen on dev for the moment, but could technically happen on other envs as well depending on collections content)

**Comment by diox** [comment]
For the collections endpoint, we should also bump the caching duration to account for CDN potentially evicting the response from their cache (since we're not in complete control of that)

**Comment by diox** [comment]
This would solve the Sentry issue referenced above, which we have only observed on dev for the moment but could technically happen on any environment. We have done work in the past to work around this issue by caching a leaner data structure, but the underlying problem would remain if we keep using memcached for this.

**Comment by diox** [comment]
QA:
- See if language tools page and mozilla collection pages still work properly
- Repeat with API calls for those pages (for example https://addons-dev.allizom.org/api/v5/addons/language-tools/?app=firefox&type=language&appversion=100.0, https://addons-dev.allizom.org/en-US/firefox/collections/4757633/privacy-matters/)

**Comment by ioanarusiczki** [comment]
@diox 

 **Lang-pack page:**

I submitted lang packs today, for example [this one ](https://addons-dev.allizom.org/en-US/firefox/addon/afrikaans-language-pack_test/) and all from the Arabic column on https://addons-dev.allizom.org/en-US/firefox/language-tools/ 

With a login: all  the new langpacks are visible on https://addons-dev.allizom.org/en-US/firefox/language-tools/, I see in the header -> cache-control: max-age:0

Log out view: when I reload the page the Afrikaans lang pack appears then dissapears, the Arabic lang packs did not appear yet. 
-> cache-control: max-age:0 

I made several requests from Postman for https://addons-dev.allizom.org/api/v5/addons/language-tools/?app=firefox&type=language&appversion=106.0 with and without authorization -> I found the new submitted lang packs in the response. -> cache-control max-age=86400

 **Mozilla collections:** 

I checked 
https://addons-dev.allizom.org/en-US/firefox/collections/4757633/privacy-matters/
https://addons-dev.allizom.org/en-US/firefox/collections/4757633/featured-add-ons/
https://addons-dev.allizom.org/en-US/firefox/collections/4757633/weather-reports/
https://addons-dev.allizom.org/en-US/firefox/collections/4757633/Large-collection-2/

They are public -> displayed on the frontend for all users

I made API requests from Postman too, such as https://addons-dev.allizom.org/api/v5/accounts/account/mozilla/collections/privacy-matters/, with authorization I see Cache-Control s-maxage=0, unauthorized max-age=180 

When I added an addon into the collection I could see it immediately after -> login view. In logout view -> Appeared after a while.


I think it's fine but if I'm wrong, let me know.

**Comment by diox** [comment]
> Log out view: when I reload the page the Afrikaans lang pack appears then dissapears, the Arabic lang packs did not appear yet. -> cache-control: max-age:0

You should _also_ see `s-maxage=180` for logged out view (header values can either be concatenated and separated with `,`, or included in a separate instance of that same header)

> I made API requests from Postman too, such as https://addons-dev.allizom.org/api/v5/accounts/account/mozilla/collections/privacy-matters/, with authorization I see Cache-Control s-maxage=0, unauthorized max-age=180

When requesting the addons from that collection - add `addons/` to the URL - you should see a `cache-control: max-age=7200`.

**Comment by ioanarusiczki** [comment]
@diox 

> You should also see s-maxage=180 for logged out view (header values can either be concatenated and separated with ,, or included in a separate instance of that same header)

Yes, for logged out view , I see s-maxage=180.  For login view it is s-maxage=0

> When requesting the addons from that collection - add addons/ to the URL - you should see a cache-control: max-age=7200.

For https://addons-dev.allizom.org/api/v5/accounts/account/mozilla/collections/weather-reports/addons/ , there's Cache-Control max-age=7200 for unauthenticated request.  With Authorization ->  s-maxage=0
