### ISSUE TITLE
Clean up usage of STATIC_URL

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18104]
After #18010 is fixed:
- Hunt down any reamining usage of `STATIC_URL` - we should be using `static()` instead most of the time
- Remove `static_url` context processor

**Comment by diox** [comment]
QA: URL for the default icon in all sizes should still point to a valid image and have a unique filename set (`https://addons-dev.allizom.org/static/addon-icons/default-32.1366fe4b2b33.png` for instance) but not query string parameters.

**Comment by ioanarusiczki** [comment]
@diox 
I see the following formats:
https://addons-dev.allizom.org/static-server/img/addon-icons/default-64.d144b50f2bb8.png
https://addons-dev.allizom.org/static-server/img/addon-icons/default-32.2b26add4b394.png 

This view - in edit profile page image section has `?1638195039982` at the end of the URLs
such as 
https://addons-dev.allizom.org/static-server/img/addon-icons/default-64.d144b50f2bb8.png?1638195039982 

![with query](https://user-images.githubusercontent.com/33448286/143882962-983c764c-c034-40e6-a77c-c6b6bc06a6fb.png)

Are these alright?

**Comment by diox** [comment]
Ah yes, I forgot Devhub was doing this. As long as the base URL are `.../addon-icons/default-64.d144b50f2bb8.png` and `.../addon-icons/default-32.2b26add4b394.png` and the added query string doesn't create errors that's fine.

**Comment by ioanarusiczki** [comment]
@diox I filed https://github.com/mozilla/addons-server/issues/18438 but it is not related to the changes made by this patch.
