### ISSUE TITLE
Document addon submission api changes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18116]
Before the addon submission API changes is enabled on prod the docs need updating with details of use.

**Comment by ioanarusiczki** [comment]
@eviljeff I've noticed at Create that it sends the user to use external authentication - which can be used indeed, but the frontend authorization is working for all the endpoints added to the docs (including the upload create). 

So maybe that could be mentioned here:

![upload create](https://user-images.githubusercontent.com/33448286/142854723-b606093c-150d-41d4-8bdb-15b7e0578d56.png)

**Comment by eviljeff** [comment]
> @eviljeff I've noticed at Create that it sends the user to use external authentication - which can be used indeed, but the frontend authorization is working for all the endpoints added to the docs (including the upload create).

Elsewhere in the docs where we've supported both internal and external auth (e.g. accounts) we've just linked to the external auth - it's sort of implied that anywhere that supports external auth also supports internal.

The other actions (addon edit, version create & edit) should have the same note though - I forgot to add it.
