### ISSUE TITLE
Throw a validation error for min or max compatibility set for dictionaries

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18137]
As a followup for https://github.com/mozilla/addons-server/issues/18024#issuecomment-944372241

Looks like the dictionaries ignore the min max versions - an API response returns the same values every time:  min:4.0 and max:65535

The expected result: at submission an warning error message should be displayed when min and max (min or max) are used, an example:
`{"upload": "04e2361ad6614f44ae705e75b2b1a589", "license":18,"compatibility": {"firefox": {"min": "61.0", "max": "92.*"}}}`

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this at addon create and addon versions:

For a new version {"upload": "3df7e3b7d4884903b63e084889569948", "license": "all-rights-reserved","compatibility": ["firefox"]}  -> I get the same error as for the PATCH on addon Versions "This type of add-on does not allow custom compatibility."

But at addon create -> {"categories": {"firefox": ["general"]}, "summary":{"en-US":"test test test"},"version": {"upload": "9e4688dfb062404dba9c22b7bdd206d2", "license": "all-rights-reserved", "compatibility": {"firefox": {"min": "61.0", "max": "99.0"}}}} it ignores the compatibility information sent and it sets the default  "min": "42.0","max": "65535". 

I think it should throw an error here too, but in case it's the expected let me know.

**Comment by eviljeff** [comment]
> But at addon create -> {"categories": {"firefox": ["general"]}, "summary":{"en-US":"test test test"},"version": {"upload": "9e4688dfb062404dba9c22b7bdd206d2", "license": "all-rights-reserved", "compatibility": {"firefox": {"min": "61.0", "max": "99.0"}}}} it ignores the compatibility information sent and it sets the default "min": "42.0","max": "65535".
> 
> I think it should throw an error here too, but in case it's the expected let me know.

it should, and I can't immediately understand why it wouldn't.  It's a low priority follow-up though.
