### ISSUE TITLE
Add ability to generate site permission add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18135]
Add ability to generate and sign unlisted add-ons that enable a list of permissions for an origin, built on top of https://github.com/mozilla/addons-server/issues/18134

- The add-on will appear as an add-on with a single unlisted version
- Everything about it is automatically generated, including name, description but also manifest and xpi package itself
- It will belong to the developer account that requested it
- We need to record what permissions it enables in a new table

The `.xpi` will contain only a manifest, in which, besides mandatory extension fields, we'll have something like (property names subject to change):
```json
{
    "install_origins": ["https://sub.foo.com"],
    "site_permissions": ["permission"]
}
```

Follow-ups:
- They will be signed through `auto_approve` as normal, though we may want to customize the approval email. https://github.com/mozilla/addons-server/issues/18405

**Comment by diox** [comment]
Note: MAD scanner should be skipped for these add-ons and no `ScannerResult` recorded for those add-ons with MAD. This should be something we get for free since [we skip add-ons without code already](https://github.com/mozilla/addons-server/blob/41e6ee9e426facb19a1e1ca8d40277cb6f94a7da/src/olympia/scanners/tasks.py#L455-L462).

**Comment by diox** [comment]
> I think I'll probably have a simple table with addon <> permissions, just to have something telling us that an add-on is a permission enabler add-on. 

Actually, after giving this more thought I'm going to introduce a new add-on type for this, so there won't be a need to a new table.

**Comment by willdurand** [comment]
> Actually, after giving this more thought I'm going to introduce a new add-on type for this, so there won't be a need to an additional query in devhub. There will still be a table to store the permissions an add-on enables.

That sounds like a good idea, Firefox will use the add-on type `sitepermission` for these add-ons, cf. https://bugzilla.mozilla.org/show_bug.cgi?id=1737161

**Comment by diox** [comment]
(Nothing to test yet for QA, they'll be able to test it once the form is up and running)
