### ISSUE TITLE
store refresh tokens from FxA

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18149]
FxA supplies a token to refresh users session. We don't current store this but if we did we could use it to to get information about the user and the status of their FxA session.

**Comment by diox** [comment]
Note: before enabling this in stage/prod we'll likely want a proper fix for https://github.com/mozilla/addons-server/issues/17836

**Comment by ioanarusiczki** [comment]
@eviljeff 

on AMO dev: 

- I did not find unusual things in dev hub but I'll leave this to further testing tomorrow on -stage.
- testing around login/logout on frontend, dev hub, code-manager, admin I did not see changes in behavior. 
- the frontend authentication works (with Bearer)

I'll check AMO stage tomorrow + the results for the fxA logout scenario

**Comment by ioanarusiczki** [comment]
@eviljeff 

 On AMO dev - I made several logins using different accounts on different profiles, left tabs open on frontend, devhub or code-manager where's the case, then logged out fxA and waited until the next day to make sure there's 12hours + 
- with an account that has 2FA enabled -> I was logged out which is the expected result 
- with a new account (which does not require 2FA yet) and an older developer account with 2FA disabled I have the login available on all AMO pages.

On AMO stage
 - I only tested with an account with 2FA enabled and I got the same result as above - expected. I'll see tomorrow what's the result for a new account. 
 - requests using the Bearer Authentication still works, I tried it on addons shelves API, create collection and addon uploads. 
 - dev hub seems to be working on addon submissions, layouts seem to be alright.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I left them open last night between 10-11 pm, logout from fxA's page https://accounts.stage.mozaws.net/settings? for -dev and https://accounts.firefox.com/settings? for -stage and checked them after 11 am today:

**AMO dev**

new account [replaceprimary@mailinator.com](mailto:replaceprimary@mailinator.com)  -> Has login
new account [newaccountondev@mailinator.com](mailto:newaccountondev@mailinator.com) -> Has login
new account [contnoudev@mailinator.com](mailto:contnoudev@mailinator.com) -> has login
old account with 2FA disabled [rusiczki.ioana@gmail.com](mailto:rusiczki.ioana@gmail.com) -> has login
old account with 2FA enabled, admin reviewer account [irusiczki+1@mozilla.com](mailto:irusiczki+1@mozilla.com)  **-> was logged out** 
old account with 2FA enabled, that's my admin [irusiczki@mozilla.com](mailto:irusiczki@mozilla.com)-> has login

**AMO stage** -> all have a login

with 2FA [irusiczki+1@mozilla.com](mailto:irusiczki+1@mozilla.com)
 with 2FA disabled [rusiczki.ioana@gmail.com](mailto:rusiczki.ioana@gmail.com) 
new account [cotnoustage@mailinator.com](mailto:cotnoustage@mailinator.com) 
new account [rusiczki.ioana+1@gmail.com](mailto:rusiczki.ioana+1@gmail.com) 
admin account with 2FA enabled [irusiczki@mozilla.com](mailto:irusiczki@mozilla.com)
