### ISSUE TITLE
new hero image upload (Relay promo)

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#18140]
To help promote Relay's upcoming release we'd like to add a custom image to the hero area (attached). Can we please have this uploaded into admin by **27 October**?

@eviljeff 

![Relay_hero](https://user-images.githubusercontent.com/8496249/137804485-23ca9dca-82b6-42c9-9a83-b4681bc3f124.jpg)

**Comment by eviljeff** [comment]
> 
> 
> To help promote Relay's upcoming release we'd like to add a custom image to the hero area (attached). Can we please have this uploaded into admin by **27 October**?

You can - the upload is done via django admin ("primary hero images" or similar) - then you just select it.
