### ISSUE TITLE
Remove as much as possible of jquery-ui

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18142]
Why do we use jquery-ui for these days in addons-server, and could we get rid of it ? 

Off the top of my head I can only think of:
- ~~[ ] [`.sortable()`](https://jqueryui.com/sortable/) in devhub which we could easily find a lightweight replacement for.~~
- [x] [`.datepicker()`](https://api.jqueryui.com/datepicker/) in stats which we could probably replace with an `<input type=date>`: https://github.com/mozilla/addons-server/issues/18738

**Comment by eviljeff** [comment]
> > IIRC it's to show the screenshots and theme images and previews in an inline, well, lightbox, on the page for reviewers to check.
> 
> Yes, exactly why I think it's not necessary and could be replaced with just links to open in a new tab.

actually, I don't think theme pages use lightbox after all - they zoombox for the background images.

**Comment by diox** [comment]
Unfortunately `sortable` is trickier to remove than I'd like. There are alternative implementations, such as https://github.com/lukasoppermann/html5sortable, but porting ours to that revealed a few gotchas, notably around invisible elements and containing the sortable items in the right parent. It's fixable but I'm not going to have the time, so instead I'll just remove as much as possible and keep what's strictly necessary for now.
