### ISSUE TITLE
Remove obsolete js code and libraries

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18143]
On top of https://github.com/mozilla/addons-server/issues/18142 ... we can probably remove:
- `jqmodal`, which doesn't seem to be referenced anywhere
- `pjax`, which might still be referenced in some templates but shouldn't be used anymore
- Almost everything in `static/js/impala/` except for `stats/` and maybe a couple other things the statistics page would use.

**Comment by diox** [comment]
QA: check around devhub, reviewer tools and statistics page for broken functionality. Features like add-on uploads, previews uploads and manual sorting, authors changes, clicking buttons in the review page that enable/disable things for an add-on, etc.

**Comment by ioanarusiczki** [comment]
@diox I checked today on -dev rev tools, stats but not entirely the dev hub part , I've also seen the instructions from https://github.com/mozilla/addons-server/issues/18792. 

So far I did not find any functional issues but I'll return with complete results tomorrow morning.

**Comment by ioanarusiczki** [comment]
@diox Verified on AMO dev and AMO stage - FF97(Win10).
