### ISSUE TITLE
Clean up restyle.less

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#1815]
`static/css/restyle.less` has inconsistent whitespace, newline usage, and style. It's worth one commit to just fix all these style nits.

**Comment by tofumatt** [comment]
We should also change everything to 2 spaces instead of 4.

**Comment by muffinresearch** [comment]
> We should also change everything to 2 spaces instead of 4.

I'll make a note we should do 2 spaces on the new addons-frontend too.

**Comment by tofumatt** [comment]
:+1:
