### ISSUE TITLE
Reviewer Statistics Improvements

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#18168]
In order to better track and analyze the types of issues involved with review actions, we need to add a multi-select that allows reviewers to choose which issues are involved with the message they are sending. The multi-select is maintained separately to the review text.

* There is an admin-configurable list of categories we track
  * We may want to retire or temporarily disable categories, but without losing their past statistics
* In the actions section of the review page, reviewers can select which reasons apply to the action they are taking
  * This applies not only to rejections, but also delayed rejections, reviewer replies. For simplicity it could apply to any type of action that requires a text
  * It should be possible to select these quickly, e.g. with an auto-complete search
  * At the same time, reviewers may want to browse the full list in case they are looking for a reason.
* (optional) Canned responses additionally receive a category assignment, inserting a canned response automatically selects the category.

* There should be a way to change the categories for a review action, in case a mistake was made. Ideally so that reviewers can do so, if need be then only for admins
* We may want to do a one-time backfill based on existing canned responses. We can maybe do this manually, but I wanted to mention this here for completeness.

**Comment by kewisch** [comment]
> It sounds like there is consensus to not have these editable inline on the review page, at least not for the MVP that we're trying to build for Dec. 1. Do you agree, @kewisch?

Confirming we don't need these editable.

> > Do you think incorrect category assignment will be a significant problem anyway? (that it'll happen often enough to skew any statistics)
Probably not on a large scale, but I can imagine this happening once in a while and reviewers asking for something to be changed.

**Comment by bobsilverberg** [comment]
I think that everything described and discussed in this issue has landed via various follow-up issues, so I am going to close this. @kewisch let me know if you feel that anything is missing.
