### ISSUE TITLE
Allow for categories/reasons to be assigned to ActivityLog entries

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18191]
This is a spin-off from https://github.com/mozilla/addons-server/issues/18168, and depends on https://github.com/mozilla/addons-server/issues/18190. 

After https://github.com/mozilla/addons-server/issues/18190 lands, we will have a category/reason entity which could be connected to an `ActivityLog` entry. This issue is about creating that relationship.

@eviljeff suggests, at https://github.com/mozilla/addons-server/issues/18168#issuecomment-952017150, that we could have, for example, a `ReviewCategoryLog` with fks to activity_log, version and review_category. We should therefore be able to create this as an empty table, with all three fks required and then create the routines to populate it in a follow-up issue.

I gather from the above that `ActivityLog` does not include `version`, or if that's not the case then I'm unclear on why we need an fk for version in the relationship table.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I see on -stage admin/models/reviewers/reviewactionreason/ module. 
I could add a couple or reasons, delete, activate or disable them.  

I don't see a connection to `/admin/models/activity/activitylog/` or into the review pages - I rejected a version, and I did not see a new field with reasons that could be selected.

Please let me know if there's anything else to see for this issue or https://github.com/mozilla/addons-server/issues/18190

Thanks

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. I probably should have labelled this as qa: not needed, as it isn't really exposed anywhere.
