### ISSUE TITLE
Update the Products section of the footer

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18207]
In the Products section of the site footer, please...

- Remove Lockwise
- Add [VPN](https://www.mozilla.org/products/vpn/#pricing)
- Add [Relay](https://relay.firefox.com) 

See https://github.com/mozilla/addons-frontend/issues/10998 for more details.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
On Dev hub: 

![dev hub dev](https://user-images.githubusercontent.com/33448286/139807029-b29e04a0-4a7a-414b-b040-9ca6cfa11bb7.png)

URLs:
https://www.mozilla.org/en-US/firefox/browsers/?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org
https://www.mozilla.org/en-US/products/vpn/?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org#pricing
https://relay.firefox.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=footer-link
https://monitor.firefox.com/
https://getpocket.com/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=footer-link

Hovering over Monitor link I see the utm parameters but they're not passed after clicking the link.

**Comment by eviljeff** [comment]
https://monitor.firefox.com/ seems to have a redirect to the slash-less url, losing the params.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @eviljeff I filed it https://github.com/mozilla/addons-server/issues/18237 

Not seeing other issues, I'll mark this verified on AMO dev - FF93(Win10)
