### ISSUE TITLE
500 server error when making PATCH requests for a dictionary

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18203]
Followup for https://github.com/mozilla/addons-server/issues/18073#issuecomment-949618038

A warning message should be displayed with a 400 when trying to update compatibility for a dict (it's been detailed into https://github.com/mozilla/addons-server/issues/18137) 

Result:
Right now it's a server error on an PATCH request with {"compatibility": {"firefox": {"min": "61.0", "max": "92.*"}}} using the version API https://addons-dev.allizom.org/api/v5/addons/addon/620855/versions/1693100/

**Comment by ioanarusiczki** [comment]
@eviljeff For https://github.com/mozilla/addons-server/issues/18137 the response was a 201 - created. In this case it's a 500.

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff For #18137 the response was a 201 - created. In this case it's a 500.

oh, right 👍

**Comment by ioanarusiczki** [comment]
@eviljeff While testing around https://github.com/mozilla/addons-server/issues/19079 I've noticed that making a request for any of the version properties that can be edited other than "compatibility" , such as source, release notes, license - they all return a 500 error for dictionaries. 

So I'll change the title for this bug.

**Comment by eviljeff** [comment]
> @eviljeff While testing around #19079 I've noticed that making a request for any of the version properties that can be edited other than "compatibility" , such as source, release notes, license - they all return a 500 error for dictionaries.
> 
> So I'll change the title for this bug.

I think it's a regression from https://github.com/mozilla/addons-server/issues/19007

**Comment by ioanarusiczki** [comment]
@eviljeff 

For dictionaries, the  Versions API will throw an error now for compatibility 
        "This type of add-on does not allow custom compatibility."

Requests for source, release notes, license  are responding now with a 200 Status.
