### ISSUE TITLE
slug accepts special chars when sending patch requests 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18201]
Followup for 

https://github.com/mozilla/addons-server/issues/18037#issuecomment-948586765

Send a request https://addons-dev.allizom.org/api/v5/addons/addon/620866/ with {"slug": "!@!#!@##@$$%$#%#%$^^%&%"} 

Result:
The response is 200. On dev hub a slug such as '75b25b33bf9c4cf9bcda' is generated.  

Another example: {"slug": "~~~~~~~~"}  -> this slug is accepted. The frontend page :https://addons-dev.allizom.org/en-US/firefox/addon/~~~~~~~~~~~~~~~~~~~~/

Expected result:
A 400 response with a warning message.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I can no longer use special chars except for {"slug": "~~~~~~~~"} which is still allowed and I get a 200. 
- the rest of my attempts did not pass, I get a 400 with:
`{
    "slug": [
        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens."
    ]
}`

**Comment by eviljeff** [comment]
> except for {"slug": "~~~~~~~~"} which is still allowed and I get a 200.

Is a slug like that not valid in devhub too?

**Comment by ioanarusiczki** [comment]
@eviljeff It is excepted everywhere - edit page - frontend 
This is the addon https://addons-dev.allizom.org/en-US/firefox/addon/~~~~~~~~~~/
