### ISSUE TITLE
Add-on verification problem after browser restart

### ISSUE THREAD

**Issue by bestsoftam** [mozilla/addons-server#1821]
After signing the add-on I could install it. But after restart Firefox says that it disabled the add-on as it's not signed, what is the problem?

**Comment by wagnerand** [comment]
The add-on most probably modified its own folders or files which breaks the signature. I recommend contacting the author of the add-on and ask them to investigate and fix the issue.

**Comment by bestsoftam** [comment]
I am the the owner of the add-on and the paths or files didn't change. Everything is the same as when the add-on was signed and installed.

**Comment by wagnerand** [comment]
Please attach the XPI to this issue, then.

**Comment by bestsoftam** [comment]
I can't attach the xpi, but I can record a video and send it to you to have a look at it.

**Comment by wagnerand** [comment]
Sorry, that won't help us. We need to investigate the code. You can also just link to the add-on on AMO even if unlisted and I can inspect it there.

**Comment by bestsoftam** [comment]
https://addons.mozilla.org/en-US/developers/addon/arpis

**Comment by wagnerand** [comment]
It works for me just fine. The add-on does not get deactivated. Is there special software needed or things to do to trigger the issue?

**Comment by bestsoftam** [comment]
My firefox version is 44.0.2

**Comment by bestsoftam** [comment]
Can you use Teamviewer to see the problem?

**Comment by wagnerand** [comment]
Please answer my previous question and add detailed information about your environment, like operating system, other software used, what the add-on actually does, how to use it etc.

**Comment by bestsoftam** [comment]
My OS is Win7, no other software used, to use the addon you need to have the backend.

**Comment by wagnerand** [comment]
Then I guess unfortunately I probably can't help you any further. I am 99% sure the add-on modifies its own contents but it seems it needs to get triggered somehow.

Why do you need to unpack it? Try removing the unpack declaration in install.rdf and see if it still happens.

**Comment by bestsoftam** [comment]
Ok, I'll try to remove it and will come back again. Thanks

**Comment by wagnerand** [comment]
I am closing this. Please direct further questions to our forums at http://discourse.mozilla-community.org/c/add-ons Thanks.

**Comment by jvillalobos** [comment]
If you want to discuss this privately, we also have a mailing list: amo-admins AT mozilla DOT org

**Comment by bestsoftam** [comment]
The problem is coming when I am switch between 2 profiles. I have 2 profiles with the same addon. When I am using only one it works fine, but when I switch from one to other the message comes that the addon is not verified.
