### ISSUE TITLE
src/olympia/templates/photon-footer.html is not localized

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18215]
This is a follow-up to https://github.com/mozilla/addons-server/issues/18207.

When working on that issue, @eviljeff noted that none of the strings in the footer template are localized. That seems unintentional and not a good thing.

We should fix it.

**Comment by ioanarusiczki** [comment]
@diox 

I checked the footer with 'de', 'it','pt-BR' and other languages but for these I could see translations.

An example:

![IT](https://github.com/mozilla/addons-server/assets/33448286/1254c531-8a12-4de8-a0c2-5643220e50b6)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-63
