### ISSUE TITLE
Display issue in "Up&Coming" pages for some themes categories

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1822]
Steps to reproduce:
1. Load AMO-stage Themes page https://addons.allizom.org/en-US/firefox/themes/
2. Go to Causes themes category https://addons.allizom.org/en-US/firefox/themes/causes
3. Click the "View All Up & Coming" link
4. Go to the bottom of the page, observe the number of pages and navigate through them

Expected results:
User is able to navigate to all listed pages without any issues.

Actual results:
Not all pages have themes, but user can navigate through empty pages.

Notes/Issues:
Issue is not reproducing for all categories. (just Causes, Foxkeh and Websites - I suspect is reproducing just for categories with number of themes under 150)
Verified on FF44(Win 7, Android 5.0.1). Issue is reproducing on AMO-stage, dev and prod.
Screencast for this issue:  http://screencast.com/t/MlJJ0udO3cQ

**Comment by EnTeQuAk** [comment]
Hmm, this is a stupid but but probably low priority enough and could be easy to fix, maybe it's just a wrong queryset that is being passed to the pagination.

I'm happy to mentor this.

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide details.

**Comment by harikishen** [comment]
I would like to take this up.

**Comment by EnTeQuAk** [comment]
@harikishen go for it, it's all yours! If you have any questions please let me know.

**Comment by Divya063** [comment]
@EnTeQuAk  I would like to take this issue.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
