### ISSUE TITLE
Allow for recording ReviewActionReasons when logging activity

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18234]
This is a spin-off from https://github.com/mozilla/addons-server/issues/18168.

In order to record the reason(s) for a review action, the routines that create `ActivityLog` entries when a user performs an action on a review will need to be able to accept one or more `ReviewActionReason`s, and then record those reasons in the database.

It looks like the places where this occurs are limited to:
- [`log_action`](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/utils.py#L831) in `reviewers/utils.py`
- [`log_and_notify`](https://github.com/mozilla/addons-server/blob/master/src/olympia/activity/utils.py#L223) in `activity/utils.py`

There are also a few places where we explicitly create an instance of `ActivityLog`, but they don't seem to be cases where we'd need to assign a reason, so we can probably ignore them. I am curious about why we are doing that and not just calling `log_action` though, but that's just me being curious.
- [`sign_file`](https://github.com/mozilla/addons-server/blob/b0db9bb7ea3093dc6bfe1625685bcb226603e703/src/olympia/reviewers/utils.py#L943) in `reviewers/utils.py`
- [`approve_latest_version`](https://github.com/mozilla/addons-server/blob/b0db9bb7ea3093dc6bfe1625685bcb226603e703/src/olympia/reviewers/utils.py#L1337) in `reviewers/utils.py`

This issue is about updating `log_action` and `log_and_notify` to accept one or more reasons and to record them in the database when recording the `ActivityLog`. As it only appears that `log_and_notify` is used in one place, it might be worth investigating whether we can discontinue its use in `reviewers/utils.py` and instead use `log_action`.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
hmm, maybe a hint, I checked around but the reasons don't seem to be visible into rev tools logs or admin activity log.

**Comment by bobsilverberg** [comment]
> @bobsilverberg hmm, maybe a hint, I checked around but the reasons don't seem to be visible into rev tools logs or admin activity log.

The reasons are not displayed anywhere in reviewer tools at the moment, nor is there a specific plan to do so. I will be adding an admin module for them, however, to allow admins to change a reason if one was selected in error, and once that lands that can be used to verify this behaviour.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I think this has been verified into https://github.com/mozilla/addons-server/issues/18301
