### ISSUE TITLE
Allow addon authors to be changed via addon api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18231]
split from #18036

You should be able to change the properties of the add-on owners/developers via the addon api.

**Comment by diox** [comment]
In https://github.com/mozilla/addons-server/issues/18604 I'm going to disallow editing add-ons and versions for site permission add-ons. When we implement authorship changes however, we'll need to allow it (it's the only kind of write operation allowed for those kind of add-ons right now).

**Comment by eviljeff** [comment]
The things needed here:
- change author
  - roles (developer <-> owner); just need to check there is at least 1 owner remaining.
  - visibility; enforce at least 1 visible author(?) 
  - position
- delete author(s); just need to check there is at least 1 owner remaining (& visible?).
- add author(s).  Complexity here is:
  - not actually creating `AddonUser`, but creating `AddonUserPendingConfirmation`.
  - we need to expose any `AddonUserPendingConfirmation` in a serializer response.  In the main addon detail response?
  - how do users confirm the pending confirmation?  (endpoint for confirmation could be follow-up)

**Comment by ioanarusiczki** [comment]
@eviljeff I tested around this on -dev. "role", "position" and "listed" can be edited using a PATCH request such as: 
https://addons-dev.allizom.org/api/v5/addons/addon/621499/authors/10642040/

 "Add-ons need at least one listed author." is displayed when I tried to make all owners/developers "listed":false
