### ISSUE TITLE
The utm params are not available for the Monitor URL  

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18237]
STR:
Click "Monitor" from the Footer

Expected result:
https://monitor.firefox.com/?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org

Actual result:
https://monitor.firefox.com ( the slash is missing)

**Comment by eviljeff** [comment]
Looks like they drop the utm params for both
https://monitor.firefox.com/?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org
and
https://monitor.firefox.com?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org
though, so this might end up being a fix on their side.

**Comment by groovecoder** [comment]
We drop the utm params, but AFTER we send our ping to Google Analytics. https://github.com/mozilla/blurts-server/blob/main/public/js/fxa-analytics.js#L355-L392

**Comment by eviljeff** [comment]
Sounds like there's no problem then, assuming both `/` and slashless urls are treated the same.
