### ISSUE TITLE
Add basic admin for InstallOrigin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18242]
We want a basic admin set up for QA/admins to look at `InstallOrigin` records.

**Comment by diox** [comment]
QA: this should allow you to test https://github.com/mozilla/addons-server/issues/18134 (like mentioned in that issue, there is no validation yet though - that's a different issue, https://github.com/mozilla/addons-linter/issues/3972)

**Comment by AlexandraMoga** [comment]
The admin model was created - https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/installorigin/ -  and has the basic fields mentioned in https://github.com/mozilla/addons-server/issues/18134#issue-1029031792.

This issue is verified fixed on -dev.
