### ISSUE TITLE
Remove support for re-using deleted GUIDs

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#18253]
Re-using a deleted add-on ID is no longer supported. When an add-on is deleted, AMO makes it explicit that the add-on cannot be restored and the ID cannot be re-used or recovered.

**Comment by eviljeff** [comment]
I think without a way to "un-delete" an add-on we're just asking for angry developers and extra admin work replying to them but 🤷

**Comment by diox** [comment]
The current warning text for deletion is:
> Deleting your add-on will permanently delete all versions and files you submitted for this add-on, listed or not. The add-on ID will continue to be linked to your account, so others won't be able to submit versions using the same ID.

I'm proposing to use:
> Deleting your add-on will permanently delete all versions and files you submitted for this add-on, listed or not. The add-on ID will forever be unusable for submission.

What do you think?

**Comment by diox** [comment]
It looks a little weird in bold because that page is also the version list page, so with the text in bold it stands out and looks out of place. The same warning is repeated in the modal (where pretty much everything is in bold) so I think it should be ok.

**Comment by wagnerand** [comment]
Ah,sorry, I thought you were referring to the modal. Sounds good then.
