### ISSUE TITLE
allow basic properties on addon to be set via the api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18269]
part of #18036 

These properties are all just boolean properties so it should be easy enough to implement write on them at the same time.
- 'is_disabled',
- 'is_experimental'
- 'requires_payment',

**Comment by ioanarusiczki** [comment]
@eviljeff 

For listed addons I could use:

POST request for https://addons-dev.allizom.org/api/v5/addons/addon/ to set `"is_experimental": true, "is_disabled":false, "requires_payment":true` at first submission
PATCH requests https://addons-dev.allizom.org/api/v5/addons/addon/620954/ to modify `{"is_experimental": false, "is_disabled":true, "requires_payment":false} `

I believe this is working as expected.
