### ISSUE TITLE
allow contributions to be updated via addon api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18267]
spun off from #18036 

The contributions_url field should be writable via the API.   It'll need some special validation that only valid contribution domains are allowed.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and these are my results:

- all the [supported domains](https://github.com/mozilla/addons-server/blob/0b5db7d544a21f6b887e8e8032496778234ade33/src/olympia/constants/base.py#L214:L226) are accepted
- the field doesn't accept empty strings
- URLs that aren't included in the supported domains list are not accepted 
- other forms of invalid data, like lists, bools, null values are not accepted (i.e. a 400 error is returned), except for random strings and numbers, for which I filed #19000
