### ISSUE TITLE
Clean up wsgi.py so that it's less custom

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18276]
Our `wsgi.py` script contains this:
https://github.com/mozilla/addons-server/blob/ddffab7fe9ca0ad84f58eab6e055a9376ecd5257/src/olympia/wsgi.py#L28-L37

That looks completely obsolete. We can probably return `django_app` directly (unless we need `wsgi.loaded`?).

**Comment by Rishabh04-02** [comment]
@diox I would like to fix this.

**Comment by diox** [comment]
@Rishabh04-02 this is a not a good first bug (yet), it needs more investigations on our side.

@bqbn do you use https://a.m.o./services/loaded endpoint at all anywhere ?

**Comment by Rishabh04-02** [comment]
Okay.

**Comment by bqbn** [comment]
> @bqbn do you use https://addons.mozilla.org/services/loaded endpoint at all anywhere ? It was added 12 years ago in https://bugzilla.mozilla.org/show_bug.cgi?id=557049, back when AMO was on... Apache/mod_wsgi

Nope, not that I'm aware of.

**Comment by diox** [comment]
This shouldn't require specific testing, it should be straightforward to see if it's working: If somehow the application fails to start, or is broken in a significant way, this is likely the culprit.

**Comment by ioanarusiczki** [comment]
@diox I verified on AMO dev on Win10 & Android - it looks like the pages load just fine: frontend, dev hub, rev tools.
