### ISSUE TITLE
clean-up obsolete FxaToken instances

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18280]
follow-up to #18149

#18185 will add a model `FxaToken` to store fxa refresh tokens, but the table will fill up with unused records each time a session is discarded.  We'll need to make sure we aren't discarding access_tokens that have been refreshed though (by checking the `modified` date)

**Comment by diox** [comment]
At the very least, we should discard obsolete ones at logout (with our current session implementation, that means discarding all `FxaToken` for a given user when they log out, since all sessions are invalidated at the same time).

**Comment by eviljeff** [comment]
we went for database backed sessions instead of a separate FxAaToken object
