### ISSUE TITLE
Read Only mode 500s when processing API requests resulting in a OperationalError

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18296]
Shortly after read-only mode was introduced in 9dfcf92c096e8e502413c468a39a912169f54a91, it was simplified to remove the `Retry-After` header, in 18c1cc943809a83f77ba83c168dfb983454c28cf

Unfortunately, that created a bug in a small, super rare condition that wasn't covered by tests:
https://github.com/mozilla/addons-server/blob/6b0ee7ca941430ba9dcc1a4f6067f62042493a23/src/olympia/amo/middleware.py#L244-L251

When:
- We're in read-only mode
- We're processing an exception that comes from a previous middleware in the stack (can't come from a view, because that would be caught in `process_request()` before)
- That exception is an `OperationalError` from MySQL
- We're dealing with an API request

We call `self._render_api_error()`, which no longer exists, resulting in a 500 instead of the intended 503.

In addition the middleware docstrings mentions we `Supports issuing `Retry-After` header` which isn't true anymore.

**Comment by diox** [comment]
We would need to force readonly mode and trigger a MySQL error to test this with QA, but that would be helpful still, so maybe we can try that on dev.

**Comment by ioanarusiczki** [comment]
@diox Let me know when the readonly is triggered and what to check. Thanks!

**Comment by diox** [comment]
This is kind of annoying to deploy, so let's skip QA actually. But I've done some extra manual testing locally that was successful by applying this patch:
```diff
diff --git a/src/olympia/amo/views.py b/src/olympia/amo/views.py
index d3cdda5972..65ab91e507 100644
--- a/src/olympia/amo/views.py
+++ b/src/olympia/amo/views.py
@@ -60,14 +60,22 @@ def monitor(request):
 @never_cache
 @non_atomic_requests
 def client_info(request):
-    if getattr(settings, 'ENV', None) != 'dev':
-        raise PermissionDenied
+    # if getattr(settings, 'ENV', None) != 'dev':
+    #     raise PermissionDenied
     keys = (
         'HTTP_USER_AGENT',
         'HTTP_X_COUNTRY_CODE',
         'HTTP_X_FORWARDED_FOR',
         'REMOTE_ADDR',
     )
+    if request.GET.get('mysqlerror'):
+        if request.GET.get('api'):
+            request.is_api = True
+        # Test for https://github.com/mozilla/addons-server/issues/18296 :
+        # trigger a mysql operational error to see how the middleware handles
+        # that.
+        from MySQLdb.connections import Connection
+        Connection('invalid-host')
     data = {key: request.META.get(key) for key in keys}
     return JsonResponse(data)

```

With that patch applied, setting `READ_ONLY = True` in my local env, when visiting http://olympia.test/services/client_info?mysqlerror=1 and http://olympia.test/services/client_info?mysqlerror=1&api=1 I get the expected 503s.
