### ISSUE TITLE
Add an admin for ReviewActionReasonLog

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18301]
A feature request is to be able to change the reason assigned to a review action if the original reason selected was incorrect. Possibly the simplest way to address this is to add an admin for `ReviewActionReasonLog` which will allow a user to edit the `reason`. I did a quick test of this, and it seems to be doable, although we'd need a way for users to be able to search through the log entries to find the one they want.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- Should this be available into the Reviewers section from admin tools? I don't see changes into `models/reviewers/reviewactionreason/`. Here I can add, remove, reasons. 
- I've noticed while checking for https://github.com/mozilla/addons-server/issues/18233#issuecomment-965355278 that "Approve content" action from "Content review" queue does not display the reasons box but the action next to it, Reject Multiple Versions will show this box.  Is this a bug ?

**Comment by ioanarusiczki** [comment]
@bobsilverberg About what I've said above - probably not a bug, Confirm approval action from Auto-approved queue is not showing the box either.

**Comment by bobsilverberg** [comment]
The admin for the ReviewActionReasonLog is found under "Activity" in the admin, not under "Reviewers". It is currently only available to admins with "*:*" permissions.

Regarding the second comment, you are right, it's not a bug. The reasons should only appear in the four places documented at https://github.com/mozilla/addons-server/issues/18233#issuecomment-965355278

**Comment by ioanarusiczki** [comment]
@bobsilverberg I checked on AMO stage the reviewactionreasonlog:
- when saving an action, the "comment" is also mandatory with the reason. "Activity log" column is showing the action: reply, reject, approve. But there is no information about the comment made by the reviewer. 
- there's a search box - not functional, it would not return results after I tried with multiple queries. 
- after making several actions in different addon queues, I think the admin side is working as expected.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I checked on AMO stage the reviewactionreasonlog:
> 
> * when saving an action, the "comment" is also mandatory with the reason. "Activity log" column is showing the action: reply, reject, approve. But there is no information about the comment made by the reviewer.
> 

This is expected.

> * there's a search box - not functional, it would not return results after I tried with multiple queries.
>

I should have mentioned, this search box only works for searching for the reviewer's email address, but should work for that.
 
> * after making several actions in different addon queues, I think the admin side is working as expected.

Thanks!

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Ah, yes it's working when I use the email address for searching. 

Verified on AMO stage - FF94(Win10).
