### ISSUE TITLE
Forbid regular submission of site permission add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18329]
https://github.com/mozilla/addons-server/issues/18135 and https://github.com/mozilla/addons-server/issues/18136 will deal with the creation of those special "site permission" add-ons. But we should also prevent submission of those add-ons in addons-server: they need to be created automatically by AMO, it shouldn't be possible for a developer to submit an add-on using the special manifest property through the regular submission process in AMO (API or devhub).

It should still be possible to submit those add-ons (which are essentially regular extensions with a `site_permissions: [...]` and `install_origins: [...]` set in their manifest, and no JavaScript code) if you have a special permission, for internal testing purposes. In any case they should be recognized as Site Permission add-ons in AMO.

**Comment by diox** [comment]
> Question is, should that restriction be handled by the linter (the base schema from Firefox will likely have to allow that property, so that would be added on top) or addons-server.

Leaning towards the linter (the generate add-ons will likely bypass validation anyway) but curious to hear your thoughts @willdurand @rpl

**Comment by diox** [comment]
It might still be worth adding a check to the linter, but I'll handle it in addons-server for now, with something like this in the parsing code:
```python
    # Permission enabler add-ons aren't directly submitted by users, they are
    # generated by us.
    if (
        xpi_info.get('type') == amo.ADDON_PERMISSION_ENABLER
        and not user.pk == settings.TASK_USER_ID
    ):
        raise forms.ValidationError(gettext('You cannot submit this type of add-on'))
```

**Comment by willdurand** [comment]
Starting with the check above in addons-server sounds good.

We could add a similar one in the linter, I suppose, but shouldn't we validate the install origins?

**Comment by diox** [comment]
Input of the install origin would happen in a form submitted by the developer in #18136. To validate the origins for that form, I see 2 options:
- Generate the add-on regardless of the contents of the form, then have that add-on go through validation tasks as a regular add-on submission, maybe passing an argument to the linter indicating that it should accept the site permission add-on / ignore the restriction, then either surface any errors or proceed with successful submission flow
- Validate the origin in addons-server python code, hooking up the denied origins logic from #18331, immediately returning any errors. If there are no errors, generate the add-on, bypass validation, proceed with successful submission flow

I lean towards the second option, at the expense of having to duplicate the check about what an origin is, to avoid having to deal with the validation tasks in the form handling code just to validate origins.

**Comment by willdurand** [comment]
Yeah, that (option 2) makes sense.

**Comment by diox** [comment]
Initial backend implementation in https://github.com/mozilla/addons-server/issues/18135 forbids submission if you are not the task user. I'll tweak that to allow users with a specific permission to allow us to upload test add-ons.

**Comment by AlexandraMoga** [comment]
@diox jut to understand how I should test this:

- regular developers (no special permissions) should not be able to upload addons that have the `site_permissions: [...]` and/or `install_origins: [...]` properties in their manifest
- users with `Addons:SubmitSitePermission` are allowed to submit add-ons with the above mentioned properties

**Comment by diox** [comment]
Yes, but remove the `/or ` part: add-ons with `install_origins` alone are ok. It's just add-ons with `site_permissions`, with or without `install_origins` added, that regular developers shouldn't be able to install.
