### ISSUE TITLE
Issues encountered for a user with multiple reviews for the same add-on

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#1832]
**Steps to reproduce:**
1. Open AMO-Stage https://addons.allizom.org/en-US/firefox/
2. Click on any addon
3. Write a review.
4. Write another review.
5. Click on “previous review” hyperlink
6. Delete last added review (the active review)

**Expected results:**
First user review reappears.

**Actual results:**
All the user review have been removed/hidden.

**Notes/Issues**
Verified in FF44(Win7) Issue is reproducing in AMO-Dev and AMO-Stage, AMO-Prod
Screencast for this issue:  http://screencast.com/t/XBstfiUF
This issue also affects the the review counter, please view this screencast: http://screencast.com/t/aaYZA3brFR6A

Another scenario related to this issue that I think has the same root cause is:
1. Open AMO-Stage https://addons.allizom.org/en-US/firefox/
2. Click on any addon
3. Write 3 reviews for that addon
4. Click on “previous review” hyperlink
5. Delete all reviews except the last one added.

Expected results:
Only the last user review appears, with no other reviews.

Actual results:
Last user review appears with  “This user has x previous reviews of this add-on” section.
Screencast for this issue:  http://screencast.com/t/outZiiCEBMt

**Comment by EnTeQuAk** [comment]
Closing this since I believe this is is very very low priority and will be reimplemented with the new addons-frontend cleanly anyway sometime in the near future. Please feel free to reopen in case someone disagrees.
