### ISSUE TITLE
Prevent updates to disabled addons via addons api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18330]
In devhub you're prevented from updating most (all?) meta data for a mozilla-disabled add-on (i.e. an add-on we've disabled, rather than user disabled), and from uploading new versions.  We should consistently enforce the same restrictions for the new addon submission/edit apis.

**Comment by ioanarusiczki** [comment]
@eviljeff I tested the following scenarios on -dev:

1. the addon is force-disabled from the reviewer page : new version uploads are forbidden, patch requests on addon or a version are all forbidden. These addons can be edited from dev hub on compatibility, release notes, license but not using the versions endpoint. Can't find the point of editing on disabled versions so perhaps the endpoint behavior is alright. 
2. addon is fully blocked: when the block uses 0-*  -> same results as above. 
3. a partial block will allow new submissions (that is expected) and PATCH requests on blocked versions are possible using the versions endpoint. (that should be alright, dev hub allows it too)
4. an addon is invisible: I could submit a new listed version. Two examples:
https://addons-dev.allizom.org/api/v5/addons/addon/620309/versions/ 
https://addons-dev.allizom.org/api/v5/addons/addon/620344/versions/
Dev hub won't allow submissions in this case -> only unlisted addons can be submitted.  -> this should be tracked into an issue.
PATCH requests are returning a 200 status, so metadata can be edited using the addon and version endpoints. This is also possible from dev hub. 
5. an addon is rejected: that would allow the submission and edit of addons/versions, which is expected.

**Comment by eviljeff** [comment]
> 4\. this should be tracked into an issue.

yes please.  I'm not 100% what the behaviour _should_ be, tbh ("Invisible" in devhub is awkwardly built on top of the `Addon.disabled_by_user` property, which is actually stored in the "inactive" database column and each of these names indicates a subtly different concept - and how it's actually treated in code is in places inconsistent).  Some discussion needed.

**Comment by ioanarusiczki** [comment]
@eviljeff I filed it here https://github.com/mozilla/addons-server/issues/18451
