### ISSUE TITLE
Add ability to prevent submission of add-ons whose `install_origins` contain specific origins

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18331]
It should be possible through an admin tool to add a pattern that would prevent certain origins from being used in `install_origins` when `record-install-origins` waffle switch is enabled.

- Shell-style (`*` to match everything) patterns should be supported.
- IDN origins should be supported, both in unicode or punycode format. The pattern can also be in either format, and would block both variants if they appear in the `install_origins`.
  - For example, a pattern of `*.栃木.jp` would block `https://foo.bar.栃木.jp` as well as `https://foo.xn--4pvxs.jp` origins. Similarly, a pattern of `*.xn--4pvxs.jp` would block `https://bar.栃木.jp` and `https://bar.xn--4pvxs.jp`
- When adding new patterns in the admin, an option needs to be present in the admin to automatically add a variant of the input pattern that matches subdomains.
  - For example, if a pattern of `foo.example.com` is provided, if that option is checked, behind the scenes that pattern would also block `*.foo.example.com`. Admins would then be free to change that option later if they wish (that wouldn't affect past uploads that have already been validated)
- If `install_origins` for an add-on being uploaded contains one or more origins that match one if the disallowed patterns, that submission should be considered invalid at upload time.

In addition, invalid `install_origins` values don't need to be blocked by a pattern, since they would cause validation to fail anyway thanks to the linter, but shouldn't cause 500/unknown errors.

(See https://github.com/mozilla/addons-server/issues/18134 for more details about `install_origins`)

**Comment by AlexandraMoga** [comment]
@diox if I add a denied install origin, like this one for example -  https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/deniedinstallorigin/2/change/ and then try to upload an addon with that origin - `"install_origins": ["https://foo.com"]` - I get the "Sorry, we couldn't load your WebExtension" upload error.

**Comment by diox** [comment]
Interesting. That's https://sentry.prod.mozaws.net/operations/olympia-dev/issues/15474571/?query=is%3Aunresolved, not sure what's happening yet, investigating.

**Comment by diox** [comment]
Should be fixed, though I haven't had the time to test it yet.

**Comment by AlexandraMoga** [comment]
I've verified this new feature on -dev with multiple combination of denied origins. I'm listing below some of the tested scenarios and their results:

- with `record-install-origins` switch off - denied install origins are ignored => validation is successful
- denied install origins set to `example.com`:
  - the following install origins were blocked: http://example.com, https://EXAMPLE.COM
  - the following install origins were not blocked: https://example.ro, https://foo.example.com, https://www.example.com; the last two examples are blocked only if the include subdomains checkbox is also selected
- blocked domain set to `example.com` and `example.*`:
  - the following install origins were blocked: http://example.com, https://example.ro, https://example.something.io
- denied install origin  set to  `*example*`:
   - the following install origins were blocked (with or without the include subdomain checkbox): https://new.example.something.com
- denied install origins set to  `*example.com` and `other.*`:
  - the following install origins were blocked: https://example.com, http://other.org
- denied install origins set to `网站.*` - will be converted to `xn--5tzm5g.*` automatically:
  -  the following install origins were blocked: https://网站.com, http://xn--5tzm5g.com
