### ISSUE TITLE
drop some_rights field from License model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18359]
while looking at License I found that `some_rights` is unused in current code, so we should drop it

**Comment by ioanarusiczki** [comment]
@eviljeff I don't see changes into the Licenses for extensions or themes on AMO Dev. 
Frontend displays the License into the More information card. 
Let me know if there's anything else to check.

**Comment by ioanarusiczki** [comment]
@eviljeff I've noticed an issue about Licenses and filed it https://github.com/mozilla/addons-server/issues/18397 but I don't think it is related to this patch so I'm going to mark it verified.
