### ISSUE TITLE
Don't require license for subsequent listed versions submitted via addon submission api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18367]
spun off from #18034 

You shouldn't have to provide a license when the previous version (in the same channel?) has one already.  Currently we require a license for all listed versions.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- when v1 is listed , for v2 "license" is no longer required at submission.
- when v1 is unlisted (and also had "license" information sent) and v2 is listed -> license is required for v2's submission. 

I hope it works as expected.

**Comment by eviljeff** [comment]
> @eviljeff
> 
>     * when v1 is listed , for v2 "license" is no longer required at submission.
> 
>     * when v1 is unlisted (and also had "license" information sent) and v2 is listed -> license is required for v2's submission.
> 
> I hope it works as expected.

yes, license inheritance is per channel (like now)
