### ISSUE TITLE
Don't require a reason for the `public` action

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#18366]
For the #18168 Reviewer Statistics Improvement project, we need to make a tweak that the review reason is optional for the `public` action. It should still be possible to select one or more reasons, but it should not be required. All other actions should still require the reason.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
"Approve" action from the reviewer pages no longer require a reason, only "Comments" field is mandatory.
When the comment is made without selecting a reason - the action is not registered in `/models/activity/reviewactionreasonlog` - which I believe is expected
