### ISSUE TITLE
Define builtin only license properties in constants rather than the model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18360]
In the license model we define `url`, `on_form`, `some_rights` [#18359], `icons`, and `creative_commons` fields for all license records, but they are only applicable for the predefined licenses we offer (MPL, GPL, cc-attrib, etc) - they aren't settable for custom (i.e. developer defined) licenses in devhub.  This is inefficient for the database table and more difficult to keep track of the values.

Note, to do this we will have to define all the built-in licenses in constants (not a bad thing either) and take away the ability to add new built-in licenses via /admin

**Comment by ioanarusiczki** [comment]
@eviljeff I'm going to check on the Licenses from admin and deb hub.

**Comment by ioanarusiczki** [comment]
@eviljeff 

- I checked dev hub - the old licenses are displayed, can be edited, the new license will be displayed on frontend,  the urls redirect to the license pages.
- the "url" field in admin is no longer available when I tried to add a [license](https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/license/4230/change/?_changelist_filters=p%3D36) id:4230. It's not available in dev hub.  

If the ability to add licenses via admin ceases, is the "Add License" button still necessary or it's going to be removed?

**Comment by eviljeff** [comment]
> If the ability to add licenses via admin ceases, is the "Add License" button still necessary or it's going to be removed?

It'd be useless for adding new built-in licenses because they won't show up anywhere; it could possibly still be used by admins to create a new custom license for a version. Given how rarely (I imagine) the License admin is used though I don't think it's worth spending any time on improving it to make `builtin` read-only, or other tweaks.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I see what you mean, I tried to add a custom license to a version. 

If I add a number for "Builtin:" , frontend will not redirect to a license page -> there's no url

![Custom License](https://user-images.githubusercontent.com/33448286/188465786-704ed420-4037-4e3f-8a57-cca4e4410c6c.png)

But once I removed "Builtin:" -> works as expected. Example is this addon https://addons-dev.allizom.org/en-US/firefox/addon/put-create-addon-ripoie-sep-5-/

Also this has been removed from admin: 

![what](https://user-images.githubusercontent.com/33448286/188466035-9eefb5d6-3a03-4c19-aaed-929bbc1dc952.png)
