### ISSUE TITLE
Enable addon submission api for users on prod

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18371]
Once all the blocking (MVP) issues in https://github.com/orgs/mozilla/projects/174 are finished we should enable the API on production AMO so it can be used by users.  It's expected they'll be other bugs found before we would want to announce it as "finished" but we won't find those until it's actually in use.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I'm writing these 2 down as I'm not 100% sure it's expected: 

- while making submissions on -dev I've noticed that at addon create if I send  "compatibility" information such as {"compatibility": ["firefox","android"]}, the addon is set for `firefox` only.  The same when I add     "compatibility": {"firefox": {"min":"46.0","max": "*"}, "android": {"min": "56.0", "max": "*"}}.  If I want to change it from it's default `"firefox": { "min": "48.0"", max": "*" } it can be done with versions endpoint using PATCH after the addon is created.  

- forgot to add into https://github.com/mozilla/addons-server/issues/18361#issue-1057374251 that license id's such as `"license":18` are throwing an error , it only works with slugs now.

**Comment by eviljeff** [comment]
>     * while making submissions on -dev I've noticed that at addon create if I send  "compatibility" information such as {"compatibility": ["firefox","android"]}, the addon is set for `firefox` only.  The same when I add     "compatibility": {"firefox": {"min":"46.0","max": "_"}, "android": {"min": "56.0", "max": "_"}}.  If I want to change it from it's default `"firefox": { "min": "48.0"", max": "*" } it can be done with versions endpoint using PATCH after the addon is created.

So #18024 doesn't work?  Or it regressed somewhere along the way?  Note: `compatibility` is a property of `version` rather than `addon` (it wasn't clear from your example how it was being sent).

>     * forgot to add into [add license slug #18361 (comment)](https://github.com/mozilla/addons-server/issues/18361#issue-1057374251) that license id's such as `"license":18` are throwing an error , it only works with slugs now.

yeah, I was aware - I couldn't see a use-case for being able to specify by id.  The built-ins can be referenced by slug and you can't set custom licenses with the `license` field (you have to use `custom_license`)

**Comment by ioanarusiczki** [comment]
@eviljeff Hmm, I must re-check to see how `compatibility` was used in my testing. Thanks!

**Comment by ioanarusiczki** [comment]
@eviljeff Yeap, that is working just fine, I forgot about keeping the compatibility under version when I wrote a JSON where I tried to include as much properties as possible (with homepage, description, developer comments and so on) at a addon creation. 

these worked :
{"categories": {"firefox": ["other"]}, "version": {"upload": "09e377ebb048434c9721746175513ef5", "license": "MPL-2.0","compatibility": {"firefox": {"min": "90.0", "max": "92.*"}}}}
{"categories": {"firefox": ["other"]}, "version": {"upload": "4d67869aa13b428ebcf31b44aeb1e3a6", "license": "MPL-2.0","compatibility": ["firefox","android"]}}
