### ISSUE TITLE
Don't show or require reasons for theme reviews

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#18380]
For the #18168 Reviewer Statistics Improvement project, we are less interested in review decision stats for themes. For the time being, we should not require a reason, nor show the reasons, when a theme is being reviewed. 

If this is difficult to do I'm happy to talk about alternatives:
* Allow selecting what reasons apply to different kinds of add-ons, e.g. some reasons only apply to themes
* Accept doing nothing until at least Q1, accepting that theme reviewers will need to select specific reasons from the list that we tailor towards themes.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I checked the static themes: New and Updates queue no longer have the reason box displayed at approval, reject, reject multiple or reply actions. 

![rev tools](https://user-images.githubusercontent.com/33448286/143875253-f8e78408-e6f7-4b6f-994a-5042fcec0b6e.png)
