### ISSUE TITLE
License changes are not visible in frontend pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18397]
While testing for https://github.com/mozilla/addons-server/issues/18359 I ran into a strange issue - I say that because I could not reproduce it with other extensions (lang packs or dicts)

I tried to change the License for (from GNU to Mozilla Public or something else)

https://addons.allizom.org/en-US/firefox/addon/english-us-language-pack/

another example where this was reproducible:
https://addons.allizom.org/en-US/firefox/addon/deutsch-de-lang-pack/

In dev hub it is changed successfully but when going to the frontend I don't see the changes, the old license is still displayed. 

Notes:
I am logged with an admin account. 
Even if I open the frontend page into a different browser and login I will not see the change I just made in dev hub.

**Comment by eviljeff** [comment]
how long ago was it changed?  (might be caching)

**Comment by diox** [comment]
Which version did you change the license on ? Licenses are set on versions, and langpacks are a little special, the version shown in the detail page might not be the latest uploaded one, as we try to return one that is compatible with your browser version.

**Comment by diox** [comment]
You can see the different licenses if you look at the all versions page: https://addons.allizom.org/en-US/firefox/addon/english-us-language-pack/versions/

**Comment by ioanarusiczki** [comment]
@diox When making the changes from dev huv that would apply to the last submitted listed version but that's not what I see on the frontend for this langpack, going to versions I see change indeed. 
On frontend I have an older version displayed "70.0buildid20190815103430" that is compatible with my browser. 

Thanks for the explanation. 
I'm closing this.
