### ISSUE TITLE
Update DEV_AGREEMENT_CHANGE_FALLBACK

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#18393]
The add-on policies are being updated Dec 1.

We need to update `DEV_AGREEMENT_CHANGE_FALLBACK` to `datetime(2021, 12, 1, 12, 00)`.

The change must go out after 2021-12-01, 12:00pm UTC, so we can schedule it for the push on December 9.

**Comment by AlexandraMoga** [comment]
@wagnerand I've logged in with an older developer account on -dev (had accepted Dev agreement at a past date) and I was prompted to accept the Developer agreement again when I've tried to upload a new addon.
I've also registered a new account to make sure that accepting the Developer agreement is required at a first addon submission.

This looks to be working as intended.
