### ISSUE TITLE
Show some helpful text in the blocklist admin

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#18407]
![image](https://user-images.githubusercontent.com/607198/143611919-7e7567ff-14b0-4ea3-9f22-e6f734cba2e8.png)

**Comment by wagnerand** [comment]
What's missing here?

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and I can see the help text under the "Url" and "Reason" fields.
[block submission form]
![image](https://user-images.githubusercontent.com/31961530/146206174-640da247-0355-4cb0-b83e-321051177795.png)

The new text is also visible in the [Blocklist submissions summary](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/455/change/?_changelist_filters=signoff_state%3D4):
[block submission summary]
![image](https://user-images.githubusercontent.com/31961530/146206203-cf24864b-ad60-468e-8424-d843391fe11b.png)

But the text is not present on the [change block page](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26295/change/). @kewisch Did you want to have the help text here as well?
[edit block page]
![image](https://user-images.githubusercontent.com/31961530/146206229-c5326638-4466-47d3-8ba2-a7bc4a65c959.png)
