### ISSUE TITLE
Allow admin reviewers to create blocklist submissions without VPN that always require sign-off

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#18404]
Creating a block entry currently requires admin and special permissions. This makes it difficult to see who originally found the add-on that led to a block. It also requires us to triage blocks from our contractors via bugzilla.

Pending review if this is ok from a security standpoint, I'd like there to be a way for SV reviewers to request a block via reviewer tools (no VPN), which would *always* make it end up requiring a sign-off, even if it has less users than the threshold. The block submission would be attributed to the reviewer in the database, so I can easily see how many blocks were requested.

**Comment by eviljeff** [comment]
The requirement to not use the VPN means a new tool would have to be written, partially replicating the functionality of the tool that lives in django admin, in the reviewer tools.  (All of the django admin is behind the VPN).  It's a roadmap sized chunk of work.

**Comment by diox** [comment]
That's partially a question for IT/ops, but wouldn't it be easier to give them VPN access ? Maybe they could be in a separate group and we would allow that group to access the admin.

**Comment by eviljeff** [comment]
this is being dealt with in https://github.com/mozilla/addons-server/issues/20498 (et al.)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-69
