### ISSUE TITLE
Remove old new_69_theme_properties_from_old & new_theme_version_with_69_properties utils

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18406]
`new_69_theme_properties_from_old()` and `new_theme_version_with_69_properties()` in `src/olympia/versions/utils.py` are obsolete. They were needed for the `repack_themes_for_69` task, which we removed in 12bc5b424324ec51ea08eebabf93fbbc451db5bb / #13506. We should remove them.

**Comment by riadh26** [comment]
There is no `new_theme_version_with_69_properties()` in `src/olympia/versions/utils.py`, is it the `build_69_compatible_theme()` ?

**Comment by diox** [comment]
Yes, sorry, wrong copy/paste on my part, `new_theme_version_with_69_properties()` has already been removed, `new_69_theme_properties_from_old()` and `build_69_compatible_theme()` are the functions that needs to be removed.

**Comment by diox** [comment]
Thanks, @riadh26 !
