### ISSUE TITLE
Fix timing messages so they are not truncated in Grafana

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18410]
I noticed that the labels for the timings that I added for submit source are being truncated in Grafana because they include spaces. I think we need to change them to use dashes or underscores instead of spaces. For example, [`timer.log_interval('1.form populated')`](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/views.py#L1589) should be changed to `timer.log_interval('1.form_populated')`.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Please add some str for qa. 
Thanks!

**Comment by bobsilverberg** [comment]
Sorry, @ioanarusiczki, QA not needed.
