### ISSUE TITLE
Cannot download compatibility bump validation log

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#1841]
STR:
1. Go to https://addons.mozilla.org/en-US/admin/validation
2. Click on `Download Errors/Warnings` for a finished validation job.

Expected results:
Access to csv file.

Actual results:
500.

Related sentry reports:
https://sentry.prod.mozaws.net/operations/olympia-prod/group/241493/
https://sentry.prod.mozaws.net/operations/olympia-prod/group/241494/
https://sentry.prod.mozaws.net/operations/olympia-prod/group/241495/

**Comment by wagnerand** [comment]
This looks like a cache issue, adding @jasonthomas.

**Comment by jvillalobos** [comment]
This is blocking the Firefox 45 compat bump, which needs to happen today. /cc @andymckay

**Comment by jasonthomas** [comment]
I don't think this is the sort of cache I can help with. Is this related to the django 1.7 upgrade?

cc @EnTeQuAk
