### ISSUE TITLE
Create a Grafana dashboard for source submit timings

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18412]
Create a dashboard that can be used to analyze the data from statsd pings that were added to the submit source view.

This should include timings for the different steps, as well as a count of source code uploads.

**Comment by bobsilverberg** [comment]
I have created the initial dashboard [here]( https://earthangel-b40313e5.influxcloud.net/d/SkaM51tnz/amo-submit-source-measurements?orgId=1&refresh=1m&var-env=dev), as a copy of https://earthangel-b40313e5.influxcloud.net/d/TUeD9MpWk/amo-security-tools?orgId=1&refresh=1m.

Although I made a copy of the AMO Security Tools dashboard, and the new dashboard does include a select in the upper left-hand corner which allows one to select an `env`, the select doesn't seem to change the data in the dashboard. I'll see if I can figure out why.

**Comment by bobsilverberg** [comment]
> 
> Although I made a copy of the AMO Security Tools dashboard, and the new dashboard does include a select in the upper left-hand corner which allows one to select an `env`, the select doesn't seem to change the data in the dashboard. I'll see if I can figure out why.

I figured out the problem and am in the process of fixing it.

**Comment by bobsilverberg** [comment]
@diox Perhaps you can take a look when you get a chance and let me know what changes, if any, you'd like to see.

**Comment by bobsilverberg** [comment]
> mmm I can't check logs right now (the console is erroring out for me), but I tried to upload sources on dev, using the submission flow since that's the bit that should be covered by the statsd pings + logs, and I don't see anything new in the graph.

I believe the issue is that, with the landing of https://github.com/mozilla/addons-server/pull/18411, the names of the events have changed. The current graphs are using the old names. The new names are active on dev, but won't be on stage and prod until the next push. I guess for now I can add a set of charts with the new names, so we can see both sets of data. At some point, when we have sufficient data on prod with the new names I can remove the charts with the old names.

**Comment by bobsilverberg** [comment]
@diox I did what I suggested above, and now, on dev, we can see data for both before and after the name change.

**Comment by diox** [comment]
Thanks. This highlights an issue with the timers/logs: for some of them we are also doing them even for the initial load of the page which displays the form. This skews the data, cause you get timings for both the initial `GET` request and the `POST` when the developer submits the form.

This is easy to see with the graph: `_submit_source.1.form_populated.sum` has a value of 2 after a single attempt, and we can see `5.validation_failed_re-displaying_the_template` even for a successful upload, because it's triggered by the initial load of the form.

**Comment by diox** [comment]
In addition, there is a separate weird issue with the graph showing all the timers: when clicking on a particular timer the graph is correct, but when they are all shown the color is incorrect - we can see a red spike that seems to correspond to `_submit_source.5.validation_failed_re-displaying_the_template.mean` but actually if we look more closely at the raw data by hover the graph, or select the timer individually, we notice that the spike is actually for `_submit_source.3.form_saved.mean` which makes more sense.

**Comment by bobsilverberg** [comment]
> Thanks. This highlights an issue with the timers/logs: for some of them we are also doing them even for the initial load of the page which displays the form. This skews the data, cause you get timings for both the initial `GET` request and the `POST` when the developer submits the form.
>
> This is easy to see with the graph: `_submit_source.1.form_populated.sum` has a value of 2 after a single attempt, and we can see `5.validation_failed_re-displaying_the_template` even for a successful upload, because it's triggered by the initial load of the form.

I'm not sure I follow what you're saying, probably due to my unfamiliarity with Grafana. It sounds like you're saying we should alter the logging code to make sure that we don't log for the initial form display. Is that the extent of the issue or is there more to it than that?

**Comment by diox** [comment]
Yes. (We clarified on slack that I was able to make those conclusions because I was testing with dev and I was the only one making uploads at that time - even going as far as spacing my attempts to ensure I would capture reliable data)

**Comment by diox** [comment]
I edited the graph now that https://github.com/mozilla/addons-server/issues/18461 has landed on dev, to only show the new names and include separate graphs for version edit. I realized that there is a minor issue with the logging in version edit: we also log even when there are not changes to the source. I think that's acceptable for now though.

**Comment by diox** [comment]
Same problem also exists in submit source: we log even when the developer is choosing `no` in the form.

**Comment by bobsilverberg** [comment]
> Same problem also exists in submit source: we log even when the developer is choosing `no` in the form.

Ok, thanks for pointing that out. I will open an issue to fix that for both views.

**Comment by diox** [comment]
It appears to be working now, we can close this.
