### ISSUE TITLE
add api endpoint that exposes available tags

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18427]
The addon api will soon allow tags to be edited #18268 and the tag selection is limited to what admin/curation staff have chosen.  But we need some way for clients to know the available tags (documenting it in the API isn't practical because the tags are defined in the database so can change at any time without code changes)

**Comment by ioanarusiczki** [comment]
@eviljeff  https://addons-dev.allizom.org/api/v5/addons/tags/ is responding with a 200 and returns the list of tags for AMO dev.
