### ISSUE TITLE
404 errors generated on the default icon 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18438]
While checking for https://github.com/mozilla/addons-server/issues/18104 I've noticed that when clicking the default icon into Images section the network is generating 2 404 errors for the 64 px and 128 px size. 

![click on the default icon](https://user-images.githubusercontent.com/33448286/144384773-048ae2d8-489a-47d6-9b2e-63d3a5041264.gif)

After saving changes the errors are gone. 
It is reproducible on all AMO servers.

**Comment by diox** [comment]
So what happens is, when you click on the default icon on the left, the JavaScript code updates the icons on the right to match. It does this by getting the size 32 url and then doing a search & replace for `32` to `64` and `128`. Now that we're using `collecstatic` properly this is wrong, they will have different hashes so you can't guess the URLs that way. This is all very old code that was a lot more useful when there were multiple default icons to choose from...

**Comment by ioanarusiczki** [comment]
@diox it's no longer reproducible on AMO dev - FF94(Win10).
