### ISSUE TITLE
Removed unused columns/code in update service database query

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18442]
The update service does a `SELECT` with a bunch of columns:
https://github.com/mozilla/addons-server/blob/7bc09ac344ae9a2756acdfc88d6308e449df2f37/services/update.py#L91-L104

Then when building the results, they are referenced again and part of the data used to build the update:
https://github.com/mozilla/addons-server/blob/7bc09ac344ae9a2756acdfc88d6308e449df2f37/services/update.py#L165-L178

But if we look at the code below, in `get_success_output()` and `get_no_updates_output()`, only a few are actually needed, so we could remove some. We can also remove the awkward `ADDON_SLUGS_UPDATE` constant.

In addition, there is also a check using `applications.D2C_MIN_VERSIONS` that is completely obsolete since we no longer have legacy extensions.

**Comment by diox** [comment]
QA: check that updates work correctly, including *not* updating if the newest version of an add-on has a `strict_min_version` higher than the app version the client requesting the update is using.

**Comment by AlexandraMoga** [comment]
I've verified add-on updates on -dev and I've had the following results:

- extension updates (without compatibility restrictions) are working as expected
- theme updates are working as expected
- dictionary updates are working as expected
- for language pack updates I used the following test method:
  - have a langpack with two versions, one compatible with an earlier version of Firefox (i.e. 93.0) and a new version compatible with the current Firefox release (i.e. 94.0);
  - open a profile in Firefox 93 and install the earlier version 
  - open the same profile in Firefox 94 and check for updates in about:addons => the new language pack version compatible with 94.0 is fetched
- extensions with `strict_min_version` higher than the client used to trigger updates:
  - I've created an add-on with two versions: the first one without compatibility restrictions and installed it in the current Firefox release (94.0.1)
  - I've uploaded a new version with  `strict_min_version` set to 95.0
  - I've checked for updates in about:addons => there were no updates returned for the installed addon

As a sidenote, while triggering these updates I've noticed that caching will interfere with the update check, namely, I might not receive updates to a new (valid) version in about:addons unless I've waited for some time (in my case was somewhere between 15 - 30 minutes). This happens only when a new version is uploaded _after_ the add-on has already been installed and not when the newer eligible version already existed at the time of the installation.

**Comment by diox** [comment]
> As a sidenote, while triggering these updates I've noticed that caching will interfere with the update check, namely, I might not receive updates to a new (valid) version in about:addons unless I've waited for some time (in my case was somewhere between 15 - 30 minutes). This happens only when a new version is uploaded after the add-on has already been installed and not when the newer eligible version already existed at the time of the installation.

Yes, that is expected. There is up to one hour caching on update results
