### ISSUE TITLE
Versions endpoint allows listed addon submission for the invisible state

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18451]
When an addon has an invisible status - the addon listed submission is no longer possible from dev hub (unlisted submission is allowed only)

Using the versions endpoint I could submit new listed versions, it creates an inconsistency which probably needs discussion as mentioned https://github.com/mozilla/addons-server/issues/18330#issuecomment-985540986

Two examples:
https://addons-dev.allizom.org/api/v5/addons/addon/620309/versions/ 
https://addons-dev.allizom.org/api/v5/addons/addon/620344/versions/

**Comment by eviljeff** [comment]
I'm going to fix this is in the most minimal way - replicate devhub's restriction but use the API terminology in the error message (`disabled` rather than `inactive`).  When we have a frontend that displays these messages to the developer we'll need to settle on the correct terminology.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified this on -dev with an extension and a static theme using the versions endpoint:

- when the addon is invisible I cannot submit a new listed version-> only unlisted versions can be submitted 
The message for listed submissions : "Listed versions cannot be submitted while add-on is disabled."

- I switched back to visible and the submissions can be made for the listed channel too. 

I've noticed an issue and filed it https://github.com/mozilla/addons-server/issues/18519
