### ISSUE TITLE
Update logging logic for submit_source

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18461]
This is a spin-off from https://github.com/mozilla/addons-server/issues/18412#issuecomment-985469239.

The current logic as implemented includes logging for the initial display of the form, which we don't want. In order to fix this, all logging code should be gated on `request.method == 'POST'`.

In addition to making that change, we should add logging to the `version_edit` path which also submits source code.

**Comment by diox** [comment]
As mentioned in #18142 there is a minor issue with the logging in version edit, we also log even when there are not changes to the source, but that's acceptable for now - it's good enough for our own testing, it's just something that we need to be aware of when we look at prod data.
