### ISSUE TITLE
Update redis docker image

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#18467]
We are using `redis:2.8` in `docker-compose.yml`. It is 5 years old and the
current latest version is `6.2`. We should probably update our `redis` image.

**Comment by diox** [comment]
Cross-linking: https://mozilla-hub.atlassian.net/browse/SVCSE-461 for dev/stage/prod

**Comment by diox** [comment]
This is only used for celery result backend nowadays so it should be pretty safe to upgrade.
