### ISSUE TITLE
Allow developers to add a hero image

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-server#18478]
Extensions featured on the AMO homepage are presented along stock photos, which could be replaced by relevant illustrations. Developers could upload a hero image while editing the product page, which would be subject to review. To avoid putting further strain on the reviewer team, the upload feature could be enabled only for extensions that are either recommended, or currently featured on the homepage.

Similar features for uploading promotional images are available in competing extension stores, and it helps users better understand or recognize the extension at a glance, which increases the conversion rate of homepage promotions.

**Comment by devaneymoz** [comment]
Hi, and thanks for your suggestion! Only Recommended and Mozilla built extensions are featured on the AMO homepage hero area. If the developer of a Recommended extension would like to provide a custom image for us to consider using in the hero we're happy to manually review, and if appropriate, upload for use. I don't think we need to go to the length of creating a new upload tool, though. Any Recommended developer (such as yourself!) is free to contact me directly to discuss and coordinate the use of a custom image.

**Comment by dessant** [comment]
Thanks @devaneymoz! I don't have an illustration to share at the moment, but it's great that custom images are allowed.
