### ISSUE TITLE
cfx validation error shouldn't appear as error for bulk validation

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#1847]
PR #381 introduced this change, but it's also showing up as an error for the Firefox 45 bulk validation. It shouldn't, and it's preventing us from notifying developers. Ideally, we should fix this and exclude it from bulk validations, but at this point disabling the test temporarily would be good enough for me.

**Comment by mstriemer** [comment]
I assume that's supposed to be https://github.com/mozilla/amo-validator/pull/381?

**Comment by mstriemer** [comment]
Just to be clear: we're going to keep upgrading these add-ons but if the developer has a bug fix they want to upload we will reject it?

**Comment by wagnerand** [comment]
Closed #403.
