### ISSUE TITLE
Header images uploaded with the theme wizard are not visible in the preview 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#18476]
### Describe the problem and steps to reproduce it:
1. Open the theme creation wizard in devhub - https://addons.allizom.org/en-US/developers/addon/submit/wizard-listed
2. Upload a valid image as the theme header
3. Verify the uploaded image in the browser preview 

### What happened?
The uploaded image is not visible in the browser preview. There is a CSP error in the console that seems to block the image rendering:
```
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/jpeg;base64,/9j/4QAYRXhpZgAAS… (“img-src”).
```
![image](https://user-images.githubusercontent.com/31961530/145371175-6a4466ce-ff28-4133-a43e-8a18c785b88e.png)

### What did you expect to happen?
The uploaded theme header should be visible in the Browser preview

### Anything else we should know?
- If you finish the submission, the image uploaded will be visible in the generated theme.
- Issue doesn't reproduce on prod

**Comment by diox** [comment]
Woops! The weird thing is that prod should be affected, the CSP changes should have landed last week...

**Comment by AlexandraMoga** [comment]
Uploaded theme headers are now visible in Browser previews:
![image](https://user-images.githubusercontent.com/31961530/145401335-2b0e4405-42e3-458b-9ff5-c62c4533cff2.png)

This issue is verified fixed on -dev.
