### ISSUE TITLE
Update source submit logging to only log when source is actually being submitted

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18489]
This is a follow-up to https://github.com/mozilla/addons-server/issues/18412#issuecomment-989873194.

We should only log, in both `_submit_source` and `version_edit`, when source is actually being uploaded.

**Comment by diox** [comment]
QA won't be able to verify the logging but might as well let them check source uploads (both from submission and version edit pages) still work fine.

**Comment by ioanarusiczki** [comment]
@diox 
- I could upload source code at addon submission for listed/unlisted
- I could upload/change the source code from the version page -> .zip, .tgz,.tar.bz2 and tar.gz file formats
- for a large .zip file (+50 MB) I ran into a warning message that file's too large, sometimes even a 504 but that's been tested into a separate issue not too long ago.
