### ISSUE TITLE
Add-on validation failed with error Sorry, we couldn't load your WebExtension.

### ISSUE THREAD

**Issue by keinagae** [mozilla/addons-server#18499]
### Addon validation failed 
I am trying to submit my addon but i am getting validation failed error described as 

> Sorry, we couldn't load your WebExtension.

> Error: Validation was unable to complete successfully due to an unexpected error.

I have tested it with addons-linter for error and it returned no errors. 

**Submission time is around 5:40 PM on 13-12-2021 Pakistan Standard Time**

you can use this [https://drive.google.com/file/d/1V6X2Ovhe226pCyz7QeO0WCgxDjBitmWm/view?usp=sharingl ](https://drive.google.com/file/d/1V6X2Ovhe226pCyz7QeO0WCgxDjBitmWm/view?usp=sharing)to download addon zip file

**Comment by eviljeff** [comment]
We were having some problems around that time that have now been resolved - can you try again?
