### ISSUE TITLE
Unable to install the add-on uBlock Origin 1.6.2

### ISSUE THREAD

**Issue by dikei** [mozilla/addons-server#1850]
I'm unable to upgrade to uBlock Origin 1.6.2 on Firefox Beta for Android.
Both the auto updater and manually update failed with the following error.
"The addon could not be installed because it does not match the add-on Firefox expected."

**Comment by dikei** [comment]
Corresponding issue on uBlock Origin's tracker
https://github.com/gorhill/uBlock/issues/1373

**Comment by jvillalobos** [comment]
Can you still reproduce the problem with 1.6.4?

**Comment by dikei** [comment]
I can upgrade to 1.6.4 smoothly now. Thanks.
