### ISSUE TITLE
`validation_results.messages` suffers from inception in signing API responses

### ISSUE THREAD

**Issue by minj** [mozilla/addons-server#1851]
API responses are inflated to ~400K by what seems to be recursion of `validation_results.messages.matched` property. 

For example, I've counted 52 layers of recursion in a GET response to the status check for pk=`5d93053acd9940ccb4691c34b203d1c4`.

Consult the provided screenshot using a JSON viewer extension:

![desktop 1_171](https://cloud.githubusercontent.com/assets/1035523/13557293/3aedfcf0-e3f6-11e5-9bd3-be9501617c43.png)

Since working with such huge files containing no new lines is no fun I stopped digging but I suspect all 14 `validation_results.messages` suffer from an identical problem as those 52 layers amount to ~1/14 of the weight.

Surely this is not the intended behavior?

**Comment by andymckay** [comment]
Could you take a look please @mstriemer?

**Comment by mstriemer** [comment]
I've never really looked at this code, and I'm not sure if it is actually used by reviewers or not. But it looks like it matches the validation to the last run against this file and I guess this file has been validated a lot so each one of those has a match. The next time this runs it will incept 53 layers deep, I believe.

I think we just want to delete the `matched` property on the previous message stop this. See [this code over here](https://github.com/mozilla/addons-server/blob/e66197c915d5b260645fd73fec04ab22b5db7a22/src/olympia/devhub/utils.py#L409-L413). I haven't tested that. But it seems like a likely candidate.

**Comment by minj** [comment]
Is this supposed to be fixed in production?
I cannot confirm. New upload with `pk=ea974e6e2a254280965036a88e35854d` gives  a 500K response. Perhaps there is a need to purge existing entries?

**Comment by andymckay** [comment]
The next push is Thursday and it will be on production then. You can see what goes out in tags: https://github.com/mozilla/addons-server/tags

**Comment by minj** [comment]
@andymckay I still get 500K responses... Like I said, I think you need to clear the existing entries.

**Comment by mstriemer** [comment]
You're getting 500k responses on new uploads or previous ones?

**Comment by minj** [comment]
Uploaded and signed yesterday. See `cb7b061a3437435f9600a941837b3262`

**Comment by minj** [comment]
@mstriemer just FYI, the responses are fine since March, 18th, i. e. later on the day I complained ;)
