### ISSUE TITLE
versions endpoint status is 500 when version already exists 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18519]
I've noticed while testing https://github.com/mozilla/addons-server/issues/18451 that versions API returns a 500 server error when I try to submit a new version which contains an already used version number.
STR: 
1. Version upload uuid for a version (1.0.5 for example) 
2. I make the submission with {"upload": "d5e427f332154f4a9b309cf4a352e6f1", "license": "cc-all-rights-reserved", "compatibility": ["firefox","android"]}
3. I use the upload endpoint again to create a new uuid with the same addon used at step 1 ( I don't change the version number in manifest.json so it's still 1.0.5)
4. I try making the submission with versions endpoint using the uuid from step 3

Result:
-> 500 server error

Expected result:
I should get a 400. " Version 1.0.5 already exists."

**Comment by AlexandraMoga** [comment]
Submitting a new version with the same version number as the previous version is now returning a 400 response with the following response message:

```
{
    "version": [
        "Version 1.98 already exists."
    ]
}
```

This issue is verified fixed on -dev.
