### ISSUE TITLE
Please add healthcheck URLs

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#18510]
### Describe the problem and steps to reproduce it:

Per https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide#NewServiceGuide-StandardEndpoints, all applications running in containers should support a few standard endpoints.

Although the addons-server supports the `__version__` endpoint, it does not support the following health check URLs,

* `/__heartbeat__`
* `/__lbheartbeat__`

Can we add them please?

### What happened?

The addons-frontend recently had an incident that has to do with using TCP port to monitor app health. We filed https://github.com/mozilla/addons-frontend/issues/11059 for it, and would like the addons-server to support the above two health check endpoints as well, so that we can start to using them.

### What did you expect to happen?

The addons-server should support the above said two health check URLs (per Mozilla standard).

### Anything else we should know?
n/a

**Comment by eviljeff** [comment]
`/__heartbeat__` seems to be similar (the same?) as what `/services/monitor.json` returns.  Is that content what's needed?  (And if so, do we still need `/services/monitor.json` or can I remove and replace it with `/__heartbeat__`?)  @bqbn

**Comment by bqbn** [comment]
Yes, I think we can replace `/services/monitor.json` with `__heartbeat__`.

**Comment by ioanarusiczki** [comment]
@eviljeff 

On https://addons-dev.allizom.org/__heartbeat__ I get a 200 response 

But for  https://addons-dev.allizom.org/__lbheartbeat__ it's a 404

**Comment by eviljeff** [comment]
> @eviljeff
> 
> On https://addons-dev.allizom.org/__heartbeat__ I get a 200 response
> 
> But for https://addons-dev.allizom.org/__lbheartbeat__ it's a 404

@bqbn only added the nginx rule for `/__heartbeat__` to allow it be accessed externally - I believe deliberately because `/__lbheartbeat__` is only useful internally within the load balancer.

**Comment by bqbn** [comment]
> > @eviljeff
> > On https://addons-dev.allizom.org/__heartbeat__ I get a 200 response
> > But for https://addons-dev.allizom.org/__lbheartbeat__ it's a 404
> 
> @bqbn only added the nginx rule for `/__heartbeat__` to allow it be accessed externally - I believe deliberately because `/__lbheartbeat__` is only useful internally within the load balancer.

That is correct. The fact that the instances are still considered healthy by the ELB is a good test for the `__lbheartbeat__` endpoint.

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, then I assume I can mark it verified.
