### ISSUE TITLE
Cannot add Thunderbird add-ons to Collections

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#18536]
### Describe the problem and steps to reproduce it:
Created a new collection, https://addons.mozilla.org/en-US/firefox/collections/11536848/icedove/, and tried to add
* https://addons.thunderbird.net/en-US/thunderbird/addon/columnswizard/
* https://addons.thunderbird.net/en-US/thunderbird/addon/xnotepp/

### What happened?
I couldn't because
* There's no "Add to Collection" menu on the add-on pages
* I cannot find Thunderbird add-ons when I Edit a Collection and search them in the "Find an add-on to include in this collection" field.

**Comment by PromoGroup** [comment]
+1

**Comment by eviljeff** [comment]
You can only add add-ons to a collection that are listed and Thunderbird add-ons haven't been listed on addons.mozilla.org in many years.  If addons.thunderbird.net still has collections you could create a collection there.

**Comment by davidhedlund** [comment]
> Thunderbird add-ons haven't been listed on addons.mozilla.org in many years.

Do you know if this issue has been submitted? If so, could you please give me the link?

**Comment by eviljeff** [comment]
> > Thunderbird add-ons haven't been listed on addons.mozilla.org in many years.
> 
> Do you know if this issue has been submitted? If so, could you please give me the link?

https://github.com/mozilla/addons-server/issues/8344 was a key issue but it was a large project
