### ISSUE TITLE
Prevent session cookie from being sent when it's not needed

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18556]
2 things are causing us to return a `Set-cookie: sessionid=...` on almost every anonymous template-based response in addons-server:
1. The register and login links for FxA, on pages like the developer hub landing page, which add a `fxa_state` in the session. Modifying the session causes it to be created/saved and the cookie is sent as a result.
2. The CSRF handling. When a csrf token is used, django flips a flag in the request  (`META['CSRF_COOKIE_USED']`) which is then used by `CsrfViewMiddleware.get_response()`
  to return the cookie or add it to the session (when `CSRF_USE_SESSIONS` is `True` as it's
  the case with our setup), which in turns causes the session cookie to be sent as above.

For 1) the solution is to link to `/api/authenticate/start` or whatever it's called instead of having the true links to FxA (which contain the state parameter) in our HTML.

For 2) we need to find why Django thinks `csrf_token` is being used. On most pages not behind auth it shouldn't be the case, Django's default context processor that adds csrf_token to template contexts is supposed to be lazy, yet I'm seeing this even on the `robots.txt` page. Maybe we are bypassing that somehow ? Could be related to our Jinja2 setup.

**Comment by diox** [comment]
2) is a red-herring, it's caused by... Django Debug Toolbar, only locally.

**Comment by diox** [comment]
QA:
- Once the fix for this lands, going to `/en-US/developers/` anonymously without a `sessionid` cookie should not create one.
- Logging in from that page or elsewhere should still work and redirect you to where you where when you clicked on the link to log in

**Comment by AlexandraMoga** [comment]
@diox I've verified this issue on -dev an these are my results:

- open https://addons-dev.allizom.org/en-US/firefox/ while being logged out =>  `sessionid` cookie not set
- open https://addons-dev.allizom.org/en-US/developers/ directly while being logged out => `sessionid` cookie not set
- use client side navigation to open various pages on the site while being logged out => `sessionid` cookie not set
- logging in in from any page on the site will set the `sessionid` cookie and users will be redirected back to the page where they started the log in process
- the  `sessionid` cookie will remain active on the site until the user logs out, at which point the cookie will be deleted

There weren't any other issues identified concerning the login functionalities.
