### ISSUE TITLE
Theme stats not updated since March 3

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#1856]
Theme user counts have not updated since about March 3, 2016. It was reported in the forums: https://discourse.mozilla-community.org/t/user-count-broken-again/7482

**Comment by atsay** [comment]
@jasonthomas @jvillalobos

**Comment by jvillalobos** [comment]
See also [ABP stats](https://addons.mozilla.org/firefox/addon/adblock-plus/statistics/?last=30)

**Comment by jasonthomas** [comment]
This was a permissions issue. Today's stats update should run correctly. I will begin backfill process later today.

**Comment by MaDonnasPersonas** [comment]
I just checked and from March 7th it hasn't caught up yet.

**Comment by jasonthomas** [comment]
This should now be fixed.

<img width="1174" alt="fixed-stats" src="https://cloud.githubusercontent.com/assets/910992/13651294/999ff5b2-e5fb-11e5-8baa-4fdd7ae1ba52.png">

**Comment by MaDonnasPersonas** [comment]
None of the themes submitted March 7th and after show any users still.

**Comment by jasonthomas** [comment]
Thanks for pointing that out @MaDonnasPersonas. The theme count stats were not populated correctly, I performed a backfill on those.

**Comment by MaDonnasPersonas** [comment]
Looking good now, Jason. Thanks. I am sure everyone appreciates it.

**Comment by JustOff** [comment]
Unfortunately, March 10 is the next point of freezing :-[

**Comment by MaDonnasPersonas** [comment]
Just noticed that myself. Thanks for reporting.

**Comment by MaDonnasPersonas** [comment]
Everything after March 15th aren't being counted.

**Comment by jasonthomas** [comment]
The look okay to me. Which ones are you having issues with? Statistics updates usually finish in PST afternoon.

**Comment by MaDonnasPersonas** [comment]
Thanks. It was this morning I looked and noticed that no one's designs had any users after March 15th, but it has changed now.. I will remember that they don't change until afternoon.

**Comment by JustOff** [comment]
Looks like the problem is back again since April 12.
