### ISSUE TITLE
Stop exposing reviewer names to developers in review emails

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18565]
This is a spin-off from #18564 and is just about removing the names of reviewers from emails sent specifically about reviews. The templates for these emails can be found in `src/olympia/reviewers/templates/reviewers/emails/`. Code used to send emails about activity log entries, as well as code that exposes reviewer names on devhub pages will be dealt with in a separate issue.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I've been looking into Fakemail to e-mails sent to developers after addons/themes are rejected from various queues and none of them displayed the Reviewer Name. 

Verified on -dev with FF95(Win10).
