### ISSUE TITLE
(non-API) /search?recommended=true does not limit to recommended extensions

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#18571]
### Describe the problem and steps to reproduce it:

Visit https://addons.mozilla.org/firefox/search/?recommended=true&type=extension.
That's linked from https://support.mozilla.org/en-US/kb/recommended-extensions-program (and likely other places too, since the link was prominently featured)

### What happened?
The result page shows all add-ons.

### What did you expect to happen?

Only recommended add-ons should be shown. I.e. the ones that appear if I use `promoted=recommended` at https://addons.mozilla.org/en-US/firefox/search/?promoted=recommended&type=extension

### Anything else we should know?
If it is undesirable to support `recommended=true`, an alternative to supporting it would be to update the links on SUMO. This would only fix visits initiated from SUMO, and not other places such as history.

**Comment by bobsilverberg** [comment]
I'm pretty sure we did away with `recommended=true` quite some time ago. The SUMO links should be updated. It's true that there could be other historical links out there, but considering that we did away with `recommended=true` intentionally, I don't think it makes sense to bring it back.

**Comment by Rob--W** [comment]
I've submitted an update to the referenced SUMO page. Hopefully the localized pages are updated automatically too.

**Comment by Rob--W** [comment]
FYI the SUMO article update for en-US has been approved; I'm told at https://chat.mozilla.org/#/room/#sumo:mozilla.org that the localized versions will be notified of the update (and presumably catch up with the update eventually).
