### ISSUE TITLE
canned reponse editor/add new form is broken

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#1858]
The canned response edit page, e.g. https://addons-dev.allizom.org/en-US/admin/models/editors/cannedresponse/43/ is supposed to have fields where you can edit the name and response.  The new response form is similarly broken meaning we can't add any new ones either.

@jvillalobos

**Comment by jvillalobos** [comment]
Is this fallout from enabling CSP? FWIW, we don't update our canned responses very often, so this doesn't require an urgent fix.

**Comment by jvillalobos** [comment]
So, about that, _now_ we need to add a canned response, so the urgency is a bit higher.

**Comment by eviljeff** [comment]
Okay, tracked down the cause to the use of `TranslatedField` so far - django admin isn't displaying those fields for any model that uses them.  E.g. the Addon model page doesn't show name, homepage, support_email, etc.

**Comment by eviljeff** [comment]
Investigated but no joy.
So, 3 options here: 
a) actually fix the issue by spending more time on it 
b) hack the page after loading with some javascript that unhides the fields.  Downsides: hacky; would need to be repeated for other broken forms. 
c) change CannedResponse to use un-translated fields as its only ever written in en-US anyway.  Downsides: potentially tricky migration needed; couldn't be re-used as a solution for forms that actually are localisable.

**Comment by jvillalobos** [comment]
I'm not aware of other forms causing real problems (even this one is just an occasional problem), so I think it's okay to focus the fix on this particular form (b or c). (c) is less hacky, so I would prefer that, but if the migration is too much of a hassle, I think (b) would be okay.

**Comment by vcarciu** [comment]
I am not able to edit a canned response : http://screencast.com/t/Zj2RQlnH8E4

**Comment by eviljeff** [comment]
After testing, looks like we were #2248

**Comment by vcarciu** [comment]
Verified as fixed based on latest comment.
