### ISSUE TITLE
Add authentication and permissions to the new search / detail API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#1859]
Tracker: #1744 

Right now the new search / detail API are limited to listed, public, not disabled add-ons. We need to add authentication and permissions to these APIs to allow showing non public/listed add-ons for reviewers/authors/admins/etc.

**Comment by diox** [comment]
Also: make sure a session cookie can not be used to query the API, in order not to expose us to CSRF attacks with the API.

**Comment by diox** [comment]
From today's vidyo meeting about auth:
- We should start by using JWT Authentication. Other mechanisms don't necessarily buy us more or less security, and we already have something for JWT Auth.
- We currently use http://getblimp.github.io/django-rest-framework-jwt/ for the signing API, so we should re-use that app
- We need new handlers though, so allow token refreshing, longer expiration (one hour? more?), and make the token depend on `SECRET_KEY`, possibly something more elaborate that allows rotating the secret, but not `ApiKey`
- We also need our tokens to have a different scope than the tokens generated for developers using `ApiKey`, that would be checked by our DRF authentication backend
- The login endpoint would generate a token, which the client would then keep for a long time, possibly refresh as needed using an endpoint provided by the server

**Comment by mstriemer** [comment]
We'll need the JWT set in a cookie for it to be accessible to the universal app. The API shouldn't accept this cookie but the universal app can pull the JWT out and send it in an `Authorization` header when it makes API requests. I'm not sure if the login endpoint needs to include the JWT in the response, it might be needed to avoid a full-page refresh on the client side after login. For now I'd say put it in a cookie and we can deal with that if we need it.

Setting the JWT in a cookie is convenient for us but doesn't handle third party support. They can use the API keys though so maybe that doesn't matter.
