### ISSUE TITLE
The source code submission page throws a 403 error when uploading a site-permission addon

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#18596]
Follow up for #18444 

### Describe the problem and steps to reproduce it:
1. Log in with a user that has `Addons:SubmitSitePermission` rights
2. Upload an add-on that uses `"site_permissions":[...]`
3. Once the validation results are successful, click continue to proceed to the Source code submission page

### What happened?
A "Oops! Not allowed." page is displayed and the DevTools Network panel shows a 403 for https://addons-dev.allizom.org/en-US/developers/addon/site_permissions_edits1/submit/source-listed

### What did you expect to happen?
The user should be able to finalize the submission without 403 errors

### Anything else we should know?
- affects both listed and unlisted submissions
- regular addons are not affected
- site-permission addons submitted with the api are not affected

**Comment by AlexandraMoga** [comment]
This issue kind of blocks me from testing all the scenarios I've prepared for  #18444, but as far as I understand, site-permission addons will be using a separate submission form - (#18136), so this error will not occur?

**Comment by diox** [comment]
Site Permissions are not supposed to be submitted by developers through devhub or the API, the special form will be used to generate them instead. The `Addons:SubmitSitePermission` is supposed to be an escape hatch for us to manually generate some in case it's needed.

Is that really a blocker ? Ignoring the fact that you can't continue and submit source code, when that happens, is the add-on uploaded or not ? Can you see it in your list in devhub ?

**Comment by AlexandraMoga** [comment]
> Is that really a blocker ? Ignoring the fact that you can't continue and submit source code, when that happens, is the add-on uploaded or not ? Can you see it in your list in devhub ?

I can test with unlisted add-ons, since they appear uploaded in devhub, but this is how a listed add-on appears in the Manage my submissions page:

![image](https://user-images.githubusercontent.com/31961530/148961866-794c84d4-60db-474c-a3fa-6f76d54bff56.png)

I'm not able to do anything with it, so it is a bit of a blocker only for listed add-ons so far.  Listed submissions are not possible through the API either, due to some weird error I've been running into:

```
{
    "categories": [
        "Invalid category name."
    ]
}
```
The payload I'm sending is valid. I've tested it with a regular add-on and the submission works - i.e. the `categories` field is not complaining. 

If listed add-ons are not in scope, I can ignore those scenarios, although some test coverage would have been good.

**Comment by diox** [comment]
Allowing listed site permissions to be submitted is not in scope but it would be good to fix this properly.

**Comment by diox** [comment]
Site permissions will be removed from AMO in https://github.com/mozilla/addons-server/issues/19771.
