### ISSUE TITLE
Prevent an user from generating a site permission add-on twice for the same origin & permissions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18595]
In the form built for #18136, if a site permission add-on already exists for a given origin + permissions *from the same developer*, throw an error. 

If a site permission add-on already exists for the same origin+permissions but the user is different, let it through: we're not planning to verify origin ownership of the origin, so we have to allow different users to generate an add-on for the same origin.

Note: Someone could still end up as the author of multiple site permission add-ons through authorship changes, race conditions with submitting the form twice while the task is running, etc. The goal with this is to prevent mistakes, it's not meant as a security feature - we have denied origins if we want to completely prevent submissions for a given origin.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and I have the following results:

- if I'm trying to send a request for an origin + permission that was already requested _by the same user_, the submission is not completed
- if I'm sending a request _with a different user_ for an origin + permission that was already requested by _another user,_ the submission is successful 

@diox there is no error message displayed when I'm submitting a duplicate request; I've also checked the Network requests and I'm not seeing anything relevant:

[resubmit a request with the same user for the same origin + permission]
![firefox_d9w69xAJ3J](https://user-images.githubusercontent.com/31961530/150148301-c865f3de-5d06-4484-afe1-2ffd2293ee83.gif)

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:
![image](https://user-images.githubusercontent.com/31961530/150964774-ad3665c4-2e85-4c66-b269-91ac268f82be.png)
