### ISSUE TITLE
Check whether origin is allowed in site permission add-on generator

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18608]
https://github.com/mozilla/addons-server/issues/18136 will allow developers to generate site permissions add-ons for a given origin. Because the add-on is automatically generated, it bypasses the linter, it also currently bypasses the mechanism to deny origins.

We need to run `annotate_validation_results()` or equivalent to benefit from `DeniedInstallOrigin.find_denied_origins()`, which will ensure we don't generate site permission add-ons for origins we've denied.

**Comment by AlexandraMoga** [comment]
I've verified the Origin input field from the site-permission add-on generation form against the denied origins set in https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/deniedinstallorigin/ and I've arrived at the same concussions mentioned in https://github.com/mozilla/addons-server/issues/18331#issuecomment-984743921.

@diox one thing I've noticed now, but didn't think of it when I first verified denied origins: if I add a full URL in admin denied origins - like http://this-origin-is-denied.com - and then try to request a site-permission add-on with that origin, the request is successful. The same applies for add-on uploads that have this value in `install_origins`.  Shouldn't a full match be denied?

**Comment by diox** [comment]
It's a little confusing because of the name, but Denied Install Origin instances are matching against the hostname, not the full origin. So you need to add a Denied Install Origin for `this-origin-is-denied.com`, and that should deny http://this-origin-is-denied.com (as well as https://this-origin-is-denied.com, http://this-origin-is-denied.com:8888, etc). Maybe we could add a warning in the admin if the pattern starts with `http://` or `https://`

**Comment by AlexandraMoga** [comment]
> So you need to add a Denied Install Origin for `this-origin-is-denied.com`, and that should deny http://this-origin-is-denied.com (as well as https://this-origin-is-denied.com, http://this-origin-is-denied.com:8888, etc)

if I add `this-origin-is-denied.com` as a denied origin in admin, I have the following behavior:
- http://this-origin-is-denied.com => is not allowed
- https://this-origin-is-denied.com => is not allowed
- http://this-origin-is-denied.com:8888 => request is successful; this origin will be denied only if I use the following format in admin: `this-origin-is-denied.*`

**Comment by diox** [comment]
@AlexandraMoga ah, can you file an issue for this ? This would affect both this and the regular submission of an add-on that specifies an install origin in its manifest. Fortunately it's an easy fix.

**Comment by AlexandraMoga** [comment]
Filed https://github.com/mozilla/addons-server/issues/18648
