### ISSUE TITLE
Some unlisted submissions pending manual review are not in the review queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#18618]
### Describe the problem and steps to reproduce it:

We noticed that some unlisted submissions pending manual review do not appear in _Unlisted Add-ons Pending Manual Approval_ (`/reviewers/unlisted_queue/pending_manual_approval`)

STR:
1. Submit an unlisted add-on (it will be auto-approved).
2. As a reviewer, disable unlisted auto-approval.
3. Submit an update.
4. Attach source code.

### What happened?

The add-on does not show up in the queue mentioned above.

### What did you expect to happen?

The add-on shows up in the queue mentioned above.

### Anything else we should know?
According to @diox:
_`UnlistedPendingManualApprovalQueueTable.get_queryset()` doesn't pass `admin_reviewer` argument down to `get_unlisted_pending_manual_approval_queue()` as it should_

**Comment by ioanarusiczki** [comment]
@diox I verified the scenario on AMO dev, it is no longer reproducible.

I also tried similar scenarios with both versions in awaiting review, both having submitted source code, none having submitted source code but all ended up into [pending_manual_approval](https://reviewers.addons-dev.allizom.org/en-US/reviewers/unlisted_queue/pending_manual_approval?sort=-waiting_time) queue.  

I've tested around on AMO stage  too but looks like that's the only scenario that had issues - when source code is attached to the update.
