### ISSUE TITLE
CSV download after bulk validation broken

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1862]
Sentry error: https://sentry.prod.mozaws.net/operations/olympia-prod/group/241494/

URL that's resulting in a 500 error: https://addons.allizom.org/en-US/admin/validation/179/tally.csv

**Comment by wagnerand** [comment]
Note that the next compat run will probably happen before London.

**Comment by EnTeQuAk** [comment]
indeed, I have it on my list to tackle asap with high priority now that most of the the linter stuff is done

**Comment by EnTeQuAk** [comment]
Unfortunately I still have a hard time reproducing this locally... working on it

**Comment by vcarciu** [comment]
@EnTeQuAk  : Can you please add some STRs to this bug or add "needs no qa" label? Please note that the link from the bug description is still 500ing for me.

**Comment by wagnerand** [comment]
This is still broken: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/337732/

**Comment by EnTeQuAk** [comment]
And a bit different this time. As discussed in IRC, let's talk about it 'cause I'll reimplement it so that it will be saved in the database once and for all.

**Comment by EnTeQuAk** [comment]
Moving this to the next milestone, we discussed a possible reimplementation of that feature this morning which should be reasonable but there's a few other more important things for now.

**Comment by wagnerand** [comment]
Do you think we could tackle this before the next bulk validation is supposed to be run?

**Comment by EnTeQuAk** [comment]
absolutely, I'd love to have the next bulk validation as an real-life test for the new implementation.
