### ISSUE TITLE
Replace "Occitan (Lengadocian)" with "Occitan"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#18626]
See mdn/content#11868

In short, we should use `Occitan` without the specific dialect (Lengadocian) because Occitan has different dialects, see also: https://en.wikipedia.org/wiki/Occitan_language

**Comment by ioanarusiczki** [comment]
@willdurand 
This has been verified into https://github.com/mozilla/addons-frontend/issues/11096
