### ISSUE TITLE
/search-tools/ results in lots of server errors for zh-tw

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1863]
Sentry error: https://sentry.prod.mozaws.net/operations/olympia-prod/group/241244/

This might be another problem because of a broken translation, not sure though.

**Comment by andymckay** [comment]
I think it is, https://github.com/mozilla/addons-server/blob/master/locale/zh_TW/LC_MESSAGES/django.po#L3552-L3559 looks suspicious.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screencast: http://screencast.com/t/mwRW2Heb9
