### ISSUE TITLE
Allow Fake FxA login page to redirect to :7000

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18637]
When testing locally with `yarn amo:olympia`, the site is hosted at `olympia.test:7000`. After logging in via the Fake FxA screen, you are redirected to  `olympia.test`, without the port. This is quite annoying as you have to remember to update the URL to include the `7000` port, which is fine for the most part, but if it's important to test something without reloading the site then you are out of luck.

It would be nice if the Fake FxA page could somehow notice that you have come from port 7000, and then redirect you back to that port. If we can do that conditionally then it shouldn't interfere with the running of addons-frontend from within the docker environment.

I can work on this, but if either @diox or @eviljeff have any helpful tips they would be welcome.

**Comment by AlexandraMoga** [comment]
Should this be a qa:not needed, since it affects only the local env?

**Comment by diox** [comment]
The main benefit of the patch is for local envs, but you can test that it didn't break logging in w/ redirecting you to the page you were on before.

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev by performing the logging from different areas of AMO. The users were correctly redirected every time after login.
