### ISSUE TITLE
GET_http://detectportal.firefox.com/canonical.html_HTTP/1.1 

### ISSUE THREAD

**Issue by f1-outsourcing** [mozilla/addons-server#18651]
What is the point of doing this constantly when it is blocked? You look like some google or microsoft that is constantly trying to grab data. If it does not work, it does not work the next second and the next second and the next second.

If your coffee machine is broken on the development department, you must have a whole queue of developers behind it, all trying the button the every second????

1642674719.139  PROXY.53245 00003 - 192.168.122.149:50640 0.0.0.0:0 0 0 0 GET_http://detectportal.firefox.com/canonical.html_HTTP/1.1
1642674720.903  PROXY.53245 00003 - 192.168.122.149:50641 0.0.0.0:0 0 0 0 GET_http://detectportal.firefox.com/canonical.html_HTTP/1.1
1642674721.094  PROXY.53245 00003 - 192.168.122.149:50642 0.0.0.0:0 0 0 0 GET_http://detectportal.firefox.com/canonical.html_HTTP/1.1
1642674723.133  PROXY.53245 00003 - 192.168.122.149:50643 0.0.0.0:0 0 0 0 GET_http://detectportal.firefox.com/canonical.html_HTTP/1.1
1642674723.449  PROXY.53245 00003 - 192.168.122.149:50644 0.0.0.0:0 0 0 0 GET_http://detectportal.firefox.com/canonical.html_HTTP/1.1

How to get rid of this, I am getting annoying popups from the proxy even though allowed connections are fine

Please redirect issue to appropriate repo/people

**Comment by eviljeff** [comment]
I don't have any idea what product/service you're talking about, but it's not related to the addons website (https://addons.mozilla.org/) so we can't help.

**Comment by f1-outsourcing** [comment]
If you do not know, how can 'regular' users know? Maybe suggest to the development team to created some catch all repo that redirects issues. This firefox is getting more and more crappy, and if you block incoming feedback, it will only get worse. I already installed brave.
