### ISSUE TITLE
Activity logs for site-permission add-on generation are incomplete

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#18650]
Follow up for https://github.com/mozilla/addons-server/issues/18638#issuecomment-1016578702

### Describe the problem and steps to reproduce it:
1. Request a site-permission add-on through the [devhub form](https://addons.allizom.org/en-US/developers/site_permission_generator/)
2. Open the admin [Activity logs](https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/) page and search for entries corresponding to the site-permission add-on generation

### What happened?
You can see an `ActivityLog` for the `{id:username} | {version} added to the {addon}` but not one for the add-on creation itself

### What did you expect to happen?
An `ActivityLog` of the format `{id:username} | {addon-name} was created` should be created when requesting a new site-permission add-on

![image](https://user-images.githubusercontent.com/31961530/150304583-17e2ee7a-d7e9-4137-b68d-a56223bcad5a.png)

**Comment by diox** [comment]
QA: in addition to testing this, please check that uploading through both new and old API, as well as devhub, still works correctly and results in an ActivityLog entry for the add-on creation.

**Comment by AlexandraMoga** [comment]
I've verified the activity logs (both in admin and the developer feed) created for the below add-on submission methods:
- devhub listed/unlisted submissions
- devhub site-permission add-on generation form
- devhub admin override for add-on with failed validation
- signing API (old)
- submission API (new)

For all these submission methods, there is a log for the add-on creation and another one for the version creation, as in the example below:
![2022-01-31_15h36_55](https://user-images.githubusercontent.com/31961530/151818770-62c062be-4293-41d3-a444-7b91a4b25169.png)

Tis issue is verified fixed on -dev.
