### ISSUE TITLE
Jarring flash as carousel loads

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1865]
See screencast: https://www.dropbox.com/s/eoacyx4hc8zm2z8/carousel-load.mp4?dl=0

Seems like we should do something to provide space for the carousel if we know it's in the page.

**Comment by mstriemer** [comment]
This always bothered me.

It's pulling HTML from the server for some reason. It would be a lot nicer if it just rendered the whole thing out initially. We could hide the controls until JS loads (if that's why it's done this way) instead of the whole thing.

**Comment by muffinresearch** [comment]
I think this is mostly resolved now with the animation.

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/tla2T849huc
