### ISSUE TITLE
Header and carousel are cramped

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1866]
Features extensions heading looks a bit cramped when the carousel is in the page:
﻿
![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13638098/a25b3958-e602-11e5-91c7-cd08f90bfdff.png)

Also `most popular` and `explore` headings not equal distances from the blue header background.

**Comment by tofumatt** [comment]
I would love to tweak this, but I don’t know how to get that Pick of the Month to show on my local dev server, and there’s nothing in the docs. Could you walk me through it? (And I’ll add docs :-))

- tofumatt

On 9 March 2016 at 14:25:24, Stuart Colville (notifications@github.com) wrote:

Features extensions heading looks a bit cramped when the carousel is in the page:
﻿


Also most popular and explore are not equal distances from the blue header.

**Comment by muffinresearch** [comment]
* Open the admin 
* Hover on `Manage Add-ons` in the nav bar
* Click Discovery Pane Promo modules

On that page enable some promos by sticking numbers in the boxes.

Ones that work are:

* `Olympics` and `holiday` are ones that work locally.

**Comment by ValentinaPC** [comment]
Verified as fixed don AMO-dev FF45(Win 7).
"Explore", "Featured Extensions" and "Most Popular" are at the same distance from the promo banner.
Postfix screenshot: 
![2016-04-08_1149](https://cloud.githubusercontent.com/assets/15685960/14378981/7b336086-fd80-11e5-8727-a1184fe63676.png)
