### ISSUE TITLE
See all link is not the same colour as the other links.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1867]
Not sure if this is intended or an inconsistency.

![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13638169/fba96df4-e602-11e5-8dae-543b718a97c5.png)

**Comment by tofumatt** [comment]
Not intentional; PR incoming!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-08_1141](https://cloud.githubusercontent.com/assets/15685960/14378666/e19b5542-fd7e-11e5-9cdd-cd40014c581c.png)
