### ISSUE TITLE
Remove easy-thumbnails dependency

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18679]
We depend on `easy-thumbnails` only for the following:
https://github.com/mozilla/addons-server/blob/f7db392878567b7332f362534c90fc7ca84c5ca1/src/olympia/amo/utils.py#L648-L649

So, a single function: `scale_and_crop` from https://github.com/SmileyChris/easy-thumbnails/blob/7ee6219f180c2f73b22b6f4a91c1647fff4696b4/easy_thumbnails/processors.py#L115-L270

Notably, we always pass a `size`, and we never pass `crop`, `upscale`, `zoom` or `target` argument. So we should be able to replace `scale_and_crop` entirely by:
- A check on the requested size being too small compared to the image size:
  - If the image is already small, do nothing
  - If it's not:
    - `im = im.convert('RGBA')`
    - `im = im.resize(...)` call with the right parameters for the x and y size, passing `resample=Image.ANTIALIAS` to keep doing antialiasing.

We should already have enough tests covering this. To manually test it, upload various images to devhub (in various sizes, aspect ratios and formats) and check that the thumbnails are generated correctly.

**Comment by Vish-Yadlapalli** [comment]
@diox: When should we consider the requested size as too small? 

- I'm thinking if the requested size is less than 10% of the original image's size?
- Should scaling up the image size be allowed?

**Comment by diox** [comment]
Small here just means target `size` (or smaller). We should never scale up.

**Comment by Vish-Yadlapalli** [comment]
This works while resizing PNG files but breaks for SVG files as they don't have a single native size but two size concepts (view box, height, and width attributes.)

`FAILED src/olympia/amo/tests/test_amo_utils.py::test_resize_image_from_svg - ValueError: bad transparency mask`

Apparently, `PIL` doesn't handle SVG files, and the `easy-thumbnails` library has the functionality to unpack SVG files and derive height and width attributes. 

https://github.com/SmileyChris/easy-thumbnails/blob/7ee6219f180c2f73b22b6f4a91c1647fff4696b4/easy_thumbnails/VIL/Image.py#L51-L60

We might end up writing a bunch of code to remove the easy-thumbnail dependency. Should I go ahead with it?

**Comment by eviljeff** [comment]
We should have already converted any [svg file into a png](https://github.com/mozilla/addons-server/blob/f7db392878567b7332f362534c90fc7ca84c5ca1/src/olympia/amo/utils.py#L632:L642) by that point so we're only dealing with a jpeg or png file.

**Comment by diox** [comment]
QA: try uploading different sizes and format of images as add-on previews and see if resizing still works correctly.

**Comment by ioanarusiczki** [comment]
@diox Looks good to me, I don't see changes. I tried uploading addon - icons, screenshot and themes using the wizard or an .xpi

Verified on AMO dev - FF101(Win10).
