### ISSUE TITLE
Different blue for linkage on the Featured Extensions pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1868]
See screenshot - again I'm not sure if this is intended as contrast to the side-bar colours.

![featured_extensions____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13638401/05de02b6-e604-11e5-9c5f-b263865e2080.png)

See https://addons-dev.allizom.org/en-US/firefox/extensions/?sort=featured

**Comment by tofumatt** [comment]
@designakt @pwalm Is this intended or should I unfiy these to be using the same colour?

**Comment by tofumatt** [comment]
I'm going to unify these.

**Comment by designakt** [comment]
@tofumatt thanks. Unifying is perfect.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-08_1138](https://cloud.githubusercontent.com/assets/15685960/14378613/8f5b34a0-fd7e-11e5-91c3-da5cb0a948f9.png)

**Comment by ValentinaPC** [comment]
@muffinresearch : What should we do if in Statistics Dashboard links have different colors, open another issue?
Please see the screenshot: 
![2016-04-08_1218](https://cloud.githubusercontent.com/assets/15685960/14379760/5aa727c2-fd84-11e5-9ef9-bc625fe847c5.png)

**Comment by muffinresearch** [comment]
> What should we do if in Statistics Dashboard links have different colors, open another issue?

Yep that should be a new issue.
