### ISSUE TITLE
Add a 'Go to My Submissions' button in the request confirmation page for site-permission addons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#18684]
### Describe the problem and steps to reproduce it:
1. Request a new site-permission add-on through the [devhub request from](https://addons-dev.allizom.org/en-US/developers/site_permission_generator/)
2. Submit the request
3. Check the information present in the submission confirmation page

### What happened?
The page contains a confirmation message but there is no 'exit' button that would allow the user to navigate away from the page

### What did you expect to happen?
All other submission confirmation pages have a button that would allow users to navigate away from the page, like going to the Manage my Submissions page for example.

[site-permission request confirmation page]
![image](https://user-images.githubusercontent.com/31961530/150961284-15f72d89-94cd-4c46-b7af-1fe48f44c84e.png)

[unlisted add-on submission confirmation page]
![image](https://user-images.githubusercontent.com/31961530/150961261-60305422-9a0b-47ca-8a9e-d2e5a70c7d39.png)

**Comment by diox** [comment]
I kinda did this on purpose :) I didn't want the developer to go to `My Submissions` right away, because the add-on is generated asynchronously, so if they go to that page too early they potentially wouldn't see the add-on (it should only take a few seconds to generate, but if we're dealing with a bunch of other things at the same time it could take a little more time).

**Comment by AlexandraMoga** [comment]
Hm, that is a good point, although the current confirmation page is not the best example of user experience.  However, landing on the Manage my Submissions page and not seeing the add-on that was just submitted could turn out to be the worse experience in the end. 

Maybe we could add some additional message on the confirmation page to let the users know that they should refresh the Manage submissions page after a few seconds if their add-on doesn't appear in the list? :shrug:

**Comment by diox** [comment]
We could, but low priority for now

**Comment by diox** [comment]
Site permissions will be removed from AMO in https://github.com/mozilla/addons-server/issues/19771.
