### ISSUE TITLE
404 needs an update

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1869]
Sidebar looks out of place next to the other refresh styling.

![not_found](https://cloud.githubusercontent.com/assets/1514/13638924/57767782-e606-11e5-98dc-6ad0fe3dab3e.png)

**Comment by tofumatt** [comment]
Forgive my cluelessness, but how do I get a 404 error easily while developing? I end up with 400 errors when setting `Debug = False`, and otherwise don't get 404s.

**Comment by andymckay-limited-access** [comment]
You are hitting an error on ALLOWED_HOSTS. Adding:

```
DEBUG=False
DEBUG_PROPAGATE_EXCEPTIONS=False
ALLOWED_HOSTS=['*']
```

To your local_settings.py should get you a 404 page.

**Comment by tofumatt** [comment]
Ah, cheers! I’ll give that a go and then get on the fix ^_^

**Comment by ValentinaPC** [comment]
Still not "in line with other pages".
Verified on AMO-dev FF45(Win 7)
Please see the screenshot: 
![2016-04-07_1005](https://cloud.githubusercontent.com/assets/15685960/14343299/a2dc468a-fca8-11e5-8e18-31a522563716.png)

**Comment by tofumatt** [comment]
I think -dev is not updating. I'll mention it to ops.

**Comment by tofumatt** [comment]
Or -dev hasn’t finished deploying yet, maybe try again in twenty or so minutes ^_^

**Comment by ValentinaPC** [comment]
Unfortunately is the first case.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-07_1744](https://cloud.githubusercontent.com/assets/15685960/14355114/86b37826-fce8-11e5-8cba-b5bcf6e319a2.png)
