### ISSUE TITLE
Link contrast issues in the add-on pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1870]
See https://addons-dev.allizom.org/en-US/firefox/addon/copy-plain-text-2/?src=hp-dl-featured
![copy_plain_text_2____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13638995/a08a5074-e606-11e5-8812-68dff44491de.png)

**Comment by tofumatt** [comment]
@pwalm What should these be changed to? Things like the text under "Enjoy this add-on?" might benefit from just a `text-decoration: underline;` and `#fff` colour. Dunno if that would work for anything else.

**Comment by pwalm** [comment]
I was thinking underline with #fff as well, that will look good.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screeshot: 
![2016-03-30_1156](https://cloud.githubusercontent.com/assets/15685960/14137030/8f300698-f66e-11e5-9ee2-0d83454889c2.png)

**Comment by 18961244441** [comment]
------------------320481198604053615




 




------------------ 原始邮件 ------------------
发件人: "ValentinaPC";<notifications@github.com>;
发送时间: 2016年3月30日(星期三) 下午4:57
收件人: "mozilla/addons-server"<addons-server@noreply.github.com>; 

主题: Re: [mozilla/addons-server] Link contrast issues in the add-on pages(#1870)



Verified as fixed on AMO-dev FF45(Win 7)
 Postfix screeshot:
