### ISSUE TITLE
Remove the reviewer name from /versions/

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18705]
As a followup for https://github.com/mozilla/addons-server/issues/18564#issuecomment-1023145346

The name of a reviewer is still visible for a developer into /versions/ when a reviewer asks for additional information, approves or rejects manually the version:

![reviewer name is visible](https://user-images.githubusercontent.com/33448286/151355544-46ac0cd4-ef27-4c68-a4f4-1514900a10e5.png)
![reviewer name](https://user-images.githubusercontent.com/33448286/151355548-e9266977-de92-4169-852b-0e893732d3b4.png)

Expected result:
should be anonymous

**Comment by bobsilverberg** [comment]
@ioanarusiczki For 2, above, are you sure the user you were logged in as isn't assigned some type of reviewer permission? I tested locally, and when I am signed in as just a developer the names are anonymized for me. Perhaps your test user has some type of review privileges? Even just the `ReviewerTools:View` permission will cause names to appear un-anonymized.

![Screen Shot 2022-01-27 at 1 13 42 PM](https://user-images.githubusercontent.com/142755/151419079-d1b75a04-f790-4b9d-929c-4cf625fde7ce.png)

**Comment by erosman** [comment]
I can also see the real names of the reviewers, but I am an add-on reviewer so I have extra privileges.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @erosman Yes, could be that I checked these on the admin profile and forgot I'm not on the developer's profile. I'll re-check to confirm this.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Even the developer account (that's what I thought) had some privileges in admin, so I removed them and there's " by Add-ons Review Team" instead of a name. 

I'm sorry for the inconvenience.  I'll close this. 

![this is not an issue](https://user-images.githubusercontent.com/33448286/151789373-793c3ad6-2677-42b3-ba44-8fc22b8a23c2.png)
