### ISSUE TITLE
Separators looks a bit severe on the details page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1871]
![copy_plain_text_2____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13639051/d43db096-e606-11e5-9ba3-c9af72e2efb6.png)

Note there's one that's a less bright blue - maybe if they all went in that direction it would stand-out less?

**Comment by tofumatt** [comment]
Ditching the separators entirely is probably the best solution here. I'll make a PR and attach screenshots.

**Comment by ValentinaPC** [comment]
The separators still exist, I suppose this is the intended form,  @tofumatt ?
Please see the screenshot: 
![2016-04-01_1104](https://cloud.githubusercontent.com/assets/15685960/14201356/061266ac-f7fa-11e5-9591-94aaf923bf78.png)

**Comment by tofumatt** [comment]
Yes, if you see the PR you can see the separators should still be there but are less thick/a softer colour. That screenshot is as intended.

- tofumatt

**Comment by ValentinaPC** [comment]
Next time I will also check the PR :+1:
