### ISSUE TITLE
Add actions that are performed by a site user to the show_user_to_developer allowlist

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#18717]
This is a follow-up to https://github.com/mozilla/addons-server/issues/18564, discussed at https://github.com/mozilla/addons-server/issues/17318#issuecomment-1024038429.

Actions that are performed by site users, as opposed to reviewers or admins, should have their user names exposed to developers in devhub. These actions include:
- ADD_TO_COLLECTION
- REMOVE_FROM_COLLECTION
- ADD_RATING
- EDIT_RATING

@wagnerand / @diox / @eviljeff Can you comment on these and their completeness?

**Comment by diox** [comment]
Those look good, but I think you're also still missing a few:
- MAX_APPVERSION_UPDATED
- DELETE_ADDON
- ENABLE_VERSION
- DISABLE_VERSION

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- as a developer I can see the name of the user who adds/removed my addon or adds/edits ratings for my addon. 
- the actions added by Mat above -> delete, enable, disable versions are actions taken by a developer and "MAX_APPVERSION_UPDATED" don't really know what it reffers to. But looking into the feed, the name of the developer is displayed for delete/disable/enable versions.  Did I get this right?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Sorry, MAX_APPVERSION_UPDATED can be done from the versions page and it is present on /feed
" Application max version for Version 1.0 updated. " by changethenameTEST
