### ISSUE TITLE
Review Tools: Reasons Select shouldn't show when approving

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#18716]
I have noticed that when approving an add-on (not _Confirm Approval_), the reason `select` appears which is not necessary.

![image](https://user-images.githubusercontent.com/6458876/151553558-c97ecf46-8f96-4df8-a1ca-9769f4a36614.png)

PS. Adding `resize` CSS to `select` `id="id_reasons"` would be useful when trying to find the right `option`.

**Comment by bobsilverberg** [comment]
This was a deliberate decision, or maybe I misinterpreted the requirement. @kewisch Can you comment on whether a reason should be required for "Approve" or not?

**Comment by erosman** [comment]
AFA I understood, the reason is meant for rejection & info request.

It does not make sense for approval since all the reasons are rejection related.

**Comment by wagnerand** [comment]
I believe this has been fixed in the meantime.
