### ISSUE TITLE
Themes' homepage header alignment/styling is different to Extensions' homepage

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1872]
See https://addons-dev.allizom.org/en-US/firefox/themes/ vs https://addons-dev.allizom.org/en-US/firefox/extensions/
Themes showing hover:

![themes____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13639188/7b13e8ea-e607-11e5-8748-f7283d0ae483.png)

Extensions (showing active nav + hover styling):

![featured_extensions____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13639200/9c3fcbba-e607-11e5-9351-0392462c33a5.png)

Note also the serif heading on Themes.

**Comment by tofumatt** [comment]
Fortunately the sidebar was fixed in #1889, but the header text and alignment still needs fixing, so I'll adjust this issue's title slightly :smile:

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-03-30_1202](https://cloud.githubusercontent.com/assets/15685960/14137184/62d9d262-f66f-11e5-978c-0cd91d453f0e.png)

**Comment by 18961244441** [comment]
------------------不要发了这个我不会，要么直接把所有账户和网络连接等等直接弄好，我不会




 




------------------ 原始邮件 ------------------
发件人: "ValentinaPC";<notifications@github.com>;
发送时间: 2016年3月30日(星期三) 下午5:03
收件人: "mozilla/addons-server"<addons-server@noreply.github.com>; 

主题: Re: [mozilla/addons-server] Themes' homepage header alignment/stylingis different to Extensions' homepage (#1872)



Verified as fixed on AMO-dev FF45(Win 7).
 Postfix screenshot:
