### ISSUE TITLE
More random blues on the collections page:

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1873]
See https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/web-dev-toolbox/

![web_dev_toolbox_-_ivan_krstic____collections____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13639306/1b60d77c-e608-11e5-9eea-73b6cac20dca.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-01_1100](https://cloud.githubusercontent.com/assets/15685960/14201226/1a9b55c6-f7f9-11e5-8df4-3ddc59f2dcd0.png)
