### ISSUE TITLE
Raise an explicit error (avoiding regular 404 html page) for obsolete API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18733]
We still have some clients hitting URLs like `/en-US/firefox/api/1.5/search/` which have been removed a long time ago (on services.addons.mozilla.org domain, since this is a Firefox request). We serve the generic HTML 404 for those, which can add unnecessary load (it handles auth if necessary, displays the site notice which causes a database request, etc).

We could consider making the generic 404 lighter, but specifically for this case, I think we should raise an explicit error early and don't even return HTML. We could also cache this for a long time, though I suspect clients would all come with different query parameters.

**Comment by diox** [comment]
We're also seeing requests to the legacy API 1.0, 1.1 or 1.2 so we should make sure to catch those as well.

**Comment by diox** [comment]
QA: `/{locale}/{app}/api/x.y/{anything}` URLs, where x and y are a single digit, should return a blank 404 page instead of the full HTML 404 page. 

Rest of the 404 on the site should not be affected and display an HTML page normally (and `/api/v{3,5,5}/...` 404s should continue to be in JSON, returning `{'detail': 'Not Found.'}`)

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and these are my results:

[Before fix - as seen in prod]
![image](https://user-images.githubusercontent.com/31961530/152166901-8d440fae-0156-45cf-8829-d85a7dff3ea7.png)

[After fix - obsolete API - page is cached for 172800 seconds]
![image](https://user-images.githubusercontent.com/31961530/152167053-43762ce7-c90f-402a-99ee-50b68c81bda8.png)

[After fix - `/v3/4/5/` APIs]
![image](https://user-images.githubusercontent.com/31961530/152167487-78f4de74-b064-4d09-9f78-9b0ac6305b5d.png)

@diox, just to be clear, this new 404 response should apply only to the `services` APIs, right? Also, the 404 response is returned for any request, valid or invalid.

**Comment by diox** [comment]
> @diox, just to be clear, this new 404 response should apply only to the services APIs, right?

It should apply to the main domain as well

> Also, the 404 response is returned for any request, valid or invalid.

Ugh what do you mean ? That doesn't seem right.

**Comment by diox** [comment]
https://services.addons.allizom.org/api/v4/addons/addon/619864/ for instance works correctly for me, not 404. But that's with the right api v4 prefix.

**Comment by diox** [comment]
Alright, that's all fine. 

I didn't expect the frontend 404 to be shown on the main domain, but I see why it's happening (the frontend is catching it, something that wouldn't happen on services domain which doesn't support any frontend pages), and as long as it doesn't happen on services domain, that's fine.

The 404 for a request that would be valid with the correct api prefix is expected.
