### ISSUE TITLE
Remove jquery-ui datepicker from statistics page

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18738]
As part of #18142: the extra datepicker displayed below the date inputs when selecting a custom range on the statistics page is redundant, we want to remove it to get rid of the extra dependency.

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev: 
![custom_daterange](https://user-images.githubusercontent.com/1583842/152782676-deeebe5e-5bb2-4fa9-90e7-2fea33b8e556.png)
