### ISSUE TITLE
Header not containing text

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1874]
See https://addons-dev.allizom.org/en-US/firefox/addon/fireftp/?src=hp-dl-featured

![fireftp____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13639364/542ce96a-e608-11e5-95d7-8db8b31a1856.png)

See the white on white text at just below the end of the blue header background.

**Comment by tofumatt** [comment]
@pwalm Are there any mocks for this? Not sure if there were and they weren't implemented properly or if we need some UX input for this bit.

**Comment by pwalm** [comment]
No mocks, let's just expand the blue area lower with 30px of padding from the text baseline.

**Comment by muffinresearch** [comment]
Hmm this one is going to be tricky. The background is a fixed height and not related to the content in terms of how the markup has been laid-out.

**Comment by pwalm** [comment]
Failing that, we could create a new block below to house the "Contribute" section. Maybe on a different shade of dark blue or grey.

**Comment by muffinresearch** [comment]
@pwalm yeah the current solution to the background is a bit of a hack so I think we'll probably find it easier to do a bit of a re-jig around the markup or some other creative approach. Background styling needs should be on a containing parent of the content otherwise it's bound to break like this.

**Comment by tofumatt** [comment]
@muffinresearch How do I get this locally? I can't seem to set up contributions locally.

If you could make my tofumatt@mozilla.com account an AMO admin on dev that might help; I can't enable the restyle for me there right now.

**Comment by muffinresearch** [comment]
The easiest way to do this is to hack it via the django admin for local-dev. You can simply enable contributions there bypassing the need for the API.

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/n7LEnSDHefv
