### ISSUE TITLE
stop adding the auth token to the api response 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18742]
We add the auth token to the api response during login, https://github.com/mozilla/addons-server/blob/master/src/olympia/accounts/views.py#L357
but
a) it's only set when there is a `data` attribute in the response (i.e. a JSON response, which we don't have any current code path to, afaik), and
b) it's not actually consumed by addons-frontend.

**Comment by eviljeff** [comment]
> Note that it's also mentioned in [the docs](https://addons-server.readthedocs.io/en/latest/topics/api/auth_internal.html):
> 
> > For the endpoint mentioned above, as a property called `token`.

yeah, I'll likely do #18743 at the same time.

**Comment by AlexandraMoga** [comment]
@eviljeff I'm not sure where the auth token was supposed to be seen during login. Should the login process start from a specific page?

**Comment by eviljeff** [comment]
@AlexandraMoga it was only exposed if was a JSON request to `/api/auth/authenticate-callback/`; but that url is only called by FxA that never made a JSON request. If the login/auth flow still works I think we'd good here.

**Comment by AlexandraMoga** [comment]
We've been verifying the login process in frontend, devhub, revtools and code manager and there were no issues found.

I'm marking this as verified fixed on -dev.
