### ISSUE TITLE
document new internal authentication methods

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18743]
Our API docs detail how to use the existing internal auth methods, but not the new session ID based authentication added in #18149.

**Comment by AlexandraMoga** [comment]
I've verified the new `Authorization: Session 1234567890`  method on -dev with several endpoints that require authentication (i.e. viewing user profile details, posting abuse reports, creating collections, submitting add-ons etc) and the this seems to function as expected.

I've checked this for the `/v5/`, `/v4/` and `/v3/` API versions and also for the `services` domain. 

The former `Authorization: Bearer {frontend_auth_token}` is still supported.
