### ISSUE TITLE
Cramped "Manage" button

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#1875]
See https://addons-dev.allizom.org/en-US/firefox/addon/fireftp/?src=hp-dl-featured

![fireftp____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/13639432/9f5be62a-e608-11e5-86cb-3bd93648a34d.png)

Needs more white-space around the manage button.

**Comment by tsl143** [comment]
hi there,
I am unable to get the current layout (as in screenshot)
![screenshot from 2016-03-19 15 45 05](https://cloud.githubusercontent.com/assets/5318732/13898095/6a744898-eded-11e5-8ced-a4794d52103d.png)

**Comment by tofumatt** [comment]
It's behind a waffle flag named "restyle" that needs to be enabled to see
the restyle. If you need help enabling that locally just let me know 😀
- tofumatt

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-01_1051](https://cloud.githubusercontent.com/assets/15685960/14201147/a500b180-f7f8-11e5-8efc-7c3ed2d40f4a.png)
