### ISSUE TITLE
Same web-extension can be installed on FF44 and cannot on FF45

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1876]
Steps to reproduce:
1. Sign in to AMO-stage with an admin account https://addons.allizom.org/en-US/
2. Submit attached web-extension and approve it 
3. Go to public pages and try to install the webextension using FF45 (https://addons.allizom.org/en-US/firefox/addon/icloud-test/)

Expected results:
The web-extension is installed with success.

Actual results:
The web-extensions cannot be installed.

Notes/Issues:
The submitted web-extension can be installed without any problems using FF44. 
Other web-extension can be installed on both firefox versions.
Verified on FF45(Win 7).
Screenshot for this issue: 
![2016-03-09_1921](https://cloud.githubusercontent.com/assets/15685960/13645153/3ae6fafc-e632-11e5-8487-83ce8a0a427b.png)

Attaching the web-extension that I've used.
[iCloud-Bookmarks_v1.4.20.zip](https://github.com/mozilla/addons-server/files/165774/iCloud-Bookmarks_v1.4.20.zip)

**Comment by jasonthomas** [comment]
As far as I can tell the sha256 hashes match and both add-ons (Windows and Mac version) are signed with the "test" certificate. Possible issue with the add-on itself?

**Comment by ValentinaPC** [comment]
If the same add-on can be installed with success on other version of Firefox (FF44), maybe is not entirely an add-on issue.
If I'll encounter the same issue with another web-extension, I will add it here.
Thanks!

**Comment by EnTeQuAk** [comment]
If this isn't neccessarily an AMO related issue, can we close this?

**Comment by andymckay** [comment]
Agreed.
