### ISSUE TITLE
Developer Blog import cron is failing

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18763]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/17705281/?referrer=github_plugin

```
TypeError: unhashable type: 'slice'
(2 additional frame(s) were not displayed)
...
  File "django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "olympia/amo/management/commands/cron.py", line 52, in handle
    getattr(module, name)(*args, **kwargs)
  File "olympia/devhub/cron.py", line 23, in update_blog_posts
    for item in items[:5]:
```

The actual issue is a 401 on the wordpress API though:
`GET https://blog.mozilla.org/addons/wp-json/wp/v2/posts [401]`

**Comment by eviljeff** [comment]
ironically, we only switched to use the json endpoint [6 months ago](https://github.com/mozilla/addons-server/issues/16724)

**Comment by diox** [comment]
Worth noting that this import code is fairly dumb: it checks that the response is json, if it is, deletes all existing blog posts before re-creating ones for the 5 last entries.

Couple issues with that approach:
- It never never checks the `status_code` of the response, we currently end up deleting the blog posts before that exception is raised. As a result, right now in production the developer news section in devhub sidebar is empty...
- It constantly re-creates posts it just deleted instead of checking for whether they are new or whatever...

**Comment by eviljeff** [comment]
Btw, I enquired internally about why this broke and was told the endpoint was disabled a few weeks ago for all blog.mozilla.org blogs, but was then re-enabled because it turned out the API was used by more teams than expected.

**Comment by eviljeff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1750739 for the background on why it was disabled (security bug; I've not read it myself)

**Comment by AlexandraMoga** [comment]
The Developer News section is populated with articles now:

![image](https://user-images.githubusercontent.com/31961530/154035950-a0fdea82-bf37-43e9-adef-1a5f3294c93a.png)

This issue is verified fixed on -dev.
