### ISSUE TITLE
Fix timestamp parsing with fxa webhook events

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18770]
For some fxa webhook events a `changeTime` property is sent in the payload https://github.com/mozilla/fxa/blob/main/packages/fxa-event-broker/README.md#example-password-change-event and we use that as the timestamp for the event (rather than `datetime.now()`).  Unfortunately it's not a unix timestamp (like the `iat` property), but a timestamp * 1000 - i.e. in millseconds rather than seconds, so python fails to parse it and raises an exception.  The exception is caught and logged as `year 54065 is out of range`

**Comment by eviljeff** [comment]
the last part of https://github.com/mozilla/addons-server/issues/14730#issuecomment-1029975913 - this fixes password changes/resets

**Comment by AlexandraMoga** [comment]
@eviljeff this seems to be working as expected now.

Change password in FxA:

when returning to the AMO page after having changed my password in FxA I still appear logged in, but when I refresh the page the UI also changes to confirm that I've been logged out from AMO; if I was logged in on a separate browser before changing the password, I'll be logged out from there as well and asked to provide the new password when I'm trying to log back in;
Reset password:

if I'm logged in two different browsers, once I'm resetting the password in browser 1 and then refresh the AMO page opened in browser 2 I'm being logged out; when I attempt to login again, I'm asked to provide my password.
