### ISSUE TITLE
Firefox extensions upload error 

### ISSUE THREAD

**Issue by jonesprg** [mozilla/addons-server#18783]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
When upload zip file of my firefox extension this error shown:
"Your add-on failed validation with 1 error.
    Received an empty response from the server; status: 502"
### What happened?
I don't know.

### What did you expect to happen?
My extension works correctly in developer mode but this error in uploading to firefox developer hub shown to me. please help!

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
[sida_firefox_extension.zip](https://github.com/mozilla/addons-server/files/8021650/sida_firefox_extension.zip)

**Comment by diox** [comment]
Apologies for not noticing this issue before - I've just tried and uploading this extension seems to be working now.
