### ISSUE TITLE
Developer hub "Manage my submissions" page is broken for "My Themes"

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#18793]
Steps to reproduce:
1. Be sure that you have some themes submitted in AMO-dev
2. Go to https://addons-dev.allizom.org/en-US/developers/themes
3. Observe the list of submitted themes

Expected results:
No layout issues 

Actual results:
Theme image is overlapping the theme info section

NOTES:
Not reproducible on Stage
Regression from https://github.com/mozilla/addons-server/issues/18760

Please see the screenshot for this issue:
![themes](https://user-images.githubusercontent.com/1583842/152995933-5a0b5d4e-7e87-41d7-9dfb-3166c8ac06de.png)

**Comment by diox** [comment]
Ah, I noticed some RTL breakage but not that one. I will fix it at the same time.

**Comment by vcarciu** [comment]
@diox : probaly with same root cause, we have a problems with text fitting for 
![difflanguages](https://user-images.githubusercontent.com/1583842/153006676-a79abd9b-bd11-45e3-8bc8-ae03f657aa47.png)
addons submission button in AMO-dev:

**Comment by vcarciu** [comment]
Verified as fixed :
![postfixthemes_buttons](https://user-images.githubusercontent.com/1583842/153022081-e82f91db-10a5-4fe9-a0b8-899787ca88b3.png)

![postfixRTL](https://user-images.githubusercontent.com/1583842/153022119-e5bbfee9-9275-4d5e-8802-b1484718e414.png)

NOTES: We also verified many languages where long strings were present and also multiple RTL languages
