### ISSUE TITLE
Can't reply to a review after deleting previous reply

### ISSUE THREAD

**Issue by folz** [mozilla/addons-server#1879]
This bug was originally posted to https://bugzilla.mozilla.org/show_bug.cgi?id=1161920, where two others have had the same issue.

Steps to reproduce:

I replied to https://addons.mozilla.org/en-US/firefox/addon/reaction-packs-for-facebook/reviews/784029/reply. Some hours later I deleted my reply and wanted to write a new one.

Actual results:

After submit, the following page is displayed and the answer is not saved:

> "Oops! We had an error.
> We'll get to fixing that soon.
> You can try refreshing the page, or head back to the Add-ons homepage."

Expected results:

The answer should be saved and made viewable to the public.

**Comment by shell15** [comment]
needs a dev to check in century for exception investigation.

**Comment by diox** [comment]
This should have been fixed some time ago, I believe in https://github.com/mozilla/addons-server/commit/188b5099789d6bbc1463a8eccedfe67dd1ffb061

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7)
Postfix video:
![reply](https://user-images.githubusercontent.com/15685960/28774136-ee1ef248-75f4-11e7-8acd-0d1dc4f8cfd9.gif)
