### ISSUE TITLE
Remove impala templates

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18792]
Few traces of the legacy "impala" templates remain, they should get removed to limit duplication, reducing confusion and maintenance cost.

**Comment by diox** [comment]
QA: Check that DevHub, Review Tools and Statistics pages work correctly. Statistics page should have a different header (making it more part of DevHub) and a slightly tweaked sidebar.

**Comment by ioanarusiczki** [comment]
@diox 

I did not find issues on Rev Tools - release testing will cover this again on -stage but as functionality I did not find broken actions. 
Stats have a new header, looks good and links redirect accordingly, I don't see other functional or visual issues.

Currently the dev hub addon validations seems to be broken , yesterday worked just fine so I don't think it's related to this issue.

**Comment by ioanarusiczki** [comment]
@diox Wow, yes, but this seems to me to be very recent. I tested around in dev hub and I did not have this error.

**Comment by ioanarusiczki** [comment]
@diox Verified on AMO dev and stage - FF97(Win10).
