### ISSUE TITLE
Static page for Firefox shield

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1880]
We need to get a static page up for Firefox shield. This will be similar to pages we've done for various other projects in the past, and is essentially a way to get around the "this add-on isn't on AMO" warning in the install flow.

@MattGrimes is going to supply the HTML for the page, but we just need to make sure its routed correctly in our URLs so it shows up at addons.mozilla.org.

Hoping to push this out next week. @EnTeQuAk can you assist on this please?

**Comment by EnTeQuAk** [comment]
Will do, as discussed on IRC the URL will be something like `/pages/firefox-shied/` unless there are other requirements.

**Comment by gregglind** [comment]
(We are also pursuing other solutions.  My (as lead) current thinking is:

- public AMO addon
- "quiet" page hosted on self-repair.

P4 this for the moment :)  The design and plan will get used for REAL in a month or two :)

**Comment by andymckay** [comment]
Chatting to @MattGrimes it seemed to be more urgent. But just to let you know our tag is Tuesday for a push on Thursday and all of us are at a work week next week in case people are responding slower.
