### ISSUE TITLE
Selecting a language from the language picker in devhub/revtools page footer doesn't change the page language

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#18817]
### Describe the problem and steps to reproduce it:
1. Log into the Developer Hub
2. Go to Manage my submissions page (or any other page that uses the same footer components)
3. Select a new language from the language picker in the page footer

### What happened?
The language can be selected but this doesn't trigger a page refresh for the new language to be applied

### What did you expect to happen?
Selecting a new language should trigger a page refresh and that language should be applied

### Anything else we should know?
The issue reproduces in all the pages that use the same language picker component - so devhub, revtools, statistics 
Doesn't reproduce on stage - so this is a new regression. 

![firefox_tJnSjCq9aa](https://user-images.githubusercontent.com/31961530/153596070-d66ec7de-0b47-43f6-88fd-1dc711b70625.gif)

**Comment by diox** [comment]
I'm guessing this is a regression from the recent devhub template & javascript cleanup I made.

**Comment by AlexandraMoga** [comment]
> I'm guessing this is a regression from the recent devhub template & javascript cleanup I made.

Yes, sorry. I forgot to mention that this reproduces only on -dev, so it's a new regression.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/commit/97f9d82cbc655e7f7ed7aafb95ba6d040187cc99 is confirmed as the culprit from bisecting.

Note that devhub "landing page", logged in or not, works, not not the pages inside devhub or rest of addons-server.

**Comment by diox** [comment]
`js/amo2009/addons.js` contained the code responsible for this and is no longer part of the bundle. Amusingly, I had forgotten to remove it (as well as `js/amo2009/global.js`).

We already had duplicated the relevant bits into `js/common/lang_switcher.js` which is used in the `devhub/new-landing/js` bundle, so I think all we need to do is move it to the `common` bundle (or, if the devhub new landing page does not include the `common` bundle, copy it instead).

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on stage:

![firefox_Jm0TnCcxI3](https://user-images.githubusercontent.com/31961530/154240332-59945fba-8b65-4144-b9a7-666a9e240afd.gif)
