### ISSUE TITLE
drop `UserLog` model/table

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18811]
Our `ActivityLog` model includes a number of models that, in theory, lead to simpler code/queries when referencing a subset of those activity logs.  One of these models is `UserLog` which links `UserProfile`s to the activity log records (we have others such as `AddonLog`, `GroupLog`, etc.).  A `UserLog` instance is created for the user who created the `ActivityLog`; and in the case of an ActivityLog that is related to a `UserProfile`, another one is created for that.

But it's only actually used in one place for calculating [`last_known_activity_time`](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/admin.py#L468) - and we can calculate that directly from `ActivityLog` instead.

**Comment by AlexandraMoga** [comment]
@eviljeff I had a look through the [Admin activity logs](https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/) on stage for several user actions (submitting addons, posting ratings, editing collections, reviewer actions) and activity logs were recorded. 

Was there something else that needed to be tested for this issue?

**Comment by eviljeff** [comment]
@AlexandraMoga we used `UserLog` to display `last_known_activity_time` in the UserProfile admin pages - just check it's still working (should be the last datetime any activity log was created by them)

**Comment by AlexandraMoga** [comment]
The `last_known_activity_time` is updated when a user makes an action (linked to an activity log) on the site:

![image](https://user-images.githubusercontent.com/31961530/154507094-cb801a2a-48f4-4c02-b61d-522fc2666a95.png)
