### ISSUE TITLE
turn on setting VERIFY_FXA_ACCESS_TOKEN on stage & prod

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18828]
Once #18754 is validated on addons-dev we can turn checking access token validity on stage (and prod - could be in subsequent weeks if we wanted to be extra careful)

**Comment by eviljeff** [comment]
@ioanarusiczki do you think #18754 is sufficiently validated for us to move forward in enabling on stage&prod?

**Comment by ioanarusiczki** [comment]
@eviljeff Do you want to enable it this week? I did not see the comment until today, sorry.

**Comment by ioanarusiczki** [comment]
P.S. @eviljeff If that's already on stage , let me know because I should prepare some accounts to test it and then wait for 12h

**Comment by eviljeff** [comment]
@ioanarusiczki it's not enabled on stage yet, I wasn't sure if it was okay on addons-dev.  If we need a 12 hour wait it might be a bit rushed to validate for stage now so I'll push a tag to stage after the prod deploy so there's all week.

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, sounds good to me. I'll have time to test it until next week's push 👍

**Comment by eviljeff** [comment]
This has been deployed to stage now, ahead of the usual push.

**Comment by ioanarusiczki** [comment]
@eviljeff Thanks, I've noticed it, I'll get things ready.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified with some accounts on AMO Stage: 
- the frontend and dev hub behave as expected (described into https://github.com/mozilla/addons-server/issues/18754#issuecomment-1042667323)
- code manager -> now if I try and browse I get a 401:

![code manager login fails](https://user-images.githubusercontent.com/33448286/155959347-a49b4191-06de-412d-832d-99d10d8ccb26.gif)

- I don't know what is the expected behavior for admin tools but I've noticed that I was not logged out.

**Comment by eviljeff** [comment]
@ioanarusiczki does code manager work after refreshing the page?  (I suspect there may never have been support added for expiring sessions in code manager)

**Comment by ioanarusiczki** [comment]
@eviljeff If I refresh the page I am in log out view, I can login and then browse again without having problems.

**Comment by eviljeff** [comment]
> @eviljeff If I refresh the page I am in log out view, I can login and then browse again without having problems.

I'll file an issue to add support for expiring sessions in code-manager.  (tbh I'm not sure if it'll get implemented given the user base)
