### ISSUE TITLE
Link to site permissions add-ons documentation from generator

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#18827]
The site permissions add-ons generator should link to documentation on how they work from a developer perspective. The URL will be https://extensionworkshop.com/documentation/publish/site-permission-add-on/

/cc @diox

**Comment by diox** [comment]
Template: https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/site_permission_generator.html
URL of the generator: /en-US/developers/site_permission_generator/ (or any other locale)

@kewisch any idea what we could use in terms of copy and where to add the link to the page ?

**Comment by diox** [comment]
Site permissions will be removed from AMO in #19771.
