### ISSUE TITLE
create db migration to drop UserLog model table

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18838]
run make_migrations to get the migration to drop the table for UserLog

follow-up for #18811 - to be merged in a subsequent milestone.

will resolve https://sentry.prod.mozaws.net/operations/olympia-prod/issues/18302183/

**Comment by ratika-12** [comment]
I want to work on this. please assign me.

**Comment by eviljeff** [comment]
@ratika-12 please go ahead.  We will assign you once we've merged your pull request.

**Comment by eviljeff** [comment]
Note, we need this to land in our next milestone - so be ready by 2021/02/22.

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa. 
Thanks!
