### ISSUE TITLE
Example links from manage payments page are not working

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#1883]
**Steps to reproduce:**
1. Open manage payments page for an add-on that has payments set up i.e: https://addons.allizom.org/en-US/developers/addon/adblock-plus/payments
2. Scroll down to "When should users be asked for contributions?" section and click on one of the "example" links.

**Expected results:**
The example page/image is displayed.

**Actual results:**
Nothing happens.

**Notes/Issues:**
Verified in FF45(Win7) Issue can be reproduced in -dev and stage.
Screencast for this issue: http://screencast.com/t/9R5vjHIZ

**Comment by muffinresearch** [comment]
Does it work in production?

**Comment by madalincm** [comment]
I can't test this in production as I do not have an account with permission in there. Contribution can be set to only fully reviewed add-ons.

**Comment by andymckay** [comment]
I've got one, so through together a quick fix ^

**Comment by madalincm** [comment]
Verified in FF45(Win7) in addons-dev.allizom.org
The screenshots are displayed correctly but they look a bit outdated. Shouldn't we change them with something more actual? http://screencast.com/t/oNzaczxiW7pl
