### ISSUE TITLE
Serve xpis from addons-server through `X-Accel-Redirect`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18844]
Currently, and since pretty much forever, `.xpi` downloads go through the following process:
1) `GET https://addons.mozilla.org/firefox/downloads/file/{file_id}/{filename}`
  That request is handled by addons-server. It considers authentication & permissions, and is not cached. It redirects to...
2) `GET https://addons.cdn.mozilla.net/user-media/addons/{addon_id}/{filename}?filehash={hash}`
  That request is handled by nginx from EFS directly, bypassing addons-server. It does not consider authentication & permissions, and is cached for 24 hours.

That second URL depends on nginx having some configuration to directly serve the file from where it's stored on EFS. The idea behind it is to avoid hitting addons-server, for perf/scalability concerns.

Because of this process, the whole `guarded-addons` concept was invented back in the day, where deleted/disabled files are moved away from the normal place where files are stored, to prevent nginx from being able to serve them. This forces us to maintain 2 directory structures, and move files around when deleting/disabling, which in turn is responsible for a number of quirks/bugs where files are not always at the right place at the right time, and awful cronjobs regularly go through our files to resume any move that failed.

Ahead of the migration to GCP, we want to move away from this architecture to make file storage simpler to change. The idea would be to:
- No longer move files to `guarded-addons/`
- Replace the step 2) in the process above: Instead of serving the file by nginx from EFS, we would go through addons-server, do a database request, determine whether the file can be served (is not disabled/deleted/etc), and let nginx serve the `.xpi` with `X-Accel-Redirect`.

We might completely remove the step 2) and just do everything in the first response (avoiding the redirect) later, but I am not sure we want to do this now yet. Note that the update endpoint that serves add-on updates to Firefox clients directly links to the URL from step 2).

Hidden benefit: currently the URL directly maps to the path on the filesystem. We'll want to change the directory structure in https://github.com/mozilla/addons-server/issues/11510 so this would help.

**Comment by diox** [comment]
Internal discussion that lead to this: https://docs.google.com/document/d/1fn-C0nl5wFAur4yEsPiEoXAKznAxl4u1TGcvaqLD_N4/edit#heading=h.xw8tkh2brgaf

We noticed that the perf/scalability concerns are alleviated by the high cache hit ratio on the CDN. Hitting addons-server might cost us a bit but we should be able to take that hit (even more so if we eventually get rid of the step 2) entirely - we already have an uncached request that goes through addons-server in many cases!)

**Comment by diox** [comment]
Implementation plan would look something like this:
- Keep step 1) for now. Getting rid of it is not in scope for this, it brings too many complications since it handles auth. We might want to add light caching to it though.
- Keep moving files to `guarded-addons/` initially, focusing on replacing step 2) first.
- Build endpoint for step 2) in addons-server, and CDN configuration allowing it to work on the main domain (replicate caching config, it should only vary on geolocation headers)
- Deploy, replacing step 2) with new implementation
- Let it live for a bit
- Have https://addons.cdn.mozilla.net/user-media/ redirect to new step 2) implementation. Likely going to be the same URL with the domain changed to the main domain
- Stop moving files to `guarded-addons/`
- Remove old nginx config

**Comment by diox** [comment]
> We might completely remove the step 2) and just do everything in the first response (avoiding the redirect) later, but I am not sure we want to do this now yet. Note that the update endpoint that serves add-on updates to Firefox clients directly links to the URL from step 2).

Digging into this a bit more: the main benefit of having those 2 endpoints for us is ensuring that downloads coming from the update service are not causing scalability and performance issues - because the update service directly links to the second endpoint.

If we can ensure a good cache hit ratio on the CDN for the first endpoint, we can probably stop using the second endpoint now instead of trying to re-implement it in addons-server. We would keep the second endpoint for now, and eventually decommission it entirely. The main benefits would be:

- No need to re-implement the second endpoint in addons-server, which is good because:
  - It's a pain to be compatible with the URL scheme used - the file id isn't present, only the addon id and the filename, requiring new indexes in the database
  - Less code in addons-server
  - Less nginx config to deal with
- Simpler setup without the redirect

**Comment by diox** [comment]
QA:
- Installing an add-on from frontend pages should still work. 
  - When inspecting network requests, you should see a direct download from the main AMO domain instead of a redirect to a domain with `cdn` in its name.
  -  When inspecting network requests you should see the URL is cacheable for 24 hours
- Downloading an add-on from reviewer tools and devhub should still work.
  - Same as above, there should not be a redirect and there should be caching headers set.
  - Rules for private downloads should still apply, namely:
    - Impossible for a non-authenticated or non-author, non-reviewer to download a file disabled by developer, but possible otherwise (bypassing georestrictions)
    - Impossible for non-authenticated or non-author, non-unlisted reviewer to download an unlisted file, but possible otherwise (bypassing georestrictions).
    - Impossible for non-reviewer to download a mozilla disabled/delete file, or file belonging to a disabled/deleted add-on, but possible otherwise (bypassing georestrictions)

In addition, try to trigger caching by repeating the scenarios a couple times and looking if it breaks any of the assumptions above. For instance, it should be ok for a file to be served from cache in all scenarios (`X-cache: hit from cloudfront` in response headers) but it should never allow a private download to be accessible to the general public.

**Comment by ioanarusiczki** [comment]
@diox 
Results on AMO dev with FF98(Win10):
- when installing an addon there’s a 200 request to `addons-dev.allizom.org` there's no `cdn`, X-cache `Hit from cloudfront` with `cache-control max-age=86400`

- Dev hub/rev tools will trigger downloads. A dev hub URL opened in a new tab https://addons-dev.allizom.org/firefox/downloads/file/414460/rename-4-an+fx.xpi triggers an install. A rev tools url https://addons-dev.allizom.org/firefox/downloads/file/414460/type:attachment/rename-4-an+fx.xpi triggers a local download. In both cases there’s a single request to `addons-dev.allizom.org` with X-cache `Hit from cloudfront` and `cache-control max-age=86400`

- When an addon version  is disabled by the developer -> the developer, other authors, reviewers can access the URLs mentioned above (even if the addons was geo-restricted). Non-authenticated or other users don’t have access to such downloads. 

- An unlisted file can be accessed by the developer, other authors, reviewers (bypassing geo-restrictions), it cannot be downloaded by other users or non-authenticated. 

- Disabled by Mozilla files (rejected, blocked) -> can be accessed by who submitted the file, other owners and reviewers (bypassing geo-restrictions), deleted files can be accessed by reviewers from the review page (bypassing geo-restrictions). 
- The update service is working, I’ve noticed the domain is still `addons-dev-allizom-org`, the request is visible if I use the browser toolbox. 

- After testing for 2 days around this issue, the urls always had `X-cache: hit from cloudfront`, cacheable for 24 hours.

I tried to make the testing summary as short as possible. I think the behavior is fine.

**Comment by ioanarusiczki** [comment]
@diox 

To respond to your question, I should have detailed that in case the file is not public (or not accessed by the group of privileged accounts) for example I can trigger an install for a disabled add-on because I'm the owner/admin for 
https://addons-dev.allizom.org/firefox/downloads/file/414498/disabled_versions_by_developer-1.0.1.3-fx.xpi
If I am not authenticated or I try it with another developer account which is not added as owner I will hit 404 Not Found
X-Cache:Error from cloudfront and max-age=86400

![404](https://user-images.githubusercontent.com/33448286/159653577-67298682-e9cf-4935-b651-be0a81433b59.png)

**Comment by diox** [comment]
For future archeologists : we discussed this on Matrix, you can build a custom android build that allows stage add-ons to be installed through [these instructions](https://addons-frontend.readthedocs.io/en/latest/fenix/) - that's how @ioanarusiczki was able to verify.
