### ISSUE TITLE
remove WebTokenAuthentication support

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18854]
#18475 added a new internal authentication method, and once frontend (https://github.com/mozilla/addons-frontend/issues/11110) and code-manager (https://github.com/mozilla/addons-code-manager/issues/2156) support it we can remove it as a method of authentication, and stop generating the `frontend_auth_token` token during login.  

There are no other supported webapps that use this internal method of authentication (we provide JWT auth keys for external developers to use); any other random tool that uses the method can switch easily to use SessionIDAuthenticatoin.

**Comment by diox** [comment]
Need to double-check with ops if still have config bits relying on frontend_auth_token. (If they do, it might be obsolete: for instance, I don't think we shouldn't do nginx caching anymore now that we have the CDN in front of us)

**Comment by eviljeff** [comment]
there's https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/addons-proxy/ansible/templates/olympia2g_resources.yml#L165 - cc @bqbn

**Comment by diox** [comment]
I'm more worried about this:
https://github.com/mozilla-services/cloudops-deployment/blob/7b738cfdfb5cb87cc6b1e3959d2b9c4420d75962/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L630-L640

Not sure if we can still hit this config path though...

**Comment by bqbn** [comment]
> there's https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/addons-proxy/ansible/templates/olympia2g_resources.yml#L165 - cc @bqbn

Thank you for letting me know. Please ping me when it is ready to remove the above line of config.

**Comment by bqbn** [comment]
> @bqbn The cookie is still set by addons-server (until this issue is closed, anyway) but it's no longer consumed by addons-frontend (as of 2 weeks ago), and addons-code-manager will stop consuming it this week. Both will only rely on the `sessionid` cookie. I guess that means it's ready to remove but I'm not completely familiar with what that config does.

@diox given what @eviljeff said, would it be OK to remove this line: https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/addons-proxy/ansible/templates/olympia2g_resources.yml#L165?

**Comment by diox** [comment]
It should be safe to do now since frontend no longer depends on this cookie, but to be 100% sure I'd wait until this issue is closed and hits prod - completely removing any handling of that cookie from our code.

**Comment by ioanarusiczki** [comment]
@eviljeff If I deleted the Session cookie from the Storage tab of the browser I see a new one being generated. The old or new one are both working.

**Comment by eviljeff** [comment]
> @eviljeff If I deleted the Session cookie from the Storage tab of the browser I see a new one being generated. The old or new one are both working.

The session cookie is still used (though it's of a different format), I meant the `frontend_auth_token` cookie specifically for frontend (sorry, should have been clearer)
