### ISSUE TITLE
Stop moving files to `guarded-addons/` and move files already there back to `files/`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18869]
Depends on https://github.com/mozilla/addons-server/issues/18844

Once the issue above is done, we'll have full control of permissions for accessing files through the database and we won't need to move disabled/deleted files any longer. We should then:
- Stop moving files to `guarded-addons/`, removing associated `hide_disabled_files` and `unhide_disabled_files` code.
- Move existing files in `guarded-addons/` back to `files/`

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/18998 is a prerequisite, because we don't want those files to accidentally be exposed to the outside world, so the old way of handling downloads needs to go away first.

**Comment by ioanarusiczki** [comment]
@diox I verified on -dev and I've been able to download some old/new disabled files from rev tools using different permissions (admin, addon reviewer, content reviewer, unlisted reviewer).
