### ISSUE TITLE
Move FileUpload storage to `shared_storage/uploads/fileuploads`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18871]
`FileUpload` files are stored in a `temp` directory under `files/` (where permanent add-ons are stored):

https://github.com/mozilla/addons-server/blob/1ac05a5454f04b0985d1b9b540ca3af601882276/src/olympia/files/models.py#L514-L516

This is a bit inconsistent with everything else: `files/` should only really contain permanent xpis (i.e. `File`). We already have a `/shared_storage/tmp/` path for really temporary stuff, and a bunch of other uploads are stored under `shared_storage/uploads/<directory>/`.

Since `FileUpload`s are short-lived but not quite as short-lived as other temporary files that are discarded right after uploads, I think we should use `shared_storage/uploads/fileuploads` instead.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-80)

**Comment by diox** [comment]
QA: uploading new add-ons/versions should still work

**Comment by ioanarusiczki** [comment]
@diox Addon submission on -stage is broken. 
On -dev is working.

**Comment by diox** [comment]
Wontfix, we'll re-open if we have a good reason to do it.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-80
