### ISSUE TITLE
Make sure AbuseReport.addon is unused and drop it

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#18879]
We used to link abuse reports to the add-on instance via `AbuseReport.addon`. For a while now, we have stopped doing that at least for abuse reports submitted from Firefox. Those are linked via `AbuseReport.guid`. We should make sure nothing else uses `addon` or migrate them to using `guid` (abuse reports from AMO possibly), then drop that field.

**Comment by diox** [comment]
We started relying on the `guid` instead of the `addon_id` in https://github.com/mozilla/addons-server/issues/17507 ; From that point forward all new add-on abuse reports should have the `guid` set. (We should double check against prod data though)

The challenge for the migration is, because of past guid re-use, I'm not sure we can know for certain which `guid` an abuse report made before that change was referring to. We have the `addon_id`, so the simple approach would be to make them use the corresponding `guid`, but that might have been a different one at the time of submission.

**Comment by wagnerand** [comment]
> but that might have been a different one at the time of submission.

Could you expand on that? Due to previously allowed re-usage of deleted GUIDs, we might have several `addon_id`s for one `guid`, but the other way around should be unique. For re-used GUIDs, it might actually be preferable to link to the latest existing add-on instance. It's not a perfect solution, but the current `guid`-based linking behaves similarly and then at least we are consistent. Also, we can see if we should expose abuse reports for all current and former add-ons of one ID together on the review page. But this is a problem we are having anyway and one that will only be relevant for past abuse reports since GUID re-usage is no longer possible.

**Comment by diox** [comment]
Mmm yeah I was thinking about this the other way around. I wonder if we still have a `guid` for older deleted add-ons though ? For recent enough ones we have the `addons_reusedguid` so we should be able to find the original `guid` even if it has been reused...

**Comment by wagnerand** [comment]
> I wonder if we still have a guid for older deleted add-ons though 

We might but for those, the new `addon_id` can be parsed from the old `guid`, because the format is `guid-reused-by-pk-<PK>`

**Comment by diox** [comment]
From discussion on Matrix: there are only a couple entries with an `addon_id` and no `guid` in the database. We should fix them in a data migration and drop the `addon` field from the model, and drop the column from the database in a following push.

**Comment by AlexandraMoga** [comment]
@diox do we need to follow some specific data to be verified after the migration is complete?

**Comment by diox** [comment]
I actually didn't do a migration in this one - there will be one in https://github.com/mozilla/addons-server/issues/19499

**Comment by AlexandraMoga** [comment]
Is there anything to verify for this one then?

**Comment by diox** [comment]
Just that we can still load abuse reports for a given add-on (behind the scenes it's now using the `guid`). You probably already verified that through the other issues that this fixed at the same time.

**Comment by diox** [comment]
mmmm, weird. Do note that depending on the env and browser frontend will not use the same mechanism to send the abuse report: on prod w/ Firefox, it uses internal Firefox APIs - I'm not sure if this applies to mobile as well.
