### ISSUE TITLE
Configure Sentry to filter out PII information

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18885]
We currently have a custom on premises Sentry, and we have configured the client to send full user information, through the `send_default_pii` key in `SENTRY_CONFIG` setting.

As we're moving to a SaaS external Sentry instance, we need to turn that option off to avoid sharing PII information with the outside world.

We do want to keep user IDs in the tracebacks for logged in users to help debugging however, so we might need to include it ourselves through before_send if `send_default_py=False` doesn't include that.

In addition, we should ensure we don't include PII in logging messages, even for exceptions.

**Comment by diox** [comment]
https://github.com/willkg/kent/ might be useful for local testing

**Comment by eviljeff** [comment]
Is there a list of the data we store/handle than could be regarded as PII?

**Comment by diox** [comment]
> Is there a list of the data we store/handle than could be regarded as PII?

I've asked, but I think that doesn't block us from deploying my PR

**Comment by eviljeff** [comment]
> > Is there a list of the data we store/handle than could be regarded as PII?
> 
> I've asked, but I think that doesn't block us from deploying my PR

You have a list: https://github.com/mozilla/addons-server/pull/18893/files#diff-9349f4d8607c31c4ec557e0f3fa841a30c2fcf98ceab6ed8c85e7b9d598833d3R1531 😛

**Comment by diox** [comment]
Yeah, that was my best guess by looking at a basic event
