### ISSUE TITLE
Change file structure for add-on git extractions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18896]
Each add-on is extracted and stored through git on EFS for reviewing purposes. The directory structure is: `/git-storage/<last addon_id digit>/<last 2 addon_id digits>/<addon_id>/`.

With only 2 intermediary levels of 10 possibilities each (the second level has 2 digits but one of them doesn't change for a given first level), the second level directories can have tens of thousands of subdirectories, which make listing them almost impossible.

We want to move to 3 intermediary levels, much like what we'll have to do for add-ons soon in https://github.com/mozilla/addons-server/issues/11510. The new structure should be:
`/git-storage/<last addon_id digit>/<last 2 addon_id digits>/<last 3 addon_id digits>/<addon_id>/`.

We'd want to avoid re-extracting all add-ons from scratch, so we should have a migration plan.

**Comment by diox** [comment]
Regarding the migration plan, we can cause temporary disruption, particularly if done outside Europe working hours. The data is only exposed to reviewers, not end-users.

So we can probably do something along the lines of:
- Create new directory structure ahead of time
- Stop the extraction of new uploads (add-ons and versions)
- Deploy new code with new structure
- Move all existing files to new locations
- Resume extraction with new code & new structure

**Comment by diox** [comment]
The function we're using to determine directory structure is https://github.com/mozilla/addons-server/blob/ca0495336f727fcfa293cb8d963df5b264466c38/src/olympia/files/utils.py#L85-L99

We're using it in a variety of places. Maybe keep it but introduce a new parameter dictating how deep we want the structure to be, and start using the parameter ? We'll eventually need to do a similar structure for add-ons storage as well...

**Comment by eviljeff** [comment]
> but introduce a new parameter dictating how deep we want the structure to be

as it's pretty harmless having a more sparsely populated structure than we really need, I'm tempted to say just work out what the most extreme structure we'd need is (probably add-ons) and use that for every type of file.

**Comment by diox** [comment]
In theory yes (As I mentioned, we'll eventually need a similar structure for add-ons storage), in practice... that would mean migrating all type of files the moment we change the behavior of this function: it's used to determine both the path we write to, but also the path we read from later on... In some cases the resulting path is stored in the database and not re-computed, but not always.

I don't want to migrate everything right now, so for backwards-compatibility, we have to either introduce a parameter (keeping the default behavior as it is now) or a completely new function, and gradually move things as they are being migrated. In my WIP branch I went for the parameter route.

**Comment by diox** [comment]
QA:
1. Check that add-ons are extracted correctly by ensuring the version contents are available in code-manager when a new version of an add-on (or a new add-on) is uploaded.
2. Then pick a few add-ons - ideally some old ones and newer ones - that you have verified are visible in code manager, and let me know - I'll trigger the migration process and flip the waffle switch enabling the new structure.
3. Once migration is done we'll want to check that the add-ons contents are still visible in code manager, as well as recheck 1.

**Comment by ioanarusiczki** [comment]
@diox 

1. New files were extracted
https://code.addons-dev.allizom.org/en-US/compare/621287/versions/1693712...1693713/
https://code.addons-dev.allizom.org/en-US/compare/621288/versions/1693714...1693715/
https://code.addons-dev.allizom.org/en-US/compare/621289/versions/1693716...1693717/

2. I've picked older files, my list is:
https://code.addons-dev.allizom.org/en-US/browse/495314/versions/1533807/
https://code.addons-dev.allizom.org/en-US/browse/495081/versions/1533341/
https://code.addons-dev.allizom.org/en-US/browse/495646/versions/1534090/
https://code.addons-dev.allizom.org/en-US/browse/616937/versions/1688361/
https://code.addons-dev.allizom.org/en-US/compare/616937/versions/1688360...1688361/
https://code.addons-dev.allizom.org/en-US/compare/616937/versions/1691757...1692695/
https://code.addons-dev.allizom.org/en-US/browse/492486/versions/1529211/
https://code.addons-dev.allizom.org/en-US/compare/492486/versions/1529211...1688395/

3. Ready for migration, please let me know when I can continue.

**Comment by diox** [comment]
Ran the migration and flipped the waffle switch.

**Comment by ioanarusiczki** [comment]
@diox 
- All files above are displayed.
- New submissions were extracted correctly. 

Verified on AMO dev. FF97(Win10).
