### ISSUE TITLE
Move sitemap files in subdirectories on filesystem

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18895]
Our sitemap is backed by XML files generated by a cron every day and stored on EFS. The files are all stored inside the same `sitemaps/` directory. That directory contains over 17K files in prod right now, which is making basic operations like `ls` difficult.

We need to update the code to spread the files in sub-directories, with each sub-directory ideally not containing more than 1000 files.

Changing the code in this way could break the sitemap temporarily if we deploy code using the files with the new structure while the files haven't been regenerated yet in the new location. Generating the full sitemap takes ~45 minutes in production, so we could simply accept a 45 minutes potential breakage and regenerate the sitemap right away after deploy, or be smarter about backwards-compatibility, depending on how easy it is.

**Comment by diox** [comment]
Note: if we want backwards-compatibility, we could create the new directory structure and make hard links between the old and new file locations. We wouldn't need to regenerate the sitemap right away after deploy that way.

**Comment by eviljeff** [comment]
I think some breakage is fine really - maybe just switch around the generation order in `write_sitemaps` so the new index gets written last?

**Comment by diox** [comment]
> I think some breakage is fine really - maybe just switch around the generation order in `write_sitemaps` so the new index gets written last?

We talked about this on Matrix but that wouldn't buy us much, it might even be worse: if the index is built first and then everything in order there might be less disruption.

**Comment by AlexandraMoga** [comment]
I've verified the the `sitemap.xml` on stage and I haven't found issues with the sections loading. I've also verified some random URLs from each section and they seem to work, i.e. a valid page will open if the URL is followed.

I'm marking this issue as verified fixed on stage.
