### ISSUE TITLE
Allow WebExtension to be signed with no add-on id

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1890]
The API for signing an add-on currently requires an id.

http://addons-server.readthedocs.org/en/latest/topics/api/signing.html#uploading-a-version

It would be really nice if it didn't, because then AMO could generate one for it. If an add-on hit that end point and it wasn't a WebExtension, it should just fail because not specifying the add-on id is a feature for WebExtensions only.

Tracker: mozilla/addons#61

**Comment by kumar303** [comment]
Since a lot of scripts exist against the current signing API (which has an extension ID in the URL path) we will probably need to keep that URL around for a while, maybe with a deprecation notice.

**Comment by andymckay** [comment]
We could just keep the ability to sign with an ID around so that people can explicitly refer to their add-on.

**Comment by EnTeQuAk** [comment]
Yeah, I don't think it hurts keeping the URL with an id alive, we'll have to do this for non WebExtensions either way afair so we'll just introduce a new endpoint I think.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
The web-extension without an ID are properly signed and can be installed as expected on FF49, but **not in FF46** and for this I've commented in https://bugzilla.mozilla.org/show_bug.cgi?id=1262005#c32

**Comment by EnTeQuAk** [comment]
@ValentinaPC I think this change landed for Firefox 48 so it's expected not to work in any version before that.

**Comment by ValentinaPC** [comment]
@EnTeQuAk: And what is expected to happen on Thursday when a user will try to install a web-extension on AMO-prod (that has a generated ID) and does not manage to do this?

**Comment by EnTeQuAk** [comment]
Hmm, good question, cc @andym on this. Imho developers just have to make
sure to set the correct version dependencies if they're using this
feature, not sure we can do much about it.
 
 
On Tue, May 10, 2016, at 03:55 PM, ValentinaPC wrote:
> @EnTeQuAk[1]: And what is expected to happen on Thursday when a user
> will try to install a web-extension on AMO-prod (that has a generated
> ID) and does not manage to do this?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[2]
>
 

Links:

  1. https://github.com/EnTeQuAk
  2. https://github.com/mozilla/addons-server/issues/1890#issuecomment-218164547

**Comment by EnTeQuAk** [comment]
damn, ment to cc @andymckay and mistyped the name.
