### ISSUE TITLE
remove sqs integration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#18914]
Now #14730 is closed and enabled on prod we can delete the now unused sqs integration

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if there's something to check by qa.

**Comment by eviljeff** [comment]
> @eviljeff Let me know if there's something to check by qa.

it should have been all dead code - the qa for https://github.com/mozilla/addons-server/issues/14730 would cover it

**Comment by ioanarusiczki** [comment]
@eviljeff Nothing unusual, all scenarios have the same behavior as mentioned into https://github.com/mozilla/addons-server/issues/14730
Verified on AMO dev - FF97(Win10).
