### ISSUE TITLE
If a WebExtension is submitted without an add-on id, create one

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1891]
Allow a WebExtension to be submitted without an add-on id. If it is, then lets create one and insert it into the mozilla.json file and save it inside the add-on.

This might mean altering an already existing file mozilla.json if one is submitted by a developer, so we can't just overwrite the whole file.

Tracker: mozilla/addons#61

**Comment by andymckay** [comment]
As per the updated spec, we aren't using mozilla.json. When an add-on is uploaded without an id, the id gets written into the AMO table and that's it. Much simpler. Please see the Wiki page for more.

**Comment by EnTeQuAk** [comment]
Note to QA: This feature sits behind the `addons-linter` flag and is only for WebExtensions.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Screenshot for this issue: 
![created2](https://cloud.githubusercontent.com/assets/15685960/15240137/2d7f1d04-18f0-11e6-9872-f78ab261d85b.png)

Web-extension used: 
[Tab-Suspender.zip](https://github.com/mozilla/addons-server/files/262649/Tab-Suspender.zip)
