### ISSUE TITLE
400 bad request on Delete notes from Collections 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18927]
STR:
1. Go to a collection , click Edit this collection
2. Leave a note
3. Try to delete it

Expected result:
The note is deleted 

Actual result: 
An error is thrown -> PATCH on https://addons.allizom.org/api/v5/accounts/account/11686419/collections/This-is-a-collection12082021/addons/619864/?lang=en-US throws a 400 Bad Request 

![401](https://user-images.githubusercontent.com/33448286/155995327-988d08cd-fd36-4dd2-bc45-76afc5f8e7a1.gif)

It is reproducible on all AMO servers.

**Comment by diox** [comment]
Transferred to addons-server since this is an API issue. This was fixed for collection descriptions in https://github.com/mozilla/addons-server/issues/18601 but as discussed in stand-up it probably needs to happen for `CollectionAddonSerializer.notes` as well.

**Comment by ioanarusiczki** [comment]
@diox Verified on AMO dev:

![AMO dev](https://user-images.githubusercontent.com/33448286/156752802-27fcb56f-687d-439a-b9a2-4826a1f389e0.gif)
