### ISSUE TITLE
If a WebExtension has an add-on id in mozilla.json, use it

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1892]
If a WebExtension does have an add-on id in mozilla.json then let's use that.  If one doesn't exist, then it will be created and saved into the add-on (see other bug for that).

Tracker: mozilla/addons#61

**Comment by EnTeQuAk** [comment]
for documentation reasons:

This is what the add-on id should match: http://mxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#267

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Generating_GUIDs

**Comment by andymckay** [comment]
mozilla.json isn't being used, I think we don't need this now.
