### ISSUE TITLE
Rename "Sign in to continue to Olympia dev" FxA page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1893]
Relates to #1753

Steps to reproduce:
1. Log in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Observe the "Sign in to continue..." FxA page

Expected result:
Maybe other page title.

Actual results:
Page title is "Sign in to continue to Olympia dev" .

Notes/Issues:
Verified on FF45(Win 7).
Screenshot fro this issue: 
![untitled](https://cloud.githubusercontent.com/assets/15685960/13697871/1a4a0396-e779-11e5-9e97-3eafae1c82c7.png)

**Comment by andymckay** [comment]
Well spotted, but not too worried about, don't think its worth fixing.
