### ISSUE TITLE
With some addons I receive a 500 error when I use a specific JSON 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#18932]
STR:
While testing around [the ](https://github.com/mozilla/addons-server/issues/18854) I've noticed I run into an error on -dev and -stage when I submit some addons using the API and use the following JSON:

{"categories": {"firefox": ["other"]}, "summary": {"en-US": "test,test, test test test"}, "version": {"upload": "4b9b40978d64449cadbc5c93e3b777d9", "license": "all-rights-reserved"}}

![500 server error](https://user-images.githubusercontent.com/33448286/156552881-b47cfd1e-1d42-4ee9-93b9-94448ec87107.png)

Notes: 
Once I removed the "summary": {"en-US": "test,test, test test test"} from the JSON I receive a 201. 
I could reproduce it with the last version of [uBlock](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/), last version of [OneTab](https://addons.mozilla.org/en-US/firefox/addon/onetab/). 
I could not reproduce it with a dummy extension or [Tabby](https://addons.mozilla.org/en-US/firefox/addon/tabby-window-tab-manager/) from prod. 
I cannot conclude what causes this behavior since all extensions I've tested with have "description" field into manifest.json 

CC @eviljeff

**Comment by diox** [comment]
https://sentry.io/organizations/mozilla/issues/3061015244/?project=6224627&query=is%3Aunresolved

**Comment by eviljeff** [comment]
error message is "'dict' object has no attribute 'strip'"

I suspect it may be bug with passing localised values -dicts with strings inside- on addon create.  (Though I'm pretty sure that was well tested behaviour.)  It might be a conflict caused when the manifest already has a value for that property.

snippet from `data` arg to `initialize_addon_from_upload`:
```
	{
   name: {
       ca: 'uBlock Origin', 
       de: 'uBlock Origin', 
       it: 'uBlock Origin', 
       lv: 'uBlock Origin', 
       pl: 'uBlock Origin', 
       pt-BR: 'uBlock Origin', 
       sk: 'uBlock Origin', 
       te: 'uBlock Origin', 
       th: 'uBlock Origin', 
       tr: 'uBlock Origin'
    },
    summary: {
        ca: {en-US: 'test,test, test test test'}, 
        de: {en-US: 'test,test, test test test'}, 
        it: {en-US: 'test,test, test test test'}, 
        lv: {en-US: 'test,test, test test test'},
        pl: {en-US: 'test,test, test test test'}, 
        pt-BR: {en-US: 'test,test, test test test'}, 
        sk: {en-US: 'test,test, test test test'}, 
        te: {en-US: 'test,test, test test test'}, 
        th: {en-US: 'test,test, test test test'}, 
        tr: {en-US: 'test,test, test test test'}
}
```

**Comment by ioanarusiczki** [comment]
@eviljeff I cannot reproduce it with upload/addons APIs for -dev
"summay" from the JSON will override the localized summaries from manifest.json -> which is the expected
