### ISSUE TITLE
Update CircleCI docker images

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18951]
Follow-up from https://github.com/mozilla/addons-server/issues/18843 we're also using on addons-server some legacy convenience images:
https://github.com/mozilla/addons-server/blob/fde1bb0f1dfce82a6a9459e68ab9f566f44bf8e1/.circleci/config.yml#L11
https://github.com/mozilla/addons-server/blob/fde1bb0f1dfce82a6a9459e68ab9f566f44bf8e1/.circleci/config.yml#L288

Those are [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) and we need to update them to supported images. The modern CircleCI convenience images have the `cimg/` prefix (but we need to check if the ones we need exist or need to be replaced with some upstream image instead)

**Comment by diox** [comment]
Update: the first one is just an orb, not a docker image, so it should be fine.

**Comment by ioanarusiczki** [comment]
@diox Is this issue qa not needed?

**Comment by diox** [comment]
> @diox Is this issue qa not needed?

Yes, if the latest version got deployed on -dev then it's working.
