### ISSUE TITLE
Hide unrelated tiers for addons-linter

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#1896]
We don't have the concept of validation-tiers in the addons-linter yet so we should hide all unrelated tiers in the validation output.

**Comment by andymckay** [comment]
Hmm, we don't break out errors, notices and warnings?

**Comment by tofumatt** [comment]
We have errors, notices, and warnings. Validation tiers are something else I think, and we didn't implement those.

**Comment by EnTeQuAk** [comment]
Actually, I tried a few things but it always looks weird and getting different detail-output and a visually completely different page is probably even more confusing.

Maybe, in some far future we add validation tiers to the linter too and then the detail page will be used a bit more but it's not looking that bad currently so I'll just close this for now until we have an actual need for it.
