### ISSUE TITLE
Log full stacktrace for `I/O error(2): No such file or directory` errors in parse_xpi()`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18967]
We had a few errors like https://sentry.io/organizations/mozilla/issues/3066304220/?project=6237717&query=is%3Aunresolved:
`I/O error(2): No such file or directory`

This is coming from `parse_xpi`()` in https://github.com/mozilla/addons-server/blob/2aa00745d78f1517d5ed57cf693c6fefbfc94e6d/src/olympia/files/utils.py#L837

We should use `log.exception` or pass `exc_info` to log the full trace to gather more information about why this is happening sometimes.

**Comment by diox** [comment]
QA: you won't be able to trigger this easily, but you can try uploading various broken extensions (no manifest, non-json manifest, weird filenames) to see if the error we return in those cases hasn't been affected by this change.

**Comment by ioanarusiczki** [comment]
@diox 
1. I did not see differences in the error messages around the manifest.json file
2.  "weird filenames" can pass validation such this one: https://code.addons-dev.allizom.org/en-US/browse/621361/versions/1693811/
3. I also ran into "Invalid file name in archive: ///////////////////////////////////////////////////////////////.js"

I got the same results on -dev and -stage so I believe that this patch did not change anything.
