### ISSUE TITLE
Point Firefox to new update info endpoint and add caching headers

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18973]
Few things I realized looking at the update info (release notes) endpoint from the Firefox side while looking into https://github.com/mozilla/addons-server/issues/18971:
- Firefox gets that URL from the update service, which currently still returns the legacy URL (formatting the string manually with no `reverse()` one of the parameters being dynamic and dealt with by Firefox in the returned URL). This can be seen by calling the update service directly, as demonstrated by example [for ublock origin upgrading from 1.38.0 to 1.48.1](https://versioncheck.addons.mozilla.org/update/versionCheck.php?reqVersion=1&id=uBlock0@raymondhill.net&version=1.38.0&maxAppVersion=98.0&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=96.0&appOS=WINNT&appABI=x86-msvc) - notice the `update_info_url` URL, which points to `https://addons.mozilla.org/versions/updateInfo/...`
- The URL returned is on the main domain instead of `services.addons.mozilla.org` as it should be
- There are 4 requests - 3 redirects before landing on the actual URL. They can be observed by opening `about:addons` for an add-on with release notes set, opening devtools to monitor network activity, and clicking at the `Release Notes` tab. For instance, for ublock-origin again:
  ```
  GET https://addons.mozilla.org/versions/updateInfo/5368975/en-US/
  GET https://addons.mozilla.org/en-US/firefox/versions/updateInfo/5368975/en-US/
  GET https://addons.mozilla.org/en-US/firefox/addon/607454/versions/1.41.8/updateinfo/
  GET https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/1.41.8/updateinfo/
  ```
  The first redirect is caused by calling the legacy URL with the locale being a suffix instead of a prefix, the second by the add-on id being used instead of the slug.

We should fix the URL directly [at the source](https://github.com/mozilla/addons-server/blob/d1e29458111842d98e48d8e5202a484dece78214/services/update.py#L205-L208), removing the need for those redirects and setting the right domain as well.

In addition, we serve those URLs without caching headers, we should add some, caching for 1 hour seems reasonable (matches the duration the XPIs and the updates are cached for).

**Comment by diox** [comment]
I'd rather not change services.a.m.o. to allow requests outside of `/api/` at this point, and `/api/` feels weird, so I'm just going to fix the update service to return the final URL without redirects, but leave this on the a.m.o. domain.

**Comment by diox** [comment]
QA: open about:addons for an add-on with release notes set (https://github.com/mozilla/addons-server/issues/18971 has some background on this, it doesn't work if you install the latest version directly), then open developer tools network monitor, and select the Release Notes tab. You should see a single request (against 4, including 3 redirects before), and the release notes should show up correctly.

**Comment by ioanarusiczki** [comment]
@diox I've noticed a single request when going to the Release Notes tab -> also the notes are displayed without issues.

![a single request](https://user-images.githubusercontent.com/33448286/159666591-abe1a98f-f90e-421c-a05d-b5a422514826.png)
