### ISSUE TITLE
Ensure update_info returns a 404 for non-public add-ons/versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#18971]
While I was working on https://github.com/mozilla/addons-server/issues/18844 I realized `update_info` currently requires the add-on and version to be _valid_, but not necessarily _public_:
https://github.com/mozilla/addons-server/blob/66e55bc230c5cce7a39fa0693fd4afde8aea4d91/src/olympia/versions/views.py#L29-L39

`VALID_FILE_STATUSES` allows versions waiting for review and approved (though not disabled).

The other view which redirects to that one doesn't even check for status:
https://github.com/mozilla/addons-server/blob/66e55bc230c5cce7a39fa0693fd4afde8aea4d91/src/olympia/versions/views.py#L48-L56

It shouldn't be a huge deal - clients won't request that information in the first place, and it's only release notes - but we should only return update info for approved and still public versions/add-ons.

**Comment by diox** [comment]
QA: release notes for installed add-ons should show up correctly in about:addons

**Comment by ioanarusiczki** [comment]
@diox 
I installed some addons with release notes (version notes) such as this [one ](https://addons.allizom.org/en-US/firefox/addon/borderify_0102/) on dev.
Then I tried on stage with this [addon](https://addons.allizom.org/en-US/firefox/addon/git-history-browser-extension/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured )
And on  prod with[ this ](https://addons.mozilla.org/en-US/firefox/addon/tab-stash/versions/?utm_content=featured&utm_medium=referral&utm_source=addons.mozilla.org)
I can see on the manage page in about:addons the presence of a description into Details and under the name it's the summary but I do not see release notes. 

that's the manage add-on page from about:addons 

![this page](https://user-images.githubusercontent.com/33448286/158332839-b2c7f115-4650-4f2e-a0b3-23d816edd917.png)

**Comment by diox** [comment]
Which version have you installed ? I think to show up, you'll need to start with an older version, let Firefox update it, and then the release notes for the version you updated to would show up.

**Comment by splitest** [comment]
@diox I installed the last version only because I thought it should work and see the notes of the latest version (or an older one) Thanks for the tip, I'll try again

**Comment by ioanarusiczki** [comment]
@diox I tried with the latest versions. Thanks for the tip, I'll try again
