### ISSUE TITLE
Retain slug changes in the activity log

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#18980]
Sometimes we encounter an URL in communications that has changed, e.g. the author has changed the slug, it was deleted.

It seems we don't retain this information, though it would be helpful to look up add-ons where we only have limited information.

If we can keep the slug in the activity log, this would already be sufficient for me, either in the entry with the property change, or separate, whatever is better for you.

This isn't super high priority, but in case we do have encounter a such case in the future, we won't have any way to find the original add-on.

**Comment by eviljeff** [comment]
not strictly an api specific request, but I'll add this to the add-on submission project because it'll need the change in there too.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-84
