### ISSUE TITLE
Make sure API calls for add-on and version changes emit a log activity.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19008]
https://github.com/mozilla/addons-server/issues/18036 and friends make several fields for add-ons and versions writable through the API. We should make sure those actions emit a log activity.

**Comment by diox** [comment]
We should copy current DevHub behavior for now. `EDIT_PROPERTIES` should be emitted in most cases, but there are also some more specific ones like `CHANGE_ICON`, `USER_ENABLE`/`USER_DISABLE`, etc.

**Comment by eviljeff** [comment]
we have a some specific actions that don't appear to be used in devhub (or anywhere) for metadata changes currently:
- EDIT_DESCRIPTIONS, 
- EDIT_CATEGORIES, 
- EDIT_CONTRIBUTIONS

Should they be used where they exist already?  Or just match devhub functionality and use `EDIT_PROPERTIES` for most properties.

**Comment by eviljeff** [comment]
It's all very inconsistent in devhub.  We have `CHANGE_ICON` but it appears to be created for _any_ change in the media section - so previews as well as icons.  We have `ADD_TAG` and `REMOVE_TAG` but just generic "edit" for other properties.  We have `EDIT_DESCRIPTIONS` but it's unused for any of the description changes.

**Comment by eviljeff** [comment]
I suggest for the API we just use `EDIT_PROPERTIES` for all metadata changes, apart from status (`USER_ENABLE`, `USER_DISABLE`) and pass a detail object (that will be serialized as JSON) with the actual properties changed.

(the logging for `ADD_TAG` and `REMOVE_TAG` is further down the stack, but it would be consistent to remove them too)

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa. 
Thanks!

**Comment by eviljeff** [comment]
QA:
essentially just check that the same activity log entries appear for changes in devhub are also created for changes via the addons api.  Probably not worth the effort to check everything, but here are some suggestions:
- icon changes should create `CHANGE_MEDIA` ("{addon} icon or previews changed.")
- tags should create separate add tag and remove tag logs - this isn't new behaviour.
- enabling or disabling the add-on should create either an activity for enable or disable
- changing a version's license should create a `CHANGE_LICENSE`
- changing a version's max application should create a `MAX_APPVERSION_UPDATED`
- uploading the version's source should create `SOURCE_CODE_UPLOADED` - this isn't new behaviour.
- `name` and `summary` should created `EDIT_PROPERTIES` ("{addon} properties edited") - but only one per request (not one each for name and summary change).  There should be an extra blob of data in the activity log entry that contains which fields were changed (not sure if we expose that in the admin though).  EDIT_PROPERTIES is the default activity created for add-on changes if there isn't a more specific type.  Note there is no generic default activity for version changes.

**Comment by ioanarusiczki** [comment]
@eviljeff 

- icon or previews changed 
- tags -> add/remove logs are generated when using the API and for each tag there's a separate activity log.

_Note:_ when it is done from dev hub, I see 2 activity logs generated , for example if I add a tag, there's "add" logged plus another report with "properties edited" 

- is_disabled -> true, activity log notifies that the addon is disabled, is_disabled false -> activity log notifies that the addon is enabled 
- license -> "is now licensed under Mozilla Public License 2.0. "
- max version change (langpack) -> "Application max version for [Version 92.0.1buildid20210922161155](https://addons-dev.allizom.org/en-US/firefox/addon/simplified-zh-cn-language-pack/versions/) updated."
- for source code -> "Source code uploaded "
- name and summary, or description, slug, e-mail address, is_experimental, categories, requires_payment -> one generic activity log with no details "properties edited"
