### ISSUE TITLE
Translate add-on API errors

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19007]
The new add-on API has a few validation errors that aren't translated, we should fix this. 

Developers are expected to speak English because the policy & distribution agreement are in English, and that's also the language that will be used to interact with reviewers, but DevHub and the frontend-facing APIs are fully translated, so we should translate the add-on API as well.

**Comment by ioanarusiczki** [comment]
@eviljeff 
1. I verified this on -dev by adding to the requests the ?lang parameter in several languages, I mainly tried with de, fr, ro, it. 
I tried to trigger as many errors as possible and where translations are available the response returned them.

- Found translations for:
 "Could not parse the manifest file."
'"URLs must start with https://."
"Upload a valid image. The file you uploaded was either not an image or a corrupted image."
  "This field may not be null."
"Invalid value."
"Both `license` and `custom_license` cannot be provided together."
 "Images must be smaller than 4MB"

- When translations are unavailable in other languages there's the en-US available: 

  "The \"other\" category cannot be combined with another category"
 "Maximum number of categories per application (2) exceeded"
 "Invalid category name."
   "Invalid app name."

2. One thing noticed about this error:
 "Images must be smaller than 4MB"

A POST request with https://addons-dev.allizom.org/api/v5/addons/addon/621486/previews/?lang=en-US using an image size > 4 MB will trigger the error above. If I use dev hub for such an image I am allowed to upload it -> I see a POST request in the network for  https://addons-dev.allizom.org/en-US/developers/addon/unlisted-example-05-28/upload_preview
Let me know if I should file an issue about this.

**Comment by eviljeff** [comment]
>     2. One thing noticed about this error:
>        "Images must be smaller than 4MB"
> A POST request with https://addons-dev.allizom.org/api/v5/addons/addon/621486/previews/?lang=en-US using an image size > 4 MB will trigger the error above. If I use dev hub for such an image I am allowed to upload it -> I see a POST request in the network for https://addons-dev.allizom.org/en-US/developers/addon/unlisted-example-05-28/upload_preview Let me know if I should file an issue about this.

yeah... I wasn't really sure if this was an oversight in devhub tbh.  4MB seems a good max size for a single screenshot to me but thoughts @mozilla/addons-amo-engineering / @wagnerand ?

**Comment by diox** [comment]
That 4MB limit should be ok and more importantly should be enforced everywhere...
