### ISSUE TITLE
The /addons/create/ API returns a 500 error if the `contributions_url` field contains some invalid values

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19000]
Follow up for #18267

### Describe the problem and steps to reproduce it:
1. Create a new add-on using the `/addons/create/ ` API
2. Add a `contributions_url` in the JSON request body with either a random string or number value, i.e. `"foobar"` or `12345`
3. Send the request

### What happened?
A 500 server error is returned

### What did you expect to happen?
A 400 error asking for a valid URL

### Anything else we should know?
Empty strings , `bool` and `null` values produce correct validation messages with a 400 response

**Comment by eviljeff** [comment]
ah, yeah

https://sentry.io/organizations/mozilla/issues/3113672000/?project=6224627

https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/fields.py#L98 - we're not capturing the case when the input isn't a valid URL so `parsed_url.hostname` is `None`

**Comment by AlexandraMoga** [comment]
Random strings or numbers in the `contributions_url` field now produce a 400 error with the following message:

```
{
    "contributions_url": [
        "URL domain must be one of [www.buymeacoffee.com, donate.mozilla.org, flattr.com, github.com, ko-fi.com, liberapay.com, www.micropayment.de, opencollective.com, www.patreon.com, www.paypal.com, paypal.me].",
        "URLs must start with https://."
    ]
}
```
