### ISSUE TITLE
Unable to get past step 2 in add-on submission

### ISSUE THREAD

**Issue by runejuhl** [mozilla/addons-server#1901]
I've been trying my luck at signing runejuhl/keysnail#issue/189, but I can't seem to get past step 2 in the process. 

Steps:

- Agree to terms (and click second menu entry due to mozilla/addons-server#1096)
- Choose unlisted
- Upload XPI
- Check succeeds with 39 warnings
- Click "Continue"
- Request goes to https://addons.mozilla.org/en-US/developers/addon/submit/2, meaning it's just a refresh of the current site.

I've tested in Iceweasel 46.0a2 (2016-02-17) as well as Chromium 47.0.2526.80, and both browsers exhibit the problem. I can provide a HAR dump and the XPI if needed.

**Comment by mstriemer** [comment]
Can you attach the XPI please? If you rename it to `.zip` it should be able to get uploaded to GitHub.

**Comment by runejuhl** [comment]
Sure, here it is. It's https://github.com/runejuhl/keysnail/tree/issue/189 with `id` and `updateURL` changed in `install.rdf`.

[keysnail.zip](https://github.com/mozilla/addons-server/files/173190/keysnail.zip)

**Comment by mstriemer** [comment]
When I uploaded it on our development server I got the error "Need to select a platform." This is because the id for the Firefox `targetApplication` was changed to the add-on id.

You'll want to set that id back to what it is on mooz/keysnail https://github.com/mooz/keysnail/blob/20c77d4efa9ec04451a1e4d24947048acdc57c7f/install.rdf#L50.

**Comment by runejuhl** [comment]
Woops, sorry about that. I don't see any error in the upload form though -- perhaps it could be shown there to avoid any needless issues from other people who might, ahem, end up with an invalid `install.rdf`?
