### ISSUE TITLE
Prevent update service tests from breaking other tests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19042]
The update service currently calls [`log_configure()`](https://github.com/mozilla/addons-server/blob/a4cb2ba4313582e1938475983901cdfed0b0bb13/services/utils.py#L26-L45) [as soon as it's imported](https://github.com/mozilla/addons-server/blob/a4cb2ba4313582e1938475983901cdfed0b0bb13/services/update.py#L23).

It does this because it's a completely separate wsgi application, that doesn't depend on django: so if it wasn't configuring logging on its own, it wouldn't have any config set, the logs wouldn't be emitted properly.

Unfortunately, we run the [update service tests](https://github.com/mozilla/addons-server/blob/a4cb2ba4313582e1938475983901cdfed0b0bb13/src/olympia/addons/tests/test_update.py) as part of the rest of the test suite, and that call to configure logging is messing up the logging configuration for all tests running after that !

A couple possible fixes/workarounds:
- Separate the test runs completely. This is a bit annoying and not a 100% guarantee, since the problem occurs as soon as we import stuff from `services/`. OTOH we shouldn't do that...
- Move the `log_configure()` call to happen at runtime inside `application()`
  - On its own it's not enough, we'd also need to mock it when we do call `application()` in tests
  - A variation of this, move the call but also replace `log_configure` by something ensuring the logging config is shared with the one we use for the django app (remember though, the update service is not django, so it can't call `django.setup()`. It can depend on settings though)

**Comment by diox** [comment]
QA: update service should still work. Once on stage, try multiple times in the same day, with at least 5 minutes between each attempt.

**Comment by ioanarusiczki** [comment]
@diox It is working on -dev but it will be re-tested for -stage tomorrow.

**Comment by ioanarusiczki** [comment]
@diox This is verified on AMO stage too -> manual and automatic updates are working.
