### ISSUE TITLE
Add add-on activity to django admin add-on page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19048]
The django admin add-on page misses a link to the add-on activity.

**Comment by AlexandraMoga** [comment]
The add-on activity logs are now linked in the add-on admin page (for all add-on types and statuses):

![image](https://user-images.githubusercontent.com/31961530/161511653-b65b53cd-1d26-46fb-b6ae-d9c5fe0c4c34.png)

This issue is verified fixed on -dev.
