### ISSUE TITLE
Update notification email targets

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19052]
Some email targets need to be updated, some others are no longer used.

**Comment by wagnerand** [comment]
QA: Not much to test here, if you'd like you check the following:

1. Delete an add-on with versions
2. Make sure that the deletion mail recipient is amo minus notifications plus deletion at mozilla dot com (it used to be dot org).

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on stage:

[before]
![image](https://user-images.githubusercontent.com/31961530/161058815-4fba0abc-bc07-480d-a48e-655f52b20d86.png)

[after]
![image](https://user-images.githubusercontent.com/31961530/161058869-8a369a70-ef05-4956-85e6-ba45eb33aec8.png)
