### ISSUE TITLE
Add-on developers should not be allowed to delete negative reviews so easily

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-server#1906]
Coming from https://bugzilla.mozilla.org/show_bug.cgi?id=1256293

I know that developers can't directly remove reviews, and I'm not sure if flagged reviews get hidden by default, but it's clear that at least one extension is doing a lot of reviews cleanup. 

Ghostery: https://addons.mozilla.org/en-US/firefox/addon/ghostery/reviews/

This is a screenshot that I made this morning at 7.30 CET

![ghostery 2016-03-15 at 07 07 31](https://cloud.githubusercontent.com/assets/3644868/13770808/f33a2d4e-ea89-11e5-9e53-5e062f1f2d0e.png)

This is the same page, less than an hour and a half later. That's 3 negative comments gone.

![ghostery 2016-03-15 at 08 38 12](https://cloud.githubusercontent.com/assets/3644868/13770835/1ca54bfa-ea8a-11e5-8e67-df222b591488.png)

It would be interesting to know the average of flagged reviews for add-on, and how many this specific add-on has.

**Comment by flodolo** [comment]
I don't have a screenshot for this one, but a user reported that he added a 4 stars review and it got removed (notice the all 5-stars review, that seems statistically improbable)
https://addons.mozilla.org/en-US/firefox/addon/reader/

**Comment by EverEve** [comment]
This screenshot has been taken yesterday. It is plain to see that at least one of the "1 stars" review has been deleted since the counter reads 116 and currently is 115 (see image in previous post).

![review_ghostery_1](https://cloud.githubusercontent.com/assets/6781183/13771053/684e652c-ea8b-11e5-856a-6817541e838d.png)

**Comment by EverEve** [comment]
At this very moment you can read this review (screenshot attached):

> Review: The developers have trashed this add-on. Most of the complaints you read below are true. This add-on has been ruined by it's developers. I suggest you all uninstall now and don't look back. Don't give Ghostery the courtesy of raising its website's click count every time you need to change or view the settings. There are other options for blocking trackers.
> 
> Note to developers: I have made it my mission to re-post this review every time it is deleted. I have an endless supply of email accounts, and I know how to use proxies for bypassing IP banning...so give it your best shot. I will be checking back daily.
> 
> 

Is there anything else we can do to prove the abusing of the review system?

![review_ghostery_3](https://cloud.githubusercontent.com/assets/6781183/13778406/dda5e758-eab5-11e5-8833-98fd71cea1d7.png)

**Comment by wagnerand** [comment]
I can see how the reviewer deleted that review, because I am not sure this is a helpful review either.

**Comment by EverEve** [comment]
Is anyone forced to leave only useful comments?
I could even leave only a "star" and a blank space in the text field. Should such a review be deleted?

We simply mean that, with the current review management, an author can alter the overall perception of an add-on. And this is what is happening now.

**Comment by jvillalobos** [comment]
The current policy is [explained here](https://addons.mozilla.org/review_guide). In that regard, I agree with @wagnerand and would consider this bug to be invalid, since the bugs are being deleted by an independent group following the stated policies.

We want reviews to be useful because at the moment we don't have a way to rank them by usefulness, so only the latest ones are immediately visible and it would be easy to discourage users with a couple of well-placed negative reviews. Long-term, we need to implement a review ranking system like most stores use, and surface the most useful ones. Then we can lower our review moderation standards. For now, I think we should keep the current policy.

**Comment by EverEve** [comment]
I don't think you are being very fair and transparent to users.

**Comment by flodolo** [comment]
@jvillalobos 
Did you  take a look at the comment removed from the first screenshot? In particular at the "Bait & Switch" one? How is that against guidelines?

Sorry but this is a huge lack of transparency, and people won't blame the author of the add-on but Mozilla.

**Comment by jvillalobos** [comment]
You're right about that one. I went over some of the deleted reviews and found a few that should have been kept rather than deleted.

**Comment by mannyanyr94** [comment]
You guys want to see deleted reviews, check out AdBlockPlus. They had 90+ 1 star and I don't know how many 2 stars but it's now 0 for both. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular

**Comment by mannyanyr94** [comment]
That's pretty crazy how this all works. Have you guys seen AdBlockPlus's reviews? They had like 100 or so in the last 2 weeks. And today, all 1 star and 2 stars have been deleted so there is 0. I'll attach a screengrab. What gives?
<img width="1090" alt="screen shot 2016-04-01 at 5 59 03 pm" src="https://cloud.githubusercontent.com/assets/18150629/14221405/99fdfd7e-f834-11e5-8173-69f88aa83df5.png">

**Comment by cweiske** [comment]
I made a comment about Adblock Plus and its shady practises yesterday. Today it is deleted, and I don't see why it should have been:

![2016-05-27 firefox addons adblock plus](https://cloud.githubusercontent.com/assets/59036/15614830/29b615dc-243b-11e6-850d-87ed855bb355.png)

https://addons.mozilla.org/de/firefox/addon/adblock-plus/reviews/

**Comment by rmenessec** [comment]
I've attempted to leave a review calling out the constant connectivity back to ghostery.com services and questioning why Mozilla are allowing an addon executing most or all of its UI code from a third-party server. This is a trivial end-run around whatever code review AMO staff are performing, and it renders the addon completely untrustworthy. My review's been deleted. Repeatedly.

In fact, I've left reviews in _several different formats,_ with widely varying language, including one that started by explaining how it was _consistent_ with both AMO review policies and the Ghostery addon's (strongly anti-user) EULA.

All of my reviews so far have been deleted. All have been honest, as concise as possible, and attempted to adhere closely to AMO policy.

There are perhaps two or three reviews left that make a passing reference to the addon requiring constant connectivity to Ghostery Internet services. There are none that refer to the developers' apparent policy of deleting honest—and negative—reviews _en masse_ or to the fact that this addon's code simply _cannot be said to have passed review by Mozilla._

If this developer is going to be allowed to continue to "curate" (destroy) their reviews, can someone please at least remove the "reviewed by Mozilla" flags on the addon? It's hugely inaccurate and misleading.

Allowing any developer to execute most of the UI—or any code at all—by loading it off a remote server is inherently risky. Mozilla's betting its reputation that Ghostery's not doing anything malicious. Mozilla's also betting that no one else is injecting code while parts of the addon are in transit.

In case no one's noticed, the EULA for Ghostery now _strictly forbids any form of analysis or code review,_ and the language is purposely broad and vague to the point that it could conceivably prohibit even Mozilla from analyzing the addon to ensure that the remote code's at least being loaded over TLS.

If any of the remotely loaded code—even a tiny bit; even just an image resource or two—is vulnerable to unencrypted HTTP injection, then the Ghostery addon is a persistent backdoor with Mozilla's seal of approval.

[Don't be these guys](http://arstechnica.com/security/2016/06/how-pc-makers-make-you-vulnerable-to-man-in-the-middle-attacks-out-of-the-box/). Please.
