### ISSUE TITLE
enable addon delete via addons api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19072]
You can submit, edit, and add new versions via the addons api; we should implement delete also.

**Comment by wagnerand** [comment]
Add-on delete has an extra confirmation step when done via devhub. Is that something we can/want to do for API calls as well?

**Comment by eviljeff** [comment]
> Probably not ideal, but we could return an url (or send an email containing a link) that the user needs to visit to confirm? Open to other suggestions as well.

In a purely API world, the url would also be using the API.  So would it be different endpoint?  The same API endpoint but with some data returned from the first call?  (All possible, but easily scriptable so how much would it help?  Not sure)

**Comment by eviljeff** [comment]
I don't have a good handle on the way forward with this issue - partly because it's unclear to me what problem we're trying to solve with the proposed roadblocks.  Is it accidental DELETE requests to the `/addon` endpoint?  Is it proving the developer has access to the account that owns the add-on?  Something else? (confirming the developer actually understands what they're doing isn't really a thing with the api - we can't show them a dialog with bold text on it like with devhub)

The two suggestions I see so far are:
- return/send a url that is either a different API endpoint and/or contains a confirmation code
- something involving a signed token delivered by another endpoint (not clear here if this is intended to be a something in response to the DELETE or something you'd get before the DELETE and provide it with the DELETE request)

**Comment by wagnerand** [comment]
I think it's a good idea to replicate the behavior we have on devhub. That requires entering a string (the add-on slug iirc), presumably to prevent accidental deletion. Imho, that is a valid and good problem to solve in the API as well.

**Comment by diox** [comment]
My idea was to force the clients implementing the API to have a mechanism similar to what we have in devhub currently, ensuring developer actually meant to delete this particular add-on.

My idea was to have clients call another endpoint first, getting some kind of token they would need to provide to the `DELETE` request if they want it to succeed. That sort of violates RESTful spirit, but I think that's acceptable. There might be a better solution though.

**Comment by AlexandraMoga** [comment]
I've verified deleting add-ons with the submissions API an these are my results:

- to delete an add-on, a user needs to follow this flow: get a `delete_confirm` token from the [Delete confirm](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#delete-confirm) endpoint and then send a DELETE request to the [Delete add-on](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#delete) endpoint passing the previously fetched token as a query parameter; a valid delete request will return a `204 No Content` status and the add-on will be deleted successfully (*)
- the confirmation token is valid for only 60 seconds; any requests using an expired token will be considered invalid
- a confirmation token requested for one add-on cannot be used for deleting another add-on
- subsequent delete requests for an already deleted add-on will return a `404 Not Found`
- a user can't requests delete confirmation tokens for another user's add-ons

(*) @eviljeff I was thinking if we should also return a more detailed confirmation message for a successful delete request. Right now, we only return the status code (the 204).

**Comment by eviljeff** [comment]
204 is the standard response for a successful DELETE https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE - there isn't any valid JSON object to be returned for a deleted add-on, and the API doesn't return general messages for success.
