### ISSUE TITLE
500 error is caused when form-data, icon:null is sent 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19079]
As I described into https://github.com/mozilla/addons-server/issues/18232#issuecomment-1087493185

I could not set the icon key to null -> I receive a 500 server error. However I could reset the icon sending it as JSON 
with  {"icon": null} I get a 200 response. 

But it won't work as form-data

![500](https://user-images.githubusercontent.com/33448286/161543490-b288cd78-f66f-4c2c-9871-8c9c944443f4.png)

Expected result:
This should be working using JSON format but it should throw a warning when form-data is used for icon instead of a 500

**Comment by AlexandraMoga** [comment]
The same issue applies to source code upload. If `source: null` is sent as `form-data`, a 500 error is returned. Maybe both issues can be solved by the same patch.

**Comment by eviljeff** [comment]
I went in the opposite direction with the patch - now `null`/`""` is a valid multipart formdata value that clears the icon (or source) in the same way `null` in a JSON request does.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- For both icon/source -> they're reset/deleted when I choose form-data "file" type and don't select any file. 

![works this way](https://user-images.githubusercontent.com/33448286/163796740-9b8f9dba-93f1-4873-b3ec-df8c05987505.png)

- I will get a 400 bad request if the request is sent as above - with form-data file (text) : null

![400badrequest](https://user-images.githubusercontent.com/33448286/163797311-7214d208-31b9-4b96-9340-f61dc30f9a5e.png)


- Works with the JSON format for both:  {"icon":null} and {"source":null} 

I'm guessing it's alright, otherwise let me know.
