### ISSUE TITLE
Show add-on average daily users in code-search results

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19073]
Code-search results (aka _Scanner query results_) should show a sortable column for average daily users of an add-on.

**Comment by wagnerand** [comment]
<img width="826" alt="Screenshot 2022-04-04 at 15 31 38" src="https://user-images.githubusercontent.com/873258/161554932-efc78ff3-7928-4a27-a626-4e6304c3c84d.png">

**Comment by ioanarusiczki** [comment]
@wagnerand I checked on admin -dev into Scanner query results and "Addon ADI" is available (it's supposed to be "Addon ADU"?)

![addon ADU](https://user-images.githubusercontent.com/33448286/161733657-d4d86e04-d4e9-4d85-a450-90d3d6b04ed9.png)

**Comment by wagnerand** [comment]
Thanks. Yea, I suppose ADU is a tick more consistent on naming, but it's fine. We also use ADI and ADU interchangeably sometimes.
