### ISSUE TITLE
dennis: planning end-of-life

### ISSUE THREAD

**Issue by willkg** [mozilla/addons-server#19075]
I'm the current maintainer of [dennis](https://github.com/willkg/dennis). I'm maintaining too many things and I haven't used Dennis in years, so I'm looking at either:

1. passing maintenance to someone else
2. or, ending the project

Dennis is used in this project to lint PO files. If you're interested in taking over maintenance, that'd be great! If no one takes over, I'll shut down the project in May 2022.

**Comment by diox** [comment]
Thanks @willkg, we're going to discuss this within our team.

Note: we considered re-implementing the linting elsewhere before, see https://github.com/mozilla/potools/issues/12. Worth keeping in mind that this affects addons-frontend too, which uses dennis as a lint step.

**Comment by diox** [comment]
We definitely need linting po files, we've caught countless issues with translators mistakenly translating variable names, not including variables in a translation, etc. I've looked at other tools to replace `dennis` and while there are quite a few projects that aim to do .`po` linting, the ones I found are either abandoned or don't have the features we need...

I'm leaning towards taking over maintenance of `dennis`, but on a very limited capacity: we don't have the bandwidth to implement new fancy features or fixing any of the existing issues...
