### ISSUE TITLE
Some API fields that expect a string value return a 500 error if an object value is provided

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19080]
### Describe the problem and steps to reproduce it:
1. Send a request to the following endpoints:
  1.1 [POST /api/v5/addons/addon/](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#create) or [POST/PATCH /api/v5/addons/addon/{addon}/versions/](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-create) with `license` field set as `"license": {"slug": "some-slug"}`
  1.2 [POST /api/v5/abuse/report/addon/](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#post--api-v5-abuse-report-addon-) with any of the following fields set as:  `"reason": {"reason": "damage"}`, `"app": {"app":"firefox"}`, `"addon_signature": {"type": "curated"}`; other fields with the same issues are  `"addon_install_source"`, `"report_entry_point"`, `addon_install_method`. 

### What happened?
A 500 error is returned

### What did you expect to happen?
A 400 error with the appropriate field validation message

### Anything else we should know?
I've tried to trigger the error for other endpoints, such as accounts, collections, ratings etc, but I could not reproduce the issue

**Comment by MichaelSp** [comment]
That is actually described in the documentation. The behaviour is neither nice nor expected but at least documented:

![image](https://user-images.githubusercontent.com/448282/166994155-5f5fae03-6a56-40eb-8466-36ae9bc60c82.png)
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-sources

**Comment by diox** [comment]
We should return a 400 and not a 500, though.

**Comment by eviljeff** [comment]
The abuse report errors seem to come from https://github.com/mozilla/addons-server/blob/master/src/olympia/api/fields.py#L49 where we catch invalid keys (`except KeyError`) but not attempts to use a key that can't be hashed - i.e. a dict can't be used as a key for a dict so a `TypeError: unhashable type: 'dict'` is thrown instead.

The `license` field doesn't use `ReverseChoiceField` but it's doing something similar(`LICENSES_BY_SLUG.get(data)`) and it's failing for the same reason.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and most of the fields that were throwing 500 errors are now returning a 400:


- license field: `"version": {
        "license": [
            "License with slug={'slug': 'some-slug'} does not exist."
        ]
    }`
- abuse report fields:
  - reason: ` "reason": [
        "\"{'reason': 'damage'}\" is not a valid choice."
    ]`
  - app: `"app": [
        "\"{'app': 'firefox'}\" is not a valid choice."
    ]`
  - addon_signature: `"addon_signature": [
        "\"{'type': 'curated'}\" is not a valid choice."
    ]
}`

@eviljeff there are some fields that are still throwing 500 in the abuse report API: `addon_install_source`, `addon_install_method`. The  `addon` field -  something I haven't mentioned in the STR, is also throwing a 500 if its value is not a string.

**Comment by AlexandraMoga** [comment]
> can you file an issue for the record?

filed #19286
