### ISSUE TITLE
Get rid of FakeEmail and EmailPreview

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#1908]
We need to ensure that dev and stage do not send real emails. On prod we need to be able to test emails before we send them. Currently we do all this by redirecting to two models FakeEmail and EmailPreview.

This isn't great for a couple of reasons 1) we have models and tables to maintain and 2) you can't actually see how the emails would render in the real world. I suggest we instead use an email list like this one I just made https://groups.google.com/forum/#!forum/addons-server-test-emails

We'll make it internal, anyone internal can subscribe or unsubscribe to it. When we send a fake email for testing purposes, instead of sending it to the real developer we send it to that email group. You'll see all the emails in an easy to use client.

For extra bonus points we could include the real person the email was going to in an extra header truncated so we don't have a log of everyone's email address in a google mailing list ready to be stolen.

**Comment by eviljeff** [comment]
1.  Do we need `EMAIL_QA_WHITELIST` and actually sending emails to that whitelist if the emails will be real now but sent to a different address?
2.  Should the default be that to email forum?  Or just for dev/stage/etc? - I'm thinking about local development (including non-moco contributors).  If the default is addons-server-test-emails@ it will potentially get all kinds of random emails; if there is no default then would the emails just be discarded?
