### ISSUE TITLE
Increase the recursion limit

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#1911]
There are some add-ons that are failing validation and we think it might be due to the python recursion limit being reached. We should increase it to at least `10000`, it can be increased using `sys.setrecursionlimit()`. I'm not sure if there's any other way of setting it.

Related to https://github.com/mozilla/addons-server/issues/1885 and https://github.com/mozilla/addons/issues/41.

**Comment by vcarciu** [comment]
mstriemer : can you please add some examples off addons for which validation failed before setting the new recursion limit?

**Comment by mstriemer** [comment]
There are add-ons in the associated issues but I'm going to test this myself since I'm not sure it will fix the root issue.
