### ISSUE TITLE
Throw an error for static themes while attempting api preview operations 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19118]
Followup for https://github.com/mozilla/addons-server/issues/18236

 I ran into a situation: after I tried PATCH and DELETE on a theme id -> I get no response, Status and Time are blank. 
POST  create preview is returning status created but sending a preview for a theme has no impact in dev hub. 
I replaced the id of the theme with an extension after this but I still get no response for PATCH and DELETE  so I made new requests (into a new tab) which will work as expected. 

PATCH/DELETE after using a theme id/guid:

![does not respond](https://user-images.githubusercontent.com/33448286/163136659-977c2f91-e8d6-4bf3-8bb9-97c802389e67.png)

Expected result:
POST, PATCH or DELETE should throw a warning when a static theme id/guid is used. 

API docs: 
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#preview-create

**Comment by eviljeff** [comment]
fwiw, it's the `POST` (create) that's at fault here - it shouldn't be possible to create previews for themes.  If it wasn't possible to create them there wouldn't be an id returned to patch or delete.  (the previews for themes are actually different objects underneath so the ids aren't shared - trying to patch or delete a genuine theme preview would 404)

**Comment by ioanarusiczki** [comment]
@eviljeff 

> fwiw, it's the POST (create) that's at fault here - it shouldn't be possible to create extension-style previews for themes. If it wasn't possible to create them there wouldn't be an id returned to patch or delete. (the previews for themes are actually different objects underneath so the ids aren't shared - trying to patch or delete a genuine theme preview would 404)

Yes, when there's no id for a preview the PATCH, DELETE operations won't work.

I get the 400  -         "Previews cannot be created for themes." on -dev.
