### ISSUE TITLE
A disabled version is listed under "Next Version" in the add-on status

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1912]
Steps to reproduce:
1. Submit an add-on and approve it in AMO-dev https://addons-dev.allizom.org/ 
2. Submit a second version for that without approving it 
3. Disable the unapproved version (i.e. https://addons-dev.allizom.org/en-US/developers/addon/vers-uni/versions)

Expected results:
Add-on status is displayed according to the approved version. There is no "next version" link.

Actual results:
The disabled version is listed in the add-on status, as a "Next version",

Notes/Issues:
Clicking the "Next version" number returns a 404 page.
After accessing the disabled version details page ( from "Manage Status & Versions" ) and downloading it, the user cannot open the version. (message: damaged/corrupt)
Verified on FF45(Win 7). Issue is reproducing on AMO-dev and AMO-stage.
Screencast for this issue: http://screencast.com/t/cCMV1Dfif

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshots: 
![1](https://cloud.githubusercontent.com/assets/15685960/15238809/2f126e42-18e5-11e6-9d9f-f794e53c1a10.png)
![2](https://cloud.githubusercontent.com/assets/15685960/15238810/33ae795a-18e5-11e6-8f02-8b9cebc2bd90.png)

**Comment by ValentinaPC** [comment]
@eviljeff : there is another situation when a disabled version is listed as "Next Version", as follows:

1. Submit-approve an add-on
2. Submit a second version for that add-on (without approve)
3. Make the add-on Hidden -> the "awaiting" version turns into "disabled"
4. The disabled version is still listed in the "Next Version" section

Is this intended?

**Comment by eviljeff** [comment]
I guess that's a code path that doesn't end up calling the code to update `latest_version`.  It doesn't really matter while its hidden (the user facing term for 'disabled'), but if it still shows the disabled version as being the next one after the add-on is listed again then can you file an issue?

**Comment by ValentinaPC** [comment]
Logged #2664
