### ISSUE TITLE
Limit an upload for screenshots to max. 4 MB

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19137]
As discussed https://github.com/mozilla/addons-server/issues/19007#issuecomment-1104185647
 
When using the API https://addons-dev.allizom.org/api/v5/addons/addon/621486/previews/ with an image >4 MB the error message is:  "Images must be smaller than 4MB"

The same error should be displayed when making the upload from dev hub because currently the upload is not limited:

https://addons-dev.allizom.org/en-US/developers/addon/unlisted-example-05-272/edit

**Comment by diox** [comment]
We should obey `MAX_IMAGE_UPLOAD_SIZE` that we're already using for the API.

**Comment by ioanarusiczki** [comment]
@diox Verified on AMO stage - FF103(Win10). 

![4MB](https://user-images.githubusercontent.com/33448286/186372432-e0649047-e593-4fcb-886c-7e8ab1b729c4.png)
