### ISSUE TITLE
Build admins-only internal search API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#1914]
Tracker: #1744 

Once the base search API, serializer fields and authentication/permissions are in place, we can build the internal search API that will be limited to admins. It will have a specific URL prefix, probably `/api/v3/internal/`, to distinguish it from the rest.

This will require making a view inheriting from the regular `AddonSearchView` with some things tweaked - in particular, the filter backends will be different in order not to limit it to public add-ons, and obviously the permissions will be more restrictive.

Changes to the ES index and the indexation code will need to be made: Deleted add-ons (and maybe incomplete as well ?) need to be added to the ES index, and ignored in most of the queries we make. Currently they are completely removed from the index when deleted.

**Comment by mstriemer** [comment]
As noted in #2244 we should include extra URLs in this endpoint that admins will find useful. Management, review, etc.

**Comment by diox** [comment]
Note: I haven't added the new fields or made a separate internal-only endpoint yet, but the detail endpoint now allows access to unlisted/deleted add-ons if you have the right permissions. That was done in #2298.
