### ISSUE TITLE
Refactor acl code to pass user instead of request in acl checks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19145]
`check_addon_ownership()` and most functions in `access.acl` receive a `request` argument, but really the only thing they care about is the `user`. We should refactor them to pass `user` directly instead, because some calls could be coming from non-request code (tasks, crons etc).

Blocks https://github.com/mozilla/addons-server/issues/19136

**Comment by diox** [comment]
QA: this should be a transparent change, check for regressions around permissions checks in reviewer tools (like, what a static theme reviewer can see/access vs what a listed reviewer or unlisted reviewer can)

**Comment by AlexandraMoga** [comment]
I've verified permission checks in rev tools by using individual permissions or a combination of permissions and the access levels and available reviewer actions were as expected. 

This issue is verified fixed on stage.
