### ISSUE TITLE
Remove code related to the "wat" scanner

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#19152]
We never enabled _wat_ in prod so let's remove the code for it.

**For QA:** please verify that:

1. there is no scanner result for "wat" in the admin
2. the  `enable-wat` waffle switch no longer exists
3. other scanner results still exist (customs/yara should still be listed in the admin)
4. other waffle switches should still exist (only the waffle switch mentioned in (2) should be removed)

**Comment by willdurand** [comment]
We should also get rid of the following env vars in all envs:

- `WAT_API_URL`
- `WAT_API_KEY`

**Comment by willdurand** [comment]
I filed a JIRA ticket for the ops side (deployment config)

**Comment by AlexandraMoga** [comment]
I've verified the scanners on -dev and I haven't found any issues.
There are no `wat` scanners results available and the other scanners are running as expected.

The only place where `wat` is still mentioned are the filters, but this can be done in another patch:
![image](https://user-images.githubusercontent.com/31961530/166238037-ae4f38cc-4713-4fde-9cf4-fad5b6e5ba39.png)

**Comment by willdurand** [comment]
> The only place where `wat` is still mentioned are the filters, but this can be done in another patch:

that is expected
