### ISSUE TITLE
Allow addon authors to be deleted via addon api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19163]
split from #18231 (which was itself spun off from #18036)

You should be able to delete add-on owners/developers via the addon api

We just need to enforce there is at least 1 owner remaining & at least 1 visible author.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified the DELETE on dev and it worked for me. 

When I tried deleting the last ownner or make changes such as "role":"developer", "listed": false I get the error messages:
  "Add-ons need at least one owner."
  "Add-ons need at least one listed author."

A deleted owner cannot cannot edit the addon:
 "detail": "You do not have permission to perform this action."
