### ISSUE TITLE
Automatic rejection of previous versions continues after Manual Approval

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#19162]
I came across the situation today and I am not sure if that is how it is meant to be or not.
I would imagine the manual approval should cancel the Automatic rejection timer.

ref: `https://reviewers.addons.mozilla.org/en-US/reviewers/review/2747436`

- Rejection scheduled on April 11, 2022 (request for sources)
- New upload on April 11, 2022 (& compliance with above request)
- Manual Review and Approval on April 11, 2022
- Automatic rejection after grace period ended on April 25, 2022 of previous versions

@wagnerand @kewisch

**Comment by diox** [comment]
IIRC this is by design - the old versions are no longer "necessary" anyway since a new compliant version was approved, and they are still problematic, so the approval of a new version "unlocks" their automatic rejection.

@wagnerand can confirm.

**Comment by wagnerand** [comment]
Confirming this works as designed.
