### ISSUE TITLE
An error should be thrown when using compatibility at addon create with dictionaries

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19166]
As for https://github.com/mozilla/addons-server/issues/18137 or https://github.com/mozilla/addons-server/issues/18203 
when this JSON is used at addon create (a dict)  {"categories": {"firefox": ["general"]}, "summary":{"en-US":"test test test"},"version": {"upload": "9e4688dfb062404dba9c22b7bdd206d2", "license": "all-rights-reserved", "compatibility": {"firefox": {"min": "61.0", "max": "99.0"}}}} , it should throw the following error:

"This type of add-on does not allow custom compatibility."

**Comment by eviljeff** [comment]
(And moving the validation into the `VersionSerializer` hits the problem that by then a default value has been generated so we can't test with something like `if 'compatibility' in data`)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tried with 
"compatibility": {"firefox": {"min": "102.0","max":"102.*"}} or "compatibility": ["firefox"]

-> I get an error   "This type of add-on does not allow custom compatibility." same now as for PATCH or Versions API when compatibility is used with dictionaries. 

 I verified this on -dev
