### ISSUE TITLE
500 server error when making a request with locales 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19196]
Followup for https://github.com/mozilla/addons-server/issues/8816

Send a PATCH request twice using a non-required field: description, support_email, developer_comments or homepage with "null" in the default locale and another locale:
{"description":{"en-US":null, "ro":null}}

-> the second request throws a server error

![500](https://user-images.githubusercontent.com/33448286/166449264-a0fba319-5ccc-4a7c-91c4-3dd00d101e2c.png)

**Comment by eviljeff** [comment]
https://sentry.io/organizations/mozilla/issues/3245034916/?project=6224627 and/or 
https://sentry.io/organizations/mozilla/issues/3245147362/?project=6224627

**Comment by eviljeff** [comment]
@ioanarusiczki is this only when there are two locales with `null` values?  I assume the add-on was `default_locale='en-US'` and no other localizations before the requests?

**Comment by ioanarusiczki** [comment]
@eviljeff I could reproduce it now only using de default locale - when there are no other translations (locales)
{"developer_comments":{"en-US":null}}
![no other locale](https://user-images.githubusercontent.com/33448286/166467364-647f59e3-fb16-498c-94a9-de2b6eea5d4c.png)

**Comment by ioanarusiczki** [comment]
@eviljeff 
I cannot reproduce this on -dev anymore. 

 I've noticed that the dev hub behavior with these localized fields (besides name and summary) have a different behavior compared to the new API:
when I send a request with PATCH, {"homepage":{"en-US":null, "ro":"https://mail.google.com/"}} I will receive an error 
 "A value in the default locale of \"en-US\" is required if other translations are set."
-> in dev hub I can save url for "ro" but I see "None" in the field until I won't go and add it for the default locale which is en-US. Then going back to "ro" the url is visible.  If I delete the default locale the field for the other locales become blank again. 

The dev hub behavior must be old, my question is if that's ok to stay or should dev hub throw an error too, same way as the API does?
