### ISSUE TITLE
Migrate files to new directory structure

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19193]
Once https://github.com/mozilla/addons-server/issues/11510 is implemented, make a script to migrate existing files to the new directory structure. This needs to work transparently/in a backwards-compatible way.

Logic is likely going to look like:
- Build a list of all known files excluding files that have been migrated already (new files etc)
- Go through the filesystem `files/` directory contents : for each directory:
  - For all files (and just files, not sub-directories) inside that directory:
    - If that file is not in the known list, ignore it
    - If that file is in the list:
      - Create directories for new path if necessary (makedirs)
      - Try linking from old to new path (skip if fail)
      - Once we know the file is linked, update file definition in database, marking the file as migrated

Once we're 100% done with that, all files in the old location (`files/<directory>/<file>` as opposed to `files/<directory>/<directory>/<directory>/<file>`) will be obsolete and we'll be able to remove them.

**Comment by diox** [comment]
Note: we should use `generate_filename()` to generate the new name, if it has been properly updated in https://github.com/mozilla/addons-server/issues/11510 that will be helpful to fix any old inconsistencies, removing any artefacts like the `platform` in the name we used to have.

**Comment by bqbn** [comment]
> * Try linking from old to new path (skip if fail)

What kind of linking is this going to be?

**Comment by diox** [comment]
A hard link, for backwards-compatibility during the migration - the old path will eventually be removed, leaving no trace of the link (that's the `Once we're 100% done with that...` part at the end)

**Comment by ioanarusiczki** [comment]
@diox Should I do a re-check of https://github.com/mozilla/addons-server/issues/19207#issuecomment-1123796442 ?

**Comment by diox** [comment]
I'm currently running the command to migrate the files on dev (*); when it's over I'll do stage. Once it's done, you should pick any old version uploaded before https://github.com/mozilla/addons-server/issues/11510 landed on that env, and see if you can download it. Repeat for different states (deleted, disabled, approved...)

(*) It's likely going to take several hours. I'll then do stage. If it takes too long then we won't run it on prod this week.

**Comment by diox** [comment]
@ioanarusiczki I ran the migration on dev and stage successfully, so you can try inspecting various versions and see if everything is working.

**Comment by ioanarusiczki** [comment]
@diox I looked on both servers, what I've noticed:
- rev tools pages for themes - at click on the file -> it triggers an install , for the rest of the addons it's a download. 
- for deleted files , I downloaded the files and don't seem to be corrupt, they're fine , they're all named "none+version"
![none](https://user-images.githubusercontent.com/33448286/169274989-d206b18c-b85d-4d80-837e-c6a1cf75070d.png)

- I  randomly checked older files on dev and stage, with focus mainly on the rev tools page. Installs are working, the update service is working. I hope it's all fine.

**Comment by diox** [comment]
Ah the `none` part for deleted ones is annoying. Need to think about that...

**Comment by ioanarusiczki** [comment]
@diox Should I file a new issue?

**Comment by diox** [comment]
No, I'll fix it here, hold on.

**Comment by diox** [comment]
@ioanarusiczki I've updated the paths for filenames that had `none` in them because the slug was empty on dev. So you can recheck those: the filename should now have the add-on id in it instead of `none`, and the file should continue to be accessible as normal by users with permission. I'll do the same on stage after.

**Comment by ioanarusiczki** [comment]
@diox Stage also revealed the format for a zip file, looks like it's different:

![stage](https://user-images.githubusercontent.com/33448286/169308966-35572f5b-f3ee-4ecb-bb20-d00c0b83773f.png)

**Comment by ioanarusiczki** [comment]
@diox But I think that should be fine, those cases are quite isolated. I don't see a problem.

**Comment by diox** [comment]
That'd typically happen on pure unlisted add-ons: we use their slug, which is randomly generated. That is expected.

**Comment by ioanarusiczki** [comment]
@diox Ok, that's good to know.
