### ISSUE TITLE
Remove `site_specific` model field ?

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#1920]
The `Addon` model has a `site_specific` field, and has tests for it, but it does not appear to be exposed anywhere in the UI. Do we need it, or can we remove it ?

**Comment by diox** [comment]
cc @jvillalobos who might know about it.

**Comment by diox** [comment]
Actually, it is exposed to *developers* in the technical details section in the devhub, it's a flag called "This is a site-specific add-on" But it doesn't seem to be exposed to users, and I'm not sure it's exposed to reviewers either, but it might be.

Same for the `external_software` / "This add-on requires external software" flag.

**Comment by eviljeff** [comment]
... and prerelease, and admin_review_type and possibly more.

**Comment by jvillalobos** [comment]
Both "Site specific" and "Requires External Software" are exposed in the review queues in the "Additional" column. We can probably do without them, but I'll leave it to @wagnerand to make the call.

**Comment by rctgamer3** [comment]
Both are useful in the list and on the review page. If the whiteboard/review notes or description do not show any info about a third-party application being required to use/test the add-on / it only runs on a particular website, this flag is usually the only/fastest way to tell.

**Comment by eviljeff** [comment]
The developer should be writing in the description if the add-on is site-specific or requires special software - letting the user know is just as important as the reviewer (or could be argued, more so).  If developers are only checking the boxes its a problem.
IIRC the main use for reviewers is skipping reviews that would mean extra work in finding and installing the external software.

**Comment by wagnerand** [comment]
I think "requires external software" is slightly more useful than "site specific". But yes, if they are not exposed to users, their overall value is limited. We could expose them on the add-on's page if it's not too much on an effort.

**Comment by diox** [comment]
Closing since it's actually useful for reviewers.
