### ISSUE TITLE
New uploads are not returned in search results

### ISSUE THREAD

**Issue by SilviaSabou** [mozilla/addons-server#19206]
**Tested with:** FF99, macOS (12.3.1)
                                 
**Preconditions:** User is logged in https://addons.allizom.org/en-US/firefox/ and has a new add-on uploaded.

**Steps to reproduce:**

1. Go to https://addons.allizom.org/en-US/firefox/ .
2. Click on the “Find add-ons” text field and type the new add-on name.
3. Press Enter.

**Expected results**: For step 2 the new add-on name should appear in the Search suggestions drop-down list and for step 3 it should appear in the Search results page.

**Actual results:** The new add-on name is not listed in the Search suggestions drop-down list nor in the Search result page.

**Notes:** Reproducible on -stage.

Please see the screenshots for this issue:
-For step 2
<img width="344" alt="Screenshot 2022-05-04 at 17 02 32" src="https://user-images.githubusercontent.com/86671716/166700673-ad64f2d5-b7c8-487d-a90c-34894e997ade.png">

-For step 3
<img width="1325" alt="Screenshot 2022-05-04 at 17 03 02" src="https://user-images.githubusercontent.com/86671716/166700716-7d3a21f2-6b92-41ea-95be-58bf8a2ccf3e.png">

**Comment by diox** [comment]
@SilviaSabou this should be fixed now.

**Comment by ioanarusiczki** [comment]
@diox Yes, now it looks good to me 👍
