### ISSUE TITLE
Remove `File.filename`, `File.file_path`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19215]
Following https://github.com/mozilla/addons-server/issues/19207 we can remove `File.filename` and `File.file_path` properties - they are there for backwards-compatibility, but we don't have to keep them, we can switch our code to use `File.file.name` and `File.file.path` instead.

Note that those properties do a `self.file` check that might still be useful in some cases, particularly in tests that create dummy `File` instances without an actual file on the filesystem.

**Comment by diox** [comment]
When we do that, we should also change the fixtures to all use the new directory structure for `File` instances.

**Comment by eviljeff** [comment]
> When we do that, we should also change the fixtures to all use the new directory structure for `File` instances.

I don't understand what this means.  (and why fixtures have anything to do with removing shortcut properties on the `File` model.  If it's still a valid thing we can deal with in a follow-up issue.)

**Comment by diox** [comment]
> > When we do that, we should also change the fixtures to all use the new directory structure for `File` instances.
> 
> I don't understand what this means. (and why fixtures have anything to do with removing shortcut properties on the `File` model. If it's still a valid thing we can deal with in a follow-up issue.)

We still have many fixtures using the old directory structure (`<addon_id>/<filename.xpi>` instead of `<last 2 digits of addon_id>/<last 4 digits of addon_id>/<addon_id>/<filename.xpi>`). This is dangerous: it hid a problem when we changed the directory structure that had to be hotfixed (https://github.com/mozilla/addons-server/issues/19243) - the code at the time wasn't handling new directory structure in the update service, and tests were passing because the fixtures used by the corresponding tests were all using the old structure.

Example: https://github.com/mozilla/addons-server/blob/43591247351c2c62c415fac0b383db2005200bfa/src/olympia/amo/fixtures/base/addon_3615.json#L204

So we should switch them all to the new structure. We can do it separately, but I figured this was a good occasion if we were touching that code, especially since the introduction of the `file` field was done to support the switch to the new directory structure in the first place.

**Comment by eviljeff** [comment]
Okay, seems to be an unrelated change from `File.filename` and `File.file_path` then - none of the fixtures needed to be touched for #19528.

**Comment by eviljeff** [comment]
Filed https://github.com/mozilla/addons-server/issues/19577 for fixtures based on comments here

**Comment by ioanarusiczki** [comment]
@diox Should I re-test what's been done for https://github.com/mozilla/addons-server/issues/19207#issuecomment-1122279675 ?

**Comment by diox** [comment]
Yeah, let's do that.

**Comment by ioanarusiczki** [comment]
@diox 
Looks good to me. 
+ I checked the update service - looks good
Android addon installs on -stage -> working
