### ISSUE TITLE
Your add-on failed validation with 1 error.      Received an empty response from the server; status: 502

### ISSUE THREAD

**Issue by MojtabaDaneshi1366** [mozilla/addons-server#19231]
Hello,
When I want to release new version, I get this error message.
What should I do?
![issue](https://user-images.githubusercontent.com/52479925/167916395-29c7361d-5cff-4901-b49f-e6a19912e60c.JPG)

**Comment by MojtabaDaneshi1366** [comment]
Small but useful. :)
I could upload it today.
Thanks.

**Comment by willdurand** [comment]
> Small but useful. :)

Yeah, sorry I should have be more clear about that. We had problems in the past with very large add-ons (like 100MB ZIP files).

**Comment by MojtabaDaneshi1366** [comment]
You're welcome. Don't say sorry. I'm sorry, My English is poor. There was a misunderstanding in my side. :)
Note: I had a problem with my internet connection last night and it may be the reason.
Sincerely
