### ISSUE TITLE
Theme preview remains blocked ( https://bugzilla.mozilla.org/show_bug.cgi?id=1181059  )

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1923]
To better keep track of this https://bugzilla.mozilla.org/show_bug.cgi?id=1181059#c2 , I've created an issue, here.

Verified on AMO-stage, dev and prod using FF45(Win 7).
Issue is constantly reproducing, following the steps from comment 2.

**Comment by andymckay-limited-access** [comment]
We can't reproduce this on Windows or OS X. Does this still occur?

**Comment by ValentinaPC** [comment]
This is not reproducing anymore.
Verified on AMO-dev, stage and prod using FF47(Win 7).
Please see the screencast: 
![hover-theme-block](https://cloud.githubusercontent.com/assets/15685960/16262542/b47aa45c-3878-11e6-80ae-6f2d54bbfc6a.gif)
