### ISSUE TITLE
The addons api doesn't provide an API accessible download API for non-public files

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19237]
The addons api (in particular the [version detail](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail) output) only exposes a url (`file.url`) that relies on browser based cookie auth - i.e. the standard add-ons server view also used for devhub (and other internal tooling). We _don't_ expose a file url that can be used by the api with [api auth](https://addons-server.readthedocs.io/en/latest/topics/api/auth.html#authentication-external).  This only applies to non-public files (not signed and/or not approved) as publicly accessible downloads don't require auth.

The older signing api has it's own [download endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#downloading-signed-files) that's a light wrapper around the same add-ons view but that's (afaik) only referenced within the signing api responses.

Options:
A) enhance the standard download view to support API auth in addition to django auth.  This could be non-trivial as there are many assumptions about api auth applying to urls under /api/ and cookie auth for others.  Essentially it'd be a hack to force checking api auth in a non-api view.
B) link to the signing api's download endpoint in the version detail serializer response (for authenticated developers).
C) re-implement a new download view/sub-view somewhere under the addons api that would possibly also reimplement some of the standard download view (and/or refactor).

**Comment by eviljeff** [comment]
> @eviljeff Could you add some str for qa? I don't find it in the docs.

The `file.url` property of a [version](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail) should be downloadable with api authentication (i.e. using the auth value in a header) for a non-public file (not signed, etc).  Both JWT auth (generated with api keys) and session key auth (the session key value in the header) should work.  

It's not documented as a new api endpoint as it's not part of the api, though the API does return that url.

(does that make sense?)

**Comment by ioanarusiczki** [comment]
@eviljeff Thanks for the info, it does make sense, yes. I managed to do one already, now I'll test around.

**Comment by ioanarusiczki** [comment]
@eviljeff 

- an unlisted approved/disabled file can be downloaded by the owner of the file or admin/users with privileged permissions in admin. The same for a listed disabled file which falls into the non-public category. Other users or non-authenticated cannot access the download. Which is expected reading the results from March https://github.com/mozilla/addons-server/issues/18844#issuecomment-1075306358

- I've noticed that an URL with a .zip file (unsigned yet) is downloaded locally as an .xpi ("response.xpi") but it should be fine as long as the file is not corrupt

 - JWT auth and Session key value are working both for Versions API and  downloading a file. 
 
- I've noticed that when an author is added for an unlisted approved addon -> it has access to the versions API and the download file. If the author is removed, the versions API will respond with a 403 Forbidden , but the download URL https://addons-dev.allizom.org/firefox/downloads/file/254838/67c62fb9309d409aa3bd-1.2.xpi still returns a 200 response when I use the removed author's session ID. -> which I don't think it should happen. Into the browser if I'm authenticated with this author I cannot download the file (trigger the install)

**Comment by eviljeff** [comment]
> I've noticed that an URL with a .zip file (unsigned yet) is downloaded locally as an .xpi ("response.xpi") but it should be fine as long as the file is not corrupt

Is that the same behaviour as via the browser?  (I'm only really interested in consistency)

> I've noticed that when an author is added for an unlisted approved addon -> it has access to the versions API and the download file. If the author is removed, the versions API will respond with a 403 Forbidden , but the download URL https://addons-dev.allizom.org/firefox/downloads/file/254838/67c62fb9309d409aa3bd-1.2.xpi still returns a 200 response when I use the removed author's session ID

it returns a 200 response and actually downloads the file?  Or just an empty 200 response?  Either way, can you file a follow-up?  (it's an edge case really, but worth investigating/fixing)

**Comment by ioanarusiczki** [comment]
@eviljeff 
- from rev tools -> https://addons-dev.allizom.org/firefox/downloads/file/414729/type:attachment/ce5a96e65013428083e6-1.0.2.1.zip, I see a .zip locally, also if I save it from dev hub, https://addons-dev.allizom.org/firefox/downloads/file/414729/ce5a96e65013428083e6-1.0.2.1.zip (same URL as the API provides) it's a .zip too. 

> it returns a 200 response and actually downloads the file? Or just an empty 200 response? Either way, can you file a follow-up? (it's an edge case really, but worth investigating/fixing)

I see a normal response and it results into downloading the addon without errors.

**Comment by eviljeff** [comment]
re: the download name, I think that's more a client detail - the suggested filename is (should be) sent in the response header (as `Content-Disposition: attachment; filename="filename.xpi"` or whatever)  and it's up to the client to use it.  Firefox uses it, but I guess whatever you use to interact with the api didn't.

**Comment by eviljeff** [comment]
> re: the download name, I think that's more a client detail - the suggested filename is (should be) sent in the response header (as `Content-Disposition: attachment; filename="filename.xpi"` or whatever) and it's up to the client to use it. Firefox uses it, but I guess whatever you use to interact with the api didn't.

Actually, looks like this header either doesn't get sent or is lost along the way when it goes through the CDN, etc.  I guess Firefox just takes the name from the url.
