### ISSUE TITLE
Remove sync_objects_to_basket and associated code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19238]
`sync_objects_to_basket` and associated code is behind a waffle switch, `basket-amo-sync`, that was never turned on in production. It was intended, as the name suggests, to sync objects (add-ons, users) data to basket which would then maintain them in Salesforce, but we moved away from Salesforce before this was enabled.

It's unlikely we'll ever pick up that work again as we've changed strategy with the new contact management system and instead of doing the queries there, we run a query against STMO and the AMO database and then export the ids into the marketing tool we use.

So let's remove all that code...

**Comment by diox** [comment]
QA: should be a transparent change, you can verify that changes to a user or add-on are saved correctly.

**Comment by ioanarusiczki** [comment]
@diox I did not see changes in behavior for user/add-on fields on AMO stage, FF100(Win10).
