### ISSUE TITLE
Refactor/de-dupe author email code

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19236]
To fix #19216 I replicated the devhub code to send relevent emails to add-on authors in the API. Having the same functionality duplicated is generally a "bad thing" so we should refactor to move the common code into a single place.

QA: check the emails for #19216 still work, and the same emails are sent when authors are managed via devhub.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I verified on -dev the e-mails sent and it should be alright, emails are sent at confirmation, an e-mail is sent when an author is deleted (already confirmed or pending confirmation) and email is sent when the role is edited.
