### ISSUE TITLE
Re-implement udpate service in Django

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19245]
Since the beginning of time, the update service, aka versioncheck, has been built separately from the rest. For perceived performance & scalability reasons, it's a single self-contained wsgi app that doesn't use Django so it doesn't benefit from our models etc.

We have had bugs from time to time caused by this separation, because it was missing some internal logic - the most recent being #19243: the recent move to a new directory structure caused that bug because the update service didn't take the new filenames into account when generating download URLs.

It's time for the madness to end. Move the service into the main app, using the regular django wsgi endpoint, our models, the ORM, urls reversing etc. It's behind the CDN, so we should be ok if we're careful enough. We should still ensure it does everything in a single efficient query (always on the replica), using `select_related()`, avoiding transforms (including translations!) and using `.only()`/`defer()` to only fetch what we need, adding some tests with `assertNumQueries()`.

Development and deployment should be coordinated with ops, maybe keep `services/` intact at the beginning to ensure smooth rollout if necessary. The nginx config will obviously need to be adjusted - it might make sense to just use the same as the main app while ensuring this only works on the specific domain (and that the domain can't be used to serve regular AMO content). 

Note that this should make the entire local config introduced in #19045 obsolete.

**Comment by diox** [comment]
qa: not needed because the code is not reachable yet

**Comment by bqbn** [comment]
> It'll probably be on the existing domain initially, but we could move it to services.a.m.o. instead in the long term ?

@diox,  what does "move it to services.a.m.o" mean? Does it mean services.a.m.o is not using regular django wsgi endpoint either?

**Comment by diox** [comment]
It is. I'm saying we could move versioncheck to `services.a.m.o.` instead of its own domain eventually, just to make things simpler. But I'm not even sure we want to.

**Comment by bqbn** [comment]
Yeah, I don't see a reason to do that at this point of time. Maybe it will change later.
