### ISSUE TITLE
Developer Hub - Developer News: & is shown as &amp; in URLs

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#19265]
`&amp;` is converted to `&amp;amp` on Developer Hub - Developer News

https://addons.mozilla.org/en-US/developers/addons

```html
<a href="https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/" target="_new">
        Manifest v3 in Firefox: Recap &amp;amp; Next Steps
      </a>
```

https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/

```html
<h1 class="entry-title">Manifest v3 in Firefox: Recap &amp; Next Steps</h1>
```

**Comment by diox** [comment]
Annoyingly, content from the API comes out already HTML-escaped. I don't really want us to start considering it's always safe though, I would rather unescape it if it is escaped, store in the database, then escape it when rendering HTML as normal...

**Comment by ioanarusiczki** [comment]
@diox Looks good now on -dev, FF100(Win10). 

![fixed](https://user-images.githubusercontent.com/33448286/172399383-3a104b9d-1d41-49f9-bdc8-bc48bd6d37ee.png)
