### ISSUE TITLE
[Android] Language drop-down does not work in Search Results page for one or no results

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1928]
Steps to reproduce:
1. Load AMO-stage on your Android device
2. Make a search that returns one or no results
3. Try to change the language

Expected results:
User can change the language.

Actual results:
User cannot change the language.

Notes/Issues:
This is reproducing in Login/Register page too. I guess it has to do with the size of the page content or display dimensions. (when user has to scroll down a bit to get to the drop-down, the language can be changed - just an assumption) 
Verified on FF45 (Android 5.0.1). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue: 
![2016-03-17_1253](https://cloud.githubusercontent.com/assets/15685960/13843943/54418874-ec3f-11e5-9d13-d57538750bc1.png)

**Comment by andymckay** [comment]
Assuming we should won't fix this in favour of the shiny new mobile pages coming in addons frontend.

**Comment by ValentinaPC** [comment]
Indeed, it was fixed, and the language drop-down is shown.
