### ISSUE TITLE
The abuse report API throws a 500 error if some field values are not strings

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19286]
Follow up for #19080

### Describe the problem and steps to reproduce it:
Send a request to the  [/api/v5/abuse/report/addon/](https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#post--api-v5-abuse-report-addon-) with any of the following fields set as: 
- `"addon": 621556` - value as `int` instead of `str`
- `"addon_install_source": {"value": "app:profile"}`
- `"addon_install_method": {"value": "rtamo"}`

### What happened?
A 500 server error

### What did you expect to happen?
A 400 bad request error

**Comment by diox** [comment]
https://sentry.io/organizations/mozilla/issues/3125135240/?query=is%3Aunresolved

```
TypeError: unhashable type: 'dict'
  File "rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "olympia/abuse/serializers.py", line 151, in to_internal_value
    data['addon_install_source'] = self.handle_unknown_install_method_or_source(
  File "olympia/abuse/serializers.py", line 132, in handle_unknown_install_method_or_source
    if value not in reversed_choices:
```

The abuse API has extra code to accept unknown `addon_install_source` / `addon_install_method` that is problematic in this case. We should have a `try/except` around `TypeError` when doing the `if value not in reversed_choices` check in https://github.com/mozilla/addons-server/blob/a265164217b400ce86a32ae33ff8c89529907a00/src/olympia/abuse/serializers.py#L132.

**Comment by eviljeff** [comment]
> The abuse API has extra code to accept unknown `addon_install_source` / `addon_install_method` that is problematic in this case. We should have a `try/except` around `TypeError` when doing the `if value not in reversed_choices` check in
> 
> https://github.com/mozilla/addons-server/blob/a265164217b400ce86a32ae33ff8c89529907a00/src/olympia/abuse/serializers.py#L132
> .

😕 I'm surprised this extra code was needed - I would have thought the ReverseChoiceField would have returned a validation error for an unknown choice.

**Comment by diox** [comment]
> I'm surprised this extra code was needed - I would have thought the ReverseChoiceField would have returned a validation error for an unknown choice.

That's is exactly why that condition is here: in the abuse API, we don't want a validation error for unknown values, we want to accept them and turn them into `other`. This is because new values might be added to Firefox without our knowledge (it has happened in the past) and we don't want to abuse report to fail to be sent because of this.

**Comment by eviljeff** [comment]
Ah.  
Well, a validator class won't work if the value needs to change, though if I was writing it I'd lean to doing it in subclass of ReverseChoiceField rather than the serializer but 🤷

**Comment by shribyte** [comment]
Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-105
