### ISSUE TITLE
Some fully blocked add-ons are not disabled

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19288]
Add-ons that have a block range of `0-*` should also have a status of `STATUS_DISABLED`. While I believe this is done correctly for new blocks, a lot of the initially imported blocks (from kinto) look like they have the wrong status, e.g. `STATUS_INCOMPLETE`. We should update the status for those manually in order to avoid going through these files for code-search. The amount of affected files probably introduces significant delay and some unnecessary cost. 

Query for reference:
```sql
SELECT
    COUNT(DISTINCT a.id)
FROM
    addons a
    JOIN blocklist_block b ON b.guid = a.guid COLLATE utf8mb4_unicode_ci
WHERE
    a.status IN (0, 4)
    AND min_version = "0"
    AND max_version = "*";
```

**Comment by eviljeff** [comment]
from slack
```
mysql> SELECT
    ->     a.status,
    ->     COUNT(DISTINCT a.id)
    -> FROM
    ->     addons a
    ->     JOIN blocklist_block b ON b.guid = a.guid COLLATE utf8mb4_unicode_ci
    -> WHERE
    ->     min_version = "0" AND max_version = "*"
    -> GROUP BY a.status;
+--------+----------------------+
| status | COUNT(DISTINCT a.id) |
+--------+----------------------+
|      0 |               518490 |
|      5 |               577046 |
|     11 |                 1678 |
+--------+----------------------+
```

**Comment by eviljeff** [comment]
> a migration with a couple of big `UPDATE` might do the trick. 

there are some that have a public status so I don't think we can get away without doing it properly (e.g. a `process_addons` task using `delete_addons`) so the correct celery tasks get fired to update ES

**Comment by eviljeff** [comment]
QA: this is a management command that is executed with `./manage.py process_addons task=disable_blocked_addons`

These are the add-on ids on dev that match the sql above, so should be disabled after the command has run. Just ask and we can execute the command (I'm not sure if you want to check anything before hand).

Creating new data to verify would be difficult as new Block objects now disable the add-on at the time.

> +--------+
| id     |
+--------+
|   6081 |
|   6584 |
|   9361 |
|   9978 |
| 285546 |
| 349281 |
| 494683 |
| 494977 |
| 495012 |
| 495113 |
| 496307 |
| 616869 |
| 616912 |
| 616913 |
| 616915 |
| 618396 |
| 618780 |
| 618822 |
| 618826 |
| 618827 |
| 618875 |
| 618931 |
| 618932 |
| 619673 |
| 619674 |
| 619675 |
| 619676 |
| 619677 |
| 619678 |
| 619680 |
| 619684 |
| 619696 |
| 619697 |
| 619708 |
| 619732 |
| 619736 |
| 619738 |
| 619739 |
| 619741 |
| 619749 |
| 619751 |
| 619752 |
| 619753 |
| 619755 |
| 619761 |
| 619769 |
| 619772 |
| 619889 |
| 619891 |
| 619892 |
| 619905 |
| 619907 |
+--------+

**Comment by AlexandraMoga** [comment]
@eviljeff I've looked through some of these add-ons to see their current status - mostly are Approved or Incomplete (i.e. they have their versions disabled but the add-on itself is not disabled).

You can run the command on -dev and I'll check these Ids again afterwards to see if the status changes to disabled.

**Comment by eviljeff** [comment]
I've ran the command on -dev.  Looks like it worked from the logging, at least.

**Comment by ioanarusiczki** [comment]
@eviljeff It should be ok, I checked some ids and all display "Disabled by Mozilla" status into dev hub and admin.
