### ISSUE TITLE
Some fully blocked deleted add-ons are not in `DeniedGuid`s

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19289]
It looks like some previously deleted blocked add-ons (with range `0-*`) have not been denied for resubmission (`DeniedGuid` entry). We should add those.

```sql
SELECT
    COUNT(DISTINCT a.id)
FROM
    addons a
    JOIN blocklist_block b ON b.guid = a.guid COLLATE utf8mb4_unicode_ci
    LEFT JOIN denied_guids d on d.guid = a.guid
WHERE
    min_version = "0" AND max_version = "*" AND a.status = 11 AND d.guid IS NULL;
```

**Comment by diox** [comment]
As https://github.com/mozilla/addons-server/issues/19288 we could use a single migration to do this - especially as there aren't that many of them.

**Comment by diox** [comment]
I just verified this myself: dev was missing 2 guids before, they are now present.

**Comment by ioanarusiczki** [comment]
@diox Thanks, I will mark it qa not needed then.
