### ISSUE TITLE
Don't return a 200 response when custom_license is not en-US at addon create

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19313]
While testing around https://github.com/mozilla/addons-server/issues/18235 ->
[docs ](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#create) specify "the default locale for [version release notes](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-create-request) and custom license text is fixed to en-US." 

When I used into JSON at addon creation another locale instead of en-US `"custom_license": {"name": {"it":"test"},"text":{"it":"test"}`
-> a 200 response is returned but the name and text are null.  Dev Hub won't display the name and text either but on frontend if I switch to "it" I will see what's been sent through the api. 

Expected result:
Maybe an error should be thrown to use only "en-US" for "custom_license".

**Comment by eviljeff** [comment]
> Maybe an error should be thrown to use only "en-US" for "custom_license".

You should be able to use other locales... but there should be an `en-US` translation too.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this on -dev, I receive a 400 Bad Request now. 
"A value in the default locale of \"en-US\" is required."
