### ISSUE TITLE
Show search suggestions if results are found for a searchterm

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#1933]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/
2.Enter "webdeveloper" search term in searchbox
3.Hit Enter

Expected results:
If there are results after the search , then we should display search suggestion in the drop down menu under searchbox

Actual results:
There are terms for which we return results, but no search suggestions

Please see screencast for this bug: http://screencast.com/t/Pc5tBXMkT6n

**Comment by andymckay-limited-access** [comment]
I don't follow this bug, @krupa will have a look.

**Comment by EnTeQuAk** [comment]
I somehow believe this is more a feature than a bug but please feel free to correct me if I'm wrong. Closing this ticket since this will be something that will be re-implemented with the new addons-frontend and a proper API, nicer, better and awesomer.
