### ISSUE TITLE
There is no difference between content rejection and code rejection

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#19336]
### Describe the problem and steps to reproduce it:
When we content delay reject after two weeks, when it gets auto rejected it's counted as a code rejection, not a content one.

### What happened?
When a content delayed rejected add-on gets auto rejected, after 2 weeks, in database the action is set as rejected instead of reject content.

### What did you expect to happen?
A content delayed add-on should get auto rejected with the action for reject content, not rejected.

**Comment by ioanarusiczki** [comment]
@eviljeff 
I "Content reject scheduled" a couple of addons on -dev and set the delay for 1 day so I can see tomorrow what happens.

**Comment by ioanarusiczki** [comment]
@eviljeff When Automatic rejection after grace period ended -> "Content rejected "is displayed

![Content rejected](https://user-images.githubusercontent.com/33448286/181254858-a969c2ef-9201-4ba8-941c-45af191be6c2.png)

Verified on AMO dev.
