### ISSUE TITLE
Move CELERY_RESULT_BACKEND to redis

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/addons-server#1934]
Currently set to 'amqp' which causes issues and not recommended for production use [1]. Related to  https://github.com/mozilla/addons-server/issues/1653

[1] http://docs.celeryproject.org/en/latest/configuration.html#amqp-backend-settings

**Comment by diox** [comment]
Has there been any progress on this ? I'd like to re-enable post-request-task but I think we should take care of that first.

**Comment by jasonthomas** [comment]
Once https://github.com/mozilla/addons-server/pull/2654 lands it will be configured on -dev. I will prepare stage and prod with it for the next deploy.
