### ISSUE TITLE
Video DownloadHelper shows a massive drop in `average_daily_users`

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19341]
### Describe the problem and steps to reproduce it:
1. Open the detail page for Video DownloadHelper https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/
2. Check the User count in the stats card

### What happened?
The add-on has only 1 user

### What did you expect to happen?
The add-on used to have a much higher number of users 

### Anything else we should know?
The detail API for this add-on returns `"average_daily_users":1`
This is relevant only on AMO prod.

**Comment by willdurand** [comment]
The issue has been identified: it looks like we have GUIDs with different case in BigQuery, which causes some add-ons to get updated with the wrong values because the `guid` field (not sure of the name) is case insensitive.

**Comment by AlexandraMoga** [comment]
This issue looks fixed on prod:

![image](https://user-images.githubusercontent.com/31961530/173510625-88735e99-59b2-4b4f-8663-4907cc5feaae.png)

Also, the user count for the rest of the add-ons seem to be unaffected.
