### ISSUE TITLE
Please consolidate the queues we have for async jobs

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#19344]
### Describe the problem and steps to reproduce it:
There are currently more than a dozen of queues we use for async jobs, e.g. `addons`, `priority`, `adhoc`, and etc. Some of them may have been deprecated, such as `limited`.

Can you help consolidate the queues? Less queues means less management effort and less chance to use the wrong queue for a purpose.

### What happened?
There are too many queues for async jobs.

### What did you expect to happen?
Have the queues consolidated.

### Anything else we should know?
The queues we have [on record](https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/amo/puppet/modules/olympia/manifests/celery.pp#L32-L74) are:
* addons
* adhoc
* amo
* api
* bandwagon
* celery
* cron
* crypto
* devhub
* default
* files
* images
* limited
* priority
* ratings
* reviewers
* search
* stats
* tags
* users
* zadmin

**Comment by diox** [comment]
The following queues are obsolete, we should be able to remove them:
`api`, `files`, `celery`, `limited`, `stats`

In addition, we could group the following together:
- `default`, `search` (keeping only `default`)
- `amo`, `addons`, `bandwagon`, `images`, `ratings`, `tags`, `users` (keeping only `amo`)
- `crypto`, `reviewers` (keeping only `reviewers`)

With that change, we should only have a single service per queue. `adhoc` should be limited to 1 worker, `reviewer` to 2. `devhub` should keep its `--max-tasks-per-child=10` (`images` had that too but that's not needed there).

**Comment by diox** [comment]
QA: this should be a transparent change... that can affect the whole site. Nothing in particular to test, so I'm marking as qa- and if anything is wrong it should be caught by regular testing/sanity checking of the site.

**Comment by bqbn** [comment]
> With that change, we should only have a single service per queue. `adhoc` should be limited to 1 worker, `reviewers` to 2. `devhub` should keep its `--max-tasks-per-child=10` (`images` had that too but that's not needed there).

@diox, do you know or remember why `images` had `--max-tasks-per-child=10` before?

**Comment by diox** [comment]
> @diox, do you know or remember why images had --max-tasks-per-child=10 before?

I don't know, it was probably set up years ago before I joined. Maybe a memory leak prevention measure, as it would force the worker to restart after 10 tasks processed. We should monitor the workers closely once this goes live and adjust if necessary.

> Except for the olympia-priority queue, which has 2 services, i.e. priority and amo.

How do you feel about splitting them, for consistency ?

**Comment by bqbn** [comment]
> How do you feel about splitting them, for consistency ?

We'll do that.
