### ISSUE TITLE
auto-detect and set target_locale for langpacks

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19355]
Follow-up from #15353 - we detect the target_locale for dictionaries but not langpacks.  We should do something similar for langpacks

**Comment by ioanarusiczki** [comment]
@eviljeff 
I submitted lang packs with dev hub and the new API (PUT or POST) and checked that at creation of a new lang pack the target_locale is present in [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/621679/change/) -> this is happening now 
The field from admin can be edited by the admin. 

I tried to make a new version upload for an older lang pack -> the field remains empty -> it is populated with the locale from the langpack_id (inside manifest.json) only when a new locale is created. 
Also, when I change the langpack_id and submit a new version -> nothing changes. 

I think this should be ok, but if not , let me know.

**Comment by eviljeff** [comment]
> Also, when I change the langpack_id and submit a new version -> nothing changes (the target locale from create is displayed)

We should probably error for that, but langpacks are only submitable by releng anyway, so there's no much risk of accidents.
