### ISSUE TITLE
JS error when tapping review rating stars on Android

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1935]
Prerequisites:
Set remote debugging for Android (https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE )

Steps to reproduce:
1.Sign in to AMO-stage page on your Android device
2. Go to an Add-on details page
3. Load Reviews page
3. Go to "Add a Review" section
4. Tap some stars to rate the add-on 
5. Observe the messages from the console

Expected results:
There are no errors.

Actual results:
There is a JS error in the console: "TypeError: e.originalEvent.touches[0] is undefined".

Notes/Issues:
Verified on FF45(Android 5.0.1). Issue is reproducing on AMO-stage, dev and prod.
Screencast for this issue: 
![2016-03-17_1510](https://cloud.githubusercontent.com/assets/15685960/13848306/db7882ba-ec59-11e5-8c53-705d74eb5473.png)

**Comment by muffinresearch** [comment]
I'll take a look at this tomorrow or early next week when I have a test device handy.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (Android 5.0.1).
Postfix screenshot: 
![2016-03-22_1606](https://cloud.githubusercontent.com/assets/15685960/13954156/42ab96ec-f048-11e5-818a-89a6ddeb2130.png)
