### ISSUE TITLE
Addons can be created without name/summary in the default-locale

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19366]
STR:
1. I used a dummy extension with name and summary , also an addon that has default_locale into manifest.json
2. Create the addon using PUT or POST with the following JSON that contains name and summary in other locale than en-US

`{
    "categories": {
        "firefox": [
            "other"
        ]
    },
    "support_email": {
        "it": "rusiczki.ioana@gmail.com",
        "ro": "rusiczki.ioana@gmail.com",
        "en-US": "rusiczki.ioana@gmail.com"
    },
    "developer_comments": {
        "it": "test"
    },
    "summary": {
        "it": "en-US"
    },
    "name": {
        "it": "en-US"
    },
    "description": {
        "it": "en-US"
    },
    "homepage": {
        "it": "https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#create",
        "ro": "https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#create"
    },
    "version": {
        "upload": "dc4f420f404b4aa5a429d0f6eb442a93",
        "custom_license": {
            "name": {
                "it": "test"
            },
            "text": {
                "it": "test"
            }
        }
    }
}`

Expected result:
An error should be thrown - perhaps that the default-locale must be declared in the JSON

Actual result:
The default locale is considered en-US but it has no name or summary in en-US

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified on -dev, -stage and this is no longer reproducible. I get a 400 Bad request -> "A value in the default locale of \"en-US\" is required." 

**_Note:_** I've noticed with 2 addons a pattern, I tried with Decentraleyes and uBlock Origin from prod an upload and create -> after I get the uuid , the addon create API throws a 400 "Upload not valid" if I try to create immediately.  I must wait for a while and then send the request and it will work as expected.  I don't know if that's expected. When the addon is a dummy this is not reproducible, but  Decentraleyes is 6,7 MB , UBlock 2,8 MB.

**Comment by eviljeff** [comment]
@ioanarusiczki 
> **_Note:_** I've noticed with 2 addons a pattern, I tried with Decentraleyes and uBlock Origin from prod an upload and create -> after I get the uuid , the addon create API throws a 400 "Upload not valid" if I try to create immediately. I must wait for a while and then send the request and it will work as expected. I don't know if that's expected. When the addon is a dummy this is not reproducible, but Decentraleyes is 6,7 MB , UBlock 2,8 MB.

#19376 also talked of getting "Upload not valid" - and I couldn't reproduce locally - so it may be the same thing.  If it's happening with large, complex, add-ons and not dummy submissions it may be a lag somewhere (database writes?) but it's difficult to say.  It sounds like something we'd like to get to understand, at least, so can you log a specific issue for it?

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, I'm going to look over https://github.com/mozilla/addons-server/issues/19376#issuecomment-1187165543 too and reply on it. 
Could be the same thing but meanwhile I filed https://github.com/mozilla/addons-server/issues/19511
