### ISSUE TITLE
l10n extraction is broken

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19364]
https://github.com/mozilla/addons-server/pull/19361 has failing CI because of

```
>>> Working on: /home/circleci/project/locale/en_US/LC_MESSAGES/django.po
Error: E103: missing left curly-brace: }}
507:msgid "You must provide an object of {{lang-code:value}}."
508:msgstr "You must provide an object of {{lang-code:value}}."
```

logged https://github.com/mozilla/dennis/issues/134

**Comment by eviljeff** [comment]
I couldn't work out a way to escape the charactors to avoid the error (might have overlooked something).

If we can't fix quickly-ish the other workaround is not to do [`self.fail('no_dict')`](https://github.com/mozilla/addons-server/blob/master/src/olympia/api/fields.py#L170), but to `gettext` and raise the exception ourselves without a `.format` (like it was before I cleaned it up)

**Comment by AlexandraMoga** [comment]
@eviljeff is there any QA needed for this?
