### ISSUE TITLE
Text in "most popular" sidebar is cut off

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#1936]
The text in the right-hand side list seems to have a set height that is too small; it cuts off the "g" in the text here:

<img width="185" alt="screenshot 2016-03-17 17 27 21" src="https://cloud.githubusercontent.com/assets/90871/13858545/6fd9d2b8-ec7f-11e5-9f4f-5bd191be5876.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-01_1055](https://cloud.githubusercontent.com/assets/15685960/14201103/58f190d4-f7f8-11e5-9e37-c5d7003aba7b.png)
