### ISSUE TITLE
Carousel should be enabled by default on freshly set up development environment (and we should add docs for it)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#1937]
Enabling the carousel at the top of the page helps when working on the AMO front-end but isn't enabled by default when a new Docker environment is set up. We should have it enable `Olympics` and `Holiday` by default (known to work locally as mentioned in #1866) so developers have a more "normal" environment by default.

We should also document how to enable this feature in the docs, as I couldn't find it.

**Comment by EnTeQuAk** [comment]
Closing as all this is going to be removed with :fire: very very soon :tm:
