### ISSUE TITLE
Throw an error when the target_locale is not the same

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19380]
Followup for https://github.com/mozilla/addons-server/issues/19355#issuecomment-1158932065

STR:
1. Submit a langpack and check the[ target_locale field](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/621679/change/) from admin -> the locale should be displayed 
2. Submit a new version with a different target_locale in the manifest

Expected result:
An error should be displayed - that the target_locale do not match

Actual result:
The target_locale of the first version is displayed in admin, no errors at submission

**Comment by eviljeff** [comment]
note: the fix for this should cover devhub and the api submission methods (a validation error is thrown at a lower level)

**Comment by ioanarusiczki** [comment]
@eviljeff 

On dev hub: 

![error changing langpackid](https://user-images.githubusercontent.com/33448286/189669374-aeeb31d3-19cb-4a35-93ae-68565e89536d.png)

Using the API:

![The API response](https://user-images.githubusercontent.com/33448286/189669425-bd8423a1-ad16-4b69-90ec-572e7e443328.png)
