### ISSUE TITLE
Explicitly specify a field when using `random_score` in Elasticsearch

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19386]
When we sort using `random` order in the API, under the hood we use `random_score` ordering in ES with a seed to guarantee "stable" randomness for the day - the idea being that the ordering for a given query should stay the same for 24 hours, so that most content doesn't jump around when reloading the page. This can be seen if a shelf present on the homepage uses the random ordering (such as the "recommended" one currently in prod).

The [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-function-score-query.html#function-random) recommends the following:
> It was possible to set a seed without setting a field, but this has been deprecated as this requires loading fielddata on the _id field which consumes a lot of memory.

We do currently omit the `field` parameter. We can just use our own `id` instead to avoid this deprecation warning in our logs. It should be a totally transparent change.

**Comment by diox** [comment]
This should be a completely transparent change. As noted in the description, for a given search API query with `sort=random` the randomness should stay the same during the entire day and change at midnight UTC.

**Comment by ioanarusiczki** [comment]
@diox I verified the search results for the search results below on AMO dev - frontend: 

https://addons-dev.allizom.org/en-US/firefox/search/?page=2&sort=relevance&type=extension
https://addons-dev.allizom.org/en-US/firefox/search/?promoted=recommended&sort=random&type=statictheme 

The order of addons/themes changed only the next day which is the expected result.
