### ISSUE TITLE
Image uploads in devhub stuck on "Image changes being processed"

### ISSUE THREAD

**Issue by GChristensen** [mozilla/addons-server#19396]
### Describe the problem and steps to reproduce it:

I'm trying to upload a new screenshot for the add-on: https://addons.mozilla.org/en-US/firefox/addon/add-torrent-to/

Steps to reproduce: 
1. Open "Edit Product Page" of an add-on.
2. Press edit button in the Images section.
3. Add a new screenshot.
4. Press the "Save Changes" button.

The uploaded image is stuck in the "Image changes being processed" stage.

### What happened?

After I press "Save Changes" button at the Images section, the uploaded image is stuck in the "Image changes being processed" stage.
![being processed](https://user-images.githubusercontent.com/170405/175260162-03f0e49f-e783-48f2-9712-f3a3209e7b38.png)

The uploaded images are in the archive below.
[images.zip](https://github.com/mozilla/addons/files/8965671/images.zip)

### What did you expect to happen?

Images being loaded normally.

**Comment by ioanarusiczki** [comment]
@diox 

I verified this on AMO dev - FF101(Win10) , the images can be uploaded and displayed now. 

![images loading](https://user-images.githubusercontent.com/33448286/175892713-554abee5-e5e2-4070-a0c0-f641679b181a.png)
