### ISSUE TITLE
Show `UserHistory` in django admin

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19429]
We have a `UserHistory` model holding user email changes. We should expose that in the admin, probably as part of the `UserProfile` for that specific user.

If we expose that model separately, we'll need to have a way to search by (old) email and by user id.

**Comment by ioanarusiczki** [comment]
@diox @wagnerand 

I went on this [particular user](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641572/change/?_changelist_filters=q%3Drusiczki.ioana%2540gmail) and there is User History under Email 

If I click it there's 2 e-mail addresses with the same id -> I remember I made some testing a while ago and I had to change the primary email address from fxA -> reason why I see here the 2 email addresses displayed. 

All the other users I've checked display 0 for User History.

There's also a typo "2 user historys"  but I don't think it matters in admin.
