### ISSUE TITLE
Exclude delayed-rejected versions from the scanner (and mad?) queue(s)

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19436]
Delay-rejected versions do not need to be reviewed and therefore should be excluded from the scanner queue and probably the mad queue as well.

@ioanarusiczki STR would be quite similar to https://github.com/mozilla/addons-server/issues/19371#issuecomment-1173793374, but we don't need to test that delayed-reject actually works and that entries appear in the _Pending Rejection_ queue. Would this description work for you or do you want me to write STR?

**Comment by ioanarusiczki** [comment]
@wagnerand Will work 👍

**Comment by ioanarusiczki** [comment]
@wagnerand @diox 

I verified this on AMO stage - > when I reject with a delay a version , the addon is no longer present in /scanners or /mad queues.
