### ISSUE TITLE
After submitting a listed review, load/redirect to the review page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19437]
### Describe the problem and steps to reproduce it:
When submitting a listed review, we should load/redirect to the (same) review page. 

### What happened?
We currently load a queue page, I believe it's the "Auto-approved add-ons" page, which is slow to load and probably not used much at the moment.

### What did you expect to happen?
Load the review page we submitted the review for.

### Anything else we should know?
We are already doing that for unlisted review submissions.

**Comment by diox** [comment]
Note that staying on the review page prevents auto-approval... so the reviewer would need to remember to close the tab/navigate away...

**Comment by wagnerand** [comment]
Ack, but unless I am missing something, this should not be an issue here. We are already doing this for unlisted, which can also pending approval, so everyone should be aware. Also, in most cases, the review decision will be an action that actually resolves the pending auto-approval. Lastly, I don't expect reviewers to idle on that page for much longer after their action is done.
