### ISSUE TITLE
Cannot approve non-latest unlisted version awaiting approval

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19438]
### Describe the problem and steps to reproduce it:

In contrast to listed versions, unlisted versions can have several versions awaiting manual approval.

### What happened?
The reviewer tools only allow the manually approve the latest submission, forcing reviewers to reject older versions in any case and asking developers to resubmit older versions with a higher version number, if those need to be signed, which could cause this issue again, unless submission and review happens one by one.

### What did you expect to happen?
Ideally the reviewer tools allow manually approving older pending versions. We could potentially follow the listed behavior and disable pending versions when a new one get submitted, but that would be a significant change in behavior that developers would not expect and are not used to.

Let's explore the first option first and implement that, if feasible.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
> The old manual 'Approve' option is still available and, if used, will approve only the latest version as before.

It's a bit unnecessary to have both but it's also not breaking anything and I don't want to add more changes than really necessary. Let's keep it like that and reviewers can use it or ignore it.

> One thing I've noticed with the new 'Approve Multiple Versions' is that it requires a 'Reason' to be specified if you want to submit your review. The old manual 'Approve' option doesn't require a Reason. @wagnerand is this a problem?

Could you file a follow-up for that, please? Approvals don't need a reason.

**Comment by AlexandraMoga** [comment]
> Could you file a follow-up for that, please? Approvals don't need a reason.

Filed https://github.com/mozilla/addons-server/issues/19488
