### ISSUE TITLE
Don't include non-public add-ons in the ES index

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19445]
We currently index all add-ons in our ES index, regardless of whether there are any approved listed versions, if the addon is enabled or disabled, or its deleted status; then filter the non-public add-ons out before returning the results.  This was done for `<`historical reasons`>`.  Although it makes the indexing code a little simpler - index everything without working out if we should - it's inflating the ES index size for no good reason so lets stop doing that.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I made some testing, these are my results: 

1. Public addon is suggested in results, made it invisible -> I waited for a while and then the addon was no longer suggested by autocomplete. 
2. New submitted addon , not approved is not suggested -> then approved , will show up in search
3. Addon disabled from dev hub / by mozilla -> won't be suggested 
4. Addon deleted is no longer suggested by autocomplete 
5. Addon [blocked ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/621899)-> when I search for "Custom Scrollbars_index" the autocomplete still displays it, the detail page throws a 404. I can't tell why( maybe it has to do with the cache feature) , but I remember this was reproducible with addons that were deleted from the user profile (from fxA)

**Comment by eviljeff** [comment]
>     5. Addon [blocked ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/621899)-> when I search for "Custom Scrollbars_index" the autocomplete still displays it, the detail page throws a 404. I can't tell why( maybe it has to do with the cache feature) , but I remember this was reproducible with addons that were deleted from the user profile (from fxA)

Interesting.  It's possible we don't filter it out, or miss the reindexing trigger when it's blocked.  Can you log a follow-up for investigation.  If you can reproduce on stage it won't be a particularly high priority though.

Fwiw, the patch shouldn't lead to any differences in the results - the filtering to only show public add-ons is still present in the search code - so it's missing add-ons that is more an indication of an immediate regression

**Comment by ioanarusiczki** [comment]
@eviljeff I tried again with the blocked addon -> I could not reproduce the issue described for "Custom Scrollbars_index" on -dev or -stage. I don't know what happened in that case but I could file an issue for investigation.

**Comment by eviljeff** [comment]
If you can't reproduce it I don't think we'd be able to investigate much, so no need to file anything unless you manage to replicate it in the future.
