### ISSUE TITLE
Number of requests for the ES cluster doubled right after 2022.07.14 push

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#19463]
### Describe the problem and steps to reproduce it:
We see that the number of requests for the ES cluster doubled almost immediately after the 2022.07.14 push. 

<img width="803" alt="Screen Shot 2022-07-14 at 9 49 27 AM" src="https://user-images.githubusercontent.com/2209111/179046710-86366c03-eace-4519-a720-25ce2dba7acb.png">

### What happened?
The ES cluster was upgraded to v7 on 7/11/2022. Right after today's push (tag 2022.07.14), we see the number of requests for the ES cluster doubled. And meanwhile, the number of requests for the website hadn't increased, so this wasn't caused by increased amount of traffic to the website.

### What did you expect to happen?
The number of requests for the ES cluster does not increase when the traffic to the website hasn't increased.

### Anything else we should know?
n/a

**Comment by diox** [comment]
It looks like this is caused by https://github.com/elastic/elasticsearch-py/pull/1623. See https://github.com/elastic/elasticsearch-py/issues/1676 for more people having this issue - elasticsearch client now does an extra request when connecting to verify the host.

This shouldn't cause scalability issues, as the extra request being made is a simple `info()` request, but this is annoying for sure, it's an extra roundtrip we don't need...

**Comment by bqbn** [comment]
We should patch it if possible IMHO. The added RTT feels like a time bomb that is going to trigger during some busy times.

**Comment by eviljeff** [comment]
Reading https://github.com/elastic/elasticsearch-py/issues/1676 this was introduced in elasticsearch-py 7.14.0, so we could pin to 7.13.0 for the 7.x branch.  It appears in 8.x they've switched to verifying the response is from an "official" ES by [checking a header value instead](https://github.com/elastic/elasticsearch-py/blob/8.3/elasticsearch/_sync/client/_base.py#L326:L338).

Alternatively the code in https://github.com/OriHoch/elasticsearch-py-disable-product-check/blob/main/example-success.py (MIT license) is trivial to include in https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/search.py.
