### ISSUE TITLE
Unexpected file signature information from addon version API

### ISSUE THREAD

**Issue by etienneroudeix** [mozilla/addons-server#19460]
Hello,

### Describe the problem and steps to reproduce it:
I requested the `https://addons.mozilla.org/api/v5/addons/addon/<guid>/versions/<version>/` API with a JWT token.
It returned me in `file.is_mozilla_signed_extension: false`
However when I download the file from the `file.url`, it has the `META-INF` folder added by mozilla with the signature files.

### What happened?
Got the following response :

```json
{
  ...
  "file": {
    "id": ...,
    "created": "2022-06-16T06:36:45Z",
    "hash": "sha256:...",
    "is_mozilla_signed_extension": false,
    "size": 1867540,
    "status": "public",
    "url": "https://addons.mozilla.org/firefox/downloads/file/.../....xpi"
  },
  ...
}

```

### What did you expect to happen?
I want to know when the file is signed by Mozilla without downloading it.

Cheers,

Etienne

**Comment by diox** [comment]
`is_mozilla_signed_extension` isn't what you think it is. As per [our docs](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html):
> Whether the file was signed with a Mozilla internal certificate or not.

Very few add-ons are signed by an internal certificate, it's for privileged/internal Mozilla extensions.

If a file has `"status": "public"`, then it should have been signed.

**Comment by willdurand** [comment]
Salut @etienneroudeix 😉  You could also take a look at https://github.com/mozilla/sign-addon/ to see how _we_ determine when a file is signed, though this lib is slowly (but surely) put on a deprecation path and we have a new signing API (which isn't what sign-addon uses).
