### ISSUE TITLE
refactor reviewer tools use of jinja functions to display review status

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19471]
In https://github.com/mozilla/addons-server/pull/19465 methods were added on Version and File to display a reviewer status for file and version (i.e. the real file status, but overridden for other properties/psueduo statuses - disabled; auto approved; pending rejection; etc).  

We should drop the use of `file_review_status` and `version_status` in favour of single definitions of review status - `File.get_review_status_display` and `Version.get_review_status_display`.

**Comment by ioanarusiczki** [comment]
@eviljeff I'm going to check again what I've done here https://github.com/mozilla/addons-server/issues/18121#issuecomment-1190636593
