### ISSUE TITLE
Add-ons using an ID ending with `@mozilla.org` suffix need to be signed with privileged certificate

### ISSUE THREAD

**Issue by rhelmer** [mozilla/addons-server#19478]
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)

### What happened?

Upload of a new, unprivileged extension failed:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/61412/179800510-ba1e2834-4199-4fd8-bca1-44bf3f259fe4.png">

This was reviewed and approved in https://mozilla-hub.atlassian.net/browse/ADDONSOPS-185

### What did you expect to happen?

Upload accepted on AMO, the suffix should not imply whether the extension is privileged or not, just that it is "owned" by Mozilla.

### Anything else we should know?

(Please include screenshots and any relevant files.)

**Comment by diox** [comment]
Essentially, this will revert https://github.com/mozilla/addons-server/issues/18252 because now the linter has specific checks about privileged extensions (See the other issues in this project: https://github.com/orgs/mozilla/projects/178)

**Comment by wagnerand** [comment]
From a requirements perspective, Rob should be able to submit the extension, which is non-privileged but has an ID that matches the reserved pattern list. As far as I remember, add-ons matching those reserved patterns need to be signed with the privileged certificate. That requirements probably needs to be removed. At the same time, we might still want to restrict who can submit (any) add-on with an ID matching the reserved patterns, so we should make sure to check for the `SystemAddon:Submit` permission. The name is a bit misleading these days and we should rename it eventually...

**Comment by ioanarusiczki** [comment]
@diox 

I verified on AMO stage:
with a mozilla e-mail address users with SystemAddon:Submit permission can submit an addon with an id such as : 123@mozilla.org or 123@rally.mozilla.org
