### ISSUE TITLE
Display the waiting time for new submitted versions after those rejected

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19487]
I applied the scenario from https://github.com/mozilla/addons-server/issues/19439 and checked the other queues with "Waiting Time":

[Other Pending Review](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/extension) : there's no time displayed for the version submitted after the one pending 

![waiting time](https://user-images.githubusercontent.com/33448286/179953508-9e7a195c-d644-4501-a35d-1ee3216195aa.png)

same for the[ New Themes ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/theme_new )queue (right now the first result)

Expected result:
there should be a nomination time (without time inherited from the previous rejected version)

**Comment by ioanarusiczki** [comment]
@diox Looks alright, the nomination time is not inherited.

**Comment by diox** [comment]
But is there a nomination date set in that case ?

**Comment by ioanarusiczki** [comment]
@diox I approved the last version -> the addon is no longer in the queue. I submit a new version and I check the queue again ( I talk about the recommended or theme updates). I see the new version with a waiting time ...seconds ago.

**Comment by ioanarusiczki** [comment]
@diox I verified on AMO stage - this issue is no longer reproducible.
