### ISSUE TITLE
enforce that a delayed rejection has a user and a content/code review status

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19498]
currently a `pending_rejection` flag in `VersionReviewFlags` can have a `pending_rejection_by` and (as of https://github.com/mozilla/addons-server/pull/19490) a `pending_content_rejection` property, or they can be `none`.  As they should always be set if `pending_rejection` is non-`none` then we should enforce this with a database constraint (we already have a constraint to ensure if `pending_rejection` is `none` then `pending_content_rejection` and `pending_rejection_by` are also none)

**Comment by eviljeff** [comment]
QA: this should be a transparent change - it just tightens the database constraint - but check delayed rejections haven't been inadvertently broken.  (including, if there are any, delayed rejections from before this change landed)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I'll check the results tomorrow morning - I prepared some delayed rejections on AMO stage.

I've noticed 2 things on AMO stage:

 - the pending rejection [queue](https://reviewers.addons.allizom.org/en-US/reviewers/queue/pending_rejection) contains a column Pending Rejection Deadline -> some addons display a deadline and some won't so I don't know if that's expected. I remember I've seen this before but I forgot to mention it. 

- the old "awaiting review" for a version that wasn't reviewed  turned into "disabled by Mozilla" when a new version was submitted. Now it's "Rejected or Unreviewed". Also when a version is disabled by the developer the rev tools page shows it like "Disabled by Developer" 

![testare](https://user-images.githubusercontent.com/33448286/182613809-ba2d6377-22c1-44d5-986b-2a6f1c9d5843.png)

**Comment by eviljeff** [comment]
>     * the pending rejection [queue](https://reviewers.addons.allizom.org/en-US/reviewers/queue/pending_rejection) contains a column Pending Rejection Deadline -> some addons display a deadline and some won't so I don't know if that's expected. I remember I've seen this before but I forgot to mention it.

it's been a while since I looked at the pending rejection queue so I'm not really sure.  Seems like a bug?
 
>     * the old "awaiting review" for a version that wasn't reviewed  turned into "disabled by Mozilla" when a new version was submitted. Now it's "Rejected or Unreviewed". Also when a version is disabled by the developer the rev tools page shows it like "Disabled by Developer"

that's https://github.com/mozilla/addons-server/issues/19471

**Comment by ioanarusiczki** [comment]
@eviljeff 

I'm still waiting for rejection to expire today in a couple of hours - > but I think there's no problem with the delayed feature. 

I filed a followup https://github.com/mozilla/addons-server/issues/19533
