### ISSUE TITLE
Manual Testing :Addons issue

### ISSUE THREAD

**Issue by kshitijakarkar** [mozilla/addons-server#1949]
The drop down list does not not have windows 10 as operating system option to run the test cases

**Comment by muffinresearch** [comment]
Hi, can you provide more details as to which drop-down you're referring to?

**Comment by kshitijakarkar** [comment]
I was trying to work on manual testing:addons
https://moztrap.mozilla.org/runtests/environment/2215/
but I have Windows 10 system . The drop down list of operating system does not have windows 10 as option to run the test

**Comment by andymckay** [comment]
Sorry, this isn't related to addon-server. I'm not sure where to file a bug about this though. moztrap doesn't use github, so I'm not sure either.

**Comment by kshitijakarkar** [comment]
Isn't it necessary to test on latest operating system?

**Comment by andymckay** [comment]
Sure. But this team has nothing to do with moztrap, so I'm not sure what you expect us to do.

**Comment by tofumatt** [comment]
Seems like moztrap is on GitHub: https://github.com/mozilla/moztrap

**Comment by bobsilverberg** [comment]
@kshitijakarkar For issues with Moztrap please file a bug in Bugzilla at https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla%20QA&component=MozTrap.

**Comment by kshitijakarkar** [comment]
@bobsilverberg :okay I'll do that

@andymckay : I am new to Mozilla team. I was trying to run some tests. Since I didn't find windows 10 option , I reported it here as it concerns with add-on tests.
