### ISSUE TITLE
Drop `abuse_reports.addon_id` and add constraint ensuring `guid` and `user_id` are mutually exclusive

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19499]
Follow-up for https://github.com/mozilla/addons-server/issues/18879 : once the field is removed from the model, remove the column in the following push.

Also add a constraint ensuring either `guid` or `user_id` are set to a non-null value, and that they are mutually exclusive: both can't be set to a non-null value at the same time.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I did notice 2 issues but they don't seem to be regressions https://github.com/mozilla/addons-server/issues/19539 and https://github.com/mozilla/addons-server/issues/19540

**Comment by eviljeff** [comment]
> @eviljeff
> 
> I did notice 2 issues but they don't seem to be regressions #19539 and #19540

they're probably regressions from the changes made in #18879 instead.

(this patch just added a database constraint, so shouldn't have changed anything else)
