### ISSUE TITLE
"Upload not valid error message" is displayed for some larger addons

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19511]
Followup for https://github.com/mozilla/addons-server/issues/19366#issuecomment-1196605727 

I've noticed with 2 addons a pattern, I tried with Decentraleyes and uBlock Origin from prod an upload and create -> after I get the uuid , the addon create API throws a 400 "Upload not valid" if I try to create immediately.  I must wait for a while and then send the request and it will work as expected.  

Notes:
When the addon is a dummy this is not reproducible, but  Decentraleyes is 6,7 MB , UBlock 2,8 MB. 
Could be what's been described into https://github.com/mozilla/addons-server/issues/19376

**Comment by AlexandraMoga** [comment]
One thing I'd like to add: this can be reproduced with less complex (dummy) addons as well if the POST `/addon/` request comes immediately after the `/upload/` request. I've noticed this while running automated submission tests with the API. In my case, a ~3 seconds wait helped with bypassing this lag, but I guess the waiting time can be longer depending on the addon size.

**Comment by diox** [comment]
From the description alone this doesn't necessarily look like a bug. What happens is, after calling /upload/ your upload gets validated asynchronously, and this can take a few seconds or even a couple minutes in the most extreme cases.

The docs say:
> After the file has uploaded the [upload response](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-detail-object) will be returned immediately, and the addon submitted for validation. The [upload detail endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#id11) should be queried for validation status to determine when/if the upload can be used to create an add-on/version.

**Comment by eviljeff** [comment]
@ioanarusiczki can you confirm that the upload detail response is showing as `"valid": true` at the point it's being used and returning an error?  As @diox mentioned, validation is an asynchronous task, so the upload request returns straight away before the validation has started.

**Comment by ioanarusiczki** [comment]
@eviljeff I see `"valid": false` in the upload response -> tried it with a dummy extension too

**Comment by eviljeff** [comment]
It's working as expected then.  If the upload is `"valid": false` it can't be used to create an add-on/version.  It will be `"valid": true` once the validation is complete (`"processed": true`), if it passed.

If we're erroring on uploads that are `"valid": true" (i.e. the upload completed validation and it passed) then there is a bug.
