### ISSUE TITLE
Submission does not work on AMO-dev due to "an unexpected error"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1955]
Steps to reproduce:
1. Sign into AMO-dev https://addons-dev.allizom.org
2. Select Tools - Submit a New Add-on
3. Select a valid .xpi and continue

Expected results:
The add-on passes validation.

Actual results:
The add-on fails validation with the error "An unexpected error has occurred".

Notes/Issues:
Please see the validation report:
![2016-03-21_1703](https://cloud.githubusercontent.com/assets/15685960/13922889/f839e95e-ef86-11e5-91be-663de3d1bb4a.png)
Verified on AMO-dev FF45(Win 7). Issue is only reproducing on AMO-dev.
Screenshot for this issue: 
![2016-03-21_1705](https://cloud.githubusercontent.com/assets/15685960/13922961/474cc3a4-ef87-11e5-8f76-38c2ff1bcdfd.png)
Attaching the xpi.
[versions.zip](https://github.com/mozilla/addons-server/files/182503/versions.zip)

**Comment by muffinresearch** [comment]
@ValentinaPC I see this error:

No install.rdf or package.json or manifest.json found

Can you re-test this and see if you can still reproduce it?

**Comment by muffinresearch** [comment]
From irc it seems like the problem has gone. Closing it now and we can re-open if it reoccurs.
