### ISSUE TITLE
Upgrade to python 3.10

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19560]
We're currently running python 3.9, which will receive security fixes for another ~3 years, but had it's final bugfix release back in May (3.9.13, release on 2022-05-17).  To keep up to date we should upgrade to python 3.10 which was released last year.

At this stage none of our dependencies have been checked to see if they support 3.10.

**Comment by eviljeff** [comment]
First blocker is our [old friend](https://github.com/mozilla/addons-server/issues/16269#issuecomment-910384318) pygit2. Will attempt to upgrade to a newer version that supports python3.10 at the same time: https://www.pygit2.org/install.html#version-numbers

**Comment by eviljeff** [comment]
n.b. it's unclear what version of `libgit2-dev` we're actually using - I doubt it it matches with the version that's supposed to be used according to https://www.pygit2.org/install.html#version-numbers

**Comment by diox** [comment]
Copy/pasting my reply from the PR regarding pygit:
> I think we should upgrade pygit first separately. We used to need to compile it ourselves because the wheels were broken/not available for our config, and we include libgit2-dev in our CI/Docker images for that reason. Nowadays that shouldn't be necessary, 1.4.0 (the version we're currently using on master) fixed that so we should be able to remove that cruft and upgrade to a more recent one.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/issues/19569

**Comment by ioanarusiczki** [comment]
@eviljeff I assume this could affect dev hub, the search and so on. Please add str if you consider I should be focusing anything in particular.

**Comment by eviljeff** [comment]
@ioanarusiczki there weren't any changes in our code needed, or dependency updates (apart from #19569 which was verified separately), so nothing in particular.
