### ISSUE TITLE
upgrade pygit2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19569]
semi-quoting @diox: We should upgrade pygit2. We used to need to compile it ourselves because the wheels were broken/not available for our config, and we include libgit2-dev in our CI/Docker images for that reason. Nowadays that shouldn't be necessary, 1.4.0 (the version we're currently using on master) fixed that so we should be able to remove that cruft and upgrade to a more recent one.

**Comment by diox** [comment]
Note that `libgit2-dev` should also be the only reason why we have `docker/buster-backports.list` (we `COPY` all `docker/*.list` files into the image) - so if we're able to remove that package from the image, we should also be able to remove that apt source list file.

**Comment by diox** [comment]
FWIW I've tried removing `libgit2-dev` from my container and upgrading `pygit` to 1.7.x and it worked, it correctly installed a manylinux wheel that has everything needed built-in. I was then able to do a git extraction with no issues (need `enable-uploads-commit-to-git-storage` and `enable-git-extraction-cron` waffle switches on, then uploading or signing a version, and running `git_extraction` management command).

**Comment by diox** [comment]
QA:
- Check newly uploaded versions are available in code-manager and that comparing to the previous version works.

**Comment by ioanarusiczki** [comment]
@diox Works for me, I verified it on AMO stage - FF103(Win10).
