### ISSUE TITLE
Updating fixtures to use modern directory structure for `File.file` property

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19577]
We still have many fixtures using the old directory structure (`<addon_id>/<filename.xpi>` instead of `<last 2 digits of addon_id>/<last 4 digits of addon_id>/<addon_id>/<filename.xpi>`). This is dangerous: it hid a problem when we changed the directory structure that had to be hotfixed (https://github.com/mozilla/addons-server/issues/19243) - the code at the time wasn't handling new directory structure in the update service, and tests were passing because the fixtures used by the corresponding tests were all using the old structure.

Example: https://github.com/mozilla/addons-server/blob/43591247351c2c62c415fac0b383db2005200bfa/src/olympia/amo/fixtures/base/addon_3615.json#L204

So we should switch them all to the new structure.

**Comment by ioanarusiczki** [comment]
@eviljeff Would https://github.com/mozilla/addons-server/issues/19215#issuecomment-1222004057 cover for this too?
