### ISSUE TITLE
Return add-on slug in abuse report API responses

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19578]
https://github.com/mozilla/addons-server/issues/18879 dropped the `addon` foreign key from `AbuseReport` and in doing so, stopped returning `slug` and `id` of the add-on being reported in the response.

When an abuse report is submitted using the `slug` or `id` though, we _should_ return the `slug` and `id` in the response. And might as well do it at all times if the add-on is public (even when a `guid` was used). addons-frontend is using that in https://github.com/mozilla/addons-frontend/issues/11780 when it's not using the Firefox API (which submits by `guid`) to submit the abuse report.

**Comment by ioanarusiczki** [comment]
@diox With https://addons-dev.allizom.org/api/v5/abuse/report/addon/ I sent several abuse reports using id, guid or slug -> the response returned "id" and "slug" every time (unlike -stage where I've noticed the issue still reproducible).
