### ISSUE TITLE
Verify web-ext integration with AMO submission API works

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19588]
Once mozilla/web-ext#2451 is closed, it would be good to verify that in the integration with the addon submission api is working as expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-114)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-114
