### ISSUE TITLE
collectstatic chokes when linked map files aren't in node_libs in django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19607]
part of https://github.com/mozilla/addons-server/issues/19595 to support newer 4.x django - collectstatic now looks for linked files in js and css files, and (at least some of) the js dependencies include links to the xxx.js.map file.  

We don't currently copy those files over and there is no obvious command line switch to disable the feature.  (I tried `--ignore '*.map'` but didn't seem to make a difference)

**Comment by eviljeff** [comment]
> Post-processing 'js/node_lib/underscore.js' failed!
> 
> Traceback (most recent call last):
>   File "/home/circleci/project/manage.py", line 11, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
>     utility.execute()
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
>     output = self.handle(*args, **options)
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
>     collected = self.collect()
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
>     raise processed
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 338, in _post_process
>     content = pattern.sub(converter, content)
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 215, in converter
>     hashed_url = self._url(
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 152, in _url
>     hashed_name = hashed_name_func(*args)
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 388, in _stored_name
>     cache_name = self.clean_name(self.hashed_name(name))
>   File "/home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 113, in hashed_name
>     raise ValueError(
> ValueError: The file 'js/node_lib/underscore-umd.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f53454d4b50>.
> make: *** [Makefile-docker:123: update_assets] Error 1
> 
> Exited with code exit status 2
> 
> CircleCI received exit code 2
>

**Comment by eviljeff** [comment]
After adding `underscore-umd.js.map` to `NODE_LIBS_JS` in `Makefile-docker` to fix that fail I hit an error with rest_framework's css files that are hoovered up during `collect_static` - it's fixed in https://github.com/encode/django-rest-framework/pull/8591 but the fix isn't in the latest DRF v3.12.4 so we'll have to wait until the next version is released.  There may be more fixes needed that file is unblocked.

**Comment by AlexandraMoga** [comment]
@eviljeff does this require QA?

**Comment by eviljeff** [comment]
@AlexandraMoga there is a slight code change relating to how static files (javascript and css) are collected and bundled up but there shouldn't be any functional difference.  Just check that js and css is loaded correctly in devhub/reviewer tools.

**Comment by AlexandraMoga** [comment]
There were no issues found in rev tools, devhub and statistic pages with regards to layouts and functionality.

I'm marking this issue as verified fixed on stage.
