### ISSUE TITLE
Log IPs from where ratings are posted in IPLog

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19602]
We already log the IP address when a user rating is posted, but we do that in the `Rating` model (`reviews` table). For consistency and to help https://github.com/mozilla/addons-server/issues/17504 I'd like to store that as an `IPLog` instance linked to the corresponding `ActivityLog` instead.

**Comment by diox** [comment]
We're going to need to backfill existing data, creating `IPLog` corresponding to past ratings activity.

Interesting gotcha: the `ADD_RATING` and `EDIT_RATING` activities are not kept for more than 90 days currently. It has been set like that 15+ years ago, I don't know why. We can change it going forward, but since `IPLog` need a corresponding `ActivityLog` that doesn't exist for old ratings, the `IPLog` backfill wouldn't be done for old ratings... unless we start re-creating `ADD_RATING` `ActivityLog` for those too - and we'd be missing `EDIT_RATING`, so we'd have an incomplete picture anyway.

My recommendation would be to not care about these older ratings for backfilling purposes, and choose what we want to do going forward:
- Start keeping `ADD_RATING` and `EDIT_RATING`
- Do nothing, only keeping them - and the associated IP address - for 90 days
- Bump the keep period for all activities we aren't keeping forever from 90 days to like 180.

Note that in any case, the `clear_old_user_data` cron clears non-developer data within 24 hours when their user account is deleted. That includes `USerProfile.last_login_ip`, `UserRestrictionHistory.ip_address` and `UserRestrictionHistory.last_login_ip` and `IPLog` instances. Currently `Rating.ip_address` is kept, but that sounds like a bug/inconsistency we'd want to fix.

**Comment by wagnerand** [comment]
> Bump the keep period for all activities we aren't keeping forever from 90 days to like 180.

Let's do this.

> Currently Rating.ip_address is kept, but that sounds like a bug/inconsistency we'd want to fix.

I believe it's worth keeping that data for more than 24h to combat rating abuse, but we don't need to keep it indefinitely, we can apply the 180 days as well.

**Comment by diox** [comment]
Note: After further discussion with @wagnerand, contrary to login data in https://github.com/mozilla/addons-server/issues/19615, we're not going to backfill activity logs for existing ratings, just bump the conservation period to 180 days and start logging the IP for new ratings. Eventually (after the 180 days) we'll be in the same situation than if we had backfilled.

**Comment by ioanarusiczki** [comment]
@diox 
I verified on -dev the Activity Log for ratings - > there's 2 entries , "written" and "updated". Seem to be as before if I tested a few for -stage. 

Should I see an Ip field inside these activity logs?

**Comment by diox** [comment]
It's not currently exposed in the admin separately (you should see the IP you used in the "known IPs" in the user admin, but it doesn't tell you where each is coming from). I've verified that the ratings you posted does have an `IPLog` by manually logging on to dev.

**Comment by ioanarusiczki** [comment]
@diox Yes, I see the ip exposed in the userprofile module.
Then I can mark this verified on AMO dev - FF 103(Win10).
