### ISSUE TITLE
address deprecation warnings for django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19606]
part of #19595 to support newer 4.x django - Django logs warnings when deprecated features will be removed in a later version - so either in django 4.0, 4.1 or 4.2.  If they're raised in django3.2 it should be completely safe to make the change now.

**Comment by eviljeff** [comment]
Django related deprecation warnings in our code:
- ../deps/lib/python3.9/site-packages/django/apps/registry.py:91
  /deps/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'olympia.core' defines default_app_config = 'olympia.core.apps.CoreConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
- `/home/circleci/project/src/olympia/amo/tests/__init__.py`:1116: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
    django_urls.url(url_regex, view, name='test-dynamic-endpoint')
- /home/circleci/project/src/olympia/api/tests/test_middleware.py:14: RemovedInDjango40Warning: Passing None for the middleware get_response argument is deprecated.
    APIRequestMiddleware().process_request(request)
- /home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/core/management/base.py:254: RemovedInDjango41Warning: Using a boolean value for requires_system_checks is deprecated. Use `'__all__'` instead of True, and [] (an empty list) instead of False.
- /home/circleci/.pyenv/versions/3.10.6/lib/python3.10/site-packages/django/utils/functional.py:228: RemovedInDjango40Warning: django.utils.http.urlunquote() is deprecated in favor of urllib.parse.unquote().

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some Str for qa

**Comment by eviljeff** [comment]
Most of the changes are in test files and if the other adjustments didn't work the site probably wouldn't load so there aren't any particular steps here.  Going to mark as QA not needed but if there _is_ some inexplicable failure on stage after the tag it _could_ be due to this issue.
