### ISSUE TITLE
00:00 is now midnight in django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19609]
in django templates, a datetime that would previously be rendered as `Jan. 1, 2011, 00:00` is being rendered as `Jan. 1, 2011, midnight`

**Comment by eviljeff** [comment]
Ugh, I think this is a subtle symptom of a[ change to default](https://docs.djangoproject.com/en/4.0/ref/settings/#use-l10n) to change `settings.USE_L10N` to `True`.  Because "Note that if [USE_L10N](https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-USE_L10N) is set to True, then the locale-dictated format has higher precedence and will be applied instead" [[docs](https://docs.djangoproject.com/en/4.0/ref/settings/#datetime-format)].

We can override with `settings.USE_L10N = False` but the docs also that setting it at all is deprecated and will be removed in django 5.0 so it's probably something we should sort out now instead.

**Comment by diox** [comment]
Probably fine to use. `USE_TZ=False` is the important one we need to keep (so that we continue to only deal with UTC, which is the timezone configured on our servers)

**Comment by eviljeff** [comment]
failing tests:
FAILED src/olympia/scanners/tests/test_admin.py::TestScannerQueryRuleAdmin::test_no_button_for_completed_rule_query
FAILED src/olympia/users/tests/test_admin.py::TestUserAdmin::test_last_known_activity_time
FAILED src/olympia/reviewers/tests/test_views.py::TestRatingsModerationLog::test_enddate_filter

**Comment by ioanarusiczki** [comment]
@eviljeff Is this qa needed?

**Comment by eviljeff** [comment]
> @eviljeff Is this qa needed?

yes, just look at somewhere we display dates and/or times in devhub/reviewer tools and check it looks reasonable.  We're now using django provided localized datetime formatting style so it may be subtly different than what we had before (and that's fine).

**Comment by ioanarusiczki** [comment]
@eviljeff Looks good to me on -dev FF104(Win10).

**Comment by ioanarusiczki** [comment]
@eviljeff I've noticed in Ratings Awaiting Moderation that the date is followed by "()" but it's also present on AMO stage. I don't think this matters for rev tools:

![brakets](https://user-images.githubusercontent.com/33448286/188648069-b9f306b3-fc60-4415-8e64-af98d70a8b04.png)

**Comment by eviljeff** [comment]
> I've noticed in Ratings Awaiting Moderation that the date is followed by "()" but it's also present on AMO stage. I don't think this matters for rev tools

no idea what that's about - I'm not sure where it is from exactly, either (it's been a long while since I was regularly using the reviewer tools) 🤷

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if this needs a fix and I should file it.

**Comment by diox** [comment]
This is extremely minor, but we should remove it. It's supposed to be the locale the rating was posted in, but we remove translation (and therefore locale) support for ratings a very long time ago.
