### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Riribouldingue** [mozilla/addons-server#19619]
From : https://css.developpez.com/telecharger/detail/id/1489/CSS-validator

### What happened?
https://addons.mozilla.org/firefox/downloads/file/14568/css_validator-0.3.2-fx.xpi
+
Nous somm[es ](https://addons.mozilla.org/fr/firefox/)désolés, mais nous ne pouvons pas trouver ce que vous cherchez.

### What did you expect to happen?
A Download
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
I don't have any more details about why the file is unavailable - the developer of the add-on should know, and we can only discuss the status with them.  But I do see the file ID is very old (more than 6 years) so it's likely it was an obsolete type of extension that Firefox - and addons.mozilla.org - no longer support.

**Comment by Riribouldingue** [comment]
Bonjour, 
Effectivement le lien date de 2011 et l'appli est maintenant intégrée dans "validator.w3.org". 
Désolé. 
Yves 
Hello, 
Indeed the link dates from 2011 and the app is now integrated into "validator.w3.org". 
Sorry. 
yves 



De: "Andrew Williamson" ***@***.***> 
À: "mozilla/addons-server" ***@***.***> 
Cc: "riribouldingue" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 31 Août 2022 13:30:03 
Objet: Re: [mozilla/addons-server] 404 (Issue #19619) 





Closed [ https://github.com/mozilla/addons-server/issues/19619 | #19619 ] as completed.
