### ISSUE TITLE
either manually set `X-XSS-Protection header` header in django4.x or drop tests

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19613]
In django 4.0 the [SecurityMiddleware](https://docs.djangoproject.com/en/4.0/ref/middleware/#django.middleware.security.SecurityMiddleware) no longer sets the X-XSS-Protection header if the SECURE_BROWSER_XSS_FILTER setting is True. The setting is removed. [[docs](https://docs.djangoproject.com/en/4.0/releases/4.0/#securitymiddleware-no-longer-sets-the-x-xss-protection-header)]

We either need to manually set the header, or accept the logic of the django project that it's an obsolete header these days, and drop the tests (and don't have it enabled in django3.2 either if it's that useless)

**Comment by diox** [comment]
We should remove it.

**Comment by eviljeff** [comment]
btw, I note from a code search that the `x-xss-protection` appears to be set by addons-frontend and addons-code-manager.
