### ISSUE TITLE
fix sitemap index xml file rendering in django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19611]
We don't do anything special with sitemap.xml files to force them to render with django, so they default to rendering with jinja2.  In django 3.2 that's fine - the syntax is compatible.  In django4.x though there has been a change in `sitemap_index.xml` template which is incompatible with jinja2, so we need to override and force the sitemap xml files to be rendered with django template renderer.

**Comment by ioanarusiczki** [comment]
@eviljeff Can qa check this issue?

**Comment by eviljeff** [comment]
> @eviljeff Can qa check this issue?

yes, just look at the sitemap index on dev - just `sitemap.xml` - and check it's rendering xml that looks like the sitemap.xml on prod (prod will have many more links to sub-sitemaps but the structure should be the same).  On addons-dev (only on -dev) you can append `?debug` to get a real-time generated (rather than cached) [sitemap.xml.](https://addons-dev.allizom.org/sitemap.xml?debug).

**Comment by AlexandraMoga** [comment]
I've checked the sitemap for -dev - https://addons-dev.allizom.org/sitemap.xml - and compared it with the sections we have on prod. All the sections available on prod are present on -dev as well. 

If new data has been made available on -dev, for example new addons have been submitted, the sitemap will load that data if `?debug` is appended.

I'm marking this issue as verified fixed on -dev.
