### ISSUE TITLE
django admin's `lookup_needs_distinct` function has moved/been removed/replaced in django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19610]
`admin.utils.lookup_needs_distinct` now doesn't resolve

**Comment by eviljeff** [comment]
From 4.0 release notes:
> The undocumented django.contrib.admin.utils.lookup_needs_distinct() function is renamed to lookup_spawns_duplicates().

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some Str for qa

**Comment by eviljeff** [comment]
Check searching in user admin in django admin works as expected.

**Comment by ioanarusiczki** [comment]
@eviljeff Works for me. Verified on [django admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/) -dev
