### ISSUE TITLE
Fix devhub forms in django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19614]
I've not investigated the cause yet, but there are a bunch of fails (27) under django4.1 for our devhub tests.  Could be a change in the django Form handling; could be change in how the default widgets/forms are rendered compared to how we (for the most part) manually construct the html form elements.

**Comment by eviljeff** [comment]
Just noting that Django has [changed the args](https://docs.djangoproject.com/en/4.1/topics/testing/tools/#django.test.SimpleTestCase.assertFormError) of the `assertFormError` method between django4.0 and 4.1 to require a form instance rather than the `response` + form name, though there is a deprecation shim around it to still accept the 4.0 and earlier style args until Django5.0.

**Comment by eviljeff** [comment]
> Just noting that Django has [changed the args](https://docs.djangoproject.com/en/4.1/topics/testing/tools/#django.test.SimpleTestCase.assertFormError) of the `assertFormError` method between django4.0 and 4.1

turns out the test fails are connected with this.  There was a [ticket](https://code.djangoproject.com/ticket/33346) filed because `assertFormError` failed under django4.1 if your form was called `form` (which we did in devhub in a few different places) and that change was the "fix".  So we either need to duplicate all the places we call `assertFormError` on a response that contains a form named `form` to use the old style args in django3.2 and the new style args in 4.1+ or rename the forms that are named `form` to something else (I'm doing the latter)

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa.

**Comment by eviljeff** [comment]
QA: I made a small change to devhub forms that are used for submitting a new add-on/version, and for editing an add-on's metadata, so just check submitting and editing an add-on works in devhub.  There shouldn't be any functional changes.

note the milestone bump, so no rush.
