### ISSUE TITLE
Displayed download size is different on AMO to what Firefox shows

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#1962]
Under https://addons.mozilla.org/addon/adblock-plus/versions/2.7.2 AMO claims that the size of Adblock Plus 2.7.2 is 984.0 kB. The size of the actual download is 1,013,992 bytes, meaning 990.2 kB. The wrong number appears to be caused by two issues:
1. The size refers to the original (unsigned) upload, not to the signed build.
2. The size of the unsigned build is 984,034 bytes so AMO appears to be showing kibibytes rather than kilobytes.

**Comment by eviljeff** [comment]
On 2. we're using the standard django [filesizeformat](https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#filesizeformat) template filter which knowingly uses the 'norm' of 1kB = 1024 bytes rather the the SI.  Its a larger discussion you should take to [dev-addons](https://mail.mozilla.org/listinfo/dev-addons) if you want it changed

**Comment by palant** [comment]
Ok, then I don't understand why the size for all downloads appears to be calculated with 1kB = 1000 bytes (yes, I checked more than just Adblock Plus 2.7.2).

**Comment by eviljeff** [comment]
Ah... we're actually using a jinja2 [filter](http://jinja.pocoo.org/docs/dev/templates/#filesizeformat) that by default does SI units.

**Comment by eviljeff** [comment]
I fixed 1. in #1969 for new versions- see [2.7.3](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/?page=1#version-2.7.3) and for 2. looks like we're showing the same as Firefox shows locally.
![screenshot 2016-05-24 18 04 05](https://cloud.githubusercontent.com/assets/768592/15512961/64ba4558-21da-11e6-882a-ae450f45409c.png)

**Comment by palant** [comment]
I can confirm the first issue being fixed. As to the second - yes, it doesn't matter for Adblock Plus any more, but that's simply a rounding error. If you take a smaller download like https://addons.mozilla.org/addon/easy-passwords/versions/1.0.6 you will see a difference between AMO and Firefox:

<img width="477" alt="easypasswords_size" src="https://cloud.githubusercontent.com/assets/374261/15517225/f8668e80-21f6-11e6-836b-b951c76242dc.png">

File size is 67,144 bytes. Firefox correctly shows 65.6 KB, AMO on the other hand shows 67.1 KB.

**Comment by eviljeff** [comment]
Ah, okay, yes, we're using SI (i.e. decimal, 1000bytes is 1kb) and Firefox is using the other definition (i.e. binary, 1024bytes is 1kb).  AMO should show what Firefox shows, agreed.

**Comment by eviljeff** [comment]
What needs to be done is:

- find all uses of `|filesizeformat` in the template files and replace them with `|filesizeformat(binary=True)`

**Comment by palant** [comment]
Heh, I got confused by https://github.com/mozilla/addons-server/issues/1962#issuecomment-199809793 - this isn't Django's `filesizeformat` filter which work correctly, it's [the one from Jinja2](http://jinja.pocoo.org/docs/dev/templates/#filesizeformat) which uses SI by default.

**Comment by eviljeff** [comment]
I've deleted that comment and your reply so a first time contributor isn't confused.

**Comment by replaceafill** [comment]
Hi. I'd like to fix this issue. I've tracked it down to [this line](https://github.com/mozilla/addons-server/blob/master/src/olympia/versions/templates/versions/version.html#L14).

As instructed in [eviljeff's comment](https://github.com/mozilla/addons-server/issues/1962#issuecomment-221545888), adding binary=True to the filesizeformat call fixes the issue. However, the "find all uses of..." makes me wonder what other parts/views I need to check for a similar problem.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/search?l=HTML&q=%7Cfilesizeformat&utf8=%E2%9C%93 shows there are some other templates that do the same thing (some a little more obscure though)

**Comment by replaceafill** [comment]
I've been able to check and fix 3 of the 5 results in that search. I'm having trouble with these:

1. src/olympia/browse/templates/browse/language_tools.html
    I assume it refers to the Dictionaries & Language Packs view, but I don't know how to upload dictionaries or language packs to populate those tables.

2. src/olympia/zadmin/templates/zadmin/hera.html
    I couldn't find any reference in the code to this template. Is zadmin the application for "Admin Tools"? Is the template included dynamically without referencing its name?

**Comment by eviljeff** [comment]
>   src/olympia/browse/templates/browse/language_tools.html
    I assume it refers to the Dictionaries & Language Packs view, but I don't know how to upload dictionaries or language packs to populate those tables.

It's tricky - you need to upload a [language pack or dictionary](https://developer.mozilla.org/en-US/Add-ons#Other_types_of_add-ons) and then in 'Edit Listing' in the 'Admin Settings' section at the bottom of the page set the 'target locale' to the matching locale.  Though if you've done the same thing in the other templates it's not necessary to explicitly test that page.

>    src/olympia/zadmin/templates/zadmin/hera.html
    I couldn't find any reference in the code to this template. Is zadmin the application for "Admin Tools"? Is the template included dynamically without referencing its name?

Looks like you found some dead code!  An easy fix for a subsequent bug.

**Comment by replaceafill** [comment]
I was able to check the language tools view and I just changed the hera.html template for consistency. I'm not sure if I got ahead of myself, but I already created a pull request.
