### ISSUE TITLE
Fix `TranslationQuery.get_compiler() got an unexpected ... 'elide_empty'` in django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19638]
the [main CI job](https://app.circleci.com/pipelines/github/eviljeff/olympia/960/workflows/a1adc3e4-e6c4-40d8-bcd0-b75214890a85/jobs/10839?invite=true#step-112-6206) running under django4.1 raises the error `TypeError: TranslationQuery.get_compiler() got an unexpected keyword argument 'elide_empty'` for some tests.

**Comment by ioanarusiczki** [comment]
@eviljeff Is this qa needed?

**Comment by eviljeff** [comment]
> @eviljeff Is this qa needed?

It's a slight change in part of the translation (user translation, like an add-on's name, summary, etc) infrastructure so the code remains compatible in newer django versions, but there shouldn't be any functional differences.  Just see that an add-on's localized fields work okay I guess.

**Comment by diox** [comment]
Specifically maybe look at whether ordering add-ons by name (which you can do in devhub when listing your own add-ons) still works - it should be ordered by the translated name in your current locale (with fallback to each add-on's default locale).

**Comment by ioanarusiczki** [comment]
@eviljeff @diox 

I filed a while ago https://github.com/mozilla/addons-server/issues/19205. I will add that using the dev hub form to add a localized custom license is not working, it keeps saving it for en-US. 

The rest should be ok.
