### ISSUE TITLE
Check and remove outgoing references from the database

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#19636]
### Describe the problem and steps to reproduce it:
We plan to use a new outgoing domain name for AMO. We need to check if the database contains any reference to the old outgoing domain name and if it does, we should remove the reference.

For -dev and -stage environment, the old domain name is

* outgoing.stage.mozaws.net

For -prod environment, the old domain name is

* outgoing.prod.mozaws.net

### What happened?
As described above.

### What did you expect to happen?

IIUC, the app itself should only rely on the `REDIRECT_URL` env variable [[1]](https://github.com/mozilla/addons-server/blob/a792e0b929df00ff70374c2d30685f85e9a4ea28/src/olympia/lib/settings_base.py#L715) to set the outgoing domain name, and not the database.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
I've looked into the places where we're using an outgoing url so I'll add my results here. I've verified on both -dev and stage.

External URLs in add-on fields such as: homepage, support site, summary, description, developer comments, contribution url
privacy policy/eula, version release notes, custom license text will no be redirected through https://stage.outgoing.nonprod.webservices.mozgcp.net/v1/
This is an example of an add-on from stage that has external URLs  all the above mentioned fields - https://addons.allizom.org/en-US/firefox/addon/devhub-listed-ext-07-30/. Note that I've updated these fields now, after the outgoing domain change.

For existing add-ons that had external URLs before the outgoing domain change I've noticed the following:
With [this add-on](https://addons.allizom.org/en-US/firefox/addon/facebook-container/), the homepage and support site URLs are going through the new domain while external links included in the add-on description are still going through the https://outgoing.stage.mozaws.net/v1/ domain.  This is just an example to point that there are instances of the old domain still used. Also, I'm not sure why in some places (homepage, support site) the domain seems to have been updated while in others (description) was not.

**Comment by diox** [comment]
Essentially any place where we generate or clean-up HTML can contain the old outgoing domain. So homepage and support site are fine because we store the raw string entered, and just use the outgoing domain at render time, where as fields like description are cleaned up once when the text is entered, the outgoing domain is applied at that time, we store the result and then use that at render time.

**Comment by diox** [comment]
Affected fields/models:
- `comments` on `CollectionAddon` (notes associated to a particular add-on in a given collection)
- `summary`, `description`, `developer_comments`, `eula`, `privacy_policy` on `Addon`
- `release_notes` on `Version`
- `text` on `License`

**Comment by diox** [comment]
We did that once in 2016 when we changed from `https://outgoing.mozilla.org/v1/` to `https://outgoing.prod.mozaws.net/v1/`, in https://github.com/mozilla/addons-server/issues/3116 (see also #3060). The script we ran was https://github.com/mozilla-services/svcops/pull/1159/files, it should still work.

We should set up some test data on dev and stage and try running it there.

**Comment by diox** [comment]
Test data still using the old outgoing URLs:

On dev:
- https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/ (check out the `Read more` links in the description)

On stage:
- https://addons.allizom.org/en-US/firefox/addon/noscript/ (checkout out the various links in the description and developer comments)

**Comment by diox** [comment]
I've tested the old script locally and it's unfortunately not working 100% correctly, so I'll have to do some tweaks to it.

**Comment by diox** [comment]
(We need to run a command manually to fix the data on dev & stage - I'll edit this comment when I have ran the command on those envs, currently waiting for deploys)

**Comment by AlexandraMoga** [comment]
A few more addons from -dev with external links that seem to have been updated correctly to the new outgoing domain:
https://addons-dev.allizom.org/en-US/firefox/addon/video-downloadhelper/ - in description, developer comments
https://addons-dev.allizom.org/en-US/firefox/addon/st-patricks-day-luck-of-the-ir/ - in summary
https://addons-dev.allizom.org/en-US/firefox/addon/vietnamese-dictionary/ - in description

**Comment by diox** [comment]
I successfully ran the script on stage and added it to prod deploy instructions.

**Comment by AlexandraMoga** [comment]
I've checked a few addons on stage and the migration seems successful for the following addons with external links:

- https://addons.allizom.org/en-US/firefox/addon/bloody-vikings/ - links in summary, description, developer comments
- https://addons.allizom.org/en-US/firefox/addon/stealthy - links in description
- https://addons.allizom.org/en-US/firefox/addon/invisiblehand/ - links in description, developer comments
