### ISSUE TITLE
Buttons have blue text but should have white text

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#1963]
This is my fault, because of #1960. Buttons should have white text but they're blue:

<img width="226" alt="screenshot 2016-03-22 13 13 03" src="https://cloud.githubusercontent.com/assets/90871/13952718/d5e574e6-f02f-11e5-8bab-bedb4914dfc8.png">
<img width="220" alt="screenshot 2016-03-22 13 12 58" src="https://cloud.githubusercontent.com/assets/90871/13952719/d5e6df98-f02f-11e5-8572-ebe48475ae36.png">

Easy fix, fortunately.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshots: 
![2016-04-01_0949](https://cloud.githubusercontent.com/assets/15685960/14200994/b734a66e-f7f7-11e5-9383-9d4f7e0494b1.png)
![2016-04-01_1051_001](https://cloud.githubusercontent.com/assets/15685960/14200998/bcd910fa-f7f7-11e5-80aa-46a431050a23.png)
