### ISSUE TITLE
Handle trailing comma/superfluous whitespace in admin IP search

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19635]
In the user admin tool, if you search for one or multiple IPs separated by commas, that triggers an IP search. As soon as you include a space or one of the IPs is invalid however, we silently revert back to a regular search, which in most cases is going to return 0 results.

That's confusing. Let's see if we can return an explicit error instead, without breaking the regular non-ip search functionality that uses the same field. Or better yet, fix the search by removing the stray whitespace around search terms when there is a comma.

**Comment by ioanarusiczki** [comment]
@diox 

I verified on -dev for the cases[ above](https://github.com/mozilla/addons-server/issues/19635#issuecomment-1240486292) using IPs and IDs , multiple scenarios and results are returned (the search bar has been modified too it's longer, I assume it's expected )

About the invalid IP scenarios I don't know what should happen, I'll give 2 examples: 

- Something like `10642416, 10642408:` will return 1 result (the first user) -> this used with 2 IPs, in theory `123.12.12.12, 12.231.123.21:` won't return results.
- search with `10642416, 10642` returns 1 result, a search like `123.12.12.12, 12.231.123` returns 0 results.

**Comment by diox** [comment]
An invalid IP will cause the search to run against the user id (exact search), email (prefix search) or username (prefix search) instead of the IP. So it can return something depending on the search string, but usually it will just return 0 results, as a broken IP is unlikely to match the fields we're falling back to.
