### ISSUE TITLE
Fix ` never_cache didn't receive an HttpRequest...` error in django4.x

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19640]
the [main CI job](https://app.circleci.com/pipelines/github/eviljeff/olympia/960/workflows/a1adc3e4-e6c4-40d8-bcd0-b75214890a85/jobs/10839?invite=true#step-112-6206) running under django4.1 raises the error `
never_cache didn't receive an HttpRequest. If you are decorating a classmethod, be sure to use @method_decorator.` for some tests.

**Comment by eviljeff** [comment]
This is due to a change in django4.0 that started requiring that one of the args to `never_cache` be a `HttpRequest` (seemingly to fix an [unrelated bug](https://code.djangoproject.com/ticket/32468) in django admin 🙃).  This means it can't be used with DRF because it's requests aren't `HttpRequest`s.  Before 4.0 was released that [check was relaxed](https://code.djangoproject.com/ticket/33350) to duck typing on `.META` but it's still failing for some reason.

**Comment by eviljeff** [comment]
well, it turns out the error message was accurate after all!  We need to use `@method_decorator(never_cache)` rather than just `@never_cache` - I read the error as only applying to `@classmethod`.  

(it worked fine before because `never_cache` doesn't actually do anything with the args and kwargs passed to it - they're just passed down to the inner function and the _response_ has it's headers patched..)

**Comment by ioanarusiczki** [comment]
@eviljeff Please add some str for qa.

**Comment by eviljeff** [comment]
QA: it just affects the endpoints used during login, so check you can login as normal.  Ideally check they aren't cached either, but I can't think how to reliably test that.

note the milestone bump, so no rush.

**Comment by ioanarusiczki** [comment]
@eviljeff Ah ok, thanks 👍  I was searching for them on the current milestone

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO dev:

Login from frontend, dev hub, code manager or admin worked for me. 
Creating a new account , resetting the password worked as expected.
I don't know about the cache either, but  for example, looking at /accounts/session api -> x-cache is Miss from cloudfront , so it should be fine.

Reproducible on all servers -> When landing on `https://accounts.stage.mozaws.net/oauth/signin?client_id` (which is already on fxA side) there's a couple of 403s from accounts-static-2.stage.mozaws.net, some xml files 

![403 on accountstaticstage](https://user-images.githubusercontent.com/33448286/190152769-11bd4280-4990-4b87-927a-ec5e8f4ad330.png)

and some errors - not cached .js files

![document not cached](https://user-images.githubusercontent.com/33448286/190152917-2a68abc1-17a5-49f8-96c1-330aa1ecb452.png)
