### ISSUE TITLE
Logging in logs `ActivityLog` twice

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19655]
Spun off from https://github.com/mozilla/addons-server/issues/19631

When someone logs in, we are recording 2 `ActivityLog` and `IPLog`. We introduced the recording of those instances in https://github.com/mozilla/addons-server/issues/19615 but the problem existed beforehand: we are calling `user_logged_in` signal once, then calling django's `login()` function which does it too.

**Comment by diox** [comment]
Note: when checking for the fix, also make sure we're correctly logging `ActivityLog`/`IPLog`/`last_login`/`last_login_ip` for each successful login through API token w/ JWT.

**Comment by ioanarusiczki** [comment]
@diox 

- When I login using FF (frontend, dev hub, code manager) -> the action is registered once, as expected. 

- Using JWT I tried to submit an addon ->for each of the endpoints addons/upload and /addons/addon/ I've noticed a logged in activity.
- Using JWT I tried to report an addon/user for abuse -> I've noticed the response is "reporter": null and I did not see a "logged in " activity
- using Session ids to submit an addon using addons/upload and /addons/addon/-> I did not see a "logged in" activity

**Comment by diox** [comment]
> Using JWT I tried to report an addon/user for abuse -> I've noticed the response is "reporter": null and I did not see a "logged in " activity

The abuse API doesn't allow submission via JWT, so that's expected.

> using Session ids to submit an addon with addons/upload and /addons/addon/ or report an abuse-> I did not see a "logged in" activity

If you're using the session id then you're already logged in for the time the session is valid and there is no need to record that again.
