### ISSUE TITLE
Add range search to django admin IP address search

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19663]
The IP address search on the django admin user profile page allows to search for one or several (comma-separated) IP addresses. 
It would be helpful if I could also search for a range of IPs (e.g. 205.251.192.0 - 205.251.255.255 or 205.251.192.0/18), or even multiple ranges, since especially larger cloud providers often have several, non-consecutive ranges. We can start with one if multiple is a challenge.

Ideally, there would be a way to go from one IP to its corresponding provider range (like we have the `+` button now to add a single IP to the search query). That might require some lookup of IP to range (which I usually do through a manual `whois` on the console). I am not sure if that is feasible on the server-side.

**Comment by diox** [comment]
> That might require some lookup of IP to range

That part is quite annoying to do well: to get accurate information, you need to query the right server (or ask a server that will find it for you and forward the request), but you get data in plain text, and each server might have their own way of formatting the data that is completely different from the others, so parsing is a pain. There are a number of packages that try to work around that with various degrees of success, but nothing really great AFAICT

**Comment by diox** [comment]
I have left out the whois functionality for now, but you can add a mix of networks (`192.168.0.0/24`), IPs and ranges (`192.168.0.1-192.168.0.254`) separated by commas. And thanks to https://github.com/mozilla/addons-server/issues/19635, most whitespace is ignored.

**Comment by ioanarusiczki** [comment]
@diox

It should work,  I tried on -dev:

- to search an ip address/32 -> returned results
- to search using a range -> returned results
