### ISSUE TITLE
Date is followed by "()" in  Ratings Awaiting Moderation queue

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19667]
While checking around for  I've noticed in Ratings Awaiting Moderation that the date is followed by "()" but it's also present on AMO stage. I don't think this matters for rev tools:

![brakets](https://user-images.githubusercontent.com/33448286/188648069-b9f306b3-fc60-4415-8e64-af98d70a8b04.png)

This is reproducible on all AMO servers - it's not a regression caused by https://github.com/mozilla/addons-server/issues/19609 and it's been there for a while.

**Comment by GregSherman** [comment]
Requesting to be assigned this issue @diox @eviljeff

**Comment by ioanarusiczki** [comment]
@eviljeff This has been fixed on AMO dev - FF112(Win10)

![fixed](https://github.com/mozilla/addons-server/assets/33448286/fbd24794-8910-4a17-9646-3f8f7ea8ca63)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-118
