### ISSUE TITLE
Raise and catch explicit error when processing FxA token data without a `refresh_token` key

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19688]
Our FxA login flow starts with a request specifying `access_type: offline`, so when we call the [token endpoint](https://github.com/mozilla/fxa-auth-server/blob/master/fxa-oauth-server/docs/api.md#post-v1token) later in our authentication callback, we should always get a `refresh_token` in the response.

But sometimes (not very often) we don't, even if the token is valid! This ends up [causing a 500 error](https://sentry.io/organizations/mozilla/issues/3174733532/?project=6310819&query=is%3Aunresolved). I suspect this is because the client has altered the URL used to start the flow, removing the `access_type`.

We should raise a more explicit `IdentificationError` in `fxa_identify()` if the response doesn't have a `refresh_token` set, so that it's caught in `with_user()` to redirect the user without logging them in in that case.

QA: check that you can still log in and out after this change (from either devhub or frontend pages)

**Comment by ioanarusiczki** [comment]
@diox 

Worked for me on AMO dev - FF104 (Win10).
