### ISSUE TITLE
Change delete_photo task to take an id instead of a path

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19690]
STR:
- As a developer, upload a profile photo
- Copy the URL to the picture
- As an admin, in the user admin, choose the action to delete the picture for that user

Expected results:
- The user profile is now shown without the photo
- The URL ends up 404ing eventually (change the `modified` query parameter to check that, to avoid CDN caching)

Actual results:
- The user profile is shown without the photo but the URL doesn't 404

`delete_photo()` task takes a full path and deletes it. If the caller was mounting the EFS volume from a different mount point than the worker though, that will fail, because we're doing the deletion with a storage object that verifies the path isn't outside the current mount point.

To fix it, we should modify `UserProfile.delete_picture()` to pass a user id to `delete_photo()` instead. It won't have to do a database query (which may fail if the user is already gone from the database), we can just instantiate a `UserProfile()` object from that id and get its `picture_path` and `picture_path_original` without making any queries.

**Comment by diox** [comment]
Yeah, we probably have some... I filed https://github.com/mozilla/addons-server/issues/19709

**Comment by ioanarusiczki** [comment]
@diox 

I verified on -dev: 
if I change/delete the `modified` query parameter I will hit a 404. The image is shown without the photo. 

To see there's a change in behavior I checked stage and I noticed it's a different behavior -> the URL is reloaded over and over
