### ISSUE TITLE
Add-on update does not work as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1970]
Steps to reproduce:
1. Sing in to AMO-dev with an admin account https://addons-dev.allizom.org/
2. Submit an add-on and approve it
3. Add a new version for that add-on and approve it

**Expected results:**
The second version appears approved in add-on review page. Add-on status is also updated in Public Pages.

**Actual results:**
The second version appears "awaiting..." in add-on review page, and add-on status is not updated in Public Pages.

Notes/Issues:
The success message appears in Editor Tools, even if the version appears not to be approved. ("Review successfully processed. ")
**Also, the review process works slower as usual. **
Verified on AMO-dev FF45(Win 7)
Screecast for this issue: http://screencast.com/t/T9nqbFcLTf

**Comment by diox** [comment]
I've seen this to today, when changing discovery modules I had to wait for a few minutes before seeing my changes applied in the admin page itself (so it was not browser caching).

It sounds like our caches are not properly cleared after an user action on dev. @jasonthomas anything wrong regarding redis/memcached on dev ?

**Comment by ValentinaPC** [comment]
This is reproducing in a weird way in AMO-dev using FF45(Win 7).
Please see the screencast: http://screencast.com/t/hYxg98r1qop

The second version is not approved, but the review message appears in Editor Tools page and, also, in Add-on Review Log a line is added as if the _first version_ is being reviewed each time user tries to make a review for the _second version_.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
All updates work as expected.
