### ISSUE TITLE
Add explicit error when a developer goes through the submission process twice

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19700]
### Describe the problem and steps to reproduce it:
- Log in and go to submit a new add-on
- Select a distribution mechanism, then pick an add-on file
- Hit continue to go to the source code step, but then, use your browser back button to go back to the previous step
- You should see the already validated add-on from the previous step, with the progress bar full
- Hit continue to go to the source code step again

### What happened?
- You see a generic error `Could not parse the manifest file`. Behind the scenes, a sentry error is generated (https://sentry.io/organizations/mozilla/issues/3179698028/?project=6310819&query=is%3Aunresolved in prod)

### What did you expect to happen?
- A specific error message indicating that the submission process has already started for that add-on, and no sentry error behind the scenes.

**Comment by AlexandraMoga** [comment]
I verified this issue on stage and the new error message - ""This upload has already been submitted." is displayed when the same upload is re-submitted. 

[devhub]
![image](https://user-images.githubusercontent.com/31961530/191458977-bbd47c56-2929-483c-aac2-8adad1efd484.png)


[api]
```
{
    "version": {
        "upload": [
            "This upload has already been submitted."
        ]
    }
}
```
