### ISSUE TITLE
Validate incoming client ids/guids more throrougly 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19702]
Some of our APIs accept "client ids" that Firefox sends. Those are SHA256 hashes, so they should always be a 64 characters hexadecimal value. Some also accept "add-on guids", which are either a proper GUID with 32 hexadecimal characters, 4 hyphens and opening & closing brackets, or a email-like identifier. We have regular expressions constants available to validate both.

Although this doesn't seem to be causing any problems (worst case scenario, we just store garbage useless data - we always use the ORM or an external service which is not susceptible to SQL injections for instance), in some APIs we haven't been validating the values properly before storing them or sending them to other services.

We should fix that. Affected APIs/parameters that I could find:
- Abuse Report API (`client_id`)
- Add-on Recommendations API (`guid`)

Non-affected APIs/parameters (relevant for QA to test the fix wouldn't cause regressions):
- Abuse Report API (`addon` should consider invalid guids as slugs)
- Discovery Recommendations API (`telemetry-client-id`, we already validate it)

**Comment by ioanarusiczki** [comment]
@diox 

I sent requests on v4/v5 : 

A**buse Report API (client_id)** 
I send API request using some client id's from [admin ](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/25924/change/) -> "Invalid value" if the string is not equal to 64 chars. 
With "client_id":null -> I run into a 500 Server Error (I'll file an issue)

**Add-on Recommendations API (guid)** 
The request always requires a valid guid.
An example: https://addons-dev.allizom.org/api/v5/addons/recommendations/?app=firefox&guid={784d6246-32bb-4af0-8c71-00fd209cc92a}&recommended=true&lang=en-US

**Abuse Report API (addon should consider invalid guids as slugs)** 
With invalid addon guids,slugs or ids -> the request responds with a 404

**Discovery Recommendations API (telemetry-client-id, we already validate it)** 
-> from about:telemetry#general-data-tab using my clientId as telemetry-client-id parameter -> I get a 200 response with data from AMO dev -> it should be custom results as the [documentation](https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#discovery-content) is describing it. I am not sure yet, but I'll try to figure it out tomorrow.

**Comment by ioanarusiczki** [comment]
@diox 

As discussed, the Discovery Recommandations API would not return custom data for -dev. 
Also, there's an issue on -prod, taar service is having problems, so I'll get the default results here again. 

I can see the data displayed in about:addons -dev , the default one. -> content looks good, addons can be installed.
