### ISSUE TITLE
Remove redundant properties/styles/selectors from restyle.less

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#1971]
There are some erroneous, duped, or poorly organised styles in restyle.less. Further to #1951 and #1944, we should tidy up this file as best we can. It's not needed to ship and it will still be a hacky file, but it'll be a bit nicer to work on in the (hopefully unlikely) event it becomes impala2.

**Comment by muffinresearch** [comment]
I think we've cleaned a lot of this up and will continue to do so. Closing this because I think it will happen organically.
