### ISSUE TITLE
Don't log BadZipFile exceptions as errors in parse_xpi()

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19713]
When a "bad" zip file is uploaded in the submission process, we return a generic `Could not parse the manifest file` error and log the exception to Sentry. But specifically for `BadZipFile` exceptions (corrupted or completely invalid zips) we should raise a more explicit error to the user like `Invalid or corrupted zip/xpi file` or something, and not bother logging it to Sentry.

Examples in Sentry on dev:
- https://sentry.io/organizations/mozilla/issues/3595650866/?query=is%3Aunresolved (Bad magic number for central directory)
- https://sentry.io/organizations/mozilla/issues/3595607666/?query=is%3Aunresolved (File is not a zip file)

**Comment by ioanarusiczki** [comment]
@diox @bobsilverberg Moving this on the next milestone -> 06.10.2022

**Comment by AlexandraMoga** [comment]
@diox I was experimenting with broken archives - like an archive corrupted by deleting some of its contents in a text editor or renaming a `.tar` compression as `.zip` to make the app believe I'm uploading a zip file, but I was already getting the `Invalid or corrupt add-on file` error.
I'm not entirely sure what has changes here, or am I testing with the wrong kind of invalid archives?

**Comment by diox** [comment]
Sorry, I was not looking in the right place when I filed this issue. We were already returning the right thing to the developer as you noted, but internally we're still logging the error in Sentry because it's coming from a different part of the code than the one I touched...

Re-opening. The changes I already landed are still nice for internal consistency but shouldn't have any visible impact.

**Comment by AlexandraMoga** [comment]
@diox I've reverified what I mentioned in my previous comment and it still works. Is there anything else I could look at or can we mark this issue as verified?

**Comment by diox** [comment]
We should be good now. I've verified that we are no longer seeing this in Sentry for dev.
