### ISSUE TITLE
Add `si` to the list of supported languages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#19717]
[This commit](https://github.com/mozilla/addons-frontend/commit/e456c1a98f5c7876db983ba3d6ac0188e143a074) added `si` as a locale, which broke our test automation. I assume that if it is supported in Pontoon, it is a valid language to support, and should be added to our list of supported languages in addons-server.

@peiying2 can you comment on this?

**Comment by peiying2** [comment]
@bobsilverberg  yes, the community requested to add the locale to the project in Pontoon, so please make necessary changes to support it on your side. 

I also add it to the AMO Linter project as well.

**Comment by diox** [comment]
I did a quick check that https://addons-dev.allizom.org/si/firefox/ works when selecting `සිංහල` in the languages dropdown and that you can navigate from the homepage to devhub and back in that language, that should be enough, no need for more QA.
