### ISSUE TITLE
Instrument get_addon_recommendations to record result of calling TAAR LITE API 

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#19711]
There has been a bug in the TAAR LITE API for quite some time, which we didn't notice because our API simply returns fallback results when it receives no results from TAAR LITE, so we don't interpret that as an error. While some manual and/or automated testing could be added by QA to verify this feature in the future, we should also instrument our `get_addon_recommendations` to record data about TAAR LITE API results so we can set up an alert which would fire in cases like this.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Moving this on the next milestone -> 06.10.2022 and please let me know if I can test around this issue.

**Comment by ioanarusiczki** [comment]
@bobsilverberg

 I verified on AMO prod:

the discovery API -> to see if recommendations change for about:addons -> they change, I sent requests from Postman and also checked the browser.  This is expected.

the recommendation API -> it is returning the same results (addons) This is not working as expected.

Please let me know when I could re-check that TAAR started functioning again for AMO prod.
