### ISSUE TITLE
Validate tar files more thoroughly

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19721]
Though we already do validate members of `.tar.gz` or `.tar.bz2` files (which you can only use for source code submission at the moment), we do it manually, so it's error prone, you need to remember to call `archive_member_validator()`. Instead, let's create a `SafeTar` class like we have `SafeZip` for zipfiles and use that everywhere. It should validate the file contents when opened.

Validation should remain the same (forbid filenames with `..` or starting with `/`) but we can also add checks against symlinks, device files etc.

**Comment by AlexandraMoga** [comment]
I've uploaded various `.tar.gz`, `.tgz`, and `.tar.bz2` files as source code and tried to trigger some validation errors. These are my results:

- uploading an unsupported file type 
![image](https://user-images.githubusercontent.com/31961530/192540753-55dca458-c4ec-45ae-ae31-efe48572ed36.png)

- uploading a broken `.tar.gz`, `.tgz`, `.tar.bz2`  or  renamed to e different file type (i.e. a `.zip` renamed as `.tgz`)
![image](https://user-images.githubusercontent.com/31961530/192540983-437b35dd-812b-48d3-aef2-d3c38414ef1e.png)

- uploading a file with `\` in filepaths
![image](https://user-images.githubusercontent.com/31961530/192541078-ff461a69-b8d6-4342-b9e6-1d7f693759ec.png)

- uploading a file which has a large uncompressed size
![image](https://user-images.githubusercontent.com/31961530/192541220-e482183e-81fc-4007-887a-4ce6995ebe04.png)

- uploading a file that includes a symlink
![image](https://user-images.githubusercontent.com/31961530/192541309-8c90a89e-f951-407e-93e8-12c157e77f46.png)


These seem to be the correct error messages for the uploaded file types.

Valid files can be uploaded successfully.

I'm marking this issue as verified fixed on -dev.
