### ISSUE TITLE
Update REDIRECT_URL default to point to GCP

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19733]
Once #19636 is done we should update the `REDIRECT_URL` setting default values to point to the new GCP URL. This should be a completely transparent change as we're already overriding it through environment variables everywhere.

**Comment by AlexandraMoga** [comment]
@diox I've looked again at the fields that use outgoing URLs  and haven't noticed any problems. If there is anything else I could check for this issue, do let me know.
