### ISSUE TITLE
Buttons on theme page look retro

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#1973]
The theme details page in general feels a bit old:

<img width="761" alt="screenshot 2016-03-23 09 09 05" src="https://cloud.githubusercontent.com/assets/90871/13980517/f264caac-f0d6-11e5-9f04-a9baf79999d7.png">

I can convert the buttons and tweak the harsh borders easily enough, but adding `needs-ux` here in case there are:

1. existing mocks for this I missed
2. quick ideas UX can add to improve

If neither 1/2 are true I'll just tidy it up best as I can and ask for UX's blessing afterward :smile:

**Comment by andymckay-limited-access** [comment]
These have been old school for a long time, themes has sadly been not kept to date. Which is sad.

**Comment by muffinresearch** [comment]
Fixed already.

**Comment by ValentinaPC** [comment]
Postfix screenshot from AMO-dev FF45(Win 7)
![2016-04-08_1130](https://cloud.githubusercontent.com/assets/15685960/14378531/1ddd358a-fd7e-11e5-9eeb-195247254f4d.png)
