### ISSUE TITLE
Add message linking to MV3 documentation when submitting a listed MV3 version

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19766]
When submitting a listed MV3 version (`enable-mv3-submissions` switch needs to be `on`) we should warn the developer that this will make their add-on listing incompatible with versions of Firefox below X (X being the release that will start supporting MV3 officially, tbd) and suggest they use unlisted in the meantime as a pseudo-beta channel.

Depends on https://github.com/mozilla/extension-workshop/issues/1415 which we should link to in that message.

Summary of expected warnings/errors:
| Manifest version | Channel | `enable-mv3-submissions` switch | Expected result |
| ---------------- | ------- | ------------------------------ | --------------- |
| 2                | Either  | Either                         | No warning or error |
| 3                | Either  | Disabled                         | **Error**: currently not supported at upload |
| 3                | Listed  | Enabled                         | **Warning**: unlisted upload recommended instead |
| 3                | Unlisted  | Enabled                         | No warning or error |

**Comment by diox** [comment]
We should also display that message (or a tweaked variant of it) at all times when MV3 is ready in the top dynamic banner in the submission page (same place we used for previous warnings to developers in the past, like the 2FA enforcement warning).

**Comment by diox** [comment]
Need better copy and an actual link that works (depends on https://github.com/mozilla/extension-workshop/issues/1415 as mentioned above) but here is what it could look like:

![Screenshot 2022-10-10 at 19-45-58 Upload Add-on Developer Hub Add-ons for Firefox](https://user-images.githubusercontent.com/187006/194928282-ce2dcfb2-44b7-4bb3-9d05-64215d057db5.png)

**Comment by diox** [comment]
After discussing with UX, new copy for that message that I tweaked a little bit:

### Manifest V3 Compatibility Warning

Firefox is adding support for manifest version 3 (MV3) extensions in Firefox [VERSION], however, older versions of Firefox are only compatible with manifest version 2 (MV2) extensions. We recommend uploading Manifest V3 extensions as self-hosted for now to not break compatibility for your users.

For more information about the MV3 extension roll-out or self-hosting MV3 extensions, visit [URL].

**Comment by diox** [comment]
QA notes:
- If `enable-mv3-submissions` switch is off, we continue to display `Manifest V3 is currently not supported for upload.` error for both unlisted and listed submissions
- If it's on and the submission is unlisted, we don't display anything
- If it's on and the submission is listed, we should display the error message above. The Firefox version will be bumped from the current value (100.0) to the correct one as we get closer to shipping official MV3 support.

**Comment by diox** [comment]
Note: The extension-workshop PR hasn't been merged yet, so at the moment the link included in the warning would fail, but we're planning to push it live later today or tomorrow.

**Comment by ioanarusiczki** [comment]
@diox I verified this on AMO stage: 

- switch is inactive, submission on both channels:
![switch disabled](https://user-images.githubusercontent.com/33448286/202189426-17437934-051b-45e9-bacf-1dba355b533b.png)

The URL is redirecting to https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/

- switch is active, the unlisted channel does not throw the warning. 

- switch is active, listed channel:
![messageforlistedchannel](https://user-images.githubusercontent.com/33448286/202188299-4f2f83c8-2c68-4cb6-8888-263c6acf547f.png)

I don't know if Manifest V3 compatibility warning shoud be with capital c and w (as in the [description](https://github.com/mozilla/addons-server/issues/19766#issuecomment-1306986917) above) 

The URL is a 404 right now indeed. And there's "Firefox 100.0" for now available.

**Comment by ioanarusiczki** [comment]
@diox On AMO dev and stage: Firefox 109.0 

![ff109](https://user-images.githubusercontent.com/33448286/202490529-777ef84b-ecfd-4383-a3a2-fb1231fc062a.png)
