### ISSUE TITLE
Remove admin/flagged page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#1978]
Is https://addons.mozilla.org/en-US/admin/flagged still used?  It's actually not worked fully since 2011 when the editor tools were rewritten from php to python (zamboni/olympia) - the flagging person and text is from the `approvals` db table that became obsolete then so you only have an empty list of addon name and version.

@jvillalobos

**Comment by jvillalobos** [comment]
It's not used anymore. We can unflag from review pages, so we don't need this.

**Comment by eviljeff** [comment]
#1982 will remove the approvals table btw
