### ISSUE TITLE
Add the ability to delete versions through the API

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#19784]
### Describe the problem and steps to reproduce it:
Developers have the option to disable and delete versions in DevHub. We should make these actions available in the [version edit](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-edit) API as well.

**Comment by eviljeff** [comment]
splitting this, and focusing this issue just on delete

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-123
