### ISSUE TITLE
IP search chokes on some IP addresses in results

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19781]
In the user admin IP search, some user known IP addresses can cause a 500 error.

https://sentry.io/organizations/mozilla/issues/3664586752/events/9caea18145cc4ca6b4f9703f2bc86b48/?project=6310819

This is because when the IPs are coming from the database in binary, the are grouped together with `GROUP_CONCAT` and then split by the python code, but if the binary string happened to contain a `,` character (which will be the case if a `44` is part of an IP address returned), we try to split on that, resulting in an invalid IP being parsed by the code to display it.

We either need to find a safe separator or find a way to keep the binary IP in hexadecimal form (or even pre-convert it to the IP in string format) until the last minute to avoid this.

**Comment by ioanarusiczki** [comment]
@diox AMO dev was checked -> waiting for stage to deploy

**Comment by ioanarusiczki** [comment]
@diox This is no longer reproducible on -stage.
