### ISSUE TITLE
Code search returns wrong data if it's the last rule

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19797]
STR:
- Create and execute a ScannerQueryRule matching a bunch of add-ons
- Delete all ScannerQueryRules
- Create and execute a ScannerQueryRule matching any number of add-ons (can be 0 to make it easier to reproduce)
- Visit that rule page and click on the link leading to its results

Expected results:
- You see the results for that rule (nothing if the rule matched 0 add-ons)

Actual results:
- You see a bunch of results with no matching rule (and the page can take a while to load, too!), pagination count doesn't match what you'd expect

This is because of the combination of 2 things:
- We have a M2M relationship between `ScannerQueryRule` and `ScannerQueryResults`. When a rule is deleted, the intermediary model instances between the 2 are deleted, but the `ScannerQueryResults` remain, now orphaned
- When Django detects that a filter has only one choice, it skips it (both in the UI and in the query)
 
So when you're down to the last `ScannerQueryRule` because all other rules have been deleted, that filter is skipped even if the corresponding parameter was present in the query string, and because we have some orphaned `ScannerQueryResults`, they are displayed...

We should remove the M2M and see if we can force the application of the filter at all times (that last part may be tricky...)

**Comment by ioanarusiczki** [comment]
@diox Let me know if I can try again, step2 , delete is not permitted yet.

**Comment by ioanarusiczki** [comment]
@diox I tested on -dev with 0 results (no matched addons) -> I see 0 addons on the [rule page](https://addons-internal.dev.mozaws.net/en-US/admin/models/scanners/scannerqueryrule/50/change/)

![on dev](https://user-images.githubusercontent.com/33448286/196749964-7b2ea7d8-8913-4f0a-ab18-f83e76a52ff4.png)

I'll try it on stage too.

**Comment by ioanarusiczki** [comment]
@diox I verified on -stage
 -> I created 2 rules that would match addons , one with 0, deleted all of them 
-> created and executed a rule that would match 2 addons
-> rule page or the matched results display the [2 addons](https://addons-internal.stage.mozaws.net/en-US/admin/models/scanners/scannerqueryresult/?matched_rule__id__exact=19) -> which is the expected result.
