### ISSUE TITLE
Web-extensions names show-up wrong in the installation popup and in about:addons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1979]
**Steps to reproduce:**
1. Sign in to AMO-stage https://addons.allizom.org/
2. Submit a web-extension that contains **kanji/unicode** chars in its name (i.e. https://addons.allizom.org/en-US/firefox/addon/avira-%E5%9F%BC-%E5%9F%BC-%C3%A3-%C4%83%C4%83/) and approve it
3. Install the web-extension
4. Observe its name in the installation popup and in about:addons

**Expected results:**
Web-extensions name is the same in the installation popup, add-ons manager, public pages and all around.

**Actual results:**
Web-extensions name appears with display issues in the installation popup and in about:addons.

Notes/Issues:
Verified on FF45(Win7). **Issue is reproducing only for web-extensions.**
Reproducible in AMO-stage and dev.
Screenshots for this issue: 
![pub](https://cloud.githubusercontent.com/assets/15685960/13988751/046ec240-f116-11e5-8f49-6c458ac51d2a.png)
about:addons ->
![2016-03-23_1603](https://cloud.githubusercontent.com/assets/15685960/13988792/36d61530-f116-11e5-8f93-2ddae4a4830d.png)

**Comment by andymckay-limited-access** [comment]
Since its bugs in the door hanger and about:addons, moved it over to bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1275316
