### ISSUE TITLE
Don't execute a full `COUNT(*)` query for objects in changelist for admin pages that don't display it

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19801]
When displaying lists of items for a particular model in the admin, if `show_full_result_count` on the `ModelAdmin` is `True` (the default), Django execute a full unfiltered `COUNT(*)` query to determine the total number of items in the database. Then, if the number of items is different than the number of items with filters etc applied, this is displayed in the search template in parenthesizes:
![Screenshot 2022-10-18 at 18-08-36 Select addon to change Django site admin](https://user-images.githubusercontent.com/187006/196484776-596f822d-4df4-4769-8434-8fd5c170cbfe.png)

But, if the search template is not shown, or filters not applied, this full unfiltered `COUNT(*)` is executed but is never displayed.

Let's stop wasting time and avoid that query completely when we know the search bar is never going to be displayed and set `show_full_result_count = False` on relevant `ModelAdmin`s.

**Comment by diox** [comment]
> Let's stop wasting time and avoid that query completely when we know the search bar is never going to be displayed and set `show_full_result_count = False` on relevant `ModelAdmin`s.

Even when the search bar is displayed, it's actually rarely useful for us to display the full count. There are very few admins where we are about showing the full count...

**Comment by diox** [comment]
QA: you can't check that the query isn't being made, but we have automated tests for that. Instead, verify that each admin from `/en-US/admin/models/` (with a user that has `*:*` permission) loads properly)

**Comment by ioanarusiczki** [comment]
@diox All modules are displayed on AMO dev with an account that has `*:*` permission.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-124
