### ISSUE TITLE
Integrate canned responses into review decision categories and increase usability

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19818]
Review decision categories (aka _review rejection reasons_) are separated from the canned responses, but serve a similar purpose. Let's link the two together and add some capabilities for efficient finding of the right category.

More details in https://mozilla-hub.atlassian.net/browse/AOP-53

**Comment by bobsilverberg** [comment]
Adding some notes from a meeting between @wagnerand and @bobsilverberg regarding this issue:

Questions:
1. The ability to add reasons is tied to particular actions. Are those the exact same actions for which one can add a canned response? If not, how do we reconcile that?
- This relationship will not change.
- Reasons should become optional for reviewer replies (this is unrelated to this issue, but something they’d like to have changed).
- Currently, only certain canned responses are available depending on your current action. This will go away, and all reasons will be available for every action.

2. Should the reasons work the same way as canned responses, i.e., when choosing one it adds text into the comment field?
- Yes, it should work in a similar fashion.

3. What would happen if a reviewer deleted the text that was added? Do we simply not care about that, and we’ll still record the reason?
- That is probably the only viable option.

4. What if a user clicks a reason, it populates the comments field, and then they click on a different reason, which causes the first to become unselected? Should that also remove the text from the comments field?
- Ideally we would do this, and it's theoretically possible, as long as they have not edited the comments field, but if they change the text that was inserted it would likely be impossible to remove the changed text.

Probably the best way to address numbers 3 and 4 is that it is the reviewer's responsibility to review the text in the comments field to make sure it is accurate, and that it reflects the selected reasons, before submitting the form.

We could introduce a "preview" step, where the system produces a formatted, editable comments box, using the selected reasons as data, which can be built from boilerplate and could, for example, enumerate the reasons. The reviewer could review and change the comments at this point before submitting. This, however, would be more work, and isn't that much different than what we have now which is a simple comments box that can be edited, so probably keeping what we have now makes more sense.

**Comment by bobsilverberg** [comment]
@wagnerand I have an addition question about improving the UX. Can we simply sort the reasons in alphabetical order, and a reviewer can use the keyboard to navigate to the one they want? This would provide a rudimentary search feature, but it would only work based on the first few letters of the reason. Or do you think we need more of an auto-complete widget, similar to what we have on AMO when searching for add-ons?

**Comment by wagnerand** [comment]
> @wagnerand I have an addition question about improving the UX. Can we simply sort the reasons in alphabetical order, and a reviewer can use the keyboard to navigate to the one they want? This would provide a rudimentary search feature, but it would only work based on the first few letters of the reason. Or do you think we need more of an auto-complete widget, similar to what we have on AMO when searching for add-ons?

@bobsilverberg if I am not mistaken, the reasons are already sorted, but there are too many to find the one needed efficiently. We tried to make finding a little easier by prefixing each entry with their category (e.g. `Security`, `Privacy`, `Consent`), but that doesn't help much with an actual search. A widget that filters the list or autocompletes would be an improvement. I also think we might want to move from a select-box to a list of checkboxes, for easier selection of multiple entries. Wdyt?

**Comment by bobsilverberg** [comment]
> > @wagnerand I have an addition question about improving the UX. Can we simply sort the reasons in alphabetical order, and a reviewer can use the keyboard to navigate to the one they want? This would provide a rudimentary search feature, but it would only work based on the first few letters of the reason. Or do you think we need more of an auto-complete widget, similar to what we have on AMO when searching for add-ons?
> 
> @bobsilverberg if I am not mistaken, the reasons are already sorted, but there are too many to find the one needed efficiently. We tried to make finding a little easier by prefixing each entry with their category (e.g. `Security`, `Privacy`, `Consent`), but that doesn't help much with an actual search. A widget that filters the list or autocompletes would be an improvement. I also think we might want to move from a select-box to a list of checkboxes, for easier selection of multiple entries. Wdyt?

I don't have access to prod, so I'm not sure how many reasons there are currently. A list of checkboxes could maybe work, but would they all fit comfortably on the screen? Or were you thinking of a scrollable list of checkboxes? I guess if all the checkboxes are visible on the screen, a reviewer could just use the browser's "Find" functionality to find one, and then click it. Although an autocomplete does sound like possibly the best solution of all.

**Comment by wagnerand** [comment]
> I don't have access to prod, so I'm not sure how many reasons there are currently. A list of checkboxes could maybe work, but would they all fit comfortably on the screen? Or were you thinking of a scrollable list of checkboxes? I guess if all the checkboxes are visible on the screen, a reviewer could just use the browser's "Find" functionality to find one, and then click it. Although an autocomplete does sound like possibly the best solution of all.

We have a bit over 40 reasons currently. That might be too much for all of them to fit on the screen, so it might need to be a scrollable list?

**Comment by bobsilverberg** [comment]
![Oct-31-2022 09-33-35](https://user-images.githubusercontent.com/142755/199020124-ea52b8c3-6c27-4f53-bafc-b675b722251b.gif)

Here's an example with a scrollable list of checkboxes. Note also that one could use the browser's Find function to search for a reason and it will automatically be scrolled into view.

@wagnerand What do you think of this implementation?

**Comment by bobsilverberg** [comment]
![Oct-31-2022 09-47-07](https://user-images.githubusercontent.com/142755/199023451-593b4000-f0ad-4ea8-9cbb-995225697cb1.gif)

Here's an example of using "Find" to locate a reason. With "Whole Words" chosen in the "Find" options, unless the first word of the reason appears elsewhere on the screen, it will simply scroll the reason into view. If a match is found elsewhere it gets a bit annoying as it will first jump you to the other match, but as soon as you get to a unique match on the reason you end up in the right place on the screen with the reason scrolled into view. You can see an example of this in the below screen cap where I turned off the "Whole Words" option, for demonstration purposes.

![Oct-31-2022 09-41-47](https://user-images.githubusercontent.com/142755/199021806-97b2683d-bc34-44c2-b8b0-62ddd825b2f6.gif)

**Comment by bobsilverberg** [comment]
@wagnerand This is a fairly simple change, so if you think it's worth trying I can implement just this UI change for now and we can see how much, if any, it improved the experience for reviewers. WDYT?

**Comment by wagnerand** [comment]
> @wagnerand This is a fairly simple change, so if you think it's worth trying I can implement just this UI change for now and we can see how much, if any, it improves the experience for reviewers. WDYT?

Yes sounds good. Note that I do expect at least some of the words in reasons to appear in other parts of the page, namely the review history. After all, the reason is an abbreviation/keyword for a rejection message. If an add-on has been rejected for that reason (with the corresponding message) before, it would show up as a match. But it's worth giving it a try, maybe it's enough already.

**Comment by bobsilverberg** [comment]
Note that I have opened 3 issues, and associated PRs to implement the feature as discussed above. I will open additional issue(s) to remove the existing Canned responses features once we are happy with the new feature.

**Comment by bobsilverberg** [comment]
@wagnerand Can you please review the current functionality and see if it meets your expectations? If not, we can file some more issues. Also, can you confirm whether we can completely remove the old canned responses functionality now?

**Comment by wagnerand** [comment]
@bobsilverberg This looks great, thank you. Reviewers have started using it and I requested their feedback.

I filed https://github.com/mozilla/addons-server/issues/19981 as a follow-up so that we can get rid of the old canned response tool for extensions.

Themes don't use review reasons yet, I filed https://github.com/mozilla/addons-server/issues/19982 to look into introducing them.

Once themes have moved over to reasons, we can remove the old functionality. If we decide to keep themes on the old canned response system, we can hide the select box on extension review pages.

**Comment by wagnerand** [comment]
Another follow-up: https://github.com/mozilla/addons-server/issues/20129

**Comment by diox** [comment]
@wagnerand @bobsilverberg Is there anything left to do here ? The milestone was closed over a month ago.

**Comment by bobsilverberg** [comment]
Oops, I forgot about this one. I think all of the new functionality is done, but we should clean up and remove all of the code related to the old canned responses. Do you agree @wagnerand ?

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-125
