### ISSUE TITLE
[Intermittent] Themes cannot be reviewed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1981]
Steps to reproduce:
1. Log in to AMO-stage with an admin account https://addons.allizom.org
2. Submit a theme (i.e. https://addons.allizom.org/en-US/firefox/addon/valentina-t/)
3. Review the theme

Expected results:
The theme is reviewed.

Actual results:
An "Oops.." page is loaded.

Notes/Issues:
Issue is reproducing intermittently. 
Verified on AMO-stage  FF45(Win 7). 
Screencast for this issue: http://screencast.com/t/kt5vVzk2wk

**Comment by andymckay-limited-access** [comment]
@ValentinaPC Can you reproduce this? We need to track down the server error for when this occurs?

**Comment by ValentinaPC** [comment]
@andymckay-limited-access : Today I was not able to reproduce this. I'll let you know when I see it again. Could this be...fixed, somehow? Thanks!

**Comment by andymckay-limited-access** [comment]
Closing based on last comment.
