### ISSUE TITLE
Scanners should ignore files that don't have a `filename`.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19815]
A few files are missing on disk (see also #17885), and code-search keeps tripping over them. Let's clear the `filename` field for those, and make code-search ignore `File`s with an empty `filename`.

SQL query to find them: `SELECT id, filename, created FROM files WHERE filename NOT LIKE '%/%';`.

**Comment by diox** [comment]
> SQL query to find them: `SELECT id, filename, created FROM files WHERE filename NOT LIKE '%/%';`.

BTW, the reason this query works to find them is that we migrated all files to a new directory structure in https://github.com/mozilla/addons-server/issues/19193 by going through everything on the filesystem file by file and trying to find the corresponding row in the database, moving the file to the new place and updating the row. So any rows left in the database with the old path, that doesn't have a `/` in it, are rows that didn't have a file on the filesystem.

**Comment by diox** [comment]
Saved the list of affected files in a spreadsheet for future reference https://docs.google.com/spreadsheets/d/1NbFEATVs2DkXGd46yRoabGGcCop5MJ6gM1f3nzRJbH4/edit?usp=sharing

**Comment by ioanarusiczki** [comment]
@diox As discussed, the code search was triggered and sentry entries checked - looks good. 

This will be repeated for AMO stage too.

**Comment by ioanarusiczki** [comment]
@diox 

After repeating testing on stage ->the affected files were ignored + no new errors in sentry
