### ISSUE TITLE
Surface some information about scanner results in reviewer tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#19825]
Now that reviewers are no longer external contributors, we can start surfacing more information about scanner results which we previously didn't for security reasons. 

We currently display a link to the admin page for each scanner result when a version was marked as needing human review by a scanner rule. Since we're not currently requiring VPN for reviewer tools we don't want to reveal too much still, but we could start exposing more basic info about the result itself, like the name of the rule, and maybe some additional information like under `__GLOBAL__` from customs `scanMap`, regardless of whether or not it matched (that will be introduced by https://github.com/mozilla-services/addons-customs-scanner/issues/1491)

**Comment by wagnerand** [comment]
Let's expose the rule name and the matched files and lines. In the process, let's also add an optional "description" (text) field to a rule that we can use to give more guidance on a particular rule.

**Comment by diox** [comment]
QA: This tweaks reviewer tools review page, widening the left column in the versions lists, removing code weight, and adding which scanner rule matched which file when an add-on is flagged by scanners. Please remember not to publicly share screenshots or information about scanner rules in general.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and these are my results:
- reviewer tools version list will display the scanner result (yara, customs) and the matched 'Human readable' rule name for each scanner (if applicable)
- rules matched in addon files will point to the file where the rule has been identified which, in turn, will link to the code manager page for the same file

Here is an example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/623532
