### ISSUE TITLE
Autocomplete API doesn't return icons objects, only returns icon_url

### ISSUE THREAD

**Issue by lharti** [mozilla/addons-server#19838]
All APIs return an `icons` object, except Autocomplete API- it returns icon_url only.

### Autocomplete Response Example:
```
curl https://addons.mozilla.org/api/v5/addons/autocomplete/\?app\=firefox\&appversion\=106.0\&q\=you\&lang\=en-US
```
```JSON
{
  "results": [
    {
      "id": 700308,
      "icon_url": "https://addons.mozilla.org/user-media/addon_icons/700/700308-64.png?modified=1666367036",
      "name": {
        "en-US": "Enhancer for YouTube™"
      },
      "promoted": {
        "apps": [
          "firefox"
        ],
        "category": "recommended"
      },
      "type": "extension",
      "url": "https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/"
    },
    ...
  ]
}
```

### Expected Response:
```JSON
{
  "results": [
    {
      "id": 700308,
      
      // Other APIs still return icon_url
      "icon_url": "https://addons.mozilla.org/user-media/addon_icons/700/700308-64.png?modified=1666367036",
      
      /// Icons object
      "icons": {
        "32": "https://addons.mozilla.org/user-media/addon_icons/700/700308-32.png?modified=4bc8e79f",
        "64": "https://addons.mozilla.org/user-media/addon_icons/700/700308-64.png?modified=4bc8e79f",
        "128": "https://addons.mozilla.org/user-media/addon_icons/700/700308-128.png?modified=4bc8e79f"
      },
      ///
      
      "name": {
        "en-US": "Enhancer for YouTube™"
      },
      "promoted": {
        "apps": [
          "firefox"
        ],
        "category": "recommended"
      },
      "type": "extension",
      "url": "https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/"
    },
    ....
  ]
}
```

**Comment by eviljeff** [comment]
@lharti if you're proficient at python, would you like to attempt this issue too, to fix both sides of the stack?  I can add some pointers about where to start.  (otherwise I can take it)

**Comment by lharti** [comment]
> @lharti if you're proficient at python, would you like to attempt this issue too, to fix both sides of the stack?  I can add some pointers about where to start.  (otherwise I can take it)

I would love that. I was thinking about working on it.

**Comment by eviljeff** [comment]
Great.  Here's the basic work:

The code change itself should just be a matter of adding `'icons'` to the `fields` tuple in [ESAddonAutoCompleteSerializer](https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/serializers.py#L1491).  

But then the tests in `addons/tests/test_serializers.py` and/or `addons/tests/test_views.py` will need updating (I'd see what fails, first of all, or you can look for tests that use `ESAddonAutoCompleteSerializer` in test_serializers.py and 'autocomplete` in the url in test_views.py)

Then the api docs will need updating - https://github.com/mozilla/addons-server/blob/master/docs/topics/api/addons.rst (which renders as https://addons-server.readthedocs.io/en/latest/topics/api/addons.html).

**Comment by eviljeff** [comment]
Then there's possibly a further piece of work to hide the extra field from older (`/api/v3` and `/api/v4`) api users - I need to double-check if it's strictly necessary.  But get the basic patch working first and I'll provide more details if needed.

**Comment by lharti** [comment]
Roger that 👍. 
Thanks for the pointers @eviljeff.

**Comment by bobsilverberg** [comment]
Thank you for your work on this @lharti, nice job!

**Comment by ioanarusiczki** [comment]
@eviljeff 

If I make a request with 
https://addons-dev.allizom.org/api/v5/addons/autocomplete/?app=firefox&appversion=107.0&q=eh&lang=en-US

The response returns "icons" for each addon:

![icons as object](https://user-images.githubusercontent.com/33448286/205854726-87a198aa-9fa5-4657-a851-1ca79cc9e1ac.png)
