### ISSUE TITLE
Convert review action reasons select to a list of checkboxes

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#19843]
This contributes to https://github.com/mozilla/addons-server/issues/19818.

As an improvement to the current UX, instead of displaying the list of available review action reasons in a select box, make them available as a scrollable list of checkboxes.

**Comment by bobsilverberg** [comment]
Here's a screenshot of the new UI:

![Screen Shot 2022-11-01 at 10 03 39 AM](https://user-images.githubusercontent.com/142755/199253804-233b4fb0-2603-490c-ae2d-bf4a832bd65a.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I could check/uncheck reasons . 
What I've noticed is that the message is hidden when no reason is selected, I had to scroll down to see it 

Maybe this explains it better: 
![hidden message](https://user-images.githubusercontent.com/33448286/199500044-db009c70-9a83-4922-adb8-a11777c89a0c.gif)

**Comment by bobsilverberg** [comment]
Thanks for finding that @ioanarusiczki, that's not great UX.  Could you please file a follow-up issue for that and I'll try to fix it.
