### ISSUE TITLE
The upload errors for a version with more than 32chars

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19842]
Followup https://github.com/mozilla/addons-server/issues/19809#issuecomment-1298318644

I re-tested some samples which I used for the linter issue.  

One thing is different on AMO Dev and reproducible for MV2 and MV3: 

when I tried with a longer string such as "123456789.123456789.123456789.123456789" I will get an error 

Version numbers should have fewer than 32 characters.  -> [full validation report](https://addons-dev.allizom.org/en-US/developers/upload/695693cb39bb493fb20731b938843291) would not indicate this error

So it is obvious this comes from the server side -> the linter does not throw this error when I test it locally. 

![error](https://user-images.githubusercontent.com/33448286/199212735-ec5eacc9-6903-4336-8d1f-26a3dc760742.png)

**Comment by eviljeff** [comment]
Fwiw, the model/db limits the `version` field to 255 so I don't see any reason to error on a lower limit.  Though with the linter not allowing any version string greater than 9+1+9+1+9+1+9 (39) anyway we could just drop the check entirely (agree @diox ?)

**Comment by diox** [comment]
Since the linter would be bypassed by admins, maybe keep the check but bump to the field's `max_length` in order not to raise an exception when that happens ?

**Comment by willdurand** [comment]
the linter forbids version strings with a length exceeding 100 chars FWIW

**Comment by ioanarusiczki** [comment]
I get a new error at 33chars+ 
"version":"123456789.214785236.355554444.444"

![new error](https://user-images.githubusercontent.com/33448286/199989974-4c0d2e35-9734-434a-a14a-0571afdcdc84.png)

**Comment by willdurand** [comment]
@ioanarusiczki IMO this looks like a different error so maybe file a new bug?

**Comment by eviljeff** [comment]
should be fixed with #19859

**Comment by ioanarusiczki** [comment]
@eviljeff I'll wait for the fix to land and re-check this.

**Comment by eviljeff** [comment]
> @eviljeff I'll wait for the fix to land and re-check this.

it's merged now (it'll be on -dev in whatever is the normal deployment lag time is)

**Comment by ioanarusiczki** [comment]
@eviljeff Yes, I don't get an error for 33+chars 

with "123456789.123456789.123456789.100000000" for MV2 and MV3

![no errors](https://user-images.githubusercontent.com/33448286/200505930-3968780f-4fa8-481e-b182-74d72ae59b53.png)
