### ISSUE TITLE
A new version submission throws an error for MV2 lang packs which use toolkit versions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#19849]
Followup for https://github.com/mozilla/addons-server/issues/19788

I've noticed for the lang packs errors which don't seem right: 

![error2](https://user-images.githubusercontent.com/33448286/199459780-3efd91ba-dbd2-40cc-85a9-5b3adcdc762e.png)
![langpackapierror](https://user-images.githubusercontent.com/33448286/199459790-81070ce4-f0ff-49c6-a85a-93a0e05bc28c.png)
![langpackserror](https://user-images.githubusercontent.com/33448286/199459793-f872ca59-06a7-4a37-a6a1-0a98dd27e698.png)
![Screenshot 2022-11-02 113910](https://user-images.githubusercontent.com/33448286/199460031-649bed43-167a-4a08-9ec5-223f39244bd9.png)

If I change the ff version from 107 to 108 -> the new version can be uploaded

Notes:
This is reproducible for langpacks which use the actual (but deprecated format) for versions -> on MV2. These throw a warning right now https://github.com/mozilla/addons-server/issues/19809#issuecomment-1299867804 
MV3 won't accept this format -> not with "buildid" in it

**Comment by eviljeff** [comment]
this should have been fixed with #19788

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified the lang packs on MV2, I could not reproduce the errors above, the errors are correct:

**Note:** -> the error is thrown even if the first version is not approved yet (as the message says) -> in my case, first versions were in awaiting review state.  You mentioned last week something about the version being approved, is this an issue? 

![3](https://user-images.githubusercontent.com/33448286/201368559-a7bd5bef-6c1f-40e0-b57d-392b4f923e86.png)
![scenario2](https://user-images.githubusercontent.com/33448286/201368589-b8214055-c704-4204-a9ef-15773dd40658.png)
![scenario-one](https://user-images.githubusercontent.com/33448286/201368590-62b941c3-9dcd-430f-9efa-7ed9bdd9cdc4.png)

I checked with new submission API and signing API :
![new api](https://user-images.githubusercontent.com/33448286/201368695-e6ceaa1d-821d-4bae-906d-43a6c81a27ae.png)
![new submission API](https://user-images.githubusercontent.com/33448286/201368699-854db4f9-ad8d-42f8-8365-7510ccf73d59.png)

 
![submitted version](https://user-images.githubusercontent.com/33448286/201368821-67023457-3ce2-466f-9633-26f54058240a.png)

**Comment by eviljeff** [comment]
> **Note:** -> the error is thrown even if the first version is not approved yet (as the message says) -> in my case, first versions were in awaiting review state. You mentioned last week something about the version being approved, is this an issue?

Mmm, I was using `addon.current_version` which I forgot is set to the latest version pending review if the addon status is nominated... so yeah, that's a bug - it is only supposed to approved versions.  Can you file a follow-up?

**Comment by ioanarusiczki** [comment]
@eviljeff I filed https://github.com/mozilla/addons-server/issues/19964.
