### ISSUE TITLE
Sort by Updated date/Newest are not in order

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#1986]
## steps to reproduce:
1. Load https://addons.allizom.org/en-US/firefox/extensions/?sort=updated
2. Notice that the add-ons are listed by Most recently updated
3. Navigate to the second page
4. Check the recently updated date again
## Observed behavior:

In the second page, we have add-ons which were updated on March 16th when the 1st page ended with add-ons that were updated on March 9th
## screenshot:

Compare the results sorted by updated date on pages 1 & 2 @
https://www.dropbox.com/s/u20chufbk9y3879/Screenshot%202016-03-23%2015.50.38.png?dl=0

**Comment by diox** [comment]
Is that a regression ?

**Comment by krupa** [comment]
Same issue with the Newest sort as well.

First occurrence is on March 21st.

**Comment by diox** [comment]
I don't think it's a new issue.

We have a `last_updated` field on `Addon`, that is set when, well, the addon is updated by the developer. We set it in Elasticsearch when indexing, and when searching we use that field to sort results, but the date we display is *not* that field, instead it's the creation date for the latest version.

**Comment by krupa** [comment]
yep, I have seen this before and there are multiple bugzilla issues regarding the same. It has resurfaced recently on dev and stage. We should either fix this issue or stop testing for it.
