### ISSUE TITLE
Investigate rewriting tests that use mapStateToProps

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/addons-server#19881]
As part of https://github.com/mozilla/addons-frontend/issues/10120, `mapStateToProps` was no longer exported from most components. There are a few tests, however, that use `mapStateToProps` and will therefore fail if we stop exporting it from those components being tested. This means there are a number of components that still export `mapStateToProps`. We should look at all of these tests and see if they can be re-written to not use `mapStateToProps`. It could be that some of them can simply be deleted, and in other cases new tests may need to be written to match the coverage of those currently using `mapStateToProps`.

**Comment by kplotnik** [comment]
Closing the issue - data-sync error
