### ISSUE TITLE
Feature request: Add a privacy nutrition label to AMO

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/addons-server#19882]
Apple added a great new feature to their App Store, being these new "privacy nutrition labels" that quickly summarize privacy information about an app. 
![image](https://user-images.githubusercontent.com/17863082/107832744-43b22080-6d5f-11eb-9b10-3814d11b7a71.png)

Now, Google has seemed to add this feature to its Chrome Web Store as well. It is incredibly convenient.
![image](https://user-images.githubusercontent.com/17863082/107832792-617f8580-6d5f-11eb-9ef3-bb7df73b9fc0.png)

Mozilla should add this feature to AMO as it is the browser being marketed as the best one for privacy. :grinning:

To enforce this rule, Mozilla could adopt a similar requirement to what Apple is doing: to forcefully make app developers add privacy information in their next extension update.

**Comment by kplotnik** [comment]
Closing the issue - data-sync error
