### ISSUE TITLE
santize sitemap.xml parameters

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#19887]
Even though any invalid values for `app`, `section` or `page` would just result in a 404 when nginx tries to serve the file, we should sanitize parameters beforehand to raise for any known invalid values.

**Comment by AlexandraMoga** [comment]
I've verified the sitemap on -dev in comparison with prod by sending various parameters for `section`, `app_name` and `p`. These are my results:

- invalid `section` value:
prod: https://addons.mozilla.org/sitemap.xml?section=foo&app_name=firefox&p=5 => 404 raised by ngnix 
dev: https://addons-dev.allizom.org/sitemap.xml?section=foo&app_name=firefox&p=5 => 404 page displayed by AMO

- invalid `app_name` value:
prod: https://addons.mozilla.org/sitemap.xml?section=users&app_name=bar&p=5 => 404 raised by ngnix 
dev: https://addons-dev.allizom.org/sitemap.xml?section=users&app_name=bar&p=5 => 404 page displayed by AMO

- invalid `p`  value:
prod: https://addons.mozilla.org/sitemap.xml?section=addons&app_name=firefox&p=44.4 => 404 raised by ngnix 
dev: https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=firefox&p=44.4 => 404 page displayed by AMO
prod: https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=firefox&p=12ab => 404 raised by ngnix 
dev: https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=firefox&p=12ab => 404 page displayed by AMO
@eviljeff for the page value, if I'm requesting `p=0` or `p=-1`, the nginx 404 error is still the one served on -dev; should we see the AMO 404 page in this case as well, similar to the previous examples? Also,, requests for out of bound pages, like https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=firefox&p=677 are returning the nginx 404 error page as well. 

- combination of invalid parameters:
prod: https://addons.mozilla.org/sitemap.xml?section=(foo)&app_name=[][][]&p=12.6 => 404 raised by ngnix
dev: https://addons-dev.allizom.org/sitemap.xml?section=(foo)&app_name=[][][]&p=12.6 => 404 page displayed by AMO

**Comment by eviljeff** [comment]
> * @eviljeff for the page value, if I'm requesting `p=0` or `p=-1`, the nginx 404 error is still the one served on -dev; should we see the AMO 404 page in this case as well, similar to the previous examples? 

I did consider it - and the debug option reports those kind of invalid page numbers as a specific error - but it doesn't really add anything, so the validation for `page` is just that it's an integer.

> Also,, requests for out of bound pages, like https://addons-dev.allizom.org/sitemap.xml?section=addons&app_name=firefox&p=677 are returning the nginx 404 error page as well.

That's fine too - we don't want to do any expensive queries to calculate if page 677 is valid or not, and we don't want to do a (relatively) slow file system request either.  nginx can handle it.
