### ISSUE TITLE
Automated verification stalls

### ISSUE THREAD

**Issue by ghost** [mozilla/addons-server#1993]
I'm trying to get my private, i.e., unlisted, add-on signed. Unfortunately, Step 2 "Upload your add-on" stalls indefinitely after uploading a single xpi, which is shown as "validating ... 100% complete", but the Continue button never becomes active.

Please be aware that I'm locked out of my browser right now. I don't care about AMO at all, I just need my private add-on to run in my very own browser again.

Please fix.

**Comment by jvillalobos** [comment]
Can you please attach the XPI for testing? If you don't want to share it this way, you can send it via email to amo-admins AT mozilla DOT org.

**Comment by EnTeQuAk** [comment]
Is this still happening in production? @jvillalobos did you get any xpi send?

**Comment by jvillalobos** [comment]
If it was, then it was probably resolved on the list. Closing for now.
