### ISSUE TITLE
Cannot upload addon sources

### ISSUE THREAD

**Issue by aemdy** [mozilla/addons-server#1995]
When uploading sources for my addon https://addons.mozilla.org/en-US/developers/addon/si%C5%ABlyk-antra%C5%A1t%C4%99/versions/1837316, I am getting a server error http://prntscr.com/ak7slf.

**Comment by jvillalobos** [comment]
Can you attach them here? If not, can you send them to amo-editors AT mozilla DOT org?

**Comment by aemdy-revel** [comment]
Sources sent via email.

**Comment by aemdy** [comment]
Sources sent via email.

**Comment by EnTeQuAk** [comment]
I can't reproduce the server error anymore, does this still happen for you?

**Comment by aemdy** [comment]
@EnTeQuAk, yes. Tried with the same sources on this version https://addons.mozilla.org/en-US/developers/addon/si%C5%ABlyk-antra%C5%A1t%C4%99/versions/1837316

**Comment by andymckay-limited-access** [comment]
@EnTeQuAk is this related to the unicode in the slug?

**Comment by andymckay** [comment]
Closing in favour of #2828 which @diox says more info.

**Comment by diox** [comment]
Because of the unicode name in the slug it might atually be a dupe of mozilla/addons#132
