### ISSUE TITLE
Prepopulate empty review message in reviewer tools for certain actions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19981]
On a reviewer tools review page, if the review text is empty (!) and

* The reviewer selects "Approve" as an action, prepopulate the text area with

"Thank you for your contribution."

* The reviewer selects "Reject" or "Reject multiple versions", prepopulate the text area with

"This add-on didn't pass review because of the following problems:

1)"

**Comment by wagnerand** [comment]
In anticipation of https://github.com/mozilla/addons-server/issues/19982, we might want to do the same thing for themes as well.

**Comment by AlexandraMoga** [comment]
I've verified the Extensions and Theme review pages where a Comment textbox is attached to a review actions and the following actions will display a prepopulated text as follows:

Approve
![image](https://user-images.githubusercontent.com/31961530/205639381-26dcd3b0-34b6-4e91-82c2-32cdef625dd6.png)

Reject
![image](https://user-images.githubusercontent.com/31961530/205639408-35d3379e-6a09-475b-8111-5c8a8b7c5d9c.png)

Reject Multiple Versions
![image](https://user-images.githubusercontent.com/31961530/205639438-219117db-75fb-447d-8ef1-b9bfd60c0f53.png)

@wagnerand One thing to note is that the prepopulated text will not reset if a reviewer switches between review actions. For example, if I'm selecting the "Approve" option and then switch to "Reject", the textarea will remain populated with the "Thank you for your contribution." text.  Do you see this as a problem for the reviewers?

**Comment by wagnerand** [comment]
> @wagnerand One thing to note is that the prepopulated text will not reset if a reviewer switches between review actions. For example, if I'm selecting the "Approve" option and then switch to "Reject", the textarea will remain populated with the "Thank you for your contribution." text. Do you see this as a problem for the reviewers?

I think this is ok for now, thanks.
