### ISSUE TITLE
Replace canned responses for theme review by review reasons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#19982]
For extensions, we introduced review reasons a while ago and are in the process of phasing out the old, separate canned responses system, by attaching a canned response to each review reason.

Themes don't use review reasons yet, but they could be. If we want to get rid of the old canned responses system entirely, we would need to introduce review reasons for themes as well. If so, the review reasons should show for the "Reject" and "Reject multiple versions" action.

**Comment by wagnerand** [comment]
In anticipation of https://github.com/mozilla/addons-server/issues/19982, we might want to do the same thing for themes as well.

**Comment by bobsilverberg** [comment]
Based on the discussion in the PR, the reasons for themes should be different from the reasons for extensions. I gather this means we need two sets of reasons, one for themes and one for extensions.

I guess the best way to implement that is to add a field to the reasons model for `addonType`. This would allow us to use the same admin to edit reasons. The simplest version of this would be that one can only assign one `addonType` to a reason, so if the same reason needs to exist for both extensions and themes, one would add it as two reasons. We could allow for multiple types to be assigned to a single reason, but that complicates things and it doesn't sound like we'll need that very often, if at all.

@wagnerand Does that sound like it will work for you?
@eviljeff Does that sound like a reasonable implementation to you?

**Comment by eviljeff** [comment]
> @eviljeff Does that sound like a reasonable implementation to you?

if we _really_ wanted to avoid duplicates then the `addon_type` field could be `null=True` and a null value (i.e. not set in the admin) would indicate that it was available for both themes and non-themes but it's not essential - I don't think one or two duplicates is the end of the world.

**Comment by bobsilverberg** [comment]
> > @eviljeff Does that sound like a reasonable implementation to you?
> 
> if we _really_ wanted to avoid duplicates then the `addon_type` field could be `null=True` and a null value (i.e. not set in the admin) would indicate that it was available for both themes and non-themes but it's not essential - I don't think one or two duplicates is the end of the world.

That's a good idea! Is that easy to set via the admin? I guess this new field would be a choice field with just `theme` or `extension` as the choices, and not choosing either would be `null`? Or maybe, even better because it would be more explicit, we could have `theme`, `extension` and `all` as choices?

**Comment by bobsilverberg** [comment]
Looking through the existing code, I see we have [THEME_REJECT_REASONS](https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/reviewers.py#L182), but it doesn't seem to be used anywhere. Is that just something that was added but never used?

**Comment by eviljeff** [comment]
> > > @eviljeff Does that sound like a reasonable implementation to you?
> > 
> > 
> > if we _really_ wanted to avoid duplicates then the `addon_type` field could be `null=True` and a null value (i.e. not set in the admin) would indicate that it was available for both themes and non-themes but it's not essential - I don't think one or two duplicates is the end of the world.
> 
> That's a good idea! Is that easy to set via the admin? I guess this new field would be a choice field with just `theme` or `extension` as the choices, and not choosing either would be `null`?

I think the default if it's not set is `-` but can be overridden with `empty_value_display` - but you might need to play around with it.

>  Or maybe, even better because it would be more explicit, we could have `theme`, `extension` and `all` as choices?

Depends what your field type is.  If it's the addon type id it's an integer and you'd have to make up a value for `all`.  But all of this is up to you really - it's an entirely internal model.

**Comment by eviljeff** [comment]
> Looking through the existing code, I see we have [THEME_REJECT_REASONS](https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/reviewers.py#L182), but it doesn't seem to be used anywhere. Is that just something that was added but never used?

iirc its from the old theme review tools - used for persona reviews, pre static-themes.  I must have just forgotten to delete it at the time.

**Comment by AlexandraMoga** [comment]
I've verified the Review action reasons for both Extension and Theme reviews on -dev and these are my results:
- review reasons and canned responses can be now set in admin to be used for Extensions only, Themes only or both Extensions and Themes 
- when a reason is set for Extensions only, the Theme review page will not display that reason; the opposite is applicable when a reason is set for Themes only
- when a reason is set for both Extensions and Themes, the review page for both Extensions and Themes will display that reason
- The Theme review page will show the new Review reasons for  the "Reject" and "Reject Multiple Versions" actions, while Extension review pages also include the "Reviewer Reply" action. I didn't see  "Reviewer Reply" being mentioned in @wagnerand 's request, so I suppose it was not in scope for Theme review pages. 

[Review reasons for Extensions]
![image](https://user-images.githubusercontent.com/31961530/205626522-1b96158d-0ae6-4793-a6a3-92a9b84998c9.png)

[Review reasons for Themes]
![image](https://user-images.githubusercontent.com/31961530/205626537-a3449e5d-5994-453a-9893-6ff708f2e703.png)

**Comment by wagnerand** [comment]
> The Theme review page will show the new Review reasons for the "Reject" and "Reject Multiple Versions" actions, while Extension review pages also include the "Reviewer Reply" action. I didn't see "Reviewer Reply" being mentioned in @wagnerand 's request, so I suppose it was not in scope for Theme review pages.

This is fine, thanks for flagging!
