### ISSUE TITLE
Create new add-on through API when previously deleted

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#2000]
If the owner of a previously deleted add-on tries to upload a new version of it we should create a new add-on for the version.

**Comment by rgh36167** [comment]
would be really helpful,  stumbled over this accidentally.

**Comment by eviljeff** [comment]
@mstriemer can remember any more context on this?  Is it common occurrence?

**Comment by mstriemer** [comment]
I'm not sure how common it is. Seems like an edge case but we allow users to recreate deleted add-ons on the site so seemed like something we should support.

**Comment by eviljeff** [comment]
but we _do_ allow users to re-submit deleted add-ons under the same guid, as long as it's the same user.

**Comment by mstriemer** [comment]
Through the API? That's what this was for.

**Comment by eviljeff** [comment]
yep.  Already fixed then 🎉
