### ISSUE TITLE
Add a setting to enable service worker support in the linter

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#20001]
In https://github.com/mozilla/addons-linter/releases/tag/5.23.0, we added a new CLI flag to enable the background service worker support (MV3+). We should have a waffle switch on AMO to toggle this flag, which will be useful eventually.

The CLI flag to pass to the linter is: `--enable-background-service-worker` and its default value is `false`.

**Comment by eviljeff** [comment]
What's the use case for having a waffle switch v.s a per-env setting (or just landing a patch to permanently enable it when we need to)?

**Comment by diox** [comment]
Discussed that with @willdurand today, let's go with a per-env setting, only enabled on -dev for now, and we'll turn it on in stage/prod when asked (and when we eventually do that, we'll likely want to keep the setting for a while in case we need to change our minds).

**Comment by ioanarusiczki** [comment]
@eviljeff I tried on -dev with what's been tested in https://github.com/mozilla/addons-linter/issues/4605#issuecomment-1325056102 

-> I don't receive an error 

compared to -stage where it's "/background" is in an unsupported format. for now.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-133
