### ISSUE TITLE
Add a 404 route

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2001]
We should have a page that renders a 404 (and possibly other error templates) in development mode without having to enable `DEBUG` or change other settings like mentioned in https://github.com/mozilla/addons-server/issues/1869#issuecomment-202519337

That way we can test the 404 and other error templates easily with the stock settings.

We should also (or, failing that idea) document how to view 404 errors in development.

**Comment by eviljeff** [comment]
This would be a good first bug for someone who knows django.

Getting started for any contributors: https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code

**Comment by eviljeff** [comment]
mentor: @kumar303
