### ISSUE TITLE
Carousel looks broken for "shopping made easy"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2002]
Screenshot from @andymckay:

![screenshot 2016-03-28 14 45 55](https://cloud.githubusercontent.com/assets/90871/14091358/b6d84f80-f537-11e5-8878-424d826f7652.png)

I didn't see this locally, but we might not have that one enabled there. We should see what's up with this being broken.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-01_1032](https://cloud.githubusercontent.com/assets/15685960/14200670/17009baa-f7f5-11e5-956a-34d45cb8626c.png)
