### ISSUE TITLE
Add a RatingLog model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20023]
To ease lookups of ActivityLogs which store some data in json blobs we have additional models for Addons (AddonLog); Versions (VersionLog) etc which link the ActivityLog instance with the related object.  We need to add one for `Rating` too.

**Comment by AlexandraMoga** [comment]
@eviljeff I'm not sure what to verify for this issue. I've checked that rating activity logs are still recorded and compared to what we had previously I didn't see any changes.

**Comment by AlexandraMoga** [comment]
Ok, then I'll add a "qa: not needed" label to make it clear.
