### ISSUE TITLE
Exclude langpacks from check about version number being greater than last signed

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20029]
Releng script failed today because of https://github.com/mozilla/addons-server/issues/19964: a new build was attempted for a 107.x but we already had (listed) langpacks for 108.x, so langpack creation failed with a 409 error.

We should allow this to happen for langpacks, excluding them from that version number check. Build will be re-attempted tomorrow, so we should cherry-pick and deploy that workaround on Nov 29 around 9 am EST, and then notify release management that they can re-run the failed jobs.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified a submission of a lang pack on dev and stage, looks good.

On dev I could submit Version 107.0buildid20221115.145410  after Version 108.0buildid20221115.145410 (previously approved)
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/623594

Same results on stage, first approved version is Version 107.0buildid20221109.173215 but then I could submit lower versions such as 106.0buildid20221109.173215 then 106.0buildid20221008.122012 

https://reviewers.addons.allizom.org/en-US/reviewers/review/1007740
