### ISSUE TITLE
Add more padding above the section header

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2003]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/extensions/?sort=hotness
2. Notice the padding over the section header "Up & Coming Extensions"

## screenshot:
Add more padding above the section header
https://www.dropbox.com/s/4esvxkg3jsmg3u8/Screenshot%202016-03-28%2015.32.47.png?dl=0

**Comment by andymckay** [comment]
It seems like these pages are just missing some breadcrumbs that other similar pages have. Perhaps that would make them more consistent.

**Comment by andymckay-limited-access** [comment]
Scratch that, there's lots of pages without breadcrumbs.

**Comment by krupa** [comment]
Another example: https://www.dropbox.com/s/nuzwqxny0t3w4va/Screenshot%202016-03-28%2015.49.56.png?dl=0

**Comment by muffinresearch** [comment]
Already fixed with heading cleanup.

**Comment by vcarciu** [comment]
Verified as fixed : 
![paddin4](https://cloud.githubusercontent.com/assets/1583842/14203881/302a748e-f809-11e5-8a24-228e1a83f9c6.png)
