### ISSUE TITLE
Can't meet the developers

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2004]
...white on white text it looks like. https://addons-dev.allizom.org/en-US/firefox/addon/integrated-gmail/?src=hp-dl-featured

<img width="1086" alt="screenshot 2016-03-28 15 43 16" src="https://cloud.githubusercontent.com/assets/74699/14092479/fa4204e6-f4fb-11e5-8077-32d6259a01c9.png">

<img width="833" alt="screenshot 2016-03-28 15 44 47" src="https://cloud.githubusercontent.com/assets/74699/14092485/0460bfe4-f4fc-11e5-9a6e-4557b7d8c7e1.png">

**Comment by andymckay** [comment]
Although interestingly https://addons-dev.allizom.org/en-US/firefox/addon/sort-tabs-by-url/ is just fine.

**Comment by vcarciu** [comment]
Verified as fixed

**Comment by vcarciu** [comment]
http://screencast.com/t/LjBFTMGvUOP

**Comment by 18961244441** [comment]
------------------我不会弄，而且我电脑和IOS系统连接不安全，总被攻击网络，我插上你们看看，




 




------------------ 原始邮件 ------------------
发件人: "vcarciu";<notifications@github.com>;
发送时间: 2016年3月30日(星期三) 下午4:50
收件人: "mozilla/addons-server"<addons-server@noreply.github.com>; 

主题: Re: [mozilla/addons-server] Can't meet the developers (#2004)



Verified as fixed

**Comment by 18961244441** [comment]
------------------




 reply@reply.github.com




------------------ 原始邮件 ------------------
发件人: "vcarciu";<notifications@github.com>;
发送时间: 2016年3月30日(星期三) 下午4:50
收件人: "mozilla/addons-server"<addons-server@noreply.github.com>; 

主题: Re: [mozilla/addons-server] Can't meet the developers (#2004)



Verified as fixed
