### ISSUE TITLE
Make `version_created_from_upload` addon-type specific

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20042]
https://github.com/mozilla/addons-server/blob/0768664e5c409dec1a7e993be680498076d06bc2/src/olympia/versions/models.py#L487 records when a version gets created. For better visibility, we want to be able to distinguish the different add-on types there.

**Comment by diox** [comment]
We should probably not touch this timer and instead just send a separate ping that depends on the add-on type.

**Comment by eviljeff** [comment]
a `devhub.version_created_from_upload.<add-on type>` ping (i.e. count) is sent in addition to the timing.

**Comment by AlexandraMoga** [comment]
@eviljeff what should I be verifying for this one?

**Comment by eviljeff** [comment]
@AlexandraMoga there's nothing for QA to verify here - the statsd pings only show up in grafana.  Adding the QA- label
