### ISSUE TITLE
Update reviewer reports to use ActivityLog records

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20041]
We have automated reviewer activity reports but they currently use the `ReviewerScore` records.  With that model/feature going away in #18049 the report sql needs updating to use something different, such as the ActivityLog records we store for every review action.

**Comment by ioanarusiczki** [comment]
@eviljeff Please let me know how can I verify this. 

Thanks!

**Comment by eviljeff** [comment]
There are email reports generated and sent to addon-reviewers@mozilla.org and addon-content-reviewers@mozilla.com which could be looked at in fake mail.  

They're normally triggered by a cron on a Monday but I can trigger it manually if you want.  It should show details of reviews that took place in the previous week (I'm not sure if you want to make any specific reviews before I trigger it).

@wagnerand normally looks at these reports so he may have some specific detail in the report he'd like to confirm?

**Comment by wagnerand** [comment]
I think it would be tricky to test the actual values in there, since every reviewer/QA person (on stage) would have to record how many add-ons they reviewed and what their risk value was. Maybe we can focus on the email format, structure and sections looking right. I can probably help with that. @eviljeff is there a way to deliver the fake email to my inbox so I can see whether it is rendered correctly?

**Comment by eviljeff** [comment]
@wagnerand there's a way, but it's a little involved:  The env variable `EMAIL_QA_ALLOW_LIST` contains addresses that get real emails even in non-prod environments, but env variables need to be set by SRE (Wei or Brandon) in their deployment scripts and then redeployed (and then later repeated to remove your address from the env variable).  Checking the FakeEmail admin for the email is much easier if that's sufficient for you.

**Comment by eviljeff** [comment]
> @eviljeff I reviewed on AMO dev a couple of add-ons today. In case you generate them for fake-email, let me know.

I just ran the command on -dev, so there should be 2 emails in fake email

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO dev -> there are 2 entries -> 
[content reviewers report](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/104160/change/) 
[addon reviewer report](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/104159/change/)


 @wagnerand I'm going to mark this verified. In case there's something wrong , let us know.

With FF:

![report](https://user-images.githubusercontent.com/33448286/211332036-20285192-3260-4ffa-94a8-28b57cce7d6b.png)

![reviewers](https://user-images.githubusercontent.com/33448286/211332040-91f8d8e4-866e-4946-94b8-ac6ce8f356f9.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-139
