### ISSUE TITLE
Have a way to distinguish FxA logins from API logins

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20043]
The [`LOG_IN` activity](https://github.com/mozilla/addons-server/blob/0768664e5c409dec1a7e993be680498076d06bc2/src/olympia/constants/activity.py#L829) records when a user logged in, but we don't know if the login happened through FxA or an API token.

Let's add this information somehow, maybe through a different action, or some other way.

**Comment by diox** [comment]
We don't currently query directly on that action, so we can add a new one (making sure it has the same properties set as `LOG_IN`).

This is created in the callback for the `user_logged_in` signal, so we should add a new kwarg when we send the `user_logged_in` signal from the API to distinguish from "regular" logging in via FxA.

**Comment by ioanarusiczki** [comment]
@diox 

I made a login using the fronted then I used JWT to make an addon submission

Activity log indicates that there are 2 different login ways:

![Activity log](https://user-images.githubusercontent.com/33448286/205881374-aecba874-f540-4a32-bdd3-4882a4f878e3.png)
