### ISSUE TITLE
Improve email searches in user admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20050]
- Make searches faster for exact email/id matches
- Allow basic pattern matching (`foo*@example.com`, `foo@*` etc)

**Comment by diox** [comment]
To do this, we'll:

> Make searches faster for exact email/id matches

- Drop the search on `username`
- Only search against id if all search query parts (separated by a comma) are numeric (previously it would allow mixing emails and ids together)

**Comment by ioanarusiczki** [comment]
@diox 

I verified this on AMO Stage: 

- I could make searches using an e-mail address, or multiple
- When email addresses are combined with ids or IPs -> results are returned for emails, IPs or ids are ignored
- I could search using a single IP or multiple
- I could search using a singe id or multiple
- combined IPs and ids won't return results

- I've noticed that search with a single id (valid)-> won't return a result.  If I use more than one -> I will get results. I filed https://github.com/mozilla/addons-server/issues/20074
