### ISSUE TITLE
Pop-up title old school?

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2005]
e.g on contributions and abuse

![screenshot 2016-03-28 15 48 19](https://cloud.githubusercontent.com/assets/74699/14092545/87423f00-f4fc-11e5-861c-4c53c1cc2508.png)
![screenshot 2016-03-28 15 48 56](https://cloud.githubusercontent.com/assets/74699/14092555/99bbd16e-f4fc-11e5-91e9-f570d663e3c3.png)

Not sure if this is a bug or not though? cc @pwalm

**Comment by pwalm** [comment]
Nope, not a bug.

**Comment by pwalm** [comment]
eehh... on second thought, the only issue that needs to be addressed with the pop-up outline. Let's go with the thin black stroke on the "Make a contribution" pop-up.

**Comment by designakt** [comment]
@pwalm I think it is a bug. Everywhere else we use Open Sans to replace Georgia. Why would you keep Georgia in those cases?
In Privacy Policy pop-up even the copy is Georgia which does not match any other font we use anywhere else on AMO.
![screen shot 2016-03-29 at 14 32 43](https://cloud.githubusercontent.com/assets/8145891/14108009/7f12d924-f5bb-11e5-8dd5-48fcd6309adc.png)

I much rather have these look like this:

![screen shot 2016-03-29 at 14 46 33](https://cloud.githubusercontent.com/assets/8145891/14108365/5a7a45aa-f5bd-11e5-8441-aac5bcc27a84.png)

Also unifying the border and have a black background on all overlays. (The white one does not provide good contrast and the contribution modal does not even use a background.)

.modal {
border: 1px solid grey;
border-radius: 0px;
}

.modal h2, 
.modal .prose {
font-family: "Open Sans", X-LocaleSpecific, sans-serif;
font-style: normal;
}

.modal-overlay {
    background-color: #000;
    opacity: .5;
}

What do you think of my proposal  @pwalm ?

**Comment by pwalm** [comment]
@designakt You are correct! My mistake, I thought we were just talking visual style, not typography.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshots: 
![2016-04-08_1125](https://cloud.githubusercontent.com/assets/15685960/14378256/b1fd418a-fd7c-11e5-9028-0daf42ec4446.png)

@muffinresearch  : The "Write a review" section from theme details, should still have a background?

**Comment by muffinresearch** [comment]
> The "Write a review" section from theme details, should still have a background?

@ValentinaPC That's not a modal so it's not really connected to this bug. But I would say a new bug should be filed for that - I think it would look better without a background.

**Comment by ValentinaPC** [comment]
Yeah, I know is not a modal...but I thought this is a good place to ask. :)
Thanks!
