### ISSUE TITLE
Show `created` and `modified` columns in regional restrictions django admin listing page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20063]
Let's add `created` and `modified` columns in regional restrictions django admin listing page, so I can see when a particular entry was created or updated.

**Comment by ioanarusiczki** [comment]
@eviljeff 

"created" and "modified" are available on[ admin dev regional restrictions ](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addonregionalrestrictions/)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-174
