### ISSUE TITLE
Some Devhub text fields won't throw an error message when the character limit is exceeded

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20069]
#### STR for new addon uploads:
1. Upload a new listed addon on AMO dev or stage
2. On the addon submission form, add some text in the "Notes to Reviewer"  field that exceeds the character limit for this textarea

#### STR for new listed version submissions:
1. Upload a new listed version for an addon
2. On the final submission step, add some text in the "Release Notes" and the "Notes to Reviewer" fields that exceeds the character limit for these textareas

#### STR for editing the Whiteboard from Devhub:
1. Open an add-on Edit page in Devhub
2. Add some text in the "Whiteboard"  field that exceeds the character limit for this textarea

### What happened?
The submission/edit is not successful and there is no error indicating what caused the submission/edit to fail

### What did you expect to happen?
The mentioned textareas should display an error message when the character limit is exceeded

### Anything else we should know?
Both the Release notes and Notes to reviewer fields are displaying an error message when the fields are edited from the Manage versions page in Devhub

**Comment by diox** [comment]
Note: on some key fields, we display "x characters left". I won't add that for every field, it's be too much noise IMHO. Instead I'm just going to set the maximum length so that browsers would prevent users from entering too much text, and raise an error if the user manages to bypass that limit somehow.

**Comment by diox** [comment]
I filed https://github.com/mozilla/addons-server/issues/20079 for the inconsistency you noticed, but it's not a blocker.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-177
