### ISSUE TITLE
White on white text renders the developer name invisible

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2006]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/reviews/add
2. Notice the developer name

## observed behavior:
White on white text renders the developer name invisible

## screenshot:
https://www.dropbox.com/s/ntvl66cfutbolfx/Screenshot%202016-03-28%2015.57.08.png?dl=0

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screeshot: 
![2016-03-30_1241](https://cloud.githubusercontent.com/assets/15685960/14138225/b0b46c54-f674-11e5-9df1-0e6bcf71ebd3.png)
