### ISSUE TITLE
Cannot enable a notable addon for the Primary Hero Shelf 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20068]
Followup for https://github.com/mozilla/addons-server/issues/19976

1. Go to Notable addons group and click one
2. Edit a description, select an image and a gradient color then click on Enabled

Expected result:
Message it's been added successfully

Actual result:
An error message 

![error](https://user-images.githubusercontent.com/33448286/206207320-ca68c529-2e94-4a90-8fbc-d0a2a0f82de1.png)

**Comment by eviljeff** [comment]
Were the add-ons approved for `Notable` at this point?  (i.e. at least one version was shown as approved in the admin)

**Comment by ioanarusiczki** [comment]
@eviljeff They are Notable - as added automatically , I did not submit new versions after they showed up as Notable in admin.

**Comment by eviljeff** [comment]
> @eviljeff They are Notable - as added automatically , I did not submit new versions after they showed up as Notable in admin.

For all the promoted groups (apart from Strategic and Spotlight)* after the add-on is added to the group there needs to be at least one version manually approved first before the add-on is approved for that promoted group.  For the older promoted groups this meant a new upload from the developer.  For Notable there was a requirement that the the existing add-on be flagged for review, and then when the approval was confirmed then _that_ would approve the existing latest version for Notable. So if the add-on hasn't been approved at least once in the reviewer tools (either an auto-approval confirmation via the flagged queue, or an approval of a new version) then it's not approved for Notable so won't be available to be featured on the Primary Hero shelf.  The per version approvals should be shown in the admin page.

*Spotlight and Strategic address this differently - Strategic just doesn't have any per-version approvals; for Spotlight when an add-on is added to the group the latest version is auto-approved for Spotlight.

**Comment by eviljeff** [comment]
> @eviljeff Got it, I must confirm approval first -> then I could add it to Primary Hero. I tried it now with [Private Relay ](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/promotedaddon/117/change/) and it worked.
> 
> I think it makes sense, so this is not a bug, it's expected.

Hah, I was so concentrating on making sure my reply was accurate I missed your follow-up in the mean time.  Sounds like we're good here so I'm going to close.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-176
