### ISSUE TITLE
Search with a single valid id returns 0 results

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20074]
Go to [user admin](https://addons-internal.stage.mozaws.net/en-US/admin/models/users/userprofile/?q=11688217) and make a search using a valid id 

Actual result:
0 results

Expected result:
1 result

**Comment by ioanarusiczki** [comment]
@diox I get 1 result - as expected, verified on -dev and -stage, FF107(Win10).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-180
