### ISSUE TITLE
The "Developer reply" field from version Review history doesn't show an error message when the character limit is exceeded

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20071]
### Describe the problem and steps to reproduce it:
1. As a developer, open the Manage versions page for an addon
2. Click on the Review History to expand the form
3. Post a developer reply which exceeds the character limit for that field

### What happened?
There is a 400 error returned by the `https://addons.allizom.org/api/v5/addons/addon/<addon_id>/versions/<version_id>/reviewnotes/` visible in the browser console but there is no actual error message displayed  in the field.

### What did you expect to happen?
There should be an error message displayed for the Developer reply field when the character limit is exceeded.

**Comment by diox** [comment]
Added a limit so the widget so you won't be able to enter more data than the field allows. This should be cherry-picked once verified on dev.

**Comment by AlexandraMoga** [comment]
The "Developer reply" field from version Review history has a fixed length now of 100.000 characters. 

This issue is verified fixed on -dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-179
