### ISSUE TITLE
`maxlength` attribute not always present in form fields that should have one

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20079]
In https://github.com/mozilla/addons-server/issues/20069#issuecomment-1342402822, QA noticed:
> the Release Notes field from the new listed version submission form doesn't have a `maxlength` set. At the same time, the same field in the Manage versions page has a `maxlength` set, so we have a small inconsistency here.

Looks like it's happening for at least `<textarea>` when there is no initial data set. An error is still raised upon submission, so we're just missing the attribute on the widget.

**Comment by diox** [comment]
This was happening for all translated fields that didn't have initial data set at the time of showing the field. So it was most noticeable for the release notes at version submission (new version, so no data set yet) but could also happen at edit time if the field was empty.

Interesting gotcha for edition: while I was fixing that, I initially only had it fixed for the current language, but we also want it to be set when you switch language using the `Localize for...` menu, so this should be verified as well.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-181
