### ISSUE TITLE
'What are Collections?' section looks squished

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2008]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/collections/kr-raj123/favorites/
2.  Notice the 'What are Collections?' section

## observed behavior:
'What are Collections?' section looks squished and needs to be wider. See screenshot.

## screenshot:
https://www.dropbox.com/s/5m56359uju7jx0t/Screenshot%202016-03-28%2016.13.58.png?dl=0

**Comment by designakt** [comment]
I agree, this looks squished. Adding 46px to the top of .primary should do the trick for those pages.

.primary {
    margin-top: 46px;
}

**Comment by muffinresearch** [comment]
@vcarciu This was cached but we've flushed the cache now and you can see the result here: https://addons-dev.allizom.org/en-US/firefox/collections/kr-raj123/favorites/

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-04_1044](https://cloud.githubusercontent.com/assets/15685960/14241090/5cc00e82-fa52-11e5-9bcc-d6244635ce18.png)
