### ISSUE TITLE
Update grafana charts/alerts to exclude langpack submissions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20080]
(or only count extension submissions?)

**Comment by wagnerand** [comment]
We can keep the existing [graphs](https://earthangel-b40313e5.influxcloud.net/d/3q-fOyOWk/amo-prod-health?orgId=1) combining all submissions. On top of that, let's add new graphs specifically for extensions and themes on this dashboard.

For the alerts, we can either remove the alert on `Uploads Per Day alert` and `Uploads Per Hour Alert`, or increase their threshold. Then, for the addon-type specific graphs, we should set up new alerts with more specific thresholds.

**Comment by eviljeff** [comment]
> On top of that, let's add new graphs specifically for extensions and themes on this dashboard.

Duplicate Uploads, Uploads per hour, and uploads per day for extensions and themes (6 extra charts) or a subset of them?

**Comment by wagnerand** [comment]
I think most relevant here are extensions, since there are no third-party language packs, but I'd also like to hear from @diox and others on the team.

**Comment by diox** [comment]
I guess the main challenge is keeping the dashboard readable...

How about: 
- Remove the Uploads section
- Add a section for Extensions (with all 3 graphs)
- Add another section for Themes (with all 3 graphs)
- Add alerts just for extensions for now.

**Comment by eviljeff** [comment]
Dashboard updated, replacing the current Uploads section with an Extension Uploads and Theme Uploads.  I reduced the existing alert thresholds by ~50% because it's just extensions but they could be reduced further (edit away!)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-182
