### ISSUE TITLE
Add missing report entrypoint for unified extensions (context) menu

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#20098]
QA just noticed that add-ons reported from the unified extensions panel are rejected by AMO because the value sent for the `report_entry_point` field is invalid. The value sent is: `unified_context_menu`.

**Comment by acornestean** [comment]
Verified fixed on -dev.

Sent 2 abuse reports for https://addons-dev.allizom.org/en-US/firefox/addon/spellcheck-enabler/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured and both reports went through and were received on the other end.

Safe to deploy the fix to the other environments.

**Comment by acornestean** [comment]
Verified fixed on -stage.

Sent 3 abuse reports for https://addons.allizom.org/en-US/firefox/addon/devhub-listed-ext-04-29/ and all reports went through and were received on the other end.

Safe to deploy the fix to -prod.

**Comment by diox** [comment]
We've deployed this to production.

**Comment by acornestean** [comment]
Verified fixed on -prod.

Sent 2 abuse reports for https://addons.mozilla.org/en-US/firefox/addon/a-test-extension/ (test extension from William Durand) and the reports went through.
Reviewer tools on William's side correctly state the reason of the report and the associated text I sent when reporting the add-on. So I assume the report was successfully received on the other end.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-186
