### ISSUE TITLE
Display and search by ip address in ratings admin using IP address from Activity Log

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20091]
Instead of relying on the `ip_address` field in the `Rating` model, we should use the `IPLog.ip_address_binary` field instead, both when searching and displaying.

While we're at it, allow searching by IP (which we record for each version submission, including the first) for add-ons.

Prerequisite for https://github.com/mozilla/addons-server/issues/19672

Depends on:
- https://github.com/mozilla/addons-server/issues/20135
- https://github.com/mozilla/addons-server/issues/20140

**Comment by diox** [comment]
Regarding search: you can currently do this by manipulating the URL with `ip_address=<ip>&addon=<addonid>` but a) this only allows a single IP/add-on id and b) this is not easily discoverable, so let's add some UI around this and add multiple IPs/add-ons to be specified.

Note that the `ip_address=` bit is used by `ip_address_link` in `RatingAdmin`

**Comment by ioanarusiczki** [comment]
@diox I see the change now on AMO dev, I'll start testing.
It's not yet on -stage.

**Comment by diox** [comment]
Additional notes:
- Search by IP is also available in the addons admin. It relies on the `ADD_VERSION` activity log
- For ratings, searching by IP for developer replies is not yet supported. It depends on https://github.com/mozilla/addons-server/issues/20168
- For ratings, searching by IP will use add both also edit rating activity logs, with the caveat that it doesn't support edits made before this landed
- For ratings, when searching by IP, an additional option to filter by add-on (for the add-ons that appear in the ratings that were found) is available

**Comment by ioanarusiczki** [comment]
@diox On AMO dev:

- search with a single IP, or multiple IPs worked for me -> separated by comma. Separated with a space will not return results.

- search with a single valid addon ID won't work -> it won't return results 

the URL looks like https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/?q=624046
when modified to https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/?addon=624046 it will return results.

- search with multiple addon ids works -> separated with comma or space. An example https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/?q=624044+620043+620047.  

- multiple ids separated by comma with multiple addon IDs is working, an example (I selected the addons using the filter):
https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/?q=34.133.228.21%2C84.117.102.49&addon=287841&addon=492159

- multiple Ips separated by comma combined with a valid id -> does not return results

**Comment by ioanarusiczki** [comment]
@diox I made some checks on AMO stage too -> looks good. 

I also filed https://github.com/mozilla/addons-server/issues/20180

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-185
