### ISSUE TITLE
Contribution section styling issues

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2009]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=ss

## observed behavior:
Contribution section looks squished. It needs more padding at the bottom. See https://www.dropbox.com/s/jjavimef4c95h8w/Screenshot%202016-03-28%2015.44.36.png?dl=0

 Suggested amount is not aligned with the contribute button - https://www.dropbox.com/s/tgh5kyxe482ydg4/Screenshot%202016-03-28%2015.45.14.png?dl=0

**Comment by krupa** [comment]
Looks particularly bad in de : https://www.dropbox.com/s/xevn3dwdh8pfsky/Screenshot%202016-03-28%2017.19.31.png?dl=0

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/vqimzlA6yi
