### ISSUE TITLE
Next and previous navigation arrows on the details page are clipped

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2010]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=ss
2. Notice the navigation arrows in the screenshot section

## observed behavior:
Next and previous navigation arrows on the details page are clipped

## screenshot:
https://www.dropbox.com/s/jlovmjwswiccw75/Screenshot%202016-03-28%2015.48.34.png?dl=0

**Comment by muffinresearch** [comment]
I don't see the same thing as in your screenshot: 

![adblock_plus____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/14213493/24e56328-f830-11e5-970f-2f6a14366504.png)

**Comment by muffinresearch** [comment]
Going to close this. But reopen it if you can still reproduce the problem.
