### ISSUE TITLE
Review action reason canned response should be optional

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20129]
### Describe the problem and steps to reproduce it:

Currently, the review action reason canned response is mandatory. As such, I cannot change the reason if the canned response is empty. Let make it optional.

STR:
1. Create a new review action reason in django admin, leave _Canned response_ blank.
2. Try to save it.

### What happened?

Saving fails, saying _Canned response_ is required.

### What did you expect to happen?

Reason should have been saved successfully with empty canned response.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand 

I verified on AMO dev -> I could create a new review action reason and leaving the canned response blank. 
Also I could delete the text from the canned response field and then save the review action reason.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-190
