### ISSUE TITLE
'View Statistics' icon is missing from the add-on stats link

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2012]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=ss
2. Notice the add-ons meta-data section which includes the number of users

## expected behavior:
There is a 'View Statistics' icon next to the user count

## observed behavior:
'View Statistics' icon is missing from the add-on stats link. See https://www.dropbox.com/s/6z28jxvaq3tdk0t/Screenshot%202016-03-28%2015.45.50.png?dl=0

**Comment by muffinresearch** [comment]
If we want to fix this and it might be intentionally removed we'll need a new asset.

@pwalm @designakt do we want to keep this icon? 

Here's the link to the current asset: https://addons-dev-cdn.allizom.org/static/img/impala/stats.png?039585f

**Comment by designakt** [comment]
I removed it as I did not see a need for the icon. (the link is still available)
It only increased importance of a tertiary feature which opposes our goal of focusing on the main use of the detail page - install an add-on and understand what it does.

**Comment by muffinresearch** [comment]
Ok great I'll close this then.
