### ISSUE TITLE
Add more throttling around ratings

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20132]
We should have throttling for ratings per day on top of the per minute thresholds we already have.

Let's start with:
- 24 new ratings per user per day
- 36 new ratings per IP per day
- 50 edits/deletes per user per day
- 100 edits/deletes per IP per day

**Comment by ioanarusiczki** [comment]
@diox I tried on AMO stage - >

 with user rusiczki.ioana+35@gmail.com I don't have a throttle per minute. I've also rated more than 24 addons and I did not hit the per user per day throttle.  I think it should be a red warning displayed on frontend in both cases. 

I see the ratings in[ admin](https://addons-internal.stage.mozaws.net/en-US/admin/models/ratings/rating/) too.

**Comment by diox** [comment]
That user belongs to a group with `API:BypassThrottling` permission.

**Comment by ioanarusiczki** [comment]
@diox I checked it too, noticed it's in the lang pack submissions. Thanks, meanwhile I've been hitting the minute throttles and going to see what's happening after 24 +

**Comment by ioanarusiczki** [comment]
@diox 
1.  New Ratings 

After avoiding the throttle/min -> at my 10th attempt I hit per user per day throttle. ->     Request was throttled. Expected available in 74325 seconds.
I used another account on this profile but I still get the previous throttle -> I cannot add new ratings (but it should allow it until it would hit per IP throttle).

Similar results with other accounts papobo9715@dmonies.com -> throttle per user hit after ~ 6 attempts or tehok65359@eilnews.com -> throttle per user hit after ~ 8 attempts
With rusiczki.ioana+36@gmail.com -> I think I made ~ 17 attempts 


![attempt nr10](https://user-images.githubusercontent.com/33448286/210554465-031c042f-b200-48d3-9614-577126cd76dd.png)


2. Edit/delete 

With a first account I started making edit/delete operations:

After  21 edit/delete operations  ->  Request was throttled. Expected available in 75442 seconds.
I used another account and tried again -> I could make 23 more edit/delete operations.  
At attempt 45 -> Request was throttled. Expected available in 74703 seconds.

**Comment by ioanarusiczki** [comment]
@diox I'll have to repeat testing tomorrow as I had mozilla vpn active plus I added score + text for all my attempts.
 
I hope I understood it right:
the score is considered a new rating 
the text is considered an edit action already. - > must be counted into the edits/user/day/IP

**Comment by diox** [comment]
Yes that's correct. If you have devtools opened when you do that, you should see the different requests being made (POST for the initial score, PATCH for the text or changes in the score once posted)

**Comment by ioanarusiczki** [comment]
@diox 

Counting every POST and PATCH operation (including the 429s when I get a temporary throttle) I can confirm the[ above](https://github.com/mozilla/addons-server/issues/20132#issue-1516624383). 

I verified this on AMO stage - FF108 (Win10).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-191
