### ISSUE TITLE
Allow filtering ratings per created date in admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20135]
Add basic filtering of ratings per creation date in the ratings admin (moving code that deals with that from the abuse admin into base class).

**Comment by ioanarusiczki** [comment]
Ratings can be filtered on AMO stage: 

An example, I used [today's date ](https://addons-internal.stage.mozaws.net/en-US/admin/models/ratings/rating/?created__range__gte=2023-01-04&created__range__lte=2023-01-04). Or with a [range ](https://addons-internal.stage.mozaws.net/en-US/admin/models/ratings/rating/?created__range__gte=2022-12-26&created__range__lte=2023-01-31)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-192
