### ISSUE TITLE
Clean up `Version.reviewed` and `File.reviewed`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20147]
Both the `Version` and the `File` model have a `reviewed` field, with the logic of neither being really clear and likely not consistently applied.
We should clean that logic up or remove those fields and start with a clean approach.

Eventually, we might want to have a completion date field or something that stores when a review was completed. The activity log might already do this in some form, but that is not trivial to analyze, so we might want to consider an extra field (probably attached to `Version`?) for easier querying in reports and data analysis.

**Comment by AlexandraMoga** [comment]
@eviljeff It's not clear to me where this info is exposed in the Versions and Files models. I've checked stage to see how this looked before your changes and there is no 'reviewed' field present in either of the models. What should I be testing to verify your changes exactly?

**Comment by eviljeff** [comment]
I don't think the `reviewed` field was exposed in django admin for either `File` or `Version`.  `Version.reviewed` was exposed via the version detail response (i.e. the addon api, and the /versions/ sub endpoints), and used in a few places to determine if a file had been reviewed or not.  

These are the model changes:
- Version.human_review_date is only for when a version has been reviewed by a reviewer
- File.approval_date is set when the file is approved (and signed, if not already signed)
- (if both fields are None then the version/file hasn't been reviewed or auto_approved)

Features/fields that should be verifiable:
- addons or versions api endpoints should still return a `reviewed` field, but it's now the datetime when the version was auto-approved, or the datetime when the version was manually approved or rejected.
- The ability to "request review" on a disabled version in devhub is now dependant on these new fields so the feature should work the same - i.e. if it's been approved or rejected then you can't request review on it.
- Whether you can upload or replace sources on a version is now dependant on whether `human_review_date` is set, i.e. if a manual review has taken place (if it's taken place you can't change/upload sources, unless the version is still pending rejection)
- There are migrations that have backfilled `human_review_date` and `approval_date` so they hopefully should have sensible-ish but it's difficult to verify as we don't directly expose those values.

**Comment by AlexandraMoga** [comment]
@eviljeff I've verified these scenarios on AMO stage and I have the following results (I've prefixed those I'm not sure about with a  [not sure if expected] tag:

- for addons auto-approved by the system the `/addons/` and `/versions` APIs return a `version.reviewed` field with the date and time the version was auto-approved;
  - [not sure if expected] Confirming Approval or Content for this version will not change the datetime value, i.e. Confirming Approval and Content are not considered as manual reviews looks like - [example](https://addons.allizom.org/api/v5/addons/addon/1007748/versions/)
- for versions that were not auto-approved nor manually reviewed (like [this one](https://addons.allizom.org/api/v5/addons/addon/1008168/) which is still Awaiting review) the API will return `file.unreviewed` and `current_version.reviewed.null`
- for versions that were manually Approved ([example](https://addons.allizom.org/api/v5/addons/addon/1008161/)) the API returns the the date and time for the Manual approval in the `version.reviewed` field
- [not sure if expected] for Rejected versions, the API returns a `version.reviewed` field with the auto-approval date if the version has been auto-approved prior to its rejection ([example](https://addons.allizom.org/api/v5/addons/addon/1005865/versions/2479983/))
-  If the version hasn't been auto-approved prior to its rejection, then the `version.reviewed` field will return the datetime of the Rejection ([example](https://addons.allizom.org/api/v5/addons/addon/1004819/versions/2478918/))
- I was able to Request review in DevHub for a version that has been disabled by the developer without having been processed by a reviewer yet - [example](https://addons.allizom.org/en-US/developers/feed/request-review-disabled-v); If the version was Approved or Rejected, the option is no longer present. 
  - [not sure if expected]  the ability to Request review for a disabled version seems to work only with listed addons as far as I can tell. I made the same steps with an unlisted addon and the option to Request review is not present in DevHub. 
- I can upload sources for versions that have been auto-approved, are still Awaiting review or have an active Pending rejection.   For versions that have been Manually approved, Confirmed Approved or Rejected source code upload is no longer possible.
  - [not sure if expected] Note that I was also able to upload sources for a Content approved version. I'm not sure if this action should also block source code submission or not.

**Comment by eviljeff** [comment]
Seems as expected to me.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-197
