### ISSUE TITLE
Add the ability to disable versions through the API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20142]
split from https://github.com/mozilla/addons-server/issues/19784

Developers have the option to disable versions in DevHub. We should make this action available in the [version edit](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-edit) API as well.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I could disable with "is_disabled": true versions of an add-on. 
I could re-enable the disabled versions with "is_disabled": false. 
An already disabled version -> I get a 400 with "File is already disabled."

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-194
