### ISSUE TITLE
Missing breadcrumbs on many pages

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2014]
## steps to reproduce:
1. Compare https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/versions to https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/

## observed behavior:
The new designs on dev are missing breadcrumbs which means that the user has no easy way of getting back to the add-on details page.

## Screenshot:
https://www.dropbox.com/s/mncc1idm8jf6civ/Screenshot%202016-03-28%2016.40.03.png?dl=0

**Comment by designakt** [comment]
We removed the breadbrumbs as the do not provide a lot of help on list and detail-view pages. For further down the hierarchy like version history as shown in your screenshot we can add a way back to the details page, but as in most cases this can be achieved by hitting the back button in the browser, we did not solve this edge case.
Making the add-on name into a link might help without introducing breadbrumbs.

**Comment by tofumatt** [comment]
I think making the add-on title a link back to the main page is perfect.

I was under the same idea that the breadcrumbs don't serve a purpose with the redesign.

I'll make the add-on title a link; if there are any pages that _do_ still have breadcrumbs, please file that as an issue (or post here) and I'll remove them :smile:

**Comment by tofumatt** [comment]
Actually, changing the title to be a link is odd; the text is "Add-on Name Version History", and changing the _entire_ thing to a link implies you're linking to the page you're already on.

Putting the `<a>` tag around only the add-on name seems awkward. This seems like an instance where the back button is probably the best option. If people are okay with that solution I say we do that; otherwise I'll add the link to only the add-on name.

@designakt thoughts?

**Comment by tofumatt** [comment]
@designakt or @pwalm: are you okay not adding the link back to the add-on and relying on the back button here? I'd like to close this out.

**Comment by designakt** [comment]
Let's rely on the back button. Users interested in this page should be experienced enough to deal with that.

**Comment by vanowm** [comment]
> Let's rely on the back button. Users interested in this page should be experienced enough to deal with that.

Please click on the link from OP and rely on your back button show me how to get to the addon's detail page.

How could anyone possible think that having no breadcrumbs is a good idea???
Idiocracy at it's finest...

**Comment by tofumatt** [comment]
@vanowm Please stop insulting the team.
