### ISSUE TITLE
Make `Version.due_date` settable by admins

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20152]
spun off from #19985

An admin reviewer (Reviews:Admin) should be able to set a new and override or clear an existing due date on the review tools page. This action should be recorded in the Add-on important changes history section.

**Comment by diox** [comment]
Note that this should be available even for add-ons not currently waiting for review - that should make them appear in the queue from https://github.com/mozilla/addons-server/issues/19984 even if they are not waiting for review.

**Comment by diox** [comment]
@wagnerand :

Currently we have set up due dates to be automatic, being dropped as soon as the version is auto-approvable, essentially (caveats apply, but the logic is mostly this: version needs to be waiting for review, without flags preventing auto-approval). This is mostly how things worked with the nomination date.

With this issue we are going to have due dates explicitly set by admins (please double-check the permission required to set/clear that btw), on potentially already approved versions. I assume the logic regarding automatically clearing the due date is going to be different in that case. So, should we clear a manually set due date it when:
- Status of the file is changed to disabled ?
- Version is deleted ?
- Version is disabled by developer ?
- Add-on itself is disabled ? made invisible ? deleted ?
- Other scenarios I'm not thinking about ?

(The answers can be different depending on existing status and channel - if so, specify)

**Comment by wagnerand** [comment]
> So, should we clear a manually set due date it when:

(Correct me if you see a case I'm missing but I believe we'd want the following cases to apply to all due dates, regardless of whether they were set automatically or manually?)

>     * Status of the file is changed to disabled ?
* If disabled by developer, only if it was not signed.
* If disabled by an admin, yes.
If that condition adds to much complexity, then we should not clear it.

>     * Version is deleted ?
Only if it was not signed. If that condition adds to much complexity, then we should not clear it.
 
>     * Version is disabled by developer ?
Only if it was not signed. If that condition adds to much complexity, then we should not clear it.
 
>     * Add-on itself is disabled ? made invisible ? deleted ?
* I assume you mean mozilla-disabled (aka force-disabled) for the first case. There we should clear the due-dates for all versions.
* When the developer changes their add-on to invisible or deletes it, we should only clear if the version was not signed. If that condition adds to much complexity, then we should not clear it.
 
>     * Other scenarios I'm not thinking about ?
Some of them might already be done or we are doing them anyway, I'm listing them here to seek completeness:
* When the version gets manually approved, approval confirmed, rejected or delay-rejected.
* When the version gets blocked.
* (I *think* we might also want to clear it on reviewer reply - `REVIEWER_REPLY_VERSION` - but that might not be desired in all cases and I'd like to make sure with reviewers first that this is what we want, so let's do that later if needed.)

In addition to that, we should automatically set a due-date when the developer replies with a message (`DEVELOPER_REPLY_VERSION`), if the version does not already have a due date. If it does, we don't change it. Let me know if you'd like this to be split into a separate issue, but it should land in the same push cycle as this issue.

**Comment by eviljeff** [comment]
I think a lot of these scenarios will get easier if we have a generic `needs_human_review` flag .  _That_ flag can be cleared by some actions - and not others - and then the `should_have_due_date` calculation can just be based on if the `needs_human_flag` is `True` or `False`.  

`Version` already has a `needs_human_review` property which was originally used by the scanners queue, and then was repurposed to be used by new Notable group additions too.  I think we can also use that flag for versions that would otherwise not have been given a due_date because they're not awaiting review.  (But, imo, ideally it would be `VersionReviewerFlags` property rather than directly on `Version` - maybe it should be re-added there, replacing `Version.needs_human_review` and `VersionReviewerFlags`?)  

Some of this depends on if there is a plan to fold the `Human Review` queue into the `Manual Review` queue though.  I assumed so?

**Comment by diox** [comment]
> Some of this depends on if there is a plan to fold the `Human Review` queue into the `Manual Review` queue though. I assumed there was at some point, but not sure if that is still the plan.

@wagnerand this is still the plan, right ? We don't seem to have an issue about it.

**Comment by eviljeff** [comment]
I thought the end state was a single queue that would contain all add-ons that were waiting some kind of human review (possibly still excluding content reviews); but some issues specifically seem to mention pre-review, i.e. reviews on add-ons that don't have any versions awaiting review would be in a separate queue.

**Comment by wagnerand** [comment]
> > Some of this depends on if there is a plan to fold the `Human Review` queue into the `Manual Review` queue though. I assumed there was at some point, but not sure if that is still the plan.
> 
> @wagnerand this is still the plan, right ? We don't seem to have an issue about it.

Yes, this is the plan. We are moving forward with it once reviewers have cleared the current queue as much as possible.

**Comment by wagnerand** [comment]
Generally, we can say that decisive reviewer actions, for instance reject, approve, force-disable, block, ban ..., should clear the due date. Non-decisive actions like reviewer reply or comment should not clear the due date. Also, auto-approval should not clear the due date.

For developer actions, if the version has been signed, no action should ever clear the due date. If the version has not been signed, then actions leading to the file being disabled or deleted should clear the due date.

**Comment by ioanarusiczki** [comment]
@wagnerand @eviljeff 

I set a due date manually as an admin with "Set Needs Human Review" from the review page then made the following actions:

- unsigned version disabled by developer -> the addon is still displayed in the Manual Queue https://reviewers.addons.allizom.org/en-US/reviewers/review/1008149

- signed version disabled by developer -> the addon is still displayed in the Manual Queue 
https://reviewers.addons.allizom.org/en-US/reviewers/review/1006053

- disabled by admin with Force-disable -> the addon is no longer displayed in the queue
https://reviewers.addons.allizom.org/en-US/reviewers/review-content/618526
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1008151

- signed/unsigned version deleted by developer -> is no longer in the queue after it's deleted. I can see the "Set Needs Human Review" button but once clicked it turns gray (nothing happens)
https://reviewers.addons.allizom.org/en-US/reviewers/review/1006059

- reviewer reply on an addon from the Manual Queue and then a developer reply -> the version is still in the Manual Queue
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1006849#review-actions

Other things I've noticed:
- I am not sure what override or clearing means 
- I added the permission testing results here https://github.com/mozilla/addons-server/issues/19986#issuecomment-1413483923. I hope that's fine.
- I did not see anything about setting a human review in the Add-on important changes history section
- Changing a manual due date -> can be done for any date including non-working days and can be changed many times not just once -> probably expected
- addons that are already present in the Manual Queue (flagged for some reason) also have the blue button present on the page. An example: https://reviewers.addons.allizom.org/en-US/reviewers/review/1006850

**Comment by wagnerand** [comment]
> unsigned version disabled by developer -> the addon is still displayed in the Manual Queue [reviewers.addons.allizom.org/en-US/reviewers/review/1008149](https://reviewers.addons.allizom.org/en-US/reviewers/review/1008149)

@eviljeff can you clarify what you implemented from https://github.com/mozilla/addons-server/issues/20152#issuecomment-1397177487. Ideally, this shouldn't be in the queue anymore.

> signed/unsigned version deleted by developer -> is no longer in the queue after it's deleted. I can see the "Set Needs Human Review" button but once clicked it turns gray (nothing happens)
[reviewers.addons.allizom.org/en-US/reviewers/review/1006059](https://reviewers.addons.allizom.org/en-US/reviewers/review/1006059)

Hm, is this a bug or will it be addressed by https://github.com/mozilla/addons-server/issues/20256?
Signed deleted should stay in the queue, unsigned deleted should be removed.

> I am not sure what override or clearing means

Clearing means to unset the due date. I suppose override means changing an existing one?

> addons that are already present in the Manual Queue (flagged for some reason) also have the blue button present on the page. An example: [reviewers.addons.allizom.org/en-US/reviewers/review/1006850](https://reviewers.addons.allizom.org/en-US/reviewers/review/1006850)

seems like a bug?

**Comment by ioanarusiczki** [comment]
@wagnerand 

I forgot the signed/unsigned invisible scenario -> they stay in queue
https://reviewers.addons.allizom.org/en-US/reviewers/review/1008155
https://reviewers.addons.allizom.org/en-US/reviewers/review/1007698

About clearing -> there's no Unset state for the new button (probably not yet). 

The date can be changed , so there's no problem with that.

I'm going to file the bug, looking a bit in the Manual Queue, this is only reproducible for addons that were disabled for auto-approval.

**Comment by eviljeff** [comment]
> > addons that are already present in the Manual Queue (flagged for some reason) also have the blue button present on the page. An example: [reviewers.addons.allizom.org/en-US/reviewers/review/1006850](https://reviewers.addons.allizom.org/en-US/reviewers/review/1006850)
> 
> seems like a bug?

 `due_date` can be for different reasons - in this case because auto approval was disabled. The version isn't explicitly flagged for needs_human_review so the button is available.

**Comment by eviljeff** [comment]
> > signed/unsigned version deleted by developer -> is no longer in the queue after it's deleted. I can see the "Set Needs Human Review" button but once clicked it turns gray (nothing happens)
> > [reviewers.addons.allizom.org/en-US/reviewers/review/1006059](https://reviewers.addons.allizom.org/en-US/reviewers/review/1006059)
> 
> Hm, is this a bug or will it be addressed by #20256? Signed deleted should stay in the queue, unsigned deleted should be removed.

Yes

**Comment by eviljeff** [comment]
> > unsigned version disabled by developer -> the addon is still displayed in the Manual Queue [reviewers.addons.allizom.org/en-US/reviewers/review/1008149](https://reviewers.addons.allizom.org/en-US/reviewers/review/1008149)
> 
> @eviljeff can you clarify what you implemented from [#20152 (comment)](https://github.com/mozilla/addons-server/issues/20152#issuecomment-1397177487)? Ideally, this shouldn't be in the queue anymore.

Was in the queue because it's flagged for `needs_human_review`? That flag is "sticky" - actions by the developer can't affect it.

**Comment by wagnerand** [comment]
> > > unsigned version disabled by developer -> the addon is still displayed in the Manual Queue [reviewers.addons.allizom.org/en-US/reviewers/review/1008149](https://reviewers.addons.allizom.org/en-US/reviewers/review/1008149)
> > 
> > 
> > @eviljeff can you clarify what you implemented from [#20152 (comment)](https://github.com/mozilla/addons-server/issues/20152#issuecomment-1397177487)? Ideally, this shouldn't be in the queue anymore.
> 
> Was in the queue because it's flagged for `needs_human_review`? That flag is "sticky" - actions by the developer can't affect it.

That file wasn't signed. In https://github.com/mozilla/addons-server/issues/20152#issuecomment-1397177487 I mentioned

>> So, should we clear a manually set due date it when:
>> * Status of the file is changed to disabled ?

> If disabled by developer, only if it was not signed.

**Comment by eviljeff** [comment]
> > > > unsigned version disabled by developer -> the addon is still displayed in the Manual Queue [reviewers.addons.allizom.org/en-US/reviewers/review/1008149](https://reviewers.addons.allizom.org/en-US/reviewers/review/1008149)
> > > 
> > > 
> > > @eviljeff can you clarify what you implemented from [#20152 (comment)](https://github.com/mozilla/addons-server/issues/20152#issuecomment-1397177487)? Ideally, this shouldn't be in the queue anymore.
> > 
> > 
> > Was in the queue because it's flagged for `needs_human_review`? That flag is "sticky" - actions by the developer can't affect it.
> 
> That file wasn't signed. In [#20152 (comment)](https://github.com/mozilla/addons-server/issues/20152#issuecomment-1397177487) I mentioned
> 
> > > So, should we clear a manually set due date it when:
> > > 
> > > * Status of the file is changed to disabled ?
> 
> > If disabled by developer, only if it was not signed.

We don't manually clear or set the `due_date` now - it's automatically set or cleared based on the criteria in `VersionManager.should_have_due_date`.  So, on that basis, should I understand that the `needs_human_review` flag should only mean a `due_date` if the file is also signed or it's not disabled?

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-198
