### ISSUE TITLE
Only set `due_date` (nee `nominated`) for add-ons waiting for a human review

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20162]
We currently set `due_date`/`nominated` on all versions that are pending approval, including versions that will be automatically approved.  This doesn't make much sense - auto approval takes place on it's own schedule, not based on the value of the field - and means we can't rely on the field being set _only_ when a manual review is going to take place.

The extra complication is we need to ensure the date is set whenever we're changing flags or other values that would cause a version that would have been auto approved to now need human review.

**Comment by diox** [comment]
This is blocking https://github.com/mozilla/addons-server/issues/19984 because the query for the merged queue needs to a) support both channels and b) exclude auto-approvable add-ons... but the flags that determine this depend on the channel.

I could write a complex query with a bunch of `IF...` conditions, but it's going to be a lot easier and a lot better for performance if we can avoid setting a `due_date` for auto-approvable versions.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I checked on AMO stage the following:

- an addon with the first version auto-approved, added to recommended addons then a v2 is submitted -> the due date is set to 4 days 23 hours (the expected time)

Recommended queue: https://reviewers.addons.allizom.org/en-US/reviewers/queue/recommended

- I manually added an addon to notable group and submitted a new version -> due date is set to 4 days 23 hours (it showed up in Other Pending Review queue besides Versions Needing Human Review)
The example: https://reviewers.addons.allizom.org/en-US/reviewers/review/1007592

- v1 auto-approved then the reviewer disables auto-approval. New version is submitted -> due date is set to 4 days 23 hours
Examples:
https://reviewers.addons.allizom.org/en-US/reviewers/review/1008003
https://reviewers.addons.allizom.org/en-US/reviewers/review/1007521

 - the thirst scenario with an unlisted addon depends on https://github.com/mozilla/addons-server/issues/19985 after it's fixed.
 
- flagged by scanners would go to Versions Needing Human Review or Flagged by MAD for Human Review -> the queues don't have a due date column.


Let me know if my testing is alright.

**Comment by eviljeff** [comment]
@ioanarusiczki that sounds right - but the queues won't be correct until https://github.com/mozilla/addons-server/issues/19984 is fixed

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-200
