### ISSUE TITLE
Refactor reviewer queues to gather title, permission, url in one place

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20174]
The various properties of reviewer queues are scattered across multiple files: `urls.py`, `views.py`, `jinja_helpers.py`, `utils.py`, `queue.html`. We should consolidate all that. Maybe add `title`, `permission` and `urlname` to the various `Table` classes, add a registry `dict` gathering all queues, and then use that everywhere.

The registry already exists, `reviewer_tables_registry`. So really it's all about putting more stuff in the table classes and using that.

**Comment by GregSherman** [comment]
I'm not understanding clearly the requirements here. What I gather is that there are some properties of queues and the contents of queues being fetched in all of these files and passed around as args whereas it's most proper to keep all of these properties inside the tables of utils.py. Would the following code from queue.html be an example of the urlname property that is being fetched in an improper location?:

```html
<h3>
  <a href="{{ review.instance.addon.get_url_path() }}">
    {{ review.instance.addon.name }}</a>
</h3>
```

The goal is to consolidate as much info into this response from the tableobj as possible? (from _queue() in views.py):

```python
return TemplateResponse(
    request,
    'reviewers/queue.html',
    context=context(
        table=table,
        page=page,
        tab=tab,
        unlisted=unlisted,
        more=stuff,
    ),
)
```

**Comment by diox** [comment]
The goal is to reduce duplication and consolidate as much as possible /somewhere/. That somewhere probably is the various `Table` objects in `utils.py`.

To take an example, for the content review queue, if we isolate all the relevant code outside of the `ContentReviewTable` object in `utils.py` we have:
```python
# urls.py
re_path(
    r'^queue/content_review',
    views.queue_content_review,
    name='reviewers.queue_content_review',
),

# views.py
reviewer_tables_registry = {
      'content_review': ContentReviewTable,
}

@permission_or_tools_listed_view_required(amo.permissions.ADDONS_CONTENT_REVIEW)
def queue_content_review(request):
    return _queue(request, 'content_review')

# jinja_helpers.py
if acl.action_allowed_for(request.user, amo.permissions.ADDONS_CONTENT_REVIEW):
    tabnav.append(('content_review', 'queue_content_review', 'Content Review'))

# queue.html
 {% if tab == "content_review" %}
      Content Review – Add-ons for Firefox
```

That's a lot of things repeated, a lot of potential for errors when adding a new queue or modifying something like the url, the title or the permissions required.

To achieve that deduplication, I think we'd need to do something like:
- Move title to the table object, use it in `queue.html`
- Add url path to the table object, use it with the `reviewer_tables_registry` keys to generate the url patterns in `urls.py`
- Move permission to the table object, use it in `views.py` (probably removing the need for the intermediary views that are just an alias to the right `_queue()` call
- Figure out how to make tabnav generation helper work with all that in `jinja_helpers.py`

**Comment by ioanarusiczki** [comment]
@eviljeff @diox 

Let me know how can I test this.

**Comment by eviljeff** [comment]
@ioanarusiczki this should be a transparent change if everything is working as expected - the same review queues are listed on the landing page, with the same titles, and can be accessed as before.  Test with a user without full reviewer admin permissions to check that works too.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-203
