### ISSUE TITLE
GET request for static/css/img/impala/no.png? returns a 404

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-server#2017]
Steps to Reproduce:

1. Load https://addons-dev.allizom.org/en-US/android/extensions/ with the Network Console open, so you can see requests/responses
2. Look at the Network Console

Actual Results:

There's a GET for no.png which returns a 404:

http://www.webpagetest.org/result/160329_9S_J1/1/details/#request35
![get-no-dot-png-404](https://cloud.githubusercontent.com/assets/387249/14094069/ca1e298c-f507-11e5-82ef-a01de1ed5f31.png)

**Comment by muffinresearch** [comment]
Looks to be related to the restyle - I don't see this with refresh off. Works on local -dev just not on a real server.

**Comment by muffinresearch** [comment]
Ok this should be cleared up by #2098
