### ISSUE TITLE
Tweak admin search tooltip to make it more accurate

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20180]
Followup for 
https://github.com/mozilla/addons-server/issues/20091 

As discussed with @diox 

- search by addon ID can be triggered with a minimum of 2 ids -> It's unclear yet if the single id search is required.  If it's not, the tooltip should display this information.

- multiple IP searches can be done when they're separated by comma. The search will not return results when they're separated with spaces. -> Separated by spaces is unclear if it's expected yet. In case it's not then the tooltip should display this information too.

**Comment by diox** [comment]
In both cases, this is the expected behavior and we should just adapt the tooltip:
- It should respect `minimum_search_terms_to_search_by_id`, adding something to indicate this will only work when multiple terms are specified and separated by a comma
- It should clarify that IP searches only work when separated by a comma (`AND` queries are not possible in this case, since it doesn't make that much sense in general)

**Comment by diox** [comment]
Also, the tooltip should never be shown on admins without a search (which should be rare, but do exist) - currently I can get it to show by hovering the UI where the search section would be, even if there is no search for that admin.

**Comment by ioanarusiczki** [comment]
@diox 
- I saw the changes specified in the tooltip 

> Also, the tooltip should never be shown on admins without a search (which should be rare, but do exist) - currently I can get it to show by hovering the UI where the search section would be, even if there is no search for that admin.

I see the tooltip while hovering without a search -> in users, ratings or addons. I'm going to file a followup.

**Comment by diox** [comment]
I meant on admins where search is not possible, where the search input is not available at all. If there is a search input, then the tooltip should always be shown when hovering it.

**Comment by ioanarusiczki** [comment]
@diox Oh sorry, well looking now over -stage I see what you mean. I checked -dev and I don't see the tooltip anymore where a search is not possible.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-206
