### ISSUE TITLE
Button styling for prelim-reviewed add-ons is incorrect

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2018]
## steps to reproduce:
1. Compare a prelim-reviewed addon on dev to that on prod. Example: https://addons-dev.allizom.org/en-US/firefox/addon/03090309-listed-prelim-r-%E6%97%A5%E6%9C%AC%E6%97%A5%E6%9C%AC/?src=cb-dl-created to https://addons.mozilla.org/en-us/firefox/addon/smartalot/?src=cb-dl-created
2. Notice the install buttons.

## expected behavior:
prelim-reviewed add-ons have a different styling for the install button to warn the user.

## actual behavior:
install buttons for prelim-reviewed buttons are missing their distinctive styling.

## screenshot:
https://www.dropbox.com/s/a57pezqxw7xfmlo/Screenshot%202016-03-28%2017.27.58.png?dl=0

**Comment by muffinresearch** [comment]
Fixed in #2055
