### ISSUE TITLE
Addons FxA webhook endpoint is returning 403s to FxA

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/addons-server#20197]
### What happened?

Starting November 10th, 2022, the prod Addons endpoint (https://addons.mozilla.org/api/auth/fxa-notification) started throwing 403s for webhook delivery requests from FxA.

### What did you expect to happen?

200s from this endpoint.

### Anything else we should know?

Per @bbangert:
> We make the request in a uniform manner to all RP's.

Since we don't see any other RPs (relying parties) returning the same errors, we are guessing it might be an issue validating the request.

**Comment by diox** [comment]
Need to trigger password change, primary email change and account deletion from FxA on dev once  https://github.com/mozilla/addons-server/pull/20201 is deployed, and look into the logs.

**Comment by ioanarusiczki** [comment]
@diox Right now this is open , waiting to be closed.

**Comment by diox** [comment]
Sorry, still opened because I haven't got a fix yet, just added more logging to see what's going on. You can try triggering events I noted in https://github.com/mozilla/addons-server/issues/20197#issuecomment-1387437126 and I'll look at the logs.

**Comment by ioanarusiczki** [comment]
@diox 

From the fxA Profile page (which is Manage Firefox Accounts URL that redirects from AMO's Edit Profile Page to fxA stage)

I changed password and the primary email for rusiczki.ioana+35@gmail.com 
Deleted account for rusiczki.ioana+37@gmail. com

**Comment by diox** [comment]
I don't see anything in the logs, unfortunately this could mean it's not connected correctly for our dev environment... We might need to test on stage.

**Comment by ioanarusiczki** [comment]
@diox Done on -stage , same accounts. 

I'll try again -dev with fxA stage, there could be a difference in behaviors but I'm not sure yet.

**Comment by diox** [comment]
The patch to add necessary logging has hit stage yet (needs to be cherry-picked)

**Comment by ioanarusiczki** [comment]
@diox 

Right now on -dev when I changed password and left the edit profile page open in a different tab I an not being logged out. Meanwhile on -stage if I refresh the edit profie page -> I am logged out 

When I switch the primary email , on dev the old email is still displayed (only after I log out and login again I will see it changed). On stage the email address changes to the new one at a page refresh (no need to logout)

**Comment by ioanarusiczki** [comment]
@diox 

I see the same at deleting the account. 

On -dev I am left with a login.
On -stage I'm automatically logged out from AMO.

**Comment by ioanarusiczki** [comment]
@diox 

I don't see a different behavior on -stage after repeating the testing now.

**Comment by diox** [comment]
I can see some errors on stage & prod now with the added logging: `The token is not yet valid (iat)`. `leeway` is 0, since this is not re-using the JWT config we have for our developer API keys.

**Comment by diox** [comment]
The root of the problem is that FxA is sending `iat` as floats with millisecond precision. When we upgraded PyJWT, we got this extra check, https://github.com/jpadilla/pyjwt/pull/794, but PyJWT is using the `iat` provided as is (a float in our case), comparing against the current `datetime` as an integer. So without a leeway, it fails everytime.

https://github.com/jpadilla/pyjwt/issues/814 would likely fix this but is not yet deployed. FxA could also send the `iat` as integer to help, but I think we'll want a short (1 to 5 seconds max - all tracebacks I found didn't need more than 1) leeway just in case.

**Comment by diox** [comment]
Since QA couldn't find any functional issue, I suspect most of these errors could be caused by notifications of events we don't actually care about... But it'd be good to fix in any case.

**Comment by diox** [comment]
Fix is on stage.

**Comment by ioanarusiczki** [comment]
@diox 

I made all the necessary operations again. 

I've noticed at change password that after I'm logged out of AMO and try to login again, I'm asked to Confirm sign-in on email. 

I did not receive the email to confirm the sign-in from the first attempt so I clicked on Resend which works, I'm getting the email. ->  this happened 3/3 attempts 

![not in inbox](https://user-images.githubusercontent.com/33448286/213664333-6e151786-9f9e-41a5-87ca-60bc5a25eb5c.png)

**Comment by bobsilverberg** [comment]
@ioanarusiczki I believe our intention is to push this change (from https://github.com/mozilla/addons-server/pull/20210) to prod today. Has this been verified on stage?

**Comment by ioanarusiczki** [comment]
@bobsilverberg The results [above ](https://github.com/mozilla/addons-server/issues/20197#issuecomment-1398145137) are from today's checking. 
As I said, I did not see changes compared to yesterday's testing on AMO stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-210
