### ISSUE TITLE
Exclude theme reviewers from weekly review reports

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20194]
### Describe the problem and steps to reproduce it:

Likely a regression from #20041.

### What happened?

The review report for add-on (code) reviews also includes theme reviews and reviewers.

### What did you expect to happen?

Theme reviews should be excluded from the report.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
(this was cherry-picked to the 2023.01.19 milestone)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-209
