### ISSUE TITLE
In FAQ page, the link to "open source" goes to http://www.mozilla.com/firefox/organic/ which is a 404

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-server#2019]
Steps to Reproduce:

1. Load https://addons-dev.allizom.org/en-US/faq#license
2. Click on "....open source" link, which goes to http://www.mozilla.com/firefox/organic/

Actual Results:

http://www.mozilla.com/firefox/organic/ is a 404

Unsure if this is:

a) broken link or redirect (301/302) that Mozilla.org should fix and/or
b) broken link AMO should fix

**Comment by andymckay** [comment]
I would just change the link to something like https://www.mozilla.org/en-US/MPL/, or just https://www.mozilla.org.

**Comment by eviljeff** [comment]
Getting started for any contributors: https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code

**Comment by eviljeff** [comment]
mentor: @kumar303

**Comment by lavish205** [comment]
I'm working on this bug.
Should I replace it with [https://www.mozilla.org/en-US/MPL/](https://www.mozilla.org/en-US/MPL/), or just [https://www.mozilla.org](https://www.mozilla.org)

**Comment by eviljeff** [comment]
Lets make it `https://www.mozilla.org/MPL/`

**Comment by kumar303** [comment]
thanks for the patch @lavish205

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7)
Postfix screencats: 
![opensource](https://cloud.githubusercontent.com/assets/15685960/16220817/dcaab2a0-3797-11e6-8c79-415e2dc1aa16.gif)
