### ISSUE TITLE
The new 'Add to Firefox' button doesn't fit in with the "featured" highlight

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2020]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/web-dev-toolbox/
2. Notice the install button for Stylish or any other featured app

## observed behavior:
The new 'Add to Firefox' button doesn't fit in with the "featured" highlight

## screenshot:
https://www.dropbox.com/s/wa2l8c2wpsiknye/Screenshot%202016-03-28%2017.43.16.png?dl=0

**Comment by muffinresearch** [comment]
Fixed in https://github.com/mozilla/addons-server/pull/2086

Note there's a pending deploy of a fix for the sprite images which is logged in https://github.com/mozilla/addons-server/issues/2098

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-08_1107](https://cloud.githubusercontent.com/assets/15685960/14377751/1c58172e-fd7a-11e5-98ae-ea0600476f47.png)
