### ISSUE TITLE
Stop translating reviewer tools/admin tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20208]
Translating admin tools/reviewer tools is not very useful: all extensions reviews are done by staff/contractors these days, and they have to understand English as all communication with developers or staff will happen in English. It's also annoying to translate because translators might not be able to see the strings in action.

Therefore, let's stop doing that. Let's remove all gettext/etc calls around strings in admin tools/reviewer tools.

**Comment by diox** [comment]
Those are fine, it's either because the translated string is coming from a part of the site that is translated (anything a developer would see, like version statuses, activity log action names, etc) or coming from our framework (all the admin stuff).

There will be some inconsistencies for admin/reviewers that decide not to use `en-US` but that's ok.

**Comment by peiying2** [comment]
@diox Thanks for the quick fix. 
From the screenshots, the features will be mixed as partially in English. And as new strings are added, this will be more and more of the case down the road. Not sure if it's better to be left entirely in English or partial. Let's keep it as is. If community complains, I will let you know.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-212
