### ISSUE TITLE
Remove useless `{% with %}` tags in admin tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20215]
https://github.com/mozilla/addons-server/issues/20208 removes translations in reviewer/admin tools. A few `{% blocktrans %}` were changed to `{% with %}` in admin templates to keep the diff simpler, but they serve no purpose and could be removed by changing the variable name(s) used inside the block to use the actual name and not the alias provided by the `{% with %}`

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-214
