### ISSUE TITLE
Some outgoing links (which fail to load) are still wrapped with outgoing-mkt-dev.allizom.org, which resolves to a phx1 host

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-server#2021]
Steps to Reproduce:

1. Load https://addons-dev.allizom.org/en-US/firefox/addon/xmas-song/?src=userprofile
2. Click on http://google.ro in the add-on's description

Actual Results:

https://outgoing-mkt-dev.allizom.org/v1/96a6b374c3b4499d5bd20807e0a47c0110ad48cba98ce2b60932f3ada8c3798e/http%3A//google.ro times out - probably because we've decommissioned this host in PHX1:

sdonners-MacBook-Pro:treeherder-tests sdonner$ nslookup outgoing-mkt-dev.allizom.org
Server:		10.252.75.6
Address:	10.252.75.6#53

outgoing-mkt-dev.allizom.org	canonical name = addons-dev.zlb.phx.mozilla.net.
Name:	addons-dev.zlb.phx.mozilla.net
Address: 63.245.217.110
<img width="1670" alt="screen shot 2016-03-28 at 5 39 50 pm" src="https://cloud.githubusercontent.com/assets/387249/14094586/8be5a94c-f50c-11e5-88a9-66dd347cdb06.png">

**Comment by andymckay** [comment]
Thanks for spotting this.

The link is stored in the database in the text, so it doesnt update, the only way to do this is to walk through the data fixing it. We recently did this on prod to fix up a bug there, but I don't want to do the same for dev. I'd much rather just delete all the data and replace with fake data (I can hope).

For that reason, I'm going to won't fix this.
