### ISSUE TITLE
Configure addons-server to start sending data to GA4

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#20222]
Our plan is to run GA4 in parallel with UA until such a time as UA is discontinued. We will need to make some decisions about what data to send to GA4, but as a starting point we should set up addons-server so the default data (e.g., page views) is being sent to GA4. This issue is about doing that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
When I navigate on dev hub, rev tools pages I get twice a blocked POST and GET request - there's no 204 status (as described into https://github.com/mozilla/addons-frontend/issues/12009#issuecomment-1406419184)

![blocked requests](https://user-images.githubusercontent.com/33448286/219395939-3eda8d9f-5684-4618-9679-cb7ea9c86019.png)


I do see a a 200 request with analytics.js as initiator and `tid=UA-36116321-7` in the request payload.

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. We need to change the CSP for `connect-src` similar to what we did for addons-frontend to address people browsing from non-North American locations. I opened #20380 for this.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-216
