### ISSUE TITLE
In file browser, "Back to addon" should read "Back to add-on"

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-server#2022]
Steps to Reproduce:

1. Load https://addons-dev.allizom.org/en-US/firefox/files/browse/1843/
2. At the bottom left of the file-control links, look at "Back to addon"

Expected Results:

s/addon/add-on

(This might have l10n implications to fix, I don't know.)

**Comment by stephendonner** [comment]
![addon](https://cloud.githubusercontent.com/assets/387249/14094687/54d38586-f50d-11e5-81f8-0973dc88be88.png)

**Comment by eviljeff** [comment]
Getting started for any contributors: https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code

**Comment by eviljeff** [comment]
mentor: @kumar303

**Comment by aelawson** [comment]
Would be delighted to fix this.

**Comment by eviljeff** [comment]
go ahead @aelawson
