### ISSUE TITLE
Increase retention for activity logs that we don't keep forever

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20228]
We want to increase the retention for activity logs that we don't keep forever to 1 year.

**Comment by AlexandraMoga** [comment]
@wagnerand is there anything QA can verify for this issue?

**Comment by wagnerand** [comment]
Good question. @diox is there a way to test this?

**Comment by diox** [comment]
Could manually modify the `created` date of a few `ActivityLog`s:
- Make one older than a year that we're supposed to keep
- Make one older than a year that we're *not* supposed to keep
- Make one younger than a year that we're supposed to keep
- Make one younger than a year that we're *not* supposed to keep (but is too young to delete)

And verify that we kept all of them except the second one.

**Comment by AlexandraMoga** [comment]
I selected a few activity logs to test your scenarios. If I haven't picked suitable examples, let me know which activity logs are we keeping indefinitely and which are deleted regularly.

> * Make one older than a year that we're supposed to keep

LOG IN activity: https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564022/change/

> * Make one older than a year that we're _not_ supposed to keep

RATING THROTTLING: https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564027/change/

> * Make one younger than a year that we're supposed to keep

ADDON SUBMISSION EMAIL RESTRICTION: https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564033/change/ - the activity log is from today but I guess we can make it a bit older than the previous retention time

> * Make one younger than a year that we're _not_ supposed to keep (but is too young to delete)

ADDON SUBMISSION THROTTLING - https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564042/change/ - this is also from today but we could make it not so recent

**Comment by diox** [comment]
> LOG IN activity: https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564022/change/
> RATING THROTTLING: https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564027/change/

Those are now set up as if they had been created over a year ago (366 days ago)

> ADDON SUBMISSION EMAIL RESTRICTION: https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564033/change/ 
> ADDON SUBMISSION THROTTLING - https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564042/change/ 

Those are now set up as if they had been created under a year ago (363 days ago).

The script will automatically run today at 22:00 UTC. So tomorrow only the RATING THROTTLING should be gone, the rest should still be there.

**Comment by AlexandraMoga** [comment]
I've verified the logs and all  except for RATING THROTTLING: https://addons-internal.stage.mozaws.net/en-US/admin/models/activity/activitylog/8564027/change/ are still present.

I'm marking this as verified fixed on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-218
