### ISSUE TITLE
Expose add-on ownership information to reviewers

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20234]
Reviewers should be able to see a list of all add-ons a user owns or owned, with the link to the respective add-on review pages.

**Comment by eviljeff** [comment]
where should this information be shown?

**Comment by wagnerand** [comment]
We probably would need a separate reviewer tools page. Since an add-on can have multiple authors and those authors can have multiple add-ons, it might be tricky to show that on the add-on review page without too much clutter.

**Comment by eviljeff** [comment]
I'm reading this as basically a reviewer version of their public profile page, but with all the add-ons they are (or were) connected to.  (probably minus the extra developer biography, etc ?)

**Comment by wagnerand** [comment]
Yes and with that, it would probably be closer to `/admin/models/addons/addon/?authors=<user-id>`.

**Comment by eviljeff** [comment]
Basic page implemented that shows up to 100 add-ons per user per page (it's paginated for edge case users).  I changed the review page author links to link to it rather than the public profile page.

**Comment by ioanarusiczki** [comment]
@eviljeff 

On the review pages there's an Author section and the names of the authors displayed with a link to a page like this one:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/developer_profile/10641574

Addons are ordered ascending by addon id. Pagination, links all seem to be working as expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-223
