### ISSUE TITLE
Do not require a review reason for reviewer reply

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20232]
### Describe the problem and steps to reproduce it:

When a reviewer sends out a reviewer reply...

### What happened?

...a review reason is mandatory.

### What did you expect to happen?

...the review reason should be optional.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@diox I checked on AMO dev -> on a review/content-review page if I make a reviewer reply the reason is no longer required.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-221
