### ISSUE TITLE
Allow sorting by IP address in ratings admin

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20230]
In the ratings admin, the _IP address_ column should be sort be sortable. ~If possible, there should also be a way to group ratings by IP address, including a count of rating per IP.~

**Comment by diox** [comment]
Grouping needs to be specified more: what should exactly be displayed when grouping, etc. Since it's more complex and requires more discussions, let's move it to a separate issue and ship sorting now, which is trivial to do.

**Comment by diox** [comment]
Also, in the case of multiple IPs, the first one found will matter more for sorting. That's ok though, since it should be the one used for creation.

**Comment by ioanarusiczki** [comment]
@diox

On -dev when I click on IP Addresses I get a 500 server error. -> that's when I don't make a search using multiple IPs, it's with all results (Show all)

**Comment by diox** [comment]
https://sentry.io/organizations/mozilla/issues/3900961281/?project=6224627&query=is%3Aunresolved&referrer=issue-stream

I probably messed that up when I fixed https://github.com/mozilla/addons-server/issues/20248 I'll take a look.

**Comment by diox** [comment]
Weirdly, unit tests are passing, including the one I added for this...

**Comment by ioanarusiczki** [comment]
@diox 

I tried with multiple IPs -> works for me

Now I don't get a 500,  I get[ this ](https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/?o=5.-3) -> the IP Addresses are not displayed (but I see now those are old 2010 results, probably expected).

**Comment by diox** [comment]
Yes, if you toggle the ordering direction (little arrow in that column) or filter out those old results, you should see some data.

**Comment by ioanarusiczki** [comment]
@diox While using By created filter I've noticed that the first entry with IP address is from Aug. 29, 2022, 4:13 p.m

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-219
