### ISSUE TITLE
Replace `needs_human_review` with due date

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20237]
Going forward, versions that need review have a due date. We also have a separate `needs_human_review` flag whose use-cases should be migrated to due-dates. We need to evaluate when we set `needs_human_review` and make sure we set a due date instead.

The patch should not land before the _Versions Needing Human Review_ queue has been cleared. Please confirm with me before landing the patch.

**Comment by diox** [comment]
The approach taken in https://github.com/mozilla/addons-server/pull/20252 has been to keep `needs_human_review` to indicate that this was an explicitly set due date that should never be cleared by non-reviewer actions.

**Comment by diox** [comment]
Closing as we're keeping `needs_human_review` as explained above.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-226
