### ISSUE TITLE
Remove "Auto Approved Add-ons" and "All Unlisted Add-ons" queues

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20239]
The "Auto Approved Add-ons" and "All Unlisted Add-ons" queues are no longer needed. We should remove them.

**Comment by ioanarusiczki** [comment]
@diox 

Auto-Approved Add-ons and Unlisted Add-ons are no longer displayed on https://reviewers.addons-dev.allizom.org/en-US/reviewers/

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-228
