### ISSUE TITLE
Store and show a reason why a restriction was added

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20236]
We have different kinds of restrictions. Many of those can get added manually or automatically by some other action. We should store why a particular restriction was added and show that in the restriction admin.

**Comment by diox** [comment]
Restriction classes should all inherit from the base `RestrictionAbstractBaseModel` abstract class, so it should be just a matter of:
- Adding a `CharField` there
- Generating migrations
- Adding that field to the admins

Then, at the moment I believe the only code that automatically adds restrictions is the `_delay_auto_approval_indefinitely_and_restrict` scanner action (and the related `_delay_auto_approval_indefinitely_and_restrict_future_approvals` which calls that function). Modify that to say something like `Automatically added for scanner rule {rule} on {addon}`.

**Comment by ioanarusiczki** [comment]
@diox

On -dev I've noticed that the disposable domain, email and Ip network restrictions have a "reason" field. 

As an example, I added some text for every module. That's for the [domain restriction](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/disposableemaildomainrestriction/). 

If there's anything else I should be checking, let me know.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-225
