### ISSUE TITLE
Remove "Versions Needing Human Review" queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20238]
Depends on #20237.

After that is fixed, we can safely remove the _Versions Needing Human Review_ queue.

**Comment by eviljeff** [comment]
Assuming #20252 is landed as currently designed, this depends on that associated issue being closed, (and any remaining add-ons in the queue [removed](https://github.com/mozilla/addons-server/pull/20252#issuecomment-1406424988))

**Comment by wagnerand** [comment]
The queue is empty. I think it should be safe to remove this queue now?

**Comment by ioanarusiczki** [comment]
@diox 

"Versions Needing Human Review" queue is no longer available on AMO dev - [reviewers queues](https://reviewers.addons-dev.allizom.org/en-US/reviewers/)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-227
