### ISSUE TITLE
Improve activity log admin

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20245]
The activity log admin listing page should show creation date, user, action and arguments (ideally denormalized), especially when the action is about a particular class we have more information about, like addons, versions, ratings etc.

The activity log admin details page should should show the same with the additional fields provided by the type of the activity log, e.g. addons, versions, IP etc.

**Comment by ioanarusiczki** [comment]
@diox 
on AMO dev models/activity/activitylog/:
- Has the following colums: Created, User, Arguments, Kept Forever, IP Address
- Created and IP Address have sorting option and work as expected
- A tooltip is displayed about searching -> there's no search bar. If I make a search using a [user ID ](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/?q=10642346) it it ignored. When an IP address is used such as [this example ](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/?q=34.28.77.188) I hit a 500 error

**Comment by diox** [comment]
> A tooltip is displayed about searching -> there's no search bar

That should be handled by https://github.com/mozilla/addons-server/issues/20180 (there shouldn't be a search functionality for this admin at the moment).

> If I make a search using a [user ID ](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/?q=10642346)it it ignored. When an IP address is used such as [this example ](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/?q=34.28.77.188)I hit a 500 error

That's https://sentry.io/organizations/mozilla/issues/3907559068/?project=6224627 which I didn't expect ! Can you file a follow-up for this ? It's low priority given that we shouldn't expect search to work, but I'll try to prevent that error.

Searching with `?user=10642346` (which isn't really a search, more of a hidden filter) should work and return activity logs created by that user.

**Comment by ioanarusiczki** [comment]
@diox

Yes, if I use ?user=10642346 the search is working 
I filed https://github.com/mozilla/addons-server/issues/20274

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-229
