### ISSUE TITLE
Add filters to django admin add-ons changelist

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20249]
We want to add a few more filters to the django admin add-ons changelist:

* User creation date (equals, less than, newer than)
* Add-on creation date (equals, less than, newer than)
* User banned status

**Comment by ioanarusiczki** [comment]
@diox On -dev and -stage I checked in the Addons model->  By created , By Author created and By banned filters are available and can be used.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-231
