### ISSUE TITLE
Add-on not available for your platform UX is less obvious in the refresh.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2024]
Old:

<img width="518" alt="featured_extensions____add-ons_for_firefox_for_android" src="https://cloud.githubusercontent.com/assets/1514/14104831/3f698da2-f59f-11e5-8ada-aeb9ee9b5be9.png">

New (with hover applied on the link):

<img width="610" alt="featured_extensions____add-ons_for_firefox_for_android" src="https://cloud.githubusercontent.com/assets/1514/14104836/508ed9f2-f59f-11e5-9408-06b6ef8cfd1c.png">

The refresh version has a lot of whitespace and requires a hover to show the add-on is not relevant. This is all a bit mystery meat. Also if you're only using the keyboard there's no way to infer any information without clicking through so it's a bit of a a11y issue too.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-05_1041](https://cloud.githubusercontent.com/assets/15685960/14274613/0ec332f8-fb1b-11e5-9b6e-06f31a216b37.png)

If this is not the intended behavior, please reopen.
