### ISSUE TITLE
500 server error with Override failed validation 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20258]
I tried to override failed validation using Administrative overrides for an add-on 

Expected: 
As an admin I can continue the submission

Actual:
500 server error -> it is reproducible on both dev and stage 

@wagnerand I filed an issue but I am not sure the feature is of any use.

**Comment by wagnerand** [comment]
@ioanarusiczki thanks! The feature is of use, although not very often.

**Comment by eviljeff** [comment]
looks like the (now unused) request parameter was removed in https://github.com/mozilla/addons-server/pull/19168

**Comment by ioanarusiczki** [comment]
@eviljeff Works now on AMO dev - FF109(Win10).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-235
