### ISSUE TITLE
Unlisted submission flag

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20250]
For new unlisted add-ons, we want to set an internal flag during submission.

If that flag is set, we delay auto-approval for X hours from the creation of the add-on.
The flag should be exposed as a filter on the django admin addons changelist. The corresponding admin detail page should have a way to set or unset the flag.

X should be a zadmin-config.

**Comment by eviljeff** [comment]
> For new unlisted add-ons, we want to set an internal flag during submission.

Can you expand on how this flag is set during submission? It obviously can't be set via django admin _before_ the add-on has been created (the add-on doesn't exist); but if it's after submission won't the xpi have potentially already been signed?  (If the intention is to catch the submission between submission and auto-approval how would the admin know to adjust the auto approval time for that particular add-on submission)

**Comment by diox** [comment]
> X should be a zadmin-config.

It will be called `INITIAL_DELAY_FOR_UNLISTED`, default to 0 and will be evaluated to set a delay at version creation time. Changes to the value will not affect versions created before the change.

**Comment by ioanarusiczki** [comment]
@diox 

I've noticed a new section on the addon's /change/ page. 

Please let me know if I must add  INITIAL_DELAY_FOR_UNLISTED with value 0 in Configs to test this or it's just about checking that addon reviewer flag section works for each action.

There's a "Auto approval delayed until" and "Auto approval delayed until unlisted ", with a Date field, I tried a couple of formats but I get "Enter a valid date."

**Comment by diox** [comment]
Small issue we need to fix:

Although we do want all versions during the period to be delayed, if an admin drops the flag, it should not be set again. 

Currently there is an issue where if someone submits an unlisted first version, and `INITIAL_DELAY_FOR_UNLISTED` is set, their approval gets delayed as expected, but if an admin removes the flag and the developer then submits another listed version still during the delay period, the flag is set again, delaying that version as well.

**Comment by ioanarusiczki** [comment]
@diox 

Then in admin [config](https://addons-internal.dev.mozaws.net/en-US/admin/models/zadmin/config/) I added INITIAL_DELAY_FOR_UNLISTED with value 2023-02-10 but the submitted unlisted addon was auto-approved. Means my value is invalid ?

**Comment by ioanarusiczki** [comment]
@diox 

On AMO dev:
- I set the delay to a day for [this addon](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/624749/change/) -> the date in admin is correct but when I check the [rev tools page](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/624749) and the [Manual queue ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/extension?page=2) the due date is 5 days, 23 hours from now
- I set the delay for 10 days for [this addon](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/624748/change/) That would be on Saturday -> it is displayed in admin but as for the first example the due date in rev tools and the Manual queue is 5 days, 23 hours from now. 

on AMO stage:
- I set the time for 5 min. This is the[ example](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1008144). The due date was 5 days, 23 hours but after waiting the 5 minutes, it's been auto-approved and now it's no longer displayed in the Manual Queue.
- with an invalid value (already confirmed) or value set to 0 -> I don't have a delay set in admin, the [addon](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1008145) was auto-approved 
- this[ addon ](https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1008143/change/) is delayed until tomorrow but same as noticed on -dev, the review-unlisted page and the queue display the default due-date interval 5 days, 23 hours from now

**Comment by diox** [comment]
Due date is still automatically set and follows regular rules for weekends etc, while the delay is separate and doesn't. That should be fine.

> I set the time for 5 min. This is the[ example](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1008144). The due date was 5 days, 23 hours but after waiting the 5 minutes, it's been auto-approved and now it's no longer displayed in the Manual Queue.

It has been approved after the delay (created at 2023-02-01 13:58:49, delay was until 2023-02-01 14:03:49, it was automatically approved on 2023-02-01 14:05:40) as expected.

**Comment by ioanarusiczki** [comment]
@diox Yes, I suspected it's expected. Should the review pages indicate somehow that there's also an auto-approval delay already set from admin?

**Comment by diox** [comment]
Yeah, but we didn't have time to do that for this week. It'll be done in https://github.com/mozilla/addons-server/issues/20251

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-232
