### ISSUE TITLE
Themes listings have layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2025]
Steps to reproduce:
1. Load any theme category page on AMO-dev  (i.e. https://addons-dev.allizom.org/en-US/firefox/themes/film-and-tv)
2. Observe the "Up & Coming" section

Expected results:
There are no layout issues.

Actual results:
There is a white padding after the columns.

Notes/Issues:
**I think same thing is happening in theme details page for "more.." section.**
![2016-03-29_1513](https://cloud.githubusercontent.com/assets/15685960/14107524/73bfd8f0-f5c1-11e5-96e8-33cc23604999.png)

Verified on AMO-dev FF45(Win 7). 
Screenshot for this issue: 
![2016-03-29_1416](https://cloud.githubusercontent.com/assets/15685960/14106544/81423808-f5ba-11e5-8f94-70c437fea1ad.png)

**Comment by ValentinaPC** [comment]
The "Up & Coming" section is fixed on AMO-dev FF45(Win 7) 
![2016-03-31_1836](https://cloud.githubusercontent.com/assets/15685960/14181526/e4f72abe-f76f-11e5-8f95-5681b12d9563.png)

But the issue mentioned at notes is still reproducible.
Please see the screenshot: 
![more](https://cloud.githubusercontent.com/assets/15685960/14181500/ccadeb6e-f76f-11e5-88de-80fea8269370.png)

**Comment by tofumatt** [comment]
Sorry, what is the URL for the unresolved section?

**Comment by ValentinaPC** [comment]
Theme details page: https://addons-dev.allizom.org/en-US/firefox/addon/dark-fox-18066/

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-04_1007](https://cloud.githubusercontent.com/assets/15685960/14240386/34872982-fa4d-11e5-8b14-84a9b473591e.png)
