### ISSUE TITLE
Project initialization issues

### ISSUE THREAD

**Issue by dhirensr** [mozilla/addons-server#20263]
### Describe the problem and steps to reproduce it:
While following https://addons-server.readthedocs.io/en/latest/topics/install/docker.html, I'm facing some issues with worker and web containers in docker

### What happened?

web and worker containers in the docker are returning errors related to supervisord.

```
PermissionError: [Errno 13] Permission denied: '/code/logs/supervisord-celery.log'
```

### What did you expect to happen?

I expected for user olympia to have all permissions.

#### Question :

I see in the dockerfile the user https://github.com/mozilla/addons-server/blob/master/docker-compose.yml#L26 being used is olympia, which is causing problems for supervisord related command in both containers.
1. Is there any steps missing in https://addons-server.readthedocs.io/en/latest/topics/install/docker.html ?

**Comment by diox** [comment]
Hi,

What host OS are you using ? What's your user `uid` on the host running docker (`id` command tells you) ?

**Comment by dhirensr** [comment]
OS : ubuntu 20.04

Uid : dhirensr

should this be run as sudo ?

**Comment by dhirensr** [comment]
uid=1001

I change the both the args in dockerfile but seems to have the same behaviour.

```
worker_1           | PermissionError: [Errno 13] Permission denied: '/code/logs/supervisord-celery.log'
```

```
git diff

 ENV PYTHONDONTWRITEBYTECODE=1
 
-ARG GROUP_ID=1000
-ARG USER_ID=1000
+ARG GROUP_ID=1001
+ARG USER_ID=1001
 
```

**Comment by diox** [comment]
`ARG` in docker file are used at build time, so you'd need to rebuild the image. You don't need to modify the `Dockerfile` though, you can pass `--build-arg` to `docker build` command.

So something like the following (outside the container, from your host):
- Make sure docker images are stopped
- Go to `addons-server` repository root
- Make sure you are the owner of every file/directory (check `/code/logs/supervisord-celery.log` in particular, but there might be other. Probably safer to do a `chown -R 1001:1001 .` from the repository root.
- `docker build -t addons/addons-server:latest --build-arg ARG GROUP_ID=1001 --build-arg USER_ID=1001 .` 
- Then use `docker-compose` as normal from the docs.

**Comment by dhirensr** [comment]
Thanks @diox for help, now that I've setup everything, I'll go through the issues and look for contribution.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-238
