### ISSUE TITLE
Refactor queues in `AddonManager` to get rid of `get_queryset_for_pending_queues`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20262]
We called `get_queryset_for_pending_queues()` by accident when meaning to call `get_pending_review_queue()` to fix some data today. That method is too misleading, and not very useful on its own. Let's:
- Move the code common between `get_pending_review_queue` and `get_themes_pending_manual_approval_queue` in `get_queryset_for_pending_queues()`
- Rename `get_queryset_for_pending_queues()` to prefix it with an underscore or something
- Remove any obsolete methods while we're at it (`get_addons_with_unlisted_versions_queue()`)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-237
