### ISSUE TITLE
500 error while searching with an IP address in activitylog admin

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20274]
Go to admin Activity Logs and make a search with an IP address like [this](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/?q=188.24.88.85)

Expected: 
No 500 server error

**Comment by diox** [comment]
Search is not supported at all in activity log at the moment, so the `q` parameter should be ignored instead of raising an error.

**Comment by diox** [comment]
Actually, I'll do a basic implementation of search by IP in activity log admin, it's relatively straightforward and might come in handy.

**Comment by ioanarusiczki** [comment]
@diox I no longer get a 500 on AMO dev. Also searches with multiple IP addresses is working.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-241
