### ISSUE TITLE
"Make this Collection Public/Private" button from My Favorite Add-ons page does not work

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2028]
Steps to reproduce:
1. Log into AMO-dev https://addons-dev.allizom.org
2. Load  "My Favorite Add-ons" page (https://addons-dev.allizom.org/en-US/firefox/collections/TestDev1/favorites/)
3. Click the "Make this Collection Public/Private" button

Expected results:
The collection status is changed.

Actual results:
The collection status is not changed.

Notes/Issues:
Verified on AMO-dev FF45(Win 7). Not reproducible in AMO-stage
Screencast for this issue: http://screencast.com/t/hydtjJX4WtF

**Comment by tofumatt** [comment]
Odd that this is working locally (development) and on stage.

Is there a problem with the data on -dev? Where would I go to see this?

**Comment by tofumatt** [comment]
This shouldn't be a style problem and may be an issue with -dev.

**Comment by tofumatt** [comment]
Can QA verify this is still happening and re-open if so? dev was wonky so I think it wasn't working but everything else was.

**Comment by ValentinaPC** [comment]
It's taking a bit longer than usual, but it is working as expected.
Verified as fixed on AMO-dev FF45(Win 7).
