### ISSUE TITLE
Please provide an API endpoint or a command that returns a list of changed files for the past X hours

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#20289]
When we sync files between AWS EFS and GCP Filestore, the tool GCP provides (i.e. the file transfer agent) takes more than a day to finish scanning the whole directory tree. As a result, the delta sync between the two filesystems takes that amount of time to finish. This is not useful in reality because we would like to finish the delta sync within the migration window.

What GCP proposes is to generate a "manifest" [[1](https://cloud.google.com/storage-transfer/docs/manifest)] and provide that to the file transfer service to skip the directory tree scanning step.

Thus this ticket is to request to provide an API endpoint or a command that returns a definitive list of changed files for the past X hours, and once we get the list of files, we'll feed that to the file transfer tool and have it transfer all the files.

Another idea is to return a definitive list of changed sub-directories, and we can use the `rsync` command to sync those. This way if files are removed from the source, `rsync` knows remove them from the destination automatically. At the moment, I'm not sure if the GCP file transfer tool supports this or not, but it's worth testing it out.

**Comment by diox** [comment]
> Another idea is to return a definitive list of changed sub-directories, and we can use the `rsync` command to sync those. This way if files are removed from the source, `rsync` knows remove them from the destination automatically. At the moment, I'm not sure if the GCP file transfer tool supports this or not, but it's worth testing it out.

That would be a lot easier. To figure that out, here is the list of user-generated files we deal with:

Type of file | Base directory | Need to sync | Can find modified date from db | Has subdirectory we could sync |
------------ | -------------- | ------------ | ------------------------------ | ------------------------------ |
User avatar | ? | ? | ? | ? |
XPI files | ? | ? | ? | ? |
Add-on uploads | ? | ? | ? | ? |
Add-on extractions | ? | ? | ? | ? |
Source files | ? | ? | ? | ? |
Add-on previews | ? | ? | ? | ? |
Theme previews | ? | ? | ? | ? |
Previews uploads | ? | ? | ? | ? |
Icon uploads | ? | ? | ? | ? |
Add-on icons | ? | ? | ? | ? |
Editorial images | ? | ? | ? | ? |
Sitemaps | ? | ? | ? | ? |
Git storage | ? | ? | ? | ? |
Blocklist | ? | ? | ? | ? |

We should investigate and fill out that table. I wrote [a doc](https://docs.google.com/document/d/1fn-C0nl5wFAur4yEsPiEoXAKznAxl4u1TGcvaqLD_N4/edit#heading=h.xvaaenu42kv3) last year that documents some of this, but it needs updating with the work we did to make the directory structure deeper where that was needed.

**Comment by eviljeff** [comment]
Updated the table.  Git storage is the one that concerns me most - it's a huge amount of files per add-on and although we can reliably-ish work out if the add-on has had a new version added, for an add-on with a large number of versions we'd have to provide the entire folder for the add-on, and the git storage is prefilled async so it won't match up to the file creation time..

**Comment by diox** [comment]
The command is `get_changed_files` and takes a number of seconds from now. It will return a list of directories with potentially added/modified/deleted files in them to sync. The directories themselves are not guaranteed to exist in either location.

**Comment by bqbn** [comment]
I tested the command in the `dev` environment, and it was able to generate a list of directories as expected. Thank you for the quick action on this issue.

When I think about running this command continuously (e.g. every X hours), there are some important metrics we probably want to watch, for example, the number of directories (or files) transferred, the time it took for one run of the command, and etc.

Because the application already has a built-in method to send its metrics to the local statsd, is it possible to provide a `sync` command that wraps the Linux `rsync` tool? For example, 

```
./manage.py sync --since 3600 <dest>
```

where `dest` can be configured via an env variable, and is in the form of `<remote_host>:<root_dir>`.?

**Comment by eviljeff** [comment]
@bqbn can you file a follow-up issue with more details because this is quite a different ask than just outputting a list. For a start: what, if any, rsync options would need to be set (or would that also need to be configurable?); is `dest` an env variable like the other env variables used in addons-server (i.e. loaded from the `.env` files into django settings) or a command line argument to the command?

**Comment by bqbn** [comment]
Yeah, that makes sense. Thanks!

**Comment by bqbn** [comment]
@eviljeff @diox how feasible is it to generate a list of files, instead of a list of directories?

I tried to feed the generated list of directories to Google's file transfer tool and that didn't work (because Google's tool only supports files).

Also, one thing I noticed is this command will output a directory that doesn't contain any recently changed files. I suspect it outputs such a directory because files were deleted from that directory recently. Is this expected?

**Comment by eviljeff** [comment]
> @eviljeff @diox how feasible is it to generate a list of files, instead of a list of directories?

For some types of file it'll be easy, but I'm not sure for all of them, it'll need some investigation (and the code reimplementing)

> I tried to feed the generated list of directories to Google's file transfer tool and that didn't work (because Google's tool only supports files).

Did `rsync` not work out?

> Also, one thing I noticed is this command will output a directory that doesn't contain any recently changed files. I suspect it outputs such a directory because files were deleted from that directory recently. Is this expected?

In some cases it'll be because the file was deleted.  In others we just don't know if a file has been modified because there's no specific timestamp to query - e.g. if the user updates their profile photo we don't have a specific model for it, so only the `UserProfile.modified` timestamp is updated, but that's also updated for other reasons.  We have to err towards over-syncing to avoid missing something.

**Comment by bqbn** [comment]
> Did rsync not work out?

I haven't tried `rsync` yet. It should work.

> We have to err towards over-syncing to avoid missing something.

Over-syncing is fine I think.

**Comment by bqbn** [comment]
We found a couple of issues with the command so far,

First is that the command will output an non-existing sub-directory, but at a wrong level. For example, it would output `/mnt/efs/addons-dev.allizom.org/shared_storage/uploads/userpics/52/2552/10642552/`, and when we tried to rsync it, the error is,

```
2023-03-13 04:01:11,110 amo_rsync WARNING    Failed to rsync from `/mnt/efs/addons-dev.allizom.org/shared_storage/uploads/userpics/52/2552/10642552/' to `rsync://olympia@*.*/filestore/addons-dev.allizom.org/shared_storage/uploads/userpics/52/2552/10642552/', and the error was: `rsync: change_dir "/mnt/efs/addons-dev.allizom.org/shared_storage/uploads/userpics/52/2552/10642552" failed: No such file or directory (2)
```

In this case, it should have output `/mnt/efs/addons-dev.allizom.org/shared_storage/uploads/userpics/52/2552/`, that way, we can have `rsync` remove the `10642552` sub-directory from the destination as well.

The second issue is that the command will output a newly created sub-directory, but again at a wrong level. For example, it would output `/mnt/efs/addons-dev.allizom.org/git-storage/55/5055/625055/addon/`, and when we tried to rsync it, the error is,

```
2023-03-13 12:01:29,966 amo_rsync WARNING    Failed to rsync from `/mnt/efs/addons-dev.allizom.org/git-storage/55/5055/625055/addon/' to `rsync://olympia@*.*/filestore/addons-dev.allizom.org/git-storage/55/5055/625055/addon/', and the error was: `rsync: [Receiver] mkdir "addons-dev.allizom.org/git-storage/55/5055/625055/addon" (in filestore) failed: No such file or directory (2)
```

In this case, it should have output `/mnt/efs/addons-dev.allizom.org/git-storage/55/5055/625055/`, that way, we can have `rsync` create the `625055` sub-directory and everything below it (on the destination).

Please let me know if that makes sense.

**Comment by eviljeff** [comment]
@bqbn we don't know _why_ a directory has potentially changed currently - it could be that something has been created, or it could have been modified, or it could have been deleted (or it might not exist at all and it's a false match)

We can change the command to always output the parent directory if that helps (and the parent-parent for git-storage) but a) it's not a complete fix - if `/52/2552/10642552/` doesn't exist, then `/52/2552/` might not exist either (or '/52/', but less likely); and b) we'll be syncing a lot more content if everything under `/52/2552/` is now to be synced.

Otherwise, we can make an attempt at working out if something has been deleted or added by checking on the filesystem if the content exists (if it does, we can assume it was potentially added/updated and keep outputting the directory as now; if it doesn't we can assume it was deleted or didn't exist and output the parent directory).  Downside of this approach (and why we don't do it already) is it's slower to access the filesystem rather than a few database queries.

**Comment by bqbn** [comment]
For the second issue above, i.e., when the command outputs a newly created sub-directory but at the wrong level, I think we can work around it by using the `--relative` option to the rsync command.

For the first issue, i.e., when the command outputs a non-existing sub-directory, the rsync wrapper script can check if a directory exists or not before the transfer, e.g., if a directory exists transfer it, if not, transfer its parent directory.

This works for most of the directories, because as you said, in reality it's less likely we need to trace back multiple parent directories. However, there is one exception, which is the `/mnt/efs/addons-dev.allizom.org/shared_storage/uploads/addon_icons/` directory. The `get_changed_files` command would output that `/mnt/efs/addons-dev.allizom.org/shared_storage/uploads/addon_icons/625/` is changed when the "change" is that the `625/` sub directory is removed. But the `addon_icons/` somehow doesn't follow the standard directory hierarchy of "at most 100 sub-folders at each level". This directory contains thousands of sub-folders. So in this case, is very time consuming to have rsync transfer `addon_icons/` and remove `625/`.

I see two options here, one, change the directory structure of `addons_icons` so it's not a flat directory but has the same directory structure as others. two, ignore the non-existing directories in `addon_icons/` directory.

What do you guys think?

**Comment by eviljeff** [comment]
It looks like we don't delete directories when files are deleted - so when directory doesn't exist then it's safe to just skip it as a false match.

**Comment by bqbn** [comment]
> It looks like we don't delete directories when files are deleted - so when directory doesn't exist then it's safe to just skip it as a false match.

Thanks. They are now skipped in https://github.com/mozilla-services/cloudops-deployment/pull/4798/commits/7d124af42f7219dad5cf8f4bc0147418d4948b77

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-244
