### ISSUE TITLE
Don't show the tooltip without making a search first

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20298]
From https://github.com/mozilla/addons-server/issues/20180#issuecomment-1419244898

1. Go to admin -> users, ratings or addons module and hover over the search bar 

Actual result:
A tooltip is displayed 

Expected result:
Nothing happens. 

Notes:
The tooltip should be displayed only after making a search.

**Comment by ioanarusiczki** [comment]
Ups, going to close this one https://github.com/mozilla/addons-server/issues/20180#issuecomment-1419248905

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-246
