### ISSUE TITLE
Unlisted versions are auto-approved  instead of being disabled for auto-approval

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20291]
Followup for https://github.com/mozilla/addons-server/issues/20277#issuecomment-1411832943

I submitted a listed version for an [addon](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/624746) and it's been delayed for approval indefinitely. Then I submitted unlisted versions too -> they're been automatically approved 

Expected result: 
The unlisted should be delayed for approval too 

Note:
I separately submitted (on dev and stage) only an unlisted versions of this addon, it's in the Manual Queue but the versions have been [auto-approved](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/624827).

**Comment by diox** [comment]
The auto-approval delay flag is now per-channel, following https://github.com/mozilla/addons-server/issues/20250. The scanner action now sets both, so this should only be an issue for existing add-ons that had not been disabled yet (as they only had the new flag, I didn't migrate them), or new add-ons where the flag is set manually by reviewers (they'll get the new flag in https://github.com/mozilla/addons-server/issues/20251 - at the moment it's only available in the add-on admin tool)

**Comment by wagnerand** [comment]
Mat and I verified this on stage:

https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1008167/change/
https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1008168/change/
https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addon/1008169/change/

**Comment by ioanarusiczki** [comment]
@diox I see for a recommended addon that unlisted versions are auto-approved -> may have been like this and it's expected ?

The scenario above is no longer reproducible. Also, for disabled unlisted auto-approval , unlisted versions don't get auto-approved.

**Comment by diox** [comment]
> @diox I see for a recommended addon that unlisted versions are auto-approved -> may have been like this and it's expected ?

Yes.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-245
