### ISSUE TITLE
Cannot save admin add-on changeset page of deleted add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20305]
### Describe the problem and steps to reproduce it:

When an add-on is deleted, I cannot save instance on the admin add-on changeset page. 

### What happened?

The `slug` field is empty but required.

### What did you expect to happen?

I should be able to save the instance on the page.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
Deleted addon can be now saved in the Admin addon detail pages. 

This issue is verified fixed on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-248
