### ISSUE TITLE
Expose fields on admin version changeset page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20304]
The admin version changeset page should expose the `due_date` field read-write.

**Comment by ioanarusiczki** [comment]
@wagnerand 

- In Flags section on versions change page there's a Due Date which can be added/modified for an addon. 

- I've noticed the addon is displayed in the Manual Queue once a date is set. 
- When the addon is already in the Manual Queue when due date is modified from admin it will change in rev tools too accordingly. 

- I could set the due date to 2023-02-01 ( in the past). 
- If there's already a due date set for the addon I could not delete it.

**Comment by wagnerand** [comment]
> If there's already a due date set for the addon (version) I could not delete it.

@diox hm, is this a limitation of the datetime widget?

**Comment by diox** [comment]
The `version` field on the model needs `blank=True` to make django forms (and therefore the admin) allow blank values.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-247
