### ISSUE TITLE
UX review current state of style refresh

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2030]
Let's have a look at the implementation of style refresh and file issues on aspects of the refresh we might have missed and general polish where necessary.

@tofumatt can you notify us when you think the implementation is ready for a review?

@pwalm is this something you can talk on maybe this week?

**Comment by tofumatt** [comment]
I am hoping to close out all “blocking-release” bugs tonight and tomorrow so we can sneak this into this week’s push.

I will let you know in this issue once all “blocking” bugs are closed and you can give a once-over to make sure nothing else is a blocker. :-)

**Comment by andymckay-limited-access** [comment]
@designakt its on -dev and can be viewed without a flag.

**Comment by pwalm** [comment]
@designakt Yeah, anytime.

**Comment by andymckay-limited-access** [comment]
@designakt and @pwalm - its now on stage. I think this is what they call "intent to ship" I think its looking good and unless QA finds a blocker we can ship it. Minor bugs can be cleaned up in the following week.

**Comment by designakt** [comment]
So that means we should do the review rather soon. 
From comparing the current implementation with the initial user style I can see some alignment and size issues:
![screen-shot-2016-03-29-at-17 12](https://cloud.githubusercontent.com/assets/8145891/14124205/59976086-f5d2-11e5-8539-85a611519e16.gif)
(Especially the blue space underneath the carousel image looks strange, as does the read headline for Featured Extensions, the size of the pick of the month add-on name, and the over states of the add to Firefox button and the carousel)

current implementation
![screen shot 2016-03-29 at 17 12 39](https://cloud.githubusercontent.com/assets/8145891/14124208/5ea3acd8-f5d2-11e5-8ae2-8270159e682c.png)

user style
![screen shot 2016-03-29 at 17 14 29](https://cloud.githubusercontent.com/assets/8145891/14124218/6bdb8a74-f5d2-11e5-9532-c764d1772ee7.png)

and I think we can get rid of the welcome banner that shows up on first visits to AMO as the carousel already serves as a sort of intro. (If we can not get rid of it, we need to re-style it.)
![screen shot 2016-03-29 at 17 12 05](https://cloud.githubusercontent.com/assets/8145891/14124260/92a48318-f5d2-11e5-9bf7-6e5bfe15fb6c.png)

@pwalm could you please file issues for the differences you think we should fix before shipping.

**Comment by tofumatt** [comment]
I might've mentioned this before, but just in case: if any bugs that impede
shipping are found, please use the "blocks-release" tag so I know to fix
them first. Thanks!
- tofumatt

**Comment by pwalm** [comment]
yep, will file issues.

**Comment by designakt** [comment]
@pwalm that could be because you are not part of the Mozilla organization on GitHub...
I think @andymckay might be able to add you.

**Comment by pwalm** [comment]
Danke! Filed em yesterday :+1:

**Comment by andymckay-limited-access** [comment]
This is happening, we've got bugs with the label and I don't think this bug is doing much. Thanks for all the bugs.
