### ISSUE TITLE
Layout issues when hovering over second row of featured themes in Themes Homepage

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2031]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1. Load themes homepage in AMO-dev https://addons-dev.allizom.org/en-US/firefox/themes/
2.  Hover over second row of featured themes in Themes Homepage

Expected results:
There are no layout issues.

Actual results:
There are some layout issues(bottom line of theme highlight is missing).

Screencast for this issue: http://screencast.com/t/wWYjapnp1

**Comment by tofumatt** [comment]
Padding for this was increased in #2147, screenshot here:

![apr-13-2016 20-47-38](https://cloud.githubusercontent.com/assets/90871/14507112/20a7e500-01b9-11e6-8477-5d1060099d52.gif)

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/yd2tRge3b
