### ISSUE TITLE
Submission acknowledgement email for unlisted Add-ons

### ISSUE THREAD

**Issue by h2oman** [mozilla/addons-server#20320]
Followup from #20250.

Upon submission of a new, unlisted add-on, we should help manage developer expectations by sending an email to acknowledge receipt and inform that there will be a delay in auto-approval of up to several days.

## Implementation Details
Previously, unlisted add-ons were auto-approved within ~5 minutes, so we should send an email within this time window to acknowledge submission and inform them of the potential delay in auto-approval and that their add-on is subject to review at any point thereafter.

### Email Copy for Unlisted Add-ons
```
<p>Thanks for submitting your {{ addon_name }} add-on to <a href="https://addons.mozilla.org">addons.mozilla.org</a> (AMO)!</p>

<p>Please note that your add-on can be subject to human review at any time. Some submissions might be held for up to a few days for human review before they get approved. While your add-on might be screened and automatically approved, reviewers may look into it and determine that it requires changes. If that occurs, you will receive a separate notification with details and next steps.</p>

<p>For more information about the review process and policies, please visit <a href="https://extensionworkshop.com/documentation/publish/add-on-policies/">https://extensionworkshop.com/documentation/publish/add-on-policies/</a>.</p>

<p>Add-ons help personalize the web experience for millions of users who have installed Firefox, and we want to help make your users happy!</p>

<p>To stay up-to-date with news from the add-ons community, or contact the add-ons team, please visit <a href="https://extensionworkshop.com/documentation/manage/resources-for-publishers/">https://extensionworkshop.com/documentation/manage/resources-for-publishers/</a>.</p>>

<p>Happy developing!</p>

<p>
-- <br/>
Mozilla Add-ons<br/>
<a href="https://addons.mozilla.org">https://addons.mozilla.org</a><br/>
</p>
```

### Email copy update for Listed Add-ons
Update to the copy for the Listed Add-on submission email here `src/olympia/devhub/templates/devhub/emails/submission.html`

```
<p>Thanks for submitting your {{ addon_name }} add-on to <a href="https://addons.mozilla.org">addons.mozilla.org</a> (AMO)! Upon approval, your add-on listing will appear on our website here: <a href="{{ detail_url }}">{{ detail_url }}</a></p>

<p>Please note that your add-on can be subject to human review at any time. Some submissions might be held for up to a few days for human review before they get approved. While your add-on might be screened and automatically approved, reviewers may look into it later and determine that it requires changes or should be removed from the website. If that occurs, you will receive a separate notification with details and next steps.</p>

<p>For more information about the review process and policies, please visit <a href="https://extensionworkshop.com/documentation/publish/add-on-policies/">https://extensionworkshop.com/documentation/publish/add-on-policies/</a>.</p>

<hr />
Attract Users, Stay Updated, &amp; Get in Touch
<hr />

<p>Add-ons help personalize the web experience for millions of users who have installed Firefox, and we want to help make your users happy!</p>

<p>To learn how to help users discover your extension, stay up-to-date with news from the add-ons community, or contact the add-ons team, please visit <a href="https://extensionworkshop.com/documentation/manage/resources-for-publishers/">https://extensionworkshop.com/documentation/manage/resources-for-publishers/</a>.</p>>

<p>Happy developing!</p>

<p>
-- <br/>
Mozilla Add-ons<br/>
<a href="https://addons.mozilla.org">https://addons.mozilla.org</a><br/>
</p>
```

**Comment by diox** [comment]
So that would trigger after the initial submission (regardless of channel, but once per add-on).

We discussed this but I don't remember the conclusion : We have _another_ email, the "held for review" email that is currently sent after a version hasn't been approved for 3 hours: Do we want to keep sending it ? If so, should we avoid sending it for the first version ? Should we keep the [existing content](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt) ?

**Comment by wagnerand** [comment]
> We discussed this but I don't remember the conclusion : We have _another_ email, the "held for review" email that is currently sent after a version hasn't been approved for 3 hours: Do we want to keep sending it ? If so, should we avoid sending it for the first version ? Should we keep the [existing content](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt?rgh-link-date=2023-02-09T13%3A13%3A31Z) ?

Let's drop the "held for review" email.

**Comment by h2oman** [comment]
> > We discussed this but I don't remember the conclusion : We have _another_ email, the "held for review" email that is currently sent after a version hasn't been approved for 3 hours: Do we want to keep sending it ? If so, should we avoid sending it for the first version ? Should we keep the [existing content](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt?rgh-link-date=2023-02-09T13%3A13%3A31Z) ?
> 
> Let's drop the "held for review" email.

Agreed

**Comment by diox** [comment]
Note: this email will trigger once per add-on - the contents will be determined by the first version channel.

**Comment by ioanarusiczki** [comment]
@diox 

I've noticed in fakemail on dev this email being sent when the addon is created for both channels and for all addon types. A new listed/unlisted version won't trigger another e-mail.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-250
