### ISSUE TITLE
 Deleted addons and versions appearing in the Manual review queue cannot be removed from the queue

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20326]
Follow up for #20256 

### Describe the problem and steps to reproduce it:
1. Select an entry for a deleted addon or deleted version from the Manual review queue:
- deleted addon: https://reviewers.addons.allizom.org/en-US/reviewers/review/1007496
- deleted version: https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1008189#review-actions
2. Try to review the add-on to remove it from the queue

### What happened?
There are no reviewer actions that allow for a deleted addon/version to be removed from the Manual review queue

### What did you expect to happen?
Reviewers should have an option that allows deleted addons/versions to be removed from the Manual review queue

### Anything else we should know?
At the moment I was able to clear such addons from the Manual queue by deleting the `due_date` field in versions admin

**Comment by eviljeff** [comment]
I'm not sure which actions would be appropriate here. Maybe we should just make the `needs_human_review` flag un-settableb instead?

**Comment by diox** [comment]
Maybe yeah? We already have a way to set it... One caveat though, from the review page we can currently set it on the last version, but we'd need to be able to clear it for an arbitrary version, or all of them at once... /cc @wagnerand

**Comment by wagnerand** [comment]
For deleted add-ons, possible actions are
* Block one or more versions
* Drop the `needs_human_review` flag/`due_date` field, or whatever is necessary to remove the add-on from the queue

**Comment by diox** [comment]
Is that for listed/unlisted channel, or both ? (Note that reviewer actions typically affect a single channel at the time, since the review page is per-channel)

**Comment by wagnerand** [comment]
> Is that for listed/unlisted channel, or both ? (Note that reviewer actions typically affect a single channel at the time, since the review page is per-channel)

Unless I am missing a specific use case here, it should be for both. There is no reverting deleted add-ons and the files are disabled.

**Comment by diox** [comment]
That makes sense, I just wanted to be explicit.

**Comment by AlexandraMoga** [comment]
@eviljeff I've verified this issue on AMO -dev and I have the following results:

- addons from both listed and unlisted channels, are no longer present in the Manual review queue once they are deleted; I understand having them in the queue was a requested feature that was implemented in #20256. This is an [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625026) of a deleted add-on which is flagged for human review but it is not in the queue. 
- for purely listed addons: addons with deleted version are still present in the Manual review queue, but the addons can be now removed from the queue by Admin reviewers by using the Clear Needs Human Review action
- for purely unlisted addons: addons with deleted version are still present in the Manual review queue, but the addons can be now removed from the queue by Admin reviewers by using the Clear Needs Human Review action
- for addons with mixed listed and unlisted versions, the Clear Needs Human Review action will remove the manual review flag for the channel respective to the review page (listed/unlisted). For example, if I'm clearing the flag in the unlisted channel but the add-on still has listed versions marked for human review, the addon will remain in the Manual queue until those versions are processed as well.

**Comment by eviljeff** [comment]
> @eviljeff I've verified this issue on AMO -dev and I have the following results:
> 
>     * addons from both listed and unlisted channels, are no longer present in the Manual review queue once they are deleted; I understand having them in the queue was a requested feature that was implemented in [Deleted add-ons and versions should show up in the Manual Review queue #20256](https://github.com/mozilla/addons-server/issues/20256). This is an [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625026) of a deleted add-on which is flagged for human review but it is not in the queue.

Deleted add-ons and versions that are flagged for needs_human_review should still be present in the manual review queue if the file was signed already; if the xpi hadn't been signed it doesn't get a `due_date` so isn't in the queue.  (If something isn't working here please file a issue)

**Comment by AlexandraMoga** [comment]
> Deleted add-ons and versions that are flagged for needs_human_review should still be present in the manual review queue if the file was signed already;

I wasn't aware of this condition. I've reverified and if the addon was approved before being deleted then it is still available in the queue ([example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/624880)). This also applies to versions: if a version is deleted before being approved, then the addon it is no longer present in the queue, provided that there are no previous approved version for this addon.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-251
