### ISSUE TITLE
Cannot change the anonymous display name for a new account

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2032]
Prerequisites:Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/ 
2.Sign up with a new account
3.Try to setup the display name when asked , after finishing sign up flow

Expected results:
Display name is correctly changed

Actual results:
Display name is not changed

Please see screencast for this bug : http://screencast.com/t/ofqjsrbym

NOTES: Not reproducible on Stage

**Comment by vcarciu** [comment]
This happened even if I tried to change a display name for an already created account. The old display name was used after changing it in Account settings

**Comment by tofumatt** [comment]
Odd, I was able to update my account on dev just now, it's an existing one.

**Comment by tofumatt** [comment]
Also not sure if this would be related to the style change; those templates haven't been modified to my knowledge.

**Comment by krupa** [comment]
i cannot reproduce this issue anymore.
