### ISSUE TITLE
Don't translate new reviewer tools buttons

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#20338]
### Describe the problem and steps to reproduce it:
This string appears [here](https://github.com/mozilla/addons-server/blob/5dfeb24c890c826476ebfd31dd4e02911807f1ef/locale/en_US/LC_MESSAGES/django.po#L5049): `Set Needs Human Review`.  

### What happened?

`Set Needs Human Review` sounds strange in another language. We we want to do is to have a real person to review it, which means **manual**, not **automatic**.  

### What did you expect to happen?
Change the wording to make it sound less robotic. 
- Current: `Set Needs Human Review`
- Suggestion: `Set Needs Manual Review`

**Comment by peiying2** [comment]
@diox tag you here and feel free to reassign to the appropriate owner of this. Thank you!

**Comment by diox** [comment]
It should really set `Set "Needs Human Review" flag`. But more importantly, this string shouldn't be translated, as we decided to stop translating reviewer & admin tools. Thanks for reporting this, we'll keep the string but prevent it from showing up in our `po` files.

**Comment by peiying2** [comment]
Thank you for your prompt reply. Yes, lets take the opportunity to check for other components that shouldn't be included for translation.

**Comment by diox** [comment]
I did a review last time but this is a new string for a new functionality that slipped through. I'll fix it this week.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-255
