### ISSUE TITLE
Unable to merge addons account with firefox accounts

### ISSUE THREAD

**Issue by ofaurax** [mozilla/addons-server#2033]
I have my addon account with "myusername" and "me+mozilla@server.com" as e-mail address.
I have a firefox account on e-mail "me@server.com".

I'm unable to migrate my addon account.
If I try to put "myusername" in my current addon account, it fails with "username already exists".
If I try to put my address "me@server.com" instead of the previous one, it fails with "e-mail already exists".

Can you explain me how I can merge the 2 accounts?
Thanks

**Comment by mstriemer** [comment]
Have you successfully logged in using Firefox Accounts on AMO? This is how the flow should work to migrate if you haven't logged in with Firefox Accounts before:

1. Log in to your AMO account with `me+mozilla@server.com` and your password.
2. You are prompted to migrate, click continue.
3. You are redirected to Firefox Accounts, login with your FxA account `me@server.com`.
4. You are redirected back and you've migrated, in the future login with `me@server.com`.

If you have two accounts on AMO already and want those merged it's a little more work and we might need to manually update the database. If you have both accounts on AMO can you put the usernames in here or email them to me mstriemer@mozilla.com?

**Comment by ofaurax** [comment]
I think I have 2 accounts on AMO: ebc229 and ofaurax.
Can you please merge the 2 of them? If you need to choose, keep the data from "ofaurax".
Thanks for your support!

**Comment by eviljeff** [comment]
I can only find https://addons.mozilla.org/user/ofaurax/ - is 'ebc229' the correct username? If you're okay with losing one (ebc229 I guess) it should just be matter of switching some fields.

**Comment by ofaurax** [comment]
I see "Anonymous user ebc229" on the top of the page.
Yes, "ofaurax" is the correct username, please make it the correct one for the account linked with addon https://addons.mozilla.org/fr/firefox/addon/esperanto-toolbar/
Thanks a lot!

**Comment by eviljeff** [comment]
Alright, I've deleted the anonymous one and changed the email address for ofaurax to be one you use for Firefox Accounts (the one ebc229 had).  If you try to log in with that email address it will migrate the account and you should be set.

**Comment by ofaurax** [comment]
Thanks!
