### ISSUE TITLE
Stop translating send_api_key_revocation_email email

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20333]
The email we send when we detect an api key in a submission is translated, but we never activate a specific language when we send it, so that does more harm than good - it'll usually be sent in English, but there is no guarantee of that. Since most developer communication should happen in English anyway, we should probably stop attempting to translate it completely.

**Comment by diox** [comment]
Actually, let's keep that for now, because devhub _is_ translated and it's part of devhub.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-253
