### ISSUE TITLE
Older listed versions shouldn't be unrejectable, only the latest version

### ISSUE THREAD

**Issue by wesinator** [mozilla/addons-server#20347]
### Describe the problem and steps to reproduce it:
In review queue, we had a case where a previous version (several versions back) was unrejected, which switched it to pending review.

We were unable to approve this prior version, there was no option in the menu to approve previous versions. This meant the addon still showed up in the manual review queue.

### What did you expect to happen?

would having an option approve multiple versions make sense?
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/5124946/218873705-f60a6c16-2628-4a43-a434-871375255aad.png">

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Could you clarify which version had what status, which versions has due dates, and what channel are we talking about ?

**Comment by wesinator** [comment]
in this case, 3.2.0 was in state awaiting review after being unrejected, and the following subsequent versions had statuses: 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/5124946/219207150-9703d435-0290-48d7-aa8f-0cf67eddc7b9.png">

**Comment by diox** [comment]
Sorry this is still not enough information for us to act on. I need:
- The channel
- The reviewer flags the add-on had
- The status displayed for the versions in the history (unreviewed, approved etc)
- Which version had a due date exactly if you can figure that out (it's not necessarily only one, or the one that was un-rejected)

A link to the review page (shared privately if needed) would also help - we can gather much of the info I ask for above from that.

**Comment by diox** [comment]
This was for listed, so I think this is an edge case specific to the un-reject action. Not sure what's the best approach here, ultimately it shouldn't matter much what happens to that version unless it somehow becomes the last non-rejected one...

**Comment by eviljeff** [comment]
I think we need to understand the scenario that led to this state happening first.  Was it a mistake to unreject the older versions?  (If so, should we add further guard rails so older listed versions aren't unrejectable?)  For listed versions it generally only makes sense to have a single version awaiting review, and for it to be newer than the approved versions, because users will get the newest version anyway.

**Comment by wesinator** [comment]
Yes, it was unintentionally unrejected. 

However, there _may_ be valid cases where we would want to unreject an older version, so I'm not sure if blocking that would make sense.

**Comment by wagnerand** [comment]
For listed, it sounds reasonable to allow unrejecting the last non-public version only. @wesinator could you think of use cases where we'd want to unreject (and approve) versions older than that?

**Comment by wesinator** [comment]
No; un-rejecting the last version seems reasonable.

**Comment by eviljeff** [comment]
Okay, so repurposing this issue to be about stopping this scenario from happening in the first place, by changing how unreject works.  @wagnerand is it possible to fix this particular add-on via the admin?

**Comment by ioanarusiczki** [comment]
@eviljeff For [multiple listed version](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/625066#review-actions) which have been all rejected I could un-reject only the last version. Then the Un-reject button is no longer available. 

Another example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625059

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-257
