### ISSUE TITLE
Remove code related to old canned responses feature

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#20353]
This is a follow up to https://github.com/mozilla/addons-server/issues/19818, and is about removing code related to the canned responses feature which is no longer needed.

**Comment by bobsilverberg** [comment]
@diox @eviljeff There is some code in `addons-code-manager` that references canned responses. The intent was that a user could create a comment in code manager and provide a `cannedResponseId` as opposed to comment text, but that feature was never implemented. So although code manager is calling the comments API with a `canned_response` parameter, it is always passed as `undefined`. As well, code manager expects that the response from the comments API will include a `canned_response`, but it never does anything with it.

I think it is possible that we can remove all code in `addons-server` relating to canned responses, including from the comments API, and code manager will simply continue to work without complaint. Ideally we would also remove those references from code manager, but considering that we are considering deprecating code manager, I'm not sure if we want to spend any time doing that.

It wouldn't be a lot of work, so it's probably worth doing, as it's the "right thing" to do, but I was wondering what your thoughts are on this.

**Comment by eviljeff** [comment]
Can we list out all of the remaining work to remove the old canned responses feature? (with links to any issues already filed)

**Comment by bobsilverberg** [comment]
> Can we list out all of the remaining work to remove the old canned responses feature? (with links to any issues already filed)

The only issues I already filed have already been completed. Here is what I think is left to be done:

- [ ] Remove the [`CannedResponse` model](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/models.py#L98)
- [ ] Update the `DraftComment` model to remove the [FK to `CannedResponse`](https://github.com/mozilla/addons-server/blob/master/src/olympia/activity/models.py#L263)
- [ ] Remove the [`CannedResponseAdmin`](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/admin.py#L9)
- [ ] Update the reviewers serializers to remove [`CannedResponseSerializer`](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/serializers.py#L544) and remove [`canned_response` from `DraftCommentSerializer`](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/serializers.py#L565)
- [ ] Update `ReviewAddonVersionDraftCommentViewSet` to remove [`select_related` for `canned_response`](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/views.py#L1406)
- [ ] Remove [constants related to canned responses](https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/reviewers.py#L14-L36)
- [ ] Update API docs to address the above changes
- [ ] Remove all tests associated with the above

While this looks like a lot of stuff, it's actually not that much code, and much of the work is just deleting stuff, so I imagine it could all be done in a single patch.

I will open a similar issue in `addons-code-manager` to list out the changes required there, which I also believe are fairly limited in terms of size.

**Comment by bobsilverberg** [comment]
I filed https://github.com/mozilla/addons-code-manager/issues/2206 for code manager.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I don't see anything changed since checking on https://github.com/mozilla/addons-code-manager/issues/2206 or https://github.com/mozilla/addons-server/issues/20354

Is there anything else I should be looking for ?

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> I don't see anything changed since checking on [mozilla/addons-code-manager#2206](https://github.com/mozilla/addons-code-manager/issues/2206) or #20354
> 
> Is there anything else I should be looking for ?

No nothing specific.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-259
