### ISSUE TITLE
Remove the canned-responses endpoint

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#20354]
This contributes to #20353.

The canned-responses endpoint, which just returns a list of existing canned responses, was never used. As we are planning on getting rid of all references to canned responses, this needs to go too.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

- Making a request such as https://addons-dev.allizom.org/api/v5/reviewers/canned-responses/ is a 404 
- Making a POST to https://addons-dev.allizom.org/api/v4/reviewers/addon/1865/versions/1688388/draft_comments/ with a "canned_response" is not possible -> "You can't submit a comment if `canned_response` is defined."
- I checked the [reviewers endpoints ](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#) for AMO dev and they seem to be working as expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-260
