### ISSUE TITLE
Remove the code from the review form that makes use of canned responses

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#20356]
This contributes to https://github.com/mozilla/addons-server/issues/20353.

We can remove the code that displays the canned responses drop-down, as well as the related JavaScript code, without having to change the model or serializers yet. The latter can be done in a different patch.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

- On the review pages -> at approval, reject for addons or static themes the canned response section is no longer displayed. 
- approve/reject actions continue to work as expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-261
