### ISSUE TITLE
Include unlisted versions in "Notable" promoted group assessment

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20351]
It seems the criteria for adding an extension to the _Notable_ group [include public add-ons only](https://github.com/mozilla/addons-server/blob/990e1af37ad8c5ed15c9426912faca3367329741/src/olympia/promoted/tasks.py#L30), which excludes purely unlisted add-ons. However, those should be included when determining the extensions that need to be added to _Notable_.

**Comment by diox** [comment]
Which version(s) should get the `needs_human_review` flag when they are added to `Notable` ? Currently it's the `current_version` - the latest approved listed (and only that one).

**Comment by wagnerand** [comment]
@kplotnik do you have an opinion here?

I could see two scenarios, we either flag all versions, or the latest as well. Unless we have an easy way to determine which exact version has the most users.

**Comment by diox** [comment]
I assume https://github.com/mozilla/addons-server/issues/20337 will be a problem here as well btw.

**Comment by wagnerand** [comment]
We want to determine the amount of add-ons that would be added, and space their due date out, as we did with listed recently.

Could anyone double-check my query to count the number of add-ons?
```
select
    count(DISTINCT v.addon_id)
from
    versions v
    join addons a on v.addon_id = a.id
where
    a.addontype_id = 1
    and v.channel = 1
    and v.id not in (
        select
            id
        from
            versions
        where
            channel = 2
    )
    and a.average_daily_users >= X;
```

**Comment by diox** [comment]
To control the assignment of due dates, we could force the `add_high_adu_extensions_to_notable` task to pass a custom argument to the `save()` method with the due date, and set it on the `Version` we are setting `needs_human_review` on... FWIW, here is what I did last time we had some backlog to catch up:
https://github.com/mozilla/addons/blob/main/releases/2023/02/09.md#after-were-done

Target per day would have to be agreed with @wagnerand and @kplotnik, not sure if the actual value needs to stay private or not.

**Comment by wagnerand** [comment]
This is now unblocked, we can go ahead.

**Comment by diox** [comment]
@wagnerand for this to work in prod, we'll need `notable-review-target-per-day` config to be set to an integer representing the number of add-ons to add to the queue per day for notable. If there are more, they'll be spread out with a due date in the future.

**Comment by eviljeff** [comment]
> @wagnerand for this to work in prod, we'll need `notable-review-target-per-day` config to be set to an integer representing the number of add-ons to add to the queue per day for notable. If there are more, they'll be spread out with a due date in the future.

(I'm guessing this has already happened) but we need to add a value for these configs - however high and arbitrary - or the cron job will fail.

**Comment by AlexandraMoga** [comment]
I've set up some test data to verify this issue on -dev and stage but I forgot to set the `notable-review-target-per-day` config in these environments, hence I don't have test results to report yet. 

If everything was set-up correctly, I'm expecting to see the following unlisted addons appear in the Notable promoted group on -dev and stage tomorrow:
- dev - https://addons-dev.allizom.org/en-US/developers/addon/statistics-reloaded/edit
- stage - https://addons.allizom.org/en-US/developers/addon/script-script-alert-1/edit

**Comment by AlexandraMoga** [comment]
I've checked today again to see if the addons I've prepared were added to the Notable group but I can't find them there.

Maybe my test method is flawed, so here is what I did:
- First of all, we did not have pure unlisted addons with ADU on -dev and stage, so I've taken one of the addons with ADU we had and deleted all its listed versions.
- I've removed the addon from the Notable promoted group
- I've uploaded a new unlisted version for the addon targeted
- set configs: `notable-adu-threshold = 1`, `notable-review-target-per-day = 10`
- wait for the cronjub to run

Again, these are the addons I used for testing :
- dev - https://addons-dev.allizom.org/en-US/developers/addon/statistics-reloaded/edit
- stage - https://addons.allizom.org/en-US/developers/addon/script-script-alert-1/edit

@wagnerand did you manage to verify if this is working as expected in prod?

**Comment by diox** [comment]
I don't know what value `notable-review-target-per-day` was set as yesterday, but it wasn't valid back then on dev. Today it's correct but the cron hasn't ran yet (it will start in a couple minutes from now, and then we need to wait for it to be finished).

**Comment by AlexandraMoga** [comment]
> On stage, its latest unlisted version had already been reviewed by a human so it wasn't marked as needing human review.

I can see the stage addon in the manual queue and it seems to have received a due date - https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1003699

**Comment by diox** [comment]
Ah yes sorry I was looking at its _listed_ versions before.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-258
