### ISSUE TITLE
Update links for the MIT and BSD licenses

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20360]
### Describe the problem and steps to reproduce it:

1. Open the detail page for an add-on with an [MIT](https://addons.allizom.org/en-US/firefox/addon/mit-license/) or [BSD](https://addons.allizom.org/en-US/firefox/addon/bsd-license/) license
2. Click on the license link in the More info section

### What happened?
The license page is not found

### What did you expect to happen?
The correct license page is opened

**Comment by eviljeff** [comment]
we should check the other urls are still valid while we're at it

**Comment by AlexandraMoga** [comment]
Yes, the other built-in license urls (both for extensions and themes) were checked and only these two seem to no longer be active at the moment.

**Comment by AlexandraMoga** [comment]
The MIT license link now points to https://opensource.org/license/mit/ and the BSD license to https://opensource.org/license/bsd-2-clause/, both pages loading the expected license. 

This issue is verified fixed on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-262
