### ISSUE TITLE
Potential race condition with reviewer flags API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20362]
A typical problem with django instances is the following pattern:
```
obj = Model.objects.get(...)
obj.foo = 'bar'
obj.save()
```

This triggers an `UPDATE` for *all* fields on model, even those not modified. Which means there can be a race condition between 2 things modifying different properties of the same object: one could override the changes made by the other. This is notably present in the django admin.

We have our own `.update()` method to work around that, and in some cases we call `update_or_create()` which also avoids that problem. Django also has `select_for_update()` to lock, and you can pass `update_fields` to `save` calls.

I noticed that we don't do anything special for the `AddonReviewerViewSet`'s `flags` API, which means it uses a regular `.save()` call and could suffer from this issue. Accidentally overriding reviewer flags is pretty bad, so we should add a workaround there.

See also https://github.com/encode/django-rest-framework/issues/2648 (which mentions http://chibisov.github.io/drf-extensions/docs/#partialupdateserializermixin as a possible fix), https://github.com/encode/django-rest-framework/issues/4675, https://code.djangoproject.com/ticket/27477

**Comment by diox** [comment]
This is hard to test for QA. The core thing we want to ensure didn't regress is changing any of the reviewer flags through the API - that's done by clicking the button for users with `Reviews:Admin` in the review page under various scenarios and check that the corresponding flag (auto approval disabled/delayed for different channels) is updated accordingly.

On top of this you could try clicking 2 buttons to clear multiple flags very quickly/firing the API requests almost simultaneously, and checking it did properly change both flags once you reload.

**Comment by ioanarusiczki** [comment]
@diox 
I've verified on AMO Stage -> sent flag requests using the reviewer flag API too. I even clicked around on multiple buttons. The states of the buttons were correctly displayed. 

I've a question about a scenario: I have an [addon](https://reviewers.addons.allizom.org/en-US/reviewers/review/1008466) in the manual review queue flagged for human review and delayed temporarily. I delayed rejection and the addon showed up in the Pending rejection queue where I've noticed that the delayed temporarily flag is displayed but without the flag for human review. I cleared the pending rejection and checked the manual queue again. This time there's only the delayed temporarily flag present. 

Should it keep it's flagged for human review flag too ?

**Comment by diox** [comment]
Rejecting (with a delay or not) clears the needs human review flag - the assumption is the reviewer has performed their review, so the relevant version(s) no longer need a human review. For listed, it clears the flags for all past listed versions, for unlisted, it clears it on the versions that have been rejected/approved specifically.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-263
