### ISSUE TITLE
Expose `version` field with the version used at submission in the add-on API for `POST`/`PUT` requests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20365]
The new add-on submission API doesn't expose the `version` you used at submission in its response. 

You can sort of guess it yourself by looking at either `current_version` (for listed) or `latest_unlisted_version` (for unlisted) but it's ideal, and there could be edge cases where it's not the version that was submitted (less likely for `POST`).

Let's expose during `POST` and `PUT` the version that was submitted in a `version` field.

**Comment by ioanarusiczki** [comment]
@diox I verified this on - dev 

Results:

->  in the response for POST with https://addons-dev.allizom.org/api/v5/addons/addon/ version object is present 
-> in a response with PUT https://addons-dev.allizom.org/api/v5/addons/addon/addonid/ version object is present 
-> POST for a new addon version such as https://addons-dev.allizom.org/api/v5/addons/addon/624970/versions/ does not return version as object -> I think it's expected 
->  GET with the detail addon https://addons-dev.allizom.org/api/v5/addons/addon/624972/ won't return version as object. -> again expected

The new layout:
![version object](https://user-images.githubusercontent.com/33448286/220318019-f58fa3fa-24e9-4b70-bc1f-20163eb68c21.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-264
