### ISSUE TITLE
Allow looking up versions by version number in the add-on versions API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20388]
The add-on versions API lets you look up versions by their `pk`, we should allow looking up by the version number (with an add-on identifier still present) too. That will make handling of conflicts (https://github.com/mozilla/addons-server/issues/20387) easier, as the clients will be able to load the existing version without going through the versions list.

**Comment by diox** [comment]
This should work for all version endpoints, you can use the version number instead of the `id`. For cases where it would be ambiguous because the version number doesn't contain a dot, you have to add the optional `v` prefix which forces the lookup to be by version number instead of by `id`.

**Comment by ioanarusiczki** [comment]
@diox 

I sent requests with:

addon versions 
GET https://addons-dev.allizom.org/api/v5/addons/addon/616961/versions/10.239/
PATCH operation https://addons-dev.allizom.org/api/v5/addons/addon/622242/versions/v31.0.7/
DELETE operation  https://addons-dev.allizom.org/api/v5/addons/addon/622242/versions/v31.0.7/

I tried with reviewers endpoints too replacing the addon id with the version number but I get 404s. I assume the changes are only for the above endpoint.

**Comment by ioanarusiczki** [comment]
@diox As discussed -> reviewers are not included in these changes 
I'll mark this verified

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-270
