### ISSUE TITLE
Fix CSP to deal with multi-region GA host

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#20380]
This is a follow-up to https://github.com/mozilla/addons-server/issues/20222#issuecomment-1433193991.

As we did for [addons-frontend](https://github.com/mozilla/addons-frontend/blob/master/config/lib/shared.js#L15-L16), we need to allow for different regions in the CSP connect-src for the Google Analytics host.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I checked on AMO Stage:

- the errors from https://github.com/mozilla/addons-server/issues/20222#issuecomment-1433193991 are no longer present

- I see a 200 with Initiator analytics.js and 2 times a 204 with Initiator .js when I navigate on dev hub.  Is that expected ? 
- Re-checking on frontend , I've noticed that in general there's once a 200 and once a 204.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-268
