### ISSUE TITLE
Errors submitting webextension to AMO

### ISSUE THREAD

**Issue by michael-oneill** [mozilla/addons-server#2038]
This Webextensions extension installs fine in Firefox 48 with signature checking turned off, but I get errors when I submit it to AMO. This install.zip contains install.xpi (silly I know)

[install.zip](https://github.com/mozilla/addons-server/files/194284/install.zip)

The errors I get are     Could not parse the manifest file.
    Could not parse `manifest.json`.
    Add-on missing manifest.
Error: The JSON parser was unable to parse the manifest.json file included with this add-on.

**Comment by jvillalobos** [comment]
Ping @tofumatt, since I think this is an issue with the new linter.

**Comment by andymckay** [comment]
New linter isn't live (we'll let you know when it is). The problem looks like a byte order marker at the beginning of the manifest.json.

```
>>> data = open('manifest.json', 'r').read()
>>> data[:5]
'\xef\xbb\xbf{\r'
>>> json.loads(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>> json.loads(data[3:])
{u'content_scripts': [{u'all_frames': True, u'matches': [u'<all_urls>'], u'run_at': u'document_end', u'js': [u'publicsuffix.min.js', u'jquery-1.10.2.min.js', u'common.min.js', u'content.min.js']}], u'name': u'__MSG_extName__', u'sho...
```
As a quick fix, @michael-oneill can remove the BOM. We should then check the new amo-linter can cope with such a BOM.

**Comment by EnTeQuAk** [comment]
@andymckay should we try to fix `amo-validator` too?

**Comment by EnTeQuAk** [comment]
Whoops, not closed yet - need to pull in a new amo-validator version first.
