### ISSUE TITLE
Fix giant red header

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-server#2039]
Make smaller and not red! Like this (from Markus' user style):
![screen shot 2016-03-29 at 4 05 49 pm](https://cloud.githubusercontent.com/assets/6797635/14126753/2a98a2cc-f5c8-11e5-8d5e-ee831c2128ce.png)

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/yVO9ofW0L

**Comment by muffinresearch** [comment]
> Verified as fixed : http://screencast.com/t/yVO9ofW0L

That doesn't look fixed yet + it's not on -dev yet.

**Comment by vcarciu** [comment]
Verified as fixed : 
![redhead](https://cloud.githubusercontent.com/assets/1583842/14206532/5838b702-f81c-11e5-9c71-20ebdd17bec6.png)
