### ISSUE TITLE
Show auto-approval date for unlisted add-ons that have auto-approval temporarily delayed and are in awaiting review state

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20392]
### Story
As an add-on reviewer, I want to be able to see when an add-on that's in the following state:
- is newly submitted
- is unlisted
- is awaiting review
- has delayed auto-approval flag
- is in the manual review queue

will be auto-approved so that I can prioritize my screening of unlisted add-ons accordingly. The due date column could work for it but this information could be anywhere in the queue. Sorting of the queue according to this auto-approval date isn't necessary, but could be useful.

### Anything else we should know?
Please reach out if you need more details on this

/cc'ing @wagnerand for any more inputs on this.

**Comment by eviljeff** [comment]
The `due_date` is supposed to be the way of prioritizing reviews, but the story appears to highlight cases where the `due_date` is ignored and some additional criteria is used for prioritization.  Can the `due_date` be changed instead?

**Comment by wagnerand** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/20421

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-271
