### ISSUE TITLE
Fix spacing at bottom of carousel

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-server#2040]
Extend the carousel image to the bottom of the carousel and decrease the padding between the carousel and the top of the "Featured Extensions" header.
From this:
![screen shot 2016-03-29 at 4 07 31 pm](https://cloud.githubusercontent.com/assets/6797635/14126891/e2c2481c-f5c8-11e5-9ec8-bf7655755ea2.png)

To this:
![screen shot 2016-03-29 at 4 11 38 pm](https://cloud.githubusercontent.com/assets/6797635/14126896/f07afd78-f5c8-11e5-80c0-629a045de111.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-01_1023](https://cloud.githubusercontent.com/assets/15685960/14200480/dffdc20a-f7f3-11e5-9a00-8eedf92a505d.png)
