### ISSUE TITLE
Store host permissions in the `webext_permissions` table

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#20417]
MV3 has a new manifest.json key named `host_permissions` with a list of, well, host permissions. More information at: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions. Basically, in MV2, permissions could contain both actual permission names and hosts. In MV3+, hosts are moved to `host_permissions`.

We are already parsing and storing `permissions` and `optional_permissions`. It'd be interesting to also store the host permissions. It might be handy for data exploration.

Product might even be interested in surfacing those hosts in the frontend. That would require more work in this project, though (e.g. exposing the new data in the API).

**Comment by bobsilverberg** [comment]
@willdurand I have some questions:

1. In MV3 do all host permissions need to be in `host_permissions`, or can an add-on have some host permissions remain in `permissions` and some also in `host_permissions.
2. In terms of displaying this information to the user, how will Firefox show these new values that are in `host_permissions`, and will they be surfaced as different from any host permissions that are stored in `permissions`.
3. Currently AMO displays permissions like this:
![Screen Shot 2023-03-01 at 12 52 04 PM](https://user-images.githubusercontent.com/142755/222222273-7bbbf300-6688-4ef8-8002-90e8965d5ead.png)
Would it be sufficient to just add whatever is found in `host_permissions` to this list, or do they need to be called out in some other way?

**Comment by bobsilverberg** [comment]
Implementation note: I believe we can implement only this change, storing this data in the `webext_permissions` table, without *needing* to do anything else (e.g., update the API, update the frontend). We should open follow-ups to do all of those things, but I think this change could land without having to do any of those other things.

**Comment by willdurand** [comment]
> Implementation note: I believe we can implement only this change, storing this data in the `webext_permissions` table, without _needing_ to do anything else (e.g., update the API, update the frontend). We should open follow-ups to do all of those things, but I think this change could land without having to do any of those other things.

Yeah, I am not suggesting that we do more than storing the host permissions in the DB.

**Comment by eviljeff** [comment]
Is it important to separate `host_permissions` and `permissions`?  If not, we could just store them in the existing `permissions` field.  If so, what about MV2 files that have both urls and permission names in the same list - I guess if it's needed we should separate those values too?

**Comment by bobsilverberg** [comment]
> Is it important to separate `host_permissions` and `permissions`? If not, we could just store them in the existing `permissions` field. If so, what about MV2 files that have both urls and permission names in the same list - I guess if it's needed we should separate those values too?

@willdurand Can you provide your opinion here? I have a PR ready to go, but we need to determine whether these new `host_permissions` should live in their own spot, or can simply be combined with the other `permissions`. I guess the former is more flexible in the long run, if we do need to differentiate between them, but if we don't think we're going to have to do that, simply adding them to `permissions` might make more sense. Also, further to Andrew's question, if we do want to store `host_permissions` separately, should we also start extracting them from `permissions` as well?

**Comment by willdurand** [comment]
>  In MV3 do all host permissions need to be in `host_permissions`, or can an add-on have some host permissions remain in `permissions` and some also in `host_permissions.

All host permssions need to be in `host_permissions`.

> In terms of displaying this information to the user, how will Firefox show these new values that are in `host_permissions`, and will they be surfaced as different from any host permissions that are stored in `permissions`.

In `about:addons`, that will be something like this eventually (maybe not _exactly_ like this but close):

<img width="681" alt="Screenshot 2023-03-02 at 11 00 51" src="https://user-images.githubusercontent.com/217628/222471253-56dfeeed-bd21-48f4-8581-0d7095d1eb1d.png">

> Currently AMO displays permissions like this:
> [screenshot]
> Would it be sufficient to just add whatever is found in `host_permissions` to this list, or do they need to be called out in some other way?

That is a Product/UX decision. I asked the same question a while ago and I think the answer was more or less "let's do nothing for now". I suppose we could ask again and see if anything has changed.

At this point it is unclear to me, in part because MV3 permissions become optional so it isn't exactly like hosts in `permissions` in MV2. That being said, I am not sure we do anything special for regular MV3 permissions on AMO at the moment, so maybe that'd be fine to do what you suggest above? Ah well, let's ask Product/UX :)

**Comment by diox** [comment]
FWIW I think I'd rather store them in a separate `host_permissions` field, then figure out in the API/frontend what to do. That's the most flexible approach, allows us to do whatever we like later with the data.

**Comment by willdurand** [comment]
In case that wasn't clear, I agree with that and that's what I was kinda suggesting.

As for the rest (api/frontend), let's move the discussion elsewhere.

**Comment by eviljeff** [comment]
If there's already a pr up then probably in a follow-up, but the handling for MV2 feels a little inconsistent right now.  If MV3 considers urls separately to built-in permissions then we should display them separately on frontend. And to be consistent between MV2 and MV3 at a time where most add-ons are still MV2, we should split the MV2 `permissions` on the server-side into `host_permissions` so frontend can just consume the API output as is.

**Comment by bobsilverberg** [comment]
> If there's already a pr up then probably in a follow-up, but the handling for MV2 feels a little inconsistent right now. If MV3 considers urls separately to built-in permissions then we should display them separately on frontend. And to be consistent between MV2 and MV3 at a time where most add-ons are still MV2, we should split the MV2 `permissions` on the server-side into `host_permissions` so frontend can just consume the API output as is.

I think this is a product question, but personally I don't agree. We are already reporting regular and host permissions in the same card on the front-end, although we do process them so host permissions will show up last. I don't see any reason why, based on that decision, we shouldn't keep showing host permissions in the same card. From the user's perspective they are all permissions. Of course if something is drastically different about host permissions in MV3 and therefore we *need* to display them differently, then we should do so, and at that point we might want to split out host permissions for MV2 add-ons as well, but at this point I don't see them as different.

**Comment by eviljeff** [comment]
> > If there's already a pr up then probably in a follow-up, but the handling for MV2 feels a little inconsistent right now. If MV3 considers urls separately to built-in permissions then we should display them separately on frontend. And to be consistent between MV2 and MV3 at a time where most add-ons are still MV2, we should split the MV2 `permissions` on the server-side into `host_permissions` so frontend can just consume the API output as is.
> 
> I think this is a product question, but personally I don't agree. We are already reporting regular and host permissions in the same card on the front-end, although we do process them so host permissions will show up last. I don't see any reason why, based on that decision, we shouldn't keep showing host permissions in the same card. From the user's perspective they are all permissions. Of course if something is drastically different about host permissions in MV3 and therefore we _need_ to display them differently, then we should do so, and at that point we might want to split out host permissions for MV2 add-ons as well, but at this point I don't see them as different.

So we're already displaying permission names and urls separately on frontend, just doing the processing per-request in frontend and showing them in the same card after one another. If Product want to keep the card the same - or we don't want to change the UI in the absence of a specific Product request - then that's fine, but for mv3 add-ons we'd be combining them into a single list in the api and then reversing that to split them out again on frontend. Seems like an adequate hack to make everything work at first, but redundant, really.

**Comment by eviljeff** [comment]
> In fact, it might make sense to leave MV2 "host" permissions in `permissions` since those are mandatory while `host_permissions` in MV3 are optional (not _all_ permissions are optional, just "host" permissions, I got confused, sorry).
> 
> For AMO (frontend), that means very little changes. `host_permissions` should be displayed under the "This add-on may also ask to:" section, after `optional_permissions` (if any). The rest should not change.

So host permissions are mandatory under MV2 (so would be displayed under permissions); but optional in MV3 (so should be displayed under optional permissions).  Interesting difference - it seems that host_permissions would need adding to `optional_permissions` instead in the API in the meantime (in #20418).

**Comment by bobsilverberg** [comment]
> > In fact, it might make sense to leave MV2 "host" permissions in `permissions` since those are mandatory while `host_permissions` in MV3 are optional (not _all_ permissions are optional, just "host" permissions, I got confused, sorry).
> > For AMO (frontend), that means very little changes. `host_permissions` should be displayed under the "This add-on may also ask to:" section, after `optional_permissions` (if any). The rest should not change.
> 
> So host permissions are mandatory under MV2 (so would be displayed under permissions); but optional in MV3 (so should be displayed under optional permissions). Interesting difference - it seems that host_permissions would need adding to `optional_permissions` instead in the API in the meantime (in #20418).

Either that, or provide them in `host_permissions` in the API response and allow the consumer of the API to do whatever they want with them. FTR, I already started on this, and that's what I am currently doing, but it sounds like it might be better to hold off on API changes until we figure out exactly what the frontend needs.

**Comment by willdurand** [comment]
> t seems that host_permissions would need adding to `optional_permissions` instead in the API in the meantime (in #20418).

maybe not because we might also introduce `optional_host_permissions` in the future.. https://bugzilla.mozilla.org/show_bug.cgi?id=1766026

> provide them in `host_permissions` in the API response and allow the consumer of the API to do whatever they want with them.

+1 to that

**Comment by eviljeff** [comment]
> host_permissions in MV3 are optional (not all permissions are optional, just "host" permissions

But then 

> we might also introduce `optional_host_permissions` in the future.

🙃 

But anyway, (imo) we should have the API process and return what is needed for frontend to display the UI we want to display to the user, rather than dump all manifest fields as is. And, as far as possible, do it in manifest version agnostic way.

**Comment by bobsilverberg** [comment]
> > host_permissions in MV3 are optional (not all permissions are optional, just "host" permissions
> 
> But then
> 
> > we might also introduce `optional_host_permissions` in the future.
> 
> 🙃
> 
> But anyway, (imo) we should have the API process and return what is needed for frontend to display the UI we want to display to the user, rather than dump all manifest fields as is. And, as far as possible, do it in manifest version agnostic way.

My suggestion was to do the opposite, assuming that we cannot guess exactly how all consumers of the API will want to use the data. If the sole purpose of the API is to provide data to the frontend, then we could take the approach you suggest here, but it seems less flexible, and would require API changes to be made if we change our mind at any point about *how* to display this data in the frontend.

In any case, all of this discussion really relates to https://github.com/mozilla/addons-server/issues/20418, which I think we won't work on until we need this info for the frontend, at which point we can start the debate again. 😉

**Comment by ioanarusiczki** [comment]
@willdurand In case qa can check for this issue, please let me know.

**Comment by willdurand** [comment]
I don't think we can QA anything at this point. Verification of this issue can be done when https://github.com/mozilla/addons-server/issues/20418 is fixed, though.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-275
