### ISSUE TITLE
addon review spam on AMO

### ISSUE THREAD

**Issue by nodeticswww** [mozilla/addons-server#20424]
### Describe the problem and steps to reproduce it:

There are some people who send spammy addon "reviews" all the time. It's very annoying.

See for example:
https://www.google.com/search?client=firefox-b-d&q=site%3Aaddons.mozilla.org+5c5810fd.weaksharedptr.com

### How to prevent that spam?

How about banning for example that 5c5810fd.weaksharedptr.com string so that any review containing it will be automatically sent to trash?

**Comment by wagnerand** [comment]
Thank you for letting us know.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-279
