### ISSUE TITLE
Host permissions of the already signed MV3 add-ons should be stored in `webext_permissions`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#20434]
We started to store the MV3 host permissions in https://github.com/mozilla/addons-server/issues/20417. We should backfill the data for existing add-ons. This shouldn't be too complicated since only MV3 add-ons can define this manifest key.

**Comment by ioanarusiczki** [comment]
@willdurand Same as for https://github.com/mozilla/addons-server/issues/20417#issuecomment-1457791636 ?

**Comment by willdurand** [comment]
> @willdurand Same as for [#20417 (comment)](https://github.com/mozilla/addons-server/issues/20417#issuecomment-1457791636) ?

Yes please.

**Comment by ioanarusiczki** [comment]
@willdurand Ok thanks. then it's a qa not needed

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-280
