### ISSUE TITLE
Show "Unlisted auto-approval delayed temporarily" icon after expiry

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20444]
### Describe the problem and steps to reproduce it:

When the unlisted auto-approval delay has expired and the add-on is still in the queue (because a channel has auto-approval disabled or `needs_human_review` is set)...

### What happened?

...we are no longer showing the icon for that in the queue entry and the row is no longer highlighted in yellow, but the add-on is still only visible to users with that permission.

### What did you expect to happen?

...we should keep showing the corresponding icon and highlight the row. It should still only be visible to users that have the permission to see it.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand 

- for the scenario when an addon has unlisted auto-approval delay set -> after the time expires the icon for unlisted auto-approval delayed temporarily is still displayed. The addon is in yellow for users with a specific permission. 

- when I disable auto-approval for the unlisted channel and I submit another version ->there's only unlisted auto-approval disabled flag. But I think this should be expected. 

Let me know if my testing is alright.

**Comment by wagnerand** [comment]
Sounds good, thanks!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-282
