### ISSUE TITLE
Consider removing `file`/`files` from arguments passed to `ActivityLog` creation in reviewer actions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20442]
We are not using the `files`/`file` argument that is passed to `ActivityLog` created by reviewer actions, should we remove it ? We pass `version`/`versions`, which should be enough...

**Comment by diox** [comment]
Fine with me.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-281
