### ISSUE TITLE
Don't create DeniedGuid when gc (garbage collection) is hard-deleting add-ons without versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20447]
[Langpacks are submitted automatically](https://moz-releng-docs.readthedocs.io/en/latest/addons/langpacks.html) when Firefox (or Nightly, or Dev Edition...) is released.

Only users with the specific permission can submit them:
https://github.com/mozilla/addons-server/blob/9b453173c2bd5c6495eca8800dabeec835250bff/src/olympia/access/acl.py#L46-L56

In addition, they all have a special `guid` ending in `@firefox.mozilla.org` or `@devedition.mozilla.org`. Interestingly, these guids are not currently in the `RESERVED_ADDON_GUIDS` as this was meant for the privileged add-ons that are signed by https://github.com/mozilla-extensions/xpi-manifest.

On stage, it appears that some langpack add-ons were created without versions - probably using the old signing API - were then disabled, and then automatically deleted. When they got deleted, their guids entered the `DeniedGuid` table, and their `guid` became impossible to re-use.

This is a problem for langpacks submitted automatically, as it's impossible for releng script to deal with that error.

Specifically for langpacks, for users with the permission, we should bypass `DeniedGuid` entirely. This mechanism was meant to avoid the possibility of a disabled-but-deleted malicious add-on re-using a guid, becoming able to ship updates to existing users, but that shouldn't be a concern here, it does us more harm than good for langpacks.

**Comment by diox** [comment]
Note: I cleared all langpack-like guids from `DeniedGuid` on stage.

**Comment by eviljeff** [comment]
(These days) we only add a guid to `DeniedGuid` if the guid is one of: a) blocked; b) specifically denied by a reviewer via the reviewer tools; c) deleted when the addon status is STATUS_DISABLED; d) hard-deleted via the delete_addons task/command.  

They all seem like valid scenarios, even for langpacks, so should we just clear any old langpack guids from the table instead?

**Comment by diox** [comment]
I think I found the missing piece of the puzzle:
> On stage, it appears that some langpack add-ons were created without versions - probably using the old signing API - were then disabled, and then automatically deleted. When they got deleted, their guids entered the DeniedGuid table, and their guid became impossible to re-use.

Because they were versionless (submission failed mid-way) they were eventually picked up by the `gc` cron, which triggered the `deleted_addons` task on them, which hard-deleted them and added them to the `DeniedGuid` table directly. 

They were never disabled.

That is the core problem IMHO: versionless add-ons are fine to hard-delete, but we shouldn't add them to `DeniedGuid`. Doing that is only useful for add-ons we hard-deleted for other reasons (legacy we don't want to keep, etc)

**Comment by eviljeff** [comment]
> Because they were versionless (submission failed mid-way) they were eventually picked up by the `gc` cron, which triggered the `deleted_addons` task on them, which hard-deleted them and added them to the `DeniedGuid` table directly.

Oh! I didn't know that task was used in the `gc` cron too.  Yeah, adding such add-ons to the `DeniedGuid` table doesn't seem to be what we want.  That's the fix, I guess?

**Comment by diox** [comment]
Yeah. Maybe we should add an argument to `delete_addons` for when we want that behavior, but not enabled by default, and enabled when called from `gc`. And remove existing langpack-like guids from `DeniedGuid`.

**Comment by bobsilverberg** [comment]
@eviljeff I suggest we change the name and description of this issue as it no longer accurately describes what's being done and may be confusing for QA.

**Comment by diox** [comment]
I think so to be safe, but could be done separately.

**Comment by ioanarusiczki** [comment]
@diox 

I'm thinking the following: 

1. submitting a lang pack 
2. hard deleting it -> at this point I need your help 
3. try to re-submit the langpack -> it should work

**Comment by diox** [comment]
On stage, @ioanarusiczki created `langpack-cs1@firefox.mozilla.org`. I hard-deleted the versions, altered the add-on creation date to be in the past, then manually ran the `cron gc` command.

**Comment by ioanarusiczki** [comment]
@diox

 I submitted again the lang pack https://addons.allizom.org/en-US/firefox/addon/language-%C4%8De%C5%A1tina-czech/ using the same guid.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-283
