### ISSUE TITLE
Don't display host permissions for MV3 add-ons found in `permissions`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#20465]
As mentioned at [here](https://github.com/mozilla/addons-frontend/issues/12038#issuecomment-1461687840), MV3 add-ons should not have host permissions listed in `permissions`, and should only have them in `host_permissions`. If they are listed in `permissions` the linter will issue a warning, but still allow submission, and Firefox will ignore them. We therefore should also not display any host permissions found in `permissions` for MV3 add-ons.

**Comment by diox** [comment]
Conversely: we shouldn't store `host_permissions` for MV2 add-ons, we should ignore them at parsing time.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

- MV3 addons, I've added host permissions in permissions , and they're being ignored, the linter throws a warning:
/permissions: Invalid permissions "http://www.mysite.com/" at 0.

The API ignores host permissions in permission.

Frontend will display host permissions into This add-on may also ask to: section. They're never present into "This add-on needs to:"

- MV2 addons, host permissions are displayed into permissions, ignored in host_ permissions 
Warning is "/host_permissions" is in a format not supported in manifest versions < 3.

Frontend will display host permissions only in "This add-on needs to:" section

This is the expected result.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-286
