### ISSUE TITLE
Hide or disable "Listed Auto-Approval" toggle button for promoted groups that have auto-approval disabled

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20464]
### Describe the problem and steps to reproduce it:

At least listed versions of an add-on in some promoted groups should not get auto-approved. 

### What happened?

Reviewers can still click the toggle to "<Enable|Disable> Listed Auto-Approval". According to @eviljeff, the toggle is ignored either way in this scenario.

### What did you expect to happen?

We should hide or disable that toggle button for add-ons in promoted groups that have auto-approval disabled. I assume hiding would be easiest to implement, but it might be nicer to disable the button and change it's label to "Listed Auto-Approval disabled by Promoted group" or similar.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@wagnerand @eviljeff 

1. I verified on -dev , went through all the promoted listed add-ons to check the button:

- before being promoted

![before being promoted](https://user-images.githubusercontent.com/33448286/226620792-40ec347f-8fd6-43a1-9cee-210146349977.png)

- when being promoted

![after being into the promoted group](https://user-images.githubusercontent.com/33448286/226621021-b053e10c-2531-4053-825b-2d93d8454653.png)

2. There is an exception in the Promoted group - the Strategic add-ons will not have the button greyed out
Example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/625098

3. After adding a listed version into Notable I've noticed that Set needs Human review button changes it's state to Change Version Review Due Date. This does not happen to the other types of promoted add-ons. Then if I move an add-on from Notable to Recommeded or any other, the add-on remains with Change Version Review Date. 

Let me know if points 2 and 3 are alright.

**Comment by ioanarusiczki** [comment]
@wagnerand Is the strategic add-ons not part of this change?

**Comment by eviljeff** [comment]
> @wagnerand Are the strategic add-ons not part of this change?

Strategic group doesn't disabled auto-approval

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, I knew that but they're not being used so I forgot it. Thanks!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-285
