### ISSUE TITLE
Only apply `needs_human_review` to non-public listed versions under certain conditions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20479]
### Describe the problem and steps to reproduce it:

This is a followup of #20422.

It states: "Listed addons with non-public versions should still be added to the Notable group once the user threshold is reached.",

**and `needs_human_review` should be set only if:**

the version has been signed and not been reviewed by a human (manually approved, auto-approval confirmed, rejected, blocked).

### Steps to reproduce the regression of #20422:

1. Submit a listed version.
2. Let it auto-approve and confirm approval, or manually approve it.
3. Disable or delete the add-on.
4. Set the usage above the threshold for Notable add-ons.

### What happened?

The latest version (actually `current_version` if I am not mistaken) gets the `needs_human_review` flag, which makes it get a due date, which in turn makes the add-on appear in the review queue.

### What did you expect to happen?

The version should not receive `needs_human_review`, and thus no due date and therefore not appear in the review queue.

**Comment by diox** [comment]
> The latest version (actually `current_version` if I am not mistaken) gets the `needs_human_review` flag, which makes it get a due date, which in turn makes the add-on appear in the review queue.

It's currently:
https://github.com/mozilla/addons-server/blob/6dea5725f23edf66d729906372e44b4499cd3b8b/src/olympia/promoted/models.py#L131-L143

We should change that to pick the latest `signed` version then.

**Comment by wagnerand** [comment]
Ah, do I understand correctly that "not been reviewed by a human (manually approved, auto-approval confirmed, rejected, blocked)", is already fulfilled by `and not version.human_review_date`. Did we backfill that date for old existing versions?

**Comment by eviljeff** [comment]
"Listed addons with non-public versions should still be added to the Notable group once the user threshold is reached but only if the version has been signed and not been reviewed by a human"

I think you mean something slightly different - that the add-on should still be added to the Notable group, but it's the due_date (and/or `needs_human_review` flag) that shouldn't happen if already reviewed?

**Comment by wagnerand** [comment]
> I think you mean something slightly different - that the add-on should still be added to the Notable group, but it's the due_date (and/or `needs_human_review` flag) that shouldn't happen if already reviewed?

Yes, you are right, let me update the issue above.

**Comment by diox** [comment]
> Ah, do I understand correctly that "not been reviewed by a human (manually approved, auto-approval confirmed, rejected, blocked)", is already fulfilled by `and not version.human_review_date`? Did we backfill that date for old existing versions?

Yes, we have backfilled that best we could in https://github.com/mozilla/addons-server/issues/20370

**Comment by wagnerand** [comment]
> I have this addon [reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/502955](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/502955) already notable, last version has auto-approval confirmed but I can submit a new listed version if needed.

I am not 100% sure, but this case might only happen for an add-on that gets added to Notable. @diox, do you have more insight, based on the code?

> After I do that , you said it has to be disabled or deleted, I assume the entire add-on , not just a version, should I use force-disable?

Yes, the entire add-on, but it has to be deleted/disabled by the author (in the devhub). Force-disable is an action by Mozilla, and will have a different effect here.

> If now on AMO dev the value is 5 for notable-adu-threshold , this addon has 13. I should set it higher than 13, am I correct?

I think that could work. First, remove it from Notable (to be double-checked with Mat), then increase the threshold and then increase the usage of the add-on.

> Should I try testing anything with unlisted versions? Title and description are a bit confusing and I'm also limited about the addons with ADU on -dev and -stage, reason why I ask for details.

No need to try with unlisted versions, this only applies to listed versions.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-291
