### ISSUE TITLE
Merge `Dockerfile.deploy` and `Dockerfile`, using the same image for development and production

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20472]
We're currently building and using 2 different docker images:
- One built by CircleCI from `Dockerfile.deploy`, available over mozilla/addons-server on Docker Hub
- One built manually from `Dockerfile`, available over addons/addons-server on Docker Hub

This is annoying, and especially so as Docker has notified us that the `addons` org was using a legacy free plan that they have deprecated.

We should find a way to merge the 2, possibly fixing the long-standing issues around permissions (like https://github.com/mozilla/addons-server/issues/20263) caused by users not using the same `uid` as the development image expects.

Then we'll be able to remove the development image completely, as well as the entire `addons` org on Docker Hub.

**Comment by diox** [comment]
Main differences at the moment:
- User and uid
- Additional dependencies (development image has additional requirements `docs.txt`, `dev.txt`, `tests.txt` - it also uses the `make update_deps` instead of manually specifying which packages to install)
- Directories used for dependencies (development image uses `/deps`, which is created with the `olympia` user it creates)

**Comment by diox** [comment]
One problem with the dev dependencies not included in the image by default is that if we add them to the container afterwards, any time the container is recreated by `docker-compose` we might have to start from scratch. Which is annoying already, but doubly so because we need `debug_toolbar` to start the server. So we might need to install dev/tests/docs dependencies in the image even if we won't use them in production.

An alternative could be to keep a `Dockerfile` for local envs, and in `docker-compose.yml` not specify an image, but instead for the image to always be built. The problem with that is then:
- Either we depend on the prod image, and we have to reconcile dependencies installed as `root` in a different place
- Or we don't and the build takes a while locally

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-288
