### ISSUE TITLE
"Confirm auto-approval" should be available for auto-approved versions of invisible or deleted add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20481]
### Describe the problem and steps to reproduce it:

"Confirm auto-approval" should be available for auto-approved versions of invisible or deleted add-ons.

### What happened?

Such add-ons might get added to the queue when they get added to the Notable group, but we don't have a way to get them out of the queue.

### What did you expect to happen?

With confirmation being available, the add-on can be removed from the queue. The alternative to that would be blocking which is already available. Rejecting is not an option and can't be one.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
Sounds good, thanks!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-292
