### ISSUE TITLE
Add-ons Developer picture is not aligned in My Profile page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2048]
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/
2. Go to <Username>->My Profile 
3. Observe Add-ons Developer picture

Expected results:
The picture is aligned.

Actual results:
The picture is not aligned.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue: 
![2016-03-30_1421](https://cloud.githubusercontent.com/assets/15685960/14140681/2a39011c-f683-11e5-8d6b-65b272801955.png)

**Comment by muffinresearch** [comment]
Already fixed by other changes:

<img width="605" alt="user_info_for_admin____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14151655/d465a668-f6a6-11e5-9eb0-00d962e18d3e.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-03-31_1842](https://cloud.githubusercontent.com/assets/15685960/14181633/65f32f28-f770-11e5-8edd-963a62429eb1.png)
