### ISSUE TITLE
Upgrade to django4.2 LTS

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20493]
The RC1 for the next LTS release of django is [available](https://www.djangoproject.com/weblog/2023/mar/20/django-42-rc1/) [now](https://pypi.org/project/Django/4.2rc1/) so it's time to get addons-server up to spec.  No rush though - 3.2 LTS is supported for another year.

**Comment by eviljeff** [comment]
Most of the heavy work should have been in https://github.com/mozilla/addons-server/issues/19595 already

**Comment by eviljeff** [comment]
This is the only thing that jumps out at me from the 4.2 release notes:

https://docs.djangoproject.com/en/dev/releases/4.2/#setting-update-fields-in-model-save-may-now-be-required
> In order to avoid updating unnecessary columns, [QuerySet.update_or_create()](https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.update_or_create) now passes update_fields to the [Model.save()](https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.save) calls. As a consequence, any fields modified in the custom save() methods should be added to the update_fields keyword argument before calling super(). See [Overriding predefined model methods](https://docs.djangoproject.com/en/dev/topics/db/models/#overriding-model-methods) for more details.

**Comment by eviljeff** [comment]
re: https://docs.djangoproject.com/en/dev/releases/4.2/#setting-update-fields-in-model-save-may-now-be-required

None of our tests fail currently so this is likely not going to impact us immediately... but it's a glaring bug that may bite us at some later point when we don't understand why a `update_or_create` call isn't causing a particular automatically-set field to be saved to the database while it _is_ set in the in-memory instance.

Using [IPLog.save](https://github.com/mozilla/addons-server/blob/master/src/olympia/activity/models.py#L231:L235) as an example, this is the existing code:
```python
class IPLog(ModelBase):
    # ....
    def save(self, *args, **kwargs):
        self._ip_address = str(self.ip_address_binary)
        return super().save(*args, **kwargs)
```

At it's most simple we just always set the field and add the field to `update_fields`:
```python
class IPLog(ModelBase):
    # ....
    def save_(self, *, update_fields=None, **kwargs):
        self._ip_address = str(self.ip_address_binary)
        if update_fields is not None and '_ip_address' is not in update_fields:
            update_fields = ('_ip_address', *update_fields)
        return super().save(update_fields=update_fields, **kwargs)
```
The edge case here is when we're _not_ saving `ip_address_binary` but it _was_ set/updated on the instance, so the record could end up inconsistent in the database. The more complete version is:
```python
class IPLog(ModelBase):
    # ....
    def save(self, *, update_fields=None, **kwargs):
        if update_fields is None or 'ip_address_binary' in update_fields:
            self._ip_address = str(self.ip_address_binary)
            if update_fields is not None and '_ip_address' is not in update_fields:
                update_fields = ('_ip_address', *update_fields)
        return super().save(update_fields=update_fields, **kwargs)
```
We'll need this boilerplate-style code in the `save` method in 18 models, and it ended up quite a long template to be added to each.  I started thinking about how to move this functionality into `olympa.amo.ModelBase` and came up with this:
```python
class ModelBase(SaveUpdateMixin, models.Model):
    # ....
    def save(self, *, update_fields=None, **kwargs):
        field_names_to_save = (
            (field.name for field in self.__class__._meta.fields)
            if update_fields is None  # get all the field names in the class
            else update_fields  # else just save the fields we are updating
        )
        extra_fields = [
            getattr(self, f'save__{field_name}__', lambda: None)()
            for field_name in field_names_to_save
        ]
        if update_fields is not None:
            update_fields = (
                *(xtra for xtra in extra_fields if xtra and xtra not in update_fields),
                *update_fields,
            )
        super().save(update_fields=update_fields, **kwargs)

class IPLog(ModelBase):
    # ....
    def save__ip_address_binary__(self):
        self._ip_address = str(self.ip_address_binary)
        return '_ip_address'

    # no overridden save method
```
So for each field we want to automatically set based on another field, we would add a specific save method that gets called.  It makes for much more straightforward `save` methods, without duplicated boilerplate code, ... but it's a bit magic sauce.

@diox thoughts?

**Comment by diox** [comment]
That feels a bit too magical and over complicated to have in a base model.

Currently we have 17 models with a custom `save()` (excluding the 3 base mixins from `amo/models.py`):

| Model | Modifies a field that depends on another one in `save()` |
| ----- | -------------------------------------------------------- |
| `FileUpload` | ✅ |
| `Collection` | ✅ |
| `Translation` | ✅ (but special enough that you should never use `update_or_create` on it...) |
| `PromotedAddon` | ❌ |
| `PromotedTheme` | ❌ (empty `NotImplemented` save, it's just a wrapper)
| `Addon` | ❌ (unless extreme edge case) |
| `AddonGUID` | ✅ (but that model is obsolete) |
| `Rating` | ❌ |
| `ScannerResult` | ✅ (but unlikely to ever call `update_or_create` on it) |
| `ScannerQueryResult` | ✅ (but unlikely to ever call `update_or_create` on it) |
| `InstallOrigin` | ✅ |
| `DeniedInstallOrigin` | ✅ |
| `EmailUserRestriction` | ❌ (same field) |
| `AppVersion` | ✅ |
| `IPLog` | ✅ (but should go away) |
| `Block` | ❌ |
| `BlocklistSubmission` | ✅ |


And we're currently using `update_or_create` on:
- `AddonReviewerFlags`
- `AddonUser`
- `ApplicationsVersions`
- `AutoApprovalSummary`
- `PromotedAddon`
- `PromotedApproval`
- `RatingAggregate`
- `VersionReviewerFlags`
- `WebextPermission`

Of those, only `PromotedAddon` has a custom `save()`... that wouldn't be affected, as noted in the table above.


So I don't feel this is worth the added complexity... but I agree this could be dangerous...

**Comment by eviljeff** [comment]
Other than some test clean-up once we're sure there aren't any problems, this is done.  addons-server is running django 4.2 on addons-dev and stage/prod will follow for the next tag/push.

**Comment by eviljeff** [comment]
QA:
This is a major update so potentially any part of AMO that uses addons-server could be impacted.  Devhub and reviewer tools particularly (I found and fixed a change with form rendering already) but anything could be affected, including the more opaque parts like cron jobs and celery tasks.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I've noticed that admin tools changed the font style, table headers or entire columns used to be with bold text and now they're not. 

There are some new elements, such as a new search bar on the left menu. All modules have drop downs in the Filter on the right side. 

Buttons are reversed in all modules, if I took a look at -stage right now: 

![stage](https://user-images.githubusercontent.com/33448286/235912500-d7b24a46-788f-4e4b-80f3-0fcbcaf46945.png)

This is on dev:

![dev](https://user-images.githubusercontent.com/33448286/235912628-d00f3d61-f459-40aa-aa6a-cf8bc98beb70.png)

I also have a question, you mentioned the celery tasks but I don't know what is impacted by it. Can you share more info please?
As for cron jobs, I'll check the auto-approvals and the notable add-ons.

**Comment by eviljeff** [comment]
> @eviljeff
> 
> I've noticed that admin tools changed the font style, table headers or entire columns used to be with bold text and now they're not.
> 
> There are some new elements, such as a new search bar on the left menu. All modules have drop downs in the Filter on the right side.
> 
> Buttons are reversed in all modules, if I took a look at -stage right now:

Ah, yeah there were changes to django admin I should have mentioned.  (I believe the buttons moving around were deliberate changes from the django developers).  We try not to customize the admin too much so as long as it's not inconsistent (e.g. some custom form we added now looks out of place with the default forms) and functional I think that's fine. 

> I also have a question, you mentioned the celery tasks but I don't know what is impacted by it. Can you share more info please? As for cron jobs, I'll check the auto-approvals and the notable add-ons.

We do maintain a list of all the [possible background celery tasks](https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L819:L917) but I don't think it's practical to go through them one by one so it's more keep an eye out for something being wrong. Background tasks wouldn't overtly fail with an on-screen error, they'd just silently fail so whatever the task was supposed to do wouldn't happen (to pick a random example, the theme preview image fails to generate).

**Comment by ioanarusiczki** [comment]
@eviljeff 

Ok, thanks for the info.

I did not notice it until today , in admin:
- [Promoted change](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/promotedaddon/128/change/)  on stage and then on dev the [image and gradient color sections ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/427/change/)are weird.
- Secondary hero shelves module -> svg icons are not visible on [dev ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/secondaryheroshelf/23/change/)  

Should I file followups for both cases?

**Comment by eviljeff** [comment]
> @eviljeff
> 
> Ok, thanks for the info.
> 
> I did not notice it until today , in admin:
> 
>     * [Promoted change](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/promotedaddon/128/change/)  on stage and then on dev the [image and gradient color sections ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/427/change/)are weird.
> 
>     * Secondary hero shelves module -> svg icons are not visible on [dev ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/secondaryheroshelf/23/change/)
> 
> 
> Should I file followups for both cases?

yes please.  (just one issue is fine because they're both about the discovery admin tools)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-293
