### ISSUE TITLE
Include non-public add-ons when (re)setting hotness

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20494]
The `hotness` value in AMO is a denormalized field representing user growth of an add-on. It's exposed on the frontend as the "Trending" sort. It's reset each day but only with public add-ons, so for everything else the data isn't necessarily accurate in the database, so let's change that.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-294
