### ISSUE TITLE
Add new GUID in the list of reserved GUIDs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#20503]
We should add the `@mozac.org` GUID suffix to the [list of reserved GUIDs](https://github.com/mozilla/addons-server/blob/866b5aa967142e6a6f72401bc6df70df7349d710/src/olympia/constants/base.py#L369) because that's used by Fenix's built-in add-ons.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-298
