### ISSUE TITLE
Force-disabling an add-on should remove all `needs_human_review` flags on its versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20507]
From https://mozilla-hub.atlassian.net/browse/AMO-47

When a reviewer force-disables an add-on, that should remove all `needs_human_review` flags on its versions (as well as `due_date`).

**Comment by ioanarusiczki** [comment]
@diox 

I tried with various addons from the Manual Queue on -dev and in all scenarios after I force disabled the addon, due dates and flagged for human review were cleared (checking on each version in admin) 

Addons I've tested with are below, I've tried to cover: promoted addons, with mixed versions, listed/unlisted addons delayed indefinitely, delayed temporarily, listed/unlisted auto-approval disabled. 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/616566
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625027
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/618965
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625075
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/624952
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/621563

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-300
