### ISSUE TITLE
Fail on user rating containing banned words

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20520]
Second part of https://mozilla-hub.atlassian.net/browse/AMO-48

> I want to automatically deny or flag a user rating for moderation, if the rating text matches a string in a list. The list needs to be non-public and editable at any time, with immediate applying of any changes. For every item in the list, I want to choose whether to automatically deny or flag a rating for moderation.

This issue will focus on denying a rating - i.e. failing immediately with a validation error

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and these are my results:

- trying to post a new review that contains a banned keyword will generate an error message
- editing an exiting review text that contains a banned word generates an error message
- all the banned words detected are currently displayed in the error message text
- the auto-flag review action is still working as before

![image](https://user-images.githubusercontent.com/31961530/229517151-354ca636-ff53-4818-ae8e-41ac1469d445.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-303
