### ISSUE TITLE
Drop `due_date` on versions disabled and not signed

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20526]
Part of https://mozilla-hub.atlassian.net/browse/AMO-47

- When a developer disables a version that isn't signed yet and has `needs_human_review`, the due date is removed.
- When a developer re-enables a version that had `needs_human_review`, it gets a due date again.
- When a developer deletes a version that isn't signed yet (internally this disables the files) and has `needs_human_review`, the due date is removed.
- When a developer deletes an entire add-on, the due date should be removed on versions that aren't signed yet and have `needs_human_review` (internally all files would be disabled).
- When a developer sets an add-on as "Invisible", the due date should be removed on _listed_ versions that aren't signed yet and have `needs_human_review` (internally there should be a maximum of one listed version pending review at any given time, and when the add-on is made invisible the file would be disabled).

In all other cases involving `needs_human_review` the due date needs to stay regardless of what the developer does.

We currently keep `due_date` if a version that has `needs_human_review` is signed or non-deleted:
https://github.com/mozilla/addons-server/blob/c206243bfd5c240637115ececbba4725e95f58ed/src/olympia/versions/models.py#L207-L210

We actually want to keep `due_date` if a version that has `needs_human_review` is signed or non-_disabled_ instead.

**Comment by ioanarusiczki** [comment]
@diox 

I all the scenarios above and I think it's working as expected.

For the scenario when a developer makes an addon invisible and there are still unsigned versions -> these versions become unreviewed (disabled) and will remain in this state.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-305
