### ISSUE TITLE
No "Complete Themes" link

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2052]
Steps to reproduce:
1. Load AMO-stage homepage https://addons.allizom.org/en-US/firefox/
2. Hover over "Themes"

Expected results:
"Complete Themes" link is displayed at the end of the drop-down.

Actual results:
"Complete Themes" link is not displayed.

Notes/Issues:
Complete Themes page can be accesed from about:addons page.
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![2016-03-30_1457](https://cloud.githubusercontent.com/assets/15685960/14141470/d174de7a-f687-11e5-912a-80d79f410c90.png)

**Comment by tofumatt** [comment]
I'm of the thought that these are going away and more fragile than "new themes", so advertising them isn't worth it. We can add the link back easily if this was an oversight, but I assume it was an intentional UX decision.

**Comment by eviljeff** [comment]
@atsay

**Comment by jvillalobos** [comment]
This definitely wasn't run past us. The link shouldn't be any less prominent than it is in the previous style.

**Comment by tofumatt** [comment]
Cool, I'll have to add them back. This is blocker then.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-03-31_1739](https://cloud.githubusercontent.com/assets/15685960/14179382/98e8e336-f767-11e5-9d18-372271102597.png)
