### ISSUE TITLE
Migrate to Docker Compose v2

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20534]
Docker Compose v1 (aka `docker-compose`), won't be supported anymore **and removed** from Docker Desktop from the end of June 2023: https://docs.docker.com/compose/reference/

We need to update our docs and build files to use Compose v2 (aka `docker compose`).

**Comment by eviljeff** [comment]
@diox can you confirm that one of https://docs.docker.com/compose/install/#installation-scenarios is viable on Linux versions that don't have `docker compose` by default?

**Comment by diox** [comment]
It's working - gotta replace the `docker` that came with the distro with the official packages though.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-310
