### ISSUE TITLE
Disallow changing compatibility info of a version in the Developer Hub if compatibility info was present in manifest

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20531]
https://docs.google.com/document/d/1Uou3WEI6W0fwLpzipLMEZHycWOUGWiDQAbVTAPemaYo/edit#heading=h.c75pefc0iki4

- When the `browser_specific_settings.gecko_android` key is present in the manifest, AMO MUST automatically mark this add-on as compatible with Android. The compatibility range will be determined by the `strict_min_version` and `strict_max_version` specified in both `browser_specific_settings.gecko` and `browser_specific_settings.gecko_android`, if any (`gecko_android` takes precedence)
- When the `browser_specific_settings.gecko_android` key is present in the manifest, AMO SHOULD display the values in devhub, but MUST no longer allow modification from what is in the manifest.
- When the `browser_specific_settings.gecko_android` key is *not* present in the manifest, AMO SHOULD make no assumptions about the compatibility of the add-on with Android. Therefore, it MUST show the checkbox to mark the add-on as compatible with Android during submission.

This should probably be done by adding a new field in `ApplicationsVersions` specifying that the min and max values were imported from the manifest automatically, so that they cannot be changed. This should only apply to Android, as just the presence of the `gecko` key isn't enough to determine whether something is compatible with Desktop at this point.

**Comment by diox** [comment]
The main driving force behind this issue was to track which add-ons were explicitly compatible with Android - those using `gecko_android` in their manifest. Once that key start being used by enough developers, that would allow us to later show on the detail page which add-ons are truly supposed to be compatible, and which ones are less guaranteed to be. Having the manifest the source of truth for _all_ compatibility was the next logical step.

But there are two issues:

### Developer might want to (temporarily or permanently) avoid being listed on Android even though their add-on is compatible.

The only way to do that right now is to remove Android compatibility for the current version. So, we have 2 choices:
1) Allow removing compatibility even if manifest said it was compatible, but track behind the scenes which versions it was compatible with, and if developer ever re-adds Android compatibility, follow the manifest min/max again.
2) Disallow removing compatibility and introduce another way to disable a listing for Android.

### Developer might have Android-specific add-ons that just specify `gecko` in their manifest

If the manifest has `gecko` + either `strict_min_version` or `strict_max_version`, we don't actually know for sure the add-on is intended for Firefox Desktop. It should be technically compatible, but there are Android-specific add-ons out there, that developers chose to not make available for desktop. Eventually as developers switch to `gecko_android` that would no longer be an issue, but it is for now.

I think we need to go back to the original problem we were trying to solve, and just record somewhere that an extension used `gecko_android` in their manifest. Completely revamping source of truth for compatibility is a harder problem to solve, that would be a lot easier once all Android extensions have switched to the explicit `gecko_android` key.

**Comment by diox** [comment]
I have edited this issue's description to address the challenges from the last comment.

**Comment by ioanarusiczki** [comment]
@diox 

With only gecko_android declared in the manifest (mv2 or mv3) , after the upload Firefox is checked by default and Firefox for Android is automatically checked

When I un-check Firefox 

![gecko_android1](https://github.com/mozilla/addons-server/assets/33448286/eb6d6bf9-82d4-4e75-be8e-8521e506b916)

**Comment by diox** [comment]
Argh, somehow I missed that case. I'll look into it.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-308
