### ISSUE TITLE
Show compatibility checkboxes once upload is made in submission page

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20532]
We currently show Firefox/Android compatibility checkboxes right at the beginning of the
submission process. We should hide it initially instead, and show it if it's an extension once we have the upload.

**Comment by ioanarusiczki** [comment]
@diox 

On -dev "Which applications is this version compatible with?" is no longer displayed at the beginning. 

I'll test the rest of it when submissions are fixed.

![now](https://github.com/mozilla/addons-server/assets/33448286/db50a119-7f62-464c-889a-b4397dbe8605)

Before: 

![before](https://github.com/mozilla/addons-server/assets/33448286/d1e4cd16-4fb4-47fa-aa02-3d39183f4884)

**Comment by ioanarusiczki** [comment]
@diox 

Applications will appear only after an upload on "Submit a New Addon" page when it's an extension. 
Applications won't show up for static themes, lang packs or dictionaries. 

I've noticed an issue about the case when applications are both un-checked and filed https://github.com/mozilla/addons-server/issues/20771

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-309
