### ISSUE TITLE
The tests results are not aligned in the validation report page

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2054]
**Steps to reproduce:**
1. Open amo homepage: https://addons.allizom.org/en-US/firefox/
2. Hover over Tools and select "Submit a New Add-on".
3. Click on "Select a File" and upload a new add-on
4. When the validation is completed click on the "See full validation report" link.

**Expected results:**
The page opens, there are no layout or display issues.

**Actual results:**
The tests are not displayed in a single line. 

**Notes/Issues**:
Verified in FF45(Win7) Issue can be reproduced in -dev and stage.
Screencast for this issue: http://screencast.com/t/i7vtaNO3iwq0   (Before the style refresh: http://screencast.com/t/LjNZKTz4)

**Comment by muffinresearch** [comment]
This looks to be ok now:

<img width="549" alt="validation_results_for_54310d688b7a471aa0fe305dd609485f_archive_xpi____developer_hub____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14558377/1481da78-02fa-11e6-8f4f-4515a9141082.png">
