### ISSUE TITLE
The auto-flag review action generates false positives for words that have a flagged term in their composition

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20547]
Follow up for #20499

### Describe the problem and steps to reproduce it:
If a review body contains a word that includes one of our flagged keywords,  for example flagged keyword = **bad**, review body includes trou**bad**our, the auto-flag action will detect the review and flag it for moderation. This situation can lead to some false positives, so we should remediate that for the moment.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and these are the new results:

accepted combinations: bads,  badger, lambada

denied combinations: bad, bad_review, bad-review, review-bad, review_bad, bad.review, review.bad, bad/review, review/bad

I can see a potential for false negatives with plurals, which are now accepted. I guess this is acceptable for now and the final tweaks will be made once we have more data from prod.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-313
