### ISSUE TITLE
Can't update Mozilla created collection Description area

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#20548]
As an AMO admin I should be able to update the copy blurb ("Description") on our collections. But whenever I try to change the Description and save, I get a red error message that reads "This name cannot be used." (which is curious since I'm not touching the name). 

We are aiming to feature three different collections in an experiment starting 12 April. 

@willdurand @diox @eviljeff 

![bug_desc](https://user-images.githubusercontent.com/8496249/228937476-ea987926-ffbb-4228-909b-3fc7337b9dd5.png)

**Comment by diox** [comment]
Both the name and the description go through validation when you save changes, and it looks like `Firefox` is not allowed in collection names (it may have been in the past).

We don't currently have a way to bypass that using the user-facing collection management feature, but you should be able to edit it through the staff admin by going to `/en-US/admin/models/bandwagon/collection/5367586/change/` (requires VPN).

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO stage and these are my results:

- users with `Collections:Edit` permission are now able to edit collection details on the frontend  when the collection name or slug contain denied names
- users without the required permission are not able to edit collections on the frontend if the name or slug contain a denied name
- the edit description field is now available in the admin collection edit tool 

![image](https://user-images.githubusercontent.com/31961530/230043033-3a1738bd-3cc4-43ba-9ee2-c4273d681c99.png)

![image](https://user-images.githubusercontent.com/31961530/230043086-fa61be57-9cdd-42a5-b1a4-39172cef5d91.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-314
