### ISSUE TITLE
Set `needs_human_review` on new version submission if it was already set in the same channel.

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20545]
When a new version is submitted, it inherits the due date of the most recent version awaiting review in the channel. For the listed channel, if the previous version was awaiting review, the new version submitted also "replaces" the previous version if it was awaiting review, disabling that previous version, since there should only be a single version awaiting review on the listed channel at any time.

Per https://docs.google.com/document/d/1G3Bts1P7N7KA5vmLhwjZNCg50hVRn2CSfbsFaYPcD6I/edit We want to change that behavior to:
- Inherit the most recent `due_date` in channel regardless of status
- Set `needs_human_review` if it was set on any version in the channel
- On the listed channel, if the previous version was awaiting review, it should lose its `due_date` when it gets disabled (but keep `needs_human_review` until dropped by a reviewer action). That should be covered by https://github.com/mozilla/addons-server/issues/20526

**Comment by ioanarusiczki** [comment]
@diox 

1. I've noticed that flagged for human review is now present for all addons/versions I submitted even when I used dummy extensions. 

2. Not sure about "Inherit the most recent due_date in channel regardless of status"

  The next version is inheriting the due date from the previous when there's been in awaiting review. 
But once the previous version is approved or rejected and a new version is submitted, this gets a due date of 3 working days (independent from the previous version). 

  As an example, [listed addon ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625176) 
First version is flagged for human review and auto-approval is disabled, due date set to 3 days
Version 1.22.2 is in awaiting review , a new version is submitted
Version 1.22.3 is displayed now in the queue with a due date inherited from the previous version (2 days, 2 hours from now at the time 1.22.3 was submitted)
Version 1.22.3 is approved -> The addon is cleared from the Manual Queue (then I waited more than an hour and submitted a new version)
The new submitted version 1.22.4 has a due date of 3 working days.

Another example, an [unlisted addon](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625183) 

First version is awaiting review , due date 3 days from now , no action is taken and a new version is submitted
1.22.4 is approved, 1.22.3 is rejected -> addon is no longer in the manual queue 
A new version 1.22.5 is submitted and the due date is set to 3 working days from now. 

3. Delayed temporary add-ons (listed or unlisted) have a 23 hours due date set (I think the [docs](https://docs.google.com/document/d/1G3Bts1P7N7KA5vmLhwjZNCg50hVRn2CSfbsFaYPcD6I/edit# mention it should be of 3 working days)

Examples: 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625175
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625185

Also while watching the manual queue these seem to have initially a 3 working days due date, but after a while they get the "23hours from now" displayed. 

4. I also tested with developer actions (these are scenarios which I think that work as expected)

When a listed version awaiting review  was disabled by the developer the due date and flagged for human review are cleared. 
A new version submitted is flagged for review and gets a 3 working days due date. 

An unlisted approved version disabled by developer , the new version submitted has the same due date as the first
version https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625167

An unlisted approved version deleted by developer has a 1 day 20 hour due date when the reviewer clears the due date. Then the developer submits a new version which is flagged for human review and receives a 3 working day due date.

**Comment by diox** [comment]
> But once the previous version is approved or rejected and a new version is submitted, this gets a due date of 3 working days (independent from the previous version).

That's expected. What we want is to inherit the due date if there was one - so that if a new version is submitted while there was already a version waiting for review on the same channel for that add-on, the new version gets that due date, regardless of why that due date is there.

Previously we would do that only for versions awaiting review, now we do that even for, say, an automatically approved (or even approved then deleted) version that still has a due date because of something else like `needs_human_review` being set after its approval.

> Also while watching the manual queue these seem to have initially a 3 working days due date, but after a while they get the "23hours from now" displayed.

Could you tell me more about that ?

**Comment by ioanarusiczki** [comment]
@diox 

> I've noticed that flagged for human review is now present for all addons/versions I submitted even when I used dummy extensions.

I assumed that this is the expected result after the patch landed, make all add-ons enter the manual queue, sorry for that, so I re-tested with a dummy extension on listed and unlisted channel and I no longer see these present in the Manual Queue. 

> Inherit the most recent due_date in channel regardless of status

Reading your comment I've done some testing again for the situation when the versions are awaiting review but also for auto-approved versions which were set by a reviewer for human review , also  deleted or disabled by developer. For all these cases, when no reviewer action was taken and  a new version is submitted, the due date is the same for both versions. The Manual Queue will display the first version in the queue (the older one), which I think it's the expected result. 

2 examples: 
https://reviewers.addons.allizom.org/en-US/reviewers/review/620286
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1009301

> Set needs_human_review if it was set on any version in the channel

As I said above, for situations a version was flagged for human review after auto-approval, the next version submitted is flagged for human review too. 

Is this sufficient to prove what you said ?

While testing I've noticed for the listed channel that when the first version is flagged for review and auto-approval is delayed indefinitely when a new version is submitted (this time I used a dummy and it was not caught by scanners) it inherits the flagged for human review and auto-approval delayed indefinitely flags.
This is the example: https://reviewers.addons.allizom.org/en-US/reviewers/review/1009446

Is this scenario alright? 

We discussed versions delayed temporary by scanners -> they get a due date of 1 day but [this doc](https://docs.google.com/document/d/1G3Bts1P7N7KA5vmLhwjZNCg50hVRn2CSfbsFaYPcD6I/edit#) mentions a "review-time" which is 3 days.  Waiting for @wagnerand to confirm.

![second phase](https://user-images.githubusercontent.com/33448286/231156717-2d789c97-a9d3-4dcf-922d-f8916b6f5db4.png)

**Comment by diox** [comment]
That all seems good. Apologies for the previous confusion, the key about this issue is inheriting needs human review and due date in various scenarios *for a given add-on*.

**Comment by wagnerand** [comment]
> We discussed versions delayed temporary by scanners -> they get a due date of 1 day but [this doc](https://docs.google.com/document/d/1G3Bts1P7N7KA5vmLhwjZNCg50hVRn2CSfbsFaYPcD6I/edit#) mentions a "review-time" which is 3 days. Waiting for @wagnerand to confirm.

Good catch, the doc was aiming to make implementation easier, but it seems we are already doing the optimal thing, no code changes needed here.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-312
