### ISSUE TITLE
Usage of V5 Submission API

### ISSUE THREAD

**Issue by avi12** [mozilla/addons-server#20554]
### Describe the problem and steps to reproduce it:
I tried to follow the [blog post](https://blog.mozilla.org/addons/2022/03/17/new-api-for-submitting-and-updating-add-ons/) and the [documentation](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html) to automate the deployment of my extensions
Calling the [upload/ endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-create) was successful, but then calling the [addon/SLUG/versions/](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-create) wasn't:
```ts
const { data } = await axios.post(`https://addons.mozilla.org/api/v5/addons/addon/${slug}/versions/`, {
  upload: uuid, // string returned from `upload/`
  release_notes: {
    "en-US": "notes"
  },
  approval_notes: "test"
}, {
  headers: {
    Authorization: `JWT ${jwt}`
  }
});
```
When trying to call it, I'm getting:
```
upload: [' upload is not valid']
```
despite the documentation clearly stating:
![screenshot](https://user-images.githubusercontent.com/6422804/229645471-e4afee75-9e44-4cc9-9287-945ca8b0d1c5.png)

### What did you expect to happen?
I expected the documentation to be accurate, unless I'm missing something

**Comment by avi12** [comment]
Oh I see, you mean that after using the `upload/` I need to use the [upload detail endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-detail) to see the submission's status
Thanks for the heads up! I'll check it out and let you know if that solves my issue

**Comment by avi12** [comment]
What interval do I repeatedly call the "upload detail" endpoint so I don't get throttled?

**Comment by diox** [comment]
You can check every second. Stop as soon as you see `processed: true` or after like 5 minutes.

Bonus points if you implement some kind of [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) after 1 minute.

**Comment by avi12** [comment]
After implementing the following algorithm:
```ts
async function validateUpload({ uuid }: { uuid: string }): Promise<object> {
  return new Promise((resolve, reject) => {
    // https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-detail
    let delayInSeconds = 1;
    const maxDelayInSeconds = 60;
    let timeout;

    function clearTimer(): void {
      clearTimeout(timeout);
    }

    async function retry(): Promise<void> {
      axios(`upload/${uuid}/`)
        .then(({ data }) => {
          if (data.processed) {
            clearTimer();
            resolve(data);
            return false;
          }
          return true;
        })
        .then(isProcessed => {
          if (!isProcessed) {
            return;
          }
          if (delayInSeconds < maxDelayInSeconds) {
            delayInSeconds *= 2;
          }
          clearTimer();
          timeout = setTimeout(retry, delayInSeconds * 1000);
        })
        .catch(reject);
    }

    retry();
  });
}
```
the snippet in my main post gave me the error:
```
upload: ["This field is required."]
```

**Comment by avi12** [comment]
Thank you so much for your help!
It seems like my algorithm was successful and I was able to push an update

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-315
