### ISSUE TITLE
The "+ Add to Firefox" label has two colors for a preliminary reviewed add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2055]
Steps to reproduce:
1. Sign in to AMO-stage page https://addons.allizom.org/en-US
2. Go to details page for a preliminary reviewed add-on (i.e. https://addons.allizom.org/en-US/firefox/addon/adblock-vv/)
3. Observe the "+ Add to Firefox" button label

Expected results:
The label of the button is in one color.

Actual results:
The label has two colors: black for the "+" and white for the rest.

Notes/Issues:
The text "This add-on has been preliminarily reviewed by Mozilla." is also black.
Preliminary reviewed add-on had the button colored in yellow and labeled in black before style-refresh.
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![2016-03-30_1504](https://cloud.githubusercontent.com/assets/15685960/14141969/504ee7f6-f68b-11e5-826a-31efd4ac37ad.png)

**Comment by muffinresearch** [comment]
It seems that the background that should be there (the stripey yellow warning one) has been clobbered.

**Comment by ValentinaPC** [comment]
This is how things look like, now:
a) preliminary reviewed add-ons: 
![prelim](https://cloud.githubusercontent.com/assets/15685960/14178556/d661171e-f763-11e5-86ce-89a83b5af863.png)
b) fully reviewed add-ons:
![fully](https://cloud.githubusercontent.com/assets/15685960/14178576/e7d6f2a2-f763-11e5-9951-a73231d94867.png)

Reopening until further notice.

**Comment by ValentinaPC** [comment]
I missed a place :(
_Add-ons listing pages_ for preliminary reviewed add-ons.
Verified on AMO-dev FF45(Win 7).
Please see the screencast: http://screencast.com/t/pr3I9fMVY

**Comment by muffinresearch** [comment]
Yep I spotted that one too. Thanks! I'll get that fixed.

**Comment by muffinresearch** [comment]
In fact I'll open a new issue for that it'll be easier to track.
