### ISSUE TITLE
Code.AMO returns 404 error on some unlisted add-ons awaiting review/auto-approval

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20563]
### Describe the problem and steps to reproduce it:
Upon clicking "browse contents" button to explore code of certain add-ons, the editor opens with a `Unexpected status for GET /reviewers/addon/1234/versions/5678/?lang=en-US: 404` error message

### What happened?
- Select an unlisted add-on waiting approval (delayed auto-approval)
- Select a version that's "awaiting review" 
- Click on "browse contents" link
- code.AMO opens with a 404 error

### What did you expect to happen?
- If the add-on isn't deleted, the code for the add-on should be readable on code.AMO

NOTE that this doesn't happen for all unlisted add-ons awaiting review. For many, I'm able to view the code just fine on code.AMO

### Anything else we should know?
I'm seeing many unlisted add-ons showing this behavior, but you can reproduce it for `{b43cfbbc-2ca4-4398-86e3-2d85984aa33e}`. I'm wondering if this is expected in any way that I'm not aware of, but I haven't see it happen until a week or so ago.

**Comment by diox** [comment]
mmm, I can't reproduce with the add-on you gave.

**Comment by abhn** [comment]
Interesting, neither can I now. 

I had the 404 shown on a whole bunch of add-ons today (~5-8 of them in a row almost) and I confirmed the behaviour with @wesinator too. Let me get back to you when I see it again

**Comment by diox** [comment]
It's possible you're trying to load them very early before we have had a chance to extract the contents of the add-on to make it available in code manager (it's an asynchronous task with a queue to avoid taking up too much resources). When that happens you can download the file directly instead of browsing through code manager.

**Comment by abhn** [comment]
Okay, sounds like that could've been the case. I'll reopen if I spot it again. Thanks @diox!

**Comment by diox** [comment]
Somewhat related is https://github.com/mozilla/addons-server/issues/19146 - on top of not auto-approving something we haven't yet extracted, maybe we should not let them have a `due_date` yet, hiding them from the queues. But this raises a ton more questions around delays (should we add to the delay ?) and would introduce more complexity around due dates...

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-319
