### ISSUE TITLE
drop signing API from api/v5/

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20560]
Following on from a conversation in [matrix](https://matrix.to/#/#amo:mozilla.org), the signing API is old has limited functionality compared to the newer addon submission API, so lets drop it from api/v5.  Developers can keep using the signing api under api/v4 if they need it.

**Comment by ioanarusiczki** [comment]
@eviljeff 

The v5 endpoints on

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-316
