### ISSUE TITLE
Restyle under chrome no longer provides button for firefox download

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2056]
Restyle:

<img width="509" alt="disconnect____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14142507/158fd524-f67e-11e5-99f7-210a6cb5912d.png">

Current page:

<img width="561" alt="disconnect____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14142520/255e548a-f67e-11e5-86ff-a601821e3c1d.png">

Note the missing prompt to download firefox.

Also the version information looks like a button but isn't.

**Comment by ValentinaPC** [comment]
Verified on AMo-dev Chrome Version 49.0.2623.110 m (Win 7).
Postfix screenshot: 
![2016-04-07_1404](https://cloud.githubusercontent.com/assets/15685960/14349557/92003e92-fccc-11e5-9b56-a2d763d67129.png)

@tofumatt , about "Also the version information looks like a button but isn't." - should the verfion info look like a button or no?

**Comment by tofumatt** [comment]
I agree with @muffinresearch , it should not look like a button. That should be filed as a separate bug with needs UX label though; I don't know what we should change it to (or if it was intentional on their part).
