### ISSUE TITLE
Add rating user restriction

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20569]
part of https://mozilla-hub.atlassian.net/browse/AMO-49

> For every pattern, I want to decide whether ratings for matching users should be denied or flagged for moderation

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev by using the admin User email restriction and IP network user restrictions tools and these are my results:

- individual emails or email domains can be completely blocked from submitting ratings:
![image](https://user-images.githubusercontent.com/31961530/233083428-bae9ca0c-5683-4158-b57c-ff41f323ffa9.png)

- IP restrictions will block any rating posted by a user under the restricted IP:
![image](https://user-images.githubusercontent.com/31961530/233086401-43ca745c-b5e1-4826-b9e7-245c51656dfc.png)

- emails and IPs can also be flagged for moderation, which will create an entry in the Moderation queue for reviews submitted from those sources; currently, the moderation queue shows a common message for email or IP flagged ratings:
![image](https://user-images.githubusercontent.com/31961530/233089329-ec5451d9-2dd4-48c7-aedb-bf977e91274f.png)

@eviljeff The email and IP restrictions can currently be applied for only one action, for example, a user/IP can't be restricted for both ratings and addon submissions. Is this something that needs to be addressed in a future patch?

**Comment by eviljeff** [comment]
> Is this something that needs to be addressed in a future patch?

It wasn't requested in the Jira ticket. If it turns out to be needed operationally an issue can be filed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-321
