### ISSUE TITLE
Addon upload validation process stuck at 100%, validating

### ISSUE THREAD

**Issue by olfMombach** [mozilla/addons-server#20576]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

When uploading an Addon for the first time, I'm stuck at the uploading step. It says 100% and validating, but it never ends. Sometimes after a long time (could also just be the internet disconnecting when the PC is going to sleep though) it says it didn't receive a response from the server.

![image](https://user-images.githubusercontent.com/28447061/230766878-8c1263f9-5d1c-41b4-b4e6-6bd11426f8f3.png)

Steps (for me):

1. Go to "Submit a new Addon"
2. Try to upload the zip of the addon

### What happened?

As explained above, it's loading indefinitely

### What did you expect to happen?

It validating in a short time (it's a very very simple addon) and letting me proceed in the process

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by gorhill** [comment]
Had the same issue, but I just gave it another try and it worked fine this time.

**Comment by olfMombach** [comment]
You are right, tried it and this time it worked. Seems like there was a temporary outage of the servers the last days

**Comment by diox** [comment]
Hi,

Sorry, didn't see that issue. As I've replied in https://github.com/mozilla/addons/issues/1481 we have mitigated the problem but are keeping an eye on it.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-326
