### ISSUE TITLE
Contributions URL field does not allow buymeacoffee.com links

### ISSUE THREAD

**Issue by tstrass** [mozilla/addons-server#20570]
### Describe the problem and steps to reproduce it:

On the Developer Hub page to edit an extension, the front end form does not allow buymeacoffee.com links, even though the description says they are allowed.

Steps:
1. On the public page for an add-on you own, click the "Edit add-on" link
2. Scroll down to the Additional Details section and click "Edit"
3. Enter a buymeacoffee.com URL
4. Click Save Changes

From there you erroneously get the following validation message and it does not save the changes:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/8235974/230509049-8db3253c-6f64-41a6-a7e6-2696baa01a77.png">

### What happened?

I got a validation message that did not make sense and the URL did not save.

### What did you expect to happen?

I expected the URL to save and to not get a validation message.

### Anything else we should know?

Nope

**Comment by diox** [comment]
Hi,

You need to add the `http://` prefix.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-322
