### ISSUE TITLE
User rating moderation log shows non-moderated deletions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20585]
### Describe the problem and steps to reproduce it:

The user rating moderations log (`/reviewers/moderationlog`) shows non-moderated deletions as well. These are attributed to presumably the add-on developer itself, again presumably when they delete their add-on, for example (there might be other cases).

### What happened?

Log entries for deletions from non-reviewers, presumably as part of the developer-initiated add-on deletion.

### What did you expect to happen?

The log should only show reviewer moderations (_deleted_ and _approved_).

### Anything else we should know?

It would be great if we could linkify the add-on name in the log to point to the review tools page (listed channel), for both the list and the moderation log details page. Let me know if you prefer a separate issue instead.

**Comment by diox** [comment]
Note: we could use `RatingLog` introduced in https://github.com/mozilla/addons-server/issues/20023 to make all this easier. We do need to be careful about keeping the query optimized though.

**Comment by eviljeff** [comment]
After some poking around, it should only be Ratings deleted when the add-on is deleted (in addition to the valid case of a reviewer/admin deleting the Rating).  There's a check that excludes the logging when the Rating was created by the current user (`core.get_user()`).  Unfortunately there isn't a way to differentiate in the query why the Rating was deleted afterwards.  (I don't think `RatingLog` helps us much here as we'll only be able to tell that the `Rating` is deleted, which we can infer from the action)

The easy fix is to just exclude activity log entries where the addon is now deleted, but that'd hide legitimate reviewer moderation actions on the add-on before it was deleted.  The better fix it to not log the `DELETE_RATING` activity when the ratings are deleted on the back of an add-on deletion, though that wouldn't fix the existing logs (and it's not obvious how to do it, but I'm sure it's possible)

**Comment by wagnerand** [comment]
> > The easy fix is to just exclude activity log entries where the addon is now deleted, but that'd hide legitimate reviewer moderation actions on the add-on before it was deleted.
> 
> > The better fix it to not log the `DELETE_RATING` activity when the ratings are deleted on the back of an add-on deletion, though that wouldn't address the existing logs (and it's not obvious how to implement the fix, but I'm sure it's possible)
> 
> @wagnerand what do you think?

@eviljeff let's do the second approach and file a follow-up for addressing existing logs later.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and the Reviewer moderation log will now include only logs from moderated reviews (deleted or approved reviews). 

@wagnerand I think you will have to file a separate issue for the following request because it wasn't addressed in this patch:
>It would be great if we could linkify the add-on name in the log to point to the review tools page (listed channel), for both the list and the moderation log details page. Let me know if you prefer a separate issue instead.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-327
