### ISSUE TITLE
Create a heartbeat endpoint for background services 

### ISSUE THREAD

**Issue by leplatrem** [mozilla/addons-server#20602]
This would allow to detect any connectivity issue without having to wait for background tasks to fail

The endpoint would monitor:
- remote settings
- celery / rabbitmq
- autograph

See https://github.com/mozilla/addons-server/pull/20603#issuecomment-1523288569

**Comment by diox** [comment]
Thanks for taking care of this, @leplatrem !

**Comment by diox** [comment]
Now we can see we're still having credentials issues with remote settings on dev: https://addons-dev.allizom.org/services/monitor.json

**Comment by leplatrem** [comment]
> Now we can see we're still having credentials issues with remote settings on dev: https://addons-dev.allizom.org/services/monitor.json

Do you use the Remote Settings DEV server on AMO DEV? 
You could use our STAGE server if that helps.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-331
