### ISSUE TITLE
Blocking an add-on did not remove the needs human review flag on already disabled versions

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons-server#20600]
Add-on: ramirezvalencia@gmail.com

Unlisted add-on was blocked, but the needs human review flag and due date were not cleared. 

Flag cleared manually, but it should've been automatic.

**Comment by diox** [comment]
@wagnerand I assume we want this. Indeed, at the moment `needs_human_review` is only cleared for the human reject action, for the "automatic" rejection associated with the block action, we don't currently clear `needs_human_review`.

https://github.com/mozilla/addons-server/blob/0d4210a8ce3a0055ebada98365640c469b02bbdc/src/olympia/reviewers/utils.py#L1229-L1232

**Comment by wagnerand** [comment]
Yes, this is

_When a reviewer takes any of the following actions, the needs_human_review flag and the due date should be cleared for all versions:
* Block (entire) add-on_

**Comment by diox** [comment]
> @wagnerand I assume we want this. Indeed, at the moment `needs_human_review` is only cleared for the human reject action, for the "automatic" rejection associated with the block action, we don't currently clear `needs_human_review`.
> 
> https://github.com/mozilla/addons-server/blob/0d4210a8ce3a0055ebada98365640c469b02bbdc/src/olympia/reviewers/utils.py#L1229-L1232

Wasn't looking carefully enough, the needs human review flag is explicitly cleared on relevant versions, but that's done by the blocklist code:
https://github.com/mozilla/addons-server/blob/efcf1b312f6a95fc28ec699eb0f9cb7ec49217bc/src/olympia/blocklist/utils.py#L128-L131

This is consistent with QA findings. Will need to investigate more to find out what happened in this particular scenario.

**Comment by diox** [comment]
@iulianacse if that happens again, please don't clear the flag manually and paste the review URL in this thread, thanks.

**Comment by wagnerand** [comment]
@diox Iirc, files never get `STATUS_DELETED`, right? In this case, the developer deleted their add-on, I think that also sets the file status to `STATUS_DISABLED`. If so, then https://github.com/mozilla/addons-server/blob/efcf1b312f6a95fc28ec699eb0f9cb7ec49217bc/src/olympia/blocklist/utils.py#L123 excludes these versions from `review.data['versions']`, which is used in https://github.com/mozilla/addons-server/blob/efcf1b312f6a95fc28ec699eb0f9cb7ec49217bc/src/olympia/blocklist/utils.py#L128-L131.

**Comment by ioanarusiczki** [comment]
@diox 

I tried with an[ unlisted](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625253) version. 
This is has been approved and then flagged for human review then disabled by developer and then the version was blocked.  -> in that order, if I test the scenario on AMO dev , flag for human review is cleared and the version automatically goes out the Manual Review Queue when a block is created.
I'll check around for listed versions too, or mixed with fully blocked add-ons.

I see that on AMO stage right now this is still reproducible.

**Comment by ioanarusiczki** [comment]
@diox 

I tried listed/unlisted versions disabled and deleted by developers after they've been approved and flagged for human review -> when they're also blocked the flagged for human review is cleared.

I  tried to add disabled/deleted unsigned versions  to the Manual Review queue -> this is not possible 

The review page looks like in the screenshot below when `Set "needs human review" ` is clicked

![try to add](https://user-images.githubusercontent.com/33448286/234257819-4ef1761b-dd4e-4ba2-98b6-926ee51b9d10.png)

The date from the image is set but won't have any effect (I could open the calendar and click on it)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-330
