### ISSUE TITLE
Developer's name is not visible after pressing "Continue to download" button

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2061]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Open an addon with contribution roadblock available (https://addons-dev.allizom.org/en-US/firefox/addon/foxyproxy-standard/?src=ss)
2.Press the "Continue to Download " button
3.Observe the developer name section

Expected results:
Developer's name is visible

Actual results:
Developer name is not visible(white text on white background)

Please see screencast for this bug : http://screencast.com/t/5hqwH3Jhv
Reproducible on stage and -dev

**Comment by ValentinaPC** [comment]
Developer's name is, also, not visible in Edit Theme page.
Please see the screenshot: 
![2016-03-30_1701](https://cloud.githubusercontent.com/assets/15685960/14144632/27b0fe70-f699-11e5-9295-3d1af729efe1.png)

**Comment by vcarciu** [comment]
Same issue reproducible in reviews section : http://screencast.com/t/bKQfZZJIr2ss

**Comment by muffinresearch** [comment]
> Same issue reproducible in reviews section : http://screencast.com/t/bKQfZZJIr2ss

Yep the patch solves that too.

**Comment by vcarciu** [comment]
Verified as fixed in all sections described above : http://screencast.com/t/czrM50Vb , http://screencast.com/t/fKTbOrbkLt3Z , http://screencast.com/t/hClsS4VzZj
