### ISSUE TITLE
Drop tests for django 3.2

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20618]
A test matrix to run all the tests with both django 4.2 and django 3.2 was added with https://github.com/mozilla/addons-server/issues/20493.  Once we've deployed django 4.2 to prod and everything seems okay we can drop the testing on django 3.2.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-332
