### ISSUE TITLE
Categories are all in bold on the theme details submission page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20626]
### Describe the problem and steps to reproduce it:
1. Submit a new listed theme
2. Once you reach the details submission page, notice the category selection section

### What happened?
All category names are bolded

### What did you expect to happen?
Category names should not be bolded 

### Anything else we should know?
Likely a regression from https://github.com/mozilla/addons-server/issues/20493
Doesn't seem to be an issue for extension details.

[dev]
![image](https://user-images.githubusercontent.com/31961530/234861766-1e3cc454-3a7e-4a5b-b28e-167d363a5dfa.png)

[stage]
![image](https://user-images.githubusercontent.com/31961530/234861809-46601ee3-d36c-4feb-96aa-8a1c922a39b8.png)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Now on -dev:

![AMOdev](https://github.com/mozilla/addons-server/assets/33448286/f2aa777f-b32a-4c02-9278-575ee46aaf3d)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-335
