### ISSUE TITLE
Reduce the visible depth of the manual review Queue

### ISSUE THREAD

**Issue by kplotnik** [mozilla/addons-server#20622]
### Describe the problem and steps to reproduce it:
The current manual review queue displays all extensions that have a due date including those that have a due date in several days.

### What did you expect to happen?
In order to reduce the mental overload of the reviewers we would like to restrict the number of extensions visible to the reviewer and display only those that are due for the review within next two business days. The total number of extensions should be displayed properly.

**Comment by eviljeff** [comment]
in #20641 config key `upcoming-due-date-cut-off-days` can be defined in the admin tools to override the default of 2 business days.

**Comment by ioanarusiczki** [comment]
@eviljeff I added in models/zadmin/config/ the config key you mention, then I added a value in days, also tries in seconds but the Manual Review Queue's content did not change. I tried this with an admin account. 

Could you add some details about this implementation please?

**Comment by eviljeff** [comment]
> @eviljeff I added in models/zadmin/config/ the config key you mention, then I added a value in days, also tries in seconds but the Manual Review Queue's content did not change. I tried this with an admin account.
> 
> Could you add some details about this implementation please?

Ah, there is a permission, `Addons:AllDueDates`, that overrides this change - if you are full admin `*:*` on dev you have the permission.  An account without `*:*` (or `Addons:*`) should be used for testing it.

**Comment by ioanarusiczki** [comment]
@eviljeff I deleted the configs on -dev and -stage

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tried with `1`, `2`, or even `3` working days as value and the add-ons are displayed according to the value set (made some submissions on dev to see what happens when I have in the queue versions with 1, 2 and 3 business days due dates)

On -dev and -stage there's plenty of versions with the due date expired -> with day or hours "ago" -> these are always displayed. -> probably the expected result

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-334
