### ISSUE TITLE
"Not available for Firefox" text is not corectly aligned inside a collection

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2062]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Find a collection containing incompatible addons(https://addons.allizom.org/en-US/firefox/collections/enkei/enkei/)
2.Observe the "Not available for Firexfox X" text

Expected results:
Text is correctly aligned

Actual results:
Text overlaps the addon frame

Please see screencast for this bug: http://screencast.com/t/T7JcTrQyRC
Reproducible on Stage and -dev

**Comment by ValentinaPC** [comment]
The size of the "Works with ...." field, is also a bit too long.
Please see the screenshot: 
![2016-03-30_1723](https://cloud.githubusercontent.com/assets/15685960/14145548/f6a5453a-f69c-11e5-8bc1-7c8a26109deb.png)

**Comment by tofumatt** [comment]
That field isn't actually too long, but in fact there's a white link in it. I'll have a fix in a few!

**Comment by vcarciu** [comment]
Original scenario is fixed : http://screencast.com/t/4EbGbHREYZ4  , the link is now displayed, but it is not working. 
For a better tracking I will close this one and open a new issue for the link bug.
