### ISSUE TITLE
"Dictionaries & Encyclopedias" link from Search Tools page has a small layout issue

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2063]
**Reproducible on Windows only.**

Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/
2. Go to More...->Search Tools
3. Click on the "Dictionaries & Encyclopedias" link: https://addons.allizom.org/en-US/firefox/search-tools/dictionaries-encyclopedias

Expected results:
There are no display or layout issues.

Actual results:
The name overlaps the arrow.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![2016-03-30_1633](https://cloud.githubusercontent.com/assets/15685960/14145141/5e3a47a6-f69b-11e5-8936-70a1091833a5.png)

**Comment by muffinresearch** [comment]
Looks to be fixed: see https://addons-dev.allizom.org/en-US/firefox/search-tools/dictionaries-encyclopedias

<img width="184" alt="dictionaries___encyclopedias____search_tools____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14176773/a628369a-f74a-11e5-8f4b-85a2a20883fb.png">

**Comment by ValentinaPC** [comment]
I am still reproducing this on AMO-dev FF45(Win 7).
I see your "screen" for other languages (i.e French)
Please see the screencast: http://screencast.com/t/eCONC7dnmBly
Reopening.

**Comment by muffinresearch** [comment]
Ah ok - yes I see it on windows only.

**Comment by ValentinaPC** [comment]
Sorry to insist for such a small thing :)
Now looks like at comment 0 when hovering over.
Please see: 
![2016-04-01_1005](https://cloud.githubusercontent.com/assets/15685960/14200126/6c5c1bf0-f7f1-11e5-9ae8-9aaffb339a25.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshots:
![2016-04-05_1055](https://cloud.githubusercontent.com/assets/15685960/14274950/003ac3f2-fb1d-11e5-8ea3-aaeb93193a37.png)
![2016-04-05_1055_001](https://cloud.githubusercontent.com/assets/15685960/14274956/050a251c-fb1d-11e5-9668-3117fa74786d.png)
