### ISSUE TITLE
Stop doing phrase matching for single-term queries in search

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20635]
When searching, we currently perform 4 kind of full text search against add-on names:
- a `MatchPhrase`
- a `Match`
- a `MatchPrefix`
- a `FuzzyMatch` (combined with a `trigrams` search, whichever returns the highest score)

The `MatchPhrase` seems to be performing poorly in some cases, being a little too lenient, allowing matches that are not very relevant. This is particularly noticeable for single-term queries, and this is also where a `MatchPhrase` makes the least sense anyway, the other matches should be enough in that case, so let's stop doing it when there is whitespace in the search query.

**Comment by ioanarusiczki** [comment]
@diox While making a query , I left spaces before, between or after the name but the autocomplete returns the name.

Is there anything else I should check ?

**Comment by diox** [comment]
Sorry, it needed a reindex to fully be fixed. That is now done. Please try multiple search queries on dev and look at the results, seeing how relevant they are (and if you think some add-ons are missing).

 When the search query is a single word, we should return fewer results than before, but they should be more relevant.

**Comment by ioanarusiczki** [comment]
@diox Looks good to me, on -dev and -stage FF112(Win10)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-337
