### ISSUE TITLE
replace flake8 & plugins with ruff

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20643]
https://github.com/charliermarsh/ruff is a rust based python linter that's much faster than flake8.  We should switch to it for the speeds.

**Comment by eviljeff** [comment]
> FYI we use flake8-mutable (avoid mutable arguments) and flake8-quotes (enforce single quotes)
  
>  ruff implements flake8-quotes natively; flake8-mutable seems to be largely abandoned and has it's functionality is implemented in another extension called [flake8-bugbear](https://pypi.org/project/flake8-bugbear/), which is reimplemented by ruff.

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if you need testing.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-340
