### ISSUE TITLE
Pseudo buttons have an underline.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2065]
They are links but since they're styled to look like buttons they shouldn't have an underline or the buttons styling should be removed.

<img alt="meet_the_foxyproxy_standard_developer____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14146080/47601cf2-f68e-11e5-8ffb-e0105cad38a1.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-01_1020](https://cloud.githubusercontent.com/assets/15685960/14200422/81da72b8-f7f3-11e5-9cda-c7e94a786383.png)
