### ISSUE TITLE
Addons can't be installed  on AMO -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20665]
### Prerequisites: 
The following prefs should be set in Firefox Nightly or unbranded to allow installations on -dev:
- `extensions.webapi.testing -  true`
- `xpinstall.signatures.dev-root - true`

### Describe the problem and steps to reproduce it:
1. Open an addon detail page - https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/
2. Install the addon

### What happened?
Installation fails with the "Download failed. Please check your connection." error
![image](https://github.com/mozilla/addons-server/assets/31961530/a8131c8a-2e52-4c24-b6f0-935555a52695)

### What did you expect to happen?
Addons can be installed

### Anything else we should know?
- if I'm opening the [.xpi](https://addons-dev.allizom.org/firefox/downloads/file/414655/awesome_screenshot_plus-10.226.xpi) file directly, I receive a 404 from nginx

@diox could this regression be caused by https://mozilla-hub.atlassian.net/browse/SVCSE-1212?

**Comment by AlexandraMoga** [comment]
Add-ons can be installed now, so I'll close the issue and mark it s verified.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-343
