### ISSUE TITLE
Add-ons can't be uploaded on -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20669]
### Describe the problem and steps to reproduce it:
1. Upload an addon on -dev
2. Verify the validation results

### What happened?
Validation fails with a "Sorry we couldn't load your Webextension" error
![image](https://github.com/mozilla/addons-server/assets/31961530/1cc8b749-6928-4a6e-adaf-3a8cb8026e23)

### What did you expect to happen?
Addons can be uploaded

### Anything else we should know?
- the issue started to be noticed today, so I'm wondering whether https://mozilla-hub.atlassian.net/browse/SVCSE-1212 has an impact here

**Comment by diox** [comment]
Looks related, yes. That's probably https://mozilla.sentry.io/issues/4168431784/?project=6224627&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=8

**Comment by AlexandraMoga** [comment]
I can't reproduce this issue anymore, so I'm going to mark it as verified fixed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-346
