### ISSUE TITLE
500 server error on the Manual Review Queue with an Admin Reviewer on AMO Dev 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20672]
While trying to test for https://github.com/mozilla/addons-server/issues/20622 I've noticed a 500 error when I tried to access the Manual Review Queue with an Admin:Reviewer account with the following permissions: 
Addons:Review,Reviews:Admin,Admin:Tools,Addons:TriageDelayed

![500 server error](https://github.com/mozilla/addons-server/assets/33448286/c3442301-443c-473f-8053-2c66b9c8b273)

I could not reproduce it on AMO stage. 

On AMO dev it is reproducible with 2 different reviewer accounts.

**Comment by eviljeff** [comment]
From https://mozilla.sentry.io/issues/4171847081/ I think you've set `UPCOMING_DUE_DATE_CUT_OFF_DAYS_CONFIG_KEY` to a string rather than an integer (and from the looks of it, a really really large number of days)

**Comment by ioanarusiczki** [comment]
@eviljeff This is how the [value](https://addons-internal.dev.mozaws.net/en-US/admin/models/zadmin/config/upcoming-due-date-cut-off-days/change/) is set right now and I have a 500 on both dev and stage. 

I set '2' on -stage.

**Comment by ioanarusiczki** [comment]
@eviljeff P.S. -> the Addons:AllDueDates added into the group seems to be working. Then I have access to the entire Manual Review Queue. But when I remove it from permissions then I'm getting the server error.

**Comment by eviljeff** [comment]
oh ... the config value is always a string, so I need to parse it into an int

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified -dev and -stage - the error is no longer reproducible.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-349
