### ISSUE TITLE
Auto-approvals/Manual approvals are working inconsistently on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20679]
Issue was mentioned on slack before but since it is becoming a long standing problem we're tracking it here as well

### Describe the problem and steps to reproduce it:
1. Upload a new unlisted addon (or a new listed version for an already approved addon) on stage
2. Wait for the addon to be auto-approved

### What happened?
The auto-approval runs with a delay. Normally, it would take ~5 mins at most for an addon to be auto-approved.

### What did you expect to happen?
Addons are auto-approved in the expected amount of time.

### Anything else we should know?
On stage, manual approvals from Reviewer Tools are also broken. I've tried to manually approve a few addons and ran into 504 errors.  Trying to manually approve a theme will lead to these timeouts most of the time.

**Comment by diox** [comment]
We're getting 504 errors from autograph https://mozilla.sentry.io/issues/4131545558/?project=6237717&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Comment by AlexandraMoga** [comment]
Both manual approvals and auto-approvals have been working today. I'll close this issue as verified and will re-open if the issue occurs again.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-350
