### ISSUE TITLE
Notable addons shouldn't be able to be added as Primary hero

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20682]
Followup for https://github.com/mozilla/addons-server/issues/19976#issuecomment-1339016579

Some changes are expected on the UX because:

Notable addons on the primary hero shelf appear as "Sponsored" and the URL "What is this"  going to https://support.mozilla.org/en-US/kb/add-on-badges -> where recommended and By Firefox labels are explained

An example:
![an example](https://user-images.githubusercontent.com/33448286/205870924-f01eec48-ce1a-4697-b0f3-d3ed95b50948.png)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I could still add a Notable add-on to Primary Hero on -dev

![Notable](https://github.com/mozilla/addons-server/assets/33448286/0666e87b-32e5-4eee-bf8e-e43941b2aa84)

**Comment by eviljeff** [comment]
@ioanarusiczki can you show me the admin?

**Comment by ioanarusiczki** [comment]
@eviljeff [The admin page](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/409/change/?_changelist_filters=group_id__exact%3D7)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Re-checked on -dev and -stage and I've noticed the following:

- with enabled checked, the error message is displayed

![enable](https://github.com/mozilla/addons-server/assets/33448286/f086086d-c87c-4d89-9c42-fc3f492b39a1)

- when "Is external" and "Enabled" are both checked, I can save the changes 

![saving notable](https://github.com/mozilla/addons-server/assets/33448286/08026572-69d6-443a-88ca-a823e4e462a0)

So I see on AMO stage the Notable displayed. But it could be the expected result. 

![Notable](https://github.com/mozilla/addons-server/assets/33448286/2d86195a-cac2-41d9-8bb9-9eb3322ab02e)

**Comment by eviljeff** [comment]
External promoted add-ons is a bit of an edge case (that I don't think was ever actually used) but if the normal case (is external = False) works then it's good.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-351
