### ISSUE TITLE
提交新附加组件时提示“发现重复的附加组件ID”

### ISSUE THREAD

**Issue by xyk953651094** [mozilla/addons-server#20685]
### Describe the problem and steps to reproduce it:
当我试图上传一个新的附加组件时，提示“发现重复的附加组件ID”，然而我并没有发现我的账号下有哪个附加组件的 ID 与我新提交的附加组件的 ID 重复。
When I try to upload a new add-on, it says "Duplicate add-on ID found", but I don't find any add-on ID under my account that is the same as the ID of my newly submitted add-on.

### What happened?
当我试图上传一个新的附加组件时，提示“发现重复的附加组件ID”，然而我并没有发现我的账号下有哪个附加组件的 ID 与我新提交的附加组件的 ID 重复。
When I try to upload a new add-on, it says "Duplicate add-on ID found", but I don't find any add-on ID under my account that is the same as the ID of my newly submitted add-on.

### What did you expect to happen?
我的附加组件能够成功上传。
My new add-on was able to upload successfully.

### Anything else we should know?
![](https://user-images.githubusercontent.com/28004442/235841579-f0b91275-5fc3-4f0a-ad63-d59f1b11a855.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-352)

**Comment by willdurand** [comment]
Given the error message ("duplicate ID"), this is a server bug.

**Comment by willdurand** [comment]
Given the error message ("duplicate ID"), this is a server bug.

**Comment by xyk953651094** [comment]
> Given the error message ("duplicate ID"), this is a server bug.

I also think it might be a server bug. 
I uploaded a plugin before, but I got stuck on the submission page. I thought the upload was not successful, but then I found that there was a strange upload record on the developer homepage, so I deleted the add-on. Then this error was reported when I trying to upload a new add-on with the same id.

**Comment by diox** [comment]
If you already uploaded an add-on with an id, and it went far enough that you could see it on the developer homepage, then it was created in the database. From that point the add-on ID is not reusable (you should have seen a warning about it when you deleted the add-on).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-352
