### ISSUE TITLE
Replace `needs_human_review` field by `NeedsHumanReview` model

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20699]
https://github.com/mozilla/addons-server/issues/20687 introduced a new model to record the reason why something was needing human review. We can go one step further, and have a boolean field indicating if that need human review is still active or not, and make sure to clear all existing instances when a reviewer reviews the version, completely replacing the old `needs_human_review` field on `Version`.

This should be almost completely transparent to reviewers. In #20687 we already recorded an activity log, this should now be done for every "source" of needs human review flag (though they don't necessarily explicitly see when it's dropped in every case - some of them are implicit, like approval/rejection of a version). In addition, because it's a bit redundant the needs human review flag is no longer displayed in the review queue (the googly eyes icon).

**Comment by ioanarusiczki** [comment]
@diox 

- while I verified https://github.com/mozilla/addons-server/issues/20687#issuecomment-1557284516 I've tested with reviewer actions -> "is active" is behaving as expected. 

- the googly eyes are no longer displayed in the Manual Review Queue

- there's a model under Reviewers in admin `admin/models/reviewers/needshumanreview/` -> it's a list of versions flagged for human review

- versions model in admin have a new Needs Human Reviews section where a history of reasons are registered. It also indicated whether the flag is active or not. 
+ The add another Needs human review -> is not functional , adding an unknown reason then saving is not registered 
![last row](https://github.com/mozilla/addons-server/assets/33448286/1029021a-939b-4fc3-a018-bfde60883587)

**Comment by diox** [comment]
> The add another Needs human review -> is not functional , adding an unknown reason then saving is not registered

That is a problem we'll want to solve before the push.

**Comment by ioanarusiczki** [comment]
@diox 

I could add a reason and save it from [admin](https://addons-internal.stage.mozaws.net/en-US/admin/models/versions/version/2477783/change/) and now it's having effect on the version -> will be available again in the Manual Review Queue

The action from admin is registered with Reason "Unknown".  Clear Needs Human Review from reviewer's page un-checks "Is Active" -> expected

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-355
