### ISSUE TITLE
Load and show per-version ADU inline in the review page versions block

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20701]
part of https://mozilla-hub.atlassian.net/browse/AMO-70 ; depends on https://github.com/mozilla/addons-server/issues/20700

**Comment by ioanarusiczki** [comment]
@eviljeff 
With Firefox Color from -dev 

![top10](https://github.com/mozilla/addons-server/assets/33448286/478f2486-889a-43c8-b3d2-77aa0e3564c0)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-357
