### ISSUE TITLE
A white padding is displayed in View Listing page of an unreviewed theme

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2070]
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/
2. Submit a new theme, _don't approve it_
3. Load its "View Listing" page 

Expected results:
The page has no layout issues.

Actual results:
A white padding is displayed above its buttons.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![2016-03-30_1753](https://cloud.githubusercontent.com/assets/15685960/14147402/fd564080-f6a3-11e5-8b87-2a706caf0e10.png)

**Comment by muffinresearch** [comment]
For reference this was the old style:

<img width="438" alt="its-a-test____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14171356/6aca963a-f72a-11e5-9721-2403bc8cad5e.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-03-31_1724](https://cloud.githubusercontent.com/assets/15685960/14178915/956ded3e-f765-11e5-800b-c78cc571d54c.png)
