### ISSUE TITLE
Store a mapping of AMO add-ons and extension IDs from other browsers

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#20708]
For instance, if an add-on is published on both AMO and the Chrome Store, we'd like to have that stored in the AMO database. But not necessarily for all add-ons, only for some add-ons and only AMO admins should be able to edit this mapping for now.

(we'll need to think about admin permissions later, potentially)

**Comment by AlexandraMoga** [comment]
The new tool is located at https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/addonbrowsermapping/
I can add and delete an addon browser mapping  through the new tool with an admin account.

I'm marking this issue as verified fixed on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-359
