### ISSUE TITLE
Flag "hot" add-ons according to their review tier 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20713]
Add-ons with a high usage growth should be flagged for human review (using the new mechanism from https://github.com/mozilla/addons-server/issues/20699 and https://github.com/mozilla/addons-server/issues/20687).

Different usage tiers should have different growth thresholds recorded in the database in a model that admins can use.

Parent project doc: https://docs.google.com/document/d/16SoRHckWpDQ2LKL991CdBXNJ6CFHDPnkNY-OMN2jftk/edit#

**Comment by ioanarusiczki** [comment]
@diox 

On -dev I set up two tiers 
[Tier number one ](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/usagetier/1/change/)
[Tier number two ](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/usagetier/2/change/)
Growth threshold before flagging:10

Someone set `extra-review-target-per-day` to 10 I left it 10. 

On -stage I set up:
[Tier nr.1](https://addons-internal.stage.mozaws.net/en-US/admin/models/reviewers/usagetier/1/change/)
[Tier nr.2](https://addons-internal.stage.mozaws.net/en-US/admin/models/reviewers/usagetier/2/change/)

Growth threshold before flagging: 10

I deleted `extra-review-target-per-day` config so it should default to 8

I'm not sure if the 10% growth threshold  is alright but I must use a value so I chose that, I could decrease it , don't know yet.
Also I am not sure what extra-review-target-per-day does, I assume 10 is a number of days, so after the versions are flagged this is distributed between them, I guess I'll see after the cron runs, can you trigger it please? 

I see on -dev right now in the manual review queue 34 pages of versions, and 22 pages on -stage, checking the reason -> must be from the cron that ran this morning. models/reviewers/needshumanreview/ registered on May 24, 2023, 6:37 a.m. versions with "Over growth treshold for usage tier" reason.

**Comment by diox** [comment]
`extra-review-target-per-day` is the maximum number of add-ons the task will assign for review per day. So if it would flag 20 add-ons, and it was set to 10, it would set the `due_date` for up to 10 of them today (might be less depending on when it starts during the day - it would spreads them out 24 hours / 10 = 2.4 hours apart, starting from when the task ran), and then 10 more tomorrow and so on until all have a due date

**Comment by diox** [comment]
I just realized the growth isn't show in the admin, and I'm not sure it's computed correctly on dev anyway, which doesn't help. I'll look into that.

**Comment by diox** [comment]
> On dev & stage, the only "hot" add-ons right now are langpacks, which means nothing would ever flagged there without manually altering the hotness and triggering the task.

@ioanarusiczki so a workaround for this is going to be:
- Select the extensions with stats on dev/stage you want to test with (should be any that exist with [those guids](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/amo_dev/amo_stats_dau_v2/query.sql#L15-L25)). Make sure to only pick extensions, and also check the average daily users value, as they need more than 100 users to be considered.
- Add them to `FrozenAddon` through the admin. That will ensure the cron to compute the growth value (`hotness`) won't touch them.
- Select the growth you want to test with for the given tier(s) for each add-on. Let me know the value and I'll manually set it in the database for each (make sure not to modify `FrozenAddon` in the admin again for those add-ons, as doing so resets the growth value to 0)
- We can then let the cron fire as normal

We can repeat that process for any number of extensions provided they would match the criteria of a minimum of 100 users.

**Comment by ioanarusiczki** [comment]
@diox 

Frozen addons on [dev ](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/frozenaddon/) and [stage ](https://addons-internal.stage.mozaws.net/en-US/admin/models/addons/frozenaddon/) -> same guids 

These are also part of the notable group (at least some, otherwise they're recommended etc) 

[Tiers on dev ](https://addons-internal.dev.mozaws.net/en-US/admin/models/reviewers/usagetier/)
[Tiers on stage ](https://addons-internal.stage.mozaws.net/en-US/admin/models/reviewers/usagetier/)

I added a third tier because there's a guid with an ADU of 1091325 but I'm not sure what the growth value should be, something low a 2 or 3 % maybe? I left in the admin a 10

**Comment by diox** [comment]
> These are also part of the notable group (at least some, otherwise they're recommended etc)

We'll need to remove them before testing (and avoid the task that would re-add them to notable, perhaps by tweaking the threshold) because the task will only flag signed versions that haven't already been reviewed by a human and aren't already flagged for another reason (such as being the last signed version when the add-on became notable).

**Comment by ioanarusiczki** [comment]
@diox 

Test results

1. AMO dev

The versions below have been removed from promoted groups, new versions submitted which got auto-approved
3 Tiers were set on AMO dev with lower and upper ADU threshold. Growth threshold set at 10%, 5% and 1 %

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/616918 -> hotness 0.15, with 10% threshold
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/495710 -> below growth and wasn't flagged with hotness 0.04 , threshold 5%
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/620017-> hotness 0.06, threshold 5%
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/617049 -> hotness 0.05 , threshold 5%
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/620153-> 0.011, threshold 1%
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/495646 -> hotness 0.01, threshold 1%
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/495646-> hotness 0.01, threshold 1%

After the cron task was complete, checking the review pages -> versions got "Over growth treshold for usage tier" reason except for 495710 which was expected
The Manual Review Queue displayed all the versions except for 495710 with due dates of 3 working days. extra-review-target-per-day was set at 10 and I've checked the queue with an admin user

2. AMO stage 

Hotness for all the versions below set above the threshold except for 1004833

https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1004834, 10% threshold,tier 1https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1004833, 5% threshold, tier 1 -> did not get the flag
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1004682, 5% threshold, tier 2
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1004832, 5% threshold, tier 2

extra-review-target-per-day set to 2

All 3 versions with "Over growth treshold for usage tier" flag are available in the Manual Review queue and have a due date.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-361
