### ISSUE TITLE
Banner for the notable extensions

### ISSUE THREAD

**Issue by kplotnik** [mozilla/addons-server#20714]
We want to show the standard banner to the notable extension group, with the text predefined and set by the operations team. The banner can be displayed permanently till the campaign is over (current estimate 4-6 weeks)

**Comment by diox** [comment]
The banner will use the same spot as the `submit_notification_warning` banner that we already have, but be limited to being displayed for new versions of a notable add-on.

Content will come from the database through a `Config` object like the regular submission warning banner, but with a different key (probably `submit_notification_warning_notable`).

**Comment by diox** [comment]
Yeah, that's expected/on purpose, didn't want to show both at once and I figured the `submit_notification_warning` one was the most important to show, so if it's set it will take precedence.

**Comment by AlexandraMoga** [comment]
Ok, so we don't want/need to show any  banner for regular addons then?

**Comment by diox** [comment]
- If `submit_notification_warning`: show it to everyone, both at add-on and version upload (actually even at channel selection during submission), don't show anything else
- If `submit_notification_warning` is not set, but `submit_notification_warning_pre_review` is set: show it on version upload of add-ons belonging to a group that does human review for the corresponding channel (for notable, it'd be both channels - for recommended, only listed)

**Comment by AlexandraMoga** [comment]
These are my final results:

- with `submit_notification_warning` : the banner is displayed both on the distribution and version upload pages, for all new addon or new version submissions (including the theme submission wizard)
[new addon]
![image](https://github.com/mozilla/addons-server/assets/31961530/81eeb95d-f0b2-479f-ba25-10fe943cfeeb)
[new version]
![image](https://github.com/mozilla/addons-server/assets/31961530/d27953fa-09b3-4ab7-9906-a8d3b97e48d4)

- with both `submit_notification_warning` and `submit_notification_warning_pre_review `: same as above (i.e. `submit_notification_warning` takes precedence)
- with `submit_notification_warning_pre_review ` only: 
  - regular addons: no banner is displayed for new addon or new version uploads
  - notable addons - pre review banner is displayed on the version upload page for both listed and unlisted distribution channels; the banner will not be displayed on the channel selection page in this case
  ![image](https://github.com/mozilla/addons-server/assets/31961530/c01bb638-059d-4154-8620-660fd61938ae)

  - recommended and by Firefox addons: pre review banner is displayed on the version upload page for new _listed_ versions only; the banner will not be displayed on the channel selection page in this case  
![image](https://github.com/mozilla/addons-server/assets/31961530/ea9ed813-e588-4ac5-93cc-60c766d65910)

- without any submission warning config: no banner is displayed for new addon or new version uploads for any addon type

I'm marking this issue as verified fixed on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-362
