### ISSUE TITLE
Text is overlapping other elements in add-on review detail page.

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2072]
**Steps to reproduce:**
1. Open editor tools: https://addons.allizom.org/en-US/editors/queue/nominated?sort=waiting_time_min
2. Open any add-on review page and scroll down (i.e: https://addons.allizom.org/en-US/editors/review/03302016test04)

**Expected results:**
There are no layout or display issues.

**Actual results:**
Text is overlapping other elements in add-on review detail page.

**Notes/Issues:**
Verified in FF45(Win7) issue can be reproduced in -dev and stage
Screencast for this issue: http://screencast.com/t/6WgcaRmPe

**Comment by muffinresearch** [comment]
Andreas had a branch with some fixes for editor-tools. I didn't get around to trying it but it's here https://github.com/mozilla/addons-server/pull/2085

**Comment by madalincm** [comment]
Is that fix in -dev?  My issue is no longer reproducing:  http://screencast.com/t/s1hKT2bA

**Comment by muffinresearch** [comment]
Yep should have been fixed already.

**Comment by vcarciu** [comment]
Marking as verified...
