### ISSUE TITLE
add cache to `usage_per_version` view?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20739]
It makes a bigquery request which is slow, and has upstream resource/cost implications, but we also want up-to-date numbers.  A compromise of a short cache time is probably sensible.

**Comment by eviljeff** [comment]
A cache of 5 minutes was accidentally added in https://github.com/mozilla/addons-server/commit/f774e37b89cdd63c9b4fe937eb9ac1c9fcb22c3a#diff-5533483b8cb53adb9e0894ed4b1ba08dc4c49eddb736e37980405951d015f066R1520

If 5 minutes is a good enough cache time I guess this is done?

**Comment by diox** [comment]
We can try this - the only thing we want to make sure is that we don't accidentally make the data publicly available because of caching.

**Comment by AlexandraMoga** [comment]
@eviljeff is this caching affecting the `/reviewers/usage_per_version/<addon-id>` page or something else?

**Comment by eviljeff** [comment]
> @eviljeff is this caching affecting the `/reviewers/usage_per_version/<addon-id>` page or something else?

yes, and the reviewers review page that calls it via an XHR.  The most obvious way to test it would be to check the response time - the first request will be slow (and so the ADU numbers will take a while to update); a subsequent review page load (or navigating to a sub-page for an add-on with paginated version history) should have a quicker ADU update.

**Comment by ioanarusiczki** [comment]
@eviljeff I can confirm that before the top 10 ADU was loading slow. 
It's not the case now. I verified  this on -dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-369
