### ISSUE TITLE
Link top 10 version ADU to other review pages

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20732]
In https://github.com/mozilla/addons-server/issues/20702 a block was added to the review page to show the top 10 versions by ADU.  But the underlying bigquery doesn't know anything about the versions, only version strings, and we just return it to the client side JS.  So the js doesn't have a way to know if a version string in the top 10 versions that isn't on the page is in another channel or on a different page. 

We need to add to the response so the js is able to match up every adu result with the channel and/or which page it would be shown on when paginated.

**Comment by diox** [comment]
Maybe we could have an intermediary redirect instead of modifying the response ?

**Comment by eviljeff** [comment]
> Maybe we could have an intermediary redirect instead of modifying the response ?

we could, if that's better for reviewers.

Otherwise, the updated view would look like:
```python
def usage_per_version(request, addon):
    def list_index(lst, value):
        try:
            return lst.index(value)
        except ValueError:
            return None

    versions_avg = get_average_daily_users_per_version_from_bigquery(addon)
    out = {version: {'adu': numberfmt(adu)} for (version, adu) in versions_avg}

    # Now add some extra metadata for the top 10, to work out which page they'd be on.
    addon_versions = list(
        addon.versions(manager='unfiltered_for_relations').values_list(
            'version', 'channel'
        )
    )
    listed_versions = [
        ver for ver, channel in addon_versions if channel == amo.CHANNEL_LISTED
    ]
    unlisted_versions = [
        ver for ver, channel in addon_versions if channel == amo.CHANNEL_UNLISTED
    ]
    for version, _ in versions_avg[0:10]:
        if (index := list_index(listed_versions, version)) is not None:
            out[version] = {**out[version], 'index': index, 'channel': 'listed'}
        elif (index := list_index(unlisted_versions, version)) is not None:
            out[version] = {**out[version], 'index': index, 'channel': 'unlisted'}

    return JsonResponse(out)
```
(or maybe return the page rather than the index, not sure yet)

**Comment by diox** [comment]
Yeah I guess it depends on how common this would be. Having to fetch all versions ahead of time is annoying (*), but hopefully it's not too slow...

(*) Someday we may want to rethink how we do pagination to avoid this...

**Comment by eviljeff** [comment]
after discussion on chat, we will go with an intermediary redirect view

**Comment by ioanarusiczki** [comment]
@eviljeff 

Most of the versions when clicked on -dev will return a 400 because the version numbers from Top 10 Version ADU don't exist here but I managed to test the 2 scenarios:

1. When going on a different page: 

![another page](https://github.com/mozilla/addons-server/assets/33448286/0f4f79ce-226c-4db1-9c2a-16a7521ede50)

2. When going from a listed review page to the unlisted review page:

![another channel](https://github.com/mozilla/addons-server/assets/33448286/19fa3bb3-8259-4b0f-a4d3-18200511acc2)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-367
