### ISSUE TITLE
admin (secondary hero shelves) have broken icon selection tool

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#20761]
I went into admin today to update AMO homepage programming and noticed the UI to select icons is goofed up for two of the three modules (see screenshot). 

![admin_secondary_hero_bug](https://github.com/mozilla/addons-server/assets/8496249/78e8fb58-5800-493a-a2e6-8f4142832650)

**Comment by devaneymoz** [comment]
@eviljeff any sense when this might get resolved?

**Comment by eviljeff** [comment]
> @eviljeff any sense when this might get resolved?

we should be able to get it done for the next release

**Comment by ioanarusiczki** [comment]
@eviljeff 

[Secondaryheroshelf](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/secondaryheroshelf/23/change/)
looks good to me on AMO dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-375
