### ISSUE TITLE
Inconsistency in rating sort & filter query parameters

### ISSUE THREAD

**Issue by ziir** [mozilla/addons-server#20763]
### Describe the problem and steps to reproduce it:

On the [`/api/v5/addons/search`](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v5-addons-search-) API endpoint, one can filter & sort add-ons by rating.
For example, a query used for searching add-ons with an average rating of 4 and sorting the results by rating would like this:
- `/api/v5/addons/search/?ratings__gte=4&sort=rating`

### What happened?

The query parameters for filtering & sorting add-ons by ratings aren't named consistently which can be confusing & error-prone, especially since, in the endpoint documentation, sort parameters & threshold style filter parameters are presented next to each other.

<details>
<summary>View docs screenshot</summary>

![Screenshot from 2023-05-27 23-53-47](https://github.com/mozilla/addons-server/assets/2394128/c1f1c744-af64-4284-8c9d-111fa12d5869)

</details>

### What did you expect to happen?

The ratings related object property & sort/filter query parameters should be named consistently.

### Anything else we should know?

`ratings` being the property actually returned in the [addon details object](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-object), it might be preferable to:
- support the `sort=ratings` query parameter.
- keep the `sort=rating` query parameter as an alias.
- update documentation to mention only `sort=ratings` query parameter for consistency / DX.
- make the "sorting parameters" & "threshold style filtering parameters" sections in the endpoint documentation stand out more from each other.

Additionally, glancing at [src/olympa/search/filters.py](https://github.com/mozilla/addons-server/blob/5d36354b061a79a1762592fd137051b3fe9e5d5f/src/olympia/search/filters.py#L979), it appears the filtering & sorting logic currently do not leverage the same ratings field: the `ratings` filter relies on the `ratings.average` field, whereas the `rating` sort relies on `bayesian_rating`, which might or might not be intentional, may lead to odd behavior.

**Comment by diox** [comment]
> Additionally, glancing at [src/olympa/search/filters.py](https://github.com/mozilla/addons-server/blob/5d36354b061a79a1762592fd137051b3fe9e5d5f/src/olympia/search/filters.py#L979), it appears the filtering & sorting logic currently do not leverage the same ratings field: the `ratings` filter relies on the `ratings.average` field, whereas the `rating` sort relies on `bayesian_rating`, which might or might not be intentional, may lead to odd behavior.

This is somewhat confusing if someone ends up comparing the 2 fields values yes, but this was done on purpose... 15 years ago. The idea is to solve the classic issue with ratings sort of something with a single 5 star rating being ranked before a super popular 4.9 one. To combat this problem, we use a bayesian rating to weigh the rating (See https://web.archive.org/web/20060423210706/http://www.thebroth.com/blog/118/bayesian-rating).

Only sorting is affected though, for filtering and displaying purposes we show the actual average, mostly out of concern that some users would do the math themselves and be confused that it's not a straight average.

We could revisit all of that, but that is a product decision to make, not an engineering call.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-377
