### ISSUE TITLE
Remove support for `ES_HOSTS` environement variable

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20778]
`ES_HOSTS` will be replaced by `ELASTICSEARCH_LOCATION` in https://github.com/mozilla/addons-server/pull/20752. The will code still supports the old variable for backwards-compatibility, but once this has landed **and** SRE has modified the environnements to use the new variable we should remove that compatibility fallback.

See also https://mozilla-hub.atlassian.net/browse/SVCSE-1319

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-383)

**Comment by eviljeff** [comment]
QA: check search still works

**Comment by alexandruschek** [comment]
Hello,

I tested the search manually and also ran the automated tests, all looks ok.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-383
