### ISSUE TITLE
Remove ability to change add-on compatibility inline from devhub dashboard

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20775]
Devhub allows you to modify add-on compatibility in 2 places:

- In the `Manage My Submissions` > `My Addons` dashboard, inline for each add-on, but only if they have `strict_compatibility` set and are listed
- In the version edit page for each add-on

`strict_compatibility` should only be set for langpacks, and we don't really want to let anyone alter langpacks compatibility in devhub, so let's get rid of the first option.

(Eventually the second option will go away too for langpacks in https://github.com/mozilla/addons-server/issues/20531 since their compatibility is set in the manifest)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-382
