### ISSUE TITLE
The error message is not displayed when both applications are unchecked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20771]
Followup for https://github.com/mozilla/addons-server/issues/20532

1. Submit an extension
2. Do not check any of the applications and click Continue

Expected result:
An error message should be displayed

Actual result: 
The upload process must be repeated

Now on -dev
![unchecked apps](https://github.com/mozilla/addons-server/assets/33448286/8aff4a1f-82d1-43a1-b816-df4eef7f1f22)

On -stage:

![error message stage](https://github.com/mozilla/addons-server/assets/33448286/78fb2372-400d-4eb9-9d83-25b043491f5f)

**Comment by diox** [comment]
Note that this error has always been kinda clunky - you can't continue from here, you have to restart the submission process anyway.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-379
