### ISSUE TITLE
Don't add a due date for unlisted delayed in some cases

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20773]
### Describe the problem and steps to reproduce it:

`INITIAL_DELAY_FOR_UNLISTED` controls the auto-approval delay for new unlisted extensions (`auto_approval_delayed_until_unlisted`). When `INITIAL_DELAY_FOR_UNLISTED` is `None` (config value empty of config not existing) or `0`...

### What happened?
...a due date will be added to review the extension.

### What did you expect to happen?
...no due date should be added.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Actually, after some checking, we should already be handling that:
- If the `INITIAL_DELAY_FOR_UNLISTED` is `None` or a non-integer value, it defaults to `0`
- If the addition of the delay with the add-on creation date (https://github.com/mozilla/addons-server/issues/20586) is in the past compared to the current date when creating the version, we don't set it (we don't even set it in the past)

Essentially this makes very short delays a no-op.

**Comment by ioanarusiczki** [comment]
@diox 

On both -dev and -stage I submitted unlisted addons after I set the value of INITIAL_DELAY_FOR_UNLISTED to 0, "abc", "1a" or deleted it -> they don't get a due date in this case

Once I set the value to "1" -> they get a due date and show up in the Manual Review queue as being temporary delayed for approval. 

I used a dummy extension to avoid scanner rules.

**Comment by diox** [comment]
Thanks. I edited my comment, the results we really care about are invalid/`0` (which are what we expected), `1` depends on a of timing/luck.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-380
