### ISSUE TITLE
No padding between Edit Profile and Manage user and page header in My Profile page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2078]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Loging to MP-dev and select My Profile from username dropdown menu

Expected results:
There is a padding between Edit Profile and Manage user and page header in My Profile page

Actual results:
No padding between Edit Profile and Manage user and page header in My Profile page

Please see screencast for this bug : http://screencast.com/t/gifcsUCz

**Comment by tofumatt** [comment]
I don't think this one should block release.

**Comment by muffinresearch** [comment]
Already fixed by other changes:

<img width="312" alt="user_info_for_admin____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14151591/9ab0da8c-f6a6-11e5-92a4-3f1ffe40b573.png">

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/87LmyCIDzfm
