### ISSUE TITLE
Link add-ons without names to their review page from the review queue

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20785]
### Describe the problem and steps to reproduce it:
Add-ons without names show an unlinked `—` in the review queue

<img width="763" alt="image" src="https://github.com/mozilla/addons-server/assets/6270406/8ef8fba6-b2eb-4bfd-bdae-ea4c7a982f09">

While it is possible to get the add-on ID from the review queue's HTML table row element (`tr#addon-<id>`) and get to its review page, it would be more convenient to just link it like other add-ons with names. 

Personally, I don't see why add-ons without names (or whitespaces for names) would be allowed, but that doesn't have to change for this issue to be fixed.

### What happened?
Add-on without name (or with whitespace name) doesn't get linked from review queue to its review page

### What did you expect to happen?
Add-on without name should be linked from the review queue to its review page

**Comment by wagnerand** [comment]
Add-ons with names are not allowed, so I think we are missing a check somewhere. My bet would be around localized names.

**Comment by wagnerand** [comment]
@abhn can you provide the guid/link to that add-on?

**Comment by abhn** [comment]
@wagnerand here's the guid: `{ac87cfd8-47b1-4401-b32e-f033af5ed96c}`

**Comment by wagnerand** [comment]
manifest.json:

```
  "name": "          ",
```

I'm not sure where exactly we are doing the name-check, possibly in addons-linter, but we should handle that case.

**Comment by eviljeff** [comment]
I started investigating this - I can replicate locally by using django admin to clear the add-on name.  There's an error being thrown somewhere in the call stack for the rendering of that table cell that is causing it to be just rendering with `—` i.e. it's not even getting to our `render_addon_name` method.

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO dev:

I deleted then saved changes from [admin ](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/626983/change/) for Name. Checked the Manual Review and Content Review queues. Now there's a link with the addon id + version number 


![addon id](https://github.com/mozilla/addons-server/assets/33448286/4ab66146-9b7b-4670-9df3-b3c648c45311)

Submission of extensions with   `"name": "          "` is not allowed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-387
