### ISSUE TITLE
Remove `PyFxA`, `hawkauthlib`, `WebOb` and `PyBrowserID` from `requirements/tests.txt`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20781]
Those requirements were added for ui-tests, that at the time needed to create users with valid FxA credentials. We still have that code in our code that generates dummy data:
https://github.com/mozilla/addons-server/blob/a9a44fc934fd63e612dff8e7c85b32b18db502e8/src/olympia/landfill/serializers.py#L40-L69

Nowadays though, the only "ui testing" being done is just a [smoke test for addons-frontend](https://github.com/mozilla/addons-frontend/tree/master/tests/smoke) that creates some content (and does need `make setup-ui-tests` for that) and loads the homepage, so we shouldn't need to create users with valid FxA credentials so we can simplify that code and remove those dependencies.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-386
