### ISSUE TITLE
The steps displayed in the add-on submission form are not centered

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2079]
Steps to reproduce:
1. Open the add-on submission form: https://addons.allizom.org/en-US/developers/addon/submit/2

Expected results:
There are no layout or display issues:

Actual results:
After step 7 there is almost no padding. 

Notes/Issues:
Verified in FF45(Win7) issue can be reproduced in -dev and stage
Screencast for this issue: http://screencast.com/t/FlHqqBLO
And this is how it looked before style refresh: http://screencast.com/t/6u2Nkz0G5F3

**Comment by madalincm** [comment]
Verified as fixed in FF45(win7) in addpns-dev.allizom.org
Postfix screencast: http://screencast.com/t/bzjJKKzMErmK
Closing bug.

**Comment by madalincm** [comment]
Issue is again reproducible.
Verified in FF45(Win7) in addons-dev.allizom.org
![submissionsteps](https://cloud.githubusercontent.com/assets/15685441/14248126/86056d7c-fa7b-11e5-9a07-68ecc5413abf.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-12_1558](https://cloud.githubusercontent.com/assets/15685960/14460666/636f4d26-00c7-11e6-8a16-e6875fc4d37f.png)
