### ISSUE TITLE
Add a couple of trusted domains

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#20804]
### Describe the problem and steps to reproduce it:

We'd like to add two trusted domains to the ALLOWED_HOSTS list, aka `amo.nonprod.webservices.mozgcp.net` and `amo.prod.webservices.mozgcp.net`. These are domains managed and controlled by us and in our GCP projects.

### What happened?
We're moving AMO to GCP, thus adding those two domains.

### What did you expect to happen?
Add the said two domains to the ALLOWED_HOSTS list.

### Anything else we should know?
n/a

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-389
