### ISSUE TITLE
The error message for missing rejection reason/canned response is not displayed 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20810]
### Describe the problem and steps to reproduce it:
1. Open an addon review page - example https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1010953
2. Select the 'Reject Multiple Versions" reviewer action
3. Select a version you wish to Reject
4. Save the form without adding a reason (canned response)

### What happened?
The form closes without any error being displayed. The rejection is not processed. 

### What did you expect to happen?
There should be an error specifying that a Reason needs to be selected in order to process the review and the review form should remain open [1]

### Anything else we should know?
If you don't select a version for rejection, the expected "This field is required." error is displayed but the form is closed [2]

[1]
![firefox_DjUoZEfBBK](https://github.com/mozilla/addons-server/assets/31961530/1fff04b1-dfa9-4820-bbc9-44e4a42c3646)

[2]
![image](https://github.com/mozilla/addons-server/assets/31961530/4c941f0d-b490-4c50-9064-bc19dfc4f454)

**Comment by diox** [comment]
The code that fails:
https://github.com/mozilla/addons-server/blob/edbe3c7bf9e9981cf82c8e39c896b437dd8e7d0c/static/js/zamboni/reviewers.js#L98-L101

This is fired on document ready, and while we do have a `review_checked` containing the right element on `POST`, somehow on dev it's not in `<li>` (`id=id_action` element should be a `<ul>` as well, but it's a `<div>`).

This likely started following Django 4.2 upgrade.

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and the error messages for the Comment/Canned Responses and the Version selection fields are triggered as expected:

![image](https://github.com/mozilla/addons-server/assets/31961530/12e25433-4123-4627-946d-cfe7814a2cb6)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-391
