### ISSUE TITLE
Disallow potentially misleading display names, at least on developer profiles

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20819]
### Describe the problem and steps to reproduce it:
Currently, users can choose display names like "Recommended" which will end up displaying next to their add-on in search results misleading users

<img width="378" alt="image" src="https://github.com/mozilla/addons-server/assets/6270406/0a214564-bef2-4ced-9833-916e2991f24c">

### What happened?
Misleading display names are allowed

### What did you expect to happen?
Words that can cause confusion or which can deceive our users (say mozilla, firefox, recommended, promoted etc) should be disallowed from being set as display name

### Anything else we should know?
I see that field on AMO but I'm not sure if it is also linked to FxA, but still thought I'd create the issue here

**Comment by wagnerand** [comment]
This is the `DeniedName` model. Let's chat about what items to add internally.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-394
