### ISSUE TITLE
Record some reviewer actions by version rather than by addon

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20813]
https://docs.google.com/document/d/1ZSHEX0h74lcZvnJbmOcziEL8XNLGtJGTHtK8Jgl_QpA/edit

Certain reviewer actions are available as a single action affecting all versions at once, where in fact the underlying properties are per-version. These actions should be changed to be per-version.

Applicable actions
- Clear pending rejections
- Set "Needs Human Review”
- Clear Needs Human Review
- Clear Admin Static Theme Review Flag (split into different issue, https://github.com/mozilla/addons-server/issues/20844)

Each of these actions should be per-version (re-using the versions dropdown UI already used by other actions). In addition, the Set "Needs Human Review” needs to record a comment with the reason. The action and text if any, should be then shown in the version log on the review page with other activity.

**Comment by ioanarusiczki** [comment]
@diox 

For "Set needs human review" the "Comment" box is mandatory but if it's left empty it won't throw an error message and the whole menu just closes. This has been[ filed already ](https://github.com/mozilla/addons-server/issues/20865#issuecomment-1600766973)

Also https://github.com/mozilla/addons-server/issues/20865 has been filed to remove the comment box for clearing pending rejections and human review actions. 

I tested all the actions on AMO stage for addons with multiple versions and on both channels - I could apply the actions on one or multiple versions, so I think it should be ok. 

I've noticed that I could apply the human review flag on some blocked versions , [ the example ](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1011538#review-actions) and I'm not sure this is expected.

**Comment by diox** [comment]
It wasn't specified which versions to allow the human review flag to be set on. Since you're able to remove it with the opposite action that should be fine IMHO.

**Comment by ioanarusiczki** [comment]
@diox 

To add to my previous comment, I said that blocked versions can be flagged for human review.

Set Needs Human review can be done on all versions now:
- for signed versions , when it's also[ deleted, disabled by developer or rejected/blocked ](https://reviewers.addons.allizom.org/en-US/reviewers/review/1011541)-> set needs human review can be applied. 
- for [unsigned versions already disabled](https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1011542#review-actions) I have the possibility to set human review , select the version but the final result is that these won't get a due date and won't be displayed in the manual review queue.  -> when clicking the button there should be no versions to select.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-392
