### ISSUE TITLE
Lock Android compatibility when `gecko_android` is present in manifest, even if empty

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20827]
Follow-up for https://github.com/mozilla/addons-server/issues/20531

When `browser_specific_settings` -> `gecko_android` is present in the manifest, even if empty, compatibility for Firefox for Android should be set and locked for that add-on.

At the moment this only works if the `gecko_android` object contains anything, but it should also work when it's `{}`.

**Comment by ioanarusiczki** [comment]
@diox 

I tested on AMO dev:

[empty gecko_android  in mv2 ](https://code.addons-dev.allizom.org/en-US/browse/625639/versions/1699475/) or [empty gecko_android in mv3](https://code.addons-dev.allizom.org/en-US/browse/625640/versions/1699477/)  -> Firefox Android compatibility is locked at submission, cannot be edited in dev hub and strict_min_version is set at 113.0

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-395
