### ISSUE TITLE
Add missing "unreviewed" status for file in documentation.

### ISSUE THREAD

**Issue by maximtop** [mozilla/addons-server#20834]
When the file status is retrieved from the version, it returns the status `unreviewed', which is not described in the documentation. 

<details>
<summary>Image of the response</summary>

![image](https://github.com/mozilla/addons-server/assets/17272769/7f4b3b60-d654-4282-a990-19605473a7d0)
</details>

https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v5-addons-addon-(int-addon_id|string-addon_slug|string-addon_guid)-versions-(int-id|string-version_number)-

<details>
<summary>Image of the documentation</summary>

![image](https://github.com/mozilla/addons-server/assets/17272769/a712b518-a85e-4af6-af19-99de81f00f62)
</details>

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-397
