### ISSUE TITLE
Remove `add-guid-to-manifest` for Insert add-on ID into manifest feature

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20833]
After discussing it with @willdurand 

https://github.com/mozilla/addons-server/issues/11559 has been done a while ago 

Addons with MV2 without an `id` in the manifest.json are getting an `id` after they're being signed

The feature is gated by `add-guid-to-manifest` waffle switch -> should be removed

**Comment by diox** [comment]
Note: I'm going to make the feature permanent, but I am not removing the waffle switch in the same push, because otherwise for the duration of the push we would not be adding guids to manifests.

**Comment by ioanarusiczki** [comment]
@diox 

On AMO stage -> I made submissions of listed/unlisted mv2 extensions that don't have an id in the manifest. 
After being signed if I downloaded the extension and checked the manifest, all versions had the id.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-396
