### ISSUE TITLE
Record `Clear Admin Static Theme Review Flag` activity

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20844]
Split from https://github.com/mozilla/addons-server/issues/20813

An activity should be recorded when the needs admin theme review flag is cleared. It should be an admin event, visible in the "important changes" section of the review page.

**Comment by diox** [comment]
@wagnerand how is that supposed to impact the review permissions for the add-on itself ? Currently, if set, that flag makes it impossible to submit a review of the entire add-on if you don't have the necessary permission. If we record it per version and no longer per add-on, what is supposed to happen ?

**Comment by wagnerand** [comment]
I think for sake of easiness, we'll probably keep it that way?

**Comment by diox** [comment]
So if there is a `needs admin theme review` flag attached to _any_ version of the add-on, require the admin permission to review that theme ?

**Comment by wagnerand** [comment]
I'd say so. Let's also have @devaneymoz weigh in, as he oversees the theme review program.

**Comment by devaneymoz** [comment]
I agree with @wagnerand  it makes sense to keep it that way, but to be clear on impact -- do our theme reviewers already have the necessary permissions to accommodate per-version reviews?

**Comment by diox** [comment]
The permissions required aren't changing. The only visible difference will be that they'll need to select which version the action applies to.

**Comment by diox** [comment]
From discussion with @wagnerand : let's simplify this and keep recording per add-on (most themes have a single version anyway) and record activity log (for the whole add-on) when a theme gets/loses the needs admin theme review flag, and show that in the "important changes" section in reviewer tools.

**Comment by ioanarusiczki** [comment]
@diox 

When a theme review is requested from admin -> the theme is no longer displayed for the reviewer. 

The admin can see in the [queue](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/theme_new) there's a flag "Needs Admin Static Theme Review" 

Before this patch -> clear admin review was possible but only from admin.

Now there's a "Clear admin review" button on the [review pages](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/495579) that can be used. 

When the flag is cleared without any other action taken (an approval for example) -> a theme reviewer will see the page back in the New/Updates queues.

Activity log admin is now recording the theme being flagged and the flag being cleared as well: 

![activity log admin](https://github.com/mozilla/addons-server/assets/33448286/efcec31a-dac8-4b62-b96f-219822837327)

Reviewer's pages register both actions too:

![imp changes](https://github.com/mozilla/addons-server/assets/33448286/5c526422-997b-4b87-8af6-f1e1b395c730)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-402
