### ISSUE TITLE
GCP migration issues

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20841]
Issues currently discovered: 

- [x] With login while trying to make a submission I get the " Sorry, we couldn't load your WebExtension. " error. 
- [x] After sign in I am redirected to frontend - log out view 
- [x] [favicon](https://addons-dev.allizom.org/favicon.ico?v=2) throws a 404
- [x] [admin tools](https://addons-internal.dev.mozaws.net/admin/) throws a 403 Forbidden (with or without VPN)

**Comment by diox** [comment]
Related:
- https://mozilla.sentry.io/issues/4259954117/?project=6224627 `/data/aeskeys/api_key_secret.key` is missing
- https://mozilla.sentry.io/issues/4253941744/?project=6224627 MySQL server is read-only ?! (Lots of occurrences of this, seem to be only in cronjobs but hard to tell with all the noise)

**Comment by bqbn** [comment]
> * https://mozilla.sentry.io/issues/4259954117/?project=6224627 `/data/aeskeys/api_key_secret.key` is missing

This should have been fixed.

> * https://mozilla.sentry.io/issues/4253941744/?project=6224627 MySQL server is read-only ?! (Lots of occurrences of this, seem to be only in cronjobs but hard to tell with all the noise)

We can ignore this. They all come from the AWS dev env where we set the primary db to be read only. We have now stopped all app instances and the cron jobs in AWS. And the error should have stopped now.

**Comment by bqbn** [comment]
> * [ ]  [admin tools](https://addons-internal.dev.mozaws.net/admin/) throws a 403 Forbidden (with or without VPN)

This should have been addressed https://mozilla-hub.atlassian.net/browse/IO-2545. Please disconnect and reconnect your VPN and try again.

**Comment by bqbn** [comment]
> * [ ]  After sign in I am redirected to frontend - log out view

AFAICT, the relevant app logs are,

```
{"Timestamp": 1687301805013831168, "Type": "accounts", "Logger": "http_app_addons_dev", "Hostname": "addons-server-v1-deploy-uwsgi-amo-web-d7b8fd9d7-ktcb5", "EnvVersion": "2.0", "Severity": 6, "Pid": 10, "Fields": {"uid": "<anon>", "remoteAddressChain": "64.252.71.149", "msg": "State mismatch. URL: f44f03d9d58ed108873a787cb20051cebc19c80b2628434093f2318978dadc46:L2VuLVVTL2RldmVsb3BlcnMvYWRkb24vc3VibWl0L2Rpc3RyaWJ1dGlvbg Session: None"}, "severity": 200}
{"Timestamp": 1687301805014178048, "Type": "accounts", "Logger": "http_app_addons_dev", "Hostname": "addons-server-v1-deploy-uwsgi-amo-web-d7b8fd9d7-ktcb5", "EnvVersion": "2.0", "Severity": 6, "Pid": 10, "Fields": {"uid": "<anon>", "remoteAddressChain": "64.252.71.149", "msg": "Redirecting after state-mismatch to: /en-US/developers/addon/submit/distribution"}, "severity": 200}
```

However, I'm not sure what is causing the above. Could it be redis, memcached or something else?

**Comment by bqbn** [comment]
> * [ ]  [favicon](https://addons-dev.allizom.org/favicon.ico?v=2) throws a 404

This should have been fixed. The file was uploaded to a wrong location in the GCS bucket.

```
$ curl -i https://addons-dev.allizom.org/favicon.ico
HTTP/2 200
content-type: image/vnd.microsoft.icon
content-length: 5430
server: openresty
date: Wed, 21 Jun 2023 00:34:23 GMT
x-guploader-uploadid: ADPycduw0wT3yEym89mzVj9ungaadvjIVcLqDPdiJpF94FGobLrbXG3V5ab-A_cccC4zkXZ88o79vvPpK1F5eCk5TEZlOAfI9Ern
expires: Sat, 18 Jun 2033 00:34:23 GMT
cache-control: max-age=315360000
cache-control: immutable
last-modified: Wed, 21 Jun 2023 00:33:23 GMT
etag: "3cec07462a3d8e6ba2b472d204fa1f30"
x-goog-generation: 1687307603898661
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 5430
x-goog-hash: crc32c=FAJ5HA==
x-goog-hash: md5=POwHRio9jmuitHLSBPofMA==
x-goog-storage-class: STANDARD
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: *
strict-transport-security: max-age=31536000; includeSubDomains
via: 1.1 google, 1.1 1570d93226c1bbca2ebaad510cff3e0c.cloudfront.net (CloudFront)
x-cache: Miss from cloudfront
x-amz-cf-pop: SEA19-C1
x-amz-cf-id: cY16rIo_MXKETV_qJq7nJUvKm6xtj6Qb9qFUPzp0lVY_613Iy3K-xA==
```

**Comment by diox** [comment]
> > * [ ]   After sign in I am redirected to frontend - log out view
> 
> AFAICT, the relevant app logs are,
> 
> ```
> {"Timestamp": 1687301805013831168, "Type": "accounts", "Logger": "http_app_addons_dev", "Hostname": "addons-server-v1-deploy-uwsgi-amo-web-d7b8fd9d7-ktcb5", "EnvVersion": "2.0", "Severity": 6, "Pid": 10, "Fields": {"uid": "<anon>", "remoteAddressChain": "xx.xxx.xx.xxx", "msg": "State mismatch. URL: f44f03d9d58ed108873a787cb20051cebc19c80b2628434093f2318978dadc46:L2VuLVVTL2RldmVsb3BlcnMvYWRkb24vc3VibWl0L2Rpc3RyaWJ1dGlvbg Session: None"}, "severity": 200}
> {"Timestamp": 1687301805014178048, "Type": "accounts", "Logger": "http_app_addons_dev", "Hostname": "addons-server-v1-deploy-uwsgi-amo-web-d7b8fd9d7-ktcb5", "EnvVersion": "2.0", "Severity": 6, "Pid": 10, "Fields": {"uid": "<anon>", "remoteAddressChain": "xx.xxx.xx.xxx", "msg": "Redirecting after state-mismatch to: /en-US/developers/addon/submit/distribution"}, "severity": 200}
> ```
> 
> However, I'm not sure what is causing the above. Could it be redis, memcached or something else?

mmm this is likely an issue with the sessions, since we shouldn't be getting `Session: None`. It should be using a database table with memcached on top, I'll look into this.

**Comment by diox** [comment]
@bqbn found the issue: `DOMAIN` environnement variable is set to `.amo-gcp-test.dev.mozaws.net`. We use that to set `DOMAIN`, `SITE_URL` and `SESSION_COOKIE_DOMAIN` settings, so anything that depend on those settings is not working properly.

**Comment by bqbn** [comment]
> @bqbn found the issue: `DOMAIN` environnement variable is set to `amo-gcp-test.dev.mozaws.net`. We use that to set `DOMAIN`, `SITE_URL` and `SESSION_COOKIE_DOMAIN` settings, so anything that depend on those settings is not working properly. `DOMAIN` environnement variable should be set to `addons-dev.allizom.org`.

Sigh, it was leftover for testing that test domain. This has been fixed and I was able to log in successfully.

**Comment by ioanarusiczki** [comment]
@diox 

Except for the 403 on admin tools the other issues seem to be working.

**Comment by diox** [comment]
The admin tool should have been fixed last night, it's now working for me.

**Comment by ioanarusiczki** [comment]
@diox Yes, it was throwing a 403 without VPN. 
I tried now with 2 accounts on different profiles and it's working.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-400
