### ISSUE TITLE
The browser mapping API returns Invisible addons in results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20843]
Follow up for #20798 

### Describe the problem and steps to reproduce it:
1. As an addon developer, set a listed addon as Invisible (example - https://addons-dev.allizom.org/en-US/developers/addon/nti2ndy/versions)
2. With and Admin user, add the addon to the [Addon browser mapping admin list](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addonbrowsermapping/)
3. Send a request to the `/api/v5/addons/browser-mappings/` endpoint

### What happened?
The Invisible addon is returned in results:
![image](https://github.com/mozilla/addons-server/assets/31961530/288fc128-794f-46f9-939e-565e5b024563)

### What did you expect to happen?
The browser mapping API doesn't return Invisible addons

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO stage and Invisible addons are no longer returned by the browser mapping API.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-401
