### ISSUE TITLE
Inform reviewers when another version of an add-on is awaiting review in a different channel

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20855]
### Describe the problem and steps to reproduce it:
When an add-on submits both listed and unlisted versions (with overlapping review periods), only one of them shows up in the queue. If the reviewer doesn't manually go check the other channel or if the version in the manual review queue is stuck for any reason, they might miss reviewing the version in the other channel

### What happened?
For an add-on with versions pending review in both listed and unlisted channel, only version from either channel (is it always consistently unlisted?) shows in the queue. To discover the other channel's version, the reviewer currently has to either:
- process the review on the version in the manual review queue
- manually check the other channel and make sure there's no version that's also waiting for a review

### What did you expect to happen?
AMO informs reviewers that there are multiple versions pending review, **AND that some versions might be in a different channel**.

### Anything else we should know?
- Ideally, it would be nice to get fully visibility into the multiple versions awaiting review directly through the manual review queue page. However, if there are technical challenges with it, a banner on the review details page alerting the reviewer of the presence of versions in other channels could still be very useful.
- (If not already this way) The version with a earlier review date shows up in the queue, with the other version discoverable through the review details page.

Something like this could be re-utilized for this purpose
<img width="432" alt="image" src="https://github.com/mozilla/addons-server/assets/6270406/7661b548-0502-4fdf-ac75-4a0668bd1bcc">

/cc @wagnerand

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-405)

**Comment by ioanarusiczki** [comment]
I verified this with the Manual Review Queue when 2 versions are submitted in different channels and both are pending review:

![a warning is displayed](https://github.com/mozilla/addons-server/assets/33448286/d8f3e91c-e293-453c-a4f3-e54c7d5061ca)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-405
