### ISSUE TITLE
Unbroken strings are not wrapped in reviewer tools

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#20853]
### Describe the problem and steps to reproduce it:
As an add-on reviewer, open a review page that shows a message from the extension developer containing a very long line without whitespace nor line breaks, e.g. a base64-encoded string.

### What happened?

The layout is stretched to the point of being unusable. Furthermore, because the width of the page is fixed, the content is near-unreadable.

### What did you expect to happen?

The long line should be broken to allow for the layout to appear normal.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Example: https://reviewers.addons.mozilla.org/en-US/reviewers/review/2709803

This is like #6698, but now in the area of the review tools.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Verified on AMO stage

![longstring](https://github.com/mozilla/addons-server/assets/33448286/3c606ad5-6418-4331-bd4a-e0ae00963dd2)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-404
