### ISSUE TITLE
expose field in Block serializer to indicate if all versions for that guid are blocked

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20857]
Previously blocks contained a range of versions to indicate which versions of an add-on were blocked, so it was easily to tell if all versions for that guid would be blocked (`0` to `*`); now blocks have a finite and defined list of versions that are blocked which is less straightforward if you want to know "is every version for this add-on blocked, or just some of them".  

So we should add a `is_all_versions` property to the Block serializer which will answer that question.

**Comment by ioanarusiczki** [comment]
@eviljeff 

This has been verified with https://github.com/mozilla/addons-frontend/issues/12252

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-406
