### ISSUE TITLE
Restore edit functionality to Block admin page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20851]
https://github.com/mozilla/addons-server/pull/20829 dropped the ability to edit a Block directly from the Block page - you have to create a BlocklistSubmission.  It was always a shortcut - when you saved the request was redirected to the BlocklistSubmissionAdmin; the submission was created; and (if it didn't require dual signoff) the change was made to the Block - but it was a nicer experience for minor changes.  We should restore that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-403)

**Comment by eviljeff** [comment]
With the planned work to introduce blocklist integration in the reviewer tools (ref https://mozilla-hub.atlassian.net/browse/AMO-228) this issue is likely obsolete. Therefore closing 

cc @wagnerand

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-403
