### ISSUE TITLE
Remove unsigned disabled/deleted versions from needing human review

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20867]
Followup for https://github.com/mozilla/addons-server/issues/20813#issuecomment-1602253156

Unsigned versions disabled by developers, deleted, rejected/blocked at review should not be available in the version list when Set Needs Human Review is clicked from the review pages. 

![followup](https://github.com/mozilla/addons-server/assets/33448286/5dfe63e4-6cc7-423d-8e0f-2cf210050a04)

**Comment by ioanarusiczki** [comment]
@diox This also applies when versions are force-disabled.  [An example](https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/617383#review-actions) -> the versions do not show up in the manual review queue

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and these are my results: 

Addon used for testing most of these scenarios: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/625797

Needs human Review _**can't**_  be set for versions:
- unreviewed/not signed - disabled by developer
- unreviewed/not signed - deleted by developer
- unreviewed/not signed - rejected
- unreviewed/not signed - addon is force disabled [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625800)
- unreviewed/not signed - blocked

Needs human Review _**can**_ be set for versions:
- signed - disabled by developer
- signed - deleted by developer
- signed - rejected
- not signed - Awaiting review
- signed - blocked
- signed - addon is force disabled (*)

(*) @diox I'm not sure that this scenario is working as expected. These are the exact steps I've made:
1. Pick an addon with an approved version 
2. Force disable the addon
3. Set Needs Human Review for the addon version that was previously approved (now its status appears as Unreviewed in Rev Tools version history)
4. Check the Manual review queue to see if the addon is present there

Result: 
The addon is not present in the Manual review queue

So, the question is, should we allow versions of force disabled addons to be flagged for human review? 

Examples: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/493556, https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/625608

**Comment by diox** [comment]
> So, the question is, should we allow versions of force disabled addons to be flagged for human review?

I'm not sure. I'd lean towards no since they are excluded from the manual review queue. @wagnerand ?

**Comment by diox** [comment]
Ok, I filed https://github.com/mozilla/addons-server/issues/20934 for that follow-up to the follow-up :)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-410
