### ISSUE TITLE
Don't require a comment for certain reviewer actions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20865]
Follow-up from #20813.

The following review actions should not require a comment, in fact we can hide the comment box on the review tools page for them.

* Clear pending rejections
* Clear Needs Human Review

**Comment by AlexandraMoga** [comment]
While in the context of reviewer actions and comments, I noticed there was some regression introduced at some point that caused this issue - https://github.com/mozilla/addons-server/issues/20810

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and the Clear pending rejections and the Clear Needs Human Review actions no longer have a Comment field:

[Clear pending rejections]
![image](https://github.com/mozilla/addons-server/assets/31961530/24aa4ecc-7776-4434-ab3c-9f288b78d28e)


[Clear Needs Human Review]
![image](https://github.com/mozilla/addons-server/assets/31961530/11ee8004-4425-4b84-9180-b8990058e0c8)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-408
