### ISSUE TITLE
AMO Header Menu disapears when trying to move mouse to it

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2087]
![amo-hover-menu-disapears](https://cloud.githubusercontent.com/assets/8145891/14158976/487f270a-f6a1-11e5-9861-ddec057e9b17.gif)

**Comment by muffinresearch** [comment]
I don't seem to be able to reproduce this. What version of FF and what platform are you running?

**Comment by designakt** [comment]
I am using the latest Nightly on Windows 10. 
Just reproduced it in an empty profile and in Release.

**Comment by muffinresearch** [comment]
I notice the cursor you have in the screenshot is miniscule to the one I see on windows 10. Is there anything special about your environment? I can't repro on FF stable on win 10 either.

**Comment by designakt** [comment]
This small cursor is due to LICEcap, the software I use for recording the gif. Nothing else is special about my setup. I run a 3 week old surface pro with the latest windows 10.
And I just tested on another windows 10 machine which results in the same behavior.
The slower I move my cursor, the more likely the menu is to disappear.

**Comment by muffinresearch** [comment]
@designakt can you try a get a screenshot of what developer tools shows when you select the element. I want to try and see if you are getting any gaps:

Here's an example on OSX:

<img alt="fullscreen_31_03_2016__16_18" src="https://cloud.githubusercontent.com/assets/1514/14180786/73279bb6-f75c-11e5-8c4b-a80836ab92e8.png">

**Comment by muffinresearch** [comment]
@designakt which server are you seeing this on? Those styles look old

**Comment by designakt** [comment]
![amo-menu-gap](https://cloud.githubusercontent.com/assets/8145891/14181697/2768a876-f736-11e5-8252-b497fca458cd.PNG)
looks like there is a gap.

**Comment by designakt** [comment]
this is on https://addons-dev.allizom.org/en-US/firefox/

**Comment by designakt** [comment]
I get the same behavior on Chrome as well. And I seam to get a different font than you do in your screenshot.

**Comment by muffinresearch** [comment]
Hmm I'm seeing CORS errors for the webfonts - I'll investigate...

**Comment by muffinresearch** [comment]
This is the cors errors I see in the console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Regular.ttf?629a55a. 
(Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by designakt** [comment]
This is what I get:
> Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.(unknown)
> The resource at "https://ssl.google-analytics.com/ga.js" was blocked because tracking protection is enabled.[Learn More]firefox
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Regular.ttf?629a55a. (Reason: CORS header 'Access-Control-Allow-Origin' missing).(unknown)
> downloadable font: download failed (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Regular.ttf?629a55acss-min.css:1:6517
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Italic.ttf?c7dcce0. (Reason: CORS header 'Access-Control-Allow-Origin' missing).(unknown)
> downloadable font: download failed (font-family: "Open Sans" style:italic weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Italic.ttf?c7dcce0css-min.css:1:7086
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Bold.ttf?5014568. (Reason: CORS header 'Access-Control-Allow-Origin' missing).(unknown)
> downloadable font: download failed (font-family: "Open Sans" style:normal weight:bold stretch:normal src index:2): bad URI or cross-site access not allowed source: https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Bold.ttf?5014568css-min.css:1:6696
> NetworkError: A network error occurred.(unknown)

CORS as well.

**Comment by muffinresearch** [comment]
@jasonthomas just in-case it's relevant these fonts are `.ttf` whereas other webfonts have beeen `.woff` previously.

**Comment by jasonthomas** [comment]
*.ttf is currently not included, https://github.com/mozilla-services/puppet-config/blob/master/amo/modules/amo_proxy/templates/nginx.addons.conf.erb#L33-L35. What other extensions need CORS Access-Control-Allow-Origin to be set?

**Comment by muffinresearch** [comment]
Just `.ttf` afaik

**Comment by jasonthomas** [comment]
Changes pushed to -dev. Can we test again?

**Comment by designakt** [comment]
I now see the right font. Which fixes this issue for me.
Strange that the font would impact if one can reach the menu or not.

**Comment by designakt** [comment]
I now get another error:

> downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:normal stretch:normal src index:2) source: https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Regular.ttf?629a55acss-min.css:1:6517
> downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:italic weight:normal stretch:normal src index:2) source: https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Italic.ttf?c7dcce0css-min.css:1:7086
> downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:bold stretch:normal src index:2) source: https://addons-dev-cdn.allizom.org/static/css/impala/fonts/OpenSans-Bold.ttf?5014568css-min.css:1:6696

**Comment by muffinresearch** [comment]
Yep I think you can ignore that. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1185685

**Comment by muffinresearch** [comment]
@jasonthomas thanks that fixed the error.

@designakt - ok I'm going to close the bug on the basis that it's working for you now.

**Comment by AlexandraMoga** [comment]
Since this is not reproducing anymore and the old site will soon become obsolete, this can be marked as verified fixed.
