### ISSUE TITLE
[GCP migration] Versioncheck is not working on -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20873]
Follow up for #20841 

### Describe the problem and steps to reproduce it:
1. Install an addon on AMO -dev
2. Go to about:addons and trigger a manual check for updates

### What happened?
The update request responds with a 301 (there are multiple identical responses for just one addon, as seen in the screenshot below) and then finally an error is returned - `NS_ERROR_REDIRECT_LOOP`

![image](https://github.com/mozilla/addons-server/assets/31961530/768d5093-c041-47de-a18e-993458261776)

### What did you expect to happen?
Addon updates are working

**Comment by diox** [comment]
cc @bqbn the redirect loops seems to happen before the app is even hit. Weirdly it redirects to `:443` explicitly.

```
% curl -i 'https://versioncheck-dev.allizom.org/update/?reqVersion=1&id=uBlock0@raymondhill.net&version=2.0&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=100.0' -i
HTTP/2 301 
cache-control: private
location: https://versioncheck-dev.allizom.org:443/update/?reqVersion=1&id=uBlock0@raymondhill.net&version=2.0&appID=ec8030f7-c20a-464f-9b0e-13a3a9e97384&appVersion=100.0
content-length: 0
date: Fri, 23 Jun 2023 15:40:39 GMT
content-type: text/html; charset=UTF-8
via: 1.1 google
x-cache-status: miss
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Comment by bqbn** [comment]
The redirection issue should have been fixed with https://github.com/mozilla-it/webservices-infra/pull/609/commits/365a189c2e512f19b7593e9b3fe99def106bdeb7

The reason was because the GCP ingress had "redirectToHttps" enabled by default, whereas in AWS we don't do that.

Please verify and let us know if there are issues.

**Comment by AlexandraMoga** [comment]
I've verified the issue on -dev and addon updates are working now. I'm not seeing any redirects anymore.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-412
