### ISSUE TITLE
 Flag add-ons with a high abuse report / users ratio according to their review tier

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20870]
A new Needs Human Review reason should be `Over abuse reports threshold for usage tier`.

A new field for each usage tier will hold the a ratio (expressed as a percentage) above which the add-ons will be flagged for human review. To begin with the ratio is computed with the number of abuse reports over the past 2 weeks compared to the number of users: An add-on with 100 users and `X` reports over the past 2 weeks would be flagged if the ratio set for that tier is `X` or lower.

**Comment by AlexandraMoga** [comment]
@diox I'm trying to set up test data to check this feature but I'm not sure if I understand the specifications correctly. For starters, I have the following set-up on AMO -dev (all these are extensions with stats available on -dev):



Addon | ADU | Nr. of abuse reports past 2 weeks | Tier | Growth threshold | Abuse reports ratio
-- | -- | -- | -- | -- | --
502955 | 10 | 3 (addon) | N/A | N/A | N/A
616918 | 2696 | 5 (addon) | 100-1000 | 10 | ?
495710 | 22929 | 13 (2 addon/ 11 user) | 10000-100000 | 5 | ?
617049 | 109174 | 10 (addon) | 100000-2000000 | 1 | ?
620017 | 155157 | 15 (addon) | 100000-2000000 | 1 | ?
495646 | 1056375 | 20 (addon) | 100000-2000000 | 1 | ?

A few things:
- do we count both addon and user abuse reports?
- is the 'Growth threshold before flagging' influencing the results? For example, if I leave it as it is set right now and the addons don't meet the condition, then we won't see the addons flagged for the Abuse reports ratio?
- I'm not sure what Abuse reports ratio I am supposed to set. If I understand the request correctly, we need to express the number of abuse reports as a percentage of total number of users? This would mean that the abuse report quantity should be very high?

**Comment by diox** [comment]
> do we count both addon and user abuse reports?

Only add-ons (same `guid`)

> is the 'Growth threshold before flagging' influencing the results? For example, if I leave it as it is set right now and the addons don't meet the condition, then we won't see the addons flagged for the Abuse reports ratio?

It's independent, **but** at the moment, when we are flagging, we are looking at the latest signed version in both channels, and if that version already has a human review date, or already have an active (non-cleared by a reviewer action) flag for human review, it is not flagged another time.

> I'm not sure what Abuse reports ratio I am supposed to set. If I understand the request correctly, we need to express the number of abuse reports as a percentage of total number of users? This would mean that the abuse report quantity should be very high?

The ratio is a percentage corresponding to the number of abuse reports in the past 14 days divided by the ADU value. The minimum is `1`, so yes, for add-ons that have a very high number of users, that is a lot of abuse reports (For an add-on with 5000 ADU, if the ratio configured for the tier is `1`, that'd be >= 50 reports).

**Comment by AlexandraMoga** [comment]
Ok, hope I got the test data right. I've reduced the usage tiers a bit to avoid using addons with high ADU's which would require too many abuse reports to be submitted. I can do that by using a script, but even so, I'd rather avoid posting thousands of abuse reports for one `guid`.  

These are the addons I'm expecting to see flagged after the cron runs on AMO -dev (not sure what's the schedule for it):



Addon | ADU | Nr. of abuse reports past 2 weeks | Tier | Growth threshold | Abuse reports ratio
-- | -- | -- | -- | -- | --
502955 | 10 | 8 | 1-10 | 10 | 5
616918 | 2696 | 29 | 100-1000 | 5 | 2
495710 | 22929 | 253 | 10000-1000000 | 1 | 1

**Comment by diox** [comment]
I wouldn't expect the second one (id 616918) to be flagged because of abuse reports - if the ratio is set to 2 for its tier, then with that ADU it'd need at least 54 reports to be flagged.

**Comment by AlexandraMoga** [comment]
> I wouldn't expect the second one (id 616918) to be flagged because of abuse reports - if the ratio is set to 2 for its tier, then with that ADU it'd need at least 54 reports to be flagged.

Yes, you're right.  I have added a ratio of 1 first and switched to 2 in the end but forgot to add additional reports. I'll add them now.

**Comment by AlexandraMoga** [comment]
@diox I have the results for the Over abuse reports threshold for usage tier:

AMO -dev: 


Addon | ADU | Nr. of abuse reports | Tier | Abuse reports ratio | Result
-- | -- | -- | -- | -- | --
502955 | 10 | 8 | 1-10 | 5 | Not in queue (*)
616918 | 2696 | 57 | 100-1000 | 2 | Not in queue - not included in any tier so it's expected
495710 | 22929 | 253 | 10000-1000000 | 1 | In Manual queue



(*) has this addon not been flagged because a tier of 1-10 doesn't include 10?

AMO stage:


Addon | ADU | Nr. of abuse reports past 2 weeks | Tier | Abuse reports ratio | Result
-- | -- | -- | -- | -- | --
1003729 | 51 | 19 | 1-100 | 3 | In Manual queue
1004834 | 2679 | 62 | 100-10000 | 2 | In Manual queue
619853 | 21881 | 261 | 10000-1000000 | 1 | Langpack - not in manual queue, expected



Stage looks good.

**Comment by diox** [comment]
> (*) has this addon not been flagged because a tier of 1-10 doesn't include 10?

Yes - user ranges include the lower value but exclude the upper one. This allows tiers to not overlap, and follows [general programming conventions about intervals](https://fhur.me/posts/always-use-closed-open-intervals).

**Comment by AlexandraMoga** [comment]
@diox I have a question regarding Abuse reports count for addons that have changed GUIDs.
We have this example on -dev - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/616918. This addon has two GUIDs: Original Add-on ID - {4ee72572-bb01-4731-921c-7f20c6556b35} and new Add-on ID - 1b2383b324c8520974ee097e46301d5ca4e076de387c02886f1c6b1503671586@pokeinthe.io. However, if I'm  looking at the Abuse Reports count on the Review page, it looks like we only count those submitted for the Old GUID. I've checked in the Admin Abuse reports lists for both GUIDs and we should have over 100 reports for the combined GUIDs.

**Comment by diox** [comment]
Mmmm I am not sure what's happening there, please open a separate issue. For the flagging, I'm only considering the current guid (on purpose: it's about fresh abuse reports, and we haven't allowed guid re-use for a long time).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-411
