### ISSUE TITLE
correctly expose which versions are in blocklistsubmission

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20882]
follow-up for #20748 

the versions that are changed in a blocklist submission should be clear in a blocklistsubmission both before and and after it's been published

**Comment by ioanarusiczki** [comment]
@eviljeff 

Going from blocksubmissions to a [page](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/601/change/?_changelist_filters=signoff_state%3Dall) 

The red dot - hovering over - there's a tooltip "Blocked".
The green dot - Not blocked.
I don't think I've noticed other issues around the states of the versions. If I try to un-block versions , the blue check-mark is available. 

I've a question about versions delayed for block.  Going on[ Edit submission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/605/change/) I tried to edit Disable addon , Url or Reason -> don't seem to work after I update, fields are empty.

Let me know if I should file an issue about this scenario -> if versions with sign-off delayed should not have Disable addon, Url or Reason as editable fields.

**Comment by eviljeff** [comment]
> I've a question about versions delayed for block. Going on[ Edit submission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/605/change/) I tried to edit Disable addon , Url or Reason -> don't seem to work after I update, fields are empty.
> 
> Let me know if I should file an issue about this scenario -> if versions with sign-off delayed should not have Disable addon, Url or Reason as editable fields.

they should be editable and the values should update - seems like another regression from https://github.com/mozilla/addons-server/issues/20888 - can you file a follow-up?

**Comment by ioanarusiczki** [comment]
@eviljeff 

I filed https://github.com/mozilla/addons-server/issues/20930. Disable add-on is updated, but url and reason are not.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-413
