### ISSUE TITLE
Define and fix behavour around Block metadata for blocklistsubmission

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20888]
Bringing over some known flaws I noted in https://github.com/mozilla/addons-server/pull/20829

Block metadata is the reason and url that we publicly expose.  When we could only have a single blocklistsubmission for one block at one time it wasn't a particular problem - now we can have multiple submissions it is.

Currently:
- when a guid is submitted in a **multiple** guid blocklistsubmission, but none of that guids versions are selected to be blocked (i.e. all the checkboxes are deselected; or the versions are already present in another blocklistsubmission so not available) currently the reason + url would be updated on that guid's block. [This isn't addressed in the PR - it's working as expected]
- On the other hand, when a guid is submitted in a **single** guid blocksubmission and none of the versions are selected to be blocked (or all are unavailable), because you _want_ to update the metadata a validation error is raised because at least one version must be selected.  [the PR fixes this - you no longer have to select a version to be blocked if you only want to change metadata]
- when there are multiple blocklistsubmissions affecting a guid each submission that is published last will overwrite the previous metadata - e.g. if you _don't_ want to change the reason/url you have to be careful to copy to have the reason/url be the same in each submission, and copy from the existing block [the PR fixes this by prefilling the existing reason/url if set, and adding a checkbox to control if you want to overwrite the existing metadata]
- when a blocklistubmission is created directly from the reviewer tools [https://github.com/mozilla/addons-server/issues/20498] we don't have a way of defining the reason or url from the reviewer tools.  We could default to a generic reason and no url but not ideal. [the PR doesn't address this because it's more in the scope of #20498, but an existing reason/url won't be overwritten, and a new one could be manually defined]

[comment updated with how the PR will address the issue]

**Comment by eviljeff** [comment]
Blocklisting [canned responses](https://mozilla-hub.atlassian.net/browse/AOP-45) is connected to metadata, so maybe that'd be an option too, for reason at least.  e.g.

- [ ] <Don't set reason>
- [ ] "" (blank)
- [ ] "This extension is bad and does bad things"
- [ ] "yada yada"

**Comment by ioanarusiczki** [comment]
@eviljeff 

Editing url or reason can be done going from rev tool's Update button to the[ block add](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B58f187d8-c3b8-4098-be5e-f736769d7f88%7D&) form

- un-checking reason and url when blocking a new version of an addon would keep the same metadata displayed on frontend pages. Same happens leaving the check marks and the content which has been used before when blocking the previous version.  An example is this [block](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26381/change/) on 3 versions -> the [frontend page](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B9b62d738-d5e7-4f8f-af3e-1da4b01481d3%7D/) 

- I've noticed that for a new version blocked if I leave the url and reason checked but I delete the input for both fields and save -> the text is being updated , it works as deleting it, but the url does not behave the same way -> I'll keep having the url from the previous block

 This is the [add block ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B58f187d8-c3b8-4098-be5e-f736769d7f88%7D&) and the [frontend page ](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B58f187d8-c3b8-4098-be5e-f736769d7f88%7D/)displays no text for reason together with the previous url. -> I don't think that's expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-415
