### ISSUE TITLE
The message generated when unblocking a version is incorrect

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20899]
Followup for https://github.com/mozilla/addons-server/issues/20748

1. This add-on has all versions blocked https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625728
2. From Edit block I clicked on Delete and selected only one version to be un-blocked

The result:
I expected to see in the Block History a message about one version being unblocked -> there's a [block edited](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B145dd373-de00-4e47-a0e9-f8e32c17ada0%7D&action=1) on all versions

The review page displays on all the versions a Block edited: 5 versions unblocked. 

Expected result: 
1 version unblocked (version 1.0)

**Comment by ioanarusiczki** [comment]
Another example: both versions (2.0 and 3.0) have been blocked for https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625741 (there's a listed and an unlisted version) 

Then version 2.0 has been deleted (unblocked) 
[Block History ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26359/change/ )mentions both versions as being edited. 

The review page displays "2 versions unblocked" on the unblocked version (2.0) -> should be "1 version unblocked"
Then it's also posted on version 3.0 which is still blocked -> should not be displayed here 

![version3](https://github.com/mozilla/addons-server/assets/33448286/8d0de751-020a-4faa-945e-317f2d6d0f8a)

**Comment by ioanarusiczki** [comment]
This also occurs when making partial blocks for an addon: 
The message when the second version is blocked is also displayed on v1 -> it should only be available once , also the reason is displayed from the initial block (maybe that should not be there)

![at partial blocks](https://github.com/mozilla/addons-server/assets/33448286/7b52028b-e354-4fde-8d99-26d5ff185da7)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I checked on AMO Stage - looks good now on block and delete block too. The reason is no longer displayed in Add-on history.

![blocked unblocked](https://github.com/mozilla/addons-server/assets/33448286/6332f29b-3e17-4ea0-9e60-171b3f5ddc00)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-419
