### ISSUE TITLE
"View on site" button not working on "Change addon regional restrictions" page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#20890]
Prerequisites:
Admin rights on AMO

Steps to reproduce:
1. Logged with Admin account access the Regional restrictions list (https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addonregionalrestrictions/?o=-1)
2. Open any restriction from the list by clicking the link under "Created" column
3. Press the "View on site" button from top right corner of restriction detail page

Expected results:
The page is correctly opened

Actual results:
"Oops..." page displayed

**Comment by eviljeff** [comment]
What would be the page you'd see?

**Comment by diox** [comment]
None - we just need to set `view_on_site = False` on that admin.

**Comment by ioanarusiczki** [comment]
@eviljeff 

" View on Site" button is no longer displayed. 

Verified on addonregionalrestrictions -dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-416
