### ISSUE TITLE
Clear human review flag action doesn't show add-on in review log

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20904]
When a reviewer clears human review on an add-on, we log the activity and show it in the review log, but the entry does not show which add-on it was for:

<img width="922" alt="Screenshot 2023-06-29 at 14 18 09" src="https://github.com/mozilla/addons-server/assets/873258/ff5b2076-858e-451c-b76c-7c0109927ae5">

**Comment by ioanarusiczki** [comment]
@diox 

On -dev I checked the[ reviewlog](https://reviewers.addons-dev.allizom.org/en-US/reviewers/reviewlog) -> the name of the addon is attached and redirects to the review page

![review page attached](https://github.com/mozilla/addons-server/assets/33448286/8894c03b-b3e8-409f-b9f8-53c2f7a29cf1)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-423
