### ISSUE TITLE
Delay block by days is displayed into Delete Blocks

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20903]
Followup https://github.com/mozilla/addons-server/issues/20748

While going to a [Delete Block](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7Bf0d4d8d1-ced9-4319-adbf-b80f0735a671%7D&action=1) , the last section of the form is

Delay Block by days -> even if I added a number, and saved the delete  -> it has no effect  because a version is instantly unblocked 

![remove delay block from delete](https://github.com/mozilla/addons-server/assets/33448286/f9da7db2-d08d-4fe7-b2af-733dcacaa87d)

**Comment by ioanarusiczki** [comment]
There are 2 check-marks without text in the form, I don't remember those being there when I filed this issue

![2 checkmarks](https://github.com/mozilla/addons-server/assets/33448286/27b11a73-8729-4bf3-8bcf-3342a328dfb5)

**Comment by eviljeff** [comment]
> There are 2 check-marks without text in the form, I don't remember those being there when I filed this issue
> 
> ![2 checkmarks](https://user-images.githubusercontent.com/33448286/250498661-27b11a73-8729-4bf3-8bcf-3342a328dfb5.gif)

I didn't see this when I merged the pr that would fix the issue.  If it does still happen it's not related to delaying.

**Comment by eviljeff** [comment]
> > There are 2 check-marks without text in the form, I don't remember those being there when I filed this issue
> > ![2 checkmarks](https://user-images.githubusercontent.com/33448286/250498661-27b11a73-8729-4bf3-8bcf-3342a328dfb5.gif)
> >       
> >         [
> >           
> >         
> >             ![2 checkmarks](https://user-images.githubusercontent.com/33448286/250498661-27b11a73-8729-4bf3-8bcf-3342a328dfb5.gif)
> >           ](https://user-images.githubusercontent.com/33448286/250498661-27b11a73-8729-4bf3-8bcf-3342a328dfb5.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/33448286/250498661-27b11a73-8729-4bf3-8bcf-3342a328dfb5.gif)
> 
> I didn't see this when I merged the pr that would fix the issue. If it does still happen it's not related to delaying.

Ah, this is another regression from https://github.com/mozilla/addons-server/issues/20888 :|

**Comment by ioanarusiczki** [comment]
@eviljeff 

Delay block is no longer in the form but the checkmarks are still present so I'm going to file a separate followup for them

![Delete not present](https://github.com/mozilla/addons-server/assets/33448286/a7519181-394a-4641-8d4c-fb27243b9fe8)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-422
