### ISSUE TITLE
A blocksubmission's Delay section does not display a date

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20909]
Followup for https://github.com/mozilla/addons-server/issues/20748

Delayed for approval versions don't display the delay in [admin pages ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/561/change/?_changelist_filters=signoff_state%3D3)

I can check the delay [here](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/?signoff_state=3) -> there is a delayed until column 

But the blocksubmission pages look like this: 

![delay not displayed](https://github.com/mozilla/addons-server/assets/33448286/b1c0f7e3-8fde-47e0-b2a1-53c3a437eb28)

**Comment by ioanarusiczki** [comment]
@eviljeff 

This is verified on AMO stage - I can view and update a [delay](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/279/change/?_changelist_filters=signoff_state%3Dall)

![date is back](https://github.com/mozilla/addons-server/assets/33448286/7096d79b-548e-45db-9514-50590243f758)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-425
