### ISSUE TITLE
Versions in blocksubmission don't get checked when making the block from Block Multiple Versions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20919]
Followup for https://github.com/mozilla/addons-server/issues/20901

1. Go to an [unlisted review page](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625782#review-actions) 
2. Click on Block Multiple Versions - select all versions or one and Save

Actual result:
On the [blocksubmission page ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B9e7cb617-89c8-4bc6-8519-067dabb7848f%7D&v=1699699#review-actions) none of the versions are selected 

I think the expected is: 
In case all versions were selected - all versions are checked
In case one version was selected - that version should be checked

**Comment by eviljeff** [comment]
I doubt this is related to https://github.com/mozilla/addons-server/issues/20901 - it's just a bit of javascript that fires when you click the links and there's no interaction with the links in the STR

**Comment by eviljeff** [comment]
I didn't bother to work out which patch broke it, but it was probably broken from when I fixed the checkboxes last.

**Comment by ioanarusiczki** [comment]
@eviljeff I've noticed this behavior the last week and updated https://github.com/mozilla/addons-server/issues/20748#issuecomment-1609649795 

But then it became more obvious it's an issue after more testing.

**Comment by ioanarusiczki** [comment]
@eviljeff 

This is verified on AMO stage

![selection fixed](https://github.com/mozilla/addons-server/assets/33448286/8177a120-3a72-47e4-b280-b12d157c4d77)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-428
