### ISSUE TITLE
Delete for un-blocking a version is not displayed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20910]
Followup  
https://github.com/mozilla/addons-server/issues/20748

Delete button is not present for already blocked versions of an addon while other versions are pending for auto-sign off

![Delete not present](https://github.com/mozilla/addons-server/assets/33448286/5ae8f884-ecd2-4984-8a83-7e602035952c)

An example:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625740

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified this on AMO Stage -> I could unblock version 1.0 while [two other versions](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/277/change/) have a delayed sign-off.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-426
