### ISSUE TITLE
Some unlisted add-ons show incorrect Last Review value

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2091]
On stage, for ADDON_stage1 .1 it says ".2 on 2015-05-21". However, version .1 was submitted after .2, and the review activity for .1 happened much later (07/22).

For LastPass it says "None on None", but there's clearly lots of review activity for that one. It would also be good to default to an empty string or something like "No reviews".

**Comment by eviljeff** [comment]
I think this is due to how listed add-ons have their 'reviewed' dates set for updates - i.e. it doesn't always seem to get set.  I'll investigate but if its what I suspect it won't be fixable for existing add-ons, but will work for any unlisted add-ons you subsequently review.

**Comment by eviljeff** [comment]
so, we have some possible fixes here:
1. continue to use `reviewed` on the version for date - problem is its been inconsistently set on existing versions, both when the add-on was previously listed and also when its unlisted, so its pretty much useless for existing versions on AMO.  We could clear it for all unlisted add-ons in a migration but then its blank for all existing add-ons, and it might cause some intended consequences .
2. `JOIN` the review log and use that as the date.  Multiple review content (e.g. a comment following an info-request) means there isn't a single 'reviewed' date - currently its the first review content (not by Mozilla) date.
3. create a whole new model just to store the last date/time an unlisted add-on had a 'review completed' on it.  Would be completely blank for any existing add-on.
4. add a new `reviewed` date to the version (called something else).  Would have the same limitations as 3. plus added confusion when some future person tries to understand why there are two reviewed dates.

I'd recommend 2. as we can use some existing data and its pretty accurate except when there is a lot of activity on a single version.

**Comment by jvillalobos** [comment]
I agree that 2 is a good approach. However, I would also like to look into why 1 is happening. If it's only old data that is wrong, that's okay. But if it's still being set inconsistently, we should fix that.

**Comment by eviljeff** [comment]
The editor tools code implies 'version.reviewed' is only set when the the add-on status changes, i.e. when an add-on goes through the nominated queue and becomes fully reviewed, or whatever.  The updates queue doesn't change the add-on status so it doesn't set `version.reviewed`.
But, some of the existing add-ons /do/ have `version.reviewed` set on random versions, and some have no versions with a `version.reviewed` on them.  The implication is the behaviour changed at some point.  As I'm not sure what `version.reviewed` is even used for I'm tempted to just leave the current behaviour as is.
