### ISSUE TITLE
Highlight/handle case where a reused guid has an identical version number

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20924]
We used to allow a guid to be reused (an add-on with a defined guid deleted on AMO, then submitted again with the same guid) so it's possible to have a guid with more than one version that shares an identical version string.  If some of those versions are blocked via the admin tools but not the others it would appear to only affect some of the versions, but actually when the bloom filter is generated everything is expanded to `guid`+`version` so they'd all be blocked. 

Two possible fixes - a validation error requiring you to block all the versions; ~or some javascript that makes sure all are [de]selected together~.  (The former is more explicit)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-433
