### ISSUE TITLE
Selecting/deselecting may not work properly 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20920]
Followup for https://github.com/mozilla/addons-server/issues/20901

1. Go to a[ Delete Blocks page ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B9e7cb617-89c8-4bc6-8519-067dabb7848f%7D&action=1#) 
2. Click select none
3. Refresh page 

-> The versions are displayed as being selected 

Same on a [blocksubmission page](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B531b5123-4642-457c-8594-ec205cbeb11e%7D&#)

Another scenario I could reproduce on both pages (block, delete) : 
1. Leave only one version selected , deselect de rest of them
2. Click select all 
-> observe nothing happened
3. Refresh page 

-> all version are selected

**Comment by eviljeff** [comment]
refreshing the page and getting the defaults back is expected - the values are parsed from the url each time.  But the javascript shouldn't just stop working once you've clicked on the checkboxes.  Fixed in #20920

**Comment by ioanarusiczki** [comment]
@eviljeff 

This is verified on AMO stage

![select deselect](https://github.com/mozilla/addons-server/assets/33448286/c24ea62a-b9dc-4bbd-a64a-7ce530a376a4)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-429
