### ISSUE TITLE
Remove select all, select none from published submissions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20922]
Followup https://github.com/mozilla/addons-server/issues/20901

[Published blocksubmission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/?signoff_state=4) pages - display the versions [already blocked ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/597/change/?_changelist_filters=signoff_state%3D4)

Because the versions cannot be selected or deselected -> select all and select none are not needed

**Comment by AlexandraMoga** [comment]
The 'select all/none' options are no longer present on a published block:

![image](https://github.com/mozilla/addons-server/assets/31961530/4bac8960-f944-4b4a-a881-74474dde4506)

**Comment by AlexandraMoga** [comment]
@eviljeff one consequence of this change, I think, is that we're no longer displaying the remaining versions that weren't covered by the block. I've made a comparison with stage and the versions that haven't been blocked are listed with a green dot next to them. Was this intended or is it a regression? 

![image](https://github.com/mozilla/addons-server/assets/31961530/c8a46f31-48a7-46b1-bbaf-bc4d24ead4e4)

**Comment by eviljeff** [comment]
> @eviljeff one consequence of this change, I think, is that we're no longer displaying the remaining versions that weren't covered by the block. I've made a comparison with stage and the versions that haven't been blocked are listed with a green dot next to them. Was this intended or is it a regression?
> 
> ![image](https://user-images.githubusercontent.com/31961530/254575231-c8a46f31-48a7-46b1-bbaf-bc4d24ead4e4.png)

the PR was to fix https://github.com/mozilla/addons-server/issues/20902 and the select all|none linkes were a minor bug I fixed along the way.  There wasn't a change to show the versions differently when you create a submission, but please highlight potential problems in #20902

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-431
