### ISSUE TITLE
Delay block by days is still present in the update form after all versions have been blocked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20923]
While checking the way metadata can be updated https://github.com/mozilla/addons-server/issues/20888

For a [fully blocked add-on ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/611/change/)

when going from the review page and Update add-on block

Delay Block by days is displayed - I added a number of days and saved it 

Result:
[A delay sign-off blocksubmission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/611/change/?_changelist_filters=signoff_state%3Dall) has been created , but versions are already blocked. 

![remove delay block from delete](https://github.com/mozilla/addons-server/assets/33448286/41737a47-f41a-45b9-b105-05777e8b1da5)

The expected -> Delay block by days should no longer be available - maybe inactive until a new version is submitted ?

**Comment by eviljeff** [comment]
just merged https://github.com/mozilla/addons-server/pull/20914 which I expect will address this issue too

**Comment by eviljeff** [comment]
So closing as complete 🤞

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-432
