### ISSUE TITLE
IP addresses are not recorded correctly on GCP dev env

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20925]
STR:
- Submit an add-on
- Look up the activity log for that add-on in the admin - there should be one "Version X.X added to YYYY".
- Check the IP address associated with that activity

Expected results:
- It's your IP

Actual results:
- It's an IP that belongs to Cloudfront

(Also affects to every other place where we record/use IPs, like rate limiting, but those STR was the easiest way to check I could think of)

---

In order for the client IP to be recorded properly, a few things are assumed by the code. One of these is likely wrong on dev:
- Cloudfront must pass it through `X-Forwarded-For` header in the last position
- Our load balancer must append the CDN IP to that header, moving the client IP to the second to last position
- Cloudfront must pass an additional `X-Request-Via-Cdn` header with a value matching `SECRET_CDN_TOKEN` env variable - that value is then stored in a django setting of the same name.

**Comment by bqbn** [comment]
We have not touched Cloudfront when moving the dev environment to GCP. It is only the application and the proxy layer software got moved to GCP.

It is unlikely that Cloudfront is the problem, and it may be one or some of the ingresses that cause the issue.

**Comment by diox** [comment]
I agree. My guess is that the load balancers behave differently and don't append the CDN IP in the same way the AWS ones did.

**Comment by bqbn** [comment]
So in AWS case, we have

```
Browser -> Cloudfornt -> ELB -> Nginx
```

Because the ELB doesn't append its own IP to the value of the `x-forwarded-for` header, normally Nginx sees 2 IPs in that header, i.e. the browser IP followed by the Cloudfront edge server IP. Here is one example,

```
1688860029.598 "188.72.101.6, 64.252.89.120" UA addons.allizom.org "GET /api/v5/addons/autocomplete/?app=firefox&lang=en-US&promoted=recommended&q=-1%20OR%202%2B706-706-1=0%2B0%2B0%2B1&type=extension HTTP/1.1" 200 14 "https://addons.allizom.org/" "Mozilla/5.0 (Linux; U; Android 4.0.3; en-us; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30" 0.035 0.035 "-"
```
where `188.72.101.6` is the browser IP and `64.252.89.120` is the Cloudfront edge server IP.

In GCP case, we have

```
Browser -> Cloudfornt -> GKE ingress -> Nginx
```

What we have seen in the Nginx logs is that the GKE ingress appends its IP to the end of the value for `x-forwarded-for`, e.g.

```
{"timestamp": "2023-07-09T00:56:59+00:00","msec": "1688864219.305","remote_addr": "34.107.180.235","body_bytes_sent": 17797,"request_time": 0.354,"response_status": 200,"request": "GET /zh-TW/firefox/collections/10642146/fenix/?utm_content=%3Cxyz%3E&utm_medium=%3Cxyz%3E&utm_source=%3Cxyz%3E HTTP/1.1","request_method": "GET","host": "addons-dev.allizom.org","server_name": "addons-dev.allizom.org","server_port": "8000","upstream_addr": "10.25.15.193:8000","upstream_response_time": "0.354","gzip_ratio": "","http_cloudfront_viewer_country": "FR","http_x_forwarded_for": "51.158.66.207, 64.252.84.215, 34.107.180.235","http_referrer": "","http_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36","http_version": "HTTP/1.1","nginx_access": true}
```
where `51.158.66.207` is the browser IP, `64.252.84.215` is the Cloudfront edge server IP , and `34.107.180.235` is the GKE ingress IP.

Do you think we may need to adjust the application to adapt to this change?

Reference:

* [[1]](https://cloud.google.com/load-balancing/docs/https#x-forwarded-for_header) explains how Google load balancer handles the `x-forwarded-for` header.

**Comment by bqbn** [comment]
We don't pass this env variable in the AWS environment (we can if needed).

**Comment by vcarciu** [comment]
Verified as fixed on AMO-dev. My IP is correctly recorded in admin activity log under IP ADDRESSES column.

**Comment by diox** [comment]
@vcarciu thanks - could you please explicitly re-test this when it hits stage on August 30th (which isn't on GCP yet - we want to make sure everything still works with AWS too)

**Comment by vcarciu** [comment]
@diox  - yes, we will verify it on Stage too, deleting the verified label until Stage verification.
Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-434
