### ISSUE TITLE
Disallow versions of force disabled addons to be flagged for human review

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20934]
Follow-up for https://github.com/mozilla/addons-server/issues/20867

>>> So, the question is, should we allow versions of force disabled addons to be flagged for human review?
>>
>> I'm not sure. I'd lean towards no since they are excluded from the manual review queue. @wagnerand ?
>
> What mat said. Since force-disabling is a purely manual action, the expect that any force-disabled add-on has been looked at by a human already. As such, there should be no need to put them into the queue again.

I had forgotten about this but we already remove all needs human review flags when force disabling anyway, so it makes even more sense to prevent flagging them. Force disabling is really the point of no return.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-437
