### ISSUE TITLE
Add-on review lock icon doesn't resume showing after network interruption 

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20931]
### Describe the problem and steps to reproduce it:
When a reviewer is reviewing an add-on, and puts their computers to sleep (say they're taking a break), the lock icon stops showing for others informing them that the add-on is being looked at, even after they open their browser to the review tab again.

### What happened?
- Reviewer is looking at an add-on
- Other reviewers can see the lock icon, indicating that a reviewer is looking at it
- Reviewer pauses work (to get a coffee ☕)
- Reviewer comes back and resumes working on their add-on review
- The lock icon no longer shows for other reviewers, warning them that the add-on is being looked at

### What did you expect to happen?
- Lock icon shows back again once the reviewer resumes their work on an add-on

### Anything else we should know?
Looks like the `setTimeout` function assumes a successful previous call. In case the internet breaks, the `$.post` call in `#check_currently_viewing` fails, and the next `setTimeout` isn't scheduled. 
https://github.com/mozilla/addons-server/blob/b204dde19e4287db3834b23d7bef2509931cb4b4/static/js/zamboni/reviewers.js#L155

Perhaps the `setTimeout` could be added to a [`.always(..)`](https://api.jquery.com/deferred.always/) or something?

**Comment by alexandruschek** [comment]
Hello @eviljeff, I checked this morning and on -dev I see that the lock on icon is empty
![image](https://github.com/mozilla/addons-server/assets/139126091/ae0b6b11-c5c1-4af1-82d0-4f0ca4c3f96e)

**Comment by ioanarusiczki** [comment]
I could reproduce the issue noticed by @alexandruschek 

The lockicons in queues are visible (did not test the reported scenario yet)

![lockicon](https://github.com/mozilla/addons-server/assets/33448286/a020440e-5d0c-47d1-b7d5-7238d3d6b6d5)

**Comment by eviljeff** [comment]
> Hello @eviljeff, I checked this morning and on -dev I see that the lock on icon is empty 

fixed in #21199

**Comment by ioanarusiczki** [comment]
@eviljeff Currently viewing warning is displayed on AMO dev.

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO dev we've tested with 3 locked add-ons from Manual Review Queue and other 3 locked i  Content Review Queue.

The lock icons disappeared from my screen once @alexandruschek set on sleep his laptop.  When he resumed activity I've noticed all lock icons being displayed.

Tested the same scenario on AMO stage and observed that out of 3 add-ons locked only one displayed the lock icon after work was resumed. -> With only one add-on locked we've got the same results : lock icon was displayed on dev and stage

**Comment by eviljeff** [comment]
@ioanarusiczki I'm not clear if you're highlighting something that isn't working as expected, or that it is and this issue is now verified

**Comment by ioanarusiczki** [comment]
@eviljeff I'll mark it verified then. 

I don't know what "taking a break" actually means, I mean how long (minutes, hours). We've noticed that the lock icons immediately disappeared once the laptop is in sleep mode. We did not wait too long.

**Comment by eviljeff** [comment]
There isn't really a way to differentiate the tab being closed (i.e. the reviewer isn't reviewing this add-on any longer) and the computer/Firefox being closed/suspended so the lock icon won't be there until Firefox is up and running again.  That is resumes when the reviewer is using their Firefox again was the expected outcome from comment#0.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-436
