### ISSUE TITLE
Reason and url won't update for auto sign off delayed blocksubmission

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20930]
Caused by https://github.com/mozilla/addons-server/issues/20888

Versions delayed for auto sign-off ->  Going on[ Edit submission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/605/change/) I tried to edit  Url or Reason -> don't seem to work after I update, fields are empty.

Notes:
Disable add-on is updated accordingly

**Comment by ioanarusiczki** [comment]
This is also reproducible for a version Pending sign-off.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I've noticed the following: 

1. an update on a [delayed sign-off](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/633/change/) without other versions already blocked -> when I previously had `url` and `reason` and I un-check `Update url value` and `Update reason value` -> the previous content is deleted instead of still being available

2. an update on a [delayed sign-off](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/639/change/) but the add-on had already a blocked version together with `url` and `reason` edited-> I cannot update the fields, I'll keep seeing the input belonging to the blocked version. 

3.  Same behavior as described at 2. is present for an update on a [pending sign-off ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/635/change/ ) In this case only the `reason` field won't update because the `url `wasn't edited for the block created on versions before this one.

4. [Already blocked versions](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D&) not being delayed for sign-off or not pending sign-off-> when updating metadata, there's no "Update url value" or "Update reason value" next to the checkmark, it's just "Url "and "Reason" and the metadata update can be done only from  "Update add-on block" button (from rev tools). 

Let me know what's the expected behavior. I think 1, 2 and 3 are not expected. And if 4 should have  "Update url value" and "Update reason value" too.

**Comment by eviljeff** [comment]
> @eviljeff
> 
> I've noticed the following:
> 
>     1. an update on a [delayed sign-off](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/633/change/) without other versions already blocked -> when I previously had `url` and `reason` and I un-check `Update url value` and `Update reason value` -> the previous content is deleted instead of still being available

This is as expected - you're changing the submission to not update url and reason in the blocks, so the submission will have no url or reason.  

However, the checkboxes should default to the current state of the submission - right now they seem to always be checked so if you purposely uncheck them so the block's existing url & reason aren't written over, save, then come back to update the submission you can accidentally leave the submission in a state where the the block's url & reason are wiped.

>     2. an update on a [delayed sign-off](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/639/change/) but the add-on had already a blocked version together with `url` and `reason` edited-> I cannot update the fields, I'll keep seeing the input belonging to the blocked version.

That's a bug.

>     3. Same behavior as described at 2. is present for an update on a [pending sign-off ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/635/change/) In this case only the `reason` field won't update because the `url `wasn't edited for the block created on versions before this one.

I'd imagine it's the same underlying cause as 2.

>     4. [Already blocked versions](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D&) not being delayed for sign-off or not pending sign-off-> when updating metadata, there's no "Update url value" or "Update reason value" next to the checkmark, it's just "Url "and "Reason"

I see checkboxes next to reason and url, just a more compact layout without the labels.

> and the metadata update can be done only from  "Update add-on block" button (from rev tools).

Can you expand on this statement?
 
> Let me know what's the expected behavior. I think 1, 2 and 3 are not expected. 

1 seems as expected, but the checkboxes don't have the correct defaults. 2 and 3 are broken - can you file a follow-up? 

> And if 4 should have "Update url value" and "Update reason value" too.

If it's just that the labels aren't there, then it's as expected - I didn't _want_ the labels but it's harder to style the page you see after the submission has been created so you just see the default admin layout.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I'll try to explain. 

> Can you expand on this statement?

An already blocked add-on when starting from admin tools: 

From [/models/blocklist/block/ ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/) -> when I go to the blocked guid and open the submission I land on 
[blocklist/block/26382/change/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26382/change/ ) where there is no possibility to edit anything except for un-blocking (Delete button is on the right side of the page)

OR from /[models/blocklist/blocklistsubmission/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/?signoff_state=all)  I have 2 entries for this guid: [/blocklistsubmission/636/change/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/636/change/?_changelist_filters=signoff_state%3Dall) and [/blocklist/blocklistsubmission/637/change/](
https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/637/change/?_changelist_filters=signoff_state%3Dall
) -> clicking one these entried I see Edit Block and I'll click it to open [/blocklist/block/26382/change/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26382/change/)

To edit metadata -> I must click on ["Review unlisted"](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625844) link to be redirected to rev tools. Then click “Update add-on blocks” button, land on [/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D&](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D& ) where I can finally edit metadata.

About the un-checking:

There's 2 different behaviors , the already blocked versions when there is content for url and reason (I simply added "test") and I un-check them and save -> [“test” is still there when I return to edit](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D&). Deleting or removing the previous content can be done by leaving the check-marks and simply deleting “test” then save.

On the other hand, for delayed sign-offs , un-checking and saving has the role of deleting the previous content.  Reason why, I thought that this is a bug.

**Comment by eviljeff** [comment]
> @eviljeff
> 
> I'll try to explain.
> 
>     1. > Can you expand on this statement?
> 
> 
> An already blocked add-on when starting from admin tools:
> 
> From [/models/blocklist/block/ ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/) -> when I go to the blocked guid and open the submission I land on [blocklist/block/26382/change/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26382/change/) where there is no possibility to edit anything except for un-blocking (Delete button is on the right side of the page)
> 
> OR from /[models/blocklist/blocklistsubmission/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/?signoff_state=all) I have 2 entries for this guid: [/blocklistsubmission/636/change/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/636/change/?_changelist_filters=signoff_state%3Dall) and [/blocklist/blocklistsubmission/637/change/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/637/change/?_changelist_filters=signoff_state%3Dall) -> clicking one these entried I see Edit Block and I'll click it to open [/blocklist/block/26382/change/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26382/change/)
> 
> To edit metadata -> I must click on ["Review unlisted"](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625844) link to be redirected to rev tools. Then click “Update add-on blocks” button, land on [/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D&](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D&) where I can finally edit metadata.

https://github.com/mozilla/addons-server/issues/20851 is for re-implementing the edit functionality, but you should be able to "edit" an existing block by just creating a submission that contains that guid.  (that's what was happening in the background before anyway

> I forgot here the most important part, to edit metadata for auto-delayed or pending sign-offs it's easier to access it, from /models/blocklist/blocklistsubmission/ I click the [submission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/639/change/?_changelist_filters=signoff_state%3Dall) and I can update url and reason.

I'm not clear what you're saying is unexpected/broken here.

>     2. About the un-checking:
> 
> 
> There's 2 different behaviors , the already blocked versions when there is content for url and reason (I simply added "test") and I un-check them and save -> [“test” is still there when I return to edit](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D&). Deleting or removing the previous content can be done by leaving the check-marks and simply deleting “test” then save.
> 
> On the other hand, for delayed sign-offs , un-checking and saving has the role of deleting the previous content. Reason why, I thought that this is a bug.

_One_ of the behaviours is a bug as far as I'm concerned ... but there's no UX person to design how it's _supposed_ to work.

**Comment by ioanarusiczki** [comment]
@eviljeff 

> I'm not clear what you're saying is unexpected/broken here.

My point was that there are again 2 different behaviors when editing metadata:

The already blocked versions -> edit can be done from https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B81933f67-733c-4217-8b54-768019a51bed%7D& which can be accessed from the [reviewer's pages](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625844)

The versions with delayed auto-approvals (or pending sign-offs) -> it's simply by going to https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/639/change/?_changelist_filters=signoff_state%3Dall in the blocksubmission module

But that's alright because after https://github.com/mozilla/addons-server/issues/20851 lands it's going to be fixed for blocked versions too because as I see, for the other categories the correct behavior is already happening. 

> One of the behaviours is a bug as far as I'm concerned ... but there's no UX person to design how it's supposed to work.

What if the check/un-check has no good role here. Without check marks:
1. when you want to keep the current metadata you simply don't change anything 
2. when you want to delete it can be done by simply clearing the previous input , leaving the fields empty 

With checkmarks:
-> un-checking url and metadata would keep the previous content for blocked versions
-> un-checking url and metadata would delete the previous content for delayed sign-off (meanwhile delete can also be done as described at 2.)

**Comment by eviljeff** [comment]
> What if the check/un-check has no good role here. Without check marks:
> 
>     1. when you want to keep the current metadata you simply don't change anything
> 
>     2. when you want to delete it can be done by simply clearing the previous input , leaving the fields empty

For a single guid in a submission that isn't being delayed (or needing sign-off) you don't strictly need the checkbox, correct, because we prefill the field with the existing value, and you can clear the value by clearing the textfield.  But with delayed/sign-off submissions the "existing" value isn't clear.  (Example: Block with reason='a'; delayed submission with reason=''; you create a new submission - if you leave the reason as 'a' the Block will either end up with a reason of  `a` or `` depending on the order the submissions are published.  You can't say "just don't update the reason")  And a submission that has multiple guids could have different existing values, and you may not want to replace all the existing reasons/urls with the same value or clear them.

**Comment by ioanarusiczki** [comment]
@eviljeff 

It took a while understanding the logic but I think I understand what you said. 

I tested on 2 versions, 1 blocked with "reason a" , then the next version delayed blocked and I un-checked the url and reason. 

After the delay expired the frontend would display "reason a" 

https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7Bc98d5319-80ef-44d5-837c-42386378fac0%7D/ 

I'll mark this verified on AMO dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-435
