### ISSUE TITLE
Update url field correctly when the url is deleted

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20935]
1. Go to a [blocksubmission](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B58f187d8-c3b8-4098-be5e-f736769d7f88%7D&) from rev tools with the "update add-on block" button 
2. Update metadata like this: leave the check marks on url and reason but delete the previous input
3. Save

Expected: 
The url and reason fields stay blank

Actual result: 
Only reason is updated correctly. Url still has the previous content in the field 

 This is the [add block ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/?guids=%7B58f187d8-c3b8-4098-be5e-f736769d7f88%7D&) and the [frontend page ](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B58f187d8-c3b8-4098-be5e-f736769d7f88%7D/)  where url should no longer be displayed

**Comment by ioanarusiczki** [comment]
@eviljeff 

This is verified on AMO dev. 

[Block History ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26378/change/) and [frontend page](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B58f187d8-c3b8-4098-be5e-f736769d7f88%7D/)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-438
