### ISSUE TITLE
Remove serif fonts from submission complete page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2093]
E.g:

<img width="587" alt="submission_complete____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14171071/e2c489fe-f728-11e5-82dd-0fa5a204c9a3.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![san2s](https://cloud.githubusercontent.com/assets/1583842/14246397/7f85cfde-fa6f-11e5-8e08-1ad4f926e393.png)
