### ISSUE TITLE
Login email box looks like it has incomplete styling.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2094]
See https://addons-dev.allizom.org/en-US/firefox/users/login?to=%2Fen-US%2Ffirefox%2F

<img width="720" alt="user_login____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14171181/89e990da-f729-11e5-8205-703bc3c7cae3.png">

**Comment by muffinresearch** [comment]
Would be best to get UX input for this. 

@pwalm @designakt - do you have some thoughts on what this should look like?

**Comment by muffinresearch** [comment]
Just deleting the backgrounds and borders within the box gets you something like this:

<img width="515" alt="user_login____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14214411/cc75064e-f834-11e5-8102-1a4e0c10e706.png">

I took a stab at that and the PR is here: https://github.com/mozilla/addons-server/pull/2154

**Comment by ValentinaPC** [comment]
The Login, Register and "I don't have an account" pages where style refreshed.
Verified on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-04_1011](https://cloud.githubusercontent.com/assets/15685960/14240479/e7e6429c-fa4d-11e5-88f8-e7ee95ad253f.png)

But, the "I forgot my password" is still old school. 
Please see the screenshot:
![preset](https://cloud.githubusercontent.com/assets/15685960/14240502/06940fee-fa4e-11e5-8a44-b98cb5b0b627.png)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-12_1600](https://cloud.githubusercontent.com/assets/15685960/14460730/c36d6d2a-00c7-11e6-8dbf-5d9aeb0e0ad7.png)
