### ISSUE TITLE
optimize how we create activity logs for BlocklistSubmission -> Block saves

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20948]
Follow-up from https://github.com/mozilla/addons-server/pull/20932#discussion_r1252263002

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO Dev -> when multiple versions are blocked or un-blocked there's a single entry registered in [Activity log](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/)

![activity log blocklist](https://github.com/mozilla/addons-server/assets/33448286/c85e7e39-2498-4521-b715-25354d0f1561)

![activity log delete](https://github.com/mozilla/addons-server/assets/33448286/98f7af20-d751-44ef-90b5-e6e0d22a7067)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-443
