### ISSUE TITLE
Enforce 2FA at extension upload time

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20943]
A while ago we started [enforcing 2FA at login for developers](https://github.com/mozilla/addons-server/issues/10046). This is however a bit confusing because it's only enforced on the first login after they have become an extension developer, which could be a long time after their upload. We want to start doing that directly when someone begins the extension upload flow (*) so that it's all consistent and all developers eventually have 2FA enabled from the start, and not just after their second login.

Theme developers (that don't also have/try to submit extensions) continue to be exempted from this.

Depends on https://github.com/mozilla/addons-server/issues/20942 (note: even once that issue is implemented the upload stage will likely be shared between extensions and themes, so we'll probably have to check for 2FA on the pages before but also before validation, in the `handle_upload()` code or nearby)

(*) Or requests API keys.

**Comment by diox** [comment]
When someone logs in, record in the session whether they had 2FA enabled when they logged in. Then, when going to a view with 2FA enforcement:
  - If they didn't have 2FA at log in, redirect them to the authentication flow with something stored in the session asking them to set it up. Need to make sure they are redirected back to the right page after.
    - If somehow they enabled 2FA on FxA side after logging in then it's fine: the authentication flow will redirect them to our protected page.
  - If they did, they can go through.
      - If somehow they disabled 2FA on FxA side after logging in then it's fine: they did log in with 2FA, so they had it at some point, and they won't be able to log back in again without it

Views that need enforcement:
  - All steps (or at least, initial agreement and upload page) of the extension (not theme) submission flow
    - Upload view that triggers validation (hit by XHR when the user selects an xpi in the upload page)
  - API key page

**Comment by diox** [comment]
This is blocked by https://github.com/mozilla/addons-server/issues/21002. There are some interesting edge cases to test around trying to be authenticated with different accounts on each side (FxA, AMO), with and without 2FA enabled - it's fine to end up with a different account than the one we started with, as long as everything is consistent.

**Comment by vcarciu** [comment]
Verified as fixed on AMO-dev. Users are asked for 2FA when trying to submit a new addon. 2FA is not enforced for themes.
We will mark this as verified after testing it on Stage too.

**Comment by ioanarusiczki** [comment]
@diox 

I've 3 notes to make after looking over -dev today, I hope all scenarios are expected:

- themes submitted from the addon submission flow with  https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed -> will require 2FA

- login with an account without 2FA and then I enabled it from the fxA page -> I'll keep having the error at submission until I log out and then back in. The same if I do the opposite, I disable 2 FA while the user has a login on AMO -> I won't receive the error that I should enable it again until I made a log out from the current session. 

- I had a login with my admin account with 2FA enabled and I get the error at submission that I should enable 2FA but after log out and login it is no longer reproducible . Also, I did not reproduce it with the same account on a new profile. 

![with admin account on default profile](https://github.com/mozilla/addons-server/assets/33448286/7a21e427-a711-4068-8bda-53cfc3db200f)

**Comment by ioanarusiczki** [comment]
@diox I forgot to add the API scenario -> it doesn't throw an error when using the new submission API.

**Comment by diox** [comment]
mmm you shouldn't see this error - you should have been redirected to FxA when accessing the upload flow to add 2FA, then redirected back to the upload flow. Something must be broken.

**Comment by ioanarusiczki** [comment]
@diox Actually when I enable 2FA from fxA after I login to AMO, I see the error , I click it and then it would only require a login and I'm back to the submission page. I think it's what you[ described above](https://github.com/mozilla/addons-server/issues/20943#issuecomment-1632210340)

**Comment by diox** [comment]
The two scenarios for the extensions submission page should be:
- User doesn't have 2FA yet. When they go to the submission page, they should be redirected to FxA where they should be forced to set up 2FA to continue. When they finish setting it up they should be redirected to the flow which should work as normal.
- User had 2FA at login time already. When they go to the submission page, it works as normal

For this it doesn't matter what they do in Firefox Accounts after login.

The `Please add two-factor authentication to your account to submit extensions` message should be almost impossible to trigger. User would need to start the flow with 2FA enabled, reach the page where they select the xpi, then in a different tab, log out of AMO, disable 2FA on FxA, log back in to AMO without 2FA, and go back to the tab with the submission page and pick a xpi.

**Comment by ioanarusiczki** [comment]
@diox 

> User would need to start the flow with 2FA enabled, reach the page where they select the xpi, then in a different tab, log out of AMO, disable 2FA on FxA, log back in to AMO without 2FA, and go back to the tab with the submission page and pick a xpi.

Interesting result when I tried it, it's not `Please add two-factor authentication to your account to submit extensions` but I hit another error:

![not responding](https://github.com/mozilla/addons-server/assets/33448286/6234f131-43f2-460f-9c5b-4d20800e8431)

**Comment by diox** [comment]
Are you sure you logged back in before submitting, and with the right user if it's an existing add-on you're submitting a new version on ?

Also, do the "normal" scenarios described above in that same comment work ?

**Comment by ioanarusiczki** [comment]
@diox 

I get the error every time before uploading a new addon, I tried again the scenario with Sandbox. 
Also, after a page refresh I'll get `Please add two-factor authentication to your account to submit extensions` and I can continue the process. 

STR: 
1. I login with an account with 2FA 
2. I go to https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed 
3. In a different tab I logout AMO
4. In a different tab I disable from fxA page the 2FA
5. Going back to the page opened at 3. and login
6. Going back to the page from 2. and upload an xpi 

> Also, do the "normal" scenarios described above in that same comment work ?

They work as expected.

**Comment by diox** [comment]
Ok, I see why you had a 403 without refreshing: when you log out, any form submission on AMO devhub/reviewer tools/admin in tabs you have already opened won't work and require a refresh (behind the scenes tech stuff: CSRF token is tied to the session and so it rotates on logout). It's an expected security feature.

Since you got the expected error after a refresh, and the other scenarios work, I think we're good.

**Comment by ioanarusiczki** [comment]
@diox 

I tested on AMO stage the scenarios below and I think they work as expected: 

1. waffle off, user doesn't have 2FA enabled

 They are able to log in as normal without 2FA
 They are able to complete the upload flow as normal (extension or theme doesn't matter)

2. waffle off, user has 2FA enabled

They are able to log in as normal with 2FA
They are able to complete the upload flow as normal (extension or theme doesn't matter)

3. waffle on, user doesn't have 2FA enabled

They are able to log in as normal without 2FA
They are redirected to set up 2FA when starting the extension upload flow, then they can complete it as normal
They are able to complete the theme upload flow as normal

4. waffle on, user has 2FA enabled

They are able to log in as normal with 2FA
They are able to complete the upload flow as normal (extension or theme doesn't matter)

5. the addon validator - is working as expected , 2fa is not triggered on this page

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-441
