### ISSUE TITLE
Split themes and extensions submission initial page

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20942]
At the moment the themes and extensions (+ dicts/langpacks) use the same initial page, where you can choose to either upload a xpi or use the theme wizard. This is super flexible to users, albeit slightly confusing perhaps.

We want to make changes to the extension submission flow without affecting theme developers, so we'll need to split the themes from the rest. The 2 cases (themes / rest) will have different URLs, slightly different "landing" page, which will look similar but will allow us to customize separately.

- On the extension page, the theme wizard should not be displayed, only the xpi upload should be present.
- On the theme page, the theme wizard and xpi upload should be present
- For backwards-compatibility, the old URLs should still work and be used for the extension (+ dict/langpack) flow.
- See also https://github.com/mozilla/addons-server/issues/20966

**Comment by ioanarusiczki** [comment]
@diox 

On AMO Dev: 

- the themes wizard has been removed when submission is made from "Submit a New Add-on" 
- theme submission has a new url https://addons-dev.allizom.org/en-US/developers/addon/submit/theme/upload-listed or 
https://addons-dev.allizom.org/en-US/developers/addon/submit/theme/upload-unlisted and have both options available: upload using an xpi and the theme wizard.
- the old urls are still being used for extension, lang pack and dictionary submissions 
https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed or
https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-unlisted

- I've checked the submission buttons on frontend 
and dev hub:
https://addons-dev.allizom.org/en-US/developers/
https://addons-dev.allizom.org/en-US/developers/addons ( on the right side and in Tools)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-440
