### ISSUE TITLE
pass all required context in BlocklistSubmission.add_view

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20950]
In django4.2 there are extra context values passed on to the admin templates which we don't pass so the logs are filled with template rendering errors.  The page is still functional, though looks like the collapsible sidebar is missing.  We should either pass on all the required values, or craft a way to use the `super` functions so we're not reliant on keeping the kwargs up to date with django admin.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Not sure what to check for this issue. 
I filed https://github.com/mozilla/addons-server/issues/20998, could it be a regression caused by this?

**Comment by eviljeff** [comment]
> @eviljeff
> 
> Not sure what to check for this issue. I filed #20998, could it be a regression caused by this?

It is,  (I noticed it myself while working on another patch today and thought it was weird it was only just happening to me)  Note, it may be hiding another problem - it only seems to happen when the form has a validation error to show.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I did not notice other issues while checking blocks on AMO Dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-444
