### ISSUE TITLE
Attribute "Previous version ... had needs human review set" activity to task user

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#20953]
### Describe the problem and steps to reproduce it:

In the reviewer tools, version review history...

### What happened?

...the activity "Previous version in channel had needs human review set" is attributed to the developer account.

### What did you expect to happen?

It should be attributed to the Mozilla Firefox task user.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
In `NeedsHumanReview.save()` we use the current user if available, which is great, but in that case we need to override it. (Called from https://github.com/mozilla/addons-server/blob/5b506fb88f0df193add4b9c6af4a6c45b2919b48/src/olympia/versions/models.py#L449C1-L451C18)

**Comment by wagnerand** [comment]
Thank you for the pointer, I'll take a stab at it.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-445
