### ISSUE TITLE
optimize MLBF generation so it can actually finish

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#20955]
`fetch_blocked_from_db `executes a query that returns `BlockVersion` instances, but then accesses fks to `Block` and `Version` for each instance - effectively executing an extra 2 queries for every blocked guid.  On dev and stage there were sufficiently few blocks that we didn't notice; on prod not so much.  The generation cron usually takes 2-3 minutes (according to statsd pings recorded in grafana); last night it took over an hour.  Considering we run this cron 4 times a day this is way too slow and puts an unacceptable strain on the database - if it doesn't entirely timeout.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-446
