### ISSUE TITLE
Prevent uploading extensions using the theme-specific submission flow

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20966]
Follow-up for https://github.com/mozilla/addons-server/issues/20942

If you upload a non-theme on the theme page (or a theme to the extension page? less problematic, maybe we don't care), display an error linking to the right page instead.

**Comment by diox** [comment]
> or a theme to the extension page? less problematic, maybe we don't care

I left that working. It could be useful as a backwards-compatibility measure for people who bookmarked old URLs, and it doesn't cause the issues submitting an extension using the theme page would.

**Comment by ioanarusiczki** [comment]
@diox 

1. The error message is displayed when extensions, dicts or lang packs are submitted from 
https://addons-dev.allizom.org/en-US/developers/addon/submit/theme/upload-listed

![not a theme](https://github.com/mozilla/addons-server/assets/33448286/c996de51-0ca2-4b7c-afca-0000f4c0eef1)

"Submit a new add-on" redirects to https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed or upload-unlisted, depending on what the developer has chosen. 


2. Themes can be submitted from extension's (old) url

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-449
