### ISSUE TITLE
Serif subtitles should be sans

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2096]
https://addons-dev.allizom.org/en-US/firefox/search-tools/dictionaries-encyclopedias

Layout looks a little wonky too.

<img width="277" alt="dictionaries___encyclopedias____search_tools____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14171989/d2d4c63a-f72d-11e5-8e78-6b674e33bd8a.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![sans](https://cloud.githubusercontent.com/assets/1583842/14210280/fc00df68-f830-11e5-86e2-5df10b9a71ec.png)
