### ISSUE TITLE
Metadata is not updated in delayed sign-offs when there's already another version blocked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20979]
Followup https://github.com/mozilla/addons-server/issues/20930#issuecomment-1629022874

 An update on a [delayed sign-off](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/639/change/) but the add-on had already a blocked version together with `url` and `reason` edited-> I cannot update the fields, I'll keep seeing the input belonging to the blocked version. 

Another example: an update on a [pending sign-off ](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/635/change/ ) In this case only the `reason` field won't update because the `url `wasn't edited for the block created on versions before this one.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-451
