### ISSUE TITLE
Abuse reports are not counted correctly for addons with multiple GUIDs

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#20977]
### Describe the problem and steps to reproduce it:
From #20870 

I have a question regarding Abuse reports count for addons that have changed GUIDs.
We have this example on -dev - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/616918. This addon has two GUIDs: Original Add-on ID - {4ee72572-bb01-4731-921c-7f20c6556b35} and new Add-on ID - [1b2383b324c8520974ee097e46301d5ca4e076de387c02886f1c6b1503671586@pokeinthe.io](mailto:1b2383b324c8520974ee097e46301d5ca4e076de387c02886f1c6b1503671586@pokeinthe.io). However, if I'm looking at the [Abuse Reports count](https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/616918) on the Review page, it looks like we only count those submitted for the old GUID. I've checked in the Admin Abuse reports lists for both GUIDs and we should have over 100 reports for the combined GUIDs.

**Comment by eviljeff** [comment]
Add-ons can't change GUIDs** - the code is to support multiple add-on instances that had the same guid, i.e. when an add-on is deleted and then resubmitted with the same guid.  So the older deleted add-on instances would have a current guid of `None`, but the original Add-on ID would be what they were submitted with. Though we no longer allow guids to be reused any longer.

**At least I hope they can't! 😨

**Comment by eviljeff** [comment]
I'm going to close this as invalid because it's a scenario that wouldn't happen.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-450
