### ISSUE TITLE
[Editor Tools] The option "Clear more info requested flag" is not working

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2097]
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/firefox/
2. Go to Editor Tools https://addons.allizom.org/en-US/editors/
3. "Request more information" for an add-on
4. Remove the flag (click the checkbox to clear the flag in add-on review page)

Expected results:
The flag is removed.

Actual results:
The flag is not removed.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screencast for this issue: http://screencast.com/t/eauBZ7Sy

**Comment by eviljeff** [comment]
It only gets cleared if you add a comment.  
This  [commit ](https://github.com/mozilla/addons-server/commit/a3416de8d62db41ca8d8a898d0477f26c9bd2c5f) added it and the commit seems to match the requesting [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1117329).  @jvillalobos anything to do here?

**Comment by jvillalobos** [comment]
If the reviewer clicks on "clear flag", I think it should do so regardless of the review action. The only exception would be when sending a new info request. CC @wagnerand who filed the original bug.

**Comment by eviljeff** [comment]
well, really its only the sending the new info request case that would need to be changed anyway - the others clear the add-on from the queue so it's irrelevant after.

**Comment by jvillalobos** [comment]
But if a new version is submitted the flag will still be there, no?

**Comment by eviljeff** [comment]
afaik its a per version flag and not inherited (someone else can confirm)

**Comment by wagnerand** [comment]
> afaik its a per version flag and not inherited (someone else can confirm)

Correct.

**Comment by eviljeff** [comment]
@jvillalobos can you confirm what should be changed here, or close the issue?
Current:
comment -> clears flag
info -> doesn't but "exception would be when sending a new info request"
approve/reject -> doesn't but irrelevant because current version won't show in queues anymore; new version won't have flag.
admin review -> doesn't clear... edge case?

**Comment by jvillalobos** [comment]
Sounds like there's nothing to do here.

**Comment by wagnerand** [comment]
Wait, why would we clear the need-info flag when a reviewer leaves a comment without actually ticking the "clear need-info" checkbox?

**Comment by eviljeff** [comment]
> Wait, why would we clear the need-info flag when a reviewer leaves a comment without actually ticking the "clear need-info" checkbox?

Is that what happens?

**Comment by wagnerand** [comment]
I interpreted https://github.com/mozilla/addons-server/issues/2097#issuecomment-219401850 that way.
