### ISSUE TITLE
Comment is persisted when clearning pending rejections even if the reviewer doesn't see the comment

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#20980]
### Describe the problem and steps to reproduce it:
When clearing rejections on an add-on, if the reviewer first selects a different tab (like `approve`) before moving to clearing pending rejections, the clearing of pending rejections gets the message from the `approve` tab. 

### What happened?
- Go to review details page of an add-on that has rejection pending
- Go to the `approve` tab. Add message "XYZ" 
- Go to the `clear pending rejections` tab and select the versions to clear rejections
- Click Send
<img width="395" alt="image" src="https://github.com/mozilla/addons-server/assets/6270406/4160f500-6cbf-4ed0-821c-1a03967a23c9">

### What did you expect to happen?
- The `clear pending rejections` should have either no comments (if there's no comment field, like is the case now) or its own comment field. It shouldn't persist comments from other tabs which are not visible when the reviewer clears pending rejections

### Additional details
I guess it doesn't matter all that much if the developer doesn't see this message, still thought I'd write this down here as it is a bit confusing.

**Comment by diox** [comment]
> I guess it doesn't matter all that much if the developer doesn't see this message, still thought I'd write this down here as it is a bit confusing.

I haven't tested this scenario but I think the developer will see the message.

**Comment by diox** [comment]
Reviewer tools comment field is shared across all actions, and should be reset when you switch actions. I guess it's not reset for actions where the comment box is hidden, and we use the data if submitted. We should ensure it's cleared and even if submitted not used for those actions.

**Comment by abhn** [comment]
> I think the developer will see the message

@diox if that's the case, it is higher priority from our side than what I originally assumed. 

Yep, resetting on tab change irrespective of if the field is displayed makes sense to me

**Comment by diox** [comment]
After double-checking: it seems I was wrong, we don't currently clear the comments box contents when switching actions - but it's less of an issue when the comment box is displayed, of course, as the reviewer can see and correct the contents.

So the least intrusive thing to do is probably to completely ignore comments on actions that are not supposed to have them. 

In fact, various actions already have a hack for this:
https://github.com/mozilla/addons-server/blob/036d18728ea5b548f29d9b77970de3ff85405ec1/src/olympia/reviewers/utils.py#L1151-L1155
https://github.com/mozilla/addons-server/blob/036d18728ea5b548f29d9b77970de3ff85405ec1/src/olympia/reviewers/utils.py#L1178-L1181
https://github.com/mozilla/addons-server/blob/036d18728ea5b548f29d9b77970de3ff85405ec1/src/olympia/reviewers/utils.py#L1517-L1518

We should do this in a centralized way for all actions that don't have comments.

**Comment by abhn** [comment]
Yep, true. I've noticed it but didn't mention in my message. 

When going from "approve" to "reject" tab, the message is persisted, requiring reviewers to clear and type out the canned text (eg. "this add-on didn't pass the review because: ") manually. 

Like you noted, not a big issue when it is displayed (mildly annoying tho) but surely a problem when it is hidden. If we can just reset the state to the default state with default text when switching tabs, that could make both issues go away. 

(I hope we're not relying on the comment persisting behavior /cc @wagnerand for visibility)

**Comment by wagnerand** [comment]
> If we can just reset the state to the default state with default text when switching tabs, that could make both issues go away.

We can do that, but we should be intentional about this change. What if you wrote a long review message and then mis-click, for example? And what should happen to the review reasons?

In addition to that, we should also just ignore the data on the server side in any case, if we are not showing the textbox, to be on the safe side.

**Comment by diox** [comment]
Yeah the simplest thing to do is probably just to ignore the comments on the server side. As I pointed out above we already do for most actions, it's just for the clear pending reviews actions that we currently don't.

**Comment by diox** [comment]
QA: comments entered from another action should not be recorded in actions that don't display the comment box (confirm auto-approval, content approve, unreject, confirm multiple versions, clear needs human review, clear pending rejection).

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev for all the reviewer actions enumerated above and I did not find an instance where comments were submitted with actions that don't require a comment after previously having an action with a comment section selected. The Review history in DevHub Manage versions page is also reflecting this. 

![firefox_gxPcBwvLyG](https://github.com/mozilla/addons-server/assets/31961530/5c745744-e4ae-4f9d-99d2-ecdd3e3ba8cd)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-452
