### ISSUE TITLE
Sprites are missing on the buttons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2098]
I changed some paths which work locally but not in the deployed version.

<img width="581" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14174597/3fa6382a-f73d-11e5-8126-f14525043f4a.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-01_1015](https://cloud.githubusercontent.com/assets/15685960/14200323/c10875ee-f7f2-11e5-8683-4fc7fdb3cbd7.png)
