### ISSUE TITLE
Allow GitHub sponsor popup in contributors field

### ISSUE THREAD

**Issue by filips123** [mozilla/addons-server#20988]
### Describe the problem and steps to reproduce it
Along with GitHub Sponsors (as a donation service), GitHub also supports a donations popup that is linked to a specific repository and allows displaying multiple donation options (GitHub Sponsors, Patreon, Liberapay, etc.). This popup can be displayed by clicking on the sponsor button on the repository page or adding `?sponsor=1` to a repository URL.

### What happened?
Because AMO has [a validation](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/forms.py#L300-L304) that GitHub URLs must start with `/sponsors/`, adding that sponsor popup is not possible.

### What did you expect to happen?
Adding a sponsor popup should be possible, as it allows developers to link multiple donation services. This is useful as some users might prefer donation services other than that one main service that the developer links on AMO.

### Anything else we should know?
I don't know if GitHub officially supports `?sponsor=1` as a way to open sponsor popup, but it's used [quite often](https://github.com/search?q=%22%3Fsponsor%3D1%22&type=code) in various repositories. It might be good to check if this is actually documented and supported feature, to prevent these links from breaking if GitHub changes this.

Another thing that might be undesirable is that I think that GitHub allows submitting any URL as a donation service, which might be used to circumvent AMO domain checks.

In case this is undesirable, an alternative is to allow adding multiple donation URLs directly to AMO and then display all of them to the user, maybe just as a list of URLs or in a popup, similarly to how GitHub handles this, but with validation. And actually, I think this is useful even if GitHub sponsor popup is added, as it removes an extra step and third party before the user can see all donation URLs. I can open another issue specific to this if needed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-454)

**Comment by eviljeff** [comment]
Hello, after some discussion about this feature we've decided not to implement it at this time.  

We can see the advantages, but it brings some risks around exposing additional, unvetted (by Mozilla), websites to users, and it's not clear how used it it would be - this is the only issue requesting it.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-454
