### ISSUE TITLE
Enable auto-approval on both channels for extensions in Notable group

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20991]
Since https://mozilla-hub.atlassian.net/browse/AOP-133 we no longer want to pre-review all versions of extensions in the Notable group introduced in https://github.com/mozilla/addons-server/issues/19976 (further refined in https://github.com/mozilla/addons-server/issues/20351). Instead the versions will be flagged for human review and put in the manual review queue for post auto-approval review.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-455)

**Comment by diox** [comment]
An important point to consider: we want to automatically flag for human review existing notable versions currently waiting for review in a data migration. Otherwise when we land this, they would be auto-approved and be removed from the queue, as they were not explicitly flagged, they are just currently in the queue because of the rules around notable.

**Comment by diox** [comment]
We have not reached a clear decision on this so I'm closing the ticket.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-455
