### ISSUE TITLE
server error when creating a partial block using multiple guids

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#20998]
From admin go to [Add block](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/add/)
Add minimum 2 guids and Submit
On the [/blocklistsubmission/add/](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/add/) page deselect all versions belonging to a guid
Save

Result:
Oops! We had an error. -> 500

Notes:
I could not reproduce it on -stage today , here's an [example](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/294/change/?_changelist_filters=signoff_state%3Dall) the scenario worked 
I could not reproduce it when blocking the versions were selected for both guids.

**Comment by eviljeff** [comment]
regression from https://github.com/mozilla/addons-server/issues/20950 - seems to only be apparent when the form has validation errors to show

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and we are displaying an error message now when one or all the GUIDS chosen for a block have all their versions deselected: 

![image](https://github.com/mozilla/addons-server/assets/31961530/6193f0e3-95a8-4d45-8cab-bad6f07d20ce)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-456
