### ISSUE TITLE
Not able to add a new theme owner

### ISSUE THREAD

**Issue by PeopleInside** [mozilla/addons-server#21000]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

I open the theme page
https://addons.mozilla.org/it/developers/themes
then I open the interested theme clicking on the title, manage authors.

Here I see my email address and the rule owner.
I add in the row below a new owner email and press enter.

As soon I insert this account email an error page is showed-

![immagine](https://github.com/mozilla/addons/assets/5006150/40f57818-c67c-4e15-b3c0-958b9c18f419)

**Comment by diox** [comment]
Hi,

- Do you see a new blank field being added after the one for the new user in the page ?
- Do you see a JavaScript error in your browser developer tools console (on Edge, Ctrl+Shift+I should open them) when adding a new owner ? 

It seems there are 2 issues here: 1) client-side, somehow the JavaScript didn't work and we got an incomplete form data 2) we are not handling that properly server-side.

**Comment by PeopleInside** [comment]
First let me say that I tried with two different browser: Firefox and Edge and the issue is the same.
A new field to add the 2 owner email is showed. If I insert an unregistered email address a correct error say the user is not find / registered. If I insert an existing email that has a Firefox account, the error page showed in the screenshot is showed.

As console error I see a 500 error.
![immagine](https://github.com/mozilla/addons-server/assets/5006150/074cddd3-f348-4a23-8b42-4c699e55fdce)

**Comment by ioanarusiczki** [comment]
@PeopleInside as a workaround until this bug is fixed,  you can use en-US and you'll be able to add the new owner. 

When "it" is used in the url, you'll get the error. 

Use `https://mozilla.org/en-US/developers/addon/server-error-test/ownership` instead

**Comment by PeopleInside** [comment]
@ioanarusiczki thank you, good idea ... probably in en will not find the bug or many user I suppose already reported this. Thanks

**Comment by diox** [comment]
This is specific to the italian locale, due to a stray character in a translation string. We'll fix that on our development branch and it'll be pushed at the end of the week.

**Comment by ioanarusiczki** [comment]
@diox 
On AMO dev -> I can no longer reproduce the server error with 
https://addons-dev.allizom.org/it/developers/addon/server-error-test/ownership

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-458
