### ISSUE TITLE
Retry authentication with FxA when we get a error in the callback

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21002]
We currently don't handle FxA errors, the user is redirected back to us, we notice that we can't log them in but do nothing about it.

FxA docs suggest to try again with a new `state` (and without `prompt=none`): https://mozilla.github.io/ecosystem-platform/reference/oauth-details#handling-errors

If FxA is returning bogus errors for some reason (it has happened once or twice in the past) then the user would be stuck in a loop, but it's not worse than being thrown back to AMO with no explanation as to why this happened. Removing the `prompt=none` in this cases gives us a chance for the next attempt to work.

**Comment by diox** [comment]
This is hard to trigger with the current flow, but it will be a potential edge case with https://github.com/mozilla/addons-server/issues/20943, with the following:
1. The user logs in successfully without 2FA enabled
2. They clear all their data on FxA side, log in to a different FxA account but keep their original AMO session (so they are now logged with different accounts on FxA and AMO)
4. They try to access a page with 2FA enforcement active on AMO, which internally triggers a redirect to FxA with `prompt=none` and `login_hint`.

Without handling errors, we'd end up with the user stuck in a loop here, they'd get redirected to our FxA callback with `error=account_selection_required`.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-459
