### ISSUE TITLE
Red\green check marks are missing when adding a new author for an addon

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2100]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to edit listing page for one of your submitted addons
2.Go to Manage Authors&Licence section
3.Try to add a new author

Expected results:
If the email address entered is unknown, a red check mark is displayed and the author cannot be added. Otherwise a green check mark is displayed and the author can be added to the list

Actual results:
There are no check marks available and any email can be added as author even if it is not a valid email

Please see screencast for this bug :  http://screencast.com/t/LqtS7hdbEwg
NOTES: reproducible also on Prod

**Comment by vcarciu** [comment]
After talking with muffinresearch on IRC, I investigated more and this is not reproducible like I said in original scenario. Before, these checkmarks were automatically displayed while writing the email of author. This is not happening anymore, but if I enter an wrong(unknown) email , the red checkmark is correctly displayed AFTER pressing "Save changes" , which is partially correct.

The green checkmark is not displayed at all even for correct emails or after pressing "Save changes"

Another strange thing is that if I enter and delete author emails more times , the author is not saved anymore and an error is displayed: http://screencast.com/t/N2fKYy4sG5c

**Comment by andymckay-limited-access** [comment]
When you click save you get the feedback. I'm suspecting this API was removed to prevent easy enumeration of emails.
