### ISSUE TITLE
addons-server build has been failing since 2023-07-18

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21016]
addons-server build has started failing today: https://app.circleci.com/pipelines/github/mozilla/addons-server/26461/workflows/1a494bce-10df-4b66-8fdf-53581aa07c4d/jobs/165146

```
(...)
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://repo.mysql.com/apt/debian buster InRelease [22.0 kB]
Get:3 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:5 https://deb.nodesource.com/node_16.x buster InRelease [4584 B]
Get:6 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
Get:7 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [541 kB]
Get:8 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
Get:9 https://deb.nodesource.com/node_16.x buster/main amd64 Packages [775 B]
Fetched 8699 kB in 1s (6428 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libmariadb-dev-compat libmariadb-dev

E: Package 'mysql-client' has no installation candidate
E: Package 'libmysqlclient-dev' has no installation candidate
```

We specifically depend on `libmysqlclient-dev` from MySQL and *not* `libmariadb-dev` which has slight incompatibilities with auth and charsets (both problems we encountered in the past when trying to use `libmariadb`). But it looks the today MySQL broke their repos, which in turn broke our build.

This is preventing us from deploying 2023.07.20 tag to stage.

This has been filed as https://bugs.mysql.com/bug.php?id=111786 upstream

**Comment by KevinMind** [comment]
@diox could this be a relevant alternative? Would mean using MariaDB. Would also mean we don't have to locally package mysql which I guess is not very forward compatible if debian stopped shipping it..

Source: https://superuser.com/questions/1479577/install-mysql-client-5-7-on-debian-buster

I'm totally sure how to verify this type of change but could be as simple as:
- read the diff comparing them feature wise
- create some queries or use existing app logic that would test those differences?

This is also something that should be pretty easy to test in dev/stage without risk to prod.

Also.... do we actually use those clients specified in the Dockerfile for production or is there some special magic in our deployment? Is this even a production relevant change?

**Comment by diox** [comment]
As mentioned above:
> We specifically depend on libmysqlclient-dev from MySQL and not libmariadb-dev which has slight incompatibilities with auth and charsets (both problems we encountered in the past when trying to use libmariadb).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-461
