### ISSUE TITLE
Page number is not displayed correctly after navigating between links

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2101]
Steps to reproduce:

1.Open firefox add-ons page: https://addons.mozilla.org/en-US/firefox/
2.Go to “Themes” and from the drop down menu select “Complete Themes”.
3.Select a link from “Sort by” for example “Most Users” and navigate few pages.
4.Select another link from “Sort by” for example “Name”.

Expected results:
User is redirected to first page from the link.

Actual results:
User is redirected to the last page number selected from the previous link..

Note/Issues:
This issue is reproducing in mp-dev and mp-stage and production.
Video to this issue:http://screencast.com/t/RjeCQYiivHX8

**Comment by muffinresearch** [comment]
Going to close this for now, but leave it in the backlog label so we can always come back to it.
