### ISSUE TITLE
Pick of the Month background image looks strage on Chrome

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2102]
![snip_20160331103204](https://cloud.githubusercontent.com/assets/8145891/14179161/fe99a9ae-f72b-11e5-97aa-0e9061300223.png)

We need to redo those images to not have to rely on css image effects to make them fit the design, as we currently do with the pick of the month image.

**Comment by muffinresearch** [comment]
Looks like it will work if it has a webkit prefix added to the filter.

**Comment by muffinresearch** [comment]
@designakt  I'll do that as a quick fix but if you want to cut a new asset we can swap it out.

**Comment by designakt** [comment]
@muffinresearch Where would I get the source files for those images?
Or who would know that?

**Comment by muffinresearch** [comment]
Hmm I'm not sure where that came from originally - @tofumatt any ideas?

**Comment by tofumatt** [comment]
No idea; they predate my involvement with add-ons by a fair bit. Maybe @jvillalobos knows?

**Comment by atsay** [comment]
I don't have the source :-/ only the PNG...

**Comment by jvillalobos** [comment]
No idea.
