### ISSUE TITLE
Addon validator is not working

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#21024]
Steps to reproduce:

1. Go to AMO Stage and login with valid credentials
2. Navigate to developer hub and go to My Addons
3. From Tools , select Add-on Validator
4. Press Select a file and add a valid addon

Expected results:
Validation passed

Actual results:
Your add-on failed validation with 1 error.

    This add-on is not a theme. Use the [Submit a New Add-on](https://addons.allizom.org/en-US/developers/addon/submit/upload-listed) page to submit extensions.

Please see screenshot for this issue:

![32E70253-B584-4D92-AB17-5E14441CB9EC](https://github.com/mozilla/addons-server/assets/1583842/3b64e11b-3d0a-4545-8a69-d712b7dae90c)

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev. Waiting for Stage push to verify it in Stage too.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-463
