### ISSUE TITLE
[WaterFox Classic] The Mozilla site seems less usable now

### ISSUE THREAD

**Issue by decembre** [mozilla/addons-server#21045]
The Mozilla site seems less usable now.
- Click on screenshot don't open them
- "More from this Dev" section  and the Dev page with addons in continuous loading
Test link:
Extension page:
- <a href="https://addons.mozilla.org/en-US/firefox/addon/stylebot-web/?utm_source=addons.mozilla.org&amp;utm_medium=referral&amp;utm_content=hotness">[Stylebot](https://addons.mozilla.org/en-US/firefox/addon/stylebot-web/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=hotness)</a>
Dev page:
- <a href="https://addons.mozilla.org/en-US/firefox/user/1550294/">[Extensions by Ankit Ahuja](https://addons.mozilla.org/en-US/firefox/user/1550294/)

Note:
Trying in different profiles
Testing to solve with (fail to find the good options)
Polly extension
Agent Switcher

**Comment by eviljeff** [comment]
Sorry, we only support Mozilla Firefox and Mozilla Firefox for Android browsers, especially for the user frontend.

**Comment by decembre** [comment]
Thanks.
So...Where i can find help about this problem?

**Comment by decembre** [comment]
> i can reproduce with a new profile, with no extensions installed
And i sent them  a request - [WaterFox Classic GitHub] (no reply yet...) - before asking here:
<a href="https://github.com/WaterfoxCo/Waterfox-Classic/issues/199">[[Waterfox Classic] Mozilla sites less usable: continuous loading for internal elements, and lost of functionnality #199](https://github.com/WaterfoxCo/Waterfox-Classic/issues/199)</a>

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-466
