### ISSUE TITLE
Usage per version on review tools page shows unexpected data

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21065]
### Describe the problem and steps to reproduce it:

For https://reviewers.addons.mozilla.org/en-US/reviewers/review-unlisted/584710...

### What happened?

...the "Top 10 Version ADU" table shows versions that only have few users

### What did you expect to happen?

...the most used versions should be shown.

### Anything else we should know?

@eviljeff said on Matrix: _The response (looking in the network tab) isn't sorted as expected - it's supposed to be ordered by ADU so the js can just take the first 10 results._

**Comment by eviljeff** [comment]
The network tab's JSON view is re-ordering the response - the server view is indeed returning the JSON in the correct order.  So it must be a problem in the js.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I don't see a change on -dev versus -stage for id 495646  on the review pages but the JSON's response is now different - it's a list

-dev 
![facebook on dev](https://github.com/mozilla/addons-server/assets/33448286/1551a994-d8b3-4bb6-82d9-5408d0873773)

- before
![facebook on stage](https://github.com/mozilla/addons-server/assets/33448286/1b0ad8b7-424c-44e2-9fce-c891e10418ea)

**Comment by eviljeff** [comment]
The change to a list was part of the fix - unlike (modern) python, JavaScript doesn't maintain the order of keys in an object .

**Comment by eviljeff** [comment]
it's because the stage links are for add-ons that only have unlisted versions, so the request isn't made.  The request is made for the unlisted review page.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-472
