### ISSUE TITLE
Developer reply does not make a version get a due date

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21087]
We have seen at least two examples where a developer reply does not make the corresponding version get a due date and thus appear in the review queue.

The code that handles this is:
https://github.com/mozilla/addons-server/blob/185aa864d7f6651ef6dd9e77838508d1c6f3360d/src/olympia/activity/views.py#L103-L115

After an investigation, @eviljeff noted the following:
_"that code ... is in the activity API viewset, which is used in devhub.  But emails don't use that viewset and there's no equivalent code there to set needs human review."_

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tried from -dev with a developer account to reply to an address ` reviewreply+5b02628109304498bf96ef8d56fc8622@addons-dev.allizom.org` 

-> I see on the[ review pages the replies](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/619912#review-actions) then the Flagged for human review. The version is then displayed in the Manual Review queue. 

Another example -> [unlisted version](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/621739)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-474
