### ISSUE TITLE
The link from "Works with..." field is not working

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2108]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Open any android addon (https://addons-dev.allizom.org/en-US/android/addon/url-fixer/?src=hp-dl-featured)
2.Press the "View other version" link from "Works with... " field

Expected results:
The other versions are displayed

Actual results:
Nothing happens 

Please see screencast showing the link with issues : http://screencast.com/t/h7PlxPHeh1

**Comment by muffinresearch** [comment]
Hmm this is due to it being in a button which is disabled. I think this shouldn't be a button at all.

**Comment by vcarciu** [comment]
Even if the addons details page is broken (https://github.com/mozilla/addons-server/issues/2192) , I will mark this as verified since the link from this issue is working : http://screencast.com/t/1n54Du2xWAi
