### ISSUE TITLE
[ARUP RATAN

### ISSUE THREAD

**Issue by Arup-dev421** [mozilla/addons-server#21103]
[ARUP RATAN SAMANTA.xlsx](https://github.com/mozilla/addons-server/files/12368464/ARUP.RATAN.SAMANTA.xlsx)
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-478
