### ISSUE TITLE
Turn off activity mails for reviewers

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21101]
part of https://mozilla-hub.atlassian.net/browse/AOP-102

> If a reviewer has done any activity for a particular version, they will automatically receive an email for that version for every
> - reviewer reply (except their own),
> - developer reply,
> - source code submission by the developer.

As we now flag the version for needing human review when a developer replies or submits source code, we don't need to email the reviewers too.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified on AMO dev and I no longer see e-mail being sent forreviewer reply (of other reviewers) , developer replies or source code attached. 

When source code is attached: while a version is pending rejection and the source code is attached then the version is flagged for human review. 

I don't know if that's a real use case: a listed version is awaiting review or an unlisted version is auto-approved then the reviewer is requesting the upload of the source code.  
These are the review pages: 
listed: https://reviewers.addons.allizom.org/en-US/reviewers/review/1014059
unlisted https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1014058

In this case the versions are not flagged for human review and the e-mail is no longer received by the reviewer -> however, they'll be notified on the review page. so I hope it's alright.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-477
