### ISSUE TITLE
Default reviewer subscription to off

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21100]
part of https://mozilla-hub.atlassian.net/browse/AOP-102
> When one or more versions are rejected, the reviewer will automatically subscribe to emails for when new versions are uploaded to the same channel.

Too many emails, so lets default it to not subscribing.

**Comment by ioanarusiczki** [comment]
@eviljeff 

When a version is rejected and then new versions uploaded there was an e-mail sent to the reviewer `You're looking great today! Also, an add-on you previously reviewed was just updated.` 

Also More Actions from the review page has `Notify me about new listed versions` and  `Notify me about new unlisted` versions which can be manually checked -> Before, these would be automatically checked after rejection but it doesn't happen anymore on AMO dev.

When the 2 options are manually checked , e-mails are sent again.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-476
