### ISSUE TITLE
Limit compatibility for non recommended/line extensions on Android to either Fennec or Fenix in DevHub

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21139]
To prepare for the [upcoming general availability of extensions on Firefox for Android](https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/):

- In the version edit page, continue to allow developers to set compatibilty as they see fit, however non recommended/line extensions for Android have to choose:
  - Either they are compatible with Firefox for Android `68.*` max (with whatever min below that). If they choose that option, `strict_compatibility` should be enabled.
  - Or, they are compatible with Firefox for Android `119.0` or `120.0` min (with whatever max above that, probably `*`) and `strict_compatibility` should be disabled if it was enabled.
- On upload (API or DevHub), if Firefox for Android is selected, force non recommended/line extension to be compatible with min `119.0` and max `*` (unless they had strictly chosen `68.*` as their max through `gecko.strict_max_version`, in which case obey that but set `strict_compatibility` like above)
  
This is all to ensure that for now, only users of Fenix `119.0` Nightly/Beta get access to all Android add-ons for testing while non-recommended/line (1) extensions remain non-installable/searchable in Fenix Release versions, until we eventually enable general availability of Android extensions.

(1) Specifically non-recommended/line extensions *for Android*. If an extension is recommended but only for desktop, they get the same restrictions regarding Android compatibility as everybody else.

**Comment by diox** [comment]
Moved the data migration part to https://github.com/mozilla/addons-server/issues/21162

**Comment by ioanarusiczki** [comment]
@diox 

1. Testing from edit version page 
- non recommended/line can set compatibility : min from 10.0a1 to max 78.* or from min 119.0a1 to  max *
 - Strict compatibility flag from file/change admin is enabled for non recommended/line when compatibility is set below 78.* and it is disabled for compatibilities from 119.0a1 above
- recommended and line: any min/max can be set, there are no restrictions and strict compatibility is disabled

2. At uploads

2.1 for non-recommended/line: when Android platform is checked. Strict_min is 119.0a1 to * 
- with gecko_android specified inside manifest.json I used strict_min_version: 119.0, 113.0 and even an interval with strict_min + strict_max -> the compatibility is set to min 119.0a1 to * and is locked -> changes can no longer be done from edit version page. Same if sending a PATCH request , the message is  "Can not override compatibility information set in the manifest for this application (Firefox for Android)"

2.2 For recommended/line
- when Android is checked as platform , compat is set to 48.0 - *
- with gecko_android and strict_min specified: 
strict_min: 113.0 or strict_min:119.0 are set as specified and locked for further changes 
https://addons.allizom.org/en-US/developers/addon/keep-the-app-closed/versions/2493044
https://addons.allizom.org/en-US/developers/addon/1tartle-raccodilla-wombatrid/versions/2493083
-when I chose a strict min: 10.0a1 and strict max:78.* I got this result:
 https://addons.allizom.org/en-US/developers/addon/keep-the-app-closed/versions/2493045 (recommended)
https://addons.allizom.org/en-US/developers/addon/1tartle-raccodilla-wombatrid/versions/2493081 (line)
- another example with strict min: 78.0 and strict max 119.*
https://addons.allizom.org/en-US/developers/addon/keep-the-app-closed/versions/2493079 (recommended)
https://addons.allizom.org/en-US/developers/addon/1tartle-raccodilla-wombatrid/versions/2493082 (line)

Are the last 2 examples expected?

**Comment by ioanarusiczki** [comment]
I forgot to add: 
- recommended for desktop only will get same restrictions as everybody else.
- for non-recommended when the interval 78.0 - 119.* is picked from edit version page it would throw an error Invalid version range. If I sent a PATCH request such as {"compatibility": {"android": {"min":"78.0","max": "119.*"}}} I'll get a 200 response but the with  "compatibility": {
        "android": {
            "min": "119.0a1",
            "max": "*"
        }

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-480
