### ISSUE TITLE
There are addons with duplicate "Add to firefox" buttons

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2113]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Scroll through addons list

Expected results:
All buttons are displayed correctly , without duplicates

Actual results:
There are addons with duplicate "Add to firefox" buttons

Please see screenscast for this bug : http://screencast.com/t/2Mt8VuKoX2J

**Comment by vcarciu** [comment]
Even with 4 duplicate buttons : http://screencast.com/t/tPVhnYZTc85Y

**Comment by muffinresearch** [comment]
Hmm I can't repro this on osx or windows.

**Comment by muffinresearch** [comment]
Aha here's a link that I can repro with: https://addons-dev.allizom.org/en-US/firefox/search/?q=vers-compat&appver=42.0&platform=mac

Those are platform install buttons but they seem to be missing the info details this.

**Comment by muffinresearch** [comment]
<img width="447" alt="vers-compat____search____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14187189/b94070c4-f779-11e5-8acd-29375a63b885.png">

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/xfpNKHZK (this addon has 4 buttons before the fix)
