### ISSUE TITLE
Add-on fails validation: Received an empty response from the server; status: 502

### ISSUE THREAD

**Issue by carleeno** [mozilla/addons-server#21140]
### Describe the problem and steps to reproduce it:
When attempting to upload our xpi (via `web-ext sign` or manually through AMO dev hub), it fails to validate with an error
```
Received an empty response from the server; status: 502
```

In this case, we are hosting the version on our own. The add-on size is 5.90 MB. We have not changed anything noteworthy in the add-on (no changes to manifest, etc).

### What happened?

![image](https://github.com/mozilla/addons-server/assets/54586926/8ececbc3-36eb-4750-87a2-714a80239c3e)

Note that the error occurs when the above progress bar is only at about 20%

### What did you expect to happen?

Version should complete validation after upload.

### Anything else we should know?

The first time we saw the failure was about an hour ago, we have attempted several times in the past hour, suspecting it to be a transient failure.

The last time we successfully uploaded our add-on to AMO was 3 days ago.

**Comment by ioanarusiczki** [comment]
It's reproducible on all AMO envs. 

![incident](https://github.com/mozilla/addons-server/assets/33448286/1dfea92d-ed26-4db9-bc68-ce8c7dd3dc23)

**Comment by diox** [comment]
Thanks for the report, you found it first but https://github.com/mozilla/addons-server/issues/21141 has more activity so I'm going to close this one to consolidate feedback there.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-481
