### ISSUE TITLE
Received an empty response from the server; status: 502

### ISSUE THREAD

**Issue by aderaynal** [mozilla/addons-server#21141]
I am getting this error when I try to upload a new version of my Firefox extension (as a ZIP file) 
```
Your add-on failed validation with 1 error.
Received an empty response from the server; status: 502
```
This did not happen when I last uploaded a zip file on Aug. 10, 2023 
and there is no major changes inside my extension

is there something wrong with your server ?

![image](https://github.com/mozilla/addons-linter/assets/954901/e9d6cc8e-9df6-4fd8-9896-d6323ebaeb01)

**Comment by willdurand** [comment]
See also: https://github.com/mozilla/addons/issues/1522

**Comment by diox** [comment]
Hi,

We are reproducing with larg-ish files (> 1 MB), investigating.

**Comment by madprops** [comment]
Happening with a 3mb zip file.

**Comment by diox** [comment]
We've found the culprit and will be rolling out a fix soon.

**Comment by madprops** [comment]
Working over here now.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-482
