### ISSUE TITLE
White cross visible for caution button in listing pages.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2115]
Relates #2055 

See Add-ons listing pages for preliminary reviewed add-ons + the screencast: http://screencast.com/t/pr3I9fMVY

**Comment by ValentinaPC** [comment]
Please see also details page of a preliminary reviewed search tool:
![2016-04-01_0959](https://cloud.githubusercontent.com/assets/15685960/14199959/88bfa6b4-f7f0-11e5-944b-9b76300d8956.png)
Thanks!

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/pJXKLQ9PSQ
