### ISSUE TITLE
[GCP migration] Reviewer tools is not loading on AMO stage

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21159]
On AMO stage 

https://addons.allizom.org/en-US/firefox/ 

With reviewer permissions try to access :
https://reviewers.addons.allizom.org/en-US/reviewers/

![rev tools stage](https://github.com/mozilla/addons-server/assets/33448286/cc18a36b-73c6-49b6-b3aa-44fbed226c17)

**Comment by bqbn** [comment]
This should be the same cert issue as the code manager site since reviewers and code manager share the same ingress.

We've fixed the cert issue. Please test this again.

**Comment by ioanarusiczki** [comment]
@bqbn 

I can no longer reproduce it on AMO stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-486
