### ISSUE TITLE
Investigate issues with uwsgi 2.0.22

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21153]
When we upgraded to uwsgi 2.0.22, we started seeing https://github.com/mozilla/addons-server/issues/21141 : it became impossible to upload files past a certain size (~ 1MB).

It didn't seem to happen locally, but it could be because the configuration was different, or there wasn't enough requests in parallel, or maybe it's possible this wasn't related to file uploading handling at all but rather had something to do with the time it took to process those requests. 

Whatever the reason, it went away as soon as we reverted back to 2.0.21. We need to investigate what happen so that we can safely upgrade uwsgi again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-483)

**Comment by eviljeff** [comment]
I poked around to try to establish _what_ uwsgi config dev/stage/prod is running under.  Locally https://github.com/mozilla/addons-server/blob/master/docker/uwsgi.ini is pretty straightforward, but the config deployed by SRE is [spread out](https://github.com/search?q=repo%3Amozilla-it%2Fwebservices-infra+uwsgi+path%3A%2F%5Eamo%5C%2F%2F&type=code)  

https://github.com/mozilla-it/webservices-infra/blob/main/amo/k8s/addons-server/templates/configMap.yaml looks to be the main config of settings, but most of the actual values are defined elsewhere - https://github.com/mozilla-it/webservices-infra/blob/main/amo/k8s/addons-server/values.yaml#L13-L19 I guess.

If there's a way to get this config from a running uwsgi on dev it'd be better though.

**Comment by diox** [comment]
You should be able to grab it from `/etc/uwsgi.d/addons.ini` from a running container. Note that the nginx config might be relevant too (locally it differs significantly, since it proxies requests through the frontend)

**Comment by diox** [comment]
Minimum patch to reproduce locally (tested using ublock origin, which is a few MB):

```diff
diff --git a/docker/nginx/addons.conf b/docker/nginx/addons.conf
index 4e36bcbeac..017db12b58 100644
--- a/docker/nginx/addons.conf
+++ b/docker/nginx/addons.conf
@@ -59,7 +59,7 @@ server {
     }
 
     location / {
-        try_files $uri @frontendamo;
+        try_files $uri @olympia;
     }
 
     location @olympia {
diff --git a/docker/uwsgi.ini b/docker/uwsgi.ini
index 114bb021e2..21aaea38a6 100644
--- a/docker/uwsgi.ini
+++ b/docker/uwsgi.ini
@@ -15,6 +15,10 @@ gid             = $(GID)
 memory-report   = true
 enable-threads  = true
 
+harakiri = 600
+harakiri-verbose
+post-buffering = 1
+
 safe-pidfile = %(base)/docker/artifacts/addons-server-uwsgi-master.pid
 
 # supervisor runs watchmedo (via watchdog) which is configured to touch this

```

(The nginx changes are just to bypass the proxy we have setup that forces requests to go through addons-frontend, it's specific to local envs)

The `post-buffering` together with the `harakiri` setup seems to be the problem.

**Comment by diox** [comment]
This has been confirmed as a `uwsgi` regression in 2.0.22+, reported as https://github.com/unbit/uwsgi/issues/2580

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-483
