### ISSUE TITLE
Test FxA Social Logins

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21158]
From an email:

> We are in the final stages of squashing bugs and unblocking full end-to-end QA for [Google/Apple auth support in Firefox Accounts](https://docs.google.com/document/d/1qtpGJrtiGgPYVy9Ep7EeLXHAe_48eG2_V7V9a4ypdcg/edit#heading=h.e6v9vmljb6xl).

Social Logins are enabled on FxA stage, apparently, which AMO dev uses.  We need to test the Standard FxA Flow [use cases](https://docs.google.com/document/d/1qtpGJrtiGgPYVy9Ep7EeLXHAe_48eG2_V7V9a4ypdcg/edit#bookmark=id.u4u99wxbfyhq) - including 2FA and how it works with AMO's requirements for extension developers to have 2FA enabled.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I've been trying to follow the steps from the [Standard fxA flow](https://docs.google.com/document/d/1qtpGJrtiGgPYVy9Ep7EeLXHAe_48eG2_V7V9a4ypdcg/edit) and tested logins from AMO dev with fxA stage:

- I could register with a new account with password, google or apple ID 

- I could login with an existing account without 2fa using password and for existing account with 2fa using password + 2fa code

- login with an existing account with 2fa enabled using google id 

- login with google or apple id without having a password set and going to the addon submission flow would trigger to enable 2FA from AMO.  Meanwhile on the fxA page it is not possible to enable/disable 2FA or to unlink the connected services until a password is set. -> which is expected

-  disabling 2FA from the fxA page and login on AMO with a developer account using google ID -> requires enabling 2FA at login 

- unlinking google or apple from fxA and login again with password or google, apple ids worked 

- deleting from AMO and then from  fxA the account then login again using password or connected services worked 

- with 2FA enabled  when login is done using connected services: every time the security code is required 

- no matter of the login type the process from this[ test case](https://testrail.stage.mozaws.net/index.php?/cases/view/2275383&group_by=cases:section_id&group_order=asc&group_id=287789) is taking place as expected -> 2FA is requested at the first submission of an extension or at login if the developer has submitted addons and  disables 2FA

**Comment by ioanarusiczki** [comment]
@eviljeff

Unrelated, Edit profile page throws lots of server errors (I could reproduce with multiple accounts today)

![Editprofilepage](https://github.com/mozilla/addons-server/assets/33448286/7280702e-af9e-4fa1-9c1b-e57662adcb93)

**Comment by eviljeff** [comment]
> @eviljeff
> 
> Unrelated, Edit profile page throws lots of server errors (I could reproduce with multiple accounts today)

From sentry looks like Basket problems.  If it persists for more than a day or so we might need to poke something on that team.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I did not see Basket problems this morning.

**Comment by diox** [comment]
> - login with google or apple id without having a password set and going to the addon submission flow would trigger to enable 2FA from AMO. Meanwhile on the fxA page it is not possible to enable/disable 2FA or to unlink the connected services until a password is set. -> which is expected
> - no matter of the login type the process from this[ test case](https://testrail.stage.mozaws.net/index.php?/cases/view/2275383&group_by=cases:section_id&group_order=asc&group_id=287789) is taking place as expected -> 2FA is requested at the first submission of an extension or at login if the developer has submitted addons and disables 2FA

@ioanarusiczki In those 2 cases, did you go through the full flow with a social login, enabling 2FA inline and being redirected back to AMO to access submission flow ?

**Comment by ioanarusiczki** [comment]
@diox I remember that I did not have issues, I was redirected to continue and complete the submission of an extension.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-485
