### ISSUE TITLE
How do I install WebExtensions in ~/.mozilla/extensions/ ?

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#21163]
### Describe the problem and steps to reproduce it:
```
cd ~/.mozilla/extensions/
wget https://addons.mozilla.org/firefox/downloads/file/4098225/zoom_page_we-latest.xpi
```
Restarted Firefox

### What happened?
The WebExtension is not visible in about:addons

### What did you expect to happen?
The WebExtension ti be visible in about:addons

### Anything else we should know?
Please give me detailed documentation links, and instructions before you close this issue, as I could not find them.

**Comment by davidhedlund** [comment]
Also, I would be very thankful if someone could help me solve this issue: https://wiki.mozilla.org/Extension_Manager:Multiple_Item_Packages is not clear enough

**Comment by diox** [comment]
Hi,

See https://extensionworkshop.com/documentation/publish/distribute-sideloading/ (and https://blog.mozilla.org/addons/2019/10/31/firefox-to-discontinue-sideloaded-extensions/).

This is not an AMO issue so I'm closing this.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-489
