### ISSUE TITLE
Rename Firefox Accounts to Mozilla Accounts everywhere (server)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21161]
part of https://mozilla-hub.atlassian.net/browse/AOP-119

**Comment by eviljeff** [comment]
Current plan is to have the new strings with a date condition around them, so at the scheduled release datetime we switch automatically to the new branding without having to co-ordinate a one-off push.

(A follow-up would be to remove the old strings and the datetime logic)

**Comment by eviljeff** [comment]
In the end the only place we exposed the branding to users was the email we send to them when their account has been deleted.

**Comment by alexandruschek** [comment]
Hello @eviljeff,

I tested this issue now, and the message contains "Firefox account". 

![firefox account](https://github.com/mozilla/addons-server/assets/139126091/839415bb-2a77-4383-b66f-cb0c547c74d6)

Also, the email for account deletion for this email adress: aschek+test-user4@mozila.com takes a longer time to be sent(30 minutes and did not receive it yet)

**Comment by eviljeff** [comment]
@alexandruschek That it still says "Firefox Account" is correct at the moment - we need to land a code change to simulate the branding change after the launch date.  we'll confirm the scheduling around that.

> Also, the email for account deletion for this email adress: [aschek+test-user4@mozila.com](mailto:aschek+test-user4@mozila.com) takes a longer time to be sent(30 minutes and did not receive it yet)

emails on dev/stage are suppressed - they'll be in fake emails in the django admin though.

**Comment by ioanarusiczki** [comment]
@eviljeff 

The e-mails on dev:

![Mozilla account](https://github.com/mozilla/addons-server/assets/33448286/e9777659-3ab9-4019-9446-354d279e0db9)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-487
