### ISSUE TITLE
Add log activity when slug is changed

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21174]
When the add-on slug is changed, we should log an activity containing:
* Add-on the slug was changed for
* User account that changed the slug
* Old slug
* New slug

**Comment by wagnerand** [comment]
Is `clean_slug` in `src/olympia/addons/models.py` the right place to do this?

**Comment by eviljeff** [comment]
dupe of https://github.com/mozilla/addons-server/issues/18980 - please close one of them

**Comment by ioanarusiczki** [comment]
@GregSherman @wagnerand 

This is verified on AMO dev

![changing the slug](https://github.com/mozilla/addons-server/assets/33448286/05845a7a-15ba-4fe7-97a6-0dcfeafc4bd8)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-491
