### ISSUE TITLE
AMO dev's frontend is not loading

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21176]
Possible regression of https://github.com/mozilla/addons-server/issues/20780 

1. Load adddons-dev.allizom.org

-> A server error is displayed 

![server error](https://github.com/mozilla/addons-server/assets/33448286/5d6a437e-ab43-49f8-9ae5-30d5689c286c)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Verified on AMO dev - homepage and all theme categories are loading

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-492
