### ISSUE TITLE
Add-on should not have 2 "add to firefox" buttons

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2118]
![amo-featured-hover-2buttons](https://cloud.githubusercontent.com/assets/8145891/14185998/3a7bf3b4-f74a-11e5-9e8d-91ff9b67a92a.PNG)
looking at the classes one is for platform windows and the other for platform linux

**Comment by tofumatt** [comment]
Can you include the URL used to reproduce this issue?

**Comment by designakt** [comment]
nor should they have 3
![amo-featured-hover-3buttons](https://cloud.githubusercontent.com/assets/8145891/14186126/c993473c-f74a-11e5-8e75-1cc4fe93074b.PNG)

**Comment by designakt** [comment]
seen on: https://addons-dev.allizom.org/en-US/firefox/
in Nightly on Windows 10

**Comment by muffinresearch** [comment]
Duplicate of #2113
