### ISSUE TITLE
Throw an error message when using the endpoint in case of invalid compatibility range

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21195]
Followup for https://github.com/mozilla/addons-server/issues/21139#issuecomment-1717636641

On dev hub: 
For non-recommended when the interval 78.0 - 119.* is picked from edit version page it would throw an error Invalid version range. 

![invalid range](https://github.com/mozilla/addons-server/assets/33448286/3417328a-837d-49b4-bdde-07fb4f4b257c)

With the API: 

If I sent a PATCH request such as {"compatibility": {"android": {"min":"78.0","max": "119."}}} I'll get a 200 response but the with "compatibility": {
"android": {
"min": "119.0a1",
"max": ""
}

**Comment by diox** [comment]
We're automatically fixing the compatibility data to avoid the forbidden range but I agree we should raise an error like we do in devhub.

**Comment by diox** [comment]
Note: We'll only raise an error if the developer provided an object with `min` and `max` values. If they only provided one of the two, or none, we won't error out and silently fix it instead.

**Comment by ioanarusiczki** [comment]
@diox 
When min or max are used from the invalid version range I hit a 400:

"compatibility": ["Invalid version range. For Firefox for Android, you may only pick a range that starts with version 119.0a1 or higher, or ends with lower than version 79.0a1."

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-496
