### ISSUE TITLE
Add webhook for cinder to call on report decision

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21194]
part of https://mozilla-hub.atlassian.net/browse/AOP-121

When a decision has been made on a report via cinder moderation tooling it will call a webhook on AMO to perform the action chosen by the moderator.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-495)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Let me know how to test this.

**Comment by ioanarusiczki** [comment]
@eviljeff Can this issue with https://github.com/mozilla/addons-server/issues/21375 get a 23.11 milestone? They're not verified yet.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I sent reports using AMO dev's frontend and then checked Cinder after each report. 
- I saw in Cinder reports sent for extensions, themes, users, ratings and collections. I did not receive reports for dictionaries, the following guids: 
af-ZAAPI@dictionaries.addons.mozilla.org and azdev2@dictionaries.addons.mozilla.org. I've sent ~5 reports for each but I found only one being present in Cinder

- I think there's an issue with reports sent when user is unauthenticated and chooses to add a name and an email because I did not receive the reports in Cinder - I could reproduce it with extensions and collections.  I received reports in Cinder every time  I left File report anonymously checked.

**Comment by eviljeff** [comment]
@ioanarusiczki can you file issues for those problems - they both sound like things we need to fix.

This issue was for the outcome of the decision in AMO_after_ the reports have been processed in cinder though (cinder -> addons-server).  The issues for the reports going _into_ cinder were in https://github.com/mozilla/addons-server/issues/21386 etc (frontend -> addons-server -> cinder)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Ok, I think I know what to do,  so I must try to make a decision in Cinder in the Content Infringement queue and then check if the reported content has been removed on AMO. 

I filed https://github.com/mozilla/addons-server/issues/21502 and https://github.com/mozilla/addons-server/issues/21503

**Comment by eviljeff** [comment]
> I had a user id which wasn't banned (no matter what I chose in Cinder besides "Ignore") The id is 10640485 , I checked it in admin and the id doesn't have permissions.

We can't immediately see the problem with this user - can you file a follow-up issue for us to investigate?

> I have some observations and I'll try to make them as clear as possible:
> 
>     * After an extension is force-disabled ( from Cinder) the regular users cannot send reports again from AMO (unless they replace the slug with the addon guid). An admin can still send reports (the name and user is still displayed on the form). Same for a rating which has already been deleted, an admin can still use the feedback form of a deleted rating. These admin reports are sent to Cinder.
> 
>     * Location section in the feedback form is no longer displayed once an addon becomes unlisted. When "It violates add-on policies" is checked without location specified since it's not available,  the report will appear in Cinder into Addon Infringement queue.
> 
> I tried a few tests from addon manager too:
> 
>     * when the addon was installed and goes unlisted because it's been reported and then disabled  -> the report opens in a new tab and has the guid in it's URL. Any of the reasons except for "it violated add-on policies" will send the report into the content infringement queue.
> 
>     * being the owner of an unlisted add-on, I installed it and then reporting it from addon manager would send reports to Cinder.
>       I also tried with an unlisted installed from a website, in this case I receive the reports in AMO admin but I don't have reports sent to Cinder.

These seem to be as expected (after discussion with @willdurand  and @diox)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-495
