### ISSUE TITLE
String contains duplicated word; min and max variable misplaced?

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#21191]
### Describe the problem and steps to reproduce it:
[Invalid version range. For Firefox for Android, you may only pick a range that starts with version %(max)s or **or** higher, or ends with lower than version %(min)s."](https://github.com/mozilla/addons-server/blob/50799423c9e462931eeeb50be2e643c05d4c530f/locale/en_US/LC_MESSAGES/django.po#L1609)

### What happened?
- There is an extra "or" in the string.
- Additionally, reconsider this string whether this is accurate with where the variables are placed. Should they be switched? 

### What did you expect to happen?
- Remove the extra "or"
- Review whether the %(max)s and %(min)s variables should be swapped.

**Comment by diox** [comment]
I see how the variables could be confusing but they are correct. The min and max here refer to a forbidden range, and so we're saying to developers they can pick something either above the forbidden range max, or below the forbidden range min.

I'll remove the extra `or`, thanks for letting us know.

**Comment by diox** [comment]
Fixed in https://github.com/mozilla/addons-server/commit/a24076e9c602ee7f463730f76e018dc550e3e220

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-493
