### ISSUE TITLE
Add cinder.co API integration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21193]
part of [https://mozilla-hub.atlassian.net/browse/AOP-121](https://mozilla-hub.atlassian.net/browse/AOP-121)

AMO needs to be able to forward reports of abusive content to cinder.co, so we need to add the API integration.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-494
