### ISSUE TITLE
Add admin permission to change regional restrictions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21203]
To widen coverage for maintaining regional restrictions, please add a specific permission `Admin:RegionalRestrictionsEdit` that allows an admin to see and edit those.

**Comment by eviljeff** [comment]
@wagnerand to be clear, _just_ view and edit?  Or create and delete too?

**Comment by wagnerand** [comment]
> @wagnerand to be clear, _just_ view and edit? Or create and delete too?

@eviljeff everything, CRUD

**Comment by ioanarusiczki** [comment]
@eviljeff 

On AMO stage:
 I could view all restrictions then create, update or delete a regional restriction after I added `Admin:RegionalRestrictionsEdit` into Reviewers:Admins 

The only difference for this user compared to an admin with "*" -> if ithe user is in the country where the addon has been restricted the detail page won't be available.  An admin with "*" has access to the detail page of an addon blocked at all times.

**Comment by eviljeff** [comment]
@wagnerand to comment about being able to access the addon detail page with this permission (currently you need `Addons:Edit` to override the regional restriction and see the content) and file a follow-up if necessary.

**Comment by wagnerand** [comment]
> ... the detail page won't be available ...

Is this the admin detail page or the add-on listing page?

**Comment by ioanarusiczki** [comment]
@wagnerand I was talking about the add-on's frontend detail page 

such as https://addons.allizom.org/en-US/firefox/addon/addon-with-test/

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-498
