### ISSUE TITLE
addons-bloomfilters is not updated on -stage 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21201]
I created several blocks this morning on -stage

An example: 
[25 guids blocked](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/325/change/?_changelist_filters=signoff_state%3Dall) and published 

Checked the records for -stage after 3 pm -> it wasn't updated with the new blocks

https://firefox.settings.services.allizom.org/v1/buckets/blocklists/collections/addons-bloomfilters/records

**Comment by diox** [comment]
```
HTTPSConnectionPool(host='settings-writer.stage.mozaws.net', port=443): Max retries exceeded with url: /v1/buckets/staging/collections/addons-bloomfilters/records
```

@bqbn any ideas ?

**Comment by bqbn** [comment]
Considering the comments in[ this PR](https://github.com/mozilla/addons-server/pull/20642), it appears that after the migration to GCP, the stage environment should utilize 'https://remote-settings.allizom.org/v1/', while prod should use 'https://remote-settings.mozilla.org/v1/' for the writers.

Can this `REMOTE_SETTINGS_WRITER_URL` setting be overridden by the same named env variable?

**Comment by bqbn** [comment]
@ioanarusiczki IMHO, I believe that blocking an addon and adding it to the bloom filter should be included in the sanity check list. This inclusion will assist in identifying issues like this more rapidly.

**Comment by ioanarusiczki** [comment]
@bqbn qa does not have access to blocklisting and bloomfilters on AMO prod. 

Also, AMO Dev's records is not functional. Stage is the only env qa can verify this.

**Comment by eviljeff** [comment]
> Considering the comments in[ this PR](https://github.com/mozilla/addons-server/pull/20642), it appears that after the migration to GCP, the stage environment should utilize 'https://remote-settings.allizom.org/v1/', while prod should use 'https://remote-settings.mozilla.org/v1/' for the writers.
> 
> Can this `REMOTE_SETTINGS_WRITER_URL` setting be overridden by the same named env variable?

No, only settings variables wrapped in `env(...)` can be overridden by env variables.  Just needs https://github.com/mozilla/addons-server/pull/20642 to land again.  **Before we switch to GCP on prod**

**Comment by eviljeff** [comment]
> It's also disturbing that [grafana](https://earthangel-b40313e5.influxcloud.net/d/IWZpIQgMk/blocklist?orgId=1&var-env=stage) isn't throwing any alerts for stage.

😬 it's because we upload the filter in a separate celery task so the `success` ping is sent straight away.  (The lack of `upload_mlbf` or `upload_stash` isn't conclusive because sometimes there isn't an upload needed)

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/pull/21204

**Comment by eviljeff** [comment]
> > It's also disturbing that [grafana](https://earthangel-b40313e5.influxcloud.net/d/IWZpIQgMk/blocklist?orgId=1&var-env=stage) isn't throwing any alerts for stage.
> 
> 😬 it's because we upload the filter in a separate [celery task](https://github.com/mozilla/addons-server/pull/13909) so the `success` ping is sent straight away. (The lack of `upload_mlbf` or `upload_stash` isn't conclusive because sometimes there isn't an upload needed)

https://github.com/mozilla/addons-server/issues/21209 to address monitoring

**Comment by diox** [comment]
@bqbn I've made a new tag, `2023.09.14-1`, which makes the default URL for stage & prod the GCP one, and also allows an env variable to override the value.

The tag also contains a minor UI fix for devhub when the read-only notice is shown. I'd like to deploy it to prod before migrating, which means we definitely need to set the env variable (to the old, AWS-specific URL) in the AWS environments.

**Comment by bqbn** [comment]
> @bqbn qa does not have access to blocklisting and bloomfilters on AMO prod.
> 
> Also, AMO Dev's records is not functional. Stage is the only env qa can verify this.

@ioanarusiczki correct, and thus I think it should be included in the sanity check list for the `stage` env so that it will be tested once a new tag is pushed to `stage`. 

We migrated `stage` to GCP on 9/5. If this were included in the sanity check, we could have identified this issue earlier.

**Comment by ioanarusiczki** [comment]
@bqbn @diox 

This is verified on AMO stage

Blocked and deleted blocks are displayed 
https://remote-settings.allizom.org/v1/buckets/blocklists/collections/addons-bloomfilters/records

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-497
