### ISSUE TITLE
Signed self-hosted add-on email version link not working

### ISSUE THREAD

**Issue by rebloor** [mozilla/addons-server#21214]
I have uploaded a self-hosted extension and received an email with the link https://addons.mozilla.org/developers/addon/2815105/versions. This get to a page saying "We're sorry, but we can't find what you're looking for." The correct link would appear to be https://addons.mozilla.org/en-US/developers/addon/04bdfedea2cc4611ad94/versions.

https://github.com/mozilla/addons-server/blob/6aa1f2a1bde4a7642a394215ec1e79e43f87b054/src/olympia/reviewers/templates/reviewers/emails/unlisted_to_reviewed_auto.ltxt#L3

**Comment by diox** [comment]
Are you sure you were logged in with the correct account ? It's working for me, `https://addons.mozilla.org/developers/addon/<addon_id>/versions` redirects to `https://addons.mozilla.org/<locale>/developers/addon/<slug>/versions`

**Comment by rebloor** [comment]
Sorry, it's opening in a different container that isn't logged in. However, a more direct "login to see your add-on" would have been helpful.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-501
