### ISSUE TITLE
Blue on blue copy on homepage carousel and mising header style

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2122]
## steps to reproduce:
1. Load the addons-dev homepage

## observed behavior:
The panel 'Build the perfect website' is different from other panels as it is 

- missing header styling
- blue on blue copy renders most things unreadable

## screenshot
![unspecified](https://cloud.githubusercontent.com/assets/1514/14205305/0fa8601a-f802-11e5-841b-0cfc73eaf810.png)

**Comment by muffinresearch** [comment]
I think this is resolved now

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![1](https://cloud.githubusercontent.com/assets/15685960/14460224/ffc46e98-00c4-11e6-8af2-f1fb09804894.png)
![2](https://cloud.githubusercontent.com/assets/15685960/14460230/03ec9e00-00c5-11e6-9697-8d90e36522da.png)
