### ISSUE TITLE
Store webext version/UA and "source" for each Version

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21225]
Follow-up for #18803:

For each `Version` we create, let's store:

* Whether it was created from devhub, signing API, new API, automation (we already record this on the `FileUpload` but currently don't keep it afterwards)
* The `web-ext` version if applicable

We'll want that table to be exposed in redash afterwards for easy querying.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-502)

**Comment by diox** [comment]
untested prototype for when we have time to pick this up again https://github.com/mozilla/addons-server/pull/21233/files

**Comment by ioanarusiczki** [comment]
With dev hub 

https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1801150/change/

With API - using 2 different clients 

https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1801153/change/
https://addons-internal.dev.mozaws.net/en-US/admin/models/versions/version/1801152/change/

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-502
