### ISSUE TITLE
Signing API should only create versions compatible with Firefox by default

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21229]
STR:
- Submit an extension using `web-ext` (without `--use-submission-api`) or the signing API directly

Expected result:
- The extension is only compatible with Firefox, *not* Firefox for Android

Actual result:
- The extension is compatible with both Firefox and Firefox for Android

The signing API doesn't allow you to choose compatibility. To submit an extension compatible with Android, developers should add `browser_specific_settings` > `gecko_android` in their manifest.

Because the signing API has been behaving like this for years, this is a breaking change that cannot land until documentation and developer outreach has been done. Those tasks are tracked separately in JIRA. (**Edit:** [announcement](https://blog.mozilla.org/addons/2023/10/05/changes-to-android-extension-signing/) is now live)

**Comment by diox** [comment]
We'll also need a migration to revert compatibility for add-ons not part of the recommended/line set for Android + list of extensions we tested as compatible. Those should be reverted from 119.0a1 to 120.0a1 *unless they were using `gecko_android`.

**Comment by diox** [comment]
> We'll also need a migration to drop Android compatibility for add-ons not part of the recommended/line set for Android + list of extensions we tested as compatible.

QA: on top of testing the signing API with the STR above, prepare a list of add-ons you want to test this migration on and let me know when to fire it (it has to be triggered manually).

**Comment by ioanarusiczki** [comment]
@diox 

I used web-ext 7.8.0 and tried the following command with an extension

`web-ext sign --api-key="user:" --api-secret="secret" --api-url-prefix=https://addons-dev.allizom.org/api/v4`

with --channel=listed/unlisted -> [versions 4.0](https://addons-dev.allizom.org/en-US/developers/addon/lapir-gorpopary-scockate1/versions/1701831) and 5.0 have been uploaded only with Firefox compatibility 

with gecko_android in the manifest -> versions 6.0 and [7.0](https://addons-dev.allizom.org/en-US/developers/addon/lapir-gorpopary-scockate1/versions/1701834) have Firefox and Android compatibility (locked and starting from 119.0a1) 

I am not sure what "not using the signing API" directly means, is my testing good so far?

**Comment by diox** [comment]
Your testing is good so far. By using the signing API directly I meant making the requests to the API yourself without `web-ext`.

**Comment by ioanarusiczki** [comment]
@diox 

I'm attaching the list of IDs for -dev -> after the script ran , Android compatibility was dropped on all addon versions. 

This will be repeated for -stage. 
[AMO dev revertandroid.csv](https://github.com/mozilla/addons-server/files/12856793/AMO.dev.revertandroid.csv)

**Comment by ioanarusiczki** [comment]
@diox 

Same results on -stage, I checked the submission using web-ext. 
On -dev I verified with web-ext and directly using the endpoint. 

IDs verified on -stage:
1016675
1016640
1016121
1016241
619654

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-504
