### ISSUE TITLE
2FA is incorrectly required for new theme version submission

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21231]
STR:

1. Create a new account 
1. Submit a first version of a theme 
1. Upload a new version

Expected result: 
The submission flow continues , new version is submitted

Actual result:
the 2fa flow is triggered 

Notes:
This is reproducible on -dev and -stage

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-505)

**Comment by ioanarusiczki** [comment]
@diox 

I submitted the first version (.xpi) of [a theme](https://addons-dev.allizom.org/en-US/developers/addon/animated-matrix_themetest/versions), then using the wizard the second version worked but at a new upload with an .xpi I get this: 

![ondev](https://github.com/mozilla/addons-server/assets/33448286/e9f8ad96-9d58-41a2-98ab-27d68bfb38a1)

**Comment by diox** [comment]
@ioanarusiczki sorry I know this is old but I haven't managed to reproduce this locally. Could you give more detailed STRs, including which URLs you used to submit which version ?

**Comment by ioanarusiczki** [comment]
I went to https://addons.allizom.org/en-US/developers/addon/submit/theme/upload-listed
Uploaded first version 
Then from dev hub I clicked Upload New Version and tried with an xpi

I've noticed now that if I try a new submission of a theme I don't get the error. It's always at new version.

![red error](https://github.com/mozilla/addons-server/assets/33448286/a2b19124-a7ba-415c-851b-ccd122cb42b7)

**Comment by diox** [comment]
Could you share the exact xpi you were trying to upload ?

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-505
