### ISSUE TITLE
POST /api/v5/addons/addon/  500 error - Stage ENV

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21258]
### Describe the problem and steps to reproduce it:
 I am trying this api call: POST /api/v5/addons/addon/ and I am receiving 500 on Stage

### What happened?
Reproduction Steps:
1. I made this one in order to have the UUID: /api/v5/addons/upload/ 
(X-AMO-Request-ID: 083c83fce3484eb297a6a3a0fd65a349 / 
X-Amz-Cf-Id: DtId7fPigyKVnutcbB6hnHI3jDCh8O0nLEJcoBnlDEAgkt6nlrqfpQ== / 
UUID: 4d88cdb302a5440a85409c72e5649b9e)
2. POST /api/v5/addons/addon/ with postman on stage and I am receiving 500 
(X-AMO-Request-ID: 7b528e05b64040be8a4c85c8f3ccfed1 / 
X-Amz-Cf-Id: 4_1miVAaQXrC6ZOWh_W9sDw6XvyHp5mYsyeFCMvMRhBLmu1f0sBY8g== ). 

### What did you expect to happen?
To do the post call with succes. I have this error on the automation side as well, last week , with the same reproduction steps and body I did not have any problems

### Anything else we should know?
Body used: 
{
    "categories": {
            "android": ["experimental", "performance"],
            "firefox": ["bookmarks", "privacy-security"]
        },
    "contributions_url": "https://www.patreon.com",
    "default_locale": "en-US",
    "description": {
        "de": "Description in german",
        "en-US": "Description in en-US",
        "fr": "Description in french"
    },
    "developer_comments": {
        "de": "Dev comments in german",
        "en-US": "Dev comments in en-US",
        "fr": "Dev comments in french"
    },
    "is_disabled": false,
    "is_experimental": false,
    "icon": null,
    "name": {
        "de": "DE Name set at creation time",
        "en-US": "EN-US Name set at creation time",
        "fr": "FR Name set at creation time"
    },
    "requires_payment": false,
    "slug": "my_slug_addon_6",
    "summary": {
            "de": "Summary, in german",
            "en-US": "Summary, in en-US",
            "fr": "Summary, in french"
        },
    "support_email": {},
    "tags": [
        "anti malware",
        "anti tracker",
        "antivirus",
        "chat",
        "container",
        "content blocker",
        "coupon",
        "dailymotion",
        "dark mode"
    ],
    "version": {
        "upload": "4d88cdb302a5440a85409c72e5649b9e",
        "license": "all-rights-reserved",
        "release_notes": {
            "de": "DE Version notes added in API at addon creation time",
            "en-US": "EN-US Version notes added in API at addon creation time",
            "fr": "FR Version notes added in API at addon creation time"
        },
        "compatibility": {
            "android": {"min": "68.0", "max": "*"},
            "firefox": {"min": "58.0", "max": "100.*"}
        }
    }
}

Upload call:
![image](https://github.com/mozilla/addons-server/assets/139126091/2ac127df-c349-4b7a-a956-8292ccbd4736)
Post Addon:
![image](https://github.com/mozilla/addons-server/assets/139126091/d3b58c06-c7a4-4a32-a330-468ad5febfcf)

**Comment by willdurand** [comment]
I think I replied to that indirectly before: the version you're trying to post doesn't have an add-on bound to it (according to [Sentry](https://mozilla.sentry.io/share/issue/fb5cd19ae8ae4d09be7b2be26457e1d4/)). Not sure why we return a 500 here but the changes from https://github.com/mozilla/addons-server/pull/21152 are in the stacktrace.

If this used to work before, it looks like we were able to create an add-on object for a very first version submitted, and we were never trying to _access_ the related add-on object?

**Comment by diox** [comment]
I'm setting this as a P1 because we have comms about compatibility coming and this bug might make things more confusing...

**Comment by ioanarusiczki** [comment]
@diox 

Not sure if this may help ->  I tried uploading addons and new versions last week and I got 201 responses. 
But I used a different JSON 

`{
    "categories": {
        "firefox": [
            "other"
        ]
    },
    "version": {
        "upload": "a24394963fda4725a9a91a2d21c9ccfa",
         "custom_license": {
            "name": {
                "en-US": "test"
            },
            "text": {
                "en-US": "test"
            }
        }
    }
    }`

**Comment by ioanarusiczki** [comment]
@diox 

I verified on AMO dev various compatibility ranges for addon create, new versions and edit versions endpoints. 

- the 500 error is no longer reproducible
- I've noticed when I've set a max value of 119.* , 120* or even higher,  I will get a 400 with Invalid version range error message. This is the JSON `{"compatibility": {"android": {"max":"120.*"}}}`. When no compatibility is set through the JSON but there is a max set in the manifest the response sets a min 119.0a1 and a max "*" (blue lines from 1.1 in my document ). 

[This is the document](https://docs.google.com/document/d/1Fv_V-yBavijTLvztnYvrTrPo5LM9CsfAuKACnv6BeRA/edit?usp=sharing) with all my testing results (1.1 was tested yesterday on AMO stage, except that all the other scenarios 1.2 -1.4) were tested today on AMO dev.

**Comment by diox** [comment]
> I've noticed when I've set a max value of 119.* , 120* or even higher, I will get a 400 with Invalid version range error message. This is the JSON {"compatibility": {"android": {"max":"120.*"}}}.

This is intended. We default to a `min` of `48.0` internally, so setting a `max` of `120.0` makes you hit the forbidden range. 

> When no compatibility is set through the JSON but there is a max set in the manifest the response sets a min 119.0a1 and a max "*" (blue lines from 1.1 in my document ).

Also intended, similar root cause if you only specify a `max` you get a default min that would put you in the invalid range, but we don't explicitly warn about problematic ranges from the manifest, we silently fix them instead.

**Comment by alexandruschek** [comment]
Hello, 

Verified on DEV env the following scenarios manually that through automated tests were failling on stage:
- Listed extension upload
- invalid categories added
- Invalid slug value

I also ran the automated tests on the dev env and there were no issues except one case for android it seems it only accepts a range, no only min or max value: {'android': {'max': '119.0a1'}} for this I get 400. and message: {"compatibility":["Invalid version range. For Firefox for Android, you may only pick a range that starts with version 119.0a1 or higher, or ends with lower than version 79.0a1."]}

**Comment by diox** [comment]
> only accepts a range, no only min or max value: {'android': {'max': '119.0a1'}} for this I get 400. and message: {"compatibility":["Invalid version range. For Firefox for Android, you may only pick a range that starts with version 119.0a1 or higher, or ends with lower than version 79.0a1."]}

Explained above: since you only specified a max, we have to guess a min, we use the default `48.0`, so your range becomes `{"min": "48.0", "max": "119.0a1"}`, which is in the forbidden range, so you get the error. That is working as expected.

**Comment by ioanarusiczki** [comment]
@diox 

I made some further testing and added into [the doc at 1.5](https://docs.google.com/document/d/1Fv_V-yBavijTLvztnYvrTrPo5LM9CsfAuKACnv6BeRA/edit?usp=sharing) when Android compatibility is set in manifest.json and also added in the JSON object. For Android, the information from manifest.json is a priority, so if JSON contains it too I get an error  "Can not override compatibility information set in the manifest for this application (Firefox for Android)"

I've encountered a 500 however, when I tried to submit or create a new version for a lang pack with android compatibility specified (in manifest.json and JSON as well) so it might seem that the issue is still reproducible for these type of addons, yet they don't have android in scope. Also, with PATCH I could change for a lang pack the compatibility from firefox to android , example is https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/627299

**Comment by ioanarusiczki** [comment]
@diox I verified on AMO Dev , at creation or new version I hit a 400, Lang packs are not supported by Firefox for Android

PATCH still allows Android compatibility.

**Comment by ioanarusiczki** [comment]
This was verified on -stage and -prod.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-510
