### ISSUE TITLE
Make model changes to AbuseReport to handle cinder/DSA requirements

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21255]
We will be repurposing the existing `AbuseReport` model to also track feedback and and content violation reports we will be handing to satisfy our DSA requirements.

Broadly we need to:
 - add decision category (disable/ban/etc)
 - probably* add the policy name and/or uuid the decision was made under
 - add reporter email and name (the user may be authenticated also)
 - change categories ... (personally) I lean towards entirely new categories and then we can translate the old categories in the serializer where appropriate while we're still getting the old reports
 - appeal state is tricky - I suppose if we're limited to just one appeal each per reporter and target then a flag on the model is sufficient. Otherwise we'd need an intermediate model.

*there is a bunch of extra metadata sent with the webhook response, but unless we _need_ it I guess we don't need to store it in the AMO DB.

**Comment by diox** [comment]
> probably* add the policy name and/or uuid the decision was made under

Need some uniquely random identifier to be able to appeal anonymous reports as the reporter (id can't be guessable since it won't be protected by auth). So the decision uuid should be recorded for sure.

> change categories ... (personally) I lean towards entirely new categories and then we can translate the old categories in the serializer where appropriate while we're still getting the old reports

aka `reason` in the existing model. I think it's fine to add new ones, it's just used by Firefox at the moment anyway.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I've noticed in the admin there are 4 more `reasons`  and I could send using the API the following:

`hate_speech`
'csam'
'does_not_work'
'not_wanted'

Sending reports using the API : I could see the name of the Reporter  (display name) in [Abuse reports ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/abuse-reports/620571) when user was authenticated. 

If I'm making an authenticated Abuse Report from the browser : the Reporter is registered as `anonymous` but I think that's a very old issue. Also these 4 new reasons are not present in the Abuse Report form. 

I don't see a `reported_email` or `reporter_name` in admin. Does this issue address only the `reason` part?

**Comment by eviljeff** [comment]
The issue was to make the model changes that a couple of different other issues depended on (the api changes are in #21268 for example) so that nothing is broken with the existing reporting is good enough.  

Can you file a follow-up to expose the new fields in the admin?  (They are more for viewing in cinder but we may as well show them in django admin too)

**Comment by ioanarusiczki** [comment]
@eviljeff 

While filing I've noticed there is already a[ `Reporter` ](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/26850/change/)field present. 

I did not encounter anything broken while sending abuse reports (api or browser).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-508
