### ISSUE TITLE
A Hidden version of an unapproved add-on cannot be made Listed again

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2125]
Steps to reproduce:
1. Sign in to AMO-dev Dev Hub page https://addons-dev.allizom.org/en-US/developers/
2. Submit a listed add-on (do not approve the add-on)
3. Make it "Hidden" from "Manage Status & Versions" page 
4. Make it listed again

Expected results:
The add-on is available again.

Actual results:
Add-on version appears disabled.

Notes/ Issues:
The version is not longer listed in the add-ons queues.
Verified on AMO-dev FF45(Win 7). Reproducing on AMO-stage, dev and prod.
Screencast for this issue: 
![2016-04-01_1318](https://cloud.githubusercontent.com/assets/15685960/14204338/53e09c0c-f80c-11e5-908e-5a9328e3d95f.png)

**Comment by andymckay-limited-access** [comment]
Is this by design @eviljeff?

**Comment by eviljeff** [comment]
Yeah, it was #1107

**Comment by eviljeff** [comment]
It says "The files awaiting review will be disabled and you will need to upload new versions. " in the dialog too.

**Comment by ValentinaPC** [comment]
Yes, it says and I've missed that.
Screenshot: 
![true_fact](https://cloud.githubusercontent.com/assets/15685960/15176746/3ace8fac-1775-11e6-825b-86fa6eccee7c.png)
