### ISSUE TITLE
Limit extensions available for Firefox for Android 119 Release

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21256]
In https://github.com/mozilla/addons-server/issues/21162 and https://github.com/mozilla/addons-server/issues/21139 we made some add-ons compatible with Firefox for Android 119.0a1 and allowed developers to make their add-ons compatible with that version.

General availability of add-ons in Firefox for Android is targeted for later though, that was to enable testing in Nightly and Beta. Therefore we need to bump add-ons targeting `119.0a1` to `120.0a1` instead just before `119.0` final version is released (*) on October 23rd.

(*) There will be a small window of time where 119 Beta (Nightly should already be on 120) users won't see the add-ons as available if they are still on `119.0a1`. They'll need to update to get `120.0a1` or higher.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-509)

**Comment by diox** [comment]
This will need to happen again when `120.0` is released if we don't enable general availability at release time but a few days later.

So the plan would be to have a generic command that takes an arbitrary version and executes the bump to `MIN_VERSION_FENIX_GENERAL_AVAILABILITY`. Then we would deploy a change to that constant and execute the command for each release on the right day.

In other words:

## October 23rd (Before Firefox for Android 119 release):
- Change `MIN_VERSION_FENIX_GENERAL_AVAILABILITY = 120.0a1`, trigger command with `119.0a1` as input

## November 21 (Before Firefox for Android 120 release):
- Change `MIN_VERSION_FENIX_GENERAL_AVAILABILITY = 121.0a1`, trigger command with `120.0a1` as input

## December ?? (General availability launch):
- Change `MIN_VERSION_FENIX_GENERAL_AVAILABILITY = 120.0`, trigger command with `121.0a1` as input (downgrading)

**Comment by diox** [comment]
Actual implementation of this happened in https://github.com/mozilla/addons-server/issues/21293

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-509
