### ISSUE TITLE
Make API changes to abuse api to handle cinder/DSA requirements

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21268]
Depends on the model changes in https://github.com/mozilla/addons-server/issues/21255

We will be repurposing the existing /abuse api endpoint to also track feedback and and content violation reports we will be handing to satisfy our DSA requirements.

We need to:
- add fields for name and email
- call `CinderAddon.report` for appropriate (DSA covered) reasons
- `Cinder` class will need updating to handle non-authenticated users with name and email
- create a `CinderReport` instance with the job id returned from the API

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-512
