### ISSUE TITLE
Expose reporter_name and reporter_email in the abuse report model admin

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21288]
Followup https://github.com/mozilla/addons-server/issues/21255#issuecomment-1750714826

Abuse Reports django model requires 2 new fields :

reporter_name 
reporter_email

Both fields are for required when the fronted form will change for unauthenticated users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-518)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-518
