### ISSUE TITLE
Submission won't continue only with Android platform checked 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21294]
Followup for https://github.com/mozilla/addons-server/issues/21226

1. Submit an extension (without gecko_android specified in the manifest)
2. Click only Firefox for Android and Yes in the popup
3. Continue

Actual result:
A message that the extension has to be compatible with at least one application

Expected result:
The next submission page should be displayed since an application is checked

Workaround:
click/unclick the Firefox platform and submission can continue

![with android only](https://github.com/mozilla/addons-server/assets/33448286/1e99818c-fa98-4ce1-a84c-8161cf78728b)

**Comment by ioanarusiczki** [comment]
@diox 

This is verified on AMO dev

![500errorfixed](https://github.com/mozilla/addons-server/assets/33448286/19caade0-b2bc-4a6d-b318-44c2bc5ca676)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-521
