### ISSUE TITLE
Spelling error "licence" vs "license"

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#21305]
This was reported by the community volunteers. Everywhere the word is spelled as `license`. However this string is spelled incorrectly: [`Commons Attribution Share-Alike Licence v3.0</a> or any later version`](https://github.com/mozilla/addons-server/blob/562ce3dc2fca04c4b3bd722e14b4a169eb47c7cb/locale/en_US/LC_MESSAGES/django.po#L5445)

**Comment by peiying2** [comment]
@diox Not sure who can fix this, tagging you for now. Thank you.

**Comment by diox** [comment]
Thanks, I'll fix it. The good news is that most strings in the footer were untranslated for years and nobody noticed, so fixing this, even if that means invalidating all current translations, shouldn't be too bad...
