### ISSUE TITLE
“Attempt limit exceeded” warning message received after performing a login

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2130]
Steps to reproduce:

1.Open firefox add-ons page: https://addons.mozilla.org/en-US/firefox/
2.Click on “Log in” link, introduce your email address and press “Continue”.
3.In login page press “Sign in” button.

Expected results:
User is logged in with his account.

Actual results:
User receives a warning message “Attempt limited exceeded”..

Note/Issues:
This issue is reproducing intermittent in AMO-dev,  AMO-stage and production.
Video to this issue: http://screencast.com/t/V19N048xK

**Comment by cosminbadescuSV** [comment]
After this warning message if user try to make a new account it will be redirected to login page and will receive same message.
See the video: http://screencast.com/t/DGfymUTMwj9S

**Comment by mstriemer** [comment]
I think you only get 5 failed password attempts then you have to wait 15 minutes to try again. Perhaps you hit that while testing?

**Comment by mstriemer** [comment]
If you're still hitting this next time you try please reopen but hopefully it's just the really low attempt limit that we're dealing with.

5 failed attempts within 15 minutes (even with successful password entries in between) will block you for 15 minutes.

**Comment by cosminbadescuSV** [comment]
I can still reproduce this issue  http://screencast.com/t/pybg0pvA3x

**Comment by cosminbadescuSV** [comment]
This issue is not reproducing anymore, see the video: http://screencast.com/t/NTaUxRTEHR
