### ISSUE TITLE
Add rate limiting to abuse appeal form

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21302]
Abuse appeal form should be rate-limited to a reasonable value (20 / day like reporting? more?), both for `GET` and `POST`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-522)

**Comment by alexandruschek** [comment]
Hello @diox,

I'm currently testing the post requests, these are the notes that I made:
New user created for these cases: aschek+qa-test-user-2@mozilla.com
Case 1:
7 post requests under 30 seconds for the same addon with the same body. 
Result: No throttle

Case 2:
20 post requests under 5 minutes for the same addon with the same body: 
Result: 429 - Too many requests

Case 3:
After getting throttled on reporting addons, I will try to report:
A collection:
Result: 429 - Too many requests
A user:
Result: 429 – Too many requests
A rating:
Result: 429 - Too many requests
Also, @ioanarusiczki tried the post requests unauthenticated and for the 6 per hour limitation: No throttle, but after 20 requests, she was not able to send more requests, even if she was authenticated.

Question:
Abuse reports are using the POST methods, what are the GET?

Thank you!

**Comment by alexandruschek** [comment]
Hello, marking this issue as fix verified, because any problems encountered here were entered in a follow-up issue, in this case issue: https://github.com/mozilla/addons-server/issues/21738

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-522
