### ISSUE TITLE
Do not show Facebook or Twitter icons when sharing an addon from a collection

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2131]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Open any collection
2.Press the share button for an addon listed inside this collection

Expected results:
 Facebook or Twitter icons are not displayed

Actual results:
 Facebook or Twitter icons are displayed

Reproducible in prod or Stage

![icons](https://cloud.githubusercontent.com/assets/1583842/14206741/d9ed7214-f81d-11e5-8f22-87700a030f48.png)

**Comment by andymckay** [comment]
We should just remove this feature like we have everywhere else.

**Comment by vcarciu** [comment]
Verified as fixed : 
![noshare](https://cloud.githubusercontent.com/assets/1583842/15180987/5f4f3f4e-178d-11e6-8e0d-641b3e332363.png)
