### ISSUE TITLE
Issues loading code manager files on -dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21315]
1. Try to open a browse or compare page with code-manager

Result:
lots of 404 , the content is not displayed 

<img width="1728" alt="code-managerpng" src="https://github.com/mozilla/addons-server/assets/33448286/ca8f9607-f37d-4993-b4b6-1c1178c9e3d8">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-527)

**Comment by bqbn** [comment]
The objects in GCP storage bucket expired. Apparently, the lifecycle rule got migrated from AWS to GCP. 

I filed https://github.com/mozilla-it/webservices-infra/pull/1090 to fix the lifecycle rule.

We also re-pushed code manager and the assets should have been there now.

**Comment by ioanarusiczki** [comment]
This is fixed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-527
