### ISSUE TITLE
Recommended add-ons should not have 120.0a1 set after submission

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21318]
Followup for https://github.com/mozilla/addons-server/issues/21293 

1. With dev hub submit a new version for a recommeded add-on and choose the Android platform 
2. Click on Android 

Expected result:
They should not have Android compatibility pop-up displayed

Actual result:
The Android pop-up is displayed then after submission the compatibility is set to 120.0a1 

Notes:
Submitting a new version using the API with android compatibility in manifest.json (strict_min set to 78.0 for Android) , response will return 120.0a1
This is not reproducible with line extensions
It is reproducible on -dev only

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-528)

**Comment by ioanarusiczki** [comment]
Closing this issue because I forgot to check the platform compatibility in admin - seems to be alright, since there are recommeded extensions which are compatible only on Firefox and this would be my case above, it's an expected behavior.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-528
