### ISSUE TITLE
ID issue with extension

### ISSUE THREAD

**Issue by madprops** [mozilla/addons-server#21325]
I have an extension with around 150 users. I'm thinking of making a version 2 of it.

I'm doing this new version because the old one uses a temporary ID, and now I want to use features that require an explicit extension ID. Changing the ID is confusing plus it would delete all settings of all users, so I decided to make this new listing.

This of course has some drawbacks, makes things more complicated. So my question is, is there a way to fix the ID issue without submitting a new version?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-530)

**Comment by madprops** [comment]
Extension in question is https://addons.mozilla.org/en-US/firefox/addon/grasshopper-urls/

The desired new ID would be: grasshopper@tabmanager

**Comment by madprops** [comment]
Nvm now.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-530
