### ISSUE TITLE
Add location to abuse api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21330]
For add-ons we want to be able to distinguish abusive content found in the add-on details on AMO, and inside the add-on itself.

server companion to https://github.com/mozilla/addons-frontend/issues/12476

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-532)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-532
