### ISSUE TITLE
Extensions developers newsletter signup confirmation email is not sent

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21335]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Extensions developers signup confirmation email is not sent on -dev and -stage
### What happened?
1. Go to Devhub Homepage 
2. Enter an email in the email input field
3. Check the newsletter privacy checkbox
4. Click the Sign-up button
5. Wait for the confirmation e-mail
6. After 20 minutes the confirmation e-mail was not received
### What did you expect to happen?
To receive on the e-mail address used for sign-up the e-mail confirmation
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Emails used:
aschek+test-user5@mozilla.com
pulvwjpcam@restmail.net
irusiczki+1003@mozilla.com

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-534)

**Comment by diox** [comment]
That form goes directly to https://www.mozilla.org/en-US/newsletter/ (regardless of the env) so it's an issue with bedrock and/or basket.

**Comment by diox** [comment]
This was an issue on basket with the email confirmation, it's been fixed since.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-534
