### ISSUE TITLE
UI issues in Part of these Collections" section from an addon details page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2134]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Open an addon which is part of 3 or less collections
2.Observe the "Part of these Collections" section in its details page

Expected results:
If the addon is part on three or less collections, show these collections in one single row

Actual results:
Even if the addon is part on three or less collections, the  "Part of these Collections" section is displayed like we have two rows of collections

![partofcoll](https://cloud.githubusercontent.com/assets/1583842/14207862/3890d7e6-f825-11e5-8dd5-6105f5f02772.png)

**Comment by muffinresearch** [comment]
@vcarciu can you provide a link to an example please.

**Comment by muffinresearch** [comment]
Ah here's an example https://addons-dev.allizom.org/en-US/android/addon/flash-video-downloader/
