### ISSUE TITLE
Allow Abuse reports to be sent against Rating

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21349]
Flagging Ratings is eventually going to be done through Abuse Reports, going through Cinder. Which means we need to:
- Add a new FK in `AbuseReport` pointing to `Rating`, updating `target` & `type` properties to support ratings
- Add a new `CinderRating` class to describe the rating entity when interacting with Cinder, update `CinderReport` model to use it. The entity also needs to be created in Cinder itself.
- Add support for appealing decisions tied to a `Rating` in the appeal flow
- Add support in the abuse API for reporting ratings through a `rating` field that corresponds to the `pk` of the `Rating` to report

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-538)

**Comment by diox** [comment]
Frontend side of things: https://github.com/mozilla/addons-frontend/issues/12507

**Comment by diox** [comment]
QA: you can test that it's now possible to submit abuse reports against ratings using the API (I've updated the docs) and view such abuse reports in the admin. Ignore the `Cinder` bits mentioned in the description for now.

**Comment by diox** [comment]
> [admin model ](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/)specified the type:Rating , reason and message are displayed , there's no rating ID field or any other information (addon id/guid or addon name). 

Can you file a follow-up for this ?

**Comment by ioanarusiczki** [comment]
@diox I filed https://github.com/mozilla/addons-server/issues/21399 for rating id field to be added in the admin model.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-538
