### ISSUE TITLE
change the mza launch date (server)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21343]
The time needs adjusting to 16:00 UTC, still November 1st 2023 as per https://docs.google.com/document/d/1KMXaqN82e0U1l0V6K0rz85Imu25qUwqhOTRDkBRmEvM/edit

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-536)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-536
