### ISSUE TITLE
Update appeals copy

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21346]
The appeals form copy needs to be updated to match what legal provided.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-537)

**Comment by ioanarusiczki** [comment]
@diox 

Could you give some str for qa? 
I did not see this form before.

**Comment by diox** [comment]
That form is not currently accessible on dev/stage/prod and everything around it is still WIP, I'll mark as qa not needed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-537
