### ISSUE TITLE
DSA: Move force-disable button into reviewer action

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21356]
The existing force-disable button for add-ons needs to be moved into the reviewer actions, so that a reviewer can select a reason and a write a response or use a canned one.
This means that for the force-disable action, the reason and the response are mandatory fields.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-544)

**Comment by eviljeff** [comment]
@wagnerand we should replace the force-enable button too - they're a toggle so makes sense to do the same for the opposite action.  I'm assuming we _don't_ want to email developers if we force enable?  
... or do we?  If so need some details about if comments are mandatory and some guidance on copy.

**Comment by eviljeff** [comment]
> re-enable those &lt;versions&gt; with force-enable, this is probably out of scope for this bug though

out of scope for this issue, yeah, but we do need to address that as part of the DSA work (for appeals and overrides)

**Comment by eviljeff** [comment]
> > re-enable those <versions> with force-enable, this is probably out of scope for this bug though
> 
> out of scope for this issue, yeah, but we do need to address that as part of the DSA work (for appeals and overrides)

@wagnerand this landed with https://github.com/mozilla/addons-server/issues/21352 fwiw - now enable and disable are reversible.

**Comment by alexandruschek** [comment]
Hello,

 I've tested this on stage env and force disable/enable actions work as expected, I've also noticed that the force enable does not appear in add-on history, only in add-on important changes history
 
<img width="1365" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/0a376c93-59cd-48f2-b0c7-0b901fa02f73">

Thank you!

**Comment by eviljeff** [comment]
it's because the addon history only shows activity logs linked to a version, and the force_enable activity doesn't have an associated version (the force disable action gets linked to whatever is the current or latest version at the time of the disable).  If @wagnerand has opinions on this I can address in a follow-up.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-544
