### ISSUE TITLE
Handle decisions from Cinder about users

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21355]
In the webhook for Cinder (https://github.com/mozilla/addons-server/issues/21194) we need to handle decisions about users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-543)

**Comment by ioanarusiczki** [comment]
@diox 

In AMO Dev Content Infringement queue from Cinder I found reported users. What I see is their ID Name, Email. On the right I can choose an action and submit. 

I don't see a correlation between the report here and the one from AMO admin, the report's id or the reason it was reported. 

If I could make a gif about what I am talking it would be easier, let me know if I can post images from Cinder here. 

I am not sure what to do further so please let me know what to verify.

**Comment by ioanarusiczki** [comment]
@diox I'll check all scenarios possible from Cinder and see what happens on AMO for users reported.

**Comment by ioanarusiczki** [comment]
@diox 

I've sent from -dev reports for 3 users and I used all reasons that should send the report to Cinder, meaning  D, E, F [report categories 
](https://docs.google.com/document/d/1INxBf3-L-LcBzL9q-hBGD_BmoT5NLty__f66WLV5W3o/edit#heading=h.bkg6hev4zbcq)

The reason chosen by the reporter matters for the feedback being sent to Cinder or not. Then, Moderator can choose in Cinder  the following: 

![Choices](https://github.com/mozilla/addons-server/assets/33448286/2041b071-2298-4396-8bb6-b7a58505bf5d)

- Ids I've tested with: 10641564, 10640485, 6683742

For "Hate Speech", " Sexual content"," Illegal goods" and services and "Terrorism and violent extremism" users 10641564 and 6683742 
were banned on AMO.  User 10640485 was not -> I don't know why 

For "Violent content" all 3 were still displayed -> I think all 3 should get a ban

For "Ignore" action -> all user profiles are still displayed , this is expected 

-  "Hate Speech" and" Illegal goods and services" does not have a "Remove" when chosen (all other actions have it except for Ignore which is expected not to have it)

![remove in cinder](https://github.com/mozilla/addons-server/assets/33448286/59bb6790-8115-4335-92df-ca1ddb232836)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-543
