### ISSUE TITLE
Handle decisions from Cinder about themes

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21354]
In the webhook for Cinder (https://github.com/mozilla/addons-server/issues/21194) we need to handle decisions about themes (see also https://github.com/mozilla/addons-server/issues/21352)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-542)

**Comment by eviljeff** [comment]
We can't think of anything special we need to do in code to handle decisions on themes, so QA procedures for https://github.com/mozilla/addons-server/issues/21352 should be repeated, but for a theme.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Verified on AMO dev https://github.com/mozilla/addons-server/issues/21352#issuecomment-1808368681

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-542
