### ISSUE TITLE
 Handle decisions from Cinder about collections

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21353]
In the webhook for Cinder (https://github.com/mozilla/addons-server/issues/21194) we need to handle decisions about collections.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-541)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Please add some str.

**Comment by eviljeff** [comment]
Just focusing on the non-cinder changes (QA for the webhook integration is part of #21194 and a bigger piece of work): soft delete for collections has been implemented, so check that deleting a collection works, and releases the slug to be reused by the user for a new collection.

**Comment by alexandruschek** [comment]
Hello,

Just checked the following scenarios:
- accessing the collection page unauthenticated
- create a collection
- edit collection details, removing add-ons, leaving notes
- Deleting a collection and it's possible to re-use the slug.
- The slug is not available for use if there is already a collection created with the same name

Marking this as fix verified.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-541
