### ISSUE TITLE
Parsing error and more

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#21365]
Communities reported the following two issues: 

1). [`Invalid combination of %s" and "%s" parameters`](https://pontoon.mozilla.org/en-CA/amo/LC_MESSAGES/django.po/?string=286660)

First ` %s"` is missing a quotation mark.

2). [`Addon slug changed`]( https://pontoon.mozilla.org/en-CA/amo/LC_MESSAGES/django.po/?string=285782)

`Addon` should be `Add-on` to be consistent with the rest of in the file.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-547)

**Comment by peiying2** [comment]
@diox

**Comment by diox** [comment]
I already fixed the first one but haven't re-generated locale files yet. I'll fix the second one and re-generate, thanks.

**Comment by diox** [comment]
(Next extraction will fix those strings)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-547
