### ISSUE TITLE
Allow Abuse Reports to be filed against themes

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21362]
Abuse Reports against themes need to be possible (already the case, will need some tweaks) and be passed to Cinder.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-546)

**Comment by diox** [comment]
As mentioned in description it already works but we need to send more data. In particular we need to the send background images, so the key will be to figure out how to deal with sending the them (we already have an util to extract them for a particular version and return base64) to Cinder.

**Comment by ioanarusiczki** [comment]
@diox 

Reports with themes are working -> Cinder would send a decision (except for Ignore) all other policies remove the theme's detail page from AMO - it disabled the theme.

I don't see theme images in Cinder on -dev. This is Cinder theme details:

![Cinderthemedetails](https://github.com/mozilla/addons-server/assets/33448286/3b04f578-bf15-43dd-a1e2-ed3c52286bcd)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-546
