### ISSUE TITLE
Allow Abuse Reports to be filed against Collections 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21361]
Abuse Reports against Collections need to be possible and be passed to Cinder.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-545)

**Comment by diox** [comment]
QA: see https://github.com/mozilla/addons-server/issues/21349#issuecomment-1790682006, same thing here expect with a collection `id` instead of a rating.

**Comment by ioanarusiczki** [comment]
@diox 

I could send reports with https://addons-dev.allizom.org/api/v5/abuse/report/collection/

- 'message' is not mandatory when there is a 'reason'
- when both are missing I get an error that `message` is required
- for the collection id in admin you've updated https://github.com/mozilla/addons-server/issues/21399

**Comment by ioanarusiczki** [comment]
@diox 

To add: the reports can be sent with and without authentication.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-545
