### ISSUE TITLE
Put add-ons in the queue when reported for Policy Violation in the add-on

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21375]
When an Abuse Report is created for `POLICY_VIOLATION`, and the location reported is `ADDON` or `BOTH`, it needs to be put in the reviewer queue through `NeedsHumanReview`, with a specific reason explaining to the reviewer an abuse report was filed against it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-549)

**Comment by eviljeff** [comment]
Note: we'll need a different queue for reports that we want to log in Cinder but we don't expect T&S/TaskUs to handle (i.e. reports we'll handle in AMO reviewer tools)

**Comment by ioanarusiczki** [comment]
@diox 

I tried with "it violates the law ... " and location Inside the add-on or Both locations but I don't see them flagged for human review in the Manual Review queue. Tried with "It violates Add-on policies" too , same result.

**Comment by diox** [comment]
@ioanarusiczki sorry, forgot to add: you need to turn on the `enable-cinder-reporting` waffle switch first (it does more behind the scenes that we're not ready to let you verify, but it should unblock testing of this particular issue)

**Comment by ioanarusiczki** [comment]
@diox 

I tried again after enabling the waffle switch but it's the same result. Or should I see these reports elsewhere? I got access to stage.cinder.nonprod 

I see there some queues but they're empty.

**Comment by eviljeff** [comment]
> @diox
> 
> I tried again after enabling the waffle switch but it's the same result. Or should I see these reports elsewhere? I got access to stage.cinder.nonprod
> 
> I see there some queues but they're empty.

The cinder integration should _just now_ be working.  But it seemsyYou've hit a bug with authenticated reports - https://mozilla.sentry.io/issues/4619894006/

**Comment by eviljeff** [comment]
> > @diox
> > I tried again after enabling the waffle switch but it's the same result. Or should I see these reports elsewhere? I got access to stage.cinder.nonprod
> > I see there some queues but they're empty.
> 
> The cinder integration should _just now_ be working. But it seems you've hit a bug with authenticated reports - https://mozilla.sentry.io/issues/4619894006/

https://github.com/mozilla/addons-server/issues/21421

**Comment by ioanarusiczki** [comment]
@eviljeff 

I can login and view [these queues](https://stage.cinder.nonprod.webservices.mozgcp.net/queues) and I sent reports again but I don't see add-ons being present here or in rev tools - dev or stage. I tried from dev the stage since it's stage.cinder

**Comment by ioanarusiczki** [comment]
@eviljeff 

I had all type of reported content in 
[AMO Dev Content Infringement](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjIz/details) 

Now it is empty because I started processing them. I saw rating, addon and user reports. Then I made new addon reports but I don't see them yet. 

My question is now , should I see for add-ons only the scenario [described](https://github.com/mozilla/addons-server/issues/21375#issue-1970469749) by @diox  

And should I see there all reports for users, ratings or collections ?

**Comment by eviljeff** [comment]
reports that are for add-ons, and the location is specified as inside the add-on, should be going into [AMO dev addon infringement](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjI1/details); everything else should be in [AM dev content infringement](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjIz/details)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I only have content into AMO dev content infrigement. It looks like addons show up in here too 

The addon queue is empty 

![addon in content](https://github.com/mozilla/addons-server/assets/33448286/d5d6b857-6d2d-4098-b1df-7cda10ec52cd)

**Comment by eviljeff** [comment]
@ioanarusiczki if the report is for a policy violation ("It violates our policies") _and_ the place of the violation is "Inside the add-on" or "both" then:
- the report should be in AMO dev addon infringement
- and the latest* versions (in each channel) should be flagged for needs human review in the reviewer tools
- *the latest versions are flagged if the addon is not installed by the user in Firefox; if the addon is installed the installed version is sent in the report and (only) that version is flagged instead.

(I gave it a quick try on addons-dev now and it seems to be working for me)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Yes, I realized today I was reporting "it violates the law" instead of "it violates our policies" 

I see in the Manual Review Queue extensions being flagged with "Reported for abuse within the add-on" 
Example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/625016

But I don't get lucky in Cinder, AMO dev addon infringement.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified the scenarios for addons uninstalled and then with versions installed.  - works as expected 
These reports are also present in Cinder into AMO Dev Add-on Infringement.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-549
