### ISSUE TITLE
switch to ruff format from black

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21383]
see https://astral.sh/blog/the-ruff-formatter

`ruff` has added a `ruff format` function to replace `black`'s formatting functionality.  As we already use `ruff check` and it's super fast (because rust), we should switch over.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-550)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Please add str. 
Thanks

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-550
