### ISSUE TITLE
Fix submit theme masthead cramped top margin

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2138]
<img width="581" alt="create_a_new_theme____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14208831/388488b2-f819-11e5-9d38-9a7cce503e62.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![cramphead](https://cloud.githubusercontent.com/assets/1583842/14210850/950d8272-f833-11e5-8888-bc4bd5982a64.png)
