### ISSUE TITLE
Call Cinder for Abuse Reports filed against users 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21386]
It's already possible to file abuse reports against users and some Cinder integration will already be there automatically following refactors from https://github.com/mozilla/addons-server/issues/21349, but it needs to be checked and completed as necessary.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-551)

**Comment by diox** [comment]
QA: ignore the cinder integration, but please ensure a `reason` can be given when filing an abuse report against a user with the API. If it's absent, it should still be possible to file the abuse report, but a `message` needs to be provided.

The docs should be updated with what `reason` are valid for a user abuse report.

**Comment by ioanarusiczki** [comment]
@diox 

- I could send `message`  without `reason` -> response returns `reason`: null

- I could send `reason` using the 3 options specified in [docs](https://addons-server.readthedocs.io/en/latest/topic/api/abuse.html#abuse-user-reason-parameter) without `message` -> response returns `message`: " "

- when `reason` and `message` are not specified -> response is a 400, `  "message": [ "This field is required."]`

- response is 200 with "user ", "reason" ,  "message" ,  "reporter_name" and "reporter_email" specified

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-551
