### ISSUE TITLE
Add rating & collection support in the abuse report model admin

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21399]
When an abuse report is made against a rating a rating ID is required (sending it using the api)

Expected result:
the rating id should also be displayed in the admin model

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-554)

**Comment by diox** [comment]
Edited the issue to reflect the fact that we'll need to do this for collections as well once https://github.com/mozilla/addons-server/issues/21361 is implemented

**Comment by eviljeff** [comment]
> @diox
> 
> When going to filter By type each category would display a search bar.
> 
> Searching multiple collections/ratings worked collections 5497705, 5497651,5497624,5497615,5497979 ratings 567466,564832,567261, 565040,5497615
> 
> A search with a single ID for collections won't return results. For ratings (or addons) I got the result (except when I searched with the last id from the list above)

what I added (and I should have mentioned!):
- ratings
  - id
  - text search for within the rating body
  - (and the abuse report message)
- collections
  - slug
  - (and the abuse report message)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-554
