### ISSUE TITLE
refresh site welcome message

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2140]
First time AMO users will see this message. We should refresh its design to work with the new design.
New yours will also be people redirected to AMO from disco pane.
![screen shot 2016-03-29 at 17 12 05](https://cloud.githubusercontent.com/assets/8145891/14209379/e9632332-f7f1-11e5-8f79-46933367ea2f.png)

@pwalm how do you think we should do that?

**Comment by pwalm** [comment]
Let's remove the little triangle from the speech bubble and follow these parameters:

/* Prompt shape Copy: */
background: #FBFBFB;
border: 2px solid #1F386E;
border-radius: 6px;

/* Welcome to Firefox A: */
color: #333333;
(keep the same type/icon styling)

**Comment by tofumatt** [comment]
Thanks! In the future, please remove the "needs ux" label and un-assign yourself once this is ready to be taken by a developer :smile:

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-05_1000](https://cloud.githubusercontent.com/assets/15685960/14273738/6c40b898-fb15-11e5-954f-3a0fb234baad.png)
