### ISSUE TITLE
return distinct response codes with cinder webhook

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21402]
Currently we return 201 in the response for all webhook requests.  After discussing with ashwin on slack we will consistently return 201 for a request we've handled, and 200 for other requests.  If the request is malformed - e.g. multiple actions, which we can't handle, we will return an error code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-556)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-556
