### ISSUE TITLE
Login is failing on dev environment

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21401]
### Describe the problem and steps to reproduce it:
Unable to login on dev environment

### What happened?
Logging with any type of user receives error: "System unavailable, try again soon"
### Anything else we should know?
<img width="1728" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/e575e936-d4e8-4c62-b872-e8ee9914f210">
<img width="1118" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/6e132d56-a26e-41da-a1e6-8bb7c40ab46d">
<img width="1728" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/78b015f2-3889-42d2-b19e-1fae82cd10a4">
<img width="1728" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/fa099cff-83dc-4281-bee0-c27ca9d8a196">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-555)

**Comment by diox** [comment]
This is a Firefox Accounts problem.

**Comment by diox** [comment]
That was fixed by FxA's SREs.

**Comment by vcarciu** [comment]
The fix was observed and issue marked as verified.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-555
