### ISSUE TITLE
Statistics page menu isn't indented properly

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21418]
The statistics page menu items specific to each type of stat (downloads / users) should be indented. We should see something like:
- Overview
- Downloads
  - by Source
  - 'by Medium
  - by Content
  - by Campaign
- Daily Users
  - by Add-on Version
  - by Application
  - by Language
  - by Platform
  - by Country

However, that's not the case at the moment, everything is flat. It likely broke a long time ago in https://github.com/mozilla/addons-server/issues/18792. Here is what we currently see:
<img width="255" alt="Screenshot%202023-11-09%20at%2015 43 13" src="https://github.com/mozilla/addons-server/assets/187006/0b040666-75b0-48c5-9c53-25d21540e607">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-559)

**Comment by ioanarusiczki** [comment]
@diox 

Fixed on AMO dev

![fixed](https://github.com/mozilla/addons-server/assets/33448286/57aff5d3-a055-4a9a-aa0f-4ada935eab68)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-559
