### ISSUE TITLE
site welcome message breaks layout on dismissing it

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2141]
![amo-welcome-dismiss-break](https://cloud.githubusercontent.com/assets/8145891/14209601/ed63c684-f7f2-11e5-81ab-341a159005c3.gif)
User gets this message the first time the visit AMO. I can get it again after deleting AMO cookies.
(Seen on Firefox Relsease on Windows 10)

**Comment by muffinresearch** [comment]
@tofumatt I really think we *do* need to change the markup here. All the height settings for the background are too fragile being based on JS. The element that has the background needs to wrap the content. 

One thing is that at least being the homepage this should be limited to that one page.

**Comment by tofumatt** [comment]
I believe the background wrapper is set that way on _every_ page.

But I agree, we should figure out a better way to do this. I can take this one.

**Comment by madalincm** [comment]
Verified as fixed in FF45(Win7) in addons-dev.allizom.org
Postfix screencast: http://screencast.com/t/a7v6jp11
