### ISSUE TITLE
Update Add-on recommendations fallback guids

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21412]
We haven't updated the add-ons used as fallback for add-on recommendations since 2018. Per @devaneymoz in https://mozilla-hub.atlassian.net/browse/AMO-122 we should use:
- `addon@darkreader.org` (Dark Reader)
- `treestyletab@piro.sakura.ne.jp` (Tree Style Tab)
- `languagetool-webextension@languagetool.org` (LanguageTool)
- `{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}` (Search by Image)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-558)

**Comment by ioanarusiczki** [comment]
@diox 

Initially there were only 2 guids available but after I made the other 2 public the section displays the fallback guids at all times (which has always been like that on -dev and -stage) 

The section is having a little delay loading content but that's also an old issue. 

![other popular extensions](https://github.com/mozilla/addons-server/assets/33448286/2d44e779-856f-41ec-88d0-33ac95259d87)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-558
