### ISSUE TITLE
Add tests for passing an id as integer in the abuse report API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21427]
For user/addon/rating/collection pk, abuse report API should allow strings or integers to be passed. Let's add tests for that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-562)

**Comment by eviljeff** [comment]
.... we do state in the api docs that it's a string though?

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-562
