### ISSUE TITLE
Drop auth requirement on the endpoint that allows users to flag ratings (user reviews)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#21425]
The DSA spec says that we should drop the authentication requirement on the [Flag endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#flag) so that users can report feedback unauthenticated.

At the moment, fixing the frontend code isn't enough:

<img width="450" alt="Screenshot 2023-11-13 at 11 24 59" src="https://github.com/mozilla/addons-server/assets/217628/369ad8fc-9a57-4a23-9a16-2798ee713bcc">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-561)

**Comment by willdurand** [comment]
In fact, we don't need that. So we can wontfix this bug.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-561
