### ISSUE TITLE
Manual approval of a pending unlisted version should clear pending rejection for that version

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21438]
### Describe the problem and steps to reproduce it:

A manual approval of an (non-approved) unlisted version that is pending rejection should clear any pending rejections for that version.

STR:
1. Submit an unlisted version, make sure it is not auto-approved
2. Delayed reject the version
3. Approve the version

### What happened?

After the deadline for the delayed rejection is up, the version is rejected.

### What did you expect to happen?

The version should not be rejected automatically as part of the delayed rejection.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-566)

**Comment by diox** [comment]
Note: this only applies to unlisted, because `ReviewUnlisted` redefines `approve_latest_version`. Initially delayed rejection of unlisted were not a thing, but when that was added in https://github.com/mozilla/addons-server/issues/19371 this became a problem.

**Comment by GregSherman** [comment]
commenting for assignment

**Comment by alexandruschek** [comment]
Hello,

I tested this on dev environment, no issue encountered.
Marking as fix verified.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-566
