### ISSUE TITLE
Ignore unsupported enforcement actions in cinder webhook

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21436]
Currently we raise an exception if we get a webhook request with any unknown enforcement actions in it (or no actions).  This limits what the structure of the policies can be on cinder (no shared policies) so it would be better if we change to ignore unknown actions, and only raise if there is no action at all that AMO supports.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-565)

**Comment by ioanarusiczki** [comment]
@eviljeff In case this can be verified by qa please add some str.

**Comment by eviljeff** [comment]
@ioanarusiczki this is one of the many bugs we've found and had to fix to actually get the decision integration with cinder working - when it eventually works (e.g. you can process an add-on report in cinder by choosing a policy like "Hate Speech" which would send the action DISABLE_ADDON) and it actually disables the add-on, the issue will have been fixed.

**Comment by ioanarusiczki** [comment]
@eviljeff I just noticed a theme being disabled indeed and I might have reported exactly that. Ok, I'll look around.

**Comment by ioanarusiczki** [comment]
@eviljeff I filed https://github.com/mozilla/addons-server/issues/21513

"Ignore" will not remove the content from AMO

Except for "Ignore" all the other actions from below will ban a user, delete a rating/reply, disable an extension, theme or dictionary.

![Choices](https://github.com/mozilla/addons-server/assets/33448286/2041b071-2298-4396-8bb6-b7a58505bf5d)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-565
