### ISSUE TITLE
Add a little padding between header title rows in developer hub

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2144]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/developers/
2.Observe the "Add-on Developer Hub " header title

Expected results:
There is a little padding between "Add-on" and "Developer Hub"

Actual results:
No padding between the two words

![padding2](https://cloud.githubusercontent.com/assets/1583842/14211436/c13473f8-f836-11e5-9331-7803f033eed7.png)

**Comment by muffinresearch** [comment]
I'm not sure what the design intention was here. We'll need to get UX input on this.

@pwalm @designakt do you have a mock for this?

**Comment by pwalm** [comment]
No mock, just add 10px of padding between the two lines.

**Comment by vcarciu** [comment]
Verified as fixed : 
![devhubb](https://cloud.githubusercontent.com/assets/1583842/15242177/580a3768-18fd-11e6-9182-d299fda74d6e.png)
