### ISSUE TITLE
Pass images to Cinder moderators and allow restoring them on successful appeal after deletion

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21445]
- Blocks https://github.com/mozilla/addons-server/issues/12625
- Blocks https://github.com/mozilla/addons-server/issues/21362
- Blocks full metadata handling for extensions reports as well

When a report is made against content containing images (*), we need to:
- Be able to pass those images to Cinder moderators
- Be able to completely prevent access of those images to end-users when the content is disabled/deleted
- Be able to revert the decision and restore access to those images

(*) The images are:
- For users, the avatar (currently permanently deleted on user ban)
- For extensions, the previews & the icon
- For themes, the previews

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-568)

**Comment by diox** [comment]
Note: in Cinder, if we pass the image as a an attribute with the correct `mime_type` value, it will be displayed as an image https://docs.cinder.co/docs/schema#media-attributes

**Comment by diox** [comment]
QA: https://mozilla-hub.atlassian.net/browse/SVCSE-1619 blocks the full implementation. In the meantime, user reporting & banning/unbanning should work without that new feature.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-568
