### ISSUE TITLE
Soft-delete content user was the author of on ban, keeping track of those relationships

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21453]
To make it possible to unban users, when we ban them, we need to:
- Soft-delete instead of hard-delete their content
- Store the relationships somewhere
- Provide ability to restore the content & relationships

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-572)

**Comment by diox** [comment]
QA: when banning a user (not deleting) their banned content should appear in the user admin detail page if you have `*:*` permission. https://github.com/mozilla/addons-server/issues/12625 will later add unbanning functionality.

If multiple users are banned at the same time they should each get the correct banned content soft-deleted and appearing in that section.

**Comment by ioanarusiczki** [comment]
@diox 
 
I tried for one user -> all information is stored, except the profile picture. (known issue)

**Comment by ioanarusiczki** [comment]
@diox I made a multiple ban on the ids below: 

10641572,10642829,10642816,10642814

The tried to unban -> average ratings for developer's add-ons is restored for rusiczki.ioana@gmail.com

Only the profile picture won't be available

![user avatar](https://github.com/mozilla/addons-server/assets/33448286/0d494e89-37bb-4e73-b92f-a1761a779c35)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-572
