### ISSUE TITLE
Don't undelete content on approval by a Cinder moderator unless it's an appeal/override

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21452]
As currently written the cinder webhook will force enable content on approval. This creates the following scenario:
- User has some public content (add-on, rating, collection...)
- Content gets reported
- User deletes the content
- Moderator processes the report, approves the content

Expected results:
- The content stays deleted

Actual results:
- The content is put back up

To avoid this, if it's the initial decision taken, and therefore not an appeal/override, we shouldn't touch the content at all, just record the decision.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-571)

**Comment by ioanarusiczki** [comment]
@diox 

Not sure what you mean by "Moderator processes the report, approves the content"  

this is the list of actions on the right

![approves](https://github.com/mozilla/addons-server/assets/33448286/d0089aec-af03-4a39-858f-bf23a8a9b166)

**Comment by ioanarusiczki** [comment]
@diox 

I tried with ratings and collections - Ignore would keep the content on AMO deleted if the user chose to to so. 

Same for extensions when made invisible or disabled.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-571
