### ISSUE TITLE
  Bump add-ons for Android minimum compatibility to 121.0a1

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21458]
Just before Firefox for Android 120.0 is released (*), we need to bump Android minimum compatibility from 120.0a1 to 121.0a1 and migrate compatibility of existing add-ons, to avoid Android 120.0 users seeing those add-ons, as they should not be available on release yet (only Beta/Nightly).

(*) This will require a special push on November 20th.

See previous issue for 119.0: https://github.com/mozilla/addons-server/issues/21293

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-574)

**Comment by diox** [comment]
QA: ping me to run the command on dev

**Comment by ioanarusiczki** [comment]
@diox Ready, I am not noting any id down. I'll look around after it's done.

**Comment by diox** [comment]
Done (+ reindexed)

**Comment by ioanarusiczki** [comment]
@diox 

The new minimum allowed for Android in uploads is 121.0a1.
 
Been testing a bit around with uploads as for https://github.com/mozilla/addons-server/issues/21293#issuecomment-1764443499, looks good.

Already submitted versions after migration have 121.0a1 for Android. 

On Fenix 119.1.1 a restricted number of recommended add-ons (+a couple of lines in dev's case) so it's expected. 
On Fenix 121.0a1 a blank search would reveal 169 results (all type of extensions) which is again expected.

**Comment by ioanarusiczki** [comment]
@diox Can this go to -stage, or we must wait for Wei?

**Comment by diox** [comment]
I've just made the tag, it will automatically be built and deployed to stage.

**Comment by diox** [comment]
Stage deployed, I've ran the command and reindexed.

**Comment by ioanarusiczki** [comment]
@diox 
Lgtm 
Verified on AMO stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-574
