### ISSUE TITLE
Allow abuse reports to be sent against add-ons georestricted in your region

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21465]
STR:
- Find/create a public add-on with an `AddonRegionalRestrictions` for the region you're in
- Submit an abuse report against it using the API

Expected results:
- You can submit the report. Since the add-on is georestricted the response doesn't contain its info beside its `guid`.

Actual results:
- You get a 451 error

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-576)

**Comment by ioanarusiczki** [comment]
@diox

I sent using the API on dev https://addons-dev.allizom.org/api/v5/abuse/report/addon/ an abuse report for a geo-restricted listed and then unlisted extension and I got a 201 response -> unlike -stage where for both scenarios I encountered a 451 - Unavailable for legal reasons.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-576
