### ISSUE TITLE
Developer hub menu is not displayed correctly in some languages

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2146]
**Steps to reproduce:**
1. Open developers hub page: https://addons-dev.allizom.org/en-US/developers/
2. Change the language to Spanish using the Other languages drop down menu from the page footer.

**Expected results:**
There are no layout or display issues.

**Actual results:**
The menu is not visible and the page title is not correctly displayed.

**Notes/Issues:**
Verified in FF45(Win7) Issue can be reproduced in addons-dev.allizom.org
Issue can also be reproduced for other languages like french  or Italian.
Screencast for this issue: http://screencast.com/t/U5ZvaCmF76mw  http://screencast.com/t/6yvxMr1eO
http://screencast.com/t/SVCPZ6VLpB

**Comment by muffinresearch** [comment]
@tofumatt fwiw this is also containment related.

**Comment by ValentinaPC** [comment]
I think the same issue is reproducing in Public Pages. (I am in add-ons categories - https://addons-dev.allizom.org/it/firefox/extensions/download-management/ )
Please see the screenshot: 
![2016-04-04_1709](https://cloud.githubusercontent.com/assets/15685960/14250710/52c68ac4-fa88-11e5-8163-afea52d6b3d8.png)

**Comment by tofumatt** [comment]
While this is certainly now crammed, it is a lot better:

<img width="1000" alt="screenshot 2016-04-06 18 57 54" src="https://cloud.githubusercontent.com/assets/90871/14327282/8445831e-fc29-11e5-8095-2dd9a4772647.png">

But I'll see about adding some margins for other languages and closing this bug then.

**Comment by madalincm** [comment]
Verified as fixed in FF45(Win7) in addons-dev.allizom.org
Postfix screenshots: 
![langbugscrn1](https://cloud.githubusercontent.com/assets/15685441/14354431/f4ae2540-fce5-11e5-996f-5ed2e4e29318.png)
![langbugscrn2](https://cloud.githubusercontent.com/assets/15685441/14354441/f88805f0-fce5-11e5-8f7c-3b257c33bb4c.png)
