### ISSUE TITLE
Prevent `ActivityLog.objects.create()` from being called, or replace it with `ActivityLog.create()`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21471]
Calling `ActivityLog.create()` (custom `classmethod` on `ActivityLog` model) creates the `ActivityLog`, doing some magic to set the `_arguments`, the `user` responsible for the activity and creates the various `*Log` instances like `AddonLog`, `VersionLog` etc.

`ActivityLog.objects.create()` (default django creation mechanism) does not do any of that, so calling it is a trap that should be avoided! Fortunately we aren't currently using it in any production code, just a few tests.

We should:
- Look into whether we can create the various `*Log` instances automatically on creation through `post_save` or custom `save()` method
- Prevent `ActivityLog.objects.create()` from being used or move `ActivityLog.create()` into `ActivityLogManager()`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-577)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-577
