### ISSUE TITLE
Unlisted add-on blocked appear into manual queue without no reason

### ISSUE THREAD

**Issue by adelapopa98** [mozilla/addons-server#21481]
### Describe the problem and steps to reproduce it:
I saw this unlisted add-on in the manual queue today. I opened it, I saw that the add-on has only one version that was blocked 3 years ago. There was no reasons to be flagged in the queue. I manually cleared the needs human review flag to disappear from the manual queue. 
https://reviewers.addons.mozilla.org/en-US/reviewers/review-unlisted/2615895

### What did you expect to happen?
I expect these kind of add-ons to not appear into the manual queue.

### Anything else we should know?
![](https://github.com/mozilla/addons-server/assets/58764959/f16fdb77-8bcf-4648-984e-4303be39fe6a)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-579)

**Comment by diox** [comment]
Not sure why there is no needs human review in the main history, but I guess it was flagged because it hit a scanner rule ? That _should_ add a needs human review.

**Comment by wagnerand** [comment]
Yes I was surprised there is no reason logged on why it was flagged either. Could you think of a reason why a scanner would run on a version submitted in 2019?

**Comment by diox** [comment]
I'm not sure this is what happened, I don't have access to the scanner result. It could be it had a due date for a while, even before the introduction of the Needs Human Review system ?

**Comment by wagnerand** [comment]
> I'm not sure this is what happened, I don't have access to the scanner result. It could be it had a due date for a while, even before the introduction of the Needs Human Review system ?

It's rather unlikely, unless there were other factors that made it not appear in the queue. if it had been in the queue for a notable time, we definitely would have seen it as it would have bubbled up much earlier.

**Comment by eviljeff** [comment]
if this has only happened this one time, going to close this issue.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-579
