### ISSUE TITLE
Add-on version that has been approved manually got flagged for growth 

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#21483]
### Describe the problem and steps to reproduce it:
Add-on version got flagged for growth that was already manually approved

### What did you expect to happen?
Add-on versions that has been manually acted upon, like rejected, approved or confirmed by a human reviewer should be exempted from growth signal

### Additional info
Please see `2777171`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-581)

**Comment by wagnerand** [comment]
@abhn can you clarify whether it was the same version? That is important here. Add-ons are not flagged for review and reviewed, but only individual versions.

**Comment by abhn** [comment]
@wagnerand Yes, that's correct. Add-on version (`5516945`) was flagged for human review after it had been manually approved. Please see `2777171`

**Comment by diox** [comment]
This is already implemented. I suspect in this case the approval date predates the introduction of `human_review_date`, which was backfilled best we could but there are still gaps in certain scenarios where we couldn't be sure the approval was made by a human.

It shouldn't be possible with more recent approvals (after 2023-02-09).

**Comment by abhn** [comment]
@diox Thanks for the background on this. 

If that's the case and we won't see this for newer approved add-ons, we can close this as I suspect the number of add-ons falling into this category to be limited.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-581
