### ISSUE TITLE
handle cinder using - seperators in slugs rather than _

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21493]
When actions are added in cinder they are generated with dash rather than underscore characters.  It _is_ possible to hack around, but it's error prone.  Instead it'd be easier if we just changed the slugs generated for our `APIChoices` subclass to be (optionally) dashes instead of underscores.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-585)

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if I can check anything for this issue.

**Comment by eviljeff** [comment]
marking QA- because it's been verified with other issues - none of the decision actions worked otherwise

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-585
