### ISSUE TITLE
Reports are missing in Cinder when it is sent with name and email while unauthenticated

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21503]
Followup for https://github.com/mozilla/addons-server/issues/21194#issuecomment-1825770324

There's an issue with reports sent when user is unauthenticated and chooses to add a name and an email because I did not receive the reports in Cinder - I could reproduce it with extensions and collections. I received reports in Cinder every time I left File report anonymously checked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-589)

**Comment by diox** [comment]
https://mozilla.sentry.io/issues/4636165535/?project=6224627

```
{'detail': ["Entity schema amo_unauthenticated_reporter does not exist.
Valid entity types: ['amo_addon', 'amo_collection', 'amo_rating', 'amo_user', 'email', 'mozillasocial_account', 'mozillasocial_infringement', 'mozillasocial_media', 'mozillasocial_report', 'mozillasocial_reported_account', 'mozillasocial_status', 'user']"]}
```

**Comment by diox** [comment]
I added the missing `amo_unauthenticated_reporter` schema and added it to the `amo_reporter_of` relationship, which should have fixed this issue.

**Comment by ioanarusiczki** [comment]
@diox No longer reproducible when sending from -dev

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-589
