### ISSUE TITLE
Cinder reports fails when the authenticated reporter is also the author of the content

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21502]
As a followup for https://github.com/mozilla/addons-server/issues/21194#issuecomment-1825770324

 I did not receive Cinder reports for dictionaries, the following guids: 
af-ZAAPI@dictionaries.addons.mozilla.org and azdev2@dictionaries.addons.mozilla.org. I've sent ~5 reports for each but I found only one being present in Cinder

Notes:
This is only reproducible for dictionaries, feedbacks for extensions, themes, users, collections or ratings are working as expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-588)

**Comment by diox** [comment]
Here is the traceback: https://mozilla.sentry.io/issues/4620368574/events/dd792b7c48e64075ab3a3ce24eec5094/

I don't think this is related to dictionaries. Somehow Cinder is returning a `{"detail": ["Duplicate amo_user entity with ID 10641574"]}` error.

**Comment by diox** [comment]
It looks like this is happening because you're both the authenticated reporter and one of the authors of the content being reporter.

**Comment by diox** [comment]
We're including the `amo_user` twice in the `entities` we send to Cinder, once as an author, once as a reporter. I'm going to try deduping to see if that fixes the issue.

**Comment by ioanarusiczki** [comment]
@diox
I reported add-ons being authenticated and the author and I've seen these reports in Cinder.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-588
