### ISSUE TITLE
notify the target of an abuse report after a successful appeal has restored the content

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21501]
If we restore content after an appeal we need to notify the target the add-on/rating/collection/account is back, and restored.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-587)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I made "Revert decision" for an appeal for user 10641572
Also I tried "Revert decision" after an appeal made for [this extension ](https://addons-dev.allizom.org/en-US/firefox/addon/fourthtest/)

It did not see an e-mail and the user, add-on were still not available on AMO so I unbanned , enabled them from AMO admin so I can use them again for testing.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tested today with an extension and a rating resolving the appeal with "Adjust decision" - Ignore/Approve 

Content was restored and email is sent to the author. 

![email sent](https://github.com/mozilla/addons-server/assets/33448286/4cd5a852-0aa1-4f04-8941-b777a77d786f)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-587
