### ISSUE TITLE
notify the target of an abuse takedown

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21500]
When an abuse report has led to an addon disable, a user ban, or a collection/rating delete, by a moderator we need to notify the target what has happened, why, and how to appeal

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-586)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-586
