### ISSUE TITLE
Android GA 'sneak peek' list

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#21512]
Please see the ["sneak peek"](https://docs.google.com/spreadsheets/d/1iZ9HjcnOi1OHjI4skGyYGpeOWH_TOi8UKdvn9DYZlbY/edit#gid=0) tab for the list of GA extensions to release on 28 Nov.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-592)

**Comment by diox** [comment]
Per spreadsheet linked above the following guids will be hardcoded temporarily, giving them ability to select all Firefox for Android versions just like recommended add-ons:

  - android_scroll_bottom@davero.addons.mozilla.org
  - android_scroll_top@davero.addons.mozilla.org
  - admin@fastaddons.com_AutoHighlight
  - batterdarkerdocs@threethan.github.io
  - black-menu-for-wikipedia@carlosjeurissen.com
  - {c3c10168-4186-445c-9c5b-63f12b8e2c87}
  - deArrow@ajay.app
  - firefox-production@exactnote.com
  - formhistory@yahoo.com
  - ink-for-google@carlosjeurissen.com
  - jid1-TMndP6cdKgxLcQ@jetpack
  - {cb2b337b-99d7-4b86-aa04-84a6f5c3e218}
  - offline-qr-code@rugk.github.io
  - {9063c2e9-e07c-4c2c-9646-cfe7ca8d0498}
  - {60B7679C-BED9-11E5-998D-8526BB8E7F8B}
  - addon@rao-text-to-speech.com
  - {2b38afa0-3422-4988-95e4-43f59d2c8e7b}
  - reopen-in-private@apps.jeurissen.co
  - {c29f5416-192d-42ab-9da0-b4a82418752b}
  - s3@translator
  - simple_gesture@utb.dip.jp
  - sitedelta-watch@schierla.de
  - tetrio-plus@example.com
  - user-agent-switcher@ninetailed.ninja
  - unchecker@ad5001.eu
  - view-page-source@apps.jeurissen.co
  - avi6106@gmail.com
  - {1e41b6c3-1ae3-41eb-89fc-f5c5eb5c1301}
  - {034d548e-9728-4e5a-9133-8ea588e47200}

**Comment by ioanarusiczki** [comment]
@diox 

I picked for -dev the following guids and submitted versions compatible with Android 121.0a1:

[android_scroll_bottom@davero.addons.mozilla.org](mailto:android_scroll_bottom@davero.addons.mozilla.org)
{c3c10168-4186-445c-9c5b-63f12b8e2c87}
jid1-TMndP6cdKgxLcQ@jetpack
{60B7679C-BED9-11E5-998D-8526BB8E7F8B}
addon@rao-text-to-speech.com
deArrow@ajay.app

AMO stage:

 {034d548e-9728-4e5a-9133-8ea588e47200}
{1e41b6c3-1ae3-41eb-89fc-f5c5eb5c1301}
[avi6106@gmail.com](mailto:avi6106@gmail.com) 
[view-page-source@apps.jeurissen.co](mailto:view-page-source@apps.jeurissen.co)  
[unchecker@ad5001.eu](mailto:unchecker@ad5001.eu)

**Comment by ioanarusiczki** [comment]
@diox 

Guids above have been submitted having 121.0a1 as minimum compatibility. 

Now they're having 120.0 and a new version submitted would gain Fenix 113.0 when the strict_min is specified in the manifest.json and 48.0 when the compatibility is not specified (just as the recommeded/line extensions). An example https://reviewers.addons.allizom.org/en-US/reviewers/review/1019571

All add-ons from my comment above are present on Fenix 120.0 

I could install them on Fenix 121.0a1

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-592
