### ISSUE TITLE
Users are not getting a ban when Cinder decision is "Violent content" 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21513]
Followup for https://github.com/mozilla/addons-server/issues/21355#issuecomment-1827865760

For "Hate Speech", " Sexual content"," Illegal goods" and services and "Terrorism and violent extremism" users 10641564 and 6683742
were banned on AMO. User 10640485 was not -> I don't know why

For "Violent content" all 3 were still displayed -> I think all 3 should get a ban

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-593)

**Comment by diox** [comment]
The policies weren't set up correctly in Cinder, this should be fixed now.

**Comment by ioanarusiczki** [comment]
@diox 

It appears to be working for all policies now. 

I'll file a separate issue for the user profile I cannot ban https://github.com/mozilla/addons-server/issues/21523

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-593
