### ISSUE TITLE
Migrate .rst files to .md in our docs/

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons-server#21520]
### Describe the problem and steps to reproduce it:
Convert our restructured markup to markdown syntax. Following [this guide](https://docs.readthedocs.io/en/stable/guides/migrate-rest-myst.html)

### Anything else we should know?
Migrating to using markdown will have several advantages.

1. it is a more popular language
1. It is a simpler language
1. It will render in github preview pages in the browser (not useful for everyone but nice to have)

There are a few downsides

1. We may not be able to support all of the content formats we had in restructured as markdown does not support everything. See [here](https://docs.espressif.com/projects/esp-docs/en/latest/introduction/restructuredtext-vs-markdown.html#features) for more details.
1. It will require work to refactor the source .rst files to mardown (luckily there is a tool for at least partially automating this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-594)

**Comment by eviljeff** [comment]
Most of our docs are documenting the API request and response so if those are readable (or can be reformatted to be readable) then we're pretty much there, imo.

**Comment by KevinMind** [comment]
@eviljeff I'm not sure I understand the A -> B of your comment. Are you suggesting that they are readable currently, and may not be with .md files? Or that they are not and would need to be made so? OR something totally different?

FYI I have another [PR](https://github.com/mozilla/addons-server/pull/21521) for adding swagger json/ui which may in fact make a lot of those docs obsolete .

**Comment by eviljeff** [comment]
> @eviljeff I'm not sure I understand the A -> B of your comment. Are you suggesting that they are readable currently, and may not be with .md files? Or that they are not and would need to be made so? OR something totally different?

(i should have quoted) it was in reply to:
> We may not be able to support all of the content formats we had in restructured as markdown does not support everything. See [here](https://docs.espressif.com/projects/esp-docs/en/latest/introduction/restructuredtext-vs-markdown.html#features) for more details.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-594
