### ISSUE TITLE
Implement verifiy email flow

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons-server#21537]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-602)

### Email verified
given: email is not suppressed (.i.e. verified)
when: visit /developers/verify-email
then: you see the email verified page
when: visit /developers
when: visit /developers/*
then: you do not see the email suppression notification

### Email suppressed
given: email is suppressed (there is a SuppressedEmail instance matching the current logged in user)
when: visit /developers
when: visit /developers/*
then: you see the email suppression notification

### Create a verification
given: email is suppressed
when: click on the "verify email" button
then: POST request to /developers/verify-email is made
   if: an existing verification is found
   then: it is deleted
then: new Verification is created in DB
then: user is redirected to /developers/verify-email
then: user should see loader for up to 30 seconds (while we attempt to unsuppress the email and send notification)
   if: email is delivered
   then: user redirected again to /developers/verify-email, where they see a note that confirmation email is sent

   if: email is not delivered
   then: user will see note that delivery failed and they can try again. or change their email

   if: email takes longer than 30 seconds to send
   then: user will see note to check back later.

### Confirm a verification
given: email is suppressed, confirmation is created and verification status is "delivered"
when: `visit /developers/verify-email?code=<confirmation_code>` (i.e when you click the link in the email)
if: the verification is expired
then: user sees expired screen with option to retry
if: the verification code belongs to another user
then: users sees note not to steal codes
if: the code is totally invalid
then: redirect to /developers/verify-email
if: the code matches the current user verification
then: delete the suppressed email for the user (also deletes the verification) and show user verified email screen.

**Comment by KevinMind** [comment]
QA: Please review and ensure the above test cases are sound and don't lack any context.

**Comment by ioanarusiczki** [comment]
@KevinMind 

On AMO dev:

- I tried with the "suppressed-emails" waffle switch active to check Email verified and Email suppressed  when going to https://addons-dev.allizom.org/en-US/developers/verify-email  and while being authenticated. 

![suppressed](https://github.com/mozilla/addons-server/assets/33448286/d84f6984-316a-4fc8-ba74-0547b5717417)

Then, when I go to any other page on dev hub I don't see a notification. 

- With the waffle switch disabled https://addons-dev.allizom.org/en-US//developers/verify-email redirects to https://addons-dev.allizom.org/en-US/developers/addons

Let me know if I understood this right.

**Comment by KevinMind** [comment]
@ioanarusiczki you have successfully verified the first test scenario where your email is verified. 👍

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-602
