### ISSUE TITLE
Implement job to clear email from email suppression list

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons-server#21538]
After reviewing the flow with @wagnerand I decided we should split this one job into 2. So there will be two jobs implemented. The specs and acceptance criteria are below.

### Description and implementation details

This job is triggered by the post method of `/developers/verify-email` as a part of the initial request to "unsupress" and verify a user email. the view will dispatch this job which should include the `SuppressedEmail` record ID as a positional argument:

1. get the `SuppressedEmail` record for the given ID
2. make an API call to socket labs to remove the associated email from the suppression list
3. create an `EmailVerification` record associated with the `SuppressedEmail`
4. attempt to send the confirmation email to the associated email (including subset of code in subject to check with)
6. dispatch the second job to "check" the status of the sent email

#### Invalid suppressed email does not exist
1. given: invalid `SuppressedEmail` ID
2. then: 
- raises cannot find record error and does not retry
- error sent to sentry for debugging (should not happen)

#### Invalid verification already exists

1. given: a valid `SuppressedEmail` ID 
2. when: that record is associate with an existing `EmailVerification`
3. then: 
- the task raises an exception and does not retry
- error sent to sentry for debugging (should not happen)

#### Socketlabs returns 404

1. given: a valid `SuppressedEmail` ID
2. when: socketlabs API returns 404 response
3. then: does not raise as this is desired behaviour

#### Socketlabs returns HTTP error

1. given: a valid `SuppressedEmail` ID
2. when: socketlabs API returns non 200 or 404 response
3. then: raises Retry error

####  Happy path
1. given: valid `SuppressedEmail` ID
2. when: socketlabs call successful
3. then: 
- EmailVerification created
- mail sent to associated email
- verification confirmation code partial in email subject
- check email task dispatched

### Description and implementation details

This job is triggered at the end of the first job and will check in with socket labs to see if the email sent in the first job has been successfully sent, was suppressed for one or another reason, or is still "queued". This job is designed to run multiple times in case the email is still queued to a) ensure we give enough time to socketlabs to send the email and b) not block celery workers by having a long running job. The job will accept the EmailVerification record ID as a positional argument:

1. get the `EmailVerification` record for the given ID
2. query socket labs mail history for associated email address
- sort by sent date
- add from based on verification created date
- check for subject containing partial confirmation code
6. if we find an email, set the appropriate status on the verification (sent | failed)
7. if we don't find the email, raise exception to Retry (max retries set on job to try X number of times)

#### Invalid no verification found
1. given: an invalid `EmailVerificaiton` ID
2. then:
- raises not found error and does not retry
- error sent to sentry for debugging (should not happen)

#### socketlabs returns HTTP error
1. given: valid `EmailVerification` ID
2. when: socket labs returns Bad response
3. then: raise Retry error

#### socketlabs returns empty history
1. given: valid `EmailVerification` ID
2. when: socket labs returns empty history
3. then: raise custom retry error

#### socketlabs returns long history
1. given: valid `EmailVerification` ID
2. when: socket labs returns non empty and not last page of history
3. then: multiple requests are sent to socketlabs to cover full history

#### socket labs doesn't have our email (yet)
1. given: valid `EmailVerification` ID
2. when: socket labs returns history, and does not include target email
3. then: raise retry exception

#### Happy path (socketlabs has our email)
1. given: valid `EmailVerification` ID
2. when: socket labs returns history, including target email
3. then: sets email status to verification (sent|failed)

[Jira issue](https://mozilla-hub.atlassian.net/browse/ADDSRV-603)

**Comment by ioanarusiczki** [comment]
@KevinMind I see https://github.com/mozilla/addons-server/issues/21687 is blocked.

I'll need more information about how to test this using the endpoint, what should I be sending in the JSON more exactly. 

We can discuss details on slack. Feel free to contact me. Thanks!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-603
