### ISSUE TITLE
Did not receive in Cinder reply reports on stage

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21541]
I sent several reports for: 
https://addons.allizom.org/en-US/firefox/feedback/review/726336/
or
https://addons.allizom.org/en-US/firefox/feedback/review/726196/

Expected result:
Should be in Amo stage content infringement 

Actual result:
None of the reports are in Cinder

Notes:
Could not reproduce this with other replies/ratings

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-605)

**Comment by diox** [comment]
https://mozilla.sentry.io/issues/4697209170/?project=6237717 and https://mozilla.sentry.io/issues/4677489238/?project=6237717 might be related but stage is way behind at the moment anyway.

**Comment by diox** [comment]
Stage should work now.

**Comment by ioanarusiczki** [comment]
@diox

This is no longer reproducible. 
I've tested  for all stage queues, extensions, themes, collections, ratings/replies, users
 https://testrail.stage.mozaws.net/index.php?/suites/view/49792

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-605
