### ISSUE TITLE
Don't copy file to backup storage if backup storage is not enabled

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21546]
Follow-up from https://github.com/mozilla/addons-server/issues/21506

https://mozilla.sentry.io/issues/4697455318/?project=6224627

Looks like at banning time, we don't check whether backup storage is enabled or not, resulting in this error in `delete_all_addon_media_with_backup` task. The ban would still go through, but we should fix this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-607)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-607
