### ISSUE TITLE
Update user abuse emails triggered by a cinder BAN_USER action to include text about where the decision originated

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21551]
follow on from https://github.com/mozilla/addons-server/issues/21534
include disclaimer about the source of the takedown request for BAN_USER action too

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-608)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I checked all reports and they mention the third party in the first phrase.

Example for the users:
![third party user cinder](https://github.com/mozilla/addons-server/assets/33448286/fa7853ae-18b1-4859-8fcf-83161024d9a7)

I've also noticed a phrase that seems to appear in the e-mails and may not be correct, perhaps "regarding" is not supposed to be there. 

![wrongphrase](https://github.com/mozilla/addons-server/assets/33448286/54a0b5e1-6de2-4021-823a-9e14c517fecf)

**Comment by eviljeff** [comment]
> I've also noticed a phrase that seems to appear in the e-mails and may not be correct, perhaps "regarding" is not supposed to be there.
> 
> ![wrongphrase](https://private-user-images.githubusercontent.com/33448286/297711080-54a0b5e1-6de2-4021-823a-9e14c517fecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODM3MDQsIm5iZiI6MTcwNTU4MzQwNCwicGF0aCI6Ii8zMzQ0ODI4Ni8yOTc3MTEwODAtNTRhMGI1ZTEtNmRlMi00MDIxLTgyM2EtOWUxNGM1MTdmZWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzMTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZGZiOGEwMmQyOTVmZDM2YTI4ZDI5ZWM0NzdmOWVmNGE4ZDJiYjY3NzdiNzYwNDFhMDI2ZDc4NTBlZWY0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0-08fd2QggoLjgveuzEv6XBnjLavbgpoLWp8lSapbes)

The policy name is supposed to be after "regarding" but the policies haven't been fully defined on AMO yet

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-608
