### ISSUE TITLE
Fix add to collection link

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2155]
It's missing some clearing:

![dark_fox____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/14215160/280e03f8-f839-11e5-8e3f-9cdcaaae519d.png)

See https://addons-dev.allizom.org/en-US/firefox/addon/dark-fox-18066/

**Comment by madalincm** [comment]
Verified as fixed in FF45(Win7) in addons-dev.allizom.org
Postfix screenshot:
![addtocollection](https://cloud.githubusercontent.com/assets/15685441/14242047/c515c04e-fa57-11e5-8503-745deb134013.png)
