### ISSUE TITLE
E-mails are not received or content restored after an appeal 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21558]
diox asked me to give exact str 

1. Extension https://addons-dev.allizom.org/en-US/firefox/addon/fourthtest/ , guid {fd722f2d-2d1a-46af-accc-d75a72cd1e3f}, was reported with "Something else" from AMO by irusiczki@mozilla.com
1. Moderated in Cinder for "Terrorism &violent extremism". Add-on is force-disabled 
1. Developer receives the e-mail , makes an appeal https://addons-dev.allizom.org/en-US/abuse/appeal/28001/e0022dd1-c2a1-40f8-99db-3915b0c13db8/, sent the appeal, user is rusiczki.ioana@gmail.com
1. Cinder receives the appeal in Content infringement queue
1. Appeal has: Confirm decision , Revert decision and Change policy . Moderator chooses Revert decision 

Expected result:
The add-on is force-enabled on AMO and an e-mail is sent to the developer

Actual result:
Add-on is not enabled, there's no e-mail in fakemail

Notes:
Also reproducible with user profiles.

User profile appeal reverted 

1. A report received in Cinder for id 10641572
1. User is banned because of Violent Content policy
1. User files https://addons-dev.allizom.org/en-US/abuse/appeal/28062/112c58cb-a2cb-4990-89e7-21d8a5ae221c/
1. The appeal is displayed in Cinder https://stage.cinder.nonprod.webservices.mozgcp.net/job/12a2f01c-9182-43fe-b9ad-1385192c919b
1. Moderator reverts decision , job is processed

appeal's url results in a 404 https://addons-dev.allizom.org/en-US/abuse/appeal/28062/112c58cb-a2cb-4990-89e7-21d8a5ae221c/ (expected after it was processed)
User profile remains banned 

1. Collection https://addons-dev.allizom.org/en-US/firefox/feedback/collection/10641574/Collectiontwo2/ is reported
1. The report is processed in Cinder with "Hate speech" policy
1. Collection is deleted on AMO
1. User sends the appeal https://addons-dev.allizom.org/en-US/abuse/appeal/28064/3f6a1355-ffd8-47a2-8c2c-4740058a8301/
1. Decision is reverted https://stage.cinder.nonprod.webservices.mozgcp.net/job/57f5d418-464b-403a-94bc-e7fd5dde6121

The collection is still deleted on AMO https://addons-dev.allizom.org/en-US/firefox/feedback/collection/10641574/Collectiontwo2/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-609)

**Comment by diox** [comment]
> Appeal has: Confirm decision , Revert decision and Change policy . Moderator chooses Revert decision

"Revert decision" is misleading and shouldn't be used. Changing policy to approve should be the way to go instead.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-609
