### ISSUE TITLE
Return search results in admin when search is done with rating ids

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21568]
1. Go to a user with many ratings such as[ this one](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641572/change/?_changelist_filters=q%3Drusiczki.ioana%2540gmail.com)

2. Click on ratings and make a search using a valid id or multiple ids 

Expected:
Results are displayed 

Actual result:
no results

Notes:
For add-ons it's working when making the search with 2+ ids

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-612)

**Comment by ioanarusiczki** [comment]
I don't seem to get results from the [rating module](https://addons-internal.stage.mozaws.net/en-US/admin/models/ratings/rating/?) either

 I'm going to update the name of the issue.

**Comment by eviljeff** [comment]
I see the following note when I try to search in the ratings module:
>  By default, search will be performed against body.
>
>    If the query contains only numeric terms, and there are 2 or more terms, search will be performed against addon instead.
>   If the query contains only IP addresses or networks, separated by commas, search will be performed against IP addresses recorded for ADD_RATING, EDIT_RATING.

So it's deliberate.  I didn't work on the feature but I'd assume it's entirely deliberate as rating ids aren't really exposed/used, compared to add-on ids.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-612
