### ISSUE TITLE
Expose outstanding abuse reports in reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21576]
part of https://mozilla-hub.atlassian.net/browse/AMO-114

We need to show the unresolved abuse reports for the add-on in it's review page, and allow a review to resolve those abuse reports.  The reviewer will have to select a Policy to resolve the reports under, so the reasoning can be fed back in a consistent way to the add-on developers.  (Expectation is to re-use the rejection reasons)  

Possibly in a follow-up issue: Emails should be similar to the cinder triggered emails, and include notifications to the reporter(s) too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-618)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tested with the "AMO Add-on Escalation" action from Cinder 

For extensions the version reported lands in Manual Review Queue. 
For themes it goes into Updates. 

They're flagged for human review with "Escalated for an abuse report, via cinder" reason. 

A reviewer can take actions such as reject, delay reject, confirm approval, clear needs human review, block or force-disable. 

There is a text below the "Comments box Outstanding DSA related reports to resolve:". I've never seen content after ":" so I am not sure what should be displayed here.

![outstanding dsa related reports](https://github.com/mozilla/addons-server/assets/33448286/e7832bec-a5e1-4ae3-b3b9-32b6b09f5527)


User, collection or rating reports also have action nr7 AMO Add-on Escalation but I'm not sure where these should go on AMO

**Comment by eviljeff** [comment]
> There is a text below the "Comments box Outstanding DSA related reports to resolve:". I've never seen content after ":" so I am not sure what should be displayed here.

mmm, *that's* a problem - there should be a list of checkboxes for all the outstanding `CinderJob`s for this add-on, i.e. at least including the escalation.

**Comment by eviljeff** [comment]
@ioanarusiczki can you link to the add-on review page so I can investigate why the jobs aren't showing up?

**Comment by ioanarusiczki** [comment]
@eviljeff 

At a quick search I found these 2

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620562 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629003

**Comment by eviljeff** [comment]
> @eviljeff
> 
> At a quick search I found these 2
> 
> https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620562 https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629003

fixed in https://github.com/mozilla/addons-server/issues/21766

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-618
