### ISSUE TITLE
Incorrect ID validation of WebExtension manifest causes signature errors

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2158]
STR:

1) Set extensions.logging.enabled to true in about:config
2) Try to install the latest version of this add-on: https://addons.mozilla.org/addon/contasturbo/

Result:
The add-on file is considered to be corrupt, and this error appears: 

> 
1459548173257	addons.xpi	WARN	Invalid XPI: Error: Illegal add-on ID Contas Turbo (resource://gre/modules/addons/XPIProvider.jsm:901:11) JS Stack trace: loadManifestFromWebManifest<@XPIProvider.jsm:901:11 < TaskImpl_run@Task.jsm:315:40

Another interesting detail: if you try to install version 1.3.1-signed, the error is different. In this case it just says the add-on isn't signed.

The add-on ID is `Contas Turbo`. We should verify if this is a legal ID for Firefox (ping @mossop) and if this is supported in Trunion (ping @andymckay). If either answer is "no", I suppose we should add a check to the validator.

**Comment by Mossop** [comment]
This is the regex we've used in Firefox for validating IDs and it hasn't
been changed since around Firefox 2.0:

http://mxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#270

It doesn't allow spaces.

**Comment by jvillalobos** [comment]
After looking further into this issue, and another add-on of the same developer that is also broken, here's the real problem. Due to confusion as to how WebExtension manifests work, the developer has uploaded versions with all sorts of conflicting data.

The initial versions of the add-on had `"id": "faleconosco@contasturbo.com",`

But the latest one has: `"id": "Contas Turbo",` both inside the `applications` section and in the root of the manifest. This apparently changed the ID of the add-on listing, instead of causing a validation errors due to the different ID than the one on the listing, and the invalid ID as well.

Looking at [another add-on of his](https://addons.mozilla.org/addon/conexaomega/), he submitted new versions with this in the manifest:
```
 		"id": "{c6f23b28-e9b8-4859-bc5a-859f45810760}",
		"applications": {
			"gecko": {
				"id": "faleconosco@conexaomega.com",
				"strict_min_version": "42.0.0",
				"strict_max_version": "50.*"
			}
		},
```
The ID in the root of the manifest is the right ID of the add-on, and the validator allowed it, even though the ID that counts (inside the `gecko` section) is incorrect.

**Comment by andymckay** [comment]
When we check out the changes to the applications key to make it optional, can we double check that the test in linter are appropriate for this.

**Comment by andymckay** [comment]
The error here is in old validator, when the addons-linter goes out, this can be closed.

**Comment by tofumatt** [comment]
The new linter is deployed, is this still happening?

**Comment by tofumatt** [comment]
The new linter is deployed and validating IDs correctly I think, so closing this.

Please reopen if I'm wrong.
