### ISSUE TITLE
Error when sorting queue by mad score

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21601]
### Describe the problem and steps to reproduce it:
Open https://reviewers.addons.mozilla.org/en-US/reviewers/queue/extension?sort=score

### What happened?
Oops! We had an error.

### What did you expect to happen?
No error.

### Anything else we should know?
https://mozilla.sentry.io/issues/4716464695/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-624)

**Comment by wagnerand** [comment]
Duplicate of #20866.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-624
