### ISSUE TITLE
Font on carousel without background should be bigger and white

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2160]
it currently looks like:
![screen shot 2016-04-03 at 14 08 26](https://cloud.githubusercontent.com/assets/8145891/14234029/63c58682-f9a6-11e5-99ff-090eda99a712.png)
but should be more like:
![screen shot 2016-04-03 at 14 08 30](https://cloud.githubusercontent.com/assets/8145891/14234033/85f401d4-f9a6-11e5-9f5a-ff4f6b9a1ecb.png)

**all font**
line-height: 1.3em;
color: #fff;

**header**
font-size: 36px;

**sub**
font-size: 14px;

**add-on name**
font-size: 18px;

**description**
font-size: 14px;

Seen on https://addons-dev.allizom.org/en-US/firefox/
Windows 10 Firefox Nighly

**Comment by muffinresearch** [comment]
Looks to be fixed albeit these have a background. 

<img width="502" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14558824/8d1451b2-02fc-11e6-9008-d5a9b55b254b.png">

**Comment by designakt** [comment]
Those texts are too small.
Add-on name should be 1.4rem (or about 18px)
Add-on description should be 1.1rem (or about 14px)

**Comment by muffinresearch** [comment]
Ah ok - yes I jumped the gun on that one. Thanks @designakt

**Comment by andymckay-limited-access** [comment]
Changing those font sizes break the carousels again and caused developers to weep.
