### ISSUE TITLE
Change sort=random seed every hour instead of every day

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#21604]
On the AMO homepage and other places we routinely point users to the full list of desktop Recommended extensions via this link:

https://addons.mozilla.org/firefox/search/?promoted=recommended&sort=random&type=extension

Note the "sort=random" element of the string. This is intended so that users won't see the same static list of Recommended extensions each time they hit the link; we want to give more equitable surfacing to all Recommended extensions. 

However it seems to not be working as intended. I'm consistently seeing our single most popular Recommended extension — uBlock Origin — appear on either the last or second to last page each time. 

How often is the "random" supposed to work? With each refresh of the page? Every hour? 24 hours? But more curiously, is there any reason I'm seeing uBO consistently bumped down the list?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-626)

**Comment by alexandruschek** [comment]
Hello,

I tested this and everything is ok.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-626
