### ISSUE TITLE
Homepage field may not be blank error

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21607]
### Describe the problem and steps to reproduce it:
Homepage field may not be blank error

### What happened?
1.  Login with a developer account
2. Go to Edit my profile
3. Uncheck few notifications boxes and click on update my profile
4. Observe that the updates are not made and an error for the homepage field appears with: This field may not be blank

### What did you expect to happen?
To be able to update my profile without having to add a homepage url
Account used: aschek+qa-developer@mozilla.com
I was able to reproduce this error with a new account as well

<img width="1728" alt="image" src="https://github.com/mozilla/addons-frontend/assets/139126091/1b9b05a5-f81e-4ba1-a50e-c4f9db736d79">
![image](https://github.com/mozilla/addons-frontend/assets/139126091/fcb03231-a47c-4ab8-9810-c9e29ef52c00)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-627)

**Comment by alexandruschek** [comment]
Hello,

I tested this on -dev and it looks ok.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-627
