### ISSUE TITLE
"Approval notes changed" log entry doesn't reflect the actual action that took place: Notes for reviewers changed

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#21609]
### Describe the problem and steps to reproduce it:
When "Notes for reviewers" section changes, the version history logs it as "Approval notes changed" in reviewer tools. That doesn't match the reality and may create confusion for reviewers who might think the approval status of the add-on changed (approved -> rejected etc)

### What did you expect to happen?
When "Notes for reviewers" section updates, a corresponding "Notes for reviewers changed" entry is logged for the version in reviewer tools.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-628)

**Comment by alexandruschek** [comment]
Hello,

I tested this on -dev and it looks ok.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-628
