### ISSUE TITLE
replace carousel background images with images designed for the style refresh

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2161]
currently I see 2 images in use. 
One for monthly pick, and one for shopping. Let us replace those with the following images.
![monthly-bg-re](https://cloud.githubusercontent.com/assets/8145891/14235533/39460db8-f9cf-11e5-8b85-f412747ee70a.png)
![bokeh-purple-bg-re](https://cloud.githubusercontent.com/assets/8145891/14235532/3945fd6e-f9cf-11e5-97e6-4e28bf780a9b.png)
Those should result in in the same kind of look the css filters currently create out of the original image.
And for the shopping image it should result in not have a visible rectangle, and thus better match the style.

If there are other image in use, we should modify those too.

**Comment by vcarciu** [comment]
I think that we should have a background image for this one too : 
![background](https://cloud.githubusercontent.com/assets/1583842/14281586/c62da7bc-fb42-11e5-9a35-5aa36e66e81a.png)

**Comment by designakt** [comment]
@tofumatt The pick of the month still uses the old bg with css filters in addition to the new png.
see css #featured-addon::before, #monthly::before for the old background.
![amo-bg-png-double](https://cloud.githubusercontent.com/assets/8145891/14285089/79f6ded8-fb4a-11e5-8f23-a3fc0ff9978f.gif)

**Comment by tofumatt** [comment]
@designakt Good catch, thanks! I'll remove those :smile:

**Comment by tofumatt** [comment]
Forgot I need to add an image for the promo @vcarciu mentioned.

**Comment by designakt** [comment]
I just saw another background on AMO. Might need to modify the image for that as well if it stays features when we go live with the style refresh.
![carousel-feature-images](https://cloud.githubusercontent.com/assets/8145891/14292173/321a6a04-fb67-11e5-903f-e60c5a82e5b2.png)

@atsay Can you tell me which other featured categories exist and will be used? And if the travel will stay featured

**Comment by tofumatt** [comment]
As a precaution I used the generic bubble background for the travel promo for now. https://github.com/mozilla/addons-server/blob/master/static/css/restyle/restyle.less#L533

**Comment by tofumatt** [comment]
In the future we should probably branch issues specific to each promo off of this one; shifting the assignee and the focus of the issue around makes it hard to track (plus we developers are usually measured by how many assigned issues we close, so eventually I'll want to steal this back :wink:).

**Comment by andymckay-limited-access** [comment]
These carousels all have images, this is done.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshots: 
![1](https://cloud.githubusercontent.com/assets/15685960/15176147/53391f88-1772-11e6-96ca-0beab83dc7a3.png)
![2](https://cloud.githubusercontent.com/assets/15685960/15176152/57f870c8-1772-11e6-80e2-8e60be3d0594.png)
![3](https://cloud.githubusercontent.com/assets/15685960/15176157/5baeea80-1772-11e6-820d-90c612858bca.png)
