### ISSUE TITLE
Drop `AbuseReport.state`

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21610]
`AbuseReport.state` is used to store the resolution state of an abuse report - if it has been reviewed by Mozilla and determined to be a valid report, (or suspicious) or deleted because it's invalid.  Now abuse reports will be resolved either in Cinder or in the reviewer tools directly, and the decision record in a `CinderJob` instance, so the field is obsolete.  From https://sql.telemetry.mozilla.org/queries/96519/source it doesn't seem to have been used anyway.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-629)

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if I should check anything here.

**Comment by eviljeff** [comment]
> @eviljeff Let me know if I should check anything here.

nothing specific, just that abuse reports can be created as normal

**Comment by vcarciu** [comment]
Various types of abuse reports were created in -dev and everything worked as expected. Marking issue as verified.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-629
