### ISSUE TITLE
Cannot reset password.

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2162]
1.Open firefox add-ons page: https://addons.mozilla.org/en-US/firefox/
2.Click on “Log in” link, introduce your email address and press “Continue”.
3.In login page press “Forgot password” link.
4.Enter the email and press “Reset password” button.

Expected results:
An email is sent to the corresponding email address.

Actual results:
“Unexpected error” message is displayed .

Note/Issues:
This issue is reproducing in mp-stage and production.
Video to this issue:http://screencast.com/t/poSoL0PjY3

**Comment by cosminbadescuSV** [comment]
If the user select “Remember password? Sign in” link and try to login with the current password will receive the same message error. http://screencast.com/t/VMDKdGPVrWn

**Comment by andymckay** [comment]
This was on Firefox Accounts, not AMO and that was caused by an outage with Firefox Accounts. This is now resolved.

**Comment by cosminbadescuSV** [comment]
This issue is not reproducing anymore, here is a video: http://screencast.com/t/JpMkoihVei  and a screenshot : http://screencast.com/t/060fkLg53
