### ISSUE TITLE
Statsd timings for class-based-views are broken

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21620]
For class-based-views that are _not_ DRF viewsets, we are recording an incorrect view name. Not sure yet when this started, but this is visible now in https://earthangel-b40313e5.influxcloud.net/d/kiTC7XDZz/amo-prod-frontend-apis-usage-performance?orgId=1 : all non-viewsets timings are missing.

Logic in django-statsd middleware is pretty basic: https://github.com/django-statsd/django-statsd/blob/a781b213296663fc8ca34e370c160b04ca95c91a/django_statsd/middleware.py#L43-L51

This returns `view` for the affected views instead of their class name... This used to work, but broke during Django 4.2 deployment earlier this year.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-632)

**Comment by diox** [comment]
Replacing the middleware `process_view` by the following code fixes it (inspired by Django's `ResolverMatch` logic):
```python
def process_view(self, request, view_func, view_args, view_kwargs):
    view = view_func
    if hasattr(view, 'view_class'):
        view = view.view_class
    if not hasattr(view, '__name__'):
        # A class-based view
        view = view.__class__
    request._view_module = view.__module__
    request._view_name = view.__name__
    request._start_time = time.time()
```

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-632
