### ISSUE TITLE
Add biography to user reports in Cinder 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21639]
Followup for https://github.com/mozilla/addons-server/issues/21234#issuecomment-1845546170

Biography field should be present in Cinder reports according to[ docs](https://docs.google.com/document/d/1k1iyC1TMdyaTsOGlJLJpDyXr4l03O9bGemOSHrbKbnE/edit)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-638)

**Comment by diox** [comment]
This was caused by the attribute being missing from the schema in Cinder (we are already sending the data), I just fixed it.

**Comment by ioanarusiczki** [comment]
@diox 

This is verified on dev


![biography](https://github.com/mozilla/addons-server/assets/33448286/eab182d4-a6c0-4703-b4f1-592197a99d57)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-638
