### ISSUE TITLE
AMO report is not displayed the second time in Relationships -  AMO Report

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21633]
Followup for https://github.com/mozilla/addons-server/issues/21571

1, From Cinder , Content Infringement queue go to an addon report which has been reported multiple times

1. Click on More details
1. Click Relationships
1. Click on each report in the list - at first clicks the reports are display 
1. Click again one of the reports

Expected result: 
the content of the AMO report is displayed

Actual result:
https://stage.cinder.nonprod.webservices.mozgcp.net/investigate/amo_report/28113 url displays the addon instead of the report's content 

![content not displayed correctly ](https://github.com/mozilla/addons-server/assets/33448286/90152a8b-b7c2-431e-8135-6d7851fa4223)

Notes:
a similar behavior is reproducible with developer reply relationships https://github.com/mozilla/addons-server/issues/21530#issuecomment-1860312335

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-636)

**Comment by eviljeff** [comment]
I've not been able to reproduce this but I'm perhaps missing something in the steps and video (cinder isn't the most straightforward UI to navigate, with a lot of clicking around to get lost in).  

Also, is this reproducible with new reports? We only recently changed to have a separate "AMO Report" entity, to store/expose all the required metadata - older reports were just the Addon/User/etc.

**Comment by eviljeff** [comment]
If this is still reproducible I'll report it to the cinder developers

**Comment by eviljeff** [comment]
closing this issue to tidy up.  Please re-open if it's still a problem

**Comment by ioanarusiczki** [comment]
@eviljeff This in particular I could no longer reproduce, yet I saw another ux problem so I filed it in their bug tracker.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-636
