### ISSUE TITLE
"Changes Saved" green message from Edit Listing page is not style-refreshed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2164]
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US
2. Go to "Manage My Submissions" page https://addons-dev.allizom.org/en-US/developers/addons
3. Load Edit Listing page for any add-on 
4. Edit a section and save

Expected results:
The "Changes Saved" message is style-refreshed.

Actual results:
The "Changes Saved" message is not style-refreshed.

Notes/Issues:
Verified on AMO0dev FF45(Win 7)
Screenshot for this issue: 
![2016-04-04_1130](https://cloud.githubusercontent.com/assets/15685960/14242662/e662e950-fa59-11e5-8738-4daf073fcb71.png)

**Comment by muffinresearch** [comment]
@pwalm @designakt what should this look like?

**Comment by designakt** [comment]
Closing this as it looks good as it is.
