### ISSUE TITLE
Inconsistent color for "Delete Theme" button

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2165]
Steps to reproduce:
1. Sign in to AMO-dev page https://addons-dev.allizom.org/
2. Go to edit listing page of any theme (i.e. https://addons-dev.allizom.org/en-US/developers/theme/hnjhdfjnf/edit)
3. Observe the "Delete Theme" button

Expected results:
The button color is red.

Actual results:
The button color is blue.

Notes/Issues:
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue: 
![2016-04-04_1159](https://cloud.githubusercontent.com/assets/15685960/14243413/1e4a6844-fa5e-11e5-859c-b39e140eff0f.png)

**Comment by muffinresearch** [comment]
I think this is OK since (if I'm understanding correctly) the first button triggers the modal and the second button in the modal actually does a deletion, so it seems to me the red colour difference is justified.
