### ISSUE TITLE
Notify reporters when their abuse report has been resolved via reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21669]
Follow-up for https://github.com/mozilla/addons-server/issues/21576

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-643)

**Comment by ioanarusiczki** [comment]
@eviljeff 

For  "Escalated for an abuse report, via cinder" and then a reviewer action is taken I should wait https://github.com/mozilla/addons-server/issues/21576#issuecomment-1905798641 to be fixed

I also tried with add-ons reported in the addon infringement queue,  here I must repeat some tests and then write results.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Reporter's e-mails are sent when an extension or theme is escalated to AMO and a decision is taken in rev tools

For listed versions:
at reject 
delay reject , email is sent but this is known and has been filed  https://github.com/mozilla/addons-server/issues/21811
force disable
clear needs human review 

Unlisted:
reject, delay reject, force disable, notify that the reported content has been removed
confirm approval and clears needs human review notify that content won't be removed

For themes when reviewer:
clears needs human review
reject or force disable

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-643
