### ISSUE TITLE
Complete Themes titles are cut off

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2166]
**Steps to reproduce:**
1. Open https://addons-dev.allizom.org/en-US/firefox/complete-themes/?sort=users
2. Observe the themes titles.

**Expected results:**
There are no layout or display issues.

**Actual results:**
The letters "p", "g" and "y" appear cut off.

**Notes/Issues:**
Verified in FF45(Win7) in addons-dev.allizom.org
Screenshot for this issues:
![completethemestopratedpage](https://cloud.githubusercontent.com/assets/15685441/14243116/604a1570-fa5c-11e5-9287-37ca335423e4.png)

**Comment by ValentinaPC** [comment]
This is reproducing for the summary row that is above the install button of an add-on.
Please see the screenshot: 
![cut](https://cloud.githubusercontent.com/assets/15685960/14318730/f4dd95e8-fc16-11e5-863e-05ab10d4cb3a.png)
![2016-04-06_1634](https://cloud.githubusercontent.com/assets/15685960/14318738/006c2e2e-fc17-11e5-899b-90f4ae216a04.png)

**Comment by madalincm** [comment]
Also reproducing in the editor tools moderated reviews queue: 
![editortoolsletterissue](https://cloud.githubusercontent.com/assets/15685441/14319771/2aa7e44a-fc1b-11e5-8fa2-4cd082a08394.png)

**Comment by eviljeff** [comment]
mentor @muffinresearch 
Can you add steps to get started?

**Comment by wagnerand** [comment]
The line-height needs to be updated.
