### ISSUE TITLE
Use separate "Other" category ID for new (DSA) abuse report flow

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21662]
Between the old and the new abuse report categories, we are only reusing "Other" internally. We should make that a new category ID as well to have a clean cut between pre-DSA and post-DSA.

This issue complements https://github.com/mozilla/addons-frontend/issues/12752.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-642)

**Comment by diox** [comment]
`other` reason should still be available for backwards-compatibility when submitting reports through the API, but we'll add a new `something_else` one that the feedback form will use (https://github.com/mozilla/addons-frontend/pull/12754).

**Comment by vcarciu** [comment]
Verified as fixed . The API now supports both  "other" and "something_else" as a valid reason. They are shown as different values when reports sent previously are viewed in the admin.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-642
