### ISSUE TITLE
Implement cinder decision resolution from AMO

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21660]
prerequisite of #21576 (that I thought initially would be trivial enough not to need to land separately).  We need the ability to create a decision on abuse reports that have been processed via amo reviewer tools, and notify cinder of that decision.

It turns out the at a decision on an entity does not automatically resolve a job - and a job can't be specified in the decision - so the job will be closed manually also.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-641)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I've tested with reports that go into [AMO dev addon infringement](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjI1/details)

Versions are flagged for review with "Reported for abuse within the add-on" reason 
For Needs human review cleared, Reject version, Delay reject , Force disable cancel de job in cinder when Outstanding DSA related reports to resolve - report is clicked

![related reports](https://github.com/mozilla/addons-server/assets/33448286/b3463d0d-18f4-4abf-a364-cd6d01d42e04)

Blocking the add-on is the only action that won't have any effect in CInder (this new section is not displayed in this case).  -> this could be a problem 

I tested this with listed versions and unlisted versions installed and reported from addon manager for "It Violates Add-on Policies" 

I also noticed a new action in Cinder in the Content Infringement queue, it's  "AMO Add-on Escalation" -> started testing scenarios.

**Comment by eviljeff** [comment]
> Blocking the add-on is the only action that won't have any effect in CInder (this new section is not displayed in this case). -> this could be a problem

Blocking isn't a reviewer tool action - it's a redirect to the admin tools. Eventually there may be an integration with abuse reports and cinder actions for blocklisting but it requires https://mozilla-hub.atlassian.net/browse/AOP-93 and the all the connected work to be completed first.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-641
