### ISSUE TITLE
The section where the "Save Changes" and "Cancel" buttons are displayed is not style refreshed

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2167]
**Steps to reproduce:**
1. Open  edit listing for any add-on i.e: https://addons-dev.allizom.org/en-US/developers/addon/flash-video-downloader/edit
2. Click on the edit button for any section in there.

**Expected results:**
Everything displayed is style refreshed.

**Actual results:**
There is a gradient in there and the section where the "Save Changes" and "Cancel" are displayed is not style refreshed. 

**Notes/Issues:**
Verified in FF45(Win7) issue can be reproduced in addons-dev.allizom.org
Screenshot for this issue: 
![editlistingpage](https://cloud.githubusercontent.com/assets/15685441/14243666/8ef9f19e-fa5f-11e5-8e57-41a6b75df28b.png)

**Comment by eviljeff** [comment]
can someone detail what the post-style-refresh section is supposed to look like?

**Comment by tofumatt** [comment]
I think removing the gradient will (mostly) do the trick; they were phased out in the refresh.

**Comment by eviljeff** [comment]
mentor @tofumatt 
Please see [our contribution docs](https://github.com/mozilla/addons-server/blob/master/CONTRIBUTING.rst)

**Comment by PhillypHenning** [comment]
Hey, I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by eviljeff** [comment]
sure, go ahead @PhillypHenning

**Comment by PhillypHenning** [comment]
This may be a silly question but, I don't have an addon submitted and can't edit other peoples. Should I make a dummy addon or is there a way to create a fake addon for dev use?

**Comment by diox** [comment]
@PhillypHenning you can use https://staticfil.es/webext-generator/ to generate and download a dummy add-on. Don't upload that to our production servers though!

**Comment by PhillypHenning** [comment]
Thanks @diox I followed your advice and can now replicate the bug. I've been poking around with the developer tools, but I'm still kinda unsure where to begin, I noticed the style refresh tag on the project does that relate to where I should be looking?

**Comment by tofumatt** [comment]
I'm not sure I'm the best person to mentor this issue anymore as I've been away from this refresh for over a year now and am pretty busy with the frontend.

You can see which classes are being applied to that element and grep for them in your project, which should help you find the element that needs tweaking. Sorry I can't be of more help but I have no off-hand knowledge of this anymore so I'd be digging around the project to get anymore info. 😄

**Comment by PhillypHenning** [comment]
So I've looked at the gradient and I'm unsure if that is the underlying issue..
Testing space - https://addons-dev.allizom.org  

No changes
![image](https://user-images.githubusercontent.com/16713447/31310533-c02edc4c-ab67-11e7-9b07-d27de646199e.png)

Applied gradient off
![image](https://user-images.githubusercontent.com/16713447/31310539-dbc8cdc8-ab67-11e7-8a1d-99b7ce88d071.png)

I noticed that the cancel text color was different than the surrounding similar text color. 

Could I get advise on what should be done going forward?

**Comment by eviljeff** [comment]
Both have a gradient - we want just a flat colour like we have in the sidebar ('Edit Information', etc)

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in addons-dev,allizom.org
Postfix screencast:
![2167](https://user-images.githubusercontent.com/15685441/33119477-d12d6386-cf77-11e7-87e8-6d5ac4c72a7d.png)
