### ISSUE TITLE
Add additional decision actions for reviewer tools specific actions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21671]
We currently just have Disable Add-on as an action that can resolve cinder reports, but in the reviewer tools there are other actions that could/should be taken on the back of a report, such as rejecting specific version(s).  We need to add support for recording those in `CinderJob.decision` so they can be shown as resolving abuse reports too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-645)

**Comment by eviljeff** [comment]
@wagnerand the only additional action that the reviewer tools will omit will be for rejecting particular versions? Is there any other reviewer tools action that would be trackable and appealable by the developer? 

Notes:
- I don't think we need to differentiate a delayed rejection and an immediate rejection, but that may change when I start the implementation
- Blocking versions isn't a reviewer tools action (until #20498)

**Comment by eviljeff** [comment]
now #21576 has been completed, abuse reports can be resolved as AMO_APPROVE with the following actions:
- 'public'
- 'confirm_auto_approved'
- 'clear_needs_human_review_multiple_versions'
- 'approve_multiple_versions'
- 'confirm_multiple_versions'

and AMO_DISABLE_ADDON with
- 'disable_addon'

**Comment by wagnerand** [comment]
> @wagnerand the only additional action that the reviewer tools will omit will be for rejecting particular versions? Is there any other reviewer tools action that would be trackable and appealable by the developer?

I believe reject is the only one. No others come to mind right now.

> now https://github.com/mozilla/addons-server/issues/21576 has been completed, abuse reports can be resolved as AMO_APPROVE with the following actions:

I am not sure 'clear_needs_human_review_multiple_versions' should considered an APPROVE.

**Comment by eviljeff** [comment]
> I am not sure 'clear_needs_human_review_multiple_versions' should considered an APPROVE.

I figured there would need to be an action for when the versions have already been approved or confirmed but an abuse report come in which flagged it for human review.

**Comment by wagnerand** [comment]
> I figured there would need to be an action for when the versions have already been approved or confirmed but an abuse report come in which flagged it for human review.

Hm, good point. I wonder if "confirm approval" should be used for that.
We could keep it for the time being and see how it works out, but clearing needs human review just means that. It does not necessarily mean that it has already been reviewed (and is ok). There are cases where add-ons are added to the queue erroneously (long story), or where we might deem a review not to be a priority.

**Comment by eviljeff** [comment]
> > I figured there would need to be an action for when the versions have already been approved or confirmed but an abuse report come in which flagged it for human review.
> 
> Hm, good point. I wonder if "confirm approval" should be used for that. We could keep it for the time being and see how it works out, but clearing needs human review just means that. It does not necessarily mean that it has already been reviewed (and is ok). There are cases where add-ons are added to the queue erroneously (long story), or where we might deem a review not to be a priority.

Resolving abuse reports is optional (checkbox right now)

**Comment by wagnerand** [comment]
> Resolving abuse reports is optional (checkbox right now)

Ok that works, thank you.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I think I've tested this for https://github.com/mozilla/addons-server/issues/21660#issuecomment-1900644758 

 Cancel de job in cinder when the related DSA report is checked: 

Needs human review cleared, 
Reject version,
Delay reject , 
Force disable

I tried now for an unlisted version with Confirm approval, and I see that the Cinder report was cleared.  

I think it's the expected at this moment., if it's not let me know.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-645
