### ISSUE TITLE
Allow reviewers to seperately resolve abuse reports per category (job)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21670]
Reviewers should be able to resolve certain categories of abuse report without resolving them all.  Note the ability to differentiate per category is limited by how they are combined into a jobs in cinder, so effectively this will be "policy violations that are reviewer handled" & "everything else that was escalated to AMO reviewers"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-644)

**Comment by ioanarusiczki** [comment]
@eviljeff 

 I reported the same extension multiple times for violating add-on policies. 2 reports went to dev addon infringement queue and one went to content infringement. Then I escalated the third report to AMO. If I go to the add-on's review page I only see the DSA from the first queue, I should see one more report but that's a known issue https://github.com/mozilla/addons-server/issues/21576#issuecomment-1904096639 I'll re-check when that is fixed.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I could resolve separate reports for[ a version ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629555) flagged with "Escalated for an abuse report", via cinder and "Reported for abuse within the add-on" 
If they're resolved , the section for Outstanding DSA related reports to resolve: does not display them. That's expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-644
