### ISSUE TITLE
The "Release My Themes Locks" button does not work in stage and appears cut when clicked

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2168]
Steps to reproduce:
1. Sign in to AMO-dev with an admin account https://addons-dev.allizom.org/en-US
2. Go to Editor Tools page https://addons-dev.allizom.org/en-US/editors/
3. Select Themes and any queue
4. Click on "Release My Themes Locks" button

Expected results:
There are not display or layout issues.

Actual results:
The button appears cut when clicked.

Notes/Issues:
Maybe is a regression from #2132 .
The "Release My Themes Locks" button is not working after first attempt.
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue: 
![2016-04-04_1220](https://cloud.githubusercontent.com/assets/15685960/14243783/2110c288-fa60-11e5-9d42-ddf248bb65f3.png)

**Comment by ValentinaPC** [comment]
This is now in AMO-stage and the button is not working at all.
Please see the screencast: http://screencast.com/t/i6jdMcre

**Comment by muffinresearch** [comment]
This is added to the cherry-picks list.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-14_1647](https://cloud.githubusercontent.com/assets/15685960/14530228/b96596a0-0260-11e6-9942-1cbcf6488991.png)
