### ISSUE TITLE
Update emails sent out for Cinder decisions on abuse reports

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21683]
For https://mozilla-hub.atlassian.net/browse/AMO-143

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-647)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I've looked over [the commit](https://github.com/mozilla/addons-server/pull/21695/commits/984499c50e83baa5a20764b6dfac04d803b10d04) and then checked fakemails. Email content has been updated.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-647
