### ISSUE TITLE
Blocklist-filing for a large number of versions of an add-on causes a 400 Bad Request error

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-server#21689]
### What happened?
- When creating a `blocklistsubmission` for a lot of versions (3000+) of an add-on, the `blocklistsubmission` creation fails and a 400 Bad Request is returned

### What did you expect to happen?
- Block-filing should go through for add-ons with as many versions as we allow an add-on on AMO to have

### Additional details
From the error trace (Sentry#4843529265), it looks like we're triggering a `TooManyFieldsSent` exception.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-650)

**Comment by abhn** [comment]
Closing as merged with #21157

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-650
