### ISSUE TITLE
Spelling error: it's vs its

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#21688]
### Describe the problem and steps to reproduce it:
An l10n community volunteer reported the spelling error in this string: [Warning: the following manifest properties that your most recent version upload used in it's manifest are unsupported in this wizard and will be ignored:](https://pontoon.mozilla.org/he/amo/LC_MESSAGES/django.po/?string=191633)]

### What happened?
`... it's...` should be `its` in this context

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-649)

**Comment by ioanarusiczki** [comment]
@diox 

Verified on AMO dev

![themewizardwarning](https://github.com/mozilla/addons-server/assets/33448286/3bb23e6a-8863-4d1e-902d-708f1a713fbf)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-649
