### ISSUE TITLE
Allow admins to mass-clear the needs human review flag

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21690]
Some edge cases can cause a lot of add-ons to be added to the review queue undesirably. In order not to involve SRE or having through click through a lot of reviews manually, it would be helpful for admins to have a way to clear the _Needs Human Review_ for multiple add-ons at once.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-651)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-651
