### ISSUE TITLE
The announcement from editor tools is not changed instantly

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2169]
Steps to reproduce:

1.Open firefox add-ons page: https://addons-dev.allizom.org/en-US/editors/
2.Click on “Announcement” from “Add-ons”.
3.Type something or edit then press “Save” button .

Expected results:
The announcement from editor tools is edited.

Actual results:
The announcement from editor tools is not changed instantly.

Note/Issues:
This issue is reproducing in AMO-dev.
Video to this issue:http://screencast.com/t/8eHcR2zQ

**Comment by andymckay-limited-access** [comment]
Does it change eventually? Instantly is not a requirement.

**Comment by cosminbadescuSV** [comment]
This issue is not reproducing anymore.
