### ISSUE TITLE
Add-on with `gecko_android: {}` in manifest is not marked as Android-compatible by AMO

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#21708]
I have an add-on on AMO, marked with `browser_specific_settings.gecko_android: {}`, uploaded to AMO on July 2nd, 2023 and approved quickly (https://github.com/Rob--W/dont-track-me-google/commit/db36130a78946b1ca852299df340be8055b2b629)

The add-on is however not marked as compatible with Firefox for Android: https://addons.mozilla.org/en-US/android/addon/dont-track-me-google1

As the developer, I can edit the version and manually add compatibility, but before touching anything at all, I wonder whether there is a bug on AMO that we need to fix.

Potentially relevant information: I unchecked the "Compatible with Android" option in march 2021 because the add-on suddenly started to appear in the search results without users being able to install it (https://github.com/mozilla/addons-frontend/issues/10270#issuecomment-807601985). It seems that every version uploaded since (version 4.24) does not have the compatibility set. This despite (latest) version 4.26 containing `gecko_android` in its manifest.json file.

I would expect any add-on with `gecko_android: {}` set to be Android-compatible, unless compatibility is explicitly disabled for that specific version.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-653)

**Comment by diox** [comment]
This is weird. 

Setting `gecko_android: {}` should indeed opt you in Android compatibility, and in fact should be impossible to remove. That was added in AMO before submission of the latest version, so it should have worked.

Do you remember how that version was submitted ? (Devhub, old submission API, new submission API)

**Comment by Rob--W** [comment]
I submitted through the devhub.

**Comment by Rob--W** [comment]
Is there anything to investigate, or should I just fix the metadata manually (as a developer) and close this issue?

**Comment by diox** [comment]
Sorry for the delay, I think this it caused by a weird combination of being recommended for Firefox but not Android and using that property that has since been fixed. Please fix manually and re-open if you don't automatically get Android compatibility next time you upload a version, regardless of the method.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-653
