### ISSUE TITLE
Use CinderAction emails to notify developers about reviewer tools originated decisions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21705]
Currently we send out different emails when an add-on is disabled, etc, depending on whether the action was by a cinder moderator via Cinder, or by an AMO reviewer via the reviewer tools.    Duplication leads to inconsistency - even if we update the reviewer tools emails to be compliant and include the appeal link, etc. - so it would be the best case to send the same emails in both scenarios.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-652)

**Comment by ioanarusiczki** [comment]
@eviljeff 


When extensions/themes are disabled from rev tools with Reject there is a default text which is going into the email (can be manually removed by a reviewer)

![default text](https://github.com/mozilla/addons-server/assets/33448286/f8d71778-31e4-47ae-a27b-d700c293397e)

This is present in the email and has some layout issues too. 

![revtoolsdisabling](https://github.com/mozilla/addons-server/assets/33448286/7ce4a3f7-f97c-4127-bc3e-c7e314020e98)

Themes when disabled from rev tools , email has "affected versions". That line is not present when theme is disabled from Cinder. 

![rejectedtheme](https://github.com/mozilla/addons-server/assets/33448286/889130f4-2981-409e-909a-b6297c7c223c)

Disabled with Cinder policies email sent to developer 

![themedisabledcinder](https://github.com/mozilla/addons-server/assets/33448286/fcb7691f-948f-4d72-b876-045d632449ce)

**Comment by ioanarusiczki** [comment]
@eviljeff Themes disabled from rev tools also have 
"You may upload a new version which addresses the policy violation(s)." which is not present in Cinder e-mails sent to developers.

**Comment by eviljeff** [comment]
@ioanarusiczki the default review-text and mismatched copy for reviewer tools canned responses is being fixed in https://github.com/mozilla/addons-server/issues/21816

I think you may be comparing an add-on disable (the only open from Cinder) with a version rejection from the reviewer tools - a Force disable action should have the same copy (apart from the policy/review-text section)

**Comment by ioanarusiczki** [comment]
@eviljeff Oh I see, I checked with force-disable for themes and they are identical indeed (leaving policies aside).

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-652
