### ISSUE TITLE
Notify only the right reporters when resolving abuse report appeals

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21719]
When resolving abuse report appeals, we currently notify all original reporters that are attached to the original job. That's wrong: we should only notify those who appealed.

STR:
- Report a content (leave your email address or be logged in)
- Report that same content with a different user/email
- Resolve the job in Cinder (should be a single job for that content)
- Appeal from reporter $1 using the email you received
- Resolve the appeal job in Cinder

Expected results:
- Reporter $1 should be notified, reporter $2 should not.

Actual results:
- Both reporters are notified

Note: at the moment, once an appeal decision has been made, further appeals from others reporters are not possible. This will change soon, and that will add another layer of complexity to this issue: if the initial appeal is resolved and there is another one from reporter $2, then resolving that one should not notify the other reporter.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-659)

**Comment by diox** [comment]
> Note: at the moment, once an appeal decision has been made, further appeals from others reporters are not possible. This will change soon, and that will add another layer of complexity to this issue: if the initial appeal is resolved and there is another one from reporter $2, then resolving that one should not notify the other reporter.

We decided _not_ to allow this for the time being: https://github.com/mozilla/addons-server/issues/21739

**Comment by ioanarusiczki** [comment]
@eviljeff 

For jobs that go to dev content infringement I tried the scenario above and after an appeal there's only one email that goes to the reported of the appeal.  Also when it's been processed , the other user cannot send the appeal. 

I noticed that when an appeal is landing into the other queue (for violating add-on policies), after a reviewer action is taken from AMO, such as clear needs human review, there is the possibility to confirm the appeal or revert but changing a policy is not possible. I confirmed the appeal but I didn't see an email sent. That's something I did not cover when I looked over https://github.com/mozilla/addons-server/issues/21575, I think I'll need to check again.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I verified this scenario for extensions that go into addon infringement queue and for escalations to AMO too. 
A second reported receives the messages from https://github.com/mozilla/addons-server/issues/21739 when attempts to appeal.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-659
