### ISSUE TITLE
Delete account mail contains Firefox add-ons team instead of Mozilla add-ons team

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21712]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Delete account mail contains Firefox add-ons team instead of Mozilla add-ons team

### What happened?
1. Create a new account or use an existent one
2. Delete the account
3. Check in fakemail/inbox
4. Observe that the sign off in the email contains: 
The Firefox Add-ons Team

### What did you expect to happen?
It should contains: The Mozilla Add-ons Teams
### Anything else we should know?
Follow-up for issue: https://github.com/mozilla/addons-server/issues/21682
(Please include a link to the page, screenshots and any relevant files.)
![image](https://github.com/mozilla/addons-server/assets/139126091/7e916d7b-ce43-45d2-b985-f0c69de9ab49)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-655)

**Comment by alexandruschek** [comment]
Hello, 

I tested this and the sign off is now changed to Mozilla Add-ons team
<img width="1225" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/894dcdf5-be98-480c-ae45-1e584b6cc193">

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-655
