### ISSUE TITLE
Complete work to make abuse report escalations work with appeals

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21716]
While all the code has been written with escalations (from Cinder to AMO) and appeals in mind we should carry out specific work (adding unit tests at least) which confirm that all scenarios work, including an appeal escalation.  This could happen either because the original job was escalated, and has now been appealed and needs to be looked at by AMO reviewers again (that it was escalated isn't "sticky" - the decision action would be replaced with the eventual decision in the reviewer tools); or because cinder moderators discover something at the appeal stage that requires AMO reviewer investigation.

One thing I noted needs changing already is:
`CinderActionEscalateAddon` uses `abusereport_set` which wouldn't work for appeals.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-656)

**Comment by eviljeff** [comment]
I'm going to close this as its written more like a story ticket than something actionable - and we have a lot of more specific issues logged about appeals already.  Also, the fix for https://github.com/mozilla/addons-server/issues/21927 changed how escalations work, and https://github.com/mozilla/addons-server/issues/21990 et al will change appeals some more.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-656
