### ISSUE TITLE
Different colors for same buttons on Android Add-ons pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2172]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US
2. Load "Other Applications" - " Firefox for Android" option
3. Go to version history page for an add-on compatible with windows and android (i.e https://addons-dev.allizom.org/en-US/android/addon/flash-video-downloader/)  
4. Hover over last 2 versions and observe the "download" buttons (v. 5.5.0 and v 5.4.4.1-signed)

Expected results:
The buttons have the same color.

Actual results:
The buttons have different colors.

Notes/Issues:
Before style refresh the "Download now" buttons _where blue and without "+"_, don't know if you want to keep that.
Also, the last version is not signed. Should all versions be signed, if they are in public pages, or not a must?
Screenshots for this issue:
![2016-04-04_1507](https://cloud.githubusercontent.com/assets/15685960/14247720/d2ef4cdc-fa78-11e5-8f1b-da2c00f8f5d0.png)
![2016-04-04_1508](https://cloud.githubusercontent.com/assets/15685960/14247728/d7630236-fa78-11e5-976b-702c9f7d859a.png)
Other example from add-ons details page:
![2016-04-04_1526](https://cloud.githubusercontent.com/assets/15685960/14247849/b54d234c-fa79-11e5-9574-43d0f3521bbb.png)
![2016-04-04_1527](https://cloud.githubusercontent.com/assets/15685960/14247852/b95fa784-fa79-11e5-8867-0bb035889b97.png)

**Comment by muffinresearch** [comment]
@ValentinaPC Is this still the case? Can you re-verify please?

**Comment by ValentinaPC** [comment]
The "blue" color is gone. :)
Now, we have yellow and green.
But.... we have "Download for Windows" yellow button for preliminary reviewed add-ons (I think this is ok) and "**+** Download for Windows" for awaiting versions....should unapproved versions be available in public pages?
Please see the screenshots: 
![not_signed_version](https://cloud.githubusercontent.com/assets/15685960/14560580/677ce0c8-0319-11e6-8e36-4978b3de3365.png)
![signed_version](https://cloud.githubusercontent.com/assets/15685960/14560586/6cb44d92-0319-11e6-8140-36920339d0fd.png)
![2016-04-15_1449](https://cloud.githubusercontent.com/assets/15685960/14560594/729c8c38-0319-11e6-88ef-82eb66241ca2.png)
