### ISSUE TITLE
Local env: warning about unsupported engine

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21723]
On local environments, during updating the instance, I see the following warning:

```
npm install --prefix /deps/
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'addons-server@0.0.17',
npm WARN EBADENGINE   required: { node: '>= 18.18' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '9.6.7' }
npm WARN EBADENGINE }
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-661)

**Comment by KevinMind** [comment]
Linked: https://github.com/nodesource/distributions/issues/1706

**Comment by diox** [comment]
This is not just about local dev: all our addons-server envs are stuck on 18.17 but they shouldn't.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-661
