### ISSUE TITLE
AMO is preventing me from updating my dictionary

### ISSUE THREAD

**Issue by hultmann** [mozilla/addons-server#21733]
### Describe the problem and steps to reproduce it:
* Download the current version XPI from https://addons.mozilla.org/pt-BR/firefox/addon/ortografia-br/
* Attempt to submit it as new version 

### What happened?
* Validations fails with the error:
Your add-on failed validation with 1 error.
The locale of an existing dictionary/language pack cannot be changed

### What did you expect to happen?
No validation errors.

### Anything else we should know?
I suspect the problem is AMO might be interpreting "pt-BR-antigo" as a conflict with "pt-BR" even though Firefox can function with both locales simultaneously.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-664)

**Comment by willdurand** [comment]
From a quick look, that seems more like a server thing.

I suppose the issue is that this is a dictionary for `pt-BR` and you'd like to submit a new version that targets `pt-BR-antigo`, which is probably not supported.  Maybe you need to make a _new_ dictionary for `pt-BR-antigo`?

**Comment by hultmann** [comment]
Both the current and new versions use the same locale (`pt-BR-antigo`). In their manifest.json files, you'll find:

```
  "dictionaries": {
    "pt-BR-antigo": "dictionaries/pt-BR.dic"
  },
```

**Comment by eviljeff** [comment]
the target locale is set as just `pt-BR` for the existing add-on (api [response](https://addons.mozilla.org/api/v5/addons/language-tools/))  but I see it's not been updated since 2018 so it's possible that was the "correct" value back then.  

@wagnerand to see if the value should be corrected (in django admin)

**Comment by wagnerand** [comment]
I am not sure we want to change the target locale on AMO. Can you change the locale inside the add-on? /cc @flodolo as he might have more insights

**Comment by eviljeff** [comment]
> I am not sure we want to change the target locale on AMO. Can you change the locale inside the add-on? /cc @flodolo as he might have more insights

if it's different to the target locale in the manifest at the moment, for the latest version, my guess is it was manually tinkered with at some point.

**Comment by flodolo** [comment]
`pt-BR-antigo` is trying to work around a [limitation in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1478915). I've tested it locally, and it works, so I think it would be fine to update the locale code in Django admin.

<img width="471" alt="Screenshot 2024-01-24 alle 12 21 20" src="https://github.com/mozilla/addons-server/assets/3644868/c4d6608c-6118-448d-ab92-225544ecc661">

**Comment by wagnerand** [comment]
Thanks @flodolo! Ok, I changed the target locale of `pt-BR-1971@dictionaries.addons.mozilla.org` from `pt-BR` to `pt-BR-antigo`, @hultmann.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-664
