### ISSUE TITLE
After IP was cleared and after three appeals for a rating, my ip got throttled -DEV

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21738]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
After IP was cleared and after three appeals for a rating, my ip got throttled

### What happened?
Step 1: I submitted 6 appeals for this addon: https://addons-dev.allizom.org/en-US/firefox/addon/consent-o-matics_1/
Step 2: My ip got throttled
Step 3: My ip was cleared
Step 4: Started submitting three rating appeals and my ip got throttled again
<img width="1118" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/30c1b2d5-8b83-4f20-9098-02c456d75513">

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Decision: 9cede051-3dbb-424c-b480-85f229d4674f
Review id: 567927
Related to this issue: https://github.com/mozilla/addons-server/issues/21302
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-665)

**Comment by diox** [comment]
This happens because non-authenticated reporter appeals go through the throttles twice for each appeal: once for the email form, once for the appeal itself.

We should give both separate throttles to avoid that.

**Comment by alexandruschek** [comment]
Hello @diox ,

I've tested this and it looks ok:
- the 6/hour limit was removed
- the 20/day limit is in place and works as expected
- i've gotten to test the abuse appeal form for both unauthenticated and authenticated sides and it works as expected
- appealing for ratings/addons/users authenticated/unauthenticated in order to check that the count is done well and it looks ok.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-665
