### ISSUE TITLE
Cinder should display the correct version number for an installed add-on

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21759]
I installed[ an older version of an add-on ](https://addons-dev.allizom.org/en-US/firefox/addon/cocerid56cheertapybaray/versions/) 

and sent a report to AMO 

Report abuse model in admin - the correct version number (4.0.5.2 in this case) is displayed  but in Cinder - the last version of the add-on is displayed `version 4.1.5.4`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-676)

**Comment by diox** [comment]
Yeah, for reports to Cinder moderators we predominantly care about what's on the listing page.

**Comment by eviljeff** [comment]
okay, closing as wontfix then

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-676
