### ISSUE TITLE
L10n: need context for placeholder "type"

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#21758]
### Describe the problem and steps to reproduce it:
[Thank you for your report about the following %(type)s on Mozilla Add-ons: %(name)s.](https://pontoon.mozilla.org/he/amo/LC_MESSAGES/django.po/?string=300086)

### What happened?
This string lacks context for localization purpose.

### What did you expect to happen?
Add comment to the string for more accurate localization

### Anything else we should know?
Through Slack conversation: `"type" here is a type of content, translated separately (Theme, Extension, Rating, Collection etc)`. Let's add it to the string in the next code update.

@diox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-675)

**Comment by willdurand** [comment]
This isn't how placeholders should work in localized content. Here, there should be a localized string per type:

> Thank you for your report about the following Extension on Mozilla Add-ons: %(name)s.
> Thank you for your report about the following Theme on Mozilla Add-ons: %(name)s.
> Thank you for your report about the following Rating on Mozilla Add-ons: %(name)s.
> Thank you for your report about the following Collection on Mozilla Add-ons: %(name)s.

That's because this only reads well in English but French localization won't work well:

> Merci d'avoir signalé le Rating suivant sur Mozilla Add-ons : <add-on name>
> Merci d'avoir signalé le Collection suivant sur Mozilla Add-ons: <add-on name>

That makes no sense. In fact, localizers are already trying to work around this issue (see matrix / l10n-community)

**Comment by eviljeff** [comment]
this will be fixed by https://github.com/mozilla/addons-server/issues/21742 - by dropping `{{ type }}`/`%(type)s` from the localized emails.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-675
