### ISSUE TITLE
N dash vs. double N dashes for hyphenated word

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#21757]
[Time--based theme changer. Make Firefox change colors as the time of day changes.](https://pontoon.mozilla.org/he/amo/LC_MESSAGES/django.po/?string=246183)

### What happened?
Notice that `Time--based...` contains double "N" dashes, where it should a single N dash? 

### What did you expect to happen?
Change to `Time-based`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-674)

**Comment by peiying2** [comment]
@diox

**Comment by diox** [comment]
@devaneymoz That's for you to fix since this is a string you control through the discovery admin I believe.

**Comment by devaneymoz** [comment]
Fixed in admin. Thanks for the catch!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-674
