### ISSUE TITLE
send new-style (DSA) emails for reviewer tools actions on add-ons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21754]
i.e. We need to call `CinderActionDisableAddon.notify_owners(...)` rather than the existing templates.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-672)

**Comment by eviljeff** [comment]
duped myself - dupe of #21705

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-672
