### ISSUE TITLE
Sections from left side of edit listing looks squished

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2175]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to edit listing page for any of your addons (https://addons-dev.allizom.org/en-US/developers/addon/4april/edit)
2.Observe the left side sections

Expected results:
The sections looks ok , without UI issues 

Actual results:
No padding on left side and also the sections should be wider

Please see screencast for this bug : http://screencast.com/t/FeVtwzS7E0

NOTES : Also , we have UI issues when there are numbers at compatibility reports : http://screencast.com/t/P7ZZbsBX

**Comment by muffinresearch** [comment]
This is fixed:

<img width="227" alt="edit_listing____4april____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14558244/317d4ff0-02f9-11e6-8e1c-ebe323ea8db0.png">

**Comment by vcarciu** [comment]
Please fix the compatibility reports issue too : 
![compatrep](https://cloud.githubusercontent.com/assets/1583842/14564487/675e2dc0-032f-11e6-9ab1-c51947722677.png)

**Comment by muffinresearch** [comment]
@vcarciu got a link to that example? Clearly I was looking at one that didn't have that issue.

**Comment by vcarciu** [comment]
@muffinresearch : https://addons-dev.allizom.org/en-US/developers/addon/adblock-plus/edit

**Comment by vcarciu** [comment]
Verified as fixed  : 
![padd](https://cloud.githubusercontent.com/assets/1583842/15182066/45e14bd2-1793-11e6-9a87-6321245872fd.png)
