### ISSUE TITLE
Correctly expose abuse report escalations in reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21766]
follow on from #21576 - it was supposed to expose escalations too but this didn't work (it regressed in a refactoring during development)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-678)

**Comment by ioanarusiczki** [comment]
@eviljeff I'm having some problems  finding how to do this because new queues landed, too many actions. I tried to move the add-on in Escalation queue but I could not send to AMO a report yet.

**Comment by eviljeff** [comment]
> @eviljeff I'm having some problems finding how to do this because new queues landed, too many actions. I tried to move the add-on in Escalation queue but I could not send to AMO a report yet.

The policies and actions are incorrect at the moment in cinder, so I'll get back to this issue when it can be tested with STR

**Comment by ioanarusiczki** [comment]
@eviljeff 

I sent the listings or themes to Deprecated AMO Dev Content Infringement where "AMO Add-on Escalation" is right now. 

I think this is working as expected on rev tools side. I tested with extensions and themes. 

![Escalations](https://github.com/mozilla/addons-server/assets/33448286/5d71c0dd-3029-4bdf-b1ae-23358fe632bb)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-678
