### ISSUE TITLE
Monitor cookie size delivered to each client

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#2177]
As part of https://github.com/mozilla/addons-server/issues/1859 we will begin storing JSON Web Tokens in the session and the session is currently implemented with signed cookies. This new data will increase the cookie size which is dangerous because once the cookie gets too big, users will not be able to stay logged into the site. 

Let's monitor the cookie size in one or more ways:

* Log an error that will show up in Sentry if the cookie gets too big
* Track the cookie size in statsd so we can see how many clients get impacted
* Add general logging for debugging

A safe estimate of cookie size (as supported by browsers) is [4096 bytes](http://browsercookielimits.squawky.net/).

If we hit the limit, we could start by compressing the cookie, like [encrypted cookies](https://github.com/brightinteractive/django-encrypted-cookie-session/#cookie-size).

**Comment by diox** [comment]
Nitpick: the plan for #1859 is to use a different cookie, *not* store JSON Web Tokens in the session. The end result - an increase in total cookie size - is the same, though.

**Comment by kumar303** [comment]
ah, yes, if we do that then this issue can probably be closed.

**Comment by andymckay-limited-access** [comment]
Based on #1859 and @kumar303 last comment, I think this can be closed.
