### ISSUE TITLE
This is a test task

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons-server#21782]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-681)

**Comment by KevinMind** [comment]
Test comment from github.

**Comment by KevinMind** [comment]
Another comment.

**Comment by KevinMind** [comment]
Test comment works.

**Comment by data-sync-user** [comment]
Testing

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-681

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-681
