### ISSUE TITLE
Dangling tabs in My submissions page

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2179]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addons
2. Notice the tabs for "My Add-ons" and "My themes"
## observed behavior:

 Dangling tabs in dev hub (look particularly not-great when there are no themes)

@pwalm notes:
    Ghost tabs! A quick solution would be that only the selected tab has a tab. the others are just word links https://images.duckduckgo.com/iu/?u=http%3A%2F%2F4.bp.blogspot.com%2F-UQZC6q3pNKo%2FUiZ7ZyFVWTI%2FAAAAAAAAFLY%2FP34Yjwyv2aA%2Fs1600%2Fajaxcssstyletabcontainer.gif&f=1

**Comment by muffinresearch** [comment]
@pwalm so something like this?

<img width="573" alt="manage_my_submissions____developer_hub____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14559312/ad0f28e0-02ff-11e6-823b-41f84813756a.png">

**Comment by pwalm** [comment]
Yep!

**Comment by andymckay-limited-access** [comment]
Why are these tabs? Can we just make them links.

**Comment by pwalm** [comment]
Agreed, never thought of that.

**Comment by muffinresearch** [comment]
@andymckay They already are links. Are you suggesting that all the tab styling should be removed like this?

![no-tabs](https://cloud.githubusercontent.com/assets/1514/15284333/8efbf688-1b48-11e6-8a23-d26c097ee9b1.png)

Personally I think that will make the UI more confusing. 

Typically a tab is related the content it includes. Unfortunately that's not the case with the markup here but hey, we don't live in a perfect world.

**Comment by andymckay** [comment]
Something like that although i'm sure @pwalm could make it better, in this example I just expanded the already existing sort by:

![screenshot 2016-05-16 08 12 59](https://cloud.githubusercontent.com/assets/74699/15293691/0e0dffb2-1b3e-11e6-84da-5e392597edbe.png)

Probably simple changes, not sure if this is harder than fixing the tabs. It is wierd that we have one and only one set of tabs in AMO and they are kinda crappy, removing a bunch of CSS to clean that up might help a little.

**Comment by LordGameleo** [comment]
Is this issue open? I would like to go for it.

**Comment by EnTeQuAk** [comment]
Personally, I like @andymckay's last idea here, using "Filter by" and regular links. I think both, sort-by and filter-by would need to increase in size a bit though to make it more obvious to users.

@pwalm any objections or other simple improvement ideas? If not then I think this may be fine for a contributor to work on.

I wouldn't change the way how these links work at all though.

@LordGameleo please hold off a bit for an approval by our UI team, if we get that then this is fine to work on.

**Comment by pwalm** [comment]
Sounds good to me! Thanks @LordGameleo

**Comment by LordGameleo** [comment]
Can I know what exactly should I do!? Is it to be made as "filter by" or anything else?

**Comment by EnTeQuAk** [comment]
Correct, the result should look similar to the screenshot in https://github.com/mozilla/addons-server/issues/2179#issuecomment-219452056 but maybe make the text a bit bigger so that it is easier to see.

You'll probably have to touch src/olympia/addons/templates/addons/includes/dashboard_tabs.html which is being used by src/olympia/devhub/templates/devhub/addons/dashboard.html

The css could potentially be all over the place :see_no_evil: but I'm happy to look into that in-depth if you want me to.

**Comment by LordGameleo** [comment]
I will go through it once on my own. If I am unable to. I will let you know. Is there any channel where we can have proper communication.

**Comment by EnTeQuAk** [comment]
It's best either to ask here or in IRC: irc.mozilla.org in the #amo channel.

**Comment by LordGameleo** [comment]
There is a problem while I do reset database. Even after typing yes it says reset cancelled. 

![snap_reset_cancelled](https://user-images.githubusercontent.com/40512667/44790685-872f6900-abbd-11e8-8e31-3740eaa133ca.png)

**Comment by pwalm** [comment]
@LordGameleo Can you show us a screenshot with more context?

**Comment by EnTeQuAk** [comment]
Yes, the actual error that you're getting woud help debugging your problem running the project.

**Comment by LordGameleo** [comment]
There are two problems:
i) When I run the server using docker, I get the page like this.
 
![prob_1](https://user-images.githubusercontent.com/40512667/44846634-83a7ea80-ac6e-11e8-97d2-
f2c30eb4aa25.png)

CSS is not loading I guess.

ii) When I go to developers hub in that, I get to see this error.

![prob_2](https://user-images.githubusercontent.com/40512667/44846635-83a7ea80-ac6e-11e8-9707-dede0ab33b88.png)

**Comment by EnTeQuAk** [comment]
> i) When I run the server using docker, I get the page like this.

You should open the page via `http://olympia.test` as written here https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#accessing-the-web-server

**Comment by LordGameleo** [comment]
I was having a doubt while installing through install docs. I have attached a screenshot. I wanted to know how to proxy nginx after changing port from 80 to 8880.

Thank You.

![dobut_nginx_config](https://user-images.githubusercontent.com/40512667/44853498-c1fbd480-ac83-11e8-8df3-4140cd7e3ba7.png)

**Comment by EnTeQuAk** [comment]
Well, in theory you don't have to change anything in that regard, the port change is purely optional. Do you need to change the port to something else?

If you go through the install docs and change the `/etc/hosts` file accordingly you should be able to simply open http://olympia.test on your browser and see the site.

**Comment by LordGameleo** [comment]
I have to change the port as when I don't it shows error while running the server that port 80 is already binded.
![bind_error](https://user-images.githubusercontent.com/40512667/44856726-bb715b00-ac8b-11e8-9554-f75ebfb863fa.png)

**Comment by EnTeQuAk** [comment]
The correct path is `/etc/hosts` 

You can also stop your already running nginx or apache or whatever runs on your port 80 to avoid changing too many things to get addons-server running. That'd be easier I think

**Comment by LordGameleo** [comment]
I have made changes to the dashboard.less file which gets converted to CSS when project is built. I want to know how can I see the updated version of project where changes will be visible.

**Comment by EnTeQuAk** [comment]
If you're running this in your docker environment you can see the changes right away, all `.less` files are compiled during run-time so just (force) reload your browser and you should see the change

**Comment by LordGameleo** [comment]
Is it ok?
![solution_1](https://user-images.githubusercontent.com/40512667/44908222-558edd00-ad38-11e8-8e4f-0ca17493d3ef.png)

**Comment by LordGameleo** [comment]
Or this?
![screenshot from 2018-08-31 16-10-51](https://user-images.githubusercontent.com/40512667/44908273-7ce5aa00-ad38-11e8-9cd4-a760f9315a7e.png)

**Comment by EnTeQuAk** [comment]
I like https://github.com/mozilla/addons-server/issues/2179#issuecomment-417625623

What does @pwalm think?

**Comment by LordGameleo** [comment]
@EnTeQuAk so what is the progress? @pwalm  what did you think about them?

**Comment by pwalm** [comment]
Agreed with @entequak! Thanks @lordgameleo

**Comment by LordGameleo** [comment]
@EnTeQuAk  can you help me out with pull request.

**Comment by eviljeff** [comment]
Tbh, I'm not convinced by the end result in https://github.com/mozilla/addons-server/pull/9367#issuecomment-423890394 - without any other UI structure on the page it just looks like a bunch of words in the middle of a white space.  There's nothing to indicate it's a table header, or what the addons/themes links are.

@LordGameleo thanks for your work on this so far, we'll get it right it the end!

@pwalm can we get some more guidance here?

**Comment by LordGameleo** [comment]
@EnTeQuAk @eviljeff @pwalm I have made changes to the pull request related to this issue. Would you mind reopening it again.

**Comment by caitmuenster** [comment]
Hey @LordGameleo, this isn't a good bug to work on. Want to take a look at bugs labeled `contrib: good first bug` or `contrib: welcome`? Those have been vetted and patches are welcomed.

**Comment by jvillalobos** [comment]
There's been too much back and forth on this issue without a clear visual goal, so let's just close it. We plan to update dev hub next year.
