### ISSUE TITLE
expose reported addon version for abuse reports in reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21797]
If a user has an add-on installed in their Firefox when they report abuse for it we record the version in the abuse report instance.  We expose this information in the full list of abuse reports available in the reviewer tools review page, but don't for the checkboxes that allow jobs to be resolved with the review.  (We do, however, make sure to flag that version specifically for human review).

We should include the reported version in the `<details>` for the abuse reports for each job.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-685)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-685
