### ISSUE TITLE
Ongoing Reports of Daily Statistics showing Zero

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#21798]
IMHO, it would be an idea to keep one topic for this report, instead of opening a new bug each time that happens...

All add-ons show zero daily users on Feb 2, 2024

Previously:
[Ongoing Reports of Daily Statistics showing Zero](https://github.com/mozilla/addons/issues/510)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-686)

**Comment by diox** [comment]
I can't reproduce with the few add-ons I've looked at. Can you share an add-on ID for which this is happening ? Also, is this only affecting daily users, do you see downloads ?

> IMHO, it would be an idea to keep one topic for this report, instead of opening a new bug each time that happens...

This doesn't happen so frequently any more (I think we've seen this once in the past 2 years) to justify keeping an issue opened about it. And I'm not sure in this case it's widespread anyway.

**Comment by willdurand** [comment]
It does look like it is fixed for me too, but I was able to confirm the issue on Sat. 3 when @erosman asked about it on matrix.

**Comment by erosman** [comment]
It is fixed for me too. I was under the impression that some one fixed it.
It lasted about 24 hours and it was for all my addons (not a few).

If it got fixed by itself, then the cause and its fix, are worth looking into.

**Comment by diox** [comment]
It's a task running daily by another team with its own monitoring. I suspect it either took longer and/or was retried.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-686
