### ISSUE TITLE
Add Group for sending mail on dev/stage

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons-server#21790]
## Problem 

Currently on dev/stage by default we do not send real mail but add a FakeMail record and log the mail to the console. We do this to prevent sending mails for real users that have data in dev/stage and to prevent devs and other employees from getting spammed too often.

Sometimes (ex: ticket) we need to actually send mails on non prod environments. Until now we have been using an environment variable EMAIL_QA_ALLOW_LIST that provides a list of emails for which we should bypass the fake mail and send a real mail. You can also specify at runtime that you want a given mail to send an actual mail.

This environment variable is static and requires SRE as well as a deployment to update, but often we want to quickly enable real mail for N users to test something and then disable again.

## Solution

We will use a `Group` to manage users that should have mail sent which can be updated on the fly via the admin or terminal. This gives us a much faster and more convenient way to update this list when we need it and removes the SRE dependency.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-684)

**Comment by ioanarusiczki** [comment]
@KevinMind 

I added emails to [dev](https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/50112/change/) and [stage ](https://addons-internal.stage.mozaws.net/en-US/admin/models/access/group/50112/change/) and I tried a couple of things
- someone is rating an add-on 
- reviewer reply
- add-on submission, add-on approval
- abuse report decisions

For users from ForceSend Mail group, I received the emails in my inboxes and they continue to be present in fakemail too.

**Comment by KevinMind** [comment]
@ioanarusiczki this is expected. ForceSend will have both, fake and real emails.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-684

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-684
