### ISSUE TITLE
Change reviewer tools canned response formatting

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#21816]
### Describe the problem and steps to reproduce it:
We need to change the way we add canned responses into the reviewer notes text box to fit into the DSA template email.

## Prefill when rejecting
When rejecting (`reject` and `reject_multiple versions`)

### What happened?

... we prefill the box with

```
This add-on didn't pass review because of the following problems:

1) 
```

### What did you expect to happen?

... we no longer prefill the text box.

## Fill when selecting a review reason
When selecting a review reason

### What happened?

... we fill (amend) the notes in the text box with the canned response for that reason.

### What did you expect to happen?

we fill (amend) the notes in the text box with the following:
```
* {{ Cinder parent-policy name }}, specifically {{ Cinder sub-policy name }}: {{ Canned response of the review reason attached to the Cinder-sub policy }}
<newline>
```

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-693)

**Comment by ioanarusiczki** [comment]
@diox 

Right now there is no prefilled text in the Comment field and once an extension or theme is rejected there's only the reason chosen by the reviewer in rev tools, or a custom reason. There's no Cinder policy.  Not sure what's exactly expected.

![rejected multiple versions](https://github.com/mozilla/addons-server/assets/33448286/17d451b0-bace-49ce-ae63-694c3b69a0c1)

**Comment by diox** [comment]
That's actually a good test since to make sure things still work when there is no linked cinder policy... But to check that particular issue, you'd need to go into the admin, edit the review action reason, and add attach a cinder policy to it (choosing one with or without a parent).

See also https://github.com/mozilla/addons-server/issues/21855 for some recent changes made to that admin

**Comment by ioanarusiczki** [comment]
@diox 

Note: I removed "-" from the text, @eviljeff discovered what was causing https://github.com/mozilla/addons-server/issues/21863

I added 2 new reasons in [reviewactionreason](https://addons-internal.stage.mozaws.net/en-US/admin/models/reviewers/reviewactionreason/15/change/) with Cinder policy.

Rejection of a version -> the text after ":" is from the [canned response field ](https://addons-internal.stage.mozaws.net/en-US/admin/models/reviewers/reviewactionreason/16/change/) In case there's no text there, the name of the policy will be displayed.

![rejectfromrevtools](https://github.com/mozilla/addons-server/assets/33448286/303a24f2-d3fe-4435-a69d-adce01230e5c)

With Force Disable

![forcedisable](https://github.com/mozilla/addons-server/assets/33448286/ba0c80f3-3e34-4fa6-90a3-097efedd72d0)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-693
