### ISSUE TITLE
 Change "legal" link to point to new central policy landing page [server]

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21828]
AMO is going to have a dedicated landing page for all policies relating to AMO/add-ons. This should replace the existing url.

New url is https://www.mozilla.org/about/legal/amo-policies/ (per https://mozilla-hub.atlassian.net/browse/AMO-185)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-698)

**Comment by ioanarusiczki** [comment]
Verified on stage

![legal on server side](https://github.com/mozilla/addons-server/assets/33448286/bd88dcef-ef88-4733-b3ce-cb65957f47a4)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-698
