### ISSUE TITLE
Navigation menu/info board in manage add-ons section of devhub needs to be wider

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2182]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/scriptalertproblem1script/edit
2. Notice the Navigation menu and add-on metadata section.

## observed behavior:
Navigation menu is narrower and all the links wrap awkwardly. See https://www.dropbox.com/s/dyq32wrusnazd57/Screenshot%202016-03-28%2016.50.47.png?dl=0

@pwalm notes:
Weird, we shouldn't have lost that padding. Bring it back!

**Comment by muffinresearch** [comment]
Looks to be fixed already.

![edit_listing____test-example-2____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/14469565/2c9f25e4-00dd-11e6-9390-7eeaf28e0854.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![wider](https://cloud.githubusercontent.com/assets/1583842/14487151/a6d0b2d8-0169-11e6-9096-56c7588f6417.png)
