### ISSUE TITLE
can`t upload new version of addons

### ISSUE THREAD

**Issue by vksaver-team** [mozilla/addons-server#21825]
### Describe the problem and steps to reproduce it:

Can`t upload new version of firefox addon. 

### What happened?

server return 403 response.

### What did you expect to happen?

upload without 403 error.

### Anything else we should know?

About 1 month all was ok.
![Снимок экрана от 2024-02-07 17-07-12](https://github.com/mozilla/addons-linter/assets/159254938/3dd18ec4-f0ec-47d3-b209-02b6a91fd960)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-695)

**Comment by diox** [comment]
Could you give more information, what's the ID of the add-on you were trying to upload ?

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-695
