### ISSUE TITLE
Expose in Cinder Report Entity whether a reporter claims reporter content is illegal or not

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21823]
As part of DSA, we are going to need to expose whether or not the reporter claimed the content they are reporting is illegal or not when we forward data to the [EU transparency database](https://transparency.dsa.ec.europa.eu/page/api-documentation).

We already ask for this at reporting time (we have a dedicated `It violates the law or contains content that violates the law` category + checkbox to confirm), and we already store that and expose it as a `reason` in the Cinder Report Entity, but the way we currently do it was meant for moderators, so we expose the reason string from the django choice (currently `DSA: It violates the law or contains content that violates the law`).

We need something separate that data consumers can use. 2 options:
- Expose an additional `considers_illegal` boolean
- Expose the `reason` as an api value constant (as already documented in our API https://addons-server.readthedocs.io/en/latest/topics/api/abuse.html#abuse-user-reason-parameter)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-694)

**Comment by diox** [comment]
Mozilla Social is going with the `considers_illegal` boolean FWIW.

**Comment by ioanarusiczki** [comment]
@diox 

Considers_illegal field is present for all entity types in Details/Relationships/AMO Reports 

Verified on Cinder stage - dev queues

![considers_illegal](https://github.com/mozilla/addons-server/assets/33448286/4d309895-e327-4ff6-91fe-50b203cdb414)

![illegal2](https://github.com/mozilla/addons-server/assets/33448286/02147818-311f-4c50-b029-a7fb81c8bb87)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-694
