### ISSUE TITLE
Parent policy is shown separately in a different line in the target/author emails. -DEV

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21827]
### Describe the problem and steps to reproduce it:
Parent policy is shown separately in a different line in the target/author emails. -DEV
(Please include as many details as possible.)

### What happened?
![image](https://github.com/mozilla/addons-server/assets/139126091/7d3b47b9-8b76-40e6-8ac0-6965ac545916)
Parent policy is shown in a separate line
### What did you expect to happen?
For the policy section to contain only this:
- Acceptable Use, specifically Acceptable Use: Harassment
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
This is related to issue: https://github.com/mozilla/addons-server/issues/21742

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-697)

**Comment by diox** [comment]
@wagnerand Would it be safe for us to ignore policies with no `enforcement_actions` ?

**Comment by diox** [comment]
Alternative, probably better approach is to ignore parent policies that we already have children of. Going to give that a stab.

**Comment by alexandruschek** [comment]
Hello @diox ,

I tested this, and the line that contained: "- Acceptable Use: Acceptable Use" was removed, only the second line was kept in the e-mail, but it still shows twice and it contains this series of characters: "&gt"
<img width="1423" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/172def90-7e01-4c47-8db0-442df0587f7f">
Also, I saw that there is a noticeable space between "Acceptable use" and the next paragraph. Is this ok?

Thank you!

**Comment by alexandruschek** [comment]
Hello,

I checked again today on -STAGE and it looks good, the only thing I noticed is that the link to acceptable use is shown twice.
<img width="1403" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/63327f69-999f-476a-b4a9-a83b17cf31a9">

Thank you!

**Comment by diox** [comment]
I noticed the link too, this is a problem with how the link was inserted in the text in Cinder, not something in the code. We'll get that sorted out.

**Comment by diox** [comment]
I fixed the policies on Cinder stage instance and re-imported them in AMO dev&stage.

**Comment by alexandruschek** [comment]
I checked again, and the link issue is fixed, it is showing only once.
<img width="1403" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/a90b5a54-a638-431c-8157-d4874df59e57">

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-697
