### ISSUE TITLE
Cinder - job cannot be opened when moving them to another queue and back 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21830]
1. Change queue for a Cinder job to any other queue available
2. Move it back to the queue it was in at 1.

Result: I could not open the jobs to start reviewing. 

I tested it with add-ons and ratings 
![nojobs](https://github.com/mozilla/addons-server/assets/33448286/012e4f8e-c7b3-4edc-b70c-50a3e9ce68cb)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-699)

**Comment by eviljeff** [comment]
reported to the cinder developers

**Comment by ioanarusiczki** [comment]
@diox 

Now I can send reports from -dev or -stage to a general queue "Escalations" .

From Escalations I could move it back with "return job" or "change queue"  to the initial queue and open the report so this has been fixed. 

![change queue](https://github.com/mozilla/addons-server/assets/33448286/40c0e2c2-3384-4b8e-a24b-5ba1b0a17010)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-699
