### ISSUE TITLE
Cinder - Privacy Policies, Image and Other , left for discussion

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21832]
Followup for https://github.com/mozilla/addons-server/issues/21741#issuecomment-1935628882

Privacy Policy, Image and Other - are policies present in Cinder but currently they don't have an effect over AMO content when they're used to process a job. 

They're in discussion -> [document](https://docs.google.com/document/d/1b5YbQSrBq_K38RIslOaNABLaPe0NBHYJccCL7Q9X3Cc/edit)

When it's going to be clear what's their effect over AMO content these should be tested accordingly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-701)

**Comment by diox** [comment]
Should be fixed now. Final doc is https://docs.google.com/spreadsheets/d/14wu7Vip25NS4iVMu3fKLz9SgDHyGEz6-2XcX-6C6vaM/edit

**Comment by alexandruschek** [comment]
Hello, 

I focused on checking the result of the actions for: **Content** and **Privacy Policy**:
I checked against the final version of the doc, and for addons, all is good, escalate to amo, redirects the decision to an AMO Reviewer and it appears in the manual review queue, in case of disable, the addon gets disabled.

For theme, the privacy policy and content option does not appear
<img width="1403" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/04768c1b-20c4-4188-9f9b-f30fc835574d">

For collections, only content appears and it only contains spam(when according to the doc it should contain promotes another site or add-on)
<img width="1403" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/e6cc3ac3-b503-4996-b980-c94c8f5a9b8b">

For ratings, same as collections, only  content is present and only spam is inside it:
<img width="1403" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/2cecae2f-81fd-4687-b6a0-30a7a0758cae">

For users, only content is present, but it does have both options(Spam and promotes another site or add-on:
<img width="1403" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/6272e996-99c9-4bfd-8085-8680ec1ca4d9">

Thank you!

**Comment by diox** [comment]
I fixed the missing ones for collections & themes.

Ratings & users look correct to me according to the spreadsheet.

**Comment by alexandruschek** [comment]
I checked for Collections & Themes, all good now. I noticed that for Collections -> Content -> Promotes sites or add-on, the user reporter/reported does not get an e-mail. I checked both my gmail account and through fake mail in admin and I was not able to get it. For the rest it works as expected

**Comment by alexandruschek** [comment]
I checked for the fix, and now I receive the e-mail and also, the collection is deleted. Thank you for the effort and the great work!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-701
