### ISSUE TITLE
Cinder - layout issues for metadata in the middle section

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21831]
User profiles:

![layout issues Cinder](https://github.com/mozilla/addons-server/assets/33448286/917cc2e1-e2c3-4930-ad71-774d4552aee5)

Themes - I could only reproduce this with one theme so far

![layout issues themes](https://github.com/mozilla/addons-server/assets/33448286/f472aa04-3754-4637-ab57-f571e00696f6)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-700)

**Comment by eviljeff** [comment]
reported to the cinder developers

**Comment by eviljeff** [comment]
fixed according to the cinder developers

(their report https://linear.app/cndr/issue/SR-820/amo-theme-and-user-renderer-bugs - not accessible outside of their org)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Looks good now 

![summary fixed](https://github.com/mozilla/addons-server/assets/33448286/5ce52b35-c93c-4146-985b-82797ea25254)
![theme fixed](https://github.com/mozilla/addons-server/assets/33448286/4efaa328-c307-497c-b1a9-f99df797b02c)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-700
