### ISSUE TITLE
Consider bypassing developer agreement check for langpacks upload

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21841]
https://bugzilla.mozilla.org/show_bug.cgi?id=1879549 happened because the developer agreement date changed on stage. Releng scripts that upload langpacks started to fail because their user had not accepted the agreement yet.

Their user is already part of a group giving them special rights. Should we have a special permission allowing them to bypass the developer agreement check entirely ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-703)

**Comment by diox** [comment]
Related issues discovered on releng side as part of looking into this:
- https://github.com/mozilla-releng/scriptworker-scripts/issues/913
- https://github.com/mozilla-releng/scriptworker-scripts/issues/912

**Comment by wagnerand** [comment]
This sounds reasonable to me.

**Comment by diox** [comment]
I think the simplest solution is to give set `bypass_upload_restrictions=True` on their user(s) on all envs. No additional code changes needed, this was intended to allow bypassing all restrictions, including developer agreement.

**Comment by wagnerand** [comment]
> I think the simplest solution is to give set `bypass_upload_restrictions=True` on their user(s) on all envs. No additional code changes needed, this was intended to allow bypassing all restrictions, including developer agreement.

I've done that now. One user had it already set, the other one didn't. I can't tell which one is the old user and which one is the new. Should we close this issue?

**Comment by diox** [comment]
Did you do it on stage as well ? (I think the user is release+addons@mozilla.com)

**Comment by wagnerand** [comment]
> Did you do it on stage as well ? (I think the user is [release+addons@mozilla.com](mailto:release+addons@mozilla.com))

I have now!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-703
