### ISSUE TITLE
Reattach the -> to the search input field

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2184]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/
2. Notice the search field

Currently the -> is separated from the search input field form. See https://www.dropbox.com/s/ofpuysa50qm2oik/Screenshot%202016-04-04%2011.21.27.png?dl=0

@pwalm notes
I think that was a design choice originally, but it would probably look better if they were attached? Low priority though.

**Comment by muffinresearch** [comment]
This is what we're looking for:

<img width="238" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14559403/514497e2-0300-11e6-902b-85190e5b5f1f.png">

**Comment by eviljeff** [comment]
See [our contributing document](https://github.com/mozilla/addons-server/blob/master/CONTRIBUTING.rst)
mentor @tofumatt

**Comment by andymckay** [comment]
Is this still worth doing?

**Comment by tofumatt** [comment]
It took me five minutes to fix, PR incoming.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF48(Win 7 x64)
Postfix screenshot: 
![2016-08-10_1232](https://cloud.githubusercontent.com/assets/15685960/17549021/2ab35da4-5ef7-11e6-919e-5dfe076395f5.png)

Was not fixed for RTL languages:
![rtl](https://cloud.githubusercontent.com/assets/15685960/17549040/3aa617ec-5ef7-11e6-9c32-7bc4b8089447.png)

@tofumatt : should we fix this here? :smile:

**Comment by tofumatt** [comment]
Yeah, I'll add a fix for RTL as well, shouldn't take long.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Ff48(Win 7 x64)
Posftix screenshot: 
![2016-08-10_1728](https://cloud.githubusercontent.com/assets/15685960/17557561/51d3bcc0-5f20-11e6-9b7e-93aa5bd1f4c2.png)
