### ISSUE TITLE
FxA migrated accounts can still log in with old username/password

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#2185]
STR:

1) Migrate account to fxa
2) Attempt to log in with username and password

Results:
* The user can still log in by firing a POST request to the login service with username/password set.

Expected:
* The user can only log in via FxA

That said, I am relying on this behavior in my tool to review extensions and would have to add code to do an fxa login, therefore I wouldn't mind if you take your time to fix this :) Here is the code I use for logging in: https://github.com/kewisch/pyamo/blob/master/pyamo/session.py#L76

**Comment by andymckay** [comment]
This is planned this quarter when @mstriemer is planning on removing the FxA migration and making FxA the default login. That will remove the password hash and the POST end point.

**Comment by kewisch** [comment]
We can probably duplicate this against #1825
