### ISSUE TITLE
Improve Cinder Policy / Review Action Reason admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21855]
In the admin:

- Expose id, parent and text in Cinder Policy list view 
- Make it easier to find the right policy in review action reason admin

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-706)

**Comment by ioanarusiczki** [comment]
@diox This was verified on -stage with https://github.com/mozilla/addons-server/issues/21816

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-706
