### ISSUE TITLE
Create the activity log entry before calling resolve_abuse_reports

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21865]
The reviewer tools Reject action (i.e. latest version reject) raises a [500](https://mozilla.sentry.io/issues/4977589166/?project=6237717) in the reviewer tools code when resolving abusereports/cinderjobs. From the traceback it looks like we're creating the activity log entry after we fire the task to resolve the cinder job, but we need the activity log instance to exist to send in the task

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-709)

**Comment by eviljeff** [comment]
STR:
- reject the latest version (not the multiple reject action) of the add-on while resolving one or more jobs of abuse reports.
- the abuse reports/jobs should be resolved and email sent - though if it doesn't outright 500 then the bug is fixed.

**Comment by ioanarusiczki** [comment]
@eviljeff Verified on -stage with https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1022942#review-actions

Note: the reports are displayed ,  but the there's no flags on the version's details 

![cherrypick2](https://github.com/mozilla/addons-server/assets/33448286/484a9c31-e851-440c-b5b6-74770d08f005)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-709
