### ISSUE TITLE
Email is not sent after version reject when the DSA related reports are checked 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21863]
I tried to test https://github.com/mozilla/addons-server/issues/21816 with Reject versions

When I select the Outstanding[ DSA related reports to resolve ](https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1008599#review-actions) and reject e-mail is not sent to the author. Also the reports continue to be displayed in the section

examples
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1008599#review-actions
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1022919#review-actions

When the version is rejected without checking the Cinder reports the email is sent to the author. 

I tested this on stage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-708)

**Comment by eviljeff** [comment]
I can reproduce this with Reject Multiple Versions.  We fire a celery task to complete the integration with cinder and send the email, and there is a [500](https://mozilla.sentry.io/issues/4976310839/?project=6237717) from the cinder api (which would prevent the email from going out, because we use the response from cinder in the email).

**Comment by eviljeff** [comment]
The underlying cause of this issue, from trawling raw logs in GCP, is `notes cannot start with =, +, -, or @'`.  Regardless of the reason for the limitation in cinder we needs to workaround it, at least temporarily, to launch.

**Comment by ioanarusiczki** [comment]
@eviljeff I see it fixed on dev.

**Comment by ioanarusiczki** [comment]
@eviljeff verified on stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-708
