### ISSUE TITLE
An e-mail should be sent to the author for to confirm the decision stays disabled 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21870]
Content not taken down, reporter appeals, we change the decision and disable. The content goes down, the author can appeal (the only time an appeal decision can be appealed)

From there, in that second appeal we can change the decision to (Neither the reporter nor the author can appeal that final decision):
Confirm the decision to disable

At the final step from https://testrail.stage.mozaws.net/index.php?/cases/view/2498871 -> An email should be sent after the decision to keep the content disable is made as described at https://github.com/mozilla/addons-server/issues/21575#issuecomment-1905800017

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-710)

**Comment by eviljeff** [comment]
Can you confirm is this applies to appeals processed in cinder, or in the AMO reviewer tools, (or both)?

**Comment by ioanarusiczki** [comment]
@eviljeff 

So for Cinder appeals if I use Adjust Decision and repeat the same action , I won't get a confirmation email that content stays disabled , 2 emails are sent again , one to reporter , one to the author.  As I described at [step 6](https://testrail.stage.mozaws.net/index.php?/cases/view/2498871)

But it did work with "Deny Appeal" (step5)

But I think I found an issue at appeals from rev tools Tried to write it all down https://testrail.stage.mozaws.net/index.php?/cases/view/2498873. At step 5 I should have the appeal in the Outstanding DSA related reports to resolve: section , the flag is present in version's details with "Appeal about a decision on abuse reported within the add-on"

I tried with listed and unlisted 

https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1022943
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1002635#review-actions

I'll file a followup.

**Comment by eviljeff** [comment]
I _think_ I know what's happening to cause this.  When trying to work out what emails we want to send out we compare the initial decision to the new decision.  This works fine until there are 3 decisions - the initial (APPROVE); the reporter appeal (DISABLE_ADDON); the developer appeal (DISABLE_ADDON) - but we're still comparing to the initial decision (so APPROVE compared to DISABLE_ADDON, rather than DISABLE_ADDON to DISABLE_ADDON) so sending out the wrong emails...

**Comment by eviljeff** [comment]
closing in favour of #21948

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-710
