### ISSUE TITLE
Appeal should be attached to un-reject or force enable to reinstate content 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21879]
Add-ons reported for violating add-on policies are flagged for human review in rev tools 

Scenario:
Content taken down, author appeals, we change the decision and bring the content back up 

I tried https://testrail.stage.mozaws.net/index.php?/cases/view/2498881 on stage 

After the author makes the appeal I see it displayed in rev tools , the problem is that I don't have a way to attach it to an action that would reinstate content.

Un-reject would work when a version is rejected https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1023081#review-actions. Currently with clear needs human review the version would stay rejected 

Force enable when disabling the add-on https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1023082#review-actions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-715)

**Comment by ioanarusiczki** [comment]
@eviljeff   I'm thinking to split this into smaller issues as followups if it's TLTR. Let me know.

**Reject - unreject**

- there's an email sent automatically at unreject that a version has been approved while the version is actually awaiting review

Email is:

Hello,

Your Extension has been approved on Mozilla Add-ons and it is now available at [https://addons-dev.allizom.org/addon/unreject-1-listed-version/.](https://addons-dev.allizom.org/addon/unreject-1-listed-version/)

Approved versions: 1.0

Thank you.

More information about Mozilla's add-on policies can be found at [https://extensionworkshop.com/documentation/publish/add-on-policies/.](https://extensionworkshop.com/documentation/publish/add-on-policies/)

[ref:502668ad-f8c4-48cd-ace7-26474d08390e]


Examples:

1 listed version approved https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629851 or https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629243
1 unlisted version approved https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/629870
2 listed approved versions https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629864
2 unlisted approved versions https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/629871
1 approved listed version with scanner rules https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629869
1 approved unlisted version with scanner rules https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/629875


- First version awaiting review: when the report is sent or author appeals they don't get into the Manual review queue, yet on their review pages the  report and appeal are displayed in DSA section

 Another problem I see is what I said at 1. , at unreject an email is sent to the author

first listed version is still awaiting review https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/629895
an unlisted version delayed by scanner rules 9this will be available in manual review queue because with "Hit scanner rule") https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/629877
 

- a first version is approved and the second is rejected then unrejected - 2 emails are sent about the version being approved
One immediately after unreject when[ resolving the appeal ](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/120721/change/) and another one [after the auto approval runs ](https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/120722/change/)

Tested with
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629868
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629896

**Force disable - Force-enable**

1. In all cases after the appeal is sent by the author the addon is not present in the Manual Review queue's list. Appeal sent by the author is available in the reviewer's page. 

2. For a first version awaiting review because it hit scanner rules, or  simply awaiting review because it's the first version , at force enable an email is sent that content has been restored but it's actually flagged for human review.

hit scanner rules https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629878
first version awaiting review  https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629879

3. A listed/unlisted approved version , after appeal is resolved with force-enable and content is reinstated, they show up in the Manual review queue as being flagged.

unlisted https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/629881
listed https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629893

**Comment by eviljeff** [comment]
we're either going to have to subtly change the email wording, or more likely* change the actions to have the file status be APPROVED after the unreject/enable actions.

*(because it will always be confusing to say we've made a decision the content is okay so are reversing a takedown; but we've not approved it because we've not made a decision yet that the content is okay)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I filed some followups but I'll wait for  https://github.com/mozilla/addons-server/issues/21987 and re-check this.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-715
