### ISSUE TITLE
Author's appeal is denied - a phrase has . . at the end 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21873]
Followup for https://testrail.stage.mozaws.net/index.php?/cases/view/2498871

Step 5: ". ." left in email's content

![2dots in the email](https://github.com/mozilla/addons-server/assets/33448286/4ff97205-6add-4f4b-aff2-b404a375dcf0)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-713)

**Comment by diox** [comment]
This is caused by the fact that there was no reasoning passed with the appeal denial. I'll add a workaround for this case.

**Comment by ioanarusiczki** [comment]
@diox 

This is fixed on -dev

![fixed](https://github.com/mozilla/addons-server/assets/33448286/b0c82576-2bcc-4cd6-8a58-7e000aa25509)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-713
