### ISSUE TITLE
Display flagged for human review + reasons for a first listed version in awaiting review

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21871]
Followup for https://github.com/mozilla/addons-server/issues/21865
 
A first listed version in awaiting review was reported with flagged for human review:reported for abuse within the add-on and Escalated for abuse report, via cinder 

Expected:
in version's details these flags should be displayed 

![cherrypick2](https://github.com/mozilla/addons-server/assets/33448286/02c16b4f-9d88-4fda-b77d-0f1013c80f5c)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-711)

**Comment by eviljeff** [comment]
fun fact: we _do_ create an activity log when we flag a version for needs human review.  But we don't show that activity in the reviewer tools history (because the activity class, NEEDS_HUMAN_REVIEW_AUTOMATIC, doesn't have the `review_queue = True` property).  
The quick fix is to change that... but that would mean _all_ automatic needs human review flags would be shown in the reviewer tools, which is kind of an intended change.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tried on dev https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630159 but I still reproduce the issue
Theme escalated -> stage https://reviewers.addons.allizom.org/en-US/reviewers/review/1024861

**Comment by eviljeff** [comment]
@ioanarusiczki can you reiterate STR?  I see an entry for `Flagged for human review` in the review history.

**Comment by ioanarusiczki** [comment]
@eviljeff While a first version is awaiting review , it's reported for add-on policies or escalated to AMO 

Click on clear needs human review or another reviewer action, there's 2 reports in the dsa section for [the extension](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630159) But meanwhile it's been approved, maybe that's why a flag is displayed. 

The theme is not approved yet and this is what I see: 

![theme and flags](https://github.com/mozilla/addons-server/assets/33448286/2c817663-df3c-4991-a519-2c61adb7c976)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-711
