### ISSUE TITLE
Author's appeal is not displayed in Outstanding DSA 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21872]
Followup https://github.com/mozilla/addons-server/issues/21870#issuecomment-1948084900 

Tested with https://testrail.stage.mozaws.net/index.php?/cases/view/2498873 

Expected result:
At step 5 I should have the appeal in the Outstanding DSA related reports to resolve: section

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-712)

**Comment by ioanarusiczki** [comment]
This is no longer reproducible now. I tested today with an extension reporter for add-on policies and a theme escalated to AMO.

![author appeal now](https://github.com/mozilla/addons-server/assets/33448286/8bb8a4e3-a706-4e83-968d-b4cd6db69e41)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-712
