### ISSUE TITLE
The name of the rating is between: &quot; instead of: " -STAGE

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21881]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
The name of the rating is between: &quot ; instead of: "" -STAGE
### What happened?
1. Job is landing in AMO stage Ratings, moderator chooses Ignore/Approve action Submit
2. An email is sent to the reporter who has the right to appeal 
3. Reporter appeals
4. Appeal is sent
5. Appeal is available in AMO stage Users queue
6. Adjust Decision - Ignore/Approve and Submit
7. Observe in the sent email that the name of the rating is between: &quot ; instead of: "

### What did you expect to happen?
The name of the rating should be between: "
Test case used: https://testrail.stage.mozaws.net/index.php?/cases/view/2499416&group_by=cases:section_id&group_id=481321&group_order=asc
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://github.com/mozilla/addons-server/assets/139126091/87249b1d-1147-4e57-84ef-62c505ac9ec8)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-717)

**Comment by alexandruschek** [comment]
Hello, 

Just checked this scenario and now the e-mails looks like this:
<img width="1367" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/413db03c-d7fc-419d-b5e3-29ec1463b1d4">
The rating is displayed, and it seems that if it's longer than a number characters, a shorter version will be displayed.
In case of a short rating, it will be fully displayed:
<img width="1367" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/01f7d2af-0159-43dc-8cdf-dc8f983eed89">
Adding a verified fix label on this one

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-717
