### ISSUE TITLE
Errors listed in the validation summary don't match with the validation details page

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2188]
## test webextension
http://cl.ly/3m3I1N0w3s3G

## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2. Notice the error summary after the submission completion
3. Compare the errors in #2 to validation details page

## expected behavior:
errors listed in the summary match up to those listed in the validation details page

## observed behavior:
Summary lists 28 errors - https://www.dropbox.com/s/ydgplhwj8w7n0h6/Screenshot%202016-04-04%2013.01.14.png?dl=0
Details page doesn't  - it lists only one error - https://addons-dev.allizom.org/en-US/developers/upload/e657f4133c2645f88bf12fd4f9f9a5b3

**Comment by ValentinaPC** [comment]
Verified as fixed on FF46(Win 7).
I've uploaded the attached web-extension.
Postfix screenshots: 
![step2](https://cloud.githubusercontent.com/assets/15685960/15500901/880e28a2-21b3-11e6-8e33-48cf88ac61d0.png)
![report](https://cloud.githubusercontent.com/assets/15685960/15500947/ad9206d4-21b3-11e6-9222-4634743daa38.png)

**Comment by krupa** [comment]
This issue isn't fully fixed.

test webext: http://cl.ly/1h0L1y0i3o1v

The validator reports that there are 55 warnings but the detailed page has no warnings listed - https://addons-dev.allizom.org/en-US/developers/upload/5037d05f2cb54abdb5f484ecc2f4c80a

See the screenshot: https://www.dropbox.com/s/gi6o4i5x3fdzf17/Screenshot%202016-05-24%2015.12.17.png?dl=0

**Comment by EnTeQuAk** [comment]
If you uncheck "Hide messages not required for automated signing" you see the warnings being shown.

See the screenshot from your validation report:

![screenshot from 2016-05-25 09-56-27](https://cloud.githubusercontent.com/assets/139033/15532245/0fc1e472-225f-11e6-82e4-e3cacdfdc01e.png)

And I also tested submitting the add-on as a new one which works fine too:

![screenshot from 2016-05-25 09-53-47](https://cloud.githubusercontent.com/assets/139033/15532262/2de5e43a-225f-11e6-9efc-e89b4cd233c1.png)

**Comment by ValentinaPC** [comment]
I've double checked on AMO-dev FF46(win 7) and everything looks fine. (for me the checkbox is not displayed at all)
Please see the screencast: 
![55warnings](https://cloud.githubusercontent.com/assets/15685960/15532483/bb91ab30-2268-11e6-905a-30ea24d6074f.gif)

**Comment by EnTeQuAk** [comment]
I think the checkbox is only visible if you're adding a new version to an add-on, not when you're submitting a new one.
