### ISSUE TITLE
Improve performance of CinderJob.resolvable_in_reviewer_tools()

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21880]
To differentiate between `CinderJob`s that are handled by T&S moderators and AMO Reviewers, we have introduced a `resolvable_in_reviewer_tools()` method that is used in the AMO review page to find jobs that can be resolved as part of the review of a given add-on.

The query that this method produces contains multiple `JOIN`s on `abuse_reports` and itself (because of appeals - which are a job on top of another job). This is made worse in the review page where we also need to filter by target, with `for_addon()`. The result scales very poorly in production where there are a lot of abuse reports, to the point where we had to [temporarily disable showing the jobs on the review page](https://github.com/mozilla/addons-server/issues/21877).

We should implement that query differently to solve this problem. Couple ideas to look into:
- Decouple from `abuse_reports` by storing the target on the `CinderJob` when it's created (this would later help to implement forwarding decisions to Cinder even if they are made on our own initiative without a report - though fixing all existing code to allow that is out of scope here)
- Decouple from `abuse_reports` by storing a boolean on the `CinderJob` indicating that this is meant for AMO Reviewers when it's created or escalated from Cinder.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-716)

**Comment by diox** [comment]
This would also greatly simplify the queries made in https://github.com/mozilla/addons-server/issues/21769 (which are slightly less problematic in terms of performance, because they are only running once per day, with a filter on creation date and without the additional joins to filter by add-on).

**Comment by diox** [comment]
The original problem was not noticeable in dev/stage but we should ensure resolvable reports (either because of original reason+location caused them to be handled by reviewers, or because they were escalated) are still seen correctly in reviewer tools.

**Comment by alexandruschek** [comment]
Hello,

I tested this and it looks good, I only found this issue, but as discussed, it's not a blocker: https://github.com/mozilla/addons-server/issues/21908 

Marking this as verified fix

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-716
