### ISSUE TITLE
Escalated themes do not get into Reviewer Tools -STAGE

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21894]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Escalated themes do not get into Reviewer Tools -STAGE

### What happened?
1. I created a new theme and approved it
2. Switched to another account and reported the theme
3. Report landed in AMO Stage Themes
4. Escalate it to Reviewer Tools
5. Observe that the theme cannot be found anywhere in reviewer tools

### What did you expect to happen?
Theme to get in the Manual Review Queue from Reviewer Tools(will update if needed, I was not able to find the theme in any queue, even though it was escalated
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Theme used for this: https://addons.allizom.org/en-US/firefox/addon/theme_abuse_report_50/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-721)

**Comment by eviljeff** [comment]
I guess it's because we never implemented `needs human review` handling for themes...

**Comment by eviljeff** [comment]
From looking in [cinder](https://stage.cinder.nonprod.webservices.mozgcp.net/investigate/amo_addon/1023178?tab=decisions&filters=%7B%7D) the job wasn't escalated to AMO Reviewers, only to T&S in cinder.  This seems like an invalid bug.

**Comment by alexandruschek** [comment]
You're right, I did not use an action to escalate to amo, instead I've sent it to Amo Escalations in Cinder. Closing this.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-721
