### ISSUE TITLE
Remove local MySQL repos mirror for our docker builds

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21895]
In #21016 we set up a MySQL repos mirror to build our docker images as the repos was busted at the time, it wasn't providing the necessary Releases file. This should have been fixed so we should go back to using the regular repos.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-722)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-722
