### ISSUE TITLE
Experiment with HTTP compression for Elasticsearch

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21905]
We're not currently using compression (in requests or responses) for Elasticsearch. Let's try it, in theory these days it should just require passing `http_compress=True` when instantiating the `Elasticsearch` object.

Need to try on dev/stage first, updating the [perf graphs]( https://earthangel-b40313e5.influxcloud.net/d/kiTC7XDZz/amo-prod-frontend-apis-usage-performance?orgId=1) to show data from dev/stage, as it might be more detrimental than beneficial to performance.

This should be 100% transparent to users - no visible changes, so if search/homepage works with no noticeable performance difference then it's successful.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-727)

**Comment by alexandruschek** [comment]
Hello,

I tested this on -DEV  and it looks ok, the search works as expected.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-727
