### ISSUE TITLE
Reports with no text do no appear in Reviewer actions -STAGE

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons-server#21908]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Reports with no text do no appear in Reviewer actions -STAGE
### What happened?
1. Submit an abuse report for an addon: violates add-on policies and place of violation: inside the add-on(no additional text added)
2. Go to reviewer tools -> Manual Review Queue
3. Click on the reported add-on
4. Click on Clear Needs Human Review
5. Observe that if the abuse report contained no text, after clicking on Show reports, an empty space will appear

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
2 reports one with no text, and one with text
<img width="1367" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/f8e888fc-2b97-40f5-b7f7-4de1a20ec95a">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-728)

**Comment by eviljeff** [comment]
It looks like it _does_ appear in your screenshot, but just as an empty bullet point, because there is no text.  Or is there a 3rd report that is excluded?

**Comment by diox** [comment]
I think the point is that an empty bullet is not very helpful - at least we could add the `reason` of the report.

**Comment by diox** [comment]
Ah right, forgot the grouping and ignore the header... We could maybe display something if empty/non-printable characters only... I imagine reports with no text are going to happen quite often so we should have _some_ way of handling that

**Comment by eviljeff** [comment]
we're in real need of a UX design for how reports are displayed, but in the mean time we can just display `<empty>` I guess.

**Comment by alexandruschek** [comment]
Hello,

I tested this on -DEV and it works as expected.
In case of no message attached, when expanding the "Show 1 report", now: <no message> appears.
In case of a message attached, it works just as before.
Marking this as verified fixed.

Thank you!

**Comment by eviljeff** [comment]
@alexandruschek 

> I tested this on -DEV and it works as expected. In case of no message attached, when expanding the "Show 1 report", now: appears. 

now what appears?  Can you explain further or add a screenshot?

**Comment by ioanarusiczki** [comment]
@eviljeff 

![newUX](https://github.com/mozilla/addons-server/assets/33448286/5f6a7495-d460-4782-b3b0-87a7f0ce8c56)

**Comment by eviljeff** [comment]
> @eviljeff Looks like Escalation have "Reasoning" , Add-on Policies don't

Indeed, that's https://github.com/mozilla/addons-server/issues/21899

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-728
