### ISSUE TITLE
"Banner-no banner" on Add-ons for Firefox For Android page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2191]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Go to "Other Applications" and select "Add-ons for Android" https://addons-dev.allizom.org/en-US/android/

Expected results:
There are no display or layout issues.

Actual results:
There is a place for a banner but no banner.

Notes/Issues:
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue:
![2016-04-05_1013](https://cloud.githubusercontent.com/assets/15685960/14273950/04ef3b90-fb17-11e5-8b60-27d36839e640.png)

**Comment by andymckay** [comment]
@tofumatt doable for tomorrow?

**Comment by tofumatt** [comment]
Yeah, I can get this tomorrow morning or tonight when I get home.

- tofumatt

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage FF45(Win 7). **(I cannot see the change on -dev)**
Postfix screenshot: 
![2016-04-07_1134](https://cloud.githubusercontent.com/assets/15685960/14345370/1c975cce-fcb5-11e5-9dfb-b23e19aba4ce.png)
