### ISSUE TITLE
Remove `fill_cinderjobs_denormalized_fields` management command and tests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#21918]
As part of https://github.com/mozilla/addons-server/issues/21880 We introduced and ran the `fill_cinderjobs_denormalized_fields` command in dev/stage/prod and we can now remove it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-730)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-730
