### ISSUE TITLE
Extension is escalated to AMO - does not work with reject version 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21927]
Tested scenario: 
Content taken down, author appeals, we change the decision and bring the content back up 

https://testrail.stage.mozaws.net/index.php?/cases/view/2498882

1. A report is escalated to AMO 
2. The reviewer rejects the version 
3. Author appeals 
4. Decision is to change the initial decision 

Actual result:
extension stays disabled,  author does not receive an email 

Expected result :
content is reinstated and an email is sent to the author 

"Hello,

Previously, your Extension was suspended/removed from Mozilla Add-ons, based on a finding that you had violated Mozilla's policies.

After reviewing your appeal, we determined that the previous decision was incorrect, and based on that determination, we have restored your Extension. "

This is not reproducible with force-disable.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-732)

**Comment by ioanarusiczki** [comment]
This is also reproducible with themes escalated to AMO when version is rejected.

**Comment by eviljeff** [comment]
So the scenario here is a cinder moderator looking at the appeal job in cinder and changing the decision from a reject version policy to the Approve policy?

**Comment by eviljeff** [comment]
So, this is because we didn't implement reversing version rejection on the back of the cinder webhook requests (because cinder moderators can't trigger the version rejection in the first place).  A successful appeal via the reviewer tools should work (i.e. the version will be unrejected; an email will be sent to the add-on developers).  

But, like you've detailed, it is possible for it to happen if the report was escalated and then the moderator doesn't escalate the appeal.

**Comment by eviljeff** [comment]
The solution we're going with is to make an appeal for a reject version action be dealt with in the reviewer tools rather than cinder.

**Comment by ioanarusiczki** [comment]
@eviljeff it would simplify things.

**Comment by ioanarusiczki** [comment]
@eviljeff 

Extensions, a listed approved version is reported, Cinder moderator escalates report to AMO. Extension is flagged for human review displayed in the Manual Review queue:

- reviewer rejects the version. The author appeals. Now the appeal is no longer in Dev Listings , it's only present in rev tools, the version is displayed in the Manual Review queue. The reviewer chooses to reinstate content and unrejects. E-mail is sent, but there's some problems known from https://github.com/mozilla/addons-server/issues/21879, a followup has been filed.

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629967

- reviewer force-disables the addon. The author appeals. The add-on is not in the Manual Review queue, yet the appeal is displayed on the review page.  With force-enable content is reinstated and the email is sent to the author which in this case is correct, because the version is automatically approved.  After force-enable action, the addon is  now displayed in the Manual Review Queue (but now it should no longer be there because it's been reviewed). This is also known from https://github.com/mozilla/addons-server/issues/21879 but there's no followup filed yet.

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629968

Themes:
- with 1 listed approved version when it's rejected then un-rejected , it's not auto-approved and the email is sent to the author (as for extensions) https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629969

- after author's appeal, they're not displayed in the Updated queue , doesn't matter if it's been rejected or force-disabled.  After force-enable , the version is displayed in the list of Updated https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629970. Let me know if you need a followup (could be all in one issue to cover extensions and themes)

It's great that when reports are escalated the following appeals don't go to Cinder anymore, and they're displayed directly in reviewer pages 👍 I did not test other possible scenarios yet but I'm hoping to cover more tomorrow.

**Comment by eviljeff** [comment]
@ioanarusiczki I wasn't 100% what part of your comments was describing functionality that was broken/missing vs. expected, but yes follow-up issues if something isn't already covered by an existing issue please.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-732
