### ISSUE TITLE
Extension is escalated to AMO , decision is confirmed after author appeals - no emails sent 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21928]
https://testrail.stage.mozaws.net/index.php?/cases/view/2499473

Scenario is: Content taken down, author appeals, we confirm the decision
 Tested with reject and force disable actions.

Expected:
When the appeal is denied (step4) an email should be sent the author.  Content is stays disabled.

Actual result:
Email not sent to the author. Content stays disabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-733)

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/21716

**Comment by eviljeff** [comment]
It's not clear to me from the description or testrail where things are happening.  Is the denial of the appeal happening in cinder or on AMO?

**Comment by ioanarusiczki** [comment]
@eviljeff Ok, I'll have to re-check

**Comment by ioanarusiczki** [comment]
@eviljeff 

It looks like the only time I received an email was when it all went through Cinder, report in listings , cinder moderator decides to take down content, emails are sent to reporter and author. Then author appeals, moderator denies appeal -> content is disabled, an email is sent to the author that the [previous decision was correct](https://github.com/mozilla/addons-server/issues/21873#issuecomment-1968633512).






I didn't get an email on [version reported for add-on policies](https://testrail.stage.mozaws.net/index.php?/cases/view/2525449) with "clear needs human review" reviewer action.

Since I don't have specifications how exactly escalations should work , I tried the cases below, none of them sent an email:
- addon report is escalated to amo,  author's appeal is moderated from Cinder (with Deny Appeal) , that's [my initial report about ](https://github.com/mozilla/addons-server/issues/21928#issue-2154339495). 
- [add-on's report and then author's appeal](https://testrail.stage.mozaws.net/index.php?/cases/view/2525303) both escalated to amo 
- [only author's appeal is escalated to amo ](https://testrail.stage.mozaws.net/index.php?/cases/view/2525445)

**Comment by ioanarusiczki** [comment]
As for https://github.com/mozilla/addons/issues/1760 this is still happening 

I tried with a report escalated to AMO for an extension and an escalated appeal for a [theme](https://reviewers.addons.allizom.org/en-US/reviewers/review/1025864). 

I received this email 

![incorrect email](https://github.com/mozilla/addons-server/assets/33448286/3427d48a-2b48-4c67-93ab-328460a43a54)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-733
