### ISSUE TITLE
Revert special characters handling for cinder API integration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21926]
https://github.com/mozilla/addons-server/pull/21866 added escaping for certain characters that cinder errored on, if they were the first character in the string.  https://mozilla-hub.atlassian.net/browse/TSPLAT-152 indicates this has now been fixed in cinder so we should be okay to revert that change (probably not a straight git revert)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-731)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I tried with ` =, +, -, or @'` when making a decision on reports/appeals/escalations on rev tools pages and it worked as expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-731
