### ISSUE TITLE
Update monitor.json to check Cinder

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21931]
split from https://github.com/mozilla/addons-server/issues/21853

We should add a check for cinder api to monitor.py to ensure they are up and we can make authenticated requests to their servers.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-734)

**Comment by eviljeff** [comment]
@mozilla/addons-amo-engineering in some of our monitor checks we try to carry out an actual task that would use the service in question (e.g. we test the database by doing `Addon.unfiltered.exists()`); in others we call a specific `__heartbeat__` or similar url.  

The latter is more "correct"... but #21853 was logged because our auth wasn't set up and a `__heartbeat__` ping wouldn't catch that. Thoughts?

**Comment by eviljeff** [comment]
cinder has a `/health` heartbeat like endpoint btw.

**Comment by eviljeff** [comment]
In the absence of dissenting opinions I will implement pinging of the basic `/health` endpoint for consistency with other services.

**Comment by diox** [comment]
@eviljeff `cinder` should appear in https://addons-dev.allizom.org/services/monitor.json following this, right? I'm not seeing it...

**Comment by eviljeff** [comment]
> @eviljeff `cinder` should appear in https://addons-dev.allizom.org/services/monitor.json following this, right? I'm not seeing it...

release master has been failing since https://github.com/mozilla/addons-server/commit/823e825a30ca9ce0605d1f1c944fdfd19f0a7cbf cc @KevinMind

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-734
