### ISSUE TITLE
Layout issues in Statistics Dashboard

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2194]
Steps to reproduce:
1. Sign in to AMO-dev
2. Load Statistics page for an add-on with public stats (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/statistics/ )

Expected results:
There are no display or layout issues.

Actual results:
There are some layout issues.

Notes/Issues:
Maybe is related to #2186 .
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue: 
![2016-04-05_1117](https://cloud.githubusercontent.com/assets/15685960/14276035/b57dfc14-fb24-11e5-9e04-ddbb53e7ff42.png)

**Comment by tofumatt** [comment]
Deployed to stage.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage FF45(Win 7).
Postfix screenshot: 
![2016-04-07_1033](https://cloud.githubusercontent.com/assets/15685960/14343841/4294076e-fcac-11e5-8879-13bf3709991d.png)
