### ISSUE TITLE
Reporter appeals - same email is sent with "Deny Appeal" and "Accept Appeal"

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21947]
1. A theme is reported lands in Cinder Stage Themes 
2. Moderator's decision is "Approve/Ignore" 
3. E-mail is sent to the reporter. Reporter sends the appeal https://addons.allizom.org/en-US/abuse/appeal/56295/d0462ba2-c1ce-439c-a92a-76bfb2e0f575/
4. Appeal is in Cinder Stage Themes https://stage.cinder.nonprod.webservices.mozgcp.net/job/0fe0c5e3-de3b-437a-9a14-377da9f57f2a
5. Use "Accept Appeal"

Result: 
Reporter receives an email - that content does not violate Mozilla's policies 
https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/146267/change/

6. Repeat all steps above and instead of "Accept Appeal" click on "Deny Appeal"

Result: 
Same email is sent to the reporter as for "Accept Appeal" 
https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/146284/change/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-739)

**Comment by eviljeff** [comment]
@ioanarusiczki from https://stage.cinder.nonprod.webservices.mozgcp.net/investigate/amo_addon/1023630?tab=decisions&filters=%7B%7D it appears the appeal has been "denied" with the IGNORE/APPROVE policy, so it is actually an accept.

**Comment by ioanarusiczki** [comment]
@eviljeff 

This changed. Right now there's new UI and it's pretty clear:

Uphold decision - content stays up, sends the final email to the reporter
Adjust decision - content stays up,  choosing the same action Ignore/Approve sends the final email to the reporter too 

![new buttons](https://github.com/mozilla/addons-server/assets/33448286/7bec1774-77c1-4063-8801-49c8d44d4746)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-739
