### ISSUE TITLE
Author/reported appeals - email not sent with Adjust decision + an action that would disable

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21948]
1. A rating is deleted after being reported 
2. Author sends an appeal https://addons-dev.allizom.org/en-US/abuse/appeal/fb5c2345-187c-49ff-82fe-78b95448b74f/
3. In  AMO Dev Ratings https://stage.cinder.nonprod.webservices.mozgcp.net/job/8a4d4e78-1856-4a1a-82ee-26eb70c8e7ba moderator chooses to "Deny Appeal" 

Result:
Content is not reinstated and an email is sent to the author https://addons-internal.dev.mozaws.net/en-US/admin/models/amo/fakeemail/120428/change/

4. Instead of "Deny Appeal" use "Adjust Decision" + the same action that initially deleted the rating (in this case it's Content - Spam)
https://stage.cinder.nonprod.webservices.mozgcp.net/job/104402b0-e34f-4f0d-8a30-adea5e61b682

Result:
Content stays disabled/deleted but there's no e-mail sent to the reported.

5.  Instead of "Deny Appeal" use "Adjust Decision" + any other action that would disable/delete content 
https://stage.cinder.nonprod.webservices.mozgcp.net/job/014b0c7b-5ed0-4c85-843e-ff16b2f69fc2

Result:
Content stays disabled/deleted but there's no e-mail sent to the reported.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-740)

**Comment by ioanarusiczki** [comment]
This was also reported with  https://github.com/mozilla/addons-server/issues/21870

**Comment by eviljeff** [comment]
@ioanarusiczki there's something I'm not following here - it's an appeal but you're _not_ denying and _not_ approving the appeal?  Is Cinder showing the appeal as being completed in some way?

(It seems to be working as we expected designed - if a moderator overrides a decision to change the policy but the action is still the same we don't email the developer because there's nothing to tell them.  But if you're saying that the override somehow resolves the appeal then that's news to us!)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Quite confusing because I thought that after an appeal is moderated , the author should get an email about the final decision.  Not sending anything means that the developer/author doesn't know what's been decided.

This is the email sent with deny appeal

![deny appeal](https://github.com/mozilla/addons-server/assets/33448286/ee9a3e19-2082-47a6-8039-634d1e20bab7)

![possible actions](https://github.com/mozilla/addons-server/assets/33448286/77094cdd-a254-412c-b05a-1615222be6d0)

When I choose adjustment,  job is closed 
https://stage.cinder.nonprod.webservices.mozgcp.net/job/7f1732bc-9b38-4b67-b31f-d7b4c71e7e89
https://stage.cinder.nonprod.webservices.mozgcp.net/job/22355d06-74e6-4262-9775-65a461b58082

Same with deny appeal https://stage.cinder.nonprod.webservices.mozgcp.net/job/a0f6ff3a-aa70-4174-b611-1058ee199968

Not sure what[ "resolution status"](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjM2/details?tab=jobs&filters=%7B%7D) is

**Comment by eviljeff** [comment]
There have been some recent changes with how appeals are implemented in cinder, and it appears they go deeper than just the UI.

**Comment by eviljeff** [comment]
> Adjust decision + the same action that initially deleted the content reported is sending the email , content is not reinstated

A correct email, I assume?

> Adjust decision + + any other action that would disable/delete content doesn't send the email, content is not reinstated -> leaves me the question if that's a bug

We should always send an email when we're resolving an appeal, so if one isn't being sent then it's a bug.   (I can guess what's happening - I think we're wrongly treating the decision as an override that that owner doesn't need to know about)

**Comment by ioanarusiczki** [comment]
@eviljeff 

It's the correct email 

![correct email](https://github.com/mozilla/addons-server/assets/33448286/bcd21e47-68f8-4afc-9b4a-eba7f153e679)

Then I'm leaving this open , issue's name still describes what's going on.

**Comment by ioanarusiczki** [comment]
I verified this on stage and it looks good to me now.

With an appeal adjustment https://stage.cinder.nonprod.webservices.mozgcp.net/job/110c90f2-4b58-4802-8ca3-8b0e550813eb I received [the email ](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154835/change/)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-740
