### ISSUE TITLE
refactor `CinderJob.DECISION_ACTIONS` into /constants/

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21954]
We define the possible values of `CinderJob.decision_action` in `CinderJob.DECISION_ACTIONS` but also reference it widely elsewhere.  If we refactor to move the definition out of the model it will be easier to use - including in other constants (e.g. the activity constants, where we are defining `cinder_action` as a string currently)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-742)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-742
