### ISSUE TITLE
Multiple "Only with Firefox - Get Firefox Now" buttons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2195]
Relates to #2126 

Steps to reproduce:
1. Load AMO-dev using Chrome 
2. Go to "Games & Entertainment" -> "Most Popular" - page 2 : https://addons-dev.allizom.org/en-US/firefox/extensions/games-entertainment/?sort=users&page=2
3. Hover over FoxTrick 

Expected results:
There are no display or layout issues.

Actual results:
The "Only with Firefox - Get Firefox Now" is displayed multiple times. (one for each platform availability)

Notes/Issues:
Verified on AMO-dev Chrome (Version 49.0.2623.110 m) (Win 7)
Screenshot for this issue: 
![2016-04-05_1408](https://cloud.githubusercontent.com/assets/15685960/14280366/0f4c4e92-fb3b-11e5-8b80-7cb674487d8f.png)

**Comment by muffinresearch** [comment]
@ValentinaPC do you have a new example of this one?

**Comment by ValentinaPC** [comment]
Here's a link from add-on details page: 
https://addons-dev.allizom.org/en-US/firefox/addon/avira/ (using Chrome Version 50.0.2661.75 m)

Or you can make an empty search and hover around:
![2016-04-15_1430](https://cloud.githubusercontent.com/assets/15685960/14560199/b734c264-0316-11e6-88ec-66ef12e2db50.png)

**Comment by andymckay-limited-access** [comment]
This is a dupe of mozilla/addons#105

**Comment by ValentinaPC** [comment]
The issue is not fixed.
Verified on AMO-dev using Chrome Version 50.0.2661.94 m.
See the screenshot: 
![2016-05-11_1244](https://cloud.githubusercontent.com/assets/15685960/15176989/6ed869f2-1776-11e6-90fc-b5ac0f598d3c.png)
or the link: https://addons-dev.allizom.org/en-US/firefox/addon/foxtrick/?src=cb-dl-users

@andymckay-limited-access : are you sure about the dupe part? Thanks!

**Comment by ValentinaPC** [comment]
This is still happening in AMO-dev FF46(Win 7).
Please see the screenshot: 
![2016-05-11_1721](https://cloud.githubusercontent.com/assets/15685960/15184204/e9dd23ce-179c-11e6-81b2-d50b81d812fd.png)

**Comment by andymckay** [comment]
Ah thanks its mozilla/addons#104.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Chrome 50.0.2661.94 m (Win 7)
Postfix screenshot: 
![multiple-platforms](https://cloud.githubusercontent.com/assets/15685960/15219844/f3fe708e-186d-11e6-8c01-60188fb9d2e5.png)
