### ISSUE TITLE
Cinder UX - when multiple reporters send appeals, only one reporter is displayed on appeals 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21962]
When multiple reporters appeal on the right panel there's "Appealed by" section ->  but there's only the first reporter displayed

![appealed by](https://github.com/mozilla/addons-server/assets/33448286/70fdef06-10fe-4cbe-be0d-8dd9da83d510)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-746)

**Comment by eviljeff** [comment]
a fix is in progress apparently

**Comment by eviljeff** [comment]
I think this is fixed (as the fix ended up breaking our appeal implementation). If not it should be in their bug tracker (lindie)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-746
