### ISSUE TITLE
Clear needs human review action should work with reports escalated from Cinder to AMO - on dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#21961]
I tried to use "clear needs human review" in rev tools when:
1. a report goes to Dev Listings and it is escalated to AMO 
2. Extension is flagged for human review https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629849#review-actions
3. Reviewer on AMO clears needs human review and checks the DSA Report (decision is not to take down content for an already approved version)

Expected result:
An email should be sent to the reporter 

Actual result:
Email is not sent, and the report is still in DSA Section. 

This is not reproducible on stage https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/1023832, it looks like it could be a regression. 
It is not reproducible for "Approve"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-745)

**Comment by ioanarusiczki** [comment]
I'm marking this verified since the reported issue is fixed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-745
