### ISSUE TITLE
"Works with ..." text is missing from Desktop compatible Android addons

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2197]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/android/
2.Hover with mouse over some Android addons which are compatible with Desktop too

Expected results:
There is a text saying that the addon is working with a range of Firefox for Android versions

Actual results:
This text is missing

Please see video for this bug : http://screencast.com/t/lMrZpCCbxj3W

**Comment by vcarciu** [comment]
Same issue with the text saying that your addon is not available for your Firefox version : http://screencast.com/t/7qhc0In7ZN

**Comment by krupa** [comment]
With the missing button indicating incompatibility, the user needs to click to the details page to find out that the add-on is unavailable. This would be a good one to fix.

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/38e2ISAoOc3x
