### ISSUE TITLE
Prevent Unreject reviewer tools action from resolving cinderjobs/abuse reports

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21987]
Follow-up from https://github.com/mozilla/addons-server/issues/21879

~Currently the reviewer tools expected operation is the unreject version(s) action sets the status to awaiting review (without notifying the developer) and then a further action is made to approve the versions.  This doesn't work with how we are using the reviewer tools action to resolve an abuse report appeal~

see following comments

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-752)

**Comment by eviljeff** [comment]
@wagnerand heads up on this change, because the unreject action is a longstanding feature. 

The other alternative (which could have it's own edge cases and limitations) is making unreject _not_ be an action that can resolve jobs/appeals, and one that doesn't send out any emails to the developer.  Then the approve action would be the one that resolves the job/appeal.

**Comment by wagnerand** [comment]
@eviljeff Let's do the alternative. Indeed unrejecting a version (as long as it puts an add-on into an awaiting state) would not resolve a job/appeal. It's the decisive action (approve, reject, disable, block ...) that resolves them.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-752
