### ISSUE TITLE
Refactor cinder integration models/class/utils to centralize email logic in one place

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21986]
Right now, what email a reporter or content-owner gets in response to a decision that's been made - if any - depends on logic in multiple different places:
- The CinderAction class name defines what template is sent to a content-owner.
  - appeals or overrides aren't differentiated, unless `CinderJob.get_action_helper` returns a specific CinderAction.
    - some CinderActions can't ever send any emails because `get_owners` specifically returns an empty list.
    - some templates are used for both overrides and appeals, with `{% if %}` conditionals.
  - for cinder decisions, whether the content-owner gets an email depends on `process_action` returning `True` (or `True` as the first item in the tuple returned after https://github.com/mozilla/addons-server/pull/21858).  Some CinderAction classes have a process_action that always return `False`
  - for amo reviewer decisions, the content-owner always gets an email.
- `reporter_template_path` in the CinderAction class defines what email template a reporter gets
  - appeal templates are directly defined as `reporter_appeal_template_path` in the CinderAction class; overrides are treated as non-appeals.
  - for some CinderActions the appropriate property is None/undefined so a reporter can't ever be sent an email.
  - with cinder decisions whether the reporter gets an email depends on logic in `CinderJob.process_decision`
  - and for amo reviewer decisions the reviewer always gets an email

This logic, unsurprisingly, makes for difficult debugging when we get an issue filed that says an email wasn't received (or the wrong content was received); and testing has to be integration tests from at least the CinderJob level, if not the webhook/reviewers view (which is always impractical to cover every exact combination of conditions).

Ideally we should refactor so:
-  _if_ an email is sent is defined only by one method for content-owners, and one method for reporters (and completely unit-tested); 
- _what_ email is sent is defined consistently with content-owners and reporters

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-751)

**Comment by eviljeff** [comment]
After #22118 landed:

What email a reporter or content-owner gets in response to a decision that's been made - if any - depends on logic in these places:
- The CinderAction class name defines what template is sent to a content-owner.
  - appeals or overrides aren't differentiated, unless `CinderDecision.get_action_helper` returns a specific CinderAction.
    - some templates are used for both overrides and appeals, with `{% if %}` conditionals.
  - if a CinderAction shouldn't send an email, `get_owners` specifically returns an empty list.
- `reporter_template_path` in the CinderAction class defines what email template a reporter gets
  - appeal templates are directly defined as `reporter_appeal_template_path` in the CinderAction class; overrides are treated as non-appeals.
  - if the reporter shouldn't be sent an email for a CinderAction, `reporter_template_path` and `reporter_appeal_template_path` are `None`
    - `CinderDecision.get_action_helper` overrides `reporter_template_path` and `reporter_appeal_template_path` in some cases (overrides)

I think this is enough of an improvement to call this closed

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-751
