### ISSUE TITLE
rename CinderJob.decision_id column

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#21999]
https://github.com/mozilla/addons-server/issues/21990 will add a `decision` foreign key to `CinderJob` ... which means a `decision_id` column to hold the pk.  But we already have a different (type charfield) column called `decision_id`.  Lets rename it beforehand (actually create a new column and then copy the values across)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-756)

**Comment by ioanarusiczki** [comment]
@eviljeff 

this qa not needed?

**Comment by eviljeff** [comment]
@ioanarusiczki it should be a transparent change but to be sure, you can check you can start an appeal on a decision that was made before this change landed (2024-03-12 15:12) because that will verify the decision ids were correctly migrated.

**Comment by ioanarusiczki** [comment]
@eviljeff I've sent https://addons.allizom.org/en-US/abuse/appeal/54893/f9d81f48-4a7f-4ea4-a6ab-3586c32ee580/ , it's from Feb 27th but I didn't see the appeal in Stage Listings or the extension being flagged for review in rev tools. 

So far I couldn't find another decision made before March 12th

**Comment by eviljeff** [comment]
I found decision [f9d81f48-4a7f-4ea4-a6ab-3586c32ee580](https://stage.cinder.nonprod.webservices.mozgcp.net/decision/f9d81f48-4a7f-4ea4-a6ab-3586c32ee580) - it's was a decision on a user, at least according to cinder, and I see it in AMO Stage Users, so I think we're good.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-756
