### ISSUE TITLE
Reporter appeals with Cinder - decision to take down content sends the wrong email , content stays up 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#22011]
I tried -dev and -stage and it looks like there's a regression at reporter's appeals with the new UI

1. Send a rating/theme report from AMO 
2. Open the job in Cinder and choose Ignore/Approve
3. Send reporter's appeal 
4.  Try to revert the initial decision with adjust decision 

Expected result: 
2 emails are sent , one to reporter and one to the author 

Actual result:
An email is sent to the reporter that content does not violate Mozilla's policies. Content is not taken down. 

![adjust appeal issue](https://github.com/mozilla/addons-server/assets/33448286/bd2819d1-809a-48f9-bc72-ba3da6654011)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-757)

**Comment by ioanarusiczki** [comment]
I tried with a rating, sent the [appeal](https://addons-dev.allizom.org/en-US/abuse/appeal/29309/78a4ac3d-a134-428f-be0b-0520a046dc4f/) but the reporter is still receiving the wrong email and content is not taken down 

![email sent](https://github.com/mozilla/addons-server/assets/33448286/e66ba70f-5ac2-461b-b721-35216fb09b4a)

**Comment by eviljeff** [comment]
@ioanarusiczki Is this is your appeal?  You denied the appeal according to cinder?
![Screenshot 2024-04-16 172853](https://github.com/mozilla/addons-server/assets/768592/a4466f08-87ca-4e57-86e9-93780535b69d)

**Comment by ioanarusiczki** [comment]
I don't know about that one but I'll give another example:

Report send to Cinder https://stage.cinder.nonprod.webservices.mozgcp.net/job/94ae1c5f-023a-441b-8201-6029b0199a57

Appeal is sent on email https://addons.allizom.org/en-US/abuse/appeal/58430/b2f1109c-bcf4-4e6a-8e65-8edf289e4bd6/  

Appeal is displayed in Cinder queue https://stage.cinder.nonprod.webservices.mozgcp.net/job/272faf03-1022-494c-83f0-1076417c84a6 -> where I chose Adjust decision + Acceptable Use

The email sent to the reporter is https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154816/change/

**Comment by eviljeff** [comment]
Something unexpected is happening, because you're choosing Adjust decision - i.e. confirming the appeal - but cinder's UI [afterwards](https://stage.cinder.nonprod.webservices.mozgcp.net/job/272faf03-1022-494c-83f0-1076417c84a6) states "Deny Appeal", and more importantly for this issue, the JSON cinder sends says "confirm", so we don't take any action.

```
{
  "event": "decision.created",
  "payload": {
...
      "decision": {
        "id": "e2334be5-be66-4b4e-90a5-82ba99ca40af",
        "type": "confirm",
        "metadata": {}
      }
...
}
```

**Comment by eviljeff** [comment]
Cinder UI reported to the vendor to fix.  We'll going to have to deal with the JSON ourselves though

**Comment by ioanarusiczki** [comment]
Verified on dev and stage with a rating and a theme 

After adjusting appeal from Cinder using an action that disables content the emails sent are the expected:

reporter 

![reporter](https://github.com/mozilla/addons-server/assets/33448286/83d81709-a173-4be0-b8a8-be27ce52237b)


author 

![author](https://github.com/mozilla/addons-server/assets/33448286/37fd10bc-9c2f-4481-b801-603245f724d1)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-757
