### ISSUE TITLE
Themes escalated to AMO - after the author sends an appeal, they're not displayed in the Updated Queue

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#22013]
Followup for https://github.com/mozilla/addons-server/issues/21927#issuecomment-1991907340

1. A theme's job is Escalated from Cinder to AMO
2. AMO Reviewer decides to reject or force-disable it , taking down the content
3. The Author appeals

Expected result:
theme should be available in the Updated Queue 

Actual result:
theme is not displayed in the Updated Queue's list 

4. Use unreject or force enable to reinstate content. 

Result:
with unreject theme is not in the Updated Queue (expected at this point) https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629997
with force-enable the theme is now available in the Updated Qeueu https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629970

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-759)

**Comment by eviljeff** [comment]
There are two problems here - one is https://github.com/mozilla/addons-server/issues/22012 - but then after that is fixed we additionally filter by status in `UpdatedThemesQueueTable`

**Comment by eviljeff** [comment]
@ioanarusiczki can you confirm the steps you took to escalate the theme to AMO?  When I looked there isn't an escalate policy available in Cinder for the AMO Dev Themes queue.

**Comment by ioanarusiczki** [comment]
@eviljeff Number 7 and 10 from here https://docs.google.com/spreadsheets/d/14wu7Vip25NS4iVMu3fKLz9SgDHyGEz6-2XcX-6C6vaM/edit#gid=0 are actions that would send the report to AMO to be resolved.

**Comment by eviljeff** [comment]
@wagnerand fyi there are a number of policies that implicitly escalate to amo, that can be used for themes.  (It's news to me!)  

They should be visible in the theme update queue after #22123 however

**Comment by wagnerand** [comment]
@eviljeff ok thank you for the heads up, I will raise that.

**Comment by ioanarusiczki** [comment]
Now the report escalated from Cinder doesn't make the theme visible in the Updated Queue.  Only author's appeal would.  

There is also another possibility or scenario, when only the author's appeal is escalated from Cinder.  In this case the escalated appeal won't make the theme visible in the Updated queue. Also there would be another problem in rev tools because for reconfirming the initial decision to take down content "clear needs human review" action cannot be attached to a version. Example is https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630549#review-actions It works with force-enable to reinstate content.

**Comment by eviljeff** [comment]
For this issue too, @ioanarusiczki I think you might have experienced the side effect from https://github.com/mozilla/addons-server/issues/22128 landing - that escalations appearing in the reviewer tools defaults to off.

**Comment by ioanarusiczki** [comment]
Oh .... re-testing ...

**Comment by ioanarusiczki** [comment]
The only problem I see now is that after force-enable the version is still in the Manual Review Queue. 

Example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630575

**Comment by ioanarusiczki** [comment]
Filed https://github.com/mozilla/addons/issues/1758

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-759
