### ISSUE TITLE
Update nonprod autograph configs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#22016]
We need to switch to new signer IDs on -dev and stage (both envs should point to the same Autograph staging instance). This should be a matter of updating the following env variables to new values (also provided):

- `AUTOGRAPH_SIGNER_ID` (defined [here](https://github.com/mozilla/addons-server/blob/0c83a6ccbc0d1ac75857c0c04de2089d3ad7b471/src/olympia/lib/settings_base.py#L1232)) should be set to `cas_cur_webextensions_rsa`
- `AUTOGRAPH_RECOMMENDATION_SIGNER_ID` (defined [here](https://github.com/mozilla/addons-server/blob/0c83a6ccbc0d1ac75857c0c04de2089d3ad7b471/src/olympia/lib/settings_base.py#L1235-L1236)) should be set to `cas_cur_webextensions_rsa_rec`

Note (1): this should only apply to -dev and stage, not prod!
Note (2): to keep Autograph working locally, I wouldn't change the default values in code but rather configure env variables in our Ops configs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-760)

**Comment by willdurand** [comment]
This is in progress. I filed https://mozilla-hub.atlassian.net/browse/SVCSE-1827 for -dev.

**Comment by willdurand** [comment]
AMO -dev has been updated.  I've requested the same change applied to stage in https://mozilla-hub.atlassian.net/browse/SVCSE-1831

**Comment by ioanarusiczki** [comment]
@willdurand 

With Nightly 125.0a1 last updated on March 14 -> I tried some installs on dev and stage but I did not have problems

Nightly updated on -dev:

- extension throw the corrupt error but I've also found some I could install
https://addons-dev.allizom.org/en-US/firefox/addon/version-testing_revert2/
https://addons-dev.allizom.org/en-US/firefox/addon/xuxen2/
or
https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/

- for a lang pack I could only install a new one submitted today
https://addons.allizom.org/en-US/firefox/addon/release-lang-pack_test/

- I could not install any theme without making a new submission today

on Stage , I get the error message

- could not install a new submitted lang pack 
 https://addons.allizom.org/en-US/firefox/addon/release-lang-pack_test/

- I could install a new submitted extension and theme
https://addons.allizom.org/en-US/firefox/addon/an-extension-today/
https://addons.allizom.org/en-US/firefox/addon/a-test_test/

- could install an older dictionary
https://addons.allizom.org/en-US/firefox/addon/dict-with-rules/

**Comment by willdurand** [comment]
> * but I've also found some I could install

Hum, that shouldn't be possible. I personally cannot install:

- https://addons-dev.allizom.org/en-US/firefox/addon/version-testing_revert2/
- https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/

As for https://addons-dev.allizom.org/en-US/firefox/addon/xuxen2/, this is a dictionary so that is expected AFAIK.

For stage, I personally cannot install:

- https://addons.allizom.org/en-US/firefox/addon/an-extension-today/
- https://addons.allizom.org/en-US/firefox/addon/a-test_test/

**Comment by ioanarusiczki** [comment]
@willdurand 

I was using:
extensions.webapi.testing -  true
xpinstall.signatures.required - false
xpinstall.signatures.dev-root - true

I think all 3 prefs should be set to true, because with xpinstall.signatures.required - true, I get[ your results](https://github.com/mozilla/addons-server/issues/22016#issuecomment-2003653639)

**Comment by willdurand** [comment]
Right, `xpinstall.signatures.required` should always been set to `true`.

**Comment by willdurand** [comment]
> I think all 3 prefs should be set to true, because with xpinstall.signatures.required - true, I get[ your results](https://github.com/mozilla/addons-server/issues/22016#issuecomment-2003653639)

That is looking good then, I'll close this issue when stage is updated.

**Comment by willdurand** [comment]
... it looks like stage has been updated. Please verify stage like you've done it for -dev and we should be good.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-760
