### ISSUE TITLE
After editing a review and refreshing the page , the old review is displayed

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2201]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to any addon details page in -dev
2.Write a new review
3.Edit the review from step 2
4.Refresh the page

Expected results:
The edited review is displayed after page refresh

Actual results:
The original review is displayed after refresh

Please see video for this issue: http://screencast.com/t/U4Rh7dv1MjO

NOTES: Not reproducibe on Stage or Prod

**Comment by andymckay-limited-access** [comment]
@jasonthomas is this the -dev server just being slow at celery/es/something else?

**Comment by jasonthomas** [comment]
This is similar to https://github.com/mozilla/addons-server/issues/2295 which I am currently investigating.

**Comment by jasonthomas** [comment]
I switched to faster caching instances on -dev and I can no longer replicate this issue.

Tested with https://addons-dev.allizom.org/en-US/firefox/addon/addthis1

**Comment by vcarciu** [comment]
Verified as fixed. Issue not reproducible anymore.
