### ISSUE TITLE
After the author sends an appeal , extensions are not displayed in the Manual Review Queue 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#22012]
Followup for 

https://github.com/mozilla/addons-server/issues/21879#issuecomment-1978460546
and https://github.com/mozilla/addons-server/issues/21927#issuecomment-1991907340

Content is taken down from rev tools -> it applies to extensions reported for add-on policies or reports escalated to AMO

1. Reviewer force-disables the addon 
2. The author appeals

Expected result: 
 The add-on should be in the Manual Review Queue. 

Actual result:
Add-on is not in the Manual Review Queue. 

3.  The appeal is present in the DSA section - resolve it with force-enable 

Result:
the extension is displayed now in the Manual Review Queue (but it's already been reviewed) 

This is not reproducible with reject - unreject actions. 

Examples:
add-on policies 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/629881
 https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629893

escalated 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/629968

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-758)

**Comment by eviljeff** [comment]
After investigating - in `get_queryset_for_pending_queues` we currently filter out in `STATUS_DISABLED` add-ons, so this is hiding appeals on disabled add-ons.

**Comment by ioanarusiczki** [comment]
Tested with  https://addons-dev.allizom.org/en-US/firefox/addon/add-on-policies-disable/
 
For add-on policies, after report is sent, the extension is not displayed in the manual review queue. It's available after author's appeal. (the opposite of what was happening initially)

It is working now with the report escalated from Cinder. The extension is displayed in the Manual Review queue after report is escalated and then again after the author is sending the appeal.

**Comment by eviljeff** [comment]
@ioanarusiczki I think you might have experienced the side effect from https://github.com/mozilla/addons-server/issues/22128 landing - that new reports appearing in the reviewer tools defaults to off.

**Comment by ioanarusiczki** [comment]
Appeals will display extensions in the Manual Review Queue. 

As I said for [themes](https://github.com/mozilla/addons-server/issues/22013#issuecomment-2061438608), after force-enable action, the human review flag is not removed so the version is still present in the queue. It can be manually removed with "clear needs human review".  I'll file a followup.

**Comment by ioanarusiczki** [comment]
Filed https://github.com/mozilla/addons/issues/1758

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-758
