### ISSUE TITLE
Introduce a command to resign test XPIs used in mozilla-central

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#22024]
We'd like to have a semi-automated way to resign test XPIs used in mozilla-central. Let's use a `process_addons` task for that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-765)

**Comment by willdurand** [comment]
After some discussions with @diox and @rpl, we decided to not pursue this path.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-765
