### ISSUE TITLE
No flag option for theme update

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2202]
Steps to reproduce:
1. Add an update for any theme in AMO-dev (https://addons-dev.allizom.org/en-US/firefox/addon/temapentruvoi/)
2. Go to theme review page https://addons-dev.allizom.org/en-US/editors/themes/queue/single/temapentruvoi
3. Observe the available options

Expected results:
There are "Request More Info", "Flag", "Duplicate", "Reject", "Approve Theme" options available.

Actual results:
The "Flag" option is not displayed.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue: 
![2016-04-05_1747](https://cloud.githubusercontent.com/assets/15685960/14286100/9bbb8350-fb56-11e5-89cd-3f4bbc61832d.png)

**Comment by andymckay-limited-access** [comment]
@muffinresearch could you check if this is the style refresh or something else please?

**Comment by muffinresearch** [comment]
There's no flag button in the markup .

**Comment by muffinresearch** [comment]
This is the condition for the flag button:

https://github.com/mozilla/addons-server/blob/7a6b9ce050a0b3f1cf76dc8a1773cba1de770bc8/src/olympia/editors/templates/editors/themes/themes.html#L90

Looks like this might be a re-review in which case this is expected.

**Comment by muffinresearch** [comment]
Since this seemed like it was expected I'm closing this.
