### ISSUE TITLE
Remove command used to merge and clean-up categories

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#22030]
As part of https://github.com/mozilla/addons-server/issues/5989 we added a command to update and clean up old categories. That command is no longer required and can be removed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-766)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-766
