### ISSUE TITLE
Display issues on dev hub and rev tools pages 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#22045]
On -dev and -stage , a black border is on most of the pages on dev hub

![devhub](https://github.com/mozilla/addons-server/assets/33448286/679f8378-66e9-4920-8bce-502b809c89a7)

Also present on Manage Authors & License, Manage Status & Versions

Rev tools:

![rev tools](https://github.com/mozilla/addons-server/assets/33448286/4f1d1224-0f65-49c8-aecb-d0c2e2837900)

Also present on the reviewer pages

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-770)

**Comment by ioanarusiczki** [comment]
@KevinMind this is looking good on dev 😃  Waiting for stage.

**Comment by ioanarusiczki** [comment]
Verified on -stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-770
