### ISSUE TITLE
Upgrade base image from debian buster to bullseye or bookworm

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#22041]
Although debian buster is technically still supported as a LTS we should upgrade to bullseye or even bookworm.

Notably, official docker python images no longer include buster since https://github.com/docker-library/python/commit/5d908b0477c003712550c84ac4d133367b912f78

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-768)

**Comment by diox** [comment]
QA: nothing specific here, it can affect anything in addons-server, so a complete sanity check of the site on dev is required.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-768
