### ISSUE TITLE
Allow decisions to exist without a cinder job, and for those decisions to be appealled

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#22049]
part of https://mozilla-hub.atlassian.net/browse/AMO-116

Following on from https://github.com/mozilla/addons-server/issues/21990 we need to make some changes in the CinderJob & CinderDecision models, and CinderAction classes, to separate decision related functionality from a CinderJob instance, because that may not exist - i.e. when a decision was made after a proactive reviewer decision

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-771)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-771
