### ISSUE TITLE
[l10n] string needs context

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#22042]
### Describe the problem and steps to reproduce it:
[`The provided code is invalid. Please use the link in the email sent to your email address %(email)s. - could be unauthorized - could be expired - could be a mistake`](https://pontoon.mozilla.org/nl/amo/LC_MESSAGES/django.po/?string=302028)

### What happened?
Should this part  be part of the string or is this the comment for the string? It looks out of place:` - could be unauthorized - could be expired - could be a mistake` ?

### What did you expect to happen?
The second half of the sentence doesn't appear to belong to the rest of the string.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-769)

**Comment by peiying2** [comment]
@diox could you help find the right person to answer this question. Thanks again!

**Comment by diox** [comment]
@flodolo caught that before you :) The string has since been changed in https://github.com/mozilla/addons-server/pull/22005 and re-extracted.

[The new version reads](https://pontoon.mozilla.org/nl/amo/LC_MESSAGES/django.po/?string=302035):
> The provided code is invalid, unauthorized, expired or incomplete. Please use the link in the email sent to your email address %(email)s. If the code is still not working, please request a new email.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-769
