### ISSUE TITLE
Devhub fails to load with django-debug-toolbar enabled

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#22053]
STR:
- Load a devhub page other that the index locally with django-debug-toolbar (4.3.0) enabled

Expected result:
- Page loads successfully

Actual result:
- Page fails to load with a traceback
- 
![Screenshot 2024-03-21 at 12-35-56 UndefinedError at _developers_addon_lobra-eellant-wallamst_ownership](https://github.com/mozilla/addons-server/assets/187006/a3360e91-9f92-48f3-9815-240249c0d99c)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-773)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-773
