### ISSUE TITLE
Update nonprod autograph configs to `cas-new`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#22051]
Similar to https://github.com/mozilla/addons-server/issues/22016, we want to switch keyids again on AMO -dev and stage to use `cas-new` certs. I am guessing we need to set the following env vars to new values as such:

- `AUTOGRAPH_SIGNER_ID` to be set to `cas_new_webextensions_rsa`
- `AUTOGRAPH_RECOMMENDATION_SIGNER_ID` to be set to `cas_new_webextensions_rsa_rec`

We'll also need to double-check with QA that they are ready for that on their end.

Note: this is only for -dev and stage, not prod!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-772)

**Comment by willdurand** [comment]
I filed https://mozilla-hub.atlassian.net/browse/SVCSE-1872 for SREs

**Comment by willdurand** [comment]
That was done last week.

**Comment by alexandruschek** [comment]
Hello,

I tested this manually and also through multiple runs of the automated install tests on -dev and -stage and all was good.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-772
