### ISSUE TITLE
handle no versions being flagged for needs human review in CinderActionEscalateAddon

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#22074]
regression from #22033 - traceback in https://mozilla.sentry.io/issues/5089687497/

> ValueError: max() arg is an empty sequence

@ https://github.com/mozilla/addons-server/blame/ec711d9ebe9dd6a2ab0bf3af1cd1591da2e5b64d/src/olympia/abuse/utils.py#L320

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-780)

**Comment by ioanarusiczki** [comment]
I tried for 
 https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630233 
 https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630225 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630158 

they show up in the manual review queue and the report is in the dsa section but the flag is not present in the version history.

**Comment by ioanarusiczki** [comment]
Add-on policies are displayed on reviewers pages on dev

![dsa fixed](https://github.com/mozilla/addons-server/assets/33448286/3aac2102-147a-411a-9db9-0e3e2967aa8a)

**Comment by ioanarusiczki** [comment]
@eviljeff I don't know what I've been thinking yesterday but looking again, the flagged for add-on policies is not displayed in add-on history. Should be "flagged for human review" Reported for abuse within the add-on

I see it on [-stage](https://reviewers.addons.allizom.org/en-US/reviewers/review/1025296), but not on -dev

**Comment by ioanarusiczki** [comment]
Did some checks and I didn't see anything new besides https://github.com/mozilla/addons-server/issues/22110 which has already been filed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-780
