### ISSUE TITLE
Cinder Policy sync fails to complete if some policies have a name longer than 50 chars

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#22081]
STR:
- (If on a fresh local environment, set up `CINDER_API_TOKEN` and `CINDER_SERVER_URL` in your local settings to point to a valid Cinder API token/URL)
- Make sure to have a Policy in Cinder (https://stage.cinder.nonprod.webservices.mozgcp.net/policies/ for the stage env) with a name that is more than 50 characters long.
- Trigger `./manage.py sync_cinder_policies` or use the `Sync from Cinder` button in `/en-US/admin/models/abuse/cinderpolicy/`

Expected results:
- We should see all policies seen in the corresponding Cinder environment when looking at the list in the admin (http://olympia.test/en-US/admin/models/abuse/cinderpolicy/)

Actual results:
- Only a specific number of those policies are imported (any policies created after the one with the long name, including that one, are missing)

Note: If using `https://stage.cinder.nonprod.webservices.mozgcp.net/api/v1/`, we should see the full list from https://stage.cinder.nonprod.webservices.mozgcp.net/policies/. At the time of creating this issue, there are 27 policies and approximately 86 nested policies, so we should get 113 when testing from a completely fresh environment. We are missing a bunch of them because it's stopping as soon as it's processing the one with the longer name.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-785)

**Comment by diox** [comment]
We receive the full list in the API, but we run into:
`django.db.utils.DataError: (1406, "Data too long for column 'name' at row 1")`

**Comment by alexandruschek** [comment]
Hello,

I just triggered a sync on dev, and I see that policies over 50 characters were succesfully added as well as new ones under 50 characters.
I'll leave an example(53 characters):
<img width="1404" alt="image" src="https://github.com/mozilla/addons-server/assets/139126091/8b6310cb-c899-4c03-ad30-b8609fdca9ef">

Marking this as fix verified.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-785
