### ISSUE TITLE
Remove obsolete discovery modules

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2210]
We have code for the following discovery modules (shown in disco pane and homepage): 
* Fx Summer Collection 	
* Fx4 Collection 	
* Olympics 	
* Privacy Collection 	
* Holiday 	
* New Year 	
* Featured Add-ons Collection 	
* Go Mobile 	
* St. Pat Themes 	
* Firefox Tester Tools 	
* Monthly
* Thunderbird Collection 	
* Starter Pack 	
* Featured Add-on 	
* School 	
* Valentines Day 	
* Up & Coming 	
* Travelers Pack 	
* Fitness 	
* Mobile Themes 	
* Webdev Collection 	
* Shopping Collection 	
* Australis Contest Results 	
* Contest Winners

I understand that we might want to enable some of those only during specific time periods, but surely there are some we can remove in there, like `Fx4 Collection` ?

**Comment by andymckay** [comment]
I think @atsay might be able to help with this one.

**Comment by atsay** [comment]
Yes, we would love to remove some of these! Our add-on editor Scott will take a look and make a recommendation.

**Comment by devaneymoz** [comment]
After review, these are the collections we should KEEP (the rest can be cut):

-     Summer Collection
-     Privacy Collection
-     Featured Add-ons Collection
-     St. Pat Themes
-     Monthly
-     Starter Pack
-     Featured Add-on
-     School
-     Valentines Day
-     Up & Coming
-     Travelers Pack
-     Fitness
-     Webdev Collection
-     Shopping Collection
