### ISSUE TITLE
split DSA/Cinder waffle switches

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#22128]
From https://mozilla-hub.atlassian.net/browse/AMO-259
> We need to split off some features gated by the waffle switch enable-cinder-reviewer-tools-integration so that we can enable processing appeals and hold off processing abuse reports (which is blocked by a decision on how to resolve the review capacity issues)
Optional but recommended, we’d also rename enable-cinder-reviewer-tools-integration to something more descriptive.
>
> 
> Proposal:
> 
>     dsa-job-technical-processing (renamed from enable-cinder-reporting) gates technical intake and integration with cinder. Default enabled.
> 
>     dsa-abuse-reports-review gates if jobs from new reports trigger a NHR, so due_date. Default disabled.
> 
>     dsa-appeals-review gates if jobs for appeals trigger a NHR, so due_date. Default enabled.
> 
>     dsa-cinder-escalations-review gates if jobs that are escalated from cinder trigger a NHR, so due_date. Default disabled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-796)

**Comment by ioanarusiczki** [comment]
What exactly should happen for `dsa-appeals-review` when switch is off? 

Because I still see appeals displayed into DSA section

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/630572

**Comment by eviljeff** [comment]
> What exactly should happen for `dsa-appeals-review` when switch is off?

All of these waffle switches should prevent or allow the needs human review flag being set.  So when  `dsa-appeals-review` is active=True a new appeal should cause the add-on to appear in the manual review queue; when it's active=False the add-on shouldn't appear in the manual review queue.  In both cases the appeal would appear on the review page if visited.

Similarly for the other cases with the new waffle switches - new abuse reports; escalations.

**Comment by ioanarusiczki** [comment]
`dsa-job-technical-processing`

Is active = true, reports go to Cinder 
Is active = false, reports are not sent to Cinder

`dsa-abuse-reports-review`

Is active = false, extensions reported for add-on policies don’t show up in the Manual Review Queue
Is active = true , extensions reported for add-on policies show up in the Manual Review Queue

`dsa-cinder-escalations-review`

Is active = false, reports and appeals escalated from Cinder don’t show up in the Manual Review Queue
Is active = true, reports and appeals escalated show up in the queue

`dsa-appeals-review`

Is active = false, appeals of extensions reported for add-on policies or escalated from cinder won't display the extension in the Manual Review Queue/Updated Queue 

Is active = true, appeals make extensions/themes show up in reviewer queues 

Reports/appeals are displayed in the reviewer detail pages but won't be available for reviewers in the queues.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-796
