### ISSUE TITLE
split approval emails into manual and auto approval

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#22125]
implements https://mozilla-hub.atlassian.net/browse/AMO-256

https://github.com/mozilla/addons-server/blob/master/src/olympia/abuse/templates/abuse/emails/CinderActionApproveInitialDecision.txt  is a template used for both manual and auto-approval notification emails.

We need to split this up to have two separate templates with different copy so that it is clear to developers whether their add-on was auto-approved (which does not mean policy-compliance), or reviewed and approved by a human (which does).

The current copy can stay as is for manual approval.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-794)

**Comment by ioanarusiczki** [comment]
An unlisted automatically or manually approved has a slug not the entire url  ` it is now available at /developers/addon/1025816/versions`  Example [here](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154357/change/) 

If that's not ok, I'll file a followup. 

Automatically approved versions have this "Your Extension has been automatically screened and tentatively approved" 
Manually approved versions look like before. An example with a [static theme ](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154344/change/)

**Comment by eviljeff** [comment]
> An unlisted automatically or manually approved has a slug not the entire url ` it is now available at /developers/addon/1025816/versions` Example [here](https://addons-internal.stage.mozaws.net/en-US/admin/models/amo/fakeemail/154357/change/)

the devhub url change is https://github.com/mozilla/addons/issues/1739

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-794
