### ISSUE TITLE
Add-ons details has white background

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2213]
https://www.dropbox.com/s/ff2jltds5xmljrl/Screenshot%202016-04-05%2018.04.16.png?dl=0

Easy fix, my fault.

**Comment by madalincm** [comment]
Verified as fixed in FF45(Win7) in addons-dev.allizom.org
Postfix screenshot:
![addondetailpagepostfix](https://cloud.githubusercontent.com/assets/15685441/14311455/40b57160-fbf0-11e5-831a-644690663743.png)
