### ISSUE TITLE
Distinguish add-ons flagged for abuse/jobs from ones that are queued for another reason

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#22145]
fulfils https://mozilla-hub.atlassian.net/browse/AMO-224

When an add-on has an abuse report (or appeal) outstanding that AMO reviewers need to review we create a NeedsHumanReview instance (commonly called “flagging” it for human review).  When a NeedsHumanReview instance is created it assigns a “due date” for the add-on, which causes it to show up in the manual review queue in the reviewer tools.  We store the reason a NeedsHumanReview is created.  

The ask from operations is that the manual review queue indicate with icons on the row what the reason of the NeedsHumanReview object is.  There will be separate icons for each reason: appeals, abuse reports, and jobs forwarded from cinder.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-797)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-797
