### ISSUE TITLE
Some versions still have a due date even when the add-on was force-disabled

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#22156]
### Describe the problem and steps to reproduce it:
We noticed [on prod](https://reviewers.addons.mozilla.org/en-US/reviewers/review-unlisted/2834759) that a force-disabled add-on still had a version with a due date. While we don't know for sure, our assumption is that it is related to the `Unlisted Auto-approval delayed indefinitely` flag and the ordering of actions when an add-on with that flag gets force-disabled.

According to @diox:

My guess is that it comes down to ordering:
* The add-on has the Unlisted Auto-approval delayed indefinitely flag
* It gets force disabled, which:
  1. Removes all existing NHR
  2. Updates all due dates (at this point the version is still pending review and the flag still present. The version keeps its due date)
  3. Disables all versions

### What happened?
This causes the due date to get updated before the versions are disabled, while they are still in a state that allows a due date.

### What did you expect to happen?
The new due date for the versions should be calculated **after** they are in the right state (i.e. disabled)
 
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-800)

**Comment by wagnerand** [comment]
I cleared the due date for the add-on mentioned above on prod now.

**Comment by ioanarusiczki** [comment]
I could reproduce this on stage indeed,  with 2 unlisted extensions
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1025965 
https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1025972

I verified on dev  with an [unlisted delayed indefinitely ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/630664#review-actions) and an [unlisted temporarily delayed](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/630666#review-actions), and then for a listed delayed indefinitely. 

 Due date is cleared now (checked on reviewer page and admin), extensions are no longer in the Manual Review Queue.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-800
