### ISSUE TITLE
Allow the offer of appeals (for proactive?) to be waffle-able

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#22155]
While we have some flaws in our appeal handling in the reviewer tools we want to put the offer of an appeal for proactive reviews behind a waffle switch - preferably an existing waffle switch, such as `dsa-appeals-review`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-799)

**Comment by ioanarusiczki** [comment]
@eviljeff 

 I tested the switch before https://github.com/mozilla/addons-server/issues/22128#issuecomment-2063177173 but I don't understand what's a proactive user.

**Comment by eviljeff** [comment]
> @eviljeff
> 
> I tested the switch before [#22128 (comment)](https://github.com/mozilla/addons-server/issues/22128#issuecomment-2063177173) but I don't understand what's a proactive user.

sorry, inside baseball.  A proactive decision/review is one that is not on the back of a user abuse report (the opposite term to proactive is third-party-initiated.  

Practically, it means a review in the reviewer tools that doesn't resolve an outstanding cinder job/appeal/escalation.

**Comment by ioanarusiczki** [comment]
I've `dsa-appeals-review` active on stage. 

I see in the Manual Review queue :
- extension that was appealed after being rejected https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1025816
- extension disabled because of an abuse report https://reviewers.addons.allizom.org/en-US/reviewers/review/619782 

Still not clear, should I only see those without abuse reports now?

**Comment by ioanarusiczki** [comment]
Switch inactive 

On dev email sent like this 

![on dev](https://github.com/mozilla/addons-server/assets/33448286/9c9df6b6-0fa0-421c-891e-ed32ab27b1b5)

**Comment by ioanarusiczki** [comment]
On AMO Stage, with `dsa-appeals-review` set to Is Active = False

Appeals are not sent in emails for rejected/disabled extensions without abuse reports

![cherrypickstage](https://github.com/mozilla/addons-server/assets/33448286/35b2dea6-28ce-4564-a110-13bf56226c3b)

For add-ons reported , emails have the appeal url 

![onstagewithareport](https://github.com/mozilla/addons-server/assets/33448286/043449c8-4045-4adb-90dd-03f37e5b2d80)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-799
