### ISSUE TITLE
Monthly pick is weird on stage

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2215]
The Monthly Picks is broken, but easily fixed:

<img width="969" alt="screenshot 2016-04-05 20 49 38" src="https://cloud.githubusercontent.com/assets/90871/14295996/f80e417e-fb6f-11e5-884d-6771f2707b38.png">

**Comment by madalincm** [comment]
Verified as fixed in FF45(Win7) in addons-dev.allizom.org
Postfix screencast: 
![pickofthemonthbanner](https://cloud.githubusercontent.com/assets/15685441/14312856/d73d56d8-fbf6-11e5-9f4e-1f996769d2ff.png)
