### ISSUE TITLE
"Extensions workshop" link from AMO Stage footer is not working

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#22161]
Steps to reproduce:
1.Go to addons.allizom.org
2.Go to the footer of the page and press on "Extensions Workshop " link

Expected results:
Page is successfully opened

Actual results:
Page is not opened and console is returning "Content-Security-Policy: The page’s settings blocked the loading of a resource at https://extensionworkshop.allizom.org/assets/img/favicon.87c0566f.ico (“default-src”). [FaviconLoader.sys.mjs:175:20](resource:///modules/FaviconLoader.sys.mjs)"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-801)

**Comment by willdurand** [comment]
Looks like this has been fixed with a re-deploy.

**Comment by ioanarusiczki** [comment]
I could open EW from stage this morning and it looks good ✌️

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-801
