### ISSUE TITLE
 [fx47] Show compatibility error if an add-on uses FUEL

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2218]
As explained in [bug 1090880](https://bugzilla.mozilla.org/show_bug.cgi?id=1090880), the FUEL library has been removed. All instances of fuelIApplication and the Application JavaScript global should be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The FUEL library is no longer supported. Please use the [Add-ons SDK](https://developer.mozilla.org/en-US/Add-ons/SDK) instead.

Affected add-on: https://addons.mozilla.org/addon/hatena-bookmark/

Release timing: Firefox 47 will be released on June 7th.

**Comment by EnTeQuAk** [comment]
Just to make sure it's not a typo, in our fx40 compat tests we flagged the instances of `fuelIApplication` and `extIApplication` for deprecation - not simply `Application`, but the latter is what we want now?

**Comment by jvillalobos** [comment]
This bug was filed for `fuelIApplication` and `Application`. I don't even remember why we also have `extIApplication`, but I agree it should be flagged as well.

**Comment by retorquere** [comment]
I don't have `fuelIApplication`, `extIApplication` or `Application` anywhere in my code, but I'm getting this through the linter:

```
The FUEL library is no longer supported.
Warning: The FUEL library is no longer supported. Please use the Add-ons SDK instead. See https://developer.mozilla.org/docs/Add-ons/SDK for more information.

chrome/locale/en-US/zotero-better-bibtex/zotero-better-bibtex.dtd
<!ENTITY zotero.better-bibtex.errorReport.reportID "Report ID:">
<!ENTITY zotero.errorReport.context "Application context">
<!ENTITY zotero.errorReport.errors "Errors">
```
