### ISSUE TITLE
[fx47] Show compatibility error if an add-on uses listTokens or listSlots

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2220]
As explained in [bug 1220237](https://bugzilla.mozilla.org/show_bug.cgi?id=1220237), these functions now return a different type. All instances of function calls of listTokens and listSlots should be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

listTokens() and listSlots() now return nsISimpleEnumerator instead of nsIEnumerator. See [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1220237) for more information.

Affected add-on: https://addons.mozilla.org/addon/belgium-eid/

Release timing: Firefox 47 will be released on June 7th.

**Comment by EnTeQuAk** [comment]
@jvillalobos curious if `listModules` should be in the list of flagged function calls as well?

See https://hg.mozilla.org/mozilla-central/rev/63fdedf32876#l5.31

**Comment by jvillalobos** [comment]
Yes, I didn't notice that one. Good call!
