### ISSUE TITLE
No padding between the add-on details and the reviews and statistics links

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2224]
Steps to reproduce:
1. Open detail page of any add-on: (i.e: https://addons-dev.allizom.org/en-US/firefox/addon/clearly/?src=hp-dl-featured)

Expected results:
There are no layout or display issues.

Actual results:
The User reviews link (and the star icons), the statistics link and the manage button (if logged in as an admin or when viewing your own add-on) are to close to the add-on summary.  This is best noticeable when viewing a featured add-on.

Notes/Issues:
Verified in FF45(Win7)  Issue can be reproduced in -dev and stage.
Screenshot for this issue:
![addondetailpagenopadding](https://cloud.githubusercontent.com/assets/15685441/14311775/c02edf2a-fbf1-11e5-97f5-7d188e1a9cd7.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![nopadding](https://cloud.githubusercontent.com/assets/1583842/14487285/721d4b22-016a-11e6-87d9-a42e3c2d5be7.png)
