### ISSUE TITLE
File tree sometimes not being correctly loaded in editor tools

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#2226]
The file tree is not being correctly loaded when visiting https://addons.mozilla.org/en-US/firefox/files/browse/421089/file/data/html/images/themes/default/inspector/UIComponents/VolumeBar.png#top. If you go to https://addons.mozilla.org/en-US/firefox/files/browse/421089/ and then navigate to the file, then the tree is shown correctly.

I found this in combination with mozilla/amo-validator#411 where that specific file is wrongfully considered to have a flagged extension.

**Comment by vcarciu** [comment]
I used this on -dev without issues : https://addons-dev.allizom.org/en-US/firefox/files/browse/201166/file/chrome/flashblock.jar/content/flashblock/authorware.png#top .

Marking bug as verified
