### ISSUE TITLE
Display issues when hovering over “Featured Themes"

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2227]
Steps to reproduce:

1.Open firefox add-ons page: https://addons-dev.allizom.org/en-US/firefox/themes/
2.In “Featured Themes” hover the mouse over the listed themes.

Expected results:
Themes are displayed correctly.

Actual results:
Display issues when hovering over the last themes in the "Featured Section".

Note/Issues:
This issue is reproducing in AMO-dev and AMO-stage.
Video to this issue: http://screencast.com/t/GZUU6RrZEJm

**Comment by muffinresearch** [comment]
So the problem here is hovering over the last item in each row is pushing down the content slightly.

**Comment by tofumatt** [comment]
Ah, okay. Noted.

**Comment by cosminbadescuSV** [comment]
This issue is still reproducing, see the video: http://screencast.com/t/QU8c7GGX4YT

**Comment by cosminbadescuSV** [comment]
This issue is still reproducing, see the video: http://screencast.com/t/0fxKmztkv

**Comment by muffinresearch** [comment]
@cosminbadescuSV I can't reproduce this on osx or windows here: https://addons-dev.allizom.org/en-US/firefox/themes/ - can you double check you can still reproduce with having force-refreshed?

**Comment by cosminbadescuSV** [comment]
@muffinresearch in "Featured Themes" the issue is no longer reproducing but it is reproducible in any theme category see the video: http://screencast.com/t/mdsNELBf5p

**Comment by cosminbadescuSV** [comment]
This issue is not reproducing anymore, video of this issue: http://screencast.com/t/A7hnMhoR
