### ISSUE TITLE
Wrong installation button color for unreviewed add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2230]
Relates to #2057 

Steps to reproduce:
1. Load AMO-stage "Manage My Submission" page https://addons-dev.allizom.org/en-US/developers/addons
2. Go to "Edit Listing" for an unapproved add-on (i.e. https://addons.allizom.org/en-US/developers/addon/%E6%97%A5%E6%9C%AC-test/edit)
3. Click the "View Listing" link

Expected results:
The installation button is yellow with black label.

Actual results:
The installation button is green with white label.

Notes/Issues:
In AMO-dev the button is green with black "+" and white text.
![dev](https://cloud.githubusercontent.com/assets/15685960/14317573/8e36e628-fc11-11e5-954b-7eae867618d5.png)
Verified on AMo-stage FF45(Win 7).
Screenshot for this issue: 
![stage](https://cloud.githubusercontent.com/assets/15685960/14317582/9d0f956e-fc11-11e5-970d-9de109f56f76.png)

**Comment by tofumatt** [comment]
This is a quick fix and I'm adding it to blocks release because it's important to signal to users that an add-on isn't reviewed yet.

**Comment by tofumatt** [comment]
Deployed to stage.

**Comment by ValentinaPC** [comment]
Verified in AMO-stage FF45(Win 7).
Screenshot: 
![2016-04-07_1038](https://cloud.githubusercontent.com/assets/15685960/14343943/095c595a-fcad-11e5-9f2f-daf3911d6fcf.png)

@tofumatt , is the white cross intended?

**Comment by tofumatt** [comment]
Shoot, no. Can you open a separate issue for that? It’s not a blocker but I’d like to fix it.
