### ISSUE TITLE
Rationalize heading margins for "Other Applications" homepages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2232]
relates to #2049 

Steps to reproduce:
1. Load AMO-stage page
2. Click on Other Applications -> Thunderbird
3. Observe page header

Expected results:
There are no layout issues.

Actual results:
The header has no bottom blue margin.

Notes/Issues:
Issue is reproducing only in homepage for Thunderbird and Seamonkey.
Screenshots for this issue: 
![2016-04-06_1650](https://cloud.githubusercontent.com/assets/15685960/14319028/38b67eaa-fc18-11e5-8d0f-db3fc140ba46.png)
![2016-04-06_1651](https://cloud.githubusercontent.com/assets/15685960/14319030/3da22b94-fc18-11e5-95dd-0276e98ea822.png)

**Comment by muffinresearch** [comment]
This was fixed already by the looks of it:

<img width="569" alt="add-ons_for_thunderbird" src="https://cloud.githubusercontent.com/assets/1514/14559544/7943b204-0301-11e6-84d0-f525f14143ee.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshots: 
![android](https://cloud.githubusercontent.com/assets/15685960/14560065/de51a57a-0315-11e6-865e-932af4cce535.png)
![thund](https://cloud.githubusercontent.com/assets/15685960/14560073/ebffd73c-0315-11e6-8228-b72e1db490a9.png)
![sea](https://cloud.githubusercontent.com/assets/15685960/14560081/f936cf82-0315-11e6-945f-1fcffbafa74d.png)
