### ISSUE TITLE
Remove big red header from Dev Hub pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2234]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
According to the style refresh , please remove the big red headers on Dev hub too:
![redheader](https://cloud.githubusercontent.com/assets/1583842/14320939/c118c0d0-fc1f-11e5-9487-d65b5b1c38ca.png)

Please remove this from any addon edit listing pages too and  from developer hub tools:
https://addons.allizom.org/en-US/developers/addon/validate
https://addons.allizom.org/en-US/developers/addon/check-compatibility
https://addons.allizom.org/en-US/firefox/collections/whimboo/devel-tools/

If I will find more places where this is reproducible, I will add them to this bug.

**Comment by vcarciu** [comment]
#2039

**Comment by vcarciu** [comment]
Also, please fix this in "Submit new addon" flow

**Comment by madalincm** [comment]
Also in Editor Tools the title is big and red (https://addons.allizom.org/en-US/editors/)
Shouldn't that be black?
Please view this screenshot:
![editortoolstitle](https://cloud.githubusercontent.com/assets/15685441/14321667/dcc0357c-fc22-11e5-948e-74350172c909.png)

**Comment by tofumatt** [comment]
The red in "Editor Tools" is no longer present (it was fixed elsewhere, but I forget where).

Incoming PR for the rest of the headers 😄

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/qyFpKm6XE
