### ISSUE TITLE
Some pages were not style refreshed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2236]
Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/firefox/
2. Go to My Favorite Add-ons collection page https://addons.allizom.org/en-US/firefox/collections/ValStage/favorites/
3. Click on the "Lean about collections" link

Expected results:
The **FAQ** page is style-refreshed.

Actual results:
The page is not style-refreshed.

Notes/Issue:
Issue is reproducing for **a 404 page **-> https://addons.allizom.org/en-US/firefox/addon/add-on-%C4%83%C4%83%E6%9C%AC%E6%9C%AC/ and for **a 500 page** -> 
![2016-04-06_1811](https://cloud.githubusercontent.com/assets/15685960/14321720/07e36486-fc23-11e5-8932-8c5d3dcda526.png)
Edit listing -> **View Recent Changes** for any addon:
![2016-04-06_1814](https://cloud.githubusercontent.com/assets/15685960/14321855/9147b6fa-fc23-11e5-8b5a-2fd3947393c3.png)

Verified on AMO-stage FF45(Win 7). Reproducible on AMO-stage and dev.
Screenshot for this issue: 
![2016-04-06_1735](https://cloud.githubusercontent.com/assets/15685960/14321728/194c3c8e-fc23-11e5-9be6-1e8b96332b42.png)

**Comment by muffinresearch** [comment]
@ValentinaPC it might be easier to break this up into an issue for each page that needs looking at.

The 404 has been dealt with.

**Comment by ValentinaPC** [comment]
I'll mark this verified as fixed, because all mentioned pages were fixed. (I'll log another for everything else)
Verified on FF45(Win 7) AMO-stage.
Postfix screenshots: 
![404](https://cloud.githubusercontent.com/assets/15685960/14533200/cdd30440-026c-11e6-9504-1fcc1efc82ab.png)

![faq](https://cloud.githubusercontent.com/assets/15685960/14533336/57c43c82-026d-11e6-9a43-3da8ac8a07a0.png)
![oops](https://cloud.githubusercontent.com/assets/15685960/14533346/5fd30be2-026d-11e6-8c01-888e559d46bc.png)
