### ISSUE TITLE
make editor review page accessible after addon is deleted

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#2242]
We retain pretty much everything about an add-on after its deleted so we have an audit trail.  But without the review page its non-trivial to get that data.  The review page can be accessed via the addon.pk so its really just using the right AddonManager object fixing whatever errors happen with a deleted add-on.

**Comment by eviljeff** [comment]
follows on from #2090 @jvillalobos

**Comment by andymckay-limited-access** [comment]
Would it make sense to have this in the new internal search that can search all add-ons be them deleted or not?

**Comment by eviljeff** [comment]
yes, it would be good if the internal search could return deleted add-ons.

**Comment by diox** [comment]
That's something I had planned to support in the new admin search. It requires some extra work - currently those add-ons, even if we soft-delete them, are removed from the search index - but definitely on my radar.

**Comment by ValentinaPC** [comment]
@eviljeff : I don't know is I got this right, but I can still not able to access editor review page for a deleted add-on.
Verified on AMO-dev FF45(Win 7).
Please see the creencasts for this issue:
-deleting the add-on:
![deleted addon](https://cloud.githubusercontent.com/assets/15685960/14785235/7b474b7a-0b02-11e6-89e5-005eeec3367a.gif)
-searching and accessing review page:
![search review page](https://cloud.githubusercontent.com/assets/15685960/14785251/8ac910ec-0b02-11e6-90d8-375e9f850a6e.gif)

**Comment by eviljeff** [comment]
The page is accessible but only via the add-on's numeric id - the /slug/ is cleared when the add-on is deleted.  Most links on pages don't account for this (the slug is null now, hence None) - the unlisted review tools do so a link from the 'Unlisted all' list would work, or manually typing in a review url with the add-on ID replacing the slug.
