### ISSUE TITLE
Include management URLs when permitted

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#2244]
If the user can access the management page for a resource we should include that URL in the response. `manage_url` or `edit_url` are probably good names but it can be whatever makes sense.

```
GET /api/v3/addons/addon/my-addon/?lang=en-US
200 OK

{
  "url": "https://addons.mozilla.org/en-US/firefox/addons/my-addon/",
  "manage_url": "https://addons.mozilla.org/en-US/developers/addons/my-addon/",
  "current_version": {
    "url": "https://addons.mozilla.org/en-US/developers/addons/my-addon/versions/18726/",
    "manage_url": "https://addons.mozilla.org/en-US/developers/addons/my-addon/versions/18726/edit",
    ...
  },
  ...
}

**Comment by diox** [comment]
Ok. I might have to separate the serializer for search and the one for the detail endpoint then - I would like the regular search API to remain anonymous, to keep it fast.

**Comment by mstriemer** [comment]
I was thinking the client wouldn't send the credentials to the search API when it was being used in an anonymous fashion. So internal search would send them but a new frontend for AMO or disco pane search would not.

**Comment by diox** [comment]
Yes. Actually, I'll be implemented an internal search specific endpoint in which I may return those, and keep the regular search endpoint (which you would no longer use until we rebuild the frontend :) anonymous-only. That's #1914.

**Comment by mstriemer** [comment]
Sweet, I commented on that one. I'll close this.
