### ISSUE TITLE
Android add-on  with contribute roadblock has an underlined download button

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2247]
Steps to reproduce:
1. Load details page for an android add-on with contribute roadblock (i.e. https://addons.allizom.org/en-US/android/addon/comicscom-search/?src=search )
2. Click the "Continue to Download" button
3. Observe the "Download now" button

Expected results:
The button has no layout issues.

Actual results:
The button label is underlined.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![2016-04-07_1131](https://cloud.githubusercontent.com/assets/15685960/14348289/2ece72d8-fcc4-11e5-8be4-42cf4ef56d3a.png)

**Comment by eviljeff** [comment]
See [our contributing document](https://github.com/mozilla/addons-server/blob/master/CONTRIBUTING.rst)
mentor @muffinresearch

**Comment by gamebusterz** [comment]
I'd like to work on this, any help regarding where I should be looking for the problem ?

**Comment by eviljeff** [comment]
You can use the devtools in Firefox to inspect the button and see the css rules and computed styles.

https://github.com/mozilla/addons-server/blob/master/static/css/restyle/restyle.less#L1263:L1266 is causing it, but it looks unintended (there is another template that shares the same classes).

There are many possible fixes but imo the easiest is to add a subsequent rule of `.notice.c.author a.download { text-decoration: none; }` to override the download button specifically.

**Comment by EnTeQuAk** [comment]
Apparently I didn't check properly that the commit message didn't contain a "fixes #..." so this is the manual closing notification from https://github.com/mozilla/addons-server/pull/4159

Thanks a lot @gamebusterz for working on this and fixing it!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50.1(Win 7)
The button is no longer underlined.
Posftix screenshot:
![2017-01-04_1157](https://cloud.githubusercontent.com/assets/15685960/21638681/0b199462-d275-11e6-857d-fdb6a63b0cd4.png)

Note: @EnTeQuAk  #3581 is happening in this page, too.
