### ISSUE TITLE
Some promo modules are not style-refreshed

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2249]
Discovery Modules that only have the class `promo` are not style-refreshed. You can see that by following these STR:
- Go to /discovery/modules admin
- Enable either `Starter Pack`, `Fx4 Collection`, `St. Pat Themes`, `Fx Summer Collection`, `Thunderbird Collection`, `Travelers Pack` or `School`.
- Go to the homepage, look at the added module title style: it's dark grey on blue, and there is no background color

Some of these modules hardcode a specific collection id. Some, like `Starter Pack`, [are even hidden if you've been to the homepage too many times](https://github.com/mozilla/addons-server/issues/2222#issuecomment-206861687). So here are some alternate STR to keep your sanity:
- Make sure `Webdev Collection` is enabled (it is on dev right now)
- Go to the homepage, and open your developer tools inspector, change the `webdev` class to `promo` and look at how it's styled

Note: `Shopping Collection`, `Mobile Themes`, `Fitness`, `Up & Coming`, `Privacy Collection`, and `Featured Add-ons Collection` seem to avoid this bug by specifying in the module definition a second class that adds a background. It's probably better to have the `promo` class provide a default background, though - as long as it's overwritten by the other classes it should not break other modules.

**Comment by tofumatt** [comment]
I'm considering this a blocker, but I'll have a patch ASAP. Agree; I'll just provide a background for `.promo` so we don't get hit by this again (hopefully).
