### ISSUE TITLE
Display issue when rating a collection while logged out

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2250]
**Steps to reproduce:**
1. Make sure you are logged out.
2. Open a collection detail page and click on thumb up/down button (https://addons.allizom.org/en-US/firefox/collections/mozilla/webdeveloper/)

**Expected results:**
The pop up to log in is displayed without any issues.

**Actual results:**
The "Create an Add-on Account" is not displayed correctly inside the borders limit.

**Notes/Issues:**
Verified in FF45(Win7) issue can be reproduced in -dev and stage.
Screenshot for this issue:
![loginbuttonratecollection](https://cloud.githubusercontent.com/assets/15685441/14351708/68ecefac-fcd9-11e5-8139-dcf6cb32ea5f.png)

**Comment by ValentinaPC** [comment]
Does not look cute in AMO-prod FF45(Win7)

**Comment by madalincm** [comment]
Verified as fixed in addons-dev.allizom.org
Postfix screenshot:
![ratecollectionloggedoutfixed](https://cloud.githubusercontent.com/assets/15685441/14669087/08e16af4-06f0-11e6-8ab5-66c43713595a.png)
