### ISSUE TITLE
Misleading information in create new collection page

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2253]
**Steps to reproduce:**
1. Open Create a new collection page: https://addons.allizom.org/en-US/firefox/collections/add
2. Scroll down to the Add-ons in your collection section.

**Expected results:**
There is clear information displayed about how can you later add add-ons to your collection.

**Actual results:**
The Add to collection button was removed from the add-on detail page. The only way you can add and add-on to your collection is to edit your collection or from another collection.  But that icon and that text can't be found anywhere to the site any longer(for add-ons, the link is still displayed for themes) . This might be confusing to the user and we should have clearer information regarding this.

Notes/Issues:
Verified in FF45(Win7) issue can be reproduced in -dev and stage.
Screencast for this issues:
![addtocollection_link](https://cloud.githubusercontent.com/assets/15685441/14353590/5fe4a48c-fce2-11e5-8e2e-559356eea33c.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot:
![2016-04-14_1225](https://cloud.githubusercontent.com/assets/15685960/14523408/3acc541a-023c-11e6-9b91-9f6f14b2693f.png)
