### ISSUE TITLE
Display issue when hovering over "3-rows name" add-ons from Featured section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2256]
Steps to reproduce:
1. Load AMO-stage page
2. Go to an add-on category (i.e.https://addons.allizom.org/en-US/firefox/extensions/download-management/)
3. Hover over an add-on with long name from Featured section (i.e. Mozilla Archive Format, with MHT and Faithful Save)

Expected results:
There are no display or layout issues.

Actual results:
Bottom border appear cut-off.

Notes/Issue:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue: 
![2016-04-07_1820](https://cloud.githubusercontent.com/assets/15685960/14356832/fb51a184-fcee-11e5-9fdb-b76ad3d9d72c.png)

**Comment by andymckay-limited-access** [comment]
This should be totally fixed.

**Comment by tofumatt** [comment]
Should now be fixed.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshots: 
![long_name](https://cloud.githubusercontent.com/assets/15685960/15177343/2df2a4a0-1778-11e6-90e0-1be18be6ed9c.png)
![hover](https://cloud.githubusercontent.com/assets/15685960/15177347/32c0f464-1778-11e6-835d-619c03f1750b.png)
