### ISSUE TITLE
"Featured" Ribbon lock-up looks slightly awkward

### ISSUE THREAD

**Issue by potch** [mozilla/addons-server#2257]
Check out this page:
https://addons.mozilla.org/en-US/firefox/addon/nimbus-screenshot/

Specifically this bit:
<img width="511" alt="screenshot 2016-04-07 11 10 49" src="https://cloud.githubusercontent.com/assets/253470/14361769/678f0d98-fcb1-11e5-8301-c876190fafa1.png">

**Comment by madalincm** [comment]
This looks like a duplicate of #2224
Closing as duplciate.

**Comment by potch** [comment]
Probably a dupe, but also need to address the featured "ribbon" Need a different holding shape if the primary island doesn't have a border.
