### ISSUE TITLE
Contribute button does not align with suggested donation

### ISSUE THREAD

**Issue by potch** [mozilla/addons-server#2258]
This page:
https://addons.mozilla.org/en-US/firefox/addon/nimbus-screenshot/?src=hp-dl-featured

<img width="358" alt="screenshot 2016-04-07 11 18 44" src="https://cloud.githubusercontent.com/assets/253470/14362042/a0d91a34-fcb2-11e5-9a42-c5a1a3e76764.png">

**Comment by krupa** [comment]
sigh, this issue was mentioned in https://github.com/mozilla/addons-server/issues/2009 which was prematurely marked as verified. Thanks @potch was catching this.

**Comment by eviljeff** [comment]
mentor @muffinresearch 
- can you add few details about what a contributor would need to do to fix this?

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by muffinresearch** [comment]
Looks like this has been fixed already:  

![nimbus_screen_capture_-_editable_screenshots____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/25188959/a674ff8a-251f-11e7-864f-c16acf5a207d.png)

**Comment by vcarciu** [comment]
Confirming that it is fixed : 
![contrib](https://cloud.githubusercontent.com/assets/1583842/25243333/55852898-2605-11e7-800b-79e4a196de33.png)
