### ISSUE TITLE
#ui-datepicker-div is visible at the bottom of statistics pages

### ISSUE THREAD

**Issue by potch** [mozilla/addons-server#2259]
This page (hash included to jump you to the spot):
https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30#ui-datepicker-div

<img width="485" alt="screenshot 2016-04-07 11 23 16" src="https://cloud.githubusercontent.com/assets/253470/14362152/274d1322-fcb3-11e5-88aa-bb0d2457f0be.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![datepicker](https://cloud.githubusercontent.com/assets/1583842/15327983/09dd8b0a-1c5c-11e6-88de-eaf1efcf98bc.png)
