### ISSUE TITLE
RTL issues on the homepage

### ISSUE THREAD

**Issue by potch** [mozilla/addons-server#2260]
https://addons.mozilla.org/he/firefox/

Various page element alignment stuff.

**Comment by ValentinaPC** [comment]
There are still some issue for RTL.
Verified on AMO-dev FF45(Win 7).
Please see the screenshots:
![header](https://cloud.githubusercontent.com/assets/15685960/14460062/2dfdb0e0-00c4-11e6-8688-3c6184288db9.png)
![footer](https://cloud.githubusercontent.com/assets/15685960/14460068/333cfea8-00c4-11e6-9b12-4cf77fd7f8ef.png)
![add-on_details](https://cloud.githubusercontent.com/assets/15685960/14460104/4dcea2e4-00c4-11e6-994a-9d0535e3698c.png)

**Comment by muffinresearch** [comment]
I don't think that's on -dev yet or caching is causing a problem.

**Comment by ValentinaPC** [comment]
I've tried on new profile, on AMO-dev FF45(Win 7), and I can still see the same results - so its not cache.

**Comment by muffinresearch** [comment]
> I've tried on new profile, on AMO-dev FF45(Win 7), and I can still see the same results - so its not cache.

I didn't mean the browser cache it's the CDN cache. It's cleared now and working as expected. Sometimes it appears request is made with the new static cache-busted URL before the new static is there. When that happens ops needs to flush the CDN cache as it means we're serving old static files.

**Comment by muffinresearch** [comment]
Ops are going to look at adding the cache flush to the deploy to hopefully alleviate the chances that this will happen in the future.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF45(Win 7) for:
1. https://addons-dev.allizom.org/ar/firefox/
2. https://addons-dev.allizom.org/he/firefox/
3. https://addons-dev.allizom.org/ar/firefox/

and looks ok for homepage and details page in what concern header-banner section.
The major functionality looks RTL.

We could also, be nicer and fix:
1.  "Other Languages" drop-down 
![2016-04-12_1643](https://cloud.githubusercontent.com/assets/15685960/14462110/44e9b538-00ce-11e6-9cbb-4c781f2e9226.png)

2. Complete Themes link from the menu
![2016-04-12_1645](https://cloud.githubusercontent.com/assets/15685960/14462118/4a109ebe-00ce-11e6-8f41-9a513c7149cd.png)

There are some other RTL issues between AMO pages;let me know if we should log other bugs for RTL. Thanks!

Please see the screenshot:

**Comment by muffinresearch** [comment]
> There are some other RTL issues between AMO pages, let me know if we should log other bugs for RTL. Thanks!

Yep I noticed there's some other issues - if you can file new issues for each one that would be much appreciated :+1: .

**Comment by AlexandraMoga** [comment]
Verified in [2393](https://github.com/mozilla/addons-server/issues/2393) and [2395](https://github.com/mozilla/addons-server/issues/2395) for the additional issues observed
