### ISSUE TITLE
No UI to add add-on to favorites / collections in new UI?

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#2264]
Now it can not seem to add an add-on directly from the detail page, can editing a collection to add only.

**Comment by andymckay** [comment]
By design as per #2013

**Comment by atsay** [comment]
Per the UX meeting this morning, we should keep the favoriting feature. The collections feature can be dialed back but users should have a way to favorite add-ons and access them in a list somewhere. @designakt @pwalm @deadsquid @jvillalobos @devaneymoz

**Comment by smayer97** [comment]
Please be sure to understand it is not only about the "Add to Favourites" link but also the "Add to Collections" and associated functions. Please re-read my comments.

If you do not use collections, then I think you are missing the significance of what removing the 2 "simple" links does (Add to Favorites and Add to Collection). It has made it EXTREMELY difficult to manage collections without them. I think it is a great lack of appreciation of how useful collections are and the way they need to be accessed (by collection creators/managers).

Also, given the amount of info on the pages anyway, 2 links on this page are not going to make a UI difference BUT they do add HUGE value. 

Please see my 3 comments here:  
https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/12?u=smayer97

https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/13?u=smayer97

https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/14?u=smayer97

Please seriously reconsider this. Please do not alienate users of collections.

**Comment by muffinresearch** [comment]
@atsay @designakt @pwalm - please could someone file new issues for each thing that needs to be added back and which pages are involved so there's clear direction on what the necessary changes are?

**Comment by pwalm** [comment]
Yep, will do. Going to file issues starting Monday.

**Comment by smayer97** [comment]
Any update on this please?
I can't imagine it is so hard to add back 2 links. They can simply go under the Collections menu, if that works. Otherwise, this is not a difficult change. Please advise.

**Comment by tofumatt** [comment]
If you want to work on it I'm happy to review your pull request quite quickly. 🙂

I don't have an ETA on this; we have a big backlog of things to get to. Thanks for letting us know you're interested though, that helps us prioritise!

**Comment by mikhoul** [comment]
Mozarella is going deep in the Dumb Browser Game, with this move they are clearly the leader for the in that field. :(

They think 2 links will confuse their dumb users... It tell a lot what they want to have as users.

**Here's a fix** **with I've done with a Userstyle that improve a lot AMO overall, add the 2 missing link & make AMO usable at least:** https://userstyles.org/styles/126536/amo-ez-on-the-eyes

**Comment by tofumatt** [comment]
@mikhoul The great thing about add-ons is that they let users customise their experience, just like you did.

Please stop insulting the people who work on Add-ons and Firefox in our issues. We've acknowledged in this issue that we'll be restoring the favourite feature and this issue is open to track it.

**Comment by smayer97** [comment]
Please make sure it is NOT just adding ONE button of Add to Favorites (as suggested here: https://github.com/mozilla/addons-server/issues/2013) but ALSO Add to Collection (as I point out up above). Otherwise, the main issue for managing Collections is not addressed and will continue to frustrate ALL those managing/creating collections other than their single Favourite collection.

**Comment by tofumatt** [comment]
Unfortunately the collections feature is not used by a majority of our users, but it adds clutter to the page. I believe the decision was made to improve the UX for the majority of the users, even though you're right: for heavy users of collections it makes collections harder to manage.

I wonder if an add-on to restore them would be useful? I'm serious; for most users it's not useful, but the API endpoints are still around, so for as long as they are it seems like a good compromise to me.

**Comment by smayer97** [comment]
There are 3 problems with this argument:
- first we are talking about only a LINK on a page....based on how much info is on the page, a single link is not going to make an iota of difference to the UX. There are SO MANY OTHER issues to address if the UX is the problem trying to be addressed. Someone is missing the forest for the trees. 

Think about it...it is ONE link on a page FULL of other "clutter". And yet the benefit is NOT minor, it is HUGE to those who need it. To those that do not use it, it may appear insignificant BUT to those who do use it, it is VERY SIGNIFICANT.

It is not just harder without it, it is virtually impractical without it. We are talking about MANY MINUTES to perform a task that used to take literally SECONDS (see details I provided proving this at links above, especially here: https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/16?u=smayer97). And it is FAR MORE ERROR PRONE, making the task far more time consuming. Multiple that my having to repeat that task several times and now a simple task can take 20-30 mins or more (I've tried)  for what should only take LITERALLY SECONDS, And all this to save one link? Really?

- Also, by removing this link, a feature is completely taken away that HAS NO WORK-AROUND...One of the purposes of the ADD TO COLLECTIONS link is the ability to see which collections an add-on has been added to, in the case when a user adds it to more than one...I as a manager of many collections (120+), and others like me, this is EXTREMELY useful. And there is NO OTHER WAY to perform this task.

- Finally, the argument that few users use this feature seems somewhat shortsighted...Though there are a few creators, managers of collections, collections serve at least 3 purposes. One is that there are many more followers, some officially subscribed , some not. Second, it increases discoverability of add-on's by seeing them linked or grouped with others. This would not show up as number of followers or creators. For creators and managers of collections, this creates more loyal following. So I suspect the volume is less apparent. 

The way that add-ons can be accessed and are visible is one of the biggest strengths of Firefox and the add-on community. Doing things that undermine this I think only undermines the ongoing attraction to Firefox. 

I think someone is really not getting the full impact of removing this SIMPLE link. All just to save room for ONE LINK? It is like removing a piece of lint from your clothes when the whole shirt is full of feathers. Its seems like picking a nit that does little to improve the UX.

And remember, if it really is so important to improving the UX (which I don't see given the many other issues with it), there is a possible solution to help the UX by placing them in the Collections menu, therefore hidden unless you click on the menu. So there are viable alternatives without getting rid of this feature.

Who is responsible for making this decision? If there is any way to bring this to their attention, PLEASE PLEASE PLEASE have someone rethink this. REALLY!

Also note, the ADD TO COLLECTION was a feature that was broken for a long time and I worked hard to finally have this feature fixed and improved just last Fall (Sep 2015). So please do not let all that effort from those involved go to waste.

**Comment by jvillalobos** [comment]
I created an add-on that brings those widgets back: [Add to Collection](https://addons.mozilla.org/addon/add-to-collection/). Should be reviewed / signed soon. Note it doesn't look pretty and it's bound to break in the future. But it should buy the affected people some time while a decision is made here.

**Comment by smayer97** [comment]
thanks jvillalobos. Sounds good for the short term. 
That said, I just tried to download this but I get the following error...It will not install:

![screen shot 2016-05-02 at 7 53 45 pm](https://cloud.githubusercontent.com/assets/6752849/14971402/d967ec26-109f-11e6-97a9-7c2928e3499b.png)

Any Thoughts?

**Comment by jvillalobos** [comment]
You have to wait for it to be reviewed (should happen in a day or so) or [override the signing restriction](https://wiki.mozilla.org/Addons/Extension_Signing) for now.

**Comment by smayer97** [comment]
Thank you !!!!!

Now how to get Mozilla to restore this functionality to the site permanently?

For all those interested, go download this Add-on, and show support for it by writing a positive review. Then spread the word!

**Comment by eviljeff** [comment]
This was a deliberate decision.

**Comment by smayer97** [comment]
Why were these closed? 
Why was it deliberate? What is the point of removing such important functionality?
WIthout, Firefox is not much different than Chrome, et. al...

Please reconsider!

**Comment by smayer97** [comment]
For those following along, be sure to also follow the info at the link provide above:
 https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/16?u=smayer97

**Comment by benryanau** [comment]
Surely the AMO team has to get some clarity here somewhere along the line.
As the perceived impact of this unintrusive feature is such a non-issue someone will remember what Mozila and FF is all about.. the user. Look at AMO, the mass of js, css, images, widgets.. anyway. 
AMO needs so much work to get it actually effective at its core mission.. pulling a solid feature which WAS well done defies logic. 
If it's about the user.. well, **it's an exercise in frustration just trying to find addons on AMO** the user seeks. You have to **FIND** an addon relevant enough to drill down to.. before even having to worry about being accosted by the Fave and Collections threat.
Inevitably the endless pages of uninformative, and mostly irrelevant, results.. means it's even more necessary to keep track of addons a user HAS found. 
Infinite monkeys I hope.

**Comment by smayer97** [comment]
Yes...PLEASE move this up the priority list to restore this functionality! It has virtually crippled my ability to effectively use FF and its add-ons. VERY PAINFUL without easy access to my over 100 Collections. It has been over a year already...
And as the this post shows (https://discourse.mozilla-community.org/t/no-favorite-button-in-new-amo-design/8015/58) users are moving away as a result of this feature missing!

**Comment by smayer97** [comment]
For those interested in following along, here are the links to the Issue Reports for each of the items I have identified…You may want to add your comments or simply subscribe to follow along on the development:

Add To Collection - List not sorted by name – https://github.com/mozilla/addons/issues/676
Add To Collection - Cannot search the list – https://github.com/mozilla/addons/issues/677
Add To Collection - No indicator showing which collection(s) the add-on already belongs to – https://github.com/mozilla/addons/issues/678
Add To Collection - There is no link to open collection from list of collections – https://github.com/mozilla/addons/issues/679

NOTE: Without all these 4 changes to re-implement the original design, the ‘new’ Add To Collection has VERY LIMITED usefulness.
