### ISSUE TITLE
Lets update the "Create a New Theme" banner

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2270]
Steps to reproduce:
1. Sign in to AMO-dev page
2. Go to "Submit a New Theme" page https://addons-dev.allizom.org/en-US/developers/theme/submit
3. Observe the banner

Expected results:
The banner is up to date.

Actual results:
The banner looks very old and dusty. 

Notes/Issue:
Verified on AMO-dev FF45(Win 7)
Screenshot for this issue: 
![2016-04-08_1231](https://cloud.githubusercontent.com/assets/15685960/14380140/a8d17310-fd86-11e5-9dc4-6b042cfcbaa6.png)

**Comment by designakt** [comment]
Let's keep it as is. Looks good enough for me.

**Comment by ValentinaPC** [comment]
@designakt: It is using gradient blue and the image inside the banner represents AMO in its old clothes.... but, your choice.
