### ISSUE TITLE
Add a "Categories" title for Themes categories section

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2272]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

With the new style, we removed any delimitation (we had a dotted line before) between Themes Sorting and Categories section, so please add a "Categories" title for Themes categories section 

Please see the screencast for this bug : http://screencast.com/t/N4fzuf1F

**Comment by muffinresearch** [comment]
Here's a screenshot:

<img width="439" alt="2016-04-08_1312_-_victorashmoto_s_library" src="https://cloud.githubusercontent.com/assets/1514/14505030/3d8ae816-01af-11e6-85ae-7cef4af1ab07.png">

**Comment by atiqueahmedziad** [comment]
@tofumatt please close it as pull request #3033 was merged.

**Comment by vcarciu** [comment]
Verified as fixed : 
![themescat](https://cloud.githubusercontent.com/assets/1583842/18086369/37ee2cf8-6eb8-11e6-858d-ed6a35ed127d.png)
