### ISSUE TITLE
Increase font size + contrast?

### ISSUE THREAD

**Issue by callahad** [mozilla/addons-server#2274]
Per this thread on Reddit: https://www.reddit.com/r/firefox/comments/4dtz7m/addonsmozillaorg_amo_new_look/d1ujfgv, the font size and contrast are subjectively a bit low.

Bumping from `12px #999` to `13px #777` looks compelling to me, as seen in the gif below:

![mopupk3](https://cloud.githubusercontent.com/assets/24193/14391407/6ca6304c-fd81-11e5-93e7-b4f3ddf77e75.gif)

**Comment by pwalm** [comment]
Good eye. Co-signed! SHIP IT.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-12_1751](https://cloud.githubusercontent.com/assets/15685960/14464365/33b4f256-00d7-11e6-8fe1-36e7e1d28150.png)
