### ISSUE TITLE
Unable to add to favorites / add to collections from add-on page

### ISSUE THREAD

**Issue by callahad** [mozilla/addons-server#2287]
Reported at https://www.reddit.com/r/firefox/comments/4dtz7m/addonsmozillaorg_amo_new_look/d1vwob0

Apparently it's not possible to favorite an add-on or add it to a collection with the new design.

**Comment by tofumatt** [comment]
It's possible to add a collection via the actual collection page but not on an add-on page anymore. But this is by design and UX approved; we have a separate bug open t

**Comment by callahad** [comment]
Thank you very much :)

**Comment by tofumatt** [comment]
Shoot I closed this by mistake then my wifi died. But this is a dupe, I'll update the bug in a bit on a better connection.

This is as intended though.

**Comment by Archaeopteryx** [comment]
It's a duplicate of issue #2264.
