### ISSUE TITLE
Incompatible addon versions are inaccessible / can't be downloaded

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#2288]
Incompatible addon versions can't be downloaded because there is only a popup 'Not available for Firefox <int>.0'. This works neither from lists like search results, the details page summary, the version details near the bottom or the page listing all versions.
Example: [MinimizeToTray for FF 3.5](https://addons.mozilla.org/en-us/firefox/addon/minimizetotray-for-ff-35/versions/)
Use case: To look into the code of these extensions.

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/Gkh1l2k3fj
