### ISSUE TITLE
Always show if addon can be installed in listings/seach results

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#2289]
[Example search](https://addons.mozilla.org/en-us/firefox/search/?q=minimize+to+tray&status=4&sourceid=Mozilla-search)

Always show if an addon can be installed in listings/seach results so one can easily view of a search yielded something useful for not or which addon can be installed.

**Comment by pwalm** [comment]
Ideally, we just shouldn't show it. Can we do that? If you can't install it on your platform, you don't see it.

**Comment by pwalm** [comment]
(I believe we did this with Marketplace)

**Comment by andymckay** [comment]
We can, but that's beyond a style change and I think we might want to think about the implications of that. In the old AMO if you couldn't install something it was clear in the search results, by being greyed out..?

**Comment by Archaeopteryx** [comment]
If I remember correct, there was a transparency applied to the listing so everything looked lighter.

**Comment by tofumatt** [comment]
There was a transparency applied; in fact we should have fixed this with transparency (#2024) but it seems it's not showing.

There is supposed to be a class applied to the `div` containing the add-on but it doesn't seem to be getting applied.

**Comment by tofumatt** [comment]
This might need some extra QA magnifying glasses, as this probably affects a fair number of pages. I tested the listings and version page.

**Comment by ValentinaPC** [comment]
@tofumatt : Can we apply this to themes as well?

**Comment by ValentinaPC** [comment]
Does this require another issue to be logged or should we reopen this?
Verified on AMO-dev FF45(Win 7) in https://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/?sort=popular . 
Please see the screencast: http://screencast.com/t/Iv3Ago5kAk

**Comment by tofumatt** [comment]
We can apply it to themes as well, but it should be a separate bug.

- tofumatt

**Comment by tofumatt** [comment]
> Does this require another issue to be logged or should we reopen this?
> Verified on AMO-dev FF45(Win 7) in https://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/?sort=popular .
> Please see the screencast: http://screencast.com/t/Iv3Ago5kAk

Please file a separate bug for this as well. It's definitely a bug, but it shouldn't block release.

**Comment by ValentinaPC** [comment]
I've logged separate issues.
I've verified this all around AMO-dev in FF45(Win 7).
Postfix screenshots: 
![2016-04-14_1959](https://cloud.githubusercontent.com/assets/15685960/14536533/8c4bfbe4-027b-11e6-948f-3984a923ba88.png)
![2016-04-14_2000](https://cloud.githubusercontent.com/assets/15685960/14536538/92bd3e66-027b-11e6-8979-7d13efeeccdf.png)
