### ISSUE TITLE
Pick of the Month background is cut of left and right

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2294]
The cheering crowd behind the pick of the month is currently cut of on the left and right without any visible hint to why this is the case.
![add-ons for firefox 2016-04-11 11-42-42](https://cloud.githubusercontent.com/assets/8145891/14423147/853f92b4-ffda-11e5-8ed6-79896ad237c1.png)
reported by @sevaan

A possible solution could be to end carousel backgrounds before they hit the sides to omit this hard cut-off, as I did with the shopping background that end before the edge of the image.
![screen shot 2016-04-11 at 11 37 59](https://cloud.githubusercontent.com/assets/8145891/14423230/fd4685f6-ffda-11e5-92ec-33b7e6d13320.png)

@pwalm what do you think? Is it something we need to fix? Or  is it ok as it is?

**Comment by muffinresearch** [comment]
What's the expected behaviour? 

This is the image used https://addons-dev-cdn.allizom.org/static/img/zamboni/discovery_pane/promos-refresh/carousel-1.png?222500c it doesn't look like it's being truncated in display or do we need to replace the asset?

**Comment by designakt** [comment]
@muffinresearch this is a design issue first. Nothing to do for engineering so far. We will need to replace assets as soon as they have been created. Scott DeVaney is working with the creative team to provide new graphics.

**Comment by muffinresearch** [comment]
> @muffinresearch this is a design issue first. Nothing to do for engineering so far. We will need to replace assets as soon as they have been created. Scott DeVaney is working with the creative team to provide new graphics.

Ah thanks for clarifying I misunderstood the bug report.
