### ISSUE TITLE
Manual file status change does not work

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2295]
STR:
1. Go to an add-on status management web page, e.g. https://addons-dev.allizom.org/en-US/admin/addon/manage/lingappcom-for-firefox/
2. Chang the status of version 1.1.7.1-signed from `Fully reviewed` to `Preliminary reviewed`.
3. Hit `Update Statuses`.
4. Refresh the page (might be necessary on prod).

Expected result:
The file status should update.

Actual result:
The file status does not update. There have been slight delays in the past, but I waited for more than 30min.

Reproducible on -dev and prod, ~~didn't try on stage~~ not reproducible on stage.

**Comment by diox** [comment]
I have no idea what change could have caused that... It looks like #1970 or #2248 ; would be nice to know if stage is affected as well. Maybe it's just an ops issue with redis or something ?

**Comment by wagnerand** [comment]
stage is not affected.

**Comment by wagnerand** [comment]
This might be related to deleted versions. Adding @eviljeff.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
The add-on has deleted versions (i.e. Version 0.7 · December 20, 2012 · Deleted)
I was able to update versions status using Site Administration page (https://addons-dev.allizom.org/en-US/admin/addon/manage/lingappcom-for-firefox/). Some can be changed instantly some need time...but this another known issue, I suppose.

Please see the screenshots: 
![ed_tools_001](https://cloud.githubusercontent.com/assets/15685960/14462868/94a4ab34-00d1-11e6-9bd5-b1d66dedf51e.png)
![2016-04-12_1711](https://cloud.githubusercontent.com/assets/15685960/14462901/b28ca8a4-00d1-11e6-9449-394e62ce4d8b.png)
