### ISSUE TITLE
Text in add-on image lightbox difficult to read

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2299]
If the text is long, it sometimes is overlapped by the next/previous icons:
![self-destructing cookies -- add-ons for firefox 2016-04-11 16-38-15](https://cloud.githubusercontent.com/assets/8145891/14430970/df295e08-0003-11e6-9d08-f0c2395acbdc.png)
https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

... or a line is cut off:
![classic theme restorer -- add-ons for firefox 2016-04-11 16-38-02](https://cloud.githubusercontent.com/assets/8145891/14430973/e0cebd2a-0003-11e6-9b7e-fb41d951531e.png)
https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/

(seen on Firefox Nightly in Windows 10)

**Comment by muffinresearch** [comment]
Yep this was always the case not something introduced via the refresh afaik.

**Comment by ValentinaPC** [comment]
I've logged this issue a few months ago, and with this I support muffinresearch opinion. 
Please see #1712 .

**Comment by muffinresearch** [comment]
Marking as dupe
