### ISSUE TITLE
Allow/Fix the ability to specify ES index shard size

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/addons-server#2304]
Our indices are large so it would be good if we can specify a shard size larger than 10. 

ES_DEFAULT_NUM_SHARDS doesn't seem like it is getting the correct information and https://github.com/mozilla/addons-server/blob/7a6b9ce050a0b3f1cf76dc8a1773cba1de770bc8/src/olympia/lib/es/management/commands/reindex.py#L5 doesn't seem like it pulls the previous index shard size.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/blob/320c1b7c945f90dd8ff3cca4e370de0e4e74aedd/src/olympia/lib/es/management/commands/reindex.py#L77 is wrong: `ES.indices.get_settings(alias)` will return a dict with the key being the real index name, not the alias. So we never pull the data from the existing index.

In addition, https://github.com/mozilla/addons-server/blob/320c1b7c945f90dd8ff3cca4e370de0e4e74aedd/src/olympia/search/indexers.py#L72 overrides whatever config we pass to `create_new_index()`, so we end up with the default configuration all the time. It should be fixed to merge the two instead.
