### ISSUE TITLE
Search endpoint sometimes returns a 500

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#2306]
There's an exception accessing `current_version` in the new search endpoint at times. See sentry [1].

[1] https://sentry.prod.mozaws.net/operations/olympia-dev/group/323221/

**Comment by diox** [comment]
That's super weird. According to sentry, it's not just missing `current_version` (which could be explained if the add-on was in a weird state), but a bunch of other fields as well. It's like it was not indexed properly... except that I've re-indexed after introducing the new fields and the results are coming from the right index.

I'll investigate more.

**Comment by diox** [comment]
Ok, actually, sentry data was truncated, when looking at the index this addon was indexed properly, it's just that it's buggy and missing `current_version` in the db.

The legacy API cheats and only returns addons with a `current_version` by querying `has_version`, that may work for the public search, but we need to be able to see them in the internal search. Therefore, I will:
  1. Fix the query to avoid those add-ons and therefore avoid a 500 in the public search API
  2. Handle the addons without a `current_version` (just returning it empty) in [the internal search API](https://github.com/mozilla/addons-server/issues/1914).
