### ISSUE TITLE
Contribution display and layout issues on Editor Tools review page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2311]
Steps to reproduce:
1. Sign in to AMO-dev page with an admin account
2. Access the review page for an add-on with contribution (i.e https://addons-dev.allizom.org/en-US/editors/review/wot-safe-browsing-tool?page=2#history)
3. Observe the contribution section

Expected results:
The contribution button should be labeled all white. No underline required. No other display or layout issues.

Actual results:
The contributions button has a black "+" mark (instead of a white heart) and a white "contribute" text. Is underlined. Has a flickering issue when is clicked. The contribution modal is not styled refreshed.

Notes/Issue:
@tofumatt : Is there a need for contribution section in Editor Tools review pages?
Also there are some links hard to read in the contribution section (i.e. What's this?)
Verified on FF45(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue: 
![2016-04-12_1017_001](https://cloud.githubusercontent.com/assets/15685960/14453188/ee28c36a-009b-11e6-8a88-6f4ccddc8229.png)

**Comment by andymckay** [comment]
I think the best thing to do is remove that block as @ValentinaPC mentioned.
