### ISSUE TITLE
"What do you think?" section from theme details page has an "old" background

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2313]
Steps to reproduce:
1. Load AMO-dev any theme details page
2. Go to "What do you think?" section

Expected results:
There is no blue background.

Actual results:
There is a blue, old background,

Notes/Issue:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev. stage and prod.
Screenshot for this issue: 
![2016-04-12_1202](https://cloud.githubusercontent.com/assets/15685960/14455230/273f9e34-00a7-11e6-8876-026078bf7de9.png)

**Comment by eviljeff** [comment]
can someone include the mockup/detail showing what the colour _should_  be?

**Comment by andymckay** [comment]
I don't think this is worth doing and we should won't fix.
