### ISSUE TITLE
No “Push to Public” option in Editor Tools after “Request Full Review” action

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2319]
Steps to reproduce:

1.Open firefox add-ons page: https://addons-dev.allizom.org/en-US/firefox/
2.Hover over “Tools ” and select “Manage My Submissions”.
3.Select an add-on that is “Preliminarily Reviewed” and choose “Manage Status & Versions”.
4.In “Current versions” tab click “Request Full Review” link.
5.Hover over “Tools ” and select “Editor Tools”.
6.Hover over “Queues” and select “Full Reviews”.
7.Search and select the add-on for which was requested a full review.

Expected results:
There is a “Push to Public”option.

Actual results:
There is no “Push to Public” option.

Note/Issues:
User must be logged in as admin.
Verified on FF45(Win 7). This issue is only reproducing in AMO-dev.
Video of this issue: http://screencast.com/t/2NsHyemyI

**Comment by andymckay** [comment]
@krupa could you check if this is occuring on stage so we don't push this out.

**Comment by cosminbadescuSV** [comment]
This issue is no longer reproducing.
