### ISSUE TITLE
Blue text on blue background in footer

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2326]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Load https://addons-dev.allizom.org/en-US/firefox/
2.Observe the footer

Expected results:
Text from footer links is white

Actual results:
Blue text on blue background in footer

Please see screencast for this bug : http://screencast.com/t/gcLy27aBXlWq

**Comment by muffinresearch** [comment]
Hmm I think the change from an id to a class in 27148146be10eca75f5c611cd8012558cacadee2 reduced the selector specificity.

**Comment by vcarciu** [comment]
Verified as fixed:
![blueblue](https://cloud.githubusercontent.com/assets/1583842/14496965/c71bcbfc-019d-11e6-9f18-c8a03ef14c7d.png)
