### ISSUE TITLE
Fix details page secondary width

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2330]
It's too tight:

![phony____add-ons_for_firefox_for_android](https://cloud.githubusercontent.com/assets/1514/14466978/0667a93e-00d1-11e6-92bf-edf6f0ee02d1.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-13_1235_001](https://cloud.githubusercontent.com/assets/15685960/14489276/f12ff6da-0174-11e6-9f6a-544705ecf670.png)

**Comment by ValentinaPC** [comment]
The issue is still reproducing in "Reviews" page.
Please see the screenshot:
![2016-04-13_1710](https://cloud.githubusercontent.com/assets/15685960/14496109/c95890ce-019a-11e6-8220-e97ceba942ce.png)

Verified on AMO-dev FF45(Win 7)

**Comment by muffinresearch** [comment]
I'm going to file another bug for that since it's a different page.
