### ISSUE TITLE
Fix simplejson version in the requirement

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#2336]
We have simplejson>=3.0.5 specified in the compiled.txt requirement file, which was introduced in Sep 2015. Can we lock down its version at this point? 

This requirement is used by production as well, so it'd be nice to lock down its version like all other modules we use in prod.

**Comment by andymckay** [comment]
Please do @bqbn.

**Comment by bqbn** [comment]
Pull request submitted. :)

https://github.com/mozilla/addons-server/pull/2357

**Comment by bqbn** [comment]
Closing this one as pull request has been merged.
