### ISSUE TITLE
Bug in Sort search results by Rating

### ISSUE THREAD

**Issue by tuudara** [mozilla/addons-server#2340]
URL : https://addons-dev.allizom.org
Browser/OS : Google Chrome
Description :Bug in Sort search results by Rating
Steps to recreate 
1.Load AMO Home page
2.Perform a search:Go to "search for add-ons" and click on Search button without typing anything
3.Click on Newest
4.Check whether apps are sorted according to ratings
Expected result 
Rated applications are triggered before  Not rated applications

![rating](https://cloud.githubusercontent.com/assets/18439582/14490587/359bb4b4-0191-11e6-8d64-570c137804f1.PNG)

**Comment by andymckay** [comment]
@diox has been working on the indexing recently.

**Comment by diox** [comment]
I don't understand this issue. If you're sorting by `Newest`, then why would you expect the add-on rating to have an influence on the ranking ? `Newest` just sorts by creation date.

**Comment by diox** [comment]
@tuudara see previous comment.
