### ISSUE TITLE
If the period is customized from Statistics Dashboard for an add-on remains the same for all add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2342]
Steps to reproduce:
1. Go to Statistiscts Dashboard for an add-on with public stats : https://addons-dev.allizom.org/en-US/firefox/addon/downthemall/statistics/
2. Click the "Custom..." link and change the period
3. Go to Statistics Dashboard for another add-on with public stats: https://addons.allizom.org/en-US/firefox/addon/greasemonkey/statistics/
4. Observe the period of the displayed stats

Expected results:
The stats or displayed for last 30 days.

Actual results:
The period that was set to first add-on remains for the second.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screencast for this issue: http://screencast.com/t/rKCnefceA

**Comment by andymckay** [comment]
This is by design, it stores the time period in local storage. Not the best design perhaps.
