### ISSUE TITLE
No padding between "Part of these Collections" and "Other add-ons by" sections in addons details pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2343]
Prerequisites : Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to an addon details page which is included in some collections and be sure that its owner created more addons (https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular)
2.Observe the "Part of these Collections" and "Other add-ons by" sections

Expected results:
There is a padding between these sections

Actual results:
No padding

![nopad](https://cloud.githubusercontent.com/assets/1583842/14492115/e0c4c77e-0185-11e6-9573-0a84320fae90.png)

**Comment by vcarciu** [comment]
Same issue between "Developer's comments" and "Version information" : 
![commvers](https://cloud.githubusercontent.com/assets/1583842/14522971/e38ca382-0239-11e6-8a7c-407d6b9ef8f6.png)

**Comment by muffinresearch** [comment]
This is how it was pre-refresh:

<img width="417" alt="adblock_plus____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14523524/13cba8ee-022c-11e6-8c9c-dfb7b46f985b.png">

**Comment by muffinresearch** [comment]
> Same issue between "Developer's comments" and "Version information" : 

Can you file a new issue for that one please?

**Comment by vcarciu** [comment]
Opened #2376
