### ISSUE TITLE
2 different sizes for “+ Add to Firefox” button

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#2345]
**Steps to reproduce**
1. Navigate to https://addons.allizom.org/en-US/
2. Add to an add-on summary a word that contains more than 25 characters.
3. Check the recently updated add-on in “Other add-ons by …” section.

**Expected Results**
There is only one install button style applied for all extensions.

**Actual Results**
There are 2 different sizes for “+ Add to Firefox” button, which depend on the characters number from summary.
 
**Additional notes:**
- The new button style is always displayed for an add-on from “This add-on requires the following add-ons to work properly:” section and in this situation the summary character number is irrelevant. Screenshot:
![2016-04-13_1443](https://cloud.githubusercontent.com/assets/18114210/14492699/c9fbdb96-0189-11e6-9814-8858c151f5fb.png)

- This issue reproduces on AMO-stage using Firefox 45.0.2 under Windows 10 64-bit.
- Please see the screenshot for this issue:
![jt](https://cloud.githubusercontent.com/assets/18114210/14492722/e7cdf1e0-0189-11e6-9a05-af1621cc6d59.jpg)

**Comment by ValentinaPC** [comment]
"Big" buttons can also be seen in add-ons categories when hovering over add-ons from "Most Popular", "Top Rated" and "Recently Added" sections (summary character number is irrelevant here too).
Please see the screenshot: 
![2016-04-13_1739](https://cloud.githubusercontent.com/assets/15685960/14497240/def51980-019e-11e6-9f3e-d5cd3f46d1e2.png)

**Comment by vasilicamihasca** [comment]
![pic01](https://cloud.githubusercontent.com/assets/18114210/14560906/60a2fa88-031b-11e6-95ae-cfa5ea25a82d.png)
![pic02](https://cloud.githubusercontent.com/assets/18114210/14560912/6547447c-031b-11e6-8b9e-55fc34b96b2e.jpg)
- This issue is no longer reproducible in Firefox application, but I still encounter it in Android application 
![pic03](https://cloud.githubusercontent.com/assets/18114210/14560935/904e5232-031b-11e6-8c12-2cdabd1e489b.png)
- @muffinresearch  Should I reopen this bug or file a separate one?
- The initial issue is now on AMO-production.
- Tested on Firefox 45.0.2 using Windows 10.

**Comment by muffinresearch** [comment]
> The initial issue is now on AMO-production.

Yep, this wasn't in the tag or cherry-picked.

> Should I reopen this bug or file a separate one?

@vasilicamihasca yep if you can file a new bug with a link to where we can see it that would be much appreciated.

**Comment by vasilicamihasca** [comment]
I am marking this bug as verified since the other issue is tracked separately (#2423).
