### ISSUE TITLE
Long add-on name or more than one install button breaks "Required Add-ons" section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2346]
Steps to reproduce:
1. Load details page for an add-on with "Required Add-ons" section: i.e. https://addons.allizom.org/en-US/firefox/addon/addontest13-04/
2. Hover over displayed add-ons

Expected results:
There are no display or layout issues.

Actual results:
The "This add-on requires the following add-ons to work properly:" sections breaks.

Notes/Issues:
The section looks bad if we have a "Meet the developer" section.
Screenshot: 
![2016-04-13_1535](https://cloud.githubusercontent.com/assets/15685960/14493315/82869586-018d-11e6-96a4-06cc023cb30a.png)

Verified on FF45(Win 7). Issue is reproducing on AMO
Screenshot for this issue: 
![2016-04-13_1522](https://cloud.githubusercontent.com/assets/15685960/14493341/9c2da1d2-018d-11e6-9fc2-45a5d0f442ad.png)

**Comment by muffinresearch** [comment]
I think the main problem here is that the hovercard styling is being explcitly removed by the refresh (not sure if that was a design decision or not?). This suggests the best solution to cleaning this up is going to be to re-instate the hovercard styling for these addons.

Also what is the undefined? Is that just a data issue?

**Comment by muffinresearch** [comment]
@ValentinaPC would you be able to set-up a new example of this one -dev please? The link to stage is broken.

**Comment by ValentinaPC** [comment]
Sure!
Please hover over the middle add-on :smile: 
https://addons-dev.allizom.org/en-US/firefox/addon/unlimited-free-vpn-test3/

**Comment by tofumatt** [comment]
I don't think the long names really affect much, but the multiple buttons definitely do.

**Comment by tofumatt** [comment]
I think the best solution is to not have these be hovercards and instead show all the info at once. The hover effect here seems silly and the call to action is clearly: "install these other add-ons so everything works". No sense obscuring the install buttons/compatibility info.

It's a bit more cluttered that way, but this is a rarely used feature and for power users, right? Most add-ons don't require other software from what I've seen.

**Comment by muffinresearch** [comment]
As an aside it would be nice to know the numbers of addons using the dependent addons feature. If it's not used then it might be something we don't retain in the future.

**Comment by tofumatt** [comment]
I think the best solution is to not have these be hovercards and instead show all the info at once. The hover effect here seems silly and the call to action is clearly: "install these other add-ons so everything works". No sense obscuring the install buttons/compatibility info.

It's a bit more cluttered that way, but this is a rarely used feature and for power users, right? Most add-ons don't require other software from what I've seen.

**Comment by tofumatt** [comment]
I re-evaluated and:

1. I don't know why these hovercards were disabled
2. There can be a lot of info in these if the add-on isn't supported for this version of Firefox

Re-implementing the hovercards was an easier and aesthetically more pleasing solution, even though it's arguably a *bit* more work to see the install button. Given how (seemingly, without numbers) rare this feature is, I think that's an alright compromise here. PR incoming.

**Comment by ValentinaPC** [comment]
Unfortunately, the issue is not fixed.
Verified on AMO-dev FF45(Win 7).
Please see the screencast: http://screencast.com/t/uzD3RI0Tty

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshots: 
![2016-04-19_1005](https://cloud.githubusercontent.com/assets/15685960/14630468/8cd8bee6-0616-11e6-8313-74c9d2ebc693.png)
![2016-04-19_1007](https://cloud.githubusercontent.com/assets/15685960/14630469/91e051ec-0616-11e6-8a70-498adb85035e.png)
