### ISSUE TITLE
Background breaks if window is smaller than page in Stats Dash using Responsive Design Mode

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2352]
Steps to reproduce:
1. Load Statistics page for an add-on with public stats in AMO-stage: https://addons.allizom.org/en-US/firefox/addon/firebug/statistics/?last=30
2. Resize the browser using Responsive Design Mode (i.e. above 1020px width)

Expected results:
There are no display or layout issues.

Actual results:
There is a white vertical bar displayed.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue: 
![2016-04-13_1901](https://cloud.githubusercontent.com/assets/15685960/14500770/fc6b509e-01ab-11e6-9593-0ef236be8c70.png)

**Comment by muffinresearch** [comment]
Seems to be windows only. 

I don't think this is a big enough problem to spend time on so I'm going to wontfix.
