### ISSUE TITLE
Secondary column is too narrow on reviews page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2353]
Relates to #2330

![c95890ce-019a-11e6-8220-e97ceba942ce](https://cloud.githubusercontent.com/assets/1514/14504799/370b69c6-01ae-11e6-8aa3-6d22bd6a1ca3.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-14_1147](https://cloud.githubusercontent.com/assets/15685960/14522352/cc017cb8-0236-11e6-857e-57c66325296f.png)
