### ISSUE TITLE
Add-on metadata links in review page are white text on white background

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2360]
Abuse Report, Privacy Policy, and EULA are affected, at least.
![white-links](https://cloud.githubusercontent.com/assets/62568/14511097/631e116a-0192-11e6-848c-3fb9e1f9dfe9.png)

**Comment by wagnerand** [comment]
Requesting cherry-pick.

**Comment by tofumatt** [comment]
You can add the commit hash for the commit itself (not the merge commit)
that fixes this bug to the push doc ether pad (in the #amo topic) to have
it be cherry-picked as well, just so it doesn't get lost in GitHub
notifications.

- tofumatt

**Comment by vcarciu** [comment]
Verified as fixed : 
![editor](https://cloud.githubusercontent.com/assets/1583842/14526664/91e8e0b8-024d-11e6-964c-a991f485272b.png)
