### ISSUE TITLE
Missing buttons in AMO Editor Tools

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#2362]
I have admin rights, but when I go to [review a flagged theme](https://addons.mozilla.org/en-US/editors/themes/flagged), I don't see the following button options on any individual theme's review page: 

- Request More Info
- Duplicate
- Reject
- Approve

... so no action can be taken. 

@atsay, @jvillalobos

**Comment by andymckay-limited-access** [comment]
I don't think you have admin rights, @jvillalobos could you check what rights Scott has please?

**Comment by jvillalobos** [comment]
He's in the Staff group, which should be sufficient.

**Comment by andymckay** [comment]
Looks it isn't, how about putting him in the reviewers group?

**Comment by jvillalobos** [comment]
The Staff group has all the permissions that the reviewer groups have. Also, I can reproduce this bug using my account.

**Comment by andymckay-limited-access** [comment]
So does that mean no-one can review a flagged theme?

**Comment by jvillalobos** [comment]
Apparently it depends on how you navigate the queues.

STR:
1. Go to [flagged queue page](https://addons.mozilla.org/editors/themes/flagged).
2. Click on any of the themes in that queue.

Result:
This takes you to the usual review page for a theme ([for example](https://addons.mozilla.org/editors/themes/queue/single/anime-34)). This page doesn't have the buttons, as this issue states.

_However_, if you go to the [interactive queue page](https://addons.mozilla.org/editors/themes/queue/flagged), then the buttons are there.
