### ISSUE TITLE
Hovering over an incompatible add-on moves the installation button

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2366]
Relates to #2289 

Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Hover over an incompatible add-on https://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/?sort=popular (i.e Evernote Web Clipper)
3. Repeat and observe the button

Expected results:
There are no display or layout issues.

Actual results:
The add-on is flickering and the "+Add to Firefox" button is changing its position.

Notes/Issues:
Verified on AMO-dev FF45(Win 7).
Screenshots for this issue: 
![no-hover](https://cloud.githubusercontent.com/assets/15685960/14524246/1e165c68-0240-11e6-8f17-d30e8d6ab29b.png)
![hover](https://cloud.githubusercontent.com/assets/15685960/14524251/22c13792-0240-11e6-9448-5c3b65e2add8.png)

**Comment by ValentinaPC** [comment]
@tofumatt : This is how is supposed to work: http://screencast.com/t/2CgKFiBSb4bP ?
Thanks!

**Comment by tofumatt** [comment]
@ValentinaPC Yes, that's right.

**Comment by ValentinaPC** [comment]
Based on above comment I'll mark this fixed.
Postfix screencast: https://gyazo.com/c5ecbb8ae7b4d5590b1b75642cda0531

**Comment by ValentinaPC** [comment]
https://i.gyazo.com/c5ecbb8ae7b4d5590b1b75642cda0531.mp4

**Comment by ValentinaPC** [comment]
Sorry but I cannot agree :(
I have troubles accessing add-on details page (very disturbing), for an incompatible add-on, because of that flickering.
Please see the screencast: http://screencast.com/t/VzqYomANcI

**Comment by ValentinaPC** [comment]
Due to #3203 fix, I'll also mark this verified-fix.
