### ISSUE TITLE
The main Add-ons Manager page is not automatically displayed after logout

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#2367]
**Steps to reproduce**
1. Login to https://addons.mozilla.org/en-US/
2. Navigate to about:addons
3. Click “Log out” link from the top right corner.

**Expected results**
The main Addons Manager page is automatically displayed.

**Actual results**
“What are Add-ons?” section is displayed, and the “Get Add-ons” page appears only after a refresh.

**Additional notes:**
- This issue reproduces on AMO-production using Firefox 45.0.2 under Windows 10 64-bit.
- Please see the screencast for this issue: http://screencast.com/t/4LziXbkSpKAh

**Comment by andymckay-limited-access** [comment]
Since we are replacing this whole functionality with the new disco pane in Firefox 48, I don't think this is worth worrying about. The new disco pane has no login/logout functionality.
