### ISSUE TITLE
“Version Information” is not collapsing correctly for unreviewed add-ons

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2368]
Steps to reproduce:

1.Open this firefox add-ons page: https://addons.allizom.org/en-US/firefox/addon/szmalback/?src=search
3.After the page is loaded scroll down to “Version Information”.
4.Click on the arrows from “Version Information” few times.

Expected results:
“Version Information” collapses correctly.

Actual results:
“Version Information” does not collapses correctly.

Note/Issues:
This this bug is reproducible if the addon doesn't have "Part of these Collections" and "Other add-ons by these authors".
This issue is reproducing in AMO-stage and AMO-dev.
Video of this issue: http://screencast.com/t/ujZsRmmT

**Comment by tofumatt** [comment]
Tested this locally and found it only occurs for add-ons requiring review/full review.

**Comment by cosminbadescuSV** [comment]
This isssue is not reproducing anymore, see the video:http://screencast.com/t/J5ewnHF9Yq7N
