### ISSUE TITLE
[AMO-dev] white background for promo-banner

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2373]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Observe the promo banner

Expected results:
The banner is on blue background.

Actual results:
The banner is on white background making it hard to read.

Notes/issues:
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue: 
![2016-04-14_1455](https://cloud.githubusercontent.com/assets/15685960/14527277/7f13343a-0251-11e6-85c5-3b7c49959ab3.png)

**Comment by tofumatt** [comment]
Regression from #2369.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-14_1637](https://cloud.githubusercontent.com/assets/15685960/14529906/4f3e2734-025f-11e6-809c-568ebf57e6db.png)
