### ISSUE TITLE
No padding between "Developer's comment" and "Version information" sections in addons details pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2376]
Prerequisites : Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to an addon details page which have Developer's comments and Version information sections(https://addons-dev.allizom.org/en-US/firefox/addon/video-downloadhelper/?src=hp-dl-mostpopular)
2.Observe the  "Developer's comment" and "Version information" sections

Expected results:
There is a padding between these sections

Actual results:
No padding

Please see screenshot for this bug : 
![commvers](https://cloud.githubusercontent.com/assets/1583842/14529614/0abf54c6-025e-11e6-837a-7d8819506687.png)

**Comment by andymckay** [comment]
This looks good to me if there's spacing or not.
