### ISSUE TITLE
UI issues in search tools

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2379]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/android/search-tools/

Expected reasults:
The page is displayed without any layout issues

Actual results:
All buttons, descriptions, reviews, etc are not correctly aligned in addon's frames

Please see screenshot for this bug :
![search](https://cloud.githubusercontent.com/assets/1583842/14533524/11395490-026e-11e6-9d6f-bbf968d318b2.png)

NOTES:
Page is also not style refreshed, but this is addressed in #2199

**Comment by vcarciu** [comment]
Also , please note that this is looking bad on -dev. On Stage even the page is not style refreshed, UI looks good.

**Comment by tofumatt** [comment]
Is this happening on stage? If so we'll need to get this a blocks-release tag and cherry-pick the fix. Fortunately it's an easy one.

**Comment by vcarciu** [comment]
Verified as fixed : 
![srchtools](https://cloud.githubusercontent.com/assets/1583842/14565239/c3d22e32-0332-11e6-810a-cae49d0e81a6.png)
