### ISSUE TITLE
Menu splitter plays "hide-and-seek"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2380]
Steps to reproduce:
1. Load AMO-stage homepage https://addons.allizom.org/en-US/firefox/
2. Decrease / Increase page font size

Expected results:
The are no display or layout issues.

Actual results:
The menu "splitter" is hiding.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO0stage, dev and prod.
Please see the screencast: http://screencast.com/t/6SJ5VF6VQc

**Comment by muffinresearch** [comment]
Not reproducible on OSX. This is such a minor problem I think it's OK to wontfix this.

If anyone feels strongly otherwise then please feel free to reopen it.
