### ISSUE TITLE
Too many TODOs

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#2383]
Over the years the amo codebase has accumulated 80+ `# TODO` comments.  We should either DO\* those still appropriate to do; or accept the truth that they're never going to be done so remove the comment and/or commented-out code.
- If they're non-trivial they could be split out into separate issues; potentially good-first-bugs

**Comment by andymckay** [comment]
I imagine 95% of them just need to be removed. And add a travis check to stop anymore being added :)
