### ISSUE TITLE
Some links are invisible in "puzzle piece" listings

### ISSUE THREAD

**Issue by Quicksaver** [mozilla/addons-server#2384]
Nuff said.

![inivisblelinks](https://cloud.githubusercontent.com/assets/802086/14541082/1e9de382-0280-11e6-8a00-5b9cd6b78caf.jpg)

**Comment by tofumatt** [comment]
In the future, can you include a link to the page where it's happening? I can find this one, it's okay, but just helps in the future.

Also: obrigado for your awesome Tab Groups add-on, you rock :smile:

**Comment by Quicksaver** [comment]
It's not just the category, it's also the reviews link, the one that list how many reviews it has. I don't think that commit fixes that one.

It happens on every single add-on page I've seen, like [Tab Groups](https://addons.mozilla.org/firefox/addon/tab-groups-panorama/), so I didn't think a link was necessary. :) And you're very welcome, I'm glad you like it.

**Comment by jvillalobos** [comment]
Reopening based on last comment.

**Comment by tofumatt** [comment]
Oh shoot, you're right. Okay, will look again and fix. Thanks!

- tofumatt

**Comment by tofumatt** [comment]
I don't see any links that are hidden now. Can you screenshot another instance? The reviews sections looked like this for me:

<img width="1004" alt="screenshot 2016-04-15 17 49 10" src="https://cloud.githubusercontent.com/assets/90871/14568690/600b2e9e-0332-11e6-826b-9c96eed2663b.png">

**Comment by Quicksaver** [comment]
@tofumatt it's not there, it's in the same area as the category links. The page still looks the same for me as in the original screenshot I posted (as it's not yet been pushed live I'm sure). Note I circled two areas in the screenshot, the category just under the add-on name which should be fixed by the commit, and the ```(98)``` just after the stars rating.

**Comment by Quicksaver** [comment]
I just checked the dev environment, the category is indeed visible, but the review count isn't: https://addons-dev.allizom.org/firefox/addon/findbar-tweak/

![reviewcount](https://cloud.githubusercontent.com/assets/802086/14569257/7b16e356-0335-11e6-8cc0-c5d775f7cb88.jpg)

**Comment by tofumatt** [comment]
Ah, sweet, thanks for the screenshot, I didn't notice them!

Fix incoming in a few 😄

**Comment by Quicksaver** [comment]
Looks great. :)
