### ISSUE TITLE
New Style wastes page width

### ISSUE THREAD

**Issue by RainerBielefeld** [mozilla/addons-server#2390]
Today most people have widescreen monitors, on which an add-on-download page looks as shown in the screenshot. 1/3 of page width is empty, but "63 Benutzerbewertungen" needs a line break? This needs improvement.
![pagewidth-screenshot](https://cloud.githubusercontent.com/assets/11803749/14552784/5123f40c-02e1-11e6-8958-468d4bf92d55.png)

----------

BTW, this Github Toy Issue Tracker is a real nuisance (does not support PDF attachments (although listed)? Good grief!)  and a great way to prevent users form contributing ideas or reporting bugs. You should use a real bug tracker for tracking AMO bugs.

**Comment by muffinresearch** [comment]
@RainerBielefeld thanks for the feedback. Right now this style update is just a refresh so bigger changes to the layout are not in-scope. However, your comments around making more use of the width will be looked at in the future when we do a more complete overhaul of the front-end.

Re: github issues I agree they have some limitations - but the team finds that having issues closer to the code outweighs the lack of more advanced features of other trackers. There are trade-offs in whatever solution is chosen but this is working for us right now. For cases where something can't be uploaded linking should suffice as a workaround.

**Comment by RainerBielefeld** [comment]
Yes, I see, this area here is quite close to the code and far away from the "customers", I won't come along again.
