### ISSUE TITLE
"View Recent Changes" page is not style-refreshed and looks weird

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2391]
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Go to My Submission page https://addons-dev.allizom.org/en-US/developers/addons
3. Click on "View Recent Changes" link from "More" 
4. Observe the page

Expected results:
The page is style refreshed.

Actual results:
The page is not style refreshed and if the users has many add-ons looks weird.

Notes/Issue:
Verified on AMO-dev FF45(Win 7). Reproducing on stage, dev and prod.
Screenshots for this issue:
1: 
![1](https://cloud.githubusercontent.com/assets/15685960/14554934/816bbe26-02f8-11e6-83e8-605987bfaa47.png)
2:
![2](https://cloud.githubusercontent.com/assets/15685960/14554944/86a13a7e-02f8-11e6-9752-d1cf09f8d521.png)

**Comment by andymckay** [comment]
This seems acceptable to me.
