### ISSUE TITLE
CSS console error at search

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2392]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Open the console
3. Make a search (i.e "free")

Expected results:
There are no errors in the console.

Actual results:
There is a CSS error in the console.

Notes/Issues:
Issue can be see in homepage too:
![2016-04-15_1111](https://cloud.githubusercontent.com/assets/15685960/14555373/df5d8e7c-02fa-11e6-95bc-78a9e8a33a9e.png)
 
Reproducing in AMO-dev, stage and prod.
Screenshot for this issue:
![2016-04-15_1109](https://cloud.githubusercontent.com/assets/15685960/14555332/9b79dcba-02fa-11e6-8e72-4301ff9983ab.png)

**Comment by muffinresearch** [comment]
These can be ignored there's nothing we can do about this. See this bug for context https://bugzilla.mozilla.org/show_bug.cgi?id=1185685
