### ISSUE TITLE
[RTL] Manage button has display issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2394]
Steps to reproduce:
1. Load AMO-dev page
2. Go to Other Languages drop-down and pick a RTL language i.e. https://addons-dev.allizom.org/he/firefox/
3. Go to any add-on details page https://addons-dev.allizom.org/he/firefox/addon/facebook-phishing-protector/?src=hp-dl-featured
4. Observe the Manage red button

Expected results:
There are no display or layout issues.

Actual results:
The "Manage" red button has display issues.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot for this issue: 
![2016-04-15_1128](https://cloud.githubusercontent.com/assets/15685960/14555832/777dabcc-02fd-11e6-9194-75094deeb580.png)

**Comment by eviljeff** [comment]
mentor @tofumatt 
Can you add steps to get started?

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2 (Win 7)
Postfix screenshot: 
![manage](https://cloud.githubusercontent.com/assets/15685960/18578493/eed3b8f0-7bf8-11e6-8990-8d7cdf737c93.png)
