### ISSUE TITLE
[RTL] Other Languages drop-down has display issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2395]
Steps to reproduce:
1. Load AMO-dev page
2. Go to Other Languages drop-down and pick a RTL language i.e. https://addons-dev.allizom.org/he/firefox/
3. Observe the Other Languages drop-down

Expected results:
There are no display or layout issues.

Actual results:
The "Other Languages" drop-down has display issues.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot for this issue: 
![2016-04-15_1133](https://cloud.githubusercontent.com/assets/15685960/14555962/4f5083f8-02fe-11e6-9e36-d9b822ed5034.png)

**Comment by eviljeff** [comment]
See [our contributing document](https://github.com/mozilla/addons-server/blob/master/CONTRIBUTING.rst)
mentor @tofumatt

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2(Win 7)
Postfix screenshot: 
![otherlang](https://cloud.githubusercontent.com/assets/15685960/18578766/71ae3d12-7bfa-11e6-84a2-ae5c7decfd8f.png)
