### ISSUE TITLE
[RTL] The "+" from the intall button has display issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2396]
Steps to reproduce:
1. Load AMO-dev page
2. Go to Other Languages drop-down and pick a RTL language i.e. https://addons-dev.allizom.org/he/firefox/
3. Go to any add-on details page https://addons-dev.allizom.org/he/firefox/addon/facebook-phishing-protector/?src=hp-dl-featured
4. Observe the "+" from the install button 

Expected results:
There are no display or layout issues.

Actual results:
The "+" from the install button has display issues.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot for this issue: 
![2016-04-15_1140](https://cloud.githubusercontent.com/assets/15685960/14556183/8041afc2-02ff-11e6-99d2-3fd2532378fd.png)

**Comment by atiqueahmedziad** [comment]
@ValentinaPC Will you please tell what's wrong with the + sign? 
![button](https://cloud.githubusercontent.com/assets/8364578/18508186/ff131d24-7a94-11e6-9817-6b05eef88b57.png)

**Comment by ValentinaPC** [comment]
I think I thought that it should be on the other side of the text.
Sorry for the inconvenience if I am wrong.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF48.0.2(Win 7)
The "+" from the normal add-ons it is now in the right place.
Postfix screenshot: 
![normal](https://cloud.githubusercontent.com/assets/15685960/18578592/8c0685e4-7bf9-11e6-8245-ebf359f7e06e.png)

But, the "+" from the experimental add-ons is causing display issues :smile: 
Please see the screenshot: 
![experimental](https://cloud.githubusercontent.com/assets/15685960/18578623/bc5032d6-7bf9-11e6-85db-cfffb9924785.png)

@atiqueahmedziad : I'll reopen this bug, but if you think we need to log another, let me know.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2(Win 7)
Postfix screenshot: 
![exp](https://cloud.githubusercontent.com/assets/15685960/18670237/9426a172-7f47-11e6-92dd-3a6e983cd610.png)
