### ISSUE TITLE
[RTL] Menu drop-down boxes have display issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2397]
Steps to reproduce:
1. Load AMO-dev page
2. Go to "Other Languages" drop-down and pick a RTL language i.e. https://addons-dev.allizom.org/he/firefox/
3. Hover over any menu option

Expected results:
There are no display or layout issues.

Actual results:
The drop-down boxes have display issues

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot for this issue: 
![2016-04-15_1201](https://cloud.githubusercontent.com/assets/15685960/14556706/32f58d44-0302-11e6-8327-91a732ee307b.png)

**Comment by eviljeff** [comment]
mentor @tofumatt 
Can you add steps to get started?

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by tofumatt** [comment]
Fixed in #3499.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2(Win 7 x64)
Postfix video: 
![indic](https://cloud.githubusercontent.com/assets/15685960/18502994/454d2dca-7a63-11e6-9c13-66bc0f4886c1.gif)
