### ISSUE TITLE
[RTL] Scroll bar in themes categories

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2398]
Steps to reproduce:
1. Load AMO-dev page
2. Go to Other Languages drop-down and pick a RTL language i.e. https://addons-dev.allizom.org/he/firefox/
3. Click on Themes option from the menu
4. Hover over any theme from "Recently Added/Most Popular/Top Rated"

Expected results:
There are no display or layout issues.

Actual results:
A scroll bar appears.

Notes/Issues:
Also the theme button has display issues.
Verified on FF45(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot for this issue: 
![2016-04-15_1159](https://cloud.githubusercontent.com/assets/15685960/14556967/877e7866-0303-11e6-8cc4-8b85eb724e83.png)

**Comment by tofumatt** [comment]
Seems fixed now.

**Comment by ValentinaPC** [comment]
Seems, but is not. :smile: 
Verified on AMO-dev FF46(Win 7).
Please load the next page: https://addons-dev.allizom.org/he/firefox/themes/seasonal
and hover over any theme listed in "Recently Added/Most Popular/Top Rated"
Screenshot: 
![2016-05-11_1308](https://cloud.githubusercontent.com/assets/15685960/15177583/79fafb4e-1779-11e6-813c-40a4064cbcb2.png)

**Comment by wagnerand** [comment]
Mentor: @tofumatt 

Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by ValentinaPC** [comment]
@atiqueahmedziad : I saw you are handling very nice (an quickly) the RTL issues and this looks very awkward in AMO production. Thanks!

**Comment by atiqueahmedziad** [comment]
@ValentinaPC Thanks for the complement 😁

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7)
Postfix screenshot: 
![scrollbar](https://cloud.githubusercontent.com/assets/15685960/18304928/da1d1468-74ed-11e6-84d1-1c83ad3be6f8.png)
