### ISSUE TITLE
Reset password message page for an unmigrated account is not style-refreshed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2399]
Steps to reproduce:
1. Click on the Register/Login link from header in AMO-dev 
2. Click the "I forgot my password." link from the right side of the page 
3. Enter a valid e-mail for a unmigrated account
4. Click the "Send password reset link" button
5. Observe the reset message section 

Expected results:
The section is style-refreshed.

Actual results:
The section is not style-refreshed.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot for this issue: 
![2016-04-15_1234](https://cloud.githubusercontent.com/assets/15685960/14557858/0df60e3c-0308-11e6-807b-aa6e307e2aaf.png)

**Comment by andymckay** [comment]
Given that this is going to be removed in the FxA update and the amount of traffic this gets and the fact that its functional, closing.
