### ISSUE TITLE
Add more padding between featured themes rows in AMO homepage

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2400]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/
2.Hover over second row of featured themes

Expected results:
There is more padding between the two rows of featured themes

Actual results:
Not enough padding

Please see video for this bug : http://screencast.com/t/D6OwVmmT3

**Comment by andymckay-limited-access** [comment]
Its an overlay, I don't think this is a problem.
