### ISSUE TITLE
[Thunderbird] "+ Download now" is not displayed for any add-on

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#2406]
**Steps to reproduce**
1. Navigate to https://addons.mozilla.org/en-US/thunderbird/
2. Hover over any extension.

**Expected Results**
”+ Download now” button is displayed .

**Actual Results**
”+ Download now” button is not displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 45.0.2 under Windows 10 64-bit.
- Please see the screenshot for this issue: 
![pic001](https://cloud.githubusercontent.com/assets/18114210/14563939/fc4bfa46-032c-11e6-8804-c8288927e102.jpg)

**Comment by muffinresearch** [comment]
Current impact is that installation requires clicking through to the add-on.

**Comment by tofumatt** [comment]
Remove `.thunderbird .listing-grid .install-shell { display: none; }`

**Comment by vasilicamihasca** [comment]
Verified as fixed on Amo-dev using  Firefox 49.0a1 under Windows 10 64-bit. 
“+Download now” button is successfully displayed.
Postfix screenshots:
![vav](https://cloud.githubusercontent.com/assets/18114210/15220728/351ce764-1871-11e6-81e3-80e898243c68.jpg)
