### ISSUE TITLE
Menu dropmarkers are missing

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#2407]
Title.

Without dropmarkers it's impossible to determine whether or not a link (ie: username or Other Applications in the header) is a menu without hovering it.

**Comment by muffinresearch** [comment]
Before the redesign:

<img width="63" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14565653/06fb2484-0324-11e6-9cf3-327cddfc152a.png">

Post refresh:

<img width="78" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/14565679/1dbc98a6-0324-11e6-8d30-ab67fc6220b1.png">

**Comment by andymckay** [comment]
By design cc @designakt
