### ISSUE TITLE
Ui issues with "Install anyway" pop-up

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2409]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/extensions/?sort=hotness
2.Find an addon which is not compatible with your version of Firefox 
3.Press the "Add to FIrefox" grey button
4.Observe the "Install anyway " popup after moving the mouse outside of popup

Expected results:
Background remains solid, no UI issues

Actual results:
Background is transparent after moving the mouse and it looks weird

Please see video for this bug: http://screencast.com/t/rEaUg6vIq

NOTES:
Not reproducible on Stage

**Comment by muffinresearch** [comment]
<img width="520" alt="fullscreen_15_04_2016__20_32" src="https://cloud.githubusercontent.com/assets/1514/14572881/588d4596-0349-11e6-8d73-dec97338863a.png">

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/Iz6b7s5uzb
