### ISSUE TITLE
Signing seems to still be broken

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#2412]
Here are some tweets, with screen shot: https://twitter.com/AkkumaRyuujin/status/720978850453262336
This was tweeted 6 hrs ago: https://twitter.com/AkkumaRyuujin/status/721005328788234240

Not sure if it's the same issue as this, which was tweeted 12 hours ago: https://twitter.com/fgbjr/status/720939227479875584

**Comment by andymckay** [comment]
We aren't seeing any errors around signing and we'll need more details to be able to proceed.

**Comment by andymckay** [comment]
(and this has nothing to do with signing)

**Comment by andymckay** [comment]
No updates from the person tweeting, no errors recorded on our end. Going to call this fixed unless someone can provide more detail.
