### ISSUE TITLE
Needs more line-height of complete theme name

### ISSUE THREAD

**Issue by magicp-github** [mozilla/addons-server#2413]
https://addons.mozilla.org/en-US/firefox/complete-themes/

**Comment by ValentinaPC** [comment]
Hello @magicp-github ! Are you referring  to this issue: https://github.com/mozilla/addons-server/issues/2166 ?

**Comment by magicp-github** [comment]
Hi ValentinaPC ! It's same issue. Thanks :)

**Comment by madalincm** [comment]
Duplicate of #2166
