### ISSUE TITLE
Moderated Reviews Count has been wrong for a long time

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#2414]
As per title...
In the past, although the count was wrong, it would reset (to zero) if all were deleted however the recent version no longer does that either.

eg:
Moderated Reviews (5) ... However, there aren't any.

**Comment by jvillalobos** [comment]
I would bet that the count is including add-ons that have since been deleted or moved to unlisted.

**Comment by wagnerand** [comment]
This is about moderated user reviews.

STR:
1. Say there are 12 pending user reviews to be moderated.
2. You clear 8 of them.
3. After you hit `Submit`, the count in the header will still be 12.
4. Refresh the page, it will correctly show 4.

**Comment by erosman** [comment]
After processing 3, it says there are 10 but only 2 are displayed.
After refreshing a FEW times.. it now says there are 7 but only 2 are displayed.

**Comment by Noitidart** [comment]
I confirm I only see 2 reviews but tab shows 7:

![](http://i.imgur.com/oHGI1Vo.png)

**Comment by erosman** [comment]
STR... that is incorrect
I cleared one Moderated Review 12+ minutes ago and it still hasnt changed.
I have noticed much longer gap times and the count was NEVER updated properly.

**Comment by jvillalobos** [comment]
> This is about moderated user reviews.

I know. For the entire day it looks like it's had 5 reviews more in the count than in the queue (which is currently empty). My suspicion is that the list filters out add-ons that are unlisted or have some other special condition, while the counter doesn't.

**Comment by erosman** [comment]
It has been a while that count discrepancy has been increased form 5 to 11

**Comment by diox** [comment]
> My suspicion is that the list filters out add-ons that are unlisted or have some other special condition, while the counter doesn't.

That's correct. The list filters out reviewed attached to unlisted versions but more importantly, filters out add-ons that do not have a valid status (add-ons that have been rejected or are incomplete are therefore excluded). The count does not filter anything atm.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF50(Win 7).
After deleting some of the moderated reviews the count is not changed. After waintig for a min or so and refresh the page - things look better. Same happens after adding a new moderated review.
This is how it should behave? Thanks!

**Comment by diox** [comment]
That's a caching invalidation issue which is a different problem - the count (as many others on the site) lags behind for a few minutes.

**Comment by ValentinaPC** [comment]
Ok. While asking if is the correct behavior I have had in mind @wagnerand 's STRs from above.
If you say this is ok, I'll mark this verified-fixed.
Postfix screenshots:
![before](https://cloud.githubusercontent.com/assets/15685960/22063350/ff98d4fa-dd86-11e6-99d8-ef5821d8c2cc.png)
![2017-01-18_1403](https://cloud.githubusercontent.com/assets/15685960/22063357/064e389e-dd87-11e6-9245-3b2d241bb3be.png)

**Comment by erosman** [comment]
There is a note that is worth considering.

The review count counts the number of reports (automatically or manually).

There are occasions where an item has been reported more than once eg: auto-reported for URL and manually reported for spam. 

When that item is removed, it is possible !!? that the count is reduced by 1 and that is where the discrepancy occurs.

**Comment by diox** [comment]
With my changes, the count will use the exact same query used by the list, so, excluding the lag caused by cache invalidation, there shouldn't be any discrepancy any more.
