### ISSUE TITLE
Please add dsb and hsb to AMO pages

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#2416]
Hi,

please add dsb (Lower Sorbian) and hsb (Upper Sorbian) to the AMO pages. AMO is translated on Pootle into dsb and hsb now.

Thanks.

Michael Wolf

**Comment by milupo** [comment]
Sorry, they are translated on **Pontoon**, not on Pootle.

**Comment by milupo** [comment]
Additional information: I don't know what source you have for language names. To be on the safe side, here they are:

Upper Sorbian - Hornjoserbšćina
Lower Sorbian - Dolnoserbšćina

**Comment by milupo** [comment]
You closed the bug but the Sorbian languages are not available on AMO yet.

**Comment by andymckay** [comment]
You will need to wait for the next deployment schedule. It's normally on Thursdays.

**Comment by milupo** [comment]
OK. Thank you.

**Comment by andymckay** [comment]
@EnTeQuAk do we have to update AMO_LANGUAGES or locales as well? https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L123 I could be looking in the wrong place, but I don't see them either.

**Comment by EnTeQuAk** [comment]
yeah, we do. I didn't get around to test what we actually need, with a bit of luck `AMO_LANGUAGES` should be it. will look at this asap.

**Comment by milupo** [comment]
When will the Sorbian locales be added? I opened this issue more than a month ago but you didn't add it yet.

**Comment by andymckay** [comment]
Please understand @milupo that people are busy and this isn't a huge priority for the team when other more urgent bugs exist. Thanks for your patience, we'll get there.

**Comment by milupo** [comment]
I understand that but 93% of hsb strings are already translated and I'd like to check my translations on the staging server.

**Comment by milupo** [comment]
@EnTeQuAk : Though it is not my problem, according to your response to my comment from 23 Apr above nn-NO (Nynorsk) should added as well.

**Comment by EnTeQuAk** [comment]
thanks for the hint @milupo, added that to the pull request too.

**Comment by EnTeQuAk** [comment]
It should be visible on dev (https://addons-dev.allizom.org/en-US/firefox/) in the language switcher shortly now that the pull request is merged. Please feel free to reopen or report any further issues.

**Comment by andymckay** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/333931/

UnknownLocaleError: unknown locale 'hsb'

**Comment by EnTeQuAk** [comment]
oh man, opened https://github.com/mozilla/addons-server/pull/2750 for that

**Comment by milupo** [comment]
Nevertheless, thank you very much, all four languages are shown in the language switcher. For hsb I can say that translated strings are displayed as well (but categories are not shown translated). For dsb djangojs is translated only until now - all strings on the home page are still displayed in English. I started translate the django file with the strings on the home page but they have to be committed first.

**Comment by milupo** [comment]
A question: What's the difference between addons.dev-allizom.org and addons.allizom.org? Only the former URL shows the new languages, the latter not.

**Comment by milupo** [comment]
Wow! The Lower Sorbian strings are already displayed!

**Comment by EnTeQuAk** [comment]
@milupo addons.dev-allizom.org is our development server which get's all updates that land on `master` immediately (a few minutes after things land on master), addons.allizom.org is our staging server which will get updates every Tuesday where we tag a new release, push that to stage and deploy to production on Thursday.

That's why you only see the changes on -dev since they're not yet in the tag (but will be next Tuesday)

**Comment by EnTeQuAk** [comment]
Closing this again since #2750 is merged and `dsb` and `hsb` should be working on -dev now too (or will be in a few minutes).

**Comment by milupo** [comment]
Thank you for all once more. It's fine, the AMO home page is completely displayed now!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshots:
![dsb](https://cloud.githubusercontent.com/assets/15685960/15566324/ec2def68-2328-11e6-95ff-0b0ccc13c14b.png)
![hsb](https://cloud.githubusercontent.com/assets/15685960/15566330/f234a582-2328-11e6-95af-9d025cd12122.png)
