### ISSUE TITLE
Stats page breaks for other languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2419]
Steps to reproduce:
1. Load Stats Dash for an add-on with public statistics in AMO-dev
2. Change the language to Deutsch (i.e. https://addons-dev.allizom.org/de/firefox/addon/tab-mix-plus/statistics/ )

Expected results:
There are no display or layout issues.

Actual results:
The page breaks. 

Notes/issues:
I guess this happens because of a too small space between left menu and displayed chart.
Issue is reproducing for other languages too.
Verified on FF45(Win 7). Issue is reproducing on AMO-dev, stage and production.
Screenshot for this issue: 
![de](https://cloud.githubusercontent.com/assets/15685960/14595885/57da13f0-054b-11e6-9e29-3c688c2529c8.png)

**Comment by ValentinaPC** [comment]
This looks bad for AMO prod. :(
Please see the screenshot: 
![stats](https://cloud.githubusercontent.com/assets/15685960/17884336/6e88b712-6920-11e6-9302-358fd47475a3.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50.1(Win 7).
Postfix screenshot: 
![fr1](https://cloud.githubusercontent.com/assets/15685960/21853405/a58ecdfa-d81f-11e6-93d9-18b3476664c4.png)

@muffinresearch Should we reopen this, to fix it for RTL locales, also, or log another?
![rtl](https://cloud.githubusercontent.com/assets/15685960/21853446/d6c16e1e-d81f-11e6-85ed-20eee5c6e43f.png)

**Comment by muffinresearch** [comment]
@ValentinaPC good catch - can you file a new bug and I'll take a look.
