### ISSUE TITLE
Update ReCaptcha CSP config

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2421]
Since recaptcha's CSP config [1]  has been updated we can remove the unecessary hosts.

[1] https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website-how-can-i-configure-it-to-work-with-recaptcha

**Comment by muffinresearch** [comment]
QA Notes: Testing this will be a case of making sure unauthenticated abuse reports work as expected since that's the only place left using the captcha afaik.

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/htUQTp7hjMo
