### ISSUE TITLE
[Android][Seamonkey] Different styles for install button

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#2423]
https://github.com/mozilla/addons-server/pull/2359 

**Steps to reproduce**
1.Navigate to https://addons.mozilla.org/en-us/android/addon/adblock-plus/?src=cb-dl-users
2.Check the “Other add-ons by …” section.

**Expected Results**
There is only one install button style applied for all extensions.

**Actual Results**
There are 2 different sizes for “+ Add to firefox” button.

**Additional notes:**
- This issue reproduces on AMO-stage and AMO-production using Firefox 48.0a1 (2016-04-17) under Windows 10 64-bit.
- The new button style is always displayed for an add-on from “This add-on requires the following add-ons to work properly”. Screenshot:
  ![2016-04-18_1514](https://cloud.githubusercontent.com/assets/18114210/14603765/4eff7f4a-0578-11e6-9bb4-5d824bdaff74.png)
- The "Big" buttons can also be seen in add-ons categories when hovering over add-ons from "Most Popular", "Top Rated" and "Recently Added" sections. Screenshot:
  ![vs](https://cloud.githubusercontent.com/assets/18114210/14603774/5f3d8bfe-0578-11e6-9d30-76a85514465e.jpg)
- Please see the screenshot for this issue:
  ![aaaa](https://cloud.githubusercontent.com/assets/18114210/14603792/7a5e90ea-0578-11e6-830d-2af4592804bb.jpg)

**Comment by vasilicamihasca** [comment]
This issue is also reproducible for Thunderbird add-ons, since #2406 has been fixed. 
![bbb](https://cloud.githubusercontent.com/assets/18114210/15220926/f6708a60-1871-11e6-8db7-31ff1a743079.jpg)

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
