### ISSUE TITLE
Incompatible add-on with contribute roadblock has an "Install anyway" weird panel

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2435]
Steps to reproduce:
1. Load AMO-dev details page for an incopatible add-on with contribute roadblock i.e https://addons-dev.allizom.org/en-US/firefox/addon/zulu-spell-checker/?src=ss
2. Click "Continue to Dowmnload"
3. Click "+Add to Firefox" grey button

Expected results:
The information panel has no display issues.

Actual results:
The information panel looks weird.

Notes/Issues:
Also, the install anyway label is underlined (is not if there are no contribution roadblock).
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue: 
![2016-04-19_1617](https://cloud.githubusercontent.com/assets/15685960/14643340/babf92d6-0656-11e6-8742-4c174d33a0f1.png)

**Comment by eviljeff** [comment]
mentor @tofumatt 
can you add some steps to get started on this issue?

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by harikishen** [comment]
I would like to work on this issue.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
