### ISSUE TITLE
Remove hidden add-ons from HTML on front page islands

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#2436]
After the style refresh, the various add-on islands on the front page no longer include pagination, but as shown in the following image the additional sections and add-ons still exist in the HTML. We should clean this up.

![screenshot 2016-04-19 17 10 29](https://cloud.githubusercontent.com/assets/122800/14646567/d9b18276-0651-11e6-9721-7a5da79db8b5.png)

**Comment by andymckay-limited-access** [comment]
Unless this is hurting anyone, its probably not worth worrying about until we do the rewrite.
