### ISSUE TITLE
Left Pane is Needlessly wide for Search Plugins

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#2437]
As per tile, `div#files"` has a `width: 18em;` which is needlessly wide and causes unneeded wrapping on `div#content`

Example:
`https://addons.mozilla.org/en-US/firefox/files/browse/427494/`

**Comment by madalincm** [comment]
Verified as fixed in FF45(Win7) in addons-dev.allizom.org
Postfix screencast:
![content](https://cloud.githubusercontent.com/assets/15685441/14712843/7485a69c-07e7-11e6-8349-1ed5a36cdc40.png)

**Comment by erosman** [comment]
@madalincm ... the example screenshot appears to be for the wrong addon type.
You can try the example I gave in my first post :)

**Comment by madalincm** [comment]
I have rechecked this issue in production using the above link: https://addons.mozilla.org/en-US/firefox/files/browse/427494/  and this is how it looks: 
![searchtoolfilecontent](https://cloud.githubusercontent.com/assets/15685441/14775288/9c0deff8-0ac6-11e6-8105-6882dea3fa36.png)

I've might misunderstand the scope of this bug, @erosman can you please is explain if this is the desired result? Is more work needed here?

**Comment by erosman** [comment]
@madalincm 

The left pane width is fine for normal addon that have some file/folders and nested menus like the first screen that yo have posted.

Search Plugins on the other hand, have a single XML file. That is all.
reducing the left pane width will give more space to the right pane (`div#content`) and helps with word wrapping in the right pane.

I am referring to the white space on the left side of `div.diff-bar`

**Comment by madalincm** [comment]
It looks good on -dev: 
![searchdev](https://cloud.githubusercontent.com/assets/15685441/14776548/d4a80b1a-0acf-11e6-8ca3-ef4f13643302.png)

**Comment by erosman** [comment]
That is good..... That was what I was referring to.
In that case, it appears that it is fixed (will be, once the next version is up and running).
Therefore, you can close this issue.
:)
