### ISSUE TITLE
No padding under some notification banners

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2440]
**Steps to reproduce:**
1. Open account settings page: https://addons.allizom.org/en-US/firefox/users/edit
2. Perform some changes and click the "Update Account"  button.

**Expected results:**
The banner is displayed with no layout or display issues.

**Actual results:**
There is no padding under the notification banner.

**Notes/Issues:**
Verified in FF45(Win7)
Issue can be reproduced in amo-dev and amo-stage.
Screenshot for this issue:
![nopaddingbanner01](https://cloud.githubusercontent.com/assets/15685441/14670799/4a4a083c-06f7-11e6-9757-7df19c8b4927.png)

The issue is also reproducing for the Errors found banner:
![nopaddingbanner02](https://cloud.githubusercontent.com/assets/15685441/14670817/5d5ad078-06f7-11e6-9337-fc8f91dc7585.png)

Also reproducing in the submit a new theme page:
![nopaddingbanner03](https://cloud.githubusercontent.com/assets/15685441/14670833/6da396c2-06f7-11e6-926e-7b7c9c0acccc.png)

**Comment by vcarciu** [comment]
Same issue reproducible with addon deletion confirmation banner : 
![deletebanner](https://cloud.githubusercontent.com/assets/1583842/14705546/c4ba955c-07c2-11e6-866b-7897a0f72725.png)

**Comment by vcarciu** [comment]
Also for update themes confirmation banner :
![updatetheme](https://cloud.githubusercontent.com/assets/1583842/14705661/4e2f72bc-07c3-11e6-9c08-213f56fb3abf.png)

**Comment by krzysztofzuraw** [comment]
Hello, I wanted to start working on this issue. Is there anything more that I need to know to start working on this?

**Comment by wagnerand** [comment]
Sorry for the delay, this one slipped through the cracks!

Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by wagnerand** [comment]
Mentor: @tofumatt

**Comment by madalincm** [comment]
Verified in FF50(Win7) in addons-dev.allizom.org
The Issue is still reproducing
Please view the following screenshots:
![p1](https://cloud.githubusercontent.com/assets/15685441/22109258/9d195a32-de5f-11e6-9eef-a908b05fdfd6.png)
![p2](https://cloud.githubusercontent.com/assets/15685441/22109259/9d1a5a5e-de5f-11e6-8c63-12846b678649.png)
![p3](https://cloud.githubusercontent.com/assets/15685441/22109260/9d1b4680-de5f-11e6-8764-08afae58ac20.png)

**Comment by tofumatt** [comment]
I don't think this a good first bug anymore because the style for that header and the revert we needed was messy. I think I mentioned that in the past but I lost the comment.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
