### ISSUE TITLE
New review is not displayed on addons-dev for some time after submission

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#2442]
We have an [automated UI functional test](https://github.com/mozilla/Addon-Tests/blob/88d2110cf75660cb53e77a6192e76cb76049a87e/tests/desktop/test_reviews.py#L49-L75) that submits a new review for an add-on and checks that the review is displayed. This test is currently failing on https://addons-dev.allizom.org (see https://github.com/mozilla/Addon-Tests/issues/844) due to the review not appearing when expected. I believe that this test was reasonably reliable, which suggests that the review not appearing promptly is likely a regression, but we only have test results going back to February 29th so it's not possible for me to determine a regression range.

Note that the test is passing on https://addons.allizom.org and is not running on https://addons.mozilla.org due to its destructive nature.

I suspect this may be related to https://github.com/mozilla/addons-server/issues/2201 and perhaps to the issues mentioned in https://github.com/mozilla/Addon-Tests/pull/837

**Comment by jasonthomas** [comment]
Can we run this test again on -dev? I made changes to our caching instances. I believe the previous instances were causing performance issues.

**Comment by davehunt** [comment]
@jasonthomas looks like it's passing now! 👍
