### ISSUE TITLE
Theme installation button has layout issues for logged out users

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2444]
Steps to reproduce:
1. Load AMO-stage page (user must be signed out)
2. Go to Themes and hover over a theme from any category: https://addons.allizom.org/en-US/firefox/themes/causes
3. Observe the installation button

Expected results:
There are no display or layout issues.

Actual results:
The button has layout issues.

Notes/issue:
On dev there are categories (Fashion, Firefox) for which the installation button is not displayed at all: 
![2016-04-20_1622](https://cloud.githubusercontent.com/assets/15685960/14675991/38916514-0714-11e6-8cf7-27ffdb7afb78.png)

Verified on AMO-stage FF45(Win 7).
Please see the screenshot: 
![2016-04-20_1539](https://cloud.githubusercontent.com/assets/15685960/14676035/609f3a2c-0714-11e6-9dfd-23f0c3efb1f2.png)

**Comment by andymckay-limited-access** [comment]
I can't reproduce on either server, looks like something else fixed it.

**Comment by andymckay-limited-access** [comment]
On stage, under categories I see a double plus, but only when under a category.

**Comment by tofumatt** [comment]
@andymckay-limited-access @andymckay Can you give me a link or screenshot where you're seeing that? I can't reproduce it.

**Comment by andymckay** [comment]
At a category, eg: https://addons.allizom.org/en-US/firefox/themes/film-and-tv, but ONLY when you are logged out. Which is wierd.

<img width="542" alt="screenshot 2016-04-20 16 56 14" src="https://cloud.githubusercontent.com/assets/74699/14693954/dcfdeea2-0718-11e6-816f-7d0754c4ba17.png">

**Comment by ValentinaPC** [comment]
I mentioned at step #2, that you have to be in a category....and provided a link for it.

**Comment by tofumatt** [comment]
Sorry, I was signed in and forgot this is only for anonymous users.

**Comment by tofumatt** [comment]
Figured it out, the HTML is bizarrely different for signed-out users. Fix incoming.

**Comment by tofumatt** [comment]
This seems to be a very strange... caching issue? The HTML on the theme category pages on stage are quite outdated-looking and have HTML that isn't even in the source repo anymore.

Can we clear memcache or whatever is needed to reset this? I can't reproduce this at all locally and the HTML on -dev and -prod are totally different.

Both screenshots as an anonymous user in a new profile on Nightly, -dev and -prod:

<img width="776" alt="screenshot 2016-04-21 15 28 59" src="https://cloud.githubusercontent.com/assets/90871/14712635/dce8188a-07d5-11e6-8127-3a8e4a196c77.png">

-----

<img width="765" alt="screenshot 2016-04-21 15 29 07" src="https://cloud.githubusercontent.com/assets/90871/14712640/e2e168cc-07d5-11e6-8ce4-9d15881d1c05.png">

**Comment by tofumatt** [comment]
@jasonthomas flushed the caches on stage and that fixed it for me: https://www.dropbox.com/s/5e4vag21bhllmm4/Screenshot%202016-04-21%2016.51.17.png?dl=0

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage FF45(Win 7).
Postfix screenshot: 
![2016-04-21_1855](https://cloud.githubusercontent.com/assets/15685960/14715754/b802c610-07f2-11e6-98a3-5003b45e2996.png)
