### ISSUE TITLE
Restyle tooltip

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2445]
Let's restyle the tooltip as seen in https://addons.mozilla.org/en-US/developers/addon/submit/2:
![screen shot 2016-04-20 at 15 47 31](https://cloud.githubusercontent.com/assets/873258/14676802/5b1cb322-070f-11e6-89c9-b1d097aca7b8.png)

Maybe make it similar to the hover-menus in the topmost menu-bar?

Adding @pwalm

**Comment by brampitoyo** [comment]
Sounds good to me. Let’s use that style.

**Comment by tofumatt** [comment]
The current hover effect seems to work fine and I don't think this is a worthwhile fix when we are looking to close the number of style refresh bugs and will eventually replace things.

I'm going to close as won't fix.
