### ISSUE TITLE
Wrong button label for preliminary reviewed incompatible add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2446]
Steps to reproduce:
1. Sign in to AMO-stage
2. Go to details page for a preliminary reviewed incompatible add-on i.e. https://addons.allizom.org/en-US/firefox/addon/add-%E9%98%9C%E9%98%9C/ (complete theme: https://addons.allizom.org/en-US/firefox/addon/ft-deep-stage-prelim/)
3. Observe the installation button 

Expected results:
The install button is grayed out and when is clicked a pop-up with a warning and an "Install anyway" button is displayed.

Actual results:
The install button is yellow and nothing happens when clicked.

Notes/Issue:
**Only reproducible for preliminary reviewed add-ons (or complete themes).**  
**When clicked nothing happens.**  
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev (on dev the "+" has a different color i.e. https://addons-dev.allizom.org/en-US/firefox/addon/test-dev-val/).
Screenshot for this issue: 
Stage
![stage](https://cloud.githubusercontent.com/assets/15685960/14677196/3de0a516-0719-11e6-8392-0056f55d859c.png)

Dev:
![dev](https://cloud.githubusercontent.com/assets/15685960/14677200/43e7ef28-0719-11e6-903b-055b8c5eca71.png)

**Comment by vasilicamihasca** [comment]
- I’ve also noticed that “Only with Firefox — Get Firefox Now!” button doesn’t work for preliminary reviewed add-ons in Chrome. 
- This issue reproduces on AMO-dev, AMO-stage and AMO-production.
- See screencast:
![gif](https://cloud.githubusercontent.com/assets/18114210/14704550/eaa1bc78-07bd-11e6-92b6-704f667c667d.gif)

**Comment by tofumatt** [comment]
At the very least, this button should be grey.

**Comment by tofumatt** [comment]
Looking at the markup, it seems this should not be installable when not available for the user's platform. There doesn't appear to be an "install anyway" button in the markup, so I think this should just be disabled. That's what I'll implement here.

**Comment by tofumatt** [comment]
Nope, I'm wrong, at least kind of. It works on the  `FT Deep-stage-prelim 1` link but not  `add-阜阜^#$% 1 `

**Comment by ValentinaPC** [comment]
I've checked the buttons for a bunch of add-ons with different statuses and I think there is still an issue related to this.
Please see the next screenshot:
**Unavailable for your platform add-on - **no button**** 
![notavailable](https://cloud.githubusercontent.com/assets/15685960/15222307/b07582f8-1877-11e6-851c-a895b5ebd227.png)

**Comment by tofumatt** [comment]
@ValentinaPC If the add-on isn't available for the user's platform, that's the intended behaviour though, right? They can't install it, so there is no button.

**Comment by ValentinaPC** [comment]
@tofumatt : I don't know if is the actual intended behavior, but it was not like this in the past, if I recall right, it was a gray button listed.
They should be able to download it, though, even if hey can't install it, no?

**Comment by tofumatt** [comment]
I think no. If the user can't install or run the add-on, I don't think we need to provide it to them.

This behaviour seems fine to me. This seems like intended behaviour (no add-on if incompatible), so I think this works as expected.
