### ISSUE TITLE
Implement API for disco pane

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2447]
We need a v3 api endpoint for `addons-frontend` to get the list of addons for the new disco pane.

Some data that we need:

 * icon
 * some sort of slogan (see invision screen, "Block ads with ...")
 * description
 * name
 * addon-id

Do we something specific about themes?

**Comment by andymckay-limited-access** [comment]
I added some comments in #2449

**Comment by diox** [comment]
Per #2449:

* `type` (e.g. Theme or Extension)
* `heading` (This is editorial and shouldn't need HTML)
* `sub_heading` _Optional_ (This is editorial and shouldn't need HTML)
* `editorial_description` (This will contain some HTML e.g. em and strong - depending on how custom this might be - at the moment I'm putting the this in a paragraph element, but there's a possibility that might need more flexibility than that.)
* `theme_url` (theme only)
* `logo_url` (extension only)

We also need the API to allow `POST`/`PUT`/`PATCH`/`DELETE`. Fields that need to be edited are the editorial fields, the add-on id, and probably some sort of numerical field for the ordering.

**Comment by diox** [comment]
Note: we want https://github.com/mozilla/addons-server/issues/2591 to be done first.
