### ISSUE TITLE
Add admin interface to organize disco pane

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2448]
Based on #2447 we need some sort of admin interface to organize the disco pane.

**Comment by andymckay-limited-access** [comment]
Recommend that with the help of @mstriemer, this should live in the new admin pages.

**Comment by diox** [comment]
I'm thinking of building the edition API at the same time as the frontend one. It'd be built on top of our existing translation fields, allowing to fetch and edit multiple translations at the same time for each field. The admin would be very simple and could look like this:

## Disco Pane entry #421

### Add-on identifier
[text input accepting slug/id/url]

### Enabled
[x]

### Heading
String | Locale
-------|--------
[text input] | en-US
[text input]  | fr
[text input]  | de
[text input]  | es
[...]  | ...

### Sub heading (optional)
String | Locale
-------|--------
[text input] | en-US
[text input]  | fr
[text input]  | de
[text input]  | es
[...]  | ...

### Description (some HTML allowed)
String | Locale
-------|--------
[text input] | en-US
[text input]  | fr
[text input]  | de
[text input]  | es
[...]  | ...

---

or like this:

---

## Disco Pane entry #421

### Enabled
[x]

### Add-on identifier
[text input accepting slug/id/url]

[v| Locale Dropdown] | (display how many languages have translations. only english is required for saving)

### Heading
[text input]

### Sub heading (optional)
[text input]

### Description (some HTML allowed)
[text input]

**Comment by diox** [comment]
No admin for now as for the initial implementation everything is in a python file + translations. I'll keep this opened for later though.

**Comment by diox** [comment]
Latest plan is still to do this later. However, for translations, the current idea is to not have them in the admin at all. Instead, use something like [django-vinaigrette](https://github.com/ecometrica/django-vinaigrette) to generate .po files from database entries, then sync that to pontoon, then have translators work there and commit it back to the repos. With some information exposed to the admin to know the state of translations for a particular entry, allowing them to decide if it's possible to enable that item or not.

Only issue with that idea is that we'd need to do extractions more often (already planned) and find a way for those to happen with the prod database (more annoying).

**Comment by muffinresearch** [comment]
Since there are no current plans to do this , closing. We can always reopen if needed.

**Comment by diox** [comment]
Could be done as a bonus when implementing #8734. I've got a half-working prototype: https://github.com/diox/olympia/commit/bd502a38271cc7a7ca403b17813fc0854dc421ed

Still not sure if it's worth doing both at the same time, though.

**Comment by diox** [comment]
QA:
- The `position` and `position_china` fields should control what's returned in the discovery pane now. Make sure the discovery pane properly reflects what's chosen. You should be able to include static or lightweight themes as well.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64

Discovery pane content can be managed from `admin/models/discovery/discoveryitem/`:
- content for the normal and for the china_edition is updated
- the position indicated in the tool is reflected on the discovery pane
- extensions, lwt and static themes can be included 

Admin tool layout: https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/
Discopane layout:
[1] https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/61.0.2/WINNT/normal
[2] https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/61.0.2/WINNT/normal/?edition=china

@diox  I've noticed that the updates made in the Discovery tool are not immediately reflected in the discovery pane. It usually takes several minutes (20 ~30) for the changes to appear. Just wanted to check if this is expected.

**Comment by diox** [comment]
Yeah, I forgot about this, but there is some caching going on in the discovery pane, so some time for changes to appear seems ok.
