### ISSUE TITLE
Add basic database structure for disco pane

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2449]
Based on #2447 we need some database structure that represents an item in the disco pane.

It's:

 * sortable
 * should be very very fast and simple
 * separate so that we can organize it easily

**Comment by andymckay-limited-access** [comment]
There are some key elements that an element in a disco pane has that is pretty unique too.

These are definitely:
* a separate description

Maybe:
* a learn more URL link that will show in the UI tour
* an id for the button that is created so the UI tour can point to it.

**Comment by muffinresearch** [comment]
So in addition to the above - here's the fields we need so far for the visible content data (based on looking at the UX):

<img  alt="data-wireframe-disco_graffle" src="https://cloud.githubusercontent.com/assets/1514/14707537/35332cb4-07bd-11e6-89a4-fc45570e3af1.png">

* `type` (e.g. Theme or Extension)
* `heading` (This is editorial and shouldn't need HTML)
* `sub_heading` Optional (This is editorial and shouldn't need HTML)
* `editorial_description` (This will contain some HTML e.g. em and strong - depending on how custom this might be - at the moment I'm putting the this in a paragraph element, but there's a possibility that might need more flexibility than that.)
* `theme_url` (theme only)
* `logo_url` (extension only) 

Would be nice if the urls for the logos have cache-busting built in, this way if the image changes the urls handed to the app from the API should change too.

I'll look into what's needed from the installation perspective in due course. E.g. what over and above the link to the addon is required.

**Comment by muffinresearch** [comment]
We'll need the theme data as per the docs here: https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes

**Comment by diox** [comment]
Is the logo coming from the add-on automatically or is it also an editorial one ?

**Comment by andymckay** [comment]
Add-on.

**Comment by diox** [comment]
We aren't doing a database for the initial implementation. https://github.com/diox/olympia/commit/e5ae01539423359e43cf70ab040703da498defd3 covered adding the basic python module for this, and #2447 will cover the API.
