### ISSUE TITLE
make sure we determine an addon as WebExtension once there's a manifest.json

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2450]
Currently we check for `manifest.json` last which leads to some problems for addons that should be WebExtensions but still have the old metadata files.

See https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L93 for example.

To make sure a scenario like this never happens we have to change the `addons-linter` and `amo-validator` to properly raise an exception.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
An error is raised if both install.rdf and manifest.json are in the .xpi package.
Postfix screenshot:  
![submission](https://cloud.githubusercontent.com/assets/15685960/15241761/deac498a-18fa-11e6-9e46-8d0c7fce88c3.png)
