### ISSUE TITLE
Remove package.json related code.

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2460]
`package.json` never happened.

**Comment by EnTeQuAk** [comment]
QA: This removes all parsing for a `package.json` if present in the XPI-file, except for validation via `amo-validator` - so we're validating the `package.json` (very basic validation, mostly what `jpm` already does) but aren't using it's values.

This allows a WebExtension to have a `manifest.json` and a `package.json` and AMO should use the `manifest.json` and ignore the `package.json`.

Mostly as outlined in #2564 and #2438

**Comment by ValentinaPC** [comment]
This can be marked as verified-fixed.
