### ISSUE TITLE
Provide a way to generate API credentials from the command line

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#2461]
In order to have functional UI tests running against AMO running in a Docker container, we need a way for users to login. Currently the UI tests in https://github.com/mozilla/Addon-Tests use the [super-create](https://addons-server.readthedocs.org/en/latest/topics/api/accounts.html#super-creation) API end-point to create a new user for every test that requires the ability to login. This requires a user in the `Accounts:SuperCreate` group, and a JWT issuer and secret for this user.

When running against deployed instances we store these credentials in a JSON file, however when running against AMO running in a Docker container, we need a way to generate the user and API credentials. Rather than storing these in a file, we could read them from environment variables such as `JWT_ISSUER` and `JWT_SECRET`.

**Comment by kumar303** [comment]
I am not clear on what change are you requesting. What is the current workaround (or roadblock) to how you solve this problem? Do you have to hit the login endpoint each time before the test or something?

**Comment by davehunt** [comment]
The only workaround is to run tests against a deployed instance of AMO with a pre-existing user and known API credentials. There's currently no way (to my knowledge) of getting the API credentials without using the UI, which would be slow and potentially brittle.

**Comment by kumar303** [comment]
this will be done in https://github.com/mozilla/addons-server/issues/2593
