### ISSUE TITLE
Provide a way to create a user in the SuperCreate group from the command line

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#2462]
In order to have functional UI tests running against AMO running in a Docker container, we need a way for users to login. Currently the UI tests in https://github.com/mozilla/Addon-Tests use the [super-create](https://addons-server.readthedocs.org/en/latest/topics/api/accounts.html#super-creation) API end-point to create a new user for every test that requires the ability to login. This requires a user in the `Accounts:SuperCreate` group, and a JWT issuer and secret for this user.

When running against deployed instances we have users added to this group manually, however when running against AMO running in a Docker container, we need a way to create the user or to add an existing user to this group.

**Comment by kumar303** [comment]
> When running against deployed instances we have users added to this group manually

How often do you have to do this? My understanding was that once you created a handful of super-creators then all tests can run with those users. The only dynamic users should be the ones that you are creating *with* the super-creator.

**Comment by davehunt** [comment]
@kumar303 We just need one super-creator, but we're running the tests against an instance of the application without any pre-existing users (using Travis/Circle to clone and spin up via Docker). So we need a way to programmatically create the super-creator. For issue #2461 we need the API credentials for this super-create user.

**Comment by kumar303** [comment]
this will be done in https://github.com/mozilla/addons-server/issues/2593
