### ISSUE TITLE
Collections containing only themes have 2 types of display

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2463]
Steps to reproduce:
1. Load AMO-stage page for a created collection i.e. https://addons.allizom.org/en-US/firefox/collections/ValStage/new-on/
2. Click the "Edit Collection" link
3. Remove all add-ons from the collection and add only themes
4. Save changes
5. Click the "View your collection" link

Expected results:
The listed themes are displayed together with: rating stars, users, add to coll button, add to fav heart, share this add-on button, etc.

Actual results:
Themes are listed in a compact mode. (maybe, **intended**?)

Notes/Issues:
_Issue is not reproducing if we create from the start a collection only with themes._
How it looks if I make like I've mentioned in the above note: 
![2016-04-21_1301](https://cloud.githubusercontent.com/assets/15685960/14705304/80fb2e04-07c1-11e6-81d5-a2c147f2feab.png)

Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue:
![2016-04-21_1304](https://cloud.githubusercontent.com/assets/15685960/14705331/a04cf56c-07c1-11e6-8949-520f97a0934a.png)

**Comment by andymckay-limited-access** [comment]
We think this is by design, we'll review in the redesign.

**Comment by ValentinaPC** [comment]
Also we should keep in mind a theme comment, in a only-themes-collections, will not be displayed.
