### ISSUE TITLE
"Oops.." page displayed and Themes cannot be approved if author is anonymous

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2464]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/editors/themes/pending
2. Try to approve a Theme with anonymous author (https://addons.allizom.org/en-US/editors/themes/queue/single/testtheme09123)

Expected results:
Theme is successfully approved 

Actual results:
"Oops .. " page is displayed and Theme is not approved

NOTES: If author is not anonymous, we can approve the Themes

Please see video for this bug : 
![oops](https://cloud.githubusercontent.com/assets/1583842/14711210/273b4ff0-07e1-11e6-8d6b-1b4fe425549d.gif)

**Comment by andymckay-limited-access** [comment]
Given that an author should not be anonymous, assuming this isn't a big deal.

**Comment by EnTeQuAk** [comment]
Is it even possible to have an anonymous author in our regular environment? Could that happen if a user deletes his account?

**Comment by EnTeQuAk** [comment]
I believe this isn't really a bug but simply something that should not occur. I don't know how you'd get something uploaded as an anonymous user. I think if someone deletes his account we should delete their add-ons too and stuff, but there's another issue for that.

Closing.
