### ISSUE TITLE
Cannot reject an unlisted addon

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2465]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/editors/unlisted_queue/all
2. Reject any addon from the list

Expected results:
Addon appear as rejected

Actual results:
Addon is still preliminary\full reviewed 

Please see screencast for this bug : http://screencast.com/t/A8ekkmvRbq

**Comment by wagnerand** [comment]
As unlisted add-ons are automatically approved, there is nothing to review from that list. It is a post-approval list for admins to see what unlisted add-ons have been approved (signed).

**Comment by wagnerand** [comment]
Closing. If I got this wrong, feel free to reply/reopen.
