### ISSUE TITLE
"My Profile" displays Firefox compatible add-ons with a "Thunderbird mask"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2468]
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/firefox/
2. Go to "Other Applications" and change to Thunderbird https://addons-dev.allizom.org/en-US/thunderbird/
3. Go to <<username>> - My Profile
4. Observe the listed add-ons

Expected results:
Only Thunderbird compatible add-ons are displayed.

Actual results:
All add-ons are listed, but with Thunderbird style "+Download now" buttons.

Notes/Issues:
If any add-on is clicked, details page containing an "+Add to Firefox" correct button is loaded. If the "+Download Now" button is clicked the .xpi can be downloaded and instruction on how to install the add-on on Thunderbird are displayed, even if the add-on is not compatible with Thunderbird.
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshots for this issue: 
![untitled](https://cloud.githubusercontent.com/assets/15685960/14714954/b49f3ed4-07ef-11e6-9066-183a903e745f.png)

**Comment by andymckay-limited-access** [comment]
This is by design in the current AMO style because the URL has thunderbird in it.
