### ISSUE TITLE
Update by developer is incorrectly detected as review

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2476]
The entry for the True Key add-on shows in Last Review: "1.11.1.1394 on 2016-03-11". If I look for that version in the history (can be found [around here](https://addons.mozilla.org/editors/review/true-key-add-on?page=24#history)), there's no review performed there. Looking at the [update history of the add-on](https://addons.mozilla.org/developers/feed/true-key-add-on?page=12), it seems like the developer changed the maxVersion, which is logged in the review history for some reason.

I suppose the solution here is to discard any activity performed by the developer.

**Comment by eviljeff** [comment]
I might be able to filter out based on the type of action  (only include info, approve, etc).  Filtering by developer oriented activity will be a little trickier (excluding 'Mozilla' was easy as its a single, fixed, user-id).

**Comment by jvillalobos** [comment]
Sounds good. So we would need Approve, Prelim Approve, Reject, Need Info, and Comment. Doesn't seem like Admin Review makes sense in this context.
