### ISSUE TITLE
Commenting on an add-on in the All Unlisted view sends you to Unlisted Prelim queue

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2477]
STR
1) Go to All [Unlisted queue](https://addons.mozilla.org/editors/unlisted_queue/all)
2) Click on an add-on
3) Enter comment and save.

Result:
Ended up in the [Unlisted Preliminary queue](https://addons.mozilla.org/editors/unlisted_queue/preliminary#review-actions).

I should end up back in the list I was in.

**Comment by eviljeff** [comment]
This an issue with editor review pages in general - no review page knows where it was launched from, so the re-direct url when the form is submitted is guessed from the add-ons status (e.g. the add-on is STATUS_LITE, so we should go back to the preliminary queue).
I'll attempt to see if we can check for an unreviewed version and use that as a criteria too - unintended consequences warning here though.

**Comment by jvillalobos** [comment]
Okay. I can definitely live without this if it's too complicated or breaks things.

**Comment by andymckay-limited-access** [comment]
If jorge can live without it, so can I.
