### ISSUE TITLE
Add popup with review text for Last Review column in All Unlisted view

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2478]
In the All Unlisted view, when the Last Review column isn't "No Reviews", there should be a way to read the text of that last review without having to go to the review page. I think it should appear when hovering over the text, but something clickable would also be okay.

**Comment by cosminbadescuSV** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshots: 
![allunlisted](https://cloud.githubusercontent.com/assets/15885467/15314481/cb061456-1c1a-11e6-92a6-ffefc8daadb0.gif)
