### ISSUE TITLE
Refreshing the page for a moment changes the add-on button status into “Download now”

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2480]
Steps to reproduce:

1.Open firefox add-ons page: https://addons-dev.allizom.org/en-US/firefox/
2.Select a category from “Categories”.
3.Refresh the page while hovering over one add-on from preview area.

Expected results:
Refreshing the page does not change the add-on button status.

Actual results:
"Download now" add-on button is displayed for a few seconds when the page is refreshed.

Note/Issues:
Verified on FF45(Win 7). This issue is reproducing in AMO-dev, AMO-stage and AMO-production.
Video of this issue:
![comp](https://cloud.githubusercontent.com/assets/15885467/14738283/5893dac4-0889-11e6-8fb6-9b4248c7959a.gif)

This issue is also reproducing for incompatible add-ons: 
![incomp](https://cloud.githubusercontent.com/assets/15885467/14737904/43f7d86a-0887-11e6-8dd7-ec0cf549eadd.gif)

**Comment by muffinresearch** [comment]
I think this is probably just because the platform detection is all done in JS. Not sure there's a lot we can do about this aside from a large refactor which will have to happen when we get to the point of a more complete front-end redesign.
