### ISSUE TITLE
Add-on details: Modal styling tweaks

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2482]
Originally from: https://github.com/mozilla/addons.mozilla.org-mod/issues/5, moving here so we can close out that repo for issues 😁

@pwalm says we should do:

background behind screenshot/description text: `#000000`
full screen background behind that: `rgba(0,0,0,0.75);`

**Comment by tsl143** [comment]
@tofumatt isnt this already achieved?
![screenshot from 2016-05-10 07 16 31](https://cloud.githubusercontent.com/assets/5318732/15133283/322d3318-167f-11e6-8a93-d04c025cf280.png)

**Comment by tofumatt** [comment]
Good call, looks like #2157 fixed this; closing.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshot: 
![addondetails](https://cloud.githubusercontent.com/assets/15685960/15187227/fc18c8fc-17a8-11e6-8c5d-8273e3d192ad.png)
