### ISSUE TITLE
"Account Settings" page returns a 500 error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2484]
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Go to Username- Account Settings

Expected results:
The Account Settings page is loaded.

Actual results:
An "Oops..." page is loaded. (500 error code in the console)

Notes/Issues:
Verified on FF45(Win 7). Issue is only reproducing on AMO-dev.
Screencast for this issue:
![oops](https://cloud.githubusercontent.com/assets/15685960/14742014/a924a716-08a2-11e6-80e2-482dd6438fd4.gif)

**Comment by muffinresearch** [comment]
KeyError 'content_host'

See  https://sentry.prod.mozaws.net/operations/olympia-dev/group/326419/

**Comment by muffinresearch** [comment]
Looks likely a regression from https://github.com/mozilla/addons-server/commit/cd22e190ed73b1ff47d0d01e544fdb3cf81588f5

**Comment by krupa** [comment]
verified fixed @ https://addons-dev.allizom.org/en-US/firefox/users/edit
