### ISSUE TITLE
Preliminary reviewed info should be white on blue background, instead of black.

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2485]
Currently on detail pages of preliminary reviewed add-ons the explanation underneath is back on blue background. ("This add-on has been preliminarily reviewed by Mozilla.")

To be better readable and conform with other text, this text should be white.

![screen-shot-2016-04-21-at-18 12 46](https://cloud.githubusercontent.com/assets/8145891/14744100/8b0422d6-08a5-11e6-952f-063fa51e3236.gif)
(before and after @ https://addons.mozilla.org/en-US/firefox/addon/download-statusbar/)

**Comment by tsl143** [comment]
@andymckay-limited-access Kindly consider the PR

**Comment by vcarciu** [comment]
This is still reproducible : 
![prelimtext](https://cloud.githubusercontent.com/assets/1583842/15150975/060f9024-16d8-11e6-83bd-7421daab3b3a.png)

**Comment by tofumatt** [comment]
Makes sense, I just checked: it should only work for themes, not add-ons.

@tsl143 Can you move this rule outside `#persona-summary`?

**Comment by vcarciu** [comment]
This issue is still reproducible like in my previous comment

**Comment by tofumatt** [comment]
Alright, I'll take this and fix it. 😄 

@tsl143 In the future, can you please test these changes locally with the code you submitted? Both times you included CSS that was nested in the wrong selector.

**Comment by tsl143** [comment]
@tofumatt apologies, but I was unable to test that locally as my docker image was unable to run after pull.
This is the issue https://github.com/mozilla/addons-server/issues/2596 referring the docker image

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-de FF46(Win7)
Postfix screenshot: 
![2016-05-12_1842](https://cloud.githubusercontent.com/assets/15685960/15220797/77b58b8a-1871-11e6-8e64-df26fb238c4b.png)
