### ISSUE TITLE
"Add to Firefox" is shown but not working as add-on is not available for this version of Firefox.

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2486]
![screen shot 2016-04-21 at 18 12 46](https://cloud.githubusercontent.com/assets/8145891/14744175/f12d8a16-08a5-11e6-8638-8ba3e61f8d2b.png)
Seen on https://addons.mozilla.org/en-US/firefox/addon/print-preview with current Nightly.
"Add to Firefox" button can not be clicked, but looks active, while a message underneath says that it is not available.

Shouldn't this just show the message that this add-in is not available? Like this:
![screen shot 2016-04-22 at 16 25 51](https://cloud.githubusercontent.com/assets/8145891/14744429/0ca47c72-08a7-11e6-80e0-93388743d893.png)

**Comment by designakt** [comment]
Or it could work as it does here:
https://addons.mozilla.org/en-US/firefox/addon/print-preview
Button is clickable but appears inactive with an explanation underneath.
Clicking the button opens a dialog asking if you want to install anyway.
![screen shot 2016-04-22 at 16 31 04](https://cloud.githubusercontent.com/assets/8145891/14744589/a5c6ae7a-08a7-11e6-9f8c-45f39dca6bf6.png)

I wonder why we have 2 behaviors for add-ons that do not work with the used version of Firefox.

**Comment by ValentinaPC** [comment]
@designakt : I think this was already caught.
Please take a look at: https://github.com/mozilla/addons-server/issues/2446
Thanks.
