### ISSUE TITLE
space between add-on description and screenshots can be reduced

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2487]
```
.previews {
    margin: 0 0 2em 0;
}
.addon-details .header-bg {
    margin-bottom: 0;
}
.restyle .previews {
    padding: 15px 0;
}

#addon {
    padding-bottom: 20px 20px 0 104px;
}

.addon-details .primary .notice {
    padding-bottom: 0px;
}
```

The white space between the blue and gray areas is visually not pleasing. And reducing the space increases the visibility of the screenshots as they move further up.

before and after @ https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/
![screen-shot-2016-04-22-at-16 52](https://cloud.githubusercontent.com/assets/8145891/14745275/d70aff7e-08aa-11e6-9905-a508fb12d1a8.gif)

**Comment by designakt** [comment]
@tofumatt This issue is very important to me as it is a big UI improvement as the detail pages are among the most visited, and we will link to those from our new discovery.
(In general, what is the best way for UX to express how important issues are to us? State it in the issue like I do here, or could we have a label for that?)

**Comment by tofumatt** [comment]
If you're looking for a system something like "p1" would work for me. But
bringing it up in the issue as you did is also fine. 🙂

- tofumatt

**Comment by vcarciu** [comment]
Verified as fixed : 
![details](https://cloud.githubusercontent.com/assets/1583842/15150809/6b4e1e0c-16d7-11e6-97f0-008d95479f5f.png)
