### ISSUE TITLE
Search field text in theme "Reviews" page is "search for add-ons"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2495]
Steps to reproduce:
1. Sign in to AMO-dev 
2. Go to Themes page https://addons-dev.allizom.org/en-US/firefox/themes/
3. Load details page for any listed theme (i.e https://addons-dev.allizom.org/en-US/firefox/addon/all-fall/)
4. Write a review or go to all review page
5. Observe the text inside the search field

Expected results:
The text is "search for themes".

Actual results:
The text is "search for add-ons"

Notes/Issue:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue: 
![theme](https://cloud.githubusercontent.com/assets/15685960/14776597/26fabef8-0ad0-11e6-9a00-56f76daa72f7.png)

**Comment by EnTeQuAk** [comment]
This is not too easy to fix because of lots and lots of legacy code involved. I'd close this in favor of our new addons-frontend.
