### ISSUE TITLE
Small statistics link in a search tool details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2496]
Steps to reproduce:
1. Sign in to AMO-dev
2. Go to "More..."->Search Tools
3. Access details page for any _search tool_ i.e. https://addons-dev.allizom.org/en-US/firefox/addon/youtube-10423/
4. Observe the "weekly downloads" link 

Expected results:
The reviews link and the statistics link have same dimension.

Actual results:
The "weekly downloads" stats link is smaller.

Notes/Issues:
Stats link inside of a normal add-on has the same dimension like the reviews link.
Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue: 
![2016-04-25_1113](https://cloud.githubusercontent.com/assets/15685960/14777930/ca687ece-0ad8-11e6-8abb-e742406a1a68.png)

**Comment by andymckay-limited-access** [comment]
Its a different template, don't think this is an issue. Will get fixed in the next redesign.
