### ISSUE TITLE
MySQL replication lag caused by stats update sometimes results in failed sign-ins

### ISSUE THREAD

**Issue by jbuck** [mozilla/addons-server#2498]
Hello AMO team!

First, [the stats](https://app.datadoghq.com/dash/78168/addons-prod?live=false&page=0&is_auto=false&from_ts=1461608126424&to_ts=1461611726424&tile_size=s):

![mysql iops & replication lag](https://cloud.githubusercontent.com/assets/578466/14797584/7a60efdc-0b01-11e6-9491-b6cbda51a1b4.png)

You can see that starting at 2:46PM EST the replication lag from master to replica increases to almost 660 seconds until 3:05PM EST when the replica catches up again. During this period of time @jrgm and I found that it was possible to successfully sign in once but if you attempted to sign in again you'd get an HTTP 500 error:

```
Apr 25 18:51:13: accounts.verify:DEBUG Got profile ...redacted...
Apr 25 18:51:13: z.users:INFO Generating username for ...redacted...
Apr 25 18:51:13: z.users:DEBUG Creating user with email ...redacted...
Apr 25 18:51:24: accounts.verify:DEBUG Got profile ...redacted...
Apr 25 18:51:24: z.users:INFO Generating username for ...redacted...
Apr 25 18:51:24: z.users:DEBUG Creating user with email ...redacted...
Apr 25 18:51:25: django.request:ERROR Internal Server Error: 
    /api/v3/accounts/authenticate/ : ... redacted... 
    IntegrityError: (1062, "Duplicate entry '...redacted...' for key 'email'")
```

@jasonthomas told us that the heavy iops & replication lag is a result of the stats update job. I had a look at the log file and there were 61 IntegrityErrors with 30 of them being unique email addresses during the stats update job.

**Comment by andymckay** [comment]
We still need to archive the stats, but in the meantime we shouldn't be generating 500's on a subsequent sign in, @mstriemer could you look at that please?
