### ISSUE TITLE
[traceback] AttributeError: 'NoneType' object has no attribute 'lower' on /firefox/i/promos?platform=linux&=

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-server#2500]
https://addons.allizom.org/en-US/firefox/i/promos?platform=linux&= throws an HTTP 500 / exception:

AttributeError: 'NoneType' object has no attribute 'lower'
  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "olympia/addons/views.py", line 401, in homepage_promos
    return promos(request, 'home', version, platform)
  File "olympia/discovery/views.py", line 74, in promos
    platform = amo.PLATFORM_DICT.get(version.lower(), amo.PLATFORM_ALL)

Sentry: https://sentry.prod.mozaws.net/operations/olympia-stage/issues/234928/

**Comment by andymckay-limited-access** [comment]
We think this is because the URL isn't right. It shouldn't generate a 500, but not critical.

**Comment by stephendonner** [comment]
Yeah, it's clearly a fuzzed or malformed URL - no legit client should be sending that, normally.

**Comment by diox** [comment]
I was about to mark this as a good first bug but I noticed a more subtle bug hidden in those lines so I'm taking it myself.
