### ISSUE TITLE
Contribution example screenshots are outdated

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2502]
**Steps to reproduce:**
1. Open manage payments page for an add-on that has developer profile set up.
2. Hover over the Example links.

**Expected results:**
The screenshots are displaying clear information and are consistent with the style refresh.

**Actual results:**
The screenshots are outdated.

**Notes/Issues:**
Verified in FF45(Win7) Issue can be reproduced in amo-dev, stage and production
Screencast for this issue:
![contributescreenshots](https://cloud.githubusercontent.com/assets/15685441/14810673/bb732ecc-0b9c-11e6-9660-8cb67118717c.gif)tyl

**Comment by muffinresearch** [comment]
@pwalm @designakt any chance you could provide a better image to us to use for this?

**Comment by muffinresearch** [comment]
Once this has an asset to use - this can be labelled `good first bug`

**Comment by designakt** [comment]
Seams like a minor problem to me as the function still is the same.
Could you please share the current assets with us so that we know what they show and what size they are. (The gif is somewhat fast for me to see what screenshots it shows.)

**Comment by andymckay-limited-access** [comment]
How about we just remove these?

**Comment by andymckay** [comment]
I'm just going to remove this as soon as I can get docker working again.
