### ISSUE TITLE
search filters with linebreaks cause vertical scrollbars

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#2503]
Go to [https://addons.mozilla.org/de/firefox/search/?q=noscript&status=4&sourceid=Mozilla-search](https://addons.mozilla.org/de/firefox/search/?q=noscript&status=4&sourceid=Mozilla-search). The filter "Alle Versionen von Firefox" on the left is too long and gets wrapped with a line break. This causes a vertical scrollbar.

**Comment by muffinresearch** [comment]
@tofumatt this is probably not very nice for any os that doesn't hide scrollbars by default - would be good to get this fixed.

**Comment by tofumatt** [comment]
Remove `#search-facets .facets .facet > ul { overflow-y: auto; }`

**Comment by vcarciu** [comment]
Verifed as fixed : 
![alleversion](https://cloud.githubusercontent.com/assets/1583842/15183937/ecd778e6-179b-11e6-9e31-8591ba054431.png)
