### ISSUE TITLE
Language pack compatibility bump fails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2504]
`https://addons.mozilla.org/en-US/admin/langpacks` tries to fetch language packs from  `https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/<VERSION>/win32/xpi/` However that URL now redirects to `https://ftp.mozilla.org/pub/firefox/releases/<VERSION>/win32/xpi/` but it seems we're not following redirects.

This makes it impossible to make language packs compatible with Firefox 46 which is to be released today.

I think the easiest solution would be to update  `LANGPACK_DOWNLOAD_BASE` in `src/olympia/lib/settings_base.py`.

**Comment by muffinresearch** [comment]
> I think the easiest solution would be to update LANGPACK_DOWNLOAD_BASE in src/olympia/lib/settings_base.py.

I agree like it would make sense to update the BASE_URL now and then also (in slower time) fix the code so it does follow redirects in the future.

**Comment by wagnerand** [comment]
Turns, we do follow the redirect. But we determine the actual language pack files to download based on https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/<VERSION>/SHA512SUMS. For 46 however, that file contains the wrong file names of the language packs which makes us trying to download files that don't exist.

**Comment by eviljeff** [comment]
So the bug is in whatever code generates SHA512SUMS for the ftp?

**Comment by wagnerand** [comment]
Yes, it's https://bugzilla.mozilla.org/show_bug.cgi?id=1160385. It's currently being thought about what could be done.

**Comment by wagnerand** [comment]
The file is going to be fixed today. There is nothing to be done here. I apologize for the noise.
