### ISSUE TITLE
Fix lang pack fetching code to follow redirects

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2505]
Relates to #2504 - the url to the lang pack downloads changed [1]. Whilst the ftp server provides a redirect our fetching code doesn't appearing to follow it. Whilst we'll  be changing the setting (in #2504) as a quick fix we'd also like to fix the code so that it follows redirects in the future should the URL change again.

[1] https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L1582

**Comment by wagnerand** [comment]
It might not be the cause for #2504, but nevertheless, we should probably update the URL.
