### ISSUE TITLE
Unable to disable API access on set up page

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#2506]
I see the "If you believe this key was created in error, you can remove the key and disable access at the following location: https://addons.mozilla.org/zh-CN/developers/addon/api/key/" in notification email, but the https://addons.mozilla.org/developers/addon/api/key/ no way to Disabled, the "Revoke and **regenerate credentials**" only.

**Comment by jvillalobos** [comment]
I think Revoke and Disable would have the same meaning in this context, though it'd be good to use the same wording. What do you want to do exactly?

**Comment by yfdyh000** [comment]
I want to completely disable this feature for now, remove API key and don't regenerate, it produces an additional security short board and I currently don't need it.

**Comment by andymckay-limited-access** [comment]
Done in https://github.com/mozilla/addons-server/pull/2522

**Comment by vcarciu** [comment]
Verified as fixed : 
![revoke](https://cloud.githubusercontent.com/assets/1583842/15181988/e553b098-1792-11e6-99a0-baf271761c3c.gif)
