### ISSUE TITLE
Disabled beta version becomes "Next Version"

### ISSUE THREAD

**Issue by Quicksaver** [mozilla/addons-server#2507]
STR:
1. Upload a beta version to the add-on's development channel.
2. Disable that beta version.

Example: https://addons.mozilla.org/developers/addon/tab-groups-panorama/versions, see screenshot.
![disabledisnext](https://cloud.githubusercontent.com/assets/802086/14821769/e5e55302-0bc3-11e6-9b1b-c55571ecce0f.jpg)

Note, the disabled version is still invisible to the public AFAICT, as expected. It only appears as the next version to me - the developer.

**Comment by ValentinaPC** [comment]
I think I've you are talking about: https://github.com/mozilla/addons-server/issues/1912 
Sorry if I'm wrong.

**Comment by Quicksaver** [comment]
I can't be sure it's the exact same issue because in my case I'm uploading a beta version, not a final/full/normal version. In #1912 it could just be that the "Next version" field is not being reset appropriately, whereas in my case, uploading a beta version doesn't set the "Next version" field by itself; that only appears **after** disabling the beta version.

I'll let someone with more knowledge of what's happening behind the scenes decide.

**Comment by Quicksaver** [comment]
In other words, in #1912 the "Next version" remains after disabling an unreviewed version, whereas here the "Next version" appears only after disabling a beta version.

**Comment by andymckay-limited-access** [comment]
@eviljeff and @krupa might want to take a look at the right thing to do here.

**Comment by eviljeff** [comment]
Its a dupe to #1912 - it's accessing the `latest_version` property which, rightly or wrongly, [doesn't exclude disabled](https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/models.py#L694) versions when its updated. 
The algorithm _does_ exclude beta versions though - that's why you don't see the next version field for beta versions, but you do when the beta status is overridden by being disabled.

**Comment by eviljeff** [comment]
As for the right thing to do, I would think we should exclude disabled versions (actually files) from the `latest_version` calculation but I'm very wary of changing the logic as its used extensively.  (Disabled status is used for rejected files/versions also.) 
If the only impact is this display inaccuracy I'd judge it not worth the risk of unintended consequences.

**Comment by Quicksaver** [comment]
Just uploaded a new beta version, disabled it, "next version" text is no longer present. Issue confirmed fixed.
