### ISSUE TITLE
Cannot Edit or Delete a reply of an addon comment

### ISSUE THREAD

**Issue by danny0838** [mozilla/addons-server#2509]
The 2 action buttons for Editing/Deleting a reply of an addon comment don't work in the below links: 

https://addons.mozilla.org/zh-TW/firefox/addon/scrapbook-x/reviews/793012/#

![2016-04-26 23_04_37-scrapbook x __ __ firefox](https://cloud.githubusercontent.com/assets/531417/14822989/6183fd94-0c03-11e6-83d2-7d0bfb26216a.png)

But buttons in the link https://addons.mozilla.org/en-US/firefox/addon/scrapbook-x/reviews/793012/# does work.

**Comment by muffinresearch** [comment]
@tofumatt if you have a chance to take a look would be good to see if this is a quick fix.

**Comment by tsl143** [comment]
Unable to reproduce, both edit and delete links work for me 
![screenshot from 2016-05-07 13 38 59](https://cloud.githubusercontent.com/assets/5318732/15091028/25168e2c-1459-11e6-8aae-feb639df9d22.png)

**Comment by tsl143** [comment]
@danny0838 ^^

**Comment by danny0838** [comment]
@tsl143 It seems to work now for unknown reason. Thanks.
