### ISSUE TITLE
Long themes names appear cut at hover

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2512]
Steps tor reproduce:
1. Load AMO-stage page 
2. Change the language to Deutsch https://addons.allizom.org/de/firefox/
3. Go to "Featured Themes" section and hover over a theme with long name 

Expected results:
There are no display or layout issues.

Actual results:
Theme name appears cut.

Notes/Issues:
Issue is reproducing in: My Profile->Themes section, Homepage->Featured Themes section, Themes homepage, Themes categories, for a theme with two-words name if other language is selected (because +Add button becomes too long) or **for English if theme name is on 4 rows at hover.**
Verified on FF45(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Please see screenshots for this issue:
![homepage-featured_themes](https://cloud.githubusercontent.com/assets/15685960/14847809/57da8b94-0c73-11e6-86c0-de3fe1a3f027.png)
![themes homepage](https://cloud.githubusercontent.com/assets/15685960/14847819/6015b810-0c73-11e6-8b21-424a234edac0.png)
![my_profile-themes_section](https://cloud.githubusercontent.com/assets/15685960/14847825/65532d94-0c73-11e6-91cd-fe2eaa2b0d73.png)

**Comment by tsl143** [comment]
PR https://github.com/mozilla/addons-server/pull/2582
this can be one possible solution, terminating with ellipsis.
@andymckay-limited-access

**Comment by tsl143** [comment]
Here are the screenshots

![after](https://cloud.githubusercontent.com/assets/5318732/15091326/d46a1a60-1463-11e6-9104-c2e6ef39f3ec.png)
![before](https://cloud.githubusercontent.com/assets/5318732/15091325/d1176a34-1463-11e6-91d8-93ffc4158d33.png)

**Comment by tsl143** [comment]
@tofumatt , screen shots attached

**Comment by ValentinaPC** [comment]
The issue with long themes name at hover was successfully fixed.
Please see the screenshot: 
![2016-05-11_1320](https://cloud.githubusercontent.com/assets/15685960/15177917/456c0c72-177b-11e6-9132-6e1a031d0741.png)

But, another thing is happening now. I'll track that issue separately and close this.
