### ISSUE TITLE
Request: Different words for "review" (rating) and "reviwe" (check)

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#2513]
Hi,

I'd like to ask you to use different words for "review" (= rating) and "review" (= check) in future. That should apply to their derivations, too, e.g. "reviewer" or "to review". It is difficult for localizers to decide which meaning applies. A localizer translates isolated strings and does not know always the context of the strings. Other languages must use different words.

Thanks.

**Comment by andymckay-limited-access** [comment]
That's a good idea and I think something we should do on the new rewrite of add-ons. But probably not something we want to try changing now.

**Comment by milupo** [comment]
OK. I realize that this is not possible right now. But keep sight of it for the future, please.
