### ISSUE TITLE
Update CORS for internal API endpoints

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#2519]
We need to update the CORS settings for the internal API endpoints. They should only be allowed from their matching addons-admin server, so https://addons-dev.allizom.org allows http://addons-admin.dev.mozaws.net (and http://localhost:3000 but only on dev).

Supports #2385.

**Comment by vcarciu** [comment]
@mstriemer : can you please add some STRs to this bug or add qa- label?

**Comment by mstriemer** [comment]
If login works it's working. No need to qa that.
