### ISSUE TITLE
All add-on validation is failing on dev: ValueError(errmsg("Extra data", s, end, len(s)))#012ValueError: Extra data: line 1 column 10298 - line 1 column 10454 (char 10297 - 10453)

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2523]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2. Upload any add-on for validation

## observed behavior:
Validation is failing for all add-ons

## error:
Apr 27 23:58:41 ip-172-31-37-129.ec2.internal: [][] z.devhub.task:ERROR Unhandled error during validation: ValueError('Extra data: line 1 column 10298 - line 1 column 10454 (char 10297 - 10453)',) :/data/olympia/src/olympia/devhub/tasks.py:138#012Traceback (most recent call last):#012  File "/data/olympia/src/olympia/devhub/tasks.py", line 128, in wrapper#012    data = fn(id_, hash_, *args, **kw)#012  File "/data/olympia/src/olympia/devhub/tasks.py", line 157, in validate_file_path#012    return run_validator(path, listed=listed)#012  File "/data/olympia/src/olympia/devhub/tasks.py", line 396, in run_validator#012    listed=listed#012  File "/data/olympia/venv/lib/python2.7/site-packages/validator/validate.py", line 68, in validate#012    apps = json.load(approved_apps)#012  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load#012    **kw)#012  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads#012    return _default_decoder.decode(s)#012  File "/usr/lib64/python2.7/json/decoder.py", line 368, in decode#012    raise ValueError(errmsg("Extra data", s, end, len(s)))#012ValueError: Extra data: line 1 column 10298 - line 1 column 10454 (char 10297 - 10453)

**Comment by andymckay** [comment]
Working now.
