### ISSUE TITLE
Themes backgrounds are not correctly aligned in homepage carrousel

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2525]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/
2.Hover over some themes on the carrousel
3.Observe the background visible while hovering

Expected results:
Background is correctly aligned

Actual results:
Theme preview is larger than the blackground

Please see video for this issue:
![background](https://cloud.githubusercontent.com/assets/1583842/14890370/0083e306-0d6b-11e6-8ca0-ba00a9213b07.gif)

**Comment by tsl143** [comment]
@andymckay can I work on this?

**Comment by tofumatt** [comment]
@tsl143 Sure thing! You we can't assign it to you via GitHub because it won't let us assign to people outside the Mozilla organisation, but please work on it and submit a pull request when it's ready. You can ping me to review your pull request, thanks! 👍🏻

**Comment by tsl143** [comment]
@tofumatt pr generated

**Comment by tsl143** [comment]
@muffinresearch - rebased the complete fork, thank you sooooo much for the help 
@tofumatt - PR generated https://github.com/mozilla/addons-server/pull/2580

**Comment by tsl143** [comment]
PR https://github.com/mozilla/addons-server/pull/2580 merged 
@vcarciu , @muffinresearch Can we close this?

**Comment by mstriemer** [comment]
Fixed by https://github.com/mozilla/addons-server/pull/2580, thanks Trishul!

**Comment by vcarciu** [comment]
Verified as fixed : 
![themebackground](https://cloud.githubusercontent.com/assets/1583842/15148882/18295928-16d0-11e6-8b06-e605fff1297d.gif)
