### ISSUE TITLE
Support hidden add-ons

### ISSUE THREAD

**Issue by wresuolc** [mozilla/addons-server#2526]
Most of the experiments in Test Pilot are not ready for general consumption so we've been avoiding putting them on AMO.  Generally we get them signed, and then host them on S3 along with an update.rdf.

The main thing stopping us from using AMO is that we can't opt out of the search pages while still having the add-on available for download.  It could have a detail page or not, but at a minimum I'd like to have a Status on AMO where a URL to the .xpi and to the .rdf is live and working, and it's not discoverable anywhere else.

This isn't an emergency or even a requirement.  What we have is working.  Just in the interest of keeping add-ons in one place and not duplicating work I thought I'd file this to explore the option on AMO.

Cheers!

**Comment by andymckay** [comment]
What do you think @jvillalobos or @deadsquid? I've seen this request from a few different teams.

**Comment by jvillalobos** [comment]
It's one of the open questions in the [status redesign](https://docs.google.com/document/d/1OH2iZ7aT9otFJvGTX1UR6pAm58u7ph2Uw8_Zv2Sl8Tk/edit). I don't think we should do this without working first on simplifying the status / review code.

**Comment by lmorchard** [comment]
IMO, this is more than experiments not being ready for general consumption. They may never be, and shouldn't be treated like normal add-ons. Test Pilot experiments may someday even want to support temporary system add-ons. I'd guess that's something AMO probably doesn't ever want to host. See also https://github.com/mozilla/testpilot/issues/406

**Comment by andymckay** [comment]
I would argue that AMO is a perfect place to host experiments, most of the add-ons are just that. 

In the future I think there's coming a difference between the idea of "shipping internal code as an add-on" (system addons) and "using the WebExtensions API" (something on AMO), something that mozilla hasn't really distinguished in the past.

I don't think the former is something we should focus in AMO and that's a bigger conversation.

However, for the next months you want people to be able to install test pilot as easily as possible. I think we've got some work arounds for that.

**Comment by lmorchard** [comment]
> In the future I think there's coming a difference between the idea of "shipping internal code as an add-on" (system addons) and "using the WebExtensions API" (something on AMO), something that mozilla hasn't really distinguished in the past.

> I don't think the former is something we should focus in AMO and that's a bigger conversation.

Yeah, I think my concern is just that I don't want us to get AMO and Test Pilot tangled together in a way that might unnecessarily limit / complicate both projects in the future.

> However, for the next months you want people to be able to install test pilot as easily as possible. I think we've got some work arounds for that.

Cool, as long as we keep in mind that it might be a temporary fix. We might also, for example, want to look into getting Test Pilot whitelisted like AMO so we can ship an add-on without all the warnings (since we're also a part of the Firefox product, after all)

**Comment by sylvestre** [comment]
Can we bump the priority of this bug?
Firefox-hotfix would greatly use this: https://addons.mozilla.org/en-US/firefox/addon/firefox-hotfix/

**Comment by andymckay** [comment]
For the firefox hotfix I would like to see it become a go faster add-on and removed from AMO completely.

**Comment by jvillalobos** [comment]
The status work is progressing, but we won't be working on this in Q4. At best we can make a decision if we really want it for Q1 or Q2 next year.

**Comment by eviljeff** [comment]
@jvillalobos decision time ⏳

**Comment by jvillalobos** [comment]
We briefly discussed this during the review work week. My position is that supporting hidden on top of what we have (listed, unlisted, beta, etc.) is too much, so we should look into this feature as a replacement rather than an addition. All that said, no decision was made 💾.

**Comment by muffinresearch** [comment]
@jvillalobos any updates on where this should fit in terms of priorityy, the idea of a separate upload hasn't really gotten any traction of late either.

**Comment by jvillalobos** [comment]
I don't expect anything to happen here in H1, so I think it's very low priority.
