### ISSUE TITLE
String 'Featured' is used in different contexts and needs disambiguation context for localization

### ISSUE THREAD

**Issue by lliehu** [mozilla/addons-server#2528]
The string 'Featured' currently exists in over a dozen different places.

The thing is that in some languages, for example in Finnish, adjectives can be singular or plural depending on how many things it refers to.

In some places 'Featured' refers to the list of featured add-ons, meaning that 'Featured' is a category containing many add-ons as in plural. This is the case on the front page, to the left, below the heading 'Explore'. Thus there 'Featured' needs to be translated as plural.

In some other places 'Featured' refers to a single featured add-on. This is the case on the page of a single add-on where on the right it says that an add-on is 'Featured'. Thus there 'Featured' needs to be translated as singular.

Because of the way Gettext works, all instances of the string 'Featured' have to share the same translation if there is no disambiguation context. Thus, as a localizer, I would like there to be some disambiguation context between these two cases so that proper localization would be possible.

**Comment by andymckay-limited-access** [comment]
Let's do this in the redesign.
