### ISSUE TITLE
Wrapping of long code

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#2529]
The word-wrap would be beneficial for the following example:
https://addons.mozilla.org/en-US/firefox/files/compare/431655...424267/file/content/browser/m_browser.js#top

**Comment by CuriousLearner** [comment]
Seems like the url is not available publically What is the issue, can you please attach a screenshot or gif? @erosman

**Comment by erosman** [comment]
I filed that nearly 2 years ago ;)
Here is the new URL:
`https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/431642/file/content/browser/m_browser.js#top`

Check the horizontal scroll.

**Comment by CuriousLearner** [comment]
Ah, seems like I cannot access it :(

**Comment by erosman** [comment]
> Ah, seems like I cannot access it :(

What about this one?
`https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/437194/file/content/browser/m_browser.js#top`

If you can access the dev version review tools 

Add-on: mKiosk: Kiosk Mode for Firefox  
URL: https://addons.mozilla.org/en-US/firefox/addon/mkiosk/
Version: 2016.05.0 or older
File: content/browser/m_browser.js
