### ISSUE TITLE
Make tool to view and edit canned responses

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2531]
We're currently using the [admin models](https://addons.mozilla.org/admin/models/editors/cannedresponse/) to handle canned responses. This has lead to some problems, like #1858, and also limitations on who has access to it.

We need a tool that is functionally equivalent to that model, that lets admin reviewers view and edit canned responses.

**Comment by vcarciu** [comment]
@jvillalobos Can you please add some STRs here or add  qa- label ?
