### ISSUE TITLE
Docker Hub builds are broken

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2536]
See https://hub.docker.com/r/addons/addons-server/builds/

https://github.com/mozilla/addons-server/pull/2300 broke them, let's fix'em again.

**Comment by muffinresearch** [comment]
We also need to work out a way to track when builds fail, so that we're aware when it happens.

**Comment by vcarciu** [comment]
@EnTeQuAk : can you please add some STRs to verify this bug or add qa- label?

**Comment by andymckay** [comment]
https://hub.docker.com/r/addons/addons-server/builds/, they say success. Yay.
