### ISSUE TITLE
Setup up something simple to track docker hub builds

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2546]
Hub builds can be broken and we don't get any notifications. We should set-up the simplest possible thing to make sure that we know when builds break.

**Comment by andymckay** [comment]
@muffinresearch with the new pipeline, is this still relevant?

**Comment by EnTeQuAk** [comment]
cc @bqbn on this, at the moment we are still waiting for circleci for addons-frontend but I don't know if that's still the case for our v2 pipeline.

**Comment by muffinresearch** [comment]
We get this by email.
