### ISSUE TITLE
Addon's version history text uses only 2/3 of available width, leaving the rest wasted

### ISSUE THREAD

**Issue by vanowm** [mozilla/addons-server#2547]
The version information text is wraps around, yet there is still 1/3 of the the column width available and wasted.
This looks quiet bad when there is a lot of text:
https://addons.mozilla.org/firefox/addon/cookies-manager-plus/versions/

![screenshot](http://i.imgur.com/GNmG8ik.png?1)

**Comment by tofumatt** [comment]
I don't think this looks bad, and I don't think extending the text improves it. Version notes are often lists where the extra space isn't used, but if it is it's a good rule to wrap text so that lines aren't too long.

Making this any wider will result in harder to read lines:

<img width="823" alt="screenshot 2016-05-03 17 11 32" src="https://cloud.githubusercontent.com/assets/90871/14989932/39b0c0f0-1152-11e6-8910-dfbe93de4ca0.png">

**Comment by vanowm** [comment]
I don't quiet understand why would it be harder to read in the column of 470 pixels wide...on screens with 800+pixels wide.
IMO it's harder to read when text wraps around for no apparent reason...especially when you don't see that "add to firefox" button until you hover over the column, but you see how wide the column is with the pink banner on top and text wrapped around at 2/3 of that column.

![mock-up](http://i.imgur.com/lFM6uwd.png?1)

In this mock-up the change was quiet simple: the .action div was moved inside the .info div, and added "float: left" to it. Tweaked some padding/margin on both divs and voilà perfect column.

**Comment by eviljeff** [comment]
@tofumatt @kumar303 are there ux mocks for the new version listing page?  (i.e. would this be a valid bug there?)

**Comment by muffinresearch** [comment]
Will be superceded by https://github.com/mozilla/addons-frontend/issues/2770

**Comment by tofumatt** [comment]
I don’t think it’s a valid bug at all. Text should wrap around 66 characters (55-70 is a good range, depending on font face) for best readability. People’s eyes find it harder to connect the end of one line to the next when the width of the text is very long.

Not sure we have mocks for the new one but I’ve won’t fix’d similar issues on the front end already.
