### ISSUE TITLE
Outdated links to Editors' Guide

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#2551]
AMO links to https://wiki.mozilla.org/AMO:Editors/EditorGuide in various places. This link is outdated, the correct one being https://wiki.mozilla.org/Add-ons/Reviewers/Guide.

In particular, this link can be found in:

* src/olympia/pages/templates/pages/dev_faq.html
* src/olympia/editors/templates/editors/queue.html
* src/olympia/devhub/templates/devhub/docs/policies-reviews.html
* src/olympia/lib/settings_base.py

**Comment by tsl143** [comment]
PR for this https://github.com/mozilla/addons-server/pull/2583
