### ISSUE TITLE
[AMO-dev] Fresh submitted web-extensions cannot be installed 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2554]
Steps to reproduce:
1. Submit and approve a web-extension on AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/addon/renametab/
2. Try to install the web-extension

Expected results:
The web-extension is installed.

Actual results:
The web-extension is not installed. A message saying the web-extension is corrupt is displayed.

Notes/Issues:
Issue is reproducing on FF46 and FF49(Win 7).
**Issue is ONLY reproducing on AMO-dev.
NOT reproducible for normal add-ons or old web-extensions.**
Please see the screenshot: 
![2016-05-04_1650](https://cloud.githubusercontent.com/assets/15685960/15016164/7a6550cc-1218-11e6-9d18-5d85de03751f.png)

Attaching used web-extension:
[RenameTab.zip](https://github.com/mozilla/addons-server/files/248851/RenameTab.zip)

**Comment by EnTeQuAk** [comment]
With a bit of luck this will be fixed with https://github.com/mozilla/addons-server/pull/2555 as well. Keeping it open to verify later though.

**Comment by EnTeQuAk** [comment]
Can you re-verify this? You will need to reupload the XPI file though so that it'll pick-up the correct add-on id.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7) using web-extensions preliminary and full.
Postfix screenshot: 
![rename_tab_installed-full](https://cloud.githubusercontent.com/assets/15685960/15039302/a27f241a-12b4-11e6-8b1e-d1872177ba20.png)
