### ISSUE TITLE
Update the copy because of signing

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2559]
Once you've submitted an add-on you get to a page like this:

![screenshot 2016-05-04 15 05 05](https://cloud.githubusercontent.com/assets/74699/15030904/ead032aa-1209-11e6-980e-2bc7b904677c.png)

"In the meantime, you and your friend can install it directly from its details page:"

...but. Thanks to signing you can't actually install that add-on until its signed which happens once its reviewed. Unless you have dev or nightly and turn off signing. If you do that, then you get an unsigned add-on that you can't update when its signed because the version doesn't change.

We should reword this.

**Comment by vcarciu** [comment]
Verified as fixed : 
![szia](https://cloud.githubusercontent.com/assets/1583842/15181683/315dd0c4-1791-11e6-88ae-ad1df351a2e1.png)
