### ISSUE TITLE
[AMO-dev] Web-extension without ID returns duplicate ID error at submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2562]
#1891 

Steps to reproduce:
1. Pick a webextension without ID set in the manifest.json 
2. Submit that web-extension using https://addons-dev.allizom.org/en-US/developers/addon/submit/2

Expected results:
A ID is generated.

Actual results:
"Duplicate add-on ID found" error message is displayed.

Notes/Issues:
Issue is only reproducing on AMO-dev for all web-extension without ID.
Verified on FF46(Win 7).
Screenshot from the manifest.json: 
![2016-05-05_1545](https://cloud.githubusercontent.com/assets/15685960/15043775/67b3b44e-12d8-11e6-986f-74501ef406ed.png)
Attaching used web-extension.
[OneTab.zip](https://github.com/mozilla/addons-server/files/250401/OneTab.zip)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF46(Win 7).
I've submitted a web-extension without an ID, no error were raised, but I cannot select a platform and for this matter, I cannot go forward with the submission process. 
Please see the screenshot: 
![2016-05-06_1628](https://cloud.githubusercontent.com/assets/15685960/15074683/efad542e-13a8-11e6-8b28-c7ec15432cb5.png)

**Comment by EnTeQuAk** [comment]
hmm, weird, looking into that

**Comment by EnTeQuAk** [comment]
@ValentinaPC can we split this into a separate issue and solve this one here since the duplicate error isn't thrown anymore?

I'll look at this on Monday.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshots: 
![2016-05-09_0821_001](https://cloud.githubusercontent.com/assets/15685960/15104296/2540a646-15bf-11e6-8b93-46a08f00a8ac.png)
![2016-05-09_0821](https://cloud.githubusercontent.com/assets/15685960/15104297/299ec83a-15bf-11e6-87ef-caf5506d851c.png)

Based on previous comment and the verification I'll close this as fixed and reopen another.

**Comment by EnTeQuAk** [comment]
Thanks!
