### ISSUE TITLE
Corrupted add-on on production

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#2564]
**Steps to reproduce**
1.Navigate to https://addons.mozilla.org/ro/firefox/addon/calculate-fba/?src=cb-dl-created
2.Install the add-on

**Expected results:**
The add-on is successfully installed.

**Actual results**:
The add-on cannot be installed.

**Additional notes:**
- This issue reproduces on AMO-production using Firefox 49.0a1 (2016-05-05) under Windows 10 64-bit.
- I was able to submit the same add-on on AMO-stage ( https://addons.allizom.org/en-US/firefox/addon/fba-calculator1/ ) but also here the add-on seems to be corrupted.
- Please see the screenshot for this issue:
![cc](https://cloud.githubusercontent.com/assets/18114210/15047883/98cb01f6-12ef-11e6-8f5b-31d43dee6edf.jpg)

**Comment by andymckay** [comment]
This add-on has a package.json and no install.rdf meaning it was built in correctly. This is very similar to #2438  and will be resolved when #2460 is fixed. I recommend we keep this open so we check this kind of add-on can't get onto AMO when #2460 is resolved.

**Comment by EnTeQuAk** [comment]
We removed the parsing related code from AMO which will land on -dev shortly, should land on -stage on Tue and go live on Thu. I'll close this as fixed but please feel free to re-open if there's something still broken.

**Comment by vasilicamihasca** [comment]
Verified as fixed on Amo-dev using Firefox 49.0a1 (216-05-09) under Windows 10 64-bit. 
- The attached add-on is not submitted on Amo-dev (No install.rdf or manifest.json found) but is successfully validated using amo-validator.
- I was also able to submit and install both webextension and add-on with a package.json. (https://addons-dev.allizom.org/en-US/firefox/addon/test-extension-1/ and https://addons-dev.allizom.org/en-US/firefox/addon/addthis1/)
- Postfix screenshots:
![2016-05-10_1557](https://cloud.githubusercontent.com/assets/18114210/15147187/ff08bb3a-16c7-11e6-9828-14fb0dc71f57.png)
![2016-05-10_1558](https://cloud.githubusercontent.com/assets/18114210/15147205/1b903170-16c8-11e6-8188-63096ddffe27.png)
