### ISSUE TITLE
Fresh installation fails

### ISSUE THREAD

**Issue by chrmod** [mozilla/addons-server#2568]
Following installation steps from: https://addons-server.readthedocs.io/en/latest/topics/install/docker.html
ends up with error on `make initialize_docker`:
```
Applying product_details.0002_auto_20151006_1348...Traceback (most recent call last):
<stack trace>
django.db.utils.IntegrityError: (1048, "Column 'last_modified' cannot be null")
```
To me it looks like **django-product-details** 0.8.2 does not provide proper product details json file.

**Comment by wagnerand** [comment]
I can confirm this.

**Comment by chrmod** [comment]
It is exactly this line causing the problem:
https://github.com/mozilla/django-product-details/blob/63c58051842835d1f21c554ba1367c1e55ef2a8a/product_details/storage.py#L234

More specifically:
`storage.last_modified('regions/')` returns `None` instead of time string

**Comment by kewisch** [comment]
I've had something like this before on an upgrade, but it fixed itself when I reinitialized everything from scratch. Does cleaning up and running `make initialize_docker` again do anything for you?

**Comment by EnTeQuAk** [comment]
We upgraded to mozilla-product-details 0.12.1 recently so this should not be a problem anymore. If it is for some reason, feel free to re-open anytime.

**Comment by harikishen** [comment]
The issue is not fixed

**Comment by EnTeQuAk** [comment]
This works perfectly for me as far as I can tell, can you post any specific details and more information about what doesn't work? If possible preferred as a new github-issue.
