### ISSUE TITLE
When will be dsb and hsb added to the AMO pages?

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#2571]
Hi,

please add the locales dsb (Lower Sorbian) and hsb (Upper Sorbian) to the AMO pages now. I opened issue https://github.com/mozilla/addons-server/issues/2416 that has been closed 10 days ago (April 26, 2016). AFAIK AMO is deployed every Thursday. Since closing the issue already 2 Thursdays have passed by.

**Comment by andymckay** [comment]
Please don't open a new bug when commenting on the old bug, #2416 will suffice.

**Comment by milupo** [comment]
Bug #2416 was closed. And: Why do you close bugs if they are not fully fixed yet?

**Comment by andymckay** [comment]
I've re-opened the bug and commented there. github automatically closes the bug when the pull request is merged.
