### ISSUE TITLE
compatibility isn´t updated if you remove "android" from the addons listing.

### ISSUE THREAD

**Issue by Ulf3000** [mozilla/addons-server#2572]
if you upload an addon which has both firefox and fennec in the package.json and you the remove the android compatibility from the addons listing after uploading it , its still available in the android addon-store. 

thanx for listening

**Comment by jvillalobos** [comment]
Which add-on are you referring to? And what do you mean by "still available"? Where do you still see it?

**Comment by Ulf3000** [comment]
any addon ... i still see it in the android addon-store as android compatible and downloadable/installable,
even though i removed android support in the addon management on amo. we discussed this on irc addons channel and they said its a bug and i should file it here.

**Comment by jvillalobos** [comment]
Can you give one example so we can look into it?

**Comment by rctgamer3** [comment]
https://addons.mozilla.org/addon/realtime-ip-check

**Comment by diox** [comment]
I don't see "realtime ip check" when searching for add-ons on Android. Any other examples, @rctgamer3 or @Ulf3000 ?

**Comment by Ulf3000** [comment]
well i edited it out in the xpi .. so you can´t find it anymore ... i don´t know if this is still in effect im just making my package.json correct now and don´t edit it on the upload page

**Comment by eviljeff** [comment]
going to close this if we can't reproduce.

**Comment by ValentinaPC** [comment]
I've tried to reproduce this issue using AMO-dev FF52(Win 7), and obtained the results:
- after deleting the "Firefox for Android", from Dev Hub - Compatibility section, for my add-on, I was still able to see the add-on in the Android Add-ons listing pages and through search suggestions
- after accessing the add-on details page, things are displayed as expected

Used add-on:  https://addons-dev.allizom.org/en-US/developers/addon/ublock-origin-test/versions/1531821
Search results: https://addons-dev.allizom.org/en-US/android/search/?q=uBlock+Origin-test&appver=&platform=
Screenshot: 
![2017-03-22_1830](https://cloud.githubusercontent.com/assets/15685960/24209041/d67cb482-0f2d-11e7-8967-5a6ff92b8d9a.png)

Reopening.
