### ISSUE TITLE
AMO returns is-compatible="false" for compatibly-overridden add-on / theme.

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#2575]
Possibly related to #2572 and similar to #2573, AMO shows the following data in the DOM for my [Firefox 2 theme](https://addons.mozilla.org/addon/6898/):

```
  data-min="29.0a2"
  data-max="*"
  data-is-compatible="false"
  data-is-compatible-app="true"
```

I've set maxVersion to the wildcard because otherwise I'd have to update the maxVersion every time (version compatibility bumps announced by @jvillalobos do not happen with complete themes).
If it turns out to be true that AMO doesn't override compatibility as suggested in #2572, `maxVersion` AMO overrides are useless and authors would need to submit updates to their add-on just to bump the `maxVersion` value.

Note: the current version of the theme as of writing (1.0.11, submitting an update soon) has `maxVersion` set to `39.*` in the install.rdf and AMO might be preferring install.rdf data over AMOs own compatibility data (because `data-is-compatible` is set to `false`).

**Comment by andymckay-limited-access** [comment]
@jvillalobos any advice?

**Comment by jvillalobos** [comment]
The compatibility info on AMO _should_ override what's in the manifest, since that what the developer has control over after the version has been uploaded. I don't know if complete themes are special-cased because they have strict compatibility set, or if this has anything to do with #2572.

**Comment by eviljeff** [comment]
This doesn't seem to be reproducible with the addon in the description any more.  If it's still reproducible on the new frontend then a new issue could be opened there instead.
