### ISSUE TITLE
[AMO-dev] Web-extension without ID blocks platforms selection at submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2586]
Steps to reproduce:
1. Pick a web-extension without ID set in the manifest.json
2. Submit that web-extension using https://addons-dev.allizom.org/en-US/developers/addon/submit/2

Expected results:
An ID is generated.

Actual results:
The platform selection is blocked. The submission process cannot be finalized.

Notes/Issues:
Verified on FF46(Win 7). Issue is reproducing on dev.
Screenshot for this issue: 
![2016-05-09_0833](https://cloud.githubusercontent.com/assets/15685960/15104438/0a7712d0-15c1-11e6-9bde-e71329081e5d.png)

Attaching the used web-extension.
[Unlimited-Free-VPN.zip](https://github.com/mozilla/addons-server/files/254356/Unlimited-Free-VPN.zip)

**Comment by andymckay** [comment]
I saw a couple of people reporting this with webextensions on prod, in the #webextensions channel.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
Screenshot for this issue:
![2016-05-10_0917](https://cloud.githubusercontent.com/assets/15685960/15137159/7e0749de-1690-11e6-8fcb-4f9460b2d4fb.png)
