### ISSUE TITLE
Move old discovery app to legacy_discovery

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2587]
To separate clearly the new disco pane code from the old stuff, move the current `discovery` app to `legacy_discovery`. Fixtures, models, templates, etc might need to be adjusted to the new app path.

**Comment by diox** [comment]
QA: please make sure discovery panel still works

**Comment by madalincm** [comment]
Verified as fixed in FF46(Win7) in addons-dev.allizom.org Discovery pane is working as expected.
