### ISSUE TITLE
Provision docker with a super creator

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#2593]
When starting a new Docker instance of AMO, the automated tests need a way to generate a [super creator](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#super-creation), I.E. a user with credentials to make POSTs to `/api/v3/accounts/super-create/`.

One possible solution is to introduce a management command that can be called like:

```
python manage.py newsupercreator
```

The script would:
- create a new user
- assign it to the `Accounts:SuperCreate` group
- tick the 'yes I accept' developer agreement box
- generate API credentials
- output credentials in JSON

**Comment by davehunt** [comment]
Hopefully the UI tests will be more stable once #3111 lands. Has there been any progress on this issue @EnTeQuAk? I'd like to get the tests dependent on logging in running, and revisit my work on a test to install an add-on, which IIRC is going to depend on an API user.

**Comment by EnTeQuAk** [comment]
there are no news on this issue yet but I think I should be able to tackle it this week to unblock you from this if that works for you. should not be too much work, just need to remember exactly what we talked about in London but I have written that down somewhere.

**Comment by EnTeQuAk** [comment]
Short update on this, I started working on it, aiming to finish this this week.

**Comment by muffinresearch** [comment]
> Short update on this, I started working on it, aiming to finish this this week.

@EnTeQuAk do you have something on this already in progress? What's the current status?

**Comment by mstriemer** [comment]
Since moving to Firefox Accounts for authentication we know have our own `python manage.py createsuperuser` command [1]. This could be updated to automatically do this or accept a parameter that would tell it to do this, then the initialize_docker script could be updated to pass the param.

[1] https://github.com/mozilla/addons-server/blob/820f00d2f261c296eff061530e7a727d69ae9217/src/olympia/users/management/commands/createsuperuser.py

**Comment by EnTeQuAk** [comment]
yeah, something like that was the plan, extending it and more importantly documenting it so this probably won't be too much work as far as I see. I'm planning to get to it Thu/Fri this week after the last bits and pieces being done on devhub landing pages.

**Comment by jrbenny35** [comment]
Hey is this still being worked on?

**Comment by EnTeQuAk** [comment]
Yes, this is now actively being worked on.
