### ISSUE TITLE
[AMO-dev] Update_url error for webextension submission 

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#2594]
**Steps to reproduce:**
1. Try to submit the attached web-extension on AMO-dev

**Expected results:**
The webextension is successfully submitted.

**Actual results:**
The webextension is not submitted because of the following error: The "update_url" property is not allowed.

**Additional notes:**
- This issue reproduces on Amo-production using Firefox 49.0a1 (2016-05-08) under Windows 10 64-bit.
- I was able to submit the same add-on on AMO-stage ( https://addons.allizom.org/en-US/firefox/addon/flash-video-downloader-icatest/ )
- Please see the attached screenshot for this issue:
![2016-05-09_1835](https://cloud.githubusercontent.com/assets/18114210/15118470/f719d228-1614-11e6-98cc-c4fc2a0c5747.png)
- I am attaching the web-extension:
[Flash-Video-Downloader.zip](https://github.com/mozilla/addons-server/files/255312/Flash-Video-Downloader.zip)

**Comment by andymckay** [comment]
This is by design, the `update_url` is not allowed, there might be bugs later that would alter this automatically for the user which would be nice. 

This verifies that mozilla/addons-linter#565 works and I'll link in #2579 for some karma.
