### ISSUE TITLE
Provide history for add-ons deleted and then uploaded again

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#2603]
I just had a case where a developer had various negative editor review comments on his review page, but then managed to delete and re-upload the add-on. This deleted all those negative review comments, which might be tactics to get a clean sheet and a more lenient reviewer.

I'm not sure there is much we can/should do, but is there a chance we can retain old review comments in some way?

**Comment by tofumatt** [comment]
Worth noting that web extensions have optional IDs (we'll generate one for them server-side if they aren't included), so while we can tell that an add-on is from the same developer, in the future of web extensions we won't have a way to tie together the old and new add-on together 100% reliably (though same name + author is obviously a pretty easy target).

**Comment by andymckay-limited-access** [comment]
This seems like a lot of effort for little gain.
