### ISSUE TITLE
Reviews number in the required add-ons section is hard to read

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2606]
**Steps to reproduce:**
1. Open the detail page of an add-on that has a required add-ons section: https://addons-dev.allizom.org/en-US/firefox/addon/tab-mix-plus/?src=hp-dl-featured

**Expected results:**
The review number is easy noticeable.

**Actual results:**
Reviews number is very hard to read.

**Notes/Issues:**
Verified in FF46(Win7) Issue can be reproduce din amo-dev, stage and production
Also the category is in a dark grey that is pretty hard to read too.
Screenshot for this issue:
![reviewnumber](https://cloud.githubusercontent.com/assets/15685441/15140561/5bc95588-16a4-11e6-848e-7bb3eaa83623.png)

**Comment by aelawson** [comment]
By "review number", do you mean the number of views in parentheses next to the star rating?

![reviews_number](https://cloud.githubusercontent.com/assets/2905514/15226403/85848138-1850-11e6-8ff6-989997278a91.png)

**Comment by madalincm** [comment]
@aelawson Yep that is the number I am talking about.

**Comment by tsl143** [comment]
Hi there,
I have made the changes locally, but I am unable to test .
When I do `docker-compose pull -d`
It gives 502 bad gateway.

**Comment by andymckay** [comment]
I think you might be blocked by #2596

**Comment by EnTeQuAk** [comment]
#2596 should be fixed with https://github.com/mozilla/addons-server/pull/2684 - once dockerhub build new images it should be fine.

**Comment by wagnerand** [comment]
We're going to redesign the desktop pages very soon, closing.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
