### ISSUE TITLE
Themes Homepage: unify "create your own theme" section

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2608]
See: https://github.com/mozilla/addons.mozilla.org-mod/issues/13

**Comment by eviljeff** [comment]
@tofumatt can you explain more about this issue so a contributor can look into it?

**Comment by wagnerand** [comment]
@designakt Would you mind adding some details what is needed to be done here?

**Comment by designakt** [comment]
This is a copy of a very old issue that got solved along the way with all the restyle changes and looks OK as it is now.
