### ISSUE TITLE
"+Add" Themes button is in the wrong side

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2615]
Steps to reproduce:
1. Load themes page https://addons-dev.allizom.org/en-US/firefox/themes/
2. Hover over any theme and observe the "+Add" button

Expected results:
The button is in the right side after the theme name.

Actual results:
The button is in the left side.

Notes/Issues:
Verified on FF46(Win7). Issue is reproduced on AMO-stage and dev.
Screenshot for this issue: 
![2016-05-11_1326](https://cloud.githubusercontent.com/assets/15685960/15178135/8e43dfa0-177c-11e6-802d-4a51e10b50d0.png)

**Comment by tofumatt** [comment]
This is intended behaviour; we're now moving the button below the text.

**Comment by ValentinaPC** [comment]
This intended behavior is causing an issue in theme details page:
Please see the screenshot: 
![2016-05-11_1635](https://cloud.githubusercontent.com/assets/15685960/15182694/9042202c-1796-11e6-9b61-5d926055e2c0.png)

@tofumatt : let me know if we should track this separately ?

**Comment by tofumatt** [comment]
Yes, please make that a separate issue and assign it to me.
