### ISSUE TITLE
A new-unapproved file for an approved add-on breaks the" View Listing" page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2624]
Steps to reproduce:
1. Submit an add-on in AMO-stage https://addons.allizom.org/en-US/developers/addon/submit/2 and approve it
2. Add a new file for that add-on (without approve) (i.e. https://addons.allizom.org/en-US/developers/addon/pinit-stage/versions/1701356)
3. Click the "View Listing" link

Expected results:
Add-on details page is loaded.

Actual results:
A 404 page is displayed.

Notes/Issues:
At least we can show the page to the add-on creator.
Verified on FF46(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Screencast for this issue: 
![add-on](https://cloud.githubusercontent.com/assets/15685960/15184485/0feb06a2-179e-11e6-8555-e5edb4ad2a6c.gif)

**Comment by andymckay-limited-access** [comment]
@eviljeff would you know anything about this, presumably the review status is causing a problem.

**Comment by wagnerand** [comment]
We should really do something about that edge case where a version has both reviewed and unreviewed files...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Once a version is approved, a new file cannot be added. (If the version is not approved, the new file button is present)
Postfix screencast: 
![no new file](https://cloud.githubusercontent.com/assets/15685960/15577266/7235c762-2364-11e6-8f0a-a76c15ab32bb.gif)
