### ISSUE TITLE
Show info message that if the validation output comes from addons-linter

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2627]
We have those little notification boxes in the preliminary validation result screen once you submit an add-on. Let's use those boxes to show the users a small info message like "Hey, we're trying out a new linting library, if there are any errors please report them here ..."

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
Postfix screenshot: 
![2016-06-01_1117_001](https://cloud.githubusercontent.com/assets/15685960/15702937/70ddf340-27eb-11e6-8f10-a8fe607e04ba.png)
