### ISSUE TITLE
Addon does not appear in My Favorites collection on addons-dev for some time after submission

### ISSUE THREAD

**Issue by stupchiy** [mozilla/addons-server#2629]
Looks like the same or related to #2442 . There is [an automated tests](https://github.com/stupchiy/Addon-Tests/blob/4ea76773b5d05be0856788cdb9bff2cb0caa2b9f/tests/desktop/test_collections.py#L52-L71), which is currently failing on https://addons-dev.allizom.org  due to the addon not appearing when expected, even manually refreshing the page doesn't show the add-on was added to that collection (details in https://github.com/mozilla/Addon-Tests/pull/837). 

Note that the test is passing on https://addons.allizom.org

**Comment by davehunt** [comment]
@stupchiy can you check again now that #2442 is resolved?

**Comment by andymckay-limited-access** [comment]
Marking as closed based on #2442, but please re-open if it still happens.

**Comment by stupchiy** [comment]
hey, sorry for the delay, I can confirm is working now, thanks!
