### ISSUE TITLE
Theme title is under [+Add] button in User Info page and not above

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2636]
Steps to reproduce:
1. Sign in to AMO-stage page https://addons.allizom.org/en-US/
2. Load User Info page for any user i.e. https://addons.allizom.org/en-US/firefox/user/MissTracee/
3. Hover over any theme

Expected results:
Theme button is under theme name.

Actual results:
Theme button is above theme name.

Notes/Issues:
Verified on FF46(Win 7). Issue is reproduced in AMO-stage and AMO-dev.
Screenshot for this issue: 
![2016-05-12_1306](https://cloud.githubusercontent.com/assets/15685960/15211177/73f43782-1842-11e6-89e5-6939c6525253.png)

**Comment by ValentinaPC** [comment]
@tofumatt : Also, theme install button does not work as expected, returning an error in the console. Will this also be fixed by this or we need to log an issue, separately?

**Comment by tofumatt** [comment]
If the install button is not working that is a separate and blocks release issue; please file it separately and assign to me.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshot: 
![themename](https://cloud.githubusercontent.com/assets/15685960/15214985/d0087144-1858-11e6-93c4-a78ebe9903cd.png)
