### ISSUE TITLE
Themes cannot be installed from User Profile page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2637]
Steps to reproduce:
1. Sign in to AMO-stage page https://addons.allizom.org/en-US/
2. Load User Info page for any user i.e. https://addons.allizom.org/en-US/firefox/user/MissTracee/
3. Try to install any theme listed there

Expected results:
Theme can be installed.

Actual results:
Theme cannot be installed.

Notes/Issues:
**Issue is not reproduced in any other themes pages.** A JS error is displayed in the console.
Verified on FF46(Win 7). Issue is reproducing in AMO-stage and AMO-dev.
Screenshot for this issue: 
![2016-05-12_1314](https://cloud.githubusercontent.com/assets/15685960/15211564/98ae2568-1844-11e6-8f7f-40fe16621465.png)

**Comment by tofumatt** [comment]
It appears the HTML for those sections varies from our usual HTML.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
Postfix screencast: 
![themeinstall](https://cloud.githubusercontent.com/assets/15685960/15215102/4ff708b6-1859-11e6-8eaa-8b0415b78f41.gif)

**Comment by ValentinaPC** [comment]
@tofumatt **This is now in AMO-prod** and also reproducible in AMO Homepage for Featured Themes section (fixed in AMO-dev).
Also the name and title are reversed in those sections.
Please see the screenshots:  
![user_profile](https://cloud.githubusercontent.com/assets/15685960/15241094/642ad392-18f6-11e6-916a-4a112541e253.png)
![homepage](https://cloud.githubusercontent.com/assets/15685960/15241096/6bf92aba-18f6-11e6-814d-588d1b65ad95.png)

**Comment by tofumatt** [comment]
The fix hasn't made it to AMO prod, I didn't realise the bug was on prod. I should have cherry picked this for the push, sorry.

It should be fixed next week.

- tofumatt

**Comment by tofumatt** [comment]
Sorry, this is fixed and verified on Dev, but it wasn't deployed to prod. But everything is fixed 😄

**Comment by ValentinaPC** [comment]
@tofumatt : The first impact between user and themes is from AMO homepage, not being able to install themes from there, made me reopen this issue. :smile:

**Comment by tofumatt** [comment]
Ah. On -dev the themes are installable, so it should be all good now. Again: it won't make it to prod until next push 😟
