### ISSUE TITLE
Search is not working in Themes "Flagged" queue from Editor Tools

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2641]
Steps to reproduce:
1. Sign in with an admin account in AMO-stage 
2. Load Editor Tools-Themes-Flagged queue https://addons.allizom.org/en-US/editors/themes/flagged
3. Make a search

Expected results:
Some results are listed.

Actual results:
No results are listed.

Notes/Issues:
Issue is NOT reproducing in Pending and Updates queues.
Verified on FF46(Win 7). Issue is only reproducing on AMO-stage.
Screencast for this issue: 
![search in editor t](https://cloud.githubusercontent.com/assets/15685960/15214695/3482b15e-1857-11e6-89cf-22237f3f9058.gif)

**Comment by andymckay-limited-access** [comment]
Let's recheck this in the triage next week to see if its occurring on prod. At the moment it does not occur on prod.

**Comment by eviljeff** [comment]
works for me on prod
