### ISSUE TITLE
After xpi file is uploaded Android checkbox is not active

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2642]
Steps to reproduce:

1.In AMO home page hover over “Tools”
2.Click on “Submit a New Add-on”
3.After submission page is loaded click on “Select a file...”
4.Upload a webextension for Android platform.

Expected results:
Android checkbox is active.

Actual results:
Android checkbox is not active.

Note/Issues:
Verified on FF49.0a1 (2016-05-11) (Win 7). This issue is reproducing in AMO-stage.
Screenshot to this issue: 
![animation](https://cloud.githubusercontent.com/assets/15885467/15214906/742fee24-1858-11e6-81c4-a599d53742f1.gif)

**Comment by cosminbadescuSV** [comment]
[AlbanianDictionary.zip](https://github.com/mozilla/addons-server/files/261457/AlbanianDictionary.zip)
Here is the webextension that I uploaded in the video

**Comment by EnTeQuAk** [comment]
info for qa once #2716 is merged: Android only supports WebExtensions from version 48.0 upwards and the checkbox should be disabled if `strict_min_version` and `strict_max_version` are set to before that, e.g

```json
  "applications": {
    "gecko": {
		"strict_min_version": "42.*",
		"strict_max_version": "47.*"
    }
  }
```

**Comment by cosminbadescuSV** [comment]
After Android option is checked and I move to step 3 of submission, I can check Firefox categories even if this was not selected. Is this intended?
Here is a video:
![checkbox](https://cloud.githubusercontent.com/assets/15885467/15472049/ce24dac8-2101-11e6-91f9-60515180c841.gif)

**Comment by EnTeQuAk** [comment]
it kindof is, I'm investigating this a bit more but at least code-wise the selected platforms aren't related to the compatible apps (firefox, android, seamonkey, etc) that you're allowed to select categories for. Which doesn't make sense to me at the moment but I think there's a reason, somewhere. I'll update this issue tomorrow when I find more :)
