### ISSUE TITLE
Get Firefox promo button appears three times in non-FX browsers

### ISSUE THREAD

**Issue by sevaan** [mozilla/addons-server#2645]
When viewing an add-on in a non-Firefox browser, the button to download Firefox appears three times, one on top of the other.

<img width="1231" alt="image 2016-05-11 at 9 53 34 am" src="https://cloud.githubusercontent.com/assets/473531/15216389/e4081ea8-1824-11e6-9faa-c43e0c136651.png">

**Comment by ValentinaPC** [comment]
This was already tracked in  #2195 . Thanks!
