### ISSUE TITLE
Remove fudge

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2653]
There's only 5 tests that use fudge in AMO. Could we make them use Mock and remove a library from AMO?

**Comment by EnTeQuAk** [comment]
I thought I added a issue for that already but it appears all I did was talking about it 😆 

👍

**Comment by andymckay** [comment]
I think @diox and @EnTeQuAk got this in London.

**Comment by diox** [comment]
Yeah, done in #2928
