### ISSUE TITLE
Duplicate add-on ID found when using curl, but OK through web page upload

### ISSUE THREAD

**Issue by brunosabin** [mozilla/addons-server#2657]
Using the curl command:

    curl https://addons.mozilla.org/api/v3/addons/@{51154b97-c607-43f0-ad88-dda01a32a1e3}/versions/10.3.10.25/ -g -XPUT --form 'upload=@npvverck.xpi' -H 'Authorization: JWT XXX-EDITED-XXX'

I get the output:

    {"error":"Duplicate add-on ID found."}

However, if I try to upload the very same XPI file through the URL https://addons.mozilla.org/en-US/developers/addon/creo-view-version-checker/ then I get a successful upload/signature.

We did create the addon entry to test signing in the ealry days of the new signing service and I wonder if we caused some confusion on the server side.

**Comment by eviljeff** [comment]
from our earlier email conversation, `https://addons.mozilla.org/api/v3/addons/{51154b97-c607-43f0-ad88-dda01a32a1e3}/versions/10.3.10.25/` (i.e. without the @) returns the same output.

**Comment by andymckay** [comment]
I've looked at the database and I can't see a reason why this should occur. @brunosabin can you run curl in verbose mode (redact your jwt stuff out of the output), perhaps there's something in there that I'm missing?

**Comment by brunosabin** [comment]
@andymckay here is the more verbose output from the curl command. Let me know whether I should also send you the rdf and xpi files if this can help. Thanks a lot for your patient assistance.

```
> curl -v https://addons.mozilla.org/api/v3/addons/@{51154b97-c607-43f0-ad88-dda01a32a1e3}/versions/10.3.10.25/ -g -XPUT --form 'upload=@npvverck-test.xpi' -H 'Authorization: JWT XXXXREMOVED_JWTXXXX'
* STATE: INIT => CONNECT handle 0x60005b3d0; line 1103 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying 54.69.215.101...
* STATE: CONNECT => WAITCONNECT handle 0x60005b3d0; line 1156 (connection #0)
* Connected to addons.mozilla.org (54.69.215.101) port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x60005b3d0; line 1253 (connection #0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x60005b3d0; line 1267 (connection #0)
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*        subject: businessCategory=Private Organization; jurisdictionC=US; jurisdictionST=California; serialNumber=C2543436; street=650 Castro St Ste 300; postalCode=94041; C=US; ST=California; L=Mountain View; O=Mozilla Foundation; CN=addons.mozilla.org
*        start date: Jul 31 00:00:00 2015 GMT
*        expire date: Sep 21 12:00:00 2017 GMT
*        subjectAltName: addons.mozilla.org matched
*        issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
*        SSL certificate verify ok.
* STATE: PROTOCONNECT => DO handle 0x60005b3d0; line 1288 (connection #0)
> PUT /api/v3/addons/@51154b97-c607-43f0-ad88-dda01a32a1e3/versions/10.3.10.25/ HTTP/1.1
> Host: addons.mozilla.org
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: JWT XXXXREMOVED_JWTXXXX
> Content-Length: 237124
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------98230454e17a2ea4
>
* STATE: DO => DO_DONE handle 0x60005b3d0; line 1350 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x60005b3d0; line 1477 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x60005b3d0; line 1487 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 100 Continue
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Allow: GET, POST, PUT, HEAD, OPTIONS
< Content-Security-Policy: script-src 'self' https://addons.mozilla.org https://www.paypalobjects.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://ssl.google-analytics.com https://addons.cdn.mozilla.net; default-src 'self'; img-src 'self' data: blob: https://www.paypal.com https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; object-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net; report-uri /__cspreport__
< Content-Type: application/json
< Date: Tue, 17 May 2016 21:21:12 GMT
* Server nginx is not blacklisted
< Server: nginx
< Set-Cookie: multidb_pin_writes=y; expires=Tue, 17-May-2016 21:21:27 GMT; Max-Age=15; Path=/
< Strict-Transport-Security: max-age=31536000
< Vary: X-Mobile, User-Agent
< X-Backend-Server: ip-172-31-42-218
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< Content-Length: 38
< Connection: keep-alive
<
* STATE: PERFORM => DONE handle 0x60005b3d0; line 1645 (connection #0)
* Curl_done
* Connection #0 to host addons.mozilla.org left intact
{"error":"Duplicate add-on ID found."}
```

**Comment by andymckay** [comment]
If you've got the xpi that wouldn't hurt. Thanks.

**Comment by brunosabin** [comment]
The XPI is 230K and you can get it from here:
https://dl.dropboxusercontent.com/u/49844234/npvverck-test.xpi

**Comment by andymckay-limited-access** [comment]
@EnTeQuAk have you had any insight into this? I couldn't spot anything.

**Comment by EnTeQuAk** [comment]
I can't find anything, at first I thought it was related to one of my changes regarding optional ids but I don't think it is. I also can't find any major difference in the API and the plain upload, both call `olympia.files.utils:parse_addon` the same way and thus `olympia.files.utils:check_xpi_info` which is the place we raise the error.

Maybe one of the cases in https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L531 is actually true for some reason?

**Comment by eviljeff** [comment]
> Maybe one of the cases in https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L531 is actually true for some reason?

Were you able to replicate it locally?

**Comment by EnTeQuAk** [comment]
no, unfortunately not. As said on IRC, I tried to come up with scenarios and test-cases but all worked as expected. I might try a few more things but for now I'm clueless.

**Comment by EnTeQuAk** [comment]
unfortunately I can't reproduce this properly locally and I don't see why this is happening. Is this still happening @brunosabin?

**Comment by brunosabin** [comment]
Hi @EnTeQuAk ,

I was away for a few days. Thanks for taking another look. I have tried once more with our next version (11.0.0.7) and I still get the same error.

This time, I attach to this issue a ZIP file containing the exact set of calls and variable values I use on my side. The "command_llines.txt" file will walk you through the steps I take and you should end up with the exact same error from any workstation (hopefully). Please give it a go and confirm you could reproduce it on your own machine.
Thanks for your patience.

[Mozilla_addon_Server_issue_2657.zip](https://github.com/mozilla/addons-server/files/371209/Mozilla_addon_Server_issue_2657.zip)

**Comment by andymckay** [comment]
1) your add-on is `{51154b97-c607-43f0-ad88-dda01a32a1e3}` as per line 7 of your install.rdf yet you are sending an add-on id of `@{51154b97-c607-43f0-ad88-dda01a32a1e3}` in command_lines.txt line 12. The values should be same, remove the @.

2) please try putting double quotes around the URL in the request,  for example `curl "https://addons.mozilla.org/api/v3/addons/{51154b97-c607-43f0-ad88-dda01a32a1e3}/versions/11.0.0.7/"`, you will note that we do this in the examples so that the string is not escaped by a space or a @ in the URL.

**Comment by andymckay** [comment]
3) please go to https://addons.mozilla.org/en-US/developers/addon/api/key/ and revoke and regenerate a new set of credentials and update the credentials you have stored.

**Comment by diox** [comment]
4) when using `curl`, be sure to use `-g`, otherwise it will try to parse the `{` and `}` as globbing patterns. I learned that the hard way recently.

**Comment by brunosabin** [comment]
@andymckay removing the spurious "@" from the ID on the curl command line fixed the issue.
Thanks a lot for spotting this.
I have revoked the credentials I had given you for testing too. Thanks for the reminder, though
@diox Thanks a lot for the tip about "-g". I was already using that argument, but it is those little details which end up wasting time.
Please close this issue as this was a user error.

**Comment by andymckay** [comment]
Good news, thanks @brunosabin.
