### ISSUE TITLE
Generate hash for cachebusting add-on icons instead of relying on modification date

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2659]
We cachebust add-on icons using the add-on last modification date. This means any modifications to the add-on will force clients to re-download the corresponding icon, even though it has not changed, which sucks for performance.

I implemented that in zamboni a while back and this commit could serve as inspiration: https://github.com/mozilla/zamboni/commit/7983195060f882c2a4cbeb82c883ca407f32c01c

**Comment by diox** [comment]
Technically not an API-only thing, though it would affect it. Removing API label.

**Comment by diox** [comment]
QA:
- URLs for existing icons should behave exactly like before: they should include a `modified={number}` bit that changes whenever the add-on is modified
- URLs for *new* icons should include a `modified={hash}` bit that does not change when the add-on is modified. It should only change when the icon itself is updated.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58 Win10x64

- 1st scenario:
 icon URL before add-on updates 
[https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-64.png?**modified=1519375853**](https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-64.png?modified=1519375853)
 icon URL after some updates applied to the add-on
[https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-64.png?**modified=1519376426**](https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-64.png?modified=1519376426)

- 2nd scenario:
new icon URL (stays the same when add-on details are updated)
[https://addons-dev-cdn.allizom.org/user-media/addon_icons/495/495305-64.png?**modified=8e891591**](https://addons-dev-cdn.allizom.org/user-media/addon_icons/495/495305-64.png?modified=8e891591)
new icon URL updated when add-on icon is changed
[https://addons-dev-cdn.allizom.org/user-media/addon_icons/495/495305-64.png?**modified=85241cf2**
](https://addons-dev-cdn.allizom.org/user-media/addon_icons/495/495305-64.png?modified=85241cf2)
