### ISSUE TITLE
Handle Personas in the search/detail API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2660]
We don't currently return Personas attributes in the search/detail API, making them a bit useless. This will require a bit of thinking.

A couple thoughts about the code:
- Do we add a different serializer and switch according to the Addon `type` ? Or do we add somehow the extra fields in the regular `AddonSerializer`/`ESAddonSerializer` ?
- In any case, it means we need to add the fields to ES, and then we need to make sure to create a fake `Persona` instance in the serializer as well, otherwise we'll cause a bunch of SQL queries in the search API

**Comment by andymckay** [comment]
Ideally this should not only be personas, but all add-on types.

**Comment by diox** [comment]
Other add-on types don't require much more work since they re-use the `Addon` model and simply are regular .xpis, Personas are a bit specific.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or add "needs no qa" label?
