### ISSUE TITLE
A reply of a review can be reported multiple times

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2673]
Steps to reproduce:
1. Load Reviews page for any add-on with reviews (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/read-it-later/reviews/?page=43)
2. Search for a review that has a reply
3. Report the reply

Expected results:
The review is reported. The review is marked as "Flagged for review" and cannot be reported again.

Actual results:
The "Flagged for review" mark turns into "Report review" after page refresh. The reply can be reported as many times as user wants.

Notes/Issues:
In Editor Tools is recorded the last report option.
**Is only reproducible for replies**.
Verified on FF46(Win 7). Reproducible in AMO-dev and stage.
Screencast for this issue: 
![report](https://cloud.githubusercontent.com/assets/15685960/15290587/2c983738-1b82-11e6-83cc-92866f6e0357.gif)

**Comment by eviljeff** [comment]
@jvillalobos this is still valid on new frontend but do we care?  I'm guessing it's just because we don't bother to expose flagging status for all reviews due to perf reasons.

**Comment by jvillalobos** [comment]
Doesn't seem important.
