### ISSUE TITLE
[AMO-dev] Permissions errors for webextension submission 

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#2681]
**Steps to reproduce:**
1. Try to submit one of the attached web-extensions on AMO-dev.

**Expected results:**
The webextension is successfully submitted.

**Actual results:**
The web-extension cannot be submitted because of a few errors.

**Additional notes:**
- This issue reproduces on AMO-dev using Firefox 49.0a1 (2016-05-16) under Windows 10 64-bit.
- I was able to submit the same add-on on AMO-stage ( https://addons.allizom.org/en-US/firefox/addon/my-dogs-new-tab/ )
- Please see the attached screenshot for this issue:
![2016-05-17_1059](https://cloud.githubusercontent.com/assets/18114210/15315479/8a54c154-1c20-11e6-9035-75089b746545.png)
![2016-05-17_1101](https://cloud.githubusercontent.com/assets/18114210/15315501/a2b92190-1c20-11e6-9e8f-76b810db2a4f.png)
- I am attaching the webextensions for which I’ve got these errors:
[WebExtensions.zip](https://github.com/mozilla/addons-server/files/267667/WebExtensions.zip)

**Comment by EnTeQuAk** [comment]
Well, most of them contain permissions that aren't allowed, e.g see https://github.com/mozilla/web-extension-manifest-schema/blob/master/src/manifest-schema.json#L88 for a list of permissions that we currently validate and expect (everything else is invalid, e.g `geolocation`). See also https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions for more details.

Closing as invalid but feel free to re-open if there are any questions or things not working.

**Comment by vasilicamihasca** [comment]
@EnTeQuAk: Now, I am able to submit the above attached webextensions without any errors. Which bug do you think that regressed this issue? Could be the linter update? Should I file a new bug for this regression?
![2016-05-20_1533](https://cloud.githubusercontent.com/assets/18114210/15427812/432f07d0-1ea0-11e6-813f-1546957e2c5c.png)

**Comment by EnTeQuAk** [comment]
all of them? that is weird, on dev and stage? Is the `addons-linter` flag active?

**Comment by andymckay** [comment]
This is to be expected, in mozilla/addons-linter#668 we conflated it down from 4 errors to 1. I also dropped it from an error down to a warning to match Firefox behaviour.

Whats interesting is the counting I see on dev though. Using one of those add-ons  it says "and 4 warnings", when I click through I get just the one warning. I'll open an issue about that.
