### ISSUE TITLE
New Homepage carousel promo: Games!

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2682]
(re-filed in the right repos, original was https://github.com/mozilla/addons-frontend/issues/372)

We'd like to promote a new collection on the Homepage. Could we please get this games collection placed in the [Disco Pane management tool](https://addons.mozilla.org/en-US/firefox/discovery/modules) by no later than **Tuesday, May 31**? 

------------------------------------

Overlay text (title, blurb, button):

**Games!**
Add more fun to your Firefox. Play dozens of games right from your browser—puzzles, classic arcade, action games, and more!
[Play now]

------------------------------------

Final URL will be:
https://addons.mozilla.org/firefox/collections/mozilla/games/

But please note that content curation is still in progress, so until I make Mozilla the "owner" of this collection, it lives here:
https://addons.mozilla.org/firefox/collections/sdevaney/games/

------------------------------------

And here's a generic background image suited for AMO's new-look design (created by pwalm)
![white-backgrounds-9](https://cloud.githubusercontent.com/assets/8496249/15234645/b64da7b4-1868-11e6-97e6-58dc94e11e47.png)

**Comment by diox** [comment]
@devaneymoz : currently we don't display a button for collections featured in the discovery pane (on the homepage or on about:addons), we only display it when we feature a single add-on.

**Comment by diox** [comment]
@devaneymoz : here is a screenshot with the background you gave on the homepage, and one with the default background. The new background looks a bit jarring, it's cut abruptly and I find the text difficult to read. Do you want to change it ? Or even skip it entirely and keep the default ?

New background:
![screen shot 2016-05-17 at 14 45 44](https://cloud.githubusercontent.com/assets/187006/15322690/86eec992-1c3e-11e6-87a0-e18859497ddd.png)

Default:
![screen shot 2016-05-17 at 14 47 07](https://cloud.githubusercontent.com/assets/187006/15322691/86ef8378-1c3e-11e6-9950-5df3261b5761.png)

**Comment by devaneymoz** [comment]
@dlox: thank you for re-filing this issue in the right spot!

@pwalm: dlox makes a good point about white design elements obscuring copy. It's hard to tell which of various generic background images you supplied this will also be the case. Any suggestions?

**Comment by pwalm** [comment]
@diox: Leave it default for now. Damn, that carousel background makes me crazy. I'll invest some time in making newer ones later this week.

**Comment by diox** [comment]
Ok, this is on dev and stage (using the mozilla/games collection) with the default background. Will land in prod tomorrow.

**Comment by madalincm** [comment]
I have checked dev and stage and this new banner is not displayed neither in the homepage or disco pane.
![promobanner](https://cloud.githubusercontent.com/assets/15685441/15385369/de33f5ee-1da9-11e6-9883-66a8b3b427cc.gif)

Also the https://addons.allizom.org/en-US/firefox/collections/mozilla/games/ is a 404. where should we see this new collection?

**Comment by diox** [comment]
The collection needs to be created (and filled) by this specific author and then the module must be added to the homepage in the discovery modules admin tool. I'll take care of that later today on dev and stage.

**Comment by madalincm** [comment]
I can see that the collection is created here: https://addons.mozilla.org/firefox/collections/mozilla/games/

But I can't see it in the banner, and I understood that it will be available in production today(well after yesterday push).  Did that change?

**Comment by diox** [comment]
It has not been enabled yet.

**Comment by diox** [comment]
@devaneymoz : the new carousel is available in prod over at https://addons.mozilla.org/en-US/firefox/discovery/modules

**Comment by devaneymoz** [comment]
Thank you, all! I see the collection in the carousel programming module. I am planning to publish the collection next week. I think we're good to go here.
