### ISSUE TITLE
Margin-bottom shouldn't be zero on home for home-header

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2691]
Caused by #2584 (https://github.com/mozilla/addons-server/pull/2584/files#r63528196)

Looks like:

<img width="1350" alt="screenshot 2016-05-17 15 12 43" src="https://cloud.githubusercontent.com/assets/90871/15325364/17d6495a-1c42-11e6-8ed9-bc58807a8c45.png">

Should look like:

<img width="1350" alt="screenshot 2016-05-17 15 13 09" src="https://cloud.githubusercontent.com/assets/90871/15325418/3d7f152e-1c42-11e6-8383-15a6c950f29b.png">

Fix incoming.

**Comment by vcarciu** [comment]
Verified as fixed :  
![nozero](https://cloud.githubusercontent.com/assets/1583842/15328274/f68bdc22-1c5c-11e6-9c3b-b991b873cbbb.gif)
