### ISSUE TITLE
get rid of the old getpersonas stuff

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#2695]
We have redirects set-up for the themes from getpersonas after the migration in 2013(?); we store the old personas_id in the database for those migrated themes; and still have to handle the image files slightly differently.  We should run a one-off migration to convert the files, rename, etc, as needed and remove the old cruft.

**Comment by muffinresearch** [comment]
@eviljeff maybe this is something that could be considered as part of the static themes migration?

**Comment by eviljeff** [comment]
In a way - _all_ personsa stuff is going to go after the -> static-theme migration, so that would include stuff from getpersonas too.

**Comment by eviljeff** [comment]
I'm going to close this now as we're going to remove everything related to personas at the same time.
