### ISSUE TITLE
Table olympia.frozen_addon doesnt exist error

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-server#2696]
Get this issue after updating latest image after #2596 

![screenshot from 2016-05-18 14 12 43](https://cloud.githubusercontent.com/assets/5318732/15353428/a4e0db48-1d06-11e6-8aa3-5cbc882b9e14.png)

**Comment by diox** [comment]
Super weird. 
- Have you run `make initialize_docker`? 
- Can you open a `dbshell` (I think you need to do `docker-compose run web manage.py dbshell`) and do `SHOW TABLES`, and tell us what you see ? I suspect something went wrong when creating the database tables.

**Comment by tsl143** [comment]
Got following errors

![screenshot from 2016-05-18 15 54 07](https://cloud.githubusercontent.com/assets/5318732/15355580/2c345782-1d11-11e6-8c4e-5f91b6689271.png)
![screenshot from 2016-05-18 15 54 29](https://cloud.githubusercontent.com/assets/5318732/15355579/2c311eb4-1d11-11e6-8cd1-7574f443d36d.png)
![screenshot from 2016-05-18 15 55 53](https://cloud.githubusercontent.com/assets/5318732/15355581/2c3898f6-1d11-11e6-807b-3d97b5c46289.png)

**Comment by davehunt** [comment]
I'm seeing the same as https://github.com/mozilla/addons-server/issues/2696#issuecomment-219986989 in Circle CI:
* Build: https://circleci.com/gh/davehunt/addons-server/34
* HTML report (with screenshots): https://circle-artifacts.com/gh/davehunt/addons-server/34/artifacts/0/tmp/circle-artifacts.7CzMDHU/results.html

**Comment by tofumatt** [comment]
I get this error after a recent pull (previously things were a-okay): https://gist.github.com/tofumatt/8eb2d87f297a7cc8eec7df8ac931fe6a

**Comment by vcarciu** [comment]
Can you please add "needs no qa" label if it is the case ?

**Comment by davehunt** [comment]
This is working for me in Circle CI now! Thanks @EnTeQuAk!
