### ISSUE TITLE
Statistics Broken - Daily Users Drops Unexpectedly

### ISSUE THREAD

**Issue by mustaim** [mozilla/addons-server#2700]
https://addons.mozilla.org/en-US/firefox/addon/time-restart/statistics/?last=30

As seen with Red graph, daily users drops steadily and does not show up correct Daily Users statistics.

It has been broken for more than a week.

**Comment by andymckay** [comment]
@jasonthomas looks like its happening on other add-ons like adblock too.

**Comment by jasonthomas** [comment]
I've back filled this data and re populated the statistics index. We are adding additional monitoring around statistics processing so we can capture these issues sooner in the future.

**Comment by mustaim** [comment]
Broken again.

Downloads do not count.
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/statistics/?last=30

**Comment by jasonthomas** [comment]
This is related to another issue, filed https://github.com/mozilla/addons-server/issues/2857
