### ISSUE TITLE
UI issues when expanding Category search filter

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2707]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/ and search for an addon
2.In search results list, expand the Category section from left side

Expected results:
Categories list is displayed without any UI issues

Actual results:
Categories list overlaps the "Work with" section

NOTES: not reproducible in production

Please see video for this bug : 
![uisearch](https://cloud.githubusercontent.com/assets/1583842/15398360/fef645f6-1deb-11e6-968e-0dae24e4b5e1.gif)

**Comment by muffinresearch** [comment]
This is a regression from the fix to #2503

**Comment by muffinresearch** [comment]
This is being cherry-picked for the 2016.05.19 push.

**Comment by vcarciu** [comment]
Verified as fixed : 
![cherrypick](https://cloud.githubusercontent.com/assets/1583842/15402600/b9be3bb2-1dfd-11e6-9cb8-601b5f93cf46.gif)
