### ISSUE TITLE
Different filters in Prod and Stage after collapsing the Category section

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2712]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

Steps to reproduce:
1.Perform a blank search on both Stage and Prod
2.Open the Category filter from left side

Expected results:
We should display same thing on Stage and Prod

Actual results:
Results are different(On Stage we have categories for all types of addons like Extensions, Complete themes, Search tools, etc. and on Stage we have only Extensions categories)

Please see video of the bug : 
![categ](https://cloud.githubusercontent.com/assets/1583842/15404860/23f00b8c-1e08-11e6-8a21-8babb92b14d9.gif)

**Comment by andymckay** [comment]
@krupa was going to test this, it could just be because of different types of add-ons that occur on stage and prod.

**Comment by andymckay-limited-access** [comment]
@krupa any luck with this?

**Comment by krupa** [comment]
I cannot reproduce this bug anymore. @vcarciu can you reopen if you see the issue again.

**Comment by vcarciu** [comment]
Now all types of addons are displayed on Production too
