### ISSUE TITLE
Use isSearchProviderInstalled for a better AMO experience

### ISSUE THREAD

**Issue by mkaply** [mozilla/addons-server#2714]
See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1249097

Currently if you go to install the Bing engine, we error out with a pretty unfriendly. We can detect if Bing is already installed via the isSearchProviderInstalled API.

We should use it and either disable the install button or provide a better message.

**Comment by andymckay** [comment]
Sorry, where is that API? https://dxr.mozilla.org/mozilla-central/search?q=isSearchProviderInstalled  returned nothing.

**Comment by mkaply** [comment]
http://mxr.mozilla.org/mozilla-central/source/dom/webidl/External.webidl#11

It's on window.external

That's odd that dxr didn't find it...

**Comment by muffinresearch** [comment]
Moved to https://github.com/mozilla/addons-frontend/issues/4256
