### ISSUE TITLE
Warning count in validation looks off

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2718]
Using one of the addons in #2681, I tried to validate an add-on. I got the expected permissions warning, so thats cool.

https://addons-dev.allizom.org/en-US/developers/upload/e522435432b14e0cb84eb2c3ef0688dc

![screenshot 2016-05-20 10 12 23](https://cloud.githubusercontent.com/assets/74699/15435875/b272d19e-1e73-11e6-8793-da0c718537bf.png)

But on the previous screen it said there were 4 warnings:

![screenshot 2016-05-20 10 15 36](https://cloud.githubusercontent.com/assets/74699/15435894/d10bc430-1e73-11e6-9609-d60df7346d1d.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7)
Postfix screenshots:
![step2-subm](https://cloud.githubusercontent.com/assets/15685960/15500735/c0c5e05a-21b2-11e6-89a8-3cc10897b689.png)
![report](https://cloud.githubusercontent.com/assets/15685960/15500744/cbeaf7b8-21b2-11e6-95f5-83e19e700edd.png)
