### ISSUE TITLE
Signing API is down

### ISSUE THREAD

**Issue by retorquere** [mozilla/addons-server#2720]
I can submit XPIs, but I'm not getting a signed status back even after waiting 10 minutes. Tried several times.

**Comment by minj** [comment]
I can confirm this.

I use a custom signing script.

API response for `pk=6d01fad6b9a64030af00b6c50c69db73`:
```
HTTP/1.1 200 OK
Allow: GET, POST, PUT, HEAD, OPTIONS
Content-Security-Policy: script-src 'self' https://addons.mozilla.org https://www.paypalobjects.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://ssl.google-analytics.com https://addons.cdn.mozilla.net; default-src 'self'; img-src 'self' data: blob: https://www.paypal.com https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; object-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net; report-uri /__cspreport__
Content-Type: application/json
Date: Sat, 21 May 2016 17:34:52 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
Vary: X-Mobile, User-Agent
X-Backend-Server: ip-172-31-9-12
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Length: 515
Connection: keep-alive

```
```json
{"guid":"{9d1f059c-cada-4111-9696-41a62d64e3ba}","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/%7B9d1f059c-cada-4111-9696-41a62d64e3ba%7D/versions/0.17.9.87/uploads/6d01fad6b9a64030af00b6c50c69db73/","files":[],"passed_review":false,"pk":"6d01fad6b9a64030af00b6c50c69db73","processed":false,"reviewed":false,"valid":false,"validation_results":null,"validation_url":"https://addons.mozilla.org/en-US/developers/upload/6d01fad6b9a64030af00b6c50c69db73","version":"0.17.9.87"}
```

[Validation results page](https://addons.mozilla.org/en-US/developers/upload/6d01fad6b9a64030af00b6c50c69db73) says this:
> #### General Tests
> *1 error, 0 warnings, 0 notices*
>
> **Error**
> **Error**: Validation task could not complete or completed with errors

**Comment by andymckay** [comment]
I was able to reproduce only intermittently. There were some rabbit MQ errors, but those always occur. The last 3 attempts by me all worked. Ops has had a look and hasn't seen anything. We'll keep an eye on this to see if we can see where its not working.

**Comment by minj** [comment]
Well, I still can't sign builds

**Comment by minj** [comment]
Apparently it worked 3 hours later :confused:

**Comment by retorquere** [comment]
I could for a while, and now it's gone again.

**Comment by serv-inc** [comment]
Has been working intermittently the last few days. Since yesterday, I was not able to submit  at all, neither using `jpm sign` nor the web interface. Maybe the same as https://github.com/mozilla/addons-server/issues/2699?

**Comment by andymckay** [comment]
I doubt its related to #2699 and more likely your specific add-on. Do you have a copy of your add-on somewhere? Also looks like you have some interesting unicode in your filename?

**Comment by andymckay** [comment]
(I also doubt its related to this bug)

**Comment by jasonthomas** [comment]
I believe this was a issue with how our rabbitmq clusters were configured. I've deployed a fix as part of our code deployment today. If you continue to have issues please reopen. Thank you for your patience.

**Comment by serv-inc** [comment]
@andymckay: thank you. Better to open a new issue? [@ytb-0.1.7.xpi.zip](https://github.com/mozilla/addons-server/files/285821/ytb-0.1.7.xpi.zip)

**Comment by andymckay** [comment]
@serv-inc looks like I was completely wrong and it probably was the issue with rabbitmq. Seems to be working for me and I can't spot anything wrong with the add-on that would cause it to fail. Can you retry please?

**Comment by serv-inc** [comment]
@andymckay: lhank you for having a look.  It just worked using `jpm` (just FYI: it failed twice using the web just before that).

**Comment by retorquere** [comment]
Same behavior again. I can submit, but I'm not getting a signed status back.

**Comment by muffinresearch** [comment]
> Same behavior again. I can submit, but I'm not getting a signed status back.

We were having problems with our task queues around this time which were resolved on the 11th. Could you retry and let us know if you continue to have any problems?

**Comment by retorquere** [comment]
I am currently not experiencing problems with the signing API.

**Comment by retorquere** [comment]
And it's down again. Is there a better place to report operational issues?

**Comment by muffinresearch** [comment]
> And it's down again. Is there a better place to report operational issues?

It's best to open a new issue instead with all the details so it can be investigated.

**Comment by muffinresearch** [comment]
@retorquere we are currently in the process of rolling out new code which could be related.

**Comment by retorquere** [comment]
I've opened a new issue but the behavior is the same as I reported in this issue. Does Mozilla have a status page where such maintenance is reported? How long is the code rollout expected to affect signing?
