### ISSUE TITLE
Accept ZIP files

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2727]
Supports #2579.

The Chrome web store actually wants `.zip` files, and that's all an XPI is, so let's allow `.zip` uploads for web extensions.

**Comment by wagnerand** [comment]
What keeps us from allowing this for traditional extensions as well?

**Comment by tofumatt** [comment]
I don't know, so I'm happy to allow traditional ones to be zips as well... provided it's no extra work 😄

**Comment by wagnerand** [comment]
I presume it might be extra work to limit it to webextensions 😆

**Comment by EnTeQuAk** [comment]
Does firefox allow loading extensions with `.zip`? Could this mess up our signing somehow (tbh, I have absolutely no idea how that works exactly so I'm just throwing around ideas)

**Comment by tofumatt** [comment]
I assume not, but if not we can just rename the file, I assume. To accept a CRX we’d need to remove the header bit with the public key in it… so doing some preprocessing on things that aren’t `.zip` files seems like an okay plan to me.

**Comment by tofumatt** [comment]
@EnTeQuAk I just tested installing a `.zip` file in `about:debugging` and it installed without issue. Installing one outside that resulted in a signing error but I assume it'd install otherwise (you get the signing error with XPIs too).

**Comment by EnTeQuAk** [comment]
that's nice :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshot: 
![zip](https://cloud.githubusercontent.com/assets/15685960/15669154/7751fbf0-2727-11e6-8d26-f35982048470.png)

**Comment by vcarciu** [comment]
We verified with many edge cases , including listed and unlisted addons, webextensions, new files and versions as ZIPs and everything looks fine.

Also , versioncheck and updates worked when used ZIP files.

Marking bug as fixed and any new issues will be logged separately .
