### ISSUE TITLE
Make fewer redirects when downloading files

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2731]
- Click on "Add to Firefox" button for Ublock Origin on the homepage 
- This triggers a request to https://addons.mozilla.org/firefox/downloads/latest/607454/addon-607454-latest.xpi?src=hp-btn-promo
-  Which is a 301 to https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/addon-607454-latest.xpi?src=hp-btn-promo
-  Which is a 302 to https://addons.mozilla.org/firefox/downloads/file/432957/ublock_origin-1.7.0-sm+tb+fx+an.xpi?src=hp-btn-promo
-  Which is a 302 to https://addons.cdn.mozilla.net/user-media/addons/607454/ublock_origin-1.7.0-sm+tb+fx+an.xpi?filehash=sha256%3A6df84d4886bc2e0b70b97c08be8e50943526f3ab8353c7e14960e5a2c27cb33a
-  Which is a 200, yay! It has Content-Length, Last-Modified, Expires, Cache-Control set, so that's good (though it's set to expire in only 24 hours)

That's way too many useless redirects, impacting performance needlessly.

**Comment by eviljeff** [comment]
Would ideal be:
"Add to Firefox" be a request to: https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/addon-607454-latest.xpi?src=hp-btn-promo
then 302 to https://addons.cdn.mozilla.net/user-media/addons/607454/ublock_origin-1.7.0-sm+tb+fx+an.xpi?filehash=sha256%3A6df84d4886bc2e0b70b97c08be8e50943526f3ab8353c7e14960e5a2c27cb33a ?

**Comment by diox** [comment]
Maybe even to the CDN one directly if it's a public add-on. Going through a django view for the download is useful if the add-on or the file is disabled (because only reviewers can access it) but for the public pages we might was well use the final URL directly IMHO.

**Comment by eviljeff** [comment]
I thought maybe there was a decision to have the link be /latest/ so people could link to it?  Also we might need to strip (and count) the `src=` first before it goes to the CDN.

**Comment by diox** [comment]
AFAIK counting does not happen in the view. We could still link to `latest` but install using the real link or something.
