### ISSUE TITLE
Validation hanging in Docker

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2738]
Updated to the most recent docker images and I'm getting validation that hangs (and eventually times out):

![may-24-2016 19-00-35](https://cloud.githubusercontent.com/assets/90871/15522629/e08df056-21e1-11e6-8c21-4a94c6a88f5e.gif)

Eventually I get:

<img width="782" alt="screenshot 2016-05-24 19 02 25" src="https://cloud.githubusercontent.com/assets/90871/15522669/1702cc92-21e2-11e6-87df-dd52b4feab35.png">

What logs should I look at to see what's up with this?

**Comment by EnTeQuAk** [comment]
you chould check everything in `logs/` and see if you can find anything suspicious. Maybe check again if everything's up with `docker-compose ps`. Does this happen to all add-ons you're trying to submit?

**Comment by tofumatt** [comment]
Yeah I looked in the logs but saw nothing, just a bunch of requests to the json url it checks when updating. Anything worth looking for in logs in particluar?

The worker is up in docker ps. Seems to happen with any add-on, I'll try a few more and report back.

- tofumatt

**Comment by tofumatt** [comment]
```
worker_1        | 2016-05-25 16:13:27,130 INFO spawned: 'olympia' with pid 106
worker_1        | 2016-05-25 16:13:28,135 INFO success: olympia entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
worker_1        | 2016-05-25 16:13:34,668 INFO exited: olympia (exit status 1; not expected)
worker_1        | 2016-05-25 16:13:35,675 INFO spawned: 'olympia' with pid 113
worker_1        | 2016-05-25 16:13:36,677 INFO success: olympia entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
worker_1        | 2016-05-25 16:13:46,956 INFO exited: olympia (exit status 1; not expected)
worker_1        | 2016-05-25 16:13:46,969 INFO spawned: 'olympia' with pid 120
worker_1        | 2016-05-25 16:13:47,975 INFO success: olympia entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
worker_1        | 2016-05-25 16:13:55,905 INFO exited: olympia (exit status 1; not expected)
worker_1        | 2016-05-25 16:13:56,911 INFO spawned: 'olympia' with pid 127
worker_1        | 2016-05-25 16:13:57,914 INFO success: olympia entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

I see the worker constantly restarting, don't know if that's related.

**Comment by EnTeQuAk** [comment]
just to update this ticket, what we noticed chatting in IRC is that @tofumatt isn't using the https://github.com/mozilla/addons-server/blob/master/scripts/start-docker.sh script as an entrypoint which downcasts permissions and runs supervisor as a non-root user.

We need to have processes running as non-root so this is the specific issue here.

**Comment by EnTeQuAk** [comment]
@tofumatt is this still a problem or more like a problem of not using correct permissions for the processes because of docker for mac?

**Comment by tofumatt** [comment]
I think it is related to the general Docker for Mac permissions problems. I went back to using `docker-toolkit`/VirtualBox because Docker for Mac was too rough around the edges (a true beta!)

**Comment by EnTeQuAk** [comment]
Is this still a problem now with the stable new docker for mac releases and everything?

**Comment by tofumatt** [comment]
Oops, no this is all good.

- tofumatt
