### ISSUE TITLE
Small issue at hover for "Next" navigation item in Search Tools pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2742]
Steps to reproduce:
1. Load AMO-stage Search Tools page 
2. Navigate to page 100: https://addons.allizom.org/en-US/firefox/search-tools/?page=100
3. Hover over "Next"

Expected results:
There are no display issues.

Actual results:
There is a small display issue.

Notes/Issues:
Reproducible in all AMO pages where user can navigate over a 3 digit page number. (i.e. themes page -> https://addons.allizom.org/en-US/firefox/themes/sports?sort=created&page=733)
Verified on FF46(Win 7). Issue is reproducing on AMO-stage, dev and production.
Screenshot for this issue: 
![2016-05-25_1248](https://cloud.githubusercontent.com/assets/15685960/15536295/6c84dd9e-2279-11e6-84c8-0d79591dc372.png)

**Comment by wagnerand** [comment]
It looks like this `Paginator` in src/olympia/amo/helpers.py needs to be updated.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
