### ISSUE TITLE
AMO Homepage contains extra HTML that is completely unused

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2743]
The style refresh removed the pagination for Featured Extensions, Up & Coming Extensions and Featured Themes on the homepage: that's good, it was probably not very useful.

However the extra pages for these sections are still present in the HTML, hidden, waiting to be displayed by JavaScript. With the removal of the pagination link these extra sections are just a waste of bandwidth, inflating the size of the HTML and causing us to load up to 50 extra images we don't need.

We'd gain a lot in bandwidth and perf by removing all that extra cruft. Might also want to simplify the view code with it.

**Comment by diox** [comment]
Same issue for category landing pages.

3 things need to be done to fix it cleanly:
- In the views, slice the querysets down to the exact number of items needed (6 instead of 18 in the case of the homepage)
- In the jinja helpers (`addon_grid`, `featured_grid`, `impala_persona_grid`, `collection_grid`, maybe others), pass the queryset directly instead of paginating it
- In the templates used by those helpers, don't loop on pages, use the queryset directly.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or add "needs no qa " label?

**Comment by diox** [comment]
I thought I had added some QA instructions...

Please just check that the homepage and category landing pages still display correctly.

**Comment by vcarciu** [comment]
@diox : Sorry , I saw that you added steps in #2744

**Comment by diox** [comment]
Ah yeah, I should have added them here and not on the pull request.

**Comment by vcarciu** [comment]
Verified as fixed
