### ISSUE TITLE
Set long expires for buttons.js and jsi18n.js

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2745]
All our pages depend on those 2 little pieces of javascript (Actual language and app in the URL might differ, obviously):
- /en-US/firefox/addons/buttons.js
- /en-US/firefox/jsi18n.js

Those are dynamic because they serve translated content. Since the language and app is already in the URL, and they are called with a cachebuster querystring, so we should be able to return caching headers so that browsers cache them for a very long time. We currently don't, that's a waste of bandwidth, browser are making unnecessary network requests for them on every page (even if it's just to get a 304).

**Comment by diox** [comment]
(Note: jsi18n.js does have caching headers set, but just for a week. We can increase that. In addition, we should load it from the CDN directly instead of loading it from `/`, forcing a redirect to the CDN)

**Comment by muffinresearch** [comment]
See also #1561

**Comment by madalincm** [comment]
Please add some steps to reproduce or add the "needs no qa" label if no qa is needed.

**Comment by diox** [comment]
Both scripts are now served from CDN directly, with the cachebusting string included, and set long expires/cache-control headers.

![caching](https://cloud.githubusercontent.com/assets/187006/15574087/9eccfc46-234b-11e6-98a4-96cef3136a9a.png)
