### ISSUE TITLE
Changing a field in the default locale of the listing should update all non-changed locales

### ISSUE THREAD

**Issue by Quicksaver** [mozilla/addons-server#2748]
Six months ago I changed the homepage of my add-ons, I changed only the en-US locale as I thought the change would propagate to other locales since that field is unchanged in all other locales. Today I spent close to half an hour manually updating every single non-default (non en-US) locale to the new url because they all kept the old url since then.

**Comment by diox** [comment]
Localized fields should fall back to the translation in the default locale for the add-on if it exists, if not it will pick the translation in en-US. What is/was the default locale for your add-on ?

**Comment by Quicksaver** [comment]
Sorry, I updated the original comment but I Iguess it was too late.

**New** localizations do fall back to the default locale's string. But apparently, existing localizations will not be updated if you modify the default locale.

**Comment by Quicksaver** [comment]
And I forgot to answer your question (too many things today), en-US. :)

**Comment by diox** [comment]
All translations do fall back to the translation in the default locale if a translation is not found in the current locale.

My guess is that in your case, translations already existed - even if the value was the same as the en-US one. That is, before changing the homepage you had something like:
- [Translation for homepage in en-US: http://old.homepage.example.com/]
- [Translation for homepage in fr: http://old.homepage.example.com/]
- [Translation for homepage in de: http://old.homepage.example.com/]

When you changed the en-US translation, you still had the old ones set to the old value. I'm not sure why this would happen (and that would be a bug), I would need to see the add-on before the changes to verify that my hunch is correct...

**Comment by Quicksaver** [comment]
Hmm, this is extremely easy to reproduce for me:
1 - Tested using Omnibar Plus - https://addons.mozilla.org/developers/addon/omnibar-plus/, has only en-US, with homepage set to ```https://github.com/Quicksaver/Omnibar-Plus/issues```
2 - Created new pt-PT locale, it automatically switches to it
3 - Clicked "Edit" on add-on details and saved changes (even though I didn't actually change anything)
4 - Switch back to en-US
5 - Edit add-on details, change homepage to ```https://github.com/Quicksaver/Omnibar-Plus```, saved changes
6 - Switch back to pt-PT, homepage still reads ```https://github.com/Quicksaver/Omnibar-Plus/issues```

**Comment by Quicksaver** [comment]
That was to say, I believe your hunch is correct, it is saving the homepage string (possibly other ones? I'm only testing the homepage string) specifically to each locale, even though it is unchanged from the default locale.

**Comment by diox** [comment]
Thanks for those steps to reproduce. I can't promise a fix soon (AMO devhub is quite the spaghetti code mess) but I'll look into it when I have the time.
