### ISSUE TITLE
Limit blocked review pages to 3 per reviewer

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#2749]
To prevent reviewers from accidentally (or intentionally) blocking too many review pages for others, we should limit how many they can have blocked.

If a reviewer has 3 review pages already opened and opens a fourth one, a message should appear on the fourth one indicating that there are already 3 review pages open and one of them needs to be closed for this one to be marked as blocked. We can reuse the style of the "this page was opened by another reviewer" message.

CC @eviljeff @wagnerand @kewisch

**Comment by wagnerand** [comment]
Do we want to limit this feature to the "Limited Reviewers" group?

**Comment by andymckay** [comment]
This does seem like adding in more features into the reviewer pages, is this something we really need?

**Comment by jvillalobos** [comment]
> Do we want to limit this feature to the "Limited Reviewers" group?

I don't think that's necessary.

> This does seem like adding in more features into the reviewer pages, is this something we really need?

Yes. This kind of activity is blocking other reviewers from being effective.

**Comment by wagnerand** [comment]
> I don't think that's necessary.

But I think it should not apply to admins, or rather the "Staff" group.

**Comment by jvillalobos** [comment]
> But I think it should not apply to admins, or rather the "Staff" group.

If it's easy to do, sure, but I don't want to make this more complicated than necessary.

**Comment by ValentinaPC** [comment]
@wagnerand : How can I could check this on Editor Tools, without an admin account? Thanks!

**Comment by eviljeff** [comment]
Being in the 'staff' group should be sufficient.

**Comment by ValentinaPC** [comment]
Verified as fixed in AMO-dev FF46(Win 7).
Postfix screenshot:
![limit_locked](https://cloud.githubusercontent.com/assets/15685960/15749157/1d2cef44-28ea-11e6-9a9a-75bdf733ca95.png)
