### ISSUE TITLE
Update heading translation on discovery API

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#2752]
Since the description includes raw HTML it would be good to get raw HTML for the heading as well. It would be ideal for the add-on name to be inserted into the translation already but we can talk about that.

We will be escaping this with DOM purify so as long as we get HTML that should be good.

`Block ads {start_sub_heading}with {addon_name}{end_sub_heading}`

Should instead be:

`Block ads <span>with Adblock Plus</span>`

Or (if adding the name in isn't going to work/is too hard):

`Block ads <span>with %(addon)s</span>`

**Comment by diox** [comment]
I can return HTML yeah ; the `{start_sub_heading}` was something we came up with @muffinresearch to avoid HTML and keep things client-agnostic, but you're right that it's inconsistent with the description. If you prefer it that way I'll change it.

I can include the name in there, it should not be a problem. In that case, do you still need the add-on `name` to be returned as well ?

**Comment by mstriemer** [comment]
I'm not sure if we're currently using `name` directly but I could see us including it in some of our own translations like `Icon for %(addon)s` or `Install %(addon)s` so we should probably keep it.
