### ISSUE TITLE
Bad URL pattern for blocklists.json

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#2755]
See https://github.com/mozilla/addons-server/blob/e51450b/src/olympia/blocklist/urls.py#L10 - the regular expression allows requesting this content as https://addons.mozilla.org/blocked/blocklists.json.html or even https://addons.mozilla.org/blocked/blocklistsxjson. I don't think that this is intended, it should really be `'^blocklists\.json$'`.

**Comment by diox** [comment]
Good catch, I missed that when reviewing that commit. /cc @Natim

**Comment by diox** [comment]
Other instances of this issue:
- in `src/olympia/zadmin/urls.py`:
  - `url('^models/(?P<app_id>.+)/(?P<model_id>.+)/search.json$',`
- in `src/olympia/amo/urls.py`:
  - `url('^robots.txt$', views.robots, name='robots.txt'),`
  - `url('^contribute.json$', views.contribute, name='contribute.json'),`
  - `url('^opensearch.xml$', 'olympia.legacy_api.views.render_xml',`
- in `src/olympia/urls.py`:
  - `url('^jsi18n.js$', cache_page(60 * 60 * 24 * 7)(javascript_catalog),`
  -  `url('^statistics/events-(?P<start>\d{8})-(?P<end>\d{8}).json$',`
- in `src/olympia/devhub/urls.py`:
 - `url('^file/(?P<file_id>[^/]+)/validation.json$',`
 - `url('^validation-result/(?P<result_id>\d+).json$',`
- in `src/olympia/pages/urls.py`:
  - url('^google1f3e37b7351799a5.html$',`

**Comment by EnTeQuAk** [comment]
Some more (probably not too bad):

* in  `src/olympia/amo/urls.py`:
 * `url('^monitor(.json)?$', never_cache(views.monitor),`

I can't find more occurences that aren't already in your list.

**Comment by Natim** [comment]
I also found:

- in ``src/olympia/zadmin/urls.py``
  - url(r'^validation/notify/syntax\.json$', ...)

**Comment by diox** [comment]
Thanks, I merged #2758 which should have taken care of the ones we found.

**Comment by ValentinaPC** [comment]
Please write some STR for this or add the label "needs no qa". Thanks!

**Comment by Natim** [comment]
Do you have some documentation about what to describe in a STR? I am not familiar with the term.

**Comment by ValentinaPC** [comment]
@Natim: We use "STR" as an acronym for "steps to reproduce" .

**Comment by Natim** [comment]
Ok so basically:

- https://addons.mozilla.org/blocked/blocklists.json.html
- https://addons.mozilla.org/blocked/blocklistsxjson

Should now returns 404 after this patch have been applied.
They are currently returning the same response as https://addons.mozilla.org/blocked/blocklists.json

**Comment by Natim** [comment]
Also in the URL listed before, the . in front of the extension could be replace by any other characters.

**Comment by ValentinaPC** [comment]
@Natim : Thanks!

Verified this on AMO-dev (https://addons-dev.allizom.org/) using FF46(Win 7)
The following pages:
-  https://addons-dev.allizom.org/blocked/blocklists.json.html
-  https://addons-dev.allizom.org/en-US/firefox/blocked/blocklistsxjson

Return a 404 page.
Postfix screenshots: 
![1](https://cloud.githubusercontent.com/assets/15685960/15575329/e906c904-235a-11e6-9561-63c486de282f.png)
![2](https://cloud.githubusercontent.com/assets/15685960/15575335/ed8d6082-235a-11e6-91f7-234a35619234.png)
