### ISSUE TITLE
Chars are pasted RTL in filter field from Deleted Themes - Editor Tools page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2760]
Steps to reproduce:
1. Sign in to AMO-stage with an admin account
2. Go to Editor Tools - Themes - Logs - Deleted (https://addons.allizom.org/en-US/editors/themes/logs/deleted/?start=2011-05-01&end=&search=)
3. Paste an e-mail from the list into the searching field

Expected results:
The email is pasted as copied.

Actual results:
The e-mail is pasted with the chars mixed up (I think it is a RTL mix).

Notes/Issues:
The e-mail selected from that page is pasted RTL anywhere you chose to past it.
Verified on FF46(Win 7). Reproducing on AMO-stage and dev.
Screencast for this funny thing: 
![mix](https://cloud.githubusercontent.com/assets/15685960/15571293/ab26f05e-2342-11e6-96f4-319f9fa1f746.gif)

**Comment by andymckay-limited-access** [comment]
There's a jinja filter that changes the DOM to obfuscate the emails so when you copy and paste it you get it in a weird order. There's no reason to do that in the editor tools though.

**Comment by eviljeff** [comment]
static themes now use the standard addon log, so the theme log is deprecated (and will be removed at some point, I suppose)
