### ISSUE TITLE
Do not display "Install anyway " button for incompatible addons

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2764]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

Steps to reproduce:
1.Find an addon incompatible with your FF version (https://addons.allizom.org/en-US/firefox/addon/noscript/?src=cb-dl-users - incompatible with 46)
2.Press the greyed out "Add to firefox" button

Expected results:
Nothing happens

Actual results:
A pop-up window containing the "Install anyway" active button is displayed. This is confusing because even if you press this button, the "not compatible" message is displayed

Please see video for this bug : 
![anyway](https://cloud.githubusercontent.com/assets/1583842/15577954/3b29027c-2367-11e6-9082-eaaa5eb29af7.gif)

**Comment by apoorvaeternity** [comment]
@eviljeff Shall I look into this? I just have to remove the button.

**Comment by eviljeff** [comment]
@jvillalobos do we want to make this change?

**Comment by apoorvaeternity** [comment]
@eviljeff @jvillalobos If the add-on is not going to work after downloading there is no point in downloading it. It's just a waste of the users internet bandwidth.

**Comment by jvillalobos** [comment]
There are ways to deactivate compatibility testing in Firefox, which is why we support this flow. Additionally, we're making some changes to #5482 that would help direct users to compatible versions.
