### ISSUE TITLE
Active install button for a non compatible addon

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2766]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

Steps to reproduce:
1.On your FF 46, go to https://addons.allizom.org/en-US/firefox/addon/download-statusbar/?src=cb-dl-users 
2.Observe the "Add to Firefox" button

Expected results:
The button should be inactive since the addon is not compatible with FF46

Actual results:
The button is active

Please see video for this bug : 
http://screencast.com/t/uAUTUEt3

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
