### ISSUE TITLE
Show column info for messages in full validation report when using linter

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2769]
As @andymckay mentioned in https://github.com/mozilla/addons-linter/issues/707#issuecomment-221914075, if the same error occurs multiple times on the same line, we show the error and line but not column number, making it look like the error is being shown more than once. (https://github.com/mozilla/addons-linter/issues/707)

We should show line _and_ column info; it's already available from the linter, so the data just needs to be grabbed and shown on AMO.

**Comment by EnTeQuAk** [comment]
amo-validator seems to also output the column numbers so this is something both support and we don't seem to do ugly workarounds.

**Comment by andymckay-limited-access** [comment]
I confess I had a quick look and couldn't spot where the line number was
added. I feel dumb, can someone throw me a clue stick.

On Thu, May 26, 2016 at 9:31 AM, Christopher Grebs <notifications@github.com

**Comment by EnTeQuAk** [comment]
It could be https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/validator.js#L314 and the following lines, maybe.

**Comment by vasilicamihasca** [comment]
Verified as fixed on Amo-dev using  Firefox 49.0a1 under Windows 10 64-bit. The column number is successfully displayed for each warning.
Postfix screenshot: 
![123](https://cloud.githubusercontent.com/assets/18114210/15602660/402ac15a-23ff-11e6-8185-c909f96d044b.jpg)
