### ISSUE TITLE
List the top 100 add-ons

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2774]
This is similar to arewee10syet.com, but now we can do this pretty easily, but just looping through the add-ons with the most users and listing out their status. It won't include unlisted add-ons since they don't have a user count on AMO.

Here's a terribly highly inaccurate mockup:

![image03](https://cloud.githubusercontent.com/assets/74699/15584357/223ebcd0-232f-11e6-9cc9-ca4a1c668e6f.png)

Because other developers might want to look up an add-on, I was thinking a simple "type your add-on id" to filter down by a specific add-on would help.

At this point the page should list the state mentioned on #2770

**Comment by andymckay** [comment]
Part of me is wondering if this is worth it. We communicate to the add-on developers on their dev hub page and we'll conflate this with the data in #2790. To benefit doing as little as possible I say, let's drop this.

**Comment by diox** [comment]
#2790 should help do this if we ever want to do it (since we can sort by number of users, or downloads/hotness whatever while exposing e10s status)
