### ISSUE TITLE
Populate the e10s state

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2775]
In issue #2772 we calculate the e10s state on submission. As cool as that is, it won't be present for currently uploaded add-ons. We need to do this for all the add-ons that have been uploaded and we'll need a command to run through them and populate that.

Supports #2770

**Comment by diox** [comment]
FWIW, on stage:
- The command ran on 29198 *listed* extensions (#2864 has not landed on stage yet)
- It succeeded for 17373 of them (the rest are probably disabled, rejected, etc)
- It found 83 compatible old-style extensions and 300 web-extensions. The compatibility for the remaining 16990 was set to "unknown".
