### ISSUE TITLE
Spacer Gif URL is needed for Personas Plus Add-on

### ISSUE THREAD

**Issue by derinb** [mozilla/addons-server#2776]
For a bug fix commit of Personas Plus add-on, we need a spacer gif located on AMO servers.
https://github.com/mozilla/personas-plus/pull/18

It is set as:

**https://addons.mozilla.org/static/img/blank.gif**

If there is already 1x1 transparent spacer of blank gif, please let us know the URL so we can change accordingly.

Example gif files on Wikipedia from which you may want to grab the transparent files
https://en.wikipedia.org/wiki/Spacer_GIF
https://commons.wikimedia.org/wiki/File:Blank.gif
https://upload.wikimedia.org/wikipedia/commons/c/c0/Blank.gif

Related Bugzilla Bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=556334

**Comment by andymckay** [comment]
This seems terribly wrong on a few levels and something we shouldn't be adding. Its not clear to me from https://bugzilla.mozilla.org/show_bug.cgi?id=556334 why you'd need this.

**Comment by derinb** [comment]
Thanks Andy,

As of now, **data:uri** used if user does not want to specify header and footer images for Custom Persona via Personas Plus add-on. Simply **data:uri** break Custom Persona.

I know the bug is RESOLVED FIXED but it is not reliable. You can also install Personas Plus and try yourself. chrome:// and resource:// URIs also are not reliable.

Light Weight Theme Manager simply asks for a HTTP or HTTPS url. Because it is SSL and AMO image, I hope it will not be an issue in common sense.

I did not try file:// uri workaround but probably it will also fail. Or it is prone to bugs because if file:// uri is used then user may delete the file from her system and issues may happen.

Let me know if you have any other suggestion please.

**Comment by mkaply** [comment]
Unfortunately this is an artifact of getpersonas.com that was not moved to AMO:

http://getpersonas.com/static/img/blank.gif

I agree it's not the most elegant solution. I'll see if there's a better way.

**Comment by wagnerand** [comment]
👍 on another solution. I asked for STR on how the reproduce the issue https://github.com/mozilla/personas-plus/pull/18 and this is supposed to fix.

**Comment by wagnerand** [comment]
This is not needed.
