### ISSUE TITLE
Signing fails if GUID case changes

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2787]
https://addons.mozilla.org/en-US/firefox/addon/steam-activity-filter/versions/1.4.0 changed its ID from `@steamactivityfilter` to `@SteamActivityFilter`, which somehow broke signature.

1.4.0 is not correctly signed.

The author uploaded 1.4.0-1 with a lower-case ID again and that worked just fine.

**Comment by wagnerand** [comment]
Adding @mstriemer and @diox.

**Comment by wagnerand** [comment]
It sounds like a blocker to me. Feel free to correct me!

**Comment by andymckay** [comment]
I was able to reproduce adding a new version by not only changing the case, but changing the add-on id completely. That was using the developer hub.

I agree this is a release blocker and needs to be fixed.

**Comment by mstriemer** [comment]
It looks like the GUID check is being skipped entirely if a webextension is uploaded.

https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L521-L522

**Comment by diox** [comment]
Yeah that check needs to be smarter (while still allowing web extensions developers to omit a guid)

**Comment by andymckay** [comment]
Oh that's cool I can assign multiple people now. That's probably more confusing right?

**Comment by EnTeQuAk** [comment]
That's probably confusing, yeah. Although, we could interpret it as "first come, first serve" :laughing: 

I'll take a look at this today. Guess I broke it with the optional id for webextensions.

**Comment by diox** [comment]
un-assigning myself since @EnTeQuAk is looking at it :)

**Comment by EnTeQuAk** [comment]
for qa: this fixes various scenarios but basically:

 * Make sure we check GUID changes again, only WebExtensions for Firefox 48+ are allowed to omit them
 * Changing the GUID is not possible (you should get "Add-on ID doesn't match add-on.")
 * We check for duplicate add-on ID found for WebExtensions now too

All that was kinda broken for WebExtensions imho.

**Comment by vcarciu** [comment]
We tested these scenarios and everything looks fine. 
We tested also more edge cases without errors and we will mark the bug as fixed.
