### ISSUE TITLE
Update linter to allow `@whatever` as a guid

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#2788]
Currently the linter will flag a submission if the email style guid has nothing before the `@`. 

After the update an id like `@whatever` will be accepted.

Previous error seen was:

```
/applications/gecko/id should match pattern \"^{[A-Fa-f0-9]{8}-([A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}}$|^[A-Za-z0-9-._]+\\@[A-Za-z0-9-._]+$\
```

**Comment by ValentinaPC** [comment]
@muffinresearch : Is this already in stage? 
Should the "flag" you are talking about be happening at validation, an can still be seen on AMO-prod?
I've tried with a web-extension that has GUID type "@whatever" in all AMO servers and no message was returned.
I am doing something wrong?
Attaching the web-
[Password-Alert_v1.19.zip](https://github.com/mozilla/addons-server/files/295659/Password-Alert_v1.19.zip)
extension.

**Comment by muffinresearch** [comment]
@ValentinaPC afaik the addons-linter isn't yet running in prod. 

The fix should be on stage now - as long as you don't see anything flagged wrt the guid on stage it's all good.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage FF46(Win 7).
Postfix screenshots:
![addon](https://cloud.githubusercontent.com/assets/15685960/15747457/7bcc19f0-28e3-11e6-8037-227e2a5b843e.png)
![webextension](https://cloud.githubusercontent.com/assets/15685960/15747464/83bb866e-28e3-11e6-9d85-af89fc9fbb80.png)
