### ISSUE TITLE
Add in e10s status to the API

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2790]
I'd like to build out a more complicated dashboard for @shell15 and to do that we need that e10s status in the API. We've got a basic dashboard in AMO, but when we start pulling in telemetry, bugzilla and other general ad-hoc stuff its going to get complicated and I don't feel comfortable sticking that stuff in AMO.

Supports #2770

**Comment by diox** [comment]
@andymckay do you care if you have to hit a separate API for this ? I'm hesitant to add the info to the main addon API, it seems a little to specific, plus extra work to add it to ES to return it in search results.

I would prefer a different endpoint like `/addons/addon/<id>/feature_compatibility/` that you'd call for each add-on. What do you think?

**Comment by andymckay** [comment]
That would work for me right now, the only place we need this is in the API is for arewee10syet. At some point it would be nice to have it show up in internal search and if we do redesign the front end to use an API it may appear there, but we can cross those bridges when and if we reach them.

**Comment by madalincm** [comment]
Verified as fixed in FF47(Win7) in addons.allizom.org
the compatibility can be seen using /addons/addon/<id>/feature_compatibility/ 
I tried with both add-ons and webextensions and everything seems to work as expected.
