### ISSUE TITLE
Detail API returns 401 for preliminary reviewed (not public) add-on

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2791]
Seems to work for one (ad block plus) and fail for another (sort tabs by url):

```
https://addons.mozilla.org/api/v3/addons/addon/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}/
200
https://addons.mozilla.org/api/v3/addons/addon/jid0-uRZpLu7VtYEF3IY7A2TpX21yj3A@jetpack/
401
Traceback (most recent call last):
  File "build.py", line 21, in <module>
    fetch('jid0-uRZpLu7VtYEF3IY7A2TpX21yj3A@jetpack')
  File "build.py", line 13, in fetch
    res.raise_for_status()
  File "/Users/andy/.virtualenvs/new-arewee10syet.com/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://addons.mozilla.org/api/v3/addons/addon/jid0-uRZpLu7VtYEF3IY7A2TpX21yj3A@jetpack/
```

Is it because https://addons.mozilla.org/en-US/firefox/addon/sort-tabs-by-url/ is preliminary reviewed?

**Comment by diox** [comment]
Yes. I wasn't sure how to set permissions so I took the most paranoid option and disallow everything not fully reviewed. It'll need adjusting.

**Comment by diox** [comment]
Verified myself using _download-statusbar_, which is _Preliminary Reviewed_ on both dev and stage with the same slug:
- On stage, which hasn't got the fix yet, `curl https://addons-dev.allizom.org/api/v3/addons/addon/download-statusbar/` returns a 401.
- On dev, which has the fix, `curl https://addons-dev.allizom.org/api/v3/addons/addon/download-statusbar/` works
