### ISSUE TITLE
host in URL to add-on file is weird in development docker

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2792]
Not sure if this is because I'm using a `.zip` on my #2785 branch, but when I see the link to my add-on's file (http://olympia.dev/en-GB/developers/addon/tabs-tabs-tabs/versions/51) it gives me a link to `localhost:8000`, eg the Django server directly rather than the right URL. It obviously 404s, though changing `localhost:8000` to `olympia.dev` works.

Screenshot:

<img width="1234" alt="screenshot 2016-05-27 19 22 04" src="https://cloud.githubusercontent.com/assets/90871/15623352/9bfe6590-2440-11e6-8db7-dd261c6226e1.png">

**Comment by diox** [comment]
In case anyone else was wondering: this is not because of https://github.com/mozilla/addons-server/pull/2771 since it has not been merged yet.

**Comment by andymckay-limited-access** [comment]
Suspecting this won't help dave with his ui tests.

**Comment by andymckay** [comment]
The docs mention that setting:

```
export OLYMPIA_SITE_URL=http://olympia.dev
docker-compose up -d
```

Before running docker-compose will do the trick.

http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#accessing-docker

This worked for me locally. Would it make sense to that by default, or is this related to you running it Docker beta @tofumatt?

**Comment by EnTeQuAk** [comment]
great catch @andymckay, I thought it was automatically set but our `docker-compose.yml` only forwards it if set. I think setting it by default could be an idea increases the burden for new people though having to hassle with `hosts`.

**Comment by tofumatt** [comment]
I think it's because I was using the beta and didn't need that feature, but now I'm back to using virtual box because it's faster/less buggy.

Looks like I forgot to RTFM 😉

**Comment by EnTeQuAk** [comment]
Is that we have to fix then?

**Comment by andymckay** [comment]
I'd be cool with saying that it always lives at amo.dev or something, the downside is that a contributor has to hack their /etc/hosts or similar to get that DNS entry to docker.

@mstriemer if I run Firefox Accounts locally, do I need to be using a specific domain?

**Comment by tofumatt** [comment]
It would be nice if it used whatever the hostname of nginx is if that env var isn’t set.

That way I could just load 192.168.99.100 or whatever my docker-machine IP is and run AMO without the need to hack hosts files, which I find really obnoxious.

**Comment by mstriemer** [comment]
By default you need to run at `http://olympia.dev` for FxA to work out of the box. It's the default key of `FXA_CONFIG` in [settings.py](https://github.com/mozilla/addons-server/blob/2a9d589eea91fd69bd4c99e75a4d906c1066f556/settings.py#L92-L101). You could in theory override it in your local config but you need an @mozilla.com email address to generate a new config on FxA's side.

**Comment by EnTeQuAk** [comment]
Maybe then it's a good idea to default to olympia.dev if we have stuff
that relies on it
 
 
On Wed, Jun 1, 2016, at 10:08 PM, Mark Striemer wrote:
> By default you need to run at http://olympia.dev for FxA to work out
> of the box. It's the default key of FXA_CONFIG in settings.py[1]. You
> could in theory override it in your local config but you need an
> @mozilla.com email address to generate a new config on FxA's side.
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[2], or mute the thread[3].
>
 

Links:

  1. https://github.com/mozilla/addons-server/blob/2a9d589eea91fd69bd4c99e75a4d906c1066f556/settings.py#L92-L101
  2. https://github.com/mozilla/addons-server/issues/2792#issuecomment-223109269
  3. https://github.com/notifications/unsubscribe/AAIfGfAbeA1SLr1YO28s_6DdF9B3QvVFks5qHea5gaJpZM4Io7ta

**Comment by andymckay** [comment]
I agree, the whole /etc/hosts manipulation is something we just have to live with, there are ways around that though.
