### ISSUE TITLE
Unused parameter tag in global template function showing()

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#2793]
Merely pointing out that this code path can be cleaned up: template function `showing()` (defined in `olympia/search/helpers.py`) takes a parameter `tag`. Both callers (`olympia/search/templates/search/collections.html` and `olympia/search/templates/search/personas.html`) will pass in a `tag` variable here that isn't actually defined in the context of these templates. So the entire tag handling seems to be dead code here.

`olympia/search/helpers.py` also defines a global function `pagination_result_count()` - this one is also dead code, not called anywhere other than unit tests.

**Comment by diox** [comment]
The tag handling should be fixed, IMHO, that's a bug. Agreed about `pagination_result_count()` that should be removed.

**Comment by diox** [comment]
Looking a this more closely, you're right, the tag handling in `showing()` should go away. The collections and themes search does not expose refining search by tag anyway. Extension search does, but it highlights the tag in the menu on the left.  (Annoyingly all three present results in a slightly different way)

**Comment by diox** [comment]
Thanks for reporting the issue, @palant. This should now be fixed in master.

QA: Please make sure searching for an extension, theme or collection still works, displaying pagination and search query correctly.

**Comment by vcarciu** [comment]
Verified as fixed for extensions, themes or collections
