### ISSUE TITLE
hsb (Upper Sorbian): Developer Hub shows some unranslated strings

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#2794]
Hi,
on the Upper Sorbian Developer Hub page - https://addons-dev.allizom.org/hsb/developers/ - some strings appear untranslated:

- week, weeks, day, days
- "There's no better way to distribute your add-on than by hosting it on Mozilla Add-ons." (#2795)

Why does it happen?

Thanks
Michael

**Comment by tofumatt** [comment]
That usually means there is no translation available for that string (when there is no translation the fallback in en-US).

For the first strings, (week/weeks/etc.) it seems the `timesince` filter we’re using (https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#timesince) isn’t localised into HSB. I tested the page in French and it is translated.

The second one is definitely a bug though! That string isn’t wrapped in a get text call, which we use to localise things. I’ll submit a patch soon!

I’m going to separate out the second issue and patch it, thanks for finding this!

**Comment by milupo** [comment]
Hi tofumatt,
thank you for you information. Yes, hsb is pretty new, and dsb (Lower Sorbian) as well so the timesince filter should be localized for dsb as well. Do you need my help for localizing the timesince filter?

> I’m going to separate out the second issue and patch it, thanks for finding this!
You are welcome! There is nothing worse for a translator than untranslated strings. :-)

**Comment by milupo** [comment]
There are still two strings on the bottom of the page:

- Report Trademarke Abuse
- Except where otherwise noted, content on this site is licensed under the
Creative Commons Attribution Share-Alike License v3.0 or any later version.

**Comment by tofumatt** [comment]
The `timesince` filter is actually upstream in Django, so I would see if they have HSB locales and patch it there. I'm not sure if we can add localisations for it, I'm not super-knowledgable about Django l10n.

I would guess those last two just aren't translated, but I can't find them in the source. If you can show me where they aren't translated I can fix those bugs too! If they're just untranslated: https://pontoon.mozilla.org/projects/amo/ would be where to go to add localisations! 😄

**Comment by EnTeQuAk** [comment]
Yeah, django unfortunately doesn't have hsb or dsb (https://github.com/django/django/tree/master/django/conf/locale) locales. So maybe it's best to start contributing (https://docs.djangoproject.com/en/1.9/internals/contributing/) there since there will be a few more cases where the locale will show the English version otherwise.

**Comment by milupo** [comment]
Hi tofumatt, hi EnTeQuAk,

AMO is completely translated into hsb since yesterday, 20% is translated into dsb now. The file djangojs is cpmpletely translated into both languages.

What can I do? On Developer Hub page, it is about plural rules, see:

http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html
Sorbian languages have the same rule as Slovenian.

Number and date/time formats are here:

http://demo.icu-project.org/icu-bin/locexp?_=hsb&d_=en
http://demo.icu-project.org/icu-bin/locexp?_=dsb&d_=en

**Comment by milupo** [comment]
BTW, I have a Transifex account for another project. (Skype)

**Comment by milupo** [comment]
On the versions page, e.g. https://addons-dev.allizom.org/hsb/firefox/addon/adblock-plus/versions/ the string "Detailed changelog" remains untranslated. Is it a bug or does this string belong to the add-on description shown always in the description language the add-on author has used?

**Comment by andymckay-limited-access** [comment]
Rather than keep adding to this bug, could please file a new bug when you find an untranslated string (and check that its not translated in another language). These are often easy to fix and we can assign them as good first bugs.

**Comment by milupo** [comment]
OK, sorry.

**Comment by milupo** [comment]
@tofumatt, EnTeQuAk: How can I have hsb and dsb added to Django on Transifex that I can translate the project? Transifex knows hsb and dsb. Thanks.

**Comment by tofumatt** [comment]
I'm not familiar with their translation system, so sadly I don't know. You'll have to ask the django team, but I'm sure they can point it out. They have excellent docs too, so see if it's mentioned there too.

- tofumatt

**Comment by EnTeQuAk** [comment]
@milupo it's probably best to ask in #django on IRC or write an email to https://docs.djangoproject.com/en/dev/internals/mailing-lists/#django-i18n so that someone from the core team can help you with that.

**Comment by milupo** [comment]
Thank you. I wrote a Transifex message to the Transifex django maintainer "jezdez" (probably also German) yesterday but he didn't answer yet.

**Comment by milupo** [comment]
Hurraaaaaa! dsb and hsb are already available on addon.mozilla.org! Thank you very much!

**Comment by EnTeQuAk** [comment]
Anytime, thank you for translating all that stuff :)

I'm going to close this issue. As far as I can see there isn't anything that's left to fix for us, please feel free to reopen if I was wrong or report new issues separately if they arise.
