### ISSUE TITLE
Section of DevHub page is not localised

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2795]
https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/index.html#L133 is missing a `{% trans %}` tag, as reported in #2794.

I'll fix this in like five minutes.

**Comment by ValentinaPC** [comment]
Please add some STR for us to verify it or mark this with "needs no qa" label. Thanks!

**Comment by vcarciu** [comment]
@tofumatt : Can you please add some STRs to this bug or add "need no qa" label?

**Comment by tofumatt** [comment]
Sorry, you're right. Marked as needs no qa, thanks.

**Comment by vcarciu** [comment]
I am sorry too , I see now that Valentina asked same question

**Comment by tofumatt** [comment]
We're all sorry! Making me feel extra 🇨🇦

**Comment by EnTeQuAk** [comment]
![giphy](https://cloud.githubusercontent.com/assets/139033/15750173/b66c3e6c-28e5-11e6-8dc3-d49b527f23b9.gif)
