### ISSUE TITLE
no_links template filter is superfluous and dangerous

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#2799]
The file `olympia/translations/helpers.py` defines a Jinja2 filter called `no_links`. The goal of this filter appears to be stripping links from fields allowing some HTML code where links are forbidden however. The code of this filter is flawed however as it won't do proper HTML parsing, so `<a/href="javascript:alert()">` won't be considered a link.

This isn't a real issue as this filter isn't actually doing anything. It is being applied to collection descriptions and user details. In both cases proper validation happens when the data is being entered, including removing links reliably (despite the validation code only displaying an error for links resolving to http:// and https:// schemes).

IMHO, this filter should be removed, otherwise somebody may be tempted to use it in a situation where it actually matters.

**Comment by diox** [comment]
That code was added in 2aabf985. That filter might have been intended to work around problems with existing content from before the check was added. I wonder if the data has been cleaned up since...

**Comment by andymckay-limited-access** [comment]
We should check that the data is good before removing this, it does look like a questionable filter.

**Comment by eviljeff** [comment]
The discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=928128 indicates it was indeed intended to deal with existing content - the concern was suddenly (silently) breaking descriptions that were otherwise okay before.

**Comment by eviljeff** [comment]
Looks like the filter was only used for collections and they've been rewritten in our new front-end and it's no longer applicable there.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
