### ISSUE TITLE
Web-extension submission fails with "/background/" errors

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2800]
Steps to reproduce:
Try to submit the attached web-extension (or any other web-extension that contains a background section in the manifest.json file) using AMO-dev - https://addons-dev.allizom.org/en-US/developers/addon/submit/2

Results:
Submission fails with "/background/" js errors.

Notes/Issue:
Verified on AMO-dev FF49(Win 7). Works in stage.
Screenshot for this issue: 
![background_](https://cloud.githubusercontent.com/assets/15685960/15644633/d0cc9a80-265c-11e6-9f89-bcfee3565d03.png)

Web-extension used: 
[Multi-highlight_v1.11.zip](https://github.com/mozilla/addons-server/files/289432/Multi-highlight_v1.11.zip)

**Comment by andymckay** [comment]
This now passes thanks to the merge from @EnTeQuAk

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win7)
Postfix screenshots: 
![1](https://cloud.githubusercontent.com/assets/15685960/15668909/52503ee4-2726-11e6-962b-c02aa342dbe8.png)
![2](https://cloud.githubusercontent.com/assets/15685960/15668913/5644e8ba-2726-11e6-9be5-7649c2a7efb7.png)

**Comment by ValentinaPC** [comment]
I've tried with a bunch of web-extensions and all worked as expected after this fix, except one (until now) that is returning " /background/scripts/0 should match format "relativeURL" " errors.
Verified on AMO-dev FF49 (Win 7).
Screenshot: 
![b](https://cloud.githubusercontent.com/assets/15685960/15670524/9dbebe16-272e-11e6-8b81-e07b572cc1b5.png)

Attaching used web-extension:
[Search-Manager_v1.0.5.79.zip](https://github.com/mozilla/addons-server/files/290781/Search-Manager_v1.0.5.79.zip)

**Comment by ValentinaPC** [comment]
Attaching second example: 
[Photo-Screen-Saver_v1.7.0.zip](https://github.com/mozilla/addons-server/files/290828/Photo-Screen-Saver_v1.7.0.zip)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
Postfix screenshots: 
![photo](https://cloud.githubusercontent.com/assets/15685960/15706461/60f719c8-27fc-11e6-9af4-fd7bc0309625.png)
![search](https://cloud.githubusercontent.com/assets/15685960/15706465/6548b964-27fc-11e6-9f33-eff0088c7acb.png)
