### ISSUE TITLE
Add-on with long author name breaks add-on featured section from any category

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2818]
Steps to reproduce:
1. Go to any add-on categories https://addons.allizom.org/en-US/firefox/extensions/bookmarks/
2. Pick an add-on from the featured section
3. Add another author with long display name (for that addon)
3. Hover over the add-on

Expected results:
There are no display or layout issues.

Actual results:
The featured section has layout issues.

Notes/Issues:
Verified on FF46(Win 7). Issue is reproducing on AMO-stage and dev.
Screencast for this issue:  
![longdisplayname](https://cloud.githubusercontent.com/assets/15685960/15713061/851600f0-281d-11e6-8aae-8b5eaf2b1f54.gif)

**Comment by wagnerand** [comment]
Mentor: @tofumatt

If this is your first bug, see https://wiki.mozilla.org/Add-ons/Contribute for details how to contribute.

**Comment by Prashant-Surya** [comment]
Can I work on this bug?

**Comment by tofumatt** [comment]
@Prashant-Surya Sure thing! We can't assign it in GitHub because you aren't in the Mozilla organisation, but feel free to work on it and ping me when you submit a PR--I'll have a look once it's ready.

Please be sure to include before/after screenshots of the fix so I can see it and QA can verify the results, thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7 x64)
Postfix screenshot: 
![longname](https://cloud.githubusercontent.com/assets/15685960/17172688/0b4413e4-53ff-11e6-9e73-d373938c8b16.png)

Note: takes a few minutes until changes apply.
