### ISSUE TITLE
Set default supported Firefox version to 48+ if id is missing

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2820]
For WebExtensions that don't have an id set in the manifest make sure we set the default supported version of Firefox and Android to 48+

**Comment by EnTeQuAk** [comment]
@jvillalobos is it okay that I won't touch add-ons that have `strict_min_version` or `strict_max_version` set, e.g to 42-47 and suddenly omit the id? I'm not sure how real-life that example is or if we mostly care about new add-ons or add-ons that convert to WebExtensions.

**Comment by jvillalobos** [comment]
If they're not going to work in 42-27 I think they should still have their `strict_min_version` updated. I don't see much difference between new submissions and updates for this bug.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7).
Web-extensions without an ID are set to be compatible with FF48 and above.
Postfix screenshot: 
![2016-06-09_1554](https://cloud.githubusercontent.com/assets/15685960/15930310/d4d9186e-2e5a-11e6-9955-1dda30bd01e9.png)
