### ISSUE TITLE
404 page tells users to contact webmaster@mozilla.com

### ISSUE THREAD

**Issue by tjol** [mozilla/addons-server#2822]
This is a duplicate of forgotten bug https://bugzilla.mozilla.org/show_bug.cgi?id=1037956 .

The "not found" error page, e.g. at https://addons.mozilla.org/en-US/thunderbird/addon/dictionnaires-fran%C3%A7ais/ (as mistakenly linked to, see https://bugzilla.mozilla.org/show_bug.cgi?id=1276656), says:

> If you followed a link from somewhere, please let us know at webmaster@mozilla.com. Tell us where you came from and what you were looking for, and we'll do our best to fix it. 

If you follow that advice, webmaster@mozilla.com helpfully replies 

> Thanks  for contacting us. We're sorry that we can't answer your
email. In  order to best serve you, please use one of the following
resources:  
> [...]
> - If you've found an issue with one of our websites, we'd appreciate
it if you could report the problem in Bugzilla, our bug tracker.
https://bugzilla.mozilla.org/enter_bug.cgi?product=www.mozilla.org One
of the Mozilla Web Developers will take a look at it as soon as
possible.

Users who encounter dead links should be not only sent to the bug tracker straight away, but also sent to the *right* one.

**Comment by tofumatt** [comment]
Best to replace the email with a link right to the bug tracker (here). Good catch.

**Comment by lavish205** [comment]
I want to work on this bug, looking for further instructions to get started.

**Comment by wagnerand** [comment]
I don't think this is an add-ons server bug. The email is not being sent by add-ons server and it's very generic and probably is not only used by us.

**Comment by wagnerand** [comment]
Oh, I misread that, ignore the previous comment.

**Comment by lavish205** [comment]
we can close this bug

**Comment by EnTeQuAk** [comment]
This is fixed now.
