### ISSUE TITLE
language-tools page out of date for logged out users

### ISSUE THREAD

**Issue by cpeterso** [mozilla/addons-server#2823]
When I load https://addons.mozilla.org/en-US/firefox/language-tools/, the French "Install Dictionary" link points to https://addons.mozilla.org/en-US/firefox/addon/dictionnaires-fran%C3%A7ais/ and is 404. Other people get https://addons.mozilla.org/en-US/firefox/addon/dictionnaire-fran%C3%A7ais1/. The first URL and spells `dictionnaires` with an `s` and doesn't end in `1`:

https://addons.mozilla.org/en-US/firefox/addon/dictionnaires-fran%C3%A7ais/ :-1:
https://addons.mozilla.org/en-US/firefox/addon/dictionnaire-fran%C3%A7ais1/ :+1:

This problem was reported on Bugzilla in [Firefox bug 1276454](https://bugzilla.mozilla.org/show_bug.cgi?id=1276454) and [bug 1276656](https://bugzilla.mozilla.org/show_bug.cgi?id=1276656).

**Comment by Flote37** [comment]
There is the exact same problem on Thunderbird.
From the Thunderbird client, when trying to add the french dictionary, I wound up on this 404 page.

Step : 
In thunderbird : Preferences -> Redaction tab -> Download more dictionary -> French dictionary link -> 404 page.

The bad link is : https://addons.mozilla.org/fr/thunderbird/addon/dictionnaires-fran%C3%A7ais/  :-1: 

But when I try with this link : https://addons.mozilla.org/fr/thunderbird/addon/dictionnaire-fran%C3%A7ais1/ :+1: it works.

It seems to be a related problem.

**Comment by jvillalobos** [comment]
After some testing, it looks like you get the right dictionary when you're logged in, and the wrong one when you're logged out.

**Comment by Flote37** [comment]
I created an account for firefox to test it out and I'm still getting the 404. Maybe it's a problem of cache.
When you log out, the cache may be different and you get the wrong link.
When you are logged in, did you try to access the dictionaries' page from : 
- right click on a word you wrote (in a search engine for example)
- select "Add Dictionaries"
From the page where I'm redirected : https://addons.mozilla.org/en-GB/firefox/language-tools/ ,
I can only access to the wrong link (the 404).

Maybe the "Add Dictionaries" button redirect on the wrong page (the one where you can select the dirctionaries) ?

**Comment by andymckay** [comment]
@jasonthomas flushed memcache and it seems to be working now, not sure how that didn't invalidate properly.

**Comment by Flote37** [comment]
It does work perfectly on firefox and thunderbird now. Thanks a lot !

**Comment by madalincm** [comment]
Verified as fixed in FF47(Win7) and Thunderbird 45.1.1(Win7) 
The links are working as expected and the dictionary can be installed.

**Comment by jvillalobos** [comment]
It looks like this is happening again for the recently added Venetan dictionary. I got separate reports from @eviljeff and @mtrevisan that the dictionary didn't appear. In the case of @mtrevisan, logging in fixed the problem.

**Comment by eviljeff** [comment]
made the title more generic.

**Comment by eviljeff** [comment]
we do some specific caching of the add-ons shown on that page: https://github.com/mozilla/addons-server/blob/master/src/olympia/browse/views.py#L93

**Comment by mtrevisan** [comment]
It seems that the problem was solved! thank you all!

**Comment by andymckay-limited-access** [comment]
Let's just remove the caching for anonymous users because this page doesn't get much traffic.

**Comment by andymckay-limited-access** [comment]
Just to confirm, that looking in google analytics, it seems like these pages get very little traffic.
