### ISSUE TITLE
Addon's versions history page has no links to the addon's listing

### ISSUE THREAD

**Issue by vanowm** [mozilla/addons-server#2824]
The version history page is missing breadcrumbs links. Currently there is no way to open the addon's listing page except for the "latest version" link, which not intuitive at all.

![](http://i.imgur.com/icX8Xfg.png?2)

**Comment by ValentinaPC** [comment]
Please take a look at the comments from #2014 . Thanks!

**Comment by vanowm** [comment]
Wow....

> Let's rely on the back button. Users interested in this page should be experienced enough to deal with that.

The issue was closed after that comment...Holly shit!
![](http://s2.quickmeme.com/img/a2/a2e2c23b6669a334364c83e892bdc9649deeec1aa530b29ce4b6f73f37539d0d.jpg)

**Comment by tofumatt** [comment]
@vanowm If you keep swearing at us and trolling the development team your comments will be deleted. If you disagree with the outcomes of these discussions and want to have a constructive conversation that's fine. If you want to mock the Add-ons team at Mozilla use your own platform and not our issue tracker.

**Comment by designakt** [comment]
@vanowm We stopped using bread crumbs on all pages as for most pages they are not needed to navigate AMO successfully. You are right that in the case of someone directly linking to a versions page this makes it a bit more difficult to get to the add-ons details page. That use case however is rather unusual and we therefor didn't consider it further as there was a way to get to details. Granted, it is not the most intuitive, but you are welcome to propose a better solution and implement it, and we will happily review and welcome your support. (Making the add-on name in the heading a link might be an intuitive solution that comes to mind.)
