### ISSUE TITLE
Version links at addon's version history page unnecessary reload the page

### ISSUE THREAD

**Issue by vanowm** [mozilla/addons-server#2825]
At addon's version history page each version of the addon has a link that point to the same addon's version page, which reloads the page when clicked and then scrolls down to that specific version once it's reloaded.
The same effect could be achieved without reloading the page: with anchor links (# hash tag in the link)

**Comment by wagnerand** [comment]
Mentor: @tofumatt 

If this is your first bug, see https://wiki.mozilla.org/Add-ons/Contribute for details how to contribute.

**Comment by lavish205** [comment]
I would like to work on this issue.

**Comment by tofumatt** [comment]
Sounds good, consider it yours. If you need any guidance let me know, otherwise just ping me when you have a pull request ready. Thanks!

**Comment by tofumatt** [comment]
Hey there,

A few of the AMO developers just talked about this on IRC. This actually doesn't seem like a good first bug as it's tied up in pagination code and would actually be a lot of work to unravel for a relatively small gain. While a fix would be an improvement, I think this is something best left alone as a wont fix that we can just do better in a new front end.

**Comment by vanowm** [comment]
Sorry, did I read it right? it's too difficult add hashtags to the links?

**Comment by tofumatt** [comment]
It's not just hashtags, the versions are laid out across different pages and the pagination seems built around where a version falls in the overall list. So it's not as simple as just adding hashes to links, it would be a lot of work to implement what you'd like here for such a small benefit.

Your idea is right but sadly the way this section was implemented makes it very complicated and not worth the effort.
