### ISSUE TITLE
JS error displayed in browser console for a supported API

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2829]
Steps to reproduce:

1.Launch Firefox with clean profile.
2.Create the xpinstall.signatures.dev-root pref in about:config and set it to true.
3.Install the following WebExtension: https://addons-dev.allizom.org/en-US/firefox/addon/citrus123/ 

Expected results:
No errors displayed in the browser console when using WebExtension.

Actual results:
WebExtension works fine but I receive an error for **chrome.alarms** which is a supported API according to http://arewewebextensionsyet.com/ 

Note/Issues:
Verified on FF49.0a1 (2016-06-01) (Win 7 64-bit). This issue is reproducing in AMO-dev.
Video to this issue:
![chromealarms](https://cloud.githubusercontent.com/assets/15885467/15742677/15169a92-28c9-11e6-9f26-8f282364b4c6.gif)

**Comment by tofumatt** [comment]
This appears to be an issue with Firefox and not with AMO. Could you please file this bug in the WebExtensions component of Firefox?

You can file the bug here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions

I don't think this is an issue with the addons-server.

**Comment by cosminbadescuSV** [comment]
The bug is filed in Bugzilla, here is a link: https://bugzilla.mozilla.org/show_bug.cgi?id=1277551
