### ISSUE TITLE
Add docs for adding/installing a new library to requirements file

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2831]
I want to add `commentjson` to AMO for #2734, but the process to add a requirement, especially with the extras around hashes and pyrepo are opaque and not documented anywhere in the docs.

@EnTeQuAk is helping me on IRC, but this seems like knowledge that isn't documented anywhere.

We should document the process for adding a requirement to AMO.

**Comment by EnTeQuAk** [comment]
I wouldn't call it a "process" but it's currently something like:

 * try to remember if you have access to pyrepo, if not ping ops or your fellow team mate
 * `pip download my_fancy_package` (which will download a .whl, *or* a .tar.gz, *or* a .zip. Guess there aren't much more variations)
 * calculate the sha256 hash of that file (e.g call `sha256sum my_fancy_package.whl`)
 * Add all that to the requirements, very probably `requirements/prod.txt` unless it's only relevant for testing then it's better to use `requirements/dev.txt`
 * `scp my_fancy_package.whl USERNAME@pyrepo.stage.mozaws.net:/data/pyrepo/olympia/`
 * *only now* can you submit your change as a pull request as travis will force packages to be installed from pyrepo and fail if they're not there

open up some :beers: or have some :cookie:'s

**Comment by diox** [comment]
FWIW there is https://mana.mozilla.org/wiki/display/WebDev/pyrepo for the pyrepo part if you didn't know already.

**Comment by diox** [comment]
Also, you want to make sure you have an up to date `pip` and `wheel` packages when you do that.

**Comment by EnTeQuAk** [comment]
I believe this got fixed by @muffinresearch in bf5a53fae0fda25f63cc539b8008fce1d1905753
