### ISSUE TITLE
Remove applications.gecko.update_url from uploaded add-ons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2835]
Rather than fail validation, the linter will soon warn users that `update_url` will not be respected for add-ons uploaded to addons-server (https://github.com/mozilla/addons-linter/issues/726).

To make that true and make sure add-ons uploaded to AMO are only updated via AMO, we should modify any manifests uploaded to AMO with `gecko.applications.update_url` to remove that value.

**Comment by andymckay** [comment]
You still want to modify the manifest? I'm still kinda convinced we shouldn't. But I could be convinced otherwise.

**Comment by tofumatt** [comment]
Yeah. Imagine:

Developer creates an add-on, it can be distributed off of AMO. They include their `update_url`.

They decide to add it to AMO. We make them manually package two versions of the add-on because we fail validation on `applications.gecko.update_url`.

Instead we can remove the attribute but _tell them version explicitly we did so and that they need to upload new versions to AMO for users who downloaded their add-on from AMO_. We're just doing automatically what we're requiring they do to get the add-on on AMO. It's worth ignoring the attribute; but in this case to deliver it to Firefox from AMO (because Firefox will use `update_url` first) we need to remove it.

We're just doing automatically what we would otherwise make a user do manually. Seems a waste.

**Comment by andymckay** [comment]
Are you saying that Firefox will use `update_url` first if its present?

**Comment by tofumatt** [comment]
My understanding was that Firefox will use:

applications.gecko.update_url if present to update

After that it will use AMO.

It should ignore update_url at the root of the manifest.

That’s what I asked in #webextensions today, I think you were the one who told me the bit about looking for update_url first because it doesn’t know the add-on came from AMO or not :-)

**Comment by tofumatt** [comment]
@andymckay and I chatted about this and we're gonna drop it. This will be an error instead, updating https://github.com/mozilla/addons-linter/issues/727...
