### ISSUE TITLE
Problem with dsb and hsb reviews

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2839]
Spotted in sentry:

NoReverseMatch: Reverse for 'addons.reviews.translate' with arguments '(u'video-downloader-player', 660352L, 'dsb')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['addon/(?P<addon_id>[^/<>"\']+)/reviews/(?P<review_id>\\d+)/translate/(?P<language>[a-z]{2}(-[A-Z]{2})?)$']

eg: https://addons.mozilla.org/dsb/seamonkey/addon/video-downloader-player/reviews/660352/

Thanks google bot for spotting that for us. Also one for hsb.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7).
All review pages are loaded with success for "three character language" (i.e hsb, dsb).
Postfix screencast: 
![dsb-hsb](https://cloud.githubusercontent.com/assets/15685960/15935696/d78e6396-2e70-11e6-9517-5073c64d1b19.gif)
