### ISSUE TITLE
WebExtension submission fails if “/background/script” has additional properties

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#2846]
Steps to reproduce:
Try to submit [StarWarsTodoList.zip](https://github.com/mozilla/addons-server/files/297600/StarWarsTodoList.zip) or a WebExtension that contains a background section in the manifest.json file using https://addons-dev.allizom.org/en-US/developers/addon/submit/2 .

Expected results:
Submission passes without any errors.

Actual results:
Submission fails with the next message : “/background/script should NOT have additional properties”.

Note/Issues:
Verified on FF49.0a1 (2016-06-02) (Win 7 64-bit). This issue is reproducing in AMO-dev, AMO-stage and AMO-production.
This issue could be related to #2800
Here is a screenshot:
![background](https://cloud.githubusercontent.com/assets/15885467/15779246/e0807a38-29a3-11e6-8516-b51857f4b87b.png)

**Comment by andymckay** [comment]
Looks like the add-on is wrong. It should be scripts, not script.

See the Chrome and Firefox docs:

https://developer.chrome.com/extensions/background_pages
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/background

The error isn't the greatest though.

**Comment by cosminbadescuSV** [comment]
After I changed "script" with "scripts" , submission passes without any errors. 
here is a screenshot: 
![script](https://cloud.githubusercontent.com/assets/15885467/15782732/1582f58e-29b4-11e6-8500-4625b669a820.png)

**Comment by tofumatt** [comment]
The error message could be a bit clearer, indeed.

**Comment by andymckay** [comment]
Closing this bug since we've got the linter one open.
