### ISSUE TITLE
Theme installation button is stuck when the user undo the theme instalation

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2855]
to access the new disco pane follow the instructions here: https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing

**Steps to reproduce:**
1. Open the new disco pane about:addons.
2. Use the toggle button to install a theme.
3. Click the undo button displayed at the top of the page.

**Expected results:**
The theme is uninstalled, the theme installation button is reset and the theme can be installed again.

**Actual results:**
The theme is uninstalled, the theme installation button is stuck and the theme can't be installed again.

**Notes/Issues:**
Verified in FF49 in addons-dev
Screencast for this issue:
![discopanethemebutton](https://cloud.githubusercontent.com/assets/15685441/15820142/21c356b6-2bf0-11e6-9538-86d11ab3c95e.gif)

**Comment by muffinresearch** [comment]
Can you file all disco pane related bugs on addons-frontend. This one is a known issue: See https://github.com/mozilla/addons-frontend/issues/467
