### ISSUE TITLE
e10s compatibility for all add-ons

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2864]
For the bugs around e10s add-ons can we ensure they are done equally for listed and unlisted add-ons please? That includes:
* the management command to process them
* the upload of add-ons warning
* the API that let's us know the state
* the message in the developer hub back to the user

**Comment by diox** [comment]
It should already be the case for everything except the management command, because `process_addons` base queryset filters them out. I'll tweak that.

**Comment by diox** [comment]
This supports #2770 btw.
