### ISSUE TITLE
generated id for webextension with no manifest id should be {uuid}

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#2865]
When a webextension is submitted with no id in manifest.json, it gets signed with a uuid as its id (to be specific, "as its id" means the contents of the Common Name field of the signature).  But Firefox requires that ids match this pattern:
https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#275
Which is either "string@somewhere" or a uuid enclosed in curly braces.
Signing addons with raw uuids (without the curly braces) led to https://bugzilla.mozilla.org/show_bug.cgi?id=1278530 
I will create a patch for Firefox to refuse to load these addons but this bug is to fix the server side.  We should also check how many addons have already been signed and might be affected.

**Comment by andymckay** [comment]
I'm betting almost none. We can fix them their id's on AMO and notify their authors. There will probably be no need for a Firefox change.

**Comment by vcarciu** [comment]
Verified as fixed on Stage : 
![curly](https://cloud.githubusercontent.com/assets/1583842/15937657/6d6801f4-2e78-11e6-9a34-08078757fd55.png)
