### ISSUE TITLE
Where are add-on categories translated?

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#2868]
Hi, hsb and dsb are already active on addons.mozilla.org, but add-on categories names are still untranslated. Where can I translate them?

Thanks

Michael

**Comment by milupo** [comment]
Hi, did anybody see my issue?

**Comment by andymckay** [comment]
Most people have been travelling to a mozilla all-hands meeting, so responses are delayed. 

@diox might know though.

**Comment by diox** [comment]
The categories and their translations are stored in the database. Unfortunately, the interface to translate them has been removed a few months ago in a cleanup sweep: https://bugzilla.mozilla.org/show_bug.cgi?id=1210238

I want to finish that work and move the categories to being static strings in our repos and in .po files but this will take time - that's #2923.

**Comment by milupo** [comment]
Thank you, diox.
