### ISSUE TITLE
Discovery Pane homepage links are not working

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2871]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0

Steps to reproduce:
1.Set your discovery pane to point to Stage (set extensions.webservice.discoverURL to https://services.addons.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%)
2.Open your Discovery Pane (Tools - Addons)
3.Try to open "Browse all addons" link under "More ways to customize" section

Expected results:
User is redirected to AMO homepage

Actual results:
A "What are addons" message is displayed and user is not redirected as expected

Please see video for this bug:
http://screencast.com/t/24ytBwg0tWw

NOTES:
Everything works as expected on prod
Reproducible for many links on discovery pane home page (ie."See all complete themes" ,  "See all" for Up & Coming addons, "My profile", etc...)
I cannot see any useful info in console

**Comment by muffinresearch** [comment]
Looks to be a regression from https://github.com/mozilla/addons-server/commit/ffd501fa32729cfea267fba37a11266d1d2ac2f4

**Comment by vcarciu** [comment]
Please note that this affects links from other pages too(ie . "learn more" links from themes details pages)

**Comment by muffinresearch** [comment]
The problem was target="_blank" removal since the page now has:

```html
<base href="https://addons.allizom.org">
```
and not:

```html
<base target="_blank" href="https://addons.allizom.org">
```

and this would affect all links.

**Comment by muffinresearch** [comment]
Added to the cherry-picks list for the release see https://public.etherpad-mozilla.org/p/amo-2016-06-09

**Comment by vcarciu** [comment]
Verified as fixed on all links
