### ISSUE TITLE
Add requirements to run l10n extraction

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2873]
To run `locale/omg_new_l10n.sh`, we need some tools that are currently not available in the docker container.

What's missing is:
- `translate-toolkit`,
- `gettext`, but using `yum install gettext` installs an old version (0.8.12) which is too old as we are using features that require a new version. @EnTeQuAk might know what version exactly we need.

**Comment by muffinresearch** [comment]
Wouldn't you be running this against the tree so these tools would live on your host. I'm not sure putting them in docker is necessary.

**Comment by wagnerand** [comment]
Well, depending on your host they are not available, or in a different version/flavor. For example, I couldn't get this to run on Mac.

**Comment by muffinresearch** [comment]
That sounds like a bug we should fix. It should be possible to run this on OSX.

**Comment by eviljeff** [comment]
I'm clearing this milestone - please add one back when there is a commit that is likely to land.

**Comment by muffinresearch** [comment]
Update: running this recently I get gettext 0.18.2 and running it via docker is needed since you require the django settings etc to do the extraction.

**Comment by EnTeQuAk** [comment]
I'm starting to get somewhere with my addons-robot refactoring so I'll tackle fixing the requirements for running the extraction again, this week.
