### ISSUE TITLE
Recognize hybrid addons and mark them to be visible to the reviewer

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-server#2875]
Once the [Embedded WebExtension feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1252227) lands, addon developer will be able to embed a WebExtension inside an SDK or a bootstrap restartless addon.

As previously discussed we will need to recognize an hybrid addon on submissions so that we will be able to:
- mark the addon submission so that the reviewer can be aware that he is going to review an classic extension addon with an embedded webextension inside it 
- customize the automated validations

An hybrid addon can be recognized by looking into its `install.rdf` file, which should contains the following field when an addon has enabled the embedded webextension feature:

```
 <em:hasEmbeddedWebExtension>true</em:hasEmbeddedWebExtension>
```

**Comment by EnTeQuAk** [comment]
It's only allowed to embedd them one-way right? A regular add-on that embeds a WebExtension but not the other way around, e.g a WebExtension that embeds a regular add-on.

**Comment by tofumatt** [comment]
Correct!

- tofumatt

**Comment by mstriemer** [comment]
The plan appears to be to just run this through the amo-validator and mark the add-on for reviewers. No need to run the embedded webextension against addons-linter.

I think the validations should be working already so it should just be to add the flag for reviewers. We may want to notify the developer of how they can lint their embedded webextension if they'd like to.

**Comment by muffinresearch** [comment]
@wagnerand Following the discussion on irc yesterday please could you clarify the requirements for this issue?

**Comment by wagnerand** [comment]
I'll file a new bug in the validator.
