### ISSUE TITLE
Updates hashes in linter

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2880]
New versions of jQuery were added to the linter/dispensary and should appear as known third-party libraries in the editor tools: https://github.com/mozilla/dispensary/pull/163/files#diff-2309c6166569debf4083042d3ee2fca6R201

Only WebExtensions are affected by this change. Web Extensions with jQuery `1.12.x` and `2.2.x` should flag those jQuery files as known third-party libraries.

@wagnerand Can you attach example add-ons for QA here?

**Comment by wagnerand** [comment]
This can be tested with
[addon-3.2.6-fx+an-windows.xpi.zip](https://github.com/mozilla/addons-server/files/307136/addon-3.2.6-fx.an-windows.xpi.zip)
The _jQuery_ file in `lib/jquery/js` should be recognized.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7) with the attached web-extension.
Warnings received:
![2016-06-09_1856](https://cloud.githubusercontent.com/assets/15685960/15936735/c55a591a-2e74-11e6-8bcf-77f5f21f93e5.png)
@wagnerand : If this will do it (?) I'll mark this verified-fixed.

**Comment by tofumatt** [comment]
It shouldn’t scan known third-party libraries, so that seems off :-(

**Comment by ValentinaPC** [comment]
@tofumatt : When submitting the attached add-on on AMO-dev FF47(Win 7) there are no warnings or errors displayed. Please let me know if this is the intended behavior.
Screenshot: 
![testaddon](https://cloud.githubusercontent.com/assets/15685960/16294251/4771c3da-3928-11e6-9af9-2c8328c2cb9e.png)

**Comment by tofumatt** [comment]
@ValentinaPC Yes, that's correct (because the libraries get ignored). Thanks!
