### ISSUE TITLE
Remove pyrepo usage from our docker builds

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#2885]
references #2884 and mozilla-services/svcops#1104

We should remove pyrepo from our docker images too when we start to remove it from our infrastructure.

**Comment by bqbn** [comment]
Closing b/c https://github.com/mozilla/addons-server/pull/2884 merged and addressed this.

**Comment by ValentinaPC** [comment]
Please add some STR for us to test or the label "needs no qa". Thanks!
