### ISSUE TITLE
No 'up & coming' add-ons displayed on dev for Firefox 46

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#2886]
Our automated UI test suite for dev is failing because there are no 'up & coming' add-ons listed, but we are expecting there to be five.

Firefox 46: https://services.addons-dev.allizom.org/en-US/firefox/discovery/pane/46.0/Darwin

![screen shot 2016-06-10 at 17 26 42](https://cloud.githubusercontent.com/assets/122800/15971411/d324c848-2f30-11e6-915e-c6ede26ba0e6.png)

Firefox 48: https://services.addons-dev.allizom.org/en-US/firefox/discovery/pane/48.0/Darwin

![screen shot 2016-06-10 at 17 26 30](https://cloud.githubusercontent.com/assets/122800/15971409/d139176e-2f30-11e6-89a4-e28e4197faf1.png)

**Comment by andymckay** [comment]
Noting that this doesn't occur on prod. @davehunt given that the new discovery pane is on track for 48 and tests of this discovery pane won't be relevant, this might get won't fixed.

https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements

**Comment by davehunt** [comment]
That's fine @andymckay, I'm xfailing the test for dev and we can ultimately retire it altogether.

**Comment by andymckay** [comment]
Cool, thanks. Is testing the new discovery pane in the works? /cc @krupa

**Comment by davehunt** [comment]
@andymckay it's one of @justinpotts intern projects. you'll meet next week. :)

**Comment by muffinresearch** [comment]
@davehunt @justinpotts let me know when that happens.

**Comment by davehunt** [comment]
@muffinresearch absolutely!

**Comment by andymckay** [comment]
Closing for now based on comments above.
