### ISSUE TITLE
Install switch does not turn green for themes

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2889]
## preconditions:
Set up for testing disco pane on dev by using the instructions at https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing

## steps to reproduce:
1. Go to Tools -> Add-ons
2. Click on the install switch to apply a theme
3. Switch to the Appearance tab to make sure that the theme is listed as installed
4. Notice the install switch

## expected behavior:
1. Theme is applied to the firefox chrome
2. Install switch turns green for the installed theme

## actual behavior:
1. Theme is applied to the firefox chrome - **Works**
2. Install switch turns green for the installed theme - **Doesn't work** - Button remains grey

<img width="1390" alt="screenshot 2016-06-14 14 30 37" src="https://cloud.githubusercontent.com/assets/301317/16044676/5a25ebba-323d-11e6-9b11-54a685006202.png">
<img width="1374" alt="screenshot 2016-06-14 14 31 19" src="https://cloud.githubusercontent.com/assets/301317/16044681/5eb048e2-323d-11e6-968f-f3eb7281bc30.png">

**Comment by muffinresearch** [comment]
Which version of FF are you using. You might need nightly until https://bugzilla.mozilla.org/show_bug.cgi?id=1268077 is uplifted. You can tell by looking at the console. If you see `mozAddonManager.addEventListener not available` in the console, the version you're running doesn't have the platform changes necessary to make that work.

**Comment by muffinresearch** [comment]
@krupa did you have logs for this one from the other day?

**Comment by muffinresearch** [comment]
We noticed recently that the events might not fire if you don't restart after changing testing configuration. Going to close this we can re-open if it's seen under other circumstances.
