### ISSUE TITLE
All the cool background stuff that happens while watching the introductory video is missing

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#2892]
## steps to reproduce:
1. Go to Tools -> Add-ons on prod 
2. Watch the Learn More video (and, pay attention)
3. Repeat steps 1 & 2 on dev with the new disco-pane and compare it to prod

## observed behavior:
In prod, there are a lot of cool effects like add-ons mentioned in the video, get listed alongside and the themes get previewed. All these cool effects are missing in the new designs.

**Comment by muffinresearch** [comment]
As discussed in London this was left out conciously.
