### ISSUE TITLE
Add a migration for addons-linter to be enabled by default

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#2893]
Now that the linter is on production, we should add a migration that enables it until we ditch the waffle flag, as it currently makes for new installs with confusing messages.

**Comment by EnTeQuAk** [comment]
We don't run migrations on or initial setup and I don't think that we
currently have a way to set flags, we could add it to the makefile
somehow though. or, just remove the flag
 
On Tue, Jun 14, 2016, at 05:50 PM, tofumatt ☕️ wrote:
> Now that the linter is on production, we should add a migration that
> enables it until we ditch the waffle flag, as it currently makes for
> new installs with confusing messages.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>
 

Links:

  1. https://github.com/mozilla/addons-server/issues/2893
  2. https://github.com/notifications/unsubscribe/AAIfGWXrGoNt0yo-D51Ke4WToCkqWqcQks5qLs3EgaJpZM4I1eSY

**Comment by EnTeQuAk** [comment]
I think I'm just going to remove the flag if no one complains about it in https://github.com/mozilla/addons-server/issues/2937 this sprint so I'll close this here for now if that's alright.

**Comment by tofumatt** [comment]
wfm 

- tofumatt
