### ISSUE TITLE
Move category translations out of the database in our repos

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#2923]
We should move categories out of the database and in a python module in our repos, and then translate them using regular gettext calls. This will help performance and make it possible for translators to translate categories again.

This has already been done once before, in Marketplace:
https://github.com/mozilla/zamboni/commit/76927e730e7a8ac0d08a32dfeed4f43fbe6828c1
https://github.com/mozilla/zamboni/commit/0214acab25fa1d078c4f43373bf8805293534078

One thing to be careful about is that AMO has different categories for different applications. Maybe we can unify all that though.

**Comment by andymckay** [comment]
See also #2830

**Comment by diox** [comment]
1. Determine list of categories, merging all applications into one. We could still have different categories per app if needed, but let's try not to (We'll have to see how well that works with Personas, Thunderbird add-ons etc).
2. Make a mapping of the existing categories in db to the static merged one (use slugs).
3. We can use that mapping to keep using the old db schema while populating the new one.
4. However, need a smart way to add the new field to the addons table, which is a big table, so it's a tricky migration.

Maybe a smarter way to deal with this for the time being would be to keep the Category related models and db tables, but do the merging, remove the name field to have translations in .po files (using [django-vinaigrette](https://github.com/ecometrica/django-vinaigrette) ?).
That way we don't have to deal with:

- A migration touching Addon
- A migration removing AddonCategory
- Making /browse/ work (it needs an addon count for each category - we could get it from ES though)

**Comment by diox** [comment]
Note about merging: `get_creatured_ids()`, which returns the featured add-ons for a given category, assumes categories are different for each app, and would need to be changed accordingly (or we'd need to stop doing featured add-ons for a given category in applications other than Firefox)

**Comment by diox** [comment]
Stage's dump, so that we have an idea of what's in there:

name | slug | type | app | weight | count
--------|-------|-------|------|---|--------
Feeds, News & Blogging | feeds-news-blogging | extension | firefox | 0 | 1662
Web Development | web-development | extension | firefox | 0 | 1831
Download Management | download-management | extension | firefox | 0 | 752
Privacy & Security | privacy-security | extension | firefox | 0 | 1401
Search Tools | search-tools | extension | firefox | 0 | 2126
Appearance | appearance | extension | firefox | 0 | 2251
Bookmarks | bookmarks | extension | firefox | 0 | 1232
Contacts | contacts | extension | firefox | 0 | 105
Language Support | language-support | extension | firefox | 0 | 670
Photos, Music & Videos | photos-music-videos | extension | firefox | 0 | 1356
RSS, News and Blogging | rss-news-and-blogging | extension | firefox | 0 | 94
Web and Developer Tools | web-and-developer-tools | extension | firefox | 0 | 167
Downloading and File Management | downloading-and-file-management | extension | firefox | 0 | 102
Privacy and Security | privacy-and-security | extension | firefox | 0 | 126
Search Tools | search-tools | extension | firefox | 0 | 110
Interface Customizations | interface-customizations | extension | firefox | 0 | 133
Miscellaneous | miscellaneous | extension | firefox | 0 | 288
Miscellaneous | miscellaneous | extension | firefox | 0 | 549
Bookmarks | bookmarks | extension | firefox | 0 | 110
Site-specific | site-specific | extension | firefox | 0 | 130
Language Support and Translation | language-support-and-translation | extension | firefox | 0 | 60
Photos and Media | photos-and-media | extension | firefox | 0 | 66
Message and News Reading | message-and-news-reading | extension | firefox | 0 | 406
Privacy and Security | privacy-and-security | extension | firefox | 0 | 157
Language Support | language-support | extension | firefox | 0 | 101
Social & Communication | social-communication | extension | firefox | 0 | 2291
Alerts & Updates | alerts-updates | extension | firefox | 0 | 1322
Other | other | extension | firefox | 333 | 1758
Calendar Enhancements | calendar-enhancements | extension | firefox | 0 | 38
Providers | providers | extension | firefox | 0 | 4
Language Support and Translation | language-support-and-translation | extension | firefox | 0 | 2
Tabs | tabs | extension | firefox | 0 | 998
Experimental | experimental | extension | firefox | 0 | 83
User Interface | user-interface | extension | firefox | 0 | 80
Security & Privacy | security-privacy | extension | firefox | 0 | 38
Shopping | shopping | extension | firefox | 0 | 11
Social Networking | social-networking | extension | firefox | 0 | 42
Feeds, News & Blogging | feeds-news-blogging | extension | firefox | 0 | 28
Sports & Games | sports-games | extension | firefox | 0 | 8
Device Features & Location | device-features-location | extension | firefox | 0 | 19
Performance | performance | extension | firefox | 0 | 27
Photos & Media | photos-media | extension | firefox | 0 | 13
Shopping | shopping | extension | firefox | 0 | 761
Games & Entertainment | games-entertainment | extension | firefox | 0 | 807
Photos & Media | photos-media | extension | firefox | 0 | 30
Performance | performance | extension | firefox | 0 | 37
Device Features & Location | device-features-location | extension | firefox | 0 | 34
Sports & Games | sports-games | extension | firefox | 0 | 12
Feeds, News, & Blogging | feeds-news-blogging | extension | firefox | 0 | 49
Social Networking | social-networking | extension | firefox | 0 | 32
Security & Privacy | security-privacy | extension | firefox | 0 | 52
Shopping | shopping | extension | firefox | 0 | 17
Experimental | experimental | extension | firefox | 0 | 92
User Interface | user-interface | extension | firefox | 0 | 120
Folders and Filters | folders-and-filters | extension | firefox | 0 | 42
Message Composition | composition | extension | firefox | 0 | 67
Calendar and Date/Time | calendar | extension | firefox | 0 | 25
Import/Export | importexport | extension | firefox | 0 | 12
Appearance and Customization | appearance | extension | firefox | 0 | 83
Chat and IM | chat | extension | firefox | 0 | 15
Tags | tags | extension | firefox | 0 | 6
Miscellaneous | miscellaneous | theme |  | 0 | 59
Sports | sports | theme |  | 0 | 38
Nature | nature | theme |  | 0 | 29
Animals | animals | theme |  | 0 | 24
Retro | retro | theme |  | 0 | 70
Compact | compact | theme |  | 0 | 122
Miscellaneous | miscellaneous | theme |  | 0 | 18
Miscellaneous | miscellaneous | theme |  | 0 | 35
OS Integration | os-integration | theme |  | 0 | 191
Modern | modern | theme |  | 0 | 218
Modern | modern | theme |  | 0 | 76
Compact | compact | theme |  | 0 | 53
Nature | nature | theme |  | 0 | 7
Large | large | theme |  | 0 | 27
General | general | theme |  | 0 | 7
General | general | dictionary |  | 0 | 154
General | general | dictionary |  | 0 | 129
General | general | dictionary |  | 0 | 138
Video | video | search |  | 0 | 0
Bookmarks | bookmarks | search |  | 0 | 0
Business | business | search |  | 0 | 0
Dictionaries & Encyclopedias | dictionaries-encyclopedias | search |  | 0 | 0
General | general | search |  | 0 | 0
Kids | kids | search |  | 0 | 0
Multiple Search | multiple-search | search |  | 0 | 1
Music | music | search |  | 0 | 0
News & Blogs | news-blogs | search |  | 0 | 0
Photos & Images | photos-images | search |  | 0 | 1
Shopping & E-Commerce | shopping-e-commerce | search |  | 0 | 1
Social & People | social-people | search |  | 0 | 0
Sports | sports | search |  | 0 | 0
Travel | travel | search |  | 0 | 0
General | general | language |  | 0 | 46
General | general | language |  | 0 | 7
General | general | language |  | 0 | 7
Abstract | abstract | persona |  | 0 | 41984
Nature | nature | persona |  | 0 | 29421
Sports | sports | persona |  | 0 | 22193
Scenery | scenery | persona |  | 0 | 10443
Firefox | firefox | persona |  | 0 | 4718
Foxkeh | foxkeh | persona |  | 0 | 387
Seasonal | seasonal | persona |  | 0 | 798
Other | other | persona |  | 0 | 79479
Websites | websites | persona |  | 0 | 20829
Solid | solid | persona |  | 0 | 5573
Causes | causes | persona |  | 0 | 5013
Music | music | persona |  | 0 | 32320
Fashion | fashion | persona |  | 0 | 9181
Film and TV | film-and-tv | persona |  | 0 | 34055
Holiday | holiday | persona |  | 0 | 4877
Entertainment | entertainment |  | None | 140 | 0
Business | business |  | None | 160 | 0
Games | games |  | None | 180 | 0
Music | music |  | None | 100 | 0
News & Weather | news-weather |  | None | 90 | 0
Productivity | productivity |  | None | 70 | 0
Social | social |  | None | 40 | 0
Travel | travel |  | None | 20 | 0
Books | books |  | None | 170 | 0
Education | education |  | None | 150 | 0
Health & Fitness | health-fitness |  | None | 130 | 0
Lifestyle | lifestyle |  | None | 120 | 0
Photo & Video | photo-video |  | None | 80 | 0
Utilities | utilities |  | None | 10 | 0
Shopping | shopping |  | None | 50 | 0
Sports | sports |  | None | 30 | 0
Reference | reference |  | None | 60 | 0
Maps & Navigation | maps-navigation |  | None | 110 | 0

**Comment by diox** [comment]
Another script which can be useful to generate the slug-id (+ name to prepare for translations later) mapping: 
```
import json

from django.utils.datastructures import OrderedDict

from olympia import amo
from olympia.addons.models import Category

def export_categories():
    dump = {}
    categories = Category.objects.all().order_by(
        'application', 'type', 'weight', 'slug')
    for cat in categories:
        if not cat.application or cat.application not in amo.APP_IDS:
            print u"Ignoring {id} ({name}), invalid app id '{app}'".format(**{
                'id': cat.id, 'name': cat.name, 'app': cat.application,
            })
            continue
        if not cat.type or cat.type not in amo.ADDON_TYPE_CHOICES_API:
            print u"Ignoring {id} ({name}), invalid type '{type}'".format(**{
                'id': cat.id, 'name': cat.name, 'type': cat.type,
            })
            continue
        app = getattr(amo.APP_IDS.get(cat.application), 'short')
        type_ = amo.ADDON_TYPE_CHOICES_API.get(cat.type)
        if app not in dump:
            dump[app] = OrderedDict()
        if type_ not in dump[app]:
            dump[app][type_] = OrderedDict()
        dump[app][type_][cat.slug] = {
            'id': cat.id,
            'name': unicode(cat.name),
        }
    return dump

dump = export_categories()
print json.dumps(dump, indent=4)
```

With the mapping this script generates, we can then deduce an internal category id (to be used to fetch add-ons belonging to the category from the db or elasticsearch) from an application + extension type + slug, reproducing what we have in addons-server now.

**Comment by milupo** [comment]
Hi,

Is it already foreseeable when categories can be translated?

**Comment by diox** [comment]
I can't give you an estimate yet, no. It's very high on my todo list, but the cleanups required are quite complex, lots of moving parts so it's taking some time. I hope to have something ready for next week, but no promises.

**Comment by milupo** [comment]
Thank you, diox. It just doesn't look when there are untranslated strings in such a conspicuous place, directly on the AMO homepage.

**Comment by diox** [comment]
I merged #3190 which adds the strings (importing existing translations I could find on stage in the database) but does not use them yet. So the strings are going to be translatable but those translations are not going to be seen on the pages yet. I'll work on that next.

**Comment by milupo** [comment]
Thank you, diox. Meanwhile I translated the strings including the category names into dsb and hsb.

**Comment by diox** [comment]
I've simplified the issue down to the most important problem: pulling translations out of the db and in our repos. We'll see about tackling the rest separately later.

**Comment by diox** [comment]
QA: once this lands, please test that categories names are displayed correctly everywhere on the site (sidebar, add-ons in listings, etc) and are translated properly.

**Comment by milupo** [comment]
Hi diox, very fine, thank you very much, it works both for hsb and dsb! But, is it correct that it works for the dev-allizom.org server only? For allizom.org and mozilla.org it doesn't work yet. The categories are shown correctly in the sidebar and, as page title, on the category add-on list. The order seems to be correct as well.

**Comment by wagnerand** [comment]
@milupo please see https://github.com/mozilla/addons-server/pull/3210#issuecomment-236887236

**Comment by milupo** [comment]
OK, thank you, wagnerand.

**Comment by vcarciu** [comment]
@diox  : not sure if this looks ok for Japanese (See "Web" word not translated) : http://screencast.com/t/R5zcMbiU79r

I saw that type if issue for many languages

**Comment by diox** [comment]
Looks ok to me ? https://addons.mozilla.org/ja/firefox/ (change hasn't been deployed to prod yet) shows the same thing.

**Comment by vcarciu** [comment]
Yes I know , but maybe it is an issue in prod too :) ... but you are right , if it is an issue it is not related to this bug

**Comment by diox** [comment]
I think it's just a choice of the translator to keep the "web" part of the word in English.

**Comment by diox** [comment]
@vcarciu btw I added more changes to categories today on dev. I did a cursory check and it seemed fine, but can you also check that saving categories when submitting/editing add-on of various types (and themes) still work properly ? Thanks.

**Comment by vcarciu** [comment]
Verified as fixed in all places
