### ISSUE TITLE
Error when trying to translate a review in Editor Tools->Moderated Reviews

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2938]
Steps to reproduce:
1. Sign in with an admin account in AMO-dev
2. Go to Editor Tools- Moderated Reviews queue
3. Click the "translate" link for any review

Expected results:
The review is translated.

Actual results:
The review is not translated. The message "Error loading translation" is displayed.

Notes/Issues:
A 500 error code appears in the console.
Verified on AMO-dev FF47(Win 7). Issue is not reproducing on AMo-stage.
Screenshot for this issue: 
![translate](https://cloud.githubusercontent.com/assets/15685960/16224099/43cac2b6-37a9-11e6-8c14-3a7739f72d1a.png)

**Comment by andymckay-limited-access** [comment]
@eviljeff to investigate and check if its a -dev only issue.

**Comment by eviljeff** [comment]
This works fine on prod and stage; only broken on -dev.  My guess is the google translate API details haven't been setup on -dev (possibly on purpose as it costs us for each request).
