### ISSUE TITLE
Navigation does not work as expected in My Profile page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2940]
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Go to My Profile page ( i.e https://addons-dev.allizom.org/en-US/firefox/user/TestDev123/)
3. Navigate through "Add-ons I've created" section
4. Observe the "My Reviews" section

Expected results:
The navigation works only for the section on which the user makes an action.

Actual results:
Both sections are moved to next pages.

Notes/Issues:
Other issues appear if the number of the pages for these two sections are different.
Verified on FF47(Win 7). Issue is reproducing on AMO-stage and dev.
Screencast for this issue: 
![nav-myprofile](https://cloud.githubusercontent.com/assets/15685960/16228153/eabbc430-37bd-11e6-9986-3deddfff9b03.gif)

**Comment by wagnerand** [comment]
Closing this as WONTFIX for now, we'll do this in the rewrite, unless someone really wants to do this now.
