### ISSUE TITLE
Unable to change license in devhub for 'Incomplete' add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2941]
Add-ons that have status `Incomplete` miss the "License" block on the devhub page `/developers/addon/<ADDON>/ownership`.

STR:
1. Submit new add-on.
2. Reject it the initial submission.
3. Go to `/developers/addon/<ADDON>/ownership`

**Comment by andymckay-limited-access** [comment]
The license is on the version model in Django, but there is no valid version at this point.

At this point we don't think we should worry about it, maybe something to address in the redesign?
