### ISSUE TITLE
Tooltip under "Not available for Firefox" text is not working when hovering over it

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2942]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Step to reproduce:
1.Go to any addons listing page where we have an incompatible addon (ie. see first addon from https://addons-dev.allizom.org/en-US/firefox/search/?q=evernote&cat=1%2C0&appver=47.0&platform=windows )
2.Hover over the addon and observe the Tooltip under "Not available for Firefox" text
3.Hover over the tooltip

Expected results:
Tooltip text is automatically displayed when hovering over it

Actual results:
Nothing happens

Please see video for this bug : 
![tooltip2](https://cloud.githubusercontent.com/assets/1583842/16231163/af74d21c-37cd-11e6-93e7-b018ba2fddeb.gif)

**Comment by andymckay-limited-access** [comment]
We'll get this in the redesign.
