### ISSUE TITLE
"Number of reviews" link from "Developer Profile" - "Addons I've created" is not working

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2947]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Steps to reproduce:
1.Go to any addon developer profile (ie. https://addons-dev.allizom.org/en-US/firefox/user/pearltrees/)
2.From one of created addons , select the number of reviews link

Expected results:
Addon reviews section should be opened

Actual results:
Addon homepage is opened

Please see video for this bug : 
![reviewes](https://cloud.githubusercontent.com/assets/1583842/16233057/ab471b7a-37d5-11e6-9763-ddb664176579.gif)

**Comment by andymckay-limited-access** [comment]
This seems to be intermittent, I think its because #reviews might not be loaded straight away. I think we'll fix or remove this in the new design.
