### ISSUE TITLE
Add hsb and dsb to the credits page

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#2958]
Hi, would you be so kind as to give me your thanks? ;-)

I am the translator for dsb and hsb and I'd appreaciate that you add those two languages with my user name or real name to the credits page if you don't mind doing that - for the sake of completeness ;-).

Thanks and regards

Michael

**Comment by EnTeQuAk** [comment]
I think @eviljeff or @wagnerand can do that. We seem to just need a "hsb Localizers" and "dsb Localizers" group and milupo should be assigned to them. What's your username on AMO @milupo?

**Comment by milupo** [comment]
Thank you, EnTeQuAk. Meanwhile I use "milupo" as my username in all Mozilla projects.

**Comment by eviljeff** [comment]
Done.

We should probably change the way how we do this - creating a group with an access permission for a tool that doesn't exist anymore so the users of that group show up on the credits page is a little odd.

**Comment by vcarciu** [comment]
@eviljeff  : where can we see if this was correctly added?

**Comment by milupo** [comment]
Thank you Andrew, I can see it even already on the mozilla.org pages.
 
@vcarciu: Here: https://addons.mozilla.org/en-US/credits

**Comment by vcarciu** [comment]
Thanks, we will mark it as verified.
