### ISSUE TITLE
Adding an Add-on to a collection causes layout issues for page footer

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2959]
Steps to reproduce:
1. Load a collection details page ( i.e. https://addons.allizom.org/en-US/firefox/collections/mozilla/privacy/ )
2. Go to the add-ons from the bottom of the page and hover over "Add to collection" icon
3. Observe page footer

Expected results:
There are no display or layout issues.

Actual results:
There is a white padding under the footer.

Notes/Issues:
Suggestion: we can show the list of the created collections in the upper side of the icon, or add a scroll bar (if there are more collections)
Verified on FF47(Win 7). Issue is reproducing on AMO-stage, dev and prod.
This applies also when trying to create a collection from the same place mentioned at step 2.
Screencast for this issue: 
![footer](https://cloud.githubusercontent.com/assets/15685960/16266622/7aceb4e4-388e-11e6-8b26-9f353b51ce6c.gif)

**Comment by shell15** [comment]
we aren't investing work into non- functionality blockers until the visual styling front-end refresh.
