### ISSUE TITLE
Removed add-on displayed in the promo banner

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2966]
**Steps to reproduce:**
1. Open https://addons.mozilla.org/en-US/firefox/ and observe the promo banner 

**Expected results:**
All the addons featured in there are available.

**Actual results:**
The Pocket add-on is removed. When clicking on it's icon the "This add-on has been removed by its author. " message it is displayed.

**Notes/Issues:**
Verified in FF47(Win7) Issue can be reproduced in production.
Screencast for this issue:
![pocketremoved](https://cloud.githubusercontent.com/assets/15685441/16275038/f9bb9d04-38b0-11e6-9d8e-b9515e96b506.gif)

**Comment by devaneymoz** [comment]
Collection has been pulled down until we can perform a thorough review of its content.

**Comment by madalincm** [comment]
The collection is removed. Marking this issue as verified for now.
