### ISSUE TITLE
Normal Reviewers cant access rejected addons after initial review

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#2969]
It seems that if an addon is reviewed and rejected for the first time (no prior history), normal reviewers cant access the review page. However, admin reviewers can.

Example:
`https://addons.mozilla.org/en-US/editors/review/socialmonkee`

> Oops! We had an error.
> 
> We'll get to fixing that soon.
> 
> You can try refreshing the page, or head back to the Add-ons homepage.

**Comment by wagnerand** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/333612/

**Comment by vcarciu** [comment]
Verified as fixed using https://addons-dev.allizom.org/en-US/editors/review/rejectionview , with a normal reviewer account
