### ISSUE TITLE
Detect explicit non-e10s add-ons

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#2972]
It was pointed out that there's at least one more state, where someone has said in their add-on that they do not support multiprocess at all and multiProcessCompatible is false. Probably simple to add in, not sure if its worth doing the backfill though.

Supports #2770

**Comment by diox** [comment]
Good point, I'll add that.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7).
An add-on with "multiprocessCompatible" set to FALSE has the Multi Process Status "Incompatible".
Postfix screenshot: 
![2016-06-24_1421](https://cloud.githubusercontent.com/assets/15685960/16336741/4c1ef52e-3a18-11e6-8f5f-0e05eeb3d488.png)

Also, an add-on without a "multiprocessCompatible" option has the Multi Process Status "Unknown"
