### ISSUE TITLE
Delete "RereviewQueue" model

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#2979]
This model was intended for apps, which never really happened.

The model and the according database table "rereview_queue" should be deleted.

**Comment by diox** [comment]
Technically apps happened, just not on AMO :)

**Comment by wagnerand** [comment]
That's what I meant to say.

**Comment by lavish205** [comment]
This issue is bit similar to #1771 
I can work on this issue

**Comment by wagnerand** [comment]
Mentor: me.

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

**Comment by lavish205** [comment]
There are two more similar models, `RereviewQueueTheme` and `RereviewQueueThemeManager`, should I remove these two as well?

**Comment by lavish205** [comment]
There are two more similar models, `RereviewQueueTheme` and `RereviewQueueThemeManager`, should I remove these two as well?

**Comment by wagnerand** [comment]
No.

**Comment by madalincm** [comment]
Plead add some steps to reproduce or add the label "needs no qa" if no QA is needed.
