### ISSUE TITLE
"^spanning$" error when submitting a web-extension in AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2980]
Steps to reproduce:
1. Try to submit the attached web-extension using https://addons-dev.allizom.org/en-US/developers/addon/submit/2

Expected results:
The web-extension can be submitted or a more clear message is displayed.

Actual results:
The web-extension cannot be submitted  and the error "/incognito" should match pattern "^spanning$" is displayed at validation.

Notes/Issues:
Issue is NOT reproducing on AMO-stage.
Could be related to #2962 .
Screenshot for this issue: 
![incognito](https://cloud.githubusercontent.com/assets/15685960/16303435/5376ee40-3959-11e6-862f-a7df1cb5521c.png)

Attaching used web-extension.
[Google-Art-Project_v1.0.37.zip](https://github.com/mozilla/addons-server/files/329951/Google-Art-Project_v1.0.37.zip)

**Comment by muffinresearch** [comment]
This looks like this is expected: https://github.com/mozilla/addons-linter/blob/master/src/schema/manifest-schema.json#L134

See also https://github.com/mozilla/addons-linter/issues/728

**Comment by muffinresearch** [comment]
@andymckay can you confirm this is the expected behaviour by virtue of pulling in the changes in the schema?

**Comment by andymckay** [comment]
It is expected and a good thing see https://bugzilla.mozilla.org/show_bug.cgi?id=1277686 for more.
