### ISSUE TITLE
Homepage promotion points to wrong collection

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#2990]
This is where our Homepage carousel promotions are managed:
https://addons.mozilla.org/en-US/firefox/discovery/modules

Therein you'll find something called the "Webdev Collection"

We recently promoted the "Webdev Collection" but discovered it wrongly featured content from the "[Reference Desk](https://addons.mozilla.org/en-US/firefox/collections/mozilla/reference/)" collection; whereas it should point to the "[Web Developer's Toolbox](https://addons.mozilla.org/en-US/firefox/collections/mozilla/webdeveloper/)". 

Can we make sure the Webdev Collection points to the right source for future promotion? Thanks!

**Comment by diox** [comment]
Indeed, the code references the collection by primary key and not by slug, and well, that primary key somehow is the one for the "Reference Desk" collection. I'll switch it to use author + slug and point to the right collection.

**Comment by diox** [comment]
Will be fixed by #2995 when it lands on prod on Thursday. It'll be on stage later today.

**Comment by madalincm** [comment]
Plead add some steps to reproduce or add the label "needs no qa" if no QA is needed.
