### ISSUE TITLE
Amazon Universal registry button won't install

### ISSUE THREAD

**Issue by WendynWicket** [mozilla/addons-server#2991]
The add on from Amazon for the Universal Registry or Wish List item from any webpage won't install. Please remedy this as I used to be able to use this add on just fine.

**Comment by tofumatt** [comment]
Could you please link to the add-on? Thanks.

- tofumatt

**Comment by WendynWicket** [comment]
Sorry. Here is the link https://www.amazon.com/gp/registry/universal/?ref=sxts_snpl_1_1_2448932322&qid=1466726895&pf_rd_t=301&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=2448932322&pf_rd_i=universal+wish+list+button&pf_rd_r=MG0PV9AESYEK5R9HZZAA&pf_rd_s=desktop-signpost

________________________________

**Comment by andymckay** [comment]
The add-on has been removed by the author:

https://addons.mozilla.org/en-US/firefox/addon/add-to-amazon-wish-list-button/

You would have to contact the add-on author for more information.
