### ISSUE TITLE
AttributeError: 'module' object has no attribute 'config' .services/utils.py

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/addons-server#2994]
Seeing this traceback on service startup for update and theme-update services. Looks like it started happening after https://github.com/mozilla/addons-server/pull/2965

`
Traceback (most recent call last):
File "./services/wsgi/versioncheck.py", line 13, in <module>
from update import application
File "/data/olympia/services/update.py", line 31, in <module>
log_configure()
File "/data/olympia/services/utils.py", line 129, in log_configure
logging.config.dictConfig(cfg)
AttributeError: 'module' object has no attribute 'config'
unable to load app 0 (mountpoint='') (callable not found or import error)
`

**Comment by madalincm** [comment]
Can you please add some steps to reproduce for this issue or mark it with the needs no qa label if no qa is needed.

**Comment by diox** [comment]
@jasonthomas can you confirm that it's working now ?

**Comment by jasonthomas** [comment]
Yes it is working now.
