### ISSUE TITLE
iTunes is prompting for an "iCloud Bookmarks extension for Firefox" ...

### ISSUE THREAD

**Issue by MizLiberty** [mozilla/addons-server#3004]
I am setting up iCloud on my laptop, and when iTunes is prompts for an "iCloud Bookmarks extension for Firefox" to be added, but the redirect results in a firefox error message [HERE](https://addons.mozilla.org/en-US/firefox/addon/icloud-bookmarks/)
What gives?

**Comment by jvillalobos** [comment]
The extension was removed from the site due to stability problems.
