### ISSUE TITLE
Add-ons get into a state waiting for full review but versions not actually pending review

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#3005]
I've seen this recently on two add-ons. The add-on is in the "pending full review" state, but the latest version is actually in the statue preliminary reviewed. This causes the only available actions to be "request super review", "request more information" and "comment".

I first though this was due to a reviewer mistake in the [せどり サーチ](https://addons.mozilla.org/en-US/editors/review/%E3%81%9B%E3%81%A9%E3%82%8A-%E3%82%B5%E3%83%BC%E3%83%81) extension and corrected the status via admin page, but then I also found it in the [happyload](https://addons.mozilla.org/en-US/editors/review/happyload) extension, which is unlisted and just received automatic review. I left the state on the unlisted add-on for now in case someone wants to investigate.

May be coincidental edge case, but I wanted to make sure it is known.

**Comment by wagnerand** [comment]
Are you sure the add-on status is "Pending Full review". I think you meant "Preliminary reviewed and awaiting full review". If so, this is getting fixed by #2992.

In the meantime, admins can just manually set the add-on status to "Awaiting full review" and then approve it.

**Comment by kewisch** [comment]
Ah yes, "Preliminary reviewed and awaiting full review" is correct. Thanks for the link!
