### ISSUE TITLE
Upgrade certifi

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3006]
We should upgrade certifi as the version we are using is quite old. We tried to do this in #2908 and it caused #2988, forcing us to revert.

The issue is, to work correctly, the latest version of certifi needs openssl 1.0.2 or greater. There are 3 different solutions:
1. Keep an old version of certifi, or use the old weak PEM bundle that the previous version used. This is bad for security.
2. Upgrade our servers to use OpenSSL to 1.0.2. Sadly, it's not available for RHEL 7 yet.
3. Upgrade python cryptography module and build it against openssl 1.0.2 statically as documented here : https://cryptography.io/en/latest/installation/#static-wheels - then figure out a way to use that and not the one from pypi.

Marketplace used option 3. It's the best option for us as well I think, except that we no longer use pyrepo so we have to find another trick to make sure our production - and docker? - builds are using our specially crafted module.

@jasonthomas any idea how we can proceed ?

**Comment by EnTeQuAk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1403271 to figure out a way, a newer OpenSSL is now available on RHEL7 but Python is not linked against it apparently.

**Comment by EnTeQuAk** [comment]
tbh… I can't reproduce this error anymore...

```
pip list | grep certifi
certifi (0.0.8)
[root@6f5221827868 code]# python -c "import requests; requests.get('https://paypal.com', verify=True)"
[root@6f5221827868 code]# python -c "import requests; requests.get('https://bucket-name.s3.amazonaws.com/', verify=True)"
[root@6f5221827868 code]# pip install --upgrade certifi
Collecting certifi
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 2.3MB/s
Installing collected packages: certifi
  Found existing installation: certifi 0.0.8
    Uninstalling certifi-0.0.8:
      Successfully uninstalled certifi-0.0.8
Successfully installed certifi-2017.7.27.1
[root@6f5221827868 code]# python -c "import requests; requests.get('https://bucket-name.s3.amazonaws.com/', verify=True)"
[root@6f5221827868 code]# python -c "import requests; requests.get('https://paypal.com', verify=True)"
[root@6f5221827868 code]# python -c "import requests; requests.get('https://www.google.com', verify=True)"
```

I think that's because the installed `cryptography` is linked against OpenSSL 1.1.0f:

```
[root@6f5221827868 code]# python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"
OpenSSL 1.1.0f  25 May 2017
```

Verified on stage too:

```
[olympia@ip-172-31-39-127 olympia]$ python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"
OpenSSL 1.1.0f  25 May 2017
```

Let's give this another shot?

**Comment by EnTeQuAk** [comment]
I think this comes from cryptography now statically being build against OpenSSL 1.1.0f: https://github.com/pyca/infra/blob/master/cryptography-manylinux1/install_openssl.sh

Yeay!

**Comment by EnTeQuAk** [comment]
QA: Make sure PayPal contributions still work.

**Comment by EnTeQuAk** [comment]
I switched the flag on dev and tested contributions there and it seems to work fine for me.

Going to switch back to simplified contributions again.

**Comment by jrbenny35** [comment]
You forgot one: https://github.com/mozilla/addons-server/blob/master/requirements/docs.txt

**Comment by EnTeQuAk** [comment]
indeed I did. Will be fixed in https://github.com/mozilla/addons-server/pull/6530
