### ISSUE TITLE
 403 Forbidden when trying to view raw file

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3007]
(Clone of https://github.com/mozilla/amo-validator/issues/441)

Quite regularly, trying the **Download ******\*  links at the bottom (ie view) results in **403 Forbidden**

Example:
`https://addons.cdn.mozilla.net/en-US/firefox/files/browse/459606/file-serve/modules/BrandThunderUtils.jsm?token=c568f0b0-e701-4990-a960-65cefaa3362a`

**Comment by eviljeff** [comment]
which add-on(s) and file(s) - link to example please.

**Comment by EnTeQuAk** [comment]
@erosman reported this initially. Do you have some more information on this, e.g to maybe reproduce this properly?

**Comment by erosman** [comment]
The bug was posted 4 months ago. I will post an example, once I come across another one.

**Comment by wagnerand** [comment]
The example in my first comment still works for me.

Am Samstag, 8. Oktober 2016 schrieb erosman :

**Comment by erosman** [comment]
Here is another example:
`https://addons.mozilla.org/en-US/firefox/files/compare/519205...518717/file/data/panel.html#top`

**Comment by wagnerand** [comment]
I am closing this since the add-on in the original report is no longer available. The add-on in https://github.com/mozilla/addons-server/issues/3007#issuecomment-252412587 works now.

If I remember correctly, @EnTeQuAk did some related work that should fix this. If not, please report new occurrences here.
