### ISSUE TITLE
Info Request attached to the wrong version

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#3008]
I rejected an addon. I needed to post additional comments which was done via "Request more information". Previously that was working as it should.

I noticed today that it was attached to the last passed version and not the current but rejected one.

Ref: `https://addons.mozilla.org/en-US/editors/review/klamm-de-websuche-gutscheine`

Re-posted from: https://github.com/mozilla/amo-validator/issues/440

**Comment by eviljeff** [comment]
Argh! sorry, didn't see you'd reposted it already so I just created #3011 - I'll keep that one.
