### ISSUE TITLE
Stop indexing compatibility data for anything other than recent versions of Firefox

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3010]
When we run the `compatibility_report` cron we index compatibility data for all add-ons, for all applications, for all versions of these applications.

This means we fill our elasticsearch cluster with compatibility data for very old versions of applications, like Firefox 4.0. Do we really need to do that ? It's going to continue growing, increasing time spent in that cron, time spent when reindexing, adding a bunch of data we don't really need and that probably kills perf.

**Comment by diox** [comment]
Side-note if you were looking to look into this like me: it's not working on dev/stage, because it depends on `UpdateCount`, which itself depends on hive data, which does not work on dev/stage. Locally, you can manually add some `UpdateCount` in your db to make it work.

**Comment by diox** [comment]
@jvillalobos what's your take on this ? How many versions should we show/support in the /admin/compat/ tool ? What about add-ons search ?

**Comment by jvillalobos** [comment]
We should support versions at least back to the last ESR. Covering the last 7 major release versions of each application (plus the prerelease versions) should be sufficient. Currently, for Firefox that would mean 40 (current release is 47) to 50 (current nightly).

**Comment by diox** [comment]
Cool, I'll look into this some day if I have time...

**Comment by diox** [comment]
Per IRC discussion, we don't even care about compatibility reports for Thunderbird and Seamonkey:
```
<TheOne> the last non-Firefox compat report ran more than two years ago, and that was Thunderbird
<TheOne> compat reports for Seamonkey were never run
```

@jorgev gave its OK to kill the compat info for Thunderbird and Seamonkey in addition to the outdated Firefox versions (see comments above), this should save us a lot of space in ES, and make reindex much faster.
