### ISSUE TITLE
Allow review comments to be added to rejected versions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3011]
From mozilla/amo-validator#440 

@9817742ad changed what is the `latest_version` so that rejected versions aren't considered.  So if a version is rejected in the editor tools then follow up review content (e.g. info requests) aren't attached to that version any more.  We'll need a `last_but_not_necessarily_latest_version` property :)

**Comment by eviljeff** [comment]
I'm assigning this to me but it'll be a long while until I can do it so please take it if you can.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7 x64)
Postfix screenshots: 
![log](https://cloud.githubusercontent.com/assets/15685960/17131457/3b58e16a-5326-11e6-90ce-74094ad2c799.png)
![review_theme_title](https://cloud.githubusercontent.com/assets/15685960/17131456/3b58ba64-5326-11e6-9ee0-cb560ce968c8.png)
