### ISSUE TITLE
Known libraries are not marked for webextensions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3015]
[Archive.zip](https://github.com/mozilla/addons-server/files/337169/Archive.zip)

This test file contains jQuery 2.2.3 which is successfully recognized by the linter, but that information is not exposed on AMO, neither in the validation report, nor in the source/diff viewer.

**Comment by eviljeff** [comment]
How can we tell it's successfully recognised by the linter?

**Comment by wagnerand** [comment]
`$ mv Archive.zip Archive.xpi`
`$ bin/addons-linter Archive.xpi`

**Comment by andymckay** [comment]
@tofumatt and @EnTeQuAk could you take a look at this for @wagnerand please and see if we can do something for the next tab?

**Comment by EnTeQuAk** [comment]
This is simply not implemented. I'll take a look at it, the linter exposes the data as does the validator so it should be relatively straight forward to implement.

**Comment by vcarciu** [comment]
@EnTeQuAk 
Can you please add some STRs to this issue or mark it as "needs no qa" ?
