### ISSUE TITLE
Add way to fetch featured (for homepage or a category) add-ons in the API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3017]
We need an API to return featured add-ons (or only extensions, or only themes) for the homepage and the category pages.

"Featured Add-ons" is an old clunky mechanism. It's not just a search+sort like other sort options. Here is how it works:
- The code calls `get_featured_ids()` with the right `app`, `lang` and optionally `type`.
- `get_featured_ids()` does fancy joins on the collection table to find add-ons belonging to featured collections matching the lang or without a locale. So it will always return the globally featured add-ons, optionally adding some locale-specific ones if there are any

If you request featured add-ons for a specific category, you call `get_creatured_ids()` instead. You don't need to pass an `app`, because you pass a specific category, and categories are separated for each app. But it works the same way, except slightly weirder.

All of this is then used in the homepage and category pages.

**Comment by andymckay** [comment]
Supports mozilla/addons#151

**Comment by diox** [comment]
The API will probably look something like this:
`/api/v3/addons/featured/`

With `app`, `appversion`, `platform`, `type`, `category` (and `lang`, like everywhere else) query parameters accepted as per the search API. `sort` wouldn't make sense since it's editorial content.
