### ISSUE TITLE
White background for Sign In button while waiting spinning wheel is displayed

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3026]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Steps to reproduce:
1.Go to AMO-Stage and Sign in with a known user
2.After entering password and pressing Enter, observe the background of Sign In button while waiting for user to be signed in

Expected results:
Background of Sign In button is Grey and waiting spinning wheel is visible

Actual results:
Background of Sign In button is white and the spinning wheel is almost invisible

NOTES: NOT reproducible on -dev

Please see video for this issue: 
![throbber](https://cloud.githubusercontent.com/assets/1583842/16456786/d3582026-3e21-11e6-84b9-cba0f0f5910e.gif)

**Comment by andymckay** [comment]
Sorry, you'd need to file that against Firefox Accounts, its not a page we control. Unfortunately its hard to move bugs in github, Firefox Accounts is here: https://github.com/mozilla/fxa
