### ISSUE TITLE
iCloud Bookmarks extention for Safari

### ISSUE THREAD

**Issue by rmshake** [mozilla/addons-server#3027]
I downloaded to my windows laptop and when I clicked on the link to download the iCloud Bookmark extention for Safari to use with my iCloud account it came up with an error with all info listed below:

We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.

Please tell me how to fix this issue so I can use Firefox.

**Comment by tofumatt** [comment]
Sadly the extension was removed because of stability problems; see #3004. It is no longer available for Firefox.

@jvillalobos That said, I think we should have a page there explaining why or letting users know it's disabled? I imagine... do we have any stats on how often that page is hit?

**Comment by jvillalobos** [comment]
Best I can offer is a blocklist page: https://addons.mozilla.org/firefox/blocked/i1214

Disabled add-on pages don't offer much information, unfortunately, but it's also rare that such a high-profile add-on is disabled.

**Comment by tofumatt** [comment]
Understood.

If we could redirect to that page it’d be great; is there code to do
redirects like this in place? If not I dunno if it’s worth it, but if so
(or if we can just do a Django redirect, if there’s prior art for that) I’d
say we go for it.

**Comment by jvillalobos** [comment]
We've never done that before, so my guess is no.

**Comment by andymckay** [comment]
One thing I'd really like to see is the ability to do more when an add-on is disabled, or merely no longer supported by a developer and they'd like to recommend another add-on. This is something we've struggled with for a while, I think we can do better.
