### ISSUE TITLE
Author can't access listing page for a hidden add-on

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3030]
**Steps to reproduce:**
1. Open the my submission page: https://addons.allizom.org/en-US/developers/addons
2. Open Manage Status & Versions page for an add-on and change the visibility to hidden
3. Open the add-on listing page.

**Expected results:**
The author can view his add-on listing page.

**Actual results:**
"This add-on has been removed by its author."  message is displayed.

**Notes/Issues**:
Verified in FF47(Win7) Issue can be reproduced in amo-stage
![hiddenlistingpage](https://cloud.githubusercontent.com/assets/15685441/16481119/38b7b996-3eb2-11e6-834b-5d60f63f8516.gif)

**Comment by diox** [comment]
@madalincm is it a regression ?

**Comment by madalincm** [comment]
I think it is, but probably an old one. In production following the same scenario you receive a 404 message but you do not get the  This add-on has been removed by its author. Just a generic 404 page.
![hiddenaddonproduction](https://cloud.githubusercontent.com/assets/15685441/16488805/021762aa-3edb-11e6-8058-8ec88ff3da01.gif)

**Comment by wagnerand** [comment]
If we show a hidden listing to its owner, we need to add a clear note at the top that this listing cannot be seen by anyone else or something.

**Comment by jvillalobos** [comment]
"This add-on has been removed by its author." is the expected result, so this isn't really a bug.

Getting a 404 as in @madalincm's last comment would be a bug, unless that add-on didn't have any versions.

**Comment by muffinresearch** [comment]
This is not an issue with the new frontend so I'm going to close this as wontfix.
