### ISSUE TITLE
Broken Link: Google Minimalist

### ISSUE THREAD

**Issue by eadsjr** [mozilla/addons-server#3037]
Link to new project from here does not work: https://addons.mozilla.org/en-US/firefox/addon/customizegoogle/

**Comment by tofumatt** [comment]
@eadsjr Thanks for the report. Unfortunately the add-on they're linking to isn't available anymore and it's the developer who is responsible for those links, but I'll see if we can fix it up. Thanks for letting us know!

@jvillalobos Would it be appropriate to just remove the link from the description? I think I have admin rights so I could probably do it if that's okay.

**Comment by jvillalobos** [comment]
I removed it, thanks.

**Comment by madalincm** [comment]
The link was removed from the description 
Marking as verified fixed.
![descriptionlinkremoved](https://cloud.githubusercontent.com/assets/15685441/16660047/78fbb8fe-4475-11e6-88c0-8b2c5a4e090c.png)
