### ISSUE TITLE
User cannot delete their account if they have deleted add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3038]
Even after a user deleted all of their add-ons, they cannot delete their account.

It should be possible for a user to delete their account in that case. We need to decide what happens with the GUIDs that used to belong to the user. Maybe add it to the blacklist?

**Comment by wagnerand** [comment]
Adding @jvillalobos.

**Comment by jvillalobos** [comment]
I suggest keeping the add-ons in a Deleted state, and associate them to a special graveyard account.

**Comment by ValentinaPC** [comment]
This is happening for a while (https://bugzilla.mozilla.org/show_bug.cgi?id=1210751)
Thanks for taking care of this1

**Comment by diox** [comment]
Is it still happening ? I think https://github.com/mozilla/addons-server/pull/4554 should have fixed this.

**Comment by vcarciu** [comment]
Verified as fixed : 
![delacc](https://cloud.githubusercontent.com/assets/1583842/24108032/17bb3076-0d95-11e7-8ac9-e9852ad84605.gif)
