### ISSUE TITLE
Validator not properly validate WebExtensions

### ISSUE THREAD

**Issue by teo951** [mozilla/addons-server#3041]
As in the title. Validator does not detect any problems in almost all the WebExtensions add-ons. Also as Andreas reports, Validator not recognize valid js libraries.

**Comment by muffinresearch** [comment]
Hi - we'll need a bit more information to go on.

Please provide links to any extensions you're testing and the problems you're seeing and how that differs from what you expect.

**Comment by teo951** [comment]
Please pay attention on using innerHTML in this add-on: https://addons.mozilla.org/en-US/editors/review/stackexchangenotifications
Validator not reports any problems.

**Comment by muffinresearch** [comment]
@wagnerand I don't have access to this link. Any chance you can add more details to this bug or file a new bug on addons-linter with details of what's not working?

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/addons-linter/issues/811
