### ISSUE TITLE
"Incomplete" status for one-version add-on after re-enable

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3051]
Steps to reproduce:
1. Submit a listed add-on https://addons.allizom.org/en-US/developers/addon/submit/2
2. Approve the submitted add-on
3. Go to Manage Status & Versions and disable add-on version 
4. Re-enable the disabled version

Expected results:
Add-o status returns to its initial state.

Actual results:
Add-on status is incomplete.

Notes/Issues: 
Two links: "Request Preliminary Review · Request Full Review " are displayed under the version, but if clicked the add-on is not listed in any queue from editor Tools and the status of the add-on remains "awaiting..."...forever. If add-on review page is accessed the add-on appears "reviewed".
Verified on FF47(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Screencast for this issue: 
![disable add-on](https://cloud.githubusercontent.com/assets/15685960/16618304/5c56046e-4391-11e6-9af7-e3a2bb6d570b.gif)

May be related to #2609

**Comment by jvillalobos** [comment]
That's odd. Since when do we have the option to re-enable a version? How could we tell between a version disabled by admins and a version disabled by the developer? cc @wagnerand @eviljeff

**Comment by wagnerand** [comment]
Since 79c57f87. We try to determine __user disabled__ vs __Mozilla disabled__ by checking whether the previous file status is __incomplete__ iiuc.

I think @eviljeff can give a better answer here.

**Comment by ValentinaPC** [comment]
from IRC: "eviljeff: ValentinaP: correct, should return to the initial status. (re #2609)"

**Comment by jvillalobos** [comment]
Then it seems that re-enabling the version should also check the global add-on status and also adjust it accordingly. There's a plan to fix some of these status complications in a cleaner way, but I don't know if we'll get to them this year.

**Comment by eviljeff** [comment]
Add-on status is [supposed](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/views.py#L1226) to be updated after the version is re-enabled but it possible/probable doesn't handle the incomplete case.

**Comment by eviljeff** [comment]
is this issue still occurring?

**Comment by ValentinaPC** [comment]
Yes. 
Verified on AMO-dev FF50(Win 7).
Please see the video:
![incomplete](https://cloud.githubusercontent.com/assets/15685960/22288003/bf6b6dbc-e2fd-11e6-8d0b-d8e4fa860f39.gif)

**Comment by muffinresearch** [comment]
Hmm is this still relevant in a post-review world? 

@vcarciu would you have a moment to see if this is reproducible a year later?

**Comment by wagnerand** [comment]
It should still be relevant, the problem is not related to post-review, but disabling and enabling versions can lead to an invalid status.

**Comment by AlexandraMoga** [comment]
@muffinresearch I can still reproduce this in a similar way for auto-approved add-ons. The difference now is that the user doesn't have the possibility to request another review, so the add-on will be stuck in an 'Incomplete' status:
![incomplete](https://user-images.githubusercontent.com/31961530/35852956-f336201e-0b34-11e8-947f-821353894b11.gif)

**Comment by AlexandraMoga** [comment]
This is now applicable to static theme review as well.

**Comment by AlexandraMoga** [comment]
Still an issue

**Comment by diox** [comment]
I haven't been able to reproduce using those STRs. The add-on gets "approved" status back.

**Comment by AlexandraMoga** [comment]
I wasn't able to reproduce based on those STR either. I've also tried with a version that was still "Awaiting Review" and even for this version the addon status wasn't stuck in "Incomplete" anymore if I Disabled and Re-enabled its only version.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-142
