### ISSUE TITLE
Add support for versionRange in graphics blocklists

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3054]
I learned from [bug 1283601](https://bugzilla.mozilla.org/show_bug.cgi?id=1283601) that there's a new attribute in graphics blocklist entries that needs to be supported in our admin interface. It's necessary in order to resolve that bug, so it can't wait for the move to kinto.

What we need is for gfx entries to have two additional text fields: Max application version, Min application version. They should both be optional. If either has a value, the `versionRange` node should be added as a child of the `gfxBlacklistEntry`, like in these examples:

`<versionRange maxVersion="49.9" />`
`<versionRange minVersion="40.0a1" />`
`<versionRange minVersion="48.0.2" maxVersion="49.*" />`

cc @n1k0 for the kinto side of this.

**Comment by n1k0** [comment]
I've filed https://github.com/mozilla-services/amo2kinto/issues/39 about this.

**Comment by andymckay** [comment]
Sorry @EnTeQuAk would you have time to look at this?

**Comment by EnTeQuAk** [comment]
eh, I tried to duck away but I guess I'll take a look at it asap :laughing:

**Comment by EnTeQuAk** [comment]
@n1k0 @Natim should I add support for this in `gfxs_to_json` while I'm at it or do you do that once you're working on the Kinto side?

**Comment by n1k0** [comment]
@EnTeQuAk that'd be helpful yes, thanks!

Note: we're both off today and tomorrow (14th of July in france + PTO)

**Comment by EnTeQuAk** [comment]
@n10k I added support for the versionRange into the json serialization too. Let me know if that works properly :)

**Comment by Natim** [comment]
@EnTeQuAk do you know if we can have a gfx_item configured with versionRange in dev to test it?

**Comment by EnTeQuAk** [comment]
We do, it's on dev, stage and prod so feel free to configure it or let me know on IRC if I should prepare something.
