### ISSUE TITLE
New homepage carousel promo: Must-Have Media

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#3063]
Time to promote a new custom collection on the homepage. Similar to our recent “Games!” promotion, can we please get the following collection placed into the [Disco Pane management tool](https://addons.mozilla.org/en-US/firefox/discovery/modules) by **Tuesday, July 19** (ideally), but the following week works fine too. 

!! Reminder: please make the title in carousel image clickable to the collection’s landing page !! 

https://addons.mozilla.org/firefox/collections/mozilla/must-have-media/

It's fine to re-use the same background image we had on the Games! collection. 

Overlay text (title, blurb):

**Must-Have Media**
Take better screenshots, improve your online video experience, finally learn how to make a GIF, and other great media tools.

**Comment by devaneymoz** [comment]
Thanks for taking care of this, @EnTeQuAk! Do you know when the collection will appear in the Disco Pane management tool so I can publish to the homepage?

**Comment by EnTeQuAk** [comment]
It should already be there, we deployed on Thursday and this feature went into the recent deploy.

**Comment by devaneymoz** [comment]
Weird, I see it now, but swear it wasn't there last week! Thanks, looks great.

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/uiTMLuav0qh
