### ISSUE TITLE
Install documentation is ambiguous for the Linux setup

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#3064]
Install documentation currently says that a VM only needs to be created for Mac and Windows, not for Linux. However, later on it suggests getting the IP address of the VM in order to access the server. It should either suggest creating a VM regardless of operating system or suggest using localhost to access the server on Linux. If it is the latter, it might be a good idea to mention that Docker requires Linux kernel 3.8 or higher - but doesn't enforce it.

**Comment by EnTeQuAk** [comment]
Indeed, I think the docs are written for MacOSX in mind but mostly valid for Linux since most of the team works on a Mac.

**Comment by wagnerand** [comment]
I think someone who is using Linux to work on AMO or someone who is at least familiar with Docker on Linux would be a better fit to fix this.

**Comment by palant** [comment]
In principle, the instructions can be generalized - if you use a VM then Linux is no different than OS X. One *could* skip creating a VM on Linux but IMHO this isn't worth adding more complexity to the documentation. People who know Docker will figure it out by themselves, others don't need to know.

**Comment by tofumatt** [comment]
Going all-VM in the instructions until Docker for Mac works for us (eg is out of beta) seems smart. Once it's out of beta we can just rewrite it to _never_ use VMs 😀

**Comment by wagnerand** [comment]
Maybe we could also wait until the Mac beta goes into release and thus avoid updating the docs twice?

**Comment by eviljeff** [comment]
Using a VM on Linux isn't necessary though, and adds complexity rather than reduces it.  I just ignored every command that referred to `docker-machine` and it worked (iirc) - should I just duplicate the install section for Linux?

**Comment by eviljeff** [comment]
With docker-for-mac (and docker-for-windows) removing the need for a VM I think the [docs](http://addons-server.readthedocs.io/en/latest/topics/install/docker.html) are okay now.  If something still isn't clear file a new issue - a pull request to update the docs, even better.
