### ISSUE TITLE
Error with translations in some add-ons

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3067]
Steps to reproduce:

1.Go to https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2.Try to submit any of the next WebExtensions: 
[Beanote-Note-Taking-on-Page_v0.0.1.zip](https://github.com/mozilla/addons-server/files/357144/Beanote-Note-Taking-on-Page_v0.0.1.zip) , [HoverCards_v2.0.8.zip](https://github.com/mozilla/addons-server/files/357145/HoverCards_v2.0.8.zip)

Expected results:
The WebExtensions are successfully submitted.

Actual results:
The WebExtensions can’t be submited, a 500 server error is displayed

Note/Issues:
Verified on FF50.0a1 (2016-07-10) (Win 7 64-bit).
This issue is reproducing for zip and crx files

Here is a video:
![500](https://cloud.githubusercontent.com/assets/15885467/16731879/196c16de-4783-11e6-9c07-055b33c88f8d.gif)

**Comment by krupa** [comment]
This looks related to https://github.com/mozilla/addons-server/issues/1681

**Comment by EnTeQuAk** [comment]
Okay, so for the hover-cards addon I get:

```ValueError: Error: invalid central directory file header signature: 0xad9e50d1``` and Beanote-Note-Taking-on-Page_v0.0.1.zip works for me locally, hmm. Looking more into it.

**Comment by EnTeQuAk** [comment]
This is the related sentry: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/340477/

**Comment by cosminbadescuSV** [comment]
This issue is not reproducing anymore, video of this issue: 
![hovercards](https://cloud.githubusercontent.com/assets/15885467/16761395/a530efb4-4828-11e6-86a3-6da8feaf9484.gif)

**Comment by EnTeQuAk** [comment]
:tada: :balloon:
