### ISSUE TITLE
Overhaul Contributions on AMO

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3074]
Contribution flows on AMO are needlessly complex and we have regular paypal outages. Time for a overhaul!

**Comment by andymckay** [comment]
The problem with this bug is the same as mozilla/addons#14 and mozilla/addons#15, it's all on paypals side and there's nothing we can do about it while the feature exists other than change the whole feature.

So I'm going to go for the "we'll address this in the rewrite", hopefully.
