### ISSUE TITLE
Hide restartless, focus on requiring restart

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3080]
As e10s rolls out, users will forced to get a restart to move between the e10s cohort and not. Unfortunately we can't detect on AMO if they are in the cohort. The main suggestion has been to hide the restartless flag from AMO.

<img width="140" alt="screenshot 2016-07-12 11 01 27" src="https://cloud.githubusercontent.com/assets/74699/16777821/05250af8-4820-11e6-8e19-80577f6fc5a0.png">

It appears on the add-ons details page and search results, maybe more.

There's a restartless tag: https://addons.mozilla.org/en-US/firefox/tag/restartless that gets added to add-ons, but we really don't advertise that too much. Perhaps we could add a message to that page to say "it may not be restartless".

**Comment by andymckay** [comment]
And once e10s is all done, we can turn this back on. Although since all WebExtensions are restartless, I think we should negatively flag add-ons that are not restartless.

**Comment by EnTeQuAk** [comment]
Is there a due date for this?

**Comment by andymckay** [comment]
Ideally before Firefox 48 goes out.

**Comment by andymckay** [comment]
Hmm, Firefox 48 goes out next week. @diox could we get this into next weeks release please?

**Comment by andymckay** [comment]
Actually lets flip this. We are moving to a world of WebExtensions where everything is restartless (unless the add-on developer forces a restart which is really rare). And roughly 50% of the add-ons now meet this criteria and its getting bigger.

Rather than focus on add-ons that are restartless, less focus on add-ons that require a restart since these are the ones with the  worse user experience.

This also solves the e10s problem. Some add-ons will require a restart even if they don't explicitly say so, but at least we aren't y'know lying.

So:
* remove the "no restart" label
* add in a "requires restart" label
* ... and erm flip the logic around

Restartless should be anything that's an SDK, restartless or a WebExtension add-on. SDK and WebExtensions should have the restartless flag automatically so it should be a simple check (although there was a comment in IRC that this was maybe applied inconsistently).

Hopefully that's not too much extra work and should work in the long term better than a temporary waffle.

**Comment by jvillalobos** [comment]
I suggest changing the color of the tag so people don't confuse it with the current one, and also to make it clearer that it's a con rather than a pro.

**Comment by diox** [comment]
What color do you suggest ? Since it's kind of a negative label, it's unfortunate that the current one is already orange, if we want to change the color...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7 x64)
Postfix screenshots: 
![2016-08-01_1606](https://cloud.githubusercontent.com/assets/15685960/17294907/34770080-5802-11e6-9890-5f74cee53a01.png)
![listing](https://cloud.githubusercontent.com/assets/15685960/17295283/0ede4994-5804-11e6-8e45-5a1041af39af.png)

**Comment by diox** [comment]
Mmm something is wrong with the label, it should have a different styling.

**Comment by ValentinaPC** [comment]
About Editor Tools flags..
![2016-08-01_1639](https://cloud.githubusercontent.com/assets/15685960/17295838/f3260888-5806-11e6-860c-2a4b48fb0138.png)

I don't see the red arrow for "restartless" add-ons, as indicated above.

**Comment by diox** [comment]
You should see it instead for add-ons requiring restart. There is an issue with styling on dev at the moment, though.

**Comment by ValentinaPC** [comment]
Maybe it helps:
-> in add-on review page the flag about requiring a restart is mentioned
![review_page_001](https://cloud.githubusercontent.com/assets/15685960/17296339/6de9b900-5809-11e6-90e9-363700458c29.png)
-> in queue the flag is missing
![2016-08-01reqrestart](https://cloud.githubusercontent.com/assets/15685960/17296353/808061e0-5809-11e6-990f-d3b3309f09bd.png)

**Comment by diox** [comment]
The flag is actually present, the icon is wrong because of the deployment issue we have on dev right now.

**Comment by diox** [comment]
Labels should be fixed now that dev is deploying correctly.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7).
The new label looks as expected.
Postfix screenshots:
![add-on_details](https://cloud.githubusercontent.com/assets/15685960/17300182/fabad0ac-5819-11e6-843b-1a24c142932f.png)
![listing](https://cloud.githubusercontent.com/assets/15685960/17300188/00eb55b4-581a-11e6-96b9-556caad5c204.png)
![queue](https://cloud.githubusercontent.com/assets/15685960/17300198/05fcd58c-581a-11e6-9f4c-bb9583e2f5c0.png)
