### ISSUE TITLE
Implement experimental flag for listed add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3084]
This is part of #3083. Listed add-on developers need a way to flag their add-ons as experimental, so they can be listed but with reduced visibility.

* On Step 3 of the submission process, add a checkbox with the label "This add-on is experimental", not checked by default. I think this should show up between the summary and the categories. It should have a help tooltip explaining that experimental add-ons are listed on the site but have reduced visibility, and that this setting can be changed later.
* In the Developer Hub, under Edit Listing > Basic Information, add a field to edit this flag, also between the summary and categories.
* The experimental flag should be handled like Preliminary Review when it comes to displaying the install buttons for all versions of the add-on (yellow stripes), showing up after other add-ons in search results, and not appearing in the Disco Pane. Other limitations for preliminary add-ons, like contributions and automatic updates, don't apply to add-ons with this flag.
* The text shown with the yellow striped button should be changed from "This add-on has been preliminarily reviewed" to "This add-on has been flagged as experimental by its developers". The Learn More link should not be there.

Reviewers won't manipulate this flag, but can recommend developers to use it when relevant.

**Comment by eviljeff** [comment]
Is `experimental` a per add-on or per version (or per file) attribute?

**Comment by eviljeff** [comment]
> Is experimental a per add-on or per version (or per file) attribute?

I'm going ahead on the assumption it's per add-on, as the text above mentions editing in edit listing.

**Comment by wagnerand** [comment]
Yes, per add-on.

**Comment by jvillalobos** [comment]
Confirming it's per add-on.

**Comment by eviljeff** [comment]
note: the UI to set this flag is behind the waffle flag `no-prelim-review` as we don't want to confuse developers with an experimental flag until preliminary review is gone.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (with flag enabled) using FF47(Win 7 x64)
Postfix screenshots: 
![details](https://cloud.githubusercontent.com/assets/15685960/17401617/4a5580fa-5a57-11e6-922c-91ce4e8ea31f.png)
![edit_list](https://cloud.githubusercontent.com/assets/15685960/17401618/4a578dfa-5a57-11e6-82fc-1233c9278ef0.png)
![review](https://cloud.githubusercontent.com/assets/15685960/17401620/4a589894-5a57-11e6-8648-1a60f4728fc4.png)
![step3](https://cloud.githubusercontent.com/assets/15685960/17401619/4a5813a6-5a57-11e6-9b15-57808e592ac8.png)
![steps](https://cloud.githubusercontent.com/assets/15685960/17401621/4a5977aa-5a57-11e6-81cd-5af5f1c4bef3.png)
