### ISSUE TITLE
Migrate add-ons and add-on files with preliminary status

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3087]
This is part of #3083.

We need to update the statuses of add-ons and add-on files that are set to Preliminary Review. There's no need to re-sign these files because Firefox doesn't care the type of cert being used. We only need to update their status:

* If the add-on has its status set to `Preliminary Review`, the add-on should have its status set to `Full Review`. All of its files with `Preliminary Review` status should have it also set to `Full Review`. The add-on also should have the experimental flag set.
* If the add-on has its status set to `Awaiting Preliminary Review`, or `Preliminary Review and Awaiting Full Review`, don't do anything. This is an edge case; reviewers should clear these cases before running this job, and if not admins can handle them manually. 
* If the add-on has its status set to anything else (`Full Review`, `Incomplete`, `Disabled`), all of its files with `Preliminary Review` status should have it set to `Disabled`.

We'll need to notify the affected developers about this change, so we'll need to generate a list of add-on IDs for each of these cases ( though we can exclude add-ons that are `Incomplete` or `Disabled`, from the last case).

**Comment by eviljeff** [comment]
We're going to have to do something with status `Awaiting Preliminary Review` and `Preliminary Reviewed awaiting Full Review` for add-ons that are user disabled - they won't show up in the queues to be cleared. We can either migrate them to Nominated or set them to another status.

**Comment by eviljeff** [comment]
> We'll need to notify the affected developers about this change, so we'll need to generate a list of add-on IDs for each of these cases

Is this effectively dumping the IDs on the command line after the task is run?

**Comment by jvillalobos** [comment]
> Is this effectively dumping the IDs on the command line after the task is run? 

Yes, excluding add-ons that are `Incomplete` or `Disabled`.

**Comment by jvillalobos** [comment]
I did some cleanup for the add-ons that are user-disabled. There are 20 or so left where I pinged the developers to see if they disabled the add-ons by mistake. I think for the migration they should be handled like the enabled ones, and move them to their full review equivalent.

**Comment by ValentinaPC** [comment]
@eviljeff : is this change on AMO-dev? (if I set the preliminary review flag)

**Comment by eviljeff** [comment]
@ValentinaPC the code has landed but the command to run the migration hasn't been executed yet.  I'm not sure there is a way to verify this without someone in ops running it then checking the database afterwards.

**Comment by ValentinaPC** [comment]
I'll wait until it lands. :smile:

**Comment by madalincm** [comment]
@eviljeff  Any news regarding the migration?

**Comment by eviljeff** [comment]
Plan is to run on -dev on the 24 Aug.
