### ISSUE TITLE
Clean up all references to preliminary review

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3088]
This is part of #3083.

After solving all other dependencies of #3083, all code relating to preliminary review should be unused, so it should also be removed. The cleanup work related to signing can be found in mozilla/addons#32, so that should probably be reopened and resolved.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
No trace of "preliminary review" in Dev Hub or Editor Tools.
Postfix screenshots from Editor Tools:
![1](https://cloud.githubusercontent.com/assets/15685960/19066441/eec5ffd0-8a21-11e6-9b96-73f4439d66f3.png)
![2](https://cloud.githubusercontent.com/assets/15685960/19066439/eec3d2b4-8a21-11e6-9dcf-03fe65815677.png)
![3](https://cloud.githubusercontent.com/assets/15685960/19066440/eec610c4-8a21-11e6-9757-9dee0b7ab7da.png)
