### ISSUE TITLE
Update documentation with FxA only changes

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3093]
Only allowing FxA may have some impact on setting up addons-server in development or in a 3rd party production system. Document what this change entails.

**Comment by EnTeQuAk** [comment]
Is this still in progress? I remember there were some changes so that fxa works relatively good for local development, at least I didn't have any problems so far and never wondered.

**Comment by mstriemer** [comment]
This is done. I added some documentation for the third-party case in https://github.com/mozilla/addons-server/pull/3867 and the local development setup seems like it just works so no need there.
