### ISSUE TITLE
Remove name uniqueness checks for new add-on submissions

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3094]
There's a bug with name resolution for localized names in WebExtensions currently.

We decided that we remove uniqueness checks for new add-on submissions (no matter if listed or unlisted) but keep the check for editing existing add-ons since they don't go through review again.

**Comment by kewisch** [comment]
I may not know all the implications for this, but IIUC it means that there could be two add-ons called "Adblock Plus" if not caught during the review? I think this would be troubling. While it may be easy to catch for popular extensions, it won't for those reviewers do not know. Or do I misunderstand this issue?

CC @wagnerand

**Comment by andymckay** [comment]
There could be. But we also only ever checked the english translation of the add-on name, not every localisation, so already the whole check was flawed. This bug came about because of chat with @jvillalobos in #amo.

**Comment by madalincm** [comment]
Submitting 2 add-ons with the same name is working, no errors or warnings are displayed, editing an add-on to have the same name as another add-on is not allowed, an error message is displayed. 
![samenameaddons](https://cloud.githubusercontent.com/assets/15685441/16840328/b2ea3f6a-49dc-11e6-98f4-5f9afa1f3f12.png)

![samenameaddonsedit](https://cloud.githubusercontent.com/assets/15685441/16840331/b76317c4-49dc-11e6-93d0-99cefca50c4c.png)

**Comment by jvillalobos** [comment]
Yes, there is a (small) possibility of duplicate names now, and it will be up to reviewers and admins to deal with those situations.
