### ISSUE TITLE
Confirmation message is displayed even when the changes are not saved

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3098]
Steps to reproduce:

1.Load My Submissions page https://addons.allizom.org/en-US/developers/addons 
2.Open an add-on Edit Listing page, click Edit button from the right side of Support Information field.
3.Type an invalid URL and press “Save Changes” button. 

Expected results:
Website field should display a warning message, the confirmation message is not displayed.

Actual results:
A confirmation message is displayed next to “Support Information” even if the changes are not saved.

Note/Issues:
Verified on FF50.0a1 (2016-07-13) (Win 7 64-bit)
This issue is reproducing in AMO -dev, stage and production servers
Here is a video for this issue:
![test](https://cloud.githubusercontent.com/assets/15885467/16834703/b84b40cc-49bd-11e6-91a0-f5c8f2587c95.gif)

**Comment by EnTeQuAk** [comment]
This is indeed misleading, I'm not sure though if the fields are saved separately from each other meaning that "email" is being saved even though "website" is invalid which might make sense but is bad ux-wise.

I guess this is low priority though.

**Comment by ValentinaPC** [comment]
This happening in "Basic Information" section, too.
Please see the video: 
![basic info](https://cloud.githubusercontent.com/assets/15685960/17395406/e8b425a6-5a36-11e6-9277-1e8193397352.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![savechanges](https://user-images.githubusercontent.com/1583842/36539078-3963ea84-17de-11e8-9b8f-95a39396974c.gif)
