### ISSUE TITLE
Internal server error after confirming link on the new registration email

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3101]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Steps to reproduce:
1.On AMO Stage, register with a new account
2.Open the confirmation email and confirm the registration by pressing on the provided link
3.Go back to AMO Stage after confirmation is confirmed

Expected results:
User is logged in with the new email

Actual results
Internal error message displayed

NOTES:
Possible Stage server issue, I encountered a 500 when tried to approve an app from Editor Tools , but this happened only one time today

Please see video for this bug : 
![internalserver](https://cloud.githubusercontent.com/assets/1583842/16842003/6ce47636-49e4-11e6-9b38-eb428a629baa.gif)

**Comment by vcarciu** [comment]
Forgot to say that this is an intermittent issue (reproducible in about 3 from 5 tries)

**Comment by vcarciu** [comment]
Please note that now I can see the 500 error also when approving themes or addons from Editor Tools . I think that these issues are related, but please let me know if a new bug is needed.

**Comment by diox** [comment]
@mstriemer any idea ? I could not find anything in sentry, I'm not sure why this is happening.

@vcarciu please file a different bug for 500s in editor tools approval.

**Comment by mstriemer** [comment]
Took me two tries but I was able to reproduce. I see an AMQP error [1] in the login view in sentry. Perhaps it's just rabbitmq? It says it timed out but it happens quite quickly.

[1] https://sentry.prod.mozaws.net/operations/olympia-stage/issues/341164/

**Comment by mstriemer** [comment]
I believe jason kicked rabbitmq and this issue went away.
