### ISSUE TITLE
Internal server error message displayed when trying to setup display name after a new user registration

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3102]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Steps to reproduce:
1.On AMO Stage, register with a new account
2.Open the confirmation email and confirm the registration by pressing on the provided link
3.Go back to AMO Stage and try to update the display name and username from Account Settings

Expected results:
Account display name and username are correctly saved

Actual results:
Internal server error

NOTES:
Possible related to #3101
Intermittent issue (reproducible in about 3 from 5 tries)

Please see video for this bug : 
![500update](https://cloud.githubusercontent.com/assets/1583842/16842124/ed80c506-49e4-11e6-87a2-4e4d2a1b7700.gif)

**Comment by diox** [comment]
@vcarciu can you still reproduce this ? on stage and dev ?

**Comment by diox** [comment]
cc @mstriemer just in case.

**Comment by mstriemer** [comment]
I believe jason kicked rabbitmq and this issue went away.
