### ISSUE TITLE
Android searches are defaulting to version 45

### ISSUE THREAD

**Issue by Caspy7** [mozilla/addons-server#3104]
Do a search from https://addons.mozilla.org/en-US/android/ and the resulting URL will be something like https://addons.mozilla.org/en-US/android/search/?q=&appver=45.0&platform=all (this is a blank search)
Note that this is specifying version 45 and says so on the side panel.

The current released version though is 47.

**Comment by diox** [comment]
This looks like a bug in the frontend code. It you clear `localStorage` the bug should go away - at least it does for me. 

https://addons.mozilla.org/en-US/android/ and other pages, like https://addons.mozilla.org/en-US/firefox/ use `localStorage` to store the `appver` and `platform` values, and then [populate the search form](https://github.com/mozilla/addons-server/blob/master/static/js/impala/search.js#L30) using the [stored values](https://github.com/mozilla/addons-server/blob/master/static/js/impala/search.js#L19). Specifying the parameter in the URL resets the stored value, but I don't see what else resets it, that's worrying... On top of that the comments in the file reference `sessionStorage` but it appears to be using `localStorage` instead, persisting across reboots...

**Comment by tofumatt** [comment]
Oddly it should be reset, but I'm going to guess the `storage` bit isn't working. That said, I don't even know why we'd use that... so I submitted a patch that just ditches it.

**Comment by vcarciu** [comment]
@tofumatt  : This is what I can see on -dev https://addons-dev.allizom.org/en-US/android/search/?q=&appver=&platform=

Please let me know if there are additional steps for this bug

**Comment by tofumatt** [comment]
Did you try it on an Android device? Those params are fine but on desktop
it fills them in rather than being blank. It’s okay as-is, just wondering
what you get when using that page on an Android.

**Comment by vcarciu** [comment]
https://addons.mozilla.org/en-US/android/search/?q=&appver=&platform= this is returned using Android device and FF 47

**Comment by tofumatt** [comment]
That’s fine, it ends up searching for all add-ons rather than for a
particular version, but it’s better than using the old storage stuff that
was outdated. That seems fine to me.

**Comment by vcarciu** [comment]
Thanks tofumatt
