### ISSUE TITLE
Icloud Addon Service Extension Issue

### ISSUE THREAD

**Issue by lishihwan** [mozilla/addons-server#3105]
Hello Firefox promoters,

I was trying to get my photos from an old device to a new one that i bought yesterday, using icloud drive. But The Icloud Addon Service Extension wasn't able to be found. And after many attempts try to use other options to solve this problem, there seemed to be no other but to send you this message.

Sincerely,

Simply another Mozilla Fan

**Comment by tofumatt** [comment]
Unfortunately, that add-on has been removed from the site because it was very unstable. Hopefully Apple submits a new version without these stability problems in the future, but right now we have unlisted the add-on because it was creating problems for many Firefox users.
