### ISSUE TITLE
Remove thumbtype and filetype field from Preview model

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3110]
The `Preview` model has a `thumbtype` field, but it's never set, or even used except in the legacy API XML. It should be easy to remove it entirely.

**Comment by diox** [comment]
Also remove `filetype` : at least on stage, it's set to an empty string for all new previews.

**Comment by diox** [comment]
QA: Verify that add-on previews still work, can be edited etc.

**Comment by madalincm** [comment]
Thanks for the steps @diox 
Verified as fixed in FF47(Win7) in addons-dev.allizom.org
There are no issues with add-ons previews (adding, edit, removing all is working correctly)
