### ISSUE TITLE
Versioncheck for a new WebExtension without ID to an add-on does not work

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3114]
Steps to reproduce:

1.Submit an add-on as first version
2.Upload a WebExtension as new version
3.Install first version
4.Go to about:addons and check for updates

Expected results:
The updated is made to the latest version

Actual results:
No updates are found

Note/Issues:
Verified on FF50.0a1(Win 7 64-bit)
This issue is reproducing in AMO -dev server

Here is a video:
![versioncheck](https://cloud.githubusercontent.com/assets/15885467/16918449/09e6d74a-4d0e-11e6-91a0-7cbf7a15e6cc.gif)

**Comment by diox** [comment]
You had `extensions.update.url` set to the dev URL, right ?

It turns out that, on this add-on on dev, the version 1.1 is available for Firefox 48.0 or greater only. Was that intentional ?

**Comment by diox** [comment]
FWIW the update should hit `https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=2&id={daf44bf7-a43e-4450-979c-91cf07664c3d}&version=1.0&maxAppVersion=50.*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=48.0&appOS=Linux&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=48.0&updateType=97&compatMode=normal` which works fine for me.

**Comment by cosminbadescuSV** [comment]
Works on stage, here is a video:
![versioncheck2](https://cloud.githubusercontent.com/assets/15885467/16943706/a8f5e3fc-4da5-11e6-9a9e-b30e479fe6c3.gif)

-dev: 
![versioncheck3](https://cloud.githubusercontent.com/assets/15885467/16943799/4c67f084-4da6-11e6-932e-25c519cbd312.gif)

**Comment by diox** [comment]
Working now so we suspect an intermittent issue.
