### ISSUE TITLE
PR request: script to update translations table with correct outgoing url

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#3116]
Last week we released a change so that AMO now uses a new end point for outgoing service (see https://github.com/mozilla/addons-server/pull/3060). However, the translations table still contains records that point to the old end point, because they were added before the release. For example:

```
mysql> select count(*) from translations where localized_string_clean regexp 'https://outgoing\.mozilla\.org/v1/';
+----------+
| count(*) |
+----------+
|   309391 |
+----------+
1 row in set (24.81 sec)
```

We have written a script that's going to update these records so they all point to the correct outgoing end point.

Can we have someone from the Dev team to review the script before we schedule a time to run it in production?

The script is staged here: https://github.com/mozilla-services/svcops/pull/1159

Thanks!

**Comment by diox** [comment]
Commented in the PR. Have you run that on dev yet ?

**Comment by bqbn** [comment]
Thanks. I submitted one update per your comments. Can you review again?

Yes, I ran it on dev already.

**Comment by bqbn** [comment]
Script has run on all envs. This can be closed. Thx for the review @diox !
