### ISSUE TITLE
Expand ACR endpoint to accept e10s statuses

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3122]
There's a couple of possible statuses regarding e10s:
* Firefox has e10s turned on.
* The add-on has the multiprocessCompatible flag on/off or is unset.

We'll need to be sure we can recieve those, see mozilla/ACR for the issues to add that into the API.

It looks like this API is in src/olympia/devhub/views.py.

Supports: mozilla/addons#163

**Comment by diox** [comment]
I think the API is not in devhub but rather in https://github.com/mozilla/addons-server/blob/master/src/olympia/compat/views.py#L22

**Comment by diox** [comment]
This means we'd need to alter `CompatReport` model to add a boolean field indicating whether e10s is turned on or off.

**Comment by andymckay** [comment]
Ah thanks @diox. It would also need a column to reflect the MPC flag at the time of testing.

**Comment by andymckay** [comment]
Also glad to note that it looks like from reading that code that it works with unlisted add-ons, so that's cool.
