### ISSUE TITLE
Shockwave Flash plugin no update

### ISSUE THREAD

**Issue by rpbaillou** [mozilla/addons-server#3125]
Hi

I clicked on a link to take me to a page with a problem solver app for my school. It says plugin is disabled. When I click on Manage Plug ins. It takes me to the plugins page and that I need to update shockwave flash when I click to update it says it cannot be found.

**Comment by jvillalobos** [comment]
You can update the Flash plugin from here: http://get.adobe.com/flashplayer/

In the future, please refer to https://support.mozilla.org/ for help with Firefox.
