### ISSUE TITLE
Show a notice on the iCloud bookmarks page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#3130]
We've had over half a dozen bug reports in the past few weeks about the iCloud Bookmarks add-on; I say we add a message to that page, even if it's a custom URL route with a simple, static page, that outlines why it's been removed and to contact Apple support. There are likely lots of users who _aren't_ reporting bugs for every one who does.

Right now Apple isn't even hearing from these users, and it's their problem to fix. Plus it will cut down on noise in all the addons projects.

Marking this as a good first bug if someone wants to create a page and add the URL route for it; otherwise I'll try to get to this before 50.4 is finished.

**Comment by wagnerand** [comment]
Marking this as "maybe..." so it will get triaged with a mentor and onboarding info.

**Comment by andymckay** [comment]
If we get more reports, I wouldn't mind just having someone pick this up and do something quicker.

**Comment by andymckay** [comment]
There have been two reports since my last comment. I think we should do something sooner rather than later as in soon.
