### ISSUE TITLE
Signing new version of deleted add-on results in a 404 signed file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3133]
If you try to sign a new version for a deleted version, it appears to work but the signed file response is a 404. I'm not sure exactly what should happen here. I guess it should be possible to sign a new version and automatically "undelete" the add-on?

To reproduce:
- generate [some API keys](https://addons-dev.allizom.org/en-US/developers/addon/api/key/)
- download this extension source: [web-ext-example.zip](https://github.com/mozilla/addons-server/files/373939/web-ext-example.zip)
- cd into the source and run [web-ext sign --verbose --api-key ... --api-secret ...](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Distributing_your_own_WebExtension)
- check the signed file with `unzip -l web-ext-artifacts/*` to make sure it's a real XPI
- go to [your add-ons](https://addons-dev.allizom.org/en-US/developers/addons), find the one you just created, go to Manage Status & Version, and click Delete Add-on.
- go back to the extension source directory, edit `manifest.json` and increment the version number
- run `web-ext sign` again which would normally sign a new version of the same add-on

Check the contents of the XPI file. This time it contains `{"detail": "Not found"}` because there was a 404. The handling of this 404 in web-ext is a [separate bug](https://github.com/mozilla/sign-addon/issues/74). What should AMO do here?

**Comment by andymckay** [comment]
I'm thinking that AMO is doing the right thing, we probably shouldn't try and automatically undelete the add-on. Would defer to @mstriemer or @wagnerand though.

**Comment by kumar303** [comment]
If that's the case, AMO should probably return an error earlier in the process. When you first try to PUT (or POST) a new version for a deleted add-on, it should return an error.

**Comment by andymckay** [comment]
Agreed.

**Comment by wagnerand** [comment]
We have no separate process of _undeleting_ an add-on.

On the web interface, we (currently) have a distinction between uploading a new version for an existing add-on and uploading an entirely new (or deleted) add-on. If the add-on was deleted previously, we just undelete it transparently during the first upload after deletion.

We don't seem to have that disctinction in `web-ext` (I don't think we need it, either).

So, how would `web-ext` users recover from such an error? We'd basically force them to use the web upload once so their add-on is undeleted.

If we do automatic undeleting on the web interface, why wouldn't we do it when using `web-ext`?

**Comment by kumar303** [comment]
> So, how would web-ext users recover from such an error?

That's a good question. We could instruct them to change the ID in their manifest, I suppose? How can you even recover from this in the web interface? Deleted add-ons are hidden. If you upload a new one with the same ID, does it create a whole new add-on?

**Comment by wagnerand** [comment]
> We could instruct them to change the ID in their manifest, I suppose?

That would break updates, which is the main concern. People delete their listing for whatever reasons, even when something completely unrelated happens.

> How can you even recover from this in the web interface?

You just submit your file as a new extension and we automatically *undelete" it in the background, invisible to the user.
