### ISSUE TITLE
User lookup API

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3138]
We would like some way of looking up users in the admin tool. This should likely only work for exact matches for privacy reasons but a search might be okay. Key off of email, username and FxA ID.

```
GET /api/v3/users/?email=someuser@somedomain.com

200 OK

{"username":"theuser", ...}
```

```
GET /api/v3/users/?fxa_id=1283def12871

404 Not Found
```

https://github.com/mozilla/addons-frontend/issues/810 depends on this.

**Comment by diox** [comment]
Yeah I'll re-use whatever permissions the current admin uses.

**Comment by eviljeff** [comment]
See #979

**Comment by diox** [comment]
Assigning to @EnTeQuAk to share the API work :) Not a priority at the moment.

**Comment by diox** [comment]
Note: http://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#profile already exists to fetch your own profile, so that's a start. We may need to make some backwards-incompatible changes to it though, since it does not seem to handle `TranslatedField`s for instance.

**Comment by diox** [comment]
I'll start to implement a base skeleton to make listing reviews of a particular user works. I'll follow the same pattern as used in addons, so:

`/api/v3/accounts/account/{pk}/`
`/api/v3/accounts/search/?{various parameters}` (restricted to admins)
`/api/v3/accounts/account/{pk}/reviews/`

**Comment by muffinresearch** [comment]
Closing this since we have no immediate plans to extend the admin api endpoints, we can simply use the django admin for this. We can always reopen this if that changes.
