### ISSUE TITLE
Replace amo.cached_property by django's

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3140]
We have our own `cached_property` implementation in https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/__init__.py#L36 but [django already has one that seem to be providing equivalent functionality](https://docs.djangoproject.com/en/dev/ref/utils/#django.utils.functional.cached_property) (except it's always writable to override the computed value, but that's a good thing)

We should remove our implementation and use django's. Bonus points, in the future we'll get nice fixes like this one: https://github.com/django/django/commit/271bfe65d986f5ecbaeb7a70a3092356c0a9e222

**Comment by diox** [comment]
(all credit goes to @eviljeff who noticed that a few weeks ago btw)

**Comment by EnTeQuAk** [comment]
I looked at this some time ago and saw cache-machine being involved but maybe the hack in there isn't really needed anymore but we need to test that things are working as expected (hoping there's a test for that line of code)

**Comment by diox** [comment]
I wouldn't be surprised if that hack wasn't tested... but we could replace it or try avoiding it.
