### ISSUE TITLE
Waffle FxA migration success banner

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3142]
When you log into with your Firefox Account for the first time you get the "Great job!" success banner even when the migration isn't enabled. This seems odd, it should not appear when the fxa-migration waffle is turned on.

**Comment by ValentinaPC** [comment]
@mstriemer : I did not receive the FxA migration banner all around AMO servers; is this change already in production? Thanks!

**Comment by mstriemer** [comment]
You should be able to see a banner by logging in with a password and then connecting a Firefox Account.

When we turn off the migration on dev this week this change should prevent you from seeing that banner anymore.

**Comment by mstriemer** [comment]
This change is not on production.

If you want some test users let me know and I'll create them.

**Comment by ValentinaPC** [comment]
I have test users...but I am not able to see the banner, even if I use AMO-production. Is there also a migration flag turned off? Thanks!

**Comment by mstriemer** [comment]
You should be able to see the banner on stage. Here's how I did it:

1. Log in with a user that needs a password.
2. Click continue.
3. Log in with an FxA that hasn't been used yet.
4. Banner appears.

Ignore the bit at the beginning of the video where I use the wrong email address.

![fxa-migration-banner-stage mov](https://cloud.githubusercontent.com/assets/211578/17221371/3c75bb60-54b9-11e6-9c91-77ca678b4ab8.gif)

**Comment by ValentinaPC** [comment]
Because I do not see the "password" field...I am not able to continue with your scenario. 
Any idea why this is happening?
Please see the video (sorry to insist):
![etst](https://cloud.githubusercontent.com/assets/15685960/17239424/9b57ca52-556c-11e6-9621-2016febb65f1.gif)

**Comment by mstriemer** [comment]
You need some un-migrated users to test with. I created some users for you, the passwords are all "password".

On dev logging in should not show a banner and should not prompt for a password since the migration is disabled, on stage you should be prompted for a password and see the banner when you log in with FxA.

On dev:
* amo-fxa-100@mailinator.com
* amo-fxa-101@mailinator.com
* ...
* amo-fxa-125@mailinator.com

On stage:
  * stage-fxa-100@mailinator.com
  * stage-fxa-101@mailinator.com
  * ...
  * stage-fxa-125@mailinator.com

**Comment by ValentinaPC** [comment]
As you can see in the above video, I was using a new, not-migrated e-mail, but for some reason did not work as expected.
Using the provided mail, the banner appears as mentioned in your message.
STAGE: 
![stage](https://cloud.githubusercontent.com/assets/15685960/17287697/d815e77a-57d9-11e6-9887-892dd93bd69f.png)
DEV:
![dev](https://cloud.githubusercontent.com/assets/15685960/17287704/e33b735e-57d9-11e6-9885-49a2b221da9c.png)
