### ISSUE TITLE
Implement Reviewer ↔️ Developer comms

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3143]
This is a tracker bug for the tasks needed to implement a reviewer ↔️ developer communication tool as initially specified in [this proposal doc](https://docs.google.com/document/d/1NeIXRkarfA0RBKuo2wnCzEpgCLwvXm4SlxdSeOiPeMA/edit#heading=h.trd8m0gqh63d). The recommended UX can be seen in https://github.com/mozilla/addons/issues/152.

Here are the steps that we need for this (I'll file individual bugs):

1. Move review history up from the individual version view to the Status & Versions page.
2. Implement a Reply feature for the latest version and show pending messages badge.
3. Update review email templates to point to tool.
4. Integrate email replies.

**Comment by eviljeff** [comment]
Just #3349 outstanding now.

**Comment by eviljeff** [comment]
All tasks done but it can be re-opened to be linked to for any bugs found during QA.
