### ISSUE TITLE
Move review history to Status & Versions page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3144]
This is part of #3143. The recommended UX can be seen in mozilla/addons#152.

A Review History link should be added under the Status label for each version in the Status & Versions page. Clicking on the link toggles the review history for that version.

The Show File History link in individual version pages (like [this one](https://addons.mozilla.org/developers/addon/amo-admin-assistant/versions/1895920)) should be removed to avoid duplication and confusion.

**Comment by eviljeff** [comment]
note for QA: screenshot in mozilla/addons#152 shows additional features not in this issue, such as unread feature, which is #3146 and reply box which is #3147

**Comment by ValentinaPC** [comment]
Verified as fixed on AMo-dev (Win 7 x64) for approved addons, unapproved add-ons or multiple versions add-ons.
The "Review History" link is displayed and works if clicked.
Postfix video/screenshots: 
![approved](https://cloud.githubusercontent.com/assets/15685960/18092387/c3119a4c-6ed4-11e6-9ef5-403a1c9231bf.gif)
![awaiting](https://cloud.githubusercontent.com/assets/15685960/18092395/cbc45d78-6ed4-11e6-8fe9-1dae80d9d633.png)
![multiple](https://cloud.githubusercontent.com/assets/15685960/18092399/d084e9f4-6ed4-11e6-888d-0cc583b10558.png)
