### ISSUE TITLE
Implement pending message badge in Dev Tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3146]
This is part of #3143. The recommended UX can be seen in mozilla/addons#152.

If an add-on has a version pending review and a review sent a Info Request (or more) that hasn't been answered, the Review History link for that version should show a badge with the number of pending messages. The Manage Status & Versions link in the navigation box on the left should also be highlighted. When the Review History for that version is expanded, the unread messages should be highlighted.

**Comment by eviljeff** [comment]
@jvillalobos is unread status per add-on+version or per add-on+version+developer?  I.e. if an add-on has 2 developers would the messages still show unread for developer-b after developer-a had read them?

I'm assuming an admin visiting the page wouldn't lead to the messages being marked read either.

**Comment by jvillalobos** [comment]
I think the events that would make the badge disappear are (a) a developer (any developer) has replied, and (b) a review is performed. It makes sense to have a "mark as read" option as an additional trigger, but I wouldn't bother making it per-developer.

**Comment by eviljeff** [comment]
Is a 'mark-read' button a requirement?  Without it we wouldn't need to keep track of specifically which messages have been 'read' or not; the indicator would be a count of messages received since the last developer reply (or all messages if no reply).

**Comment by jvillalobos** [comment]
It's not a requirement. We can implement it as initially conceived and see if it becomes a frequent request from devs.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF48.0.2(Win 7 x64)
Seems like the pending message badge appears in "Manage Status & Versions" page and the review is highlighted as not read.
Please see screenshot:
![review](https://cloud.githubusercontent.com/assets/15685960/18463060/071a844a-7990-11e6-809f-3db4f4c0aa9b.png)

Question: It can be marked as read and make the badge disappear? Thanks!

**Comment by eviljeff** [comment]
there is no mark read button as per https://github.com/mozilla/addons-server/issues/3146#issuecomment-245300443 and I interpreted https://github.com/mozilla/addons-server/issues/3146#issuecomment-245092198 as leaving the messages 'pending' until the developer replies or they upload a new version.  (I.e. the developer must have taken some action).  An approval/rejection by a reviewer doesn't count because they might be some information in the notes the developer should see.  @jvillalobos can comment if that's not what he intended.

Unfortunately the "developer reply making them unread" feature is impossible to QA currently (without some hacking) because it doesn't exist yet.

**Comment by ValentinaPC** [comment]
Thanks for your reply! Make sense.
Base on your comment and my verification I'll mark this issue as verified-fixed.
Waiting for the new featured to show-up. :)

**Comment by ValentinaPC** [comment]
Appendix:  "... or they upload a new version" -> uploading a new version removes the pending message badge for the previous comment, BUT adds a "0" badge for the current unapproved version; intended?
![2016-09-13_1537](https://cloud.githubusercontent.com/assets/15685960/18474112/1a9d2d04-79c9-11e6-9942-17e5a12a0f5d.png)


Sorry for 2 messages in stead of one.

**Comment by eviljeff** [comment]
@jvillalobos do you want a `0` when there are no pending messages or no indicator?

**Comment by jvillalobos** [comment]
>  An approval/rejection by a reviewer doesn't count

I does count. On my previous comment I noted that reviews should reset the counter.

> do you want a 0 when there are no pending messages or no indicator?

I'd rather have no indicator.

**Comment by ValentinaPC** [comment]
@eviljeff : Should I open another issue for the indicator, you guys already did or here will do it?

**Comment by eviljeff** [comment]
I'll make the changes along with #3147

**Comment by eviljeff** [comment]
to clarify @jvillalobos "reviews should reset the counter." you mean the following 3 actions would reset the pending count: approval; rejection; developer-reply ?

**Comment by jvillalobos** [comment]
> to clarify @jvillalobos "reviews should reset the counter." you mean the following 3 actions would reset the pending count: approval; rejection; developer-reply ?

Yes.
