### ISSUE TITLE
Change review email templates to point to Status & Versions page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3148]
This is part of #3143.

The email templates used to notify developers about reviews should be updated to point to the Status & Versions page as the default place to respond to reviews. Replying via email should still be supported as an alternative.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7).

There are the following 2 cases:
- if an editor leaves a note from Reviewer Tools - in the activity mail points to Manage Status & Version page
Screenshot: 
![manage-statsu-vers](https://cloud.githubusercontent.com/assets/15685960/23208871/6e363f5e-f8ff-11e6-958f-e86f5c6e23b7.png)
- if a developer leaves a reply from Dev Hub - in the activity mail points to add-on review page
Screenshot: 
![review](https://cloud.githubusercontent.com/assets/15685960/23208918/9abc2a70-f8ff-11e6-9aa9-df5ff7970e27.png)

If the behavior is not how it suppose to be, please reopen.

**Comment by eviljeff** [comment]
It's more who the email is going _to_ rather than who left the note or where it was generated from, but the outcome mentioned is correct.

**Comment by ValentinaPC** [comment]
Yeah, I understood, just wanted to find a logic while discovered 2 places where the e-mail is going _to_.
Thanks for your reply.
