### ISSUE TITLE
Integrate email replies to comms tool

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3149]
This is part of #3143.

This is the part that could be partly ported from the commbadge code in Marketplace. It should be possible for developers and reviewers to reply to the notifications they receive via email and have them be stored and handled by AMO like replies done within the site. 

Email should be treated as text-only, and attachments should be discarded in this iteration.

**Comment by eviljeff** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1296696 to have the incoming emails forwarded to AMO's API

**Comment by eviljeff** [comment]
QA: this won't be end-to-end testable until bug 1296696 is fixed and socketlabs collects the incoming emails.
