### ISSUE TITLE
Cannot migrate to an FxA with a different email

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3151]
Migrating to an FxA with a different email will actually create a new account. This appears to be because `request.user` is set to `AnonymousUser` instead of the user from the session.

https://github.com/mozilla/addons-server/blob/39796c94b12e55d83e812a3d40ff005e923cc1a9/src/olympia/accounts/views.py#L213

Originally from https://bugzilla.mozilla.org/show_bug.cgi?id=1288252.

**Comment by ValentinaPC** [comment]
I've tried to reproduce the initial issue, but couldn't, or maybe I left something out while trying.
@mstriemer : could you help us with a more detailed expected and actual results?

As far as I understood we should be able to see the migration (together with the banner), like illustrated in #3166 , at least on AMO-stage/prod, yes?

Thanks in advance!

**Comment by mstriemer** [comment]
I did this on stage:

1. Log in with a user that needs a password.
2. Click continue.
3. Use an FxA that hasn't been used yet, but is a different email.
4. You see the migration banner and your email has changed.

![fxa-migraiton-change-stage mov](https://cloud.githubusercontent.com/assets/211578/17222060/1b89af9e-54bc-11e6-96d3-fecbd1baa07e.gif)

**Comment by ValentinaPC** [comment]
I followed above steps, and I am not able to reproduce the initial issue in AMO-stage FF47(Win 7 x64).

But... if I follow above STR, after step 3 I receive a migration page even if the second account is already migrated - as the info "red-message" says - If I click "skip", another migration page appears.  
Please let me know if this is intended, or expected.
See the screencast: 
![2-banners](https://cloud.githubusercontent.com/assets/15685960/17289297/c3952ee8-57e1-11e6-8bc2-fabbd009746c.gif)

**Comment by Luckz** [comment]
Hey, I'm the person who opened the Bugzilla bug. By first casting https://addons.mozilla.org/en-US/firefox/users/delete on the new AMO account created by the bug, I was able to successfully link the two accounts under the Firefox account's email. Thanks for that.

Like @ValentinaPC I have also experienced this odd loop. The only valuable information about it is the "Your Firefox Account already exists" message, which makes the process
"log in to AMO with this Firefox account, then do https://addons.mozilla.org/en-US/firefox/users/delete , then log in to your real AMO account again and repeat" very unintuitive for non-technically minded users. Fortunately only people who suffered this bug or people who accidentally made new AMO accounts by logging into AMO with their Firefox accounts would be affected.

**Comment by ValentinaPC** [comment]
@mstriemer I have a scenario, maybe valid or expected...

**1. Use an unmigrated account and log in to AMO-stage (enter a password as requested - I've used one of the accounts you provided)
2. Choose to "Skip" migration
3. Go to Account Settings, change the e-mail to a test one (gone@mailinator.com) and save changes
4. Choose to migrate this account
5. Log out
6. Log in with the unmigrated account used at step 1 (**no pass is requested**) and the MIGRATION BANNER is no longer displayed, FxA Accounts page is loaded.**

**Comment by mstriemer** [comment]
In step 4 do you complete the migration? If you do then this sounds right. The email sent to gone@ should no longer work.

**Comment by ValentinaPC** [comment]
Yup, in step 4 I complete the migration for the "gone" account.
In step 6 I use the account used for step 1 and 2.

**Comment by ValentinaPC** [comment]
@mstriemer : So, if I start with an unmigrated e-mail, choose not to migrate it (Skip), change the e-mail (Account Settings), migrate the new e-mail and try to log in with the first not-migrated e-mail -> eliminates the possibility to skip migration, is ok? 
Sorry to insist.
Thanks!

**Comment by mstriemer** [comment]
@ValentinaPC it sounds like you're creating a new account which is done through FxA and wouldn't have a migration. 

1. Change home@me.com to work@me.com
2. Migrate work@me.com to FxA
3. Create a new account with home@me.com (new account, no migration)

Is that right?

**Comment by ValentinaPC** [comment]
Yup.

**Comment by mstriemer** [comment]
Sounds right to me then. Thanks!
