### ISSUE TITLE
Privatix Add-on

### ISSUE THREAD

**Issue by AlvaroChente** [mozilla/addons-server#3152]
Please, take a look in this link:

https://addons.mozilla.org/en-US/firefox/addon/privatix/

Privatix was great and we need a firefox add-on. Hel me !!

Thanx in advance.

**Comment by jvillalobos** [comment]
Judging by the recent history of the add-on, a new version will be submitted for review and that page should reappear. The reason it's showing an error right now is that there are no versions available.

**Comment by AlvaroChente** [comment]
Gracias jvillalobos, en efecto recibí un comunicado de Privatix directamente, donde me dicen que en esta semana seguramente estará apareciendo la nueva versión.
