### ISSUE TITLE
Theme review title has layout issues in theme details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3160]
Steps to reproduce:
1. Sign in and go to any theme details page in AMO-dev i.e https://addons-dev.allizom.org/en-US/firefox/addon/hello-kitty-diamonds/
2. Write a review (must type a "Title")
3. Observe the review

Expected results:
The review title is bold and larger than the review body.

Actual results:
The title is exactly the same as the body.

Notes/Issues:
Things are as expected in reviews page.
Verified on FF47 (Win 7). Issue is reproducing on AMO-stage, dev and production.
Screenshot for this issue: 
![review_theme_title](https://cloud.githubusercontent.com/assets/15685960/17094567/d8bd9da2-5258-11e6-8605-630fe6eb3d7d.png)

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
