### ISSUE TITLE
iCloud Bookmarks broken link.

### ISSUE THREAD

**Issue by TheOpen1** [mozilla/addons-server#3165]
I went to setup iCloud for Windows. I set it up to sync my firefox bookmarks with my safari bookmarks, then it says I need an add-on for it to work. I click on download which opens up firefox to "https://addons.mozilla.org/en-US/firefox/addon/icloud-bookmarks/" but the add-on site displays a 404 error. What is going on?

**Comment by tofumatt** [comment]
See #3130; it's actually been disabled because of stability problems. We're adding a notice to the page that will alert users that Apple needs to update the add-on so it doesn't crash users' Firefox browsers before we can re-enable it.
