### ISSUE TITLE
First 2 add-ons mentioned in about:addons video cannot be opened

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3167]
Steps to reproduce:
1. Open about:addons (under any AMO server)
2. Play the video
3. Go to the middle of it (0:40 sec) and try opening the first 2 add-ons listed on the right side

Expected results:
Add-ons details page are opened as expected.

Actual results:
"What are Add-ons?" page is displayed.

Notes/Issues:
This is happening only for the first 2 add-ons.
Verified on FF47(Win 7 x64). Reproducing on Add-ons Manager under stage, dev and prod.
Screencast for this issue: 
![video addons](https://cloud.githubusercontent.com/assets/15685960/17128851/3252c350-5318-11e6-911d-c06f0bf9a627.gif)

**Comment by muffinresearch** [comment]
Do you have STR to get to the video? I don't seem to ever get the video using a new profile.

**Comment by ValentinaPC** [comment]
Load about:addons in Firefox 47 and click on the "Learn More" button. (
![video](https://cloud.githubusercontent.com/assets/15685960/17139991/6d1e9932-534f-11e6-972e-479126805cc4.gif)
)

**Comment by muffinresearch** [comment]
Hmn. That doesn't show a video for me. It just links to amo.

**Comment by muffinresearch** [comment]
Ah, I found why - when the locale is en-GB it doesn't work :). Maybe it only works for what is presumed to be english e.g. en-US - since the video isn't localized.

**Comment by muffinresearch** [comment]
So both of those are 404 hence the message. Since the disco pane is about to be replaced I think we can not worry too much about that. It's been like it for a while.

**Comment by ValentinaPC** [comment]
I just thought that users can encounter this issue, until the new disco pane show-up....and be upset :)

**Comment by muffinresearch** [comment]
> I just thought that users can encounter this issue, until the new disco pane show-up....and be upset :)

It's out on 2nd august so not long at all. It would take us longer to deal with changing the video etc.
