### ISSUE TITLE
CircleCI fails often and needs to be restarted

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#3177]
CircleCI builds fail quite often but will succeed once restarted. This causes a lot of PRs to appear red until the CircleCI tests are restarted. Or worse, the failing tests are ignored as "just something that happens sometimes", which negates the point of having our tests and code in the same repo (so we can see when a change to the code breaks QA's automated tests).

Not sure what we can do to fix this, but I'm filing this so it's known/documented, as I didn't see an actual issue about this anywhere.

If there's any way I can help let me know, I worry we will just start ignoring CircleCI and that's very bad to me.

**Comment by EnTeQuAk** [comment]
It's a bit related to https://github.com/mozilla/addons-server/pull/3111 and right now we're unsure as to why the setup on the circle ci fails sometimes.

I might get to investigate this a bit more while fixing up migrations for django 1.8 so hopefully we get a few answers tomorrow.

We shouldn't ignore the tests, I agree but if fixing them takes more time we should at least avoid any more confusion by disabling them for our PRs. Merging with a red cross in the PR title feels wrong and is confusing, especially for 3rd party developers.

**Comment by davehunt** [comment]
Hopefully the patch in #3111 will fix this.

**Comment by davehunt** [comment]
#3111 is merged now, let's see how the CircleCI builds go, and consider closing this if stability has improved.

**Comment by muffinresearch** [comment]
I'm going to close this - but please feel free to reopen if needed.
