### ISSUE TITLE
Ui issues in Editor Tools for users with long Display Names

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3180]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Steps to reproduce:
1.Be sure that you have a max length Display Name for your AMO user 
2.Go to https://addons.allizom.org/en-US/editors/
3.Observe the "Reviews this month" section

Expected results:
Long names should be truncated and no UI issues displayed

Actual results:
Long names are not truncated and there are text overlapping issues

Please see photo for this issue:
![editor](https://cloud.githubusercontent.com/assets/1583842/17172173/82af9f64-53fc-11e6-85b2-5e9af7099b71.png)

**Comment by vcarciu** [comment]
Another place with issues for long reviewer name  : 
![reviewers](https://cloud.githubusercontent.com/assets/1583842/17172478/fc404f08-53fd-11e6-8967-585a71c8e41e.png)

**Comment by diox** [comment]
Not worth spending time to fix this bug IMHO, it's fairly specific, affects only reviewer tools, and is not a very big deal. Wontfix.
