### ISSUE TITLE
Improve API request error page in development

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3187]
Currently if you get a 500 on an API request you see `{"detail": "Internal Server Error"}` and the stack trace is hidden from the logs.

https://github.com/mozilla/addons-server/commit/a121c9290d28fcf27971e97344332c02ef83643a says it showed the django error page in development but that seems to be what is causing the error to be swallowed. Maybe shouldn't set an error handler in development?

Either by showing the django page or printing the stack trace to the log, we should get some feedback in development. Returning the detail JSON is probably a good idea since that's what happens in production.

**Comment by diox** [comment]
I often set `DEBUG_PROPAGATE_EXCEPTIONS` to `True` locally, but it also means other `APIException` are propagated up (400/403/404 in particular), causing 500 errors themselves because the exception is not caught. So it's probably best to leave it as `False` by default and use logging instead.

**Comment by ValentinaPC** [comment]
I've verified Register/Log in from a unicode named add-on details page i.e. https://addons-dev.allizom.org/en-US/firefox/addon/%D0%B4%D0%B2%D0%B5-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8-%D1%88%D0%B5%D1%81%D1%82%D1%8C-%D1%81%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2-2-6/?src=search in AMO-dev using FF48(Win 7)

"Register" worked fine, but "Log in" didn't.
After entering my credentials, this page loaded:
![dev](https://cloud.githubusercontent.com/assets/15685960/18196724/d47f65c4-70fb-11e6-801a-f59e0f0fc6bb.png)

Let me know if I should log a separate issue for this or reopen this one.

**Comment by mstriemer** [comment]
I'm not sure why log in wouldn't be working. I tried logging in from that page and it worked for me. If it is happening consistently then it could be a bug.

If you did:

1. Load page then register
2. Log out
3. Use the back button to go back to original page
4. Log in
5. Error

It could be that your cookie no longer matches what was on the page. If that is the case then https://github.com/mozilla/addons-server/issues/3389 should fix that issue.

**Comment by mstriemer** [comment]
This is just a change in the development flow so there's no QA needed on the site.

**Comment by ValentinaPC** [comment]
Not reproducing anymore. Thanks!
