### ISSUE TITLE
Contributions is failing with a 500

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3188]
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=ss
2. Click on the Contribution button

## expected behavior:
paypal window opens

## actual behavior:
Contribution fails with a 500

<img width="1439" alt="screen shot 2016-07-27 at 5 12 20 pm" src="https://cloud.githubusercontent.com/assets/301317/17196969/55537b64-541d-11e6-931f-6fca2daa1879.png">

## sentry:
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/243045/

## traceback details:
KeyError: 'payKey'
  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "olympia/addons/decorators.py", line 44, in wrapper
    return f(request, addon, *args, **kw)
  File "olympia/amo/decorators.py", line 52, in wrapper
    return f(request, *args, **kw)
  File "olympia/addons/views.py", line 499, in contribute
    uuid=contribution_uuid))
  File "olympia/paypal/__init__.py", line 131, in get_paykey
    return response['payKey'], response['paymentExecStatus']

**Comment by EnTeQuAk** [comment]
The same error appears to have happened on stage yesterday too but I cannot reproduce this anymore.

![screenshot from 2016-07-28 18-12-56](https://cloud.githubusercontent.com/assets/139033/17220358/2af8c018-54ef-11e6-9dd1-88c6e2628b41.png)

**Comment by muffinresearch** [comment]
It's not repro'ing on -dev any more either

**Comment by andymckay** [comment]
PayPals sandbox isn't a shiny beacon of reliability and this was most likely an outage on their side.

**Comment by muffinresearch** [comment]
It didn't reproduce on prod when it was reproducing on -dev so this suggests it was just a temporary issue with the sandbox endpoint: https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/stage/settings.py#L192

**Comment by madalincm** [comment]
I can't no longer reproduce this in dev or stage.
Also I have tested in production and everything looks good.
marking as verified.
