### ISSUE TITLE
Change "Login with" to "Log in with"

### ISSUE THREAD

**Issue by TonnesM** [mozilla/addons-server#3193]
Recent new strings contain "Login with Firefox Accounts", available for l10n. Since "Login" is a noun and a verb is intended here, they should use "Log in".

https://github.com/mozilla/addons-server/blob/master/src/olympia/users/templates/users/login.html#L12
https://github.com/mozilla/addons-server/blob/master/src/olympia/users/templates/users/mobile/login.html#L11

**Comment by mstriemer** [comment]
I never considered this distinction but a quick search backs it up [1]. Feel free to submit a pull request with the updated strings (or in the future do that with an explanation if you find something, no need for an issue). I'll update these later if they haven't changed yet.

[1] http://grammarist.com/spelling/log-in-login/

**Comment by TonnesM** [comment]
Thanks. Also good to know is that such "phrasal verbs" apparently need to use "in to" ("not into"), i.e. "log in to", "sign in to".

Please don't mind if I leave this to you. I was hoping for a quick fix by the one responsible and was asked to file the issue here, but would need to dig into (not a phrasal verb ;) ) the issue which would keep me from doing other things with the risk of messing up (i.e. not entirely sure if it's only about adding two spaces in these files.)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (Win 7, Android 6.0.1)
Postfix screenshots:   
![2016-08-25_1146](https://cloud.githubusercontent.com/assets/15685960/17962638/755338ec-6aba-11e6-8797-a3af521327b0.png)
![2016-08-25_1152](https://cloud.githubusercontent.com/assets/15685960/17962639/75583a18-6aba-11e6-8423-b1331580decc.png)
