### ISSUE TITLE
iCloud bookmarks extension required

### ISSUE THREAD

**Issue by DasReport** [mozilla/addons-server#3194]
The iCloud app on PC says the bookmarks extension for firefox is required to sync the desktop pc bookmarks with the icloud. The download button directs to a dead end. Here is the link in browser:  https://addons.mozilla.org/en-US/firefox/addon/icloud-bookmarks/

**Comment by andymckay** [comment]
This is a duplicate of #3027. The iCloud Bookmarks add-on was taken down due to serious stability problems. It's up to Apple to submit an update that corrects these problems.
