### ISSUE TITLE
Activity Remover 

### ISSUE THREAD

**Issue by daniel156858217** [mozilla/addons-server#3195]
Por favor, yo quiero probar el addons Activity Remover para Mozilla.

Gracias.

**Comment by jvillalobos** [comment]
Supongo que esto es en referencia a una página de un complemento que ya no existe. De ser así, el complemento fue deshabilitado y no hay nada que podamos hacer para rehabilitarlo. Sugiero buscar alternativas en https://addons.mozilla.org/

**Comment by daniel156858217** [comment]
Hoa Jorge. Gracias por responder. Te ruego ayuda. ¿Podrías por favor recomendarme una alternativa? Es porque siento que me están entrando al Facebook y quiero borrar todo para estar más tranquilo. Pero estar borrando elemento por elemento me está llevando denasiado tiempo, días! Desde ya gracias.

**Comment by daniel156858217** [comment]
Hola Jorge. Gracias por responder. Necesito tu ayuda, te ruego me recomiendes una alternativa. Es porque siento que me están entrando al Facebook y quiero borrar todo para estar más tranquilo. Pero estar borrando elemento por elemento me está llevando denasiado tiempo, días! Desde ya ^nuevamente gracias. Daniel.
