### ISSUE TITLE
Activity Remover para Mozilla

### ISSUE THREAD

**Issue by daniel156858217** [mozilla/addons-server#3202]
Necesito tu ayuda, les ruego me recomienden una alternativa al Activity Remover para Mozilla. Es porque están entrando a mi cuenta de Facebook y quiero borrar todos mis datos personales para estar más tranquilo, pero no tener que estar borrando elemento por elemento porque eso me está llevando demasiado tiempo, muchos días! Desde ya gracias. Daniel.

**Comment by jvillalobos** [comment]
Este no es un foro de soporte. Puede solicitar ayuda en http://foro.mozilla-hispano.org/
