### ISSUE TITLE
Update intro text for Discovery Pane for launch

### ISSUE THREAD

**Issue by deadsquid** [mozilla/addons-server#3204]
In discussions with Legal, we need to modify the text of the introductory paragraph of the discovery pane to make it clearer that add-ons are bits of code that are downloaded and installed independently from Firefox.

The paragraph under "Personalize Your Firefox" needs to be updated to:

"There are thousands of add-ons created by developers all over the world to help you personalize your browsing experience--everything from fun visual themes to powerful tools and features. Here are a few great ones to try out."

Could the text be uipdated and pushed today? It needs to be in for release tomorrow.

Sorry for the last-minute modification.

**Comment by muffinresearch** [comment]
The new copy was added. However, the new key would mean all the translations would fall-back to english. Hence the key was updated for all locales so that we get out of date translations instead of falling-back to english.

The updates are in this tag: https://github.com/mozilla/addons-frontend/compare/2016.07.28...2016.08.01

Which is now on stage.

**Comment by muffinresearch** [comment]
Note: what was committed to master is just the copy changes, this way the l10ners will see that translations are needed as soon as I do an extraction.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage FF48(Win 7 x64)
Postfix screenshot: 
![2016-08-11_1433](https://cloud.githubusercontent.com/assets/15685960/17587379/aefe2e98-5fd0-11e6-897f-33cca277ca01.png)

I've also checked for "de" and RTL lang and for the second the translation of the text is not made. (but I guess these things are going forward as soon as a contributor wants to translate it)

Please let me know if there is something else we should check.
Until further notice I'll mark this verified.
