### ISSUE TITLE
Message about firefox account is not displayed at log in

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3205]
### Steps to reproduce:
1. While logged out open the amo homepage:  https://addons-dev.allizom.org/en-US/firefox/
2. Click on the Log In link

### Expected results:
The page that explains that AMO has transitioned to Firefox Accounts is displayed

### Actual results:
No message is displayed.

### Notes/Issues:

The banner is displayed when logging in from the write a review form: 
![writereview](https://cloud.githubusercontent.com/assets/15685441/17294905/310e23c4-5802-11e6-8118-335912edc9f9.gif)

Verified in FF47(Win7) Issue can be reproduced in amo-dev
Screencast for this issue:
![directlogin](https://cloud.githubusercontent.com/assets/15685441/17295236/d12abdd0-5803-11e6-8ea9-c5e3126da73e.gif)

**Comment by mstriemer** [comment]
As far as I'm concerned the homepage is working as intended. I think the write a review link should be updated to go straight to FxA though.

@designakt is this the expected behaviour once we remove the migration? Any login link on the site will go directly to FxA?

**Comment by designakt** [comment]
I would think directing to FxA for logins should be default after removing migration.
But @brampitoyo can better talk to this as he has been working on it.

**Comment by andymckay** [comment]
Agreed, I think we should go straight to FxA. @mstriemer, @designakt and I agree, so that's enough of agreement to me. Let's do it.

**Comment by brampitoyo** [comment]
Yes. We should go straight to the standard FxA registration/login page whenever there’s a link that points there. There’s no need to put any transitional page inbetween.

![artboard](https://cloud.githubusercontent.com/assets/51007/17915288/896f9a04-69fd-11e6-9c51-15b959cf13e3.jpg)

**Comment by madalincm** [comment]
Verified as fixed in FF48(Win7) 
Verified using all the log in links and it works as expected.
Postfix screencast: 
![3205postfix](https://cloud.githubusercontent.com/assets/15685441/18246280/58fe83ce-7373-11e6-8736-e8aff3932b17.gif)
