### ISSUE TITLE
Add IDs or Class Names to dropdowns in header for automated tests

### ISSUE THREAD

**Issue by justinpotts** [mozilla/addons-server#3212]
For dropdowns such as this one, we need an ID or Class Name to interact with these more concretely, since the order of them changes depending on previous user behavior.

<img width="552" alt="screen shot 2016-08-02 at 7 42 23 am" src="https://cloud.githubusercontent.com/assets/2042849/17332764/b45cb664-5884-11e6-8f84-c67889ac38e2.png">

For example, when it's the user's first time submitting an add-on, they'll see this, which is great and we can just select the first `<li>`. However, after this account has done it once, they'll see "Manage my Submissions" as the first item, and we have to choose the second item.

Currently, our automated tests are relying on finding the element by Link Text, essentially the content in between the hrefs. It would be great to have these locators in case the wording changes, we have something more concrete to keep the tests from failing.

**Comment by muffinresearch** [comment]
Something I've done in the past is to use `data-qa-[name]=[value]` (with the value being completely optional if you just want a boolean attr) that way it's clear to a dev that changing that markup will likely break a test, plus it provides a nice way to find the relevant test. The only downside is that it adds weight to the page but if that got excessive it could be conditionally published only when under test.

**Comment by EnTeQuAk** [comment]
@jrbenny35 I wonder if we can close this and add these classes along new tests where they're needed?
