### ISSUE TITLE
old toolbar back 

### ISSUE THREAD

**Issue by elisha1983** [mozilla/addons-server#3214]
I don't like the new yahoo toolbar it want let u add what u want to it. is there some way i can get the old one back on my computer 
![img_2849](https://cloud.githubusercontent.com/assets/20806537/17351730/264ddc88-58ff-11e6-8812-f931509a193c.JPG)

**Comment by wagnerand** [comment]
The author of that add-on is responsible for the add-on. Please contact them.

**Comment by elisha1983** [comment]
How do I contact them don't get mad I was just wondering

**Comment by muffinresearch** [comment]
@elisha1983 there's a number of posts on Yahoo's forums re the toolbar see https://forums.yahoo.net/t5/Other-products/bd-p/additional-yahoo-products otherwise Yahoo's main support website can be found here: https://help.yahoo.com/kb/helpcentral
