### ISSUE TITLE
old toolbar back

### ISSUE THREAD

**Issue by elisha1983** [mozilla/addons-server#3215]
I don't like the new yahoo toolbar it want let u add what u want to it. is there some way i can get the old one back on my computer 
![img_2849](https://cloud.githubusercontent.com/assets/20806537/17351758/524463fc-58ff-11e6-9074-9bcc2be597a3.JPG)

**Comment by elisha1983** [comment]
I don't like the new yahoo toolbar it want let u add what u want to it. is there some way i can get the old one back on my computer

**Comment by elisha1983** [comment]
![img_2849](https://cloud.githubusercontent.com/assets/20806537/17351776/71d25422-58ff-11e6-9dcb-be84f43cfeeb.JPG)

**Comment by elisha1983** [comment]
I don't like the new yahoo toolbar it want let u add what u want to it. is there some way i can get the old one back on my computer 
![img_2849](https://cloud.githubusercontent.com/assets/20806537/17351784/84c70bf4-58ff-11e6-8143-8e91190aba69.JPG)

**Comment by wagnerand** [comment]
The author of that add-on is responsible for the add-on. Please contact them.

**Comment by elisha1983** [comment]
How do I find out who it is

**Comment by muffinresearch** [comment]
@elisha1983 there's a number of posts on Yahoo's forums re the toolbar see https://forums.yahoo.net/t5/Other-products/bd-p/additional-yahoo-products otherwise Yahoo's main support website can be found here: https://help.yahoo.com/kb/helpcentral
