### ISSUE TITLE
Make the old olympia documentation go away

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3220]
For some reason (awesome bar ghosts?!) I still land on http://olympia.readthedocs.io/en/latest/ sometimes. Can we make that go away? Or can we make it redirect to http://addons-server.readthedocs.io/en/latest/ ? It is very confusing.

**Comment by andymckay** [comment]
You can't do a whole project redirect, but I did just remove olympia from read the docs, so now it 404s.

**Comment by kumar303** [comment]
thanks!
