### ISSUE TITLE
Rename Fully Reviewed to Approved

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3227]
This is part of #3083.

As part of the follow up work for removing preliminary review, we should remove the visible references to `Full Review` and `Fully Reviewed` and just go with `Approved` instead.

**Comment by wagnerand** [comment]
Same with `Awaiting Full Review` => `Awaiting Review`.

**Comment by eviljeff** [comment]
To confirm, what about `Awaiting Review` (unreviewed files) and `Awaiting Full Review` (nominated)?  Everything should be approved, rather than reviewed?

**Comment by eviljeff** [comment]
effectively all the terms in here:
https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/base.py#L22:L51 (Ignore the preliminary ones, they'll be going)

**Comment by jvillalobos** [comment]
Yes, `Awaiting Review` and `Approved` for both file and add-on status.

**Comment by eviljeff** [comment]
we also need to rename `Nomination` queue and similar to `New Add-ons` and `Pending Updates` to just `Updates`

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
Postfix screenshots: 
![status versions](https://cloud.githubusercontent.com/assets/15685960/19072328/4d7e3c70-8a3d-11e6-8016-bc9d5738c059.png)
![2016-10-04_1406](https://cloud.githubusercontent.com/assets/15685960/19072332/55b2afde-8a3d-11e6-9c9f-f4d994d6e7ce.png)
![approved](https://cloud.githubusercontent.com/assets/15685960/19072343/6464c17a-8a3d-11e6-80de-0b4995228289.png)
![dev-hub](https://cloud.githubusercontent.com/assets/15685960/19072342/64649a42-8a3d-11e6-96bb-feb28801e16a.png)
![newvers](https://cloud.githubusercontent.com/assets/15685960/19072344/64672438-8a3d-11e6-8791-ed04ef982087.png)

**Comment by ValentinaPC** [comment]
I forgot the changes from the queues:
![editor_tools_nomination_queue](https://cloud.githubusercontent.com/assets/15685960/19072601/cf7e8940-8a3e-11e6-9305-c0460ed83c4b.png)
