### ISSUE TITLE
Version check serving badly formatted XML for disabled add-on

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3228]
A parsing error in the Add-ons Manager lead to finding this issue. The long-dead [Microsoft .NET Framework Assistant](https://addons.mozilla.org/en-US/firefox/addon/microsoft-net-framework-assist/) add-on has been disabled for a while. However, its individual files weren't disabled and still had a Fully Reviewed status.

Checking for updates for this add-on yields an XML file ([version-check.xml.txt](https://github.com/mozilla/addons-server/files/404751/version-check.xml.txt)) with a malformed URL:

`<em:updateLink>/_privatefiles/9449/microsoft_net_framework_assistant-1.3.1-fx-windows.xpi?filehash=sha256%3A3dca35bee0acb9e767d683e2096fdb53f1b9a551a13983070dadd7db12e69cfb</em:updateLink>`

Disabling the files fixed the problem for this add-on, but we should still make sure we handle this case. Developer or admin disabled add-ons shouldn't be serving updates.

@rhelmer @sapohl

**Comment by diox** [comment]
In `services/update.py` we do through:
- `get_rdf()`
- `self.is_valid()` (returns `True`, even for disabled add-ons)
- `self.get_update()` which does `row['url'] = get_mirror(data['addon_status'], data['id'], row)`

And `get_mirror()` does this:
```
    if row['disabled_by_user'] or status == STATUS_DISABLED:
        host = settings.PRIVATE_MIRROR_URL
    else:
        host = user_media_url('addons')
```

If the add-on is not disabled, `host` will be something like `https://<cdn>/user-media/addons/` but if it's disabled, it'll just be `/_privatefiles`.

If developer/admin disabled add-ons shouldn't be serving updates, then the solution is probably to modify the query in `is_valid()` to reflect that, and always serve an empty RDF file for them... That likely means all the code handling disabled status elsewhere in `services/` would be dead and should be removed.

**Comment by ValentinaPC** [comment]
Verified this as fixed for `admin-disabled add-on status `on AMO-dev FF51(Win 7):
-> while installing an approved version (not the last one) of an add-on, and "admin-disabling" the add-on after that, I was not able to find any updates for that add-on.

For `admin-incomplete add-on status` or `admin-awaiting review add-on status` **updates are found**.
By `admin` I mean: changing an add-on general status from Admin Manage page.
@diox : Please let me know if this behavior is ok or needs further investigation.

**Comment by diox** [comment]
Yeah, I could have tightened the status condition even more but it didn't feel necessary and could potentially replace one edge case by another.
