### ISSUE TITLE
Install button in version list shows confusing "works with" message

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3229]
STR:
- Pick an app that is not compatible with Android
- On desktop, open its version page, using android as the app in the URL, like this: https://addons.mozilla.org/en-us/android/addon/fireftp/versions/
- Hover the versions in the list

Expected results:
- Since you're using a desktop browser, the install buttons should not say anything about Android. Or maybe you should have been redirected ? Not sure. Anything but the behavior described below :)

Actual results:
- When hovered, the versions show a green install button with a super confusing warning saying "works in Android" - which is not true - with a "no" red sign.

It looks like it's done by https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/buttons.js ; not sure, lots of duplication between different templates and that js code :(

**Comment by vcarciu** [comment]
Verified as fixed : http://screencast.com/t/y4qwx0zZ

**Comment by atiqueahmedziad** [comment]
@vcarciu your screencast doesn't match the `after` screenshot present in pr #3414 
I am missing the warning message- `Only works on Firefox Desktop` (My bad :( ) below the red download button.
Please open the issue. I will give a pr very soon to fix it :)
