### ISSUE TITLE
[FF48]Corrupt message at add-on installation in AMO-dev and stage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3235]
Steps to reproduce:
1. Upgrade Firefox browser to 48
2. Install an add-on on dev or stage (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/noverflow/?src=hp-dl-featured)

Expected results:
The add-on is installed.

Actual results:
A "corrupt" message is displayed.

Notes/Issues:
The signature pref is set true. **Issue is not reproducing on AMO-prod.**
Verified on AMO-dev and stage using FF48(Win 7 x64).
The message "1470753001404	addons.xpi	WARN	Download of https://addons.allizom.org/firefox/downloads/latest/rainbow-color-tools/addon-14328-latest.xpi?src=hp-dl-featured failed: signature verification failed" is displayed din the browser console.
Please see the screenshot: 
![corrupt](https://cloud.githubusercontent.com/assets/15685960/17519997/c75537aa-5e56-11e6-8cff-e86bd7c5c9c4.png)

**Comment by andymckay** [comment]
Could you please file this in Bugzilla under Toolkit > Addons Manager. My guess is that signing enforcement is happening. This might be unfixable with signing enforcement, just so you know.

**Comment by ValentinaPC** [comment]
Because of:  _"Firefox 48: (Pushed from Firefox 46). Release and Beta versions of Firefox for Desktop will not allow unsigned extensions to be installed, with no override. Firefox for Android will enforce add-on signing, and will retain a preference — which will be removed in a future release — to allow the user to disable signing enforcement."_ I'll not log an issue in Bugzilla.
Sorry for the noise.

**Comment by andymckay** [comment]
You can try using the unsigned builds: https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds
