### ISSUE TITLE
No right-padding at hover in "More by this Artist"/"My Profile" themes sections

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3243]
Steps to reproduce:
1. Load details page for a theme in AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/addon/cute-birds-animated/
2. Go to "More by this Artist" section and hover over any theme

Expected results:
There are no display or layout issue.

Actual results:
There is no right-padding for the theme.

Notes/Issues:
This issue is also reproducing in Theme section from _My Profile_.
Screenshots fro this issue: 
![padding](https://cloud.githubusercontent.com/assets/15685960/17550193/7433a768-5efc-11e6-9277-b588b432ed07.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7)
Postfix screenshots:
![padding](https://cloud.githubusercontent.com/assets/15685960/17558300/ce9c9914-5f22-11e6-9c88-d8a9af8bbc67.png)

**Comment by ValentinaPC** [comment]
This is still reproducing in AMO-prod.

**Comment by tofumatt** [comment]
I don't think this made it to the prod tag and didn't feel it was a
blocker, so we'll see it in the next push.

- tofumatt
