### ISSUE TITLE
Incompatible add-ons from featured section (any category) breaks the row at hover

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3250]
**For this issue to reproduce, an incompatible add-on must be listed in Featured section from add-on categories.**

Steps to reproduce:
1. Log in to AMO-stage https://addons.allizom.org/en-US/
2. Load Appearance add-on category in AMO-stage https://addons.allizom.org/en-US/firefox/extensions/appearance/
3. Make an add-on listed in featured section incompatible with your platform or browser 
4. Go back to that category and hover over the changed add-on

Expected results:
Changes are made. There are no display or layout issues.

Actual results:
Changes are made. The "not available.." banner escapes the box and the next displayed add-on from Featured section, disappears.

Notes/Issues:
Verified on Ff48(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Screenshots for this issue:
![cat](https://cloud.githubusercontent.com/assets/15685960/17555749/67570ce8-5f19-11e6-8be9-765b7bffd864.png)
![2016-08-10_1629](https://cloud.githubusercontent.com/assets/15685960/17555783/85cede9e-5f19-11e6-8086-03eb7898f4c9.png)

P.S. for incompatible add-on listed in other category section things look a bit "large" - don't know if expected. (see second screenshot)

**Comment by ValentinaPC** [comment]
Verified as fixed in what concerns the "evanescence" of the next displayed add-on, but the fix looks like this: 
![2016-08-12_1619](https://cloud.githubusercontent.com/assets/15685960/17623476/e54599b8-60a8-11e6-873c-1bf599b78b5a.png)

@tofumatt ?

**Comment by tofumatt** [comment]
Darn. Okay, can you file a new issue for that and I'll fix it. What a rabbit hole!

**Comment by ValentinaPC** [comment]
The same layout issue seems to affect collections.
Please check the last add-on added in the collection: https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-add-ons/?sort=added&page=9 
Screenshot: 
![2016-08-18_1703](https://cloud.githubusercontent.com/assets/15685960/17777076/cec24dbc-6567-11e6-910f-22c9fd731eb2.png)
