### ISSUE TITLE
Useless scrollbar in themes history for pagination section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3251]
Steps to reproduce:
1. Log in with an admin account in AMO-stage https://addons.allizom.org/en-US/
2. Go to any theme details page
3. Click on "Review History" blue button
4. Click "Your Review History" button from the right side
5. Scroll down to the end of the page

Expected results:
There is a navigation section with no layout issues.

Actual results:
There is an unused scroll-bar in the pagination section.

Notes/Issues:
You must have over one page activity in themes history for this to reproduce.
Verified on FF48(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![x](https://cloud.githubusercontent.com/assets/15685960/17561179/868546fc-5f2d-11e6-98ae-851c18adbfec.png)

**Comment by tofumatt** [comment]
Does this only happen with an admin account? If so I would WONTFIX this.

**Comment by ValentinaPC** [comment]
I cannot access Editor Tools without an admin account. I don't know if your are a reviewer, you also can access the page, don't you?
Your choice. :smile:

**Comment by tofumatt** [comment]
I think this is small enough to won't fix, if an admin/reviewer disagrees feel free to reopen 😄
