### ISSUE TITLE
"Awaiting..." status for an add-on with its only version "Approved"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3256]
Steps to reproduce:
1. Submit a fully reviewed add-on in AMO-stage https://addons.allizom.org/en-US/developers/ and approve it
2. Add a new version for that add-on (without approve)
3. Disable the approved version
4. Re-enable the approved version
5. Delete the "awaiting..." version

Expected results:
Add-on status is the same as the version status: fully reviewed.

Actual results:
Add-on general status is "awaiting prelim review" and add-on version is "fully reviewed".

Notes/Issues:
**If "view listing" link is clicked, the add-on appears as "This add-on has not been reviewed by Mozilla. Learn more" but if we download the add-on: it is signed.**
Don't know if what happens after step #3 (add-on status turns into aw prelim review from fully reviewed) is another issue, same issue, or something intended?
Video for this issue: 
![i](https://cloud.githubusercontent.com/assets/15685960/17585715/e176a5f4-5fc5-11e6-87ed-07856e4b5b62.gif)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF48(Win 7 x64) and observed:
- after making the exact steps as described above add-on status "Awaiting Full Review"  does not match its only version status "Fully Reviewed"
- if "view listing" link is clicked, the add-on appears as "This add-on has not been reviewed by Mozilla. Learn more" but if we download the add-on: it is signed.

I know this is a bit edgy... you know better if this require another fix.
Good thing: the preliminary review status is gone.

Screenshots: 
![2016-08-17_1057](https://cloud.githubusercontent.com/assets/15685960/17728928/5ebe8ee8-646a-11e6-8a43-4d826a6c08a1.png)
![2016-08-17_1058](https://cloud.githubusercontent.com/assets/15685960/17728932/648d4a4e-646a-11e6-90ac-0ce374d06b64.png)

Reopening until further notice.

**Comment by eviljeff** [comment]
I can imagine how it can happen but I don't think it's enough of a problem to warrant a fix before the cleanup, which will involve rewriting the code that handles the status changes anyway.  

I checked and it does show up in the review queue, but with no way to approve - in this case we'd expect someone to ping an admin and we'd do a manual fix.

**Comment by wagnerand** [comment]
@eviljeff Can you document the here how this can happen, so admins are aware? Thanks.

**Comment by eviljeff** [comment]
> Can you document here how this can happen, so admins are aware? Thanks.

using the admin manage page for the addon in /admin/ we need to change the add-on status in the select field to be Fully Reviewed (soon to be 'Reviewed')

**Comment by eviljeff** [comment]
going to close this in preference to #3876

**Comment by ValentinaPC** [comment]
@eviljeff Even if #3876 was marked as dupe for #4024 which it was fixed, this is still reproducing and has to do with "disable-renable" and not with "Invisible-Visible", also this add-on contains an approved version.

STR:
   1. Submit an unlisted/listed add-on (approve the listed add-on)
   2. Disable its version
   3. Re-enable it
   4. Click the "Request Review" link from Manage "Status & Versions" page

Please let me know what you think!

**Comment by muffinresearch** [comment]
@vcarciu if you have time would be good to know if this one is still relevant in the post-review world or if we can close it out?

**Comment by wagnerand** [comment]
Let's reopen this until we hear back from @vcarciu.

Also, probably related to #3051 .

**Comment by AlexandraMoga** [comment]
@muffinresearch This is still happening in the current process, with the exception that the user can't request another review any longer. The inconsistency will result now from an "Incomplete" general status vs an "Approved" version status (when only one version is available).

![image](https://user-images.githubusercontent.com/31961530/35854262-8c6cb380-0b38-11e8-83d0-74bb9826c16b.png)

As a side note, the new "Force disable/enable add-on" action available in Rev Tools has the ability to override the Incomplete status:
- with 'Force disable' - add-on general status -> 'Disabled by Mozilla'
- with 'Force enable' - add-on general status -> 'Available' (no longer Incomplete)

**Comment by AlexandraMoga** [comment]
This is still an issue so it would be good to keep it open
