### ISSUE TITLE
Long author name breaks layout for Themes

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3258]
Steps to reproduce:
1. Change your display name in a long one in AMO-stage https://addons.allizom.org/en-US/firefox/
2. Go to "My Themes" page and hover over any submitted theme

Expected results:
There are no display or layout issues.

Actual results:
The long author name brakes theme layout.

Notes/Issues:
Verified on FF48(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
-at hover
![2016-08-11_1625](https://cloud.githubusercontent.com/assets/15685960/17590168/4eb07968-5fe1-11e6-864c-dfd57a54104c.png)
-without hover
![without_hover](https://cloud.githubusercontent.com/assets/15685960/17590238/a393ab1c-5fe1-11e6-876f-64ddca894eb3.png)

#2275

**Comment by Prashant-Surya** [comment]
Can I work on this? It is similar to issue https://github.com/mozilla/addons-server/issues/2818 I worked on

**Comment by wagnerand** [comment]
Sure, go ahead!

Your mentor is @tofumatt since he already reviewed the other PR.

**Comment by Prashant-Surya** [comment]
@tofumatt For displaying long name in hover mode using height:auto is sufficient. But while displaying the name without breaking in no hover state should I use ellipsis?

**Comment by tofumatt** [comment]
Yes, an ellipsis that cuts off the text would be perfect. Thanks 😄

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7).
Postfix screenshots:
![longname](https://cloud.githubusercontent.com/assets/15685960/18338686/7ee42490-75a3-11e6-9aac-83cce634e75c.png)
