### ISSUE TITLE
Browser incompatible add-ons from featured section have layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3265]
For this issue to reproduce, an incompatible add-on must be listed in Featured section from add-on categories.

Steps to reproduce:
1. Log in to AMO-dev https://addons-dev.allizom.org/en-US/
2. Load an add-on category
3. Make an add-on listed in featured section incompatible with your browser
4. Go back to that category and hover over the changed add-on

Expected results:
Changes are made. There are no display or layout issues.

Actual results:
There is a small layout issue.

Notes/Issues:
Not reproducing if the add-ons are incompatible with your platform.
Verified using FF48(Win 7). 
Screenshot for this issue: 
![e54599b8-60a8-11e6-873c-1bf599b78b5a](https://cloud.githubusercontent.com/assets/15685960/17625350/2ed376f6-60b1-11e6-8a6c-be05a37e6f7d.png)

**Comment by tofumatt** [comment]
This page was replaced by the new front-end, so closing.
