### ISSUE TITLE
Validation of overlay extension fails: No install.rdf or manifest.json found Add-on missing manifest.

### ISSUE THREAD

**Issue by kabeleced77** [mozilla/addons-server#3266]
Hi,
I would like to upload and validate my overlay extension but failing with:

Your add-on failed validation with 2 errors.
    No install.rdf or manifest.json found
    Add-on missing manifest.

install.rdf & chrome.manifest files are included and saved in the root folder of the extension. The extension is working in the latest Firefox developer edition (50.0) though.

Thanks
Kabeleced
[foxfm_0-30-0.zip](https://github.com/mozilla/addons-server/files/416110/foxfm_0-30-0.zip)

**Comment by diox** [comment]
The files are not in the root folder in that .zip, they are in a `foxfm_0-30-0` folder. Move everything from that folder to the root of the archive and it should solve your problem.

**Comment by kabeleced77** [comment]
Thank you very much!

**Comment by diox** [comment]
Also, there appears to have other errors, but at least your `<em:id>` is invalid, it should be between brackets, like this: `<em:id>{9259A3DC-60C8-11E6-90EE-7C5C6166FB5E}</em:id>`.

**Comment by kabeleced77** [comment]
Thanks, fixed that already. Used to be an email address and changed it back to it.
