### ISSUE TITLE
Firefox Add-on listed rendering page not found

### ISSUE THREAD

**Issue by lasernite** [mozilla/addons-server#3274]
Hi Mozilla,

The extension 'Websee' appears to say that it is listed, but the link from the dashboard renders a page not found error: https://addons.mozilla.org/en-US/firefox/addon/websee/

![Dashboard navigation](https://cloud.githubusercontent.com/assets/1097642/17687834/9e4e2192-632d-11e6-998d-a6df2ea7d3b8.png)

It says it's 'Incomplete' but 'Listed', and clicking 'View Listing' goes to the page not found page.

Thanks!

**Comment by diox** [comment]
Thanks for your report. The wording is unfortunate, but add-ons in incomplete status can't be displayed even when their visibility is set as "listed", because they are, well, incomplete. If you complete the submission the add-on status will be changed and the listing page will be available.
