### ISSUE TITLE
Search Tools without mandatory author name

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3280]
Steps to reproduce:
1. Load details page for a search tool i.e. https://addons.allizom.org/en-US/firefox/addon/video-sequereeu/
2. Observe the author name

Expected results:
The name of the author is listed (or, if not mandatory, the "by" text is not displayed)

Actual results:
The author name is not listed. 

Notes/Issues:
If we go to "Manage" page, we observe no author listed, but if we click "save changes" _without making any changes_, the text "Must have at least one owner." is displayed.
Verified on FF48(Win 7x64). Issue is only reproducing on stage.
Screenshot for this issue: 
![2016-08-17_1319](https://cloud.githubusercontent.com/assets/15685960/17733339/c2c4f012-647e-11e6-910a-44493f99cd81.png)

**Comment by muffinresearch** [comment]
> Verified on FF48(Win 7x64). Issue is only reproducing on stage.

I see this on production too.

<img width="230" alt="video____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/17733748/06dd8aa2-6470-11e6-89eb-88820b595a76.png">

**Comment by jvillalobos** [comment]
The add-on apparently has no authors, which is very odd. The add-on is also very old, so I don't think if it's worth investigating how it ended up that way. We could either disable the affected add-ons or leave them in their current state. I think I prefer the latter, even if it looks odd.

**Comment by diox** [comment]
wontfixing then.
