### ISSUE TITLE
Re-using a version number we re-packed breaks file

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3286]
We did a couple of rounds of repacking add-ons for several reasons (`let` changes, signing...). In some of those rounds we changed the version string (to make Firefox recognize it as an update) of an existing version, instead of uploading a new one. We also replaced the original file on the filesystem.

If a developer chooses to re-use that version number (which we'd normally prevent but we changed the version string), it will break the repacked version as the new version will replace the old file.

Example where this happened: https://addons.mozilla.org/en-US/editors/review/ip-check

The author uploaded version 0.2.1 before we had signing, so when we bulk-signed, this version got renamed to 0.2.1.1-signed. After that, the author uploaded 0.2.1 again which a reviewer rejected, but at that point it was already too late. The new (rejected) file replaced the old (signed) file, resulting in that version being still public but it's file being inaccessible, and therefore 404.

cc @jasonthomas

**Comment by EnTeQuAk** [comment]
hmm, a lot has happened since then especially with all our refactorings going on. I wonder if this is still valid and a problem?

**Comment by wagnerand** [comment]
It's still valid, but I think it's far enough in the past so that it's not super relevant anymore. Also, we haven't done any repacks for webextensions (yet).
