### ISSUE TITLE
No data for ru locale in discovery pane

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3287]
Seems to be a regression related to the author link changes. see https://discovery.addons.allizom.org/ru/firefox/discovery/pane/48/Darwin/normal

Results in this:

<img width="449" alt="_ _ _" src="https://cloud.githubusercontent.com/assets/1514/17772970/af3a4d92-6543-11e6-89dc-8e544ab8f95e.png">

Traceback from https://sentry.prod.mozaws.net/operations/olympia-stage/issues/345578/

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
  File "rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "olympia/discovery/serializers.py", line 41, in to_representation
    addon_name, _('by'), url, authors))
```

**Comment by ValentinaPC** [comment]
Verified the above link in my browser and seems fixed.
Please see the screenshot: 
![darwin](https://cloud.githubusercontent.com/assets/15685960/17777678/1d7ca220-656a-11e6-8096-984dc9159f1d.png)

Downloaded FF48.0.1 RU build and the disco-pane page is displayed as expected.
![2016-08-18_1730](https://cloud.githubusercontent.com/assets/15685960/17777712/38e29a10-656a-11e6-9fa0-6128ce298cde.png)
 
Please let me know if there anything else I should verify here.

**Comment by muffinresearch** [comment]
@ValentinaPC that's it - thanks!
