### ISSUE TITLE
Use better wording for "We do not make your email address available to add-on developers and they may need to contact you to help resolve your issue."

### ISSUE THREAD

**Issue by TonnesM** [mozilla/addons-server#3290]
"We do not make your email address available to add-on developers and they may need to contact you to help resolve your issue."

This string turns up twice in strings at this point and appears to be a bit confusing as well as contradictive to say the least, i.e. users would expect to have their emails made available when developers may need to contact them. I know there is a support link for that purpose, but that's not being made very clear and the wording may be improved nevertheless, especially because of the ""we don't make it available, and they may need to contact you" part. It's also confusing for localizers, and I've seen some weird translations for it.

How about using something like "We do not make your email address available to add-on developers. In case you want them to contact you to help resolve your issue, use the support link instead.", or better? (Will leave that to others, since English is not my native language.)

**Comment by TonnesM** [comment]
I agree about "Please do not post bug reports in reviews", but also (and mainly) think that "Developers can't contact you back to help resolve your issue" should be avoided, because it simply isn't always true, it implies a flaw, and it's not the real reason why users shouldn't (ab)use the reviews for bug reports. Please also keep in mind some users may stop reading after that sentence, and possibly get annoyed.

So instead, it might be better to just point their attention to how they _can_ submit feedback, i.e. the support link, if available. If it's a requirement to elaborate on why they shouldn't use reviews for that, it might be better to mention that developers aren't always able to or simply don't like to dig through reviews to find bugs/issues. ;)

**Comment by EnTeQuAk** [comment]
@jvillalobos @atsay any more opinions on this one and recent suggestions?

**Comment by jvillalobos** [comment]
We plan to change the rating flow in the future, so we won't make any big changes now. Maybe we should just close this and leave it for the new version.

**Comment by TonnesM** [comment]
My $0.02:
Sorry to say but I don't agree with the latter, since it would be yet another Mozilla project stalled with issues just because of "future" plans that might get postponed, like happened before. It would retain the issues and annoyance for users as well, and be a waste of time and resources (including mine) while it could easily be solved, even if it was for just a couple of (tentative) months.

IMO, what could be fixed quickly should be and users should be served and guided as best as we can. Meanwhile I have seen a number of projects and bugs waiting for action (or a future) long enough to get invalid in the end (even though some were accepting other strings or patches meanwhile), causing users to legitimately complain about actions not taken. I don't like that, but it’s just my 2 contributor cents, and I may not be aware of future plans enough.

**Comment by EnTeQuAk** [comment]
I'm going to close this since we're busy working on the future. Please feel free to re-open anytime if there's the need to do that but I'm guessing discussing the proper wording for this can also take quite some time which might be better suited otherwise.

**Comment by TonnesM** [comment]
Not entirely unexpected but this year’s first dismay, which will make me hesitate to ever report such issues in the future. I think this could have taken 5 minutes to fix at most while adding new strings simply by rewording to something like 
"We do not make your email address available to add-on developers, so they can’t contact you to help resolve your issue."
...like we are currently using for our locale. Users don’t live in the future.

**Comment by atsay** [comment]
Ugh, this is another one of those bugs I was cc'd on but never got a notification. Don't know why that happens. I agree this is a simple text change that would make life a little easier, so let's do it. Let's go with:

"Please do not post bug reports here. We do not make your email address available to add-on developers, so they can't contact you to resolve your issue.

See this add-on's [support section](/#support) to find out if assistance is available. You can also try asking the [add-on community](https://discourse.mozilla-community.org/c/add-ons/add-on-support) for help."

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50.1(Win 7)
Postfix screenshots:
![1](https://cloud.githubusercontent.com/assets/15685960/21850911/90fbd7a2-d815-11e6-868c-91826679c71b.png)
![2](https://cloud.githubusercontent.com/assets/15685960/21850912/90fc9980-d815-11e6-8662-a3b5a0a34825.png)
![themes](https://cloud.githubusercontent.com/assets/15685960/21850991/f4f82a12-d815-11e6-85bb-5258e095ca82.png)

**Comment by atsay** [comment]
Thank you @ValentinaPC and @EnTeQuAk! And @TonnesM for filing the issue :-)

**Comment by TonnesM** [comment]
Thank you all for fixing, and sorry for my somewhat moody replies. ;-)
