### ISSUE TITLE
"Blocked Add-on" prompt while installing add-ons on Android

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#3294]
## system info:

6.0.1 / Nexus 6
Latest Nightly - 51.0a1
## steps to reproduce:
1. Load https://addons.mozilla.org on your Android device
2. Find the first add-on listed and load the details page
3. Install the add-on
## expected behavior:

Install is successful
## actual behavior:

There is a warning about the add-on being "Blocked". However, on clicking 'Allow' on that warning, the add-on is successfully installed.
## logcat:

 https://pastebin.mozilla.org/8902295
## screenshot

![img_2103](https://cloud.githubusercontent.com/assets/301317/17794305/0f38c358-6563-11e6-87c6-f0ae299c1612.JPG)

**Comment by wagnerand** [comment]
This looks very familiar to the extension installation doorhanger on desktop, which can be configured on about:preferences#security. I'm not that familiar with Android, is there a similar setting and maybe somehow AMO got deleted from the exceptions list?

**Comment by ValentinaPC** [comment]
Verified this on FF48 using Android 6.0.1.

I was able to install the add-on from the screenshot with success.
Also tried with the first listed add-on, and was installed without being blocked.
Screenshots: 
![screenshot_2016-08-23-13-06-45](https://cloud.githubusercontent.com/assets/15685960/17888398/784e9470-6933-11e6-944d-1561c304c850.png)
![screenshot_2016-08-23-13-07-53](https://cloud.githubusercontent.com/assets/15685960/17888399/787d4d10-6933-11e6-8bbf-806534fcb8be.png)

**Comment by andymckay** [comment]
Suspecting this is an issue in nightly with Android. If it doesn't get resolved soon, probably makes more sense to open an Android bug.

**Comment by EnTeQuAk** [comment]
@krupa is this still reproducable or can this be closed?

**Comment by ValentinaPC** [comment]
@EnTeQuAk: Verified this on all AMO servers and received 3 different results, as follows:

1. AMO-stage under FF54.0a1 (Android 6.0.1) and **the message with "blocked add-on" content is still displayed** - add-on is installed if we click "Allow"
Please see the screenshot:
![nightly-stage](https://cloud.githubusercontent.com/assets/15685960/23157652/ba693678-f824-11e6-9342-be06f28f0cc1.png)

2. AMO-prod under FF54.0a1 (Android 6.0.1) and **the message is not displayed** - add-on is installed
Please see the screenshot:
![n-prod](https://cloud.githubusercontent.com/assets/15685960/23157833/623bb420-f825-11e6-8150-6f3cfee5c08e.png)

3. AMO-dev under FF54.0a1 (Android 6.0.1):
-> with `extensions.webapi.testing` set to `true` I encounter the issue #[1724](https://github.com/mozilla/addons-frontend/issues/1724)
-> with `extensions.webapi.testing` set to `false` I encounter the issue #4443

**Comment by eviljeff** [comment]
this sounds like the same issue as #4565
