### ISSUE TITLE
Password is not correctly displayed when clicking the Show button

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3295]
Steps to reproduce:
1. Open AMO homepage and click the Register link.
2. Enter an email address and click the Continue button.
3. Fill the form and click the Show button for the password field.

Expected results:
The password is displayed and it's displayed until the Show button is clicked again.

Actual results:
The password is just displayed for a fraction of a second when clicking the Show button.

Notes/Issues:
Issue is also reproducing in the log in form.
Verified in FF48(Win7) Issue can be reproduced in amo-prod and amo-stage. Issue is not reproducing in amo-dev.
Screencast for this issue:
![showpasswordissue](https://cloud.githubusercontent.com/assets/15685441/17802078/a8f6b444-65f6-11e6-802c-9161285f7011.gif)

**Comment by andymckay** [comment]
Chatting to vladikoff on IRC, it was said this is by design. This page is on a Firefox Accounts page, so any further bugs should be filed against that project, not this one.

**Comment by kitcambridge** [comment]
> This page is on a Firefox Accounts page, so any further bugs should be filed against that project, not this one.

Which is https://github.com/mozilla/fxa-content-server, for the record. 😃

**Comment by ryanfeeley** [comment]
FIrst of several fixes to come: https://github.com/mozilla/fxa-content-server/issues/4076
