### ISSUE TITLE
bad link for theme

### ISSUE THREAD

**Issue by mikeestl08** [mozilla/addons-server#3303]
The theme is not working correctly and went to get an update and found this link wasn't working: https://addons.mozilla.org/en-US/firefox/addon/space-fantasy/

**Comment by wagnerand** [comment]
Are you the owner of that theme?

**Comment by mikeestl08** [comment]
Now I had just noticed that the link was bad after that is having problems with the theme but I guess you have discovered that the link that I had wasn't bad?

**Comment by wagnerand** [comment]
I can't find any reference to this url in our system nor was this theme recently deleted. I think you just got the wrong link.
