### ISSUE TITLE
Addons can still be preliminary reviewed

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3304]
### Steps to reproduce:
1. Enable the "Disallow Preliminary review" in AMO-dev
2. Go to editor tools - preliminary review queue.
3. Open any add-on review detail page.

### Expected results:
The add-on can't be approved with the prelim reviewed status.

### Actual results:
The add-on can be preliminary reviewed.

### Notes/Issues:
Verified in FF48(Win7) Issue can be reproduced in amo-dev
Screencast for this issue:  
![prelimreview01](https://cloud.githubusercontent.com/assets/15685441/17853621/60a15398-6876-11e6-8ffe-cfc2dbd660c3.gif)

**Comment by eviljeff** [comment]
That's as expected if it was pending preliminary review.
