### ISSUE TITLE
Both unlisted and bundled unlisted addons are fully reviewed

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3305]
### Steps to reproduce:
1. Submit an unlisted add-on and one bundled unlisted add-on. 

### Expected results:
Since bot flows grant full review only one should be kept.

### Actual results:
Both submission processes are displayed and both grant full review.

### Notes/Issues:
Verified in FF48(Win7) Issue can be reproduced in amo-dev

**Comment by eviljeff** [comment]
This is just a checkbox that's ignored - everything gets the sideloading treatment now.

**Comment by madalincm** [comment]
Verified as fixed in FF48(Win7) in addons-dev.allizom.org
postfix screencast: 
![sideloadsubmis](https://cloud.githubusercontent.com/assets/15685441/17939058/7316b588-6a31-11e6-9e2c-0801350919a5.png)
