### ISSUE TITLE
Don't add "restart required" to search engines

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3307]
As per: https://blog.mozilla.org/addons/2016/08/15/restart-required/#comment-222469 let's remove this from search engine plugins please.

**Comment by diox** [comment]
Interesting: we never cared about it before, but yeah, search add-ons were never considered "restartless". This will need a fix in the code as well as a migration for the existing data.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7 x64)
Postfix screenshots (before/after):
![2016-08-23_1612](https://cloud.githubusercontent.com/assets/15685960/17893033/cae649c6-694c-11e6-9a24-ba98ab1ff5fd.png)
