### ISSUE TITLE
New unlisted submissions end up with wrong add-on status

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3314]
New unlisted files are automatically approved, but the add-on status is still `STATUS_NOMINATED`instead of `STATUS_PUBLIC`.

**Comment by wagnerand** [comment]
I haven't seen this before we flipped the waffle switch to disable preliminary-review level today, so I am fairly certain it's related to that.

Adding @eviljeff

**Comment by jvillalobos** [comment]
It'd be good to test that unlisted submissions are getting the approval email. If they do, this doesn't affect developers much, because they can still download the signed files. The status in the developer page is confusing, though, and the add-ons are showing up in the unlisted review queue until admins clean up their status.

**Comment by ValentinaPC** [comment]
@jvillalobos : I've submitted on AMO-dev FF48(Win 7) an unlisted add-on. I've checked the e-mail used while submitting, and no mail was received. Not sure if this is the case you are talking about in the above comment, but if YES, this is the results.

Hope I helped.

**Comment by eviljeff** [comment]
I can't replicate this on -dev or prod via the website.  Maybe it's API uploads?

**Comment by jvillalobos** [comment]
Looking at the DB, I can see a fraction of unlisted submissions (less than half) are getting the right status, so it's possible this has to do with the API.

**Comment by eviljeff** [comment]
I can replicate via the API with dev.

I'm blocked on either getting the server logs (kibana wasn't working and i'm not authorized anyway currently) or being able to use the API locally to debug (various jpm issues).

**Comment by eviljeff** [comment]
I can't replicate this locally via the API.

**Comment by eviljeff** [comment]
QA: this needs to be tested via the API as well as via devhub.  It's only unlisted add-ons that were affected.

**Comment by madalincm** [comment]
@eviljeff Is there any documentation on the API. I would need some information on how the submission works via the API.

**Comment by eviljeff** [comment]
easiest solution is to use `jpm sign` with an sdk addon https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign

something like:
`jpm sign --api-key <issuer> --api-secret <secret> --xpi <xpi file> --api-url-prefix=https://addons-dev.allizom.org/api/v3`
`<issuer>` and `<secret>` from https://addons-dev.allizom.org/en-US/developers/addon/api/key/

**Comment by jvillalobos** [comment]
@eviljeff will there be a migration to fix the add-ons affected by this? They're up to 500 now, and will probably double/triple by the time this is out.

**Comment by eviljeff** [comment]
> will there be a migration to fix the add-ons affected by this? They're up to 500 now, and will probably double/triple by the time this is out.

#3211 will fix them

**Comment by madalincm** [comment]
I have tried submissions from both dev-hub and API and the add-ons have the status public:
API: 
![apisubmission](https://cloud.githubusercontent.com/assets/15685441/18089760/383a78d0-6eca-11e6-981d-aa39bdcbfb92.png)

DevHub:
![devhubsubmission](https://cloud.githubusercontent.com/assets/15685441/18089782/454347d2-6eca-11e6-9ea0-80f230d9f70e.png)

Should we test anything else in here?

**Comment by eviljeff** [comment]
looks good to me

**Comment by madalincm** [comment]
Marking as verified fixed.
