### ISSUE TITLE
Limit who can upload a WebExtension Experiment

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3315]
We've done this for telemetry experiements, so this should be a simple copy and paste of that code, tweak a few things.

Basically for WebExtensions Experiements, we added in a new add-on type: 256. We'll need to support that on AMO and then we'll need to limit it down so only users in a particular group can do it. Again, this should be similar to what we did for Telemetry Experiments.

**Comment by andymckay** [comment]
Could you take a look at this please? Hoping to get an add-on ready to upload in the next couple of weeks.

**Comment by diox** [comment]
@andymckay I can build on the existing code, sure, but where is `type` supposed to be specified in `manifest.json` ?

**Comment by diox** [comment]
Ah, reading https://github.com/aswan/webext-experiment-hello/blob/master/experiment/install.rdf it looks like it's embedded in a regular extension, alright then.

**Comment by diox** [comment]
It's actually 2 separate extensions, and only the old-style one has the special type, the other is a normal web extension. 

I'm going to re-use the same permission as the one used for telemetry experiments.

**Comment by andymckay** [comment]
Can we do a seperate permission please? The Telemetry team is not the same as the WebExtensions team.

**Comment by diox** [comment]
The permission is called `Experiments:submit`, do we really need to make things more complex and add 2 separate permissions for something that will only be used internally for a very limited number of add-ons anyway ?

**Comment by andymckay** [comment]
Suppose not. Thanks.
