### ISSUE TITLE
An install.rdf with duplicate targetApplication causes a 500

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3318]
The attached zip file has a mangled install.rdf (I can't remember where I found it) with two targetApplication entries for Firefox `{ec8030f7-c20a-464f-9b0e-13a3a9e97384}`.  This is causing https://sentry.prod.mozaws.net/operations/olympia-dev/issues/346125/

I can replicate on dev and prod.

[unlisteduploadtest1.zip](https://github.com/mozilla/addons-server/files/432286/unlisteduploadtest1.zip)

**Comment by andymckay** [comment]
Should probably catch this in the validator too.

**Comment by EnTeQuAk** [comment]
I'll following up on this and see how and where to fix this. It'll probably be at least some tests and small fix in AMO to avoid us throwing a 500 error and adding a new validation in the validator.

**Comment by EnTeQuAk** [comment]
Stupid question, does anyone know how firefox behaves with this install.rdf? Meaning, is this maybe supported and that's just a bug in our code?

**Comment by eviljeff** [comment]
Firefox accepts the attached add-on without complaining (there is warning in the console that the duplicate entry is being ignored) - give it a try.

**Comment by diox** [comment]
Forward duping to https://github.com/mozilla/addons-server/issues/5172
