### ISSUE TITLE
Use bulk indexing in compatibility report cron

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3319]
The compatibility report cron generates chunks of 150 documents before indexing in ES... and then indexes them all separately, negating the purpose of the chunking. It should use bulk indexing instead (keeping the chunking: we don't want to send too much data in a single ES call)

**Comment by eviljeff** [comment]
this was in the 2016-09-22 milestone wasn't it?

**Comment by diox** [comment]
Yes. Fixed, thanks.
