### ISSUE TITLE
Remove password hash from the database

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3324]
Once we have removed the migration code and are just using Firefox Accounts, once we've removed all the code around logging in, getting passwords and so on. There's one last step. And that's removing the password hashes out of the database.

What a glorious day that will be.

**Comment by wagnerand** [comment]
@mstriemer isn't this done?

**Comment by mstriemer** [comment]
Password hashes have all been set to the empty string and there is no longer a way to set the password through code.

At some point we may drop the column entirely but there were some strange bugs I couldn't work out so it is just blank for now.
