### ISSUE TITLE
Statistics not reflecting disco pane installs

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3325]
The statistics for emoji cheatsheet show a nice rise due to being on the disco pane, yay!

But if you look at it by source:

https://addons.mozilla.org/en-US/firefox/addon/emoji-cheatsheet/statistics/?last=90

It doesn't seem to show the increase in installs via the disco pane, instead its showing an increase by the details page. If I remember correctly, and I may be completely wrong here, the installs are counted by parsing the URLs requested for install. 

I think a simple way to get those numbers in is to add ?src=... to the URL we use to download the .xpi once a user clicks install. (What ... is might need checking). Does that summary sound right @diox?

**Comment by muffinresearch** [comment]
Looking at services.a.m.o, download links look to have `src=discovery-promo`. Setting that up in the API might be easiest but if that's a pain we could quite easily replace it / add the correct src in addons-frontend.

**Comment by diox** [comment]
Per IRC discussion we are going to do that in addons-frontend instead: https://github.com/mozilla/addons-frontend/issues/966 I've documented the currently supported values for the `src` parameter in #3331.
