### ISSUE TITLE
The legend for the languages pie chart isn't displayed correctly.

### ISSUE THREAD

**Issue by matt-w-github** [mozilla/addons-server#3326]
Steps to reproduce:
1. Load the Stats Dash for an add-on with public statistics in AMO-dev
2. View the legend for the languages pie chart.

Expected results:
The legend is displayed correctly.

Actual results:
The legend is displayed incorrectly.

![languages-legend-bug](https://cloud.githubusercontent.com/assets/1216679/17908437/56ee6f42-6935-11e6-826c-810c045c0f31.png)

**Comment by eviljeff** [comment]
@matthewjwein what's the page url?

**Comment by jvillalobos** [comment]
Related to #2717

**Comment by jvillalobos** [comment]
@matthewjwein ping :)

**Comment by muffinresearch** [comment]
You can see another example of this in the linked bug: https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30

A quick fix will be to update the CSS for `.toplist` to alleviate the space problem.

**Comment by eviljeff** [comment]
Mentor: @muffinresearch 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by lavish205** [comment]
I would like to work on this bug.

**Comment by muffinresearch** [comment]
@lavish205 go for it

**Comment by wagnerand** [comment]
@lavish205 are you still working on this?

**Comment by wagnerand** [comment]
There hasn't been much activity in a while, so we're opening up that bug for everyone.

**Comment by replaceafill** [comment]
Hello.

I've noticed this is [still around in production](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30), and wanted to work on it. However, I found out that the docker dev environment doesn't run the stat task (and confirmed it in the #amo channel).

Is there any way to run the task or populate/fake the stats in the dev environment to get the charts rendered?

**Comment by VishalCR7** [comment]
@muffinresearch can you please review the PR #7295 regarding this issue.

**Comment by ioanarusiczki** [comment]
@VishalCR7 I tried to test this issue for some add-ons with public statistics from AMO dev but none of them display pie-charts. 
Please provide us with the link to the add-on for which this bug was initially logged.
Thank you!

**Comment by VishalCR7** [comment]
@ioanarusiczki I cannot test the changes made my me locally as the statistics tasks were not running hoever i tried the changes through developer tools here https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/?last=30 and it worked absolutelly fine

**Comment by ioanarusiczki** [comment]
@matt-w-github Please provide us with the link to the add-on for which this bug was initially logged on AMO dev. I searched for pie charts but couldn't find any.
Thank you!

**Comment by madalincm** [comment]
Verified in FF57(Win7) in amo-prod

I have verified this issue in production using the changes through developer. I tried for 3 different add-ons:
![adblockplus](https://user-images.githubusercontent.com/15685441/35104322-2ebb210c-fc71-11e7-8c87-11827eb3a068.png)
![easyscreenshots](https://user-images.githubusercontent.com/15685441/35104323-2ee08118-fc71-11e7-8ac2-a9525988a89d.png)
![ublockorigin](https://user-images.githubusercontent.com/15685441/35104325-2f672434-fc71-11e7-91d1-7094e06c2af3.png)

Marking bug as verified fixed.
