### ISSUE TITLE
[Android] "View Mobile Site" is not working from some pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3339]
Steps to reproduce:
1. Load Themes page on Android using AMO-dev
2. Make a blank search
3. Click on "View Mobile Site" link

Expected results:
User is redirected to mobile site.

Actual results:
The link is not working. User is stuck on "desktop" site using a device.

Notes/Issues:
Clicking anything else but the obvious link, user is redirected to mobile site; this is very misleading.
Issue is also reproducing from any other AMO desktop page that is not implemented on mobile.
(_We could make a redirection to mobile homepage at link click, if the page has no correspondent on mobile_)
Verified on FF48(Android 6.0.1). Issue is reproducing on AMO-stage, dev and prod.

**Comment by diox** [comment]
We're going to rework the mobile pages entirely, so let's not work on enhancements like this now.
