### ISSUE TITLE
Add API to allow admins to see flagged add-on reviews

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3345]

**Comment by diox** [comment]
We'll also need to change the serializer for them, presumably. Add `ip_address`, `editorreview`, `flag`, `sandbox`, `client_data`, `deleted` fields.

**Comment by eviljeff** [comment]
I'm clearing this milestone - please add one back when there is a commit that is likely to land.

**Comment by muffinresearch** [comment]
Let's check and see if we can move this to an admin page rather than exposing this as content mixed into the front-end display.

**Comment by muffinresearch** [comment]
@jvillalobos was there a specific use-case for this view on the data, since reviewer tools has some of this data already?

**Comment by jvillalobos** [comment]
We don't need to expose if a review is up for moderation in the user UI, and there's a review moderation tool in the reviewer tools, so I don't think we need a separate admin tool either.

**Comment by diox** [comment]
Closing as wontfix for now then.
