### ISSUE TITLE
'next' url in API results is prefixed 'http://web' in local development environment

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3347]
All other urls in local environment are without prefix or with the correct `http://olympia.dev` site, from `SITE_URL`.  But the ViewSet response, when results are long enough to need pagination, is being prefixed 'http://web', e.g. `"next":"http://web/api/v3/addons/addon/62/versions/73/"`

**Comment by EnTeQuAk** [comment]
I believe this may be because the actual container is called `web` and drf generates the url based on the actual host by calling ``request.build_absolute_uri`` and django doesn't know anything about SITE_URL.

**Comment by eviljeff** [comment]
I guess the options are

1. Set/override the host (for DRF responses).  Somehow.
2. Write custom pagination that returns relative urls or uses SITE_URL
3. Strip off the host in JS before adding it to the page.

**Comment by diox** [comment]
Can we fix that so that the web container is called with the right host ? I'm confused as to why this isn't the case.

**Comment by EnTeQuAk** [comment]
yeah, I started to look into that a bit. Not sure yet why it's called with that host and not the original one. I'm guessing that this is messing up more URLs somewhere and we should generally use `build_absolute_uri` instead of relying on `SITE_URL` whenever possible imho.

**Comment by EnTeQuAk** [comment]
This should be fixed since https://github.com/mozilla/addons-nginx/issues/3 landed and got build once you're re-pulling the `addons/nginx` image.
