### ISSUE TITLE
Missing statistics in production for 24 25 August

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3351]
### Steps to reproduce:
1. Open https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/downloads/?last=365 and observe the last 2 days.

### Expected results:
There are no issues in displaying the statistics.

### Actual results:
Statistics are missing for 24 and 25 august.

### Notes/Issues:
Verified in FF48(Win7) Issue can be reproduced in amo-prod.
Screencast for this issue:
![statisticsdownloads](https://cloud.githubusercontent.com/assets/15685441/17999679/e200a8e4-6b82-11e6-848f-715fa80ba878.png)

**Comment by muffinresearch** [comment]
@jasonthomas is anything up with stats?

**Comment by jasonthomas** [comment]
Thursday aren't processed yet. Those should show up later today. I will need to reindex stats for Aug 24th.

**Comment by wresuolc** [comment]
I'm seeing stats for the 24th and 25th now, fwiw.  Thanks.

**Comment by jasonthomas** [comment]
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1274996 reopened to fix up the current stats monitoring.

**Comment by wresuolc** [comment]
The 26th is now missing

**Comment by jasonthomas** [comment]
Stats are processed late in the day https://github.com/mozilla/addons-server/blob/master/scripts/crontab/crontab.tpl#L56-L59
