### ISSUE TITLE
Compatibility reports page is showing "Search Unavailable"

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3353]
STR:
1) Go to https://addons.mozilla.org/admin/compat

Result: 
Search Unavailable
Search is temporarily unavailable. Please try again in a few minutes.

@diox could this be related to #3010?

**Comment by diox** [comment]
Yes, I forgot to ask for a reindex, sorry about that.

**Comment by diox** [comment]
Appears to be a deeper issue, it persists after a reindex. `Parse Failure [No mapping found for [works.48000000200100.failure_ratio] in order to sort on]`. Not sure what's going on yet, it's using the new index (`addons_prod-20160826184414`) but the mapping is somehow wrong.

**Comment by diox** [comment]
The query that causes the error runs fine locally :(

```
{'sort': [{'works.48000000200100.failure_ratio': 'desc'}, {'works.48000000200100.total': 'desc'}], 'query': {'filtered': {'filter': {'and': [{'range': {'works.48000000200100.failure': {'gt': 10}}}, {'range': {'works.48000000200100.failure_ratio': {'gt': 0.8}}}, {'range': {'support.max': {'gte': 0}}}]}, 'query': {'function_score': {'query': {'match_all': {}}, 'functions': [{'field_value_factor': {'field': 'boost', 'missing': 1.0}}]}}}}, 'size': 20}
```

Maybe there is something wrong with the indexing process. I'll need to see what's in the index in prod.

**Comment by diox** [comment]
Co-assigning jason because I need his help getting me a ES mirror of prod to figure out what's wrong.

**Comment by jasonthomas** [comment]
The mirror is up and I've sent you a email with details on how to access it.

**Comment by diox** [comment]
The mirror shows that the `compat` mapping is empty, and there are no documents of this type. Which is... unexpected. And bad. Nothing in sentry, nothing weird in kibana that I can see. We see the compatibility cron being executed, but sadly it does not log anything else.

**Comment by diox** [comment]
Making progress, jason got the following traceback running the command manually:
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/data/olympia/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/data/olympia/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/olympia/venv/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/data/olympia/venv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/data/olympia/venv/lib/python2.7/site-packages/cronjobs/management/commands/cron.py", line 64, in handle
    registered[script](*args)
  File "/data/olympia/src/olympia/compat/cron.py", line 109, in compatibility_report
    if compat_doc['support']['max'] >= version]
KeyError: 'support'
```

**Comment by diox** [comment]
That PR did fix it 3 weeks ago :)
