### ISSUE TITLE
 Don't add "restart required" to language packs

### ISSUE THREAD

**Issue by nohamelin** [mozilla/addons-server#3354]
Same as #3307; check it with any langpack from:
https://addons.mozilla.org/en-US/firefox/language-tools/

**Comment by diox** [comment]
Ah, I thought they did require a restart. I'll change that.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7 x64)
Issue was fixed for lang-packs and dictionaries with type=8/64
Postfix screenshots: 
![langpack](https://cloud.githubusercontent.com/assets/15685960/18092888/b7ff936e-6ed6-11e6-9a3c-2eb714dd331c.png)
![no8-64](https://cloud.githubusercontent.com/assets/15685960/18092889/b80560be-6ed6-11e6-801b-f08087d628ec.png)
