### ISSUE TITLE
Use alphabetical order for platform identifiers in per-version addon downloads

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3358]
*originally posted to https://github.com/mozilla/addons-frontend/issues/996 by @polyzen*

https://addons.mozilla.org/firefox/downloads/file/492123/ublock_origin-1.9.2-fx+sm+tb+an.xpi

The order of the "platform identifiers" change every release. If you remove anything from the last slash onward, it downloads the latest version.

Many addons are packaged for global installation in Arch Linux (eg. see here). If we source from AMO, we have to match the new, random order every release, which is quite monotonous.

If they could be made to follow alphabetical (or any) order going forward, that would be extremely appreciated.

Edit: Well, apparently not [every](https://addons.mozilla.org/firefox/downloads/file/492500/ublock_origin-1.9.4-fx+sm+tb+an.xpi?src=version-history) release.

**Comment by polyzen** [comment]
(eg. see [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firefox-ublock-origin))*

Thank you again.

**Comment by andymckay** [comment]
Should just be a matter of putting a sort in here: https://github.com/mozilla/addons-server/blob/f5a68aa5008cd8d2cb5ab7d285ff66309e2a8950/src/olympia/files/models.py#L254

**Comment by wagnerand** [comment]
Mentor: @kumar303 

Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by Prashant-Surya** [comment]
Can I work on this issue?

**Comment by wagnerand** [comment]
You don't need to ask for permission. You can start right away and submit a PR or ask questions here if anything is unclear. :)

**Comment by lavish205** [comment]
@Prashant-Surya are you working on this bug? or should I create new PR?

**Comment by Prashant-Surya** [comment]
@lavish205 I'm working on this

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
Postfix screenshots:
![2016-10-06_0937](https://cloud.githubusercontent.com/assets/15685960/19142759/940c6b78-8ba8-11e6-8cd5-f71b955244f3.png)

@Prashant-Surya : is this the correct place I should check for fixing the alphabetical platform order?
Hope so. :)

**Comment by Prashant-Surya** [comment]
@ValentinaPC I think it is correct place.

**Comment by polyzen** [comment]
The code has been in use since the merge? These beta releases since then don't have the identifiers (fx+sm+..) sorted:

https://addons.mozilla.org/firefox/downloads/file/516024/ublock_origin-1.9.15b0-tb+an+fx+sm.xpi?src=version-history
https://addons.mozilla.org/firefox/downloads/file/517173/ublock_origin-1.9.15b1-sm+an+tb+fx.xpi?src=version-history

**Comment by diox** [comment]
It missed the tag by a day, so no, it hasn't been deployed to prod yet, only dev. It will land on prod next Thursday around noon PST.
