### ISSUE TITLE
Remove categories in the db depending on old applications like Sunbird

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3360]
AMO has somewhat hidden support for some applications it considers as deprecated. These includes:
- Sunbird (`{718e30fb-e89b-41dd-9da7-e25a45638b28}`), which you can't submit new add-ons for
- Mozilla (Seamonkey) (`{86c18b42-e466-45a9-ae7a-9b95ba6f5640}`), which you can't submit new add-ons for
- Fennec (`{a23983c0-fd0e-11dc-95ff-0800200c9a66}`), which is a bit of an outlier in this list, it appears to be still available at submission - not sure if that's intended.

When I moved categories to static constants in #2923 I didn't care about those, but the result is that it's polluting our logs with messages about unknown categories. I'll remove the log message, but we should consider removing the categories (and the links between add-ons and those categories) or even maybe the `AppSupport`, `AppVersion` and `ApplicationsVersions` instances depending on those deprecated applications.

**Comment by diox** [comment]
@jvillalobos : any reason to keep references in our code to those applications ? Could we clean up our database from them ?

**Comment by jvillalobos** [comment]
I think it's okay to clean up those applications from the DB, though it's probably lots of hairy code touching submission and possibly validation.

**Comment by eviljeff** [comment]
I think we can just dupe this to #5981 - the obsolete categories will go away when we drop the `Category` model
