### ISSUE TITLE
Send user to FxA log in when clicking sign in

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3368]
Send the user's preferred action to FxA based on the link they click.

**Comment by ValentinaPC** [comment]
Please add some STR for us to verify this. Thanks!

**Comment by mstriemer** [comment]
These need to be done in private browsing to ensure that Firefox Accounts isn't detecting whether you need to create or log in.

Log in (in private browsing):

1. Click "Log in"
2. Verify that you are on the Firefox Accounts log in page

Register (in private browsing):

1. Click "Register"
2. Verify that you are on the Firefox Accounts register page

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2 (Win 7 x64)
Postfix video: 
![private](https://cloud.githubusercontent.com/assets/15685960/18138224/67502c24-6fb4-11e6-8eff-37e8b3c91274.gif)

@mstriemer : there are other places in AMO that don't redirect directly to FxA page, is this ok?
e.g. 
![theme](https://cloud.githubusercontent.com/assets/15685960/18138339/e7219e24-6fb4-11e6-853d-57db051a9d72.gif)

**Comment by krupa** [comment]
reopened to address the above comment.

**Comment by ValentinaPC** [comment]
Please take in consideration that above comment was just an example and is happening also after deleting an account.
Video: 
![delete account](https://cloud.githubusercontent.com/assets/15685960/18158094/a9c0350c-7029-11e6-8de4-de54756a6e2d.gif)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48(Win 7).
Postfix videos:
![theme](https://cloud.githubusercontent.com/assets/15685960/18195896/f2b0b4f8-70f6-11e6-876f-5c46cd6f307e.gif)
![delete](https://cloud.githubusercontent.com/assets/15685960/18195904/f8b45ecc-70f6-11e6-9475-ed7f31f918b0.gif)
