### ISSUE TITLE
500 Error: keyError trying to go to django admin (admin/models)

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3371]
See https://sentry.prod.mozaws.net/operations/olympia-dev/issues/347020/

Happens locally and on -dev. Looks to be related to an admin template.

**Comment by madalincm** [comment]
Verified as fixed in FF48(Win7) in addons-dev.allizom.org
Postfix screencast: 
![adminmodel](https://cloud.githubusercontent.com/assets/15685441/18159494/b144b322-7031-11e6-8e54-5388a7377593.png)
