### ISSUE TITLE
500 error caused by locals at webextension submission

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#3375]
**Steps to reproduce:**
Try to submit the attached webextension:
[Any.do-Extension_v3.1.3.22.zip](https://github.com/mozilla/addons-server/files/447548/Any.do-Extension_v3.1.3.22.zip)

**Expected results:**
The webextension is successfully submitted.

**Actual results:**
Server error is returned and the oops message is displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 51.0a1 (2016-08-31) under Windows 10 64-bit.
- I suspect that this issue is caused by the “x” character from locales folders name because the error is no longer displayed if I removed the “x_”. 
- Please see the attached video:
![gif](https://cloud.githubusercontent.com/assets/18114210/18133619/008788a8-6fa4-11e6-81e7-68bfa151ccaa.gif)

**Comment by eviljeff** [comment]
I'm clearing this milestone - please add one back when there is a commit that is likely to land.

**Comment by vasilicamihasca** [comment]
Verified fixed on AMO-dev using Firefox 51.0a1 (2016-09-14) under Windows 10 64-bit. The webextension was successfully submitted.
![2016-09-14_1828](https://cloud.githubusercontent.com/assets/18114210/18518594/4b246b46-7aa9-11e6-929e-7c3618847610.png)
