### ISSUE TITLE
Typo: "Addon visibility" should be "Add-on visibility" in Status & Versions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3379]
In the Status & Versions page of an add-on's developer pages, the word add-on is misspelled.
<img width="311" alt="addon" src="https://cloud.githubusercontent.com/assets/62568/18148882/bff2ef08-6f99-11e6-8ce4-38255006abfa.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![visibility](https://cloud.githubusercontent.com/assets/1583842/18165709/85e72fb6-704f-11e6-986d-41765192de55.png)
