### ISSUE TITLE
Remove old review process reference from add-on submission checklist

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3380]
When an add-on is submitted for validation, a "submission checklist" is shown:
<img width="700" alt="submission-checklist" src="https://cloud.githubusercontent.com/assets/62568/18148967/6753edf6-6f9a-11e6-902e-9a82f16f298b.png">
There are two things there that are no longer relevant:
* "If your add-on is intended for a limited audience you should choose Preliminary Review instead of Full Review." The Experimental status is the replacement for Preliminary Review, but I don't think we should encourage it. Let's just remove this line.
* The link with the text "If you are unfamiliar with the add-ons review process". That blog post is very outdated, and hopefully the review process is now simple enough that it doesn't need additional explanation.

**Comment by vcarciu** [comment]
Verified as fixed : 
![submission](https://cloud.githubusercontent.com/assets/1583842/18157380/c32de088-7025-11e6-87ff-2993e80c3f25.png)
