### ISSUE TITLE
Don't show submission checklist on first submission

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3381]
I filed #3380 to remove a couple of lines from the submission checklist. After looking at the remaining points, I see they're not relevant for first submissions, because the first submission flow doesn't include adding notes to reviewer or version notes. Even if we add those fields to the submission flow, we should highlight their importance when they are shown, and not in the validation step.

Let's remove the checklist entire, keeping only the link to see the full validation report.

**Comment by eviljeff** [comment]
is this still valid?

**Comment by jvillalobos** [comment]
I don't think so? Either way, we're making some changes to the submission flow with the post-review work, so this will change anyway.
