### ISSUE TITLE
Redundant links in Themes categories pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3384]
Steps to reproduce:
1. Load any theme category i.e. https://addons.allizom.org/en-US/firefox/themes/scenery
2. Hover over the "Up & Coming Themes" title 

Expected results:
The title is not a link.

Actual results:
Both "Up & Coming Themes" and "View All Up & Coming" are links, redirecting the user to the same page.

Notes/Issues:
Same thing happening for "Recently Added" and "View all Recently Added", etc. from themes categories.
Verified on FF48 (Win 7). Reproducing around all AMO servers.
Screenshot: 
![2016-09-01_1053](https://cloud.githubusercontent.com/assets/15685960/18159699/9316a6c0-7032-11e6-9708-95d4cea91f2f.png)

**Comment by muffinresearch** [comment]
Since this is very minor I don't think there's a need to fix this here since we're already working on a new version of the public pages.
