### ISSUE TITLE
No error description in validation report

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#3385]
**Steps to reproduce:**
Try to submit the attached webextension:
[GamingWonderland_v12.41.9.65484.zip](https://github.com/mozilla/addons-server/files/449082/GamingWonderland_v12.41.9.65484.zip)

**Expected results:**
A detailed error description is displayed in validation report.

**Actual results:**
The submission fails with “Your JSON is not valid” error but there is no description in validation report.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 51.0a1 (2016-08-31) under Windows 10 64-bit.
- Please see the attached screenshot:
![2016-09-01_1055](https://cloud.githubusercontent.com/assets/18114210/18159720/aa0b7284-7032-11e6-86b6-b27706ae8288.png)

**Comment by EnTeQuAk** [comment]
I believe this is the best we can do but you're right, especially the "Error: ()" looks empty, let's see if we can improve the error message a bit and give a few more details.

**Comment by andymckay** [comment]
Ha its on `test/invalid.json`. Guess its working correctly.

**Comment by EnTeQuAk** [comment]
QA: This is now on -dev and -stage and will go live on Thursday.

**Comment by vasilicamihasca** [comment]
Verified fixed on AMO-dev using Firefox 52.0a1 (2016-10-12). The error is successfully detailed in validation report. Postfix screenshot:
![2016-10-13_1209](https://cloud.githubusercontent.com/assets/18114210/19343354/974f29f6-913e-11e6-9544-7677d20aaeb8.png)
