### ISSUE TITLE
Invisible author name if user `display_name` has non-printable characters

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3388]
If the `display_name` of a user is empty (for example https://addons.mozilla.org/en-US/firefox/user/exeguard/), add-ons having that user as the author will show up with an empty author (for example https://addons.mozilla.org/en-US/firefox/addon/exeguard/)

![screen shot 2016-09-01 at 19 01 07](https://cloud.githubusercontent.com/assets/873258/18176590/80d995a0-7076-11e6-91d6-6dcb17eb68ca.png)

Note that the link is technically there, it just has an empty text:

![screen shot 2016-09-01 at 19 02 09](https://cloud.githubusercontent.com/assets/873258/18176624/a66f1380-7076-11e6-9e2d-a312278c9fc3.png)

**Comment by atiqueahmedziad** [comment]
@wagnerand what should be the expected behaviour in [addon page](https://addons.mozilla.org/en-US/firefox/addon/exeguard/) for empty `display_name`?  
Should the `author` remain hidden then? OR Should username replaces as titile in addon page ?

**Comment by wagnerand** [comment]
That needs be to decided.

If we use the `display_name` in prominent places like this, I suppose we should make it mandatory (which is probably not possible, not that we are using FxA) or have it at least default to something reasonable, like the `username`.

**Comment by jvillalobos** [comment]
I think the behavior in other places on AMO is to show the `display_name`, and if there is none, use the `username` instead.

**Comment by ValentinaPC** [comment]
I remember this. #3280

**Comment by wagnerand** [comment]
So, the issue here is that the `display_name` is set, but it's set to non-printable characters. There are several thousands of users that did that.

**Comment by wagnerand** [comment]
@EnTeQuAk has some ideas on what we could do (like ` unicoddata.normalize('NFKD').encode('ascii', 'ignore')`), but we need to decide first, what we actually want to support and how we are going to migrate effected users.

**Comment by wagnerand** [comment]
Marking this as "needs more triage" so we can talk about it in the next standup.

**Comment by muffinresearch** [comment]
From the meeting last week, short-term we could look to not show the "By [INVISIBLE]" string if we know the string is nothing but invisible characters. 

Longer term as per https://github.com/mozilla/addons-server/issues/3388#issuecomment-272895582 we should work out if we want to enforce author names to be something non-invisible and how to fix the existing data in that state.

**Comment by diox** [comment]
@wagnerand did https://github.com/mozilla/addons-server/issues/10266 fix this ?

**Comment by wagnerand** [comment]
The original issue was about empty `display_name`, which was specific to the old frontend.

I don't know of an example of non-printable characters. @AlexandraMoga would you have time to create a user account consisting of only non-printable characters, submit an add-on and see if the add-on page and the user profile page shows a meaningful user name?

**Comment by AlexandraMoga** [comment]
@wagnerand I think that the above scenario is not possible anymore.

I've tried to set a `display_name` of only non-printable characters - for example `\u00A0 \r\n \u200b \uFEFF \t` - through the PATCH account api but since #10266 this is not allowed.

Trying to set the same name in the frontend or through users admin will simply render those characters as plain text (which is an expected behavior).

Furthermore, purely empty `display_names` - something you can set in users admin - will just fallback to the default value assigned by AMO - i.e `Firefox user <userId>`

**Comment by wagnerand** [comment]
Great, thank you for testing! Let's close this.
