### ISSUE TITLE
Email developers about status changes from #3087

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3390]
The migration in #3087 will change the status of lots of add-ons, and we should tell developers about it. After looking into other options, we decided using the /admin tool would be best.

We want to notify all developers who had their add-on status changed. If an add-on only has some its files change status, but not the add-on status, there's no need to notify the dev.

I'll write the template on [this etherpad](https://public.etherpad-mozilla.org/p/prelim-removal-email).

**Comment by jvillalobos** [comment]
This should only be sent in the case of listed add-ons.

**Comment by eviljeff** [comment]
QA: you're only going to be able to check this after the migration is run, so it will work on -dev, but on stage the migration has yet to be run.

https://.../en-US/admin/email-devs will show the option to email affected preliminary reviewed add-on developers, which should be developers of add-ons in https://.../en-US/admin/models/devhub/activitylog/?action__exact=139 that have "email": "true" in the details (no way to filter the list to show just those add-ons)
