### ISSUE TITLE
layout of review history in status & versions is broken by some review content

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3392]
Long lines of review content are causing the layout to break when 'show review history' is clicked and the review content is loaded in-line.

**Comment by madalincm** [comment]
Verified in FF48(Win7) in addons-dev.allizom.org and addons.allizom.org Issue is still reproducing
Screencast for the issue:
![reviewhistorybug](https://cloud.githubusercontent.com/assets/15685441/18304831/51b2da4a-74ed-11e6-9677-5afd07b91356.gif)

Reopening.

**Comment by madalincm** [comment]
Reproducing in both dev and editor tools:
![reviewhistory](https://cloud.githubusercontent.com/assets/15685441/18340743/576371da-75af-11e6-88fa-8fb3c8c4c706.png)

I think we should fix this in both places. Thanks

**Comment by eviljeff** [comment]
can you file a separate issue for editor tools? - it's always been broken :)

**Comment by madalincm** [comment]
done: #3447

**Comment by madalincm** [comment]
Verified as fixed in FF48(Win7) in addons-dev.allizom.org
Postfix screencast: 
![3392fix](https://cloud.githubusercontent.com/assets/15685441/18353615/57b910f4-75eb-11e6-9a64-6d2e8fa00ba6.png)
