### ISSUE TITLE
Super creation failing in functional tests

### ISSUE THREAD

**Issue by davehunt** [mozilla/addons-server#3398]
The [super creation](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#super-creation) API endpoint is no longer working in our functional tests. On dev we get a 500 response:

> HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://addons-dev.allizom.org/api/v3/accounts/super-create/

I tried checking the JWT issuer and secret, but when attempting to open https://addons-dev.allizom.org/en-US/developers/addon/api/key/ I get "Oops! We had an error. We'll get to fixing that soon."

![screenshot 2016-09-02 12 56 11](https://cloud.githubusercontent.com/assets/122800/18203129/c1b6ec80-710c-11e6-951f-b0fbbffe51db.png)

**Comment by diox** [comment]
Sentry tracebacks: 
- https://sentry.prod.mozaws.net/operations/olympia-dev/issues/347134/
- https://sentry.prod.mozaws.net/operations/olympia-dev/issues/347504/

A deploy issue perhaps ? Or because of the django 1.8 merge ?

**Comment by davehunt** [comment]
If it helps we first saw these failures [in this build](https://webqa-ci.mozilla.com/view/AMO/job/amo.dev/911/) which ran Aug 31, 2016 7:54:00 PM (PDT).

**Comment by muffinresearch** [comment]
Fwiw: Django 1.8 merge landed on 31st at 07:43 BST / 06:43 UTC [1]

[1]  https://github.com/mozilla/addons-server/pull/3168

**Comment by muffinresearch** [comment]
According to an update in irc the containerized olympia web was available on -dev on the 1st Sept at 01:27 BST / 00:27 UTC

**Comment by EnTeQuAk** [comment]
Hmm, I can't think how this would be related to django 1.8 to be honest, `django-aesfield` looks fine to me, and the path is entirely configured in the settings.

**Comment by bqbn** [comment]
The sentry error is due to a missing directory bind mount when starting the container. I've merged a fix (https://github.com/mozilla-services/puppet-config/pull/2248) in our puppet-config, and next push should pick it up. 

Also for my information, can someone tell me if "/data/aeskeys/api_key_secret.key" is only used by olympia web at this point? because the services web component has been containerized for more than a week by now on both -dev and -stage, and no one seems to have complained about the same error.

**Comment by EnTeQuAk** [comment]
@bqbn yes, that file is only being used by olympia and only for our APIs that use JWT authentication. the services component is super minimal and re-uses only a very minimal amount of code currently.

**Comment by bqbn** [comment]
@EnTeQuAk thanks for the explanation.

I believe the issue has been resolved after the above mentioned merge. Let me know if that's not the case.
