### ISSUE TITLE
Blocklist isn't updating with new blocks

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3405]
After adding a new [block](https://addons.mozilla.org/en-US/admin/models/blocklist/blocklistdetail/1267/) it's not appearing in the blocklist xml file (the source used for non-Nightly Firefox releases), nor the list on  https://addons.mozilla.org/en-US/firefox/blocked/ (should be [this](https://addons.mozilla.org/en-US/firefox/blocked/i1267)).  
The XML has an hour cache; the list page shouldn't be cached at all.

**Comment by EnTeQuAk** [comment]
And it's only visible in the JSON export for now which reuses a lot of the code that is used on the page and XML export.

**Comment by eviljeff** [comment]
Looks like was due to an existing block with the same guid and some shakey code that combines the two in unpredictable ways.

**Comment by eviljeff** [comment]
actually, I'm going to close this as the kinto based blocklist is going to replace the AMO one real-soon-now.

**Comment by Natim** [comment]
Well actually it adds problems for Kinto synchronization.

**Comment by Natim** [comment]
It thought there were a mecanism to invalidate the cache in case we changed the blocklists?

**Comment by eviljeff** [comment]
it wasn't caching, the new block was being combined into an existing block for that guid.

**Comment by Natim** [comment]
@eviljeff It seems you nailed down the problem, if you could write a test to reproduce the error I would be willing to write a fix for it.

**Comment by eviljeff** [comment]
it can be reproduced trivially on -dev by adding two blocklist details entries for the same guid, but with different max or min blocking versions.  The resulting xml will intermittently either have a block for the first block-id, with two entries inside for the two version ranges, or a block for the second block-id.

I'm not sure what the actual fix is - it depends on what Firefox will accept (it's quite possible only have a single block-id per guid is correct and a block for each would be an error)

**Comment by Natim** [comment]
The thing is we are having the issue on a certificate in stage and certificate don't have guid :s

**Comment by eviljeff** [comment]
it's not connected then.  please open a new issue.

**Comment by Natim** [comment]
Yes sure will do.

**Comment by Natim** [comment]
I did there: #3518
