### ISSUE TITLE
stats job failed on Aug 31

### ISSUE THREAD

**Issue by wresuolc** [mozilla/addons-server#3406]
Stats for Aug 31 are zeroed out still.  /cc @jasonthomas  <3 😻

**Comment by jasonthomas** [comment]
I filed a bug earlier today with IT https://bugzilla.mozilla.org/show_bug.cgi?id=1300125.

**Comment by CharlieSuth** [comment]
Everywhere AMO has 0 user add-ons filled.  Fix it quick por favor.

**Comment by jasonthomas** [comment]
Stats backfill is currently in progress. It will take a few more hours for it to be completed.

**Comment by jasonthomas** [comment]
Stats backfill is now completed.
