### ISSUE TITLE
[fx50] Show compatibility error if an add-on uses draggesture or dragdrop

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3407]
As explained in [bug 1162050](https://bugzilla.mozilla.org/show_bug.cgi?id=1162050), the `draggesture` and `dragdrop` events were removed. All instances of these events should be flagged. Note this means we should also flag `ondraggesture` and `ondragdrop`.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The draggesture and dragdrop events are no longer supported. You should use the standard equivalents instead: dragstart and drop. For more information, please refer to [this documentation](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API).

Affected add-on: https://addons.mozilla.org/addon/foxclocks/

Release timing: Firefox 50 will be released on November 8th.

**Comment by EnTeQuAk** [comment]
Something like that sounds quite reasonable, let's try and see how that goes.

**Comment by wagnerand** [comment]
I tested that add-on against our index of all add-on code to make sure the amount of false positives is minimal. I'm ok with using a different regexp but we should test than one as well.

**Comment by madalincm** [comment]
I tried to upload the specified add-on in addons-dev but I can't see a warning at validation regarding the use of draggesture or dragdrop.
I have also installed the add-on in latest nightly and it works as expected.

I have 2 questions @EnTeQuAk :
1. Was in the scope of this bug to add a message in the validator regarding the use of draggesture and dragdrop.   Should I see a warning when I upload the add-on mentioned in the first comment.
2. Is there any other way we can test this except installing and using that add-on?

**Comment by EnTeQuAk** [comment]
The problem with the add-on that was uploaded is that it's current `maxVersion` in the `install.rdf` is set to `47.*` - if you change that to `50.*` the warning will show up properly.

> 1. Was in the scope of this bug to add a message in the validator regarding the use of draggesture and dragdrop. Should I see a warning when I upload the add-on mentioned in the first comment.

Yes, you should see the message if you're add-on uses these events and targets Firefox 50.

>  2. Is there any other way we can test this except installing and using that add-on?

The only way to test this is to upload an add-on that targets Firefox 50 and see if the warning occurs.

**Comment by madalincm** [comment]
I have changed the max version to 50.* and now the warning is shown:
![draggesture](https://cloud.githubusercontent.com/assets/15685441/18347767/1b346be4-75d0-11e6-82d3-260a9430e5dc.png)
Also waiting for @wagnerand response in the other bug and after that we can mark the bug as verified fixed.

**Comment by wagnerand** [comment]
Looks good! Thank you for testing!
