### ISSUE TITLE
[fx50] Show compatibility error if an add-on uses getUsagesArray, requestUsagesArrayAsync, or getUsagesString

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3408]
As explained in [bug 1284946](https://bugzilla.mozilla.org/show_bug.cgi?id=1284946), `getUsagesArray`, `requestUsagesArrayAsync`, and `getUsagesString` were removed from `nsIX509Cert`. All instances of these methods should be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The methods getUsagesArray, requestUsagesArrayAsync, and getUsagesString are no longer supported. For more information, please refer to [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1284946).

Affected add-on: https://addons.mozilla.org/addon/cert-viewer-plus/

Release timing: Firefox 50 will be released on November 8th.

**Comment by madalincm** [comment]
When validation in addons-dev.allizom the specified add-on the validation warning is displayed correctly:
![getusagesarray](https://cloud.githubusercontent.com/assets/15685441/18344727/150784d6-75c1-11e6-8c0e-8b7f27d3a5db.png)

@EnTeQuAk Is there any other way we can test this except installing and using that add-on?

**Comment by EnTeQuAk** [comment]
Oh I'm sorry, I forgot to add qa information to this bug (note to myself…)

This is only relevant for the bulk validation process that bumps the add-on versions in case they're compatible. @wagnerand can elaborate a bit more and he's probably the one testing this with the next batch run today or tomorrow.

**Comment by EnTeQuAk** [comment]
So, to actually answer your question: You can only test this by uploading an add-on to AMO, that's the only place where we show the actual warning.

**Comment by madalincm** [comment]
The warning is displayed so I think we are ok. We will wait for @wagnerand  response before marking this as verified as fixed.

**Comment by wagnerand** [comment]
Looks good to me.
