### ISSUE TITLE
Add an experimental flag in Editor Tools

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3412]
Steps to reproduce:
1. Sign in to AMO-dev https://addons-dev.allizom.org/en-US/firefox/
2. Submit an experimental add-on/webext
3. Go to Editor Tools to approve it

Expected results:
There is a experimental flag available in queue and review pages.

Actual results:
There is no difference between a exprimental or normal add-on.

Note/Issues:
Verified on FF48(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshots for this issue:
![dev_hub](https://cloud.githubusercontent.com/assets/15685960/18251294/0ca3888a-7391-11e6-989e-338dde9a7a9b.png)
![queue](https://cloud.githubusercontent.com/assets/15685960/18251297/1314dd54-7391-11e6-88d0-b795ec27267d.png)
![review_page](https://cloud.githubusercontent.com/assets/15685960/18251302/1977f8e8-7391-11e6-9b66-8bfb030d6282.png)

**Comment by wagnerand** [comment]
As the _experimental_ flag does not really influence the review at all, I'm not sure how much value this would have.

**Comment by ValentinaPC** [comment]
Maybe, just to know, as a reviewer, what kind of add-on it's going to be reviewed and how much attention needs.

**Comment by wagnerand** [comment]
The _experimental_ flag is totally different from what we used to have with _preliminary_. The same review policies apply for both _experimental_ and _non-experimental_ add-ons.

**Comment by EnTeQuAk** [comment]
Based on the fact that there isn't anything review-related I'm going to close this. We can always add new information as a flag under `Flags` if there's an actual need for it.
