### ISSUE TITLE
Theme user counts broken since Aug 31

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#3427]
Background themes uploaded from Aug 31 onward show 0 users.
https://addons.mozilla.org/firefox/themes/?sort=created

**Comment by MaDonnasPersonas** [comment]
Thanks, Amy.

**Comment by andymckay** [comment]
Duplicate of #3406.

**Comment by MaDonnasPersonas** [comment]
Has this problem been closed or am I reading this wrong? Because there is still no user count since Aug. 31st.

**Comment by atsay** [comment]
It was closed because it was a duplicate of issue [3406](https://github.com/mozilla/addons-server/issues/3406)--it's not resolved yet but we're working on it!
