### ISSUE TITLE
Upgrade django-csp

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3434]
* Upgrade django-csp
* Use the `child-src`, `base-uri` and `form-action` directives.

## Qa notes for testing this:

1. Make a request and look at the CSP headers:
    * `child-src` settings should match the same values for `frame-src`
    * `form-action` should be present and set to `'self'` and `https://developer.mozilla.org`
    * `base-uri` should be present and set to `'self'` and the relevant host for the server you are on.
2. Change the markup  and look for CSP errors.
   * Modify the action attribute of a form (e.g. search) to a different site and you'll see a CSP error if you submit the search relating to violation of the `form-action` directive.
   * Add a `<base>` element with an `href` attribute pointing to a different site and you'll see a CSP error relating to violation of the `base-uri` directive.
3. The base-uri should still work on services.a.m.o (for the legacy discovery pane) - please check there's no issues here with links out to AMO.
4. The only other special search action is the devhub search which points to MDN, this should still work without errors.

Known issues: 

You may see CSP violations re: `about`. This is caused by addons that block requests by pointing them to `about:blank`.

**Comment by muffinresearch** [comment]
Note: This should also be validated post-relase in production too.

**Comment by madalincm** [comment]
Verified in FF48 and FF51 in addons-dev.allizom.org
1. Everything is in place.
2. Everything is working as expected. When following the steps in there I receive the following CSP warnings:
i. Content Security Policy: The page's settings blocked the loading of a resource at https://google.com/ ("form-action https://addons-dev.allizom.org https://developer.mozilla.org").
ii. Content Security Policy: The page’s settings blocked the loading of a resource at http://www.w3schools.com/images/ (“base-uri https://addons-dev.allizom.org https://addons.mozilla.org https://addons-dev.allizom.org”).
4. The search in dev hub works with no issues.

I have not completely understand 3. I have looked around and there is nothing strange going on, no csp errors are being displayed. Can you detail a bit on what should be done on 3? @muffinresearch

**Comment by muffinresearch** [comment]
@madalincm for `3` if you go to https://services.addons-dev.allizom.org/en-US/firefox/discovery/pane/pane/46.0/strict etc directly the links should still work and should point to `https://addons-dev.allizom.org`. The reason base-uri comes into play is because the`base` element href is set to point to `https://addons-dev.allizom.org` (on -dev) (or instead of `services.addons-dev.allizom.org`.

Note: this only applies to relative links without an explicitly defined origin e.g some links do explicitly point to `services....`

**Comment by madalincm** [comment]
Everything looks good except one thing. When opening https://services.addons-dev.allizom.org/en-US/firefox/discovery/pane/pane/46.0/strict I can see this:
![cspdiscopane](https://cloud.githubusercontent.com/assets/15685441/18356118/212c66a4-75f4-11e6-806b-6de7e063a600.png)

This only happens in 48 (that error is not displayed in nightly). So I think is related to #3440 
What do you think @muffinresearch

**Comment by muffinresearch** [comment]
@madalincm yep that's #3440

**Comment by madalincm** [comment]
I have checked in production and I can see that child-src, form-action and base-uri is not present in production.
Was this fix pushed to production?

**Comment by muffinresearch** [comment]
@madalincm not yet - see the milestone date it's due for release next week.

**Comment by madalincm** [comment]
Verified in FF48
I have checked again production and when I tried the steps from point 2 I haven't seen any errors.  The child-src, form-action and base-uri are all good but no errors are displayed in the console.
The same when I checked in -dev. 

@muffinresearch  Did something change, is this the new expected behavior?

**Comment by muffinresearch** [comment]
@madalincm I see the following when manipulating a form action and adding a base element as per the step 2 in https://github.com/mozilla/addons-server/issues/3434#issue-175500340

![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/18671378/c116e8ce-7f3b-11e6-90bb-d91566aa0b7c.png)
