### ISSUE TITLE
"Works with..." message is not entirely displayed in "Required add-ons" section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3437]
Steps to reproduce:
1. Load this page https://addons.allizom.org/en-US/firefox/addon/test-%C5%9Fcoal%C4%83-_/
2. Hover over the second add-on from "Required add-ons" section

Expected results:
There are no display or layout issues.

Actual results:
The text inside the "Works with..." box is not entirely visible.

Notes/Issues:
Verified on FF48(Win 7). Reproducing on AMO-stage and dev.
Screenshots:
![required_add-on](https://cloud.githubusercontent.com/assets/15685960/18319627/2feccb68-752f-11e6-8880-4c2b181ee2f2.png)

**Comment by ValentinaPC** [comment]
@tsl143 : maybe you can fix this too if still on it and are related :smile: 
![coll1](https://cloud.githubusercontent.com/assets/15685960/18505990/89915a74-7a72-11e6-8ea2-ce3f260906a9.png)
![coll2](https://cloud.githubusercontent.com/assets/15685960/18505995/8e8a088c-7a72-11e6-968f-910e412fe5db.png)

**Comment by tofumatt** [comment]
Closed in #3475

**Comment by ValentinaPC** [comment]
@tofumatt I sow the initial fix, but I thought the issues from my second comment, can be fixed together with first one. :)

**Comment by tsl143** [comment]
@ValentinaPC , will it be fine to file another issue linking with this issue?
