### ISSUE TITLE
Stop using 'Admin:%' in API permission checks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3438]
There are one or two places in the API where we depend on 'Admin:%' permission, and we should try to get rid of it for a more specific permission instead.

**Comment by diox** [comment]
@wagnerand what permission should be used to see deleted add-ons in the API ? I'm currently restricting it to users with `Admin:%` (+ a special query parameter indicating that they want to see deleted add-ons).

**Comment by diox** [comment]
From IRC discussion today:
- To access deleted add-ons, create a new `Addons:ViewDeleted` permission, giving it to the `Staff` group
- It would be nice to make permission handling a little more sane by starting to have constants for them. That way we ensure that when we add a new permission, we've at least looked at the existing list.

**Comment by eviljeff** [comment]
Well, I did the second bullet point :)  Is the first still valid?

**Comment by diox** [comment]
Yeah, I think so. Your refactor does make it easier to fix but I don't have time for it currently.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
