### ISSUE TITLE
Long review content break the layout in editor tools - add-on review logs

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3447]
### Steps to reproduce:
1. Open https://addons-dev.allizom.org/en-US/editors/reviewlog
2. Click on the Show Comment link for a review that contains a long comment

Expected results:
There are no layout or display issues.
### Actual results:

The layout breaks.
### Notes/Issues

Verified in FF48(Win7) Issue can be reproduced in addons-dev and addons-stage
Screencast for this issue: 
![reviewhistorybug](https://cloud.githubusercontent.com/assets/15685441/18351140/a3fe8818-75e1-11e6-8066-8506ffedbbf6.gif)

**Comment by wagnerand** [comment]
Mentor: @eviljeff.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by leni1** [comment]
@eviljeff I'm interested in working on this bug. However I am unable to reproduce it via the link that @madalincm used. I ended up with the following error:

Oops! Not allowed.
You tried to do something that you weren't allowed to.

I'm guessing that it is reproducible on a local build of the addon-server code and that it isn't platform specific, since I happen to be using Linux at the moment. Your thoughts are appreciated.

**Comment by eviljeff** [comment]
@leni1 Hi.  Yes, you'll need a local build of the server running to test it yourself.   See http://addons-server.readthedocs.io/en/latest/topics/install/docker.html for details - it's not platform specific but we regularly run it via docker on Windows, Linux & Mac.

**Comment by anubhavsinha98** [comment]
I am a newbie to opensource so please help me to solve this issue!
I want to learn more about this issue.

**Comment by eviljeff** [comment]
@anubhavsinha98 have you set up a local addon-servers instance and gotten into the reviewer tools?

**Comment by anubhavsinha98** [comment]
@eviljeff according to @madalincm  I opened the link provided by him but its showing OOPS! NOT ALLOWED! on the web page.

**Comment by eviljeff** [comment]
See the reply to leni1

**Comment by anubhavsinha98** [comment]
@eviljeff I have set up a local addon-servers !

**Comment by anubhavsinha98** [comment]
Cloned the addon-server repo, now what to do?

**Comment by jrbenny35** [comment]
@anubhavsinha98 not to bud in but you probably want to follow this doc: https://addons-server.readthedocs.io/en/latest/topics/install/docker.html

**Comment by eviljeff** [comment]
@anubhavsinha98 next step after you've cloned the repo and have addons-server running locally is to try to replicate the issue locally - 

- submit an addon to your local server;
- in http://olympia.test/en-GB/reviewers/ find the review in the queues
- then approve or reject the addon with a long review comment (a single word without spaces)

**Comment by eviljeff** [comment]
I'm pretty certain you can fix this with some css.  I think you'll find the css to change in `olympia/static/css/zamboni/reviewers.less` (look for the class, or parent class, etc)

**Comment by anubhavsinha98** [comment]
Ok I am trying with it, this repo is of more than a GB waiting for it to get downloaded.

**Comment by anubhavsinha98** [comment]
I am working on it.

**Comment by LordGameleo** [comment]
Is it open?

**Comment by eviljeff** [comment]
@LordGameleo the issue is open (as github indicates).  @anubhavsinha98 said they were working on it though.  I don't know where they got to.

**Comment by LordGameleo** [comment]
@anubhavsinha98  are you still working on this issue.

**Comment by anubhavsinha98** [comment]
No @LordGameleo , currently I am not working on this issue!
You can take the issue!
Happy Coding!

**Comment by LordGameleo** [comment]
@eviljeff I am working on this issue. I just wanted to ask how to upload an addon. I can't just add any .zip file.

**Comment by eviljeff** [comment]
you can upload any (webextension based) addon downloaded from AMO.  Or a test one from https://staticfil.es/webext-generator/

**Comment by LordGameleo** [comment]
![screenshot from 2018-09-06 16-07-56](https://user-images.githubusercontent.com/40512667/45152576-0c82d100-b1ef-11e8-9512-6cfc775650f8.png)
I am getting an error while uplading it.

**Comment by eviljeff** [comment]
that normally means your addons-server isn't set up correctly.  You can see more about the error in the `/logs/` folder - `docker.log` and/or `docker-celery.log`.  If you can't work it out then it's probably going to be easier to come talk in #amo on irc because debugging server installs via github issues is hard.

**Comment by LordGameleo** [comment]
@eviljeff  I saw these log files I couldn't find anything that may be the reason for this. I again set up the using docker. Still it is like this.

**Comment by caitmuenster** [comment]
Hey @LordGameleo, it's probably easier to troubleshoot the addons-server setup in real time. Can you join us on IRC in the #amo channel? If this is your first time using IRC, instructions for how to join can be found here: https://wiki.mozilla.org/IRC

**Comment by caitmuenster** [comment]
We're removing this from the "good first bug" list until we can figure out where the bug in the add-ons server dev environment is.

**Comment by miphilomath** [comment]
Is this issue open to work? I would like to work on, If it is still open to work :)

**Comment by eviljeff** [comment]
@miphilomath it is still open, but we took if off the good first bug list because it requires a fully working local addons-server setup, which many other contributors (in this issue and others) have found prohibitively difficult to do.  If you can get it all up and running, please go ahead.

**Comment by miphilomath** [comment]
Cool! I will it a shot and will ask on the IRC channel if I need any help :)

**Comment by miphilomath** [comment]
I have a query while reviewing the test add-on submitted on my local project.

Steps I followed:
* Installed the required software, docker version `Docker version 18.06.1-ce, build e68fc7a
` in my system following the tutorial on https://addons-server.readthedocs.io/en/latest/topics/install/docker.html.
* Start the docker service using systemctl.
* Installed the docker-compose in my system using `pip install docker-compose` in a `virtualenv` 
* Activated my Virtualenv
* `docker-compose pull` in project directory
* `make initialize_docker`
* `docker-compose up -d`
* Added `olympia.test` in `/etc/hosts`
* Accessed the service on 'http://olympia.test`
* Registered for the account and submitted a test addon from here, https://staticfil.es/webext-generator/

Error Encountered:
* To test the bug, I need to review the addon with single and long comment but unable to access the reviewers access on `http://olympia.test/reviewers`
* "Not allowed!" Error encountered. 
![screenshot from 2018-11-10 14-03-19](https://user-images.githubusercontent.com/26297035/48299583-da466600-e4f4-11e8-86ac-446d40d634b3.png)

**Comment by diox** [comment]
@miphilomath : try this:
```
docker-compose exec web ./manage.py addusertogroup your@email 1
```

Where `your@email` is replaced by the email of the user you created. Then refresh the page, you should have access to the reviewers page (and more, this makes your user an admin - `1` is the id of the admins group)

**Comment by miphilomath** [comment]
Yes, It worked. I now finally managed to triaged the issue :)

**Comment by caitmuenster** [comment]
Hey @miphilomath, were you able to figure this out?

**Comment by suhailsinghbains** [comment]
Hi
I would like to take this one up.

**Comment by eviljeff** [comment]
@suhailsinghbains no, you don't have access to that tool.  You will need to run addons-server locally and replicate there so you can fix it.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified this on AMO dev and the issue is no longer reproducible. A long unbroken string won't break the layout of the page. 

![string layouts on dev](https://user-images.githubusercontent.com/33448286/66291408-6a9a5000-e8ea-11e9-9f1f-001ca66e6a6c.png)

**Comment by wagnerand** [comment]
Reopning, as the patch caused a regression (#12547).
