### ISSUE TITLE
API endpoint for overall add-on ratings

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3451]
Users of the new mobile UI will be able to give an add-on an [overall rating](https://github.com/mozilla/addons-frontend/issues/1017). This is a low-friction way to begin rating an add-on before going into detail. It consists of three values to gauge their experience:

* Love it!
* It's OK
* Huh?

We need a new endpoint to create this overall rating for the logged in user.

UX flow tracker: https://github.com/mozilla/addons-frontend/issues/927

**Comment by kumar303** [comment]
We may be able to re-use the [review API](http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#post) for this but we wouldn't want these type of ratings to show up on the old site.

**Comment by kumar303** [comment]
@diox @EnTeQuAk any thoughts on using the existing review API for this? Or do we need a new API?

**Comment by diox** [comment]
I specifically built the review API for this. As discussed I don't remember which meeting (mobile frontend kick off meeting or stand-up) the idea was to use the API to get / set a rating of 1, 3 (or 4 if you prefer) or 5 and present the human friendly versions in the frontend. That way we get the old ratings information and the new rating continue to work on the old site.

**Comment by diox** [comment]
See https://github.com/mozilla/addons-server/issues/3024 for the general tracker I've been using for this.

**Comment by kumar303** [comment]
Ah, cool. Is it ok to post a review that has no text? I was wondering if this would pose a problem on the old site. I think the frontend / backend flow would look something like:

* User selects the "I love it!" smiley
* App posts a 5 star review to the API without a title or a body
* App asks the user, would you like to leave more feedback?
* User writes a longer review
* App *updates* the 5 star review to add a body of text

There will be an additional complication with the [generic feedback UI](https://github.com/mozilla/addons-frontend/issues/1018) but we can worry about that later.

**Comment by andymckay** [comment]
In #3328 @diox said it should be ok. Might be worth checking the effect on the rest of AMO. Will having no comment mess up the desktop UI for example?

**Comment by kumar303** [comment]
We chatted about it on IRC. I think a review without a comment will be fine. If it becomes a problem we can always hide them later. Thanks, I will try using the existing API and file new bugs if I hit issues!
