### ISSUE TITLE
Reviews aggregation queries are broken

### ISSUE THREAD

**Issue by JonathonGold** [mozilla/addons-server#3452]
https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular

Scroll down. Right side, Up to the "Write a review" button. It has **1** for each rating.

**Comment by diox** [comment]
Thanks for the report.

I suppose I broke that when refactoring reviews for the API and no tests caught that :(

**Comment by diox** [comment]
Could also be django 1.8 upgrade actually...

**Comment by diox** [comment]
Confirming, it's the 1.8 upgrade, and more specifically 7c560174c62918bb0cd4f50aa5fcc4f4ac8456f2.

You can reproduce locally by leaving a bunch of reviews on an add-on (the latest version of `generate_addons` command should do this for you) and run the following:

```python
from django.db import models
addon = Addon.objects.get(slug='review-me')
Review.unfiltered.all().no_cache().filter(addon=addon).values_list('rating').annotate(models.Count('rating'))
```

If the result look something like this, it's wrong:
```python
[(None, 0), (2, 2), (0, 2), (4, 1), (3, 1), (4, 1), (3, 1), (5, 1), (0, 2), (2, 1), (1, 1), (2, 1), (1, 1), (2, 1), (3, 2), (2, 1), (3, 1), (5, 1), (1, 2), (4, 1), '...(remaining elements truncated)...']
```

If it looks something like this, it's right:
```python
[(None, 0), (0, 4), (2, 7), (5, 4), (4, 5), (3, 7), (1, 8)]
```

My guess is the query generated is subtly different (and broken) in 1.8. I wonder if something else could be broken on the site as a result.

**Comment by diox** [comment]
Note that the total reviews count for add-ons are also broken in a similar way, as soon as you post a new review. I've just submitted a pull request to fix both issues. Once this lands we may want to re-trigger the tasks on all add-ons which were reviewed since the last push.

**Comment by madalincm** [comment]
The review section still looks broken in stage. From what I remember this bug should have fix this issue. Should we log another bug for this layout problem?
Please have a look in here: https://addons.allizom.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular

![brokenreviewes](https://cloud.githubusercontent.com/assets/15685441/18702728/a50b5312-7feb-11e6-9dbf-a789d96e1336.png)

**Comment by diox** [comment]
Looks like some add-ons were not fixed on stage. I just ran the script to regenerate broken data and that fixed it.

**Comment by AlexandraMoga** [comment]
This is no longer an issue.
