### ISSUE TITLE
Investigate moving wafflejs to be served via the CDN

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3455]
An example of where this script is served is as part of the submission flow e.g:
https://addons.mozilla.org/en-US/developers/addon/submit/2

* Is this actively used? If not can it be removed?
* If it is can we move it to the CDN? (@diox mentioned it should not be cached)

**Comment by muffinresearch** [comment]
See https://github.com/mozilla/addons-server/blob/874726d1a9b76356464a3c2e8730000090cbe868/src/olympia/amo/urls.py#L23

**Comment by muffinresearch** [comment]
I don't see any mention of `waffle` in js - so I'm not sure we're using this.

**Comment by diox** [comment]
It's only included in devhub FWIW.

It currently returns, in prod:
```
FLAGS = {
    'automatic-validation': true,
    'collect-timings': false,
    'no-prelim-review': true,
    'restyle': true,
    'unlisted-addons': true
},
SWITCHES = {
    'video-upload': false,
    'current_version_crons': true,
    'reviews-translate': true,
    'drf': false,
    'allow-long-addon-guid': true,
    'local-statistics-processing': true,
    'icloud_bookmarks_redirect': true,
    'fxa-migrated': true
},
SAMPLES = {
    'autosuggest-throttle': false,
    'csp-store-reports': false,
    'disco-pane-store-collections': true,
    'paypal-disabled-limit': false
}
```

A lot of those should be removed / should have been removed already. And I'm not sure any of those are useful in js code.

**Comment by diox** [comment]
I can't find any reference to `waffle` or these particular values in js code in addons-server either. I vote for killing it.

**Comment by eviljeff** [comment]
looks like it was a apps/Marketplace thing https://github.com/mozilla/addons-server/commit/80cdf47ff7a1349e8348fe788a2e5d67ac896058

**Comment by muffinresearch** [comment]
QA: Notes - this was only used on the devhub. Since it was un-used the removal should cause no problems.

**Comment by ValentinaPC** [comment]
Checked functionality for all pages in Dev Hub, and no errors were thrown. 
Also, "waflejs" is no longer displayed in the web console.
Let me know if there is anything else to be checked. Thanks!
