### ISSUE TITLE
White section when window is smaller than the page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3457]
Steps to reproduce:
1. Load any **theme/collection** details page with resized browser (window smaller than the page) i.e https://addons-dev.allizom.org/en-US/firefox/addon/moonforget/
2. Scroll to the right and observe the header and the footer

Expected results:
There are no display or layout issues.

Actual results:
There is a white section on header and footer.

Notes/Issues:
Verified on FF48(Win 7). Issue is reproducing on all AMO servers.
Video for this issue: 
![theme-coll](https://cloud.githubusercontent.com/assets/15685960/18388145/1eef0bb6-76a9-11e6-8d59-66b55a0b2588.gif)

**Comment by EnTeQuAk** [comment]
Given that we're reimplementing all that relatively soon I'm going to close this since we really aim to simply not introduce any bugs like that in the new addons-frontend since it'll be so much better, nicer, more beautiful and generally super awesome :)
