### ISSUE TITLE
Make the google script-src reference more explicit

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3463]
The script for GA is fixed, we can therefore point at the full script path instead of just the origin.

**Comment by muffinresearch** [comment]
QA Notes:

You should see the google analytics script continue to load ok following this change. Look for 'https://ssl.google-analytics.com/ga.js' in the network tab.

**Comment by ValentinaPC** [comment]
@muffinresearch : 
The Network tab returns a 304 into the console for the request you mentioned, using AMO-dev FF48(Win 7). 
Is this how it should behave? Thanks!
![google analitycs](https://cloud.githubusercontent.com/assets/15685960/18426368/bdfa1fc6-78c9-11e6-8d8c-5342b4297335.png)

**Comment by muffinresearch** [comment]
@ValentinaPC yep - you're just looking for it not to be blocked. If you force refresh you should see a 200, but in any case as long as it's not getting blocked we're good.

**Comment by ValentinaPC** [comment]
Based on verification in AMO-dev FF48.0.2(Win 7x64) and above 2 comments I'll mark this verified - fixed.
