### ISSUE TITLE
New add-on submission flow for Listed and Unlisted

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3468]
Part of #3465

The new submission flow will be shorter for all submissions and will have a step dedicated to selecting the channel. UX for this new flow is in ~~mozilla/addons#197, mozilla/addons#198,~~ mozilla/addons#199, ~~mozilla/addons#200~~.

**Comment by eviljeff** [comment]
In https://cloud.githubusercontent.com/assets/51007/18494607/357437d8-7a6b-11e6-83cb-a6b12e3a22f5.png the 'done' screen shows text indicating the add-on can be made publicly viewable when the developer chooses.  This isn't current behaviour (it's on the site immediately after editor approval) and I don't see an issue requesting a change.  Can you clarify?

**Comment by eviljeff** [comment]
in https://github.com/mozilla/addons/issues/199 btw

**Comment by jvillalobos** [comment]
The text is wrong, it's definitely not the final copy.

**Comment by eviljeff** [comment]
Can you supply replacement copy for any strings not as per bram's mockups in those issues?  (and the unlisted one)

**Comment by eviljeff** [comment]
QA - test all combinations you can think of of new add-on submission, both listed and unlisted.

**Comment by vcarciu** [comment]
Should I wait for #3802 to be closed before marking this as verified?

**Comment by eviljeff** [comment]
> Should I wait for #3802 to be closed before marking this as verified?

whatever works for you - just check it doesn't blow up horribly for now I guess.

**Comment by vcarciu** [comment]
Verified as fixed with various submission scenarios.
