### ISSUE TITLE
Update add-on visibility box and status sidebar for Listed and Unlisted versions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3471]
Part of #3465

The Add-on Visibility box on Status & Versions needs to be updated, since Listed / Unlisted won't be a global status anymore. UX for this is in mozilla/addons#194.

The status sidebar (appearing above the navigation items on the left column) also needs to be updated.  The UX discussion about this began in https://github.com/mozilla/addons/issues/193#issuecomment-245777027, but will be moved to a separate issue.

**Comment by eviljeff** [comment]
My best guess on outstanding questions in mozilla/addons#193 is in #4005

**Comment by jvillalobos** [comment]
After discussing with @wagnerand, I'd like to make some text changes to avoid developer confusion about what visible/invisible means. Here's my proposal:

> * Visible: visible to everyone on this site, and included in search results and listing pages.
> * Invisible: your add-on won't be included in search results, and its listing page will indicate you disabled it. New version submissions for listing won't be accepted in this state.

**Comment by eviljeff** [comment]
> New version submissions for listing won't be accepted in this state. 

Is that true?

**Comment by jvillalobos** [comment]
They won't be reviewed, so I would consider that as non-acceptance :). #4025 covers the actual blocking of those submissions.

**Comment by eviljeff** [comment]
I slightly modified to make the text consistent:

> "Visible to everyone on {0} and included in search results and listing pages."

> "Hosted on {0}, but won't be included in search results, and its listing page will indicate you disabled it. New version submissions for listing won't be accepted in this state."

`{0}` is the site url, so addons.mozilla.org for prod.

@jvillalobos okay?

**Comment by jvillalobos** [comment]
I removed the site name and 'hosted on' bits in the update because they were originally there to contrast with `Unlisted`, which is no longer there. I don't mind the `Visible to everyone on {0}`, but I'd rather not have `Hosted on {0}`.

**Comment by eviljeff** [comment]
> **Invisible:** Won't be included in search results, and its listing page will indicate you disabled it. New version submissions for listing won't be accepted in this state.

Or 
> **Invisible:** Your add-on won't be included in search results, and its listing page will indicate you disabled it. New version submissions for listing won't be accepted in this state. 

I prefer the former as the 'Visible' text doesn't start with "Your add-on is visible..."

**Comment by jvillalobos** [comment]
The first one is okay.
