### ISSUE TITLE
 Hide unneeded developer options when only unlisted versions have been submitted

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3472]
Part of #3465

The developer hub has a lot of management pages and options, many of which are only relevant to listed add-on developers. We should hide the things that aren't needed when an add-on only has unlisted versions. UX for this is in mozilla/addons#195, mozilla/addons#196.

**Comment by eviljeff** [comment]
Clarification - "only unlisted versions have been submitted" - so once you've submitted a listed version once you get all the options?  What if you delete the listed version(s), leaving only unlisted?
(And what if you delete all the versions)

**Comment by jvillalobos** [comment]
The more precise wording would be "when the add-on doesn't have enabled listed versions". So, if all listed versions are deleted or disabled, the listing options shouldn't appear. If the disabled case is too much of a hassle, it's fine to drop, since it's edge-casey and the only fallout is UI clutter.

**Comment by eviljeff** [comment]
Hiding all the settings if the last listed version is disabled may be jarring for the developer (e.g. it gets rejected).  Up to you but I'd go with the options being available it there are any non-deleted listed versions.

Also need clarification on the null case - what if an add-on has no listed and no unlisted versions?  (all deleted).  Is it to be treated as a listed add-on or an unlisted add-on?

**Comment by jvillalobos** [comment]
The rejection case is a good point, so let's keep them available like you said.

If all versions are deleted, let's treat it as an unlisted add-on.

**Comment by ValentinaPC** [comment]
Checked various scenarios, like: 

- submit listed add-on, not approved/approved, disable version

- submit listed add-on, not approved/approved, delete version

- submit listed add-on, not approved/approved, make it hidden

- submit listed add-on, not approved/approved, make it unlisted

- etc.

Options from add-on edit page are acting as expected.
Maybe other cases could be checked after "An add-on with a mix of unlisted/listed versions" is implemented.
