### ISSUE TITLE
Cleanup for Listed and Unlisted versions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3473]
Part of #3465 (and hopefully the final step)

The only cleanup step that comes to mind is removing `is_listed` from `addon`. The rest should be already covered in other bugs.

**Comment by diox** [comment]
Depend on https://github.com/mozilla/addons-server/issues/3977

**Comment by eviljeff** [comment]
Everything will be cleaned up in #4442 but leaving this issue to remove the column asynchronously from the database and add a migration for local installs.

**Comment by eviljeff** [comment]
`is_listed` column is gone (on dev, stage, and prod today) so calling it done!
