### ISSUE TITLE
Desktop layout on mobile site

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-server#3474]
### What did you do?
Navigate to https://addons.mozilla.org/en-US/android/users/edit (already logged in)

### What happened?
Desktop layout on mobile website

### What did you expect to happen?
Mobile optimized website.

![photo266479365140883814](https://cloud.githubusercontent.com/assets/5318732/18408810/fecb5ce0-7757-11e6-8911-62ebdf38b8f2.jpg)

**Comment by muffinresearch** [comment]
Thanks for the bug report. This will eventually be fixed as we migrate to a new frontend based on mozilla/addons-frontend which will be responsive from the start.
