### ISSUE TITLE
Make sure to use `.objects` when calling `get_object_or_404` on models with soft-deletion

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3478]
When you call `get_object_or_404()` with a model as the first argument, django uses the first manager for that model, not necessarily `objects`. When we do soft-deletion on models, that first manager is often `unfiltered`, to allow relations, cascade etc to work properly.

This means that any call to `get_object_or_404(SomeModel)` has a potential of returning deleted instances of `SomeModel`, which is usually something we don't want. Instead, we should use `get_object_or_404(SomeModel.objects)`.

As far as I can tell, only `Addon`, `Version` and `Review` are affected. I'm already taking care of `Review` as part of another issue. A quick grep found:
```
src/olympia/addons/views.py:    version = get_object_or_404(Version, pk=version)
src/olympia/devhub/views.py:    version = get_object_or_404(Version, pk=version_id, addon=addon)
src/olympia/devhub/views.py:        addon = get_object_or_404(Addon, slug=addon_slug)
src/olympia/devhub/views.py:        addon = get_object_or_404(Addon, slug=addon_slug)
src/olympia/devhub/views.py:    version = get_object_or_404(Version, pk=version_id, addon=addon)
src/olympia/devhub/views.py:    version = get_object_or_404(Version, pk=version_id, addon=addon)
src/olympia/devhub/views.py:    version = get_object_or_404(Version, pk=version_id, addon=addon)
src/olympia/devhub/views.py:    version = get_object_or_404(Version, pk=version_id, addon=addon)
src/olympia/versions/views.py:    version = get_object_or_404(Version, pk=version_id)
src/olympia/versions/views.py:    version = get_object_or_404(Version, pk=version_id)
src/olympia/editors/views.py:    addon = get_object_or_404(Addon, pk=addon_id)
```

**Comment by muffinresearch** [comment]
@diox I wonder if we could have a custom lint rule to guard against this happening in the future?

**Comment by diox** [comment]
Maybe. It's hard to really guard against it, and it's a bit specific - only 3 models are affected - but it may be worth doing it, yeah.
