### ISSUE TITLE
"Invalid value" message for Contribution is displayed in multiple languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3481]
Steps to reproduce:
1. Load an add-on details page with contribution i.e. https://addons-dev.allizom.org/en-US/firefox/addon/web-developer/?src=ss
2. Click the "Contribute" button
3. Enter a small value (i.e. 0.014)
4. Click the "Make Contribution" blue button

Expected results:
A message is displayed saying that the value is too small in the used language.

Actual results:
The message is displayed using some Cyrillic letters.

Notes/Issues:
Intermittently the message is displayed using other languages (i.e French)
![another_lang](https://cloud.githubusercontent.com/assets/15685960/18434732/80653c4e-78f7-11e6-9fc9-54e96ccf84c1.png)
![french](https://cloud.githubusercontent.com/assets/15685960/18434733/8067ab3c-78f7-11e6-9064-522fc627ea77.png)

Verified on FF48.0.2 (Win 7 x64). Issue is reproducing around all AMO servers.
Screenshot for this issue: 
![2016-09-12_1425](https://cloud.githubusercontent.com/assets/15685960/18434739/89ab707a-78f7-11e6-9f45-6efa2f549630.png)

**Comment by muffinresearch** [comment]
Does this reproduce on production?

**Comment by ValentinaPC** [comment]
All screenshots are from AMO-prod.

**Comment by muffinresearch** [comment]
@ValentinaPC ah ok, I missed that in the screenshots because the STR url is -dev.

**Comment by ValentinaPC** [comment]
Sorry for misleading.
i.e. Try this https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular
Enter 0.013 and click two times on "Make contribution"

**Comment by eviljeff** [comment]
contributions are gone!
