### ISSUE TITLE
Themes with "Daily users" on two rows have layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3484]
Steps to reproduce:
1. Load Themes homepage in AMO-dev in other language i.e. https://addons-dev.allizom.org/uk/firefox/
2. Hover over a theme from Themes section 

Expected results:
There are no display or layout issues.

Actual results:
Themes that have "Daily users" on 2 rows appear with installation button as cut.

Notes/Issues:
Reproduced more often in homepage and "More by this artist" section (I think this is happening because the theme "boxes" are smaller there, than in other places e.g. listing pages)
Verified on FF48.0.2(Win 7x64). Issue is reproducing on AMO-stage, dev and production.
Screenshot: 
![themes](https://cloud.githubusercontent.com/assets/15685960/18465163/f5889ec0-799d-11e6-9d50-183eead6982b.png)

Other **URLs** to reproduce:
dsb - https://addons-dev.allizom.org/dsb/firefox/ 
ru - https://addons-dev.allizom.org/ru/firefox/ 
nl - https://addons-dev.allizom.org/nl/firefox/ 
etc.

**Comment by EnTeQuAk** [comment]
Given that we're expecting more and more work (+desktop) this year being done on the new addons-frontend I'm going to close this to focus on the new world.

If this is a more urgent issue since it's broken more heavily than I imagine please feel free to re-open anytime.
