### ISSUE TITLE
"Override failed validation" option check returns a 500 error at submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3485]
Steps to reproduce:
1. Select to submit the attached web-extension using AMO-dev https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2. Check the "Override failed validation " box

Expected results:
User can continue with submission.

Actual results:
"Oops.." page is displayed.

Notes/Issues:
Verified on AMO-dev FF48.0.2 (Win 7 x64)
Used webextension: 
[We-Heart-It_v4.1.14.zip](https://github.com/mozilla/addons-server/files/469317/We-Heart-It_v4.1.14.zip)

**Comment by EnTeQuAk** [comment]
Relevant sentry error: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/349501/

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2(Win 7)
Postfix video: 
![continue](https://cloud.githubusercontent.com/assets/15685960/18504093/28ccd050-7a69-11e6-9c64-1d6849cc56f9.gif)
