### ISSUE TITLE
Add the edit URL to the upload endpoints

### ISSUE THREAD

**Issue by darktrojan** [mozilla/addons-server#3489]
When I upload a new version of an extension (via the API as I'm usually in my console at the time), the next thing I want to do is post the version notes. If the URL to the edit page (or at least the version id) was in the API response I could go straight there instead of via at least two other pages.

**Comment by EnTeQuAk** [comment]
Hmm, I don't think we want to expose that kind of information in the API. We are working on all sorts of APIs currently though to be able to support the development of our new https://github.com/mozilla/addons-frontend so if those version notes happen to be implemented there, we will add an api endpoint so you could theoretically automate that yourself some time.

I'm going to close this though for now unless there's a strong reason to interlink like that.

**Comment by darktrojan** [comment]
If you don't want to expose that information you probably should remove it from the public API, for example [here](https://addons.mozilla.org/api/v3/addons/addon/new-tab-tools/versions/1923995/). :-)

**Comment by diox** [comment]
I think what @EnTeQuAk meant is that he didn't want to add the links themselves to the API responses. We might add them at some point if we need to, but for now, we'd prefer not to.
