### ISSUE TITLE
Documentation: Bad JWT authentication token used as example

### ISSUE THREAD

**Issue by palant** [mozilla/addons-server#3493]
Documentation under http://addons-server.readthedocs.io/en/latest/topics/api/auth.html uses `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0NDcyNzMwOTZ9.MG9LJiEK5_Db8WpF5cWWRebXCtUB48EJzxKIBqQhSOo` as example authentication token. Now for the people who would like to generate the token themselves this isn't a good example. First of all, the payload part encoded here is `{"iat":1447273096}` - `iss` and other fields missing got me confused initially, I thought that not all payload fields are transmitted. Worse yet, the signature is bogus - it contains an underscore meaning that it isn't valid base64. I assume that this underscore should be a forward slash, the signature size is correct then.

I'd suggest using `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ5b3VyLWFwaS1rZXkiLCJqdGkiOiIwLjQ3MzYyOTQ0NjIzNDU1NDA1IiwiaWF0IjoxNDQ3MjczMDk2LCJleHAiOjE0NDcyNzMxNTZ9.MG9LJiEK5/Db8WpF5cWWRebXCtUB48EJzxKIBqQhSOo` as example token, this actually shows what a proper token should look like.

**Comment by mstriemer** [comment]
I think the underscore is there since it is a URL safe base 64 encoding, replacing `+` with `-` and `/` with `_`. We are using PyJWT and it looks like they accept both formats. Their documentation shows the URL safe variant: https://pypi.python.org/pypi/PyJWT/1.4.0#usage.

It looks like https://jwt.io exports URL safe by default, that's likely where this came from. How about using `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ5b3VyLWFwaS1rZXkiLCJqdGkiOiIwLjQ3MzYyOTQ0NjIzNDU1NDA1IiwiaWF0IjoxNDQ3MjczMDk2LCJleHAiOjE0NDcyNzMxNTZ9.fQGPSV85QPhbNmuu86CIgZiluKBvZKd-NmzM6vo11DM` and linking to the [jwt.io debugger](https://jwt.io/?value=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ5b3VyLWFwaS1rZXkiLCJqdGkiOiIwLjQ3MzYyOTQ0NjIzNDU1NDA1IiwiaWF0IjoxNDQ3MjczMDk2LCJleHAiOjE0NDcyNzMxNTZ9.fQGPSV85QPhbNmuu86CIgZiluKBvZKd-NmzM6vo11DM#debugger) so it's easy to see the value.

**Comment by palant** [comment]
Ok, I didn't realize there was a different base64 variant, then it's fine of course (my script still sends regular base64, it's not a URL). Yes, your suggestion sounds good to me.

**Comment by madalincm** [comment]
The link for  jwt.io debugger is now displayed: 
![debugerlink](https://user-images.githubusercontent.com/15685441/35616994-953ff908-067f-11e8-8184-f3cefa179b3b.png)

But the displayed example token (eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ5b3VyLWFwaS1rZXkiLCJqdGkiOiIwLjQ3MzYyOTQ0NjIzNDU1NDA1IiwiaWF0IjoxNDQ3MjczMDk2LCJleHAiOjE0NDcyNzMxNTZ9.fQGPSV85QPhbNmuu86CIgZiluKBvZKd-NmzM6vo11D
) seems invalid. 
If the user copies the example token and paste it in the debugger he receives an invalid signature message:
![invalidsignature](https://user-images.githubusercontent.com/15685441/35617081-dc1e53ec-067f-11e8-9632-fded27b86cc9.png)

I think there is a "M" missing from the token that is causing the token to be invalid.
Reopening bug.

**Comment by AlexandraMoga** [comment]
I've had a look in the API docs and the information regarding the use of '_secret_' has been added.
The link to jwt.io debugger is working and the user can verify the token by clicking the link and following the verification instruction. 

However, the JWT example desplayed in the docs is still not updated, meaning that if I copy/paste the example token in the debugger, I'm still seeing the 'Invalid signature' message.

@EnTeQuAk could the JWT token example provided in the docs also be updated? 

![image](https://user-images.githubusercontent.com/31961530/41841301-980042f2-7870-11e8-94e3-555e6b99a6d0.png)

![image](https://user-images.githubusercontent.com/31961530/41841315-a26a3766-7870-11e8-828d-f003aa598e1f.png)

**Comment by EnTeQuAk** [comment]
> However, the JWT example desplayed in the docs is still not updated, meaning that if I copy/paste the example token in the debugger, I'm still seeing the 'Invalid signature' message.
> @EnTeQuAk could the JWT token example provided in the docs be updated? Also, do we want this only in the v4 documentation? The v3 docs did not receive these updates.

Indeed, I did not update the actual token. I'll fix this. Thanks a lot for the hint!

**Comment by EnTeQuAk** [comment]
I mislinked the issue in my PR.

This got fixed in https://github.com/mozilla/addons-server/pull/8812

**Comment by madalincm** [comment]
Verified as fixed in FF61(Win7). 
Postfix screencast:
![jwt](https://user-images.githubusercontent.com/15685441/42623402-7626bb58-85cb-11e8-9526-3c86a515f5ef.png)
Marking bug as verified fixed.
