### ISSUE TITLE
addons server failing to sign my .xpi

### ISSUE THREAD

**Issue by groovecoder** [mozilla/addons-server#3502]
### What did you do?
`web-ext sign --api-user=<redacted> --api-key=<redacted>`

### What happened?
```
sign: Error: Validation took too long to complete; last status: {"guid":"blok@mozilla.org","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/blok@mozilla.org/versions/1.0rc6/uploads/94b362a2b65f482aa6bf54397dbbb976/","files":[{"hash":"sha256:d0df2891de957edaae40b088a0524d1788cb87a117057bc921bf788f9691513a","signed":true,"download_url":"https://addons.mozilla.org/api/v3/file/502141/blok-1.0rc6-fx+an.xpi?src=api"}],"passed_review":false,"pk":"94b362a2b65f482aa6bf54397dbbb976","processed":true,"reviewed":false,"valid":true,...
    at Timeout._onTimeout (/Users/lcrouch/code/blok/node_modules/sign-addon/dist/webpack:/src/amo-client.js:214:16)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

### What did you expect to happen?
Addons server should have returned my signed `.xpi` file.

### Anything else we should know?
I see `processed: true` and `valid: true` but it still times out? And [the results link](https://addons.mozilla.org/api/v3/addons/blok@mozilla.org/versions/1.0rc6/uploads/94b362a2b65f482aa6bf54397dbbb976/) response `{"detail":"Authentication credentials were not provided."}`
```
[sign-addon] [API] GET response:
 Status: 200
 { headers:
   { allow: 'GET, POST, PUT, HEAD, OPTIONS',
     'content-security-policy': 'script-src \'self\' https://addons.mozilla.org https://www.paypalobjects.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://ssl.google-analytics.com https://addons.cdn.mozilla.net; default-src \'self\'; img-src \'self\' data: blob: https://www.paypal.com https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; style-src \'self\' \'unsafe-inline\' https://addons.cdn.mozilla.net; frame-src \'self\' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; object-src \'none\'; connect-src \'self\' https://sentry.prod.mozaws.net; font-src \'self\' https://addons.cdn.mozilla.net; report-uri /__cspreport__',
     'content-type': 'application/json',
     date: 'Tue, 13 Sep 2016 19:33:09 GMT',
     etag: '"83230b48574d52c4c7f9caee09c26e82"',
     server: 'nginx',
     'strict-transport-security': 'max-age=31536000',
     vary: 'X-Mobile, User-Agent',
     'x-backend-server': 'ip-172-31-41-5',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'DENY',
     'x-xss-protection': '1; mode=block',
     'content-length': '1327',
     connection: 'Close' },
  response:
   { guid: 'blok@mozilla.org',
     active: false,
     automated_signing: true,
     url: 'https://addons.mozilla.org/api/v3/addons/blok@mozilla.org/versions/1.0rc6/uploads/94b362a2b65f482aa6bf54397dbbb976/',
     files: [ [Object] ],
     passed_review: false,
     pk: '94b362a2b65f482aa6bf54397dbbb976',
     processed: true,
     reviewed: false,
     valid: true,
     validation_results:
      { errors: 0,
        success: true,
        warnings: 0,
        messages: [Object],
        passed_auto_validation: true,
        ending_tier: 5,
        compatibility_summary: [Object],
        detected_type: 'extension',
        signing_summary: [Object],
        notices: 1,
        signing_ignored_summary: [Object],
        metadata: [Object] },
     validation_url: 'https://addons.mozilla.org/en-US/developers/upload/94b362a2b65f482aa6bf54397dbbb976',
     version: '1.0rc6' } }
```

**Comment by kumar303** [comment]
The [validation results](https://addons.mozilla.org/en-US/developers/upload/94b362a2b65f482aa6bf54397dbbb976) show that it should have passed review (I think). Since this add-on is unlisted I'm not sure why it wasn't signed.

**Comment by kumar303** [comment]
if it's easy, could you attach a text file of the full output with 

    web-ext --verbose sign ... --timeout=10000 

? That will show us the initial PUT responses as well as the GET responses. It will stop after 10 seconds so the log should be short-ish.

**Comment by groovecoder** [comment]
https://gist.github.com/groovecoder/eaf648649f5d033e4bdb178e763c287f

**Comment by mstriemer** [comment]
New versions are listed as Beta [1] but we have a test [2] that shows that shouldn't happen for unlisted.


[1] https://addons.mozilla.org/en-US/developers/addon/blok1/versions
[2] https://github.com/mozilla/addons-server/blob/b9c4aa89f883572b3f05b75b8b26dd8a75e364bf/src/olympia/signing/tests/test_views.py#L231-L251

**Comment by eviljeff** [comment]
The 'rc' in the version string is triggering beta version detection so it's getting marked as a beta version.  That shouldn't happen for unlisted addons (we apparently have a bug) but beta is signed anyway so it shouldn't be a problem...

The test in [[2]](https://github.com/mozilla/addons-server/blob/b9c4aa89f883572b3f05b75b8b26dd8a75e364bf/src/olympia/signing/tests/test_views.py#L231-L251) needs updating, which I [did ](https://github.com/mozilla/addons-server/pull/3494/files#diff-a2b5268d8e9c234d081f5658cd7dec07L231 )but it's not merged yet.

**Comment by groovecoder** [comment]
FWIW, I had signed 'rc1' and 'rc2' successfully before 'rc4' hit this problem.

**Comment by mstriemer** [comment]
The problem is just that it has changed how this works. We don't want beta to happen for unlisted and web-ext isn't expecting to get a beta back so it is choking.

I modified the test locally to have the add-on with `status=amo.STATUS_PUBLIC` and it is indeed making the test fail the same way we see here. The version is created as a beta when it shouldn't be.

I'd say https://github.com/mozilla/addons-server/pull/3494 is the fix for this issue then.

I tried uploading a new unlisted version through the website on stage and this is what I see, not sure if it is related. It happens for "beta" (1.7.0-rc1) and non-beta (1.6.3) version strings. Checking the upload validation  shows it there.

<img width="512" alt="screenshot 2016-09-14 10 46 47" src="https://cloud.githubusercontent.com/assets/211578/18519220/b825af98-7a68-11e6-80aa-a23a2118abd9.png">

**Comment by kumar303** [comment]
> FWIW, I had signed 'rc1' and 'rc2' successfully before 'rc4' hit this problem.

It looks like we introduced a regression, probably on last week's deployment (on Thursday)

**Comment by kumar303** [comment]
@eviljeff it sounds like you are the best person to check on fixing this but correct me if I'm wrong.

**Comment by eviljeff** [comment]
does this happen on -dev now?

**Comment by eviljeff** [comment]
This might be fixed in #3494 (just merged).  When -dev is up will try.

**Comment by muffinresearch** [comment]
Fwiw the screenshot in https://github.com/mozilla/addons-server/issues/3502#issuecomment-247058784 looks to be the same thing as https://bugzilla.mozilla.org/show_bug.cgi?id=1303217 for which a fix has been committed.

**Comment by eviljeff** [comment]
#3494 does indeed fix the beta issue with unlisted addons.
With that and https://github.com/mozilla/addons-server/issues/3502#issuecomment-247580205 I think we're done here.
Re-open if you're still having problems.
