### ISSUE TITLE
[Statistics] Bad source data should not be added

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3510]
Steps to reproduce:
1. Load Statistics page for any add-on with public stats in AMO-prod i.e. https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/statistics/?last=30
2. Go to Download->By Source page
3. Click "Next" to navigate in the "Download sources by Date" section

Expected results:
There are no display or layout issues.

Actual results:
There is a white padding displayed between table header and the content. If we scroll to the right side we observe a bad source data that is causing the padding.

Notes/Issues:
Verified on FF48.0.2(Win 7) using AMO-prod.
Screenshots for this issue: 
![pg2](https://cloud.githubusercontent.com/assets/15685960/18509925/0b1f045e-7a84-11e6-98e1-171070754528.png)
![2016-09-14_1321](https://cloud.githubusercontent.com/assets/15685960/18509931/11cb40b0-7a84-11e6-991f-cfcf3419f5f0.png)

**Comment by muffinresearch** [comment]
Would be good to investigate how this currently works. Can we limit to a list of allowed src params to avoid this kind of data being displayed.

**Comment by EnTeQuAk** [comment]
So, from my investigation: We already limit sources in the `DownloadSource` model which can be configured in the admin. There are two variations of sources, one that requires a full match and one that only requires a partial match by prefix.

The one found here only requies a prefix match unfortunately so the behavior is perfectly correct. Not sure what to do about it, if someone has the permissions to look on prod how many sources are configured and how many actually require a partial match that'd be nice, best maybe to remove the partial match feature.

At least we should normalize and sanitize those inputs and fix the layout issue to show an ellipse in case of unexpected large text.

**Comment by eviljeff** [comment]
here are the sources: https://gist.github.com/eviljeff/c3f0ba71392fbd81de60dac9d4a9ba24 (some are likely to be obsolete)

**Comment by EnTeQuAk** [comment]
I stopped working on this for now, I'll followup once q4 goals and file-browser stuff and maybe other things are done.

**Comment by ValentinaPC** [comment]
Seems like this was fixed on AMO-prod FF54(Win 10).
Postfix video:
![stats](https://user-images.githubusercontent.com/15685960/27709339-6274af1e-5d24-11e7-9f6b-c77a2f3bbdd0.gif)
