### ISSUE TITLE
Version status turning in to "Preliminary Reviewed" after "Cancel Review Request" and unlisting

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3517]
Steps to reproduce:
1. Submit an add-on using https://addons.allizom.org/en-US/developers/addon/submit/2
2. Go to "Manage Status and Versions" and check the "Hidden" option
3. Make it "Listed" again
3. Add a new version for that add-on
4. In "Manage Status and Versions" page click "Cancel Review Request" (for the version submitted at step 3)
5. Check the "Unlisted" option

Expected results:
The version is automatically fully reviewed.

Actual results:
The version is automatically PRELIMINARY reviewed.

Notes/Issues:
Verified on FF48.0.2(Win 7). Issue is reproducing on AMO-stage.
Screenshot for this issue: 
![2016-09-15_1112](https://cloud.githubusercontent.com/assets/15685960/18542779/486e2fae-7b35-11e6-8e28-b97380162c8a.png)

**Comment by ValentinaPC** [comment]
Relates to #3494

**Comment by ValentinaPC** [comment]
This is no longer reproducing, but, after making these steps the last version added is **automatically fully reviewed**, but still has the "Request Full Review" link. 
![link](https://cloud.githubusercontent.com/assets/15685960/18944330/891ea2a6-862d-11e6-9177-9bcd63ca233e.png)

**Comment by eviljeff** [comment]
I don't think this issue is applicable any more.  We've replaced it with new status bugs 😆
