### ISSUE TITLE
Blocklists certificates missing in XML and JSON file.

### ISSUE THREAD

**Issue by Natim** [mozilla/addons-server#3518]
### Describe the problem and steps to reproduce it:

If you look at both URLs:

- https://addons.allizom.org/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/46.0/
- https://addons.allizom.org/blocked/blocklists.json

You will see that there is a difference:

You can find `ESFfLkWTIV5an6YQtSudbzKT` in the XML one and not in the JSON one, the other way around for `CZua`

```
                 {
-                    "@issuerName": "MEwxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSIwIAYDVQQDExlBbHBoYVNTTCBDQSAtIFNIQTI1NiAtIEcy", 
-                    "serialNumber": "ESFfLkWTIV5an6YQtSudbzKT"
+                    "@issuerName": "MEcxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMSAwHgYDVQQDExdSYXBpZFNTTCBTSEEyNTYgQ0EgLSBHMw==", 
+                    "serialNumber": "CZua"
                 }, 
```

### What happened?

At first we thought it was a similar issue as #3405 but for #3405 this is related to having two blocked item with the same add-ons `guid`.

### What did you expect to happen?

I know that the block ID for `CZua` is `c1154` however I couldn't find yet the one for `ESFfLkWTIV5an6YQtSudbzKT`

This is really a strange behavior, because the view uses directly `issuerCertBlocks = BlocklistIssuerCert.objects.all()` to get all the blocked certificates and both views JSON and XML are using it. I don't see how one could be overridden somewhere.

### Anything else we should know?

This is a major bug for the [synchronization mecanism](https://github.com/mozilla-services/amo2kinto) between AMO and Kinto.

**Comment by eviljeff** [comment]
The json [url ](https://addons.allizom.org/blocked/blocklists.json) for me is returning c1154 correctly as 
```
            "issuerName": "MFoxCzAJBgNVBAYTAk5MMR8wHQYDVQQKDBZHZXRyb25pY3MgTmVkZXJsYW5kIEJWMSowKAYDVQQDDCFHZXRyb25pY3MgQ1NQIE9yZ2FuaXNhdGllIENBIC0gRzI=",
            "blockID": "c1154",
            "details": {
                "who": "mwobensmith.",
                "created": "2016-09-13T15:17:49Z",
                "name": "QA Cert",
                "bug": "https://bugzilla.mozilla.org/show_bug.cgi?id=1286600",
                "why": ".onecrl regression testing"
            },
            "serialNumber": "fU+JpbcYY+v46GDSd3GX1w=="
```
which matches https://addons.allizom.org/en-US/admin/models/blocklist/blocklistdetail/1154/
I couldn't find `ESFfLkWTIV5an6YQtSudbzKT` or `CZua`.

The XML isn't working for me at all - I just get an error `{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet on resource: mmd-uat-es"}`

**Comment by Natim** [comment]
@eviljeff apparently the stage environment changed a bit since my try (DNS, etc) Do you know where is the XML endpoint for the stage environment?

**Comment by Natim** [comment]
This was supposed to work before: https://addons.allizom.org/blocklist/3/%7B3550f703-e582-4d05-9a08-453d09bdfdc6%7D/47.0/

**Comment by diox** [comment]
I'm getting 403s as well on those XML URLs :(

**Comment by Natim** [comment]
Maybe @jasonthomas knows where are the news URLs.

**Comment by jasonthomas** [comment]
I had setup a redirect from amo blocklist stage to kinto blocklist stage which didn't work as expected. I've reverted my changes and it should be back to normal.

**Comment by jasonthomas** [comment]
https://blocklist.allizom.org/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/46.0/ is the direct endpoint, addons.allizom.org redirects to blocklist.allizom.org.

**Comment by diox** [comment]
Now that it's fixed I can access both the json and XML variants but I can't find `ESFfLkWTIV5an6YQtSudbzKT` or `CZua` in either list. Is this issue still valid?

**Comment by Natim** [comment]
Let me check locally, I will tell you in a minute.

**Comment by Natim** [comment]
I don't have any diff between both version so far. I will close this until I can reproduce the error. Thanks everyone.

**Comment by eviljeff** [comment]
https://addons.allizom.org/blocked/blocklists.json is still broken though - it's not valid json because it's got
```
{"response":[{"name":"Cache-Control","value":"max-age=3600"},{"name":"content-security-policy","value":"script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.paypalobjects.com/js/external/dg.js https://addons.cdn.mozilla.net https://addons-stage-cdn.allizom.org; img-src 'self' data: blob: https://www.paypal.com https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net https://addons-stage-cdn.allizom.org; object-src 'none'; default-src 'self'; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com https://www.sandbox.paypal.com; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net https://addons-stage-cdn.allizom.org; media-src https://videos.cdn.mozilla.net; child-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com https://www.sandbox.paypal.com; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net https://addons-stage-cdn.allizom.org; form-action 'self' https://developer.mozilla.org; base-uri 'self' https://addons.mozilla.org https://addons.allizom.org; report-uri /__cspreport__"},{"name":"Content-Type","value":"application/json"},{"name":"Date","value":"Thu, 15 Sep 2016 13:29:52 GMT"},{"name":"Etag","value":"\"afef7272af49df0ebd6becff929a31d7\""},{"name":"Server","value":"nginx"},{"name":"Strict-Transport-Security","value":"max-age=31536000"},{"name":"Vary","value":"X-Mobile, User-Agent"},{"name":"X-Backend-Server","value":"ip-172-31-20-207"},{"name":"X-Content-Type-Options","value":"nosniff"},{"name":"X-Frame-Options","value":"DENY"},{"name":"X-XSS-Protection","value":"1; mode=block"}],"request":[{"name":"Host","value":"addons.allizom.org"},{"name":"User-Agent","value":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"},{"name":"Accept","value":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},{"name":"Accept-Language","value":"en-US,en;q=0.5"},{"name":"Accept-Encoding","value":"gzip, deflate, br"},{"name":"Referer","value":"https://github.com/mozilla/addons-server/issues/3518"},{"name":"DNT","value":"1"},{"name":"Connection","value":"keep-alive"},{"name":"Upgrade-Insecure-Requests","value":"1"}]}
```
at the end

**Comment by Natim** [comment]
I don't see that myself :s

**Comment by eviljeff** [comment]
The issue I just mentioned is a json parsing problem related to amo's csp rules and dev edition.  Not blocklist specific.

**Comment by Natim** [comment]
Do you call it with a JSON content-type?

**Comment by diox** [comment]
@natim: unrelated bug in dev edition/nightly itself, see https://github.com/mozilla/addons-server/issues/3527 and https://bugzilla.mozilla.org/show_bug.cgi?id=1303086
