### ISSUE TITLE
500 error when trying to make a "no-version" addon Unlisted

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3519]
Steps to reproduce:
1. Load "My Submissions" page in AMO-stage https://addons.allizom.org/en-US/developers/addons
2. Go to "Manage Status and Versions" page for any listed add-on 
3. Delete all its versions
3. Change its status to "Unlisted"

Expected results:
Status is successfully changed or a message saying you cannot do this action is displayed.

Actual results:
An "Oops..." page is displayed.

Notes/Issues:
Verified on FF48.0.2(Win 7). Issue is also reproducing on production.
Screencast for this issue: 
![oops](https://cloud.githubusercontent.com/assets/15685960/18545224/db9d59fc-7b40-11e6-8fd5-7f3646ad4696.gif)

**Comment by muffinresearch** [comment]
Here's the related sentry link: https://sentry.prod.mozaws.net/operations/olympia-stage/issues/349836/ for the stage example here.

**Comment by ValentinaPC** [comment]
May be related to #3804

**Comment by diox** [comment]
Yeah, like #3627 it will be fixed by #3804.
