### ISSUE TITLE
Error displayed when uploading a new version for an unlisted incomplete add-on

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3520]
### Steps to reproduce:
1. Open manage status and version page for an unlisted add-on that has the status incomplete (i.e: https://addons.allizom.org/en-US/developers/addon/08112016test02/versions)
2. Click on Upload New Version button and try to submit a new version for that add-on.

### Expected results:
The user can upload a new verssion.

### Actual results:
Received an empty response from the server; status: 404   Message is displayed.

### Notes/Issues:
Verified in FF48(Win7) issue can be reproduced in amo-stage
![newverserror](https://cloud.githubusercontent.com/assets/15685441/18545312/516af040-7b41-11e6-8018-bfc7a219d581.png)

**Comment by muffinresearch** [comment]
Fixed by https://github.com/mozilla/addons-server/pull/3534

This fix is in production. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1303217

**Comment by madalincm** [comment]
Issue is no longer reproducing:
![3520post](https://cloud.githubusercontent.com/assets/15685441/18631018/576c7fba-7e78-11e6-9569-3724135fa564.png)
