### ISSUE TITLE
[RTL] Reviews and "Other addons by author" sections are not loaded on a dirty profile

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3524]
Steps to reproduce:
1.Open FF Release with a dirty profile(I used an old profile but without any specific add-ons installed)
1. Load any add-on details page using an arabic language (ie. https://addons.allizom.org/ar/firefox/addon/%C4%83%C3%A2%C3%AE%C5%9F%C5%A3-%C3%A3-l%C3%A3/?src=cb-dl-updated)

Expected results:
Add-on details page is loaded with all information available

Actual results:
Revuiews and "Other add-ons by author" sections are not loaded in RTL

NOTES:
Not reproducible on a clean profile

Please see video for this bug : 
![rtldetails](https://cloud.githubusercontent.com/assets/1583842/18554738/dd6243ec-7b6d-11e6-8358-af54ebff5b18.gif)

**Comment by muffinresearch** [comment]
Since this are all the same issue marking as a dupe: #3528
