### ISSUE TITLE
JSON responses are broken on dev edition - CSP is blocking internal json viewer

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3527]
Anywhere a JSON response is returned such as during the upload validation or blocklist the output contains extra content meaning it's no longer valid json.

Likely cause is:
``` Content Security Policy: The page’s settings blocked the loading of a resource at resource://devtools/client/jsonview/ (“base-uri https://addons.allizom.org https://addons.mozilla.org https://addons.allizom.org”).```

**Comment by muffinresearch** [comment]
Devtools shouldn't be affected by our CSP rules. I think this needs a devtools bug to be filed on bugzillla.

**Comment by muffinresearch** [comment]
If anyone needs to workaround this issue:

Going to `about:config` and setting `devtools.jsonview.enabled` to `false` will then show the old-style json response.

**Comment by eviljeff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1303086

**Comment by muffinresearch** [comment]
There's no action to take this end so closing this in favour of the bugzilla bug.
