### ISSUE TITLE
JS format function throwing for AR locale

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3528]
We have various bugs filed which mention issues with the AR locale (see the linked issues below).

The issue seems to be that the locale was updated adding support for multiple plural forms, however there's no translations for the additional plural forms, so the JS throws an exception [1] when encountering an empty string.

This change [2] was the most recent change relating to a change to the plural forms for the AR locale.

[1] https://github.com/mozilla/addons-server/blob/master/static/js/lib/format.js#L13
[2] See https://github.com/mozilla/addons-server/commit/60624ba8cc1dfb6b85a11d0b3d426e6abb103da1

Relates to: #3418
Relates to: #3526
Relates to: #3524 

I'll check if this is happening for other locales too.

**Comment by muffinresearch** [comment]
The calling line is: https://github.com/mozilla/addons-server/blob/7a6b9ce050a0b3f1cf76dc8a1773cba1de770bc8/static/js/common/ratingwidget.js#L31

I think this likely to be the one causing all the trouble since the iterations across the numbers of stars is going to hit the case where we don't have a translation for that index.

**Comment by muffinresearch** [comment]
Filing in the translations here locally and rebuilding the locales fixed the problem, so I think the next step is to get a localizer to fill in the missing translations and that should fix this.

[1] https://github.com/mozilla/addons-server/blob/master/locale/ar/LC_MESSAGES/djangojs.po#L23

**Comment by muffinresearch** [comment]
The error to look for in the console is "Format string is empty!" also this generally repros only when logged-in due to it being related to ratings functionality.

**Comment by muffinresearch** [comment]
I've emailed a localizer to see if we can get the locale updated.

**Comment by muffinresearch** [comment]
I've emailed the l10n mailing list to ask for help with this.

**Comment by mohamed7afezz** [comment]
Hi @muffinresearch i updated the plural translations for missing strings in [pontoon](https://pontoon.mozilla.org/ar/amo/LC_MESSAGES/djangojs.po/?string=66616), just waiting automatic pushing to github.

**Comment by muffinresearch** [comment]
@mohamed7afezz excellent thanks!

**Comment by muffinresearch** [comment]
Fixed by https://github.com/mozilla/addons-server/commit/390e17880d16bce4c1a58e5f0b0ae6c4b673d036

**Comment by ValentinaPC** [comment]
The "Format string is empty!" js error is no longer thrown in the console.
Verified as fixed on AMO-dev FF48.0.2(Win 7) around some AMO pages.
Postfix screenshot from Themes homepage:
![js](https://cloud.githubusercontent.com/assets/15685960/18704496/c2fcd74a-7ff2-11e6-97c3-7114ca578bb4.png)
