### ISSUE TITLE
Searching after “%add”  will result in an “Opps! We had an error” message

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3536]
Steps to reproduce:
1.Load AMO https://addons.mozilla.org/en-US/firefox/ page.
2.Type “%adb” into the “search for add-ons” box from the top right. 

Expected result:
One or more results are displayed after the search.

Actual result:
 “Opps! We had an error” message is displayed.

Notes/Issues:
I’ve also reproduced this issue with “%ee” , “%adb” , “%ad”.

Verified on FF48.0.2(Win 7 64-bit)
This issue is reproducing in AMO dev, stage and production servers.

**Comment by muffinresearch** [comment]
Related sentry report https://sentry.prod.mozaws.net/operations/olympia-prod/issues/348994/

**Comment by cosminbadescuSV** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
Postfix video: 
![adb](https://cloud.githubusercontent.com/assets/15885467/18958626/ecb258b0-866b-11e6-9af7-01a2c6e160b2.gif)
