### ISSUE TITLE
/editors/performance/ webpage shows too many reviews for September 2016

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#3541]
### Describe the problem and steps to reproduce it:

Going to https://addons.mozilla.org/en-US/editors/performance/ shows currently 49034 reviews in September 2016, an average per reviewer jump from 600 to 2300 reviews.
### What happened?

Changes on eliminating the prelim queue last week is probably the source of this issue. Jorge V. guessed on IRC that maybe it stopped filtering our unlisted reviews for some reason.
### What did you expect to happen?

The number of reviews and its average should be similar as the last months, as there was no big difference in terms of reviewers workload by looking at "Top Reviewers (past 7 days)" from the past two weeks.

**Comment by jvillalobos** [comment]
@eviljeff could this be related to the recent preliminary review changes?

**Comment by eviljeff** [comment]
Its possibly including all the migration notes that were added to each
changed add-on. Though they were added in the same way other automatic
messages are added so they shouldn't have been.

**Comment by jvillalobos** [comment]
The performance page is fairly old. Maybe it's counting comments and we never noticed.

**Comment by eviljeff** [comment]
from a quick look, it's counting by event - essentially everything that shows up in the review log shown in `/editors/` is counted.  So automated approvals for unlisted; these migration messages; possibly other stuff; all included in the total.  

A quick fix for existing performance is to exclude activity by the `TASK_USER_ID` but it will need to be more fine-grained once activity mail and developer replies are included or they'll be counted too.

**Comment by wagnerand** [comment]
Part of #3726 I suppose.

**Comment by ValentinaPC** [comment]
Not sure how to check this, because seems like September 2016 looks ok from Performance point of view. Please add some STR for us to check or mark it with "needs no qa" label. Thank you!

**Comment by eviljeff** [comment]
yeah the preliminary migration events were already fixed (not sure when) so September 2016 was correct when I looked.  So I just made sure that automatic approvals for unlisted versions were excluded too.
You can verify by submitting an unlisted version and checking the total review count doesn't go up.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
Adding a new unlisted version does not change the overall review count.
