### ISSUE TITLE
Implement search autocomplete API endpoint

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#3545]
I'm looking to implement the autocomplete for https://github.com/mozilla/addons-frontend/issues/1079 using the `/api/v3/addons/search/` API. I think this would be the right approach over implementing a custom autocomplete API but I could be wrong.

Right now the search API returns a lot of extra info for my needs (I just need name & slug right now, probably icon in the future). Maybe a "condensed" or "_autocomplete" param that reduced the response size (and presumed non-cached request time) would be useful? Not sure about that.

Right now the autocomplete on AMO seems to be separate from the actual search, as the results for the same string I get in the autocomplete are different to the search results page. I'd like to use the search API to avoid this in the future and minimise code paths, but if this is too naive for the kind of responsiveness we'd want for autocomplete let me know.

Opening this for discussion, basically.

**Comment by diox** [comment]
A separate endpoint would probably be best, depending on the needs in terms of filtering/fields/ordering we could even leverage [ElasticSearch suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-suggesters.html) feature - I did that in Marketplace and it seemed better for performance.

So, what fields / filtering options / ordering options do you need ?

**Comment by tofumatt** [comment]
Hmm, interesting. Good point, and clearly the reason the autocomplete
suggestions should be different than the search results, as they’re search
suggestions (/me was being dense earlier I guess).

I would want to search by name (giving that a lot of weight) and
description (giving it little to prevent description spamming). It would
probably be really cool to add in the content of ratings/reviews to the
search (so if a lot of people rated something highly it would come up, but
also common terms they use like “fast” would rate the search for “fast
adblock” higher. But that’s something we could do later.

For starters I think just a suggestion based on add-on name and description
would be a great start.
