### ISSUE TITLE
NOT FOUND

### ISSUE THREAD

**Issue by Nanas-Dusty-Box** [mozilla/addons-server#3547]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Went to the following webpage : http://www.clickvideodownload.com/download.php 
then clicked on the following links:

**## Download The Add-On

The latest version can be downloaded from here:**
[1 Click Video Download ](https://addons.mozilla.org/en-US/firefox/addon/1-click-youtube-video-download/)

For previous versions: (It is not recommended to use old versions!)
[1 Click Video Download](https://addons.mozilla.org/en-US/firefox/addon/1-click-youtube-video-download/versions/)

### What happened?
[got this page instead ](https://addons.mozilla.org/en-US/firefox/addon/1-click-youtube-video-download/)

### What did you expect to happen?
to get the latest file file or plugin to appear and then go abo
![1 click video download a](https://cloud.githubusercontent.com/assets/22282597/18619797/5ac3c664-7dd3-11e6-8a67-9cf91be21a3d.png)
![1 click video download b](https://cloud.githubusercontent.com/assets/22282597/18619798/5ac40200-7dd3-11e6-9ea3-fde363f1d2b4.png)

ut my business

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
We don't have control over the links on a 3rd party site. I'd suggest you contact the site author and tell them their download link is pointing to a 404.
