### ISSUE TITLE
Auto-respond to emails that are broken

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3555]
Splitting out #3349 to make it easier to track

Auto-respond to emails that are broken or have an invalid token rather than just silently ignore

**Comment by eviljeff** [comment]
@EnTeQuAk wrote
> I'm a bit worried here, all those headers can very easily be forged and it seems (unless I'm missing something) that I could send an automated mail that get's added via the the API, is invalid for some spoofed reason and set From to eviljeff at mozilla.com and send spam emails. Is that a valid case or am I just missing some additional verification step somewhere? I know we have the activity token that get's parsed and verified but that doesn't stop us from bouncing it seems.

bouncing was requested by @jvillalobos - as it stands we would auto-respond to every email that had either a `from` or `reply-to` header, even if it was otherwise entirely broken/empty. (Though socketlabs would presumably only forward emails that were some level of valid).  If we only want to bounce a subset of emails and silently ignore the rest we could do that instead (e.g. message had content but missing token; had a token like thing in the to: but it wasn't in the database; had a token but it was invalid; etc)

**Comment by ValentinaPC** [comment]
Please add some STR for us to verify this or the label "needs no qa". Thanks!

**Comment by eviljeff** [comment]
with the waffle switch `activity-email-bouncing` enabled:

send emails to @addons-dev.allizom.org that
- are to a random email address, e.g. foo@addons-dev.allizom.org
- are to a valid looking reply address but with a token that doesn't exist (modify the to address a little).  E.g. reviewreply+5a0b8a83d501412589cc5d562334b46b@addons-dev.allizom.org
- are to a valid reply address (get one out of fake mail) but you are unauthorised to reply to (e.g. you aren't an AMO reviewer/admin; you aren't a developer of that add-on.)
- are to a valid reply address but there is a newer version now.  str - review a version; upload a new version; the token for the old version shouldn't be valid now.
- bonus for weird encoding, etc.

In each case you should get an automated email back.

**Comment by ValentinaPC** [comment]
Sorry to insist...
I don't know how to send e-mails to `@addons-dev.allizom.org` that are to a random e-mail address.
How do I send e-mail to a random e-mail address through AMO and activity mails?
I am not able to create an account in AMO using that "domain"... I couldn't access the mail, to verify it.
I have a feeling that either I don't have the resources to check this, or...I've did not understood correctly your steps.
Thanks in advance.

**Comment by eviljeff** [comment]
you send emails with your email client/webmail (gmail?).  It doesn't matter what account you send the email 'from', only what address the email is addressed 'to'.  There are example email addresses for the first 2 bullet points. Is that clearer?

**Comment by ValentinaPC** [comment]
Yes, it's clearer.
Tried with the first two options, the e-mails were sent but no automated email was received. :(

**Comment by ValentinaPC** [comment]
Following the steps given by evilljeff, in the previous comment, I was not able to receive any automated emails back. 
Tried sending mails from _gmail_ and _yahoo_, if counts. 
E-mails were sent (ex.: first 2 options) as it can be seen in these two screenshots, no errors received, but neither an automated e-mail.
![to](https://cloud.githubusercontent.com/assets/15685960/19890206/e535c424-a041-11e6-84bc-e94349462eaa.png)
![yahoo](https://cloud.githubusercontent.com/assets/15685960/19890207/e5397470-a041-11e6-9895-2cfc394d6ec1.png)

**Comment by ValentinaPC** [comment]
I've also tried with the `activity-email-bouncing` flag disabled to see if there are some differences but the results are the same. :(
I think there is a problem somewhere, maybe on my side..

Used examples:
- reviewreply+9e11afc8e80d4a0598f641a0f9ea8ce6@addons-dev.allizom.org -> e-mail sent from peleskeiv@gmail.com
- valentina@addons-dev.allizom.org ->e-mail sent also from peleskeiv@gmail.com

No mails bounced back.

**Comment by eviljeff** [comment]
they will bounce into fake mail - I'm not sure if that's where you're looking.  Otherwise, I will still look into this and get it sorted before we enable the feature on prod (probably end of Q4 or start of Q1)

**Comment by ValentinaPC** [comment]
I searched everywhere, maybe it needs time 😄 
Does it counts that the sender is an e-mail associated to an AMO admin account?
Thanks for you reply!

**Comment by eviljeff** [comment]
I might have this fixed 😱 😮 
the fake mail log shows the emails now (though some with possibly weird formatting)

**Comment by EnTeQuAk** [comment]
🎉

**Comment by eviljeff** [comment]
calling this fixed.  Re-open if it's still broken (formatting issues new issue please)

**Comment by ValentinaPC** [comment]
Verified as fixed using AMo-dev FF51(Win 7).
Sent 2 e-mails from gmail  to:
- reviewreply+5a0b8a83dfhghd@addons-dev.allizom.org
- valentinaclara@addons-dev.allizom.org 
Received 2 e-mails back that can be seen in Admin Tools - Manage Add-ons - Fake Mail logs (https://addons-dev.allizom.org/en-US/admin/mail)
Postfix screenshot:
![bounce](https://cloud.githubusercontent.com/assets/15685960/23203845/f0478754-f8ec-11e6-9e28-68bc4bbe9140.png)
