### ISSUE TITLE
Copy admins at amo on all activity emails

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3557]
Splitting out #3349 to make it easier to track

Add a new permission and group for users that get a copy of all activity emails (with reply tokens)

**Comment by eviljeff** [comment]
Probably do "Also need to exclude task user Mozilla from the version history for email purposes" in here too or we might get circular emails threads.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF49(Win 7) as follows:
Added my admin account into the CC Activity Mails group:
![addtocc](https://cloud.githubusercontent.com/assets/15685960/19681291/82078dc8-9ab1-11e6-9c4f-024466ebd4a5.png)
Logged in with another account and added a review from Review History section:
![reviewer_reply](https://cloud.githubusercontent.com/assets/15685960/19681299/8cdbd84e-9ab1-11e6-82f3-dd26515f76c9.png)
Accessed fake mails admin page (using my admin account) -  https://addons-dev.allizom.org/en-US/admin/mail and observed that I've "received an e-mail":
![mail](https://cloud.githubusercontent.com/assets/15685960/19681465/30c79b32-9ab2-11e6-99b5-757857e0a651.png)

If there isn't anything else that must be checked here, we can mark this verified. 
@eviljeff Just let me know.

**Comment by eviljeff** [comment]
That's it. You could check that you don't get duplicates if you are already involved in the add-on as the developer or the reviewer but you'll probably test that in the other issues.

**Comment by ValentinaPC** [comment]
From yesterday, even if I am in the `Activity Mail CC` , I do not receive any fake mail while adding a reply for an add-on from Review history; do you have any idea why?

**Comment by eviljeff** [comment]
are you replying with the same account?

**Comment by ValentinaPC** [comment]
I am using the same account like yesterday, the account I've added in the Activity Mails CC group; and....the used add-on is not mine and it sends a fake mail to its creator, but not to me.

**Comment by ValentinaPC** [comment]
While this is not working on -dev using fake mails log, I'll reopen until further notice.
Added my account in `Activity Mail CC`, but did not receive any activity mail copy. (**at some point this was working** as can be seen from my previous comments)

**Comment by ValentinaPC** [comment]
While being logged with an admin account in AMO-dev FF50(Win 7):
- Added another account (with reviewer rights) in the `Activity mail CC` group
- Added a reply to a random add-on i.e. Firebug from Review history section of Dev Hub
- Checked the Fake mails page and saw a mail received for the user added in the `Activity mail CC` group.
Screenshots:
![dev-hub](https://cloud.githubusercontent.com/assets/15685960/20390926/9fcc507a-acd9-11e6-932a-92991538d2e1.png)
![group](https://cloud.githubusercontent.com/assets/15685960/20390936/a5d70046-acd9-11e6-8233-b42daa573e4c.png)
![fake_mails](https://cloud.githubusercontent.com/assets/15685960/20390941/a96fa384-acd9-11e6-993b-94785bed2a94.png)

Closing this as verified fixed.
