### ISSUE TITLE
Use channel to determine version visibility and updates

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3567]
Part of #3465

Once we're setting `channel` for all add-on versions, we need to start using that attribute instead of `is_listed`. This includes a few tasks that can be broken down into separate bugs if needed:
- [x] Only show versions on the listed channel on public add-on pages.
- [x] Only show listed versions in the review page of an add-on, by default. ~~Implement a switch to flip between listed and unlisted versions. Alternatively, create a different review page for unlisted versions.~~ Remaining editor tools modifications are tracked in https://github.com/mozilla/addons-server/issues/3989
- [x] Only use listed versions on the listed channel for automatic updates.
- [x] Only use listed versions on the listed channel for legacy API (which is used by about:addons)

**Comment by diox** [comment]
One big problem we're going to have is `current_version` and `latest_version` on the `Addon` model. Those properties point to the latest public version and latest available version, respectively, and are used throughout the site to show the latest version available to the user/developer. Both unlisted and listed add-ons use those at the moment, yet we probably those to point to versions in the unlisted channel... This will be tricky.

We'll also need to be careful about `update_status()`, which sets the status on the `Addon`.

**Comment by diox** [comment]
I'll investigate removing `latest_version` property altogether to simplify things, replacing it with a method that can filter on the channel and optionally include/ignore disabled versions.

If that works, maybe the next step could be to rename `current_version` to something like `public_listed_version` and use the new method for all other use cases.

**Comment by diox** [comment]
All tasks done. Each will necessitate extra QA to make sure nothing is broken, particularly around the add-on update stuff.

**Comment by ValentinaPC** [comment]
This can be marked as verified-fixed.
