### ISSUE TITLE
Every refresh action loads "Add a new Version" popup even if was initial canceled 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3570]
Steps to reproduce:
1. Load Edit Listing page for any add-on i.e. https://addons-dev.allizom.org/en-US/developers/addon/tab-mix-plus/edit
2. Click the "Upload a New Version" link above
3. Click "Cancel" in the popup window
4. Refresh the page

Expected results:
The page is refreshed.

Actual results:
Every time a refresh action is made, the "Add a new Version" popup appears.

Notes/Issues:
It is reproduced if at step 1 user goes to "Manage Authors & License", "Manage Developer Profile"or "Manage Payments" page.
Verified on FF48.0.2(Win 7). Issue is reproducing around all AMO servers.
Video for this issue: 
![refresh](https://cloud.githubusercontent.com/assets/15685960/18712392/e40003e4-8016-11e6-967f-3899d4683c1a.gif)

**Comment by eviljeff** [comment]
The inline dialog that did this has been replaced with different pages.
