### ISSUE TITLE
Dont show "Awaiting full review" message for add-ons with only disabled versions available

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3573]
Steps to reproduce:
1.Submit a new add-on
2.From Manage Status&Versions, make the add-on hidden(observe that add-on version is now "Disabled by Mozilla")
3.Make it listed again

Expected results:
Add-on status is not "Awaiting full review" until a new version of add-on is uploaded

Actual results:
Add-on status is "Awaiting full review" even if all its versions are disabled

Please see a photo of the issue : 
![awaiting](https://cloud.githubusercontent.com/assets/1583842/18717285/1bacfbc4-8028-11e6-8fae-696e3e1958a8.png)

**Comment by eviljeff** [comment]
I'm pretty sure this is fixed now but please re-open if you can replicate.
