### ISSUE TITLE
Document the review API responses

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3578]
None of the JSON responses are documented for the Review API, for example: http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#post

I saw one fly by but I didn't copy the JSON in time. Since you only typically get one post before the next one is a 400, it would be helpful to see the response documented.

**Comment by diox** [comment]
I'll add docs, but it's pretty straightforward: if it's a 200, you get the same data you'd get when calling the detail API, which is documented.

**Comment by kumar303** [comment]
OK, good to know. I think it would be fine to just link to the Details section for the response.

A section about error responses would be really helpful (like, examples of `non_field_errors`, etc). I feel like we had a generic section for error responses but I can't find it now.
