### ISSUE TITLE
Privacy policy missing even though it has been entered in the add-on listing

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#3580]
### Describe the problem and steps to reproduce it:
- Go to https://addons.mozilla.org/en-US/editors/review/pokego-tab
- Click on the privacy policy link which takes you to https://addons.mozilla.org/en-US/firefox/addon/pokego-tab/privacy/
### What happened?
- The privacy policy page loads with the "Not Found" message
### What did you expect to happen?
- The page should show the privacy policy entered in the listing

**Comment by eviljeff** [comment]
The add-on is incomplete now, so the add-on listing page is inaccessible and I guess privacy policy for the same reason.

**Comment by kewisch** [comment]
That would make sense, but I have been able to view the privacy policy in all cases before during review. Maybe I was always lucky to have cases where the add-on is not incomplete though.

**Comment by EnTeQuAk** [comment]
We're closing this since it's more an edge-case where the add-on is in a state where you can't see the listing page so it's okay to not access the privacy policy too.
