### ISSUE TITLE
Instant Session Joining in Screenconnect

### ISSUE THREAD

**Issue by CATNigel** [mozilla/addons-server#3584]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Screenconnect displays the following message:  Suggestion: Install the Microsoft .NET Framework Assistant extension to enable instant session joining.

### What happened?

I downloaded the tool, which was KB article, This article has been removed, so say by an administrator.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

My copy of Screenconnect will not work properly in Firefox.  It use too - quite well, but now it doesn't work properly without a bit of farting about.  Oh well, back to Google Chrome I go, and I will recommend that ALL of out clients do the same (All 5465 of them in the UK)

**Comment by tofumatt** [comment]
This is an issue with Screenconnect and Microsoft's website, not the add-ons website or Firefox.

If you could report this issue to Screenconnect or Microsoft they should be able to help you.
