### ISSUE TITLE
RTL issues for header in AMO homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3590]
Steps to reproduce:
1. Load AMO-prod page https://addons.mozilla.org
2. Change the language to a RTL one i.e. https://addons.mozilla.org/ar/firefox/
3. Hover over "Other Application" link

Expected results:
Other application icons are near the name, in the right side.

Actual results:
Icons are in the wrong side.

Notes/Issues:
Also, the "mozilla" logo is in the wrong side of the header.
Verified on FF48.0.2.
Screenshot for this issue: 
![2016-09-23_1527](https://cloud.githubusercontent.com/assets/15685960/18785727/9662df48-81a2-11e6-83c2-65f360af0c14.png)

**Comment by ValentinaPC** [comment]
The issue was not fixed for "Firefox" application icon. (issue can be seen if other application is selected i.e. Thunderbird)
Please see the screenshot: 
![2016-09-27_0848](https://cloud.githubusercontent.com/assets/15685960/18861720/10ff79ce-8490-11e6-9eaa-7420263e10a2.png)
Also the "mozilla" logo is not in the expected position.
Please see the screenshot: 
![mozilla](https://cloud.githubusercontent.com/assets/15685960/18861757/52c17f9c-8490-11e6-8d56-65c7035e0769.png)

**Comment by atiqueahmedziad** [comment]
ah, I can fix the Firefox logo alignment. Well, I am not sure why [`.html-rtl #tabzilla {...}`](https://github.com/mozilla/addons-server/blob/master/static/css/tabzilla/tabzilla.css#L8-L10) is not showing in browser. It's likely the `tabzilla.css` file is not getting the update version of it. @tofumatt can you please add your opinion here?

**Comment by tofumatt** [comment]
I commented in the PR, seems like a `.firefox a` class is needed, but if the CSS isn't showing make sure the right version is deployed to -dev. If not... it could be an assets issue and is worth asking ops. That'd be `jason` in the `#amo` IRC channel.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
Postfix screenshot: 
![rtl](https://cloud.githubusercontent.com/assets/15685960/18906226/56b586ae-856f-11e6-8577-cf94778a60b0.png)
