### ISSUE TITLE
Unlisted files should be treated like disabled files for storage

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3596]
We currently don't do special treatment for files belonging to unlisted add-ons. We should treat them like disabled add-on files instead and store them in `<File>.guarded_file_path`.

**Comment by diox** [comment]
One way to fix this issue without doing #4649 and #3598:
- Move all unlisted files to a specific `unlisted-files/` directory, that works like the `guarded-addons` one, that is, there are no direct URLs for the files in that directory, you have to go through the django views that do the relevant permission checks, and then use `X-Accel-Redirect` if it's an unlisted file
- Avoid touching unlisted files entirely in code moving disabled files around
- Profit ?!

We'd need a migration to move all the affected files. Perhaps this could be done in 2 separate steps:
- First create a hard link to the new directory for all unlisted files
- Once that is done, activate code looking in the new directory and fire up a task to remove the old files (the hard link becomes the only copy left, in the new directory)

(If we don't have hard links support on our storage backend this could be done with simple copies, it's just slightly more annoying)

**Comment by diox** [comment]
@bqbn do you know if we do have hard links support on the storage used for add-on files?

**Comment by bqbn** [comment]
According to [the doc](http://docs.aws.amazon.com/efs/latest/ug/limits.html), AWS EFS supports up to 175 hard links to a file.

While we're on this topic, any thoughts about replacing the file system with AWS S3? That supposedly can make things like this much easier. Scalability and manageability are better too.
