### ISSUE TITLE
Double space in faq

### ISSUE THREAD

**Issue by zelitomas** [mozilla/addons-server#3601]
Hello, 

while translating AMO on Pontoon I have found a marginal bug - in file src/olympia/pages/templates/pages/faq.html there are double spaces on line 190.

Greetings
Tomáš Zelina

**Comment by EnTeQuAk** [comment]
Thanks for the bug report but I'm going to close this as wontfix for the same reason noted in the related pull request: https://github.com/mozilla/addons-server/pull/3602#issuecomment-249603845 We'll fix this once we touch the actual string to avoid our translators to have to do unneccesary work.
