### ISSUE TITLE
Some addons show as both Jetpack Add-on and Requires Restart

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#3605]
I think the server looks for `package.json`.
An idea would be to look for both `package.json` & `bootstrap.js` to mark as Jetpack

Examples:
https://addons.mozilla.org/en-US/editors/review/buzdid
https://addons.mozilla.org/en-US/editors/review/external-ip-en

**Comment by jvillalobos** [comment]
This is intentional. See https://blog.mozilla.org/addons/2016/08/15/restart-required/
