### ISSUE TITLE
Avoid transactions for GET / HEAD / OPTIONS / TRACE requests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3610]
Because we use [`ATOMIC_REQUESTS` ](https://docs.djangoproject.com/en/1.8/topics/db/transactions/#tying-transactions-to-http-requests) by default, every request to addons-server opens and closes a transaction.

To avoid useless transactions for read-only requests, we use the `non_atomic_requests` decorator in a few places. Unfortunately, because it needs to be applied to the actual view, you can't use it on DRF `ViewSet`s, because the same view function is used for a variety of operations, writes and reads. (For single class-based views decorating `as_view()` works, but that's not the case for viewsets).

This means that, currently, all our APIs that uses ViewSets open useless transactions for read-only requests. We should fix that to avoid perf issues. 

I think the following workaround would work, in a mixin somewhere:

``` python
    @classonlymethod
    def as_view(cls, actions=None, **initkwargs):
        view = super(MyMixin, cls).as_view(actions=actions, **initkwargs)
        return non_atomic_requests(view)

    def dispatch(self, request, *args, **kwargs):
        if request.method in ('DELETE', 'PATCH', 'POST', 'PUT'):
            with atomic():
                return super(MyMixin, self).dispatch(
                    request, *args, **kwargs)
        return super(MyMixin, self).dispatch(request, *args, **kwargs)
```

The positioning of the `atomic()` decorator would be a little different than when `ATOMIC_REQUESTS` does it, but it should not have much impact on our code.

**Edit:** see updates below, we're going to do this through a middleware on all requests, not just the API.

**Comment by diox** [comment]
Note: testing this is annoying, because `atomic()` is disabled by default in tests. You need a `TransactionTestCase`, which means in turn that you need to mock ES yourself, clean-up after each test, etc.

**Comment by EnTeQuAk** [comment]
I think this should work just fine. I thought drf provides something but the only reasonable way would be `method_decorator` and doing it on every view which kinda sucks.

Maybe a middleware is less fiddling and easier testing?

**Comment by diox** [comment]
Sadly, it's a bit tricky to do cleanly in a middleware because you can't decorate/wrap the view in a context manager through a middleware - `process_view()` middleware hook gives you the view, but you can't modify it AFAIK. So you end up having to manually open a transaction before, and close it after, which is a bit janky.

**Comment by EnTeQuAk** [comment]
fair enough, that makes sense and is very hacky.

**Comment by diox** [comment]
[Django's new-style middlewares](https://docs.djangoproject.com/en/1.11/topics/http/middleware/#writing-your-own-middleware), available from Django 1.10 and greater, should allow you to wrap the view in a context manager nicely (just wrap `get_response()`). That's an interesting option...

**Comment by diox** [comment]
We switched to the new `MIDDLEWARE` setting in 3d7ab2abc100bd0ca2b91e066ca1b32ee5a38218 so there is nothing stopping us now.

**Comment by diox** [comment]
My naive approach to implement this failed: I wanted to remove the use of `non_atomic_requests` and `ATOMIC_REQUESTS` entirely, and instead wrap the view in `atomic` inside a new-style middleware.

It doesn't work, I think because the exception is caught & transformed before exiting the atomic context. I'll have to go back to using `ATOMIC_REQUESTS` and find a way to access the view and use `non_atomic_requests` on it when it's a safe request.

**Comment by diox** [comment]
QA:
- Browse around and make sure the site works correctly (It would be nice to test database rollback when a 500 occurs after a write operation, but it's going to be difficult for you to trigger)

**Comment by AlexandraMoga** [comment]
We covered most of the site functionalities during our release testing. Everything seems to be working as expected, so I'm going to mark this issue as verified fixed on AMO stage with FF62, WIn10x64 and Android 8.0.
