### ISSUE TITLE
Disco Pane content update - Oct. 2016

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#3614]
Time for our first Disco Pane content refresher. For the **11 October** push, can we please REMOVE:

- AdBlock Plus
- All three themes (golden butterfly_9, kanagawa wave, marvelous magnolias)

... and REPLACE them with uBlock Origin and three new themes, respectively (note full copy included):

**Block ads** 
with [uBlock Origin by Raymond Hill](https://addons.mozilla.org/firefox/addon/ublock-origin/)
A lightweight and effective ad blocker. uBlock Origin enforces thousands of content filters without chewing up a bunch of memory. 

[themes]

Glitter Closeup by [Candelora](https://addons.mozilla.org/firefox/addon/glitter-closeup/)

Metal Flowers (animated) by [kumyko](https://addons.mozilla.org/firefox/addon/metal-flowers-animated/ )

Live With Music by [gluvel](https://addons.mozilla.org/firefox/addon/live-with-music/)

**Comment by muffinresearch** [comment]
@devaneymoz are you OK with the release on the 13th October?

**Comment by devaneymoz** [comment]
@muffinresearch there's really no hard deadline we're working with other than the folks charged with spreading the word about Test Pilot just launched a campaign to spread the word, and we offered to help. Ideally we dovetail our efforts with broader communication efforts, which began yesterday. 

So that's a long way of saying we can launch this whenever, but ideally asap. What about the 11th October push? 

I'll leave it to you guys to decide. This shouldn't push aside any other high priority work you have. Again, we're doing a favor for a good cause.

**Comment by devaneymoz** [comment]
@muffinresearch Yes the 13th is fine. Thanks!

**Comment by EnTeQuAk** [comment]
I just kept the order in-place and replaced them one by one. Let me know if something should change in that regard.

**Comment by ValentinaPC** [comment]
Themes are replaced, but, instead of Adblock Plus is no "uBlock Origin by Raymond Hill" ... it is going to be until in 13th October, or is "forgotten"?
Please see the video:
![themes](https://cloud.githubusercontent.com/assets/15685960/19158032/e994c170-8bef-11e6-983b-dedfc22b17ee.gif)

**Comment by devaneymoz** [comment]
@ValentinaPC The entire content refresh was intended for next week's push on the 13th (though I incorrectly initially requested the 11th). It is critical that uBlock replace Adblock Plus by the 13th. Are we still on track for that? Thanks!

**Comment by ValentinaPC** [comment]
@devaneymoz : I saw the milestone and the comment regarding the due date for the changes... but seeing that themes were replaced, I thought uBlock was missed.

**Comment by muffinresearch** [comment]
@ValentinaPC uBlock Origin was included in the patch. However the problem might be that the data doesn't exist on -dev which is why it's not appearing in the API data.

**Comment by EnTeQuAk** [comment]
Yeah, so regarding testing this. It's almost impossible unfortunately. We have to use the ids from production to configure this and those aren't on -dev and not on -stage and especially are not the add-ons we'd expect. Guess we'll have to trust me :(

**Comment by EnTeQuAk** [comment]
@devaneymoz we're on track, the changes already got merged and everything - the questions here are only regarding testing them which isn't that easy.

**Comment by ValentinaPC** [comment]
Verified this on AMO-prod using FF49(Win 7)
All add-ons and themes are changed as suggested.
Posftix screenshot:
![disco](https://cloud.githubusercontent.com/assets/15685960/19429162/c5ebe93c-9456-11e6-8486-0740164340ad.png)
