### ISSUE TITLE
Homepage carousel promotion: Test Pilot

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#3615]
A quick turnaround request, I realize, but with the Test Pilot program launching this week, we'd like to help promote it on AMO by featuring a link to it from the carousel on **Tuesday , Oct. 4**. 

Here is an example of what we'd like the finished carousel image to look like (including copy and button CTA):

https://cl.ly/3e3i151v0I1m

Is it possible for engineering to approximate this graphical copy style? 

Here's the background image.
![amo-banner_testpilot_960x271](https://cloud.githubusercontent.com/assets/8496249/18857241/258532d6-8417-11e6-8acd-e7970bbdeeaa.png)

Clicking the [GET STARTED] button directs you here:
https://testpilot.firefox.com/

**Comment by muffinresearch** [comment]
Following an irc conversation, next Thursday's push is fine.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
Postfix screenshot: 
![2016-10-05_1026](https://cloud.githubusercontent.com/assets/15685960/19105146/27ed2032-8ae9-11e6-8380-26f5380cf429.png)
