### ISSUE TITLE
Reviewing: Oops! We had an error

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#3616]
For the last 2 days, I have been getting an error when trying to post the review for an addon. 
Comment works.

> Oops! We had an error.
> We'll get to fixing that soon.
> You can try refreshing the page, or head back to the Add-ons homepage.

Here is the addon:
`https://addons.mozilla.org/en-US/editors/review/magneton`

**Comment by EnTeQuAk** [comment]
Closing this in favor of https://github.com/mozilla/addons/issues/228 - which is also handled and fixed in bugzilla.
