### ISSUE TITLE
as

### ISSUE THREAD

**Issue by alongabay** [mozilla/addons-server#3620]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
i cant download it
### What did you expect to happen?
it will download
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
Hi, please could you provide more details so we can understand what the issue is?

**Comment by EnTeQuAk** [comment]
Closing as invalid, if you have more details on the issue please feel free to reopen anytime.
