### ISSUE TITLE
Typo in source string

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozilla/addons-server#3624]
### Describe the problem and steps to reproduce it:
There is a repeated "unsubscribe" in the source of unsubscribe template: https://github.com/mozilla/addons-server/blob/master/src/olympia/users/templates/users/unsubscribe.html#L31-L32

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
Postfix screenshot: 
![unsubscribe_001](https://cloud.githubusercontent.com/assets/15685960/19153698/3fe4dd4a-8be0-11e6-92ae-695627df449f.png)
