### ISSUE TITLE
Trying to switch add-on from listed to unlisted status results in an Oops error message

### ISSUE THREAD

**Issue by oliveoyl** [mozilla/addons-server#3627]
### What happened?
I submitted an add-on for approval for public listing but I now need to switch it to unlisted. 

I tried to change the radio button selection from Listed to Unlisted:

<img width="814" alt="mozillaunlisted" src="https://cloud.githubusercontent.com/assets/20339642/18891054/f1122052-8503-11e6-8b28-4f0bc6e97ce7.png">

But I get an error:

<img width="998" alt="mozillaoops" src="https://cloud.githubusercontent.com/assets/20339642/18891053/f111620c-8503-11e6-97a7-4c5b1b73259d.png">

### What did you expect to happen?
I expected to be able to switch the status for the existing add-on that I submitted.

### Anything else we should know?
I tried it multiple times over a couple of days but to no avail. Philipp Kewisch recommended that I submit a bug here.

**Comment by ValentinaPC** [comment]
This issue was tracked in #3519 .
Thanks for submitting!

**Comment by kewisch** [comment]
Thanks for reporting. I'm closing this in favor of mentioned other issue.
