### ISSUE TITLE
Comments from Editor Tools add-on review page are not displayed in Review history section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3631]
STR:
1. Load Review page for any add-on and leave a "Comment"
2. Load Manage Status & Versions page for that add-on i.e https://addons-dev.allizom.org/en-US/developers/addon/word-test-vrs/versions
3. Click "Review history" and observe the comment

ER:
The comment is listed in the "Review history" page

AR:
The comment is not listed in the "Review history" page

Notes/Issues:
If a "Super review" or a "Request more information" options are made, they are listed in the Review history section from Dev Hub.
Verified on Ff49(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshots for this issue: 
![comm](https://cloud.githubusercontent.com/assets/15685960/18910912/c6d5f668-8582-11e6-8be3-1be1f246552b.png)
![no_comm](https://cloud.githubusercontent.com/assets/15685960/18910913/c6d71624-8582-11e6-9606-befe709a0a70.png)

Relates to https://github.com/mozilla/addons/issues/152

**Comment by jvillalobos** [comment]
Comments are private to reviewers. They shouldn't be displayed to the developer.

There seems to be a different bug here, though, and that is that the text of a super review shouldn't show up. Either we shouldn't show that text, or we shouldn't show the super review entry at all.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7):
-> Only "More information requested" info is listed in "Manage Status & Versions page", under "Review history" as you can see in the following screenshots: 
![ms v](https://cloud.githubusercontent.com/assets/15685960/18956349/d1bdbe3a-8663-11e6-91e2-006d1aa2e051.png)
![review_page](https://cloud.githubusercontent.com/assets/15685960/18956348/d1b4c3fc-8663-11e6-8be1-302cb7eb58f3.png)
