### ISSUE TITLE
"Return to the DevHub homepage" element is too large

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3633]
STR:
1. Load Dev Hub homepage https://addons.mozilla.org/en-US/developers/
2. Observe the dimension of the "Add-on Developer Hub" header element

ER:
"Return to the DevHub homepage" message is displayed at hover.

AR:
The action can be made also if we hover near the username link (and can easily be accessed by mistake).

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue: 
![hover_001](https://cloud.githubusercontent.com/assets/15685960/18918245/d2df01fa-85a2-11e6-847a-2d5604da3d16.png)

**Comment by EnTeQuAk** [comment]
Closing this as it'll all go away with our work on https://github.com/mozilla/addons-frontend/issues/1021
