### ISSUE TITLE
Implement notification and shut down switch for add-on submissions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3634]
We need an admin tool that lets us notify developers about any issues around add-on submission, and also shut down submissions if needed. This allows us to close submissions if a major bug surfaces or we don't want developers to submit add-ons during a period of time reviewers generally won't be available (like the week between Christmas and Jan 1st).

I picture the admin tool like an email autoresponder tool, where you set up the start date, end date, and a message (required). Shutting down listed and unlisted submissions would be optional checkboxes. (After a discussion with @kewisch and @wagnerand, there were some concerns about shutting down submissions during the whole end of year week, so we'll want to play around with that a bit.)

The messaging and optional blocking would happen in the upload step, both for new submissions and update submissions (note that they are being changed in #3465).

**Comment by brampitoyo** [comment]
* We want to show notification on the submission/upload step of the developer hub (“Starting from x to y, we’re going to take a break, so you’re going to experience some delays”). This won’t block developers from uploading file.
* We want the ability to completely shut submission down and block people from uploading file.

**Comment by Leif-W** [comment]
Good idea, to have the ability to shot down and post a message, in the event of a critical need to fix a bug.

Bad idea, to shut down the store on a holiday which not everyone celebrates.  Making a decision in a vacuum with the societal bias that everyone will be doing the same thing - even if MOST will be - is a poor way to make a decision.  If you shut down for this holiday, and why not that other holiday, it sets a clear pattern of bias.  Then shut down for two or three or four holidays?  When does it end?  What metric do you use to determine that one person gets to decide for the rest?  If 85% will be away?  90%?  99%?  Even if it's 100% today, and all days in the past, who is to say it will always be that way?

I think a compromise would be to simply post a message that submissions will be allowed, but there will naturally be fewer reviewers available as a result of holidays.  However, to shut down entirely on a holiday would prevent what few reviewers may be available, from doing anything.  This benefits nobody.

What benefit is there, really, in shutting down?  The reviewers just get slammed the following week with a high number of submissions, or slammed the week before shutdown with everyone trying to get in line.  Either way, the net effect is made worse by closing?  The only motivation for closing is to enforce a cultural norm onto any and all dissenters, not for any practical benefit, which is the epitome of bias, and a poor foundation for a decision making process.

**Comment by wagnerand** [comment]
This is purely about implementing the feature into our software. It has nothing to do with actual decisions on when and how we are going to use it.

Although your concerns are duly noted. Some of us had similar ones, but again, discussing when and how we are going to use this feature is not part of this _issue_.

Feel free to start a discussion [in our forums](https://mail.mozilla.org/listinfo/dev-addons). However, note that we are already aware of the concerns you raised and **nothing has been decided yet** regarding the usage of this feature.

**Comment by Leif-W** [comment]
Appreciated.  Sorry if this was the wrong place for discussion, I just happened across this first, as I am trying to familiarize myself with the general direction of things, and upcoming decisions, and saw no discussion of concerns in this place, so thought I would make note of them here, if someone else, like me, had found this first and not the discussions elsewhere.

But as I initially said first and foremost, the feature itself is a good idea.

**Comment by brampitoyo** [comment]
Here’s what the notification would look like on the **new add-on** flow:

![add-new-addon-notification](https://cloud.githubusercontent.com/assets/51007/20087621/58b5c8fe-a5ce-11e6-9513-96571ab2e9c4.png)

And on the **new version** flow:

![add-new-version-notification](https://cloud.githubusercontent.com/assets/51007/20087631/652d6d6c-a5ce-11e6-935e-b9f039f2dbad.png)

Thoughts?

**Comment by wagnerand** [comment]
@brampitoyo what would the page look like for submissions are closed vs not closed?

**Comment by brampitoyo** [comment]
@wagnerand Since you can still submit your files – they just won’t be reviewed during the time period – the page will look exactly the same other than the addition of the yellow flag.

Another thing I’ve thought of is that we can disable the “Submit” and “Upload” buttons entirely, and when you mouse over it, we’ll show a tooltip that says that they’re closed.

![add-new-addon-disabled](https://cloud.githubusercontent.com/assets/51007/20333018/e81bca80-ac03-11e6-944c-bda190a9cf80.png)
![add-new-version-disabled](https://cloud.githubusercontent.com/assets/51007/20333020/ecd8c2c6-ac03-11e6-8d71-b43dc62b3f19.png)

The downside of this approach is that you can still access the submission URL by manually typing it. In this case, we’ll have to block users from proceeding further, like so:

![add-new-addon-page-closed](https://cloud.githubusercontent.com/assets/51007/20333036/0bc02756-ac04-11e6-9063-732c87b4a610.png)

I think that this hard-line approach is harder to do than if we are to put up a notification flag but don’t actually block you from submitting a file? Another thing to consider is that there might be some developers who would still like to upload their files even though the submission is closed. Maybe they’d like it to be reviewed first thing in the next year. Maybe they’re just finished fixing an issue as the last thing they do this year. There can be other reasons, too.

**Comment by wagnerand** [comment]
@brampitoyo I was wondering whether the background color of the box should be different if submissions are closed.

Disabling the buttons with the 'hover' message is a good idea!

**Comment by jvillalobos** [comment]
I'd like to minimize the touch points for this change, so I think we should only show the messaging in the submission flow, not try to block all the paths that lead to it. Also note that this would be implemented on top of the listed/unlisted changes, so the Add Version / Add File popups would no longer exist.

The contents of the warning box would be entirely defined by us, so the clarity of the message would be up to whomever adds the message. I think it's fine to use the same look (the yellow background) both when it's just a warning or an actual shutdown.

**Comment by brampitoyo** [comment]
@wagnerand wrote:

> @brampitoyo I was wondering whether the background color of the box should be different if submissions are closed.

Ah. I didn’t realise that you were asking about the difference between a warning flag vs. a shutdown flag. For the sake of consistency, I think they both should look the same and also use the same shade of yellow that we already use for notifications today. But if you’d like it to stand out, it would be fine to use a light red background. I just worry about colour fatigue, I suppose.

@jvillalobos wrote:

> […] this would be implemented on top of the listed/unlisted changes, so the Add Version / Add File popups would no longer exist.

If this is the case, then what would happen when I click “Upload New Version”? Do we not show any popup?

**Comment by jvillalobos** [comment]
No, "Upload New Version" should take you to the new flow, and those popups would be gone.

**Comment by brampitoyo** [comment]
> "Upload New Version" should take you to the new flow […]

Of course I had forgotten that we’re implementing an updated “Upload New Version” flow. Yes. In that case, this new flow would have the same flag as the one found on “Submit a New Add-on”.

**Comment by brampitoyo** [comment]
In addition to posting a yellow flag on top of the upload/submit UI, we should also consider posting a blog post (if we haven’t already planned on doing this), as in this example:

https://developer.apple.com/news/?id=11292016a

**Comment by diox** [comment]
How would this system handle translations of the notification message(s) ?

**Comment by wagnerand** [comment]
My personal opinion would be that we don't need to translate these messages. Pinging @jvillalobos...

**Comment by jvillalobos** [comment]
> How would this system handle translations of the notification message(s) ?

While making them localizable is ideal, it's not a requirement. There are various other communication channels we share with developers that are English-only (notably, add-on reviews).

I don't know if we have any capabilities on AMO to translate strings dynamically. I mean being able to set a string from the admin UI and then having localizers translate it when/if they have the time, and fall back to English if no translation is available.

**Comment by diox** [comment]
> I don't know if we have any capabilities on AMO to translate strings dynamically. I mean being able to set a string from the admin UI and then having localizers translate it when/if they have the time, and fall back to English if no translation is available

There used to be a convoluted system for this for categories, but it was removed a while ago.

@wagnerand was suggesting to implement this notification system to do the legacy submission restriction warning (#4233). Doing that would mean this warning would not be translated, is that OK?

**Comment by jvillalobos** [comment]
I think that's okay.

**Comment by brampitoyo** [comment]
I believe we’ve completed the UI design for this feature, so I’m taking the label off. Feel free to put it back on if there’s anything else that we should work on!

**Comment by muffinresearch** [comment]
@jvillalobos do we still need this?

**Comment by jvillalobos** [comment]
Yes. We currently have a notification mechanism, but we don't have a way to turn off submissions. We might still want this for end of year operations, or if we find ourselves being flooded by malicious actors.

**Comment by kplotnik** [comment]
@wagnerand  This issue didn't see any movement in over 4 year. There's a duplicate more recemt issue: #14387

**Comment by wagnerand** [comment]
And yet it comes up every towards every end of year and then deemed too late for that year, with the claim that we'd look into it for the next year.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-143
