### ISSUE TITLE
Email is missing from account settings page

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3636]
The email field is not editable but it should still be shown on the account settings page.

![prod](http://content.screencast.com/users/ValentinaClara/folders/Jing/media/e6440a75-ae5d-464d-8ab4-51f0cc2b84cf/2016-09-28_1800.png)
> Good

![stage](http://content.screencast.com/users/ValentinaClara/folders/Jing/media/4df13593-ccf5-4e9d-8a88-412202331c86/2016-09-28_1848.png)
> Less good

**Comment by mstriemer** [comment]
The email field should be present on the account settings page but not editable. An admin should be able to edit an email address when viewing the user and clicking "Manage User".

**Comment by mstriemer** [comment]
Fixed by https://github.com/mozilla/addons-server/commit/2914d6773639f983f6a7148196ff364381ac2e2a, referenced the wrong issue there, oops.

**Comment by ValentinaPC** [comment]
@mstriemer 
E-mail is hiding and showing up on its own, while refreshing "My Profile->Edit profile" page
Page before and after refresh:
![myprofile-editprofile](https://cloud.githubusercontent.com/assets/15685960/18944880/70547388-8630-11e6-9d89-547f017e2c4d.png)
![myprof-editprofile-refresh](https://cloud.githubusercontent.com/assets/15685960/18944887/77c237c2-8630-11e6-9ae0-a34cb0c7e32c.png)

This is happening in "My Profile->Manage user" page:
Page before and after refresh:
![admin-before](https://cloud.githubusercontent.com/assets/15685960/18944865/61bb2a4c-8630-11e6-8826-958a5e0489f2.png)
![admin-after](https://cloud.githubusercontent.com/assets/15685960/18944873/65ccc578-8630-11e6-8fcf-bc70d64a61ef.png)

What is happening?
I've used a clean profile of FF49(Win 7) and AMO-dev.

**Comment by mstriemer** [comment]
I was seeing the same thing on -dev. I think that server might have something weird going on.

My stage deployment yesterday failed but it worked today, so it appears to be working for me at https://addons.allizom.org/en-US/firefox/users/edit.

**Comment by ValentinaPC** [comment]
Works as expected on AMO-stage FF49(Win 7).
Marking it as verified-fixed.
Postfix screenshots:
![1](https://cloud.githubusercontent.com/assets/15685960/18957437/b90ca528-8667-11e6-9ee4-238c12c6c95d.png)
![2](https://cloud.githubusercontent.com/assets/15685960/18957438/b93b119c-8667-11e6-95e3-edb3da9a8e04.png)
