### ISSUE TITLE
Awaiting add-on version cannot be opened if it was "hidden" before

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3639]
STR:
1. Submit an add-on without approving it on AMO-stage i.e. https://addons.allizom.org/en-US/developers/addon/smoothwheel-stage4/versions
2. Change its status by clicking the "Hidden" option
3. Change its status back to "Listed"
4. Download the add-on version

ER:
The version is downloaded and can be accessed.

AR:
The version is downloaded but cannot be accessed.

Notes/Issues:
The version can be opened if we download it when add-on is in the Hidden state.
Also if the link of the version from manage version page is clicked: a 404 page is returned.
Verified on FF49(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshots for this issue: 
- after download
  ![damaged](https://cloud.githubusercontent.com/assets/15685960/18945399/0e00b158-8633-11e6-8baa-d78b942611c1.png)
- at click
  ![atclick](https://cloud.githubusercontent.com/assets/15685960/18945610/ff0ae44c-8633-11e6-995b-743f367fb1c6.png)

**Comment by diox** [comment]
Duplicate (different STR, but same core issue) of https://github.com/mozilla/addons/issues/324

**Comment by ValentinaPC** [comment]
@diox : A duplicate bug it suppose to be logged after the initial bug.

**Comment by diox** [comment]
Yes, but the other one has more info about what's going on internally because that's the one I saw first :)

**Comment by ValentinaPC** [comment]
Yeah :) Fixing it is our common goal.
