### ISSUE TITLE
Tags are causing layout issues in add-on details page if no "Other by..." and "Part of these Collections" sections

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3640]
STR:
1. Load details page for an add-on with tags and no "Other by..." and "Part of these Collections" sections i.e. 
   https://addons.allizom.org/en-US/firefox/addon/pics9/   
   https://addons.allizom.org/en-US/firefox/addon/pcm-tools/?src=ss  
2. Go to the end of the page and observe "Tags" section

ER:
Tags are aligned with the rest of the page.

AR:
Tags are lower than the rest of the page.

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshots for this issue:
![2](https://cloud.githubusercontent.com/assets/15685960/18946595/4378aa70-8638-11e6-8cfe-c63d60f29a28.png)
![tags](https://cloud.githubusercontent.com/assets/15685960/18946594/4373cda2-8638-11e6-8e6d-bc67e4c68316.png)

**Comment by muffinresearch** [comment]
Not sure I understand this bug. Are you saying the sidebar on the right shouldn't be longer than the main content or something else?

**Comment by ValentinaPC** [comment]
Yes, I was talking about the alignment.

**Comment by muffinresearch** [comment]
@ValentinaPC Ok I don't think there's anything we can fix here in that case.
