### ISSUE TITLE
Show super-review request on developer page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3642]
#3641 hides the super-review request on the developer page entirely. However, we should show the event itself (without the message body) on the developer page as we are sending out an email when an add-on gets admin flagged and so that should be documented on the review activity page as well.

**Comment by ValentinaPC** [comment]
Message listed for a super review in Dev Hub:
![super](https://cloud.githubusercontent.com/assets/15685960/19271528/ba17be8e-8fcd-11e6-894c-11be1e2748d4.png)
But...if we make a "Request more information" action in Editor Tools - add-on review page, there is an issue: the super review action is made again, and listed.
Verified on AMO-dev FF49(Win 7).
Screenshots for this issue:
![2016-10-11_1611](https://cloud.githubusercontent.com/assets/15685960/19271578/f329dd38-8fcd-11e6-9ad0-27323024164a.png)
![editor_tools](https://cloud.githubusercontent.com/assets/15685960/19271579/f32ddbd6-8fcd-11e6-89aa-1e597c96b51d.png)

**Comment by eviljeff** [comment]
Typically the super review would happen during a review so there would be an outcome and it would be cleared because of the review resolution.   
In the case where it's been flagged and cleared outside of a review... yeah we don't notify the developer at all (and the email/messaging is confusing, because it talks about a review).  

@wagnerand if you think this is a worthwhile fic can you open an issue for it?  (It's not really high priority as its edgecasey and existing functionality really)

**Comment by wagnerand** [comment]
@eviljeff can you clarify the current behavior?
If an add-on is *not* pending review and someone admin-flags it:
1) Do we send an email?
2) Do we show a note in the activity view?

**Comment by wagnerand** [comment]
Also, I think @ValentinaPC was talking about the line wrap, breaking one word in half.

**Comment by eviljeff** [comment]
haha, okay.  Well "checked" being split is due to #3392 - words are split to wrap lines - can't have it both ways alas.

**Comment by eviljeff** [comment]
As for current behaviour, afaik there is no differentiation between an add-on awaiting review and one not in terms of sending an email, etc.

**Comment by ValentinaPC** [comment]
"can't have it both ways"  - for sure :dancing_women:

**Comment by ValentinaPC** [comment]
A "super-review request" on the developer page is shown as an event, without the message, but with a generic one.
Comments are not displayed in Dev Hub page.
"More information requested" is displayed entirely.
![devhub](https://cloud.githubusercontent.com/assets/15685960/19550080/6ff4dc08-96b0-11e6-9283-02fd5bb76126.png)
![editortools](https://cloud.githubusercontent.com/assets/15685960/19550081/700ef480-96b0-11e6-91cb-5d90d6403bb2.png)
