### ISSUE TITLE
A 404 is returned when trying to change the GUID from Admin Settings 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3644]
Steps to reproduce:
1.Go to any webextension edit listing page 
2.Try to modify the Add-on GUID from Admin Settings

Expected results:
Add-on GUID is modified

Actual results:
Waiting spinning wheel continuously displayed and a 404 is returned in the console

Please see a photo of the issue: 
![changeid](https://cloud.githubusercontent.com/assets/1583842/18960052/03791110-8671-11e6-8000-8111f7e78e75.png)

**Comment by EnTeQuAk** [comment]
Do we actually want to keep this "feature" for WebExtensions too? In Marketplace for example all add-on metadata is being fetched from the addon submission files which we should do eventually too imho.

**Comment by vcarciu** [comment]
Please note that we cant change the add-on type too (same behavior , but it will return a 304)

**Comment by jvillalobos** [comment]
The GUID and type are obtained from the file. This is an admin override. I don't remember the last time we changed the GUID, but I have had to manually change the type of some add-ons in the past.

**Comment by EnTeQuAk** [comment]
From our meeting: We're simply going to remove the field to change the GUID since the side-effects are kinda unpredictable and we won't need that.

**Comment by vcarciu** [comment]
Verified as fixed : 
![idchange](https://cloud.githubusercontent.com/assets/1583842/19157967/b3158594-8bef-11e6-80ac-a22ba70043c9.png)
