### ISSUE TITLE
"Not available for Firefox ..." label is causing layout issues in Featured section of any add-on category

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3645]
For this issue to reproduce, an unavailable add-on for Firefox browser must be listed in Featured section from add-on categories.

STR:
1. Hover over the unavailable add-on from Featured section 
2. Observe the unavailability label and the author name

ER:
There are no layout issues.

AR:
The label is displayed between "by" and add-on author.

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot from production: 
![2016-09-30_1005](https://cloud.githubusercontent.com/assets/15685960/18983861/f14bc8de-86f7-11e6-85ca-330279e912f6.png)

**Comment by eviljeff** [comment]
mentor @tofumatt
If this is your first bug please look at https://wiki.mozilla.org/Add-ons/Contribute/Code

The 'Not available...' box should be above and before the "by __author name__"

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
Postfix screenshot: 
![2016-10-10_1735](https://cloud.githubusercontent.com/assets/15685960/19239938/e4ab06d2-8f10-11e6-9ffc-023495479a02.png)
