### ISSUE TITLE
"Normal" add-ons are listed in the Featured section of a category listing page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3646]
STR:
1. Load https://addons.mozilla.org/en-US/firefox/extensions/shopping/ page
2. Observe the add-ons listed in the Featured category
3. Access PriceBlink - Automatic Price Comparison & Coupons add-on page: https://addons.mozilla.org/en-US/firefox/addon/priceblink/?src=cb-dl-featured

ER:
The add-on listed in the Featured section has a "featured" label.

AR:
The add-on is listed in the Featured section but does not have a "featured" label.

Notes/Issues:
Verified on FF49(Win 7). 
Reproducing in other categories too.
Ex:
1. https://addons.mozilla.org/en-US/firefox/extensions/feeds-news-blogging/ - StumbleUpon add-on
2. https://addons.mozilla.org/en-US/firefox/extensions/social-communication/ - ScribeFire Classic add-on
Video and screenshots for this issue:
![nolabel](https://cloud.githubusercontent.com/assets/15685960/18985125/08d1dd7a-86ff-11e6-80d8-330fc5c1b4f7.gif)
![1](https://cloud.githubusercontent.com/assets/15685960/18985134/10048f66-86ff-11e6-81ef-962bdcf48b4d.png)
![no](https://cloud.githubusercontent.com/assets/15685960/18985135/10342e60-86ff-11e6-8f9f-416a9184ba42.png)

**Comment by devaneymoz** [comment]
Really nice catch @ValentinaPC ! I also found similar issues in other categories...

- Download Management (Update Notifier is not a featured add-on)

- Alerts & Updates (ReminderFox)

- Bookmarks (NewsFox)

- Feeds, News & Blogging (NewsFox)

**Comment by diox** [comment]
The bug here is that when we look at featured add-ons for a category, we consider the language but don't care about the application, so we end up seeing results from other applications. All those add-ons are actually featured for another application than Firefox:
- StumbleUpon, ScribeFire Classic, ReminderFox and NewsFox are featured for Seamonkey
- Update Notifier is featured for Sunbird

etc (some could be featured for Thunderbird or Firefox for Android, or even Fennec)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
All add-ons listed in the featured section of every category, have a "featured" label.
Add-ons that are featured for other apps (like Thunderbird, Seamonkey, etc) are not listed in the featured section of Firefox app.

**Comment by vcarciu** [comment]
This is still reproducible on prod now : 
![reminderfox](https://cloud.githubusercontent.com/assets/1583842/19388197/fe47ad8e-9226-11e6-9ebd-0fd7005c942b.gif)

**Comment by diox** [comment]
It hasn't been deployed to prod yet (it didn't make the tag).
