### ISSUE TITLE
"Review history" section is broken after changing the Username from Account Settings

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3647]
STR:
1. Sign in to AMO-prod https://addons.mozilla.org/en-US/firefox/
2. Go to "Account Settings" and change your "Username" https://addons-dev.allizom.org/en-US/firefox/users/edit
3. Save changes
4. Go to "Manage Status & Versions" page for any add-on
5. Click on "Review history" link

ER:
Some reviews are listed.

AR:
The error message "We had a problem retrieving review notes /api/v3/addons/addon/492428/versions/1529143/reviewnotes/, UNAUTHORIZED, {"detail":"Invalid signature."}" is displayed.

Notes/Issues:
Issue is reproducing only if the "Username" is changed.
Issue is "fixed" after sign out - sign in.
Verified on FF49(Win 7). 
Screenshot for this issue: 
![2016-09-30_1156](https://cloud.githubusercontent.com/assets/15685960/18986346/0c68c8a8-8705-11e6-8631-dabededda1d0.png)

**Comment by eviljeff** [comment]
For some reason changing the username (or perhaps anything on the user profile page?) is seemingly invalidating the auth in jwt_api_auth_token cookie.
@mstriemer do you know why?

**Comment by ValentinaPC** [comment]
@eviljeff : from what I've seen, only changing the "Username", interferes.

**Comment by mstriemer** [comment]
I'm not sure why this would happen. I don't see anything in the jwt code about usernames

**Comment by eviljeff** [comment]
This is problem with jwt tokens using `username` in them (and then becoming invalid when the username changes).

**Comment by mstriemer** [comment]
I think we need to override the `authenticate_credentials` method in `olympia.api.authentication.JSONWebTokenAuthentication`. The [default implementation](https://github.com/GetBlimp/django-rest-framework-jwt/blob/00f76e44da4a2b62075696cce1f583dd735ff197/rest_framework_jwt/authentication.py#L52) finds the user by username.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
Postfix video: 
![inco](https://cloud.githubusercontent.com/assets/15685960/19145663/a9d7d4d2-8bb8-11e6-9094-37f4bbf17750.gif)
Changing the username field does not affect the "Review history" section anymore.
