### ISSUE TITLE
Maximum-length comment from "Make a Contribution" window is not parsed correctly

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3648]
STR:
1. Load details page for an add-on with contributions available i.e. https://addons.mozilla.org/en-US/firefox/addon/firebug/?src=hp-dl-mostpopular
2. Click on "Contribute" button and leave a comment over 255 chars (on multiple rows)
3. Click "Make contribution" button

ER:
User is not let to type more than 255 chars.

AR:
"Invalid data" message is displayed.

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing on all AMO servers.
Screenshot for this issue:
![contrib](https://cloud.githubusercontent.com/assets/15685960/18992435/fcfc6aa6-8726-11e6-88f9-d0113f2b68e9.png)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF49(Win 7) and the issue seems to still reproduce:
Screencast: 
![contrib](https://cloud.githubusercontent.com/assets/15685960/19635858/1f3ca7fc-99ce-11e6-8b16-6dc1741b2894.gif)

**Comment by EnTeQuAk** [comment]
The actual bug here apparently is that newlines are invalid and lead to "invalid data" and it has nothing to do with the amount of characters.

**Comment by EnTeQuAk** [comment]
I an going to close this, it's definetly an edge-case and contributions might change in the very near future too.
