### ISSUE TITLE
[RTL] Profile photo is not correctly aligned in account settings

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3651]
Steps to reproduce:
1.Open amo-dev in Arabic and selecte Account Settings
2.Observe the profile photo

Expected results:
Photo should be RTL aligned

Actual results:
Photo is centered 

Please see photo of the issue:
![imageprofile](https://cloud.githubusercontent.com/assets/1583842/18996876/c5171366-873a-11e6-8947-c8d439f60bfa.png)

**Comment by eviljeff** [comment]
mentor @tofumatt 
If this is your first bug please look at https://wiki.mozilla.org/Add-ons/Contribute/Code

**Comment by vijeth-aradhya** [comment]
@eviljeff I want to try to work on this issue. Can you assign it to me?

**Comment by tofumatt** [comment]
We can’t assign issues to people outside the Mozilla organisation, but
please do work on this and push a PR for review :-)

**Comment by vcarciu** [comment]
Verified as fixed : 
![rtlaccountimage](https://cloud.githubusercontent.com/assets/1583842/19384098/33f0d652-9210-11e6-9dd6-2de5613abecf.png)
