### ISSUE TITLE
Spece Fantasy

### ISSUE THREAD

**Issue by ratajs** [mozilla/addons-server#3657]
I click to link https://addons.mozilla.org/firefox/addon/space-fantasy/ in about:addons, but it throw 404.

**Comment by tofumatt** [comment]
Looks like that add-on has been unlisted so it won't show anymore. If there's any way to contact the developer about it maybe @jvillalobos or another review team person would know, but otherwise we can't help much as the add-on developer decided to unlist their add-on.

Sorry about that!
