### ISSUE TITLE
improve / fix bulk validation

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3666]
https://github.com/mozilla/addons-server/pull/3197 changed and rewrote a few parts of the bulk validation overview. This is a follow-up to fix some outstanding issues required for the next validation run.

- [x] Only show compatibility errors
- [x] Fix 500 error on detail page

**Comment by madalincm** [comment]
Please add some steps to reproduce or if no qa is needed please add the "no qa needed" label.

**Comment by wagnerand** [comment]
As this lands very soon, I will test this myself, as I am the main (and likely only) user for this internal tool.
