### ISSUE TITLE
"Please fill out this field" warning is not hidden when scrolling through Account Settings page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3671]
Steps to reproduce:
1.Login to MP-dev and with an admin account and select My Profile
2.Click the Manage User button
3.Scroll down and select Update Account 
4.Scroll up and observe the "Please fill out this field" warning from "Reason for change section"

Expected results:
The "Please fill out this field" warning should disappear when scrolling up

Actual results:
The "Please fill out this field" warning is still present while scrolling up

Please see a video for the issue:
![scroll](https://cloud.githubusercontent.com/assets/1583842/19079397/29fffa8a-8a5c-11e6-83ba-1ea6a3065a93.gif)

**Comment by ValentinaPC** [comment]
This issue is happening for "Homepage" field also (https://addons.mozilla.org/en-US/firefox/users/edit), while not entering a valid URL.
Verified on AMO-prod FF50.0.2(Win 7)
Video: 
![url](https://cloud.githubusercontent.com/assets/15685960/20878948/1b85da8e-bada-11e6-9f33-20713dd06bad.gif)

**Comment by eviljeff** [comment]
it's a bug but really quite minor so marking as wontfix
