### ISSUE TITLE
Include user ID in review object API response

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3672]
Many API requests respond with a [review object](http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#review-detail-object). This object looks like `{username: '...', url: '...'}`. Can you add a `user_id` to it? Also, could you document this object?

Supports the UI review flow: https://github.com/mozilla/addons-frontend/issues/927

**Comment by kumar303** [comment]
Until we get this we have to either make additional API requests to get the full user object or rely on `username` for a key into saved review data.

**Comment by diox** [comment]
The property should probably just be called `id` if it's part of the user object, right ?

**Comment by kumar303** [comment]
whoops, correct

**Comment by kumar303** [comment]
It would be great to also get a user ID in this response: http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#get--api-v3-addons-addon-(int-id|string-slug|string-guid)-reviews-(int-id)- Maybe it's all part of the same serializer?

**Comment by diox** [comment]
It is: it's `BaseUserSerializer`.
