### ISSUE TITLE
Overriding the platform checkboxes on submission leads to unsigned add-on

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3673]
The problems are described in [this discourse thread](https://discourse.mozilla-community.org/t/problem-with-addon-not-being-signed-at-amo/10194/10). There are two:
1. Some add-ons with incorrect manifest information pass validation, but (correctly) disable the platform selection checkboxes.
2. Developers can re-enable the checkboxes and still submit the add-on.

When the add-on is forced through this process, it isn't signed, but everything on the site indicates it was signed.

To fix (1), we should display a clear error message explaining why the checkboxes are disabled. To fix (2), we need to make sure the submission process can't continue even when the page is tampered with.

**Comment by muffinresearch** [comment]
Duplicating this one to: https://github.com/mozilla/addons-server/issues/1448
