### ISSUE TITLE
Add "All Rights Reserved" as a predefined license option for add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3674]
The current source code license selection widget shows a number of open/free/whatever source licenses, and then an "Other" option where you add custom license text. We should have an "All Rights Reserved" license to choose from as well, since many add-ons are closed source.

**Comment by eviljeff** [comment]
Please feel free to contribute to this bug, but it's a little involved, likely involving making changes to the django models and an sql db migration.  Ask for more details.

**Comment by harry-7** [comment]
I would like to take up this task. I would be glad if someone can provide some details about this . Thanks :)

**Comment by eviljeff** [comment]
@harry-7 great 👍 
I implemented some changes recently which should make this easier (in theory!  you will need to locally test to make sure it works)

Should just be a matter of adding the license to src/olympia/constants/licenses.py and then adding a migration that inserts it into the DB similar to src/olympia/migrations/981-add-creative-commons-licenses.sql 

your license class should be:
 some_rights = False
 creative_commons = False
 builtin = <18 I think is unused - needs to match the migration>

**Comment by harry-7** [comment]
@eviljeff  there is already an all right reserved class defined  [here](https://github.com/mozilla/addons-server/blob/7530d64257bbe4185cb2a9df276283afd259c880/src/olympia/constants/licenses.py#L13)
Should I add a similar class again ?

**Comment by eviljeff** [comment]
Yeah, that one is for creative commons licenses (used for Themes).

**Comment by harry-7** [comment]
@eviljeff I created a pull requests. I think it solves this issue. Please check once and let me know if any changes are required :)

**Comment by vcarciu** [comment]
@eviljeff @jvillalobos The option was correctly added, but when viewing the listing page for a webextension submitted with "All Rights Reserved" license we can see that there is no link under License section. Is this ok?
![nolicence](https://user-images.githubusercontent.com/1583842/32795710-3dbf6ab6-c975-11e7-82d2-7a2c23064400.png)

**Comment by jvillalobos** [comment]
Nope, that's not expected behavior.

**Comment by eviljeff** [comment]
yeah, that's my bad.  Doesn't work properly with the API (kind of a problem these days)

**Comment by eviljeff** [comment]
It'll have to be either fixed in some way or reverted before the deployment on Thursday.  I'll take a look.

**Comment by harry-7** [comment]
@eviljeff  I did not a url field for it. Could it be the reason for this behaviour ?

**Comment by eviljeff** [comment]
No it's that the API returns the database name directly rather than using the constant you defined.

**Comment by vcarciu** [comment]
@eviljeff : One question, should this "all rights reserved" license to be linked to some page? Right now I can see the license correctly but not linked.

**Comment by eviljeff** [comment]
No link - there isn't an explanation other than all rights are reserved (I specifically added a fix not to return a url to an empty license page too)

**Comment by vcarciu** [comment]
Thank you! 
Marking issue as verified : 
![rights](https://user-images.githubusercontent.com/1583842/32892948-8e39f076-cae0-11e7-8877-b74cb2be6223.png)
