### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by NurdBurd** [mozilla/addons-server#3678]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?  How to correct this error quickly.
![firefoxproblem](https://cloud.githubusercontent.com/assets/16694816/19120125/e3fdbb8c-8aef-11e6-99e0-4ae260aa3e51.JPG)

(Please include a link to the page, screenshots and any relevant files.)

**Comment by gregglind** [comment]
(Hard to reproduce without seeing which url this went to. 

UNABLE to reproduce)

**Comment by andymckay** [comment]
@NurdBurd we aren't sure what URL this is about, if you can give us some more details, we can point it the appropriate team. It isn't about addons-server, although the link may have appeared on AMO page, its actually from a part of Firefox.

**Comment by andymckay** [comment]
Pinging @gregglind

**Comment by gregglind** [comment]
I will dig.

**Comment by mythmon** [comment]
Normandy had this variable configured to `https://addons.mozilla.org/firefox/shield_study_5&utm_campaign=shield-study-context-graph-v1`. Notice the `&` instead of `?` for the query string. I've updated the config.

**Comment by andymckay** [comment]
The latter URL works great, I'll close this, thanks @mythmon @gregglind
