### ISSUE TITLE
"Delete current photo" causing layout issues

### ISSUE THREAD

**Issue by vijeth-aradhya** [mozilla/addons-server#3683]
### Steps to reproduce
Go to https://addons.mozilla.org/en-US/firefox/users/edit and scroll down till you get the profile picture

### AR
"Delete current photo" link is NOT aligned with the photo and other fields

### ER
There should be no blank space after "Choose Photo..". Basically, "Delete current photo" should be there

### Screen shot
![bug](https://cloud.githubusercontent.com/assets/15227565/19150190/29d2c424-8be3-11e6-8df7-1e202c2ecec7.png)

**Comment by ValentinaPC** [comment]
This is also tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1120938 .

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
Delete current photo link is displayed correctly.
Postfix screenshot: 
![save](https://cloud.githubusercontent.com/assets/15685960/19387417/b662b364-9222-11e6-92d1-7c9c4b6dfa43.png)

"Use original" link displayed right after adding a new profile picture, has layout issues, maybe you want to fix this too?
![add](https://cloud.githubusercontent.com/assets/15685960/19387439/da8377ec-9222-11e6-851a-eea4e9fd3d44.png)
