### ISSUE TITLE
Admin rights and submitted addons are lost after anonymizing an account and sign out \ sign in 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3687]
Steps to reproduce
1.Login to AMO-dev with an admin account and be sure that you have at least one add-on submitted
2.Go to My Profile - Manage User
3.Anonymize the user then log out
4.Log in again

Expected results:
The user is still anonymous but admin rights and submitted add-ons are still available

Actual results:
Admin rights and submitted add-ons are not available anymore

Please see a video of this bug : 
![adminrights](https://cloud.githubusercontent.com/assets/1583842/19158525/c07a8336-8bf1-11e6-83ef-68d658f3177f.gif)

**Comment by krupa** [comment]
i think this is by design.
