### ISSUE TITLE
Remove load tests

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3690]
We used the load tests when we switched to AWS but now that we've migrated they're no longer being run.

Since the code requires maintenance from time to time and it's easy enough to resurrect it from a commit we should remove the code until we decide it's worth bringing up to date and running on a regular basis.

**Comment by EnTeQuAk** [comment]
I remember that there were a few scenarios where @jasonthomas ran loadtests in the recent months after we long switched to AWS, e.g for docker stuff maybe? Not sure if we were using the same tests though.

**Comment by jasonthomas** [comment]
I was using httperf with log replay. If no one else is using these we should get rid of them.

**Comment by EnTeQuAk** [comment]
Since I just searched where those load-tests are, here they are: https://github.com/mozilla/amo-loadtest

**Comment by EnTeQuAk** [comment]
We're not removing them but actually integrating them into this repository very soon. Closing this.
