### ISSUE TITLE
Last row of add-ons description appears cut in promo banner

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3715]
STR:
1. Load AMO-stage in a new and clean profile
2. Navigat to promo banner and observe the add-ons descriptions

ER:
There are no display or layout issues.

AR:
The last row of add-ons description is cut.

Notes/Issues:
I think this is happening because, somehow, description is listed on four rows instead of three.
I am able to reproduce at every clean, new profile start for stage and dev on Firefox Release and latest Nightly.
Refreshing the page turn things back to normal.
Screenshots for this issue:
![cutrowstage](https://cloud.githubusercontent.com/assets/15685960/19261204/41833802-8f98-11e6-84a4-87c62f1aeee7.png)
![dev-cutrow](https://cloud.githubusercontent.com/assets/15685960/19261203/417f47ec-8f98-11e6-9715-eee5ba5afcba.png)

**Comment by eviljeff** [comment]
looks like this is fixed - overflowing text is clipped with ... now.

**Comment by ValentinaPC** [comment]
I am still able to reproduce this on clean profile using AMO-dev FF52(Win 7)
Please see screenshot: 
![dev](https://cloud.githubusercontent.com/assets/15685960/24144140/d8b6356a-0e34-11e7-946c-1fce9172cab3.png)

Note reproducing on production.

**Comment by eviljeff** [comment]
![screenshot 2017-03-22 10 30 39](https://cloud.githubusercontent.com/assets/768592/24193610/c6e78a30-0eea-11e7-841e-9da023f07187.png)
- they never wrap onto the 4th line for me
