### ISSUE TITLE
Review page throws 500

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3721]
### Describe the problem and steps to reproduce it:

I dared to access https://addons.mozilla.org/en-US/editors/review/697186

### What happened?

`500. Oops! We had an error.`

### What did you expect to happen?

No error, please.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/356516/

@EnTeQuAk said "ugh, @eviljeff touched that recently with the whole status refactor"

**Comment by diox** [comment]
The exception is `KeyError: 8` when iterating over file statuses, and the value 8 corresponds to ` _STATUS_LITE`, which was removed as part of the changes to preliminary status, so it does look like something @eviljeff touched indeed.

**Comment by wagnerand** [comment]
It looks like the only file in the only version of that add-on still has `STATUS_LITE` in the database:
```
$ select id, status from files where version_id = 1846730;
+--------+--------+
| id     | status |
+--------+--------+
| 424352 |      8 |
+--------+--------+
```

**Comment by wagnerand** [comment]
And there are ~8195 other files across all add-ons that have `8` as well. Did some add-ons not get migrated on purpose?

**Comment by eviljeff** [comment]
Ah... from the review url I'm deducing the add-on was deleted (we released the slug).

Deleted add-ons weren't migrated.  Perhaps they should have been but as they couldn't be undeleted it seemed harmless (assumption:wrong).

**Comment by wagnerand** [comment]
Yes, this add-on has been deleted. I took the url from dxr, though :)
