### ISSUE TITLE
settings files are in the wrong order for INBOUND_EMAIL_DOMAIN

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3728]
#3726 

INBOUND_EMAIL_DOMAIN has a default of DOMAIN, if not set from local Env but the line for INBOUND_EMAIL_DOMAIN is above where we set DOMAIN.

**Comment by madalincm** [comment]
Please add some steps to reproduce or add the "needs no qa" label if no qa is needed

**Comment by eviljeff** [comment]
With the `activity-email` waffle switch enabled, do something in the editor tools that would send an email (approve, reject, info request).  The email sent to the developer should have a reply-to address that ends `@addons-dev.allizom.org`, or equivalent for stage.  Email will be in /admin/fakemail unless it's whitelisted.

**Comment by madalincm** [comment]
Verified as fixed in FF49(Win7) in amo-dev.
The reply to mail ends with @addons-dev.allizom.org
![replytoemail](https://cloud.githubusercontent.com/assets/15685441/19349051/b1198f00-9159-11e6-8105-e327f5be6543.png)
