### ISSUE TITLE
Date/time for activity is an hour out

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3729]
#3726 

e.g. https://addons-dev.allizom.org/en-US/developers/addon/amo-admin-search/versions 
date/time stamps are an hour out for me, (probably DST)

**Comment by muffinresearch** [comment]
Is that because it's UTC?

**Comment by wagnerand** [comment]
Yes, dates in the db are UTC, the view is responsible for translating them to the clients timezone. I'm not exactly sure where that happens, but timestamps on a editor review page are correct.

**Comment by eviljeff** [comment]
these are from an API rather than served via a django view.  Client-side translation is probably most appropriate (the page already uses a js library to do "an hour ago", etc)

**Comment by ValentinaPC** [comment]
I've checked the time in an add-on review page, after adding a developer reply from "Review history" section (where the date/time is mentioned as "2 minutes ago", "an hour ago", etc.), and seems to be UTC format.
![dev_reply](https://cloud.githubusercontent.com/assets/15685960/19601748/3f042870-97b3-11e6-87bc-68ccaf3bf1f3.png)

Is there anywhere else I should check the date/time?
Or, something else to be checked? Thanks!

**Comment by eviljeff** [comment]
This patch only fixed dates that were served from the API, (e.g the versions page in devhub where I noticed it).  If other places, like the editor tools are wrong then its a different issue (editors probably don't care that much).

**Comment by ValentinaPC** [comment]
@eviljeff : There are some other places where the date is served from the API? Thanks in advance!

Related to review page and editors: I thought that date/time from review page is on UTC format, and this is intended, no?
Also "Notes to Reviewer" field, from submission, has no date or time at all while checked in review add-on page...this is also something that editors don't care?

**Comment by eviljeff** [comment]
> @eviljeff : There are some other places where the date is served from the API? Thanks in advance!

The new mobile front-end I guess.  I'm not aware of other places on prod

> Related to review page and editors: I thought that date/time from review page is on UTC format, and this is intended, no?

No idea.

> Also "Notes to Reviewer" field, from submission, has no date or time at all while checked in review add-on page...this is also something that editors don't care?

It's a property of the version rather than a log entry (we fake it to show it to the editor in the same list) so doesn't have a time/date as such.  Could fake that too if anyone wanted it.
