### ISSUE TITLE
Add a New Version is broken

### ISSUE THREAD

**Issue by JamesSylvia** [mozilla/addons-server#3730]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I can not upload new Firefox add-on version to AMO.

### What happened?
Stucks at Validating. Gives error 504.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
It's pretty hard to tell what's wrong without any information whatsoever.

Can you provide the file you are trying to upload?

**Comment by JamesSylvia** [comment]
Today it works. Bye
