### ISSUE TITLE
CSP allows scripts from several third-parties without pre-loaded key pins in Firefox

### ISSUE THREAD

**Issue by kmaglione** [mozilla/addons-server#3731]
The current AMO CSP allows scripts from the following domains, which don't pre-loaded key pins in Firefox, or use HPKP:

- ssl.google-analytics.com
- www.google.com
- www.gstatic.com
- www.paypalobjects.com

I'd like to add some client-side restrictions to Firefox that require a fairly strict CSP for sites with elevated privileges like AMO. Ideally, I'd like all script sources to have static key pins. At the very least, I'd like to limit the number of third-party sites we load scripts from.

Can any of these third-party scripts be hosted from our own CDNs rather than from third parties? Is there any other way we can reduce the list of allowed sites?

**Comment by muffinresearch** [comment]
Moved this discussion to bugzilla.
