### ISSUE TITLE
File browser shows not found page for specific add-on

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#3732]
### Describe the problem and steps to reproduce it:
* Go to https://addons.mozilla.org/en-US/editors/review/bkav-plugin
* Click on "Contents" for 1.5.3, which takes you here: https://addons.mozilla.org/en-US/firefox/files/browse/513436/

### What happened?
* The pretty "Not Found" page is shown

### What did you expect to happen?
* The file contents should be shown

**Comment by EnTeQuAk** [comment]
I can't access that link, with our recent fixes for the file-viewer and other parts, is this still happening?

**Comment by wagnerand** [comment]
It works for this particular add-on. Let's close this and file a new issue if we see it again.
