### ISSUE TITLE
WebExtensions Experiments are restartless

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3733]
If an add-on has type=256, then its restartless and shouldn't show a restart required badge.

https://addons.mozilla.org/en-US/firefox/addon/experimental-logins-api/

**Comment by diox** [comment]
I merged a fix, but just realized that maybe you'd need a migration to fix those add-ons ? Or are there so few of them that it can be done manually ? Just uploading a new version should do the trick once the fix goes into production.

**Comment by andymckay** [comment]
We've only got one so far to test things out and I'll upload a new version of that, so don't worry about it. Thanks.

**Comment by madalincm** [comment]
Verified in FF49(Win7) on amo-dev. I have uploaded on -dev an add-on with type 256 and the restart required badge is not displayed.
![norestartbadge](https://cloud.githubusercontent.com/assets/15685441/19340602/6df3c294-9132-11e6-9cbe-90bfd43b4532.png)

Is there anything else we should check before marking this bug as verified fixed?

**Comment by diox** [comment]
No, that's it, thanks.
