### ISSUE TITLE
"Test Pilot" section from the promo-banner has layout issues if is translated

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3736]
Steps to reproduce:
1. Load AMO-stage homepage 
2. Change the language to Deutsch https://addons.allizom.org/de/firefox/
3. Observe "Test Pilot" section from the banner

Expected results:
There are no display or layout issues.

Actual results:
The "get started" button appears cut.

Notes/Issues:
Verified on AMO-stage FF49(Win 7).
Issue is reproducing if the description about Test Pilot is translated.
Screenshot for this issue: 
![testpilot](https://cloud.githubusercontent.com/assets/15685960/19305161/68105d70-9078-11e6-91be-92b1615bed05.png)

**Comment by muffinresearch** [comment]
I'll look to get a fix in for this and cherry pick it so we can put it out as part of the release tomorrow.

**Comment by ValentinaPC** [comment]
I think the issue will reproduce for other languages too, if Test Pilot description is translated.

**Comment by muffinresearch** [comment]
> I think the issue will reproduce for other languages too, if Test Pilot description is translated.

It's possible we'll have to see, the `de` locale is usually a good indicator and the change has a bit of scope for longer strings before wrapping.

I've cherry-picked the fix into a new tag and it's on its way to stage.

**Comment by muffinresearch** [comment]
Here's a screenshot from stage now:

<img src="https://cloud.githubusercontent.com/assets/1514/19314111/de6a6d68-9090-11e6-97de-2fdede5687e2.png">

**Comment by ValentinaPC** [comment]
Yup. Looks great!
Could you please add the Test Pilot info from the banner in -dev, too? (for testing purposes) Thanks!

**Comment by muffinresearch** [comment]
I've added the data, just waiting for the CSS patch to be release. -dev deploys seem to have backed up a little bit.

**Comment by muffinresearch** [comment]
@ValentinaPC it's up on -dev now.

**Comment by ValentinaPC** [comment]
Verified as fixed on -dev and -stage using FF49(Win 7)
Postfix screenshot: 
![2016-10-13_0946](https://cloud.githubusercontent.com/assets/15685960/19339115/060c3f7e-912a-11e6-83ac-c57c174d2ae6.png)
