### ISSUE TITLE
Maximum version is not listed in "Version History"and "Review add-on" pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3745]
Steps to reproduce:
1. Submit a webextension with version range using AMO-stage i.e. https://addons.allizom.org/en-US/developers/addon/v-user/versions/1702013
2. Go to version history public page and observe the max version limit

Expected results:
The version range is the one set in the manifest.json, before submission (this case 48.0 - 49.0)

Actual results:
In version history page and review add-on page the max limit is transformed to "later".

Notes/Issues:
Reproducing for add-ons also. Not reproducing for other platforms like Firefox for Android, Thunderbird, etc.
Verified on FF49(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshots for this issue:
![manage_version](https://cloud.githubusercontent.com/assets/15685960/19312472/271c79b6-909b-11e6-8dc6-fb7c9c8c2924.png)
![reviewer_page](https://cloud.githubusercontent.com/assets/15685960/19312471/271c0a80-909b-11e6-8465-dea0fd44ae20.png)
![versionhistory](https://cloud.githubusercontent.com/assets/15685960/19312473/271e0bd2-909b-11e6-928b-6ed34838124e.png)

**Comment by EnTeQuAk** [comment]
I think this is mostly an issue how it's being displayed but worth investigating. But I think the actual data is correct so we're good in that end.

**Comment by ValentinaPC** [comment]
I think that at add-on install, the max version is taken into consideration correctly, but is a bit misleading to be listed different.

**Comment by vasilicamihasca** [comment]
Not being able to set a max compatible version for an add-on (any max version I set is not taken into consideration) blocks me for checking if an add-on with version range between, let's say 36.0-49.0 cannot be installed on Nightly (e.g. https://addons-dev.allizom.org/en-US/firefox/addon/uuupdate/ is successfully installed on Firefox 52.0a1) 


Is there any workaround for this?

**Comment by diox** [comment]
This is because the max version is ignored if the corresponding files don't have `strict_compatibility` enabled (to follow Firefox behavior of ignoring max version if strict compatibility is not set in `install.rdf`).

It might be worth revisiting with WebExtensions, especially now that we have a warning when the developer sets `strict_max_version` in the manifest, but IMHO going forward we should just prevent developers from playing with compat versions in devhub and just follow the manifest...

**Comment by EnTeQuAk** [comment]
> It might be worth revisiting with WebExtensions, especially now that we have a warning when the developer sets strict_max_version in the manifest, but IMHO going forward we should just prevent developers from playing with compat versions in devhub and just follow the manifest...

@jvillalobos can this be part of https://github.com/mozilla/addons-server/issues/7825 or maybe something we can target once we disable support for legacy add-ons fully? Not sure it's worth doing this now.

**Comment by jvillalobos** [comment]
Yes, it should be part of #7825. We don't want developers making compat changes on AMO in the future.
