### ISSUE TITLE
Drop confirmationcode and password columns

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3746]
Once `password` and `confirmationcode` are no longer needed they should be dropped from the UserProfile database table. Since we might want to use the existence of some data there to perform some cleanup we will do this at a later date.

Extracted from #3049.

**Comment by mstriemer** [comment]
I tried running the delete SQL from the `unconfirmed()` cron job and it caused some integrity errors which prevented the delete from running. I've updated the SQL so that it can run on -dev and have deleted the unconfirmed users on -dev.

I put the [updated SQL](https://gist.github.com/mstriemer/6f48d765f776e04962cee578eee220f2) in a gist. I'll look into running this on stage on Monday to confirm there are no issues with it there and then we can run it on production at some later time. Dropping `password` and `confirmationcode` can follow that.

@diox @EnTeQuAk does this SQL look reasonable to you? Am I missing any other tables? I figured it was best to keep any users that had any data associated rather than trying to figure out if it is safe to remove.

**Comment by EnTeQuAk** [comment]
This looks permissive enough to me, I'd rather delete one user too few than too many. Do you have a count of how many people are affected by that query to get an estimate of how reasonable it is?

**Comment by mstriemer** [comment]
These users shouldn't be able to add any of those things so hopefully it shouldn't be much less than all of them.

The total we're expecting from the old query is `390,592` and this updated one returns `390,467` on prod.

**Comment by mstriemer** [comment]
I had to add another join to the `collections` table to run this on stage. Originally was going to delete `339,028` users but after that the new number was `338,106`. It took 1 minute and 8 seconds to run.

@jasonthomas is this a reasonable [query](https://gist.githubusercontent.com/mstriemer/6f48d765f776e04962cee578eee220f2/raw/896c48df9832dc38740756b1bc173a1bcd807b86/old-users.sql) to run on production? I'd imagine running a minute long query against the users table is a bad time.

**Comment by jasonthomas** [comment]
Since this is a DELETE query affecting a large amount of records it will
cause some replication lag but it will not lock the table. We should be
okay to run this on production.

**Comment by mstriemer** [comment]
QA:

There is nothing really specific to test here, this is just removing old data that isn't being used. It would be good to test that all of the user views are working as expected though. Login/register/edit/etc.

**Comment by vcarciu** [comment]
Verified as fixed after trying more login/register/edit scenarios.
