### ISSUE TITLE
Oops error displayed when creating a blocklist detail

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3748]
### Steps to reproduce:
1. Open https://addons.allizom.org/en-US/admin/models/blocklist/blocklistitem/ and click on the Add blocklist item button.
2.  Click on the green plus sign from the Details field to open the Create Blocklist Detail page.
3. Fill the form and click the Save button.

### Expected results:
The blocklist detail is created and a confirmation message is displayed.

### Actual results:
The blocklist detail is created and a oops error is displayed.

### Notes/Issues:
Verified in FF49(Win7) Issue can be reproduced in amo-dev and amo-stage
Screencast for this issue:
![oopsdetails](https://cloud.githubusercontent.com/assets/15685441/19317437/b026387a-90ad-11e6-9a02-c5fe97d881ba.gif)

**Comment by krupa** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/349543/

traceback details:
AttributeError: 'NoneType' object has no attribute 'user'
  File "django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "olympia/zadmin/__init__.py", line 17, in rendered_content
    self.context_data['user'] = self._request.user

**Comment by andymckay** [comment]
If this doesn't affect @jvillalobos then this code is all going to be removed when the blocklist moves to kinto.

**Comment by jvillalobos** [comment]
It doesn't affect the way we currently create blocklists, so we can ignore this.
