### ISSUE TITLE
Get rid of `Addon.latest_version`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3751]
Splitt from #3567

The `latest_version` field on `Addon` points to, well, the latest (non-disabled) version. It's used by reviewer tools to figure out which version to review, and internally so set a few things.

With the introduction of version channels, it won't be as useful, since you need to figure out the latest version available in the same channel you're interested in. We could add `latest_unlisted_version` and `latest_listed_version` fields, but that's probably overkill and won't scale if we decide to add more channels later.

I want to try to get rid of that field, replacing it with a method that takes a `channel` and maybe an optional argument to ignore disabled versions. To do this safely, my plan is to do this in 3 steps:
- [x] Keep the field and the methods that sets it, but stop using it directly, instead using `latest_version` property to emulate it, and modifying reviewer tools queries that directly hit the database
- [x] Then, replace `latest_version` property with a method using the channel
- [x] Then, stop setting the (now obsolete) field
- [x] Then, remove the column entirely.

**Comment by diox** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1328917 to let ops handle the column removal.

**Comment by eviljeff** [comment]
column is gone (on dev, stage, and prod today) so calling it done!
