### ISSUE TITLE
Inefficient "View Listing" link for rejected themes

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3752]
Steps to reproduce:
1. Submit a new theme in AMO-stage
2. Reject the theme
3. Go to "Edit Listing" theme page 
4. Click "View Listing" link

Expected results:
"View listing" link is not available/accessible.

Actual results:
"View Listing" link is available. If clicked, returns a 404 page.

Notes/Issue:
Issue is reproducing for the other actions like: duplicate and flag.
Verified on FF49(Win 7). Issue is reproducing in AMO-stage, AMO-dev.
Video for this issue: 
![rejectedtheme](https://cloud.githubusercontent.com/assets/15685960/19346039/0a4f065a-914a-11e6-8d59-d2b329de77c6.gif)

**Comment by eviljeff** [comment]
link shouldn't be shown for unapproved themes

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by lavish205** [comment]
I would like to work on this bug. @eviljeff

**Comment by eviljeff** [comment]
@lavish205 great.  
Should just be a matter of wrapping https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/personas/edit.html#L55 in `{% if ... %}` where you check `addon.status == amo.STATUS_PUBLIC`

**Comment by ValentinaPC** [comment]
@eviljeff : do we also wanna remove the "View Listing" link for unapproved themes?
Please see screenshot:
![view-listing-aww](https://cloud.githubusercontent.com/assets/15685960/25393906/7283e806-29e5-11e7-9085-2b9bcc377cd5.png)

**Comment by eviljeff** [comment]
@jvillalobos not sure what's expected or desired functionality ^

**Comment by ValentinaPC** [comment]
I think we should let the link for "pending approval" themes, and remove it just for rejected ones. :)

**Comment by jvillalobos** [comment]
If the listing page is visible while awaiting review, I suppose it makes sense to show the link in that case.

**Comment by eviljeff** [comment]
_Is_ it visible (for normal theme submitters)?  I'm not familiar with the norms around themes.

**Comment by ValentinaPC** [comment]
It is visible for the owner of the theme. Can be simple user, not necessarily and admin.
![2017-04-26_1423](https://cloud.githubusercontent.com/assets/15685960/25432181/207f9c2e-2a8c-11e7-8de5-de1ef7b0427f.png)
![2017-04-26_1425](https://cloud.githubusercontent.com/assets/15685960/25432250/5ab54718-2a8c-11e7-8e9f-e8f2b484f039.png)

**Comment by eviljeff** [comment]
@lavish205 do you want to work on another commit for this issue?  We need to change it to be `addon.status in [amo.STATUS_PUBLIC, amo.STATUS_PENDING]`

**Comment by lavish205** [comment]
cool, I'll fix this. @eviljeff

**Comment by ValentinaPC** [comment]
Verified as fixed in AMO-dev FF53(Win 7).
Pending approval themes also have "View Listing" link.
Postfix screenshot:
![2017-04-27_1631](https://cloud.githubusercontent.com/assets/15685960/25486779/e6a65b70-2b6a-11e7-924a-87977b2a4263.png)
