### ISSUE TITLE
Update admin flag notification

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3753]
https://github.com/mozilla/addons-server/pull/3707 add a generic message about the added admin-flag. It works for when the add-on is currently under review, but it sounds odd if the add-on is not under review.

Let's update it to something even more generic...

````
Review might take a bit longer than usual as it needs to be checked by an admin reviewer.
```

@eviljeff thoughts?

**Comment by eviljeff** [comment]
How often do we admin flag add-ons not under review?  If it's a very rare thing might not be worth bothering.
If we change the message in the log we need to change the email template that gets used too.

**Comment by wagnerand** [comment]
Correct. But it will be those two changes only, not shouldn't be a big deal.

I don't have exact numbers how often we do it, but it happens.

**Comment by jvillalobos** [comment]
Telling developers that their add-on is still in the queue is important, so I wouldn't want to remove it when it's relevant. That leaves a few options: (1) not notifying developers in that case, (2) sending a separate message, (3) keeping things as they are. I'm guessing 3 is the most practical, given the rarity of the situation.
