### ISSUE TITLE
[Blocklisting] "No, take me back" button form blocklist item delete page does not work

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3754]
Steps to reproduce:
1. Load Blocklist items from Admin Tools page https://addons.allizom.org/en-US/admin/models/blocklist/blocklistitem/
2. Pick an item and access details page i.e. https://addons.allizom.org/en-US/admin/models/blocklist/blocklistitem/815/
3. Click "Delete" link
4. Click "No, take me back" button

Expected results:
Item details page is loaded.

Actual results:
Nothing happens.

Notes/Issues:
Verified on AMO-stage FF49(Win 7).
Video for this issue: 
![delete-changeurmind](https://cloud.githubusercontent.com/assets/15685960/19348940/1b8f8a48-9159-11e6-9679-d723d48f2d6e.gif)

**Comment by jvillalobos** [comment]
Not worth fixing since we never use that button and we're migrating away from those tools.
