### ISSUE TITLE
Remove SubmitStep model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3757]
The SubmitStep model is used during add-on submission but will soon only track the progress from upload->details, and only for listed add-ons.  So we should get rid of it entirely and establish that an add-on is mid-submission by inspecting it's attributes.

**Comment by eviljeff** [comment]
follow on from #3468

**Comment by eviljeff** [comment]
QA: try to go back and forth in submission flow; abort a submission mid-steps; try to resume, etc.

**Comment by ValentinaPC** [comment]
Verified aborting submit, resuming submit, closing after 1 submission step, and other scenarios and seems to work as expected.
Verified on AMO-dev FF49(Win 7)
