### ISSUE TITLE
A soft blocklisting will prevent the updates to last version even if user chose to enable the addon

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3758]
Steps to reproduce:
1. Go to AMO stage as an admin, and soft blocklist an add-on(or webextension) for all its versions(min - 0 max - *)
2. Install the soft blocklisted add-on and from add-ons manager, chose to enable it (it is disabled due to blocklisting)
3. Upload a new version and approve it 
4. Go to addons manager and from Tools drop down menu, select Check for Updates

Expected results:
New version of the addon is downloaded. Eventually , user can have the option to enable it too

Actual results:
Update is never made

Notes:
Update the extensions.update.url to https://versioncheck.allizom.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%

Please see video for issue:
![blocklisting](https://cloud.githubusercontent.com/assets/1583842/19355124/d78cc888-9171-11e6-85f1-aa865d2d5c9c.gif)

**Comment by eviljeff** [comment]
AMO no longer handles blocklisting.  If this issue is still reproducing please log again on https://bugzilla.mozilla.org/buglist.cgi?component=Blocklisting&product=Toolkit&list_id=13475633
