### ISSUE TITLE
Version notes is forever loading for Unlisted New Add-ons queue

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3759]
Steps to reproduce:
1.Go to editor tools and select Unlisted New Add-ons queue (https://addons.allizom.org/en-US/editors/unlisted_queue/new)
2.Click on Version Notes / Notes for reviewer icon

Expected results:
Notes are opened or a message saying that there are no notes is displayed

Actual results:
A forever "Loading" message is displayed

Please see a video for the issue:
![unlistednew](https://cloud.githubusercontent.com/assets/1583842/19355520/582dc1f8-9173-11e6-8079-2140c7e12e89.gif)

**Comment by wagnerand** [comment]
I really wonder whether anyone uses that button these days...I certainly don't.

@kewisch let's get rid of it?

**Comment by jvillalobos** [comment]
We talked about removing a couple other columns when we met to discuss AMO features: https://public.etherpad-mozilla.org/p/amo-removal-list#lineNumber=29. So, if we're nuking a column, might as clean up the others we think we don't need.

**Comment by wagnerand** [comment]
Ok, I close this as a wontfix and will file a new issue about removing the column.

**Comment by kewisch** [comment]
I certainly have never used it, happy to get rid of it
