### ISSUE TITLE
"This add-on is experimental" checkbox can be checked by pressing on its tooltip

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3761]
Steps to reproduce:
1.Start a new submission flow on AMO-dev
2.At step 2 , hover over the "This add-on is experimental" tooltip then click on it

Expected results:
Checkbox on the left side is not checked when pressing on the tooltip question mark

Actual results:
Checkbox is checked

NOTES:
This is reproducible in the old submission flow too

Please see the video of issue:
![questionmark](https://cloud.githubusercontent.com/assets/1583842/19381029/7b3857dc-9202-11e6-871a-b182f74826ea.gif)

**Comment by muffinresearch** [comment]
This is presumably because the tooltip `?` is part of the label.

**Comment by wagnerand** [comment]
Mentor for this issue will be @eviljeff.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by meetmangukiya** [comment]
I'll like to try my hands at this one! :D

**Comment by eviljeff** [comment]
@meetmangukiya should just be a matter of moving the `<span>` out of the `<label>` here: https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/addons/submit/describe.html#L41:L50

**Comment by meetmangukiya** [comment]
Oh.. well, thats easy! On it, I'll raise a PR soon :D

**Comment by vcarciu** [comment]
Verified as fixed : 
![tooltipch](https://cloud.githubusercontent.com/assets/1583842/20106205/049caa12-a5dd-11e6-9291-ea2216e9665c.gif)

**Comment by meetmangukiya** [comment]
What holds ahead? After `good first bug` ?

**Comment by eviljeff** [comment]
@meetmangukiya you can choose another one from https://github.com/mozilla/addons-server/labels/good%20first%20bug
