### ISSUE TITLE
Remove editor checkbox for notification on next submission

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3762]
Part of #3726 -ish.

Since direct reviewer notification is around the corner, I don't think we need the checkbox below the review submission form on a review details page:

`Notify me the next time this add-on is updated. (Subsequent updates will not generate an email)`

anylonger.

Adding @kewisch to confirm.

**Comment by kewisch** [comment]
I've heard that even with the reviewer commuication tool there won't be a way to get such updates. I'd like the functionality to stay, because in certain cases it is helpful to get notifications when developer has uploaded a new version.
