### ISSUE TITLE
Improve performance of the function used to fetch the add-on in the queue

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3766]
The `get_position()` helper is used by the devhub - and exclusively by the devhub, it seems - to determine the position of the add-on in the queue. It's called in a lot of places in devhub, and in particular it's called _for each add-on_ by the page that lists the add-on you've developed.

It's current implementation is super inefficient. For each add-on, it:
- Does a query that gets the full list of pending add-ons, filtered on the current add-on id, complete with multiple `JOIN`, `GROUP BY`, `DISTINCT` to determine the value of various fields... only to do a `COUNT(*)` of that query, with a subselect.
- If that count is > 0:
 - It does that same query without the filtering on add-on id but with a filtering on the minimum amount of time waited, (doing a `COUNT(*)` on the full query again) giving it the position of the add-on
 - It repeats the query without any filtering (doing a `COUNT(*)` on the full query again) to get the total

There are variations depending on whether the `addon` we're looking at is already public or nominated, listed or unlisted, but the same principles apply. 

It's completely crazy from a performance standpoint. The query to fetch the queue alone is fairly expensive, to do it multiple times just to get a `COUNT(*)` on it is really bad. The first query is done even if the add-on has no pending versions!

It should be changed for something simpler and less expensive.

**Comment by diox** [comment]
FWIW Marketplace had a simpler version (that does extra stuff we don't need) https://github.com/mozilla/zamboni/blob/master/mkt/reviewers/helpers.py#L245

**Comment by eviljeff** [comment]
The Marketplace version calculated an estimated review time too (i.e. did more with less impact).

**Comment by jasonthomas** [comment]
This affected our prod MySQL master performance today, I'm assuming because the page with this query was requested multiple times. I had to manually kill the SELECT's to get MySQL CPU under control. If we can't fix the query right away I would suggest routing these to the our MySQL slaves.

**Comment by bqbn** [comment]
Got one alert for master high CPU over the weekend

https://app.datadoghq.com/monitors#1023844?to_ts=1477289320000&group=dbinstanceidentifier%3Aamo-olympia-db-master-prod-amoprod1&from_ts=1477288020000

**Comment by diox** [comment]
@eviljeff fixed that in https://github.com/mozilla/addons-server/issues/3834 - the reviewer tools part is covered by #3864.
