### ISSUE TITLE
Change name of Download button at the end of unlisted submission flow because it is triggering an install

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3767]
Steps to reproduce:
1.Go to MP-dev and submit a new unlisted addon
2.At the end of submission flow, press on Download button

Expected results:
If button is named Download, a download dialog should start

Actual results:
Installation flow is started

NOTES:
I know that the button is named according with the design of the new submission flow, but I still think that we should rename it.

Please see video of issue:
![download](https://cloud.githubusercontent.com/assets/1583842/19393317/ecc41ae6-923c-11e6-8842-a246edfcfa0a.gif)

**Comment by jvillalobos** [comment]
If it's possible to trigger a download instead of an install, that would be ideal. Otherwise maybe we should change it to a link to set clearer expectations.

**Comment by eviljeff** [comment]
The [download](https://developer.mozilla.org/en/docs/Web/HTML/Element/a#attr-download) attribute purports to force a download but it looks like the content-type sent by the CDN is overriding it (from a quick hack of the html on the page).  I can't think of a way around it.

**Comment by muffinresearch** [comment]
Firefox only supports same-origin links for the download attribute. This starts same origin but there's a redirect to the CDN. This could be why it's not working.

**Comment by madalincm** [comment]
Verified as fixed in FF49(Win7) in addons-dev.allizom.org
Postfix screencast:
![unlisteddownload](https://cloud.githubusercontent.com/assets/15685441/20478893/bfb1f3f0-afe4-11e6-909f-bb81dd42c5e8.gif)
