### ISSUE TITLE
[Blocklisting] No security warning message is displayed for a blocklisted WebExtension/Add-on on Android

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3768]
Steps to reproduce:
1. Load the page: https://addons.allizom.org/en-US/firefox/addon/blocklistandroid/
2. Tap “Add to Firefox”.

Expected results:
The WebExtension is not installed and a security warning message is displayed.

Actual results:
The WebExtension is not installed but there is no security warning message displayed.

Notes/Issues:
Verified on AMO-stage FF49(Android 4.2.1).

**Comment by eviljeff** [comment]
https://bugzilla.mozilla.org/buglist.cgi?component=Blocklisting&product=Toolkit&list_id=13475633
