### ISSUE TITLE
Incompatibility with Firefox label for "no-platform option" unapproved Search Tool

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3769]
Steps to reproduce:
1. Submit a search engine without approving it 
2. Click the "View Add-on Listing" link from Dev Hub i.e https://addons-dev.allizom.org/en-US/firefox/addon/3-times/

Expected results:
There is an "Add to Firefox" yellow button and the message "This add-on has not been reviewed by Mozilla. Learn more" bellow.

Actual results:
Under the message there is incompatibility with Firefox label, even if there is no info related with platforms availability at submission or in the .xml file.

Notes/Issues:
Reproducing on all AMO servers.
Verified on AMO-dev FF49(Win 7).
Screenshot for this issue: 
![searchtool](https://cloud.githubusercontent.com/assets/15685960/19394151/7ff6a380-9240-11e6-8759-8207a5d7d6e2.png)

**Comment by EnTeQuAk** [comment]
Maybe the problem here was that the add-on really has not been reviewed yet? Can't reproduce anymore since the add-on is not accessible anymore.

**Comment by ValentinaPC** [comment]
Issue is still reproducing. Verified this on AMO-dev FF52(Win 7).
Another example: https://addons-dev.allizom.org/en-US/firefox/addon/genscript-test/
Yes, the add-on is not reviewed.

After approving it will delete the "Works with Firefox" banner.

If you think the behavior is ok, I can live with this also.
