### ISSUE TITLE
Cannot upload webextensions .xpi file to AMO

### ISSUE THREAD

**Issue by michael-oneill** [mozilla/addons-server#3774]
I am trying to upload a new version of my webextensions addon Bouncer to AMO

### What happened?
The "Add a new Version" modal hangs with the blue stripe "Validating install.xpi" showing

I have attached the file install.xpi (renamed to install.zip)
[install.zip](https://github.com/mozilla/addons-server/files/532045/install.zip)

**Comment by ValentinaPC** [comment]
Maybe this will help while trying to find a solution: 
-> I've tried to submit the attached webextension and received the following error: 
![2016-10-17_0916](https://cloud.githubusercontent.com/assets/15685960/19427293/bc2c2494-944b-11e6-889d-95173c52e2dd.png)
Verified on FF49(Win 7) around all AMO servers.

**Comment by michael-oneill** [comment]
Thanks for seeing that, its fixed now, The validation still hangs though :(

**Comment by EnTeQuAk** [comment]
Hmm, I cannot reproduce that the modal hangs. It's a bigger add-on so it might take a minute but maybe it was just a hickup on the server-side. Does it still not work? Also see the error message that @ValentinaPC posted - that'll get fixed before being able to upload the add-on.

**Comment by michael-oneill** [comment]
fixed it, the manifest.json was encoded with wrong codepage. Thanks for your help! I will close this now
