### ISSUE TITLE
window.postMessage in content script issue

### ISSUE THREAD

**Issue by michael-oneill** [mozilla/addons-server#3775]
### Describe the problem and steps to reproduce it:

I am sending a message from a content script to the controlled page using window.postMessage

if I set the origin parameter (2nd) to window.location.origin the postMessage fails with an error on the console saying the origin of the receiving is different from the targeted origin (although it prints them as identical).

The code works on Chrome.

If I change the origin parameter to "*" it works (on Chrome & Firefox).

The change fixes my problem but maybe its a bug needing to be fixed for others

**Comment by andymckay** [comment]
Is this about a WebExtensions code and a possible bug in Firefox itself? For that we use Bugzilla: https://wiki.mozilla.org/WebExtensions#Status.

We use this repository for tracking issues about addons.mozilla.org.

**Comment by eviljeff** [comment]
this isn't an addons website bug.
