### ISSUE TITLE
[Blocklisting] No security warning displayed for a softblocked WebExtension in about:addons.

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3776]
Steps to reproduce:
1. Load the page: (https://addons.allizom.org/en-US/firefox/addon/blocklistandroid3/)  
2. Tap “Add to Firefox”
3. Navigate to about:addons and tap on the installed WebExtension/Add-on.

Expected results:
The WebExtension/Add-on is installed and a security warning message is displayed in detailed page of the WebExtension/Add-on.

Actual results:
The WebExtension is installed but there is no security warning message displayed in detailed page of the WebExtension/Add-on.

Notes/Issues:
Verified on AMO-stage FF49(Android 4.2.1).
This issue is reproducing for Add-ons as well.

**Comment by muffinresearch** [comment]
@cosminbadescuSV can you provide a screenshot of the the page you're referring to?

From the description it sounds like you're referring to a bug in the browser details page? If so a bug should be filed in bugzilla instead of here since that's a bug in platform code.

**Comment by cosminbadescuSV** [comment]
Here are some screenshots:

Mobile
![screenshot_2016-10-19-11-45-43](https://cloud.githubusercontent.com/assets/15885467/19512021/ab62c7f0-95f2-11e6-8b7e-7ed0e2898abb.png)


Desktop
![2016-10-19_1156](https://cloud.githubusercontent.com/assets/15885467/19512138/1b4ce956-95f3-11e6-979a-b15f082b72c7.png)

For desktop I used unbraded build.

**Comment by muffinresearch** [comment]
Can you verify that the blocklist has been updated correctly on the device? Looking at https://wiki.mozilla.org/Blocklisting/Testing#Testing_on_Android getting android to update is a different process?

**Comment by cosminbadescuSV** [comment]
Yes for Android is a different process, as presented in https://wiki.mozilla.org/Blocklisting/Testing#Testing_on_Android. Severity for this WebExtension is set to 1, extensions.autoupdate.interval is set to 60 seconds.
I am not sure how could I verify if the blocklist is updated correctly, but I can see that the behaviour is correct and the only issue is related about the message.
Do you have any suggestion how can I check if the blocklist is updated correctly?

**Comment by muffinresearch** [comment]
@cosminbadescuSV I would think you could look at the profile on the filesystem via adb, but you'd probably need root for that.

A trick you can use without root is to use firefox android to look at it's own files:

Go to this url in the browser: `file:///data/data/org.mozilla.firefox/files/mozilla/`.

Then find the profile - usually the one ending default. Tap on the `whatever.default` and then you should see the blocklist.xml from there and you can look at it by tapping on it to load it in firefox android.

Is there an example of an add-on blocked in production that works correctly on android?

**Comment by muffinresearch** [comment]
If you're using nightly substitute `org.mozilla.firefox` with `org.mozilla.fennec` and open the files in nightly too since you'll get permission denied if you try and open the nightly files from regular FF android.

**Comment by cosminbadescuSV** [comment]
In both cases the ID from this WebExtension is present in the blocklist.xml file.
Thanks for the help!

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/15885467/19520911/7e2a58de-961a-11e6-80ab-0457695736a9.png)

Fennec:
![fennec](https://cloud.githubusercontent.com/assets/15885467/19520913/83f9521a-961a-11e6-9de9-9dbd2c039bc1.png)

**Comment by Natim** [comment]
This look like a bug that we should file in Firefox especially if the item is present in the blocklist file.

**Comment by muffinresearch** [comment]
@cosminbadescuSV is this still reproducible?

**Comment by cosminbadescuSV** [comment]
@muffinresearch following the instructions from https://wiki.mozilla.org/Blocklisting/Testing#Testing_on_Android , I can see that the blocklist.xml file does not contain the ID of the blocklisted WebExtension ( https://addons.allizom.org/en-US/firefox/addon/blocklistandroid3/ ) or the ID for the new blocklisted WebExtension ( https://addons.allizom.org/en-US/firefox/addon/blocklistandroid99/ ).
The behavior of the blocklisted WebExtensions is the same as presented in the actual result.

In this case I am not sure if this is the correct behavior.

**Comment by muffinresearch** [comment]
@cosminbadescuSV when were those blocks added?

**Comment by cosminbadescuSV** [comment]
After following the steps from https://wiki.mozilla.org/Blocklisting/Admin#Extension_blocks the ID (The ID from the WebExtensions was automatically generated) of the WebExtensions ( https://addons.allizom.org/en-US/firefox/addon/blocklistandroid3/ and  https://addons.allizom.org/en-US/firefox/addon/blocklistandroid99/ ) are present in blocklists-preview bucket, but are not present in the xml.file.
These WebExtensions were blocked recently as you can see in the video.
The same issue is also for Android.
 Here is a video with this issue: 
![block](https://cloud.githubusercontent.com/assets/15885467/23617676/855dbbf8-0296-11e7-81c2-f4d131b8dc59.gif)

**Comment by Natim** [comment]
> are present in blocklists-preview bucket

Were your changes actually reviewed by someone? Are you using the XML preview URL or the production one?

**Comment by Natim** [comment]
Is it supposed to be present here: https://settings.prod.mozaws.net/v1/preview/3/%7Baa3c5121-dab2-40e2-81ca-7ea25febc110%7D/51.0.1/ ?

**Comment by cosminbadescuSV** [comment]
> **Were your changes actually reviewed by someone? Are you using the XML preview URL or the production one?**


 -The changes were reviewed by me. 
 -We only have access to https://kinto-writer.stage.mozaws.net/v1/admin , a bug was filed ( https://bugzilla.mozilla.org/show_bug.cgi?id=1344167 ) so we can have access to kinto-writer.stage. 
 -The blocklisted WebExtension ( https://addons.allizom.org/en-US/firefox/addon/blocklistandroid3/ ) is present in blocklists-preview/addons for testing and review 
![blocklists-preview_addons](https://cloud.githubusercontent.com/assets/15885467/23648569/f0300b2e-0323-11e7-86ee-bcf10571a176.png)
 and was also deployed to the final blocklists bucket 
![blocklist_addons](https://cloud.githubusercontent.com/assets/15885467/23648614/16ac6aea-0324-11e7-82ab-069728f75ad7.png)


> **Is it supposed to be present here: https://settings.prod.mozaws.net/v1/preview/3/%7Baa3c5121-dab2-40e2-81ca-7ea25febc110%7D/51.0.1/ ?**


 -It supposed to be present here: https://settings.stage.mozaws.net/v1/preview/3/%7Baa3c5121-dab2-40e2-81ca-7ea25febc110%7D/51.0.1/  and it is 
![xmlweb](https://cloud.githubusercontent.com/assets/15885467/23648714/77cb472e-0324-11e7-8e21-86c29b4a65a7.png)


> **I don't see anything in add-ons that is targetting android: https://settings.prod.mozaws.net/v1/buckets/blocklists/collections/addons/records**


 -In https://settings.stage.mozaws.net/v1/buckets/blocklists/collections/addons/records it is listed 
![json](https://cloud.githubusercontent.com/assets/15885467/23648824/d4a93bd6-0324-11e7-8411-345e7b5304d8.png)

**Comment by Natim** [comment]
Ok so if it is in the blocklist file where is the issue?

**Comment by cosminbadescuSV** [comment]
The issue is with the blocklist.xml local file from my PC, it is not updated with the new ID that is blocklisted. 
As I said earlier the I followed the steps from https://wiki.mozilla.org/Blocklisting/Admin#Staging and tested after the steps from https://wiki.mozilla.org/Blocklisting/Admin#Testing .

**Comment by Natim** [comment]
Can you try using https://github.com/leplatrem/aboutremotesettings to force an update of the XML file?

**Comment by cosminbadescuSV** [comment]
On desktop using https://github.com/leplatrem/aboutremotesettings works! The blocklist,xml file is updated.
Here are some screenshots:
![worksdesktop](https://cloud.githubusercontent.com/assets/15885467/23653738/3c3c42dc-0336-11e7-9890-304cc7ecefa0.png)

Also the ID is present in the blocklist,xml.
![worksdesktop2](https://cloud.githubusercontent.com/assets/15885467/23653780/5481a2ec-0336-11e7-99d7-a34fff217507.png)

On mobile the update is made in the blocklist,xml but there is no security message displayed in about:addons. 
In this case this issue is still reproducible.
Here is a video for this issue:
![andro](https://cloud.githubusercontent.com/assets/15885467/23654512/afaa02f6-0339-11e7-8f4c-3e92cbd9a83c.gif)

Thanks @Natim for the help!

**Comment by Natim** [comment]
I filled https://bugzilla.mozilla.org/show_bug.cgi?id=1345092 so that the Android team can have a look at it.

**Comment by EnTeQuAk** [comment]
> I filled https://bugzilla.mozilla.org/show_bug.cgi?id=1345092 so that the Android team can have a look at it.

Closing because of that and because it's now unrelated to AMO.
