### ISSUE TITLE
"Mobile Add-ons" page still available in AMO

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3777]
Steps to reproduce:
1. Submit an add-on compatible with mobile (_not_ Firefox for Android) i.e. https://addons-dev.allizom.org/en-US/mobile/addon/full-screen-test-mobile/

Expected results:
User cannot submit the add-on or it is not available in public pages according to #3244 .

Actual results:
User is able to submit and review the add-on. Add-on is listed in public pages under "Mobile Add-ons " page.

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing all around AMO servers.
Screenshots for this issue: 
![categories](https://cloud.githubusercontent.com/assets/15685960/19430336/8b341ac0-945c-11e6-9a66-677ca53c7110.png)
![public_pages](https://cloud.githubusercontent.com/assets/15685960/19430337/8b350dea-945c-11e6-97a7-3eda164c6299.png)
![otherapps](https://cloud.githubusercontent.com/assets/15685960/19430462/fd63d6ee-945c-11e6-9946-9e36bcbede45.png)

**Comment by EnTeQuAk** [comment]
We never removed things like that, that's true. There was some work going on in https://github.com/mozilla/addons-server/issues/3360 but that only covered fennec specific categories for now.

@jvillalobos just making sure, all that should and can be removed?

**Comment by jvillalobos** [comment]
It should be okay to remove support for the old mobile platform, but that might not be worth the effort right now. We plan to make big changes on the site next year, and this will probably be included.

**Comment by EnTeQuAk** [comment]
adding it to `triaged` to maybe track it for the next refactor coming up next year.

**Comment by ValentinaPC** [comment]
We can also access Mobile Add-ons pages using a direct URL: https://addons.allizom.org/en-US/mobile/extensions/

**Comment by muffinresearch** [comment]
It's not possible any more AFACT.
