### ISSUE TITLE
WebExtension upgrade annotation breaks if upload.version is None

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3778]
Sentry error: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/351771/

`FileUpload.version` can be `None` at times (apparently, there's a comment stating that but I didn't see that at the time) which breaks the annotation function since we can't find a previous version for this upload.

**Comment by EnTeQuAk** [comment]
I have the feeling that this is related to https://github.com/mozilla/addons/issues/252 and https://github.com/mozilla/addons-server/issues/3774

**Comment by ValentinaPC** [comment]
After making the changes that I've suggested in #3774 I was able to submit and update the attached add-on.
@EnTeQuAk 
Not sure what "`FileUpload.version`" being "`None`" means, can you please tell me?

But, I've tried to delete the `version` element from the manifest, I receive a 500 server error at submission or update. Not letting the user know what happened is not ok.
Please let me know if this is the case, or should be logged separately:
 
![2016-10-20_1309](https://cloud.githubusercontent.com/assets/15685960/19555687/8b88097a-96c6-11e6-9a1d-fb0acbe7981d.png)

**Comment by EnTeQuAk** [comment]
@ValentinaPC sorry for not providing clear qa instructions, I forgot about that.

Removing `version` from the manifest is exactly what this means so you correctly reproduced this :)

I reopened this as there's another place that needs to deal with that, looking at https://sentry.prod.mozaws.net/operations/olympia-dev/issues/360475/ - I'll fix this.

**Comment by ValentinaPC** [comment]
While not having a `version` property in manifest.json I receive another error at submission in AMO-dev FF49(Win 7):
![2016-10-26_1305](https://cloud.githubusercontent.com/assets/15685960/19721940/1b771b2e-9b7d-11e6-9bdd-d69a2a9ff111.png)

Is this the fix? :smile:

**Comment by EnTeQuAk** [comment]
That's actually another error, I get the feeling that none of our code ever supported optional versions. Just making sure, a missing version is actually a thing we officially support? Is that documented somewhree? :laughing:

**Comment by ValentinaPC** [comment]
I know you did not asked me, but from my opinion, even if we do not support missing version, we can tell the user why its submission stopped. :smile_cat:

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49.0.2(Win 7) for add-on and webextensions.
Postfix screenshots:
![add-on](https://cloud.githubusercontent.com/assets/15685960/19846807/efe471ce-9f4a-11e6-8b88-47b14d08977b.png)
![webext](https://cloud.githubusercontent.com/assets/15685960/19846808/efe51a7a-9f4a-11e6-80a5-af91c1c095f3.png)
