### ISSUE TITLE
WebExtension with no version string fails

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3779]
I just noticed https://sentry.prod.mozaws.net/operations/olympia-prod/issues/349393/ which is weird since `version` is a required attribuite as far as I can see in the `addons-linter` so it shouldn't come to this.

Investigating.

**Comment by EnTeQuAk** [comment]
Maybe related? https://sentry.prod.mozaws.net/operations/olympia-prod/issues/349393/

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49.0.2(Win 7).
Postfix screnshot: 
![webext](https://cloud.githubusercontent.com/assets/15685960/19847081/ccf4a952-9f4c-11e6-9786-455e41866d39.png)
