### ISSUE TITLE
Don't attempt to load translations from invalid json files

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3780]
Sentry issue: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/344330/

This will be less of an issue if https://github.com/mozilla/addons-linter/issues/701 get's implemented but we should not attempt to load an invalid translations json or at least fail with something better than an 500 server error.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa:not needed" ?

**Comment by vcarciu** [comment]
Verified as fixed :  
![confirm approval](https://cloud.githubusercontent.com/assets/1583842/26154065/b085972a-3b16-11e7-9348-1cea4f5c7c33.gif)

**Comment by EnTeQuAk** [comment]
STR:

* Create a WebExtension with `_locales` and damage one of the `messages.json` (e.g remove some parts of it or so, make it invalid JSON)
* Try to upload (new add-on or an update, doesn't matter) that WebExtension, the add-on should now ignore the failed locale and continue validation.

Before this fix we returned a "Unexpected error" while validating.

**Comment by vcarciu** [comment]
The validation is still failed, even if now the message is more clear, saying that you have invalid JSON files : 
![invalidjson](https://cloud.githubusercontent.com/assets/1583842/26252803/f0a5f634-3cb9-11e7-91e4-9e71999cf294.png)

**Comment by EnTeQuAk** [comment]
That message should only me raised if you have a invalid `manifest.json`, mind uploading the add-on you tried?

**Comment by vcarciu** [comment]
@EnTeQuAk : 
[dpnopermissions-1-an+fx.zip](https://github.com/mozilla/addons-server/files/1014676/dpnopermissions-1-an.fx.zip)

**Comment by EnTeQuAk** [comment]
@vcarciu heh, you made the `manifest.json` file invalid, that's not what this issue is actually about and the error for that is expected. Please make the `_locales/en/messages.json` invalid and you should not run into any errors imho.

**Comment by vcarciu** [comment]
@EnTeQuAk : _locales/en/messages.json was the file made invalid for my testing . Please see the error from full validation report : 
![locale](https://cloud.githubusercontent.com/assets/1583842/26589927/f217a93a-4561-11e7-9208-95e80890aea7.png)

**Comment by EnTeQuAk** [comment]
Actually, that is the expected output for this. I just wasn't sure if the linter would complain - it does which is good. The original problem was that instead of a proper error like you get now the user got a 500 server error presented.

I'm going to close this as I think you just verified it's fixed, I just wasn't sure what to expect, sorry about that!
