### ISSUE TITLE
Link initial page Yahho dont work (installation)

### ISSUE THREAD

**Issue by tubrik** [mozilla/addons-server#3781]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Link dont work (initial page Firefox):
https://downloads.yahoo.com/unifiedUpsells/ext_firefox/?intl=br&ctid=%257b3122CF7F-DCE3-7F46-99E8-7127C2EB38C8%257d

**Comment by muffinresearch** [comment]
Hi, we aren't responsible for the content of other sites. If you have more details that show there's something wrong at our end please let us know.
