### ISSUE TITLE
Add links for reviewers and admins

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3782]
Since webextensions are not allowed anylonger to inject content-scripts into AMO, reviewers and admins are lacking simple but important features needed to facilitate daily work.
- [x] Add "Review" (`https://addons.mozilla.org/editors/review/SLUG`) and "Admin" (`https://addons.mozilla.org/admin/addon/manage/SLUG`) links to listing pages.

Example of how [AAA](https://addons.mozilla.org/en-US/firefox/addon/amo-admin-assistant) did this:
![screen shot 2016-10-17 at 13 06 07](https://cloud.githubusercontent.com/assets/873258/19435376/9aedb850-946a-11e6-8c18-05bbe8fd5444.png)

Note that admins already have a "Manage" button, so for them it looks like:

![screen shot 2016-10-17 at 13 09 10](https://cloud.githubusercontent.com/assets/873258/19435452/fd712f98-946a-11e6-8cf0-4768772710e4.png)

For add-on listing 404 pages, it looks like:

![screen shot 2016-10-17 at 13 13 39](https://cloud.githubusercontent.com/assets/873258/19435552/94748a16-946b-11e6-963f-563cc7995bca.png)

Author-disabled add-ons should be covered as well, but I don't have an example for that.

---
- [x] Add the same links to the sidebar of a developer edit page for an add-on.

Example:

![edit_listing____add-on_review_helper____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/873258/19435485/27d66262-946b-11e6-9894-869b9ef27be7.png)

---

At least, those links should be visible to reviewers and admins (iirc `staff` group or the respective permission?) only, not to normal users. Bonus points if we show links to admin pages for admins only.

**Comment by eviljeff** [comment]
reviewers (users with just `Addons:Review`) wouldn't have access to the devhub edit page anyway

**Comment by wagnerand** [comment]
Yeah, they would get an error page, which is why it would make more sense to not show them the links in the first place, but it's also bit more effort to implement.

**Comment by wagnerand** [comment]
Note that links for 404 pages and disabled add-ons are not implemented yet.

**Comment by jvillalobos** [comment]
This was done in the old front end, and for the new one is being tracked on https://github.com/mozilla/addons-frontend/issues/2756.
