### ISSUE TITLE
TypeError: e.split is not a function

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3785]
STR:

Use a non Firefox browser to vist the following:

dev:  https://addons-dev.allizom.org/en-US/firefox/search/?q=foo&cat=1%2C0&appver=&platform=
stage: https://addons.allizom.org/en-US/firefox/search/?q=foo&cat=1%2C0&appver=&platform=
prod: https://addons.mozilla.org/en-US/firefox/search/?q=foo&cat=1%2C0&appver=&platform=

You will see the following error in the console:

```
TypeError: e.split is not a function
```

**Comment by ValentinaPC** [comment]
Verified as fixed on **AMO-dev** using Chrome Version 53.0.2785.143 m (Win 7)
Postfix screenshot: 
![split](https://cloud.githubusercontent.com/assets/15685960/19466930/fcd326c0-9516-11e6-87a0-94f1803a5fce.png)
