### ISSUE TITLE
[Blocklisting] Softblocked add-on is installed normally

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3787]
Steps to reproduce:
1. Soft-block an add-on on AMO-stage i.e. https://addons.allizom.org/en-US/firefox/addon/add-on-sev1-popup/ (blocklist item: https://addons.allizom.org/en-US/admin/models/blocklist/blocklistitem/826/)

Expected results:
A popup window with the option "Install anyway" appears and user can choose whether to install or not the add-on. If installed, it is automatically disabled for security and stability reasons.

Actual results:
Add-on installation is made as usual; no blocking window displayed. 

Notes/Issues:
After installation the add-on behaves normally. 
Verified on Nightly 52.0a1 - 17.10.2016 (Win 7) using AMO-stage.
Video fro this issue: 
![softblock](https://cloud.githubusercontent.com/assets/15685960/19466384/33e3aecc-9513-11e6-97ff-1b1e6410f600.gif)

**Comment by muffinresearch** [comment]
Do you have a screenshot of the _expected_ behaviour? It's unclear to me if "popup" refers to something in the site or something the browser does.

**Comment by ValentinaPC** [comment]
Unfortunately, I have not.
We receive explanation about how softblock should behave, but not mocks... maybe the person who is in charge with blocklisting should know the exact form o the window?

**Comment by muffinresearch** [comment]
@ValentinaPC do you have a link to any docs/sources that you're using as a reference? 

Looking at https://wiki.mozilla.org/Blocklisting#What_users_will_see (and assuming it's still relevant) it shows a doorhanger with similar copy to what you mention though looks to only relate to hard blocks.

**Comment by ValentinaPC** [comment]
I was talking about this window for - softblock:
![2016-10-18_1700](https://cloud.githubusercontent.com/assets/15685960/19481105/825dd504-9555-11e6-87b3-1298b119a253.png)

Checked this on Win 10 and seems to work as expected.
I'll recheck on my system and come back with a comment.

**Comment by jvillalobos** [comment]
Did you make sure the blocklist was updated before trying to install the add-on?

**Comment by ValentinaPC** [comment]
@jvillalobos : Of course.

Today, I was not able to make a blocklist from beginning to end.
Why? Because from some reason the blocklist item is added but the add-on is not blocked.
So, I don't have any news about the softblock window.

**Comment by ValentinaPC** [comment]
Finally my add-on was softblocked....related to this I have a question, just to be sure I got it right:
@muffinresearch 
-> The "blocked" window should only be displayed if the add-on is installed first and blocked after?
Because if this is the case, works as expected:
![2016-10-20_1203](https://cloud.githubusercontent.com/assets/15685960/19553695/e7e3890a-96bd-11e6-86b3-1f9e819b3688.png)

**Comment by muffinresearch** [comment]
> Finally my add-on was softblocked....related to this I have a question, just to be sure I got it right:
@muffinresearch
-> The "blocked" window should only be displayed if the add-on is installed first and blocked after?
Because if this is the case, works as expected:

I don't know 100% all the expected behaviour of the browser for block-listing - but that seems reasonable to me.

The only change being made here is the source of data. If the blocklist updates correctly and the data updates are matching the old service then what the browser does with that data shouldn't be impacted.

**Comment by ValentinaPC** [comment]
We can close this, based on above comments.
