### ISSUE TITLE
Remove  Unlisted New Add-ons and Unlisted Updates queues in editor tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#3792]
In Editor Tools we have 3 different "queues" for unlisted add-ons, in a similar vein to listed add-ons:
- Unlisted New Add-ons
- Unlisted Updates
- All (unlisted) Add-ons

Only the last one is useful nowadays since we auto-approve all unlisted add-ons and their updates by default. We should remove the extra ones, that will help #3567.

We'll figure out what modifications to make to the editor tools with the introduction of channels separately.

**Comment by vcarciu** [comment]
Verified as fixed : 
![allunlisted](https://cloud.githubusercontent.com/assets/1583842/19487272/bb3decdc-956a-11e6-9168-725101e253e7.gif)
