### ISSUE TITLE
Internal add-on detail endpoint

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3798]
The admin tools expect all of its endpoints to be nested under `/api/v3/internal/` but there is no add-on detail endpoint at `/api/v3/internal/addons/addon/<guid|slug|id>/`.

For now, that endpoint should just use the regular add-on detail view. In the future it will likely make the non-internal view only support accessing public add-ons and add-ons that the user owns while the internal one can access anything if the user is an admin.

**Comment by diox** [comment]
One thing I'd like to do later is to split up the code so that the regular detail API class doesn't handle deleted/unlisted addons, and inherit from that class in the internal code and do it there. But this is a good first step in the right direction.
