### ISSUE TITLE
New add-on submission flow follow ups

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3802]
Following up on #3468. Great job, by the way 💯.

Some tweaks:
* The developer agreement step is titled "Getting Started". Let's rename it "Firefox Add-on Distribution Agreement".
* In the same step, the printable version link should open in a new tab.
* In the "where to host" step, I made some tweaks to the "on your own" option. They're in [the doc](https://docs.google.com/document/d/1wMF2F13yfsquymQHqnjanr0vjbYF1b67kBFm6n7JqLg/edit#).
* In the upload step, the source code review policy link should open in a new tab.
* In the details step, "This add-on has a Privacy Policy:" ends with an unnecessary `:`.
* In the details step, the "Details" link for every source code license should open in a new tab.
* In the last step, I renamed "Return to My Submissions" to "Go to My Submissions", which makes more sense, since there are so many access points. I also added it to the last step for all the flows. [The doc](https://docs.google.com/document/d/1wMF2F13yfsquymQHqnjanr0vjbYF1b67kBFm6n7JqLg/edit#) should be up to date now.

**Comment by eviljeff** [comment]
> The developer agreement step is titled "Getting Started". Let's rename it "Firefox Add-on Distribution Agreement".

I dropped "Firefox" from that as it's not just Firefox Add-ons - okay?

**Comment by eviljeff** [comment]
> In the "where to host" step, I made some tweaks to the "on your own" option. They're in the doc.

Didn't I already do that?  What am I missing vs. the doc?

**Comment by jvillalobos** [comment]
I updated the first comment, keeping the upload source step, after discussion with @wagnerand. The link needs to open in a new tab, though.

**Comment by jvillalobos** [comment]
One more thing:
* For the source code upload widget, an addition to the text: `If your add-on contains binary... for review. Please include instructions on how to reproduce the final add-on file, either in a README file or the Notes to Reviewer for this version.`

**Comment by vcarciu** [comment]
I went through the follow ups and I observed some issues :

In Choose listed or Unlisted page , for Unlisted the text requested is "On your own. Your submission will be immediately signed for self-distribution. Updates should be handled by you via an updateURL or external application updates." The text on -dev is "On my own. This version will be immediately signed for self-distribution. Updates should be handled by you via an updateURL or external application updates."

Also , at the end of Unlisted submission flow in the linked doc we have 
"[If platforms were chosen] You selected only some of the available platforms for this submission. You can upload more files that target other platforms:

[Upload File][/If platforms were chosen]" , which is not happening.

Please see video for the issue:

![followups](https://cloud.githubusercontent.com/assets/1583842/19605465/e44f80b8-97c2-11e6-8ac5-28d535eecc32.gif)
