### ISSUE TITLE
[Blocklisting] WebExtensions with generated ID and softblocked are not disabled after install

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#3808]
Steps to reproduce:
1. Load the page: https://addons.allizom.org/en-US/developers/addon/blocklistandroid26/
2. Tap “Add to Firefox”
3. Navigate to about:addons.

Expected results:
The WebExtension is installed and disabled after the install.

Actual results:
The WebExtension is installed but enabled after the install.

Notes/Issues:
Verified on AMO-stage FF52(Android 6.0.1).
Here is an example of WebExtension with the ID added in the manifest.json file. https://addons.allizom.org/en-US/firefox/addon/blocklistandroid3/
In both cases the severity is set to 1 (softblock).
Here are some screenshots:

Mobile
![mobile](https://cloud.githubusercontent.com/assets/15885467/19523864/80c939e8-9624-11e6-8509-7bc10169dc94.png)

Desktop
![desktop](https://cloud.githubusercontent.com/assets/15885467/19523871/875b0c8c-9624-11e6-88b5-ef052c9a9a24.png)

**Comment by eviljeff** [comment]
https://bugzilla.mozilla.org/buglist.cgi?component=Blocklisting&product=Toolkit&list_id=13475633
