### ISSUE TITLE
[Android] Last addons from search suggestions are not visible when keyboard is opened

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3809]
Steps to reproduce:
1.Open AMO Stage on Android
2.Be sure that you already have some search suggestions from earlier searches
3.Tap on "Search for add-ons" searchbox

Expected results:
After taping on search box, the keyboard is opened and search suggestions are moved upside of search box. All suggestions should be visible when scrolling

Actual results:
Last 2 suggestions are not visible even if user scrolled at maximum

Please see how it looks after scrolling : 
![androsearch](https://cloud.githubusercontent.com/assets/1583842/19524842/bb6ea1f2-9627-11e6-89eb-55d85184ee50.png)

**Comment by muffinresearch** [comment]
This looks like it's a browser bug than a code issue bug since we're just using the standard control `<input type="search">`.  The display of recent searches is done entirely by the browser.

**Comment by EnTeQuAk** [comment]
Closing as wontfix since all that is or at least will be reimplemented by addons-frontend
