### ISSUE TITLE
Different width of Categories section when scrolling through an Editor Review page for an add-on

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3810]
Steps to reproduce:
1.Login to AMO Stage as an Administrator
2.Go to details page for an add-on like https://addons.allizom.org/en-US/firefox/addon/stylish/?src=hp-dl-featured
3.Press the Editor Review button
4.While scrolling in the Editor Review (https://addons.allizom.org/en-US/editors/review/stylishpage), observe the Categories section from the right side

Expected results:
Categories width is consistent while scrolling through the page

Actual results:
Categories width is changing while scrolling

Please see a video for this bug : 
![widthcat](https://cloud.githubusercontent.com/assets/1583842/19526968/e83dc968-962e-11e6-8e0e-6102f161dcd6.gif)

**Comment by muffinresearch** [comment]
Since the impact is super low, I think it's very unlikely we'll actively look to address this ahead of overhauling the frontend for desktop.
