### ISSUE TITLE
Change Contribute button text colour from Editor Review page 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3811]
Steps to reproduce:
Steps to reproduce:
1.Login to AMO Stage as an Administrator
2.Go to details page for an add-on with contributions like https://addons.allizom.org/en-US/firefox/addon/stylish/?src=hp-dl-featured
3.Press the Editor Review button
4.Observe the Contribute button

Expected results:
Contribute button text is readable and white on blue background

Actual results:
Blue on blue background

Please see a photo for this issue:
![blue](https://cloud.githubusercontent.com/assets/1583842/19527454/bf639b74-9630-11e6-84a0-b069f609a1e2.png)

**Comment by andymckay** [comment]
I think there's a bug already on this somewhere and the real fix is not to bother showing this information at all.

**Comment by wagnerand** [comment]
Yup, https://github.com/mozilla/addons-server/issues/2311
