### ISSUE TITLE
Add link to theme header for admins and reviewers

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3812]
Related to #3782. If a user has `Personas:Review` permission, show a link to the header image in theme listing pages, like the [AAA add-on](https://addons.mozilla.org/addon/amo-admin-assistant/) does. This is useful for inspecting the whole image quickly.

It doesn't need to be pretty; what the add-on does is add a link next to `Add to collection`, using the same styling. Some versions of the add-on also link to the footer image, but that's no longer useful.

**Comment by eviljeff** [comment]
Looks like a dupe of https://github.com/mozilla/addons-frontend/issues/2745 now.
