### ISSUE TITLE
Test pilot promo is unstyled in the legacy discovery pane

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3819]
See https://services.addons.mozilla.org/en-US/firefox/discovery/pane/pane/48.0/strict

<img width="532" alt="_" src="https://cloud.githubusercontent.com/assets/1514/19560373/266d102a-96cc-11e6-8422-a45b3b7ac802.png">

The reason is the styles are in the restyle CSS but services.a.m.o doesn't get those styles at all.

**Comment by muffinresearch** [comment]
QA Notes:

In testing this we should make sure that the test-pilot promo on the home page and the services page (legacy disco pane) are both looking correct.

Here's the links for the legacy disco pane:

 * dev: https://services.addons-dev.allizom.org/en-US/firefox/discovery/pane/pane/46.0/strict
 * stage: https://services.addons.allizom.org/en-US/firefox/discovery/pane/pane/46.0/strict

**Comment by ValentinaPC** [comment]
Verified on AMO-dev and AMO-stage using FF49(Win 7) by setting the `extensions.webservice.discoverURL` to `https://services.addons-dev.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%` and the correspondent link for stage and observed:
STAGE
![stage1](https://cloud.githubusercontent.com/assets/15685960/19635534/b3ee2ba8-99cb-11e6-9f55-246bc1c6f1c6.png)
DEV
![dev1](https://cloud.githubusercontent.com/assets/15685960/19635536/bd2b3184-99cb-11e6-8339-9a59f2ebe94b.png)

Conclusions:
-stage is not fixed
-dev has the "test pilot" banner with the `CSS` style format, but "the pilot" seems a bit cut, nu?

@muffinresearch : we will leave this as it is?
Thanks!

**Comment by muffinresearch** [comment]
> -stage is not fixed

It's not on stage yet, it will be going out this Thursday (27th)

> -dev has the "test pilot" banner with the CSS style format, but "the pilot" seems a bit cut, nu?

Yeah this is fine.

**Comment by ValentinaPC** [comment]
Based on previous 2 comments I'll mark this as verified fixed.
