### ISSUE TITLE
Bubble background is showing through for the test-pilot promo.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3820]
There should only be one background. This was regressed in https://github.com/mozilla/addons-server/commit/4a8f2d6e235bd8af438b08995bfd6e7ab8f8d55f

Should look like this:

<img width="543" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/19561334/398a4e4e-96d0-11e6-8c24-67e3c9988213.png">

Currently looks like this:

<img width="572" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/19561369/5e617706-96d0-11e6-925a-544594f079f5.png">

**Comment by muffinresearch** [comment]
This is on -dev now.

**Comment by vcarciu** [comment]
Verified as fixed : 
![bubbble](https://cloud.githubusercontent.com/assets/1583842/19564967/f634ffd6-96ed-11e6-9725-7421d5db338b.gif)
