### ISSUE TITLE
Redirect /developers/addon/submit/1 to /developers/addon/submit/

### ISSUE THREAD

**Issue by sks939** [mozilla/addons-server#3825]
### Describe the problem and steps to reproduce it:
I was trying to find out how to submit an add-on to AMO by following a link from this page,
https://developer.mozilla.org/en-US/Add-ons/Distribution, to this page:

"New add-ons are uploaded to AMO through this [submission form](https://addons.mozilla.org/en-US/developers/addon/submit/1)_"

### What happened?
Page not found error

### What did you expect to happen?
I expected to see a web page about AMO

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
I'll update the links I can find, but we should preserve the old URL with a redirect.

**Comment by eviljeff** [comment]
You can just make it `/developers/addon/submit/`

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
For an old account with already submitted add-ons:
![1-d](https://cloud.githubusercontent.com/assets/15685960/19719227/b1dd923e-9b71-11e6-9c39-bb9739b3ff18.gif)
For a new account with no add-ons:
![new-acc](https://cloud.githubusercontent.com/assets/15685960/19719254/c8d51822-9b71-11e6-8aa9-ceea52d934cf.gif)
