### ISSUE TITLE
Fix CORS for addons-frontend login on -dev

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3826]
The CORS isn't setup correctly for logging in on -dev. The public login endpoint needs the `amo.addons-dev.allizom.org` domain allowed as it currently only allows `INTERNAL_DOMAINS` which is for the admin.

**Comment by mstriemer** [comment]
Supports https://github.com/mozilla/addons-frontend/issues/1251.

**Comment by ValentinaPC** [comment]
Please add some STR for us to test this or mark this as "needs no qa". Thanks a lot!
