### ISSUE TITLE
Amazon Add-On Button

### ISSUE THREAD

**Issue by mr-5th** [mozilla/addons-server#3829]
I previously had an add-on button that would help me access other websites and add them to my wishlists in Amazon.com. A specific link leads me to another page but then forwards me to Mozilla incompatible installation button for this internet browser.

Once the is clicked nothing happens. but, then the page reloads and takes me to the incompatible add-on page in Mozilla site.

I expected the link to install the ad-on and lead through the steps to add the Amazon button.
![screen shot 2016-10-20 at 5 28 46 pm](https://cloud.githubusercontent.com/assets/22968148/19578663/c567884a-96ea-11e6-92b7-e2a118377fb1.png)
![screen shot 2016-10-20 at 5 28 46 pm](https://cloud.githubusercontent.com/assets/22968148/19578666/c7aaac0e-96ea-11e6-9e58-fcec201c5734.png)
![screen shot 2016-10-20 at 5 30 41 pm](https://cloud.githubusercontent.com/assets/22968148/19578689/dac5f1c2-96ea-11e6-9fe7-37732c6187e1.png)

**Comment by muffinresearch** [comment]
Hi @mr-5th, the add-on has been removed by the author - see https://addons.mozilla.org/en-US/firefox/addon/add-to-amazon-wish-list-button/ 

You would have to contact the add-on author for more information.
