### ISSUE TITLE
Review queue page cleanup

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3831]
In London we discussed what could be done to reduce information overload for editors and what's really relevant for them.

People agreed on removing the following:
- [x] Columns in queue view: Platform, Additional, Application, Version Notes.
- [x] Search filters.

The first one seems easy.
I don't remember the details about the search filters. Do want to remove them entirely? At least _Platforms_ and _Max. Version_ don't seem to useful to me.

Adding @kewisch @jvillalobos.

**Comment by wagnerand** [comment]
For reference, the current advanced search looks like:

![screen shot 2016-10-21 at 16 33 44](https://cloud.githubusercontent.com/assets/873258/19602106/372234f0-97ac-11e6-8210-5a3a2be5e4fa.png)

**Comment by diox** [comment]
Note: when working on removing the columns in the queue view, don't forget to remove the relevant parts in the SQL query that is made as well. It does joins all over to fetch the extra information, so simplifying it would be great for perf.

**Comment by jvillalobos** [comment]
I would remove all filters except Name, Admin Flag, and Application (since we're removing the column). The others are either unnecessary or easy to figure out with little scrolling.

**Comment by wagnerand** [comment]
@jvillalobos Let's keep "Add-on Types" as well for the time being. I think we can revise that next year, but for now it seems useful for reviewers than focus on themes.

**Comment by jvillalobos** [comment]
Fine with me.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7).
1. Some review queue columns were removed, remaining as displayed in the next screenshot:
![2016-10-25_1617](https://cloud.githubusercontent.com/assets/15685960/19687622/db9a9f70-9ace-11e6-90c4-d6e144e14ea6.png)
2. Advanced search simplified for listed and unlisted queues, as displayed in the next screenshots:
![listed](https://cloud.githubusercontent.com/assets/15685960/19687924/2a357280-9ad0-11e6-8410-b574f6664551.png)
![unlisted](https://cloud.githubusercontent.com/assets/15685960/19687928/2db5ab96-9ad0-11e6-9032-8cddcdb4a1b3.png)

Also, search works as expected.
