### ISSUE TITLE
"use original" profile photo link is misaligned

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3835]
### Describe the problem and steps to reproduce it:
The **use original** link when you have set a profile photo but not yet submitted is misaligned.

1. Click **Choose Photo...**
2. Upload a photo
3. The **use original** link appears

### What happened?

The **use original** link is misaligned and incorrectly capitalised.

### What did you expect to happen?

The **use original** link should be under the **Choose Photo...** button like the **Delete current photo** link.

The text of the link should start with an uppercase letter as well **Use original** not **use original**.

### Anything else we should know?
<img width="468" alt="screenshot 2016-10-21 13 08 13" src="https://cloud.githubusercontent.com/assets/211578/19607504/eb8a9f58-978f-11e6-85cc-e85ccb4586be.png">
> **use original** link

<img width="462" alt="screenshot 2016-10-21 13 12 28" src="https://cloud.githubusercontent.com/assets/211578/19607527/11baa916-9790-11e6-9542-926cd6edfafc.png">
> **Delete current photo** link

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
Postfix screenshot: 
![use](https://cloud.githubusercontent.com/assets/15685960/19635305/f7caf1aa-99c9-11e6-8a0a-af7806f43636.png)
