### ISSUE TITLE
Feeling Lucky Fixer

### ISSUE THREAD

**Issue by Booboo13** [mozilla/addons-server#3837]
I am attempting to set Mozilla Firefox up with all of the goods and gadgets (most of all I am looking for a PDF program that will allow me to print them every time other than Adobe Acrobat DC - they wan t a minimum of $10.00 a month with an yearly commitment).

From the Mozilla Firefox home page I chose ADD-ons icon at the bottom of the page which took me to Add-ons Manager.  Several add-ons with brief descriptions were shown.  At the bottom of the page was a light blue box that read "See more add-ons!".  Upon clicking the box, Add-ons for firefox came up.  Again, several add-ons with descriptions were listed, including:  "Feeling Lucky Fixer".  According to the description was closer to what I wanted than anything else I had seen since starting my search.  And what do I get when I go to check it out??  

      " Feeling Lucky Fixer
        Feeling Lucky Fixer Project Image
        Feeling Lucky Fixer is the ultimate tool to bring back the default I’m Feeling Lucky searches 
        on Firefox and Flock for OpenDNS service subscribers with a quick and easy solution.
        OpenDNS is great service as providing safer and faster surfing experience for web users. 
        However when it comes, it brings a big headache for Firefox and Flock users. You can’t 
        use I’m Feeling Lucky searches in address bar any more after registering OpenDNS. All 
        the keywords redirect to OpenDNS Guide page.
        I have created an extension that will fix this problem in seconds for Firefox and Flock. 
        Install the extension, restart your browser and bring I’m Feeling Lucky searches back to 
        your Firefox and Flock.
        Extension will bring back the default keyword browsing usage to Firefox. All you need to 
        use extension is typing a keyword in location bar that describes your visit site best (e.g.
        yahoo mail) and pressing Enter."

OpenDSN is **NOT** what I want and to the best of my knowledge it has not been installed on my computer.  A more thorough search will be done and if ir is found . . . we may be short on IT personnel come Monday morning.

I have tried several times going the way I outlined above but an unable to find the add-on that way.  Finally found it in a web search at:  barisderin,com/?p=3.  It is the second box from the left in the top row.

When you figure out how I should proceed, please let me know.  Thank you in advance for your prompt attention to this matter!!

Booboo13
aka:  kfischer713@yahoo.com

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
This issue tracker is for dealing with bugs related to the addons.mozilla.org website and we can't answer questions about specific add-ons here. However, you might find some answers to your question here:  https://support.mozilla.org/en-US/kb/view-pdf-files-firefox
