### ISSUE TITLE
Remove 'site-specific' flag from devhub

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3841]
#3839 removed the flags _site-specific_ and _requires external software_ from the review queue. According to @eviljeff the only other place we use this is in the devhub, so we should remove them there as well, making devhub easier, yay!

Adding @jvillalobos.

**Comment by diox** [comment]
See also this old issue about the same subject https://github.com/mozilla/addons-server/issues/1920

**Comment by jvillalobos** [comment]
Lets get rid of them.

**Comment by wagnerand** [comment]
Actually since webextensions will have nativeMessaging, maybe let's keep 'external-software' for a little while and see whether it would be useful.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
The "external-software" flag is still listed in the Tehnical Details section from Dev Hub:
![ext-soft](https://user-images.githubusercontent.com/15685960/28317159-7e2087e8-6bce-11e7-833c-3166d46b233e.png)
@diox : In what concerns the "site-specific" flag that was listed only in Reviewer Tools pages...not sure that I can check this....no trace of this flag in stage or dev. I do not recall seeing it in the past, either.

**Comment by ValentinaPC** [comment]
from irc: 
`mat  -  you're right that it was never shown to end-users`

We can mark this verified fixed, because the rest of the issue was fixed as shown in the above screenshot.
