### ISSUE TITLE
Intruder "." in add-on download link from yahoo e-mails returns 404 page at click

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3842]
Steps to reproduce:
1. Submit an unlisted add-on in AMO-prod https://addons.mozilla.org/en-US/developers/addon/submit/distribution using an account with yahoo mail
2. Check your e-mail

Expected results:
There is an e-mail from `amo-editors@mozilla.org ` about automatic validation. There is also a link that redirects to "Manage Status & Versions" page from Edit Listing, if you want to download your add-on.

Actual results:
Link does not work at click, because a point is also included in the URL and user is redirected to a 404 page.

Notes/Issues:
I could not check for listed add-ons because I don't have admin rights.
Not reproduced for accounts using gmails.
Verified on AMO-prod FF49(Win 7).
Screenshot for this issue: 
![2016-10-24_1341](https://cloud.githubusercontent.com/assets/15685960/19643126/5667ecf0-99f1-11e6-8b41-bae02fba2bcd.png)

**Comment by wagnerand** [comment]
Meh, stupid email clients.

**Comment by ValentinaPC** [comment]
Verified as fixed in AMO-dev using fake mail admin tool - https://addons-dev.allizom.org/en-US/admin/mail
A space was added at the end of the URL, before the end of the sentence, marked with `.`
Postfix screenshot: 
![dev-fakemails](https://cloud.githubusercontent.com/assets/15685960/19680683/672dab92-9aaf-11e6-95e7-6a150767eb2f.png)
