### ISSUE TITLE
[DevHub Landing] Implement waffle switch

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3848]
Supports https://github.com/mozilla/addons-frontend/issues/1021

Implement a waffle switch to be able to work on the new devhub landing pages incrementally.

**Comment by ValentinaPC** [comment]
The waffle was introduced (can hardly wait to see how it looks)
Postfix screenshot: 
![newwaffle](https://cloud.githubusercontent.com/assets/15685960/20175616/584b88de-a74c-11e6-9064-25681bc7ce08.png)
