### ISSUE TITLE
[DevHub Landing] Whats New section

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#3852]
Supports https://github.com/mozilla/addons-frontend/issues/1021

Implement "what's new" section for the logged in state.

**Comment by EnTeQuAk** [comment]
This already landed, closing.

**Comment by atsay** [comment]
@EnTeQuAk let's update the content to the following (I previously mistakenly put this feedback on [#1021](https://github.com/mozilla/addons-frontend/issues/1021):

Happy New Year! See what's in store for add-ons in 2017
Button: Show me (https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/)

WebExtensions are now the standard for add-on development in Firefox. You'll need to update your legacy add-ons to stay compatible.
Button: Learn how (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on)
