### ISSUE TITLE
Developer can't switch to unlisted

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3854]
### Describe the problem and steps to reproduce it:
A developer  cannot switch their add-on to _unlisted_. The current status of the add-on is _hidden_, I am not sure whether that is related or not.

### What happened?
https://addons.mozilla.org/en-US/developers/addon/ziskejte-cz-cashback/unlist responds with 500.

### What did you expect to happen?
User should be able to switch to _unlisted_

### Anything else we should know?

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/348929/

https://addons.mozilla.org/en-US/developers/addon/ziskejte-cz-cashback/versions

**Comment by muffinresearch** [comment]
@eviljeff could you see if this is something that could be fixed for this week's push?

**Comment by eviljeff** [comment]
pretty sure @diox fixed this in https://github.com/mozilla/addons-server/pull/3804/files#diff-d44d7c61debbafff179eff98c046d0b6L388

**Comment by diox** [comment]
Yeah - also the correct line is https://github.com/mozilla/addons-server/pull/3804/files#diff-d44d7c61debbafff179eff98c046d0b6R414

**Comment by diox** [comment]
Side note: it's indeed happening because the add-on is *hidden*, or more precisely because its latest version is disabled, causing `find_latest_version()` to return `None`. 

@eviljeff noted this particular problem could happen when reviewing #3804 so I included a fix in there.

**Comment by wagnerand** [comment]
Great, let's close this, then!

Thanks everyone.

**Comment by vcarciu** [comment]
Verified as fixed : 
![unlist](https://cloud.githubusercontent.com/assets/1583842/19773803/8fb5e8fc-9c73-11e6-85a9-b5cd3a682606.gif)
