### ISSUE TITLE
Extension Defender no longer works

### ISSUE THREAD

**Issue by JimInSanDiego** [mozilla/addons-server#3856]
I installed Extension Defender in the last few versions of Firefox and found the extension no longer works.  When I click to scan, a process seems to begin but never finishes.  Once I let it run for 20 minutes and it never finished.  Their website http://extensiondefender.com no longer works also.

**Comment by muffinresearch** [comment]
This issue tracker is for issues related to the addons.mozilla.org website only, and we are unable to provide support for individual add-ons. 

Usually I'd recommend contacting the add-on developer for support but unfortunately in this case there appears to be no support information given: https://addons.mozilla.org/en-US/firefox/addon/extension-defender/
