### ISSUE TITLE
Remove region code

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3865]
I believe the region code is leftover from Marketplace. We should remove any references to region and database columns. A cursory grep shows references in stats, notifications and users. DB columns in stats and users.

@diox I don't see this being used and it looks like Marketplace but let me know if we're using it.

**Comment by diox** [comment]
Yeah, it's a leftover from Marketplace. I didn't know it was still there...

**Comment by diox** [comment]
Those fields and associated code were removed a few months ago in f582ab5cec7bcab6a343a1780da25fdac839337f and b838f3efb7c92fdc6595bcd36971d17c89a1f131
