### ISSUE TITLE
Summary field doesn't appear during add-on submission

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3868]
Reported [in the forum](https://discourse.mozilla-community.org/t/amo-summary-not-working/). It looks like under certain circumstances the summary field isn't shown and therefore the submission process can't finish. According to the reporter, the problem could be related to international characters being present in the default summary text. I'm requesting the file to see if there's anything different about it.

**Comment by jvillalobos** [comment]
Ah, we have the file already, which can be obtained from the [review page](https://addons.mozilla.org/editors/review/password-crypt). I see some warnings about permissions fields and CSP, but the `description` field and rest of the manifest look very normal...

**Comment by jvillalobos** [comment]
I also noticed the URL is set to `custom-license`, so there may be other bugs related to trying to finish a submission.

**Comment by beastybeast** [comment]
Like to point out that both the name and summary input field is empty to start with. After a submit the name field is shown and can be entered. But this is not the case with the summary textarea.

**Comment by ValentinaPC** [comment]
@jvillalobos :
Maybe my suggestion will help in figuring this out.
I am almost convinced that is has everything to do with `locales`.
There are several issues logged for this case: no field name (or summary) while submission i.e. https://github.com/mozilla/addons-linter/issues/701

I've observed that the only folder from `_locales` is `en`, and the `default_locale` from the manifest is also `en` - submission for English work as expected.
Setting any other locale beside `en` is returning the initial issue.

**Comment by eviljeff** [comment]
(I sent this by email last night but it seems to have been eaten)
I'll put money on this being a localisation related issue when the manifest is parsed (the fields would be missing if the value doesn't exist in the database).

(The slug being Custom License is a weird but related bug - the slug gets a default based on the value of the 'name' field... which is normally the add-on name field.  Because that's missing it's finding the next field called 'name', which so happens to be the license name.)

**Comment by eviljeff** [comment]
We should certainly fix this but its not submission flow related, per se.

**Comment by eviljeff** [comment]
I'll put money on this being a localisation related issue when the 
manifest is parsed (the fields would be missing if the value doesn't 
exist in the database).

(The slug being Custom License is a weird but related bug - the slug 
gets a default based on the value of the 'name' field... which is 
normally the add-on name field.  Because that's missing it's finding the 
next field called 'name', which so happens to be the license name.)

**Comment by beastybeast** [comment]
While we are waiting for this bug to be fixed - anybody that have a way that will allow me to publish my webextension?

**Comment by ValentinaPC** [comment]
Delete `default_locale` from your manifest and the folder `_locales` from the archive.
Don't know if this is the BEST solution, but it works.
As a second solution would be - you can add a `da` folder in the `_locales` one with a valid messages.json file.
While being just the QA person, hope I helped.

**Comment by eviljeff** [comment]
The localization in `_locales` seems to be unused anyway - it's just a template with placeholder text you've not changed.

**Comment by jvillalobos** [comment]
We would need to delete the add-on for the developer, since they don't have access to the dev tools. @beastybeast, if you're okay with making that change and resubmitting, I'll delete the partial submission for you.

**Comment by beastybeast** [comment]
Fine with me.

**Comment by jvillalobos** [comment]
Okay, it should be deleted now. Please try submitting again with the change to the manifest.

**Comment by beastybeast** [comment]
Just for your information it tells me on submit that (translated):

Addon with this Slug already exist.

And I had to rename it to pcrypt from password-crypt

NB: Some text is a mixture of Danish and English - does not look nice

**Comment by beastybeast** [comment]
When I look at the listing it tells me that standard language is Danish - also for support etc.

Where have I specified that?
Where can I change that?

It is not correct as it have been developed for both English and Danish from the beginning!

**Comment by beastybeast** [comment]
When I try to change the standard language I get this message:

> Before changing your default locale you must have a name, summary, and description in that locale. You are missing 'description', 'name', 'summary'.

**Comment by jvillalobos** [comment]
Please send a message to amo-admins AT mozilla DOT org and we'll continue the discussion there. This conversation should be reserved for solving the summary issue.

**Comment by beastybeast** [comment]
Sorry - just believed it was related to this bug!
