### ISSUE TITLE
"Edit review" link from "Write a reply" page does not work as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3869]
Steps to reproduce:
1. Write a review to an add-on i.e. https://addons.allizom.org/en-US/firefox/addon/clean-links/reviews/
2. Click the "Reply to review" link under your comment
3. Click "Edit review" from the page you are in after step 2

Expected results:
The reply action is cancelled. User is redirected to edit its review.

Actual results:
The first comment is removed from the page, and the "Write a reply" form remains.

Notes/Issues:
Reproducing for themes and add-ons.
Verified on FF49(Win 7). Issue is reproducing on -stage and -dev.
Video for this issue: 
![writeareply](https://cloud.githubusercontent.com/assets/15685960/19728562/90d3522e-9b9c-11e6-855b-a8142f623f58.gif)

**Comment by EnTeQuAk** [comment]
Closing because that's an edge-case that is only valid for the case that you are replying to your own review and it's going to be reimplemented in addons-frontend anyway.
