### ISSUE TITLE
Text can be entered in search box by typing letters even if it was not selected

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3871]
Steps to reproduce:
1.Open MP Stage 
2.Just press some random letters on your keyboard

Expected results:
Nothing happens

Actual results:
After few pressings the text starts to be written in search box

Please see video of the issue(observe that search box was not selected): 

![srchbox](https://cloud.githubusercontent.com/assets/1583842/19732686/416dde58-9baa-11e6-87c0-679d8c292d1b.gif)

**Comment by muffinresearch** [comment]
I think this is a feature not a bug. I think the search box is focused by default.

**Comment by vcarciu** [comment]
@muffinresearch : The text is not entered from the first letter pressed . Search box starts to be filled after pressing 4-5 times on any letters.

**Comment by muffinresearch** [comment]
@vcarciu ah ok sorry my bad - I misunderstood the original report.

Further investigation shows whilst this behaves like the search box is being autofocused there isn't any actual autofocusing going on. Seems that keypresses for the search are activating "ind as you type" even when the search is not focused, which is definitely a bug.

**Comment by muffinresearch** [comment]
@vcarciu ok I've found why this happens:  https://github.com/mozilla/addons-server/blob/0c2b633c592a882a51698949f2262773d1462b5b/static/js/impala/suggestions.js#L223

Looks like if "s" is pressed the form is focused - this was presumably a "feature".  

If you don't press "s" at all you should find the search is not filled.

**Comment by muffinresearch** [comment]
I don't think this is a bug and it's behaving as intended. Needless to say I don't think this is a feature that we'll keep for the new frontend.
