### ISSUE TITLE
Broken link to a user review for my add-on "English Dictionary Lookup"

### ISSUE THREAD

**Issue by bitskeptic** [mozilla/addons-server#3872]
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)
"Add-on Developer Menu" Tools --> Manage My Submissions --> English Dictionary Lookup --> View Recent Changes -->  Review for English Dictionary Lookup written (5 days, 14 hours ago by sai) (Links to [https://addons.mozilla.org/en-US/firefox/addon/english-dictionary-lookup/reviews/824509/], which is broken)
### What happened?

Followed the above broken link and was greeted by a "We're sorry, but we can't find what you're looking for." page
### What did you expect to happen?

To be linked to the review
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
Looks like the review that was linked in the activity log was subsequently deleted so it didn't exist any more.
