### ISSUE TITLE
Improve the admin tool for sending emails to developers

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3873]
We have a tool for sending emails to developers but it is limited to only being able to send to subsets of developers that are hard-wired in advance.

Occasionally we need to send one-off emails to a subset of developers. To be able to do that the admin tool needs to be modified to allow admins to input the list of user ids we want to send to.

**Comment by diox** [comment]
This functionality was removed in #10521 (42b52cd11175883f9868c7b50baf74b3da20ae69) in favor of using Salesforce.
