### ISSUE TITLE
Disabling and enabling add-on awaiting review leads to inconsistent status

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3876]
If a new add-on is submitted (it's `Awaiting Review`) and it is disabled by the developer in the devhub, the latest version is disabled, but the add-on status isn't changed. If the add-on is enabled again, the add-on status is still `Awaiting Review`, but all versions are disabled.

There are a couple of ways to solve this:

1) Don't show the disable option if the add-on status is `Awaiting Review`. Since the listing isn't publicly visible at that point (other than people who have the URL) and the add-on can't be reviewed, this feature being available doesn't make much sense.
2) When the add-on is disabled by the developer, set the right add-on status. In this case it should be `Incomplete`.

I prefer option 2, but either one is fine.

**Comment by ValentinaPC** [comment]
Issues related to "disable-enable" actions:
#3256 
#3051 
#3573 
Let's see how it ends :smile_cat:

**Comment by MJPWork** [comment]
Please consider the use case where Developer submitting the new version wishes for the review approval to not immediately make that version "live" + available for upgrades - perhaps for coordinating a user announcement. 

Would like this feature to permit submitter to indicate after review the submission should be disabled (and available for enabling in the future)

**Comment by eviljeff** [comment]
is this still valid?

**Comment by eviljeff** [comment]
this was duped #4024 really so I fixed it with that.
