### ISSUE TITLE
No "Transfer ownership" e-mail in Edit Listing theme page causes all fields to be empty

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3877]
Steps to reproduce:
1. Submit a Theme in -stage and approve it
2. Go to "Edit Listing" theme page
3. Click "Transfer ownership" button and delete the e-mail
4. Save changes

Expected results:
A message saying that the field is mandatory is displayed.

Actual results:
All fields are emptied.

Notes/Issues:
Theme license is also requested even if is already checked.
If a valid e-mail is entered back in the transfer ownership field, things go back to normal.
Verified on FF49(Win 7). Issue is reproducing all around AMO servers.
Video fro this issue: 
![savenomail](https://cloud.githubusercontent.com/assets/15685960/19760332/f4c751c0-9c39-11e6-816b-fa21a9d12833.gif)

**Comment by EnTeQuAk** [comment]
It's not currently important or blocking, also it doesn't destroy any actual data so it'd be nice to fix.

**Comment by diox** [comment]
Wontfixing this because lightweight themes are about to be replaced with static themes, which behave more like regular add-ons.
