### ISSUE TITLE
Inconsistent page title at submission distribution

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3878]
Steps to reproduce:
1. Log in to AMO-stage https://addons.allizom.org/en-US/
2. Click the "Submit a New Add-on" link from Tools (https://addons.allizom.org/en-US/developers/addon/submit/distribution)
3. Observe page title in tab or page subtitle

Expected results:
A clear title/subtitle is displayed.

Actual results:
The title/subtitle is "How to Distribute this Version" even if we are talking about the entire add-on; while adding a new version, user cannot select where to distribute it, because is distributed where the add-on is.

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue: 
![version](https://cloud.githubusercontent.com/assets/15685960/19760970/a0d0c31e-9c3c-11e6-882c-56426c49dc28.png)

**Comment by jvillalobos** [comment]
That's intentional. This work is part of #3465, which will make it possible to choose a different distribution channel for each version. Naming it `How to Distribute this Add-on` could suggest that all versions will use the same channel, which is true now, but not when the rest of the changes land.
