### ISSUE TITLE
Double "require review" note in Editor Tools add-on review page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3879]
Steps to reproduce:
1. Go to Editor Tools https://addons.allizom.org/en-US/editors/
2. Click on any awaiting review add-on that has a `require restart` flag i.e. https://addons.allizom.org/en-US/editors/review/%E6%9C%AC%E6%97%A5%E6%9C%AC-

Expected results:
The flag is also listed in the review page.

Actual results:
The flag and a button, both "require restart", are displayed.

Notes/Issues:
I think we can easily remove the button.
Verified on FF49(Win 7). Issue is reproducing on AMO-stage and dev,
Screenshot: 
![reqrestart](https://cloud.githubusercontent.com/assets/15685960/19761960/a341b186-9c40-11e6-995c-088971e74f2b.png)

**Comment by eviljeff** [comment]
double label is double-plus-good 😆
