### ISSUE TITLE
Report on ACR and e10s

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3886]
Since we launched the new ACR we've been collecting data in AMO about add-ons and their success on e10s. That data has been going to the add-on authors, which is cool. But we haven't got any data about ACR. I'd be curious to know, since we put the time and effort into this:
- how many reports we've had come in
- how add-ons are working with e10s enabled and e10s compatible etc

We could do this by a) creating an API to get this data or b) a script against the MySQL db.

/cc @shell15

**Comment by wagnerand** [comment]
Note: This is blocked by #3947.

**Comment by muffinresearch** [comment]
I think we can close this out now.
