### ISSUE TITLE
Data missing in API

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#3901]
### Describe the problem and steps to reproduce it:
Downloaded https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/noscript

### What happened?
Lots of data missing.

### What did you expect to happen?
I expected to see this data but it was excluded

* "Support E-mail"
* "Related Categories"
* "Tags"
* "Version Information"
* "Development Channel"

### Anything else we should know?
For example, they are all listed in https://addons.mozilla.org/en-US/firefox/addon/noscript/ but not in https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/noscript

**Comment by mstriemer** [comment]
That's our old API that I believe was just to drive some views in Firefox so the dataset was quite small.

You can try our new API at https://addons.mozilla.org/api/v3/addons/addon/noscript/, I think it has everything you mentioned. You can find documentation on the [addons-server Read the Docs](http://addons-server.readthedocs.io/en/latest/topics/api/index.html) and if you think it's missing something please file a new issue.

**Comment by davidhedlund** [comment]
@mstriemer I found it on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Add-ons_manager_API

See also Google search +"services.addons.mozilla.org/api/1.5": https://encrypted.google.com/search?hl=en&q=firefox%20api#hl=en&q=%2B%22services.addons.mozilla.org%2Fapi%2F1.5%22

**Comment by davidhedlund** [comment]
@mstriemer Yes I found it in the newer API. Thanks.
