### ISSUE TITLE
API page do not state slug

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#3902]
### Describe the problem and steps to reproduce it:
The API page do not state that **slug** (see "slug" in https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/adblock-plus for example which is "adblock-plus") can be used:

### What happened?
> Available Methods
> addon
> 
> Returns details of a particular add-on.
> Prototype
> 
> https://services.addons.mozilla.org/api/[version]/addon/[id]
> Parameters
> 
> id
>     The id of the desired add-on, as per AMO.
> 
> Example
> 
> Requesting https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/1865 returns the information for addon 1865, Adblock Plus.

### What did you expect to happen?
Please add it like something like this:

> Available Methods
> addon
> 
> Returns details of a particular add-on.
> Prototype
> 
> https://services.addons.mozilla.org/api/[version]/addon/[id]
> or
> https://services.addons.mozilla.org/api/[version]/addon/[slug]
> 
> Parameters
> 
> id
>     The id of the desired add-on, as per AMO.
> 
> Example
> 
> Requesting https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/1865 or https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/adblock-plus both returns the information for addon 1865, Adblock Plus.

# More
This is useful when you have a large collection of URLs to AMO pages that you want to download XML data from.

**Comment by mstriemer** [comment]
Please try the new API which is documented at http://addons-server.readthedocs.io/en/latest/topics/api/index.html.

Where did you find this documentation? Looks like we should probably take that down.

**Comment by davidhedlund** [comment]
@mstriemer I found it on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Add-ons_manager_API

See also Google search +"services.addons.mozilla.org/api/1.5": https://encrypted.google.com/search?hl=en&q=firefox%20api#hl=en&q=%2B%22services.addons.mozilla.org%2Fapi%2F1.5%22
