### ISSUE TITLE
Add-ons with only unlisted versions should have a status of ... ?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3909]
Part of #3465

Currently you have the following scenarios:
- Listed add-ons are
  - `STATUS_NULL` with no versions or incomplete meta-data
  - `STATUS_NOMINATED` with 1 version `STATUS_AWAITING_REVIEW` and no versions `STATUS_PUBLIC`
  - `STATUS_PUBLIC` with >1 versions `STATUS_PUBLIC`
- Unlisted add-ons are
  - `STATUS_NULL` with no versions
  - `STATUS_PUBLIC` with >1 versions

Soon we will have add-ons like:
- An add-on with no versions:
  - `STATUS_NULL`
- An add-ons with only listed versions:
  - `STATUS_NULL` with incomplete meta-data
  - `STATUS_NOMINATED` with 1 version `STATUS_AWAITING_REVIEW` and no versions `STATUS_PUBLIC`
  - `STATUS_PUBLIC` with >1 versions `STATUS_PUBLIC`
- _An add-on with a mix of unlisted/listed versions_
  - `STATUS_NULL` with >1 listed versions and >1 unlisted versions and incomplete meta-data
  - `STATUS_NOMINATED` with 1 listed version `STATUS_AWAITING_REVIEW` and no listed versions `STATUS_PUBLIC` and >1 unlisted versions.
- _An add-on with only unlisted versions_:
  - `STATUS_NULL` with >1 versions `STATUS_PUBLIC`

**Comment by eviljeff** [comment]
What should the `STATUS_???` be?  (edit comment0 when we're decided)

I guess for
>  `STATUS_???` with 1 listed version `STATUS_AWAITING_REVIEW` and no listed versions `STATUS_PUBLIC` and >1 unlisted versions.

it should be `STATUS_NOMINATED`.  But for the other two?  `STATUS_NULL` ?  Seems wrong.

**Comment by jvillalobos** [comment]
It seem like the global status doesn't matter for unlisted add-ons, except when it's `Disabled by Mozilla`. With that in mind, your proposal sounds good.

**Comment by diox** [comment]
`STATUS_NULL` could work, it has a special meaning in a couple places, we'd need to check that it's ok. I know deletion code uses that to check whether the add-on should be soft or hard delete, but it does check whether the add-on has versions or not too so it should be ok, I think.

**Comment by eviljeff** [comment]
Updated comment 0 to effectively ignore unlisted versions where working out the status.  Will likely cause some edge cases.
