### ISSUE TITLE
Notify reviewers when "notes to reviewers" is updated

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3913]
Reviewers often ask for additional information which developers provide using the _Notes to Reviewers_ field.
However, reviewers have no way of knowing when that field was updated.

If the _info-request_ flag is set and the _Notes to Reviewers_ field is updated, we should clear the flag and send an email to the reviewer. Also, an event like `Notes to Reviewers have been updated` should be added to the review activity.

If the _info-request_ flag is *not* set, we don't need to sent emails, I think. Adding the event wouldn't hurt though.

Adding @kewisch as this might be relevant to him.

**Comment by kewisch** [comment]
Yes, I would love to see this. As long as something shows up in the activity for a version that mentions the reviewer notes have been changed, for my use case I am happy. The fix should entail everything Andreas mentioned though.

**Comment by wagnerand** [comment]
Turns out, we are already dropping the _info-request_ flag :)

**Comment by ValentinaPC** [comment]
Verify in AMO-dev FF49.0.2(Win 7)

- I've added some text (and an update) in the "notes to reviewers" field, and the notes were passed to add-on review page from Editor Tools, which I suppose, is ok, yes?
- I've checked in Fake mails page from Admin Tools for a mail regarding the note, but didn't find any.
- I've also set the "info-request flag" and updated the 'Notes to Reviewers" field and the flag was cleared.

Anything else to be checked here? Please add some STR if so. Thanks!

**Comment by wagnerand** [comment]
If the 'activities email' feature is deactivated, there should only be logging entries when 'source code uploaded' or 'approval notes changed' on the review page.

If the 'activities email' feature is activated, it behaves the same as above if the 'info-request' flag had **not** been set at the time of the event.
If the 'info-request' flag had been set, emails should be send out in addition.

**Comment by ValentinaPC** [comment]
"Activity mail" feature is enabled.

1. _adding text in the "Notes to Reviewers" field_ at submission -> the notes are passed to add-on review page from Editor Tools 
2. _adding a source code_ -> a "Super review requested" note is added in add-on review page form Editor Tools and the "info request flag" is set
3. _updating the "Notes to Reviewers"_ after doing step 2 -> **the flag was not dropped**
4. _removing the source code_ - the same message as when I was adding the source code, is generated - **might be an issue?** ; the "info request flag" remains and is not removed while updating the "Notes to Reviewers" field
5. _updating the "Notes to Reviewers" field after manually adding the "info request flag"_ (from add-on review page) - the flag is removed
6. _adding a source code_ after doing step 5 - generates **two** "Super review requested" notes (the presence of two identical notes **might be also an issue**?)

Tried to be as clear as I could. 
Other mails than the ones related to the manual more info request (More information requested from Editor Tools) are not sent.

Please let me know if there is anything true from my suppositions :smile: or if there is anything else I should test. Thanks!

**Comment by wagnerand** [comment]
Thanks for testing, some feedback:

> adding a source code -> a "Super review requested" note is added in add-on review page form Editor Tools and the "info request flag" is set

Which form did you add source code on? Adding source code should add a "Source code uploaded" note. The info-request flag should not be set by this event. Do you mean it had been set before?

>  updating the "Notes to Reviewers" after doing step 2 -> the flag was not dropped 

Hm, I just tested this and it works fine.

>  removing the source code - the same message as when I was adding the source code, is generated - might be an issue? ; the "info request flag" remains and is not removed while updating the "Notes to Reviewers" field
Yeah adding the same message is the current behavior. Afaics, this has been the previous behavior as well. But I agree we should fix that at some point.
Also, I cannot reproduce that the "info-requested" flag was not removed. It works just fine for me.

>  Other mails than the ones related to the manual more info request (More information requested from Editor Tools) are not sent.
Did you use the same account for uploading and reviewing the add-on? The code filters recipients and does not send any emails if you are in both groups.

**Comment by ValentinaPC** [comment]
> Which form did you add source code on? Adding source code should add a "Source code uploaded" note. The info-request flag should not be set by this event. Do you mean it had been set before?
I've added the source code from Dev Hub - Manage Version page - something changed from yesterday, but the flag is still set and is not dropped if the source code is removed, please take a look:
![addsoucecode](https://cloud.githubusercontent.com/assets/15685960/20342049/83fe2c58-abf1-11e6-9cf6-cc96d0ae5bdf.gif)

Adding/updating the "Notes to Reviewers" after I've added the source code from Dev Hub as in the above video - the flag is not dropped, please take a look:
![flagnotdropped](https://cloud.githubusercontent.com/assets/15685960/20342387/dd6cb538-abf2-11e6-847b-526217f03598.gif)

> Did you use the same account for uploading and reviewing the add-on? The code filters recipients and does not send any emails if you are in both groups.
Yup, same account. Should I use an account while submitting and another for review? 

I think points 5 and 6 behave now as expected:
![devhub](https://cloud.githubusercontent.com/assets/15685960/20342655/0001f0c6-abf4-11e6-9ad5-8013c43196bf.png)
![reviewpage](https://cloud.githubusercontent.com/assets/15685960/20342697/217613a4-abf4-11e6-8066-33e08b1cd524.png)

**Comment by wagnerand** [comment]
The first screencast looks fine to me: A version is not admin-flagged initially. You then submit source code and it's admin-flagged afterwards.

The second screencast is also fine: Changing the "Notes to Reviewer" should not drop the admin-flag. It should drop the info-requested flag if it had been set before.

> Yup, same account. Should I use an account while submitting and another for review? 

In theory this should make emails work. I don't think real emails are enabled on -dev though.

**Comment by ValentinaPC** [comment]
Well, if things seem ok to you, we can mark this verified-fixed based on above comments.
