### ISSUE TITLE
"Prev"/"Next" arrows in Disco Pane menu

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3917]
Steps to reproduce:
1. Open your Firefox browser
2. Access about:addons
3. Click to play the video
4. Make the video "full screen"
5. Navigate between tabs
6. Close "full screen"

Expected results:
"Prev"/"Next" arrows are no longer displayed.

Actual results:
The arrows are still displayed.

Notes/Issues:
The arrows disappear after page refresh.
Reproducing on -prod using FF49.0.2(Win 7)
Screenshot for this issue: 
![2016-11-02_1637](https://cloud.githubusercontent.com/assets/15685960/19933048/d3b93e18-a11a-11e6-9d1d-5c131da1b3cb.png)

**Comment by mstriemer** [comment]
This is weird. The buttons seem to handle the browser history forwards/back. I think this is a Firefox bug though.

**Comment by muffinresearch** [comment]
>  I think this is a Firefox bug though.

Yep, looks like it since those arrows are not part of the web content. 

@ValentinaPC could you re-file this as a Firefox bug on bugzilla please and then close this one?

**Comment by ValentinaPC** [comment]
Logged https://bugzilla.mozilla.org/show_bug.cgi?id=1314917
Closing this.
