### ISSUE TITLE
Expand Summary help text in submission flow to encourage longer summaries

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#3919]
The recent changes to the submission flow have yielded many add-ons lacking in descriptive text, which reviewers have a hard time figuring out. The Summary field in the submission flow is pre-populated with data from the manifest, which is insufficient in many cases. Let's encourage developers to add more info to it.

Current text:

> This summary will be shown in listings and searches.

Proposed text:

> This summary should clearly explain what your add-on does. It will be shown in listings and searches, and it will be used by reviewers to test your add-on.

**Comment by vishal-chitnis** [comment]
Hi, I have found the template used for this page. I would like to work on this.

**Comment by ValentinaPC** [comment]
Verified this as fixed on AMO-dev FF55(win 7).
Postfix screenshot:
![summ](https://user-images.githubusercontent.com/15685960/29654457-fda4a95a-88b5-11e7-83ad-8ac7578adcb4.png)

@EnTeQuAk : Should we add the same text in Basic Information also?
Please see screenshot:
![dev-hub](https://user-images.githubusercontent.com/15685960/29654529-42104f2c-88b6-11e7-88e2-dbb0ee90d439.png)

**Comment by ValentinaPC** [comment]
Verified as fixed in Edit Information using FF55(Win 7) in AMO-dev.
Postfix screenshot:
![summ](https://user-images.githubusercontent.com/15685960/29773456-463b5f6c-8c06-11e7-9047-dee7e31a460a.png)
