### ISSUE TITLE
outgoing.prod.mozaws.net eats "&"

### ISSUE THREAD

**Issue by JustOff** [mozilla/addons-server#3929]
Redirector, used on AMO, eats "&" in urls, making the links broken.

For example, at [here](https://addons.mozilla.org/addon/cookies-exterminator/), near the end of description, link to forums.mozillazine.org.

**Comment by muffinresearch** [comment]
Duplicate of https://github.com/mozilla/addons/issues/146 

A patch has landed we're just waiting for it to be deployed.
