### ISSUE TITLE
API response type is text/html, should be JSON

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#3930]
The API response type is `text/html` instead of `application/json`, which means browsers won't show a pretty JSON view when requesting the API (as I sometimes do when testing).

We should change the response to `application/json`.

Screenshot of ⌘+I on Firefox hitting the API:

<img width="656" alt="screenshot 2016-11-03 21 33 21" src="https://cloud.githubusercontent.com/assets/90871/19986091/3dfd8520-a20d-11e6-9eea-9d9a5e707042.png">

**Comment by diox** [comment]
Pretty sure that's a bug from Firefox. I see it as `application/json` when using curl.

**Comment by tofumatt** [comment]
That's weird; in multiple Firefoxes and Chrome I see this as the header output:

```
Content-Security-Policy: script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.paypalobjects.com/js/external/dg.js https://addons.cdn.mozilla.net https://addons-dev-cdn.allizom.org; img-src 'self' data: blob: https://www.paypal.com https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net https://addons-dev-cdn.allizom.org; object-src 'none'; default-src 'self'; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com https://www.sandbox.paypal.com; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net https://addons-dev-cdn.allizom.org; media-src https://videos.cdn.mozilla.net; child-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com https://www.sandbox.paypal.com; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net https://addons-dev-cdn.allizom.org; form-action 'self' https://developer.mozilla.org; base-uri 'self' https://addons.mozilla.org https://addons-dev.allizom.org; report-uri /__cspreport__
Date: Thu, 03 Nov 2016 21:47:34 GMT
Public-Key-Pins: max-age=5184000; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="
Server: nginx
strict-transport-security: max-age=31536000
Vary: X-Mobile, User-Agent
x-content-type-options: nosniff
X-Frame-Options: DENY
x-xss-protection: 1; mode=block
Connection: keep-alive
```

No content type in sight.

**Comment by tofumatt** [comment]
I just hit some URLs again and shift-refreshed them and it was fine. 😖

**Comment by diox** [comment]
I  see `Content-Type: application/json;q=0.8` in Chrome - we certainly don't set it like that, the developer tools seem to be rewriting headers before displaying them. 

Only way I could reproduce the missing `Content-Type` header is when I was served a 304 because of the browser cache, but that shouldn't be an issue.

**Comment by diox** [comment]
Note: I don't know about Chrome, but in Firefox, devtools json view is broken by... our CSP. See https://bugzilla.mozilla.org/show_bug.cgi?id=1303086

**Comment by tofumatt** [comment]
Hah! Okay, maybe it's that. Merci.

- tofumatt

**Comment by muffinresearch** [comment]
FWIW: You can work around this by setting `devtools.jsonview.enabled` to false in `about:config`
