### ISSUE TITLE
Disco Pane content update - Nov. 2016

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#3931]
For the Thursday, **17 November** push, can we please REMOVE: 

- Emoji Cheatsheet
- All three themes (glitter closeup, metal flowers, Live With Music)

… and replace them with OmniSidebar and three new themes, respectively (note full copy included):

**Easily access bookmarks**
with [OmniSidebar by Quicksaver](https://addons.mozilla.org/firefox/addon/omnisidebar/)
Are you constantly scrolling through your bookmarks? Bring your lists into view with a single, simple gesture. 

[themes]

Aurora Australis by [silfiriel](https://addons.mozilla.org/firefox/addon/aurora-australis/)

snow style by [elakeduck](https://addons.mozilla.org/firefox/addon/snow-style/)

My Vinyl by [baliclem](https://addons.mozilla.org/firefox/addon/my-vinyl/)

**Comment by devaneymoz** [comment]
I just learned we have the ability to customize how we present the titles of themes on the Disco Pane. So with that in mind, please display the second theme in title case:

Snow Style by [elakeduck](https://addons.mozilla.org/firefox/addon/snow-style/)

**Comment by vcarciu** [comment]
Verified as fixed : 
![newdisco](https://cloud.githubusercontent.com/assets/1583842/20396907/6dbf8720-acf0-11e6-9b2a-a53c8a38b9b1.gif)
