### ISSUE TITLE
Custom titling for themes in Disco Pane

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#3933]
Problem: 
Currently we cannot change or customize how theme titles appear on the Disco Pane. This is problematic since theme creators are wildly varied in their titling styles (e.g. use of capitalization, sometimes including author names in titles, applying underscores between words, using abstract numbers, etc.) not to mention occasional misspellings. The result can be a very messy presentation, especially so given the juxtaposition with the rest of the headers and copy on the page, which is presented in a uniform style. 

Proposed fix:
Have the ability to customize theme titles. If we could do this, we could edit odd titling issues and present a cleaner looking page that's more appropriate given the weight of the Disco Pane.

**Comment by diox** [comment]
The API code already allows for this - if we specify a title, it takes precedence over the default `{name} by {authors}` title. So if you provide us with custom titles we can add them.

**Comment by ValentinaPC** [comment]
Is there a way for us to verify this? Thanks!

**Comment by muffinresearch** [comment]
It should be possible to verify this when https://github.com/mozilla/addons-server/issues/3931 is landed for next week's push.

**Comment by ValentinaPC** [comment]
I saw the changes from about:addons; editing themes or add-ons names should be seen in Disco Pane, too? Thanks!

**Comment by ValentinaPC** [comment]
Verified this in 53.0a1 (2016-11-21) (Win 7 32-bit) using about:addons set for -dev.

- Name of the add-ons appear changed in first page from about:addons and add-on public details page:
![name-in-aboutaddons](https://cloud.githubusercontent.com/assets/15685960/20515905/5b09c492-b09c-11e6-92fc-ace4ab0ef814.png)
![name-in-addondetails](https://cloud.githubusercontent.com/assets/15685960/20515951/a27ad4ce-b09c-11e6-8486-58fb15f76928.png)

- Name of the add-on does not change in about:addons -> Extensions tab (if installed)
![name-in-extensionstab](https://cloud.githubusercontent.com/assets/15685960/20515942/8df0b438-b09c-11e6-9b32-18838473d914.png)

- Name of the themes cannot be changed:
![aboutaddons](https://cloud.githubusercontent.com/assets/15685960/20516008/f0c55672-b09c-11e6-9e68-45d6367d5101.png)
![themedetails](https://cloud.githubusercontent.com/assets/15685960/20516010/f3e9f4e8-b09c-11e6-9c1e-b3609f2942b3.png)

@muffinresearch : Should it be possible to change themes names also? Thanks!

**Comment by ValentinaPC** [comment]
Works as expected for themes also, only needs some time to propagate.
Screenshot: 
![2016-11-22_1101](https://cloud.githubusercontent.com/assets/15685960/20517315/303fdc4a-b0a3-11e6-8e53-ca549c33709d.png)

Closing this as verified.
