### ISSUE TITLE
Long collector's notes are not truncated

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3935]
Steps to reproduce:
1. Open one of your collections in order to Edit it 
2.In the Add-ons section add some long notes for any add-on from the list
3.Save the change

Expected results:
Long Collector's notes are truncated 

Actual results:
Long Collector's notes are not truncated

NOTES:
Reproducible in production
I will add a screencast for the issue this time because I am not able to add a gif(Github issue) : http://screencast.com/t/aY1fp9aFd

**Comment by wagnerand** [comment]
Mentor: @eviljeff.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by piyushrungta25** [comment]
I tried to reproduce but the text is wrapped. I have attached a screenshot which was running in docker container. Is this not the expected behaviour?
![addon_ser](https://cloud.githubusercontent.com/assets/11994135/21547264/f432c8c2-ce0a-11e6-824c-127c1e3e0441.png)

**Comment by eviljeff** [comment]
@piyushrungta25 have you tried it with long words (without spaces) too, like in the screencast linked in the first comment.

**Comment by piyushrungta25** [comment]
@eviljeff The text was overflowing for long words as you said. I made the fix. Let me know if I missed something. Should I open a PR?

**Comment by eviljeff** [comment]
@piyushrungta25 yes, please open a pr and reference #3935 in the pull request summary.

**Comment by vcarciu** [comment]
Verified as fixed :  
![longtextnotes](https://cloud.githubusercontent.com/assets/1583842/25668136/6f6daf04-302e-11e7-8959-6021dd2f30e5.png)
