### ISSUE TITLE
API: No license data

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#3936]
### Describe the problem and steps to reproduce it:
Compared the new API with the old one:
* https://addons.mozilla.org/api/v3/addons/addon/noscript/
* https://services.addons.mozilla.org/en-US/firefox/api/1.5/addon/noscript

### What happened?
The new API don't show license data like the old one:
* License -> name
* License -> URL

### What did you expect to happen?
The new API should display license data.

### Anything else we should know?
They have to display so we can finish the IceCat add-on repository.

**Comment by davidhedlund** [comment]
[mylabel:license](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Alicense%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by diox** [comment]
Hi, thanks for submitting this issue. This information is provided in a different endpoint. See http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail

**Comment by davidhedlund** [comment]
@diox The URL is not valid.

**Comment by davidhedlund** [comment]
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail

**Comment by davidhedlund** [comment]
@diox Thanks.
