### ISSUE TITLE
Version notes should flow under the "add to firefox" button

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#3939]
### Describe the problem and steps to reproduce it:

Originally filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=976220

> See https://addons.mozilla.org/en-US/firefox/addon/flagfox/versions/

> The "Add to Firefox" button on each version listing takes up the full right-side space of the entry. This causes the version notes to be cramped. Please widen things a little bit so the version notes can flow underneath the space where the button is. I can't fit in the full width of my version notes as-is. :/

### What happened?

There's a large margin on the right-hand side of the version notes block. 

### What did you expect to happen?

Text should be able to fill the full width of the block.
Currently text stops at the red line, it should continue to the green line.

![wrapping-bug](https://cloud.githubusercontent.com/assets/1514/20013424/f55af2c8-a2aa-11e6-8694-f8bb5ed1fa63.png)

Thanks @wagnerand for the screenshot

**Comment by wagnerand** [comment]
Had I known the screenshot would be actually used, I would have made it prettier! 😃

**Comment by ValentinaPC** [comment]
Should this be applied in add-ons listing pages i.e. https://addons-dev.allizom.org/en-US/firefox/search/?q=&appver=49.0&platform=windows ?
Screenshot: 
![2016-11-07_0907](https://cloud.githubusercontent.com/assets/15685960/20049173/184ec518-a4ca-11e6-93ef-24bc2bb508ec.png)

**Comment by wagnerand** [comment]
I'm not sure whether it should. But it wouldn't be as easy as for the version history page as the text on the listing page would collide with the "Add to Firefox" button, which can't happen on the version history page.

**Comment by muffinresearch** [comment]
Digging into this issue a little deeper, I'm wondering how viable this bug is to fix without more invasive changes.

This screenshot shows more information:

<img width="720" alt="fullscreen_07_11_2016__13_38" src="https://cloud.githubusercontent.com/assets/1514/20059731/9406c30c-a4ef-11e6-9ed9-ffffefc3e70e.png">

The buttons are in a container and each button is `visibility: hidden` until hovered.

To change this is *and* have the text take up more width is beyond a simple CSS change. I think this probably isn't worth pursuing since user-facing pages are going to be overhauled next year.

**Comment by muffinresearch** [comment]
I see the patch in the PR takes the approach of widening the entire block without interfering with the action div. If that doesn't cause regressions elsewhere (the selectors look very general) then that could be a good approach.

**Comment by muffinresearch** [comment]
Based on the comments in the PR going to mark this as wontfix.
