### ISSUE TITLE
Edit Collection: Indicate removed add-ons

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#3941]
### Describe the problem and steps to reproduce it:
Clicked on My collections -> any collection -> Edit. They collection must include an add-on removed by Mozilla.

### What happened?
When you Edit your Collection, all add-ons you added to it will display. This includes old add-ons that were removed by Mozilla (like [Web of trust](https://addons.mozilla.org/en-US/firefox/addon/wot-safe-browsing-tool/)). This might be good for the authors of the collections, for example they might want to copy their added comments that they added to them before they remove them from the collection.

### What did you expect to happen?
Removed add-ons should be indicated on the Edit Collection list.

### Anything else we should know?
No.

**Comment by wagnerand** [comment]
Possible dupe of #2971.

**Comment by davidhedlund** [comment]
@wagnerand Thanks.
