### ISSUE TITLE
New File update for Listed and Unlisted

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3948]
Follow on from #3469 

Although files don't have a channel the UI/functionality will be different for the new Version uploads so need to add an equivalent flow for new Files on Versions.  

Also: a) we can properly link into this new flow from new version/addon finish step b) remove all the old version upload flow code (it's used by File and Version currently)

**Comment by eviljeff** [comment]
UI is https://github.com/mozilla/addons/issues/192#issuecomment-252531408

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF50(Win 7). The flow for the new file submission is the same as before.
Tried with add-ons and webextensions and different file combinations. 
Please see the screenshots:
![add-onlisted](https://cloud.githubusercontent.com/assets/15685960/20517012/d30415ec-b0a1-11e6-9bad-166f9c7d01c0.png)
![unlisted](https://cloud.githubusercontent.com/assets/15685960/20517015/d79e0216-b0a1-11e6-9e0d-4904a074b173.png)

**Comment by eviljeff** [comment]
addons-dev hasn't updated with the commit yet

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
Postfix screenshots: 
![unlisted_001](https://cloud.githubusercontent.com/assets/15685960/20560038/ff3a0e44-b17f-11e6-85cf-bde685700bb3.png)
![listed_001](https://cloud.githubusercontent.com/assets/15685960/20560069/2a62d7cc-b180-11e6-9eb3-752f0e673d32.png)
