### ISSUE TITLE
Add an intersitial page on report a bug

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#3951]
People are clicking on the report a bug link on the bottom of AMO to report bugs in add-ons into github and its slow and tedious to point them to where they should go. They end up in addons and that's not really helpful. 

I think we need an intersitial page, which is just a simple static page that says:
* Found a bug in an add-on? Go here.
* Found a bug in Firefox? Go here.
* Found a bug in AMO, continue on.

I bet we have this in an FAQ already and its just a matter of pointing to that.

**Comment by muffinresearch** [comment]
I think this was fixed by #3952

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49.0.2(Win 7)
Postfix video: 
![fileabug](https://cloud.githubusercontent.com/assets/15685960/20137055/ff04f6f0-a680-11e6-8898-840af8fae834.gif)
