### ISSUE TITLE
Include license.name and license.url for each addon

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#3964]
@kumar303 pointed out that I'm essentially doing a TONNE of effort to fetch the current version details in https://github.com/mozilla/addons-frontend/pull/1354 because the license URL and license name aren't included, because the license isn't included in the results for performance.

I imagine this is to prevent `license.text`, which could be a wall of text, from being sent over the wire. Could we include just the name and URL in the response? It would save every add-on detail page an API request, cut hundreds of lines of code from my patch, and make for speedier navigation between search results and an add-on as we'd have all data prefetched to show the content as I understand it.

**Comment by diox** [comment]
Technically it was also done to avoid the extra `JOIN`, but well, if we need it anyway... Yeah, I'll add those.
