### ISSUE TITLE
Search for collections is returning add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3965]
Steps to reproduce:
1. Go to Collections page in AMO: https://addons.mozilla.org/en-US/firefox/collections/
2. Make a search i.e. https://addons.mozilla.org/en-US/firefox/search/?q=free&cat=collections
3. Delete the text from the search box - observe default text "search for collections"
4. Make another search

Expected results:
Search is made as the default search box text suggests: through collections. 

Actual results:
Search is made through add-ons.

Notes/Issues:
Add-ons suggestions are displayed.
If no suggestion is selected, search works as expected.
Verified on FF49.0.2(Win 7). Issue is reproducing all around AMO servers.
Video for this issue: 
![coll](https://cloud.githubusercontent.com/assets/15685960/20133956/46064e46-a672-11e6-8eea-b044b68e5450.gif)

**Comment by EnTeQuAk** [comment]
That will be reimplemented in addons-frontend sooner or later so let's close it here.
