### ISSUE TITLE
'Download latest' link is 404

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3966]
### Describe the problem and steps to reproduce it:

Try https://addons.mozilla.org/firefox/downloads/latest/donottrackplus/

### What happened?

404

### What did you expect to happen?

An XPI file.

### Anything else we should know?

I'm going to take a wild guess here and assume this is because that add-on has a version pending review.

**Comment by diox** [comment]
From IRC discussion: that addon version has multiple files for different platforms, and because no platform is specified in the link, it can't find one and 404s (we default to `PLATFORM_ALL` but that add-on does not have a file that supports all platforms)

**Comment by EnTeQuAk** [comment]
Given that this is imho expected behavior I think this can be closed. If there is an actual issue here please fee free to re-open at any time.
