### ISSUE TITLE
"Add-on" word overlaps the text from Dev Hub header in some languages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3968]
Steps to reproduce:
1.Open AMO Developer Hub in different languages(https://addons.allizom.org/it/developers/ ,  https://addons.allizom.org/fr/developers/)
2.Observe the translated "Add-ons " word(in black)

Expected results:
Text is correctly displayed

Actual results:
"Add-on" word overlaps the rest of the text

Please see video for this bug:
![overlapping](https://cloud.githubusercontent.com/assets/1583842/20145068/5ab86c36-a6a7-11e6-8239-e7757b35a177.gif)

**Comment by EnTeQuAk** [comment]
I'm working on a refactor of all that, it'll be gone once that is done.
