### ISSUE TITLE
It should not be possible to submit a new version for an admin disabled add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#3970]
### Describe the problem and steps to reproduce it:

We have two status for disabled add-ons:
* Incomplete = There are no approved versions. The author can upload a new version any time.
* Disabled by Mozilla = The listing (if applicable) is disabled. The author can not upload any versions.

This issue is solely about the latter status.

STR:
1. Upload a new add-on (listed or unlisted does not matter).
2. Go to the admin manage page for that add-on (/admin/addon/manage/<slug>/) and set the add-on status to 'Disabled by Mozilla'.
3. Upload a new version for the same add-on.

### What happened?

An author can upload new versions for an add-on that has been 'Disabled by Mozilla'.

### What did you expect to happen?

The version upload should have failed.

**Comment by eviljeff** [comment]
Is this for both listed and unlisted uploads?

**Comment by wagnerand** [comment]
Yes.

**Comment by eviljeff** [comment]
We don't currently (that I can see) prevent a developer from deleting their add-on either when it's admin disabled... so if we stop them from uploading new versions won't they just delete the listing and resubmit?

**Comment by wagnerand** [comment]
Hm, this has further implications. Adding @jvillalobos.

**Comment by wagnerand** [comment]
Moving to P1. We need this to prevent malware submissions.

**Comment by jvillalobos** [comment]
> We don't currently (that I can see) prevent a developer from deleting their add-on either when it's admin disabled...

I thought developers didn't even have access to the management pages when an add-on was admin-disabled. I know I've been asked to re-enable add-ons in order for developers to be able to delete them... Anyway, I agree that an admin-disabled add-on should be essentially frozen, and it shouldn't be possible to submit new versions, delete versions, or delete the add-on.

**Comment by eviljeff** [comment]
@wagnerand has confirmed we don't show the delete button to the developer if the add-on is STATUS_DISABLED, so we don't need to worry about that case.  False alarm.
