### ISSUE TITLE
Validation is never finished on STAGE

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3975]
Steps to reproduce:
1.Log in to AMO Stage and try to upload a new webextension

Expected results:
Validation is successfully passed 

Actual results:
Validation is never finished

NOTES:
Not reproducible on-dev 
Reproducible for both add-ons and webext

Please see video below:
![stagesubm](https://cloud.githubusercontent.com/assets/1583842/20181369/9ac65288-a766-11e6-856d-81c0d87b21b7.gif)

**Comment by muffinresearch** [comment]
I've asked ops to check the queues.

**Comment by bqbn** [comment]
Restarted devhub celery task. Please try again.

**Comment by muffinresearch** [comment]
> Restarted devhub celery task. Please try again.

It's working now. Thanks!

**Comment by vcarciu** [comment]
Verified as fixed
