### ISSUE TITLE
Unlisted add-on with "View Listing" link

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#3976]
Prerequisites: enable the `step-version-upload` and `mixed-listed-unlisted` flags

Steps to reproduce:
1. Submit a unlisted add-on in AMO-dev i.e. https://addons-dev.allizom.org/en-US/developers/addon/love-o-clock-vdev/versions
2. Add-a a listed version for that add-on and approve it
3. Check "Edit Information" page for the submitted add-on

Expected results: 
The add-on is unlisted. No "view listing" link is displayed.

Actual results:
The add-on is unlisted but a "View Listing" link is displayed.

Notes/Issues:
The link does not load any public page. Other links, "add-on listed" specific, are also displayed.
Screenshot for this issue: 
![unlisted_001](https://cloud.githubusercontent.com/assets/15685960/20182982/554ddff4-a76c-11e6-9c07-a63860759b70.png)

Relates to #3469

**Comment by eviljeff** [comment]
yep, that's how it's supposed to work 😄 
There won't be a concept of 'unlisted' and 'listed' add-ons in the future - just add-ons that have zero or more versions that can either listed or unlisted.  If an add-on has one or more listed versions then the listing details, etc, are shown.  (Links to non-devhub pages probably won't work because there's still lots of work to be done)

**Comment by ValentinaPC** [comment]
@eviljeff So, as an example:
- an add-on listed is rejected, afterwards a new unlisted version is uploaded for that add-on (automatically approved), add-on final status will be listed, the unlisted version will be approved and public - is this case how is suppose to work, also? 
Thanks!

**Comment by eviljeff** [comment]
> an add-on listed is rejected, afterwards a new unlisted version is uploaded for that add-on (automatically approved), add-on final status will be listed, the unlisted version will be approved and public - is this case how is suppose to work, also? Thanks!

Add-ons won't have a listed or unlisted status, only the versions.  When we've finished the overall approval status (incomplete, waiting review, approved, etc) of the add-on will only depend on the listed versions too.
