### ISSUE TITLE
stop referencing `is_listed` in production code

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#3977]
Part of #3465
We can't just stop setting `is_listed` in all our code at once, because there are other django apps that still expect the property to be set.  Similarly with our tests.  So a prerequisite is we stop _checking_ for `Addon.is_listed` in all non-test code.

Only 87 occurrences so should be simple 😆 
- [x] update.py (#4016)
- [x] activity (#3985)
- [x] addons (#4084)
- [x] api (#3922, #4043)
- [x] compat (#4101)
- [x] devhub (#4068)
- [x] editors (#3996)
- [x] files (#3985)
- [x] legacy_api (#3567)
- [x] search
- [x] signing (#4073)
- [x] stats
- [x] versions (#3985 and #4099)

**Comment by diox** [comment]
Some of those depend on https://github.com/mozilla/addons-server/issues/3847 to be fixed. For instance, in search, you can't stop filtering on `is_listed` yet, you need to wait for `current_version` to only return listed versions and filter on `current_version.id` existence instead.

**Comment by eviljeff** [comment]
Yeah there are some easy wins and some no-so-easy.  We can switch out for checking `Version.channel` in most cases, or `Addon.has_listed_versions()`.  I created the list so we (I) can chip away at it.

**Comment by diox** [comment]
I'm going to take care of everything api, search, and legacy api related in various issues already opened.

**Comment by eviljeff** [comment]
the only references that remain to `is_listed` now are either setting the property in the Addon/AddonManager model; or ensuring we don't allow mixed versions while the waffle flag is disabled.

steps remaining:
- [ ] remove inline upload flow, after flipping the `step-upload`waffle switch
- [ ] flip and remove waffle `mixed-listed-unlisted`
- [ ] remove `with_unlisted` AddonManager
- [ ] remove `is_listed` property

There are still a lot of tests that do `.update(is_listed=False)` that we can replace with `self.make_unlisted` too.

**Comment by eviljeff** [comment]
All done.  The column in the database will be removed in #3473
