### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by JamesSylvia** [mozilla/addons-server#3979]
### Describe the problem and steps to reproduce it:
Any AMO page resolves to frequent Internal Server Error as the time being. Reloading helps but next reload causes 503 error once again.

**Comment by muffinresearch** [comment]
@JamesSylvia thanks the report. We are in the process of fixing a problem that ocurred during our weekly push. It should be resolved shortly.

**Comment by andymckay** [comment]
This was fixed.

**Comment by vcarciu** [comment]
Verified as fixed on prod
