### ISSUE TITLE
Extract permissions from WebExtension

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3981]
We want to display what permissions a WebExtension will use to the user before they install it. To do this we need an easy way of retrieving what permissions a WebExtension is asking for.

The permissions are stored in the manifest.json so we should copy the permissions into the database and/or elasticsearch.

**Comment by mstriemer** [comment]
A possible solution might be to be the entire manifest.json somewhere easily retrievable. I'm not sure how big these files can get so it could turn out to be too much data but it could ease retrieving any other data we might need.

**Comment by diox** [comment]
We'd need to store this on the `Version` or `File` model in order not to repeat the mistakes of https://github.com/mozilla/addons-server/issues/3947

**Comment by mstriemer** [comment]
Ran some status on a zip full of manifests Andy gave me (sizes in bytes):

thing | value
--------|--------
file_count | 10335
total_size | 11370825
mean | 1100.22496372
median | 830
maximum | 52228
5th biggest | 29795
10th biggest | 22853
25th biggest | 13947
99% biggest | 5483
minimum | 222

**Comment by eviljeff** [comment]
I've been noodling on how to define the known permissions so we can highlight known permissions and show a description to the user.  
We either define them as constants in the code, and need to manually update them, or define them dynamically (database?).  Constants would give us the ability to localise easily.  Storing them in the database means we could update them from the schemas in Firefox automagically (at least, give us the possibility)

**Comment by mstriemer** [comment]
I'm hoping to get the schema exported in an npm module so that we can import that wherever we need it. I'm not sure how that will work with localisation, we may need to copy some stuff but hopefully there's a convenient solution.

I guess translations could be in the database and options for translating could be pulled from the npm module.

**Comment by diox** [comment]
We don't really have a good solution for translators to work on strings stored in database at the moment - that's the main reason why the new discovery pane add-ons list and strings are stored in a simple dict in our repos.

**Comment by eviljeff** [comment]
In theory Firefox has localisations for the permission descriptions ([en-US](https://dxr.mozilla.org/mozilla-central/source/browser/locales/en-US/chrome/browser/browser.properties#84-94)) though I couldn't find the non en-US ones. If those were in the npm module too that would be ideal.
