### ISSUE TITLE
Expose WebExtension permissions in the API add-on version blob

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#3982]
We are going to start exposing WebExtension permissions on the site. We should include them in the API so that the data can be shown on the new frontend.

Since the permissions can change from version to version this should likely be exposed on the `current_version` property in add-on detail and in the full version listing.

Depends on #3981.

**Comment by eviljeff** [comment]
@mstriemer what do you think will be need on `current_version` in terms of permissions?  The current UX mocks I saw indicate a short description and a long description for each permission so it might get quite large; `current_version` uses the `SimpleVersionSerializer` and typically doesn't send large chunks of text unnecessarily. 
Could just be `has permissions` to know if the link should be shown?

**Comment by eviljeff** [comment]
Oh, also, on the model permissions are on `File`, because they could vary from platform to platform (theoretically).  So a multiple `File` version could get the same text three times per version.  A `has_permissions` field likely make more sense on the `File`s too, rather than the `Version` serialization directly.

**Comment by mstriemer** [comment]
Just the name of the permission is probably good for now. Whatever is stored in the manifest and then the frontend can pull the strings from the npm module that extracts the data from mozilla-central.

I guess having it on a file makes sense. I would imagine a webextension should only have one file since you can't bundle executables with it? I guess you might want a Windows version that talks to a Windows executable installed in some other method though... Putting it on file should work either way.

Do you think the list of permissions would be too big to send? I think it would be nice to be able to populate that in the frontend without an additional query.

**Comment by eviljeff** [comment]
mozilla-central will only have, at best, the short description (and perhaps then only in en-US until the permission has hit a latter train). But you could include the long descriptions manually in the npm module I guess (if you can get them localised).  

List of permissions might be large... depends on how much a developer puts in there.  Filtering out any match urls should reduce the list to a manageable size though.

**Comment by mstriemer** [comment]
Hmm, yeah the schema files don't have any description at all. I think the permissions stuff is landing now so it may have en-US and hopefully translations make it in soon.

I checked the size of manifest files before and I think there were a few outliers from the Chrome web store that were quite large but the rest were all pretty small. And that's the entire manifest not just permissions (I assume permissions are the only section that would contribute to large file sizes though).

Are you suggesting we add a second API that just returns the permissions and query that if the add-on needs permissions? This seems like over kill to me if that's the case.

**Comment by eviljeff** [comment]
Nah, it wouldn't be a separate API, just on the File response off Version.

**Comment by mstriemer** [comment]
Having it on file should be fine. We might want to start passing the platform if we aren't already and use that to filter the files (and limit the permissions spam) in the future, but that should be done separately.
