### ISSUE TITLE
Retrieve reviews by user for a specific add-on version

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#3986]
On the detail page of an add-on, we allow the user to select a 1-5 star rating for the add-on / version. If they have already rated the add-on, we need to pre-populate the stars to indicate their saved rating.

Currently, we can do this by [retrieving all user reviews](http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#list-reviews-by-a-user) then filtering them in JavaScript to see if one exists for the current add-on / version.

However, this will become slow for prolific review writers. Can we get an additional filter params? We would like to do the following:

* retrieve a saved review by user, add-on ID, and version ID (there will only be one)
* retrieve all reviews (for all versions) by user for an add-on. This will let us get at the most recent review.

**Comment by tofumatt** [comment]
Possible premature optimisation, but being able to get all reviews *for the current user* and store them in the `state` would be nice too; saving requests for each add-on if the user writes a lot of reviews (I'd love to see data on it but I imagine we have people who write either zero or many reviews, with few in-between).

**Comment by mstriemer** [comment]
Do we want the review for the current version or just the latest review (highest version)? If I review version 1.1.0 and then version 1.1.1 is released I would imagine my old review is still valid until I update it.

I think of the version as metadata that might be useful to the developer (if we actually get it right and they aren't running an old version when they leave the review) or other users if we can mention that a review is for an old version and a bug might be fixed now.

**Comment by kumar303** [comment]
The point of this issue is to make a more specific query like: give me the review for user=X, add-on=Y and version=Z. The logic of which saved review to display on the add-on detail page is out of scope.

**Comment by mstriemer** [comment]
Well this will affect what the user sees. What if there is only one review on an add-on and I left it on an old version? Do I see that I haven't reviewed the add-on but directly underneath is the only review, left by me?

**Comment by mstriemer** [comment]
To be clear I don't think we need to specify the version, we just want the latest review for the add-on by this user.

**Comment by kumar303** [comment]
ok, I see what you mean. Well, I think we need both filters. I updated the issue description.

**Comment by kumar303** [comment]
This is more urgent than I first thought because our workaround would need to page through all possible user reviews to find the right one.

**Comment by kumar303** [comment]
If it helps to do this incrementally, this feature (from the description) is more important:

> retrieve a saved review by user, add-on ID, and version ID (there will only be one)

**Comment by diox** [comment]
Note that currently, when you're looking at add-on reviews with `/api/v3/addons/addon/{addon}/reviews/`, it only shows you the latest review for each user, so you're already guaranteed to only see one review per user per add-on using this API.

**Comment by diox** [comment]
I think it was a mistake on my part to have reviews under `/api/v3/addons/addon/{addon}/reviews/` and `/api/v3/accounts/account/{account}/reviews/`. I'll probably have to move them to `/api/v3/reviews/` and add filtering through query string parameters instead.
