### ISSUE TITLE
"This field is required" warning displayed in the wrong place when adding new files without selecting a platform

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3998]
Steps to reproduce:
1.Go to dev hub and submit an add-on with only a platform selected(ie. Linux)
2.Go to Manage Status & Versions page for this add-on and and click on the previously submitted version
3.Click the upload another file, select a file , validate it, but don't select any target platform 
4.Click Add File button

Expected results:
"This field is required" should be displayed above the target platforms section

Actual results:
"This field is required" is displayed above validation section and this is confusing because validation successfully passed

Please see video for this issue : 
![fieldrequired](https://cloud.githubusercontent.com/assets/1583842/20269446/c00a76dc-aa8b-11e6-87e8-6d0093e0d003.gif)

**Comment by eviljeff** [comment]
this form has been removed so I think it's fixed... please re-open/re-file if it's still reproducible.

**Comment by vcarciu** [comment]
Yeah , this is now fixed : 
![leastoneplatform](https://cloud.githubusercontent.com/assets/1583842/24145140/8d54dfdc-0e38-11e7-93dd-457194b9e95b.png)
