### ISSUE TITLE
Don't show the "Could not parse the manifest file" error for an already validated add-on

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#3999]
Steps to reproduce:
1.Go to dev hub and start a new add-on submission
2.Select how to distribute the add-on and then Continue
3.Select an add-on which passes the validation and click Continue
4.Go back (in order to change the platform for example) and press again Continue

Expected results:
Submission is going to the next step or we should change the warning and say that we have to upload the file again

Actual results:
"Could not parse the manifest file" message is displayed

Please see a video for this bug : 
![parse](https://cloud.githubusercontent.com/assets/1583842/20269939/eb7a0a42-aa8d-11e6-82b2-e8efe5ad78ec.gif)

**Comment by EnTeQuAk** [comment]
This is probably minor priority since it's been like that forever but true, I can imagine that this sucks workflow-wise.

I'm not too sure if it's an easy fix though so it might have to wait for all the new things tools coming up in 2017.
