### ISSUE TITLE
Reset current_version on deleted unlisted add-ons and add-ons with mixed versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4008]
When we made `current_version` for listed versions only we made a task to process existing add-ons and reset their `current_version`, but that task is currently not covering these 2 edge cases:

1. [ ] deleted unlisted add-ons. Those might need a SQL migration to unset `current_version` for good (doing it from python is unreliable, re-saving deleted add-ons might not work in all cases)

2. [x] add-ons with mixed unlisted/listed versions (created manually or using the waffle). I think it's not necessary to modify the script, we can just find them and fix them manually, there shouldn't be any in prod.

**Comment by eviljeff** [comment]
I did 2) on -dev via django console

**Comment by diox** [comment]
Actually, when we delete, we already unset current_version: `self.update(status=amo.STATUS_DELETED, slug=None,  _current_version=None)`

I wonder if somehow that bit isn't working properly ? Or maybe the add-ons I found on dev had their status altered manually.

**Comment by eviljeff** [comment]
I'm not sure we need to worry about STATUS_DELETED add-ons.  It doesn't really matter they're broken.  I'd close this now.

**Comment by diox** [comment]
Agreed
