### ISSUE TITLE
Add-on visibility both invisible and visible

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4015]
Steps to reproduce:
1. Submit a listed add-on in AMO-stage 
2. Reject it
3. Check Manage Status & Versions page i.e. https://addons.allizom.org/en-US/developers/addon/project-%C4%83-%C3%A2-%C3%A2-%C3%AE-%C3%AE-%C5%9F-%C5%9F-%C5%A3-%C5%A3-%E6%97%A5%E6%9C%AC%E8%AA%9E/versions

Expected results:
Add-on appears `Invisible` in both listing visibility and add-on status box.

Actual results:
Add-on visibility from the status box is `Invisible`, but the radio button from the listing visibility is `Visible`.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing on AMO-stage and -dev.
Screenshot for this issue: 
![invisible-visible](https://cloud.githubusercontent.com/assets/15685960/20348991/f51bd128-ac10-11e6-846e-538bd18ff365.png)

 #3471

**Comment by eviljeff** [comment]
@jvillalobos what should the right behaviour be?  My thinking was it was kind of inaccurate to say in the status box the listing was visible when it clearly wasn't (because there weren't any approved versions and it's status was Incomplete (STATUS_NULL))

**Comment by jvillalobos** [comment]
If an add-on is `Incomplete`, what makes most sense to me is that we don't show the visibility on the sidebar, nor show the visibility control in the status page. However, we can't hide the visibility control now because it's still possible to use it to switch to unlisted.

The short term solution would be to either hide the visibility from the sidebar when the add-on is `Incomplete`, or have it say that it's `Visible` (which isn't quite accurate, but at least is consistent).

**Comment by eviljeff** [comment]
This issue now conflicts with https://github.com/mozilla/addons/issues/193 where Visibility is shown as Listed rather than Visible. (What is the opposite of Visibility: Listed in the AMO section???).   Is there a time when we should show anything different?

**Comment by jvillalobos** [comment]
`Listed` is definitely not a valid visibility. When we show the visibility, it should either be `Visible` or `Invisible`.

**Comment by eviljeff** [comment]
Could just drop the 'Visibility' line altogether?  It's a relic from when the add-on was listed or unlisted which I re-purposed to match the status&versions page.  If the add-on is set as 'Invisible' the status changes anyway.

**Comment by eviljeff** [comment]
_Should_ the status change?  Currently if the add-on is 'Invisible' the Status label is changed to `You have disabled this add-on`.  Needs new copy for that if that's staying around.

**Comment by jvillalobos** [comment]
Yeah, I suppose it's simpler to show a single status to the dev. So, let's not have a separate line for visibility, and use `Invisible` as the status value if the add-on is invisible.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF50(Win 7).
1. Listed add-on can be:
- approved or awaiting - visible (left/right)
- invisible - invisible
![awaiting](https://cloud.githubusercontent.com/assets/15685960/20599426/c8e4c7b2-b256-11e6-950a-ef6a87e66ce6.png)

2. A listed add-on that is rejected it is: 
- incomplete - visible
- invisible - invisible
![rejected](https://cloud.githubusercontent.com/assets/15685960/20599442/d59be292-b256-11e6-9991-bccb8d4f2c1e.png)

3. An unlisted add-on can be:
- has no visible or invisible status
![unlisted](https://cloud.githubusercontent.com/assets/15685960/20599511/1d6f2afc-b257-11e6-8dcf-198f78d03a26.png)

@eviljeff - If those are the intended statuses, we can mark this as verified.

**Comment by eviljeff** [comment]
lgtm 👍 
@jvillalobos is that what you intended?

**Comment by jvillalobos** [comment]
Yeah, that looks good. I'll also note that #4061 was filed about the blue info box on the last screenshot, which should go away.
