### ISSUE TITLE
[Matching results] are displayed twice for Vietnamese

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4018]
Steps to reproduce:
1. Set the language to Vietnamese in AMO-stage : https://addons.allizom.org/vi/firefox/
2. Make a search

Expected results:
The number of "matching results" is written twice.

Actual results:
The number of "matching results" is displayed one time.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue: 
![duble](https://cloud.githubusercontent.com/assets/15685960/20355219/4890137e-ac29-11e6-822f-72296eb7aa62.png)

**Comment by ValentinaPC** [comment]
This is still reproducing on AMO-dev FF52(Win 7).
Screenshot: 
![vi](https://cloud.githubusercontent.com/assets/15685960/24155301/1b07aa62-0e5c-11e7-83bb-ed3f1b89d81d.png)

**Comment by EnTeQuAk** [comment]
It just wasn't on -stage yet, it's fixed there now. 
![screenshot from 2017-03-22 09-39-45](https://cloud.githubusercontent.com/assets/139033/24191373/8b1e64d0-0ee3-11e7-9521-16749ef979a2.png)

**Comment by ValentinaPC** [comment]
> It just wasn't on -stage yet, it's fixed there now.

I made the check in -dev - you can see the URL in my screenshot.

Verified again in AMO-dev FF52(Win 7), and seems to be fixed now.
Postfix screenshot:
![secondcheck](https://cloud.githubusercontent.com/assets/15685960/24192616/3dc11678-0ef8-11e7-99e9-66e4fbff706d.png)
