### ISSUE TITLE
Error displayed while adding a developer reply for second unlisted version of an add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4022]
Steps to reproduce:
1. Submit an listed i.e. add-on https://addons-dev.allizom.org/en-US/firefox/addon/source2/
2. Update the add-on with an unlisted second version
3. Go to `Manage Status & Versions` and give a `Reply` from `Review history` for the unlisted version

Expected results:
No error displayed.

Actual results:
A new tab page containing the message "{"detail":"Authentication credentials were not provided."}" is opened.

Notes/Issues:
Not reproducing if the add-on has only unlisted versions.
Verified on AMO-dev FF50 (Win 7)
Video for this issue: 
![reply](https://cloud.githubusercontent.com/assets/15685960/20396308/6eec8fb4-acee-11e6-85c7-82bf2a4e54f9.gif)

 #3469

**Comment by eviljeff** [comment]
Also part of #3726

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50 (Win 7)
Postfix screenshot: 
![reviewhistory](https://cloud.githubusercontent.com/assets/15685960/22291078/1adece00-e30d-11e6-9116-a74e86677859.png)
