### ISSUE TITLE
Setting an add-on waiting for approval to invisible leaves it with incorrect add-on status

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4024]
### Describe the problem and steps to reproduce it:

~~This only happens with the new listed-unlisted flow.~~

STR:
1. Submit a new add-on.
2. While waiting for approval, set its status to 'Invisible'.

### What happened?

The add-on status is 'Awaiting approval'.

### What did you expect to happen?

The add-on status should probably be 'Incomplete' if there are no other approved listed versions and 'Approved' if there are.
@eviljeff might know better though.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Nope.

**Comment by eviljeff** [comment]
example addon and/or screenshot?

**Comment by wagnerand** [comment]
https://addons-dev.allizom.org/en-US/admin/addon/manage/my-jetpack-addon5/

![screen shot 2016-11-17 at 18 21 23](https://cloud.githubusercontent.com/assets/873258/20399819/b445c69e-acf2-11e6-8ee8-1c8ec8234215.png)

**Comment by eviljeff** [comment]
So, we don't actually expose this wrong status anywhere?

**Comment by wagnerand** [comment]
At least not in devhub. There, we have a special terminology like "You have disabled this add-on."

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF50(Win 7).
Incomplete status is listed in Dev Hub pages and also in Admin Manage page after Invisible-Visible actions.
Postfix screenshots:
![admin](https://cloud.githubusercontent.com/assets/15685960/22292508/4715910a-e314-11e6-88f8-9aea03779a15.png)
![afterinvisible](https://cloud.githubusercontent.com/assets/15685960/22292509/471a9876-e314-11e6-97d3-36f8659cef7f.png)
