### ISSUE TITLE
Admin is not redirected back to "Manage user" page if changes his mind about deleting a user

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4031]
Steps to reproduce:
1. Submit into AMO-dev with an admin account
2. Go to "Manage user" for any user account i.e. https://addons-dev.allizom.org/en-US/firefox/users/edit/144770
3. Click "Delete account"
4. Click "No, take me back"

Expected results:
Admin is taken back to "Manage user" page.

Actual results:
Nothing happens.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing on AMO-stage and -dev.
Video for this issue: 
![no](https://cloud.githubusercontent.com/assets/15685960/20480203/3a4a9f68-afea-11e6-8f77-570453ae2451.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC Can you check the browser console with the security logging enabled. It's possible this is due to CSP.

**Comment by muffinresearch** [comment]
Actually looking at the code I can see this is an onclick attribute so it will be blocked by CSP because it's inline script.

**Comment by muffinresearch** [comment]
This will likely be fixed when we upgrade to django 1.10 since that removes all inline script to make it CSP friendly.

**Comment by ValentinaPC** [comment]
There is no error in the console. Other "No, take me back" buttons from Admin Tools don't work.

**Comment by diox** [comment]
Wontfixing because it's a minor issue in admin tools (plus https://github.com/mozilla/addons-server/issues/4031#issuecomment-262485133)
