### ISSUE TITLE
A word is missing from add-on delete popup window

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4032]
Steps to reproduce:
1. Go to "Manage My Submissions" page 
2. Load "Manage Status & Versions" page for any add-on i.e. https://addons.mozilla.org/en-US/developers/addon/colorzilla-stage/versions
3. Click the "Delete Add-on" red button

Expected results:
A popup window is displayed. No issues listed.

Actual results:
Word is missing from "Enter the following text confirm your decision: <<add-on name>>" phrase.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue: 
![text](https://cloud.githubusercontent.com/assets/15685960/20480540/9f7c85da-afeb-11e6-8b6e-73e9b156bb94.png)

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by eviljeff** [comment]
mentor @wagnerand

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7) for add-ons and themes deletion.
Postfix screenshot:
![missing](https://cloud.githubusercontent.com/assets/15685960/22418861/83193904-e6e3-11e6-875a-3f3bef167856.png)
