### ISSUE TITLE
Make file viewer compare channel aware

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#4040]
The file viewer checks permissions for access to unlisted files but the compare dropdown lists all files for all versions.  

Need to decide if we should show all files and allow cross-channel comparisons (if so should the UI be modified to indicate what channel the file is?);  or prevent cross-channel comparison, in which case should the access be on a different url?  
Or just show a different set of files to compare to depending on which channel the current file is in?

**Comment by eviljeff** [comment]
note: this isn't particularly high priority IMO as the file content itself is secured.

**Comment by jvillalobos** [comment]
Hiding unlisted files for the users without the right permissions is what matters most to me here. Another thing to keep in mind is that the compare links from review pages continue to work even for admins, and don't accidentally show a comparison with other channels involved.

Having some annotation next to the files indicating which ones are listed and which ones are unlisted seems like the right approach here.

**Comment by eviljeff** [comment]
the review page will only have links for comparisons within the channel
