### ISSUE TITLE
can't install amazon wish list on firefox

### ISSUE THREAD

**Issue by llprine** [mozilla/addons-server#4047]
### Describe the problem and steps to reproduce it:hit the install and says error, can't do it
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
Unfortunately the add-on author removed this add-on and are still linking to the odd add-on page which results in a 404 error page. Since we don't have any control over 3rd party sites there's nothing we can do from this end.
