### ISSUE TITLE
[DevHub Landing Desktop] Whats New section

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4052]
Supports mozilla/addons-frontend#1021

**Comment by EnTeQuAk** [comment]
This one landed already, follow-up issues for detail bugs may be created at a later time.

**Comment by ValentinaPC** [comment]
@EnTeQuAk : are these changes (new Dev Hub landing) ready for QA? Thanks!

**Comment by EnTeQuAk** [comment]
Actually, I lied, the what's new section isn't done yet. Reopening-

**Comment by EnTeQuAk** [comment]
@ValentinaPC we are aiming to switch the new devhub pages on some time this week on -dev - once that happens you'll be able to throw all the issues at us :)
