### ISSUE TITLE
EULA/PP links are not aligned for incompatible with your platform add-ons 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4056]
Steps to reproduce:
1. Load details page for an add-on incompatible with your platform https://addons-dev.allizom.org/en-US/firefox/addon/fireftp/?src=userprofile with Privacy Policy or EULA links

Expected results:
There are no display or layout issues.

Actual results:
The links are not aligned with the rest of the text.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing on AMO-stage and -dev.
Screenshot for this issue: 
![pp-eula](https://cloud.githubusercontent.com/assets/15685960/20559773/cea9bd0c-b17e-11e6-8d1c-4a9db3b65477.png)

**Comment by ValentinaPC** [comment]
This is now valid for Permissions link.
Please see the screenshot:
![perm_001](https://cloud.githubusercontent.com/assets/15685960/23132369/0b1d502a-f796-11e6-85d6-e2511ee010e9.png)

**Comment by diox** [comment]
Minor issue that will be fixed in addons-frontend when it implements desktop.
