### ISSUE TITLE
White padding in screenshot section while resizing the browser

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4058]
Steps to reproduce:
1. Load details page for any add-on i.e. https://addons.mozilla.org/en-US/firefox/addon/download-youtube/?src=hp-dl-featured
2. Resize your Firefox browser - until an horizontal scrollbar appears

Expected results:
There are no display or layout issues.

Actual results:
A white padding appears in the screenshot section.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing all around AMO servers.
Video for this issue: 
![white](https://cloud.githubusercontent.com/assets/15685960/20566243/08241fdc-b19d-11e6-8b57-823ceb3be646.gif)

**Comment by vijeth-aradhya** [comment]
@ValentinaPC 

This does not seem to happen in Chrome, but only happens with Firefox

![google](https://cloud.githubusercontent.com/assets/15227565/20844365/6c7fe46c-b8e5-11e6-9c66-1f5258f52acb.png)

**Comment by ValentinaPC** [comment]
It can be seen in the add-on details page, screenshot section.
![whitep](https://cloud.githubusercontent.com/assets/15685960/20875926/1d9084ae-bac7-11e6-839c-8f3f223fb34f.png)

**Comment by diox** [comment]
Minor issue that will be fixed in addons-frontend when it implements desktop.
