### ISSUE TITLE
Send an automated email to a list of add-ons based on a DB query

### ISSUE THREAD

**Issue by shell15** [mozilla/addons-server#4060]
We have a list of ~50  more add-ons and their IDs that we need to email to let them know that calling CPOWs directly isn't going to be supported.  We are allowing it for add-ons that have already done it to continue - but we actively block CPOW usage for add-ons marked MPC=true.   Timing wise it would be good to send out before end of January.   With only 50 i could send manually if the bug is too complex.

It would be nice to be able to put the add-on name into an email that goes out to them if possible.

from Jorge:  There's an admin tool on AMO that can send an automated email to a list of add-ons based on a DB query. Since we already have the add-on IDs, it's just a matter of building the query using those IDs. This requires a patch, so I suggest filing an issue on Github soon if it's needed to run next week. Andrew Williamson has done this before, so you can ask him for specifics.

Here is the link to the letter https://docs.google.com/document/d/1ZFy2B6C-C8B0jfEgd0eAazTv0xXg2A6-HRdiVN2I5Uo/edit

**Comment by diox** [comment]
@shell15 End of January was a couple months ago, is this issue still necessary? Did we end up sending that mail by another method ?

**Comment by jvillalobos** [comment]
We've been doing messaging in various forms, and we're tracking all compatibility issues and comms on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1335456) now.
