### ISSUE TITLE
"Why can't I switch to Listed?" info for no-version add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4061]
Steps to reproduce:
1. Submit a listed add-on in AMO-dev i.e https://addons-dev.allizom.org/en-US/developers/addon/listed-novers/versions
2. Delete its version

Expected results:
User is not informed that he can switch to `listed` only if deleted the entire add-on.

Actual results:
User is informed that he can switch to `listed` only if he deletes the entire add-on.

Notes/Issues:
- happening for "unlisted" add-ons also
- the term `listed` no longer exists in dev-hub
- user can make the add-on "listed" by adding a new listed version.

Verified on FF50(Win 7). Issue is reproducing on AMO-dev.
Screenshot for this issue: 
![listed-novrs](https://cloud.githubusercontent.com/assets/15685960/20600234/412afe04-b25b-11e6-9098-233a0ee7c625.png)

**Comment by jvillalobos** [comment]
That info box should go away with listed/unlisted channels, though I don't think the spec ever said explicitly to get rid of it.

**Comment by eviljeff** [comment]
At the moment the box is a remnant of the existing process where you switch an entire add-on from listed to unlisted.   Should the box remain while the `mixed-listed-unlisted` waffle is disabled?  Or can it go now?

**Comment by jvillalobos** [comment]
It should remain until we enable the waffle flag.

**Comment by ValentinaPC** [comment]
With the mixed-listed-unlisted flag enabled, this is verified as fixed on AMO-dev FF50(Win 7).
Postfix screenshots:
![listed](https://cloud.githubusercontent.com/assets/15685960/20699675/3b544a26-b611-11e6-814b-b046289015ca.png)
![unlisted](https://cloud.githubusercontent.com/assets/15685960/20699678/3ffdc052-b611-11e6-9102-5b407059e631.png)
![mix](https://cloud.githubusercontent.com/assets/15685960/20699686/43947b20-b611-11e6-801a-163008a4b496.png)
