### ISSUE TITLE
Remove obsolete flag_binary task

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4063]
There is a very old `flag_binary` task that you can only call through `process_addons --task=flag_binary` or `process_addons --task=flag_binary_components` management command. It was introduced in 2b1bf381, so more than 5 years ago, I suppose it's obsolete and should be removed, but is it ?

**Comment by diox** [comment]
@jvillalobos and @andymckay do you know ?

**Comment by jvillalobos** [comment]
The [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=655115) says it was a one-time thing, so I think it's okay to remove.
