### ISSUE TITLE
New Version / New File submission flow bugs

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4064]
Here are the issues I think need to be addressed before we can waffle on the two new flows:

- [ ] Hide the Where to Host section in both of them (I believe there's a separate waffle flag for that, but I want to make sure).
- [ ] In the last step, remove the line above the Manage button that says `Your listing will be more successful by adding a detailed description and screenshots. Get your listing ready for publication:`. That line is only relevant for new add-ons.
- [ ] Text tweak, also in the last step: `You can also edit this version you just submitted by adding version notes` -> `You can edit this version to add version notes`
- [ ] In the Submit New File flow, first step, the subtitle should be `Upload File` instead of `Upload Version`.
- [ ] Also in the first step, the button says `Sign Add-on`, even when uploading a file for a listed version.
- [ ] (Unrelated, not a blocker) The text and link that appear below the file upload section after the upload initiates, indicating the source code upload policy, is all bold. Let's unbolden it, please :).

**Comment by eviljeff** [comment]
> Hide the Where to Host section in both of them (I believe there's a separate waffle flag for that, but I want to make sure).

The waffle currently hides the link to change but keeps the text block for information.

**Comment by jvillalobos** [comment]
But it's currently on, right? I saw the link when submitting a new version. Regardless, I would prefer to hide the whole block rather than just the link.

**Comment by eviljeff** [comment]
Its on, yes.  But the waffle (when not on) hides the link.

**Comment by eviljeff** [comment]
fwiw, 
>In the Submit New File flow, first step, the subtitle should be Upload File instead of Upload Version.

https://github.com/mozilla/addons/issues/192#issuecomment-252531408 shows the subtitle as 'Upload Version'

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7). I've named the screenshots 1 - 6 according to the points mentioned in the first comment.
Postfix screenshots: 
![1](https://cloud.githubusercontent.com/assets/15685960/20672718/e7524e0e-b58a-11e6-9ecb-732df6af6a68.png)
![newfile-2](https://cloud.githubusercontent.com/assets/15685960/20672728/eed59780-b58a-11e6-81eb-16b303612166.png)
![new-version2](https://cloud.githubusercontent.com/assets/15685960/20672732/f24e56b8-b58a-11e6-9477-52c69beba5b4.png)
![3](https://cloud.githubusercontent.com/assets/15685960/20672735/f7a283dc-b58a-11e6-844a-af9f20a9d114.png)
![4](https://cloud.githubusercontent.com/assets/15685960/20672740/fb0d36f2-b58a-11e6-89bb-e4e9112ef039.png)
![5](https://cloud.githubusercontent.com/assets/15685960/20672747/fe5392a2-b58a-11e6-9de3-fabbd7556e96.png)
![6](https://cloud.githubusercontent.com/assets/15685960/20672750/02aa9666-b58b-11e6-95be-643614bac8d3.png)
