### ISSUE TITLE
No longer support file deletion in add-on versions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4066]
Deleting and reuploading individual files inside add-on versions cause all sort of problems with reviews. We already disable file deletion after a version has been reviewed. Let's extend that to not allowing file deletion altogether. Developers can disable or delete entire versions if they need to reupload for some reason.

**Comment by ValentinaPC** [comment]
Is this fix in -dev?  Thanks!

**Comment by diox** [comment]
It should be, yes.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF51(Win 7).
Seems like I can delete files inside an non-approved add-on version.
Please see the video:
![deletefille](https://cloud.githubusercontent.com/assets/15685960/23754458/b42504ae-04e5-11e7-9cbe-46dfbfd6a4f8.gif)

Did I missed something?

**Comment by diox** [comment]
Maybe something wrong with dev deploy, I'll check it out.

**Comment by diox** [comment]
Yeah, it looks like there is a deployment issue on dev. I'll comment when it's fixed so that you can check again.

**Comment by diox** [comment]
Dev should be updated now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7).
Files cannot be deleted inside of a version, even if the version is not approved.
Postfix screenshot:
![delete_file](https://cloud.githubusercontent.com/assets/15685960/23760086/4758407c-04f7-11e7-9760-eb7a619b1222.png)
