### ISSUE TITLE
Migration banner - still available

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4070]
Steps to reproduce:
1. Load https://addons.mozilla.org/en-US/firefox/users/login page

Expected results:
User is redirected to FxA.

Actual results:
The migration banner is displayed.

Notes/Issues:
Issue is happening all around AMO servers.
Screenshot for this issue: 
![prod](https://cloud.githubusercontent.com/assets/15685960/20628362/2efea4fa-b32e-11e6-990d-a5d643147934.png)

**Comment by mstriemer** [comment]
This is intentional. I figured it was best to show that you did make it to AMO but the log in page has moved rather than redirecting to something completely different.

This is just if you put that URL in the address bar right? This shouldn't be happening via a link on the site.

**Comment by ValentinaPC** [comment]
@mstriemer : Using only the URL directly, yes.
The banner is also displayed when logged in, if entering the URL.
If logged in and clicking `continue` from the banner, user enters in a loop.
Video: 
![loop](https://cloud.githubusercontent.com/assets/15685960/20659887/2253ccbc-b54f-11e6-8624-5cf839d619fb.gif)

If this is also intended, let us close this. Thanks!

**Comment by mstriemer** [comment]
@designakt If you go to https://addons.mozilla.org/en-US/firefox/users/login (or register) by URL directly right now we show this "Log in with Firefox Accounts" page. We could redirect to FxA directly but I thought it would be weird to think you were going to AMO and land on FxA without any explanation as to why.

Do you think we should keep this page or redirect without it?

If you perform an action on the site like clicking log in or trying to add an add-on to a collection you are sent to FxA directly without seeing this page.

**Comment by andymckay** [comment]
Leave it, for those people who land on the page accidentally, its helpful for the meantime.

**Comment by ValentinaPC** [comment]
> This is just if you put that URL in the address bar right? This shouldn't be happening via a link on the site.

This is also happening while having two tabs with the AMO homepage (https://addons.mozilla.org/en-US/firefox/) opened and trying to sign in from both tabs => second `log in` will return the banner.
Please see the video: 
![banner](https://cloud.githubusercontent.com/assets/15685960/20881093/55fad328-bae3-11e6-8712-caf1052dd2f1.gif)

**Comment by mstriemer** [comment]
That should redirect you wherever you came from. I filed #4112 to fix this, thanks.
