### ISSUE TITLE
Link to extrabux extention doesn't work

### ISSUE THREAD

**Issue by Anaphemaphone** [mozilla/addons-server#4077]
Hello! I got to the website https://www.extrabux.com/extensions to try the extension they offer to work with. When I followed the link (pressed the button) there was a page with the text "Sorry, no extension found"
![screen shot 2016-11-27 at 17 34 41](https://cloud.githubusercontent.com/assets/24209215/20649831/39d8593e-b4c8-11e6-93a3-8e5714fdbe25.png)
![screen shot 2016-11-27 at 17 34 54](https://cloud.githubusercontent.com/assets/24209215/20649832/39f386aa-b4c8-11e6-9c12-c221b5c181ef.png)

**Comment by tofumatt** [comment]
The link included from extrabux is wrong so you'll need to contact them to change it on their site.

That said, I can't find that add-on on the site using search, so maybe it's been removed.
