### ISSUE TITLE
Last step of new file submission mentions "version" submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4081]
Steps to reproduce:
1. Submit an add-on in AMO-dev without checking all platforms 
2. Add a new file for that add-on
3. Observe the last step

Expected results:
"This **file** was submitted for review..." text displayed.

Actual results:
"This **version** has been submitted for review..." text displayed.

Notes/Issues:
Verified in FF50(Win 7). Issue is reproducible in -dev.
Video for this issue: 
![new-file-laststep](https://cloud.githubusercontent.com/assets/15685960/20673121/87cc0266-b58c-11e6-939c-e1966b7560a0.gif)

#4064

**Comment by jvillalobos** [comment]
I suggest doing these changes:

* Change title to `Submit a New File`.
* Remove subtitle `Version Submitted for Review`. The version was already submitted for review, and individual files aren't really submitted for review.
* On that same note, change button in first step to only say `Submit File`.
* Replace following paragraph with only `You're done!`.

The rest can remain the same.

**Comment by eviljeff** [comment]
@jvillalobos can you quickly mockup what the page should look like in terms of copy?

**Comment by eviljeff** [comment]
Also, note the layout/copy is different for unlisted versions so need for those versions too.

**Comment by jvillalobos** [comment]
Step 1 - Listed. Only changed the button label.
![step-1-listed-fullpage](https://cloud.githubusercontent.com/assets/62568/21408011/1b04c690-c798-11e6-8b06-6f82685d846d.png)
Step 2 - Listed. Renamed main header, removed second header, cut down paragraph to only say you're done.
![step-2-listed-fullpage](https://cloud.githubusercontent.com/assets/62568/21408010/1b04562e-c798-11e6-94d8-cd6d1810d25d.png)
Step 1 - Unlisted. Stays the same.
Step 2 - Unlisted. Changed headers and paragraph to say "file" instead of "version".
![step-2-unlisted-fullpage](https://cloud.githubusercontent.com/assets/62568/21408009/1afd8312-c798-11e6-8b57-a98374861547.png)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF50.1(Win 7).
Postfix screenshots:
> Step 1 - Listed. Only changed the button label.
![listed_-_newfile](https://cloud.githubusercontent.com/assets/15685960/21602997/77b5b494-d1a2-11e6-9e2e-c2c98359b5cf.png)
> Step 2 - Listed. Renamed main header, removed second header, cut down paragraph to only say you're done.
![step2-listed](https://cloud.githubusercontent.com/assets/15685960/21603000/87ac10be-d1a2-11e6-9044-a7524f9e4adc.png)
> Step 1 - Unlisted. Stays the same.
@jvillalobos **About the "Sign Add-on" button from new file page - shouldn't this be "Sign File"?**
![unlisted_-_submit_file](https://cloud.githubusercontent.com/assets/15685960/21603028/c3ae0040-d1a2-11e6-9f02-91f2bbc5b16a.png)
> Step 2 - Unlisted. Changed headers and paragraph to say "file" instead of "version".
![step2_-_unlisted](https://cloud.githubusercontent.com/assets/15685960/21603036/d62eb98a-d1a2-11e6-9e9a-9e88ff30fbf1.png)

**Comment by jvillalobos** [comment]
>  @jvillalobos About the "Sign Add-on" button from new file page - shouldn't this be "Sign File"?

Didn't think it was worth making that change.

**Comment by ValentinaPC** [comment]
> Didn't think it was worth making that change.

Marking this as verified fixed.
