### ISSUE TITLE
`Last updated` is empty for unlisted add-on

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4083]
Just noticed this on [an unlisted add-on I manage](https://addons.mozilla.org/developers/addon/amo-admin-assistant-unlisted/edit). The `Last Updated:` label doesn't have anything next to it. I uploaded a new version today, don't know if that's the reason.

**Comment by diox** [comment]
That's consistent with what I've found in #4028 - it seems that `last_updated` is never updated for unlisted add-ons.

**Comment by ValentinaPC** [comment]
Before these changes, was the same, as far as I remember.
![2016-11-29_0833](https://cloud.githubusercontent.com/assets/15685960/20699221/d8141dd0-b60e-11e6-98f3-1b93c49c2747.png)

**Comment by eviljeff** [comment]
This will be fixed when #4028 is finished.

**Comment by eviljeff** [comment]
This looks fixed on -dev, as expected, so closing.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF50(Win 7)
`Last updated` is not empty anymore -> 
![2016-12-22_1014](https://cloud.githubusercontent.com/assets/15685960/21419507/b3570eba-c830-11e6-8ba1-f6988dfaf56f.png)

-> but it is not updated if a new version is added for that add-on ->
![noupdates](https://cloud.githubusercontent.com/assets/15685960/21419530/e3f8f998-c830-11e6-84ea-e2565c66fca8.png)

Let me know if we can reopen this issue, or log another. Thanks!

**Comment by eviljeff** [comment]
The last updated date is actually updated on a daily cron, so it might take 24 hours to show.  (Yes, this is weird, but it's how listed add-ons work now so we'll upgrade that functionality at a later point)

**Comment by ValentinaPC** [comment]
Based on previous two comments I'll mark this verified-fixed.
