### ISSUE TITLE
First add-on welcome email has old reviewer links

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4085]
Testing for some other issue, I created a new account and submitted an add-on. The email I got for submitting it has a section beginning with:

> Get Ahead in the Review Queue!

The links point to https://wiki.mozilla.org/Marketplace/Reviewers or subsections of that page. They should be pointing to https://wiki.mozilla.org/Add-ons/Reviewers instead.

Looks like the files to change are `olympia/devhub/templates/devhub/email/submission.html` and `olympia/devhub/templates/devhub/email/submission.txt`

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by eviljeff** [comment]
mentor @jvillalobos

**Comment by ValentinaPC** [comment]
Using Fake Mails page from Admin Tools, on AMO-dev FF50(Win 7), this is verified.
Postfix screenshot:
![links](https://cloud.githubusercontent.com/assets/15685960/20828262/5b01a88a-b87f-11e6-84af-7e17907abc98.png)
