### ISSUE TITLE
Unusable "Upload new version" button in "Manage Status & Versions" page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4086]
Steps to reproduce:
1. Go to "Manage Status & Versions" page for any submitted add-on i.e. https://addons-dev.allizom.org/en-US/developers/addon/ghghbjm/versions

Expected results:
One option of "Upload new version" is available.

Actual results:
Two options of "Upload new versions" are available.

Notes/Issues:
Verified on FF50(Win 7). Present all around AMO servers.
Screenshot for this issue:
![button](https://cloud.githubusercontent.com/assets/15685960/20702432/7a963578-b620-11e6-8667-3cc205f1c7c0.png)

**Comment by vijeth-aradhya** [comment]
@ValentinaPC Are there two buttons "Upload a New Version"?

**Comment by ValentinaPC** [comment]
@vijeth-aradhya : there is an "Upload New Version" link (in the add-on status box from the left) and an "Upload a New Version" button on the right, both loading the same page.
![newversion](https://cloud.githubusercontent.com/assets/15685960/20876032/d88f91dc-bac7-11e6-919e-0b3585747fca.png)

**Comment by vijeth-aradhya** [comment]
@ValentinaPC Oh I understand :smile:
What do you think should be done? Should the extra button be removed, and only the link on the left be kept as it is?

**Comment by ValentinaPC** [comment]
@vijeth-aradhya : If you ask me, yes. The button had a purpose in the past, but I cannot see one now.
But, lets ask someone else about this and its solution, @EnTeQuAk ?

**Comment by EnTeQuAk** [comment]
More is always better is the contra to minimalism 😆 This isn't wonderful I agree but it's been like that forever and unless one of these buttons don't work anymore (which is suggested by the title but doesn't appear to be the case?) I'm in favor of simply ignoring this in favor of our wonderful work going on in addons-frontend.

So, if there's an actual bug that's not UI/UX related please feel very free to re-open at any time.
