### ISSUE TITLE
Don't disable statistics dashboard for dev-disabled add-ons

### ISSUE THREAD

**Issue by dhemmert** [mozilla/addons-server#4092]
### Describe the problem and steps to reproduce it:
Team,  the add-on SalesforceOverlay (Developed by Nate Snow and managed by myself) has been removed from public visibility.  However, I needed to get metrics related to the add-on like "How many downloads? and Where were the downloads from?" but since it was removed the dashboard I had before is no longer accessiblie.

### What happened?
Dashboard statistics/metrics not available anymore

### What did you expect to happen?
Wasn't aware that this data would be removed immediately and would like to recover if possible.

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/salesforceoverlay/versions/

**Comment by jvillalobos** [comment]
You can temporarily enable your add-on, get what you need from the stats dashboard, and then disable it again. The data isn't gone, it's just inaccessible in the current state.

I'll keep this bug open in case anyone wants to take it. Seems like an easy thing to fix.

**Comment by EnTeQuAk** [comment]
Should this dashboard maybe still be accessible by the add-on developer so that the enabling back and forth isn't needed anymore? Adding this permission check shouldn't be too heavy, could be a good first bug to work on in the backend views.

**Comment by wagnerand** [comment]
The triage team thinks: This is probably not a good first bug

**Comment by diox** [comment]
I do think it's a good first bug for python/django contributors, the changes required are minimal.

To sum up, the issue is that we'd like to let developers (or people with specific `STATS_VIEW` permission) view statistics for add-ons that have been disabled by user. However, we don't want general public to view them.

A contributor would need to look at the views in the `stats` app and do the following:

1. Figure out what is preventing user disabled (`disabled_by_user` property) add-ons from showing their statistics and change that to allow them.
2. Change the permission check so that when we display stats because the add-on is configured to show its stats publicly (`public_stats` property), we also check that the add-on itself is public (Adding a `is_public()` call for that specific condition)
3. Change tests accordingly. There is already a test covering this, and it has comments explaining what is currently tested so what needs to be changed should be straightforward.

**Comment by Akhila499** [comment]
Hello Mentors, 

I am Akhila and I am outreachy applicant for March 2020. I would like to work on this issue if it is considered as firstbug/outreachy eligible issue. I am currently reading through the Mozilla addon contribution page (https://wiki.mozilla.org/Add-ons/Contribute/Code). 

@diox @eviljeff Kindly help me in getting up to speed with the issue.

**Comment by eviljeff** [comment]
@Akhila499 diox already detailed what to do in the comment above.  For general setup the wiki link you posted has all the details.

**Comment by caitmuenster** [comment]
Mentor: @diox

**Comment by Akhila499** [comment]
Hi @diox @eviljeff I have installed Docker and was able to run olympia.test and was able to get into Sh shell. However, I use pycharm for my code changes and I am unable to figure out a way to run pycharm inside the Docker engine. I did try installing busybox but I seem to have hit a dead end there. KIndly help me in being able to run the addons server and the code from Pycharm concurrently on Ubuntu Machine.
Thanks

**Comment by diox** [comment]
I am not sure anyone on the team use PyCharm at the moment, and if somebody is they are probably not using the docker integration, it's not needed. Don't run the project from inside PyCharm, follow our installation instructions over at https://addons-server.readthedocs.io/en/latest/topics/install/index.html to run a local env.

**Comment by avgupt** [comment]
Hello is anyone still working in this issue? I would like to take this up.

**Comment by eviljeff** [comment]
> Hello is anyone still working in this issue? I would like to take this up.

As you can see @Akhila499 was working on it.  I don't know if they got past their general setup problems though.

**Comment by avgupt** [comment]
@Akhila499 please let me know if you're not working on the issue anymore. :)

**Comment by Akhila499** [comment]
> @Akhila499 please let me know if you're not working on the issue anymore. :)

@avgupt I am working on this issue. Thanks.

**Comment by Akhila499** [comment]
HI @diox @eviljeff Although I worked on Python programming before this is my first time working in a linux and open source environment. Pardon me for being slow to catch up. I am having trouble installing and running the addons webserver. I tried all I can. I am unable to run the webserver.

Initially, I had issues with docker-compose. Now, I am past that and currently facing issues with Django and its settings.
Here is the error I am dabbling with:

![image](https://user-images.githubusercontent.com/60104414/77450726-b5b50a80-6e19-11ea-9178-afd27665c5ab.png)

I also tried by changing write and read permissions of the mentioned folders. But Could not make it work.

**Comment by avgupt** [comment]
@Akhila499 What command did you run?

**Comment by Akhila499** [comment]
> @Akhila499 What command did you run?

I finished 'docker-compose up -d' and
This is the output after 'make initialize'

**Comment by eviljeff** [comment]
it's not really practical to debug setup problems via an issue (and it makes the issue harder to follow because the setup problems are unrelated to the actual bug/feature).  Please join us on https://chat.mozilla.org/#/room/#amo:mozilla.org

**Comment by Akhila499** [comment]
Hi, I am working on linux env for the first time. I had learnt a lot in the past few weeks regarding installation and set up of applications in Linux. However, I am not sure, I can get past some of the issues I articulated above. So, I request you to unassign the task. Thanks for the support
Regards,
Akhila

**Comment by hundredrab** [comment]
Hi! If this issue is unclaimed, I'd like to work on this.

**Comment by eviljeff** [comment]
@hundredrab doesn't look like anyone is working on it right now.

**Comment by willdurand** [comment]
Adding this to my list of things since it might be automagically fixed.

**Comment by willdurand** [comment]
Looks like it was fixed when we removed the stats visibility property.

**Comment by willdurand** [comment]
> Looks like it was fixed when we removed the stats visibility property.

Ha, no. Wrong property.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on AMO stage with FF76(Win10). 

With a developer account I disabled from dev hub all versions of a listed add-on: "View Statistics Dashboard" link is available and accessible from the menu on the[ left](https://addons.allizom.org/en-US/developers/addon/ibish-sheeros-gnaill2/versions). 
"Statistics" link to an incomplete add-on won't be available on[ Manage my submission](https://addons.allizom.org/en-US/developers/addons?page=2) page.

I made the add-on invisible: same results as I mentioned above when disabling the addon.

Let me know if that's the expected. Thanks!

**Comment by willdurand** [comment]
Yes, I think that's expected, although an improvement would be to show the link on the "Manage my submission" page, I guess.

We don't show this link on this page for unlisted add-ons either so maybe we could try to show this link more often?

**Comment by ioanarusiczki** [comment]
@willdurand I filed a followup for all the cases. https://github.com/mozilla/addons-server/issues/14595
Verified on AMO dev with FF76(Win10).
