### ISSUE TITLE
Drop or Fix unique names for addons

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#4095]
Listed add-ons have unique names*; Unlisted add-ons do not.  Having mixed listed and unlisted versions complicates this - think an addon with the first unlisted versions being called 'Ad Block Plus', and then the second version is submitted as listed.   *(This uniqueness may or may not be enforced for new submissions or changes via edit listing, under some circumstances though.)

First question: Do we want to keep enforcing a unique name for Add-ons?

If so, then we should somehow fix the listed/unlisted conundrum (and make sure we do actually enforce it, but that's another issue);  If not then lets drop it entirely.

**Comment by jvillalobos** [comment]
The main pro of name uniqueness is to not allow developers to trick users into installing an add-on with the same name as an existing one. But that can be easily worked around by submitting an add-on with a very similar name, or playing around some of the uniqueness gaps with localization, name changes, etc. It doesn't seem like it justifies the cons and complexity.

Let's kill it 🦃

**Comment by diox** [comment]
This will help #4028 - one less thing to fix there.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF50(Win 7).
@diox : While same name is accepted, same slug returns an error which, I suppose is intended, yes?
 Postfix screenshot:
![samename](https://cloud.githubusercontent.com/assets/15685960/20828655/3e622220-b881-11e6-9b15-c7cb807f95a4.png)
