### ISSUE TITLE
Unlisted add-on search doesn't return `Incomplete` add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4104]
I went to the unlisted reviewer tools looking for an add-on using its guid and couldn't find it (the add-on's numeric ID is 711557). It turns out that it has an `Incomplete` status, which is probably filtered out from the results. I believe that the `Incomplete` status is related to the latest version channel changes, so we should make sure that any unlisted add-on searches account for `Incomplete`.

**Comment by eviljeff** [comment]
All the 100% unlisted add-ons have an `Incomplete` status now, as we changed status so it's dependant on the listed versions only.  What are you searching for? - 'Categorization' wfm.

**Comment by jvillalobos** [comment]
It didn't work when I looked for it before, using its guid and its name. Seems to work now, so I don't know what happened.
