### ISSUE TITLE
UI issues while hovering over an incompatible add-on

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#4108]
**Steps to reproduce:**
1.Launch Firefox and navigate to https://addons-dev.allizom.org/en-US/firefox/extensions/?sort=created&page=637.
2. Hover over “Image Assistant” add-on.

**Expected results:**
The incompatible message is displayed without any jerkiness or rendering issues.

**Actual results:**
Visual glitches appear while hovering over the add-on.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 53.0a1 (2016-12-01) under Windows 10 64-bit.
- This issue is reproducible only for those add-ons that provide the incompatibility reason via the question mark.
- Please see the attached screencast for this issue:
![glitches1](https://cloud.githubusercontent.com/assets/18114210/20836513/5ed5a762-b8a8-11e6-90a2-ce62ea0457fb.gif)
- There is a different behavior while searching for the incompatible add-on - the text modifies its alignment:
![glitches2](https://cloud.githubusercontent.com/assets/18114210/20836522/68c8b246-b8a8-11e6-828c-fb422edce37f.gif)

**Comment by EnTeQuAk** [comment]
Closing in favor of our ongoing work on addons-frontend. It'll not have any of these bugs, I'm so very sure of it :)
