### ISSUE TITLE
Visible-approved add-on is not available in public pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4109]
Steps to reproduce: 
1. Submit an "unlisted" add-on 
2. Submit a new "listed" version for that add-on and approve it i.e. https://addons-dev.allizom.org/en-US/developers/addon/samename-listedsecond/edit
3. Click the "View Listing" link from "Manage Status & Versions" page

Expected results:
Add-on public page is loaded.

Actual results:
A 404 page is loaded.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing on AMO-dev and AMO-stage.
Video for this issue: 
![vl](https://cloud.githubusercontent.com/assets/15685960/20837726/fc9ec3c0-b8ad-11e6-8977-ee94e221d0b1.gif)

**Comment by eviljeff** [comment]
@diox can you think / see anything obvious why this add-on listing is a 404?

**Comment by diox** [comment]
`is_listed` is `False` for this add-on, so the `objects` manager is not finding it. It'll be fixed when #4028 is fixed.

**Comment by eviljeff** [comment]
This looks fixed now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
Postfix video: 
![viewlisting](https://cloud.githubusercontent.com/assets/15685960/21418930/599b99b6-c82d-11e6-8d83-1c7fca12bf8d.gif)
