### ISSUE TITLE
Start using a central billing account for our translation service

### ISSUE THREAD

**Issue by wresuolc** [mozilla/addons-server#4110]
We started using Google's translate API in 2013 to automatically translate comments on the site so that more folks could review them easily.  It was an experiment that (I assume?) has been convenient and useful.

It's still billing my credit card every month, and it's not a large amount of money (usually ~$1, although it spiked up to $13 last month which was unusual and maybe should be investigated?) but we should probably clean that up at some point and get it billing some central account.

**Comment by jvillalobos** [comment]
I looked into the feature a while ago and it didn't appear to be used much. We should consider removing it altogether as part of the ratings work we're planning for next year.

**Comment by EnTeQuAk** [comment]
I'm labeling this as `redesign` humbly hoping to just track this and avoid us not seeing it when the time comes.

**Comment by diox** [comment]
Let's kill it or re-implement it cleanly in addons-frontend.
