### ISSUE TITLE
Use redirect path if available when logging in and already logged in

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#4112]
### Describe the problem and steps to reproduce it:
When you are already logged in to AMO and try logging in again you get an error telling you that you are already logged in. This error is shown at /users/login/ and should instead redirect the user to the `to` path if it is valid, otherwise /users/login/ is fine.

1. Open AMO in two tabs.
2. Log in in one tab.
3. Log in in the other tab.

### What happened?
You are redirected to /users/login/ and shown an error.

### What did you expect to happen?
You are redirect to wherever you clicked the "Log in" button and shown an error.

### Anything else we should know?
![ValentinaPC's screencast](https://cloud.githubusercontent.com/assets/15685960/20881093/55fad328-bae3-11e6-8712-caf1052dd2f1.gif)

From #4070.

**Comment by mstriemer** [comment]
We should be passing the `next_path` to the `render_error` function in `olympia.accounts.views.with_user` [1]. You can see how it is passed in the other cases.

You should just need to update `next_path=None` to `next_path=next_path` and update the tests.

Feel free to message me here or on IRC (mstriemer) with questions if you would like to work on this.

[1] https://github.com/mozilla/addons-server/blob/a618d2f69fbb750a768fb93bac6ab2007c7a8fe1/src/olympia/accounts/views.py#L192

**Comment by vijeth-aradhya** [comment]
@mstriemer I have an honest question :sweat_smile:
If the user already has a session going on (logged in), and enters the Log In page, then he should just be redirected to addons main page right ( https://addons.mozilla.org/en-US/firefox/ )? 
Why do we even let the user enter his login details again in the first place?

So, if the user enters his Log In details again, then the error must be shown in the same page (in the log in page). Is that what you are saying? If no, then where should he be redirected to? (link?)

**Comment by mstriemer** [comment]
@vijeth-aradhya redirecting to the homepage would make sense but I think we should do that as a separate bug if that's okay. This issue could still happen even if we make that change by clicking the "Log in" link in two separate tabs and completing the flow in each. The second tab to complete the flow would see this error.

As for where to redirect, when the user clicks the "Log in" link we pass a parameter to FxA and that path is available in the view I linked to as `next_path`. We should be able to redirect them to where they clicked the "Log in" link by updating the line I linked to above to pass the `next_path` to the `render_error` error handler.

**Comment by vijeth-aradhya** [comment]
@mstriemer Can you help update the tests? How do I get started?

**Comment by mstriemer** [comment]
@vijeth-aradhya Unfortunately the test didn't fail with your changes as I expected. The test that should change is [`test_logged_in_disallows_login`](https://github.com/mozilla/addons-server/blob/90126e8d1601401fe14eb720596a559b9a983bdc/src/olympia/accounts/tests/test_views.py#L475).

The reason it doesn't fail is that the next path is pulled from the state and this test isn't setting the next path in the state so it falls back to using `None`. You'll want to update line 476 to set a next path. Once you change that the test should fail and you can make it verify that the next path is set correctly.

```diff
-        self.request.data = {'code': 'woah', 'state': 'some-blob'}
+        self.request.data = {
+            'code': 'woah',
+            'state': u'some-blob:{next_path}'.format(
+                next_path=base64.urlsafe_b64encode('/some/path')),
+        }

**Comment by vijeth-aradhya** [comment]
@mstriemer I've made similar changes with only '/next' path. Is is okay?

**Comment by mstriemer** [comment]
@vijeth-aradhya sorry for the late reply, I was travelling.

Those changes look good, mind opening a pull request and linking to this issue?

One thing I'd suggest changing is the message in the commits. We normally use a format like: `Short description of change (fixes #1234)` so something like `Redirect to next path instead of user login on error (fixes #4112)` might be a good message for this. I can change the commit message when I merge it if that's easier.

Once you've got a pull request open I think this should be good to merge.

**Comment by ValentinaPC** [comment]
This issue is still reproducing.
Verified on AMO-dev FF50(Win 7).
Video: 
![2tabs](https://cloud.githubusercontent.com/assets/15685960/21175305/42c15850-c1ea-11e6-8bf6-249cda6fc93a.gif)

Reopening until further notice.

**Comment by mstriemer** [comment]
Looks like I didn't catch all the spots that needed a change. @vijeth-aradhya's change was needed but we'll need one more change for this to work the way we want.

In [`olympia.accounts.views.render_error`](https://github.com/mozilla/addons-server/blob/6e72b4765b6f6a6a0665a8e53704e12611f84471/src/olympia/accounts/views.py#L133-L135) it is always redirecting to the "users.login" endpoint. We instead only want to do that when `next_path is None` (basically what's there but without the `urlparams()` call to set the `to` query param) and otherwise just do `HttpResponseRedirect(next_path)`.

If you make the changes I suggested above it should just be the [`TestRenderErrorHTML.test_error_no_code_with_safe_path`](https://github.com/mozilla/addons-server/blob/6e72b4765b6f6a6a0665a8e53704e12611f84471/src/olympia/accounts/tests/test_views.py#L269-L278) test that fails and it will just redirect to `/over/here`.

I had problems logging in with FxA when I tested this before but I've sorted this out and am quite confident it will work this time.

@vijeth-aradhya if you'd still like to work on this extra change I'm happy to review your changes again.

**Comment by vijeth-aradhya** [comment]
@mstriemer I have rebased my repo, and made the changes. Should I update the test as well?

**Comment by mstriemer** [comment]
@vijeth-aradhya if you put up a pull request I'll take a look at it. Feel free to update the test before you put it up but you can commit more changes when we see the failure too.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50.1(Win 7)
Postfix screenshot of second tab, after second log in:
![secondtab](https://cloud.githubusercontent.com/assets/15685960/21922823/357d15de-d979-11e6-916b-cf0884a7bd2e.png)
