### ISSUE TITLE
cannot Install the Universal Registry Button 

### ISSUE THREAD

**Issue by alansplace** [mozilla/addons-server#4113]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
go here: https://www.amazon.com/gp/registry/universal/
### What happened?
pressed install button
### What did you expect to happen?
Install the Add to Registry/Add to Wish List Firefox button.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
I end up here: https://addons.mozilla.org/firefox/downloads/latest/add-to-amazon-wish-list-button/addon-257015-latest.xpi?src=external-help

**Comment by jvillalobos** [comment]
The add-on was [removed by Amazon](https://addons.mozilla.org/addon/add-to-amazon-wish-list-button/), so it's up to them to fix that installation page.
