### ISSUE TITLE
No message while upgrading an Add-on to a WebExtension if versions are decreasing

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4116]
Steps to reproduce:
1. Submit a listed add-on in AMO-dev 
2. Approve it
3. Add a new version (also listed) for that add-on - a WebExtension - with smaller version compared to the add-on version i.e. https://addons-dev.allizom.org/en-US/firefox/addon/note-rev-add-on/

Expected results:
A message saying that you are going to upgrade your add-on to a WebExtension is displayed.

Actual results:
No message displayed.

Notes/Issues:
Add-on is upgraded to the WebExtension.
Verified on FF50.0.2(Win 7). Reproducing on -dev and -stage.
Screenshot for this issue:
![2016-12-06_1216](https://cloud.githubusercontent.com/assets/15685960/20921714/0b2d8086-bbae-11e6-9f09-3c9f76a340fe.png)

Relates to #3082

**Comment by EnTeQuAk** [comment]
summoning @jvillalobos if this is an issue which should be fixed or not.

We are only using the "previous version" for these checks which involves a check if the previous version is smaller than the current one. There might be other instances using this functionality relying on the same logic (e.g the addons validator annotator)

**Comment by jvillalobos** [comment]
It seems unlikely to happen in reality, and the fix is easy (resubmit with a higher version), so I don't think we should worry about this.
