### ISSUE TITLE
Bulk validation result page has duplicated add-ons and validation results

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4118]
### Describe the problem and steps to reproduce it:

The bulk validation result page does not deduplicate add-ons and validation reports shown are not filtered for a specific add-on, instead all validation reports are shown for an add-on. See the screenshot.

### Anything else we should know?

<img width="977" alt="screen shot 2016-12-06 at 15 50 41" src="https://cloud.githubusercontent.com/assets/873258/20951813/3a7baf52-bbcc-11e6-80f4-c996e413e401.png">

Adding @EnTeQuAk

**Comment by EnTeQuAk** [comment]
This got fixed in https://github.com/mozilla/addons-server/issues/4119

**Comment by EnTeQuAk** [comment]
Hmm, checking production apparently some add-ons are still duplicated. I'll check this again but at least the validation reports are reasonable now as far as I can tell.

If you sort by add-on it should be fairly easy to filter out the duplicates, I hope this works for now. Sorry about that.
