### ISSUE TITLE
No longer able to upload new listed addon versions via the API

### ISSUE THREAD

**Issue by erikdesjardins** [mozilla/addons-server#4124]
### Describe the problem and steps to reproduce it:

For a while we've been successfully deploying releases (both beta and stable, if that's relevant) to [a listed addon](https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/).

Starting a few days ago, all requests fail with `You cannot add a listed version to this addon via the API due to missing metadata. Please submit via the website`.

So we submitted via the website--and deploying via the API continues to fail with the same error.

And now it is unclear what we need to do at this point.

### What happened?

`PUT /api/v3/addons/jid1-xUfzOsOFlzSOXg@jetpack/versions/5.2.1/` failed with `You cannot add a listed version to this addon via the API due to missing metadata. Please submit via the website`

([log](https://travis-ci.org/honestbleeps/Reddit-Enhancement-Suite/jobs/182057731#L703), [previous attempt](https://travis-ci.org/honestbleeps/Reddit-Enhancement-Suite/jobs/181434456#L766))

### What did you expect to happen?

Either:
- the request succeeds, or
- the error response makes clear:
  - exactly what metadata is missing, and
  - whether or not adding that metadata (via the website or anywhere) will allow adding future listed versions to the addon via the API, or if they will always need to be submitted via the site

It also does not appear that [the docs were updated](https://github.com/mozilla/addons-server/pull/4073#issuecomment-262997771) with the change that added this error.

**Comment by eviljeff** [comment]
The add-on (somehow) is missing a license.  You can add one here:
https://addons.mozilla.org/en-US/developers/addon/reddit-enhancement-suite/ownership

(This shouldn't happen in the future but the new feature that would fix this if you submitted via the website isn't enabled yet)

**Comment by erikdesjardins** [comment]
Looks like that worked, thanks!
