### ISSUE TITLE
Displayed Internal Server Error on Review Notes.

### ISSUE THREAD

**Issue by hisamatsu-ts** [mozilla/addons-server#4126]
### Describe the problem and steps to reproduce it:
On the page below, after clicking Review History for our addon version 3.1 (refer to screenshots)
Internal Server Error has shown.
https://addons.mozilla.org/en-US/developers/addon/add-to-buyee/versions

### What happened?
The Review History hasn't be displayed.

### What did you expect to happen?
The Review History should be displayed.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/developers/addon/add-to-buyee/versions

screenshots:

<img width="1085" alt="screen shot 2016-12-08 at 2 36 02" src="https://cloud.githubusercontent.com/assets/11264227/20999220/8491a480-bd56-11e6-9d10-1590a3df4e2b.png">

**Comment by jvillalobos** [comment]
I can reproduce this. /cc @eviljeff

**Comment by eviljeff** [comment]
Narrowed this down to the log event that's created when approval notes are changed.  It's created without any text comment and the serializer assumes all review related log events have text to display.  So we need to fix the serialiser to handle events without text (and fix the log event?)

**Comment by eviljeff** [comment]
@wagnerand did you mean to log `APPROVAL_NOTES_CHANGED` without a `details` parameter?

**Comment by wagnerand** [comment]
I did. I didn't know this would cause trouble, I also didn't see that issue locally.

**Comment by wagnerand** [comment]
I mean, we can also just set something redundant like "The approval notes have changed" for `details`.

**Comment by eviljeff** [comment]
yeah that generic text would do.

**Comment by ValentinaPC** [comment]
Verified this in AMO-dev FF51(Win 7).
Seems like adding "Notes for Reviewers" in manage version page will brake the "Review history" link for add-on with mixed (or just listed/unlisted) versions, approved or awaiting review status.
Please see the screenshot:
![reviewer_tools](https://cloud.githubusercontent.com/assets/15685960/22419684/4d612c1e-e6e7-11e6-9022-772a35e5f29e.png)

Notes:
- deleting the notes will not repair the Review history link

@eviljeff : Let me know if this asks for another issue to be logged or can be included here. Thanks!

**Comment by eviljeff** [comment]
@ValentinaPC new issue.  This was fixed last year so we can't know it's the same problem.
