### ISSUE TITLE
Trying to approve an Add-on or a WebExtension does not work

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#4127]
Steps to reproduce:

1.Log in with valid credentials.
2.Navigate to Editor Tools.
3.From Queues -> New Add-ons list try to approve an Add-on or a WebExtension.

Expected results:
The approve process work's.

Actual results:
The approve process does not work, “Oops! We had an error” message is displayed.

Notes/Issues:
Verified on FF53.0a1 (Win 7 64-bit).
This issue is reproducing on -dev and stage servers.
Here is a video for this issue: 
![oopsy](https://cloud.githubusercontent.com/assets/15885467/21003708/8746f1a6-bd35-11e6-8648-d28ddf56f4f5.gif)

**Comment by wagnerand** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/371778/

**Comment by wagnerand** [comment]
@jasonthomas is this limited to -dev?

**Comment by jasonthomas** [comment]
This was affecting -dev and stage servers. It is now fixed.

**Comment by cosminbadescuSV** [comment]
The approve process is working now, this issue is verified as fixed on AMO-dev and AMO-stage on FF53.0a1 (Win 7 64-bit).
Postfix video: 
![anima](https://cloud.githubusercontent.com/assets/15885467/21040612/bd30c760-bdee-11e6-8891-032341564942.gif)
