### ISSUE TITLE
Force hybrid extension updates before a full web extension update

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4129]
Following on from https://bugzilla.mozilla.org/show_bug.cgi?id=1214790, it would be nice if AMO could force a hybrid add-on update before a full web extension update. This would mean there would less data loss by skipping a version.

**Comment by EnTeQuAk** [comment]
I believe this needs a bit more context. From what I understand you want us to return a hybrid-webextension version - if there is any - prioritised to a WebExtension version for an update request if the current version is a legacy add-on? And on the next update request we'd return the WebExtension version?

Is there a timeline need for this?

**Comment by andymckay** [comment]
@EnTeQuAk - Yep, that's exactly right.

This is part of the plans for 57, but would need to happen well before then. I know @jvillalobos had some opinions on this.

**Comment by jvillalobos** [comment]
We talked about this last week, and my impression is that this is very edge-casey and would be better served with clear documentation to developers, explaining they should give users enough time to update to the hybrid before pushing a full WE update.

**Comment by diox** [comment]
Is this still relevant? This isn't on our radar for 57 and as @jvillalobos said it seems very edge-casey.

**Comment by jvillalobos** [comment]
Probably not worth the effort. The devs I've talked to are aware they need to give users time to switch over.
