### ISSUE TITLE
“Check for Updates” does not work for Add-ons/WebExtensions

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#4133]
Steps to reproduce:

1.Install an Add-on or a WebExtension with a version that is not the latest.
2.Go to about:addons -> Extensions tab.
3.Click on the “Check for Updates” from the gear icon.

Expected results:
The Add-on/WebExtension is updated.

Actual results:
The Add-on/WebExtension is not updated.

Notes/Issues:
Verified on FF53.0a1 (Win 7 64-bit).
This issue is reproducing on -dev and stage servers.
Here is a video for this issue: 
![asd](https://cloud.githubusercontent.com/assets/15885467/21095930/51d9eab2-c066-11e6-885b-c5c48e31fb5e.gif)

**Comment by andymckay** [comment]
@bqbn certificate needs updating?

**Comment by muffinresearch** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1323300

**Comment by jasonthomas** [comment]
Updated cert on -dev and stage.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on AMO-dev and AMO-stage on FF53.0a1 (Win 7 64-bit).
Certificates are up to date, as presented in the video the update process for Add-ons/WebExtensions work as expected.

Postfix video:
![certs](https://cloud.githubusercontent.com/assets/15885467/21306186/6b0160fc-c5d8-11e6-89ff-8004d2e2c7b9.gif)
