### ISSUE TITLE
[Android Add-ons] Compatible with Android webextensions have "Download anyway" link in details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4134]
Steps to reproduce:
1. Submit a listed webextension in AMO-dev (automatically at submission all webextensions are available for both Firefox and Android applications) 
2. Approve the webextension and go to its details page i.e https://addons-dev.allizom.org/en-US/android/addon/addon10/?src=ss

Expected results:
There is a "Download now" green button.

Actual results:
Beside a "Download now" button there is a "Download anyway" nonfunctional link.

Notes/Issues:
Verified on FF50(Win 7). Issue is only reproducing on AMO-dev
Screenshot for this issue: 
![2016-12-12_1615](https://cloud.githubusercontent.com/assets/15685960/21102288/3cbf2f8c-c086-11e6-95b0-aef3307fdb82.png)

**Comment by ValentinaPC** [comment]
This kind of add-ons have other "form" in listing pages: a "view other versions" functional link and no "Download Anyway".
Example add-on details: https://addons-dev.allizom.org/en-US/android/addon/divtranslate/?src=cb-dl-mostpopular
Example listing pages: https://addons-dev.allizom.org/en-US/android/search/?q=divtranslate&cat=1%2C0&appver=&platform=

**Comment by muffinresearch** [comment]
I don't see in this in the new frontend, marking as wont-fix.
