### ISSUE TITLE
Big-blue-active installation buttons in about:addons if set for -dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4136]
Steps to reproduce:
1. Open a new clean Firefox profile
2. Go in about:config and set disco pane pref to point to -dev (`extensions.webservice.discoverURL` - `https://discovery.addons-dev.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%` )
3. Open about:addons page

Expected results:
There are a list of add-ons and themes together with their correspondent radio buttons. The buttons cannot be clicked.

Actual results:
For each add-on/theme there is a big blue button. If clicked, we end up in "What are Add-ons?" page.

Notes/Issues:
If `extensions.webapi.testing` is created and set to true, things look as before.
Issue is **only** reproducing for -dev.
Screenshot for this issue: 
![n](https://cloud.githubusercontent.com/assets/15685960/21104308/bb9c39c8-c08e-11e6-9d24-228f43decd38.png)

**Comment by muffinresearch** [comment]
This is the fallback for when mozAddonManager isn't available. I suspect the buttons should actually work though @mstriemer may know what the issue might be there. 

Only FF versions with mozAddonManager should hit this page so should be low impact.

**Comment by mstriemer** [comment]
The buttons should indeed work. The behaviour before was that the install buttons didn't work on -dev or if `mozAddonManager` was missing. I'll file an issue to clean up the styling in the disco pane but at Stuart mentioned these shouldn't appear in production.

Provided everything works when the config flag is flipped to allow `mozAddonManager` on -dev then I think it's safe to close this.

**Comment by mstriemer** [comment]
I filed #4141 to clean up the styling. I see you mentioned that it works as it did before when `mozAddonManager` is available via the `extensions.webapi.testing` flag. Closing this then.
