### ISSUE TITLE
[L10n] Overlay issue for Complete Themes section in Themes drop-down

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4138]
Steps to reproduce:
1. Load AMO homepage 
2. Change the language to "French" https://addons.mozilla.org/fr/firefox/
3. Hover over "Themes" option from the main menu

Expected results:
There are no display issues.

Actual results:
The "Complete themes" section overlays the drop-down border.

Notes/Issues:
Issue is only reproducing if the translated text from the complete themes section is displayed on 2 rows.
Other example: Deutsch, Bulgarian, Portuguese,
Verified on FF50(Win 7). Issue is reproducing all around AMO-servers.
Screenshot: 
![2016-12-13_1525](https://cloud.githubusercontent.com/assets/15685960/21141984/a9eaa614-c148-11e6-8100-b73d291fc6bd.png)

**Comment by wagnerand** [comment]
The triage team decided this is too minor, let's WONTFIX. If anyone else wants to take this anyway, feel free to do so.
