### ISSUE TITLE
[L10n] "Add to collection" link from theme details causes display issues while logged out

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4140]
Steps to reproduce:
1. Load details page for any theme while being logged out 
2. Change the language to Deutsch i.e https://addons.mozilla.org/de/firefox/addon/firefox-v19-by-cp/
3. Click the "Add to collection" link

Expected results:
A popup message to _log in_ or _create an account_ first, is displayed without any issues.

Actual results:
The "Create an Add-on Account" button overlays the popup borders. 

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing all around AMO-servers.
Other examples:  
- https://addons.mozilla.org/bg/firefox/addon/firefox-v19-by-cp/
- https://addons.mozilla.org/cs/firefox/addon/firefox-v19-by-cp/
- https://addons.mozilla.org/el/firefox/addon/firefox-v19-by-cp/
etc.
Screenshot for this issue: 
![de](https://cloud.githubusercontent.com/assets/15685960/21142875/d6b28c62-c14c-11e6-8da1-e472fe07171a.png)

**Comment by EnTeQuAk** [comment]
The add-ons detail pages are being reimplemented by addons-frontend so I'm going to close this to not worth fixing I think.
