### ISSUE TITLE
Disco pane fallback buttons styled poorly

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#4141]
### Describe the problem and steps to reproduce it:
Disco pane fallback buttons aren't formatted nicely.

1. Go to discovery pane somewhere `mozAddonManager` isn't available like http://localhost:3000

or:

1. Open a new clean Firefox profile
2. Go in about:config and set disco pane pref to point to -dev (`extensions.webservice.discoverURL` - `https://discovery.addons-dev.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%` )
3. Open about:addons page

### What happened?
Install button fallback is shown and they aren't formatted well.

### What did you expect to happen?
Pretty install fallback buttons.

### Anything else we should know?
![n](https://cloud.githubusercontent.com/assets/15685960/21104308/bb9c39c8-c08e-11e6-9d24-228f43decd38.png)

Extracted from https://github.com/mozilla/addons-server/issues/4136.

**Comment by diox** [comment]
Disco pane bugs should be opened in https://github.com/mozilla/addons-frontend
