### ISSUE TITLE
Rating stars are not preserved at edit review

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4144]
Steps to reproduce:
1. Log in to AMO-stage  https://addons.allizom.org/en-US/firefox/
2. Go tho any extension details page i.e. https://addons.allizom.org/en-US/firefox/addon/clearly/reviews/#review-edit-form
3. Write a review 
4. Edit your review

Expected results:
The rating stars selected while the review was submitted are displayed.

Actual results:
The ratings stars are not preserved.

Notes/Issues:
Issue is also reproducing for themes reviews.
Verified on FF50(Win 7). Issue is reproducing all around AMO-servers.
Video for this issue: 
![stars](https://cloud.githubusercontent.com/assets/15685960/21184096/9279e1a4-c213-11e6-9b3c-cb0dab512816.gif)

First logged: https://bugzilla.mozilla.org/show_bug.cgi?id=1214604

**Comment by EnTeQuAk** [comment]
This should maybe happen somewhere in `review_comment_edit_click` in `static/js/impala/reviews.js` near lines 82-85 since this is where the form get's filled in.

**Comment by wagnerand** [comment]
Since we are going to reimplement those pages very soon in the new frontend, we WONTIFX this.
