### ISSUE TITLE
[Request] Please create a separate location/section for Editor/Review Related bugs/issues

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#4146]
### Describe the problem and steps to reproduce it:
Issues related to addon review tools gets mixed with (buried in) issues related to general AMO usage.
It would be beneficial to have a separate section for the tools/issues related merely to reviewing and reviewers/editors.

**Comment by muffinresearch** [comment]
We have a label `reviewer tools` that should be used to flag reviewer tools issues as specific to that area.

**Comment by erosman** [comment]
I haven't seen it used ... it still get buried though
Example: https://github.com/mozilla/addons-server/issues/3579

**Comment by muffinresearch** [comment]
I'm not sure what precisely qualifies something as buried in this case - #3579 is being investigated currently having only been reopened recently. I don't think a separate project would necessarily alleviate the  sense of issues getting "buried" though.

@wagnerand has set up a tracker bug to cover the highest priority reviewer tools issues here: https://github.com/mozilla/addons/issues/282 we'll be looking at those in priority order in q1 next year. As I commented there, any time spent to provide specific examples and the expected output for the validation related issues will help those get fixed quicker. 

One thing that might help is if there's a regular review of the "reviewer tools" issue label too to make sure any important issues aren't falling throught the cracks, and that we are prioritising issues effectively (this is definitely an area we can improve on), I'll suggest that to Andreas.

**Comment by erosman** [comment]
Thank you @muffinresearch 

By buried..... for example, I refer to a number of bugs, some filed over a year ago and still outstanding.
I actually have been writing scripts myself to overcome these bugs (where possible).

The fact that they (review related) are divided into separate branches doesn't help either.

mozilla/addons-server
mozilla/amo-validator
mozilla/addons-linter

**Comment by muffinresearch** [comment]
We do have the mozilla/addons repo which is supposed to be the umbrella project. Filing bugs there might be useful if you feel an issue covers more than one area or if it's not clear what engineering project is the relevant one. 

I'm definitely keen to see us improve our handling of the issues that impact reviewers so please do keep filing bugs for new things and feel free to let me know if you feel there's anything we're overlooking. Prioritisation is definitely something that's harder to do in github, but we've already been looking at using priority labels to help with that along with more regular review of high priority issues.

We have a lot of important goals to work on next year, and working on one thing means there's something else we don't, so we'll be looking to aim for fixing the bugs that will have the highest impact first. Feel free to make the case for any issues that you feel would make a big impact for reviewers as that will help us with prioritization.

**Comment by erosman** [comment]
Thank you. I shall :)
