### ISSUE TITLE
Fileviewer highlighting breaks with certain regexes

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#4147]
### Describe the problem and steps to reproduce it:
Visit https://addons.mozilla.org/en-US/firefox/files/browse/546862/file/data/content_script/youtube.js#L286

### What happened?
Unnecessarily escaped " causes highlighting to break (using `/\"video_id\":\s*\"([^\"]+)\"/`)

### What did you expect to happen?
Correct Highlighting

**Comment by kewisch** [comment]
Similar regex issues here: https://addons.mozilla.org/en-US/firefox/files/browse/547010/file/bitport.js#L5

**Comment by muffinresearch** [comment]
There's been a bunch of issues recently with the syntax highlighting code and when @wagnerand looked at it recently it became clear that the way it works is fundamentally flawed. Some patches were applied to attempt to fix that but quote matching had some issues which required additional patches and this sounds like a related problem.

There's a complication with the diffing but the first thing that should be looked at is seeing if highlight.js can wholesale replace the current syntax highlighting. If the diffing parts will work applied separately that might be a viable alternative to continuing to hack the minimally maintained lib we're currently using.

**Comment by EnTeQuAk** [comment]
Linking this to https://github.com/mozilla/addons-server/issues/4149 for better issue tracking.

**Comment by muffinresearch** [comment]
We're looking into a complete replacement here via https://github.com/mozilla/addons-server/issues/7171
