### ISSUE TITLE
File viewer comparison marks file as deleted which wasn't actually deleted

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#4148]
### Describe the problem and steps to reproduce it:
Visit https://addons.mozilla.org/en-US/firefox/files/compare/547391...460553/file/lib/robinson.js#top

### What happened?
* The file says "That file no longer exists" in the footer and all lines are marked with minus.
* The file size is correctly shown in the footer, 4.3KiB
* Downloading the xpi shows the file still exists and there are two lines different between 1.0.7 and 1.1.0

### What did you expect to happen?
* Show correct diff

**Comment by muffinresearch** [comment]
I've filed https://github.com/mozilla/addons-server/issues/4149 to investigate a replacement.

**Comment by diox** [comment]
@EnTeQuAk says it's a dupe of another fileviewer bug.

**Comment by wagnerand** [comment]
Can we link to the other fileviewer bug, then?

**Comment by EnTeQuAk** [comment]
i was sure there was one, I'm marking this as `triaged` since I can't find the other one and this is apparently still a problem some times.

**Comment by muffinresearch** [comment]
Associating this with https://github.com/mozilla/addons-server/issues/7171 and since we're unlikely to fix this without the complete replacement I'm going to wontfix this one.
