### ISSUE TITLE
Reviews > 7 days don't gives up bonus points

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#4150]
### Describe the problem and steps to reproduce it:
Reading https://wiki.mozilla.org/Add-ons/Reviewers/Points_and_Incentives shows that "For add-on submissions waiting over 7 days, 2 points are added for every day that exceeds the 7 day mark."

Unfortunately this is not the case anymore. It would seem reviews I did in the past weeks gave the "normal" amount of points. I'm not sure if this issue arise all the time as I don't really look at the points system most of the time.

### What happened?
Doing a review on December 15th 2016 for https://addons.mozilla.org/en-US/editors/review/super-twitter-auto-reresh Version 1.0.0 (November 29, 2016) should have given up more than 80 points. It however gave me 80 points

### What did you expect to happen?
The review should have giving up around 90 points.

### Anything else we should know?
The issue is probably around addons-server-master\src\olympia\editors\models.py#425

Erosman was able to reproduce this issue as well. 

While this is not really important for top reviewers, this could greatly affect reviewers with low levels trying to level++ their way up.

**Comment by erosman** [comment]
Confirmed... I reviewed 4 addons in a row (Full Review) that were 15 days old and the additional incentive were not given.

**Comment by diox** [comment]
Has it ever worked ? 

From looking at the code, When `ReviewerScore.award_points()` is called, the addon is already public, so when it tries to find out the waiting time using the queue, it fails to find it and never awards the bonus points.

I guess the fix would be to pass the `version` as well, and just check `version.nomination` difference with the current date to find if it's old enough to warrant bonus points.

**Comment by spoji** [comment]
It work, a while ago. It was forking for sure when I started reviewing add-ons in mid 2015.

**Comment by vcarciu** [comment]
Bonus points are now given for review > 7 days : 
![bonuspoints](https://cloud.githubusercontent.com/assets/1583842/25128407/543358da-2442-11e7-9046-270e4ada1ec5.gif)
