### ISSUE TITLE
Confusing text: Be careful with old versions! ... You should always use the latest version of an add-on.

### ISSUE THREAD

**Issue by peter-kehl** [mozilla/addons-server#4157]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0
Build ID: 20160111185352

Steps to reproduce:

1. Submit a new version of an existing XPI.
2. Visit the addon's  webpage - e.g. https://addons.mozilla.org/en-US/firefox/addon/selite-run-all-favorites/. Until someone at AMO reviews the new version, this page shows the last reviewed version - OK.
3. Follow link 'See complete version history' (in this case  https://addons.mozilla.org/en-US/firefox/addon/selite-run-all-favorites/versions/). That lists previous versions, the current reviewed version, and the new version (not reviewed yet).

This page has the following text above the listing of versions:

"Be careful with old versions!

These versions are displayed for reference and testing purposes. You should always use the latest version of an add-on."

Where 'latest version' is to the add-on's main page (e.g. https://addons.mozilla.org/en-US/firefox/addon/selite-run-all-favorites/).

That text is a problem. That 'latest version' is not the latest version - since it's older than the (unreviewed) version shown at the top of versions listing. Developers point to these  https://addons.mozilla.org/en-US/firefox/addon/XXX/versions/ pages specifically so that users can download the very newest versions, even before they get reviewed. However, this text confuses the user.

If you take users away from this page, then what's the purpose of the page....

Suggested changes:

OLD: Be careful with old versions!
NEW: Be careful with old or new unreviewed versions!

OLD: You should always use the latest version of an add-on.
NEW: You should always use the latest reviewed version of an add-on, unless you specifically want a different version.

(Copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1239898.)

**Comment by diox** [comment]
Yes, it's mostly a wording issue - though in the future we're likely to remove unreviewed versions from this page completely.

**Comment by wagnerand** [comment]
Yes, I'd like to close this in favor of https://github.com/mozilla/addons-server/issues/3704.
