### ISSUE TITLE
New file is removed if no platform is selected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4160]
Steps to reproduce:
1. Add a new file for an already submitted add-on on AMO-dev i.e. https://addons-dev.allizom.org/en-US/developers/addon/idmatch-dev/versions
2. Select the new file but no platform

Expected results:
A message is displayed saying that a platform must be chosen. The selected file is not removed.

Actual results:
The selected file is removed.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing in AMO-stage and dev. 
It is also reproduced for new versions or new submission.
Issue is not reproducing for the old submission flow (the new add-on submission scenario is not very disturbing, because, `all platform` option is selected by default and the case is rarely achieved).
Video for this issue:
![fileremoved](https://cloud.githubusercontent.com/assets/15685960/21343294/b129b248-c69e-11e6-8127-d5edc4cae5ef.gif)

**Comment by eviljeff** [comment]
maybe we can pick this up with #4868

**Comment by EnTeQuAk** [comment]
This is imho the same / very similar issue to https://github.com/mozilla/addons-server/issues/3999 :thinking:
