### ISSUE TITLE
Validator failed to provide a valid rejection on search engine without a valid <shortname>

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#4162]
### Describe the problem and steps to reproduce it:
Uploading a search engine XML file with an empty ShortName value will result to a bad behavior for the developer where he/she can't figure out what to fix to continue uploading to AMO.

### What happened?
Uploading the following XML :
[gists.zip](https://github.com/mozilla/addons-server/files/663875/gists.zip)

Will result with the following message 
"Your add-on failed validation with 1 error. Could not parse uploaded file."

The XML can be parsed as it's valid XML. However, the validator doesn't show any valid error for the user to fix his/her issue :
https://addons.mozilla.org/en-US/developers/upload/fcd799b5314c47308ca8b2b2b11dac01

### What did you expect to happen?
The validator should warn the developer that ShortName must not be empty.

### Anything else we should know?
I'm Spoji on IRC under #amo-editors if you got any questions regarding this bug. A developer called Jan\
needed help regarding this issue and I filled a bug for him/her.

**Comment by wagnerand** [comment]
Yeah, in `files/utils.py::parse_search` we fail with a generic error message if something goes wrong in `extract_search`.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF52(Win 7) for 2 cases: empty `shortname` and missing `shortname`.
First case returned:
![shortname](https://cloud.githubusercontent.com/assets/15685960/24246191/dd009ac0-0fce-11e7-833a-7a5002b08713.png)

Second case returned:
![noshortname](https://cloud.githubusercontent.com/assets/15685960/24246200/e7ad9220-0fce-11e7-9c2a-09acf9390a80.png)

@EnTeQuAk : Should we handle the second case better - lets say one message instead or two - or this is ok?
