### ISSUE TITLE
Error while opening "Have an account? Sign in" in a new tab

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4163]
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/ being logged out
2. Click the "Register" link
3. In the FxA page open the "Have an account? Sign in" link in a new tab

Expected results:
User is redirected to sign in.

Actual results:
An error is displayed.

Notes/Issues:
- Issue is not reproducing while making the same steps from Sync. (about:accounts?action=signup&entrypoint=menupanel)
- Reproducing also vice versa - click "Log in" and open "Create an account" link in a new tab.
Issue is reproducing all around AMO-servers.
Video for this issue: 
![badreq](https://cloud.githubusercontent.com/assets/15685960/21384550/afdc45c4-c773-11e6-8c35-7f2635974c37.gif)

**Comment by andymckay** [comment]
Errors on Firefox Accounts pages should be filed against the Firefox Accounts repositories. I imagine this is just a temporary problem with the Firefox Accounts stage server though. Pinging @rfk for more.

**Comment by rfk** [comment]
I can't repro this, it may have been a transient error on the FxA dev server.  I'll ask some other FxA devs to weigh in if they have any theories.

**Comment by rfk** [comment]
Alternately, this could be something specific to your local browsing session; @ValentinaPC let me know if you can still reproduce this, and I'll migrate it to an issue in https://github.com/mozilla/fxa-content-server/ which is almost certainly where the bug will be.

**Comment by ValentinaPC** [comment]
@andymckay - I logged this here, because I could not reproduce it via Sync - FxA - and I thought is not entirely FxA related.

@rfk - I've tried again today, with a new  clean Firefox profile and was able to reproduce it.

**Comment by andymckay** [comment]
@rfk I can reproduce it following @ValentinaPC steps on prod: https://www.dropbox.com/s/72u86hc12dxi7pr/fxa-login-error.mov?dl=0

**Comment by rfk** [comment]
> in a new tab

Aha, I had somehow missed this part in the STR.  Thanks, I will migrate this to fxa-content-server for further discussion.

>  could not reproduce it via Sync

FWIW I expect you wouldn't be able to login to sync via this process either, but we probably just fail to show an error message :-/

**Comment by rfk** [comment]
Moved to https://github.com/mozilla/fxa-content-server/issues/4547
