### ISSUE TITLE
The "Install anyway" popup is display on top of the contribution popup

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4164]
Steps to reproduce:
1. Load contribute roadblock page for an add-on incompatible with your Firefox version i.e. https://addons-dev.allizom.org/en-US/firefox/addon/faroese-spell-checker-faroe-is/contribute/roadblock/?src=dp-btn-primary&version=2.0
2. Click on "Add to Firefox" gray button
3. Click on "Contribute" blue button

Expected results:
The "Install anyway" popup is dismissed.

Actual results:
The "Install anyway" popup is display on top of the contribution popup.

Notes/Issues:
Verified on AMO-dev FF50(Win 7).
Screenshot for this issue: 
![2016-12-21_1615](https://cloud.githubusercontent.com/assets/15685960/21392475/b540a45e-c798-11e6-913c-bb9dd4fe8167.png)

**Comment by EnTeQuAk** [comment]
All this get's reimplemented sooner or later in addons-frontend and it feels like an edge-case. I'll close this in favor of not wasting time on it.

Please feel free to re-open anytime though.
