### ISSUE TITLE
Top Reviewers(past 7 days) section is not populated on -dev after approving a recently submitted add-on

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4166]
Steps to reproduce:
1.Submit a new add-on
2.Approve it from editor tools (https://addons-dev.allizom.org/en-US/editors/queue/new)

Expected results:
Top Reviewers(past 7 days) section is updated 

Actual results:
Top Reviewers(past 7 days) section is not populated  at all

Please see photo of this issue:
![toprew](https://cloud.githubusercontent.com/assets/1583842/21430371/a8972f1a-c86b-11e6-9e68-0383c97d03d3.png)

NOTES : 
Not reproducible on STAGE

**Comment by eviljeff** [comment]
Top reviewers excludes any user who is in the 'Staff', 'Admins' or 'No Reviewer Incentives' groups so if all of the people reviewing in the past week are in those groups (possible because we tend to give ourselves super powers to make QA easier) then it will be empty.

**Comment by EnTeQuAk** [comment]
given @eviljeff's answer I think this is not an actual issue. Please feel free to re-open anytime if I'm wrong.
