### ISSUE TITLE
an incomplete addon causes a redirect loop

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#4167]
If an add-on has all STATUS_DISABLED (e.g. rejected) versions and is STATUS_NULL (Incomplete) then any attempt to access it's devhub edit pages gets stuck in a redirect loop from `/submit/details/` to `/submit/finish/'.

I think this is a regression from https://github.com/mozilla/addons-server/pull/4073, in particular the changes to how [`has_required_metadata`](https://github.com/mozilla/addons-server/pull/4073/files#diff-d5d4f5e227c5a588706b9e9f6879197eR1260) works.

**Comment by eviljeff** [comment]
Okay, so fortunately these are only add-ons that are missing a license for their latest version. Unfortunately this may be ~5000 add-ons.  Even with a missing license there shouldn't be a redirect loop.

**Comment by jvillalobos** [comment]
The ones that qualify for this bug are closer to 1000, and only a few dozen updated somewhat recently. Given that we aren't hearing tons of complaints about it, I suppose we better wait for the first January push to fix this.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF50.1(Win 7)
I've submitted a new add-on and made the following actions on it:
- rejected - Incomplete status
- disabled - Incomplete status
- deleted (its version) - no status
And I accessed its _devhub edit page_ from Editor Tools or from My Submission with success.
@eviljeff : Please let me know if any additional check is required. Thank you!

**Comment by eviljeff** [comment]
@ValentinaPC if you can find an old add-on with a missing license, that would be an ideal add-on to reject and put in the incomplete status, but they're difficult to find, and (should be) impossible to recreate now.  So if you can't find one, then nothing more to do.

**Comment by ValentinaPC** [comment]
Through my add-ons I found only **unlisted** ones without `license` and I was able to disable them and access the edit info devhub page with success.... but no **listed** - `without license`  add-ons with **incomplete** status into my "history chest" :(
