### ISSUE TITLE
Unable to see review notes in devhub

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4169]
### Describe the problem and steps to reproduce it:
1. Go to the _Manage Status and Versions_ page of an add-on in the devhub.
2. Click _Review History_ for a reviewed version.

### What happened?

We had a problem retrieving review notes
/api/v3/addons/addon/670489/versions/1954013/reviewnotes/, UNAUTHORIZED, {"detail":"Ungültiger Autorisierungs-Header. Keine Daten angegeben."}

### What did you expect to happen?

Review notes should be displayed.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
might be a dupe of https://github.com/mozilla/addons-server/issues/4126 ?

**Comment by wagnerand** [comment]
Right. Thanks.
