### ISSUE TITLE
remove (hidden) devhub breadcrumbs code

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#4173]
All the devhub pages have a breadcrumbs line, just under the navigation bar.  But it's hidden with a css rule in restyle.less (inadvertently?).  We should either tinker with the css rules to show it again or remove the code entirely.
![screenshot 2016-12-23 18 59 17](https://cloud.githubusercontent.com/assets/768592/21460620/459b3cbc-c942-11e6-8bbe-99c4e9241d83.png)
Note for most of the devhub pages it's redundant because there's a navigation box on the left.  Arguably during addon submission it's fairly redundant too as you can click the 'MY ADD-ONS' link above.  The only place it's potentially useful is during version/file submission where there isn't an escape hatch back to the addon you're adding a version/file to.  Also, it looks a bit ugly as it is now.

**Comment by jvillalobos** [comment]
Since it's been hidden for a long time, I don't think there's any harm in getting rid of it. Any navigational changes should come as part of a larger devhub redesign.

**Comment by eviljeff** [comment]
Okay, lets remove the code then.

**Comment by atiqueahmedziad** [comment]
`breadcumbs` are also available almost in every pages of addons website. It's look weird in addons-detail page- 
![screenshot from 2016-12-31 20-51-07](https://cloud.githubusercontent.com/assets/8364578/21578016/e29be800-cf9a-11e6-9980-a6205ef07758.png)
So, should we remove them from everywhere in AMO?

**Comment by jvillalobos** [comment]
If they're all hidden, it should be okay to remove those too (in a separate issue). Just be careful not to remove something we're actually using ;)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev and -prod using FF50.1(Win 7).
No hidden breadcrumbs were discovered all around Dev Hub pages.
![breadcrumbs](https://cloud.githubusercontent.com/assets/15685960/21847089/b7a27e1e-d802-11e6-9de4-07981b3681cb.png)
