### ISSUE TITLE
kaspersky password manager does not work

### ISSUE THREAD

**Issue by bern21** [mozilla/addons-server#4175]
### Describe the problem and steps to reproduce it:
Kaspersky password manager does not work.  I just installed the latest Kaspersky Password Manager which should fill in passwords when I go to a site that I have stored a password.  However, it will not work.  The version is PW manager BETA.

### What happened?
The passwords will not fill in.  Before I installed this PW manager, the passwords would fill in via Firefox.
### What did you expect to happen?
I expected the extension to install and work correctly.  Kaspersky said that it should install and work with Firefox.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Yes - HOW DO I GET THIS TO WORK?

**Comment by tofumatt** [comment]
Sorry for the confusion but this is the bug reporter for the add-ons site itself, but your issue is with a particular add-on made by a third-party developer.

In this case you'll need to contact Kaspersky's support: http://support.kaspersky.com/

Sorry about your add-on not working. ☹️
