### ISSUE TITLE
Kabyle locale on AMO staging and production server

### ISSUE THREAD

**Issue by belkacem77** [mozilla/addons-server#4179]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
We are translating AMO on Pontoon into Kabyle language and we would like get it activated on staging and production server
### What happened?
No kab location on AMO 

### What did you expect to happen?
Select kab locale in AMO
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Next 7th January 2017, i will give a speech in Tizi-ouzou Algeria on Opensources solutions and tools.
I'am also going to talka about AMO and extension development. If i could get kab locale activated on AMO before 07 January, it will be better for me to give a short training for attendees.

**Comment by tofumatt** [comment]
Our next push is on https://public.etherpad-mozilla.org/p/amo-2017.01.05 so if the `kab` locales are ready then we should be able to enable them.

Have they been recently added?

**Comment by belkacem77** [comment]
We started the localization months ago. The kab locale is not enabled on amo staging Web site.
Sorry, the date of my speech and short training about mozilla addons dev will be on 7th January not 1st January.

**Comment by tofumatt** [comment]
Thanks for the info. A lot of the team are off for holidays right now, but if the locale is ready we hopefully should be able to enable it in time for your speech. I'll check on it and try to get it in the next deploy.

**Comment by belkacem77** [comment]
Thanks for support. We are now about 49 of job done on kab translation. The localization is going on.

**Comment by tofumatt** [comment]
I'm blocked fixing this while my Docker image is messed up (#4186).

I'm sorry but I don't think we'll be able to get this out; the holidays meant we were mostly offline and it's short notice. Really sorry! 😞

**Comment by EnTeQuAk** [comment]
I can take a look at this after our tag today - this way we'll have it on our development server soon and you will have time till the next tag to make sure everything is properly translated.

**Comment by belkacem77** [comment]
Hi, 
Our localization (kab) reached 71%. Is there a chance to get it enabled on staging site before 07/01?

**Comment by EnTeQuAk** [comment]
I'm looking into this. Short side note regarding the error @tofumatt saw - it helps updating the product details: `manage.py update_product_details`

**Comment by EnTeQuAk** [comment]
This should be landing on http://addons-dev.allizom.org/ momentarily. Happy testing! :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50.1(Win 7)
The `kab` locale was added and work as expected.
Postfix screenshots: 
![footer](https://cloud.githubusercontent.com/assets/15685960/21718516/ad4f939c-d420-11e6-8228-834e688d1102.png)
![url](https://cloud.githubusercontent.com/assets/15685960/21718515/ad4e946a-d420-11e6-9934-a0d4a4755df3.png)
