### ISSUE TITLE
API requests with bad type params should error but don't

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4181]
### Describe the problem and steps to reproduce it:
(@mstriemer found this)
Using the new React front-end, go to different category results pages (eg https://addons-dev.allizom.org/en-US/android/extensions/security-privacy/ and https://addons-dev.allizom.org/en-US/android/extensions/feeds-news-blogging/ with the MAMO cookie set)

### What happened?

The results from the API are the same even though they should be varied. The params sent are different.

### What did you expect to happen?

The result sets should be different across categories.

### Anything else we should know?

The actual search API requests are:

* https://addons-dev.allizom.org/api/v3/addons/search/?app=android&category=security-privacy&type=extensions&page=1&lang=en-US
* https://addons-dev.allizom.org/api/v3/addons/search/?app=android&category=feeds-news-blogging&type=extensions&page=1&lang=en-US

**Comment by diox** [comment]
The `type` parameter is wrong, it should be `extension` singular. http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-type

**Comment by tofumatt** [comment]
Omg you're right, how did I miss that. Thanks!

- tofumatt

**Comment by diox** [comment]
I don't quite remember where I left things with the handling of wrong parameters but I suppose it should generate a 400 error, so it's worth keeping this issue opened, re-purposing it to deal with that.

**Comment by tofumatt** [comment]
Agreed, it would have been handier to get an error/warning than results.
Thanks!

**Comment by diox** [comment]
The API should now return 400 errors when an invalid parameter is specified. Let me know how it goes!
