### ISSUE TITLE
Code coverage tests are failing on Travis

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4183]
### Describe the problem and steps to reproduce it:
Send a pull request that will run code coverage on Travis.

### What happened?
The build failed.

### What did you expect to happen?
The build shouldn't fail.

### Anything else we should know?
This is a known issue, but I wanted to file here so others weren't thrown off by it. Seems there isn't an obvious fix. 😢

**Comment by muffinresearch** [comment]
I'm not sure what the upstream issue was but I don't think this is still an issue. Please re-open if it is.
