### ISSUE TITLE
"JSON Web Token (JWT)" titles have layout issues for other languages in Manage API Keys page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4191]
Steps to reproduce:
1. Load https://addons.mozilla.org/en-US/developers/addon/api/key/
2. Change the language to i.e. French (https://addons.mozilla.org/fr/developers/addon/api/key/)

Expected results:
There are no display or layout issues.

Actual results:
The "JSON Web Token (JWT)" titles have layout issues.

Notes/Issues:
Verified on AMO-prod using FF50.1(Win 7)
Screenshot for this issue: 
![2017-01-03_1602](https://cloud.githubusercontent.com/assets/15685960/21609976/0f634cb8-d1ce-11e6-8a8a-3a6e6199f20c.png)
Other examples:
- https://addons.mozilla.org/de/developers/addon/api/key/
- https://addons.mozilla.org/cs/developers/addon/api/key/
- https://addons.mozilla.org/it/developers/addon/api/key/
- https://addons.mozilla.org/ru/developers/addon/api/key/
- etc.

**Comment by wagnerand** [comment]
The mentor for this bug is: @tofumatt 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by totaki** [comment]
I find this problem and suggested three solves:
1. Increase width % on this label. 
![2017-02-09 20-13-48](https://cloud.githubusercontent.com/assets/6254062/22794581/110c3820-ef0d-11e6-9c29-e1ffe59ba087.png)
2. Disabled float
![2017-02-09 20-14-34](https://cloud.githubusercontent.com/assets/6254062/22794618/351dfa3c-ef0d-11e6-95ba-0542c0d45b7b.png)
3. Hardcode height for first row
![2017-02-09 20-22-38](https://cloud.githubusercontent.com/assets/6254062/22794867/f96b624e-ef0d-11e6-8911-9511d2a3dfed.png)

**Comment by tofumatt** [comment]
Disabling the floats is the most future-proof solution, as if the labels get longer again we'd have the same issue wit the first solution, and the third solution is a bit ugly.

Plus the second option means you can see the entire API key.

Let's go with option 2.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7)
Postfix screenshot:
![it](https://cloud.githubusercontent.com/assets/15685960/23121574/9dbdecb4-f769-11e6-9ab2-03ba008c372a.png)
