### ISSUE TITLE
chrome registration failed by incorrect manifest.mf file

### ISSUE THREAD

**Issue by gomita** [mozilla/addons-server#4192]
### Describe the problem and steps to reproduce it:
1. Upload new version of a XUL-based extension to AMO
2. Install the new version from AMO

### What happened?
After a Firefox restart, the new version of extension installed successfully.
However, it seems that chrome registration failed.
For example, after installing the latest beta version of my FireGestures add-on from the following URL:
https://addons.mozilla.org/en-US/firefox/addon/firegestures/versions/?page=1#version-1.11b1
I cannot access the chrome URL: `chrome://firegestures/content/browser.js`

### What did you expect to happen?
I can access the chrome URL: `chrome://firegestures/content/browser.js`

### Anything else we should know?
I found that the auto-generated `META-INF/manifest.mf` file in the XPI has a small difference with one of previous version.

In firegestures-1.11b1-fx.xpi (uses backslashes)
```
Name: chrome/content\firegestures\browser.js
Digest-Algorithms: MD5 SHA1
MD5-Digest: FqgJKLEKb+lJOKgNOU9hxg==
SHA1-Digest: LC/u7AycjpF1bulf+/cHJeHKwA8=
```
In firegestures-1.10.13-fx.xpi (uses slashes)
```
Name: chrome/content/firegestures/browser.js
Digest-Algorithms: MD5 SHA1
MD5-Digest: peTIb/Ne1W5BavipignMOw==
SHA1-Digest: xt5kKHqIFFHiFJ1tK3BPSSoBIKU=
```

**Comment by jvillalobos** [comment]
I can confirm that the `chrome` path only works in the non-beta version, and I also see the slash and backslash weirdness in the manifest. However, signature verification shouldn't have any effect in chrome registration. If the signature fails, the add-on shouldn't be loaded at all.

Were the beta and non-beta versions built in the same system, using the same tools? I'm wondering if the signing tool is just taking paths from the zip and that's the reason behind the slashes and possible the chrome registration failure.

**Comment by gomita** [comment]
Thanks Jorge.
I found that the slash and backslash weirdness happened before updating to AMO.
I'm using 7-Zip to make XPI but something might have changed in upgrading Windows 8 to 10.
Anyway, it's not a bug with AMO.

**Comment by gomita** [comment]
I just have been solved the problem.
When I use nsIZipWriter.addEntryDirectory to make XPI, `|path|.replace("\\", "/", "g")` does not work after I updated Firefox to 50.1.0.
I changed it to `|path|.replace(/\\/g, "/")` and everything works fine.
