### ISSUE TITLE
Disco Pane content update - Jan. 2017

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#4198]
For the **19 January** push, can we please REMOVE:

- Awesome Screenshot Plus
- All three themes (Ice Flower, Les Éléphants, Owl First Snow)

... and REPLACE them with Emoji Keyboard and three new themes, respectively (note full copy included):

**Emoji expression** 
with [Emoji Keyboard by Harry N.](https://addons.mozilla.org/firefox/addon/emojikeyboard/)
Dozens of amazing emojis for every occasion—always just one click away. 

[themes]

Symphony of Colors by [rositza212](https://addons.mozilla.org/firefox/addon/symphony-of-colors/)

Stained Glass Fractal by [Guitarzan](https://addons.mozilla.org/firefox/addon/stained-glass-fractal/)

Blue Twirl by [RLC ♥†](https://addons.mozilla.org/firefox/addon/blue-twirl/)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF50(Win 7)
Postfix screenshot:
![discopane](https://cloud.githubusercontent.com/assets/15685960/22141525/188d865c-defb-11e6-90e9-70d723ec4180.png)
