### ISSUE TITLE
[DevHub Landing Desktop] Add port chrome ext block

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4206]
Looks like this in the mocks:

<img width="639" alt="d94a454a-aca8-11e6-852f-92284eda5db0_png__png_image__1280 x 2850_pixels_" src="https://cloud.githubusercontent.com/assets/1514/21643974/092c82fa-d283-11e6-87b6-3adba82a7225.png">

<img width="180" alt="710ffb0e-aca9-11e6-8eeb-6a75df8e0da2_png__png_image__320 x 2860_pixels_" src="https://cloud.githubusercontent.com/assets/1514/21643980/0ff83e30-d283-11e6-9871-c51083962a37.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7)
The picture, while being small, does not look exactly as it is in your mocks, but I thinks is ok. Please let me know if is not.
Postfix video: 
![port](https://cloud.githubusercontent.com/assets/15685960/22335627/1b2fb8e8-e3e8-11e6-88ea-bbe1e963d98d.gif)
