### ISSUE TITLE
[DevHub Landing] Publish your add-on content block

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4208]
Looks like this in the mocks

<img width="640" alt="d94a454a-aca8-11e6-852f-92284eda5db0_png__png_image__1280 x 2850_pixels_" src="https://cloud.githubusercontent.com/assets/1514/21644357/03b38790-d285-11e6-9fa8-a2bb39a8e843.png">

<img width="180" alt="710ffb0e-aca9-11e6-8eeb-6a75df8e0da2_png__png_image__320 x 2860_pixels_" src="https://cloud.githubusercontent.com/assets/1514/21644364/0c91ae3c-d285-11e6-8721-1cdbac15ef9a.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7)
Postfix video: 
![side](https://cloud.githubusercontent.com/assets/15685960/22335316/ea8bd39e-e3e6-11e6-8605-e41d2d804b41.gif)
