### ISSUE TITLE
[l18n]"Continue to download" button breaks the layout for featured add-ons section at hover

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4209]
Steps to reproduce:
1. Load AMO-stage homepage and change the language to French https://addons.allizom.org/fr/firefox/
2. Go to an add-on category (https://addons.allizom.org/fr/firefox/extensions/language-support/) that has an add-on with "Continue to download" button and hover over

Expected results:
There are no display or layout issues.

Actual results:
The add-on with "Continue to download" button is causing layout issues.

Notes/Issues:
Reproducing all around AMO servers.
I think is because of the length of the button label.
Verified on FF50.1(Win 7 x64).
Screenshot for this issue: 
![fr](https://cloud.githubusercontent.com/assets/15685960/21644484/5988e884-d296-11e6-85e9-9b3f950d3bb5.png)

**Comment by wagnerand** [comment]
The mentor for this bug is: @tofumatt 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by totaki** [comment]
You was right, it because final width button more than parent width. First simple changes at more shorted message :). More difficult solution from change CSS.

**Comment by tsl143** [comment]
@ValentinaPC Does this still exist?

<img width="699" alt="screen shot 2017-07-20 at 3 52 39 pm" src="https://user-images.githubusercontent.com/5318732/28413001-96f664ea-6d63-11e7-9583-bd9503e1e677.png">

**Comment by ValentinaPC** [comment]
@tsl143 : Yes. But, you have to have an add-on that has a "Continue to download" button instead of an "Add to Firefox" as we can see in your screenshot.
Please access https://addons.allizom.org/fr/firefox/extensions/language-support/ and hover over "gtranslate" add-on.
Screenshot:
![fr](https://user-images.githubusercontent.com/15685960/28414450-60c36580-6d54-11e7-82ba-2066c521209a.png)

Thanks for your reply!

**Comment by tsl143** [comment]
Got it,
thanks for clarification :)

**Comment by ValentinaPC** [comment]
Anytime!

**Comment by tsl143** [comment]
This issue also replicates with `Download` button on chrome and other browsers.
<img width="908" alt="screen shot 2017-08-21 at 6 19 26 pm" src="https://user-images.githubusercontent.com/5318732/29520473-cd1dd11c-869e-11e7-8725-c7afcd3c98b6.png">

<img width="892" alt="screen shot 2017-08-21 at 6 19 05 pm" src="https://user-images.githubusercontent.com/5318732/29520464-c208c6e2-869e-11e7-86c9-6af99109ba66.png">

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
