### ISSUE TITLE
Beta-channel tooltip from beta-version submission step is not aligned

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4217]
Steps to reproduce:
1. Submit a new beta version for an add-on in AMO-dev i.e https://addons-dev.allizom.org/en-US/developers/addon/test-add-on-dev-1/versions/submit/
2. Observe the beta-channel tooltip

Expected results:
There are no display or layout issues.

Actual results:
The tooltip is not aligned. 

Notes/Issues:
Verified on FF50.1(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshot for this issue:
![2017-01-05_1049](https://cloud.githubusercontent.com/assets/15685960/21674150/263ececc-d335-11e6-978e-5d0691c335e7.png)

**Comment by wagnerand** [comment]
The mentor for this bug is: @EnTeQuAk 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by ValentinaPC** [comment]
This was fixed meanwhile <3
Verified as fixed on AMO-dev FF51(Win 7).
Postfix screenshot: 
![betachannel](https://cloud.githubusercontent.com/assets/15685960/22458012/43e7eaa8-e7a3-11e6-90a0-28cb03f81b5d.png)
