### ISSUE TITLE
Different format for beta versions used in Add-ons and WebExtensions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4220]
Steps to reproduce:
1. Submit a beta version for an add-on i.e. https://addons-dev.allizom.org/en-US/developers/addon/test-add-on-dev-1/versions (_Version 4.b1_)
2. Submit a beta version, using the same format` x.by` for a webextension i.e https://addons-dev.allizom.org/en-US/developers/addon/webext-version-%E6%97%A5%E6%9C%AC%E8%AA%9E/versions

Expected results:
Same format is accepted for both add-ons and webextensions.

Actual results:
The beta version, in the format mentioned at step 2, is not accepted. The version format `x.yb` is accepted for beta webextensions.

Notes/Issues:
- Chrome webextensions don't have in their `version` field the letter "b" for beta webextensions.
- the format `x.y.z-beta` used for chrome webextension in version_name field is also not accepted for webextension, but works for add-ons.
Verified on AMO-dev FF50.1(Win 7)
Screenshots for this issue:
![add-on](https://cloud.githubusercontent.com/assets/15685960/21677516/352f2b62-d343-11e6-94c4-cff75b4ff1d2.png)
![webext](https://cloud.githubusercontent.com/assets/15685960/21677517/35303d86-d343-11e6-87fb-69de9559e819.png)

**Comment by EnTeQuAk** [comment]
This never worked for WebExtensions and got introduced in https://github.com/muffinresearch/web-extension-manifest-schema/commit/5f3392a5f4e23e95bdcc251b5592abeb50acab19 - I wonder where that format was coming from as the manifest in the mozilla hg repository doesn't specify this format and I'm guessing firefox works fine with whatever regular add-ons do.

The version pattern in amo-validator is `^[-+*.\w]{,32}$'` so there's a clear difference. Does anyone have something against changing the format? cc @muffinresearch @jvillalobos

**Comment by muffinresearch** [comment]
At the point that was added to the schema was being based on our limited docs and/or whatever chrome was doing for versions at the time if there wasn't enough data in our own docs to go on. Looking at the string for the error I suspect this was more based on chrome's implementation at that point in time.

Looks like the schema in moz-central is just asking for a string if I'm looking at the right thing https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/schemas/manifest.json#68 - That seems very permissive - and we should check if there's any further validation that should be taken into account if we're going to change this.

**Comment by wagnerand** [comment]
`addons-server` identifies beta versions using https://github.com/mozilla/addons-server/blob/master/src/olympia/constants/base.py#L381

**Comment by muffinresearch** [comment]
One thing to bear in mind if we move to being more permissive for webext versions in the schema, we should at least warn if the version is not compatible with a stricter definition to aid interop if a dev wants to have minimal friction in writing a webext for multiple (web-ext supporting) browsers.

**Comment by wagnerand** [comment]
Another thing to keep in mind is that beta versions are supposed to go away: https://trello.com/c/ynsau1yU/60-beta-versions-on-amo#comment-57f3ce60d04d2baa1bc7a8f2

**Comment by jvillalobos** [comment]
AMO and Firefox should accept the same version string format, and ideally it should match what Chrome does like @muffinresearch points out. @andymckay, can you tell us what Firefox does here?

**Comment by andymckay** [comment]
Judging by: https://developer.mozilla.org/en-US/docs/Toolkit_version_format and https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIVersionComparator it allows a string that is <number-a><string-b><number-c><string-d>, in this case 2.b1 would be invalid. There's some tests here: https://dxr.mozilla.org/mozilla-central/source/xpcom/tests/unit/test_versioncomparator.js. Including the rather interesting version: "3.0.-1".

I think the regex in the schema needs improving.

Also @mstriemer should bear this in mind when he pulls the schema out of Firefox so we don't just end up with "string" as the allowed version.

**Comment by EnTeQuAk** [comment]
Thanks for all the feedback. I'm marking this as `triaged` then, given that there are potentially multiple sources that need sync I'll leave it open here in `addons-server`. That's probably a great idea for the schema-pull project to keep in mind.

**Comment by EnTeQuAk** [comment]
this is being tracked in https://github.com/mozilla/addons-linter/issues/1527, closing this here. most of whats discussed here should be fixed too imho
