### ISSUE TITLE
Webfonts are 404ing on the new landing page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4222]
Probably due to where the import is coming from it's cause the font file refs to be off resulting in 404s for the Fira webfonts.

I'm seeing this locally, I'm assuming running from -dev etc is no different.

<img width="302" alt="developer_tools_-_developer_hub____add-ons_for_firefox_-_http___olympia_dev_en-us_developers_" src="https://cloud.githubusercontent.com/assets/1514/21681201/1cdd29da-d346-11e6-88f5-214f341b4952.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7) (signed in or out)
Postfix screenshots: 
![fonts](https://cloud.githubusercontent.com/assets/15685960/22335062/d3f1a2a4-e3e5-11e6-9251-5a5696d2475c.png)
![signed-out](https://cloud.githubusercontent.com/assets/15685960/22335063/d3f26400-e3e5-11e6-8acb-5ee8fe11478c.png)
