### ISSUE TITLE
[Devhub Landing] Run svg + png optimisations on the static image files.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4223]
Currently all the new images png + svg etc are unoptimised we should run svgo and pngcrush (or whatever) on the images.

Ideally sources could be put to one side, but we can easily extract them from the sketch doc so it's not really a big problem if they are optimized in place.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this. Thanks!
