### ISSUE TITLE
[Devhub Landing] Implement Manage Your Add-on and Evolution block (signed-out)

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4224]
Mocks looks like this:

<img width="633" alt="d94a454a-aca8-11e6-852f-92284eda5db0_png__png_image__1280 x 2850_pixels_" src="https://cloud.githubusercontent.com/assets/1514/21683322/c46a9746-d350-11e6-88a4-13cafd1d9e66.png">

<img width="207" alt="710ffb0e-aca9-11e6-8eeb-6a75df8e0da2_png__png_image__320 x 2860_pixels_" src="https://cloud.githubusercontent.com/assets/1514/21683302/a9054e1a-d350-11e6-93c6-4a9809df28ec.png">

**Comment by ValentinaPC** [comment]
@muffinresearch : this mocks are before the signed out dev hub landing page was modified, yes?
While resizing the page, things seem to look nice, with a small note in what concerns the ladder - not listed for small dimensions - intended?.
Verified this on AMO-dev FF50(Win 7) using Responsive Design Mode.
Please see the screenshots and let me know if there is anything else I should check here:
![1](https://cloud.githubusercontent.com/assets/15685960/22333438/ec3e62cc-e3de-11e6-9049-091033a93b51.png)
![2](https://cloud.githubusercontent.com/assets/15685960/22333444/ef7147d4-e3de-11e6-89c2-db005f525f3f.png)
![3](https://cloud.githubusercontent.com/assets/15685960/22333448/f29fb38c-e3de-11e6-9169-7470b6173354.png)
![5](https://cloud.githubusercontent.com/assets/15685960/22333453/f6fa87cc-e3de-11e6-958b-cf2051156125.png)
![6](https://cloud.githubusercontent.com/assets/15685960/22333457/fb9f86a6-e3de-11e6-9f57-be9d8e91095c.png)

**Comment by muffinresearch** [comment]
> @muffinresearch : this mocks are before the signed out dev hub landing page was modified, yes?
While resizing the page, things seem to look nice, with a small note in what concerns the ladder - not listed for small dimensions - intended?.
Verified this on AMO-dev FF50(Win 7) using Responsive Design Mode.
Please see the screenshots and let me know if there is anything else I should check here:

@ValentinaPC Yep I think that's fine, it was something of a trade-off making things work across various resolutions.
