### ISSUE TITLE
Problem with Provider for Microsoft Exchange successor

### ISSUE THREAD

**Issue by JohnAnderson** [mozilla/addons-server#4225]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I installed "Provider for Microsoft Exchange" in Thunderbird.  Now when logging into TB, I get the following popup:
![image](https://cloud.githubusercontent.com/assets/4228382/21684374/690eef66-d32b-11e6-92f0-291e6b2ed6e9.png)
(Hopefully that worked.) But when I'm taken to the page where that says it will take me, it says the new extension can't be found:
![image](https://cloud.githubusercontent.com/assets/4228382/21684585/3140c9be-d32c-11e6-9a47-5662d3a74058.png)
### What happened?
see above
### What did you expect to happen?
see above
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
see above

**Comment by wagnerand** [comment]
Thank you for your report, can you please tell us the URL that is being opened in your browser, so we can investigate?

**Comment by JohnAnderson** [comment]
It wasn’t opened in a browser, it was opened in a tab in Thunderbird.  But when I open that tab in a browser, it is https://addons.mozilla.org/en-US/thunderbird/addon/exchange-20072010-calendar-/.

John

John Anderson, Ph.D.
@doctorjah
Director, Science and Culture Initiative
Senior Research Lecturer, Department of Physics
University of North Florida
+1-904-620-3988

**Comment by wagnerand** [comment]
Thank you.
This add-on has been deleted by its author a couple of years ago already.

Unfortunately, there is nothing we can do about this, so I'm closing this issue. I'm sorry for your inconvenience.
