### ISSUE TITLE
Add warnings in devhub about submission restrictions for legacy add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4233]
Per https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/ we'll be restricting *new* submissions of legacy add-ons to AMO when Firefox 53 is released (by end of Q1).

The add-on submission flows (new add-on, new version, new file) need to inform developers of the upcoming restrictions before that date. Per [the PRD](https://docs.google.com/document/d/1BdiJSYD4aOMClasGxx5wVShHEk8VbxefE3Gf_6jpgkQ/edit#) this should follow the UX proposed in #3634

**Comment by wagnerand** [comment]
Couldn't this be just another example of the "notification" system we'll need for https://github.com/mozilla/addons-server/issues/3634 ?

**Comment by diox** [comment]
Maybe it could, but I fear scope creep. I added a comment about the main thing that worries me about it - translations - in that issue.

**Comment by diox** [comment]
We don't need a new model for this - we can just use `zadmin.models.Config`, which is already used for the editors motd and the site-wide admin message. We just need to pick a key name like "submission_notice" and modify the relevant templates to display it where needed.

**Comment by diox** [comment]
The message can be set by admins in /en-US/admin/models/zadmin/config/, by adding a Config with the `submit_notification_warning` key and the desired text as value (HTML is allowed)

**Comment by muffinresearch** [comment]
@jvillalobos do you have copy for this, and an idea of how far in advance this should be turned on? 

It would be good to add the copy and test it out in advance of needing to show this notice in prod.

**Comment by jvillalobos** [comment]
Since we're turning on the restrictions for 53 and today we're launching 51, I think as soon as possible.

As for copy, how about "Starting with Firefox 53, new add-ons that use legacy APIs (anything except WebExtensions) will not be accepted on AMO. Version updates using legacy APIs will continue to be accepted until Firefox 57.".

**Comment by diox** [comment]
I've enabled that warning on dev.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (Win 7)
Banner is available in distribution page, in first step of submission for listed and unlisted add-ons, new version page (listed/unlisted) and new file page (listed/unlisted).
Postfix screenshots:
![newbanner-addon](https://cloud.githubusercontent.com/assets/15685960/22288614/6573263a-e300-11e6-933a-2e1c123a9bce.png)
![newfile](https://cloud.githubusercontent.com/assets/15685960/22288616/657a54dc-e300-11e6-8fe2-6c3d4fafd3e6.png)
![newversbanner](https://cloud.githubusercontent.com/assets/15685960/22288615/657674b6-e300-11e6-87ea-0292260a6d17.png)
