### ISSUE TITLE
Restrict legacy add-on submissions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4234]
Main bug for the actual restriction of new legacy add-ons submissions as described in https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/

The idea is to prevent the submission of new non-webextensions extensions in devhub. The following caveats apply:
- The restriction should be behind a waffle, not active yet.
- Only *new* submissions. Updates should still be possible for now.
- Only add-ons with the *extension* type, that are not webextensions.
- Only add-ons targeting only Firefox, Firefox for Android, or both. This leaves a loophole for extensions supporting multiple applications like Thunderbird or Seamonkey, but we can tackle that separately.
- Both listed or unlisted should be affected
- Only add-ons supporting version 53 or above (more precisely, we would only accept legacy Firefox extensions with strict compatibility and a `maxVersion` lower than 53.0)
- It should still be possible for an admin to click on “Override failed validation” in order to continue with the submission process.

**Comment by wagnerand** [comment]
Great overview!

> This leaves a loophole for extensions supporting multiple applications like Thunderbird or Seamonkey, but we can tackle that separately.

Any ideas on what we could do here?

**Comment by diox** [comment]
I just know there are/should be discussions happening with the maintainers of those apps to figure out something. IMHO this is more a discussion for the mailing-list or [the PRD document](https://docs.google.com/document/d/1BdiJSYD4aOMClasGxx5wVShHEk8VbxefE3Gf_6jpgkQ/edit#)

**Comment by wagnerand** [comment]
Summoning @jvillalobos then 😄

**Comment by jvillalobos** [comment]
Yes, we're having conversations with the Thunderbird and SeaMonkey councils about this. We shouldn't expect this to be resolved soon, so I think we should move forward allowing any new extension that supports either Thunderbird or SeaMonkey.

**Comment by diox** [comment]
Notes for developers working on this, i.e. @eviljeff  and me:

Spent quite some time investigating the best way to implement this. It's a less trivial than one could think, because we want the error to be one that can be overridden by admins.

The validator itself is the first obvious choice but it does not know whether an add-on is a new submission or a new version/file.

The alternative is somewhere in `parse_addon()` in addons-server code. Sadly, `parse_addon()` happens after validation has taken place, it can add fatal errors on top of that through raising `ValidationError`, but those are fatal and impossible to override. Trying to change this is both tedious and difficult, as `parse_addon()` is called in a lot of different places.

Because we need to check whether it's a new submission or not I think tweaking `parse_addon()` is the right approach but I'm not quite sure yet what form it should take.

**Comment by EnTeQuAk** [comment]
There is also `annotate_webext_incompatibilities` in `devhub.tasks` - not sure if something like that would be something you could use or abstract and re-use for that?

**Comment by diox** [comment]
Ah yes, thanks for pointing that out, I wanted to investigate how we annotate validation results currently, that seem like a promising approach.

**Comment by ValentinaPC** [comment]
@diox : new files are in the "updates" category? Because new files that are legacy add-ons with `maxVersion` over 53 are not restricted.

**Comment by diox** [comment]
> Only new submissions. Updates should still be possible for now.

What and where are you testing exactly ? Is the waffle enabled ?

**Comment by ValentinaPC** [comment]
Yes, the waffle is enabled. Stage.
I submitted a webextension and selected only Linux, then added a new file for the same version but other platform (new file was a legacy add-on with `maxVersion` 55) and it was not restricted.

**Comment by diox** [comment]
This is an edge case we are not concerned about for this issue. There is another issue filed to prevent you from doing this, https://github.com/mozilla/addons-server/issues/4689

**Comment by kewisch** [comment]
@jvillalobos, @diox  What are we doing for legacy add-ons that are in the queue right now and we have to reject because of issues? I suspect uploading a new version with fixes will still consider this addon to be "new". Developers can be unhappy if after waiting for a long while we rejected them with a valid (but possibly minor) issue and fixing that issue is not possible without rewriting as a WebExtension.

**Comment by diox** [comment]
No, AFAIK the restrictions should not apply in this case.

**Comment by jvillalobos** [comment]
If the restrictions don't apply in that case (which is good), we should still review them.
