### ISSUE TITLE
If installing a theme from Disco Pane, the author will not be displayed in More section for that theme

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4236]
Steps to reproduce:
1.On latest Aurora , go to about:addons and install Ice Flower theme
2.From Disco Pane - Appearance press More button for the newly installed theme
3.Remove the theme and install exactly same theme from AMO (https://addons.mozilla.org/en-US/firefox/addon/ice-flower-265447/?src=ss)
2.From Disco Pane - Appearance press More button for the theme installed from AMO

Expected results:
Same info are presented in More section for both installations

Actual results:
If installed from Disco Pane, the More section will not show the author , but if installed from AMO the Disco Pane will show it

Please see video for this bug:

![discopane](https://cloud.githubusercontent.com/assets/1583842/21723991/39c786b2-d43b-11e6-8ff3-d20227b75795.gif)

**Comment by mstriemer** [comment]
We should be including the author in the JSON that we put into the `data-browsertheme` blob.

This should be filed against addons-frontend, I'll move it.

**Comment by mstriemer** [comment]
Good catch by the way! Thanks for filing.
