### ISSUE TITLE
[DevHub Landing] Cross-browser testing of new developer pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4237]
Clearly our prime focus should be to have the devhub landing pages work in FF desktop and mobile, but we should also check other modern browsers just to make sure it's not horribly broken.

This issue is to just to serve as a reminder to check that.

**Comment by EnTeQuAk** [comment]
This is done, it looks fine in various browsers (Edge, Chrome, Firefox, Opera)
