### ISSUE TITLE
[Devhub Landing] Test and make sure it looks fine in RTL

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4243]
We didn't test this yet on RTL, let's test it and fix all the things.

**Comment by muffinresearch** [comment]
Logged out page has had the first pass of RTL fix-ups so the rest should mainly be focused on the logged-in page.

**Comment by vcarciu** [comment]
@EnTeQuAk : Hey , I think that the "Sign Out" should open the https://addons-dev.allizom.org/en-US/developers/ in signed out view and not AMO homepage. What do you think?

**Comment by EnTeQuAk** [comment]
This isn't the case anywhere currently. Although I do agree that'd be separate feature request and might not be easy to add or even not useful in some cases. So the default to redirecting to the homepage after logout is relatively safe and imho it's known behavior to users.

**Comment by vcarciu** [comment]
@EnTeQuAk Thanks for the response . I dont know what I did yesterday but I asked this question in the wrong bug and Today I asked again in the correct one . I will copy your response in the other bug.
