### ISSUE TITLE
Add-on admin page should point to review-unlisted pages when relevant

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4245]
STR:
1) Go to https://addons.mozilla.org/admin/addon/manage/amo-admin-assistant-unlisted/
2) Click on any link under the `Version` column.

That link takes you to https://addons.mozilla.org/editors/review/amo-admin-assistant-unlisted, which won't show much because all versions for that add-on are unlisted. It should point to https://addons.mozilla.org/editors/review-unlisted/amo-admin-assistant-unlisted instead. The target of the link should depend on the channel of the version.

**Comment by wagnerand** [comment]
That's why I voted for a single review page having a "listed" and an "unlisted" tab.

**Comment by jvillalobos** [comment]
Might also be nice to have a link under the `Actions` on the sidebar of review pages so admins can switch from one to the other easily.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF50(Win 7).
While having mixed versions for that add-on, clicking on the version number for unlisted, returns a 500 error page.
Please see video:
![unlisted](https://cloud.githubusercontent.com/assets/15685960/22289641/54b9896a-e305-11e6-8688-ac5f41febff5.gif)

Not reproducing for an add-on with all versions unlisted.
Ex. if admin page for add-on https://addons-dev.allizom.org/en-US/admin/addon/manage/test-webext1/ is loaded and version number is clicked, correct page - https://addons-dev.allizom.org/en-US/editors/review-unlisted/add-on-unlist is loaded.

@diox : please reopen this issue, if we wanna include mixed-versions case too, or let me know if another issue should be logged.

**Comment by diox** [comment]
@ValentinaPC that's an error in the unlisted review page itself, the link in the admin page is right with my changes. Please open up a new issue.

**Comment by ValentinaPC** [comment]
Ok, I shall mark this versified fixed.
