### ISSUE TITLE
Adblock Plus Pop-up Addon

### ISSUE THREAD

**Issue by erssre** [mozilla/addons-server#4247]
### Describe the problem and steps to reproduce it:
I'm trying to locate Adblock Plus Pop-up Addon via the link https://addons.mozilla.org/firefox/addon/adblock-plus-pop-up-addon/ given at http://jessehakanen.net/adblockpluspopupaddon/ but it says there is no such addon anymore.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
The add-on was taken down a couple of months ago, so it's no longer available. You can try contacting the developer to see if there are alternatives or future plans for it.
