### ISSUE TITLE
Stage is intermittently 502'ing

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4251]
Steps to reproduce:
1.Randomly navigate through AMO Stage pages

Expected results:
Everything is working as expected

Actual results:
Stage is intermittently 502'ing

Notes:
Not reproducible in Prod or -dev

**Comment by jasonthomas** [comment]
I could only replicate this once and could not after trying again. I also did not see anything unusual in the logs. I feel like one of the instances started up in a bad state so I restarted the uwsgi workers.  If you see this again please let us know. This could be indicative of a larger issue with our stage environment.

**Comment by ValentinaPC** [comment]
Tried 1 sec ago and was able to reproduce this:
![502](https://cloud.githubusercontent.com/assets/15685960/21812484/c7d2a072-d75b-11e6-8eef-f344c5767e34.gif)

**Comment by jasonthomas** [comment]
One of the nginx (olympia_proxy) ec2 instances was having issues. I've destroyed it and it is being rebuilt as part of the autoscaling group. Please test again and let me know if you continue to have issues. Thanks

**Comment by vcarciu** [comment]
Verified as fixed . Issue was not observed anymore.
