### ISSUE TITLE
Handle (wrongly) submitting a new version of an add-on via submit new addon better

### ISSUE THREAD

**Issue by Natim** [mozilla/addons-server#4257]
### Describe the problem and steps to reproduce it:
Upload a new version of an add-on from the New addon menu.

### What happened?

It tells you that the add-ons ID is already used.

### What did you expect to happen?

I though it would upgrade the addon version or redirect me to the new version page because I was in the personal management of the add-on mode and I didn't expect AMO to keep track of the add-on. I later realized that it was listed in my list of add-on with a new addon button.

I think that page should at least have redirected me to the list of add-ons with an error message.

### Anything else we should know?
- https://addons.mozilla.org/en-US/developers/addon/submit/distribution
- https://addons.mozilla.org/en-US/developers/addons

Maybe the translation in french was misleading and I wouldn't have made the same mistake in english.

**Comment by jvillalobos** [comment]
There are a couple of things we could do here:
* Possibly easier: when we check for duplicate IDs and find a match, check if the ID is owned by the same developer. If it is, show a more informative message with a link to `My Add-ons`.
* Again, if there's a match owned by the same dev, prompt them asking if they intended to submit a new version to the existing listing, and then direct them to the new version flow (ideally skipping the upload step). @eviljeff is most familiar with the existing flows, so I'll let him comment on how feasible this is.

**Comment by Natim** [comment]
> If it is, show a more informative message with a link to My Add-ons. 👍

**Comment by eviljeff** [comment]
Easiest would be just to just show a more specific error message when the add-on exists in the developers account.  
Adding a link to the error message that goes to my add-ons, or to the new version upload for the duplicated add-on is probably not too difficult either.
Jumping into the upload flow without the upload step may be more of a challenge - we do different checks for new add-ons and new versions (different validation too?).   Possible but probably infeasible.
