### ISSUE TITLE
Themes with "no-target" version number in Dev Hub homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4258]
Steps to reproduce:
1. Submit and approve a theme in AMO-stage i.e. https://addons.allizom.org/en-US/firefox/addon/4ttt/
2. Load Developer Hub homepage https://addons.allizom.org/en-US/developers/ and observe "My Add-ons" section

Expected results:
Last submitted add-on, in this case, theme, is listed. No "Latest version" link available (or, if available, should be working)

Actual results:
"Latest version" link available for theme, while we do not have the option to set a version for a theme. The link redirects to a 404 page.

Notes/Issues:
- the "latest version" number is increased every time theme design is updated;
- any number loads a 404 page even if the theme is public;
Verified on FF50.1(Win 7). Issue is reproducing all around AMO servers.
Video fro this issue:
![themeversion](https://cloud.githubusercontent.com/assets/15685960/21848159/448ec580-d808-11e6-8ec3-451b8d312326.gif)

**Comment by muffinresearch** [comment]
A replacement My Add-ons is being worked in presently - assigning this to @EnTeQuAk to take into acccount.

**Comment by EnTeQuAk** [comment]
This is already fixed in the new devhub pages, this isn't a link anymore. Closing, please feel free to re-open in case I misunderstood something.

**Comment by ValentinaPC** [comment]
@EnTeQuAk : yes, your are right, is not a link anymore, but, do we wanna displaye version number for themes, if, while submission, we do not set any versions number?
Thanks!!!
![theme](https://cloud.githubusercontent.com/assets/15685960/22290660/d9b4b2d4-e30a-11e6-88df-a3ffb6d29703.png)

**Comment by EnTeQuAk** [comment]
Yeah, I'll see if I can adapt this. I won't be cherry-picking this though since I think it's more of an edge-case than a blocker. Thanks for the idea!

**Comment by ValentinaPC** [comment]
@EnTeQuAk : I found a good reason to fix this: theme version (in general "`0`") can be seen in the brand new redesigned mobile pages, theme details. 
What do you think? Thanks!
