### ISSUE TITLE
Add-ons can’t be installed on Android using Nightly

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#4259]
**Describe the problem and steps to reproduce it:**

Try to install any Add-on using the latest Nightly on Android.

**What happened?**

The Add-on is not installed.

**What did you expect to happen?**

The Add-on is installed without any issues.

**Anything else we should know?**

This issue is reproducing only on **-dev** and **stage** servers on latest Nightly. 
I am not sure if this is a Firefox related issue.
I receive this error in the remote debugging console:
![mobile](https://cloud.githubusercontent.com/assets/15885467/21851425/c40f6878-d817-11e6-8c85-99dd5697a795.gif)

**Comment by muffinresearch** [comment]
@cosminbadescuSV looking at the console the error appears to be in browser code. 

Seems odd that this doesn't repro on prod, maybe it's related to signing in some way?

Could you re-file under addonManager in bugzillla and close this one pls? If investigation shows the error is related to something on AMO we can always reopen this or file a new issue.

**Comment by cosminbadescuSV** [comment]
@muffinresearch thank you for your assistance!
This issue was re-filed in bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1330537
