### ISSUE TITLE
Blocklist page on -dev shows "Oops! We had an error."

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4265]
Go to https://addons-dev.allizom.org/en-US/firefox/blocked/ and you'll see the error page. The individual blocklist pages ([like this one](https://addons-dev.allizom.org/en-US/firefox/blocked/p956)) still work. It all works in prod.

**Comment by muffinresearch** [comment]
This is a regression from https://github.com/mozilla/addons-server/commit/03dc6c26e4995133fa3c59ab50d20c76cf71fdfd

TemplateSyntaxError: Encountered unknown tag 'endblock'.

Template is 'blocklist/blocked_list.html', looks like the opening block was erroneously removed.

**Comment by muffinresearch** [comment]
Downgrading this, it's not on stage yet.

**Comment by vcarciu** [comment]
Verified as fixed : 
![blockl](https://cloud.githubusercontent.com/assets/1583842/21891713/ab52bca2-d8dc-11e6-92d0-c67d5e9ade00.png)
