### ISSUE TITLE
"Incomplete" status for unlisted add-ons in Dev Hub homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4269]
Steps to reproduce:
1. Submit an unlisted add-on in AMO-stage https://addons-dev.allizom.org/en-US/developers/
2. Observe its status in Developer Hub homepage

Expected results:
Add-on status is something else but "Incomplete".

Actual results:
Add-on status is "Incomplete".

Notes/Issues:
Verified on FF50.1(Win 7). Issue is reproducing all around AMO servers.
Video for this issue:
![unlisted](https://cloud.githubusercontent.com/assets/15685960/21886677/84d42370-d8c5-11e6-85d0-7d079ad52fa6.gif)

**Comment by wagnerand** [comment]
Yeah, it's confusing, but the status is actually correct. We probably shouldn't expose it, like we do on the Add-on edit pages.

**Comment by diox** [comment]
Yeah, it shouldn't be exposed if the the add-on has no listed versions.

**Comment by EnTeQuAk** [comment]
This page is being rewritten anyway at the moment, I'll take care this will be fixed there if that works for everybody.

**Comment by ValentinaPC** [comment]
Verified as fixed o AMO-dev FF50(Win 7)
Add-ons with only unlisted versions will not have status displayed in the new Dev Hub page.
Postfix screenshot: 
![unlisted](https://cloud.githubusercontent.com/assets/15685960/22141898/c47e5332-defc-11e6-8f86-9a7c65632ce6.png)
