### ISSUE TITLE
Use outgoing links for support_url and homepage in API responses

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#4270]
API responses include a support_url and homepage for add-ons which are external links. These should be sent through our outgoing link domain but currently they are returned by the API directly.

Example https://addons.mozilla.org/api/v3/addons/addon/adblock-plus/:

```json
{
  "homepage":{"ru":"http://adblockplus.org/","fr":"http://adblockplus.org/fr/","de":"http://adblockplus.org/de/","en-US":"https://adblockplus.org/","ko":"http://adblockplus.org/","pt-BR":"http://adblockplus.org/","pl":"http://adblockplus.org/"},
  "support_url":{"en-US":"http://adblockplus.org/forum/"}
}

**Comment by diox** [comment]
Should it be the API's job ? The outgoing link service is only relevant for AMO itself, and technically the API's scope is broader than that. Shouldn't it be done by the frontend code ?

**Comment by mstriemer** [comment]
That's fair. The API does provide outgoing links when they are embedded in the description of the add-on. If we are going to leave it up to the consumer those links should probably not be passing through the outgoing domain.

**Comment by muffinresearch** [comment]
> Should it be the API's job ? The outgoing link service is only relevant for AMO itself, and technically the API's scope is broader than that. Shouldn't it be done by the frontend code?

I agree that generally we'd push filtering/sanitization to API consumers however in this case I wonder if in this case it makes more sense to centralize outgoing external link building in addons-server as opposed to having to implement the same thing on addons-frontend too?

Having outgoing links by default shouldn't impact any external consumers, it just means outgoing might get a bit more traffic than otherwise. In any case as Mark mentions we are already doing this for the HTML we're sending for addon descriptions etc.

**Comment by muffinresearch** [comment]
@diox any further thoughts - what would it take to update the other urls sent by the API to use outgoing? See also the other discussion in mozilla/addons-frontend#1696

**Comment by diox** [comment]
It should be trivial to modify the API to do it. I've looked at it a little bit more and since using outgoing requires to generate a signature it would be tricky for the client to implement it, so maybe it should be the API's job.

**Comment by vcarciu** [comment]
Verified as fixed : 
![linksandoutgoing](https://cloud.githubusercontent.com/assets/1583842/23263511/1ea76646-f9e7-11e6-984c-da9bf2d62fa8.gif)

**Comment by ValentinaPC** [comment]
I'm not very sure where to check this....

I've verified API response for Firebug using AMO-dev - https://addons-dev.allizom.org/api/v3/addons/addon/firebug/ - and observed that homepage and support_url are using outgoing links.
See screenshots:
![homepage](https://cloud.githubusercontent.com/assets/15685960/23411013/c48b9e92-fdd9-11e6-8247-78d55755392c.png)
![support_001](https://cloud.githubusercontent.com/assets/15685960/23411014/c48fee66-fdd9-11e6-9048-e06375d6cd4b.png)

Please let me know if there is another place to verify this. Thanks!

**Comment by diox** [comment]
That's good, thanks.
