### ISSUE TITLE
Add embedded extension to the compat API

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4271]
We'd like to be able to track how many people have updated to an embedded extension. I think we added this to the reviewer tools, so it indicates this status to the reviewers. Could we also get this added to the compat API end point too?

http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#add-on-feature-compatibility
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions

**Comment by eviljeff** [comment]
is this obsolete now, given we're deprecating embedded extensions along with legacy xul ones?

**Comment by andymckay** [comment]
If reviewers didn't need it by now they won't need it by the time 57 is on release, so sure.
