### ISSUE TITLE
Beta releases gone from versions history for Thunderbird add-on

### ISSUE THREAD

**Issue by jikamens** [mozilla/addons-server#4275]
### Describe the problem and steps to reproduce it:

As of today, beta releases don't show up in the version history at https://addons.mozilla.org/en-US/thunderbird/addon/send-later-3/versions/ . N.B. this is a Thunderbird add-on, not a Firefox add-on.

### What happened?

Beta releases disappeared from version history.

### What did you expect to happen?

Beta releases should still appear in version history.

**Comment by kumar303** [comment]
We did a release today with these changes: https://github.com/mozilla/addons-server/compare/2017.01.10...2017.01.12

@muffinresearch do you know of anything that went out?

**Comment by EnTeQuAk** [comment]
Maybe https://github.com/mozilla/addons-server/commit/c16c75bdbea20bb2e40283ee27f00170c5799fc7?

**Comment by kumar303** [comment]
Hmm, I thought all of the unlisted/listed changes were behind a switch?

**Comment by diox** [comment]
This was a deliberate change https://github.com/mozilla/addons-server/issues/3704

Beta versions are no longer shown in the main versions list, and instead only shown in the development channel versions list.

**Comment by jikamens** [comment]
Thanks for the explanation. Is there some RSS feed / blog / announcements mailing list / whatever I can subscribe to where functional changes in upcoming AMO pushes are announced in advance of pushes? I would prefer not to be blindsided by such changes in the future.
