### ISSUE TITLE
Click on incomplete status redirects to final step of submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4282]
Steps to reproduce:
1. Submit a listed add-on in AMO-dev i.e. https://addons-dev.allizom.org/en-US/developers/addon/incomplete-dev/versions
2. Go to "Manage Status & Versions" and click "Cancel Review Request"
3. Click on "Incomplete" add-on status

Expected results:
User is redirected to step 1 of new version submission.

Actual results:
User is redirected to the final step of the submission process. User cannot `complete` its add-on from that point.

Notes/Issues:
Verified on AMO-dev FF50.1(Win 7).
Video for this issue: 
![incomplete](https://cloud.githubusercontent.com/assets/15685960/21926020/b457a144-d988-11e6-9ed2-7e657b63c8d3.gif)

**Comment by EnTeQuAk** [comment]
Hmm, is that a regression or does this happen on stage too?

**Comment by ValentinaPC** [comment]
It happens on stage, too.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
- clicking on "Incomplete" link while being in add-on manage page, user is not redirected anywhere.
- clicking on "Incomplete" link while being in My Submissions page, user is redirected to add-on manage page.
Postfix video: 
![inc](https://cloud.githubusercontent.com/assets/15685960/22196167/680b30b6-e154-11e6-8dad-49cf92403c60.gif)
