### ISSUE TITLE
Dev hub crashes with server error after submitting a new theme

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#4283]
### Steps to reproduce:
1. Open developer hub homepage: https://addons-dev.allizom.org/en-US/developers/
2. Click on "Submit a New Theme" button and complete the theme submission process.
3. Open developer hub homepage: https://addons-dev.allizom.org/en-US/developers/

### Expected Results:
The dev hub page loads.

### Actual Results:
Dev hub page does not load. "Oops! We had an error." error is displayed.

### Notes/Issues:
Issue can be reproduced in FF50(Win7) in addons-dev.allizom.org
Screencast for this issue: https://www.screencast.com/t/kLhNARwKc

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/377975/

I'll take a look.

**Comment by EnTeQuAk** [comment]
@madalincm I'm curious if this is happening on stage too 🤔

**Comment by madalincm** [comment]
It doesn't  happen on stage.

**Comment by eviljeff** [comment]
This happens if you have existing themes too... but only sometimes.  My speculation is that the page shows 3 Addon objects, and if one of those Addon is actually a Persona then it 500's.

**Comment by madalincm** [comment]
@eviljeff Yes you are right.  If one of those 3 objects is a theme then the dev hub page does not load.

**Comment by madalincm** [comment]
Verified as fixed in FF50(Win7). The issue is no more reproducing.
Postfix screencast:
![devhubpage](https://cloud.githubusercontent.com/assets/15685441/22287886/4b19f5b4-e2fd-11e6-8b09-2d02996fcb67.png)
