### ISSUE TITLE
New Dev Hub homepage has layout issue at browser resize

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4287]
Steps to reproduce:
1. Load Dev Hub homepage https://addons-dev.allizom.org/en-US/developers/
2. Resize the browser (width under 1024)

Expected results:
The page is resized.

Actual results:
The page is not resized.

Notes/Issues:
Verified on FF50.1(Win 7). Issue is reproducing only for the new Dev Hub pages.
Screenshot:
![resize](https://cloud.githubusercontent.com/assets/15685960/21929311/83334bf8-d998-11e6-8de3-8fbf202c6729.png)

**Comment by ValentinaPC** [comment]
Scrolls were added with success.
Verified on AMO-dev FF50(Win 7)
Video:
![devhub](https://cloud.githubusercontent.com/assets/15685960/22102663/ec613494-de40-11e6-9e77-bba64eaf1e37.gif)



@EnTeQuAk : is this the fix?

**Comment by EnTeQuAk** [comment]
Yes, at it's current version the logged-in pages aren't supposed to be responsive. Could be added later as a stretch goal but since most other pages on the AMO devhub aren't responsive too this didn't make much sense yet.

**Comment by EnTeQuAk** [comment]
> With a small white issue for smaller browser window:

Oh, that actually is a bug. Mind opening a new issue just with that screenshot and I'll take a look at it asap? Should be minor though I hope. Thanks a lot!
