### ISSUE TITLE
Pressing profile pic from Dev Hub will log you out from AMO

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4288]
Steps to reproduce:
1.Log in to AMO-dev 
2.Go to Tools- Developer Hub  
3.Press on the profile pic from top right side

Expected results:
Some info about the user are displayed

Actual results:
AMO page is displayed and user is signed out

Please see video for this issue: 
![profilepic](https://cloud.githubusercontent.com/assets/1583842/21929541/b255105a-d999-11e6-966a-e98e0c62b107.gif)

**Comment by EnTeQuAk** [comment]
yeah, I left a TODO note in the code. @pwalm I temporarily linked the profile picture to "logout" which probably isn't clever. I'm going to add a separate "Sign Out" link to the navigation to fix this, could have just been forgotten in the Sketch file.

**Comment by muffinresearch** [comment]
Now seeing it in practice it's clearly "Mystery meat navigation" [1] so a dedicated link is definitely the way forward. 

[1] https://en.wikipedia.org/wiki/Mystery_meat_navigation

**Comment by vcarciu** [comment]
@EnTeQuAk : Hey , I think that the "Sign Out" should open the https://addons-dev.allizom.org/en-US/developers/ in signed out view and not AMO homepage. What do you think?

**Comment by vcarciu** [comment]
Based on EnTeQuaAk's response from another bug, I will mark this as verified : 
 EnTeQuAk commented 5 hours ago

This isn't the case anywhere currently. Although I do agree that'd be separate feature request and might not be easy to add or even not useful in some cases. So the default to redirecting to the homepage after logout is relatively safe and imho it's known behavior to users.

Postfix video of the issue: 
![devhubnew](https://cloud.githubusercontent.com/assets/1583842/22028397/ba05ff64-dcdf-11e6-8a74-8b928f022abb.gif)

**Comment by pwalm** [comment]
Ah yes, a proper "Sign Out" link is much better.

**Comment by pwalm** [comment]
Oh, and I agree with @vcarciu, we should go to the Dev Hub home page instead of AMO.

**Comment by EnTeQuAk** [comment]
imho that'd require a more deep decision about whether we want to redirect the user to the page he came from after logout all the time or if that should be only something for devhub. I'll open a issue to talk about that in tomorrows standup.
