### ISSUE TITLE
When opening Add-on validator from -dev , the prod add-on validator is opened

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4289]
Steps to reproduce:
1.Log in to AMO-dev
2.Go to Tools- Developer Hub
3.Click on Tools - Add-on validator from page footer

Expected results:
The validator from -dev is opened(https://addons-dev.allizom.org/en-US/developers/addon/validate)

Actual results:
Validator from Production is opened (https://addons.mozilla.org/en-US/developers/addon/validate)

Please see video for this bug : 
![validatorprod](https://cloud.githubusercontent.com/assets/1583842/21929708/e5b4f43c-d99a-11e6-9e7d-acdf742643c2.gif)

**Comment by vcarciu** [comment]
@EnTeQuAk : can you please do the same thing for "Compatibility Checker" and "Compatibility Reporter" which are still pointing to Prod?

**Comment by wagnerand** [comment]
_Compatibility Checker_ does not have a stage (or dev) version, _Compatibility Reporter_ is just a link to an add-on which might or might not exist on stage (or dev).

**Comment by vcarciu** [comment]
@wagnerand at least for Compatibility Checker , I can see that https://addons.allizom.org/en-US/developers/addon/check-compatibility is opened on Stage , but if this is not relevant for testing the compatibility , I will mark the issue as fixed. Thanks

**Comment by wagnerand** [comment]
It looks like we're talking about different links.

Compatibility Checker links to https://compatibility-lookup.services.mozilla.com/
Compatibility Reporter links to https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/

**Comment by vcarciu** [comment]
@wagnerand I wanted to say that opening Compatibility Checker from Stage and Dev will return different things : 
Stage : https://addons.allizom.org/en-US/developers/addon/check-compatibility
Dev : https://compatibility-lookup.services.mozilla.com/

For Compatibility Reporter I agree with you that its only a link to an add-on which might or might not exist on dev

**Comment by EnTeQuAk** [comment]
I'm closing this since https://compatibility-lookup.services.mozilla.com/ is the correct link for the Compatibility Checker and linking to an add-on is only reliable on prod so I wouldn't change that too.

Unless I didn't grasp the whole discussion, otherwise feel free to re-open anytime.

**Comment by vcarciu** [comment]
I will reopen this for another reason. In signed out view , there are 2 links for Add-on validator from new dev hub and only one is now correctly pointing to -dev . The other one is still pointing to prod . Please fix the issue for the Validator from video below : 
![devhubvalidator](https://cloud.githubusercontent.com/assets/1583842/22069354/d304a3c8-dda0-11e6-8304-d67993f5c200.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![devvalidator](https://cloud.githubusercontent.com/assets/1583842/22335801/c0909280-e3e8-11e6-9fb3-6faa804de29b.gif)
