### ISSUE TITLE
"Site Status" link from page footer is not working

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4290]
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Go to Footer and click "Site Status"

Expected results:
A page is loaded. 

Actual results:
"Problem loading page" message displayed.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue: 
![2017-01-13_1717](https://cloud.githubusercontent.com/assets/15685960/21934993/50e75e48-d9b4-11e6-959b-c9a3ed36fc21.png)

**Comment by muffinresearch** [comment]
Somewhat ironically it looks like that status.m.o is down.

**Comment by muffinresearch** [comment]
Checked with the MOC and it's a known issue as the backend is being changed over. It will be back as soon as that's completed. 

Since there's nothing we can do from here I'll make this as closed and it should be possible to verify this as fixed soon.
