### ISSUE TITLE
[New DevHub Landing] Add language switcher

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4291]
The new devhub pages don't have our language switcher anymore. We should bring it back.

@pwalm any requirements for that from UX? I'll just add the switcher on the right hand side in a new row in the footer, similar to how it currently looks but adapted to new devhub color schemes.

**Comment by pwalm** [comment]
Sounds good to me! Can you provide a link or screenshot once implemented for review?

**Comment by EnTeQuAk** [comment]
Absolutely, I'll cc you on the pull request.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
Postfix screenshots for for signed in or out:
![logged_in](https://cloud.githubusercontent.com/assets/15685960/22068361/74715098-dd9d-11e6-9a49-a96023d23af6.png)
![logout](https://cloud.githubusercontent.com/assets/15685960/22068362/7473841c-dd9d-11e6-90c3-124084e098a0.png)

**Comment by pwalm** [comment]
👍
