### ISSUE TITLE
'New editors' pane contains editors that are no longer part of the group

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4298]
### Describe the problem and steps to reproduce it:

1. Add an user to the `Add-on Reviewers` group.
2. Make sure it shows up on `.../editors/`in the _New Editors_ panel.
3. Remove that user from the `Add-on Reviewers` group again.

### What happened?

The user is still listed in the _New Editors_ panel.

### What did you expect to happen?

The user should not bel listed in the _New Editors_ panel.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7)
Postfix screenshots:
![done](https://cloud.githubusercontent.com/assets/15685960/21979340/2e673a52-dbe7-11e6-8257-28946b8d311a.png)
![removed](https://cloud.githubusercontent.com/assets/15685960/21979345/31a5afe6-dbe7-11e6-8edb-5d2f95efdb5d.png)
