### ISSUE TITLE
"Submit your first theme" label is changed after submitting first add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4301]
Steps to reproduce:
1. Log in to AMO-dev with an account without add-ons 
2. Load Dev Hub for that account https://addons-dev.allizom.org/en-US/developers/
3. Observe the submission buttons (Submit your first add-on/Submit your first theme)
4. Submit your FIRST add-on and check the buttons again

Expected results:
Theme submission button is still "Submit your first theme".

Actual results:
Theme submission button is the same as add-on submission button, even if no theme was submitted.

Notes/Issues:
Verified on FF50 (Win 7). Issue is reproducing in AMO-dev.
Screenshots for this issue: 
![new-first](https://cloud.githubusercontent.com/assets/15685960/21976756/fbaf2382-dbdb-11e6-85d5-001d3ff99bed.png)
![2017-01-16_1103](https://cloud.githubusercontent.com/assets/15685960/21976763/048becd8-dbdc-11e6-855c-55aec1782cd2.png)

**Comment by EnTeQuAk** [comment]
We do not distinguish between whether or not a user submitted an Add-on or a Theme for the text and I don't think that's necessary. The switch is only intended for first-timers to have a proper "empty list" screen and after that it's just "Submit a new ...".
