### ISSUE TITLE
Misleading info while adding a second beta-listed version for an unlisted add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4302]
Steps to reproduce:
1. Submit an unlisted add-on i.e. https://addons-dev.allizom.org/en-US/developers/addon/avira-browser-safety/versions
2. Add a new listed `beta` version for that add-on 

Expected results:
No "Only publish this version to my beta channel." text and checkbox available, because the version will not end-up `beta` (as indicated in this [link](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance#How_do_I_submit_a_Beta_add-on) ), being the first listed version of an unlisted add-on.

Actual results:
The "Only publish this version to my beta channel." text and checkbox are available, misleading the user.

Notes/Issues:
- not reproducing without first unlisted version.
Verified on FF50(Win 7). Issue is reproducing on AMO-dev and AMO-stage.
Screenshots:
![beta](https://cloud.githubusercontent.com/assets/15685960/21978866/2b18b53a-dbe5-11e6-8ab6-e980e5b090b4.png)
![beta2](https://cloud.githubusercontent.com/assets/15685960/21978867/2e57425c-dbe5-11e6-8627-de22e1f1f5ac.png)

**Comment by ValentinaPC** [comment]
Is the fix on -dev already? Because I verified for add-ons and webextensions in AMO-dev FF50(Win 7) and the issue is still reproducing.
Screenshot: 
![2](https://cloud.githubusercontent.com/assets/15685960/22059969/a865b630-dd77-11e6-965e-5f4e1ef30f62.png)
Link for add-on: https://addons-dev.allizom.org/en-US/developers/addon/test-add-on-test123/edit

**Comment by eviljeff** [comment]
I was supposed to be but I made a mistake when merging.  It should be on -dev shortly (but isn't in the 2017-01-19 tag for deployment to prod)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMo-dev FF50(Win 7) for add-ons and webextensions.
The checkbox is not displayed for second `beta ` version while first version is unlisted.
Postfix screenshot:
![second-beta](https://cloud.githubusercontent.com/assets/15685960/22068142/bb53071e-dd9c-11e6-9188-480b9cd3bb0c.png)
