### ISSUE TITLE
"Internal Server Error" for "View Mobile Status" link from My Profile page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4304]
Steps to reproduce:
1. Load My Profile page in AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/user/ValentinaV/
2. Click on "View Mobile Site" link from the footer

Expected results:
No errors displayed.

Actual results:
"Internal Server Error" page is displayed.

Notes/Issues:
- after making step 2, if user navigates through AMO pages that have no correspondent for mobile, will receive error, without accessing the link from the footer. 
![others](https://cloud.githubusercontent.com/assets/15685960/21983566/9eb1f118-dbfa-11e6-86f5-c115be05a885.gif)

- not reproducing on AMO-stage and AMO-prod.
Verified on AMO-dev FF50(Win 7).  

Video for this issue:
![ise](https://cloud.githubusercontent.com/assets/15685960/21983407/d855370a-dbf9-11e6-9726-c97d9b7d5800.gif)

**Comment by muffinresearch** [comment]
That's issue is filed as an ops bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1330939
