### ISSUE TITLE
Add-ons cannot be installed from about:addons set to -dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4312]
Prerequisites:
Make the changes indicated in [page](https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing) for -dev

Steps to reproduce:
1. Access about:addons using Nightly
2. Install an add-on listed in "Get Add-ons" page

Expected results:
The add-on is installed.

Actual results:
The button is banned and the add-on cannot be installed.

Notes/Issues:
- if we set the `extensions.webapi.testing` pref to "false" the radio buttons fallback to big blue ones, that still don't work while trying to install a theme and return the JS error "TypeError: can't access dead object" while trying to install an add-on.
- if we test this on Firefox Release things from _actual results_ happen the same, but if we change the `extensions.webapi.testing` pref to "false" the add-on installation part triggers a doorhanger for add-on install.
- only reproducing for -dev  

Verified on FF53.0a1 and Ff50.1(Win 7).
Video for this issue: 
![installfail](https://cloud.githubusercontent.com/assets/15685960/22012964/4550484a-dc9f-11e6-9f51-66e232fbf28c.gif)

**Comment by muffinresearch** [comment]
I've added a blocks release label since I think this might be regression since it's only on -dev.

**Comment by muffinresearch** [comment]
Bisecting this shows the problem was introduced by https://github.com/mozilla/addons-frontend/commit/493abb6bbf8e7d64fc1e1fabf7efc5e73804b6c7

**Comment by muffinresearch** [comment]
The fix is on -dev. However, due to the caching by the server you will still get the old version until the cache expires. To test sooner you can go to `about:config` and append a query string to end of the value for `extensions.webservice.discoverURL`. e.g `?whatever=1` .

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev using FF50.1 and FF53 under Windows 7.
Add-ons can be installed without any problems after making the suggested changes.
Postfix video: 
![install](https://cloud.githubusercontent.com/assets/15685960/22025615/d73b32e2-dcd6-11e6-9beb-da0b753198f5.gif)
