### ISSUE TITLE
Incorrect use of `check_addon_ownership`

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla/addons-server#4313]
I was trying to understand which authors roles can reply to a review on AMO. Reading [this check](https://github.com/mozilla/addons-server/blob/b1a67339f0fc8974ef940be60e7d6d1ad08a0f03/src/olympia/reviews/views.py#L81), you would think all of `dev`, `viewer`, `support` can do this, but [another check](https://github.com/mozilla/addons-server/blob/b1a67339f0fc8974ef940be60e7d6d1ad08a0f03/src/olympia/reviews/views.py#L196) says only `dev` can.

Actually, looking at [`check_addon_ownership`](https://github.com/mozilla/addons-server/blob/0c2b633c592a882a51698949f2262773d1462b5b/src/olympia/access/acl.py#L86), you'll see passing `dev=True, viewer=True, support=True` doesn't work as intended and means only `owner` and `dev` roles.

I'd guess there're other confusing calls like this.

**Comment by muffinresearch** [comment]
@diox was this resolved by the fix to #6280?

**Comment by diox** [comment]
Yeah, both `support` and `viewer` were removed so that's not a problem anymore.
