### ISSUE TITLE
[RTL] Edit Listing links from new Dev Hub homepage are not entirely RTL

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4320]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/ar/developers/
2.Observe the Edit Listing links under My Add-ons section

Expected results:
Edit Listing links are placed in the left side of add-ons names

Actual results:
Edit Listing links are placed next to add-ons icons

Please see video for this bug : 
![editlisting](https://cloud.githubusercontent.com/assets/1583842/22030469/5adad2e2-dce6-11e6-8f9f-1bce3ab0628f.gif)

**Comment by EnTeQuAk** [comment]
ugh, good catch! I'll fix this shortly :)

**Comment by vcarciu** [comment]
Verified as fixed : 
![editrtl](https://cloud.githubusercontent.com/assets/1583842/22099376/c8b2658e-de33-11e6-9f1d-f5cd761e649a.png)
