### ISSUE TITLE
"Completed" add-on is displayed as incomplete

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4394]
Steps to reproduce:
1. Submit an unlisted add-on in AMO-stage
2. Add a second listed version for the submitted add-on but STOP at the step where categories and other details are requested
3. Go to "Manage My Submission" page and see your add-on status

Expected results:
The add-on is displayed as unlisted, as before making step 2.

Actual results:
The add-on is displayed as incomplete with "Resume/Delete" links and "This add-on will be deleted automatically after a few days if the submission process is not completed." text.

Notes/Issues:
- the add-on looks like the submission process was not finalized at all, even if this is true only for the second version
- if the first version is also listed, the issue is not reproduced
Verified on FF50(Win 7). Issue is reproducing on AMO-dev and AMO-stage.
Screenshots for this issue: 
![iscompleted](https://cloud.githubusercontent.com/assets/15685960/22067740/3cfa8af0-dd9b-11e6-9066-875814c6c5e3.png)

**Comment by diox** [comment]
It's an interesting edge case.

We discussed it with @eviljeff and came to the following conclusion:
- The _"This add-on will be deleted automatically after a few days if the submission process is not completed."_ text is obsolete. As far as we know, we don't do that. We should modify/remove it, it's unnecessarily scary.
- We need to adjust the wording for this use-case specifically. Technically, I think it makes sense to be able to resume submission... of the listed version. Or be able to cancel it if you want to keep it unlisted-only.

**Comment by ValentinaPC** [comment]
Because having the same results, I'll add here other steps to reproduce this. 
Please let me know if a separate issue must be logged.

1. Submit a listed add-on and approve it (i.e. https://addons-dev.allizom.org/en-US/developers/addon/test-webext-secondbeta/edit)
2. Submit a second `beta` version for the submitted add-on
3. Delete or disable the listed version
4. Go to "My Submissions" page and see your add-on status

**Comment by diox** [comment]
@ValentinaPC : please file a separate issue for this so that we can discuss it independently

**Comment by diox** [comment]
@jvillalobos I need some help with the wording on these 2 edge cases in "my add-ons" listing in devhub:

- **Add-on has no version (listed or unlisted)**. We currently don't display anything, and I think that's confusing. I'd like to display a message like "Your add-on currently has no versions. Do you want to submit one?". Suggestions?

- **Add-on has a listed version but didn't finish entering metadata (categories, description etc)**. We currently display *"This add-on will be deleted automatically after a few days if the submission process is not completed"* but this is wrong (we don't delete them), scary and confusing if you already had an unlisted version (in which case you did complete the submission process, it's just that you haven't completed the *listed* one). Can you figure out an alternative message to display instead ?

**Comment by eviljeff** [comment]
Beta versions add a [further edge case](#4427)

- **Add-on has a listed beta version.**  We currently display "This add-on will be deleted automatically after a few days if the submission process is not completed" which is also a little confusing (and still wrong) and doesn't mention the beta version.  The fix for the developer is the same as having no versions, i.e. upload one.

**Comment by jvillalobos** [comment]
* Add-on has no versions: "This add-on doesn't have any versions."
* Add-on has a listed version but didn't finish entering metadata: "This add-on is missing some required information before it can be submitted for publication."
  * Question: what happens in this case if there are unlisted versions?
* Add-on has a listed beta version: "This add-on doesn't have any listed versions, so its public page and beta versions are also hidden."

**Comment by diox** [comment]
> Add-on has a listed version but didn't finish entering metadata: "This add-on is missing some required information before it can be submitted for publication."
> 
>    Question: what happens in this case if there are unlisted versions?

@jvillalobos What *currently* happens is the initial subject of this bug, what *should* happen is what I'd like to know :)

**Comment by jvillalobos** [comment]
Given what I'm suggesting on https://github.com/mozilla/addons-server/issues/4440#issuecomment-274883515,  we should show "This add-on is missing some required information before it can be submitted for publication." regardless of there being additional unlisted versions or not.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7) with or without a first unlisted version.
Postfix screenshot: 
![resume](https://cloud.githubusercontent.com/assets/15685960/22418729/e4600b3a-e6e2-11e6-9fa8-f47fa44dae2f.png)
Also, "Resume" link work as expected.

**Comment by ValentinaPC** [comment]
@diox : Uuff... I don't know how to handle this: reopen - log another issue - please give me a hand:
 "Resume" link doesn't work anymore...
Please see video: 
![resume](https://cloud.githubusercontent.com/assets/15685960/22472377/1caa21fa-e7de-11e6-962b-d53432547433.gif)

**Comment by ValentinaPC** [comment]
Resume link is working as expected.
Postfix video:
![resume-ok](https://cloud.githubusercontent.com/assets/15685960/22584269/1f6612be-e9fa-11e6-9de1-86dfb8182fcc.gif)
