### ISSUE TITLE
Direct links to beta versions are broken

### ISSUE THREAD

**Issue by JustOff** [mozilla/addons-server#4395]
After #3704 was landed direct links to beta versions are broken.

For example, https://addons.mozilla.org/en-US/firefox/addon/speed-start/versions/2.1.0b1 leads to the list of releases, where no such beta exists. At the same time, list of beta versions https://addons.mozilla.org/en-US/firefox/addon/speed-start/versions/beta provide only links to specific version as shown above.

**Comment by diox** [comment]
Argh. I'll fix that (pointing to the beta list if the version is a beta one), thanks for reporting the bug.

**Comment by JustOff** [comment]
Thanks. It also concerns to auto-generated links in the recent activity at [DevHub](https://addons.mozilla.org/en-US/developers/addons).

**Comment by ValentinaPC** [comment]
Verified as fixed for beta versions from page https://addons-dev.allizom.org/en-US/firefox/addon/firebug/versions/beta using AMO-dev FF50(Win 7).
 Postfix video:
![beta](https://cloud.githubusercontent.com/assets/15685960/22145906/bcd5c818-df0b-11e6-94fc-48024e861a0b.gif)

> Thanks. It also concerns to auto-generated links in the recent activity at DevHub.
Not very sure where to check this? Thanks!

**Comment by JustOff** [comment]
> >    Thanks. It also concerns to auto-generated links in the recent activity at DevHub.
>
> Not very sure where to check this?

Since links don't change (only rules of redirect were updated), they will also redirect to the right page. Thanks!

PS: When we can expect this fix in production?

**Comment by ValentinaPC** [comment]
> PS: When we can expect this fix in production?
I think with the push from January 26. 
Maybe @diox can confirm :)

I'll mark this as verified fix based on above comments.

**Comment by diox** [comment]
Yep, it will land in prod next week.
