### ISSUE TITLE
Restart browser message for restartless add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4396]
Steps to reproduce:
1. Go to about:addons
2. Install an add-on i.e. OmniSidebar
3. Go to "Extension" tab and remove it
4. Switch back to "Get Add-ons" tab

Expected results:
There are no display or layout issues.

Actual results:
Restart browser message is displayed a few seconds for that the uninstall changes to be applied, even if the add-on is restartless.

Notes/Issues:
Verified for about:addons set to -stage, -dev and -prod using FF53(Win 7).
Video and screenshot for this issue:
![green](https://cloud.githubusercontent.com/assets/15685960/22071055/9f346e7e-dda6-11e6-85a8-1f153b49d001.gif)
![2017-01-18_1750](https://cloud.githubusercontent.com/assets/15685960/22071066/a724b346-dda6-11e6-8932-a48828edb72c.png)

**Comment by muffinresearch** [comment]
This is possibly a bug in `mozAddonManager`. It needs further investigation to clarify. We only generally show that UI if we get the needRestart hint so if this isn't just a bug in in our code it might mean we get a needRestart hint erroneously - if that's the case this can be re-filed as a bug on bugzilla.

**Comment by diox** [comment]
Not an addons-server bug, might be a bug in addons-frontend or platform, please re-open in addons-frontend for investigation.

**Comment by ValentinaPC** [comment]
Logged: https://github.com/mozilla/addons-frontend/issues/2116
