### ISSUE TITLE
New dev hub should have a Register button if it is in signed out state

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4397]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/developers/ and be sure that you are signed out

Expected results:
In order to be consistent with the rest of AMO and because I think that users will expect that , a "Register" button should be available next to "Sign In"

Actual results:
Only "Sign in" button available

Please see screenshot for this issue : 
![register](https://cloud.githubusercontent.com/assets/1583842/22072330/ba29a0ce-ddaa-11e6-90fd-731b48895a6f.png)

**Comment by EnTeQuAk** [comment]
cc @pwalm here, I'm going to change this to what we currently have on AMO, "Register or Sign In" if that's alrighty with everyone. I do agree that the register link is missing.

**Comment by pwalm** [comment]
Perfect, sounds good 👍

**Comment by ValentinaPC** [comment]
Verified as fixed (also for RTL) in AMO-dev FF50(Win 7).
Postfix screenshot:
![2017-01-20_1348](https://cloud.githubusercontent.com/assets/15685960/22148512/317fd1da-df17-11e6-816d-08ab5fe339c7.png)
