### ISSUE TITLE
Don't include paypal javascript on pages that don't need it.

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4421]
3 years ago (!) in 76aeb500827c273702988f09029360690b13dbe9 we changed our pages so that the paypal javascript is only present on pages that may need it. It's now only present on developer pages, addon detail page, addon review page.

We can go one step further and remove it from developer pages entirely - where the contribution button never appears - and check if the add-on takes contributions on the other pages, and remove it if it doesn't, improving perf for those pages.

**Comment by ValentinaPC** [comment]
Can you please add some STR so we can check this? Because I took a look in the console, comparing -stage and -dev and didn't saw any difference.
Thanks in advance!

**Comment by diox** [comment]
STR:
- With an add-on that has contributions disabled, make sure that on the detail page, on the review page and on any devhub page, there is no reference to a paypal javascript file in the source or in the network tab when loading the page
- Repeat with an add-on that has contributions enabled: the paypal javascript should be present in the pages mentioned above, *except* devhub.
- Obviously those page should still work properly :)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF50(Win 7) and obtained the following results:
1. Contributions _disabled_ : **no reference** to a paypal file in detail page, on the review page and on any devhub pages - pages work properly; 
2. Contributions _enabled_: **reference** to a paypal file in details page and review page, **_but none in devhub pages_**
![details](https://cloud.githubusercontent.com/assets/15685960/22153996/61cee522-df32-11e6-9750-ca4f824fcec5.png)
![review](https://cloud.githubusercontent.com/assets/15685960/22154004/68f21c2a-df32-11e6-94fa-74f27c281ef9.png)
![manage](https://cloud.githubusercontent.com/assets/15685960/22154009/6d7843e6-df32-11e6-90cb-177c4628b127.png)

I have another question (sorry): are the changes already in -stage? because with contributions enabled, no paypal js file on devhub, here either. (so I was not able to see the initial issue while reproducing)

**Comment by diox** [comment]
Good catch, I actually made a mistake because the naming of the templates are confusing. The template I changed is on the "meet the developer" public page, and that was wrong, I'll fix that.

**Comment by kewisch** [comment]
Would also be nice to remove this from the editor review pages, I've had some minor delays when reviewing add-ons and it is unlikely that I would donate from the review page.

**Comment by diox** [comment]
I've removed it from review pages of add-ons that do not have contributions enabled, but left it when contributions are enabled in order not to break existing functionality - I didn't want to judge alone if it was useful or not. If the contribute button itself is useless on review pages then please file another issue about it (removing it is a little more involved, since it's re-using the public details page template).

**Comment by diox** [comment]
@ValentinaPC the fix for what I describe in https://github.com/mozilla/addons-server/issues/4421#issuecomment-274102089 should be on dev in 10 minutes.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF50(Win 7).
If Contributions are `enabled`, paypal .js file is listed in: add-on details page, add-on review page, Meet the developer page and NOT in any of the Dev Hub pages.... but same thing happens in -stage. Is this fix already in stage?

**Comment by diox** [comment]
Ignore devhub pages, that was a misread on my part, it hasn't changed as part of this patch - paypal js was already absent from these pages before, should still be after.

**Comment by ValentinaPC** [comment]
@diox : but as a part of this patch - https://github.com/mozilla/addons-server/pull/4422 ?

In the first comment and in your second, it is stated that:
> the paypal javascript should be present in the pages mentioned above, except **devhub**
I understood that the second patch is for adding back the paypal js to the Meet developer page, but the first one?
Thanks and sorry to insist!

**Comment by diox** [comment]
The first one didn't touch devhub at all - I thought it did at the time, but I was wrong, it was actually touching the meet the developers page, which is why it required the second patch to fix that page.

**Comment by ValentinaPC** [comment]
I am just confused about the initial purpose of this bug... but if you say it is ok, I' ll add the screenshot related to Meet developer page and close this.
Postfix screenshot: 
![meetthedev](https://cloud.githubusercontent.com/assets/15685960/22210348/2ea1f998-e192-11e6-9925-426cfca0815c.png)

**Comment by diox** [comment]
Just ignore all references to developer pages in the bug description, that was a wrong assumption from me, it was already gone from these pages a long time ago.
