### ISSUE TITLE
Beta add-on asking for resume after deleting first listed version

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4427]
Steps to reproduce:
1. Submit a listed add-on and approve it (i.e. https://addons-dev.allizom.org/en-US/developers/addon/test-webext-secondbeta/edit)
2. Submit a second beta version for the submitted add-on
3. Delete the listed version
4. Go to "My Submissions" page and see your add-on status

Expected results:
The add-on has a status (maybe "Incomplete"?).

Actual results:
The add-on has 2 links: Resume and Delete together with the message "This add-on will be deleted automatically after a few days if the submission process is not completed." 

Notes/Issues:
- Using the direct manage link for the submitted addon  i.e. https://addons-dev.allizom.org/en-US/developers/addon/test-webext-secondbeta/edit the add-on status is "Incomplete".
- if the listed version is only `disabled` the add-on is listed as "Incomplete"
- Beside the "Listed version" text from manage page is displayed the beta version number - which is a bit confusing.
Verified on FF50(Win 7). Issue is reproducing on AMO-dev and -stage.
Screenshots for this issue:
![manage](https://cloud.githubusercontent.com/assets/15685960/22148002/4deac13e-df14-11e6-9fe8-d6d4a3bc16b9.png)
![mysubm](https://cloud.githubusercontent.com/assets/15685960/22148007/544e32a4-df14-11e6-84be-549670724439.png)

**Comment by eviljeff** [comment]
Currently what happens in this scenario is the Addon stops being Approved, because it has no Approved listed versions, but it _does_ have a listed version (the beta version) so it's status is Incomplete and shown as such.  
The 'listed version' is shown as 1.1b as a beta version stops being treated as a beta version for latest version purposes because only Approved Addons can have a beta channel.

(It's all a bit muddled because beta versions are a type of listed version, rather than an explicit extra channel.)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF51(Win 7) and obtained the following results:
- Add-on status: Incomplete
- Info message displayed in "Manage My Submissions" page
- adding an unlisted version will add an `AMO` label near the Beta version
- adding a listed version will turn add-on status to "normal"
Screenshots:
![manage_pg](https://cloud.githubusercontent.com/assets/15685960/22749611/9b5249ac-ee36-11e6-8955-565d8b0da676.png)
![mysubmission](https://cloud.githubusercontent.com/assets/15685960/22749610/9b4d96a0-ee36-11e6-8327-a3f0405b2980.png)
![amo-label](https://cloud.githubusercontent.com/assets/15685960/22749621/a2600b76-ee36-11e6-93d5-c17496c96769.png)

@diox : If this is how it suppose to look, I'll mark this verified. Thanks!

**Comment by diox** [comment]
Yep, that's it. We could do better in the versions page but I focused on making the message in the add-on list correct.
