### ISSUE TITLE
"Report bug" link from the new Dev Hub pages redirects to wrong page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4428]
Steps to reproduce:
1. Load the new Dev Hub page in AMO-dev (sing in or out mode) https://addons-dev.allizom.org/en-US/developers/
2. Go to page footer
3. From "Support" section click "Report bug" link

Expected results:
Page https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact is loaded.

Actual results:
Page https://github.com/mozilla/addons/issues/new loads.

Notes/Issues:
Verified on FF50(Win 7). Issue is only reproducing from the new Dev Hub pages.
Video for this issue:
![reportbug](https://cloud.githubusercontent.com/assets/15685960/22148745/8e966fcc-df18-11e6-801b-129348741ed1.gif)

**Comment by EnTeQuAk** [comment]
This is the link and copy I got from @atsay, see https://github.com/mozilla/addons-frontend/issues/1021#issuecomment-253661285 for more details. So I think it's correct to link to GitHub. Afterall our mozilla/addons repository will be used for a broader audience for bug reporting for various projects afaik.

**Comment by ValentinaPC** [comment]
@EnTeQuAk I filled this based on #3951 being introduced a few months ago 😄 and my support in terms of consistency.

**Comment by EnTeQuAk** [comment]
oh, I didn't know about this one. I'll update the link then, thanks for pointing this out!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7) for sign in or out mode.
The _Report Bug_ link redirects to "https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact" page now.
