### ISSUE TITLE
Review tools: Please re-add the file-path display

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#4434]
### Describe the problem and steps to reproduce it:
Previously file-path was displayed after the `<h3>` title on top of the `/files/browse/` or `/files/compare`/ display.
The last update removed the file-path display.

It was useful for copying when we had to note the filename in the review ie:
`background/lib.js`

Using just the filename can cause confusion if there are other files with the same name ie
```
data/js/jquery.min.js
libs/jquery.min.js
```

Now, the options are to copy the URL and delete the starting part OR manually write the nested directories OR write a script to replace the missing file-path.

It would be helpful if the file-path display is re-added.

**Comment by EnTeQuAk** [comment]
I wonder if you mean 03dc6c26e4995133fa3c59ab50d20c76cf71fdfd by "recent update" since this only removed the actual file-link from the breadcrumb but didn't really show the file-path before. Do you maybe have a screenshot of where the path was before?

**Comment by erosman** [comment]
I dont have a screenshot and I cant get it anymore but...

For example:
https://addons.mozilla.org/en-US/firefox/files/browse/616882/file/js/bg.js#top
Where you have
```
<h3>
  <a href="/en-US/editors/review/*****">*** for YouTube™ 2.0.3</a>
</h3>
```

It would have appeared in front of it.
Since h3 is a block element, it would have been placed after  `<a>...</a>`

Its data (I imagine) would have come or was the same as `data-short="js/bg.js"`

`<a class="file selected" data-delay="0" href="/en-US/firefox/files/browse/616882/file/js/bg.js" data-short="js/bg.js" style=""><span>bg.js</span></a>`

I hope that helps.

**Comment by EnTeQuAk** [comment]
That helps! Thanks!
