### ISSUE TITLE
What is mysql user name and password?

### ISSUE THREAD

**Issue by kamikaze123** [mozilla/addons-server#4444]
What is mysql credential? I want to login to mysql, but I do not know the credentials...

**Comment by kamikaze123** [comment]
I am reading document(Install with Docker), but I can not find the default credentials

**Comment by muffinresearch** [comment]
If you've installed the development environement with docker all you need to do is run `make dbshell` and that should drop you at a mysql prompt.

**Comment by kamikaze123** [comment]
Thanks:))
