### ISSUE TITLE
[devhub landing] footer is not "stuck" bottom of the viewport

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4451]
### Describe the problem and steps to reproduce it:

- With no pre-existing addons, sign-in to /en-US/developers/ 
- Scroll to the bottom of the page

### What happened?

Note the whitespace at the bottom of the viewport

### What did you expect to happen?

No whitespace at the bottom of the viewport.

### Anything else we should know?

Here's a screenshot (note whilst the screenshot is in RTL the problem exists for both LTR and RTL.)

<img width="698" alt="_ ____ _" src="https://cloud.githubusercontent.com/assets/1514/22212882/2e23d4da-e18a-11e6-9a25-a837ff3b7f3d.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
Postfix screenshots (ltr, rtl) :
![nopadding](https://cloud.githubusercontent.com/assets/15685960/22289980/0c60f0d4-e307-11e6-92ac-f3014e8e02fc.png)
![rtl](https://cloud.githubusercontent.com/assets/15685960/22289981/0c613cec-e307-11e6-8903-3dc69df3baca.png)
