### ISSUE TITLE
Can't skip Android categories, but I can for Desktop

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4455]
### Describe the problem and steps to reproduce it:
Submit an add-on, decide you don't like Desktop categories, click "My add-on doesn't fit into any of the categories." Try the same on Android. There isn't a similar button, field is required.

### What happened?
Form submit not allowed.

### What did you expect to happen?
If I can skip categories on Desktop, should be able to on Android.

### Anything else we should know?
![screenshot 2017-01-23 11 55 01](https://cloud.githubusercontent.com/assets/74699/22220360/3883cac4-e163-11e6-9b81-3fb5f8285547.png)

**Comment by diox** [comment]
For some reason there is no "misc" category for android extensions, that's why the option is missing.

We need a migration to add the category (with the `misc` field set to `True`, as well as the right `type` and `application`) *and* modification of the constants.

**Comment by vcarciu** [comment]
Verified as fixed : 
![misc](https://user-images.githubusercontent.com/1583842/30631686-c3f824b4-9ded-11e7-8c6a-a5c9c8f2d77c.png)
