### ISSUE TITLE
Tabgroups Manager revived

### ISSUE THREAD

**Issue by luber1** [mozilla/addons-server#4458]
After Tabgroups Manager revived was available Feb 2016, things were going swimmingly, sure some TGM tabs were switched around each startup but relatively plain sailing.

Now I'm on Firefoc 50.1.0, Win10 
To get to roughly where I was pre this FF version, I have to do Session Manger/backuo sessions/previous session 3 times to get to a window which has TGM tabs [first time results in 1 tab with 190FFtabs, second time 190FF tabs in 3 rows, third time 16TGM tabs with FF tabs included] but the TGM tabs are a little disarrayed, 1 TGM tab with name replaced by generic but name still available in favourites list and TGM tabs with icons, losing them].

The main reason I use FF is because I can group and quickly jump from tab to tab.

Does anybody know if TGM is still being supported/upgraded?  

Does Edge Chrome Opera Pale Moon Safari Maxthon etc have TGM or TGM type feature?

**Comment by jvillalobos** [comment]
You have to contact the developer to get any answers. There's contact information on the [listing page](https://addons.mozilla.org/addon/tabgroups-manager-revived/).

**Comment by luber1** [comment]
Thank you for your reply.  FYI I've scoured the listing page but while it lists the developers. it doesn't list contact details [even by inspecting page code]

 

regards, Lu

 

 

Sent: Wednesday, January 25, 2017 at 8:30 AM

**Comment by jvillalobos** [comment]
I can see links to a support site and support email on the listing page.
