### ISSUE TITLE
Enable and use USE_L10N setting and framework

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4464]
Django has wonderful and powerful tools to do l10n formatting of datetimes and strings: https://docs.djangoproject.com/en/1.10/topics/i18n/formatting/ - we aren't using it at the moment, we really really should though.

Let's do it!

Things that come to mind:

We do sometimes things like

```django+html
{{ addon.last_updated|datetime(_('%%b %%e, %%Y')) }}
```

which could and should be 

```django+html
{{ addon.last_updated|datetime('DATETIME_FORMAT') }}
```
 (pseudo code, not sure if this works easily with how we're integrating with Jinja2 but you see what I mean. https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#date

**Comment by eviljeff** [comment]
closing as per my last comment - we don't do custom datetime or date formatting in templates any longer.  (reopen if there's another concrete use case)
