### ISSUE TITLE
Rows containing new files are not aligned in Manage Admin page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4477]
Steps to reproduce:
1. Access "Admin Manage" for that add-on with multiple files contained in a version i.e https://addons.allizom.org/en-US/admin/addon/manage/word-stage-xpi/

Expected results:
There are no display or layout issues.

Actual results:
Rows containing new files are not aligned with first submitted file. 

Notes/Issues:
Verified on AMO-stage FF50(Win 7).
Issue is reproducing on AMO-stage and AMO-dev.
Screenshot for this issue: 
![2017-01-25_1334](https://cloud.githubusercontent.com/assets/15685960/22289195/1244af1c-e303-11e6-8bcd-d8200257edac.png)

**Comment by diox** [comment]
Fixed in #4478 I will be backporting the fix to this week's tag.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7)
Postfix screenshot: 
![mixed](https://cloud.githubusercontent.com/assets/15685960/22298465/41ca7a02-e329-11e6-91a0-694d2df0047f.png)
