### ISSUE TITLE
Add-on unlisted review page is returning 500 error for add-ons with mixed unlisted/listed versions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4479]
Steps to reproduce:
1. Load Edit information page for an add-on with mixed versions i.e. https://addons-dev.allizom.org/en-US/developers/addon/test123456-dev/edit
2. Click "Admin Manage" link
3. Click on an unlisted version number

Expected results:
Review page should load (listed or unlisted).

Actual results:
500 error page is loaded.

Notes/Issues:
Verified on AMO-dev and AMO-stage using FF50(Win 7).
Issue is not reproducing for all unlisted versions add-on.
Video for this issue: 
![54b9896a-e305-11e6-8688-ac5f41febff5](https://cloud.githubusercontent.com/assets/15685960/22290420/52d1bb8c-e309-11e6-8929-7ab6dc28fcce.gif)
Relates to #4245

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/379479/

**Comment by diox** [comment]
Note: this affects the unlisted review page regardless of whether you go through the admin page or not, so it's quite serious.

**Comment by diox** [comment]
New (theoretical, not tested) STR:
- Turn the `mixed-listed-unlisted` switch on
- Submit an unlisted and a listed version for an add-on. The add-on should now be awaiting review, with the unlisted version "public", the listed version awaiting review
- Go to the unlisted review page
- You get the error

**Comment by ValentinaPC** [comment]
> Go to the unlisted review page
How do I get there? 
Because searching the add-on in _All Unlisted Add-ons_ page does not work, from "Admin Manage" this #4479 blocks us and from "Add-on Review" we are redirected to add-on review listed page. Thanks!

**Comment by diox** [comment]
My point in those STR was to say that it doesn't matter how you reach the page. i.e. if you knew the link in advance it would fail the same way, no need to go through the admin page.

That being said, the search *should* have worked. That's a different issue though...

**Comment by ValentinaPC** [comment]
There is an issue logged for that case? Let me know if I can help by logging one or adding a comment to an existing one.

**Comment by diox** [comment]
Please file another issue for the search - I'm not sure exactly what's causing this, so if you could find precise STRs for it (what state the add-on must be in in order to reproduce it) that'd be great.

**Comment by ValentinaPC** [comment]
@diox: I wanna add something discovered here:
- while first submitted version is listed and second submitted version is unlisted there is no 500
Issue is reproducing **only if the first submitted version is unlisted**, as is the case of #4484 .
I don't know if something you worked at already fixed this case (I don't think so, because this is also happening in stage); hope I helped!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7)
Postfix video:
![review-unlisted](https://cloud.githubusercontent.com/assets/15685960/22325834/c36d9aa0-e3b8-11e6-874e-27bf7a73e8f9.gif)
