### ISSUE TITLE
Search in "All Unlisted Add-ons" is not working for add-on with mixed versions if first version is unlisted

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4484]
Steps to reproduce:
1. Submit an unlisted add-on i.e. https://addons-dev.allizom.org/en-US/developers/addon/first-unlisted-secondlisted-aw/edit
2. Add a new listed version for that add-on (approve it or not)
3. Go to _Reviewer Tools-All Unlisted Add-ons_ queue page and search the submitted add-on

Expected results:
The add-on is displayed after search.

Actual results:
The add-on is no displayed.

Notes/Issues:
- if the add-on has **only unlisted** version, the add-on is displayed after search in "All Unlisted Add-ons" queue
- if **first** submitted version is **listed** (awaiting/approved), after adding a **second unlisted** version, the add-on is displayed after search in "All Unlisted Add-ons" queue  

**The issue is only reproducing for an add-on with mixed versions, from which first MUST be UNLISTED.**  

Verified on FF50(Win 7). Issue is reproducing in AMO-dev and -stage.
Video for this issue: 
![search-unlisted](https://cloud.githubusercontent.com/assets/15685960/22295767/c7b59f92-e320-11e6-94a9-e47fac34bf89.gif)

**Comment by eviljeff** [comment]
I think it may be if the most recent version is listed, rather the first version being unlisted.  But yeah, it's broken.

**Comment by ValentinaPC** [comment]
> I think it may be if the most recent version is listed, rather the first version being unlisted. But yeah, it's broken.

- you are right, but it must be an unlisted version before. :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
Postfix video:
![unlisted-listed](https://cloud.githubusercontent.com/assets/15685960/22336110/cee9fadc-e3e9-11e6-9bcd-51c893422a73.gif)
