### ISSUE TITLE
Handle duplicate version better

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4488]
Steps to reproduce:
1. Submit a listed add-on in AMO-stage (approve it or not)
2. Select a valid file and click "Continue" to upload new version for that add-on
3. Go back from the browser
4. Select the file used at step 2 and click "Continue"

Expected results:
Handle duplicate version better.

Actual results:
The message "Version 2 already exists, or was uploaded before." is displayed and user is blocked, even if "Submit Version for Review" submission final step was not passed.

Notes/Issues:
Checking add-on manage page, we will see the version selected at step 2, awaiting review.
Verified on FF50(Win 7). Issue is reproducing on AMO-dev, stage and prod.

Logged as a follow-up to @eviljeff suggestion from #4420.

**Comment by vcarciu** [comment]
Verified as fixed : 
![versionsame](https://cloud.githubusercontent.com/assets/1583842/24105499/b7ab4a9c-0d8d-11e7-9223-88efe849e4da.gif)
