### ISSUE TITLE
Resolve https://outgoing.prod.mozaws.net/v1/ being reported as an attack page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4489]
https://outgoing.prod.mozaws.net/v1/ is marked as an attack page 🔥 (apparently) by Google. The details are at https://www.google.com/transparencyreport/safebrowsing/diagnostic/index.html#url=http://outgoing.prod.mozaws.net/v1/

It's not a huge surprise since this is just our forwarder to external pages and developers can link to any website in add-on listings.

Short-term, we should try to get us off the list, but long-term we need a plan to avoid it from even happening as we can't really control what pages we are going to forward to.

Screenshot: 

<img width="524" alt="reported_attack_page_" src="https://cloud.githubusercontent.com/assets/1514/22330847/2feec4b8-e3c0-11e6-8d5d-b623c79cb338.png">

**Comment by tofumatt** [comment]
It's probably a bit of cat and mouse; apparently we're largely in violation because of `imgbox.cc`, so maybe we need a block list of sites we allow authors to link to if they show up on there?

**Comment by muffinresearch** [comment]
FWIW: I've sent the review form on https://www.stopbadware.org doing anything else required webmaster tools setup for outgoing.  Since that's https://github.com/mozilla-services/outgoing we might be better to move this bug there.

Looking at the db the addon pointing to imgbox has already been disabled so that should mean we aren't currently linking to it via outgoing.

**Comment by jasonthomas** [comment]
I signed up for webmaster tools for outgoing - there are a few other urls (pasted them in channel). These urls will still remain valid unless we block them from the outgoing service (via nginx or the actual application). We can also rotate the outgoing secret key but that will require us to make modifications to the DB to fix up old outgoing links iirc.

**Comment by muffinresearch** [comment]
As mentioned on irc, blocking via nginx sounds good. 

Longer term we'll need to think about how we can prevent outgoing links working for bad hosts. E.g. should we run a manual block-list or should outgoing be aware of these 3rd party blocklists and remove bad links as they come up.

Blocking on the way in addons-server is also a possibility however, a problem with that approach is that a good actor today could be a bad actor tomorrow. Blocking at the outgoing level probably makes more sense and we could then also show an informative page at that point (albeit less scary than the FF one). That would also hopefully mean the whole of outgoing stays out of this blocklist in future.

**Comment by jasonthomas** [comment]
nginx block in place on prod. I submitted a review request via google webmaster tools. They state that it may take up to 72 hours :\

**Comment by MaDonnasPersonas** [comment]
I have the same issue with the links to my wallpapers.

**Comment by jasonthomas** [comment]
The safebrowsing block has been lifted.

> Google has received and processed your security review request. Google systems indicate that https://outgoing.prod.mozaws[.]net/ no longer contains links to harmful sites or downloads. The warnings visible to users are being removed from your site. This may take a few hours to happen.

**Comment by muffinresearch** [comment]
Thanks @jasonthomas I see we're clear on https://www.stopbadware.org/clearinghouse/search?url=https://outgoing.prod.mozaws.net/v1/.

Unfortunately Firefox is still showing the red screen having just re-tested. I'm not sure how our integration works but it might just be a matter of time before the update propagates.

**Comment by muffinresearch** [comment]
I'm still seeing the attack page report on the same profile I used the other day, albeit new profiles doen't seem to show the same issue. It's unclear to me what the update mechanism is for the attack page blocklist.

**Comment by muffinresearch** [comment]
@wagnerand have the errors cleared for you? I'm still getting the error for the profile I originally used to test this but I'm not sure if that's an isolated issue.

**Comment by MaDonnasPersonas** [comment]
Yes, the link works now for me and has since the day after I posted.

**Comment by wagnerand** [comment]
@muffinresearch I don't get the attack page anymore in neither main profile nor in a fresh profile.

**Comment by muffinresearch** [comment]
Great, thanks for the updates. Marking this as closed.
