### ISSUE TITLE
No source-code file available anywhere if added during new file submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4491]
Steps to reproduce:
1. While submitting a new file for an add-on add a `source code` file and finalize submission i.e https://addons.allizom.org/en-US/developers/addon/version-file-sourcecode/edit
2. Go to Manage version page and check if a source code file exists

Expected results:
If `source code` option is available while uploading a file, it should be listed in manage version page. If source code should not be available, then a message about this should not be listed in Review history link from DevHub or in Review page from Reviewer tools.

Actual results:
`Source code` option is available while uploading a new file for a version, but is not listed anywhere in manage version page, and **a message about this is listed** in DevHub and Reviewer Tools.

Notes/Issues:
Verified on FF50(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Video for this issue: 
![no-sourcecode](https://cloud.githubusercontent.com/assets/15685960/22330634/e343a56a-e3cf-11e6-9641-68b10b14c34b.gif)

**Comment by eviljeff** [comment]
> and a message about this is listed in DevHub and Reviewer Tools.

what's the message?

**Comment by ValentinaPC** [comment]
Test webext: https://addons-dev.allizom.org/en-US/developers/addon/test-source-file/edit
Screenshots with messages:
![dev_hub_msg](https://cloud.githubusercontent.com/assets/15685960/23906451/a9fd450a-08d6-11e7-969b-61cae171c5b9.png)
![revtools](https://cloud.githubusercontent.com/assets/15685960/23906452/aa01e54c-08d6-11e7-9706-414cfdf8abbd.png)

**Comment by eviljeff** [comment]
I just tried to replicate this with a random xpi and couldn't - can you still replicate?

**Comment by ValentinaPC** [comment]
> I just tried to replicate this with a random xpi and couldn't - can you still replicate?

Did you tried adding a source code while uploading a new FILE? This is my case, and yes, I can still reproduce it.

**Comment by eviljeff** [comment]
oh, a File specifically. I'm tempted to remove the option for Files.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7).
Source code file cannot be added for listed or unlisted add-ons during new file submission.
Postfix screenshots:
![newfile-unlisted](https://cloud.githubusercontent.com/assets/15685960/24403819/4403b332-13c7-11e7-8293-f3701cffd816.png)
![nosourcecodefile](https://cloud.githubusercontent.com/assets/15685960/24403820/440765c2-13c7-11e7-9efc-5fd9ecf475ce.png)
