### ISSUE TITLE
Mozilla Add-ons: HoFF - [Hide Offline Facebook Friends] 1.5.6 signed | Not Found

### ISSUE THREAD

**Issue by nar3nd3r** [mozilla/addons-server#4496]
### Describe the problem and steps to reproduce it:
I just happen to submit a web extension, which got auto approved, however I can't see it. Even I tried searching from add-on store.

### What happened?
I am not able to see it when clicked on the link (in the auto generated mailer)

### What did you expect to happen?
I was hoping to see my WebExtension (for editing and putting images and all)

### Anything else we should know?
![screen shot 2017-01-26 at 11 39 08 pm](https://cloud.githubusercontent.com/assets/3421680/22344084/aa7465c0-e420-11e6-9e68-70ad959a5958.png)

**Comment by wagnerand** [comment]
You submitted your add-on for distribution "on your own: Your submission will be immediately signed for self-distribution."

Such add-ons are by definition not listed on AMO.

As for clicking on the link. Are you signed in, as the email mentions?

**Comment by nar3nd3r** [comment]
Hi There,

Thanks for the quick revert.

however I was hoping for to put it on AMO, and I don't want to self host it (at least not for now). 👍 

Did I Miss any step while signing it, cause web-ext does not give me any more option to upload on AMO.

Moreover, I'm signed in (Developer Hub) using my credential and I can see both the add-on and web extension both under my dashboard. 

See below

![screen shot 2017-01-27 at 12 13 38 am](https://cloud.githubusercontent.com/assets/3421680/22345274/81952680-e425-11e6-9d7e-627204013729.png)

Please advise me, how can I put it on AMO.

Appreciate your help.

Thanks.

**Comment by wagnerand** [comment]
Ah, so if I remember correctly, web-ext defaults to using the self-hosted variant. You should be able to submit a new version (using the webpage, not web-ext), where the first step is to decide the channel (listed or self-hosted) you wan to upload it to. Just choose listed.

**Comment by nar3nd3r** [comment]
Got it, done. Thanks @wagnerand .

Looks good for now (under review, it's a long long queue, phew.. ).

https://addons.mozilla.org/en-US/firefox/addon/hide-offline-facebook-friends/

**Comment by wagnerand** [comment]
Yes, we are aware of that and doing our best to get it it as soon as we can. I'm sorry for the inconvenience.

**Comment by nar3nd3r** [comment]
Appreciate that 👍
