### ISSUE TITLE
Typo on new dev hub page

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4497]
https://addons.mozilla.org/en-US/developers/

"Firefox supports WebExtension APIs, which in most cases are compatible with the extension APIs supported by Google, Chrome and Opera, so your extensions will run in Firefox with just a few changes."

Is that meant to be "supported by Chrome and Opera" or "supported by Google Chrome and Opera" or how about "supported by Chrome, Opera and Edge"?

**Comment by devaneymoz** [comment]
Edit:

"Firefox supports WebExtension APIs, which in most cases are compatible with the extension APIs supported by Chrome, Opera, and Edge, so your extensions will run in Firefox with just a few changes."

**Comment by madalincm** [comment]
Verified in FF50 (Win7) Addons-dev.allizom.org The issue is still reproducing. Please have a look:
https://addons-dev.allizom.org/en-US/developers/
![devhubtypo](https://cloud.githubusercontent.com/assets/15685441/22365433/1fd4ee70-e480-11e6-90e2-2b4a3c806533.png)

**Comment by EnTeQuAk** [comment]
Works for me, maybe force reload because of caching or so? Or -dev deployment got stuck, not sure.

See screenshot attached.

![screenshot from 2017-01-27 12-18-17](https://cloud.githubusercontent.com/assets/139033/22369197/c356a200-e48a-11e6-80c3-3716b4f4f3b0.png)

**Comment by madalincm** [comment]
I think maybe was a problem with -dev at that moment. Looks good for me too now. Marking as verified fixed
![4497retest](https://cloud.githubusercontent.com/assets/15685441/22373754/e1eabaf0-e4ab-11e6-9846-fa8bcf082e59.png)
