### ISSUE TITLE
CSP Limit paypal img-src directive by path

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4507]
We currently have `https://www.paypal.com` listed in the img-src we can limit that further to just load the paths required so we're not open to everything under that origin.

**Comment by muffinresearch** [comment]
QA notes: to test this once it's landed - check that there's CSP violations for `img-src` for paypal when using contributions.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF51(Win 7) and there are **two** (required?) CSP violation when using contributions.
Screenshot: 
![ora12](https://cloud.githubusercontent.com/assets/15685960/22420667/3598a3c8-e6ec-11e6-8518-6b97156a55b7.png)

**Comment by muffinresearch** [comment]
Ah ok that's not right I think I erroneously added a slash to the logger path.

**Comment by muffinresearch** [comment]
@ValentinaPC I've landed a change to remove the slash you should no longer see those violations on dev once it's updated with that change.

**Comment by muffinresearch** [comment]
> QA notes: to test this once it's landed - check that there's CSP violations for img-src for paypal when using contributions.

That should have read "there's *no* CSP violations" I'll update it.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7).
Postfix video: 
![img-src](https://cloud.githubusercontent.com/assets/15685960/22428080/640218a8-e70e-11e6-9306-3c74344f8004.gif)
