### ISSUE TITLE
update API docs with mixed listed unlisted and is_listed changes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#4514]
We made some API changes to handle the change from addon's being unlisted or listed to versions and not all of them were documented at the time because it was going to be months before the changes were enabled on production.  Need to catch up!

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the "needs no qa" label. Thanks!

**Comment by eviljeff** [comment]
http://addons-server.readthedocs.io/en/latest/topics/api/signing.html mentions the channel but the changes are there so I guess I've just done the QA :)
