### ISSUE TITLE
Automatically ask users to consider migrating to WebExtensions and/or e10s compatibility

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#4518]
I'm currently using the following canned response in a few add-ons:

>Thank you for your contribution. For the next version, please consider testing for multiprocess compatibility. See https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox for more information. 
>
> You may also be interested to hear that Firefox now offers the WebExtensions API, which is similar to the Chrome Extension API. If you have a Chrome version of this add-on, it may just be a matter of testing that within Firefox. See https://developer.mozilla.org/en-US/Add-ons/WebExtensions for more details and http://arewewebextensionsyet.com/ for information on which APIs are supported.

To encourage users to switch without having to paste that each time, I'd like to propose to add this kind of response to the email on each approval/reject for add-ons that are not webextensions or not e10s compatible.

@jvillalobos @wagnerand what do you think?

**Comment by jvillalobos** [comment]
The current review emails templates are used for all add-ons indiscriminately, and I wouldn't want to change that for a temporary notification. We could add a note to the existing templates, which are sent to everyone, and reword it so it's clear it's a general thing.

Or maybe it would make more sense to add it to the top of developer hub pages of extensions that aren't WebExtensions.

**Comment by kewisch** [comment]
I think we should at least add a general note. We want to encourage folks to migrate to WebExtensions, and this is a kind of transactional email they will read. Maybe I am underestimating the effort, but it seems to me that splitting up a template based on a single db flag would not be that much work. We could go with just adding the note for non-WebExtensions and ignore e10s compatibility to make it easier.

**Comment by kewisch** [comment]
I spoke with Jorge and from a product standpoint this is a good idea. @eviljeff can you forsee how much work this would be on a technical level? From my naive understanding it would just be a matter of adding a variable to the template and then adding a the text in an if block in the template.

We decided that we should be encouraging WebExtensions but not specifically e10s.

**Comment by eviljeff** [comment]
Doesn't sound like a lot of work.  Can you do a sample email showing what you'd like the output to be, with appropriate copy?  Also, which email templates would it apply to?  We have a [few](https://github.com/mozilla/addons-server/tree/master/src/olympia/editors/templates/editors/emails) or it can be in `base.ltxt` and be in all of them.

**Comment by jvillalobos** [comment]
I think adding it to `base` makes sense. I suggest adding it after the `To learn more about the review process` line:

> To ensure your add-ons are compatible past Firefox 57, please migrate them to WebExtensions as soon as possible: https://mzl.la/1RzETMA

**Comment by manvideo** [comment]
Please send my imail language Persian I don't red English if not Persian
please don't send

**Comment by ValentinaPC** [comment]
Verified as fixed on mail client (Yahoo) and Admin Tools - Fake Email - Logs using AMO-dev FF52(Win 7) and the message about migrating to WebExtensions is displayed. Also displayed while add-on update or rejection.
Not displayed for WebExtension review.
Postfix screenshots: 
![2017-03-28_1403](https://cloud.githubusercontent.com/assets/15685960/24402309/9f8f63e2-13c0-11e7-9792-92055f3364bb.png)
![yahoo](https://cloud.githubusercontent.com/assets/15685960/24402310/9f9328ba-13c0-11e7-9268-2033baccd9cd.png)
