### ISSUE TITLE
image-missalignment on signed-in DevHub landing page (in some languages)

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#4526]
Go to the new DevHub landing page, see the What's New section on top, change language to German. Notice that the rocket on the left side is not starting from the corner of the What's New section anymore.

See language comparison:
![devhub-whatsnew-image-missalignent-language](https://cloud.githubusercontent.com/assets/8145891/22427032/d1c74bae-e701-11e6-8523-2d13f1a91460.gif)

I expected the rocket to always start from the bottom left corner of the What's New block. (Potentially it would shrink if the block is not high enough...)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7).
Postfix screenshot (i.e. it):
![it](https://cloud.githubusercontent.com/assets/15685960/22502805/3a599fc0-e877-11e6-8a6c-31e032bc9384.png)
