### ISSUE TITLE
"Request review" link is removed while changing details for a version with incomplete submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4527]
Steps to reproduce:
1. Submit a listed versions but stop at add-on details step during submissions (**click "Cancel Review and Disable Version"**)
2. Click on version number and change something for that version: release notes, platform, etc.
3. Save changes and go back to "Manage Status & Versions" page
4. Observe the version

Expected results:
The "Request review" link is still displayed.

Actual results:
The "Request review" link is no longer displayed.

Notes/Issues:
Submission cannot be finalized anymore for that version.
Verified on FF51(Win 7). Issue is only reproducing on -dev.
Video for this issue: 
![nomorelink](https://cloud.githubusercontent.com/assets/15685960/22427502/1ea894b4-e70c-11e6-9db0-b503bdbdb584.gif)

**Comment by eviljeff** [comment]
https://addons-dev.allizom.org/en-US/developers/addon/no-mor-request-link/versions

**Comment by eviljeff** [comment]
Think I've got to the bottom of why the link isn't there - we only show it for the 'latest_version' and a rejected version can't be 'latest'.  As for why it's there just after you cancel, that's a flaw in how we're cancelling the review that isn't resetting the cached latest_version value (being fixed in another issue)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7)
The "Request Review" link is not deleted after editing add-on version.
Postfix screenshot: 
![2017-02-03_0922](https://cloud.githubusercontent.com/assets/15685960/22583945/6261f8b4-e9f8-11e6-82cb-a063e681847c.png)
