### ISSUE TITLE
no Firefox logo on DevHub landing page

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#4531]
When going to https://addons.mozilla.org/developers/ I was briefly puzzled about what browser that pages belongs to as there is no Firefox logo on the page but a Chrome and Opera logo.

I expected to also see a Firefox Logo to reassure me that this page is for developing for Firefox.

Maybe something like this might help:
![screen-shot-2017-01-30-at-19 06_2](https://cloud.githubusercontent.com/assets/8145891/22436598/0f8bba60-e725-11e6-9617-a7c3ab3798a2.png)
(or maybe that is too obvious.)

**Comment by brampitoyo** [comment]
There are multiple solutions we might consider:

* Adding the word “Firefox” in front of “Add-on Developer Hub”
  * The concern here is whether we want this site to change name, and whether this change makes us sound less inclusive to developers trying to port from Chrome. Our messaging so far has been “With WebExtensions, you code once and deploy everywhere”, so why does the developer page imply that it’s exclusive to Firefox?
* Add some sort of a Firefox or Mozilla mark to the logo
  * MDN has the same issue: how to make a site that’s only partially about Firefox (and mostly about the open web) looks like it “belongs” to Mozilla? I think their logo have helped.
* Add a Firefox graphic somewhere on the website (Markus’ example up above)

What’s your thought on these approaches?

/cc @fangshih

**Comment by fangshih** [comment]
I agree with both of you, for this part of the illustration, we wanted to let them know that with WebExtensions, it runs everywhere, not exclusive to Firefox, but works anywhere. So I was wondering if we want to reassure also works for Firefox, maybe we can be part of the group, surrounding this WebExtensions tool within other browsers. something like this? So it won't feel too exclusive but also be part of it?
![2017-02-03 4 13 40](https://cloud.githubusercontent.com/assets/4862573/22584359/f564462e-ea2c-11e6-9c94-7c625a2c0697.png)

**Comment by brampitoyo** [comment]
The only change I’d suggest is to exchange the position of the Chrome and Firefox logo, so Firefox becomes the more important graphic element on the page. Other than that, I think it’s good to go!

What do you think?

**Comment by designakt** [comment]
That would be great. It would still convey that you can port a Chrome or Opera extension, but put the focus on Firefox.

**Comment by brampitoyo** [comment]
Another approach that @pwalm had suggested was to greyscale the other two browser logos in order to further emphasize Firefox.

@fangshih If it looks too much grey on grey, then maybe try desaturating the logo by 50%.

**Comment by EnTeQuAk** [comment]
Is there any update on this that needs or can be implemented by us?

**Comment by pwalm** [comment]
@fangshih @brampitoyo Any way we can update these files?

**Comment by fangshih** [comment]
Hey, Just updated the image and assets based on our discussion
Here is the SVG asset: 
https://www.dropbox.com/s/05b6oqh5yq189td/image-port-extension.svg?dl=0 
Thanks! 
![landing page - not signed in with sidebar - visual design](https://cloud.githubusercontent.com/assets/4862573/24180897/8af76b0a-0ef2-11e7-989b-96b42a5fb360.png)

**Comment by brampitoyo** [comment]
I like it. Thank you, @fangshih!

**Comment by pwalm** [comment]
Great work, @fangshih ! 😄

**Comment by muffinresearch** [comment]
Here's the svg in a zip just in-case the dropbox link goes away.

[image-port-extension.svg.zip](https://github.com/mozilla/addons-server/files/1690785/image-port-extension.svg.zip)

**Comment by designakt** [comment]
I updated the logo in that file to the new Firefox Quantum one.
[image-port-extension_quantum.zip](https://github.com/mozilla/addons-server/files/1698984/image-port-extension_quantum.zip)
![image-port-extension_quantum_preview](https://user-images.githubusercontent.com/8145891/35859558-826a11de-0b38-11e8-80e1-851c88b50eb5.PNG)

**Comment by ddurst** [comment]
(I don't know whom to ask, @pwalm? @brampitoyo?) Is there any plan to address branding -- bringing back to the MDN comparison in [#issuecomment-276210252](#issuecomment-276210252)?

**Comment by brampitoyo** [comment]
@ddurst I wonder what @pwalm would think of this idea, but we can slightly alter the existing logo on AMO and use it on DevHub, like so:

[Firefox logo] Add-ons Developer

or [Firefox logo] Add-ons Developer Hub

We remove the word “Firefox”, because it would unnecessarily lengthen the wordmark. Just the Firefox logo is enough to signal the fact that it belongs to Mozilla.

Thoughts?

**Comment by pwalm** [comment]
I think we have to keep "Firefox" as it is part of our overall branding and shouldn't be dropped. So it would be:

[Firefox logo] Firefox Add-ons Developer Hub

Kind of a mouthful, but that's what we've ended up with!

**Comment by brampitoyo** [comment]
@pwalm Sounds good. If you have a logotype vector file handy and haven’t got the time to refit the type, I’d be happy to do that and post the SVG + PNG here!

**Comment by wagnerand** [comment]
@ddurst could we split the headline changes into a different issue, please? 

I'm going to update the image as per https://github.com/mozilla/addons-server/issues/4531#issuecomment-363406568, which is good to go, but it seems the other task needs some more work.

**Comment by vcarciu** [comment]
Verified as fixed : 
![logodevhub](https://user-images.githubusercontent.com/1583842/36482158-fdc16736-171a-11e8-9d9d-9a2dc6bc24e8.png)
