### ISSUE TITLE
Signing Put Results in 301 Moved Permanently 

### ISSUE THREAD

**Issue by Akkuma** [mozilla/addons-server#4532]
### Describe the problem and steps to reproduce it:
I've attempted to use the put [signing API](http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version) and only receive a 301, which doesn't help me understand what the problem actually is. I've tried several different variations of URL:

* https://addons.mozilla.org/api/v3/addons/virtrufirefox@virtru.com
* https://addons.mozilla.org/api/v3/addons/virtrufirefox@virtru.com/versions
* https://addons.mozilla.org/api/v3/addons/virtrufirefox@virtru.com/versions/4.0.5 (matches package.json)
* https://addons.mozilla.org/api/v3/addons/virtrufirefox@virtru.com/versions/4.0.5.1

I can successfully use the post signing API and see the extension created and signed on the developer hub, which means my authentication should not be an issue.

Additionally, I've tried using the guids as the ids to see if the old non-guid uuid was the issue and they too 301.

### What happened?
Receive a 301 with no information on what is wrong

### What did you expect to happen?
Upload a new version to be automatically signed

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Akkuma** [comment]
It would be great if someone would at least let me know if this is a problem on my end or a problem from the addon-server's API.

**Comment by jvillalobos** [comment]
@muffinresearch Do you know what could be going on here?

**Comment by mstriemer** [comment]
I'm not sure what's going on here. What's the `Location` header in the 301 response?

Do other API requests work? Have you tried accessing the profile endpoint [1] to verify authentication is working correctly?

[1] https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#profile

**Comment by Akkuma** [comment]
@mstriemer I said it up in the issue 

> I can successfully use the post signing API and see the extension created and signed on the developer hub, which means my authentication should not be an issue.

I'll check what the location is showing

**Comment by muffinresearch** [comment]
@Akkuma can you see what happens if you add the trailing slash in your original request?

**Comment by Akkuma** [comment]
@muffinresearch I verified using a trailing slash fixes the issue. There is a separate issue that the documentation doesn't really clarify that a trailing slash is mandatory, which seems strange. Also the API seems weird when the documentation mentions `version` as part of the body, but it doesn't do anything.

**Comment by muffinresearch** [comment]
@Akkuma ok thanks for checking- I'll close this one in favour of the new one you opened.
