### ISSUE TITLE
Add "Add-on Unlisted Review" link to devhub for add-ons with unlisted versions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4536]
Steps to reproduce:
1. Submit an unlisted add-on i.e. https://addons-dev.allizom.org/en-US/developers/addon/no-more-review1/versions
2. Click "Add-on Review" link
3. Observe "Add-on history" section

Expected results:
After the page title an "unlisted" note will be listed. History about automatic validation, platforms, content, etc. is displayed.

Actual results:
No "unlisted" note after "Review add-on_name" page title. No add-on history.

Notes/Issues:
- If a Request more information/Request super-review is added from that page - 500 error page is displayed. (Comment works as expected)
- If the add-on is searched in the "All Unlisted queue", it is found and after is accessed all usual info about add-on review history are listed.
- Works as expected for add-on with mixed versions.
Verified on FF51(Win 7). Issue is reproducing on AMO-dev and -stage.
Screenshot for this issue: 
![noreviewhistoryforunlisted](https://cloud.githubusercontent.com/assets/15685960/22459540/aecd46d2-e7a9-11e6-9135-11304b27965e.png)

**Comment by eviljeff** [comment]
you want https://addons-dev.allizom.org/en-US/editors/review-unlisted/no-more-review1 for unlisted review history - it's a different page

**Comment by ValentinaPC** [comment]
@eviljeff : Well, I was thinking, if while submitting a listed add-on (all versions listed - example: https://addons-dev.allizom.org/en-US/developers/addon/no-more-request-beta/edit ) and clicking on "Add-on Review" link from DevHub will redirect you to a page with review history, why not the same results for all versions unlisted add-on?

**Comment by eviljeff** [comment]
I agree with your thinking, but that's not the current functionality.  You could change the issue to change/add the link I guess.

**Comment by ValentinaPC** [comment]
> I agree with your thinking, but that's not the current functionality. You could change the issue to change/add the link I guess.
You say "link" but I am referring to a section from Reviewer Tools, while clicking "Add-on review" link from Dev Hub.
The "Review History" link from Dev Hub - exists.
Please see the video (I've also added the oops issue):
![nohistory oops](https://cloud.githubusercontent.com/assets/15685960/22471753/f7531daa-e7db-11e6-8d36-db1105199e1f.gif)

**Comment by eviljeff** [comment]
No, it's literally a different review page.

**Comment by ValentinaPC** [comment]
So.... this page, that is accessed after I click "Add-on Review" link, should not exist, and the link should redirect to https://addons-dev.allizom.org/en-US/editors/review-unlisted/no-more-review1 . 
I'll change this issue... somehow...

**Comment by eviljeff** [comment]
the page should exist, and there shouldn't be a redirect (#3989), but the unlisted review page should be linked to as well/instead of.  I updated the title.

**Comment by ValentinaPC** [comment]
@eviljeff : Unlisted Review page link should be available in Dev Hub even if the submitted add-on is listed?

**Comment by eviljeff** [comment]
both links are always visible.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF52(Win 7).
There are 2 cases:
1. Submit listed add-on (only listed versions) - 2 links (expected) - "Unlisted Review Page" loads a page from where a comment can be added but does not appear anywhere (I guess I can live with this)
2. Submit an unlisted add-on (only unlisted versions) - 2 links (expected) - "Listed Review Page" loads a page from where a comment can be added; comment is displayed on that page with incorect notes in Add-on History section:
![incorrect](https://cloud.githubusercontent.com/assets/15685960/24039138/b9480b5c-0b0c-11e7-9af0-7b5a7e8f9c68.png)
- version was not deleted (did not exist at all)
- "files in this versions" - but no files

Should I mark this verified fixed, as the initial purpose of this was fulfilled and log another issue for point 2, or no?
Thanks!

**Comment by eviljeff** [comment]
Leaving comments on an add-on with no versions (or in this case, no versions of the correct channel) is basically unsupported behaviour (that it works at all is surprising). 
I'm not sure filing an issue is worthwhile as realistically its such an edge case it won't be fixed.  Might be picked up with #4760 though.

**Comment by ValentinaPC** [comment]
Marking this verified-fixed.
