### ISSUE TITLE
Disable codecov, delete it once and for all

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4538]
Codecov is hitting our nerves and it's not being used at the moment anyway. We should but we aren't and we can think about this at a later point once we have resources to take care of this.

Can we delete it? https://codecov.io/gh/mozilla/addons-server Apparently it started commenting on our pull requests again 👎 This needs an admin user unfortunately (or fortunately :D)

**Comment by muffinresearch** [comment]
I've disabled the webhook - feel free to re-open this and let me know if that's not enough.
