### ISSUE TITLE
Disco Pane content update - Feb. 2017

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#4546]
For the **16 February** push, can we please REMOVE:

- OmniSidebar
- all three current themes

... and REPLACE them with Video DownloadHelper and three new themes.

**Download videos** 
with [Video DownloadHelper by mig](https://addons.mozilla.org/firefox/addon/video-downloadhelper/)
Easily grab videos from YouTube, Dailymotion, Facebook, and most other video sites with this simple download tool.

[themes]

Books [by Josterix](https://addons.mozilla.org/firefox/addon/color-books/)
Yellowfield [by g650609](https://addons.mozilla.org/firefox/addon/yellowfield-1/)
Fon615 [by levscaya16](https://addons.mozilla.org/firefox/addon/fon615-by-levscaya/)

Also, could we please change up the ordering of content? Full lineup to look like so:

Books [theme]
Video DownloadHelper
uBlock
Yellow field 1 [theme]
Enhance YouTube
Emoji Keyboard
Fon615 [theme]

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF51(Win 7)
Postfix screenshot:
![untitled](https://cloud.githubusercontent.com/assets/15685960/23302551/d3af4062-fa97-11e6-9786-dafb3df23a8e.png)
