### ISSUE TITLE
Small issue in "What's New" section in other languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4550]
Step to reproduce:
1. Being logged access Dev Heb page: https://addons-dev.allizom.org/en-US/developers/
2. Change the language to -de: https://addons-dev.allizom.org/de/developers/
3. Observe the "What's New" section

Expected results:
There are no display or layout issues.

Actual results:
The "Learn How" button is overlaying a bit the cube from the background picture.

Notes/Issues:
Verified on FF51(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue:
![de](https://cloud.githubusercontent.com/assets/15685960/22502997/2aba46c2-e878-11e6-8d07-cf8dd885a639.png)

**Comment by muffinresearch** [comment]
It's a background image and as such the foreground elements may overlap in some scenarios and I think that's fine.
