### ISSUE TITLE
Same names for categories in search suggestions can be confusing

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4551]
Steps to reproduce:
1. Load https://addons.allizom.org/en-US/firefox/
2. Search for "Bookmarks"

Expected results:
"Bookmarks" add-on category is displayed.

Actual results:
Two identical "Bookmarks" categories are listed.

Notes/Issues:
- one "Bookmarks" category is an add-on category, the other is a Search Tools category
- same happens if searching for "Sports" in Search Tools page (one category is a CT category and one is a Search Tools category)
User can be confused.
Verified on FF51(Win 7). Issue is reproducing on all AMO servers.
Screenshot for this issue: 
![categories](https://cloud.githubusercontent.com/assets/15685960/22504676/3e1a29e6-e880-11e6-818e-5b92b457121f.png)
![sports](https://cloud.githubusercontent.com/assets/15685960/22504677/3e2053ac-e880-11e6-95a9-53c1a9baccbb.png)
All categories (if helps):
![all](https://cloud.githubusercontent.com/assets/15685960/22504690/4d55a480-e880-11e6-883e-65c1cf1ec0ba.png)

**Comment by diox** [comment]
Unlikely to be fixed before addons-frontend re-implement desktop.
