### ISSUE TITLE
Filebrowser incorrectly shows line contents as "undefined"

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#4552]
### Describe the problem and steps to reproduce it:
* Go to https://addons.mozilla.org/en-US/firefox/files/compare/582238...566147/file/diffworker.diff
* See lots of "undefined" lines.

### What happened?
Aside from the fact that including this file was accidental, it does actually have readable content. Maybe it is because it is a patch file?

### What did you expect to happen?
The file contents should correctly be displayed.

**Comment by wagnerand** [comment]
Showing the wrong content of a file is pretty much as bad as not showing the file at all (and we had that case before), marking as P1.

**Comment by wagnerand** [comment]
Downgrading to P2 as per @EnTeQuAk's request, but we still need this to be solved asap (next week at the latest).

**Comment by vcarciu** [comment]
Verified as fixed : 
![noundef](https://cloud.githubusercontent.com/assets/1583842/22693946/fe75ba94-ed4d-11e6-8fa1-6c10497e0fe9.png)

**Comment by wagnerand** [comment]
This screenshot looks odd. @vcarciu would you mind providing the link where you see that? Thanks!

**Comment by wagnerand** [comment]
Confirming this is fixed based on a test with the real diff file. (It seems @vcarciu got a html page instead of the actual diff file)

![screen shot 2017-02-08 at 11 02 49](https://cloud.githubusercontent.com/assets/873258/22732478/999b0100-edee-11e6-8e3b-79a06adb4b7f.png)
