### ISSUE TITLE
Add a button in the last step of unlisted submission flow to access add-on manage page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4557]
Steps to reproduce:
1. Submit an unlisted add-on in AMO-stage: https://addons.allizom.org/en-US/developers/addon/submit/distribution
2. Finalize the submission flow
3. Access add-on manage page

Expected results:
There is an "Manage Listing" button that redirects the user to add-on manage page.

Actual results:
The user cannot access add-on manage page from that point.

Notes/Issues:
If the user wanna add a new version, or just want's to access add-on manage page has to : 
- go Manage My Submission page
- sort the add-ons by created to find your add-on
- click "New Version" or "Manage Status & Versions" links  

Verified on FF51(Win 7). Issue is reproducing all around AMO servers.
Screenshot:
![2017-02-01_1842](https://cloud.githubusercontent.com/assets/15685960/22516506/ae11e3a0-e8ae-11e6-923f-4b6fc0165965.png)

**Comment by eviljeff** [comment]
@jvillalobos for comment because these screens are exactly as you and ux designed.

**Comment by jvillalobos** [comment]
Haven't heard any complaints about this one. While possible, I don't think it's likely that you need to go to the management page after uploading an unlisted version. What you generally want is just get the signed file.
