### ISSUE TITLE
[Dev Hub] Spacing between Latest News and Tools on signed out page should be larger

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#4561]
When signed out of the Dev Hub landing page, the space between the Latest News and Tools columns should be larger.

Expected spacing (from mockup): https://www.dropbox.com/s/eridgdu8pwwnu4t/Screenshot%202017-02-01%2015.36.13.png?dl=0

Screen shot from production: https://www.dropbox.com/s/l21pwr5202dhqm2/Screenshot%202017-02-01%2015.33.51.png?dl=0

**Comment by muffinresearch** [comment]
This was already fixed - here's a screenshot on stage:

![developer_hub____add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/22556032/b008b850-e95d-11e6-80f1-08c588b829f5.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![spacenewstools](https://cloud.githubusercontent.com/assets/1583842/22556378/9a3b37b6-e96f-11e6-8409-58c1043e619c.gif)
