### ISSUE TITLE
Theme submission is not working for "ar" language

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4564]
Steps to reproduce:
1. Go to Create a New Theme page in AMO-stage
2. Change the language to `ar` https://addons.allizom.org/ar/developers/theme/submit
3. Complete all mandatory fields and submit you theme

Expected results:
The theme is submitted with success.

Actual results:
The theme cannot be submitted.

Notes/Issues:
- while entering the Name for the theme, URL field is not automatically filled.
- after selecting a picture for theme header, is not previewed at the end of the submission form.
- issue is not reproducing for the other RTL lang: `fa`
  
Verified on FF51(Win 7). Issue is reproducing all around AMO servers.
Video for this issue:
![themesubmission](https://cloud.githubusercontent.com/assets/15685960/22540272/f5c37f0a-e927-11e6-8e83-70af70d281c9.gif)

**Comment by muffinresearch** [comment]
Looks like this might be related to missing plural forms again. 

I see this in the console: `uncaught exception: Format string is empty!` I'll investigate further and see what can be done. 

If it is what I think it is a change is also needed to ensure that the format func doesn't blow-up when missing plural forms like this in future. Also validating the localisations might help with this.

**Comment by muffinresearch** [comment]
Digging into this further it's a django bug.

The current js ngettext function provided by django returns "" when we don't have a plural form. This then causes our format function to throw.

Changing that function to look like this fixes it so it returns the english string instead when a plural form cannot be found in the catalog:

```js
window._ngettext = function (singular, plural, count) {
  var value = django.catalog[singular];
  var trans; 
  if (typeof(value) !== 'undefined') {
    trans = value[django.pluralidx(count)];
    if (trans && trans.length > 0) {
      return trans;
    }
  }
  return (count == 1) ? singular : plural; 
};
```

Here's a js bin demonstrating the fix with our real AR catalog. http://jsbin.com/yizenicuki/edit?js,console

**Comment by muffinresearch** [comment]
I'd be somewhat surprised if there aren't other django users being hit by this issue so are we doing something different re: the creation of our po files?

**Comment by muffinresearch** [comment]
On irc @diox noted this bug https://code.djangoproject.com/ticket/27418 which has landed in https://github.com/django/django/commit/b24af2f40508bc0d8aa0cef264e51c537ffb92bd

**Comment by muffinresearch** [comment]
@ValentinaPC the patch for this is now on -dev.

**Comment by vcarciu** [comment]
Verified as fixed : 
![rtlthemear](https://cloud.githubusercontent.com/assets/1583842/22559949/781008ae-e97b-11e6-8fb3-c13641bf05be.gif)

Verified also for add-ons submissions
