### ISSUE TITLE
Add-ons installation fails on stage with the Blocked add-on error message

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#4565]
### Steps to reproduce:
1. Create xpinstall.signatures.dev-root and set it true in about:config
2. Open Tap Translate add-on in stage and tap the Add to Firefox button

### Expected results:
The add-on can be installed

### Actual results:
The add-on can't be installed. "Firefox has prevented addons.allizom.org from installing an unverified add-on"

### Notes/Issues
Verified in FF50 (Android 6.0.1 and Android 7.1.1) in addons-allizom.org
![screenshot_20170202-115615](https://cloud.githubusercontent.com/assets/15685441/22544896/5db9a186-e93f-11e6-99b1-36d2568da0dc.png)

**Comment by EnTeQuAk** [comment]
@jasonthomas what certificates are used on -stage, is this bug maybe related to that? Doesn't sound too AMO related to me though but I'm not sure.

**Comment by jasonthomas** [comment]
This add-on on stage is not signed. Although I am not sure why it was not, it's possible that we didn't run bulk signing on android add-ons on stage? Looks like it was signed on prod.

`stage: 14K Jul 25  2014 tap_translate-0.3.0-an-android.xpi`
`prod: 18K Jan 28  2016 tap_translate-0.3.0-an-android.xpi`

**Comment by jasonthomas** [comment]
I've signed add-ons on stage.
