### ISSUE TITLE
Javascript errors on /developers/

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4568]
Looking at the console I notice there's a couple of errors on the developers page:

```
 ReferenceError: gettext is not defined[Learn More]
 TypeError: $(...).installButton is not a function[Learn More]
```

I think this is possibly due to missing the i18n js bundle and maybe some others.  It's not related to #4564 afaict.

See https://addons.mozilla.org/en-US/developers/ applies to all locales and logged-in and logged-out.

**Comment by ValentinaPC** [comment]
Verified both `/developers` pages (logged in and out) for all available locales and there is no `js` error in the console. There are some `CSS` errors and some `CSP` warnings, but nothing `js` related.
Postfix screenshot - `fr` locale example:
![fr_ex](https://cloud.githubusercontent.com/assets/15685960/22639130/276ae55e-ec55-11e6-98af-31795f5e0b57.png)

**Comment by muffinresearch** [comment]
@ValentinaPC thanks for that from that console looks like we're blocking the loading of some font formats due to cors missing. I'll file a separate issue for that.
