### ISSUE TITLE
 "e10s" is accepted as a minversion for Add-ons

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#4570]
(transfered from https://github.com/mozilla/addons-linter/issues/1004)

1. Submit an add-on with `minversion` "e10s" i.e. https://addons-dev.allizom.org/en-US/firefox/addon/resurrect-pages-testminvers/

Expected results:
Submission is blocked at validation with a message of no such Firefox version.

Actual results:
User can submit and install the add-on.

Notes/Issues:
**Any value** listed in Manage Status & Version->Manage Version->Compatibility Firefox dropdown is accepted by linter, even if the value is not a Firefox version. 
Also those values not coincide with the values listed in https://addons.mozilla.org/en-US/firefox/pages/appversions/, and they should.
Verified on FF49(Win 7). Reproducing on AMO-stage and dev.
Screenshot for this issue: 
![2016-10-21_1118](https://cloud.githubusercontent.com/assets/15685960/19591864/cb693e04-9781-11e6-839d-2bd41a0b8047.png)

**Comment by eviljeff** [comment]
This doesn't seem reproducible on prod.  I think someone just added "e10s" to the appversions on dev/stage https://addons-dev.allizom.org/en-US/firefox/pages/appversions/.  (Or e10s was deleted from prod at some point manually and wasn't on dev/stage)
