### ISSUE TITLE
Warning for unsaved text in "Localize for" section is very ugly

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4571]
Steps to reproduce:
1.Login to AMO and go to account settings
2.In _Localize for_ section, add some text
3.Change the language from drop down list
4. Observe the warning for unsaved text 

Expected results:
Unsaved text warning is displayed without UI issues

Actual results:
Unsaved text warning is very ugly

Notes:
Reproducible on all servers

Please see video for this bug : 
![uglyunsaved](https://cloud.githubusercontent.com/assets/1583842/22557329/ef34cefa-e972-11e6-9455-1b212829ab2e.gif)

**Comment by jvillalobos** [comment]
This dialog is pretty terrible, but probably not worth fixing with the old frontend. For now I think we just need to make sure there's proper spacing between the buttons.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by psionikangel** [comment]
I think I have a working fix for this bug. You can see it here https://github.com/psionikangel/addons-server/commit/775c0c661ae9c54ecf1eb35abd9d979f3d0ddddc

This is what it looks like in my dev environment:
<img width="570" alt="screen shot 2017-04-17 at 17 07 34" src="https://cloud.githubusercontent.com/assets/547413/25105495/d3d39056-2392-11e7-9303-ab6aad2ebd85.png">

If you think that would be fine, we could work together to eventually get this change merged.

Regards,

Jérémie

**Comment by eviljeff** [comment]
@psionikangel great, can you submit a pull request with your commit?  Reference this issue (`#4571`) in the pull request summary so it links together.

**Comment by psionikangel** [comment]
@eviljeff And done. The pull request is created https://github.com/mozilla/addons-server/pull/5222

**Comment by vcarciu** [comment]
Verified as fixed : 
![modals](https://cloud.githubusercontent.com/assets/1583842/25328719/a3c9122e-28e1-11e7-91f7-e331bee6a216.png)
