### ISSUE TITLE
Back button will not bring back previously selected language for AMO

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4572]
Steps to reproduce:
1.Go to  https://addons.allizom.org/en-US/firefox/
2.From _Other languages_ , select any other language
3.Press Back button

Expected results:
Language from step 1 is selected in the list after pressing back

Actual results:
Back button will not bring back previously selected language and if you select again the language from Step 2 , it will not work

Notes:
Reproducible on all servers

Please see video for this bug : 
![languageback](https://cloud.githubusercontent.com/assets/1583842/22557693/f3d5b694-e973-11e6-8846-4e33e4dcb7ad.gif)

**Comment by muffinresearch** [comment]
This is a side effect of form state being maintained by default in the browser and that the language change only applies when the select changes.

**Comment by EnTeQuAk** [comment]
This can and should be fixed by addons-frontend once it implements this feature. Given that the language selector is super old and messy, let's not touch it.

**Comment by ValentinaPC** [comment]
@EnTeQuAk : I am able to reproduce this **on device** under FF52(Android 6.0.1). 
While the language selector from desktop will be "fixed" with the new frontend, this fix will also propagate on device?

**Comment by EnTeQuAk** [comment]
I do think so, yes. Otherwise it's a bug imho that needs fixing in addons-frontend. Mind filing a bug there?
