### ISSUE TITLE
Resume link is not underlined anymore and its greyed out when hovering

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4574]
Steps to reproduce:
1.Go to AMO -dev and in _Manage My submissions_ observe add-on in an incomplete state
2.Hover over Resume button

Expected results:
Resume button is blue and underlined while hovering on it

Actual results:
Resume button is greyed out and not underlined while hovering

NOTES:
Not reproducible on Stage
Distance between Resume and Delete buttons is different now 

Please see video for the bug:
![resumebutton](https://cloud.githubusercontent.com/assets/1583842/22562806/c3e419cc-e986-11e6-9d4d-ac23c63b3a25.gif)

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by lavish205** [comment]
I would like to work on this bug, @eviljeff can you please provide some information to start with this bug?

**Comment by eviljeff** [comment]
@lavish205 thanks.
This should be just a css change.  I changed the Resume 'link' to actually be a button, which meant it lost some styling.  It's specified here https://github.com/mozilla/addons-server/blob/master/static/css/devhub/listing.less#L120:L130 and it might just be a matter of adding something similar to https://github.com/mozilla/addons-server/blob/master/static/css/devhub/listing.less#L163:L165 - might need some trial and error and tinkering in the dev tools first.

**Comment by lavish205** [comment]
@eviljeff What I understand is, I need to add blue color to `button.link` and add `text-decoration: underline` for hover property.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/blob/master/static/css/devhub/listing.less#L116 I think

**Comment by apoorvasingh17** [comment]
Hi, can I work on this?

**Comment by EnTeQuAk** [comment]
I'm not sure if @lavish205 is currently working on this, if not, sure @apoorvasingh17 go for it!

**Comment by apoorvasingh17** [comment]
@EnTeQuAk Thank you :)
Where can I find the guidelines to set up the environment?

**Comment by EnTeQuAk** [comment]
@apoorvasingh17 you can find everything you need in http://addons-server.readthedocs.org/en/latest/topics/install/docker.html and the already mentioned https://wiki.mozilla.org/Add-ons/Contribute/Code#Improve_addons.mozilla.org_.28AMO.29

**Comment by PhillypHenning** [comment]
Hey, I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by eviljeff** [comment]
It's been a month so I don't think @apoorvasingh17 is still working on it.  So go ahead.

**Comment by 16116073** [comment]
Hey, I am a college student and wish to learn open source. I wish to contribute here, I have already set up the development environment. I would like to work on this issue.

**Comment by eviljeff** [comment]
Lots of people are interested but no-one seems to proceed further.  Shouldn't be complicated so just shout up when you've got the fix ready.

**Comment by 16116073** [comment]
@eviljeff, I wanted to see the changes I make on my local machine for that do I have to submit new addonn. Because without that the "Resume" does not appear.
(https://user-images.githubusercontent.com/25207205/33284086-df5a0508-d3d3-11e7-83ae-06407eb5024c.png)

**Comment by eviljeff** [comment]
@16116073 yes you need to start submitting an addon with a listed version and get to the details step

**Comment by 16116073** [comment]
Does this mean that i have to make a new addon web extension, upload it and
then go for correcting the bug.

**Comment by eviljeff** [comment]
@16116073 yes you need to start submitting an addon with a listed version and get to the details step

**Comment by 16116073** [comment]
the extension i tried to upload it works well in "about: debugging" but when i upload it on addons it shows me a error 
My approach:
the bug is in the file 
/src/olympia/devhub/templates/devhub/addons/listing/items_actions.html

**Comment by VishalCR7** [comment]
@eviljeff  please review the pr #7231 regarding this issue.

**Comment by kumar303** [comment]
This was fixed in https://github.com/mozilla/addons-server/pull/7231

**Comment by vcarciu** [comment]
Verified as fixed : 
![resumeunderlined](https://user-images.githubusercontent.com/1583842/34820572-9bb8ffa2-f6c9-11e7-90fa-e53bd1f53dfc.gif)

**Comment by Obtin** [comment]
Hello there,

I just signed the petition ".@jairamthakurbjp @prahladspate : PETITION TO
PROTECT TOURISTS IN HIMACHAL PRADESH" and wanted to see if you could help
by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/2RQvpq9jmR

Thanks!
Tina
