### ISSUE TITLE
No way to get back to AMO homepage from Dev Hub new landing page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4580]
Prerequisites:
User is log out.

Steps to reproduce:
1. Load Developer Hub pages https://addons-dev.allizom.org/en-US/developers/
2. Go back to AMO homepage

Expected results:
There is a link or a button that redirects the user to AMO homepage.

Actual results:
User cannot go back to AMO homepage.

Notes/Issues:
Issue is also reproducing for logged in view, because there is no back to homepage button, either. (a new user will not guess that clicking on profile picture redirects him to AMO)
Verified on FF51(Win 7).

**Comment by muffinresearch** [comment]
Maybe adding it to the footer would work but if that happens bear in mind the bottom footer is not shown on mobile viewports currently (see #4693)
