### ISSUE TITLE
Some RTL issues during and after theme submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4581]
Steps to reproduce:
1. Sign in to AMO-dev and change the language to a RTL one 
2. Submit a theme (access edit theme page after submission) - https://addons-dev.allizom.org/ar/developers/theme/submit

Expected results:
There are no display or layout issues.

Actual results:
There are some RTL issues.

Notes/Issues:
_If we have a reviewer that it is a RTL language speaker, let's give him the possibility to approve a theme - because of the theme preview that overlays the commit section - he cannot.
Example: https://addons-dev.allizom.org/ar/editors/themes/queue/single/my-test-theme-of-win_ 

Verified on AMO-dev FF51(Win 7).
Screenshots:
![rtl themes](https://cloud.githubusercontent.com/assets/15685960/22592379/33fad142-ea22-11e6-9025-fd77d825f2aa.png)

**Comment by pranaygupta36** [comment]
I would like to take this issue up.

**Comment by muffinresearch** [comment]
@eviljeff since the new static theme wizard will eventually replace this do we need to keep this open?

**Comment by eviljeff** [comment]
It would still be nice to fix, I guess, but it's been open a year and not fixed so probably not going to happen static themes replace it.  Lets close it.
