### ISSUE TITLE
Followers number is not modified after a second following action on the same collection

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4582]
Steps to reproduce:
1. Sign in to AMO-dev and go to a collection details page i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/privacy/
2. Click "Follow this collection" - observe the number of followers
3. Refresh the page
4. Click "Stop following" - observe the number of followers

Expected results:
The number of followers turns back to the one it was before following this collection.

Actual results:
Nothing happens.

Notes/Issues:
- If the first act is "Stop following" for a collection, it will work, and don't for the "Follow this collection" option. Seems like second action is not taken into consideration.
- the collection is not listed in the Collection I'm Following page after step 4.

Verified on FF51(Win 7). Issue is reproducing all around AMO servers.
Video for this issue: 
![follow](https://cloud.githubusercontent.com/assets/15685960/22593558/cbf1c78a-ea27-11e6-9ef4-be200c2f3c49.gif)

**Comment by EnTeQuAk** [comment]
This is because of caching and eventually that number will be correct.
