### ISSUE TITLE
Add a "Self" section in Manage Status and Versions, containing the latest unlisted version

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4586]
Steps to reproduce:
1.Go to AMO and submit a listed version of an add-on
2.Submit a newer version for same add-on, but unlisted

Expected results:
We should display the latest unlisted version in a section similar _AMO Listed versions_  , but named _Self Listed versions_

Actual results:
The Unlisted version is going under _Older_ section , which is confusing because basically this is the latest version

Please see a screenshot for this : 
![self](https://cloud.githubusercontent.com/assets/1583842/22598020/a7af956a-ea3a-11e6-99d6-0efadb3cc189.png)

**Comment by eviljeff** [comment]
That's as UX [designed it](https://github.com/mozilla/addons/issues/193), but @jvillalobos can confirm a change is needed.

**Comment by jvillalobos** [comment]
That section is meant to highlight the version published on the site and the version pending review. There isn't much value in showing the latest unlisted one.

I agree `Older versions` is inaccurate. We could change it to `Other versions` to make it clearer.
