### ISSUE TITLE
Woff2 loading is blocked due to missing cors headers for that format

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4595]
### Describe the problem and steps to reproduce it:

* Unload fira sans if you have it locally (I use FontExplorer X Pro to do this)
* Go to https://addons.mozilla.org/en-US/developers/ 
* Look at the console 

### What happened?

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons.cdn.mozilla.net/static/fonts/fira/woff2/FiraSans-Regular.woff2?979a139. (Reason: CORS header 'Access-Control-Allow-Origin' missing).  (unknown)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons.cdn.mozilla.net/static/fonts/fira/woff2/FiraSans-Light.woff2?af42317. (Reason: CORS header 'Access-Control-Allow-Origin' missing).  (unknown)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons.cdn.mozilla.net/static/fonts/fira/woff2/FiraSans-Bold.woff2?a1ea7f3. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

### What did you expect to happen?

Woff2 format fonts should be ok to load without console errors. 

To get that we'll need the dev, stage and prod CDN configs updated to add cors headers for woff2 fonts

**Comment by jasonthomas** [comment]
These changes have been deployed on stage. I did a quick test and it looks okay. Can you also verify?

**Comment by muffinresearch** [comment]
@jasonthomas looks good
