### ISSUE TITLE
multifox add once blocked,what can i do?

### ISSUE THREAD

**Issue by hasan111sf** [mozilla/addons-server#4632]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment]
It seems the page is a 404 indicating the author would have removed their add-on, but I'm not sure.

I just checked and yes development of multifox has stopped, but the developer recommends checking out a Mozilla-developed feature: https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

- Matthew Riley MacPherson (sent from mobile)
