### ISSUE TITLE
Always include xmlns attribute when serving version update info

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4633]
Original bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1336786

STR:
- With Firefox 51, install an old version of an add-on that has release notes containing HTML formatting (e.g. lists, bold items, etc)
- In Firefox Add-on manager, click the gear icon, look at "View Recently Updated", then click on "Show Release Notes"

Expected Results:
- Notes are shown with formatting

Actual Results:
- Notes are shown without formatting.

Behind the scenes Firefox uses our update_info view to show release notes of add-ons in the add-on manager panel. It serves XHTML, which is then directly displayed by Firefox using an XHR.

In Firefox 51 a change to the Accept header was made: if was previously sending `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`, it's now sending `Accept: */*`. We relied on the header to include a `xmlns` attribute in the content, and not having it breaks how Firefox formats the release notes.

The fix is going to be to always include the xmlns attribute. I don't see a good reason to not send it, especially as this view only purpose is to be consumed by the internal Firefox XHR.

**Comment by muffinresearch** [comment]
Checked on -dev with breakpoints in charles proxy to modify the requests and `xmlns="http://www.w3.org/1999/xhtml"` is present on the `html` whereas in prod it isn't.
