### ISSUE TITLE
multifox add once problem.........

### ISSUE THREAD

**Issue by hasan111sf** [mozilla/addons-server#4636]
Hello team,

multifox add once some problem now,I don,t Understand for this problem. 

please,see the attached file.

how can i handel this problem? 

help me about that as soon as posible......

thanks & best regards,
Hasan Emam,
![2017-02-08 5](https://cloud.githubusercontent.com/assets/25627013/22736254/7b644348-ee27-11e6-8d2d-40d9d5d594ff.png)
![2017-02-08 6](https://cloud.githubusercontent.com/assets/25627013/22736255/7b645856-ee27-11e6-9595-59f04ab08adc.png)

Thanks & Best Regards.
hasan emam

**Comment by tofumatt** [comment]
**MultiFox is no longer available.**

Read info here: https://github.com/hultmann/multifox

You cannot download Multifox from Mozilla Add-ons anymore.

You can use https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers.

Please stop filing issues about Multifox and please read our responses. There is no Multifox add-on available anymore from Mozilla. You can download the source from https://github.com/hultmann/multifox and possibly install it yourself as an unlisted add-on.

**Comment by hasan111sf** [comment]
my install github/github sell, sowfter,how can i use this sowfter?
I am try again for this link https://getmultifox.com/.but I see this site
is no fond?
How can i do? pls,help as soon as posible....

pls,see thie attach file....

Thanks & Bestregards.
hasan emam

**Comment by tofumatt** [comment]
It is not available. You can not run Multifox anymore. Sorry but it is not available.

**Comment by guilhas** [comment]
Hello,

The .xpi can still be downloaded from here:
https://github.com/hultmann/multifox/releases

Regards
