### ISSUE TITLE
Long-name add-ons are causing small layout issue in new Dev Hub page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4640]
STR:
1. Submit an add-on with long name (max length accepted) i.e. https://addons.allizom.org/en-US/developers/addon/easy-youtube-video-download/edit
2. Go to Dev Hub page and observe "My Add-ons" section

Expected results:
The section looks good.

Actual results:
The section near add-on name is squeezed.

Notes/Issues:
- reproducing only for add-on with name on two rows;
- reproducing more often using other languages.
Verified on FF51(Win 7). Issue is reproducing around all AMO servers.
Screenshot for this issue:
![2017-02-08_1623](https://cloud.githubusercontent.com/assets/15685960/22744520/3ec729d8-ee26-11e6-86ec-f04dd57615e1.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![longname](https://cloud.githubusercontent.com/assets/1583842/22937008/e76048be-f2df-11e6-8767-d3463b2177b8.png)
