### ISSUE TITLE
Error when uploading Add-On file for different platform

### ISSUE THREAD

**Issue by carlin-q-scott** [mozilla/addons-server#4641]
### Describe the problem and steps to reproduce it:
After uploading a new version of my add-on for mac/linux, I chose the option to upload another file for a different platform (Windows). After uploading and clicking Submit.

### What happened?
- I was redirected to an error page: https://addons.mozilla.org/en-US/developers/addon/media-keys/versions/submit/2032816/finish-file
- The add-on file was actually submitted correctly from what I can tell when managing the review submission page.

### What did you expect to happen?
A page indicating that my add-on file for the Windows platform was submitted successfully.

### Anything else we should know?
I can't access the page that's linked to for the version of my add-on mentioned in this bug: https://addons.mozilla.org/en-US/firefox/addon/media-keys/versions/1.0.1

**Comment by ValentinaPC** [comment]
@carlin-q-scott : if you access your add-on manage page, you will see that the file was added, and this is only a "surface" problem. 
The issue you encountered was tracked here - https://github.com/mozilla/addons-server/issues/4525#event-952435776 - and will be pushed in production tomorrow.
Thanks for understanding and sorry for the inconvenience!
