### ISSUE TITLE
Add on Browsec is not found in the add ons. Is it unavailable?

### ISSUE THREAD

**Issue by Jsulleonor** [mozilla/addons-server#4643]
### Is it Gone?

###https://addons.mozilla.org/en-US/firefox/addon/browsec/
![untitled](https://cloud.githubusercontent.com/assets/25650744/22764126/9f60be16-ee1d-11e6-8a6d-6546872def74.JPG)

**Comment by tofumatt** [comment]
If an add-on is no longer appearing in the search it is not available, sadly. Most likely the author disabled it; this issue tracker is for bugs with the add-ons site itself, not for contacting add-on developers, so I'll close this issue.

But it looks like you can contact the developer here: https://browsec.com/en/

(Yes, it looks like the add-on has been removed, presumably by the author. @jvillalobos could confirm.)

**Comment by Jsulleonor** [comment]
Thank You for the immediate response

**Comment by kewisch** [comment]
Just for the record, we have gotten request from the author and are handling this on amo-admins. It does not look like the author disabled the add-on.

**Comment by jvillalobos** [comment]
I disabled the add-on due to compatibility problems. It looks like the developer already submitted an updated version for review.

**Comment by Jsulleonor** [comment]
This shows when I tried to re-install browsec again. What could be the
problem?

**Comment by jvillalobos** [comment]
Assuming you tried to install it from the add-on page, you will get an installation error until the add-on is reviewed and signed. See the line below the installation button that indicates this.
