### ISSUE TITLE
Weird search results from "Dictionaries & Language Packs" homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4650]
Steps to reproduce:
1. Go to Dictionaries & Language Packs page https://addons.allizom.org/en-US/firefox/language-tools/
2. Make an empty search

Expected results:
Either dictionaries/language packs or all add-ons are displayed.

Actual results:
Only dictionaries are listed but **Filter Results** menu has as selected category "**All Add-ons**".

Notes/Issues:
- no language packs listed
- reproducing also from Complete Themes homepage
- not reproducing from Search Tools homepage
- clicking on "Category" to expand , doesn't show anything (AMO - dev and stage)
- clicking once on "All Add-ons" will display, as the filter suggests, ALL ADD-ONS.

Verified on FF51(Win 7). Issue is reproducing on all AMO servers.
Video for this issue: 
![search](https://cloud.githubusercontent.com/assets/15685960/22790782/ff8e006e-eeef-11e6-9b47-babcd12f6cd2.gif)

**Comment by diox** [comment]
Will be fixed in addons-frontend re-implementation of desktop.
