### ISSUE TITLE
Can't submit new Add-on — "This field is Required"

### ISSUE THREAD

**Issue by chrisiona** [mozilla/addons-server#4654]
Hi there,

### What happened?
I'm trying to upload my add-on and keep getting "This field is required" errors, with no text field to edit.  The uploader was happy with my ZIP file.  I can't proceed past this screen.

I'm not sure if it has actually uploaded, because it now rejects the unique Add–on URL I used (future-pass-phishing-alert), which may indicate the upload it's partially complete?

I do not see any add–ons in the "Manage my Subscriptions" screen.

Tried in Firefox latest and chrome latest (OSX).

My profile is:  https://addons.mozilla.org/en-GB/firefox/user/futurepass/

Thanks again.

### What did you expect to happen?

Upload my zip file, fill out the form and have my add–on in the Firefox add–on store.

### Anything else we should know?

![image](https://cloud.githubusercontent.com/assets/1732182/22807254/32277098-ef7a-11e6-8f14-5d33db9dd563.png)

![image 1](https://cloud.githubusercontent.com/assets/1732182/22807283/4587fa9a-ef7a-11e6-8214-bc32d766303f.png)

![image 2](https://cloud.githubusercontent.com/assets/1732182/22807300/52367816-ef7a-11e6-825d-9db9840c8ff1.png)

**Comment by chrisiona** [comment]
The links in my Recent Activity (which are labelled as "None" in the below image) point to the URL I requested.  Going to the address shows a "sorry, can't find it" page.

https://addons.mozilla.org/en-GB/firefox/addon/future-pass-phishing-alert/

![image](https://cloud.githubusercontent.com/assets/1732182/22813945/bd2e0f16-efa3-11e6-9148-8a0bcf17ee38.png)

![image](https://cloud.githubusercontent.com/assets/1732182/22813954/d2eb2c80-efa3-11e6-9fb5-4228d2e96048.png)

**Comment by eviljeff** [comment]
Yeah, delete and resubmit.  It's caused by some sort of invalid localisation (either broken or just unsupported) meaning that the name, etc, just doesn't exist in the database.

**Comment by chrisiona** [comment]
Thanks for the help guys

I'm assuming you guys delete on your end, given that I can't see it in my add–ons console?

Re the localisation issue, is that an issue with my zip or with my Moz account?  I'll double check my declarations in the zip in the mean time.

**Comment by eviljeff** [comment]
It should have been on your my submissions page, but I've deleted it for you anyway.
I'm not 100% sure about the localisation issue but I did notice you declared the default locale as 'en' rather than 'en-US' or 'en-GB' changing or the removing the line should be enough.

**Comment by chrisiona** [comment]
Thanks @eviljeff — yeah, it wasn't visible on the submissions page for me to delete unfortunately.

I had to remove the locale line from the manifest, and remove the locale directory for ```web-ext``` to accept it.  I'll zip and upload it again shortly.

Thanks again.

**Comment by chrisiona** [comment]
It worked!  Thanks.

Mind you I had to upload the new zip a couple of times, as the linter complained that there was no manifest (even though there was).

![image](https://cloud.githubusercontent.com/assets/1732182/22905581/f159eb68-f294-11e6-9df1-d7788571d07b.png)

**Comment by kumar303** [comment]
> I had to remove the locale line from the manifest, and remove the locale directory for web-ext to accept it.

Do you mean you were you using [web-ext](https://github.com/mozilla/web-ext) to build your extension package? If so, could you elaborate on the locale directory problem?

**Comment by chrisiona** [comment]
Hi @kumar303 — I was using the web-ext to dev test the plugin in FF.  

Here's the scenarios.

– Had locale folder, and declared locale as 'en' [Worked]
– Had locale folder, and declared locale as 'en-US' [Failed]
– Had locale folder, and declared locale as 'en-GB' [Failed]
– Had locale folder, and no declared locale [Failed]
– No locale folder, and no declared locale [Worked]

**Comment by kumar303** [comment]
@chrisiona I'm curious as to how you were able to build an add-on with a missing locale. Could you file a [web-ext bug](https://github.com/mozilla/web-ext/issues) with some source code that reproduces it? Maybe your `web-ext` version is out of date?

If I edit the manifest from [this example](https://github.com/mdn/webextensions-examples/tree/master/notify-link-clicks-i18n) to:

````diff
diff --git a/notify-link-clicks-i18n/manifest.json b/notify-link-clicks-i18n/manifest.json
index 6aa060f..997ec09 100644
--- a/notify-link-clicks-i18n/manifest.json
+++ b/notify-link-clicks-i18n/manifest.json
@@ -14,13 +14,13 @@
   "background": {
     "scripts": ["background-script.js"]
   },
-  
+
   "content_scripts": [
     {
       "matches": ["<all_urls>"],
       "js": ["content-script.js"]
     }
   ],
-  
-  "default_locale": "en"
+
+  "default_locale": "en-US"
 }
````

then web-ext won't even let me build it (which is expected):
````
$ web-ext build
Building web extension from /Users/kumar/dev/webextensions-examples/notify-link-clicks-i18n

build: UsageError: Error reading messages.json file at /Users/kumar/dev/webextensions-examples/notify-link-clicks-i18n/_locales/en-US/messages.json: Error: ENOENT: no such file or directory, open '/Users/kumar/dev/webextensions-examples/notify-link-clicks-i18n/_locales/en-US/messages.json'
````
