### ISSUE TITLE
waht happend in multifox ?not work 

### ISSUE THREAD

**Issue by youssefm199** [mozilla/addons-server#4656]
We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.

**Comment by tofumatt** [comment]
Multifox is no longer available for download; it has been removed by its developer.

**Comment by youssefm199** [comment]
Please make sure it did not work again

**Comment by guilhas** [comment]
The .xpi can be download and installed from the author page:
https://github.com/hultmann/multifox/releases
