### ISSUE TITLE
Remove Tabzilla from devhub

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4658]
Steps to reproduce:
1. Load AMO homepage https://addons.mozilla.org/en-US/firefox/
2. Observe the "Mozilla" logo

Expected results:
New logo is displayed.

Actual results:
Old logo is displayed.

Notes/Issues:
Verified on FF51(Win 7). Issue is reproducing all around AMO-servers.
Screenshots:
![logo](https://cloud.githubusercontent.com/assets/15685960/22820678/7eaf9db8-ef80-11e6-9fed-c17e9c7225c3.png)

**Comment by vcarciu** [comment]
If you decide to do that, please make same change on Mobile View too

**Comment by muffinresearch** [comment]
Depends on https://github.com/mozilla/tabzilla/issues/84

**Comment by fitojb** [comment]
It doesn’t appear like Tabzilla has any future, given that [a new global navigation component](https://github.com/mozilla/bedrock/pull/4738) is being built…

**Comment by muffinresearch** [comment]
@fitojb thanks for the heads up. Our new desktop UX which is being worked on in Q2 features the new logo so I think for now for this specific issue we can resolve it there without relying on any upstream project.

**Comment by eviljeff** [comment]
Given the chat in the bugs it looks like tabzilla is effectively deprecated.  New front-end doesn't use it, so lets just remove it from devhub.

**Comment by EnTeQuAk** [comment]
Removing as in really just removing it or replacing it with an up-to-date logo?

![screenshot-2018-1-30 manage my submissions developer hub add-ons for firefox](https://user-images.githubusercontent.com/139033/35570673-2e1c80d4-05d0-11e8-8c4b-4aad5b38904d.png)

Looks fairly okay to me. Opinions?

**Comment by eviljeff** [comment]
New frontend doesn't have the Mozilla logo/word-mark at all so I suggest really just removing it.  So looking like that screenshot, yup.

But.  New front-end has the Mozilla logo in the footer.  In #6167 when I updated the footer links there was talk of adding the same footer (the "new global footer") that never happened.

**Comment by lavish205** [comment]
Hi 
I would like to work on this bug.

**Comment by eviljeff** [comment]
@lavish205 go ahead. It's mainly deleting code.  Search for `tabzilla`

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/41456543-754847bc-7089-11e8-8815-58a64df804d6.png)
