### ISSUE TITLE
The uninstall option is available in "Get Add-ons" page for a "requires restart" add-on that was previously removed from "Extensions" tab

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4659]
Prerequisites:
- disco pane is set to point -dev

Steps to reproduce:
1. Install a "requires restart" add-on from Add-ons Manager - Get Add-ons page i.e. Enhance YouTube
2. Restart the browser to apply changes
3. Go to "Extensions" tab and click "Remove" button
4. Go to "Get Add-ons" - refresh the page
5. Click the switch button to uninstall the add-on

Expected results:
User is not able to click the switch button because of a green banner that displays a message that you need to restart the browser to apply changes.

Actual results:
User can click the switch button and receive an error message "An unexpected error occurred during uninstallation."

Notes/Issues:
- reproducing only for "requires restart" add-ons
Verified on FF54(Win 7).
Video for this issue: 
![unex](https://cloud.githubusercontent.com/assets/15685960/22822190/0a07dc26-ef87-11e6-994f-ae52975ad7ac.gif)

**Comment by diox** [comment]
Disco pane bugs should be opened in https://github.com/mozilla/addons-frontend
