### ISSUE TITLE
Display an info page for Multifox

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4667]
Multifox, a popular add-on has seemingly been deleted recently and is confusing a lot of users. They go to the page and are treated with a 404, which is bad UX. The add-on used to exist but now doesn't and the 404 page includes a link to this repo to file an issue, which several people have. Triaging these bugs has become annoying enough I'm filing this issue; I think we should just add a page explaining it's no longer available and why (the author stopped development).

**Comment by jvillalobos** [comment]
This will only get worse as add-ons become increasingly incompatible on the way to 57. Maybe it's worth doing this for this particular add-on, but it won't scale.

We're starting to work on a proposal to [recommend alternative add-ons](https://docs.google.com/document/u/1/d/19CB11uJbhz2txgP9AMPdvAcqjTHubQvEHU5E17LiaTs/edit) when add-ons are no longer being maintained.

**Comment by guilhas** [comment]
The add-on is still the best working option. Not everyone is using or will soon use the latest Firefox versions.

The .xpi can be downloaded and installed from here:
https://github.com/hultmann/multifox/releases

**Comment by diox** [comment]
We haven't had issues about this in a while, let's close this.

(We do have a recommendation system in place, but we don't use it in 404s/add-on detail pages atm. Maybe something worth revisiting if this problem comes back)
