### ISSUE TITLE
multifox is deleted

### ISSUE THREAD

**Issue by Maria9090** [mozilla/addons-server#4668]
Hi,
I was using an add-on Multifox, then I've installed tree etyle tab and multifox stopped working.
Now I can't fint Multifox in add-ons and can't install it.
How can I install Multifox? Or is there a new add-on in which I can log in in a lot of accounts in one browser?

Loking for your answer.
Best regards, Mary

**Comment by jvillalobos** [comment]
The add-on is incompatible with current versions of Firefox. It's up to the developer to upload new compatible versions so it can be available again.

There's a feature similar to Multifox possibly coming up in Firefox, but it might still be a couple of months away.
