### ISSUE TITLE
New developer hub: "my add-ons" looks strange

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-server#4671]
Screenshot of "my add-ons" in the new developer hub (https://addons.mozilla.org/de/developers/):
<img width="976" alt="bildschirmfoto 2017-02-13 um 23 32 06" src="https://cloud.githubusercontent.com/assets/1100614/22906420/a8a8c24a-f244-11e6-8fbc-e39de3fee4fc.png">

Please see the different text breaks / alignments.

**Comment by EnTeQuAk** [comment]
I'll close this in favor of https://github.com/mozilla/addons-frontend/issues/1800 which contains more context about a potential fix. Thanks a lot for reporting this!
