### ISSUE TITLE
javad

### ISSUE THREAD

**Issue by javad1372** [mozilla/addons-server#4678]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by javad1372** [comment]
hi it is very good

**Comment by tofumatt** [comment]
This is an issue tracker for Mozilla's Add-ons site. If you are having an issue with the site please let us know, otherwise I'll leave this closed.
