### ISSUE TITLE
Support authentication with addons-frontend in development workflow

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#4684]
### Describe the problem and steps to reproduce it:
Run addons-server with docker and addons-frontend AMO with its proxy server. Logging in from addons-frontend works but logging in from addons-server on localhost:3000 does not.

### What happened?
FxA redirected to http://olympia.dev.

### What did you expect to happen?
FxA redirected to http://localhost:3000 and log in was successful.

### Anything else we should know?
This is really a configuration problem. If addons-server was setup to use the "local" FxA config then this would work. There should be some way to tell addons-server to use this configuration instead of the default. The code path for the log in link starts from [olympia.accounts.helpers](https://github.com/mozilla/addons-server/blob/4a59ee4b4e7bf425fdc9e64afbc3bbe57a942bc9/src/olympia/accounts/helpers.py).

The addons-frontend README should be updated when this is fixed.

**Comment by willdurand** [comment]
This works now.
