### ISSUE TITLE
Block certain guids in a mozilla namespace

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4688]
We have some guids that we are using for system add-ons. Those never get uploaded to AMO and confusion would ensure if someone created an add-on that conflicted with one of those guids. So let's avoid that by blocking all guids that are: *@mozilla.org 

That should cover all the existing system add-ons currently. I note that we have a DeniedGuid class in AMO, but it just appears to be a string match, not a regex.

**Comment by jvillalobos** [comment]
That could block future submission of other internal add-ons that aren't system add-ons, so we'll need to at least have an admin bypass for this.

Alternatively, they could just upload one version of each as unlisted, which blocks the guid.

**Comment by andymckay** [comment]
That's a good point, and developers might change their mind moving from a system add-on to AMO at some point. Ideally not changing guid on the way.

/cc @rhelmer

**Comment by rhelmer** [comment]
It's very likely that developers will want to both ship as a system add-on and also have a newer version on AMO - Hello did this for example, so people could opt into being beta testers.

**Comment by andymckay** [comment]
So perhaps anything with a *@mozilla.org guid needs to have a permission on AMO. Then people can ask for the right to use it and we can assign out that permission as needed.

**Comment by jvillalobos** [comment]
Or check if the account has an @mozilla email address.

**Comment by rhelmer** [comment]
All of the system add-ons we've shipped so far end with `@mozilla.org` except for Pocket which uses `firefox@getpocket.com` so please make sure to cover this one too.

**Comment by muffinresearch** [comment]
@eviljeff would you be able to take a look at this one? Seems like something we should do sooner rather than later.

**Comment by eviljeff** [comment]
May as well just add `firefox@getpocket.com` to the DeniedGuid list if it's just a single guid for an add-on.

**Comment by jvillalobos** [comment]
Language pack GUIDs follow the format `langpack-xx-XX@firefox.mozilla.org`. That shouldn't match the filters we're talking about here, but I'm bringing it up just to be safe :).

**Comment by eviljeff** [comment]
yeah, I just did `endswith('@mozilla.org')`.  If it's the function that adds the lang packs from the ftp server it uses it's own special sauce in zadmin to add them anyway.

**Comment by eviljeff** [comment]
@jvillalobos can you add `firefox@getpocket.com` to the `DeniedGuid` model in /admin on prod?  (I've done stage and dev)

**Comment by jvillalobos** [comment]
Added.

**Comment by vcarciu** [comment]
Verified as fixed for bot listed and unlisted add-ons and webextensions : 
![mozillaorg](https://cloud.githubusercontent.com/assets/1583842/23064888/4f66d1f2-f51b-11e6-9665-d6084a608527.png)

**Comment by muffinresearch** [comment]
@eviljeff thanks for patching this so quickly!
