### ISSUE TITLE
The devhub footer is hidden at mobile view port sizes

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4693]
### Describe the problem and steps to reproduce it:

The new devhub footer is explicitly removed at small viewport sizes. This removes some potentially useful links but also makes it impossible to change the language since the language switcher is in the footer. 

Since it's being served but just `display: none` I think we should consider improving the styling and including it or at least the relevant parts of it.

### See full-page screenshot below:

![screen shot 2017-02-16 at 11 00 55-fullpage](https://cloud.githubusercontent.com/assets/1514/23018812/59c482f0-f437-11e6-9973-8536a90ca0cf.png)

**Comment by SeanPrashad** [comment]
Hi there! I'd love to tackle this bug if it's available. At first glance, it might be a CSS issue - what do you think?

**Comment by CuriousLearner** [comment]
@SeanPrashad Are you working on this one? :)

If not, then let me know, I'd like to take this up!

**Comment by SeanPrashad** [comment]
Please feel free to take it over @CuriousLearner! ✌🏽

**Comment by eviljeff** [comment]
closing this in favour of #12555
