### ISSUE TITLE
Fix test database setup to allow for proper database usage within UI tests.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#4697]
This has come up while I have been trying to move addons-tests over to addons-server. 

It seems the ```liveservertestcase``` uses a different database than the one used to create users, specifically the supercreate user. @EnTeQuAk has been digging into a solution.

**Comment by EnTeQuAk** [comment]
A first prototype / workaround has been implemented in https://github.com/jrbenny35/addons-server/commit/9ad19160ae1361a90535e01d52ac7ac57d98ff6a but I need to look into this further to fix this properly and understand the actual problem a bit more.
