### ISSUE TITLE
Link to unlisted review page is missing

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4699]
https://addons.mozilla.org/en-US/editors/review/test-legacy-update does not have a link to the unlisted review page in the *Action* section on the right, but I think it should have, since it has unlisted versions, see https://addons.mozilla.org/en-US/editors/review-unlisted/test-legacy-update.

**Comment by diox** [comment]
How did you get to the page ? It has no listed versions, so the behavior of the listed review page is a bit unreliable. 

The "Actions" links depend on the presence of a valid version, which is why the link is not showing up. We could refactor this a little to make it show up.

**Comment by wagnerand** [comment]
I got a mail notification that this add-on was flagged for admin review.
