### ISSUE TITLE
Internal Server Error's

### ISSUE THREAD

**Issue by psiinon** [mozilla/addons-server#4702]
### Describe the problem and steps to reproduce it:
Access the following URLs with a mobile user agent like "Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0":

- https://addons-dev.allizom.org/api/v3/accounts/account/6362937?query=ZAP%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%0A
 - https://addons-dev.allizom.org/api/v3/accounts/account/6362937?query=14816458835629746137950925770871450099358545
 - https://addons-dev.allizom.org/api/v3/addons/search/?app=firefox&page_size=4&sort=rating&type=extension&page=42534372092246088007922959442281889602546449&lang=en-US

### What happened?
Server returned:

> {"detail":"Internal Server Error"}

### What did you expect to happen?
An error which indicates the relevant parameter does not have a valid value

**Comment by diox** [comment]
The first 2 return `{"detail": "Not found."}` for me. The third one does return a internal server error: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/381113/

I'll see what I can do about that, maybe introduce an upper limit for the page parameter.

**Comment by psiinon** [comment]
@diox did you try with the specified user agent string? If you use a desktop one they are ok.

**Comment by diox** [comment]
Yes.

```
% curl 'https://addons-dev.allizom.org/api/v3/accounts/account/6362937?query=ZAP%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%25n%25s%0A' -H "Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0"
{"detail": "Not found."}
```
and
```
% curl 'https://addons-dev.allizom.org/api/v3/accounts/account/6362937?query=14816458835629746137950925770871450099358545' -H "Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0"
{"detail": "Not found."}
```

**Comment by diox** [comment]
@psiinon ah, I see what's going on. The view you're hitting does not exist, and until yesterday it was returning a 500... on purpose (raising `NotImplementedError`). I removed it in https://github.com/mozilla/addons-server/commit/9031a6bb7d7e13e8a4f383742c4eb569f1197691

The 3rd URL is still a valid issue though.

**Comment by psiinon** [comment]
Ah ha! Yes, I ran the scan yesterday :)

**Comment by vcarciu** [comment]
Verified as fixed. Server is now returning {"detail":"Invalid page."} for third URL
