### ISSUE TITLE
Special case 404 for mobile UAs

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#4706]
With the new mobile pages we fallback to the django site if the mobile app returns a 404, this is due to there being some pages that don't exist on the mobile app but do exist in the django site. 

An example of this is the new devhub landing page - the fallback behaviour is as follows (following steps assume a Mobile UA or the client has the mamo cookie set)

* Client requests /en-US/developers/ on the mobile app via nginx
* Mobile app server replies with 404 
* Nginx fallsback to requesting /en-US/developers/ from the django app.
* Client gets 200 and the devhub landing page

Now consider what happens when we have a 404 on both sites:

* Client requests /en-US/whatevar/ on the mobile app via nginx
* Mobile server replies with 404 
* Nginx fallsback to requesting /en-US/whatevar/ from the django app.
* Desktop app server replies with 404
* Client sees non responsive 404 page

To fiix this we need to either replace our 404 with something generic that we can serve in all cases or alternatively special case the 404 response if it's a mobile UA or the mamo cookie is set.

Here's an example of a current mobile app 404: view-source:https://discovery.addons-dev.allizom.org/en-US/firefox/fdsjkfh

**Comment by ValentinaPC** [comment]
@muffinresearch - In order to check this, I have a question:
I've logged this https://github.com/mozilla/addons-frontend/issues/1786, and I saw now the current bug... and I am bit confused - it is ok to show a 404 page while logging in from homepage mobile site or is my bug a regression to this or the redirect is wrong? Thanks in advance!

**Comment by muffinresearch** [comment]
This is unrelated to that bug. Logging in should not result in a 404.
