### ISSUE TITLE
Addon validation fails completely on large files

### ISSUE THREAD

**Issue by Akkuma** [mozilla/addons-server#4717]
### Describe the problem and steps to reproduce it:
File is too large to parse, upload an extension with a file larger than 4MB

### What happened?
Receive the error "File is too large to parse", so cannot sign an unlisted addon that is a develop build that isn't minified.

### What did you expect to happen?
Get a signed extension

### Anything else we should know?
https://addons.mozilla.org/en-US/developers/upload/d0a95d7b4efd47008b2b7e7fc5bec167

**Comment by jvillalobos** [comment]
Can you please share the file you're trying to upload? Is this currently blocking you from submitting your add-on?

**Comment by muffinresearch** [comment]
Closing this due to lack of information. Please re-open this if you're still experiencing the problem.

**Comment by gorhill** [comment]
I received the same error when trying to have my extension signed:

![Screenshot from 2023-08-11 18-32-36](https://github.com/mozilla/addons-server/assets/585534/75ed2b56-f945-45ed-b9f7-bf7d7661e53f)

Validation URL is: <https://addons.mozilla.org/en-US/developers/upload/c65513ae305a4cdbaf4600dad60af212>

Two files are larger than 4 MB in the extension:

![Screenshot from 2023-08-11 18-34-33](https://github.com/mozilla/addons-server/assets/585534/a91ef56f-c618-4364-81ac-f8c6fbc731b1)

These are ruleset files to be used by the declarativeNetRequest API, the only workaround I can see is:

- Do not prettify the generated JSON, which results in `default.json` shrinking to 3.6 MB
- Do not ship `stevenblack-hosts.json` DNR ruleset, it's still at 5.3 MB without pretty JSON

The extension package: <https://github.com/gorhill/uBlock/releases/download/uBOLite_1.0.23.8118/uBOLite_1.0.23.8118.firefox.mv3.xpi>, and it's the first release of uBO Lite for Firefox which I expect to be as functional as the Chromium version.
