### ISSUE TITLE
2 "Request Review" links for an add-on with one version disabled and one beta

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4722]
Steps to reproduce:
1. Submit a listed add-on in AMO-dev
2. Approve the version
3. Submit a second beta version for this add-on
4. Disable the listed version

Expected results:
There is a "Request Review" link.

Actual results:
There are two "Request Review" links: one under the disabled version, one under the beta version.

Notes/Issues:
- both links have the same results while being clicked. 
Verified on FF51(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue:
![2links](https://cloud.githubusercontent.com/assets/15685960/23128631/473a09b2-f788-11e6-9703-0f131257ff06.png)

**Comment by jvillalobos** [comment]
Beta versions are no longer supported.
