### ISSUE TITLE
Non-promptable permissions are specified in amo permissions pop-up

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#4723]
**Steps to reproduce:**
1. Navigate to https://addons-dev.allizom.org/en-US/firefox/addon/webext100/?src=search
2. Click on “Permissions” link.

**Expected results:**
Non-promptable permissions are not mentioned in amo Permissions pop-up.

**Actual results:**
Non-promptable permissions are listed in amo Permissions pop-up even if they are not displayed in installation doorhanger.

**Additional notes:**
- This issue reproduces on AMO-dev using Firefox 54.0a1 (2017-02-29) under Windows 10 64-bit.
- Please see the attached screenshots for this issue:
![2017-02-20_1630_001](https://cloud.githubusercontent.com/assets/18114210/23129172/4cc12d50-f78a-11e6-9c7b-ab7f5317ae95.png)
![2017-02-20_1630](https://cloud.githubusercontent.com/assets/18114210/23129180/51fc5632-f78a-11e6-904b-c867d75b7e78.png)

**Comment by eviljeff** [comment]
The original PRD didn't specify whether to show unknown permissions, or permissions that Firefox considers unpromptable, or not.  Subsequent comment in #3983 clarified and it will be changed as part of that issue.
