### ISSUE TITLE
The link “Leave a reply” does not redirect the user correctly

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#4724]
### Describe the problem and steps to reproduce it:
Prerequisites: The WebExtension must contain an approved version and a disabled version.

1.Try to leave a reply to the approved version of this WebExtension https://addons-dev.allizom.org/en-US/developers/addon/testactivitymail1123/versions 

### What happened?
The user is redirected to the disabled version of this WebExtension.

### What did you expect to happen?
A reply can be added to the selected version.

### Anything else we should know?
Verified on FF54.0a1 under Win 7 64-bit.
This issue is reproducing on -dev and stage servers.
Please see the video for this bug :
![leaveacomment](https://cloud.githubusercontent.com/assets/15885467/23129959/46b6eaaa-f78d-11e6-82da-6efb68c50b93.gif)

**Comment by eviljeff** [comment]
that's by design - you're leaving a reply on the last version.  The requirement was that only one version could have a message attached to it, and that would be the latest (similar to how the reviewers review page works).

**Comment by ValentinaPC** [comment]
@eviljeff : I have a question - shouldn't "Leave a reply" link **`take`** the user to the last version? Because if, the add-on has multiple versions, seems like "Leave a reply" link does not work, if user does not scroll down.
Please take a look and let me know if we need to track this separately or is not such big of a deal:
![leave a reply](https://cloud.githubusercontent.com/assets/15685960/23162858/aa4a69e2-f838-11e6-87b3-a090634a8ec2.gif)

**Comment by eviljeff** [comment]
yes, I think it probably should scroll the page down so the reply box is visible (and possibly focused)

**Comment by eviljeff** [comment]
#3726

**Comment by ValentinaPC** [comment]
Verified on FF51(Win 7).
While clicking "Leave a reply" link for a version that is not the last, user is redirected to the last version, but the focus is not on the text-field. Is this the fix? Shouldn't we send the user directly to the section where he can write the reply? Thanks!
Please see the video: 
![ex2](https://cloud.githubusercontent.com/assets/15685960/23360752/e27b288a-fcf5-11e6-8acb-7317b92e468a.gif)
![focus](https://cloud.githubusercontent.com/assets/15685960/23360751/e27925ee-fcf5-11e6-86be-7ddaed8d966c.gif)

**Comment by eviljeff** [comment]
It would be a reasonable change, but I didn't make it focused - I thought the scrolling was the important part.

**Comment by ValentinaPC** [comment]
For sure, that was the important part :). Just asking.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on Firefox 54.0a1 under Wind7 64-bit
Postfix video:
![fixed](https://cloud.githubusercontent.com/assets/15885467/23366780/ad9e4c80-fd10-11e6-9c53-718dedaeeea4.gif)
