### ISSUE TITLE
addon missing: new-tong-wen-tang (新同文堂) is missing

### ISSUE THREAD

**Issue by samuelololol** [mozilla/addons-server#4728]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
The link of this addon is invalid
https://addons.mozilla.org/zh-TW/firefox/addon/%E6%96%B0%E5%90%8C%E6%96%87%E5%A0%82-new-tong-wen-tang/

### What happened?
link invalid

### What did you expect to happen?
provide latest version

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
The latest source of this addon is located at 
https://github.com/softcup/New-Tongwentang-for-Firefox

**Comment by jvillalobos** [comment]
If you're the developer of the add-on, please send an email to amo-admins AT mozilla DOT org and we'll help you submit new versions to have the add-on reinstated.

Otherwise, it seems the add-on was abandoned, and there are no recent versions available.
