### ISSUE TITLE
Review Tools: No need for Syntax Highlighting for JSON files

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#4729]
### Describe the problem and steps to reproduce it:
Addons often include large JSON files. The Syntax Highlighting script attempts to process the file which often results in unresponsive browser for a while.
The Syntax Highlighting is not really needed for JSON files.

Example:
`https://addons.mozilla.org/en-US/firefox/files/compare/594962...572165/file/res/entitylist.json`

PS. If needed, a simpler cut-down string-highlight script, just for strings would do the job.

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/4149

**Comment by jvillalobos** [comment]
This code viewer is going away soon.
