### ISSUE TITLE
Remove old auto validation code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4730]
Once upon a time, an auto validation feature was considered for addons-server, and some code was written to support it. The initial idea, IIRC (I wasn't on the AMO team at the time), was that it would be used for both unlisted and listed add-ons, making it possible for them to be automatically approved depending on the result from the validator.

Ultimately, it didn't work out - perhaps because, since they don't have a permission model or any kind of sandboxed API, you could easily add malicious code in legacy extensions, making the proposition dangerous. We did end up making all unlisted add-ons automatically signed, though, instead of waiting for a human review.

Today, some of the code that was produced for this feature still exist in AMO (both in addons-server and amo-validator). If we are to build #4533 we should remove it first to prevent confusion.

**Comment by diox** [comment]
Some of the code that deals with auto validation is now fairly intertwined with the rest, so it's a bit difficult to fully identify what can be removed.


- Remove all occurrences of `passed_auto_validation`
- Remove all occurrences of `signing_summary`, `signing_help`, `signing_severity`
- Remove most code that "annotates" validation result, except webextensions stuff. In particular, simplify `ValidationAnnotator`, remove `annotate_validation_results`, and more
- Remove `ValidationComparator` and things that deal with automatic validation results comparison. 

Regarding the last item, validation results comparison was supposed to be used with automatic signing to ignore validation results that had already been checked by a human in a previous version. File viewer still displays has a checkbox that says "Ignore this message in future updates" next to validation warnings, is it actually useful or completely ignored ?

**Comment by wagnerand** [comment]
> Regarding the last item, validation results comparison was supposed to be used with automatic signing to ignore validation results that had already been checked by a human in a previous version. File viewer still displays has a checkbox that says "Ignore this message in future updates" next to validation warnings, is it actually useful or completely ignored ?

We currently do not review unlisted add-ons, which I think that checkbox applies to. We will, however, start doing this at some point in the future again, but it will be post-approval reviews.

**Comment by diox** [comment]
QA: please make sure add-on validation still works correctly for both listed and unlisted add-ons, including showing warnings.

**Comment by ValentinaPC** [comment]
This can be marked as verified-fixed.
