### ISSUE TITLE
Small issue while unchecking "My add-on doesn't fit into any of the categories" category during submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4736]
Steps to reproduce:
1. Submit a listed add-on and stop to details step
2. Don't select a category for Firefox and select a category (or 2) for Android
3. Uncheck the "My add-on doesn't fit into any of the categories" category (that was automatically selected)

Expected results:
The category is unchecked. Nothing happens with the check-boxes from the Android categories group.
Unchecking the category that was automatically checked, does not mean the user wants to uncheck everything.

Actual results:
The Firefox category is unchecked together with all Android checked categories.

Notes/Issue:
Verified on FF51(Win 7). Issue is reproducing all around AMO-servers.
Video for this issue: 
![cat](https://cloud.githubusercontent.com/assets/15685960/23172543/c162f5a6-f85e-11e6-94fa-160596729848.gif)

**Comment by diox** [comment]
Broken javascript that @eviljeff says he almost fixed but didn't :) The javascript that is responsible for the checkbox uses an overzealous CSS selector and ends up affecting all the checkboxes instead of only the ones for desktop.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @eviljeff

**Comment by lavish205** [comment]
I would like to work on this bug.

**Comment by eviljeff** [comment]
@lavish205 great.  
You need to change the js in https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/devhub.js#L975:L999 - probably either the `checkOther` function or the `$main` selector.  I'm not sure why _only_ this functionality is broken, but the max category counting and `checkMain` seem to working okay.

**Comment by lavish205** [comment]
@eviljeff @ValentinaPC how can I reproduce the same issue in my local system.

**Comment by eviljeff** [comment]
easiest way is to start uploading a webextension, because they are cross-platform by default

**Comment by caitmuenster** [comment]
Hey @lavish205, how is it going with this bug?

**Comment by raajitr** [comment]
hi @caitmuenster, I thought I was working on this bug :p
PR #5568 is still open, which is not being referenced here.

**Comment by caitmuenster** [comment]
Hi @raajitr -- I am so sorry, that was totally my bad! :)

**Comment by jvillalobos** [comment]
Unassigning this issue since there has been no reply in the PR.

**Comment by diox** [comment]
mozilla/addons-server#6471 should have fixed this

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix video:
![checkbox](https://user-images.githubusercontent.com/15685960/30742119-69f397dc-9fa0-11e7-9fb6-24fac6b42207.gif)
