### ISSUE TITLE
Cannot explicitly hide grouped ratings when listing reviews

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#4737]
### Describe the problem and steps to reproduce it:

Make an API request to [list reviews](http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#list-reviews) with an explicit GET parameter to hide grouped ratings, like `?show_grouped_ratings=0`.

### What happened?

The grouped ratings are shown

### What did you expect to happen?

The grouped ratings should be hidden

**Comment by diox** [comment]
As discussed on IRC I'll make the API parse the value as int, reject with a 400 values it can't parse or that are not 0 or 1
