### ISSUE TITLE
Empty replies can be performed for a version of an Add-on or of a WebExtension

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#4740]
### Describe the problem and steps to reproduce it:
Leave a reply with an empty field for any version from this WebExtension https://addons-dev.allizom.org/en-US/developers/addon/activitymail20/versions  

### What happened?
A reply with an empty field can be performed and an email is sent to the user.

### What did you expect to happen?
A warning for the empty field is displayed.

### Anything else we should know?
Verified on FF54.0a1 under Win 7 64-bit.
This issue is reproducing on -dev and stage servers.
Please see the video for this bug :
![empty reply](https://cloud.githubusercontent.com/assets/15885467/23209394/c2a09a2e-f901-11e6-942b-a188210822b7.gif)

**Comment by wagnerand** [comment]
We should probably disable the button if the box is empty.

**Comment by wagnerand** [comment]
Fixed in #4905.

**Comment by eviljeff** [comment]
I was going to disable the button but I was too lazy to hook up a listener on keystrokes :)
Instead the button just doesn't do anything if there is no text in the textarea.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF55.0a1 (Wind 7 64-bit) on -dev server.
Empty replies can’t be performed, clicking on the “Reply” button with an empty text box will not leave a reply.
Please see the video:
![emptyreplies](https://cloud.githubusercontent.com/assets/15885467/23845349/301de2a0-07d0-11e7-9800-26b769ac8daa.gif)
