### ISSUE TITLE
Skip edit account redirect when registering with addons-frontend

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#4742]
When a user registers for AMO we redirect them to the edit account page so they can set their username. The new mobile pages don't have a page for this so this isn't very helpful there.

The regular `next_path` redirect should be used when a user registers using the addons-frontend FxA config.

Supports mozilla/addons-frontend#1660.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
User is redirected to homepage after registering.
Postfix video: 
![registering](https://cloud.githubusercontent.com/assets/15685960/23303617/d154883a-fa9d-11e6-8df1-5ae69a0b2716.gif)
