### ISSUE TITLE
Add-on submission email indicates add-on can be installed from detail page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4744]
After submitting an add-on for the first time, the email developers receive says:
> While awaiting review, your add-on can still be accessed and installed directly from its detail page:

That's not really true since signing. The add-on is available, but it's not easy to install. Let's change it to:

> While awaiting review, you can preview your add-on detail page, but it can't be installed until it is reviewed and signed:

**Comment by jvillalobos** [comment]
Mentor: @eviljeff

**Comment by lavish205** [comment]
I would like to work on this bug. @eviljeff

**Comment by eviljeff** [comment]
@lavish205 great.
The two files that need changing are
https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/email/submission.html
https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/email/submission.txt

**Comment by ValentinaPC** [comment]
@eviljeff :
I am not receiving an e-mail after add-on submission. Am I doing something wrong?
I receive an e-mail ONLY after approve.
I've checked Fake mail page also, and no trace of this there either.

**Comment by eviljeff** [comment]
You only get the email if it's your first submission.  You can either use a fresh account or delete all the add-ons from your existing account.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7) using a new account.
Postfix screenshot:
![mail](https://cloud.githubusercontent.com/assets/15685960/25393325/dc9a60aa-29e3-11e7-88c2-57c2ede5c3ad.png)
