### ISSUE TITLE
Error displayed when editing the homepage field for an unlisted add-on

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#4745]
### Steps to reproduce:
1. Open Edit information page for an unlisted add-on.
2. Click the Edit button in the Add-on Details section
3. Enter an invalid url format in the homepage field and click save
4. Enter an valid url format in the homepage field and click save

### Expected results:
The changes are saved.

### Actual results:
The changes are not saved,  "Enter a valid URL." error is displayed even if the url is valid

### Notes/Issues:
Is there a point to have the homepage field for unlisted add-ons at all ?  Shouldn't we remove it?

Verified in FF51(Win7) issue can be reproduced in -dev, stage and production
Screencast for this issue:
![unlistedhomepage](https://cloud.githubusercontent.com/assets/15685441/23220943/38cab318-f92c-11e6-908a-f641cdaa35ed.gif)

**Comment by jvillalobos** [comment]
> Is there a point to have the homepage field for unlisted add-ons at all ? Shouldn't we remove it?

The homepage can be useful for admins and reviewers to learn more about the add-on or contact the developers. I don't think it's a required field, so there's no harm in keeping it there.

**Comment by diox** [comment]
@madalincm can you still reproduce ? can you link the affected add-on ?

**Comment by eviljeff** [comment]
I suspect something else weird is happening and the fact its an add-on with no listed versions is irrelevant.  But if we can't reproduce lets close.
