### ISSUE TITLE
Uploading consequent updates resets wait in queue

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons-server#4748]
If a dev uploads an addon, then waits 2 weeks, then uploads an update, they are sent back in the queue. Would it be possible to not reset their position?

**Comment by Noitidart** [comment]
Oops I heard there was a template. I filed this from waffle so I didn't see the template. I'm ready to answer any questions.

Steps to reproduce:
1. Upload an addon to AMO
2. It gets approved
3. Upload an update
4. Wait 2 weeks
5. Upload an update - you will now see your position reset

**Comment by muffinresearch** [comment]
@diox or @eviljeff would either of you have a moment to look into this and see what it would take to prevent the queue position change following updates?

**Comment by diox** [comment]
Note that in theory this should already work like that: the nomination date should be inherited when uploading a new version, and therefore the position should be roughly the same.

**Comment by wagnerand** [comment]
Yes, it's a bug. We are getting reports from affected developers on a daily basis.

**Comment by eviljeff** [comment]
Does this affect both new addons and new versions?

**Comment by wagnerand** [comment]
Do you mean add-ons in the nomination and the updates queue?

**Comment by eviljeff** [comment]
yes.... new addons in the nomination queue and new versions in the updates queue

**Comment by wagnerand** [comment]
I am not sure. @Noitidart might know.

**Comment by eviljeff** [comment]
Can't reproduce with an addon in the nomination queue, only an update to an approved addon.

**Comment by Noitidart** [comment]
Hi all, I only encountered this in the update queue.
