### ISSUE TITLE
403 on "Download file" while reviewing

### ISSUE THREAD

**Issue by rafspiny** [mozilla/addons-server#4750]
**Steps to reproduce it**

1. Choose an addon to review
2. Compare it with an old version
3. Choose a file
4. Click on the link Download <filename>

**What happened**
A 403 page is returned

**What did you expect to happen?**
I expected to see the raw file

**Anything else we should know?**
It is not happening on all files, or for all addons. I experience it on ["Private Tab"](https://addons.mozilla.org/en-US/firefox/addon/private-tab/?src=search) that is not in review anymore.
Here you can find a screen recording at this [link](https://www.dropbox.com/s/xcnl2riu6vtb3fb/AMO%20-%20403%20issue.mp4?dl=0)
It seems to be related to #3007

**Comment by diox** [comment]
We can't reproduce any more so I suspect it's yet another manifestation of (a variant of) mozilla/addons/issues/324 ; the old file you were comparing to was disabled, the path to the file should have changed but that wasn't done by the time you were looking at the version.
