### ISSUE TITLE
No name in "Reviews This Month" from Reviewer Tools for an user without display name set

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4751]
Steps to reproduce:
1. Go to Account Settings and delete your Display Name - https://addons.allizom.org/en-US/firefox/users/edit
2. Go to Reviewer Tools homepage and observe "Reviews This Month" section

Expected results:
Reviewer name and points are listed.

Actual results:
No name, just points.

Notes/Issues:
- I have a username set but is not used in that section.
Verified on FF51(Win 7). Issue is reproducing on AMO-stage and -dev.
Screenshot for this issue:
![2017-02-23_1213](https://cloud.githubusercontent.com/assets/15685960/23254820/03ca630c-f9c2-11e6-8b2a-db453f6ec3b8.png)

**Comment by diox** [comment]
In the corresponding template, we should be using `name` instead of `display_name` so that it falls back to `username` correctly.

**Comment by wagnerand** [comment]
I think we should be using `display_name` generally but fall back to `name` if `display_name` is empty.

**Comment by diox** [comment]
`name` uses `display_name` but falls back to `username` if empty.

**Comment by wagnerand** [comment]
So, is this a sub-bug of https://github.com/mozilla/addons-server/issues/3388 ?

**Comment by wagnerand** [comment]
Mentor: @wagnerand 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by raajitr** [comment]
Hi, can i work on this? I am new to contributions.

**Comment by wagnerand** [comment]
Hi, you don't need to ask for permission, just submit a pull request when you are ready!

**Comment by lavish205** [comment]
Hi @raajitr are you still working on this bug?

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Postfix video:
![revname](https://cloud.githubusercontent.com/assets/15685960/25612505/ac0e57f2-2f33-11e7-90b1-8a9f6d1512b7.gif)
