### ISSUE TITLE
Maintain a counter of the number of times an add-on has been approved

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4752]
Prerequisite for #4533 

~~- For each add-on, the counter should start at 0.~~
~~- Uploading a new listed and non-beta version (including initial version) increments the counter, except if previous version was already awaiting review~~
~~- Deleting or rejecting a listed non-beta version awaiting review decrements counter~~

- For each add-on, counter starts at 0 (add-ons that have a public listed version already start at 1 with a migration)
- A human approving a listed version awaiting review increments the counter
- Auto-approving (when we implement it) resets the counter

Counter value should be visible in admin somewhere for debugging.

**Comment by ValentinaPC** [comment]
> Counter value should be visible in admin somewhere for debugging.

Could you provide the place, Mat? Thanks!

P.S.: I recall asking you this on Friday, but...no trace ... (

**Comment by ValentinaPC** [comment]
Verified this as fixed on AMO-dev FF53(Win 7).
After first version of a webextension is submitted and manually approved, the second version can be auto-approved and the counter is set to "0"(also, the counter is reset to 0 after every auto-approval).
Counter will be incremented every time a new version is added and manually approved.

Please see postfix screenshots:
![no_version_approved_after_last_auto-approve](https://cloud.githubusercontent.com/assets/15685960/25377290/cdd554e6-29af-11e7-9462-fb536d5183d3.png)
![2017-04-24_1808](https://cloud.githubusercontent.com/assets/15685960/25377328/d5dc68f0-29af-11e7-9969-cfc59abfead7.png)
![1_approve_after_auto](https://cloud.githubusercontent.com/assets/15685960/25377339/db72a1bc-29af-11e7-9edd-770f7917f4c1.png)
