### ISSUE TITLE
Reviewed themes displayed through search results in "Pending" queue (with pending status)

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4753]
Steps to reproduce:
1. Load Reviewer Tools - Themes page: https://addons-dev.allizom.org/en-US/editors/themes
2. Click "Queues" - "Pending" - observe results
3. Make a search i.e. "test"

Expected results:
Themes with "test" in their name, that are pending review are listed.

Actual results:
Themes that are already reviewed are listed through results.

Notes/Issues:
- _themes already reviewed that are listed through results have "pending" status._
- same issue while searching in Flagged queue, but with "pending-review" status (for already approved themes)
Verified on FF51(Win 7). Issue is reproducing on AMO-stage and -dev.
Video for this issue:
![not-](https://cloud.githubusercontent.com/assets/15685960/23261057/4f3caf96-f9dd-11e6-94a1-a333470e71f3.gif)

**Comment by eviljeff** [comment]
I can't reproduce this on -dev - are there particular themes that are affected?

**Comment by ValentinaPC** [comment]
I can not longer reproduce this either, on AMO-dev, but seems to still reproduce on AMO-stage.
Theme example: https://addons.allizom.org/en-US/editors/themes/queue/single/francais-theme
Theme is listed in Pending queue and has the status "pending" even if the theme was flagged.
See screenshot also: 
![2017-03-21_1545](https://cloud.githubusercontent.com/assets/15685960/24150094/770c2036-0e4d-11e7-88bd-e466e6e8518a.png)

**Comment by eviljeff** [comment]
it's showing as flagged now... it sounds like caching

**Comment by ValentinaPC** [comment]
> it's showing as flagged now... it sounds like caching

You must do a search, and in search results see its status.
Please see video:
![flagged](https://cloud.githubusercontent.com/assets/15685960/24255240/93ccb6e4-0fed-11e7-8c33-0878343047cc.gif)

**Comment by eviljeff** [comment]
oh, I see now
