### ISSUE TITLE
Deleted add-ons have "Request more information" option that returns a 505 error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4754]
Steps to reproduce:
1. Load Reviewer Tools -> All Unlisted Add-ons queue https://addons.allizom.org/en-US/editors/unlisted_queue/all
2. Pick a deleted add-on i.e. https://addons.allizom.org/en-US/editors/review-unlisted/618559
3. Write a "Request more information/Request super-review"

Expected results:
User cannot give a "Request more information/Request super-review" or the options are not available.

Actual results:
User can give a "Request more information/Request super-review" but a 505 error page is displayed.

Notes/Issues:
- "comment" option does not return a 505 error, but is not saved - but "Review successfully processed." message is displayed.
- while looking through all unlisted add-on you cannot glimpse which are with a "deleted" status. (I've ended up by mistake in a deleted add-on review page and did not knew why I cannot leave a note )

Verified on FF51(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Video for this issue:
![rt](https://cloud.githubusercontent.com/assets/15685960/23262516/ab8f50fe-f9e3-11e6-964c-ae2c79886fed.gif)

**Comment by eviljeff** [comment]
closing in favour of #4760
