### ISSUE TITLE
No way to find out with what account user is logged from new Dev Hub page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4768]
Steps to reproduce:
1. Load Dev Hub new landing page while being logged in: https://addons-dev.allizom.org/en-US/developers/
2. Observe with which account you are logged in

Expected results:
A username/account is listed.

Actual results:
The username or account is not listed anywhere in new Dev Hub landing page, logged in view.

Notes/Issues:
- Clicking on account picture, user gets redirected to its profile - user must navigate back and forth to find out with what account is logged and to continue its activity, which can be annoying. 
- Suggestion: we can show it at hover over account picture.

Verified on FF51(Win 7). Issue is reproducing all around AMO-servers.
Screenshot for this issue: 
![2017-02-24_1506](https://cloud.githubusercontent.com/assets/15685960/23304577/328236de-faa3-11e6-8f3d-5f52cc101bc7.png)

**Comment by muffinresearch** [comment]
> Suggestion: we can show it at hover over account picture.

Hover won't work for mobile so we'll need some UX input to this.

**Comment by designakt** [comment]
We show the users image, and to make it more explicit a tooltip could be added. But I don't think we need to be more explicit about it than that.

**Comment by EnTeQuAk** [comment]
The tooltip part is relatively useless for mobile imho, I'm closing this as it's currently the best we can do.
