### ISSUE TITLE
Add-ons/WebExtensions can’t be approved

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#4778]
### Describe the problem and steps to reproduce it:
Try approving this add-on https://addons-dev.allizom.org/en-US/editors/review/allpermissionsaddon-1-0 

### What happened?
The Add-on is not approved and the message “Oops! We had an error” it is displayed.

### What did you expect to happen?
The Add-on is approved.

### Anything else we should know?
Verified on FF54.0a1 under Win 7 64-bit.
This issue is reproducing only on -dev.
Please see the video for this bug :
![approve](https://cloud.githubusercontent.com/assets/15885467/23362909/a4e2d134-fd00-11e6-9327-69f60fdfc3fc.gif)

**Comment by wagnerand** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/384427/

Looks like it's because migration 923 failed, as @diox mentioned.

**Comment by diox** [comment]
Fixed in #4779

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on Firefox 54.0a1 under Wind 7 64-bit.
Postfix video:
![approved](https://cloud.githubusercontent.com/assets/15885467/23365745/d68f9e68-fd0c-11e6-9fe9-517ff2ca42f3.gif)
