### ISSUE TITLE
Small RTL issue for "Mobile Add-ons site" message banner

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4791]
Steps to reproduce:
1. Load AMO-dev page in a RTL language ie. https://addons-dev.allizom.org/ar/firefox/
2. Resize the browser (under 500 px width)
3. Check the "Mobile Add-ons site" info message

Expected results:
There are no display or layout issues.

Actual results:
The `x` mark overlays the info.

Notes/Issues:
Verified on FF51(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue:
![rtl](https://cloud.githubusercontent.com/assets/15685960/23399456/ebeb0e90-fda8-11e6-80b6-2562f2687d57.png)

**Comment by diox** [comment]
Mobile site has been migrated to a new one, so this is no longer valid.

**Comment by ValentinaPC** [comment]
This is not a mobile site bug , to be fixed by mobile redesign. 
AMO server displays a message for the user to use the mobile site, while using browser under some dimensions.

Screenshot for en-US locale and RTL locales:
![info](https://cloud.githubusercontent.com/assets/15685960/24150464/78100a14-0e4e-11e7-9d47-6ac1effc8dcf.png)

**Comment by EnTeQuAk** [comment]
Ah, sorry, we misunderstood the issue. It's a RTL bug really.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @tofumatt

**Comment by ahmedhasan07** [comment]
I am working on it.

**Comment by ValentinaPC** [comment]
This is not yet in -dev, can we check why?
Thanks!
![banner](https://user-images.githubusercontent.com/15685960/27419894-ea7b9eb2-572b-11e7-9a3c-88217c6d88f5.png)

**Comment by EnTeQuAk** [comment]
Will be in a few hours, we're currently experiencing a very slow migration on -dev (well, my fault!) Once it succeeded, I'll update the issue.

**Comment by atiqueahmedziad** [comment]
@ValentinaPC this is now fixed in -dev

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix screenshot: 
![rtl](https://user-images.githubusercontent.com/15685960/27472978-1f2e9922-5806-11e7-9c69-b085d0e4f130.png)
