### ISSUE TITLE
No longer use MD5

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4793]
MD5 is highly unsafe. Because it's easy to break, we can't rely on its integrity anymore.

This has been fixed in #4769 already, so here are QA instructions:

1) Please make sure PayPal contributions work as usual.
2) Collection pages should be displayed correctly, especially the counter at the bottom of the page, showing the number of entries in a collection.
3) For reviewers, the file viewer should correctly display the files. Also, at the bottom of the file viewer, it should display the Sha256 sum of the file (instead of previously md5 sum).

**Comment by muffinresearch** [comment]
Marking this closed as the PR is merged.

**Comment by vcarciu** [comment]
Verified as fixed:

- Contributions works as expected while logged in and out, with different add-ons and amount of contributions
- Collections pages looks good including the counter at the bottom of the page
- File reviewer is correctly displaying the files and there is a Sha256 sum instead of md5
