### ISSUE TITLE
Only restrict @mozilla.(com|org) guids for new add-ons

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4796]
#4688 introduced a restriction for IDs ending in `@mozilla.(com|org)`. However, we have hundreds of existing add-ons that use IDs like that and can't change ID now. This restriction should only apply to new add-ons, not updates. This is already blocking at least one developer, so we should fix this asap.

**Comment by bilalasif** [comment]
Hi,
I recently submitted a new version of the addon that was already present on mozilla store
When i submit it, I get this validation error: 
"You cannot submit an add-on with a guid ending "@mozilla.org" ".

I dont understand what needs to be done about this. I asked addon reviewers they asked me to file this bug report here any help would be appreciated

**Comment by diox** [comment]
Hi,

Sorry about that. We fixed your issue, but it's not live in production yet, it should be on Thursday around noon PST.

**Comment by vcarciu** [comment]
Verified as fixed for both @mozilla.(com|org) guids. I was able to upload new versions for an already listed submitted add-on

**Comment by itsazzad** [comment]
```
Your add-on failed validation with 1 error.
You cannot submit an add-on with a guid ending "@mozilla.org"
```

![screen shot 2017-07-19 at 4 36 23 am](https://user-images.githubusercontent.com/54909/28342822-04fd55d0-6c3c-11e7-8e49-ea2bf6cfd23e.png)

But `All tests passed successfully.` https://addons.mozilla.org/en-us/developers/upload/c5a36d4fb2d6487ba5f74dd6eb32e0af

**Comment by eviljeff** [comment]
@itsazzad it's not a validation error as such, rather a restriction on uploads.  What part don't you understand?  The restriction is literally as it says: you cannot submit an add-on with a guid ending "@mozilla.org" (unless you have a @mozilla.com email address)

**Comment by itsazzad** [comment]
From where this guid coming? I have never used any such thing before

**Comment by eviljeff** [comment]
it's in the manifest file - are you trying to upload a sample xpi from somewhere?  

A closed issue isn't really the best location for this discussion - asking in #addons on irc https://wiki.mozilla.org/IRC#Project_Channels is probably the easiest way.
