### ISSUE TITLE
Disco Pane content update - March 2017

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#4799]
For the **16 March** push, can we please REMOVE: 

- YouTube High Definition
- all three current themes

... and REPLACE them with Awesome Screenshot Plus and three new themes. 

**Take screenshots** 
with [Awesome Screenshot Plus](https://addons.mozilla.org/firefox/addon/awesome-screenshot-capture-/)
More than just screenshots, Awesome Screenshot Plus lets you annotate images with text and graphics. Storing and sharing files is a breeze. 

[themes]

[Tender Spring Rain](https://addons.mozilla.org/firefox/addon/tender-spring-rain/) by takatan
[Abstract Splash](https://addons.mozilla.org/firefox/addon/abstract-splash/) by Ljubichica
[Owls](https://addons.mozilla.org/firefox/addon/owls-by-cp/) by Crazy Psychiatrist

Also please order the full page of content like so:

Tender Spring Rain 
Awesome Screenshot Plus
uBlock
Abstract Splash
Video DownloadHelper
Emoji Keyboard
Owls

**Comment by muffinresearch** [comment]
This one got missed, let's land it ASAP and see where translations are at with a view to pushing this out next week (23rd March)

**Comment by EnTeQuAk** [comment]
As a side-note, the link for "Awesome Screenshot Plus" is broken, I am assuming that https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate is what is being meant here?

**Comment by muffinresearch** [comment]
> As a side-note, the link for "Awesome Screenshot Plus" is broken, I am assuming that https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate is what is being meant here?

@devaneymoz can you confirm that's the link expected? ^

**Comment by devaneymoz** [comment]
Yes that's the link I intended, sorry!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF52(Win 7).
Postfix screenshot: 
![disco](https://cloud.githubusercontent.com/assets/15685960/24287934/30bc10da-1084-11e7-9731-94cf2561197b.png)

Note: all links work as expected.
