### ISSUE TITLE
Add-ons stats should show the number of enabled users first

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#4801]
Over the last few years the top 10 add-ons has been a pretty accurate representation of the most popular add-ons on AMO. I don't have the stats to prove it, but I bet a few installs come from being featured there.

Sadly one add-on currently has an extremely large number of user disableds occuring on it. Basically people don't like the add-on and aren't enabling it. I think the top 10 (and other pages that show the number of users) should show the number of enabled users.

This number is available on the stats page for example:

https://addons.mozilla.org/en-GB/firefox/addon/adblock-plus/statistics/usage/status/?last=30

That number compares favourably to the high level number of users shown in the top 10 list and details pages for that add-on, we can see that its an add-on people choose to use.

I think we should be using this everywhere as the most important stat to show, not the just number of Firefox instances it sits on. I know this might be a controversial change, but hopefully a relatively small code change.

cc'ing @jvillalobos for policy help here on making an announcement

**Comment by wagnerand** [comment]
Is this a dupe of #3632?

**Comment by andymckay** [comment]
Yes, thanks.
