### ISSUE TITLE
Legacy update for webextension add-on fails validation

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4810]
### Describe the problem and steps to reproduce it:

1. Submit a webextension as unlisted, e.g. [webext.zip](https://github.com/mozilla/addons-server/files/810746/webext.zip)
2. Submit an SDK file as an update for that add-on, e.g. [sdk.zip](https://github.com/mozilla/addons-server/files/810749/sdk.zip) (might have to rename to `.xpi`)

### What happened?

The validation summary on the upload page does not indicate any errors. Clicking on "View full report" says `Add-on failed validation.` though.
Clicking on "Sign add-on" fails with `There was an error with your upload. Please try again.` 

### What did you expect to happen?

The validation and signing succeeds.

### Anything else we should know?

The error is in https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/tasks.py#L367 as we always increase the error-counter even when it is just a warning, like for unlisted submissions (see line 361).

**Comment by wagnerand** [comment]
Btw, this is a regression from https://github.com/mozilla/addons-server/commit/d6f6f14d98be6967810d7f9141662d0cf5384af3#diff-c997d74049a3a470ef41efaa2c6552a1R304.

**Comment by jvillalobos** [comment]
Is this a dupe of #3599?

**Comment by wagnerand** [comment]
Looks like it, thanks!
