### ISSUE TITLE
Use addon link instead of addon name in /collections/.../.../edit/#addons-edit's addons-list

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#4813]
### Describe the problem and steps to reproduce it:
Editing a collection.

### What happened?
Can not go to added add-ons's details page, just a name.

### What did you expect to happen?
Linked add-on name.

### Anything else we should know?
https://github.com/mozilla/addons-server/blob/0c2b633c592a882a51698949f2262773d1462b5b/src/olympia/bandwagon/templates/bandwagon/includes/addon_selector.html#L35

**Comment by muffinresearch** [comment]
This is superceded by the new collections feature due to arrive in the new frontend this quarter. See https://github.com/mozilla/addons-frontend/issues/2782
