### ISSUE TITLE
Developer profile is not created if the <<optional>> fields from "Manage Developer Profile" page are not filled

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4817]
Steps to reproduce:
1. Load "Manage Developer Profile" for an add-on i.e. https://addons.allizom.org/en-US/developers/addon/test-contribution/profile
2. Leave the two _optional_ fields - "Why did you make this add-on?" and "What's next for this add-on?" - empty
3. Go to "Manage Payments" and set contributions

Expected results:
User can set contributions.

Actual results:
User cannot set contributions because he did not complete its "developer profile".

Notes/Issues:
- optional fields are not optional.
Verified on FF51(Win 7). Issue is reproducing on all AMO servers.
Video for this issue: 
![optional](https://cloud.githubusercontent.com/assets/15685960/23496653/facd990c-ff27-11e6-825a-dbc2ef39ee61.gif)

**Comment by diox** [comment]
Note: according to the code those fields should *not* be optional for an add-on that takes contributions.

**Comment by diox** [comment]
This page will be removed in #6072 so I don't think it's worth looking into this.
