### ISSUE TITLE
All-versions unlisted add-on has no info about this in Dev Hub landing page 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4818]
Steps to reproduce:
1. Submit an unlisted add-on in AMO-stage https://addons.allizom.org/en-US/developers/addon/submit/distribution
2. Load Dev Hub landing page https://addons.allizom.org/en-US/developers/
3. Observe "My Add-ons" section

Expected results:
A label/text differentiating the unlisted submitted add-on for the other add-ons is displayed.

Actual results:
No label/text differentiating the unlisted submitted add-on for the other add-ons.

Notes/Issues:
- we could add an "Unlisted" label/info
Verified on FF51(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Screenshot for this issue:
![unlisted](https://cloud.githubusercontent.com/assets/15685960/23498941/9fe53828-ff32-11e6-9a08-d82d638fab1f.png)

**Comment by EnTeQuAk** [comment]
I think that's a good idea, showing that information explicitly is probably more clear.

**Comment by jvillalobos** [comment]
In the Status & Versions page we only show the `AMO` and `Self` tags when there are versions of both kinds, since most developers have one or the other and not both, and we didn't want to clutter things too much. I think it makes sense to show them on the devhub landing page, since you could have both.

Additionally, unlisted versions should have their status (usually `Approved`) next to them, like it's done on the Status & Versions page.

**Comment by ValentinaPC** [comment]
@jvillalobos : What would be the difference between an add-on with all version listed and and add-on with all versions unlisted in Dev Hub landing page?

**Comment by jvillalobos** [comment]
In the previous comments I'm recommending we show the `AMO` or `Self` tag next to the version, so at least you know what channel is the latest one. However, we won't show if it's only-listed, only-unlisted, or mixed. That distinction is too specific to be useful IMO.

**Comment by pwalm** [comment]
Do you guys need guidance from ux on this? Or do you just need to a show a tag or something similar to denote this extensions status?

**Comment by eviljeff** [comment]
@jvillalobos does something need to be done for this issue.  If so, what?

**Comment by jvillalobos** [comment]
I haven't heard from developers that this is an issue, so I think it's safe to close. We also plan to look into revamping the Developer Hub in Q1.
