### ISSUE TITLE
"Prev" screenshots navigation arrows are displayed for a moment at page refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4819]
Steps to reproduce:
1. Load details page for an add-on with screenshots  i.e. https://addons.mozilla.org/en-US/firefox/addon/smart-https/?src=hp-dl-featured
2. Refresh the page while observing the screenshots section

Expected results:
There are no display or layout issues.

Actual results:
"Prev" navigation arrows are displayed for a moment.

Notes/Issues:
Verified on FF51(Win 7). Issue is reproducing all around AMO servers.
Video for this issue:
![prev](https://cloud.githubusercontent.com/assets/15685960/23499518/1e408612-ff35-11e6-9f3a-68403dd027b4.gif)

**Comment by muffinresearch** [comment]
Probably not worth spending time on due to the new desktop frontend being started soon.

**Comment by ValentinaPC** [comment]
Maybe worth checking this after desktop redesign.

**Comment by eviljeff** [comment]
This will be implemented on addons-frontend so closing this on addons-server.
