### ISSUE TITLE
Suggestion selection does not work properly while using the keyboard buttons

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#4821]
**Steps to reproduce:**
1.Navigate to https://addons-dev.allizom.org/en-US/firefox/
2.Type a key in the search bar.
3.Hover over any item from drop-down list using the keyboard arrows and press enter.

**Expected results:**
The corresponding add-on listing page is loaded.

**Actual results:**
The search is performed.

**Additional notes:**
- This issue reproduces on AMO-dev and AMO-stage using Firefox 54.0a1 (2017-03-01) under Windows 10 64-bit.
- Please see the attached screencast for this issue:
![animation](https://cloud.githubusercontent.com/assets/18114210/23510233/5ba5e548-ff61-11e6-9eb5-8c64a3cc5d22.gif)

**Comment by ValentinaPC** [comment]
This issue is also reproducing while selecting a search suggestion (with arrows or mouse hover) and clicking on the green arrow near the search field. 
Please see video: 
![search](https://cloud.githubusercontent.com/assets/15685960/23704889/b0e3e5f2-040f-11e7-8c3b-104eef8f24d0.gif)

**Comment by diox** [comment]
We won't get to fix that issue before it gets remade in addons-frontend.

**Comment by Gitoffthelawn** [comment]
What is the ETA to land the new addons-frontend?
