### ISSUE TITLE
Permissions are not listed in descending order of priority

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#4822]
**Steps to reproduce:**
1. Navigate to https://addons-dev.allizom.org/en-US/firefox/addon/permissionsorder1/
2. Click on “Permissions” link.

**Expected results:**
Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1339952#c1 the permissions are listed as follows:
- the hosts permission: because this is probably the most understandable risk. It's related directly to what people use firefox for, browsing.
- native messaging: because it means you are getting out of the Firefox sandbox.
- the rest (no order)

**Actual results:**
Permissions are not listed in descending order of priority. 

**Additional notes:**
- This issue reproduces on AMO-dev using Firefox 54.0a1 (2017-03-02) under Windows 10 64-bit.
- This priority order is already applied in installation permission pop-up.
- Please see the attached screenshots for this issue:
![2017-03-02_1617](https://cloud.githubusercontent.com/assets/18114210/23511114/cb5df15c-ff64-11e6-847d-7a1a1a5d5eab.png)
![2017-03-02_1618](https://cloud.githubusercontent.com/assets/18114210/23511120/d1e4794c-ff64-11e6-9568-27f395b07747.png)

**Comment by eviljeff** [comment]
The PRD didn't specify there was an order of priority so...

**Comment by vasilicamihasca** [comment]
Seems that clipboardRead and clipboardWrite permissions are not displayed in the same order they appear in browser pop-up, The browser displays permissions in the order they are declared in manifest json, excepting hosts and native messaging. Tested using https://addons-dev.allizom.org/en-US/firefox/addon/promptable5/ on Firefox 55.0a1 (2017-03-09):
![2017-03-10_1622](https://cloud.githubusercontent.com/assets/18114210/23798975/80d9e608-05af-11e7-9b16-9a0b72f40b36.png)
![2017-03-10_1621](https://cloud.githubusercontent.com/assets/18114210/23798978/84a2e352-05af-11e7-8e15-623e01124a9f.png)

**Comment by eviljeff** [comment]
There's no particular reason to display them in the manifest order - they are displayed in alphabetical (of the permission name) instead.  It would be better if Firefox did that too because that way the ordering is consistent between different add-ons.

**Comment by vasilicamihasca** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1346722 at the suggestion of eviljeff .

Verified fixed on AMO-dev using Firefox 55.0a1 (2017-03-12). Permissions are successfully listed in descending order of priority. Postfix screenshot:
![2017-03-13_1246](https://cloud.githubusercontent.com/assets/18114210/23851251/88d8c480-07eb-11e7-8766-89a5061524e3.png)
