### ISSUE TITLE
French translations have not been deployed for several weeks

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/addons-server#4823]
On about:addons for instance, the translation for Video Download Helper has not been deployed for French, while it has been deployed for other locales (Italian for instance), and the French translation has been committed first https://discovery.addons.mozilla.org/fr/firefox/discovery/pane/54.0a1/Darwin/normal

The dev server is also not showing the latest translations on this page https://addons-dev.allizom.org/fr/developers/ 

So I suspect there is an issue with the French PO file, preventing it from being deployed on any server.

Note that Firefox users are seeing English strings on about:addons, so that would be great to understand the root cause to prevent this from happening in the future

**Comment by TheoChevalier** [comment]
@diox Any idea what’s happening here?

**Comment by peiying2** [comment]
@andymckay could you help address the issue?

**Comment by diox** [comment]
Yes, at least one of the strings was incorrectly translated, `dennis-cmd` complains and I suspect that prevents file from being compiled automatically when we deploy.

```
% dennis-cmd lint --errorsonly fr/LC_MESSAGES/django.po                                                                            
dennis version 0.8
>>> Working on: /home/mat/work/mozilla/olympia/locale/fr/LC_MESSAGES/django.po
E201: invalid variables: %(reg)s
5820:#: src/olympia/devhub/templates/devhub/new-landing/components/navigation.html
5821:#, python-format
5822:msgid "<a href=\"%(register)s\">Register</a> or <a href=\"%(login)s\">Sign In</a>"
5823:msgstr "<a href=\"%(reg)s\">S’inscrire</a> ou <a href=\"%(login)s\">Se connecter</a>"

Totals
  Errors:       1
```

**Comment by diox** [comment]
The string should be fixed in pontoon. @TheoChevalier can you do that ? 

It would be nice if pontoon could lint the `.po` files to prevent this kind of issue in the future. We could add it to our tests but since pontoon commits directly to our repos I am not sure if it's the best place to do it...

**Comment by TheoChevalier** [comment]
Crap :/ Thanks @diox , fixed in https://github.com/mozilla/addons-server/commit/74ba007616f19d9cb9e86fef29103ab35a89d6f9
Let’s hope this was the only one…

No idea if Pontoon can do that, but that might be something to run on web status app? cc @flodolo

**Comment by diox** [comment]
According to `dennis-cmd` there are no other issues in `fr`. In other languages though, I can see those 3:
```
>>> Working on: /home/mat/work/mozilla/olympia/locale/pa_IN/LC_MESSAGES/django.po
E201: invalid variables: { user}
1712:#: src/olympia/amo/log.py
1713:msgid "Admin {0} viewed activity log for {user}."
1714:msgstr "ਐਡਮਿਨ {0} ਨੇ { user} ਲਈ ਸਰਗਰਮੀ ਲਾਗ ਸਮਝਿਆ।"

Totals
  Errors:       1

>>> Working on: /home/mat/work/mozilla/olympia/locale/pa/LC_MESSAGES/django.po
E201: invalid variables: { user}
1712:#: src/olympia/amo/log.py
1713:msgid "Admin {0} viewed activity log for {user}."
1714:msgstr "ਐਡਮਿਨ {0} ਨੇ { user} ਲਈ ਸਰਗਰਮੀ ਲਾਗ ਸਮਝਿਆ।"

Totals
  Errors:       1

>>> Working on: /home/mat/work/mozilla/olympia/locale/pt_PT/LC_MESSAGES/djangojs.po
E201: invalid variables: { 0}
695:#. L10n: {0} is an integer.
696:#: static/js/impala/stats/csv_keys.js
697:msgid "Add-ons Created, last {0} days"
698:msgstr "Extras criados, últimos{ 0} dias"

Totals
  Errors:       1
```

**Comment by flodolo** [comment]
Adding a linter to webstatus is not an option, since it will be replace by the new unified dashboard.
I know there are discussion on running linters as part of the new dashboard though.

**Comment by TheoChevalier** [comment]
FTR, fixed pt-PT and pa-IN
https://github.com/mozilla/addons-server/commit/3ab698a88a803222d43ea62fc16c413b9056db39
https://github.com/mozilla/addons-server/commit/f2eb7211e43503d0b947748389e39226eace3138
