### ISSUE TITLE
"Reply" button from "Review history" Dev Hub page is not RTL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4827]
Steps to reproduce:
1. Load Manage Status and Versions page for an add-on with at least 1 version i.e. https://addons-dev.allizom.org/en-US/developers/addon/permissionsorder6/versions
2. Change the language to a RTL one -  https://addons-dev.allizom.org/fa/developers/addon/permissionsorder6/versions
3. Click the "Review history" link

Expected results:
"Reply" button is RTL.

Actual results:
"Reply" button is LTR.

Notes/Issues:
Verified on FF51(Win 7). Issue is reproducing on all AMO servers.
Screenshot for this issue:
![reply](https://cloud.githubusercontent.com/assets/15685960/23545423/fb1a57ec-0003-11e7-9b96-ab3d4a769e05.png)

**Comment by eviljeff** [comment]
button doesn't need to be on either side really so right is as good as left.
