### ISSUE TITLE
"View listing" redirects to "Mobile Add-ons" page for an "Android" add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4829]
Steps to reproduce:
1. Go to "Firefox for Android" page on desktop https://addons-dev.allizom.org/en-US/android/
2. Load "Full Screen mobile" add-on page - https://addons-dev.allizom.org/en-US/android/addon/full-screen-252573/
3. Click "Manage" button
4. Click "View listing"

Expected results:
User is redirected back to android add-on details page.

Actual results:
User is redirected to mobile add-on details page.

Notes/Issues:
- another example: https://addons-dev.allizom.org/en-US/android/addon/phony/
- add-on has both "Firefox For Android" and "Mobile" options in manage last version page

Verified on FF51(Win 7). Issue is only reproducing on AMO-dev.
Video for this issue:
![android-vs-mobile](https://cloud.githubusercontent.com/assets/15685960/23553888/6a6baa8e-002b-11e7-826a-2af64556b9b1.gif)

**Comment by eviljeff** [comment]
I'm not sure how this is a bug - if the add-on supports multiple platforms then devhub has got to go to the display page for one of them.

**Comment by ValentinaPC** [comment]
> I'm not sure how this is a bug - if the add-on supports multiple platforms then devhub has got to go to the display page for one of them.
Why isn't the user redirected to the platform he access the add-on from aka "Android Add-ons" and is sent to any other page beside the intuitive one?

**Comment by eviljeff** [comment]
Once they go to devhub the platform is dropped from the url.  So if they decide to go back to the listing page we don't know what platform they came from.

**Comment by diox** [comment]
That add-on is set to support both the old mobile and android platforms, so you'll get redirected to either one of those.
