### ISSUE TITLE
When some of the options are not checkmarked when submitting a new add-on, the page should be scrolled to the section where the (first) error is thrown

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-server#4834]
*Environment*
Firefox: Nightly 54.0a1
Server: -dev
OS: Windows 10

*Steps to reproduce*
1. Go to AMO page.
2. Start procedure for submitting new add-on and reach the “Submit a New Add-on” page.
3. Check an option only on the first section (Select up to 2 Firefox categories for this add-on: ). 
4. Leave the others blank and click Submit. Observe the position of the page after the refresh.

*Expected results*
The page should be scrolled on the sections where errors are thrown (for not checkmarking any option).

*Actual results*
The name displayed in Listing is the initial one.
In the add-on manager the displayed name is the new one, as well as in the Permission prompt when installing the webextension.

*Notes*
1. Reproducibility: 5/5.
2. The issue is reproducible also on production on release build (51.0.1).

![scroll to error](https://cloud.githubusercontent.com/assets/26005101/23559493/dc80ba74-003f-11e7-82e6-1b35bf5ec6b3.gif)

**Comment by EnTeQuAk** [comment]
That's a good enhancement but if we want that it should land in addons-frontend and not on addons-server anymore. Also, usually something like that is quite hard to do correct.

I'm going to close this since it probably won't be touched / fixed / added in addons-server any time soon if ever.
