### ISSUE TITLE
When confirming the delete of an add-on, the entered text should escape space in front and at the back

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-server#4836]
*Environment*
Firefox: Nightly 54.0a1
Server: -dev
OS: Windows 10

*Steps to reproduce*
1. Go to AMO page.
2. Go to Tools > Manage My Submissions and click on an add-on.
3. Go to Manage & Status versions. 
4. Click Delete Add-on button.
5. On the confirmation prompt, enter the required text with spaces in front and/or at back and confirm the operation. Observe the behavior.

*Expected results*
The spaces should be escaped and the operation should be completed successfully.

*Actual results*
The spaces are treated as characters so the string won’t match, thus an error is thrown for entering the correct text.

*Notes*
1. Reproducibility: 5/5.
2. The issue is reproducible also on production on release build (51.0.1).

**Comment by diox** [comment]
You should enter the exact add-on name, spaces should not be ignored.
