### ISSUE TITLE
Don't show permissions link for add-ons that aren't extensions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4841]
Just noticed that the permissions link is being shown for all add-on types: https://addons.mozilla.org/addon/metal-lion-australis-theme/

Permissions are only relevant for extensions, not other add-on types (complete themes, dictionaries, language packs, Open Search).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7).
Postfix screenshots (Complete Themes, Dictionaries, Lang Packs or Search Tools):
![permissions](https://cloud.githubusercontent.com/assets/15685960/23601177/d1ece014-0252-11e7-8754-468578dad0c0.png)
