### ISSUE TITLE
Consider not reporting frontend JS errors to Sentry

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#4845]
Currently, any Javascript error gets reported to Sentry here: https://sentry.prod.mozaws.net/operations/frontend-prod/

@jasonthomas says that this generates a lot of traffic to Sentry which is one reason that Sentry is slow to render new events (for any other project).

Perhaps we could turn off frontend JS errors until we need them? In other words, maybe we could introduce a waffle switch that can be toggled only when someone knows about an error they would like to capture in prod. There are downsides to this of course but maybe they are worth it.

**Comment by diox** [comment]
Should this be filed in addons-frontend instead ?

**Comment by jasonthomas** [comment]
No, this is for ravenjs configured for assets generated by addons-server. 

https://github.com/mozilla/addons-server/blob/master/src/olympia/conf/prod/settings.py#L252-L253
