### ISSUE TITLE
I changed the name and url of my addon and now I get a 404 error

### ISSUE THREAD

**Issue by Ideandro** [mozilla/addons-server#4850]
### Describe the problem and steps to reproduce it:
I made an addon named:
**Secrets Revealer (for Facebook™)**

After many days I made new version 2.0.0 with many improvements and new name:
[Secret Revealer (for Facebook™)](https://addons.mozilla.org/En-us/firefox/addon/secret-revealer-for-facebook/)
without the end "**s**" of "Secret**s**"...

So **I changed the URL** of my addon and now, when I [search addon on Google](https://www.google.it/#q=secret+revealer+for+facebook), I [found your website here](https://addons.mozilla.org/En-us/firefox/addon/secrets-revealer-for-facebook/?src=cb-dl-created) at the first position:
https://addons.mozilla.org/En-us/firefox/addon/secrets-revealer-for-facebook/?src=cb-dl-created
with "**s**" at the end of "secret**s**"

**But I get an 404 error!**

### What happened?
The search of Secret Revealer (for Facebook™) on Google **results in a wrong (404) URL**

### What did you expect to happen?
Is possible **to update**, on Google search, the page of addon?

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

--> **old page of addon**:
--> https://addons.mozilla.org/En-us/firefox/addon/secrets-revealer-for-facebook/
--> results: "_We're sorry, but we can't find what you're looking for._"

--> **NEW PAGE OF ADDON**:
--> https://addons.mozilla.org/En-us/firefox/addon/secret-revealer-for-facebook/
--> results: **Yhaaa!!! All right!**

# Thank you! ;)

**Comment by eviljeff** [comment]
We aren't responsible for what Google has in it's search results.  The url they show will be a combination of links to your addon (i.e. the old one) from other websites and what they found while spidering through AMO before you changed it.

**Comment by Ideandro** [comment]
Ok, thanks, but do you know how much time **is still needed** for the review of the new version of [my addon](https://addons.mozilla.org/En-us/firefox/addon/secret-revealer-for-facebook/)?

I'm waiting to be approved to update the post on my blog and edit the title with the new name for SEO.
