### ISSUE TITLE
[Review Tools] Undeleted Reviews should go back to the Moderated Reviews

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#4852]
I was processing over 1800 **Moderated Reviews** and I deleted 3 which I did not plan to.
I undeleted them from **Moderated Review Log**.

I expected them to go back to the **Moderated Reviews** queue but instead they were cleared as if "**Keep review; remove flags**" was selected for them.

While this is quite a minor issue, it would have been more appropriate for the undeleted items to go back to the **Moderated Reviews** queue.

**Comment by jvillalobos** [comment]
Why would it make sense to bring them back to moderation? If they were deleted and it's decided they shouldn't have been deleted, then the only other option is to publish them.

**Comment by erosman** [comment]
There are 3 options for the review. IMHO, it should go back to the queue as if it was never dealt with. That is what undelete should mean (ie undo),. It shouldn't mean accept ... but that is my opinion. :)

**Comment by eviljeff** [comment]
We'll go with what @jvillalobos said.  The only reason you'd want to revert the deletion via the moderated review log is if they should be kept so reflagging them seems a little redundant.
