### ISSUE TITLE
Complete themes page for Android should 404

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4869]
The page for Android + Complete Themes is a blank page (see https://github.com/mozilla/addons-frontend/issues/1916) so we should 404 on it rather than showing an empty page.

-----

Steps to reproduce:
1. Load AMO-dev Complete Themes page on mobile https://addons-dev.allizom.org/en-US/android/complete-themes/

Expected results:
404 page is displayed or a page using new mobile redesign.

Actual results:
An old AMO page is displayed.

Notes/Issues:
Verified on FF51(Android 6.0.1).
Screenshot for this issue:
![ct](https://cloud.githubusercontent.com/assets/15685960/23355752/e8976762-fcdf-11e6-98a3-d604d6b20266.png)

**Comment by harikishen** [comment]
I would like to work on this.

**Comment by harikishen** [comment]
But this is the output i get
<img width="512" alt="image" src="https://cloud.githubusercontent.com/assets/8170184/26051702/963946ba-3980-11e7-810a-4b0faff864f0.png">
Not the one mentioned in the issue.

**Comment by ValentinaPC** [comment]
@harikishen I think meanwhile some changes where introduced, and the results from the initial issue, changed.

@tofumatt : I am also receiving the page from the @harikishen 's comment.
Is this the case? Showing an empty page for Complete Themes homepage?
Thanks!

**Comment by tofumatt** [comment]
Ah yes, because of how we fallback to addons-server the page displayed now is the correct one; it used to show the mobile one but does so no longer.

Still, it arguably isn't a valid URL as we don't serve "complete themes" for Android so it should 404 IMO.

**Comment by muffinresearch** [comment]
Afaict this should 404 when the old site is switched off so this is probably a wontfix.

**Comment by eviljeff** [comment]
This page 404s now
