### ISSUE TITLE
The message about permissions for URLs should be clear and unequivocal

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-server#4870]
*Environment*
Firefox: Nightly 54.0a1
Server: -dev
OS: Windows 10

*Steps to reproduce*
1. Submit and approve an extension with host permissions for a few websites.
2. Go to the listing page of the extensions and click on Permissions link, near its name. Observe the message referring to the host permissions on the websites.

*Expected results*
The message should be clear and unequivocal about the number of the websites that are included in the host permissions list.
e.g. “Access your data on the following websites:”.

*Actual results*
The message says “Access your data on various websites”.
The term various is ambiguous and does not suggest that the list of websites where the webextension has access to your data is complete. This may lead the user into confusion.

*Notes*
1. Reproducibility: 5/5.

![host persmission urls](https://cloud.githubusercontent.com/assets/26005101/23659041/800d2172-034d-11e7-9691-4eb46d7c0d9f.gif)

**Comment by eviljeff** [comment]
@jvillalobos to decide if any further copy/ux changes needed

**Comment by jvillalobos** [comment]
`Access your data on the following websites:` looks like an improvement to me. @devaneymoz, do you agree?

**Comment by devaneymoz** [comment]
My understanding of this case is that the message may NOT list all of the possible websites (due to the possibility it could be a very high number and not just three or four domains). So the vagueness of "various websites" was intentional. 

If that's not the case (i.e. the message will indeed list all websites), then yes, I like the specificity of "Access your data on the following websites:"

**Comment by jvillalobos** [comment]
Agreed, if `various` is intentional, let's keep it.

**Comment by raresmsv** [comment]
Hi guys,
I agree that the list of websites might be too long and would be difficult to display it in the Permissions prompt. Still, we need to find a formula to inform the user of all the websites he gives access to, by installing a certain webextension.

Regards,
Rares

**Comment by eviljeff** [comment]
> My understanding of this case is that the message may NOT list all of the possible websites (due to the possibility it could be a very high number and not just three or four domains).

When expanded, the message __will__ list all of the match patterns manifest specified.  Some may be written to match a specific website (`http://example.org/*`); some may be a pattern that would match multiple websites (`http://*/foo*`).  We display the pattern, not the websites it would match, as it's impossible to enumerate all the websites a `*` would match.  If the manifest specifies a very high number of match patterns, then we would display a very high number of them.

**Comment by jvillalobos** [comment]
Okay, then let's reword so the language is not ambiguous.

**Comment by devaneymoz** [comment]
Sounds good. 

"Access your data on the following websites:" wfm then.

**Comment by raresmsv** [comment]
The issue has been Verified as Fixed on amo-dev on Nightly build 55.0a1.

![urls permissions message](https://cloud.githubusercontent.com/assets/26005101/24109407/3677ddee-0d99-11e7-9501-12b32b7bc020.gif)
