### ISSUE TITLE
Static Themes (with a manifest.json) should be listed under the Themes tab

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#4876]
### Describe the problem and steps to reproduce it:
1. Go to https://addons-dev.allizom.org/en-US/developers/addon/submit/distribution
2. Upload a static theme which uses a manifest.json
3. Complete the submission process
4. Go to https://addons.mozilla.org/en-US/developers/addons

### What happened?
The static theme is listed under 'My Add-ons'

### What did you expect to happen?
The static theme is listed under 'My Themes'

**Comment by eviljeff** [comment]
There isn't any support on AMO for webext based themes right now - work is going to start in Q2

**Comment by AlexandraMoga** [comment]
Verifed as fixed on AMO-dev with FF57 Win10
Themes submitted with a manifest.jason or via the static themes wizard are now displayed under 'My Themes" tab in Dev Hub - Manage my submissions

Postfix screenshots:
![image](https://user-images.githubusercontent.com/31961530/33546873-e33d92ae-d8ea-11e7-90d4-d40a5768819c.png)
![image](https://user-images.githubusercontent.com/31961530/33546919-077d94c0-d8eb-11e7-8aa6-37f45955b274.png)
