### ISSUE TITLE
[Review Tools] Developers are able to re-nominate rejected addon versions

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#4877]
I have noticed some cases where the addon developers have been able to re-nominate a rejected version for review.

AFAIK, only admins were able to re-nominate a rejected version. Is this intentional or a bug?

Example:
`https://addons.mozilla.org/en-US/editors/review/%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF-%D0%BA-kino-live2`

**Comment by eviljeff** [comment]
It was an intentional change (to make another feature work).  Admin flag it and someone can disable the add-on for being a nuisance.
