### ISSUE TITLE
Incompatible add-ons with "Works with" filter listed through search results

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4880]
From https://bugzilla.mozilla.org/show_bug.cgi?id=904487.

Steps to reproduce:
1. Make a search on AMO-stage i.e. "3++" - https://addons.allizom.org/en-US/firefox/search/?q=3%2B%2B&appver=51.0&platform=windows

Expected results:
All displayed add-ons should be available for the version of the Firefox on which the "Works with" filter is applied.

Actual results:
Add-ons that are not available for the selected version of Firefox are also displayed.

Notes/Issues:
Verified on FF51(Win 7). Issue is reproducing on AMO-dev, stage and prod.
Screenshot:
![2017-03-08_1513](https://cloud.githubusercontent.com/assets/15685960/23705528/ed5c67d6-0412-11e7-8315-99cbc943a35d.png)

**Comment by diox** [comment]
Will not be fixed before we move to new addons-frontend for desktop.
