### ISSUE TITLE
"Permissions" link is not displayed in AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4885]
Steps to reproduce:
1. Submit a WebExtension with permissions in AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/addon/permissionsman2/
2. Observe the "Permissions" link

Expected results:
Link is displayed. Permissions are listed in a popup.

Actual results:
Link is not displayed.

Notes/Issues:
- issue is ONLY reproducing on -dev
- the browser is displaying the permissions
- permission flag from Admin Tools is enabled

Verified in AMO-dev FF54(Win 7).
screenshot: 
![dev](https://cloud.githubusercontent.com/assets/15685960/23710542/c8682cae-0425-11e7-9581-f1f5410086ed.png)

**Comment by eviljeff** [comment]
Hmm... it's there now.  Can you replicate still?

**Comment by ValentinaPC** [comment]
Verified in AMO-dev FF52(Win 7) and seems like the link is there for old or new submissions.
Postfix screenshot:
![permlink](https://cloud.githubusercontent.com/assets/15685960/23786553/62996396-0576-11e7-8b74-b5dedfb89946.png)
