### ISSUE TITLE
"Save changes" is not working in Manage Version page from Dev Hub

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4889]
Steps to reproduce:
1. Submit an add-on in AMO-dev
2. Go to Manage Version page for that add-on i.e. https://addons-dev.allizom.org/en-US/developers/addon/test-nofileremove/versions/1531645
3. Add "Notes for Reviewers" or just click "Save changes" button

Expected results:
Changes are saved.

Actual results:
The message "u'files-0-id'" appears instead of versions files and notes are not saved.

Notes/Issues:
Verified on FF52(Win 7). Issue is ONLY reproducing on AMO-dev
Video for this issue: 
![savechanges](https://cloud.githubusercontent.com/assets/15685960/23760556/c61c975e-04f8-11e7-87b3-f410313c48c5.gif)

 May be regression from #4066

**Comment by eviljeff** [comment]
@diox #4066 would be my suspicion too, given the message.

**Comment by diox** [comment]
Weird. I can't reproduce locally with versions in various states (one file, multiple files, public or awaiting review...) but I can on the linked one on dev...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7).
Manage version page can be edited and changes are saved for listed and unlisted add-ons.
Postfix video:
![savechanges](https://cloud.githubusercontent.com/assets/15685960/23796532/1b0ad11c-05a4-11e7-9606-c1d3e9bfaad8.gif)
