### ISSUE TITLE
Activity email sending duplicate emails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4895]
I got an activity email about a developer reply to a review twice.
Happy to provide headers/more info in a private conversation if needed.

**Comment by wagnerand** [comment]
https://addons.mozilla.org/en-US/editors/review/unpaywall

**Comment by eviljeff** [comment]
The reply is there twice... and (as the review email was sent 5 days ago, so wouldn't have gotten a token) it must have been sent via devhub. Maybe the dev sent it twice?  (or had a browser glitch?) Is this the only example?

**Comment by wagnerand** [comment]
So far, it is the only example. Closing for now, then. Thanks.
