### ISSUE TITLE
[about:addons] In search results page the "Undo" link from "More" details page does not work as expected 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4897]
Steps to reproduce:
1. Load about:addons page
2. Search for an add-on i.e. TV-FOX
3. Install that add-on
4. Click "More"
5. From "More" details page click "Undo"

Expected results:
Add-on is no longer present through search results or second "undo" works.

Actual results:
Another "Undo" is present in search results page and doesn't do anything at click.

Notes/Issues:
- must be a `requires restart` add-on
- same actions made from "Extensions" tab work as expected
- refreshing the page, removes the add-on from search results page

Verified on FF52(Win 7). Issue is reproducing all around AMO-servers.
Video for this issue:
![undo](https://cloud.githubusercontent.com/assets/15685960/23791394/6fb72c2e-058b-11e7-9778-79d3cc441d0e.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC this page is actually browser code not addons-server so the bug report would be best filed in bugzilla instead.
