### ISSUE TITLE
Activity email: Clicking the 'Reply' button several times quickly send the message multiple times.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4900]
### Describe the problem and steps to reproduce it:

STR:
1. Go to an add-on version page on the devhub.
2. Open the review history panel.
3. Type something in the textbox.
4. Quickly click 'Reply' several times.

### What happened?

The message will be added several times.

### What did you expect to happen?

The message is only added once.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF55.0a1 (Wind 7 64-bit) on -dev server.
Clicking several times on the “Reply” button will leave only one reply.
Please see the video:
![onereply](https://cloud.githubusercontent.com/assets/15885467/23845741/9546f386-07d2-11e7-99f5-8ac8afc54b22.gif)
