### ISSUE TITLE
"nativeMessaging" permission is not compiled correctly on AMO

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4903]
Steps to reproduce:
1. Submit a WebExtension containing "`nativeMessaging`" permission in the manifest i.e. https://addons-dev.allizom.org/en-US/firefox/addon/perm-firefox/
2. Click "Permissions" link

Expected results:
Permission description is listed with no errors.

Actual results:
"Exchange messages with programs other than **%S**" is displayed instead of "Exchange messages with programs other than **Firefox**"

Notes/Issues:
Verified on FF55(Win 7). Issue is reproducing only on AMO-dev.
Screenshot for this issue: 
![firefox_001](https://cloud.githubusercontent.com/assets/15685960/23797752/044f041a-05aa-11e7-851a-bdbdf13cce3a.png)

https://github.com/mozilla/addons-server/issues/4861

**Comment by eviljeff** [comment]
Fixed now - the script for updating the permissions had some issues

**Comment by ValentinaPC** [comment]
The "nativeMessaging" permission is listed as expected in AMO-dev FF52(Win 7).
Postfix screenshot:  
![firefox](https://cloud.githubusercontent.com/assets/15685960/24144670/c98aa04c-0e36-11e7-9dc4-2afe6b3dcda0.png)
