### ISSUE TITLE
Activity email has odd wording

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4909]
The email sent due to a developer reply to a review has this footer: `If you want to respond to this email please reply to this email`. Let's change that to `If you want to respond please reply to this email`.

**Comment by ValentinaPC** [comment]
This is still reproducible on AMO-dev FF52(Win 7).
Screenshot: 
![2017-03-13_1456](https://cloud.githubusercontent.com/assets/15685960/23855156/5222859a-07fd-11e7-9759-38cc21aca92f.png)

**Comment by ValentinaPC** [comment]
Verified multiple activity mail cases using Admin Tools - Fake Mail logs and observed:
1. Reply from Dev Hub - my own add-on - odd wording
2. Reply from Dev Hub - not my add-on - odd wording
3. Approve/Reject/Request (more info or super-review) - wording changed

See screenshot for case 1 and 2:
![my_add-on](https://cloud.githubusercontent.com/assets/15685960/23857841/4cddd5a8-0807-11e7-8fcf-96f5908a97f4.png)
![notmyadd-on](https://cloud.githubusercontent.com/assets/15685960/23857842/4cdfe2f8-0807-11e7-86e6-44457daa3642.png)

Reopening.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7).
Postfix screenshots:
![ok](https://cloud.githubusercontent.com/assets/15685960/23888840/a9148660-0892-11e7-85ed-2effc290f2c3.png)
