### ISSUE TITLE
Review History for add-on shows "We had a problem retrieving review notes"

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4915]
This is the same as https://github.com/mozilla/addons/issues/256. There's a workaround, but it's not a very good way to resolve this.

When I clicked on the Review History link of the latest version of Password Exporter, I got

> We had a problem retrieving review notes
> /api/v3/addons/addon/2848/versions/2056432/reviewnotes/, UNAUTHORIZED, {"detail":"Invalid Authorization header. No credentials provided."}

I can confirm that logging out and logging back in fixes the problem.

**Comment by ValentinaPC** [comment]
I have encountered a similar issue regarding "Review History"....or the same :)
This is ONLY happening on AMO-dev.
- Error message returned: "We had a problem retrieving review notes /api/v3/addons/addon/494241/versions/1531859/reviewnotes/, UNAUTHORIZED, {"detail":"Error decoding signature."}"
- Error message returned in a new-clean profile: same as @jvillalobos ' s

_Logging out and back in does **not** fix the issue._

**Comment by ValentinaPC** [comment]
Based on #5093 I'll close this also and mark it verified-fixed.

**Comment by ValentinaPC** [comment]
Synchronization and its odd results. Sry @muffinresearch :)
