### ISSUE TITLE
Host Permissions are not displayed if they are declared in "content_scripts" field

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#4916]
**Steps to reproduce:**
1. Navigate to https://addons-dev.allizom.org/en-US/firefox/addon/permissioncs/
2. Click on “Permissions” link.

**Expected results:**
“Access your data for all websites”/ "Access your data for ..." descriptions appear in AMO permissions pop-up.

**Actual results:**
Host permissions are not mentioned in AMO permission pop-up. 

**Additional notes:**
- This issue reproduces on AMO-dev using Firefox 55.0a1 (2017-03-13) under Windows 10 64-bit.
- This issues also reproduces for the following extension: https://addons-dev.allizom.org/en-US/firefox/addon/permissioncs2/
- Please see the attached screenshots for this issue:
![2017-03-13_1656_002](https://cloud.githubusercontent.com/assets/18114210/23860035/6379cfb8-080e-11e7-815e-d5875543c62d.png)
![2017-03-13_1656_001_001](https://cloud.githubusercontent.com/assets/18114210/23860037/65f8a46c-080e-11e7-9f51-0ae8fb4edf64.png)

**Comment by eviljeff** [comment]
Hmm.  Didn't even know these were classed as 'permissions' by Firefox.  
@jvillalobos can you expand here because `content_scripts` weren't mentioned in the PRD or any of the issues.

**Comment by jvillalobos** [comment]
[The documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions) mentions three types of permissions: host, API, and `activeTab`. Are we only displaying API permissions now?

**Comment by eviljeff** [comment]
We're displaying everything under the `permissions` key in the manifest, so everything the documentation mentions.  But @vasilicamihasca is referring to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts I believe.

**Comment by jvillalobos** [comment]
Makes sense to include them, since they are an implicit permission. @andymckay, are there other manifest keys that should be handled like permissions?

**Comment by andymckay** [comment]
We don't display these in the install prompts in Firefox either. I don't think we should be displaying these unless you want to get into a general "content script" permission which would be something like "Alters the way websites look on these sites....". I don't think Chrome does this.

I would consider this seperate from the general permissions work we've done.

Also pinging @aswan to confirm that.

**Comment by aswan** [comment]
not confirmed :-)
This code changed more recently than what's newest on searchfox but see:
http://searchfox.org/mozilla-central/rev/7419b368156a6efa24777b21b0e5706be89a9c2f/toolkit/components/extensions/Extension.jsm#384-388

**Comment by andymckay** [comment]
Well ignore what I just said :) Thanks for the confirmation!
