### ISSUE TITLE
Contradictory compatibility messages for Android Add-on in Version History page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4917]
Steps to reproduce:
1. Submit an add-on compatible with both Firefox and Firefox for Android i.e.: https://addons-dev.allizom.org/en-US/developers/addon/youtube-test-w/versions/1531691
2. Go to version history page for that add-on i.e https://addons-dev.allizom.org/en-US/android/addon/youtube-test-w/versions/ (under Firefox for Android)
3. Observe version compatibility range

Expected results:
Add-on is compatible with Firefox for Android versions mentioned in the install.rdf file.

Actual results:
Add-on seems to be incompatible with the versions mentioned in the install.rdf file.

Notes/Issues:
- on device the add-on from step 1 can be installed without any issues using FF52;
- no "Download Now" button available in add-on details page; 
- in search results pages, different results are displayed at hover over the same add-on for Relevance and Newest Sort menu options;
- Firefox listing pages for this add-on look ok;

Verified on AMO-dev FF52(Win 7, Android 6.0.1).
Screenshots for this issue:
![1-ffa](https://cloud.githubusercontent.com/assets/15685960/23860070/76e125f6-080e-11e7-80fd-707050d7ad1b.png)
![search-results](https://cloud.githubusercontent.com/assets/15685960/23860121/ab3f94e0-080e-11e7-8fc4-8eb60a943097.png)

**Comment by muffinresearch** [comment]
Will be superceded by https://github.com/mozilla/addons-frontend/issues/2770 - this will be linked there so this issue can be revalidated if needed. There's no action to take on this repo though so marking as wontfix.
