### ISSUE TITLE
Validation results can be seen by anyone if you know the URL

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#4922]
### Describe the problem and steps to reproduce it:

- Sign an add-on with [jpm](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign) or [web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Signing_your_WebExtension_for_distribution) and use `--verbose` to see the API responses
- Open the `validation_url` you get from the upload response in a browser
- When prompted, sign in as *any* user

### What happened?

Any user can view the URL. For example: https://addons.mozilla.org/en-US/developers/upload/0049031fb64f462a9acd7beb6797216c

### What did you expect to happen?

I think this URL should only be visible by the user who uploaded the add-on, right?

**Comment by diox** [comment]
I don't know the reason but it's been that way forever. Worth noting that it's not really a problem if the developer doesn't share the URL, since the identifier is a randomly generated uuid, so it's impossible to guess.

**Comment by kumar303** [comment]
Has it always been that way? It seems odd that it requires a login -- that made me wonder if something regressed. Well, anyway, feel free to close the issue if it's a wontfix. I guess at the very least we could lift the login requirement.

**Comment by diox** [comment]
It has always been that way, did some digging and even found commits you made in that code from 2011 :)

That being said, I'm not sure it's intentional, and it could be fixed - we just need to check that the `user` on the `FileUpload` instance matches `request.user` (if both are set and not anonymous). Maybe re-using acl checking code so that reviewers can also access those results if needed.

**Comment by rctgamer3** [comment]
>I think this URL should only be visible by the user who uploaded the add-on, right?

And reviewers/admins.

**Comment by jvillalobos** [comment]
The URL was intended to be secret but shareable.
