### ISSUE TITLE
Update content of "What's New" banner

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4926]
Steps to reproduce:
1. Load Dev Hub homepage while being signed in - https://addons-dev.allizom.org/en-US/developers/
2. Observe "What's New" banner

Expected results:
Info are up to date.

Actual results:
"Happy New Year!" is a bit...obsolete.

Notes/Issues:
Verified on FF52(Win 7). Reproducing on -dev, stage and prod.
Screenshot: 
![2017-03-14_1523](https://cloud.githubusercontent.com/assets/15685960/23902904/60dca54c-08cb-11e7-9368-5c6444710bac.png)

**Comment by EnTeQuAk** [comment]
cc @atsay on this for potential new content.

**Comment by atsay** [comment]
Thanks for pointing this out! Please change to: 

Migrating your legacy add-on to WebExtensions? Get more personalized help during Office Hours, or email webextensions-support@mozilla.org.

See Schedule (https://atsay.github.io/WebExtensions_office_hours/)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7).
Postfix screenshot: 
![2017-03-28_1245](https://cloud.githubusercontent.com/assets/15685960/24399305/fe9beca4-13b4-11e7-9d43-8dd08d896a45.png)

**Comment by atsay** [comment]
Awesome, thanks!
