### ISSUE TITLE
502 bad gateway returned on -dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4929]
Steps to reproduce:
1. Open AMO-dev

Expected results:
Amo-dev is working as expected

Actual results:
502 bad gateway message displayed

NOTES:
Not reproducible on Stage

**Comment by diox** [comment]
Yes, dev is currently down because of a migration issue.

**Comment by EnTeQuAk** [comment]
This should be resolved now.

**Comment by vcarciu** [comment]
Verified as fixed
