### ISSUE TITLE
Writing logs to console

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#4930]
In order to support moving the app logs to logging 2.0 [1] platform, please consider having addons-server log to console directly. Logging to console directly is one of the required logging behaviors by logging 2.0 and is generally considered as good practice for containerized app [2].

I think during the transition from current logging platform to 2.0, the app needs to log to both the console and syslog. Once we complete the transition, I can submit another issue to stop writing logs to syslog.

[1] https://mana.mozilla.org/wiki/display/SVCOPS/Logging+2.0
[2] https://12factor.net/logs

**Comment by diox** [comment]
will be done together with https://github.com/mozilla/addons-server/issues/4931
