### ISSUE TITLE
Logging with mozLog format

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#4931]
This request is for addons-server to log in mozLog format [1] in order to hook it up with our logging 2.0 platform [2].

For example purpose, there are some python/django modules that implement logging in mozLog format, such as [3] and [4].

[1] https://wiki.mozilla.org/Firefox/Services/Logging
[2] https://mana.mozilla.org/wiki/display/SVCOPS/Logging+2.0
[3] https://github.com/mozilla-services/python-dockerflow
[4] https://github.com/mozilla/mozilla-cloud-services-logger

**Comment by diox** [comment]
To clarify, can you confirm that:
- We should add a new console logger using the new mozLog JSON format
- We should also keep using the syslog handler in parallel with current formatting for the moment, for backwards-compatibility

**Comment by bqbn** [comment]
Yes, that'd be great if we can do that.

**Comment by bqbn** [comment]
Can I get an estimated timeline for this, if possible?

Logging 2.0 is supposedly a lot better than our current logging platform. For example, we no longer share the elasticsearch and kibana cluster with other non-amo services and there is a dedicated grep host in each environment that developers will have access to as well.

**Comment by diox** [comment]
It should be ready for next week's tag.

**Comment by diox** [comment]
This is blocked by https://github.com/mozilla-services/python-dockerflow/pull/9
