### ISSUE TITLE
Switch to SHA2 for addon signing

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/addons-server#4933]
### Describe the problem and steps to reproduce it:
I see that addons signing uses SHA1 and MD5. Now they both have collision attacks. Are there any plans to switch to SHA2 or something else? Should I report a bug?

### What happened?
Firefox addon signing is based on 2 vulnerable hashing algorithms for singing (md5 and sha1).

### What did you expect to happen?
I expected addon singing to use SHA2 or some other hashing algorithm that has no known vulnerabilities.

### Anything else we should know?
Initially reported here https://discourse.mozilla-community.org/t/are-there-any-plans-to-switch-to-sha2-for-addon-signing/14200

**Comment by andymckay** [comment]
We'll use https://bugzilla.mozilla.org/show_bug.cgi?id=1342582 as the main tracker for this, there will be a need to change add-ons server though so we'll need some github bugs.

**Comment by EnTeQuAk** [comment]
Assigning to @muffinresearch for further planning since the bugzilla bug is also assigned.

**Comment by EnTeQuAk** [comment]
Short update on this: `signing-server` does generate SHA2 hashes now and the resulting add-ons are in testing. So I'd say this is WIP, afaik landing in Firefox 59 with the hash generating code a bit after that or so.

**Comment by EnTeQuAk** [comment]
More updates on this: I'm planning on enabling this for next week's milestone.

cc @krupa @jvehent

**Comment by EnTeQuAk** [comment]
https://github.com/mozilla/addons-server/issues/7668 will land next Thursday. I opened another issue about this since this one is explicitly about a broader picture. I wonder if we can close it too though given that stuff like that is being tracked in bugzilla?

**Comment by EnTeQuAk** [comment]
I'm going to close this issue here since it's tracked in bugzilla and the current work that was needed on AMO was fixed via #7668
