### ISSUE TITLE
Add-ons cannot be installed from Disco Pane by clicking on the switch button

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4940]
Prerequisites:
- `extensions.webservice.discoverURL` pref is set to point stage/dev

Steps to reproduce:
1. Load about:addons page
2. Try to install an add-on by clicking on the switch button

Expected results:
Add-on is installed.

Actual results:
Add-on cannot be installed.

Notes/Issues:
- add-on can be installed from AMO public pages (i.e https://addons.allizom.org/en-US/firefox/addon/video-downloadhelper/)
- add-ons can be installed from search results pages in about:addons

Verified on FF55(Win 7). Issue is reproducing in AMO-stage and dev.
Video for this issue:
![installdiscopane](https://cloud.githubusercontent.com/assets/15685960/23954086/0b0122a4-099f-11e7-834c-158fe50b41e7.gif)

**Comment by tofumatt** [comment]
This issue should be in front-end, not server. Can you move it? :-)

**Comment by ValentinaPC** [comment]
Ufff ....forgot about this :(
See - https://github.com/mozilla/addons-frontend/issues/2074
