### ISSUE TITLE
Android add-on seen in Featured section for Firefox Add-ons

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4941]
Steps to reproduce:
1.Open AMO-Stage , and click on Clean Links (https://addons.allizom.org/en-US/android/addon/clean-links/) add-on from Featured section

Expected results:
We should have only Firefox compatible add-ons under Featured section

Actual results:
After opening the add-on , we can see that it is only Firefox for Android compatible

Please see video for this issue : 
![androidaddon](https://cloud.githubusercontent.com/assets/1583842/23954835/f7c9c5d6-09a0-11e7-9678-be88c9ea4bed.gif)

**Comment by diox** [comment]
It sounds like that's an editorial problem, not an addons-server bug: someone has added this add-on to the featured section on Android, and we don't prevent/filter that.

With great powers come great responsibilities.
