### ISSUE TITLE
Inconsistencies between number of add-ons in categories and number displayed in "See all" section for a category

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#4942]
Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/extensions/games-entertainment/
2.Observe the number displayed in "See all .." link at the bottom of selected category (835 in this case)
3.Press the "See all .." link

Expected results:
Number of add-ons from category listing pages should be the same with the one from "See all.." link 

Actual results:
Numbers are different

NOTES:
The number from Category listing pages is the correct one

Please see video for this bug : 
![seealladd](https://cloud.githubusercontent.com/assets/1583842/23955552/e6d4925e-09a2-11e7-9463-c93553f740ed.gif)

**Comment by diox** [comment]
Sounds like the count from the first page is not filtering something correctly.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
