### ISSUE TITLE
"n Daily Users" may need singular form

### ISSUE THREAD

**Issue by TonnesM** [mozilla/addons-server#4947]
In some and probably rare occasions, there may be 1 active user for some add-on, such as when viewing [1].

The associated string however only exists for plural forms. [2]

It may be nice to add a singular form for this string for linguistic reasons.

[1] https://addons.allizom.org/en-US/firefox/themes/sports?sort=created
[2] https://pontoon.mozilla.org/en-GB/amo/LC_MESSAGES/django.po/?search=%7B0%7D+Daily+User&string=154492

**Comment by eviljeff** [comment]
mentor @EnTeQuAk

**Comment by wagnerand** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by apoorvaeternity** [comment]
@EnTeQuAk Please tell me how to fix this.Do I just have to check in the template that if the number of daily active users is less than 2 then the string should be **Daily User** otherwise **Daily Users** ?

**Comment by ValentinaPC** [comment]
Verified this on AMo-dev FF54(Win 7) for:
- themes 
![2017-07-31_1450](https://user-images.githubusercontent.com/15685960/28776716-78a0fe74-7600-11e7-89fd-30f9d2d00c89.png)
- add-ons
![2017-07-31_1458](https://user-images.githubusercontent.com/15685960/28776766-c934cc1c-7600-11e7-8aaf-122847cfe16d.png)
- statistics
![2017-07-31_1458_001](https://user-images.githubusercontent.com/15685960/28776773-d16a0884-7600-11e7-8ec0-8ae109cb527c.png)

@EnTeQuAk : Do we also want to change the term in Statistics page?
Thanks!
