### ISSUE TITLE
"Recently Updated" Collections sort-option does not work in search results pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4951]
Steps to reproduce:
1. Load Collections page in AMO-stage https://addons.allizom.org/en-US/firefox/collections/
2. Make a blank search
3. Sort results by "Recently Updated"

Expected results:
Search results are sort accordingly.

Actual results:
Older updates are listed before recent updates.

Notes/Issues:
- sorting works as expected in collections homepage;

Verified on FF52(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue:
![recently_updated](https://cloud.githubusercontent.com/assets/15685960/23987594/067bf346-0a33-11e7-8f13-887710a9ce6c.png)

**Comment by diox** [comment]
It's a valid issue, but it's unlikely we'll ever get to fix it before migrating to addons-frontend.
