### ISSUE TITLE
Add label to listing pages to highlight WebExtensions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#4974]
As part of our [plans to transition users to WebExtensions](https://docs.google.com/document/d/19CB11uJbhz2txgP9AMPdvAcqjTHubQvEHU5E17LiaTs/edit), we need to highlight WebExtensions on AMO by adding a label to all WebExtensions listing pages. The label should look like the existing `Requires restart` label:

<img width="623" alt="label" src="https://cloud.githubusercontent.com/assets/62568/24060180/a36412bc-0b17-11e7-968f-67ad01a4eca4.png">

The label should say `Future-compatible` and be green. /cc @designakt @atsay for alternative suggestions.

The label should link to a SUMO page (to be set up) explaining what it means.

**Comment by diox** [comment]
I'll do this for addons-server but we may want to do it for addons-frontend mobile pages as well (I'll add a boolean indicating whether the file is a webextension or not to the API)

**Comment by yfdyh000** [comment]
Any possibility for a tag added? used as search filter. https://github.com/mozilla/addons-server/issues/4511

**Comment by jvillalobos** [comment]
Updated label to `Future-compatible`.

> Any possibility for a tag added?

That's a good idea, and it looks like we already have some code for that for "restartless". @diox, can you check if what we did for the reserved "restartless" tag can be extended for a second tag?

**Comment by muffinresearch** [comment]
@jvillalobos could another possibility be to add a "deprecated" label to non-webext? I'd worry that "Future-compatible" is a bit abstract.

**Comment by jvillalobos** [comment]
We're intentionally avoiding negative messaging on the first phase, which is why we want to highlight WebExtensions instead. I agree the label is a bit abstract, but that's the best option we have so far. Suggestions welcome :)

**Comment by diox** [comment]
Pretty sure the `restartless` (and maybe `jetpack`) tag has been broken for a while (not being updated) but the mechanism is sound, I can re-use it yeah. I'll also add something to the API.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by krupa** [comment]
Does 'future-compatible' translate easily to other locales easily?

Can we maybe highlight them by using something like https://www.dropbox.com/s/jrs2b5xmod0c7b7/Screenshot%202017-03-30%2015.58.06.png?dl=0 which is what yelp uses to indicate "hotness". That way we can highlight webextensions without getting into the messy web of compatibility.

**Comment by jvillalobos** [comment]
I don't think an icon will help make the flag more understandable, but it gives me the idea that there should be a hover text expanding on what it means.

**Comment by muffinresearch** [comment]
Ping @devaneymoz + @pwalm for input on this, since this labelling is a combination of UX + editorial.

**Comment by devaneymoz** [comment]
It's my understanding this label will only be a temporary thing displayed during the ramp up to 57, then it goes away. And it's further intended to speak to the leading edge tech audience, so I think that gives us some leeway to be more esoteric with language. 

While I agree "future-compatible" is a bit abstract and would make for a good Death Cab for Cutie song title, I think it's primarily accurate and illustrative. Other considerations I might toss into the ring:

Full Compatibility
Future Tech
Next Gen Add-on
Next Gen Compatibility

... or maybe just go with **WebExtension** despite our being wired to not consider it a user-facing term. If this label is only going to be temporary anyway, what's the issue? Also, might we introduce more confusion by labeling a WebExtension something other than WebExtension when the purpose is to alert the tech forward crowd that this is a WebExtension?

**Comment by andymckay** [comment]
Could you say "Firefox 57+" compatible? I'd like to avoid using the term WebExtension if it all possible. We could force all non-WebExtensions to not have compatibility beyond Firefox 56, inside AMO. And then just do a lookup to determine which version it works on.

**Comment by devaneymoz** [comment]
@andymckay that's not a bad idea.

**Comment by atsay** [comment]
It might read better as "Compatible with Firefox 57+"

**Comment by diox** [comment]
I apologize for the bike-shedding, but I am not a big fan of any of those proposals.
- "Compatible with Firefox 57+"  exposes Firefox version numbers, which are pretty opaque/meaningless/confusing for end-users. I suspect most end-users don't know which version they are running.
- "Webextension" has similar issues. What is a "WebExtension" for a end-user ?
- "Future-compatible" is vague (though it kinda works in its favor)

I think that ultimately the issue here is that we don't market WebExtensions to end-users (and we don't really warn them about the impending changes in 57 - we warn developers) ; The "requires restart" label has meaning for them, but I suspect it will be hard to find a similarly meaningful wording for WebExtensions as long as we don't educate users about what they are and provide for them.

**Comment by davidhedlund** [comment]
@diox What about adding dev.addons.mozilla.org?

Example
* https://addons.mozilla.org/en-US/firefox/addon/bulk-media-downloader/
* https://dev.addons.mozilla.org/en-US/firefox/addon/bulk-media-downloader/ -- To show additional information on the page for developers.

**Comment by diox** [comment]
This issue is not about showing additional information to developers, it's about adding it to end-users. I'll add the information to the API and developers will be free to use an extension or whatever they like to display it, but this is not what we are worried about here.

**Comment by jvillalobos** [comment]
I think "Compatible with Firefox 57+" has become the top choice. The "future" options sound like we're promising too much, and we really don't want to use "WebExtensions".

For the tag I suggest we use "firefox57".

For the hover text, I'm suggesting "This add-on is built on new technology that is compatible with future versions of Firefox."

**Comment by atsay** [comment]
I wouldn't use "future" here either. I suggest this: "This add-on is built with new technology that is compatible with Firefox 57 and beyond."

**Comment by erosman** [comment]
What about "**Multi-Process**" tag to indicate addon is Multi Process Compatible?!

**Comment by atsay** [comment]
Here are the [URLs](https://docs.google.com/spreadsheets/d/16cPPQDPILEK3RujBhbJlbI7hyNjKr_vykWAC14yxlY0/edit#gid=0) you can link the label to. The articles are not ready yet, but when they are they will appear on these pages.

**Comment by diox** [comment]
@atsay can you provide a single link that will redirect according to the locale ?

**Comment by ValentinaPC** [comment]
@diox: should we display this label in search results pages also, as we do for the "require restart" label? Thanks!
Here is a screenshot:
![labels](https://cloud.githubusercontent.com/assets/15685960/24955025/6bb4db9e-1f8a-11e7-9799-3088b4033dd9.png)

**Comment by diox** [comment]
@jvillalobos see @ValentinaPC question, should we?

**Comment by atsay** [comment]
Jorge is out for the week so I'll decide for him. Yes, let's put them in search results too!

**Comment by atsay** [comment]
Here's the response I got from SUMO re: a redirecting link. Apparently we can't do that at the moment: "Our new platform doesn't support redirects to different locales yet, but we're working with our vendor to implement that in the future. What we're doing in the interim is creating separate links for each locale, but we plan to change that in the future."

**Comment by grahamperrin** [comment]
Re: choices of wording, I'm fairly certain that in at least one other WebExtensions-related issue, the word _legacy_ was proposed. For what it's worth I don't view that word as negative in a context such as this.

**Comment by diox** [comment]
> Here are the URLs you can link the label to. The articles are not ready yet, but when they are they will appear on these pages.

@atsay: The links are still not working. I'd prefer not merging broken links that I and QA can't test, and we're tagging today for this Thursday's push. Should I wait and include them for next week ?

**Comment by atsay** [comment]
@diox Are they broken, or just not redirecting (they are loading for me)? SUMO says, "Now that we have the article up, we have to submit this list to our vendor so they can set up the redirects. It will take them 1-2 days." I got this message yesterday, so I guess the redirects should work by tomorrow?

**Comment by diox** [comment]
They are all redirecting to the Mozilla Support (English) home page for me at the moment

**Comment by diox** [comment]
@atsay missed the tag anyway... so the links will be for next week. Can we in the meantime make the redirect URLs more consistent with the locales on AMO ? I'd like to make the following changes:

* Change https://support.mozilla.org/kb/webextensions-en to https://support.mozilla.org/kb/webextensions-en-us
* Change https://support.mozilla.org/kb/webextensions-pt to https://support.mozilla.org/kb/webextensions-pt-pt
* Change https://support.mozilla.org/kb/webextensions-jp to https://support.mozilla.org/kb/webextensions-ja
* Change https://support.mozilla.org/kb/webextensions-zh to https://support.mozilla.org/kb/webextensions-zh-cn

**Comment by atsay** [comment]
Joni said she changed the links as requested.

**Comment by ValentinaPC** [comment]
> Change https://support.mozilla.org/kb/webextensions-en to https://support.mozilla.org/kb/webextensions-en-us
> Change https://support.mozilla.org/kb/webextensions-pt to https://support.mozilla.org/kb/webextensions-pt-pt
> Change https://support.mozilla.org/kb/webextensions-jp to https://support.mozilla.org/kb/webextensions-ja
> Change https://support.mozilla.org/kb/webextensions-zh to https://support.mozilla.org/kb/webextensions-zh-cn

These links don't work neither **if clicked from the comment** or from webext details page using "Compatible with Firefox 57+" link. I think I have to wait until next week, @diox?
I'll reopen this until the redirect links will be fixed to better keep track of changes.

Verified the other things on AMO-dev using FF52(Win 7).
- label is also a link
- hovering over the label some info are displayed
- the compatibility label is also listed in the search results pages

Please see screenshot:
![2017-04-20_1824](https://cloud.githubusercontent.com/assets/15685960/25238639/a08c2d14-25f6-11e7-974b-88cbe9ddf34f.png)

**Comment by diox** [comment]
I don't control those links so I simply don't know. @atsay can you look into that?

**Comment by ValentinaPC** [comment]
When I started to test this, I saw the tag "firefox57" in add-ons details page.
Searching by this tag returned all add-ons compatible with 57+, and I consider it very helpful, but that was yesterday, today, no tag. Do you know something about this, @diox ?

**Comment by diox** [comment]
I ran the command to add the tag to existing (public+listed) webextensions on dev and stage but somehow they were not indexed after that, so they have the tag but don't show up when searching for it (https://addons.allizom.org/en-US/firefox/tag/firefox57 and https://addons-dev.allizom.org/en-US/firefox/tag/firefox57) yet. I'm currently reindexing both dev and stage to see if that fixes the issue.

**Comment by diox** [comment]
Reindexing somehow made things worse, investigating.

**Comment by diox** [comment]
Ah, just had to wait. Now everything should be working, @ValentinaPC ; you can see the tag on webextensions detail pages and you can search for it.

**Comment by ValentinaPC** [comment]
Verified the tag part on AMO-dev FF53(Win 7) and seems to work as expected.
Tag is automatically added for new submissions, listed for already submitted webextensions and  search by tag is returning all compatible webext.
![2017-04-21_1653](https://cloud.githubusercontent.com/assets/15685960/25280581/242fa49a-26b3-11e7-9814-a2fffad5fc01.png)
![2017-04-21_1653_001](https://cloud.githubusercontent.com/assets/15685960/25280582/243190b6-26b3-11e7-83db-5d171ad58ea5.png)

Leaving this open because of the redirection links.

**Comment by atsay** [comment]
I received this from the SUMO team:
"To be safe, please use this link: https://support.mozilla.org/kb/firefox-add-technology-modernizing
It will automatically redirect to the different locales. Just be aware that we might have to change the link when we move back to the new platform, but the above link will work in the interim. We'll keep you posted of that though."

Since we have until next week to push out the links, maybe we should wait a few days to see if they move back to the new platform? Perhaps if we don't hear back by Tues we should just go with this one.

**Comment by diox** [comment]
Crap, I missed that. So what's the status, which link should we be using come Thursday (date of our push)? I can change it and cherry-pick into our tag, I just don't want to go back and forth.

**Comment by atsay** [comment]
Please use this link: https://support.mozilla.org/kb/firefox-add-technology-modernizing

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Postfix video:
![link57](https://cloud.githubusercontent.com/assets/15685960/25432416/038ea906-2a8d-11e7-9321-ace9cdc107a1.gif)

**Comment by ValentinaPC** [comment]
**@diox** : the part about the `firefox57` tag was not pushed to prod?
Thanks!

**Comment by diox** [comment]
It was: https://addons.mozilla.org/en-US/firefox/search/?tag=firefox57

**Comment by erosman** [comment]
A couple of suggestion:
- Collections could also benefit from the tag
- Wouldn't a shorter tag be more aesthetically pleasing? for example **Firefox 57+ ✔️**
