### ISSUE TITLE
Define multiprocess compatibility on add-on pages on AMO

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#4975]
### Describe the problem and steps to reproduce it:
The add-on pages on AMO (eg [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)) do not specify if they are compatible with Multiprocess (didn't find "Electrolysis", "e10s" either).

_Add-on Compatibility Reporter_ (ACR) are the recommended way to find out multiprocess compatibility, but that's only possible for Firefox as ACR do not run on:
* Firefox for Android
* Thunderbird
*  SeaMonkey

Thus this must be stated on AMO as a work around.

### What did you expect to happen?
I expected that the multiprocess compatibility should be stated on the the page because it is defined in the [API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail)
> GET /api/v3/addons/addon/(int:id|string:slug|string:guid)/feature_compatibility/

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by diox** [comment]
e10s compatibility will not matter very soon as it will be force-enabled on everyone. We do want to label web extensions instead though, to indicate that they will be future-compatible. https://github.com/mozilla/addons-server/issues/4974

**Comment by wagnerand** [comment]
Plans have changed. It won't be force-enabled before 57. Reopening, so we can discuss whether we need to do this or not...

**Comment by davidhedlund** [comment]
@wagnerand 
> It won't be force-enabled before 57.

Can you please give me a official reference for that?

**Comment by wagnerand** [comment]
https://wiki.mozilla.org/Electrolysis#Add-ons_Schedule

**Comment by wagnerand** [comment]
Also, the table is slightly outdated. According to @shell15 we won't enable e10s for add-ons without MPC=true even if they don't use shims.

**Comment by davidhedlund** [comment]
@wagnerand Thank you very much.

**Comment by davidhedlund** [comment]
@wagnerand Can you please ask him to add that to https://wiki.mozilla.org/Electrolysis#Add-ons_Schedule ?

**Comment by wagnerand** [comment]
Yes, I already pinged her :)

**Comment by davidhedlund** [comment]
@wagnerand Thanks again.

**Comment by davidhedlund** [comment]
@wagnerand Based on https://wiki.mozilla.org/Firefox/AddOns/Status/current#Schedule would you say that Firefox 57 or 58 will implement Electrolysis absolutely fully?

**Comment by davidhedlund** [comment]
https://github.com/mozilla/addon-compatibility-reporter/issues/77

**Comment by davidhedlund** [comment]
@wagnerand @diox Added to top of this issue:

> _Add-on Compatibility Reporter_ (ACR) are the recommended way to find out multiprocess compatibility, but that's only possible for Firefox as ACR do not run on:
> * Firefox for Android
> * Thunderbird
> *  SeaMonkey
> 
> Thus this must be stated on AMO as a work around.

**Comment by wagnerand** [comment]
@davidhedlund I think we already clarified that some products might not even be using e10s. Why list them here again?

**Comment by davidhedlund** [comment]
@wagnerand This is still valid for Firefox for Android, right?

**Comment by wagnerand** [comment]
I don't know.

Also, this is kind of blocked on #3947

**Comment by davidhedlund** [comment]
@wagnerand Interesting.

**Comment by diox** [comment]
Worth noting that Firefox also has its own (small) blocklist of add-ons it will not enable multiprocess for : https://dxr.mozilla.org/mozilla-central/source/browser/extensions/e10srollout/bootstrap.js#97

**Comment by Gitoffthelawn** [comment]
+1 for a solution

**Comment by diox** [comment]
We're now very close to Firefox 57 and considering removing e10s information at all (see discussion in #3947) so I don't think it's worth pursuing.

**Comment by Gitoffthelawn** [comment]
I have to laugh a just a little... wait long enough without solving an issue, and the issue becomes irrelevant...  ;)
