### ISSUE TITLE
Download links broken on mozilla.org/en-US/firefox/channel/android/

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#4976]
### Describe the problem and steps to reproduce it:
I'm using Firefox 52 on Android 4.4.2.

I cannot download any of the Firefox-variants from Android at https://www.mozilla.org/en-US/firefox/channel/android/. For example, Firefox Beta download link
> market://details?id=org.mozilla.firefox_beta&referrer=utm_source%3Dmozilla%26utm_medium%3DReferral%26utm_campaign%3Dmozilla-org

### What happened?
I get the message
> "No such app found."

### What did you expect to happen?
I should obviously be able to download Firefox.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by eviljeff** [comment]
this isn't bug on addons.mozilla.org - can you re-file on https://bugzilla.mozilla.org/enter_bug.cgi?product=www.mozilla.org

**Comment by davidhedlund** [comment]
@eviljeff Thanks, filed to https://bugzilla.mozilla.org/show_bug.cgi?id=1349222
