### ISSUE TITLE
Deleting a user should delete their reviews

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4977]
STR:
- Post a rating/user review on an add-on
- Delete your user profile

Expected results:
- The rating/review should have been deleted

Actual results:
- The rating/review is kept. The name displayed is now "Anonymous user xxx" but the content is still there. It leads people to believe we're allowing anonymous reviews, which is not the case, AFAIK.

/cc @jvillalobos to say if my expected results make sense. It should be easy to fix if we all agree that is a bug.

**Comment by jvillalobos** [comment]
I agree with the premise, but I think that's what happens already. All the "Anonymous user xxx" users, as I understand it, are users that haven't set a username or display name. For example, [this user](https://addons.mozilla.org/user/anonymous-6baa9b81ec4837f95084f1e091de9178/).

**Comment by diox** [comment]
Ah, will double-check then. Since we anonimize users when they are deleted I was thinking that was where the name was coming from.

**Comment by diox** [comment]
So, although reviews from `Anonymous user xxx` do seem to come from users that haven't set a username/display name, we still don't delete reviews from "deleted" users.

This is the delete view: https://github.com/mozilla/addons-server/blob/71dbbec022dc1d3073261148e7d2db2264525603/src/olympia/users/views.py#L93-L108

It calls [`.anonymize()`](https://github.com/mozilla/addons-server/blob/71dbbec022dc1d3073261148e7d2db2264525603/src/olympia/users/models.py#L318-L328), which does *not* delete any related objects.

**Comment by eviljeff** [comment]
I thought this was expected behaviour - once you leave a review it doesn't get deleted if you delete (anonymize) your account.  This is what we tell the user too https://github.com/mozilla/addons-server/blob/master/src/olympia/users/templates/users/delete.html#L40

**Comment by jvillalobos** [comment]
Yeah, anonymizing doesn't delete any content, which is the current expected behavior.

**Comment by eviljeff** [comment]
So... it's not a bug then?

**Comment by jvillalobos** [comment]
Doesn't look like it.
