### ISSUE TITLE
Addons -dev server returns 403 error message

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#4978]
### Describe the problem and steps to reproduce it:
Access https://addons-dev.allizom.org/ with a new profile.

### What happened?
A 403 error message is displayed.

### What did you expect to happen?
The page from https://addons-dev.allizom.org/ should be displayed without any issues.

### Anything else we should know?
Please see the video for this issue:
![403](https://cloud.githubusercontent.com/assets/15885467/24091331/2482f450-0d50-11e7-8ffa-aada89027825.gif)

**Comment by muffinresearch** [comment]
Looks like the new nginx config only works with a mamo cookie on -dev.

As a quick hack running `document.cookie = "mamo=off;path=/"`

**Comment by cosminbadescuSV** [comment]
I typed this command: < document.cookie = "mamo=off;path=/" >  in the browser console using a new profile and it seems it does not have any effect I still can see the 403 error message.
A profile with mamo cookie will receive the same error message.
![403-2](https://cloud.githubusercontent.com/assets/15885467/24101254/41efc704-0d80-11e7-873f-91420e582c02.gif)

**Comment by cosminbadescuSV** [comment]
Typing `document.cookie = "mamo=off;path=/"` in the web console seems to work!
The -dev server will work every time only after this command is performed in the web console.
Thanks @muffinresearch!
![403-3](https://cloud.githubusercontent.com/assets/15885467/24102111/90c802a8-0d83-11e7-89ad-cb9fc70b8778.gif)

**Comment by muffinresearch** [comment]
This should be fixed now. See https://github.com/mozilla/addons-frontend/issues/2082#issuecomment-287830583

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF55.0a1 (Wind 7 64-bit) on -dev server.
The https://addons-dev.allizom.org/ page is loaded without any issues.
Please see the video:
![403good](https://cloud.githubusercontent.com/assets/15885467/24136592/33e29fb8-0e18-11e7-8ae8-cbba63cff238.gif)
