### ISSUE TITLE
Restrict deletion of non-moderated user reviews to permission Addons:Edit

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#4981]
Deletion of non-moderated user reviews should be restricted to admins ie, anyone with the permission `Addons:Edit`.

Regular reviewers should still be allowed to delete moderated reviews.

Motivation:
Deleting non-moderated reviews does not getting logged in the moderation-log (which is probably correct), but doing so does not give admins a chance to undelete such a review.

//cc @jvillalobos

**Comment by wagnerand** [comment]
QA information:

* On an add-on reviews page, the _Delete review_ link next to each review should be visible to:
** admins always,
** the author of the review always,
** add-on reviewers **only** that review is flagged for moderation.
* If the review is flagged for moderation, clicking the "Delete review" link should **always** add a log entry to `/editors/logs`.
* The review moderation page (`/editors/queue/reviews`) should work correctly, i.e. deleting moderated reviews should work for all add-on reviewers.

**Comment by jvillalobos** [comment]
Shouldn't these deletions also go to the moderation log, anyway?

**Comment by wagnerand** [comment]
@jvillalobos we can do that, but the current design is to log **moderated** user reviews. If we change the design, we also need some updates to that log page.

Do you want all deletions to be logged, regardless of the moderation status?

**Comment by jvillalobos** [comment]
> Do you want all deletions to be logged, regardless of the moderation status?

Yes. It's still moderation, but taking a shortcut.

The only thing I see in the log pages that would need to change is that at the end of the detail page it says `Review was flagged prior to deletion.`, which suggests we were meant to support direct deletions as well.

**Comment by wagnerand** [comment]
PR updated.

**Comment by vcarciu** [comment]
Verified for all scenarios described in the bug , please see my comments below and let me know if this should be reopened: 

- Admin can always delete : OK 
![admin](https://cloud.githubusercontent.com/assets/1583842/24258573/e571321e-0ff6-11e7-9b0f-6b60891dab90.png)

-  Author of review  can delete his reviews : OK
![authorofreview](https://cloud.githubusercontent.com/assets/1583842/24258704/3c71e554-0ff7-11e7-990c-a48a23f532e3.png)

- Reviewers can only delete flagged : PARTIALLY OK
![rewonly](https://cloud.githubusercontent.com/assets/1583842/24260348/4e5c18d4-0ffc-11e7-98df-f255bbecfbcb.gif)

     **- Reviewers can also delete developers replies : Is this correct?**

- "Delete review" link should add a log entry to /editors/logs always (except if the author themselves deletes it).  - PARTIALLY OK
      **- If a Reviewer delete his own review , this will add an entry to /editors/logs - I think that this is not correct since in this case, the exception from above should take place even if the user is a reviewer : Is this correct?**

- The review moderation page (/editors/queue/reviews) should work correctly, i.e. deleting moderated reviews should work for all add-on reviewers. : OK
![deleteinqueue](https://cloud.githubusercontent.com/assets/1583842/24261365/67f20cb0-0fff-11e7-94d6-5290439ec2fe.gif)

**Comment by wagnerand** [comment]
> - Reviewers can also delete developers replies : Is this correct?

Yeah, this is correct. If a review is deleted, all replies are deleted too.

> - If a Reviewer delete his own review , this will add an entry to /editors/logs - I think that this is not correct since in this case, the exception from above should take place even if the user is a reviewer : Is this correct?

Good catch. I fixed it in #5021.

**Comment by vcarciu** [comment]
Reviewers can also delete developers replies : Is this correct?

Yeah, this is correct. If a review is deleted, all replies are deleted too.

I think that we have a misunderstanding here . So, the reviewer(not admin) can delete a developer reply for a NOT flagged review : is this correct?

**Comment by wagnerand** [comment]
> So, the reviewer(not admin) can delete a developer reply for a NOT flagged review : is this correct?

Hm, that sound wrong. Do you have an example for that on -dev?

**Comment by wagnerand** [comment]
I can't reproduce this:

![screen shot 2017-03-24 at 12 52 08](https://cloud.githubusercontent.com/assets/873258/24293176/c613196a-1090-11e7-97fa-8fdcbbcc0d2f.png)

**Comment by vcarciu** [comment]
@wagnerand 
I am not able to reproduce this scenario anymore :(

**Comment by wagnerand** [comment]
Ok, I'm closing this. If it comes up again, please file a new issue.

**Comment by vcarciu** [comment]
Verified as fixed with the scenario from #5021  : 
![deleteownreview](https://cloud.githubusercontent.com/assets/1583842/24363313/25cb4b28-1318-11e7-94b6-b20cb5cbf822.gif)
