### ISSUE TITLE
Same e-mail is generated at submission for each file inside an unlisted version

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#4985]
Steps to reproduce:
1. Submit an unlisted add-on while selecting only some platforms at submission i.e. https://addons-dev.allizom.org/en-US/developers/addon/activity-m-files/edit
2. Upload a new file for the submitted version
3. Check out the activity mails (Admin Tools-Fake Mail - https://addons-dev.allizom.org/en-US/admin/mail)

Expected results:
An e-mail that contain the platform for which the file was added is generated.

Actual results:
Same e-mail is generated every time a new file is added (for the same unlisted version), as the one received when submitting the unlisted add-on for the first time.

Notes/Issues:
Verified in FF52(Win 7). Issue is reproducing on -dev and -stage.
Screenshot for this issue: 
![mfiles](https://cloud.githubusercontent.com/assets/15685960/24137176/4b2b1a62-0e1b-11e7-8045-217bfad9c8c6.png)

#3726

**Comment by muffinresearch** [comment]
Seems bad if this is resulting in multiple emails unnecessarily.

**Comment by EnTeQuAk** [comment]
Please comment/re-open if I'm mistaken but with #9362 landed this shouldn't be an issue anymore given that you can't upload files manually after submission anymore or even submit separate platforms.
