### ISSUE TITLE
Remove user reviews translations feature

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#4990]
Speaking about the feature that does translations of user reviewers, in https://github.com/mozilla/addons-server/issues/4110#issuecomment-265272693 @jvillalobos said:
> I looked into the feature a while ago and it didn't appear to be used much. We should consider removing it altogether as part of the ratings work we're planning for next year.

We are voting for removing it if possible. It's not used much and it has bugs we don't want to maintain.

**Comment by jvillalobos** [comment]
Yeah, let's drop it.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7).
Translate feature from "Moderated reviews" queue is no longer available.
Postfix screenshot: 
![notranslation](https://cloud.githubusercontent.com/assets/15685960/24242397/4df2ab42-0fc0-11e7-825d-db46e5adb488.png)

**Comment by rctgamer3** [comment]
This feature was very useful for translating Russian/Cyrillic, and other reviews not in English to decide if they would qualify for vulgar language/spam/deletion. At the bare minimum, I woudl've expected a leftover of this feature to persist in the moderated review queue.

**Comment by spoji** [comment]
For reviewers that need this feature, note that we integrated it back inside the add-on "AMO Queue Helper 5.7.1" : https://addons.mozilla.org/en-US/firefox/addon/amo-queue-helper/
