### ISSUE TITLE
[Dev Hub] Add ratings to listings in signed-in view

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#4994]
Originally filed on addons-frontend, but should be here.

See: https://github.com/mozilla/addons-frontend/issues/1717

**Comment by eviljeff** [comment]
looking roughly like:
![screenshot](https://cloud.githubusercontent.com/assets/51007/22871335/0d7282a6-f204-11e6-8cef-96c5f512c98f.png)

**Comment by caitmuenster** [comment]
@brampitoyo, can you give us a quick summary about what happened with issue #1717 so contributors who want to dive into this issue can know where to pick up?

**Comment by brampitoyo** [comment]
Since mozilla/addons-frontend/issues/1800 has been fixed, fixing this issue consists of simply adding the star graphic above the “last updated” value on the right hand corner of the add-on listing.

Before:
![before](https://user-images.githubusercontent.com/51007/31149998-7e20f7e8-a8ee-11e7-9122-28716d1520ee.png)

After:
![after](https://user-images.githubusercontent.com/51007/31150002-80a16cd2-a8ee-11e7-874e-3d9017d27f10.png)

**Comment by wagnerand** [comment]
Mentor: @eviljeff (please do add some guidance for contributors)

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by eviljeff** [comment]
I think this is just a matter of changing the template @ https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/new-landing/components/my-addons.html#L104 to add `{{ addon.average_rating|float|stars }}`, with some css to make it look like the mockup above.

**Comment by PhillypHenning** [comment]
Hey I'm a Seneca Student I would love to take this

**Comment by eviljeff** [comment]
@PhillypHenning please do

**Comment by VishalCR7** [comment]
@eviljeff  can I take up this issue ? Looks like no one is working on it right now.

**Comment by caitmuenster** [comment]
Hey @VishalCR7, it looks like @phillyphenning isn't currently working on this so please feel free to pick it up!

**Comment by VishalCR7** [comment]
@eviljeff  can you please review the PR #7274 regarding this issue.

**Comment by ioanarusiczki** [comment]
Verified on AMO-dev FF57 (Win10)

![rated extensions](https://user-images.githubusercontent.com/33448286/34994320-c7c60750-fadb-11e7-9bcb-e362ff4289ac.png)
