### ISSUE TITLE
Let's change "My Add-ons" title from Developer Hub homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5003]
Steps to reproduce:
1. Load Deb Hub landing page while being signed in https://addons.allizom.org/en-US/developers/
2. Observe "My Add-ons" section

Expected results:
The section containing themes, add-ons, webextensions, etc. should be named "My Submissions" - for consistency.

Actual results:
The section has the "My Add-ons" title.

Notes/Issues:
- there is also a "My Add-ons" link in the header that redirects to "My Add-ons" tab from "My Submissions" page.
Verified on AMO-dev FF52(Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue:
![2017-03-22_1733](https://cloud.githubusercontent.com/assets/15685960/24206189/26ea8794-0f26-11e7-8439-2d5fc776d24d.png)

**Comment by wagnerand** [comment]
We use _add-ons_ as the umbrella term for extensions (XUL/SDK/webextensions), themes, language packs, dictionaries...

**Comment by ValentinaPC** [comment]
> We use add-ons as the umbrella term for extensions (XUL/SDK/webextensions), themes, language packs, dictionaries...

I know... but we have separate tabs regarding add-ons and themes in My submissions and also the other "My Add-ons" (link from Dev Hub header) is redirecting to "My Add-ons" tab....that is why I made the suggestion.

**Comment by jvillalobos** [comment]
We'll change other pages in the developer hub to match what is in this homepage, when we get to them. I think what's in the new homepage makes more sense.
