### ISSUE TITLE
Remove automatic validation filter from Reviewer Tools->Logs->Signed Beta Files Log

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5011]
Steps to reproduce:
1. Load page https://addons.allizom.org/en-US/editors/beta_signed_log?filter=131 while being signed in with an admin account
2. Select "Failed automatic validation" from the drop-down
3. Click "Filter" button

Expected results:
A list of failed automatic validation add-ons is listed, or an empty one if none.

Actual results:
Even if "Failed automatic validation" option is selected, after "Filter" click the "Passed automatic validation" option is listed.

Notes/Issues:
- don't know if having a beta file that fails automatic validation would change anything.
- could not check in production

Verified in FF52(Win 7). Issue is reproducing on -dev and -stage.
Video for this issue:
![failed](https://cloud.githubusercontent.com/assets/15685960/24240532/a9bfeaee-0fba-11e7-86fb-c6eefde7d132.gif)

**Comment by eviljeff** [comment]
@jvillalobos does anyone actually use the signed beta files log?   (And when would there be any failed validation)

**Comment by jvillalobos** [comment]
No, we've never really had the resources to cover beta files. I suppose we added that filter because at some point there would be validation rules that would block it from being automatically signed, but they were never added.

I think the filter can be safely removed. Not so sure about the log.

**Comment by muffinresearch** [comment]
Since beta is going away I'm going to wontfix this.
