### ISSUE TITLE
Developer replies are not threaded

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5015]
### Describe the problem and steps to reproduce it:

1) Receive two developer replies or other messages on one add-on

### What happened?
* The emails show up as two separate threads in my email client

### What did you expect to happen?
* Replies should include a References header to make them show up as one thread in my email client.

**Comment by wagnerand** [comment]
@kewisch would you agree that we'd probably want them to be grouped by *version*, not *add-on*?

**Comment by muffinresearch** [comment]
@eviljeff would you be able to take a look at this and see what it would take to fix when you have a moment?

**Comment by kewisch** [comment]
Yes, by version would be great! If you could make it so that all previous message ids are mentioned in the `References` header it would be great, in case the opening message was deleted in the user's inbox.

**Comment by eviljeff** [comment]
message-ids are generated (involving a random element) per message so we'd need to store the message-id in the database after each email is sent so it can be referenced in subsequent emails.

Github seems to use something other than message-ids for it's `Reference` header - I'm guessing it works because they use a common 'In-Reply-To:` header, and reference that instead.  Do Github emails thread for you correctly?  (I don't use threading typically)

**Comment by kewisch** [comment]
github messages all have one parent and are only one level deep. If you delete the parent message, the first child message becomes parent. If you implement it like they do that would be fine with me.

**Comment by vcarciu** [comment]
@kewisch @eviljeff  : I tried to add many developer replies to same add-on and the emails are still in different threads in my email client : 
![threaded](https://user-images.githubusercontent.com/1583842/27545680-19f8269a-5a99-11e7-918e-24638abdebd2.gif)

**Comment by wagnerand** [comment]
<eviljeff> Wait, I remember now - gmail threads based on subject line.  So our emails are never going to thread in gmail because they include the action taken

**Comment by vcarciu** [comment]
The emails still  show up as separate threads in my email client : 
![thread](https://user-images.githubusercontent.com/1583842/28455784-ec2689cc-6e08-11e7-9f6f-9a4e3b699276.gif)

**Comment by vcarciu** [comment]
Downloaded all details about emails received when testing :
[original_msg.txt](https://github.com/mozilla/addons-server/files/1165089/original_msg.txt)

Please let me know if any other thing is needed

**Comment by vcarciu** [comment]
Adding the other emails too : 
[original_msg(1).txt](https://github.com/mozilla/addons-server/files/1165114/original_msg.1.txt)
[original_msg(2).txt](https://github.com/mozilla/addons-server/files/1165115/original_msg.2.txt)
[original_msg(3).txt](https://github.com/mozilla/addons-server/files/1165116/original_msg.3.txt)

**Comment by muffinresearch** [comment]
I've been testing this locally and threading works fine in Gmail using django-anymail with mailgun to send real emails. I'm seeing threading in two separate accounts used to do the developer and reviewer parts of this. 

_Once caveat is that I'm using the web-interface to send the emails not replies via email._ 

Set-up was pretty simple I used this in a local_settings.py file with:

```python
from olympia.lib.settings_base import INSTALLED_APPS  # noqa

INSTALLED_APPS += (
    'olympia.landfill',
    'anymail',
)

ANYMAIL = {
    # (exact settings here depend on your ESP...)
    "MAILGUN_API_KEY": "api-key-sekret!",
    "MAILGUN_SENDER_DOMAIN": 'something-something-email-mailgun-whatever',  # your Mailgun domain, if needed
}
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"  # or sendgrid.EmailBackend, or...
DEFAULT_FROM_EMAIL = ""  # if you don't already have this in settings -  I set this to noreply@the-mailgun-domain
SEND_REAL_EMAIL = True # wasn't sure if this was actually needed
# *_EMAIL = '' I also set these to make sure any other mail didn't get routed to a real address for the purposes of the test.
```

Next step is to see how difficult it will be to have a local setup get hooked up to read the incoming mail.

@vcarciu do the examples you show above fail when replying via email? If so can you check if it doesn't fail to thread if using the web interface. At least this gives us some direction to debug the problem.

**Comment by vcarciu** [comment]
It looks that emails are not threaded from any place where I send a reply

**Comment by muffinresearch** [comment]
Let's see if the adding `<` and `>` makes any difference. 

As a side note - I saw looking at http://wesmorgan.blogspot.co.uk/2012/07/understanding-email-headers-part-ii.html that it would be expected that  the references header should be growing as more replies are sent.

**Comment by vcarciu** [comment]
The emails are still not threaded(sent many developer replies and they are still sent in separate threads). I added the details of messages received today : 
[original_msg(4).txt](https://github.com/mozilla/addons-server/files/1180408/original_msg.4.txt)
[original_msg(5).txt](https://github.com/mozilla/addons-server/files/1180409/original_msg.5.txt)
[original_msg(6).txt](https://github.com/mozilla/addons-server/files/1180410/original_msg.6.txt)

**Comment by wagnerand** [comment]
😩

Can we maybe set the message-id manually? We're referencing emails like <494585/1532646@addons-dev.allizom.org> but I don't see where we'd ever set such a message-id.

**Comment by vcarciu** [comment]
I am not sure if I am doing something wrong here or not, but if I add more developer replies, I still can see as different threads in my email client :(

**Comment by eviljeff** [comment]
Almost out of ideas for this.  We could generate a full list of references, based on how we now consistently generate message IDs from the addon, version and activity ids.

**Comment by wagnerand** [comment]
With the latest changes, threading works fine for me on prod. I'm closing this for now, until we have a specific example where it doesn't.
