### ISSUE TITLE
Fileviewer performance needs improvement

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5016]
### Describe the problem and steps to reproduce it:

1) Visit https://addons.mozilla.org/en-US/firefox/files/browse/521169/ when it is not cached
2) open modules/ical.js

### What happened?

**Request for (1):**
Blocked: → 0 ms
DNS resolution: → 0 ms
Connecting: → 0 ms
Sending: → 0 ms
Waiting: → 26604 ms
Receiving: → 7025 ms

**Request for (2):**
Blocked: → 0 ms
DNS resolution: → 27 ms
Connecting: → 223 ms
Sending: → 0 ms
Waiting: → 32172 ms
Receiving: → 1158 ms

### What did you expect to happen?
Substantially faster loading times

### Anything else we should know?
The file browser is a prime tool for reviewers to do their work. Large add-ons take a long time to load, which adds up and is frustrating. Even loading subsequent files take just as long as the initial file.

I am experiencing delays regularly and it is not always as bad as it is with Lightning, but I chose this example because I knew it would trigger the issue due to the file size.

**Comment by diox** [comment]
cc @EnTeQuAk since it's close to #5135

**Comment by muffinresearch** [comment]
Likely to be fixed when we get to replacing the whole thing. It's not worth trying to fix this with the current code I would think.

**Comment by EnTeQuAk** [comment]
> Likely to be fixed when we get to replacing the whole thing. It's not worth trying to fix this with the current code I would think.

Closing precisely because of that.
