### ISSUE TITLE
Theme switching on AMO causes tab to go blank

### ISSUE THREAD

**Issue by adamopenweb** [mozilla/addons-server#5019]
### Describe the problem and steps to reproduce it:
**URL**: https://addons.mozilla.org/en-US/firefox/themes/
**Browser / Version**: Firefox 55.0
**Operating System**: Linux

**Steps to Reproduce**
1. Navigate to: https://addons.mozilla.org/en-US/firefox/themes/
2. Try out one of the themes by hovering your mouse over "Globules Multicolores" or "ABSTRACT'".

### What happened?
The tab goes blank

### What did you expect to happen?
Still see the webpage

### Anything else we should know?
Certain themes like "Globules Multicolores" or "ABSTRACT'" cause the tab to go blank. The page is still there and you can hover over different themes, but the page stays blank.

Originally reported here: https://github.com/webcompat/web-bugs/issues/5268

![Screenshot Description](https://webcompat.com/uploads/2017/3/7007d81b-a2af-4c7a-815f-9bcad3677535.jpg)

**Comment by diox** [comment]
Thanks, this looks like a Firefox bug though (that should be filed on bugzilla) - I can reproduce on Firefox 55 but not on Firefox 52 on Linux (and the code that does the preview on AMO hasn't changed in ages)

**Comment by diox** [comment]
FWIW the code that we use to preview themes https://github.com/mozilla/addons-server/blob/2eeedbfab1dd46a9d51e4195ad1bf403a2941cec/static/js/zamboni/personas_core.js#L7

I can still reproduce with today's nightly on Linux. Will open a bug (bugzilla is down for maintenance atm)

**Comment by diox** [comment]
Firefox bug tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1351352
