### ISSUE TITLE
Stats on AMO-dev are forever loading

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5022]
Steps to reproduce:
1. Go to Statistics page for any add-on with public stats i.e. https://addons-dev.allizom.org/en-US/firefox/addon/noverflow/statistics/?last=365

Expected results:
Some stats or no results are displayed.

Actual results:
Dashboards are forever loading.

Notes/Issues:
- if the period is changed, a `js` error is displayed in the browser console - "TypeError: this._recipeManager is null" 

Verified on FF52(Win 7). Issue is ONLY reproducing on dev.
Video for this issue: 
![load](https://cloud.githubusercontent.com/assets/15685960/24286647/b313116a-107e-11e7-81b9-464932703435.gif)

**Comment by diox** [comment]
Dev does not have working stats.

**Comment by ValentinaPC** [comment]
It should, at leas as those from Stage....imho.
