### ISSUE TITLE
Title is not wrapped for non-en locales while in "Add-ons for Android" Themes homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5037]
Steps to reproduce:
1. Load Themes homepage on desktop - "Add-ons for Android", using AMO-dev while your language is set to `Italiano` - https://addons.allizom.org/it/android/themes/

Expected results:
There are no display or layout issues.

Actual results:
Page title overlays the search bar.

Notes/Issues:
- reproducing also for Search Tools homepage: https://addons.allizom.org/it/android/search-tools/

Verified on AMO-dev FF52(Win 7). Reproducing all around AMO servers.
Screenshot for this issue:
![st](https://cloud.githubusercontent.com/assets/15685960/24358542/23af171a-130a-11e7-9535-dd7ca183316e.png)

**Comment by wagnerand** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @tofumatt

**Comment by psionikangel** [comment]
Hi @tofumatt and others,

I have prepared a fix for this bug at https://github.com/psionikangel/addons-server/commit/751db86f14dbdc4a6c8bfdd5211574410ea83223

Here are some **before** screenshots:
_italian_
<img width="1002" alt="before-italian" src="https://cloud.githubusercontent.com/assets/547413/25293424/de8afb24-26a8-11e7-9c57-05dc74c64e01.png">
_portuguese_
<img width="967" alt="before-portuguese" src="https://cloud.githubusercontent.com/assets/547413/25293425/de8b62ee-26a8-11e7-8159-8fef6d6454c0.png">

And the **after** screenshots:
_italian_
<img width="1000" alt="after-italian" src="https://cloud.githubusercontent.com/assets/547413/25293436/ea2c4050-26a8-11e7-8c5b-2b35d3926303.png">
_portuguese_
<img width="982" alt="after-portuguese" src="https://cloud.githubusercontent.com/assets/547413/25293437/ea2fa79a-26a8-11e7-8dcf-82aead4008fe.png">

Could you review this when you have some free time?

Regards,

**Comment by umaarabdullah** [comment]
@psionikangel this looks nice. I think you should send a pull request.

**Comment by umaarabdullah** [comment]
@psionikangel this looks nice. I think you should send a pull request.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
