### ISSUE TITLE
Problems with working with Firefox

### ISSUE THREAD

**Issue by belibelibeli** [mozilla/addons-server#5044]
### Describe the problem and steps to reproduce it:  This link doesn't work to install add-on:
https://addons.mozilla.org/en-US/firefox/addon/email-signature-rescue/
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by belibelibeli** [comment]
Not working with Firefox.

**Comment by tofumatt** [comment]
It looks like that add-on is no longer available. If you had installed it previous Please contact the add-on author; this is just the issue tracker for the website that hosts the add-one for Firefox. Unfortunately we can't provide any support for the add-ons themselves.
