### ISSUE TITLE
API for finding out web extensions

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#5045]
### Describe the problem and steps to reproduce it:
I don't know how to figure out if an add-on is a _web extension_. https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#add-on-feature-compatibility is only helpful to find out how to list add-ons that are _Electrolysis (multiprocess) compatible_, this is not not the same thing.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[Add-on Compatibility Reporter](https://github.com/mozilla/addon-compatibility-reporter) should add extra text in the **Add-on Manager** next to each add-on by changing the "Compatible with multiprocess" to "[Not] compatible with multiprocess. This is [not] a web extension".

**Comment by diox** [comment]
Should be done as part of https://github.com/mozilla/addons-server/issues/4974

Note that Add-on Feature Compatibility does make the distinction between webextensions and other types of extensions : any (and only) webextension should return `compatible-webextension` through that API, so you can definitely use it to confirm whether or not an add-on is a webextension. There is just one small limitation: it will use the latest uploaded version, which may not be public yet.

Please file a separate issue for Add-on Compatibility Reporter in that repository.

**Comment by davidhedlund** [comment]
https://github.com/mozilla/addon-compatibility-reporter/issues/78
