### ISSUE TITLE
Average rating stars is not looking good

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5049]
Steps to reproduce:
1.On Android, go to https://addons-dev.allizom.org/en-US/android/addon/shamrocks2/
2.Observe the average rating stars under number of users (2,5 out of 5)
3.Open "Read all 3 reviews" link under rating section
4.Observe the Ratings(2x4 star ratings and one of 3 stars rating)

Expected results:
The average rating stars should indicate an average of 3,66 out of 5 stars

Actual results:
2,5 out of 5 stars

Notes:
Moved from addons-frontend (mozilla/addons-frontend#2200)

Please see video for this issue :
![avgstars](https://cloud.githubusercontent.com/assets/1583842/24414099/0c81aec2-13e6-11e7-9cc6-dad82354c884.gif)

**Comment by diox** [comment]
Re-triggering the task that calculates the average fixed it for this particular add-on.

@vcarciu can you try to figure out STRs leading to this state with a fresh add-on ? This one has some very old reviews, some of them deleted - I suspect it's related but it's hard to find out what happened without more precise STRs. It might be that it's just a problem with dev and its frequent deploys breaking the tasks that calculate the average.

**Comment by vcarciu** [comment]
@diox - You are right , with new reviews the average looks good. I tried also to delete/edit some reviews and everything was ok in this case too , so I guess that it's just a problem with -dev , as you said.

**Comment by diox** [comment]
Closing for now. Re-open if you find more cases.

**Comment by vcarciu** [comment]
@diox - There is one more scenario for the average on Android. If you have more than one reviews/user on desktop, then the average will include all the reviews for this user in the math, not only the last one. The problem is that on Android we are displaying only last review for an user and this will lead to misunderstandings for the Android users. What do you think?

**Comment by diox** [comment]
That's a valid issue, yeah. I think we should only care about the latest review for each user. Can you open a different issue for that ?

**Comment by tofumatt** [comment]
One other thing I just realised about averages: because we hide star ratings that don't have text reviews, you could leave five 5-star reviews with no text, one 1-star review with text, and would see an average of 4.5 or 5 stars with a single 1-star review visible.

Not much way around this, but it could look weird 🤷‍♀️

**Comment by diox** [comment]
> One other thing I just realised about averages: because we hide star ratings that don't have text reviews, you could leave five 5-star reviews with no text, one 1-star review with text, and would see an average of 4.5 or 5 stars with a single 1-star review visible.

Yeah, this could look a little weird. On mobile we don't seem to be displaying the count for each rating - we display that on desktop (see https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/ on the right next to the reviews) and it would help a little (need to pass `show_grouped_ratings` to the [reviews list API](http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#list-reviews) to get that)
