### ISSUE TITLE
Remove django-mobility and all code serving mobile-specific pages

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5055]
Now that we've switched the mobile site to mozilla/addons-frontend + API we don't need all the code that serves a different mobile template, detects mobile users etc, we should remove that.

One thing to make sure is that we don't still need some of this stuff behind the scenes. Like, I don't know how the mamo cookie system works at the moment. Does it rely on something in addons-server code setting it ? We were using `mobility.middleware.DetectMobileMiddleware` and `mobility.middleware.XMobileMiddleware` but they don't appear to set cookies, though the former adds a `Vary` header on `User-Agent`.

cc @muffinresearch and @bqbn for input about how it works now.

**Comment by muffinresearch** [comment]
The cookie setting on the desktop frontend is in JS so that bit needs to stay.

I don't think there's anything else related to the mobile middleware that needs to stay. The mechanism for redirection is all happening at the nginx level so the mobile middlewares are not involved.

The only other consideration is looking at the way that the mobile middelware optimizes caching - I'm not sure if we're doing the same in nginx or if there is potentially some useful functionality that we should look to implement. See https://github.com/jbalogh/django-mobility#varying-on-user-agent for more information.

**Comment by diox** [comment]
> The proxy can run the logic in DetectMobileMiddleware and set HTTP_X_MOBILE (so we know whether to serve a mobile view) without varying on user agent internally. Instead, it can vary on X-Mobile while sending Vary: User-Agent back to the client. From the outside it looks like the app varies on User-Agent but the proxy will only need to cache a mobile and non-mobile version of the URL.

mmm, atm we do the detection in nginx, but we also have the middleware active, re-doing the detection (useless) and adding `User-Agent, X-Mobile` to the `Vary` header. The proposed optimization here makes sense, but for now we can keep the existing `Vary`.

So IMHO we should:
1) Consider that `Vary` optimization, but in another issue
2) Remove django-mobility in this issue, but keep (move it to addons-server) the middleware part that sets the `Vary` on both headers for now.

**Comment by muffinresearch** [comment]
Would it make sense to have nginx add vary headers? Afaik we're not varying on user-agent from the addons-frontend app presently.

**Comment by diox** [comment]
It probably would. addons-server currently sends:
`Vary: Accept-Language, User-Agent, X-Mobile`

If all of those would be set at the nginx level it would simplify things. They should definitely be needed on all pages where we have the UA detection, as well as pages depending on the user language. We can probably skip `X-Mobile` if we don't use it, but it doesn't hurt to have it.

Random notes:
- I don't know how we cache things on top of addons-server/addons-frontend at the moment. I vaguely recall there is something for disco pane, but I don't know what and whether it only affects disco pane. This can be impacted by `Vary` changes.
- I think we should technically vary on `Cookie` but we don't seem to, I don't know why.

**Comment by diox** [comment]
@bqbn could you tell me if we set `Vary` header at nginx level right now, and if so what do we set and where ? Also, while I'm at it, where does the mobile detection happens ? Thanks.

**Comment by bqbn** [comment]
We don't set Vary header at the nginx level. The headers we set are following
```
add_header Content-Security-Policy "default-src 'none'; report-uri /__cspreport__";
add_header Content-Disposition attachment;
add_header Content-Security-Policy "default-src 'none'; report-uri https://addons.mozilla.org/__cspreport__";
add_header Content-Security-Policy "default-src 'none'; report-uri https://addons.mozilla.org/__cspreport__";
add_header Content-Security-Policy "default-src 'none'; report-uri https://addons.mozilla.org/__cspreport__";
add_header Access-Control-Allow-Origin *;
add_header Content-Security-Policy "default-src 'none'; report-uri /__cspreport__";
add_header Access-Control-Allow-Origin *;
add_header Access-Control-Allow-Methods GET;
add_header Content-Security-Policy "default-src 'none'; report-uri /__cspreport__";
add_header Public-Key-Pins 'max-age=5184000; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="';
```

The mobile detection happens at nginx level. It checks the UA and the mamo cookie. The logic happens in the following sequence.

If mamo is set to "on", redirects to the mobile site.
If mamo is set to "off", redirects to the desktop site.
If mobile UA, redirects to the mobile site.
otherwise fall back to the desktop site.

**Comment by diox** [comment]
So... from that answer and what I can see in the code, https://github.com/jbalogh/django-mobility#varying-on-user-agent is not true is on current configuration. That is to say, though we do the detection in nginx, we keep both django-mobility python middlewares in all situations (local/dev/stage/prod) and therefore, it adds `User-Agent` and `X-Mobile` to the `Vary` header in responses, and re-does the mobile user agent detection on each request. 

Focusing on simply removing django-mobility, without trying to optimize for now, it means we need to:
* Add an unconditional `Vary: User-Agent` - ideally only on pages which paths that can be handled by both addons-frontend and addons-server
* Pass something down a request header to addons-server so that it knows the result of the detection. That is because it needs to serve a different, responsive 404 page to mobile devices (see https://addons.mozilla.org/en-US/firefox/404-on-purpose/ with a mobile browser for instance).

@bqbn would it be possible to have both those things done in nginx ? If so, let me know where I can file an issue to make that happen.

**Comment by bqbn** [comment]
What is the purpose for adding ```Vary: User-Agent``` header now that we're removing the django-mobility middleware anyway?

According to https://bugzilla.mozilla.org/show_bug.cgi?id=1330939#c13 there should already be a responsive 404 page for mobile. I think it's in https://github.com/mozilla/addons-server/pull/4715.

**Comment by diox** [comment]
The purpose is to let upstream caches cache pages differently since for the same URL, depending on the user agent, you might get served a mobile or a desktop page. *Technically* we should also vary on `Cookie` but I'm going for the exact same result here first before messing with things.

There *is a responsive 404 already, I'm not saying otherwise :) The problem is, we can not serve it to desktop (it's meant for the new mobile design only). So without django-mobility, addons-server needs *something* to know it should be serving the responsive one or the legacy one.

**Comment by bqbn** [comment]
@diox please create a bugzilla ticket for this and we can discuss the details there.

Nginx should be able to add the Vary header for the clients and pass a header for the application.

**Comment by diox** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1361323
