### ISSUE TITLE
Thunderbird most popular extensions list has broken link

### ISSUE THREAD

**Issue by TAnthrax** [mozilla/addons-server#5056]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
The issue occurs on page 3/68 near the bottom of the list at [https://addons.mozilla.org/en-US/thunderbird/extensions/?sort=users&page=3](https://addons.mozilla.org/en-US/thunderbird/extensions/?sort=users&page=3) when you click on the extension Clean Links it leads to a custom 404 page here: [https://addons.mozilla.org/en-US/thunderbird/addon/clean-links/?src=cb-dl-users](https://addons.mozilla.org/en-US/thunderbird/addon/clean-links/?src=cb-dl-users)
### What happened?
The link is broken for the extension's details page as well as the download
### What did you expect to happen?
I expected the link to not 404 (I expected to download "clean links")
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
I assume Clean Links has been taken down, if so it should be removed from any lists it is featured in. 
Thanks!

**Comment by bkzhang** [comment]
It seems like the addon was removed, it does not appear for me.

**Comment by jvillalobos** [comment]
Yes, it sounds like it was a temporary caching issue. I don't see the add-on on the first few pages of that list.
