### ISSUE TITLE
Remove total_contributions field and related task

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5069]
`Addon` has a `total_contributions` field that well, represents the total number of contributions (donations) made to this add-on through AMO. We recalculate this field each time a contribution is made through a celery task.

But is that field useful to anyone ? It's not exposed anywhere AFAIK. Removing it would free up the task queues a little bit.

**Comment by diox** [comment]
@jvillalobos are you using this field ? Can we get rid of it ?

**Comment by jvillalobos** [comment]
You can see contribution stats in the statistics dashboard. I suppose that's where it's used.

**Comment by jasonthomas** [comment]
Can we just move this task to cron?

**Comment by diox** [comment]
The contribution stats dashboard uses the `Contribution` model/table rows, *not* that `total_contributions` field.

**Comment by jvillalobos** [comment]
If it's not being used, it's okay by me to remove it.

**Comment by diox** [comment]
Task was removed in https://github.com/mozilla/addons-server/issues/5070 ; the field is still here but can be removed at any time. Note that it defaults to `NULL` so we should be able to remove it from the models first and then from the db at a later date.
