### ISSUE TITLE
Clean Links deleted from AMO for allegedly not working with e10s

### ISSUE THREAD

**Issue by leedoyle** [mozilla/addons-server#5073]
Clean Links is a great extension that many users enjoyed, and in fact, the most popular and capable choice for deobfuscating links.
![LastSeenOnAMO](https://cloud.githubusercontent.com/assets/25978190/24577823/1859bb18-16de-11e7-9e3b-05271e432d52.png)
[extension link](https://addons.mozilla.org/en-US/firefox/addon/clean-links/)
[archived link](http://web.archive.org/web/20170311015206/https://addons.mozilla.org/en-US/firefox/addon/clean-links/)

I think the fact that the extension is not e10s yet should NOT be a reason for deleting it from AMO altogether! And as far as I know, it's not in the rules either. 
Please consider restoring it, not the least because it does work with ESR 45 which is still supported.

**Comment by EnTeQuAk** [comment]
Please contact the add-on author about his add-on as we do not remove add-ons unless there's a good reason, if something is not e10s compatible a user gets a proper warning instead.

**Comment by leedoyle** [comment]
@EnTeQuAK it doesn't explain why mozilla team deleted the extension from AMO

**Comment by jvillalobos** [comment]
The add-on was disabled because it was causing problems for users (unrelated to e10s) and we wanted to prevent more people installing it and having a bad experience. It's up to the developer to submit a new version that addresses these issues. Given it hasn't been updated in over 2 years, it seems unlikely.
