### ISSUE TITLE
"Upload another file" is not available for and Android compatible add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5083]
Steps to reproduce:
1. Submit an add-on compatible only with Android i.e. https://addons-dev.allizom.org/en-US/developers/addon/legacy-android/versions/1531893
2. Add a new file for its version

Expected results:
A new file can be added.

Actual results:
"Upload another file" button is not available. 

Notes/Issues:
- only "Android" option is displayed in the file drop-down
- if a new compatibility app is selected from manage version page i.e. Thunderbird, and the changes are saved, uploading a new file is possible. 

Verified on AMO-dev FF52(Win 7). Issue is reproducing on all AMO-servers.
Video for this issue: 
![oneoption](https://cloud.githubusercontent.com/assets/15685960/24613836/31cf1a24-1892-11e7-8cc1-578a2a2dad63.gif)

**Comment by muffinresearch** [comment]
@diox any idea why this is?

**Comment by diox** [comment]
This is not a bug. If your add-on is only compatible with Firefox for Android, then you don't need to add another file to it... When you add compatibility to another app then that becomes useful and the option to add another file is then present.
