### ISSUE TITLE
Trying to submit a multi-platform add-on after an 1-platform add-on will not reset the platform availability

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5085]
Steps to reproduce:
1. Select an Android-only compatible add-on file from submission page https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed
2. Observe platform availability (only Android available -> expected)
3. Refresh the page and select a multi-platform compatible add-on file
4. Observe the platform availability

Expected results:
Platform availability is reset.

Actual results:
Platform availability is limited to "Android". 

Notes/Issues:
- closing the tab and opening a new one or navigating to another page will fix the problem;

Verified on FF52(Win 7). Issue is reproducing on all AMO-servers.
![onlyan](https://cloud.githubusercontent.com/assets/15685960/24616245/34b9c624-1899-11e7-8fb5-486142bbd79a.gif)

**Comment by eviljeff** [comment]
is this still reproducible with webextensions?  (that are inherently compatible with both Desktop and Android)

**Comment by ValentinaPC** [comment]
@eviljeff : reproducing also if second add-on is webextension.
But, analyzing better this issue, saw that the platform limitation only happens if there is an issue with the second add-on and generates an error.

Video 1 without error for second add-on:
![not](https://user-images.githubusercontent.com/15685960/30744296-1e8a1140-9faa-11e7-9bc0-a78a20d45766.gif)
Video 2 with error for second add-on:
![err](https://user-images.githubusercontent.com/15685960/30744522-1f42feb6-9fab-11e7-817e-bc5edeb2a641.gif)

So I think that we can close this.
