### ISSUE TITLE
Remove sandbox field from Review model

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5090]
The `Review` model has this field:
`sandbox = models.BooleanField(default=False)`

It does not appear to be used anywhere. If that's truly the case, let's remove it.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by harikishen** [comment]
@diox I would like to take this up.

**Comment by harikishen** [comment]
What all are the things to keep in mind while removing fields from models for this project ? I mean will it break something ? @diox

**Comment by diox** [comment]
You need to create a SQL migration with the necessary `ALTER TABLE` command to remove the field, and put that in `src/olympia/migrations/xxx-migration-name.sql` - look in that folder for more migrations for inspiration. `xxx` needs to be replaced with the latest migration number + 1.

**Comment by harikishen** [comment]
@diox is it necessary that i should update the latest working copy of master branch ?

**Comment by harikishen** [comment]
i get about 111 errors while running the tests after doing the said changes.
https://pastebin.mozilla.org/9022278
https://pastebin.mozilla.org/9022279
https://pastebin.mozilla.org/9022280
https://pastebin.mozilla.org/9022281
https://pastebin.mozilla.org/9022282
https://pastebin.mozilla.org/9022283
these are just some of them i can't fit the entire log to pastebin at a time

**Comment by diox** [comment]
I would recommend updating your working copy of master yes, just to make sure your migration is named correctly, yes.

Regarding your errors, you need to run the tests with a new, fresh db (`--create-db` option).

**Comment by harikishen** [comment]
thanks @diox i'm kind of new to tests so didn't think of the db.

**Comment by harikishen** [comment]
https://pastebin.mozilla.org/9022287 this is the only error remaining

**Comment by harikishen** [comment]
I fixed the errors with json files but this one seems to have some issue with guarded-addons section

**Comment by harikishen** [comment]
and may i know what the files in guarded-addons are ?

**Comment by harikishen** [comment]
@wagnerand @diox any idea what causes that failure ?

**Comment by harikishen** [comment]
@diox @wagnerand @eviljeff thanks
