### ISSUE TITLE
Fetching Add-on review history fails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5093]
### Describe the problem and steps to reproduce it:

1. Go to https://addons.mozilla.org/en-US/developers/addon/qirimtatarca-til-destesi/versions
2. Click _Show Review History_ for version 52.0

### What happened?

```We had a problem retrieving review notes
/api/v3/addons/addon/7420/versions/2049978/reviewnotes/, UNAUTHORIZED, {"detail":"Error decoding signature."}
```

### What did you expect to happen?

Seeing the review history.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ValentinaPC** [comment]
This is happening, for sure, starting from about a week ago.
Please see my comment from https://github.com/mozilla/addons-server/issues/4915

**Comment by wagnerand** [comment]
Actually, I think https://github.com/mozilla/addons-server/issues/4915#issuecomment-289744624 is related to this issue, while the original report for #4915 is something else, as the error message is different.

**Comment by ValentinaPC** [comment]
As you can read in my comment, I also received Jorge's error, while using a new clean profile, that is why I chose to comment there and not to log another issue.

**Comment by diox** [comment]
I missed a spot when changing the token cookie name in #4907. Will fix.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Win 7).
New submission, listed/unlisted or mixed add-ons/webext, awaiting or approved versions - all seem to return correct the info from Review History section using an old or a new-clean profile.
Postfix screenshots:
![2017-04-04_1745](https://cloud.githubusercontent.com/assets/15685960/24662764/befbd5be-195e-11e7-9a77-f9736cbbdeb0.png)
![untitled](https://cloud.githubusercontent.com/assets/15685960/24662765/bf2784c0-195e-11e7-958e-99e5237e7412.png)
