### ISSUE TITLE
Please add "Urdu" language to AMO desktop site

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5094]
Steps to reproduce:
1. Load AMO-dev page on desktop https://addons-dev.allizom.org/en-US/firefox/
2. Change the language to "ur"

Expected results:
The language is available in the drop-down.

Actual results:
The language is not available in the drop-down.

Notes/Issues:
Verified on AMO-dev FF52(Win 7).
The language is added to mobile site as for https://github.com/mozilla/addons-frontend/pull/2203

**Comment by ValentinaPC** [comment]
"Urdu" language was added to desktop pages, but while selecting the language the content of AMO (old desktop pages) si not RTL. Is this ok?
Postfix screenshots:
![ur](https://user-images.githubusercontent.com/15685960/29766854-e755d846-8be8-11e7-9254-d64d6a4b3972.png)
![ur-footer](https://user-images.githubusercontent.com/15685960/29766855-e7573024-8be8-11e7-9e1f-cd24334f767b.png)

**Comment by EnTeQuAk** [comment]
fair point, I missed that during review. I looked it up again and yeah, urdu is indeed an RTL language. 

@atiqueahmedziad mind submitting a patch that adds urdu to `settings.LANGUAGES_BIDI` as well and check that it's properly rendered as RTL?

**Comment by atiqueahmedziad** [comment]
@ValentinaPC Thanks for notifying. 
@EnTeQuAk Offcourse I will love to submit a patch for that. Thnaks

**Comment by ValentinaPC** [comment]
The `ur` language is still not RTL on AMO-dev.
Verified this using FF55(Win 7).
Video:
![ur](https://user-images.githubusercontent.com/15685960/29866141-26777b4a-8d80-11e7-84e8-02f222d466e3.gif)

**Comment by muffinresearch** [comment]
This has been fixed.

<img width="1385" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35752210-104bc0f8-0853-11e8-9ddd-26d2875a7968.png">

**Comment by AlexandraMoga** [comment]
Marking this as verified fixed on AMO prod, FF58

![image](https://user-images.githubusercontent.com/31961530/35846839-d504eae4-0b20-11e8-8d05-4ed3a5bbf6f4.png)
