### ISSUE TITLE
Disco Pane content update - April 

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#5099]
For the **20 April** push, can we please REMOVE: 

- Video DownloadHelper
- all three current themes

… and REPLACE them with Bulk Media Downloader and three new themes. 

**Download media** 
with [Bulk Media Downloader](https://addons.mozilla.org/firefox/addon/bulk-media-downloader/)
Manage massive audio, video, and image downloads with this lightweight tool. 

[themes]

[Japanese Tattoo](https://addons.mozilla.org/firefox/addon/japanese-tattoo/) by enguyen
[Two Little Birds](https://addons.mozilla.org/firefox/addon/two-litle-birds/) by math3us.c
[Giz Gaz](https://addons.mozilla.org/firefox/addon/giz-gaz/) by Bátja

Full page content ordering: 

Japanese Tattoo
Bulk Media Downloader
uBlock
Two Little Birds
Awesome Screenshot Plus
Emoji Keyboard
Giz Gaz

**Comment by muffinresearch** [comment]
@EnTeQuAk As always we'll need get the strings landed early to give translators as much time as possible ahead of the 20th release.

**Comment by EnTeQuAk** [comment]
Scheduled merging the changes (opening the PR a bit earlier) for next Tuesday (04/11) after the tag.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF53(Win 7).
Postfix screenshot:
![untitled](https://cloud.githubusercontent.com/assets/15685960/25273141/322fe58e-2693-11e7-85a2-f24b4547679a.png)
