### ISSUE TITLE
Search by tags is returning an old mobile page while "View Mobile Site" link is clicked

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5105]
Steps to reproduce:
1. Load details page for an add-on that has some tags available i.e. https://addons.mozilla.org/en-US/firefox/addon/instant-translate/
2. Click on any listed tag
3. Click "View Mobile Site" from page footer

Expected results:
Nothing happens because the page does not exist on mobile.

Actual results
An old mobile page is displayed.

Notes/Issues:
Verified on FF52(Win 7). Issue is reproducing all around AMO servers.
Video for this issue: 
![oldmp](https://cloud.githubusercontent.com/assets/15685960/24701452/379a826e-1a03-11e7-995e-54150a89b2f0.gif)

**Comment by diox** [comment]
Old mobile pages are gone and this bug appears to be fixed. 

(Ideally we should to replace the tag view/links by a regular search like `https://addons.mozilla.org/en-US/firefox/search/?tag={insert_tag_here}`)

**Comment by ValentinaPC** [comment]
Following the above steps, a mobile page is not loaded and the same page is refreshed, as intended.
Postfix video:
![view](https://cloud.githubusercontent.com/assets/15685960/25854411/8cf4afa6-34d8-11e7-98b7-3c4224cbaa29.gif)

Marking this verified-fixed.
