### ISSUE TITLE
Admin changed add-on status to "awaiting..." will not remove it from a collection

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5109]
Prerequisites:
- user is signed in with an admin account;

Steps to reproduce:
1. Create a collection in AMO-stage i.e. https://addons.allizom.org/en-US/firefox/collections/Vivre/collection-unreviewed-add-on/
2. Pick an add-on from that collection and change its status to "Awaiting review"
3. Go to collection page again

Expected results:
Add-on is no longer displayed inside the collection.

Actual results:
The unreviewed add-on is listed inside the collection.

Notes/Issues:
- disabling the add-on, making it incomplete will remove the add-on from the collection.
- invisible status will also remove the add-on from the collection
Verified on FF52(Win 7). Issue is reproducing on AMO-stage and -dev.
Screenshot for this issue: 
![2017-04-05_1605](https://cloud.githubusercontent.com/assets/15685960/24706914/44e6e6bc-1a1a-11e7-878a-ff8e2ed8e502.png)

**Comment by eviljeff** [comment]
@jvillalobos is this admin edge case worth handling?

**Comment by jvillalobos** [comment]
No, I don't think this matters much.
