### ISSUE TITLE
Legacy add-on with correct maxVersion is restricted at submission with incomplete error message

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5110]
Steps to reproduce:
1. Try to submit a legacy add-on that has an accepted `maxVersion` (ex. 52) but without `strict compatibility `

Expected results:
A clarification error message is displayed.

Actual results:
The message "Starting with Firefox 53, new extensions on this site can only be WebExtensions." is displayed.

Notes/Issues:
- user may be confused about the reason of its submission restriction, given the fact that its add-on has `maxVersion `under 53.

Verified on FF52(Win 7). Issue is reproducing on AMO-dev and -stage.
Screenshot for this issue:
![2017-04-05_1754](https://cloud.githubusercontent.com/assets/15685960/24711636/3251fece-1a29-11e7-833a-a1850541f3b7.png)

Attaching used add-on. 
[legacy addon-nosc+kanji.zip](https://github.com/mozilla/addons-server/files/899769/legacy.addon-nosc.kanji.zip)

#4234

**Comment by jvillalobos** [comment]
We don't want to encourage people to use `strictCompatibility`, and we can respond to it if they ask us about it. For now I'd rather not change the text, but will reconsider if it becomes a big problem.
