### ISSUE TITLE
Support section from "Write a review" for is not working at a second try

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5114]
Steps to reproduce:
1.Go to any add-on with support section )https://addons.allizom.org/en-US/firefox/addon/stratiform/?src=hp-dl-featured )
2.Click "Write a review " button
3.In the Review pop-up window, click the "support section" link and observe that you were redirected to add-on detail page with support links in the right side
4.Click again "Write a review" button
5.In the Review pop-up window, click the "support section" link again

Expected results:
You are redirected to add-on detail page with support links in the right side as in step 3

Actual results:
Nothing happens when clicking the "support section" from write a review form second time

NOTES:
Reproducible on all servers

Please see video for this bug : 
![write review support section](https://cloud.githubusercontent.com/assets/1583842/24745200/75644c28-1abd-11e7-9e0f-46854e7dd263.gif)

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
