### ISSUE TITLE
Profile picture with significant difference between height and width brakes Dev Hub page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5116]
Steps to reproduce:
1. Set a profile picture (with big height) - https://addons.allizom.org/en-US/firefox/users/edit
2. Load Developer Hub page i.e. https://addons.allizom.org/en-US/developers/
3. Observe account icon

Expected results:
There are no display or layout issues.

Actual results:
The account icon brakes the page.

Notes/Issues:
- issue is also reproducing for profile picture with big width;
- "My Profile" page is not affected by the height size - https://addons.allizom.org/en-US/firefox/user/Vivre/ ;

Verified on FF52(Win 7). Issue is reproducing on all AMO servers.
Screenshot for this issue:
![height](https://cloud.githubusercontent.com/assets/15685960/24747370/d7113556-1ac4-11e7-9917-d305da1a38bf.png)

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

mentor: me

I think the fix for this is just adding some css that sets a max-height for the img to something sensible.

**Comment by CuriousLearner** [comment]
Hey @eviljeff 

I'm working on this issue.
I did change `.DevHub-Navigation ul li.avatar img` to have a `height` of `40px`, same as the `width` of the selector in the file: `static/css/devhub/new-landing/base.less.css`

But once I refresh the page, I did not see any change. Am I missing something here?

**Comment by CuriousLearner** [comment]
Ah, seems like I'm able to get it done. But I think this file in in `.gitignore`. How do we get past it?

**Comment by CuriousLearner** [comment]
I guess that it should be modified in some other file and the `*.less.css` file is generated. Is that correct? Can you please provide me a pointer on this?

**Comment by eviljeff** [comment]
yes, `base.less.css` is generated from `base.less`

**Comment by CuriousLearner** [comment]
Oh, thanks, I figured out we're using https://github.com/jsocol/jingo-minify for minifying assets. I'm done with the patch, will raise a PR in just few mins :)

**Comment by ioanarusiczki** [comment]
This issue is verified on AMO dev with FF58(Win10). 
7680 pixels height 
![7680 pixels height](https://user-images.githubusercontent.com/33448286/37028704-a5d27b14-213d-11e8-91da-c791c9fc648a.png)

5000 pixels width 
![5000 pixels width](https://user-images.githubusercontent.com/33448286/37028731-b8823362-213d-11e8-97a9-190f5345c997.png)
