### ISSUE TITLE
"Cancel Review and Disable Version" for third version also disables second unapproved version of an add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5117]
Steps to reproduce:
1. Submit a listed add-on https://addons.allizom.org/en-US/developers/addon/submit/upload-listed and approve it
2. Add a second listed version for this add-on (without approve)
3. Add a third version, but stop the submission process by clicking the "Cancel Review and Disable Version"
4. Go to "Manage Status and Versions" page

Expected results:
Only third version is disabled.

Actual results:
Second version is also disabled, even if, third version submission was not finalized.

Notes/Issues:
Verified on FF52(Win 7). Issue is reproducing on AMO-stage and dev.
Video for this issue:
![disable](https://cloud.githubusercontent.com/assets/15685960/24752926/b6acdaea-1ad8-11e7-8c99-395746d30d57.gif)

**Comment by eviljeff** [comment]
The second version is disabled as soon as the third version is submitted (at the point you 'Continue').  It's not a great flow admittedly but it's not a bug as such.
