### ISSUE TITLE
Provide error codes for failed API auth responses

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#5122]
### Describe the problem and steps to reproduce it:

Open a page on mobile AMO, let your auth token expire (see https://github.com/mozilla/addons-frontend/issues/2130), and try to do something requiring auth like submit a star rating. 

### What happened?

The API returns a response like:
````json
{"detail": "Signature has expired."}
````

### What did you expect to happen?

We need some kind of error code we can use, like:
````json
{"detail": "Signature has expired.", "code": "SIGNATURE_EXPIRED"}
````
### Anything else we should know?

The main thing is that there are edge cases where encountering this error is inevitable. For those cases, we will need to prompt the user to refresh the page. We will use the code for that purpose.

Also, the [error message](https://github.com/mozilla/addons-server/blob/2a38a51dcdf86d6766ea2347b6d1f66430b690fe/src/olympia/api/authentication.py#L86) should be localized since it's displayed to end users. Until it's localized we can just rely on the string as a sort of code but that's not a long term solution.

I made the title of this issue generic because I think all failure cases should provide codes.

**Comment by kumar303** [comment]
I would be using the code for https://github.com/mozilla/addons-frontend/issues/2238 but I can use the message string until it's ready.

**Comment by diox** [comment]
Random drive-by thought I need to write down somewhere: investigate whether providing an empty implementation for `perform_authentication()` for `AddonSearchView` and similar class that don't need auth entirely improves perf or not. It makes auth lazy, which might help (or might not make a difference : maybe `authentication_classes = []` is enough to avoid hitting most of the code anyway)

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by kumar303** [comment]
This is a bit tricky to test but I verified it when I landed https://github.com/mozilla/addons-frontend/issues/2238
