### ISSUE TITLE
Error submitting extension to unlisted channel via API or website

### ISSUE THREAD

**Issue by dstillman** [mozilla/addons-server#5124]
### Describe the problem and steps to reproduce it:

I haven't been able to submit a new unlisted version of my (small) WebExtension since April 2. New listed versions work via the website.

### What happened?

I get a timeout from the API via `web-ext`. On AMO, I get "Oops! We had an error. We'll get to fixing that soon." trying to submit after successful validation (with a single warning and no errors).

From one of the many retries before `web-ext --verbose` times out:

```
{ guid: 'first_mention@danstillman.com',
     active: false,
     automated_signing: true,
     url: 'https://addons.mozilla.org/api/v3/addons/first_mention@danstillman.com/versions/1.0.5/uploads/835ec50095c34388aa22a08f944e5162/',
     files: [],
     passed_review: false,
     pk: '835ec50095c34388aa22a08f944e5162',
     processed: true,
     reviewed: false,
     valid: true,
     validation_results:
      { errors: 0,
        success: true,
        warnings: 1,
        compatibility_summary: [Object],
        ending_tier: 5,
        messages: [Object],
        detected_type: 'extension',
        notices: 0,
        metadata: [Object] },
     validation_url: 'https://addons.mozilla.org/en-US/developers/upload/835ec50095c34388aa22a08f944e5162',
     version: '1.0.5' } }
```

**Comment by dstillman** [comment]
Oh, and I should probably mention, for `web-ext` I [modified](https://github.com/mozilla/web-ext/issues/877#issuecomment-289139651) the `sign-addon` module locally to pass the `channel` parameter to the API in order to fix a bug in `web-ext` when the last-uploaded version from the website was listed. But this doesn't apply to the website attempts, obviously — for that I'm just selecting "On your own" before uploading.

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/390602/

cc @EnTeQuAk since that looks similar to the encoding issues we had with other devhub/file viewer parts in the past.

**Comment by eviljeff** [comment]
@dstillman do any of the filenames in your zip include non-ascii characters?

**Comment by dstillman** [comment]
Nope. I'm bundling XRegExp, which has all sorts of crazy characters in it, but filenames themselves are all ASCII. (And the same code, with `applications.gecko.update_url` removed from the manifest, uploads successfully on the listed channel.) Here's the ZIP if it's helpful: [first_mention-1.0.5.zip](https://github.com/mozilla/addons-server/files/906396/first_mention-1.0.5.zip)

**Comment by diox** [comment]
Mmm, I must be wrong about the sentry traceback then.

**Comment by diox** [comment]
Actual sentry traceback for the devhub upload attempt: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/390109/

Somehow the `Version` ends up with no files, or at least an empty `all_files` property.

**Comment by diox** [comment]
The code that fails was added in 16448298581c81d6c3e0cafc7cbcc3f900d803f1, which is consistent with @dstillman reporting that it started to happen on April 2nd - that code was pushed on March 30th. It affects 5 other users according to sentry, bumping priority.

**Comment by diox** [comment]
I fixed this on our `master` branch, it should land in production Thursday around 19:00 UTC.

**Comment by dstillman** [comment]
Confirmed fixed — thanks.
