### ISSUE TITLE
remove Addon.prerelease column?

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5125]
I can't tell much about how it's supposed to be used but it's apparently unused so let's get rid of it if possible.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @EnTeQuAk

**Comment by eviljeff** [comment]
@EnTeQuAk can you add some detail for a contributor to get started?

**Comment by harikishen** [comment]
I would like to take this up. @EnTeQuAk.
