### ISSUE TITLE
Trying to attempt to donate using the "contribute" button always fails

### ISSUE THREAD

**Issue by Tormen** [mozilla/addons-server#5128]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20170330221232

Steps to reproduce:

* open "about:addons"
* select addon (in my case "Add URL to Window Title")
* click "preferences"
* click "contribute" button
* which redirects (opens a new tab) for:
https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/developers?src=api
* click "contribute" button
* click into textbox to enter 5 USD as custom amount
* enter a message (or not) - I tried both
* click "Make a contribution"

I tried this within firefox 52, chrome and chromium.

To precise: There is also a 3rd case in at lest 50% of all cases you hit "Make contribution" and wait that the "Contacting Paypal" cog turned and disappeared and then NO feedback at all! No error message, nothing.

You'll find the screenshots that show all 3 cases:
 * firefox shows the "no message at all" case
 * chrome shows the "Problem with paypal" case
 * Chromium shows the "invalid date" case

But I had all 3 cases in all 3 browsers. I did screenshots of all cases. You can find them here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1354479

Actual results:

I get one of 2 error messages:
* There was an error communicating with PayPal. Please try again later.
* Invalid data.

Expected results:

allow me to contribute (very important :)).

**Comment by Tobithy** [comment]
Same issue here. Can't contribute from any browser. 

Let me do my good works please!

**Comment by diegocr** [comment]
An user of one of my add-ons just brought that to my attention:

https://addons.mozilla.org/addon/bluhell-firewall/reviews/861154/

This doesn't seems a new problem, rather a regression? it has been reported a number of times in the past:

1. https://bugzilla.mozilla.org/show_bug.cgi?id=646860

2. https://github.com/mozilla/addons-server/issues/2988

Please fix this at your earliest convenience :-)

**Comment by jvillalobos** [comment]
I'm getting this message consistently in the contribution popup:

> There was an error communicating with PayPal. Please try again later.

**Comment by marcoagpinto** [comment]
I have been getting the error too.

**Comment by marcoagpinto** [comment]
![error_communicating_paypal_20170417](https://cloud.githubusercontent.com/assets/5192600/25092467/c4b019b2-2385-11e7-8023-130827203a0b.png)

**Comment by palant** [comment]
Yes, this issue was brought to my attention by a fellow add-on developer and I could reproduce it consistently myself.

**Comment by andymckay** [comment]
@diox did you change this recently? I can consistently reproduce it too.

**Comment by diox** [comment]
No, I haven't - nobody has touched this code in years in fact. I recently [removed a task spawn by the contribute page that calculated the total number of contributions for a given add-on](https://github.com/mozilla/addons-server/issues/5069), but that's not the core paypal/contribution code.

We've had intermittent problems with Paypal for basically forever though, so this is not surprising. It usually solves itself, but apparently not this time... I'd be more than happy to[ replace all that gigantic mess by a simple donate button that does goes directly to paypal](https://github.com/mozilla/addons-server/issues/5079) with no useless interaction with AMO.

**Comment by diox** [comment]
Logs indicate that paypal started rejecting the data we send them (which would seem to confirm the problem comes from a change on their side):
`Paypal Error (580001): Invalid request: Data validation warning(line -1, col 0): String "TRUE" is not valid boolean value.`

**Comment by andymckay** [comment]
Ah sorry about that.

**Comment by muffinresearch** [comment]
@jvillalobos assuming paypal doesn't resolve the issue their end do we have a plan for what we want to do with simplifying paypal contributions - I'm wondering if ripping out the old integration is going to be the best way forward unless there's a simpler change we can make?

@diox and I were talking about it and one suggestion that came up was to think about using paypal.me links - see https://www.paypal.me/. This would also allow an optional suggested amount. The only data we'd require is a slug. It appears to be fairly well supported. https://www.paypal.me/pages/countries

**Comment by jvillalobos** [comment]
Long term I'd like to just have a URL field for contributions, so we can support more than Paypal.

If we can't fix this issue quickly, I think the short-term solution is to remove the feature for now. I can announce it in the blog so developers know why it isn't working anymore.

**Comment by andymckay** [comment]
I wrote a lot of this code and can probably remember how to set up the Paypal sandbox and see what's going on if you want to investigate the current problem. I'm all for making it simpler in the long term though :)

**Comment by muffinresearch** [comment]
Before we jump into bigger changes I think it warrants further investigation to make sure there's not some simple change that can be made to our requests to get this working. Would be good to find out if there's anthing in the error messages that helps pin down the error paypal is trying to tell us about. 

@diox would you have some time to investigate a bit further?

**Comment by diox** [comment]
Some progress: the sandbox is configured on dev. I found the [docs for the Paypal API we're using](https://developer.paypal.com/docs/classic/api/adaptive-payments/Pay_API_Operation/) so I tried fixing the error that appear in our logs, replacing `TRUE` by `true`... only to find another one: `Paypal Error (579008): You must specify only one primary receiver and at least one secondary receiver`. 

I suspect that the offending `primary` property never worked properly, was actually evaluated to `false` before, and paypal somehow started treating this as an error instead of a silently ignored warning. In the documentation it's said it should only be set for chained payments, and that's why it requires a second recipient, which we don't provide. I'm going to try removing it.

Note that [they mention](https://devblog.paypal.com/adaptive-payments-limited-release/) this API is deprecated and shouldn't be use except for select partners...

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/5255 seems to have fixed this, at least on dev. It'll land in production next Thursday around 19:00 UTC.

**Comment by vcarciu** [comment]
Verified as fixed on -dev , by making several donations. No errors from bug description were found: 
![contrib](https://cloud.githubusercontent.com/assets/1583842/25390587/a64c2fa8-29dc-11e7-9d39-943228b126dc.gif)

**Comment by Tormen** [comment]
Sounds good.
Thanks!
Can't wait next Thursday :)

Tormen
