### ISSUE TITLE
Links for an own uploaded app are broken

### ISSUE THREAD

**Issue by chickahoona** [mozilla/addons-server#5130]
### Describe the problem and steps to reproduce it:

I uploaded an app some time ago and never published it. Now I wanted to upload a new version and follow on this page:
https://addons.mozilla.org/de/developers/addons?sort=name

This link for example:
https://addons.mozilla.org/de/developers/addon/psonopw/edit

(Also all other links related to my app, e.g. https://addons.mozilla.org/de/developers/addon/psonopw/versions or https://addons.mozilla.org/de/developers/addon/psonopw/ownership have the same outcome)

### What happened?
The page (https://addons.mozilla.org/de/developers/addon/psonopw/edit) opened, yet I only see this text:

> Diese Seite wurde leider nicht gefunden.
> 
> Die Webseite oder Datei, die Sie angefordert haben, wurde auf unserem Server nicht gefunden. Es ist möglich, dass Sie auf einen Link geklickt haben, der nicht mehr aktuell ist, oder vielleicht haben Sie sich bei der Eingabe der Adresse vertippt.
> 
> Falls Sie die Adresse von Hand eingegeben haben, überprüfen Sie bitte noch einmal, ob Sie sie richtig geschrieben haben.
> Wenn Sie einem Link gefolgt sind, schreiben Sie bitte einen Fehlerbericht.Teilen Sie uns mit, woher Sie gekommen sind und wohin Sie gelangen wollten, und wir werden uns bemühen, das Problem zu beheben.
> Stattdessen möchten Sie aber vielleicht auch einfach zu einer der beliebten Seiten auf unserem Angebot surfen.
> 
> Möchten Sie eine Liste von vorgestellten Add-ons sehen?
> Möchten Sie nach Add-ons suchen? Dazu können sie die Suche aufrufen oder einfach etwas in das oben stehende Suchfeld eingeben.
> Wenn Sie lieber von vorne beginnen wollen, gehen Sie einfach zurück zur Hauptseite.

### What did you expect to happen?

Maybe the details of my app, a possibility to upload a new verion, a possibility to change some attributes (title, description,...)

### Anything else we should know?

Not that I would know

**Comment by thib3113** [comment]
same error for me .

**Comment by wagnerand** [comment]
I probably means you aren't logged in, or are logged in with the wrong account. Please double-check.

**Comment by thib3113** [comment]
@wagnerand : i'm good logged in ...

I can see the plugin's versions
![image](https://cloud.githubusercontent.com/assets/5489218/24947738/344b5f7e-1f68-11e7-88f1-f004b578da25.png)

And if I click on the version link
I can see it :
![image](https://cloud.githubusercontent.com/assets/5489218/24947784/5856b5e4-1f68-11e7-9798-2f471e1a01d0.png)

But If I click on the link for the .xpi :

![image](https://cloud.githubusercontent.com/assets/5489218/24947818/78cce9ec-1f68-11e7-9307-58a704667f50.png)

**Comment by wagnerand** [comment]
Can you please provide the devhub link to your add-on?

**Comment by thib3113** [comment]
@wagnerand oh yes .... read too quickly ...
this : https://addons.mozilla.org/fr/developers/addon/dealabs-non-officiel/edit ?

**Comment by wagnerand** [comment]
@thib3113 Ok, I can reproduce the bug, please file a new issue.

**Comment by wagnerand** [comment]
@chickahoona Please double-check that you are logged in with the right account.

**Comment by diox** [comment]
@thib3113 actually don't file a new issue, it's already known as https://github.com/mozilla/addons/issues/324 ; If you wait a bit (~ one hour IIRC) the problem should automatically fix itself. Alternatively, you can set your add-on as "visible", which works around the core of the issue.

**Comment by chickahoona** [comment]
@wagnerand Thanks for that tip. Fixed my problem.
