### ISSUE TITLE
Complete Themes with maxVersion>53 are not blocked at submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5133]
Prerequisites:
- flag "`restrict-new-legacy-submissions"` enabled

Steps to reproduce:
1. Try to submit a Complete Theme with `maxVersion` set to 55 in AMO-dev https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed

Expected results:
Complete Themes are treated like legacy add-ons, therefore blocked at submission if `maxVersion` over 53.

Actual results:
Complete Themes can be submitted even if `maxVersion` over 53.

Notes/Issues:
- tried with or without `strictCompatibility` set.
Verified on FF55(Win 7). Issue is reproducing on both -dev and -stage.
Attaching used extension:
[CT-fx55.zip](https://github.com/mozilla/addons-server/files/909442/CT-fx55.zip)

#4234

**Comment by diox** [comment]
The PRD only mentioned extensions, not themes, complete or not, I suspect because the new theme stuff isn't ready yet. @jvillalobos can you confirm it's ok?

**Comment by ValentinaPC** [comment]
Based on https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/ -"Legacy Add-ons" section, and the idea that CT are in fact legacy add-ons, I made the supposition that is should behave alike....

**Comment by jvillalobos** [comment]
We hadn't made a decision on Complete Themes when we filed #4234, and this issue is valid. Not a terribly urgent thing, since new Complete Themes should be extremely rare.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Same rules as for legacy add-ons are applied to CT as well.
Postfix screenshots fro new submissions and new version:
![ct](https://user-images.githubusercontent.com/15685960/29356284-6f042d90-827c-11e7-8779-bfb02b28969b.png)
![new-version](https://user-images.githubusercontent.com/15685960/29356285-6f07be24-827c-11e7-8b65-4474ba37dc6a.png)
