### ISSUE TITLE
Source code viewer returns error

### ISSUE THREAD

**Issue by JustOff** [mozilla/addons-server#5134]
### Describe the problem and steps to reproduce it:
Follow "View the source" link for any add-on.

### What happened?
```
Oops! Not allowed.
You tried to do something that you weren't allowed to.
```
### What did you expect to happen?
The source should be there.

**Comment by EnTeQuAk** [comment]
Please see https://mail.mozilla.org/pipermail/dev-addons/2017-April/002713.html fore more details. This is a temporary measure to fix an ongoing performance problem we had server-side and we disabled the source-viewer for public until it's properly resolved. It will be re-enabled, we just don't have a date for that yet.

**Comment by JustOff** [comment]
Since you've closed this issue (despite it still unresolved) where can I track the status of the problem to know when the source-viewer will be re-enabled?

**Comment by EnTeQuAk** [comment]
I just opened https://github.com/mozilla/addons-server/issues/5135 for it, there'll be more added to it as I finish cleaning up my notes.

**Comment by JustOff** [comment]
Thank you.
