### ISSUE TITLE
Submission is not working on AMO-stage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5136]
Steps to reproduce:
1. Try to submit an add-on in AMO-stage - https://addons.allizom.org/en-US/developers/addon/submit/upload-listed

Expected results:
User is able to submit an add-on.

Actual results:
User is blocked by a **continuous validation**.

Notes/Issues:
After 30 minutes, an error message is displayed;
Verified on FF52(Win 7). Issue is _only_ reproducing on -stage.
See screenshot for this issue:
![2017-04-10_1213](https://cloud.githubusercontent.com/assets/15685960/24854672/f867b10a-1de7-11e7-9a3d-62bd38999428.png)

**Comment by jasonthomas** [comment]
There was a issue with a rabbitmq node in our cluster on stage which caused the cluster to be sad. I've fixed the node and restart all workers. This should now be working.

**Comment by ValentinaPC** [comment]
Yes it does. Thanks!
Verified as fixed on AMO-stage FF52(Win 7).
Postfix screenshot:
![stage](https://cloud.githubusercontent.com/assets/15685960/24865570/5486aae0-1e10-11e7-8dc8-076a201dbf37.png)
