### ISSUE TITLE
amo-editors spam from activity email

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5137]
amo-editors has been getting various email from AMO replying to spam that is not setting activity mail uuids. Example (most headers removed for brevity):

```
From: amo-editors@mozilla.org
To: amo-editors@mozilla.org
Date: Mon, 10 Apr 2017 09:17:18 -0000
Message-ID: <20170410091718.4474.13718@ip-172-31-35-15.us-west-2.compute.internal>
Subject: Re: [amo-editors] Scanned image from MX-2600N

Hello,

An email was received, apparently from you. Unfortunately we couldn't process it because of:
TO: address does not contain activity email uuid (noreply@addons.mozilla.org).

Please visit https://addons.mozilla.org to leave a reply instead; alternatively if you need to send file attachments, please reply by email to amo-editors@mozilla.org.
--
Mozilla Add-ons
https://addons.mozilla.org
```

**Comment by diox** [comment]
It's controlled by the `activity-email-bouncing` waffle switch. @jvillalobos @bqbn should we disable that switch ?

**Comment by diox** [comment]
To clarify: I know the waffle switch controls exactly that and only that ; my concern is, what are the consequences of disabling those bounces ?

**Comment by jvillalobos** [comment]
This was introduced in #3555. The consequence of those bounces is that some malformed replies from legitimate developers will get dropped with no action. I suppose those are rare enough and don't warrant the volume of spam amo-editors is getting (I'm told it's 1-2 emails per minute).

I'll disable the switch for now.

**Comment by jvillalobos** [comment]
It's off now and that fixed the problem. @jasonthomas is investigating if there's a way to filter the spam emails on the socketlabs side. We can enable the switch again if we find a good way to filter those emails.
