### ISSUE TITLE
Add Manage API Keys to Dev Hub footer

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5146]
The Tools menu in the AMO header has some developer options, one which is `Manage API Keys`. It takes you to a [page](https://addons.mozilla.org/developers/addon/api/key/) where you can generate API keys to submit add-ons. The new [Developer Hub](https://addons.mozilla.org/developers/) doesn't offer that option. I think it should be added to the footer, in the `Tools` subsection (under `Compatibility Reporter`).

/cc @atsay

**Comment by atsay** [comment]
Sounds good. Do you think we ought to add a Tools menu to the header as well?

**Comment by jvillalobos** [comment]
I think it's okay to keep them at the bottom. I actually want to get rid of the Tools menu for most cases and that's why I was reviewing all the options it currently has.
