### ISSUE TITLE
Gmail account does not receive activity emails while being in "Activity Mail CC" group

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5149]
Prerequisites:
- user has a Gmail account that is added to "Activity Mail CC" group - https://addons-dev.allizom.org/en-US/admin/models/access/group/

Steps to reproduce:
1. Add a reviewer reply from Manage Status & Version page for an add-on i.e. https://addons-dev.allizom.org/en-US/editors/review/webext-activity
2. Check your Gmail account (that was added to the activity mail cc group)

Expected results:
A mail was received.

Actual results:
No mail was received.

Notes/Issues:
- same happens while approve, reject, review, etc. ;
- yahoo accounts work as expected;
- fake mail logs record correctly the emails activity;

Verified on FF52(Win 7). Issue is reproducing on AMO-dev and AMO-stage.
Screenshots for this issue:
![activity](https://cloud.githubusercontent.com/assets/15685960/24897667/7bcb5258-1ea2-11e7-84f5-4468f7596791.png)

#3726

**Comment by eviljeff** [comment]
Hopefully redundant question : it's not in your spam folder or something is it?

**Comment by ValentinaPC** [comment]
> Hopefully redundant question : it's not in your spam folder or something is it?

Nope.

**Comment by wagnerand** [comment]
@ValentinaPC could you please try again?
Several admins use their gmail account and we receive emails just fine.

Also note that need-info's are not part of activity email (yet) and thus not delivered to members of the "Activity Mail CC" group.

**Comment by ValentinaPC** [comment]
@wagnerand : "need-info's" means: the newly added "reviewer reply" and the old "request super review"?

Anyway, same happens while approving or rejecting add-ons, as I mentioned in "Notes" section.
Maybe I need to do something else with my account?
Fake mails logs are recording every activity as expected;

Other example:
I was using my admin account to add the account that has the Gmail account associated, to add another owner to an add-on... Fake mail logs recorded the change but the mail to my Gmail account was not actually sent.
 
![2017-04-26_1801](https://cloud.githubusercontent.com/assets/15685960/25441482/051b864a-2aab-11e7-9995-537777b7a46b.png)
![2017-04-26_1803](https://cloud.githubusercontent.com/assets/15685960/25441481/04e4eac2-2aab-11e7-9c14-997b9149ae58.png)

**Comment by eviljeff** [comment]
I see you're testing on -dev.  To get real emails in your inbox that email address would need to be in the  https://addons-dev.allizom.org/en-US/admin/settings#email_qa_allow_list setting (the yahoo address is; the gmail address isn't).  Someone in ops will be able to add it (ask on irc)

**Comment by eviljeff** [comment]
If this can be replicated on prod, or with the email address in `email_qa_allow_list` please re-open.

**Comment by ValentinaPC** [comment]
@eviljeff 
- I tried for the account `carcium@gmail.com`, which is in the `email_qa_allow_list` and the user of that account received a real e-mail while a developer/reviewer activity was made
- Also he did not receive any e-mail if he replied as a reviewer for an add-on (i guess this is ok, yes?)

**Comment by eviljeff** [comment]
yep, that seems as expected

**Comment by ValentinaPC** [comment]
Thanks!
