### ISSUE TITLE
Add a list of auto-approved add-ons in reviewer tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5154]
We're about to automate auto-approval of a fraction of webextensions updates (#5155), using the command in #4533. Later, we're going to relax the rules and move to full auto-approval with post-approval human review.

To do that we need to add a list of auto-approved add-ons in reviewer tools. From the [post-review implementation plan](https://docs.google.com/document/d/1rZvM2QGk8WtkNUDRvLEvrbqZ190hvHfOle4zVRllQmw/edit#), here is what needs to be done:

Add a new tab to the queues called “Post-review”:
* Have it point to `/editors/queue/post`
* Only display it for users with the `Addons:PostReview` permission.
* Add-ons that are auto-approved will appear in the post-review list. 
* Show the following columns:
  * Add-on: add-on name and version number (linking to the corresponding review page).
  * Last review: time since last manual review (in days).
  * Flags: like in current queues.
  * Exclude “Type” column.
* Sort add-ons by “Last review” by default.

**Comment by ValentinaPC** [comment]
@diox : This is not in -dev yet, yes? Thanks!

**Comment by diox** [comment]
It is, but it depends on two things:
- To see the list, you need the permission. I've given it to members of the Staff and Senior Reviewer groups
- To see add-ons in the list, some add-ons need to be auto-approved. I'm debugging issues with that as we speak (was blocked by #5214) so for the moment the list is empty on dev.

**Comment by ValentinaPC** [comment]
Thanks!
I'll give a look after the queue is populated with some add-ons.
Can you give me a notice, here?

**Comment by diox** [comment]
@ValentinaPC I populated it with some add-ons: https://addons-dev.allizom.org/en-US/editors/queue/auto_approved

Their last review column is blank, I suspect because the migration to initialize that column was a bit too restrictive. 

It'd be worth doing the following:
 - Create a basic web extension that does not use any special features (in particular: no custom csp, no permissions, no content script for all URLs)
- Approve it
- Submit a new version
- Don't manually approve it, wait for it to be auto approved (should be done every hour - I'm investigating issues regarding this, if you wait an hour and it is not approved, ping me and I'll trigger the command)
- Look if it is displayed correctly in the auto approved queue, with the last (human) review date.

**Comment by ValentinaPC** [comment]
I've added a basic WebExtension on AMO-dev: https://addons-dev.allizom.org/en-US/firefox/addon/webext-simple/
Approve it. Added a second version for it and waited. Passed over an hour. Second version is still awaiting.
Now I am pinging you :)

**Comment by diox** [comment]
Done. You can now see the add-on in the list, with the time it was last reviewed by someone.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF53(Win 7).
An Auto Approved Add-ons queue is displayed in Reviewer Tools for add-ons.
After following the STR indicated by Mat, the simple webextension appears in the Auto Approved Add-ons queue with the correct time.
Please see screenshots:
![2017-04-21_1811](https://cloud.githubusercontent.com/assets/15685960/25283945/344c4094-26be-11e7-832a-a0527263c956.png)
![2017-04-21_1812](https://cloud.githubusercontent.com/assets/15685960/25283944/344a36f0-26be-11e7-9786-03cdd0b0ee15.png)


Can we mark this verified-fixed or should we leave it like this until `auto-approve` function is working "without your action"?

**Comment by ValentinaPC** [comment]
I'll mark this verified fixed, then.
