### ISSUE TITLE
Automate auto-approval task

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5155]
This is just to add the `manage.py auto_approve` command from #4533 to the crontab. It needs to be run every hour.

**Comment by diox** [comment]
Somehow doesn't work on dev, re-opening.

**Comment by diox** [comment]
It turns out logging from crons was broken. @jasonthomas fixed it in https://github.com/mozilla-services/cloudops-deployment/pull/637 ; Keeping this issue opened because I'd like to be sure there isn't *also* a problem with the command. Now that logging is fixed it should be easier to figure that out.

**Comment by diox** [comment]
That was https://sentry.prod.mozaws.net/operations/olympia-dev/issues/394551/ , which is a network error: the signing server was not reachable from dev because crons didn't require talking to it before, so the networking wasn't set up to let them do that. This is now fixed, the command is now running normally on dev.

**Comment by ValentinaPC** [comment]
If the conditions from #4533 are fulfilled, a version of a manually reviewed add-on is auto-approved, in the range of approximately an hour.

We can mark this verified-fixed, also based on the checks from #4752.
