### ISSUE TITLE
Empty name in lightweight theme breaks layout, preview and installation

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5156]
Just noticed today that a number of lightweight themes didn't have a name. [Here's one example](https://addons.mozilla.org/addon/rainbowczechia109/), which may be fixed by the developer soon.

The listing page looks like this (notice the by-line):
<img width="729" alt="theme" src="https://cloud.githubusercontent.com/assets/62568/24923633/5ebdfd20-1eaf-11e7-9b48-076893e2579a.png">

More importantly, the theme preview and installation features don't work at all. They also don't work if the theme is on a results list (like on the recent themes or search results). No errors appear in the console.

It should be sufficient to ensure that a non-empty name is mandatory on submission and when editing a lightweight theme. I'll contact the developer to have the blank names fixed.

**Comment by eviljeff** [comment]
I can't replicate this bug - the submission and edit forms always require a name to be supplied.  Please reopen with STR.
