### ISSUE TITLE
Owncloud / Nextcloud link not working from many, many different referring sources

### ISSUE THREAD

**Issue by quinnwizard** [mozilla/addons-server#5159]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org

**Comment by quinnwizard** [comment]
Okie doke.  No problem.  Thanks for the quick reply 😃
