### ISSUE TITLE
Links for an own uploaded app are broken ( link to .xpi )

### ISSUE THREAD

**Issue by thib3113** [mozilla/addons-server#5161]
### Describe the problem and steps to reproduce it:
I've uploaded an application, in invisible mode .

The upload work good, but when I try to retrieve the signed .xpi, I've a 404 error .
### What happened?
I've a 404 link ... I've tried the link in the webui, the link at the end of the upload, and the link in the email ... They are the same, but all don't work

### What did you expect to happen?
I expect to download the xpi files

### Anything else we should know?
I can see the plugin's versions
![image](https://cloud.githubusercontent.com/assets/5489218/24947738/344b5f7e-1f68-11e7-88f1-f004b578da25.png)

And if I click on the version link
I can see it :
![image](https://cloud.githubusercontent.com/assets/5489218/24947784/5856b5e4-1f68-11e7-9798-2f471e1a01d0.png)

But If I click on the link for the .xpi :

![image](https://cloud.githubusercontent.com/assets/5489218/24947818/78cce9ec-1f68-11e7-9307-58a704667f50.png)

link to the addon : https://addons.mozilla.org/fr/developers/addon/dealabs-non-officiel/edit

**Comment by diox** [comment]
Hi, thanks for the issue. It's already known as mozilla/addons#324 ; If you wait a bit (~ one hour IIRC) the problem should automatically fix itself. Alternatively, you can set your add-on as "visible", which works around the core of the issue.

**Comment by thib3113** [comment]
https://github.com/mozilla/addons/issues/324
