### ISSUE TITLE
Reset AddonApprovalsCounter for add-ons when they are auto approved

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5164]
`AddonApprovalsCounter` is supposed to only be incremented for human reviews, and reset when an add-on is auto-approved, so that it always counts the number of human approvals the add-on had in a row.

Right now `auto_approve` does not reset it when it approves an add-on, it should.

**Comment by diox** [comment]
@wagnerand pointed out on IRC that my interpretation of the PRD was likely wrong, and I agree. Instead of maintaining a counter of the human reviews, we should maintain a counter of the auto approvals instead.

Relevant sentence from the PRD:
> When enabled 1 out of every N consecutive updates for an add-on will be auto-approved, so a counter should be kept per-add-on

It is slightly ambiguous, but it makes more sense to keep a counter of auto-approvals. The situation we want to avoid is `> N` consecutive auto approvals, the number of consecutive human reviews is not important.

**Comment by wagnerand** [comment]
Well, at least that's how I read the sentence. I might be wrong as well!

**Comment by diox** [comment]
@jvillalobos replied in the PRD comments that he had the original implementation in mind originally. Let's not change it then.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Counter is incremented every time a version of an extension is human reviewed and reset after every auto-approve.
Postfix screenshots:
![2017-04-28_1211](https://cloud.githubusercontent.com/assets/15685960/25534085/70550b02-2c3b-11e7-8463-623faf573f46.png)
![2017-04-28_1752](https://cloud.githubusercontent.com/assets/15685960/25534138/92d0edfe-2c3b-11e7-95b4-248c8e6fb208.png)
![2017-04-28_1725](https://cloud.githubusercontent.com/assets/15685960/25534084/7051e454-2c3b-11e7-9267-b011ac345cbc.png)
