### ISSUE TITLE
Where do I find API to list add-ons in collections

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#5166]
### Describe the problem and steps to reproduce it:
I had a look at https://addons-server.readthedocs.io/en/latest/topics/api/addons.html to find API for [Collections](https://addons.mozilla.org/en-Us/firefox/collections/).

### What happened?
I didn't find anything.

### What did you expect to happen?
That collections should be mentioned on the link

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by diox** [comment]
Sorry, there is no API to do that currently, and it's unlikely to happen in the near future.

**Comment by davidhedlund** [comment]
@diox Can you please open this issue again, I changed the topic.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by diox** [comment]
As mentioned this is unlikely to ever happen before we completely replace collections by a different mechanism, so keeping that issue opened would just be noise for us at the moment.

**Comment by davidhedlund** [comment]
@diox I see.

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by diox** [comment]
> mylabel:open

@davidhedlund Could you please stop adding comments like these to issues? Every time you do that, a number of people receive a github notification and/or email for something that is completely irrelevant to them. Use bookmarks or any external site to track your issues, thanks.

**Comment by davidhedlund** [comment]
@diox No thanks, I'm the add-on repository maintainer for GNU IceCat. We need to track activities that meet our goals.

**Comment by davidhedlund** [comment]
@diox Perhaps I'll be migrating the issues to Sync. I'll think about it.

**Comment by davidhedlund** [comment]
@diox I cannot use Sync, its broken in IceCat, so I reported the bug. Thank you for inspire me to have a look at it.

I have to come up with something else.

**Comment by davidhedlund** [comment]
@diox I've removed all my labels from all issues on all repositories on GitHub now.
