### ISSUE TITLE
Add-on "Require Restart"/"Compatible with Firefox 57+" labels are not RTL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5168]
Steps to reproduce:
1. Load details page for an add-on with "Require Restart"/"Compatible with Firefox 57+" label
2. Change the language to a RTL one i.e.: https://addons-dev.allizom.org/ar/firefox/addon/clearly/?src=hp-dl-featured

Expected results:
Label is RTL.

Actual results:
Label is not RTL.

Notes/Issues:
- not reproducing for search results pages.
![2017-04-12_1644](https://cloud.githubusercontent.com/assets/15685960/24960820/a4206d9e-1f9f-11e7-9500-4d33856903e0.png)

Verified on FF52(Win 7). Issue is reproducing on all AMO servers.
Example for "Compatible with Firefox 57+" label - https://addons-dev.allizom.org/ar/firefox/addon/awesome-screenshot-plus-/?src=ss
Please see screenshots:
![2017-04-12_1646](https://cloud.githubusercontent.com/assets/15685960/24961505/a71a9da6-1fa1-11e7-991d-d9eceb501b94.png)

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
@tofumatt

**Comment by kewisch** [comment]
The version number probably also needs to go on the other side, so the order would be:

LTR: Name - version [label]
RTL: [label] version - Name

**Comment by ValentinaPC** [comment]
This fix is not in -dev, Chris, can you take a look why? Thanks!

**Comment by EnTeQuAk** [comment]
Will be in a few hours, we're currently experiencing a very slow migration on -dev (well, my fault!) Once it succeeded, I'll update the issue.

**Comment by atiqueahmedziad** [comment]
@ValentinaPC This fix is now available on -dev. :smile:

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix screenshots:
![compat](https://user-images.githubusercontent.com/15685960/27429613-476f5b46-574e-11e7-982c-8a7cd3cc197f.png)
![reqres](https://user-images.githubusercontent.com/15685960/27429614-4774bb86-574e-11e7-83e2-49d487e5da7d.png)
