### ISSUE TITLE
Remove the Firefox hotfix from AMO

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#5174]
Please note that this bug can't be started until we've got the work in Firefox done, or at least https://bugzilla.mozilla.org/show_bug.cgi?id=1355937 is done.

When that happens, we can remove the Hotfix add-on off of AMO:

https://addons.mozilla.org/en-US/firefox/addon/firefox-hotfix/

This means we can also remove anything from AMO that mentions the hotfix and there's a little bit:

https://github.com/mozilla/addons-server/search?utf8=%E2%9C%93&q=hotfix&type=

Plans for this are here:

https://wiki.mozilla.org/Add-ons/HotfixRemoval

**Comment by andymckay** [comment]
Heads up, it looks like the removal of the hotfix is landing in https://bugzilla.mozilla.org/show_bug.cgi?id=1355937 in time for ESR and then AMO can think about removing the custom code for the hotfix.

**Comment by andymckay** [comment]
The patch for Android landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1260213. So when Firefox 60 is on release, which is in May 2018 according to https://wiki.mozilla.org/RapidRelease/Calendar, the hotfix code can be removed from AMO.

**Comment by diox** [comment]
Asked @sylvestre on IRC and he told me to wait until Firefox 61 just in case.
