### ISSUE TITLE
Localize resctrict legacy add-ons banner from Dev Hub

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5188]
Steps to reproduce:
1. Load add-on distribution/submission page i.e https://addons-dev.allizom.org/en-US/developers/addon/submit/distribution
2. Change the language and observe the legacy restriction banner (https://addons-dev.allizom.org/de/developers/addon/submit/distribution)

Expected results:
The banner is localized.

Actual results:
Banner is not localized.

Notes/Issues:
Verified on FF52(Win 7). Issue is reproducing all around AMO servers.
Screenshot for `de`:
![2017-04-18_1444](https://cloud.githubusercontent.com/assets/15685960/25129185/964b5d46-2445-11e7-8200-def165c4f89c.png)

**Comment by diox** [comment]
This was discussed when it was implemented and we decided not do translate it, because the text is dynamic, it's entered by admins and can be changed at runtime.
