### ISSUE TITLE
list of add-ons containing the locales hsb and dsb

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#5192]
Hi,

is it possible to get a list of add-ons containing the Sorbian locales hsb and dsb? I'd like to make Sorbian users aware of add-ons that have been translated into Upper Sorbian and/or Lower Sorbian.

Thanks in advance and regards,
Michael Wolf

**Comment by andymckay** [comment]
Sorry, we don't store that information in AMO. You might try using the API to get add-ons and examining them to see if you can find those locales: http://addons-server.readthedocs.io/en/latest/topics/api/index.html

**Comment by EnTeQuAk** [comment]
What we do store is what add-ons have translations for their `name`, `homepage_url` and `description` but that's about it. I'll agree with Andy here, it's probably up to you to fetch that information for now.
