### ISSUE TITLE
Sorting options don't list themes with corresponding details

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5201]
Steps to reproduce:
1. Load Themes homepage and select a sort option i.e. https://addons.allizom.org/en-US/firefox/themes/?sort=up-and-coming
2. Observe details for listed themes
3. Change the sort option i.e. https://addons.allizom.org/en-US/firefox/themes/?sort=rating
4. Repeat step 2

Expected results:
Different sorting details are listed together with theme name and author.

Actual results:
Same details are listed for any sort option: theme name, theme author and Daily users.

Notes/Issues:
- even if, probably the sorting is correct, additional information like date, rating stars, etc. would be useful.

Verified on FF52(Win 7). Issue is reproducing on all AMO servers.
Video for this issue:
![theme-sort](https://cloud.githubusercontent.com/assets/15685960/25181282/b6705a2a-2519-11e7-8f44-5d2a9d5ce6d2.gif)

**Comment by EnTeQuAk** [comment]
I'm going to close this since we probably won't work on this given the new addons-frontend is upcoming and under heavy development. I don't know if something like that is planned, maybe @muffinresearch or @pwalm would know or could get inspired by the idea :)
