### ISSUE TITLE
Update text in FAQs to reflect changes in review process and WebExtensions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5206]
The [FAQ](https://addons.mozilla.org/en-US/faq) and [Developer FAQ](https://addons.mozilla.org/en-US/developer_faq) are significantly outdated. This is just a quick text update to reflect recent events. We need to decide if we still need them for the new front end, or rely on MDN or the Developer Hub.

**Comment by ValentinaPC** [comment]
Verified both pages on AMO-dev FF53(Win 7)
1.  FAQ
- should we directly redirect the user while clicking on [Firefox](https://www.mozilla.org/en-US/firefox/desktop/) and [Firefox for Android](https://www.mozilla.org/en-US/firefox/android/) to the corresponding pages, or let the same page load for both links (as it happens now)?

2. Developer FAQ
- can we add the wiki page and not a redirection page for https://techbase.kde.org/Policies/Licensing_Policy ?

**Comment by jvillalobos** [comment]
Thanks, I'll fix those too.

**Comment by ValentinaPC** [comment]
I saw you logged a follow up issue for this, so we can mark this verified fixed.
