### ISSUE TITLE
A ActivityLogToken exception can happen after signing an add-on

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5214]
When signing an add-on, we send an activity email to the addon author(s). The [code](https://github.com/mozilla/addons-server/blob/d7710012aeae80a3a9bc67289c89f5a6657a5db6/src/olympia/activity/utils.py#L218-L229) does this:
```python
    for recipient in recipients:
        token, created = ActivityLogToken.objects.get_or_create(
            version=version, user=recipient)
        if not created:
            token.update(use_count=0)
        else:
            # We need .uuid to be a real UUID not just a str.
            token.reload()
            log.info('Created token with UUID %s for user: %s.' % (
                token.uuid, recipient.id))
```

I just saw the `token.reload` line fail with `ActivityLogToken matching query does not exist` on dev, when using `auto_approve` command:
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/394641/

I'm not sure what's happening (slave lag? transaction issue? cache issue ?), but it's bad, this would rollback the transaction, except the file has already been signed and moved at that point... The solution is to not `reload()` at all IMHO.

**Comment by diox** [comment]
Note that [the PR to put `auto_approve` in a crontab](#5162) was merged late on purpose ; it is scheduled for next week's push so we're safe for this week.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
