### ISSUE TITLE
"57+" compatibility link is hard to be noticed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5216]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/
2. Observe the compatibility link

Expected results:
There are no display or layout issues.

Actual results:
The link is hard to see because of its color.

Notes/Issues:
Verified on AMO-dev FF52(Win 7).
Screenshot for this issue:
![2017-04-20_1755](https://cloud.githubusercontent.com/assets/15685960/25237168/90d48dc0-25f2-11e7-8325-ddc26ae7b152.png)

Relates to #4974

**Comment by muffinresearch** [comment]
@ValentinaPC I think this was in the process of being deployed - a hard refresh and I see it:

<img width="401" alt="awesome_screenshot_plus_-____add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/25237548/dce2c750-25e2-11e7-9e4a-2a9b81772820.png">

**Comment by ValentinaPC** [comment]
Yep, I was moving to quickly 💃
