### ISSUE TITLE
No version number displayed after add-on name

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5225]
Steps to reproduce:
1. Load details page of any public add-on on AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/addon/video-downloadhelper/?src=hp-dl-mostpopular
2. Observe add-on version number

Expected results:
Last public version number is listed after add-on name.

Actual results:
The version number is not listed after add-on name.

Notes/Issues:
Verified on FF53(Win 7). Issue is only reproducing on dev.
May be related with the compatibility label changes?

Screenshot for this issue:
- dev
![vno](https://cloud.githubusercontent.com/assets/15685960/25283500/b1fb19f4-26bc-11e7-8273-a3c69b6e5242.png)

- prod
![2017-04-21_1803](https://cloud.githubusercontent.com/assets/15685960/25283600/fe08d7be-26bc-11e7-8ca3-b1c6aead3402.png)

**Comment by diox** [comment]
Yeah, that looks like something I broke while refactoring the way the labels are displayed.

**Comment by ValentinaPC** [comment]
Verified as fixed for add-ons/webextensions using AMO-dev and FF53(Win 7).
Postfix screenshot:
![2017-04-24_1405](https://cloud.githubusercontent.com/assets/15685960/25334477/6013cc20-28f7-11e7-93e5-848891ac0225.png)
