### ISSUE TITLE
Add a page endpoint to handle finding addon replacements

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5228]
A new feature [1] is being added to Firefox with a link to AMO to find alternative add-ons. 

For this feature to be implemented we need to add an endpoint as a placeholder for actual functionality. The real functionality is TBD, for now this should just be a URL that doesn't 404.

The URL will be: `/find-replacement/?guid=XXXXX`

[1] https://mozilla.invisionapp.com/share/HUAUGBGWZ#/screens/227774578

**Comment by eviljeff** [comment]
@muffinresearch is the URL fixed?
I propose `/api/v3/addons/find-replacement/xxxxxx` (drop requirement for `?guid=` too)

**Comment by muffinresearch** [comment]
> is the URL fixed? I propose /api/v3/addons/find-replacement/xxxxxx (drop requirement for ?guid= too)

It'll be worth checking with aswan, but I think this is expected to be a web-page rather than an API.

**Comment by andymckay** [comment]
about:addons is redirecting to a page on AMO, so yeah its a page. There might be an AMO API behind it, but about:addons doesn't need to know about it.

**Comment by eviljeff** [comment]
Oh! I assumed it was an API that would be consumed and shown within AOM, but okay.
