### ISSUE TITLE
Clarify max characters error message upon addon submit

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5229]
[Originally submitted to addons-frontend](https://github.com/mozilla/addons-frontend/issues/2295)

-----

### Describe the problem and steps to reproduce it:
An newly submitted addon with supporting i18n names can hit the name limit without a clear message on addons.mozilla.org.

### What happened?
The addon name i18n for Dutch is for example "Shop & winkel goedkoop bij Amazon.com zonder extra kosten" (57 characters). The English name is "Shop on Amazon.com without extra costs" (38 characters).

You put in "Shop on Amazon.com without extra costs" as a name (38 characters) and yet is says "Ensure this value has at most 50 characters (it has 57)".

### What did you expect to happen?
A message is displayed which shows the name which is too long, instead of the vague message right now.

### Anything else we should know?
Screenshot from https://discourse.mozilla-community.org/t/cannot-submit-because-of-the-limitation-for-name/14096/6
![](https://discourse-paas-production-content.s3.amazonaws.com/original/2X/8/864b083e5f6f2a7183b7420793923461502ff0fb.png)

**Comment by EnTeQuAk** [comment]
This will certainly go away once we improved our metadata handling https://github.com/mozilla/addons-server/issues/7825 and only allow changing this via updating things in the manifest.

I'll leave this open though since a proper error message has to be implemented there too.

**Comment by Smile4ever** [comment]
Keep it open

**Comment by Smile4ever** [comment]
Has this been addressed?

**Comment by Smile4ever** [comment]
Keep it open and look at #7825

**Comment by Smile4ever** [comment]
Please reopen
