### ISSUE TITLE
Broken character escaping on frontpage

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons-server#5230]
![untitled-1](https://cloud.githubusercontent.com/assets/6733770/25289686/11274cde-26a1-11e7-842e-a2f4d3ebdfce.png)

`<p class="desc vtruncate" data-oldtext="Point &amp;amp;amp; click to forbid&amp;#x2F;allow any class of requests made by your browser. Use it to block scripts, iframes, ads, facebook, etc.">Point &amp;amp; click to forbid/allow any class of requests made by your brows…</p>`

**Comment by ValentinaPC** [comment]
Verified this in AMO-dev FF53(Win 7).
Tried with different characters.
Postfix screenshot:
![2017-05-02_1210](https://cloud.githubusercontent.com/assets/15685960/25611593/5cf3b584-2f30-11e7-896d-a8fd63009a82.png)
