### ISSUE TITLE
What happened to the Color Contrast Analyzer Firefox Extension? I tried to download it from the CCA site and Mozilla didn't find it.

### ISSUE THREAD

**Issue by IanKHall** [mozilla/addons-server#5235]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by IanKHall** [comment]
https://addons.mozilla.org/en-US/firefox/addon/7313/ documents the error.
Here's where I expected to download the FF extension from:
http://juicystudio.com/article/colour-contrast-analyser-firefox-extension.php

**Comment by jvillalobos** [comment]
That add-on hasn't been updated in over 7 years and is no longer active. That's why the listing page is not available. I suggest you contact the developer about this.
