### ISSUE TITLE
Distance between "Permissions" link and "Add to Firefox" button is too little in RTL

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5241]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/fa/firefox/addon/unparsablepermissions/?src=cb-dl-updated

Expected results:
Distance between "Permissions" link and "Add to Firefox" button is the same like for non RTL languages

Actual results:
Distance between "Permissions" link and "Add to Firefox" button is too little in RTL

Please see video for this bug : 
![rtldistance](https://cloud.githubusercontent.com/assets/1583842/25342721/79ad25a0-2915-11e7-9eeb-35dd96d1a12f.gif)

**Comment by eviljeff** [comment]
mentor @eviljeff (me)
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

This is likely just a simple css fix.  I can provide some more context.

**Comment by vcarciu** [comment]
Verified as fixed : 
![distance](https://cloud.githubusercontent.com/assets/1583842/25991775/31860bba-370d-11e7-9386-403fb6588173.png)
