### ISSUE TITLE
Checking admin "Override failed validation" option blocks submission with a 500 error page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5257]
Prerequisites:
User is logged with an admin account.

Steps to reproduce:
1. Select to submit an add-on that fails validation due to a reason that allows you to "Override failed validation" (example: legacy add-on) using AMO-dev  https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed (listed or unlisted)
2. Check "Override failed validation" and click "Continue/Sign Add-on" button

Expected results:
Submission can be continued.

Actual results:
Submission is blocked by an "Oops..." page.

Notes/Issues:
Issue is only reproducing on AMO-dev.
Verified on FF53(Win 7).
Video for this issue: 
![override](https://cloud.githubusercontent.com/assets/15685960/25387960/22664874-29d5-11e7-9aa5-b7be06b3f991.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/395343/

That's caused by the fix for #3572

**Comment by ValentinaPC** [comment]
@eviljeff : what should we do if the same "500 error page" is displayed for other cases when the user want to "Override failed validation", like in the next video?
![double](https://cloud.githubusercontent.com/assets/15685960/25433276/78333e54-2a90-11e7-9efe-e82686aae52c.gif)

**Comment by eviljeff** [comment]
what are the 'other cases'?

**Comment by ValentinaPC** [comment]
The case from my example is for the error "Found duplicate target application elements", as you can see in the above video. I said "other cases" because maybe there are more.
If is just only this one, then I am sorry for misleading you.

**Comment by diox** [comment]
So, your original problem when overriding failed validation came from a regression in #3572, but *now* it's directly tied to duplicate targetapplication elements, so #5172 should be re-opened for this specific edge case.

**Comment by ValentinaPC** [comment]
I will do as you tell me. :)
I thought is related to this because, here we are dealing with "Override failed validation".
Thanks, Mat.

**Comment by ValentinaPC** [comment]
Verified as fixed using AMO-dev FF53(Win 7) for the case regressed from #3572.
Postfix video:
![overr](https://cloud.githubusercontent.com/assets/15685960/25435556/08fd2302-2a99-11e7-8fa3-2b76d04994b8.gif)
