### ISSUE TITLE
Add UserProfile API public view methods

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5261]
Supports user profile pages on addons-frontend.

First step - API(s) to allow publicly viewable information to be shown ([e.g.](https://addons.mozilla.org/en-US/firefox/user/eviljeff/))

PRD [spec](https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit?pli=1#heading=h.t8mr6z8hqji)

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
