### ISSUE TITLE
Add UserProfile edit API to self-modify AMO profile information

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5263]
Supports user profile pages on addons-frontend.

We need to add API methods to support editing user profile data, so a page similar to https://addons.mozilla.org/en-US/firefox/users/edit can be created on front-end.

PRD [spec](https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit?pli=1#heading=h.5cheild9uc3u)

see #5261 for view API

**Comment by eviljeff** [comment]
The current 'admin' manage edit profile has some overlap with #3138

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
