### ISSUE TITLE
drop user profile localisation

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5264]
We allow the bio to be localised currently, and a handful of users (~100) do this.  We're going to drop this minor feature because the addons-frontend won't support this.

**Comment by eviljeff** [comment]
https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit?pli=1#heading=h.5cheild9uc3u for PRD mentioning dropping default locale setting

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by eviljeff** [comment]
STR:
look at some user profiles with biography sections, preferably old profiles for high profile users e.g. the developers of Adblock Plus.
See the biography isn't broken.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
- checked the biography section on several developers (Wladimir Palant, Giorgio Maone, Anthony Lieuallen)
- checked for different languages
- checked HTML tags
- checked updates on my own profile

Biography looks all good.
Postfix screenshots:
![details](https://cloud.githubusercontent.com/assets/15685960/26354638/2374a544-3fce-11e7-8035-804a48f9fde0.png)
![mine](https://cloud.githubusercontent.com/assets/15685960/26354639/269e3956-3fce-11e7-95ed-e0239d3ac3db.png)
