### ISSUE TITLE
Review for deleted addon is still displayed on user page

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons-server#5266]
### Describe the problem and steps to reproduce it:
Open https://addons.mozilla.org/firefox/user/onemen/

### What happened?
You can see the review this user left for an addon that has been deleted by its developer.

**Comment by EnTeQuAk** [comment]
This is definetely because we only soft-delete an add-on, reviews themselves are also only soft-deleted so maybe there's a bug in between that doesn't make tihs work properly.

**Comment by dessant** [comment]
I'm also seeing this with a deleted add-on version, no reviews have been removed or hidden.

**Comment by eviljeff** [comment]
Closing this in favour of #6378 because we should fix it in the API that new frontend pages will use to display reviews.
