### ISSUE TITLE
No error message while trying to delete an account if no "e-mail format" is used

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5268]
Steps to reproduce:
1. Try to delete an account by entering some text in the Email field from delete user page - https://addons.allizom.org/en-US/firefox/users/delete - that does not have an e-mail format

Expected results:
User should be informed that the text entered is not an e-mail.

Actual results:
No message is displayed.

Notes/Issues:
- if the e-mail format is used text@text.text then a message is displayed.

Verified as fixed in AMO-dev FF53(Win 7).
Video for this issue:
![email](https://cloud.githubusercontent.com/assets/15685960/25435663/73b0ba10-2a99-11e7-9fc8-73434a505d00.gif)

**Comment by EnTeQuAk** [comment]
I'm closing this, this is a browser-specific problem imho. For example, it works for me (see attached screenshots).

This is related to us using `type="email"` in the input field, which is a good thing.

![screenshot from 2017-04-27 17-09-49](https://cloud.githubusercontent.com/assets/139033/25478798/b049092c-2b6c-11e7-83d7-7c72eb780246.png)
![screenshot from 2017-04-27 17-10-27](https://cloud.githubusercontent.com/assets/139033/25478799/b04c2b20-2b6c-11e7-8e92-26b3aec5ef0d.png)
