### ISSUE TITLE
Display recent user ratings and abuse reports in review page (for users with postreview permission)

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5272]
In the review page, if the reviewer has the `Addons:PostReview` permission, display recent user ratings and abuse reports (for the add-on or the developers, if there are any reports), with links to the full lists, below the add-on metadata and right above “More about this add-on”.

**Comment by diox** [comment]
Note: because we didn't have a page for user abuse reports, I've splitted this issue in two, creating #5310 ; this issue is now only about user reviews and add-on abuse reports, not developer abuse reports.

**Comment by jvillalobos** [comment]
Per a suggestion in the PRD, can we filter the user reviews so we only get the ones with 3 stars or less?

**Comment by diox** [comment]
Sure.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7).
This is the way it looks right now:
![userabuse-report](https://cloud.githubusercontent.com/assets/15685960/25664854/905e0b1e-3024-11e7-8003-4618c50d7c82.png)

Do we wanna list the explicit reviews and reports? or should we only list the links with redirection?

**Comment by diox** [comment]
The PRD asked for the lists of recent reports/reviews, so I've paginated the list to 5 + gave the full link (which is already present in the top part, but I don't think it hurts to have it twice :)

And yeah, only reviews of 3 stars and under with a text should show up in the "Bad User Reviews" list.

**Comment by ValentinaPC** [comment]
> I've paginated the list to 5

You answered to my next question with this :) So we list 5 of the reviews.
We are not interested in listing "good" reviews?

**Comment by diox** [comment]
No, only the "bad" ones: it's to help reviewers figure out if an auto-approved add-on is suspicious or not, so good reviews are not necessary.

**Comment by ValentinaPC** [comment]
The number limit applies for abuse reports also, I think this is also intended.

Marking this verified fixed.
