### ISSUE TITLE
Add ability to store reviewer approval for auto-approved add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5273]
We want reviewers with `Addons:PostReview` permission to be able to confirm approval of an auto-approved add-on. 

This means that, on the review page, for auto-approved add-ons, if the reviewer has the Addons:PostReview permission, the approve resolution should be available, and shouldn’t display the form for comments and canned responses. Instead, it should only show the Save button. Approving an add-on doesn’t send any information to the developer or change its status. It only records the approval so its time of last approval is used to prioritize it in the future.

**Comment by diox** [comment]
From comments in the implementation plan, the reason why storing this info is useful:
> The size of code changes would be calculated comparing the latest version of the add-on with the last version that was manually approved. So we still need to keep a record of manual approvals. It will also be necessary so reviewers can see it in the review history.

For the last part, the review history, just using activity log should be enough. For the first part, I'm debating different solutions:
- Store manual approval ("confirmation") in a new field in `AutoApprovalSummary`
- Delete the `AutoApprovalSummary` instance when a reviewer manually approves that version
- Add a new model to store those manual approvals

**Comment by vcarciu** [comment]
Verified as fixed : 
![confirm approval](https://cloud.githubusercontent.com/assets/1583842/26154103/d9d0c258-3b16-11e7-93ef-17047560fe00.gif)
