### ISSUE TITLE
Stop sending email to developers when requesting super-review of an auto-approved add-on

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5274]
For auto-approved add-ons, the request superreview option should still be available, but it should not send an e-mail to the developer.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7) in Admin Tools - Fake mails log page.
The only mail sent is to "`amo-editors+somethingbad@mozilla.org`" and not to the developer.
Postfix screenshot:
![2017-05-12_1119](https://cloud.githubusercontent.com/assets/15685960/25989581/64095e46-3705-11e7-96f8-0a75ec07f1fc.png)
