### ISSUE TITLE
Implement rejection of auto-approved add-ons by human reviewers

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5275]
Rreviewers with `Addons:PostReview` permission should be able to reject an auto-approved add-on.

The *Reject* action should, in that case, include a way to select which versions of the add-on are affected by the rejection. All of those versions should be disabled once the review is saved, and should be listed in the email sent to the developer.

**Comment by diox** [comment]
@jvillalobos can you provide the email template ? (mocks shouldn't be necessary, I can come up with the UI, but you're welcome to add some too if you have something specific in mind)

**Comment by jvillalobos** [comment]
[Here's what I'm thinking for the rejection email](https://docs.google.com/document/d/1so1dLqu5qtYhdcffExtSKE2NO99f1MvKDZKVIk3tAjo/edit#).
/cc @atsay @wagnerand @kewisch for feedback.

**Comment by wagnerand** [comment]
Lgtm.

**Comment by kewisch** [comment]
lgtm too. Is there a separate email they get if they fail to address the issues for multiple versions and we disable the add-on completely?

**Comment by jvillalobos** [comment]
Not at the moment. We only have one reject resolution. We can consider expanding that in Q3 if it turns out we're doing this often.

**Comment by diox** [comment]
@jvillalobos what subject should I use for the email ? For the basic reject action it's `Mozilla Add-ons: %s %s didn't pass review` and we insert the add-on name and version number. (I don't think it will be practical to use all affected version numbers here - and since we already sent an approval email, it'd need to be different...)

**Comment by jvillalobos** [comment]
`Mozilla Add-ons: One or more versions of %s didn't pass review`

**Comment by ValentinaPC** [comment]
@diox - Seems like the the option to reject multiple auto-approved versions is not yet available. Is it because this is not yet in dev or because you postpone it to Q3?
Here is the screenshot:
![nomultiple](https://cloud.githubusercontent.com/assets/15685960/26359852/38fea20a-3fdf-11e7-9901-4547c1c4b2aa.png)

**Comment by diox** [comment]
Dev is having deploy issues at the moment.

**Comment by ValentinaPC** [comment]
Thanks for info.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7), and observed the following:

1. all extensions have the "Reject Multiple Versions" tab their review page
![rejectm](https://cloud.githubusercontent.com/assets/15685960/26403104/9c673274-4095-11e7-8c2e-80fcb96333be.png)

2. extensions with only an awaiting version don't have anything in the "Reject Multiple Versions" 
![rejsimple](https://cloud.githubusercontent.com/assets/15685960/26403203/146ce124-4096-11e7-8630-e318b9177df2.png)
![rejm](https://cloud.githubusercontent.com/assets/15685960/26403215/1991fb12-4096-11e7-9c61-24df42421855.png)

3. the last awaiting version of an add-on is not listed in the "Reject Multiple Versions" tab
4. for extensions that have multiple files for the same version, in the "Reject Multiple Versions" tab same version will be listed multiple times
5. an extension with all versions rejected, still has the "Reject Multiple Versions" unusable option
6. an activity mail is generated as expected.
![activity](https://cloud.githubusercontent.com/assets/15685960/26404687/72a8bf10-409b-11e7-992d-b3e4f2d0794a.png)


@diox: please let me know which are intended and which aren't and if separate tracking is required. Thanks!

**Comment by diox** [comment]
1. Works as intended
2. Works as intended, but may need to be clarified : it's only for public versions, I just could not name the action "Reject Multiple Public Versions" because it would have been too long. I'll look into modifying the description to make that clearer.
3. See above.
4. That's a minor issue, but yeah, it should be fixed.
5. Minor issue we don't really care about.
6. Works as intended

@ValentinaPC I'll reuse #5008 which was just filed, to fix the issues 2 and 4.

**Comment by ValentinaPC** [comment]
@diox : #5508 instead of #5008, I suppose :P

Because a separate issue was logged to track some of the issues here, we can mark this verified-fixed.

**Comment by diox** [comment]
Right :)
