### ISSUE TITLE
Use Firefox schemas for manifest validation

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#5276]
We're importing Firefox schemas in addons-linter and they're going to be used for validating the manifest file.

This will need some extra QA to verify that manifest files are still validated correctly after the change.

**Comment by mstriemer** [comment]
This was fixed by #5247.

**Comment by ValentinaPC** [comment]
I've tried submission for a bunch of different files (webextensions, legacy add-ons, or other add-ons, beta versions, etc.) for both listed and unlisted distribution and validation worked as expected.

We can mark this verified fixed.
