### ISSUE TITLE
Add locked/has_info_request/has_admin_review flags to AutoApprovalSummary

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5292]
Currently, when `auto_approve` runs, it skips add-ons that are locked by other reviewers, or have info requests pending, or are flagged for admin reviews. However, it doesn't store info about add-ons it skips that way like it does for other criteria - they are just skipped, and we lose the info explaining why they were skippped.

Let's stop doing that. Consider those 3 things are regular criteria to be stored on `AutoApprovalSummary` model and part of the verdict. It means that re-calculating verdict for a given version might give different results every time, but that's fine, it's already the case for the daily users criteria for instance.

**Comment by ValentinaPC** [comment]
What should be checked here extra beside what was checked in #5294 and #5337 ?
Many thanks!

**Comment by diox** [comment]
You can test this change with updates of add-ons that are flagged for admin review, locked by a reviewer (keep the review page opened, wait till auto-approve script runs, refresh the page) or have an info requests.

Previously, those add-ons would be skipped by auto-approval, and you'd see "no attempt recorded yet" in auto approval summary info, which was false (they were just skipped). Now, you should see the real reason they were not auto-approved.

**Comment by ValentinaPC** [comment]
Yes, I've checked that in #5337 .
Verified as fixed on AMO-dev FF53(Win 7)
Postfix screenshots:
![not_run_yet](https://cloud.githubusercontent.com/assets/15685960/25793800/d3a84bb8-33d6-11e7-8531-58d40517c1b2.png)
![2017-05-08_1223](https://cloud.githubusercontent.com/assets/15685960/25798285/3b0d1cb8-33e9-11e7-9983-c63cfdc54237.png)
