### ISSUE TITLE
Display auto approval summary info in review page for users with Addons:PostReview

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5294]
In the add-on review page, if the user has `Addons:PostReview` permission, display auto approval summary for each version that could have been auto-approved (i.e. is a unreviewed, listed webextension).

This is mostly a bonus feature to help QA and devs debug issues with auto-approvals, but could be useful for human reviewers as well.

**Comment by vcarciu** [comment]
If the webextension is not candidate for auto-approval(CSP linter warning displayed at submission) , we should not display the auto approval summary. 
This is the webextension with CSP linter warning displayed at submission : https://addons-dev.allizom.org/en-US/firefox/addon/jeckmanel/ . 
Please see screenshot with the auto approval summary section : 
![autoapproval](https://cloud.githubusercontent.com/assets/1583842/25628050/86230c38-2f6d-11e7-8cff-b4dd9abb8cd6.png)

**Comment by diox** [comment]
We *should* display it. It's mean to debug why a version has not been auto-approved...

**Comment by diox** [comment]
What's expected here:
- After a little while (less than an hour), if nobody is locking the review page (you are, at the moment I'm writing this), auto approves script runs and tries to auto-approve this version
- The script notices the file is using a custom CSP, and therefore marks the version as *not* auto-approves, recording the reason
- The review page will display those reasons in the summary of the version *if it's still awaiting review*. The intent is to help debug why a particular version has not been auto-approved.

Now, because of a limitation that I'll fix in #5292, the fact that a reviewer has a lock on this page means auto-approve will skip the version entirely, not recording anything. But otherwise, you'd see "Uses a custom CSP" in there, if no human manually approves it.

**Comment by vcarciu** [comment]
Verified as fixed then . This is what I can see when no human manually approves the webextension with cusom CSP : 
![customcsp](https://cloud.githubusercontent.com/assets/1583842/25665778/4697c986-3027-11e7-822e-abcd857b2c58.png)

Also, if there are not enough human approvals : 
![autoapprovalsummary](https://cloud.githubusercontent.com/assets/1583842/25665830/6a112060-3027-11e7-8b1c-c7085d23b911.png)

If the auto approval was not performed(reviewer tools opened or less than an hour) : 
![autoapproval](https://cloud.githubusercontent.com/assets/1583842/25665873/884648c6-3027-11e7-87b2-7747248425c6.png)
