### ISSUE TITLE
Provide a filter param to hide reviews without a body

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#5297]
The [list reviews](http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#list-reviews) API will hide reviews without a body (i.e. star ratings) by default as of https://github.com/mozilla/addons-server/pull/5227#issuecomment-296651852

As discussed on IRC:

1. The API should not exclude reviews without a body by default (https://github.com/mozilla/addons-server/commit/b098079c45f#diff-e765b320da36dae52a4fb1bf0d08ada9R399). 
2. The endpoint should accept a new filter param that can be used to show/hide star reviews without a body. Perhaps it should be called `exclude_textless_reviews=True` but maybe there is a better name.

**Comment by kumar303** [comment]
> The API should not exclude reviews without a body by default.

By doing this, the legacy frontend will need to explicitly hide reviews without a body

**Comment by eviljeff** [comment]
for the front-end work, #4966 was the original issue.
https://github.com/mozilla/addons-server/issues/4966#issue-214820648 mentions users's own reviews should be shown if they're empty;
https://github.com/mozilla/addons-server/issues/4966#issuecomment-287883300 mentions admins should be able to see non-empty reviews too for all users.  I'm not sure if you want a generic toggle, or just use the profile details you know to request without the filter for admin users.  The API doesn't check `addons:edit` now that the default is to show empty reviews for everyone.
