### ISSUE TITLE
Give reviewers some points for info requests and admin flags

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#5302]
Not my idea, remembered this bug when it was first filed, was curious what happened to it, but it was left to rot in the graveyard, so reposting here (1125326)

>jorgev - 2015-01-23:
> We give reviewers points for finishing reviews, but we don't give them any points for info requests or admin flags. Since these info requests generally involve some work on their part, we should give them at least a little credit for them.
> 
> My suggestion is to give them 20 points for either, regardless of the type of review being performed (see https://wiki.mozilla.org/Add-ons/Reviewers/Points_and_Incentives for current points).

**Comment by rctgamer3** [comment]
I'm not sure how needinfo should be handled nowadays. Needinfo is still there, but marked as developer replies back and forth.

**Comment by wagnerand** [comment]
I'm 👎  on that.

**Comment by jvillalobos** [comment]
We need to re-evaluate all the points system when we move to post-reviews, and I don't think we'll spend any time changing the pre-review points system. We'll consider this request for post-reviews, but closing this bug since we won't fix it.
