### ISSUE TITLE
Make shield study 11 page translatable

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5304]
Quoting @squarewave in #5298:
> This page will need to be translated since we are targeting several locales.

Though the PR has already been merged, opening this issue to track this in the milestone.

**Comment by muffinresearch** [comment]
Just awaiting incoming translations.

**Comment by muffinresearch** [comment]
Translations handled as cherry-picks see https://public.etherpad-mozilla.org/p/amo-2017.05.04
