### ISSUE TITLE
Auto-approval counter is not working as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5309]
Steps to reproduce:
1. Submit an add-on that meets the criteria from #4533 and manually approve it i.e. https://addons-dev.allizom.org/en-US/developers/addon/webext-simple-wow/versions 
2. Add a new version for this add-on (and wait for auto-approve)
3. Meanwhile go to add-on review page and see the auto-approval counter

Expected results:
Counter is "0".

Actual results:
Counter is "1".

Notes/Issues:
- Friday this worked as expected. (#4752)

Verified on AMO-dev FF53(Win 7). Reproducing on dev and stage.
Screenshot for this issue:
![automatic_rev_counter](https://cloud.githubusercontent.com/assets/15685960/25622897/9f84a7fe-2f5e-11e7-94e1-3803fa2fb600.png)

**Comment by diox** [comment]
It seems to me the counter is still 1 and not 0 because it has not been auto-approved yet.

**Comment by ValentinaPC** [comment]
Hm...I thought it should start with 0, because it should count the number of approvals after first auto review, as the name says "Approvals since last automatic review", in this case 0 approvals... or did I got it wrong? :(

**Comment by diox** [comment]
It should really say "Approvals since last automatic review or the beginning of the life of the add-on, whichever comes first" but that's too long :) Alternatively you can think of it as "Total number human approvals, except it's reset when the add-on is automatically approved".
