### ISSUE TITLE
Expose permissions on the review page

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5311]
To aid reviewers in making quick decisions on the approval status of an add-on, we would like to expose the permissions an add-on has in the reviewer tools.

The permissions are per-file, so we need to include them down in the files section:
![image](https://cloud.githubusercontent.com/assets/607198/25624805/e15065aa-2f5a-11e7-9568-f87dc3044cc3.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Postfix screenshot:
![2017-05-03_1136](https://cloud.githubusercontent.com/assets/15685960/25654238/fd409142-2ff8-11e7-9ae1-ac0f5db20910.png)

**Comment by ValentinaPC** [comment]
@kewisch : I forgot something - for add-ons with no permissions should we list "Permissions: None" in review page? Thanks!

**Comment by wagnerand** [comment]
@ValentinaPC We do list "Permissions: None" for **webextensions** that don't require any permissions. We don't show the permissions block at all for legacy add-ons.
