### ISSUE TITLE
500 error page for "Listed Review Page" link

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5312]
Steps to reproduce:
1. Add a new version that qualifies for auto approve for a public add-on that has reviews under 10k in AMO-dev i.e. https://addons-dev.allizom.org/en-US/developers/addon/bidninja/edit
2. Click on "Listed Review Page" link (https://addons-dev.allizom.org/en-US/editors/review/bidninja)

Expected results:
Review page for that add-on is loaded.

Actual results:
A 500 error page is loaded.

Notes/Issues:
- I din not managed to reproduce this on stage.
- I did not manage to reproduce this with other add-on on dev.

Verified on AMO-dev FF53(Win 7).
Video for this issue:
![500](https://cloud.githubusercontent.com/assets/15685960/25625268/cb1de0fa-2f64-11e7-9f5c-dbf30c4dfb07.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/459866/

The tracekback seems to imply it's because there is a deleted version on that add-on - we do some weird hacks in the review page in that case.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Review page is available for add-ons with hard deleted versions.
Postfix video:
![review](https://cloud.githubusercontent.com/assets/15685960/25652853/d2c7e006-2ff2-11e7-901e-35b2ad0737d7.gif)
