### ISSUE TITLE
Theme description from edit listing is not localized

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5319]
Steps to reproduce:
1. Change language in AMO-stage homepage i.e. https://addons.allizom.org/es/firefox/
2. Submit a theme with description https://addons.allizom.org/es/developers/theme/submit
3. Go to Edit listing page for the submitted theme

Expected results:
Description is displayed.

Actual results:
Theme has no description.

Notes/Issues:
- not seeing any description in edit listing page for a theme, even if you previously added one, can be a bit confusing;

Verified on AMO-stage FF53(Win 7). Issue is reproducing on all AMO servers.
Video for this issue:
![es](https://cloud.githubusercontent.com/assets/15685960/25660519/4eec6644-3015-11e7-9f75-fbdc976629ff.gif)

**Comment by diox** [comment]
Wontfixing this because lightweight themes are about to be replaced with static themes, which behave more like regular add-ons.
