### ISSUE TITLE
Collector's notes are not RTL

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5322]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/fa/firefox/collections/esorhjy/playpc/

Expected results:
Collector's note is RTL

Actual results: 
Collector's notes is not RTL

Please see screenshot for this bug : 
![colnot](https://cloud.githubusercontent.com/assets/1583842/25667954/d1483a2e-302d-11e7-8eb5-9a2a694a43b7.png)

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @tofumatt

**Comment by harikishen** [comment]
i would like to take this up.

**Comment by harikishen** [comment]
@tofumatt is this concerned with modifying the templates or modifying the styling ???

**Comment by harry-7** [comment]
@vcarciu  is this still open ? If yes what part of the work is left?

**Comment by vcarciu** [comment]
@harry-7 : Yes , the "Collector's Note" text should be in the right side of collector's note section

**Comment by harry-7** [comment]
@vcarciu  I am unable to reproduce the bug. Also please let me know how to check if my code works correctly ..

**Comment by harry-7** [comment]
@tofumatt with the current version of code I can the "Collector's Note" as rtl only. I am trying on my local development server. Am I missing something ?

**Comment by tofumatt** [comment]
This page is being replaced in the new front-end and I don't think this is a good contributor bug as the page has been replaced. Sorry @harry-7 but I think you should find another bug to work on. Sorry no one told you earlier; I just saw this.
