### ISSUE TITLE
Remove Mobile as an application option in version edit page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5324]
STR:
1. Go to an add-on management page
2. Go to the Status & Versions page
3. Click on a version
4. Under Compatibility, click on Add Another Application

Result:
You'll see "Firefox for Android" and "Mobile" as separate, confusing options.

"Mobile" corresponds to an old platform we no longer support. We should at least remove that option from the Add Another Application list. Removing it as a valid application altogether is also one way to resolve this, but it's probably much more work.

**Comment by diox** [comment]
Possibly related (I don't remember how everything is tangled together) https://github.com/mozilla/addons-server/issues/3360

**Comment by vcarciu** [comment]
Verified as fixed : 
![removemobile](https://cloud.githubusercontent.com/assets/1583842/25862202/eed7de3e-34ef-11e7-900a-a1e80b5be0f0.png)
