### ISSUE TITLE
Overlapped words in promo banner

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#5329]
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/en-US/firefox/ and navigate in the promo banner.

### What happened?
Words are overlapped in the promo banner for some Add-ons.

### What did you expect to happen?
Words to not be overlapped in the promo banner for some Add-ons.

### Anything else we should know?
Verified on FF55.0a1 and FF53.0 under Wind 7 64-bit in AMO prod server.
Please see the video for this issue:
![overlapped](https://cloud.githubusercontent.com/assets/15885467/25694026/1a5f72e0-30b5-11e7-8a07-24371a03e854.gif)

**Comment by muffinresearch** [comment]
Looks like a subtle difference in font sizes are causing this - it doesn't happen for me on OSX.

**Comment by muffinresearch** [comment]
Doesn't happen on windows 10 either.

<img width="1036" alt="screenshot_12_05_2017__19_11" src="https://cloud.githubusercontent.com/assets/1514/26010960/f437a5e0-3746-11e7-913b-0a36124891ff.png">

**Comment by cosminbadescuSV** [comment]
I can confirm that this issue is verified as fixed on FF55.0a1 and FF53.0 under Wind 7 64-bit in AMO prod server, please see the video below:
![overlappedfix](https://cloud.githubusercontent.com/assets/15885467/26047413/c7dbca28-395b-11e7-8ef5-37b9343353ff.gif)
