### ISSUE TITLE
New Add-ons review percentage is not calculated correctly

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5331]
Steps to reproduce:
1. Load Reviewer Tools homepage https://addons.allizom.org/en-US/editors/
2. Hover over New Add-ons - Current waiting times - percentage bar

Expected results:
Add-on reviewing percentage is calculated correctly.

Actual results:
Add-on reviewing percentage sum is incorrect.

Notes/Issues:
- review add-on percentage is calculated correct for "Updates" section.

Verified on FF53(Win 7). Issue is reproducing on both dev and stage.
Screenshots for this issue:
New-Addons (0%+0%+99%<>100%)
![new-addons](https://cloud.githubusercontent.com/assets/15685960/25699611/9a34b3b0-30cc-11e7-8cbc-d1253a03fbda.png)

Updates(correct) (1%+99%=100%)
![updates](https://cloud.githubusercontent.com/assets/15685960/25699617/9e74de1e-30cc-11e7-8448-2be2fa6e12d9.png)

**Comment by eviljeff** [comment]
It's just rounding
2/644 = 0.31% (rounded to 0%)
3/644 = 0.47% (rounded to 0%)
639/644 = 99.22% (rounded to 99%)
There isn't an easy fix - if we round up <1 then it'd be 1% + 1% + 99% and there would be other cases where it'd be like 1.49% + 1.49% + 99.02% that'd still be wrong.
