### ISSUE TITLE
Make the admin environment view useful

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5334]
STR:
* Visit https://addons-dev.allizom.org/en-US/admin/env as an admin

Expected results:
- A useful page detailing the server environment

Actual results:
- A blank page with just `<WSGIRequest: GET '/en-US/admin/env'>`.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7)
Postfix screenshot:
![env](https://cloud.githubusercontent.com/assets/15685960/25738677/1786f4e4-3187-11e7-9ce3-f723a3fba417.png)
