### ISSUE TITLE
Be explicit when a submission failed auto-approval 

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5337]
```
<mat>  (small caveat: currently add-ons that are locked by a reviewer, or have an info request, or are flagged for admin review, are skipped entirely, and thus you might see this message even though the script *has* run ; that will be fixed next week)
<mat> next week, for this add-on, you'd see: "Auto Approval Summary: Is flagged for admin review." (maybe "Is locked by a reviewer" as well, depending on whether it was locked at the time the script ran)
<TheOne> mat: can we be more explicit like "Not approved because ... "
<mat> TheOne: yes; file me an issue
```

Thanks! 😄

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF53(Win 7).
There are 2 cases when we do not specific why the add-ons it was not auto-approved:
- embedded webextensions (example: https://addons-dev.allizom.org/en-US/developers/addon/embedded-webextension-2/edit)
- add-on flagged by admin during submission (example: https://addons-dev.allizom.org/en-US/editors/review/multiple-)
 
What should we do with these?

The rest of cases display a reason of not auto-approve.
Please see screenshots:
![csp](https://cloud.githubusercontent.com/assets/15685960/25748217/11723ace-31b3-11e7-88b7-6b96cc859a4b.png)
![flag](https://cloud.githubusercontent.com/assets/15685960/25748218/11742b86-31b3-11e7-86bc-194ff7c3b0a3.png)
![perm](https://cloud.githubusercontent.com/assets/15685960/25748219/11ad3746-31b3-11e7-951f-78a6fc716805.png)
![reason](https://cloud.githubusercontent.com/assets/15685960/25748220/11b04242-31b3-11e7-868b-8b4142029c0a.png)

**Comment by diox** [comment]
> embedded webextensions (example: https://addons-dev.allizom.org/en-US/developers/addon/embedded-webextension-2/edit)

Only "pure" webextensions can be auto-approved

> add-on flagged by admin during submission (example: https://addons-dev.allizom.org/en-US/editors/review/multiple-)

Not a webextension

**Comment by ValentinaPC** [comment]
Marking this verified fixed.
