### ISSUE TITLE
Exposing long list permissions on the review page create minor UI issues

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#5339]
### Describe the problem and steps to reproduce it:
On Firefox, looking at https://addons.mozilla.org/en-US/editors/review/samo-select shows a long list of permissions that somewhat create a bad UI experience for the reviewer.

On Google Chrome 53, the UI of this same review page is broken. See :
![chrome_ui_broken](https://cloud.githubusercontent.com/assets/2171145/25746168/36ee3fca-3170-11e7-8893-970d8645b552.png)

### Anything else we should know?
This is related to https://github.com/mozilla/addons-server/issues/5311

**Comment by eviljeff** [comment]
assigned Andreas because he added the feature.
