### ISSUE TITLE
Don't display approvals counter for non-webextensions in reviewer tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5341]
The approvals counter in reviewer tools is only useful for auto-approvable add-ons, only display it for webextensions.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Postfix screenshot:
![no-counter](https://cloud.githubusercontent.com/assets/15685960/25795329/8098cc02-33dd-11e7-831f-74ac44b3e213.png)
