### ISSUE TITLE
User bio HTML support broken

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5356]
See for example this profile: https://addons.mozilla.org/user/MaDonna/

The HTML is just shown directly on the page, rather than parsed. I would guess this is related to #5264.

**Comment by eviljeff** [comment]
![screenshot 2017-05-09 16 32 32](https://cloud.githubusercontent.com/assets/768592/25859015/294fae18-34d5-11e7-890f-9c0f85093bd9.png)

@jvillalobos which do you prefer to be 'correct'? (1st is what's on prod)

Raw string is `u'<b>bold</b> \r\n rn linebreak \r\n <script>alert()</script> <i>italic</i> <br>br linebreak</br> <a href="http://awesome/">a link</a>'`

**Comment by jvillalobos** [comment]
I prefer the last one.

Also, glad I already ate. 🌯

**Comment by eviljeff** [comment]
Note that one keeps the text for the link, which is a little different than what the localised version before used to do. 
🍣

**Comment by jvillalobos** [comment]
Noted.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7) in both My Profile and Developer profile pages.
Postfix screenshots:
![myprofile](https://cloud.githubusercontent.com/assets/15685960/25938041/9d4129a2-3636-11e7-8029-c1a9d0c752ef.png)
![html](https://cloud.githubusercontent.com/assets/15685960/25938045/a1021ac4-3636-11e7-8a10-590399a86e07.png)
