### ISSUE TITLE
Wrap add-on summary in public pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5357]
Steps to reproduce:
1. Add a multiple line summary for a public add-on i.e. https://addons-dev.allizom.org/en-US/firefox/addon/tab-mix-plus/?src=cb-dl-mostpopular
2. Go in its category listing page and hover over it i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/tabs/

Expected results:
The summary is wrapped and causing no issues.

Actual results:
The summary is not wrapped.

Notes/Issues:
- in Dev Hub, Edit Information page the summary is wrapped at save.
- on device the summary is wrapped in add-on details page

Verified on FF53(Win 7). Issue is reproducing on all AMO servers.
Screenshot for this issue:
![edit](https://cloud.githubusercontent.com/assets/15685960/25841174/c87783ae-34a7-11e7-8f4f-2d45d2668749.png)
![add-on_details](https://cloud.githubusercontent.com/assets/15685960/25841186/d4d62416-34a7-11e7-9ccb-869876ba4562.png)
![listing](https://cloud.githubusercontent.com/assets/15685960/25841192/d9681a84-34a7-11e7-9781-4c0838f41ea1.png)

**Comment by tsl143** [comment]
What should be ideal behavior for this -
- Shall we restrict number of lines?
- Shall we restrict height and put scroll?

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
