### ISSUE TITLE
Disco Pane content update - May 2017

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#5364]
For the **25 May** push, we'll leave all current extensions featured (Bulk Media Downloader, uBlock, Awesome Screenshot Plus, Emoji Keyboard), and just REPLACE the three themes...

[new themes]

[Colorful Mandala](https://addons.mozilla.org/firefox/addon/colorful-mandala-by-candelora/) by Candelora
[Fiery Lion](https://addons.mozilla.org/firefox/addon/fiery-lion/) by Cheddo
[Sunshines Bright](https://addons.mozilla.org/firefox/addon/sunshines-bright/) by MaDonna

Full page content lineup, top to bottom...

Colorful Mandala
Emoji Keyboard
uBlock
Fiery Lion
Bulk Media Downloader
Awesome Screenshot Plus
Sunshines Bright

@muffinresearch, @EnTeQuAk, @diox

**Comment by muffinresearch** [comment]
@EnTeQuAk you ok to get the updated strings landed ASAP so there's enough time to get the translations ahead of the 25th push?

**Comment by EnTeQuAk** [comment]
@muffinresearch yeah, I am just about to prepare the patch so it can land after our tag tomorrow
