### ISSUE TITLE
Add-on compatibility cannot be changed if Mobile option is present

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5366]
Steps to reproduce:
1. Load Manage page for an add-on that has Mobile set through its Compatibility options i.e. https://addons-dev.allizom.org/en-US/developers/addon/phony/versions/1425918
2. Add/delete some compatibility options and "Save changes"

Expected results:
Changes are saved.

Actual results:
Changes are not saved.

Notes/Issues:
- not reproducing for add-ons that don't have "Mobile" compatibility option set

Verified on FF53(Win 7). Issue is reproducing on AMO-dev and AMO-stage.
Video for this issue:
![mobilecompat](https://cloud.githubusercontent.com/assets/15685960/25890130/195e30ba-3575-11e7-9e5b-a56a1db2bc76.gif)

May be a regression from #5324

**Comment by diox** [comment]
Certainly a regression from #5324, yes. I wonder how it has been handled in the past when deprecating applications, it's something that has not been done in a very long time...

**Comment by diox** [comment]
Since we can't add them back, I think the solution will be a migration to remove the compatibility info for the "Mobile" app.

**Comment by diox** [comment]
Once https://github.com/mozilla/addons-server/commit/1fca3dd2119a4759a3049a4f44c97ad5c4471cc0 has landed on dev we'll cherry-pick it to stage. It will remove usage of that application directly in the database.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev and stage using FF53(Win 7).
Seems like the Mobile compat option was removed from all available add-ons. (although I could not check it all :) )
Postfix video:
![compat](https://cloud.githubusercontent.com/assets/15685960/25939742/911f8172-363c-11e7-8a10-4062b38bc588.gif)
