### ISSUE TITLE
Display abuse reports for user on an admin viewable user profile page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5375]
Similar to https://github.com/mozilla/addons-server/issues/5310, I'd be good to show user abuse reports on the user profile page (for users with the right permission).

**Comment by eviljeff** [comment]
Is this required sooner than Q3 when addons-frontend will replace the existing (legacy) profile page?

**Comment by wagnerand** [comment]
Maybe not required, but if easy, it would be a quick win. Currently, we have to go through salesforce...

Adding @jvillalobos for making a decision.

**Comment by jvillalobos** [comment]
Not required before the new front end.

**Comment by muffinresearch** [comment]
Since in the new frontend we're not going mix privileged data views in on regular pages this should probably be setup as an admin page instead.

**Comment by diox** [comment]
The user admin page has been doing this for over a year, since 75a24cc23a38a848db464f6c129ac34656671a2f, and we're moving away from adding admin stuff on the frontend, so can we close this?
