### ISSUE TITLE
Remove footer field from theme submission form

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#5379]
### Describe the problem and steps to reproduce it:
Theme footers are obsolete, so we should remove the field on the theme submission form where we ask for a footer image.

### Anything else we should know?
https://www.dropbox.com/s/k5gvodd0c88pazg/Screenshot%202017-05-10%2011.31.23.png?dl=0

**Comment by caitmuenster** [comment]
Hey @atiqueahmedziad, how are you doing with this?

**Comment by atiqueahmedziad** [comment]
@caitmuenster I had to close the previous pr due to having conflicts. I will open a new pr within this week. :D

**Comment by CuriousLearner** [comment]
Hey is this still under progress? @atiqueahmedziad 

If not, I'll be able to take this forward ;)

cc @caitmuenster

**Comment by atiqueahmedziad** [comment]
@CuriousLearner Please feel free to proceed with this one. I will pick another bug :)

**Comment by EnTeQuAk** [comment]
@atsay @jvillalobos this is going to land with https://github.com/mozilla/addons-server/pull/7718 probably next week. Does this need some developer communication?

We'd also remove footer files and model fields one week after this change lands, does that work for you?

**Comment by atsay** [comment]
No comms needed, and removing files sounds good. Thanks!

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF59, Win10x64:
- themes can be submitted/updated
- themes can be approved/rejected
- themes can be previewed and installed

![image](https://user-images.githubusercontent.com/31961530/37911028-a778dd7a-3117-11e8-9bea-b9ea51fa40a0.png)
