### ISSUE TITLE
Remove "Add-ons for Mobile" option from "More..."

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5384]
Steps to reproduce:
1. Load AMO homepage https://addons-dev.allizom.org/en-US/firefox/
2. Click on "More..." option from the menu

Expected results:
"Add-ons for Mobile" option is not listed.

Actual results:
"Add-ons for Mobile" option is listed.

Notes/Issues:
- "Mobile" compatibility no longer being listed in Dev Hub ( #5324 ), no use to confuse the user;
- clicking on it redirects as expected.

Verified on FF53(Win 7). Issue is reproducing on all AMO servers.
Screenshot for this:
![mobile](https://cloud.githubusercontent.com/assets/15685960/25939061/37182276-363a-11e7-8600-2883d578a272.png)

**Comment by ValentinaPC** [comment]
In time.... only the link changed and not the option name.

**Comment by jvillalobos** [comment]
This doesn't need to be changed, at least not in the old front end. The distinction between "mobile" and "Android" is strictly internal, and shouldn't be confusing for end users.

The new frontend, as it currently stands, won't have that option in the main navigation.
