### ISSUE TITLE
Experimental add-ons available on all platforms have the install button text black

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#5385]
### Steps to reproduce:
1. Open https://addons.allizom.org/en-US/firefox/addon/no-shoes-radio-add-on-for-fire/ and observe the button
2. Open https://addons.allizom.org/en-US/firefox/addon/fireplurk/ and observe the button

### Expected results:
Both experimental add-ons not compatible on current Firefox version have the same button.  

### Actual results:
The button for the all platform add-on has the text black.

### Notes/Issues:
Verified in FF53(Win7) in addons.allizom.org
Screencast for this issue:
![2017-05-11_1220](https://cloud.githubusercontent.com/assets/15685441/25942045/4579b406-3644-11e7-918c-ceb600152ea8.png)

**Comment by Anirudh257** [comment]
Hey, I have just started contributing to open source and have a bit of knowledge about Front-end development. I would love to help you

**Comment by EnTeQuAk** [comment]
unfortunately I am going to close this bug given that this particular part is currently being reworked as part of our new https://github.com/mozilla/addons-frontend so I'd feel bad having anyone work on this and replace that work soon after.

There's quite a few other open bugs that should be easy to work on and have a mentor assigned @Anirudh257 so please have a look at https://github.com/mozilla/addons-server/labels/contrib%3A%20good%20first%20bug - any help on these is very much appreciated!

**Comment by Anirudh257** [comment]
Thanks.!!
