### ISSUE TITLE
multifox

### ISSUE THREAD

**Issue by deniz4424** [mozilla/addons-server#5388]
multifox  eklentisi neden yok bulamıyorum  lütfen yeniden eklenti olarak verirmisiniz. mozilla güncellemesi sonrasında eklenti çalışmadı  yeniden yüklemek istedim ancak siz kaldırmışsınız ilgini ve cevabınızı bekliyorum. teşekkürler.

**Comment by andymckay** [comment]
Please see the comments in #4714.
