### ISSUE TITLE
File viewer fails to display file contents

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5394]
It happened again. I know. I'm sorry. 

The file viewer failed horribly for file 641732.

<img width="1675" alt="screen shot 2017-05-12 at 20 19 36" src="https://cloud.githubusercontent.com/assets/873258/26011335/3769d042-3740-11e7-8a35-f20d405333ff.png">

Pinging @EnTeQuAk as he'll sure love to see this.

**Comment by muffinresearch** [comment]
@wagnerand I've not look at this on the site, but from the screenshot it says the highlighted file is a directory. Or is that you can't view the files under the directory at all too?

**Comment by wagnerand** [comment]
Correct. There should be at least a manifest file (otherwise it wouldn't have passed validation and therefore wouldn't be accepted).

**Comment by EnTeQuAk** [comment]
😠 I'll take a look shortly, let's hope we can still see something in the server-logs. I assume this was on prod?

**Comment by wagnerand** [comment]
Yes! Thank you!

Christopher Grebs <notifications@github.com> schrieb am So. 14. Mai 2017 um
08:26:

**Comment by EnTeQuAk** [comment]
Still investigating… I can't see anything obvious related to that file but I found 

```XPI parse error :/data/olympia/src/olympia/files/utils.py:660#012Traceback (most recent call last):#012 File "/data/olympia/src/olympia/files/utils.py", line 648, in parse_xpi#012 extract_xpi(xpi, path)#012 File "/data/olympia/src/olympia/files/utils.py", line 618, in extract_xpi#012 tempdir = extract_zip(xpi)#012 File "/data/olympia/src/olympia/files/utils.py", line 547, in extract_zip#012 zip_file.extract_to_dest(tempdir)#012 File "/data/olympia/src/olympia/files/utils.py", line 527, in extract_to_dest#012 self.extract_info_to_dest(info, dest)#012 File "/data/olympia/src/olympia/files/utils.py", line 514, in extract_info_to_dest#012 self.zip_file.extract(info, dest)#012 File "/usr/lib64/python2.7/zipfile.py", line 1024, in extract#012 return self._extract_member(member, path, pwd)#012 File "/usr/lib64/python2.7/zipfile.py", line 1080, in _extract_member#012 shutil.copyfileobj(source, target)#012 File "/usr/lib64/python2.7/shutil.py", line 49, in copyfileobj#012 buf = fsrc.read(length)#012 File "/usr/lib64/python2.7/zipfile.py", line 628, in read#012 data = self.read1(n - len(buf))#012 File "/usr/lib64/python2.7/zipfile.py", line 668, in read1#012 self._update_crc(data, eof=(self._compress_left==0))#012 File "/usr/lib64/python2.7/zipfile.py", line 643, in _update_crc#012 raise BadZipfile("Bad CRC-32 for file %r" % self.name)#012BadZipfile: Bad CRC-32 for file 'chrome/skin/overlay.css'
```

which isn't something that's in that package but there are quite a few… can't find anything containing a file in that package though… still searching…

**Comment by EnTeQuAk** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/8220
