### ISSUE TITLE
Fails while running 'make initialize_docker'

### ISSUE THREAD

**Issue by harikishen** [mozilla/addons-server#5395]
The make script to initialize db fails
This is the output of the command https://pastebin.mozilla.org/9021528

**Comment by harikishen** [comment]
I would like to takeup this issue and fix this

**Comment by EnTeQuAk** [comment]
I don't see anything in the paste you linked, mind checking and posting all the details you have? I just reset and initialized my database locally and it worked just fine.

**Comment by EnTeQuAk** [comment]
I closed the issue for now but please feel very free to re-open at any time with more information if necessary.

**Comment by harikishen** [comment]
@EnTeQuAk I think there is some issue

**Comment by harikishen** [comment]
Thought the script did work now

**Comment by harikishen** [comment]
It would be great if you look into it

**Comment by harikishen** [comment]
Sorry about the pastebin link I had by mistake set it to be available only for a day

**Comment by harikishen** [comment]
this was the issue i faced earlier https://github.com/mozilla/addons-server/issues/2568

**Comment by EnTeQuAk** [comment]
Interesting, I can't reproduce and this was fixed for quite some time. It'd be really nice to get some kind of log or so to reproduce or follow along this easier if you have it or if you're able to reproduce.

**Comment by EnTeQuAk** [comment]
Maybe this got fixed by https://github.com/mozilla/addons-server/issues/5374?

**Comment by harikishen** [comment]
Hmm
