### ISSUE TITLE
[Auto-Review] Not picking up Unacceptable JQuery Libraries

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#5407]
ref: `https://addons.mozilla.org/en-US/editors/review/706533/`

Version 1.1.2 · March 17, 2017
Approved By Mozilla on May 11, 2017, 10:15:11 PM

Above should not have passed the AUTOMATIC review.

**Comment by diox** [comment]
It's not an auto-approval criteria. 

If we're talking about a jQuery file that is directly imported from their website, and should not be allowed, this should be done in addons-linter. Otherwise, we have no way to reliably detect this.

cc @jvillalobos

**Comment by wagnerand** [comment]
Version 1.1.2 contains a jQuery 3.1.1 that validation recognized as valid.

**Comment by erosman** [comment]
I was actually referring to other JQueries such as `jquery-ui.min.js` which is NOT recognised by the validator.

**Comment by wagnerand** [comment]
If, a file is not recognized as a known library, it's just yet another file. We (currently) cannot detect a library that just doesn't match the hashsum. We therefore cannot reject (post-review or not) a file that includes a non-matching library file.

**Comment by erosman** [comment]
As a suggestion, auto-approval can consider/detect minified files (ie files without line breaks for XXX length characters).

**Comment by diox** [comment]
This is out of scope for the current auto-approval mechanism.

For post-review (planned this quarter), something like that (which may not be 100% reliable) will be included to bump the add-on up in the post-review queue.
