### ISSUE TITLE
Track successful / failed submissions via statsd

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5410]
There's a bunch of stats already being sent related to upload, but it's unclear if they're the right stats in order to track the health of submissions via the devhub.

The ideal solution to this would be to track submission successes and failures via a statsd count.

**Comment by diox** [comment]
We already track successes in AMO Prod Health dashboard in datadog / grafana, so lowering priority. It'd be nice to track failures as well.
