### ISSUE TITLE
User account admin functionality

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5411]
The new [desktop scope PRD](https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit?pli=1#heading=h.5cheild9uc3u) calls for the exact existing functionality administering user accounts.  I.e. in addition to an admin being able to change everything the user can change (biography, username, etc) they can also set/view account notes; change email address; anonymize the account; and are required to supply a reason for the change.

Leaving aside whether building extra admin functionality into user facing pages is good security practise, its certainly scope creep.  IMO admin functionality should be in an admin tool, ideally. There was a plan to build an admin account lookup(#3138) after the admin addon lookup tool... but given the recent deprecation of the latter the former seems unlikely in the short term.  One solution is to fall back to using the user profile editing functionality in django-admin (/admin).

Thoughts @jvillalobos @mozilla/addons-mozilla-org-developers ? (and anyone else)

**Comment by jvillalobos** [comment]
Having a separate admin tool is ideal, but not in the current plans, so I think keeping the existing behavior is the better way forward. The django-admin page doesn't seem to have the same functionality.

I'd like to dedicate some focus to admin tools sometime in Q4/Q1-2018, but that depends on what else is happening then.

**Comment by eviljeff** [comment]
To be clear, any existing behaviour is bound in the current django-frontend that will be dropped when desktop is finished for addons-frontend later this year.  So what we're talking about is effectively *new* functionality.  Either:

a) spend development resources adding extra admin functionality (and complexity) to the account API; then spend development resources adding the same functionality to addons-frontend to handle it.  I don't know if UX have done any user profile related work yet but they'd need to take it into account too.

b) spend development resources fixing up user profile editing in django-admin to add/fix anything missing/broken there.  I don't think we know what doesn't work there yet, other than it's not pretty.

c) spend (a lot of) development resource building a complete new admin user lookup and editing tool.  At the very least this is unlikely to happen before we're ready to enable addons-frontend on desktop so there would be a gap in functionality.

**Comment by muffinresearch** [comment]
We should discuss this further, but I would very much like to get away from having admin functionality interleaved with user  pages. 

For now if we need additional admin functionality to edit user pages I'd propose we should make a specific page in the current addons-server admin app.

**Comment by tofumatt** [comment]
> We should discuss this further, but I would very much like to get away from having admin functionality interleaved with user pages.
> 
> For now if we need additional admin functionality to edit user pages I'd propose we should make a specific page in the current addons-server admin app.

I agree.

I've always found it a straightforward way of building apps–to simply add some admin checks into the controllers/views+templates rather than build a new admin page, but even I agree when we want the admin behind a VPN for security reasons and not part of the "user-facing" app. 👍 

Mixing and matching is the worst-case I think because it's confusing and arguably a lot of our admin security is via access-control via the VPN. Exposing that stuff to the world when we don't normally feels like a weak spot in our known attack vectors.

**Comment by jvillalobos** [comment]
> For now if we need additional admin functionality to edit user pages I'd propose we should make a specific page in the current addons-server admin app.

Is this different from the admin app in https://github.com/mozilla/addons-frontend/issues/2373?

**Comment by tofumatt** [comment]
Yes, that's the React-based app we'll be phasing out. @muffinresearch was talking about the addons-*server* Django admin app.

**Comment by eviljeff** [comment]
After finishing the delete endpoint for accounts here's the state of things:
* Anonymise: it's the same as user delete so for the 'admin anonymize' just call the user delete.  If a hard delete is needed (that removes fk-linked content like reviews too) then continue to link to the existing /admin/ model delete, as the current user profile pages do.
* Changing of user settings: In the same way admins can use other consumer APIs, admins can set the same account details the user can.  The only detail an admin can currently change that user's can't is their email address (because FxA) - /admin/ model allows this to be changed in the very rare cases it's needed.
* Account notes:  Fun fact, the existing user profile page's 'notes' field is broken, possibly for [>5 years](https://github.com/mozilla/addons-server/commit/bff516fe585ef765f2f531f455feb316a5138ac9), and always returns "" for the value and would error if you tried to set it. There are 1.4 million accounts have notes set but they're all (apart from 3 accounts)* automated notations when we did some kind of migration.  This won't be implemented in the API - it could still be get/set via the /admin/ model but we could drop this field. 
* Reason for Change: Nowhere else on AMO do we require admins to specifically write down why they are changing something, so requiring it for user profiles is inconsistent; it's _not_ required for deleting profiles; and its _not_ required if the changes are made via /admin/ model anyway.  So this won't be implemented in the API.

I don't think there's anything more to do here then.  Until /admin/ model search and editing is replaced with a dedicated lookup api (#3138) anyway.

---
Account notes:
1324787 * `Imported from getpersonas, username: <username>`
156528 * `bug1035375`
474 *  `__market__`  
1 * `Admin change to email address (from xxx@gmail.com to xxx@kadale.info) on 9/19/07 by fwenzel.`
1 * `OAuth Account for Add-on Builder`
