### ISSUE TITLE
"Updates" queue is active while "Queues" option is clicked

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5415]
Steps to reproduce:
1. Load Reviewer Tools page https://addons-dev.allizom.org/en-US/editors/
2. Click "Queues"

Expected results:
Queues page is loaded. "New Add-ons" tab is active.

Actual results:
Queues page is loaded. "Updates" tab is active.

Notes/Issues:
- I've search a few times `new submitted add-ons` in Updates queue and was scarred that could not find them, because of this. :)
- initially New Add-ons tab was active while clicking on Queues option from the menu.
- any other menu options loads the first option

Verified on FF53(Win 7). Issue is reproducing on AMO-dev and AMO-stage.
Video for this issue:
![new-addons](https://cloud.githubusercontent.com/assets/15685960/26097924/df64e2be-3a2e-11e7-98e5-8d6cd7bfc5b1.gif)

**Comment by diox** [comment]
This is just because going to /queues/ redirects to the /queues/update, on purpose.
