### ISSUE TITLE
Do not send super-review request notifications to amo-editors

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5419]
We're slowly phasing out the amo-editors mailing list, since we have activity email now. @kewisch and I are ok with removing email notification to that mailing list for super review requests, since we don't look at them anyway currently. Long term, super-review might shift a little bit with post-review, but we can tackle that at a later time. It won't probably involve sending a mail to a mailing list anyway.

**Comment by ValentinaPC** [comment]
@wagnerand : You are talking about the "`Dear Superheroes...`" mails sent to `amo-editors`, yes?
This kind of mails are no longer sent.
Verified on AMo-dev FF53(Win 7) using Fake mails logs and may Yahoo client.
Only an `admin flag` notification is sent to add-on developer.
Postfix screenshots:
![fakemail](https://cloud.githubusercontent.com/assets/15685960/26146552/3e4eed2c-3af9-11e7-8ba5-bca9379ec55c.png)
![yahoo](https://cloud.githubusercontent.com/assets/15685960/26146553/3e550fb8-3af9-11e7-9635-a69ed5e4ca31.png)

**Comment by wagnerand** [comment]
Yes, talking about the email to amo-editors.
