### ISSUE TITLE
Search will not list any search results even if there are some suggestions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5421]
Steps to reproduce:
1. Load AMO homepage https://addons-dev.allizom.org/en-US/firefox/
2. Make a search after "423" 

Expected results:
If search suggestions are displayed, after finalizing the search, results should be listed.

Actual results:
One search suggestion is displayed, but clicking on the green arrow or hitting "enter" will not display the search suggestion.

Notes/Issues:
- other example "123" - will list 1 search suggestion but the suggestion will not be listed through search results.

Verified on FF53(Win 7). Issues is reproducing on all AMO servers.
Video for this issue:
![search](https://cloud.githubusercontent.com/assets/15685960/26103388/c76a9d58-3a41-11e7-81fa-db02a5772d41.gif)

**Comment by diox** [comment]
Only happens when you search for numbers, and it's intended - there is a shortcut built into the suggestion view (and only there, apparently) that gives you the add-on with the corresponding ID.
