### ISSUE TITLE
Wrong message while user logs in from 2 AMO tabs

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5428]
Steps to reproduce:
1. Open AMO-stage in 2 tabs while being logged in
2. Sign out from each tab independently 
3. Sing in from each of the tabs

Expected results:
At the second tab, user is announced that he is already signed in.

Actual results:
User appears to be signed in, but the message "You could not be logged in. Please try again. Need help?" is displayed.

Notes/Issues:
- refreshing the page will remove the message
- there is also the case when the message will be displayed again, this time, without logging in the user.

Verified on FF53(Win 7). Issue is reproducing in all AMO servers.
Screenshots for this issue:
![2017-05-17_1320](https://cloud.githubusercontent.com/assets/15685960/26150431/f657e718-3b06-11e7-806e-7316fc23bc3f.png)

**Comment by eviljeff** [comment]
Message says "You are already logged in. " now

**Comment by vcarciu** [comment]
@eviljeff  : using the same steps as Valentina, I was able to reproduce this one. Please be sure that after being logged in both tabs, you refresh them before starting to follow the STRs : 
![message](https://user-images.githubusercontent.com/1583842/35568185-a92db14e-05d0-11e8-826d-ed599fe11a10.png)

**Comment by eviljeff** [comment]
I was testing from clean tabs - i.e. not logged in.  Having two tabs open that you then individually log out from, then log in again seems quite an unlikely edge case
