### ISSUE TITLE
Cannot change name of language pack on AMO

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5432]
### Describe the problem and steps to reproduce it:

This happens on prod only!
1. For a langpack, go to the *Edit Information* page in the devhub, e.g. https://addons.mozilla.org/en-US/developers/addon/czech-cz-language-pack/edit
2. Change the name.
3. Change the summary.

### What happened?

After step 2, the title is not changed.
After step 3, the summary **and** name are changed to the exact same string.

### What did you expect to happen?

Summary and name should be changeable independently.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
My money is on https://github.com/wagnerand/addons-server/blob/master/src/olympia/zadmin/tasks.py#L619

**Comment by ValentinaPC** [comment]
For what it's worth this is not happening on AMO-stage or -dev.

**Comment by wagnerand** [comment]
Yes, as mentioned in the initial comment.

The reason for that is that is because language packs are generally pulled from FTP by an automated process, and the bug seems to be in there.

**Comment by wagnerand** [comment]
As per my [earlier comment](https://github.com/mozilla/addons-server/issues/5432#issuecomment-302154356) it seems that during the initial pull of a language pack, we set the summary to the name (because there is no summary yet). What actually happens is that the summary **instance** is set as the name, leading to name and summary being linked to a single row in the translations table.

```
+--------+------------------------+---------+---------+
| id     | slug                   | name    | summary |
+--------+------------------------+---------+---------+
| 417160 | czech-cz-language-pack | 3914620 | 3914620 |
+--------+------------------------+---------+---------+
```

Further investigation revealed that all 115 langpacks are affected.

**Comment by wagnerand** [comment]
After fixing the issue, a very dirty hack could be to delete all langpacks before we pull them again for the next release.
I hope someone has a less crappy idea.

**Comment by jvillalobos** [comment]
A DB script could duplicate the strings on `translations` and change, say, `summary` to point to the new one.

**Comment by wagnerand** [comment]
Heh, what could possibly go wrong. 😄

**Comment by ValentinaPC** [comment]
This fix is already in prod? Can be checked already? Thanks!

**Comment by EnTeQuAk** [comment]
The fix will be in production this Thursday, I already verified on -dev that the fix is working as expected.

**Comment by ValentinaPC** [comment]
While not reproducing in -dev from the beginning, thought it should be checked on prod.

**Comment by EnTeQuAk** [comment]
This is now in production, I think @wagnerand could verify this is fixed?
