### ISSUE TITLE
Give WebExtensions higher priority on search results

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5433]
As part of the transition to Firefox 57, at some point we need to give WebExtensions higher ranking in search results, to encourage users to install WebExtensions over legacy extensions. This behavior should be gated by a waffle flag since the timing to make it live on prod isn't clear yet.

**Comment by diox** [comment]
Easy enough, we just need to figure out a boost value that works. We should be able to do this at runtime I think, just adding a should clause with the appropriate boost if the waffle is turned on.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7) while enabling the waffle "`boost-webextensions-in-search`".
Searching after "permissions" search term will boost the webextensions through the first page of search results and leave the legacy add-ons at the end, but not sure if interfering with the "`name-match boost`"?

Made 2 screenshots with and without the waffle:
![untitled](https://cloud.githubusercontent.com/assets/15685960/26249044/6b0796e2-3cad-11e7-9827-d5d372a0e469.png)

@diox : do you think is ok?

**Comment by diox** [comment]
It's ok. We might tweak the boost to give them an even bigger priority, we'll look into that when enabling it.

**Comment by ValentinaPC** [comment]
Looking forward :)

**Comment by muffinresearch** [comment]
@jvillalobos do you know when you want to turn this on?

**Comment by jvillalobos** [comment]
I'd say the hard deadline is when 57 hits beta (09-26), but we should probably turn it on a couple of weeks earlier to make sure it's working well. Doing it too early might alienate some legacy add-on devs.

**Comment by jvillalobos** [comment]
This is now live in prod.
