### ISSUE TITLE
de-anonymise UserProfile

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5440]
from irc

> — @eviljeff notes three different references to 'anonymous' in UserProfile - is_anonymous; has_anonymous_username; anonymize (not logged in; no username set; deleted) :/
> — @eviljeff tries to come up with non-stupid synonyms

I'm thinking of changing `def anonymize` to override `delete` as we never actually delete.  And it's how we do soft-delete on other models.

`is_anonymous` is defined on AbstractBaseUser https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.is_anonymous so we need to keep that one.

anonymous usernames just need renaming.

**Comment by ValentinaPC** [comment]
Verified the anonymize feature from User Profile while being logged with an admin account on AMO-dev using FF53(Win 7), and observed the following:
- even if there is "Notes" filed in the "Anonymize" section, it cannot be completed - why there?
- anonymizing a user will redirect to an admin page where incomplete and incorrect info about this action will be displayed - who anonymized, but not whom
- the anonymized user is not removed from the add-on and if clicked will redirect to a 404 page

Video/screenshot:
![incorrect](https://cloud.githubusercontent.com/assets/15685960/26238188/aa7abc28-3c80-11e7-94ca-2c4ac50d2938.png)
![anonymize](https://cloud.githubusercontent.com/assets/15685960/26238200/b58d02d8-3c80-11e7-97af-780c8e23b2ee.gif)

@eviljeff : what do you think about these?

**Comment by eviljeff** [comment]
It does some weird things, but it's functioning as before.

**Comment by ValentinaPC** [comment]
> It does some weird things, but it's functioning as before.

"as before" means "correct"?

**Comment by eviljeff** [comment]
Don't know why the admin log is wrong - seems to be a bug.  The others are just the way the tool works now - correct is up to Product to decide and log an issue to ask us to change.

**Comment by ValentinaPC** [comment]
Should I log an issue for the admin log?
Also, we can mark this verified?
Thanks @eviljeff !

**Comment by eviljeff** [comment]
Admin-only functionality like that is being re-implemented in Q3 and it's not going to be fixed before then so I wouldn't bother logging an issue.
Sounds otherwise verified to me!
