### ISSUE TITLE
Add search in Auto Approved Add-ons queue

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5442]
Steps to reproduce:
1. Load Auto Approved Add-ons queue from Reviewer Tools https://addons.allizom.org/en-US/editors/queue/auto_approved

Expected results:
A search field is displayed.

Actual results:
No search field.

Notes/Issues:
- being at the beginning of auto-approvals, this does not seem mandatory, but in the future will be useful to be able to search for a specific auto-approved add-on.

Verified on FF53(Win 7).
Screenshot for this issue:
![2017-05-18_1517](https://cloud.githubusercontent.com/assets/15685960/26201767/33e06e8a-3bdd-11e7-8af5-f264d1ba6787.png)

**Comment by EnTeQuAk** [comment]
I triaged this since it sounds like a reasonable idea but cc @diox and @jvillalobos whether or not this needed in the future (and could be closed if not)?

**Comment by jvillalobos** [comment]
Yes, we'll possibly need this in the future, though it's not a pressing issue right now.
