### ISSUE TITLE
"400 Bad Request" after long word search

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5443]
Steps to reproduce:
1. Navigate to the AMO home page.
2. Perform a search for ~8100 characters.
3. Click on any hyperlink button on the page.

Expected results:
The user is redirected to the correct page.

Actual results:
The "400 Bad Request" error page is displayed.

Notes/Issues:
Issue is reproducing on all AMO servers.
Verified on FF53(Win 10 64Bit).
When performing a search with more than 10.000 character the user is directly redirected to the "414 Request-URI Too Large" error page.
Video for this issue:
![long search 1](https://cloud.githubusercontent.com/assets/28138132/26203300/608d88d6-3be3-11e7-9177-ebb587594be9.gif)

**Comment by muffinresearch** [comment]
> The user is redirected to the correct page.

What is the expected "correct" page for this kind of search request? 

Personally I think the 414 error is right, but the presentation could be improved.

**Comment by SVSanta** [comment]
Well for the first scenario when you introduce ~8100 characters, the problem is first that there is no error displayed until you click on any hyperlink button. As a side effect if he wants to use the AMO page again he has to open a different tab, so that is a big issue since the user is unaware of the workaround.

For the ~10.000 characters search, the 414 error message should be displayed and chandelled inside the amo page.

**Comment by diox** [comment]
No actual user should ever do that, though...

**Comment by EnTeQuAk** [comment]
I'm triaging this but I think it's an edge-case and low-priority

**Comment by EnTeQuAk** [comment]
@diox I think this got fixed with your recent changes to character length on search?

**Comment by diox** [comment]
The 400 we control, yes. The 410, no, but as I said, if you do that... you kinda deserve a non-fancy error page :)

Let's close this.

**Comment by AlexandraMoga** [comment]
The current maximum length for the new frontend search is 100 characters. The above steps will no longer apply on the new AMO, so this can stay closed.
