### ISSUE TITLE
Links from "Add-on Review Log" for unlisted/mixed add-ons load the listed review page of the add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5445]
Steps to reproduce:
1. Pick a mixed versions add-on, or unlisted i.e. https://addons.allizom.org/en-US/firefox/addon/wombarog-rhingon-whawk/
2. Go to its unlisted review page https://addons.allizom.org/en-US/editors/review-unlisted/wombarog-rhingon-whawk
3. Leave a comment (any type)
5. Go to Logs -> Add-on Review Log from Reviewer Tools - https://addons.allizom.org/en-US/editors/reviewlog and click on the comment you left

Expected results:
User is redirected to the Unlisted Review page.

Actual results:
User is redirected to the Listed Review page if the add-on has mixed version, or to neither listed or unlisted for an only unlisted add-on.

Notes/Issues:
Verified on FF53(Win 7). Issue is reproducing on AMO-dev and stage.
Video for this issue:
![logs](https://cloud.githubusercontent.com/assets/15685960/26205239/d0ccce6c-3be9-11e7-8f7f-9852ec2f761c.gif)

**Comment by harikishen** [comment]
I would like to take this up.

**Comment by caitmuenster** [comment]
It's all yours, @harikishen!

**Comment by harikishen** [comment]
@caitmuenster thanks

**Comment by harikishen** [comment]
@eviljeff how do i reproduce the issue locally ???

**Comment by eviljeff** [comment]
To get an unlisted version you just need to submit an addon to your local AMO, but choose you don't want to list it on the website.  Then in devhub edit page for that add-on they'll be link to it's unlisted review page.  From there the instructions and video in the first comment should help to finish reproducing.

**Comment by harikishen** [comment]
@eviljeff Thanks

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Unlisted or mixed versions add-on that have been reviewed will redirect to the correct page from Add-on Review Logs.
Postfix video:
![unlistedlogs](https://cloud.githubusercontent.com/assets/15685960/26823908/0226fd84-4ab8-11e7-978d-c3d377dda6b1.gif)
