### ISSUE TITLE
"Statistics" spinner overlapping "search suggestions"

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5446]
Prerequisites:
User is logged with an admin account.

Steps to reproduce:

1. Navigate to the AMO home page.
2. Tap on any addon that has statistics available.
3. Tap on the "View statistics" button.
4. Quickly introduce 3 letters in the search field.

Expected results:
"Search suggestions" overlaps the "Statistics" spinner.

Actual results:
"Statistics" spinner overlaps the "search suggestions".

Notes/Issues:
Issue is reproducing on all AMO servers.
Verified on FF53(Win 10 64Bit).
Screenshot for this issue:
![overlap](https://cloud.githubusercontent.com/assets/28138132/26205811/8c3724da-3beb-11e7-8d93-fade029c7e39.jpg)

**Comment by eviljeff** [comment]
fixed this by dropping the search box 😆 in #10918
