### ISSUE TITLE
Show reason for activity email

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5453]
For admins to distinguish whether they are actually involved in a review or getting an activity email because there are a member of the CC group, it would be useful to know why they got an activity email.

The email should not something like one of:
`You are receiving this mail because you are an author of the add-on.`
`You are receiving this mail because you reviewed this add-on.`
`You are receiving this mail because you are in the activity mail cc group.`

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev using FF53(Win 7) and Fake Mail Logs page.
Postfix screenshots:
![untitled](https://cloud.githubusercontent.com/assets/15685960/26297996/2f63b49e-3ede-11e7-96f4-f5de60b8db30.png)
