### ISSUE TITLE
"Confirm approval" message is recorded in Dev Hub at the not-approved version of an add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5456]
Steps to reproduce:
1. Go to review page for an add-on that has a version that was **not** auto-approved from some reason i.e. https://addons-dev.allizom.org/en-US/editors/review/catrid-ratel-magoodpird-csp
2. Click "confirm approval"
3. Go to Manage Status & Versions page and click Review history

Expected results:
Auto-approval confirmation is not listed (maybe?).

Actual results:
Confirmation of auto-approval was recorded on the version that failed auto - approval.

Notes/Issues:
- "Confirm approval" option is displayed at the last version of an add-on that has at least 1 version auto-approved and public, even if, last version does not qualify for auto-approval.

Verified on AMO-dev FF53(Win 7).
Screenshots for this issue:
![2017-05-19_1246](https://cloud.githubusercontent.com/assets/15685960/26246446/e5e258d6-3ca1-11e7-81ea-5132966e87bd.png)
![devhub](https://cloud.githubusercontent.com/assets/15685960/26246780/970e12ac-3ca3-11e7-8e1d-c0436a180145.png)

**Comment by wagnerand** [comment]
@diox does this fix https://github.com/mozilla/addons-server/issues/1542 as well?
