### ISSUE TITLE
Update links in FAQs

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5465]
Followup from https://github.com/mozilla/addons-server/issues/5206#issuecomment-303100566

**Comment by wagnerand** [comment]
@jvillalobos that KDE page is not that helpful anymore, what about https://choosealicense.com/ ?

**Comment by jvillalobos** [comment]
The FAQ is just listing a bunch of them, including the one you mention.

**Comment by wagnerand** [comment]
Ok, so merge anway and deal with it later?

**Comment by wagnerand** [comment]
Ah, now I see what you mean. Still the description for that url says something about a "table for comparison", which doesn't seem to be there any longer.
No blocker though, we can update that list later.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7).
Link from [Developer FAQ](https://addons-dev.allizom.org/en-US/developer_faq) is redirecting as expected.
Links from [FAQ](https://addons-dev.allizom.org/en-US/faq) page - Firefox and Firefox for Android - redirect as expected.

There is an issue with the "gallery" link from FAQ page, Mobile section, redirects to the wrong page.
Can we fix that too?
Please see screenshot for the gallery link:
![2017-05-24_1400](https://cloud.githubusercontent.com/assets/15685960/26400470/acbdb38e-4089-11e7-8189-bb2dde58480c.png)

**Comment by jvillalobos** [comment]
I'm assuming this was reopened accidentally, so closing again.

**Comment by ValentinaPC** [comment]
@jvillalobos : Was reopened **on purpose**, because one of the link from FAQ is returning a 404 and seemed like a good idea not to log another issue and reopen this one. 
But, we can do it as you wish.

**Comment by jvillalobos** [comment]
Ah, sorry, I didn't realize the previous comment was connected to the reopening. Doing a followup issue is good, thanks.

**Comment by ValentinaPC** [comment]
@jvillalobos Thanks for your reply!
