### ISSUE TITLE
Activity mail should appear to come from the actual sender

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5468]
Right now activity email is sent with the header `From: amo-editors@mozilla.org`, with no name. 

This makes it hard to easily see who the email is really from. It would be great to show the actual sender's name (i.e. the reviewer or developer). 

The header would be `From: Philipp Kewisch <amo-editors@mozilla.org>`.

Possibly we should use another email address to avoid email clients saving the name together with the email address in the address book and confusing email actually for/from amo-editors

**Comment by vcarciu** [comment]
The actual sender is still not displayed in activity mail : 
![amoeditors](https://cloud.githubusercontent.com/assets/1583842/26412779/85b17c20-40b2-11e7-99ca-8c265bc282db.png)

**Comment by wagnerand** [comment]
Approval/Rejection emails are not part of the activity email feature yet. Can you please try using reviewer or developer reply?

**Comment by vcarciu** [comment]
Using reviewer or developer reply , this looks fixed : 
![notif](https://cloud.githubusercontent.com/assets/1583842/26454065/94d618a2-416e-11e7-9788-ac7c6b3a43ce.png)
![sender](https://cloud.githubusercontent.com/assets/1583842/26454079/9e474afa-416e-11e7-8d7b-a3a88c200f1e.png)
