### ISSUE TITLE
Prioritize post-review queue with risk factors evaluation

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5473]
For post-review, we need to sort the list of auto-approved add-ons in reviewer tools according to a set of factors representing the "risk" to end-users.

The set of factors is defined here: https://docs.google.com/spreadsheets/d/1CZEECHHqEmK87fNiWNslAsFQBL7zxYF-c63-zZVZuqw/edit#gid=0

It would be set at (auto-)approval time, stored in a new field in `AutoApprovalSummary` and then used to sort the list in reviewer tools.

**Comment by diox** [comment]
Basic factors:

| Risk Factor | How much is an "instance"? | Value/instance | Min | Max |
| ----------- | -------------------------- | -------------- | --- | --- |
| Admin review flag | One flag; can only have one | 100 | 0 | 100 |
| Size of code changes | 5 Kb code changed | 1 | 0 | 100 |
| Abuse reports | 1 abuse report in the past year | 10 | 0 | 100 |
| Negative ratings / reviews | 1% of ratings with 3 stars or less in the past year | 2 | 0 | 100 |
| Add-on reputation | 1 admin vouch | -100 |-300 | 0 |
| Number of active users | 10K ADI | 1 | 0 | 100 |
| Past rejection history | 1 rejection in the past year | 10 | 0 | 100 |

**Comment by diox** [comment]
Note: size of code changes depend on https://github.com/mozilla/addons-linter/issues/1304 + some field to store the information in addons-server.

**Comment by ValentinaPC** [comment]
There is a new column in the Auto-Approved queue from Reviewer Tools:
![2017-06-06_1135](https://cloud.githubusercontent.com/assets/15685960/26820695/62356ca8-4aac-11e7-8246-01122cb6b448.png)
Not sure what type of sorting should be applied there - given the fact that all the values are 0.
Can this be verified or we should wait for other issues to be fixed, @diox ?
Thanks!

**Comment by diox** [comment]
The sorting should be down using this column, then last human review, then add-on creation date. The weight value depends on the table in the comment above, with the following caveats:
- Size of code changes is not implemented yet
- Add-on reputation, implemented in #5520, goes from -300 to +300

Note that the weight is calculated only once, at auto-approval time, and I haven't bothered to re-calculate it for old add-ons.

**Comment by ValentinaPC** [comment]
> Add-on reputation, implemented in #5520, goes from -300 to +300

Why do we show -3 to +3 on Edit Info page from Dev Hub and not -300 to +300?

**Comment by diox** [comment]
The reputation gets multiplied by -100 to find the weight. (Each "positive step" in the reputation equals -100 weight, decreasing priority, each "negative step" equals +100 weight, increasing it)

**Comment by diox** [comment]
Re-opening to adjust negative reviews weight.

**Comment by ValentinaPC** [comment]
> Note that the weight is calculated only once, at auto-approval time, and I haven't bothered to re-calculate it for old add-ons.

Changing the `reputation` will not change anything in Reviewer Tools, yes?

**Comment by ValentinaPC** [comment]
> Basic factors from the spreadsheet are reproduce below:
 
![2017-06-07_1907](https://user-images.githubusercontent.com/15685960/26888748-a52e5e8a-4bb4-11e7-946f-45fb563a8728.png)

About the table: we can check, for now, only the reputation? Or, the other cases too? and, if yes, can you give me a hand?
Many thanks!

**Comment by diox** [comment]
If you want to check just one flag, it should be doable by just submitting normally, setting the reputation, then submitting an update that would be auto-approved. Just ignore the other flags (don't set admin review flag, don't add abuse reports or negative reviews, don't reject versions, etc)

**Comment by ValentinaPC** [comment]
Yes, doing that. But...the other options are implemented? could be checked?

**Comment by diox** [comment]
Sorry, misread your comment. Everything in that table has been implemented *except* size of code changes.

**Comment by ValentinaPC** [comment]
Ok, will check everything.

Also, while the reputation is between -300 and +300, why I am seeing 310 for "Terrible(-3)"?
Soory for being such a pain in your ... :D

**Comment by diox** [comment]
My guess is that another factor is in play. Either abuse report or past rejection (keep in mind the reputation value is "inverted", multiplied by -100)

**Comment by ValentinaPC** [comment]
As you can see, Is a newly submitted webextension with no abuse report or rejection.
Maybe the abuse report for me, as in the developer of the webextension?

**Comment by diox** [comment]
Ah, yes, abuse reports against the developer count as well.

**Comment by ValentinaPC** [comment]
> Ah, yes, abuse reports against the developer count as well.

Is there a way to delete abuse reports against developers?

**Comment by diox** [comment]
> Is there a way to delete abuse reports against developers?

Not that I know of. I can work on adding a quick and dirty admin in the django admin pages (/admin/models/) if that's a problem for you.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7) and obtained the following results:

1. **admin flag - is this possible before auto-approve if this is a mandatory criteria for an add-on to be auto-approve?**
1'. admin flag after auto-approve - does not make any changes on the weight
2. abuse reports - weight is incremented with 10 - **2 abuse reports to developer does not 
increment weight with 10 more, is this ok?**
3. negative ratings - weight is incremented with 2 for every negative reviews, including 3 stars - works as expected
4. add-on reputation - weight is incremented with: -100, -200, -300, 0, +100, +200, +300 depending 
on add-on reputation - works as expected
5. number of active users - 10k - tba
6. past rejection - weight is incremented with 10 for 1 rejection in the last year - 2 
rejections in the past year - will increment weight with 20 - work as expected
![priority](https://user-images.githubusercontent.com/15685960/26925729-8d003816-4c53-11e7-9dd6-3ef5e94302f1.png)


Note:
- this was tested while the developer had 2 abuse reports

**Comment by diox** [comment]
1. Yes, because in the future admin review will no longer prevent auto-approval. This is something you can't test right now, unfortunately, so you'll have to trust me :)
2. It should count (if the developer is a *listed* developer)

**Comment by ValentinaPC** [comment]
1. Will do this - I mean - trust you :)
2. There are listed 2 abuse reports on me - am I a **listed** developer?
![me](https://user-images.githubusercontent.com/15685960/26926559-e70efc72-4c56-11e7-917f-570868a0099c.png)

**Comment by diox** [comment]
Yes, but note that one of them is too old (April 4, 2016 - more than a year old) so it does not count.

**Comment by ValentinaPC** [comment]
Doh.

**Comment by ValentinaPC** [comment]
This can be marked as verified fixed due to above comments.
