### ISSUE TITLE
API allways return 404

### ISSUE THREAD

**Issue by goums** [mozilla/addons-server#5474]
I'm trying to connect to the addon store API, with a nodejs script, as described on the documentation:
http://addons-server.readthedocs.io/en/latest/topics/api/auth.html#example-request

I'm trying different endpoint but I keep getting a 404 NOT FOUND error.

Has the API url changed?
Am I doing anything wrong?

Here is the script I'm using:
```
"use strict";
const debug = require("debug")("firefox-plugin:uploader");
const jwt = require("jsonwebtoken");
const fetch = require("node-fetch");
const jwt_issuer = "user:xxx";
const jwt_secret = "xxx";

let issuedAt = Math.floor(Date.now() / 1000);
let payload = {
  iss: jwt_issuer,
  jti: Math.random().toString(),
  iat: issuedAt,
  exp: issuedAt + 60
};
let token = jwt.sign(payload, jwt_secret, {
  algorithm: "HS256" // HMAC-SHA256 signing algorithm
});

fetch("https://addons.mozilla.org/api/v3/accounts/profile/", {
  method: "GET",
  headers: {
    Authorization: "JWT " + token
  }
}).then(res => {
  debug(res);
});
```

Thanks in advance for your help

**Comment by goums** [comment]
I'm trying different endpoint, GET/POST, with/without data, but I always get:
`Body { url: 'https://addons.mozilla.org/api/v3/accounts/profile/', status: 404, statusText: 'NOT FOUND', ... }`

**Comment by eviljeff** [comment]
Fixed.  It'll be live on Thursday.
