### ISSUE TITLE
Use static analysis flags in post-review queue prioritization 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5475]
https://github.com/mozilla/addons-server/issues/5473 will implement the basic post-review queue prioritization that depend on a number of risk factors and associated weights.

This issue is for tracking additional factors that depend on static analysis flags. They are described in the [Post-review prioritization weights document](https://docs.google.com/spreadsheets/d/1CZEECHHqEmK87fNiWNslAsFQBL7zxYF-c63-zZVZuqw/edit#gid=0) under *Static analysis flags* and reproduced below. 

| Risk Factor | How much is an "instance"? | Value/instance | Min | Max | Issue |
| ----------- | -------------------------- | -------------- | --- | --- | ----- |
| eval, ~~evalInSandbox~~, document.write | One or more flags | 20 | 0 | 20 | https://github.com/mozilla/addons-linter/issues/1047 |
| setTimeout, setInterval, and on* attributes | One or more flags | 5 | 0 | 5 | https://github.com/mozilla/addons-linter/issues/1206 |
| <script> tag with a remote URL | One or more flags | 40 | 0 | 40 | https://github.com/mozilla/addons-linter/issues/1321 |
| Unsafe DOM: innerHTML | One or more flags | 20 | 0 | 20 |  https://github.com/mozilla/addons-linter/issues/1187 |
| Custom CSP | One or more flags | 30 | 0 | 30 | https://github.com/mozilla/addons-linter/issues/562 |
| Plain HTTP for sensitive operations | One or more flags | 20 | 0 | 20 | https://github.com/mozilla/addons-linter/issues/259 |
| Synchronous (non-local) HTTP requests | One or more flags | 5 | 0 | 5 |  https://github.com/mozilla/addons-linter/issues/1322 |
| Violate the Mozilla Conditions of Use | One or more flags | 20 | 0 | 20 | https://github.com/mozilla/addons-linter/issues/1285 |
| Require permissions that are not used | One or more flags | 10 | 0 | 10 | https://github.com/mozilla/addons-linter/issues/1286 |
| Native messaging | One or more flags | 20 | 0 | 20 | |
| Libraries and other unreadable code | One or more flags | 10 | 0 | 10 |  https://github.com/mozilla/addons-linter/issues/1323 |

Note that, because of the nature of static analysis, detection will not be 100% reliable.

**Comment by EnTeQuAk** [comment]
For what's needed in addons-linter:

* `eval, evalInSandbox, document.write` - #1047 - code: `DANGEROUS_EVAL`
* `setInterval, and on* attributes` - #1206 - code: `NO_IMPLIED_EVAL`
* <script> tag with a remote URL` -  needs issue filed, we only warn generally on `<script>` tags
* `Unsafe DOM: innerHTML` - #1187 - code: `UNSAFE_VAR_ASSIGNMENT`
* `Custom CSP` - #562 - code: `MANIFEST_CSP`
* `Plain HTTP for sensitive operations` - #259 - needs to be implemented
* `Synchronous (non-local) HTTP requests` - needs issue filed
* `Violate the Mozilla Conditions of Use` - #1285 - needs to be implemented
* `Require permissions that are not used` - #1286 - needs to be implemented, might be hard to do, easy to fool (imho)
* `Native messaging` - needs issue filed
` `Libraries and other unreadable code` - needs issue filed, vague description?

**Comment by diox** [comment]
Note: `nativeMessaging` does not need a linter issue for now, I'll just detect it from the permission list.

**Comment by diox** [comment]
Closing to be verified by QA, but it's still missing some flags that have not been implemented in the linter yet. See https://github.com/mozilla/addons-server/issues/5475#issuecomment-306451131 for the list of missing "needs to be implemented in linter" flags

**Comment by ValentinaPC** [comment]
@diox : I have the same question, like the one I've asked you in #5473, but now about "Custom CSP" flag... how it is possible to have an add-on **that uses a CSP**, auto-approved?
 I am very confused.

**Comment by diox** [comment]
@ValentinaPC it's not currently possible. It will be in the future though (because at some point in the near future we'll allow all webextensions to be auto-approved once they pass validation)

**Comment by ValentinaPC** [comment]
> @ValentinaPC it's not currently possible.

Can you help me with what is possible to be tested from that list?
Because I've tried with `eval` and using `content_scripts` in manifest interacts **again** with auto-approvals (https://addons-dev.allizom.org/en-US/editors/review/webext-eval) and weight cannot be calculated.
Thanks!!!

**Comment by diox** [comment]
Using content scripts is fine, it's just content scripts for *all URLs* that leads to no auto-approval right now.

From the list, here is what's currently implemented:
*  eval, evalInSandbox, document.write
* setInterval, and on* attributes
* Unsafe DOM: innerHTML
* Custom CSP **but you can't test it with auto-approval**
* Native messaging **but you can't test it with auto-approval**

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7) and obtained the following results:
- `eval` - https://addons-dev.allizom.org/en-US/developers/addon/webext-eval-test/edit - no changes for weight
- `document.write` - https://addons-dev.allizom.org/en-US/developers/addon/webext-eval-test/edit - no changes for weight

@diox : I guess that something happened while working on https://github.com/mozilla/addons-server/issues/5520 in what concerns the weight values.

**Comment by diox** [comment]
The linter is not returning what I expect. Re-opening.

**Comment by diox** [comment]
Depends on https://github.com/mozilla/addons-linter/issues/1355

**Comment by diox** [comment]
668f524afd33c7df9c909ce085d36917f27eef20 should have fixed that. Note that you'll need to upload new versions of your add-ons so that they're validated again. I did that for `Webext-eval-test` already, but feel free to do it again :)

**Comment by ValentinaPC** [comment]
Verified all 7 scenarios using AMO-dev FF54(Win 7) and obtained the following results:
1. `eval` - https://addons-dev.allizom.org/en-US/developers/addon/webext-eval-harm/edit
- warning at validation
![linter-eval](https://user-images.githubusercontent.com/15685960/27389430-09817b86-56a7-11e7-8c92-836524c12b59.png)
- weight incremented with 20

2. `evalInSandbox` - https://addons-dev.allizom.org/en-US/developers/addon/webext-evalinsandbox/edit
- no warning at validation
![evalinsandbox-no_warning](https://user-images.githubusercontent.com/15685960/27389486-33d8b12e-56a7-11e7-961c-8bdeb86ba6d1.png)
- **weight not incremented**

3. `document.write` - https://addons-dev.allizom.org/en-US/developers/addon/webext-docwrite/edit
- warning at validation
![docwrite-linter](https://user-images.githubusercontent.com/15685960/27389534-528a0730-56a7-11e7-8145-816e535950bf.png)
- **weight not incremented**

4. `setInterval` - https://addons-dev.allizom.org/en-US/developers/addon/webext-setinterval/edit
- no warning at validation
![no_warning-setinterval](https://user-images.githubusercontent.com/15685960/27389596-7667ebcc-56a7-11e7-8d31-a6ff8507cf2a.png)
- **weight not incremented**

5. `innerHTML` - https://addons-dev.allizom.org/en-US/developers/addon/webext-innerhtml/edit
- warning at validation
![linter-innerhtml](https://user-images.githubusercontent.com/15685960/27389633-9182a0b4-56a7-11e7-89f3-e77e013cf484.png)
- weight incremented with 20

6. `Custom CSP` - https://addons-dev.allizom.org/en-US/developers/addon/webext-csp/edit
- warning at validation
![linter-csp](https://user-images.githubusercontent.com/15685960/27389681-b7fe31cc-56a7-11e7-8c80-e86ce4fa48e7.png)
- weight is incremented with 30

7. `Native messaging` - https://addons-dev.allizom.org/en-US/developers/addon/webext-nativeperm/edit
- no warning at validation
- weight is incremented with 20

Screenshots from Reviewer Tools:
![csp](https://user-images.githubusercontent.com/15685960/27390196-58b3a2b8-56a9-11e7-97c1-f2e876b1ac44.png)
![doc-setint-sandb](https://user-images.githubusercontent.com/15685960/27390198-58b76f56-56a9-11e7-8dd1-8f4fad9a950c.png)
![harm-native-inner](https://user-images.githubusercontent.com/15685960/27390197-58b47f4e-56a9-11e7-8ac1-d2fa617670a1.png)

@diox - What should we do about 2, 3, 4?

**Comment by diox** [comment]
I'll look into those.

**Comment by ValentinaPC** [comment]
> I'll look into those.

Anything I can help, just give me a ping.

**Comment by diox** [comment]
Regarding `setInterval`, it's because your add-on was doing a `setInterval()` call with a function, which is not dangerous. It's only `setInterval("some string")` that is triggers the implied eval warning and weight, so that seems to behaves as expected.

The other points are valid, I'll fix them. (`evalInSandbox` might require a linter change)

**Comment by ValentinaPC** [comment]
Submitted the webextension (using `document.write()`) https://addons-dev.allizom.org/en-US/editors/review/webext-docwrite2 and got auto-approved after few minutes, but no trace of this webext in auto approved queue.... should I wait longer?
Thanks!

**Comment by diox** [comment]
I do see it in the list, it has a weight of 60.

**Comment by ValentinaPC** [comment]
Yes, seems like `document.write()` is working as expected.
Postfix screenshot: 
![docwrite](https://user-images.githubusercontent.com/15685960/27608401-1753747e-5b90-11e7-8eea-1868923e3f7f.png)
But, I am not able to obtain a correct weight for a webextension that uses `setInterval("some string") `
Created:
- https://addons-dev.allizom.org/en-US/editors/review/webext-setinterval5
- https://addons-dev.allizom.org/en-US/editors/review/webext-setinterval4
If are not created correctly could you give me a hand? maybe an example.
Thanks!

**Comment by diox** [comment]
In both these extensions `setInterval()` seems to be used with a function and not a string:
* https://addons-dev.allizom.org/en-US/firefox/files/browse/253338/file/enable.js#L5
```
setInterval(function () {
	    cur = div + 1;
	    $('#records_crawled').text(cur);
	    div = cur;
	    console.log(div);
	}, 2000);
```

* https://addons-dev.allizom.org/en-US/firefox/files/browse/253337/file/enable.js#L28

```
setInterval(randomQuote, 10000);
```

Instead you want something like `setInterval("randomQuote()", 10000)` for instance.

**Comment by ValentinaPC** [comment]
So.... I've tried using your example and I have two news: a bad one and a good one.
1. The good one is that a warning was generated while submitting a webextesion that uses `setInterval`
![warning](https://user-images.githubusercontent.com/15685960/27612331-b2158bd8-5b9e-11e7-9712-90a290e62cc1.png)
2. The bad one is that the weight is not incremented with **5**
![setinterval](https://user-images.githubusercontent.com/15685960/27612367-d8141548-5b9e-11e7-9d67-7063bea310bf.png)

**Comment by diox** [comment]
Sigh, I suck.

**Comment by ValentinaPC** [comment]
> Sigh, I suck.

Be positive! :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7). Using `setInterval` increments weight with 5, as expected.
Postfix screenshot:
![weight](https://user-images.githubusercontent.com/15685960/27662404-554ade26-5c66-11e7-8fe9-6cc625453bb2.png)

All possible scenarios were checked and this bug can be marked as verified-fixed.
