### ISSUE TITLE
Server error at add-on approval 

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#5484]
**Steps to reproduce:**
1.Navigate to https://addons-dev.allizom.org/ro/editors/queue/new
2.Try to approve an add-on.
 
**Expected results:**
The approval process is successfully completed.
 
**Actual results:**
Oops page is displayed.
 
**Additional notes:**
- This issue might be related to #5275
- This issue reproduces on AMO-dev using Firefox 55.0a1 (2017-05-23) under Windows 10 64-bit.
- Please see the attached video:

![animation](https://cloud.githubusercontent.com/assets/18114210/26404262/e7bf0d92-4099-11e7-9598-35ecbc752254.gif)

**Comment by muffinresearch** [comment]
I've asked ops to look into this since it looks to be a network issue looking at the sentry error: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/608691/

**Comment by muffinresearch** [comment]
@vasilicamihasca this should be fixed now the instance has been re-deployed.

**Comment by vasilicamihasca** [comment]
Verified fixed on AMO-dev using Firefox 55.0a1 (2017-05-24) under Windows 10 64-bit. The add-ons are successfully approved. See postfix screencast: 
![animation](https://cloud.githubusercontent.com/assets/18114210/26410851/1408e78e-40ad-11e7-89d6-a4fca38baa41.gif)
