### ISSUE TITLE
switch to yarn for our node dependencies

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5486]
It's the new shiny/stringy.

**Comment by eviljeff** [comment]
we should do https://github.com/mozilla/addons-frontend/issues/2431 too

**Comment by muffinresearch** [comment]
Most importantly verifying the lock file for yarn installs is necessary.

**Comment by eviljeff** [comment]
After reading https://mixmax.com/blog/to-yarn-and-back-again-npm I'm not sure if we should still do this.

**Comment by EnTeQuAk** [comment]
Probably not necessarily… npm has evolved massively in the last few years so I think an up-to-date npm should be fine.

**Comment by eviljeff** [comment]
let just do #7696 instead then
