### ISSUE TITLE
drop css and js pollyfill for old IE versions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5487]
from https://github.com/mozilla/addons-server/pull/5485#discussion_r118325940

> According to GA, overall IE usage is low, as expected. IE 11 is the highest by far (28K sessions), and 8, 9, and 10 are roughly on par (700 - 1K sessions).
> 
> So, I think IE 7 and older can be dropped with very little loss. IE 10 and older can also be dropped, if needed.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by eviljeff** [comment]
I don't think we generally test in non-Firefox browsers like IE so no specific QA needed, just watch out for general javascript errors throughout the site.
