### ISSUE TITLE
Mozilla extensions showing up in "Up & Coming"

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#5489]
### Describe the problem and steps to reproduce it:
I just loaded AMO and noticed that 2 of the entries under Up & Coming Extensions are "Search Shield Study" and "Firefox OnBoard".  I don't think either of these are intended to be directly installed by users.

### What happened?
see above

### What did you expect to happen?
These extensions shouldn't show up on the front page.  I guess ideally they would be unlisted but I presume that they are listed so that they can just be hosted on AMO.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
They're both intentionally listed. AMO is all or nothing, you can't get hosting without listing and showing up on various sections of the site.

**Comment by aswan** [comment]
So when I brought this up on IRC, @andymckay (I think it was him) asked me to file this here.  I think this needs addressing, it sounds like you think the shield/onboarding maintainers should make them unlisted and do their own hosting?

**Comment by jvillalobos** [comment]
If that's what meets their needs, yeah. But I know that at least in the Firefox OnBoard case I asked them specifically whether they wanted to be hosted and they said yes.
