### ISSUE TITLE
Empty string in "Add-on Reviewer Performance" from Reviewer Tools for users without display name set

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5491]
Steps to reproduce:

1. Go to Account Settings and delete your Display Name - https://addons.allizom.org/en-US/firefox/users/edit
2. Go to Reviewer Tools homepage and click on "Performance".
3. Click on the drop-down arrow button for "View statistics for user". 

Expected results:
Reviewer name are listed.

Actual results:
Empty strings are displayed for reviewers with no listed name.

Notes/Issues:
- Ihave a username set but is not used in that section.
Verified on FF53(Win 10 64Bit). Issue is reproducing on AMO-stage and -dev.
Screenshot for this issue:
![performance](https://cloud.githubusercontent.com/assets/28138132/26451630/916babea-4165-11e7-819f-8a82ba8e48ff.jpg)

**Comment by wagnerand** [comment]
Mentor: me (@wagnerand)

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by SVSanta** [comment]
Verified as fixed using AMO-dev FF55(Win 10 64Bit).
Postfix screenshot:
![clipboard01](https://cloud.githubusercontent.com/assets/28138132/26819669/92ce7b92-4aa8-11e7-9f8f-3b8d307f2b53.jpg)
