### ISSUE TITLE
Docker commands and Makefile do not work on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5495]
### Describe the problem and steps to reproduce it:
All of this is run inside [WSL](https://msdn.microsoft.com/commandline/wsl/about)
Run a `git clone` of addons-server, have Docker for Windows installed, and use `docker-compose.exe pull` and `docker-compose.exe up -d` to get the latest images and run the docker images.

After that, follow the docs and use `make initialize_docker`

### What happened?
The Makefile commands will fail because `docker.exe` is on the `$PATH` not `docker`.

If that issue is fixed, an error about input device not being a TTY will appear:

```
➜  addons-server git:(master) ✗ make initialize_docker
docker.exe exec -t -i "addonsserver_web_1" make initialize_docker_inner
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
Makefile:207: recipe for target 'initialize_docker' failed
make: *** [initialize_docker] Error 1
```

Running the command directly from a Windows shell instead of a WSL bash/zsh shell by copying the command in the Makefile will work.

### What did you expect to happen?
The command to work.

### Anything else we should know?
I'm running Creator's Edition, Ubuntu 16.04, and using ZSH fwiw.

**Comment by eviljeff** [comment]
Do the docker commands work if just entered directly?  (i.e. not using makefile).  I've been running AMO on Docker for a while, since before WSL was available, and I found all the docker stuff worked but there wasn't any makefile support natively in Windows.

**Comment by tofumatt** [comment]
If I run `docker.exe exec -t -i addonsserver make initialize_docker_inner` from WSL, sadly no. But I think that's a WSL bug:

```
docker.exe exec -t -i addonsserver_web_1 make initialize_docker_inner
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

And of course the command from the `Makefile` won't directly work because `docker` can't be found as it's `docker.exe` on Windows.

I think there's upstream stuff happening here too, but we aren't even able to get to the point of running the command right now.

FWIW if I run these commands from Windows Shell it's fine; that's what I've been doing but it'd be nice to be able to run them from WSL, where I do all my other work.

**Comment by eviljeff** [comment]
I've thought about replacing the makefile for external (non container) commands but I couldn't see a good cross platform alternative.   Likely wouldn't help your WSL problems though, which I guess are more about trying to run Windows stuff (Docker for Windows) via WSL.

**Comment by johnbindel** [comment]
Issue is with running Docker on WSL: https://github.com/docker/for-win/issues/1588

It appears to be an issue with WSL not supporting TTY for Windows executables. From what I can tell, the only working solution as of today is to set up a Docker client from inside WSL that accesses the Windows-hosted daemon via TCP without TLS.

Steps to set that up are here: https://medium.com/@sebagomez/installing-the-docker-client-on-ubuntus-windows-subsystem-for-linux-612b392a44c4

I'm really hoping for a better solution from the WSL team to come soon.
