### ISSUE TITLE
Remove extraneous data from URLs

### ISSUE THREAD

**Issue by Gitoffthelawn** [mozilla/addons-server#5505]
AMO adds extraneous data to the URLs, making bookmarking a nightmare.

For, example, from search, `?src=ss` gets added to the URL.

From updates, `?src=cb-dl-updated` gets added to the URL.

If the user bookmarks the former, and then later visits the identical extension via the recently updated AMO page, the FF UI will make it appear as though the item was never bookmarked.

If the user then bookmarks it from there, they will have duplicate bookmarks.

It was trivial to work around this issue using the [Redirector extension](https://github.com/einaregilsson/Redirector), but extensions like it are currently not allowed to work with AMO.  See https://github.com/einaregilsson/Redirector/issues/90 and https://bugzilla.mozilla.org/show_bug.cgi?id=1310082

**Comment by tofumatt** [comment]
Those URLs aren't extraneous, they're for analytics, as I understand it.

I am so rusty on analytics I can't recall if we could amend the URL with JS after it loads to get it out of the URL bar while still getting the analytics result we desire, but we could try that?

They do serve a purpose for us though, so we can't remove them right away, I think...

Though interestingly the addons-frontend doesn't use these anywhere. If those are all from internal links maybe we *don't* need them...

**Comment by Gitoffthelawn** [comment]
Thanks @tofumatt 

If data is being collected (and actually used), perhaps header referers could be used instead.

BTW, any idea if/how any analytics data is actually used?

**Comment by tofumatt** [comment]
No problem.

Yeah, it's possible we could be tracking things better. We are moving to a new frontend (https://github.com/mozilla/addons-frontend/) which won't add these query strings, for what it's worth 😄 

I'm not sure the specifics but I would imagine it's in the [Mozilla Websites Privacy Policy](https://www.mozilla.org/en-US/privacy/websites/). Sorry, I'm not very involved with the old add-ons server site and I'm not sure how it does analytics.

**Comment by Gitoffthelawn** [comment]
Thanks again @tofumatt 👍 

I don't see the info in the Privacy Policy, but I'm more wondering if/how anyone is actually using the data (as opposed to if they are allowed to collect it).  I wonder if the collected data is actually useful, or if collecting it could just be scrapped... thus simplifying all the URLs.

**Comment by diox** [comment]
It's used for both analytics and stats provided to add-on developers. 

You can see it in action on statistics pages like https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/downloads/sources/?last=30 : every different source in the legend corresponds to a `src` parameter. The full list of valid parameters is documented here: http://addons-server.readthedocs.io/en/latest/topics/api/download_sources.html

IMHO addons-frontend *should* use it, it's useful information. It could be done differently, but right now, we don't have an alternative that makes it work with both add-on stats exposed to developers and our private analytics.

**Comment by Gitoffthelawn** [comment]
@diox What about using header referers instead of URL params?

BTW, is it known if other devs actually use those stats for anything?  Personally, I've never found them useful.  It's a lot of info... but to what end?  I didn't find any of the information actionable.

**Comment by jvillalobos** [comment]
I know of many developers who look into these stats very carefully to see if there are ways they can improve the performance of their listing. AMO admins also use this sort of data often.

I agree that we should continue using something similar for the new front-end, since it's very valuable.

**Comment by Gitoffthelawn** [comment]
Thank you @jvillalobos .  Glad to know the data is being used.

What about the idea of using a referer instead of a URL param?

**Comment by jvillalobos** [comment]
That would be up to the engineers to figure out if it's a better solution.

**Comment by diox** [comment]
I do agree it'd be much better, but it would involve overhauling the stats pipeline and analytics, and that's a part of our architecture that's super old and not trivial to modify, so it's unlikely to happen any time soon.

**Comment by Gitoffthelawn** [comment]
@diox Thank you.  That's unfortunate, but understandable.  If you think of any other solutions, just let me know, and we can discuss it.

BTW, as a kludge, and certainly not an officially supported/recommended solution, would it be possible for me to use either:

 - https://addons.allizom.org/
or
 - https://addons-dev.allizom.org/

where I can freely use a WebExtension API extension to remove the source data?

**Comment by diox** [comment]
I don't understand your question. You can use addons.allizom.org (stage) or addons-dev.allizom.org (dev) for testing purposes, but it's not intended for end-users: data uploaded there may disappear or be modified without warning, and they use different signing certificates, making it impossible for users to install add-ons from those sites without some modification to their Firefox.

**Comment by Gitoffthelawn** [comment]
@diox Thanks.  That answers my question. :)

Just to learn more (and satisfy curiosity), how does one set up Firefox to use different signing certificates?  Is it documented somewhere?
