### ISSUE TITLE
Reviewer rejection box shows list for rejecting multiple versions.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5508]
### Describe the problem and steps to reproduce it:

When using the "Reject" (single version) action in the reviewer tools, it shows an empty list for selecting versions.

### Anything else we should know?

![screen shot 2017-05-29 at 11 48 50](https://cloud.githubusercontent.com/assets/873258/26545181/2f676172-4454-11e7-8321-9d516b2ba621.png)

**Comment by diox** [comment]
Not technically a regression since the field didn't exist before :)

**Comment by jvillalobos** [comment]
![62f538b129e13afc6c7d9b9278b63f63f4c91e1f8fd1077c36e088039bf538f8](https://cloud.githubusercontent.com/assets/62568/26545844/82ef48a6-4467-11e7-9810-8cc4f516b018.jpg)

**Comment by diox** [comment]
In addition, from QA feedback in #5275 , the following tweaks are required:
- Clarify in the description of the "Reject Multiple Versions" action that's it's limited to public versions. Also make sure it does not appear for the unlisted review page
- Make sure the same version does not appear twice in the list if it has multiple files (needs a `.distinct()`).

**Comment by wagnerand** [comment]
Meh!

The second line in the description above the versions list should also be hidden.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
- awaiting versions don't have multiple rejection option
![awaiting](https://cloud.githubusercontent.com/assets/15685960/26589263/3f6c7244-4560-11e7-90bf-391484b2381a.png)
- unlisted versions don't have multiple rejection option
![unlisted](https://cloud.githubusercontent.com/assets/15685960/26589474/d34ff490-4560-11e7-86b3-fac74268266e.png)
- second line from the rejection tab was removed and changed
![message](https://cloud.githubusercontent.com/assets/15685960/26589568/082e64b2-4561-11e7-9868-12421dfab4f7.png)
- empty box is not listed in the normal rejection tab
![2017-05-30_1756](https://cloud.githubusercontent.com/assets/15685960/26589941/ffac4b32-4561-11e7-9794-b3dc1c177127.png)
- versions with multiple files list once the version number in the multiple rejection tab
![2017-05-30_1804](https://cloud.githubusercontent.com/assets/15685960/26590144/7ee0c87e-4562-11e7-8b27-2cda9cc1dbac.png)
