### ISSUE TITLE
Docker hub build is failing due to ipdb version requiring python 3+

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5515]
The docker hub build started failing this morning with the following:

`The command '/bin/sh -c pip install 'ipython<6' ipdb supervisor' returned a non-zero code: 1`

Looking further into the logs shows:

```
Complete output from command python setup.py egg_info: error in ipdb setup command: Invalid environment marker: python_version >= "3.3" 
```

Whilst the ipython was pinned in https://github.com/mozilla/addons-server/issues/5380 it looks like ipdb need to be pinned too.

Link to build: https://hub.docker.com/r/addons/addons-server/builds/b4aqcobp2rcrvqqnpzwbb6e/

**Comment by muffinresearch** [comment]
Marking as high-priority since this will block the hub build from successfully completing.

**Comment by muffinresearch** [comment]
Looks like the latest ipdb is still 0.10.3 (2017-04-22) so this might need further investigation unless somehow we were pulling in an old version.

**Comment by EnTeQuAk** [comment]
ipdb is pulling in ipython which recently dropped python 3, I can take a
look at this in a few minutes

On Tue, May 30, 2017, at 03:40 PM, Stuart Colville wrote:
> Looks like the latest ipdb is still 0.10.3 (2017-04-22) so this might
> need further investigation unless somehow we were pulling in an old
> version.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons-server/issues/5515#issuecomment-304812704

**Comment by muffinresearch** [comment]
As noted by @eviljeff on irc both the failing builds are PRs. If the next latest build is fine then we can downgrade the priority of this.

**Comment by muffinresearch** [comment]
The latest build failed too: https://hub.docker.com/r/addons/addons-server/builds/bsc4chnatrgj52ryxfzlg7e/
