### ISSUE TITLE
Admin bulk compatibility validation page responds with 500.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5519]
I was about to run compat bulk validation.

https://addons.mozilla.org/en-US/admin/validation throws https://sentry.prod.mozaws.net/operations/olympia-prod/issues/609425/ 🚨.

**Comment by wagnerand** [comment]
This fails because there are some jobs in the `validation_jobs` which don't have a corresponding *appversion* (using `curr_max_version_id` and target_version_id`) anymore. Sadly those columns were not linked using a foreign key constraint, which caused this when we removed *Mobile* in https://github.com/mozilla/addons-server/pull/5367.

**Comment by diox** [comment]
```
<mat> TheOne: looks like we just need to remove the offending rows in validation_jobs ?
<TheOne> mat: yes, and ideally introduce the FK constraint so that it doesn't happen again
<mat> yeah good point
```

**Comment by wagnerand** [comment]
Since we don't have the needed data on -dev, I'm going to test this manually once it has been pushed to prod.
