### ISSUE TITLE
Allow admin to "vouch" for add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5520]
As part of the [prioritization of the post-review queue](https://github.com/mozilla/addons-server/issues/5473), we need to let admins vouch for add-ons. ~~Multiple admins can do it, decreasing the priority of the add-on in the queue each time, and we should have a simple way for an admin to add/remove their vouch.~~

~~It should probably live in admin tools somewhere.~~

It should be a simple integer field between 0 and 3 in the addon admin edit section in devhub. See below.

**Comment by wagnerand** [comment]
Not sure if this is clear from reading the plan: The feature is supposed to
work in both ways, meaning admins could also use it to *increase* the
priority.

Mathieu Pillard <notifications@github.com> schrieb am Di. 30. Mai 2017 um
16:33:

**Comment by diox** [comment]
mmm, the [implementation plan](https://docs.google.com/document/d/1rZvM2QGk8WtkNUDRvLEvrbqZ190hvHfOle4zVRllQmw/edit#) seems to contradict this:

> Add-on reputation is an admin-set override that helps rank down popular add-ons that are known to be high-quality and would generally rank higher due to code complexity and high volume of user feedback. This also includes add-ons developed by Mozilla.
> 
> The reputation is an integer ranging between 0 and 3, that is set per-add-on, defaulting to 0. It should be editable by admins in the Edit page for an add-on, in the Admin Settings section at the bottom. Each reputation point corresponds to a “vouch” by an admin, but the reputation field only corresponds to the total and any admin will be able to change it (the vouching process is manual, not something AMO will manage).

This is further confirmed by the [prioritization weights document](https://docs.google.com/spreadsheets/d/1CZEECHHqEmK87fNiWNslAsFQBL7zxYF-c63-zZVZuqw/edit#gid=0):

| Risk Factor | How much is an "instance"? | Value/instance | Min | Max |
| ----------- | -------------------------- | -------------- | --- | --- |
| Add-on reputation | 1 admin vouch | -100 | -300 | 0 |

**Comment by wagnerand** [comment]
Hm, weird.

@jvillalobos why not make this work both ways? Quite a few add-ons come to my mind where we'd generally want to have a closer look at submissions...

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7).
In the "Edit Information" of an add-on, 'Admin Settings" section there is a new "Add-on Reputation" field with different values.
![rep](https://cloud.githubusercontent.com/assets/15685960/26821894/bfc7779a-4ab0-11e7-8c55-eb253260ce0b.png)

1. All option work while selected
2. Is there a place where this reputation can be checked, beside dev hub?
3. Add-on position inside the auto-approved queue is not changed after a reputation is set, should it?

**Comment by diox** [comment]
2. No
3. It should change for future auto-approvals, per #5473

**Comment by ValentinaPC** [comment]
As per last 2 comments, we can mark this verified-fixed.

**Comment by jvillalobos** [comment]
> @jvillalobos why not make this work both ways? Quite a few add-ons come to my mind where we'd generally want to have a closer look at submissions...

The specification is correct. If an add-on should have a bad reputation, then that should be reflected on the other risk factors rather than admin opinion. If something isn't being covered in the risk factors (note that past rejections are included), then that's something that should be fixed in the prioritization, rather than a manual override.

Also note that the reputation points are extremely heavy-handed, so I'd rather not be using them in the opposite direction unless there's a really good reason for them.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Win 7).
On Edit Information page only positive reputation is displayed:
![onlypozitive](https://user-images.githubusercontent.com/15685960/27141369-a59e5b0a-5130-11e7-9918-eefa36280136.png)

But, on Auto-Approved queue, positive reputation is not added in weight :( (reputation was added while add-on was _awaiting review_)
![no-reputation](https://user-images.githubusercontent.com/15685960/27141420-c7a71d04-5130-11e7-936a-97fd23aef6c7.png)

Example: https://addons-dev.allizom.org/en-US/developers/addon/webext-pre3/edit

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Weight is incremented according to add-on reputation.
Postfix screenshots: 
![prioritate](https://user-images.githubusercontent.com/15685960/27337162-49d45c1c-55da-11e7-98ab-972c035e8e7d.png)
