### ISSUE TITLE
"View Mobile Site" link is not working on AMO-dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5522]
Steps to reproduce:
1.Go to AMO-dev
2.Click "View Mobile Site" link at the bottom of the page

Expected results:
Mobile view is correctly displayed

Actual results:
Top of the desktop page is displayed and a "#" is added to url

NOTES : 
Not reproducible on Stage

Please see video for this bug : 
![viewmobile](https://cloud.githubusercontent.com/assets/1583842/26591516/9707d9fc-4566-11e7-88be-110fbe827a7a.gif)

**Comment by muffinresearch** [comment]
This was due to the JS being broken - the patch was reverted so this should be resolved now.

Revert was in: https://github.com/mozilla/addons-server/commit/677f00a3df6aea0756a05d86e72393ada7830231

**Comment by vcarciu** [comment]
Verified as fixed : 
![vimob](https://cloud.githubusercontent.com/assets/1583842/26623993/34fa667a-45f8-11e7-8f2f-cc03d5a5a2c7.gif)
