### ISSUE TITLE
Reviewer reply vs need-info

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5536]
Currently, a reviewer reply that is sent using the review tools (website) is always an information request. However, there are a significant amount of cases where a reply does not ask for information but in fact answers questions from a developer.

We need a way to distinguish between regular replies and information requests. https://github.com/mozilla/addons-server/issues/5081 suggested to add a checkbox for a reviewer to tick if a reply is in fact an information request.

Information request emails also still have the old footer, which we probably can get rid of:
```
===================================================================
You received this email because you're subscribed to:
   * email me when Mozilla needs to contact me about my individual add-on


You can't unsubscribe from this type of email.

Manage email notifications: https://addons.mozilla.org/users/edit#acct-notify
```

**Comment by eviljeff** [comment]
The footer is because we pass `perm_setting='individual_contact' ` - it's not part of the template but added later in the `amo.utils.send_mail` and its supposed to added to all unsolicited emails.   If you want something changing around that log a different issue.

**Comment by wagnerand** [comment]
Ah. Interesting that none of the other comms emails use it.

**Comment by eviljeff** [comment]
Maybe we should that's why I want a separate issue - Jorge and others might have opinions.
