### ISSUE TITLE
Developer notification returns 500 in case user email is null.

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5544]
Sentry: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/379893/

So apparently the `UserProfile.email` is None and that's why the notification fails. I don't know yet why it's None, "It's a very old account from ~2012 I've started reusing recently if that helps." (quote).

**Comment by SamHH** [comment]
Hey, I'm the guy who reported this in IRC.

Username: `ClutchHunter`
Addon name: `Bukubrow`

Here is the updated ZIP I'm trying to upload just in-case it's helpful.

[bukurow-webext.zip](https://github.com/mozilla/addons-server/files/1044232/bukurow-webext.zip)

Cheers!

**Comment by eviljeff** [comment]
Part of the FxA login is matching/updating the email address so that's weird...  I'd put this under 'component: firefox accounts' - I think it's reasonable for all non-login related code to assume email is non-null.

**Comment by diox** [comment]
Hold on, which user is it failing for ? It looks like the problem is triggered when going through `EditorSubscription` instances, so presumably the `email` that is `None` is one of the subscribers, not the add-on author ?

**Comment by diox** [comment]
Yeah, that's it. I can reproduce locally. STR:
- Submit an add-on
- Approve it in reviewer tools with another user account, and subscribe to updates
- Somehow remove the email associated with the account you just used to subscribe (set to `None`)
- With the original user account (that does have an email), submit a new version, that crashes

We should ignore `EditorSubscription`s pointing to users with no email set. We should probably also look into removing them, though it could be useful to keep them for old logs ?

**Comment by eviljeff** [comment]
Ah.  Yes.  It's https://addons.mozilla.org/en-US/firefox/user/Anonymous-6307327/ - an editor that was previously involved in the thread whose account was subsequently deleted (soft deleted, where we anonymize, including clearing the email adddress).  The EditorSubscription record wasn't deleted though (because no cascade)

**Comment by wagnerand** [comment]
Hm, that user is no longer a reviewer. I think we could filter that early, to check whether the user we're going to send an `EditorSubscriptions` email really is a reviewer.

**Comment by muffinresearch** [comment]
Since this is blocking updates makeing this a p1.

**Comment by SamHH** [comment]
Still getting the `Oops! We had an error. We'll get to fixing that soon.` upon submission of my updated ZIP. Has this not made it into production yet?

**Comment by wagnerand** [comment]
We freeze the code every Tuesday and deploy every Thursday.

**Comment by vcarciu** [comment]
Verified as fixed by adding a new version to an extension approved by an user which was deleted after that : 
![n0500](https://user-images.githubusercontent.com/1583842/27088395-35ade49e-5060-11e7-82f0-7e8c1517d7a7.gif)
