### ISSUE TITLE
Update to Celery 4.x

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5549]
There's a massive amount of new features, cleanups and improvements in celery 4.x: http://docs.celeryproject.org/en/latest/whatsnew-4.0.html

We're currently using Celery 3.x and should upgrade to 4 eventually. Unfortunately there's quite a few blockers and things that need changing since it's not backwards compatible at all.

This issue is to track all tasks that should be done to achieve celery 4.x.

**Comment by diox** [comment]
This broke on dev, triggering tasks from a uwsgi worker seem to result in a 500: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/668681/

I'm strongly suspecting newrelic. I haven't tried it locally yet, but it works in a shell on dev, and newrelic does some deep monkeypatching of celery code (which we know is active in that traceback, we hit a log statement that says `newrelic.config instrument module (<module 'celery.app.task' from '/usr/lib/python2.7/site-packages/celery/app/task.pyc'>, 'newrelic.hooks.application_celery', 'instrument_celery_app_task')`)

**Comment by diox** [comment]
Reverted in https://github.com/mozilla/addons-server/commit/43d88b4f55bbbd5f138201fad72d26ec2132eb95

**Comment by EnTeQuAk** [comment]
Yeah… unfortunately the agent does not have it's repository or any issue tracker so this is hard to track down. Looking at https://github.com/edmorley/newrelic-python-agent/commits/master/newrelic/newrelic/hooks/application_celery.py (unofficial mirror) the celery agent hasn't seen any updates between releases.

On the other hand, newrelic doesn't contain the word `djcelery` anywhere so there must be something else at work here.

Investigating.

**Comment by diox** [comment]
The `djcelery` part is coming from celery itself: https://github.com/celery/celery/blob/6bdf5aea3a715734ccee75236389b11358c77c58/celery/loaders/__init__.py#L15

Maybe I'm completely wrong with newrelic, but my guess was that its monkeypatching threw something off in celery code that forced it to use a different path and end up with trying to use the `djcelery` loader.

**Comment by EnTeQuAk** [comment]
QA: Most importantly submitting new add-ons should continue to work since this is using asynchronous celery tasks in the background. Statistics are unfortunately hard to test on dev and stage but this update is most importantly an either it works or it doesn't update and add-on submission is one of our most complicated uses of celery so that should be fine for testing imho.

**Comment by vcarciu** [comment]
Auto-approval is not working anymore on -dev. After talking with @EnTeQuAk and @diox, it is related to this issue.
Reopening

**Comment by EnTeQuAk** [comment]
I opened https://github.com/mozilla/addons-server/issues/6690 for the specifics

**Comment by EnTeQuAk** [comment]
> Auto-approval is not working anymore on -dev. After talking with @EnTeQuAk and @diox, it is related to this issue.

This should be fixed in the next few minutes or so once the just merged fix from #6690 lands on -dev.

**Comment by EnTeQuAk** [comment]
All relevant issues are now fixed, I'm closing this again.

**Comment by vcarciu** [comment]
Auto-approval is now working and all scenarios related to new add-ons submissions and around worked.
Marking bug as verified.
