### ISSUE TITLE
Add a link to report a bug on github to the 500 error page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5551]
If a user comes across a 500 error, it would be helpful to both us and them if they could easily file an issue on github with the relevant information (incl. steps to reproduce and sentry information) from that 500 page.

I think @EnTeQuAk has some more insights here.

**Comment by EnTeQuAk** [comment]
Sentry supports ending the error event id to users: https://docs.sentry.io/clients/python/integrations/django/#message-references - we should do that and show that id to users, bold and large and make people include them.

That'd allow us to link issues to sentry and the other way around and simplifies the search for duplicates.

**Comment by harikishen** [comment]
I would like to help on this.

**Comment by aarushivij** [comment]
Hello, This shall be my first bug to contribute into moz add-ona
Can I work on it?
Also how can I get started? 
Thank you
Aarushi

**Comment by diox** [comment]
@jvillalobos can you provide some text to add to the 500 error page ? I guess we'll link to https://github.com/mozilla/addons/issues/new. The current content, for reference, is:
```html
<h1>Oops!  We had an error.</h1>

<p>We'll get to fixing that soon.</p>
<p>
  You can try refreshing the page, or head back to the
  <a href="{{ home }}">Add-ons homepage</a>.
</p>
```

@aarushivij : you can follow https://addons-server.readthedocs.io/en/latest/topics/install/docker.html to install addons-server environment locally. For this issue, once the text to add has been provided, you'll want to add it to [src/olympia/amo/templates/amo/500.html](https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/templates/amo/500.html)

**Comment by aarushivij** [comment]
Okay @diox I shall set up the environment first and then move forward with the issue.
Thanks :)

**Comment by jvillalobos** [comment]
```html
<h1>Oops!  We had an error.</h1>

<p>We'll get to fixing that soon.</p>
<p>
  You can try refreshing the page, or head back to the
  <a href="{{ home }}">Add-ons homepage</a>. You can also help us fix this by 
<a href="https://github.com/mozilla/addons/issues/new">filing an issue</a> with the 
details of how you got to this page. Make sure to include this error reference number: {{ ref }}.
</p>```

I'm not sure if the error reference @EnTeQuAk mentioned is out of scope for this issue. If so, we can just drop the last sentence.

Looks good, @caitmuenster?

**Comment by wagnerand** [comment]
We could make use of the `title` and `body` GET parameters to the `.../new`link to pre-fill some information, for example the reference.

Example link: https://github.com/mozilla/addons-server/issues/new?title=Server%20Error&body=Reference%20No:%20...

**Comment by jvillalobos** [comment]
That would kill the template text, no? Though I suppose we can include that in the body too...

**Comment by caitmuenster** [comment]
@jvillalobos Text LGTM!

**Comment by varunbankar** [comment]
@diox I set up the dev environment, made the change but how do I view the error 500 page?
I read the documentation and going to `/services/500` did not work.

**Comment by caitmuenster** [comment]
Mentor: @diox 

@varunbankar, were you able to figure out how to view the 500 error page?

**Comment by richard-hutchings** [comment]
Hi is this a good issue to work on as an outreachy. i would like to work on it if so.
regards
Richard

**Comment by diox** [comment]
Hi, someone has already submitted a pull request for this.
