### ISSUE TITLE
Developer reply does not clear 'need-info' flag

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5554]
### Describe the problem and steps to reproduce it:

At least in some cases (if not all), when a developer replies to a message from a reviewer, the *need-info* flag does not get dropped.

STR:
1. As a developer submit an add-on.
2. As a reviewer, do a "reviewer reply" on the review tools page. The add-on should have the "information requested" flag afterwards.
3. As the developer, reply to the reviewer message, either using email or AMO devhub.

### What happened?

The need-info flag is still set after the developer reply.

### What did you expect to happen?

It should have been dropped.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Nah.

**Comment by ValentinaPC** [comment]
Verified on AMo-dev FF53(Win 7).
Flag is cleared after page refresh.
Postfix video:
![flag](https://user-images.githubusercontent.com/15685960/26928441-c7d81ebc-4c5e-11e7-9f5b-1dc89e641895.gif)
