### ISSUE TITLE
Remove unused js libraries

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5572]
Part of #5458

There shouldn't be any impact, but watch out for random javascript errors throughout the site.

**Comment by ValentinaPC** [comment]
This error while clicking on an add-on/theme name in View Mobile Site mode, can be related?
![first_click](https://user-images.githubusercontent.com/15685960/26973888-56cf86f6-4d21-11e7-8cfd-d1282b189617.png)

**Comment by eviljeff** [comment]
No, this doesn't affect addons-frontend pages.
