### ISSUE TITLE
Remove legacy devhub index page

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5582]
Our new devhub pages landed with mozilla/addons-frontend#1021 but our old index page is still in our code.

* [ ] Remove `devhub/index.html` - or replace it by the new index.html
* [ ] Add migration to remove waffle flag.
* [ ] Find unused css and images and remove them

**Comment by ValentinaPC** [comment]
Navigating through Dev Hub will be enough while checking this?
Thanks!

**Comment by EnTeQuAk** [comment]
Yes, sorry for the missing notes.

The code that got removed should have been unused since either February (old devhub index page) or much much longer (some of the images / css) so generally, yes, navigating through devhub pages should verify this being fixed. Maybe a closer look at any potential missing images in the network tab but that's it.

Thanks!
