### ISSUE TITLE
Add-on browser incompatibility red mark is not RTL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5590]
Steps to reproduce:
1. Load a page for an add-on that is not compatible with your Firefox version and change the language to a RTL one i.e. https://addons.allizom.org/ar/firefox/addon/tlegacy-versioncomapt/
2. Observe the incompatibility red mark 

Expected results:
Red mark is RTL.

Actual results:
Red mark is not RTL.

Notes/Issues:
Verified on AMO-stage FF53(Win 7). Issue is reproducing on all AMO servers.
Screenshot:
![rtl](https://user-images.githubusercontent.com/15685960/26884614-d211be12-4ba8-11e7-96d5-8d1f10081ffd.png)

**Comment by muffinresearch** [comment]
@ahmedhasan07 did you make a start on this? If not we're probably going to reduce the priority on this since a new frontend is coming in q4.

**Comment by ValentinaPC** [comment]
Verified as fixed in AMO-dev FF54(Win 7).
Postfix screenshots for bot platform and browser incompatibility red mark:
![platform](https://user-images.githubusercontent.com/15685960/28462708-04b612d4-6e25-11e7-8eda-546cd7cac43e.png)
![redmark](https://user-images.githubusercontent.com/15685960/28462707-04b36b24-6e25-11e7-864b-cb0586e02756.png)
