### ISSUE TITLE
Small format issue for add-on browser incompatibilty tooltip 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5591]
Steps to reproduce:
1. Load https://addons.allizom.org/fr/firefox/addon/tlegacy-versioncomapt/
2. Click on the "`?`"

Expected results:
There are no layout issues.

Actual results:
There is a small format issue.

Notes/Issues:
Verified on AMO-stage FF53(Win 7). Issue is reproducing on all AMO servers.
Screenshot: 
![2017-06-07_1736](https://user-images.githubusercontent.com/15685960/26885288-f0eceddc-4baa-11e7-97ee-d98697d44b1e.png)

**Comment by EnTeQuAk** [comment]
This is only because the space before the colon in our french translation is not a non-breaking-space, I'll try to fix that via Pontoon and see where how it goes.

**Comment by EnTeQuAk** [comment]
submitted a suggestion to the french translation, let's see if that get's accepted.

**Comment by diox** [comment]
This popup will go away in #6028

**Comment by ValentinaPC** [comment]
This was fixed by removing the popup in #6028 .
Marking verified fixed.
Postfix screenshot:
![fr](https://user-images.githubusercontent.com/15685960/28781902-4baaa154-7614-11e7-9b0f-040ab43dad2a.png)
