### ISSUE TITLE
Don't link to user account profiles for non-developers in the API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5592]
Edited to focus this issue on just stop including the user profile url in the API responses.

Follow up issues to this:
- [ ] make the accounts API 404 for non-developer users, except for admins and your own account #6042
- [ ] stop including links to the user profile on other pages. #6044

**Comment by eviljeff** [comment]
@jvillalobos can you confirm about timing on this - do you only want it to happen when we have addons-frontend serving user profiles for both mobile and desktop?  Or are you okay with us stopping linking to profiles gradually? Would you want the existing user profile pages (i.e. the ones we serve from addons-server now) blocked as well before the addons-frontend user pages are implemented?

**Comment by jvillalobos** [comment]
I'm okay with stopping the linking gradually. The first point (make the accounts API 404 for non-developer users) should only be done in the new front end, since it's a bigger change that should be announced.

**Comment by eviljeff** [comment]
Do we want to stop linking to profiles in certain _places_ (i.e. APIs) or try to selectively include the profile url in the API depending on the user?  Example:
user review page -  should we 
a) exclude the url for all reviews?  
b) only include the url for developer replies (developer of that add-on) 
c) determine if the profile should be included by seeing if they are have any listed add-ons (they're a developer)

(a) is the easiest and least fragile - the more clever we try to make it, the more edge case bugs they'll be.

**Comment by eviljeff** [comment]
@tofumatt for the api consumption

**Comment by tofumatt** [comment]
(c) is definitely the best option for the front-end–the API should be able to tell/mark a user as "having a public profile" and I think if it isn't public (eg will result in a 404) we shouldn't get it in the response. That would also allow for authenticated requests (admins or something) to get URLs in the response... rather than just never showing the info. If a developer leaves a review and they have a profile we should link to it, it's handy.

More work, sadly 😅

**Comment by eviljeff** [comment]
The implementation isn't really more work - I can just change the main Serializer and every response gets the correct profile url, or not ... but I'm currently trying to avoid having to do an extra query for each review in the response because we don't store if a user is developer - it takes a query to find out.

**Comment by eviljeff** [comment]
The compromise I came up with skips the full database query in a few places:
* we assume all authors of an add-on are a developer (obvious) so include the url
* we assume all replies to a review are from a developer so include the url, because only they can reply.
* we assume all reviews _aren't_ from a developer, because they shouldn't (can't?) write a review on their own add-on, so don't include the url.  This also means a developer of a different add-on writing a review doesn't get special treatment and have their url shown.

All APIs will return the account profile url when:
* it's your account being referenced in a serialized response (e.g. your own review, your own activity, etc)
* you have admin super powers.

**Comment by tofumatt** [comment]
> we assume all reviews aren't from a developer, because they shouldn't (can't?) write a review on their own add-on, so don't include the url. This also means a developer of a different add-on writing a review doesn't get special treatment and have their url shown.

But I would *want* a review from a developer to shown a link to their profile. To start with, it's good to link across pages on the site, but also I think giving a developer who is probably more of an advanced user special treatment (and also a bonus link to their profile to advertise their own add-ons) is a good thing.

**Comment by eviljeff** [comment]
The test is basically 
```
if obj == current_user or is_developer() or is_admin():
     return absolutify(obj.get_url_path()
)```
where we cheat with `is_developer` in the places I mentioned in the previous comment to avoid extra DB queries.

**Comment by eviljeff** [comment]
> But I would *want* a review from a developer to shown a link to their profile. To start with, it's good to link across pages on the site, but also I think giving a developer who is probably more of an advanced user special treatment (and also a bonus link to their profile to advertise their own add-ons) is a good thing.

I don't agree with your conclusion that submitting an add-on (literally **any** add-on) makes you inherently more worthy of special treatment.  Even if so, we're talking an extra query per review.  So 25 extra database queries per 25 reviews returned in a page (the current serializer takes up to 7, depending on replies.  So up to 32)

**Comment by tofumatt** [comment]
The link to a developer account drastically improves trust/verification though. Let's say I change my display name to AgileBits or some other prominent developer's name and start posting reviews. The link to the profile will allow someone to see if it's the real developer or not.

**Comment by tofumatt** [comment]
I mean I guess that's an issue in general... without links to profiles the effort to impersonate someone has gone way down.

**Comment by eviljeff** [comment]
Lets say you change your name to AdblockPlus, upload a theme, and start posting AdblockPlus reviews.  The fact you have a linked profile makes it _more_ misleading.  You could have your malware infested fork listed in your profile too.  If only the developers of that add-on, and admins, had profile links it would indicate if it was one of the developers.

**Comment by eviljeff** [comment]
@jvillalobos had it in the Desktop Scoping PRD so he'll can make the call 😛 
If it's desirable to link to account profiles in all reviews then that's what we'll do, and have to work out how to optimize the database queries (or live with the inefficiency).

**Comment by tofumatt** [comment]
Hmmm, neat idea. Eventually we might want some kind of "verified developer badge" or whatever but now I'm way off topic.

Okay your point convinced me, your way sounds good! Only he add-on's developer gets a link in reviews. 👍🏻

- Matthew Riley MacPherson (sent from mobile)
