### ISSUE TITLE
Accounts API page is a bit long

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5597]
Lets move the collections to a separate page.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by eviljeff** [comment]
The docs are http://addons-server.readthedocs.io/en/latest/topics/api/accounts.html and http://addons-server.readthedocs.io/en/latest/topics/api/collections.html but I don't think there's much for you to do there.
