### ISSUE TITLE
Update text for developer notification checkbox "add-on events and contests"

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#5600]
Currently, developers see these notification options when they edit their account settings on https://addons.mozilla.org/en-US/firefox/users/edit: 

![notifications](https://user-images.githubusercontent.com/23342476/26902212-3dbc2074-4b8d-11e7-9742-7ff42572b5cc.png)

Following a discussion with @amyt and @jvillalobos, we would like to update the text next to the box  "add-on contests or events are announced" to "stay up to date with news and events relevant to add-on developers." 

Whatever parameter is being passed in the backend can stay the same; we just want to change the text associated with that box. 

Users who opt in to this box will be added to the subscription list for the about:addons newsletter. 

Thank you!

**Comment by jvillalobos** [comment]
@atsay is the `amyt` you want :P

**Comment by atsay** [comment]
Let's not leave out the hyphens, and take out the period to stay consistent: "stay up-to-date with news and events relevant to add-on developers"

**Comment by eviljeff** [comment]
@jvillalobos can you confirm the defaults for all of them too?  As I noted on irc yesterday, the developer notifications are only defaulting to `false` because the form is broken (in _another_ way)

**Comment by jvillalobos** [comment]
I'm thinking only the "events" checkbox (the one this bug is for) should be off by default.

There are a couple of settings we should revisit in other issues:

1) Compat and SDK settings won't be needed after the bulk compat check for 56, in a few weeks.
2) "new add-ons or Firefox features are available" is for contacting all registered users for marketing reasons. Not sure if we'll ever need to do this, especially considering our millions of incredibly old or mostly spam user accounts.

**Comment by atsay** [comment]
I want to keep #2 as a lifeline to communicate to all registered users, should the need arise. Agree the "Events" box should be unchecked by default.

**Comment by vcarciu** [comment]
Verified as fixed : 
![usernotif](https://user-images.githubusercontent.com/1583842/27085566-4f7900fa-5058-11e7-84a6-7fb024068942.png)

@eviljeff 
Not sure about the "New" red text , is this present because I newly created this account and submitted an extension?

**Comment by eviljeff** [comment]
Yes.  It's shown when the notifications are being set for the first time.

**Comment by vcarciu** [comment]
Thanks

**Comment by caitmuenster** [comment]
Brian Smith just advised that we revise the opt-in language from "stay up-to-date with news and events relevant to add-on developers" to "stay up-to-date with news and events relevant to add-on developers (including the about:addons newsletter). 

Any chance we could get this patched by Aug 2?

**Comment by caitmuenster** [comment]
Per @eviljeff's advice, I'm opening a new issue.
