### ISSUE TITLE
Add basic admin for abuse reports

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5601]
QA asked for a way to delete abuse reports in #5473 ; it might prove useful for admins too in the future, to delete spam.

**Comment by ValentinaPC** [comment]
@diox : I searched around Admin Tools page for the implementation and did not find anything new.
Can you enlighten me? :) Thanks!

**Comment by diox** [comment]
It should be in https://addons-dev.allizom.org/en-US/admin/models/ but unfortunately dev seems to be lagging behind at the moment so you can't access it :(

**Comment by ValentinaPC** [comment]
I am a patience woman. :)

**Comment by diox** [comment]
Dev is now fixed.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
The Abuse Reports page is available and functional in Admin Tools page.
Postfix screenshot:
![abuse-rep](https://user-images.githubusercontent.com/15685960/27022964-196623e4-4f59-11e7-9c84-c9688a667dbb.png)
