### ISSUE TITLE
Don't show "Confirm approval" for pending versions.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5604]
If the latest submitted version is pending review, we shouldn't show the "Confirm approval" action.

**Comment by ValentinaPC** [comment]
@wagnerand : I have a question for you. :) 
If the add-on has last version "awaiting" and the previous "auto approved" the "Confirm approval" action should not be possible for the last **public** version than after approving the awaiting version?
Thanks!

**Comment by wagnerand** [comment]
Well, I think this is a stop gap only until we roll out post review.

I don't think we need to show the "Confirm approval" action because the latest version is pending review which can mean two things:
1) Either it hasn't been auto-approved yet, so humans should wait until the auto-approval task ran.
2) It failed the auto-approval criteria, which means it needs to be reviewed by a human.

So for 1), we will show "Confirm approval" **after** it has been auto-approved.
For 2), a human reviewer needs to look at this either way, so it don't think it's a good use of a human's time to look at an old auto-approved version when they have to look at the newest pending version anyway.

**Comment by ValentinaPC** [comment]
As far as I know the "Confirm approval" option, if made, is applied to last _public_ version that was auto approved, even if the last _submitted_ version is **awaiting**. 

Thanks for your reply!

**Comment by wagnerand** [comment]
Yeah, that's probably right. But it doesn't make much sense to confirm an old version if a new one is pending.

**Comment by diox** [comment]
Note: per discussion in #5609 we do want to keep the action for unlisted versions (even though they are technically not "public").

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Postfix screenshot:
![2017-06-14_1851](https://user-images.githubusercontent.com/15685960/27142150-e4a91efa-5132-11e7-9b50-9c119bc9fb72.png)
