### ISSUE TITLE
Add additional analytics tool to AMO for experiment

### ISSUE THREAD

**Issue by chrismore** [mozilla/addons-server#5608]
The Firefox Growth team would like to perform an experiment and we need assistance of the AMO team to perform it.

Here's what we need:

1) In this file:

https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/analytics.js

2) Add this code:

```
<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=11365629; 
var sc_invisible=1; 
var sc_security="d1b4d3fb"; 
var sc_client_storage="disabled"; 
var sc_https=1; 
var sc_remove_link=1; 
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript><div class="statcounter"><img class="statcounter"
src="//c.statcounter.com/11365629/0/d1b4d3fb/1/" alt="free
web stats"></div></noscript>
<!-- End of StatCounter Code -->
```

In StatCounter's admin interface, cookies have been disabled and all IPs are masked per our privacy policy.

3) Wrap the code in step 2 with JS that only execute the code above at a 30% sample. i.e. Random number from 0-1 and only execute when the number is < 0.3.

4) Deploy this site-wide for all visitors.

5) Let us know once it is has been deploy and we will monitor the experiment via StatCounter's admin interface. 

Thanks and let me know if you have any questions. You can ping :cmore on Slack or IRC.

**Comment by jvillalobos** [comment]
Are there any documents you can point to so we can understand the motivation and goals behind this request? Is this a temporary change?

/cc @deadsquid

**Comment by chrismore** [comment]
TBD on how temporary. Let me talk to @deadsquid and osunick about it as they know the back story.

**Comment by chrismore** [comment]
Also, /cc @andymckay

**Comment by muffinresearch** [comment]
Couple of immedidate questions aside from understanding the background. This snippet contains HTML with a `<noscript>` image beacon fallback so we can't just put this verbatim inside  `analytics.js`. 

Is the no-js fallback required?

Using this in HTML would violate our Content Security Policy (CSP) too. Afaik `document.write` is not allowed to add script even if running from a JS file allowed by the `script-src` without `unsafe-inline` being added and that would cripple the CSP so we'd not want to go in that direction.

**Comment by chrismore** [comment]
There is a no-JS version, let me drop that into here too. When we added this to www.mozilla.org, we had to adjust the CSP rules.

**Comment by chrismore** [comment]
non-JS version:

<div id="statcounter_image" style="display:inline;"><img
src="//c.statcounter.com/11365629/0/d1b4d3fb/1/" alt="StatCounter stats" style="border:none;" /></div>

**Comment by chrismore** [comment]
@muffinresearch here's a few PRs to add StatCounter and adjust the CSP on mozilla.org for this same type of test:

https://bugzilla.mozilla.org/show_bug.cgi?id=1352821#c15

CSP fix:

https://bugzilla.mozilla.org/show_bug.cgi?id=1352821#c16

**Comment by deadsquid** [comment]
I'd like to do what we can to enable this experiment to help us validate our analytics platform against /compare them to third-party services like StatCounter. Stuart, I'd like to enable this as soon as we can. From the convo we'd: i) use the non-js version (image load) ii) modify the CSP to allow for that image and iii) add a throttling mechanism so that only x% of AMO page loads 

What's needed from a requirements side to move forward, and are there additional discussion items that need to be addressed?

**Comment by muffinresearch** [comment]
@deadsquid hi, sorry missed the mention on this one. We'll enable this on amo for next week's push. We'll also need to look at enabling this on the mobile/new desktop site although that might take a bit longer since we don't have mechanism for limiting to x% of users yet.

**Comment by muffinresearch** [comment]
@deadsquid I'm going to close this for now since we don't need this anymore based on the recent email thread - but if that changes this can be re-opened.
