### ISSUE TITLE
Confirm approval option available in "Unlisted Review Page"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5609]
Steps to reproduce:
1. Load "Unlisted Review Page" for an auto-approved add-on i.e. https://addons-dev.allizom.org/en-US/editors/review-unlisted/webext-simple
3. Observe the options for Add-on history section

Expected results:
No "confirm approval" option.

Actual results:
Confirm approval option is available.

Notes/Issues:
- confirm approval action will be recorded in the Review **Listed** Page
- issue is reproducing for _all versions listed_ add-on
Verified on AMO-dev FF53(Win 7). Issue is reproducing on stage and dev.
Video for this issue:
![confapprov](https://user-images.githubusercontent.com/15685960/26971641-a4dd9456-4d16-11e7-983d-d835ade2037c.gif)

**Comment by wagnerand** [comment]
I'm wondering whether that's something we'd explicitly want. It certainly seems useful and superior to commenting "ok", which is what the current process looks like.

@jvillalobos thoughts?

**Comment by jvillalobos** [comment]
Agree. The unlisted process should largely mimic the post-review process, though we don't have short-term plans to dedicate time to it.

**Comment by diox** [comment]
Closing the issue then because otherwise it becomes confusing :)

**Comment by ValentinaPC** [comment]
@diox:  this issue was not just for an unlisted review page having a "confirm approval" option, but for that action done in the _unlisted review page_ and _recorded in the listed review page_, as you can see in my notes.

**Comment by diox** [comment]
True. That will be fixed as well when I tweak this action for #5604

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7)
Approval confirmed for unlisted will be stored in the unlisted review page.
Postfix screenshot:
![unlisted_pages](https://user-images.githubusercontent.com/15685960/27134569-a682be7e-511e-11e7-8bbf-aedd3ffd7c23.png)
