### ISSUE TITLE
Scroll click on “Report Abuse” link opens “AMO Contact Information” MDN page

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#5611]
**Steps to reproduce:**
1.Navigate to https://addons-dev.allizom.org/en-US/firefox/addon/bloody-vikings/
2.Scroll click on “Report Abuse” link.
 
**Expected results:**
a) The add-on listing page is opened in a new tab just as “Permissions” link does.
b) Report abuse page is opened in a new tab ( https://addons-dev.allizom.org/en-US/firefox/addon/bloody-vikings/abuse/ )
 
**Actual results:**
AMO Contact Information MDN page is loaded in a new tab ( https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact )
 
**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 55.0a1 (2017-06-08) under Windows 10 64-bit.
- Please see the attached video:
![animation](https://user-images.githubusercontent.com/18114210/26974981-7e9d4dee-4d26-11e7-996d-4f3839781808.gif)

**Comment by EnTeQuAk** [comment]
@wagnerand or @jvillalobos should this be changed? This is going to change with the new addons-frontend desktop work very soon anyway so I assume it's worth closing if no one as any concerns doing so.

**Comment by wagnerand** [comment]
I think this should point to the *report abuse* page, but @jvillalobos might know what's going on.

**Comment by EnTeQuAk** [comment]
Fair warning: As far as I see this link as been like this since forever unless I'm blind and can't read git blame 🤔

**Comment by wagnerand** [comment]
That would explain why we get so many user abuse reports that complain about a certain add-on.
But we do get add-on abuse reports too! How do users reach that page?

**Comment by jvillalobos** [comment]
It's definitely a bug, though I agree not a high priority. Is it a good first bug? Maybe an easy fix for someone who wants to contribute.

**Comment by vcarciu** [comment]
@jvillalobos 
Report form will be opened in a pop-up window . Is this correct? : 
![abusereport](https://user-images.githubusercontent.com/1583842/27870089-95b75798-61aa-11e7-83e1-1523f9cf939f.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![scrollclick](https://user-images.githubusercontent.com/1583842/27870783-78e34e2c-61ac-11e7-9a2a-e1a8c34f9aca.gif)
