### ISSUE TITLE
"Not Auto Approved Because" message is not listed for popular add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5612]
Steps to reproduce:
1. Submit a new version that qualifies to be auto-approved for a webextension with over 10k active users i.e. https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/
2. Observe the "Not Auto Approved Because " message

Expected results:
O corresponding message is displayed.

Actual results:
No message is displayed.

Notes/issues:
- initially the "Not Auto Approved Because " was that the script was not run yet, and after run, no other message was displayed.
Verified on AMO-dev FF53(Win 7).
Screenshot for this issue:
![no_reason](https://user-images.githubusercontent.com/15685960/26977217-b43b87a0-4d2f-11e7-837d-771c4950439c.png)

**Comment by diox** [comment]
I can reproduce and I have no idea what's going on yet...

Everything works as expected in a shell:
```
>>> addon = Addon.objects.get(slug='awesome-screenshot-plus-')
>>> version = addon.versions.all()[0]
>>> version.get_channel_display() 
u'Listed'
>>> version.is_public()
False
>>> version.was_auto_approved
False
>>> a = AutoApprovalSummary.objects.get(version=version)
 a.calculate_verdict()
{'has_info_request': False, 'uses_native_messaging': False, 'too_many_average_daily_users': True, 'is_locked': False, 'uses_content_script_for_all_urls': False, 'too_few_approved_updates': False, 'is_under_admin_review': False, 'uses_custom_csp': False}
>>> a.calculate_verdict(pretty=True)
<generator object <genexpr> at 0x40eca00>
>>> list(a.calculate_verdict(pretty=True))
[u'Has too many daily users.']
```

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Postfix screenshot:
![2many](https://user-images.githubusercontent.com/15685960/27141774-c5c3d90e-5131-11e7-87a3-8adfb85093be.png)
