### ISSUE TITLE
Review disappeared

### ISSUE THREAD

**Issue by gkratoc1** [mozilla/addons-server#5614]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
I reviewed the MetaMask addon.  I went to the review's static link and it was gone.
### What did you expect to happen?
I expected the review to load.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/reviews/880762/
Did Mozilla or the publisher take down my review?

**Comment by wagnerand** [comment]
It was probably flagged for moderation and deleted by the moderator.
