### ISSUE TITLE
Don't sign Mozilla Signed Extensions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5619]
[Mozilla Signed Extensions](https://wiki.mozilla.org/Add-ons/InternalSigning) are internal add-ons that will be signed using a different signature than the one used on AMO. While generally they won't be distributed on AMO, some people have shown interest in doing so because of the facilities AMO provides (auto-updates and statistics, mainly).

If one of these extensions is submitted, we should do two things:

1) Don't allow submission unless the owner has a Mozilla email address (#4688 is similar, but it's only based on the add-on ID). 
2) Once the add-on passes all checks, it shouldn't be signed again. We did a similar thing for the Hotfix add-on, but I don't know if we made the exception by ID or by the detected signature. The latter would be ideal for this new kind of add-on.

@andymckay: what would be look for in the signature to identify these add-ons?

**Comment by andymckay** [comment]
Here's an example, basically you are looking for a specific OU in the signature along with the specific key information. Definitive information on that will be in the Firefox tree and @aswan can point you at that.

**Comment by andymckay** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1369532

**Comment by muffinresearch** [comment]
@eviljeff, since you worked on #4688 would you be able to look into providing a rough idea on how much work this would take?

**Comment by eviljeff** [comment]
@jvillalobos
> Don't allow submission unless the owner has a Mozilla email address (#4688 is similar, but it's only based on the add-on ID).

To confirm, the _only_ criteria for these "Mozilla Signed Add-ons" is the OU in the signature? 

> Once the add-on passes all checks, it shouldn't be signed again.

What are the "all checks" - is this add-on to treated normally except for not-resigning at the end? 

>  We did a similar thing for the Hotfix add-on, but I don't know if we made the exception by ID or by the detected signature. The latter would be ideal for this new kind of add-on.

The Hotfix add-on exception is made by a hard-coded list of two guids, one for the Firefox Hotfix, one for TB. Is there a plan to move the Hotfix add-on to this same signing method too?

**Comment by andymckay** [comment]
The Hotfix is going to be removed completely and instead will use system add-ons https://wiki.mozilla.org/Add-ons/HotfixRemoval.

**Comment by eviljeff** [comment]
> The Hotfix is going to be removed completely and instead will use system add-ons https://wiki.mozilla.org/Add-ons/HotfixRemoval.

I can remove the Hotfix handling while I'm at it then, I guess?  (i.e. "going to be" has already happened, or will coincide with this issue being implemented)

**Comment by eviljeff** [comment]
Regardless of outstanding questions, in terms of difficultly, this shouldn't be complicated.  Assuming [signing-clients](https://github.com/mozilla/signing-clients) supports getting `OU`, anyway.  When this goes ahead I'd be tempted to block on cgrebs' [partial rewrite](https://github.com/mozilla/signing-clients/pull/19) so we're using update-to-date-ish libraries at least.

**Comment by jvillalobos** [comment]
> To confirm, the only criteria for these "Mozilla Signed Add-ons" is the OU in the signature?

Yes. One would think all of them will have a @mozilla.com GUID, but I'd rather not bank on that.

> What are the "all checks" - is this add-on to treated normally except for not-resigning at the end?

Yes. I was only referring to hard validation errors.

> I can remove the Hotfix handling while I'm at it then, I guess?

I think it's best not to do that yet and leave that work for #5174.

**Comment by andymckay** [comment]
@eviljeff I would suggest you double check with @jvehent or @aswan when you get to the review or prototype stage to make sure that the detection is correct.

**Comment by jvehent** [comment]
You'll need to parse the PKCS7 signature of the addon and check the OU of the end-entity certificate. Regular add-ons have the OU "Production", but could also be a hotfix if the CN is set to "firefox-hotfix@mozilla.org". Other types have different OUs.

```go
switch OU {
case "Production":
    if endEntity.CN = "firefox-hotfix@mozilla.org" {
        type = "hotfix"
    } else {
        type = "add-on"
    }
case "Mozilla Extensions":
    type = "privileged web extension"
case "Mozilla Components":
    type = "system add-on"
}
```

**Comment by ValentinaPC** [comment]
@EnTeQuAk : Could you please add some STR for us to check this or the label "qa: not needed".

I've downloaded a sample extension from the Bugzilla issue, that was already signed and tried to submit it again on AMO, but the validator informed me the the package will be signed again, even if is already signed. 
Thanks in advance!

**Comment by eviljeff** [comment]
That's the first part checked, so is probably enough.  To fully test you need to get past that to confirm that the file _isn't_ re-signed*, but it's limited to users logging in with a `@mozilla.com` email address though.

* the UI hasn't been changed so the site still tells you the add-on will be signed in various places.

**Comment by ValentinaPC** [comment]
> it's limited to users logging in with a @mozilla.com email address

You mean, logged in on AMO with a Mozilla account?

**Comment by ValentinaPC** [comment]
While being logged with a Mozilla account, the about error is no longer displayed, a warning is listed in the validation report (as before), and submission can be finalized.
Screenshots:
![mozilla-account](https://user-images.githubusercontent.com/15685960/28270997-17fa6772-6b10-11e7-9910-3ab918523ad3.png)

**Comment by muffinresearch** [comment]
@eviljeff if you don't already could you file issues to have the messaging reflect reality? It'll probably save some future confusion.
