### ISSUE TITLE
Site administration page is not centered on -dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5629]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/admin/models/

Expected results:
The page is correctly aligned

Actual results:
All the content under the header is wrongly aligned to the left

NOTES: 
Not reproducible on Stage

Please see video for this issue : 
![siteadministration](https://user-images.githubusercontent.com/1583842/27089859-4a1546d0-5064-11e7-8ef6-a28a914ef1ab.gif)

**Comment by diox** [comment]
It's ugly but it was a quick hack to make the list of items on the other pages in the admin wider. We don't really care about the design of those pages as long as it still works.
