### ISSUE TITLE
"Compatibility" pop-up for deleted addons

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5631]
Prerequisites:
User is logged with an admin account.

Steps to reproduce:

1. Navigate to the AMO home page.
2. Click on "Tools>Manage My Submissions.
3. "Ctrl+Click" on the "Edit Information" for an add-on.
4. Delete the add-on.
5. Click back on the first Tab with the "Manage My Submissions" page.
6. Click on the "Compatibility" button for the deleted add-on.

Expected results:
The pop-up displayed has an error message or an "close" button.

Actual results:
The pop-up displayed is white.

Notes/Issues:
Issue is reproducing on all AMO servers.
Verified on FF53(Win 10 64Bit).
Clicking outside of the pop-up will not dismiss it.
Video for this issue:
![compatibility pop-up](https://user-images.githubusercontent.com/28138132/27091003-81ad9efa-5067-11e7-94ce-b0ba82166978.gif)

**Comment by EnTeQuAk** [comment]
I'm going to close this as that's a huge edge-case and given that you just deleted the add-on I don't expect anyone to expect clicking a link in another tab to work properly. Eventually we're going to rewrite the developer hub also in our shiny new addons-frontend and until then I'd say we can live with that bug.

Please re-open in case I misunderstood the importance of this bug.
