### ISSUE TITLE
"Reject Multiple Versions" does not allow rejecting pending versions

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5633]
### Describe the problem and steps to reproduce it:
* Submit a few versions of an extension
* Upload one as pending review
* Go to reject multiple versions

### What happened?
* It is not possible to also reject the pending version, only past versions are selectable

### What did you expect to happen?
* It should be possible to also reject the pending version

### Anything else we should know?
This might be WONTFIX given that eventually we will have post-review, but if this is an easy fix maybe it can be done.

**Comment by diox** [comment]
It's easy enough to add the pending versions to the list but I don't want to spend time investigating the possible extra edge cases.
