### ISSUE TITLE
Inconsistency between two sections that should display same results

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5643]
Steps to reproduce:
1. Find an unreviewed add-on i.e. https://addons-dev.allizom.org/en-US/firefox/addon/permissionstesta/?src=search
2. Click on "View Mobile Site"
3. Select some rating stars, but dismiss the review popup (by clicking outside the popup)
4. Click "View classic desktop site" 
5. Click on review link under the rating stars

Expected results:
The add-on has the same number of reviews in the header section of add-on details page as in the "Reviews" section.

Actual results:
The add-on has 1 user review as a link and "This add-on has not yet been reviewed. Be the first!" in the Reviews section below.

Notes/Issues:
Verified on FF53(Win 7). Issue is reproducing on both stage and dev.
Screenshot and video for this issue:
![2017-06-15_1549](https://user-images.githubusercontent.com/15685960/27181937-434d2c12-51e2-11e7-9359-eb4950fa8da7.png)

Initially on https://github.com/mozilla/addons-frontend/issues/2371

**Comment by eviljeff** [comment]
Two questions:
a) how does front-end handle an add-on with ratings but not text-based reviews in the UI?
b) is this worth fixing before addons-frontend replaces this page anyway.
@jvillalobos

**Comment by jvillalobos** [comment]
a) We're hiding ratings that don't have a written review, so the behavior is right (though clearly inconsistent).
b) I don't think so.

**Comment by ValentinaPC** [comment]
Present "look" for All reviews page if the review has no text, only rating stars:
![add-on_details](https://user-images.githubusercontent.com/15685960/28120568-1187f3d4-6721-11e7-8e43-f5d441169eac.png)
![all_reviews](https://user-images.githubusercontent.com/15685960/28120562-0cfedbf2-6721-11e7-970a-70343a458c16.png)

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
