### ISSUE TITLE
add-on upload on AMO website issue

### ISSUE THREAD

**Issue by steross** [mozilla/addons-server#5644]
Hello there,

I am the creator of the complete theme for Mozilla Firefox called "FT DeepDark" which is available on AMO website at this address: https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/

I'm writing this post, because every time that I log into my developer account and try to upload a new version of my add-on (since beginning of June), the AMO's site displays the following error message: "Oops we had an error. We'll get on fixing that soon". When I refresh the page showing this error message, it brings me back on the upload page and under the "Select a file..." button it is written in red: "could not parse the manifest file."
It is not the first time this happens, but usually after a couple of days the problem is gone, but not this time.

The steps to reproduce the issue are the following:

1. Click the "Select a file..." button on this page: https://addons.mozilla.org/en-US/developers/addon/ft-deepdark/versions/submit/

2. Upload the the following add-on file: https://drive.google.com/file/d/0B17CBdDllx0zVzREcjYwM3pUM0E/view

3. Check the "Linux" and "Windows" platforms

4. Click the "continue" button

After doing all this, the following page displays: http://i.imgur.com/D5KVrms.jpg

When refreshing the page with the error message, this page displays: http://i.imgur.com/0zLwwy9.jpg

As usual, I expected the upload process to be completed, but as you can see on the screenshots it is not the case. By the way, my "manifest" file structure is the same as usual and it always worked fine. I don't know why suddenly there is a problem with it. If I try to install the add-on manually, it works without any problem, so I don't think it is an issue related with the way I packaged the add-on and/or the files it contains.

Thanks in advance for any kind of help

**Comment by wagnerand** [comment]
Hello, thank you for the report.
You are hitting #397, which has already been fixed and will be deployed to our servers later today.

**Comment by steross** [comment]
Thank you for your prompt reply. Then I will try to upload my add-on's package tomorrow.
