### ISSUE TITLE
Unable to install add-on on *BSD

### ISSUE THREAD

**Issue by JafarAkhondali** [mozilla/addons-server#5647]
### Describe the problem and steps to reproduce it:
When we tried to install it on FreeBSD and OpenBSD got an error saying "Not available for your platform"

### What did you expect to happen?
Add-on should've installed :-|

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

![firefox](https://user-images.githubusercontent.com/11364402/27195796-5f5894f6-521d-11e7-95a5-d0f7659c5699.jpg)

**Comment by eviljeff** [comment]
Please provide url to the add-on.  The developer may not have made the add-on available on that platform.

**Comment by JafarAkhondali** [comment]
@eviljeff I'm the developer of this add-on, there was no option for BSD.
here is the link:

https://addons.mozilla.org/en-US/firefox/addon/persepolis-dlm-integration/

**Comment by eviljeff** [comment]
Ah.  Yes.  As the add-on has been specifically marked as being compatible with Linux, MacOS, and Windows then it's only compatible with those platforms.  If it was 'all platforms' it would be installable on BSD.  (We don't allow add-ons to be compatible with BSD directly as it's not a supported platform)

**Comment by JafarAkhondali** [comment]
@eviljeff Oh thanks, I'll submit the new version as 'all platfrom' today if the problem solved i'll close the issue :+1:

**Comment by eviljeff** [comment]
@grahamperrin that add-on is only marked as available on Windows and MacOS platforms (not Linux)

**Comment by grahamperrin** [comment]
Thanks @eviljeff that makes perfect sense now. Sorry for the noise!
