### ISSUE TITLE
theme_data outputs `description: 'None'` when description is null

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5650]
### Describe the problem and steps to reproduce it:
When a persona has an empty description, the API outputs `description: null` for the main add-on object in the API but its `theme_data` property outputs `description: 'None'`. This is very confusing as I expect both values to be the same (they usually are, if `addon.description` is not `null`.

I know the `theme_data` stuff is special and inserted into a special `data` attribute so I'm not sure if `description` needs to be a string and is thus set to that for browser/client reasons, but I couldn't find any docs on that and this tripped us up in https://github.com/mozilla/addons-frontend/issues/2569.

### What happened?
`addon.description` and `addon.theme_data.description` were not equal.

### What did you expect to happen?
`addon.description` and `addon.theme_data.description` were equal. Or docs explain the possibility of a different value and why.

**Comment by diox** [comment]
I guess we just need to change `unicode(addon.description)` to `unicode(addon.description) if addon.description or None` in `Addon.theme_data`, and make sure this does not cause any problems for Firefox.

**Comment by eviljeff** [comment]
I'd really hope Firefox doesn't have special code in to handle `"None"` differently but personas...
At the expense of extra code complexity could just work around it so only the serializer gets None.

**Comment by diox** [comment]
I've tested this locally and Firefox seems to cope with `description: null` just fine - it let me install it, see it in add-on manager list/detail, no issues. So I'm going to fix `theme_data` at the source.

**Comment by tofumatt** [comment]
That's awesome, thanks!
