### ISSUE TITLE
"Gallery" link from FAQ page is returning a 404 page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5656]
Steps to reproduce:
1. Load FAQ page in production https://addons.mozilla.org/en-US/faq
2. Go to Mobile section and click on "gallery" link

Expected results:
A corresponding /android page is loaded.

Actual results:
A 404 page is loaded. 

Notes/Issues:
 - the URL ends /mobile, which is a 404.
Verified on AMO-prod FF53(Win 7).
Video for this issue:
![gallery](https://user-images.githubusercontent.com/15685960/27216857-18cc2634-5280-11e7-92ad-73fc6949f245.gif)

#5465

**Comment by jvillalobos** [comment]
This is a fairly trivial change in /olympia/pages/templates/pages/faq.html

Mentor: me.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by umaarabdullah** [comment]
assuming that link should redirect to https://addons.mozilla.org/en-US/android/ ?

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix video:
![gallery](https://user-images.githubusercontent.com/15685960/27418948-d5acbb6a-5726-11e7-9a95-32b9bbdc5a3c.gif)
