### ISSUE TITLE
Remove auto-approval restrictions, making all WebExtensions that pass validation auto-approved automatically

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5665]
Remove auto-approval restrictions, making all WebExtensions that pass validation auto-approved automatically. Do this behind `post-review` waffle, still using the `auto_approve` cron for now.

**Comment by vcarciu** [comment]
Verified using multiple webextensions which passed validation , new webextensions versions and webextensions which triggered warnings. All of them were auto approved. Marking as verified.
