### ISSUE TITLE
Development Channel download button no longer goes to download page for beta release?

### ISSUE THREAD

**Issue by jikamens** [mozilla/addons-server#5674]
The "Continue to Download" button in the "Development Channel" section of my add-on's page no longer takes the user to downloading the most recent release in the development channel. Instead, it atkes the user to downloading the most recent approved, non-development release.

This means there are no straightforward instructions I can give to my users for how to become beta-testers of my add-on.

**Comment by diox** [comment]
Can you link your add-on ?

**Comment by jikamens** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/send-later-3/

**Comment by diox** [comment]
Thanks. Looks like a bug in the way the contributions "roadblock" works, its download button does not obey the `version` passed in the URL. 

We'll look into it. As a workaround in the meantime, setting contributions to anything other than "Ask before users can download this add-on" should fix it (I haven't tried it though).

**Comment by diox** [comment]
The contributions "roadblock" page will be removed in #6072 so I don't think it's worth looking into this any more.
