### ISSUE TITLE
Upload a new version of an addon

### ISSUE THREAD

**Issue by romainneutron** [mozilla/addons-server#5693]
Hello,

I'm not sure this is the right place to ask such question, anyway as you proposed me [on twitter](https://twitter.com/mozamo/status/876859187329773568), I'm gonna fill this issue :)

I would like to automate the releasing of the new version of a addon, as I do on the Chrome WebStore for our Blackfire extension (https://chrome.google.com/webstore/detail/blackfire-companion/miefikpgahefdbcgoiicnmpbeeomffld)

On Mozilla AMO (https://addons.mozilla.org/en-GB/firefox/addon/blackfire/), it seems there's no way to upload a new version of the add-on using the API (http://addons-server.readthedocs.io/en/latest/topics/api/addons.html)

Maybe I'm wrong, could you please give me a pointer to the doc? Otherwise I think it would be nice to add such feature.

**Comment by muffinresearch** [comment]
@romainneutron these docs provide info on uploading a new version http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version

**Comment by romainneutron** [comment]
Thanks @muffinresearch ! That's definitely what I was looking for.
What about adding a link in the add-on section?

**Comment by romainneutron** [comment]
Another question: I've now pushed a new version of my add-on, but it does not appear on my admin listing view : https://addons.mozilla.org/en-GB/developers/addon/blackfire/versions

I get this result when issuing the request again:

 ```
HTTP/1.1 202 ACCEPTED
Allow: GET, POST, PUT, HEAD, OPTIONS
Content-Security-Policy: script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.paypalobjects.com/js/external/dg.js https://addons.cdn.mozilla.net; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; default-src 'self'; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; child-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; img-src 'self' data: blob: https://www.paypal.com/webapps/checkout/ https://www.paypal.com/webapps/hermes/api/logger https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; object-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net; form-action 'self' https://developer.mozilla.org; base-uri 'self' https://addons.mozilla.org; report-uri /__cspreport__
Content-Type: application/json
Date: Tue, 20 Jun 2017 11:09:22 GMT
ETag: "6246dd40e7bafdd056995c14372e5d73"
Server: nginx
Set-Cookie: multidb_pin_writes=y; expires=Tue, 20-Jun-2017 11:09:37 GMT; Max-Age=15; Path=/
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
X-Frame-Options: DENY
x-xss-protection: 1; mode=block
transfer-encoding: chunked
Connection: keep-alive

{"guid":"74e6405d-2f36-498b-b652-4c65c849eecd","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/74e6405d-2f36-498b-b652-4c65c849eecd/versions/1.10.0/uploads/304416b052774be0a34552bcdbcf5da6/","files":[],"passed_review":false,"pk":"304416b052774be0a34552bcdbcf5da6","processed":false,"reviewed":false,"valid":false,"validation_results":null,"validation_url":"https://addons.mozilla.org/en-US/developers/upload/304416b052774be0a34552bcdbcf5da6","version":"1.10.0"}%
```

**Comment by diox** [comment]
That output indicates that it has not been processed by the validator yet. See http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#checking-the-status-of-your-upload to query the endpoint that allows you to check the progress, no need to send the file again.

**Comment by romainneutron** [comment]
Thanks @diox for your answer. I understand the API provides information about the status.

However, I'm wondering why I don't see my upload in the webview. I use my CI to automatically push new versions once they are tagged, I use my browser to monitor what is the status of the uploads, and was expecting to see the uploads in the admin view

**Comment by diox** [comment]
The developer pages show actual versions once they have been processed, not all uploads. This is a quirk that we inherited from how AMO was designed, at this point the version does not truly exist, it's just a generic upload, and we don't list those anywhere. Once validation is done you'll see the version in the list.

**Comment by diox** [comment]
Closing because the validation result indicates that this add-on is not valid, which explains why a version was never created. The API docs will be updated to add the link in the add-on section as suggested, that's #5696

**Comment by romainneutron** [comment]
Hello,

I've fixed an issue in the manifest.json. Apparently, the manifest.json must not include the uuid under `application.gecko.id`, otherwise the `{"error":"Duplicate add-on ID found."}` error is returned.

Anyway, I now got this response:
```
HTTP/1.1 202 ACCEPTED
Allow: GET, POST, PUT, HEAD, OPTIONS
Content-Security-Policy: script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.paypalobjects.com/js/external/dg.js https://addons.cdn.mozilla.net; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; default-src 'self'; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; child-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; img-src 'self' data: blob: https://www.paypal.com/webapps/checkout/ https://www.paypal.com/webapps/hermes/api/logger https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; object-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net; form-action 'self' https://developer.mozilla.org; base-uri 'self' https://addons.mozilla.org; report-uri /__cspreport__
Content-Type: application/json
Date: Wed, 21 Jun 2017 11:29:06 GMT
ETag: "85965e560a18a597c8b8906c4948bcb3"
Server: nginx
Set-Cookie: multidb_pin_writes=y; expires=Wed, 21-Jun-2017 11:29:21 GMT; Max-Age=15; Path=/
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
X-Frame-Options: DENY
x-xss-protection: 1; mode=block
transfer-encoding: chunked
Connection: keep-alive

{"guid":"74e6405d-2f36-498b-b652-4c65c849eecd","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/74e6405d-2f36-498b-b652-4c65c849eecd/versions/1.10.0/uploads/5671a938e3514f10be4f335017166c64/","files":[],"passed_review":false,"pk":"5671a938e3514f10be4f335017166c64","processed":false,"reviewed":false,"valid":false,"validation_results":null,"validation_url":"https://addons.mozilla.org/en-US/developers/upload/5671a938e3514f10be4f335017166c64","version":"1.10.0"}
```

According to the validation_url, there are no errors, however the version does not appear in the version list.

**Comment by romainneutron** [comment]
I now realize the API route you mentioned to me only signs addons, it does not upload an addon on the addon server.
I would like to upload a new version of my add-on "On this site" using the API, as I can do manually:

![image](https://user-images.githubusercontent.com/137574/27382421-39a9552e-5687-11e7-8f9c-f8bdb6ec9e9b.png)

Could you help me and point me the appropriate direction to achieve that?

**Comment by diox** [comment]
The signing API does allow you to upload add-ons to be listed on the site, see the documentation for the `channel` parameter. 

Both unlisted and listed versions should appear in the developer hub version list, they will just have a different tag (and unlisted version won't have a public listing page, obviously).

Can you try again with the `channel` parameter, and post exactly what API calls you are making ? (obfuscating the credentials)

**Comment by romainneutron** [comment]
I use the channel parameter. here's full request and response:

```
PUT /api/v3/addons/74e6405d-2f36-498b-b652-4c65c849eecd/versions/1.10.1/?channel=listed HTTP/1.1
Host: addons.mozilla.org
Authorization: JWT xxxxxxxxxxxxxxx
User-Agent: Guzzle/3.9.3 curl/7.51.0 PHP/7.1.5
Content-Type: multipart/form-data
Expect: 100-Continue
```
```
HTTP/1.1 202 ACCEPTED
Allow: GET, POST, PUT, HEAD, OPTIONS
Content-Security-Policy: script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.paypalobjects.com/js/external/dg.js https://addons.cdn.mozilla.net; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; default-src 'self'; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; child-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; img-src 'self' data: blob: https://www.paypal.com/webapps/checkout/ https://www.paypal.com/webapps/hermes/api/logger https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; object-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net; form-action 'self' https://developer.mozilla.org; base-uri 'self' https://addons.mozilla.org; report-uri /__cspreport__
Content-Type: application/json
Date: Wed, 21 Jun 2017 11:59:02 GMT
ETag: "c1656626128590e398d680b967c81397"
Server: nginx
Set-Cookie: multidb_pin_writes=y; expires=Wed, 21-Jun-2017 11:59:17 GMT; Max-Age=15; Path=/
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
X-Frame-Options: DENY
x-xss-protection: 1; mode=block
transfer-encoding: chunked
Connection: keep-alive

{"guid":"74e6405d-2f36-498b-b652-4c65c849eecd","active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/74e6405d-2f36-498b-b652-4c65c849eecd/versions/1.10.1/uploads/3b9dbda6b50b498cab841db6fb0f439f/","files":[],"passed_review":false,"pk":"3b9dbda6b50b498cab841db6fb0f439f","processed":false,"reviewed":false,"valid":false,"validation_results":null,"validation_url":"https://addons.mozilla.org/en-US/developers/upload/3b9dbda6b50b498cab841db6fb0f439f","version":"1.10.1"}
```

**Comment by diox** [comment]
Sorry, it's not entirely clear from the docs, but the `channel` parameter should be part of the `form-data`. By having it part of the URL query string, it was ignored. So what happened is that the upload succeeded and created... a new, unlisted add-on. Why ? Well, because of a second issue, the guid should include the `{}` brackets if there are some, otherwise it's a different guid! If you log in to your developer hub on addons.mozilla.org you should see the extra add-on (https://addons.mozilla.org/en-GB/developers/addon/blackfire-companion6/edit)

I'll fix the docs to make it clearer that `channel` should be part of the form data, and make the API return an error when clients send a guid that should contain brackets without them.

**Comment by romainneutron** [comment]
\o/ Thanks a lot !
It works

**Comment by romainneutron** [comment]
Now I want to list the already uploaded versions using the `'https://addons.mozilla.org/api/v3/addons/addon/%7B74e6405d-2f36-498b-b652-4c65c849eecd%7D/versions/'` endpoint
It works perfectly, however if I use the filter query parameter, it fails with a `Authentication credentials were not provided.` error. Anything I missed?

```
GET /api/v3/addons/addon/%7B74e6405d-2f36-498b-b652-4c65c849eecd%7D/versions/?filter=all_with_deleted HTTP/1.1
  Host: addons.mozilla.org
  Authorization: JWT xxxxx
  Content-Type: application/json
  User-Agent: Guzzle/3.9.3 curl/7.51.0 PHP/7.1.5
```
```
  HTTP/1.1 401 UNAUTHORIZED
  Allow: GET, HEAD, OPTIONS
  Content-Security-Policy: script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.paypalobjects.com/js/external/dg.js https://addons.cdn.mozilla.net; style-s
  rc 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; default-src 'self'; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; child-src 'self' https://ic.paypal.co
  m https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com; img-src 'self' data: blob: https://www.paypal.com/webapps/checkout/ https://www.paypal.com/webapps/hermes/api/logger https://ssl.google-analytics.com ht
  tps://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; object-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://
  addons.cdn.mozilla.net; form-action 'self' https://developer.mozilla.org; base-uri 'self' https://addons.mozilla.org; report-uri /__cspreport__
  Content-Type: application/json
  Date: Wed, 21 Jun 2017 13:59:26 GMT
  ETag: "d5972c9c85159c7a7494e2554c26def1"
  Server: nginx
  strict-transport-security: max-age=31536000
  WWW-Authenticate: bearer realm="api"
  x-content-type-options: nosniff
  X-Frame-Options: DENY
  x-xss-protection: 1; mode=block
  transfer-encoding: chunked
  Connection: keep-alive
  {"detail":"Authentication credentials were not provided."}
```

**Comment by diox** [comment]
That error is because most of the APIs *except* signing do not currently support external authentication mechanism like JWT. They work with the internal authentication mechanism (and that should be documented), but it's meant for our own apps, not third parties. There is some discussions about either enabling jwt for all APIs or something else like oauth, but right now, I'm afraid you're stuck and can't use that API with authentication.
