### ISSUE TITLE
Add-on reputation values are incorrect displayed in Dev Hub

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5697]
Steps to reproduce:
1. Submit an add-on that qualifies for auto-approval i.e. https://addons-dev.allizom.org/en-US/developers/addon/webext-prioritate1/edit
2. Go to "Admin Settings" - "Add-on Reputation"

Expected results:
Reputation values are negative.

Actual results:
Reputations values are positive.

Notes/Issues:
- weight is calculated correctly.

Verified on AMO-dev FF53(Win 7).
Screenshot for this issue: 
![rep](https://user-images.githubusercontent.com/15685960/27337367-e0411a14-55da-11e7-8f5e-de9af894792c.png)

**Comment by diox** [comment]
Looks like it's working as intended. The reputation are positive values, because the higher a reputation the more thrustworthy it is, but get inverted when calculating the weight, because the lower the weight the less important it is to review it.

**Comment by ValentinaPC** [comment]
I misunderstood it.

**Comment by ValentinaPC** [comment]
@diox : So, an add-on with higher reputation becomes more trustworthy.
If it is trustworthy, then it should wait longer for review, not vice versa?

**Comment by diox** [comment]
The only impact is that add-ons with higher reputation will sit lower in the post-review queue (because their weight will be lowered by the high reputation). There is technically no guarantee that it will impact review times whatsoever.
