### ISSUE TITLE
drop raven js lib

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5698]
We include raven.min.js in our bundles, and activate it on dev, stage, prod but it's only used, that I can see, in [one place](https://github.com/mozilla/addons-server/blob/master/static/js/common/upload-addon.js#L43), if the server (i.e. amo) doesn't return valid JSON, during validation.
From a search in sentry I can't see any matches for "Error parsing upload status JSON" which leads me to believe it's basically unused.  So lets remove it.

**Comment by muffinresearch** [comment]
Raven is implicitly catching all errors in the JS  - we are seeing a lot of things logged here: See https://sentry.prod.mozaws.net/operations/frontend-prod/

On that basis I think it makes more sense to look at updating it rather than just removing it.
