### ISSUE TITLE
Ensure node js libs are fully installed in the dev environment 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5699]
Running recent development docker images of the development environment you get an error when loading the environment in a browser.

```
OSError at /

[Errno 2] No such file or directory: '/code/src/olympia/../../static/js/node_lib/jquery.js'
```

Is there anything that would prevent copying the node js libs as part of the image build so that the development environment has everything it needs when starting it up?

**Comment by eviljeff** [comment]
Potentially file system permission issues could stop it, but `make initialize` would fail.  Where is the error is received and at what point?

**Comment by muffinresearch** [comment]
I had pulled the latest containers, started up with `docker-compose up -d` and then visited olympia.dev. The error is displayed in the browser.

**Comment by eviljeff** [comment]
http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#setting-up-the-containers 
if you don't do `make initialize_docker` after `docker-compose up -d` lots of things fail.

**Comment by muffinresearch** [comment]
`make initialize_docker` should only be something run once when you set up the dev-env though.

**Comment by diox** [comment]
`make update` or `make update_deps` should also copy the libs over

**Comment by eviljeff** [comment]
oh, http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#updating-your-containers then.

**Comment by eviljeff** [comment]
`make update_docker` from outside the container.

**Comment by muffinresearch** [comment]
> oh, http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#updating-your-containers then.

Ah ok - those docs do the job. Thanks.

Seems odd that we reinstall all the deps all again when that's done as part of the docker container build.

**Comment by muffinresearch** [comment]
>Seems odd that we reinstall all the deps all again when that's done as part of the docker container build.

I've filed a separate bug covering the duplication of dep installs. https://github.com/mozilla/addons-server/issues
