### ISSUE TITLE
Docs for updating containers suggest running commands which reinstall deps already in the containers

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5701]
The docs for updating containers [1]  recommends running a command that reinstalls the dependencies. All the deps are installed as part of the build [2] so running the dep install again seems to be superfluous.

It's definitely still handy to have the ability to install new deps between container builds but running this after specifically pulling new containers could be avoided and that command should just run the migrations and any static file processing needed.

[1] http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#updating-your-containers
[2] https://github.com/mozilla/addons-server/blob/master/Dockerfile

**Comment by eviljeff** [comment]
Looks like it was originally added in https://github.com/mozilla/addons-server/pull/2981
Imo, it's pretty harmless to try to update the deps again, and it means we don't have to have a special `docker_update` task (which we then inconsistently change v.s. regular `update`).
