### ISSUE TITLE
replace jquery.minicolors with npm version

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5713]
part of #5458 
this library is only used for submitting (editing?) background themes - to select the colours.

**Comment by ValentinaPC** [comment]
Please add some STR or the label "qa: not needed". Thanks!

**Comment by eviljeff** [comment]
submit a background theme; color pickers for selecting text colors work.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Color picker for font and background is working as expected.
@eviljeff : After submitting the theme, the selected background color is not previewed, not sure if this is known or worth fixing.
Please see video:
![color](https://user-images.githubusercontent.com/15685960/28306223-2cded4ce-6ba7-11e7-9f13-68093e70baa8.gif)

**Comment by eviljeff** [comment]
I don't know if it's a known issue, but I doubt it's a bug with AMO (and very unlikely to be due to this library upgrade)

**Comment by ValentinaPC** [comment]
We can mark this as verified fixed and keep in mind while the new desktop pages are coming in our way.
Thanks!

**Comment by muffinresearch** [comment]
> We can mark this as verified fixed and keep in mind while the new desktop pages are coming in our way.
Thanks!

@ValentinaPC to clarify - the new frontend doesn't cover the developer hub it is just the user pages. Reviewer tools and developer hub are not changing.

**Comment by ValentinaPC** [comment]
@muffinresearch : Theme submission process will be different, no?
