### ISSUE TITLE
Add new (date, addon_id) index on theme_user_counts

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5715]
Part of #5712

`theme_user_counts`:

* [x] Drop `addon_date_idx` (`addon_id`,`date`)
* [x] Add new (date, addon_id) index

**Comment by vcarciu** [comment]
Please add some STRs to this bug or mark it as "qa: not needed"

**Comment by diox** [comment]
The migration failed on dev, because the key it's trying to remove is used in a constraint (presumably the one on `addon_id` on the same table).
