### ISSUE TITLE
"Start a new collection..." link is not working as expected if collection description is too long

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5723]
Steps to reproduce:
1. Load a theme details page i.e. https://addons.allizom.org/en-US/firefox/addon/ladybug-s-holiday/
2. Click on "Add to Collection" button
3. Click "Start a new collection..." link
4. Complete all mandatory fields (add a description with empty rows and over max length accepted)
5. Click "Create Collection" button

Expected results:
A message error that says that the description was too long is displayed.

Actual results:
The banner dimension is changed. Collection is not created.

Notes/Issues:
Verified on AMO-stage FF54(Win 7). Issue is reproducing on all AMO servers.
Video for this issue:
![coll](https://user-images.githubusercontent.com/15685960/27385121-342878ba-569a-11e7-99d3-7820c1e0acd6.gif)

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
