### ISSUE TITLE
Increase auto_approve cron frequency

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5724]
We want to increase the auto_approve cron frequency with post-review. Start with every 10 minutes, and try every 5 minutes later if it works fine.

Note that some kind of locking mechanism will have to be put in place (note that at the moment, post-review bypasses all checks done by `AutoApprovalSummary`, and that includes reviewer locks)

**Comment by ValentinaPC** [comment]
Are you talking about the frequency of auto-approval? Thanks!

**Comment by diox** [comment]
Yes. It should now be done every 10 minutes instead of every hour.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Auto-approval is done at 10 minutes.
Postfix screenshot:
![hour](https://user-images.githubusercontent.com/15685960/28272665-d869cc74-6b14-11e7-9734-4b53afe46482.png)
