### ISSUE TITLE
Some themes author have format issues after install in "Appearance" tab from about:addons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5726]
Steps to reproduce:
1. Load about:addons 
2. Install first theme: "SEBASTIAN KITTY" 
3. Go to "Appearance" tab and click "More" for the installed theme
4. Observe the author

Expected results:
Author is displayed without any issues.

Actual results:
Author has some format issues.

Notes/Issues:
- loading details page for that theme - https://addons.mozilla.org/en-US/firefox/addon/sebastian-kitty/ - we can observe that there are some weird chars in description (may cause the issue for the author?)
- for last theme -  Festival of Lights (that has different author listed) - we can see that after install same weird author is displayed on Appearance tab as in the first case -> loading details page for last theme will display the exact same weird chars in theme description as for the first theme.
- tried to change theme description in while Disco Pane is set to -stage, but no chenges in the author form. 

Verified on FF54(Win 7). Issue is reproducing for all AMO servers.
Video for this issue: 
![weirdauthor](https://user-images.githubusercontent.com/15685960/27391801-93e5ebe4-56ad-11e7-981b-71fbff762b56.gif)

**Comment by ValentinaPC** [comment]
> tried to change theme description in while Disco Pane is set to -stage, but no chenges in the author form.

Changes were made after a while, as follows:
- modifying theme description in AMO and saving the changes, will show, after install, in about:addons - Appearance tab, me as theme author, is this ok?
- note that Disco Pane is not modified and theme author is still the same.
![disco_pane](https://user-images.githubusercontent.com/15685960/27418803-3134683a-5726-11e7-80ef-65bc43d3c304.png)
![addonsmanager](https://user-images.githubusercontent.com/15685960/27418806-3509cac2-5726-11e7-8cd1-d7adb9a61845.png)

**Comment by diox** [comment]
This is not a bug. The disco pane add-on headers (title, authors) are sometimes tweaked manually to avoid uppercase or other weird formatting, but ultimately once installed the real name is displayed.
