### ISSUE TITLE
Create a sub-heading/description for each category and return in the API

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5728]
Now that #2923 and #3238 are complete we should add a description property to each category that can be translated and returned by the API.

The is so we can have a category description like in these mocks:

<img width="432" alt="screenshot 2017-06-21 17 38 49" src="https://user-images.githubusercontent.com/90871/27395670-80c6dc4e-56a8-11e7-87fa-df80aac962ef.png">

**Comment by tofumatt** [comment]
Alternatively we *could* store these in add-ons frontend actually, and just have one for every known theme category... but that limits the API as a single source of truth for data returned from it, which I'm not a fan of.

**Comment by eviljeff** [comment]
I think we can just add this to StaticCategory
