### ISSUE TITLE
Create description for every category

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5729]
The mock-ups have a description required for each category but they are just placeholders:

<img width="432" alt="screenshot 2017-06-21 17 38 49" src="https://user-images.githubusercontent.com/90871/27395741-bc4c7792-56a8-11e7-947e-97b56b5c8028.png">

It's fine to ship the category pages without the description but we should create them. We'll need one in English for every category. This depends on #5728.

**Comment by eviljeff** [comment]
@devaneymoz if you include them here we can add them to the static category definitions.

**Comment by willdurand** [comment]
The mock-ups have changed and we do not display the description of a category on its page *but* I need descriptions for Google (`meta[name="description"]` tag in addons-frontend).

I am hijacking this issue to add some category descriptions available in this doc: https://docs.google.com/document/d/1jCkeuyCuLpcwAVIXnqpYKgqnHnV0y1OkuQ1WHUc-ftI/edit?usp=sharing

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev by calling the Categories endpoint:` GET /api/v4/addons/categories`
Add-ons with `type` = `extension` , `persona`, `statictheme` have a category description. For all other `types`, category description is `null`

![image](https://user-images.githubusercontent.com/31961530/47564234-ef37cc80-d92c-11e8-924a-e9fefea2e861.png)
