### ISSUE TITLE
500 error page at webextension manual approval

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5737]
Steps to reproduce:
1. Submit a new webextension i.e. https://addons-dev.allizom.org/en-US/developers/addon/webext-oops/edit
2. Go to its review page and approve it manually (https://addons-dev.allizom.org/en-US/editors/review/webext-oops)

Expected results:
Webextension can be manually approved.

Actual results:
Webextension returns an "Oops..." page at approve.

Notes/Issues:
- don't know if related but, intermittently, the "Listed Review Page" link is returning a 404 page for same submitted webextension. (searching the webext in Reviewer Tools provides access to webext review page)
Verified on FF54(Win 7). Issue is only reproducing on AMO-dev.
Video for this issue:
![oops](https://user-images.githubusercontent.com/15685960/27420649-93df8d12-572f-11e7-8567-3c02923575ac.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/616151/

I suspect it's because of https://github.com/mozilla/addons-server/commit/1b5aa29c109374de42c08902849ebdcb1e3762bf

**Comment by diox** [comment]
Also https://sentry.prod.mozaws.net/operations/olympia-dev/issues/616218/

This affects auto-approvals and probably unlisted approvals too.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
1. Human approval for new listed submissions or old ones, unlisted add-ons, is working as expected
![approve-ok](https://user-images.githubusercontent.com/15685960/27473382-b5be1e5c-5807-11e7-8c47-5a188ad9c195.png)

2. Auto-Approvals for new submission or new versions is done
![auto](https://user-images.githubusercontent.com/15685960/27473662-9b64846e-5808-11e7-8f94-91ed002bd61e.png)
