### ISSUE TITLE
Beta add-on with rejected listed version loads a 404 page while accessed from Add-on Review Log page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5738]
Steps to reproduce:
1. Submit a listed webextension in AMO-stage and approve it 
2. Add a second beta version for your extension (https://addons.allizom.org/en-US/developers/addon/webext-listed-beta/versions)
3. Reject the public listed version using "Reject Multiple Versions" option from its review page
4. Load "Add-on Review Log" page https://addons.allizom.org/en-US/editors/reviewlog
5. Click on add-on name

Expected results:
Add-on name is not a link or it reloads the same log page at click.

Actual results:
Add-on name is a link that loads a 404 page at click.

Notes/Issues:
Verified on AMO-stage FF54(Win 7). Could not see if reproduced in dev because of #5737 .
Video for this issue: 
![404](https://user-images.githubusercontent.com/15685960/27424858-28eb3e2e-573f-11e7-8dd4-69522364177e.gif)

**Comment by muffinresearch** [comment]
Beta version support is being removed: https://github.com/mozilla/addons-server/issues/7163
