### ISSUE TITLE
Add a count of reviews that have a text body (not star ratings)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#5748]
The frontend [fetches an addon](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v3-addons-addon-(int-id|string-slug|string-guid)-) to render the detail page. This will say *Read N reviews* linking to a list of all reviews. We want it to say *Read N reviews* where N is the count of readable reviews, i.e. a count that does not include star ratings.

Request: can we get something on the [addon object]() like `ratings.textCount` ? Unlike `ratings.count` this would be a count of just the reviews that have a text body.

Without this data parameter we would have to make an additional API call to fetch all reviews using `filter: without_empty_body` and use the result count.

**Comment by diox** [comment]
Would need to be added to the `addon_review_aggregates` task, which would fill out a new field on the `Addon` model with that info. We'd also need to put that new field in ES, and expose it via the serializer.

Currently, the task calculate the total number of reviews and average rating does a single query (regardless of how many add-ons are considered by the task - but 99% of the time it's 1), and with that we'd have to add a new one. But this shouldn't be too much of an issue.
