### ISSUE TITLE
Wrong message displayed when trying to upload an add-on with over 200 MB

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5752]
Steps to reproduce:
1.Go to AMO Stage and try to upload an add-on bigger than 200MB(https://www.dropbox.com/s/03u7sgefn8r7wsj/testbigsize2.zip?dl=0)

Expected results:
Validation is failed and the error message should be useful

Actual results:
Validation is failed , but the validation message is not useful for understanding the reasons : "Received an empty response from the server; status: 0"

Please see screenshot for this issue : 
![over200mb](https://user-images.githubusercontent.com/1583842/27480904-d6aef864-5822-11e7-8cb7-563bcae23e85.png)

**Comment by craterkamath** [comment]
Hey guys I am a beginner and would like to work on  this issue. Is it open to take?

**Comment by diox** [comment]
No, that's probably not a good first bug. Have a look at [the good first bug list](https://github.com/mozilla/addons-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22contrib%3A+good+first+bug%22) instead.

**Comment by EnTeQuAk** [comment]
@wagnerand @jvillalobos does "Your add-on is too large. We do not accept add-ons bigger than 200M" work as a message? Do we have a page to link to where that change is documented?

**Comment by jvillalobos** [comment]
`Your add-on exceeds the maximum size of 200 MB.`

I don't think this warrants a link to more info, though we should probably mention this in the submission docs @atsay is working on.

**Comment by atsay** [comment]
@andrewtruongmoz Andrew, would you mind adding a note about max file size on [this page](https://developer.mozilla.org/en-US/Add-ons/Distribution/Submitting_an_add-on)? Thanks!

**Comment by andrewtruongmoz** [comment]
I've added a message to the 2nd last paragraph above 'Getting help'.

**Comment by vcarciu** [comment]
Verified as fixed : 
![messagebigsize](https://user-images.githubusercontent.com/1583842/27958941-ffee68de-632d-11e7-91b8-1c7d8a43d7e5.png)
