### ISSUE TITLE
Show subset of flags raised by static validation after webextension submission

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5753]
For WebExtensions, we want a subset of flags raised by static validation to be shown after it completes. They are specified on [this spreadsheet](https://docs.google.com/spreadsheets/d/10XXJeoIZrBQJiff2Gm_pXoFwhQNAA7UgtPlqTTAWR1g/edit#gid=378253551), in the column “Flag with developer during submission”.

This is spawn of #5579 which was becoming a little too large in scope.

**Comment by diox** [comment]
QA: when submitting a webextension using `eval()`, `document.write()`, `setInterval`/`setTimeout` (with a string, not a function),`document.write`, `innerHTML`, or a custom CSP, in the upload page, a list of messages summarizing the potential issues found (maximum one per type of issue found) should be shown under "Add-on submission checklist". The title of the list, "The validation process found these issues that can lead to rejections", should not be shown if none of those issues are found.

**Comment by ValentinaPC** [comment]
@diox : Verified submitting a webext that uses custom CSP and no extra messages under the ""Add-on submission checklist" and everything looks like before.
Please see screenshot:
![csp](https://user-images.githubusercontent.com/15685960/28113873-0cc61368-6707-11e7-82e0-5dd2db3dfba4.png)

**Comment by diox** [comment]
You were too fast, I just merged it, dev hasn't been updated yet.

**Comment by ValentinaPC** [comment]
Oops....I read 21 hours...I thought :P

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Things are working as expecting for `eval()`, `document.write()`, `innerHTML` and `CSP`.
No messages listed for native permissions (used webext is correct because the weight is incremented as expected)
Webext:
- https://addons-dev.allizom.org/en-US/developers/addon/webext-nativeperm-test12july/edit

@diox : or we don't care about native perm?
Thanks!

**Comment by diox** [comment]
At the moment we don't - it was not specified as something we should warn the developer about in the original spreadsheet (it makes sense to me: the others are potential mistakes, where as `nativeMessaging` is likely a conscious choice from the developer, even though it carries some risk).

**Comment by ValentinaPC** [comment]
Based on above coments, this can be marked as verified fixed.
Postfix screenshots:
![csp](https://user-images.githubusercontent.com/15685960/28152685-6c7e4444-67aa-11e7-8513-8f141d3a54f0.png)
![docw](https://user-images.githubusercontent.com/15685960/28152686-6c841f36-67aa-11e7-81e7-b0fa62e034cb.png)
![eval](https://user-images.githubusercontent.com/15685960/28152687-6c847d50-67aa-11e7-9d06-0f430592683d.png)
![html](https://user-images.githubusercontent.com/15685960/28152689-6c8915ea-67aa-11e7-85a4-4c0a6e5a9496.png)
![set](https://user-images.githubusercontent.com/15685960/28152688-6c85b45e-67aa-11e7-879b-f89da40df069.png)
Verified on AMO-dev FF54(Win 7)
