### ISSUE TITLE
could not get to link called IE Tap from PC Pitstop

### ISSUE THREAD

**Issue by ardellwatry** [mozilla/addons-server#5758]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
It sounds like you clicked a link on PC Pitstop for an add-on called IE Tab that is no longer available. You can search for other similar add-ons on the site, but there's nothing we can do about the removed listing or the dead link.
