### ISSUE TITLE
Link to extension is not working

### ISSUE THREAD

**Issue by Ankur098** [mozilla/addons-server#5760]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
1. I am trying to launch the RediStay application on Firefox.
2. I need an extension to launch it.
3. The link I gave doesn't work.

"Browsers Supported:

    Internet Explorer 11
    Firefox must be installed on your system
    In order to launch the application you need to install the following extension:
 Microsoft.Net Framework Assistant

https://innlaunch.redroof.com/

**Comment by jvillalobos** [comment]
That extension was discontinued many years ago and hasn't been available on the site for a very long time. It looks like the website you linked to needs to be updated to reflect that.
