### ISSUE TITLE
Try removing SQLAlchemy

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5762]
We require SQLAlchemy in addons-server, for the update service. We should try to get rid of it and just use django cursors.

I tried that a while ago in Marketplace and failed, in those 2 commits: https://github.com/mozilla/zamboni/commit/72fe88ed4b5e9ac4112d3d287280e0acfab2d362 and https://github.com/mozilla/zamboni/commit/f76c11a8c5fc87663b79e257ed0aa8bd3e4c8ba2 ; it had to be reverted because even though tests were passing, it broke updates on dev, causing a lot of `(2013, 'Lost connection to MySQL server during query')` after a few minutes.

**Comment by eviljeff** [comment]
Did you establish the cause of the failures?

**Comment by diox** [comment]
Back then we never understood why it was doing this. Django has support for [persistent connections](https://docs.djangoproject.com/en/1.8/ref/databases/#persistent-connections) and is supposed to re-open a new one when necessary but evidently it was not working properly in that case. It's probably because of the way `services/` operate, with its own wsgi app, manually setting up django etc, but I don't really know.

**Comment by eviljeff** [comment]
yeah, using part of django in something that isn't running with django is going to be risky.

**Comment by eviljeff** [comment]
> could just port the whole services/ section over to rust

no
