### ISSUE TITLE
404 MDN page for "Review Rules" link

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5765]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/agreement
2. Click on "Review Rules" link

Expected results:
A page is loaded.

Actual results:
A MDN 404 page is displayed.

Notes/Issues:
- url displayed: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Rules
Verified on AMO-dev FF54(Win 7).
Screenshot for this issue: 
![404](https://user-images.githubusercontent.com/15685960/27611149-be085114-5b99-11e7-915a-a0b72c43c3a7.png)

**Comment by diox** [comment]
Known issue, assigning to @jvillalobos - we can't launch post-review without that link.

**Comment by diox** [comment]
@ValentinaPC that's only with the `post-review` waffle enabled though, right ?

**Comment by ValentinaPC** [comment]
@diox : Yup . The page is only available on -dev where the flag is enabled.

**Comment by jvillalobos** [comment]
Adding @wagnerand, who has been working on the doc, and @atsay, who I think was going to give Andrew Truong a go at the document before publishing.

**Comment by ValentinaPC** [comment]
This was removed in #6293 , and this issue can be closed.
