### ISSUE TITLE
Add is_featured property on Addon detail request

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5769]

**Comment by diox** [comment]
I fear we'll need this on the search endpoint as well, which would complicate things (we'd need to index the property and update the search index when the add-on featured state changes)

**Comment by eviljeff** [comment]
oh?  I kinda of assumed it was already indexed as we show it in the existing search results. 😒

**Comment by diox** [comment]
Legacy frontend search only fetches the ids from ES, then does a database query to fetch add-ons matching those ids. And whatever extra database queries it needs. It's kinda crazy, only really works without bringing the whole site down because of cache-machine, which we want to get rid of...

**Comment by eviljeff** [comment]
Slight complication - `is_featured` isn't just a normal boolean property - it's dependent on the app currently being requested (e.g. Firefox) and the language/locale of the user.

Locale isn't a concern - we can get from the API parameter, or return the locale='' collection if it's not passed.

App is a problem.  We could support passing an `app` parameter and default to Firefox?  Or return 'True' if the addon is featured in any application's collection?  Or something else?

**Comment by eviljeff** [comment]
@tofumatt ^

**Comment by diox** [comment]
Wild suggestion: do we actually care which locale/app the add-on is featured in ? Ultimately, that information is presumably going to be displayed on the detail and search pages - as a user, you already stumbled upon the add-on, you don't really care where it's featured, the important part is that is *is* featured, isn't it ?

**Comment by eviljeff** [comment]
It's only because there are Firefox, Thunderbird, fennec, etc, collections, and some addons support multiple applications while not being particularly useful in the primary supported application.  I guess locale specific featuring are for niche country add-ons.  On the other hand, you're right - if you've already discovered the add-on then it's a mark of quality.

**Comment by tofumatt** [comment]
Yeah I don't care which application the add-on has been marked as being featured in. I guess an add-on being only featured in a certain locale is a bit weird but could make sense because of how it worked (a great * -> French translator shouldn't appear "featured" in Dutch).

If it's featured in any app or language though I'd consider it featured. A description will clear up locale issues, even.

**Comment by eviljeff** [comment]
So should the API handle language then, by taking in account the `lang` parameter, if present?  Or just ignore language entirely?

**Comment by diox** [comment]
Not handling locale will certainly make it easier to store in ES later :-)

**Comment by tofumatt** [comment]
I think not. If there are wins for ignoring locale on the dev side and it makes the code path/reasoning about what `is_featured` less complicated/complex let's just say "an add-on featured for any app in any locale will return `is_featured: true`". As @diox said before: if something is featured that's all we care about, especially once you get to the detail page. It's a sign of quality of the add-on, we don't need to be so specific as to locale/app.

**Comment by eviljeff** [comment]
Looking at the code, `Addon.is_featured(app, lang)` relies on `get_featured_ids` which is [memoized](https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/utils.py#L18:L46) for 10 minutes (because it's used for the homepage featuring sections) so I'm not sure we need to put a specific per Addon `is_featured` in ES.

**Comment by eviljeff** [comment]
It does break all the ES reliant tests though, because on the first request it is indeed an SQL query and we check there are no additional queries.

**Comment by ValentinaPC** [comment]
Please add some STR or the label "qa: not needed". Thanks!
