### ISSUE TITLE
Add is_restart_required property to File api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5772]

**Comment by diox** [comment]
QA: no need to test the API part (it will be done when the new frontend implements it) but please make sure that "restart required" info is still displayed everywhere when it should.

**Comment by ValentinaPC** [comment]
Seems like the requires restart label is available everywhere it should.
Verified as fixed on AMo-dev FF54(Win 7)
Screenshots from around AMO pages:
![reqres](https://user-images.githubusercontent.com/15685960/28266637-9a0d8c2e-6afe-11e7-9d53-660d4f5d60f5.png)
![list](https://user-images.githubusercontent.com/15685960/28266639-9cbd2b32-6afe-11e7-93ba-874ca1393199.png)
![rt](https://user-images.githubusercontent.com/15685960/28266641-9f00c71e-6afe-11e7-8d2c-8bd09b1321d8.png)
![revt](https://user-images.githubusercontent.com/15685960/28266643-a154d1d6-6afe-11e7-8308-57be2a5337ab.png)
