### ISSUE TITLE
expose developer comments in Addon API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5773]
~Not sure if we should combine it the model / database at this stage, or just in the API results.~
No combining; expose as is, as a separate field.

https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.4qn2rle47cci

**Comment by eviljeff** [comment]
@tofumatt @jvillalobos are you okay with `Addon.description` in the API being the `Addon.description` + `Addon.developer_comments`?  alternatives:
* a more permanent change be made (will affect the existing listing pages and devhub)
* expose developer comments in the API in a separate field and frontend can combine

**Comment by tofumatt** [comment]
I would much prefer the properties be exposed separately and not merged. That way if we want to highlight/change how dev comments are displayed in the future we can. I'm happy to make changes on the front-end to deal with the API change.

**Comment by jvillalobos** [comment]
Yes, please keep them separate.
