### ISSUE TITLE
Long descriptions are not entirely displayed in screenshots full view

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5776]
Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/addon/classicthemerestorer/?src=cb-dl-users
2.Open screenshots to full view and navigate through them

Expected results:
All screenshots descriptions are readable 

Actual results:
Long descriptions are not entirely displayed in screenshots full view

Please see screenshot for this bug : 
![cuttextscreenshot](https://user-images.githubusercontent.com/1583842/27638538-4529fc42-5c1c-11e7-9223-3921eb889e07.png)

**Comment by ValentinaPC** [comment]
This was tracked in https://github.com/mozilla/addons-server/issues/1712 ,
