### ISSUE TITLE
Search filter results are not working as expected

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5777]
Steps to reproduce:
1.Go to AMO Stage and perform a blank search 
2.Expand the Category section in the left side, under Filter Results
3.Select "Bookmarks" category under Search Tools

Expected results:
All search tools under bookmarks category are displayed (I verified and the category is populated : https://addons.allizom.org/en-US/firefox/search-tools/bookmarks)

Actual results:
"No results found" message is displayed

NOTES:
Reproducible also if selecting some categories under Complete Themes(ie. Animals)
Not reproducible for Categories under Extensions
Reproducible in prod too

Please see video for this bug : 
![emptyresults](https://user-images.githubusercontent.com/1583842/27640576-5cdfda54-5c22-11e7-8a0c-a99c60df2dcd.gif)

**Comment by diox** [comment]
This works if you deselect the "Works with Firefox {version}" filter and pick "Any Firefox" instead. I suspect because search engines have no compatibility information set or something like that.

**Comment by diox** [comment]
I don't have a specific commit or issue handy, but this should have been fixed with all the compatibility work in preparation for 57.

**Comment by vcarciu** [comment]
@diox : you are right issue was fixed and fix is on prod, thanks!
![bookmarkscateg](https://user-images.githubusercontent.com/1583842/30951218-62942f90-a42a-11e7-93ba-1a6bf3c1a86f.png)
