### ISSUE TITLE
Selected options from Filter Results are not highlighted in orange

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#5778]
Steps to reproduce:
1.In AMO Stage, perform an empty search
2.Under Filter Results in the left side, select many options

Expected results:
Selected option is highlighted in orange

Actual results:
Selected options are not highlighted 

NOTES:
Not reproducible in Prod

Please see video for this issue : 
![filters](https://user-images.githubusercontent.com/1583842/27641427-6d7aa41e-5c24-11e7-859f-c17460bc4498.gif)

**Comment by diox** [comment]
Could be because of 6df8d9d1307e013fdf86ba2162c798fc09e4bd71

**Comment by vcarciu** [comment]
Verified as fixed : 
![highlight](https://user-images.githubusercontent.com/1583842/27682263-a043b1c8-5cca-11e7-97a7-8db1e9d0306a.gif)
