### ISSUE TITLE
Add API to expose which collections an Addon is contained within

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5782]
from https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.4qn2rle47cci

Could be part of the collections api, could be part of the addons api

**Comment by eviljeff** [comment]
from irc:

> @eviljeff>does a property on the Addon API work for you? It would only be present for the detail view (because it's not - and won't be - in ES)
> @tofumatt> I think a collections property on the addon makes sense
> and then the collections API would be about returning a collection with a list of addons

**Comment by eviljeff** [comment]
@tofumatt `collections` can potentially be a very large list.  Which is best?
- a separate endpoint under the Addon detail, e.g. `/api/v3/addons/addon/(int:id|string:slug|string:guid)/collections/` with the usual pagination
- return a limited number of results in the Addon detail response.  E.g. the existing frontend shows only the top 3 collections, sorted by subscriber count.

**Comment by tofumatt** [comment]
I'd say both. I'll need to check the PRD to see how many collections we'd want returned without checking the endpoint, but I'd think the top 5 would be good for most things... and then we could query the `/api/v3/addons/addon/(int:id|string:slug|string:guid)/collections/` API when we need the whole hog.

**Comment by eviljeff** [comment]
@tofumatt what sort should the collections have?  Subscribers are being dropped so we don't have a way of determining popularity.  Idea: could be random?

**Comment by tofumatt** [comment]
If we don’t have a sane way to sort them… yeah, sure. ^_^

**Comment by eviljeff** [comment]
@jvillalobos do you have any thoughts on this?  If we're just return random collections... do we even want this at all?  (I started already but not point in wasting more time if it's useless)

**Comment by jvillalobos** [comment]
We don't want to expose user collections, since the goal is to make them semi-private. The only collections that could show up on that list would be those that are already featured, which would be a handful, at most.

**Comment by tofumatt** [comment]
Is it still worth showing that list at all then? Sounds like most add-ons won't have it and rarely would it show more than one collection. "Is featured" is probably a better signifier and we have an issue for that (https://github.com/mozilla/addons-frontend/issues/2752)

**Comment by jvillalobos** [comment]
Let's drop it for now and decide if it's worth adding later as part of the editorial changes.

**Comment by eviljeff** [comment]
closing for now then.
