### ISSUE TITLE
Add search addons by author functionality to addons API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5786]
Addons detail page needs to be able to show other addons by a developer, and it's pretty useful functionality anyway.

**Comment by diox** [comment]
API added, the query parameter is `author`. Needs no qa, let's wait until there is a frontend for it.

**Comment by eviljeff** [comment]
I guess username is good enough for the front-end feature, but only username, not id, etc?

**Comment by diox** [comment]
mmm I didn't think of doing it by `id. We only ever had `username` in Marketplace and it was fine. If `id` is needed that's simple to add, though.

**Comment by ValentinaPC** [comment]
Please add some STR for this or the lable "qa: not needed".
Thanks!
