### ISSUE TITLE
Only show active reviewers in the reviewer leaderboard

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5792]
https://addons.mozilla.org/en-US/editors/leaderboard/ should only show users in the group "Add-on Reviewers".

**Comment by wagnerand** [comment]
Oh, we also want "Senior Add-on Reviewers" included.

**Comment by wagnerand** [comment]
Also, Persona (Theme) reviewers...

**Comment by SVSanta** [comment]
Verified as fixed on AMO-dev FF54(Win 10 64Bit).
For position 12 bug [5809](https://github.com/mozilla/addons-server/issues/5809) has been logged.
Postfix screenshot:
![leaderboard groups](https://user-images.githubusercontent.com/28138132/27737469-f2377636-5db0-11e7-9bd7-df8ab7aa1538.PNG)
