### ISSUE TITLE
Remove base_site.html hack

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5796]
[`base_site.html`](https://github.com/mozilla/addons-server/blob/3e92c6a151b87c8e391e273e65ae3b559a3dc673/src/olympia/zadmin/templates/admin/base_site.html) contains what's probably the worst hack of the whole addons-server codebase.

It's a template that is essentially being rendered both by django and jingo, so that it can be used by the django admin (which uses django templates) while still including our admin tools menu (which use jinja templates). 

It's combined with a monkeypatching of `SimpleTemplateResponse` which cause each template in the django admin to be rendered twice: once by django template engine and then the result is parsed as a template by jingo.

Let's remove all this and instead make the django admin separate. It will help #1573

**Comment by wagnerand** [comment]
![h373def2a](https://user-images.githubusercontent.com/873258/27711480-4e63842e-5cd8-11e7-8d57-bebaa8e4c478.gif)

**Comment by ValentinaPC** [comment]
Please add some STR for this or the lable "qa: not needed".
Thanks!
