### ISSUE TITLE
"Mozilla" application option in Advanced search from Reviewer Tools 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5798]
Steps to reproduce:
1. Load Reviewer Tools any queue page https://addons-dev.allizom.org/en-US/editors/queue/new
2. Click on "Advanced Search" link
3. Click on "Application" dropdown

Expected results:
A list of all apps is displayed.

Actual results:
"Mozilla" option is also displayed.

Notes/Issues:
Verified on FF54(Win 7). Issue is reproducing on dev and stage.
Screenshot:
![mozilla_app](https://user-images.githubusercontent.com/15685960/27710672-39734bc0-5d29-11e7-99dd-b4cb809115a7.png)

**Comment by eviljeff** [comment]
It's on prod already and I can't see what change may have added this (Mozilla is legacy pseudo-'application' for some old stats) but it's harmless.  So calling this wontfix.
