### ISSUE TITLE
add langpack & dict api

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5803]
We need responses for https://addons.mozilla.org/en-US/firefox/language-tools/
The results are pretty specialised so sticking this extra stuff on the main Addon search api will be a waste for normal searches, and return a lot of extra data for these matches.

We just need the locale and links for the relevant dictionaries and language packs for those locales.

**Comment by ValentinaPC** [comment]
Please add some STR or the label "qa: not needed". Thanks!
