### ISSUE TITLE
Increase icon size for add-ons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5805]
The icon sizes are way too small and are making retina monitors cry.

Can we make them 1024px x 1024px max? And return a few different sized ones? I'd think we'd want 128px and 256px.

**Comment by muffinresearch** [comment]
Somewhat related is adding SVG support https://github.com/mozilla/addons-server/issues/4161

**Comment by eviljeff** [comment]
#7514 is connected to this.  As mentioned in that issue we do actually generate more than 64px (despite what devhub says) but just don't expose them in the API.  Is 1024px still needed?

**Comment by diox** [comment]
Note that IIRC we scale the icons up so a 1024x1024 might be super ugly depending on the source...

**Comment by diox** [comment]
@eviljeff mentioned the same thing in #7514:
> Really the feature is broken - we say 64 is the max in devhub (so that's probably the max size uploaded by a Dev); then resize them anyway. It's quite likely all the icons at 128, 256, 512 are useless therefore -we should probably just delete them.

I agree. We should start from scratch for anything above 64... Maybe the plan could be:
- Delete any icons > 64px
- Start supporting higher sizes in devhub
- Return what is available in the API, through the new `icons` property.

The problem is finding out what's available without having to store yet another field on `Addon`...

**Comment by eviljeff** [comment]
We could rely on `.exists()` on the filename (they're consistently named). 

When it comes to the larger sizes (larger than 64, or whatever we decide is the "minimum required size" in the future) I think we should only generate them if the source is equal or greater than that size so we never upscale (e.g. dev uploads a 128px icon, we create 32, 48, 64, 128, but but 256 and 512).

Aside: 48 seems useless.

**Comment by diox** [comment]
I'd like to avoid calling `.exists()` on the (network) filesystem when serving an API response though... I guess we'll have to add a field.

Agreed on the rest. And 48 is definitely useless.

**Comment by eviljeff** [comment]
@jvillalobos @pwalm what icon sizes do we want?  Though I suppose a better question is what icon sizes does frontend want to display?

**Comment by eviljeff** [comment]
fwiw, frontend is displaying the 64 icon right now (and resizing it down to 32 on the shelves).  I think we're good with switching to 48 and 96 on devhub, though they'll be some frontend work and it'll be upsizing to 96.  Its a #7907 style/sized project again really.

**Comment by jvillalobos** [comment]
After some discussion, we have decided to standardize to 128x128 for the icon. We'll eventually require it for upload (either on the XPI or on AMO, TBD), but we'll still need at least one fallback with those dimensions for existing add-ons that don't have one.

**Comment by eviljeff** [comment]
Should we just have 128x128?  (We might need to keep generating 64 and/or 32 for Firefox, in /api/v3/ at least - see #7514)

Can you link to the companion frontend issue?

**Comment by jvillalobos** [comment]
> Should we just have 128x128?

We should generate any thumbnails we use regularly, I think.

> Can you link to the companion frontend issue?

Not sure what you mean here. I haven't filed any new ones, because I don't know if any frontend work is needed. I don't quite understand the issue you linked to, which seemed urgent... back in February?

**Comment by eviljeff** [comment]
>>   Can you link to the companion frontend issue?
> 
> Not sure what you mean here. I haven't filed any new ones, because I don't know if any frontend work is needed.

Well, it's useless devhub collecting and serving 128x128 icons if frontend never actually uses 128x128.  It currently always uses 64x64.

> I don't quite understand the issue you linked to, which seemed urgent... back in February?

The issue was to have frontend switch to using the `icons` property in the addon api response, so they could display the most appropriate size from a set of icon sizes.  Frontend currently uses the `icon` property, which is always a 64x64 icon.  (It got less urgent after we decided to keep both `icon` and `icons` around even though `icon` became redundant when `icons` was added)

**Comment by eviljeff** [comment]
Re: Firefox needs in the `/api/v3/` api:

>`<eviljeff>` do you know what icon sizes Firefox expects from the AMO API (ref https://github.com/mozilla/addons-server/issues/7514)?  We have some changes in standard sizes planned but if you need some specific sizes we'll be sure to keep them (e.g. 64x64)
`<John-Galt>` 64×64 and 48×48
`<freaktechnik>` (48 in list view, 64 in details/options)
`<eviljeff>` What would happen if we only had 128x128?
`<John-Galt>`We'd scale that and use it for both.  We should probably use 128 for retina anyway, but I don't think we currently do

**Comment by jvillalobos** [comment]
> Well, it's useless devhub collecting and serving 128x128 icons if frontend never actually uses 128x128. It currently always uses 64x64.

There are plans for a new product page in Q1. Many of the content requirements being introduced in Q4 are meant as the first step in that direction. So, at least in Q4, I don't think there will be any consumers for that particular size.

The Add-ons Manager will also be refreshed sometime in the future, but I don't know their timeline. Definitely not Q4 either.

**Comment by eviljeff** [comment]
@jvillalobos is this copy okay for the tooltip: "Will be the standard in future add-on detail pages." ?
![screenshot 2018-11-26 18 05 47](https://user-images.githubusercontent.com/768592/49033021-f9581f80-f1a5-11e8-910d-f752e762ff7b.png)

Also, I minimally adjusted the existing explanation text to "PNG and JPG supported. Icons resized to 128x128 pixels if larger." but I'm not sure if that's the desired behaviour any longer - should we still be upsizing and downsizing whatever is submitted to the standard sizes?  Right now we don't enforce _any_ restrictions on size (or ratio - the icon doesn't even need to be square!)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

- add-on icons are rendered now in three different sizes: 34, 64, 128 (the new addition) 
- icon uploads are restricted to JPG and PNG
- the icon must be square and its size needs to be equal to or larger than 128px width and height 

![image](https://user-images.githubusercontent.com/31961530/49378676-da154100-f715-11e8-8391-451284e9cf82.png)

![image](https://user-images.githubusercontent.com/31961530/49378680-e13c4f00-f715-11e8-84c4-5f1b984346d3.png)

There is an issue with previews rendering immediately after the changes are submitted - #8977 opened a while back (now I've updated it a bit to match the current behavior)

I've also filed #10146  for an issue with the 128px icon preview.
