### ISSUE TITLE
Empty "Name" field inside "Reviewer Leaderboard"

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5809]
Prerequisites:
- Have a user in the "Reviewer Leaderboard" with nothing in the "Display Name" field.

Steps to reproduce:

1. Navigate to https://addons-dev.allizom.org/en-US/editors/leaderboard/ .

Expected results:
All users have a name.

Actual results:
Users with no "Display Name" have an empty string in the "Name" field.

Notes/Issues:
Verified on AMO-dev FF54(Win 10)
Picture for this issue:
![leaderboard](https://user-images.githubusercontent.com/28138132/27736905-cbe7e44a-5dae-11e7-88c9-c2d59b5fbeb7.PNG)

**Comment by diox** [comment]
Should be fixed as part of the changes in #6611

**Comment by vcarciu** [comment]
Verified as fixed : 
![leaderboard](https://user-images.githubusercontent.com/1583842/32384021-47c6418a-c0c2-11e7-9c59-fb3b6a3e7cf0.png)
