### ISSUE TITLE
Disco Pane content update - July 2017

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#5815]
For the **20 July** push, we'll REPLACE uBlock Origin and Emoji Keyboard for two new extensions:

**Stop sneaky trackers** with [Privacy Badger](https://addons.mozilla.org/firefox/addon/privacy-badger17/)
Block invisible trackers and spying ads that follow you around the Web. 

**Improve your writing** with [LanguageTool Grammar Checker](https://addons.mozilla.org/firefox/addon/languagetool/)
Supporting 25+ languages, this extension puts a proofreader right in your browser. 

And REPLACE all three themes with the following:

[Summer Fractal](https://addons.mozilla.org/firefox/addon/summer-fractal/) by Alizarin
[Romantic Firefox](https://addons.mozilla.org/firefox/addon/romantic-firefox/) by Candelora
[Space Stars](https://addons.mozilla.org/firefox/addon/space-stars/) by Woutergude

Full page content lineup, top to bottom...

Summer Fractal
Privacy Badger
LanguageTool Grammar Checker
Romantic Firefox
Awesome Screenshot Plus
Enhancer for YouTube
Space Stars

@muffinresearch @EnTeQuAk @diox

**Comment by EnTeQuAk** [comment]
Shit, I completely forgot to push the PR last Tuesday and now it's too late unfortunately 😞 I am about to prepare the data and PR so that we can land this asap after the next tag so that there'll be only one week delay. I hope this still works.

**Comment by ValentinaPC** [comment]
Verified this on **AMO-prod** FF54(Win 7) but the new changes did not land, should they?
This is the Disco Pane, now:
![untitled](https://user-images.githubusercontent.com/15685960/28520346-c7ec4828-7077-11e7-9efd-b9cd93239666.png)

**Comment by EnTeQuAk** [comment]
They will land this week because I missed the window for this last cycle.

**Comment by ValentinaPC** [comment]
I thought **_I_** missed it :D

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF54(Win 7)
Postfix screenshot:
![untitled](https://user-images.githubusercontent.com/15685960/28707061-874860da-737f-11e7-837a-d78061cdb1ca.png)
