### ISSUE TITLE
Dictionary add-ons should not have strict compatibility

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#5830]
#5825 revealed that dictionaries have strict compatibility and have been working because of the bulk compatibility updates we run for all add-ons. Since we don't plan to do bulk compatibility updates past 56, we need an alternative way to keep them working.

Dictionaries should be compatible with all versions of Firefox (for desktop), Thunderbird, and SeaMonkey. Firefox for Android is the only application that isn't supported. This may change in the future if we move them to WebExtensions, but for now there's no reason to restrict their compatibility.

**Comment by diox** [comment]
*Technically* they don't have strict compatibility set (neither in the `install.rdf` of the dictionaries I could find or in the database). It's just that some of them have `maxVersion` set in `install.rdf` and therefore are displayed as non-compatible next to their install button (but the button works, even if it's greyed out).

Up until now we obeyed whatever `maxVersion` was set in `install.rdf` but bumped it afterwards when doing the compatibility bumps. I guess we need to start ignoring that for dictionaries somehow ?

**Comment by jvillalobos** [comment]
Yes, by strict compatibility I mean that we respect the `maxVersion` and grey out the button. The request is that we stop doing that for dictionaries.

**Comment by diox** [comment]
Ok. I wonder what's the best strategy. We have 2 options
- Just ignore the max version when displaying the button.
- Don't record the max version when uploading (or cheat somehow like we do for webextensions)

Both have different edge cases, need to think about this more.

**Comment by ValentinaPC** [comment]
Verified this on AMo-dev FF54(Win 7).

I've submitted a dictionary that has `maxVersion` = 20 (https://addons-dev.allizom.org/en-US/firefox/addon/united-states-english-d2/) and obtained the following results:
1. dictionary can be installed in FF54
2. compatibility range is written in all versions page - https://addons-dev.allizom.org/en-US/firefox/addon/united-states-english-d2/versions/ - expected?
3. no compatibility options in My Add-ons page or in Manage Versions page (https://addons-dev.allizom.org/en-US/developers/addon/united-states-english-d2/versions/1532696) from Dev Hub

**Comment by diox** [comment]
Had not thought about the compatibility range displayed in the versions page, I'll change that.

**Comment by ValentinaPC** [comment]
Compatibility is also listed in Reviewer Tools, don't know if we need to bother with that.
Please see screenshot:
![compat-rev_tools](https://user-images.githubusercontent.com/15685960/28455108-8459d9ea-6e06-11e7-9003-2b31223bc887.png)


> Firefox for Android is the only application that isn't supported

Regarding this: I've submitted a dictionary https://addons-dev.allizom.org/en-US/android/addon/united-states-english-d4/?src=ss that is also compatible with Firefox for Android, the `maxVersion `from the manifest is 20.* but I was able to install the dictionary on my Android device using FF54.
I've submitted a dictionary compatible only with Android (https://addons-dev.allizom.org/en-US/android/addon/dictionary-for-android/?src=search) and has the exact same behavior as above.
@diox : Is this correct? Or I misunderstood something? Thanks!

**Comment by diox** [comment]
Reviewer tools is also something I had not thought about :) Let's keep it, because it reflects what the developer put in the manifest, so that may be useful for debugging problems.

**Comment by ValentinaPC** [comment]
And the questions about dictionary compatible with FF for Android?

**Comment by diox** [comment]
Being able to ignore `maxVersion` is normal (that's kind of the point of this issue, Android or not : dictionaries should ignore it)

**Comment by ValentinaPC** [comment]
Could you, please, explain to me this comment:
"Dictionaries should be compatible with all versions of Firefox (for desktop), Thunderbird, and SeaMonkey. **Firefox for Android is the only application that isn't supported.**" At what type of "unsupported" we refer?

**Comment by diox** [comment]
I... had not seen that. And I don't know, I thought they were supported just fine.

**Comment by ValentinaPC** [comment]
My understanding was that in the Firefox for Android case, we do not drop the compatibility, but i can be wrong.

**Comment by diox** [comment]
@jvillalobos making a special case for Firefox for Android is significantly more work - right now I've just made them ignore compatibility entirely, like personas and search engines. Do we really need to make them incompatible with Firefox for Android ?

**Comment by jvillalobos** [comment]
As far as I know, they don't show up on the mobile site, so I don't think we need to take any additional action to make they incompatible.

**Comment by ValentinaPC** [comment]
Based on above comments we can mark this verified fixed.
Verified on AMO-dev FF54(Win 7).
Postfix screenshot from add-on details page - where compatibility range is no longer listed:
![2017-07-24_1009](https://user-images.githubusercontent.com/15685960/28511927-3a0a3296-7058-11e7-96f7-31e4d306db59.png)
