### ISSUE TITLE
undefined variables in templates aren't "" anymore with DEBUG=True

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5837]
regression from jingo -> django-jinja

Previously an undefined variable in a `{{ variable }}` seemed to resolve to an empty string ("");  now they resolve to literally "{{ variable }}".  Only in local dev environments where DEBUG=True though.

**Comment by eviljeff** [comment]
Two places I've noticed this so far:
- search field query string on homepage is "{{ query_term }}"
- body attribute in the default template is `data-raven-dsn="{{ no such element: django.conf.Settings object[&#39;RAVEN_DSN&#39;] }}"`

**Comment by diox** [comment]
Github needs a "everything is terrible" emoji.

**Comment by EnTeQuAk** [comment]
fyi, given the fact that the behavior in -dev, -stage and -prod matches what we previously had this is not a regression that justifies a cherry-pick imho. For example, raven-dsn is just fine on -dev.

I'll look into fixing those two things.

**Comment by eviljeff** [comment]
got it on http://olympia.dev/en-US/editors/themes/pending too.  

Given QA won't be able to pick this up should we consider trying to a) change the behavior for DEBUG=True so undefined values are "" as before or b) making -dev show the error like it does locally?

**Comment by EnTeQuAk** [comment]
> Given QA won't be able to pick this up should we consider trying to a) change the behavior for DEBUG=True so undefined values are "" as before or b) making -dev show the error like it does locally?

Eventually I'd like us to not have any template code that does rely on variables being set or unset but rather explicitly expects them to be empty or nullable. Explicit is always better than implicit.

So I'd give this another week and maybe turn that on for -dev as well. I don't think it's a good idea to do that for -stage given that it should be as prod like as possible.

**Comment by EnTeQuAk** [comment]
Another one: http://olympia.dev/en-US/developers/addon/submit/upload-listed

``{{ no such element: django.forms.utils.ErrorDict object['supported_platforms'] }} ``

**Comment by EnTeQuAk** [comment]
I'm closing this, this needs drive-by fixes in other PRs once we discover these places. I don't think it's reasonable to try and catch 'em all. The only way to do this is to let jinja throw errors but that might be unreasonable as long as we still have old frontend code lying around.
