### ISSUE TITLE
change admin tools link to point to admin home

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5839]
currently the 'Admin Tools' link goes to the models page which a) isn't accessible to anyone other than full admins (all 3 of them) and b) doesn't have a header any more to go to the other admin tools.  Lets just change it to point to /admin

**Comment by vcarciu** [comment]
Verified as fixed : 
![admintools](https://user-images.githubusercontent.com/1583842/27907792-bcce2814-6251-11e7-802e-de9efb6b4c3e.gif)
