### ISSUE TITLE
404 page for self hosted signed addon download link

### ISSUE THREAD

**Issue by biscoe916** [mozilla/addons-server#5840]
### Describe the problem and steps to reproduce it

Links to signed, self-hosted, addons lead to 404. 

##### Steps to reproduce: 
1. From "Versions" page click "Upload a New Version"
2. Select "On your own", in the "Where to Host Version" section.
3. Select zip file for your extension
4. Selet All Platforms 
5. Click Sign Addon
6. Attempt to download the signed addon when it completes.
7. 404

Note: I don't know which of the steps outlined above are required to reproduce, but those are the steps I followed. 

### What happened?

The download link provided in the resulting page leads to 404.

### What did you expect to happen?
I expected to be able to download the signed extension

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by biscoe916** [comment]
I am now able to download the signed extension. It took approx. 2 hours for the download to be available. Perhaps a cron job repaired the problem?

**Comment by eviljeff** [comment]
https://addons.mozilla.org/en-US/developers/addon/virtru-email-encryption/versions

**Comment by eviljeff** [comment]
If I had to take a wild guess, I'd point my finger of blame at the Invisible status of the addon, which shouldn't affect unlisted versions, but may inadvertently.

**Comment by diox** [comment]
yeah, that sadly mozilla/addons/issues/324 ; it's quite difficult to fix properly, though we have some ideas (but haven't had the time to implement them yet). As guessed, a cron job repairs the problem automatically.
