### ISSUE TITLE
TheFreeDictionary Extension for Mozilla Firefox - Broken Link?

### ISSUE THREAD

**Issue by ARL87** [mozilla/addons-server#5842]
I was looking for TheFreeDictionary extension for Mozilla Firefox. 
URL:   http://www.thefreedictionary.com/_/help/help4.htm#41
Link Location:   https://addons.mozilla.org/extensions/moreinfo.php?id=68
Upon clicking the link, I was taken to the following URL:
https://addons.mozilla.org/en-US/firefox/addon/?id=68
So I clicked on "file an issue", signed up for GitHub, and now you know what I know :-)
I've included the page URL [above]  where I came across the link, the link location [above], and a screenshot [below] for your reference. I hope this helps.

![broken-link](https://user-images.githubusercontent.com/29934555/27891198-3551bc10-61ad-11e7-8d9c-35fdbc2ff410.JPG)

**Comment by muffinresearch** [comment]
@ARL87 hi, this is the add-on you're looking for:

https://addons-dev.allizom.org/en-US/firefox/addon/dictionarysearch/
