### ISSUE TITLE
Search tools homepage can't be opened while logged in

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#5848]
### Steps to reproduce:
1. Open addons.allizom.org and log in.
2. Open https://addons.allizom.org/en-US/firefox/search-tools/

### Expected results:
The page is correctly opened.

### Actual results:
Oops! We had an error. message is displayed

### Anything else we should know?
Verified in FF54(Win7) issue can be reproduced in amo-stage and amo-dev
This issue is not reproducing if the user is not logged in.
Screencast for this issue:
![searhtoolshomepage](https://user-images.githubusercontent.com/15685441/27913888-2ec8fd32-626a-11e7-9d50-1375eee29426.gif)

**Comment by muffinresearch** [comment]
Related sentry error: https://sentry.prod.mozaws.net/operations/olympia-stage/issues/620666/

**Comment by EnTeQuAk** [comment]
This got fixed together with https://github.com/mozilla/addons-server/pull/5849 - it's now on -dev (where it was reproducable before) and now that page works on -dev again.

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in addons-dev.allizom.org
Postfix screecast: 
![searchpagepostfix](https://user-images.githubusercontent.com/15685441/27947692-a2141afc-62ff-11e7-8935-a858ed2c73d4.png)
