### ISSUE TITLE
Clicking on theme image will disable preview

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5851]
Steps to reproduce:

1. Navigate to https://addons.allizom.org/en-US/firefox/addon/big-sur-coast/ .
2. Click on the there preview image.

Expected results:
The preview is distill displayed.

Actual results:
Preview is disabled when clicking on the theme image.

Notes/Issues:

- Verified on FF54(Win 10). Issue is reproducing on all AMO servers.

- Gif for this issue:
![preview1](https://user-images.githubusercontent.com/28138132/27916295-4d1689ec-6271-11e7-8a48-1bf6555d9f45.gif)

**Comment by EnTeQuAk** [comment]
okay, I misread the description so sorry for all the label spam.

I do think this is a nice addition and adds a touch of multiple options to disable the preview. I can even imagine that on smaller screens (or with a touch-pad) this feels even better not to have to scroll somewhere else to disable the preview again.

I am going to close this unless I misunderstood this but I think it has been like that for ages. And it'll be re-implemented by addons-frontend soon-ish anyway.
