### ISSUE TITLE
New Collection can't be created using the add to collection button

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#5854]
### Steps to reproduce:
1. Open https://addons.mozilla.org/en-US/firefox/collections/mine/favorites
2. Click on the Add to collection button.
3. Click on the Start a new Collection... link.
4. Fill the form and click the Create Collection button.

### Expected results:
The collection is created.

### What did you expect to happen?
The collection is not created. The Post request fails with a 500 error message.

### Notes/Issues
Verified in FF54(Win7) Issue can be reproduced in -dev, stage and production.
Screencast for this issue:
![createcollection](https://user-images.githubusercontent.com/15685441/27948354-3cb627e2-6302-11e7-88fa-07c1a6b1a007.gif)

**Comment by muffinresearch** [comment]
Sentry: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/620775/events/11218589/

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in addons-dev.allizom.org
Postfix screencast:
![collectioncreate](https://user-images.githubusercontent.com/15685441/28124330-042e452a-672c-11e7-93ab-1a24e33204e7.gif)
