### ISSUE TITLE
Add description field to submission flow

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5855]
When submitting a new add-on the developer is presented with a lot of things to fill out including the summary, but not the description.

As a result, a lot of listings we review have a filled out summary but no description. I think it would be a good idea to add the description field to the submission flow, this way the developer has a chance to fill it out directly and there may be less info requests needed to get a complete description.

![image](https://user-images.githubusercontent.com/607198/27952313-2097e27a-6308-11e7-8208-f88477b25b72.png)

**Comment by emerald2k** [comment]
As an add-on reviewer we do a lot of requests for adding more info to the listing from developer. The summary, description and screenshots are very often missed or incomplete. Making these to be mandatory to the submission flow or in a way so developer it's aware that these are required will reduce our load of requests and help to focus on the important review criteria.

**Comment by wagnerand** [comment]
We discussed making the description mandatory just a couple of months ago and came to decision to not do it.
I personally don't think screenshots should be mandatory.
I'm not sure how much clutter we'd add by adding the description to that page. I wouldn't mind adding it now, and maybe it's something we can optimize when the devhub pages get redesigned.

**Comment by kewisch** [comment]
I agree the description doesn't need to be mandatory, especially since sometimes the summary is sufficient to describe the add-on. But as an optional field I think it would make sense (despite clutter). Screenshots can remain on the listing page, no need to add them to the submission flow.

**Comment by jvillalobos** [comment]
If a developer can't be bothered to add a summary that explains what the add-on does, I don't see how an optional description box is going to help. Adding some help text around the summary box that encourages something more descriptive _might_ help, but that's a separate issue. Please file if you think that will help.
