### ISSUE TITLE
Turn around meaning of privacy policy checkbox in the submission flow

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5856]
In order to encourage developers to add a privacy policy, it would be a good idea to turn around the meaning of the checkbox in the submission flow and require the privacy policy if the checkbox is not checked. I am thinking something like this (with slightly better layout):

![image](https://user-images.githubusercontent.com/607198/27953175-18c693fe-630b-11e7-824a-b595c0d28f4d.png)

**Comment by wagnerand** [comment]
I think @deadsquid has some opinions on this. Iirc, he suggested several checkboxes that give an overview whether user data is collected, stored and shared...

**Comment by emerald2k** [comment]
I subscribe to @kewisch idea and I suggest that submission form should contain a dedicated part for remote data exchange, where developer describes exchanged and collected data and the requirement of a privacy policy.

**Comment by kewisch** [comment]
> I think @deadsquid has some opinions on this. Iirc, he suggested several checkboxes that give an overview whether user data is collected, stored and shared...
Yes, we had been talking about this. That would be the more ideal solution and if we can do that I'd prefer, but this issue may be a quick intermediate fix since it can be done without changing any models.

**Comment by jvillalobos** [comment]
I don't think it's a good idea to default to the minority case. It may lead to junk privacy policies because developers just want to move on to the next submission step.

As mentioned above, we're planning on change the way in which we handle privacy. I expect to have a spec ready this quarter.
