### ISSUE TITLE
Don't ignore 400 errors when creating ES indices

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5859]
Our elasticsearch index creation code does this:
```python
if not es.indices.exists(index):
    es.indices.create(index, body=config, ignore=400)
```

Ignoring 400 errors is bad... It can lead to more errors later that are tricky to debug, like when you expect the index to have been created but it wasn't...

**Comment by ValentinaPC** [comment]
Please add some STR for this or the label "qa: not needed".
Thanks!
