### ISSUE TITLE
Implement (or think) about partial re-indexes

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5861]
Currently, whenever we have a mapping change we are reindexing all our data. As far as I know ElasticSearch supports dynamically adding new items to the schema at run-time and we should be able to backfill the data relatively easy.

As a first step I think it'd help to only re-index models that actually changed, I think it's okay to just reindex everything and not just the data that got added/changed/removed but it'd speed-up and save quite a bit of money / energy to re-index only, say add-ons instead of everything (e.g stats data which is huuuuge).

**Comment by diox** [comment]
Yeah, we should add the ability to specify both the index and doc type we care about. Note that by default, we currently only reindex document in the `addons` index, which, confusingly, contains different document types: add-ons, collections and compatibility info. We don't include the `addons_stats` index by default.

**Comment by diox** [comment]
We never felt the need to implement it since it was filed, and we now only index add-ons on the main index, so this is even less important than before. Closing.
