### ISSUE TITLE
Fix django admin pages for Addons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5862]
STR:
- From django admin pages (/admin/models/) select Addons and pick an add-on in the list, e.g. https://addons-dev.allizom.org/en-US/admin/models/addons/addon/

Expected results:
- The admin page loads

Actual results:
- Oops, we had an error ! 

Traceback : https://sentry.prod.mozaws.net/operations/olympia-dev/issues/612196/

**Comment by SVSanta** [comment]
Verified as fixed in FF54(Win10 64Bit) in addons-dev.allizom.org
Postfix screenshot:
![admin page](https://user-images.githubusercontent.com/28138132/28009871-ac9628b8-6565-11e7-985c-dda773148dfe.PNG)
