### ISSUE TITLE
pop up blocker ultimate addon for Firefox

### ISSUE THREAD

**Issue by davyg57** [mozilla/addons-server#5866]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.).  : followed a Google link for "Pop Up Blocker Ultimate" for Firefox

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

![untitled-1](https://user-images.githubusercontent.com/29996256/27983308-34547216-63b1-11e7-84ff-70b36a2fad41.jpg)

**Comment by jvillalobos** [comment]
The listing is currently disabled due to pending code review issues.
