### ISSUE TITLE
Make `reviewer_scores.score` INT

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5869]
We need to correct/transfer large reviewer score for some reviewers (due to account transfer, contractor status change), but `reviewer_scores.score` is `smallint` so we can add/subtract only about 32k points at a time, which is cumbersome.

If we change the column to `int`, it's large enough for any changes we need to make.

**Comment by ValentinaPC** [comment]
Please add some STR for this or the label "qa: not needed".
Thanks!
