### ISSUE TITLE
0 results for "Any" filter in Django Admin\Addons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5870]
Originally filed at https://github.com/mozilla/addons-frontend/issues/2725

----------

Steps to reproduce:

1. From Django admin pages (/admin/models/) select Addons and pick an add-on in the list, e.g. https://addons-dev.allizom.org/en-US/admin/models/addons/addon/ .
2. From the "By type" tap on the "Any" filter and from "By status" tap on the "All" filter.

Expected results:
Add-ons with the selected filtering are displayed.

Actual results:
0 add-ons are displayed.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on AMO Dev servers.
Video Gif for this issue:
![any](https://user-images.githubusercontent.com/28138132/28010954-533b7c38-6569-11e7-9aa6-245bf290cf93.gif)

**Comment by SVSanta** [comment]
Retested and reopened this on FF54(Win 10).
Screenshot:
![any scr](https://user-images.githubusercontent.com/28138132/28109463-d809c5a2-66f7-11e7-8783-16d5b7abf020.PNG)

**Comment by SVSanta** [comment]
Verified this on AMO-dev FF54(Win 10 64Bit).
Postfix screenshot:
![any fixed](https://user-images.githubusercontent.com/28138132/28267096-187b1e1c-6b01-11e7-9035-18b5940f75c7.PNG)
