### ISSUE TITLE
Search sorting causes JS error

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5880]
Steps to reproduce:

1. Navigate to https://addons-dev.allizom.org/en-US/firefox/ .
2. ~Click on "View Mobile Site" button.~
3. Perform a search.(ex. "add" then tap "Enter")
4. ~Click on the "View classic desktop site" button.~
5. Click on any of the sorting categories.

Expected results:
The sorting is performed according to the selected filter. 

Actual results:
Nothing happens.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on AMO Dev servers.
Tapping on the browser "Back" button does not redirect the user to the previous page.
Video gif for this issue:
![broken link](https://user-images.githubusercontent.com/28138132/28061749-41883f50-6634-11e7-9023-96720100f303.gif)

**Comment by muffinresearch** [comment]
This has nothing to do with the mobile site. Just making a search on the current desktop site and clicking a filter shows a JS error:

```javascript
uncaught exception: expected string value for 'container' option; got undefined
```

**Comment by muffinresearch** [comment]
Looks to be caused by this line: https://github.com/mozilla/addons-server/blob/master/static/js/impala/search.js#L82

**Comment by muffinresearch** [comment]
I've updated the STR to reflect a quicker route to reproduction.

**Comment by muffinresearch** [comment]
This is fixed on -dev now.

**Comment by SVSanta** [comment]
Verified on FF54(Win 10) on AMO Dev servers.
Gif postfix:
![search fixed](https://user-images.githubusercontent.com/28138132/28116064-1320a65c-6710-11e7-8132-7124d0af2505.gif)
