### ISSUE TITLE
Remove old no_restart column in files table

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5881]
As part of #5772 we're going to replace the `no_restart` column in the `File` model by a `is_restart_required` column which is the opposite, for consistency.

To avoid breakage, the old column can't be removed directly, otherwise old code still running while deploying new migration would result in a 500 error. Instead, the plan is to:
1. For this push, remove the field from the model and set the database column as nullable. That way, both new and old code still works
2. For the next push, remove the column

This issue is simply about that second part, removing the old column.

**Comment by SVSanta** [comment]
Please add some STR or the label "qa: not needed". Thanks!
