### ISSUE TITLE
Update text on dev hub landing page

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#5887]
SIGNED-IN VIEW:

In the What's New promo box at the top, please replace the text block that starts with "Migrating your legacy add-on to WebExtensions?" with the following text:
- Ready to submit an add-on? Read our step-by-step tutorial on the submission process.
- Button: [See Tutorial](https://developer.mozilla.org/en-US/Add-ons/Distribution/Submitting_an_add-on)

SIGNED-OUT VIEW:

In the big blue box under the header "Tools", change the link associated with the text "Compatibility Checker" from https://compatibility-lookup.services.mozilla.com/ to https://addons.mozilla.org/developers/addon/check-compatibility

In the "Evolution in Add-on Development" promo box, change the text to:
- Header: Update Your Legacy Extension
- Body: There is a new, cross-browser standard for developing extensions in Firefox. You'll need to update your legacy extensions to stay compatible.

**Comment by ValentinaPC** [comment]
Verified these changes on AMO-dev FF54(Win 7)
All changes look and work as it should, except the "Compatibility Checker" link, which returns a 404 page.
Please see video:
![404](https://user-images.githubusercontent.com/15685960/28163702-ed5a2c16-67d4-11e7-8130-72b451649f1c.gif)

Reopening.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix video/screenshots:
![cc](https://user-images.githubusercontent.com/15685960/28202132-b02f47ec-687c-11e7-915b-908991df9651.gif)
![si](https://user-images.githubusercontent.com/15685960/28202302-5b58c6fc-687d-11e7-86be-361e6d550f19.png)
![so](https://user-images.githubusercontent.com/15685960/28202300-5b510d5e-687d-11e7-9021-2bb0c491325b.png)
"See Tutorial" loads - https://developer.mozilla.org/en-US/Add-ons/Distribution/Submitting_an_add-on
"Learn How" loads https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on
