### ISSUE TITLE
Update dev hub footer

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#5888]
Under the header "Documentation":
- change the link text from "WebExtensions" to "Extensions"
- under "Themes", add a fourth bullet point: [Porting](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension)

Under the header "Support", change the link text from "Review Policies" to "Policies"

Under the header "Tools", change the link associated with the text "Compatibility Checker" from https://compatibility-lookup.services.mozilla.com/ to https://addons.mozilla.org/developers/addon/check-compatibility

**Comment by ValentinaPC** [comment]
@atsay : Can we add a Compatibility Checker link for each server? If it is not a big deal. 
It is a bit misleading while testing on -dev and ending up on prod.
Thanks in advance!

Everything else was added as described above and work as expected while signed in or out, using en locale or other on AMO-dev FF54(Win 7).
Postfix screenshots:
![2017-07-17_1509](https://user-images.githubusercontent.com/15685960/28267274-069562ba-6b02-11e7-8b7a-a853908edbbe.png)

**Comment by atsay** [comment]
Ok, re-opening this issue to use a relative path to the compat checker so it's easier to test.

**Comment by ValentinaPC** [comment]
I'll wait for your decision, about the same link from Dev Hub page but while signed out, before marking this verified fixed.
Thanks!

**Comment by ValentinaPC** [comment]
Based on https://github.com/mozilla/addons-server/issues/5972#event-1174098545 I'll mark this issue verified.
