### ISSUE TITLE
"Back" button not working after switching back and forth 

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5894]
Steps to reproduce:
1. Navigate to https://addons-dev.allizom.org/en-US/firefox/ .
2. Click on "View Mobile Site" button.
3. Click on any item(ex. "Themes" button).
4. Click on the "View classic desktop site" button.
5. Click on the "Back" button.

Expected results:
The user is redirected to the previous page.

Actual results:
Only the link changes. The user is not redirected to the previous page.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on all AMO servers.
Gif for this issue:
![link scr](https://user-images.githubusercontent.com/28138132/28121164-eb8bf002-6722-11e7-8f28-acdd7191dbad.gif)

**Comment by eviljeff** [comment]
Not sure this is fixable with our current solution for switching to amo-frontend pages - it sets a cookie when you click the link and pressing back doesn't unset the cookie.

**Comment by eviljeff** [comment]
Going to wontfix this - the site switching is temporary thing, more for debugging than an end-user feature.
