### ISSUE TITLE
"View Mobile Site" is not working from themes categories pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5895]
Steps to reproduce:
1. Load Themes homepage on you device https://addons.allizom.org/en-US/android/themes/
2. Go to any theme category page i.e. https://addons.allizom.org/en-US/android/themes/abstract/
3. Click "View classic desktop site"
4. Click " View Mobile Site"

Expected results:
The mobile page is loaded again.

Actual results:
Nothing happens.

Notes/Issues:
- issue is not reproducing for extensions
- nothing displayed in the console
- issue is also reproducing while using new desktop pages

Verified on FF54(Android 7.1.2, Win 7). Reproducible around all AMO servers.
Video fro this issue:
![28123720-5e86ce5e-672a-11e7-8e2f-e08926f61004](https://user-images.githubusercontent.com/15685960/28126900-8b139548-6733-11e7-8adf-a62977d03eae.gif)

Originally filled at https://github.com/mozilla/addons-frontend/issues/2786

**Comment by eviljeff** [comment]
I think it's because addons-frontend is capturing:
https://addons.allizom.org/en-US/android/themes/abstract/
but not
https://addons.allizom.org/en-US/android/themes/abstract

**Comment by tofumatt** [comment]
Shoot, okay, we'll need to redirect. I thought we had a bug open for that... I'll investigate.

**Comment by muffinresearch** [comment]
@tofumatt there's the ops managed nginx config which defines what urls addons-frontend can serve if the mamo cookie is set or if it's a mobile UA. If a url isn't defined you get routed to addons-server.

I think there's a couple of options here:

* Make addons-server and addons-frontend use the same url by changing addons-server
   * make sure the old url non-slash url redirects correctly

Alternatively change addons-frontend's url config:

* File a bug to have ops to update the config to included routing the non-slash variant to addons-frontend and test on -dev
   * Addons-frontend would need to handle 301'ing missing slash maybe it does that already?

**Comment by tofumatt** [comment]
I think the front end already does handle it (search for trailingSlashesMiddleware) but the nginx updates removed its ability to do so. The second one could work pretty easily.

Matthew Riley MacPherson (sent from mobile)

**Comment by eviljeff** [comment]
Can the nginx change be to just capture everything starting /themes/ and sent it to addons-frontend?

**Comment by muffinresearch** [comment]
> Can the nginx change be to just capture everything starting /themes/ and sent it to addons-frontend?

Yep the second option should cover that.

**Comment by AlexandraMoga** [comment]
I think this can also be closed by #8115

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, WIn10x64 and Android 7.0
Also see results from #7524
