### ISSUE TITLE
Disable tracking/Google Analytics when DNT is enabled

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5901]
Since we're turning off GA when DNT is enabled in addons-frontend we should also do the same thing in addons-server.

Once implemented this should be tested on both addons.mozilla.org and the services.addons.mozilla.org (old discovery pane).

**Comment by muffinresearch** [comment]
Analytics code setup is here https://github.com/mozilla/addons-server/blob/0c2b633c592a882a51698949f2262773d1462b5b/static/js/zamboni/analytics.js

**Comment by vcarciu** [comment]
Verified as fixed on AMO , discovery pane, new frontend , using nightly , release and some secondary browsers and everything looks fine to me. I will mark the issue as verified based on my results from : https://public.etherpad-mozilla.org/p/ZQNxSyyVwM
