### ISSUE TITLE
Edit review or reply opens review bar for both Review and Reply

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5902]
Prerequisites:
Have a review with a reply submitted.

Steps to reproduce:
1. Navigate to the review.
2. Tap on "Edit review" button.
3. Select a star ratting and tap on the "Submit Review" button.
4. Tap on the "Edit reply" button.

Expected results:
The edit reply section is opened.

Actual results:
The edit reply and edit review sections are opened.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on Dev and Stg servers.
Gif for this issue:
![edit issue](https://user-images.githubusercontent.com/28138132/28163689-e51d81f6-67d4-11e7-95f8-f45fa0cc1f2b.gif)

**Comment by muffinresearch** [comment]
I'm thinking this is a wontfix since the new frontend has superceded the old UI and the latter will be switched over 100% some time later this year.
