### ISSUE TITLE
Move some editors helpers to editors/utils.py

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5903]
During the switch from jingo to django-jinja `editors/helpers.py` was renamed to `editors/templatetags/jinja_helpers.py`, but some of the functions and classes in that files are not jinja helpers they are just... regular helpers :)

We should move that stuff back to a more generic name like `utils.py`.

**Comment by ValentinaPC** [comment]
Please add some STR for this or the label "qa: not needed".
Thanks!

**Comment by diox** [comment]
QA: just make sure that reviewing an add-on still signs it / sets it to public correctly.

**Comment by ValentinaPC** [comment]
Verified submission, reviewing, public pages, Dev hub pages, signature, etc. using AMO-dev under FF54(Win 7).
Things are working as expected!
