### ISSUE TITLE
Make addons-internal.dev.mozaws.net accessible to anyone via the mozilla VPN

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#5909]
Currently to access http://addons-internal.dev.mozaws.net/ you need to be added a VPN access group, and a different one for prod and stage access.  Given the user has already authenticated via VPN, with 2FA, and will then have to log in to AMO, with it's own access groups, to do anything this extra requirement seems unnecessary.

**Comment by jasonthomas** [comment]
My understanding is that addons-internal endpoint will only be used to access the django admin pages. This is a limited set of users, I would say less then 15 people. Has the scope of addons-internal changed, and if so how? Right now I am not convinced that this needs to be accessible by every VPN user.

The VPN has route limitations and we can only push a limited amount of routes to a user. The way we get around this is by only pushing routes to users that need access to them by adding them to specific VPN groups.

**Comment by eviljeff** [comment]
Ah, I wasn't aware of the route limitations.  Pull #5783 was going to limit permissions to the extent that the addons-internal endpoint would have to be used for a much wider range of tasks throughout devhub, reviewer tools, and possibly accessing the API in the future.  The number of people (and the people) are likely to be the same though.

It seems like this issue is a cantfix, so I'll close.
