### ISSUE TITLE
Firefox crash when inputting wrong data in "Statistics Custom Date Range"

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5910]
Steps to reproduce:

1. Navigate to the statistics page for any add-on.
2. Click on the "Custom..." button.
3. Set the date range for "1000-07-13".
4. Click on the "Update" button.

Expected results:
The statistics for the selected range are displayed.

Actual results:
Firefox crashes, showing a "Close Script" window.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on all AMO servers.
This issue may happen with any data introduced by mistake, and it makes the statistics unusable for any other add-on, because the user is unable to change the date range between crashes.
This issue does not reproduce on Nightly.
Gif for this issue:
![statistics crash](https://user-images.githubusercontent.com/28138132/28166214-c35dae28-67df-11e7-9233-f1e1670dfa14.gif)

**Comment by muffinresearch** [comment]
@SVSanta Does Firefox actually crash (exit) or does it just make that tab unusable?

**Comment by SVSanta** [comment]
Firefox goes "Not Responding" for a few seconds, then I get the unresponsive script message warning.
Only the tab becomes unresponsive afterwards.
Screenshot:
![1](https://user-images.githubusercontent.com/28138132/28170467-2eec3b56-67ee-11e7-9deb-34efb79398ba.PNG)

**Comment by muffinresearch** [comment]
I don't think this is a p1, if the date picker is used normally it won't cause the hang, we should look to improve the validation here to prevent the hang.
