### ISSUE TITLE
Disable Google Analytics for local development

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#5913]
As mentioned in https://github.com/mozilla/addons-server/pull/5911#discussion_r127223534, we should disable GA from loading when developing locally.

**Comment by Bhupesh-V** [comment]
This doesn't seem to be fixed?
A simple `if window.location.host !== local IP` filter might fix this. 
Is this the change we are looking for?
https://github.com/mozilla/addons-server/blob/bf7d6d7a1bb9ed093755020f3f4c2d019f7c35fb/static/js/zamboni/analytics.js#L21-L45

**Comment by diox** [comment]
This hasn't been fixed yet, no. If you have a fix, please test it locally and send a PR.

**Comment by diox** [comment]
Removing the qa: not needed label - QA can't test that it's disabled for development but will be able to test that it's still working everywhere else.
