### ISSUE TITLE
Make it impossible to upload sources to a rejected version

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#5914]
When developers fail to upload sources after 7 days of waiting we reject add-ons with a comment. Sometimes, the developer will upload the sources to the already rejected version, which we cannot take action on and need to ask the developer to resubmit a new version.

I would appreciate if it were made impossible for the developer to upload sources to an already rejected version, with a note that a new version needs to be submitted.

**Comment by jvillalobos** [comment]
As I understand it, this would only entail changing the version management page ([example](https://addons.mozilla.org/developers/addon/remote-xul-manager/versions/1901145)). The changes would be:

* If no files in the version are pending review, and no source code has been uploaded, hide the `Source code` field.
* If no files in the version are pending review, and source code has been uploaded, show `Source code` field, allow the sources to be cleared, but don't allow new sources to be uploaded (remove upload button).
* If any file is pending review, keep as it is.

Does that look right, @kewisch?

**Comment by kewisch** [comment]
Almost. I'd prefer:

* If no files in the version are pending review, and no source code has been uploaded, replace the filepicker with a label "This version has already been rejected. Please submit a new version to attach sources".
* If no files in the version are pending review, and source code has been uploaded, show Source code field, don't allow new sources to be uploaded or cleared

I could accept clearing the sources, but I really think they should be immutable once a reject or approve has been done.

**Comment by jvillalobos** [comment]
> If no files in the version are pending review, and no source code has been uploaded, replace the filepicker with a label "This version has already been rejected. Please submit a new version to attach sources".

That message is aimed at a very specific use case. I'm suggesting we disable source code uploading if the version has been rejected, disabled by an admin, overriden by a new submission, or even approved. Detecting the specific use case when a rejection happened and changing the behavior only in that case seems like overkill to me.

> I could accept clearing the sources, but I really think they should be immutable once a reject or approve has been done.

I think that falls on the same category as "should we allow devs to delete versions?" and the decision is that we should. It's their property, so they should be able to remove it if they choose to.

**Comment by wagnerand** [comment]
Deleted versions are soft-deleted for a reason. If sources are soft-deleted
as well, that's fine with me, but hard-deleting them will increase review
efforts and is therefore beneficial to neither us nor to the developer.


Jorge Villalobos <notifications@github.com> schrieb am Fr. 14. Juli 2017 um
00:14:

**Comment by jvillalobos** [comment]
I'm okay with doing the same thing we do for versions.

One additional requirement: users with `Addons:Edit` should always see all upload options, so admins can upload sources in odd cases when they are needed and the dev doesn't have that option anymore.

**Comment by kewisch** [comment]
> > If no files in the version are pending review, and no source code has been uploaded, replace the filepicker with a label "This version has already been rejected. Please submit a new version to attach sources".
>
>That message is aimed at a very specific use case.

Then maybe just a more generic message? What I am trying to avoid is developers not knowing why they can't upload sources and then sending us email that they don't have the options we told them about.

**Comment by jvillalobos** [comment]
Okay, so how about this:

* If no files in the version are pending review, instead of the upload button, show a message saying `You can only upload sources for versions pending review.`.
   * If sources have already been uploaded for that version, keep the indication that they have been uploaded, and the option to clear them.
  * Users with `Addons:Edit` should still be able to see and use the upload button.
* If any file is pending review, keep as it is.

**Comment by kewisch** [comment]
Sounds good to me.

I was just reminded of this issue, because a developer cleared the sources for an already approved version (just the sources, not the version). As a result, I have to re-review their latest version from scratch because I have nothing to diff against.

This really also means that developers could wait for approval, clear sources, upload modified sources to the approved version, and then rely on us only checking diffs. 

If "You can only upload sources for versions pending review" will cover this case by not allowing them to upload sources for already approved versions, that would be great. Keeping approved source code available and not allowing it to be cleared would still be preferable to me.
