### ISSUE TITLE
Local maximum length of the text is set too small for long comments.

### ISSUE THREAD

**Issue by leni1** [mozilla/addons-server#5948]
### Local maximum length of the text is set too small for long comments:
1. Go to http://olympia.dev/en-US/editors/review/
2. Select an add-on to review. 
3. Type in a long stretch of text that wraps.
4. Submit your review.

### What happened?
In the process of reproducing bug [#3447](https://github.com/mozilla/addons-server/issues/3447), I found that typing in a long stretch of text where the review is entered cause a Data Error. I typed until the text automatically wrapped itself and there were no spaces in the text I entered. 

### What did you expect to happen?
For the text to be submitted and the effect of [#3447](https://github.com/mozilla/addons-server/issues/3447) to be demonstrated. 

### Anything else we should know?
![data_entry_1](https://user-images.githubusercontent.com/8645218/28365601-e807dac6-6c91-11e7-89da-134d2ad8bfcd.jpg)
![data_entry_2](https://user-images.githubusercontent.com/8645218/28365607-edce037c-6c91-11e7-8abf-ceb4d90a35b8.jpg)

**Comment by muffinresearch** [comment]
Would be good to find out if this is still reproducible.

**Comment by diox** [comment]
This field was changed to a `TextField` (was previously a `CharField` limited to 255 chars) a few months ago in 3e1f925458ff315635b6020c4cbfd5d8f819ce32
