### ISSUE TITLE
Compatibility cannot be checked for webextensions without target applications

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5950]
Steps to reproduce:
1. Load https://addons.allizom.org/en-US/developers/addon/check-compatibility this page
2. Check compatibility for a webextension that has no ID

Expected results:
Compatibility can be checked.

Actual results:
Compatibility is not checked. 

Notes/Issues:
An error message is displayed - "No Mozilla products listed as target applications"
Verified on FF54(Win 7). Issue is reproducing on dev and stage.
Screenshot for this issue:
![2017-07-19_1623](https://user-images.githubusercontent.com/15685960/28368916-afc95f2e-6c9e-11e7-8eab-0d304de8ba94.png)

**Comment by diox** [comment]
@jvillalobos should this page even work for webextensions ?

**Comment by jvillalobos** [comment]
No, and that tool will go away with legacy add-ons. If possible we should tweak the validation message. Otherwise we can add something to the static text on the page.

**Comment by diox** [comment]
Can you give me the validation error message to use ? And maybe a static text to use on the page as well ?

**Comment by jvillalobos** [comment]
Validation message: 

> This tool only works with legacy add-ons. WebExtension APIs are thoroughly [documented here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions).

Static text (first paragraph): 

>Use the field below to upload your add-on package. Note that this tool only works with legacy add-ons. WebExtension APIs are thoroughly [documented here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix screenshot:
![2017-07-24_0944](https://user-images.githubusercontent.com/15685960/28511219-ee323632-7054-11e7-930e-fbb0e89fb29f.png)
