### ISSUE TITLE
Expose strict_compatibility boolean in addons search and detail API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5952]
We need to expose the `strict_compatibility` boolean in the addons search and detail API so that the frontend can mimic what addons-server is currenly doing with the compatibility checks (things like greying our the install button if strict compatibility is enabled and the max version is too low compared to the user's browser).

**Comment by diox** [comment]
Assuming we're going to put this on the `Version` responses (*) next to `compatibility`, I'm having a hard time figuring out a name for this field. If we want to follow the `<verb>_<something>` scheme, the best I have at the moment is `should_compatibility_be_strictly_enforced`, which is a bit long. Any other suggestions ?

Another idea I had was to put it *inside* `compatibility`, returning not only `min` and `max` for each platform, but also `strict`. We would potentially copy the value several times, one for each platform, but maybe that's ok ?

(*) in the model, the field lives on `File` but I don't think it matters that much - we can write a simple wrapper as we have for some of the other fields - just making sure it's `True` if any of the `File` instances under that `Version` have strict compatibility enabled.

**Comment by muffinresearch** [comment]
`is_strict_compat` or `is_strict_compatibility`?

**Comment by diox** [comment]
It feels a bit weird to just use `is_strict_compatibility`. It feels like bad english because strict compatibility is not really a thing you can be (the other fields we have, `is_webextension`, `is_restart_required` or `is_source_public` work much better)

**Comment by muffinresearch** [comment]
> It feels a bit weird to just use is_strict_compatibility. It feels like bad english because strict compatibility is not really a thing you can be (the other fields we have, is_webextension, is_restart_required or is_source_public work much better)

Maybe `is` -> `has`?

**Comment by diox** [comment]
That would work for me. Or `is_strict_compatibility_enabled`.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
