### ISSUE TITLE
Reviewer without name shows up in site credits

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#5954]
User (retrieved from source code)
https://addons.mozilla.org//en-US/firefox/user/Anonymous-6307327/
![image](https://user-images.githubusercontent.com/607379/28391291-ab8e7f36-6cdd-11e7-9b79-76e394d758e4.png)

**Comment by wagnerand** [comment]
I tried to just set a display name for that user, but I can't since that user has been deleted and in order to change it, I would have to set an email address.

The general problem is that a lot of queries don't exclude deleted users. ¯\_(ツ)_/¯

**Comment by EnTeQuAk** [comment]
> The general problem is that a lot of queries don't exclude deleted users.

I think that'll have to change eventually.

**Comment by jvillalobos** [comment]
Closing because we're not porting this page to the new site (see #6830).
