### ISSUE TITLE
External auth for the new APIs

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#5964]
This issue is to discuss the possible approaches for external auth for the new AMO apis and to get an idea of how much work it would take to provide an implementation.

We're looking to answer the following:

* What authentication would make the most sense?
* How much work would be involved? E.g. rough estimate of what it would take to implement.
  * The estimate should include any time to build auth flows and revocation etc.

**Comment by eviljeff** [comment]
Oauth2 seems to be standard.  
We probably need to decide where the flow for generating tokens will live - in addons-frontend (with APIs that would generate a new key, revocation, etc - I guess relying on the existing internal auth) or addons-server (if so, where - devhub is fine... but if we intend a non-developer audience to use them, then perhaps not)

**Comment by jvehent** [comment]
@g-k and @peterbe have evaluated options for socorro and can probably contribute their findings here.

**Comment by EnTeQuAk** [comment]
To be fair, do we think this is ever going to happen? If not we should probably close this issue.

**Comment by diox** [comment]
Clearly not.
