### ISSUE TITLE
Make MDN links non-localizable

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#5966]
This is kind of a follow-up on #5897.

Some links to MDN are localizable. No matter whether we hard code locale slugs or not, I'm not sure those links should be localizable. We can probably come up with a better mechanism if we need a way to dynamically determine the best locale.

Occurrences:
```
src/olympia/addons/templates/addons/report_abuse.html:10
src/olympia/browse/templates/browse/search_tools.html:93
src/olympia/applications/templates/applications/appversions.html:18
src/olympia/applications/templates/applications/appversions.html:35
src/olympia/devhub/templates/devhub/new-landing/components/overview.html:5
src/olympia/devhub/templates/devhub/personas/submit.html:195
src/olympia/pages/templates/pages/dev_faq.html:47
src/olympia/pages/templates/pages/dev_faq.html:74
src/olympia/pages/templates/pages/dev_faq.html:183
src/olympia/pages/templates/pages/dev_faq.html:195
src/olympia/pages/templates/pages/faq.html:99
src/olympia/pages/templates/pages/faq.html:163
src/olympia/pages/templates/pages/faq.html:172
```

~~@atsay to confirm.~~

**Comment by wagnerand** [comment]
What we'd look for here specifically is removing the `trans` keyword or the `_()` shortcut from links to MDN, to make them non-localizable.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: me (@wagnerand)

**Comment by harry-7** [comment]
I would like to take up this task.

**Comment by EnTeQuAk** [comment]
@harry-7 go for it! Please let us know if the information in the issue helps or if you need anything else.

**Comment by caitmuenster** [comment]
Hey @harry-7, how's it going with this bug?

**Comment by harry-7** [comment]
@caitmuenster  I am unable to setup the developer environment on my pc. I raised an issue on the issue tracker but no improvement.

**Comment by wagnerand** [comment]
Hi @harry-7 what is the link to the issue you opened?

**Comment by harry-7** [comment]
@wagnerand  #6066  is the link

**Comment by harry-7** [comment]
@wagnerand

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
