### ISSUE TITLE
FileViewer: Tab stops change not working

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#5969]
Originally reported by @erosman in https://github.com/mozilla/amo-validator/issues/392

It was a useful feature and it has been a while that Tab stops change is not working ie changing it has no effect at all.

For example on one of the following:

```
https://addons.mozilla.org/en-US/firefox/files/compare/398047...384466/
https://addons.mozilla.org/en-US/firefox/files/browse/398047/
```

On the left pane:
**Tab stops: 3 ↓ ↑**

Changing the above value (3) or clicking on either ↓ ↑ (which would change the value 3) would increase or deceases the number of leading space (ie indentation) eg:

```
var selector;
                 var selector;
                               var selector;
```

However, above hasn't been working for a while.
I hope that helps.

> ( wagnerand ) Probably a regression from mozilla/addons-server@ecadb47

**Comment by jvillalobos** [comment]
We're dropping this file viewer soon.
