### ISSUE TITLE
Same apps listed during a dictionary submission regardless of what apps are in the instal.rdf file

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5970]
Steps to reproduce:
1.  Submit a dictionary available for Thunderbird and Firefox i.e. https://addons-dev.allizom.org/en-US/firefox/addon/dictionary-for-ff-and-thunder/
2. At submission add-on details step, observe available categories and corresponding apps

Expected results:
Categories displayed should be only for apps added in the `install.rdf.`

Actual results:
No matter with what apps is the add-on compatible, categories for Thunderbird, Firefox and SeaMonkey will be displayed.

Notes/Issues:
- checking all categories is mandatory
- categories will be also listed in Basic information section from Dev Hub
- `small issue regarding the number of categories that should be checked and the available ones
`
Screenshots for this issue:
![2017-07-21_1132_001](https://user-images.githubusercontent.com/15685960/28456002-cbe1e26e-6e09-11e7-9e7e-8f2d91afdabe.png)
![cats](https://user-images.githubusercontent.com/15685960/28456030-e440b8c6-6e09-11e7-8391-cfd8c0b97897.png)

**Comment by diox** [comment]
It's a consequence of having them ignoring compatibility - dictionaries will be available for every app - but I'd say it's a good thing...

**Comment by ValentinaPC** [comment]
If you are ok with this, I am too.
Then, maybe just fixing the small context issue regarding the number of categories listed for each app?

**Comment by diox** [comment]
We don't get enough dictionary submissions to care about that IMHO - not worth adding an extra string to translate just to handle the fact that there is only one category per app for dictionaries.
