### ISSUE TITLE
Make the link relative for compatibility checker

### ISSUE THREAD

**Issue by apoorvaeternity** [mozilla/addons-server#5972]
### Describe the problem and steps to reproduce it:
The link to compatibility checker on dev hub under "Tools" is hard-coded.It should be relative.

### What happened?
Clicking on the link always ends up on compatibility checker on -prod.

### What did you expect to happen?
The link should end up on compatibility checker on the same server.
If the user is on -dev then the link should take him to the compatibility checker on -dev.

### Anything else we should know?
![screenshot_tools](https://user-images.githubusercontent.com/21103831/28461396-0d356bda-6e34-11e7-8274-75c1aab53a90.jpg)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix video: 
![cc](https://user-images.githubusercontent.com/15685960/28510815-fbaedf74-7052-11e7-8013-9bfc1a268740.gif)
