### ISSUE TITLE
No "Please enter a URL." warning in "Account Settings"

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5974]
Steps to reproduce:
1. Login.
2. Navigate to the "Account Settings" page.
3. Introduce an invalid url in the "Homepage" section.
4. Scroll down and click on "Update Account".

Expected results:
The message "Please enter a URL." is displayed.

Actual results:
No warning message is displayed.

Notes/Issues:
- Verified on FF54(Win 7). Issue is reproducing on all server.
- This issue has a low reproducibility rate.
- Gif for this issue:
![no url warning 1](https://user-images.githubusercontent.com/28138132/28462836-c683ebe8-6e25-11e7-8418-5a1b7a42267f.gif)

**Comment by muffinresearch** [comment]
Closing since this will be superceded by https://github.com/mozilla/addons-frontend/issues/3144
