### ISSUE TITLE
dgsdazh6745a

### ISSUE THREAD

**Issue by lamoure** [mozilla/addons-server#5982]
im on this page: https://addons.mozilla.org/de/firefox/user/sharath-av/?src=api

clicking on this link: https://addons.mozilla.org/de/firefox/addon/soundgrab/?src=userprofile

and then i get referred to this one: https://addons.mozilla.org/de/firefox/addon/soundgrab/?src=userprofile

**Comment by jvillalobos** [comment]
If you have an issue to report, you'll have to set a sensible title and more details than what you provided. Closing for now.
