### ISSUE TITLE
Hide "compatibility reports" link for web extensions in devhub

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5986]
The "compatibility reports" link in devhub sidebar menu when editing an add-on is useless for web extensions and should be hidden.

**Comment by SVSanta** [comment]
Verified as fixed on AMO-dev FF54(Win 10).
Postfix screenshot:
![compatibility](https://user-images.githubusercontent.com/28138132/28613873-659c58ee-71fc-11e7-8461-2e30c825e98d.PNG)
