### ISSUE TITLE
Add-on submission broken if you use en-GB to submit an en l10n'd webext.

### ISSUE THREAD

**Issue by sblask** [mozilla/addons-server#5988]
From my question on dev-addons@mozilla.org:

I tried to submit a new extension (https://github.com/sblask/webextension-enhanced-image-viewer/releases/download/1.0.0/enhanced_image_viewer-1.0.0-firefox.zip), but the page to do that looks like in the attachment. No input fields where you'd expect one. When I try to submit anyway it says field required. There is a display: none on the input element, but changing it manually doesn't make the form submit either. I tried current Firefox, clean Firefox nightly and current Chromium, they all have the same problem. Nothing but "Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead." in the console.

![screenshot](https://user-images.githubusercontent.com/681955/28518834-ae97027c-7069-11e7-95fd-88912175b653.png)

**Comment by eviljeff** [comment]
Weird, I can submit that add-on zip without a problem locally and on addons-dev.  Can you link to the broken listing?

**Comment by ValentinaPC** [comment]
I think @sblask is trying with a non-en locale.... seems like that kind of behavior. I may be wrong.

**Comment by sblask** [comment]
https://addons.mozilla.org/en-US/developers/addon/enhanced-image-viewer6/submit/details 

```
distribution.searchplugins.defaultLocale;en-US
general.useragent.locale;en-GB
intl.locale.matchOS;true
```

My OS locale is en-GB.

@eviljeff if you say it works for you, that means that it's not an issue that I use localization strings in the title (https://github.com/sblask/webextension-enhanced-image-viewer/blob/master/manifest.json#L31)?

I also have this issue that is locale related: https://github.com/mozilla/addons-server/issues/5459

**Comment by eviljeff** [comment]
good call ... it's the `en-GB` locale (the dev edition profile I use for work is `en-US`).
I'm not sure if it's `en-GB` per se, or if it's the combination of that and the default locale for the add-on being `en` which we don't support (AMO only supports `en-US` and `en-GB`)

**Comment by eviljeff** [comment]
yeah, I can't replicate even using `en-GB` locale, if I change the zip to use `en-US`.

**Comment by eviljeff** [comment]
@sblask you should be able to work around this by either changing the add-on to use en-US, or submitting from http://olympia.dev/en-US/developers/addon/submit/distribution instead.

**Comment by sblask** [comment]
I can try later today. I assume I have to delete the existing submission first? Will I get a problem because the ID is already used?

This page: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization should probably be updated to reflect this issue (unless this gets fixed soon) because it happily gives `en` as example for default_locale.

I never minded, but I sometimes had an issue when submitting a new version. There is the page where description and notes to reviewers can be specified and sometimes (might be just have happened for this add-on: https://addons.mozilla.org/en-us/firefox/addon/skip-redirect/ which I initially submitted without localization and added support for it later.) the description field would be missing. Sounds like the same issue to me.

**Comment by sblask** [comment]
Deleting the extension and submitting it again with default locale being en-US fixed the issue.
