### ISSUE TITLE
Simplify add-on compatibility code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5990]
Add-on compatibility is defined as the set of conditions that disables (greys out) the install button for an add-on on AMO.

Some of the code to handle add-on compatibility is present in triplicate, depending on the context (detail page, listing page) and template style (impala/non impala), with some variants functioning in a completely different way than the rest (for some we handle it directly in the template, for some the template outputs some html which is escaped, stored in a data attribute, read by js, which displays it according to another set of parameters...). We even have some conditions for Firefox < 4 and others for Firefox 10, and who knows what else.

This needs to be simplified, if only for my own sanity to do #5277 and #5482. I propose the following:
- Remove all conditions we can find for super old Firefox versions, keeping only ~~one~~ two incompatibility scenarios: the add-on has strict compatibility enabled, or uses binary components.
- Replace all incompatibility messages by just `This add-on is not compatible with your version of Firefox.`
- Remove the `Install Anyway` button in the compatibility tooltip, completely preventing installs of add-ons that have opted in to strict compatibility or use binary components (which should only be possible for legacy add-ons) if the browser version does not match.

This is similar to [what @jvillalobos was proposing](https://github.com/mozilla/addons-server/issues/5277#issuecomment-315185528) except my idea is to do it now, not behind a waffle. It should only really affect legacy add-ons that enabled strict compatibility/use binary components anyway (*). My reasoning is that it affects a small number of users (few add-ons concerned in the first place, and would only be relevant if they have a low `maxVersion` set compared to what the end-users trying to install it are using)

(*) Unless someone can see a reason besides strict compatibility/binary components for greying out an add-on install button.

**Comment by diox** [comment]
@jvillalobos : thoughts ?

**Comment by EnTeQuAk** [comment]
I agree, that code is a huge pain in the ass and cleaning that up does make things a lot easier long-term. Keeping @diox' sanity is usually a good idea too :)

**Comment by diox** [comment]
Going to close this and comment in [the google docs about finding compatible versions for pre-57](https://docs.google.com/document/d/1ui9Zq1iCzIA5DIneHN5i1LzGhs9HOdN9h8532SuqavY/edit#) - between the other 2 issues we have already opened it should be enough.
