### ISSUE TITLE
static page:  shield study 16 - pioneer

### ISSUE THREAD

**Issue by gregglind** [mozilla/addons-server#5994]
Static consent page for Study 16 - Pioneer

https://bugzilla.mozilla.org/show_bug.cgi?id=1382761

**Comment by SVSanta** [comment]
Please add some STR or the label "qa: not needed". Thanks!

**Comment by EnTeQuAk** [comment]
https://addons-dev.allizom.org/en-US/firefox/shield_study_16 is the page this added, this looks great and I think that @gregglind and co are testing these too.
