### ISSUE TITLE
Admin Tools gives "404 Not Found" error

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#5998]
Steps to reproduce:

1. Login with any admin user.
2. Click on "Tools>Admin Tools".

Expected results:
The "Admin Tools" page is displayed.

Actual results:
A 404 page is displayed.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on the STG and DEV servers.
Gif for this issue:
![admin tools 404](https://user-images.githubusercontent.com/28138132/28563102-7e2018a8-712d-11e7-9cee-78c72c17b1d4.gif)

**Comment by wagnerand** [comment]
Afaik, admin pages are behind VPN now.

**Comment by SVSanta** [comment]
My VPN is up and running, same issue for the rest of the team, maybe we haven't been granted access yet.

**Comment by wagnerand** [comment]
Summoning @jasonthomas ...

**Comment by jasonthomas** [comment]
@SVSanta Please file a bug in Cloud Services: Operations: AMO Operations with the users in your team that need access.

**Comment by SVSanta** [comment]
Hello Jason, I think that Stuart Colville already sent you an email with all ldap accounts for our team. Please confirm and I will close this issue.

**Comment by jasonthomas** [comment]
Just saw the email. I've added everyone to the correct VPN group. You will need to reconnect to the VPN to access the new endpoint. Please ping me on irc if you have questions. Thanks!

**Comment by SVSanta** [comment]
Verified as fixed on AMO-dev FF54(Win 10).
Postfix screenshot:
![admin working](https://user-images.githubusercontent.com/28138132/28614173-84f5b09a-71fd-11e7-99ae-3925109bb8e6.PNG)
