### ISSUE TITLE
Add-on indexing (or other task) sometimes happen too early

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#5999]
We can sometimes end up indexing add-ons too early before the transaction has been committed. I believe this is what's been happening in those cases:

https://github.com/mozilla/addons-server/issues/4894
https://github.com/mozilla/addons-server/issues/5588

We developed [post-request-task](https://github.com/mozilla/django-post-request-task) to solve this, but never deployed it on AMO (it was deployed on Marketplace however) because of [issues with validation never completing when it was enabled](https://github.com/mozilla/addons-server/issues/1552). In addition, we had [at least one instance where we fired up a celery task *synchronously*](https://github.com/mozilla/addons-server/blob/4f76d663cdb72fda6fe0859de4e40e54931f8db4/src/olympia/devhub/views.py#L673-L688), which was broken with post-request-task.

We need to find a solution for this to stop incoherent data like mentioned in the 2 issues above. 

Note that recent django versions will bring [`on_commit`](https://docs.djangoproject.com/en/1.11/topics/db/transactions/#django.db.transaction.on_commit) but this will just allow us to write `post-request-task` in a cleaner way, the same problems we had with it will likely remain. Plus, we're not on the right django version yet anyway.

**Comment by EnTeQuAk** [comment]
Assigning to me to look into this in the coming weeks as part of my attempt to work on django 1.11 and potentially celery 4 upgrade.

**Comment by ValentinaPC** [comment]
Adding some example of add-ons that no longer exist, but are still displayed in AMO public pages
- Webext-+beta - https://addons-dev.allizom.org/en-US/firefox/addon/webext-beta/
- <script>alert(‘Problem123')</script> - https://addons-dev.allizom.org/en-US/firefox/addon/scriptalertproblem1script/
- Warrior Forum Formatter - https://addons-dev.allizom.org/en-US/firefox/addon/warrior-forum-formatter/
- Webext-to many reasons - https://addons-dev.allizom.org/en-US/firefox/addon/webext-to-many-reasons/

Also if we click the "View classic desktop site" from the Up & Coming page we will see first 3 incmplete add-ons in old pages too, clicking on them will redirect to a black search results page:
![upand_coming](https://user-images.githubusercontent.com/15685960/32008222-625baea0-b9b4-11e7-8eac-1ac435b58d31.png)

**Comment by muffinresearch** [comment]
Since this is more visible on the new frontend I'm going to move it up to p2.

**Comment by EnTeQuAk** [comment]
QA: Can you do additional testing around upload and validation of add-ons to verify this didn't break anything?

I just switched the flag on -stage and it's active on -dev as well.

cc @krupa @ValentinaPC

**Comment by ValentinaPC** [comment]
Sure! Will do this today and tomorrow as well.

**Comment by ValentinaPC** [comment]
Verified this on AMO-stage and -dev FF56 (Win 7) and I have a question: things where fixed only for the add-ons that will be deleted/disabled from now on, or for the already deleted add-ons also?

Because "Trending extension" listing still displays incomplete add-ons.
See homepage https://addons-dev.allizom.org/en-US/firefox/ or "See more trending extensions" page https://addons-dev.allizom.org/en-US/firefox/search/?sort=hotness&type=extension

**Comment by EnTeQuAk** [comment]
Yes, only for new cases that would be broken. Existing ones weren't fixed, we primarily fixed the root case but didn't do anything (yet?) to fix broken data.

**Comment by diox** [comment]
Yeah we'll need a reindex to fix existing add-ons.

**Comment by ValentinaPC** [comment]
Verified different scenarios using AMO-dev FF56(Win 7), like: add-on with its only version disabled, add-on with no version, deleted add-on, submission, new file and new version upload, auto approve, check for updates and everything seems to work as expected.

I suppose https://github.com/mozilla/addons-server/issues/6873 has nothing to do with this issue, yes?

**Comment by jzav** [comment]
Are there any news here, please? I have exactly same issue as described at https://github.com/mozilla/addons-server/issues/6727#issue-266604054...

**Comment by diox** [comment]
@jzav it should have been fixed a couple weeks ago - but we haven't recalculated ratings for affected add-ons. Can you link your add-on?

**Comment by jzav** [comment]
Thank you for quick response. And here is the link: https://addons.mozilla.org/en-US/firefox/addon/at-your-command/

**Comment by jzav** [comment]
@diox Can I somehow help to resolve this issue?

**Comment by diox** [comment]
The issue is fixed. The ratings for your add-on will automatically be recalculated as soon as a new one is posted.
