### ISSUE TITLE
Error message in Disco Pane under each add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6000]
Steps to reproduce:
1. Load about:addons using Nightly browser
2. Activate/deactivate the legacy pref while accessing Disco Pane

Expected results:
No issues displayed.

Actual results:
An error message is displayed under each add-on/theme.

Notes/Issues:
- I could no longer reproduce it a new Nightly profile.
Screenshot:
![nightly](https://user-images.githubusercontent.com/15685960/28567646-b8afe4c2-713b-11e7-8634-84b912183120.png)

**Comment by eviljeff** [comment]
That message is coming from https://github.com/mozilla/addons-frontend/blob/77c2a5b3e937aadc51bd3ed70f84369eee192c40/src/disco/components/AddonCompatibilityError/index.js#L49 so I'd assume it's a frontend issue but it's when `reason` is something 'else' so it's possible it originates in the API, I guess.  Have you changed your user agent to a non-Firefox one?  That could explain it.

**Comment by muffinresearch** [comment]
@ValentinaPC do you still have the old profile that caused this around - can you check if the user-agent string is looking as expected?

**Comment by ValentinaPC** [comment]
@muffinresearch : unfortunately I had a problem with the profile I reproduce this and is no longer accessible.
But, I've looked to the user agent - if you are talking about the string from about:support - and seemed ok.
I don't know how to change it, though. Or maybe something I did, changed it?

**Comment by muffinresearch** [comment]
@ValentinaPC ok, if this can be reproduced then we can look at it, if it's difficult to repro it's going to be difficult to debug.

**Comment by ValentinaPC** [comment]
@muffinresearch : If you want you may close this and I'll reopen as soon as I will reproduce it again.

**Comment by muffinresearch** [comment]
@ValentinaPC Ok lets do that. Thanks!

**Comment by ValentinaPC** [comment]
I managed to reproduce this as follows:
1. Create a new clean Nightly profile
2. Install https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher/ (set `extensions.allow-non-mpc-extensions` pref on true if not able to install it)
3. Change the default user agent
4. Change the Disco Pane to point to -dev (not reproducing for -stage Disco Pane redirect)
5. Uninstall the add-on
 ..... ta daaaa :)

I guess that the main issue is why the message is not removed after uninstalling the add-on; 
Thanks for you patience :D

**Comment by eviljeff** [comment]
so... the issue is that you get an error message about an unsupported browser if you change your user agent to indicate you have an unsupported browser?

**Comment by ValentinaPC** [comment]
> so... the issue is that you get an error message about an unsupported browser if you change your user agent to indicate you have an unsupported browser?

 "I guess that the main issue is why the message is not removed after uninstalling the add-on."

**Comment by eviljeff** [comment]
Ah.  Is the add-on definitely reverting the user agent on uninstallation?  (check about:config for the user agent) If not it's a problem with the add-on.  If the user agent _is_ being reset it's strange AMO is getting the old one.

**Comment by ValentinaPC** [comment]
The add-on used is no longer compatible with FF57 - so that exact scenario cannot be checked, and I was not able to find an add-on that works on changing the user agent. Do you know an add-on that works, to try with another? Thanks!

**Comment by eviljeff** [comment]
I don't - I'm not sure webextensions can change the user agent.  
If we can't reproduce I'm going to close.  Please reopen if we find a reproducible scenario in the future.
