### ISSUE TITLE
Conflicting setuptools versions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6001]
`make update_docker` calls https://github.com/mozilla/addons-server/blob/master/Makefile-docker#L96 which installs the latest _setuptools_ version. Later on, we install a very specific version of it in https://github.com/mozilla/addons-server/blob/master/requirements/prod.txt#L439 which causes failures if a new _setuptools_ version has been released but we haven't locked it in the requirements (yet):

(irrelevant log output removed)
```
$ make update_docker
docker-compose exec worker make update_deps

Collecting setuptools
  Using cached setuptools-36.2.2-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.0
    Uninstalling setuptools-36.2.0:
      Successfully uninstalled setuptools-36.2.0
Successfully installed setuptools-36.2.2

pip install --no-deps --exists-action=w -r requirements/dev.txt
Collecting setuptools==36.2.0 (from -r requirements/prod.txt (line 439))
  Using cached setuptools-36.2.0-py2.py3-none-any.whl
Installing collected packages: certifi, setuptools
  Found existing installation: certifi 2017.4.17
    Uninstalling certifi-2017.4.17:
      Successfully uninstalled certifi-2017.4.17
  Running setup.py install for certifi ... done
  Found existing installation: setuptools 36.2.2
    Uninstalling setuptools-36.2.2:
      Successfully uninstalled setuptools-36.2.2
  Rolling back uninstall of setuptools

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 305, in clobber
    ', '.join(info_dir))
AssertionError: Multiple .dist-info directories: /usr/lib/python2.7/site-packages/setuptools-36.2.2.dist-info, /usr/lib/python2.7/site-packages/setuptools-36.2.0.dist-info
make: *** [install_python_dependencies] Error 2
make: *** [update_docker] Error 2
```

**Comment by EnTeQuAk** [comment]
My action plan here is the following: I'd like to remove `setuptools` from `requirements/prod.txt` since we are explicitly installing and upgrading it in our `Dockerfile` and there's no inherit need to keep it up-to-date, on-build is perfectly fine.

We do explicitly install the latest version of pip and setuptools in every docker container right now anyway.

On the other hand, there's a very good reason to simply pin our dependencies so there's a disadvantage to removing it from requirements/prod.txt - but it feels like a chicken-egg problem. We can't install from requirements files unless we have a proper pip/setuptools version.

@diox @eviljeff opinions?

**Comment by eviljeff** [comment]
remind me why we have to install setuptools in the docker container before `install_deps`?

**Comment by EnTeQuAk** [comment]
We don't have to do that explicitly, generally only installing / upgrading pip to the latest version suffices. That'll usually pull an up-to-date version of setuptools though.

**Comment by EnTeQuAk** [comment]
Unassigning myself for now until I really have time to work on it.
