### ISSUE TITLE
Add throttling to the Abuse API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6004]
To prevent abuse, natch.

**Comment by eviljeff** [comment]
@jvillalobos what limits should we put on the abuse API?  And should they apply to everyone*?

e.g. a user is limited to 1 abuse report per minute.  Or should it be like 10 an hour? or 20 a day?  (you get the idea)

* everyone meaning both an authenticated user and an anonymous user (identified by their IP address for uniqueness)

**Comment by eviljeff** [comment]
I did 1 per minute, regardless of authenticated or not.  Can be changed.

**Comment by jvillalobos** [comment]
20 a day sounds okay to me. Someone doing bulk reporting (say, for spam) may run into a 1-per-minute limit.
