### ISSUE TITLE
where is Firefox Cookie Swap extension:  https://addons.mozilla.org/firefox/3255/ 

### ISSUE THREAD

**Issue by akehsanz** [mozilla/addons-server#6008]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I cannot find the Firefox Cookie Swap extension:
 https://addons.mozilla.org/firefox/3255/ 
### What happened?
just putting me here...
### What did you expect to happen?
go to there...
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

how to fix easily...

**Comment by diox** [comment]
Your link is wrong, where did you get it ? The correct one is https://addons.mozilla.org/en-US/firefox/addon/3255/ which redirects to https://addons.mozilla.org/en-US/firefox/addon/cookieswap/
