### ISSUE TITLE
User reviews could include application version and OS

### ISSUE THREAD

**Issue by darktrojan** [mozilla/addons-server#6014]
Because people sometimes post useless reviews ("It's not working!"), any more information would be more useful to the developer, and maybe also to other users reading reviews. ISTR the Play Store lists the device and Android version with reviews.

**Comment by jvillalobos** [comment]
Reviews aren't meant to be used for support or bug reports. Adding metadata to a review that is in itself useless (and probably will be deleted by a moderator) probably won't add much for the developer to act upon.

We plan to unify the feedback UI so users are better aware of their options (review, get support, report abuse) and hopefully avoid all the misreporting we get now. I'd rather not add more info that is potentially considered private and users don't necessarily want to share.

**Comment by eviljeff** [comment]
@jvillalobos so, wontfix?

**Comment by jvillalobos** [comment]
Yeah, we'll look into ratings and reviews more closely next year.
