### ISSUE TITLE
"Admin Tools" issue on STG and DEV

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#6018]
Steps to reproduce:

1. Connect to the Mozilla VPN.
2. Login with any admin user.
2. Click on "Tools>Admin Tools".

Expected results:
The "Admin Tools" button is not displayed or the button redirects to the: "https://addons-internal.dev.mozaws.net/" and "https://addons-internal.stage.mozaws.net/" links.

Actual results:
A 404 page is displayed after clicking the "Admin Tools" button.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on the STG and DEV servers.
The issue is also reproducible when click on "Admin Manage" from the add-on details page, click on "Admin Page" from Reviewer Tools and click on "Admin Manage" from Edit Information.
Gif  and screens for this issue:
![admin tools 404](https://user-images.githubusercontent.com/28138132/28620356-4344b278-7215-11e7-829b-da9f9f17c759.gif)

![admin 1](https://user-images.githubusercontent.com/28138132/28624082-9dd0cc3a-7220-11e7-891a-a7ca1374edeb.PNG)

![admin 2](https://user-images.githubusercontent.com/28138132/28624089-a25cd262-7220-11e7-817a-e9637013f489.PNG)

![admin 3](https://user-images.githubusercontent.com/28138132/28624094-a630229a-7220-11e7-93e2-1e975c561d87.PNG)

**Comment by muffinresearch** [comment]
Filed an ops bug here to take care of this with a redirect: https://bugzilla.mozilla.org/show_bug.cgi?id=1386196

**Comment by SVSanta** [comment]
Verified as fixed on AMO-dev FF55(Win 10)
Postfix gif:
![admin tools](https://user-images.githubusercontent.com/28138132/29458297-0a5c1d9c-8427-11e7-87ba-6fe88fb37b63.gif)
