### ISSUE TITLE
500 error page while adding "Notes" from Manage User page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6020]
Prerequisites: 
Being logged with an admin account.

Steps to reproduce:
1. Load Manage User page i.e. https://addons-dev.allizom.org/en-US/firefox/users/edit/2392246
2. Type a "Reason for change" and "Notes"
3. Click "Update Account" button

Expected results:
Account is updated or a message is displayed.

Actual results:
An "Oops..." page is loaded.

Notes/Issues:
- issue is also reproduced using the new link - https://addons-internal.stage.mozaws.net/en-US/firefox/users/edit/5198343
- if the "Anonymize" option is checked we hit the 404 page which is due to VPN changes.

Video for this issue:
![500](https://user-images.githubusercontent.com/15685960/28625335-90f0eb4a-7224-11e7-8e8b-9232be10ae81.gif)

**Comment by muffinresearch** [comment]
Sentry report is here: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/629463/

**Comment by muffinresearch** [comment]
Will be superceded by https://github.com/mozilla/addons-frontend/issues/2749
