### ISSUE TITLE
The AMO -dev server returns 502

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#6026]
### Describe the problem and steps to reproduce it:
Access https://addons-dev.allizom.org/ with a new profile.

### What happened?
A 502 error message is displayed.

### What did you expect to happen?
The page from https://addons-dev.allizom.org/ should be displayed without any issues.

### Anything else we should know?
This issue is reproducing constantly on AMO-dev server.
Verified on Firefox 56.0a1 under Wind 7 64-bit.

Please see the video for this issue:
![502-dev](https://user-images.githubusercontent.com/15885467/28657178-7607bfa4-72ae-11e7-89bc-64f7eb8f95cb.gif)

**Comment by kumar303** [comment]
There was a problem with the cryptography library which was fixed in https://github.com/mozilla/addons-server/pull/6025 Dev should be functioning again. Sorry about that.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on Firefox 56.0a1 under Wind 7 64-bit.

Please see the attached video:
![fixed502](https://user-images.githubusercontent.com/15885467/28705421-57ae4882-7378-11e7-9144-20b1e5194009.gif)
