### ISSUE TITLE
No "Up and Coming" themes in some pages for some categories

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6027]
Steps to reproduce:
1. Load themes Websites category i.e. https://addons.allizom.org/en-US/firefox/themes/websites
2. Click on "View All Up & Coming" link https://addons.allizom.org/en-US/firefox/themes/websites?sort=up-and-coming
3. Navigate between pages

Expected results:
There are no display or layout issues.

Actual results:
No results displayed in page 3 and after.

Notes/Issues:
- same results for other categories like: Causes, Foxkeh.
Verified on AMO-stage (Win 7). Issue is also reproducing on -prod.
Video for this issue:
![catthemes](https://user-images.githubusercontent.com/15685960/28661873-dca8a89c-72c0-11e7-8956-7044495e63a4.gif)

**Comment by muffinresearch** [comment]
@diox @EnTeQuAk any ideas about this one?

**Comment by diox** [comment]
The count in this page is hardcoded for performance reasons, and sometimes wrong depending on the popularity of themes. 

See https://github.com/mozilla/addons-server/blob/11748c0f70e5aa630bd68bb554b7a6b5106eb7b0/src/olympia/browse/views.py#L307-L313 and https://github.com/mozilla/addons-server/blob/11748c0f70e5aa630bd68bb554b7a6b5106eb7b0/src/olympia/browse/views.py#L244-L247

This is not a new bug, I don't think it should be a P2.

**Comment by ValentinaPC** [comment]
I've added the label P2 just considering that any user can run into this issue. :)
But, you are entitle to do as you think is more correct.

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  Bugs with our new front-end can be filed at https://github.com/mozilla/addons-frontend/issues/new
