### ISSUE TITLE
Remove compatibility popup message and "Install Anyway" option

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6028]
When an add-on is deemed incompatible with your current app (e.g. Firefox) version, but you still have the right app (usually because the add-on has enabled strict compatibility, which is not the default), the install button is greyed out and a message saying that the add-on is not compatible with your version appears.

Depending on the reason behind the incompatibility, we can display a small "?" icon with a popup giving more information about the incompatibility. In addition, clicking the greyed install button opens a popup repeating the message and giving you the option to install the add-on anyway.

As part of the Firefox 57 compatibility changes, we want to remove those 2 popups. The reasoning is that the message inside the first popup is not helpful to end-users anyway - it tells them that the add-on has opted in to strict compatibility or uses binary components, which does not help them - and the install anyway option would lead users to try to install completely broken add-ons.

**Comment by ValentinaPC** [comment]
Verified this as fixed on AMO-dev FF54(Win 7).
Postfix screenshots:
![add-on_details](https://user-images.githubusercontent.com/15685960/28882158-134c14aa-77b3-11e7-960b-60eb691c8b06.png)
![eula](https://user-images.githubusercontent.com/15685960/28882160-13504c14-77b3-11e7-80b3-6300b709f2ca.png)
![homepage](https://user-images.githubusercontent.com/15685960/28882161-1353a36e-77b3-11e7-8438-246923387833.png)
![listing](https://user-images.githubusercontent.com/15685960/28882159-134de8de-77b3-11e7-819a-ca9ac54a29b2.png)
![otherbr](https://user-images.githubusercontent.com/15685960/28882157-134be6a6-77b3-11e7-8379-2597d232315e.png)
![vhistory](https://user-images.githubusercontent.com/15685960/28882156-134a2a82-77b3-11e7-9aff-77971a8f70d8.png)
