### ISSUE TITLE
Search is unavailable in Admin page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6030]
Steps to reproduce:
1. Load Admin Tools page i.e. https://addons-internal.stage.mozaws.net/en-US/admin/
2. Make a search after add-on name or ID

Expected results:
A list of add-ons is displayed.

Actual results:
Search is unavailable.

Notes/Issues:
- not reproducing on -dev
- reproducing also from Server Tools - Manage Elastic Search - https://addons-internal.stage.mozaws.net/en-US/admin/elastic
- 503 service unavailable error in the console

Verified on -stage FF54(Win 7).
Video fro this issue: 
![search](https://user-images.githubusercontent.com/15685960/28675791-92f67662-72f1-11e7-91ec-eec9ef69b9ab.gif)

**Comment by wagnerand** [comment]
@ValentinaPC This should have been fixed in https://github.com/mozilla-services/cloudops-deployment/pull/963. Could you please re-check?

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO - stage FF54(Win 7).
Search is working as expected using https://addons-internal.stage.mozaws.net/en-US/admin/
Postfix video:
![search in stage](https://user-images.githubusercontent.com/15685960/28768392-224798f0-75e0-11e7-8082-67c53eed3639.gif)
