### ISSUE TITLE
"Log out" from Admin Tools is returning a 500 error page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6031]
Steps top reproduce:
1. Load a page from Admin Tools where you have a Log out link i.e. https://addons-internal.stage.mozaws.net/en-US/admin/models/access/group/
2. Click on "Log out"

Expected results:
User is logged out.

Actual results:
An 500 error page is displayed.

Notes/Issues:
- "View site" link is working as expected
Verified on FF54(Win 7). Issue is reproducing for dev and stage.
Video for this issue:
![logout](https://user-images.githubusercontent.com/15685960/28676595-b987989a-72f3-11e7-9531-8f3c26405cd4.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/623664/

The `django/contrib/admin/templates/registration/logged_out.html` template is parsed using django-jinja and not django template engine. It's just a matter of updating `JINJA_EXCLUDE_TEMPLATE_PATHS` to include `registration\/`.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev https://addons-internal.dev.mozaws.net/en-US/admin/models/ using FF54(Win 7) - log out is working as expected.
Postfix video:
![logout](https://user-images.githubusercontent.com/15685960/28777395-8b19383e-7603-11e7-8a3f-80e18a74f504.gif)
