### ISSUE TITLE
Admin ACR Reports dashboard is down with "Search Unavailable" message

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6043]
If I go to https://addons-internal.prod.mozaws.net/en-US/admin/compat, I get an error page with the message "Search Unavailable". This page displays reports from the Add-on Compatibility Reporter, and it's used to identify add-ons with recent compatibility problems.

It was working recently, so this might be related to the move to the internal server behind the VPN (cc @jasonthomas).

**Comment by wagnerand** [comment]
Same error message as #6030.

**Comment by eviljeff** [comment]
I can replicate this locally too so it's not VPN related

**Comment by bqbn** [comment]
This is because the ES hostname isn't configured correctly on the internal instances. I just filed a PR for this, which should fix it by next release.

**Comment by jasonthomas** [comment]
This should be fixed on prod now.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
The page indicated in the first comment is still not working on -dev (works on -stage) even if the #6030 was fixed.
Screenshot from dev:
![compat](https://user-images.githubusercontent.com/15685960/28769548-ab60f4e8-75e4-11e7-8f90-190c112bae9b.png)

Reopening until further notice.

**Comment by jasonthomas** [comment]
The ES host configuration is correct on dev and other search functionalities work. Is the /admin/compat area failing because we are missing data in elasticsearch?

**Comment by diox** [comment]
That would be my guess as well. @jvillalobos is it working in prod?

**Comment by jvillalobos** [comment]
Yes, it's working on prod now.
