### ISSUE TITLE
Stop including links to the user account profile on other pages.

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6044]
part of #5592 
This is relating to addons-server pages, so primarily devhub, but probably reviewer tools too (as standard reviewers currently aren't 'admin enough' to see everyone's account profile pages).  No need to change existing user facing pages as the account profile will only be unavailable on the new front-end.

**Comment by jvillalobos** [comment]
Closing in favor of the more targeted https://github.com/mozilla/addons-server/issues/9339. There may be some followups on devhub and the reviewer tools, but we'll deal with them as they come up.
