### ISSUE TITLE
Update text for developer profile notification box "news and events"

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#6045]
Brian Smith just advised that we revise the opt-in language from "stay up-to-date with news and events relevant to add-on developers" to "stay up-to-date with news and events relevant to add-on developers (including the about:addons newsletter).

Any chance we could get this patched by Aug 2 (next issue send date)? 

**11:11am PST edit: No need for an unscheduled push -- it's ok if this goes through with the scheduled push on Aug 3.**

**Comment by ValentinaPC** [comment]
@eviljeff : can you please point out the page where the changes were made?
Thanks!

**Comment by eviljeff** [comment]
https://addons-dev.allizom.org/en-US/firefox/users/edit in the notifications section at the bottom

**Comment by ValentinaPC** [comment]
Verified as fixed on AMo-dev FF54(Win 7); 
Postfix screenshot:
![2017-07-31_1424](https://user-images.githubusercontent.com/15685960/28775745-45b67e84-75fc-11e7-822f-61aa764fc6f0.png)

From some users there is a "new" label after the notification options, why is that?
![new](https://user-images.githubusercontent.com/15685960/28775953-22a11ebc-75fd-11e7-8ea1-8e1070a67b31.png)

Thanks!

**Comment by eviljeff** [comment]
It's shown when the notifications are being set for the first time.

**Comment by ValentinaPC** [comment]
I did not change anything, just accessed the page.

**Comment by ValentinaPC** [comment]
This can be marked as verified-fixed.
Thaks, @eviljeff !
