### ISSUE TITLE
Invalid strict_min_version causes silent upload failure (can't select platform)

### ISSUE THREAD

**Issue by mw-ding** [mozilla/addons-server#6046]
### Describe the problem and steps to reproduce it:

1. upload my add-on package
2. get some warnings after the validation process
3. **[This is when the problem happen]** cannot select the platform checkboxes, because they are all disabled 
4. click the "continue" button but got error in submit the add-on

![error](https://discourse-paas-production-content.s3.amazonaws.com/original/2X/6/644487f4b6ca75dbfdaa98201aa4e718409e1ad4.png)

### What did you expect to happen?

expect to select the checkboxes and submit my add-on package successfully.

### Anything else we should know?

For more details and conversations, please refer to this post:

https://discourse.mozilla-community.org/t/trouble-in-publishing-addon-developed-by-react-js/17362/4

**Comment by jvillalobos** [comment]
Can you attach or point to the file you're trying to upload?

**Comment by mw-ding** [comment]
@jvillalobos can you leave me an email address so that I can only share it with you?

**Comment by mw-ding** [comment]
@jvillalobos ping?

**Comment by jvillalobos** [comment]
You can send it to amo-admins AT mozilla DOT org, or jorge AT mozilla DOT com.

**Comment by mw-ding** [comment]
@jvillalobos Thanks. Already send you the link. Please take a look

**Comment by jvillalobos** [comment]
The problem is this line in your manifest: `"strict_min_version": "1.0"`

Removing it fixes the upload problem. We should probably make this case a hard error, though I'm not sure if this is linter code or server code. /cc @EnTeQuAk @wagnerand

**Comment by mw-ding** [comment]
It works now. Thanks Jorge.

**Comment by EnTeQuAk** [comment]
The linter does not know about app versions, amo-validator did but that was mostly a hack. It's probably best to get this validated in addons-server.

**Comment by mw-ding** [comment]
Thanks guys for the help. Feel free to close this issue. Problem fixed in my end already.

**Comment by diox** [comment]
Fixing https://github.com/mozilla/addons-server/issues/6226 should (hopefully) have fixed this.

**Comment by vcarciu** [comment]
Verified as fixed : 
![strictmin](https://user-images.githubusercontent.com/1583842/29968479-8810db08-8f24-11e7-804c-c7f836ed050e.png)
