### ISSUE TITLE
[ideas] Filter add-ons permissions during search

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#6048]
Expect to happens:
1. Indexing and allows to filter ["permissions"](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions) during search.
2. Show popular permissions on the sidebar of the search page (like filtering "Compatible for"), allowing click them to add filter to query, like permissionsHas() and permissionsNot().
3. In addition, I hope combinable filters to replace the current category and "sort by", they are can not combined to query.
4. I know the above may be resource constraints for development, indexing and caching, just write and hope.

Possible use scene:
1. Find all add-ons for like modify github.com, find something of interest.
2. Find all ["chrome_url_overrides"](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/chrome_url_overrides) add-ons, as well as allow like "overrides-newtab" as identifier in amo search.
3. As reviewer tool for find all add-ons that use specific permissions.
4. ...

**Comment by eviljeff** [comment]
summoning Product @jvillalobos

**Comment by jvillalobos** [comment]
That's too low level (and really complex) for a search tool that's intended for the general public. Developers can use descriptions, categories and tags to make their add-ons easier to find for people looking for specific aspects of them (like the github.com example, or if someone was looking for "new tab"). Admin reviewers use different tools to look into add-ons, so this isn't a case we should consider either.

I don't think this brings enough benefit to warrant the development effort.
