### ISSUE TITLE
Review mails to addon developer doesnt contain the review comment

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-server#6049]
### Describe the problem and steps to reproduce it:
A user reviewed an addon, the mail was sent to addon developer.

### What happened?
The mail received was not having the actual review comment

### What did you expect to happen?
The mail should have the review comment.

### Anything else we should know?
<img width="563" alt="screen shot 2017-07-30 at 9 39 30 am" src="https://user-images.githubusercontent.com/5318732/28750510-5abb08dc-750b-11e7-84f8-f66523beec7d.png">

<img width="911" alt="screen shot 2017-07-30 at 9 39 47 am" src="https://user-images.githubusercontent.com/5318732/28750512-62cad796-750b-11e7-974c-a35166b87df3.png">

**Comment by jvillalobos** [comment]
I haven't had this problem before. It's possible that the review was submitted initially without text and later edited. This needs reliable steps to reproduce.

**Comment by ValentinaPC** [comment]
I could reproduce the initial issue, if following the suggestion @jvillalobos added above.

STR:
1. Write an empty review for any add-on while using the new desktop pages i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-compat/
2. Edit the empty review by adding some text
3. Observe Fake Mails logs - https://addons-internal.dev.mozaws.net/en-US/admin/mail

Results:
Initial review text "None" is not replaced with the new text.

**Comment by eviljeff** [comment]
Is the issue more that we don't send a new email if the review text is edited by the user?

**Comment by Rob--W** [comment]
Most if not all of the review mails that I got over the past few weeks / months don't include the review text, only the rating.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/6817 is newer but probably explains the issue, so closing in favor of that one.
