### ISSUE TITLE
Unable to search past page ~1250 of results

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6053]
Steps to reproduce:
1. Make an empty search on AMO-dev https://addons-dev.allizom.org/en-US/firefox/search/?q=&appver=54.0&platform=windows
2. Go to last page

Expected results:
Last page is loaded without any issues.

Actual results:
An "Search Unavailable" page is loaded. 503 error in the console.

Notes/Issues:
- issue is reproducing on both -dev and -stage

Verified on AMO-dev Ff54(Win 7).
Video for this issue:
![search](https://user-images.githubusercontent.com/15685960/28770929-9e33f2b6-75e9-11e7-936c-c4fb5c11cd57.gif)

May be regression from #5209

**Comment by diox** [comment]
There are too many results: https://sentry.prod.mozaws.net/operations/olympia-stage/issues/631649/

In aff92bc15e1533ceb334760a01c48529803b8383 I added something in the API to handle this... and I just realized we have 2 implementations of `ESPaginator`, one with the fix (the API) and one without...

**Comment by diox** [comment]
We should replace `amo.utils.ESPaginator` by `api.paginator.ESPaginator` but first, @bqbn, can you check what's the value of `index.max_result_window` setting in ES ? It should be 25000. See https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings

**Comment by bqbn** [comment]
`index.max_result_window` was using the default value `10000`, and I've just set it to `25000`.

@diox, why 25000 and not other value?

**Comment by diox** [comment]
@bqbn : 25000 is slightly higher than the number of public add-ons we have, so this allows all pages of an empty search with no filters to work.

**Comment by diox** [comment]
Taking this to eliminate the duplicate `ESPaginator`.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Issue is still reproducing for themes and collections.
Please see video:
![search-themes-coll](https://user-images.githubusercontent.com/15685960/28823180-fd84005e-76c4-11e7-9e4e-79fbbf3e7533.gif)

**Comment by diox** [comment]
Ugh there are a lot of those... this will need to be handled by an artificial limit in the app's pagination, I think.

**Comment by bqbn** [comment]
I don't understand why this issue happens to ES v5 but not ES v1.6.

The difference I can tell is that v1.6 doesn't have `index.max_result_window` setting, however considering we already set `index.max_result_window` to 25000 for v5, shouldn't the issue be gone, or is it a different issue now?

**Comment by diox** [comment]
We had a similar issue in v1.6, but I don't remember what the max limit was.

It turns out that 25000 is enough if you only search for regular add-ons... but if you include personas (lightweight themes) or collections the number of potential results grows significantly and that limit becomes too low.

I do think we should keep the limit at 25000, though, and solve this on the app side. There is merit in browsing through all add-ons in search (some people do that with the API to do stats etc about public add-ons) but searching through all lightweight themes or collections is less useful and I don't mind blocking it at some upper limit.

**Comment by ValentinaPC** [comment]
Verified as fixed for themes and collections using FF54(Win 7).
Issue is still **reproducing** for add-ons, while making an empty search with filters set to "Any Firefox" and "Windows" - to display more results.
Please see video:
![add-ons](https://user-images.githubusercontent.com/15685960/29355718-c45022a6-827a-11e7-9517-93bfc930bcd3.gif)

**Comment by ValentinaPC** [comment]
How it looks like now while makin an empty search from Extensions homepage and going to page 401 - https://addons-dev.allizom.org/en-US/firefox/search/?page=401&platform=windows&type=extension
![untitled](https://user-images.githubusercontent.com/15685960/31330709-2609f0ca-ace8-11e7-81df-56228abcf193.png)

**Comment by ValentinaPC** [comment]
This is still happening on AMO-dev and AMO-stage using FF56(Win7).
After an empty search in Extensions section and navigating to last page, the "Search Unavailable" message is displayed.
Please see screenshot:
![addons](https://user-images.githubusercontent.com/15685960/31482690-f32c558e-af31-11e7-9c4b-8f3c3632a944.png)

Reopening.

**Comment by EnTeQuAk** [comment]
That change is not yet on -stage. But -dev is insteresting, apparently it has a different configuration than -prod:

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/639271/ says that the max window size is 10000 while it's 25000 on prod. @bqbn can you adapt the configuration on -dev too or why is there a difference?

**Comment by bqbn** [comment]
Yeah, I've just set ```max_result_window``` to 25000 on -dev and -stage.

**Comment by EnTeQuAk** [comment]
Closing this again then should be working fine on -dev, -stage and -prod now.

I filed https://github.com/mozilla/addons-server/issues/6703 to make sure it doesn't happen again.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
No "search unavailable" listed after an empty search for extensions, themes or collections, but if, more pages are displayed, they are working until 25.000 results... that means if we have 5000 pages, nav will work only until page no 1250 and last page will never work, are we ok with this?
