### ISSUE TITLE
refine which users are "developers"; which users can see all user account profiles

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6056]
part of #5592

Currently `UserProfile.is_developer` is defined as a user that has _any_ type of add-on associated with them, (owner, developer, viewer, 'listed' or not), that is not deleted, regardless of status.  Only users that are `is_developer` will have their profiles publicly viewable by all.

Users that will be able to see any user account profile (admin-ish) have `Users:Edit`.

Do either of these restrictions need to be changed?

**Comment by jvillalobos** [comment]
For profile visibility, I would prefer that to be limited to:

1. Users with an owner or developer role
2. in a listed add-on
3. that is not deleted (doesn't matter other status)

Is your suggestion that we change the meaning of `UserProfile.is_developer`? Where else is it used?

**Comment by eviljeff** [comment]
> in a listed add-on

Technically, there aren't any listed add-ons.  An add-on with >0 non-deleted listed versions?

> Is your suggestion that we change the meaning of UserProfile.is_developer? Where else is it used?

Yes.  Though if we change it as you suggest I think we'll need an alternate property - it's mainly used to control if a user account can be deleted, though we use it to show/hide a few other random bits of UI.

**Comment by jvillalobos** [comment]
> Addon having a current version, which essentially means a listed version that is either approved or awaiting approval (e.g. not rejected). But the add-on having >0 listed versions is doable too if you want.

Either way is fine. In a different issue I was wondering if having an `Approved` status is sufficient, but I don't know about the edge cases.

**Comment by eviljeff** [comment]
Requiring the Add-on to be `Approved` works.  It's also pretty straightforward - I worry about having to explain the logic involving.

**Comment by eviljeff** [comment]
I'm going to make the changes with #6042 fwiw

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
