### ISSUE TITLE
Fix ElasticSearch 5 deprecation warning

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6060]
`[2017-07-26T14:11:16,878][WARN ][o.e.d.c.ParseField       ] Deprecated field [exclude] used, expected [excludes] instead`

https://github.com/mozilla/addons-server/issues/5209#issuecomment-318208925

Not blocking release since it continues to work. Would be nice to fix though.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
