### ISSUE TITLE
"Continue to download" button is not working for incompatible add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6061]
Steps to reproduce:
1. Set contribution roadblock for an incompatible with you FF version add-on i.e. https://addons-dev.allizom.org/en-US/firefox/addon/pearl-fiber/
2. Click on "Continue to download" button

Expected results:
Button is working and redirects to "Meet add-on developer" page.

Actual results:
Button is not working.

Notes/Issues:
Verified on AMO-dev Ff54(Win 7).
Video fro this issue:
![notclik](https://user-images.githubusercontent.com/15685960/28782742-c0f9dcc0-7616-11e7-81e3-8504d015741a.gif)

#6028

**Comment by diox** [comment]
This is an interesting edge case. Not sure what to do in this scenario. Letting the user continue to the roadblock page feels wrong, they should not be able to install the add-on anyway. Maybe just change the message, leaving "Add to Firefox" and greying out the button as normal? IMHO there is no point in showing the roadblock page at all if the add-on version we're linking to is incompatible.

**Comment by muffinresearch** [comment]
> This is an interesting edge case. Not sure what to do in this scenario. Letting the user continue to the roadblock page feels wrong, they should not be able to install the add-on anyway. Maybe just change the message, leaving "Add to Firefox" and greying out the button as normal? IMHO there is no point in showing the roadblock page at all if the add-on version we're linking to is incompatible.

I don't know that anything needs to be done for this case. @jvillalobos what do you think?

**Comment by jvillalobos** [comment]
Agree with @diox. It'd be nicer to show the normal button, disabled.

**Comment by diox** [comment]
With contributions roadblock going away in #6072 and the fact that it's an edge case to begin with I don't believe it's worth fixing.

**Comment by ValentinaPC** [comment]
"Continue to download" from inside a collection is still redirecting to "Meet the developer" page.
Keep this in mind while implementing #6072 .
