### ISSUE TITLE
Small display issue for incompatibility message at hover

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6062]
Steps to reproduce:
1. Hover over an incompatible add-on in a category page or in "versions history" page i.e. https://addons-dev.allizom.org/en-US/firefox/addon/who-is-this-person/versions/

Expected results:
Text is aligned.

Actual results:
Text is not aligned.

Notes/Issues:
Verified on AMO-dev FF54(Win 7). 
Screenshots for this issue:
![allvers](https://user-images.githubusercontent.com/15685960/28783048-bc1eb9cc-7617-11e7-96c6-15f40a626f2c.png)
![cat](https://user-images.githubusercontent.com/15685960/28783054-c2840b82-7617-11e7-8d27-c0c82e122cbb.png)
 
#6028

**Comment by diox** [comment]
I'll find a way to remove the "View other versions" text when you're already on the versions page. And try to do something for the homepage as well...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
![homepage](https://user-images.githubusercontent.com/15685960/28826388-acfbe314-76d2-11e7-9d3d-0f76ca47353d.png)
![listing](https://user-images.githubusercontent.com/15685960/28826389-acfcd5d0-76d2-11e7-8313-e792145c46b4.png)
