### ISSUE TITLE
HTML User details are not rendered correctly in "Meet add-on_name developer" page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6064]
Steps to reproduce:
1. Load Edit Profile page and add some accepted HTML code in Details section https://addons-dev.allizom.org/en-US/firefox/users/edit 
2. Save the changes
3. Create a developer profile in Dev Hub and access the page "Meet add-on_name developer" page i.e. https://addons-dev.allizom.org/en-US/firefox/addon/popup-incompat/developers
4. Observe "Who is developer_name?" section

Expected results:
Developer description is displayed without any issues.

Actual results:
Developer description is displayed using HTML code.

Notes/Issues:
Verified on AMO-dev FF54(Win 7). Issue is also reproducing on -stage.
Screenshots from this issue:
![untitled](https://user-images.githubusercontent.com/15685960/28784347-d9d3bf0e-761b-11e7-98a6-8e815af18399.png)

**Comment by diox** [comment]
This page will be removed in #6072 so I don't think it's worth looking into this.
