### ISSUE TITLE
Add a Contributions URL field in the developer tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6070]
Part of #6069.

Add a `Contributions URL` field to the Edit Information page, below Tags. The tooltip explanation should read: `If you would like to request monetary contributions from your users, set this to a page where they can do so.`.

In edit mode, below the text field, there should be a list of the supported domains: `Supported domains: paypal.com, patreon.com`. I'll update this list when we get feedback from developers. The field should be validated so it only accepts URLs on those domains. Subdomains (like pay.paypal.com) should be accepted as well.

**Comment by diox** [comment]
Is it actually possible to set up a paypal URL to request a payment/donation without using http://paypal.me/ ?

**Comment by jvillalobos** [comment]
Yeah, it does look like we should be using paypal.me instead of paypal.com. Not sure if people with business accounts get different URLs, though.

**Comment by jvillalobos** [comment]
We should also add a note to the existing Manage Developer Profile and Manage Payments sections indicating that they're going away:

`This page will soon be removed in favor of the Contributions URL field in the main Edit page. Make sure to use that field to keep Contributions enabled.`

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(win 7)
Postfix screenshots:
![contrib](https://user-images.githubusercontent.com/15685960/29772161-1efdeb6e-8c00-11e7-8ef8-54c8ea986e3d.png)
![edit](https://user-images.githubusercontent.com/15685960/29772165-22db864c-8c00-11e7-8ab9-be608518ecd8.png)
![edit_001](https://user-images.githubusercontent.com/15685960/29772168-299b9fee-8c00-11e7-9607-16b3493eb817.png)
