### ISSUE TITLE
Update Contribute section in listing pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6071]
Part of #6069.

The Contribute button, when visible, should open the Contributions URL (#6070) in a new tab (using the outgoing redirect like all external URLs).

Remove link to Developer Profile, developer image, and suggested amount from contribution block.

**Comment by eviljeff** [comment]
To work with the existing contribution functionality - which we aren't going to remove immediately as we have to notify developers - the new 'Contribute' button will only be shown when the developer hasn't set up the Paypal stuff already.  That seems the cleanest way of doing it.

**Comment by eviljeff** [comment]
@jvillalobos can you clarify the logic re: existing contribution functionality co-existing with this new contribution url?

Currently the logic is:
- if paypal/charity stuff is set, show the old button, including links to developer profile
- elseif the developer profile is set, just link to that
- elseif the new contribution url is set, show a button that links to that url.

i.e. work like now unless the developer doesn't have any of the paypal/profile set up.

**Comment by jvillalobos** [comment]
This issue and following issues in #6069 should be waffled-off (or not implemented) until we have given developers some time to use the new field and be prepared. With this issue the plan is to change to the new URL wholesale. No need to have both systems working in parallel.

**Comment by eviljeff** [comment]
Okay, the developers can fill in the field in devhub but it won't be exposed anywhere publicly until the old contribution feature is removed/disabled.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7) and obtained the following:
- while setting the Contributions URL from Edit Information page for an add-on - no public contribution can be seen in add-on public details page - https://addons-dev.allizom.org/en-US/developers/addon/video-downloadhelper/edit
- for add-ons that have old contributions already set and we add a Contribution URL noting changes - https://addons-dev.allizom.org/en-US/firefox/addon/smoothwheel/

@eviljeff : I guess this is normal, as far as the old contribution is not yet removed, yes?

**Comment by eviljeff** [comment]
@ValentinaPC you'll need to set the waffle switch `simple-contributions` in /admin to be able to test this now.

**Comment by ValentinaPC** [comment]
Ok. I've enabled the flag, and obtained the following results:
1. While the Contribution URL is set the Contribute button from add-on public pages redirects to the desired link, but is listed in the wrong side of the page - intended?
![position](https://user-images.githubusercontent.com/15685960/29868208-bce3d352-8d86-11e7-8b69-30a5c498e0be.png)

2. The "Requires Payment?" option form Edit Information page has something to do with the Contribution URL part? if yes, what?

3. For old Contribution add-ons the public page will not contain any contribution sections

4. Reviewer Tools pages will not contain any contribution section if Contribution URL is set.

5. No link for developer profile in Contribution section from add-on public pages.

Please let me know if everything here is as supposed to be.
Thanks!

**Comment by eviljeff** [comment]
>  While the Contribution URL is set the Contribute button from add-on public pages redirects to the desired link, but is listed in the wrong side of the page - intended?

The stylesheet changes didn't deploy properly on -dev, should be working now.

>    The "Requires Payment?" option form Edit Information page has something to do with the Contribution URL part? if yes, what?

No connection (though I agree it's potentially confusing)

>   For old Contribution add-ons the public page will not contain any contribution sections

correct.  That's all going to be removed (in other issues)

>    Reviewer Tools pages will not contain any contribution section if Contribution URL is set.

Reviewer tools wasn't specified in the issues, so it's not going to be shown there.

>    No link for developer profile in Contribution section from add-on public pages.

correct.  The developer profile is being dropped in #6072

**Comment by ValentinaPC** [comment]
Seems like now, the contribution section is not listed at all if the Contribution URL is set in Dev Hub.
Example: https://addons-dev.allizom.org/en-US/firefox/addon/video-downloadhelper/
Screenshots:
![2017-08-30_1914](https://user-images.githubusercontent.com/15685960/29883009-8960eba6-8db7-11e7-8f9d-46bca9875a84.png)
![addon](https://user-images.githubusercontent.com/15685960/29883010-896476ae-8db7-11e7-9a3d-c0e008c68ee5.png)

**Comment by eviljeff** [comment]
Did you turn off the waffle?  It was just there an hour ago (or I wouldn't have been able to verify the style sheet change)

**Comment by ValentinaPC** [comment]
The waffle was on. Now looks and works as expected!
Postfix screenshot:
![contrib](https://user-images.githubusercontent.com/15685960/29909751-0a7f1528-8e30-11e7-8f37-0d388ddecbce.png)

Last question - only for my knowledge - according to the text listed in the Contribution zone from add-on details page, the user is asked to make a small contribution for that specific add-on, while clicking on the "Contribute" button he will be redirected to the general paypal.me page - where will he find the add-on? Thanks!

**Comment by eviljeff** [comment]
The url is supposed to be the personal one to your contributions on paypal.me. We only enforce that it's to that domain though... I don't know if @jvillalobos wants it locked down further so only specific urls can be used?  (e.g. with regex)  @jvillalobos please log a follow up issue if so.

**Comment by jvillalobos** [comment]
No, we'll only enforce the domain. If someone messes up the URL, it's their own fault ;)
