### ISSUE TITLE
Remove Developer Profile and Roadblock pages from Contributions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6072]
Part of #6069.

The Developer Profile (Meet the Developer) and contribution roadblock pages are no longer needed.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
Developer Profile and Roadblock pages are no longer displayed in Dev Hub or working with direct links.
![2017-09-27_1556](https://user-images.githubusercontent.com/15685960/30914457-70268f10-a39c-11e7-83b2-6d469a10422b.png)
