### ISSUE TITLE
 Remove Manage Developer Profile and Manage Payments sections

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6073]
Part of #6069.

Remove the no longer needed Manage Developer Profile and Manage Payments sections from the devhub.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Both pages are no longer available on Dev Hub.
Tried also with direct links - behaving as expected.
Postfix screenshot:
![no_page](https://user-images.githubusercontent.com/15685960/30803875-edfdd6dc-a1f3-11e7-8d49-e3c2ec62a945.png)
