### ISSUE TITLE
 Remove Contributions section from developer statistics dashboard

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6074]
Part of #6069.

Note on timing: the communication that goes out to developers before the switch the new contributions system will explain to them when the switch will happen. After the switch, they should get a few weeks to export their contributions stats before we completely remove them.

**Comment by eviljeff** [comment]
@jvillalobos got a date for when we can remove the stats?

**Comment by jvillalobos** [comment]
Ugh, I forgot about this. I don't think it's worth sending an email just for this... Let's do it after Nov 1st.

**Comment by eviljeff** [comment]
I think stats are fairly self-contained, so keeping them around shouldn't stop the rest of the code from going.

**Comment by ValentinaPC** [comment]
Are you talking about removing contributions from here:
![2017-11-24_1607](https://user-images.githubusercontent.com/15685960/33213788-b7633eb0-d131-11e7-9f86-a8ac36200b17.png) or from other place?
Thanks!

**Comment by eviljeff** [comment]
From there, and some other (non-visible) cleanup.  But the deployment failed so you weren't seeing the new code - fixed now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win 7).
Contributions link was removed from statistics dashboard.
Postfix screenshot:
![removed_contrib](https://user-images.githubusercontent.com/15685960/33217077-33432bfa-d13f-11e7-8ce2-a1d2c078a9dc.png)
