### ISSUE TITLE
name, description, hotness and summary are not excluded from Addon _source field

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6078]
See https://github.com/mozilla/addons-server/pull/6077 for a few more details.

We exclude certain fields from addons search `_source` for performance reasons. This doesn't work for `name`, `description`, `hotness` and `summary` while others are properly excluded.

**Comment by EnTeQuAk** [comment]
Interesting, if so then we should at least update the comment introduced in https://github.com/mozilla/addons-server/pull/6077/files#diff-a8438459c522f502af8aaeb71ac3b352R2319

**Comment by diox** [comment]
Re-opening to update that test
