### ISSUE TITLE
"Not available for your platform" message is missing for dictionaries

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6079]
Steps to reproduce:
1. Submit a dictionary which is not compatible with your operating system i.e. https://addons-dev.allizom.org/en-US/firefox/addon/dictionary-for-ff-and-thunder/ (compat with Linux while using Windows)

Expected results:
The message "Not available for your platform" is displayed in add-on details page.

Actual results:
No message displayed.

Notes/Issues:
- add-on can be installed on Android, while on device. ( https://github.com/mozilla/addons-frontend/issues/2087 )

Verified on AMO-dev FF54(Win 7)
Screenshot for this issue:
![dict](https://user-images.githubusercontent.com/15685960/28816417-75e7749e-76ad-11e7-99ec-7a3f2193c5a2.png)

Maybe related to https://github.com/mozilla/addons-server/issues/5830 ?

**Comment by diox** [comment]
> Submit a dictionary which is not compatible with your operating system

This is the real bug: it should not be possible to do this, as it's pointless.

**Comment by muffinresearch** [comment]
Seems fine on the new frontend so I'm thinking that this is a won't fix for the legacy frontend.
