### ISSUE TITLE
Remove review renomination from devhub

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6081]
The review renomination link on the devhub causes some issues with nomination and review dates and in almost all cases developers use it to renominate their already rejected version which causes the version to go back into the queue.

It will become a real problem with post-review when nominated files will be auto-approved.

@jvillalobos agreed to remove it.

**Comment by eviljeff** [comment]
Note, this link is used to resume a submission that has been cancelled before full meta-data has been provided.  

We don't have an Incomplete file status, so files are created as Awaiting Review; we stop the confusion of exposing that status to the developer by locking them into the listed submission flow; to abort the submission (for example, to access their unlisted versions) we therefore have to set the file status to Disabled.

**Comment by wagnerand** [comment]
Afaik, that link is on a different page (`src/olympia/devhub/templates/devhub/addons/listing/item_actions.html`) and that one I don't touch.

**Comment by eviljeff** [comment]
It's linking to the same url/view, because its the same thing, just inside rather than outside the add-ons page on devhub.  I think the benefit of it being there outweighs occasional misguided developers; if it causes a problem with auto approval then fix auto-approval instead imo.

**Comment by wagnerand** [comment]
The current problem is that developers can re-nominate rejected versions, which causes
* extra effort for reviewers/admins
* broken metrics because suddenly the nomination timestamp is past the rejection timestamp.

The problem in post-review is that if a rejected version can be re-nominated, it will be auto-approved the next time the cronjob runs.

**Comment by jvillalobos** [comment]
Thanks for the reminder of why we have that link on the devhub. I totally forgot we introduced it when we did mixed listed/unlisted.

Given that, I think it's best to limit the impact of the change to where it really matters. So, I think we have two options:

1. Hide it when the version was rejected before.
2. Hide it when the version uses WebExtensions.

I suspect admin reviewers will prefer option 1.

**Comment by wagnerand** [comment]
That's the crux of the problem. We don't know why a version was disabled. Therefore we cannot check whether a version was rejected.

Can we hide it for all listed add-ons?

**Comment by jvillalobos** [comment]
>We don't know why a version was disabled. 

There's a review log that can be used to figure that out. 

> Can we hide it for all listed add-ons?

I suppose that hiding it for add-ons with `Approved` status would work. @eviljeff, does that make sense?

**Comment by wagnerand** [comment]
> There's a review log that can be used to figure that out.

I can see the reviewer of that patch crying already. :)

**Comment by eviljeff** [comment]
There are no listed add-ons 😄

**Comment by wagnerand** [comment]
Yes, **LISTED VERSIONS**...

Also, have we ever used the activity log other purpose than just logging stuff, e.g. make control flow decisions.

**Comment by diox** [comment]
Yeah, let's not use the activity log for anything else than, well, logging. I can see the myriad of edge cases and performance issues coming from a mile away.

**Comment by eviljeff** [comment]
Agreed, activity log is not to be relied upon really.  
We have `reviewed` dates that may be usable (on `Version` or `File`? I forget)

**Comment by wagnerand** [comment]
version.reviewed is only set for non-decisions (need-info for example).
file.reviewed is only set for decisions (approval, rejection).

**Comment by eviljeff** [comment]
> I suppose that hiding it for add-ons with Approved status would work. @eviljeff, does that make sense?

That would work.  Though would leave the case for new submissions being repeatedly renominated and/or being auto-approved.

**Comment by wagnerand** [comment]
So, all webextensions and all add-ons with status `APPROVED` then?

**Comment by jvillalobos** [comment]
> So, all webextensions and all add-ons with status APPROVED then?

Sounds okay to me.

**Comment by eviljeff** [comment]
So, the link was already excluding add-ons with status Approved.  The patch therefore is _only_ excluding webextensions.

**Comment by wagnerand** [comment]
> So, all webextensions and all add-ons with status APPROVED then?

Turns out, that's not going to work (https://github.com/mozilla/addons-server/pull/6087#discussion_r130683672). 

Let's step back and restate the goal (some might have forgotten 😉):
Developers should not be able to re-nominate a version that has been rejected.

Since we don't have a dedicated field for that, let's instead check when a version has been reviewed. We can check for that using `files.reviewed`. As stated in https://github.com/mozilla/addons-server/issues/6081#issuecomment-319430126), if that field is set, the version (and therefore its files) have either been rejected or approved.
* If they have been approved, the current behavior is to not show the *Request Review" link, for obvious reasons. This is achieved by https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/models.py#L1124
* Using the suggested `files.reviewed`, if they have been rejected, we won't show the link, since that file has that field set.

For resuming a pending listed submission, that field would not be set and should therefore still work as expected.

**Comment by wagnerand** [comment]
STR:

* A rejected version should not have the "Request Review" link the devhub. (Please test for both initial submissions and public add-ons with rejected versions)
* It should still be possible to "Cancel Review" and "Request Review" for pending versions.
* It should be possible to cancel and resume a submission (during the submission process).

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Postfix screenshots:
![auto-approved-no_rev_req](https://user-images.githubusercontent.com/15685960/28878721-c309f57a-77a8-11e7-8631-36a21b7213aa.png)
![cancel_rev_req](https://user-images.githubusercontent.com/15685960/28878727-c6f97f84-77a8-11e7-9afb-915becd504fa.png)
![incom-req_rev](https://user-images.githubusercontent.com/15685960/28878729-cdf49d64-77a8-11e7-8779-db7e77b6ce1e.png)
![rej](https://user-images.githubusercontent.com/15685960/28878732-d09c3068-77a8-11e7-819a-dae20d2e404f.png)

@eviljeff : Just one question: second version, that is awaiting review, shouldn't have a "Cancel review request" link? Thanks!
![second_vrs_-_no_cancel_review](https://user-images.githubusercontent.com/15685960/28878779-f825268a-77a8-11e7-98ba-6dc70b01d7d2.png)
