### ISSUE TITLE
Remove duplicate ESPaginator

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6083]
Both `amo/utils.py` and `api/paginator.py` contain a `ESPaginator` class. It's a custom `Paginator` that avoids doing an extra request to fetch the `count`, since ES provides that in the results already.

Unfortunately, the 2 classes are not exactly the same. One is compatible with our custom ES wrapper, one is compatible with elasticsearch-dsl. Fixing this could end up being a rabbit hole filled with yaks to shave.

If anyone wants to try it, I've got a branch that moves the files around https://github.com/diox/olympia/tree/eliminate-duplicate-espaginator but it's currently failing because of all the legacy search code not using elasticsearch-dsl.

Originally part of #6053 but I moved it because it was more complex than originally thought.

**Comment by EnTeQuAk** [comment]
We are seeing increasingly high numbers of errors because of https://github.com/mozilla/addons-server/issues/6053 so I'm trying to do this right now to mitigate our error rates.

**Comment by bqbn** [comment]
To add some info from #amo channel:

For the past  6 hours, there were about 115K errors like below on one ES node (there are 9 on -prod).

```
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Result window is too large, from + size must be less than or equal to: [25000] but was [388185]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.
```

The 500 errors increased a lot because of this.
