### ISSUE TITLE
Incompatibility message is not entirely RTL in listing pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6086]
Steps to reproduce:
1. Search for an incompatible add-on i.e. https://addons-dev.allizom.org/ar/firefox/search/?q=popup&appver=55.0&platform=windows while using a RTL lang
2. Hover over the incompat add-on i.e. "PopupMaster"

Expected results:
There are no display or layout issues.

Actual results:
The red mark is on the wrong side.

Notes/Issues:
- same in version history page
- we can also add a space between "View other versions" and the rest of the message. (for all locales)

Verified on AMO-dev FF54(Win 7).
Screenshot for this issue:
![rtl_sm](https://user-images.githubusercontent.com/15685960/28827008-dbe75e04-76d4-11e7-9fc9-096ca45f5c36.png)

#6028

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF55(Win 7).
Postfix screenshot:
![rtl-incompat](https://user-images.githubusercontent.com/15685960/29517634-acdcd364-867e-11e7-8f8b-c52ca577fe6b.png)

@tsl143 - should we align the text to the right, to remove the white space between the incompat sign and the text? Not sure how is correct. Thanks!

**Comment by tsl143** [comment]
Doing the text right align will give something as 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/5318732/29518146-dea723a6-8695-11e7-8f4e-ffd9646b6732.png">
is that fine?

**Comment by ValentinaPC** [comment]
@EnTeQuAk : opinion?

**Comment by EnTeQuAk** [comment]
thanks @tsl143 for the quick turnaround. Yeah, right aligning that text sounds like a great idea.
