### ISSUE TITLE
Rejecting an add-on version with Chinese characters shows an empty rejection.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#6088]
### Describe the problem and steps to reproduce it:
I tried to reject version 1.5.2 of https://addons.mozilla.org/en-US/editors/review/kobeengineerinput with the following text :
=-==-==-==-==-==-=
HrJasn,

由於以下問題，您的附加元件沒有通過同行評議：

1）根據您的附加元件的工作原理和描述方式，由於此附加元件是受限/非公眾受眾，此附加元件不適合列在“網上商店”上。 請將您的加載項提交為“不公開”。 有關更多信息，請參閱https://developer.mozilla.org/zh-CN/Add-ons/Distribution# 了解更多詳細信息。

=-==-==-==-==-==-=

### What happened?
While the version seems to be rejected, the rejection reason shows <empty>. I'm not sure if the text has been sent to the developer via email.

### What did you expect to happen?
The rejection text should show properly on the webpage.

### Anything else we should know?
For now I have created a "Reviewer reply" with the same text and it seems ok.

I tried to reproduce the issue on dev via https://addons-dev.allizom.org/en-US/editors/review/mymundus-web-history without success. Maybe there is no bug after all and I did something wrong on my side while submitting the rejection.

If possible, the email that was sent for this rejection must be checked to find out of the rejection reason was sent or not.

**Comment by eviljeff** [comment]
Looks like the add-on has been deleted (or slug changed) so it's going to be difficult to diagnose now.  Have you seen it before?  Just Chinese characters?

**Comment by spoji** [comment]
Never saw this issue before. At the end maybe it was a user error from my part. 

I guess you can close this issue and I'll reopen it if I can reproduce it in the future.

Thanks!

**Comment by eviljeff** [comment]
cool, closing.
