### ISSUE TITLE
Unexpected "Extensões" or "Extensions" in zh-CN rss

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#6093]
Check the https://addons.mozilla.org/zh-CN/firefox/extensions/format:rss?sort=created, the title is Extensões, it looks be "pt" locale, this is not Chinese.

In addition, check the https://addons.mozilla.org/zh-CN/firefox/extensions/tabs/format:rss?sort=updated, the title is "Extensions", that is English instead of Chinese.

**Comment by yfdyh000** [comment]
The titles seems to be randomly shown, both are "Bővítmények" & "扩展" (work fine) for now.

**Comment by diox** [comment]
Yeah, there are a couple calls to `ugettext` that should be lazy and are not, so the language used first in that thread persists:

* https://github.com/mozilla/addons-server/blob/5d456ba5e3d0494ce59d7b82f6a3fb663f60d801/src/olympia/browse/feeds.py#L92
* https://github.com/mozilla/addons-server/blob/5d456ba5e3d0494ce59d7b82f6a3fb663f60d801/src/olympia/browse/feeds.py#L107

**Comment by vcarciu** [comment]
Verified as fixed : 
![chn1](https://user-images.githubusercontent.com/1583842/28880392-94ba3540-77ad-11e7-80c3-b851b9430508.png)
![chn2](https://user-images.githubusercontent.com/1583842/28880396-984f3fe8-77ad-11e7-81f2-17a41cb9bbd6.png)

**Comment by yfdyh000** [comment]
Thanks. Verified as fixed.
