### ISSUE TITLE
With post-review, don't show waiting webextensions in the pre-review queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6103]
While a webextension submission waits for the auto-approval cronjob, it should not be shown in the pre-review queues in order to avoid a human reviewer picking it up.

It sounds like an edge-case, but due to reviewers' habits of picking reviews from the bottom of the queue, it's not as unlikely to happen as one might imagine.

**Comment by diox** [comment]
@wagnerand should they show up in search though? Currently the search functionality in editor tools is re-using the query used in the queues, so filtering out something from the queues hides it from search...

**Comment by wagnerand** [comment]
If that makes it easier for you, I am okay with them not showing up.

The search is of limited use anyway...

**Comment by diox** [comment]
It's *a lot* easier yeah. thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7)
Submitted webextension or update are not waiting in the pre-review queues.
Postfix screenshots:
![1](https://user-images.githubusercontent.com/15685960/30211326-351ced58-94a9-11e7-85a3-58af664841a2.png)
![not_in_queue](https://user-images.githubusercontent.com/15685960/30211329-388952e2-94a9-11e7-9389-04abf24cd3ab.png)
![vers](https://user-images.githubusercontent.com/15685960/30211376-7d18594e-94a9-11e7-8bde-046a3515d895.png)
![rt](https://user-images.githubusercontent.com/15685960/30211381-801ed366-94a9-11e7-8b6f-181f5cd6a090.png)
