### ISSUE TITLE
"Get data from the clipboard" & "Input data to the clipboard" is not localizable

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#6104]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
e.g. https://addons.mozilla.org/zh-CN/firefox/addon/new_tongwentang/ - Permissions
https://addons.mozilla.org/en-us/firefox/addon/new_tongwentang/

### What happened?
Keep in english. I can not find it in source code and Pontoon.

### What did you expect to happen?
Strings localizable.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Those strings are a bit special... To keep things in sync with Firefox, their translations are imported from mozilla central repos into our database. They are technically localizable, it's just that the translations need to be present in mozilla central repos instead. If you look at the french version for instance, it's there.

Now... https://hg.mozilla.org/l10n-central/zh-CN/file/tip/browser/chrome/browser/browser.properties does have a translation for `webextPerms.description.clipboardRead` and `description.clipboardWrite` so it's a little weird we don't have those...

**Comment by diox** [comment]
It looks like the script that updates the permissions (`manage.py update_permissions_from_mc`) isn't run in a cron or at startup, I thought we had done that. I've ran it on dev and stage and will ask ops to do it in prod in a moment.

**Comment by diox** [comment]
We ran the script everywhere, should be fixed now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF54(Win 7).
Postfix screenshots from some languages:
![fr](https://user-images.githubusercontent.com/15685960/29111524-473de94c-7cf3-11e7-9f04-cae3e6d85408.png)
![ka](https://user-images.githubusercontent.com/15685960/29111523-473dc17e-7cf3-11e7-915f-88a3e43890cd.png)
![zh-cn](https://user-images.githubusercontent.com/15685960/29111525-473ff8b8-7cf3-11e7-8245-dec85fba226e.png)
