### ISSUE TITLE
Contradiction between a webextension compatibility and “Compatible with Firefox 57+” label

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#6105]
**Steps to reproduce:**
1. Try to install the following webextension on Firefox 56 or Firefox 57: https://addons.mozilla.org/en-US/firefox/addon/xtense-we/?src=search

**Expected results:**
I’m not sure which should be the expected result here but I’m thinking about 2 options:
1. “Compatible with Firefox 57+” label is not displayed for webextensions with  strict_max_version < 57.0
2. Force all webextension to have at least strict_max_version = 57.0

**Actual results:**
The webextension is not installed because it is not compatible with Firefox 56 or Firefox 57 which contradicts “Compatible with Firefox 57+” label. This issue can be very confusing for the users.

**Additional notes:**
- This issue reproduces on AMO-production using Firefox 56.0a1 (2017-08-01) and Firefox 57.0a1 (2017-08-03) under Windows 10 64-bit.
- Please see the attached screenshot for this issue:
![2017-08-03_1816](https://user-images.githubusercontent.com/18114210/28929296-4f81ddfe-7878-11e7-8b17-c0bd9da8d147.png)

**Comment by wagnerand** [comment]
Nice edge case you found there.

It's a webextension but it has a `"strict_max_version": "54.0"`.

**Comment by jvillalobos** [comment]
`strict_max_version` usually doesn't make any sense for add-ons using WebExtensions. Most of the time, we should be telling the developer not to do that. In the rare cases where it makes sense, I think it's an edge case we can accept.
