### ISSUE TITLE
Catch zips using '\' in file-paths

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6111]
See https://github.com/mozilla/addons-linter/issues/1426 for much more details.

tldr; zip doesn't allow paths to contain backslashes but windows did that in the past and users do submit extensions like that. I don't know current behavior and couldn't find anything related to that in sentry so potentially we simply accept zips like that.

Should add at least a test though.

**Comment by muffinresearch** [comment]
>  I don't know current behavior and couldn't find anything related to that in sentry so potentially we simply accept zips like that.

We should *not* accept zips using backslashes in paths and should flag it to developers.

**Comment by EnTeQuAk** [comment]
> We should not accept zips using backslashes in paths and should flag it to developers.

I was just stating my guess of our current behavior, if we do that, we indeed should change it.

**Comment by muffinresearch** [comment]
> I was just stating my guess of our current behavior, if we do that, we indeed should change it. 

Aha ok - it makes more sense now - I was confused by "so potentially we simply accept zips like that" which sounded like a future direction which conflicted with the linter issue. 

Feel free to clarify the original description and delete my comments.

**Comment by yfdyh000** [comment]
Due to use of [`path`](https://nodejs.org/docs/latest/api/path.html). I tried to changes to `path.posix.` or [path-posix](https://www.npmjs.com/package/path-posix), but encountered a variety of errors for build or debugging, did not succeed.

**Comment by willdurand** [comment]
Let's reopen this issue because that could be useful to avoid bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1732997

**Comment by willdurand** [comment]
The idea would be to reject submissions with such invalid paths during (or before) the `repack` task so that we don't build completely different XPIs.

**Comment by diox** [comment]
The check should probably be added in https://github.com/mozilla/addons-server/blob/2f9f85d6b05256e145c765a4553605b64a4f9a39/src/olympia/files/utils.py#L515. Would need to double-check if somehow `\` isn't used as an escape character in some cases too (which could be valid)

**Comment by willdurand** [comment]
For an invalid zipfile (as per this bug), the backslash in a path looks escaped in the list of filenames:

```
>>> z.namelist()
['path\\to\\file.txt']
```

**Comment by AlexandraMoga** [comment]
@willdurand I've created a `.zip` file using the windows powershell [archive creation tool](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.1#example-4--compress-a-directory-that-excludes-the-root-directory). I've inspected the file paths with https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.allizom.org%2Fen-US%2Ffirefox%2Faddon%2Fno-name-in-file%2F to make sure the structure was using back slashes - `\`.  I've submitted the add-on on stage to see how the issue reproduces - https://addons.allizom.org/en-US/firefox/addon/no-name-in-file/

Afterwards, I've tried to submit the same add-on on -dev but I'm getting the 'Validation was unable to complete successfully due to an unexpected error.' message.

[PSzip.zip](https://github.com/mozilla/addons-server/files/7286226/PSzip.zip)

**Comment by willdurand** [comment]
> @willdurand I've created a `.zip` file using the windows powershell [archive creation tool](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.1#example-4--compress-a-directory-that-excludes-the-root-directory). I've inspected the file paths with [robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.allizom.org%2Fen-US%2Ffirefox%2Faddon%2Fno-name-in-file%2F](https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.allizom.org%2Fen-US%2Ffirefox%2Faddon%2Fno-name-in-file%2F) to make sure the structure was using back slashes - `\`. I've submitted the add-on on stage to see how the issue reproduces - [addons.allizom.org/en-US/firefox/addon/no-name-in-file](https://addons.allizom.org/en-US/firefox/addon/no-name-in-file/)

So far, so good.
 
> Afterwards, I've tried to submit the same add-on on -dev but I'm getting the 'Validation was unable to complete successfully due to an unexpected error.' message.

Ha. Let me see.

**Comment by willdurand** [comment]
Amazingly, this is the expected scenario. Our `@validation_task` decorator swallows most errors, including `ValidationError` for some reasons. This is probably something we want to change but it is a different issue.

**Comment by AlexandraMoga** [comment]
@willdurand I see. Will you file that new issue, because I don't fully understand what's the real problem there :)

**Comment by willdurand** [comment]
> Will you file that new issue, because I don't fully understand what's the real problem there :)

Yes, I will file an issue. The problem is that we have a more user-friendly and specific error message for this kind of issues but it isn't shown to end users.
