### ISSUE TITLE
Misleading link while trying to delete your account

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6112]
Steps to reproduce:
1. Submit an add-on using your newly created account
2. Try to delete your account
3. Click on the link available in the "Delete User Account" page

Expected results:
Should redirect to a page where user can see its submitted add-ons.

Actual results:
Link redirects to "My Profile" page, where there are no add-ons, if the author has unlisted or unreviewed add-ons.

Notes/Issues:
Verified on AMO-prod FF54(Win 7).
Video for this issue:
![no-add-on](https://user-images.githubusercontent.com/15685960/28960873-ed8a4154-7908-11e7-99d1-429e85213f4f.gif)

**Comment by EnTeQuAk** [comment]
User profile editing and deletion is now implemented in the new frontend. Closing.
