### ISSUE TITLE
Several add-ons are not displayed as suggestions in search list

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-server#6113]
**Steps to reproduce:**
Navigate to https://addons-dev.allizom.org/en-US/firefox/ and type the following add-ons names: 
- “navigation stats” for https://addons-dev.allizom.org/en-US/firefox/addon/navigation-stats/
- “context menu demo” for https://addons-dev.allizom.org/en-US/firefox/addon/context-menu-demo/

**Expected results:**
The add-on is successfully displayed in the search suggestion list.

**Actual results:**
The add-on misses from the search suggestion list while searching from its name.

**Additional notes:**
- This issue reproduces on AMO-dev and AMO-stage while using Firefox 57.0a1 (2017-08-03) under Windows 10 64-bit.
- This bug is reproducible on AMO-stage while searching for the following add-ons: https://addons.allizom.org/ro/firefox/addon/adblock-plus-test/ , https://addons.allizom.org/ro/firefox/addon/update-add-on-webext1/
- Please see the attached screenshot for this issue:
![2017-08-04_1243](https://user-images.githubusercontent.com/18114210/28963662-98f42e8e-7912-11e7-8537-d86b697977b0.png)

**Comment by EnTeQuAk** [comment]
I'll take a look at this, afair the autocomplete does search very differently than our actual search so I'm not sure what we can do about it. Potentially use our new API views and hook them into the views.

**Comment by EnTeQuAk** [comment]
This should be a bit better with https://github.com/mozilla/addons-server/pull/7303 now. It'll land on Thursday, I'm closing this issue for now but please feel free to re-file once new search-scenarios arise.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev and stage (new frontend) with the given examples and the add-ons were displayed as search suggestions. Based on this result, I'm marking this as verified fixed.
For more extensive observations regarding exact matching please see my comments from [#6837](https://github.com/mozilla/addons-server/issues/6837#event-1447867918)

![image](https://user-images.githubusercontent.com/31961530/35609611-a00f90c8-0666-11e8-8c42-8490959275f7.png)
