### ISSUE TITLE
Text can be moved up inside the search field

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6115]
Steps to reproduce:
1. Paste in the search field a text that uses only the upper side of the line i.e `జత చేయు`
2. Select the text and move the cursor down

Expected results:
Text is not moved.

Actual results:
Text is moved.

Notes/Issues:
- unselecting the text after step 2, and typing some normal text will cause some display issues inside the search field.

Verified on FF54(Win 7). Issue is reproducing on all servers.
Video for this issue:
![up-search](https://user-images.githubusercontent.com/15685960/28971378-671deb58-7934-11e7-8f4b-2bd9dfabbb89.gif)

**Comment by EnTeQuAk** [comment]
I'm closing this since it only affects the legacy frontend and should be less and less important over time once we move more missing functionality to the new frontend.
