### ISSUE TITLE
Search results have changed considerably

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-server#6116]
I have an add-on which was in a steady 4th position for this query since it was published:
https://addons.mozilla.org/en-US/firefox/search/?q=Search+By+Image
https://addons.mozilla.org/en-US/firefox/addon/search_by_image/

About 3 days ago statistics have stopped updating on evenings, and when the stats finally appeared yesterday, I've seen that downloads have dropped to nothing, and that the add-on was nowhere to be found on the search results page.

Currently it alternates between appearing at the bottom of the first page for the above query, and the third page. Some of the listings which rank above it do not seem to be relevant for the query.

I have checked the results for some other queries, like 'google docs' and others, and the results look different than a week ago.

Have others noticed recent changes in the rankings of their add-ons?

**Comment by EnTeQuAk** [comment]
We found potential problems that caused this. We're working on this so stay tuned. I can't promise this will be fixed in this weeks deployment but I'm sure we will get something up and running next week at the latest.

**Comment by dessant** [comment]
I forgot to mention that for this query the extension was at the 5th position from the bottom:
https://addons.mozilla.org/en-US/firefox/search/?q=reverse+image+search

@EnTeQuAk, do you have some updates regarding this issue?

**Comment by EnTeQuAk** [comment]
No, we pushed a few fixes out that fixed quite a few of these issues but there's still quite a bit that's still WIP. I'll update this issue as soon as there's anything to share.

**Comment by dessant** [comment]
The shared example is not relevant anymore, most variables have changed, including the description, and also rank positions. #2661 is a better place to track this issue.
