### ISSUE TITLE
Permissions are duplicated for each platform in Reviewer Tools

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6118]
Steps to reproduce:
1. Submit a webextension with permissions and multiple files  i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-auto-approval/
2. Go to Editor Tools and observe in webextension review page the files/permissions section
3. Approve the webextension
4. Repeat step 2.

Expected results:
Permissions are written once, together with platform files availability, as before step 3.

Actual results:
Same permissions are written for each file.

Notes/Issues:
Verified on AMO-dev FF54(Win 7). Issue is reproducing on dev and stage.
Screenshots for this issue:
![perm-revtools](https://user-images.githubusercontent.com/15685960/29017651-6ef01d14-7b60-11e7-83ab-1c0b0322fb49.png)

**Comment by jvillalobos** [comment]
While still valid, we dropped multi-file versions for new versions, so this shouldn't a common problem anymore.
