### ISSUE TITLE
Hide the install button for incompatible add-ons entirely in search/browse

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6119]
From https://github.com/mozilla/addons-server/issues/5277#issuecomment-318074010

Hide the install button for incompatible add-ons entirely in search/browse/homepage and instead, show an expanded compatibility explanation and a link to the All Versions page.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix video:
![incompat](https://user-images.githubusercontent.com/15685960/29526760-5a7ebf4e-869f-11e7-98f3-836f1fd1e79b.gif)
