### ISSUE TITLE
"Manage My Submissions" links to the "Next Listed Version," but that link fails

### ISSUE THREAD

**Issue by peter-kehl** [mozilla/addons-server#6123]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Visiting https://addons.mozilla.org/en-US/developers/addons?page=2 logged in as myself

### What happened?
I've submitted a new version of add-on SeLite Selblocks Global. The above page says:
Listed Version: 2.70
Next Listed Version: 2.71
"2.71" links to https://addons.mozilla.org/en-US/firefox/addon/selite-selblocks-global/versions/2.71 but that page fails (probably since not approved yet)

### What did you expect to happen?
Make the link work, or don't show it.

### Anything else we should know?

Related to this, https://addons.mozilla.org/en-US/firefox/addon/selite-selblocks-global/versions/ doesn't show my pending 2.71.

**Comment by diox** [comment]
> Related to this, https://addons.mozilla.org/en-US/firefox/addon/selite-selblocks-global/versions/ doesn't show my pending 2.71.

That's on purpose. We no longer show pending versions in there, because they are not signed and therefore not installable.

**Comment by peter-kehl** [comment]
Then don't show links to the pending versions either.

**Comment by diox** [comment]
I don't dispute the issue, merely gave an explanation as to why it's not shown on the public versions listing page :)

I agree we should not link to the listing page if the version is not public. Unsure if the best solution is to avoid linking in that case or always linking to the developer version edit page instead.

**Comment by diox** [comment]
It turns out this issue has already been reported as #5533
