### ISSUE TITLE
Different results at submission vs. update for a multiple-apps compatible legacy add-on if maxversion over 56.*

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6126]
Steps to reproduce:
1. Submit an add-on compatible with Firefox, Thunderbird and SeaMonkey while having `maxversion` for Firefox : `57.0` i.e. https://addons-dev.allizom.org/en-US/developers/addon/new-mixed-legacy-add-on/edit
2. Add a new version for this add-on, maintaining the `maxversion` value

Expected results:
Both steps have the same result.

Actual results:
New submission can be done without any problems, while updates are blocked.

Notes/Issues:
Verified on AMO-dev FF54(Win 7). Issue is only reproducing on dev.

May be related with #5277

**Comment by diox** [comment]
I disagree with the expected results. Change the `maxVersion`, it should not be possible for legacy add-ons to be marked as compatible with Firefox 57, that was precisely one of the goals of #5277.

**Comment by wagnerand** [comment]
@ValentinaPC has a point though. I doesn't seem logical that we allow an initial legacy submission but not any updates...

**Comment by ValentinaPC** [comment]
My supposition was based on the fact that **new legacy add-on submission can be done, if add-on is compatible with multiple apps** (beside FF, like Thunderbird or SeaMonkey), but u`pdates no.`
If you think this is expected, I can adjust my opinion, but if you ask me, is not ok.

**Comment by diox** [comment]
Fair enough. I can apply that restriction to both new submissions and updates.

**Comment by ValentinaPC** [comment]
@diox : now is a little contradiction between the new message you've added in this issue and the banner from my submission page. Maybe you can add the same message that is displayed while new submissions in case of single app legacy add-on - "Starting with Firefox 53, new extensions on this site can only be WebExtensions." ?

As far as restriction for new submission : multiple app legacy add-on fail to be submitted, as expected.

**Comment by diox** [comment]
It's not a contradiction if you consider "until" in the top message excludes 57 itself :)

**Comment by ValentinaPC** [comment]
So we are ok with leaving this as it is now?

**Comment by diox** [comment]
I think so yes. Note that the message at the top can be edited by admins at any time, so we may change it as we get closer to 57 stable.

**Comment by ValentinaPC** [comment]
Marking this verified, considering above comments.
