### ISSUE TITLE
Remove legacy add-on bulk validation

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6131]
So apparently the last bulk validation we will ever run was with Firefox 56 which means, if we're not going to do that anymore we can as well delete all code related to it.

Do we need to wait for ESR to loose support for legacy add-ons as well?

I'm not sure we want to delete the data associated to it too, at least not too fast but I honestly can't think of a scenario where we might need to use it again?

cc @wagnerand @jvillalobos

**Comment by jvillalobos** [comment]
I have no objections to dropping the bulk validator now. The [compatibility checker](https://addons.mozilla.org/developers/addon/check-compatibility) and the compatibility tests in the validator should stay at least until we launch 57 on release (Nov 14th).

**Comment by EnTeQuAk** [comment]
> I have no objections to dropping the bulk validator now. The compatibility checker and the compatibility tests in the validator should stay at least until we launch 57 on release (Nov 14th).

Cool, yeah I'm mostly talking about the stuff in zadmin.

**Comment by diox** [comment]
Do we have anything in place to do compatibility bumps on language packs ? Should we ? How do they get their compatibility info updated these days ?

**Comment by wagnerand** [comment]
Language packs never get their compatibility bumped (and they shouldn't). Shortly after every new Firefox release, we manually pull the latest langpacks from ftp and sign them (using `/admin/langpacks`).

**Comment by diox** [comment]
Ok perfect, I wasn't sure if it was done through the compat tool or not, ignore my comment then :)
