### ISSUE TITLE
"+Add to Firefox" for experimental legacy add-ons triggers an installation popup

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6134]
Steps to reproduce:
1. Click on "+Add to Firefox" for an **experimental** legacy add-on i.e. https://addons.allizom.org/en-US/firefox/addon/adblock-plus/

Expected results:
The button does not trigger any popup.

Actual results:
The button triggers a popup.

Notes/Issues:
- reproducing only for experimental add-ons
- was not reproducing while verifying #6028 on -dev
Verified on FF54(Win 7). Issue is reproducing on stage and dev.
Video for this issue:
![experimental](https://user-images.githubusercontent.com/15685960/29120909-0ef7eb38-7d15-11e7-9eb2-669f75c9069c.gif)

**Comment by diox** [comment]
Weird. I'm not able to reproduce... I know our button css/js code is finicky, but still...

**Comment by diox** [comment]
Ah, nevermind, it looks like the add-on I was testing with is no longer experimental. I can reproduce with a legacy experimental add-on as noted in the description of the issue.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix video:
![exp](https://user-images.githubusercontent.com/15685960/29213396-cd7354f2-7eab-11e7-8a97-7ea51a006a17.gif)
