### ISSUE TITLE
Incompatible add-ons inside of a collection trigger installation popups

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6135]
Steps to reproduce:
1. Add an incompatible add-on to a collection i.e. https://addons.allizom.org/en-US/firefox/collections/Vivre/e-coll/ (i.e Gmail Notifier (restartless))
2. Go to collection details page and click on "+Add to Firefox" button for the incompatible add-on

Expected results:
The button does not trigger any popup.

Actual results:
The button triggers a popup.

Notes/Issues:
- after clicking on the "+Add to Firefox" button for the incompat add-on the button color changes to white.
Verified on FF54(Win 7). Issue is reproducing on dev and stage.
Video for this issue:
![coll-popup](https://user-images.githubusercontent.com/15685960/29121892-168f2fa6-7d19-11e7-9d83-aecd71718c2c.gif)

#6028

**Comment by ValentinaPC** [comment]
@diox : do you think is worth fixing the button color or better leave it like this? I mean experimental incompatible add-ons inside a collection have inactive yellow button.
Screenshot:
![2017-08-11_1548](https://user-images.githubusercontent.com/15685960/29213594-8c91c8fa-7eac-11e7-9d1f-3346fab12cbf.png)

**Comment by diox** [comment]
I did the best I could but collection list pages are weird... this will have to do until someone complains :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix video:
![coll](https://user-images.githubusercontent.com/15685960/29214669-e92943be-7eb0-11e7-92e2-77aef8f6dcdb.gif)
