### ISSUE TITLE
"Changes Saved" message with invalid data

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#6136]
Steps to reproduce:
1. Login with any user that has 1+ extensions submitted.
2. Navigate to: Manage My Submissions>Edit Information.
3. Click on "Edit" from the "Basic Information" section.
4. Unselected all options from the "Categories" section.
5. Click on the "Save Changes".

Expected results:
The changes are not saved.

Actual results:
The "Changes Saved" message is displayed.

Notes/Issue:
Verified on FF54(Win 10). Issue is reproducing all around AMO-servers.
Video for this issue:
![changes saved](https://user-images.githubusercontent.com/28138132/29130880-c5b199fa-7d33-11e7-94e8-da0caaf27533.gif)

**Comment by eviljeff** [comment]
duping this to #3098
