### ISSUE TITLE
Lang Pack with maxversion 57.0 can be submitted but cannot be installed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6141]
Steps to reproduce:
1. Submit a language pack with `maxversion 57.0a1` i.e. https://addons.allizom.org/en-US/firefox/addon/acholi-ug-lp-57/

Expected results:
Language Pack cannot be submitted.

Actual results:
Language Pack is successfully submitted.

Notes/Issues:
- `maxversion` in public pages is displayed as "`57.0a1`"
- `maxversion` in Dev Hub is "`------`" with the possibility to set it to 56.*
- maxversion in Editor Tools is "57.0a1"
- lang pack cannot be installed in FF57.0a1
Screenshots for this issue:
![langpack](https://user-images.githubusercontent.com/15685960/29162017-ddd65ab0-7dc0-11e7-859b-ab309d14da5b.png)
![dev_hub](https://user-images.githubusercontent.com/15685960/29162027-e3b82634-7dc0-11e7-88a1-d75928f49374.png)
![lp -revtool](https://user-images.githubusercontent.com/15685960/29162033-e910fc00-7dc0-11e7-8564-9cc450bd2b62.png)
![vrs](https://user-images.githubusercontent.com/15685960/29162040-ed0e96b4-7dc0-11e7-8547-82998f8cba3f.png)
![ff57](https://user-images.githubusercontent.com/15685960/29162158-3e0398d0-7dc1-11e7-80bd-6bdd0817add5.png)
Verified on FF54(Win 7). Issue is reproducing on both stage and dev.
#5277

**Comment by diox** [comment]
@jvillalobos how should we treat language packs exactly?

**Comment by krupa** [comment]
Lang packs should be supported post-57. They remain unaffected by the cutover.

**Comment by wagnerand** [comment]
This is a valid bug. A developer should be able to set 57 as a version for langpacks.

**Comment by jvillalobos** [comment]
To clarify, the issue as originally file is _not_ an issue because we want language packs to support 57. The fact that 57 doesn't appear in the version selection dropdown _is_ an issue that should be corrected.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Submission and new version uploads work as expected for Lang Packs. Compatibility options are available in Dev hub, until `57.0` and `*`

The only thing I wanna ask you, @diox, is that: we are ok with setting `maxversion` automatically to `56.*` if is set to "`*`" in install.rdf? More precisely #5277 applies to Lang Packs as well?

**Comment by diox** [comment]
Lang packs should not be submitted with `*` anyway, so yes, that should be fine.

**Comment by ValentinaPC** [comment]
Marking as verified-fixed.
