### ISSUE TITLE
Themes sorting criteria does not display results as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6142]
Steps to reproduce:
1. Load Themes homepage https://addons.allizom.org/en-US/firefox/themes/
2. Click on any sort option from the left i.e "Top rated"

Expected results:
Ratings stars are displayed for each theme and ordered as expected.

Actual results:
Daily users are listed for each theme.

Notes/Issues:
- same for each sorting criteria
- **apparently reproducing on new desktop pages for extensions and themes - same details are displayed no matter or what sorting criteria is selected doing things difficult for users;**
Verified on FF54(Win 7). Issue is reproducing on all servers.
Screenshots for this issue:
![1](https://user-images.githubusercontent.com/15685960/29164226-7049096e-7dc7-11e7-9eb9-9a4c57b7f30d.png)
![2](https://user-images.githubusercontent.com/15685960/29164227-7079d094-7dc7-11e7-89c8-49146a221754.png)
![3](https://user-images.githubusercontent.com/15685960/29164229-7080348e-7dc7-11e7-8866-7d44331cec60.png)
![4](https://user-images.githubusercontent.com/15685960/29164228-707b883a-7dc7-11e7-8726-abe9061aab77.png)

**Comment by muffinresearch** [comment]
Closing this since the new frontend launched.
