### ISSUE TITLE
Sorting by Popularity is not working inside of a collection

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6144]
Steps to reproduce:
1. Load details page for a collection i.e. https://addons.allizom.org/en-US/firefox/collections/mozilla/webdev-toolbox-ivan-krsti%C4%87/
2. Sort the add-ons inside by popularity

Expected results:
Add-ons inside the collection are sorted by number of users.

Actual results:
Add-ons inside the collection are not sorted.

Notes/Issues:
Verified on FF54(Win 7). Reproducing on stage and dev.
Screenshot for this issue:
![popularity](https://user-images.githubusercontent.com/15685960/29168923-ead736bc-7dd9-11e7-8231-cd5597755bb3.png)

**Comment by eviljeff** [comment]
This page/feature has been rewritten in our new front-end and the problem reported in this issue is fixed there, or is no longer applicable.  In a way: new frontend doesn't support sorting the add-ons in a collection.
