### ISSUE TITLE
Don't hide the install button for compatible add-ons while displaying disabled buttons 

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#6150]
### Describe the problem and steps to reproduce it:
1. Load https://addons.mozilla.org/en-US/firefox/extensions/?sort=featured
2. Notice the install buttons for listed add-ons

### What happened?
For compatible add-ons, the install button is only visible on mouse-over whereas the disabled buttons are grayed out and are always shown.

### What did you expect to happen?
- Call-to-Action buttons for compatible add-ons are clearly visible
- When install buttons are missing, it may confuse the user into thinking that the add-on is incompatible

### Anything else we should know?
<img width="868" alt="screenshot 2017-08-10 13 57 59" src="https://user-images.githubusercontent.com/301317/29191862-fa5b9e62-7dd3-11e7-8590-53e87d83762c.png">

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
Compatible add-ons display the installation button only at hover, as before. 
Please see the screenshot:
![incomapt-_vs _compat](https://user-images.githubusercontent.com/15685960/29526971-076b9d30-86a0-11e7-8273-06675842c78b.png)

**Comment by diox** [comment]
@jvillalobos should we always display the green install button in search or only at hover? I didn't want to change this behavior so I only hid the incompatible buttons, but if it makes more sense to always chose the green buttons it's easy to do.

**Comment by jvillalobos** [comment]
I would prefer that we always show the buttons, if that isn't hard to do. The hover behavior is a bit strange and has confused others.

**Comment by diox** [comment]
Ok, I'll do it for next week's push

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix screenshot:
![compat-incompat](https://user-images.githubusercontent.com/15685960/29712719-e59938d2-89a3-11e7-8f7b-d3754975f407.png)
