### ISSUE TITLE
Make lang=lang in our db queries safer

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6153]
In order to cache make all our database queries dependent on the current language we do 
`qs = qs.extra(where=['"%s"="%s"' % (lang, lang)])` in `amo/models.py`. It's ugly, and I'm not totally sure it's still useful because cache-machine does make the cache keys depend on the current locale, but I don't really want to find out if we can remove that.

What we could do however is make it safer. `lang` should have been validated, but just in case, we should use `params=` to pass the lang, which escapes things for free.

**Comment by diox** [comment]
Gave it a try but I'm seeing some test failures that don't look good... https://travis-ci.org/diox/olympia/builds/263432269

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
