### ISSUE TITLE
Extensions missing when searching with non-'en-US' locale

### ISSUE THREAD

**Issue by nkestrel** [mozilla/addons-server#6156]
The `en-GB` locale (and other non-`en-US` locales) cannot find the Cookie AutoDelete extension.

https://addons.mozilla.org/en-GB/firefox/search/?q=cookie+autodelete&appver=57.0&platform=windows
![](https://i.imgur.com/GpDwi5y.png)

https://addons.mozilla.org/en-US/firefox/search/?q=cookie+autodelete&appver=57.0&platform=windows

![](https://i.imgur.com/1pk4Ccj.png)

**Comment by diox** [comment]
@EnTeQuAk *maybe* it's not related to the elasticsearch upgrade, but this the timing is suspicious. In any case, it's bad, we should look into it. Maybe an issue with translations somehow.

**Comment by EnTeQuAk** [comment]
I'm pretty sure it's the regression we found that's related to the upgrade and our scoring / matching. For example, the add-on is perfectly reachable via https://addons.mozilla.org/en-GB/firefox/search/?q=autodelete&appver=57.0&platform=windows so it doesn't seem locale related.

I'm assigning this to me in any case

**Comment by EnTeQuAk** [comment]
actually… I tested this again and it seems unrelated to my recent changes so there's another bug lurking somewhere. I'll look into it.

**Comment by EnTeQuAk** [comment]
Alrighty, I finally got this reproduced locally with properly synced public prod data. This is indeed valid, once an add-on only has en-GB (or pt-BR or anything that's not en-US) it's not listed anymore. I'll dig deeper.

**Comment by madalincm** [comment]
Verified as fixed in addons.mozilla.org in FF55(Win7)
The extension is correctly returned when performing a search:  https://addons.mozilla.org/en-GB/firefox/search/?q=cookie+autodelete&appver=57.0&platform=windows
Postfix screencast: 
![engb](https://user-images.githubusercontent.com/15685441/29713307-a4a48afe-89a6-11e7-8961-68b02886d210.png)
