### ISSUE TITLE
 Admin ACR Reports dashboard is down again

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6161]
Same issue as #6043. /cc @jasonthomas

**Comment by jasonthomas** [comment]
cc @bqbn

**Comment by bqbn** [comment]
The issue may have to do with this error log:

```
2017/08/11 20:24:09 [error] 4459#0: *7862 connect() to [::1]:10015 failed (113: No route to host) while connecting to upstream, client: 63.245.214.169, server: addons-internal.prod.mozaws.net, request: "GET /en-US/admin/compat HTTP/1.1", upstream: "uwsgi://[::1]:10015", host: "addons-internal.prod.mozaws.net"
```

Nginx somehow resolved the upstream (in this case, localhost) to "[::1]", which doesn't exist. I've set the upstream to "127.0.0.1" on the instance for now.

@jvillalobos please check again.

**Comment by bqbn** [comment]
It looks like the IP resolution is part of the issue. In #6043, towards the end, it's also mentioned that the issue may be "we are missing data in elasticsearch"? How was that solved?

**Comment by bqbn** [comment]
Elasticsearch returned 400 bad request. See below,

```
GET /addons_prod/compat/_search HTTP/1.1
Host: ***
Accept-Encoding: identity
Content-Length: 587
connection: keep-alive
content-type: application/json

{"sort": [{"works.55000000200100.failure_ratio": "desc"}, {"works.55000000200100.total": "desc"}], "query": {"bool": {"filter": {"bool": {"must": [{"range": {"works.55000000200100.failure_ratio": {"gt": 0.8}}}, {"range": {"works.55000000200100.failure": {"gt": 10}}}, {"range": {"support.max": {"gte": 0}}}]}}, "must": {"function_score": {"query": {"match_all": {}}, "functions": [{"field_value_factor": {"field": "boost", "missing": 1.0}}]}}}}, "_source": ["id", "guid", "slug", "name", "current_version", "max_version", "works", "usage", "has_override", "overrides", "id"], "size": 20}
```

```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
Content-Length: 643
Connection: keep-alive

{"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [works.55000000200100.failure_ratio] in order to sort on","index_uuid":"MKaq8lV8SQCa49r6SDXG0A","index":"addons_prod-20170803170032"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"addons_prod-20170803170032","node":"694wHD7cQ1GsMYwFAfbxHg","reason":{"type":"query_shard_exception","reason":"No mapping found for [works.55000000200100.failure_ratio] in order to sort on","index_uuid":"MKaq8lV8SQCa49r6SDXG0A","index":"addons_prod-20170803170032"}}]},"status":400}
```

**Comment by jvillalobos** [comment]
> @jvillalobos please check again

Still not working.

**Comment by bqbn** [comment]
> Still not working.

Yeah, I'm able to reproduce it. And it's due to the 400 error I posted above. We need some help to check why the application is sending a request that the ES doesn't recognize.

**Comment by diox** [comment]
The tool relies on a specific index, which itself uses dynamic mapping. That index is filled with add-on compatibility data by `compatibility_report` cron. Crucially, the tool needs at least one document with data for the latest released version of Firefox to work, because it's using it as a sort field. (That's because it's using dynamic mapping: the field would not exist otherwise).

Unfortunately it looks like the [cron is currently failing to execute properly](https://sentry.prod.mozaws.net/operations/olympia-prod/issues/630340/), and I guess it's been failing for a couple weeks, so there is no data (I suppose because of the ES5 switch) and the tool fails. Fixing the cron (which I think should just be a matter of ignoring add-ons with no compatibility data) should fix the tool.

**Comment by ValentinaPC** [comment]
Verified this in **stage** and ACR is working.
- dev is down, but based on early discussions is ok.
- prod - I have no rights, maybe someone can take a look there.

Screenshot from stage using FF55(Win 7):
![stage-acr](https://user-images.githubusercontent.com/15685960/29406879-21c04b70-834b-11e7-807e-dbefbcf28bb0.png)

**Comment by diox** [comment]
The fact that stage works is accidental :) It won't be fixed in prod today, will be next week.

**Comment by diox** [comment]
nvm: I just cherry-picked it, it *will* land on stage later today and go out in prod. I figured since the cron was broken anyway there was no possibility of further regression so we might as well try to get it fixed sooner than later since there were no conflicts when cherry-picking it.
