### ISSUE TITLE
 "Find a Replacement" button for Legacy Extensions links to a list of incompatible extensions

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#6162]
Steps to reproduce:
* Click about:addons / Legacy Extensions / Find a Replacement.

Actual result:
* The page displayed starts with two add-ons which aren't compatible with Firefox 57.

Expected result:
* The button should link to a list of add-ons which are only compatible with Firefox 57.

**Comment by jvillalobos** [comment]
That's because we haven't removed all legacy add-ons from the Featured Add-ons collection. This is scheduled to happen on September 1st. /cc @devaneymoz in case there has been any change of plans.

**Comment by devaneymoz** [comment]
Yes - legacy content will be removed from the Featured Extensions collection on 1 September.
