### ISSUE TITLE
After the last update, some legacy add-ons‘s install button were grayed out or complete disabled

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#6164]
### Describe the problem and steps to reproduce it:
After the AMO site last update, some add-ons (compatibility not specified to latest)'s install button were grayed out or complete disabled for original Firefox.

For example:
1. https://addons.mozilla.org/firefox/addon/autoproxy-ng/
2. https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/

### What happened?
1. The install button were complete disabled, click is invalid. `Works with Firefox 3.0.9 - 26.0a1, ...`
2. The install button were grayed out, click to install is still working. `Works with Firefox 17.0 - 39.*`
### What did you expect to happen?
1. Allows users to install legacy add-ons when using Firefox 56 and earlier, keep the old strategy, i.e. compatibility to min “and later” instead of specified max. Older Firefox users should have the same experience as before, no obstacles.
2. No different click hijacking strategy. Allow right click to opening the context menu for the install button (link) to download the version (xpi).

**Comment by diox** [comment]
1. The developers of those add-ons have marked it compatible with Firefox 3.0.9 - 26.0a1 and Firefox 17.0 - 39.* respectively. Legacy add-ons compatibility is now strict to prepare for the switch to 57 and that's why the install button is now greyed out.
2. This was unintentional, because of other fixes to the button disabling code, I'll see what I can do about it.

**Comment by yfdyh000** [comment]
> The developers of those add-ons have marked it compatible with Firefox 3.0.9 - 26.0a1 and Firefox 17.0 - 39.* respectively. Legacy add-ons compatibility is now strict to prepare for the switch to 57 and that's why the install button is now greyed out.

I think they should be max=56.0, unless the add-on developer set the strict compatibility. This is the previous act.

**Comment by diox** [comment]
> I think they should be max=56.0, unless the add-on developer set the strict compatibility. This is the previous act.

For each Firefox release, we bump the compatibility of *most* legacy add-ons on AMO to the next version. Emphasis on *most*. I'm not sure why those have not been bumped in a while, maybe @wagnerand knows.

**Comment by wagnerand** [comment]
Looking at the compatibility settings, it seems both failed compatibility bumping at some point.

**Comment by pamadini** [comment]
I've noticed the same issue when using the website in Firefox 55, and as a workaround I've manually updated the compatibility metadata for the latest version of the add-on I'm maintaining.

However, this is still a bug in the compatibility checking. Many legacy add-ons have been uploaded with the default setting of strict compatibility disabled, in which case the maximum version is usually set to the host application version at the time the add-on was released, or set to be equal to the minimum version (for example, 52.0 - 52.*).

At the moment, such add-ons can be installed in any newer version of the host applications and are considered compatible. The same logic is also used by ESR versions of the browser. Only when using Firefox 57, such legacy add-ons can be considered incompatible.

Adjusting compatibility information manually is just a workaround, as this bug affects archived old versions of such add-ons, as well as currently published add-ons whose authors haven't realized the issue yet.

**Comment by diox** [comment]
> No different click hijacking strategy. Allow right click to opening the context menu for the install button (link) to download the version (xpi).

I recently made the download anyway link appear for incompatible add-ons on the detail page to work around this problem (most notably in c75b7dc1a64d17972ed7392f6693bb6fd0bea221, but also another commit before that I can't find right now) 

Regarding old add-ons with wrong compatibility information, it should be limited to a small number of add-ons that failed the compatibility bump sometime in the past. When that happened authors should have been notified, it's up to them to fix it.
