### ISSUE TITLE
Add new footer links

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6167]
See: https://github.com/mozilla/addons/issues/471

**Comment by eviljeff** [comment]
There wasn't any UX so I just tried to make it look like it was supposed to be there...ish.  Or was it supposed to look like mozilla.org's list of links?  Hmm.  Anyway, what do you think?
![firefox footer](https://user-images.githubusercontent.com/768592/29663418-9af0cb48-88fd-11e7-8289-bec3d5d93d69.png)

**Comment by eviljeff** [comment]
@pwalm what do you think ^ ?  It's shown on the user facing pages (until addons-frontend takes over) and devhub detail pages (but not developer landing)

**Comment by designakt** [comment]
@eviljeff please make the font smaller, add some space above it, to have roughly the same height of white above and below, and maybe stretch to the full with of the footer.
Those things will hopefully reinforce that this is not related to "get to know Add-ons", and will give the individual items more space - probably important for other languages, as in English, the space between the words "Browser" is quite narrow.

**Comment by eviljeff** [comment]
![untitled](https://user-images.githubusercontent.com/768592/30062382-88a76cec-927d-11e7-8e3e-7b24d289ec64.png)

**Comment by pwalm** [comment]
Looks good for now, but we're gonna have to switch to the new global footer at some point pretty quick: [As seen here](https://www.mozilla.org/en-US/).

**Comment by eviljeff** [comment]
is there an issue (or two) about implementing this "new global footer"?

**Comment by pwalm** [comment]
There will be once I find it! It's the current footer on Mozilla.org. We'll be implementing a version with AMO links.

**Comment by eviljeff** [comment]
cool.  addons-frontend will need an issue for implementing there, and depending on how "quick" is "pretty quick" addons-server too (i.e. if we need to switch to it on the legacy frontend before the new frontend takes over in Q4).

**Comment by ValentinaPC** [comment]
So, this is not implemented yet? When it will be? Thanks!

**Comment by eviljeff** [comment]
The deployment had some problems.  Ops will fix it (if it doesn't fix itself)

**Comment by ValentinaPC** [comment]
Links are arranged as expected and load corresponding pages.
Postfix screenshot from AMO-dev FF55(Win 7):
![footer](https://user-images.githubusercontent.com/15685960/30368979-959fbcc0-987b-11e7-9417-0cbffef336dd.png)
