### ISSUE TITLE
Create a script that copies our public AMO add-ons for local development

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6174]
This is already WIP but I'm opening this issue to track it's progress.

The script should scrape our API and website to download all public add-on data that we have to simplify local development, e.g to test our search results and result scoring better.

**Comment by wagnerand** [comment]
Maybe one of the following does already what you need:

https://github.com/andymckay/addons-server-mirror
https://github.com/cr/webextaware

**Comment by EnTeQuAk** [comment]
Done, closed since we decided not to publish that script in our repository. If someone needs it, feel free to ping me.
