### ISSUE TITLE
Quick Locale Switcher 2 doesn't appear in search results

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6176]
[This add-on](https://addons.mozilla.org/addon/quick-locale-switcher-2/) doesn't appear on search results for "Quick Locale Switcher", while the original Quick Locale Switcher does appear. See [this query](https://addons.mozilla.org/en-US/firefox/search/?q=quick+locale+sqitcher&appver=any&platform=all) for example.

One unusual thing I noticed about Quick Locale Switcher 2 is that its metadata is only in the `en-GB` locale, but I don't know if that's related.

**Comment by diox** [comment]
A variation of #6156 maybe ? /cc @EnTeQuAk

**Comment by EnTeQuAk** [comment]
yeah, maybe. I'll look into it together with the other search related issues.

**Comment by EnTeQuAk** [comment]
Given #6156 is actually valid and not fixed by my recent changes I'll close this as a duplicate.
