### ISSUE TITLE
"Get Firefox Now" button on AMO in Chrome not working

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#6177]
When you visit AMO from Chrome, and go to an extension listing or detail page, there is a green "Get Firefox Now" button that should take you to the Firefox download page. This button is currently not clickable. 

Unsure how long it's been broken, but this impacts Firefox acquisition efforts.

Screenshot: https://www.dropbox.com/s/riwdztookcy1qj7/Screenshot%202017-08-16%2011.07.44.png?dl=0

**Comment by diox** [comment]
Dammit. It's a regression from last week changes to the button styles. Fortunately the fix should be easy, so I'll cherry-pick it into this week's tag.

**Comment by atsay** [comment]
Oh thank goodness it's recent! Thanks for fixing!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Chrome Version 60.0.3112.90 (Win 7).
Postfix video:
![getff](https://user-images.githubusercontent.com/15685960/29407248-76786bce-834c-11e7-80e5-1980aa920fbf.gif)
