### ISSUE TITLE
Add "Get Firefox Now" button to AMO Theme pages in Chrome

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#6180]
We currently only show these buttons for extension listing and detail pages but not themes. This impacts our ability to do Firefox acquisition campaigns around themes.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev Chrome Version 60.0.3112.101 (Win 7).
The "Get Firefox now" button was added to personas as well, in details page and work as expected.
Postfix screenshot:
![personas](https://user-images.githubusercontent.com/15685960/29450865-2568fdd0-8409-11e7-9a18-1d996c474855.png)

In themes homepage pr listing pages the "+Add" button is still displayed, and inactive - @diox - do we wanna leave it like that?
Please see screenshot:
![add](https://user-images.githubusercontent.com/15685960/29450859-1a655e10-8409-11e7-9046-55c8f516c525.png)

**Comment by diox** [comment]
Sigh, it's a completely different button code, because of course it is. I'll look into it.

**Comment by diox** [comment]
I tried to do this, but it would require significant tweaks to the style, because the "Get Firefox Now!" button is much larger and it breaks the grid layout used in personas listing, so I don't think it's worth doing right now.

Attaching the patch just in case someone wants to take a look:
```diff
diff --git a/src/olympia/addons/templates/addons/persona_preview.html b/src/olympia/addons/templates/addons/persona_preview.html
index 08b7695..8bee094 100644
--- a/src/olympia/addons/templates/addons/persona_preview.html
+++ b/src/olympia/addons/templates/addons/persona_preview.html
@@ -106,11 +106,7 @@
     </h4>
 
     {% if linked %}
-      <div class="persona-install">
-        <button class="add">
-          <span>{{ _('Add') }}</span>
-        </button>
-      </div>
+      {{ install_button(addon) }}
     {% endif %}
   </div>
 {% endif %}
diff --git a/static/css/restyle/restyle.less b/static/css/restyle/restyle.less
index 3d813c3..8df5601 100644
--- a/static/css/restyle/restyle.less
+++ b/static/css/restyle/restyle.less
@@ -1668,8 +1668,8 @@ h3.author .transfer-ownership {
 
   &:focus,
   &:hover {
-    height: 136px;
-    margin-bottom: -36px;
+    height: 162px;
+    margin-bottom: -62px;
   }
 
   h3 {
@@ -1687,10 +1687,6 @@ h3.author .transfer-ownership {
     }
 
   }
-
-  a {
-    display: inline;
-  }
 }
 
 .persona-list-3col {
@@ -1872,10 +1868,7 @@ h3.author .transfer-ownership {
 
 // This is used to override JS that tries to mess with these styles :'(
 .restyle .persona.hovercard a {
-  background: none !important;
-
   .persona-preview [data-browsertheme] {
-    background: none;
     border: 0 !important; // zamboni.css defines this as !important :-/
   }
 }
```
