### ISSUE TITLE
Autocomplete endpoint returns results with null names

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6189]
Hi,

The autocomplete endpoint returns results with `null` value for the `name` field.

[The documentation](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#autocomplete) says it returns a subset of fields but its behavior is similar to the search API. In the [add-ons object documentation](https://addons-server.readthedocs.io/en/latest/topics/api/internal.html#addon-detail-object), the `name` field is nullable, so that behavior could actually be correct.

Yet, I would expect proper results to suggest addons to the users. I can filter the invalid entries on the frontend, but not sure if it makes sense to expose unusable data.

Thanks.

---

Example: https://addons-dev.allizom.org/api/v3/addons/autocomplete/?app=android&q=adblock%20P&lang=en-US

<details>

```json
{
    "results": [
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addon_icons/394/394968-64.png?modified=1392504497",
            "id": 394968,
            "name": "Adblock Edge",
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/adblock-edge/"
        },
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addons/361486/preview_small.jpg?1328106102",
            "id": 361486,
            "name": "A P P L E",
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/a-p-p-l-e/"
        },
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addons/446596/icon.png?1371247873",
            "id": 446596,
            "name": "Light_Trails :P",
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/light_trails-p/"
        },
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addon_icons/6/6081-64.png?modified=1379299943",
            "id": 6081,
            "name": null,
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/verificador-ortogr%C3%A1fico-para-p/"
        },
        ...
    ]
}
```
</details>

**Comment by eviljeff** [comment]
looks like a l10n fail somewhere along the way - https://addons-dev.allizom.org/api/v3/addons/autocomplete/?app=android&q=adblock%20P&lang=pt-BR includes the name but https://addons-dev.allizom.org/en-US/firefox/addon/verificador-ortogr%C3%A1fico-para-p isn't broken enough not to have the name.

**Comment by diox** [comment]
This appears to be working for me now. Maybe because of the recent fixes following the elasticsearch upgrade? @willdurand can you retry on dev/stage and tell us if there are still autocomplete queries that produce `null` names?

**Comment by willdurand** [comment]
@diox I am still seeing `null` names with the URL I pasted above (https://addons-dev.allizom.org/api/v3/addons/autocomplete/?app=android&q=adblock%20P&lang=en-US).

<details>

```json
{
    "results": [
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addon_icons/394/394968-64.png?modified=1504086960",
            "id": 394968,
            "name": "Adblock Edge",
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/adblock-edge/"
        },
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addons/361486/preview_small.jpg?1328106102",
            "id": 361486,
            "name": "A P P L E",
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/a-p-p-l-e/"
        },
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addons/446596/icon.png?1371247873",
            "id": 446596,
            "name": "Light_Trails :P",
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/light_trails-p/"
        },
        {
            "icon_url": "https://addons-dev-cdn.allizom.org/user-media/addon_icons/6/6081-64.png?modified=1379299943",
            "id": 6081,
            "name": null,
            "url": "https://addons-dev.allizom.org/en-US/firefox/addon/verificador-ortogr%C3%A1fico-para-p/"
        },
        ...
    ]
}
```

</details>

**Comment by diox** [comment]
Oops, tested the wrong URL. Well, at least it didn't disappear magically, that's good, I was wondering how the ES fixes could have caused that.

**Comment by willdurand** [comment]
Thanks for the update!
