### ISSUE TITLE
Expose rating counts grouped by star in API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6191]
The API (maybe [add-on detail API](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v3-addons-addon-(int-id%7Cstring-slug%7Cstring-guid)-)?) needs to expose rating counts grouped by stars. It could look something like this (just an idea):

```js
{
  "slug": "some-addon",
  "ratings": {
    "count": 1913,
    "count_per_star": {
      "5": 1478,
      "4": 237,
      "3": 95,
      "2": 41,
      "1": 62,
    }
  }
}
```
Here is how we will be rendering it [in the UI](https://github.com/mozilla/addons-frontend/issues/2564):

<img width="461" alt="screenshot 2017-08-17 17 03 44" src="https://user-images.githubusercontent.com/55398/29435943-dcae41a8-836e-11e7-8357-3d390a7fab75.png">

**Comment by diox** [comment]
The reviews API already has a `show_grouped_ratings` parameter for this : http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html

Is that enough for you ? It's not ideal for perf to have this in the add-on detail API.

**Comment by kumar303** [comment]
Oh! I somehow totally forgot about that one. Thanks, I'll try it with that and see if I run into any issues.
