### ISSUE TITLE
Clear up garbage playmate themes from stage

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6200]
### Describe the problem and steps to reproduce it:
I'm debugging add-ons and searching for themes, then I get a screen full of women in lingerie. Coffee shop development becomes awkward, contributors feel off-put during development, and I let out a frustrated sigh knowing this is likely just data from production.

Search https://addons.allizom.org/en-US/firefox/search/?q=a&cat=themes to see what I'm talking about. (I was using addons-frontend `localhost` and hitting the stage API using https://addons.allizom.org/en-US/firefox/search/?q=a&type=persona as a URL).

### What happened?

I frowned as I thought of all the contributors this would turn away from add-ons development because they think our stage data is full of lingerie models uploaded by the team, even though this is likely just replicated production data. I'm no prude, but who wants their browser to constantly look like this anyway? Okay, whatever...

### What did you expect to happen?

No lingerie models appear during my development using the stage server as reference.

### Anything else we should know?
It would be great if these could be deleted or flagged. Maybe we need some kind of flag for these add-ons, not to hide them or not host them, but at least to not get copied to stage? Or some filter I can easily apply?

**Comment by eviljeff** [comment]
Well... we can't programmatically filter existing personas based on an individual's definition* of what is appropriate or not.  Those personas were with acceptable content guidelines* when uploaded to production.
You're getting those particular personas because you're searching for "a" - if you searched for "b" the results are different.  As it's stage no-one is going to care if you delete anything you think unacceptable though - you have the permissions to delete any risky theme.

* which may be disagreed with, but it's impossible to set a global standard - the North American attitude to nudity tends to greater prudity than European, but less so than many Middle Eastern countries.   Decisions for Product, anyway.

**Comment by tofumatt** [comment]
Yeah, I get there isn't a programmatic way to do this. I also understand I'm being a prude 😅

When I'm at home it's just sort of annoying, but I'm actually thinking about the developer who *is* working on this from a cafe in Qatar or Indonesia. In Europe or the Americas I'll generally just get a raised eyebrow, but this stuff (unexpectedly, to a new developer at least) popping up on a screen might be embarrassing.

If product were cool with some kind of "mature content" flag–no age verification needed or anything, just a flag to say "this theme contains lingerie models or Rambo-style killing sprees"–that'd be great. I'll just force it on for development when I'm at a cafe! 😉

@jvillalobos–has stuff like this been addressed before?

**Comment by diox** [comment]
> When I'm at home it's just sort of annoying, but I'm actually thinking about the developer who is working on this from a cafe in Qatar or Indonesia. In Europe or the Americas I'll generally just get a raised eyebrow, but this stuff (unexpectedly, to a new developer at least) popping up on a screen might be embarrassing.

:+1: and IMHO, it's just as problematic for *users* in those countries as well, in production. I'm no prude either, I don't mind for myself, but this could be a bit embarrassing (or worse!) for some users...

**Comment by dessant** [comment]
Most of them may also infringe on someone's copyright. 😋

**Comment by tofumatt** [comment]
> Most of them may also infringe on someone's copyright. 😋

That may be true, although we have to rely on copyright holders to inform us of violations because of, I believe, how DMCA safe harbour works. Or something like that. I am not a lawyer 😆

**Comment by eviljeff** [comment]
If we're just talking about stage, and we havn't synced data from prod in a loooong time, the easiest fix may just be to delete any theme you don't like the look of.  That won't address the issues for users of prod who may not (or whose country may not) approve of certain themes though.

**Comment by jvillalobos** [comment]
> has stuff like this been addressed before?

A "mature" flag has been considered before, but never prioritized. It's still in the back burner and could be considered for next year.

Additionally, new themes will allow us to have unlisted themes. We could potentially remove all mature themes from AMO and have them be unlisted instead. That's more of a content decision, but again, not for the near future. /cc @atsay @devaneymoz

**Comment by atsay** [comment]
I just want to clarify that women in bikinis are ok per guidelines, but definitely not rambo-style killing sprees.

Flagging could work if it happened on the review side. But how would you handle all the themes that are already there?

**Comment by tofumatt** [comment]
Thanks. Sorry to equate them too, that was lazy of me. I haven't encountered any gore yet, just bikinis.

I'm not sure how to deal with the data that's already there aside from a "flag as mature" button we could slowly click on all the offending themes. I don't think this is the kind of thing we should (expect to) automate.

I'd simply like reviewers and developers to have a simple, opt-in checkbox that says "mature content". That doesn't have to mean nudity or whatever, but all the bikini girls, anime girls, etc. could just be flagged with that and searches could exclude them by default with a simple check-box.

**Comment by atsay** [comment]
I suppose hunks would meet the same fate? https://addons.mozilla.org/en-US/firefox/search/?q=hunk&cat=themes

**Comment by tofumatt** [comment]
Sadly, yes. I just see fewer of them in the search results for whatever reason, but I would just think of all of those themes as being at least somewhat "mature" in their nature.

Though https://addons.mozilla.org/en-US/firefox/addon/christmas-hunk/ is amazing and I'm better for knowing about it.
