### ISSUE TITLE
kompozer/0.8b3

### ISSUE THREAD

**Issue by jiskte** [mozilla/addons-server#6201]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org/

If there isn't any contact info available for that developer we're sorry about that, but we aren't able to offer support for add-one that weren't developed by Mozilla.
