### ISSUE TITLE
Add a search param for featured add-ons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6205]
The new search mocks include a switch to include only featured add-ons, but the current search API doesn't support returning only featured add-ons.

Maybe this is unclear or really tough to implement and I think it's a bit of a strange feature anyway. Would this be a tough option to add to the [Search API](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search)?

See: https://github.com/mozilla/addons-frontend/issues/2956

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
