### ISSUE TITLE
Ignore platform filter for personas

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6206]
This isn't a blocker but it would be nice if the `platform` filter was ignored when it will only cause empty result sets. For the new search filter (https://github.com/mozilla/addons-frontend/issues/2956) we allow sending `sort`, `platform`, and `type` params (in any combination).

When `type=persona` and `platform` is set to anything there are no results returned, even though the persona *should* work with any of those platforms. I guess the filters are looking for add-ons that have *exclusive* compatibility with `platform`... but arguably personas should always be compatible.

We could (and may well) hide the filter option for `platform` when the user selects `type=persona`, but it seems like platform should be a filter that returns add-ons that are compatible with that platform but not flagged as *exclusively compatible* with that platform.

**Comment by diox** [comment]
Yeah, we should just always consider them available for all platforms at indexing time, that way you could even search for all add-ons (regardless of type) for a given platform.

**Comment by tofumatt** [comment]
Another thing to note is that passing the `appversion` param (eg `/search/?appversion=57.0&app=firefox&q=test`) will result in only extensions being returned because themes seem not to have this compatibility info set. Searching for themes specifically with the same query (eg `/search/?appversion=57.0&app=firefox&q=test&type=persona`) results in zero themes/zero search results.

It would also be nice if themes were returned for those searches as they are compatible.

**Comment by diox** [comment]
We should apply a similar strategy for the `appversion` as the one I describe for the `platform` above: just set a low min, high max compatibility with Firefox for all personas.
