### ISSUE TITLE
Different results for same empty search in collections

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6209]
Steps to reproduce:
1.Perform an empty search on collections (https://addons-dev.allizom.org/en-US/firefox/collections/)
2.Perform the same empty search a few more times.

Expected results:
1.Search results should be displayed in the same order

Actual results:
The results are displayed in different orders, this issue also reproduces when refreshing the page after the search is performed.

Please see video for this issue:
![searchsearch](https://user-images.githubusercontent.com/1583842/29518626-c4b67572-8682-11e7-86aa-9ca68fd075db.gif)

**Comment by vcarciu** [comment]
Issue found during verification of #6190

**Comment by vcarciu** [comment]
This was verified in AMO-dev FF55(Win 7).

**Comment by EnTeQuAk** [comment]
Actually, this could very well be missing data on -dev, this works perfectly fine on -stage and -prod -> https://addons.allizom.org/en-US/firefox/search/?cat=collections&sort=all

We don't have stats running on -dev and most popular afair is based on our stats. Stage has bits of our production data so it does have some stats or at least most popular ratings copied.
