### ISSUE TITLE
Compatible add-ons have "Download anyway" link

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6212]
Steps to reproduce:
1. Load details page to a compatible with your browser add-on i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-simple/?src=search or https://addons-dev.allizom.org/en-US/firefox/addon/firebug/?src=search

Expected results:
There is a green installation button.

Actual results:
There is a "Download anyway" link under the installation button.

Notes/Issues:
- reproducing for compatible extensions and webextensions
Verified on FF55(Win 7). Reproducing only on dev.
Screenshot for this issue:
![webext](https://user-images.githubusercontent.com/15685960/29527371-584121f2-86a1-11e7-867b-8c16108f9819.png)

**Comment by diox** [comment]
QA: I moved the "Download anyway" link into the warning being shown when there are no compatible versions. It should now be hidden when the add-on is compatible, and shown otherwise, unless we can't find an appropriate platform (*)

Please test with various platform/version incompatibility/browser scenarios.

(*) It can't be shown if the *platform* is incompatible, because we would not know which link to show.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7) and obtain the following:

> It can't be shown if the platform is incompatible, because we would not know which link to show.

- link not shown for incompatible platform
![not_shown_for_incomp_plat](https://user-images.githubusercontent.com/15685960/29618882-2938fa10-8822-11e7-81bb-d8f09f487e01.png)

- "Download anyway" triggers a download
![down](https://user-images.githubusercontent.com/15685960/29618966-6153b1ec-8822-11e7-90e1-4afa9e3f06ca.gif)

- checked some compatible extensions and the link is hidden
![compat](https://user-images.githubusercontent.com/15685960/29619021-8d5b6906-8822-11e7-91f3-63c3bd83e733.png)

@diox: 
1. Should we show the link in listing pages also?
![2017-08-23_1551](https://user-images.githubusercontent.com/15685960/29619137-efd9cbae-8822-11e7-8678-99a9810fcaf2.png)

2. Should we have the link for Thunderbird, SeaMonkey or Android compatible with your platform, but incompatible with used browser? Because we are repetitive - example - https://addons-dev.allizom.org/en-US/seamonkey/addon/tlegacya-2/
![thunder](https://user-images.githubusercontent.com/15685960/29619634-395cd676-8824-11e7-9921-97728d1553cf.png)

**Comment by diox** [comment]
1. I decided against it showing it in the listing pages. If people want to download anyway they can go to the add-on detail page
2. It's not ideal but let's keep it for now until someone complains because it's just a cosmetic edge case and I'm sick of this button code...

**Comment by ValentinaPC** [comment]
Based on above verification and comments we can mark this as verified-fixed.
