### ISSUE TITLE
"Find a replacement" is not designed to be helpful.

### ISSUE THREAD

**Issue by hwine** [mozilla/addons-server#6214]
### Describe the problem and steps to reproduce it:
With 57 & support for legacy add-on's enabled, the link for "Find a replacement" is not designed to be helpful. While the URL from Firefox 57 includes the name, and some features, of the legacy add-on, every request is redirected to "https://addons.mozilla.org/en-US/firefox/collections/mozilla/featured-add-ons/?src=find-replacement"

### What happened?
I got directed to a [list](https://addons.mozilla.org/en-US/firefox/collections/mozilla/featured-add-ons/?src=find-replacement) that has nothing to do with the extension I'm trying to find a replacement for.

### What did you expect to happen?
I expected to, at least, be directed to a search that includes my legacy add-on, and thus a relevant list of add-ons to consider -- not 124 possibly unrelated add-ons.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Note: this is not #6162 -- I'm saying the "featured add-ons" collection is a poor target, regardless of presence of legacy apps. My legacy add-on may never have been featured.

**Comment by jvillalobos** [comment]
The Featured Add-ons list is the fallback option, in case there are no set replacements for the particular add-on you're looking for. The Find Replacement feature is optimized to provide some alternatives for the top add-ons, but for the long tail there won't be anything else we can recommend.

We hope this will become more useful as more add-ons are ported and we have more to choose from as recommendations, but there are many add-ons that inevitably won't have a suitable replacement.

**Comment by hwine** [comment]
Ah, got it. That makes more sense. It would be nice if the experience was smoother, but that's not a bug.

In an ideal world, there would be a brief note for the long tail folks "Sorry, we don't have a a strong recommendation, here are some things to browse through."

**Comment by MikkCZ** [comment]
Well, the featured list currently contains a lot of legacy addons. This will change before the release or beta, right?

**Comment by gaby2300** [comment]
I am sorry but till "Find a replacement" isn't really helpful and even
leads to non compatible with Firefox 57 addons, wouldn't it be better to
avoid offering the option?

**Comment by diox** [comment]
> Well, the featured list currently contains a lot of legacy addons. This will change before the release or beta, right?

Yes.

> I am sorry but till "Find a replacement" isn't really helpful and even leads to non compatible with Firefox 57 addons, wouldn't it be better to avoid offering the option?

Nightly is not release for a reason :)

**Comment by gaby2300** [comment]
Of course! But as we are trying to get as many Nightly users as we can and
they are already grumbling about the addons issue, I thought this wculd be
yet another item to grumble about and lead them to stop using Nightly and
Firefox all together. It's not what we want, is it?

**Comment by jvillalobos** [comment]
I would expect Nightly users to understand that nothing around it is a finished product, and things are bound to break. If they decide to stop using Nightly, I really doubt it will be because the recommendations feature wasn't useful for them.
