### ISSUE TITLE
External API to delete unlisted add-ons

### ISSUE THREAD

**Issue by codefisher** [mozilla/addons-server#6221]
I have been using the API to create unlisted add-ons.  I would like to be able to easily clean them up after because I am getting quite a lot of them now.  There is no way in the API to delete add-ons.  I know it might be a security risk to allow this for any add-on, but for those that are unlisted it might be permitted?

For a bit of context to this question see my online tool: https://codefisher.org/toolbar_button/link-button-maker/

**Comment by eviljeff** [comment]
The Addons API doesn't have any modification functionality right now, only Listing and Detail (and Create, via the separate signing API).  At some point we do plan to expand it so all actions can be carried out via the API though - probably Q1 2018, though we might be able to start late Q4.

**Comment by codefisher** [comment]
Not stale.
