### ISSUE TITLE
Upload a webextension with a bogus strict_max_version and it hits amo-validator

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#6226]
### Describe the problem and steps to reproduce it:

Upload the extension here: https://www.dropbox.com/s/lp21hwbooscovat/new-firefox-extension.zip

### What happened?

Got an error that said "This tool only works with legacy add-ons."

### What did you expect to happen?

It's not a legacy add-on, yet that string is from amo-validator: https://github.com/mozilla/amo-validator/blob/50e2e5cb9c6d1a94e1a4c7c6d312dcea860164f4/validator/submain.py#L180

### Anything else we should know?

<img width="995" alt="screenshot 2017-08-22 20 31 35" src="https://user-images.githubusercontent.com/74699/29598002-0d0c35a2-877b-11e7-9524-3fd236fc3517.png">

**Comment by EnTeQuAk** [comment]
This is indeed very weird, as far as I know the we decide whether or not to use linter vs validator based on if there's a `manifest.json` present in which case we mark an extension as a WebExtension so there is not much parsing going on before that decision is happening.

**Comment by diox** [comment]
Maybe some weird exception handling - if we catch the error by accident and we do a `if` without a `else` to call the linter or the validator, we might end up calling the linter, raising an exception, catching it, calling the validator? It should be rather obvious to spot if that's the case.

**Comment by diox** [comment]
Good news is that I can reproduce this locally.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
A bogus strict_max_version does not turn the webextenstion into a legacy add-on.
Postfix screeenshot:
![bogus](https://user-images.githubusercontent.com/15685960/29664447-451112f2-88d8-11e7-9e1c-b090d1b0b15b.png)
