### ISSUE TITLE
Sorting add-ons after "Type" does not work as expected in Reviewer Tools

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6230]
Steps to reproduce:
1. Load New Add-ons queue in Reviewer Tools https://addons.allizom.org/en-US/editors/queue/new
2. Sort the add-ons after "Type"

Expected results:
Add-ons are sorted alphabetically.

Actual results:
Add-ons are not sorted alphabetically. 

Notes/Issues:
- reproducing in all queues.
Verified on FF55(Win 7). reproducing on dev and stage.
![2017-08-23_1542](https://user-images.githubusercontent.com/15685960/29616324-be997ebc-8819-11e7-9123-3fce2189a027.png)

**Comment by eviljeff** [comment]
It's sorting by the numeric type ID (Extension=2).  TBH, I think the only use-case for sorting by type is to group non-Extension add-ons together and the secondary sort isn't that important beyond that (though I'd expect it to be something sensible, like waiting time)
