### ISSUE TITLE
Change default sorting to be "Updated" on "developers/addons" (my add-ons) page

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#6235]
### Describe the problem and steps to reproduce it:
Open https://addons.mozilla.org/developers/addons, see your uploaded add-ons.

### What happened?
There may be many add-ons, and they are sorted by name by default. This is unreasonable.

### What did you expect to happen?
Updated date sorted by default. 
Consider grouping for recent updates, listed, etc.

### Anything else we should know?
If the user uses automation tool (like https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/?src=github), may uploaded many add-ons.

**Comment by yfdyh000** [comment]
Maybe this issue should be reported at https://github.com/mozilla/addons-frontend/issues?

**Comment by EnTeQuAk** [comment]
This is actually perfectly fine here. The developer hub is on addons-server and will stay here for quite some time. The developers home page https://addons.mozilla.org/developers/ does contain a new layout and way of showing listed vs unlisted but I agree, sorting by something more reasonable is a good idea. Although, it's hard to argue that sorting by name is predictable and easy to figure out for the user.

I'd say this needs UX + Product to make an educated decision.

**Comment by eviljeff** [comment]
@jvillalobos because `needs: product` label doesn't alert product

**Comment by jvillalobos** [comment]
Product read no tags!

That page already has the sorting options, so I think it's just a matter of changing the default (gfb, maybe?). That's fine with me, and it's probably what we'll do when we redesign those pages next year.

**Comment by wagnerand** [comment]
Mentor: @diox 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by diox** [comment]
@raajitr fixed this in #6732.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
My Add-ons is now sorted after "Updated" by default.
Sorting is working as expected.
Postfix screenshot:
![2017-10-19_1836](https://user-images.githubusercontent.com/15685960/31779735-81b485a4-b4fc-11e7-97cf-c4c694b7f94b.png)
