### ISSUE TITLE
uBlock origin can't upload their extension

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#6236]
Mostly in https://github.com/gorhill/uBlock/releases/tag/1.13.10, I'm filing on their behalf.

My guess is that uBlock already has a WebExtension in the Beta channel and the check to see if a WebExtension version already exists does not take that into account. That's a guess though, someone should check that's the case.

Would like to give this a bit of priority if we can please.

**Comment by wagnerand** [comment]
Side note: I was able to override the failed validation and submitted the version on behalf of the author.

**Comment by diox** [comment]
Note that fixing this creates another potential problematic edge case:
- User installs a beta (webext) version
- User then wants to install the public (legacy) version which has a higher version number
- Firefox fails to install, since it's a downgrade from a webext.

**Comment by andymckay** [comment]
At least in Firefox 57 that will cease to be a problem.
