### ISSUE TITLE
Older versions of legacy add-ons can't be downloaded

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#6237]
### Steps to reproduce:
1. Open a legacy add-on Version History page. I.e: https://addons.allizom.org/en-US/firefox/addon/fastest-notifier-for-gmail/versions/?page=1#version-0.1.6.1-signed
2. Hover over any version and observe the install button.

### Expected results:
The button is grayed out but there is a link to download the version anyway.

### Actual results:
Any of the versions displayed in the Version History page can't be downloaded.

### Notes/Issues:
Verified in FF55(Win7) Issue can be reproduced in -dev and stage
Screencast for this issue: 
![can tdownloadolderversions](https://user-images.githubusercontent.com/15685441/29664436-3bee3aba-88d8-11e7-8d9b-f9711c3d1dad.png)

**Comment by diox** [comment]
Yes, I placed the "Download anyway" link in the comp info box on the detail page, but I didn't want to overload the other pages with more links.

**Comment by diox** [comment]
@jvillalobos do we care about that?

**Comment by jvillalobos** [comment]
Yes, I think the All Versions page should let you download old versions.

**Comment by madalincm** [comment]
Verified as fixed in FF55(Win7) in addons-dev.allizom.org
Postfix screencast:
![versionhistorydownloadbutton](https://user-images.githubusercontent.com/15685441/30428302-c18e3682-995b-11e7-8f52-9fcf60ad8c11.png)
