### ISSUE TITLE
Legacy-add-ons that have contribution roadblock can't be downloaded from the collection page they are listed

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#6240]
### Steps to reproduce:
1. Open this collection page: https://addons.allizom.org/en-US/firefox/collections/mozilla/webdev-toolbox-ivan-krsti%C4%87/
2. Scroll to the FoxyProxy Standard add-on and try to install it.

### Expected results:
The add-on can be downloaded.

### Actual results:
The Continue to download button is inactive.

### Notes/Issues:
Verified in FF55(Win7) Issue can be reproduced in -dev and stage
Screencast for this issue: 
![contributeroadblockdownloadbuttoncollectionview](https://user-images.githubusercontent.com/15685441/29670359-1f09973e-88ef-11e7-8a3e-5d2562e6f178.png)

**Comment by diox** [comment]
I think I'd rather work on removing contributions that fixing this one...

**Comment by muffinresearch** [comment]
Roadblocks were removed with new contributions.
