### ISSUE TITLE
Flag CSP header for review only if needed

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-server#6258]
CSP works by restricting features, if a feature is not explicitly restricted through its directive or if it doesn't fall back to a declared `default-src`, it means it is allowed. Setting a custom CSP header is optional.

The [default CSP header](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_Security_Policy#Default_content_security_policy) is `"script-src 'self'; object-src 'self';"`.

Consider this custom header:
```
default-src 'self'; style-src 'self' 'unsafe-inline'; img-src * data:; connect-src *;
```
Both `script-src 'self'` and `object-src 'self'` fall back to `default-src 'self'` and the rest of the directives could contain anything, because setting them is optional, and by not setting them they implicitly allow everything.

Custom headers like these currently cause a warning and are flagged for additional review, it would be nice to only issue a warning if the directives of the default header are rendered more permissive by the custom header.

**Comment by diox** [comment]
https://github.com/mozilla/addons-linter/issues/1298 should have taken care of this, so maybe this wasn't enough? cc @EnTeQuAk for investigation.

**Comment by wagnerand** [comment]
The mentioned CSP does not show a raise a warning for me, when running against the linter.

**Comment by dessant** [comment]
My last submit is from Aug 16, 2017, and it has this warning:
```
"content_security_policy" is defined in the manifest.json

Warning: A custom content_security_policy needs additional review.
```

CSP header:
```
default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; object-src 'none'; child-src 'none'; form-action 'none';
```

https://addons.mozilla.org/en-US/firefox/addon/view-page-archive/

**Comment by dessant** [comment]
I've checked both headers now with addon-linter 0.24.0 and they are not flagged anymore indeed. https://github.com/mozilla/addons-linter/pull/1434 was likely not in production at the time of my last submit. Sorry for not checking again before opening the issue. 😋

**Comment by SVSanta** [comment]
Please add some STR or the label "qa: not needed". Thanks!
Maybe we can test and find some scenarios around the fixed issue.

**Comment by jonathanKingston** [comment]
I'm going to double check the linter however a more permissive header of unsafe inline CSS should be flagged, I don't see why you need this @dessant.
