### ISSUE TITLE
Disco Pane passes different information than "Add to Firefox" button for LWTs

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#6261]
### Describe the problem and steps to reproduce it:
This was originally reported in bugzilla at https://bugzilla.mozilla.org/show_bug.cgi?id=1393361
The issue is that themes installed from the disco pane don't include the icon (among other things).

### What happened?
A user-visible symptom is that if a theme is installed from the disco pane and then viewed in about:addons, it does not have an icon.  But a theme installed from its regular AMO page does have an icon in about:addons.

### What did you expect to happen?
For the theme to have an icon regardless of how it was installed.

### Anything else we should know?
Captured theme data when installing "c o l o r s" from the disco pane:
```
{
  "id":"61230",
  "name":"c o l o r s","
  description":null,
  "headerURL":"https://addons.cdn.mozilla.net/user-media/addons/61230/colors.png?1264095023",
  "footerURL":"https://addons.cdn.mozilla.net/user-media/addons/61230/colorsfoot.png?1264095023",
  "textcolor":"#ae24d4",
  "accentcolor":"#d4d4d4",
  "author":"andreacastillo"
}
```

Capture theme data when installing the same extension with "Add to Firefox" from its main AMO page:
```
{
  "category":"Abstract",
  "iconURL":"https://addons.cdn.mozilla.net/user-media/addons/61230/preview_small.jpg?1264095023",
  "headerURL":"https://addons.cdn.mozilla.net/user-media/addons/61230/colors.png?1264095023"
  ,"name":"c o l o r s",
  "author":"andreacastillo",
  "footer":"https://addons.cdn.mozilla.net/user-media/addons/61230/colorsfoot.png?1264095023",
  "previewURL":"https://addons.cdn.mozilla.net/user-media/addons/61230/preview_large.jpg?1264095023",
  "updateURL":"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/61230",
  "accentcolor":"#d4d4d4",
  "header":"https://addons.cdn.mozilla.net/user-media/addons/61230/colors.png?1264095023",
  "version":"1.0",
  "footerURL":"https://addons.cdn.mozilla.net/user-media/addons/61230/colorsfoot.png?1264095023",
  "detailURL":"https://addons.mozilla.org/en-US/firefox/addon/c-o-l-o-r-s/"
  ,"textcolor":"#ae24d4"
  ,"id":"61230",
  "description":""
}
```

**Comment by diox** [comment]
It looks like the API (all endpoints) does pass this data, so I think this is a frontend bug. Thoughts, @tofumatt ?

**Comment by ValentinaPC** [comment]
@diox : can add that this is also happening while installing a theme for new desktop pages.

**Comment by ValentinaPC** [comment]
Closing this due to its transfer to addons-frontend.
