### ISSUE TITLE
Incompatibility banners look concatenated in My Profile

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6262]
Steps to reproduce:
1. Submit an add-on that is compatible with Firefox for Android and that is not compatible with your platform i.e. https://addons-dev.allizom.org/en-US/android/addon/saveas/
2. Go to My profile page and hover over you add-on while using Nightly

Expected results:
Incompatibility banners have no display issues.

Actual results:
Incompatibility banners have layout issues.

Notes/Issues:
Verified on FF57(Win 7).
Labels look cut in FF55 also.
Screenshots for this issue:
FF55
![ff55](https://user-images.githubusercontent.com/15685960/29776135-6e4fd74e-8c10-11e7-9803-2680d7165ad1.png)
FF57
![my_prof](https://user-images.githubusercontent.com/15685960/29776134-6e4bb9fc-8c10-11e7-8f02-8f8aed807a75.png)

**Comment by diox** [comment]
Is it just happening on the my profile page?

**Comment by ValentinaPC** [comment]
@diox : did not see it in other places. Will take a closer look today.

**Comment by muffinresearch** [comment]
Closing since this will be superceded by https://github.com/mozilla/addons-frontend/issues/2781
