### ISSUE TITLE
Omit `license` from search API results

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6270]
The search API currently returns `null` for every `license` field under the `current_version` of add-ons it returns. This is because we don't index that information in ES and we build a fake `Version` instance when serializing, without giving data for that field, so it ends up being `None`.

We hopefully don't need to return that data in search results, so it could be omitted entirely from the search endpoint instead of returning false information.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
