### ISSUE TITLE
Don't allow install of legacy add-ons on 57 for Android

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#6271]
### Describe the problem and steps to reproduce it:
1. Install the latest nightly on your Android device
2. Navigate to addons.mozilla.org 
3. Try to install Adblock Plus or any legacy extension

### What happened?
Install of Adblock Plus is successful

### What did you expect to happen?
Install of legacy extensions is not allowed on 57

**Comment by diox** [comment]
This is an addons-frontend bug (probably a dupe of https://github.com/mozilla/addons-frontend/issues/2888 which lands this week in prod)
