### ISSUE TITLE
Add support for collection contributors to API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6273]
Not sure if this was a change in the [PRD](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit) or it was overlooked when the rest of collections was implemented (possibly the latter as contributors weren't mentioned on the main Desktop Scoping doc, and only briefly mentioned at the end of the collections PRD)

Need:
- Contributors will need to be able to access and modify collections they are a member of
- ~list, add, remove contributors~
- ~change ownership of collection to a contributor~

**Comment by eviljeff** [comment]
@jvillalobos can you confirm about the 'change of ownership' function?  The existing collections feature allows it as part of managing contributors but the PRD doesn't mention it explicitly.  I do wonder how useful it will be - the only unique reference to a collection is the url, containing the owners username  -if it's transferred to another user it's going to have a different url with no way to discover the new collection url.

**Comment by jvillalobos** [comment]
I don't think we need change of ownership. The main use case for which we'll continue supporting contributors (for now) is the [Featured Themes collection](https://addons.mozilla.org/collections/mozilla/featured-personas/), which has various active contributors. It shouldn't be too hard to dupe a collection in a different account to simulate transfer of ownership.

**Comment by eviljeff** [comment]
Hmm.... but thinking about it, we need change of ownership for that case in particular - to be able to create a collection and assign it's ownership to Mozilla.  If the use case is just for featured collection that can be a setting in /admin though.
If collaborators is only useful for Mozilla featured collections too that could _also_ be a setting in /admin too?

**Comment by jvillalobos** [comment]
> create a collection and assign it's ownership to Mozilla

I think we're able to log in to the Mozilla account and create collections from there. It's not ideal, but we can do it.

> If collaborators is only useful for Mozilla featured collections too that could also be a setting in /admin too?

I'm sure it's used for non-Mozilla collections, too, but the reason I want to keep the feature is the featured themes collection. Not sure what you mean about having it be a setting in /admin, though. Do you mean that in /admin we would enable collaborators for specific collections?

**Comment by eviljeff** [comment]
Yes, I mean the only way to edit (add/remove) contributors to a collection would be via django admin in /admin, meaning realistically it would only be suitable for Mozilla collections.  If you _do_ want to retain the feature then that's possible too - we just need to add the API (and the front-end).

Understood about ownership changes - we won't implement that in the API.

**Comment by eviljeff** [comment]
logged https://github.com/mozilla/addons-server/issues/6418 to add django admin page(s) to manage contributors for Moz collections.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
