### ISSUE TITLE
Add to collection issue

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#6276]
Steps to reproduce:

1. Navigate to "Collections>Create a Collection" page.
2. In the "Enter the name of the add-on to include" field type "add".
3. Hove over any of the suggestions.
4. Click on the "Add to Collection" button.

Expected results:
The add-on is added to the collection.

Actual results:
The add-on is not added and the string is deleted from the "Enter the name of the add-on to include" field.

Notes/Issues:
Verified on AMO-dev FF55(Win 10).
The issue is also reproducible when introducing the name of the add-on in the "Enter the name of the add-on to include" field and pressing the "Add to Collection" button.
The behavior is slightly different on Nightly, it happens intermittently when hovering over suggestions.
Gif for this issue:
![add col not working](https://user-images.githubusercontent.com/28138132/29824134-5298c50a-8cd9-11e7-9f34-a742012b1b87.gif)

**Comment by eviljeff** [comment]
This only happens on Windows?  😨

**Comment by SVSanta** [comment]
Retested and reproduced the issue using Mac OS 10.12.3.

**Comment by muffinresearch** [comment]
Since the new collection feature is coming soon, I'm going to mark this as wontfix.

**Comment by muffinresearch** [comment]
Tracker issue for the new UI is here: https://github.com/mozilla/addons-frontend/issues/2782
