### ISSUE TITLE
Filter by compatibility within collection API

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-server#6279]
`project: firefox 57 compatibility`

## Enhancement request

At https://github.com/mozilla/addons-server/issues/4974#issuecomment-305976199 (2017-06-03) under _Add label to listing pages to highlight WebExtensions · Issue `#4974` · mozilla/addons-server_,  @erosman wrote:  

> Collections could also benefit from the tag

Additionally, it should be possible to: 

- exclude legacy items

– in other words, **filter by compatibility**. 

If not filter, then please at least allow readers to **sort by compatibility**. 

## For now, in the absence of tags

I use multiprocess-compatible [User Agent Overrider](https://addons.mozilla.org/firefox/addon/user-agent-overrider/) to quickly set or unset an appropriate string. 

### Examples

https://addons.mozilla.org/en-GB/firefox/collections/Firebreathing/h/?sort=added (a _Hidden Gems!_ collection), without then with an override: 

![2017-08-30 01 36 15 hidden gems collections add-ons for firefox](https://user-images.githubusercontent.com/192271/29850352-ed9b572a-8d24-11e7-9993-87ca92138d6d.png)

`Mozilla/5.0 (X11; FreeBSD amd64; rv:57.0) Gecko/20100101 Firefox/57.0`

![2017-08-30 01 34 49 hidden gems collections add-ons for firefox](https://user-images.githubusercontent.com/192271/29850351-ed9910dc-8d24-11e7-8b75-81cbe1d98635.png)

[A more popular collection](https://addons.mozilla.org/en-GB/firefox/collections/davy-jones/optimizefirefox/?sort=popular) (6,284 followers), sorted by popularity, exemplifying the current likelihood of promotion of legacy items, without attention to compatibility – 

![2017-08-30 01 59 14 optimized firefox collections add-ons for firefox](https://user-images.githubusercontent.com/192271/29850692-4a404f74-8d27-11e7-81d3-09fc57da3234.png) 

– then with: 

![2017-08-30 01 58 05 optimized firefox collections add-ons for firefox](https://user-images.githubusercontent.com/192271/29850691-4a3d1a16-8d27-11e7-8435-6dbb4b3b7afc.png)
 
I wondered whether the FreeBSD/Linux aspect of my `general.useragent.override` was skewing things, so I switched to: 

`Windows / Firefox 57: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0`

– then browsed all nine pages of that popular collection. Not one green display of compatibility `</cough> ;-)`

**Comment by eviljeff** [comment]
The collections feature is being rewritten and will be relaunched later this year with a different (more focused) feature set, so we both have to consider the current collections, and the rewrite.
@jvillalobos 
Is this kind of sorting/filtering necessary to add to the current collections views?  And should they be added to the API (and frontend)  The API currently supports some sorting [options](http://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-add-ons-list), but doesn't support any filtering.

**Comment by jvillalobos** [comment]
I think that filtering out incompatible add-ons by default in collections is a good idea. I wouldn't put any effort for this in the old front-end, though.

**Comment by eviljeff** [comment]
On the API side we can add support for platform and application parameters to be passed, and that will filter.  

It will be up to the front-end to pass these parameters, and handle the UI, as we can't filter by default unless we know what platform/application the user has.  @jvillalobos can you log the addons-frontend issue - there may be UX requirements, etc.

**Comment by eviljeff** [comment]
@jvillalobos said the companion issue in addons-frontend (mozilla/addons-frontend'3080) could be closed so I guess this is a wontfix too.
