### ISSUE TITLE
Remove Support and Viewer Addon author classes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6280]
> There are 193 Viewer role assignments, and 32 Support, very low numbers. I think it's fine to change those to Developer and remove both roles.

So lets remove them in devhub and elsewhere.

Original issue text:
~From https://bugzilla.mozilla.org/show_bug.cgi?id=1393849~

~The devhub UI (apparently) already prevents Non-[Owner|Developer] users from replying by disabling the reply button, but the API needs to enforce the check too.
Also need to fix email replies to not send reply tokens, and to check authorship class when considering if the email can be added.~

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/4313

Can/should we just remove the extra roles?

**Comment by eviljeff** [comment]
to c&p from irc a few days ago: personally I'd like to reduce the roles to just owner and developer, where the two have identical powers (except the ability to change ownership)
either support or viewer (I forget which) is Marketplace cruft anyway, just added to handle refunds.

@jvillalobos can we simplify things?

**Comment by wagnerand** [comment]
*Support* is Marketplace cruft.

**Comment by jvillalobos** [comment]
> Support is Marketplace cruft.

Aren't we all...

> can we simplify things?

I need to think more about roles and whether we need them at all. Let's not kill them yet.

**Comment by muffinresearch** [comment]
> I need to think more about roles and whether we need them at all. Let's not kill them yet.

@jvillalobos do you have any updates on whether these roles are relevant?

**Comment by jvillalobos** [comment]
There are 193 `Viewer` role assignments, and 32 `Support`, very low numbers. I think it's fine to change those to `Developer` and remove both roles.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF58 (Win10)

1. New roles as viewed by the "Owner" of the add-on
![image](https://user-images.githubusercontent.com/31961530/35572637-b6797218-05dd-11e8-8ae4-3ae9ae8520b5.png)
2. New roles viewed by the "Developer" - with no edit ownership rights

![image](https://user-images.githubusercontent.com/31961530/35572699-d919afae-05dd-11e8-8b1e-1e25e76e22da.png)
