### ISSUE TITLE
Cannot find opensearch plugins in search when app version is passed

### ISSUE THREAD

**Issue by yookoala** [mozilla/addons-server#6283]
### Describe the problem and steps to reproduce it:
1. Use Firefox 57 (nightly) to open https://addons.mozilla.org/en-US/firefox/search/
2. Search "Spanish"

### What happened?
Cannot see [SpanishDict Search](https://addons.mozilla.org/en-US/firefox/addon/spanishdict-search/), an OpenSearch plugin.

### What did you expect to happen?
Firefox 57 still support OpenSearch plugin. They should be visible.

**Comment by diox** [comment]
That's weird, search tools should be in `NO_COMPAT` and therefore compatibility should just be ignored for them. Random observations:
- I don't see it in search results when filtering with appversion (https://addons.mozilla.org/en-US/firefox/search/?q=spanishdict&appver=any vs https://addons.mozilla.org/en-US/firefox/search/?q=spanishdict&appver=57.0)
- In the API, it has `current_version.compatibility` returning... `{}`
- In the detail page, the install button is shown normally.

**Comment by yookoala** [comment]
Seems if you cannot see OpenSearch addon when you input `appver`.

Even with `appver=55.0`, those OpenSearch addons are not shown:
https://addons.mozilla.org/en-US/firefox/search/?q=spanishdict&appver=55.0&platform=linux

User can see OpenSearch addons because on stable Firefox version (55), the search won't include the `appver` in the URL.

**Comment by diox** [comment]
Yeah. The fix for #6206 (landing in prod next week) may have accidentally fixed this - I think we were indexing empty compatibility information and that caused the issue. I'm investigating.

**Comment by diox** [comment]
Confirming that #6206 does fix it. I fired up a reindex on dev and I can see the search tools in results, they are considered compatible with all apps and platforms. See https://addons-dev.allizom.org/en-US/firefox/search/?platform=linux&appver=57.0&atype=4 for instance.
