### ISSUE TITLE
Filtering by a list of authors in the search addons API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6285]
Refs #5786

---

For the frontend feature ["more addons by these developers/artists"](https://github.com/mozilla/addons-frontend/issues/2767), I found myself calling the API `N` times, `N` being the number of authors for a given add-on (using the `author` filter parameter).

Would it be possible to allow a (comma-separated maybe?) list of authors? The result should be a list of distinct add-ons.

Thanks!

**Comment by diox** [comment]
So, you want a list of add-ons developed by either of the authors, or a list of add-ons developed by the same group of authors?

**Comment by willdurand** [comment]
> So, you want a list of add-ons developed by either of the authors, or a list of add-ons developed by the same group of authors?

[According to the existing website](https://addons.mozilla.org/en-GB/android/addon/wikipedia-panel/), I would like to have a list of add-ons developed by either of the authors.
