### ISSUE TITLE
addons.mozilla.org doesn't support Galician?

### ISSUE THREAD

**Issue by jikamens** [mozilla/addons-server#6286]
Some users of my add-on recently translated it into Galician (gl-ES) for me, but when I went to customize its add-on listing on addons.mozilla.org with the strings they translated, I discovered that there doesn't appear to be any way for me to add Galician localizations to addons.mozilla.org. Is there some reason why Galician isn't available as an option on addons.mozilla.org? Is this fixable?

**Comment by muffinresearch** [comment]
@jikamens the new locale needs to be added and enabled.

@EnTeQuAk is there a script to create new locales?

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk is there a script to create new locales? Otherwise I presume this just needs a config update and the template files copied to a new locale dir?

tbh, I'll have to try. There isn't any script but in theory, creating the folder `gl-ES` in `locale`, updating the config and running the new locale script should suffice. If not this needs to be automated better.

Imho, in the past we were getting new locales directly from pontoon so potentially that's the first step to start: Add the locale to pontoon, which get's synced to us and then we can configure it.

**Comment by muffinresearch** [comment]
> Imho, in the past we were getting new locales directly from pontoon so potentially that's the first step to start: Add the locale to pontoon, which get's synced to us and then we can configure it.

Yep on addons-frontend the new locales generally appear via Pontoon which then fails a test because since we check for a match between dirs and the config. We also have a simple script to create new locales based on the config here [1].

[1] https://github.com/mozilla/addons-frontend/blob/51b44171b069b4c9e65798e07a6cca9f5d049336/bin/create-locales

**Comment by jikamens** [comment]
Ping?
