### ISSUE TITLE
Invalid strict_max_version does not return an error at webext submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6287]
Steps to reproduce:
1. Submit a webextension that has an unavailable `strict_max_version` set in its manifest i.e. https://addons-dev.allizom.org/en-US/firefox/addon/val-invalid-maxvrs/

Expected results:
An error message regarding the `strict_max_version` invalid value is displayed.

Actual results:
Submission is made with success. Max version is set to `*`. 

Notes/Issues:
Verified on AMO-dev FF57(Win 7).
- any invalid max_version can be used;
- webext cannot be installed;
Screenshot for this issue:
![strict-max-vrs](https://user-images.githubusercontent.com/15685960/29919624-bf3070c6-8e52-11e7-82c9-2c884bbae206.png)

**Comment by diox** [comment]
What's happening here is the `gecko` key is under `application` and not `applications`. So it's completely ignored, and the `strict_max_version` is therefore ignored as well. If you fix the manifest to use `applications` you'll see the correct errors:
* `Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?`
* `"/applications/gecko/strict_max_version" should match pattern "^[0-9]{1,3}(\.[a-z0-9*]+)+$"`

**Comment by ValentinaPC** [comment]
True. Thanks!
