### ISSUE TITLE
Link to "My submissions" broken on My profile page

### ISSUE THREAD

**Issue by peterbe** [mozilla/addons-server#6290]
### Describe the problem and steps to reproduce it:
I wanted to get to my existing add-ons I've published. Couldn't find the link. (Side-note; I did *not* think "Tools" is the right thing to click to manage my submissions). 
So I went to https://addons.mozilla.org/en-US/firefox/user/peterbengtsson/

### What happened?
On my profile page, there's a link ("1 add-on"). Clicking it does nothing. Just changes the anchor. 
<img width="1769" alt="screen shot 2017-08-31 at 11 00 38 am" src="https://user-images.githubusercontent.com/26739/29930204-bf0827fe-8e3b-11e7-91f8-7721cd2ba709.png">

The href of that link is `https://addons.mozilla.org/en-US/firefox/user/peterbengtsson/#my-submissions`

### What did you expect to happen?
To go to `https://addons.mozilla.org/en-US/developers/addons` after clicking that "1 add-on" link on the My Profile page. 

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
That's the intended behavior. Clicking on the link scrolls down to the `Add-ons I've created` section. The link is intended for the general public, not for developers to find their own add-ons.

The AMO front-end is undergoing a major rewrite that will probably go live later this year, so there's nothing to do here. The current designs feature a clearer link to the Developer Hub, where you can find your add-on submissions.

**Comment by peterbe** [comment]
Ha! Interesting. I appreciate your point but it's a sad thing nevertheless. Anchor links have always sucked in the web in the last 20 years when it comes to making it obvious what the anchor link is trying to focus into view. 

Good luck with the new rewrite!
