### ISSUE TITLE
Remove checkbox for Review Rules doc in submission process

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6293]
In #5579, we made some changes to the submission process to align it with post-review. One of the changes is that on the first step we won't show the full text of the Developer Agreement, and instead show some checkboxes and links pointing to the agreement, review policy, and review rules.

Since then, we merged the review policy and review rules, so we won't need the checkbox for the review rules. We just need these two:

- [ ] [Developer Agreement](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Agreement).
- [ ] [Review Policy](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews).

**Comment by vcarciu** [comment]
In issue description, first link is named "Developer agreement" , but in I can see that it is named "Distribution agreement" on -dev : 
![distributionagreement](https://user-images.githubusercontent.com/1583842/30061335-a9e68ede-924f-11e7-9087-98d04e387903.png)

Is this ok?

**Comment by diox** [comment]
Mmm I must have missed that, it was also "Developer agreement" in the previous issue. I'll change it.

**Comment by vcarciu** [comment]
Verified as fixed : 
![devag](https://user-images.githubusercontent.com/1583842/30069930-aba9d83c-926a-11e7-8f42-e5a5757fee20.png)
