### ISSUE TITLE
Cannot find Microsoft .net framework assist addon

### ISSUE THREAD

**Issue by Marcoevich** [mozilla/addons-server#6296]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I followed the Microsoft download link from https://configure.office.com/Scenario.aspx?sid=18 to install the addon. Note: you need an office 365 global admin account to check this. The download link provided is: https://addons.mozilla.org/nl/firefox/addon/microsoft-net-framework-assist/

### What happened?

Addon cannot be found, therefore I cannot run the checks using Firefox

### What did you expect to happen?

I expected to find an addon on the above location.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

![afbeelding](https://user-images.githubusercontent.com/1243033/29943976-dd59642e-8e9b-11e7-87e0-e775f5cbbb1b.png)

**Comment by jvillalobos** [comment]
That add-on was discontinued many years ago. That documentation is probably outdated.
