### ISSUE TITLE
Impossible to "Delete review" for removed add-ons

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#6299]
### Describe the problem and steps to reproduce it:
I tried to remove old reviews from my account.

For example: I could not remove the review for "Multi Links" on https://addons.mozilla.org/en-US/firefox/user/DavidHedlund/

### What happened?
Nothing.

### What did you expect to happen?
That the review get deleted.

### Anything else we should know?
I don't want to keep my useless reviews on my user account.

**Comment by diox** [comment]
mmm technically, those reviews should not appear anymore, so that's a duplicate of https://github.com/mozilla/addons-server/issues/5266

**Comment by davidhedlund** [comment]
@diox Thanks.
