### ISSUE TITLE
Featured add-on disappear while hovering over featured section for any Category

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6302]
Steps to reproduce:
1.From https://addons.mozilla.org/en-US/firefox/ , select any category (ie, https://addons.mozilla.org/en-US/firefox/extensions/download-management/)
2.Hover over Featured add-ons section

Expected results:
The focus will be on the add-on which is hovered, without any issues

Actual results:
While hovering over them, one of the add-ons disappear

NOTES:
NOT reproducible on Stage or -dev.

Please see video for this issue :
![philadelphiaexperiment](https://user-images.githubusercontent.com/1583842/29966885-804dee36-8f1c-11e7-8e3d-b3d82f5514b4.gif)

**Comment by diox** [comment]
It's also happening on dev/stage, it just depends on what add-ons are compatible with your browser in the featured section. Unfortunately on dev/stage it appears all featured add-ons haven't changed in a very long time and you only get incompatible add-ons, even with Firefox 55, so you don't see the problem. But you do see it with Chrome, for instance.

**Comment by diox** [comment]
I modified the featured add-ons on a category on dev to reproduce the problem there: https://addons-dev.allizom.org/en-US/firefox/extensions/alerts-updates/ (unfortunately the list is random so it's not guaranteed to happen - if you see "VersionTest" or "webext-setInterval7" in the featured list, then the bug should happen)

**Comment by vcarciu** [comment]
Verified as fixed : 
![featcateg](https://user-images.githubusercontent.com/1583842/30027409-9701adec-9189-11e7-9b30-df57e9333544.gif)
