### ISSUE TITLE
Update contributions data sent via API to Add-ons Manager

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6308]
This is part of #6069.

We need to update the contributions data sent in the [API](https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/guid:%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D?src=firefox&appOS=Darwin&appVersion=56.0a1) in the `contribution_data` section.

Required work:
* Send the new contributions URL using the Meet the Developers field (`meet_developers`).

Optional cleanup work:
* Stop sending the `link` field.
* Stop sending the `suggested_amount` field.

**Comment by ValentinaPC** [comment]
Verified this while installing an add-on that had old contribution set up, and no new contributions settings using FF58(Win 7) in AMO-dev.
- Installed the add-on https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/
- Went to about:addons page: the amount is gone
![aa](https://user-images.githubusercontent.com/15685960/30914135-35db2baa-a39b-11e7-9d5c-75fe98a78554.png)
- Contribute button redirects to paypal,.me even if an URL is not set in Dev Hub.

While setting a contribution URL - `https://www.patreon.com/ `- in Dev Hub, after installation, the contribution button from about:addons will still redirect to `paypal.me` page.
Is this ok, @eviljeff ?

**Comment by eviljeff** [comment]
@ValentinaPC can you confirm what Firefox config you have - are you definitely using the -dev api, not the stage one?

**Comment by ValentinaPC** [comment]
@eviljeff : I've changed both `extensions.getAddons.search.url`/ `extensions.getAddons.get.url` to point -dev . The redirection was bad only for this extension - meaning one that used old contributions, but now seems to be working as expected.

After checking things again....I think that it takes some time to apply changes in about:addons.
Removing the URL from Dev Hub, will maintain the redirection in about:addons to the URL previously set .
Please see complete video:
![url](https://user-images.githubusercontent.com/15685960/30962728-999f6800-a453-11e7-82eb-0abdd717b9ea.gif)

**Comment by eviljeff** [comment]
okay.  short term caching we can live with.
