### ISSUE TITLE
Add Micropayment to list of allowed payment providers

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6309]
Please add Micropayment (micropayment.de) to the list of allowed providers in the new contributions feature (#6069).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win7).
- `micropayment.de` was added to contributions domains list.
- User is redirected as expected from add-on details page while clicking on the "Contribute" button.
Postfix screenshot:
![2017-09-11_1206](https://user-images.githubusercontent.com/15685960/30267186-68849f22-96ea-11e7-8943-7c45cc101318.png)
