### ISSUE TITLE
Add content review list for post-review

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6310]
This is part of the post-review process specified in [this document](https://docs.google.com/document/d/1hVx-NbuVRc0wKXSdt8eHceObexY93YFzMXtqYC95nUs/edit). It's not a blocker for the initial release.

Add-ons submitted to be listed on AMO need to be screened for content, separately from their code post-review. This is what I think is needed (will be kept up to date with changes that come up in the discussion):
- [x] Add a `last_content_review` date field to add-ons (not versions or files).
- [x] Add a new content review list (/editors/queue/content) that lists all WebExtension add-ons without  `last_content_review`, or with a `last_content_review` that is older than a year. Columns: "Add-on" (the add-on name, linking to the review page), Flags, "Last Content Review". Sort by Last Content Review, with the empty ones at the top.
- [x] This new list can only be seen by users with the `Addons:ContentReview` permission.
- [x] Review pages for content review are identical than for post-review, with one difference: approving and rejecting should log different events in the history (Content Approval, Content Rejection), so they don't affect post-review risk rankings. Requesting information, super-review, and commenting behave exactly the same.
- [x] Both content approvals and post-review approvals should set the `last_content_review` date, since post-review also covers content.

TODO:
* Determine point values of Content Approval and Content Rejection for the incentives program.

**Comment by diox** [comment]
What should content rejection do, exactly? I assume also reject the version? What about other versions?

Also, should reject multiple versions action be present ?

**Comment by caitmuenster** [comment]
@jvillalobos and @kewisch should confirm this, but I think we should reject the version and all previous versions.

**Comment by jvillalobos** [comment]
> Also, should reject multiple versions action be present ?

Yes, rejection should work like in post-review: you can reject multiple versions. Rejecting means the versions are disabled and a message is sent to the developer.

> should approve/reject content log events be shown to developers? (I just noticed that the confirm auto approval is shown)

Rejections should be shown. Approvals shouldn't, including the confirm auto-approval. It's not particularly useful info for the devs, and could potentially be used to gather info on review timeframes, which we want to keep private.

**Comment by kewisch** [comment]
Are there mockups for what the content review UI would look like? Given that content reviewers don't care about the technical details, if possible I'd like the UI to fit on one screen and show all details relevant for the content review only. Here is an example from back when we did the manual auto-approval. The buttons are part of my add-on and were a quick hack solution to speed up the review process (along with pre-loading tabs).


![image](https://user-images.githubusercontent.com/607198/30854387-bf76aae6-a2b1-11e7-826c-768cd8959db6.png)

**Comment by jvillalobos** [comment]
The idea is for the pages to be identical to the post-review pages. While there is some unnecessary data for content review, I don't want to create specialized pages now, since we plan to rewrite the reviewer tools in the future (Q1-Q2) and developer time is very limited with everything else that is going on.

**Comment by kewisch** [comment]
Fair enough. I'll make the changes in my add-on for the time then :)

**Comment by diox** [comment]
Points values are going to be handled in https://github.com/mozilla/addons-server/issues/6473

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7) 
- a new Content Review queue was added in Rev Tools
- Approve Content/ Reject will remove the add-ons from the queue
- **Add-on Review Log do not mention which action - approve/reject - was made:**
![2017-10-05_0952](https://user-images.githubusercontent.com/15685960/31217251-f973e240-a9be-11e7-96a8-3200d637b4c7.png)
Is this ok?
- other reviews options are working as expected

Another thing I would ask is - what action will add the "Last Content Review" date?
Thanks!

**Comment by diox** [comment]
* Reviewlog is something I should fix.
* Last Content Review should be set when the add-on auto-approval is confirmed or when the add-on is content approved (we consider that when a reviewer confirms an approval, they are also approving the content). Once this happens the add-on should disappear from the content review list for a year.

**Comment by diox** [comment]
Re-opening to fix review log, the view has a specific `action_dict` I need to modify.

**Comment by diox** [comment]
Filed https://github.com/mozilla/addons-server/issues/6602 to handle this instead of doing this in this issue.

**Comment by ValentinaPC** [comment]
This ca be marked as verified fixed.
