### ISSUE TITLE
Reviewer Reply to Email Queries are Ignored

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#6311]
Reviewers get forwarded the email responses by the developers (i.e. from Reviewer reply).

It seems dealing with such enquires are no longer logged (Add-on Review Log) nor counted. The reviewer action is totally ignored.

While dealing with queries never had any point incentive, they were counted and taken into account in the past.

I am not sure if the new changes have been intended as such or whether it is a bug.

**Comment by eviljeff** [comment]
@wagnerand what do you think?

**Comment by wagnerand** [comment]
If I read this correctly, you're asking for reviewer replies to appear in the review log? 

Generally, I wouldn't be opposed to that, but I am not sure if it's worth the effort since the reviewer tools are going to go through some bigger changes soon.

Can you explain what the gain for reviewers would be to show them?

**Comment by erosman** [comment]
Previously, all these actions were counted and reflected in reviewer stats as well as logs.
**Approve
Reject
Reviewer reply
Request super-review
Comment**

Recently, **Reviewer reply** is ignored unless "Is more info requested?" is ticked.

Result is that, when developer emails with query, dealing with those queries (which doesn't require "Is more info requested?") is completely ignored by the logs and stats.

Should answering developer email be ignored? Is it ignorable?

**Comment by wagnerand** [comment]
Until recently, we haven't had "Reviewer replies". So, this is not a regression, we just didn't actively add them to the logs when we implemented them.

Can you explain what the gain for reviewers would be to show them?

**Comment by erosman** [comment]
> Can you explain what the gain for reviewers would be to show them?

I did in my previous post.... they are not counted as actions and not added to the stats, the same way, other actions are added to the stats.
They should count as "Reviewer reply" but they don't.

They should be reflected on the reviewer total and Weekly Add-on Reviews Report.

**Comment by wagnerand** [comment]
I'm trying to rephrase:

I'd like to understand why you'd like to get this added to the logs. Where do you see the benefit for reviewers?

For the stats, I agree that it's a bit inconsistent to to count information requests, but not replies. Generally I am not sure why we should count them at all, since they don't really complete a review cycle.

(The weekly add-on reviews report is generated manually, so you'd have to talk to @jvillalobos)

**Comment by jvillalobos** [comment]
Like Andreas pointed out, we plan to do a big redesign of the reviewer tools soon (hopefully in Q4), so it's not a good idea to tackle this now. We will take it into account when designing the new version.

**Comment by erosman** [comment]
> I'd like to understand why you'd like to get this added to the logs.
Not being added to "Add-on Review Log" was an observation, not a request.

Logging was a general reference for the action to be logged somewhere, i.e. counted (did not refer to  "Add-on Review Log" )

> For the stats, I agree that it's a bit inconsistent to to count information requests, but not replies. Generally I am not sure why we should count them (both information requests and replies) at all, since they don't really complete a review cycle.
Reviewers do not gain any incentive for them but it shows that their time and effort is COUNTED. In other words, it shows that Mozilla considers their efforts.

Info requests are often made after checking the addon and spending time on the review.
Replying to queries involves, reading emails, going to addon review and preparing a reply.
The process is similar to "Request super-review" and "Comment". It requires time and effort to be spent 

These actions do take and require time and effort by the reviewers.

Ignoring time and effort spent by the reviewers is not an encouragement of the reviewers.

> Like Andreas pointed out, we plan to do a big redesign of the reviewer tools soon (hopefully in Q4), so it's not a good idea to tackle this now. 
IMHO ...... Not fixing an issue that can have a bearing on morale, workplace satisfaction and enthusiasm could be seen as being taken for granted.
Ignoring and disregarding the work done by the people and not counting their time and effort could be seen as discouraging.

Please note that volunteer reviewers are not paid and being appreciated (and counted) is one of the main motivations for them.
