### ISSUE TITLE
Add tags for multiprocessCompatible and hasEmbeddedWebExtension

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#6313]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/tag/firefox57 will show _all_ WebExtensions

However, I tried to find:
* multiprocessCompatible
* hasEmbeddedWebExtension

### What happened?
I could not find the desired tags.

### What did you expect to happen?
I expected to find:

* multiprocessCompatible - I suggest that you start https://addons.mozilla.org/en-US/firefox/tag/multiprocess or https://addons.mozilla.org/en-US/firefox/tag/multiprocessCompatible
* hasEmbeddedWebExtension (aka hybrid WebExtension) -- I suggest that you start https://addons.mozilla.org/en-US/firefox/tag/hasEmbeddedWebExtension or 

### Anything else we should know?
The "multiprocessCompatible" and "hasEmbeddedWebExtension" keys are mandatory in install.rdf so it should be easy to make tags for them.

**Comment by diox** [comment]
Both will be almost irrelevant once Firefox 57 is released (yes, I know, ESR, but most users will be on 57), and are also way too technical to have any benefit for end-users.
