### ISSUE TITLE
Long reviews are deleted on AMO, without warning

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#6317]
### Describe the problem and steps to reproduce it:
Posted long reviews (to combat license issues):
https://addons.mozilla.org/en-US/firefox/addon/webrtc-control/reviews/914382/
https://addons.mozilla.org/en-US/firefox/addon/noflash/reviews/914401/
https://addons.mozilla.org/en-US/firefox/addon/dynamichistory/reviews/914375/
https://addons.mozilla.org/en-US/firefox/addon/wayback-machine_new/reviews/914416/
https://addons.mozilla.org/en-US/firefox/addon/bloody-vikings/reviews/914363/

I measured the file size of text in a stand alone document: 4.9 kb

### What happened?
They were deleted after 12 hours or so.

### What did you expect to happen?
That they should stay.

### Anything else we should know?
Please send a copy of the deleted reviews and say were they have been deleted, so I have a chance to send them to someone else. Some people don't provide any email or bug trackers so you have to send them the issue as a Review.

**Comment by diox** [comment]
This is not an issue with AMO code, so it has nothing to do here. You can use the [discourse forums](https://discourse.mozilla.org/c/add-ons) to discuss this further or maybe contact admins.

**Comment by davidhedlund** [comment]
@diox Submitted to https://discourse.mozilla.org/t/long-reviews-are-deleted-on-amo-without-warning/18817
