### ISSUE TITLE
Automatically insert a MPL LICENSE file

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#6318]
### Describe the problem and steps to reproduce it:
The most popular license on AMO is MPL 2.0.

### What happened?
Most of them do not ship with a LICENSE at all.

### What did you expect to happen?
* It would be convenient if you could suggest a automatic way to insert https://www.mozilla.org/media/MPL/2.0/index.txt into LICENSE when the authors upload new versions.
* Also, it would be very useful to verify if a LICENSE file exist in the API. Example: https://addons.mozilla.org/api/v3/addons/addon/popup-blocker/. Then we don't have to download add-ons, extract them, and look for LICENSE.

### Anything else we should know?
The Free Software Directory (https://directory.fsf.org/wiki/Free_Software_Directory:IceCat_WebExtensions_(proposed)) don't approve add-ons that are said to be distributed under MPL on AMO but doesn't ship with a copy of the license.

**Comment by davidhedlund** [comment]
Also, it would be very useful to verify if a LICENSE exist in the API. Example: https://addons.mozilla.org/api/v3/addons/addon/popup-blocker/

Then we don't have to download add-ons, extract them, and look for LICENSE.

**Comment by jvillalobos** [comment]
Automatically changing files in add-ons is error-prone, so we don't do it unless strictly necessary, which isn't the case here. 

Adding a linter warning about the LICENCE file if the add-on has one of the preset open source licenses could be useful, though. @wagnerand, @kewisch thoughts?

As for exposing the presence of the file in the API, I think that's too specific.

**Comment by diox** [comment]
> Adding a linter warning about the LICENCE file if the add-on has one of the preset open source licenses could be useful, though. @wagnerand, @kewisch thoughts?

It'd be nice, but the licence choice happens *after* validation in the submission flow (both for new submissions and updates) so the only warning we can add really is just a generic "Your add-on does not contain a LICENCE file" at validation time, without knowing what licence will be chosen later in the process.

**Comment by jvillalobos** [comment]
For updates we at least know what was chosen for the previous version, which will most likely remain the same for the new version. I'm not opposed to a generic notice, though, since most add-ons claim to be open-source.

**Comment by wagnerand** [comment]
I mostly agree with @jvillalobos although I don't believe it warrants a validation warning. We have to be careful to not overload developers with warnings, otherwise we risk that they start ignoring them.

https://developer.mozilla.org/en-US/Add-ons/Listing already mentions a license in general, we could add a note about including LICENSE files in the add-on.

**Comment by davidhedlund** [comment]
@wagnerand 
> https://developer.mozilla.org/en-US/Add-ons/Listing already mentions a license in general, we could add a note about including LICENSE files in the add-on.

Yes, that is a good idea. Can you add it?

**Comment by davidhedlund** [comment]
@wagnerand 
> https://developer.mozilla.org/en-US/Add-ons/Listing already mentions a license in general, we could add a note about including LICENSE files in the add-on.

The GPL licenses recommends a COPYING file.

**Comment by jvillalobos** [comment]
Okay, let's not bother with the validation warning now. Nothing left to do in code, then.

**Comment by davidhedlund** [comment]
Also, regarding https://github.com/mozilla/addons-server/issues/6318#issuecomment-327118201

> https://developer.mozilla.org/en-US/Add-ons/Listing already mentions a license in general, we could add a note about including LICENSE files in the add-on.

Can you please do that?

**Comment by jvillalobos** [comment]
> Again, I've been working hundreds of hours on IceCats add-on list and I'm tired of contacting the add-on owners each time.

I'm sorry you have to do that, but we need to balance various factors and decided this isn't worth doing. Adding too much messaging during the submission process makes developers less likely to pay attention to the most critical ones.

> Can you please do that?

It's a wiki, so anyone can do that. I'm pretty busy myself, so I can't help you with that.

**Comment by davidhedlund** [comment]
I would like Mozilla to add a license file to all 256 add-ons in https://addons.mozilla.org/en-US/firefox/user/mozilla/#my-submissions
