### ISSUE TITLE
Weight is not incremented for negative reviews

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6322]
Prerequisites:
- post-review waffle is enabled;

Steps to reproduce:
1. Submit a webetexnsion i.e. https://addons-dev.allizom.org/en-US/editors/review/negative-reviews-weight and wait to be auto approved
2. Add some negative reviews 
3. Add a second version for that webextension
4. Check the weight from Auto Approved queue for that webextension

Expected results:
Weight is incremented with "2" for each bad review (1, 2, or 3 stars) int he past year.

Actual results:
Weight is not incremented for negative ratings.

Notes/Issues:
- if the review was added before auto approve (with an admin account), the results are the same.
- I think this is happening because de bad reviews are recorded for the version that was previously auto-approved (at step 1) and not the next (step 3).
Verified on AMO-dev FF55(Win 7).

**Comment by diox** [comment]
That was originally the rule, but after discussion with product it turned out that I had misunderstood the intent and it was changed in https://github.com/mozilla/addons-server/pull/5584 to make "1 % of total number of reviews with score less than 3" correspond to a value of "2".

Said otherwise, it will take 100 bad reviews in a year to increment the weight by 2.

**Comment by ValentinaPC** [comment]
Oh, I see... could you somehow automatically add my webextension 100 bad reviews to see if this works? Because finding an add-on that already has so many bad reviews is a bit difficult.

**Comment by diox** [comment]
Done, there should now be 1 good review... and 101 bad (<= 3) on this add-on on dev.

**Comment by ValentinaPC** [comment]
Perfect! Things seem to work as expected.
Postfix screenshot for the webextension from above example(4x1 - ab reports + 100 bad reviews - 2 = 42):
![2017-09-04_1541](https://user-images.githubusercontent.com/15685960/30026890-7f54834c-9187-11e7-839a-558f5f6d9262.png)
