### ISSUE TITLE
Layout issues for "Files" section from Contents/Compare pages of an add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6323]
Steps to reproduce:
1. Submit a webextension and access its review page i.e. https://addons-dev.allizom.org/en-US/editors/review/webext-html-csp
2. Go to "Add-on history" section and click on Contents/Compare link
3. Observe the files listed in the left side of the page

Expected results:
A list of files from the .xpi are displayed together with an expand option if there are subfolders or files in folders.

Actual results:
The list of files and folders has layout issues in form of too much white padding.

Notes/Issues:
Verified on FF55(Win 7). Issue is only reproducing on -dev.
Video for this issue:
![expanded](https://user-images.githubusercontent.com/15685960/30052956-da6188f4-922f-11e7-96b2-bc91a814a8a4.gif)

**Comment by tsl143** [comment]
@ValentinaPC , I am not able to view this issue as I am unable to login at `https://addons-dev.allizom.org/en-US/editors/review/webext-html-csp`.
Can you point me where to request access for dev server ?

**Comment by ValentinaPC** [comment]
Can you access https://addons-dev.allizom.org/en-US/editors/ ?

**Comment by tsl143** [comment]
No, 
`Oops! Not allowed.`

**Comment by wagnerand** [comment]
@ValentinaPC Accessing the URL that is shown in the screencast (https://addons.mozilla.org/en-GB/firefox/files/browse/253576/) gives me a different add-on that the one shown.

Either way, I cannot reproduce:

<img width="506" alt="screen shot 2017-09-07 at 14 35 43" src="https://user-images.githubusercontent.com/873258/30163636-eece4286-93d9-11e7-9cd6-e9cf840a1a00.png">

Can you provide the URL where you see this?

**Comment by ValentinaPC** [comment]
See this: https://addons-dev.allizom.org/en-US/firefox/files/browse/253576/
Issue is only reproducing on -dev.

**Comment by wagnerand** [comment]
Ugh, this is on prod now. :(

**Comment by wagnerand** [comment]
Regression from 748878cf6f8fc5374ce311208c9f33b241c48b62.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev using FF55(Win 7).
Postfix screenshot:
![rev_tools](https://user-images.githubusercontent.com/15685960/30210329-df22cd68-94a4-11e7-9550-17f92db51f7b.png)
