### ISSUE TITLE
Calculate size of code changes in post-review, use it to assign a weight

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6330]
Part of #6033 but it's slightly bigger than just checking for a flag in the linter so it deserves its own issue.

The idea is, when approving a version, to calculate the size of code-related changes between the previously approved version and determine a post-review weight from it. 

For the weight value, the [post-review priorization weights doc](https://docs.google.com/spreadsheets/d/1CZEECHHqEmK87fNiWNslAsFQBL7zxYF-c63-zZVZuqw/edit#gid=0) suggests __one point per 5kB of code changes, up to a maximum of 100__.

**Comment by diox** [comment]
@jvillalobos if it's the first listed version... should we have 0 as the weight value for this factor or use the code size for this version only?

**Comment by jvillalobos** [comment]
For the first version we should use the entire code size.

**Comment by ValentinaPC** [comment]
@diox : I've submitted a webextension and after that a new version for that webextension smaller than the first. No changes to the weight for the second version auto-approval. And vice versa. Still nothing.

Both examples:
1. https://addons-dev.allizom.org/en-US/editors/review/webext-size-of-big
2. https://addons-dev.allizom.org/en-US/editors/review/size-of-code-changes-reversed

What am I doing wrong?
Thanks!

**Comment by diox** [comment]
Had not noticed your answer, sorry. It looks like the info that the linter is supposed to give us is missing somehow. Reopening to investigate.

**Comment by ValentinaPC** [comment]
Verified in AMO-dev FF55(Win 7).
- over 500kb code changes will increment weight with max value of 100
- under 500kb code changes should increment with 1 for each 5 kb changes.

Example: https://addons-dev.allizom.org/en-US/firefox/addon/size-of-code-scad/versions/
This should have:  368.4 KiB -  4.3 KiB =  364.1 Kib => 364.1 / 5 = 72.82 weight
I also have 4 abuse reports => 40
Total weight should be: 112 (113)
But the weight from reviewer Tools is 115.
@diox - Am I missing something?

**Comment by diox** [comment]
There is a problem, but not the one you think :)

The key thing to remember here is we are supposed to compare size of *code* changes, not size of the packages themselves. Artificially increasing the size by adding images should not have any impact on the weight.

In your first version, the size of code is 809 bytes. It would be the same in the second version since all you did was add an image but the linter seems to be considering binary files as well, we're going to change that.

**Comment by diox** [comment]
New linter version landed in https://github.com/mozilla/addons-server/commit/f15fc6dd6a262b0f9a51249bc226863d304f5778 and should now only consider code correctly, ignoring binary files.

**Comment by ValentinaPC** [comment]
> New linter version landed in f15fc6d and should now only consider code correctly, ignoring binary files.

Yeah, you are right. repeated the above scenario and the weight was not incremented.

**Comment by ValentinaPC** [comment]
Verified the weight while changing the code size using FF55(Win 7) in AMO-dev and:
Example: https://addons-dev.allizom.org/en-US/firefox/addon/mare/
Values: 29.6 KiB - 26.4 KiB = 3.2  which is under 5kb, nevertheless the weight is incremented with 1.
 :(
 Tried other examples also, and the values don't sum up as expected. :(

**Comment by diox** [comment]
You're comparing total file size again, not code size.
For this add-on:
Version 1 reported code size is 12813 bytes (.json files in _locales/ count)
Version 2 reported code size is 3626 bytes (a couple javascript files were removed from the first version)

The weight is incremented by 1 because we round the number down (12813-3626)/5000.

**Comment by ValentinaPC** [comment]
Yeah....I am a huge pain in ...

Verified AGAIN on AMO-dev FF55(Win 7).
Weight is incremented as expected for size code changes.
Marking as verified.
