### ISSUE TITLE
Remove built-in "Travelers Pack" collection

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6333]
requested by @devaneymoz.

**Comment by vcarciu** [comment]
@wagnerand  I am still able to find this collection at search even if it is empty : 
![traveler](https://user-images.githubusercontent.com/1583842/30167057-da0b3070-93ed-11e7-8bd9-06f05e887218.png)

Is this ok?

**Comment by wagnerand** [comment]
I believe this is ok. That patch just allows us to manually remove the collection. So what you can do to test this is try to delete that collection. It should work and not show an "Oops" page.

**Comment by vcarciu** [comment]
I dont think that I can do that in production. Not sure if deleting it on -dev will correctly verify the issue. Please let me know how to proceed.

**Comment by wagnerand** [comment]
You can't do it on production since the code hasn't landed in production (yet). You can try on -dev if you' like to. Otherwise we can just ignore this and I will try to delete the collection on prod later today.

**Comment by vcarciu** [comment]
@wagnerand , ok , thanks it is not on -dev so just delete it and I will mark it as verified tomorrow.

**Comment by wagnerand** [comment]
I still can't delete it. Talked to @devaneymoz and we're ok to keep it for now since the collection is empty unused. It's not worth the effort.

**Comment by wagnerand** [comment]
This is finally gone.
