### ISSUE TITLE
Layout issue in collections pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6341]
Steps to reproduce:
1. Load Collections page  https://addons.allizom.org/en-US/firefox/collections/
2. Make a search

Expected results:
A list of collections are listed. There are no display or layout issues.

Actual results:
There is a white space between collection's details.

Notes/Issues:
- issue is reproducing also in Collections I've Made, Collections I'm Following, My Favorite Add-ons, or any collection details page.
Verified on FF55(Win 7). Issue is reproducing on both stage and dev.
Screenshots for this issue:
![white](https://user-images.githubusercontent.com/15685960/30106654-da1b5fb6-9304-11e7-9e20-3003de78916a.png)
![2017-09-06_1312](https://user-images.githubusercontent.com/15685960/30106737-1d9dc45e-9305-11e7-8eba-85e48949c14a.png)

**Comment by tsl143** [comment]
This might be Fixed if https://github.com/mozilla/addons-server/pull/6344 gets merged.
These both issues are caused by same CSS rule.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (Win 7).
Postfix screenshots:
![1](https://user-images.githubusercontent.com/15685960/30148263-45090f3e-93ab-11e7-8d5c-5dea7cc11679.png)
![2](https://user-images.githubusercontent.com/15685960/30148264-450c8d80-93ab-11e7-80e7-23a7e980eded.png)
