### ISSUE TITLE
Broken layout in theme details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6342]
Steps to reproduce:
1. Load any theme details page i.e. https://addons.allizom.org/en-US/firefox/addon/horse-on-the-beach-jen/

Expected results:
There are no display or layout issues.

Actual results:
There is a layout issue in the upper side of theme details page.

Notes/Issues:
- issue is seen better for themes with no summary.
Verified in FF55(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue:
![theme](https://user-images.githubusercontent.com/15685960/30109074-9cd10bb6-930d-11e7-8bf7-b5393b492b7e.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix screenshot:
![t](https://user-images.githubusercontent.com/15685960/30148043-515aa19a-93aa-11e7-88ee-a01dcc213c4f.png)

**Comment by diox** [comment]
Re-opening because the fix caused more issues. It's related to 748878c which caused other issues (#6356 and #6323) that we're going to tackle by making the rules more specific.

**Comment by muffinresearch** [comment]
Patch reverted in https://github.com/mozilla/addons-server/commit/8dd0a94eb54faf18607843d31de70a7e32e48419

**Comment by ValentinaPC** [comment]
@diox : The other one was also logged, and fixed on dev, yesterday.
Please see: https://github.com/mozilla/addons-server/issues/6341

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
The white gap is off, but the lines are still broken.
Please see screenshot:
![theme](https://user-images.githubusercontent.com/15685960/30210471-74331854-94a5-11e7-8d80-f18cf9acfd1d.png)

**Comment by ValentinaPC** [comment]
Cleared cache - all good.
Postfix screenshot from AMO-dev using FF55(Win 7)
![2017-09-08_1457](https://user-images.githubusercontent.com/15685960/30210662-12233e2c-94a6-11e7-8510-55cdef27e0ed.png)
