### ISSUE TITLE
Compatible Language Pack shown as incompatible

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6343]
Steps to reproduce:
1. Submit a language pack with `maxversion 57.0a1` i.e. https://addons.allizom.org/en-US/developers/addon/lp-test/versions/1703633 and approve it
2. Go to its details page using FF57.0a1 and observe installation button

Expected results:
Install button is green and active.

Actual results:
Install button is grey and inactive.

Notes/Issues:
- same happens for 57.0a2
Verified on AMO-stage FF57.0a1(Win 7). reproducing on -dev also.
![2](https://user-images.githubusercontent.com/15685960/30111885-15a101fe-9318-11e7-837a-608298cfcce8.png)
![3](https://user-images.githubusercontent.com/15685960/30111886-15ce77ba-9318-11e7-857b-7e0343af40a0.png)

**Comment by wagnerand** [comment]
I find it a bit weird that language packs can be compatible to more than one version.

**Comment by diox** [comment]
I don't think this is specific to langpacks or a new issue. Nightly reports "57.0" (full UA string is "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0") so as far as AMO is concerned, it's 57.0, not 57.0a1 (which is lower), so it marks the add-on as incompatible.

It's just a bad idea to use alpha versions in max versions...

**Comment by ValentinaPC** [comment]
I just wanted to install a lang pack using latest Nightly....and couldn't .

**Comment by diox** [comment]
Well langpacks are not uploaded by regular means anyway: they are generated from mozilla-central, and that happens by a task triggered by admins when the packs are ready... which is generally after each release.

But if it's just to test langpack installs in general, just set 57.0 instead of 57.0a1 in the compatibility in devhub.

**Comment by wagnerand** [comment]
For the record, I think anyone can upload new langpack add-ons (and I believe some are, as they're not on ftp).

**Comment by diox** [comment]
True, we don't disallow langpack uploads. I thought that nobody did that though, but I guess it's possible for some languages people might submit ones themselves.

**Comment by ValentinaPC** [comment]
> But if it's just to test langpack installs in general, just set 57.0 instead of 57.0a1 in the compatibility in devhub.

I was able to test install as you suggested.

**Comment by diox** [comment]
Closing per your last comment - there is nothing we can do about Nightly detection.
