### ISSUE TITLE
Add authors' `username` to the Add-on detail response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6346]
Hi,

In order to use the `author` query parameter on the [search API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search), I need the `username` of the different authors of an add-on. It is exposed _via_ the Accounts API but it would be simpler to have such a field in the `authors` set part of the [Add-on detail response](https://addons-server.readthedocs.io/en/latest/topics/api/internal.html#addon-detail-object).

This set only have the `id`, `name` and `url` of each author. Having the `username` would be great to avoid extra requests to the API.

(I am working on the "More add-ons by authors" feature on the frontend).

Thanks!

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
