### ISSUE TITLE
Broken layout for Collections

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#6356]
https://addons.mozilla.org/en-US/firefox/collections/DavidHedlund/

![screenshot from 2017-09-07 19 28 28](https://user-images.githubusercontent.com/6416073/30176474-d8bef8ae-9402-11e7-97cf-c01f1b6633be.png)

As you can see there's to much space between the rows.

**Comment by wagnerand** [comment]
Related to https://github.com/mozilla/addons-server/issues/6323

**Comment by davidhedlund** [comment]
This bug is also seen when I visit my collections.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix screenshot:
![coll](https://user-images.githubusercontent.com/15685960/30210738-5eea46e2-94a6-11e7-985d-c28b8937c695.png)

Everything looks good in Collections I'm Following and Collections I've Made pages.
