### ISSUE TITLE
The 2017-09-07 L10n extract didn't update the templates folder

### ISSUE THREAD

**Issue by mathjazz** [mozilla/addons-server#6357]
The [latest l10n extract](https://github.com/mozilla/addons-server/commit/48a8a950c18f45504cabc3bb10c3a4024978da09) didn't update the `templates` folder, which is used by Pontoon to get source strings from.

Please coordinate with me before pushing the changes, because it will likely require an intervention from my side in Pontoon.

**Comment by EnTeQuAk** [comment]
Fixed in recent pull request
