### ISSUE TITLE
queue position reset if a revision is canceled

### ISSUE THREAD

**Issue by plujon** [mozilla/addons-server#6359]
### Describe the problem and steps to reproduce it:

I use tab-count-badge as an example in the following scenario.  But the problem does not reproduce with tab-count-badge because tab-count-badge is automatically approved by mozilla (apparently).  However, if tab-count-badge were flagged for administrative review, it would sit in the queue longer, reproducing the issue (see critical step 6 below).

1. https://addons.mozilla.org/en-US/developers/addon/tab-count-badge

2. Click "Upload New Version" (https://addons.mozilla.org/en-US/developers/addon/tab-count-badge/versions/submit/)

3. Select a file... (browse to tabcountbadge.xpi)

4. Click "Continue"

5. Add release notes on https://addons.mozilla.org/en-US/developers/addon/tab-count-badge/versions/submit/2175572/details and then click "Submit Version for Review".  This will be "version 2".

6. Wait some time (e.g., 2 weeks) and gain queue position.

7. https://addons.mozilla.org/en-US/developers/addon/tab-count-badge

8. Click "Upload New Version" (https://addons.mozilla.org/en-US/developers/addon/tab-count-badge/versions/submit/)

9. Upload version 3 of tabcountbadge.xpi.

10. Click Continue.

11. Click "Cancel Review and Disable Version" (imagine it was at this stage that you realized version 3 had a problem that you wanted to fix before allowing users to use it).

12. Behold, version 2 is no longer awaiting review.  If a new version (fixed version 4) is uploaded, the queue position for version 4 is the now maximum value.

### What happened?

Queue position was reset after canceling a new version.

### What did you expect to happen?

I expected the queue position and review status for version 2 to be retained after I clicked "cancel review and disable version".  If the button said, "cancel all pending reviews for this addon and disable unreviewed versions," I would not have been surprised by what happened.

### Anything else we should know?

This is probably only an issue for folks like myself who wait in the review queue for multiple weeks.  If I had known the queue position would be reset, I would not have clicked "cancel review and disable version".  Instead, I would have just uploaded another version (fixed version 4) immediately after uploading problematic version 3.

**Comment by eviljeff** [comment]
@jvillalobos @wagnerand thoughts?

**Comment by wagnerand** [comment]
We could potentially fix this by disabling the previous version only after the developer clicked the "submit for review" button, but then this is also quite the edge case, and won't be much of an issue with post-review either, so 🤷‍♂️.

**Comment by jvillalobos** [comment]
Agree, not really worth the effort now.
