### ISSUE TITLE
Update the language pack import tool to support WebExtensions packages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6360]
Part of #6297.

The [language pack admin tool](https://addons-internal.prod.mozaws.net/admin/langpacks) is used to import language packs from the Firefox build directories and update their AMO listings. We need to determine if there's anything that needs to change for this tool when language packs start using WebExtensions packaging.

**Comment by diox** [comment]
I took a quick look and I think it's going to be OK once #6350 is implemented - [the task that does this](https://github.com/mozilla/addons-server/blob/3a4622b3d1f4518e5f78c2f967683c0b75e1b71a/src/olympia/zadmin/tasks.py#L236) uses `parse_addon()` and `from_upload()` as normal, so it should just work once `parse_addon()` knows how to deal with webextension langpacks.

**Comment by diox** [comment]
Will need to wait for #6350 to test

**Comment by ValentinaPC** [comment]
The [language pack admin tool](https://addons-internal.prod.mozaws.net/admin/langpacks) page is not working, could you please give a hand, Mat?

**Comment by diox** [comment]
What do you mean not working? @jvillalobos successfully used it to fetch the language packs for Firefox 56 in https://github.com/mozilla/addons-server/issues/6543

**Comment by ValentinaPC** [comment]
I mean that accessing the page - https://addons-internal.prod.mozaws.net/admin/langpacks - while having the VPN active, I get no results.

Updated:
I figure it out....it is because I was trying the -prod site, where i don'e have rights. -dev is working.
Sorry for the noise.
