### ISSUE TITLE
Add-on with "firefox57" tag but no "Compatible with Firefox 57+" label

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#6365]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/ has tag "firefox57" but there's no "Compatible with Firefox 57+" label on top of the page.

### What happened?
I have no idea. Is FoxyProxy Standard as WebExtension or not?

### What did you expect to happen?
If  FoxyProxy Standard is not a WebExtension then the "firefox57" tag should be removed, otherwise ( a "Compatible with Firefox 57+" label should be added.

### Anything else we should know?
Try to find out what triggered this add-on to get wrong tag/label and see if it apply to other add-ons as well.

**Comment by diox** [comment]
This is a known limitation of the tag, there was a 5.0 version that was compatible with Firefox 57 but it was disabled and the tag hasn't been updated.

**Comment by davidhedlund** [comment]
https://github.com/mozilla/addons-server/issues/8579
