### ISSUE TITLE
"Compatible with Firefox 57+" list API

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#6366]
Is there any API that can be used to list all add-ons in https://addons.mozilla.org/en-US/firefox/search/?tag=firefox57 instead of crawling it with wget for example?

**Comment by diox** [comment]
See http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search

**Comment by davidhedlund** [comment]
@diox https://addons.mozilla.org/api/v3/addons/search/?tag=firefox57 didn't work for me

I only want
* guid
* Add-on name
* Add-on AMO URL

I would be glad if you could help me.

**Comment by diox** [comment]
It's a JSON API, just ignore the fields you don't care about? We're not going to build an API for each and every specific individual need...

**Comment by davidhedlund** [comment]
@diox Yes, I can use jq to filter them out. Thanks.

**Comment by davidhedlund** [comment]
To get the add-on ID's I used:

> cat search.json | jq '.results[] | .id'
