### ISSUE TITLE
Auto Approved Add-ons page returns a 500 error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6368]
Prerequisites:
- user has `Addons:PostReview` permission

Steps to reproduce:
1. Load Auto-Approved Add-ons queue from Reviewer Tools i.e. https://addons-dev.allizom.org/en-US/editors/queue/auto_approved

Expected results:
List of auto-approved add-ons is displayed.

Actual results:
An "Oops..." page is displayed.

Notes/Issues:
- only reproducing on -dev.
Verified on FF55(Win 7).
Video for this issue:
![auto app](https://user-images.githubusercontent.com/15685960/30211590-5bf1ec5c-94aa-11e7-8816-59284484dd4b.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/646855/

Regression from https://github.com/mozilla/addons-server/issues/6103 when the `post-review` waffle is enabled. It's a tricky one, the queryset in the `_queue()` function is either a real queryset or a fake one from `sql_model`, so we need to be extra careful about what we filter it with...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix screenshot:
![auto-approve-queue](https://user-images.githubusercontent.com/15685960/30272251-466bdf42-96fc-11e7-9c71-9b4546f9376d.png)
