### ISSUE TITLE
Document how to access recommendation engine in Discovery endpoint

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6370]
The API docs for the [discovery endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html) need to explain how to retrieve recommendation engine results (https://github.com/mozilla/addons-server/issues/5943).

**Comment by eviljeff** [comment]
I didn't know how secret/closed the trial was, so how much we should document on the api docs, but sure, can do.

**Comment by kumar303** [comment]
Document all the things! :) It's too cumbersome to try and dig through code to figure out how things work. We can always put disclaimers in the docs if needed.
