### ISSUE TITLE
"Search unavailable" message displayed when going to last page after a blank search

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6372]
Steps to reproduce:
1.On AMO-dev, perform a blank search (https://addons-dev.allizom.org/en-US/firefox/search/?q=&appver=&platform=windows)
2.Go to the last page 

Expected results:
Last page with results is correctly displayed

Actual results:
"Search unavailable" message displayed

NOTES:
Was able to reproduce also in prod for : 
https://addons.mozilla.org/en-Us/firefox/search/?page=1251&cat=collections
https://addons.mozilla.org/en-US/firefox/search/?page=1191&cat=themes

Please see video for this bug : 
![searchunavailable](https://user-images.githubusercontent.com/1583842/30218737-80fecc00-94c2-11e7-9622-e219b0d95dd0.gif)

**Comment by eviljeff** [comment]
Might be a dupe to #6053

**Comment by diox** [comment]
Looks like the same thing, yes.
