### ISSUE TITLE
Indicate in API response when add-ons are recommended 

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6373]
There's no way to tell from an API response of add-ons if each add-on has been recommended or not (recommendations were added in https://github.com/mozilla/addons-server/issues/5943). Could we add a new field to the `addon` object for this? I suggest something like `is_recommendation`. 

We don't have a specific need for this but I think it will help for collecting future stats on conversion rates. In other words, a question we may need to ask is "did the user install this add-on because it was recommended?"

I am suggesting to add this field on `addon` and not the Discovery result because the recommendation engine may ultimately wind up on AMO.

**Comment by diox** [comment]
> I am suggesting to add this field on addon and not the Discovery result because the recommendation engine may ultimately wind up on AMO.

Recommendations are (or rather, can be) user-specific though, they depend on the client telemetry id being passed.

Plus, we don't want to call the recommendation server when serving the various endpoints that can return add-on objects...

**Comment by kumar303** [comment]
As I understand it, the Discovery endpoint will serve the user a mix of add-ons, some which were from the recommendation engine and some that were from the normal, curated Discovery list. I think we need a way to know if the add-on was from the recommendation engine or not so that we can track the effectiveness of recommending add-ons to users.

**Comment by diox** [comment]
I agree about the need to differentiate between recommendations and the curated content; my point was just that it shouldn't (and couldn't easily) be applied to other endpoints than the discovery one, and so perhaps that the additional property didn't make much sense in `addon`.

**Comment by kumar303** [comment]
> it shouldn't (and couldn't easily) be applied to other endpoints than the discovery one

Can't it just be hard coded to false?

I think the next experiment will be adding this to AMO, probably a box on the page that's like 'other recommended add-ons'. I just thought it would keep things consistent. 

However, if it's easier to start with the discovery endpoint then we can always adjust this later if needed. I honestly don't know if we even need `is_recommendation` but I can't think of any other way we'd be able to track conversions properly (if we wanted to).

**Comment by eviljeff** [comment]
Adding it to just the discovery endpoint results would be a lot more straightforward - we already pass other data in addition to the addon serialization.

However, _is_ there a request to track installs?  I agree it would be nice data.  But if no-one has asked for it, is anyone going to look at it? Seems like a question for the taar people.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
