### ISSUE TITLE
Alternative recommendations doesn't give result expected for "NoSquint"

### ISSUE THREAD

**Issue by shell1** [mozilla/addons-server#6374]
I installed "NoSquint" on Fx 55.  Closed Fx 55 and Launched Nightly 57.  NoSquint showed in my list of Legacy add-ons.  Clicked on "Find a Replacement"

I was brought to a generic screen with collection results (see attachment)

I expected the direct suggestion of Zoom Page WE.  Verified with Scott Devaney that NoSquint should have had that direct suggestion.

<img width="564" alt="screen shot 2017-09-08 at 9 05 42 am" src="https://user-images.githubusercontent.com/8192232/30224729-b92c0cb6-9484-11e7-938c-0c222aec75f5.png">

**Comment by shell1** [comment]
Sorry - more details.  Tried "Zoom Page" Legacy add-on and the "Find a Replacement" tool, went right to Zoom Page WE like expected.

Tree Style Tabs worked fine as well.  so it seems specific to "NoSquint" @devaneymox

**Comment by jvillalobos** [comment]
This is working for me: http://addons.mozilla.org/find-replacement/?guid=nosquint@urandom.ca

Note that there's a "NoSquint" and a "NoSquint Plus".

**Comment by shell1** [comment]
Thanks Jorge - you are right.  I see that difference and will close out bug.

Cheers,
Shell

Engineering Program Manager
IRC: Shell

**Comment by shell1** [comment]
Jorge pointer out that I was using NoSquint Plus.. not NoSquint.  closing out.  It works
