### ISSUE TITLE
Source code: change button does not actually change the source code

### ISSUE THREAD

**Issue by plujon** [mozilla/addons-server#6375]
### What happened?
A reviewer pointed out that I neglected to include a file in the amo.zip (source code) file that I uploaded to https://addons.mozilla.org/en-US/developers/addon/plucki/versions/2166864 .  The original amo.zip was 247044 bytes.

So, I created a new amo.zip that was 247689 bytes.

I attempted to upload the new version by clicking the "browse" button next to Change: in the Source Code section of the web form.

A successful result was returned from the server, and I was redirected to the same page.

I then attempted to confirm that the new amo.zip contained the missing file by clicking "view current".  After clicking "view current", I had a 247044 byte plucki-10.17.0-src.zip, the same as the original source upload, and not the modified version that I expected.

### What did you expect to happen?

I expected the downloaded zip file to be the one I most recently uploaded, with 247689 glorious bytes.

### Anything else we should know?

The Network panel indicated the response was cached (transferred: cached).  The resonse headers were:

Accept-Ranges: bytes
Content-Disposition: attachment; filename="plucki-10.17.0-src.zip"
Content-Type: application/octet-stream
Date: Fri, 08 Sep 2017 16:47:21 GMT
Last-Modified: Sat, 26 Aug 2017 00:26:52 GMT
Server: nginx
x-backend-server: ip-172-31-12-244
Content-Length: 247044

I conducted this test at about Fri, 08 Sep 2017 22:25:00 GMT

**Comment by plujon** [comment]
![source-code-form](https://user-images.githubusercontent.com/8648864/30233319-ae6fb582-94a9-11e7-8af0-337c06b2db86.png)

**Comment by jvillalobos** [comment]
The one I see now is 247689 bytes, so it sounds like it's just server caching and not that the file isn't being correctly replaced. Not sure if this is a case we should be concerned about.

**Comment by diox** [comment]
Closing per previous comment
