### ISSUE TITLE
Add exclusion field on Search API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6376]
Hi, the addons-frontend has to display a set of related add-ons made by any of the authors on a add-on detail page (see: https://github.com/mozilla/addons-frontend/pull/3027 and https://github.com/mozilla/addons-frontend/pull/3083). It would be unfortunate to have the add-on of the detail page also listed in the "other add-ons by these authors". I do the filtering on the client side right now, but it will not play nice with pagination and I think we will need such filters sooner or later.

Would it be possible to add exclusion filters to the [Search API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search)?

Specifically, having a `exclude_addon_ids` or `exclude_addon_slugs` query parameter would be handy. These fields should allow comma-separated values to exclude multiple add-ons at once. Feel free to come up with a better name.

Thanks!

**Comment by eviljeff** [comment]
`exclude_addons` and have it handle both slugs and ids :)

**Comment by diox** [comment]
I've got a working patch locally but I need to land #6396 first to get exclusions on slugs working.
