### ISSUE TITLE
Don't show reviews of disabled/deleted/removed add-ons in reviews api

### ISSUE THREAD

**Issue by ghost** [mozilla/addons-server#6378]
### Describe the problem and steps to reproduce it:
Deleting/removing reviews of disabled/deleted/removed add-ons is impossible.

### What happened?
This warning error message:

"We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

If you typed in the address, please double check the spelling.
If you followed a link from somewhere, please let us know at webmaster@mozilla.com. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

Are you interested in a list of featured add-ons?
Do you want to search for add-ons? You may go to the search page or just use the search field above.
If you prefer to start over, just go to the add-ons front page.".

### What did you expect to happen?
Review have to be deleted/removed.

### Anything else we should know?
No.

**Comment by eviljeff** [comment]
Why do you want/need to delete a review for an add-on that isn't available anymore?

**Comment by Anonymous123456789012** [comment]
Because:
-I don't want to see it on my profile
-I don't want others to see it on my profile
-I would like to be able to delete it, like other reviews
-Why should I not to?
-etc.

**Comment by eviljeff** [comment]
@jvillalobos do we want reviews for deleted/disabled addons visible on the profile page?

**Comment by jvillalobos** [comment]
No, I think hiding them is the way to go. Additionally, only developers will have public profiles in the future, so this issue becomes much smaller.

**Comment by eviljeff** [comment]
@jvillalobos does this need to be addressed before profile pages are served by addons-frontend?

**Comment by jvillalobos** [comment]
No, it's not a blocker.

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/5266
