### ISSUE TITLE
Downlad Anyway link is not shown in Seamonkey

### ISSUE THREAD

**Issue by milupo** [mozilla/addons-server#6381]
Hi,

until lately, there was a Download Anyway link on an add-on page to enable downloading an add-on with another program than Firefox, e.g. with SeaMonkey. Why doesn't it exist anymore? 

Michael

**Comment by diox** [comment]
It still does. Can you link an add-on where it's now showing, and what browser you are using?

**Comment by milupo** [comment]
No, the issue is that the link is **not** shown, not that it is **now** shown. I tested e.g. Adblock Plus, Video Download Helper, New Tab Override in Seamonkey:

- https://addons.mozilla.org/de/firefox/addon/adblock-plus/
- https://addons.mozilla.org/de/firefox/addon/video-downloadhelper/
- https://addons.mozilla.org/de/firefox/addon/new-tab-override/

**Comment by milupo** [comment]
Maybe it's a CSS issue. The code for this link exists in the source code:

`<span class="download-anyway "> | <a href="/firefox/downloads/latest/noscript/type:attachment/addon-722-latest.xpi?src=hp-dl-mostpopular" download>Trotzdem herunterladen</a></span>`

**Comment by diox** [comment]
It was a typo in my comment, it's definitely supposed to be shown. It's working fine for me in Firefox so I suppose we just broke it for Seamonkey.

It's not just a CSS issue, there is some JavaScript to show the right button/link (because it depends on the client platform).

**Comment by milupo** [comment]
Well, I think that this link is not required for Firefox but just for Seamonkey and other browsers.

**Comment by milupo** [comment]
It's because I often us Seamonkey but translate add-ons into Sorbian languages and German. Therefore I have to download them.

**Comment by diox** [comment]
It's required for Firefox depending on the Firefox versions the add-on is compatible with, or simply if the add-on is entirely incompatible with Firefox.

**Comment by milupo** [comment]
Well, I count on you. :-)

**Comment by milupo** [comment]
It works in Firefox when I open a SM add-on in Firefox, e.g. the SM version of Adblock Plus. But in Seamonkey it doesn't work withe Firefox version of ABP.

**Comment by muffinresearch** [comment]
Closing this since it won't be fixed in this repo as SeaMonkey and Thunderbird are moving to a separate system. The bug may exist there too but it will need to be re-checked once it's available.
