### ISSUE TITLE
Typo in extracted l10n string

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#6383]
@TonnesM reported a possible typo in a recent l10n string extraction:

https://github.com/mozilla/addons-server/pull/6319/files#diff-e444d2da49b8f22dca0f0769be400631R138 
"URL domain must be one of [%s], or a subdomain., " 

Notice the sentence ends with a period and a comma.

@EnTeQuAk could you confirm?

**Comment by diox** [comment]
Very weird. The code with the `ugettext` call is:

```python
              raise forms.ValidationError(ugettext(
                   'URL domain must be one of [%s], or a subdomain.' %
                   ', '.join(amo.VALID_CONTRIBUTION_DOMAINS)))
```

Yet somehow in the `.po` files we end up with:
```
msgid "URL domain must be one of [%s], or a subdomain., "
```

**Comment by EnTeQuAk** [comment]
This is indeed interesting, I don't see anything wrong with it yet. I'll take a closer look at it though.

**Comment by eviljeff** [comment]
Ah... is it because the ` % ', '.join(amo.VALID_CONTRIBUTION_DOMAINS)` is also inside the ugettext?  So the `', '` is getting tacked onto the string? Although I'm not sure how else I should have written it.

**Comment by diox** [comment]
Yeah, probably. Maybe just having a variable with the result of `', '.join(amo.VALID_CONTRIBUTION_DOMAINS)` would be enough to avoid that?

**Comment by EnTeQuAk** [comment]
indeed, the formatting should be outside of the ugettext. I am making that mistake regularly
