### ISSUE TITLE
Create redirects for Thunderbird and SeaMonkey clients

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6390]
This is part of the project to move Thunderbird and SeaMonkey add-ons to a separate site ([PRD](https://docs.google.com/document/d/1FIu9Wh18rsgeZibYCOcX2H13ZeSQTgVS3PUn1GrRFAU/edit#)). For the following requests:

* Discovery pane.
* Add-on updates.
* Add-on metadata ping.

We need to detect when SeaMonkey or Thunderbird clients are making the request, and do a redirect to the same URL in addons.thunderbird.net. This all needs to be waffled off in production until the planned deployment date in November.

**Comment by jvillalobos** [comment]
We need logging for these redirects so we can track their performance and potentially remove them in the future.

**Comment by diox** [comment]
Because it receives a huge amount of traffic, the add-on updates service is written in a very specific way to only do a minimum amount of very fast queries. It might be tricky to integrate a waffle in that service without impacting its performance.

**Comment by muffinresearch** [comment]
Would be good to ask jason about this, I'm thinking this might be something better done by ops under nginx.

**Comment by bqbn** [comment]
I think that if we know the full list of endpoints that are for either thunderbird or seamonkey, we should be able to tell if it is feasible to do all the redirects on the Nginx layer.

Currently and to my best knowledge, the URLs with the following two prefixes are for thunderbird and seamonkey only.

* ```/<locale>/thunderbird/...```
* ```/<locale>/seamonkey/...```

For these two, it should be easy for Nginx to do the redirects.

Are there more, or they're the only two?

**Comment by diox** [comment]
versioncheck (the add-on updates mechanism) URLs are definitely different from that.

The URL scheme is the same for Firefox, Thunderbird and Seamonkey, the parameters passed change though.

It looks like `https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%`

Note the `appID=%APP_ID%` parameter. For thunderbird, it should be `{3550f703-e582-4d05-9a08-453d09bdfdc6}`. So you'd need to match on `/VersionCheck.php` with  `appID={3550f703-e582-4d05-9a08-453d09bdfdc6}` (if you want to include the domain in the rule, there are 2 of them: `versioncheck.addons.mozilla.org` and `versioncheck-bg.addons.mozilla.org`.

**Comment by bqbn** [comment]
Nginx should be able to do the redirects for the above mentioned three URLs. We probably have to wait until the addons.thunderbird.net is set up in order to test the redirects though. Meanwhile, I suggest we lower the priority of this ticket for now.

**Comment by jvillalobos** [comment]
@Sancus, please update this issue once the server is up, so we can start working on this again.

**Comment by Sancus** [comment]
Will do.

**Comment by jvillalobos** [comment]
We met today to discuss progress, and the current plan is to enable these redirects on the week of June 18th. Given the coming Work Week, I'm bumping this back up to P2.

**Comment by bqbn** [comment]
So based on the comments so far,  the to-be-redirected URLs are:

1. `/<locale>/thunderbird/...`
2. `/<locale>/seamonkey/...`
3. `/update/VersionCheck.php` with `appID={3550f703-e582-4d05-9a08-453d09bdfdc6}` for `versioncheck.addons.mozilla.org` and `versioncheck-bg.addons.mozilla.org` domains.

Where should they be redirected to?

**Comment by Sancus** [comment]
1. https://addons.thunderbird.net/<locale>/thunderbird/...
2. https://addons.thunderbird.net/<locale>/seamonkey/...
3. https://versioncheck.addons.thunderbird.net and https://versioncheck-bg.addons.thunderbird.net respectively.

**Comment by Sancus** [comment]
There are some other URLs I've pulled from the client. Not sure how feasible some of these are to rewrite though. We can and will, of course, change URLs in the client but it'd be best to avoid breaking old versions if possible.

1. `https://services.addons.mozilla.org/%LOCALE%/%APP%/*` (used for the discovery pane and a couple other things)
2. `https://services.addons.mozilla.org/api/v3/addons/search/?guid=%IDS%&lang=%LOCALE%`
3. `https://services.addons.mozilla.org/api/v3/addons/compat-override/?guid=%IDS%&lang=%LOCALE%`
These should all redirect to `https://services.addons.thunderbird.net`.

**Comment by diox** [comment]
> 2. `https://services.addons.mozilla.org/api/v3/addons/search/?guid=%IDS%&lang=%LOCALE%`
> 3. `https://services.addons.mozilla.org/api/v3/addons/compat-override/?guid=%IDS%&lang=%LOCALE%`

Firefox uses those as well, so they can't be blindly be redirected.

**Comment by Sancus** [comment]
OK so the v3 URLs were newly added and do not yet exist in any release version of Thunderbird. I am working on a client patch now to change these to point at live.thunderbird.net, which will redirect to the correct place. So we won't have to worry about server-side redirects for these on AMO. 

Thus the final list of things that will need rewrites is:

1. `https://addons.mozilla.org/<locale>/thunderbird/...` -> `https://addons.thunderbird.net/<locale>/thunderbird/...`
2. `https://addons.mozilla.org/<locale>/seamonkey/...` -> `https://addons.thunderbird.net/<locale>/seamonkey/...`
3. `/update/VersionCheck.php` with `appID={3550f703-e582-4d05-9a08-453d09bdfdc6}` for `versioncheck.addons.mozilla.org` and `versioncheck-bg.addons.mozilla.org` -> `https://versioncheck.addons.thunderbird.net` and `https://versioncheck-bg.addons.thunderbird.net`
4. `https://services.addons.mozilla.org/%LOCALE%/%APP%/*` -> `https://services.addons.thunderbird.net/%LOCALE/%APP/*` where `%APP = thunderbird or seamonkey`.

**Comment by bqbn** [comment]
Question: do we need to match the appID for seamonkey? or is it that `3550f703-e582-4d05-9a08-453d09bdfdc6` is the appID for both thunderbird and seamonkey?

**Comment by jvillalobos** [comment]
SeaMonkey uses `{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}`, Thunderbird uses `{3550f703-e582-4d05-9a08-453d09bdfdc6}`

**Comment by Sancus** [comment]
Thanks, yes I had just copy pasted from above... edited my comment to add the Seamonkey appID as well.

**Comment by bqbn** [comment]
The redirection rules are deployed to -dev environment. Please test.

**Comment by diox** [comment]
@Sancus can you confirm whether the redirect work for you on dev?

**Comment by Sancus** [comment]
I tested 1,2&4 on addons.allizom.org and they seem to work as expected, but I don't know what the domain is for versioncheck. `https://versioncheck.addons.allizom.org` doesn't work?

**Comment by kewisch** [comment]
@Sancus it is https://versioncheck.allizom.org/ for stage and https://versioncheck-dev.allizom.org/ for dev.

**Comment by Sancus** [comment]
@diox It seems to me that the versioncheck redirects don't work on dev. Here is the URL I was using to test: `https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=2&id={3ed8cc52-86fc-4613-9026-c1ef969da4c3}&version=3.2.4&maxAppVersion=60.*&status=userEnabled&appID={3550f703-e582-4d05-9a08-453d09bdfdc6}&appVersion=45.0&appOS=WINNT&appABI=x86-msvc&locale=en-US&currentAppVersion=52.9.0&updateType=97&compatMode=strict`

The appID is for TB so it should go directly to thunderbird.net.

**Comment by diox** [comment]
@bqbn ^

**Comment by bqbn** [comment]
Maybe I missed the question, but I see the URL in https://github.com/mozilla/addons-server/issues/6390#issuecomment-402821821 got 301 to thunderbird.net.

```
$ curl -I "https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=2&id={3ed8cc52-86fc-4613-9026-c1ef969da4c3}&version=3.2.4&maxAppVersion=60.*&status=userEnabled&appID={3550f703-e582-4d05-9a08-453d09bdfdc6}&appVersion=45.0&appOS=WINNT&appABI=x86-msvc&locale=en-US&currentAppVersion=52.9.0&updateType=97&compatMode=strict"
HTTP/1.1 301 Moved Permanently
Content-Length: 178
Content-Security-Policy: default-src 'none'; object-src 'none'; report-uri /__cspreport__
Content-Type: text/html
Date: Thu, 05 Jul 2018 22:15:04 GMT
Location: https://versioncheck.addons.thunderbird.net/update/VersionCheck.php?reqVersion=2&id=3ed8cc52-86fc-4613-9026-c1ef969da4c3&version=3.2.4&maxAppVersion=60.*&status=userEnabled&appID=3550f703-e582-4d05-9a08-453d09bdfdc6&appVersion=45.0&appOS=WINNT&appABI=x86-msvc&locale=en-US&currentAppVersion=52.9.0&updateType=97&compatMode=strict
Server: nginx
Strict-Transport-Security: max-age=300
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

**Comment by diox** [comment]
@bqhn: when there are `{` or `}` in the url, you should use `-g` with curl, otherwise it does not send the request you want. You can check with `-v`, the brackets are lost, causing a different request to be send. Ironically I suspect a similar issue is present with the redirects that's causing them not to work when the brackets are present in the URL.

**Comment by bqbn** [comment]
Thanks @diox.

This should have been fixed.

```
$ curl -g -I 'https://versioncheck-dev.allizom.org/update/VersionCheck.php?reqVersion=2&id={3ed8cc52-86fc-4613-9026-c1ef969da4c3}&version=3.2.4&maxAppVersion=60.*&status=userEnabled&appID={3550f703-e582-4d05-9a08-453d09bdfdc6}&appVersion=45.0&appOS=WINNT&appABI=x86-msvc&locale=en-US&currentAppVersion=52.9.0&updateType=97&compatMode=strict'
HTTP/1.1 301 Moved Permanently
Content-Length: 178
Content-Security-Policy: default-src 'none'; object-src 'none'; report-uri /__cspreport__
Content-Type: text/html
Date: Thu, 05 Jul 2018 23:34:53 GMT
Location: https://versioncheck.addons.thunderbird.net/update/VersionCheck.php?reqVersion=2&id={3ed8cc52-86fc-4613-9026-c1ef969da4c3}&version=3.2.4&maxAppVersion=60.*&status=userEnabled&appID={3550f703-e582-4d05-9a08-453d09bdfdc6}&appVersion=45.0&appOS=WINNT&appABI=x86-msvc&locale=en-US&currentAppVersion=52.9.0&updateType=97&compatMode=strict
Server: nginx
Strict-Transport-Security: max-age=300
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

**Comment by Sancus** [comment]
Can confirm that all redirects seem to be working on dev now, thanks!
