### ISSUE TITLE
 ublock on desktop links to android

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#6393]
Copied over from [bug 1397705](https://bugzilla.mozilla.org/show_bug.cgi?id=1397705):
----

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Build ID: 20170824053622

Steps to reproduce:

open about:addons
open ublock settings
scroll down to homepage

Actual results:

sometimes the homepage links to
https://addons.mozilla.org/de/android/addon/ublock-origin/?src=api

and sometimes to
https://addons.mozilla.org/de/firefox/addon/ublock-origin/?src=api

but the client is always a desktop firefox

Expected results:

Firefox should always link to the specific page

**Comment by diox** [comment]
I can not reproduce with my Firefox, there must be some step I'm missing. I would need to see what URL the original reporter was hitting.

Trying to mimic their config, I've tried hitting `https://services.addons.mozilla.org/de/firefox/api/1.5/search/guid:uBlock0@raymondhill.net?src=firefox&appOS=WINNT&appVersion=55.0` a few dozen times and I've got consistent results, no android.

**Comment by diox** [comment]
I was able to reproduce after trying again a few times, by hitting the url with `Android` as the `appOS` and then `WINNT` immediately after. That looks like a caching issue of some sort, the result seems to "stick" for a while despite the `appOS` parameter changing between requests.
