### ISSUE TITLE
Collections: no entry, 'Works with Firefox', for add-ons that are not for Firefox

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-server#6394]
For example, a Firefox 55.0.3 view of https://addons.mozilla.org/collections/tonymec/trh/

> Works with Firefox

– should **not** appear for add-ons such as _Lightning_ and _Provider for Google Calendar_. 

![2017-09-10 20 55 15 tonymec s rubble heap collections add-ons for firefox](https://user-images.githubusercontent.com/192271/30353835-80a8b728-9820-11e7-9f89-6cc6e79c85d3.png)

**Comment by eviljeff** [comment]
This is kinda fixed in new frontend, by not having install buttons in the collection view 😄

**Comment by grahamperrin** [comment]
Thanks. TBH I stopped visiting collections after features such as _sort_ disappeared with the new look … and I haven't reviewed issues recently to tell whether reintroduction is on the roadmap for this year. Laziness here (priorities elsewhere).
