### ISSUE TITLE
Create SUMO article explains permissions APIs in broader detail

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#6395]
Currently the only information users have about extension permissions is through a small overlay that details each extension's permission/s through one or more bullet points. In some cases, these tiny bullets don't provide enough context. We should create a SUMO page (linked to from the overlay) that describes each permission in broader detail.

**Comment by eviljeff** [comment]
Does the SUMO page exist now?  If not have you been working with someone to create it?
I don't know if any of the permissions are documented anywhere at the moment - the Firefox application devs are probably the best people who to know what the permission does (as they added them).

Also, it's probably more important to log this on addons-frontend as the legacy detail page is going by the end of the year.
