### ISSUE TITLE
Consider indexing add-on slugs as 'keyword' in ES

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6396]
At the moment, we index add-on slugs in ES as `text`, so they are analyzed. When searching, we include `slug` in the clauses.

But... does it make sense? For most add-ons, `slug` is just like a poor variant of `name`. Do we really need to analyze slugs and include them when searching with a query ? If slugs were indexed as keyword, it would allow exact matches on them, which seem more useful (allows to find an add-on by slug in ES, and also exclude them in #6376)

**Comment by EnTeQuAk** [comment]
I agree that indexing the slug as `text` doesn't make much sense and would vote to change this to be indexed as `keyword` instead which allows filtering or exact matching and represents more what a slug is actually used for. Imho the slug is very similar to a guid and should only be used for exact matches.

So 👍 on changing this.

**Comment by eviljeff** [comment]
In general, you're right - the slug will be a variant of the name, or at least mentioned in the summary text.  I can't help thinking of a (hypothetical) edge case where you might want to search by slug though.  But if it's needed for #6376 then :+1: too

**Comment by diox** [comment]
Would we still need to search against the slug when a query is present ? At the moment we have a bunch of `should` clauses (`MatchPhrase`, `Match`, `Fuzzy` and `Prefix`) applied to the `name`, `slug`, and `listed_authors.name`.

**Comment by vcarciu** [comment]
Can you please add some STRs for this issue or mark it as "qa: not needed" ?
