### ISSUE TITLE
Remove ADI restriction when total downloads are lower

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6397]
Certain add-ons have a higher ADI count than total downloads. One example is [ipFood](https://addons.mozilla.org/addon/ipfood/), which has ~440K ADI downloads and ~86K. The listing page shows only ~86K users because at some point we introduced a restriction that ADI shouldn't be higher than downloads.

It was meant as a way to block abuse of the update API to fake higher usage numbers, but in practice it hasn't been a real problem. Looking at the add-ons affected by this, it seems to be causing more harm than good, so we should get rid of it.

**Comment by eviljeff** [comment]
It was more bundled system add-ons than intentional abuse, fwiw.  From https://bugzilla.mozilla.org/show_bug.cgi?id=684998
> Now that we sort popularity by most users, add-ons that are bundled with other apps and ping AMO for updates by default are gaming the system unintentionally. For example, the most popular extension (https://addons.mozilla.org/en-US/firefox/extensions/?sort=users) is Microsoft .NET. This is really bad -- we don't want these advertised as the most popular add-ons.

Ref https://github.com/mozilla/addons-server/commit/c1588538479d9f85f4c1419e1f22c794a1674ace

**Comment by jvillalobos** [comment]
Most of those cases should no longer be a problem after #3632.

**Comment by EnTeQuAk** [comment]
@jvillalobos does this need some kind communication on the blog or elsewhere, otherwise, I'd like to get this into this weeks milestone or next weeks.

**Comment by jvillalobos** [comment]
No, it's not a big change.
