### ISSUE TITLE
Auto-approve WebExtensions Language Packs

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6398]
At the moment `auto-approve` does not consider WebExtensions Language Packs as auto-approvable, because they have a different `type` in the database. We need to change that to make them auto-approvable.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Webextension Lang Packs are auto-approved.
Example:
https://addons-dev.allizom.org/en-US/developers/addon/language-pack-test/edit
