### ISSUE TITLE
Make the button label @ /developers/addon/submit/agreement more readable

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-server#6400]
### Describe the problem and steps to reproduce it:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/agreement
2. Notice the button label

### What happened?
Button label is grammatically correct but is too lengthy and not very readable.

### What did you expect to happen?
Button label is readable. Suggest changing the copy to "Yes, I Accept" because there is copy above which clearly states that clicking the button means they have read the links.

### screenshot
<img width="1055" alt="screenshot 2017-09-13 16 22 13" src="https://user-images.githubusercontent.com/301317/30398996-49771ab2-98a0-11e7-8723-cc7da2f5f84e.png">

**Comment by diox** [comment]
That's for @jvillalobos to decide

**Comment by jvillalobos** [comment]
I think the button is okay, but maybe less so in other languages. We could move the text to a line above the buttons:

`I have read and accept this Agreement and the Rules and Policies.`
`[Accept] or [Cancel]`

**Comment by apoorvaeternity** [comment]
@jvillalobos 
Suggestion:
I think it would be better to remove the text line 
"I have read and accept this Agreement and the Rules and Policies."
from the page.
Just [Accept] or [Cancel] would be enough.
The page clearly states that it is an agreement. Plus we are also using checkboxes for both Agreement and Review Policies and Rules.

**Comment by jvillalobos** [comment]
That kind of statement is fairly standard in such UI, and it might have some legal implications. I'd rather keep it.

**Comment by ilmanzo** [comment]
already fixed ? in current tree I have this

![image](https://user-images.githubusercontent.com/1872816/30849892-229a7110-a2a4-11e7-9180-6d17c046ebe5.png)

**Comment by diox** [comment]
@ilmanzo you need to enable the `post-review` waffle switch. You can do so using `./manage.py waffle_switch post-review on` from inside the addons-server container.

**Comment by ilmanzo** [comment]
whops... Sorry :) 
This seems simple to me, the only issue is to introduce a translation for 'Accept' string (we already have 'Cancel')
