### ISSUE TITLE
Webext Lang Pack cannot be installed

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6408]
Steps to reproduce:
1. Submit a Webext Lang Pack in AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/addon/app-language-pack/
2. Try to install it

Expected results:
Lang Pack is successfully installed.

Actual results:
Lang Pack cannot be installed.

Notes/Issues:
- a message is displayed in the browser console at installation: 
`1505377355381	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing languages.pl: Unexpected property "resources"`
- strict_min/max version are correct
- no strict_min/max version will make the webext lang pack compatible from FF48.0 to *

#6350

**Comment by diox** [comment]
@ValentinaPC where did you get that language pack? I assume you were using nightly?

@zbraniecki is it supposed to be working yet? It looks like this should be a bug filed in bugzilla if that's the case, but maybe there is more that we can validate on our end?

**Comment by ValentinaPC** [comment]
@diox : Nightly, yes.
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1365709

**Comment by zbraniecki** [comment]
As far as I know we do not yet support WebExt Langpacks in AMO. The work is ongoing in https://github.com/mozilla/addons-server/issues/6297

**Comment by zbraniecki** [comment]
Oh, wait. You're asking if it works in Firefox! Yes, it should :)

**Comment by diox** [comment]
@zbraniecki : I did implement basic support to upload them in AMO. As far as AMO is concerned it should work on dev, which is where @ValentinaPC was testing. Which is why I'm wondering if the langpack that was uploaded (see link above) should be working in nightly right now.

**Comment by zbraniecki** [comment]
It may be that the langpack in the bug was using some older schema.

I updated the attached extension in https://bugzilla.mozilla.org/show_bug.cgi?id=1365709 and it does work now for me locally. Please use it to test the AMO cycle.

Thank you!

**Comment by zbraniecki** [comment]
Yeah, so `Reading manifest: Error processing languages.pl: Unexpected property "resources"` indicates that it was an outdated schema.

If you have a mozilla-central build system you can build the langpack yourself with `WEBEXT_LANGPACKS=1 ./mach build langpack-fr`

**Comment by diox** [comment]
Thanks, the next extension is working for me too, so nothing left to do here, I'll let @ValentinaPC verify.

**Comment by vcarciu** [comment]
Verified as fixed based on previous comments by installing https://addons-dev.allizom.org/en-US/firefox/addon/polski-language-packzz/
