### ISSUE TITLE
"Is more info requested?" checkbox displayed in Comment tab

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6409]
Steps to reproduce:
1. Add a "Reviewer Reply" for an add-on while also checking the "Is more info requested?" option  i.e. https://addons-dev.allizom.org/en-US/editors/review/bitch-bitched-bitches-2
2. After "Save" go back to add-on review page and click in Comment tab

Expected results:
A text field is opened where user can write a comment.

Actual results:
The "Is more info requested?" checkbox is also displayed under the text field.

Notes/Issues:
- the checkbox is not displayed in the Request Super Review tab
- the checkbox is not displayed in Request Super Review and Comment tabs if not checked at Reviewer Reply submission.

Screenshot for this issue:
![2017-09-14_1012](https://user-images.githubusercontent.com/15685960/30420612-cc971666-9942-11e7-93ba-8dadb62963c0.png)

**Comment by wagnerand** [comment]
This is intended.

* the checkbox should only be checkable during a reviewer reply.
* the checkbox should be uncheckable during reviewer reply or comment.
