### ISSUE TITLE
"View Mobile Site" unusable link in Reviewer Tools 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6411]
Steps to reproduce:
1. Load Reviewer Tools homepage https://addons-dev.allizom.org/en-US/editors/
2. Observe page footer

Expected results:
There is no "View Mobile Site" link.

Actual results:
There is a "View Mobile Site" unusable link.

Notes/Issues:
- this is a suggestion as per Developer Hub page
Verified on AMO-stage FF55(Win 7).
Screenshot: 
![30421105-67e97284-9944-11e7-8ee0-cf818707476f](https://user-images.githubusercontent.com/15685960/30424301-32481a0e-994e-11e7-8a6e-9c5001cf20bd.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/49435304-f7521a00-f7be-11e8-9b3b-e30f6343bbc9.png)
