### ISSUE TITLE
ES indexing does not seem to "unaccent" strings

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6413]
To fix #6396 I made `slug` a `keyword`, so it's not analyzed anymore. I then noticed that the following test was broken:
```python
        addon = addon_factory(slug='my-addon', name=u'My Addôn',
                              tags=['some_tag'])
        addon_factory(slug='unrelated', name=u'Unrelated')
        self.refresh()

        data = self.perform_search(self.url, {'q': 'addon'})
        assert data['count'] == 1
        assert len(data['results']) == 1

        result = data['results'][0]
        assert result['id'] == addon.pk
```

It turns out that searching for `addon` does not match a document with `My Addôn` as a name... because of the accent. That test used to pass before purely because of the slug.

Worryingly, this seems to happen even if the add-on name is considered to be a french translation, meaning that somehow ES french analyzer does not remove accents when indexing. It's kind of a basic expectation when searching, at least in french, so we should definitely fix this.

**Comment by diox** [comment]
There is probably a lot more on the subject (including digging deep into the language-specific analyzers) but I found this: https://www.elastic.co/guide/en/elasticsearch/guide/master/asciifolding-token-filter.html

**Comment by EnTeQuAk** [comment]
Yeah, asciifolding is probably the first step in getting something reasonable. Next step is actually researching all those languages we support and add tests for basic needs for them

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-150
