### ISSUE TITLE
Expose permissions in the user profile

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6415]
Hi, I was looking for the user's permissions and hardly found them in the [`login` endpoint response](https://addons-server.readthedocs.io/en/latest/topics/api/auth_internal.html#get--api-v3-accounts-login-).

The frontend does not query this endpoint very often and I think permissions belong to the user profile. Therefore, would it be possible to expose the permission in the [`profile` response](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#profile)?

Edit: we actually never use the `login` endpoint on the frontend...

Thanks!

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
