### ISSUE TITLE
Search suggestions does not match search results in Nightly

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6417]
Steps to reproduce:
1.Open Latest Nightly
2.Go to https://addons.allizom.org/en-US/firefox/
3.Enter a search term (ie. "firebu")
4.Observe the search suggestions
5.Click Enter

Expected results:
Search suggestions should match the search results list

Actual results:
Search results are completely different than search suggestions

NOTES:
This is reproducible only on Firefox Nightly. Not reproducible on Release.
This is reproducible also on Production 
This is probably caused by the fact that search results are not listing the incompatible add-ons , while search suggestions allow that.

Please see a video with this issue : 
![brokensearch](https://user-images.githubusercontent.com/1583842/30435930-a816d606-9973-11e7-86ff-f40bc0b2f312.gif)

**Comment by diox** [comment]
Yes, this is not a new problem. The search suggestions on the legacy frontend are using a different codepath than regular search does. Most parameters that would filter stuff out in the regular search are completely ignored in the search suggestion view.

**Comment by EnTeQuAk** [comment]
This got improved recently and a bit more with https://github.com/mozilla/addons-server/pull/7303 which has landed on master and will be deployed on Thursday and should fix this problem. I'm closing this issue but please feel free to re-file / re-open any time if things aren't working properly.

**Comment by vcarciu** [comment]
Tested this issue in Nightly, new frontend and it is not reproducible anymore. Marking it as verified : 
![searchnightly](https://user-images.githubusercontent.com/1583842/35575162-62d48bbe-05e4-11e8-9e40-667de5e92097.png)
