### ISSUE TITLE
add django admin pages to change collection contributors and owner

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6418]
The new collection API won't publicly support contributors but we still have them for Mozilla controlled collections (e.g. featured addons/themes) so we need a django admin page to modify stuff.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Adding or deleting collaborators from collection using django admin page is propagated in AMO with no issues. Vice-versa is also correct.
Postfix video:
![amo-dj](https://user-images.githubusercontent.com/15685960/30850104-20daa44a-a2ad-11e7-9df4-ecafe59f9dca.gif)
