### ISSUE TITLE
Cannot register to AMO prod

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6421]
Steps to reproduce:
1.Go to amo prod and try to register with a new account
2.Click the "Activate now" button from verification email

Expected results:
User is automatically logged in to AMO prod with the new account

Actual results:
User is asked for password again and again and cannot register with new accounts

NOTES:
Not reproducible on Stage

Please see video for this issue: 
![registration](https://user-images.githubusercontent.com/1583842/30445423-91c5dff8-998e-11e7-9a9c-cc5e02808b9a.gif)

**Comment by EnTeQuAk** [comment]
So, from my perspective:

I can log in properly with my "old" user cgrebs@mozilla.com but a newly registered one `cg+test1@webshox.org` can't login, I get redirected from fxa to AMO but no session is set.

**Comment by EnTeQuAk** [comment]
This works for me in chromium. So now I have one user (was already registered) that is able to login in firefox, one that isn't (newly registered) but the one that isn't, is able to login via chromium.

**Comment by EnTeQuAk** [comment]
status update: It seems to have been solved by magic, we're waiting a bit and will try to verify and see if it continues to work.

**Comment by EnTeQuAk** [comment]
status update: So this is related to us running loads of celery tasks to calculate review aggregates. That task calls `addon.update()` which in turn starts a new `index_addon` task which is a priority task and blocks processing of register events via celery. What I don't get for now: I don't see what is async on the register process, hmm... still investigating

**Comment by EnTeQuAk** [comment]
mystery solved: That processing task launched a massive amount of tasks that quickly got processed by our celery workers which in turn apparently led to a replication lag of multiple minutes (up to 21 minutes to be precise) which then means that a newly registered user (write to master) needs a few minutes to replicate to our slaves which are the ones that are queried for a log-in.

**Comment by EnTeQuAk** [comment]
I'm closing this since the database lag is now fixed and thus the issue.

**Comment by vcarciu** [comment]
Verified as fixed
