### ISSUE TITLE
API: Add category names to Addons detail responses

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6422]
The [details response only provides a list of category slugs for a given Addon](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v3-addons-addon-(int-id|string-slug|string-guid)-). 

This means that to display the category we need to make a separate request for the categories.

Ideally we would be able to get the category names and slugs so that this separate request can be avoided. 

This may need discussion since changing the data layout might be problematic.

**Comment by diox** [comment]
Categories are static though. Couldn't they be included in the frontend? See http://addons-server.readthedocs.io/en/latest/topics/api/categories.html#current-categories for the full list

**Comment by tofumatt** [comment]
So we were chatting on IRC but I actually don't think the API needs to send anything more than a slug down. The frontend makes a single request to get ALL categories using `categoriesFetch` (https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Categories/index.js#L60).

I think given it's a single request and having category info in state is handy this would be better accomplished by just dispatching `categoriesFetch` if the data isn't already loaded in state.

**Comment by tofumatt** [comment]
So @diox and I chatted on IRC and I think this is a won't fix. I get that it means an extra request for the front-end but I think that small request is worth it as it will cache ALL of the categories in the future in state for the app and means:

* no breaking API change
* relatively little engineering effort on both apps
