### ISSUE TITLE
Internal Mozilla-signed add-ons are legacy but should not have compatibility restrictions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6424]
For the foreseeable future, AMO will be getting legacy submissions that are signed with the internal Mozilla certificate, which gives them the ability to be installed in Firefox 57 and above. We need to make an exception for these add-ons in our compatibility restrictions. Specifically:

- It should be possible to upload them without an admin override.
- They shouldn't have strict compatibility and should appear as compatible in 57 and above.
- They should show the `Compatible with 57+` tag.
- They shouldn't have lower ranking on search results.

For an example, see [Firefox multi-account containers](https://addons.mozilla.org/addon/multi-account-containers/).

**Comment by jvillalobos** [comment]
We'll also need to verify that automatic updates are working normally.

**Comment by diox** [comment]
We already have a `is_mozilla_signed_extension` field on `File`. We need to:
- Check when we do that detection. It might need to happen earlier than we currently do, because...
- ... Add the result of that detection in the validation metadata
-  Use the newly added metadata to bypass upload restrictions, avoid setting `strict_compatibility` on the `File`, and avoid the compatibility limits
- Make the `Compatible with Firefox 57+` label use the tag instead of `is_webextension()`, and apply that tag if the File has `is_mozilla_signed_extension` as well (*)
- Store `is_mozilla_signed_extension` in ES, modify the rule that boosts webextensions when searching to also boost if that field is present.

(*) Creates a potential issue if the add-on is *not* compatible with 57... Hopefully that won't happen.

**Comment by groovecoder** [comment]
Thank you for taking this on! If you have any questions that could be answered by specific add-on authors, please ping @jonathanKingston or myself here.

**Comment by jonathanKingston** [comment]
I'm not sure how much the work @diox is suggesting is however there could be an interim task of changing the button code to use the legacy whitelist which is in firefox at the moment. This would allow easier installs for the extension even if they can't be searched for etc.

**Comment by diox** [comment]
@jonathanKingston that would not be enough for search as you point out, but also this hack would need to be applied to the `Compatible with Firefox 57+` label, the compatibility information displayed on the add-on detail / versions page, and more importantly the update service. I don't think it's worth it compared to the somewhat (it's still a hack that's going to make AMO more complex) cleaner approach I described above.

**Comment by TanviHacks** [comment]
Is there anyway something (hack or full solution) could be put in place to fix the "Download Anyway" bad user experience by September 26th when Firefox 57 moves to beta?

**Comment by diox** [comment]
@TanviHacks : Please open a new issue if you have a bug to report instead of commenting on an existing one.

**Comment by TanviHacks** [comment]
Filed https://github.com/mozilla/addons-server/issues/6446

**Comment by TanviHacks** [comment]
Is there a timeline on this issue?

**Comment by diox** [comment]
It is set as "priority: p2", and already assigned. We're hoping to do this in time for this week's tag, released next Thursday, or the week after that.

**Comment by ValentinaPC** [comment]
I've tried submitting the attached extension, without the "META-INF" folder, and I received the message "Starting with Firefox 53, new add-ons on this site can only be WebExtensions".
I've added the strict compat option in the install.rdf...but same results.
I am doing something wrong? Thanks!

**Comment by diox** [comment]
The whole point of this issue is being able to submit extensions already signed with Mozilla internal certificate, so you need to keep the `META-INF` folder.

**Comment by ValentinaPC** [comment]
Did that, initially....but got an error. Does this still needs time to be in -dev?

**Comment by muffinresearch** [comment]
@ValentinaPC that'll probably depend on the error - could you provide more details?

@EnTeQuAk can you provide some steps for how this should be tested and what to expect etc?

**Comment by ValentinaPC** [comment]
@muffinresearch: same old message:
![2017-09-26_1609](https://user-images.githubusercontent.com/15685960/30862016-3b90e010-a2d5-11e7-8564-f152a4e39965.png)

**Comment by diox** [comment]
@ValentinaPC only users with a `@mozilla.com` email can submit a Mozilla Signed Extension.

**Comment by ValentinaPC** [comment]
@diox : you are right, using a `@mozilla.com` account, submission of the attached extension is made with success.
- `strict min version` is taken into consideration
- `max_version` is set to `------` 
- cannot be installed on FF58

All good? :)

**Comment by EnTeQuAk** [comment]
that sounds good imho

**Comment by ValentinaPC** [comment]
@EnTeQuAk : why I cannot install it on FF58? And why is not the max version "*" if that is what it was set up in install.rdf?

**Comment by diox** [comment]
@ValentinaPC what's the link to the add-on?

**Comment by ValentinaPC** [comment]
https://addons-dev.allizom.org/en-US/firefox/addon/embeded-signed-legacy-addons/

**Comment by diox** [comment]
I don't see any issue with that add-on in FF58, and the max version is "*" as far as AMO is concerned (it displays "and later" in the detail page).

**Comment by ValentinaPC** [comment]
Maybe add-on details page displays "...and later" but Dev Hub **does not list** "`*`" as max version, because it does not exist, last version for legacy being `56.*`, and I suppose that is why, we cannot install the add-on on 58.
![2017-09-27_1518](https://user-images.githubusercontent.com/15685960/30913003-47cf5bdc-a397-11e7-9264-460130b979d1.png)

**Comment by diox** [comment]
That's a different issue. Again, I was able to install that add-on without any problems with FF58. The detail page / API show the right max version, `*`.

However, you're right that devhub form should be fixed to allow to display `*`. ( @EnTeQuAk : that's in https://github.com/mozilla/addons-server/blob/774c3b927ec05ef971e4206e2669b4291b8b4f17/src/olympia/devhub/forms.py#L449-L454 )

**Comment by groovecoder** [comment]
Did this fix deploy today? I still see a disabled "Add to Firefox" button on 57 ...

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/71928/30990225-12df67da-a466-11e7-97cb-a4be041da5a9.png">

**Comment by EnTeQuAk** [comment]
This got fixed for mozilla signed add-ons that are receive new version uploads (might be a workaround for you). I'm working on a script / migration that set's the correct restrictions for all already uploaded versions.

**Comment by EnTeQuAk** [comment]
https://github.com/mozilla/addons-server/pull/6540 can be run by ops once reviewed and merged.

**Comment by ValentinaPC** [comment]
Was #6540 run? Thanks!

**Comment by diox** [comment]
@ValentinaPC yes, we ran it directly on prod. You can see the add-on mentioned in this issue, [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/), is now available for Firefox 57 and higher despite not being a webextension.

**Comment by ValentinaPC** [comment]
Should we list the compatibility label if is not a webextension?

**Comment by diox** [comment]
Yes, that's the point of this issue. It's not a webextension, but mozilla signed extensions should work and are therefore marked as compatible.

**Comment by ValentinaPC** [comment]
I understand the point of this issue. Just thought that active installation button would be enough.

Marking this verified as fixed on AMo-prod FF56(Win 7)

**Comment by groovecoder** [comment]
Yup, thanks everyone! We now have a green "Add to Firefox" button on our add-on.
