### ISSUE TITLE
Strict-compatibility enabled for too many add-ons.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6425]
#5277 enabled strict-compat for legacy add-ons to prevent them from being compatible with 57.

However, the implementation deviates from the defined requirements a bit.

What was said in the requirements (https://github.com/mozilla/addons-server/issues/5277#issue-224529745):
"So, for legacy add-ons that don't already have strict compatibility set, we should set it to a maxVersion of 56.*."

What we did:
We set strict-compatibility for all legacy add-ons, but we didn't bump the maxVersion to 56.* (for the ones that didn't already have it set by the developer).

What we need to do now:
Figure what legacy add-ons we set the strict-compatibility as part of that work and bump the maxVersion to 56.* for those, and for those only.
We should not bump the maxVersion for legacy add-ons where the developer set strict-compatibility in the manifest.

**Comment by diox** [comment]
For reference, the commit that did this: https://github.com/mozilla/addons-server/commit/3a23e4021d8845c609a82735716e81f55c8f959c#diff-c23a5f0fb77b91c0cb4dc0018de9e1ba

I assumed when I wrote it that the compatibility bump we used to do for every Firefox release would be enough, but that's not the case.

I see only 2 ways to find affected add-ons:
- Use a backup from before the migration. The only thing we'd really care about is exporting a list of add-ons that already had the `strict_compatibility` on a file for their current listed version, then bump compatibility on all legacy listed add-ons not in that list.
- Add a task that goes through all existing listed legacy add-ons, re-parse the contents of the current file(s), and bump those not having strict compatibility enabled in their install manifest

I think the first solution would be better, but need to figure out with ops how annoying it is to pull such a backup. We'd only need the `files` and `version` tables really to build the list, so if we can restore a backup ignoring FKs that'd help speed things up.

**Comment by diox** [comment]
For the second solution, we can cheat and only look at add-ons not compatible with 56.* max. That should limit the time spent parsing add-ons.

**Comment by diox** [comment]
@wagnerand could you link some affected add-ons in prod that should receive a compat bump to 56.*, so that I can verify what I'm doing?

**Comment by diox** [comment]
After talking with @bqbn I concluded that the first solution, using backups, won't work: our policy is to keep 35 days of snapshots + some older, more sporadic ones, so we only have backups that are too old or too recent for this.

I'll go with the second solution, re-parsing a bunch of add-ons.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
- if strict compat is set to true for legacy add-ons the min/max versions remain the ones set by developer
- if strict compat is not set to true, for example for multiple apps add-ons, and have the max version `*`, after submission the max version is set to `56.*`

Postfix screenshot:
![strict](https://user-images.githubusercontent.com/15685960/30635315-b2bfd5a4-9dfa-11e7-98db-2a45c6c97620.png)
