### ISSUE TITLE
Bust the cache on the favicon

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6431]
* [x] Change the url to bust the cache on addons-server
* [x] Change the url to bust the cache on addons-frontend

This should mean that on visiting amo for both the legacy and new frontend you will see the new favicon:

<img width="249" alt="menubar_and_amo-favicon-teal-00c8d7_png__png_image__32 x 32_pixels__and_skype" src="https://user-images.githubusercontent.com/1514/30545248-fad896b2-9c80-11e7-9faa-5416ff4b6363.png">

**Comment by kumar303** [comment]
Why do we need to bust the cache? Is it a browser bug? Could we adjust our caching headers instead?

**Comment by muffinresearch** [comment]
> Why do we need to bust the cache? Is it a browser bug? Could we adjust our caching headers instead?

Afaict the browser will never make the request because of far futures expires. The undesirable alternative would be to wait 10 years.

**Comment by madalincm** [comment]
Verified as fixed in FF55(Win7) in addons-dev.allizom.org in legacy pages and new pages. The fav icon is displayed without any issues.
Marking bug as verified fixed.
