### ISSUE TITLE
Change favicon colour to #00c8d7

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6433]
Following some rapid prototyping with @pwalm on irc we're going to change the colour of the favicon to provide something that works on light/dark themes and doesn't need a background.

![amo-favicon-less-hot-2](https://user-images.githubusercontent.com/1514/30494833-8da7f902-9a41-11e7-91ea-4d7511e879f2.png)

**Comment by madalincm** [comment]
Verified as fixed in FF55(win7) in addons-dev.allizom.org
Postfix screencast:
![favicon](https://user-images.githubusercontent.com/15685441/30534796-67cdad5c-9c68-11e7-864e-35c26cde3e58.png)
