### ISSUE TITLE
URL /themes/ does not load on local running olympia.dev

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#6445]
The URL ```/themes``` does not load correctly on a local instance of the AMO site.

Log of the error:
https://pastebin.mozilla.org/9032667

@diox created a patch that works but advised it as a temporary solution.
https://gist.github.com/diox/856ed1651be6e97bd55e1083c71e592b

**Comment by diox** [comment]
This happens because our template engines considers absent variables as '' when `DEBUG` is `False`, but throws an error in that specific case (an object's property) when `DEBUG` is `True`.

I think my patch makes sense but it needs more testing, maybe there is a better way to do that.

**Comment by EnTeQuAk** [comment]
The patch looks good but instead of the empty string we should pass in nothing imho. `category` is optional in the url as far as I can see and the view is actually testing for `category_slug is not None`

**Comment by jrbenny35** [comment]
As mentioned in #6457 @diox would like a test for this patch. 

I am thinking this is the test that needs updating: https://github.com/mozilla/addons-server/blob/master/src/olympia/browse/tests.py#L939

How should I go about changing this to accommodate the new changes?

**Comment by diox** [comment]
I don't think you should change those tests (they have one job - testing redirects - let's leave them alone).

You can try the following:
```diff
diff --git a/src/olympia/browse/tests.py b/src/olympia/browse/tests.py
index 9f60d98..40baced 100644
--- a/src/olympia/browse/tests.py
+++ b/src/olympia/browse/tests.py
@@ -1053,6 +1053,11 @@ class TestPersonas(TestCase):
             a.status = amo.STATUS_PUBLIC
             a.save()
 
+    def test_does_not_500_in_development(self):
+        with self.settings(DEBUG=True):
+            self.test_personas_grid()
+            self.test_personas_landing()
+
     def test_personas_grid(self):
         """
         Show grid page if there are fewer than
@@ -1060,10 +1065,10 @@ class TestPersonas(TestCase):
         """
         base = Addon.objects.public().filter(type=amo.ADDON_PERSONA)
         assert base.count() == 2
-        r = self.client.get(self.landing_url)
-        self.assertTemplateUsed(r, self.grid_template)
-        assert r.status_code == 200
-        assert r.context['is_homepage']
+        response = self.client.get(self.landing_url)
+        self.assertTemplateUsed(response, self.grid_template)
+        assert response.status_code == 200
+        assert response.context['is_homepage']
 
     def test_personas_landing(self):
         """
@@ -1082,8 +1087,8 @@ class TestPersonas(TestCase):
             type=amo.ADDON_PERSONA, slug='abc',
             count=MIN_COUNT_FOR_LANDING + 1, application=amo.FIREFOX.id)
         category.save()
-        r = self.client.get(self.landing_url)
-        self.assertTemplateUsed(r, self.landing_template)
+        response = self.client.get(self.landing_url)
+        self.assertTemplateUsed(response, self.landing_template)
 
     def test_personas_grid_sorting(self):
         """Ensure we hit a grid page if there is a sorting."""
```

**Comment by jrbenny35** [comment]
I'll get that in a PR! Thanks @diox!

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
