### ISSUE TITLE
Document /accounts/login/start/ API endpoint

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6452]
Unless I'm missing it, I don't see `/accounts/login/start/` documented here: https://addons-server.readthedocs.io/en/latest/topics/api/auth_internal.html

This is what the [frontend calls](https://github.com/mozilla/addons-frontend/blob/master/src/core/api/index.js#L197) to begin the Firefox Accounts login process so I think it should be documented.

**Comment by EnTeQuAk** [comment]
I'll get something going here, I looked at the whole process how FxA worked a few weeks ago when working on our locust.io tests.

**Comment by tapaswenipathak** [comment]
Hi folks: Can I work on the ticket?
