### ISSUE TITLE
Allow add-on developers to request GUID namespaces to be locked to their account

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/addons-server#6455]
Right now, issues #4688 and #4796 have made it so that the `@mozilla.org` GUID namespace is locked to Mozilla accounts.

I request that any add-on developer can make a request to have the GUID namespace that they use in their add-ons to be locked to their account, preventing other developers from using it.

Once a GUID lock request is filed, it is reviewed by Mozilla to ensure that the developer is authorised to claim the GUID namespace and isn’t trying to claim someone else’s domain or do something else that is malicious.

It should also be possible for other developers to file a request for GUID namespace lock revocation that would then be reviewed by Mozilla to filter out valid claims from unauthorised ones.

There should also be some requirements to qualify for GUID namespace locks. For example, having at least one add-on with a namespaced GUID and a sufficiently clean record (i.e. no intentionally malicious extensions and good conduct).

**Comment by jvillalobos** [comment]
This is a lot of work and manual process for a feature that wouldn't be used much. GUIDs are hidden from users, so it's not something that matters that much for anyone other than the developer. Also, the current trend is to not set an ID in the manifest at all, and just rely on whatever is randomly set by AMO on submission. I don't think this provides enough value to warrant the effort.
