### ISSUE TITLE
Configure l10n extract as cronjob

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6462]
Needs https://github.com/mozilla/addons-server/issues/6461 to be implemented first.

Refs https://github.com/mozilla/addons-server/issues/2181

The idea was to configure the script via travis cronjobs since that allows us to re-use the secret values we already have in our `travis.yml` file.

**Comment by EnTeQuAk** [comment]
This is configured now and running every Thursday, needs to be checked and improved upon.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed'?
Thank you
