### ISSUE TITLE
The badges for non-compatible add-ons on the author profile page are not consistent

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/addons-server#6466]
### Describe the problem and steps to reproduce it:
1. In Firefox (on other platform than Windows) go to my [user page](https://addons.mozilla.org/en-US/firefox/user/mstanke/).
2. See there is an add-on for Thunderbird on Windows only (xpDefault).
3. Hover it with your mouse.

### What happened?
Two badges will display on the right. One "Not available for your platform" and second "Works with Firefox".

### What did you expect to happen?
The second text is wrong, should be "Does not work with Firefox". Looking into the strings, this one is probably reused from somewhere else and I guess it will be the case one more places than just this one.

### Anything else we should know?
![snimek z 2017-09-21 08-28-33](https://user-images.githubusercontent.com/3941344/30681853-7bdd7750-9ea7-11e7-8f3a-c448c840db97.png)
CC @zelitomas @peiying2

**Comment by peiying2** [comment]
@muffinresearch

**Comment by muffinresearch** [comment]
@diox any thoughts on what might cause this?

**Comment by diox** [comment]
The platform compatibility stuff is just a mess with add-ons for other apps than Firefox, but particularly on the user profile page, I don't know why. We must be ignoring the current app somehow on that page, or something like that.

**Comment by muffinresearch** [comment]
This will be superceded by https://github.com/mozilla/addons-frontend/issues/2781
