### ISSUE TITLE
"Add-on distribution agreement" is required on Stage even if it is not the first submitted addon

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6467]
Steps to reproduce:
1.Login to Stage with an account which already have some submitted add-ons
1.Try to upload a new add-on or a new version to an existent add-on

Expected results:
"Add-on distribution agreement" is not required 

Actual results:
"Add-on distribution agreement" is required

NOTES:
After accepting the agreement, it is not required at subsequent submissions 
NOT reproducible on -dev or prod

Please see video for this bug : 
![devagreement](https://user-images.githubusercontent.com/1583842/30694637-85182050-9edd-11e7-8710-4fd09aeab2fa.gif)

**Comment by diox** [comment]
This is on purpose. We require the agreement to be signed when it changes. We consider it has changed at the date of the last modification of the `post-review` waffle switch.
