### ISSUE TITLE
"Oops.." page displayed for Unlisted Queues in reviewer tools

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6468]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/editors/unlisted_queue/all logged as a reviewer

Expected results:
A list of unlisted add-ons is displayed

Actual results:
"Oops.." page is displayed

NOTES:
Reproducible on -dev too

Please see video for this bug:
![ups](https://user-images.githubusercontent.com/1583842/30701451-f874fcc0-9ef2-11e7-97dc-ee895ab1d200.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/650090/

**Comment by diox** [comment]
This looks like a consequence of having `post-review` enabled.

**Comment by vcarciu** [comment]
Verified as fixed : 
![unlisted](https://user-images.githubusercontent.com/1583842/30738110-a9a87b9a-9f91-11e7-89f7-18e3dc125094.png)
