### ISSUE TITLE
Hide lowest risk add-ons

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#6472]
Part of [#6454](https://github.com/mozilla/addons-server/issues/6454). 

Do not expose extensions within the lowest risk factor range in the review queue for technical reviewers. 

Content reviewers will still need to see these extensions in their version of the queue to reject for violations of Mozilla's [Acceptable Use Policy](https://www.mozilla.org/en-US/about/legal/acceptable-use/), but these extensions won't need a technical review. 

Depends on:

- [x] post-review going live
- [ ] determining lowest risk factor range [TBD after production]

**Comment by jvillalobos** [comment]
What is the motivation behind this one?

**Comment by caitmuenster** [comment]
This is to help prioritize higher risk add-ons for review. The other thought was that the lowest risk add-ons should be safe enough to not need manual review. 

I'm open to feedback about this.

**Comment by kewisch** [comment]
I believe this is not necessarily a requirement to update the recognition program, we can keep them in but give 0 points instead. It would be worth considering at some point though when we are confident that the automated part of the review will catch issues in low-risk add-ons.

**Comment by caitmuenster** [comment]
Agreed, this is not a blocker. I'm also happy to assign 0 points to lowest risk add-ons.

**Comment by jvillalobos** [comment]
Okay, so let's just assign no points to them and make sure reviewers are aware.
