### ISSUE TITLE
Create reporting for add-on reviewer contributions 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#6474]
Refs: #6520

Part of issue #6454. 

Set up automated quarterly reporting with reviewer's ID, reviewer's name, number of add-ons reviewed that quarter, and number of points achieved that quarter. 

Report can be formatted as a .csv or .xls file. Report should be automatically sent to Caitlin, Andreas, and Philipp.

Alternatively, the report could be automatically dropped into a Google sheet that is accessible to Caitlin, Andreas, and Philipp.

**Comment by eviljeff** [comment]
Automated _quarterly_ reporting?  How long would it take to do manually once a quarter?  Doesn't Jorge do this anyway each week and include monthly counts - you could just add them up.

**Comment by caitmuenster** [comment]
Jorge's report doesn't break down numbers by reviewer, it only provides a list of reviewers who have contributed 5+ reviews in a week. I'm also pretty leery of manual counting since it increases the chances for errors. 

If this is something that's easier to implement through a db query, that's doable (though I would need some help with the query). Automated would just make it run smoother. :)

**Comment by jvillalobos** [comment]
We shouldn't assume that we will always have direct access to the DB, so an automated report is preferable. It looks like a fairly straightforward query. As for the report's recipients, I think it's best to send it to a list. Something like `amo-admins+personas@` :D.

**Comment by caitmuenster** [comment]
👍Sweet, thanks @jvillalobos. Unless you, @wagnerand and @kewisch have any objections, I think we can set it to send to amo-admins.

**Comment by kewisch** [comment]
If you don't specifically require it to be sent to a list, you could also use redash to create the query and get live results. I'm happy to help with that if necessary. 

Of course regular reports are better for archiving purposes. In that case I'd go with amo-admins with a (different ;) tag as Jorge mentioned.

**Comment by wagnerand** [comment]
QA: This is not that easy to test manually. A simple way would be to ensure that emails go out (check FakeMail on -dev) on Monday 9:01am to `addon-reviewers AT mozilla DOT org` and addon-content-reviewers AT mozilla DOT org`. If you'd like to do a bit more thorough check, you can do some reviews before Monday and the numbers should be reflected in that email report.

**Comment by AlexandraMoga** [comment]
@wagnerand I have checked the Fake Mail log on AMO -dev but I couldn't see any report emailed to the addresses mentioned above.  But again, I had a look at our review activity for the week before (19 - 23 Nov) and there were no review actions at all, so maybe that explains it?

Probably I need to wait until next Monday to see if there will be a report sent for this week's activity.

**Comment by AlexandraMoga** [comment]
I've verified this again on Monday morning and there are two reports sent to the above mentioned reviewers' emails, with the information corresponding to the group they belong to. 

@wagnerand there are a few points that need to be clarified:

1. the report is sent as plain HTML and it seems like there are duplicated entires for the same email body - see https://addons-internal.dev.mozaws.net/en-US/admin/mail#msg-9962 . Probably this is an issue with how Fake mail renders the information though.

2. I'm not sure that the report is bringing all the add-on review activities from the past week - i.e. if I'm comparing last week's [Addon review log](https://reviewers.addons-dev.allizom.org/en-US/reviewers/reviewlog?start=2018-11-26&end=2018-12-02&search=) (excluding Content review activity) with the emailed report (see attached), I do not have the same numbers.

![image](https://user-images.githubusercontent.com/31961530/49380405-45f9a880-f71a-11e8-9a45-1884a063799b.png)

**Comment by wagnerand** [comment]
@AlexandraMoga Thanks for verifying.

> the report is sent as plain HTML and it seems like there are duplicated entires for the same email body - see addons-internal.dev.mozaws.net/en-US/admin/mail#msg-9962 . Probably this is an issue with how Fake mail renders the information though.

Yes, that is a known issue, which we don't have a good solution for. Tables in plain text emails usually don't display very well. I am not sure whether it's worth spending time on this.

> I'm not sure that the report is bringing all the add-on review activities from the past week - i.e. if I'm comparing last week's Addon review log (excluding Content review activity) with the emailed report (see attached), I do not have the same numbers.

Not all activity is being counted. For example, we only count review decisions (approval, rejection), but not other activity like reviewer replies or information requests.

**Comment by AlexandraMoga** [comment]
>Not all activity is being counted. For example, we only count review decisions (approval, rejection), but not other activity like reviewer replies or information requests.

Ok, in that case I think the report makes sense. 

I'm marking this issue as verified fixed.
