### ISSUE TITLE
Determine risk factor ranges for add-ons in post-review

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#6475]
Part of Issue #6454. 

We need to determine the range of risk factors that result in an add-on being classified as highest risk, high risk, medium risk, and low risk. 

Dependencies: 
- [x] Post review being turned on

**Comment by eviljeff** [comment]
Can you add more detail explaining what you want us to implement here?

**Comment by jvillalobos** [comment]
This is mostly a product discussion, so we can just fold this back to the issue that needs it.
