### ISSUE TITLE
Firefox download links are not localizable

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6476]
The text inside the links should be wrapped in the relevant gettext calls so they can be updated.

https://github.com/mozilla/addons-server/blob/00c3711a1a7a23921fa81cc62683c9d627ef9234/src/olympia/templates/footer.html#L13-L19

**Comment by EnTeQuAk** [comment]
This got fixed by merging https://github.com/mozilla/addons-server/pull/6477 and is heading towards -dev.
