### ISSUE TITLE
Disabling then renabling extensions mark it as "incomplete" and don't list it

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/addons-server#6478]
### Describe the problem and steps to reproduce it:

1. Uploaded addon
2. Disabled current version due to bug
3. Uploaded another version
4. Disabled that version too to test
5. Renabled the latest version from the version page after testing my addon

### What happened?

My extension: https://addons.mozilla.org/en-GB/firefox/addon/containers-theme/ was marked as "incomplete" until @jvillalobos enabled it again.
3. Made the extension public, 5 didn't.

### What did you expect to happen?

Enabling the latest version should mark the addon available to be viewed

**Comment by ValentinaPC** [comment]
Thanks for reporting!
This was also tracked in https://github.com/mozilla/addons-server/issues/3051 .

**Comment by diox** [comment]
Closing as duplicate per previous comment.
