### ISSUE TITLE
Fileviewer compare link should compare to the last manually reviewed version

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#6483]
When doing auto-approval reviews and clicking the compare link, it always compares to the last approved version by default. This can be a second auto-approved version as well. Instead, it should compare to the last manually approved version. Example:

v1 - manually approved
v2 - auto approved
v3 - auto approved

Clicking on the compare link for v3 compares with v2, instead of v1.

**Comment by kewisch** [comment]
Can we give this one a high priority? Given it is easy to miss, this blocks onboarding more volunteers.

**Comment by diox** [comment]
Should it take into account *confirmed* auto-approvals though ? At the moment we don't record that info outside of the log...

In the following situation, what should the compare link for v3 compare:
v1 - auto approved (confirmed by a human reviewer)
v2 - auto approved
v3 - auto approved

**Comment by kewisch** [comment]
Yes, it should. Essentially, we want to review all changes since it was last looked at by a human, so this also includes confirmed auto-approvals.

In the situation you've mentioned, it should also compare v1 to v3

**Comment by diox** [comment]
Ok, so we need to add a `confirmed` boolean flag on `AutoApprovalSummary` and record confirmation in that field when it happens. Then filter on that when presenting file compare links (handling situation where a version has *not* been auto-approved at all gracefully)

This is not trivial, probably won't happen before next week's push.

**Comment by diox** [comment]
QA note: we are not handling confirmations that were made before the fix, so if you want to test this, you need to submit and wait for auto-approval of a new version.

**Comment by vcarciu** [comment]
Verified as fixed with:

Case 1:
v1 - manually approved
v2 - auto approved
v3 - auto approved

Case 2:
v1 - auto approved (confirmed by a human reviewer)
v2 - auto approved
v3 - auto approved

In both cases v1 was compared with v3:
![comparemanualapproval](https://user-images.githubusercontent.com/1583842/30872051-8584e7fe-a2f1-11e7-90aa-cedcca0de10b.png)
