### ISSUE TITLE
Cleanup our |datetime, |babel_datetime and |babel_date template filters

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6485]
* `|babel_date` is unused as far as I can tell, might need more verification
* `|babel_datetime` and `|datetime` template filters should be ported to django's `|date` template filter

Something like

```python
from django.template import defaultfilters

@register
def format_date(value, format='DATE_FORMAT'):
    return defaultfilters.date(value, format)

@register
def format_datetime(value, format='DATETIME_FORMAT'):
    return defaultfilters.date(value, format)
```

luckily we don't have any specific time filters in use as far as I can tell but that's worth investigating more too.

Or should we just use https://github.com/python-babel/django-babel#using-the-template-tags instead of Django's house tools? We are using django-babel mostly for extraction-reasons but not much beyond that. Babel's date/time formatting capabilities are highly superior to what Django provides though so maybe it's worth just using that? I usually can't decide where to start, simplicity first, use Django unless we need more powerful tools?

cc @eviljeff @diox for discussion

**Comment by EnTeQuAk** [comment]
Depending on the outcome of our discussion this could be a `contrib: welcome` bug

**Comment by EnTeQuAk** [comment]
We are using babel formatting for `currencyfmt` and `numberfmt` apparently. All that should be replaced by their equivalent wrapper from django babel imho. Separate issue?

**Comment by eviljeff** [comment]
I lean towards using Django's filters, unless we know we need the extra complexity in django-babel.  It's one less thing to tie as a site wide (well, soon to be site-frontend) run-time dependency.

**Comment by eviljeff** [comment]
currencyfmt looks like it's just used for contributions, so that'll be gone soon.

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by eviljeff** [comment]
mentor me

**Comment by harry-7** [comment]
I would like to take this up.  Would be glad if someone guides me on what needs to be done to fix this. Thanks :)

**Comment by eviljeff** [comment]
You need to remove the `babel_datetime` `babel_date` and `datetime_filter` methods in olympia/amo/templatetags and replace them with the simple method @EnTeQuAk suggested above (just `def format_datetime` is enough for our current needs).  
Register it with `@library.filter(name='datetime')` for a nicer name, and less template changes.  Then change all the .html templates that use `|babel_datetime` with `|datetime`.  Then test as many pages as you can think where there is a date shown :)

There is a slight complication, in that some (10 occurrences) of the `|datetime` filters use a custom format string (e.g. `'%B %e, %Y %H:%M:%S'`) and the syntax used is different - our current `|datetime` filter uses python's [strftime so is C style](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior); whereas django's date filter we want to use instead is based on [PHP codes](https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#date).  Once you've got everything set up and running and basics done above we'll decide what to do about them.  Some we can maybe drop, others will need converting.

**Comment by harry-7** [comment]
@eviljeff Okay will start working on them. From the things mentioned above I did not quite understand what this meant ?
> Register it with @library.filter(name='datetime') for a nicer name, and less template changes.

**Comment by eviljeff** [comment]
if you see the `datetime_filter` method, it does it there.

**Comment by harry-7** [comment]
@eviljeff  I pushed some changes and tested some of them. They seem to work fine . But however some of the tests are failing. How should I fix them ?

**Comment by eviljeff** [comment]
Looks like they're breaking due to differences in the format of the date string - somewhat expected as the custom format strings haven't been changed.
It has highlighted how much of a mess our usages are though - e.g. our current `|datetime` filter defaults to a date-only format, rather than a date&time format.  They need to be changed in the templates to be `|date` instead, and we will need a `def format_date` after all.  I'll comment in the pull request.

So... I don't know if you want to narrow down this issue to _just_ our existing `|datetime` usages, and deal with `babel_datetime` as a follow-up issue.
