### ISSUE TITLE
Prevent random users from profiting off of unclaimed Contribute (PayPal.me) URLs

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6489]
To quote @jvillalobos :
Make the Contributions URL clickable (opens in new tab) in the Edit page, when it's set. That should encourage devs to try it out. I don't see other concrete actions to do.

Original filed issue (that we decided not to do) for reference:
--------------------------------------------------------------------------------------------
### Describe the problem and steps to reproduce it:

As a developer, enter a `paypal.me/my-addon` URL to receive contributions

### What happened?

Devhub lets you enter an unclaimed URL. You may not know that this URL needs to exist and be claimed by you.

### What did you expect to happen?

The Devhub should report an error if the URL has not been claimed.

### Anything else we should know?

If the `paypal.me` URL has not been claimed then the first person who sees it can claim it for themselves. This would redirect funds to that person's account and the original developer may not be aware.

For example, here's what it would look like if you try to contribute to an add-on for which a developer has configured an unclaimed `paypal.me` URL:

1. Click the Contribute button:

<img width="947" alt="screenshot 2017-09-22 11 33 28" src="https://user-images.githubusercontent.com/55398/30755956-19617530-9f8e-11e7-969a-00d33cf4a60d.png">

2. PayPal says the URL is unclaimed and asks if you want to claim it:

<img width="796" alt="screenshot 2017-09-22 11 31 36" src="https://user-images.githubusercontent.com/55398/30755964-23831000-9f8e-11e7-8e03-05d992eb635d.png">

3. Click Grab This Link to claim it for yourself

![screenshot-2017-9-22 get your very own paypal me link](https://user-images.githubusercontent.com/55398/30755996-40f5150c-9f8e-11e7-9cee-93cde7f94c8c.png)

4. Profit.

**Comment by jvillalobos** [comment]
Beyond making the text around the Contributions URL input clearer (without being specific about any payment provider), I don't think we should do anything else. This isn't a heavily-used feature, and it shouldn't be common for developers to enter an invalid URL, given its importance to them.

We have the tooltip and the help text explaining the domain restrictions. I'm open to suggestions for changing the text in either or both.

**Comment by EnTeQuAk** [comment]
I agree with @kumar303 here, typos unfortunately happen more often than we'd like to admit and not everyone does indeed check that the end-result works. The real problem here is that verifying that this link actually worked is not easily done, PayPal returns a `200` and relying on some HTML code to be present makes that verification quite brittle. I don't see any way to use the API to verify it but I might be bad at searching, PayPal docs are pain.

**Comment by muffinresearch** [comment]
I agree that typos can happen, but the ownus here is on the developers to check their data.

What we **_can_** reasonably do is make the documentation and any help text as clear as possible. 

It may also be useful to have the UI  for setting the link provide a test link after update so the developer is literally prompted to test their payment hookup after making changes.

**Comment by eviljeff** [comment]
@jvillalobos can you update the issue to confirm/clarify what we need to do here, or close otherwise?

**Comment by jvillalobos** [comment]
I like Stuart's suggestion. Let's make the Contributions URL clickable (opens in new tab) in the Edit page, when it's set. That should encourage devs to try it out. I don't see other concrete actions to do.

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
mentor me

**Comment by CuriousLearner** [comment]
@kumar303 @eviljeff I've raise a PR for this :)

**Comment by vcarciu** [comment]
@eviljeff @jvillalobos 

From " Let's make the Contributions URL clickable (opens in new tab) in the Edit page, when it's set. That should encourage devs to try it out. I don't see other concrete actions to do." I understand that the url should be clickable in Edit Basic information section, where the Contribution url is set, but this is not happening. 

Please confirm me that I correctly understand the issue before re-opening it.

**Comment by eviljeff** [comment]
agreed, that's not working 😿

**Comment by CuriousLearner** [comment]
I've tested the changes locally. 

Also, I've found that another commit had Circle CI failed because of ImportError for `scandir`, but I could already found it in dev requirements.

**Comment by eviljeff** [comment]
server has been updated

**Comment by vcarciu** [comment]
Verified as fixed : 
![contriblink](https://user-images.githubusercontent.com/1583842/37046197-67518eba-2170-11e8-8bd4-3c38ed7f46f4.gif)
