### ISSUE TITLE
Add JSON export of replacement data

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6495]
The TAAR service needs data from the replacements table. We currently have a mapping of guid -> path. The data TAAR needs is guid -> guid.

Assuming getting at the data isn't too problematic it would ideal if there was a way to export the source / replacement guid data as JSON. This could either be an export in the admin or as an API.

From talking to @jvillalobos I don't think there's a reason that we can't make the replacement data public.

**Comment by muffinresearch** [comment]
@eviljeff do you think this would be reasonably straight-forward to implement?

**Comment by eviljeff** [comment]
The path->guid could get messy.  The path is just that - a path on AMO.  It might be a path to a single valid add-on (that we have to parse into an add-on without a request going through the middleware), but it might also be a path to collection of multiple add-ons (or a path to another page on AMO, or just invalid).

Export in the admin - is this a one-off task?

**Comment by muffinresearch** [comment]
> Export in the admin - is this a one-off task?

It's something we would want to get every 1/2 weeks.

**Comment by muffinresearch** [comment]
> The path->guid could get messy. The path is just that - a path on AMO. It might be a path to a single valid add-on (that we have to parse into an add-on without a request going through the middleware), but it might also be a path to collection of multiple add-ons (or a path to another page on AMO, or just invalid).

I think we'd only want a guid -> guid for a exact replacement, we definitely can't have a guid when collections are used or it's not pointing a details page.

**Comment by eviljeff** [comment]
I'm going to do an API at `api/v3/addons/replacement-addon/` it will be a standard List response of `{'guid': 'old@guid', 'replacement': 'new@guid'}` results, wrapped in standard pagination.

**Comment by Dexterp37** [comment]
FWIW, the [format of the file](https://github.com/mozilla/taar/blob/master/tests/test_legacyrecommender.py#L5-L9) we use in taar supports multiple replacement GUIDs for each legacy GUID.

```
{
 "legacy-guid-1": ["replacement-guid1", "replacement-guid2", ...].
 "legacy-guid-2": [...],
}
```

The idea is to use this recommendation strategy for about one year or more, depending on the 57+ release uptake.

**Comment by eviljeff** [comment]
okay, I can include collections too then.

@Dexterp37 Is an API response of the following okay:
```
{
"page_size":25,
"count":2,
"next":null,
"previous":null,
"results":[
  {"guid":"bbbbbbb@","replacements": ['gui1@', 'guid2@']},
  {"guid":"foo@baa","replacements":null}]
}
```
Or do you want it in that exact format?

**Comment by Dexterp37** [comment]
Thanks @eviljeff , I think this format is fine. Will the API report all the available mappings or should we query all the legacy addons ourselves?

**Comment by eviljeff** [comment]
I was going to have it return all mappings, paginated (default is 25 mappings per page but I can override that if you want a larger number).  
If you want a detail endpoint that would respond to a particular guid that's doable too.

**Comment by Dexterp37** [comment]
Nope, all mappings is perfectly fine, thanks!

**Comment by mlopatka** [comment]
Is it possible to have a one-off JSON export of current guid->guid mappings ASAP to act as a stand-in for future weekly generated jobs so that we can beta-test TAAR?

I am trying to avoid inconsistencies in the recommendations TAAR makes versus the substitutions recommended by the "find a replacement" button in discovery-pane.

**Comment by eviljeff** [comment]
> Is it possible to have a one-off JSON export of current guid->guid mappings 

That's going to be difficult unfortunately as it's not stored as guid -> guid, but guid -> path in the database.  The API I'm writing will parse the path, look up the add-on or collection, and then return the guid(s).  

It's done, btw, just working out some test fails so it will be our Oct 5th deployment.  (Could be cherry picked for this week's if you really need it - speak to @muffinresearch about that)

> future weekly generated jobs

It will be an API using the live data.  Could even be queried in real-time, if you could live with the response time.

**Comment by mlopatka** [comment]
@muffinresearch ^^ it would be really amazing if we could cherry-pick this week's JSON as per @eviljeff 's suggestion. This would unblock TAAR's beta testing before launching in the SHIELD infrastructure.

**Comment by muffinresearch** [comment]
@mlopatka yep we can pick it, once it's through review, landed and looks good on -dev. /cc @eviljeff

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this. Thanks!

**Comment by eviljeff** [comment]
it's tricky to QA, because it's only an API with JSON output, but essentially `https://addons-dev.allizom.org/api/v3/addons/replacement-addon/` should return what's in `http://addons-dev.allizom.org/en-US/admin/models/addons/replacementaddon/`.

The difference is rather than the path to the replacement add-on that you enter in django admin, the API should return the guid of the replacement addon. (guid is shown in devhub edit listing in technical details as uuid)

If the path is to a replacement _collection_ then it should be a list of the guids of the add-ons in that collection.

**Comment by ValentinaPC** [comment]
Content of above 2 pages match in what concerns the JSON output and the replacement add-ons.
Checked each option from AMO-dev. Added a new replacement add-on and it was also added in the JSON output.
Link from Add-ons Manager redirects as expected.
![2017-10-10_1205](https://user-images.githubusercontent.com/15685960/31380376-dca8be48-adb9-11e7-940c-3746e481c7a5.png)
![2017-10-10_1252](https://user-images.githubusercontent.com/15685960/31380382-df609110-adb9-11e7-9f00-a3cae74651c4.png)

Marking this verified-fixed.

**Comment by mlopatka** [comment]
updated uris for addon replacements retrieval:
https://addons.mozilla.org/api/v3/addons/replacement-addon/
