### ISSUE TITLE
Tidy up Collections models, DB, code once frontend pages launch

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6496]
Collection models currently include a number of features that the simplification of collections [[PRD](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit)] drops.  After addons-frontend launches collections pages we should drop all unused properties in the model and database, and supporting code.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/8944 will drop most features we no longer need, this issue can be used to properly remove the tables from the database once the obsolete models & fields are gone from the code.

**Comment by diox** [comment]
Things that can now safely be dropped in a migration:

Tables:
* `collection_subscriptions`
* `collections_votes`
* `stats_addons_collections_counts`
* `stats_collections_counts`
* `stats_collections`

Columns:
* `users.display_collections_fav`
* `collections.rating`
* `collections.downvotes`
* `collections.upvotes`
* `collections.monthly_subscribers`
* `collections.downloads`
* `collections.subscribers`
* `collections.weekly_subscribers`

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/10053 will also drop the `collections.icontype` column.
