### ISSUE TITLE
Auto-approval can be confirmed more than once per version

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#6497]
**STR**:
1) upload version for auto-approval
2) confirm auto-approval
3) confirm auto-approval again on the same version

**Result**:
There are two messages that auto-approval has been confirmed

**Expected**:
It should not be possible to select `Confirm Auto-Approval` in the review actions after a version has already been confirmed, similar to how before it is not possible to approve again after the version has been approved.

**Other**:
In a similar situation: I'm somewhat open to how rejecting should be handled for already confirmed versions. Before post-review, a reviewer could not reject a version that had already been approved. Going by this, a reviewer should not be able to reject a version that has already been confirmed. Admins were able to correct the status by hand using the admin manage feature.

I'm not sure what @jvillalobos imagined here, maybe the rejection case is a feature. The approval case I started out with seems like a bug to me though.

**Comment by jvillalobos** [comment]
Double confirmation shouldn't impact the add-on or the developer, so I don't see it as a big problem. It could be useful in the future if we wanted to double-check old approvals and log it in some way (in a crazy world where we have time to spare for this).

For the rejection case I think we can keep it as it is. Confirmed add-ons shouldn't show up in the queue, so a reviewer rejecting something that has already been confirmed is probably a case where an issue is found for an add-on later on and is determined to be rejection-worthy. I'd like us to rely less on admins having to do the work in such cases.

If there are no objections, I think we can close this.

**Comment by kewisch** [comment]
I'm fine with keeping the rejection case as is.  We need to make sure this doesn't lead to inconsistent rejections, but this is a matter of training.

> Double confirmation shouldn't impact the add-on or the developer, so I don't see it as a big problem. 
This will become a "problem" when we give points for confirming an add-on. Reviewers might misuse this by confirming add-ons that have already been confirmed, either by themselves or by others. Unless it is non-trivial to make this change, I'd rather remove the tab to confirm if it has already been confirmed.

**Comment by jvillalobos** [comment]
> Unless it is non-trivial to make this change, I'd rather remove the tab to confirm if it has already been confirmed.

That's fine with me.
