### ISSUE TITLE
Reviews are no longer locked when being viewed

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#6499]
**STR**:
1) reviewer A visits a review page for an add-on (e.g. through one of the queue pages)
2) reviewer B opens the queue

**Expected**:
* There should be a lock icon in all queues the add-on appears in, both auto-approval and e.g. updates.

**Result**:
There is no lock icon

**Other info**:
I'm not quite sure if the issue is with the ping not being sent, or the lock icon just not being shown. Here a few anecdotal situations:

* When @emerald2k is viewing a review page from the updates queue after I have closed it, he does get the pings sent, but I don't see the lock icon
* When I am viewing the same page (no matter if he has closed or not), I don't see any pings in the network monitor, nor does the lock icon appear.

**Comment by diox** [comment]
The auto-approved queue does not show the lock icon (it was not implemented there), but it should work in all other queues. Is this really broken for all queues or just missing in auto-approved queue?

Note that you can see if a particular add-on is truly locked by going to its review page (though it will lock it for you if it's not already locked)

**Comment by kewisch** [comment]
Both @emerald2k and I went to the same review page (linked from the updates queue) and neither of us see the review lock notification on the review page, so it seems to be broken.

Aside from that, would it take much to implement this on the auto approval queue as well? Especially if we instruct reviewers to take from the top, the lock is important.

**Comment by diox** [comment]
It should be straightforward to implement in the auto-approval queue.

I just checked and it's definitely working for me on dev (XHR is going out, and I can see the lock icon in the queue and the warning in the review page if I use another account in a private window)... No idea what's going on in your case...

**Comment by diox** [comment]
> It should be straightforward to implement in the auto-approval queue.

Actually, I was wrong, it *is* implemented for auto-approved queue already (just confirmed on dev).

**Comment by kewisch** [comment]
This was something very strange with my profile. Works fine on a new profile, therefore closing issue.
