### ISSUE TITLE
[i18n] Separate different usages of the word "featured"

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozilla/addons-server#6500]
### Describe the problem and steps to reproduce it:
The term "featured" is used around 10 times and in several different contexts. In my language it is not appropriate for a category to be "featured" the same way as the add-on is. It is gender incompatible, it is wrong in terms of sequence of tenses (you get the picture).
### What happened?
There is only one string that is used site-wide.
### What did you expect to happen?
To have separate strings for every usage so that the translator have the opportunity to use correct meaning for his locale.
### Anything else we should know?
https://pontoon.mozilla.org/en-GB/amo/all-resources/?search=featured&string=63947

**Comment by kumar303** [comment]
Hi, thanks for the bug report. Could you provide a more specific example? Are you saying that you cannot conjugate something like [No featured add-ons in {0}](https://pontoon.mozilla.org/en-GB/amo/all-resources/?search=featured&string=64549) because you don't know the gender of the category that gets inserted into `{0}`?

**Comment by StoyanDimitrov** [comment]
Rereading the description I realize it's not clear enough. I'm sorry about that.
What I've wrote is related to the linked string only. It is used in the popout menu of categories, as well as some sort of badge in the add-on. In my language category is differenr fender than add-on. So one string for both uses makes the translation illogical.

**Comment by eviljeff** [comment]
fwiw, this issue probably needs to be moved/replicated in addons-frontend.  I think the majority of references will be in non-developer/reviewer pages

**Comment by muffinresearch** [comment]
Moved to https://github.com/mozilla/addons-frontend/issues/3520
