### ISSUE TITLE
UnicodeDecodeError exception when signing

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6507]
We got this `UnicodeDecodeError` in `signing_clients` :
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/650895/

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcd in position 13: invalid continuation byte
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "olympia/editors/management/commands/auto_approve.py", line 92, in handle
    self.process(version)
  File "django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "olympia/editors/management/commands/auto_approve.py", line 127, in process
    self.approve(version)
  File "olympia/editors/management/commands/auto_approve.py", line 151, in approve
    helper.handler.process_public()
  File "olympia/editors/utils.py", line 520, in process_public
    sign_file(file_, settings.SIGNING_SERVER)
  File "olympia/lib/crypto/packaged.py", line 137, in sign_file
    cert_serial_num = unicode(call_signing(file_obj, endpoint))
  File "olympia/lib/crypto/packaged.py", line 70, in call_signing
    log.debug(u'File signature contents: {0}'.format(jar.signatures))
  File "signing_clients/apps.py", line 332, in signatures
    self._sig = Signature([self._sign(f) for f in self._digests],
  File "signing_clients/apps.py", line 315, in _sign
    digests = _digest(str(item))
  File "site-packages/six.py", line 865, in <lambda>
    klass.__str__ = lambda self: self.__unicode__().encode('utf-8')
  File "signing_clients/apps.py", line 146, in __str__
    return entry.decode('utf-8')
  File "encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
```

This is particularly bad because it crahes `auto_approve`, blocking auto approvals.

**Comment by diox** [comment]
The affected add-on: https://addons.mozilla.org/en-US/editors/review/%E6%97%BA%E9%94%80%E7%8E%8B

**Comment by diox** [comment]
The offending add-on was manually rejected, `auto_approve` is temporarily unstuck, downgrading to p2

**Comment by EnTeQuAk** [comment]
can we ask the developer to re-zip that package? Somehow filenames are encoded with GB2312 which is something zip does not support per spec and python falls back to utf-8. Why `zipinfo` (bash tool) does the right thing (https://gist.github.com/EnTeQuAk/cf4f45ee19bf6026e09c226ef67adef5) is unknown to me… probably tries to detect something somehow, I don't know yet...

**Comment by diox** [comment]
Failing at the linter level sounds like a good idea, but I worry that some developers will be super confused and left without options...

**Comment by EnTeQuAk** [comment]
true, but repackaging a zip and magically sanitizing filenames doesn't feel right to me either tbh...

**Comment by diox** [comment]
We definitely should not be repackaging it. Can Firefox cope with it ?

**Comment by EnTeQuAk** [comment]
It can't get installed because it has an invalid manifest.json (which apparently was not catched by the linter but afaik there's an issue about warning about unknown keys)

And even with that removed I get an error in the browser console:

```
1506493786976	addons.xpi	WARN	Invalid XPI: [Exception... "Could not convert Native argument arg 0 [nsIUTF8StringEnumerator.getNext]"  nsresult: "0x8057000a (NS_ERROR_XPC_BAD_CONVERT_NATIVE)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: loadManifestFromZipReader :: line 923"  data: no] Stack trace: loadManifestFromZipReader()@resource://gre/modules/addons/XPIInstall.jsm:923
```

Unpacking the zip locally throws this serror:

```
file #15 (images/旺销王logo.png):
         mismatch between local and central GPF bit 11 ("UTF-8"),
         continuing with central flag (IsUTF8 = 0)

warning:  Unicode Path checksum invalid
images/旺销王logo.png:  mismatching "local" filename (images/���������logo.png),
         continuing with "central" filename version
```

Maybe that's something we can adapt and check against? Still this might leave developers confused without options...

so apparently it seems to me that Firefox can't cope with that zip either. Repackaging the add-on get's me further and stops installation at a missing signature but doesn't complain about the zip anymore.

**Comment by diox** [comment]
Let's try to catch that in the linter and throw a hard error then, no need to try to handle it more gracefully.

**Comment by EnTeQuAk** [comment]
> Let's try to catch that in the linter and throw a hard error then, no need to try to handle it more gracefully.

Jupp, I'll file an issue. Might not be easy to do but we'll see.

**Comment by diox** [comment]
Another one https://addons.mozilla.org/en-US/editors/review/%E5%A4%8D%E6%9D%82%E5%AF%86%E7%A0%81%E7%94%9F%E6%88%90 :(

**Comment by EnTeQuAk** [comment]
short status update: I have a working experiment in the linter but that still proves to be a not-so-great idea. I'd go ahead and do the verification in addons-server for now, since we can properly detect it by blowing up via the python zip module.

**Comment by EnTeQuAk** [comment]
Fixed via https://github.com/mozilla/addons-server/commit/8990d60f71d467efd3cf9dfe21675bbd679b1fb3

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa:not needed" ?
