### ISSUE TITLE
auto_approve should not attempt to approve locked add-ons

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6509]
`auto_approve` knows about reviewer locks (even sets up its own when doing work) but when `post-review` is enabled it does not respect them. That sucks, it'd be a nice workaround for when it's stuck on an add-on (see #6507)

**Comment by diox** [comment]
It would also be useful if it skipped add-ons for which a super review has been asked maybe?

**Comment by ValentinaPC** [comment]
Is this in -dev yet?
Because I've just checked and event if the page is locked, the webext get auto-approved.
![locked_](https://user-images.githubusercontent.com/15685960/30861161-8884c790-a2d2-11e7-817e-5a88e3c9c8e6.png)

**Comment by diox** [comment]
@ValentinaPC I'm not sure addons-server was deployed when you checked. Could you re-test with a new add-on now?

**Comment by ValentinaPC** [comment]
@diox : Re-tested on AMO-dev FF55(Win 7).
Webextension is not auto-approve while being locked by a reviewer, but....if webextension contains a CSP or any other rule which in the past blocked the auto-approval, those are also listed.
Is this ok? Shouldn't we only list the "locking" part? not to confuse the reviewer...or the developer.
Please see screenshot:
![lock](https://user-images.githubusercontent.com/15685960/30863930-f0c5304e-a2da-11e7-866e-3c6e98451cfd.png)

**Comment by diox** [comment]
I agree it's confusing... not a huge deal, but yeah it's a valid edge-case... can you open a new issue for this? *technically* this one is fixed, the locking works.

**Comment by ValentinaPC** [comment]
Marking this as verified fixed on AMO-dev FF55(Win 7) based on above comments. 
Logged https://github.com/mozilla/addons-server/issues/6515.
