### ISSUE TITLE
Remove post-review waffle, except in reviewer tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6510]
post-review is live. We should remove usage of the waffle everywhere, except in reviewer tools for the time being. This will give us an off switch when `auto_approve` is having issues while not altering devhub pages etc.

**Comment by diox** [comment]
In particular we should modify `User.has_read_developer_agreement()` so that it does not use the post-review waffle switch modified date anymore, and instead use 22 September 2017 17:38 UTC as the date (it's the date it went live).

**Comment by diox** [comment]
QA:

This is just re-testing things that were validated before:

- Auto approvals should still work
- Developer Agreement should be presented to users that validated it before 22 September 2017 17:36 UTC at upload time or when they visit the API keys page, and never again afterwards

**Comment by vcarciu** [comment]
@diox : I visited the https://addons-dev.allizom.org/en-US/developers/addon/api/key/ , revoked credentials and then tried to upload a new add-on, but I was not asked about Developer Agreement. Is this expected?

**Comment by diox** [comment]
@vcarciu with a new account or an old one? Had you seen the agreement page before with that account?

**Comment by diox** [comment]
What's the account id/email? If you saw it before today but after when switched on post-review, then it's normal you were not asked to agree again.

**Comment by vcarciu** [comment]
@diox  : carcium@gmail.com . From your description, I thought that after visiting the API key , the Developer Agreement is displayed again.

**Comment by diox** [comment]
Ah, non. It's just that visiting the API Key page and uploading a new add-on/version both trigger the check. You still won't see it if you already read it after it was last changed.

**Comment by diox** [comment]
(That account read the dev agreement on September 26th, so it's normal that you don't see it again)

**Comment by vcarciu** [comment]
@diox  : thanks!
Also, I can confirm that Developer Agreement is needed for an user who validated it before 22 September. Auto approvals are still working. Marking bug as verified.
