### ISSUE TITLE
Add logging around disabling/deleting/re-enabling add-on versions

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#6516]
We were just reviewing https://addons.mozilla.org/en-US/editors/review/norton-identity-safe and for some reason the confirm approval didn't go through and it ended up in a state where the approved version is rejected. 

Now it is unclear if the developer disabled the version, or if there was a bug. In debugging with @diox we saw only an entry that the current version changed in the logs, but not why.

It would be good to get more information in the logs to better debug cases like this in the future.

**Comment by diox** [comment]
Note: we should add both `log.info()` or `log.debug()` statements and `ActivityLog`. In a similar vein, double-check which reviewer tools actions don't have `log.info()` statements.

**Comment by ValentinaPC** [comment]
First I though that we need to track an activity log for these actions - but while accessing Admin Tools - Fake mails log page - no tracking there, except while deleting the entire add-on.
Second I looked in Reviewer Tools - Add-on Review log page to see if there is some tracking there, but nothing there either.

Could you please add some STR for us to check the correct place for this, or the label "qa: not needed"? Thanks!

**Comment by diox** [comment]
There should be some activity logging done when you enable/disable versions in devhub. You can then see those activities when looking at the "View Recent Changes" link from the sidebar in an add-on developer pages.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
1. Changes around an add-on version are tracked in the "Recent Activity" section from manage My Submission page, until the add-on is deleted. After this actions made before add-on deletion are also erased, are we ok with this?
![changes](https://user-images.githubusercontent.com/15685960/31124646-0564fbce-a84e-11e7-98e5-ad1b36c2d21e.png)

2. Changes are also tracked in "View Recent Changes" accessed from add-on manage page
![bun](https://user-images.githubusercontent.com/15685960/31124672-2981ec24-a84e-11e7-8890-a5765bc13f1f.png)

3. Page "Recent Activity for My Add-ons" - https://addons-dev.allizom.org/en-US/developers/feed still looks bad.
![toolong](https://user-images.githubusercontent.com/15685960/31124794-9d5d631c-a84e-11e7-982b-5dc41aff7a28.gif)

**Comment by diox** [comment]
1. We shouldn't be erasing anything. Can you link the add-on(s) ?
3. This is nothing new, it's just because you have a ton of add-ons.

**Comment by ValentinaPC** [comment]
> We shouldn't be erasing anything. Can you link the add-on(s) ?
I cannot help you in this case...because the add-on was deleted. :)

> This is nothing new, it's just because you have a ton of add-ons.
I know is not new, just seeking for a solution :)

**Comment by diox** [comment]
> I cannot help you in this case...because the add-on was deleted. :)

Ah, but yeah, nevermind, we don't show deleted add-ons activity in the recent changes in devhub. So that's fine.
