### ISSUE TITLE
Color weights in auto-approved queue

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6518]
Refs: #6520

The auto-approved queue lists add-ons sorted by their weight, which is a calculation of their risk. #6473 defines 4 ranges for those weights: highest risk, high risk, medium risk, low risk. They should appear differently in the queue so it's easy for reviewers to identify their importance and point value. This can be done by coloring the numerical value in the `Weight` column:

- Highest risk: red.
- High risk: yellow.
- Medium risk: green.
- Low risk: black.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshots:
![collors](https://user-images.githubusercontent.com/15685960/31779103-faa009a4-b4fa-11e7-806b-837cac32ab31.png)
![2017-10-19_1824](https://user-images.githubusercontent.com/15685960/31779108-fd3c1676-b4fa-11e7-97f4-2064c21ec089.png)

**Comment by diox** [comment]
I guess that's a question for @wagnerand
