### ISSUE TITLE
File viewer broken on AMO for RES 5.8.6

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#6519]
Was viewing RES version 5.8.6 and marked it as approved. File viewer only shows three files;
![image](https://user-images.githubusercontent.com/607379/30884637-a91c8d60-a310-11e7-8555-5ed7249977ee.png)
Diff with the previous version shows all files except these three being deleted, validation results are not modified but most file references are broken.
https://addons.mozilla.org/developers/addon/reddit-enhancement-suite/file/727847/validation
https://addons.mozilla.org/en-US/firefox/files/compare/727847...723738/

**Comment by EnTeQuAk** [comment]
Assigning this to me to debug this.

**Comment by EnTeQuAk** [comment]
Error in kibana log: 

`Error unzipping: [Errno 39] Directory not empty: '/mnt/efs/addons.mozilla.org/shared_storage/tmp/file_viewer/0926/727847' :/data/olympia/src/olympia/files/templatetags/jinja_helpers.py:105`

with the following flow following before that line:

![screenshot from 2017-09-27 08-21-01](https://user-images.githubusercontent.com/139033/30898685-da80a494-a35c-11e7-8549-313747fedf8c.png)

So the workflow looks fine but maybe we're running into network delays again? Not sure... 

Imho this is very similar to https://github.com/mozilla/addons-server/issues/5394 and https://github.com/mozilla/addons-server/issues/4148

**Comment by rctgamer3** [comment]
RES 5.8.6 is back to normal.

**Comment by EnTeQuAk** [comment]
jupp, this usually happens once the file-viewer caches get invalidated after an hour afair. The issue didn't get fixed yet though.

**Comment by erosman** [comment]
Content/Compare fails to show the files:

Add-on:
```
https://reviewers.addons.mozilla.org/editors/review/518894/
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/861375/
https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/861375...418581/
```

**Comment by EnTeQuAk** [comment]
Closing this as part of https://github.com/mozilla/addons-server/issues/8220
