### ISSUE TITLE
Unified Reviewer Dashboard

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6522]
Part of #6520. As specified in [this document](https://docs.google.com/document/d/1R3uSejL43pjUgMQUy4GxxlNb3pl1XB5cOJ-p3CP4eZc/edit#), we want a reviewer dashboard that serves as a landing page for the different reviewer groups that exist now and will exist in the near future. This will make it easier to support content reviewers in Q4 and to separate user review moderation from add-on reviews.

These are the main tasks required here:

- [ ] Create a new reviewer dashboard under `/reviewers/` and redirect the existing theme and editor dashboard URLs to it.
- [ ] The announcement (MOTD) is shown for all reviewers.
- [ ] The dashboard will be divided by sections per review permission, and only the sections you have permission to will be displayed.
- [ ] Each section has links to the tools relevant to that permission.
- [ ] Clean up header for all reviewer tools: remove toolbar menu, remove search box, remove Add-ons/Themes selector.
- [ ] (Optional) Paths for all reviewer tools are unified under `/reviewers/`.

It's not a requirement to implement this in the new front-end, so it can be done in whatever way is most convenient.

**Comment by diox** [comment]
Should those be kept on the dashboard:
- Current waiting times for new add-ons / updates
- Leaderboards: Total Reviews, Reviews This Month, New Reviewers
- Moderated ratings log
- Link to "Performance"
- Link to logs (Add-on Review Log, Moderating ratings logs, Signed beta files logs)

Same questions for things appearing on the current themes dashboard:
- Recent Points, Top Reviewers (past 7 days), All Time
- Total Reviews, Reviews This Month
- Link to logs (Reviews, Deleted)

**Comment by jvillalobos** [comment]
The [links section](https://docs.google.com/document/d/1R3uSejL43pjUgMQUy4GxxlNb3pl1XB5cOJ-p3CP4eZc/edit#heading=h.kh9j19zdq1qn) in the doc specifies which links to include in each section of the dashboard. I think that covers the links to performance and logs.

The stats and leaderboards are going away for now. We'll bring them back once we know what we want to show each reviewer type. That's something I need to discuss a bit more with @caitmuenster.

**Comment by diox** [comment]
I created https://github.com/mozilla/addons-server/issues/6937 to separate the dashboard itself from the rest of the tasks. Once it has been implemented, tested etc, I can proceed with the rest.

**Comment by diox** [comment]
This is blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1417866, I'll ping ops about it.

**Comment by AlexandraMoga** [comment]
Verified on AMO dev with FF57 Win 10
Here are my comments:


> Create a new reviewer dashboard under /reviewers/ and redirect the existing theme and editor dashboard URLs to it.

Works as expected. The user can access the new dashboard by going to Tools -->Reviewer tools or by direct link to https://reviewers.addons-dev.allizom.org/en-US/reviewers/

> The announcement (MOTD) is shown for all reviewers.

@diox Here I have a question: Shouldn't the Announcement section be visible to all reviewers, regardless of the group they belong to? For example, I've created a new user and included him in the Content review group but the Announcement section was not displayed on the dashboard. Also, in the old tools, an announcement preview was displayed when reviewers accessed a certain queue. Does this no longer apply?
![image](https://user-images.githubusercontent.com/31961530/33323373-fb580904-d454-11e7-936f-ba4ea4038214.png)


> The dashboard will be divided by sections per review permission, and only the sections you have permission to will be displayed.

this is working as expected (i.e. if the user has Content review permissions, he will only see this section on the dashboard)

> Each section has links to the tools relevant to that permission.

corresponding links are displayed for each section

> Clean up header for all reviewer tools: remove toolbar menu, remove search box, remove Add-ons/Themes selector.

New 'clean' header
![image](https://user-images.githubusercontent.com/31961530/33321905-ff491990-d44f-11e7-92bf-d9f186cc24f1.png)


> (Optional) Paths for all reviewer tools are unified under /reviewers/.

navigation inside Reviewer tools is done under /reviewers/ (former /editors/)

**Comment by diox** [comment]
> @diox Here I have a question: Shouldn't the Announcement section be visible to all reviewers, regardless of the group they belong to? For example, I've created a new user and included him in the Content review group but the Announcement section was not displayed on the dashboard. Also, in the old tools, an announcement preview was displayed when reviewers accessed a certain queue. Does this no longer apply?

I actually haven't changed the behavior of the announcement: it should be displayed on all reviewer pages, unless dismissed, regardless of permissions.

**Comment by AlexandraMoga** [comment]
1. Based on the specification, I understood that all reviewer groups should see the Announcement section on the dashboard
Below is a screenshot showing the dashboard for a user that has Content review and Unlisted queue permissions but the Announcement menu is not displayed. 

![image](https://user-images.githubusercontent.com/31961530/33326106-a63dbf9c-d45c-11e7-8bed-c7ca0d1dc6b8.png)

2. Regarding the announcement preview, it was displayed once the message has been updated, so I suppose there's no issue here.

![image](https://user-images.githubusercontent.com/31961530/33326535-e9ce52fc-d45d-11e7-9a27-78ea8b99b551.png)

**Comment by diox** [comment]
When logged in with the user that does not see the motd, can you open the web console and give me the result of `z.Storage().get('motd_closed')` ?

**Comment by AlexandraMoga** [comment]
is this result the one you're asking for?

![image](https://user-images.githubusercontent.com/31961530/33328444-b21e63f6-d462-11e7-9000-22fc22738b88.png)

**Comment by diox** [comment]
Yes. Now I understand what's going on :) You've already dismissed the announcement on dev (maybe using a different user : it doesn't matter, it's stored independently in your browser storage), that's why you are not seeing it. If you clear stored data in your browser (or use a different container/profile/browser) you'll see it again.

**Comment by AlexandraMoga** [comment]
I think I failed to properly explain my first issue regarding Announcements. What I'm trying to point out is that the user who has some reviewer permissions (i.e Content, Unlisted add-ons) will not have access to the Announcement section (i.e. is not able to edit the message to be displayed). Below is a comparison between a user who has all permissions and the other with partial permissions:

![image](https://user-images.githubusercontent.com/31961530/33330073-8c88ae22-d466-11e7-9237-d0b9fddfe508.png)



> The announcement (MOTD) is shown for all reviewers.

does this specification refer only to the actual message being displayed at the top of the page, or to the ability of each reviewer group to update the message in the announcement?

**Comment by diox** [comment]
Ah.

The message being displayed at the top for everyone is enough, the announcement *section* is just for admins, to give them a link to change it.

**Comment by AlexandraMoga** [comment]
Great. This clarifies my initial misunderstanding. 

About the small issue in the Themes section mentioned above, would you prefer it to be logged separately?

> One small issue here: for consistency, 'Themes" should start with an upper letter

![image](https://user-images.githubusercontent.com/31961530/33331137-77ecb050-d469-11e7-9154-4f94a322a56e.png)

**Comment by diox** [comment]
I'll fix it right away, no need for a new bug.

**Comment by AlexandraMoga** [comment]
This can now be marked as verified fixed

![image](https://user-images.githubusercontent.com/31961530/33365740-d5c30a20-d4f1-11e7-814b-d872b2dd94bc.png)
