### ISSUE TITLE
My addon disappeared

### ISSUE THREAD

**Issue by plneappl** [mozilla/addons-server#6528]
### Describe the problem and steps to reproduce it:
Yesterday I uploaded an addon, today it still appears in the search, but I can no longer access it; neither through a saved link nor through the search.
Addon: 
[link](https://addons.mozilla.org/en-US/firefox/addon/streamlink-firefox-helper/)
[Source code](https://github.com/plneappl/streamlink-firefox-helper/)

**Comment by diox** [comment]
Your add-on has been rejected by a reviewer. You should have received an email about it, and you should be able to see the reason in the developer hub.
