### ISSUE TITLE
Remove concept of HIDDEN_LANGUAGES

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6534]
We don't have the l10n dashboard anymore so we should just make languages available whenever they are available via Pontoon / as .po files.

We have a -dev and -stage concept for people to review strings and deploying weekly gives translators enough time to improve translations incrementally.

Also, no idea who decides when a language get's promoted so let's save all that hassle and just promote all languages :)

**Comment by EnTeQuAk** [comment]
I mean… according to https://l10n.mozilla-community.org/webstatus/?product=addons-server this kinda makes sense but then again this doesn't.

@jvillalobos @muffinresearch @diox @eviljeff any opinions about that? I'd vote for simplifying all the things and just forwarding all translations we have to end-users to encourage people translating. I assume addons-frontend doesn't have a mechanism that promotes languages based on completion either right?

**Comment by EnTeQuAk** [comment]
Note to myself: We're limited to what mozilla-product-details supports for what we can enable vs what we have as .po files though. But it still makes sense to sync that list.

**Comment by eviljeff** [comment]
I can't see any reason why we'd keep it around (though I can't remember exactly why we had 'hidden' languages in the first place).  If we do want to 'hide' certain localisations based on completeness then we should probably find a way of doing that programmatically, imo (not sure if that's practical to calculate from the .po files on deploy).

**Comment by eviljeff** [comment]
re: mozilla-product-details -  should we / can we actually sync these up?  Is there a real penalty to having locales available that are very incomplete (or completely incomplete)?

**Comment by jvillalobos** [comment]
I'm not familiar with this. Has the list of hidden languages changed in the past months / years? If it hasn't, can we just remove those partial translations instead of publishing them? It sounds like they're far from complete and not being looked at?

I also like the idea of calculating completeness and using that as a criteria for publication, but maybe it's too much work.

**Comment by EnTeQuAk** [comment]
>  If we do want to 'hide' certain localisations based on completeness then we should probably find a way of doing that programmatically, imo (not sure if that's practical to calculate from the .po files on deploy).

We could steal from pontoon or that api that I posted to calculate things.

> re: mozilla-product-details - should we / can we actually sync these up? Is there a real penalty to having locales available that are very incomplete (or completely incomplete)?

What do you mean? Add more languages to product details or the other way around? In that PR I synced all our .po files, hidden languages with what we have available in product details and used that as the new status quo (funny side fact: nothing changed, probably because product details doesn't change that frequently).

I don't see any penalty of being very incomplete except that people of certain locales might be encouraged to help translating it. Although we could add some more incentives for them in that regard since currently there's just no information on how to do that directly on AMO. I'm only guessing that from UX perspective a completely untranslated page is better to look at than something partially translated.

**Comment by eviljeff** [comment]
>> re: mozilla-product-details - should we / can we actually sync these up? Is there a real penalty to having locales available that are very incomplete (or completely incomplete)?

> What do you mean? 

Set up something that keeps the list of languages the same as with product_json.  But if it almost never changes then probably no point in doing it.

**Comment by ValentinaPC** [comment]
Please add some STRs for us to check this or the label "qa: not needed". Thanks!
