### ISSUE TITLE
Language Tools API should return an add-on slug as well as full URL

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6539]
The AMO API for Language Tools returns only the full URL for language packs and dictionaries (http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#language-tools), but it would be useful for the front-end to get back just the slug for the add-on as that's how we tend to build URLs (this matters for React).

Could we get just the slug in the responses back from this endpoint?

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
