### ISSUE TITLE
Caching of API responses

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6544]
Webpage test running on the new frontend pointed out that our API responses aren't cacheable and for that tool, the definition of  "cacheable" is related to not having either a Max-Age or Expires header set.

This issues is to discuss if we should consider making any change to headers sent in API responses  or if we're happy with the status quo.  This might be something that would be different depending on the resource e.g. if there's something that infrequently changes then setting a max-age might be relevant, but for frequently changing content it might not. This could make the difference between the browser needing to make any requests versus making one that might result in 304 or a 200.

If the answer is that we're already doing what we need to do, then that's fine and we can close this out - the purpose of this bug is just to discuss what we have and whether there's any room for improvements.

Refs:  https://github.com/mozilla/addons-frontend/issues/3274

**Comment by diox** [comment]
I had already filed https://github.com/mozilla/addons-server/issues/2663 a while ago but never got around to do it. I'll close it to discuss it here. We need to decide on some kind of strategy for this.

We can probably return a 5 minutes max-age on all `GET` requests, if the client is aware of it. And even bump that to one hour on things like the homepage. Just need to make sure it does not create incoherencies when the client is posting or editing something (obvious case that comes to mind is user reviews)

**Comment by diox** [comment]
Yeah we do have basic `ETag` support and obey `If-None-Match` though django's middleware. The question is, what kind of `max-age` do we want...

**Comment by EnTeQuAk** [comment]
> The question is, what kind of max-age do we want...

That might be different for every endpoint imho. 5 minutes probably works for all the things but I doubt 10 or 15 minutes will be a deal-breaker for things like browsing add-ons etc. Speaking of unauthenticated read-only requests here, we might want different rules for authenticated users, e.g to give developers the "oh, it got published, click, yeaaah, there it is" experience.
