### ISSUE TITLE
Return (paginated) add-ons along with the detail of a collection

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6548]
The API exposes a detail endpoint to fetch a single collection: https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#detail. Yet, it does not expose the add-ons part of this collection, only metadata about it. There is a second endpoint to fetch the add-ons for a given collection though: https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-add-ons-list.

The problem is that to retrieve and display a collection, the frontend has to send two queries. Would it be possible to have a query parameter to include the add-ons along with the metadata?

Something like this or with `?with-addons`:

```
GET /api/v3/accounts/account/<user>/collections/<collection>/?includes=addons
```

It should return the same JSON as the [collection add-ons list](https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-add-ons-list) in a new attribute (`items`?). I also think this endpoint should also support pagination.

Thanks!

**Comment by eviljeff** [comment]
copy of the irc chat pre- the issue being filed:

> 17:41 @willdurand eviljeff: would it make sense to have a "?with-addons" or "?includes=addons" in the collection detail API? https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#detail. I have to send 2 requests to display a collection page right now. I did not see this pattern in the API though, so just asking
> 
> 18:19 @eviljeff Andrew Williamson willdurand: it's possible. Generally we don't try to combine detail responses with lists of stuff that could need pagination but if it's a performance bottleneck it's doable.
> 18:19 that said, I guess there are a number of pages that need multiple requests (add-on page, for example) so is it a problem? Hmm. mat, cgrebs, kumar: opinions?
> 
> 18:21 @kumar303  eviljeff: willdurand: there are a couple other pages where we need to load data with two API requests per page. We should probably wait until we finish our initial release then take a step back and look at all the pages that require multiple API requests.

**Comment by eviljeff** [comment]
Is this still a post-release task, or do you need this adding before the MVP in November?

There are a few different ways we could add this, depending on whether it's purely single collection (detail view, not list); if only read-only is needed, or write too.   Whether this is going to be a pattern used for other API endpoints that have a similar hierachy (Addons, Accounts, etc)

**Comment by willdurand** [comment]
I think it can be done post release. I have implemented the feature on the frontend calling the two endpoints.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF58 (Win10x54)

I've sent the following request and both collection meta-data and add-on details were returned:
```
https://addons-dev.allizom.org/api/v3/accounts/account/AlexandraMoga1/collections/try-again/?with_addons
```
There was no pagination implemented after all, as far as I understood from your [discussion](https://github.com/mozilla/addons-server/pull/7546)
