### ISSUE TITLE
Cleanup 'Staff' group permissions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6556]
On stage, the Staff group has the following permissions:

`['Addons:Review', 'Apps:Review', 'Personas:Review', 'Reviews:Edit', 'Addons:Edit', 'Addons:Configure', 'Users:Edit', 'Stats:View', 'CollectionStats:View', 'Collections:Edit', 'AdminTools:View', 'SeniorPersonasTools:View', 'Apps:Configure', 'AccountLookup:View', 'AppLookup:View', Lookup:View', 'FeaturedApps:View', 'FeaturedApps:Edit', 'Stats:View', 'Apps:ReviewPrivileged', 'Apps:Publisher', 'Apps:ReviewRegionCN', 'Addons:ReviewUnlisted', 'Addons:PostReview', 'Addons:ViewDeleted']`

That's a lot of rules! Some of them are obsolete (the `Apps:` ones) and some could be written in a more generic way ([according to @jvillalobos](https://github.com/mozilla/addons-server/pull/6532#discussion_r141954595) we should be able to replace all the `Addons:` ones with `Addons:*`)

**Comment by jvillalobos** [comment]
Updated the permissions in the 3 environments:

`Addons:*,Admin:Tools,Collections:Edit,CollectionStats:View,ReviewerAdmin:Tools,Reviews:Edit,Stats:View,Users:Edit,Ratings:Moderate,ReviewerTools:View`
