### ISSUE TITLE
Remove internal API endpoints

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6568]
The internal API endpoints (`/api/v3/internal/`) were set up for the new Admin Tools living in addons-frontend. Those tools were [removed a while ago](https://github.com/mozilla/addons-frontend/issues/2373) but at the time we kept the endpoints, figuring they could be useful for debugging for instance.

However since they require either re-using a token or implementing a client with proper login flow (no other authentication mechanisms are enabled for these endpoints), they are not practical to use - and nobody has built anything on top of them, AFAIK. Plus #6448 proved how confusing it can be to keep old APIs around, so let's just remove them.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
