### ISSUE TITLE
Retroactively award reviewer points for post-review/content-review actions 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6570]
Once #6473 lands we'll need to retroactively award reviewer points for post-review/content-review actions that were made before the rewards were added.

This will probably be a one-off task that digs into `ActivityLog`s and call `award_points()` accordingly.

**Comment by diox** [comment]
@caitmuenster 

There are 4 different actions that should award points if we consider content review:
- Confirming an auto-approval
- Rejecting multiple versions
- Approving Content
- Rejecting multiple versions (for content-only reasons)

One of them, Rejecting multiple versions, is difficult to isolate in the history, because the only thing I can use to award the points retroactively are the activity logs, and "reject multiple versions" does not have its own activity log id.

Adding points for the other 3 is straightforward, but it's going to take me a lot more time to do it for this particular action, so... is it a problem or can we ignore it?

**Comment by caitmuenster** [comment]
Ok, that makes sense. Let's enable the three straightforward ones.

**Comment by erosman** [comment]
What is "Approving Content"?!

**Comment by diox** [comment]
It's a [Content Review](https://github.com/mozilla/addons-server/issues/6310) action.

**Comment by diox** [comment]
QA: ping me when you're about to test this. It requires a command to be ran manually.

**Comment by ValentinaPC** [comment]
@diox - ping :)
Also, how should we test this?
Making the 4 actions and see the points...where?
Thanks in advance!

**Comment by ValentinaPC** [comment]
@diox: Should we try this again?
You said something about, checking this again after fixing https://github.com/mozilla/addons-server/issues/6473#event-1290460551 , if I remember correct.

**Comment by diox** [comment]
I'll mark it as verified, as we ended up running it in prod yesterday (from the logs I have, it seems to have run without issues) and it was a one-off task.
