### ISSUE TITLE
Implemention of Static Themes in existing Addon models

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6574]
[Tracker mozilla/addons/issues/501]

Rambling dump-o-thoughts:

Static Themes are packaged as a webextension, with a JSON manifest, but have a specific 'theme' property, which identifies them as a theme.  An add-on can't be both an extension and a theme (an extension can use the _theme API_ instead, but that's regarded as an extension, rather than a theme).

There are a variety of ways we indicate "types" of things in olympia, and store extra data, currently:
- LWT are `Addon.type == amo.ADDON_PERSONA`, but also have an extra Persona model attached to Addon
- XUL themes are `Addon.type == amo.ADDON_THEME` and don't have extra data in the model
- Standard extension Webextensions are `File.is_webextension is True`, but `Addon.type == amo.ADDON_EXTENSION`
- Webext langpacks are `File.is_webextension is True`, and `Addon.type == amo.ADDON_LPAPP`

So, one possible implementation is Static Themes as `Addon.type = amo.ADDON_THEME`, with  `File.is_webextension is True`.  This is similar to how langpacks were implemented.

But Static Themes are supposed to more the successor to LWT than XUL themes, and it's unlikely there will be any XUL theme->Static Theme upgrades by developers.  Static Themes as `Addon.type = amo.ADDON_PERSONA` is problematic because LWT have weird statuses, weird extra data, weird handling of File & Version objects, and are generally weird compared to extensions.  LWT->Static Theme upgrades are envisioned in the future, though possibly only after we've one-way converted all LWT to Static Themes.

Creating a new Addon type and having `Addon.type = amo.ADDON_STHEME` (or similar) could be a lot cleaner, at the expense of recreating/changing more stuff.  (And us having 3 different types of theme at once!)

Alternatively we could look to a cleaner future when everything is `File.is_webextension is True` and everything is `Addon.type == amo.ADDON_EXTENSION` and represent it's a Static Theme with some other property on Addon or File (or Version)

**Comment by eviljeff** [comment]
@diox @EnTeQuAk for their own thoughts

**Comment by diox** [comment]
Yeah this is tough. On the one hand, I agree that the new type would be cleaner. On the other, that means touching a lot of code : I'm not sure how we want them to behave in devhub (more like how we currently handle extensions, or how we currently handle personas?) and reviewer tools (with extensions in the "regular" reviewer tools, or separated like personas?)

It's probably best to bypass the `Persona` stuff, so I'm leaning towards the new type. (wild suggestion that is probably a terrible idea, but I have to say it: you could also re-use `ADDON_THEME` while setting `File.is_webextension` to `True` ...)

**Comment by eviljeff** [comment]
> I'm not sure how we want them to behave in devhub (more like how we currently handle extensions, or how we currently handle personas?) and reviewer tools (with extensions in the "regular" reviewer tools, or separated like personas?)

Product havn't created any issues (only long, possibly partially obsolete, PRDs) so I'm not sure - the read I get is they are the 'replacement' for personas, so be treated like them for review (though being entirely different means either a new review tool, or adding something to the extension review tools to approve them); for devhub I'm working on the assumption they'll be like extensions.

> It's probably best to bypass the Persona stuff, so I'm leaning towards the new type.

It's the cleanest... but yeah, a lot of code will need touching.

> (wild suggestion that is probably a terrible idea, but I have to say it: you could also re-use ADDON_THEME while setting File.is_webextension to True ...)

We think the same terrible ideas 😆 :
>>So, one possible implementation is Static Themes as Addon.type = amo.ADDON_THEME, with File.is_webextension is True

**Comment by EnTeQuAk** [comment]
I am actually leaning towards the `is_webextension is True` + `type = amo.ADDON_THEME` idea and at the same re-declaring `amo.ADDON_THEME` (current XUL add-ons) with a different type (`ADDON_LEGACY_THEME` or so) which might touch even more code I suppose but imho represents the add-on type more exactly (being a regular webextension plus a bit theme fuzz on top of it).

On the other hand I do see the reasoning behind a separate type… I just wonder if for them `is_webextension` would be true too? Given that looking at personas themes are historically handled quite different to how regular extensions are that could prove difficult too. Especially since right now `is_webextension` is used entirely under the assumption of targeting add-ons so there might be queries here and there that might need an explicit `type` added. Or not, not sure, just thinking loud.

**Comment by jvillalobos** [comment]
To answer the product-ish questions:

* Submission should be handled like extensions (with the caveat that we will also offer the simplified upload form theme designers currently use).
* Dev Hub should be handled like extensions. Won't be pretty, but hopefully we'll improve this next year.
* Review should be handled like lwt.
* Listing should be handled like lwt, in that the listing has a prominent preview image. They should appear like lwt in search and use the same categories.

The general goal is to drop all the special-casing we do for lwt, eventually.

Another thing to keep in mind: at some point in the future we'll want to migrate existing lwt to static themes, and this means we'll need to expose some static themes as lwt for a period of time.

**Comment by eviljeff** [comment]
I'm going to go with a new type `ADDON_STATICTHEME` because categories are going to be different than `ADDON_THEME` and it might make some other differences easier to implement too (e.g. reviewing).
(Though switching the names is a good idea... though I'd do that beforehand in a separate pull)

Thanks for inputs.
