### ISSUE TITLE
Ability to filter auto-approved add-ons by columns

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#6575]
Title; just like the current new submissions and updates, it would be useful to sort (asc/desc) by title/last human review date/flags/weight

**Comment by wagnerand** [comment]
I don't see how this is useful. What is the expected gain?

**Comment by wagnerand** [comment]
We haven't heard back on the reasoning why this is useful. Feel free to reopen when you have time to elaborate.
