### ISSUE TITLE
Add-on is Android compatible but does not have an Android install file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6576]
### Describe the problem and steps to reproduce it:

I'm not sure how to reproduce this. 

**UPDATE**: see https://github.com/mozilla/addons-server/issues/6576#issuecomment-334090810

### What happened?

I have seen several add-ons that are marked as Android-compatible yet do not have an install file for either all-platforms or for the Android platform.

Here is an example of an API response from https://addons.allizom.org/api/v3/addons/addon/webext-no-platf/ : 
[webext-no-platf.json.zip](https://github.com/mozilla/addons-server/files/1353661/webext-no-platf.json.zip)

Its current version says it is compatible with Android:

```
      "compatibility" : {
         "android" : {
            "min" : "48.0",
            "max" : "*"
         },
         "firefox" : {
            "min" : "48.0",
            "max" : "*"
         }
      }
```

but it does not have an `android` file. It has a `mac` and `linux` file only.

### What did you expect to happen?

This version should not be marked as compatible with Android

### Anything else we should know?

https://addons.allizom.org/en-US/firefox/addon/webext-no-platf/

**Comment by diox** [comment]
To reproduce:
- Upload an add-on for Firefox only
- Edit its version and set the file to any platform other than "all" or "android"
- Add "Firefox for Android" as an application

We should prevent developers from doing this. I'm not sure to what extent, though. Maybe don't allow editing platform/apps entirely? Is there another way to end up in this situation without editing?

**Comment by kumar303** [comment]
I've been duping a few bugs related to this and I just saw that it's affecting Privacy Badger which is a high profile add-on: https://www.reddit.com/r/firefox/comments/75azzo/i_cant_download_privacy_badger_on_firefox_android/

What can we do to fix the missing install files?

I verified that Privacy Badger's current version does not have an Android file. `https://addons.mozilla.org/api/v3/addons/addon/privacy-badger17/`

**Comment by diox** [comment]
The quickest way to fix this is probably to only keep one single file compatible with "All" platforms. The problem is, we don't know what was the intent - why didn't the developer allow the "All" platform? Was it deliberate? Does it actually work with all platforms or not?

**Comment by eviljeff** [comment]
I suspect STR could be:
* upload a webextension and don't change Application or Platform (so it defaults to All; Desktop and Android)
* Change the file in edit version to be Mac (or something other than All or Android)

i.e. they didn't _add_ the application - we did

**Comment by kumar303** [comment]
Here are a few notes:
* The legacy AMO mobile site used to display these add-ons on Android as incompatible
* The new AMO mobile site shipped with a bug that let the user install these add-ons anyway by just serving them the first file and hoping for the best
* A change was released around Sep 28th where these add-on pages broke (the install button was enabled but it caused a JS error). No error was displayed to the user.
* In https://github.com/mozilla/addons-frontend/issues/3266 we will release a fix where these add-on pages show up as incompatible on Android

**Comment by kumar303** [comment]
btw, 13k users on Firefox Mobile have tried within the last week to install an add-on lacking an Android file. https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/656097/

**Comment by diox** [comment]
More info: from https://github.com/mozilla/addons/issues/348#issuecomment-302791236 it's clear that the support for Android was /not/ intended in Privacy Badger. https://github.com/mozilla/addons-server/issues/4868 also has more info about the mess that is created by having Android added by default like @eviljeff mentions a few comments above this one.

**Comment by diox** [comment]
So, we should do something about this. Something like:
- Fixing https://github.com/mozilla/addons/issues/348, re-organizing the checkboxes in the initial submission step to make it clear whether you want to enable Android or not. The trick is that it needs to also work for version upload
- For existing versions, if there is no file for `all` or `android`, remove `android` application support & compatibility information

**Comment by eviljeff** [comment]
>     Fixing mozilla/addons#348, re-organizing the checkboxes in the initial submission step to make it clear whether you want to enable Android or not. The trick is that it needs to also work for version upload

Agreed.  Part of the problem is knowing what the correct UX is though - do we default Android off and Desktop on?  do we force the developer to select Applications?  Hide the platforms by default to stop developers from changing them?  
https://github.com/mozilla/addons-server/issues/4868 is a semi-dupe also.

**Comment by kumar303** [comment]
I found another one today on production while browsing the site in Android. It was on the front page in the *trending* section.


<details>
  <summary>Show output

`$ curl 'https://addons.mozilla.org/api/v3/addons/addon/seznam-pro-firefox-esko/' | jq .current_version`

</summary>

```
{
  "id": 2222950,
  "compatibility": {
    "android": {
      "max": "*",
      "min": "55.0"
    },
    "firefox": {
      "max": "*",
      "min": "55.0"
    }
  },
  "edit_url": "https://addons.mozilla.org/en-US/developers/addon/seznam-pro-firefox-esko/versions/2222950",
  "files": [
    {
      "id": 764078,
      "created": "2017-11-08T14:36:56Z",
      "hash": "sha256:10f953f927aa7e7f9d17b07c29857a2fc2d2f01c39a46017a731b8c648e13ed9",
      "is_restart_required": false,
      "is_webextension": true,
      "is_mozilla_signed_extension": false,
      "platform": "linux",
      "size": 2351964,
      "status": "public",
      "url": "https://addons.mozilla.org/firefox/downloads/file/764078/seznam_pro_firefox_esko-4.0.7-an+fx-linux.xpi?src=",
      "permissions": [
        "<all_urls>",
        "geolocation",
        "management",
        "nativeMessaging",
        "storage",
        "tabs",
        "webNavigation",
        "http://sbrowser.dev/*",
        "https://www.seznam.test/doplnky*",
        "https://www.seznam.cz/doplnky*"
      ]
    },
    {
      "id": 764079,
      "created": "2017-11-08T14:36:56Z",
      "hash": "sha256:2933825a337d125509b61c25c4f60b8c7e5a70c9c1a0e2ae82dc438e99d8f50c",
      "is_restart_required": false,
      "is_webextension": true,
      "is_mozilla_signed_extension": false,
      "platform": "mac",
      "size": 2351967,
      "status": "public",
      "url": "https://addons.mozilla.org/firefox/downloads/file/764079/seznam_pro_firefox_esko-4.0.7-an+fx-mac.xpi?src=",
      "permissions": [
        "<all_urls>",
        "geolocation",
        "management",
        "nativeMessaging",
        "storage",
        "tabs",
        "webNavigation",
        "http://sbrowser.dev/*",
        "https://www.seznam.test/doplnky*",
        "https://www.seznam.cz/doplnky*"
      ]
    },
    {
      "id": 764080,
      "created": "2017-11-08T14:36:56Z",
      "hash": "sha256:b79f4ab9ba7ef61022f767845de0e039be95652930646ec03b51ab12f7373a12",
      "is_restart_required": false,
      "is_webextension": true,
      "is_mozilla_signed_extension": false,
      "platform": "windows",
      "size": 2351964,
      "status": "public",
      "url": "https://addons.mozilla.org/firefox/downloads/file/764080/seznam_pro_firefox_esko-4.0.7-an+fx-windows.xpi?src=",
      "permissions": [
        "<all_urls>",
        "geolocation",
        "management",
        "nativeMessaging",
        "storage",
        "tabs",
        "webNavigation",
        "http://sbrowser.dev/*",
        "https://www.seznam.test/doplnky*",
        "https://www.seznam.cz/doplnky*"
      ]
    }
  ],
  "is_strict_compatibility_enabled": false,
  "license": {
    "id": 18,
    "name": {
      "el": "Άδεια BSD",
      "vi": "Giấy phép BSD",
      "ca": "Llicència BSD",
      "it": "Licenza BSD",
      "cs": "BSD licence",
      "eu": "BSD Lizentzia",
      "sv-SE": "BSD-licens",
      "id": "Lisensi BSD",
      "es": "Licencia BSD",
      "ru": "Лицензия BSD",
      "nl": "BSD-licentie",
      "en-US": "BSD License",
      "fr": "Licence BSD",
      "bg": "BSD Лиценз",
      "de": "BSD-Lizenz",
      "da": "BSD-licens",
      "fa": "مجوز BSD",
      "hu": "BSD licenc",
      "pt-PT": "Licença BSD",
      "sr": "БСД лиценца",
      "sq": "Leje BSD",
      "ga-IE": "Ceadúnas BSD",
      "sk": "Licencia BSD",
      "zh-CN": "BSD 授权"
    },
    "url": "http://www.opensource.org/licenses/bsd-license.php"
  },
  "release_notes": null,
  "reviewed": "2017-11-08T14:40:41Z",
  "url": "https://addons.mozilla.org/en-US/firefox/addon/seznam-pro-firefox-esko/versions/4.0.7",
  "version": "4.0.7"
}
```

</details>

**Comment by muffinresearch** [comment]
Summoning @jvillalobos for input on this based on https://github.com/mozilla/addons-server/issues/6576#issuecomment-335896575

**Comment by jvillalobos** [comment]
What I would like to do in Dev Hub eventually is that Android support is handled by a global flag (per add-on, instead of per-version), and it's off by default. Currently, I would favor switching the submission flow so that Android is off by default, since that's the most likely scenario.

**Comment by EnTeQuAk** [comment]
So, this more or less has been fixed by https://github.com/mozilla/addons-server/pull/9362 but before closing this, does this issue involve changing existing add-ons too? Given that we're going away from "platform" towards "compatibility apps" and you can't change the platform for a file afterward anymore I feel like this may have been properly addressed?

**Comment by jvillalobos** [comment]
Won't it be a problem if add-ons still have multiple files? Or are we just picking one of the files and sticking to it?

**Comment by diox** [comment]
To fix it for existing add-ons we need to extra files, yeah. I think just picking one at seemingly random is ok, in 99% of the case they are dupes.

**Comment by jvillalobos** [comment]
Agree. I think there's also a query that we can run to find the few cases where the files don't match and then we can warn devs about it.
