### ISSUE TITLE
Disco Pane content update - Octo. 2017

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#6577]
For the **19 October** push, please REMOVE:

- New Tab Override  
- LanguageTool Grammar Checker 

... and REPLACE them with uBlock Origin and Search Image:

**Block ads** with [uBlock Origin by Raymond Hill](https://addons.mozilla.org/firefox/addon/ublock-origin/)
A lightweight and effective ad blocker. uBlock Origin enforces thousands of content filters without chewing up a bunch of memory.

**Easily find images** with [Search Image by Didier Lafleur](https://addons.mozilla.org/firefox/addon/search-image/)
Highlight any text and right-click to quickly perform an image search. 

REMOVE all current themes and REPLACE them with:

All Fall by [MaDonna](https://addons.mozilla.org/firefox/addon/all-fall/)

Snub Nosed Dog by [Bátja](https://addons.mozilla.org/firefox/addon/snub-nosed-dog/)

Butterfly Fantasies by [SassyGirl1016](https://addons.mozilla.org/firefox/addon/butterfly-fantasies/)

Full page content ordering should appear as such:

All Fall
uBlock Origin
Enhancer for YouTube
Snub Nosed Dog
Search Image
Emoji Cheatsheet
Butterfly Fantasies

@muffinresearch @diox

**Comment by EnTeQuAk** [comment]
These changes should be landed on Oct 11th.
