### ISSUE TITLE
Incorrect message in Add-on Validator page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6580]
Steps to reproduce:
1. Log in to AMO-stage
2. Access Validator page from Dev Hub https://addons.allizom.org/en-US/developers/addon/validate
3. Observe the message under the page title

Expected results:
No note about this working only for legacy add-ons.

Actual results:
Message about the tool working only for legacy add-ons is displayed.

Notes/Issues:
- maybe this was added by mistake in https://github.com/mozilla/addons-server/issues/5950. 
Verified on AMO-stage FF56(Win 7). Issue is on -stage, dev and prod.
Screenshot:
![webext](https://user-images.githubusercontent.com/15685960/31166174-7fb34a54-a8f6-11e7-8c29-3f87a3af69f9.png)

**Comment by diox** [comment]
mmm yeah it should only be applied to https://addons-dev.allizom.org/en-US/developers/addon/check-compatibility, not https://addons-dev.allizom.org/en-US/developers/addon/validate ...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshot:
![validator](https://user-images.githubusercontent.com/15685960/31213241-372eda92-a9ae-11e7-9795-0a5dabb014a0.png)
