### ISSUE TITLE
services/* files don't get flake8 checked

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6582]
Everything in src/ is flake8 checked by travis, so lets make sure files in services don't contain horrible syntax too.

**Comment by eviljeff** [comment]
QA - this touches the code called in Firefox to check for updates for add-ons and personas and we certainly don't want that to break.  However, there are no functional changes in the code, so there _shouldn't_ be any changes.

**Comment by vcarciu** [comment]
It looks like check for updates is not working anymore on -dev and Stage : 
![update](https://user-images.githubusercontent.com/1583842/31451550-107aec2c-aeb5-11e7-9265-19e7008b08c1.gif)

**Comment by vcarciu** [comment]
Check for updates is not working anymore on -dev and Stage : 
![update](https://user-images.githubusercontent.com/1583842/31451805-c4880f2e-aeb5-11e7-9061-e889524e70e8.gif)

**Comment by vcarciu** [comment]
Verified as fixed. Extensions were updated to latest version
