### ISSUE TITLE
Add paypal.com to list of allowed payment providers

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6585]
Please add Paypal (paypal.com) to the list of allowed providers in the new contributions feature (#6069). We already support paypal.me because I thought it was _the_ way to use Paypal for this, but per [this discourse post](https://discourse.mozilla.org/t/upcoming-changes-to-contributions-on-amo/17734/35) it's also possible to use paypal.com, apparently with some added flexibility for the recipient.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshots:
![2017-10-11_1248](https://user-images.githubusercontent.com/15685960/31433677-b52c216a-ae82-11e7-9399-8dba4809f052.png)
![2017-10-11_1249](https://user-images.githubusercontent.com/15685960/31433678-b54e7846-ae82-11e7-85e7-13254c736b43.png)
Corresponding page is loaded while clicking on the "Contribute" button from add-on details page.

**Comment by oeekker** [comment]
This now also works on production server of amo.
![paypal com contributions url](https://user-images.githubusercontent.com/1092048/31996785-0e0d5d50-b98a-11e7-8874-ca3d542b7da5.png)
