### ISSUE TITLE
Return GUIDs for language-tools API endpoint

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6586]
Because of how we structure our data in redux reducers on the front-end, it would be really handy to get just a tiny bit more consistency in the language-tools API data. (https://github.com/mozilla/addons-frontend/pull/3288#discussion_r142681513)

If we could get the GUIDs for every add-on returned by this endpoint it would help us a lot. It would also allow us to eventually allow installs right from the listing page which would be cool!

**Comment by eviljeff** [comment]
Anything else you need for consistency?  Just guid?

**Comment by tofumatt** [comment]
I think just GUID is good; between that and the current_version we could hook up an install right from the page in the future.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or add the "qa : not needed" label?
