### ISSUE TITLE
Compare does not pick up the Last Human Review

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#6593]
**project: auto approval**

Example:
```
https://addons.mozilla.org/editors/review/812838/
https://addons.mozilla.org/en-US/firefox/files/compare/734239...647615/
```

It seems the compare picked up v1.4.1 to compare with, while the last human review was v1.5.2

Version 1.4.1 · May 14, 2017 · Approved By Andreas
Version 1.5.0 · July 25, 2017 · Deleted
Version 1.5.1 · July 26, 2017 · Approved By Mozilla
Version 1.5.2 · July 30, 2017 · Approved By erosman
Version 1.6.0 · September 2, 2017 · Approved By Mozilla
Version 1.7.0 · September 30, 2017 · Approved By Mozilla

**Comment by wagnerand** [comment]
This sounds like https://github.com/mozilla/addons-server/issues/6483 which has been fixed already.

**Comment by diox** [comment]
This was indeed fixed in #6483 but it was too difficult to backfill data for auto-approvals made before that push.

**Comment by erosman** [comment]
Has the push already been made?
It is still picking the wrong version.

**Comment by diox** [comment]
As I said, we didn't backfill data for previous auto-approvals, so it will only work for approvals made *after* that push.
