### ISSUE TITLE
Add-on Review Log should show action description for content approve/reject actions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6602]
Originally reported in https://github.com/mozilla/addons-server/issues/6310#issuecomment-334395413 but this deserve its own issue cause I'd like to fix it by doing some refactoring to avoid the issue for future actions as well.

STR:
- Approve or reject content for an add-on
- Go to review log, see your action

Expected Result:
- You should see what kind of action you did like "Content approved" or "Content Rejected"

Actual Result:
- You see only the add-on name and version in the "Event" column for those actions.

**Comment by ValentinaPC** [comment]
Verified as fixed in AMO-dev FF56(Win 7).
Postfix screenshot:
![rej-app](https://user-images.githubusercontent.com/15685960/31385007-1a26c08e-adca-11e7-8e51-54c538c46887.png)
