### ISSUE TITLE
Search via v3 api raises too_complex_to_determinize_exception

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6604]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/385995/

```
TransportError: TransportError(500, u'search_phase_execution_exception', u'too_complex_to_determinize_exception: Determinizing automaton with 22645 states and 36695 transitions would result in more than 10000 states.')
(7 additional frame(s) were not displayed)
...
  File "rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "rest_framework/pagination.py", line 214, in paginate_queryset
    self.page = paginator.page(page_number)
  File "olympia/api/paginator.py", line 56, in page
    result = self.object_list[bottom:top].execute()

TransportError: TransportError(500, u'search_phase_execution_exception', u'too_complex_to_determinize_exception: Determinizing automaton with 22645 states and 36695 transitions would result in more than 10000 states.')
```

To be honest, I have no idea where that comes from and how to solve it and the interwebs isn't very helpful either.

**Comment by diox** [comment]
It seems to be caused by a specific query. Sentry seems to truncate it, but it looks like `ppppppppppppppppppppppppp0pppppppppppppppppppp0pppppppppppppppppppppppppppppppppppppppppppppppppppppp`. I wonder how long it actually is...

**Comment by EnTeQuAk** [comment]
So that sounds like something like https://github.com/mozilla/addons-server/issues/5443 and we should just start to remove support for unlimited length 🤔

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/645767/

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/641832/

**Comment by diox** [comment]
If the query is super large, we return a `HTTP/1.1 414 Request-URI Too Large`. If the query is not that large, we support it, up to a point where it returns a 500.

We should add a limit to the `q` parameter in the search API, something like 100 chars.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed".
Thanks!

**Comment by diox** [comment]
Re-opening because it's still happening in sentry despite the character limit: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/645767/

The following query appears to have triggered it:
`览器附加组件搜索：firebug 下载第一个 安装 这时候右上角会出现一个甲虫的标志 点开点击cookies 开`

The limit helped reduce the number of occurences though, so I'm removing the priority.

**Comment by diox** [comment]
@EnTeQuAk can you take another look? This started to happen after the ES5 upgrade, and the query limit is not enough... maybe we need to be more careful with some clauses, like don't do fuzzy if the query is too large, that kind of stuff.

**Comment by diox** [comment]
Also happening with `.com von qavai  export gpx-track from strava.com experimentellexperimentell zu firefox hinzufü`.

**Comment by EnTeQuAk** [comment]
Jupp, I'm looking into this right now.

**Comment by diox** [comment]
So it is possible to reproduce locally with just fairly basic data indexed (just need one `make populate_data`) but not with all query strings. This multi-word string with unicode chars fails for me : `남포역립카페추천+jjtat닷컴+≡제이제이♠♠+남포역스파+남포역op남포역유흥≡남포역안마남포역오피` but slight alterations work fine.

Need to investigate further.

**Comment by diox** [comment]
The problem seems to come from this:
```
            (query.Match, {
                'query': search_query, 'boost': 2,
                'prefix_length': 4, 'fuzziness': 'AUTO'}),
```

Fuzziness doesn't like complex strings like this one. Even changing `fuzziness` to a hardcoded number, or `prefix_length` and `max_expansions` doesn't really help. I think the solution is to avoid fuzziness if the string contains unicode or is too long.

**Comment by EnTeQuAk** [comment]
Yeah, the problem is also that the length differs quite a bit depending
on the encoding and some of the strings in sentry aren't that long per
se but are huge if encoded in utf-8 for example. Or the other way
around, I don't remember :/
I'd say ignoring fuzziness for longer that anything longer than 20
characters sounds reasonable, or anything more than two words or any
combination thereof.

On Fri, Jan 12, 2018, at 4:58 PM, Mathieu Pillard wrote:
> The problem seems to come from this:


>             (query.Match, { 'query': search_query, 'boost': 2,
>             'prefix_length': 4, 'fuzziness': 'AUTO'}),
>> Fuzziness doesn't like complex strings like this one. Even changing
> fuzziness to a hardcoded number, or prefix_length and max_expansions
> doesn't really help. I think the solution is to avoid fuzziness if the
> string contains unicode or is too long.> — You are receiving this because you were assigned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/mozilla/addons-server/issues/6604#issuecomment-357276802

**Comment by diox** [comment]
Yeah I was thinking about a 20 chars limit and see how it goes. I'll submit a patch for that.
