### ISSUE TITLE
Remove google analytics update task

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6607]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/643407/

```
AccessTokenRefreshError: invalid_grant
(5 additional frame(s) were not displayed)
...
  File "apiclient/http.py", line 716, in execute
    body=self.body, headers=self.headers)
  File "oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "oauth2client/client.py", line 494, in new_request
    self._refresh(request_orig)
  File "oauth2client/client.py", line 653, in _refresh
    self._do_refresh_request(http_request)
  File "oauth2client/client.py", line 710, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)

AccessTokenRefreshError: invalid_grant
```

cc @muffinresearch didn't you do something google analytics related recently? Did something change, some tokens or something?

This started happening about a month ago. I didn't look yet if the analytics update is failing completely or just partially.

**Comment by muffinresearch** [comment]
> cc @muffinresearch didn't you do something google analytics related recently? Did something change, some tokens or something?

Not that I know of.

**Comment by muffinresearch** [comment]
I see this is still occurring - it needs investigation to find out what's happening here and why - I'm not sure what stats this relates to.

**Comment by diox** [comment]
This is used to fetch global stats from Google Analytics and feed them into the `global_stats` table.

It uses the column name 'webtrends_DailyVisitors' when inserting rows, and I don't think this data is accessible from anywhere, so it's only useful to people with direct access to the database.

That table is replicated in telemetry and there is no data with this name after 2017-08-21. Does it means that nobody looks at it and that it should be killed? cc @jvillalobos

**Comment by jvillalobos** [comment]
I didn't know that existed, and it sounds like nobody relies on it. @benmiroglio, do you know anything about this? If not, it sounds like it can be removed.

**Comment by benmiroglio** [comment]
Nope -- I don't touch GA at all.

**Comment by diox** [comment]
Perfect let's kill it :)

Also worth looking if that allows us to remove extra libraries. It looks like oauth2client, gflags, google-api-python-client and httplib2 are no longer required after removing this code...

**Comment by diox** [comment]
Looks like it was introduced for Marketplace back in the day: https://bugzilla.mozilla.org/show_bug.cgi?id=821923
