### ISSUE TITLE
Non-ascii username causes 500 in /api/v3/addons/search/

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6610]
### Describe the problem and steps to reproduce it:

Search for add-ons by author where the author's username has non-ascii characters in it:

```
curl -I 'https://addons-dev.allizom.org/api/v3/addons/search/?app=firefox&appversion=58.0&author=kumar-krstić&page_size=7&sort=hotness&type=extension&lang=en-US'
HTTP/1.1 500 INTERNAL SERVER ERROR
...
```

### What happened?

500 error

### What did you expect to happen?

What did *you* expect to happen?

### Anything else we should know?

[We've all been there](http://farmdev.com/talks/unicode/).

**Comment by kumar303** [comment]
I stole the idea of using non-ascii characters in every configurable thing (while developing) from @krupa. Everyone should do this ❤️

**Comment by diox** [comment]
I don't think this is related to unicode chars. We do have a test proving that unicode chars work when searching by author: https://github.com/mozilla/addons-server/blob/c94c5ddcca68538e68af642a271ed2247297c261/src/olympia/addons/tests/test_views.py#L2859

And it works fine on stage:
`https://addons.allizom.org/api/v3/addons/search/?app=firefox&appversion=58.0&author=kumar-krstić&page_size=7&sort=hotness&type=extension&lang=en-US`

This just look like a general issue with ES on dev at the moment:
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/639271/

**Comment by kumar303** [comment]
Oh, awesome, that's good. I didn't check Sentry out of laziness.

**Comment by diox** [comment]
Back to normal. The servers had to be restarted, which is weird, but weirder things have happened on dev before.

**Comment by diox** [comment]
On IRC @bqbn found an elasticsearch issue that could explain the crashing. If that's correct then it was probably caused by my investigations of https://github.com/mozilla/addons-server/issues/6604 trying to trigger that issue with a large query size, it does not play well with prefix/fuzzy matches.
