### ISSUE TITLE
Reorganize reviewer groups

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6611]
We need to make some changes to our permission groups for reviewers to keep up with recent updates:

* [ ] Rename `Add-on Reviewers` as `Reviewers: Legacy`, and only give them `Addons:Review` permission.
* [ ] Rename `Unlisted Add-on Reviewers` as `Reviewers: Unlisted`.
* [ ] Rename `Persona Reviewers` as `Reviewers: Themes`. 
* [ ] Figure out if the `SeniorPersonasTools:View` permission is used for anything. If so, add that permission to the `Reviewers: Themes` group.
* [ ] Remove the `Senior Personas Reviewers` group.
* [ ] Remove the `Senior Add-on Reviewers` group.
* [ ] Create a `Reviewers: Content` group with the permission `Addons:ContentReview`.
* [ ] Create a `Reviewers: Add-ons` group with the permission `Addons:PostReview`.
* [ ] Create a `Reviewers: Moderators` group with the permission `Reviews:Edit`. If possible, copy over all users in the `Reviewers: Legacy` group. Otherwise we can do this manually.

**Comment by diox** [comment]
When doing this, need to be careful with the Reviewer Leaderboard, which uses the Reviewers/Senior Reviewers groups to find well, reviewers.

**Comment by diox** [comment]
@jvillalobos : `SeniorPersonasTools:View` is used for 3 things:
- Flagged Themes in the "Interactive Theme Queue"
- Updated Themes in the "Interactive Theme Queue"
- Deleted Themes (in Logs -> Deleted from themes reviewer pages) 

In each case, people with `Admin:%` or `AdminTools:View` can also access those pages.

Can it be removed completely and replaced by a check on `Personas:Reviews` ?

**Comment by jvillalobos** [comment]
> Can it be removed completely and replaced by a check on Personas:Reviews ?

Yes, the current theme reviewers are all admins, and I don't see anything risky about keeping them under a single permission.

**Comment by diox** [comment]
@jvillalobos for this:
>  Create a Reviewers: Moderators group with the permission Reviews:Edit. If possible, copy over all users in the Reviewers: Legacy group. Otherwise we can do this manually.

`Reviews:Edit` is not used in our code. Assuming this is about user reviews, here is what we have:
- Users with `Addons:Edit` can edit a user review
- Users with `Addons:Review` or `Personas:Review` can delete a user review if it was flagged, depending on whether the add-on is a lightweight theme or not. Users with `Addons:Edit` or `Users:Edit` can delete reviews regardless of whether or not they were flagged.

Should we change those rules? Note that I'd like to call `reviews` `ratings` internally everywhere possible.

**Comment by jvillalobos** [comment]
> Reviews:Edit is not used in our code.

Ah, then we can drop that permission entirely.

I think we should create a `Ratings:Moderate` permission that gives users the ability to delete or unflag flagged ratings, regardless of type of add-on. That's what the `Reviewers: Moderators` group should have.

> Users with Addons:Review or Personas:Review can delete a user review if it was flagged, depending on whether the add-on is a lightweight theme or not.

Drop this.

> Users with Addons:Edit or Users:Edit can delete reviews regardless of whether or not they were flagged.

Keep this.

**Comment by jvillalobos** [comment]
> @jvillalobos does the Unlisted Add-on Reviewers group exist in prod? 

Yes, it exists in prod.

**Comment by diox** [comment]
@ValentinaPC:
- On dev, I've created `Reviewers: Unlisted` manually.
- On stage, I've created the missing `Unlisted Add-on Reviewers` that exist on prod. That way, when my changes hit stage, you'll be able to confirm that the rename does take place correctly.

**Comment by ValentinaPC** [comment]
The "Reviewers: Unlisted" group is now on dev.
![unlisted](https://user-images.githubusercontent.com/15685960/32488269-c194000c-c3b4-11e7-976a-becd363bcd30.png)
The missing "Unlisted Add-on Reviewers" group was added in stage.

I'll not mark this verified fixed, until I'll test this group migration on stage.
Please, @diox, give me a ping when changes are in stage.
Thanks!

**Comment by diox** [comment]
@ValentinaPC this is now on stage.

**Comment by ValentinaPC** [comment]
Verified in AMO - stage and the missing group is there:
![2017-11-09_1258](https://user-images.githubusercontent.com/15685960/32602173-d83b3fe2-c54d-11e7-864a-c318430cd6d5.png)

I compared the groups from stage and dev and are the same, there is only a small difference for Reviewers:Themes group, as there is an extra rule in dev for this group - `Reviews:Edit`, are we ok with this?

**Comment by diox** [comment]
That extra rule won't have any impact, so it's fine.

**Comment by ValentinaPC** [comment]
Marking this verified fixed.
