### ISSUE TITLE
Keep Complete canned Responses in Post Review

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#6613]
project: auto approval

They are needed for rejections.

**Comment by diox** [comment]
Can you explain a little more what did you expect, on which page, and what was the actual result?

**Comment by erosman** [comment]
The way it is now on the Post Review page (of any add-on), options are:

> Confirm Approval
> Reject Multiple Versions
> Reviewer reply
> Request super-review
> Comment

- Confirm Approval
It doesn't display `Insert canned response...` which is fine
- Reject Multiple Versions
It does display `Insert canned response...` but the list of options are limited to:

  - Request testing information
  - Binary, minified or obfuscated code
  - Incomplete Description    

These options are suited to `Reviewer reply` and not a rejection which requires the full list of canned responses ie Rejecting for eval, remote script, hash mismatch etc etc

**Comment by diox** [comment]
That looks like an issue for @jvillalobos (admins can adjust which canned responses are available for which actions).

**Comment by erosman** [comment]
Oh... I see... I thought it was done server-side.. then no problem.

**Comment by emerald2k** [comment]
@erosman this is already submited, issue to be fixed in https://github.com/mozilla/addons/issues/494

**Comment by diox** [comment]
Closing as duplicate
