### ISSUE TITLE
addon doesnt work

### ISSUE THREAD

**Issue by bmhermitage** [mozilla/addons-server#6617]
I, was on ad-on site 'minimalist google' at http://go.infinise.com/   I tried to add it on and I expected to add it but.......

### Yes, I would still like the ad-on if it is available
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
If you looked for an add-on on addons.mozilla.org and got that message, it means it was removed and it's no longer available.
