### ISSUE TITLE
Expand Find Replacement feature to support non-AMO pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6626]
The admin tool built in #5637 was designed to only point to AMO pages. However, some high-profile add-ons don't have good replacements because they have been replaced with existing Firefox features, so it will serve those users better to direct them to help pages (on SUMO, for instance).

Let's expand the admin tool to support non-AMO pages. Don't know if anything needs to be done about the redirect to work with external sites.

**Comment by jvillalobos** [comment]
Looks like we'll be doing this via heartbeat instead.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).

Used legacy add-on: https://addons-dev.allizom.org/en-US/developers/addon/chatzilla/edit
Admin Tools settings and replacement:
https://addons-internal.dev.mozaws.net/en-US/admin/staff-models/addons/replacementaddon/
![replacement-path](https://user-images.githubusercontent.com/15685960/32273833-c3f907f4-bf0c-11e7-97c9-3136faa94e5c.png)
Redirection link:
https://addons-dev.allizom.org/find-replacement/?guid={59c81df5-4b7a-477b-912d-4e0fdf64e5f2}

Things seem to work as expected.

@eviljeff: please let me know if there is anything else I should check here.
Thanks!

**Comment by eviljeff** [comment]
lgtm

**Comment by ValentinaPC** [comment]
Marking this as verified-fixed.
