### ISSUE TITLE
Gzip API responses

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6636]
Gzipping addons-server responses was disabled a while ago to prevent CRIME/BREACH attacks. While it's useful to avoid leaking CSRF tokens in regular HTML pages, we should not need that kind of protection in the API, which a) does not have cookie-based auth, so no secret is automatically sent with each request and b) does not include both a secret and user input in its responses.

Re-enabling gzip for the API, especially with large responses with lots of add-ons (there will be a lot of property names repeated)n should help the new frontend performance.

**Comment by kumar303** [comment]
Doesn't `/api/v3/accounts/authenticate/` respond with a `set-cookie` header? Maybe that response should not be gzip'd? I forget how the crime/breach attack worked.

**Comment by diox** [comment]
It needs the secret and a chosen text to be both part of the request and the response. Essentially the idea is for an attacker to force the victim's browser to call our server with a cookie + some chosen text over and over and over, and look at the responses sizes to try to guess the cookie. The response varies because of the text.

While we do have endpoints that set cookies, or respond with a chosen input text (errors for some parameters for instance) we never do both, and we don't support cookie auth so there is nothing to leak (you can't force a victim browser to automatically send our auth tokens).
