### ISSUE TITLE
Invalid link to add-on review

### ISSUE THREAD

**Issue by asraskin** [mozilla/addons-server#6639]
I received an email from "Mozilla Add-ons" telling me about a review of my Exif Viewer extension. The email included a link to https://addons.mozilla.org/en-US/firefox/addon/exif-viewer/reviews/932340/reply, so I could reply to the review.

When I clicked on the link and logged in, I instead got a "We're sorry, but we can't find what you're looking for." response.

I expected to be taken to the review reply page.

**Comment by eviljeff** [comment]
@wagnerand what would you expect to be changed here?

**Comment by wagnerand** [comment]
Redirecting to @jvillalobos.

**Comment by jvillalobos** [comment]
The Not Found page is in the old front-end, so that's one thing to fix. As for the content of the page, it could be something more specific, like "This review no longer exists", but I'm hesitant of creating a page just for this.

**Comment by eviljeff** [comment]
Exposing deleted things to end-users isn't usually a good idea.  (even if we're only exposing their existence)

> The Not Found page is in the old front-end, so that's one thing to fix. 

Looks like frontend doesn't support the url to a review reply because they implemented it inline - we dropped the reply link from that email in the meantime (with #6817).  I guess addons-frontend could capture and redirect the old reply urls but it's a bit edge case.

**Comment by jvillalobos** [comment]
> Exposing deleted things to end-users isn't usually a good idea. (even if we're only exposing their existence)

Fair enough. We _could_ show something different if you're logged in and you're a dev for the add-on being reviewed. But that's a tad too specific.

> Looks like frontend doesn't support the url to a review reply because they implemented it inline

https://github.com/mozilla/addons-frontend/issues/2771 is open to support URLs to specific reviews.

**Comment by jvillalobos** [comment]
Closing this, since I don't see any action to take other than what's tracked in other issues.
