### ISSUE TITLE
Migrate from Trunion to Autograph for add-ons signing

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6640]
The signature of addons of all types should be performed by the Autograph service, and no longer by the trunion service on the SCL3 HSMs.

Relevant example code from sign-xpi: https://github.com/mozilla-services/sign-xpi/blob/master/aws_lambda/sign_xpi.py#L293-L307
 
Now we apparently can use autograph via docker so we should finally be able to write proper unittests against it. Holy new shiny era!
> You can either run autograph from the container at mozilla/autograph, or from the binary at go.mozilla.org/autograph. The default configuration can sign add-ons (but not issue real signatures) [1] using hawk credentials from [2]. There's a test client at [3], but Ethan's code is probably a better place to start.
>
> [1] https://github.com/mozilla-services/autograph/blob/master/autograph.yaml#L67
> [2] https://github.com/mozilla-services/autograph/blob/master/autograph.yaml#L216-L217
> [3] https://github.com/mozilla-services/autograph/tree/master/tools/sign-addon

* [x] Make the change switchable via waffle
* [x] Integrate autograph (docker image) into our unittests

References [bug 1352424](https://bugzilla.mozilla.org/show_bug.cgi?id=1352424) and [bug 1352439](https://bugzilla.mozilla.org/show_bug.cgi?id=1352439)

Currently (partially) blocked by [bug 1409197](https://bugzilla.mozilla.org/show_bug.cgi?id=1409197)

**Comment by bqbn** [comment]
Had a meeting with @jvehent and @Micheletto yesterday. The hope is that we switch AMO to using autograph in December on -prod (so not to overlap with 57 launch). -dev and -stage can (and probably should) happen before that.

**Comment by EnTeQuAk** [comment]
QA: The actual change in here is not yet live and we don't have a test-server on -dev yet so for now just make sure add-on upload works fine and signing generally works :)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7) and :
- submissions
- new file upload
- new version upload
- auto-approve
- manual approve
 work as expected.
