### ISSUE TITLE
Android marked supported despite deselected during submission

### ISSUE THREAD

**Issue by cr** [mozilla/addons-server#6645]
### Describe the problem and steps to reproduce it:
* Submit a web extension.
* Deselect "All platforms" and select all but Android instead.

### What happened?
* Further submission dialogs force you to specify a category for Android.
* Listing's "Version Details" still show Android support
* "Manage Status and Versions" also still shows Android as supported.

### What did you expect to happen?
* No more on-submission questions about Android.
* Android not being marked as supported anywhere in AMO.

### Anything else we should know?
* Extension was marked "Experimental"

**Comment by diox** [comment]
Hi, this has already been reported a while ago in https://github.com/mozilla/addons/issues/348 and we never got around to fixing it, sorry about that :(
