### ISSUE TITLE
Make "Cancel and Disable Version" behave like regular Version Disable, if possible

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6646]
Separated from https://github.com/mozilla/addons-server/issues/6587

I noticed the "Cancel and Disable Version" doesn't behave exactly like the regular "Disable Version" action:
- "Cancel and Disable Version"  (`devhub.views.cancel`) manually changes the add-on status and then does this on the `latest_version`:
```python
for file_ in latest_version.files.filter(
                status=amo.STATUS_AWAITING_REVIEW):
            file_.update(status=amo.STATUS_DISABLED)
```

- "Disable Version" (`devhub.views.version_delete`, with `disable_version` passed) first calls `version.is_user_disabled = True` then `version.addon.update_status()` to handle add-on status changes. `version.is_user_disabled = True` does this:
```python
            activity.log_create(amo.LOG.DISABLE_VERSION, self.addon, self)
            for file in self.files.exclude(status=amo.STATUS_DISABLED).all():
                file.update(original_status=file.status,
                            status=amo.STATUS_DISABLED)
```

So, questions (maybe @eviljeff knows) :
- Why does `cancel` does not call `version.is_user_disabled = True` then `version.addon.update_status()`  like `version_delete` does ?
- Assuming we do need to keep the 2 slightly different ways of doing this, why does `cancel` does not set `original_status` when changing the files `status` ?

In any case, #6587 proved that we need to add some logging in `cancel` if it continues to do its own thing.

**Comment by eviljeff** [comment]
While I can't recall exactly, I strongly suspect they were just two different features added at different times.  Primarily the 'cancel' in the submission flow is for interrupting new submissions (the first listed version submission, anyway); whereas the 'disable version' option in debhub is for disabling a version at some later point (at least after you've exited the submission flow).  So although they do the same thing, pretty much, they're doing it for different purposes.

I can't think of any reason right now why it can't be the same code - though there are edge cases with non-STATUS_AWAITING_REVIEW files that shouldn't happen.
