### ISSUE TITLE
 Add-on website header color is too similar to confirmation button color.

### ISSUE THREAD

**Issue by equant** [mozilla/addons-server#6659]
### Describe the problem and steps to reproduce it:

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
Build ID: 20170826053331
Added an add-on.

### What happened?

When adding an add-on, the color of the "Add" and "Restart" buttons used by firefox are very similar in color to the background, and it's hard to see the firefox button.  I've attached a screenshot showing the issue.

### What did you expect to happen?
The button should be more visible.

### Anything else we should know?

I've attached a screenshot.
![screenshot_2017-10-09_08-22-54](https://user-images.githubusercontent.com/114806/31465286-5b714b40-ae88-11e7-9246-48a8b8db84ee.png)

**Comment by andymckay** [comment]
This will be fixed soon when we launch the new desktop site - its not got big blocks of blue on it.
