### ISSUE TITLE
Themes updates are not applied if the same theme was previously installed 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6665]
Steps to reproduce:
1.Install any theme from amo-dev (ie, https://addons-dev.allizom.org/en-US/firefox/addon/dark-fox-18066/)
2.Go to Edit Theme page and upload a new design
3.With a reviewer account , go and approve the update
4.Go to about:addons and remove the theme installed at Step 1
5.Install again the theme from Step 1

Expected results:
The new design is applied

Actual results:
The old design (the one before the update) is applied

NOTES:
1. Should Enable\Disable action after Step 3 automatically apply the update ?
2.Check for updates should bring the new design ?
3.If FF is restarted after Step 4 , the new design is applied
4.Tried in latest Nightly 

Please see video for this issue (I recorded only the part after Step 3 , where you can see that another design is applied than the new one) : 
![themesupdate](https://user-images.githubusercontent.com/1583842/31501695-a1397436-af73-11e7-8cc9-bd45790bc458.gif)

**Comment by diox** [comment]
Wontfixing this because lightweight themes are about to be replaced with static themes, which behave more like regular add-ons.
