### ISSUE TITLE
Use uwsgi in our local docker environment

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6668]
To find issues like https://github.com/mozilla/addons-server/commit/97d288b9440d388183b195b0062bd83636ae355a better in the future we should add one more component from our production pipeline to our local development pipeline: uwsgi

Currently we are running our runserver which should in theory have catched that issue but somehow it didn't. Probably because the loader and settings are loaded before the `wsgi` file is loaded and the environment variable got changed.

**Comment by muffinresearch** [comment]
Moving to the full docker file might be even nicer.
