### ISSUE TITLE
ValueError: badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6670]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/378972/

```
ValueError: badly formed hexadecimal UUID string
(16 additional frame(s) were not displayed)
...
  File "olympia/amo/decorators.py", line 144, in wrapper
    return f(*args, **kw)
  File "olympia/amo/decorators.py", line 131, in __call__
    return self.f(*args, **kw)
  File "olympia/devhub/views.py", line 866, in upload_detail
    upload = get_object_or_404(FileUpload, uuid=uuid)

ValueError: badly formed hexadecimal UUID string
```

**Comment by diox** [comment]
From the data we have in sentry it looks like someone mistyping an URL or trying to enter garbage. We should simply return a 404 when the uuid is invalid in `{locale}/developers/upload/{uuid}`

**Comment by diox** [comment]
QA: make sure that visiting the page for a previous validation result works, and that submission still works as well. Also test that changing the hexadecimal id in the URL (removing a character, or changing one to a different character) results in a 404, not a 500.

**Comment by vcarciu** [comment]
Visiting the page for a previous validation works together with submissions.
Changing the hexadecimal id in the URL will return a 404: 
![urlhex](https://user-images.githubusercontent.com/1583842/31823847-1ae1bcce-b5b6-11e7-9db7-ee3500acb870.gif)
