### ISSUE TITLE
Firefox 57 about:addons Find a replacement: where a developer of a legacy add-on provides (or works towards) a compatible successor add-on, favour the developer; refrain from recommending unrelated developments elsewhere

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-server#6674]
### [FireTitle](https://addons.mozilla.org/addon/firetitle/)

The developer confirmed work with WebExtensions APIs at <https://github.com/captnfab/FireTitle/issues/9#issuecomment-287645927> (2017-03-19) and there's more recent, unmistakably titled: 

- [Port to WebExtensions · Issue #12 · captnfab/FireTitle](https://github.com/captnfab/FireTitle/issues/12)

#### Expected

Recommend the Firefox 57-compatible successor from the same developer(s), in this case: 

1. <https://addons.mozilla.org/find-replacement/?guid={f4b962b4-ab75-41bf-8da7-a0435258a27c}>
2. redirection
3. <https://addons.mozilla.org/addon/crappy-firetitle/?src=find-replacement> 

#### Actual result

3. <https://addons.mozilla.org/en-GB/firefox/collections/mozilla/featured-add-ons/?src=find-replacement>

– sixty-eight items featured by Mozilla across three pages, nothing like FireTitle on any of the three.

## Other cases

In `#amo` on 2017-10-02 I asked: 

> When a (57/58) search for an alternative leads away from an appropriate alternative, how best to report an improvement? Somewhere in GitHub, one issue per case?

@tofumatt responded: 

> yeah I think that's appropriate. In the addons-server repo, which handles the alternatives (if I recall correctly)
> though failing that in the regular addons repo is fine and we'll triage it :-)

I might find time to identify more cases around the end of this month …

**Comment by diox** [comment]
To explain the behavior: The add-on replacements feature is curated by humans, so it doesn't know about all add-on replacements that may be out there (there are far too many add-ons for the list to be 100% comprehensive). When no replacement is known, it redirects you to the featured add-on list, with the hope that one of the most popular add-ons might have a feature that is close to what you were looking for.

@devaneymoz : this is not the first time someone filed a bug here to suggest a specific replacement. Is it the best place to do so?

**Comment by grahamperrin** [comment]
> … curated by humans …

👍 and I'll happily help with curation in ways that will help things in Mozilla domains. 

(OT: I had a hideous, somewhat inhuman experience with 57-transition-specific curation elsewhere. Never again.)

**Comment by devaneymoz** [comment]
This is a fine place to file replacement recommendations, in general. However @grahamperrin if you have other 1:1 replacement recommendations for legacy content, you can feel free to email them directly to save some churn. sdevaney@mozilla.com

I will apply this FireTitle recommendation to the tool. Thank you!

**Comment by jvillalobos** [comment]
I think the preferred place is [the discourse thread](https://discourse.mozilla.org/t/favorite-webextensions), where you can also check if others have made similar suggestions, and it takes less time to monitor.

It sounds like there's nothing left to do here, so I'm closing this.

**Comment by grahamperrin** [comment]
Thanks folks, is the FireTitle case fixed? 

(Sorry – I don't have easy access to any machine with 57.)
