### ISSUE TITLE
Show post-review risk on review page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6675]
Currently, the only way to see the risk of an add-on is while it's pending post-review.  If it's not pending, the risk is inaccessible.

Let's add the risk to the review page.

**Comment by jvillalobos** [comment]
Agree. I think it should show up in the metadata list, below `Requires payment` and above `Last approval date`.

**Comment by wagnerand** [comment]
Different versions can have different weights, so it will be shown per version, below the "Compatibility" information.

**Comment by wagnerand** [comment]
We can show the weight of the current version on the top, if necessary. Let's do this in a follow-up though.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfi screenshot:
![w](https://user-images.githubusercontent.com/15685960/31661660-2d8ff620-b344-11e7-86a6-636fcdf6b704.png)
