### ISSUE TITLE
`yum` doesn't install `supervisor`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6679]
For some reason, https://github.com/mozilla/addons-server/blob/6c5b74e2039f3e35c0ea31f397160c2d888ab657/Dockerfile#L21 doesn't really install `supervisor`.

Output: `No package supervisor available.` (Example: log output on https://hub.docker.com/r/addons/addons-server/builds/biktrkvnih367boqwerbuxa/)

@EnTeQuAk any ideas?

**Comment by EnTeQuAk** [comment]
That totally explains why my celery tests on circleci fail so randomly,
I'll look into it. Could just get that the package is named differently
but imho it has always been 'supervisor'.I'll check Monday morning to unblock everyone, sorry about that. 


On Sat, Oct 14, 2017, at 11:41 PM, Andreas Wagner wrote:
> For some reason,
> https://github.com/mozilla/addons-server/blob/6c5b74e2039f3e35c0ea31f397160c2d888ab657/Dockerfile#L21
> doesn't really install supervisor.> Output: No package supervisor available.


> @EnTeQuAk[1] any ideas?


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 

Links:

  1. https://github.com/entequak
  2. https://github.com/mozilla/addons-server/issues/6679

**Comment by wagnerand** [comment]
I assume this is rather some timing issue.

In a started container, `yum` finds the package just fine:

```
$ make shell
docker-compose exec web bash
[root@8104597fd19a code]# yum search supervisor
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: repo1.ash.innoscale.net
 * epel: s3-mirror-us-east-1.fedoraproject.org
 * extras: repos-va.psychz.net
 * updates: mirrors.seas.harvard.edu
====================================================================================================== N/S matched: supervisor =======================================================================================================
nodejs-supervisor.noarch : A supervisor program for running nodejs programs
python-simplevisor.noarch : Python simple daemons supervisor
supervisor.noarch : A System for Allowing the Control of Process State on UNIX

  Name and summary matches only, use "search all" for everything.
[root@8104597fd19a code]#
```

**Comment by EnTeQuAk** [comment]
eh, nevermind my celery idea…

Regarding supervisor - we install it via `yum` but also install it in our `requirements/dev.txt` so in practice the yum installed thing (even if it doesn't work) doesn't matter. I'll get rid of it.
