### ISSUE TITLE
AMO: Tier-3 platform BSD equivalence to Tier-1 Linux for new front-end purposes

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-server#6680]
Follow-up to: 

- [Unable to install add-on on *BSD · Issue #5647 · mozilla/addons-server](https://github.com/mozilla/addons-server/issues/5647) 
- <https://github.com/mozilla/addons-server/pull/6157> (2017-08-11), which fixed [Various extensions inexplicably not, or no longer, installable to Firefox on FreeBSD through the GUI to addons.mozilla.org (AMO) · Issue #468 · mozilla/addons](https://github.com/mozilla/addons/issues/468) for the _legacy frontend_ component.  

Shared understandings: 

> We don't officially support BSD, but this small change should improve the life of its users by letting them install add-ons marked as compatible with Linux instead of "All platforms".

> … I don't mind doing it now because it's relatively easy, but the code is old and fragile and I can't promise it won't break again in the future …

With Firefox 56.0.1 (64-bit) on FreeBSD-CURRENT **switched to the (mobile) new front-end**, there's no platform equivalence. I have not tested that end often enough to tell whether (a) it has not gained a fix for equivalence; or (b) a fix has been broken. 

In any case: @diox and colleagues, please, might there be a fix? With the same shared understandings, for the _new_, as we had for the _legacy_ front-end 👍 

TIA

## Tested

[Close Other Windows](https://addons.mozilla.org/addon/close-other-windows/) with reference to [Close Other Windows 0.1 with Firefox on FreeBSD · Issue #1 · mystor/close-other-tabs](https://github.com/mystor/close-other-tabs/issues/1).

Extensions in the attached screen recording: 

- [Context Plus](https://addons.mozilla.org/addon/context-plus/) @totallymike
- [MultiSelect Tabs](https://addons.mozilla.org/addon/multiselect-tabs/) @mikeconley
- [Tab Center Redux](https://addons.mozilla.org/addon/tab-center-redux/) (featured by Mozilla) @eoger 
- [Tab notifier](https://addons.mozilla.org/addon/tab-notifier/) (featured by Mozilla) – [home page not available](http://unusoft.it/blog)
- [Webcompat.com Reporter](https://addons.mozilla.org/addon/webcompatcom-reporter/) @webcompat

– although (sorry) I can't tell/recall whether any of those five is truly incompatible with BSD.  

[2017-10-13 02:24:17 new front-end without platform equivalence.mp4.zip](https://github.com/mozilla/addons-server/files/1385100/2017-10-13.02.24.17.new.front-end.without.platform.equivalence.mp4.zip)

## Workarounds

Either: 

a) a platform-oriented override with legacy [User Agent Overrider](https://addons.mozilla.org/addon/user-agent-overrider/), if Firefox is less than 57; or 

b) _View classic desktop site_, for as long as that will be possible.

**Comment by diox** [comment]
Please don't highlight random addon authors in issues, there is no need for that notification spam.

This should be re-filed over at https://github.com/mozilla/addons-frontend/ which is the repository for the new frontend.

**Comment by grahamperrin** [comment]
Thanks, please note that I was previously steered to `addons-server`; my comment at <https://github.com/mozilla/addons/issues/468#issuecomment-321657734> reflected that steering and apologised for the misplacement in `addons` after I was misdirected by Bugzilla@Mozilla. 

Also **please do not misinterpret the four mentions as spam**. They certainly were not random, and any one of those developers might have liked to comment on whether there's a known incompatibility with BSD. 

I'll re-file as suggested.
