### ISSUE TITLE
Show error if add-on is using Mozilla trademarks incorrectly

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6693]
This is something the legacy validator does, but apparently is not applied consistently for all add-ons, or for all cases. The rule is that you can only use `Firefox` or `Mozilla` in an add-on name if they are used at the end, in the form `for Firefox`, or `for Mozilla`, _or_ if the submitter has an account associated with an `@mozilla.com` or `@mozilla.org` email address.

We need this to be applied to WebExtension add-ons, and we also need to ensure this rule is applied during the submission flow and the developer hub, where the name can be changed by the developer. This is particularly important now that we have auto-approval turned on.

**Comment by eviljeff** [comment]
This would be easier to handle if we didn't let developers change their add-on's name via devhub, just sayin'

**Comment by EnTeQuAk** [comment]
I can take a look at this, especially since this needs a sister-issue in the linter too but unfortunately needs to be implemented in both places to catch name-changes via the UI.

**Comment by jvillalobos** [comment]
> This would be easier to handle if we didn't let developers change their add-on's name via devhub

That's coming, but not this quarter.

**Comment by AlexandraMoga** [comment]
Verified this on AMO-dev with FF58 (Win10x64)

Observations:
- When using "for Mozilla/Firefox" in the name format, there is no error thrown by the linter or in Dev Hub even if `Firefox `or `Mozilla `are used elsewhere inside the add-on name (i.e. I can name my add-on like this: "Firefox word1 word2 for Mozilla")
- the detector is not checking the URLs, i.e my URL can end in `/addon/good_firefox`

screenshot:
![image](https://user-images.githubusercontent.com/31961530/35340078-e443ccaa-012a-11e8-8ce8-c8630811131a.png)

Extension uploaded:

[firefox addon.zip](https://github.com/mozilla/addons-server/files/1660348/firefox.addon.zip)

**Comment by jvillalobos** [comment]
Good catch for the first one. The second one is out of scope; maybe something to consider for the future.

**Comment by rctgamer3** [comment]
Will this prevent add-ons that are allowed to use Firefox/Mozilla in their name prevent the developer from uploading new versions? Or is this check only done on new submissions/name changes?

**Comment by EnTeQuAk** [comment]
This is being checked for new submissions and whenever someone tries to change an add-ons name. People with a mozilla email address are allowed to use the trademark though.

**Comment by AlexandraMoga** [comment]
I've verified this again on AMO-dev but I don't see any changes yet...

![image](https://user-images.githubusercontent.com/31961530/35624599-1e692c8c-0698-11e8-9bde-a9330bfb1dc2.png)

**Comment by EnTeQuAk** [comment]
Indeed, my workaround fixed the case for "Mozilla awesome for Mozilla" but obviously didn't for "Firefox awesome for Mozilla". I'll get it in for next week :)

**Comment by EnTeQuAk** [comment]
Pushed a fix for that edge-case again. Let's please open new issues in case you find more edge-cases here. Should be heading to -dev soon and will make it into todays tag.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF59 Win10x64

There were no other edge cases identified

![image](https://user-images.githubusercontent.com/31961530/37397513-7bf618e4-2784-11e8-89bf-feda78342577.png)

![image](https://user-images.githubusercontent.com/31961530/37397527-8585dd4a-2784-11e8-9de3-b2aad3085ebd.png)
