### ISSUE TITLE
Error adding images to extension listing on Dev Server

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#6695]
### Describe the problem and steps to reproduce it:

I submitted an extension to https://addons-dev.allizom.org and edited the listing multiple times to create samples to be used for content review onboarding. 

### What happened?
When I went to add an icon and screenshots to the listing, the section timed out and never resolved. I stopped and re-tried a few times with the same result each time. Here's a screenshot of the last try to add an icon (no screenshots): 

![screen shot 2017-10-16 at 3 16 41 pm](https://user-images.githubusercontent.com/23342476/31637927-e2dfb85e-b285-11e7-9f59-060ee8ecfa08.png)

### What did you expect to happen?
To either have the icon added or to receive an error message and re-submit an icon image. 

### Anything else we should know?
I had edited the same extension listing a few times. 

Link to the extension: https://addons-dev.allizom.org/en-US/developers/addon/fuck-yeah-jgl/edit

**Comment by diox** [comment]
This is another consequence of switching the default serializer for celery tasks to JSON. See https://sentry.prod.mozaws.net/operations/olympia-dev/issues/671111/ for the traceback.

Grepping for `modified_on=` it's obvious that we do this in a few other places as well. Given that we are close to tagging and we probably have more instances of this happening in other tasks that won't be as easy to grep, I think we should go back to pickle this week and switch to JSON next week, if we can.

The other option would be to make the tests properly fail on such cases and make sure all calls to tasks are covered by tests - grepping for `.delay`, `.apply_async` etc to make sure no task is going to fall through the cracks...

**Comment by EnTeQuAk** [comment]
> I think we should go back to pickle this week and switch to JSON next week, if we can.
> The other option would be to make the tests properly fail on such cases and make sure all calls to tasks are covered by tests - grepping for .delay, .apply_async etc to make sure no task is going to fall through the cracks...

I agree I'll fall back to using pickled serialization instead and work on our tests to use a running celery worker before enabling JSON again.

**Comment by vcarciu** [comment]
Verified as fixed: 
![superimages](https://user-images.githubusercontent.com/1583842/31673397-c470952c-b367-11e7-84bc-1b6138b9ff28.gif)
