### ISSUE TITLE
Investigate setting important index metadata during reindex

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6703]
Refs https://github.com/mozilla/addons-server/issues/6053#issuecomment-336293808

`max_result_window` got lost during reindex, we should either add a new management command that is setting these or the reindex command should take care of that.

**Comment by diox** [comment]
It got lost again yesterday, so I'm putting this in the next milestone.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
