### ISSUE TITLE
Add notifications API

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6712]
At some point we'll need to show notifications in the new frontend which will display messages across the site to our users. 

We'll need to investigate whether we can use the existing infrastructure and expose an API for it or if we need to build a new system.

This will need fleshing out with more detail requirements in due course.

**Comment by jvillalobos** [comment]
This is covered in the [Admin Tools PRD](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.s99wtbxa3v59). This particular feature hasn't been scheduled for implementation yet, but we can keep the issue open until then.
