### ISSUE TITLE
No warning displayed in the submission process if the user does not select a platform

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#6715]
### Steps to reproduce:
1. Open the submit a new add-on page: https://addons.allizom.org/en-US/developers/addon/submit/upload-listed
2. Upload a file and deselect all the check boxes in the platform selection section
3. Click the continue button

### Expected results:
A warning that you must choose a platform is displayed.

### Actual results
No warning is displayed.

### Notes/Issues:
Verified in FF56(Win7) Issue can be reproduced in amo-dev, stage and prof
Screencast for this issue:
![noplatformwarning](https://user-images.githubusercontent.com/15685441/31719646-d18abbba-b41c-11e7-871c-a2a1b213a197.gif)

**Comment by diox** [comment]
@eviljeff can you take a look, since you touched this with the static themes?

**Comment by eviljeff** [comment]
mmm, I think my JS changes to not show the platform selector by default are the problem here.  Though I'm also not sure why we don't just block proceeding with JS if you don't select any platform.

**Comment by madalincm** [comment]
Verified as fixed in FF56(Win7) in addons-dev.allizom.org
Postfix screencast:
![noplatformwarning](https://user-images.githubusercontent.com/15685441/32162057-50fa3898-bd60-11e7-9549-28a8f1f7bed7.png)
