### ISSUE TITLE
OneTab FF addon 2.1

### ISSUE THREAD

**Issue by kstavert** [mozilla/addons-server#6716]
OneTab team has written an update for OneTab addon.

I have this update installed on another computer and
it works beautifully.

I tried to install it on another computer/same version
of FF by going to the same link:

https://addons.mozilla.org/en-US/firefox/addon/onetab-modified/

and was delivered to this page that told me I was in the wrong
place ;(

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiRzaL-ofrWAhVJ6YMKHf3OAIoQFggoMAA&url=https%3A%2F%2Faddons.mozilla.org%2Fen-US%2Ffirefox%2Faddon%2Fonetab-modified%2F&usg=AOvVaw10mvKCwZ8IR60lQhIrwdLO

OneTab is a FABULOUS addon for FireFox (and Chrome) - wish
you guys would just build it into FF so that it would work
on all updates.

I will NOT update FireFox right now because OneTab stops
working.

Do YOU have tools that you use all of the time?  Tools that make
your online life easier when they work properly?

OneTab is one such tool for me (and thousands of others)

I am attaching a screenshot from my extensions that shows
OneTab 2.1 installed.

Why am I not able to locate this extension in the FF addons?

PLEASE PLEASE PLEASE... make this work
![onetab 2 1](https://user-images.githubusercontent.com/6510503/31721749-db87c9ce-b3df-11e7-924c-9a54ae5ac9bc.jpg)

**Comment by jvillalobos** [comment]
The add-on was taken down due to code review issues. It's up to the developer now to address these issues and submit a new version so the listing will come back. It'll probably happen soon.

**Comment by kstavert** [comment]
WOW... Jorge, thank you so very much
for responding... never thought I'd actually
really hear from anyone ;)
