### ISSUE TITLE
Change order and link in Tools section of Dev Hub footer

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#6721]
Edits to the footer of https://addons.mozilla.org/developers/.

Current:

**Tools**
Add-on Validator
Compatibility Checker
Compatibility Reporter
Manage API Keys

Change to:

**Tools**
[Web-Ext: build & test extensions](https://github.com/mozilla/web-ext)
Add-on Validator
Compatibility Checker
Manage API Keys

Summary: Remove Compatibility Reporter, add Web-Ext to the top

**Comment by vcarciu** [comment]
Verified as fixed : 
![webextlinktogit](https://user-images.githubusercontent.com/1583842/31949773-c9610aaa-b8e2-11e7-9165-4161771e849e.gif)

**Comment by ValentinaPC** [comment]
@atsay : do we wanna change the options from Tools section while logged out?
![2017-10-25_1239](https://user-images.githubusercontent.com/15685960/31991953-a00490c4-b981-11e7-986d-f5457a2035f5.png)
Thanks!

**Comment by atsay** [comment]
That is a really good point, thanks for flagging! I'll create a separate issue.
