### ISSUE TITLE
[API] addon developer url is sometimes null

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6726]
See https://github.com/mozilla/addons-frontend/issues/3555

It would be easy enough to workaround this rather than have a broken link but is it actually expected that we null as a value for this?

<img width="749" alt="nightly" src="https://user-images.githubusercontent.com/1514/31734566-17f04062-b40d-11e7-9d89-7e5badf822d3.png">

**Comment by muffinresearch** [comment]
@diox this seemed to fix itself but it would be good to know if there's a way to workaround it.

**Comment by diox** [comment]
I can see it being `null` now. This is not supposed to be happening for add-on developers. @eviljeff, can you take a look?

**Comment by eviljeff** [comment]
https://addons.mozilla.org/api/v3/accounts/account/13298371/ isn't viewable either, so it points to `is_public` being `False`.  It's supposed to be updated via `UserProfille.update_is_public` whenever an add-on's status changes.

Kibana is showing nothing helpful about either the addon (855221) nor the user (13298371) - not really anything at all about the Add-on status changing, which is odd in itself.

**Comment by diox** [comment]
FWIW, in the activity log it was approved on September 21st. The `is_public` stuff landed way before that though.

**Comment by eviljeff** [comment]
I can replicate this on -dev with an unused account and then uploading an add-on, so something is going wrong with the signals that are supposed to fire when an addon's status changes to update the authors's `is_public` status.

**Comment by eviljeff** [comment]
QA STR:
* Register new AMO account (or login with an account that has never been used to upload addons/themes)
* (set a username - optional but makes urls easier)
* see `https://addons-dev.allizom.org/api/v3/accounts/account/<username or user id>/` should be a 404-ish JSON response (not found)
* Upload a webextension add-on on listed channel and finish upload process to create it, leaving it at 'awaiting review'
* Wait for automated post review task to approve the add-on (up to 10 minutes)
* Go back to `https://addons-dev.allizom.org/api/v3/accounts/account/<username or user id>/` and there should be a full JSON response now - the public account details.

**Comment by vcarciu** [comment]
Followed the steps from above and the response after last step is still 404 : https://addons-dev.allizom.org/api/v3/accounts/account/testapi/

**Comment by eviljeff** [comment]
Looking in kibana confirms "Not changing 10641506.is_public from False :/data/olympia/src/olympia/users/models.py:302" so the signal and `update_is_public` method _is_ being called; but the `.filter(...).exists()` is `False` so it's not getting set correctly.

**Comment by vcarciu** [comment]
Verified as fixed : 
![url](https://user-images.githubusercontent.com/1583842/31997964-9a9e4d04-b996-11e7-8a10-d7b75a3a1ab9.png)
