### ISSUE TITLE
Deleted review rating included in average rating

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-server#6727]
An invalid [review](https://addons.mozilla.org/en-US/firefox/addon/clear-browsing-data/reviews/935487/) was flagged and removed a day ago, but it still affects the average rating of the add-on.

The review count on the [listing page](https://addons.mozilla.org/en-US/firefox/addon/clear-browsing-data/#reviews) should be 2, not 3 (`3 user reviews`, `See all 3 user reviews`), and the average rating should be 5, not 4.
The [reviews page](https://addons.mozilla.org/en-US/firefox/addon/clear-browsing-data/reviews/) lists the correct number: `2 reviews for this add-on`.

**Comment by kumar303** [comment]
I confirmed that the new frontend site experiences the same thing so it affects the API.

**Comment by diox** [comment]
I bet it's a variation of https://github.com/mozilla/addons-server/issues/5999 ; the task does the right thing and excludes deleted reviews, but it could have been called too early, before the transaction that deletes the review has been committed...

**Comment by dessant** [comment]
Meanwhile the add-on got a new review and all stats are now correct, the rating of the deleted review is not included in the average rating anymore.

**Comment by jzav** [comment]
Any chance of fixing this? I am not sure when my add-on will get new review...

**Comment by diox** [comment]
Closing as duplicate to #5999

@jzav : we really want to fix this issue, but it's not trivial, so we can't really give a timeline as to when it will be fixed.
