### ISSUE TITLE
Empty JSON response from API causes a syntax error

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6728]
### Describe the problem and steps to reproduce it:

The [flag review](https://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#flag) endpoint returns an empty response. Here is an example:

```
$ curl -v -H "Content-Type: application/json" -H 'Authorization: Bearer [redacted]' 'https://addons-dev.allizom.org/api/v3/reviews/review/562052/flag/' -d '{"flag":"review_flag_reason_spam"}'
...
> POST /api/v3/reviews/review/562052/flag/ HTTP/1.1
> Host: addons-dev.allizom.org
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer [redacted]
> Content-Length: 34
>
* upload completely sent off: 34 out of 34 bytes
< HTTP/1.1 202 OK
< Allow: POST, OPTIONS
< Content-Security-Policy: script-src [...]
< Content-Type: application/json
< Date: Wed, 18 Oct 2017 23:24:47 GMT
< ETag: "d41d8cd98f00b204e9800998ecf8427e"
< Server: nginx
< Set-Cookie: multidb_pin_writes=y; expires=Wed, 18-Oct-2017 23:25:02 GMT; Max-Age=15; Path=/
< strict-transport-security: max-age=31536000
< x-content-type-options: nosniff
< X-Frame-Options: DENY
< x-xss-protection: 1; mode=block
< transfer-encoding: chunked
< Connection: keep-alive
<
* Connection #0 to host addons-dev.allizom.org left intact
```

### What happened?

Since the response is empty, it causes [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to throw a syntax error:

```
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

Well, I haven't fully tracked this down yet but I think it's happening within `fetch()`, not my code.

### What did you expect to happen?

It should not throw a syntax error. I think it's happening because the content type of the response is `application/json` which is not technically correct. It is not valid JSON.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I'll try to find a workaround next.

**Comment by diox** [comment]
I'll make it return some message instead of empty data.

**Comment by ValentinaPC** [comment]
Please add some STR or the label "qa: not needed". Thanks!

**Comment by kumar303** [comment]
I verified that this is working now. Thanks again.
