### ISSUE TITLE
Add-on Daily users zero for 17.10.2017

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-server#6734]
### Describe the problem and steps to reproduce it:
Daily users stats are 0 for October 17, including all substats.

### What happened?
The usage stats say 0 users for every extension

### What did you expect to happen?
At least my usage of the extensions should show up (so the stats should have at least one user reported)

### Anything else we should know?
Example stats: https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/statistics/usage/?last=30

Those stats (and for other add-ons) also report 0 for every metric (including downloads) for October 18, but I'm not sure if those should be available yet at the time I'm filing this issue.

**Comment by wagnerand** [comment]
Adding @jasonthomas.

**Comment by jasonthomas** [comment]
@bqbn can you take a look? We probably need to run stats again for this day. This might be related to when amo-cron was having issues.

**Comment by Croydon** [comment]
This happens pretty regular

**Comment by bqbn** [comment]
Restored data for 10/17 and 10/18.

**Comment by freaktechnik** [comment]
Does not seem fixed for the 18th. Nor the 19th.

**Comment by freaktechnik** [comment]
Ok, it got fixed for the 18th now, but the 19th is still 0, while the 20th has data.
