### ISSUE TITLE
Reviewer Tools URL is causing 404 pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6736]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Go to Tools -> Reviewer Tools option
3. Click on any links that takes you out from Reviewer Tools i.e. "Developer Hub"

Expected results:
User is redirected to the corresponding page.

Actual results:
A 404 page is loaded.

Notes/Issues:
- _while step 3 is made, "reviewers" term is added to the page URL, that becomes - https://reviewers.addons-dev.allizom.org/en-US/editors/_
- the term it cannot be removed
Verified on AMO-dev FF56(Win 7).
Video for this issue:
![revtools](https://user-images.githubusercontent.com/15685960/31775273-cd33686c-b4f0-11e7-9a16-b08205866cef.gif)

**Comment by diox** [comment]
@bqbn could you make the reverse redirects, i.e. when you're already on reviewers.a.m.o domain and trying to load a non-reviewers related URL, it strips the `reviewers.` part of the domain?

**Comment by bqbn** [comment]
Made the reviewers site redirect non-listed endpoints back to the main site.
Please test again.

**Comment by ValentinaPC** [comment]
Seems like the new URL is not causing issues anymore and all redirections work as expected.
Verified on AMO-dev FF56(Win 7).
Postfix video:
![rev tools](https://user-images.githubusercontent.com/15685960/31811091-f16b65e0-b586-11e7-8dd7-f8ce49853f04.gif)
