### ISSUE TITLE
Auto approval is not working anymore on -dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6737]
Steps to reproduce:
1.Submit a new add-on on AMO-dev
2.Wait for auto-approval

Expected results:
Auto-approval is working as expected

Actual results:
Auto approval not working anymore

NOTES;
You can see that https://reviewers.addons-dev.allizom.org/en-US/editors/review/dover-trotartle-koonbilss is not auto approved after more than 15 mins

**Comment by diox** [comment]
Not just auto-approval, all signing is down on dev.

https://sentry.prod.mozaws.net/operations/olympia-dev/issues/673045/

```
ConnectionError: HTTPSConnectionPool(host='signer-addons.allizom.org', port=443): 
Max retries exceeded with url: /1.0/sign_addon (Caused by 
NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x4899d90>:
Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by bqbn** [comment]
Connection restored. The VPN NAT box went down.

```
$ curl -I https://signer-addons.allizom.org/
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 19 Oct 2017 22:30:12 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 153
Connection: keep-alive
```

**Comment by vcarciu** [comment]
Verified as fixed.
