### ISSUE TITLE
Support WebExtensions Dictionaries

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6739]
[Bug 1410214](https://bugzilla.mozilla.org/show_bug.cgi?id=1410214) tracks Add-ons Manager support for WebExtensions packaging for dictionary add-ons. This bug tracks the corresponding AMO work.

There are a few things we need to do:

- [ ] Detect if the XPI is a dictionary and give it the correct type.
- [ ] In the linter, validate that the add-on only includes the dictionary manifest flags. Dictionaries shouldn't run any code.
- [ ] Show an error if a dictionary uses `strict_max_version`, since they shouldn't have compatibility restrictions.
- [ ] Automatically convert all dictionaries on AMO to the new format. This can't be done until they are supported on release, and will require notifying developers as well.

**Comment by diox** [comment]
> Automatically convert all dictionaries on AMO to the new format. This can't be done until they are supported on release, and will require notifying developers as well.

What about ESR? Also, does that mean pushing a new version for each of these add-ons automatically? It might be tricky to figure out the versioning.

**Comment by jvillalobos** [comment]
> What about ESR?

Since this will happen post-57, ESR users will need to look for older versions, like they'll probably have to in other cases. We'll need to set a `minVersion` for all dictionaries once we know which version of Firefox introduces them.

> Also, does that mean pushing a new version for each of these add-ons automatically? It might be tricky to figure out the versioning.

Yes, and yes.

**Comment by muffinresearch** [comment]
Superceded by https://github.com/orgs/mozilla/projects/24

**Comment by diox** [comment]
Not sure why the project is not public, but the plan is still roughly the same as it was laid out in the description of this issue - fairly straightforward, move towards having dictionaries in AMO using a WebExtension-like packaging instead of what we have now.
