### ISSUE TITLE
Server 500 error when uploading new addon locally

### ISSUE THREAD

**Issue by PhillypHenning** [mozilla/addons-server#6741]
### Describe the problem and steps to reproduce it:
1. clone the latest source
2. follow installation steps
3. open browser to olympia.dev
4. Sign in
5. tools > submit new addon
6. using a zip file downloaded from [here](https://staticfil.es/webext-generator/) upload file

### What was expected to happen?
File was uploaded and navigation to next step unlocked

### What actually happened
 `Received an empty response from the server; status: 500`    

### Anything else we should know?

![image](https://user-images.githubusercontent.com/16713447/31797126-b4fa8442-b4fa-11e7-8152-857607c8408d.png)

**Comment by eviljeff** [comment]
You need to look in the logs (`/logs`)to find out what problem you're having.  (The feature isn't generally broken)

**Comment by PhillypHenning** [comment]
Thanks for responding @eviljeff 
So after investigating, I believe I have found the root of the issue,

In my docker.log file I see the issue ```OSError: [Errno 13] Permission denied: '/code/user-media/addons/temp'``` 

Trying to address the issue I created the temp folder and gave it rwxrwxw-x permissions however doing this causes an issue where it complains about missing tables. 

Recreating all tables and addressing the temp directory prior to trying to access the site for the first time after the restart will prevent the above error but will get permanently stuck in the below loopl.  

![image](https://user-images.githubusercontent.com/16713447/31856528-1a6dab78-b691-11e7-90ce-a06fa9051091.png)

**Comment by EnTeQuAk** [comment]
>  prevent the above error but will get permanently stuck in the below loop.

How large is that add-on? Can you make sure that celery is running (`docker-compose ps` and checking logs, specifically `logs/docker-celery.log`)? Celery is used to run asynchronous tasks in the background and this process uses that and waits for the results to come back. That's what the regular GET requests are for.

**Comment by PhillypHenning** [comment]
Hey @EnTeQuAk 

The file is 277 bytes

`docker-compose ps`
![image](https://user-images.githubusercontent.com/16713447/32127011-e96a2b9a-bb41-11e7-83b9-77af636252f2.png)

docker-celery.log
```
usage: celery worker [options] 
celery: error: unrecognized arguments: --autoreload
```
This loops 10 or so times on the last line of the log. 

It's worth noting this is my log directory
![image](https://user-images.githubusercontent.com/16713447/32127126-a6444926-bb42-11e7-8d5a-f3ee161a86bf.png)


If you need any other logs or data, or if you want to work with me to get this solved I would really appreciate the help. I'm doing these bugs for a class and have spent more time stuck here than actually working and it is going to affect my grade. I'm willing to work live with you anytime now until tomorrow night. Thanks!!

**Comment by EnTeQuAk** [comment]
> usage: celery worker [options] 
celery: error: unrecognized arguments: --autoreload

Can you pull the latest docker images via `docker-compose pull` please? That'll fix your celery image. We recently upgraded to Celery 4 which changed how auto-reload works. Also make sure to not just restart the container but to actually `docker-compose stop worker` and then `docker-compose up -d worker` again.

**Comment by EnTeQuAk** [comment]
Also, do you see any other errors in the other log files? `docker.log` might contain the actual traceback.

**Comment by PhillypHenning** [comment]
@EnTeQuAk 
Following your instructions, I pulled and re-up-d the containers. I navigated to the site and received
![image](https://user-images.githubusercontent.com/16713447/32138308-6f1d86a8-bbfe-11e7-8220-2228a8d3f836.png)
This is actually as I expected, as I need to delete and pull the containers everytime I want to load the site. 

docker.log
```
OSError: [Errno 13] Permission denied: '/code/user-media/addons/temp'

Unhandled exception in thread started by <function wrapper at 0x5a3b7d0>
Traceback (most recent call last): 
...
File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysqld' (111)")
```

This may be unrelated, but previous to this I was running Ubuntu 16.04 as well, when I reinstalled my OS I decided to encrypt my hard drive. The project resides in that hard drive, would that affect it?

**Comment by EnTeQuAk** [comment]
>  The project resides in that hard drive, would that affect it?

I doubt that. Looks like MySQL isn't running, do the logs say anything useful? You might want to check the permissions of `user-media` folder and folders inside to make sure they belong to the correct user which breaks the upload as well.

**Comment by PhillypHenning** [comment]
@EnTeQuAk 
What should the permissions be and what do you mean correct user? I am the only user, so should it not only be mine or root?

**Comment by PhillypHenning** [comment]
@EnTeQuAk, I checked the permissions and noticed that most of the files were under my own id, but user-media along with a few others were under root. I changed the ownership, removed and reran but it didn't solve the issue. I'm checking around in my logs and I noticed the following in my `docker.log`

```
You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

OSError: [Errno 13] Permission denied: '/code/user-media/addons/temp'
[02/Nov/2017 19:14:06] "POST /en-US/developers/upload/unlisted HTTP/1.0" 500 198289

File "/code/src/olympia/addons/cron.py", line 11, in <module>
    from celery.task.sets import TaskSet
ImportError: No module named sets
``` 

I ran `python manage.py migrations` but I get `ImportError: No module named olympia.lib.settings_base`

Any suggestions on how I could try an approach fixing these?

**Comment by PhillypHenning** [comment]
While working I also noticed in the docker.log that the MySQLid is complaining 

```
django.db.utils.OperationalError: Problem installing fixture '/code/src/olympia/versions/fixtures/initial.json': Could not load translations.Translation(pk=2): (1366, "Incorrect string value: '\\xCE\\xAD\\xCE\\xBA\\xCE\\xB4...' for column 'localized_string' at row 1")
make: *** [initialize_db] Error 1
Makefile-os:45: recipe for target 'initialize_docker' failed
make: *** [initialize_docker] Error 2
```

**Comment by iamkhush** [comment]
@PhillypHenning were you able to fix the last error somehow - `Problem installing fixture` ?

**Comment by EnTeQuAk** [comment]
> @PhillypHenning were you able to fix the last error somehow - Problem installing fixture ?

This seems to be related to some wrong versions of dependencies, specifically django-extensions. Can you make sure you're running `make update_deps` to fix this?

I'm also closing this, given that the celery startup got fixed a long time ago. If there are any further issues, please step by `#amo` in IRC or open a new issue.
