### ISSUE TITLE
"Try the new frontend" banner is listed in Admin Tools page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6742]
Steps to reproduce:
1. Load Admin Tools page - https://addons-internal.dev.mozaws.net/en-US/admin/

Expected results:
The new frontend banner is not displayed.

Actual results:
The banner is displayed and does not work.

Notes/Issues:
Verified in AMO-dev FF56(Win 7).
Video for this issue:
![admin tools](https://user-images.githubusercontent.com/15685960/31811463-569ce6d6-b588-11e7-8e9e-b5b62133d864.gif)

**Comment by diox** [comment]
As long as it does not break the admin tools themselves, it's not a big deal.

**Comment by ValentinaPC** [comment]
I was logging this only because you mentioned that it should be listed only on public pages.

**Comment by diox** [comment]
Yes ; I was more worried about devhub though ; admin tools are used by so few people (all staff) that it does not really matter there, as long as it does not break the tools themselves.

**Comment by ValentinaPC** [comment]
Yes, seems to be harmless. :)

**Comment by ValentinaPC** [comment]
The banner is no longer displayed in the Admin Tools page.
Verified on AMO-dev FF56(Win 7)
Postfix screenshot:
![admin_tools_-_no_banner](https://user-images.githubusercontent.com/15685960/31877788-7472bef6-b7e0-11e7-98c4-644a91598305.png)
