### ISSUE TITLE
Rename editors to reviewers internally

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6751]
In #6522 we'll rename `/editors/` to `/reviewers/`. Before that, we should rename the django app and urls (keeping the tables intact, at least for now).

**Comment by diox** [comment]
Note: this will change the celery queue name, so need to sync up with ops on that.

**Comment by diox** [comment]
QA: make sure reviewer tools and auto approvals still work fine. All changes here should be internal, everything should still work the same for now (save for a few trivial wording changes).

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7)
1. Auto-approval work as expected
2. Weight is added accordingly
3. Points for reviewer work as expected 
4. Actions like approve content, reject. etc. work as expected
5. Normal reviews work as expected
6. LWT themes approval work as expected
7. Moderated review actions work as expected
8. Links from Reviewer Tools redirect as expected

This can be marked as verified-fixed.
