### ISSUE TITLE
Daily users stats 0 for 19th October 2017

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-server#6759]
### Describe the problem and steps to reproduce it:
The daily users stat count is 0 on the 19.10.2017 for all extensions. This also includes all the substats like versions etc.

### What happened?
The usage stats say 0 users for every extension

### What did you expect to happen?
At least my usage of the extensions should show up (so the stats should have at least one user reported)

### Anything else we should know?
You can observe this for example in these stats: https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/statistics/usage/?last=30

**Comment by jvillalobos** [comment]
Closing as a dupe of https://github.com/mozilla/addons/issues/510
