### ISSUE TITLE
Themes option from Reviewer Tools is not marked as selected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6760]
Steps to reproduce:
1. Load Reviewer Tools homepage i.e. https://reviewers.addons-dev.allizom.org/en-US/editors/
2. Click on "Themes"

Expected results:
Themes option is selected.

Actual results:
Add-ons option is selected.

Notes/issues:
- page content and URL are change accordingly 

Verified on AMO-dev FF56(Win 7). not reproducing on -stage.
Video for this issue:
![themes rev tools](https://user-images.githubusercontent.com/15685960/31935978-e075d718-b8b8-11e7-87ef-67df4df7d257.gif)

May be related with https://github.com/mozilla/addons-server/issues/6751

**Comment by diox** [comment]
Definitely related to #6751. I'll look into it today.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix video:
![rev tools](https://user-images.githubusercontent.com/15685960/31990915-1e683996-b97f-11e7-8cac-a01ed7ec926b.gif)
