### ISSUE TITLE
Rename reviews to ratings

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6761]
Both internally and in the API, we should rename `reviews` to `ratings` to avoid clashing with `reviewers` (see #6751). For the API we should keep things backwards-compatible for now.

- [x] Move the app (and templates, fixtures etc)
- [x] Change the URL names
- [x] Change the model names
- [x] Change functions/methods/classes names (API only)

**Comment by milupo** [comment]
I have already proposed this in the following issue:

https://github.com/mozilla/addons-server/issues/2513

It will help translators to differentiate between ratings and checkups which both are still called "review".

**Comment by diox** [comment]
This is a different issue. I completely agree with you, but I'm not planning to change the strings/translations yet.

**Comment by diox** [comment]
I've opened up https://github.com/mozilla/addons-server/issues/6849 to change the API urls, splitting that task into a different issue.

I'm not sure we'll want to take care of the database yet because it has tons of implications (renaming indices, dealing with the fact that some people might have queries saved in redash, etc) so I am not planning to handle that for now.

**Comment by diox** [comment]
QA: the changes in this issue should be completely transparent to end-users. Please verify that posting/editing/listing/moderating user ratings on add-ons still work.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev FF57 (Win 10)
I've taken the following action for user reviews:  submitting editing, flagging, posting developer replies, moderating (from Reviewer tools - Moderated reviews queue).
Everything seems to be working as expected, apart for the review counts mentioned in [#3904](https://github.com/mozilla/addons-frontend/issues/3904)
