### ISSUE TITLE
Correctly handle static themes in devhub

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6764]
* Properties not applicable to static themes shouldn't be shown or editable in edit listing
* version edit shouldn't allow extra applications to be added or platforms modified.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7)

> Properties not applicable to static themes shouldn't be shown or editable in edit listing
- EULA, Privacy Policy and Custom License fields were removed
![2017-11-06_1451](https://user-images.githubusercontent.com/15685960/32441885-fa0377dc-c301-11e7-95ba-b8c2480e306e.png)
- Experimental option, Require payment, Icon and screenshots, Description, Developer Comments, Required Add-ons, Add-on Flags, View Source were removed
![2](https://user-images.githubusercontent.com/15685960/32442189-2c68d6f8-c303-11e7-9d45-52551f8efdb2.png)
![no_desc](https://user-images.githubusercontent.com/15685960/32442194-2ed13aca-c303-11e7-8e48-817d9dcfa8af.png)
![td](https://user-images.githubusercontent.com/15685960/32442209-3c45d526-c303-11e7-8777-d694d02f853e.png)

@eviljeff : Also, I have a question to this section: static theme will be auto-approved? if "yes" ok, if "no", there is no use of the "add-on reputation" field.

> version edit shouldn't allow extra applications to be added or platforms modified.
- no extra application or platforms can be added
![2017-11-06_1502](https://user-images.githubusercontent.com/15685960/32442426-155bdb1c-c304-11e7-8fd6-5c53f886746d.png)

**Comment by eviljeff** [comment]
@ValentinaPC static themes won't be auto-approved (at least that's the current idea).  The add-on reputation field is there for all add-ons (i.e. non-webextensions too) though.  I'm not concerned because it's an admin only setting.

**Comment by ValentinaPC** [comment]
This can be marked as verified fixed based on above comments.
