### ISSUE TITLE
New monetary donation mechanism doesn't include recommended donation amount

### ISSUE THREAD

**Issue by jikamens** [mozilla/addons-server#6768]
It is a significant regression in functionality that users who contribute to add-ons through the new contribution mechanism are not given a recommended contribution amount. I think this is very unfortunate and I wish this functionality were restored.

**Comment by jvillalobos** [comment]
Since we're not doing more than link to the payment URL, we can't really tell the payment provider to default to a particular amount. However, I know there are ways to set up Paypal URLs with a predefined amount. So, it's up to the payment provider to support URLs that have parameters for this.
