### ISSUE TITLE
Change links in Tools section on signed-out Dev Hub landing

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#6772]
![image](https://user-images.githubusercontent.com/15685960/31991953-a00490c4-b981-11e7-986d-f5457a2035f5.png)

Please change the three links to the following:

[Web-Ext](https://github.com/mozilla/web-ext)
A command line tool to build, run, and test extensions.

[Add-on Validator](https://addons.mozilla.org/developers/addon/validate)
Automated code tests for your add-on. 

[Compatibility Test](https://www.extensiontest.com/)
Check to see if your extension is compatible with Firefox.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7)
Postfix video:
![tools](https://user-images.githubusercontent.com/15685960/32092783-99a3ea72-bb02-11e7-8166-e9278dd04160.gif)

@atsay : I saw you changed the "Compatibility Checker" link to "Compatibility Test" link. 
Should we change it in Tools section from the footer section or there should stay the old option?
