### ISSUE TITLE
Elasticsearch 5.5 upgrade

### ISSUE THREAD

**Issue by Sancus** [mozilla/addons-server#6775]
In the processing of setting up addons.thunderbird.net (bug 1399129) I was going to use the Amazon AWS ES service to save some setup time, but seems like it only supports ES 5.3 and 5.5... whereas addons-server is on 5.4.

If this is a drop-in upgrade with no changes it'd be handy to do, if not I'll just have to do my own ES cluster setup.

**Comment by Sancus** [comment]
@EnTeQuAk ^

**Comment by EnTeQuAk** [comment]
Looks like things work perfectly fine with ElasticSearch 5.5 so you should be able to use that. Our unittests are running on the latest 5.x branch currently anyway.
