### ISSUE TITLE
Firefox static themes category found in search suggestions for add-ons

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#6778]
Steps to reproduce:
1.Go to https://addons.mozilla.org/en-US/firefox/
2.Enter "fire" search term in add-ons search box
3.Observe the "Firefox" category under search suggestions
4.Click on the category from step 3 and observe that will open a 404 : https://addons.mozilla.org/en-US/firefox/static-themes/firefox

Expected results:
The "Firefox" static themes category under search suggestions should not be displayed

Actual results:
The static themes category is displayed in search suggestions

Please see a video with this issue:
![static](https://user-images.githubusercontent.com/1583842/32066962-29b7c09e-ba8a-11e7-8e72-01415918fcc7.gif)

**Comment by eviljeff** [comment]
So, these categories for Static Themes do exist (they're named the same as the Persona categories), but I didn't expect them to show up anywhere if there weren't any static themes submitted.

**Comment by vcarciu** [comment]
Verified as fixed : 
![static](https://user-images.githubusercontent.com/1583842/32112357-bace1130-bb45-11e7-9d21-eb6ed38792a2.gif)
