### ISSUE TITLE
Dead link on https://developer.mozilla.org/en-US/docs/Toolkit_version_format

### ISSUE THREAD

**Issue by ingoe** [mozilla/addons-server#6780]
### Describe the problem and steps to reproduce it:
On the Page https://developer.mozilla.org/en-US/docs/Toolkit_version_format is a dead link called "maintenance policy"

### What happened?
Clicking the link results in a "Not Found" error page on https://addons.mozilla.org/en-US/developers/docs/policies/maintenance#beta-addons

### What did you expect to happen?
Correct page is displayed.

**Comment by eviljeff** [comment]
MDN is outside of AMO so it's not an issue that belongs here exactly.  It's a wiki though, so feel free to change it yourself.  The content is on MDN now https://developer.mozilla.org/en-US/Add-ons/Distribution#Beta_versions
