### ISSUE TITLE
Return compatibility info for dicts, search engines, and persona add-ons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6781]
### Describe the problem and steps to reproduce it:

Make an API request for an add-ons of type dict, search engine, and persona. Examples:

* `curl 'https://addons.mozilla.org/api/v3/addons/addon/afrikaans-spell-checker/' | jq .current_version.compatibility`
* `curl 'https://addons.mozilla.org/api/v3/addons/addon/gift-from-butterfly/' | jq .current_version.compatibility`
* `curl 'https://addons.mozilla.org/api/v3/addons/addon/google-default-1/' | jq .current_version.compatibility`

### What happened?

They all have `current_version.compatibility = {}` (empty)

### What did you expect to happen?

They should specify a min/max version for all supported client apps.

**Comment by diox** [comment]
Yeah, I thought it was a good idea to [make them return `{}`](https://github.com/mozilla/addons-server/blob/30332f629bd3b3ebcafc673371dcdf90560906fb/src/olympia/addons/serializers.py#L152-L153) but it's clearly not. They should return a full compatibility info object for all client apps. 

[We do something like that in `Addon` model](https://github.com/mozilla/addons-server/blob/30332f629bd3b3ebcafc673371dcdf90560906fb/src/olympia/addons/models.py#L1229-L1239), but don't include min/max versions. [In the indexer](https://github.com/mozilla/addons-server/blob/30332f629bd3b3ebcafc673371dcdf90560906fb/src/olympia/addons/indexers.py#L227-L262) though, we almost do the right thing and fake min/max versions, except it's a bit hackish and we don't bother with human-readable versions.

We need to unify all this mess. Maybe use the version info from product details, or fake a very big max one like we do in the indexer.

**Comment by ValentinaPC** [comment]
Please add some STR or the label "qa: not needed". Thanks!

**Comment by diox** [comment]
@kumar303 are you ok with testing that yourself ?
