### ISSUE TITLE
"About" link from Developer Hub page loads a -prod page if accessed from -stage /dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6789]
Steps to reproduce:
1. Load Dev Hub page https://addons-dev.allizom.org/en-US/developers/
2. Go to page footer and click on "About" from Community section

Expected results:
-dev server corresponding page is loaded.

Actual results:
-prod server corresponding page is loaded.

Notes/Issues:
- we have this page available for each server and we load it while accessed from public pages footer.
Verified on AMO-dev FF56(Win 7). Issue is also reproducing on -stage.
Video for this issue:
![wrong server](https://user-images.githubusercontent.com/15685960/32163984-c324545c-bd66-11e7-92a3-0f258470b9da.gif)

**Comment by rafspiny** [comment]
I guess that a small change in the [footer.html](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/new-landing/components/footer.html#L19) file like the one below should be enough:
`<li><a href="{{ url('pages.about') }}">{{ _('About') }}</a></li>`

If it's ok, there is already a pull request for it

**Comment by vcarciu** [comment]
Verified as fixed: 
![about](https://user-images.githubusercontent.com/1583842/36964857-92cde1b2-2060-11e8-8044-2480b37729d3.gif)
