### ISSUE TITLE
No link from Developer Hub back to main Add-ons site

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#6791]
Originally filed by @jvillalobos at https://github.com/mozilla/addons-frontend/issues/3682

-----

Go to https://addons.mozilla.org/developers/. There's no link pointing back to addons.mozilla.org. It should probably be in the header.

**Comment by ValentinaPC** [comment]
This was logged a while ago: https://github.com/mozilla/addons-server/issues/4580
