### ISSUE TITLE
API does not return all reviews immediately after submitting a new review

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6800]
### Describe the problem and steps to reproduce it:

See https://github.com/mozilla/addons-frontend/issues/3720

I can reproduce it every time on the hosted dev server but for some reason I cannot reproduce it when running a local proxy to dev.

Here is what the frontend code does if you look at the Network panel in the devtools:

1. User first loads the all reviews page:

```
[Some initial GETs are on the server, then...]
GET https://addons-dev.allizom.org/api/v3/reviews/review/?user=10641514&addon=494845&version=1533058&lang=en-US
```

2. User selects a star to submit a rating. This begins by submitting the star without any text:

```
POST https://addons-dev.allizom.org/api/v3/reviews/review/?lang=en-US
{"addon":494845,"rating":4,"version":1533058}
```

3. User enters text for the review. This updates the rating with text.

```
PATCH https://addons-dev.allizom.org/api/v3/reviews/review/562135/?lang=en-US
{"rating":4,"body":"New review 8"}
```

4. The frontend *erases* all reviews and re-fetches them from the API

Due to a couple of events happening at once it re-fetches some data twice. This probably needs to be optimized. Here is the full sequence:
```
GET https://addons-dev.allizom.org/api/v3/reviews/review/?addon=mingrafow-crafow-donbise&api=&page=1&filter=without_empty_body
GET https://addons-dev.allizom.org/api/v3/addons/addon/mingrafow-crafow-donbise/?lang=en-US
GET https://addons-dev.allizom.org/api/v3/reviews/review/?addon=mingrafow-crafow-donbise&api=&page=1&filter=without_empty_body
```

### What happened?

Both responses to `https://addons-dev.allizom.org/api/v3/reviews/review/?addon=mingrafow-crafow-donbise` exclude the *last* review in the list but they do include the newest review just posted. If you refresh the page you can see the last review.

### What did you expect to happen?

It should include all reviews.

**Comment by kumar303** [comment]
> for some reason I cannot reproduce it when running a local proxy to dev

This is confusing to me ^ I can't spot any differences in the request headers. I also tried clearing the browser cache right before pressing the submit button for the new review -- no difference.

**Comment by eviljeff** [comment]
I can't replicate this on -dev following the steps in mozilla/addons-frontend#3720

**Comment by kumar303** [comment]
I tried again--I can no longer reproduce the bug on https://addons-dev.allizom.org/en-US/firefox/addon/mingrafow-crafow-donbise/reviews/ . 

However, I can reproduce it on other add-on pages. Here is a screencast of reproducing it on https://addons-dev.allizom.org/en-US/firefox/addon/webext-simplegrrss/reviews/ 

I guess it's related to the number of reviews somehow.


![addons-frontend-review-6800 mov](https://user-images.githubusercontent.com/55398/32300363-244813c4-bf27-11e7-8653-304c4cfc1139.gif)

**Comment by eviljeff** [comment]
I tried on some random add-ons and still can't reproduce.

**Comment by muffinresearch** [comment]
Looks like this is going to be tricky to fix unless we can get some reliable STR. I'm going to mark this down as lowish priority, but if anyone has the time to debug it, that would be appreciated.

**Comment by kumar303** [comment]
I can no longer reproduce it so maybe it's fixed. Let's re-open if it happens again.

**Comment by muffinresearch** [comment]
I reproduced it today.

**Comment by AlexandraMoga** [comment]
Yes, I was able to reproduce this as well multiple times

![image](https://user-images.githubusercontent.com/31961530/35846496-9496b146-0b1f-11e8-81e9-68eb20729044.png)
