### ISSUE TITLE
Expose static theme previews in API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6804]
Part of mozilla/addons#501

~To be able to display a preview and other details in the front-end we need to expose meta data and the image files within the theme.~

We just need to add the VersionPreview to the VersionSerializer

**Comment by eviljeff** [comment]
See https://github.com/mozilla/addons-server/pull/7766#discussion_r174069534 for some thoughts/problems around the API and https://github.com/mozilla/addons-server/issues/7563#issuecomment-372465411

**Comment by AlexandraMoga** [comment]
Could you please add some STR to understand what we need to test here?
Thanks

**Comment by diox** [comment]
You should be able to test this by looking at the detail page of a static theme : in both the new and old frontend, its preview should be shown and always match the preview for the current public version (only).

**Comment by AlexandraMoga** [comment]
This was verified via server issue #7756 and frontend issue [#4425](https://github.com/mozilla/addons-frontend/issues/4425)
