### ISSUE TITLE
Investigate speeding up POSTs to the review API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6811]
### Describe the problem and steps to reproduce it:

* Go to the add-ons detail page
* Sign in
* Select a star to post a rating

### What happened?

This sends a POST to the review API. According to our [measurements](https://app.datadoghq.com/dash/391675/amo-prod-frontend-apis-usage?live=true&page=0&is_auto=false&from_ts=1509639617335&to_ts=1509654017335&tile_size=m&fullscreen=false) this is taking almost one second on average.

![amo prod frontend apis usage performance datadog](https://user-images.githubusercontent.com/55398/32348293-521cea94-bfe1-11e7-9836-d4553c020dd8.png)

### What did you expect to happen?

This seems a bit slow. We can do better!

### Anything else we should know?

The STR is important. If you enter text on the next step then you would be doing a PATCH, not a POST, and that is already pretty fast.

**Comment by diox** [comment]
The add-on authors are notified by email of new reviews. That's done in `Review.post_save`, which calls `Review.send_notification_email`, which calls `send_mail_jinja()` : https://github.com/mozilla/addons-server/blob/3e18c9c708b39f9c93174f92c0f3050dc087b0d9/src/olympia/reviews/models.py#L221-L223

`send_mail_jinja()` calls `send_mail()` which defaults to `async=False`, so the email is sent synchronously, during the request-response cycle, which slows everything down. We talked about switching that to `True` by default, I think it's a good example of why this would be a good thing.

**Comment by diox** [comment]
cc @eviljeff and @EnTeQuAk for any additional input. I believe just changing the `async=False` to `async=True` would dramatically help perf, and be enough to make posting of ratings fast. In fact, I don't see a good reason to keep the `async` parameter at all...

**Comment by EnTeQuAk** [comment]
async=true sounds like a great plan to me and I don't see any problems
doing that by default. It actually increases stability of email sending
since our tasks automatically retry while sync sending doesn't.
Let's do this. 


On Thu, Nov 2, 2017, at 09:28 PM, Mathieu Pillard wrote:
> cc @eviljeff[1] and @EnTeQuAk[2] for any additional input. I believe
> just changing the async=False to async=True would dramatically help
> perf, and be enough to make posting of ratings fast. In fact, I don't
> see a good reason to keep the async parameter at all...> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 

Links:

  1. https://github.com/eviljeff
  2. https://github.com/entequak
  3. https://github.com/mozilla/addons-server/issues/6811#issuecomment-341548057

**Comment by eviljeff** [comment]
Changing to `async=True` works, though it's highlighted that the email process for ~reviews~ ratings is broken.  It's unconnected to speed ups so I've logged this as #6817

**Comment by diox** [comment]
Keeping this opened to see if #6868 makes a difference.

**Comment by diox** [comment]
It's better now with #6868, but not amazingly so. I'll keep this open if anyone wants to pick it up.

**Comment by diox** [comment]
Definitely fixed now:
`Avg: 158.83 addons_prod.view.olympia.ratings.views.RatingViewSet.POST.95percentile`
