### ISSUE TITLE
Search: Remove prefix boosting

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6815]
We currently apply a `1.5` boost to prefix queries. I honestly don't see this being useful since imho most of our searches are based on add-on names or phrases of things a user wants to achieve (e.g "video upload" or "ublock").

We don't have any data on that though so this is just a guess.

As far as I can tell from a bit of research, prefix queries quite cluster-performance heavy so if we can get rid of them without any negative effects on search quality - let's do this. Less querying/filtering is usually good.

Opinions about that @diox?

**Comment by diox** [comment]
It may still be useful in some cases though. Maybe limit it to one-word queries only?

**Comment by EnTeQuAk** [comment]
Yeah, prefix boosting is very helpful for our current implementation of search suggestions. Removing it makes things a lot worse imho.

I'm closing this since it's indeed useful :)
