### ISSUE TITLE
Missing stats for daily users

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-server#6816]
Daily user count is missing for Oct 30 and Nov 1. Missing statistics has been a recurring issue, are there any checks in place for the scheduled tasks which compile these reports, to verify that they have completed successfully?

**Comment by bqbn** [comment]
Closed as a dup for https://github.com/mozilla/addons/issues/510.

These are caused by the delay from our upstream data source. We've filed an internal ticket for our data team to look into it.
