### ISSUE TITLE
Emails to developers about add-on ratings don't contain review text

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6817]
The email process for ratings is broken - we only email when the rating is first created, not on any subsequent changes to text/score.  As the pattern now used by frontend is to create the rating without the text, then amend after, we always email the developer incorrect details about the rating left.

The simplest fix is probably just to email on rating edit.

**Comment by jvillalobos** [comment]
It might be a good idea to have a delay before sending the email, to make sure all edits are done and the developer isn't emailed multiple times per rating/review.

Also (maybe out of scope but relevant), we should consider sending a summary of reviews on a daily or weekly basis, since some developers have been hit by review spammers and get dozens or even hundreds of emails.

**Comment by Rob--W** [comment]
> Yeah, sending a daily summary instead of per review would solve this.

Can this be opt-in, or can the frequency be configurable to sooner than once a day, e.g. once an hour?

**Comment by jvillalobos** [comment]
I don't think it's worth making it configurable. If a developer wants to monitor their reviews real-time (say, because of a recent release), they can just go to the reviews page and reload it as needed.

**Comment by dessant** [comment]
> they can just go to the reviews page and reload it as needed.

Would you spend your time refreshing the review page to see if there are any questions to answer or issues to resolve?

Giving developers a chance to react in a timely manner is useful, and they shouldn't continuously reload a page to do so. A delay of 5 minutes is enough to take care of the initial review edit, though a daily summary is also interesting, as long as it will be introduced as an option.

**Comment by dessant** [comment]
A different approach would be to not include the review text in the mail, but link to the review directly. Some sites do this and it seems to be a decent compromise, it depends on what's the real purpose of the mail: to notify about the existence of a new rating/review, or to deliver written reviews to your inbox.

**Comment by diox** [comment]
> A different approach would be to not include the review text in the mail, but link to the review directly.

Not sure about everyone else but I like this idea :)

**Comment by eviljeff** [comment]
The developer who's monitoring carefully and receiving small number of reviews wouldn't mind a link; but if there are hundreds a day it's no improvement really - you still get spammed with hundreds of emails, and have to click on a link for each.  Really we're talking about 2 different types of developer and a fix for one isn't going to help the other.

**Comment by dessant** [comment]
This is why introducing a new option for sending a daily summary is worth exploring, while omitting the review text from immediate notifications solves this issue.

**Comment by jvillalobos** [comment]
> Would you spend your time refreshing the reviews page to see if there are any questions to answer or issues to resolve?

I wouldn't be monitoring my reviews so intently in the first place, no. Replying within a day is more than reasonable, IMO, especially considering that developer replies to reviews aren't all that common. I'd rather avoid adding configuration options that will be rarely used, even if it's less than ideal for a few power users.

But I agree that the missing text issue is what matters most now, and I've been hearing more about it from developers, so we should look at a short term fix.

**Comment by dessant** [comment]
> Replying within a day is more than reasonable, IMO, especially considering that developer replies to reviews aren't all that common.

@jvillalobos, that sounds like confirmation bias. 😋 

Not all reviews need to be replied to, but you want to be notified in time if something is worth reacting to (if you have enabled the option for sending notifications for new reviews). I also think there are more people caring about the work they've shared on AMO, than a few power users.

**Comment by ghostwords** [comment]
Chiming in as an add-on developer ([Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/)). It seems like we've got two things happening here at least:
- Review notifications emails used to include text but no longer do. This is a bug.
- Various ideas for making notifications emails nicer.

I suggest fixing the bug first and considering potential enhancements at a more leisurely pace.

A somewhat related bug is that now it seems you can leave a review without any review text, which didn't appear to be the case in the past: https://github.com/mozilla/addons/issues/531.

**Comment by jvillalobos** [comment]
Allowing ratings without a written review is an intentional change.

**Comment by ghostwords** [comment]
Ah OK, well then I think it's an ill-considered change, as it gives developers no tools to understand or respond to negative reviews. I don't mean to derail this issue though; would it worth to open a new one to express my problem with allowing no-text reviews?

**Comment by dessant** [comment]
@ghostwords, I have opened one some time ago, if you'd like to share your thoughts there.

https://github.com/mozilla/addons-frontend/issues/3628

**Comment by eviljeff** [comment]
@jvillalobos revised template:
```
{% block content %}
A user has rated your add-on, {{ name }}.

Rating:
{{ rating.rating }} out of 5 stars.

You can read the review text, if left by the user, and reply to it here:
{{ reply_url }}
{% endblock %}
```
?

**Comment by jvillalobos** [comment]
wfm. What does the page look like if it's only an empty rating?

**Comment by Rob--W** [comment]
Could you also include a publicly viewable review link (i.e. reply_url without the trailing "/reply")?
That allows me to view the review without signing in to AMO.

**Comment by eviljeff** [comment]
Good point, I'll just link to the public url and the developer can login and click the reply link if they want to reply.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF57(Win 7).
Format of the e-mail sent to developers about a review is:
![review_mail](https://user-images.githubusercontent.com/15685960/33258472-5fb97e62-d362-11e7-8157-4ce88911ddc5.png)
Mails are generated for empty reviews as well.

Review updates can also be seen updated in the link from the mail, but another mail is not sent.
Is this intended?

**Comment by eviljeff** [comment]
That's intended.

**Comment by ghostwords** [comment]
An add-on developer's experience before the AMO redesign: You get emails containing review text every time a review is left. You can quickly see whether you need to visit AMO to respond to the feedback/misplaced support requests.

After the redesign: You get a higher volume of emails (now that one can leave text-free "reviews"), none of them containing review text. There is no way to tell if you need to visit AMO.

**Comment by vanowm** [comment]
Why this issue is tagged as "fixed" and closed? it's not fixed!
