### ISSUE TITLE
Re-word "View mobile site" Link

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6819]
Currently we have the "View mobile site" link on the old site, and this is not very accurate. 

Let's update it to something that reflects the new site's capabilities a bit better.

**Comment by devaneymoz** [comment]
How about: "View the new site"

Even at four words it would be the wordiest of the footer links.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev FF56 (Win10)

![image](https://user-images.githubusercontent.com/31961530/32436142-bcf28056-c2eb-11e7-9e35-f7ce5eb65558.png)
