### ISSUE TITLE
Post-Review: Higher Weighting for minified Code

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#6821]
I came across an add-on with 3600+ users with minified/obfuscate code that had a weighting of 10 which would be ignored.
There have been other similar instances.

IMHO, minified code (e.g. if a line of code had more 200 characters) should get a much higher weighting.

Example:
`https://reviewers.addons.mozilla.org/editors/review/861392/`

**Comment by jvillalobos** [comment]
Having minified or obfuscated code is not a great signal on its own. Most add-ons will be flagged by this in one way or another, so increasing this number won't make this add-on stand up much more. The abuse reports and increased usage of the add-on should increase its weight in relation to others and make it more likely to be reviewed.

**Comment by wagnerand** [comment]
I agree with erosman here. Given the amount of webextensions that minify code, and the impact minified code can have, we need to increase the weight.

**Comment by wagnerand** [comment]
Philipp and I are working on updating the weights, risk categories and points. I'm closing this an open a new issue once we have the final numbers.
