### ISSUE TITLE
Port from "fuzzy" query to "match + fuzziness"

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6824]
At https://qbox.io/blog/elasticsearch-optimization-fuzziness-performance and other places it's generally adviced that a `match + fuzziness option` is a better candidate than an actual `fuzzy` query.

It also analyzes the query text before performing the search which imho sounds preferable.

Supports https://github.com/mozilla/addons-server/issues/6116

**Comment by ValentinaPC** [comment]
Please add some STR or the label "qa: not needed".
Thanks!

**Comment by EnTeQuAk** [comment]
Nothing specific to test except to make sure that simple typos still lead to correct search results.

E.g https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=Firex+Lightbeam

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshots:
![2017-11-07_0921](https://user-images.githubusercontent.com/15685960/32481679-1bdf47a0-c39d-11e7-979c-a479371fe571.png)
![2017-11-07_0921_001](https://user-images.githubusercontent.com/15685960/32481680-1c01ab92-c39d-11e7-96df-aa1bd788f1b6.png)
