### ISSUE TITLE
Use different admin flag for content review

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6826]
This is a followup for #6310.

The original issue requested to use the same admin review flag for code review and content review. Discussing with @wagnerand, clearly there are use cases where those flags should work independently. So, we'll need these changes:

- [ ] Have two admin review flags, something like `admin_code_review` and `admin_content_review`.
- [ ] Content review can still be done for add-ons that have `admin_code_review`, by any content reviewer.
- [ ] Code review can still be done for add-ons that have `admin_content_review`, by any code reviewer.
- [ ] The code review queues only display the `admin_code_review` flag.
- [ ] The content review queues only display the `admin_content_review` flag.
- [ ] Only admin content reviewers can do a content review for an add-on with the `admin_content_review` flag.
- [ ] The same permission is used for admin code reviewers and admin content reviewers (`ReviewerAdminTools:View`, I think). 
- [ ] Admins can unflag add-ons in their respective review pages.

**Comment by wagnerand** [comment]
1) Should we send emails to developers when their add-on is escalated for content?

I'd say probably not.

2) Should we disable the listing when the add-on is escalated for content?

Might be worth considering.

**Comment by jvillalobos** [comment]
> 1. Should we send emails to developers when their add-on is escalated for content?

> I'd say probably not.

Agree. We introduced emailing for admin escalation because we wanted devs to be aware of why their review might take longer. It's not relevant for post-review.

> 2. Should we temporarily disable the listing while the add-on is escalated for content?

> Might be worth considering.

Let's not do that for now. If it becomes a problem, then sure. I'm thinking that in clear cases where something should be disabled, it will be rejected. Escalations should be used in cases where the decision isn't clear.

**Comment by jvillalobos** [comment]
I'm being informed that content reviewers will be onboarded recently and this will become a problem soon, so I'm setting a high priority for this.

**Comment by ValentinaPC** [comment]
> Have two admin review flags, something like admin_code_review and admin_content_review.

Where can we see these 2 flags?

**Comment by diox** [comment]
@ValentinaPC you need to be an admin, and they'll appear on the relevant review/content review pages for the affected add-ons, as well as the queues (the add-ons will be hidden from the respective queues for regular reviewers, but not for admins).

Do wait 20 minutes or so though, dev is having issues deploying.

**Comment by ValentinaPC** [comment]
> @ValentinaPC you need to be an admin

I am :)

> Do wait 20 minutes or so though, dev is having issues deploying.

Thanks for the heads up!

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF57(Win 7).

> Have two admin review flags, something like admin_code_review and admin_content_review.
![admin_content](https://user-images.githubusercontent.com/15685960/33207184-6abfd378-d115-11e7-932f-79c983a26ddd.png)
![code](https://user-images.githubusercontent.com/15685960/33207185-6ae45982-d115-11e7-8a64-22cde469ae09.png)

> Content review can still be done for add-ons that have admin_code_review, by any content reviewer.
Add-ons are still in the corresponding queue after flagging.

> Code review can still be done for add-ons that have admin_content_review, by any code reviewer.
Add-ons are still in the corresponding queue after flagging.

> The code review queues only display the admin_code_review flag.
![code2](https://user-images.githubusercontent.com/15685960/33207147-4c0ff5fc-d115-11e7-9f3a-a9419c82a65d.png)

> The content review queues only display the admin_content_review flag.
![2017-11-24_1223](https://user-images.githubusercontent.com/15685960/33207150-5617c688-d115-11e7-8141-88881d43157d.png)

> Only admin content reviewers can do a content review for an add-on with the admin_content_review flag.
Works as expected.

> Admins can unflag add-ons in their respective review pages.
- if same add-on is flagged for both reasons, removing the flag can be done only from the page that was made initially and not the other way around, meaning: removing "admin content review" flag can be don only from content review page - I think this is intended, yes?

Also:
1. Emails are not sent for none of the 2 flagging options.
2. An add-on can be flagged for both code and content review and both checkboxes are listed in each review page (https://reviewers.addons-dev.allizom.org/en-US/editors/review/1-platform and https://reviewers.addons-dev.allizom.org/en-US/editors/review-content/1-platform) - @diox - is this expected?
![mix](https://user-images.githubusercontent.com/15685960/33207247-a4c72c1a-d115-11e7-95c6-cee997f2a23f.png)

**Comment by diox** [comment]
1. Yes. Since it does not block the developer, they are not warned (they are if that's a legacy add-on version)
2. Yes. I was a bit generous with admins here.

**Comment by ValentinaPC** [comment]
We can mark this as verified fixed.
