### ISSUE TITLE
Enable Turkish locale

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6828]
As requested from localizers by email.

**Comment by ValentinaPC** [comment]
I can see a Turkish locale in the language drop-down in all AMO servers.... so I guess I am not looking in the right place?

**Comment by muffinresearch** [comment]
@ValentinaPC this is only for the old site, since this is the addons-server repo.

**Comment by ValentinaPC** [comment]
You are riiiight 👯 

Verified as fixed on AMO-dev FF56(Win 7)
Turkish locale was added.
Postfix screenshot:
![2017-11-06_1624](https://user-images.githubusercontent.com/15685960/32445635-0a9ec300-c30f-11e7-94d3-2ec719c6b45b.png)
