### ISSUE TITLE
Credits page not yet ported over to the new lay-out

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#6830]
https://addons.mozilla.org/en-US/credits

Site credits page hasn't been ported over yet. This page lists all people that have made a substantial contribution to AMO in terms of translation work, list current and former add-on reviewers and their # of total reviews (this information isn't listed anywhere else on AMO) and lists icon packs and how they are licensed, though should probably be updated for the current AMO design.

This is the only public-facing page that gives some of these people just that little bit of recognition for their contributions.

**Comment by jvillalobos** [comment]
We're not planning on porting the credits page. It's often outdated and doesn't cover all contributions. @caitmuenster runs the recognition program and there are other ways we can and should highlight people's contributions. Having an AMO page we have to maintain permanently is not one of them, though.
