### ISSUE TITLE
Add tests that fail if a new locale is added that doesn't exist in settings.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6831]
We have similar in addons-frontend. This will help avoid localizations getting out of sync and inform us when a new locale is added that wasn't previously there.

Basically the test should cross check the locale dirs + po files with the list of languages.

**Comment by EnTeQuAk** [comment]
Ah, you mean a double-check that verifies if something get's added in our locale dir a test will fail? That won't be easily possible since we're bound to what mozilla-product-details support but we can add a test that explicitly fails if a new locale is added that is supported but not yet in settings or in a different constellation. Is that what you mean?

**Comment by muffinresearch** [comment]
@EnTeQuAk yep, it's to check for pontoon adding new localizations which we aren't setup to use. It'll save localisers being confused when they add a new locale.

What's the relationship between site localization and mozilla-product-details, how tightly are they coupled?

**Comment by EnTeQuAk** [comment]
> What's the relationship between site localization and mozilla-product-details, how tightly are they coupled?

Currently very, I'll cc @diox to make sure I don't tell any crap. From what I see product-details is mostly used for our language-tools page in addons-server and for our stats page (for devs to filter by languages). That language-tools page that is now replaced by the new frontend unless I'm mistaken 😆 

So, we don't use it that much but our integration is incapable of dealing with additional locale codes in our settings.

**Comment by muffinresearch** [comment]
> So, we don't use it that much but our integration is incapable of dealing with additional locale codes in our settings.

@EnTeQuAk Is there a test for that? - this sounds like adding a locale to AMO_LANGUAGES that doesn't existing in mozilla-product-details would break things.

**Comment by EnTeQuAk** [comment]
It should break things yes. I know we have a few tests for that, a quick grep shows that at least `src/olympia/browse/tests.py:test_locale_diplay_name` might break.

**Comment by muffinresearch** [comment]
Closing this since it sounds like a non-issue from https://github.com/mozilla/addons-server/issues/6831#issuecomment-346576346
