### ISSUE TITLE
Unknown error message returned - Manual and script/fetch doesn't work

### ISSUE THREAD

**Issue by Noitidart** [mozilla/addons-server#6833]
### Describe the problem and steps to reproduce it:

Manually uploading the attached file at https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted goes through the validation fine. However clicking "Sign Add-on" button causes a "Oops! We had an error." page:

> Oops! We had an error.
>
> We'll get to fixing that soon.
> 
> You can try refreshing the page, or head back to the Add-ons homepage.

Uploading with script is is not giving an informative error either, it gives status of 500 and json is `{ detail:'Internal Server Error' }` Script is:

```
            const body = new FormData();
            body.append('Content-Type', 'multipart/form-data');
            const presignedFile = new File([presignedBlob], 'dummyname.xpi'); // http://stackoverflow.com/a/24746459/1828637
            body.append('upload', presignedFile);

            const res = yield call(fetch, `${AMO_DOMAIN}/api/v3/addons/${encodeURIComponent(signingId)}/versions/${version}`, {
                method: 'PUT',
                credentials: 'include',
                body,
                headers: {
                    Authorization: 'JWT ' + (yield call(generateJWTToken, userKey, userSecret))
                }
            });
```

JWT stuff is fine, it works for others.

### What happened?
500 - Internal Server Error

### What did you expect to happen?
I think this extension should fail signing. I was just hoping for a more informative error. This is the Google Hangouts extension from CWS.

### Anything else we should know?

[IKAsUn20.zip](https://github.com/mozilla/addons-server/files/1443774/IKAsUn20.zip)

**Comment by kjschulz** [comment]
I don't know that this is the same issue, but this was the thread mentioned in the error.  I get the following error in red text:  `Failed to upload to AMO. Internal server error occured, this extension is likely unsupported by the review system and will even fail manual upload.`

**Comment by eviljeff** [comment]
@Noitidart this is hitting an internal exception when generating the slug - the name is too common.  (Probably because you're trying to sign Google Hangouts).    https://github.com/mozilla/addons-server/issues/5955 should fix it eventually, or you could edit the name in the manifest to something more unique before submitting.

**Comment by eviljeff** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/378936/ for our reference.

**Comment by eviljeff** [comment]
going to dupe this to #5955

**Comment by Noitidart** [comment]
Oops @eviljeff I missed your replied excuse that please. Thanks very much for your replies a week ago and sharing the info! I should have searched out that dupe first.
