### ISSUE TITLE
Search: Add exact matching

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6837]
Supports #2661 

Currently, we only have phrase matching and a `match` query on analyzed fields. That can sometimes to issues where a user wants to search for the exact name of an add-on.

Example:

https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=Youtub%27s+Annotations+No+more should match https://addons.mozilla.org/en-US/firefox/addon/youtubes-annotations-no-more/ - it does but it doesn't list it at the top which it should (imho).

![screenshot from 2017-11-06 08-56-06](https://user-images.githubusercontent.com/139033/32430616-5cbf14b2-c2d0-11e7-9daf-a8c5eb0c9b96.png)

Todo:

* [x] Add filter that uses `name_sort` field which is a `keyword` type and not analyzed
* [x] Investigate if we can move `name_sort` to a sub-field like `name.raw` which appears to be more how unanalyzed versions of analyzed fields are used in ES world.
* [x] Add tests that use a similar example like above to test exact matching
* [x] Make sure this works in other common languages (German, French, Chinese, Arabic)

@diox any opinion about moving `name_sort` to `name.raw` like this?

```udiff
diff --git a/src/olympia/addons/indexers.py b/src/olympia/addons/indexers.py
index cb66878ec6..0f671a3d21 100644
--- a/src/olympia/addons/indexers.py
+++ b/src/olympia/addons/indexers.py
@@ -142,10 +142,17 @@ class AddonIndexer(BaseSearchIndexer):
                     'modified': {'type': 'date', 'index': False},
                     # Adding word-delimiter to split on camelcase and
                     # punctuation.
-                    'name': {'type': 'text',
-                             'analyzer': 'standardPlusWordDelimiter'},
-                    # Turn off analysis on name so we can sort by it.
-                    'name_sort': {'type': 'keyword'},
+                    'name': {
+                        'type': 'text',
+                        'analyzer': 'standardPlusWordDelimiter'
+                        'fields': {
+                            # Turn off analysis on name so we can sort by it
+                            # and implement exact matches.
+                            'raw': {
+                                'type': 'keyword'
+                            }
+                        }},
+                    },
                     'persona': {
                         'type': 'object',
                         'properties': {
```

**Comment by muffinresearch** [comment]
@EnTeQuAk presumably this would also impact search suggestions? 

Let me know if you need a new issue for that (see https://github.com/mozilla/addons-frontend/issues/3853 for the issue that I duped to this one).

**Comment by EnTeQuAk** [comment]
Yes it does and should fix mozilla/addons-frontend#3853

**Comment by diox** [comment]
@EnTeQuAk +1 on `name.raw`. How do you plan to handle translations though? Currently `name_sort` just uses the current translation (it uses `addon.name`), and I *think* the index task is always be in english, though I'm not sure.

**Comment by diox** [comment]
(Maybe as a first step translations don't matter, as long as we're consistent and always index that field in english)

**Comment by EnTeQuAk** [comment]
> (Maybe as a first step translations don't matter, as long as we're consistent and always index that field in english)

I think they matter but we can implement that in a second wave of changes. Especially since we might want to think to restructure the mapping a bit if we're going to save the raw translation strings too given that we already have them in `name_translations` but that field is harder to query. I'll look into that and open another issue about that.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF58(Win 7).
Searched for "Adblock Plus" and exact match was not the first result.
Please see screenshot:
![2017-11-14_1112](https://user-images.githubusercontent.com/15685960/32771984-2da36742-c92d-11e7-9d5e-cd0a1072ac29.png)

Reopening.

**Comment by EnTeQuAk** [comment]
my bad, I originally designed this patch to be backwards compatible with the currently indexed data but messed up in between. I'll issue a reindex and update the issue accordingly so you can test again, sorry about that!

**Comment by EnTeQuAk** [comment]
So, this is now on -dev but not really fixed unfortunately, while there are many scenarios that now work better than before - your example doesn't :)

I'd keep this open and work on additional fixes for next week.

**Comment by ValentinaPC** [comment]
@EnTeQuAk : while making a search in AMO-stage, I am not able to find an add-on, after it's exact name.
Example: https://addons.allizom.org/en-US/firefox/addon/kanji-%E6%BC%A2%E5%AD%97-%C4%83%C3%A2%C3%AE%C8%99%C8%9B/
Are this related?

**Comment by EnTeQuAk** [comment]
This should have been significantly better with https://github.com/mozilla/addons-server/pull/7303 so I'm going to close this but please feel free to open a new issue in case you find more examples that don't work.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF58 (Win10, Android 7.0)
I've searched with several add-on examples and here are my observations:
1. `__MSG_egname__ ` - displayed third in search suggestions and results
2. `Search this on` - displayed very low among search suggestions
3. `MyGiganticAddonName` - is placed on the 5th position - might be caused by the unbroken string
4. `To do this and that` - not displayed among search results (name contains 'stop words')
5. `Firefox add-on` - does not display [example for Android ](https://addons-dev.allizom.org/en-US/firefox/addon/multiple-platf/) or [this search pluggin](https://addons-dev.allizom.org/en-US/firefox/addon/firefox-add-ons/) first in the search results
6. `VerCheck07.13.16.3` - is displayed as a first suggestion but other add-ons starting with `VerCheck` will not be immediately displayed among suggestions
7. `axl51UPB1` - displayed first but other examples starting with 'axl' are not displayed immediately after
8. `Tabs, tabs, tabs and more tabs `- displayed first but other examples starting with 'tabs' (ie. [this example](https://addons-dev.allizom.org/en-US/firefox/addon/tabs-tabs-tabs-oop/)) is not displayed immediately after 
9. general observations: 
- it seems like search suggestions are trying to push themes higher in the list, even when there are extensions with a more immediate match (see examples from point  5, 6, 7, 8)
- searching for 'ad block plus' will not return results for `Adblock Plus` when I think it should

**Comment by EnTeQuAk** [comment]
Thanks a lot for testing this, those are great examples!

Let me get into these a bit more.

> 1. `__MSG_egname__ ` - displayed third in search suggestions and results

That's sad, I'll look at that. Imho that shouldn't be.

> 2. `Search this on` - displayed very low among search suggestions

I'm afraid this also contains a stopword with `on` which seems to be a problem with our current implementation.

> 3. `MyGiganticAddonName` - is placed on the 5th position - might be caused by the unbroken string

Hmm, that should indeed match perfectly. Great example, I'll look into it. One thing to note is that there might be other add-ons with similar names rank higher because of weekly downloads or so, it'd be worth taking a look at that too.

> 4. `To do this and that` - not displayed among search results (name contains 'stop words')

Still a great example that should work though.

> 7. `axl51UPB1` - displayed first but other examples starting with 'axl' are not displayed immediately after

That's kinda expected, we prefer prefix-matching starting with 4 characters.

> - searching for 'ad block plus' will not return results for `Adblock Plus` when I think it should

It totally should!

**Comment by EnTeQuAk** [comment]
I'm removing my assignment for now, this got a bit better after the latest search update and might require much more in-depth changes to fix fully.

**Comment by bjherbison** [comment]
Here is an example that is worse than I've come across before:

**Comment by diox** [comment]
Fixing #9196 should fix most of the issues here. One problem that remains is multiple translations for the name, but that's tracked in a different issue, #6898.

Regarding the examples provided in the comments here:
* "Youtube's Annotations No more " is now the first result for "Youtube's Annotations No more " in production
* All examples for https://github.com/mozilla/addons-server/issues/6837#issuecomment-361602802 on dev seem to behave like expected.
* "Currentcy" is now the first result for "Currentcy" in production.

**Comment by AlexandraMoga** [comment]
Confirming what diox mentioned above: search results have improved significantly when it comes to exact matching.
I have run through all the examples mentioned in the issue and they are all displayed first in the list now.

I'm marking the issue as Verified fixed
