### ISSUE TITLE
Exclude deleted add-ons from collections endpoint by default

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6845]
Currently the collections api endpoint includes deleted add-ons by default. 

See https://addons.mozilla.org/api/v3/accounts/account/mozilla/collections/featured-personas/addons/?sort=added for an example.

The suggested approach was to exclude deleted add-ons by default and have a separate param that can be used to request a collection including deleted add-ons for editing purposes. E.g. a `with_deleted` filter.

We should also consider how much the the `with_deleted` would be needed - although I can see that it might be handy to know that an add-on you added to a collection has now been deleted during editing.

**Comment by ValentinaPC** [comment]
I've checked if the list from https://addons-dev.allizom.org/api/v3/accounts/account/mozilla/collections/featured-personas/addons/?sort=added contains any deleted add-on and I did not found any.

Also I created a new collection and tried to add a deleted add-on and was not able.
Note: if I deleted an add-on after it was added inside a collection, it was removed from there too.

Please add other STRs, if we should look for anything else in here. Thanks!

**Comment by eviljeff** [comment]
https://addons-dev.allizom.org/api/v3/accounts/account/mozilla/collections/featured-personas/addons/?filter=all_with_deleted will include the deleted addons (and `filter=all` just the non-public ones) but we don't generally ask for QA the API endpoints directly - when the edit collection functionality is added it'll be used there.  So I don't think anything else.
