### ISSUE TITLE
Map new type params to the old atype params.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6846]
This is the inverse of https://github.com/mozilla/addons-frontend/issues/3791 this will help during the transition so that new frontend pages redirect correctly when served from addons-server e.g. when switching a search page on the new frontend to the old frontend.

`type=extension` -> `atype=1`
`type=dictionary` -> `atype=3`
`type=search` -> `atype=4` 
`type=language` -> `atype=5`

**Comment by muffinresearch** [comment]
@diox since the frontend code has done this in the app, we should do these in the addons-server app too. 

I think we'll probably want to 302 them since if the 301s get cached that could be problematic.

**Comment by vcarciu** [comment]
Verified as fixed : 
![typenewold](https://user-images.githubusercontent.com/1583842/32554022-2a9efd58-c4a1-11e7-99c9-ebaf928e1ad9.gif)
