### ISSUE TITLE
"Abstract" category is returning 500 error page at Static Theme submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6847]
Steps to reproduce:
1. Select a static theme to submit in AMO-dev
2. At details step, pick "Abstract" category
3. Finalize submission

Expected results:
Submission is finalized with succes.

Actual results:
An "Oops..." page is displayed at "Submit version" click.

Notes/Issues:
- did not try all categories

Verified on AMO-dev FF56(Win 7).
Video for this issue:
![500](https://user-images.githubusercontent.com/15685960/32444312-ceabcb8a-c30a-11e7-8602-ad4ab20043d0.gif)

**Comment by eviljeff** [comment]
I think this is a side effect of #6842 - we've run some fixup on -dev so it should be good now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win 7).
Postfix video:
![abstract](https://user-images.githubusercontent.com/15685960/32942601-313153bc-cb92-11e7-98dd-66a7df24cdca.gif)
