### ISSUE TITLE
Change API url for reviews to ratings

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6849]
After https://github.com/mozilla/addons-server/issues/6761 the `reviews` app will have been renamed to `ratings`. Let's also change the URLs for the API, exposing `/api/v3/ratings/`. Also, this may be a good time to expose the value of the rating as a `score` property instead of `rating`. Maybe accept/return both during the transition.

We'll need to keep backwards-compatibility for a little while to get addons-frontend updated.

**Comment by AlexandraMoga** [comment]
I have verified the new /ratings/ endpoint by sending several requests with mixed queries. 
Here are two examples:
```
https://addons-dev.allizom.org/api/v4/ratings/rating/?addon=awesome-screenshot-plus-
```
```
https://addons-dev.allizom.org/api/v4/ratings/rating/?user=10641605&page=2&filter=without_empty_body
```
@diox, just to double check:
`v3` api still uses `/reviews/review/`  to fetch add-on ratings and this endpoint does not work with `v4` api
`v4` api uses `/ratings/rating/`  to fetch add-on ratings and this endpoint does not work with `v3` api
Is this correct?

**Comment by diox** [comment]
> v3 api still uses /reviews/review/ to fetch add-on ratings and this endpoint does not work with v4 api
> v4 api uses /ratings/rating/ to fetch add-on ratings and this endpoint does not work with v3 api
Is this correct?

That is correct.

**Comment by AlexandraMoga** [comment]
I'm marking the issue as verified fixed on AMO-dev.
