### ISSUE TITLE
[TAAR] Pass locale/platform to the TAAR-api when opening the Discopane

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/addons-server#6853]
This is a feature request for the TAAR project. When Firefox opens the Discopane, it sends along some bit of information (locale, platform, ...).

We would love this informations to be propagated to the TAAR api to make use of it if some user requesting recommendations is not in our database.

I will file a similar issue in mozilla/addons-frontend#3804 for the front-end part.

**Comment by muffinresearch** [comment]
@Dexterp37 do you have a specific timeline you need this by?

**Comment by mlopatka** [comment]
@muffinresearch @Dexterp37  It would be ideal if we could land this by November 30th.

**Comment by eviljeff** [comment]
QA - you can test this with mozilla/addons-frontend#3804
