### ISSUE TITLE
Static Theme wizard

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#6860]
It's magic! ✨ ✨ ✨ 
part of mozilla/addons#501

**Comment by ValentinaPC** [comment]
@eviljeff : I have some questions:

1. Will not be better to put "Create theme" button in distribution page?
2. Can we remove the yellow notification banner from theme wizard?
2. Themes submission returns a 500 page, is this the purpose of this issue, or only the availability of the wizard is?

Thanks in advance!

**Comment by eviljeff** [comment]
> Will not be better to put "Create theme" button in distribution page?

The [submission flow doc](https://docs.google.com/document/d/1NB5RNu_eoJmDAlb1V_BrT-4BpmHUc1ZvGjOEZS5hQvQ/edit#heading=h.d2b5xq8gxmbk) shows the link/button on the upload page.

> Can we remove the yellow notification banner from theme wizard?

Which notification banner?  If it's the generic webextension one I think it's enabled on -dev only (or rather, it's been disabled on prod and the waffle switch/flag/etc is still enabled on dev)

> Themes submission returns a 500 page, is this the purpose of this issue, or only the availability of the wizard is?

I'm not sure which 500 error you're seeing - I've just tried and it works.

**Comment by ValentinaPC** [comment]
Please see video:
![upload theme](https://user-images.githubusercontent.com/15685960/33217304-0b2a8e6e-d140-11e7-8d7e-a218fc67807c.gif)

Also...not sure about the selection of colors from the Header area background (accentcolor) * and Header area text (textcolor) * - should look like that?

**Comment by ValentinaPC** [comment]
I think the fix was not properly deployed on my side.
I see other changes.
Let me remake the video.

**Comment by eviljeff** [comment]
yes, looks like your js is out of date.  Maybe a force-refresh?  The 500 is probably because the theme isn't valid - the JS would normally have stopped you from trying to submit in the first place.

**Comment by ValentinaPC** [comment]
Done! Sorry :)

1. Buttons without padding between:
![static_theme](https://user-images.githubusercontent.com/15685960/33217661-7bf36c3c-d141-11e7-93e1-1ee7a125cd15.png)

2. " Select a different header image" positioned wrong (I think)
![2017-11-24_1802](https://user-images.githubusercontent.com/15685960/33217707-bf4da8ee-d141-11e7-9d58-d8ec1b0f88e6.png)

3. "Upload theme" button redirects to submission? I see in the submission flow doc no such button but a "Continue" one (seems more expected)
![upload theme-2](https://user-images.githubusercontent.com/15685960/33217744-f95e4c78-d141-11e7-822d-5265aa9f9a63.gif)

**Comment by eviljeff** [comment]
Hah, your css is out of date too.

**Comment by eviljeff** [comment]
The `Upload Theme` is the `Continue` button.  I named it differently to reflect what it does but I'm expecting some feedback from @jvillalobos about that and the feature in general.

**Comment by ValentinaPC** [comment]
I verified things again using AMO-dev FF57(Win 7).
And things observed last time look nice.
Screenshots:
![static](https://user-images.githubusercontent.com/15685960/33262235-4b603d32-d36e-11e7-86c2-d1a6f224b3d2.png)
![br1](https://user-images.githubusercontent.com/15685960/33262233-4b189644-d36e-11e7-8c24-81251a35982f.png)
![colors_st](https://user-images.githubusercontent.com/15685960/33262234-4b41e972-d36e-11e7-95c4-96e4dabd404f.png)
![uploading](https://user-images.githubusercontent.com/15685960/33262236-4ba31e68-d36e-11e7-9f5d-a73b48a19561.png)

Still, one question to go:
- **the "Select a header image for your Theme." is a mandatory field, that does not return an error if a wrong file is loaded - is this intended?** 
I should mention that if a wrong file is loaded, it is not taken into consideration and theme submission is finalized with succes.

**Comment by eviljeff** [comment]
I'm not sure what you mean by "wrong file" - no file, as shown in the screenshot, or just an invalid image file?

**Comment by ValentinaPC** [comment]
A .json file, a .zip file, etc. - a file that is not mentioned under the "Browse" button.
![zp](https://user-images.githubusercontent.com/15685960/33270144-b1fc716a-d38b-11e7-9bce-ebc2c322d1e2.gif)

**Comment by eviljeff** [comment]
The linter is supposed to pick up invalid image files during the upload but mozilla/addons-linter#1587 isn't done yet so anything is accepted.

**Comment by ValentinaPC** [comment]
Got it.

@eviljeff : We can mark this verified-fixed, or we wait a response from Jorge about:
> The Upload Theme is the Continue button. I named it differently to reflect what it does but I'm expecting some feedback from @jvillalobos about that and the feature in general.

**Comment by eviljeff** [comment]
I'd prefer it in a new issue anyway so if that's it then verified 😉

**Comment by ValentinaPC** [comment]
@eviljeff : Should I log it, or did you already? :P

**Comment by eviljeff** [comment]
Followup issues are for Jorge to file once he decides what actually needs to be changed.

**Comment by ValentinaPC** [comment]
Ok. We can mark this issue verified.
