### ISSUE TITLE
Using a letter to indicate a beta version makes a Firefox extension incompatible with Chrome

### ISSUE THREAD

**Issue by mlissner** [mozilla/addons-server#6861]
### Describe the problem and steps to reproduce it:

In the docs, [it says to use a letter to indicate that an extension is a beta version][b], for example, you might release version `1.0b`. This, alas, makes that extension incompatible with Chrome, which has a different approach to this. I'm trying very hard to have one codebase for Chrome and Firefox (and other browsers, one day), but this is a blocker. Because of this difference I think I'm going to have to have a build system that can generate different manifest files for each browser. 

[b]: https://developer.mozilla.org/en-US/Add-ons/Distribution#Beta_versions

### What happened?

When you try to upload the `1.0b` version into Chrome, it chokes.

### What did you expect to happen?

I expected both browsers to work nicely. 

### Anything else we should know?

I think the best way to do this is to tweak the upload UI a bit so that there's a checkbox that you can use to mark an item as a beta version. I assume on the backend the boolean exists already anyway, so maybe just maybe this is a straightforward change.

**Comment by jvillalobos** [comment]
We plan to remove the beta versions feature in the near future, so we shouldn't spend time making it work with Chrome. As an alternative, developers can submit unlisted beta versions (with whatever version number they want) and distribute them on their own.

**Comment by mlissner** [comment]
> As an alternative, developers can submit unlisted beta versions (with whatever version number they want) and distribute them on their own.

OK, sorry to be a pest, but...I tried this out tonight, and it's a pretty poor substitute. This means that if we want to distribute a beta version, it doesn't wind up on AMO. 

That means that either:

 - We email around a signed XPI. People that install this way don't have an update mechanism and the addon is considered "temporary" according to `chrome.runtime.onInstalled`, or
 - We set up our own distribution channel. This is a lot of work just to do a beta version.

I can't speak for others, but what we need is what we have now, but with the ability to support beta versions via a boolean flag on the backend, not via a letter in the version number. 

Addons distributed that way have an update mechanism, and aren't considered temporary. It's pretty good how it is, and it'd be a shame to take a way and require that we either email around XPIs or set up our own distribution channels.

Can we open this for further consideration?

**Comment by jvillalobos** [comment]
The beta feature on AMO isn't very heavily used, and adds complexity to an already fairly complex system. It doesn't meet developer expectations very well because it's somewhat hidden in the listing page (by design) and developers are stuck updating both channels forever (or leave users stranded in the beta channel since there's no way to move from one to the other).

Using unlisted versions addresses these issues. You're right that there's additional effort the developer has to make to set up a distribution channel, but I don't think it's a very significant effort.

**Comment by mlissner** [comment]
> I don't think it's a very significant effort.

Depends. I don't see a lot of people standing up a server, doing DNS, figuring out Apache, and everything else just to distribute a beta version. That's the opposite of easy in my book, and I'm primarily a backend dev. Could I do it, sure. Am I willing to do it just to host a beta version when Chrome lets me do that already? Probably not.

I'm struggling to respond because of how inadequate I'm finding this plan. You're basically saying that if we want to do a beta version, we have to stand up a server forever. Or abandon Firefox for this purpose and use the Chrome store.

> The beta feature on AMO isn't very heavily used

I bet if it were a checkbox in the UI instead of an arcane version string, it would be used a lot more. I bet it'd be used more if there was a link on the upload page that said, "Beta version? Learn more." Right now it's a secret feature and you're saying nobody uses it so you're going to remove it.

On Chrome, not only do they have a beta channel, but they even [have a controlled roll out feature][c] so you can roll out your extension to only a small percentage of users for testing. This is *so much better* than what you're offering here that I think we have no choice but to treat FF as a secondary platform. First, we'll do a beta version on Chrome, then we'll do a roll out on Chrome, then, and only then will we consider Firefox. And at that point, we'll probably just roll it out to everybody and hope that it doesn't have any FF-specific bugs because...there's no practical way to do a beta version anymore, apparently. 

Can anybody check with Chrome to see how popular their controlled roll out or beta channels are, since they're first class citizens in their web store?

Why not just add a checkbox to the UI instead of doing the version string parsing? It sure seems simple to me.

I'm sorry, but I strongly disagree with this plan. I know you guys are used to donning your asbestos suits, but I still hope you'll reconsider. 


[c]: https://developer.chrome.com/webstore/publish#control-how-fast-your-app-reaches-users

**Comment by jvillalobos** [comment]
> Depends. I don't see a lot of people standing up a server, doing DNS, figuring out Apache, and everything else just to distribute a beta version.

Setting up a server on Dreamhost with a couple of pages shouldn't take more than a few hours. Of course if you want to be more thorough, there's more work to do, but that's your choice.

> You're basically saying that if we want to do a beta version, we have to stand up a server forever.

For as long as you want to maintain beta versions. Migrating users back to the main channel is very easy in this case (and not really possible with the beta implementation AMO uses).

> they even have a controlled roll out feature

That's a nice feature that we may try in the future, but at the moment there is more pressing work to do.

> I'm sorry, but I strongly disagree with this plan.

And I'm sure others agree with you, but our goal is to focus on the site's core features and go back to something that can be maintained long-term. AMO is meant for distributing add-ons to end users. Beta versions are better off being maintained separately by their developers.

**Comment by mlissner** [comment]
> Beta versions are better off being maintained separately by their developers.

Is this something that can be discussed at one of the triage meetings or something? I find it hard to believe that the plan is to not support beta versions of Firefox extensions on AMO.

FWIW, Opera supports beta versions, and they do it with a simple checkbox:

![screenshot from 2017-11-09 14-37-24](https://user-images.githubusercontent.com/236970/32633428-59c7608c-c55c-11e7-8bed-1884b3f5134b.png)

**Comment by jvillalobos** [comment]
That's a hidden add-on, which is a different concept (also supported by the Chrome Store and also considered for future development). The entire listing is only known to people who have the URL.

**Comment by mlissner** [comment]
That seems fine to me. I just want a way to get an extension to a subset of users. If it creates a beta-track for upgrades, that's bonus. But I really just want to way to distribute an add-on that regular, lay, people can use to install it if I give them a URL.
