### ISSUE TITLE
Inconsistent JWT vetting complicates troubleshooting

### ISSUE THREAD

**Issue by cynwoody** [mozilla/addons-server#6862]
### Describe the problem and steps to reproduce it:
It appears parts of AMO understand a JWT with `iat` and `exp` as strings, while other parts subsequently fail on the same faulty JWT with an opaque "500 INTERNAL SERVER ERROR" status.

### What happened?
So, I was setting out to learn the API. I began with the account profile endpoint, that appearing to be the simplest one requiring authentication. I used the following:

`profile.sh`:
```bash
#!/usr/bin/env bash

ttl=$1
url="https://addons.mozilla.org/api/v3/accounts/profile/"
auth="Authorization: JWT $(../bin/jwt_token.py $ttl)"
# auth="Authorization: JWT Hello.cruel.world"
[ "$ttl" != "" ] && sleep $(($ttl+10))
curl -g -H "$auth" "$url" | python -m json.tool
```
`jwt_token.py`:
```python
#!/usr/bin/env python

import imp
import jwt
from os.path import dirname, join, realpath
import random
import sys
import time

topDir = realpath(join(dirname('__file__'), '..'))

cred = imp.load_source('cred', join(topDir, 'mozilla-credentials.py'))

def makeJWT(lifetime = None):
    lifetime = lifetime and int(lifetime) or 5*60
    issuedAt = int(time.time())
    payload = {
        "iss": cred.apiKey,
        "jti": str(random.SystemRandom().random()),
        "iat": str(issuedAt),
        "exp": str(issuedAt + lifetime)
    }
    return jwt.encode(payload, cred.apiSecret)

if __name__ == '__main__':
    print makeJWT(sys.argv[1:] and sys.argv[1] or None),
```
Running `profile.sh` with no operand resulted in a 500 error. So, I ran it with 5 seconds as the token time to live. Note that the script ensures the token will be stale in this case. After 15 seconds, the server again 500'd, but with a `detail` indicating that the cause was an expired token. This outcome lead me to believe the problem was not the token. After all, AMO understood the token well enough to flag it as expired, didn't it?

I also tried a wrong API key, a wrong API secret, and a completely malformed JWT. The server diagnosed all three conditions correctly, further leading me to believe the token was not the cause of the 500 error.  (Although, there should be a better message in the case of an incorrect secret — actually, it should probably be "failed to authenticate" for both bad key *and* bad secret. In any case, the bad-secret response should *not* be "Error decoding signature"!)

So, assuming the problem was  something in the HTTP protocol, I checked that my version of `curl` was up to date. No problem there. I pointed at a server that echoes the headers, and all appeared to be in order.

Finally, I tried `web-ext` signing. It worked. Hmm... Realizing that `web-ext` is in Node, I translated my little example to Node, using `jsonwebtoken` and `node-fetch`. `jsonwebtoken` instantly barfed on my string `iat` and `exp` fields. I fixed them, and my Node version worked. 

Then I fixed the Python, and my original example starting working.

### What did you expect to happen?
I expected the server would have complained intelligibly about my invalid JWT, instead of half-understanding it and obscuring the real problem.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
We shouldn't 500 on anything, it's definitely a bug.

The traceback is https://sentry.prod.mozaws.net/operations/olympia-prod/issues/680287/ - though because it's a re-raise the traceback isn't very useful, so I'm glad to have an example script that caused this.

**Comment by cynwoody** [comment]
Thanks!

That was really fast response.

**Comment by vitaly-zdanevich** [comment]
The same 500 for me, [jwt.io](https://jwt.io) shows me that `Signature Verified` (input string copied from the verbose curl output). My bash script for macOS that generates 500:
```
AMO_JWT_ISSUER=user:<your-numbers>
AMO_SECRET=<your-secret>
JWT_HEADER_BASE64=`printf %s '{"alg": "HS256", "typ": "JWT"}' | base64`

random() {
    dd if=/dev/urandom bs=20 count=1 2>/dev/null | openssl sha1
}
UNIXTIME=`date +%s`
PAYLOAD_JSON='{"iss": "'$AMO_JWT_ISSUER'", "jti": "'$(random)'", "iat": "'$UNIXTIME'", "exp": "'$(($UNIXTIME+99))'"}'
JWT_PAYLOAD_BASE64=`printf %s $PAYLOAD_JSON | base64`
FOR_SIGN="$JWT_HEADER_BASE64.$JWT_PAYLOAD_BASE64"
JWT_SIGNATURE_BASE64=`printf %s $FOR_SIGN | openssl dgst -binary -sha256 -hmac $AMO_SECRET | base64`
JWT=$JWT_HEADER_BASE64.$JWT_PAYLOAD_BASE64.$JWT_SIGNATURE_BASE64

curl -v https://addons.mozilla.org/api/v3/addons/ -g --form "upload=@$FILEPATH" -F "version=1.0" -H "Authorization: JWT $JWT"
```

**Comment by vitaly-zdanevich** [comment]
My code above is correct?
