### ISSUE TITLE
Discover if signed in user can reply to a review via API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6863]
In the frontend we want to implement this user flow for https://github.com/mozilla/addons/issues/526:
* Sign in as an **unlisted** developer, viewer, or support user of an add-on
* Go to the detail page for the add-on
* Click *Read N reviews*
* Reply to a review

We currently cannot show a *reply* button because don't know if the user has the access rights. They are not included in the list of add-on authors returned from the add-on detail API (which is how we would normally know).

The Django site checked for access like this: https://github.com/mozilla/addons-server/blob/c0d8e97cb7251d0702c0b8b4c18a5e9d9127680a/src/olympia/reviews/views.py#L82-L83

What API could return this information? Do we need a new API?

One possibility would be to include this information in the response to [list reviews](https://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#list-reviews) because the frontend will make request to this endpoint as an authenticated user.

**Comment by diox** [comment]
> One possibility would be to include this information in the response to list reviews because the frontend will make request to this endpoint as an authenticated user.

That's probably our best bet. The issue I have with it is that making responses content depend on authentication+permissions opens a can of worms that I didn't want to deal with, since it kills any future potential caching etc... Returning a 403 or a 200 is one thing, changing content completely is another... but I guess we don't have a choice.

**Comment by kumar303** [comment]
In case it would help for caching we could add a filter like:

```
GET /api/v3/reviews/review/?show_permissions_for_user_id=1234
```

If user `1234` were not authenticated when making the request then it would be a 403.

The frontend would only add this filter when viewing the review list while signed in.

**Comment by diox** [comment]
Yeah, I was thinking about something along those lines. We don't have to do this now (since we don't do any caching atm), but this is a good option to keep in mind in the future not just for the review API.

**Comment by kumar303** [comment]
Jorge requested to bump priority of this since some recent changes to the frontend make this bug more visible to developers.

**Comment by diox** [comment]
There is now a new `show_permissions_for` parameter to be used together with the `addon` parameter when requesting ratings through the API. See https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#get--api-v4-ratings-rating-

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with the following method:

1. As a developer, I've added User 1 as an _unlisted_ developer to one of my addons
2. As User 1, I've authenticated through the API and sent the following request:

https://addons-dev.allizom.org/api/v4/ratings/rating/?addon=add-on-indexing&show_permissions_for=10641527

I've checked the response and made sure that the new added `can_reply` property is `true`

I've also made sure that User 1 can indeed leave a reply to a review by using the following endpoint:
`POST /api/v4/ratings/rating/(int: id)/reply/`
