### ISSUE TITLE
License is not listed in static theme details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6873]
Steps to reproduce:
1. Submit a static theme i.e. https://addons-dev.allizom.org/en-US/firefox/addon/st-11/
2. Observe its license

Expected results:
Selected license at submission is listed in theme details page.

Actual results:
Selected license at submission is not listed in theme details page.

Notes/Issues:
Verified on AMO-dev FF56(Win 7).
Screenshot for this issue:
![2017-11-09_1616](https://user-images.githubusercontent.com/15685960/32609781-72781592-c569-11e7-8ad9-470541830d0e.png)

**Comment by ValentinaPC** [comment]
Not sure if here is the right repository for this issue. Let me know.

**Comment by eviljeff** [comment]
That looks like the new frontend so it'd be mozilla/addons-frontend instead, though mozilla/addons-frontend#3388 hasn't been implemented yet so I wouldn't expect them much about their detail pages to work.

**Comment by AlexandraMoga** [comment]
License is now displayed on static theme details page

![image](https://user-images.githubusercontent.com/31961530/43442822-cecec968-94a7-11e8-951f-c4c1c0792493.png)
