### ISSUE TITLE
"View on site" link from Abuse Report admin page is returning a 500 error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6874]
Prerequisites:
User is logged with on admin account.

Steps to reproduce:
1. Load Admin Tools page https://addons-internal.dev.mozaws.net/en-US/admin/models/
2. Go to Abuse Reports page https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/
3. Click on any abuse report i.e. https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/24507/
4. Click on "View on site" link from top right side of the page

Expected results:
Corresponding page is loaded.

Actual results:
A 500 "Oops..." page is loaded.

Notes/Issues:
Reproducing on both -dev and -stage.
Video for this issue:
![view](https://user-images.githubusercontent.com/15685960/32612308-9bddc286-c570-11e7-9133-3feb2b1cf610.gif)

**Comment by eviljeff** [comment]
The 'view on site' links in django admin don't work (or rarely do - I think I did find one model that did). 
I'm tempted to say wontfix.
