### ISSUE TITLE
Post-Review: New Upload Removes the Info request Flag

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#6878]
Normally, once and Info Request is made, add-on is flagged with an Info request flag.

It seems, developer can then upload a new version and the info request is cleared.
This would enable developer to ignore and bury such requests.

Example:
`https://reviewers.addons.mozilla.org/editors/review/866778/`

Info request for Version 1.0.2  on Nov. 7, 2017, 10:28 a.m.
Version 1.0.3 · Nov. 7, 2017 · Approved
No Info Request flag

**Comment by eviljeff** [comment]
the logic is that the new upload might be addressing the upload request.
@jvillalobos for his learned opinion.

**Comment by jvillalobos** [comment]
While re-uploading could address the info request, I think in most cases it won't, so we might want to change that behavior. Up to @wagnerand and @kewisch to decide.

**Comment by wagnerand** [comment]
I agree that the need-info flag should stay.

We also need to evaluate in which cases we drop the flag (and in which cases we should and shouldn't), but that's out of the scope for this issue.

**Comment by erosman** [comment]
If normal reviewers could also drop the Need Info flag when needed, that would be useful in clearing the unnecessary ones and reduce admin work load.

**Comment by jvillalobos** [comment]
Related to https://github.com/mozilla/addons-server/issues/6991

**Comment by jvillalobos** [comment]
Provided #6991 remains closed, I think this is okay to go forward.

**Comment by AlexandraMoga** [comment]
This issue was fixed in the meantime I believe. The need info flag is not removed on anew version upload unless the developer marks the Information  request resolved checkbox.
