### ISSUE TITLE
Screenshots should display tips while hovering them

### ISSUE THREAD

**Issue by marcoagpinto** [mozilla/addons-server#6879]
### Describe the problem and steps to reproduce it:
Open:
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2/
and hover the mouse over the screenshots.

### What happened?
No tips are shown (they used to be on the old site) and the screenshots don't fit in the gadget.

### What did you expect to happen?
See the tips and the images should fit in the gadget.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Can you please re-file this over https://github.com/mozilla/addons-frontend/ ?
