### ISSUE TITLE
[TAAR] Accessing AMO database from Spark clusters

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/addons-server#6880]
For the [TAAR](https://github.com/mozilla/taar) project we need access to the details of all public addons from our Spark clusters (we can't use re:dash for our purposes).

We currently have a [weekly job](https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala) that scrapes this information using the [Search API endpoint](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search).

It would be great to be able to access the data in a simpler and more reliable way.

**Comment by eviljeff** [comment]
@jasonthomas @bqbn I don't know if this is desirable/possible

**Comment by jasonthomas** [comment]
I don't like the idea of database access from spark clusters. The database servers are not publicly internet accessible and would require changes to our ACLs.

Instead, can we write a management command to dump the required data, configure it to run via cron daily, and make that dump publicly accessible?

**Comment by bqbn** [comment]
I too don't like to expose our database to external services directly. We should really leverage our API to expose/provide data to the trusted party (via Oauth 2 maybe?).

If current API endpoint is not good/efficient for the purpose, the client should send a feature request for a better/more efficient API endpoint. IMHO, it helps us evolve into an API backend service as well.

**Comment by muffinresearch** [comment]
@Dexterp37 could you provide more details of exactly what data on the add-ons you need?

**Comment by Dexterp37** [comment]
@muffinresearch ideally, all the add-on metadata that are publicly available through the AMO website. However, Martin (@mlopatka) might have a better idea of what he needs.

**Comment by mlopatka** [comment]
Everything currently available via the [public API ](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search) would be useful for further work in leveraging addon metadata for recommendations. 

I dont want to lean so heavily on that API which is a bit sluggish for real-time querying. We have been using a batch dump of it ourselves for exploring addon metadata currently. So, if a daily dump is better for you guys that satisfies our use case completely.

**Comment by eviljeff** [comment]
We're trying to focus on speeding up the API too - what kind of access time would you regard as non-sluggish?

**Comment by crankycoder** [comment]
I don't think we need to keep this issue open.  TAAR is currently running a daily dump of the addons database and we haven't had any issues.   Let's close this issue for now until we have a concrete problem that we need addressed.
