### ISSUE TITLE
Content Reviewers cannot access content review page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6881]
Users in the *Reviewers:Content* group (permission: 'Addons:ContentReview') can access the content review queue, but not any content review (detail) pages.

`<mat> that view does 4 different types of reviews, needs a refactor of its permission checks`

**Comment by diox** [comment]
This goes deeper than I thought.

Most views in `reviewers/` are protected with either `addons_reviewer_required` or `any_reviewer_required` (and others that don't matter here). That means they won't work with users that only have `Addons:PostReview` or `Addons:ContentReview` permissions.

Among the affected views, there is:
- The reviewers home
- The logs page
- The performance page
- The leaderboard
- The whiteboard change page (it's where you POST data when you change the whiteboard text. It then redirects to the review page, but currently it checks for `Addons:Review`)

@wagnerand do all these page need to be accessible for users with only `Addons:PostReview` or `Addons:ContentReview` ? I'm assuming yes for the whiteboard (it needs to follow the permissions of the review page) but what about the others?

**Comment by wagnerand** [comment]
Yes to all of those views.

**Comment by jvillalobos** [comment]
The reviewer home should be accessible to reviewers of all kinds when #6520 is done. Making the other views useful to other reviewer groups should follow next year, but for now it makes sense to restrict to those permissions.

**Comment by ValentinaPC** [comment]
> Users in the Reviewers:Content group
 should have access to Content Review queue page?

Because I created an account, added the user only to this group and I can load the page using a direct link. Is this ok? Or it is the same as before and I have to wait for #6520 to land?

I can also approve content.


Verified on AMO-dev FF57(Win 7)

**Comment by diox** [comment]
@ValentinaPC I fixed it early because I didn't want to wait for #6520 to land (and because it'll make my follow-up changes easier to review)

**Comment by ValentinaPC** [comment]
So, the only way a user, that is in the Reviewers Content group, can access the Content Review page is a direct link? or should have a link in Dev Hub for its add-ons?

**Comment by diox** [comment]
No, they should also be able to see the homepage, giving them a link to the content review queue, giving them a link to the content review pages.

**Comment by ValentinaPC** [comment]
Uff....I am a bit slow today, maybe :(

I'll give you an example: https://addons-dev.allizom.org/en-US/firefox/addon/content-permissions/

This add-on was submitted using a new account that is part of the group mentioned above.
No way for me to go to Reviewer Tools pages using that account.
![2017-11-16_1654](https://user-images.githubusercontent.com/15685960/32897742-117b345a-caef-11e7-823f-71b5eedc49ca.png)
![2017-11-16_1654_001](https://user-images.githubusercontent.com/15685960/32897744-11a321a4-caef-11e7-8791-0f2eaae3cc97.png)

**Comment by diox** [comment]
The fact that there are no links for content review is a different issue. The problem I solved was access to reviewer tools themselves. Can your user go to https://addons-dev.allizom.org/en-US/editors/ and from there, use the menu to go to https://addons-dev.allizom.org/en-US/editors/queue_content_review, and from there, access the content review page for add-ons in the content review queue? If so, then it's working as intended.

**Comment by ValentinaPC** [comment]
Yes, as I was saying above, using a direct link, and that new user, I can access Reviewer Tools page and make a content approval.
I was just making sure that this was fixed here and no anything else.
Thanks for your reply.

Accessed Rev Tools using a new user that is part of Reviewers Content group.

![2017-11-16_1708](https://user-images.githubusercontent.com/15685960/32898418-ca64c412-caf0-11e7-844b-1fa64613aeb5.png)
![2017-11-16_1708_001](https://user-images.githubusercontent.com/15685960/32898420-cae99aa2-caf0-11e7-9ee2-68116851cae8.png)
