### ISSUE TITLE
Firefow arrowhandle request of user and pwd: is it normal?

### ISSUE THREAD

**Issue by gitille** [mozilla/addons-server#6888]
I installed firefox and after some seconds working, it appeared a message by www.arrowhandle.com asking to give user and pwd, is it normal? At the moment my firefox has been blocked and I disinstalled it from my laptop. In attachment the message.
![firefox screen question](https://user-images.githubusercontent.com/33574390/32690259-4b36391e-c6f4-11e7-8090-8d63032cfb89.png)

Why I need to create user and pwd? The message seemed aggressive... is it spam?
I look forward your feedback
Thanks
Kind regards
![firefox screen question](https://user-images.githubusercontent.com/33574390/32690255-3174462e-c6f4-11e7-9eb9-dd366120089d.png)

Gitille

**Comment by eviljeff** [comment]
This isn't a problem with the addons website.  Please see https://support.mozilla.org/en-US/ for general support.
