### ISSUE TITLE
If existing ID is found owned by uploader, don't throw an error, use it!

### ISSUE THREAD

**Issue by mlissner** [mozilla/addons-server#6889]
### Describe the problem and steps to reproduce it:
I just finished making a new version of my extension and wanted to upload it. I went to AMO, and I selected the link that says, "Tools > Submit a new addon-on". 

I then uploaded my addon and got this:

![screenshot from 2017-11-11 15-30-10](https://user-images.githubusercontent.com/236970/32694470-6757b9b4-c6f5-11e7-9e96-deab4f7be309.png)

### What did you expect to happen?

Since the duplicate add-on ID is mine, it should work.

### Anything else we should know?

Clicking the link to the full validation report doesn't provide any more information on this error and in fact doesn't mention the error at all. That was a surprise since it failed validation.

**Comment by jvillalobos** [comment]
Duplicate of https://github.com/mozilla/addons-server/issues/4257
