### ISSUE TITLE
Collection comments missing from new layout

### ISSUE THREAD

**Issue by irvinm** [mozilla/addons-server#6892]
### Describe the problem and steps to reproduce it:
When adding comments to an add-on when creating a collection, these comments are no longer shown to users of the collection with the new layout.

### What happened?
Comments can still be entered as part of the collection, but not shown to users of the collection.

### What did you expect to happen?
I should be able to enter the comments and users should be able to see them.

### Anything else we should know?
Comments can still be entered:

![2017-11-12_8-47-11](https://user-images.githubusercontent.com/979729/32699586-2bb6d656-c786-11e7-8625-1e006466ebbf.png)

However, the view of the collection no longer displays any of the comments.

![2017-11-12_8-48-50](https://user-images.githubusercontent.com/979729/32699599-643a7e42-c786-11e7-80a7-f0aa526bfb67.png)

For me, the usefulness of the comments was to help users understand WHY either I use them or why THEY might want to use them.  

I don't have a screenshot of my comments in the old format and was only able to find an old screenshot  via Google Images.

![2017-11-12_8-54-21](https://user-images.githubusercontent.com/979729/32699644-3d9b2056-c787-11e7-8685-7d754bcfd037.png)

**Comment by eviljeff** [comment]
I've re-filed this on our front-end repository, as the code for the new front-end resides there now.
