### ISSUE TITLE
Search: Support translations for exact name matches

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#6898]
Follow-up issue to #6837 which implemented basic exact matching support.

We need to extend that support for translations. We already have a `name_translations` field so let's see if we can re-use that in a good way, otherwise let's think about restructuring things.

**Comment by diox** [comment]
This is more important than we initially thought, because fixing exact matches revealed some add-ons trying to game the system using translations.

**Comment by diox** [comment]
In addition: with the way we're doing it currently, we're missing some exact matches. For instance, this should generate an exact match and doesn't:
- Add-on name "Foo" in english and "Bar" in french
- Search for "Foo"

It doesn't generate an exact match, because we index "Foo Bar" (or "Bar Foo") as the raw name.

**Comment by diox** [comment]
The mapping has been updated to prepare for the new code to do this, it will go to production this week and the code to use it next week.

As part of the new mapping, each `name_l10n_{lang}` field has the following mapping:
`{u'fields': {u'raw': {u'normalizer': u'lowercase_keyword_normalizer', u'type': u'keyword'}}, u'type': u'text', u'analyzer': u'english'}`

This can be checked with something like this in a django shell (adapt for different envs/aliases):
`get_es().indices.get('addons_dev-20181030145945')['addons_dev-20181030145945']['mappings']['addons']['properties']['name_l10n_english']`

(or just looking at the mapping in json)

**Comment by diox** [comment]
QA: To test this, try to play around having translations for various fields of different add-ons and searching for them while in the corresponding language. Specifically, this scenario should now work better, while keeping the rest of the search results relatively similar to what they were before:
1. Take an existing add-on that has a number of users > 0, default locale en-US and no translations for its name (you could technically upload a new add-on, but then you have to make sure it has a number of users > 0 for everything to work reliably) 
2. Change its name in another language (say, french) to something else.
3. From AMO in english, search for the exact original name: it should be found at the top
4. From AMO in a language other than the one you picked and other than english, search for the exact original name: it should still be at the top
5. From AMO in the language you picked at step 2, search for the exact name you set in that language: it should be found at the top

Note: feel free to pick any language, but importantly, if the language is in the following list, then step 5 is not guaranteed to be supported:
Afrikaans (af)
Asturianu (ast)
Azərbaycanca (az)
বাংলা (বাংলাদেশ) (bn-bd)
Bosanski (bs)
Maya Kaqchikel (cak)
Dolnoserbšćina (dsb)
Frysk (fy-nl)
Gaeilge (ga-ie)
ગુજરાતી (gu)
עברית (he)
Hornjoserbsce (hsb)
ქართული (ka)
Taqbaylit (kab)
Македонски (mk)
Монгол (mn)
Melayu (ms)
Norsk bokmål (nb-no)
Norsk nynorsk (nn-no)
ਪੰਜਾਬੀ (ਭਾਰਤ) (pa-in)
Polski (pl)
slovenčina (sk)
Slovenščina (sl)
Shqip (sq)
తెలుగు (te)
ไทย (th)
Türkçe (tr)
Українська (uk)
اُردو (ur)
Tiếng Việt (vi)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

I have taken several addon samples, all with >0 users and followed the above steps to see the results. 
For example, the following add-on has the default locale set to `en-US` and I've added `de` as a secondary locale:

- searching for `add-on indexng` - AMO locale set to `en-US` - finds [Add-on Indexing](https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=add-on%20indexing) as first result
- searching for `add-on indexng` - AMO locale set to `nl` - finds [Add-on Indexing](https://addons-dev.allizom.org/nl/firefox/search/?platform=windows&q=add-on%20indexing) as first result
- searching for `suche nach ubersetzungen` (German name)  - AMO locale set to `de` - finds [Suche nach Übersetzungen](https://addons-dev.allizom.org/de/firefox/search/?platform=windows&q=suche%20nach%20ubersetzungen) as the only result

The add-on is also found as an exact match when searching for specific strings from the summary or description.

As expected, the add-on can't be found if one of the set locale is part of the  languages list mentioned above. For example [this add-on](https://addons-dev.allizom.org/pl/firefox/addon/add-on-indexing/?src=search) can't be found when searching for its Polish name.

I haven't observed other new problems, apart from the shortcomings tracked already in all the separate search related issues - one example is  https://github.com/mozilla/addons-server/issues/9803

[en-US]
![image](https://user-images.githubusercontent.com/31961530/48187269-3c5f6980-e343-11e8-9da4-6ae4105f2190.png)
[nl]
![image](https://user-images.githubusercontent.com/31961530/48187295-54cf8400-e343-11e8-8cb9-bec8e44407cf.png)

[de]
![image](https://user-images.githubusercontent.com/31961530/48187318-6c0e7180-e343-11e8-9636-091a9715a04f.png)
