### ISSUE TITLE
Search API should not provide a `next` URL for the last (allowed) page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#6902]
### Describe the problem and steps to reproduce it:

When browsing [the 1000th page of themes]( https://addons.mozilla.org/api/v3/addons/search/?app=firefox&appversion=58.0&lang=en-US&page=1000&type=persona), you get a `next` attribute for the next page. Yet, there is a hard limit set and this 1001st page does not exist (404).

### What happened?

A `next` URL is provided, but it returns 404 ([URL]( https://addons.mozilla.org/api/v3/addons/search/?app=firefox&appversion=58.0&lang=en-US&page=1001&type=persona)).

### What did you expect to happen?

The `next` URL attribute should be `null` and not a URL that loads a 404.

Also, it would be nice to mention this limit of 25k add-ons returned somewhere in the doc, close to the `count` attribute if possible so that no one will implement a pagination based on `count` only (like we currently do in the frontend 😛).

Thanks!

**Comment by EnTeQuAk** [comment]
Fixed in https://github.com/mozilla/addons-server/commit/708a66cad6e98bb7ff5e5e6ac97a8fdf3fdda8b3

**Comment by vcarciu** [comment]
Verified as fixed : 
![null](https://user-images.githubusercontent.com/1583842/32794913-d9a2d2fe-c972-11e7-8aac-a44966512fac.png)
