### ISSUE TITLE
Add-ons being incorrectly flagged as not compatible with Quantum

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6905]
Reported by a couple of developers [in the forum](https://discourse.mozilla.org/t/extension-not-compatible-with-firefox-quantum/21460/7). Certain add-ons are showing up as not compatible with Quantum, when they are using WebExtensions. It's possible that it's due to them being platform-specific ([this example](https://addons.mozilla.org/addon/simple-browsing-schedule/) is Windows-only).

If the short-term solution is to remove that incompatible flag, we should do that. Marking WebExtension add-ons as incompatible is a big deal given the upcoming launch.

**Comment by kumar303** [comment]
The API is doing the right thing. The frontend has the logic to display this badge so I moved it over there https://github.com/mozilla/addons-frontend/issues/3895
