### ISSUE TITLE
Review not visible for my add-on

### ISSUE THREAD

**Issue by Lumox100** [mozilla/addons-server#6911]
The following review of my add-on "Save Images" was sent to my email address but when I following the link to reply, it is not available on the website. Please could you resolve this as I would like to reply to the person who posted the review.

A user has left a review for your add-on, Save Images.

Rating:
5 out of 5 stars

Review:
First of all, the 5 star rating is my &#39;thank you&#39; for all the years I used this extension in Firefox, before I switched to Chrome a few months ago due to Mozilla killing the huge number of &#39;legacy&#39; extensions.

Now to the point: Mr. developer, do you still state (like you did last time I checked) that you won&#39;t make this extension a WebExtension one? If so, would you be interested in maybe collaborating in making a &#39;new&#39; (and a little different) Save Images webextension that is able to do almost what your legacy extension does right now (but in a different way)?

The reason I&#39;m asking this is because right now I&#39;m developping a sort of &#39;equivalent&#39; of &#39;Save Images&#39;, but for Chrome, and so far it&#39;s showing a reasonable potential, at this developping stage (it&#39;s not yet finished, but it could be by the end of the year, hopefully). As far as I know, there wouldn&#39;t be much to change from a Chrome extension to make it a Firefox &#39;WebExtension&#39; one, if you&#39;re interested. Plus, the exchange of ideas might be beneficial to both parties.

Of course, if you changed your mind and plan to actually port your legacy extension to a webextension one, maybe you don&#39;t need such a collaboration.

If you&#39;re interested though, just reply me here, and I&#39;ll mail you with the details (what I can share so far, of course).

Thank you again for your work on Save Images. When switching over to Chrome, your extension&#39;s functionality (or an equivalent) was the only thing I couldn&#39;t find on their &#39;WebStore&#39; (thus my decision to make one myself).

You can read the review and reply to it here:
https://addons.mozilla.org/addon/save-images/reviews/933667/reply

**Comment by jvillalobos** [comment]
It looks like the review was deleted after it was submitted and before you clicked through. There's nothing that can be done in that case.
