### ISSUE TITLE
Cannot approve content review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6912]
### Describe the problem and steps to reproduce it:

See https://reviewers.addons.mozilla.org/en-US/editors/review-content/middle-click-to-go-back

### What happened?

There is no "Approve" action.

### What did you expect to happen?

The add-on is supposed to be content-approved.

### Anything else we should know?

A wild guess would be that it's because the latest version has been disabled.

**Comment by diox** [comment]
You already reported that :) https://github.com/mozilla/addons-server/issues/6894

**Comment by wagnerand** [comment]
🙃 crazy week...
