### ISSUE TITLE
ActivityLog pointing to old ratings are broken, breaking devhub and reviewer tools

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6913]
Old `ActivityLog` pointing to ratings can't be displayed following the internal renaming of reviews to ratings in #6761. This breaks devhub and reviewer tools as soon as one appears in one of those pages.

Sentry traceback: https://sentry.prod.mozaws.net/operations/olympia-dev/issues/688860/

**Comment by ValentinaPC** [comment]
I've verified the Moderated Review Log page and redirection links from there using AMO-dev FF57(Win 7) and work as expected.
Anything else I should check here, Mat?

**Comment by diox** [comment]
Nope it's fine.
