### ISSUE TITLE
Update auto-approval message to provide more context for developers

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#6921]
When an add-on is auto-approved, the Mozilla account sends the normal approval message:

> This version has been approved for the public.
> 
> Thank you!

Some developers appear to be confused about its meaning, and then are confused if the add-on is later rejected by a reviewer. We should change the approval message to provide more context and mitigate this problem.

Here's the proposed text:

> This version has been screened and approved for the public. Keep in mind that other reviewers may look into this version in the future and determine that it requires changes or should be taken down. In that case, you will be notified again with details and next steps.
> 
> Thank you!

/cc @wagnerand @kewisch @caitmuenster for content.

**Comment by wagnerand** [comment]
LGTM.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win 7).
I've checked the message in Dev Hub, Reviewer Tools and Fake Mail Logs admin page.
Postfix screenshot:
![log](https://user-images.githubusercontent.com/15685960/33078775-63ef0c84-cedc-11e7-8dc0-b659ea5843f2.png)
![msg](https://user-images.githubusercontent.com/15685960/33078776-6410cd88-cedc-11e7-85b2-2a2f1a4adcd5.png)
