### ISSUE TITLE
Addon.last_updated includes unlisted activity

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6929]
Refiling from https://github.com/mozilla/addons-frontend/issues/3856.

Basically, `addon.last_updated` should ignore unlisted versions since the frontend shows that info on the listing details page.

**Comment by diox** [comment]
There are fancy queries and somehow even a cron to deal with changing `last_updated`. It was indeed never updated (ah!) to avoid unlisted versions, and  we should do that. While we're at it, we could probably:
- Remove the cron, only ever updating when `version_changed` is called. I believe the cron was there to catch things going south when we didn't have transactions wrapping every view
- Just take `addon.current_version.all_files[0].datestatuschanged` if it's higher than the current `last_updated` value and ignore all the complicated queries

**Comment by jvillalobos** [comment]
Maybe we should just show the creation date of the version on display on the page. That would account for versions that are rejected after the fact and would better align with what users expect.

**Comment by diox** [comment]
Since unlisted versions have been included on purpose in https://github.com/mozilla/addons-server/issues/4083 I've refiled the issue back in frontend land using @jvillabos's suggestion: https://github.com/mozilla/addons-frontend/issues/8861
