### ISSUE TITLE
Rename `eventlog` to something more sensible like `ratings_moderation_log`.

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6931]
In addons-server code, the `olympia.reviewers.views.eventlog` views, as the name does not suggest, is only a log of ratings related events. It calls `ActivityLog.objects.reviewer_events()`, which uses `LOG_REVIEWERS` which is a list of activity actions that have the `reviewer_event` property set, which is only `APPROVE_RATING` and `DELETE_RATING`.

It's super confusing, you'd think it's a log of all review related events when it's just ratings. Let's rename all those things.

**Comment by AlexandraMoga** [comment]
@eviljeff does this impact Reviewer Tools as a whole or should we test only the Ratings Moderation component?
Thanks

**Comment by eviljeff** [comment]
@AlexandraMoga primarily it's the ratings moderation tool.  And the dashboard links too.

**Comment by AlexandraMoga** [comment]
Verified on AMO-stage with FF59, Win10x64
I haven't noticed other problems besides the issue reported in #6948
