### ISSUE TITLE
Upload/signing api should allow supplying the slug

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#6932]
Right now when uploading a new addon for signing via the api it is not possible to specify the slug. If this were possible, Chrome Store Foxified could use a randomized slug. @EnTeQuAk  said this would be a worthwhile addition.

**Comment by eviljeff** [comment]
@kewisch is this still needed now unlisted addons get a random slug automatically?  (#6983)

**Comment by eviljeff** [comment]
Actually, as you can _only_ create unlisted add-ons via the API, and all unlisted add-ons get a random slug, then this issue is was fixed by #6983.
