### ISSUE TITLE
Implement new Unified Reviewer Dashboard (standalone for now)

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6937]
Split from https://github.com/mozilla/addons-server/issues/6522

Implement new Reviewer Dashboard per specs in #6522, but don't redirect existing paths and don't modify menu for existing reviewer tools as well. In short, make it completely standalone, accessible from an URL (like `/{locale}/editors/dashboard`) that will go away when #6522 is done. This is to ease the transition and make it easier to test before switching to the real thing, without having to deal with a waffle switch.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF57(Win 7).
The standalone dashboard was added: https://reviewers.addons-dev.allizom.org/en-US/editors/dashboard
Checked every link and works.

@diox : Have a a question related to those links: "Performance" and "Add-on Review Log" links are listed under multiple sections but load the same page, is this intended?
