### ISSUE TITLE
Add-on version summary of rating count does not match actual count

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6942]
The count of ratings with text is 10:

```
$ curl 'https://addons-dev.allizom.org/api/v3/reviews/review/?addon=vertical-tabbar&api=&filter=without_empty_body&page=1' | jq .count
10
```

but the `ratings.text_count` is 7:

```
$ curl 'https://addons-dev.allizom.org/api/v3/addons/addon/vertical-tabbar/' | jq .ratings
{
  "bayesian_average": 2.86387,
  "count": 7,
  "average": 3.1429,
  "text_count": 7
}
```

Here are the steps to reproduce (and the ultimate frontend bug): https://github.com/mozilla/addons-frontend/issues/3904

I tried submitting reviews other add-ons on dev and I see the same thing happening. It has been longer than 5 minutes and refreshing the page doesn't help.

**Comment by AlexandraMoga** [comment]
This can be marked as verified fixed on all AMO servers (FF57, Win 10 and Android 7.0) based on the steps from [#3904](https://github.com/mozilla/addons-frontend/issues/3904)
