### ISSUE TITLE
Discuss slug redirections 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6943]
If a slug is changed on AMO today we don't have any automatic redirection. I wonder if we should consider having some so that we don't have to manually setup redirects if a slug changes.

As an example collections are under user names so changing a slug could potentially automatically set a redirect without compromising slug availability. Add-on URLS do not contain a user or team name, so any automatic redirection would limit the availability of slugs unless we changed that.

We have also talked about using add-on ids for URLS but this isn't quite as nice as a slug-based URL since having a slug gives you some indication of what is expected.

This issue is to discuss the following: 

* Is this something we actually want?
* If we do, what it would take to get there?
* What technical considerations are there around how redirects would work in a API based frontend?

**Comment by devaneymoz** [comment]
+1

Often we create Mozilla editorialized collections that are used in various content marketing channels outside of AMO and may live in relative perpetuity (recurring email campaigns, on mozilla.org sites, linked to from third party sites or blogs, etc). So not having to worry about where a static link lives for these collections would be great.

**Comment by jvillalobos** [comment]
Slug changes shouldn't be very common, so blocking the slug and having a redirect is probably okay. However, we'll need some way for admins to manually free these kinds of slugs in cases of abuse (for add-ons, since it's not a problem for collections).

I think I would prefer add-on URLs to have the ID and the (optional) slug, so the URL would be `/addon/ID/SLUG`. However, that means we would still need to redirect the old URLs to the new ones, so we wouldn't be able to rely on that format in the near future.

**Comment by muffinresearch** [comment]
> I think I would prefer add-on URLs to have the ID and the (optional) slug, so the URL would be /addon/ID/SLUG. However, that means we would still need to redirect the old URLs to the new ones, so we wouldn't be able to rely on that format in the near future.

Having the id in the url would help a lot for slug change redirections since it removes the possibility of collisions.

**Comment by rraue** [comment]
Jorge asked me to bring in some Seo perspective:

I think it will be valuable over time to have such kind of redirects as we will then not lose PageRank for incoming links to changed URLs. Links to 404s do not pass PageRank. And that's the second advantage, we will create less 404s and as the content doesn't change radical, that's best practice for Seo to redirect old URLs to new ones, even with some changes in wording, name etc.
