### ISSUE TITLE
Legacy ratings list return 500 error when it contains a rating you have already flagged

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#6944]
STR:
- Go the legacy website add-on detail page
- Log in
- Visit the reviews list page
- Flag a review
- Reload the page

Expected Results:
- The page loads correctly. You are not presented with the option to flag the review you already flagged

Actual Results:
- The page returns a 500 error.

It's because of 0af406cbdc3c13570946daa06f16657684d339fd. The traceback is https://sentry.prod.mozaws.net/operations/olympia-prod/issues/693498/

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF57 (Win10)

![flag](https://user-images.githubusercontent.com/31961530/32944568-ab756572-cb98-11e7-8571-e218891658c6.gif)

Report appears in rev tools:

![image](https://user-images.githubusercontent.com/31961530/32944605-c0ab1946-cb98-11e7-9327-818d703e2d35.png)

**Comment by EnTeQuAk** [comment]
Just directly linking this in Sentry and marking it as resolved for the next release: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/693498/
