### ISSUE TITLE
Review Tools: Reviews This Month - Mix Of Code & Content Review Stats

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#6947]
At the moment, both Content Review Stats and Code Review Stats are mixed into one column.

> **Reviews This Month**
> erosman | 756
> Raluca Sofian | 132
> Andreea Neamtiu | 124
> Bogdan Matei | 93
> Philipp Kewisch | 51

The current system provides an unbalanced overview of the contributions. I would suggest a separate column for the Content reviews.

**Comment by wagnerand** [comment]
@jvillalobos Should we do this now or wait for the rewrite next year?

**Comment by jvillalobos** [comment]
Those numbers will disappear soon with the unified dashboard (https://github.com/mozilla/addons-server/issues/6522), and we'll bring group-specific numbers back with the rewrite, hopefully in Q1. Hence, closing this.
