### ISSUE TITLE
Moderated reviews queue shows a duplicate report for the same flagged review

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#6948]
Steps to reproduce:

Prerequisites: user needs to have two accounts for AMO-dev; user needs to have access to reviewers tools

1. Log in with one account on AMO-dev
2. Choose an add-on and go to its reviews page (i.e. https://addons-dev.allizom.org/de/firefox/addon/awesome-screenshot-plus-/reviews/)
3. Pick one of the listed reviews and flag it for one of the available options
4. Log in with the other account and flag the same review chosen at Step 3
5. Go to Reviewers Tools and verify if the recent flags appear in the Moderated Reviews queue

Expected result:
The flagged review appears in the moderated reviews list and displays the two reports chosen above

Actual result:
The moderated list displays a duplicate report of the same review (same users, same flag reasons)

Notes: The moderated reviews queue might not be updated instantly, so refreshing the page several times might be necessary before the results are observable;
Reproduced on AMO-dev with FF57 (Win 10); 

Screenshot for the duplicate report;
![image](https://user-images.githubusercontent.com/31961530/32953768-e5e4e13a-cbb9-11e7-9c21-3972498f071c.png)

**Comment by eviljeff** [comment]
Is this reproducible with both the legacy frontend and new frontend?

**Comment by AlexandraMoga** [comment]
Yes, this will happen for reviews reported from both legacy and new frontend:

![image](https://user-images.githubusercontent.com/31961530/33180496-93ea54d0-d075-11e7-942b-f22dd79dc199.png)

---------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/31961530/33180584-e1bad194-d075-11e7-874e-81675adc04a8.png)

**Comment by AlexandraMoga** [comment]
One additional note; sometimes, a new flagged review will not appear in the moderated queue unless some older reviews are processed, or another review gets flagged in the meantime

**Comment by AlexandraMoga** [comment]
The issue mentioned in https://github.com/mozilla/addons-server/issues/6948#issuecomment-382392156 and the duplicate entries are still reproducible
