### ISSUE TITLE
Cannot install add-on with really long ID

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#6951]
### Describe the problem and steps to reproduce it:

A developer in the `#addons` channel had converted a Chrome extension to a Firefox extension and uploaded it to AMO.

Example file: https://addons.mozilla.org/firefox/downloads/file/778198/tel_linker-0.4.2-an+fx-windows.xpi?src=dp-btn-primary

### What happened?

The extension could not be installed.

### What did you expect to happen?

The extension should be installable.

### Anything else we should know?

They saw this in the console:

```
WARN	Download of https://addons.mozilla.org/firefox/downloads/file/778198/tel_linker-0.4.2-an+fx-windows.xpi?src=dp-btn-primary failed: Error: Webextension is signed with an invalid id (ab7765828f4fee6dfa3558c5a01b9ab9975ea3c8c446e487bb879b957675cde5) (resource://gre/modules/addons/XPIInstall.jsm:931:15) JS Stack trace: loadManifestFromZipReader@XPIInstall.js
```

And @diox mentioned that its guid is really long:
```
ceiihmdnpjglaoolchdmncoffhhbgodj@chrome-store-foxified-1127895862
```
...which triggers different code [that shortens the ID](https://github.com/mozilla/addons-server/blob/f5e77c16baa7c0dbada5fae10c5ab84b75386321/src/olympia/lib/crypto/packaged.py#L49-L57) because of https://bugzilla.mozilla.org/show_bug.cgi?id=1203365

and some platform folks said that an ID is extracted from the manifest. Perhaps the fix here is to include the original ID in the manifest, they said.

**Comment by kumar303** [comment]
This might be high priority but I'm not totally sure. I don't know how to reproduce it.

**Comment by wagnerand** [comment]
I believe reproducing is rather easy. Just sign a file with the chrome-store-foxified add-on.

The only thing I don't get is how that add-on submission managed to be listed. Chrome-store-foxified hits the signing API and does not specify a channel at all, and the default is *unlisted*.

**Comment by kumar303** [comment]
I think they copied it from Chrome-store-foxified then uploaded it to AMO but I'm not sure.

**Comment by wagnerand** [comment]
I don't see how this is possible. They had to use the submission feature in chrome-store-foxified, which hits the API directly. Otherwise, the ID wouldn't have been passed, so AMO would have created a random <64char ID.

**Comment by andymckay** [comment]
Sorry I was in meetings when I first saw this so didn't have time to think about it properly. I now understand what @wagnerand was talking about in IRC. Something somewhere went wrong, but its an edge case and should probably not be a P1, but I'll let you guys figure out how it got into this state. As @kumar303 said, this is why we haven't seen this in 2 years. Just so I can remember:

* An add-on can be submitted with an id greater than 64 chars, so it turns into a hash in the signing processs. The only way it can do this is by specifying an id in the manifest.json. But the Firefox signature check can then read it out of the manifest.

* If an add-on is submitted with no ID, then its given an id by AMO and that will fit with the 64 chars.

So somehow, as @wagnerand, someone got an add-on onto AMO with no ID specified in the manifest.json but managed to specify an ID and not do it in the manifest. That's probably somewhere in the API that chrome store foxified uses. 

BTW I'm really hoping that in this case AMO still checks the add-on id against the listed guids... Once again sorry for the worries in IRC and thank for investigating it so quickly.

**Comment by wagnerand** [comment]
> So somehow, as @wagnerand, someone got an add-on onto AMO with no ID specified in the manifest.json but managed to specify an ID and not do it in the manifest. That's probably somewhere in the API that chrome store foxified uses.

Exactly. It's http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version which is the API that chrome-store-foxified uses.

**Comment by EnTeQuAk** [comment]
Assigning this to me, I'll take a look on getting this fixed today. As far as I can tell for now it should be enough to just fail for a missing id in the manifest if the guid is too long. As far as I can tell this should only be achievable via the API, so the fix should be somewhere there.

I'll investigate a bit more but if that's it the fix is easy enough.

**Comment by EnTeQuAk** [comment]
This is heading to -dev right now

**Comment by AlexandraMoga** [comment]
Can this be verified by QA? If so, are there some more clear steps that we could follow? 
Thanks.

**Comment by muffinresearch** [comment]
@EnTeQuAk could you provide some steps for QA to verify? ^

**Comment by EnTeQuAk** [comment]
STR:

* You're creating a new add-on so make sure the add-on has not yet been uploaded and the id is not registered
* Use http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version to upload a new add-on BUT…
* don't set the add-on id in the manifest and use an `addon-id` with more than 64 characters long 

As an example:

```bash
curl "https://addons.mozilla.org/api/v3/addons/this_guid_is_longer_than_the_limit_of_64_chars_see_bug_1201176_and_should_fail@webextension-guid/versions/1.0/"
    -g -XPUT --form "upload=@path/to/my-addon.xpi"
    -H "Authorization: JWT <jwt-token>"
```

The JWT Token has to be aquired via http://addons-server.readthedocs.io/en/latest/topics/api/auth.html but I'm sure it should be reproducible via web-ext somehow too.

Or alternatively use https://github.com/mozilla/sign-addon/ and set `id` to something like `this_guid_is_longer_than_the_limit_of_64_chars_see_bug_1201176_and_should_fail@webextension-guid` and make sure to set `apiUrlPrefix` correctly.

Let me know if you need anything else and I can come up with an example script to reproduce this on -dev using `sign-addon`
