### ISSUE TITLE
Changing the developer account displayname is not reflected in listings.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#6964]
I noticed when changing a displayname of an account it doesn't cause the display name of the add-ons to be updated to reflect the change. It's only when you carry out a save on the add-on that the name change update is reflected.

If the new user APIs will cause the relevant updates when writing changes then this issue can probably be closed.

STR:

* Look at an existing add-on listing page
* Go to the the user profile page and update your display name
* Go back to the listing and the add-on still shows the username from before the change.

**Comment by eviljeff** [comment]
I'm not sure we watch any of the UserProfile changes for ES updates.

**Comment by diox** [comment]
Yeah, we don't. That would only affect the search API though, the detail endpoint should reflect any changes to the user immediately.

**Comment by ValentinaPC** [comment]
https://github.com/mozilla/addons-frontend/issues/2079

**Comment by muffinresearch** [comment]
I'm earmarking this for a milestone next year. We'll want to check that the API for editing usernames / display names results in updates to addons correctly.

**Comment by AlexandraMoga** [comment]
> the detail endpoint should reflect any changes to the user immediately.

based on this comment, I was expecting the changes applied to the display name to be reflected instantly when going back to the add-on details page. However, the changes are visible only after 10-15 minutes. 

![image](https://user-images.githubusercontent.com/31961530/34721765-b1684232-f54c-11e7-9f66-ead5af28187f.png)

**Comment by diox** [comment]
@AlexandraMoga could you please retest on stage and see if there is a delay there, and what's the duration if there is one ? dev is a little too unreliable for this.

**Comment by AlexandraMoga** [comment]
Re-tested on stage but the changes still have a ~10 min delay.

**Comment by muffinresearch** [comment]
@diox do you expect to be able to improve on this? Eventual consistency of ~10mins could be considered close to good enough.

**Comment by diox** [comment]
I'm pretty sure this is a cache-machine issue but I could not figure it out. IMHO this is a rare enough problem that it's not super high priority, at least now it does eventually changes to the right name.
