### ISSUE TITLE
Traitlets package is missing.

### ISSUE THREAD

**Issue by MichalTHEDUDE** [mozilla/addons-server#6980]
### Describe the problem and steps to reproduce it:
During debugging (using `make debug` and setting `import ipdb; ipdb.set_trace()` somewhere in the code) when going to `olimpia.dev` website, there is an `ImportError: No module named traitlets.config.application`.

All installation when smooth using docker-compose.

### What happened?
I believe that there is missing dependency in `requirements/dev.txt`. Normally `traitlets` should install with `ipdb` package, but as long as `pip install` is with `--no-deps` there will be no package installed :).

Missing package version:
`traitlets==4.3.2`

**Comment by EnTeQuAk** [comment]
Indeed I ran into this as well the other day. This comes from https://github.com/ipython/ipython/blob/5.x/setup.py#L198

**Comment by MichalTHEDUDE** [comment]
Hmm, just installed `traitlets` and there is new error :)
`ImportError at No module named pexpect`

Missing package:
pexpect==4.3.0

**Comment by EnTeQuAk** [comment]
Jupp, this needs `pathlib2` as well looking at https://github.com/ipython/ipython/blob/5.x/setup.py#L207

**Comment by EnTeQuAk** [comment]
As well as https://github.com/ipython/traitlets/blob/master/setup.py#L82

**Comment by EnTeQuAk** [comment]
And a few more, see https://github.com/mozilla/addons-server/pull/6981 for more details. Once this is merged you'll be able to do `make update_deps` and run ipython perfectly fine :)
