### ISSUE TITLE
Review weight drop when using <all_urls> instead of https://*/*

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#6985]
### Describe the problem and steps to reproduce it:
I got an interesting weight drop (from 141 to 43) for a review with this particular change in manifest : https://reviewers.addons.mozilla.org/en-US/firefox/files/compare/784222...763037/file/manifest.json .

Is it possible that <all_urls> is not being used for calculating the weight ? 

To my understanding, <all_urls> is even more dangerous than "https://*/*"as it also include extension calls, ftp:, etc.

### What did you expect to happen?
The weight should stay the same or even go a bit higher.

mat said on irc that the sudden weight change could however be related to the massive code addition that were added in 763037. If this is the case then this bug should probably be closed as invalid. I cannot check this out on my side.

**Comment by diox** [comment]
We don't care about `<all_urls>` (or equivalent) at all to calculate weight.

The previous version had such a high weight because of the size of its code changes - it added a bunch of json files, among other things. The current version did not change those files, so the weight dropped.

/cc @jvillalobos to make sure this matches expectations

**Comment by jvillalobos** [comment]
It matches expectations, so the issue as filed is invalid.

Now, is using `<all_urls>` a good signal to increase weight? We probably have thousands of add-ons that match this while being harmless. I would argue it's not very useful, but the admin reviewers might have different opinions. /cc @wagnerand @kewisch

**Comment by kewisch** [comment]
We do have many such add-ons, but I would argue that an add-on that can just access example.com is more safe than one with `<all_urls>` that might access facebook in the background. I'd be inclined to have `<all_urls>` and `https://*/*` contribute to weight.

**Comment by diox** [comment]
Per @jvillalobos comment and mine the bug is invalid. Please file a new issue indicating how much weight `<all_urls>` and `https://*/*`, `https://*/*` should represent.
