### ISSUE TITLE
Reviewers are rewarded with points in case of multiple Confirm Approval for same version

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#6986]
Steps to reproduce:
1. Load Reviewer Tools page https://reviewers.addons.allizom.org/en-US/editors/
2. Go to Logs -> Add-ons Review Log
3. Search for an add-on that was confirmed as auto-approved i.e. https://reviewers.addons.allizom.org/en-US/editors/review/webext-setinterval-test
4. Re-confirm approval
5. See review points boards

Expected results:
Points are not increased because that version was already reviewed and auto-approval was confirmed.

Actual results:
Points increase with add-on weight corresponding values (in this example 90 p).

Notes/Issues:
- all leader boars are updated.
Verified on AMO-stage FF57(Win 7). Issue is also reproducing on -dev.

**Comment by diox** [comment]
This is slightly tricky to fix properly. While we could check the `confirmed` property, that would not solve the problem for content review. A few ideas:
- Store the `version` in `ReviewerScore` as well, and check if points were already awarded for this addon+user+version. Perhaps check that the action is the same as well.
- Store `confirmed_content` and not just `confirmed` on `AutoApprovalSummary`, and check that - allowing the same version to be confirmed multiple times, but only awarding points the first time.
- Dig in `ActivityLog`.. brr. Let's not do that.

**Comment by wagnerand** [comment]
If I remember correctly, re-confirming an already confirmed auto-approval is something that was explicitly defined in the PRD, right? If so, I find it logical to award points to re-confirmation as well.

**Comment by diox** [comment]
Fair enough.

**Comment by ValentinaPC** [comment]
@wagnerand : in my opinion is not ok to reward reviewers for an add-on already reviewed.... basically give points for nothing.
But, I guess is not my call.

**Comment by wagnerand** [comment]
@jvillalobos and @caitmuenster think we shouldn't award points in this case, so lets do that :)
