### ISSUE TITLE
Not redirecting to right page.

### ISSUE THREAD

**Issue by Zoeymae** [mozilla/addons-server#6987]
We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.

https://www.stefanvd.net/support/index.htm
It brought up this page but I have his extensions installed.
### Anything else we should know? I found his extension on your approved wed extensions: very short, inadequate list
(Please include a link to the page, screenshots and any relevant files.)https://www.stefanvd.net/support/index.htm

I can't get a screen shot that your page will accept.  You don't accept .html.

**Comment by muffinresearch** [comment]
> I can't get a screen shot that your page will accept. You don't accept .html.

@Zoeymae if you drag an image into github's comment box it will be embedded automatically.

**Comment by Zoeymae** [comment]
Well, it brings the redirection to the older add-ons page.  I have his extensions installed (very nice by the way).  So I would think it would re-direct from the older extension page.  But it just ends up on 


https://www.stefanvd.net/404.html/

**Comment by Zoeymae** [comment]
I can't drag and drop anything on here that it will accept or open.  I'm not new at being foolish - so be prepared for it!

**Comment by Zoeymae** [comment]
Oops!  See.
