### ISSUE TITLE
Add a flag that blocks auto-approval

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6989]
There have been several cases now where want to hold off on auto-approval for various reasons. Admin reviewers need a way to say "Do not auto-approve any further versions".

I believe a separate flag would be best/simplest to avoid overloading the current model even more.

Setting or removing this flag should only be available to admins, but ideally it should be part of the review page.

**Comment by diox** [comment]
Could `admin_review` (which will soon be splitted into needs admin code review and needs admin content review) be used for this ?

**Comment by wagnerand** [comment]
Not without more invasive changes, I believe. The admin flag will automatically be added to an add-on as soon as sources are attached to a version. Currently, I don't believe it is wise to hold off on auto-approval for those add-ons, because the amount of add-ons that have sources attached is quite big, it would bring back the bottlenecks we had in pre-review.

**Comment by diox** [comment]
We could not add this flag automatically for webextensions. See also https://github.com/mozilla/addons-server/issues/6991#issuecomment-346413137 though.

**Comment by wagnerand** [comment]
We still need the admin flag due to restrictions on visibility of attached source code and review of those add-ons.

**Comment by jvillalobos** [comment]
Closing in favor of #6990.

**Comment by wagnerand** [comment]
This is a different use case than #6990, I filed this issue on behalf on  @deadsquid. I suggest we discuss this before making a decision, so everyone is onboard.

**Comment by jvillalobos** [comment]
I did discuss it with him. What's the difference?

**Comment by wagnerand** [comment]
#6990 is a permanent status for add-ons that are targeted at internal, private or testing use. According to the policies, those add-ons have to be unlisted.

This is about a temporary block of auto-approval for an add-on when we want to make sure that certain conditions are met before we resume auto-approval.

Maybe let's discuss within the team so we can provide the complete picture.

**Comment by jvillalobos** [comment]
I don't see any difference in the *behavior* of the block on both of those cases, so I still don't see why we need separate features.

**Comment by wagnerand** [comment]
Issue #6990 blocks submissions to the listed channel.

This issue allows listed submissions but will prevent auto-approval.

**Comment by jvillalobos** [comment]
So the difference is that in one case your can submit new versions and in the other you can't. I don't think that warrants separate features.

I assume you're thinking of a case where a dev doesn't follow or understand instructions. That can't be helped in either case and will require admin intervention if the dev is persistent. What would happen in that case, if we allow submission, would be something like this:

1. Dev is rejected and listed submissions are no longer auto-approved.
2. Dev submits again, add-on ends up in some queue.
3. Admins have a few options: reject again with a stronger message, ignore, silently disable version.
4. Dev submits again.
5. Add-on gets admin-disabled.

While it takes more steps, it *should* be a rare case (and the alternative isn't that much better in terms of admin work).

**Comment by wagnerand** [comment]
What you are describing would cover this issue.

The other issue (preventing listed submission) is about content that cannot be hosted on AMO because of it can't comply with our content policies. Are we willing to admin-disable the entire add-on and thus prevent even unlisted submissions if the developer keeps submitting listed submissions?

**Comment by jvillalobos** [comment]
Yes, I think admin-disabling is appropriate if a dev isn't listening to us and wasting our time. I doubt we'll run into many cases where the dev acts like this *and* has both active version channels.

**Comment by wagnerand** [comment]
Alright, I am closing the other issue then, based on the discussion here.

**Comment by wagnerand** [comment]
This has been implemented a while ago.
