### ISSUE TITLE
Prevent auto-approval if the add-on is pending 'need-info'

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6991]
The information-requested ('need-info') flag is used when we ask developers to provide information or to make changes to their add-on (that don't warrant a rejection). 

If developers do not reply or comply, future version submissions should not be auto-approved until a reviewer manually drops the 'need-info' flag.

A common use case for this is asking a developer for source-code of a minified add-on submission. Some developers ignore that request and just keep submitting updates, which we can reject, but only after they have been auto-approved and shipped to at least some users already.

**Comment by diox** [comment]
Need to be careful here, because currently all webextensions are hidden from the "legacy" add-on queues, so there is no easy way to find the add-ons that would not be auto-approved...

**Comment by wagnerand** [comment]
Uhm, yes, we need to be able to see a list of them somewhere so we can go through them quickly every day and drop the flag where appropriate.

**Comment by jvillalobos** [comment]
I don't think we should do this. It will lead to many add-ons being blocked from auto-approval and review delays. need-info isn't a very clear process for developers and can lead to confusion because some need-infos can be resolved with new version uploads rather than replies.

**Comment by wagnerand** [comment]
While it's true that some need-infos are resolved by uploading a new version, most of them are not. I expect that only a few add-ons are held back from auto-approval when they shouldn't be. The majority is hold back because information is missing that is required to complete the review (for example source code) and we don't want developers to get around that by submitting new versions.

I expect a triage of those add-ons pending need-info to be very lightweight, and it should only take a couple of minutes each day.

We are also re-evaluating when we set and unset need-info to narrow down the cases as much as possible and prevent lots of add-ons being blocked for no good reason.

**Comment by wagnerand** [comment]
Keep in mind that the purpose of need-info is to retrieve information from the developer in order to complete the review.

Things are trigger a submission of a new version are usually rejections.
