### ISSUE TITLE
Text cut off on new reviewer dashboard

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#6994]
<img width="841" alt="screen shot 2017-11-22 at 19 45 21" src="https://user-images.githubusercontent.com/873258/33144625-f755776a-cfbd-11e7-8fbc-e6ba3a8d3537.png">

It resolves itself if you hover over the "Performance" element, and I had to hard-refresh to make the issue re-appear again.

**Comment by diox** [comment]
I can't reproduce it somehow. Even when playing with zoom and text zoom, it still works for me. Using Firefox 59.0a1 on Linux.
