### ISSUE TITLE
Opensearch module has old icon

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/addons-server#6995]
### Describe the problem and steps to reproduce it:
1. Go to https://addons.mozilla.org/.
1. Switch to old desktop view (due to https://github.com/mozilla/addons-frontend/issues/3836).
1. Add the AMO search module via Firefox search field.
1. See the installed search module icon.

The search module uses old (green puzzle) favicon, instead the new fox-like one.

**Comment by diox** [comment]
Note: it's not on the new frontend, that's https://github.com/mozilla/addons-frontend/issues/3836

**Comment by rctgamer3** [comment]
Likely https://addons.cdn.mozilla.net/favicon.ico

**Comment by MikkCZ** [comment]
@diox Yes, the new frontend does not have the search module at all.
@rctgamer3 yes, exactly this one.

Btw. the fix is in PR #6984. ;)

**Comment by ValentinaPC** [comment]
> Add the AMO search module via Firefox search field.

@diox : not sure how to do this :( , could you give me a hand? Thanks in advance!

**Comment by MikkCZ** [comment]
@ValentinaPC You need to [add the search bar first](https://support.mozilla.org/en-US/kb/my-search-bar-gone-how-add-it-back), if you do not have it in the toolbar. Than refresh AMO and you should see a green + sign on the left in the search bar. Clicking it should allow you to [add the module](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox#w_add-a-search-engine).

Note that the icon in the search bar menu when adding will be taken from the web favicon and will be up to date. You need to add the search module and than [open the search preferences](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox#w_hide-search-engines) to see the icon of the module itself.

**Comment by ValentinaPC** [comment]
@MikkCZ : Thanks!!!

Verified this as fixed in AMO-dev FF57(Win 7).
The icon of the "Firefox Add-ons" search module is updated as expected.
Postfix screenshot:
![new_favicon](https://user-images.githubusercontent.com/15685960/33163042-23046228-d035-11e7-907a-e9290188a1b1.png)
