### ISSUE TITLE
Developer Hub will show a 404 page if locale is not available on the old pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7004]
Steps to reproduce:

1. Go to AMO homepage i.e. https://addons-dev.allizom.org/fy-NL/firefox/
2. Click on Developer Hub  link in the page header

Expected result:
Developer Hub homepage is loaded

Actual result:
A 404 page is loaded instead (https://addons-dev.allizom.org/en-US/firefox/fy-NL/developers/)

Notes: this error can be reproduced with all locales not present on the old pages. Other examples are:
https://addons-dev.allizom.org/cak/firefox/
https://addons-dev.allizom.org/bs/firefox/
https://addons-dev.allizom.org/ms/firefox/
https://addons-dev.allizom.org/nb-NO/firefox/
https://addons-dev.allizom.org/te/firefox/
https://addons-dev.allizom.org/th/firefox/
Reproduced on all AMO servers with FF57 (Win10)

![locales](https://user-images.githubusercontent.com/31961530/33177258-a993207e-d06a-11e7-9037-1da6f3ad4f43.gif)

**Comment by muffinresearch** [comment]
One thought about solving this is to make the locales a package - iirc we did something similar before on Marketplace or payments`. This would be an easy way for both addons-server and addons-frontend to stay in-sync by installing from a single source of truth. 

The only additional issue would be making sure we do generate the locale files if we don't have them already when adding a new locale that doesn't exist. We can add tests for that easily enough.

This way we can make sure all projects use the same list of locales, it could export both python and json, or just json whatever makes consumption easiest. This could then be used consumed in the settings for each project. Thoughts?

**Comment by diox** [comment]
I'll look into adding a redirect to the default locale (english) instead of returning a 404. The package idea deserves its own separate issue for more discussion.

**Comment by diox** [comment]
Interestingly, on the legacy site:
- https://addons-dev.allizom.org//fy-NL/firefox/ correctly redirects to https://addons-dev.allizom.org/en-US/firefox/
- https://addons-dev.allizom.org/fy-NL/developers/ redirects to https://addons-dev.allizom.org/en-US/firefox/fy-NL/developers/ which 404s.

So there is definitely something we can fix here. The middleware is just not redirecting correctly when the URL does not need/contain an app and we're using an unknown locale.

**Comment by diox** [comment]
It turns out it's quite tricky to fix. I tried in #7408 but kept hitting more edge cases - since addons-server does not maintain a list of URL prefixes for which it adds the locale/app, but rather maintains a list of URL prefixes for which it does not add them, it's difficult to make it accept unknown locales that could be any arbitrary string (sure, we can apply a regexp, but I think it's going to be too broad)

I could fix `/developers/` specifically but we'd hit the problem elsewhere. Ignoring the legacy frontend would help, but it's difficult with all the code for it still there, as the problem lies in the `Prefixer` class that is used everywhere in addons-server for resolving/reversing URLs, not just in the middleware that redirects.

**Comment by AlexandraMoga** [comment]
I've retried the scenarios on AMO-dev FF58 (Win10) and the issue seems to be fixed now.

One exception is https://addons-dev.allizom.org/cak/developers/addons which is triggering an internal server error. This will reproduce only with `/cak/`
If needed, I can open a new issue for this scenario.

**Comment by diox** [comment]
I'll deal with it here

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58 (Win10)

![image](https://user-images.githubusercontent.com/31961530/35791928-fc7c1652-0a52-11e8-8612-cd496cb45e16.png)
