### ISSUE TITLE
Add Review Guide links to reviewer dashboard

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7010]
This is a followup for #6937. Each section should have a link to its respective review guide. The list of links in [the document](https://docs.google.com/document/d/1R3uSejL43pjUgMQUy4GxxlNb3pl1XB5cOJ-p3CP4eZc/edit#) has been updated with these additions.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF57 (Win10)

With regards to the Content review queue, should there be no Review guide for this section? I've seen that the [Reviewrs dashboard doc ](https://docs.google.com/document/d/1R3uSejL43pjUgMQUy4GxxlNb3pl1XB5cOJ-p3CP4eZc/edit#heading=h.3o2cob6bpbz9) doesn't mention it either.

![image](https://user-images.githubusercontent.com/31961530/33259669-47562ccc-d366-11e7-8268-488ac9cad760.png)

**Comment by diox** [comment]
Yeah, Content Review section does not get a guide precisely because the reviewers dashboard doc didn't mention one :)

**Comment by jvillalobos** [comment]
Yes, I think they're still being worked on, so I don't have a permanent link to that one yet.
