### ISSUE TITLE
Enable static theme wizard for new versions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7018]
It's currently limited to new addons but should be available for new versions too.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF57(Win 7).
New version can be added for a static theme.
![2017-11-29_1733](https://user-images.githubusercontent.com/15685960/33383412-eb61deda-d52b-11e7-8207-0bf223e73603.png)

@eviljeff : please take a look at my questions, when you have time:
1. Version number is set to be generated automatically?

2. While trying to add a new version - should we change the label for the "create a theme" button?
![upload_version_-_create_theme](https://user-images.githubusercontent.com/15685960/33383420-eef68082-d52b-11e7-913f-14ef006a18f5.png)

3. For a new version I think theme name should be preserved - now, a mandatory empty name field is displayed and typing something in it will not change the initial theme name.

**Comment by eviljeff** [comment]
1. version number is automatic; 
2.Jorge didn't specify a different label for versions; 
3. agreed on the theme name - technically you can have a different name in the manifest - which should be what you'll see when you install it.  Can you file a follow-up issue?
4. it's not the name you type?  Does the new addon theme wizard do this too?

**Comment by ValentinaPC** [comment]
I am not clear with something:
- new version for a static theme should be made using the "Select a file" button and a .zip archive or the "Create a theme" option?

**Comment by eviljeff** [comment]
You can either create the version with the create a theme button or by uploading a zip archive.

**Comment by ValentinaPC** [comment]
a) New version submission using "Create a theme" button will not change the theme name, even if we use a different name - which is ok, I guess?
b) New version using a .zip archive with a manifest file will not offer the possibility of changing theme name, or details - which is ok?

Add-ons Manager will use the name set in the manifest.json and not the one set at submission - I think this also is expected, no?

**Comment by eviljeff** [comment]
I'll just remove the theme name entirely from the theme wizard for versions.  The behavior otherwise regarding names should be the same as extensions.

**Comment by ioanarusiczki** [comment]
The name issue is tracked under https://github.com/mozilla/addons-server/issues/4809 
I'm marking this issue verified fixed on AMO dev (Win10).
