### ISSUE TITLE
user-tagging for add-ons

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-server#7030]
This may be a duplicate report, but I just wanted to suggest that I look forward to having a user tagging system, maybe like Steam.

Sometimes developers don't adds the appropriate tags, users want to highlight its characteristics in order to search and recommend.

**Comment by jvillalobos** [comment]
Tags originally worked like that on AMO, but unfortunately it's very easy for abuse (spam, bad competitors, angry users) to occur through that mechanism. We will bring back tagging later this year and need to think how we want it to evolve in the future. Being more involved as curators is part of that. I don't expect us to support arbitrary tagging, though.
