### ISSUE TITLE
Incorrect name and description for language pack

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-server#7033]
CC @peiying2 and @georgianizator

Not sure where this should be filed, but:
https://addons.mozilla.org/en-US/firefox/addon/ინგლისური-აშშ-language-pack/

The name of the add-on is currently: `ინგლისური (აშშ) Language Pack`. That's incorrect, since it's a translation of `English (USA)`.

As far as I know, that comes from this string within Firefox, and it was [updated several months ago](https://pontoon.mozilla.org/ka/firefox/toolkit/defines.inc/?search=MOZ_LANG_TITLE&string=79135) to `Georgian (ქართული)`, but that change is not reflected on the AMO website. If you download and open the XPI, it correctly says `Georgian (ქართული) Language Pack`.

That name also shows up in the Add-ons manager, but the description is still off (does that come from AMO?).

![lqwpxsk](https://user-images.githubusercontent.com/3644868/33275880-2855ce9e-d394-11e7-914e-5856f3fb47da.png)

Does it need to be manually updated in the DB?

**Comment by peiying2** [comment]
@muffinresearch could you confirm?

**Comment by diox** [comment]
The task that fetches langpacks never updates the `name` for existing add-ons. I manually updated the entry, including the slug.https://addons.mozilla.org/en-US/firefox/addon/georgian-ქართული-language-pack/ should be fixed now.

**Comment by flodolo** [comment]
Thanks. Is there any chance to update the task to look out for these changes?

**Comment by muffinresearch** [comment]
There's some incoming changes to how langpacks will be updated which should make things more automated. Since I don't think it makes sense to modify our current process I'm going to close this out.
