### ISSUE TITLE
Disco Pane theme pages should link to dev profiles

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-server#7039]
On the theme detail page in Disco Pane, please link the developer name to its corresponding profile on AMO. This exists for regular extensions but not themes at the moment, which means there's no way of connecting back to AMO once you hit this page.
<img width="1341" alt="screenshot 2017-11-26 17 03 17" src="https://user-images.githubusercontent.com/2701092/33295872-12d61e9a-d38d-11e7-8e30-c374d117620e.png">

**Comment by eviljeff** [comment]
That's not discopane anymore, it's the addons manager in Firefox (XUL).  This probably needs refiling in bugzilla but might be worth checking with someone in #teamaddons first

**Comment by andymckay** [comment]
@atsay if you did, we'd probably reclose it as pending for the about:addons rewrite.
