### ISSUE TITLE
Artist name has formatting issues when looking at theme details in about:addons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7044]
Steps to reproduce:

1. Install a theme from Discopane (i.e. Butterfly Fantasies) and look at the artist's name
2. After installation is complete, go to the Themes tab and click on More in order to check the theme details
3. Observe the format of the artist's name

Expected result:
Name of the artist is displayed without any formatting issues

Actual result:
Name of the artist includes special characters that haven't been set in the author's username or display name

Notes: Installing a theme by the same artist from AMO will generate the same results (https://addons-dev.allizom.org/en-US/firefox/addon/butterfly-fantasies/)
Reproduced on all AMO servers with FF57 Win 10.

![weird_characters](https://user-images.githubusercontent.com/31961530/33315983-f85254a4-d43a-11e7-9d1f-007713d4d17b.gif)

**Comment by diox** [comment]
`Persona.display_username` is culprit here. It's set when saving the add-on, but never get reset when the user changes their name. That field should be removed and we should just use the author's `name` instead.

**Comment by eviljeff** [comment]
As LWT are being migrated to static themes in Q3 I'm wontfix'ing this
