### ISSUE TITLE
Increase weight of add-ons flagged for using coin miners

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7052]
This is a followup for https://github.com/mozilla/addons-linter/issues/1643. This flag should give increased weight for all add-ons that have it.

It should have a weight of 20, and it shouldn't add up (multiple instances is the same as one instance).

**Comment by wagnerand** [comment]
Why not give it a really high weight to make it go to the top immediately, like 200 or so?

**Comment by jvillalobos** [comment]
It could be higher, yeah. Not sure if you want legitimate add-ons with code related to coin mining always cluttering the top. What do you think?

**Comment by wagnerand** [comment]
Yes, it would depend on how we implement the detection. I think we can keep the amount of false positives fairly low, for example by ignoring everything but JS files (so we don't match adblockers, that have anti coin-mining rules) or even just match the coinhive script (entirely or in parts).

**Comment by jvillalobos** [comment]
Alright, let's use 200, which should pretty much assure they should up on the first page or two.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

Addons that use coinmining are receiving now  2000 weight points. 
Weight is assigned just once, regardless of how many instances are detected. 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/coinhive-weight
![image](https://user-images.githubusercontent.com/31961530/49580051-a2e1a280-f956-11e8-8bc3-9694645e2b9a.png)
