### ISSUE TITLE
Going to an invalid addon page logs you out of AMO.

### ISSUE THREAD

**Issue by mkaply** [mozilla/addons-server#7053]
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org
Login.
Note you are logged in in the upper right.
Go to https://addons.mozilla.org/en-US/firefox/addon/omnibear/
Notice that you are NOT logged in in the upper right.
Go back to https://addons.mozilla.org
Notice you are still not logged in.

### What happened?

I got logged out.

### What did you expect to happen?

I expected to stay logged in.

**Comment by diox** [comment]
I can reproduce - somewhat: I'm actually still logged in if I visit the homepage by entering the URL, it's just that I'm not if I click on the logo to go back to the homepage from the error page.

In any case, it's a frontend bug (does not happen on the legacy frontend that is served by addons-server), so could you please re-file it over at https://github.com/mozilla/addons-frontend/ ?

**Comment by mkaply** [comment]
Opened https://github.com/mozilla/addons-frontend/issues/3997
