### ISSUE TITLE
Redirect Dev Hubs link to Dev Tools Collection

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7054]
When logged in to the Add-on Developer Hub, following the Tools -> Development Add-ons path directs the user to https://addons.mozilla.org/en-US/firefox/collections/whimboo/devel-tools/

![screen shot 2017-11-28 at 2 10 26 pm](https://user-images.githubusercontent.com/23342476/33346930-23826a14-d446-11e7-8b84-cefc988a75cc.png)

![screen shot 2017-11-28 at 2 10 46 pm](https://user-images.githubusercontent.com/23342476/33346936-283e14cc-d446-11e7-8eb3-68974eabf5ec.png)

The user should instead be directed to https://addons.mozilla.org/en-US/firefox/collections/mozilla/webdeveloper/

**Comment by AlexandraMoga** [comment]
Verifed on AMO-dev FF57 Win 10:

The new link redirects to a 404 page:

![image](https://user-images.githubusercontent.com/31961530/33544164-5a7c4602-d8e2-11e7-9bff-bf0d604a87a2.png)

**Comment by wagnerand** [comment]
Yes, it should work once this is on prod. Closing.
