### ISSUE TITLE
generate preview from static themes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7056]
There's a template we can hopefully reuse, but we're going to have to do it in python to handle api and devhub zip uploads.

**Comment by eviljeff** [comment]
ref: mozilla/addons#568 for what the screenshot/preview should be like

**Comment by eviljeff** [comment]
From the Austin work week there was a decision the preview be the same size as the existing LWT preview, which is 680x100.

Static Theme previews are being implemented as normal add-on previews (i.e. screenshots) which have a full size and a thumbnail size.  Do we want two sizes?  Could do 680x100 as the thumbnail size, but then "full size" is what exactly?  rendering a 3000x200 full persona size is a bit nuts.  Alternatively 680x100 would be the "full size" and we could have a smaller thumbnail for... something.

@tofumatt @kumar303 @jvillalobos

**Comment by jvillalobos** [comment]
I don't know of any use we can have for a larger or smaller image. However, it would be time-consuming to generate new images for all themes if we needed them. Scaling down is not too bad, but scaling up is terrible, so I would suggest having a 2x full image (1360x200) that we can use in case we need a larger preview in the future.

**Comment by eviljeff** [comment]
@jvillalobos problem - I don't know what a 200 high preview will look like after I make the changes we agreed to in the all hands meeting to focus on a simple UI of a typical user (i.e. it'd be 100 pixels or less or tabs and buttons, then content.  No menus or extra toobars).

**Comment by jvillalobos** [comment]
I was thinking it would be the exact same image, but doubled the size. Given the source is SVG, things should generally scale up well. However, maybe that won't work so well with background images or icons, so maybe we should just stick to the one preview image.

**Comment by ioanarusiczki** [comment]
@eviljeff Can we help by verifying here ? If so, please provide some more details. 
Thanks!

**Comment by eviljeff** [comment]
@ioanarusiczki if you upload a static theme - or create one via the wizard - then a preview of the theme should be saved as a screenshot.  I don't know what new frontend displays for static themes currently, but legacy frontend should display them as a standard extension style page - and the preview should be shown as a screenshot (with the version as the preview description).

As an extra step you could verify that a new preview is added for each new version uploaded.

If you do find any bugs please file as follow-up rather than re-opening - the commit isn't going to get reverted and won't be fixed for a while.

**Comment by ioanarusiczki** [comment]
Hi, I made some tests on AMO dev, FF58 (Win10) and I filed the following
https://github.com/mozilla/addons-server/issues/7610
https://github.com/mozilla/addons-server/issues/7611
https://github.com/mozilla/addons-server/issues/7614
I'll update this when other issues will be discovered during this week.
