### ISSUE TITLE
Add-on validator page in devhub should not contain checkbox for listed/unlisted status

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#7059]
https://addons.mozilla.org/developers/addon/validate
![image](https://user-images.githubusercontent.com/607379/33373311-99319ada-d501-11e7-8bdb-38a2c6a98ebe.png)
The checkbox here is out of place, it should not exist here. It should show up in the submission process, but not on the page to manually validate an add-on.

**Comment by wagnerand** [comment]
The functionality of the checkbox needs to stay.

What we need to do here is update the style to use the radio-boxes, like on the regular submission page: https://addons.mozilla.org/en-US/developers/addon/submit/distribution

<img width="989" alt="screen shot 2017-11-29 at 12 37 11" src="https://user-images.githubusercontent.com/873258/33373402-0fdee278-d502-11e7-8868-bf1435a87c2b.png">

**Comment by VishalCR7** [comment]
@wagnerand what I understand is that we need to just replace the check box with radio-button on https://addons.mozilla.org/developers/addon/validate  right?

**Comment by wagnerand** [comment]
Yes, addons.mozilla.org/developers/addon/validate should look similar to (or rather the same as) addons.mozilla.org/en-US/developers/addon/submit/distribution.

**Comment by VishalCR7** [comment]
Should i add two options i.e 
![image](https://user-images.githubusercontent.com/24241258/34786124-2f18a782-f659-11e7-9039-0e3f96d5d3f1.png)

or just replace check-box with radio button in this:
![image](https://user-images.githubusercontent.com/24241258/34786160-4ce023bc-f659-11e7-9e7a-9cfa79178e3f.png)

**Comment by wagnerand** [comment]
There should be two options, like on the regular submission page.

**Comment by VishalCR7** [comment]
Thanks @wagnerand  I ll start working on it then!

**Comment by VishalCR7** [comment]
@wagnerand I tried using the validator tool and it doesn't actually makes any difference if the functionality is present or not as what validator does is just validating the addon and showing results. They are not submitted or there are not anymore further steps(functionality) after that. So should I still add these options? I think that the issue originally was right and the checkbox should be just removed.

**Comment by wagnerand** [comment]
Ah, yes, contrary to my belief in my earlier comment, the standalone validator does not accept legacy files anymore, which means the checkbox is probably not needed anylonger. Is this is intended (@jvillalobos can confirm), it should be ok to remove the checkbox.

**Comment by jvillalobos** [comment]
There might be a difference in the validation output if there's an `update_url` present. That should pass for unlisted for show an error for listed. If that's not the case, I suppose we can drop the checkbox for simplicity.

**Comment by VishalCR7** [comment]
@jvillalobos @wagnerand  as @jvillalobos pointed out its exactly the case with `update_url` (checked it by uploading the addon with update_url as well as this is whats written in validator code `*listed=True*
        If the addon is unlisted, treat it as if it was a self hosted one
        (don't fail on the presence of an updateURL).` ) .
 So should I replace one option checkbox with 2 option radio-button ?

**Comment by wagnerand** [comment]
Yes, please do so. Thank you.

**Comment by VishalCR7** [comment]
@wagnerand please review the PR #7329 regarding this issue. Thanks!

**Comment by vcarciu** [comment]
It looks like validator is not working anymore on -dev: 
![validator](https://user-images.githubusercontent.com/1583842/35286924-e2746fa4-0069-11e8-89cb-bce192ed22ee.gif)

**Comment by diox** [comment]
@VishalCR7 do you think you can fix the problem? `$isUnlistedCheckbox` was removed but it's still used here:
https://github.com/mozilla/addons-server/blob/c88516280cd8833b3d4637fdd84bc4a6f5b7e2f3/static/js/common/upload-addon.js#L324

**Comment by VishalCR7** [comment]
@diox  I have fixed it and I will be adding a new PR as soon as possible.

**Comment by VishalCR7** [comment]
@eviljeff @vcarciu I have fixed it in PR #7378 . Extremely Sorry for the inconvenience.

**Comment by vcarciu** [comment]
@diox : l observed that the "More information on Add-on Distribution and Signing"  link is missing from Validator , but it is present in the bug description. Do you know if this is expected?

**Comment by diox** [comment]
I don't know if we care. @wagnerand ?

**Comment by vcarciu** [comment]
@diox : I will mark this as verified and I will open a separate bug for the missing link if @wagnerand will ask for that.

**Comment by VishalCR7** [comment]
@wagnerand is not available this week (as informed.)

**Comment by vcarciu** [comment]
@VishalCR7 : this is not a problem , I think that the link can be added later in a different issue without affecting the Validator

**Comment by VishalCR7** [comment]
@vcarciu : let me know if required in this thread. I would be very happy to finish it up.

**Comment by wagnerand** [comment]
Ultimately, a question for @jvillalobos. Imho, we can do without that link on the standalone validator page.

**Comment by jvillalobos** [comment]
Adding it is nice to have, and should be done in a follow up if anyone wants to take it. Related, I also noticed that the styling is a bit off with the text bold. See [submission](https://addons.mozilla.org/developers/addon/submit/distribution) vs. [standalone](https://addons.mozilla.org/developers/addon/validate). Again, something that can be fixed in a followup.

**Comment by rctgamer3** [comment]
This wasn't fixed, the page still contains elements relevant to the page, such as the new radio buttons for listed/unlisted.

**Comment by rctgamer3** [comment]
Follow up: Seems good as-is right now, maybe drop part of the bold text.
