### ISSUE TITLE
Posting an abuse report affects the throttle of the ratings API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7062]
### Describe the problem and steps to reproduce it:

See https://github.com/mozilla/addons-frontend/issues/4010

### What happened?

Posting an abuse report affected the throttle of the ratings API.

### What did you expect to happen?

It should not affect the ratings API throttle.

**Comment by diox** [comment]
Both `AddonAbuseViewSet` and `RatingViewSet` have `throttle_classes` set, and their throttling class inherit from the `UserRateThrottle`. They don't set a specific `scope` though, so it's shared, even though their limits are different.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev FF57 (Win10, Android 7.0)

![throttle_fix](https://user-images.githubusercontent.com/31961530/34782939-db9bf224-f632-11e7-8ccc-67fdda7c244b.gif)
