### ISSUE TITLE
Expose information about pending extension in 401 response

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7064]
### Describe the problem and steps to reproduce it:

* Upload a theme or extension
* Make an API request for the add-on details before the add-on has been auto-approved

### What happened?

You see a 401 request with some data about the reasons:
```
curl -v 'https://addons-dev.allizom.org/api/v3/addons/addon/dev3-theme2/'
< HTTP/1.1 401 UNAUTHORIZED
< Content-Type: application/json
...
{"is_disabled_by_mozilla":false,"detail":"Authentication credentials were not provided.","is_disabled_by_developer":false}
```

### What did you expect to happen?

There is no reason to indicate that the add-on is pending approval.

### Anything else we should know?

I think we just need a new key like `is_pending_approval` or whatever.

The old site showed a message saying "this theme/extension is pending approval" so the new frontend should do something similar.

Here are screenshots of the new and old behavior: https://github.com/mozilla/addons-frontend/issues/3966

**Comment by wagnerand** [comment]
Hm, pending extensions don't have a public product page, why would this be different for themes?

**Comment by wagnerand** [comment]
If I remember correctly, we deliberately changed the behavior for the new frontend, @jvillalobos could confirm (or deny).
