### ISSUE TITLE
Add a private whiteboard for reviewers

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#7065]
For reviewers it would be great if we had a private whiteboard that we can use to write down information relevant to the add-on. The consequence if this is not added is that hard-to-determine edge cases (e.g. when use of eval is acceptable) may be overlooked, causing grief later on when the developer gets a rejection for something that has already been discussed. With the private whiteboard we have a chance to write this down without having it lost in the comments section of a previous version.

For testing we need to make sure the private whiteboard stays private to reviewers, the public whiteboard remains accessible to developers and reviewers. Upgrading should also retain public whiteboard data since data is migrated.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win 7).
A private board is displayed in add-on review page.
Reviewer can update the board.
Postfix screenshot:
![2017-12-05_1237](https://user-images.githubusercontent.com/15685960/33603186-6862cec0-d9ba-11e7-9aa9-d0ab1bd65726.png)
