### ISSUE TITLE
Add new pytest dependency's to support pytest 3.3.0

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#7066]
As seen here #7040, pytest added some new dependency's with their latest updated. 

@EnTeQuAk pointed out in that PR what they are: ```attrs``` and ```pluggy```. 

I think it would be good to add these before the selenium update to make sure they're compatible, which they should be.

**Comment by EnTeQuAk** [comment]
Sorry for stealing this but I just pushed everything to https://github.com/mozilla/addons-server/pull/7040 which hopefully lands today. I'll update the issue as necessary.

**Comment by EnTeQuAk** [comment]
just merged it
