### ISSUE TITLE
Create separate section for theme form in add-on submission flow

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7069]
Followup for #6860.

The page currently shows the Upload button and the Create a Theme button side-to-side, which seems confusing. We want them to be similarly prominent, but still separate. I suggest something like this:

> **Upload version**
> // regular stuff here
> **Create a theme version**
> You can upload a finished theme using the upload option above, or you can build it yourself using this tool.
> [Create a Theme]
> 
> [Continue]

**Comment by ioanarusiczki** [comment]
Verified on AMO-dev FF57 (Win10)
![create a theme](https://user-images.githubusercontent.com/33448286/34609369-1ef784a0-f225-11e7-82b5-5d4ef7e123df.png)
