### ISSUE TITLE
Theme generator changes

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7070]
Followup for #6860.

They're a bunch of (I think) small fixes, so I'm just bundling them in one issue. Feel free to branch it out:
* [x] The "Select a different header image" link should open the upload dialog right away, and the image shouldn't be changed unless a different image is selected (so clicking on Cancel in the upload dialog should keep the previous image).
* [x] Preselect reasonable options for the required colors. I suggest white for the header area bg and black for the header area text.
* [x] Remove the parentheticals with the manifest names for the colors. Add them to the help popups ("Corresponds to toolbar_field in the manifest.").
* [x] In the section headers (like "Select a header image"), use "theme" in lower case and remove the ending periods.
* [x] Change label in button: "Upload Theme" -> "Finish Theme".

**Comment by eviljeff** [comment]
> Preselect reasonable options for the required colors. I suggest white for the header area bg and black for the header area text.

Not sure about white for the header area background - pretty sure Firefox doesn't use white (`#fff`) and besides the toolbar background defaults to white in the preview (with a partial transparency) so it all blends together.  Try it out in the wizard and see.

**Comment by jvillalobos** [comment]
Not a big deal either way, since theme background images will generally cover the whole toolbar. The ideal color might be the default background color in the Windows theme, so I'm okay with changing it to that.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF57, Win10
- The previous background remains in place if the user cancels the option to upload a new image
- manifest name for colors are now present in the help pop-ups

![image](https://user-images.githubusercontent.com/31961530/34953846-c6469116-fa26-11e7-93a4-935066c7e52b.png)

@eviljeff eventually, the decision was to have as Header background the basic Windows theme color (#e3e4e6)?

**Comment by eviljeff** [comment]
yep
>  The ideal color might be the default background color in the Windows theme,
