### ISSUE TITLE
Change last submission step for listed themes

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7073]
Followup for #6860.

The copy and options being shown now are the same for extensions, but some of it doesn't apply to themes. Please change to this:

> You’re done! This version will be available after it passes review. You will be notified when it is reviewed.
> 
> Your listing will be more successful by adding a detailed description. Get your listing ready for publication:
> 
> [Manage Listing]
> 
> [Go to My Submissions]

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF57 (Win10)

![image](https://user-images.githubusercontent.com/31961530/33823728-c7910bba-de64-11e7-99f4-4d82365450b4.png)
