### ISSUE TITLE
Trending themes showing themes with single-digit usage

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7088]
This is what I see on the themes homepage right now:

<img width="1171" alt="trending" src="https://user-images.githubusercontent.com/62568/33492176-ea67f116-d681-11e7-86cc-49a12184e56d.png">

Those themes has almost no usage and appear just to be very recently-added. There should be a minimum threshold of usage to appear on that list, to avoid random new stuff to show up.

**Comment by EnTeQuAk** [comment]
This is a p2 but I probably won't be able to get to it till 01.18 milestone. Let me know if that works, otherwise I'll try to sqeeze it in.

**Comment by EnTeQuAk** [comment]
@diox or @eviljeff I may need a bit of a history lesson here… looking at https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/cron.py#L230-L259 we never calculated the `hotness` for personas which seems to be the problem we are hitting here.

Can we simply do that? Or should we expose a different value for themes here?

**Comment by eviljeff** [comment]
Yeah, in the legacy frontend for the `up-and-coming` sort/section we use `Persona.movers` for LWT, and `hotness` for Addons - the API only looks at `hotness` only.  (tbh I noticed this while investigating stats migration for LWT and forgot to file an issue about it).  

We _could_ calculate `hotness` for LWT too - though it doesn't use `UpdateCount` so it'd need some tinkering - but just switching the API to use `movers` is the easy fix here and it's [almost the same](https://github.com/mozilla/addons-server/blob/master/src/olympia/stats/management/commands/update_theme_popularity_movers.py#L30).

**Comment by EnTeQuAk** [comment]
> We could calculate hotness for LWT too - though it doesn't use UpdateCount so it'd need some tinkering - but just switching the API to use movers is the easy fix here and it's almost the same.

Perfect, I'll do that! I never knew about `Personas.movers`

**Comment by diox** [comment]
Essentially all static themes and personas have zero hotness at the moment. For personas, it's because we exclude them from the code that computes that value, and don't copy the `movers` property. For static themes, it's because... they are too recent! To be set, the add-on must have had at least one active user 4 weeks ago and more than 1000 this week.

**Comment by diox** [comment]
@jvillalobos can we just hide this block for now and wait for static themes to become "hot" enough to fix the problem ? Eventually as static themes grow in popularity the problem will go away (see the rule I describe above)

**Comment by eviljeff** [comment]
@diox when all LWT are migrated to static themes then, assuming some of them are indeed "hot", won't the list be populated correctly then?

**Comment by diox** [comment]
it will if some of them are hot and stay that way, yes.

**Comment by jvillalobos** [comment]
This issue is almost a year old. If the theme migration will fix this anyway, I think we can leave the block alone and just close this issue.

**Comment by diox** [comment]
Closing as wontfix per previous comment, the situation will rectify itself once we get enough static themes with enough users.
