### ISSUE TITLE
Don't flag user ratings that have no review text

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#7110]
### Describe the problem and steps to reproduce it:
Reviewers have been requested by admins for a while now to select "Keep review; remove flags" for all mobile user reviews that are getting flagged. Those are currently blank as (I think) there is no way for now to enter text for a review on mobile.

### What did you expect to happen?
Flagged empty user reviews should be either : 

a. Hidden from reviewers;
b. Get their flag automatically removed by the server so they don't show in the queue.

**Comment by wagnerand** [comment]
As far as I can see, you can only flag those in the old frontend. Maybe we should prevent empty reviews from being flagged by either:

1) Don't show them on the reviews page.
2) Remove the "Report this review" link.

**Comment by ochristi** [comment]
@wagnerand They already do not appear on the reviews page. Also they can be flagged on multiple locations, two I know of: Review page, User page.
This is a bit off topic, but to give an opinion, as a (add-on) developer I would prefer to have a list of all reviews, to get an idea of what the mood is, the activity feed already does not display this. The point is, removing access to those complete, would be bad.

**Comment by wagnerand** [comment]
@ochristi thanks for the note about the user page.

Ratings without a review text are also hidden in the new frontend afaik, so it makes sense to adapt the old frontend to this to avoid those moderation flags.

**Comment by eviljeff** [comment]
The new account profile page is coming soon and I wouldn't expect empty ratings to be shown on there, so at that point it's only legacy frontend pages that expose them to be flagged.

**Comment by eviljeff** [comment]
The correct data is already available in the API so new the account page won't display empty reviews

**Comment by wagnerand** [comment]
As long as the legacy frontend is around, it can be used to flag empty reviews. Given that reviewers have to handle hundreds of moderated reviews each week, I believe it makes sense to add a filter to the queue page, given that it should be fairly low effort.

**Comment by wagnerand** [comment]
After some discussion/clarification in IRC and digging through the code, we are going to do the following:

When a rating that doesn't have a review text gets flagged by the user, we just don't set the flag internally. This affects the legacy frontend only.

This might seem a little odd, but the API already behaves that way and since the new frontend uses the API it shows the same behavior. Although the new frontend sometimes doesn't show individual ratings without a review text which makes it impossible to flag them using some of the frontend pages.

**Comment by vcarciu** [comment]
Verified as fixed. No empty flagged reviews seen anymore on https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/reviews
