### ISSUE TITLE
broken review page links on /developers/addons (Manage My Submissions)

### ISSUE THREAD

**Issue by ochristi** [mozilla/addons-server#7111]
### Describe the problem and steps to reproduce it:
* As logged in developer developer access https://addons.mozilla.org/developers/addons
* Have at least one add-on assigned

### What happened?
All listed Add-ons have a link to their respective reviews. The links use the old anchor link in the form of `https://addons.mozilla.org/firefox/addon/<addon-id>/#reviews`

### What did you expect to happen?
The links should point to `https://addons.mozilla.org/firefox/addon/<addon-id>/reviews/`

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
mentor @diox

**Comment by SeanPrashad** [comment]
I've gone ahead and submitted a fix for this! Please let me know if there's anything else I may help with!

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF58, WIn10.
The link is now redirecting correctly to the add-on review page:
![reviews link](https://user-images.githubusercontent.com/31961530/36027858-a0320a2c-0da5-11e8-8a0b-8986e09dafc4.gif)
@eviljeff we might have a small inconsistency when it comes to empty reviews. The legacy site does not ignore them, so they will come up in count when looking at ratings in Dev Hub. If ,for example, the add-on has only empty reviews, the user will land on an empty reviews page when selecting the link (like this one https://addons-dev.allizom.org/en-US/firefox/addon/friday_firefox/reviews/)
If you think this needs pursuing I can open a new issue.

**Comment by eviljeff** [comment]
@AlexandraMoga it's not a particularly high priority fix, but it should probably be consistent in devhub and the new frontend, yeah.
