### ISSUE TITLE
Category selection should not be required for Language pack and dictionary submissions

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7113]
Steps to reproduce:

1. Log in to Developer Hub and submit a new Language Pack (i.e. https://addons-dev.allizom.org/en-US/developers/addon/submit/distribution)
2. Once the package passes validation, click Continue to edit the details of your submission
3. Observe that there is a 'Select a Category' section (mandatory)

Expected result:
Category section should be excluded from the Language Packs submission form

Actual result;
Category filed is displayed with title 'Select up to 2 Firefox categories for this add-on' and one category option - 'General'

Reproduced on all AMO servers with FF57 (Win10)

![image](https://user-images.githubusercontent.com/31961530/33722131-d3d8c796-db71-11e7-90fb-4a0c2486d908.png)

**Comment by ioanarusiczki** [comment]
This issue is also reproducible on AMO dev for dictionaries - using FF58 (Win10).

![dictionaries general](https://user-images.githubusercontent.com/33448286/36734500-4ff5a006-1bdc-11e8-8124-b7de0fc7c7dc.png)

**Comment by AlexandraMoga** [comment]
This issue is still valid
