### ISSUE TITLE
Remove message at bottom of review emails prompting developers to migrate to webext

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7114]
We no longer need to ask developers to migrate to webextensions for 57, so we might as well just remove that from the reviewer emails.

This basically reverts https://github.com/mozilla/addons-server/pull/5042.

**Comment by ValentinaPC** [comment]
I made a reviewer reply to an add-on from stage and checked the Fake Email Log page, but did not see a section regarding migrating to webextensions.
Please see screenshot:
![2017-12-08_1010](https://user-images.githubusercontent.com/15685960/33756877-24f60d3a-dc00-11e7-95ce-b379ef6fdcc3.png)

I am looking in the wrong place?

**Comment by wagnerand** [comment]
This bug is about removing the section, so it shouldn't be there. You can test it by rejecting or approving a legacy version and then checking the email.

**Comment by ValentinaPC** [comment]
> This bug is about removing the section, so it shouldn't be there.

I suppose it should still be there, on stage, I mean, no?
Also, to see if something was fixed, I must first see how it look like before - and, usually I am checking this on stage.
My question was just to assure myself that I am looking in the right place.

> You can test it by rejecting or approving a legacy version and then checking the email.

Other review actions like: reviewer reply, that generate mails, don't display the message. Approving/rejecting, do.

Verified as fixed on AMO-dev FF57(Win 7).
Postfix screenshot:
![no_57](https://user-images.githubusercontent.com/15685960/33766570-c3d29ed4-dc26-11e7-8f99-e13015fe45b3.png)

**Comment by wagnerand** [comment]
Sorry, yes, it should still be on stage. As far as I know, they are only displayed for approvals/rejections of legacy add-ons, not for other review actions.
