### ISSUE TITLE
Add an API method to get details about multiple addons with a single request

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#7119]
Over at https://bugzil.la/1402064 we are working on migrating Firefox from API version 1.5 to the new API.  Firefox currently uses the search API endpoint which can return the details for a list of addons (specific by guid) in a single request.  But there does not appear to be a way to do this with the new API.
The next Firefox ESR will be based on 59, which uplifts on Jan 22 so if we can get this all in place by then, the old API can be retired some time after ESR52 is end-of-life, otherwise we'll have to wait for ESR59 to reach end-of-life, which would be sometime in 2019 (!!)

**Comment by AlexandraMoga** [comment]
I've made a request on -dev to retrieve details for multiple addons but I'm still getting a `'Not-found'` result.
Are the changes not available yet or am I missing something in my request?
https://services.addons-dev.allizom.org/api/v3/addons/addon/aaa@xulforge.com,tabs-tabs-tabs-test-123@mozilla.org/

Verified with FF57, Win10

**Comment by eviljeff** [comment]
Ah, you reminded me I forgot to document how to use the API in the docs.
It's a search parameter so the URI would be:
https://addons-dev.allizom.org/api/v3/addons/search/?guid=aaa@xulforge.com,tabs-tabs-tabs-test-123@mozilla.org

The code is live but I need to have ops do something to make it work (rebuild the ElasticSearch index)

**Comment by eviljeff** [comment]
docs are live now too.

**Comment by AlexandraMoga** [comment]
This can be marked  as verified fixed. Add-on details can be retrieved when searching by multiple guids:
- https://addons-dev.allizom.org/api/v3/addons/search/?guid=addon111@example.com,{4dfeed54-1a52-4a42-a96d-50e37e1f2d6e},tabs-tabs-tabs-test-123@mozilla.org
- https://addons-dev.allizom.org/api/v3/addons/search/?guid=kittens@pioneer.mozilla.org,aaa@xulforge.com,{c9bb2665-0c3f-4d95-9ea5-7b10c1ca3af0}
