### ISSUE TITLE
develop AMO back-end publishing tool

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#7120]
Creating this issue to kick start planning for the Q1/2018 development of an AMO back-end editorial publishing tool. (Currently, all content programming changes require manual code updates). 

This [PRD](https://docs.google.com/document/d/1JLNsuRbd8m4uG-HW5j67_sAT4wb1z-pAj0YaHd_76wE/edit#) was used as a foundational document for AMO's front-end redesign relative to editorial programming; and it includes publishing tool feature requirements. But is this PRD comprehensive enough to begin work focused on a publishing tool? Or should the tool have its own distinct PRD?

Also... should we produce wireframes for the tool? Other UI detailing? Anything else? 

@muffinresearch @pwalm @jvillalobos

**Comment by jvillalobos** [comment]
I started a [PRD for Admin Tools](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#) where I wanted to cover the management support for content curation (at least for the homepage) and wanted to get your feedback on that.

The general idea is that it would behave like toolbar customization in Firefox: the homepage is like the toolbar, homepage modules are like buttons, and the admin tool is like the customization UI. There are a set of pre-built modules that can be moved between the homepage and an unused list, and reordered as needed. 

We should find some time for this next week, so we can go over it in person.

**Comment by muffinresearch** [comment]
@devaneymoz I think we have the broadstrokes of what we're trying to do here. I'm going to close this - but if you think we still need it please reopen.
