### ISSUE TITLE
Unbroken strings are not wrapped for Release Notes

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7128]
Steps to reproduce:  

 1. Log into AMO and go to Developer Hub (i.e. https://addons-dev.allizom.org/en-US/developers/)
 2. Click one of your submitted add-ons
 3. In the  Manage Status&Versions section click the Version of your ad-on (such as https://addons-dev.allizom.org/en-US/developers/addon/swarrand/versions/1533356)
 4. Insert a long unbroken text in the Version Notes and Save Changes
 5. Click on View Listing and observe the Release Notes field

Expected result:
Text is wrapped 

Actual result:
Text is not entirely displayed and appears cut

Notes:
Reproduced on both AMO-stage and dev with FF57(Win 10)
![release notes](https://user-images.githubusercontent.com/33448286/33887271-ebab6552-df51-11e7-97a6-57c78c83886a.png)

**Comment by eviljeff** [comment]
This is a bug on the frontend rather than in devhub. Can you re-file this in the mozilla/addons-frontend repo?

**Comment by AlexandraMoga** [comment]
Filed [#4086](https://github.com/mozilla/addons-frontend/issues/4086) on addons-frontend
