### ISSUE TITLE
Remove /services/monitor page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7133]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1393850
Drop `/services/monitor` (but keep `/services/monitor.json`) as they arne't used any more.

**Comment by AlexandraMoga** [comment]
Hi @eviljeff I was trying to open the bug from Bugzilla thinking that I might find some STR there but I do not have access to read this bug. I have a Bugzilla account, so that should not be a problem. 
Are you able to give me access?
