### ISSUE TITLE
Yardi compatiable 

### ISSUE THREAD

**Issue by Domaine** [mozilla/addons-server#7134]
Yardi stays in test mode i need the viewer like IE or something to fully use the website 

https://www.yardiaspla1.com/3005lpcres/pages/Login.aspx

**Comment by muffinresearch** [comment]
Please, can you provide more details as to what issue you're seeing and how it relates to addons.mozilla.org?

**Comment by muffinresearch** [comment]
This bug tracker is related to the addons server component of addons.mozilla.org. If your issue relates to an add-on then please look for a way to request support from the add-on author. 

On the basis there's no action to take here I'm going to close this issue.
