### ISSUE TITLE
Quick link to add-on management page / review page from add-on listing

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#7139]
Before the redesign the add-on listings featured links to quickly navigate to the add-on management page (as a developer, e.g. to upload a new version or edit the description), and the review page (as an add-on reviewer).

These links are non-existent in the redesigned AMO. Can these links be restored?

**Comment by jvillalobos** [comment]
Tracked on https://github.com/mozilla/addons-frontend/issues/2756
