### ISSUE TITLE
Rejected add-on still appearing in search results

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#7140]
This add-on was rejected a few days ago: https://reviewers.addons.mozilla.org/en-US/reviewers/review/stream-love-hip-hop-new-york87

But it still shows up in the search results, both in the old and the new AMO:
Search for "episode", sort by Recently updated, filtered by extensions: https://addons.mozilla.org/en-US/firefox/search/?q=episode&sort=updated&type=extension

In the new UI, it links to https://addons.mozilla.org/en-US/firefox/addon/stream-love-hip-hop-new-york87/

In the old UI, it links to https://addons.mozilla.org/en-US/firefox/search/?src=search

@kewisch @eviljeff

**Comment by eviljeff** [comment]
I fixed this add-on but if you see this bug again and/or can see how it happened so we can reproduce open an issue again.
