### ISSUE TITLE
Perform some basic automatic checks on addon metadata before approving them

### ISSUE THREAD

**Issue by marco-c** [mozilla/addons-server#7150]
My addon was automatically accepted, despite containing the string "Firefox" in its name, which is apparently not allowed.
This check should be made during addon submission, preventing the submission altogether.

**Comment by eviljeff** [comment]
I think this is going to be hard to do as the rules (as I understand them) don't explictly prohibit "Firefox" in the name, just naming the Add-on in a certain way that could imply it's official. Plus you could actually be uploading an official add-on.

@jvillalobos to opine|close as appropriate.

**Comment by jvillalobos** [comment]
We rarely auto-reject because there are always multiple cases where the rule wouldn't apply. I _think_ we had a warning flag for using "Firefox" in an add-on name, but maybe it was only in the legacy validator. @wagnerand or @kewisch can confirm if we still have it.

**Comment by wagnerand** [comment]
We still have the policy, but I can't find a rule or a linter issue for it.

**Comment by eviljeff** [comment]
I'm going to close this on addons-server - reopen on addons-linter if you think it deserves a warning there (though comment 0 calls for preventing the submission altogether, and a warning could just be ignored)

**Comment by marco-c** [comment]
I think a warning is better than nothing, at least you know you have to change the name before submission.
