### ISSUE TITLE
Changing "payment required" should reset the needinfo status

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#7151]
Changing the "payment required" field should reset the needinfo status for an add-on. We often request this to be changed, and it would be good to react earlier to this.

@wagnerand does this make sense for you?

**Comment by wagnerand** [comment]
Part of #7007.

**Comment by kewisch** [comment]
Ok, moving my comment over.

**Comment by wagnerand** [comment]
Keeping this open  is also fine, I just wanted to link them together :)
