### ISSUE TITLE
Remove beta version support

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7163]
- [x] Email developers using beta versions, explaining that this feature will be removed soon and alternatives to use (PM).
- [x] Disable beta version submission and listing, gated by a waffle switch. (#7435)
- [x] Publish blog post explaining removal and update documentation (PM).
- [x] Redirect beta update pings to the main branch. (#7830)
- [x] Flip waffle switch (PM).
- [x] Disable all files with beta status. (#7904)
- [x] Remove code related to beta versions. (#8099)
- [x] Remove `beta-versions` waffle flag. (#8660)

**Comment by wagnerand** [comment]
>  Redirect beta update pings to the main branch, gated by the same waffle switch.

Using the same switch means that users will be migrated off the *beta* channel right away (if there is a newer stable version). So, reverting the switch won't have any effect for the ones already migrated. Are we ok with that?

**Comment by jvillalobos** [comment]
The waffle flag is only meant to control the timing between the email and the actual change. If we send the email, then we're committed to doing it and should accept there's no going back.

**Comment by diox** [comment]
Note: I don't know if we have a better alternative, but it's probably best to avoid making the update service depend on a waffle switch. We never done this before AFAIK and this code is kinda weird, trying very hard not to directly import django stuff and do the database queries manually.

**Comment by eviljeff** [comment]
agree with @diox here. Anyway we can avoid using a waffle flag in `update.py` is desirable.

**Comment by jvillalobos** [comment]
Okay, I'll update the timing to take that into account.

**Comment by wagnerand** [comment]
With that in mind, do we still need the waffle switch for submission and listing?

**Comment by eviljeff** [comment]
A waffle for the devhub work is practical, so it can be reviewed and landed anytime. (Not clear what the objection is to having a waffle for that part of the work).

 The change for update.py we'll have to land and test without the waffle so will need QA to be aware it needs to be extra tested. 

There is no other gating.

**Comment by wagnerand** [comment]
Ah, I thought the submission and listing changes would land together with the changes to the update-service. If we land the code separately, a waffle switch makes more sense. If they are landed together, I'm not sure how much sense a waffle switch makes: we'll start moving users to the release branch right away, so there is not much of a point in still allowing beta submissions.

**Comment by muffinresearch** [comment]
@jvillalobos do you have a timeline in mind for when this should happen?

**Comment by jvillalobos** [comment]
It's not urgent. During the Austin WW @wagnerand mentioned he wanted to do this in Q1 himself, which is why I filed it and will help with the PM work.

**Comment by eviljeff** [comment]
I can't see any absolute objection to landing all the code at once but I suspect the devhub changes will be numerous but not particularly impactful so normal review and QA can be done; the update.py changes will be very slight in terms of number of lines of code but could break all the things for updates so need to be very carefully reviewed and QA'd.

**Comment by AlexandraMoga** [comment]
@wagnerand is there anything left to be tested around this feature apart from what we've marked already as verified?
Thanks

**Comment by wagnerand** [comment]
@AlexandraMoga the last part was removing the waffle flag `beta-versions`. If you'd like to test that, just make sure it's not on the waffle flag admin page anymore.

**Comment by AlexandraMoga** [comment]
No more `beta-versions` flag in admin pages on -dev and stage:
![image](https://user-images.githubusercontent.com/31961530/41974659-3cbcc2c8-7a21-11e8-927f-4d7fa5ee5018.png)

Considering that all other related issues were verified, I'm going to mark this one as verified fixed as well.
