### ISSUE TITLE
Filter collections by user and add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7167]
There is already a way to find all collections belonging to a user: https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#list

The `frontend` would like a way to find all user collections that an add-on belongs to. For example, *uBlock Origin* might belong to three collections that the user had made: *Ad Blockers*, *Privacy*, and *Faster Browsing*.

Here is a description of this feature from the site user's point of view: https://github.com/mozilla/addons-frontend/issues/2768

As a current workaround we have to list all user collections and then list *all add-ons* for each collection and filter the add-on list to see if any matches the target add-on.

**Comment by diox** [comment]
Alternative approach discussed on IRC:
- Add a parameter to the collection list endpoint for a given user, allowing to pass an add-on
- If that parameter is present, the collection list return an extra field for each collection returned, indicating whether or not the add-on is present in the collection.

It should be enough to work around #7173 and avoid calls to add-ons list for each collection. I just need to check if it does not incur a bad perf hit.
