### ISSUE TITLE
Indicate that external software is required if nativeMessaging is used

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#7170]
When nativeMessaging is required in the manifest, the user will have to install external software to use the add-on. The data exchanged with this application may be privacy sensitive. Our policies protect against this to some extent, but certain kinds of applications will require access to sensitive data (e.g. password managers). 

With the new policy we require data exchanged via nativeMessaging to be disclosed in the privacy policy. Therefore, I'd suggest that we add info to the AMO listing to inform the user about this. For example, we could show a message like this:

> This add-on requires use of external software. Data exchanged with this software is not under our control, please consult the developer’s privacy policy for more details.

Wording to be improved. This may be a scary warning, but then again exchanging data with an app can be scary.

@jvillalobos @wagnerand what do you think?

**Comment by jvillalobos** [comment]
I don't think this should be highlighted beyond what is already done in the permission. Other permissions and add-on behaviors have similar privacy implications and we don't special-case them either. If there's something to refine in the permission message, that should be done as part of #2757.
