### ISSUE TITLE
Investigate code review and search tools

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7171]
This tracking issue covers the code review and search tools as specified in the Reviewer Tools PRD, specifically the sections ["File and Diff Viewer"](https://docs.google.com/document/d/1Me-2Qx-C7cMptKQt_-1gAyPZCBOiww9laQLEMlD9N2M/edit#heading=h.nc9b5q9b6vd8) and ["Code Search"](https://docs.google.com/document/d/1Me-2Qx-C7cMptKQt_-1gAyPZCBOiww9laQLEMlD9N2M/edit#heading=h.bm70cluquedx). The key requirements are:
* Code inspection of any add-on file.
* Showing linter flags in context.
* Diffing between any two versions of an add-on.
* Tracking the origin of code lines (like `blame`).
* Searching within an add-on version.
* Searching over the entire repository of latest add-on versions.

The task is to investigate which tool or set of tools best satisfy these requirements, and produce a prototype for what would be integrated into AMO.

**Comment by wagnerand** [comment]
> Searching over the entire repository of latest add-on versions.

https://oracle.github.io/opengrok/ seems like a viable candidate for this and has been recommended to me for this task by several people.

**Comment by EnTeQuAk** [comment]
This is pretty much done, I just need to publish my findings and plans for implementing this. Putting it into next weeks milestone so that I don't forget about that.

**Comment by EnTeQuAk** [comment]
I'm closing this one as we're investigating this through other channels.
