### ISSUE TITLE
https://www.facebook.com/profile.php?id=100011206217039

### ISSUE THREAD

**Issue by heck19** [mozilla/addons-server#7186]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by heck19** [comment]
https://www.facebook.com/profile.php?id=100011206217039

**Comment by tofumatt** [comment]
If you want to be friends on Facebook, check out https://www.facebook.com/mozaddons/ 😉
