### ISSUE TITLE
Have a bad link to the page with older versions of 1 click video download

### ISSUE THREAD

**Issue by wkbennion** [mozilla/addons-server#7201]
### Describe the problem and steps to reproduce it:
http://www.clickvideodownload.com/download.php

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
It's up to the developers to update their website. I can be that they changed their URL slug, disabled their listing, or deleted it. Please bring it up to them.
