### ISSUE TITLE
Cleanup temporary file setup, remove atexit hack

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7205]
Remove the atexit hack in our settings_test, move to pytest fixtures to manage temporary paths.

This will improve temporary file management, pytest's `tmpfile` fixture allows automatic cleanup for old test runs and is configurable to keep more old test runs, e.g for easier debugging.

**Comment by AlexandraMoga** [comment]
Please include some STR or the label "qa:not needed"
