### ISSUE TITLE
Don't remove original avatar (and other) images

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7208]
We are currently removing originally uploaded avatar and screenshot images which is super bad for future upgrades, e.g to support higher resolutions.

Let's not do that.

**Comment by eviljeff** [comment]
What's the avatar, exactly?

**Comment by AlexandraMoga** [comment]
Could you please add some STR to help us test this?

**Comment by eviljeff** [comment]
Upload a screenshot/preview and icon in devhub and a profile photo in account settings. For each there should be an original file accessible too (with different urls) 

Screenshots with the "full size" url of
[https://addons-dev-cdn.allizom.org/user-media/previews/__full__/128/128936.png](https://addons-dev-cdn.allizom.org/user-media/previews/full/128/128936.png)
should have an original at
[https://addons-dev-cdn.allizom.org/user-media/previews/__original__/128/128936.png](https://addons-dev-cdn.allizom.org/user-media/previews/original/128/128936.png)

icons:
normal (64x64)
[https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-__64__.png](https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-64.png)
original:
[https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-__original__.png](https://addons-dev-cdn.allizom.org/user-media/addon_icons/494/494655-original.png)

account profile photo:
normal:
[https://addons-dev-cdn.allizom.org/user-media/userpics/0/0/631.png](https://addons-dev-cdn.allizom.org/user-media/userpics/0/0/631.png)
original:
[https://addons-dev-cdn.allizom.org/user-media/userpics/0/0/631_ __original__.png](https://addons-dev-cdn.allizom.org/user-media/userpics/0/0/631_original.png) (no space)

**Comment by AlexandraMoga** [comment]
Thanks @eviljeff 
Verified on AMO-dev, FF58 (Win10x64) with all image types and checked the image URLs for each case. The images are correctly rendered.

Below is an example for an extension icon:
normal:
https://addons-dev-cdn.allizom.org/user-media/addon_icons/495/495198-64.png?modified=1519128532
original:
https://addons-dev-cdn.allizom.org/user-media/addon_icons/495/495198-original.png?modified=1519128532
