### ISSUE TITLE
Reviewer reply is logged as developer reply

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7210]
@jvillalobos replied to a developer, but it got logged as a developer reply:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-listed/flagfox (version 6.0.0).

I assume this happened because he wasn't a reviewer of that version.

Potential STR:
1. Developer X submits an add-on version.
2. Reviewer A rejects.
3. Reviewer B sends a reviewer reply.

(Reviewer B shouldn't have any previous interactions for that version.)

**Comment by wagnerand** [comment]
@jvillalobos Did you use the devhub interface, the reviewer tools interface or email to reply?

**Comment by jvillalobos** [comment]
What happened is that the dev CCd me to the email thread manually, and I just replied-all via email.

**Comment by wagnerand** [comment]
Ugh, ok. This is not a bug then. We might want to avoid doing that though. A developer reply resets the *need-info* flag, which is probably not what you want when you reply.
