### ISSUE TITLE
"Invalid assertion" error received when trying to log into AMO -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7212]
STR:

1. Access AMO homepage and click on 'Register or Log in' button (https://addons-dev.allizom.org/en-US/firefox/)
2. Enter valid credentials and hit Sign In

Expected result:
User is redirected to AMO homepage

Actual result:
The user is not logged in and an "Invalid assertion" error is displayed

Notes:
- Only happens when trying to log in to AMO-dev
- reproduced with AMO-dev, FF57 (Win10)

![image](https://user-images.githubusercontent.com/31961530/34563028-88ae490a-f159-11e7-9f95-50f416fb09a5.png)

**Comment by muffinresearch** [comment]
Bumping this to a P1 since it prevents testing on landed changes that require login.

**Comment by vladikoff** [comment]
cc @jbuck @jrgm

I believe @jbuck is fixing this right now, we will let you know when this is all done. Sorry about that

**Comment by vladikoff** [comment]
@muffinresearch @AlexandraMoga @kumar303 This should now be fixed! Sorry about that!

**Comment by jrgm** [comment]
This should be all fixed now. I have auth with https://addons-dev.allizom.org/en-US/firefox/ with oauth from stable.dev.lcip.org.

**Comment by diox** [comment]
Thanks!

**Comment by AlexandraMoga** [comment]
Login on AMO-dev is working. This can be marked as verified fixed.
