### ISSUE TITLE
Versionlist of addon which was switched off is available

### ISSUE THREAD

**Issue by gusowski1** [mozilla/addons-server#7234]
### Describe the problem and steps to reproduce it:
I watched the following link: https://addons.mozilla.org/de/firefox/addon/test-pilot/versions/
This is available and tells, that the addon is outdated.

If i want to switch to the root of the addon (or the link last version) ( https://addons.mozilla.org/de/firefox/addon/test-pilot/ ) the page tells me, that i am not authorized

### What did you expect to happen?
the first link shouldn't be visable

**Comment by jvillalobos** [comment]
Can you include a screenshot of what you see in https://addons.mozilla.org/de/firefox/addon/test-pilot/? I can see the add-on page with a notice that it's incompatible.

**Comment by gusowski1** [comment]
![addons](https://user-images.githubusercontent.com/6065608/34735844-283b4764-f571-11e7-9850-e0187db37903.jpg)

**Comment by gusowski1** [comment]
it seems to be a browser specific problem

In Firefox it works - in chrome it doesn't work

**Comment by jvillalobos** [comment]
Hmm, it also loads normally for me in Chrome. Not sure why that would happen.
