### ISSUE TITLE
'Continue' button from add-on submission page is out of context

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7235]
STR:

1. Log in to Developer Hub and select Submit a New Add-on (https://addons-dev.allizom.org/en-US/developers/addon/submit/distribution)
2. Mark as distribution option 'On this site' and click Continue
3. In the Upload Version section click on 'Select a file..." button and browse for an add-on to submit
4. Once your add-on passes validation, look for the 'Continue' button which allows you to go to the next submission step

Expected result:
'Continue" button is positioned in the Upload version section, following the add-on validator

Actual result:
'Continue' button is located beneath the 'Create a Theme' section, which makes it look a bit out of context

Notes:
- it would make more sense to have the 'Continue' button placed above the 'Create a Theme' section, since it triggers the next step in the file submission process
- the same applies to 'Sign add-on' button available for unlisted add-on submissions

![image](https://user-images.githubusercontent.com/31961530/34711101-b6f16d44-f526-11e7-9188-5a445763cb3b.png)

**Comment by jvillalobos** [comment]
Moving it above the dotted line would be inconsistent with the rest of the wizard, and having the button with a dotted line above and below would also be confusing...

I'm leaning toward hiding the "Create a Theme" section once validation passes and the Continue button is enabled. At that point I don't see a good reason the uploader would want to switch the the "Create" method. @eviljeff, what do you think?

**Comment by eviljeff** [comment]
yeah, agreed.  When testing a theme xpi submission I've sometimes pressed Create a Theme by mistake, so hiding it once you've committed yourself to a file rather than the wizard seems reasonable.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev FF57 (Win10)

![image](https://user-images.githubusercontent.com/31961530/34762211-a74f338e-f5ef-11e7-9adb-161b6894b70d.png)
