### ISSUE TITLE
Try and switch to `AND` default search operator for search queries

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7244]
Refs #7215

**Comment by AlexandraMoga** [comment]
We've mentioned our observations regarding the new search criteria in bugs affected by this change. 
I think we can mark this one as verified fixed considering that no major regressions were identified and continue the discussions on the following related bugs:
See comments from [#6837](https://github.com/mozilla/addons-server/issues/6837), [#6891](https://github.com/mozilla/addons-server/issues/6891), [#359](https://github.com/mozilla/addons/issues/359)
New issues found will be tracked separately.
