### ISSUE TITLE
License section in static theme submission form has layout issues

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7245]
Steps to reproduce:
1. Log into AMO dev and from Developer Hub submit a new static theme. (https://addons-dev.allizom.org/en-US/developers/addon/submit/distribution) 
2. On the second page of the submission process observe the text displayed in the License section.
    
Expected result:
Text is displayed without problems.

Actual result:
"y" and "g" letters are incomplete.
![incomplete g y](https://user-images.githubusercontent.com/33448286/34776426-8bce7cc0-f61f-11e7-96b8-123b6011cec4.png)

Notes:
Reproduced on AMO-dev with FF57(Win 10)

**Comment by eviljeff** [comment]
going to dupe this to https://github.com/mozilla/addons-server/issues/7071 as I already started on it.
