### ISSUE TITLE
Create Admin Tools index page and link

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7251]
Part of #7176 

I think https://addons.mozilla.org/admin/ could be reused to serve as the index for the new admin tools. Its current contents aren't useful and could be replace with a simple list of the tools that will be implemented.

Add an `Admin Tools` link to the user dropdown on AMO (under `Tools`), pointing to an index of available admin tools.

Anyone with `Addons:Edit` or `Users:Edit` should have access to this page and see the link.

**Comment by diox** [comment]
Done a while ago in https://github.com/mozilla/addons-server/issues/7848
