### ISSUE TITLE
https://addons.mozilla.org/firefox/downloads/latest/disconnect/?src=external-home-button

### ISSUE THREAD

**Issue by hakiador84** [mozilla/addons-server#7254]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by andymckay** [comment]
Is this a link for another website? There is a disconnect add-on here:

https://addons.mozilla.org/en-US/firefox/addon/disconnect/

But I'm not sure what your issue is about.
