### ISSUE TITLE
Create Homepage Content Curation tool

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7261]
Part of #7176 

This admin tool will enable users with the `Content:Curate` permission to customize the AMO homepage using a set of pre-built homepage _modules_. This tool will work similarly to the toolbar customization feature in Firefox, where there are some buttons in the toolbar, which can be rearranged, or moved in an out of a collection of unused buttons.

Each homepage module is a rectangular section that spans the entire width of the page, so only their vertical ordering can be altered.

It should be possible for the curator to make multiple changes before saving them.

/cc @devaneymoz

**Comment by jvillalobos** [comment]
Here's the list of modules currently on the homepage and their properties:
* Hero area. 
  * Currently points to 3 add-ons, which could be customizable if the metadata comes from the listing rather than the curator.
* Top collections. 
  * The list of collections to show could be configurable **if** we have graphics for all of them.
* Featured extensions. 
  * Shows random subset of featured extensions.
  * Link: https://addons.mozilla.org/search/?featured=true&type=extension
* Popular extensions.
  * Shows top extensions by usage.
  * Link: https://addons.mozilla.org/search/?sort=users&type=extension
* Top-rated themes.
  * Shows top-rated themes.
  * Link: https://addons.mozilla.org/search/?sort=rating&type=persona
* Productivity tools.
  * Shows random subset from productivity collection.
  * Link: https://addons.mozilla.org/collections/mozilla/be-more-productive/
* Privacy protection.
  * Shows random subset from privacy collection.
  * https://addons.mozilla.org/collections/mozilla/privacy-matters/
* Theme categories. 
  * The list of categories to show could be configurable **if** we have graphics for all of them.

@devaneymoz can maybe propose other modules to add to the unused set. Other collections that we frequently feature are the first that come to mind. Also top-rated extensions and popular themes.

**Comment by devaneymoz** [comment]
Please note that we hope to retire the UI you currently see in the Hero area with a new "card" design that UX has been working on. @pwalm to provide final designs. 

Also to note -- given our desire to refresh the homepage regularly (weekly), Editorial will file issues whenever we need a new module created—be they the aforementioned "cards" or new types of thematic shelves ala "Privacy protection" or "Top-rated" etc.

**Comment by devaneymoz** [comment]
Please note that we hope to retire the UI you currently see in the Hero area with a new "card" design that UX has been working on. @pwalm to provide final designs. 

Also to note -- given our desire to refresh the homepage regularly (weekly), Editorial will file issues whenever we need a new module created—be they the aforementioned "cards" or new types of thematic shelves ala "Privacy protection" or "Top-rated" etc.

**Comment by jvillalobos** [comment]
> Please note that we hope to retire the UI you currently see in the Hero area with a new "card" design that UX has been working on. @pwalm to provide final designs.

@devaneymoz What's the status of this?

**Comment by devaneymoz** [comment]
@jvillalobos The new card design was discussed some weeks back during one of our Tuesday Leadership meetings and the general consensus was the card design needs validation before implementation. 

@pwalm you had mentioned something about putting together a test on usertesting.com. Is that still in play?

**Comment by diox** [comment]
@jvillalobos does this issue still make sense with the work in https://github.com/orgs/mozilla/projects/95 ?

**Comment by jvillalobos** [comment]
It's a broader version of that work, but we don't have plans for doing this at the moment, so it's okay to close.
