### ISSUE TITLE
Add documentation on how to run UI Tests

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#7269]
As per the title, we should also add information on the config and why the settings are necessary.

**Comment by jrbenny35** [comment]
Should I add a section on adding a test? It will be kinda in-depth as we use a Page Object Model.

**Comment by muffinresearch** [comment]
> Should I add a section on adding a test? It will be kinda in-depth as we use a Page Object Model.

@jrbenny35 more info is probably better than less - so if that's possible it sounds good to me!

**Comment by AlexandraMoga** [comment]
Could you please add a "qa:not needed" label to this issue?
Thank you
