### ISSUE TITLE
Reviewer page: Merge links to identical files in the file panel into one

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7271]
Due to the way upload and compatibility worked for legacy (and is being re-used for webextensions), sometimes we duplicate the uploaded file into identical files per platform. Reviewers used to see and check each file individually on the review page, until we merged them together (if identical) in https://github.com/mozilla/addons-server/commit/421fff5ddf44ee46829a358f42d9c2abed3b6a20. That broke when we introduced signing as the file hash will be different after signing.

I didn't know about `file.original_hash` at the time (or it didn't exist), but using that now should solve this issue.

**Comment by AlexandraMoga** [comment]
@wagnerand could you please add some steps to help QA verify this issue?

**Comment by wagnerand** [comment]
STR:

1. Submit a file. For platforms, check "Mac" and "Android".
2. Go to the reviewer page for the add-on.
3. The version history should show one link to the file named "Mac /Android" (or "Android / Mac") instead of two separate links.

**Comment by AlexandraMoga** [comment]
Thanks @wagnerand 

This can be marked as verified fixed on AMO-dev, FF57 (Win10)
![image](https://user-images.githubusercontent.com/31961530/34980528-7eaa4118-faad-11e7-98c6-0321eabcc764.png)

**Comment by wagnerand** [comment]
Done, thank you!
