### ISSUE TITLE
Drop "#addons.mozilla.org_service_history" target from "Site Status" link in footer

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7275]
Steps to reproduce:
1. Log into AMO dev and click on Developer Hub
2. Go to page footer and click on "Site Status" link
3. Click the back button of your browser.
     
Expected results:
Add-on Developer Hub is reloaded.

Actual results:
Site Status page is still displayed.

Notes:
This can be reproduced on all servers with FF57(Win 10) on the old frontend where the Site status option is available in the page footer.
This issue is also reproducible on Android devices.

![site status](https://user-images.githubusercontent.com/33448286/34883794-5eabf09c-f7c3-11e7-9722-0d634802ea5a.gif)

**Comment by eviljeff** [comment]
The double back isn't really a bug with AMO - the status site is doing a redirect immediately on load to strip out our `#addons.mozilla.org_service_history` anchor target (not sure why as it can just be ignored if it's not valid).  However, we should probably stop including that in the link if it's not valid any more.

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
mentor @diox

**Comment by SeanPrashad** [comment]
Hi there, I'd love to tackle this bug if it's ok!

**Comment by diox** [comment]
Thanks, @SeanPrashad !

**Comment by ioanarusiczki** [comment]
@SeanPrashad I verified this issue on AMO dev and it is still reproducible.

**Comment by diox** [comment]
dev is experiencing deployment failures today. This issue can't be verified yet, we need ops to fix this.

**Comment by SeanPrashad** [comment]
@diox @ioanarusiczki Please let me know if there's anything I can help with! I am not sure how to deploy my updates on AMO dev - if there's any documentation to read, please let me know!

**Comment by diox** [comment]
Nothing to do on your end, it's normally completely automatic, it's just broken today because of other changes. I'll comment and close this issue when it's ready to test on dev.

**Comment by ioanarusiczki** [comment]
@diox Thanks, I re-checked this issue and it is verified fixed on AMO dev and AMO stage, FF58 (Win10, Android 8)
