### ISSUE TITLE
Theme update-check returning bogus footerURL

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#7281]
As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1428379, it looks like theme update-check is returning a bogus 403 URL. Let's remove that, so that like the rest of AMO its a blank string.

```
https://versioncheck.addons.mozilla.org/en-US/themes/update-check/886607
footerURL	"https://addons.cdn.mozilla.net/user-media/addons/886607/?1511381323"
```

**Comment by vcarciu** [comment]
Verified as fixed : 
![footerurl](https://user-images.githubusercontent.com/1583842/35682816-ae411d74-076a-11e8-8fa5-e7edfa8b94ad.png)
