### ISSUE TITLE
Implement "More Actions" section in add-on review pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7282]
Part of #7172

Add a new section to the bottom or add-on review pages (below the private whiteboard), titled "More Actions". It should include the following options:
* "Notify me about new listed versions" toggle option. 
  * This replaces the "Notify me the next time this add-on is updated" checkbox.
  * It also includes a change in how this feature behaves: instead of sending a single update for the next version, the setting should persist until it's toggled off by the reviewer. #7311
* "Clear Admin Code Review Flag" button.  (and same with "Clear Admin Content Review Flag")
  * Present if add-on is flagged for admin review and user has `Reviews:Edit` permission
  * This replaces the "Clear Admin Code Review Flag" checkbox.
* "Listing disabled" toggle option.
  * Present if the user has `Reviews:Edit` permission.
  * This is a new status flag for add-ons. It behaves like the `inactive` (developer disabled) flag, in that the listing will be hidden, but the developer can still access the devhub pages ~~and submit versions~~.

All of these actions should work inline, meaning the user should stay in the add-on review page.

**Comment by diox** [comment]
> This is a new status flag for add-ons. It behaves like the inactive (developer disabled) flag, in that the listing will be hidden, but the developer can still access the devhub pages and submit versions.

Is the developer supposed to be aware that the add-on is in this state? If so, what do we display to them? The same thing as `inactive`, except that they can't change it?

**Comment by wagnerand** [comment]
> "Clear Admin Review Flag" button. 

Let's please still call this "Clear Admin Code Review Flag" and "Clear Admin Content Review Flag" to avoid ambiguity. :)

**Comment by diox** [comment]
Going back to the actions available to developers while the add-on listing is disabled...

> It behaves like the inactive (developer disabled) flag, in that the listing will be hidden, but the developer can still access the devhub pages and submit versions.

What good does it to be able to submit new versions, if the entire listing is disabled? What status should these versions obtain after submission? I assume they can't be auto-approved...

**Comment by jvillalobos** [comment]
The listing could be disabled due to issues with its content, or the current versions. If the developer addresses the problem (which could involve uploading a new version) then the status can be reverted.

I think it would be better to still accept uploads and auto-approve them, provided that we aren't serving automatic updates to users while in that state.

**Comment by diox** [comment]
I'll dig into this more but I fear this is going to be super tricky to implement. Accepting new uploads in this state and being able to auto-approve them probably means I need to introduce a whole new status, which I'd really like to avoid, at least while we still have the old frontend and the legacy add-ons to deal with. I was hoping I would be able to just straight-up reuse the current admin disabled status instead.

**Comment by diox** [comment]
Per IRC discussion with @jvillalobos we're going to go with disabling without allowing versions uploads for now. So the inline disable action behaves like the disabling on the admin manage page.

**Comment by diox** [comment]
Also note: the `Reviews:Edit` permission has been replaced by `Reviews:Admin`. Currently nobody has this permission, so you need to be an Admin and have all permissions to get it. https://github.com/mozilla/addons-server/issues/7279 will give it to a new group.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF57 (Win10)
- 'Notify...' toggle button is present and functional (see also my comments from [7311#issuecomment](https://github.com/mozilla/addons-server/issues/7311#issuecomment-359466711)
- "Clear Admin Code Review Flag" and "Clear Admin Content Review Flag" work as expected
- "Force disable/enable add-on" button changes the status of the add-on to "Disabled by Mozilla' respectively 'Approved' (as seen in Developer Hub)

One small note: maybe the 'light orange' background visible in the buttons section could be removed.
Also, there are some other issues concerning how these changes will impact certain sections in Dev Hub, but I will track them separately.

![image](https://user-images.githubusercontent.com/31961530/35276574-79b374fa-004c-11e8-82de-5c9694d402cb.png)

**Comment by diox** [comment]
The light orange is something I added to make it clear that those actions are admins-only. If admins don't like it I can remove it, but I was concerned about separating them from regular actions, especially because of how they now work inline, I don't want people to hit the buttons by mistake.

**Comment by jvillalobos** [comment]
Good idea. For consistency, I would suggest using the red color that's used in other places of the old front end for advanced actions, like Edit and Manage buttons:

<img width="135" alt="red-button" src="https://user-images.githubusercontent.com/62568/35298125-c99e8bfe-0046-11e8-915f-d321a96cae1f.png">
