### ISSUE TITLE
Option to disable auto-approval for an add-on

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7284]
Part of #7172

In some cases admin reviewers want add-ons to be "frozen": the listing still works normally, but future listed version submissions are held for review. So, they effectively work as legacy add-ons.
* "Disable auto-approval of listed versions" toggle option in "More Actions" section (#7282), for users with `Reviews:Edit`.
* New version submission for flagged add-ons effectively work the same as for legacy add-ons: same messaging in submission flow and email, new version has an Awaiting Review status and shows up in the Legacy Updates queue (this is meant to make things easier to implement, if it's easier to create another queue, so be it).

**Comment by diox** [comment]
Implementation notes: 
- Another mission for `AddonReviewerFlags`
- To hide webextensions from the queues, we do a `qs.filter(**{'files.is_webextension': False})`. We also already join `addons_addonreviewerflags`. Need to find a way to take the new field into consideration, so that we only include non-webextensions or web-extensions with auto-approval disabled.
- There are maybe a couple places in devhub where we'd want to show the message we show for legacy, so we'd need to check for the flag there as well. Grep for `is_webextension` to find them.

**Comment by AlexandraMoga** [comment]
Verified on AMO stage with FF58 (Win10)
**Things that work:**
- using the 'Disable auto-approval' button will block auto-approval on the next listed version; Re-enabling it will remove the flag and next version will be auto-approved. The previous blocked version will be disabled.
- blocked versions are listed in 'Add-on Updates' queue

![image](https://user-images.githubusercontent.com/31961530/35622714-7f5f9f46-0691-11e8-847a-41a513f04534.png)


**Things that need to be clarified:**
- @diox when a reviewer disables auto-approval for an add-on, there is no notification sent to the developer to inform him about this action. The next version submitted will remain in "Awaiting review" status but there is no Review History available to the developer via DevHub or other channels to make it clear why his new version has not been approved yet.
![image](https://user-images.githubusercontent.com/31961530/35622730-888994f0-0691-11e8-999c-677a70386ea6.png)

**Comment by diox** [comment]
Yeah. I assumed that was the intent, and reviewers would contact developers if necessary. @jvillalobos thoughts on that point?

**Comment by jvillalobos** [comment]
During submission, the last step should tell the developer the add-on is awaiting review (like with legacy, see second bullet point in the opening comment). And yes, if a reviewer resorts to this, it means that at this point there has been some discussion with the developer, and they should be aware of what's going on.

**Comment by AlexandraMoga** [comment]
@jvillalobos 




> New version submission for flagged add-ons effectively work the same as for legacy add-ons: same messaging in submission flow **and email**

I think this part was a bit confusing. I expected this new action to trigger an email to the developer but I couldn't find anything in the fake email logs.



> During submission, the last step should tell the developer the add-on is awaiting review (like with legacy

I believe you are referring to the below step. Here I was also expecting to see a more 'direct' message but if you say that, at this point, a reviewer might have notified the developer about his add-on status, I guess this message should work well enough

 
![image](https://user-images.githubusercontent.com/31961530/35667843-c2ce850c-0737-11e8-9124-c6bf1231f1f2.png)

**Comment by diox** [comment]
> New version submission for flagged add-ons effectively work the same as for legacy add-ons: same messaging in submission flow and email

I suppose @jvillalobos was referring to the post-submission email - but that one is already fairly generic, as opposed to the message that appears in devhub (which I did change, as you noted)

**Comment by AlexandraMoga** [comment]
> I suppose @jvillalobos was referring to the post-submission email

As far as I could see in the Fake mail log. there is no email received by the developer after he submits a new version for an add-on that has 'auto-approval' disabled. I'm afraid is still not clear for me what is expected here.

**Comment by diox** [comment]
Sorry, you're right, this email is only sent for the initial add-on submission, not versions, so it doesn't matter here.

**Comment by jvillalobos** [comment]
> I believe you are referring to the below step.

Yes, that's what I'm referring to. The messaging may be subtle, but this sort of situation should be very rare and the developer should have been notified in advance.

**Comment by AlexandraMoga** [comment]
Thanks for your input.
I will mark this as verified fixed.
