### ISSUE TITLE
Searchbox and Register/login link in header of Firefox for Android mobile page don't react to taps on small devices

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#7289]
### Describe the problem and steps to reproduce it:
Firefox for Android 57.0.4 and latest 59 nightly on Sony Xperia Z3 Compact with Android 6.0.1

1. Go to https://addons.mozilla.org/en-US/android/ on the Android device.
2. Tap onto the search field in the top left to type something or tap the link in the top right to register or log in (both in portrait mode without zooming).

### What happened?
Nothing.

### What did you expect to happen?
Search field activated and keyboard shown or page to log in or register opened.

### Anything else we should know?
If I zoom in and keep the right side visible until "Extensions" from the header "Extensions, Themes, More" is not visible anymore, then the taps will trigger the desired action.

**Comment by ioanarusiczki** [comment]
I verified this issue on Nexus5 with Android 6.0.1, ff57 and ff59, but I could not reproduce it. 
Also it was verified on Android 7.0 and Android 8.0.1.

Video attached

![videotogif_2018 01 15_11 30 10](https://user-images.githubusercontent.com/33448286/34936662-f0bd801c-f9ea-11e7-9dc2-ae2823c619db.gif)

**Comment by diox** [comment]
Hi,

I can't reproduce either on the exact same configuration (Sony Z3C, Android 6.0.1, Firefox for Android 57)

Please make sure you don't have any custom apps or add-ons that would cause this. Also, this is the wrong repos to file frontend bugs against, the right one would be https://github.com/mozilla/addons-frontend/
