### ISSUE TITLE
Pass additional params to TAAR

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7296]
TAAR is starting to use some new query string parameters in the disco pane so we should pass through `study` and `branch` as well as the clientId to TAAR when received on the API endpoint.

To make this easier in the future I'm wondering if we should just add a list for params that are OK to pass through, that way we just need to add to the list to send additional parameters.

See https://github.com/mozilla/addons-frontend/issues/4155 for the associated frontend patch.

**Comment by AlexandraMoga** [comment]
Could you please include some steps to help us verify these changes?

**Comment by muffinresearch** [comment]
I added some QA notes here: https://github.com/mozilla/addons-frontend/issues/4155#issuecomment-358259534

We'll need to check with the TAAR team they are seeing the expected parameters later today.

**Comment by AlexandraMoga** [comment]
I've followed the QA steps from [#4155](https://github.com/mozilla/addons-frontend/issues/4155#issuecomment-358259534) and I could't find any issues around dico pane functionality.

@muffinresearch Any news from TAAR?

**Comment by muffinresearch** [comment]
> I've followed the QA steps from #4155 and I could't find any issues around dico pane functionality.
@muffinresearch Any news from TAAR?

@AlexandraMoga No news as yet. As long as nothing is breaking I think this is good to go, if there's any issues with the integration we can make changes later.
