### ISSUE TITLE
Developer Hub logo is displayed with layout issues when the back button of the browser is clicked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7301]
Prerequisites:
User is logged in

Steps to reproduce:
1. Load AMO page and click on Developer Hub
2. Click on My Add-ons
3. Return to the Developer Hub page by clicking the logo
4. Click on the back button of the browser

Expected result:
The Logo is correctly displayed. 

Actual result:
Two white rectangles are displayed on the logo.

Notes:
Reproduced on all AMO servers with FF57(Win 10).
Please note that after the first click of the mouse the rectangles are no longer there.

![developer hub logo3](https://user-images.githubusercontent.com/33448286/34952204-a5944c6a-fa21-11e7-848d-caca63b56487.gif)

**Comment by eviljeff** [comment]
It's just Firefox's UI for indicating selected links - you always get it when you click on a link and go back to that page (you'll see it on other links too).  It just looks a little strange on this page because we have unusual styling on the link to have the "Add-on" positioned lower, overlapping "Developer Hub".

**Comment by wagnerand** [comment]
Mentor: me

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

To fix this issue, you would want to add `outline:none` to the header links.

**Comment by SeanPrashad** [comment]
Hi there, I'd like to help out with this bug if it's still available!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev using FF58 (Win10). I also tested with some similar scenarios and I could no longer reproduce this issue. 

![dreptunghiuri](https://user-images.githubusercontent.com/33448286/36098563-0b35395c-1008-11e8-9611-dd1b361972bf.gif)
