### ISSUE TITLE
Comments in Collections are not displayed

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#7307]
### Describe the problem and steps to reproduce it:
Visit https://addons.mozilla.org/en-US/firefox/collections/DavidHedlund/webextensions/

### What happened?
I don't see the comments that I've added for the add-ons.

### What did you expect to happen?
I have commented some add-ons, for example Privacy Badger with:
> Prevents canvas based fingerprinting, (like CanvasBlocker) supercookies (like Click&Clean), and unique cookies that contain tracking IDs.

**Comment by eviljeff** [comment]
dupe of mozilla/addons-frontend#3890 (and others)
