### ISSUE TITLE
The new layout for the license section in static theme submission introduced an empty space in the left margin 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7308]
STR:

1. Log into DevHub and submit a new static theme
2. Once your file passes validation, click Continue to proceed to the theme description form
3. Observe the layout of the license section in the theme description form

Expected result:
The license option section has the same alignment as the rest of the elements in the form

Actual result;
The license option section has an empty space in the left margin

Notes: 
- reprodced on AMO-dev, FF57, Win 10
- First reported in [#7071](https://github.com/mozilla/addons-server/issues/7071)
![image](https://user-images.githubusercontent.com/31961530/34981361-fa777e9e-faaf-11e7-989b-461be2e7eb80.png)

**Comment by eviljeff** [comment]
from @jvillalobos:
How about this:
* Drop the margins.
* Drop the tooltips, except for "Yes, as long as they share alike". That's the item that is hardest to understand and presumably is not affected by the cropping issue.
* Add a new line to the box that says "Your add-on will be released...". The new line should have this link: [More information on Creative Commons licenses](https://creativecommons.org/licenses/).

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF57 (Win10)


![image](https://user-images.githubusercontent.com/31961530/35224284-26718e40-ff8d-11e7-9b01-0636b65d5266.png)
