### ISSUE TITLE
Cannot preview addon source before installing

### ISSUE THREAD

**Issue by F-3000** [mozilla/addons-server#7310]
### Describe the problem and steps to reproduce it:
As a normal logged-in user one cannot view an addon source before installing it.

### What happened?
I found no way to download the source without installing the addon!

### What did you expect to happen?
I was expecting there to be a link to separately download the addon for possibility to inspect it before installing.

### Anything else we should know?
As an example:
https://addons.mozilla.org/en-US/firefox/addon/wealias/
![wealiasaddonpage](https://user-images.githubusercontent.com/33088171/34989555-a7aded6c-facb-11e7-90e2-5e6476976bb4.png)

**Comment by diox** [comment]
Hi,

You can right click the install button and select "Save Link As" to download the source
