### ISSUE TITLE
Make new version notification for reviewers persist and ignore unlisted versions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7311]
Spun off from https://github.com/mozilla/addons-server/issues/7282

Rename "Notify me the next time this add-on is updated" to "Notify me about new listed versions" in reviewer tools. Change how this feature behaves: instead of sending a single update for the next version, the setting should persist until it's toggled off by the reviewer.

**Comment by AlexandraMoga** [comment]
I have tried to test this but it appears that the 'Notify me...' toggle button is not functional:

![noyify-toggle](https://user-images.githubusercontent.com/31961530/35227397-af0dda2a-ff96-11e7-9ab4-a7bc78129ff0.gif)

**Comment by diox** [comment]
mmm yeah, it looks like the token is empty for some reason. I wonder if this is because of the special reviewers domain...

**Comment by diox** [comment]
I pushed a fix, it should be deployed on dev shortly.

**Comment by diox** [comment]
Note: you'll need to log out and back in to test this.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF57 (Win10)
- toggle button is functional
- reviewer is notified when a new listed version has been uploaded
- reviewer will not receive further notifications if he disables the 'Notify me...' option

Example of email received:
![image](https://user-images.githubusercontent.com/31961530/35266718-c5abe33a-002c-11e8-8731-0165dff2f53d.png)

@diox one question: wasn't the notification option supposed to work for beta versions as well? To my understanding, only unlisted versions (self) were to be ignored.

**Comment by jvillalobos** [comment]
Beta versions aren't being reviewed and will go away soon, so ignoring them is the right way to go (admittedly I forgot to account for them).

**Comment by AlexandraMoga** [comment]
I'm marking this as verified fixed, based on the above comment.
