### ISSUE TITLE
Detect devtools_page manifest property and display as webext permission

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7316]
Follow on from #7265 

Firefox now treats an extra manifest key, `devtools_page` https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/devtools_page, as a permission, and displays in the popup on install.  It's not in the permission section of the manifest but should be treated as such.

**Comment by bobsilverberg** [comment]
@eviljeff This will definitely help with https://github.com/mozilla/addons-frontend/issues/2757, or whatever follow-up is filed for it. Will the new code just add an extra string to the array of permissions already returned by the API?

**Comment by eviljeff** [comment]
I think so, yes, but I've not thought about it since I logged the issue after I discovered _why_ the list in Firefox didn't match AMO.  No-one from the Firefox side asked us to support this extra manifest property - I'm not sure why it wasn't added in the permissions block of the manifest either.

**Comment by bobsilverberg** [comment]
I believe the reason it works the way it does is because of how Chrome implements it, and we needed to maintain compatibility, so I doubt it will ever appear as an actual permission string in the manifest. As far as https://github.com/mozilla/addons-frontend/issues/2757#issuecomment-372694056 goes, as long as the permission appears in the array of permissions returned by the API, and its name is `devtools`, then once that change lands it should "just work" on the front-end.

**Comment by shashwatsingh** [comment]
Would this be a good first bug? Is it okay if I pick this one?

**Comment by eviljeff** [comment]
> Would this be a good first bug? 

well, no. It's a contrib:welcome bug - they're more challenging and require some experience with python/django.  Plus we don't do all the investigation for you to identify what code to change - that's for you to do as part of resolving the issue.

> Is it okay if I pick this one?

Sure, go ahead.   Once you think you've understood the problem and how to fix it, let us know so we can confirm you're on the right path.

**Comment by shashwatsingh** [comment]
I will give this a try, but have to setup the application locally for debugging. Will keep updating here if I have any questions.

**Comment by shashwatsingh** [comment]
It took some time, but here is my understanding of the process:

I could find two ways to update an WebextPermission:
1. POST to addon/submit/upload-... 
    - handled by `olympia\devhub\views.submit_addon_upload`
2. `olympia.devhub.tasks.create_version_for_upload`
    - (not sure how control reaches here...)

Both of these get permissions from `olympia\files\utils.parse_addon` method, which in turn, uses `olympia.files.utils.ManifestJSONExtractor.parse` method.

Would it be appropriate send `devtools_page` as an item in the `permissions` array of the object returned by `ManifestJSONExtractor.parse` method?

That way, it would eventually be saved in the webext_permissions table and be sent as part of "permissions" to the addons-frontend.

**Comment by eviljeff** [comment]
> Would it be appropriate send `devtools_page` as an item in the `permissions` array of the object returned by `ManifestJSONExtractor.parse` method?

it would work, but I think it'll end up confusing later to mix up the logic of parsing the manifest with interpreting the permissions.  

So you should add something in `ManifestJSONExtractor.parse` to store the `devtools_page` property in `data` first.  Then in `File.from_upload` where the permissions are handled (after `permissions = list(parsed_data.get('permissions', []))`) then something like `if 'devtools_page' in parsed_data:\n permissions.append('devtools')`.

There should be tests added for the parsing in `ManifestJSONExtractor` and in `from_upload`.  Please open a draft pull request when you have something working for you locally and we can discuss the code implementation further there.  Thanks!

**Comment by shashwatsingh** [comment]
When I tried to test uploading an addon locally, I get repeated errors in 
`docker-compose logs --tail=1 -f` with the same message:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```
![image](https://user-images.githubusercontent.com/676751/79893904-386abe80-83f4-11ea-819f-dfd98d8a6951.png)

And the browser is stuck at 
![image](https://user-images.githubusercontent.com/676751/79893839-225cfe00-83f4-11ea-8e98-e7b5fd290ad1.png)

Thinking it is due to my changes, I switched to master (currently pointing to `a1c10fa5cd`)
and still the same issue.

What's interesting is this:
```
addons-frontend_1  | [2] [1587489255733] DEBUG (amo.proxy/88 on ee1877a4892a): 404 ~> http://0.0.0.0:3333/en-US/developers/upload/cf8f8f79a4a947f9bfd3464606c5b8d9/json?_=1587489163320
```
Could you let me know where else to look?

**Comment by eviljeff** [comment]
The `addons-frontend` errors/logging aren't relevant for developer hub - it's just passing through the request.  All the relevant logs would be under `addons-web` or `addons-worker` or in the `logs/uwsgi-master.log` file.  Anyway, debugging via github issues isn't really practical - you're best asking us on matrix https://chat.mozilla.org/#/room/#amo:mozilla.org

**Comment by shashwatsingh** [comment]
I got latest source code from addons-server repository and that worked without any extra changes. The changes seem to work fine and I see this extra line. Please let me know if I can move the PR from draft.

![image](https://user-images.githubusercontent.com/676751/80066883-5f2c1080-852c-11ea-9089-890624f13528.png)

**Comment by shashwatsingh** [comment]
Is this change okay?

**Comment by eviljeff** [comment]
if you're happy with your changes and tests pass, then change it from a draft pull review and someone will review it.
