### ISSUE TITLE
Wrong Android message: "Works with Firefox for Android. Download Anyway"

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#7317]
### Describe the problem and steps to reproduce it:
Open for example https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/ in Android. See version 3.17 for example.

### What happened?
I see this message

> Works with Firefox for Android
> Download Anyway

### What did you expect to happen?

> Doesn't work with Firefox for Android.
> Download Anyway

Firefox says

> This add-on is not compatible with your version of Firefox.
> Download Anyway

So this message can also be used for Android, but it will take a lot of space on the mobile device screen:

> This add-on is not compatible with your version of Firefox for Android.
> Download Anyway

**Comment by jvillalobos** [comment]
This page is being rewritten in https://github.com/mozilla/addons-frontend/issues/2770, so this should be considered on that issue. This looks like an edge case related to Firefox 57 compatibility.
