### ISSUE TITLE
Please add link to Version History (beta) in Version History and vice versa

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#7318]
Greasemonkey is only used as an example, this issue covers all add-ons.

### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/ lists:
* See all versions
* See all beta versions

I visited https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/ but could not find a link to beta releases there.

### What did you expect to happen?
* Can you please add the link "See all beta versions" https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta in https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/ and vice versa:
* Can you please add the link "See all stable versions" https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/ in https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
See my reply in https://github.com/mozilla/addons-server/issues/7319#issuecomment-358110107 ; beta versions are being removed, there is therefore no point in implementing this.
