### ISSUE TITLE
Change "See all versions" to "See all stable versions"

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#7319]
Greasemonkey is only used as an example, this issue covers all add-ons.

### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/ lists:
* See all versions
* See all beta versions

### What did you expect to happen?
I expected the text:
* See all **stable** versions
* See all beta versions

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Hi,

Future frontend issues should be logged over mozilla/addons-frontend, not here, as we're moving away from addons-server for well, frontend things.

It turns out that we're going to remove beta versions soon, in #7163, so this suggestion won't be implemented.

**Comment by davidhedlund** [comment]
@diox Thanks.
