### ISSUE TITLE
Expose CompatOverrides via API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7322]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402064#c16 highlighted this functionality is provided (but not documented) in the v1.5 API and is still needed by Firefox Addon Manager so we need to expose it in the v3 API too.

**Comment by AlexandraMoga** [comment]
Please include some STR or the label 'qa:not needed'

**Comment by eviljeff** [comment]
You can do a basic check the API is working by adding a Compat Override via `/admin/models/addons/compatoverride/add/` with the guid `foo@baa` (fill in as much of the remaining boxes as you want) and seeing it show up in `/api/v3/addons/compat-override/?guid=foo@baa`.  If you add multiple CompatOverrides you will be able to search for multiple matches with `/?guid=foo@baa,foo2@baa,foo3@baa` etc.

An end to end test (with full impact of the values in disabling add-ons) can only be done in Firefox itself after the required work is done there.  I believe aswan was waiting for the API to be finished before he finished the patches.

**Comment by AlexandraMoga** [comment]
Following the above steps, I've added new compat-overrides via Admin tools with guids `ice@cold, ice2@cold, ice3@cold` and performed the following request: https://addons-dev.allizom.org//api/v3/addons/compat-override/?guid=ice@cold,ice2@cold,ice3@cold
The api returns results and there were no errors detected

Based on this result, I will mark this case as verified fixed.
