### ISSUE TITLE
make static theme preview changes from Austin meeting

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7323]
From my recollection:
* [x] Change preview size to match existing persona preview size (680x100)
* [x] drop menu items, toolbar text, other text, from the preview, just show abstract iconography
* [x] allow opacity to be specified for all colours
* [x] Show the background image as close as possible to how it would look on an actual toolbar (instead of trying to show the full background image).

@jvillalobos anything else you remember?

follow-up from #6860

**Comment by jvillalobos** [comment]
- [ ] Show the background image as close as possible to how it would look on an actual toolbar (instead of trying to show the full background image).

**Comment by ioanarusiczki** [comment]
@eviljeff  I've noticed that for the Browser Preview after I selected a picture (I used a white sample in the example below) the colors for the Header Are Background don't change. 
After submitting and installing the theme the changes were visible. 
I tested this issue on AMO dev (Win10).

![testalb3](https://user-images.githubusercontent.com/33448286/35286330-67df1d30-0068-11e8-8f8b-007777f6d741.gif)

**Comment by eviljeff** [comment]
How big was the white image?  Header area background is used _behind_ the header image, so you'd only see if it the image was less than 680 x 100, or had transparency.

**Comment by ioanarusiczki** [comment]
@eviljeff I used a .png file, dimensions 377x133. Went to "Select colors for your theme" section and for the Header area background I selected something around these properties rgba(204, 49, 49, 1).  I did not change anything else. 

Here's how the theme looks like after installing it. 

![headerarea](https://user-images.githubusercontent.com/33448286/35380388-c58868b0-01c1-11e8-864c-cfe079a6c450.gif)

The Browser Preview did not show what I selected when I submitted the theme.

![themepreview](https://user-images.githubusercontent.com/33448286/35380755-d83583de-01c2-11e8-8705-604f159d60d1.gif)

**Comment by eviljeff** [comment]
@ioanarusiczki thanks... from investigating this I've found a quite serious flaw that got introduced at some point - the header image preview is only accurate with a persona-sized image (200px high, and at least 680px wide, anyway).  I'm pretty sure it wasn't this patch, but and earlier pull request where I thought I could safely strip out a lot of javascript.  Filed #7418

**Comment by ioanarusiczki** [comment]
@eviljeff I also filed #7405 which is a Theme Preview layout issue that I observed while testing. If the issue above is filed in #7418 I will mark this as verified fixed.
