### ISSUE TITLE
Link from DevHub homepage to Add-on reviews page does not work as expected

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7324]
Prerequisites: Developer account with recent add-ons submitted and rated

STR

1. Log into Developer Hub and scroll down to 'My Add-ons' section
2. Pick an add-on that has some reviews and click on the link present next to the rating stars

Expected result;
The link should redirect to the add-on reviews page (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/code_count/reviews/)

Actual result:
The link redirects to the add-on details page instead and has the following structure -  https://addons-dev.allizom.org/en-US/firefox/addon/code_count/#reviews

Reproduced on AMO-dev and stage with FF57 (Win10)

![dev_rev](https://user-images.githubusercontent.com/31961530/35050994-dfc5684c-fbac-11e7-8849-dcac36db2727.gif)

**Comment by diox** [comment]
Pretty sure this is a duplicate bug - maybe the frontend should handle that URL though, instead of changing the devhub link.

**Comment by eviljeff** [comment]
yeah, that's the legacy frontend style ratings link and new frontend changed it.   Anywhere on AMO that uses the `impala_reviews_link` or `reviews_link` jinja helpers (or the underlying templates) will link to the `#` style link by default.

**Comment by eviljeff** [comment]
dupe of #7111 - which has an open PR
