### ISSUE TITLE
[FF ESR] - Closing mark from the "new site" banner is missing

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7326]
Re-filing from https://github.com/mozilla/addons-frontend/issues/4069

Steps to reproduce:
1. Load old AMO homepage i.e. https://addons-dev.allizom.org/en-US/firefox/
2. Observe the closing option from the new site banner

Expected results:
There are no display or layout issues.

Actual results:
The "x" mark is not displayed.

Notes/Issues:
Verified on AMO-dev FF52.5.2 using Win 7.
Please see screenshot:
![esr](https://user-images.githubusercontent.com/15685960/33827151-f8e0b656-de6f-11e7-8f69-ea6d9cadfd20.png)

**Comment by eviljeff** [comment]
We show the new frontend by default so is this valid any more?

**Comment by muffinresearch** [comment]
It's still being shown on the old site if you visit it.

**Comment by muffinresearch** [comment]
FWIW: The problem is due to no SVG mask support in FFESR.

**Comment by diox** [comment]
Maybe we should remove the banner entirely on the old site? If you're on it, it's because you chose to, right?

**Comment by eviljeff** [comment]
wontfix this?  ESR users choosing to visit the old site is an edge case, surely.

**Comment by muffinresearch** [comment]
> Maybe we should remove the banner entirely on the old site? If you're on it, it's because you chose to, right?

I've turned it off on prod.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-prod, FF ESR (Win10)
The banner is no longer diplayed

![image](https://user-images.githubusercontent.com/31961530/35573905-08d251a8-05e1-11e8-8b4f-0897cdd87d58.png)
