### ISSUE TITLE
The Deleted table header and content rows do not match in width

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7337]
Prerequisites:
Deleted themes

Steps to reproduce:

1.Load AMO Reviewer Tools page
2.Go to Lightweight Themes queue and select the Deleted Themes Log from the available options
     
Expected result:
The header of the table and it's content are correctly displayed.

Actual result:
The content is not alligned with the header.

Notes:
This issue is also noticeable in the Review tab.
Reproduced on both AMOdev and stage with FF57(Win 10).

![deleted themes logs](https://user-images.githubusercontent.com/33448286/35092338-ba6b3b6c-fc47-11e7-9126-fa0380b64ca4.png)

**Comment by eviljeff** [comment]
static themes now use the standard addon log, so the theme log is deprecated (and will be removed at some point, I suppose)
