### ISSUE TITLE
Toggle button of the extension is not displayed correctly on resize

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-server#7342]
### Describe the problem and steps to reproduce it:
1.Open Firefox.
2.Go to about:addons web page.
3.Resize the web page.
4.Observe the toggle button of the extension.

### What happened?
The toggle button of the extension is displayed on the left side after resize.

### What did you expect to happen?
The toggle button of the extension is displayed on the right side after resize.

### Anything else we should know?
Reproduced on AMO-dev, stage and prod with FF59 and FF57 (Win7 64-bit and Mac OS X 10.13)
![resize](https://user-images.githubusercontent.com/15885467/35144776-44234f22-fd0e-11e7-9efc-287984491cc7.gif)

**Comment by muffinresearch** [comment]
@cosminbadescuSV hi - anything related to the disco pane UI should be filed in mozilla/addons-frontend since that's the project that contains the code to fix this.

**Comment by muffinresearch** [comment]
Moved to https://github.com/mozilla/addons-frontend/issues/4190
