### ISSUE TITLE
Email notifications are being sent to non-admin reviewers after a listed->unlisted switch

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#7344]
### Describe the problem and steps to reproduce it:
I've received an email saying that version number 1.0.4 of  [https://addons.mozilla.org/reviewers/review/860555](https://addons.mozilla.org/reviewers/review/860555) is ready for review. 

This email was sent because the option 

> Notify me the next time this add-on is updated. Subsequent updates will not generate an email

 was selected when I've reviewed 1.0.3.

### What happened?
The developer after version 1.0.3 switched the extension from listed to unlisted. As such, version 1.0.4 is not visible for me (non-admin reviewer).

### What did you expect to happen?
Subsequent extension uploads after a listed->unlisted switch should not send emails to non-admin reviewers.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/7311 will fix it by only notifying about listed versions. There is a PR approved but I want to land something else with it.
