### ISSUE TITLE
The filter buttons from Deleted Themes Log are too narrow

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7345]
Steps to reproduce:

1. Load AMO Reviewer Tools page
2. Go to Deleted Themes Log from the Lightweight Themes queue.
3. Observe the filter button from Reviews and Deleted tabs. 
     
Expected result:
The filter buttons look good.

Actual result:
The filter buttons are too narrow. Text is crammed.

Notes:
Reproduced on both AMO dev and stage with FF57(Win 10).
![filter button](https://user-images.githubusercontent.com/33448286/35155922-de7f93b8-fd37-11e7-9f19-da1552421c68.png)

**Comment by eviljeff** [comment]
static themes now use the standard addon log, so the theme log is deprecated (and will be removed at some point, I suppose)
