### ISSUE TITLE
managing firefox esr

### ISSUE THREAD

**Issue by Ulf3000** [mozilla/addons-server#7351]
### Describe the problem and steps to reproduce it:

ive ported 2 of my addons to webext 
so when i go to amo they are shown correctly i can install them with firefox 57+ no problem.

But when i go there with firefox esr or waterfox56 or any older version of firefox , it shows that its not compatible . that sucks

### What did you expect to happen?

I expect for users older firefox to show the last sdk addon version for their browser which is still there

**Comment by diox** [comment]
Hi,

We looked into this a few months ago and decided it was too costly for us to implement. See the long discussion in https://github.com/mozilla/addons-server/issues/5482 for more information.
