### ISSUE TITLE
New Mozilla collection: Webextension Replacements

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#7353]
I'll be very happy if you publish this collection as "Webextension Replacements (by Mozilla)" on the [main page](https://addons.mozilla.org/en-US/firefox/) or just at [Mozilla collections](https://addons.mozilla.org/en-US/firefox/collections/mozilla/).

* Bookmarks Organizer - Comment: Replaces: Bookmarks LinkChecker
* Cookie Autodelete -- Comment: Replaces: Self-Destructing Cookies
* Country Flags & IP Whois -- Comment: Replaces: WorldIP
* Empty Cache Button -- Comment: Replaces: Clear Cache Button
* Gesturefy -- Comment: Replaces: All-in-One Gestures, FireGestures
* HTTP/2 Indicator -- Comment: Replaces: HTTP/2 and SPDY indicator
* New Tab Override (WebExtension) -- Comment: Replaces: NewTabURL
* Tab Session Manager -- Comment: Replaces: Session Manager
* WX Download Status Bar -- Comment: Replaces: Download Status Bar

I post here rather than create a collection with [invisible comments](https://github.com/mozilla/addons-frontend/issues/3890).

**Comment by davidhedlund** [comment]
@diox What do you think?

**Comment by eviljeff** [comment]
@devaneymoz manages a number of replacements for legacy add-ons via this discourse thread https://discourse.mozilla.org/t/favorite-webextensions/17087

**Comment by davidhedlund** [comment]
@eviljeff I started my own collection about this at https://addons.mozilla.org/en-US/firefox/collections/DavidHedlund/
