### ISSUE TITLE
Invalidate old sessions when soft-deleting a user account

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7361]
Originally reported in one of the comments of https://bugzilla.mozilla.org/show_bug.cgi?id=1428047 (which is an invalid security bug).

The problem is simple: it's still possible to access your (now anonymized) user account after it has been soft-deleted, if you keep your cookies. Let's prevent that.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF57 (Win10)
1. after the user confirms the deletion process, he receives a 'not authorized' error (see screenshot);
2. user is still able to log into AMO (anonymized account) with the same email/password. Isn't this what needed to be prevented?

![image](https://user-images.githubusercontent.com/31961530/35279262-38a8e27a-0055-11e8-8146-4f4f3f078b58.png)

**Comment by diox** [comment]
2. No, that's a different thing, though it's the same FxA account, it's a different (new) AMO account. What I prevented here is accessing the same old deleted AMO account by keeping a session cookie.

**Comment by vcarciu** [comment]
@diox : So if the deleted account had some collections for example and the new account will not have these collections , it means that we correctly verified the issue? Or should we use some cookie managers to verify this issue?

**Comment by diox** [comment]
@vcarciu using a cookie manager is the most accurate test, yeah. It's cumbersome, but anything else won't be testing exactly what I changed here. You should not go through the login page at all to test, but instead, use these STR:
- Log in
- Using a cookie manager, save the `sessionid` and `api_auth_token` cookies 
- Delete the account
- Re-install the saved cookies, and load devhub and the homepage. Both pages should consider you logged out.

**Comment by vcarciu** [comment]
@diox  : I used a cookie manager for this testing and results were good according your STRs . Also, I can confirm that no info from older account is present if logging in again with the same account. 

Marking issue as verified.
