### ISSUE TITLE
Extra ElasticSearch queries are being made when a search returns no results

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7364]
Spotted by @EnTeQuAk : on the legacy frontend, when a search query is made, it does several ES queries instead of a single one (easily visible by adding a breakpoint in a legacy frontend search test returning no results and looking at the `z.es` logger ouput). That's pretty awful for performance.

This is because of those 2 lines:
https://github.com/mozilla/addons-server/blob/507a9c705f268be798601e07f73316de603e6b99/src/olympia/amo/search.py#L88
https://github.com/mozilla/addons-server/blob/507a9c705f268be798601e07f73316de603e6b99/src/olympia/amo/search.py#L226

`_results_cache` is initialized to `None`, but when it's set to the list of results, it can evaluate to `False` if there are no results, causing the queries to be re-evaluated.

Fortunately the problem is contained to search queries returning no results on the legacy frontend. Nevertheless, we should fix it and make sure it does not happen again (double-checking the API while we're at it - writing tests for this)

**Comment by diox** [comment]
QA: you won't be able to check that extra queries are being made, but do check that searching on the legacy site still works, including pagination and looking at pages with no results.

**Comment by vcarciu** [comment]
Verified if search(w/o results), pagination, filters and sorting are still working on legacy site and everything is working as expected.
