### ISSUE TITLE
Update template for "More Information Requested" email to developers 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7366]
Part of issue #7352.  This issue is to update the template for the "more information requested" email from reviewers to developers. 

[Here's](https://github.com/mozilla/addons-server/blob/master/src/olympia/activity/templates/activity/emails/from_reviewer.txt) the current template. 

Below is the updated template. We might need to double check that the fields map correctly to the AMO database. 
_____________________________________________

Subject: Mozilla Add-ons: Action Required for {{ add-on name }} {{ version }} 

Hello, 

{{ Reviewer }}, a reviewer at addons.mozilla.org, found an issue when reviewing version {{ version }} of the extension {{ extension name }} and requests additional information. You are receiving this email because you are listed as an author of this add-on.  

********* [8 stars]
{{ Reviewer }} wrote: 

{{ comments }} 

******* [8 stars]

To respond, please reply to this email or visit {{ dev versions URL }}. If we do not hear from you within seven (7) days of this notification, this listing may be removed from addons.mozilla.org. 

Thank you for your attention. 

-- [two -]
Mozilla Add-ons
https://addons.mozilla.org

**Comment by jvillalobos** [comment]
Note that #7283 is intended to set a deadline for info requests, which can be edited by admins. I don't mind "7 days" being hardcoded for now, but it should take into account that it will become a variable.

**Comment by jvillalobos** [comment]
Another note: how about removing "from the developer"? The next line mentions "authors" which is at the same time redundant and slightly confusing.

**Comment by caitmuenster** [comment]
Oh, if we know what the variable field is called, can we just pop that into the response now? I'm fine with waiting, but if we're worried about this getting overlooked in the future I'm also fine with putting it in now. 

Also, yes, we can delete "from the developer." I'll edit the text now.

**Comment by diox** [comment]
@caitmuenster / @jvillalobos : this template is used any time the reviewer adds a comment in the "thread", so they are not necessarily requesting information, right? With that in mind, do you still want to make those changes? @eviljeff and I were thinking that was the reason behind the currently vague template.

**Comment by jvillalobos** [comment]
Good point. I'm thinking the "If we do not hear from you" bit should be removed when the need info flag isn't added.  The rest may be a bit more alarming than needed in some cases, but we want devs to actually read what we send them, so I'm okay with leaving that in.

**Comment by caitmuenster** [comment]
Totally agree -- thanks for the catch, @diox!

**Comment by diox** [comment]
I also realized something... the whole activity emails code assumes reviewers have `Addons:Review` permission for listed add-ons - if they don't, it prevents them from doing actions by email reply and- does not copy them to any emails being sent. I'm assuming that's a problem? A new issue should be filed for this if it is.

**Comment by jvillalobos** [comment]
Filed #7441 for that.

**Comment by AlexandraMoga** [comment]
I've tested with the Reviewer reply action -  with and without more info request flag -  with a user included in the `Addons:Review` group and the new template is being sent. I believe this action can be tested again with other user permissions once [#7441](https://github.com/mozilla/addons-server/issues/7441) will land.
@diox there are two small changes that need to be added in the template (see first screenshot for details)

![image](https://user-images.githubusercontent.com/31961530/35812542-f3c9ae06-0a99-11e8-972a-82a9f8eb74fd.png)

-------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/31961530/35812606-266ed390-0a9a-11e8-899b-31b70a4d12db.png)

**Comment by diox** [comment]
I changed *extension* to *add-on* on purpose since it's not necessarily an extension that is being reviewed. Agreed on the version number being missing though, I'll fix that.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO-dev, FF58 (Win10)

![image](https://user-images.githubusercontent.com/31961530/35859701-c1facdbe-0b49-11e8-8757-63667acbdaa6.png)
