### ISSUE TITLE
Updated Canned Response for "Incomplete Description" 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7367]
Part of issue #7352. This is to update the canned response text for "Incomplete Description." Updated text below: 

Please include more information in your add-on listing. At minimum, the add-on’s summary should clearly explain what the add-on does and how it can be used, so that even people without knowledge about your add-on and its services can understand. If you run out of characters in the summary field, you can include more information in the description  field and/or include screenshots. 

For more tips on how to create an appealing listing, please visit https://developer.mozilla.org/Add-ons/Listing.

**Comment by jvillalobos** [comment]
Done.

**Comment by AlexandraMoga** [comment]
Are these changes visible only on AMO-prod?
We had a similar situation with [#494](https://github.com/mozilla/addons/issues/494) when we reported that for -dev and stage we can't see any canned responses.
Does the same apply here? 

![image](https://user-images.githubusercontent.com/31961530/35283320-9b10df34-0060-11e8-984a-f9494002d8a6.png)
