### ISSUE TITLE
API provides & as &amp; in collection description

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7368]
Looks like there's an escaping issue on the collections page [1] , the api appears to provide it with an encoded ampersand [2].

<img width="540" alt="dynamic_media_downloaders_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35239866-9247b9de-ffa9-11e7-8ce1-1efec748cf97.png">
 
[1] https://addons.allizom.org/en-US/firefox/collections/mozilla/dynamic-media-downloaders/
[2] https://addons.allizom.org/api/v3/accounts/account/mozilla/collections/dynamic-media-downloaders/

**Comment by eviljeff** [comment]
Hmm.  We don't do anything special with `description` before serializing it.  Is this the only place the API is returning `&` pre-encoded for inclusion in html?

**Comment by muffinresearch** [comment]
@eviljeff if this happens elsewhere it's probably a bug too, I wouldn't expect the API to have assumed  anything about the context of usage in general (albeit there are cases where the API does supply HTML, but I don't think this is one of them).

**Comment by muffinresearch** [comment]
Closing in favour of https://github.com/mozilla/addons-frontend/issues/4213
