### ISSUE TITLE
Update Email Template for Add-on Rejections

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7369]
Part of issue #7352. This issue is to update the email template that notifies developers when their add-on is rejected.  The current template is [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/reject_multiple_versions.ltxt). Updates are below. 
________

Subject: Mozilla Add-ons: {{ Add-on Name }} {{ Add-on version }} Has Been Disabled

[_If one version has been disabled, use this_:] 
Version {{ version disabled # }} of your add-on {add-on name} has been disabled on addons.mozilla.org due to issues discovered during the review process. Please see the reviewer’s comments below for more information about why your add-on was disabled. 

If your add-on has other enabled versions (such as a previous version), it will continue to appear in the gallery and work for users.]

[_if multiple versions have been rejected, use this:_]
This email is to notify you that your add-on {add-on name} has been de-listed from addons.mozilla.org by a member of the add-on reviewer team. Your add-on will no longer appear in the gallery. 

Please see the reviewer’s comments below for more information about why your add-on was de-listed. ]

[formatting: eight asterisks] 
Details: 
{{ Comments }} 

Version(s) affected and disabled: 
{{ versions }}

Reviewer: 
{{ reviewer}} 
[formatting: eight asterisks]

Before we can re-enable your listing, please address the issues raised in the reviewer's notes and inquire about any unclear items. Afterwards, please upload a new version of your add-on at {{dev version URL}}. 

[formatting: two dashes]

Mozilla Add-ons
https://addons.mozilla.org

**Comment by jvillalobos** [comment]
I think these need some work. We should only tell developers we've delisted their add-on if all active versions have been disabled. It's possible to reject multiple versions without delisting an add-on. So, the rejection template should assume one of more versions being disabled for all cases.

**Comment by caitmuenster** [comment]
👍 Sure thing, that makes sense. I'll go back to the [drawing board](https://docs.google.com/document/d/1A8f83hnPSEBNekynHvca5R6i04qR5CwC-1aQWJXx9iU/edit).

**Comment by caitmuenster** [comment]
Revised templates below: 

## Template: Add-on Versions Disabled, Not De-listed 
Subject: Mozilla Add-ons: Versions disabled for {{ Add-on Name }}

Hello, 

Due to issues discovered during the review process, one or more versions of your add-on {add-on name} have been disabled on addons.mozilla.org. Please see the reviewer’s comments below for more information. 

[formatting: eight asterisks ] 
Details: 
{{ Comments }} 

Version(s) affected and disabled: 
{{ versions }}

Reviewer: 
{{ reviewer}} 

[formatting: eight asterisks]

Please address the issues raised in the reviewer's notes and inquire about any unclear items. Afterwards, please upload a new version of your add-on at {{dev version URL}}. 

If other versions of {{add-on name}} are enabled on addons.mozilla.org, it will continue to appear in the gallery. Users who had installed an enabled version will still be able to use the add-on. 

Thank you for your attention. 

[formatting: two dashes]
Mozilla Add-ons
https://addons.mozilla.org 

## Template: Template: Add-on De-Listed 

Subject: Mozilla Add-ons: {{ Add-on name}} has been disabled on addons.mozilla.org 

Hello, 

Due to issues discovered during the review process, your add-on {{ add-on name }} has been disabled on addons.mozilla.org and no longer appears in the gallery. Users who have previously installed your add-on will be able to continue using it.  

Please see the user’s comments below for more information. 

[formatting: eight asterisks]
Details: 
{{ Comments }} 


Reviewer: 
{{ reviewer}} 

[formatting: eight asterisks]

Please address the issues raised in the reviewer's notes and inquire about any unclear items. Afterwards, please upload a new version of your add-on at {{dev version URL}}. 

Thank you for your attention. 

[formatting: two dashes]
Mozilla Add-ons 
https://addons.mozilla.org

**Comment by diox** [comment]
When would the second template (which reviewer action specifically) come into play ? Is that just an edge case of the Reject Multiple Versions action ? Doesn't the wording on the first template `If other versions of {{add-on name}} are enabled` make that second one redundant ?

**Comment by jvillalobos** [comment]
The second one just makes it clearer that the listing is no longer visible. It's meant to reduce surprises and urge developers to react faster in those cases.

**Comment by diox** [comment]
But which action is it supposed to be used for ? Is it a different variant to be used for "Reject Multiple Versions"?

**Comment by jvillalobos** [comment]
Yes, sorry, they're both intended to be used when rejecting one or more versions of an add-on. The second one is meant to be used when all active versions are being disabled and the add-on ends up in an `Incomplete` status.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF58 (Win10)

Here is a sample of the email sent, respecting the new template:
![image](https://user-images.githubusercontent.com/31961530/35808009-27a53856-0a8d-11e8-9cd0-0855a5c110eb.png)


@caitmuenster I have a question with regards to the second template (Add-on De-Listed), specifically to the following line:




> Please see the user’s comments below for more information.

Shouldn't be more accurate to say "Please see the reviewer's comments..."?

**Comment by caitmuenster** [comment]
@AlexandraMoga Thank you for catching that! Yes, it should absolutely say "the reviewer's comments." :)

**Comment by AlexandraMoga** [comment]
@diox could you please add the above change in the mentioned template?

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO-dev, FF58 (Win10)

![image](https://user-images.githubusercontent.com/31961530/35859370-777d569a-0b48-11e8-8ff0-b8430eac548a.png)
