### ISSUE TITLE
New canned response: rejected for lack of response 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7370]
This is part of issue #7352. We should create a new canned response for rejecting add-ons because the developer did not respond to a request for more information within a reasonable period of time (ie, 7+ days). 

Text below: 

This add-on has been disabled due to lack of response for a prior request for additional information. Please get back to us with the requested information before uploading a new version.

**Comment by jvillalobos** [comment]
Since it's possible that failure to reply doesn't lead to complete delisting, and you can get rejected for multiple reasons, I suggest something like this:

> We didn't receive a response for a prior request for additional information. Please get back to us with the requested information before uploading a new version.

**Comment by caitmuenster** [comment]
That works for me. However, if an add-pon *does* get de-listed for failure to reply, we need to be able to communicate that with the dev. It looks like one of the sore spots is that developers aren't sure what it means to have an add-on "disabled" vs. "de-listed."

**Comment by jvillalobos** [comment]
Sure, but that's where the template can help. The template can tell you if you're being de-listed or not. The canned response should just explain the reason.

**Comment by caitmuenster** [comment]
Ah, got it. Would you mind taking a look at the [draft document](https://docs.google.com/document/d/1A8f83hnPSEBNekynHvca5R6i04qR5CwC-1aQWJXx9iU/edit#)? The rejection/de-listed template has been separated from the rejection/disabled template.

**Comment by caitmuenster** [comment]
Hey @kewisch and @wagnerand, do we still need a template for extensions that get rejected because the developer did not reply to a needinfo?

**Comment by wagnerand** [comment]
@caitmuenster Can you elaborate on that? There is a rejection template that is filled with whatever reason the reviewer provides.

**Comment by caitmuenster** [comment]
Oh, yes -- this canned response would specifically be for rejections caused by the developer not replying to a needinfo within the given timeframe. 

@kewisch mentioned on IRC that only the admins are rejecting for this reason, so I wasn't sure if this specific canned response was still needed.

**Comment by wagnerand** [comment]
Ah, thank you. I thought you were talking about the templates in the code :)

I can't find a canned response on AMO for lack of response. Where do you see it?

**Comment by caitmuenster** [comment]
It doesn't exist yet. :) I proposed creating a new canned response because I saw some people using it earlier this year before we changed the guidelines about acceptable summaries/descriptions.

**Comment by wagnerand** [comment]
Ah, sorry for the back and forth.

Yes and no: Yes, I believe we need a canned response for admins. No, I am not sure whether that one is worth adding to the ones on AMO.

**Comment by jvillalobos** [comment]
Closing this until/if it's clear it's needed.
