### ISSUE TITLE
Using the disable/enable button from Rev Tools will set an unclear add-on status in Dev Hub - Recent Activity section 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7374]
STR:

Prerequisites:  user has admin reviewer permissions

1. Log into Developer Hub and submit a new extension
2. Wait for the add-on to pass auto approval, 
3. Go to Reviewer Tools and search for your add-on in the auto-approved queue
4. In the add-on review page, scroll down to More Actions section and click on 'Force disable Add-on'
5. Go back to DevHub - Manage my submissions and observe the information displayed in the Recent Activity section

Expected result:
The displayed messages are clearly informing the developer about the current status of one or more of his add-ons

Actual result;
A "status changed to 5" message is displayed, which doesn't explain to the developer that his add-on was disabled by a reviewer

Notes:
When the reviewer uses the 'Force enable add-on' option, the message displayed in dev hub is "status changed to 4"
Reproduced on AMO-dev, FF57 (Win10)
Ref [#7282](https://github.com/mozilla/addons-server/issues/7282)

![image](https://user-images.githubusercontent.com/31961530/35281867-ab7f1fd8-005c-11e8-84a4-1cc1e26bc973.png)

**Comment by diox** [comment]
I re-used the same `ActivityLog` that the add-on admin page does, but yeah, that's ugly and we should fix it.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev and stage with FF58 (Win10)

![image](https://user-images.githubusercontent.com/31961530/35617586-499d890a-0681-11e8-8df3-87aa69fb5aad.png)
