### ISSUE TITLE
Add some space between "Private whiteboard" section and "Update whiteboard" button

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#7377]
Originally filed by @vcarciu at https://github.com/mozilla/addons-frontend/issues/4206

--------

Steps to reproduce:
1.Go to Reviewer Tools and open an add-on (https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/mixed-add-on)

Expected results:
We should have some space between "Private whiteboard" section and "Update whiteboard" button

Actual results:
There is almost no space between "Private whiteboard" section and "Update whiteboard" button

NOTES:
Issue was reproducible on Win10x64, FF 57

Please see screenshot for this issue : 
![whiteboard](https://user-images.githubusercontent.com/1583842/35290594-599c06f6-0073-11e8-8a33-fb3235ebd48f.png)

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
mentor me!

**Comment by SeanPrashad** [comment]
I'd love to help with this bug if possible!

**Comment by vcarciu** [comment]
I am still able to reproduce the issue in AMO-dev : 
![whiteboard2](https://user-images.githubusercontent.com/1583842/35514701-bd05ec84-050f-11e8-9656-78d3149247c0.png)

**Comment by eviljeff** [comment]
there was a dev deploy problem -  should be verifiable now

**Comment by vcarciu** [comment]
Verified as fixed : 
![whiteboard3](https://user-images.githubusercontent.com/1583842/35581757-77fc52a4-05f5-11e8-928b-c94f529094d9.png)
