### ISSUE TITLE
Prepare for Autograph release: Waffle Flag, use different statsd event 

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7380]
We want to enable autograph signing on production potentially over the next few weeks.

Lets…

* Switch from a waffle-switch to a flag to allow gradually enabling the autograph server config
* Make use of another statsd key in addition to the current one to allow tracking both values for old and new signing side-by-side for latency and req/m

Once this lands we can enable it slowly for a percentage of our developers and see how it goes and go forward once we deem it working and fast enough for broad usage.

**Comment by AlexandraMoga** [comment]
We tested several scenarios around add-on signing and everything seems to work as expected.
Marking this as verified fixed.
