### ISSUE TITLE
Update UI tests and circleci configuration to test against the new frontend.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#7381]
We should update the tests to work with the new frontend, as well as update circleci to pull the addons-frontend repo and set it up for CI testing.

**Comment by jrbenny35** [comment]
I am up for ideas on how to get this to work. I can't access the host network from within the docker container at an IP that is reliable it seems. I have tried downloading addons-frontend inside the ```selenium-firefox``` container but it seems that either I run out of memory, or the container just doesn't have the horsepower. Any thoughts?

**Comment by jrbenny35** [comment]
The tests are almost ready, currently blocked by #7402

**Comment by jrbenny35** [comment]
Added frontend sever [config](https://github.com/mozilla/addons-frontend/pull/4295) to addons-frontend.

**Comment by jrbenny35** [comment]
Blocked by #7526

**Comment by jrbenny35** [comment]
Fixed in #7565

**Comment by AlexandraMoga** [comment]
Could you please add a "qa:not needed" label to this issue?
Thank you
