### ISSUE TITLE
reviewer tools for static themes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7385]
part of mozilla/addons#501

Static themes need to be reviewable in a similar way to LWT are now.  This will probably need splitting up into sub-issues, or follow-ups filed.

To quote from the [PRD](https://docs.google.com/document/d/1d9acBumpdK87sYg7Ah98BEKvL7b4tuO-RDpgqbm7FTs/edit#heading=h.2lashaarscvd):

> The lightweight theme review guidelines and existing review tools are the best fit for reviewing static themes. Showing a preview image for inspection like it’s done for lightweight themes would make reviewing new themes a very straightforward task, avoiding the difficulties encountered for extension reviews, where code inspection and installation are required. It would also allow using the extremely efficient and very non-technical theme reviewer team with minimal re-training.
> 
> One addition that should be made to these tools in the case of new themes is an option to install or download the file, since in some cases the preview image might be insufficient.

**Comment by eviljeff** [comment]
roughly I'm thinking this as the plan:
1. Differentiate STs in reviewer tool queues
   a) stop extension queues from including STs
   b) create new queues for STs only (non-interactive)
   c) stop auto approve for STs
2. modify review page for single ST review
   a) modify to prominently show preview image for single ST review
   b) modify to support simple approve; numbered reject; (duplicate marking?)
3. interactive queues for pending & updates for bulk ST review
   a) approve/reject/etc API endpoints for review tools (just theme?)
   b) queue endpoint with locking
   c) write html UI with JS for XHR to APIs

I have the most doubts about the interactive queue - writing APIs and hand crafting JS to use them is time consuming (and fragile because no tests).  And it's effectively duplicating the existing reviewer tool functionality, including the work detailed in 1. and 2.

**Comment by jvillalobos** [comment]
FWIW, the reviewer tools plan includes consolidating the behavior of most reviewer tools, and that means that the interactive queues for themes will probably go away.

**Comment by eviljeff** [comment]
>  the interactive queues for themes will probably go away.

orly? 😮 I thought the interactive queue would have been a blocker.  That makes things a lot easier then.

**Comment by eviljeff** [comment]
This became a tracker issue - themes are listed in the queues appropriately; and the review page is customized.  @jvillalobos to review the tools and file follow-up issues for changes requested and calling this closed in the meantime.

**Comment by jvillalobos** [comment]
I'll add followups on https://github.com/mozilla/addons-server/issues/7855
