### ISSUE TITLE
Cannot log out of the frontend (DELETE /api/v3/accounts/session/)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7388]
### Describe the problem and steps to reproduce it:

See https://github.com/mozilla/addons-frontend/issues/4212

### What happened?

One cannot log out

### What did you expect to happen?

One should be able to log out

### Anything else we should know?

This looks like a regression introduced by https://github.com/mozilla/addons-server/pull/7360

According to the [Django docs](https://docs.djangoproject.com/en/2.0/ref/request-response/#django.http.HttpResponse.delete_cookie), we also need to set the domain when calling `response.delete_cookie()`

**Comment by diox** [comment]
Easy to fix, but testing is going to be tricky: https://code.djangoproject.com/ticket/28119

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF58 (Win10) -  see comments in [#4212](https://github.com/mozilla/addons-frontend/issues/4212)
