### ISSUE TITLE
Wrong ownership of official language pack

### ISSUE THREAD

**Issue by bidaian** [mozilla/addons-server#7389]
The Esperanto language pack is not owned by Mozilla but is built automatically. Because of that a manual approval was triggered:

> Your add-on, Esperanto Language Pack 58.0, has been approved and is now available for download in our gallery at https://addons.mozilla.org/addon/esperanto-language-pack/

I should be owned by Mozilla, according to this:

https://bugzilla.mozilla.org/show_bug.cgi?id=485617#c35

Could you please fix the ownership so that the language pack follows the normal (fast-tracked) procedures?

**Comment by jvillalobos** [comment]
The add-on is owned by Mozilla and was automatically approved after the language pack update yesterday. Maybe I'm missing something, but it looks like things worked normally.

**Comment by bidaian** [comment]
Well, I had not received an approval for years. Flod pointed out to the fact that the language pack was not solely owned by Mozilla and suggested that could be the cause. Do you have any idea on why I received the approval this time? Is there a way to simply remove me as a owner so that the language pack is just like all the others?

**Comment by jvillalobos** [comment]
No problem, I removed you now.
