### ISSUE TITLE
A "not authorized' error is received after the user deletes his account

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7392]
STR:

1. Log into AMO
2. From the user menu, select Edit profile
3. Scroll down in the profile page and click on delete account
4. Fill in the necessary fields and confirm the account deletion

Actual result:
The user is redirected to https://addons-dev.allizom.org/en-US/firefox/ but receives a 401 'Not authorized' error

Expected result:
The user is redirected to AMO homepage with a confirmation that the account was successfully deleted

Notes:
- reproduces on AMO-dev and stage with FF58 (Win10x64)
- possible regression from [#7361](https://github.com/mozilla/addons-server/issues/7361) where this  issue was first reported 

![image](https://user-images.githubusercontent.com/31961530/35383530-36ff9db6-01cb-11e8-93df-388f5309b7e3.png)

**Comment by diox** [comment]
It might be a consequence of https://github.com/mozilla/addons-server/issues/7388. We'll need to retest once the fix for it lands.

**Comment by AlexandraMoga** [comment]
This appears to be fixed on -dev. Can we close this issue?

**Comment by diox** [comment]
Yeah.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO-dev, FF58 (Win10)
