### ISSUE TITLE
[Legacy pages] A second search for collections will show add-ons suggestions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#7394]
Originally logged in #4224

Steps to reproduce:
1.Go to AMO , legacy pages
2.Search for a collection and press Enter
3.Search again for a collection

Expected results:
For collections, there is no search suggestions

Actual results:
Search suggestions are displayed under search box and the suggested items are add-ons not collections

NOTES:
Reproducible in production
Tested with Win10x64, FF release

Please see video for this issue :
![collsuggestions](https://user-images.githubusercontent.com/1583842/35391920-c88281dc-01e8-11e8-8f37-5eec13d950a7.gif)

**Comment by EnTeQuAk** [comment]
I'm going to close this in favor of https://github.com/mozilla/addons-frontend/issues/2782 as this will be re-implemented on the addons-frontend soon enough and fixing this here isn't really on our time-line right now.
