### ISSUE TITLE
Theme generator changes, part deux

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7398]
The new color selectors are really great. Love playing with the transparency.

**Wizard**
- [x] The "Select a header image" title has no spacing.
<img width="232" alt="header-margin" src="https://user-images.githubusercontent.com/62568/35411231-9c44ef84-01dd-11e8-8aeb-dc23fadc49f6.png">

- [x] The text fields for the color selectors are wider than necessary. Reduce their length to ideally align with the browser preview below.
- [x] Add a margin to top the tooltip buttons in the color selectors. The spacing at the top and bottom of the buttons should be similar.
<img width="181" alt="help-button-margin" src="https://user-images.githubusercontent.com/62568/35411346-133b1c3a-01de-11e8-9623-fe441b992415.png">

- [x] "Header area text" -> "Header area text and icons"
- [x] "Header area text" help text -> "The color of the text and icons in the header area, except the active tab."
- [x] "Toolbar area text" -> "Toolbar area text and icons"
- [x] "Toolbar area text" help text -> "The color of the text and icons in the toolbar and the active tab."
- [ ] The only required field should be the theme name. However, the button shouldn't be enabled until a header image is uploaded or a color field has a non-default value.
- [x] The header image preview (after uploading) needs some size restrictions. A big square image takes more of the page and pushes everything down.

**Description step**

- [ ] The summary field covers the whole width of the page, which makes it partially disappear to the right if the window isn't very wide.  Not sure if this is consistent with other upload flow fields, but ideally it shouldn't be so wide. 
- [x] There's no indication that the license fields are required.

**Comment by eviljeff** [comment]
> The only required field should be the theme name. However, the button shouldn't be enabled until a header image is uploaded or a color field has a non-default value.

The required fields are as per the [specification](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme).  (`name` should be required too, yep)

**Comment by eviljeff** [comment]
>The summary field covers the whole width of the page, which makes it partially disappear to the right if the window isn't very wide. Not sure if this is consistent with other upload flow fields, but ideally it shouldn't be so wide.

It is consistent, yeah.  All devhub `section`s are 960px wide, and the text areas are 100% of whatever they're placed within.

**Comment by jvillalobos** [comment]
> The required fields are as per the specification.

Odd, but okay.

**Comment by jvillalobos** [comment]
> It is consistent, yeah.

Okay, let's not change that then.

**Comment by AlexandraMoga** [comment]
Verify on AMO dev with FF58, Win10
- All changes mentioned below have been applied 
- there are some small issues noticed: "Toolbar area text icons" is missing an "and; the reduce width for the color selector section will cause layout issues for some locales (opened issue [#7451](https://github.com/mozilla/addons-server/issues/7451) for both these problems)

![image](https://user-images.githubusercontent.com/31961530/35632010-1b7297a0-06ae-11e8-849b-7c0d00166575.png)

![image](https://user-images.githubusercontent.com/31961530/35632016-22841190-06ae-11e8-964b-dc26500004a9.png)

Marking this as verified fixed
