### ISSUE TITLE
Separator line is not properly placed on Theme Generator page 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7405]
Steps to reproduce:
1. Load AMO dev and go to Developer Hub to submit a new add-on.
2. Use "Create a Theme Version" wizard to submit a static theme.
3. Scroll down and observe the separator line displayed below Browser Preview.

Expected result:
The separator line has approximately the lenght of the image and it is displayed at a visible distance.

Actual result:
The separator line extends beyond the image and it is placed right under the image.

Notes:
This issue was verified on AMO dev (Win10)

![separator line](https://user-images.githubusercontent.com/33448286/35433794-5ad0a3c6-028d-11e8-88dd-2785ac76b100.png)

I attached a screenshot with the Preview displayed for Lightweight Themes.

![lightweight themes](https://user-images.githubusercontent.com/33448286/35433811-6af4c34a-028d-11e8-92f3-8e5dffaa2264.png)

**Comment by SeanPrashad** [comment]
Hi there, I would like to work on this bug if it's still available!

**Comment by SeanPrashad** [comment]
I was trying to recreate the issue on my local machine but I'm only able to find [this](https://addons.mozilla.org/en-US/developers/theme/submit) webpage for submitting a new theme. I don't think that's what I need to be looking for - where would I find the Theme Wizard?

**Comment by diox** [comment]
@SeanPrashad : this is the new static theme wizard, it's currently behind a switch that is not activated in prod or your local environment. To enable it locally, run:
`docker-compose exec web bash ./manage.py waffle_switch allow-static-theme-uploads on`

Then in Developer Hub, select "Create a New Add-on" (not "Submit a New Theme"), and then "Create a theme". You should see the wizard.

**Comment by SeanPrashad** [comment]
Thanks for that heads up @diox! Unfortunately, when I try to run that command, I get the following error:

<img width="936" alt="screen shot 2018-02-20 at 9 30 20 am" src="https://user-images.githubusercontent.com/13009507/36429649-3dc45776-1621-11e8-8ba3-02473b012e31.png">

Should I try and edit the `manage.py` file myself?

**Comment by diox** [comment]
sorry, remove the extra `bash` in the command I gave you.

**Comment by SeanPrashad** [comment]
Still doesn't look like it's working 😞:

<img width="1691" alt="screen shot 2018-02-20 at 11 54 04 am" src="https://user-images.githubusercontent.com/13009507/36437421-ee66b3f4-1634-11e8-83fd-1dc9327e5fb4.png">

**Comment by diox** [comment]
Welp. Add `--create` to that command, that should fix it.

**Comment by SeanPrashad** [comment]
Should `--create` be placed anywhere specifically?

<img width="1686" alt="screen shot 2018-02-20 at 12 04 40 pm" src="https://user-images.githubusercontent.com/13009507/36437927-63b799c4-1636-11e8-941d-01b5d16b53d6.png">

**Comment by SeanPrashad** [comment]
It worked! I used this command: `docker-compose exec web ./manage.py waffle_switch allow-static-theme-uploads on --create`

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF58 (Win10).  

![browser preview sepline](https://user-images.githubusercontent.com/33448286/36780374-82611f62-1c7b-11e8-96d4-e7c3249b7db1.png)
