### ISSUE TITLE
Don't warn about icon size mismatch if icon is SVG

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#7415]
ref: mozilla/addons-linter/issues/1669

There are still warnings ....

https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/817497/

    Warning: The size of the icon does not match the manifest.
    Expected icon at "images/rikaichamp-blue.svg" to be 48 pixels wide but was 200.

    Warning: The size of the icon does not match the manifest.
    Expected icon at "images/rikaichamp-blue.svg" to be 96 pixels wide but was 200.

    Warning: The size of the icon does not match the manifest.
    Expected icon at "images/rikaichamp-blue.svg" to be 128 pixels wide but was 200.

**Comment by EnTeQuAk** [comment]
addons-linter 0.34.0 is heading towards AMO so this should be fixed as of this Thursday.

Please keep in mind that this doesn't apply to old reviews. I can't see the review you posted but I assume it might be an old one where it wasn't properly linted yet.

**Comment by erosman** [comment]
>  I assume it might be an old one where it wasn't properly linted yet.

It is an older one but are these data cached at the time of submission? Don't they run the linter whenever requested?

**Comment by EnTeQuAk** [comment]
> It is an older one but are these data cached at the time of submission? Don't they run the linter whenever requested?

I might be wrong but we store validation data at the time of submission as far as I know and don't re-validate add-ons usually. I thought there was a "re-validate" button somewhere but I'm not too certain.

**Comment by AlexandraMoga** [comment]
I've validated a new extension which included `.svg` icons with wrong sizes defined in the manifest and no errors/warnings were thrown.
@EnTeQuAk , @erosman if the issue can't be reproduced with new submissions, can we mark this case as verified?

**Comment by erosman** [comment]
> @erosman if the issue can't be reproduced with new submissions, can we mark this case as verified?

Sure ... I was under the impression that whenever we run the validation, it runs a new validation, but as it seems, it is cached and the error pertains to the older validation.
