### ISSUE TITLE
Fix static theme wizard to handle oddly sized images

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7418]
During ongoing development of the static theme wizard the ability to handle arbitrary sized background images seems to have to "optimized" out of the code 😞 

Currently only images that are 200px high and at least 680px and rendered correctly.  A different height or a shorter width and the image is scaled (wrongly).

**Comment by ioanarusiczki** [comment]
I made some tests using .png and .jpg samples for 680x200, 200x100, 1080x1920, 2016x1512.  I've chosen red for the header area background.

680x200 .png and .jpg sized images won't display any changes in theme preview but when theme is installed the chosen red background is visible. The same for 1080x1920, 2016x1512.  The small samples 200x100 were the only ones that look the same in theme preview and after installing them. 
 
680x200 .png and .jpg samples in theme preview and after installing the themes

![680x200](https://user-images.githubusercontent.com/33448286/35797050-25edce36-0a67-11e8-8fd6-d0fcc72073c1.gif)

1080x1920 .png , 2016x1512 .jpg in theme preview and after installing the themes

![big samples](https://user-images.githubusercontent.com/33448286/35798587-e705c23c-0a6b-11e8-8ef1-8104919f5343.gif)

200x100 .png and .jpg in theme preview and after installing the themes

![200x100](https://user-images.githubusercontent.com/33448286/35798654-21026864-0a6c-11e8-9ec3-08245e17eb91.gif)

Shouldn't the size of the image be settled at a specific height and width for upload, the same way as for the lightweight themes (3000x200 in their case) ?

**Comment by eviljeff** [comment]
No, images can be any size.  They _should_ be 200 high, like LWT, but it's not enforced and any size is handled in the browser (afaik).  
re: the red showing for 680px wide images - I assume you're getting different results because you're using a larger browser window than 680px.  The preview is only what you're going to see at that size - if the browser is larger or smaller it's going to be different.  Potentially the wizard could be developed to support variable sized windows but that wouldn't help as the preview is rendered into a PNG eventually, and that's obviously a fixed size.

**Comment by ioanarusiczki** [comment]
@eviljeff  I'm not sure that a different browser size is the problem because when I use the 680x200 .jpg sample and only edit the Toolbar Area background ( I selected blue for that area) the theme preview shows the same changes like any browser size after installing the theme.  Shouldn't changing colors for the Header Area work like changing them for the Toolbar area?

![blue toolbar](https://user-images.githubusercontent.com/33448286/35853354-f6c6403c-0b35-11e8-9c2e-c84a8abdcd04.gif)

**Comment by eviljeff** [comment]
sorry, I'm lost what the problem is from looking at the videos.  can you repeat with STR or come chat on IRC?

**Comment by ioanarusiczki** [comment]
I used a .png sample which supports transparency. The preview will display the changes for the Header Area Background. This is verified fixed on AMO dev using FF58 (Win 10).

![png transparent](https://user-images.githubusercontent.com/33448286/35868760-226d51a0-0b66-11e8-9781-c601bc3b6004.png)
