### ISSUE TITLE
Refactor reviewer flags APIs into a single endpoint

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7419]
In https://github.com/mozilla/addons-server/issues/7282 I've added several API endpoints for reviewer flags. I've then starting adding more. @eviljeff [pointed out](https://github.com/mozilla/addons-server/pull/7407#issuecomment-361217316) it'd be more convenient to have a single reviewer flags endpoint with some parameters to change the values instead of adding a new endpoint every time, and he's absolutely right :)

**Comment by diox** [comment]
QA:
- Verify that the "More Actions" (clear pending info request, clear admin content/code review, disable/enable auto approval, etc) for admins on a review page are still available when needed and working correctly

**Comment by AlexandraMoga** [comment]
I've verified the options from "More Actions" section in AMO stage and all available actions seem to be working correctly.

I will mar this as verified fixed.
