### ISSUE TITLE
New version notifications are sent only to Reviewers with Addons:Review permission

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7420]
STR: 

Prerequisites: log into AMO with a user that has Addons:PostReview permissions and is not an admin

1. Log into Developer Hub and submit a new listed add-on
2. Once your add-on passes auto-approval, go to Reviewer Tools and search for your add-on in the Auto-approved queue
3. Select the add-on to open its review page and scroll down to 'More Actions' section
4. Click on "Notify me about new listed versions" checkbox to subscribe to new version notifications
5. Go back to Dev Hub and submit a new listed version for your add-on
6. With an Admin account, go to Admin tools - Fake email log and verify if the reviewer received a notification regarding the new submitted version

Actual result;
There is no notification sent to the reviewer with PostReview permission when a new listed version is uploaded

Expected result:
The reviewer with PostReview permission receives an email if he subscribes to new listed version notifications for a reviewed add-on

Notes:
- The same steps can be applied for a user with Review:Content permission who subscribes to new version  notifications
- Reproduced on AMO-dev, FF58 (Win10x64)

**Comment by diox** [comment]
Ah, yeah. It actually works for any user with the `Addons:Review` permission - so, legacy reviewers. I'll change that to any kind of reviewer.

**Comment by AlexandraMoga** [comment]
Verified with two users having `Review:Content`, respectively `Addon:PostReview` permissions and both received new version notifications.

The change is currently only on AMO-dev...

**Comment by diox** [comment]
This fix should also be on stage now. Can you double-check?

**Comment by AlexandraMoga** [comment]
Works on stage as well
