### ISSUE TITLE
A non-functioning "Create a Collection" button is displayed in "Create a new collection" form 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7423]
Steps to reproduce:
1. Load AMO dev, hover over the account name and click on "View my collections"
2. Click on "Create a collection" 
3. Type a name, description and select an ad-on to add in the new collection
4. Click again on "Create a collection" button displayed on the left side of the screen

Expected result:
The collection is created and displayed.

Actual result:
Create a new collection form is reset to the initial state. Name, description and the ad-on selected are no longer displayed.

Notes:
Please note that "Create Collection" button displayed at the end of the form works as expected. 
This issue was verified on AMO dev and AMO stage using FF58 (Win10).

![create a collection](https://user-images.githubusercontent.com/33448286/35512607-0907cab4-0509-11e8-9817-b96db7793770.gif)

**Comment by muffinresearch** [comment]
This will be superceded by the new UI for collections. See https://github.com/mozilla/addons-frontend/issues/2782
