### ISSUE TITLE
Prefix subject of review emails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7427]
We got reports that developers missed the emails from reviewers because it didn't look "official" enough.

We could prefix the subject of the email with "[Mozilla Add-on Review]" or similar.

@kewisch @jvillalobos for feedback.

**Comment by kewisch** [comment]
One thing we need to be careful of is the term "review". Some developers have expressed they thought this was a user review, not an add-on review (and even "add-on review" might be ambiguous).

I'd suggest "%name via Add-on Reviewers". The difference is subtle, but to me "via Add-on Reviewers" makes it sound like that is a dedicated group, as opposed to just a "review".

I'm also open to alternatives without the word review as well.

**Comment by jvillalobos** [comment]
This may be already covered by the other issues in #7352. For instance, the info request email would have "Mozilla Add-ons: Action Required for {{ add-on name }} {{ version }}" for its subject, which should make it clearer that something needs to be done. I haven't heard many complaints about rejections not being noticed :P.

Another thing we could do it set an importance header on the emails. It's a bit of an ancient and obscure email feature, but I think most email clients support it.

**Comment by wagnerand** [comment]
The info-request email has this now. Let's close this and evaluate further whether and which templates need more updates.
