### ISSUE TITLE
Documentation: Explicitly mention to use Firefox for olympia.dev

### ISSUE THREAD

**Issue by SeanPrashad** [mozilla/addons-server#7433]
### Describe the problem and steps to reproduce it:
As a first time user who has no exposure to Docker or any other technologies, the [addons-server documentation](https://addons-server.readthedocs.io/en/latest/topics/install/docker.html) was great however I spent many hours debugging why I wasn't able to access olympia.dev via Chrome even though I successfully configured the Docker containers.

It would be very helpful to mention that you need to explicitly access the web server from within Firefox (and no other browser variant).

### What happened?
Unable to access olympia.dev from within Google Chrome due to misunderstanding that it was accessible via Firefox only!

### What did you expect to happen?
Olympia.dev would load as normal in any browser

### Anything else we should know?
![screen shot 2018-01-29 at 8 45 24 pm](https://user-images.githubusercontent.com/13009507/35543847-5d837e86-0535-11e8-9e28-132c1dc7f840.png)

**Comment by eviljeff** [comment]
You hit https://github.com/mozilla/addons/issues/493 which we're in the process of fixing.  Though, generally, as we're developing for Firefox Add-on users, using Firefox is best anyway.
