### ISSUE TITLE
Disable beta versions submission and listing

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7435]
This is part of #7163.

Beta submissions will no longer be possible. All submissions will be submitted against the same channel (if listed), regardless of their version string.
Beta versions will no longer show up in the public listing and the developer hub.

STR will follow.

**Comment by eviljeff** [comment]
"Beta versions will no longer show up in the public listing" - will API changes be needed for new frontend?  (Maybe separate issue?)
Or any changes on new frontend itself?  (certainly separate issue)

**Comment by wagnerand** [comment]
STR:

1. Make sure the `beta-versions` waffle switch is enabled:
2. Have a public add-on with at least one approved version.
3. Submit a new version for that add-on with a beta version number, for example `3.1beta1`.
4. Check the *beta* checkbox during submission to submit that version to the beta channel.
5. Flip the `beta-versions` waffle switch.

A) 
1. Submit a new version for that add-on with a beta version number, for example `3.1beta2`.
2. Make sure the beta checkbox does **not** show up in the submission process.
3. Go to the devhub -> Manage Status and Versions and confirm that the version you just added is **not** marked as beta.

B)
1. Go the public listing page on the **old** frontend.
2. Make sure the listing page does not show the "Development version" section towards the bottom of the page.

**Comment by vcarciu** [comment]
Verified as fixed :  
![beta2](https://user-images.githubusercontent.com/1583842/36490660-743c0554-1731-11e8-9a5b-46ae201e3d59.gif)
