### ISSUE TITLE
Allow all reviewer types to participate in email notifications and replies 

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7441]
Came up on #7366.

The following permissions should be permitted for email comms: `Addons:PostReview`, `Reviews:Admin`, `Addons:ContentReview`, `Addons:Review`, `Addons:ReviewUnlisted`, `Personas:Review`.

Note: theme reviewers (`Personas:Review`) don't have that capability yet, but the plan is for theme review tools to eventually use the same flows as the other review tools, so we might as well allow this now.

**Comment by AlexandraMoga** [comment]
I've tested with different users having the above permission sets by posting reviewer replies, information requests, add-on rejections.
The correct email templates were sent for each case and a copy of the email was also sent to these users if they were included in the Activity mail group.
I'm marking this as verified fixed.
