### ISSUE TITLE
Avoid xpi extraction when reading manifest.json information

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7443]
Reading through our code I always assumed we extract the XPI for more than just reading the manifest.json but it appears we don't. When I implemented the `_locale` messages parsing it uses the zipped data directly and the linter does that as well.

So there seems to be no reason to ever extract the XPI, especially not for reading the manifest.json. Some add-ons contain quite a lot of files and extracting that on our EFS can be quite slow and unnecessary.

Let's remove the `extract_xpi` functionality and make sure it's never used during our upload process.

Refs #4438

**Comment by eviljeff** [comment]
Mmm, I'm actually going to be doing something similar for generating screenshot previews for static themes  - the background image needs to be extracted to be referenced.  I didn't use `extract_xpi`, etc though, I'm doing https://github.com/mozilla/addons-server/compare/master...eviljeff:7056-generate-static-theme-preview#diff-910d9d00817510d6161315516feecfcbR1131

**Comment by EnTeQuAk** [comment]
QA: This primarily modifies code during submission of a new add-on or an update of an add-on. So testing that should cover the modifications here, making sure that all that still works for new add-ons and potentially an update for a legacy add-on as well.

**Comment by AlexandraMoga** [comment]
There weren't any issues discovered at add-on submission or version updates (including legacy add-on updates). The extension package was also correctly rendered in the file viewer available in Reviewer tools. 
Based on that I will mark this issue as verified fixed.
