### ISSUE TITLE
Searches performed in the collection page are returning extensions and themes

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#7448]
### Steps to reproduce:
1. Open https://addons-dev.allizom.org/en-US/firefox/collections/
2. Enter a generic search term and perform a search

### Expected results:
A list of collections is returned.

### Actual results:
Extensions and themes are returned.

### Anything else we should know?
Verified in FF58(Win7) Issue is reproducing only in amo-dev
Might be a regression from #7244 
Screencast for this issue:
![collectionsearch](https://user-images.githubusercontent.com/15685441/35618985-37005706-0685-11e8-85fe-00053440c699.gif)

**Comment by muffinresearch** [comment]
We'll soon have a new collection page on the new frontend so that should stop this being so dis-jointed. Marking this as a won't fix as a result of that.
