### ISSUE TITLE
Prevent users from setting their username/display name as 'Mozilla' or 'Firefox'

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7449]
Follow up from [#6693](https://github.com/mozilla/addons-server/issues/6693#event-1448527363)

STR:

1. Log into AMO-dev and select 'Edit Profile' from the user menu
2. Set your display name as 'Mozilla"
3. Hit the "Update profile' button

Actual result:
A user can successfully set his display name as 'Mozilla' even when he is not associated with the organization.

Expected result:
Users that have no association with Mozilla should not be allowed to set their username/display name as 'Mozilla' or 'Firefox'.

Notes:
- This could be very misleading for an AMO user looking at the add-on details page
- Reproduced on AMO -dev with FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/35625215-35ad621c-069a-11e8-9c85-573de4be5a6e.png)

**Comment by jrbenny35** [comment]
@EnTeQuAk I could work on this.

I see in the ```users.py``` that the field for username is unique. I am thinking that on -dev there is no 'Mozilla' user created so that is why this could happen.

**Comment by eviljeff** [comment]
The `DeniedName` model is supposed to be used to filter out invalid names like this... so either a) this isn't working somehow or b) "Firefox" and "Mozilla" aren't in the DeniedName list on -dev or stage.

DeniedName list can only be edited in django admin so someone with Admin rights will need to check to see what's in the list.

**Comment by jvillalobos** [comment]
"Mozilla" and "Firefox" aren't on either list. The denied names filter is applied to other properties (like collection names) and its scope is planned to be expanded (see #7252). So, that list should be focused on targeting spam. Blocking those terms will probably lead to many false positives, so I don't think that's the right place for that filter.

**Comment by rafspiny** [comment]
In the meantime I added a test to check that DeniedName is used when updating a user's display_name. I didn't find such a test elsewhere so I added it and made it available in this pull request #7736

How (and if) this shall be addressed then?
- Creating a separate list of reserved_name
- Making display_name unique

**Comment by jvillalobos** [comment]
We decided a better fix for this is to make display names unique (and block those names with official Mozilla accounts). Closing in favor of https://github.com/mozilla/addons-server/issues/8296
