### ISSUE TITLE
addons should work on amo 

### ISSUE THREAD

**Issue by Ulf3000** [mozilla/addons-server#7450]
### Describe the problem and steps to reproduce it:
theres a problem with adddons not being able to modify amo.. 

people are really dumb and ignorant and try to use your addon directly on amo and then give a 1star rating (obviously withOUT any sort of explanation like browser version os etc)

**Comment by diox** [comment]
Unfortunately, as AMO has access to special APIs allowing add-ons to work on AMO is dangerous. That restriction is implemented in Firefox itself, it may be tweaked in the future but for now it has to be this way. See https://bugzilla.mozilla.org/show_bug.cgi?id=1310082 and https://bugzilla.mozilla.org/show_bug.cgi?id=1295324 for more information.

**Comment by Ulf3000** [comment]
ok too bad , but its a problem because like whatever text addon would simply be skipped by most users becasue they try it directly on the amo page and think its broken
