### ISSUE TITLE
Color selectors in static theme submission wizard have layout issues for some locales

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7451]
STR:

1. Log into Developer Hub and submit a new static theme using the wizard
2. Change your locale to i.e. German, Italian etc
3. Observe the text layout for the color selectors

Actual result:
Text specific for each color selector is not correctly aligned 

Expected result:
The text specific for each color selector is properly aligned with the color field

Notes:
- there is also an "and" missing from "Toolbar area text icons"
- reproduced on AMO-dev with FF58, Win10

![image](https://user-images.githubusercontent.com/31961530/35632499-860f584a-06af-11e8-801f-8ba678f240d9.png)

![image](https://user-images.githubusercontent.com/31961530/35632519-9562f46e-06af-11e8-8964-d16054d3fc9b.png)

**Comment by eviljeff** [comment]
@jvillalobos can you suggest what the ideal layout would be given that some locales have the temerity to have long(er) words?

**Comment by jvillalobos** [comment]
We don't want to crop the names or the other metadata, so inevitably they'll have to break into a new line for those cases. It doesn't look as neat English, but I don't think it looks terrible or confusing.

If we can make them a bit wider to accommodate more languages, that's okay with me, but I don't want to completely change the layout for this.

**Comment by eviljeff** [comment]
There is already wrapping by default so does anything need to be done?  

I could make the text label the same length as the input, though that'll lead to more wrapping; 
I could extend the input box width though it looks better as is with a gap, imo;
I can't really make it all wider without the inputs and labels above being wider than the preview below (I seem to recall the preview width matching the rest of the page was a previous ask)

**Comment by jvillalobos** [comment]
Extending the input box to match the max width of the label would make this look better IMO. There would still be a gap, just a smaller one.

**Comment by AlexandraMoga** [comment]
@eviljeff Note also that for RTL, the  right margin is not consistent with the rest of the page

![image](https://user-images.githubusercontent.com/31961530/37088097-e4d1c546-2204-11e8-8e8d-c6bf40c34e97.png)

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF58, Win10x64. 
The reported layout issues have been fixed, except for the RTL alignment mentioned above. I will mark this as verified and open a new case to track the RTL issue.

![image](https://user-images.githubusercontent.com/31961530/37338434-1f8c98c2-26c0-11e8-8f10-efdc5e47c768.png)
