### ISSUE TITLE
Stop sending an email to developers if their add-on got flagged for admin review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7453]
Meant for pre-review, we are sending out an email to developers if a reviewer flags the add-on for admin review. The intention was to inform the author to expect some delay until the add-on is being approved.

It is not super useful in post-review. On the contrary, we get inquiries of confused developers asking what's going on.

Let's drop the notification email. For the sake of reducing complexity, I'd remove it for all add-ons, including legacy, given the low volume of submissions we get.

@kewisch @jvillalobos @caitmuenster for feedback

**Comment by jvillalobos** [comment]
Agree. The PRD for Reviewer Tools doesn't include that notification for that reason.

**Comment by caitmuenster** [comment]
I'm ok with dropping notifications to developers that their add-on has been moved to the admin review queue.

**Comment by AlexandraMoga** [comment]
Checked with requesting Super Review for code and content and in both cases there was no email sent to the developer.
This an be marked as verified fixed
