### ISSUE TITLE
Split travis jobs in a more efficient way

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7468]
We're running the following matrix of tests:
  - TOXENV=codestyle
  - TOXENV=docs
  - TOXENV=assets
  - TOXENV=es
  - TOXENV=addons
  - TOXENV=devhub
  - TOXENV=reviewers
  - TOXENV=amo-and-locales
  - TOXENV=users
  - TOXENV=main

`main` is a fallback for everything not run above. One thing I've noticed is that most of the time is spent installing packages... but also that the jobs split is not optimal at all. The one that is immediately noticeable is `users`:
- Takes around 5-6 minutes
- Around 3 minutes are spent in tox
- Only 30 seconds spent in actual tests, there are only 166 of them.

I don't know how many concurrent jobs we can currently run, but I think it'd be good to rethink the split and either move back `users`tests in an another job or do the opposite, move some from `main` to `users` (`accounts` at least is a prime candidate for this).

**Comment by diox** [comment]
Looking at a few recent builds moving `accounts` to `users` would make the most sense for starters. `main` and `es` are usually the slowest and we always (?) have enough concurrent jobs to run them all in parallel so they are the 2 we should focus our efforts on.

**Comment by eviljeff** [comment]
re: `main` - might be an interesting exercise to separate out the legacy frontend tests from the backend ones... though addons (and users, in part) has a mix too.

**Comment by diox** [comment]
I thought about that but... that's not necessarily trivial and it's "wasted" once we remove the legacy site... any day now...
