### ISSUE TITLE
Revise Add-on update notification 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7469]
Part of issue #7352. These are revisions to the email generated when a developer updates their add-on on AMO. 
______

Subject: Mozilla Add-ons: {{ add-on name}} Updated 

Hello,

Your add-on {{ add-on name}} has been updated on addons.mozilla.org (AMO). Version {{ version number}} is now available for download in our gallery at {{ url }} . 

This version has been screened and approved for the public. Keep in mind that other reviewers may look into this version in the future and determine that it requires changes or should be taken down. In that case, you will be notified again with details and next steps.

Thank you!

[formatting: eight ********]
Developer Resources 
[formatting: eight ********]

To respond, please reply to this email or visit:  {{ url }} 

You can also get in touch with us using these channels: 
https://developer.mozilla.org/Add-ons#Contact_us

For tips on how to attract more users by updating your add-on’s listing, please visit: https://developer.mozilla.org/Add-ons/Listing

To learn more about the review process, please visit: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews

[formatting: two --]
Mozilla Add-ons Team
https://addons.mozilla.org

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF58, Win10x64

The template looks ok, just two small issues to address:

1. there are two "Hello"s in the intro
2. maybe the "Contact us" link should be displayed on the same line with "_You can also get in touch with us using these channels_" to make it similar to the other links in the body 

![image](https://user-images.githubusercontent.com/31961530/36429045-3533a6aa-165a-11e8-9b6e-bc60982b6a3a.png)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO stage, FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/36488826-173b3824-172d-11e8-970d-06a47876eede.png)
