### ISSUE TITLE
LibreOffice support

### ISSUE THREAD

**Issue by b0c1** [mozilla/addons-server#7470]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
LibreOffice using Firefox themes for personalization. Currently, LO can't download the theme from FF.

### What happened?
LibreOffice can't download the themes because the download link changed or removed...

### Anything else we should know?
I know this is not the Mozzila problem, but there is a Community around open source software, and it depends on each other. Can you contact LO developers about the changes?

LibreOffice issue page: https://bugs.documentfoundation.org/show_bug.cgi?id=114731

Thanks

**Comment by eviljeff** [comment]
We don't support third party usage of the AMO frontend - and the bug report is too vague for us to do anything anyway.
Some additional points:
* if the legacy frontend is being used for the 'download link' then be aware it's deprecated, will only be getting minimal maintenance, and will be removed some time in the middle of the year.
* if the new frontend is being used for the 'download link' then it's completely different react based code.
* in any case, 3rd party use should be done via the API http://addons-server.readthedocs.io/en/latest/topics/api/index.html

**Comment by eviljeff** [comment]
Oh also we're planning on deprecating and removing existing Themes from AMO some time this year and replacing them with web extension based themes. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme
