### ISSUE TITLE
add-on is available in content review queue,after being rejected in the technical review queue

### ISSUE THREAD

**Issue by ralli007** [mozilla/addons-server#7477]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
You can still approve the add-on in the content queue, although it's been rejected during technical review

### What happened?
The add-on was in the content review. A content reviewer asked for more info, then a technical reviewer rejected the version during technical review. 

### What did you expect to happen?
To see the add-on in the technical queue, not in the content one.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/metadesk-assistant-for-firefox
![image](https://user-images.githubusercontent.com/17409099/35746536-c77d40ac-084f-11e8-93ec-5457f06bb48a.png)

**Comment by diox** [comment]
Well, this is awkward, but the add-on itself hasn't been rejected, only the latest version, so technically it's still up for content review... /cc @jvillalobos

**Comment by jvillalobos** [comment]
If there are active versions, I think content review should still be possible. Content review applies to the listing and not specific versions, but I can see how the way we implemented it would make it awkward to deal with this case.
