### ISSUE TITLE
Update template for "successful submission to AMO" notification

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7478]
Part of issue #7352. These are updates to the template notification developers receive when they successfully submit an add-on to AMO. 
___ 

Subject: Mozilla Add-ons: {{ add-on name }} has been submitted to addons.mozilla.org! 

Thanks for submitting your {{ add-on name }} add-on to addons.mozilla.org (AMO)! Your add-on listing will go live shortly in our gallery here: {{ url }}

Please keep in mind that while your add-on has been screened and approved for listing, other reviewers may look into it in the future and determine that it requires changes or should be removed from the gallery. If that occurs, you will receive a separate notification with details and next steps.

For more information about the review process and policies, please visit https://developer.mozilla.org/Add-ons/AMO/Policy/Reviews. 

[formatting: eight ********]
Attract Users, Stay Updated, & Get in Touch 
[formatting: eight ********]

Add-ons help personalize the web experience for millions of users who have installed Firefox, and we want to help make your users happy! If you have not already done so, we recommend checking out these resources: 

* Help users discover and install your add-on by learning how to create an appealing listing:  https://developer.mozilla.org/Add-ons/Listing

* Want your add-on featured on AMO? Learn more: https://developer.mozilla.org/Add-ons/AMO/Policy/Featured

* Join our mailing list to stay up-to-date with news and events relevant to add-on developers, including a subscription to our quarterly newsletter, about:addons: https://addons.mozilla.org/firefox/users/edit#acct-notify

* Follow the Add-ons Blog to stay up-to-date on the latest news: https://blog.mozilla.org/addons/

* For more add-on developer resources, please visit MDN web docs: https://developer.mozilla.org/Add-ons

* Want to ask a question or file a bug report? These are the best ways to contact us:  https://developer.mozilla.org/Add-ons#Contact_us

Happy developing! 

[formatting: two --]
Mozilla Add-ons
https://addons.mozilla.org

**Comment by AlexandraMoga** [comment]
@diox , this should be in dev, right? I've test it now but I am not receiving the new template.

**Comment by diox** [comment]
It should be, yes. What are you seeing? Keep in mind this is only sent once, for your very first listed submission.

**Comment by AlexandraMoga** [comment]
Verified on AMO stage with FF58 Win10x64

@diox not sure if this has anything to do with how fake mail interprets data but when I looked at this template, there was also the HTML version displayed right below the email.
Here is the log entry if you want to have a look yourself - https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-29327

![image](https://user-images.githubusercontent.com/31961530/36490162-4c993dd8-1730-11e8-9e94-f54f3429a083.png)

**Comment by diox** [comment]
Yes, this email is one of the only emails that is sent in both HTML and text formats.

**Comment by AlexandraMoga** [comment]
In that case, this can be marked as verified fixed
