### ISSUE TITLE
Enhancement: Allow Unflagging the Flagged Reviews

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#7481]
I have often noticed people who make a irrelevant review, later change their review (once they find out their mistake).

For example, I have got a few erroneous bad reviews for not being FF57 compatible when the reviewer posted the review to the wrong add-on. That is to say they wanted to post it to a different add-on but posted it to my add-on. Once their error is pointed out to them in **Developer response**, they sometimes change their review.

Now, if the developer had already flagged the review as inappropriate, there is no mechanism to undo the flag and such mechanism would be useful to have.

**Comment by erosman** [comment]
Here is the screenshot:

https://screenshots.firefox.com/zi0j4HH7GTICzgvj/addons.mozilla.org

**Comment by jvillalobos** [comment]
I can see it being useful, but it looks like a very limited use case. I'd say it's either low priority or WONTFIX.
