### ISSUE TITLE
Make "Support Site" more visible on add-on page 

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#7483]
For years, I have been asked "Where is the support site?" even though they have ALWAYS been listed under "Support Site" on add-on's pages. Users then use  the Review system for support queries.

The new layout made it even **less** noticeable. Please make it more dominant and noticeable.

**Comment by muffinresearch** [comment]
@erosman please can you provide a screenshot to illustrate what pages you are referring to?

**Comment by erosman** [comment]
Here is the screenshot:

https://screenshots.firefox.com/zi0j4HH7GTICzgvj/addons.mozilla.org

**Comment by diox** [comment]
This screenshot has expired, but this is a frontend issue, not a server one. @erosman can you please re-file over https://github.com/mozilla/addons-frontend ? Thanks. That new issue should probably filed as need ux to get UX input on this, they may disagree with you :)
