### ISSUE TITLE
CircleCI: Unify git checkout, use depth=1 for image builds

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7488]
As part of https://github.com/mozilla/addons-server/pull/7473 I started using `git clone --depth 1` for the ui tests and we should make use of that for our image builds directly too.

This would mean moving the cloning bit to a bash script and re-use it for every step.

**Comment by EnTeQuAk** [comment]
Fixed via #7473

**Comment by AlexandraMoga** [comment]
Could you please add a "qa:not needed" label if there's nothing expected from QA?
Thank you
