### ISSUE TITLE
Serve tailored content for China Edition on the disco pane endpoint

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7489]
Product have requested we serve a tailor-made set of content for the china edition audience. 

Content is here: 

https://docs.google.com/document/d/16Fh55WyjVLeYbNlRaE85dsV5hA5jQIRSojd2gGQaSK4/edit

* We'll need to define a query parameter that addons-frontend passes through to addons-server. This should be a 1 line change on the front-end. I've not filed a bug for that since it'll make sense to do taht when we know what to call it.
* This should ignore the TAAR experiments when this parameter is passed.
* The existing content for the disco pane should be un-affected by this change.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF58 (Win10x64)
- I've modified my dicoveryURL to https://discovery.addons.allizom.org/en-US/firefox/discovery/pane/58.0.1/WINNT/normal?edition=china
- here is the tailored Disco Pane content:
![image](https://user-images.githubusercontent.com/31961530/35907843-b8f0d0de-0bf7-11e8-9e9e-a0584c4fc498.png)

@eviljeff there is an extension missing (New Tab Override) but I assume this has to do with the fact that there is no correspondent on stage, right? We had such issues before but I believe it's better to double check just to be sure.

**Comment by eviljeff** [comment]
@AlexandraMoga the add-on exists on stage but under a different id - and we use a hard-coded id so yeah, it's not going to show up, that's okay.

**Comment by AlexandraMoga** [comment]
Thanks! In that case, I'm marking this as verified fixed.
