### ISSUE TITLE
Default sort option for 'My Themes' is by 'Name"

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7502]
STR:

1. Log into Developer Hub and go to the following link: https://addons-dev.allizom.org/en-US/developers/themes
2. Observe the default sort option

Actual result:
Themes are default sorted by Name 

Expected result:
Themes are sorted by Creation/Update date which would be more relevant and consistent with what we have for My Add-ons

Notes: Reproduced on all AMO servers, with FF58 (Win10)

![image](https://user-images.githubusercontent.com/31961530/35863514-903993ec-0b57-11e8-8c23-44319b0dde11.png)

**Comment by rafspiny** [comment]
This one should be an easy fix that I can pick up.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/38132651-90c5d88a-3414-11e8-83bc-2fe1f0c874cf.png)
