### ISSUE TITLE
After editing Basic information the old name of the add-on is still displayed on Edit information page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7504]
Steps to reproduce:
1. Load AMO dev and from Developer Hub go to Manage my Submissions.
2. Choose an  add-n from the list and Click on Edit information.
3. Change the Name from Basic Information section and click Save Changes.
4. Click on View Listing then go back to Edit information and observe the name displayed on the upper left side of the screen.

Expected results:
The name has changed.

Actual results:
The old name is still displayed.

Notes:
After the page is refreshed the new name will be displayed.
This issue is reproducible on AMO dev and AMO stage with FF58 (Win 10)

![updated](https://user-images.githubusercontent.com/33448286/35864243-e433b0de-0b59-11e8-901a-8a7987225789.gif)

**Comment by rafspiny** [comment]
Hi, what do you think is the best approach in this case? I was thinking about the following:
- Update the h2 tag on a successful __Basic information__ form submission
- Request another endpoint to retrieve the top-left quadrant information and update the view, if there is already such an endpoint.

Do you have anything else beside this very simple idea?

**Comment by diox** [comment]
There isn't a good endpoint to call to retrieve this information. Manually updating the h2 does not sound entirely terrible, so go for it if that's easy enough to identify what section was updated.

**Comment by rafspiny** [comment]
@diox It should be easy. I will apply the first solution then.

**Comment by diox** [comment]
Though this is annoying, it's a lot of work to fix with translations etc. We could automatically refresh the page or call an API just to get the name, but I don't think it's worth the effort for such a minor issue, so I'm wontfixing this.

**Comment by AlexandraMoga** [comment]
@diox  could you also add a wontfix label for this, please? Thank you
