### ISSUE TITLE
Special chars without text can be used in the Theme name field

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7506]
STR:
1. Load AMO dev and from Developer Hub submit a static theme using the Theme generator wizard.
2. In the Theme name* filed type two special characters or more but do not use letters.
3. Click on Finish Theme.
4. Observe the Name and Summary field on the next page.

Expected result:
A warning message should be displayed to use a valid name containing letters, numbers, underscores.

Actual result: 
A name of an already existing add-on is displayed in the Name Field. Summary is already filled in. 

Notes: 
This issue is reproducible on AMO dev with FF58 (Win10).

![special chars](https://user-images.githubusercontent.com/33448286/35869305-67b3d5ee-0b67-11e8-9c12-497a29fad340.gif)

**Comment by diox** [comment]
Is that a restriction we have elsewhere on the site ? I don't remember having something to prevent this elsewhere.

**Comment by eviljeff** [comment]
@ioanarusiczki the selecting of another add-on part is weird - is it always chatzilla?  And was the actual theme generated okay?  (I'm also wondering if the same thing would happen if you uploaded a zip file with a manifest that had the name with special characters in.)

**Comment by ioanarusiczki** [comment]
@eviljeff @diox  Hey,
1.  I did some more testing with this issue and it looks like things get very strange when I rename an add-on with special chars in the manifest too. It's not always chatzilla, actually every time it's a different add-on. The wizard has the same behavior if the steps of submissions are completed. 
-> I submitted a file with a manifest that contains only special chars in the name
-> On the second page of the submission in the name field another add-on is displayed also summary or other text fields are already filled in
-> I selected a category and license and clicked submit version 
-> when View listing is clicked after submission the user is redirected to an add-on (the one that appeared randomly on the second page during submission)
-> from Dev Hub - going back to Manage my submission the add-on is displayed as being in the submission process but resume clicked displays an empty page and delete won't work either

![2 special chars strange behavior](https://user-images.githubusercontent.com/33448286/37913179-f5a90fce-311c-11e8-9980-a1e878f761e5.gif)

resume/delete 
![resume delete](https://user-images.githubusercontent.com/33448286/37913239-17c82c34-311d-11e8-9bb9-ee276ce99fac.gif)



2. The Static Theme wizard - when the theme name field on the first page is left empty the finish theme button should be greyed out. This happens only after clicking the finish theme button.  I don't really see the use of this field because the second page has a Name field too. Should I file an issue to remove the Theme name field from the first page? 

![theme name field](https://user-images.githubusercontent.com/33448286/37913163-ec6260dc-311c-11e8-8a20-a8704baa3ec9.gif)

**Comment by ioanarusiczki** [comment]
As an update - I noticed now that the above behavior is for accounts with admin rights.
When using the scenario for an account without admin permissions the second page displays an error message while making a submission. Same behavior for the Static Theme Wizard.
This is reproducible on AMO dev and AMO stage with FF59(Win10).

![messages1](https://user-images.githubusercontent.com/33448286/38029612-f84a99ea-329e-11e8-83aa-dd9877aa6975.png)
![messages2](https://user-images.githubusercontent.com/33448286/38029620-ff422ab0-329e-11e8-9a57-6286a461675c.png)

**Comment by eviljeff** [comment]
I looked into this and the problem is down to slugs - the name is reduced to `""` (e.g. `"%$£"` as the add-on name, which is a valid name), if all the chars are invalid slug chars.   The most straightforward fix is to generate a random uuid style slug instead.  

The javascript in the detail step thwarts this though, by resetting the slug back to the name (once again ending up as "").   So, we can change the javascript to not change touch the slug, unless the developer has already started playing with it.   I doubt this is really a common scenario outside of QA testing and spamming.  The downside is potentially a few more submissions won't be prompted to change their slug in the detail slug, and will instead get a slug like `1234-1234-1234-12345` if the name only has nonsense characters (or the auto-generated `name1` when name isn't nonsense, but already exists).

fyi @jvillalobos

**Comment by jvillalobos** [comment]
The UUID solution sounds good to me.
