### ISSUE TITLE
Remove "search-use-dfs-query-then-fetch" flag in search

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7508]
I pushed an experiment using `search-use-dfs-query-then-fetch` last week which didn't turn out to be useful and had quite a bit of performance impact on our search API.

Let's remove this.

**Comment by AlexandraMoga** [comment]
Does this have an impact on the current search properties in AMO?

**Comment by diox** [comment]
It shouldn't : we removed code that was behind a flag that we never turned on.
