### ISSUE TITLE
Feb Disco Pane content update 

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#7510]
For the **22 February** push, can we please REMOVE: 

- uBlock Origin
- LastPass
- Enhancer for YouTube
- all three current themes

... and REPLACE them with To Google Translate, Search by Image - Reverse Image Search, Video DownloadHelper, plus three new themes:

**Translate easily** with [To Google Translate by Juan Escobar](https://addons.mozilla.org/firefox/addon/to-google-translate/)
Highlight any text, right-click, and translate instantly. 

**Reverse image search** with [Search by Image by Armin Sebastian](https://addons.mozilla.org/firefox/addon/search_by_image/)
See an interesting picture on the Web and want to learn more about it? Try this image search tool. 

**Download videos** with [Video DownloadHelper by mig](https://addons.mozilla.org/firefox/addon/video-downloadhelper/)
Works with YouTube, Facebook, Vimeo, Twitch, Dailymotion, Periscope, and hundreds of other video sites. 

[Themes]

Swirley Purple by [Thamyrus](https://addons.mozilla.org/firefox/addon/swirley-purple/)

Eco Theme by [McSimych](https://addons.mozilla.org/firefox/addon/eco-theme/)

Light Up the Morning by [MaDonna](https://addons.mozilla.org/firefox/addon/light-up-the-morning/)

Full page content lineup should reflect like so:

Swirly Purple
To Google Translate
Search by Image
Eco Theme
Video DownloadHelper
Emoji Cheatsheet
Light Up the Morning

@muffinresearch @EnTeQuAk

**Comment by ioanarusiczki** [comment]
I verified this with FF58 (Win10).  
@diox I don't see Emoji Cheatsheet and Light Up the Morning from the above list but instead below the Download videos I get a red banner with the message This add-on does not support your browser. 
Could you please confirm that this is as expected ?

![disco pane](https://user-images.githubusercontent.com/33448286/36374052-b86b7bbc-1572-11e8-8350-2cdbdcf7799c.png)

**Comment by EnTeQuAk** [comment]
I feel like this could be because of the recommendation engine that's also involved maybe? With my set of add-ons, I can see the missing ones on your machine. I'm not to sure about the incompatible recommendation though, that should be a bug imho, TAAR should not return such thing.

**Comment by EnTeQuAk** [comment]
I could be completely wrong but if you disable all telemetry stuff in your Firefox settings I think you should see an untampered list.

**Comment by diox** [comment]
@ioanarusiczki where are you testing? dev?

Disco Pane updates are always tricky to test as the add-ons they are referencing may not exist on dev/stage, or may not be in the same state as prod's.

**Comment by ioanarusiczki** [comment]
@diox Hi! This is from AMO dev. Is the message displayed because it could not find an equivalent to match with for Emoji and the Light up theme?

**Comment by diox** [comment]
No, missing add-ons are ignored. The message is displayed because on dev specifically, Video DownloadHelper is not compatible with your version of Firefox.

**Comment by ioanarusiczki** [comment]
Ok, then I'll mark it as verified fixed.  
Thanks!
