### ISSUE TITLE
Only wrap URLs with outgoing.prod.mozaws.net in the API if a specific query parameter is present

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#7513]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

Retrieving addons details using eg the search api, any non-AMO URLs in the result (eg homepage_url, support_url, etc) are wrapped with `https://outgoing.prod.mozaws.net/...`. 

### What did you expect to happen?
I expected to get an unwrapped URL, eg `https://github.com/gorhill/uBlock#ublock-origin` for uBO as opposed to `https://outgoing.prod.mozaws.net/v1/788d66e7299bdfb1da05832994551640d0ad441e148a3e29afe8dd0a5a90800c/https%3A//github.com/gorhill/uBlock%23ublock-origin`.  I get that the front-end needs to wrap URLs (actually I don't, but I trust there's some good reason) but it seems like the front-end should be doing that wrapping, it shouldn't be part of the API results.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
I don't like it either, but it was done that way on purpose: the frontend can't do the wrapping itself because it needs a secret key to do that (to prevent people from using `outgoing.prod.mozaws.net to` execute arbitrary redirects), and keeping that key secret on the client side is not possible.

**Comment by aswan** [comment]
Well this doesn't sound great but can we make it optional based on a query parameter or something?  With the wrapping in place the API is quite tied to the AMO front-end and much more difficult to use for other clients.

**Comment by diox** [comment]
We can, yeah. Edited the title of the issue to reflect that.

**Comment by aswan** [comment]
For what its worth, I think that most users of the API that aren't the AMO frontend probably don't want the wrappers so making that the default and having the presence of the option force the wrappers to be added would be nice, but up to you...

**Comment by diox** [comment]
Yeah, that's a good point. We need to get the frontend to send us that parameter.

**Comment by EnTeQuAk** [comment]
Any opinions about naming? Let's call this `force_outgoing_links` maybe?

**Comment by diox** [comment]
`wrap_outgoing_links` maybe?

**Comment by kumar303** [comment]
> I expected to get an unwrapped URL, eg https://github.com/gorhill/uBlock#ublock-origin for uBO as opposed to https://outgoing.prod.mozaws.net

@aswan What's the rationale for this change request? Privacy? The outgoing server gives us an opportunity to warn about phishing attempts and also a central location to address malicious links. However, I'm not aware that we've ever employed that functionality.

**Comment by aswan** [comment]
Discussed in IRC, but Firefox uses the search API to gather addon metadata that is presented in about:addons.  Without this change, the homepage is totally obscured in the addons details:

![screen shot 2018-02-15 at 9 25 39 am](https://user-images.githubusercontent.com/3308522/36271397-5edb3160-1233-11e8-8b9e-47607d94f7fe.png)

**Comment by muffinresearch** [comment]
@diox is that the right milestone? Looks like the frontend patch is ready to go.

**Comment by diox** [comment]
It is. I don't want to push both the API and the frontend at the same time, because then if the API is deployed first, we'll get responses without the wrapping for a short while. So I've planned to push the API part next week to be on the safe side.

**Comment by kumar303** [comment]
This frontend change has landed: https://github.com/mozilla/addons-frontend/pull/4408

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58, Win10x64

- with wrap parameter set

![image](https://user-images.githubusercontent.com/31961530/36596021-fcc6b2e4-18ac-11e8-960f-b4242940d209.png)



 - without wrap parameter

![image](https://user-images.githubusercontent.com/31961530/36596029-03e7fda8-18ad-11e8-8ecf-4c00e7846ccf.png)
