### ISSUE TITLE
New API only returns a single icon

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#7514]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Searched for addon details with the new search API, the result includes a single `icon_url` property.

### What did you expect to happen?
The old search API returned a list of icons, that looked something like
```
<icon size="32">https://addons.cdn.mozilla.net/user-media/addon_icons/blah32.png</icon>
<icon size="64">https://addons.cdn.mozilla.net/user-media/addon_icons/blah64.png</icon>
```
I expected the new API to also include all the available icons.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
64 pixels should be enough for everyone!

Yeah, not sure what I was thinking when I wrote it. We currently generate a bunch of sizes: 32, 48, 64, 128, 256, 512. I'm not sure if we need all that... Also, changing this without breaking existing clients is going to be annoying.

**Comment by eviljeff** [comment]
good thing the v3 is still "experimental" 😆  - we just need addons-frontend to support both a single icon and a size:path dict first.  I'll log an issue.

**Comment by diox** [comment]
32, 48, 64 appear to be the only sizes that are actually working, at least for the add-ons I'm testing with. Since the legacy API was returning only 32 and 64, I suggest that the v3 API only return those 2 sizes as well, and we can figure out what to do about the other sizes afterwards.

**Comment by diox** [comment]
I think we can add a new `icons` field to the response, and not touch the `icon` one. We'd eventually drop `icon` entirely, but that enables us to implement it without waiting for the frontend.

So, it would look like this:
```
"icons": {
  "32": "https://addons.cdn.mozilla.net/user-media/addon_icons/1/1865-32.png?modified=1516707961",
  "64": "https://addons.cdn.mozilla.net/user-media/addon_icons/1/1865-64.png?modified=1516707961"
}
```

**Comment by eviljeff** [comment]
Yeah, added on `icons` - it's accurately named too.

I found from testing yesterday that all the icon sizes were generated when i selected a new icon for an existing listing. I don't know how long that's been true for though.

**Comment by eviljeff** [comment]
Yes, and we don't really want to upscale all the existing 64x64 icons to 512. 

Really the feature is broken - we say 64 is the max in devhub (so that's probably the max size uploaded by a Dev); then resize them anyway. It's quite likely all the icons at 128, 256, 512 are useless therefore -we should probably just delete them.

**Comment by diox** [comment]
I agreed. Moving this discussion to #5805 :)

**Comment by AlexandraMoga** [comment]
Verifed on AMO dev, with FF58, Win10x64

Checked with the following add-on and the new `icons` property is returned; the old `icon_url` property is also present:
```
https://addons-dev.allizom.org/api/v3/addons/addon/adblock-plus-test/

```
![image](https://user-images.githubusercontent.com/31961530/36311897-76348f84-1335-11e8-84e1-e1616548bb07.png)
