### ISSUE TITLE
Remove "Contains Reviewer Comment" flag

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7516]
When a reviewer posts a comment for other reviewers (not for the developer) in reviewer tools, it's shown in the activity log for reviewers, but not developers. In addition, a flag is stored and displayed in the queue for the add-on, indicating that it contains a reviewer comment.

I'm wondering how useful the flag is - essentially it will only be shown in the queues the add-on appears in. It's stored on the version and is a bit wasteful. Can it be dropped or is it still useful?

**Comment by diox** [comment]
Side note: is the reviewer comment functionality still useful now that reviewers have a private dashboard?

**Comment by wagnerand** [comment]
Generally, the reason why we have a dashboard vs comment is that they serve two different use-cases: Comments are version specific, the dashboard contains information that is not specific to a particular version.

We might be able to remove comments, but the private dashboard lacks a few important features:
* When a comment was added
* Who added it
(* Ability to prevent removal of some comments in the dashboard).
Of course, this is pretty far out and hasn't even been properly scoped yet.

**Comment by diox** [comment]
Thanks, that clarifies this bit. Completely replacing it with the private whiteboard is clearly out of scope then. (The question about keeping the flag which appears in the queues still remains)

**Comment by wagnerand** [comment]
> The question about keeping the flag which appears in the queues still remains.

I don't believe it has still a high value.

@kewisch and  @jvillalobos might have an opinion as well.

**Comment by jvillalobos** [comment]
Removing the flag from the queue view is fine with me.

**Comment by AlexandraMoga** [comment]
I've checked  AMO -dev but I'm still seeing a reviewer comment flag, with its specific icon, when looking in the auto-approved add-ons queue for example.
This is a comment I've just added:

![rev comment](https://user-images.githubusercontent.com/31961530/44096087-151ffe8c-9fe3-11e8-9e93-8c594e034e71.gif)


@eviljeff is there a chance that this hasn't landed on dev yet?

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![no comment](https://user-images.githubusercontent.com/31961530/44100007-a2c1bc86-9fec-11e8-9f24-e2a70ddf8c9a.gif)
