### ISSUE TITLE
Docker images exit on restart (Error 137)

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7518]
This is the best error I got so far:

```
+ docker-compose exec web supervisorctl restart all
Exited with code 137

Hint: Exit code 137 typyically means the process is killed because it was running out of memory
Hint: Check if you can optimize the memory usage in your app
Hint: Max memory usage of this container is 0
 according to /sys/fs/cgroup/memory/memory.max_usage_in_bytes
```

@muffinresearch had the great idea that it might be because of how signals handled which I'll investigate a bit more too.

This started to fail when we moved to our debian based docker images.

**Comment by kumar303** [comment]
I run into this every time I try to update docker. Erasing all containers and recreating the Docker env seems to work fine.

I have looked in all the logs I can find and these are the only suspicious entries. It doesn't point out anything obvious though.

rabbitmq: https://pastebin.mozilla.org/9077537 (connection_closed_abruptly)
mysql: https://pastebin.mozilla.org/9077538 (Got an error reading communication packets)

**Comment by philipcristiano** [comment]
Using `stopasgroup=false` in the supervisor config I was unable to reproduce the problem. I don't know if this will cause other problems, if there are other child processes running that aren't cleaned up.

**Comment by AlexandraMoga** [comment]
Could you please add a "qa:not needed" label to this issue?
Thank you
