### ISSUE TITLE
Be consistent and have theme category URLs end in "/"

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7524]
see https://github.com/mozilla/addons-frontend/issues/4252 for background.

**Comment by jrbenny35** [comment]
What would need to be done for this?

**Comment by eviljeff** [comment]
I'm not 100% certain but changing the regexs that relate to themes in https://github.com/mozilla/addons-server/blob/master/src/olympia/browse/urls.py#L22:L92 is where I'd start.

**Comment by jrbenny35** [comment]
I was able to get this working adding this url : ```url('^themes/(?:(?P<category>[^ /]+)/)?$', views.personas, name='browse.personas'),``` 

However I must keep the existing url ```url('^themes/(?P<category>[^ /]+)?$', views.personas, name='browse.personas'),``` for the url at ```themes/``` to work.

Any tips or something I'm missing?

**Comment by eviljeff** [comment]
you should be able to combine that into a single regex

**Comment by jrbenny35** [comment]
I think when I use the first example the category of ```None``` doesn't get passed so django returns a 404.

**Comment by eviljeff** [comment]
maybe your regex is wrong :)
Actually, you shouldn't need the non-`/` variant - there is a middleware class that adds a slash to any url that would otherwise 404.  Just changing the regex to the new one should be enough.

**Comment by eviljeff** [comment]
@jrbenny35 did you finish this?
