### ISSUE TITLE
Add URL for reviews to search results

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#7534]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
about:addons uses the search api to get the detailed results to display, but as described at https://bugzilla.mozilla.org/show_bug.cgi?id=1437068#c2, that url is not present in the new api.  I really don't want to put logic about constructing these urls into the client, please add a new field to the search results that includes a link to the reviews.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Since the v3 API will be frozen soon, should be called `ratings_url` while we still have a chance to do this right...

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, Win10x64
The `ratings_url` property was added in the API and redirects to addon user reviews while `review_url` redirects to reviewer tools
@diox - should this change have any impact on addon reviews? Would be worth to look for regressions in this area?

![image](https://user-images.githubusercontent.com/31961530/36384955-bc2bdf2c-1599-11e8-9845-20c9531fb857.png)

**Comment by diox** [comment]
It should not have, no. It was relatively straightforward, just adding a property, so I don't expect any regression in addon reviews.

**Comment by AlexandraMoga** [comment]
Thank you!
In this case I'm marking this issue as verified fixed.
