### ISSUE TITLE
A logo inconsistency is observable on the first page when submitting an ad-on versus a theme  

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7544]
Prerequisites:
User is logged in

STR:
1. Load AMO dev and hover over the username and open the drop down menu.  
2. Click Submit a new add-on from Tools.
3. Observe the Add-on Developer Hub logo and click on it.
4. Load AMO dev and click on Submit a new theme from Tools.
5. Observe the logo and click on it.

Expected result:
In both cases the Developer Hub logo is displayed and user is redirected to Dev Hub homepage.

Actual result:
For themes Add-ons logo is displayed and the user is redirected to AMO homepage.

Notes:
This issue is reproducible on all AMO servers with FF58 (Win10).

![inconsistency](https://user-images.githubusercontent.com/33448286/36105271-daac0d1e-101c-11e8-9ffe-ff140d0a514b.gif)

**Comment by eviljeff** [comment]
The old theme wizard for LWT has been disabled now
