### ISSUE TITLE
https://addons.mozilla.org/en-US/firefox/addon/cryptonite-by-metacert/

### ISSUE THREAD

**Issue by AdiProdan** [mozilla/addons-server#7551]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
https://addons.mozilla.org/en-US/firefox/addon/cryptonite-by-metacert/
This extension is for some reason missing..

### What happened?
Page says: "Sorry, but we can't find anything at the address you entered."

### What did you expect to happen?
I expected to find the add-on

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
This add-on has been disabled by reviewers because of a couple issues with it. Once they are fixed by the author(s) it will return.

**Comment by AdiProdan** [comment]
Awesome reply time, thanks!!
