### ISSUE TITLE
Drop `info_request` field from `Version`

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7555]
In #7283 the `info_request` field will be replaced by a `pending_info_request` field on `AddonReviewerFlags`.

To ensure a clean migration, we'll do the usual:
- Drop the field from the model, keeping the database column (On dev/stage/prod `Version.info_request` already has a default in the database)
- In a push after that one, drop the column

**Comment by AlexandraMoga** [comment]
@diox what exactly is the impact of this change? Where should we focus our attention?

**Comment by diox** [comment]
There should be no impact to production. I've just marked the bug as not needing qa.
