### ISSUE TITLE
Pressing Enter will disable the submission process instead of finish it 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#7556]
Steps to reproduce:
1.Go to dev hub and start a submission for a new webextension
2.After a successful validation, press "Submit version" button without completing all mandatory fields(ie. categories or change the slug if it was used before)
3.Complete the mandatory fields and press Enter keyboard button

Expected results:
The webextension is successfully submitted

Actual results:
Submission is cancelled and webextension is in an incomplete state

NOTES:
Tested using Windows 10x64, FF Release, AMO-dev
Reproducible on all servers

Please see video for this bug(Enter was pressed at the end of video) : 
![enter](https://user-images.githubusercontent.com/1583842/36156451-c120a8c8-10df-11e8-9df4-ca32a0638436.gif)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

![2018-12-06_13-21-47](https://user-images.githubusercontent.com/31961530/49581827-dffc6380-f95b-11e8-98ae-54f2a9a5d5cc.gif)

Also, the button order has changed in all the submission flows:
![image](https://user-images.githubusercontent.com/31961530/49581954-3cf81980-f95c-11e8-83cd-6056853ef005.png)

![image](https://user-images.githubusercontent.com/31961530/49581963-42556400-f95c-11e8-8073-40d6d2520779.png)
![image](https://user-images.githubusercontent.com/31961530/49581969-46818180-f95c-11e8-86c8-68d35b0b35b2.png)
