### ISSUE TITLE
User reviews count from Add-ons manager is inconsistent with the new frontend

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7557]
STR:

1. Access AMO homepage and install an extension that has both written and empty reviews (i.e. https://addons.mozilla.org/en-US/firefox/addon/open-via-idm-manager/)
2. After the installation is complete, go to about:addons and check the installed add-on in the Extensions tab
3. Click on 'More' to see additional details for this add-on and observe the number of reviews displayed 
4. Click on <# reviews> link to read all the reviews associated with this extension

Actual result:
The number of reviews displayed in addon reviews page does not match the number observed in add-ons manager

Expected result:
Since the new frontend is not counting empty reviews , the same should happen in addons manager

Notes:
- if, for example, all reviews available for an installed add-on are deleted from AMO, add-ons manager will still show a link to the reviews page displayed as "0 reviews"; in such cases, this link should not be present
- reproduced on all AMO servers with FF58, Win10x64
- similar issue reported here - [#639](https://github.com/mozilla/addons/issues/639)

![reviews addons manager](https://user-images.githubusercontent.com/31961530/36157688-0c6d3ffa-10e3-11e8-8d74-85580b6d7f0c.gif)
<br>
![image](https://user-images.githubusercontent.com/31961530/36157722-22ff963c-10e3-11e8-82f2-874b2c52e10c.png)

**Comment by eviljeff** [comment]
This would require a breaking change in the legacy (1.5) API and potentially changes in Firefox code (Add-on Manager is _not_ part of AMO).  Firefox 60 (in Nightly now) is expected to have a rewritten Add-on Manager which will use the newer 3.0 API, where both rating count with text reviews, and without is available.
