### ISSUE TITLE
Use Scandir to speed up our os.walk usage

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7561]
One of our dev dependancies uses scandir and the description implies it's double++good
https://github.com/mozilla/addons-server/pull/7549
We should use it in prod code too (?)

**Comment by CuriousLearner** [comment]
@eviljeff The scandir functionality is already added in CPython for 3.5+. So, what exactly needs to be done here and what is the version of Python we prefer on add-ons server?

**Comment by diox** [comment]
We are still using Python 2.7.x currently. This issue is about replacing our usage of `os.walk` in our python code with the version that comes from `scandir`.

**Comment by CuriousLearner** [comment]
@eviljeff @diox I've raise a PR for this :)

**Comment by AlexandraMoga** [comment]
Please add some STR or the label 'qa:not needed'
Thank you

**Comment by eviljeff** [comment]
@CuriousLearner thanks for the fix!

**Comment by CuriousLearner** [comment]
Yay! Thanks @eviljeff for the quick reviews :)
