### ISSUE TITLE
Compare search results add-on data to add-on detail data

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7563]
The API exposes add-on detail data in [search results](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search) but the frontend doesn't make much use of this. It always loads all data from the [detail endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail) because it needs a few fields that are missing from search results. For example, it needs version notes and some info about licenses.

We should re-evaluate how much add-on data is included in search results. We'll need to keep in mind planned future features such as showing install buttons in search results.

**Comment by diox** [comment]
Are `previews` needed for search results? If not, will they ever be? It's be nice to be able to drop them from ES entirely.
