### ISSUE TITLE
Blank name personas with no versions are returned as search results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7599]
STR:

1, Send a search request that will return themes, sorted by name:
 ```
GET https://addons-dev.allizom.org/api/v3/addons/search/?sort=name&type=persona/
```
2. Observe the search results listed on the first 8 pages

Actual result:
A list of themes with blank names and no versions is displayed

Expected result:
A list of themes correctly sorted by name is displayed

Notes:
Reproduced on AMO dev, FF58, (Win10x64)

Here is how the results look on the frontend: https://addons-dev.allizom.org/en-US/firefox/addon/-180276/

![image](https://user-images.githubusercontent.com/31961530/36381800-6846f752-158f-11e8-8d3d-cadb9a844ca0.png)

**Comment by diox** [comment]
Weird enough that it should be looked at.

**Comment by muffinresearch** [comment]
@AlexandraMoga can you reproduce this on production at all?

**Comment by AlexandraMoga** [comment]
@muffinresearch yes, I can see his behavior in production as well, both in the API and on the frontend.

Here is an example from prod:
https://addons.mozilla.org/en-US/firefox/addon/-40913/?src=search
![image](https://user-images.githubusercontent.com/31961530/37206690-6cd2b0e2-23a2-11e8-85ba-61dd1bc2bb60.png)

**Comment by diox** [comment]
I've been digging into this a little and those themes are super old, and although they have a blank name, they are working in the legacy site. The API does return all necessary data for them (their slug is a little weird, but should work). So I'd say it's a frontend bug rather than a server bug - I'm not sure what we could do on the server side regarding their names...

**Comment by diox** [comment]
Side note: I don't know if that was done on purpose, but on the legacy site, it's almost impossible to search lightweight themes and order the result by name (it's easy for every other type of add-on).

**Comment by diox** [comment]
I noticed that although the legacy frontend is able to display the page, installing or previewing the theme does not work, because of the empty name. I'm going to add a dummy "Untitled" name to them, which the API will return as well, and see if that fixes it.

**Comment by diox** [comment]
Note that although fixing their name will fix the theme on the legacy site, the new frontend has another issue because of the slugs https://github.com/mozilla/addons-frontend/issues/4541

**Comment by AlexandraMoga** [comment]
I've verified theme search with AMO-dev on the legacy site and a list of "Untitled" themes is now returned when ` sort=name`. The themes can be previewed and installed.

![image](https://user-images.githubusercontent.com/31961530/37525075-6b20f500-2934-11e8-8e1e-beeb83448d18.png)


@diox when searching in the API, theme name is still returned as a `null` value. I thought I was supposed to be "Untitled"

**Comment by diox** [comment]
@AlexandraMoga I haven't bothered to reindex so the search API will still return the empty name. As long as the frontend issue still exist there is no point in doing the reindex to fix the search API.

**Comment by AlexandraMoga** [comment]
Ok, in that case I'm marking this as verified for fixing theme search on the legacy site.
For the remaining issues, I'll wait for a fix to land in [addons-frontend/issues/4541](https://github.com/mozilla/addons-frontend/issues/4541)

Verified on AMO-dev, FF59 Win10x64
