### ISSUE TITLE
"Esc" key doesn't work to get out full screen view for addon screenshots on Listed Review Page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7611]
STR:
1. Load AMO dev and from Developer Hub go to Manage My submissions.
2. Click on Edit information below a submitted static theme.
3. Click the image displayed below the name of your theme.
4. Try to close it using "Esc" from your keyboard.
5. Click an image from Image Gallery and try to close it using "Esc" key.

Expected results:
The image is no longer displayed on screen.

Actual results:
Nothing happened. 

Notes:
This issue is also reproducible on Unlisted Review Page.
This issue is reproducible on AMO dev with FF58(Win10). 

![listed review page](https://user-images.githubusercontent.com/33448286/36433499-555467a2-1665-11e8-9ea8-4a87f5b5c4b1.png)

**Comment by eviljeff** [comment]
is this _just_ happening for static themes?  It seems odd it wouldn't be same for other addon types.
Fwiw Static Themes will have their own review tools anyway but I'm interested to know if there is something special about the `Preview` records created.

**Comment by ioanarusiczki** [comment]
When I filed this issue I was testing the screenshot implementation for static themes but I checked again now and the issue is reproducible for other add-on types too when screenshots are added. (verified with FF58, Win10x86).

I'll update the name of this issue.
