### ISSUE TITLE
No action triggered in Add-on review history when developer uses "This request for information has been resolved'' checkbox

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7623]
Follow up for [#7283](https://github.com/mozilla/addons-server/issues/7283#issuecomment-367027273)

STR:

1. Log in to Reviewer Tools with an Admin account
2. Go to Auto-Approved add-ons queue and pick an add-on to review
3. Use the Reviewer reply action, mark the 'Request more info' checkbox and Save your review
4. Access the DevHub page for the add-on you just reviewed and submit a new version
5. In the final submission step, mark "This request for information has been resolved'' checkbox
6. Go back to the add-on review page and check if the developer response appears in Add-on review history

Actual result:
There is no entry in Add-on review history to mention that the developer used "This request for information has been resolved'' checkbox - see example https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/wed-31-18

Expected result:
A developer response should be visible in Add-n review history

Notes:
- reproduced on AMO-dev, with FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/36479608-f39e278e-1711-11e8-9309-bc5f4dd1be9e.png)

**Comment by diox** [comment]
@AlexandraMoga have you retested that today ? I've made a fix for this late yesterday.

**Comment by AlexandraMoga** [comment]
Retested today by using the clear information request checkbox available in the version edit page and a developer response was displayed in add-on review history:

![image](https://user-images.githubusercontent.com/31961530/36480453-0d2b791a-1715-11e8-96e4-0ea4b49521fd.png)
