### ISSUE TITLE
Screenshot previews for static themes are not centered on Listed review page 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7624]
STR: 
1. Load AMO dev and from Dev Hub go to Manage My submissions.
2. From My Themes tab click on edit information for a static theme with multiple versions.
3. Click on Listed review page.
4. Click the image displayed below the name of the theme and observe layout.
5. Click an image from Image Gallery and observe layout.

Expected results:
The screenshot is centered.

Actual results:
The screenshot is displayed in the upper part of the screen. 

Notes:
This issue is reproducible on AMO dev with FF58 (Win10).
This issue is also reproducible on Unlisted review page.

![screenshots in reviewers pages](https://user-images.githubusercontent.com/33448286/36479712-4f457cae-1712-11e8-8c29-41e614ca76ea.gif)

**Comment by eviljeff** [comment]
Probably because they're a different size to standard screenshots.

As static themes are going to use custom reviewer tools (similar to the existing LWT tool, rather than the extension ones) this won't be a bug there so going to close.
