### ISSUE TITLE
Prevent non-images to be uploaded through user photo or collection icon

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7635]
Through the add-on previews/icons upload code does check that the uploaded content is indeed an image (and not animated), the user photo and collection icon ones don't. Ultimately it's not a very big deal as it will get cleaned up later by the `gc` cron since we won't be able to resize them, let's prevent those broken uploads in the first place.

**Comment by AlexandraMoga** [comment]
@diox until now the user photo and collection icon allowed only .jpg and .png uploads. I'm not sure I understand what changed exactly with this new feature.

**Comment by diox** [comment]
@AlexandraMoga the code didn't completely prevent this before - we only checked the mime type sent by the browser, which could be crafted, allowing someone to send a non-image. 

If you want to check this thoroughly you'll need to be able to craft an arbitrary request to the server (or modify an existing one created by your browser) to send a non-image with an `image/png` content type. Just verifying that image uploads still work and non-image are still rejected is probably fine, though.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58 Win10x64

Uploading an image file (i.e. .jpg and .png) for the user photo and the collection icon is working as expected.
Non-image files are rejected.
