### ISSUE TITLE
Only show queue tabs the reviewer has permissions for

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-server#7640]
The reviewer queue tabnav bar shows tabs that some reviewers don't have access to. The tab bar should be updated to adhere to permissions. See:
https://github.com/mozilla/addons-server/blob/360517b91eaf4311cf3f1c5c972014c9badd550e/src/olympia/reviewers/templatetags/jinja_helpers.py#L68-L115

We should add in checks for legacy reviewer permission, and moderated reviews permissions.

**Comment by kewisch** [comment]
QA: Check the reviewer tools tab strip that shows the queues with different permission sets:
* legacy reviewer
* post-reviewer
* ratings moderation reviewer
* content reviewer
*

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58 Win10x64

Tested with each permission individually and then with several combinations.
Below is a view for a user with `Addons:Review` and `Ratings:Moderate` permissions
![image](https://user-images.githubusercontent.com/31961530/36717474-e1fb6840-1ba6-11e8-9945-7b919fd35d1d.png)
