### ISSUE TITLE
500 error when visiting a beta versions listing page when beta versions are disabled.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7641]
STR:
1. Make sure the `beta-versions` waffle is disabled.
2. Go to a beta versions listing page, e.g. https://addons-dev.allizom.org/en-US/thunderbird/addon/lightning/versions/beta

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/2760044/

**Comment by vcarciu** [comment]
Verified as fixed: 
![betaver](https://user-images.githubusercontent.com/1583842/36603486-929e1616-18c3-11e8-945b-b0b83c6f872f.png)
