### ISSUE TITLE
Incorrect spelling of `submit` for button type

### ISSUE THREAD

**Issue by SeanPrashad** [mozilla/addons-server#7652]
### Describe the problem and steps to reproduce it:
Whilst figuring out #7405, I ran across a piece of code that has `sumbit` as the type for a button instead of `submit`.

### What happened?
N/A

### What did you expect to happen?
N/A

### Anything else we should know?
The source file in question can be found here:

https://github.com/mozilla/addons-server/blob/82a9e8cab26248c4ef4323922d85760b5592521e/src/olympia/devhub/templates/devhub/addons/submit/wizard.html#L80

**Comment by eviljeff** [comment]
QA:
check both the "Cancel and Disable Version" buttons in the upload flow, and the static theme wizard's "Back" button work as before.

**Comment by AlexandraMoga** [comment]
I've looked for regressions around the affected buttons and everything seems to be working normal.

I'm going to mark this as verified, on AMO-dev, FF58, Win10x64.
