### ISSUE TITLE
Prevent changing the extension type from Admin Settings in devhub

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7657]
STR:
1. Load AMO dev and from Dev hub go to Manage My Submissions.
2. Click on Edit information for a submitted add-on.
3. From Admin Settings change the add-on type from Extension to Theme.
4. Go back to Manage my submissions and try to access My Themes tab.

Expected result:
My Themes tab is displayed.

Actual result:
Oops! We had an error. The content of the theme tab is not visible.

Notes:
This issue is reproducible in AMO dev with FF58 (Win10).

![oops](https://user-images.githubusercontent.com/33448286/36676633-dc36bfd2-1b14-11e8-883f-22acbd3fb400.gif)

**Comment by vcarciu** [comment]
The user profile will return "Oops..." page too after following the same steps. Not reproducible for other profiles.

**Comment by diox** [comment]
Not sure I consider this a bug. Changing the add-on type is not exactly an action that one can make lightly. It *will* break things depending on the add-on, because files etc will be missing.

**Comment by eviljeff** [comment]
I'm going to fix this by [re]moving the admin only settings from devhub.  You will only be able to make those kind of breaking changes from django admin in future (where you really should know better)

**Comment by ioanarusiczki** [comment]
Admin section is no longer available in dev hub - verified on AMO dev with FF60(Win10)
It can (but won't) be made from django admin.

![django admin](https://user-images.githubusercontent.com/33448286/41910079-515b6066-7951-11e8-992a-4310c4cdd764.png)

**Comment by eviljeff** [comment]
@ioanarusiczki I also removed the other admin settings in devhub too - the only thing that wasn't already present in /admin/ was `reputation`
