### ISSUE TITLE
Cachebust Personas images with the Persona checksum

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7658]
We already compute and store a `checksum` for each `Persona` object, but for their images (footer, header, thumbnail) we still used the related `Addon` `modified` field as a cachebusting string. Let's use the `checksum` instead.

Do this after #7406 goes in production to avoid users/CDN caching the non-crushed version.

Similar to #2659 which implemented cachebusting based on icon hashes for add-ons.

**Comment by diox** [comment]
Patch is going to be something like:
```#diff
diff --git a/src/olympia/addons/models.py b/src/olympia/addons/models.py
index b58a723..5a7fe4f 100644
--- a/src/olympia/addons/models.py
+++ b/src/olympia/addons/models.py
@@ -1554,8 +1554,9 @@ class Persona(caching.CachingMixin, models.Model):
     def _image_url(self, filename):
         host = jinja_helpers.user_media_url('addons')
         image_url = posixpath.join(host, str(self.addon.id), filename or '')
-        # TODO: Bust the cache on the hash of the image contents or something.
-        if self.addon.modified is not None:
+        if self.checksum:
+            modified = self.checksum[:8]
+        elif self.addon.modified is not None:
             modified = int(time.mktime(self.addon.modified.timetuple()))
         else:
             modified = 0
```

**Comment by diox** [comment]
Also: `approve_rereview()` in `reviewers/tasks.py` needs to recalculate the theme checksum, like the `save_theme` task in `addons/tasks.py` does. That probably just means importing and calling `theme_checksum()` with the persona instance.

**Comment by diox** [comment]
QA:
- Create a theme (not a static theme, a Persona-style theme)
- Make sure the images work, note their URLs
- Modify the theme metadata.
- Make sure the images still work: the URLs should not have changed.
- Submit an update to that theme, and approve it.
- Make sure the images are updated, the URL should not have changed.

Regarding URL change, what you want to pay attention to is the `modified=` query parameter.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF58 Win10x64

Imag URLs:
- after upload:
[https://addons-dev-cdn.allizom.org/user-media/addons/495387/preview.png?**modified=7e3ec1a4**](https://addons-dev-cdn.allizom.org/user-media/addons/495387/preview.png?modified=7e3ec1a4)
- after some meta changes:
[https://addons-dev-cdn.allizom.org/user-media/addons/495387/preview.png?**modified=7e3ec1a4**](https://addons-dev-cdn.allizom.org/user-media/addons/495387/preview.png?modified=7e3ec1a4)
- after theme update:
[https://addons-dev-cdn.allizom.org/user-media/addons/495387/preview.png?**_modified=e48eb5b6_**](https://addons-dev-cdn.allizom.org/user-media/addons/495387/preview.png?modified=e48eb5b6)


@diox 
> Submit an update to that theme, and approve it.
> Make sure the images are updated, the URL should not have changed

You can see above that the image URL _has changed_ after the theme has been updated, while you mentioned it should not.

**Comment by diox** [comment]
My bad, it definitely should change when there is an update (the only time it should change). So your test verifies that everything works as expected.

**Comment by AlexandraMoga** [comment]
@diox, thanks for clarifying that part.
This can be marked as verified fixed then.
