### ISSUE TITLE
Update signing-clients to 1.5.0 for SHA2 manifest hashes

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7668]
Update signing-clients to 1.5.0 to add SHA2 support to manifest hashes.

See https://github.com/mozilla/signing-clients/commit/1a00de847c5da549b398ca5d0acaed8a9803d278 for more details.

Refs #4933

**Comment by vcarciu** [comment]
This issue was verified according to a set of tests discussed with @EnTeQuAk . All tests were passed. Marking issue as verified.
