### ISSUE TITLE
Users with Reviewers:Admin permission do not have visibility to add-ons with 'Needs Admin Review' flag

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7673]
Prerequisites: have a user account with at least  the following reviewer permission sets: `Addons:Postreview, Addons:ContentReview, Reviews:Admin`

STR:

1. Log in to Reviewer Tools with an account including the permissions mentioned above
2. Select the Auto-Approved add-ons queue from the dashboard
3. Observe the add-ons currently pending for review in the auto-approved queue

Actual results:
Add-ons flagged for Admin review are not listed among the available add-ons

Expected result:
Users with `Reviews:Admin` permission should have visibility to add-ons pending for admin review

Notes:
- the same applies to Content review queue
- @jvillalobos when reading the [Reviewers PRD](https://docs.google.com/document/d/1Me-2Qx-C7cMptKQt_-1gAyPZCBOiww9laQLEMlD9N2M/edit#)  I was under the impression that the Reviews:Admin permission should allow this action. Please let me know if what was observed above is actually expected?
- reproduced on AMO-dev and stage with FF58 Win10x64

[1] auto-approved queue for 'Admin' users

![image](https://user-images.githubusercontent.com/31961530/36780895-fe5bd43a-1c7c-11e8-854a-3186ce8e471e.png)

[2] auto-approved queue for users with 'Reviews:Admin'

![image](https://user-images.githubusercontent.com/31961530/36780919-160cea4c-1c7d-11e8-9f2c-63791ba2f3c9.png)

**Comment by wagnerand** [comment]
Just as background info. In the current implementation, the permission to see admin-flagged reviews is `ReviewerAdminTools:View`. Not sure if that is supposed to be that way.

**Comment by jvillalobos** [comment]
Yes, `Reviews:Admin` was intended to be the permission for admin reviewers.  The `Reviewers: Admin` group currently has `Reviews:Admin` as its only permission. Since the admin reviewers are in other groups with other permissions, they are currently unaffected by this bug.

If `ReviewerAdminTools:View` is the permission that currently gates the admin reviewer actions, we can just change the PRD and the group permissions.

**Comment by diox** [comment]
`ReviewerAdminTools:View` is used by some older code, but if it's safe to do so we should definitely replace its usage with `Reviews:Admin` only.

**Comment by jvillalobos** [comment]
Sounds good to me.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with several users having different reviewer permissions, including `Reviews:Admin`
This permission is giving visibility now to add-ons pending for Admin Code/Content Review:

 
![image](https://user-images.githubusercontent.com/31961530/37586242-703976f2-2b64-11e8-8fe7-125ccfeb4744.png)

Verifed fixed on AMO-dev, FF59, Win10x64
