### ISSUE TITLE
Implement `current_compatible_version` in language tools API, add-on type filtering, and better caching

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7676]
We want Firefox users to be able to directly install langpacks from the browser. [bug 1429610](https://bugzilla.mozilla.org/show_bug.cgi?id=1429610) will implement the APIs needed for this in Firefox itself, and they need to be able to hit AMO APIs for this.

The [language tools API](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#language-tools) is not currently suitable for this because:
- It does not expose `current_version` any more
- It has relatively poor performance
- It does not allow you to only show language packs

In addition, `current_version` is not going to cut it anyway if it was reintroduced because each language pack version is only strictly compatible with the major Firefox version that was available at the upload time (i.e. at the time of this writing, `current_version` for all automatically uploaded language packs is marked as compatible with `58.0` to `58.*`).

So we need to:
- [ ] Allow filtering by `type` to only show language packs
- [ ] Expose a new `current_compatible_version` *if* `appversion` is passed. addons-frontend should not pass this parameter to the language tools API right now, since it does not need it.
- [ ] This property will fetch the latest publicly available version compatible with the `appversion` passed. This needs to happen in SQL, in a transformer to avoid hundreds of queries.
- [ ] The whole thing needs to be cached. We tried this before in https://github.com/mozilla/addons-server/issues/6850 but had issues with cache eviction, while we still have cache-machine to work around this problem we probably need to be cached on EFS, in a file, instead of memcached.

**Comment by diox** [comment]
Base SQL query code for a single add-on:
```python
appver = version_int('38.0')
addon.versions.filter(apps__min__version_int__lte=appver, apps__max__version_int__gt=appver)
```

This needs to be done in a transformer so that only one query is made when returning 100+ add-ons. Big question is how cache-machine would react to this, maybe we'll need a `no_cache()`.

**Comment by zbraniecki** [comment]
Thank you @diox!
