### ISSUE TITLE
Change anonymous user image url/picture_type to a null value

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#7679]
Currently when you request a user from the API (https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#get--api-v3-accounts-account-(int-user_id|string-username)-), if the user hasn't set their profile image we get `/static/img/anon_user.png` as a `picture_url`, but I think it would be better to set an empty one so we can more easily check to see if one is set. The front-end should render its own anonymous image (in our case that image is no longer the correct one anyway, and we have an SVG we can render instead–included in part of the bundle as well so it displays while loading without an extra request) so I don't think the API need provide one. This will make it easier to check for a set image.

If the image is not set the `picture_type` docs indicate it can be `null`, but I'm receiving requests that have `picture_type` set to `''`. I think it should be `null` if not set as well.

**Comment by CuriousLearner** [comment]
Hey @tofumatt @diox I'm almost done with the patch. The only thing is that I've made changes in the user model:

```    picture_type = models.CharField(max_length=75, default=None, null=True,
                                    blank=True)```

If I go inside the containers and run `python manage.py makemigrations`, they tell me no changes detected. Am I missing something here?

**Comment by tofumatt** [comment]
We can't know what issues exist in your patch without seeing it. If you'd like feedback on a patch it's best to open a pull request.

**Comment by CuriousLearner** [comment]
@tofumatt Sure, I've explained the issue on the PR. My only question is with generating migrations for changes in the DB models.

**Comment by diox** [comment]
As with pretty much everything in addons-server, it's legacy : when the code was initially written (almost 9 years ago) django migrations didn't exist... We want to switch, see https://github.com/mozilla/addons-server/issues/3705 but this is far from trivial as some database tables in production differ slightly from what's in the models.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, (Win10x64) and here are my results:
- for `picture_url` - the value is set to `null` when the user has no picture uploaded to the user profile
- for `picture_type` - there are two results:
 1. request details for a user that has no profile picture -> returns  `picture_type`:  `""` (1st screenshot)
 2. upload an image for the same profile and then delete it
 3. request the same user details again -> returns  `picture_type`:  `null` (2nd screenshot)

@CuriousLearner 
My understanding was that `picture_type` should always be `null`

[1] before picture upload
![image](https://user-images.githubusercontent.com/31961530/37341772-42a4ca5e-26cb-11e8-9963-67d4be78a48c.png)

[2] after picture upload and delete
![image](https://user-images.githubusercontent.com/31961530/37341789-53ab16aa-26cb-11e8-948c-adbadc7ebe97.png)

**Comment by CuriousLearner** [comment]
@AlexandraMoga I guess that is because of the earlier data. What we can do is running a query on dev/prod making all `picture_type` that are `""` to `null`.

cc @eviljeff

**Comment by CuriousLearner** [comment]
I think we can include that in migration only. Let me know what would be the best way to handle this and I'll do that :)

**Comment by eviljeff** [comment]
@CuriousLearner if you know the sql just include it here and our operations staff will run it directly on the databases.

**Comment by CuriousLearner** [comment]
Sure, we need to set the `picture_type` explicitly to `null` where currently it is empty string. Since, `picture_url` is a model property, rest everything would be taken care of.

```
UPDATE `users`
SET `picture_type` = NULL
WHERE `picture_type` = "";
```

**Comment by bqbn** [comment]
The above sql has run on -dev and -stage environments.

**Comment by CuriousLearner** [comment]
Awesome @bqbn ! Thanks for the heads up!

@AlexandraMoga Can you please test this now? :)

**Comment by AlexandraMoga** [comment]
I've re-tested this today and now `picture_type` is always set to a `null` value.

I'm marking this issue as verified fixed
