### ISSUE TITLE
Can't search for search tools

### ISSUE THREAD

**Issue by pizzahut2** [mozilla/addons-server#7681]
### Describe the problem and steps to reproduce it:

I was trying to find a search engine for a particular website, however the search field at https://addons.mozilla.org/de/firefox/search-tools/ doesn't search for search tools. I eventually guessed the parameter I need to use to make it happen, but the website needs to be fixed.

Edit: I found the correct URL and parameter is used at about:preferences#search which makes this a lesser issue. Though it would still be nice if
1) the search field at https://addons.mozilla.org/de/firefox/search-tools/ would search for search engines and
2) if I could select "search" as add-on type at https://addons.mozilla.org/de/firefox/search/ .

### What happened?

* I get a list of unrelated results (extensions) after using the search field at https://addons.mozilla.org/de/firefox/search-tools/ .
* I can't select search as add-on type at https://addons.mozilla.org/de/firefox/search/ .

### What did you expect to happen?

* Using the search field, I should get a list of search tools (not search extensions) at "/search-tools/".
* I should be able to select search as add-on type at "/search/".

### Anything else we should know?

The required parameter to search for search engines is "type=search". Example:

https://addons.mozilla.org/de/firefox/search/?q=OpenThesaurus&type=search

**Comment by eviljeff** [comment]
I've re-logged this here: https://github.com/mozilla/addons-frontend/issues/4496
