### ISSUE TITLE
Remove old Trunion based signing code

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7688]
In #6640 we switched from Trunion to Autograph.

This is now live, switched on and tested for quite some time.

Let's remove the old code.

Also, switch release-import based langpack signing over to Autograph.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Hello, can you provide some STR for QA? If it is qa is not needed please add the label. 
Thank you!

**Comment by EnTeQuAk** [comment]
Sorry for the late response. The only thing this changes is removing old code so the only thing you'll have to check is that submitting an add-on or updating it still works and that they get signed.

**Comment by vcarciu** [comment]
That was already tested, so marking the issue as verified.

Thanks!
