### ISSUE TITLE
Don't convert empty strings to "/" when wrapping outgoing links in the API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7691]
For add-ons that have contribution url set to an empty string somehow instead of `None`, when outgoing links wrapping is enabled (so, requests from the frontend, which uses `wrap_outgoing_links=true` query parameter) we end up with `"/"` instead of `""`.

This is bad because then the frontend considers it's an actual URL and displays the contributions card.

**Comment by muffinresearch** [comment]
Looks good one stage:

Before: 
<img width="1470" alt="crafowl-wrebray-oystee_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/36873527-a4a1d0be-1da0-11e8-8c83-81551b4af0e6.png">


After: 
<img width="1549" alt="crafowl-wrebray-oystee_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/36873550-b625f31a-1da0-11e8-9eae-79849565fbac.png">

**Comment by muffinresearch** [comment]
Here's a before on production for https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/?src=search

<img width="1404" alt="enhancer_for_youtube _ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/36873654-0340a596-1da1-11e8-82c4-0523a58deba3.png">

**Comment by muffinresearch** [comment]
After on production:

<img width="1418" alt="enhancer_for_youtube _ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/36874372-94d1bff2-1da3-11e8-87ca-bba6cd3d42ab.png">
