### ISSUE TITLE
Upgrade to npm 5.x or higher

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7696]
Currently our debian docker image **and** travis make use of npm 3.x which compared to more recent npm versions might slow things down quite a bit.

Let's upgrade this and get into faster CI builds for free.

**Comment by CuriousLearner** [comment]
@EnTeQuAk Where do I start looking for this issue? Can you please provide a pointer?

**Comment by CuriousLearner** [comment]
@EnTeQuAk Ping :)

**Comment by EnTeQuAk** [comment]
@CuriousLearner sorry for the late response, I didn't see the notification. Unfortunately I don't think that issue is a good contributor issue since it involves knowing how we build our JavaScript and you'll have to test loads of different parts of AMO to ensure things don't break unexpectedly.

I do hope you'll consider a few other issues though! We're happy to help you there.

**Comment by EnTeQuAk** [comment]
This will be fixed once https://github.com/mozilla/addons-server/issues/8454 is done.
