### ISSUE TITLE
Updated themes do not appear in Theme Updates queue in Rev Tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7701]
Prerequisites: User has Persona:Review permissions

STR:
1. Select a theme (lightweight) from AMO and click on Edit details
2. Upload a new design - header and footer - and save your changes
3. Access Reviewer Tools and check the 'Theme Updates' queue

Actual result:
The theme updated at step 2 is not listed among the available updates

Expected result:
The theme updated at step 2 is listed among the available updates

Notes:
- reproduced on AMO-dev, FF58 Win10x64
- blocks the verification of [#7658](https://github.com/mozilla/addons-server/issues/7658#issuecomment-369662522)

Here are some themes for which I've uploaded a new design and were not listed among Theme updates:
https://addons-dev.allizom.org/en-US/developers/theme/test-theme-icon-url-fif/edit
https://addons-dev.allizom.org/en-US/developers/theme/test-theme-icon-urls/edit
https://addons-dev.allizom.org/en-US/developers/theme/test-theme-icon-url-two/edit

**Comment by eviljeff** [comment]
@diox regression from #7658 ... somehow?  (I can't think of any other LWT changes recently)

**Comment by AlexandraMoga** [comment]
I've checked again this morning and the Updated Themes queue seems to be working now. 
Maybe it was a regression from [#7594](https://github.com/mozilla/addons-server/issues/7594#issuecomment-370015342) instead?
I will close this issue, since the problem can't be reproduced anymore but we will keep checking this functionality to make sure it won't happen again.

**Comment by diox** [comment]
I also suspect #7594 : LWT submission does depend on a couple tasks, so when celery is down, they are left in limbo.
