### ISSUE TITLE
[Lightweight] Theme design is not displayed in edit theme details page after submission

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7702]
STR:

1. Log in to Developer Hub and click on Submit a New Theme (lightweight)
2. Fill in the theme details, upload a design and click on Submit Theme
3. In the confirmation page , select 'edit listing'

Actual result:
The details page of the new submitted theme opens but there is no preview of its design displayed

Expected result:
The details page of the new submitted theme opens and a preview of its design is displayed

Notes:
 - reproduced on AMO-dev, FF58 Win10x64
- I was not able to reproduce this 100% of the time but it did occur more often than not
- might be a regression from [#7658](https://github.com/mozilla/addons-server/issues/7658#issuecomment-369662522)

![theme -upload](https://user-images.githubusercontent.com/31961530/36904558-9d04f90a-1e39-11e8-98e8-fa60de366a94.gif)

**Comment by diox** [comment]
Can you retest ? I suspect it was because of the same root issue behind https://github.com/mozilla/addons-server/issues/7594

**Comment by AlexandraMoga** [comment]
I can still 'partially' reproduce this, both on dev and stage. You can see in the below screencast that the header design appears now in the Edit section. Also, if you wait a few seconds and refresh the page, the previews are displayed as well.

![theme preview](https://user-images.githubusercontent.com/31961530/37089930-1ce1334e-220b-11e8-9267-989301783f89.gif)

**Comment by diox** [comment]
I think this happens because of the png crushing that makes the preview/thumbnail generation take just a second or two more, which is enough to be an issue here.

**Comment by eviljeff** [comment]
the LWT theme wizard is deprecated, only available for existing rejected LWT, and will be removed in the next few weeks so closing
