### ISSUE TITLE
Avoid using reserved Python keywords in naming attributes for models.py

### ISSUE THREAD

**Issue by CuriousLearner** [mozilla/addons-server#7714]
### Describe the problem and steps to reproduce it:
`type` is a reserved keyword in Python. It refers to the type of object being formed dynamically.

I was just browsing the code casually, when I saw the `Addon` model uses `type` as one of the attribute.

IMHO, we should change that to something like `addon_type` which would be more verbose. This would also avoid unforeseen problems with using reserved keywords.

### Anything else we should know?
If devs give a thumbs up for this. I'd like to refactor this thing.

cc @caitmuenster

**Comment by CuriousLearner** [comment]
Here is what I'm referring to:

<img width="868" alt="screen shot 2018-03-04 at 4 51 57 pm" src="https://user-images.githubusercontent.com/8039608/36945004-109d7a7e-1fcd-11e8-83ae-edbb7617eb80.png">

**Comment by diox** [comment]
While I would not have chosen `type` if I had been around when this naming decision was made, I don't think it's worth doing. `Addon.type` is never referenced on its own, it's always `{instance}.type` or `.something(type=...)` which can't conflict with anything. `addon_type` is needlessly redundant, and there would be ton of code to update for limited gains.

**Comment by CuriousLearner** [comment]
@diox Agree that it would be a lot of change in the code-base. But it is just a decision on if we can now make the things correct.

https://stackoverflow.com/questions/10568087/is-it-safe-to-use-the-python-word-type-in-my-code

While `instance.type` would work, it can cause a lot of problems. Believe me, I've been in those code bases when there were a lot of problems shadowing a built-in. 
It is never a good idea to use these :)

**Comment by diox** [comment]
I'm perfectly aware of what problems if can cause, and I still don't think it's worth changing. We have a ton more important stuff to worry about than this.
