### ISSUE TITLE
API server gives me JSON status instead of XPI download

### ISSUE THREAD

**Issue by arantius** [mozilla/addons-server#7717]
See here for both the (Python) source calling the API, and the console output it produces:
https://gist.github.com/arantius/76956f94891d27f6be63e8c730d2c5fd

Key highlight:

    Downloading https://addons.mozilla.org/api/v3/file/881494/greasemonkey-2018.03.04.6nightly-an+fx.xpi?src=api ...
    Got 4888 bytes; writing greasemonkey-2018.03.04.6nightly.xpi.

Those 4888 bytes are the JSON result I'd expect from the "Checking the status of your upload" call, but I'm trying to download the signed XPI, by referring to the URL provided in `files`.  

The docs ( http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#downloading-signed-files ) say I'll either get a file or a header; I've separately checked headers and don't get any such thing.

**Comment by diox** [comment]
There is a bug in your script, you're not downloading the URL you are printing (the file), but instead [just re-downloading `result['url']`](https://gist.github.com/arantius/76956f94891d27f6be63e8c730d2c5fd#file-sign-py-L56), which is, well, the URL if the result you already downloaded.
