### ISSUE TITLE
Update email template for signed extensions 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#7724]
Related to #7352. We should update the email template generated when a developer signs an unlisted extension. This template covers both new unlisted signs and updated unlisted signs. 

It looks like the current template is located [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/emails/unlisted_to_reviewed_auto.ltxt).  

Updated template is below the line. 

******
Hi there, 

Your add-on, {{ name }}, has passed our automatic tests. Version {{version number }}  is now signed and ready for you to download at {{ dev_versions_url }}. Note that you need to be logged in as a developer of the add-on before downloading.

(formatting: two em dashes ] 
Mozilla Add-ons 
addons.mozilla.org 

****** 

As a quick note, this bit from the original template should be cut: 

`You received this email because you're subscribed to:
email me when my add-on is reviewed by a reviewer`

**Comment by arantius** [comment]
Re: my dupe filed in the wrong place:

I'd really like to be able to turn these off; I expect to be doing ~nightly automated unlisted builds now, and I don't need/want an email about each of them.  This is different from how I might feel about listed builds.

**Comment by diox** [comment]
@arantius sorry if my comment there sounded harsh: don't worry about filing bugs on the `addons` repos, it's our catch-all and we monitor it and re-file if necessary.

Can you open a new issue (in addons-server directly while you're at it :) for it? I think it makes sense to have an option for this, but this deserve a separate issue.

**Comment by arantius** [comment]
No offense taken.  RFE filed: #7802

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/37657571-0f3946fc-2c54-11e8-8a81-2a2b309a324e.png)
