### ISSUE TITLE
Theme preview is not correctly rendered for static themes with additional backgrounds

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7729]
Follow up for [#7019](https://github.com/mozilla/addons-server/issues/7019)

STR:

1. Log into Developer Hub and submit a new static theme that includes additional backgrounds (i.e. [this example](https://github.com/mdn/webextensions-examples/tree/master/themes/weta_mirror)
2. After submission, go to the theme review page and approve it
3. Open the theme's details page and observe the preview displayed in the screenshots section

Actual result:
A screenshot of the "headerURL" image is displayed, which in this case is blank

Expected result:
A preview of the theme as it will look in the browser after installation is displayed in the screenshots section

Notes:
- the screenshots will sometimes display a completely random image, as observed in [#7610(comment)](https://github.com/mozilla/addons-server/issues/7610#issuecomment-370753584)
- reproduced on AMO-dev, FF58, Win10x64

![empty screenshot](https://user-images.githubusercontent.com/31961530/37033875-180a9a38-2150-11e8-91dc-db271d80effb.gif)

**Comment by eviljeff** [comment]
Additional backgrounds that don't specify tiling properties are broken (I've replicated locally)

**Comment by AlexandraMoga** [comment]
I've verified this on AMO-dev with several examples and there are a few issues that need to be clarified.

@eviljeff 
The following examples are showing that theme preview is not an exact representation of what the theme will look in the browser once installed:
[1] - background alignment is not rendered correctly in theme preview
[2] - the preview shows a transparency in the left corner which is not visible in the browser


**[1]** - https://addons-dev.allizom.org/en-US/firefox/addon/more-bckg-preview-3/
![image](https://user-images.githubusercontent.com/31961530/37335207-93ae6ce4-26b6-11e8-883a-eccbd3d56935.png)
**[2]** - https://addons-dev.allizom.org/en-US/firefox/addon/additional-bckg-standard-3/
![image](https://user-images.githubusercontent.com/31961530/37336201-571000e2-26b9-11e8-876e-d0088f52a7f5.png)

**Comment by AlexandraMoga** [comment]
I think we should follow the last observations in a separate case (opened [#7804](https://github.com/mozilla/addons-server/issues/7804) for that).
The initial issue is not reproducing anymore, so I'm marking this as verified fixed.
