### ISSUE TITLE
March 2018 Disco Pane content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#7740]
For the **22 March** push, can we please REMOVE:

- Search by Image
- Emoji Cheatsheet
- Video DownloadHelper

... and REPLACE them with Firefox Multi-Account Containers, Forecastfox, New Tab Override (so we'll also KEEP To Google Translate); plus three new themes:

**Separate your online lives** with [Firefox Multi-Account Containers by Mozilla ](https://addons.mozilla.org/firefox/addon/multi-account-containers/)
Privately distinguish your various online identities—work, personal, etc.—through color-coded tabs that split your digital cookie trail.  

**Instant weather updates** with [Forecastfox by Oleksandr](https://addons.mozilla.org/firefox/addon/forecastfox-fix-version/)
Get instant global weather information right in Firefox. 

**Tab Customization** with [New Tab Override by Sören Hentzschel](https://addons.mozilla.org/firefox/addon/new-tab-override/)
Choose the page you see every time you open a new tab. 

[Themes]

The Universe of Ancient Times by [NorDesign](https://addons.mozilla.org/firefox/addon/the-universe-of-ancient-tim/)

Square Red by [Notice](https://addons.mozilla.org/firefox/addon/square-red/)

Dreams Beach by [Candelora](https://addons.mozilla.org/firefox/addon/dreams-beach/)

Full page content lineup should reflect like so:

The Universe of Ancient Times
Firefox Multi-Account Containers
Forecastfox
Square Red
New Tab Override
To Google Translate
Dreams Beach

@muffinresearch @diox @EnTeQuAk

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with the _little_ data available and below you can see the current layout.
A full validation will be made once the changes will be available on prod.

![image](https://user-images.githubusercontent.com/31961530/37527521-e41e07da-293a-11e8-9953-da56ffaf1c7d.png)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-prod, FF59 Win10x64

![image](https://user-images.githubusercontent.com/31961530/37816919-83347e20-2e7d-11e8-8aff-e1e2b8dc5d6b.png)
