### ISSUE TITLE
Remove django-cache-machine

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#7743]
After quite some time we finally decided to remove django-cache-machine.

It's partially blocking our Django 1.11 upgrade (#5271) and I assume there will be a measurable positive impact from removing it.

This issue is to track what's needed to be done to get there.

TODO:

* [x] Remove all `no_cache()` calls
* [x] Do not inherit from `CachingQuerySet`, `CachingManager`, or `CachingMixin`
* [x] Backport Django 1.11's `cache.get_or_set` instead of our own `cached` helper which is similar but less tested. Makes upgrading easier later.
* [x] Make sure `assert_cache_requests` can use cache-aliases

**Comment by EnTeQuAk** [comment]
This is blocked by https://github.com/mozilla/addons-server/issues/7744 so I'm removing the milestone for now.

**Comment by EnTeQuAk** [comment]
Alrighty, I started working on this more in-depth and started from scratch removing cache-machine from our code.

From what I see there are multiple ways to tackle this, let me explain a bit more.

Either…
* Remove the caching mixins from our models but continue using cache-machine helpers (`cached_with`, fragment caching, etc)
* Remove cache-machine completely

Now, for now I took the second approach since that'll be more complete and I'd rather have one complete caching solution than many. By removing and porting some of the helpers I obviously ran into invalidation questions and how we actually want to handle them.

There are multiple approaches…

… the one cache-machine goes: Maintain a cache-key list (flush list) that links models and objects to the keys so that we can invalidate them once changed. That's complicated and hard to maintain, the code in cache-machine is battle-tested but super-comlex. I'd like to avoid that.

… a reduced version of that: Only maintain cache-namespaces (e.g a module name, a view name, something else) that get linked to models so that, when an object change all namespaces related to that model get invalidated. That'll have the advantage of being super-simple - namespaces can be per view and don't depend on parameters etc - but has the disadvantage that we may invalidate one key too much here and there along the way. But I that this should be easy to handle and we won't end-up with too many namespaces and links to models, e.g if an `Addon` changes we have to invalidate a whole lot anyway.

I'm personally in favor of the second, reduced "namespaced cache-keys" idea. It'll make invalidation simple, is easy to maintain and doesn't add unnecessary overhead.

Now, do we want to implement this. The most ideal solution would be to use redis completely for caching, instead of memcached. That way we can invalidate cache-keys by namespace much much more easily and efficiently. Or we'll have to implement separate cache-keys that store that information and mapping for us inside Memcached. Imho that's not nice but might work, as far as I can see that's how Marketplace does it.

So, let's be frank… We're using ElastiCache anyway… are there any concerns of simply switching over to using redis for our caching?

**Comment by EnTeQuAk** [comment]
Updated the issue description with what's left todo once #8460 and #8462 are done.

**Comment by EnTeQuAk** [comment]
This is being split up a bit, this issue will be solely focused on removing the model layer of cache-machine

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Could you add some STR or "qa not needed" label ?

**Comment by EnTeQuAk** [comment]
As discussed on IRC (a few days ago, I don't remember):

This changes how and what we're caching. Generally, if you save a few forms and see the changes right away we're good (e.g update an add-on) and your general smoke-tests should suffice testing this.

In the end, we're testing much much less compared to before now. So although I did run tests, if you see any crazy slow (legacy) pages, these may be regressions. Same for the new frontend, although it's queries and APIs are much more fleshed out / optimized compared to the legacy sites.

**Comment by vcarciu** [comment]
Verified during our release testing cycle and everything looks fine. Marking bug as verified.
