### ISSUE TITLE
Link Preview for static themes to Version it's for

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7752]
part of mozilla/addons#501
We render an svg preview for each version of a static theme and save it in a `Preview`.  We need a fk to the Version so we can display the appropriate preview in the right places.

**Comment by ioanarusiczki** [comment]
@eviljeff Could you please provide some STR for QA. I see #4425 is still open. I don't understand exactly what appropriate preview in the right places means at this moment.
Thank you!

**Comment by eviljeff** [comment]
This is mainly a back-end change that was blocking other issues.  

You can verify by submitting a static theme and checking legacy frontend's detail page for the screenshot.  There should be only preview only (no caption) for the current version - so if a second version is submitted and approved the preview should update.  (Previously there would be all previews for all versions on the same page).

Any static themes already submitted won't have screenshots showing on the detail page anymore - we changed how they are stored and didn't migrate existing submissions because it's not a live feature yet.

The API hasn't been updated but the changes will mean that **no previews will be exposed** via the API, therefor shown on new frontend - until #6804 is implemented.  That fixes mozilla/addons-frontend#4425 in a way 😆  for now at least.

**Comment by ioanarusiczki** [comment]
Hello @eviljeff !
I made some testing on AMO dev with FF58 (Win10) and notices the followings:
1. The legacy frontend's detail page has an issue so I filed https://github.com/mozilla/addons-server/issues/7797 
2. The submission and the previews displayed while submitting a static theme work as expected. Also I could install the themes. 
3. I checked the themes detail page on the new frontend and the screenshot section is no longer available for any of the submitted versions (before or after theme's approval). Also they are no longer displayed on Listed review page. I verified and closed yesterday issue #7610 but you said 

> Any static themes already submitted won't have screenshots showing on the detail page anymore

Please let me know if we can close this issue. 

Thank you!

**Comment by ioanarusiczki** [comment]
I'm marking this issue verified fixed on AMO dev, FF59 (Win10) after the confirmation received on irc from Andrew.
