### ISSUE TITLE
Delete static theme preview for a version when version is deleted

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7756]
part of mozilla/addons#501

We render an svg preview for each version of a static theme and save it in a Preview.  Previews need to deleted when the version is deleted.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF59, Win10x64

I've checked theme preview rendering on the add-on details page and in Reviewer Tools and the preview matches the current approved version (there are no screenshots connected to disabled/deleted versions or previously approved versions)
In parallel, I've looked in the API and the theme `preview` property is also returning a single preview with an ID matching the current version

https://addons-dev.allizom.org/en-US/firefox/addon/foglet/
![image](https://user-images.githubusercontent.com/31961530/37648004-6c4a4d5a-2c36-11e8-825f-32f279cb01e0.png)
