### ISSUE TITLE
RFE: Tag to suppress validation warnings

### ISSUE THREAD

**Issue by arantius** [mozilla/addons-server#7758]
I've got the same several warnings for every version of my extension.  Some things baked into open source third party code, and some things that I just have to do, to do what my extension does.  It's counterproductive to see these each and every time validation happens.  I'd like some way to suppress this message.  To indicate that I've seen it, I've evaluated it, and I choose to ignore it.

Something like the [@SuppressWarnings](https://docs.oracle.com/javase/7/docs/api/java/lang/SuppressWarnings.html) annotation from java?  But if I could apply it to third party code (a whole directory of it?) without _editing_ that code, it would be especially useful.

**Comment by diox** [comment]
cc @jvillalobos for input

**Comment by wagnerand** [comment]
Since those message are currently equally seen by developers and reviewers, suppressing them would hide them for both, which is undesirable.

**Comment by jvillalobos** [comment]
Agree with Andreas that we would first need to have separate views for reviewers and developers, since reviewers need to see everything (or at least not be affected by any message suppression system). @wagnerand, is there an open issue for it?

**Comment by wagnerand** [comment]
I thought I filed an issue, but I can't find it right now.

I did find #746 however which sounds quite similar to this one. Might be a dupe?

**Comment by jvillalobos** [comment]
Yes, Iet's close this one in favor of the other one. There's still the issue of figuring out what to do about linter flag classification, which appears to be the main blocker for this.
