### ISSUE TITLE
XPATH CHECKER

### ISSUE THREAD

**Issue by neetapandey** [mozilla/addons-server#7763]
### Describe the problem and steps to reproduce it:
Thre used to be a add-ons Xpath Checker, which is no more available.

### What happened?
Could not find the add-ons on Firefox
### What did you expect to happen?
Please have it back , its very usefull add-on

### Anything else we should know?
http://www.seleniumpoint.com/install-firebug-firepath-xpathchecker-firefox-addons-for-selenium

Go through this link which will show you xpath checker add-on

**Comment by jvillalobos** [comment]
It's likely the add-on was removed by the developer at some point. You can try finding a similar one by [searching the site](https://addons.mozilla.org/firefox/search/?q=xpath%20checker).
