### ISSUE TITLE
Review page for Static Themes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7765]
Part of mozilla/addons#501 and #7385

We need to optimize the Reviewer review page for static theme reviewing. 

- the Preview needs be the full size and prominent
- Any details not relevant for Static Themes can be hidden
- generally it would be nice to de-clutter and reduce the amount of page the content takes up

**Comment by eviljeff** [comment]
Open questions:
- do we need replicate the pre-set responses for rejections?
  - if so, can they be implemented like addons, i.e. canned responses that can be edited?
- are shortcut keys to approve/reject, etc like in the LWT tools needed?

@jvillalobos

**Comment by jvillalobos** [comment]
Yes, let's reuse canned responses for this.

No, I don't think we need the keyboard shortcuts. If they turn out to be important, we should consider implementing something like it for all reviewer tools, further down the line.

I think it should also be possible to inspect the background image(s) individually, since some themes contain images with inappropriate content that isn't visible in normal resolutions.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59, Win10x64
Here are some observations:
1. themes can be composed of several backgrounds, so an image gallery could actually be useful for reviewers; in the current implementation, you can't know how many images are there unless you navigate through all the available screenshots
2. for Admin Reviewers: More Actions section includes the 'Disable auto-approval' button which doesn't really apply to static themes
3. 'Request super review' will set a 'Needs Admin Code Review' flag which makes more sense for extensions; maybe a new flag that will distinguish static themes from the rest of the add-ons could be put in place?
4. Unlisted queue - is this in scope for static themes?

@eviljeff could you please comment on the above points?

For what I'v identified as a potential issue, I filed the following bugs:  #7850, #7851, #7853

**Comment by eviljeff** [comment]
>    themes can be composed of several backgrounds, so an image gallery could actually be useful for reviewers; in the current implementation, you can't know how many images are there unless you navigate through all the available screenshots

The caption on the preview shows x of y, but anyway, I believe this satisfies "possible to inspect the background image(s) individually".  Jorge to file follow-ups if the implementation needs changing  as there weren't any UX descriptions or mock-ups.

>    for Admin Reviewers: More Actions section includes the 'Disable auto-approval' button which doesn't really apply to static themes

Yes.  It's harmless, but shouldn't be there.

>    'Request super review' will set a 'Needs Admin Code Review' flag which makes more sense for extensions; maybe a new flag that will distinguish static themes from the rest of the add-ons could be put in place?

It's a bit of an open question what admin flagging should look like for static themes.  (I couldn't see any reference to it in the PRD/issues so just left it at standard add-on admin flag). It probably shouldn't be "Needs Admin Code Review" but it's not clear what it _should_ be yet. I'll leave it to Jorge to specify.

>    Unlisted queue - is this in scope for static themes?

No, but it would be nice if static themes with unlisted versions would show up in the unlisted list and the review page would minimally work

**Comment by AlexandraMoga** [comment]
> for Admin Reviewers: More Actions section includes the 'Disable auto-approval' button which doesn't really apply to static themes

I've filed #7854 

> No, but it would be nice if static themes with unlisted versions would show up in the unlisted list and the review page would minimally work

I've submitted several unlisted static themes and here are the results:
1. they appear in the Unlisted queue
2. they can be downloaded for preview in the browser
3. reviewer actions can be performed, i.e. Confirm Approval, Reviewer reply, Comment etc + More Actions for Admin Reviewers
4. theme previews are NOT available
5. reject action is NOT available

@eviljeff please have a look at my remarks regarding Unlisted static themes and let me know what you think

For the remaining open items I've filed issue #7855 and cc'd Jorge.

**Comment by eviljeff** [comment]
we only generate previews for listed versions, so no previews for unlisted is to be expected.  Afaik we don't support Rejecting for any type of addon for unlisted so that's okay too.

**Comment by AlexandraMoga** [comment]
Based on the above comments, I'm marking this issue as verified fixed.
For all other identified issues and open discussion points bugs were filed separately. 

Verified on AMO-dev, FF59 Win10x64
