### ISSUE TITLE
Update staff & theme reviewer groups with Static Theme permission

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7769]
They both need `Addons:ReviewTheme` because I thought it a good idea at the time to create a new Permission and add a whole bunch of methods to check for that permission rather than the existing `Personas:Review` permission 😒

**Comment by eviljeff** [comment]
Ideally we should do this closer to the review tools being "finished" for static themes to avoid the confusion of exposing half-finished tools that don't work yet.

**Comment by eviljeff** [comment]
QA: just need to finish the last part of the testing from #7750

**Comment by vcarciu** [comment]
This is what I see when adding a new user to the Reviewers: themes group : 
![staticthemepermission](https://user-images.githubusercontent.com/1583842/38565542-43199a34-3cea-11e8-99cf-759d9304cd60.png)

**Comment by vcarciu** [comment]
Now I can see both lightweight and Static themes if I add an user to Reviewers : themes group : 
![revtoolspermissionsthemes](https://user-images.githubusercontent.com/1583842/38674010-ae4dae86-3e5b-11e8-86e1-d6986560df7b.png)
