### ISSUE TITLE
An internal server error is received after Static Theme approval in Reviewer Tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7773]
STR:

1. Log in to Reviewer Tools with an Admin account
2. Click on Static Themes queue in Reviewer's dashboard
3. Filter your results to view the available Static themes waiting for approval
4. Select a theme to review and Approve it

Actual result:
The user receives an internal server error after submitting a static theme approval

Expected result:
Static Theme approval is successfully submitted

Notes:
- the same error is received when posting a theme rejection, but if you visit the same theme's review page again, there will no longer be an option to Approve or Reject this theme; also, there is no event logged in Add-on review log
- reproduced on AMO-dev with FF58, Win10x64

![st approve error](https://user-images.githubusercontent.com/31961530/37271878-7368c54e-25dd-11e8-95e5-308710e82b35.gif)

**Comment by eviljeff** [comment]
The review page isn't finished (not started either) so while I'd be happy if it was working already, I'd also be surprised.  see #7765 - closing as a dupe because we can track that it's working in that issue.

**Comment by eviljeff** [comment]
Thanks for the report though - I know I need to add reviewer points as part of #7765 now

**Comment by eviljeff** [comment]
Going to say this was fixed with #7765

**Comment by AlexandraMoga** [comment]
@eviljeff  has this been fixed only for recent submissions?
I've tried to approve/reject themes listed in the Static Theme queue but any version older than 3 days is still generating an internal server error.

**Comment by eviljeff** [comment]
@AlexandraMoga at the time #7765 wasn't actually closed - it was just now.
It _should_ fix the error for all submissions, but tbh we're only interested in new submissions from this point.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF59, Win10x64
All static themes from New Add-ons/Add-on updates queue can be approved or rejected.
