### ISSUE TITLE
"Webextension could not be loaded' error message is displayed when submitting a new add-on 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7774]
STR:

1.  Log in to Developer Hub and submit a  add-on
2.  Check the validation report during version upload

Actual result:
A "Webextesnion could not be loaded" error message is displayed

Expected result:
Add-on successfully passes validation

Notes:
- also happens with static themes when using the submission wizard 
- reproduced on AMO-dev, FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/37282597-b400058e-25fd-11e8-992b-3a90fd168c33.png)

![image](https://user-images.githubusercontent.com/31961530/37282609-baf11144-25fd-11e8-8306-1543a4890c7e.png)

**Comment by EnTeQuAk** [comment]
The fix is heading towards -dev, should be there in a few minutes.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO-dev, FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/37327974-110c7980-26a1-11e8-8664-9ad973c7d592.png)
