### ISSUE TITLE
Validation error "/version" should match format "versionString" should say what the versionString format is

### ISSUE THREAD

**Issue by arantius** [mozilla/addons-server#7778]
I tried to automatically submit a nightly build for signing and self-serving.  The (partial) result was:

    {
      "guid": "{e4a8a97b-f2ed-450b-b12d-ee082ba24781}",
    ...
      "validation_results": {
        "errors": 1,
        "success": false,
    ...
        "messages": [
          {
            "uid": "ba64e9016ce74252b49bc45f074ef667",
            "dataPath": "/version",
            "tier": 1,
            "message": "\"/version\" should match format \"versionString\"",
            "type": "error",
            "id": [
              "JSON_INVALID"
            ],
            "description": "Your JSON file could not be parsed."
          },
    ...
      "version": "2018.03.09.nightly.e7c1c74"
    }

The [webext docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/version) say "see the Version format page."  The [version format](https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format) page says "A version string consists of one or more version parts, separated with dots. Each version part is itself parsed as a sequence of four parts: \<number-a\>\<string-b\>\<number-c\>\<string-d\>. Each of the parts is optional."

Okay, I've got five parts. 

1. number a (rest, optional, omitted)
2. number a (rest, optional, omitted)
3. number a (rest, optional, omitted)
4. number a (optional, omitted), string b, (rest, optional, omitted)
5. number a (optional, omitted), string b, (rest, optional, omitted)

But, rejected.  And I don't know what to fix, because I'm already compliant with the docs.

(I can make an educated guess that you actually want me to follow [chrome's rules](https://developer.chrome.com/extensions/manifest/version), "One to four dot-separated integers identifying the version of this extension." -- except I've had non-numeric characters work in the past so I think that's not _quite_ it.)

**Comment by diox** [comment]
Moved to https://github.com/mozilla/addons-linter/issues/1905

**Comment by EnTeQuAk** [comment]
Short note, a number should not include leading zeros according to our implementation. Does that help you already maybe?
