### ISSUE TITLE
Find a friend

### ISSUE THREAD

**Issue by zeviaran** [mozilla/addons-server#7782]
Hi. I'm zevi from Israel. I got two mail addresses from a friend in Ukraine, and I can not seem to get in touch with her. Unfortunately she also can not get in touch with my email addresses. We agreed that we would search the various search engines on the Internet for a solution. I hope I've come to the right place. I would be very happy if you could help me.
Here are the two addresses of the friend:
1. irina1006@gmail.ru
2. irina1006@yahoo.com
In all attempts, the mailbox claims that the domain is invalid. We checked ourselves over and over again and can not figure out where the problem is.
I would be very grateful if you could help me decipher the problem.
Thanks.

**Comment by EnTeQuAk** [comment]
This is the bug-tracker for addons.mozilla.org and anything Add-ons related. Please don't use this bug-tracker for anything else.

Closing.
