### ISSUE TITLE
Color selectors in static theme submission wizard have layout issues in RTL

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7783]
STR:

1. Log into Developer Hub and submit a new static theme using the wizard
2. Switch to an RTL locale
3. Observe the text layout for the color selectors

Actual result:
The color selector area does not have the same margins as the LTR locales 

Expected result:
Color selector area has the same margins for RTL and LTR

Notes:
- reproduced on AMO-dev, FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/37338909-85147bb4-26c1-11e8-8a21-a8cbd90ebc0f.png)

**Comment by wagnerand** [comment]
Mentor: @eviljeff 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by deepanshu-jain1999** [comment]
I want to work on this issue.

**Comment by eviljeff** [comment]
@deepanshu-jain1999 great - this should just be a css fix

**Comment by deepanshu-jain1999** [comment]
Thanks

**Comment by deepanshu-jain1999** [comment]
It seems in this way on linux .

![issue](https://user-images.githubusercontent.com/31172305/39286083-98c03c1c-4939-11e8-8628-86834a6658dc.png)

**Comment by deepanshu-jain1999** [comment]
Thanks I got it . Actually I am new to open source. So I feel afraid how to do it. Please help me where I will get this issue in project. Is this problem specific to window 10 user because it seems fine on linux

![newissue](https://user-images.githubusercontent.com/31172305/39293949-f7a26b6a-4957-11e8-9d31-51adcb743b87.png)

**Comment by eviljeff** [comment]
@deepanshu-jain1999 
The problem isn't OS specific, but is specific to RTL locales (e.g. Arabic, Hebrew, Urdu, etc).  I should have linked to one of those pages to demonstrate, e.g. https://addons-dev.allizom.org/ar/developers/addon/submit/wizard-listed

**Comment by deepanshu-jain1999** [comment]
Thanks I got it. It should be in this style 
![solved](https://user-images.githubusercontent.com/31172305/39561084-f60501b4-4ec0-11e8-9994-6555565545bd.png)

I have done it on browser . Now I am going to implement it inside project

**Comment by deepanshu-jain1999** [comment]
When I signup on the project locally it redirect to "refuse to connect ". What am i doing wrong?

**Comment by eviljeff** [comment]
That's quite a vague error and impossible to debug without more details.  If you visit the #amo irc channel we might be able to suggest something.

**Comment by deepanshu-jain1999** [comment]
Yes I have posted on    http://disq.us/p/1s9bdf6

**Comment by eviljeff** [comment]
> Yes I have posted on http://disq.us/p/1s9bdf6

That's not irc... that's a website with a directory listing of irc channels.

**Comment by deepanshu-jain1999** [comment]
I have solved login problem but I am unable to access page http://olympia.test/en-GB/developers/addon/submit/wizard-listed locally.

**Comment by eviljeff** [comment]
ah, yes, it's turned off by default.  You can enable it by adding a flag (a "waffle switch") in django admin here: http://olympia.test/admin/models/waffle/switch/ called "allow-static-theme-uploads".  It will look something like this:
![screenshot 2018-05-14 19 08 20](https://user-images.githubusercontent.com/768592/40015086-2ec2203a-57aa-11e8-97ae-d983908aefb6.png)

**Comment by deepanshu-jain1999** [comment]
Thanks

**Comment by caitmuenster** [comment]
Hey there @deepanshu-jain1999, how's it going with this issue?

**Comment by eviljeff** [comment]
I linked the page in RTL local in https://github.com/mozilla/addons-server/issues/7783#issuecomment-386048998

**Comment by deepanshu-jain1999** [comment]
When I am changing in "static/css/devhub/static-theme.less" it shows this error-
Permission denied: u'/code/static/css/devhub/static-theme.less.css'

**Comment by deepanshu-jain1999** [comment]
#8463 Fix issue #7783

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, WIn10x64


![image](https://user-images.githubusercontent.com/31961530/41218228-0c40ccea-6d63-11e8-862f-65fb8d8bb1b8.png)
