### ISSUE TITLE
 Add OpenCollective to list of allowed payment providers

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7790]
Please add OpenCollective (opencollective.com) to the list of allowed providers for contributions. See #6309 for a previous addition.

**Comment by vcarciu** [comment]
Verified as fixed: 
![opencollective](https://user-images.githubusercontent.com/1583842/37709103-c5b25212-2d11-11e8-83ec-d7a9d27bfeeb.gif)
