### ISSUE TITLE
Error message is displayed in classic view for static theme detail pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7797]
STR:
1. Load AMO dev and from Developer Hub submit a static theme or choose an already submitted static theme.
2. Open the theme's detail page and change to classic view.
3. Observe the screen. 

Expected results:
The page is displayed without layout issues.

Actual results:
Oops! We had an error message is displayed.

Notes:
This issue is reproducible on AMO dev with FF58 (Win10).

![static themes legacy page](https://user-images.githubusercontent.com/33448286/37392993-7ae7f3c0-2778-11e8-949e-5a1da806a726.gif)

**Comment by diox** [comment]
Not entirely surprising since we haven't particularly focused on making the legacy site work, but it should not 500...

It's because of this from the version preview changes:
`{% set previews = list(version.previews) %}`

`list` is undefined in the template context.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59 (Win10).
