### ISSUE TITLE
Allow developers to opt-out of auto-approval notifications

### ISSUE THREAD

**Issue by arantius** [mozilla/addons-server#7802]
See also https://github.com/mozilla/addons-server/issues/7724

I'd like to be able to opt out of email notification of newly signed/reviewed versions separately, based on whether that version is listed or unlisted.

**Comment by diox** [comment]
This looks like a good idea to me, no need for unwanted emails for unlisted uploads. @jvillalobos thoughts?

**Comment by caitmuenster** [comment]
Thanks @arantius! 

I chatted with @jvillalobos about this. We're not in favor of letting developers opt out of some notifications (like notes from reviewers, although that doesn't apply to unlisted emails), but it might make sense to have a setting to disable auto approval notifications. 

I still want developers to receive a confirmation message when their unlisted extension is signed. If possible, I'd like to have the default set to receive notifications when updates are confirmed, but I'm fine if they want to opt out of those.

**Comment by jvillalobos** [comment]
Yes, it's still possible for reviewers to reject or needinfo unlisted versions, so those notifications should still be mandatory. We can have a setting to opt-out of auto-approval email, which is admittedly not that useful.

**Comment by jvillalobos** [comment]
This can be another checkbox in the user profile, under "Notifications". Something like "my add-on is automatically approved". Toggling it off would turn off auto-approval email for that account. All other review email would still need to work.

**Comment by birtony** [comment]
Hey, is this issue still relevant? I would be happy to work on it!
