### ISSUE TITLE
Upload/submit a new listed add-on version through the API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7811]
This API feature would support the highly requested [`web-ext submit`](https://github.com/mozilla/web-ext/issues/804) command and improve automation abilities for add-on developers.

In addition to the existing [upload](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#upload-version) endpoint, we want an endpoint (the same one, maybe) that would allow us to upload a new add-on in a listed state.

**Comment by diox** [comment]
I think the 3 requirements are categories, summary and license, so we'd need to add that. But presumably we'd also want to be able to set any of the fields available through devhub submission and not just those.

**Comment by birtles** [comment]
The request we've had from add-on developers here in Japan is to be able to set the summary, description, and release notes, and to be able to do it for multiple locales too.

On the add-on developer experience team we're keen to see this happen soon and are prepared to put resources behind the `web-ext` bits. Please let me know if there's anything else we can do to help.

**Comment by eviljeff** [comment]
(I'm certain we have an existing issue asking about this but I can't find it)

I'd prefer we implement POST/PATCH on the /addon/ API endpoint rather than attempt to hack something (more) onto the signing endpoint.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/7825 would help nicely with the summary (though it still does not solve the category & license)

**Comment by kumar303** [comment]
> I'm certain we have an existing issue asking about this

I thought so too but I couldn't find one. I'm sure it will turn up 😄

**Comment by birtles** [comment]
Thanks, that's very helpful. I think hacking on the AMO API is pretty far outside our usual area of work (we're basically platform engineers) so let me see if there are any existing plans to work on that in the AMO team before we consider taking it on.

**Comment by stoically** [comment]
Would be useful to declare the compatible apps when submitting Add-on as well, since currently it always adds Firefox and Firefox Android as compatible.

**Comment by rubenwardy** [comment]
Maybe I misunderstand this issue, but submitting a new add-on is an infrequent task that should be low priority when it comes to adding an API

Much much higher priority would be allowing submitting updates to existing add-ons. I'm currently unable to do this due to #9913

**Comment by LinusU** [comment]
@rubenwardy it was a while since I worked on this now, but I was automatically submitting updates to a web extension using the following library: https://github.com/LinusU/wext-shipit

**Comment by MihaiTabara** [comment]
This may be random but TIL this issue may be paving the way for https://github.com/mozilla/addons-server/issues/15353 which is very exciting to hear for us in RelEng/RelMan teams. Just wanted to drop a thank you note for this :)

**Comment by eviljeff** [comment]
> Maybe I misunderstand this issue, but submitting a new add-on is an infrequent task that should be low priority when it comes to adding an API
> 
> Much much higher priority should be allowing submitting updates to existing add-ons. I have a CI process that runs when I tag a release, but I'm unable to deploy the release to AMO due to #9913

this will be the base work that will eventually allow you to submit/manage everything about an add-on via the API.

**Comment by rubenwardy** [comment]
That's great to hear, thanks for clearing it up!

**Comment by willdurand** [comment]
> @LinusU Unfortunately, this uses web-ext so probably doesn't support uploading source .zips I'm guessing?

The work for this is tracked in https://github.com/mozilla/sign-addon/issues/409

**Comment by ioanarusiczki** [comment]
@eviljeff
I tested with a dummy extension and a static theme using JWT Authentification like this:
- POST with api/v5/addons/upload/ to get the <uuid>. At this step `upload` file and specification of the `channel` is required. 
- POST `/api/v5/addons/addon/` to create a new extension/static theme. Depending on the channel specified into the first step, the addons are created - 201 status. It needs the JSON: `{"categories": {"firefox": ["other"]}, "version": {"upload": "e8c7c1dbfe794f9aa920b079097b947a", "license": 18}}`

**Notes:**
- when there's no "summary" the submission is created but it looks incomplete in dev hub where it can be resumed
- a submission is created with any valid license id from admin tools, so I could add for an extension a license id that belongs to themes (I refer to the list of licenses displayed for themes in dev hub)
- I get a 201 created status when no category is mentioned, "firefox": [], in this case the submission can be resumed from dev hub. 

A new version of an extension can be submitted and it can be listed or unlisted, it does not matter what channel used the previous version:
- it requires the `uuid` generated with POST `api/v5/addons/upload/`
- POST with `api/v5/addons/addon/620780/versions/`, JSON {"upload": "04e2361ad6614f44ae705e75b2b1a589", "license":18}

**Notes:**
- For a new unlisted version the license is required.
