### ISSUE TITLE
Suggestion: "Compatible with Firefox 57+" is not as informative as before

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#7814]
Since FF57 and the changes to AMO, seeing "Compatible with Firefox 57+" on every add-on that comes up in searches and listings (dominantly geared towards WE add-ons) is no longer as informative as it once was.

Opting a reverse method (i.e a legacy tag) or at the very least a smaller tag (e.g. "Firefox 57+" or "Quantum") seems to be a possible enhancement to the UI.

TBH, IMHO, it is not even necessary any more.

**Comment by eviljeff** [comment]
I don't see the "Compatible with Firefox57+" tag on the new frontend - where are you seeing this?

**Comment by erosman** [comment]
It came up here

https://addons.mozilla.org/en-US/firefox/tag/proxy

**Comment by eviljeff** [comment]
Okay, so it's on the legacy frontend.  If we do end up reimplementing that page on new frontend (I don't think it will be) then the tag won't be there.
We're not doing any more work on legacy frontend so this won't be fixed.

**Comment by erosman** [comment]
I see... just out of curiosity, are "tags" still used in the new front-end?

**Comment by eviljeff** [comment]
They aren't exposed in the UI, but are supported in the API and are still used as a factor in freetext search, iirc.  @jvillalobos might have a link/doc to the plans around tags.

**Comment by jvillalobos** [comment]
The plan is to bring them back, but that's probably happening on the second half of the year.
