### ISSUE TITLE
Remove stylus 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7815]
We use Stylus for enhancing our css files for a [very small number of files](https://github.com/mozilla/addons-server/search?utf8=%E2%9C%93&q=extension%3Astyl) and it makes little sense to support it for only 4 files.  We should either convert them to Less format that we use everywhere else (68 files) or just flatten them to css.  Then we can remove the dependency and the associated code we have for handling it.

**Comment by vcarciu** [comment]
@eviljeff : Can you please add some STRs to this issue or mark it as "qa: not needed" ?

**Comment by EnTeQuAk** [comment]
The code that got removed here was primarily used in the reviewer tools. So a quick click-through there that verifies that nothing looks off should suffice.

It's mostly a 1:1 translation so I'm not too worried.

**Comment by vcarciu** [comment]
Verified rev tools and everything works fine. Marking issue as verified
