### ISSUE TITLE
Do not show 'Themes (Static)' as an advanced search option to non-static theme reviewers

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7816]
Follow up form #7750 

STR:
1. Log in to Reviewers Tools with a user having legacy reviewer permissions (i.e. New Add-ons/Add-on Updates)
2. Select the 'New Add-ons' queue from the dashboard
3. In the pending add-ons list, click on Advanced search option
4. Check the available options in the 'Add-on type' filter

Actual result:
Legacy reviewers can filter by 'Themes (Static)' which will return an empty pending list

Expected result:
'Themes (Static)' should not be an available filter option if the reviewer is not a static theme reviewer

Notes:
- reproduced on AMO-dev with FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/37455372-95b7fe70-2845-11e8-97e5-b58005e93b81.png)

**Comment by eviljeff** [comment]
as long as they can't review them I think it's fine.

**Comment by diox** [comment]
Yeah it's not worth the complexity.
