### ISSUE TITLE
Add-on Metadata Handling Updates

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7825]
This is a tracker for the work needed to update add-on metadata handling on AMO. The main goal is to have a clearer separation between what metadata is defined in the manifest and what is defined and editable on AMO.

* [ ] Import the name, summary, and icon from the add-on package. 
  * Add support for importing SVG icons (and possibly other image sizes). This doesn’t mean AMO needs to keep them as SVG (they could be rasterized).
* Support importing all localizations of the name and summary. 
  * Validate summary and name length so they conform to AMO restrictions.
  * They can be updated with a version update; the fields will need to be validated and updated if they change.
* [ ] Name, summary, and icon are no longer editable from the Developer Hub.
* [ ] [PM] Coordinate so the Add-ons Manager no longer uses the API to update these values.
* [ ] In the edit page for a version, the Compatibility section should no longer be editable.
  * Compatibility with Firefox for Android should be a checkbox in the main edit page, affecting all versions, and no longer a setting that is tracked for each version.
* Note: compatibility with Firefox for Android is tied to the Firefox for Android categories.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-157)

**Comment by hiikezoe** [comment]
> Add support for importing SVG icons (and possibly other image sizes). This doesn’t mean AMO needs to keep them as SVG (they could be rasterized).

SVG support should be done in #4161?

**Comment by diox** [comment]
> SVG support should be done in #4161?

Yes.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-157
