### ISSUE TITLE
Redirect beta versions to the stable channel

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7830]
Part of #7163.

To prevent beta users from being stranded after we disabled new beta version submissions, we redirect all beta versions to the stable channel.

STR:
0. Make sure the waffle `beta-versions` is true.
1. Install the beta version of an add-on and close Firefox.
2. Submit a beta update to that add-on, then immediately flip the `beta-versions` waffle to false. (It's best to use a different profile to prevent the add-on from updating in the background).
3. Open Firefox from step 1 and check for updates. => There should be no update available (especially not the update you submitted in step 2).
4. Submit another (stable) update to the add-on.
5. With the profile from step 1, check for updates again. => There should be an update available to the version uploaded in step 4.

**Comment by AlexandraMoga** [comment]
I have followed the steps mentioned above and the results are as expected.

With the waffle off:
- it is not possible to update an installed beta version to a new beta version 
- an installed beta version can be updated to a new listed (stable) version

Verified on AMO-dev, Nightly 61.0a1, Win10x64
