### ISSUE TITLE
Revisit the way we do the django admin permission checks

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7848]
By default, the django admin is guarded with the following:
- A `has_permission()` method on the admin site, which checks against `<user>.is_staff`.
- Various `has_*_permission()` methods on each model admin class, which use `<user>.has_perm()`, building a permission string corresponding to what the model admin is for and what action the user is doing.
- For object deletion, the `has_*_permission()` is not necessarily enough, [a `<user>.has_perm()` call is made anywa](https://github.com/mozilla/addons-server/issues/6245#issuecomment-325931173)y.

Unfortunately... we currently bypass all that. In our current implementation:
- `UserProfile.is_staff` checks `acl.action_allowed_user(self, amo.permissions.ADMIN)`
- `UserProfile.has_perm()` ignores the permission string and just check against `self.groups.filter(rules='*:*').exists()`

The result is that only users with the `Admin:%` ACL can log in to the admin tools, and on top of that they need `*:*` anyway to be able to see/do anything.

When we introduced replacement add-ons, that were open to other users, we added a different admin site that:
- Has a custom `has_permission()` on it checking for `acl.action_allowed(request, amo.permissions.ADDONS_EDIT)`
- Has a base model admin with a custom implementation of each `has_*_permission()` method that calls the `has_permission()` on the admin site.

That makes the special staff admin available for users with just the `Addons:Edit` ACL, but they can't delete objects if they are not full admins because deep in django admin code that causes another call to `<user>.has_perm()`.

We need to revamp all that to allow for more granularity, to implement https://github.com/mozilla/addons-server/issues/7253 and future tools. The way forward probably involves carefully replacing the extremely naive `<user>.has_perm()` implementation that we have with something that does use the permission string to figure out whether or not the user has access... And also find a way to replace the `is_staff` check that guards the admin tools by default.

**Comment by eviljeff** [comment]
As well as `UserProfile.has_perm` there's `UserProfile.has_module_perms` but I can't remember how that's used.

**Comment by eviljeff** [comment]
Replacing `UserProfile.has_perm` is probably the way to go, agreed.  The reason I eventually didn't do that for ModelAdmin/AdminSite was there wasn't an easy match between our ACL permissions and the "perm" that django builds and thought it would clutter up UserProfile with other model specific logic.  (Subclassing ModelAdmin didn't turn out great either though).

One option is to have a dict that's a lookup between "perm" strings django generates and our `AclPermission`s, defaulting to just checking for full admin like now.  Django is very much about Models and concrete create/update/delete actions though, unlike our more abstract task based acl permissions, so we might need to create some extra AclPermissions.

Also, ideally we'd push the logic for determining `UserProfile.has_perm` back into the model it relates to,   but that would probably need some horrible parsing of the string to work out which class it related to 😞 

As for `is_staff`, perhaps we can relax significantly that by just assuming that all access to `/admin` is by staff by the fact it needs VPN now.  I can't remember what `is_staff` and `is_superuser` actually **do** though, practically, in the tools.  Obviously we don't want to give a load of extra powers and/or access to data to people who don't need it.

**Comment by diox** [comment]
> One option is to have a dict that's a lookup between "perm" strings django generates and our AclPermissions, defaulting to just checking for full admin like now.

Yeah, that's what I was thinking about and I'll try to go that route.

> As for is_staff, perhaps we can relax significantly that by just assuming that all access to /admin is by staff by the fact it needs VPN now. I can't remember what is_staff and is_superuser actually do though, practically, in the tools. Obviously we don't want to give a load of extra powers and/or access to data to people who don't need it.

At the moment since `is_staff` requires `Admin:%` and `is_superuser` requires `*:*` I'm not sure there is much difference... This will definitely need to change.

`is_staff` only gives access to the admin tools without opening any specific part of it (so if a user only has `is_staff` without `is_superuser` and without any permissions, ignoring VPN, they'd be able to log on the admin tools which would then be completely empty and not allow anything to be done)

With an overhaul of the way we do permissions, we could actually get rid of the separate staff admin: we'd give everyone that needs admin tools `is_staff` somehow, then the permission checks would guard the specific tools inside.

**Comment by diox** [comment]
As part of this, `AdminTools:View` permission is replaced by `Admin:Tools`. This still allows the same thing: access to admin tools living under `/admin` that are not based on django admin (i.e. not `/admin/models`)

**Comment by AlexandraMoga** [comment]
@diox I went through your comments related to everything that changed here but I'm not absolutely certain that I'm getting the full picture:
- is "Staff' as a group no longer available?
- is Admin:Curation permission assigned to a specific group?
- are other permissions affected by these changes?

I'm just trying to make sure I'm testing all the important parts affected by these changes.
Thank you

**Comment by diox** [comment]
`Staff` group is still there. What changed is an internal `is_staff` method which, annoyingly, has nothing to do with that group.

What changed is:
- `Admin:Curation` is introduced. This is given only to a new group called `Content Curators`. For more details about this part, check out https://github.com/mozilla/addons-server/issues/7253
- The way we determine who has access to the admin tools have changed, but so far this should be transparent. You need to be in a group with `Admin:Tools` to see them, this permission is given to `Staff`, and obviously `Admins` should be able to access it as well.
- Also, the django admin, which is `/admin/models`, is now accessible to anyone with `Admin:Tools`, *but* the content seen there should be dynamic and depend on your permissions. Users with `*:*` (the `Admins` group) should see everything, users with `Addons:Edit` or `Admin:Curation` should see replacement add-ons only.

**Comment by AlexandraMoga** [comment]
I've verified several scenarios on AMO-dev and here are my results:

**Working:**
1. Users included in groups with `Admin:Tools` and `*:*` have access to `/admin/` and `/admin/models/`
2. Users with `Addons:Edit` and `Admin:Curation` permission can access `/admin/models/addons/replacementaddon/`

**Needs info:**
1. Admin users (with `*:*` permission) can't see all the tools available in django admin. Also, the tools list seems to fluctuate based on the pages accessed by the user. I've added two examples below with the tools available to Admins now in dev compared to the same page from stage:

- dev
https://www.screencast.com/t/BTFkWelWXvCr
- stage
https://www.screencast.com/t/k87JbVzsF5y

2. Users with only "Admin:Tools" permission have view access to Replacement Add-ons without an additional `Addons:Edit` permission. Is this supposed to happen?

@diox could you please have a look at the two points mentioned in the Needs info section?

**Comment by diox** [comment]
@AlexandraMoga  Regarding 1, I'm fixing this. Regarding 2, which user were you testing with?

**Comment by AlexandraMoga** [comment]
@diox I've tried with user  testemaildev11, included in a test group for which I added only an "Admin:Tool" permission - see https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/50099/

**Comment by diox** [comment]
Are you sure you were testing with that user ? I've removed myself from `Staff` and added myself to that group, and I can't access Replacement Add-ons.

**Comment by AlexandraMoga** [comment]
Hm...I think I might have mixed my accounts somehow. I don't have visibility to any tools inside /admin/models/ with this account, as it should be.
Sorry for the noise.

**Comment by diox** [comment]
I fixed the other issue through https://github.com/mozilla/addons-server/pull/7964 so I think we're good now.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF59, WIn10x64

All the available tools are now displayed to Admin users:

![image](https://user-images.githubusercontent.com/31961530/38247343-99db9126-374d-11e8-8b7e-316ea8ccd041.png)
