### ISSUE TITLE
Theme can't be installed for preview in the browser from static theme review page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7850]
Follow up for #7765 

STR:

1. Log in to Reviewer Tools on AMO-dev and select 'New Add-ons' from reviewer's dashboard
2. In the New add-on queue filter by Themes(static) - [this link](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/new?searching=True&text_query=&needs_admin_code_review=&application_id=&addon_type_ids=10)
3. Select a theme pending for review (one of the more recent ones)
4. In the theme review section click on 'Download' to view the theme in the browser

Actual result:
Theme can't be installed because Firefox identifies it as corrupt

Expected result:
Static theme reviewers should have an option which gives them the possibility to preview the theme in the browser

Notes:
- I think themes can't be installed because they are not approved (signed) at this point
- I've tested with AMO-dev, Nightly 61.0a1, Win10x64 and set `xpinstall.signatures.required` to `false`

![theme error install](https://user-images.githubusercontent.com/31961530/37608159-84086f2e-2ba2-11e8-9817-10b4fc73488b.gif)

**Comment by eviljeff** [comment]
> I think themes can't be installed because they are not approved (signed) at this point

You're correct.  This is the same as other webextension based add-ons since the id became optional in Firefox 48.  We can't really fix this on the AMO side (if we could, we'd fix it for all add-ons, not just static themes)
