### ISSUE TITLE
Remove "Reject multiple versions" action for static themes in reviewer tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7851]
Follow up for #7765 

STR:

1. Log in to Reviewer Tools on AMO-dev and select 'Add-on Updates' from reviewer's dashboard
2. In the Add-on updates queue filter by Themes(static) - [this link](https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/updates?searching=True&text_query=&needs_admin_code_review=&application_id=&addon_type_ids=10)
3. Select a theme pending for review and click on Reject multiple versions

Actual result:
Reject multiple versions is applied only to the _approved version_ of the theme under review

Expected result:
Reviewers have the option to select _multiple versions_ to reject for the theme under review

Notes:
- reproduced on AMO-dev with FF59, Win10x64

![multiple version reject](https://user-images.githubusercontent.com/31961530/37609032-bb11ec3c-2ba4-11e8-97a9-a144b67b18eb.gif)

**Comment by diox** [comment]
This is not specific to static themes and is the expected behavior: "Reject multiple versions" is intended for public versions only. However one could argue that, since they are not auto-approved, this option is in fact a bit useless for static themes. Maybe we should remove it ? cc @jvillalobos

**Comment by jvillalobos** [comment]
Yes, I think it makes sense to not have "Reject Multiple Versions" for static themes.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/38191058-bc41e8ca-366f-11e8-93b3-6fb659e101cb.png)
