### ISSUE TITLE
Document partial add-on objects returns from the search API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#7856]
Document how the [search](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search) endpoint returns add-ons that contain a `current_version` object without a `license` field. Are any other fields missing?

**Comment by kumar303** [comment]
@diox do you know what other fields might be missing from the search endpoint? We just need to know how to deal with it for the frontend code.

**Comment by diox** [comment]
I think it used to be documented... maybe we lost that in a refactor. The only differences should be:
- Similar to `current_beta_version`, `current_version` omits `license` and `release_notes`
- Objects inside the `authors` array do not get a `picture_url`
