### ISSUE TITLE
Generate migration for footer removal from RereviewQueueTheme model

### ISSUE THREAD

**Issue by CuriousLearner** [mozilla/addons-server#7858]
### Describe the problem and steps to reproduce it:
The `footer` attribute on `RereviewQueueTheme` model will be removed in PR: https://github.com/mozilla/addons-server/pull/7718 as part of issue: https://github.com/mozilla/addons-server/issues/5379

We need to generate a migration that removes the field from the database.

Also remove `personal_footer` folder

### What happened?
Footer field is currently maintained in the DB.

### What did you expect to happen?
Footer field should be removed from DB.

**Comment by EnTeQuAk** [comment]
This should also address https://github.com/mozilla/addons-server/pull/7718#discussion_r175695796 (`If this lands we should remove all files in that folder too`) as well once deployed.

**Comment by EnTeQuAk** [comment]
There's nothing you can do specifically, it's just a reminder to remove those files once this change will be deployed. It'll be removed directly from our servers, correct.

**Comment by CuriousLearner** [comment]
@EnTeQuAk Sure, thanks!

I've raised the PR. Can you please review that? https://github.com/mozilla/addons-server/pull/7859
