### ISSUE TITLE
[Reviewer Tools] Weighting Threshold Adjustment

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#7863]
At the moment, thresholds are set to end at the mark and new threshold to start from higher weighting.
A minor change in threshold formula from > to >= would prove beneficial. In other words, the threshold should belong to the next higher level.

For example, weighting of 20 is applied for Native Messaging.

Currently, that would put it in 0-20 band and consequently in the ignore band.

Options are:
- Assign 21 instead of 20 to move it to a higher band (same with all other criteria)
- Change the band to 0 - 19 and new band 20- n

I think the second option would be neater to implement.

Above example is not the only one. Many add-ons end up on a lower weighting bandwidth since round figures are used and they end up on the threshold.

Currently:

POST_REVIEW_WEIGHT_HIGHEST_RISK 151+
POST_REVIEW_WEIGHT_HIGH_RISK 101-150
POST_REVIEW_WEIGHT_MEDIUM_RISK 21-100
POST_REVIEW_WEIGHT_LOW_RISK 0-20

Suggestion:
POST_REVIEW_WEIGHT_HIGHEST_RISK 150+
POST_REVIEW_WEIGHT_HIGH_RISK 100-149
POST_REVIEW_WEIGHT_MEDIUM_RISK 20-99 
POST_REVIEW_WEIGHT_LOW_RISK 0-19 ( between 0 < 20)

**Comment by eviljeff** [comment]
@wagnerand for consideration

**Comment by wagnerand** [comment]
Philipp and I are working on updating the weights, risk categories and points. I'm closing this an open a new issue once we have the final numbers.
