### ISSUE TITLE
If a theme is opened from list of flagged themes in rev tools, then no option is provided for reviewers

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#7871]
Steps to reproduce : 
1.Login to AMO-Stage with an account with reviewers permissions
2.Go to https://reviewers.addons.allizom.org/en-US/reviewers/themes/flagged
3.Select any theme from the list

Expected results:
The teme is opened and some options(Approve, Reject, etc.)  are provided for reviewers

Actual results:
No options are provided for reviewers

NOTES:
This is reproducible only for Flagged themes(working for new or updated themes)

Please see a video for this issue : 
![flaggedthemes](https://user-images.githubusercontent.com/1583842/37714550-74cedf94-2d22-11e8-85df-bc5381c76f1c.gif)

**Comment by eviljeff** [comment]
marking this low priority because LWT are going to be replaced by static themes soon
