### ISSUE TITLE
Rejection reason is displayed in review history even if the theme was approved.

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#7872]
Steps to reproduce:
1.Login to AMO-Stage with an account with review permissions
2.Go to https://reviewers.addons.allizom.org/en-US/reviewers/themes/pending
3.Select any theme, select Reject button and chose a reason for rejection
4.Change your mind and approve the theme, then press Commit Review button
5.Press Your Review History button

Expected results:
No reason is listed under Reason column for previously approved theme

Actual results:
Reason chosen at step 3 is displayed under Reason column

Please see a video for this bug : 
![rejectapprove](https://user-images.githubusercontent.com/1583842/37714935-69362b00-2d23-11e8-91e2-4c6a806788ed.gif)

**Comment by eviljeff** [comment]
marking this low priority because LWT are going to be replaced by static themes soon

**Comment by eviljeff** [comment]
and closing because LWT is deprecated
