### ISSUE TITLE
Generate simple theme preview for thumbnails

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7888]
As @diox observed, an entire page full of downsized versions of our current static theme previews, complete with representations of the browser chrome, may not look so good.  

We want to show a realistic representation of what the theme will look like, but at the same time it has to look appetizing enough to want to install it.  One solution could be to render a simple version of the theme as the thumbnail, e.g. just the background images, without the extra UI for tabs, toolbars, etc., rather than just resizing the full size preview.  An obvious downside is that without the toolbars being rendered - which might have profoundly contrasting colors - the thumbnail might be a very flawed render.

@jvillalobos to ponder/despair/comment

**Comment by jvillalobos** [comment]
> may not look so good

Do you have a screenshot or mock I can look at? I'd like to understand what you're picturing.

**Comment by eviljeff** [comment]
I did a bit of html tinkering to show what static themes would look like mixed in with LWT results.  New frontend currently uses the full LWT 680x100 preview and then does some tricks with scaling/clipping on the search results and landing pages for the responsive design - but displays them 64px high.  

You can see the sample static theme inserted into each page, with both the Firefox UI style preview we're going to use for the detail pages and the "simple preview" I was suggesting.  TBH I'm not convinced about the "simple preview" now I see it.

Themes landing page (wide browser)
![screenshot 2018-03-27 18 22 41](https://user-images.githubusercontent.com/768592/37962170-e10e542c-31ec-11e8-9e32-57fdf31f74ca.png)
Search results / category list page (wide browser)
![screenshot 2018-03-27 18 22 50](https://user-images.githubusercontent.com/768592/37962176-e57183c2-31ec-11e8-8228-d1fae8674f6e.png)
Themes landing page (narrow browser)
![screenshot 2018-03-27 18 23 09](https://user-images.githubusercontent.com/768592/37962182-e8d74862-31ec-11e8-91bf-68b54ad652b5.png)
Search results / category list page (narrow browser)
![screenshot 2018-03-27 18 23 24](https://user-images.githubusercontent.com/768592/37962187-eac3c61e-31ec-11e8-8e02-19ea7dc1bd0d.png)

**Comment by eviljeff** [comment]
Also, as you can see, the careful preview we rendered is getting either badly scaled or cropped too.

**Comment by jvillalobos** [comment]
Cropping is unavoidable, I suppose. It'd be nice if the shelves expanded vertically to become 2x2 rather than 1x4, but that's a separate discussion.

What I'd like to avoid is what is shown in the "Search results / category list page (wide browser)" screenshot, which is cropping the image vertically. Can we at least make sure the full height of the preview is shown? Maybe in the future we can do some fancy expand or scroll on hover, so the user can inspect the rest of the preview from those pages.

**Comment by eviljeff** [comment]
I can refile some of this on addons-frontend, specifying what changes are needed there.

What about the preview itself though -  do you think the "full" preview, complete with illustrative Firefox UI, scaled down and cropped horizontally where necessary, is okay?  I.e. the "simple preview" idea and this issue is a wontfix?

**Comment by jvillalobos** [comment]
I think the cropped "full" preview is a better way forward than the "simple" one. So yeah, I think we can close this one.

**Comment by eviljeff** [comment]
closing this issue.  Frontend work has been logged as mozilla/addons-frontend#4661
