### ISSUE TITLE
Reviewers cannot click the extension's main screenshot thumbnail anymore.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#7892]
### Describe the problem and steps to reproduce it:
Go to any review link, for example https://reviewers.addons.mozilla.org/en-US/reviewers/review/instarss

Try to click the main screenshot thumbnail.

### What happened?
There is not a full image showing up.

### What did you expect to happen?
The full size image should appear via jquery-lightbox

### Anything else we should know?
The DOM element "#addon-summary-wrapper" is now showing up on top of the DOM element ".secondary" that contains the image.

Reproducible on Chrome and Firefox.

**Comment by caitmuenster** [comment]
Thanks @spoji! Bumping this up in priority as the content reviewers need to be able to see the screenshot thumbnail to approve content.

**Comment by spoji** [comment]
For content reviewers that needs a quick solution for this :

 - Go to the inspector tool (F12)
 - Find and delete the DOM element with the id "addon-summary-wrapper"
 - Click the image

**Comment by diox** [comment]
Bisecting this indicated that it broke in 187bee262e81fd155db9f64c5f4b4208fb7fea81 (#7805) which is not super surprising. Now to find out why...

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF59, Win10x64

Screenshots can be previewed and navigation through image gallery is possible:

![image prev](https://user-images.githubusercontent.com/31961530/37907804-d35cc34c-310e-11e8-9642-9ab950ff6d42.gif)


For all the related issues discovered, new bugs were filed.
