### ISSUE TITLE
Wide images are not fully visible for preview in static theme review page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7896]
Follow up for #7765 

STR:

1. Log in to Dev Hub and submit a new static theme (I used the wizard and uploaded a header image of 3000x200px)
2. After submission, go to Reviewer Tools and search for your theme in the New Add-ons list (see https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/brave-cat)
3. Check the theme preview section and navigate to see all the associated images

Actual result:
Images with a higher width can't be fully inspected in the image viewer

Expected result:
The reviewer should be able to fully inspect wider images in the static theme review page

Notes:
Reproduced on AMO-dev, FF59 Win10x64

![image](https://user-images.githubusercontent.com/31961530/37819660-e9e14ee2-2e86-11e8-83ce-7e707ecb755e.png)

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59 Win10x64

A preview with a hover property is present for all the images composing a static theme:

![st hover](https://user-images.githubusercontent.com/31961530/38803269-59b29f34-4177-11e8-9f03-94cf82f7fbfc.gif)

@eviljeff couldn't there also be a hover for the main theme preview?

**Comment by eviljeff** [comment]
> @eviljeff couldn't there also be a hover for the main theme preview?

Hover is for exposing backgrounds that are scaled down to fit on the page but the preview is already displayed at the full size its rendered at.
