### ISSUE TITLE
Show the developer agreement page on April 1 again.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7899]
The review policies become effective April 1, so we need to show the developer agreement page to everyone starting from that date to make sure they have accepted the new policies.

**Comment by wagnerand** [comment]
STR for testing:

Note: The `config` mentioned below refers to a config setting (`/admin/models/zadmin/config/`). The config key is `last_dev_agreement_change_date` and the value is a date in the following format: `2018-04-01 15:00`.

a) Without a config set, make sure that:
  1. a new developer is shown the developer agreement page when submitting a new add-on.
  2) an existing developer (that has already agreed to the developer agreement since October 2017) is *not* shown the developer agreement while submitting a new add-on.

b) Set the config date to some day in the past (but not before October 2017). Make sure that:
  1. a new developer is shown the developer agreement page when submitting a new add-on.
  2. an existing developer (that has already agreed to the developer agreement after the date you set) is *not* shown the developer agreement while submitting a new add-on.
  3. an existing developer (that has agreed to the developer agreement before the date you set) is shown the developer agreement while submitting a new add-on.

c) Set the config date to some day in the future. Make sure that:
1. a new developer is shown the developer agreement page when submitting a new add-on.
2. an existing developer (that has already agreed to the developer agreement since October 2017) is *not* shown the developer agreement while submitting a new add-on.

d) Set the config date to some invalid value (an invalid date or not a date at all). Make sure that:
  1. a new developer is shown the developer agreement page when submitting a new add-on.
  2) an existing developer (that has already agreed to the developer agreement since October 2017) is *not* shown the developer agreement while submitting a new add-on.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF59, Win10x64

I've gone through all of the above scenarios and the results were as expected.
