### ISSUE TITLE
Allow uploading larger screenshots on devhub

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7908]
Part of #7907.

The developer hub must allow image uploads of up to 1280x800, both in PNG and JPG format. I believe we already do post-upload processing to ensure the images have a reasonable file size, but if I'm wrong about it, we need to do something like that.

**Comment by jvillalobos** [comment]
This maximum is the same that the Google Chrome Store sets, which makes it easier for developers to have the same/similar images for both listings.

**Comment by eviljeff** [comment]
I believe we do allow larger screenshots to be uploaded, but then downscale them.  Is 1280x800 to be the new standard size, or are you asking for an additional size in addition to 700x525?

**Comment by jvillalobos** [comment]
There are a few things at play:
* What is accepted in the upload form. If we're already accepting 1280x800 or larger, then we're good on this point.
* What dimensions of thumbnails are we generating from these uploads. The Chrome Web Store recommends 1280x800 or 640x400, so ideally we should aim for the same ratio to make developers' lives easier.
* Which thumbnails we show on the front end. That's the frontend dependencies of #7907.

**Comment by eviljeff** [comment]
@jvillalobos can you clarify what thumbnail size we want?  Currently we generate 200x150.  You want to increase that to 640x400?  (Is that not a little large for a thumbnail?)

**Comment by jvillalobos** [comment]
1280x800 and 640x400 are the dimensions recommended to developers by the Chrome Store. I suggest we use the same aspect ratio for the thumbnails we generate, but not necessarily the same size. We could aim for something like 320x200, which is close to the current sizes.

**Comment by eviljeff** [comment]
From discussion:
We're going to create a single max 1280x800 preview, and a 320x200 thumbnail.  

Frontend will initially consume this 1280x800 preview and display at full size (or whatever fits on screen) but will also look at using `srcset` to use other sizes - and addons-server will return other sizes when we know what we need.

**Comment by eviljeff** [comment]
Discussion with @willdurand ^ (need link to srcset issue)

**Comment by willdurand** [comment]
> and a 320x200 thumbnail.

strict? or max size? 😋

**Comment by AlexandraMoga** [comment]
I've checked the devhub screenshot upload component on AMO stage by uploading several image types of various sizes
I haven't noticed issues at upload and the previews are generated. 

I have found that the new thumbnail size is breaking the layout of add-on reviews page for which I filed #8584 

I'm going to mark the issue as verified fixed on AMO stage with FF60, WIn10x64
