### ISSUE TITLE
Show maximum and recommended screenshot sizes on devhub

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#7909]
Part of #7907 

Add the following text below the `Add a Screenshot...` button:

> PNG and JPG supported. The maximum and recommended size for screenshots is 1280x800 pixels. 640x400 pixels is a good alternative if you only have smaller images. Having screenshots in your listing page greatly increases its chances of being installed and being featured in the homepage.

/cc @devaneymoz @atsay for content review (Meridel too?).

**Comment by vcarciu** [comment]
Verified as fixed : 
![addscreenshot](https://user-images.githubusercontent.com/1583842/41665096-d326b0ba-74af-11e8-8289-66829f68f560.png)
