### ISSUE TITLE
Non-legacy reviewers do not have access to extension code and validation information 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7911]
Prerequisites: Log in with a user with no legacy reviewer permissions (i.e. can have only `Addons:PostReview` or `Addons:ContentReview` permissions)

STR:
1. Log in to Reviewer Tools and select the Auto-approved add-ons queue from the dashboard
2. Pick an add-on that is pending for review to access its review page
3. In Add-on history section, click on Validation/Contents link

Actual result:
The user does not have access to validation information and code for the reviewed extension

Expected result:
The user should be allowed to inspect validation information and  code for the reviewed extension

Notes:
- even if the user has `Reviews:Admin` permissions, this information is not available 
- the information will be displayed if the user is added to the `Reviewers:Legacy` group
- reproduced on AMO-dev and stage with FF59, Win10x64

![oops-content](https://user-images.githubusercontent.com/31961530/37897647-52cd15b6-30ef-11e8-8904-266e68fbe79a.gif)

**Comment by diox** [comment]
It's a problem, but this is not new - the permission check uses `check_addons_reviewer()`, which uses `Addons:Review` if the add-on is listed - that hasn't changed recently.
