### ISSUE TITLE
Screenshot thumbnail should not be present in static theme review page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7912]
Follow up for #7892 

STR:

1. Log in to Reviewer Tools and select the 'New Add-ons' queue from the dashboard
2. Filter the results by 'Themes(static)' and select a theme pending for review
3. Observe the top section of the theme review page

Actual review: 
There is a screenshot thumbnail present right below the theme preview section, also impacting the layout for the theme description

Expected result:
Screenshot thumbnails should not be displayed in static theme review pages (unless they are intended for a specific use)

Notes:
 - probably introduced by #7901 
 - reproduced on AMO-dev, FF59, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/37899069-1a5a1392-30f3-11e8-8ddc-5db09d0b7b35.png)

**Comment by diox** [comment]
@eviljeff any reason not do do this? :+1: 
```diff
diff --git a/src/olympia/reviewers/templates/reviewers/addon_details_box.html b/src/olympia/reviewers/templates/reviewers/addon_details_box.html
index 0657e681e3..89c06570b0 100644
--- a/src/olympia/reviewers/templates/reviewers/addon_details_box.html
+++ b/src/olympia/reviewers/templates/reviewers/addon_details_box.html
@@ -1,4 +1,5 @@
   <div class="addon-info-and-previews">
+    {% if addon.type == amo.ADDON_STATICTHEME %}
     <div id="addon-theme-previews-wrapper">
       <div>
         {% with previews = version.previews.all() if version else [] %}
@@ -21,6 +22,7 @@
         {% endfor %}
       </div>
     </div>
+    {% else %}
     <div class="addon-previews">
       {% if addon.all_previews %}
         {% with preview=addon.all_previews[0] %}
@@ -33,7 +35,8 @@
         <img class="screenshot thumbnail" src="{{ addon.thumbnail_url }}"
           alt="" width="200" height="150" />
       {% endif %}
-    </div>{# /secondary #}
+    </div>{# /addon-previews #}
+    {% endif %}
 
     <div class="addon-info">
       <p{{ addon.summary|locale_html }}>{{ addon.summary|nl2br }}</p>
```

**Comment by eviljeff** [comment]
Only that I was trying to avoid adding more template conditionals unless it was really necessary - it's not possible with css?

**Comment by diox** [comment]
It's totally doable with css, yeah. The template way is not strictly necessary, but does avoid useless db queries, so it balances out the additional complexity...

**Comment by eviljeff** [comment]
I didn't think with the review page extra db queries were worth worrying about.  I don't care that strongly about it though.

**Comment by diox** [comment]
I don't think it's really worth worrying about, just a nice bonus :) I'll see which way feels simpler.

**Comment by jvillalobos** [comment]
From #7855:

> * The preview image appears above the metadata, and it looks strange along with the generic image on the left column of the metadata. I suggest moving it below the metadata, with a title above it ("Theme Images").
> * A counter for the images would be handy, so reviewers know whether they should click through. It could be a line of text below the preview image ("2 images").

Hiding the thumbnail helps, but the other comments also address the hidden behavior of clicking on it to see a larger preview and the other background images in the theme.

**Comment by eviljeff** [comment]
Taking this from @diox 😛 because I'll fix the rogue preview image at the same time as #7896 (and the counter is going to be unnecessary with the change to how background images will be presented.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/38799816-3234dba6-416e-11e8-998e-4c35f873e8db.png)
