### ISSUE TITLE
Add-on info is placed after the thumbnail in review page if summary is too long

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#7913]
### Describe the problem and steps to reproduce it:
- Go to the review page for an add-on containing a large enough description

### What happened?
- Add-on info is displayed after the thumbnail
![reviewer-tools-no-flex](https://user-images.githubusercontent.com/187006/37902684-808bea26-30f5-11e8-9c3f-ae04b3553520.png)

### What did you expect to happen?
- Add-on info should always be placed in the same "row" as the thumbnail.

### Anything else we should know?
This is probably caused by the fix for https://github.com/mozilla/addons-server/issues/7892

Maybe we should go back to floats for this, or fix the flex rules.

See also https://github.com/mozilla/addons-server/issues/7912

**Comment by diox** [comment]
Note: the obvious solution is to remove the `wrap` on `.addon-info-and-previews` `flex-flow` but it was added to handle static themes previews, letting them take the first row and then wrap before displaying the rest. This is still possible, just need to be smarter about it.

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/7914

**Comment by eviljeff** [comment]
`addon.type` is in a class in <div id="addon"> if that helps to selectively remove it for non-themes

**Comment by AlexandraMoga** [comment]
@diox, I've compared the layout from dev with the current look from stage and there are some differences. You can see that stage looks a bit more 'organized' overall (rows are clearly delimited and there is more spacing between the two columns)

**[1] dev**
![image](https://user-images.githubusercontent.com/31961530/37951056-ab5ac37c-31a3-11e8-88e5-9ce39d92a36b.png)
**[2] stage**
![image](https://user-images.githubusercontent.com/31961530/37951066-b5c76194-31a3-11e8-89e5-be9339257cf8.png)

**Comment by diox** [comment]
No need for a new issue, I'll fix this here.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO dev and stage with FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/38020502-1196ed52-3283-11e8-9118-b12caba706c4.png)
