### ISSUE TITLE
Keyboard navigation in screenshots preview is not always accurate in reviewer tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7920]
STR:

1. Log in to Reviewer Tools and choose an add-on to view its review page (i.e. https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/simplecrew-webclipper)
2. Click on the main add-on screenshot to preview it
3. Exist screenshot preview
4. Click again on the main add-on screenshot
3. Press the left navigation key to preview the next screenshot

Actual result:
Navigation jumps to a non-consecutive image

Expected result:
Navigation keys will display the next/previous screenshots relevant to the key used

Notes:
 - this is not a new issue
 - reproduced an AMO dev and stage with FF59, WIn10x64

![keyb nav](https://user-images.githubusercontent.com/31961530/37952641-2a632a92-31a9-11e8-9b0d-f3f1b44dbdb8.gif)

**Comment by diox** [comment]
Note that it works fine the first time. 

It seems that each time you re-open the lightbox, keys will move forward one additional image. So the second time you open it, pressing right when viewing the first image will show you the 3rd one, and pressing it again will show the 5th. If you close and re-open the lightbox once more, again from the first image, and press right, this time it will jump to the 4th one, etc.

**Comment by AlexandraMoga** [comment]
Still reproduced
