### ISSUE TITLE
Show a banner in persona creation wizard to try static theme wizard

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7935]
After we launch static themes, but before we disable creating LWT, we could show a banner in the LWT wizard encouraging users to try out the static theme wizard instead.

Needs some rudimentary UX (color at least, but if more than a boring box, then that too) and messaging copy.

**Comment by jvillalobos** [comment]
I'm not sure we need a banner. We want to get early use from staff and big theme designers at first, and then we'll do the switch. Also, before the switch, we will notify all theme designers about it, so we can mention how they can try it out.

**Comment by eviljeff** [comment]
sounds like a wontfix then.
