### ISSUE TITLE
Collections API appears to allow whitespace only collection names

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#7936]
Based on the report in https://github.com/mozilla/addons-frontend/issues/4652

The API should also presumably prevent white-space only collection names?

**Comment by muffinresearch** [comment]
@eviljeff how is this p4?

**Comment by eviljeff** [comment]
User enters a nonsense name; user gets a broken collection.  p4 because low impact to anyone else and they can edit the collection again to fix it, looking at the screencast. Bump it up if you want.

**Comment by muffinresearch** [comment]
> User enters a nonsense name; user gets a broken collection. p4 because low impact to anyone else and they can edit the collection again to fix it, looking at the screencast. Bump it up if you want.

Yeah I can see that the impact is minimal if this state is self-inflicted. However, I also think we should increase the priority on the basis that we should _always_ validate against bogus data getting into the system.

**Comment by rafspiny** [comment]
I would like to be assigned to this one if it is ok.

**Comment by eviljeff** [comment]
@rafspiny okay, go ahead.  I think the fix would be in https://github.com/mozilla/addons-server/blob/master/src/olympia/bandwagon/serializers.py#L43:L51

**Comment by rafspiny** [comment]
@eviljeff I added a test like this:
```python
    def test_edit_only_spaces_in_name(self):
        """Let's put only spaces in the collection name."""
        collection_name = 'awesome_collection_vol_1'
        self.create_collection(name=collection_name)
        url = reverse('collections.edit', args=['admin', self.slug])

        r = self.client.post(url,
                             {'name': '   ', 'slug': self.slug,
                              'listed': True}, follow=True)
        # assert r.status_code == 200
        c = Collection.objects.get(slug=self.slug)
        assert unicode(c.name) == collection_name
```

Although this test seems to be legit, is unexpectedly passing. Probably, I missed something, but I would have expected this test to fail.

Then I realised that I was looking at the view, not the API. I should look at the API explained here: https://addons-server.readthedocs.io/en/latest/topics/api/collections.html

Is that correct?

**Comment by eviljeff** [comment]
@rafspiny yes, that's the legacy view, rather than the API views.  If you add your test to `CollectionViewSetDataMixin` in test_views.py it will apply to both Collection creation and updates. There are few methods already which show how the tests are written.  `CollectionViewSetDataMixin.test_biography_no_links` is quite similar to what you need to test - it would just be doing `data.update(name=u'   ')` rather than `data.update(description=...)`.  Note the testing of both a flat string and a dict for localized values.

**Comment by AlexandraMoga** [comment]
I have tested this by enabling the "Save Collection" button from DevTools and entering only blank spaces in the collection name field. The form can't be saved unless actual characters are provided. 

Marking as verified fixed on AMO-dev with FF59, Win10x64

![white space coll](https://user-images.githubusercontent.com/31961530/39250669-011f8b04-48aa-11e8-97f1-e138be90bc84.gif)
