### ISSUE TITLE
Original icon filename extension should not always be 'png'

### ISSUE THREAD

**Issue by hiikezoe** [mozilla/addons-server#7940]
We always use '.png' for original icon image files even if the original file is a jpeg image, it's super weird.  Given that we will support SVG (#4161), should we drop the filename extension?

**Comment by diox** [comment]
Yeah, it's a bit weird. We do need to be careful and make sure we can always guess the path though, without having to store yet another field in the db just for this.

**Comment by hiikezoe** [comment]
> We already use '.png' for original icon image

I meant 'always use'.  :)

**Comment by muffinresearch** [comment]
@hiikezoe not sure if it's being used to bugzilla, but you can edit your original issue description in Github :)

**Comment by hiikezoe** [comment]
Oh, thanks.
