### ISSUE TITLE
Update FxA SQS settings for stage&prod

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7941]
Follow from #6451 ; arns from https://bugzilla.mozilla.org/show_bug.cgi?id=1419516#c4

arn:aws:sqs:us-east-1:927034868273:amo-account-change-dev / amo-account-change-dev
arn:aws:sqs:us-east-1:142069644989:amo-account-change-stage / amo-account-change-stage
arn:aws:sqs:us-west-2:361527076523:amo-account-change-prod / amo-account-change-prod

-dev is already there but should probably be moved out of settings_base into the dev conf.

**Comment by eviljeff** [comment]
QA:
same procedures as #6451 but this time on stage.  Prod will be enabled by ops once stage is verified.

**Comment by vcarciu** [comment]
@eviljeff  : Changing secondary email with primary email in fxa will not change the email from account settings page on Stage (it's working on -dev) : 
![secondarymail](https://user-images.githubusercontent.com/1583842/38357066-3a65a726-38ca-11e8-9997-af0ddfc0d2bf.gif)

**Comment by eviljeff** [comment]
The sqs messages FxA is sending are from their stage server (which we don't use).  Filed mozilla/fxa-auth-server#2387 to fix.

**Comment by eviljeff** [comment]
QA: should be working now.  As before, this only applies to AMO stage.

**Comment by AlexandraMoga** [comment]
I have verified this on AMO stage an here are my test results:

1.Have your AMO account page open
2.Open FxA page in a new tab to add a secondary email to your account, then set it as a primary e-mail 
=> change is reflected in AMO user account page once the page is refreshed

@eviljeff  for the first time you reset your primary email address in FxA, the changes are applied in AMO. When re-setting the email the second time, the changes are no longer visible in AMO when the account page is refreshed. I have logged #8384 to explain in more detail

**Comment by AlexandraMoga** [comment]
Verified via #8384
