### ISSUE TITLE
"image/jpg" is invalid MIME type

### ISSUE THREAD

**Issue by hiikezoe** [mozilla/addons-server#7943]
We have 'image/jpg' in IMG_TYPES, but it's actually invalid.

As per [MIME type document on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types), the correct mime type for jpeg image is only 'image/jpeg'.

**Comment by muffinresearch** [comment]
@hiikezoe Can you add an STR to this issue please?

**Comment by muffinresearch** [comment]
> @hiikezoe Can you add an STR to this issue please?

Looks like this dates back a long, long way to https://github.com/mozilla/addons-server/commit/a89b89f129fd690bc98606ed0417ba8d4b6ecb2d I can't see any comments in the related bugzilla issues re: any compat reasons for this being done then, so we can probably forgo an STR.

**Comment by diox** [comment]
QA: make sure you can still upload jpg images everywhere in devhub.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/pull/7944 fixed this.

**Comment by ioanarusiczki** [comment]
This was tested in #7947 I'm marking this verified fixed on AMO dev with FF59(Win10)
