### ISSUE TITLE
Incomplete status  after making an add-on visible again before auto-approval

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7946]
STR:
1. Submit an add-on 
2. Before the add-on is auto-approved from the versions page click on Invisible.
3. Observe that the status changes from Awaiting Review to Invisible.
4. Click on Visible.
5. Observe the status.  

Expected result:
The Awaiting Review status is displayed.

Actual result:
Incomplete status is displayed and the listed page is not available.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF59(Win10).
This issue is reproducible with static themes before approval.
It is not reproducible after add-ons are approved.

![status incomplete](https://user-images.githubusercontent.com/33448286/38097451-1a80f100-337e-11e8-8218-5fa37931adf0.gif)

**Comment by diox** [comment]
Similar to https://github.com/mozilla/addons-server/issues/3051 , could be a dupe.

**Comment by ioanarusiczki** [comment]
@diox Yes, I filed a different issue for this scenario because I could not tell if technically this could be a dupe of https://github.com/mozilla/addons-server/issues/3051

**Comment by ioanarusiczki** [comment]
Now reproducible with static themes too FF65(Win10)

![static themes version one](https://user-images.githubusercontent.com/33448286/52861801-44962480-313c-11e9-9df8-1d3fc3d617ac.gif)
