### ISSUE TITLE
Reuse IMG_TYPES for 'data-allowed-types'

### ISSUE THREAD

**Issue by hiikezoe** [mozilla/addons-server#7947]
Once we drop 'image/jpg' from IMG_TYPES (#7944), we should reuse it for 'data-allowed-types' so that we can simply add 'image/svg+xml' in IMG_TYPES when we support SVG images.

**Comment by diox** [comment]
QA: Make sure images upload across the site works, including rejecting non-images.

**Comment by ioanarusiczki** [comment]
I verified upload of images for the user profile thumbnail, add-on icons and screenshots, uploads for
lightweight themes and static themes.  
For the observed issues I filed https://github.com/mozilla/addons-server/issues/7954 and https://github.com/mozilla/addons-server/issues/7956
This was verified on AMO dev with FF59 (Win10).
