### ISSUE TITLE
Show a different 404 message for unlisted/removed add-ons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#7953]
### Describe the problem and steps to reproduce it:
1. Publish and add-on
2. Get some downloads and users
3. Remove your add-on from the site
4. Try to visit the old URL and get a generic 404 message

Right now add-one that have been removed/unlisted from the site, by the author or by admins/review team, always show a 404 message saying the add-on can’t be found.

This means we get a lot of big reports for unlisted addons we have to triage, which we can’t even do effectively without them checking to see if there’s a typo in their url or what. It’s lead to us giving user support in github, and also isn’t a very useful error message for users. 404s happen by mistake all the time in the real world, so users legitimately believe they’ve encountered a bug instead of an unlisted add-on.

I think if an add-on has been listed publicly and then is removed, we should still output a 404 status code as the add-on can’t be found, but it’d be nice if the API sent an extra message/reason code we could use on the Front end to say “this add-on used to exist but has been removed” or whatever.

### What happened?
Generic not found message with plenty of github issues.

### What did you expect to happen?
Error message that explains the problem,because it’s always what we end up saying on github to users anyway.

### Anything else we should know?
I’m shocked by the number of users looking to install crypto mining add-ons 😁

**Comment by diox** [comment]
The API already returns `is_disabled_by_developer` and `is_disabled_by_mozilla` when an add-on still exists but has been disabled by the developer or well, Mozilla. The frontend already has code to handle that.

The only case that this does not handle is an add-on that has been deleted by the developer entirely, not just disabled (by them or by us). IMHO we shouldn't try to be handling this case: the developer has explicitly deleted the content, asking us to remove any trace of it.

**Comment by tofumatt** [comment]
Hmm... okay, I'll check the API results of add-ons we've been having issues with and report back.

But if an add-on was published on the open internet and then "permanently deleted", still showing a "no longer available" message might be nice. I don't think that's any kind of violation of user expectation/privacy in my mind, especially as we often end up responding in GitHub comments with "it was probably deleted" anyway. 🤷‍♂️

**Comment by CuriousLearner** [comment]
I would say that specific messages would definitely help in removing confusion. Although, I was curious to know this case:

- If I have an addon having slug `xyz` and I delete it.
- Someone else, or even me recreate an addon with `xyz`.

Does it have the same slug allocated?

**Comment by diox** [comment]
If an add-on is deleted - not just disabled - by its author then the slug becomes available again to everyone.

**Comment by jvillalobos** [comment]
This has been covered on other issues since then. The 404 message is now more informative about the possible reasons for the missing page. We still get issues filed for missing add-ons, and will get many more in the future, but I don't think there's much more we can do to mitigate it.
