### ISSUE TITLE
The icons are not updated immediately on the add-on detail page 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7954]
STR:
1. Go to Edit images in dev hub for a submitted ad-on
2. Click Upload a custom icon and select an image (I used a .png sample)
3. Save changes, click on view listing to see the icon
4. Go back to images and change the image (I used a .jpg sample this time)
5. Save changes, click on view listing again and observe the icon

Expected results:
The new photo is visible.

Actual results:
The first uploaded picture is visible.

Notes:
This issue was intermittent, it should be tried a couple of times by replacing the existing .png file with a .jpg. 
This scenario is also reproducible in Edit profile - when changing the profile picture for the new info card.
Refreshing page will display the right image.
It is reproducible on AMO dev and AMO stage with FF59 (Win10).

![changing icon scenario](https://user-images.githubusercontent.com/33448286/38195736-cc4d4fb2-3687-11e8-9406-8faa9d91dcab.gif)

**Comment by eviljeff** [comment]
It's likely just the processing time - we resize and crush the images on a celery task and only then is the image updated.  I'm guessing if you took a few seconds more to navigate to the listing page it would work?

**Comment by ioanarusiczki** [comment]
@eviljeff yes, if I take a couple of seconds and then navigate to the listing page it works.
