### ISSUE TITLE
Add-on custom icons are not correctly displayed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7956]
STR:
1. Go to Edit images in dev hub for a submitted ad-on
2. Upload a .jpg sample from edit images using upload a custom icon button
3. Save changes and click on View Listing
4. Observe the icon on the ad-on detail page

Expected result:
Images look a bit squashed.

Actual result:
Images are correctly displayed.

Notes:
This issue was reproducible for the user info card but then fixed [here](https://github.com/mozilla/addons-frontend/issues/4598).
This issue is reproducible with .jpg and .png samples with normal size and dimension, it is more obvious for images with a larger width.
This is reproducible on AMO dev with FF59(Win10).

![squashed image](https://user-images.githubusercontent.com/33448286/38197341-5067de72-3690-11e8-9a85-e9490b320a66.gif)

**Comment by diox** [comment]
@ioanarusiczki does that happen on stage as well, or only dev ?

**Comment by ioanarusiczki** [comment]
@diox it happens in stage too 

Here's the screenshot
![stage](https://user-images.githubusercontent.com/33448286/38235344-75cded66-3729-11e8-8a97-790f48c95d16.png)

**Comment by ioanarusiczki** [comment]
@willdurand https://github.com/mozilla/addons-frontend/issues/5388
