### ISSUE TITLE
Separator line is not correctly displayed on the second page of the theme wizard submission

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7957]
STR:
1. Go to dev hub to submit a static theme using the theme wizard.
2. Check the display of the separator line before the Cancel and Disable Version and Submit version at the bottom of the page.

Expected result:
There is some space between the licence section , line and the buttons.

Actual results:
Separator line is right next to the licence section, has no space.

Notes:
This issue is reproducible on AMO dev with FF59(Win10).

![separator line](https://user-images.githubusercontent.com/33448286/38201239-3e2a77f0-36a0-11e8-921b-8ee9b25cc88b.png)

**Comment by shiri1248** [comment]
I would like to work on this issue.

**Comment by caitmuenster** [comment]
Hey @shiri1248! Go for it! Mentor is @eviljeff. 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by deepanshu-jain1999** [comment]
I am new to open source and i want to work on this issue. Please help me

**Comment by eviljeff** [comment]
@deepanshu-jain1999 great, I don't know if @shiri1248 has started on this already though.

**Comment by eviljeff** [comment]
FYI, this wizard is turned off by default. If you are locally running addons-server on docker you can enable it by adding a flag (a "waffle switch") in django admin here: http://olympia.test/admin/models/waffle/switch/ called "allow-static-theme-uploads". It will look something like this:
![screenshot 2018-05-14 19 08 20](https://user-images.githubusercontent.com/768592/40015086-2ec2203a-57aa-11e8-97ae-d983908aefb6.png)

**Comment by deepanshu-jain1999** [comment]
Hello, Is there any direct url to access this page.

**Comment by eviljeff** [comment]
No - either submit a static theme in an xpi or use the static theme wizard.

**Comment by kajalsah** [comment]
Is this still up for grabs? I would like to take up this issue if it is available. I am totally new to open source and may require help. Thanks 😄

**Comment by eviljeff** [comment]
@kajalsah, yes. It looks like the previous contributers haven't worked on it.

**Comment by jsmnbom** [comment]
I'd like to work on this :D

**Comment by caitmuenster** [comment]
Go for it, @jsmnbom!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev - FF63 (Win10)

![the separator line](https://user-images.githubusercontent.com/33448286/48263778-ecaa9c00-e42f-11e8-8e0c-39d554184959.png)
