### ISSUE TITLE
Replacement add-on tool shows some behavior issues

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7963]
Prerequisites:
User logs in with an Admin account

STR:
1. Log in to AMO-dev, switch to the legacy site and select Admin Tools from the user menu
2. Go to 'Site Settings and Environment'  and select 'Django admin pages' option
3. From the list of available tools, choose 'Replacement addons' (https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/replacementaddon/)
4. Click on 'Add replacement add-on' button on the top right
5. Enter a guid for the add-on you want to replace and a path to the replacing add-on 
6. Save your entry  and observe the changes in the Replacement addon list

Actual results:
The number of  add-ons is not increased and the replacement add-on Path shows a guid again instead of the URL entered
 
Expected result:
the correct number of replacement add-ons is displayed when the list is updated and the add-on path shows the URL provided

Notes:
 - a different behavior observed with the list: the number of add-ons is updated correctly, but the last add-on added does not appear in the list or disappears after page refresh
 - reproduced on AMO-dev, with FF59, Win10x64

![repl addon tool](https://user-images.githubusercontent.com/31961530/38243772-3f40311a-3741-11e8-9496-feac7fedf77f.gif)

**Comment by eviljeff** [comment]
Might just be django admin's annoying caching?

**Comment by AlexandraMoga** [comment]
@diox I can't find issues with add-on count and the list is updated when I'm adding a new item.
However, the Path filed still doesn't record the path I've supplied. 

I have just added two more add-ons to the list - https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/replacementaddon/

**Comment by diox** [comment]
@AlexandraMoga count / old list showing up will still be an issue on stage/prod (should be fine on dev), but I've fixed the path editing.

**Comment by AlexandraMoga** [comment]
Retested after the fix and the Path field is now populated correctly. 

![image](https://user-images.githubusercontent.com/31961530/40647110-bc711406-6333-11e8-9a19-22e8078e1344.png)

Verified as fixed on AMO-dev with FF60, Win10x64
