### ISSUE TITLE
'Reject multiple versions' does not include version pending review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7968]
When rejecting multiple versions in the reviewer tools, a version that is currently pending review (not auto-approved) is not rejected.

STR:
1. Submit an add-on version. Wait for auto-approval to run.
2. As an admin reviewer, disable auto-approval (yellow button at the bottom of the page).
3. As the developer, submit another version.
4. As the reviewer, try to reject all versions using "Reject multiple versions"

Expected results:

Both the first (auto-approved) and the second (not auto-approved) versions should show up in the list of versions to be rejected.

Actual results:

The second (not auto-approved) version is not in the list of versions to be rejected.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59 (Win10).

![bothversions are rejected](https://user-images.githubusercontent.com/33448286/38561976-193a7db2-3ce2-11e8-81b6-3c84ceced8a1.gif)
