### ISSUE TITLE
April 2018 Disco Pane content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#7972]
For the **19 April** push, can we please REMOVE all current featured extensions and themes and REPLACE them with...

**Spring is Here** by [LisaAtTheBeach](https://addons.mozilla.org/firefox/addon/spring-i-368421-2/)

**Stop Facebook tracking** with [Facebook Container by Mozilla](https://addons.mozilla.org/firefox/addon/facebook-container/)
Isolate your Facebook identity into a separate “container” that makes it harder for Facebook to track your movements around the web. 

**Simplify search** with [Swift Selection Search by Daniel Lobo](https://addons.mozilla.org/firefox/addon/swift-selection-search/)
Just highlight text on any web page to search the phrase from an array of engines. 

**Dream of Waves** by [jrhd437](https://addons.mozilla.org/firefox/addon/dream-of-waves/)

**Ad blocking & privacy protection** with [Ghostery by Ghostery](https://addons.mozilla.org/firefox/addon/ghostery/)
A simple set-up lets you take control of the ads you see and how you’re tracked on the internet. 

**Re-imagine tabs** with [Tree Style Tab by Piro](https://addons.mozilla.org/firefox/addon/tree-style-tab/)
Do you have a ton of open tabs? Organize them in a tidy sidebar. 

**Space Stars** by [woutergude](https://addons.mozilla.org/firefox/addon/space-stars/)

@muffinresearch @diox @EnTeQuAk

**Comment by muffinresearch** [comment]
@EnTeQuAk would you be ok to pick this up for the push on the 19th?

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk would you be ok to pick this up for the push on the 19th?

Absolutely, also put it into my personal task-list for the 04.19 deployment

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59, Win10x64
The full content will be verified in production. 
![image](https://user-images.githubusercontent.com/31961530/38810928-d7ff676e-4190-11e8-818b-29d21984c6db.png)

**Comment by vcarciu** [comment]
Verified as fixed in prod.
