### ISSUE TITLE
While creating a collection a limited number of chars can be added when describing it

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#7975]
STR: 
1. Load AMO dev and go to Create a collection page.
2. Try to type in the Describe your collection field a longer text.
3. Save the collection and click edit this collection.
4. Try to continue adding text. Observe that the new front end allows adding more text in the field.

Expected results:
Description field while creating the collection allows adding a longer text.

Actual results:
Only a limited number of chars can be used in the description field.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF59 (Win10).

![testing describe your collection](https://user-images.githubusercontent.com/33448286/38306862-8b889ede-381a-11e8-9bd9-d31a7b747fb8.gif)

**Comment by eviljeff** [comment]
I'm a little confused about this issue - it's connected to a front-end change?  If it's a bug in the addons-server based edit collection page we won't be fixing it because its deprecated (in favour of the new addons-frontend edit collection page)

**Comment by bobsilverberg** [comment]
I was just typing what @eviljeff said. This is an old screen that is being replaced by a new front-end screen, and I don't think this has any connection to https://github.com/mozilla/addons-frontend/issues/4505. I think this can be closed.

**Comment by eviljeff** [comment]
going to close for now then - re-open with some clarification if we've misunderstood the situation.
