### ISSUE TITLE
Add an optional `firefox_url` field for custom "Download Firefox" URLs

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-server#7982]
### Describe the problem and steps to reproduce it:
The Facebook Container add-on has a custom URL to "Download Firefox", currently hard-coded to add-on ID on the frontend. This is fragile and not super-extendable, so it'd be nice if we could set a custom "Download Firefox" url for an add-on if it's part of a custom campaign or something.

Not sure if we want some kind of custom Mozilla-specific object in the add-on response for this kind of stuff, but it'd be nice to set it in the DB rather than hard-code it on the frontend, as obviously an add-on ID change will break what we did.

See: https://github.com/mozilla/addons-frontend/issues/4737

**Comment by jvillalobos** [comment]
There's an ongoing project (FIA) to enable creating Firefox builds that bundle an add-on with them. The idea is that, eventually, many/all add-ons on AMO would have a similar link (one idea is to offer Firefox+add-on if you visit an add-on page on AMO using a different browser).

The project is getting started and depending on the early results we will determine whether we should do something like this. /cc @atsay, who leads the FIA project.

**Comment by atsay** [comment]
We started exploring this late last year, and currently are able to create an installer with a hard-coded add-on. Problem is it's hacky, and there is no pre- or post-install experience. There's a [PRD](https://docs.google.com/document/d/1BukJcOsfXoP651IN8P2BTZ8jpc83KAa3caMKlpjTxDQ/edit) that isn't finalized but if interested feel free to take a look. We plan to start the x-func meetings for this project again next week.
