### ISSUE TITLE
Add a migrated_themes model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7988]
We need a table to link the original LWT and the static theme replacement.
It'll be needed for #7976 at least, and we may decide to do some other redirection/handling elsewhere in the future too.

**Comment by eviljeff** [comment]
Actually, i'm reconsidering the special model/table idea (after I finished the code and migration already) and think it may be best to add the field to the `Persona` model as every (non-deleted) LWT will be migrated.  If we want to clear up LWT data in the future we can just drop the unneeded columns at that point from Persona, leaving the links to the replacement static themes.

**Comment by AlexandraMoga** [comment]
Please add some STR to this issue or the label "qa:not needed"
