### ISSUE TITLE
Allow admin reviewers to undo approval confirmation

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#7989]
Sometimes mistakes happen and admins have to correct a review. Correcting a rejection is easy, but there is currently no way to undo a "Confirm Approval" or "Approve Content" action (and thus put it back into the review queue).

Admins need a way to revert "Confirm Approval" (for add-on reviews) and "Approve Content" (for content-reviews).

A button in lower of the page in the "More Actions" section that just removes the respective confirmation flag would be enough. Admins can elaborate then using a "Comment".

**Comment by jvillalobos** [comment]
Admins should be able to content-reject or code-reject add-ons after approval. If the review is known to be incorrect, you should know at that point that it should be rejected, no? How often does a case come up where a review was approved accidentally and can't be followed up on at the same moment?

**Comment by wagnerand** [comment]
In the recent case, an add-on was approved when it was meant to be content-approved (and therefore no code-review was involved). We didn't know whether it is safe or not, but we weren't able to put the add-on back into the queue for a reviewer to pick it up.

Instead we had to expedite the review (which wouldn't have been necessary, based on the risk) using an admin reviewer.

I don't expect that to happen too often, but having an option to put an add-on back into either queue sounds quite basic.

**Comment by eviljeff** [comment]
looks like this is a wontfix then
