### ISSUE TITLE
simplify our settings files

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#7997]
we have:

- settings.py
- settings_base.py
- dev/settings.py
- stage/settings.py
- prod/settings.py
(and settings_test.py)

with a lot of duplicate settings.  Let's simplify!

**Comment by ioanarusiczki** [comment]
@eviljeff Could you please provide some STR for QA or add the qa not needed label ? 
Thank you!

**Comment by eviljeff** [comment]
no specific QA needed - just make sure the sites are working as normal.

**Comment by ioanarusiczki** [comment]
I'm marking this issue verified fixed on AMO stage with FF59(Win10 and Android 8.0). 
Release testing is complete. Test results are [here](https://testrail.stage.mozaws.net/index.php?/plans/view/9257).
