### ISSUE TITLE
jjapan

### ISSUE THREAD

**Issue by otoha0x01** [mozilla/addons-server#8006]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by otoha0x01** [comment]
Nothing

**Comment by otoha0x01** [comment]
Nothing

**Comment by otoha0x01** [comment]
Nothing

**Comment by otoha0x01** [comment]
Hallo

**Comment by rctgamer3** [comment]
Please do not post empty and irrelevant to AMO-issues on this repo.
