### ISSUE TITLE
Regular reviewers should not be able to approve/reject add-ons pending admin content-review

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8012]
A regular reviewer should not be able to approve or reject an add-on that is pending admin content-review (and vice versa).

**Comment by eviljeff** [comment]
I'm not sure I entirely understand this issue.  Isn't content review about auto-approved webextensions?  How can they be approved or rejected by a legacy addon reviewer?  Unless you're talking about content reviewers approving or rejecting the content review?  ("regular" reviewer was ambiguous)

**Comment by wagnerand** [comment]
Yes, I didn't mean legacy reviewers. The issue is that a regular add-on (post) reviewer is able to approve or reject a webextension that is pending admin content-review.

**Comment by wagnerand** [comment]
STR:

a) 
1. Flag an add-on for admin add-on review (from the regular review page).
2. Go to the content review page and make sure you don't see "Approve Content" and "Reject multiple versions".
b)
1. Flag an add-on for admin content review (from the content review page).
2. Go to the add-on review page and make sure you don't see "Confirm Approval", "Reject" and "Reject multiple versions".

**Comment by vcarciu** [comment]
@wagnerand  : I verified following the steps from above : 
a)
![admincodereview](https://user-images.githubusercontent.com/1583842/38625032-40980444-3db2-11e8-9fa8-db27c7d7d328.png)

b)
![contentreview](https://user-images.githubusercontent.com/1583842/38625054-4e348190-3db2-11e8-9b71-6db63075c7cd.png)

Please let me know if anything else is needed

**Comment by vcarciu** [comment]
Marking issue as verified.
