### ISSUE TITLE
The user profile avarage ratings is updated with a delay 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8017]
Copied issue https://github.com/mozilla/addons-frontend/issues/4587 here

STR:
1. Load AMO dev and create a new account. 
2. Submit some add-ons.
3. Using a different account rate the add-ons.
4. Check the user info card of your new account to see if the average rating is updated.

Expected results:
Average rating of developer’s add-ons is displayed with dark grey for a developer with rated add-ons.

Actual results:
Average rating of developer’s add-ons is not updated until the next day. 

Notes:
This issue is reproducible on AMO dev with FF59(Win10).
I tested this using[ this](https://addons-dev.allizom.org/en-US/firefox/user/Contrating2/) account.  It did not update the ratings until the next day and only after I logged into it and used it to create collections.

**Comment by eviljeff** [comment]
This is deliberate - it's updated with a daily cron job that recalculates all users's average ratings.
