### ISSUE TITLE
Use separate activity log types for 'admin content review' and 'admin add-on review'

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8027]
When a reviewer requests admin review, the log entry just says "Super review requested", but it does not say which one (add-on vs content).

We should use separate activity log types so we can distinguish them on the review page and on the logs page.

**Comment by eviljeff** [comment]
while you're at it, add one for admin theme review too please :)  (#7855)

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF59 (Win10). 
Activity log types can be distinguished on the review page and logs page.

Super-review requested from Auto Approved add-on queue
![addon review](https://user-images.githubusercontent.com/33448286/39193630-b87facaa-47e4-11e8-80b4-b243cbab10ba.png)

Super-review requested from Content review queue
![content review](https://user-images.githubusercontent.com/33448286/39193724-e11417b4-47e4-11e8-9c90-6a1e170d6d74.png)

The Ad-on Review Log 
![logs](https://user-images.githubusercontent.com/33448286/39193857-1f3af166-47e5-11e8-81e7-408c05e0fd72.png)
