### ISSUE TITLE
Implement a `Request-ID` that allows us to track a request through the system

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8033]
Supports https://github.com/mozilla/addons-server/issues/7744

The idea is to have a unique request-id that is recorded internally for now but can be exposed to different layers in the long term. Among them, sentry (in addition to their own error event id), the frontend and performance tests that allow correlating request-related data.

My primary use case for this are new regression tests that will log various information throughout the run and I have to correlate request-related data (sql, cache queries) with external load test data (locust requests, request timings).

**Comment by AlexandraMoga** [comment]
Please add STR to this issue or the label "qa:not needed"
