### ISSUE TITLE
[Reviewer Tools] Legacy Review Incentive to match WE

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#8036]
Legacy Review Incentive could more closely match WE Review Incentives, 
In fact, they may even be justified for more advantageous incentives.

**Comment by wagnerand** [comment]
Legacy add-ons are going away in just a few months, so I am not sure how much effort we should put into this, also given the very low volume of legacy submissions we get these days and the fact that a lot of them are handled by @kewisch and me.

Ultimately a question for @caitmuenster though.

**Comment by caitmuenster** [comment]
Yeah, I don't think we should be incentivizing legacy reviews at this point. :)

**Comment by erosman** [comment]
Maybe the point was misunderstood.

Changing the current 80 to 90 or 100 etc should takes about 5 seconds to implement and makes it more in-tune with WE review.

Currently there are legacy add-on on the queue waiting to be reviewed for 50 days. I thought that might  encourage faster turn over.

Legacy and Thunderbird add-ons will be around for another 5 months, AFAIK.

**Comment by caitmuenster** [comment]
Apologies, @erosman, this fell off my radar. 

I'm fine with updating the legacy points to reach parity with WebExtensions (as it does seem like we could use some more help reviewing Thunderbird extensions in the queue, at least until the TB fork of AMO finalizes -- @kewisch, do you know when that is expected to happen?), but I don't think we'll be able to allocate engineering resources to it. :/ Is this something you would be comfortable fixing yourself?

**Comment by erosman** [comment]
> but I don't think we'll be able to allocate engineering resources to it. :/ Is this something you would be comfortable fixing yourself?

IMHO, it is a really small change. It is not like the multi-tier Post Preview system (although that shouldn't pose a challenge either).

Currently, updates are set to 80 and new reviews to 120 (and 30 for search plug-ins and 60 for dictionaries) AFA I recall.
There is a single line of code that set the figure of 80 (wherever it is) and changing the 80 to some other figure is quite a minor change.

If I were familiar with the code, I could have done the Pull Request in a minute.
The time it would take for someone to show me what to do would be considerably longer than actually doing it :)

In any case, that was just a suggestion.
