### ISSUE TITLE
Change preview for static themes with additional backgrounds for Firefox 61(?) changes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8038]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1443561

Firefox will now display the primary background _below_ the additional backgrounds.  Often the primary background would be empty or transparent so it won't make a difference in those cases but otherwise will.

The change in Firefox will also fix the additional_backgrounds alignment bug (all alignments other than left top, top, right top were broken)

**Comment by jvillalobos** [comment]
This issue depends on the Firefox bug being resolved, which is currently very low priority. /cc @ddurst @mconca

**Comment by mconca** [comment]
I asked Dao to raise the priority of the underlying Firefox bug.

**Comment by mconca** [comment]
I believe the Firefox bug is landed and tested at this point, and it has been uplifted to 60 ESR and 62 beta (the request to uplift to 61 was denied). So I think AMO should be good to go.

**Comment by jvillalobos** [comment]
Yes, by next week all release versions should have the fixed code, so let's get this done.
