### ISSUE TITLE
Add-ons that are no longer public should not be displayed in Expired info request queue 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8059]
Followup for https://github.com/mozilla/addons-server/issues/8008

Prerequisites:
Admin rights in dev hub

STR:
1. Load AMO dev and go to Reviewer Tools to the Expired info request queue.
2. Click an add-on from the list and then go to Edit(admin).
3. From View All click on Invisible from Listing Visibility section.
4. Go back to  Expired info request queue and check if the add-on is still in the list.

Expected result:
The add-on is no longer displayed in the Expired info requests queue.

Actual result:
The add-on is still displayed in the list from Expired info requests queue.

Notes:
This issue is reproducible on AMO dev with FF59(Win10).

![invisible status](https://user-images.githubusercontent.com/33448286/38807337-ebb3f13c-4184-11e8-88ee-e77e1949156e.gif)

**Comment by wagnerand** [comment]
Fixed via #8661.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10). 

![the invisible status](https://user-images.githubusercontent.com/33448286/42172641-4851e552-7e25-11e8-9f51-201651c764aa.gif)
