### ISSUE TITLE
Allow content-reviewers to approve or reject if the review has sources attached.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8062]
This is a follow-up from #8012.

We still want content-reviewers to be able to content-review if the add-on has sources attached.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-stage, with FF59, WIn10x64
Content reviewers are allowed to approve/reject content for an add-on with sources attached.
I've also  checked several additional scenarios involving attached source code and admin flags and the results were as expected.

**Comment by bjherbison** [comment]
When will this get deployed? I thought deployment day was Thursday but I still can't review content for many add-ons.

**Comment by wagnerand** [comment]
This was deployed yesterday. Let's follow up on IRC.
