### ISSUE TITLE
LastPass

### ISSUE THREAD

**Issue by eeazye** [mozilla/addons-server#8064]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I tried downloading LastPass to my laptop this afternoon & for some reason am not able to do so. I clicked

### What happened?

I clicked on the link to download LastPass & this page popped up 
Not Found

We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

    If you typed in the address, please double check the spelling.
    If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

Or you can just jump over to some of the popular pages on our website.

    Are you interested in a list of featured add-ons?
    Do you want to search for add-ons? You may go to the search page or just use the search field above.
    If you prefer to start over, just go to the add-ons front page.

### What did you expect to happen?

I expected to download the LastPass App to my laptop

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

This is the URL I tried downloading their app from -
 https://www.lastpass.com/

**Comment by rctgamer3** [comment]
Just grab it from here: https://addons.mozilla.org/addon/lastpass-password-manager/

**Comment by jvillalobos** [comment]
It's possible there's a dead link on their site. You can use the link provided in the previous comment, or contact LastPass about the website issue.
