### ISSUE TITLE
Clean up using timestamps in activity log with Django 1.11

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8068]
After Django 1.11 lands, (#5271), we should clean up setting the correct timezone in `ActivityLog.create()`, by overriding the `created` field as described in https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.DateField.auto_now_add which enables us to pass `created` in the constructor of the `ActvitiyLog` class and its subclasses.

**Comment by EnTeQuAk** [comment]
What is the "correct" time zone in this regard? We don't have a user timezone unless we introduce this as a setting, otherwise we're using UTC as far as I know.

**Comment by wagnerand** [comment]
What I meant is that we should just set `default=timezone.now` for `created`, so that it override the parent and we can synchronize the timestamps for the same event in the activity logs.

**Comment by eviljeff** [comment]
I don't see what changed in django 1.11 that we can't do now in 1.8

**Comment by eviljeff** [comment]
QA:
Just need to look for regressions with this.  _Potentially_ any part of AMO could be affected (I changed a base class for all our content).  There are two scenarios 
- an activity log being created that _doesn't_ set a specific date (the normal scenario).  Easiest way is to do anything that would normally log something - e.g. edit an Addon's information; submit a new add-on; do a review, and then check the log has now's date and time.  (things in devhub should show in https://addons.mozilla.org/developers/feed/<addon-slug>; review things in review page log)
- an activity log being created that _does_ set a specific date.  The place I remember this being used is in the reviewer tools when rejected multiple old versions of an add-on.  Date/time of the rejection(s) should be now.

**Comment by AlexandraMoga** [comment]
I had a look at the activity logging for dev-hub and rev tools and things seem to be working as intended:

1. Dev Hub - https://addons-dev.allizom.org/en-US/developers/feed
- checked for: add-on submission, updates, edit information, adding authors, uploading source code;
- activity is logged in the format "x _time_ ago"

2. Rev Tools - review log https://reviewers.addons-dev.allizom.org/en-US/reviewers/reviewlog
- checked with postreview approvals, rejections comments etc; legacy add-on approvals, rejecting multiple versions;
- LWT approvals/rejections - https://reviewers.addons-dev.allizom.org/en-US/reviewers/themes/logs
- reviews moderations - https://reviewers.addons-dev.allizom.org/en-US/reviewers/moderationlog
- activity date is logged with the UTC date and time, ex. `Aug. 28, 2018, 1:10 p.m.`

@eviljeff after this verification, things don't look broken. A general site verification will be completed during the release testing, so if there are any possible regressions they will be reported.

**Comment by AlexandraMoga** [comment]
No regressions found during our release testing.
Marking the issue as verified fixed on -dev and stage.
