### ISSUE TITLE
collection slugs can be set to be all numeric when we don't support that in the API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8070]
From mozilla/addons-frontend#4653 - entirely numeric slugs aren't allowed - either for collections or addons - because there's no way to differentiate an ID from a slug in a url. (This was more a policy of consistency until #7529 added the ability to refer to collections by ID as well as slug).

But we don't enforce this in the API for creating/editing a collection so you can end up with an inaccessible collection (based on the slug... and we don't expose the collection ID to the user).

**Comment by eviljeff** [comment]
Fixed by removing the lookup by ID function in the API.  Slugs can be all numeric again.

**Comment by AlexandraMoga** [comment]
Test results:
1. Requested a collection by slug - collection details returned
`https://addons.allizom.org/api/v3/accounts/account/amoga1/collections/spring-is-in-the-air/`
2. Requested _the same collection_ by ID - collection details not found
`https://addons.allizom.org/api/v3/accounts/account/amoga1/collections/5744645/`
3. Created and edited a collection with a numeric slug on the frontend and collection details were displayed: see https://addons-dev.allizom.org/en-US/firefox/collections/AlexandraMoga1/741852/ and https://addons.allizom.org/en-US/firefox/collections/amoga1/456321/

Verified on AMO-dev and stage with FF59, Win10x64
