### ISSUE TITLE
Stop using amo-editors AT mozilla DOT org

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8075]
The amo-editors mailing-list has been deprecated for about two years now. Review emails are using a different system and there has been an auto-responder forwarding users to the right process since we started the deprecation.

I have been monitoring the list since it's deprecation and pretty much all emails arriving are spam.

Currently, the list is still referenced in the following places:

* The sender (FROM) in review emails, but we set `reply_to` to make replies go to AMO directly.
* the sender (FROM) in reviewer notification emails when an add-on they subscribed to gets updated.
* the welcome email for submitting a new add-on to AMO. Interestingly here the sender (FROM) is nobody@ but `reply_to` is set to amo-editors.

I believe for the first and second case, we could change it to nobody@.

For the welcome email, we already include information on how to contact us in case something goes wrong, I am not sure if more information is needed. This could then come from nobody@ as well.

Thoughts? @jvillalobos @caitmuenster

**Comment by jvillalobos** [comment]
Sounds good to me.

**Comment by caitmuenster** [comment]
🚢it

**Comment by wagnerand** [comment]
STR:

1. Submit a new add-on. Make sure the welcome email doesn't have the `reply_to` header.
2. Send a reviewer or developer reply (using review tools or developer hub). Make sure the sender email is *nobody@mozilla.org*.
3. As a reviewer subscribe to an add-on review (on the bottom of a review page). Submit another version for that add-on. Make sure the notification email you get comes from *nobody@mozilla.org*.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59, Win10x64 via the Fake mail log:
1. The welcome email sent to new users at their very first add-on submission doesn't contain a `reply_to` header (see email log [#5378](https://addons-internal.dev.mozaws.net/en-US/admin/mail#msg-5378))
2. @wagnerand I have left reviewer/developer replies and in all cases the notification was coming from <notifications@addons-dev.allizom.org> not nobody@mozilla.org.
3. New version notifications are received from nobody@mozilla.org (see email log [#5376](https://addons-internal.dev.mozaws.net/en-US/admin/mail#msg-5376))

Additional notes: add-on approval and rejection notifications are also received from nobody@mozilla.org

**Comment by wagnerand** [comment]
Thanks for testing.

Point 2 is fine.
