### ISSUE TITLE
Change theme_data JSON for LWT to be `null` for undefined textcolor / accentcolor

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8080]
See #8067 for full background.  In brief, we return `"#"` when `textcolor` or `accentcolor` hasn't been set by the theme designer via the LWT creation wizard, which isn't correct.  We should return `null` instead.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF60, Win10x64

I have checked the theme data both for existing themes and newly submitted themes that did not have a defined `textcolor` and `accentcolor`. In both cases, the value for these two properties was `null`
I've also submitted theme updates with defined `textcolor` and `accentcolor` to make sure the values are updated accordingly. 
Here is an example of a theme without `textcolor` and `accentcolor` set during theme submission:

![image](https://user-images.githubusercontent.com/31961530/40354102-c5bc032c-5dbb-11e8-8ffc-49c5edcf26ca.png)
