### ISSUE TITLE
A name of a searched collection is not suggested in the list (old pages)

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8083]
STR:
1. Load AMO stage and go to Collections 
2. Make a search entering the name of a collection in the search field
3. Observe the suggested results

Expected result:
The name of the collection is displayed as the first suggestion in the list.

Actual result:
The collection is not displayed in the list.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF59 (Win10).
Sometimes the list of suggestions is not displayed at all.

![search suggestions](https://user-images.githubusercontent.com/33448286/39000281-461ba600-43fc-11e8-9171-e3f35628bec1.gif)

![searchcollection](https://user-images.githubusercontent.com/33448286/39000386-98ea8400-43fc-11e8-9c3e-18683fae25fd.png)

**Comment by eviljeff** [comment]
If this is just affecting legacy frontend I'm going to wontfix because we don't have the ability to search collections at all in new frontend.
