### ISSUE TITLE
Please reduce cron interval for signing addons.

### ISSUE THREAD

**Issue by Callek** [mozilla/addons-server#8084]
Can we reduce the interval in the sign langpack cron?

Context: Release Engineerings langpack uploads submit a set of language packs and then wait for them to be signed, frequently the task times out after waiting for around 10 total minutes since the API says they are still not yet signed. If we can reduce the cron timing to less than every 10 minutes that should greatly increase the release throughput, even every 5 or less.

CC: @jvillalobos @muffinresearch

**Comment by muffinresearch** [comment]
@diox would you have any concerns about moving to 5mins?

**Comment by diox** [comment]
It should be fine.

**Comment by AlexandraMoga** [comment]
Could you please add some STR or the label "qa:not needed"?
Thank you

**Comment by diox** [comment]
@AlexandraMoga make sure addons are now auto-approved every 5 minutes instead of 10.
