### ISSUE TITLE
Content Review list should only show add-ons where Approve Content will be shown

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#8094]
As a content reviewer I don't want to waste my time on add-ons which I can't review. When an add-on is flagged "Needs Admin Code Review" the add-on is still show in the Content Review list, but "Approve Content" isn't one of the options.

I tried to [review rested](https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/rested) and after looking the add-on over I went down to the action line and Approve Content wasn't listed. Yesterday there was a point where all the add-ons in [my Content Review list](https://reviewers.addons.mozilla.org/en-US/reviewers/queue/content_review#review-actions) were blocked from being reviewed.

The list of add-ons for Content Review should be exactly those add-ons for which Approve Content is allowed (for the current user).

**Comment by caitmuenster** [comment]
Hey @wagnerand -- I'm also not sure what's causing the block. :) Could you give us a quick summary?

**Comment by wagnerand** [comment]
If the add-on has sources attached, then content-review can be done by regular content-reviewers. This was done in #8062.

**Comment by bjherbison** [comment]
An example of a current add-on in the content review queue which where there is no "Approve Content" action link for me:
https://reviewers.addons.mozilla.org/en-US/reviewers/review-content/cisco-jabber-guest
It has flag Needs Admin Code Review, but as I noted in an earlier comment that flag doesn't always cause Approve Content to be hidden.

**Comment by wagnerand** [comment]
That add-on is pending admin code review and doesn't have sources attached so it must be reviewed by an admin.

**Comment by bjherbison** [comment]
So it either should either have Content Approve available, or not be in the list of items to be content reviewed.

**Comment by wagnerand** [comment]
This is not properly solvable without #8041, so the interim solution here is to allow content-review even if the admin code flag is set.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

Scenarios tested:

- Add-on has Admin Content Review flag -> content reviewers _cannot_ approve content
- Add-on has Admin Content Review flag and Admin Code Review flag-> content reviewers _cannot_ approve content
- Add-on has Admin Code Review flag -> content reviewers _can_ approve content
- Add-on has Admin Code Review flag and source code -> content reviewers _can_ approve content
