### ISSUE TITLE
Duplicate host permissions on AMO

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#8112]
### Describe the problem and steps to reproduce it:

Visit https://addons.mozilla.org/en-US/firefox/addon/okta-verify-auto-send/

### What happened?

Note that the permissions look like below:

<img width="397" alt="screen shot 2018-04-23 at 2 14 53 pm" src="https://user-images.githubusercontent.com/74699/39153710-c3f06aa0-4700-11e8-8b14-e03c2359e0ac.png">

### What did you expect to happen?

More like when you install it, where only one set of permissions is shown:

<img width="364" alt="screen shot 2018-04-23 at 2 15 31 pm" src="https://user-images.githubusercontent.com/74699/39153726-d02b4858-4700-11e8-9e1e-c775db86fdb8.png">

### Anything else we should know?

Y'all are awesome. 👋 🍺

**Comment by diox** [comment]
That add-on has the following permissions set:

```
"permissions": [
  "https://*.okta.com/",
  "https://*.okta.com/login/login.htm*",
  "https://*.okta.com/signin/verify/okta/push",
  "https://*.okta.com/signin/verify/okta/sms"
]
```

Guess Firefox simplifies that to a single domain, we should as well. Not sure it should be done on the server though, we might want to keep the API closer to the truth and have the frontend just display a simplified output to the user.

**Comment by muffinresearch** [comment]
Closing as this is now moved to https://github.com/mozilla/addons-frontend/issues/4871
