### ISSUE TITLE
Broken link to old versions of ColorfulTabs

### ISSUE THREAD

**Issue by powert9n** [mozilla/addons-server#8114]
### Describe the problem and steps to reproduce it:
On the ColorfulTabs add-ons page (https://addons.mozilla.org/en-US/firefox/addon/colorfultabs/?src=search), in the "About this extension" section, there is a link that is supposed to take me to previous versions of the extension.  The information on the page says "Previous versions are available at https://addons.mozilla.org/en-US/firefox/1368/history/"

![image](https://user-images.githubusercontent.com/35274050/39167639-c28efab4-4755-11e8-846f-3c3e6ec2c560.png)

![image](https://user-images.githubusercontent.com/35274050/39167658-e7c81b8a-4755-11e8-95dc-c263a46a64ef.png)

### What happened?
Clicking on that link brings up a "Not Found" page.  The "Not Found" page advises opening an issue if I followed a link to get to that Not Found page, so here I am.

### What did you expect to happen?
I expected to get to a landing page where I could access older versions of ColorfulTabs.  I'm on the ESR channel and the latest version of ColorfulTabs does not work with 52.7.3.  I'm trying to locate an older version of ColorfulTabs (e.g. 31.2.3) that works with Firefox ESR 52.7.3.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
That link was included by the add-on author in the description, so we can't really change it for him. The link should actually point to https://addons.mozilla.org/addon/1368/versions/. Try contacting the author to get that fixed.
