### ISSUE TITLE
Support SameSite cookie attribute on sessionid

### ISSUE THREAD

**Issue by psiinon** [mozilla/addons-server#8117]
### Describe the problem and steps to reproduce it:

Firefox 60 introduces support for the SameSite cookie attribute: https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/
This provides significant protection against CSRF vulnerabilities and so it should be applied to the sessionid cookie.
It looks like its been added to Django https://code.djangoproject.com/ticket/27863 but the fix doesnt appear the be in the latest release.
I'm guessing we'll need to wait until theres a new Django release and then migrate to it before we can add SameSite support?

**Comment by diox** [comment]
You beat me by 20 minutes :)

I'd love to get this, we need to evaluate how much work (and how much of a hack) it is to get it now cause it's going to take us a while to get to Django 2.1 even if it were to be released right now.

**Comment by diox** [comment]
Also, we want this on the API cookie as well, which is different than the session one (it's essentially a separate session token)

**Comment by psiinon** [comment]
:+1:

**Comment by psiinon** [comment]
Pontoon are also on 1.11 but they're looking at implementing this via middleware: https://github.com/mozilla/pontoon/pull/964
@diox is this something we could do in AMO as well?

**Comment by diox** [comment]
Not a huge fan of using a property called `_reserved` :) But yes, we could probably do something like that.

**Comment by jezdez** [comment]
@diox In the spirit of keeping the tech debt low, could we please release an app to do this that we can all use instead of a wild growth of middlewares allover the place?

**Comment by diox** [comment]
Sure. Note that currently nobody is working on this for addons-server, and it's unlikely to change in Q2, however trivial this might be.

**Comment by jezdez** [comment]
@diox Sure, what I'm afraid is that everyone won't be able to work on this in a manner that prevents creating tech debt.

@psiinon Which makes me wonder if you could drive the effort to write an app as part of https://github.com/mozilla-services/foxsec/issues/886?

**Comment by jotes** [comment]
@diox I'm not a fan of `_reserved` myself, however as it's stated -> It's only to keep legacy apps alive untill they'll migrate to Django 2.0

**Comment by psiinon** [comment]
@diox if I were to add @jotes's https://github.com/jotes/django-cookies-samesite package to addons-server what would you require from a PR?

@jezdez I'm trying to coordinate adding samesite support to all of our services :)

**Comment by diox** [comment]
@psiinon we'd need a couple integration tests somewhere in our repos making sure it's behaving normally. 

Also I think it'd be best for that app to live under the mozilla org with more people having access to it in case we need to make changes to it.

**Comment by jotes** [comment]
@diox definitely! In case of Pontoon `SameSite=strict` broke integration with `Firefox Accounts` but `SameSite=lax` is fine.

**Comment by diox** [comment]
Since we're now on Django 2.1+ we've automatically got `SameSite=Lax` added to our session cookies
