### ISSUE TITLE
Implement recommendations API with A/B

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8118]
We need an API that returns add-on recommendations from a single guid. We want to do A/B testing on this so it also needs some way for the frontend to ask for a fallback list of add-ons instead, managed by addons-server, which is the "B" side of things.

Rough implementation plan:
- inherit from `AddonSearchView`
- implement different filter_backends: keep `ReviewedContentFilter` but add a custom filter that calls TAAR if necessary (or just use the fallback guids if we're on the "B" side of the A/B test - or if TAAR took too long to answer) and then just search for the guids returned
- implement a custom serializer, if only to add a property indicating whether we were using the fallback or not.

**Comment by AlexandraMoga** [comment]
I've tested this by using the new add-on recommendation endpoint (`/api/v3/addons/recommendations/`) to send requests to the -dev server. I've applied the parameters mentioned in the [API docs](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#recommendations) and checked the response values.

I'm not sure if this has to do with the amount of data available on -dev, but most of the requests returned no values for `results []`

@eviljeff  could you please specify if there is something more specific to test at this point?
Thanks

**Comment by eviljeff** [comment]
yeah, I expected a lot of blank results too, similar to the discopane TAAR feature - TAAR is returning guids but if they aren't available on amo-dev then their details aren't returned.
What's happening underneath is the guid passed to our API is being passed along to https://taar.dev.mozaws.net/taarlite/api/v1/addon_recommendations/<guid>/

to double check it's just missing addons you could try to see if the guids returned are genuinely not on AMO by doing:
https://addons-dev.allizom.org/api/v3/addons/addon/search/?guid=<guid1>,<guid2>,<guid3>,<guid4> and seeing if that is blank also.
