### ISSUE TITLE
Add setting to disable cache-machine on dev

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8125]
As part of the work to remove cache-machine (#7743) we need to add a setting to disable it on dev and dev only for now.

**Comment by diox** [comment]
Fixed in c3e6d3cc1fa46f0298a4c008a441f50fc3701df9 (#8123)

**Comment by diox** [comment]
QA: no specific things to check, so just make sure there is nothing new broken while browsing the site on dev.

**Comment by ioanarusiczki** [comment]
I checked AMO dev with FF59(Win10 and Android 8.0).  I'm marking it verified fixed.
Went through:
- search
- amo homepage and the features from the drop down menu below username, detail pages for an add-on/lightweight theme
- dev hub
- rev tools
