### ISSUE TITLE
Signing API seems to sometimes consider a version is not attached to a file upload for some time

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8136]
@Callek is having an issue where after using the signing API to create a new version, somehow for a little while the API returns that there are no files attached to the upload, preventing him from downloading the signed file.

Logs: https://taskcluster-artifacts.net/eX0G8c2OT2O22G1kgllNGA/0/public/logs/live_backing.log

**Comment by Callek** [comment]
@diox so looks like this didn't solve it on my end...  a recent log for langpack-ar: https://taskcluster-artifacts.net/A3CEW_YQQ2u5LnMdT4Gy4Q/0/public/logs/live_backing.log

**Comment by diox** [comment]
@Callek can you add more recent logs to this issue, and look it's always happening to the same langpack(s), and/or how many langpacks are affected when a release is made ?
