### ISSUE TITLE
Freeze the v3 API; create a v4 API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8139]
Firefox 60 uses the v3 api so we can't make any breaking changes.  So we're going to freeze the v3 api and create a v4 endpoint.  v4 will immediately be the same as v3, but will in the future have breaking differences.  
Round table discussion points:
* we'll use feature flags to control the differences.  These could be flags in the serializers or in the views.
* documentation will update to reference v4; we'll link to last commit on github that mentioned v3 as the archive.

**Comment by EnTeQuAk** [comment]
We'll need to configure http://www.django-rest-framework.org/api-guide/versioning/#urlpathversioning or http://www.django-rest-framework.org/api-guide/versioning/#namespaceversioning - both do the same thing, I think I like `NamespaceVersioning` better

My proposal back what I meant with feature-flags is something like https://gist.github.com/EnTeQuAk/6ef738f5f467d06f686a5ed7cdac5fcc - which I used at various other projects and worked nicely. Feel free to steal whatever we need :)

**Comment by eviljeff** [comment]
now we're going to have to come up with feature names like "break_this_bit_of_the_api_to_fix_issue_1234" 😛

**Comment by EnTeQuAk** [comment]
> now we're going to have to come up with feature names like "break_this_bit_of_the_api_to_fix_issue_1234" stuck_out_tongue

:rofl: :innocent:

**Comment by eviljeff** [comment]
Oh, and check the v4 API is there.  Basically any API url that currently has `/v3/`  should now also be available as `/v4/` with identical functionality (in this first commit - later the functionality will diverge)

e.g.
https://addons-dev.allizom.org/api/v3/addons/search/
https://addons-dev.allizom.org/api/v4/addons/search/

**Comment by vcarciu** [comment]
@eviljeff  : the /v4/ is returning a 403

**Comment by eviljeff** [comment]
There is an ops change needed it seems (mozilla-services/cloudops-deployment#1978)

**Comment by philipcristiano** [comment]
https://addons.allizom.org/en-US/firefox/api/v4/addons/search/ is up.

**Comment by vcarciu** [comment]
Closing based on comment from above.

**Comment by vcarciu** [comment]
Verified as fixed with various /v3/ vs /v4/ API urls.
