### ISSUE TITLE
Drop rating title

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8144]
New frontend doesn't allow you to set a rating title, so we're going to drop it from the model and database (and thus in legacy frontend too)

**Comment by muffinresearch** [comment]
Presumably this is blocked on switching fully to the new frontend?

**Comment by eviljeff** [comment]
I was going to drop it entirely, from legacy frontend too.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64

The rating title has been removed on the legacy site from Write a Review component and from the Reviews listing page:

[1] Add-on review
![image](https://user-images.githubusercontent.com/31961530/41235270-2041ceb8-6d97-11e8-974a-b76baaec8575.png)
[2] Theme review
![image](https://user-images.githubusercontent.com/31961530/41235292-2b21c7de-6d97-11e8-98cf-395fbd3c2673.png)
[3] Reviews listing
![image](https://user-images.githubusercontent.com/31961530/41235310-3541b864-6d97-11e8-82c0-6185b2d75124.png)
