### ISSUE TITLE
Remove plugin finder service code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8147]
Any support for PFS, the Plugin Finder Service, has been removed from Firefox a while ago. We still have code dealing with that however, `services/pfs.py`, and possibly some nginx rules going with that. We should remove all that.

Relevant links:
- https://www.fxsitecompat.com/en-CA/docs/2014/plugin-finder-service-has-been-shut-down/
- https://wiki.mozilla.org/PFS (points to https://pfs.mozilla.org which is not resolving)
- https://wiki.mozilla.org/PFS2 (points to https://www.mozilla.org/en-US/plugincheck/ which is just a generic page telling you Firefox now supports features that used to require additional plugins)

**Comment by diox** [comment]
Can't find any `z.pfs` occurrences in the logs either FWIW.

**Comment by ioanarusiczki** [comment]
Could you please add some STR or add qa not needed label?
Thank you!
