### ISSUE TITLE
Allow both static themes and lightweight themes to be requested with type=persona?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8150]
#7986 added the ability to request a comma-separated list of types in the API and for frontend to use it there are two options:

A) use the feature in #7986 directly and change the API requests in frontend from `type=persona` to `type=persona,statictheme`.
B) have a request of `type=persona` from the API be interpreted as `type=persona,statictheme`.

**Comment by diox** [comment]
I don't think returning static themes when type=persona is requested is a good idea, since their responses are completely different.

**Comment by eviljeff** [comment]
yeah I think a change to frontend to re-define the theme constant for searches from `persona` to `persona,statictheme` shouldn't be that difficult.  (he says, without knowing how difficult it may be)

**Comment by eviljeff** [comment]
Addons-frontend seems to have gone with A) from looking at https://github.com/mozilla/addons-frontend/pull/5067 so closing this.
