### ISSUE TITLE
May 2018 Disco Pane content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#8153]
For the **17 May** push, here's the full page content line-up for Disco Pane...

**Distortion** by [DarkHunt3r](https://addons.mozilla.org/firefox/addon/distortion/)

**Ad blocking & privacy protection** with [Ghostery by Ghostery](https://addons.mozilla.org/firefox/addon/ghostery/)
A simple set-up lets you take control of the ads you see and how you’re tracked on the internet. 

**Re-imagine tabs** with [Tree Style Tab by Piro](https://addons.mozilla.org/firefox/addon/tree-style-tab/)
Do you have a ton of open tabs? Organize them in a tidy sidebar. 

**Sunset Over Water** by [MaDonna](https://addons.mozilla.org/firefox/addon/sunset-over-water/)

**Stop Facebook tracking** with [Facebook Container by Mozilla](https://addons.mozilla.org/firefox/addon/facebook-container/)
Isolate your Facebook identity into a separate "container" that makes it harder for Facebook to track your movements around the web. 

**Search Images** with Image [Search Options by Xamayon](https://addons.mozilla.org/firefox/addon/image-search-options/)
Perform reverse image searches from an array of engines. 

**Crazy Cats Action** by [keram](https://addons.mozilla.org/firefox/addon/crazy-cats-action/)

@muffinresearch @EnTeQuAk

**Comment by ioanarusiczki** [comment]
Verified on AMO-dev with FF60(Win10) and the content is updated. (-dev is missing the Stop Facebook tracking and Crazy Cats Action)
Full validation will be made in prod.
