### ISSUE TITLE
The recommendations API is not returning curated results

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#8154]
STR:

Look at the response from https://addons-dev.allizom.org/api/v3/addons/recommendations/?guid=%7B9D6218B8-03C7-4b91-AA43-680B305DD35C%7D&recommended=false&lang=en-US&wrap_outgoing_links=true

Expected:

The results array should contain the 4 curated add-ons.

Actual:

The results array is empty.

Note that the same thing happens if you change `recommended` from `false` to `true`. The outcome is listed as `recommended_fallback`, but the results array is still empty.

Note also that I manually added the 4 add-ons listed at https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/utils.py#L143:L147 to dev, so they should be findable. One example is https://addons-dev.allizom.org/en-US/firefox/addon/new-tab-override-2/.

I am currently working on the component that displays these results, and it's difficult to do without any results, so I'd greatly appreciate it if this could be addressed soon.

**Comment by eviljeff** [comment]
3 of them are there now (and `uBlock0@raymondhill.net` doesn't seem to exist on -dev) so it _does_ appear to be caching, or more likely a delay in elasticsearch indexing.  The question is how long it took after you added them...

**Comment by diox** [comment]
Were they just not public at the time? It takes a few minutes for auto-approval to make new submissions public.

**Comment by bobsilverberg** [comment]
I'm pretty sure it was at least 30 minutes or more after I added them, but no worries. They are appearing now. I wasn't able to add the one for uBlock. I'll ping @eviljeff about that in IRC. This can now be closed.
