### ISSUE TITLE
Two or more add-ons with the same name can be submitted 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8156]
Prerequisites:
User is logged in

STR:
1. Go to dev hub and submit an add-on.
2. Submit a new add-on using the same name.
3. After they're auto approved go to AMO homepage and make a search.
4. Observe results.

Actual results:
The search returns two add-ons with the same name.

Expected results:
User should be warned during submission that the name already exists and he should change it to avoid a duplicate name.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF59(Win10).
While submitting an add-on a warning message is displayed to correct the slug "This slug is already in use. Please choose another". It should also warn the developer about the Name.

![same name](https://user-images.githubusercontent.com/33448286/39511010-90356710-4df4-11e8-9488-6b383fc5de68.png)
![slug](https://user-images.githubusercontent.com/33448286/39511016-95efd5dc-4df4-11e8-9a78-b7ad1faeb6ed.png)

**Comment by eviljeff** [comment]
Not sure that's a bug, rather a long term feature.  @jvillalobos to confirm.

**Comment by jvillalobos** [comment]
We allow duplicate names for unlisted add-ons, but not listed ones. Maybe we're not making name checks when it's the same user because they are allowed to re-submit previously deleted add-ons? That would still make this a bug, though.

Not sure what feature @eviljeff is referring to.

**Comment by diox** [comment]
We killed name uniqueness checks for listed uploads a year ago in https://github.com/mozilla/addons-server/issues/4095 :)

**Comment by eviljeff** [comment]
I forget I did that in 2016 🙄, heh.  Closing as the kill order was given and carried out.
