### ISSUE TITLE
Add fxa account options to createsuperuser script

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#8157]
It would be great if we could create a superuser and have an fxa account tied to that.

**Comment by jrbenny35** [comment]
Looking [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/models.py#L102) it seems there is a ```username``` and ```fxa_id``` option, as per @EnTeQuAk comments on IRC.

**Comment by ioanarusiczki** [comment]
Please add QA not needed label if QA is not needed.
Thanks!
