### ISSUE TITLE
Add-on deletion emails are no longer sent

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8158]
We used to get an email when an add-on gets deleted. Those emails stopped on Nov 6, 2017.

The code is still there (https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/models.py#L514) so I am not sure what broke.

**Comment by wagnerand** [comment]
@philipcristiano are there any mail server logs we can check? I just tested this locally and the email is logged in the *fake mail* system which means it should have been sent successfully.

**Comment by philipcristiano** [comment]
I'm trying to grab access to the account to see if there are any logs in the email sending API service. The log lines internally appear to be debug, so nothing show up in Kibana after a quick search.

**Comment by philipcristiano** [comment]
commit-fixed link for the code https://github.com/mozilla/addons-server/blob/021863cdea3ac87145adc5df0b44b91fd71b8aba/src/olympia/addons/models.py#L515

**Comment by wagnerand** [comment]
I found statements in the activity log. (https://github.com/mozilla/addons-server/blob/021863cdea3ac87145adc5df0b44b91fd71b8aba/src/olympia/addons/models.py#L509)

```
mysql> select created from log_activity where action = 133 order by created desc;
+---------------------+
| created             |
+---------------------+
| 2018-05-23 09:35:29 |
| 2018-05-23 09:27:10 |
| 2018-05-23 07:59:30 |
| 2018-05-23 07:26:57 |
...
```

I checked locally that `send_mail` is called properly and that the outgoing email appears in the fake-email log.
We also use that same `send_mail` function for abuse reports and others and those emails arrive just fine.

**Comment by wagnerand** [comment]
When I filed this issue, I was looking into that as well. What strikes me is that it stopped working on Nov 6, which is nowhere near a push date. I looked at the tags, and there didn't seem to be any extra-pushes for that date.  @philipcristiano are there any logs that would confirm we didn't push that day?

I also don't see how permissions would be involved in that. We're calling `send_mail` directly in the function that deletes the add-on.

**Comment by philipcristiano** [comment]
There does not appear to have been a deploy at that time. I had to check Datadog as Jenkins doesn't have information back that far. 

I was able to gain access to SocketLabs which does allow searching by email. It turns out the email address used was on the suppression list. 

```
550-5.1.1 The email account that you tried to reach does not exist. Please try  550-5.1.1 double-checking the recipient's email address for typos or  550-5.1.1 unnecessary spaces. Learn more at  550 5.1.1  https://support.google.com/mail/?p=NoSuchUser u89si2693197qtd.361 - gsmtp  
```

It looks like Google nack'd the address on Nov 6th and it's stuck around since then. I've removed the email from the suppression list.

**Comment by philipcristiano** [comment]
@wagnerand Not a very easy way that I'm aware of. We'd need to write something to compare a list of admin emails we use in the config and check them against socketlabs. 

Might be possible to export metrics from socketlabs and send counts of moco emails that don't get delivered. 

These wouldn't address errors unrelated to problems at the API provider. And end-to-end solution would catch more cases.
