### ISSUE TITLE
How do add-ons end up with no author?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8160]
Following on from https://github.com/mozilla/addons-frontend/issues/4907 it would be good to understand the paths that allow an add-on to get to a state without an author. 

Presumably this isn't a desirable stat? If there are bugs allowing it we should look to fix them so it's not possible to get to this state.

<img width="1169" alt="the_pirate_bay_search____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/39514251-9a251bf4-4dee-11e8-9b12-e833daa51acd.png">

**Comment by diox** [comment]
We have https://github.com/mozilla/addons/issues/422 filed already, we might want to dupe one way or the other.

**Comment by muffinresearch** [comment]
@diox yep I'll dupe this to the older bug.
