### ISSUE TITLE
replace amo.utils.no_translation with django's translation.override

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8164]
less custom cruft plz

**Comment by eviljeff** [comment]
QA: the changes concern emails, primarily.  So perform some actions in a non-English locale that would send an email, and check that there is no-non-English in the response.
E.g. send an abuse report ("User" and the different add-on type names should be in English in the email); delete an Add-on (the email should be in English)

**Comment by AlexandraMoga** [comment]
I have performed several actions on stage that generate an email (user abuse report, add-on abuse report, add-on review, add-on deletion, reviewer replies etc) and I've noticed the following:
1. the predefined email is sent in English (default notification text set for a specific action)
2. add-on name (when add-on is localized) will be rendered in the subject and body in the locale set by the user on AMO. Below is an example of an abuse report sent from Arabic - `/ar/`. 

https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-33109
![image](https://user-images.githubusercontent.com/31961530/39806940-ca12094a-5383-11e8-8668-33266d1c5f14.png)
 **Note** - the email subject will be rendered like this by a proper email client: **"[Extension] Abuse Report for آدبلوك ب, لس"** 

Additional examples:
[- add-on review -](https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-33112)
[- add-on deletion -](https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-33127) 

@eviljeff If I understood your guideline, point 2. should not be expected?

**Comment by eviljeff** [comment]
@AlexandraMoga it was already broken - the code that forces it back to `en-US` only affected a few small parts, like the add-on type and the unsubscribe footer - so it's not any _more_ broken than before 😆 

Arguably we shouldn't be localizing Add-on name in the emails either - can you file a follow-up issue?

**Comment by AlexandraMoga** [comment]
Logged #8230 as follow up

I'm marking this issue as verified fixed
