### ISSUE TITLE
Support unlisted => listed promotion, without resigning

### ISSUE THREAD

**Issue by Callek** [mozilla/addons-server#8179]
This is just one of the possible ways to help release engineering's use cases with automatically submitting addons to AMO for signing.

Background
----------------

Release engineering does:

1. Builds release version of firefox about 1 to 2 weeks ahead of the release date
1. Submits Language Packs to AMO on the initial build date
1. Takes those language packs and bundles them with some build types (e.g. Ubuntu Snap) and makes sure the packs are available in the Releases Directory (https://archive.mozilla.org/pub/firefox/releases/59.0.3/)

Because of the limitation of "only one version uploaded at once" (rather than one version per channel) Release Engineering currently has to submit these language packs as "listed" at the initial build time (1 to 2 weeks ahead). And this can cause user confusion.

Potential Solution
-----------------------

If we could have a way to say "Please promote this addon to listed" that takes the (already signed) addon and resubmits it as listed, letting it go through the usual processes involved in listing an addon, just without re-signing, and then outputting a signed copy at the other end, that could solve Release Engineerings needs here, and we'd then just add an API call to list our addon as public when we do finally ship the version of Firefox we are targetting.

**Comment by wagnerand** [comment]
The review process is very different for unlisted vs listed. Also, there are different and conflicting validation rules.

**Comment by Callek** [comment]
@wagnerand In my mind, AMO could treat this as "your thing already passed unlisted, and is fine that way, but since you want to list it now, lets start over and validate it all"

So we'd send it through all the validation rules for listed, we'd do the review process from scratch, etc. and only when everything passes we'd offer it on AMO itself, but the only magic difference being no need to re-sign it.

I can easily imagine how the implementation details of my mindset could be pretty hard.

**Comment by wagnerand** [comment]
In lots of cases files won't pass because they use an `update_url` which is forbidden in listed versions.

**Comment by jvillalobos** [comment]
We decided not to support this back when we started signing add-ons.

Given the very specific requirements language tools have and will have in the future, we should seriously consider whether AMO is the right place for them.
