### ISSUE TITLE
Do not mark an addon as incompatible if there is a previous version that is compatible.

### ISSUE THREAD

**Issue by Callek** [mozilla/addons-server#8180]
Currently if you visit addons.mozilla.org and look at language packs, with Firefox 59, you'll see `This add-on is not compatible with your version of Firefox.`

Though in the "More Versions" link at the bottom left you will see a compatible version.

This is because language packs all set min_version and max_version to be very restrictive (only one major version of Firefox) rather than allowing a wider range. And because now Release Engineering submits the addon as listed ahead of the release day (previously AMO staff would manually take the language packs and submit them into AMO sometime shortly after the release day).

This has the end result of confusing users who may have an up to date Firefox (or even after the next version is out, if we stop updates due to crashes, or are throttling the rollout % of the new version) they won't be able to download the language pack they want, and are unlikely to look in "More Versions"

I propose that we offer them the most-recent addon version that is supported by the browser version they are loading AMO with, e.g. if they come in with Firefox 58 they get a direct link to download a language pack supported by Firefox 58, and similarly for 59, 60, etc.

This has the added bonus that we can realistically list language packs for each Firefox Beta version, and maybe even Nightly on AMO without worrying that we might be confusing users on the Release Version.

**Comment by Callek** [comment]
Note: that in implementing a fix this, we might want to be careful here though, since for example: https://addons.mozilla.org/en-US/firefox/addon/shqip-language-pack/versions/ has a version that is compatible with 61beta, and 62a1 all the way down... That version is 38.0.5

**Comment by diox** [comment]
This was deemed too complex to implement for the general add-on population in the past - AMO relies heavily on the concept of `current_version`, which is the latest publicly available version.

Specifically for langpacks though, we can do something. The [language tools API](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#language-tools), if the `appversion` parameter is passed, does support this.

**Comment by Callek** [comment]
@diox - Would this help in the situation of a user visiting: https://addons.mozilla.org/en-US/firefox/addon/ca-language-pack/ as opposed to *just* visiting https://addons.mozilla.org/en-US/firefox/language-tools/

I ask because the latter page seems to be what you're referring to but the former page is what the latter links to.

**Comment by diox** [comment]
What I'm saying is that we implemented something like this in the API for the language tools page, so we could implement something like this for the detail page as well *but only for langpacks*. We'd still have to consider UX here though, cause it'd be an exception to the way we offer versions for other add-ons.

**Comment by kumar303** [comment]
I spoke to @Callek and others in the `#ci` channel; this langpack incompatibility is going to keep happening for the foreseeable future.

The release engineering team needs to push langpacks early due to signing requirements (since Firefox 60). They can't push early langpacks as unlisted because those cannot be changed to listed.

Since this is essentially preventing users from installing langpacks, we need to think of some other workarounds. I will increase the priority of https://github.com/mozilla/addons-frontend/issues/4935

**Comment by diox** [comment]
@kumar303 : on the frontend side, I think the only thing you'll need to do is pass `appversion` to the detail page (it should already be done for search). In this issue I'll make the API support it and change `current_version` when it's passed, for langpacks only.

**Comment by wagnerand** [comment]
> I spoke to @Callek and others in the #ci channel; this langpack incompatibility is going to keep happening for the foreseeable future.

This was raised early in the process when we planned to start signing langpacks and it was deemed ok for the time being.

**Comment by diox** [comment]
It was, but there are enough people complaining about it and filing issues that we should try finding a solution. At least both @kumar303 and I feel that way :p

**Comment by diox** [comment]
QA: API-side is ready, it's technically testable manually, but it'd be easier once the frontend side is implemented too.

If you want to test it manually: when you pass `appversion` and `app` parameters to the add-on detail API of a language pack (and only a language pack), the version returned will be the latest public listed compatible with the parameters you passed, if there is one available (instead of just the latest public listed version).

**Comment by AlexandraMoga** [comment]
I have tested this new addition to the api and the new results for language packs  seem to be correct.

Specifically:

https://addons-dev.allizom/api/v3/addons/addon/finn-language-pack/ - returns the latest listed version 
```
"release_notes": null,
"reviewed": null,
"url": "https://addons-dev.allizom.org/en-US/firefox/addon/finn-language-pack/versions/63.0buildid20180830143136",
"version": "63.0buildid20180830143136"
```


https://addons-dev.allizom/api/v3/addons/addon/finn-language-pack/?app=firefox&appversion=62.0 - returns the listed version compatible with the `appversion` parameter
```
"release_notes": null,
"reviewed": "2018-09-05T09:45:11Z",
"url": "https://addons-dev.allizom.org/en-US/firefox/addon/finn-language-pack/versions/62.0buildid20180830143136",
"version": "62.0buildid20180830143136"
```
