### ISSUE TITLE
"You are missing description" but description is filled

### ISSUE THREAD

**Issue by spixy** [mozilla/addons-server#8187]
Edit: this issue is fixed, see [my comment](https://github.com/mozilla/addons-server/issues/8187#issuecomment-386880051)

### Quick description
When I want to change default language, I am getting error "You are missing description" but description is filled (see image).

### What happened?
I made an addon in english as default language.
I added more languages.
I chose **Portugal** as default language (because I misunderstood that **Default Locale** is global setting for all languages).
I wanted to reset default language to **English** but now I cannot:

![mozilla](https://user-images.githubusercontent.com/4542110/39673728-abcf8460-5141-11e8-8f42-a941492121c0.png)

**English (British)** and any other languages are not working as well.

### What did you expect to happen?
To hide that description error and change **default language** to **English (US)**.

### Addon link
https://addons.mozilla.org/sk/firefox/addon/no-more-mobile

**Comment by spixy** [comment]
Problem solved. It must be done in two steps:
1. write description and press **Save changes**
2. change default language and press **Save changes**


However, this should be fixed.

**Comment by eviljeff** [comment]
Tbh, it's really difficult to fix without reworking how devhub handles localisation, and if we did that there would be a lot of other changes.
