### ISSUE TITLE
Missing 'Coffee Mug' Firefox Extension Download Page

### ISSUE THREAD

**Issue by HaKDMoDz** [mozilla/addons-server#8188]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

**Operating System:  Kali Linux 2.4 
Browser:   Firefox Quantum 64bit version 60**

### What happened?
**https://shaneliesegang.com/projects/coffee.php** 
directed my browser to
**'https://addons.mozilla.org/en-US/firefox/2677/'**

### What did you expect to happen?

Expecting to be taken to '**Coffee Mug version 1.26'** Firefox extension download page but instead page is missing so i thought I'd fill out a issue card
Just wanted '_Coffee Mug_' extension doesn't really matter just thought surely I'm not the only one seen this and maybe someone could fix
 
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Have a nice day**

**Comment by rctgamer3** [comment]
This is not an AMO bug. The developer simply forgot to include **/addon/** in the URL.
https://addons.mozilla.org/en-US/firefox/addon/2677/
