### ISSUE TITLE
Add-on submission is stuck in validation state on AMO-dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8192]
STR:

1. Log into Developr Hub
2. Submit a new extension 
3. Wait for your validation results

Actual result:
Extension is stuck in validation mode and no results are triggered

Expected result:
Validation is successfully completed for the submitted extension

Notes:
- it is also happening at theme submission, when using the theme generator wizard (submission is stuck in upload mode)
- it is similar to the issue reported in #7594 
- reproduced on AMO-dev, FF59 (Win10x64)

![image](https://user-images.githubusercontent.com/31961530/36372534-ff959ea0-156d-11e8-8bdc-fa5eb4c3df0a.png)
=======================================================
![image](https://user-images.githubusercontent.com/31961530/36372544-08848d1e-156e-11e8-8f77-ec80c3302733.png)

**Comment by wagnerand** [comment]
Actually, this has just been fixed. Could you retry with an account that **does** have an API key, in oder to verify?

**Comment by AlexandraMoga** [comment]
I have tried again with a user that has an API key and the issue seems to be intermittent. Some add-ons are validated, other are stuck. I could not observe a clear pattern that separates one from the other.

**Comment by wagnerand** [comment]
Can you provide an example of a stuck add-on?

**Comment by vcarciu** [comment]
@wagnerand : 
I will provide an example of a stuck add-on.
Also, please note that exactly the same add-on passed validation without issues using a new account and a new profile, before adding the api keys in manifest.json.

[vraddon-3.57-an+fx-windows.xpi.zip](https://github.com/mozilla/addons-server/files/1980270/vraddon-3.57-an.fx-windows.xpi.zip)

**Comment by wagnerand** [comment]
Would you mind trying again on -dev, please?

**Comment by AlexandraMoga** [comment]
@wagnerand I've verified again on -dev and stage and the validation seems to be working now.

**Comment by wagnerand** [comment]
Yay, thank you. Closing...
