### ISSUE TITLE
Json export should only include lang code as key

### ISSUE THREAD

**Issue by nukeador** [mozilla/addons-server#8194]
### Describe the problem and steps to reproduce it:
I'm trying to consume the data exported from addons language stats, reading from the json file linked.

Example:
https://addons.mozilla.org/firefox/addon/easyscreenshot/statistics/usage/languages/?last=30
https://addons.mozilla.org/firefox/addon/easyscreenshot/statistics/locales-day-20180407-20180507.json

### What happened?
The json file has the names of the languages with unicode charters as keys. Examples

Español (de España) (es-es) | Português (do Brasil) (pt-br) | Русский (ru)

### What did you expect to happen?

I would like to suggest this json just export the lang code as the key. Why?

- Parsing unicode characters is problematic and requires a lot more coding effort to handle any issues.
- By using the iso lang codes simplifies anyone searching for a specific language even if they don't know the language name in the local language. I want to see all stats for "ru" but I don't really know how to write it in Russian ;-)  

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
If we can make this change easily without breaking stuff, I'd like it to be done soon. This supports a localization project currently in the works.

**Comment by diox** [comment]
I'm all for it, but it would break backwards-compatibility for anyone using those JSON (including ourselves in our statistics pages, those would need to be fixed)

**Comment by jvillalobos** [comment]
I doubt there are many external consumers of those JSON files. I can't find them on GA, but maybe @philipcristiano or @bqbn can get server logs for those?

**Comment by jvillalobos** [comment]
We can be more specific and go with `addon\/[^/]+\/statistics\/locales-[^/]+json$`, since that's the only one we might change.

**Comment by jvillalobos** [comment]
Oh, and we would need to make sure the referrer is not AMO, since we want to measure external consumers of that data, not just how often it's loaded from the stats page.

**Comment by nukeador** [comment]
A lot of them last week probably was my script, I would check a couple of weeks ago just in case.

**Comment by jvillalobos** [comment]
Thanks, Wei. It appears to be a small number either way, so I'd be okay with changing the JSON file. I'll reiterate that we should do this soon *if* it can be done quickly. AMO has a very full plate for the quarter, so we'll have to work around this if this delays other work significantly.

**Comment by jvillalobos** [comment]
Don't think we need this anymore.
