### ISSUE TITLE
Json export: Total number of users count mismatch 

### ISSUE THREAD

**Issue by nukeador** [mozilla/addons-server#8196]
### Describe the problem and steps to reproduce it:
I'm trying to consume the data exported from addons language stats, reading from the json file linked.

Example:
https://addons.mozilla.org/firefox/addon/easyscreenshot/statistics/usage/languages/?last=30
https://addons.mozilla.org/firefox/addon/easyscreenshot/statistics/locales-day-20180407-20180507.json

### What happened?
The json file has a value named "count" with the total number of users and numbers of users per language.

### What did you expect to happen?

This total count number mismatches. If you sum all languages users you always get more users than this total count value.

**Comment by jvillalobos** [comment]
After giving it some thought, I think this may be because of the changes we made to the active user count on https://github.com/mozilla/addons-server/issues/3632. The total user counts are just counting enabled installs, while other stats pages probably include both enabled and disabled installs.
