### ISSUE TITLE
Duplicate entries in language-tools api endpoint

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-server#8198]
### Describe the problem and steps to reproduce it:
Fetching either
https://services.addons.mozilla.org/api/v3/addons/language-tools/?app=firefox&appversion=60.0&type=language&lang=en-US
or
https://services.addons.mozilla.org/api/v3/addons/language-tools/?app=firefox&appversion=60.0&type=language

The `results` array has a number of (mostly) duplicated entries.  For example, the first entry is for the guid "langpack-ro@firefox.mozilla.org" and id 4551.  The second entry is mostly the same, the difference is that the "name" property in the first result is `null`, it is properly populated (depending in the presence of the `lang` key in the query string) in the second result.

Changing the query string from `appversion=60.0` to `appversion=59.0` gives results that don't exhibit this problem.

### What happened?

Results contained duplicate entries as described above.

### What did you expect to happen?

I expected results to contain unique (non-duplicated) entries.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
> Changing the query string from `appversion=60.0` to `appversion=59.0` gives results that don't exhibit this problem.

Also, not passing `appversion=` at all gives results that don't exhibit the issue as well. Annoyingly we can't reproduce on stage.

**Comment by aswan** [comment]
I believe that with langpack signing now happening in an automated way from the Firefox release pipeline, this is going to happen with every release (ie, we'll get langpacks as part of each RC build, the actual release, and any dot releases)

**Comment by diox** [comment]
Makes sense. I was working under the assumption that it would not happen and didn't test it, but we definitely want to support that.

**Comment by diox** [comment]
Firefox is not the only consumer of this API, it's also used by addons-frontend. It can return different types depending on what parameters you pass.

Regarding the files, there is no guarantee there will only be one - it all depends on what was set at upload time, and although it's controlled by the scripts set up by release engineering, I'm hesitant to make more assumptions, since this very issue comes from a previous assumption I had made because of the way the add-ons were set up in the past...

**Comment by diox** [comment]
@AlexandraMoga you can create an upload a language pack compatible with FF60 (needs to have `strict_min_version` and `strict_max_version` set in manifest) and upload it normally, it will be auto-approved. Then you'll need to create another version of the same langpack with the same compatibility set. Finally you'll have to call the language tools API endpoint with the parameters described in the description.

**Comment by AlexandraMoga** [comment]
@diox 
1. I've submitted a language pack as suggested above - see https://addons-dev.allizom.org/en-US/firefox/addon/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-language-pack/versions/
2. I've sent the following request:
```
https://services.addons-dev.allizom.org/api/v3/addons/language-tools/?app=firefox&appversion=60.0&type=language&lang=en-US
```
--> there are no results in the response

**Comment by diox** [comment]
@AlexandraMoga sorry, forgot an important step. Your add-on needs to have a "Target Locale" set. This is done through Admin Settings in the developer hub.

**Comment by diox** [comment]
@AlexandraMoga I believe that's just due to caching. We cache things with the URL for 24 hours, so if you change the query string you get the updated results.
