### ISSUE TITLE
Update Account endpoint documentation (`picture_url`)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#8200]
After https://github.com/mozilla/addons-server/issues/7679, the `picture_url` can be `null` and we no longer receive the URL of the default profile picture. [The documentation](http://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#get--api-v3-accounts-account-(int-user_id|string-username)-) should reflect these changes.

**Comment by AlexandraMoga** [comment]
Please add STR or the label 'qa:not needed'
Thanks
