### ISSUE TITLE
Disconnect Website

### ISSUE THREAD

**Issue by PayneLessDesigns** [mozilla/addons-server#8206]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Just try the "Get Disconnect" button and see if you get a "Not Found" page.
### What happened?
The "Get Disconnect" button on https://disconnect.me/disconnect sends me to a page like a 404 Error page --- "Not Found"
### What did you expect to happen?
I expected to get the Disconnect extension for Fx.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
The Disconnect site where button to get extension is: https://disconnect.me/disconnect

The "Get Disconnect" extension link is https://addons.mozilla.org/downloads/latest/disconnect?src=external-home-button .

Ron

**Comment by jvillalobos** [comment]
That's a bad link on the developer's website. You can find the add-on here: https://addons.mozilla.org/addon/disconnect/
