### ISSUE TITLE
Searching for an Image toggle addon and the correct results are buried.

### ISSUE THREAD

**Issue by Caspy7** [mozilla/addons-server#8207]
I came across this this post
https://www.reddit.com/r/firefox/comments/8huosl/help_addin_to_hide_images_in_firefox_59_and_higher/
saying, in part, "no matter how much I search for I can not find a working plugin that switches off/on showing/loading of images in web pages."

I did a search on AMO: https://addons.mozilla.org/en-US/firefox/search/?q=toggle+images 
using "toggle" instead of hide and only one hit was near the bottom of the page that was relevant.  ( I believe the original legacy addon (or one of them at least) used the word toggle.)
I sorted through the first 7 of 19 pages and found a total of 8 relevant hits (that all do about the same thing).  Here's the addons if it's helpful.

https://addons.mozilla.org/en-US/firefox/addon/image-block-x/
https://addons.mozilla.org/en-US/firefox/addon/image-video-block/
https://addons.mozilla.org/en-US/firefox/addon/easy-image-blocker/
https://addons.mozilla.org/en-US/firefox/addon/image-blocker-plus/
https://addons.mozilla.org/en-US/firefox/addon/block-image-video/
https://addons.mozilla.org/en-US/firefox/addon/hide-images-per-tab/
https://addons.mozilla.org/en-US/firefox/addon/image-hide/
https://addons.mozilla.org/en-US/firefox/addon/block-images-webextensions/ 

This seems a bit rubbish notably because of how modern users currently work. They're very used to Google quality search results, seldom make it to the bottom of the page and almost never go to page 2.

I've noticed several users on reddit complaining in recent history of poor search results on AMO.

**Comment by EnTeQuAk** [comment]
Just checking in here, we recently improved search a bit - or at least the ranking specifically but this specific scenario seems still very much not functional.

So I'll leave this open for further investigation.

**Comment by diox** [comment]
The fixes for https://github.com/mozilla/addons-server/issues/9196 and https://github.com/mozilla/addons-server/issues/6838 should help, but we can't do miracles and completely guess that one of the words the user is searching for is not the right one to use :)

Will re-evaluate once the fixes for the 2 issues I mention are in production.

**Comment by AlexandraMoga** [comment]
I've retried the same search example on prod but I've come up with pretty much the same results as pointed in the issue. 

I guess that #9196 and #6838 didn't improve this use case too much.

**Comment by diox** [comment]
There are 2 issues left here:
1. We need (custom) synonyms support to help users searching for "hide" find add-ons with only "toggle" in the description. Obviously we can't possibly define all potential synonyms, but still, maybe we can give this a shot.
2. Fuyzzy matching on the name is giving us too much garbage. When you search for "toggle images", you get tons of results with "Toggle" or "Image" in their name, because of the fuzzy match we apply on the name. Perhaps this is just a matter of adjusting the boost?

**Comment by diox** [comment]
Closing because I think the changes to fuzzy name matching in mozilla/addons#567 have improved the situation enough for this particular scenario. Synonyms support will be tracked in a future issue if we deem it necessary.
