### ISSUE TITLE
Submitting webextension with an invalid filename raises errors about the file being legacy

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8208]
Submit the following invalid webextension: [invalid_webextension.zip](https://github.com/mozilla/addons-server/files/1983794/invalid_webextension.zip)

Actual results:
<img width="978" alt="screen shot 2018-05-08 at 13 58 12" src="https://user-images.githubusercontent.com/873258/39756497-2c0e2242-52ca-11e8-9e96-a55fa09460cd.png">

Expected results:
Only the very first error should be raised.

**Comment by diox** [comment]
Going to remove one of the two warnings because it's in my way, but it's hard to fix this properly because we don't know it's a webext for sure since we're bailing early because of the invalid filename. Getting rid of legacy extensions will work around this :-)

**Comment by diox** [comment]
We now display the generic `Sorry, we couldn't load your WebExtension` error for this submission, so it's better tracked in https://github.com/mozilla/addons-server/issues/12054
