### ISSUE TITLE
Some developers have more than one active API key

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8211]
Some developers have more than one active API key, which is not supported and throws errors since the retrieval function relies on having only one.

We should enforce that in the database if possible, and figure out what to do with the affected keys.

**Comment by wagnerand** [comment]
For the record, the following sql query can be used to determine affected keys:

`SELECT created, modified, user_id, is_active  from api_key where user_id in (select user_id from api_key group by user_id having sum(is_active) > 1) order by user_id, created;`

**Comment by diox** [comment]
QA:
- Make sure you can't generate multiple API keys in any way. Also, if you have an account that did have multiple API keys before, like @vcarciu had on dev, make sure it's no longer the case and the api keys page is accessible, you can submit add-ons etc.
