### ISSUE TITLE
Use guids instead of ids in disco pane data

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8221]
We currently hardcode discopane contents inside [src/olympia/discovery/data.py](https://github.com/mozilla/addons-server/blob/master/src/olympia/discovery/data.py) so that strings get picked up by translators. To avoid accidentally linking to the wrong add-on if one gets deleted, we use their primary keys ids and not their slugs, which could potentially be re-used.

Using the ids makes it difficult to test discovery pane on dev&stage, cause it's annoying to create add-ons with the same id. But instead, we could switch to using `guid`s. We'd keep the same benefits but it'd be much easier to create test data.

**Comment by diox** [comment]
This can't be done while Personas haven't been replaced by Static Themes, because Personas have no guids.

**Comment by muffinresearch** [comment]
@diox don't they have a pseudo guid e.g. `something@getpersonas.com` ?

**Comment by diox** [comment]
No, I thought so, but I checked and they don't have one at all.

**Comment by muffinresearch** [comment]
Maybe not in the data, but IIRC that psuedo guid is used to introspect them in `mozAddonManager`.

**Comment by diox** [comment]
Disco pane data is going to move to a database source in https://github.com/mozilla/addons-server/issues/2448, rendering this issue obsolete.
