### ISSUE TITLE
Clear last_login_attempt_ip on user deletion

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8223]
We already anonymize most data when a user deletes their account we should also clear `last_login_attempt_ip` when a user deletes their account too.

This should also look to remove this for already deleted accounts too.

Needs to be in the 2018.05.24 push at the latest.

**Comment by EnTeQuAk** [comment]
We might want to extend that a bit and look into

 * `last_login_ip`
 * `last_login_attempt` (a datetime from when the last login attempt was)
 * `last_login_attempt_ip? (referenced in this issue)

too.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk @muffinresearch  I guess this can't be easily verified directly from AMO, right? Is there another method available to us to test these changes?

**Comment by EnTeQuAk** [comment]
Unfortunately, there isn't, as you don't have access to the database to test this properly. I'll take care of making sure that re-anonymizing usre-data works properly on dev and stage.
