### ISSUE TITLE
Update Firefox logo in old front-end header

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8224]
Brought up in https://github.com/mozilla/addons/issues/712.

We expose old front-end pages in some cases, particularly the public statistics dashboard for some add-ons ([example](https://addons.mozilla.org/addon/adblock-plus/statistics/?last=30)). We haven't planned when to port them to the new style, so it would be good to at least update the Firefox logo in the header.

**Comment by championshuttler** [comment]
Hi @jvillalobos , I would like to work on it

**Comment by jvillalobos** [comment]
Great. If you need any guidance, maybe @eviljeff can help?

**Comment by eviljeff** [comment]
for the header used on the statistic page you can just update the image in static/img/icons/

Looks like we have 6 other "firefox" images of various sizes in static/img/ though (excluding shield studies), which could also be updated - I'm not sure where they are used exactly, or if they are used at all still.

**Comment by ioanarusiczki** [comment]
I verified this on AMO dev with FF60(Win10).  I also checked other old pages, new logo seems to be present everywhere. 
![new logo](https://user-images.githubusercontent.com/33448286/40166764-0784dbbe-59c8-11e8-9d90-21943c194e02.png)
