### ISSUE TITLE
It should be possible to remove a review's body via the API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#8226]
This is related to https://github.com/mozilla/addons-frontend/issues/4367. It is currently not possible to pass a `null` into an API call to the edit endpoint to remove a review's body, but we would like to be able to do that. I understand that there are complexities behind the scenes on the server side which convert the string passed into the API into a localizedString, so that will need to be dealt with. As a consumer one should be able to call the edit endpoint, passing a `null` as the `body` and this should result in the corresponding localizedString being removed.

One item to discuss: What if a `null` is passed in using a locale that is different from one stored for the review? Should it only remove the data for the current locale, or should it remove the data for all locales? I would suggest it should remove all of them, as localized reviews are not something that has ever been documented and it's unlikely that someone would post reviews in multiple locales (intentionally) and then choose to remove the body from only one of those locales. If that is considered dangerous, or overly difficult to implement, I think it's fine to just remove the body for the current locale, although that seems sub-optimal.

**Comment by eviljeff** [comment]
See mozilla/addons-server#7832 also - it's the same underlying problem with the current API l10n implementation

**Comment by eviljeff** [comment]
is this issue still valid - ratings/reviews aren't localised any more afaik

**Comment by diox** [comment]
Right, this has worked on the API side for quite a while now - because of 356844f5153
