### ISSUE TITLE
Add-on name is localized in emails generated after a specific user action

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8230]
STR:

1. Log in to AMO and select a localized add-on to view its details page
2. Shift to a non-English locale (i.e. https://addons.allizom.org/ar/firefox/addon/adblock-plus-test/?src=search)
4. Post an abuse report for this add-on
5. With an admin account, open the fake email log and look for the abuse report notification
6. Inspect the email content (subject, body etc)

Actual result:
The name of the add-on is localized in the email subject and body

Expected result:
Add-on name should not be localized for email notifications

Note:
- reproduced on AMO dev and stage with FF60, Win10x64
https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-33109
![image](https://user-images.githubusercontent.com/31961530/39873963-1901cd96-5475-11e8-9ed9-411b1d8d72f7.png)
**Note** - the email subject will be rendered like this by a proper email client: **"[Extension] Abuse Report for آدبلوك ب, لس"**

Additional examples:
[- add-on review -](https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-33112)
[- add-on deletion -](https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-33127)

**Comment by AlexandraMoga** [comment]
This can be still reproduced - see https://addons-internal.stage.mozaws.net/en-US/admin/mail#msg-925

**Comment by diox** [comment]
We stopped sending abuse report emails in 27059216f3cd30d9f34d3ca8024a436f973550a8
