### ISSUE TITLE
change static theme previews to generate paint style simple ui

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8248]
As argued in #7888, the current "realistic" static theme previews (that attempt to show Firefox's UI) will get busy, especially when there are many on the same page.  So instead we will render a more simple, stylized, preview.

[amo static theme svgs.zip](https://github.com/mozilla/addons-server/files/2000457/amo.static.theme.svgs.zip)

**Comment by AlexandraMoga** [comment]
I've verified the new simplified static theme previews for the sections in which they are currently available:

**1. Developer Hub**

![image](https://user-images.githubusercontent.com/31961530/40303729-a9e5968c-5cfc-11e8-9eb4-d43bef3056b7.png)
----
![image](https://user-images.githubusercontent.com/31961530/40303761-cbe6d110-5cfc-11e8-80c6-dab6dc946adc.png)

**2.  Rev Tools**

![image](https://user-images.githubusercontent.com/31961530/40303764-d3d347be-5cfc-11e8-8f3b-fc75e637598a.png)
**3.  Screenshots section in listing page** 

![image](https://user-images.githubusercontent.com/31961530/40303792-f7f660e0-5cfc-11e8-92ef-9b8f622ecdd9.png)
**4.  Wizard Placeholder and browser preview**

![image](https://user-images.githubusercontent.com/31961530/40304063-efa7407a-5cfd-11e8-84da-9fa58a0af327.png)
---
![image](https://user-images.githubusercontent.com/31961530/40304176-53062f14-5cfe-11e8-90f6-5bb9c36df6fb.png)

**Not verified:** list view and shelf view, as they are not implemented yet

 @pwalm @eviljeff

Would it be possible to make the preview styles "less bold"? This can be best understood if you look now at a theme that uses default (black) colors for the Header/Toolbar icons/text, the generated screenshot seems overshadowed by the black lines. I'm thinking that for smaller screenshots (like shelf previews for example) they will look even more prominent. 

![image](https://user-images.githubusercontent.com/31961530/40305240-55ecf9e8-5d02-11e8-9037-26e9ede8e0a5.png)

**Comment by eviljeff** [comment]
You can see what the list view image will be because I implemented it as the "thumbnail" for the preview (and the shelf view will be the list view cropped).

@pwalm to decide on any changes to the new design.

**Comment by AlexandraMoga** [comment]
@eviljeff when you're saying that the listing view will be same as the "thumbnail" for the theme preview, are you referring to the below screenshot?

![image](https://user-images.githubusercontent.com/31961530/40425898-6669fd38-5ea2-11e8-8238-15fc0045b9df.png)

cropped version:
![image](https://user-images.githubusercontent.com/31961530/40426005-a2aad5b0-5ea2-11e8-96d1-7096a505234a.png)

**Comment by eviljeff** [comment]
@AlexandraMoga yes.  the thumbail is `list view.svg` and `shelf.svg` and `more by shelf.svg` files ux provided (see zip at the top) are basically just cropped versions of `list view.svg`

**Comment by pwalm** [comment]
This looks awesome, I will make the shapes less bold. 👍

**Comment by AlexandraMoga** [comment]
@pwalm , thanks for taking in consideration my suggestion. 

Until the updated design will be ready, I'm marking this issue as verified fixed, since the implementation was following the specs provided in the .zip attached to the issue. 

Verified with AMO -dev, FF60, Win10x64
