### ISSUE TITLE
add v4 documention; explain v3/v4 setup; archive v3;

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8254]
Mostly this is a v3 -> v4 find&replace.  We also need an explanation about v4 being the new unstable API and full of new goodness, and v3 being the old reliable, and that v4 is the default (as much as we can "default" without /api/ being available to us).
v3 api docs archive will be taken as the 2018.05.17 tag - once it exists RTD can expose that as a specific version for us to link to.

**Comment by AlexandraMoga** [comment]
@eviljeff does this require any QA?
