### ISSUE TITLE
Add API feature gates

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8255]
We need a sensible way of turning on/off features at a view or serializer level per api, so when we add a new feature to the v4 API, or remove something but have a fallback/shim for v3, it's only there for the correct version of the API.  I.e. don't break the v3 api; don't clutter the v4 api with obsolete response.

https://github.com/mozilla/addons-server/issues/8139#issuecomment-385866348 had a proposal - may need some tinkering as we have v4 - the unstable version - as the default rather than v3.

**Comment by eviljeff** [comment]
There's an argument here if we need something as heavy as feature gates, given how we develop our API.  Feature gates is based on the assumption (that I understand - plz correct) that there is a "stable" and "beta" API, both of which have changes, so feature gates allow features to be enabled on the "beta" API and then later enabled on the "stable" API.  AMO, on the other hand, has effectively a "frozen" (v3) and "development" (v4) API and new features aren't grandfathered into the "frozen" API, so the gates will never be enabled for v3.

The simple alternate is just doing:
```python
if request.version == 'v3': 
    ...
elif request.version == 'v4':
    ...
```

**Comment by EnTeQuAk** [comment]
A gate is not bound to a specific version, except the one it's
explicitly configured for.
gates are a way to do that request.version compare in a more documented,
easier to find fashion, especially if specific new functionality goes
all the way down to models. Looking for 'is_gate_active("responsive-profile-picture-
url")' is much easier than just the V3/b4 compare.
Gates do not rely on the idea that some functionality does go from beta
to stable, although adding that would be relatively easy.

On Fri, May 18, 2018, at 7:56 PM, Andrew Williamson wrote:
> There's an argument here if we need something as heavy as feature
> gates, given how we develop our API.  Feature gates is based on the
> assumption (that I understand - plz correct) that there is a "stable"
> and "beta" API, both of which have changes, so feature gates allow
> features to be enabled on the "beta" API and then later enabled on the
> "stable" API.  AMO, on the other hand, has effectively a "frozen" (v3)
> and "development" (v4) API and new features aren't grandfathered into
> the "frozen" API, so the gates will never be enabled for v3.> The simple alternate is just doing:


> if request.version == 'v3':  ... elif request.version == 'v4':  ...> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons-server/issues/8255#issuecomment-390284679

**Comment by EnTeQuAk** [comment]
Also, given a v4 to v5 move you can just copy all gate flags to the v5
gate config and have everything working, that way you don't need to look
for the request.version calls.

On Sun, May 20, 2018, at 8:03 AM, cg@webshox.org wrote:
> A gate is not bound to a specific version, except the one it's
> explicitly configured for.> 
> gates are a way to do that request.version compare in a more
> documented, easier to find fashion, especially if specific new
> functionality goes all the way down to models. Looking for 'is_gate_active("responsive-profile-picture-
> url")' is much easier than just the V3/b4 compare.> 
> Gates do not rely on the idea that some functionality does go from
> beta to stable, although adding that would be relatively easy.> 
> 
> On Fri, May 18, 2018, at 7:56 PM, Andrew Williamson wrote:
>> There's an argument here if we need something as heavy as feature
>> gates, given how we develop our API.  Feature gates is based on the
>> assumption (that I understand - plz correct) that there is a "stable"
>> and "beta" API, both of which have changes, so feature gates allow
>> features to be enabled on the "beta" API and then later enabled on
>> the "stable" API.  AMO, on the other hand, has effectively a "frozen"
>> (v3) and "development" (v4) API and new features aren't grandfathered
>> into the "frozen" API, so the gates will never be enabled for v3.>> The simple alternate is just doing:


>> if request.version == 'v3':  ... elif request.version == 'v4':  ...>> — You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub[1], or mute the
>> thread[2].>> 

Links:

  1. https://github.com/mozilla/addons-server/issues/8255#issuecomment-390284679

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not neded"?

**Comment by eviljeff** [comment]
Both the case where the original `Rating.rating` is returned, and the new `Rating.score` should be tested.  
Easiest way to test original behaviour is to check addons-frontend still works for retrieving, creating, and editing user ratings.
To test the new behaviour the kind of testing in https://github.com/mozilla/addons-server/issues/6849#issuecomment-392009543 is probably good enough - see that the JSON response for v4 has `score` in the response rather than `rating`

**Comment by AlexandraMoga** [comment]
I have checked the JSON response for the new `v4` ratings endpoint and the value  posted by the user is expressed under `score`

Example:
`https://addons-dev.allizom.org/api/v4/ratings/rating/?addon=greenleafs-v2`

![image](https://user-images.githubusercontent.com/31961530/40646315-759fd226-6331-11e8-91ac-280442205806.png)

I've checked the ratings component on the frontend (submitting reviews, editing reviews, adding dev replies, flagging) and I could not observe any regressions.
Also, the JSON response for the `v3` api is expressing the value given by the user under `rating`
