### ISSUE TITLE
"More Actions" is too far down on the review page

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#8262]
The whiteboard fields are blank or only contain one line most of the time. Having to scroll down 800 pixels of whiteboards gets cumbersome if I want to be notified if a new version gets submitted:

Two improvements I thought of:

- Move the "More Actions" section above the whiteboard(s)
- If a whiteboard is empty (`:empty`), hide them (`display:none`), and only show the empty whiteboard if a button is pressed/clicked on the page.

**Comment by jvillalobos** [comment]
I think having the whiteboards collapsed when empty makes sense, and it's a relatively easy fix to implement.

**Comment by LordGameleo** [comment]
Is this open?... I would like to take it.

**Comment by LordGameleo** [comment]
Yes I would like to take it. How can I reproduce it.

**Comment by LordGameleo** [comment]
@EnTeQuAk  will you be mentoring me on this issue?

**Comment by AlanXu12** [comment]
Is this issue still open? I'm interested in working on it :)

**Comment by eviljeff** [comment]
Note https://github.com/mozilla/addons-server/pull/13792#discussion_r399444293 as a possible/probable fix for the whiteboard
