### ISSUE TITLE
Use `src=collection` when clicking on collection shelf on homepage

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#8264]
Go to the AMO homepage. Content programming frequently changes, but often we'll use a collection to feed into a homepage shelf. 

Currently we have a "Privacy tools" collection on the homepage. If you click one of the individual extensions directly from the shelf—for instance Ghostery—you click thru to its detail page and the URL looks like so:

https://addons.mozilla.org/firefox/addon/ghostery/

Now, go back the homepage. And click "See more privacy tools" link at the far right of the module. Then find Ghostery and click. Its detail page will look like so:

https://addons.mozilla.org/firefox/addon/ghostery/?src=collection

The source should be the same in both cases (src=collection), regardless of whether it's clicked directly from the homepage shelf, or from within the full collection.

**Comment by jvillalobos** [comment]
Should the `src` for collections in the homepage be the same as for any other random collections on the site? Would it be more useful to have a `homepage` or `homepage-collection` value for `src` so they can be differentiated?

**Comment by devaneymoz** [comment]
It would definitely be more useful if we can get more granular with the 'src' from homepage collections. 

I think the ideal case would be to know the specific collection it originated from, as well. In other words, we often have the same extension promoted in multiple concurrent homepage collections (e.g. uBlock Origin is in the "Featured" collection, as well as "Ad blockers" collection; understanding which performs better could help to optimize future programming decisions. So maybe it would be something like... src=homepage-collection-featured  ....  src=homepage-collection-ad-blockers

**Comment by diox** [comment]
Refiled on addons-frontend: https://github.com/mozilla/addons-frontend/issues/5476
