### ISSUE TITLE
Migrated LWT can't be installed on AMO

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8266]
Prerequisites:
- use an unbranded version of Firefox
- apply the following prefs: `xpinstall.signatures.required` - `false` ; `xpinstall.signatures.dev-root` - `true`

STR
1. Log in to AMO and go to the details page of a migrated LWT - see https://addons-dev.allizom.org/en-US/firefox/addon/green-space2/
2. Click on 'Add to Firefox'

Actual result:
Theme is not installed because Firefox reads it as "corrupt"

Expected result:
Theme is successfully installed

Notes:
 - I have been able to install other static themes, created by me for example, without receiving any errors
 - Theme status is Approved
 - reproduced on AMO-dev, with FF60, WIn10x64
![lwt install error](https://user-images.githubusercontent.com/31961530/40110449-aae60ae6-5908-11e8-90ea-ad5c9875912e.gif)

**Comment by eviljeff** [comment]
I think it's because I just set the status rather than pushed it through the signing process.

**Comment by diox** [comment]
oops :>

**Comment by AlexandraMoga** [comment]
@eviljeff  I am still reproducing the issue. Do you think that your update was also applied to the already migrated themes? For example, if I download the theme .xpi, there is no META_INF file in the package.

**Comment by eviljeff** [comment]
The ones we migrated before will stay broken -  I'll have ops do some more.

**Comment by eviljeff** [comment]
Tried to migrate these:
https://addons-dev.allizom.org/en-US/firefox/addon/building-a-snowman/
https://addons-dev.allizom.org/en-US/firefox/addon/wolf-eye-to-eye/

But got a fail in the celery task that generates the previews:
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4366764/

Would still be interested to know if they're signed properly though!

**Comment by AlexandraMoga** [comment]
Those themes can be installed and their package also contains the META_INF file

![image](https://user-images.githubusercontent.com/31961530/40800888-3b441fd4-651a-11e8-94f4-7d7ed78aea99.png)

Marking issue as verified fixed on AMO-dev, with Nightly 61.0b10, Win10x64

**Comment by eviljeff** [comment]
logged the preview generation fail as #8405
