### ISSUE TITLE
Ratings are missing for migrated LWT

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8267]
STR:

1. Log in to AMO-dev and go to the details page of a migrated LWT - see https://addons-dev.allizom.org/en-US/firefox/addon/green-space2/
2. Check the statistics card (users, average rating) displayed at the top right side

Actual result:
There are no stats available for the migrated lightweight theme

Expected result:
User downloads, average rating and number of reviews (written and unwritten) should also be migrated with the LWT

Notes:
- reproduced on AMO-dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40111107-8b2690c0-590a-11e8-82d5-8aea23acb7c0.png)

**Comment by eviljeff** [comment]
The ratings part of this landed already so I'm calling that closed and opening a new issue for (the much more tricky) usage statistics part.

**Comment by AlexandraMoga** [comment]
The best examples to migrate that will help in testing are:

https://addons-dev.allizom.org/en-US/firefox/addon/lilac-prediction/?src=search
https://addons-dev.allizom.org/en-US/firefox/addon/litefox/?src=search
https://addons-dev.allizom.org/en-US/firefox/addon/an-autumn-reverie/?src=search

**Comment by eviljeff** [comment]
@AlexandraMoga command has been ran.  They look good to me.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/42036024-fbe62862-7aec-11e8-851d-564b465d0aef.png)
![image](https://user-images.githubusercontent.com/31961530/42036026-ff650544-7aec-11e8-855f-ced23099d82a.png)
