### ISSUE TITLE
Remove notifycompat and notifyevents from database.

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8274]
https://github.com/mozilla/addons-server/pull/8258 removed them from our code and once that lands in the May 23rd milestone we can add a migration that removes these fields from the database too.

Since it's something on the `users` table we should make ops aware of the migration.

**Comment by championshuttler** [comment]
I will try to solve it ;)

**Comment by lavish205** [comment]
I would like to work on this bug. Please guide me with some initial steps.

**Comment by vcarciu** [comment]
Can you please add "qa: not needed" for this issue?
