### ISSUE TITLE
User accounts can't be updated on the legacy pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8281]
STR:

1. Log in to AMO-stage with a newer account
2. Select Edit my Profile from the User menu (https://addons.allizom.org/en-US/firefox/users/edit)
3. Edit some of the available fields
4. Click on Update Account

Actual result:
A server error is received after submitting an account update

Expected result:
User account is successfully updated

Notes:
- reproduced also on AMO-dev with the legacy pages
- I did not reproduce with one of my older accounts
- not reproduced on prod
- not sure if [frontend-issue#4284](https://github.com/mozilla/addons-frontend/issues/4284) can have any implications

![profile 500](https://user-images.githubusercontent.com/31961530/40163805-742d5938-59c0-11e8-909e-ddc8578b5e39.gif)

**Comment by EnTeQuAk** [comment]
That's because of the new basket integration, I didn't know it throws
that kind of error for unknown users. I'll fix this asap

On Thu, May 17, 2018, at 9:54 AM, Alexandra Gal-Moga wrote:
> STR:


>  1. Log in to AMO-stage with a newer account
>  2. Select Edit my Profile from the User menu
>     (https://addons.allizom.org/en-US/firefox/users/edit)
>  3. Edit some of the available fields
>  4. Click on Update Account> Actual result:
>  A server error is received after submitting an account update


> Expected result:
>  User account is successfully updated


> Notes:


>  * reproduced also on AMO-dev with the legacy pages
>  * I did not reproduce with one of my older accounts
>  * not reproduced on prod> profile 500


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons-server/issues/8281

**Comment by EnTeQuAk** [comment]
The fix just got merged and should be on -dev and -stage in a few minutes.
