### ISSUE TITLE
Implement quoted search

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8284]
### Describe the problem and steps to reproduce it:

We get asked for this a lot and it seems like a reasonable request. We should add support for quoted searches that would mean for the quoted search stemming would be bypassed. 

### What happened?

Currently AFAIK only searches based on stemmed terms are carried out. This means a search for `fixed` will actually search for the stem `fix` irrespective of whether quotes are used.

This makes it hard for a user to tune their search. Quoting is commonly supported in search engines and users are used to using it to further qualify search results.

### What did you expect to happen?

If a user submits a search with quotes e.g. `'fixed'` that term should be searched for exactly. 

### Other information

A possible recipe for doing this exists here: https://www.elastic.co/guide/en/elasticsearch/reference/current/mixing-exact-search-with-stemming.html

**Comment by diox** [comment]
> Currently AFAIK only searches based on stemmed terms are carried out. This means a search for fixed will actually search for the stem fix irrespective of whether quotes are used.

That is not entirely true. [We **are** already boosting on exact matches](https://github.com/mozilla/addons-server/blob/2d8cf8c6b35ae54dd1880f0ba3aa89a21b41185e/src/olympia/search/filters.py#L302-L328). Or rather, we should be. The problem is that it doesn't seem to be working correctly, and we are not sure why. I'd rather fix this than implement quoted search tbh.

**Comment by diox** [comment]
See also https://github.com/mozilla/addons-server/issues/6837 in which we did implement the exact match I'm talking about in my previous comment... it got re-opened because well, it doesn't work like it should :(

**Comment by diox** [comment]
Between addons and addons-server repos we've got ~ 20 issues opened around search dealing in various ways with the fact that relevancy is broken. My point is that we need to fix relevancy and exact match, and I bet that then we won't need to implement quoted search at all.

**Comment by diox** [comment]
To add to that, I firmly believe that anything forcing the user to add specific magical characters to their search query is bad UX. Users shouldn't need to search for `"something"` to find an add-on named that way. It should be higher up in the results, at the top even if it's an exact match.

**Comment by muffinresearch** [comment]
@diox fair enough. I'll mark this as YAGNI. Let's aim for fixing https://github.com/mozilla/addons-server/issues/6837 if exact matches are boosted correctly and that negates the need for quoting that sounds good to me.

Closed in favour of fixing https://github.com/mozilla/addons-server/issues/6837 instead.
