### ISSUE TITLE
Buttons from More Actions section in Add-on review page are not working

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8285]
STR:

1. Log in to AMO Reviewer Tools with a user that has add-on review permissions
2. Select the Auto-approved queue from Reviewer's dashboard (https://reviewers.addons.allizom.org/en-US/reviewers/queue/auto_approved)
3. Pick an add-on that is currently pending for review to access its review page
4. Scroll down to More Actions section and click on any of the available buttons

Actual result:
The buttons from More Actions section are non-responsive

Expected result:
The buttons from More Actions section are working

Notes:
- reproduced on AMO dev and stage with FF60, Win10x64

![more actions buttons](https://user-images.githubusercontent.com/31961530/40178277-bbc5ba6e-59e9-11e8-9598-f59129b188c0.gif)

**Comment by diox** [comment]
This is because of #8139 ; this is (accidentally, but I don't think we need to change that yet?) using v4, and we haven't whitelisted v4 in the locale middleware so we're hitting a redirect instead of POSTing normally.

**Comment by diox** [comment]
in `settings_base.py` we need to modify `CORS_URLS_REGEX` and `SUPPORTED_NONAPPS_NONLOCALES_PREFIX`

**Comment by vcarciu** [comment]
Verified as fixed for all buttons from description
