### ISSUE TITLE
Notifications endpoint should only return the notifications the user is interested in

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#8286]
### Describe the problem and steps to reproduce it:

Call the notifications endpoint: https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#notifications-list

### What happened?

We get all the notifications (11 at the time of writing), even if the user is not a developer.

### What did you expect to happen?

We should only get the notifications that will be displayed to the user, so if she is not a developer, she should not get the 11 notifications (only 2 I think).

**Comment by diox** [comment]
So the form has this, that we should probably steal for the API:
```python
        visible_notifications = (
            notifications.NOTIFICATIONS_BY_ID if self.instance.is_developer
            else notifications.NOTIFICATIONS_BY_ID_NOT_DEV)
```

Not sure I like the idea of hiding stuff in API results though. Maybe instead we should expose which notifications are dev-only notifications and let the frontend knows whether the user is a developer or not when they log in ? Or even when they call this API?

**Comment by willdurand** [comment]
It would be faster/more efficient for the frontend to get only what it needs (rather than filtering 70% of the receiving data because that won't be used in any case).

This endpoint already depends on the authenticated user so it is more about receiving an accurate response than hiding stuff.

**Comment by diox** [comment]
Fair warning, this API will eventually be slow anyway because of the basket integration :) And it's not that much extra data. But yeah, you're probably right, let's do see on the API side.

**Comment by EnTeQuAk** [comment]
I'd argue this as part of filtering data the user has access to so this is a matter of permissions in a way. I think filtering out the data should be fine.

I wonder though - not sure how that currently works - if a developer looses the developer-state, we don't unsubscribe him anywhere currently, do we?

**Comment by diox** [comment]
> I wonder though - not sure how that currently works - if a developer looses the developer-state, we don't unsubscribe him anywhere currently, do we?

Right, but it shouldn't matter that much I think. They shouldn't receive developer-specific notifications if they are not a developer, and they can unsubscribe from the newsletter from the email preferences center anyway (see also https://github.com/mozilla/addons-server/issues/8320)

**Comment by willdurand** [comment]
I just noticed that the notification `announcements` is returned twice by the API.

**Comment by AlexandraMoga** [comment]
I've checked this in the frontend by signing in with a developer and with a regular user account:

**[1] regular user**
![image](https://user-images.githubusercontent.com/31961530/41024212-488b3e1e-6977-11e8-90b7-dc03fe5640fb.png)

**[2] developer** (ignoring the duplicate `announcement` notification)
![image](https://user-images.githubusercontent.com/31961530/41024261-6e7882d0-6977-11e8-9f5d-c17973acdd8d.png)

As this seems to be the expected behavior, I'm marking the issue as verified fixed on AMO dev with FF60, Win10x64
