### ISSUE TITLE
User deletion might set already set username

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8289]
STR:

 * Another user already has set "Anonymous-631" (say, user-id 12314141)
 * the actual user with the id 631 is deleted
 * User with id 631 get's re-deleted because of data-scrubbing
 * Now we're setting username to "Anonymous-631"

…but that'll fail because username needs to be unique

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Hello Chris, could you add some STR for QA testing ?
Thanks!

**Comment by ioanarusiczki** [comment]
I talked with @diox so I did the following test on AMO dev with FF60(Win10):
1. Created two users anonymous-316651f91f257f0b80132a390b7a842f with currentUserID:10641648 and anonymous-2ec6790b1a7fde02d428f62eb4188536 
2. Renamed the second user anonymous-10641648
3. Deleted the first user anonymous-316651f91f257f0b80132a390b7a842f (from the old pages) 
4. Re-logged in and checked the username, it's anonymous-cd615d63c6ff052592393c4d389d6198 which means it gets a new username.

Please let me know if  this can be marked verified fixed on AMO dev with FF60(Win10).
