### ISSUE TITLE
API wrapper for TAAR lite should show fallback if < 4 addons are unavailable.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8300]
Refiled from: https://github.com/mozilla/addons-frontend/issues/5044

### Describe the problem and steps to reproduce it:
* Go to https://addons-dev.allizom.org/en-US/firefox/addon/bloody-vikings/
* Ensure you have the `taar_cohort` cookie set to `TAAR_COHORT_INCLUDED`
* Note the empty recommendations block. 

### What happened?
<img width="1057" alt="bloody_vikings__ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/40244160-ffe4237c-5ab9-11e8-96df-64b3aeb8abf1.png">

### What did you expect to happen?

Show the fallback add-ons.

From @willdurand's comment:

The API response for this add-on is:

```json
{
    "count": 0,
    "fallback_reason": null,
    "next": null,
    "outcome": "recommended",
    "page_count": 1,
    "page_size": 1,
    "previous": null,
    "results": []
}
```

The taar data is synced every 24 hours so the likelihood of this occurring is limited to the 24 hour window following each sync.

In any case if taar asks for add-ons that we don't have anymore because they've been removed this should show the fallback data and give a reason.

For the fallback content if one of the 4 add-ons disappears during the study we just show what we have. If this happened it would require the entire trial to be re-run in any case.

**Comment by AlexandraMoga** [comment]
Verified on AMO-stage with FF60 by using several add-on examples. In all cases, when guids returned by TAAR did not have or had only partial equivalents on AMO stage, the recommendations displayed were brought from `fallback`.

Here is a concrete example:
```
GET https://addons.allizom.org/api/v3/addons/recommendations/?guid={73a6fe31-595d-460b-a920-fcc0f8843232}&recommended=true&lang=en-US
```
Response:
`"outcome": "recommended_fallback",`
   ` "fallback_reason": "invalid_results",`

Check the same guid with the TAAR-lite endpoint...
```
GET https://taarlite.prod.mozaws.net/taarlite/api/v1/addon_recommendations/{73a6fe31-595d-460b-a920-fcc0f8843232}/
```
...then verify if the guids recommended by TAAR are indeed not found on AMO-stage. In this case, only 3 out of the 4 recommended add-ons are available on stage.

And here is the add-on details page on the frontend:


![image](https://user-images.githubusercontent.com/31961530/40422335-b7ed8dec-5e97-11e8-9c9d-ae01846e6fa1.png)
