### ISSUE TITLE
Stop using username

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8302]
AMO has a username field and a display name field. The distinction exists because usernames used to be for authentication, and they had stricter formatting requirements (like no spaces). The display name was meant as a more user-friendly name that would fall back to the username if not set.

Since we're using FxA for auth on AMO, this distinction doesn't make sense anymore. To address issues like https://github.com/mozilla/addons-server/issues/8296, I think we should merge both fields and have a single display name field with the same rules as the current display name, with the addition of uniqueness as a restriction.

**Comment by eviljeff** [comment]
the username is used in urls though

**Comment by eviljeff** [comment]
What should happen for currently non-unique display names?

Tbh, it would be a lot more straightforward to drop `display_name` instead

**Comment by jvillalobos** [comment]
> Tbh, it would be a lot more straightforward to drop display_name instead

How about this:

1) Drop `display_name`.
2) Relax the rules for `username` so they are "unique `display_name`".
3) Notify developers about the changes.

This way we don't break existing URLs and developers get the choice to switch back to their nicer names if they don't mind the change in their user URLs. Display names can be encoded so they work as slugs, right?

**Comment by eviljeff** [comment]
I did some local testing.  Our current username validation rejects any spaces and most special characters (anything other than letters+numbers+`-`+`~`).  However, when I edited via django-admin, which bypassed any validation, I was able to set a username such as `This is a special username!` which worked in the url fine(*).  

So we can pretty much allow anything, but encoding "abnormal" characters results in crappy looking urls when encoded, so we usually don't.  It can also complicate things like passing the username as a parameter (we do it in some of the APIs) as a comma, ampersand, etc would need to be encoded to stop them from breaking something.  The biggest risk is existing code in addons-server or addons-frontend that does an append or string substitution without encoding the parts first (worst case I can think of is it might allow masquerading as another username).  So if we relax from letters+numbers+`-`+`~` I would advise the least relaxation possible to have "nice" usernames)

(*) Firefox displayed it in the url bar as `/en-GB/firefox/user/This is a special username!/` and it's encoded as `/en-GB/firefox/user/This%20is%20a%20special%20username!/` when shown as text.

**Comment by eviljeff** [comment]
@jvillalobos what would be the minimum relaxing that would be needed to have "nice" usernames?  Is allowing spaces sufficient?  We already support mixed case.

**Comment by jvillalobos** [comment]
Looking at the [top display names](https://sql.telemetry.mozilla.org/queries/54942/source), here's what I think we need to support (besides what's already supported + spaces).

* Punctuation (`Ipswitch, Inc.`, `Paolo "Kaosmos"`, `Justin Scott (fligtar)`, `Yahoo!`).
* Other common symbols (`Поиск@Mail.ru`, `V@no`, `Vlad & Serge Strukoff`). `+`,  `<`, `>`, `=`, `[`, `]`, `{`, `}`, also come to mind. I suppose there's a standard set of symbols we can allow.
* Accented characters, Cyrillic characters (`Яндекс`, `Mime Čuvalo`, `Sören Hentzschel`). This one I'm not so sure about. We definitely don't want to get into a whole Unicode slippery slope, but if we can at least cover the "Western" alphabets, that would be ideal.

**Comment by jvillalobos** [comment]
Adding to this, we should also require at least one Latin character in the name, so it's not all symbols.

**Comment by eviljeff** [comment]
what about all those people with the misfortune to be given names not in the Latin character set? (i.e. half the world)

**Comment by jvillalobos** [comment]
They'll need an alias that includes a Latin character. It's not uncommon that people from that side of the world use aliases that are entirely in Latin characters. It's inconvenient and unfair, but necessary for SEO and content quality reasons.

**Comment by jvillalobos** [comment]
One more thing! Length should be between 2 and 50 characters.

**Comment by eviljeff** [comment]
> It's not uncommon that people from that side of the world use aliases that are entirely in Latin characters

Common in some cultures, I'm not sure as common in others.  Mixing Hebrew, Arabic (RTL) with ASCII (LTR) may also cause complications somewhere along the line.

**Comment by muffinresearch** [comment]
> They'll need an alias that includes a Latin character. It's not uncommon that people from that side of the world use aliases that are entirely in Latin characters. It's inconvenient and unfair, but necessary for SEO and content quality reasons.

Do you have some additional content for this? Maybe I'm misunderstanding something but I'm confused as to how requiring a single character Latin character in a string that's otherwise Unicode would meet SEO or quality requirements.

**Comment by jvillalobos** [comment]
@MeridelW can help clarify this point. I think it has more to do with usernames not being a just string of symbols rather than international characters.

**Comment by MeridelW** [comment]
The rationale for requesting that devs include a Latin character was two-fold:

1. From a content quality perspective, I want to avoid having display names in all special characters, which aren't legible or very good at inspiring trust of users. 

2. From an SEO perspective, Raphael recommended that URLs should only contain  "a-z", "1-9" and "-". I am not sure, however, is this recommendation is actually about SEO or still just about content quality. 

**@rraue Can you please elaborate on this recommendation?**

**Comment by rraue** [comment]
The problem with non latin characters is, that there are different ways to interpret it and to get diplicate content. If we can make sure, that both writings always are redirected to just one url, it would be fine. In the end, in my experience, this simple task at the end is bigger pain then going full latin.

One example: https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5. Open this link, its a simplified Chinese url with Chinese signs in it. But if you copy and paste it, it will be translated into latin characters. Same for urls with üöä in Germany. 

I agree, that this system is not great and ignoring half of the world, but right now special signs cause problems for any kind of crawlers, apis, servers and clients.

**Comment by eviljeff** [comment]
thanks @rraue 

So, the requirement (for "good" urls) is basically to have all usernames that are just `a-z,A-Z,0-9`?  That's what we already have, so that's fine.  IMO that leaves only a few options:
a) wonfix this issue because it's not feasible to have a "nice" display name that is also a "good" username.
b) drop display name and just have a username (i.e. we're not _merging_ display name into username).

**Comment by eviljeff** [comment]
yeah, with c) we'd have to keep `username` around for the most part and continue to support it in the APIs to make existing urls work.  For new users we just wouldn't show username and let them edit it... but for existing users that have set their username I suppose we'd have to allow them to keep editing it?  Or show it but don't allow them to change it?  

This is probably as much, if not more, a frontend than server change - frontend would have to switch to showing IDs in urls instead of usernames in the urls and handle existing users with usernames differently in the account profile page.  mozilla/addons-frontend#6275 would need doing in reverse.

Note: collections use username in the url too, so https://addons.mozilla.org/de/firefox/collections/mozilla/bookmark-managers/ would become https://addons.mozilla.org/de/firefox/collections/4757633/bookmark-managers/ (that link doesn't work right now - frontend bug) unless we add additional extra complexity to special case special accounts that _should_ have an exposed username.

**Comment by jvillalobos** [comment]
> for existing users that have set their username I suppose we'd have to allow them to keep editing it? Or show it but don't allow them to change it?

It wouldn't be shown for any users. The old URL would still work as a redirect to the ID URL, but developers wouldn't have a way to change it.

> Note: collections use username in the url too

Good point, and another important reason to keep the usernames to redirect, particularly for Mozilla collections.

**Comment by eviljeff** [comment]
> Make user and collection URLs redirect from the /username/ URLs to the /userID/ URLs.

mozilla/frontend#6275 can probably be refocused for that for frontend.

**Comment by willdurand** [comment]
>  Use /userID/ URLs throughout the site, instead of /username/.

I filed https://github.com/mozilla/addons-frontend/issues/6526.

**Comment by eviljeff** [comment]
> Use display name everywhere we identify the user on the site, without the username fallback.

What should happen for users who haven't set the display name, but we need to display a name in the UI?
There are three cases (I can think of):
a) existing user who has set a username (currently we display `username`)
b) existing user who hasn't set a username (currently we display `Firefox user {xxx}` where xxx is like `abcd12`, extracted from the generated username in the form `anonymous-abcd123456ef...`)
c) a future new user where we may not generate the `anonymous-abcd123456ef...` username  (I think django needs a single username field so for backwards compat we may just have the username be the numeric user id)

Should we display the numeric id when there isn't a username?  Or something like `Firefox user {user-id}`?  Or do something different depending if it's a), b) or c) ?

@jvillalobos

**Comment by jvillalobos** [comment]
I think it should be something like `Firefox user {user-id}`, to have somewhat consistent behavior for users who haven't set it.

**Comment by diox** [comment]
> Other than not allowing display names that are just spaces, current character restrictions to the display name should remain the same.

I think for this, if we want to go further, my suggestion in https://github.com/mozilla/addons-server/issues/10097#issuecomment-448253159 should work - Using `unicodedata.category` + the [Unicode Character Database](http://www.unicode.org/reports/tr44/tr44-6.html#Property_Values) properties values we can figure out whether each character is meant to be a letter in any alphabet, or punctation, space character of any kind, symbol, etc

**Comment by eviljeff** [comment]
Logged follow-up issues for all the remaining parts.  As username is used _very_ extensively in the codebase I'll leave this issue open for follow-ups and clean-up once all the dependent issues have completed.

**Comment by eviljeff** [comment]
I think we've removed all the public facing uses of username now.  The API still supports username in urls for backwards compatibility, and exposes it for the same reason, but doesn't allow it to be set.  Urls throughout addons-server and addons-frontend use the user-id and if `display_name` isn't set then the user-id is used instead rather than the username.

We could consider future work to entirely remove username from the model but there are a lot of tests that rely on it that would need to be changed, and django requires `USERNAME_FIELD` to be defined anyway (we'd have to switch `USERNAME_FIELD` to be `id` or `email` I guess) so there are decreasing returns for the effort involved.  

In the mean time, closing this issue as done.  Any random instances of username we've missed can be filed as follow-ups.
