### ISSUE TITLE
The add-on submission is stuck in validation state on AMO dev 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8317]
STR:

1. Load AMO dev and from dev hub try to submit an extension.
2. Observe page.

Expected result:
Submission is completed without issues.

Actual result:
Submission won't pass through the validation state - is stuck

Notes:
This issue is reproducible on AMO dev with FF60(Win10),
This is reproducible with static themes too.

![won t pass validation state](https://user-images.githubusercontent.com/33448286/40309343-c4842cc8-5d11-11e8-8685-dac7a957036e.png)

**Comment by diox** [comment]
We just updated celery to 4.1.1 and kombu to 4.2.0 could it be related?

Saw this in sentry:
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4342770/

And in the logs:
```
Error response from daemon: No such container: olympia-devhub
Error response from daemon: No such container: olympia-devhub
Error response from daemon: Cannot kill container olympia-devhub: No such container: olympia-devhub
Error response from daemon: No such container: olympia-devhub
```

**Comment by diox** [comment]
Deploy issue, fixed itself.

**Comment by ioanarusiczki** [comment]
Yes, it works again now - verified fixed on AMO dev with FF60(Win10). I tested with a couple of extensions.
![passed validation](https://user-images.githubusercontent.com/33448286/40313447-78c65b50-5d1e-11e8-8c12-47dad2f49dab.png)
