### ISSUE TITLE
Additional parameters for dev marketing email setting with Basket 

### ISSUE THREAD

**Issue by jessilyndavis** [mozilla/addons-server#8320]
This is a feature enhancement to the work done in: https://github.com/mozilla/addons-server/issues/7808

Please add these 2 parameters to the Basket API calls:
1) source_url = https://addons.mozilla.org/firefox/users/edit
2) optin = Y 

Additional details on how this is setup:
http://basket.readthedocs.io/newsletter_api.html#news-subscribe

1) "Source URL" allows us to acknowledge in our system where/how people join our email programs. It is important to keep this information for legal purposes.

2) "Optin" controls our double opt-in process. Since email opt-in status is captured behind a Firefox Account login, the double opt-in process for this email program can be bypassed. We are currently bypassing the double opt-in process via the Basket admin setting for this email program.

To enable stand-alone email opt-in forms for the "about:addons" newsletter, outside of the AMO Dev user settings, we will need to enable the double opt-in process. Once the "double opt-in" setting is enabled, if this integration does not send the "optin = Y" parameter, AMO Devs will have to confirm their subscription via email when they check the email opt-in box in their AMO dev settings. This is an unnecessary barrier for our devs who want to get emails from us.

**Comment by jessilyndavis** [comment]
For this particular integration between the AMO Dev user profile settings email opt-in waffle and Basket, yes!

If/when you want to put the about:addons email opt-in somewhere else on the AMO site (or anywhere else) - then no.

**Comment by jvillalobos** [comment]
@EnTeQuAk this looks like a trivial addition. Can it be done this quarter?

**Comment by AlexandraMoga** [comment]
Could you please add STR to this issue or the label 'qa:not needed'?
Thanks

**Comment by EnTeQuAk** [comment]
STR:
 * Subscribing and unsubscribing to newsletters on the user profile page should work as expected
 * Especially the about-addons (developer news) which tests the basket integration explicitly

**Comment by jessilyndavis** [comment]
@AlexandraMoga - If possible, could you try a brand new user opt-ing into the newsletter from AMO on Stage?

I need to check Salesforce to make sure the parameters passed through correctly.

Thank you.

**Comment by AlexandraMoga** [comment]
@jessilyndavis  - I've created a new user on stage and subscribed to the about:addons newsletter from AMO:
The new user is: retest-basket-stage@mailinator.com

**Comment by jessilyndavis** [comment]
Brilliant! Thanks @AlexandraMoga ! Everything passed through correctly.

**Comment by AlexandraMoga** [comment]
@jessilyndavis here is a new user I used to test again in prod:
prod-fxa@restmail.net

**Comment by jessilyndavis** [comment]
Perfect! Prod is working great.

Thanks @AlexandraMoga ! :)
