### ISSUE TITLE
May 2018 updates to DevHub landing copy - signed in view 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#8322]
﻿This is the monthly update to the [Add-ons Developer Hub](https://addons.mozilla.org/developers/). These updates pertain to the view developers see when they are signed-in. 

**Current screenshot:** 
﻿
![screen shot 2018-05-21 at 10 56 25 am](https://user-images.githubusercontent.com/23342476/40325351-3bf3038c-5cf0-11e8-8b9b-0a1e5c1c35fd.png)

**Changes:** 

- Change “Get Started” to “Welcome Back” 
- Column 1: 
--  Change text to: “We’re interested in your feedback about the extension development experience! Take our short survey to  let us know what kinds of documentation, APIs, and tools would be most useful to your development work.
-- Change CTA to say “Take Survey” and link to https://qsurvey.mozilla.com/s3/Extension-Developer-survey

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64

![dev-hub-log-promo](https://user-images.githubusercontent.com/31961530/40541740-c61cbf16-6025-11e8-9167-cd18eab476fb.gif)
