### ISSUE TITLE
May 2018 updates to DevHub - signed-out view 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#8323]
This is the monthly update to the [Add-ons Developer Hub](https://addons.mozilla.org/en-US/developers/). These updates pertain to the view developers see when they are not signed in. 

**Current screenshot**

![screen shot 2018-05-21 at 10 58 32 am](https://user-images.githubusercontent.com/23342476/40325605-495237ea-5cf1-11e8-849e-1220704bcf26.png)

**Changes to "Update Your Legacy Extension" box:**
- Change title to, “Help us improve the developer experience” 
- Change text to: “We’re interested in your feedback about the extension development experience! Take our short survey to  let us know what kinds of documentation, APIs, and tools would be most useful to your development work.
- Change CTA box to say “Take Survey” and link to https://qsurvey.mozilla.com/s3/Extension-Developer-survey

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64

![dev-hub-promo](https://user-images.githubusercontent.com/31961530/40541273-c821af30-6023-11e8-9991-99d4d5dededf.gif)
