### ISSUE TITLE
Convert all the old API to our new v3 REST based API

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#834]
We have multiple APIs, a v1.5, a v2, mostly used by clients like Firefox for searching.

We are creating a new API for addons.mozilla.org which will be less XML, more JSON, faster and better in every way. Maybe. Assuming that's the case, we need to deal with legacy clients that use the old API. That means providing an API to move to, a migration plan and a deprecation strategy.

**Comment by muffinresearch** [comment]
Keeping this open to figure out all the apis used in Firefox and to work out what the replacements would be.

**Comment by eviljeff** [comment]
Seems like this was done in https://bugzilla.mozilla.org/show_bug.cgi?id=1402064 - re-open if we have more work to do.
