### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\uff09' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8343]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4304510/

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\uff09' in position 0: ordinal not in range(128)
  File "olympia/addons/decorators.py", line 46, in wrapper
    return f(request, addon, *args, **kw)
  File "olympia/versions/views.py", line 59, in version_detail
    return cached(f, 'version-detail:{}:{}'.format(addon.id, version_num))

UnicodeEncodeError: 'ascii' codec can't encode character u'\uff09' in position 0: ordinal not in range(128)
```

**Comment by diox** [comment]
STR:
- Go to https://addons-dev.allizom.org/en-US/firefox/addon/ublock-origin/versions/%C3%A9%C3%A6%C3%A7%C3%A0'c

Expected Results:
- See a 404 because the parameter for the version is invalid

Actual Results:
- A 500 oops page

**Comment by AlexandraMoga** [comment]
I've tired this link and several others and I'm receiving a 404 instead of a 500:

![image](https://user-images.githubusercontent.com/31961530/40654946-60d93b7c-6348-11e8-9bbc-8e23e7172da9.png)

I'm going to mark the issue as verified fixed on AMO-dev with FF60, WIn10x64
