### ISSUE TITLE
Reject submissions for legacy add-ons that are not compatible with Firefox 

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8344]
Legacy add-ons that aren't compatible with Firefox or Firefox for Android should be rejected on upload, with the following message:

> "Add-ons for Thunderbird and SeaMonkey are now listed and maintained on [addons.thunderbird.net](https://addons.thunderbird.net). You can use the same account to update your add-ons on the new site."

The plan is to turn this on the week of June 18th, so __it should be waffled off until then__. Given the Work Week in between, this is a P2.

**Comment by diox** [comment]
We also want a script that removes all add-ons not compatible with either Firefox or Firefox for Android from the site.

**Comment by eviljeff** [comment]
That script can be a separate issue.

**Comment by diox** [comment]
Filed https://github.com/mozilla/addons-server/issues/8476

**Comment by eviljeff** [comment]
We'll also need to stop developers from being able to add those applications via devub edit version

**Comment by diox** [comment]
In addition, Thunderbird and Seamonkey compatibility info needs to be hidden everywhere. In particular I think we should hide it from the applications page.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev after enabling the `disallow-thunderbird-and-seamonkey` switch

Issues:
- with the switch enabled, submission of any new webextension  will generate the "Thunderbird and SeaMonkey" compatibility error
- when submitting a legacy extension (with install.rdf) that has compatibility set for multiple applications (i.e. Firefox, Firefox for Android, Seamonkey, Thunderbird) the "Thunderbird and SeaMonkey" compatibility error is not generated, allowing the user to proceed with the submission
- a submitted add-on that supports multiple applications will only display the Thunderbird and Seamonkey compatibility in version Information - applications - see https://addons-dev.allizom.org/en-US/developers/addon/adblock-plus-legacy-switch/versions/1534377

@diox I'm reopening this issue considering that the first point is a blocker.

**Comment by diox** [comment]
Second point is fine and expected. First and third though... That's super weird, need to fix that.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF60, Win10x64 with the `disallow-thunderbird-and-seamonkey` switch enabled:
- add-on compatible only with Thunderbird and Seamonkey will generate the appropriate error at validation [1]
- the applications section from Manage status and version page is restricted to maximum two applications - Firefox or Firefox for Android [2],[3]
- Thunderbird and Seamonkey compatibility is also hidden on the versions page and on add-on review page [4],[5]
- add-ons compatible with Firefox can be submitted as before

[1]
![image](https://user-images.githubusercontent.com/31961530/41780212-c7d35662-763c-11e8-9807-31fea11dc942.png)
[2]
![image](https://user-images.githubusercontent.com/31961530/41780312-0a352c56-763d-11e8-8ab0-33a94c968d6d.png)


[3]
![image](https://user-images.githubusercontent.com/31961530/41780257-e7102e60-763c-11e8-92c0-554c77954ca7.png)

[4] - https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus-legacy-switch-1/versions/?page=1#version-1.0.0-signed
![image](https://user-images.githubusercontent.com/31961530/41780779-5d4106f8-763e-11e8-9f84-36f8dca24845.png)

[5] - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/adblock-plus-legacy-switch-1
![image](https://user-images.githubusercontent.com/31961530/41780813-75beea88-763e-11e8-9cf2-4bd74d6ce2ba.png)
