### ISSUE TITLE
Uninformative "IOError: write error"

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8350]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/367360/

This exception is pretty useless. I wonder if it's related to https://github.com/getsentry/raven-python/issues/732#issuecomment-176854438

Is that maybe something we can add to our uwsgi config?

**Comment by EnTeQuAk** [comment]
what do you think about that @philipcristiano?

**Comment by philipcristiano** [comment]
Seems reasonable!

**Comment by EnTeQuAk** [comment]
:+1:

**Comment by vcarciu** [comment]
@EnTeQuAk  : can you please add some STRs to this issue or mark it as "qa: not needed" ?
