### ISSUE TITLE
The notifications API endpoint returns the notification named "announcements" twice

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#8377]
### Describe the problem and steps to reproduce it:

From: https://github.com/mozilla/addons-server/issues/8286#issuecomment-392537562

Retrieve the user notifications for any user.

### What happened?

The notifications API endpoint returns the notification named "announcements" twice.

### What did you expect to happen?

The notifications API endpoint returns the notification named "announcements" once, NOT twice or more.

### Anything else we should know?

This prevents the new frontend to work correctly because notification names should be unique (at least that's my assumption).

**Comment by diox** [comment]
Removing the old notification from the database makes sense, make sure that Saleforce is fully synced up and we're not going back though.

Also note that the legacy page doesn't appear to suffer from this problem, so maybe the API can be smarter here.

**Comment by EnTeQuAk** [comment]
> run a migration to clear old announcements notifications from the database (wouldn't have been in the main basket implementation commit to avoid push deploy breakage... don't think it was done later @EnTeQuAk?)

No, this hasn't been done yet. We only recently synced up with Salesforce properly so I think we'll be able to clear this up maybe next push.

**Comment by willdurand** [comment]
Reopening as `announcements` notifications are still sent twice for users who are developers.

**Comment by AlexandraMoga** [comment]
I've noticed that after the user hits 'Update profile' the `announcements` notification is shown three times:

![image](https://user-images.githubusercontent.com/31961530/41020168-7b79bb96-696a-11e8-99c8-720f48823360.png)

**Comment by willdurand** [comment]
This is more a UI bug implied by this API issue. Once the API stops sending duplicates, that won't happen.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF60, Win10x64. The 'about:addons' notification is returned only once. 

![image](https://user-images.githubusercontent.com/31961530/41098468-21311ff8-6a64-11e8-9281-24789102e410.png)
