### ISSUE TITLE
show static theme preview image in devhub's list of submissions

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8385]
LWT show an icon - that we no longer generate for static themes because it's not used in frontend - so its difficult to differentiate between your submissions.  We can use the "thumb" preview image.

**Comment by eviljeff** [comment]
These are the two alternate ways of doing this I came up with:
![theme preview alternates](https://user-images.githubusercontent.com/768592/40968385-564be79e-68ad-11e8-8c72-238a787affb1.png)

The top is devhub landing page that shows the most recent three submissions of any type; the bottom is the "my submissions" page that has tabs for extensions and themes - the latter containing both LWT and static themes (while they both exist).  Arguably they should look the same/similar though.

Alternate one is showing a cropped version of the preview, only slightly larger than a normal icon (128px wide); Alternate two changes the layout around to show the preview above the text.

**Comment by eviljeff** [comment]
@jvillalobos for UX decision on above ^

**Comment by jvillalobos** [comment]
I like the one on the top. The dev shouldn't need the whole preview to recognize their theme. @pwalm, what do you think?

**Comment by pwalm** [comment]
Yep, I agree with @jvillalobos . Top one!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10)

dev hub landing page
![dev hub landing page](https://user-images.githubusercontent.com/33448286/41294371-96f21b52-6e60-11e8-9ebf-9f9406a91834.png)

manage my submissions page
![manage my submission page](https://user-images.githubusercontent.com/33448286/41294386-9eb79e20-6e60-11e8-8a45-4d5e1721cfc1.png)
