### ISSUE TITLE
A .jpg photo with portrait orientation is not correctly displayed on User profile info card and for the add-on screenshot section

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8390]
STR:

1. Load AMO dev and go to Edit profile page
2. Upload a .jpg photo of any size that has less than 4 MB and has a portrait orientation. Observe it's display after photo is selected from folder
3. Update account and click on View Profile
4. View the image saved

Expected results:
The image is displayed in portrait orientation.

Actual results:
The image is displayed in landscape view.

Notes:
This issue is reproducible on AMO dev with FF59 (Win10).
This issue is also reproducible when uploading images for the add-on screenshots section.
This issue is not reproducible for a .png file with portrait orientation.

![jpg portrait](https://user-images.githubusercontent.com/33448286/40732847-eceea59e-643c-11e8-973e-79632b629361.gif)

**Comment by diox** [comment]
@ioanarusiczki can you attach to this issue the file you were testing with ?

**Comment by ioanarusiczki** [comment]
@diox Sorry for the delay. I attached the samples.
[only portrait2.zip](https://github.com/mozilla/addons-server/files/2187773/only.portrait2.zip)
