### ISSUE TITLE
Performing a search from the Searh tools second page returns only search tools

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#8402]
### Steps to reproduce:
1. Open the search tools landing page: https://addons.allizom.org/en-US/firefox/search-tools/
2. Scroll down the page and click the next button to navigate to the page 2
3. Perform a search using any search term
4. Observer the returned extensions

### Expected results:
Extensions of all types are returned.

### Actual results:
Only search tools are returned

### Notes/Issues
When performing a search from the search tools page 1 the issue in not reproducing, the result list contains all types of extensions.

Verified in FF 60.0.1 on Win7(x64) Issue can be reproduced on amo-dev, amo-stage and amo-prod
Screencast for this issue: 
![searchtoolssearch](https://user-images.githubusercontent.com/15685441/40780155-1cdcf816-64e0-11e8-9f6f-dd6535ae108b.gif)

**Comment by EnTeQuAk** [comment]
cc @willdurand as I think this may be a frontend-thing. From what I can tell once you click on the "next page" button you're leaving the `/search-tools/` page and enter the regular search. I don't think that should happen.

**Comment by willdurand** [comment]
I guess it is a frontend issue, investigating...

**Comment by willdurand** [comment]
> From what I can tell once you click on the "next page" button you're leaving the /search-tools/ page and enter the regular search.

So, I believe that is intended (but I was not there when this was decided). My understanding is that `/search-tools/` is a landing page and we have to go to the search page for more results.

See also: https://github.com/mozilla/addons-frontend/issues/4496

**Comment by EnTeQuAk** [comment]
Interesting, that's a bit confusing but then "working as expected" I think. The results do what the user expects though, mostly, so this shouldn't be much of a problem.

Thanks for investigating! Closing.

**Comment by willdurand** [comment]
> The request that is made when performing a search from the landing page looks like this: addons.allizom.org/api/v3/addons/search/?app=firefox&appversion=60.0&platform=windows&q=fire&lang=en-US&wrap_outgoing_links=true
> 
> And when searching from page 2 looks like this: addons.allizom.org/api/v3/addons/search/?app=firefox&appversion=60.0&platform=windows&q=fire&sort=relevance&type=search&lang=en-US&wrap_outgoing_links=true
> 
> In the second request we have "type=search". Is that ok? If yes, why we do not do that in the landing page?

See the filters on the left, you will see that the "add-on type" is "search tools" when you navigate to page 2. That's why the search behaves differently.

**Comment by madalincm** [comment]
When you access https://addons.allizom.org/en-US/firefox/search-tools/ the filter "add-on type"  is set to Search Tool.
![landingpagefilter](https://user-images.githubusercontent.com/15685441/40789078-3b8519dc-64fa-11e8-9648-e8de28545735.png)
 If you perform a search in there the request that is fired is this one: 
https://addons.allizom.org/api/v3/addons/search/?app=firefox&appversion=60.0&platform=windows&q=fire&lang=en-US&wrap_outgoing_links=true 
which does not contain "type=search"  - extensions of all type are returned.

------

When you navigate to the second page https://addons.allizom.org/en-US/firefox/search/?page=2&sort=relevance&type=search the filter "add-on type"  is set to Search Tool. If you perform a search in there the request that is fired is this one: 
https://addons.allizom.org/api/v3/addons/search/?app=firefox&appversion=60.0&platform=windows&q=fire&sort=relevance&type=search&lang=en-US&wrap_outgoing_links=true
which does contain "type=search" - only search tools are returned.

**Comment by willdurand** [comment]
ah right, we should probably not display the filters on `/search-tools/`.

**Comment by madalincm** [comment]
Reopening based on comment https://github.com/mozilla/addons-server/issues/8402#issuecomment-393556441

**Comment by willdurand** [comment]
@madalincm could you reopen this issue on addons-frontend instead? thanks!

**Comment by madalincm** [comment]
I have logged https://github.com/mozilla/addons-frontend/issues/5182
Closing this issue.
Thanks @willdurand
