### ISSUE TITLE
Static theme migration preview image migration broken after celery pickle changes

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8405]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4366764/

irc discussion:
```
19:35 <eviljeff> I think the celery pickle changes may have broken something with the static theme migration script.
19:35 (Or I did).  Because https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4366764/ 
19:35 - my first thought was it's a task triggered from inside a task, in an @atomic block.
19:35 So... does the object actually exist (to the preview generating task) at that point?
19:36 <mat> it probably doesn't 
19:37 that's an interesting problem
19:38 where is the code triggering the code to generate_static_theme_preview task again? 
19:38 <eviljeff> in Version.from_upload
19:39 which is called from the addons.tasks.add_static_theme_from_lwt method 
19:40 fix might be just to stick a delay on the task of a few seconds so the atomic block has finished by that point
19:40 although we don't usually want that inside Version.from_upload :/
19:40 mmm
19:40 <mat> yeah
19:40 that'd be bad for the general use case
19:40 and we definitely want to keep the atomic in the migration task
19:41 s/task/function, technically
19:41 so
19:41 <eviljeff> I noted from the sentry traceback the celery task ran 4 times for 2 addons.
19:41 <mat> maybe we can play with savepoints somehow
19:41 <eviljeff> I don't know what was up with that either.
19:41 <mat> OR
19:42 avoid calling generate_static_theme_preview from Version.from_upload(), specifically when migrating
19:42 and call it later, again specifically when migrating
19:42 <eviljeff> Another idea: can we have that celery task retry in 5 seconds if it can't find the pk first time?
19:43 <mat> I guess it wouldn't be that bad yeah
```

**Comment by diox** [comment]
Another option is to benefit from the post-request-task stuff: force the tasks to all be delayed until after a certain point, in which case the point is the transaction commit. We are seeing this issue because we're outside the request-response cycle, so the post-request-task is not enabled. But maybe we can enable it and fire the signals it listens to...

**Comment by eviljeff** [comment]
Looks like it listens to the standard django.core.signals `request_finished` and `request_started` which i'm a little wary about firing because what else is listening for them.  We want to call https://github.com/mozilla/django-post-request-task/blob/master/post_request_task/task.py#L23 directly really.

**Comment by diox** [comment]
Yeah calling `_start_queuing_tasks()` and `_send_tasks_and_stop_queuing()` should work.

**Comment by AlexandraMoga** [comment]
@eviljeff so you're still waiting for https://github.com/mozilla/addons-server/issues/8412 before migrating a few more themes? #8558 it is also pending for verification.

**Comment by eviljeff** [comment]
It's a bit of a hassle to have the command run, so yeah, I'll wait for everything.  #8412 should be ready for this week's tag (though can and should be verified separately because it covers uploads/wizard submissions too, and not just the migration).

I was hoping to get #8267 done at the same time but it's less straightforward.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with the following migrated themes:

https://addons-dev.allizom.org/en-US/firefox/addon/lilac-prediction/?src=search
https://addons-dev.allizom.org/en-US/firefox/addon/litefox/?src=search
https://addons-dev.allizom.org/en-US/firefox/addon/an-autumn-reverie/?src=search

Previews are being generated now. 

Here is an example:
![image](https://user-images.githubusercontent.com/31961530/42031886-7a2b533a-7ae0-11e8-95d6-e3575913300a.png)
