### ISSUE TITLE
Replace add-on admin with django admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8410]
The current add-on admin is a [custom view](https://github.com/mozilla/addons-server/blob/db3cbaa2e24f132ac5966469402ff4d127c725f4/src/olympia/zadmin/views.py#L354) that re-uses some styles of the django admin, and provides minimal functionality: it lists the add-on name, slug and status, as well as all files attached to a version attached to the add-on. It lets you modify the status of either the add-on or the files.

We should make the django admin provide the same functionality in the django admin change view for add-ons. That would ease integration with other tools based on the django admin like the user admin being built in #7268. It would also allow us to use the same permission checks we're implementing in the rest of the django admin code.

**Comment by diox** [comment]
In particular, that means `AddonAdmin` needs to:
- Show all files, with creation date, version, channel, id, platform, status and hash through some inline admin
- Allow status changes, both for files and the add-on
- Make sure status changes for both addon and files are logged like it's done in add-on manage zadmin

**Comment by wagnerand** [comment]
It would be nice if that page had a safety net that catches invalid status combinations. This has been a problem in the past.

**Comment by AlexandraMoga** [comment]
I've verified the new Files component from add-on admin and I have the following results:

- all add-on files, with creation date, version, channel, id, platform, status and hash. File statuses can be changed as shown in the below screenshot. Note that for deleted versions file status changes are no longer possible:
![image](https://user-images.githubusercontent.com/31961530/72255658-f6212c80-360f-11ea-9d68-8926dbd8463b.png)
- the list is paginated if there are > 30 versions available

@eviljeff I also have some questions/observations:
- regarding activity logs for add-on and file status changes, if I'm looking in the [admin activity log](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/?created__year=2020) I can see there are entries for add-on status changes but not for files status changes. Am I looking in the wrong place?
- the pagination could be improved by adding an inline display, which, I think, will also rid us of the unnecessary numbering. I can open a follow up for this. 
This is the current pagination:
![image](https://user-images.githubusercontent.com/31961530/72256414-d0952280-3611-11ea-870b-bfddbaf3d476.png)
- in the old manage add-on page, version numbers were linked to the add-on review page and file ID's were pointed to the corresponding file in the file viewer.
![image](https://user-images.githubusercontent.com/31961530/72256662-616bfe00-3612-11ea-8c4a-3722728c4f74.png)
In the new tool, version numbers and file ID's are not linked to any page. We could link file IDs to the [Files](https://addons-internal.dev.mozaws.net/admin/models/files/file/) admin tool (considering that the old file viewer will be closed at some point) and the versions could still be linked to the add-on review page, unless @wagnerand has a more useful set-up in mind.

**Comment by eviljeff** [comment]
> regarding activity logs for add-on and file status changes, if I'm looking in the admin activity log I can see there are entries for add-on status changes but not for files status changes. Am I looking in the wrong place?

The old tool didn't create ActivityLog entries for file status changes (that I could see) so I didn't implement it for this either.  There's some logging via Logger (i.e. ends up in the raw server logs & stackdriver), that's all.

> the pagination could be improved by adding an inline display, which, I think, will also rid us of the unnecessary numbering. I can open a follow up for this.

Hmm, yes, that's a css bug - it's supposed to be styled as a single line of links.

**Comment by eviljeff** [comment]
fwiw, #13199 asks for a link to the review page.

**Comment by AlexandraMoga** [comment]
If #13199 is implemented, it will be indeed redundant to also link versions to the same review page. We still need to decide where we should link file IDs. I will file a follow up issue to discuss this further.
