### ISSUE TITLE
Fix potential performance regressions for cache-machine removal

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8413]
After https://github.com/mozilla/addons-server/issues/7744 there are a few views that show signs of issuing too much queries and behaving differently depending on how much data is shown.

`/<lang>/thunderbird/search-tools/format:rss` is really slow with 1.7s. This could have been cache-warming but seems to be related to Thunderbird directly.

`/de/firefox/` - our Startpage is much slower than it should be. Let's see what can be optimized there, if there's anything depending on whether or not this is frontend or backend related.

`/de/firefox/collections/mozilla/password-managers/` - user collections show signs of behaving and issuing different amount of queries depending on data.

`/de/firefox/user/daveg/` - the user profile page does that too.

`/de/thunderbird/addon/lightning/reviews/` - the reviews page also behaves differently depending on the amount of data.

`/en-US/seamonkey/search/?platform=linux&q=Privacy` - search for legacy apps seems much slower than for Firefox. Needs some investigation.

More information:

Test run on NewRelic with cache-machine disabled: https://rpm.newrelic.com/accounts/1402187/applications/76231391/transactions/table?type=app&tw[start]=1527844990&tw[end]=1527862414#sort=8%2C1

Test results from locust with a total of 23924 requests: https://gist.github.com/EnTeQuAk/f9bc6ee6e3834238d8931c3a132a5c8e (they're less uniquified than the previous tests)

Going to test all that locally with django-debug-toolbar and see what can be optimized.

**Comment by EnTeQuAk** [comment]
This got already fixed and merged in an attempt to split these as part of the fragment cache removal. There might be more, let's open specific issues for them.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  please let me know if there is anything to test around this issue, or otherwise mark it with 'qa:not needed'
Thank you
