### ISSUE TITLE
Lost List of FF add-ons for mobile

### ISSUE THREAD

**Issue by RiffRaffMama** [mozilla/addons-server#8420]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know? 
Came from here: https://support.mozilla.org/en-US/questions/928073
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This issue tracker is for the development of addons.mozilla.org. Please use [Discourse](https://discourse.mozilla.org/) for support.
