### ISSUE TITLE
File link on review page should trigger download, not install

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8426]
### Describe the problem and steps to reproduce it:
Reviewers should not install add-ons in the profile they're reviewing in for security reasons. Therefore, offering an install when clicking on the file link is not helpful. The link should trigger a download instead.

1. Open a review page.
2. Click on a file link.

### What happened?
Firefox trying to install the add-on.

### What did you expect to happen?
Firefox downloading the add-on.

### Anything else we should know?

Note that using the `download` attribute for the anchor won't work because the reviewer tools and the file are on different hostnames and the `download` attribute only works with same-origin-policy.

**Comment by EnTeQuAk** [comment]
I'm marking this as p4 since it's easy enough to simply do a right-click and "save as". It's something that'll be nice to fix though.

**Comment by wagnerand** [comment]
Reviewers have been using this workaround for years now, hundreds of times each week.

With the introduction of post-review, the risk of accidentally installing a harmful add-on has increased significantly. Therefore, I'd like to get this resolved rather sooner than later.

I'm happy to give this a try myself if someone can point me to an approach we could take here.

**Comment by EnTeQuAk** [comment]
I put this into the Q3 reviewer tools improvement project.

**Comment by wagnerand** [comment]
Thanks!

**Comment by diox** [comment]
> Note that using the `download` attribute for the anchor won't work because the reviewer tools and the file are on different hostnames and the `download` attribute only works with same-origin-policy.

Need to double-check, but I think we already support the download view through the reviewer tools domain, so we could force it to be on the same domain and use the `download` attribute.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

Clicking on 'All Platforms' link on an add-on review page is now triggering an actual file download: 

![2020-10-12_15-55-41](https://user-images.githubusercontent.com/31961530/95749100-bb821880-0ca3-11eb-8de3-f1a1df67a9e1.gif)
