### ISSUE TITLE
June 2018 Disco Pane content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#8431]
For the **21 June** push, please adjust Disco Pane programming to reflect as the following...

**Bokeh Beta** by [Joe.lv](https://addons.mozilla.org/firefox/addon/bokeh-beta/)

**Stop sneaky trackers** with [Privacy Badger by EFF](https://addons.mozilla.org/firefox/addon/privacy-badger17/)
Block invisible trackers and spying ads that follow you around the web. 

**Customize new tab pages** with [Tabliss by tabliss.io](https://addons.mozilla.org/firefox/addon/tabliss/)
Enjoy a beautiful new page with customizable backgrounds, local weather info, and more. 

**Foggy Dawn** by [twisfowt](https://addons.mozilla.org/firefox/addon/foggydawn/)

**Translate easily** with [To Google Translate by Juan Escobar](https://addons.mozilla.org/firefox/addon/to-google-translate/)
Highlight any text, right-click, and translate instantly. 

**Search Images** with [Image Search Options by Xamayon](https://addons.mozilla.org/firefox/addon/image-search-options/)
Perform reverse image searches from an array of engines. 

**Sakura Blossoms & Birds** by [MaDonna](https://addons.mozilla.org/firefox/addon/sakura-blossoms-birds/)

@muffinresearch @diox @EnTeQuAk

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev. Full validation will be mad in prod.

**Comment by AlexandraMoga** [comment]
Verified fixed in prod
