### ISSUE TITLE
Update add-on review weighting

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8436]
@kewisch and I reviewed the current review weighting for add-ons and identified a few factors that we'd like to have changed:

**Abuse reports**
From: 1 abuse report in the past year: 10 points
To: 3 abuse reports per 6 weeks: 10 points

**eval, document.write**
From: 20
To: 50

**'script' tag with a remote URL**
From: 40
To: 100

**Unsafe DOM: innerHTML**
From: 20
To: base of 50, then 10 per instance

**Custom CSP**
From: 30
To: 90

**Native messaging**
From: 20
To: 100

**Libraries and other unreadable code**
From: 10
To: base of 100, then 10 per instance

After the changes are live, we need to run the re-weighting command.

**Comment by wagnerand** [comment]
Setting P2 as we'd like to land this before the end of the quarter.

**Comment by diox** [comment]
> To: 3 abuse reports per 6 weeks: 10 points

Does that mean we should go back further in the past than just 6 weeks? Use the whole history?

**Comment by wagnerand** [comment]
Could we go back 30 weeks? (which means a max of 50 points)

**Comment by diox** [comment]
We can try, yes. Right now I have no idea what the query will look like :)

**Comment by wagnerand** [comment]
@diox To make it easier, let's change the abuse reports rule to:

Each abuse report in the past 6 weeks: 15 points

**Comment by AlexandraMoga** [comment]
I have tested the new weight allocation and here are the results:

**Confirmed:**
- Add-on with `Custom CSP` => weight = 90 ([1st version example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/csp-warning-wup))
- Add-on with `'script' tag with a remote URL` => weight = 100 ([1st version example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/weights-updates-remote-script))
- Add-on with `Native messaging` => weight = 100 ([1st version example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/weights-updates-remote-script))
* Abuse reports past 6 weeks:
  * for user => 15 points per abuse - see [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/word-violation)
  * combined user and add-on => 15 points per user/add-on abuse reports- see [example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/native-messaging-wup-2)


**Needs Info:**
_The examples below refer to the first version of the add-on, when the user had **NO abuse reports**_
_Point 2, 3 and 4 could be related to https://github.com/mozilla/addons-linter/issues/1645 but the extra weight is amplified now_

1. For `innerHTML` and `Libraries and other unreadable code` - the higher weight (50 for `innerHTML`, 100 for `libraries`) is applied to the _first flag raised_, while the additional flags will receive 10 weight each? Examples: [innerHTML](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/innerhtml-wup), [Libraries and other unreadable code](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/libs-unread-code-wup)
2. For `eval` - the add-on submitted received 150 weight - =>100 weight unaccounted - see [eval example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/eval-wup)
3. For `document.write` - the add-on submitted received 150 weight => 100 weight unaccounted - see [doc.write example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/docwrite-wup)
4. For combined `eval` and  `document.write` - the add-on submitted received 162 weight (50 from flags+2 from size of code) => 110 weight unaccounted.
5. For `'script' tag with a remote URL` - there will always be 100 weight applied, regardless of the number of "Remote scripts" flags raised during validation? ([example](https://addons-dev.allizom.org/en-US/developers/addon/remote-scriptx2/file/255103/validation))

@diox , please have a look at the points raised above

**Comment by diox** [comment]
1. Yes.
2. `contentscript.js` was detected as minified in that add-on, adding an extra 100. Also note that this add-on author now has abuse reports (that wasn't the case initially).
3. Same thing as 2.
4. Same thing as 2. and 3., except there are 2 "minified" files (`contentscript-doc.js` and `contentscript.js`).
5. Yes.

I know that those files detected as minified are not actually minified but rather just one-line files, but that's not a new issue. That's https://github.com/mozilla/addons-linter/issues/1645

**Comment by AlexandraMoga** [comment]
Regarding 2, 3 and 4 I've also hinted in my comments that https://github.com/mozilla/addons-linter/issues/1645 might be the culprit. 

Since there haven't been any other problems spotted, I'm going to mark this issue as verified fixed on AMO -dev with FF60, Win10x64

**Comment by erosman** [comment]
@wagnerand  @diox   Noteworthy is that unless all add-ons that are currently in the queues are re-evaluated and re-weighted, 1000s of add-ons that were previously weighted according to the previous rules and should be humanly reviewed, will fall under the new ignore threshold of 90.
