### ISSUE TITLE
Update legacy profile edit page to tell users how to update their email address

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8437]
To copy from [the addons-frontend comment](https://github.com/mozilla/addons-frontend/issues/3144#issuecomment-377195562): 
> The message about Firefox Accounts and changing email addresses should say instead that they can change their email address via Firefox Accounts. https://support.mozilla.org/en-US/kb/change-primary-email-address-firefox-accounts seems like the relevant article about it.

#4925 was the first (of many!) implementation issues about this.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/41228520-53f72566-6d81-11e8-8877-c780d0ebd91d.png)
