### ISSUE TITLE
Handle translated fields in django admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8450]
Translated fields currently do not show up in the django admin - for instance if you look at the django admin page for an add-on, it should show the name, but doesn't.

Even if it did show up, we need to display all translations in the change pages instead of just the translation in the user's current language. We've got some form fields for this, but they need to be integrated into the admin.

**Comment by AlexandraMoga** [comment]
I've verified the new admin layout for Addon details page on AMO -dev and here are my observations:
- localized fields are present for sections that support localization i.e. name, summary, description, homepage, privacy policy etc
- the fields can be edited by admins and the changes are reflected in AMO add-on details page 

localized fields
![image](https://user-images.githubusercontent.com/31961530/41284274-80c46e76-6e41-11e8-9e22-eadafa226c4f.png)



@diox 
1. I have compared the number of translated fields (see name, summary) from add-on admin page with the actual localization files available in the add-on package, Admin tools shows 49 localisations while the add-on package has 85 files. Example used: https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/495691/?_changelist_filters=type__exact%3D1%26status__exact%3D4
2. There are some minor styling issues that caught my attention: the locale name and its corresponding fields are split on different rows [pic.1]; if data is deleted from a specific field, after changes are saved, that field is still displayed as a blank form [pic. 2]. Maybe such fields could be hidden when no data is available.
I could file a separate issue for the styling part if you prefer. 

**[pic.1]**
![image](https://user-images.githubusercontent.com/31961530/41284699-af9d3ea2-6e42-11e8-99cb-966f3b1ae154.png)

**[pic.2]**
![image](https://user-images.githubusercontent.com/31961530/41284772-f47c6ade-6e42-11e8-9564-ae058fc26a4f.png)

**Comment by diox** [comment]
1. I don't know how important that is, but it doesn't look like a problem with my changes, but rather a potential problem at import time.
2. Yeah, deletion of translated fields doesn't really delete anything. I prefer keeping the blank fields to help debug issues around that. You can file a new issue about the styling.

**Comment by AlexandraMoga** [comment]
@diox 
regarding 1. I've looked at the api response for the same add-on and it is indeed showing only 49 locales. So, this needs more investigation to see why haven't all the localization files been imported. 

For the styling part, I've filed #8506 

Marking this issue as verified fixed on AMO-dev with FF60, Win10x64
