### ISSUE TITLE
Drop static pages from legacy frontend that haven't been (& won't be) migrated to new frontend

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8453]
addons-server has a number of pages that show some static content about the site.  Some have already been rewritten on addons-frontend; some are non-AMO branded landing pages (e.g. shield studies); the rest are obsolete and won't be migrated.  We could drop any unused pages now, or decide on appropriate redirects.

From: https://github.com/mozilla/addons-server/blob/master/src/olympia/pages/urls.py

## Migrated already
https://addons.mozilla.org/about
https://addons.mozilla.org/review_guide

## To delete?
https://addons.mozilla.org/credits
https://addons.mozilla.org/faq
https://addons.mozilla.org/compatibility_firstrun
https://addons.mozilla.org/developer_faq
https://addons.mozilla.org/sunbird

## infrastructure, nothing to see here
https://addons.mozilla.org/google1f3e37b7351799a5.html
https://addons.mozilla.org/google231a41e803e464e9.html

## Non-AMO-Branded (doesn't use our templates and jinja helpers so probably okay to stay)
https://addons.mozilla.org/shield-study-2
https://addons.mozilla.org/shield_study_3  (all the way to  `_16`)
https://addons.mozilla.org/pioneer

## Redirects
https://addons.mozilla.org/pages/compatibility_firstrun (redirect to https://addons.mozilla.org/compatibility_firstrun)
https://addons.mozilla.org/pages/developer_faq (redirect to https://addons.mozilla.org/developer_faq)
https://addons.mozilla.org/pages/review_guide (redirect to https://addons.mozilla.org/review_guide)
https://addons.mozilla.org/pages/developer_agreement (redirect to https://addons.mozilla.org/developers/docs/developer_agreement then https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Agreement)
https://addons.mozilla.org/pages/validation (redirects to https://wiki.mozilla.org/Add-ons/Reviewers/Guide/AddonReviews#Step_2:_Automatic_validation (broken link))

**Comment by jvillalobos** [comment]
I can confirm the deletion list:

> https://addons.mozilla.org/credits
> https://addons.mozilla.org/faq
> https://addons.mozilla.org/compatibility_firstrun
> https://addons.mozilla.org/developer_faq
> https://addons.mozilla.org/sunbird

Also filed https://github.com/mozilla/addons-server/issues/8455 since I just found out we link to the old FAQ from devhub.

**Comment by AlexandraMoga** [comment]
After checking the above links on -dev:
- the links from the Deleted list are now returning a 404
- the first two links from the Redirect group are also on the Deleted list => they return a 404; the rest of the links are redirecting to the indicated landing pages
- the already migrated links are unchanged (open in their corresponding new frontend pages)
- the FAQ links was also removed from the footer menu

![image](https://user-images.githubusercontent.com/31961530/41222099-b88f7c84-6d6e-11e8-85d1-a13b6caed599.png)
