### ISSUE TITLE
Remove link to FAQ from Developer Hub landing page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8455]
The [Developer Hub](https://addons.mozilla.org/developers/) landing page has links to various useful resources for developers. There's a link in the Support column pointing to an [FAQ](https://addons.mozilla.org/faq) that is in the old front-end and won't be migrated to the new one. It should be removed.

**Comment by gabru-md** [comment]
Hi, I have never contributed to Mozilla. I would like to solve this issue and contribute to the community.
@jvillalobos can I be assigned to this issue? :smiley:

**Comment by jvillalobos** [comment]
@gabru-md sure, go for it. I think [this is the file](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/new-landing/components/footer.html) you'll want to change.

Mentor: @eviljeff  :D

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO-dev with FF60, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/41152544-95821e58-6b1c-11e8-8fa6-51fe33bae8fe.png)
