### ISSUE TITLE
Deploy static files using a hash approach

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8456]
AMO predates the introduction of staticfiles in django and as such addons-server handling of static files has always been a bit... clunky.

A while ago addons-server was modified to properly separate media and static files, and make use of `collectstatic`. However, we're still not using staticfiles to the fullest and instead our cachebusting strategy entirely depends on `jingo_minify` on addons-server.

This is a problem because it means static files included from templates not using jingo_minify won't get cachebusted properly. It's visible right now in the admin, with pages like this (on dev):
```html
<link rel="stylesheet" type="text/css" href="https://addons-dev-cdn.allizom.org/static/admin/css/base.css" />  
<link rel="stylesheet" type="text/css" href="https://addons-dev-cdn.allizom.org/static/admin/css/changelists.css" />
(...)
<script type="text/javascript" src="https://addons-dev-cdn.allizom.org/static/admin/js/core.js"></script>
<script type="text/javascript" src="https://addons-dev-cdn.allizom.org/static/admin/js/jquery.min.js"></script>
<script type="text/javascript" src="https://addons-dev-cdn.allizom.org/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="https://addons-dev-cdn.allizom.org/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="https://addons-dev-cdn.allizom.org/static/admin/js/actions.min.js"></script>
```

This will be a problem for each django upgrade. It will also be a problem when we want to add custom javascript to those admin pages.

The solution is to use a staticfiles storage class that changes the filename with a hash, like [`ManifestStaticFilesStorage`](https://docs.djangoproject.com/en/2.0/ref/contrib/staticfiles/#manifeststaticfilesstorage). Few things to be paying attention to:
- Need to make sure every reference to every static file is done through `{{ static() }}` in jinja or `{% static %}` in django templates.
- Need to fix our `static()` jinja helper to call django's https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#std:templatetag-static instead of doing its own thing.
- ~~Need to make sure compatibility is ensured for any static files that might be referenced outside of AMO... if necessary. That may not be the case, but maybe some sites hotlink some logo or something ?~~ `collectstatic` also copies the original version so that's not needed.
- Need to make sure this doesn't cause issues with `jingo_minify`.

**Comment by AlexandraMoga** [comment]
I can see the new file formats in devhub, reviewer tools and admin tools. I didn't see any rendering issues either. 

I'm marking this issue as verified fixed on stage.
