### ISSUE TITLE
Remove template fragment caching

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8460]
As part of #7743, splitted off to make review easier.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed'?
Thank you

**Comment by EnTeQuAk** [comment]
This is hard to test explicitly but if you notice any of the legacy pages become very unresponsive or super slow, that could be related to this change. We do have monitoring on this though so I'm marking this as qa not needed for now. Just be aware that this changes performance characteristics of our legacy pages.
