### ISSUE TITLE
Add-ons for all platforms listed under "Other users with this extension also installed"

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#8486]
### Describe the problem and steps to reproduce it:
Visited https://addons.mozilla.org/en-US/firefox/addon/trackmenot/ with the binary release of Firefox ESR 60.0.2 (64-bit) for GNU/Linux.

### What happened?
The "Other users with this extension also installed" section lists the add-on ([Steganos Privacy Suite](https://addons.mozilla.org/en-US/firefox/addon/steganos-privacy-suite/)) that are available only for the Windows platform.

### What did you expect to happen?
Add-ons for the Windows platform should not be listed when I'm using Firefox in GNU/Linux.

### Anything else we should know?
![screenshot at 2018-06-09 16 41 33](https://user-images.githubusercontent.com/6416073/41194234-89575aec-6c18-11e8-8d5c-526a0f82353b.png)

**Comment by diox** [comment]
Steganos Privacy Suite is not a legacy add-on. It is, however, a windows-only add-on for some reason.

**Comment by davidhedlund** [comment]
@diox Sorry, you are right.

**Comment by davidhedlund** [comment]
@diox Should add-ons not available for my OS be displayed for me?

**Comment by diox** [comment]
Technically an API issue, we should filter them somehow, but I don't see how. We'd need telemetry to be able to do that, no?

**Comment by eviljeff** [comment]
We _could_ filter them, but we've previously been very strict about only returning 4 results or nothing (the fallback instead).  Ideally we'd pass on the platform parameter to TADAR/TAARLite  so we'd only get back compatible results (I don't know if that's supported - we only send the add-on guid currently)

**Comment by diox** [comment]
I think this will probably wait until platforms are eradicated in https://github.com/mozilla/addons-server/issues/8752

**Comment by crankycoder** [comment]
@diox Does #8752 really mean that all webextensions will run on mobile and desktop?  That seems unlikely.  I'd like to have the platform parameter passed into TADAR (formerly TAAR-lite) so that we can run the add-on filtering within the TADAR server. 

cc/ @muffinresearch

**Comment by diox** [comment]
@crankycoder platforms will go away but *applications* won't. See https://github.com/mozilla/addons-server/issues/8752#issuecomment-402680467

The fact that there is an android platform is legacy cruft, the thing that matters is app compatibility, not platform.
