### ISSUE TITLE
Installing extensions on old pages using the MMB gives a permission error

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-server#8491]
STR:

1. Load AMO and click on the "Wiew classic desktop site" button.
2. Hover over an extension and using the middle mouse button click on the "+ Add to Firefox" button.

Expected result:
A new page is opened with the add extension popup.

Actual result:
A new page is opened with the warning "Firefox prevented this site from asking you to install software on your computer." is displayed.

Notes:
This issue is reproducible on all AMO servers with FF62(Win10 64Bit).
This issue is not reproducible on the new amo pages.
![old pages mmb](https://user-images.githubusercontent.com/28138132/41237717-beb85c88-6d83-11e8-9ae1-8328ce552a28.gif)

**Comment by diox** [comment]
We're not going to fix legacy frontend issues like these.
