### ISSUE TITLE
After submitting a static theme "Go to my submissions" should redirect to "My Themes" tab

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8497]
STR:
1. Load AMO dev and submit a static theme
2. Click on Go to my Submissions button after the submission is complete
3. Observe the tab displayed in Manage my submissions page

Expected result:
My Themes tab is opened with sorting option "Created" displaying the last submitted theme.

Actual result:
My Add-ons tab is displayed.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).

![manage my submissions](https://user-images.githubusercontent.com/33448286/41297140-2f18ad64-6e67-11e8-8fe2-4c3638f6cab0.gif)

**Comment by kvaluruk** [comment]
@eviljeff Can I work on this?

**Comment by eviljeff** [comment]
@kvaluruk sure, go ahead. But note a) it's not been marked as a good first bug (yet*?) b) you'll need to write some tests c) because of (b) you'll probably need to install addons-server locally to develop the fix. *(and because of (b) and (c) it might not be marked as a good first bug)

**Comment by kvaluruk** [comment]
@eviljeff sorry for that quick fix PR, I'd still love to work on this issue! I've never worked with testing before though. How can I get started?
If you think it'll be a bit complex, I'll look into the other issues. Thanks!

**Comment by eviljeff** [comment]
It's up to you.  It's perhaps not a super beginner issue, but I think you can just see what tests fail on the Travis test run and then change those lines.  Once you've made the template change I requested if you can't work out how to change the tests I'll point the lines out.

**Comment by caitmuenster** [comment]
Hey @kvaluruk! Since you are close to closing this bug out, we are marking you as assigned to this bug. :) 

@eviljeff is here to help with questions about the tests to help you get this over the finish line!

**Comment by kvaluruk** [comment]
@eviljeff @caitmuenster Thanks for the motivation and guidance! This was my first ever OS contribution, looking forward to getting involved even more :heart: :tada:

**Comment by caitmuenster** [comment]
Nicely done, @kvaluruk! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition) and your mozillians.org profile has been vouched. 

Welcome onboard! We look forward to seeing you around the project. 🎉

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10)
![go to themes tab](https://user-images.githubusercontent.com/33448286/44578242-cd3e9400-a79b-11e8-9813-f1f6960c86ab.gif)
