### ISSUE TITLE
The locale name and its corresponding field are split on different rows on Addon Admin page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8506]
Follow up for #8450 

STR:
1. Log in to AMO Admin tools
2. Go to Django Admin pages - Addons
3. Open the details of and add-on with translated fields ( see https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/495691/?_changelist_filters=type__exact%3D1%26status__exact%3D4)
4. Observe the layout of the translated fields (name, summary, description etc)

Actual result:
The locale name and its corresponding field are split on different rows

Expected result:
The locale name and its corresponding field are displayed on the same row to make them easier to track

Notes:
- reproduced on AMO-dev with FF60, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/41343451-4ffbab4e-6f07-11e8-8a09-dc972a3a6926.png)

**Comment by EnTeQuAk** [comment]
@diox you worked on this, is it okay to assign this to you? I would understand if you have enough of the admin for now though :rofl:

**Comment by diox** [comment]
It's really just css, and a minor issue IMHO.

**Comment by AlexandraMoga** [comment]
It seems that the admin doesn't display the locale corresponding to each field. Not sure if this was intended or a regression. 
Having the locale name present might prove helpful.

![image](https://user-images.githubusercontent.com/31961530/64600841-7dd9fe80-d3c4-11e9-9b1d-ac413613e16e.png)

**Comment by diox** [comment]
The regression was fixed in https://github.com/mozilla/addons-server/issues/13587 - the alignement issues are still there, though we don't particularly care much.
