### ISSUE TITLE
Add-on submission, slug already in use

### ISSUE THREAD

**Issue by AaronLaBrie** [mozilla/addons-server#8507]
### Describe the problem and steps to reproduce it:

Trying to submit an add-on for the first time, there's a slug conflict with an existing add-on. Changing the slug and submitting the form just resets to the (conflicting) slug and the `This slug is already in use. Please choose another.` message.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![screen shot 2018-06-13 at 12 48 46 pm](https://user-images.githubusercontent.com/5460483/41368644-27ee1dfc-6f08-11e8-9a3f-16e6d0836b4e.png)

**Comment by jvillalobos** [comment]
There was an old entry with the same name and slug. Can you please try again?

**Comment by AaronLaBrie** [comment]
Works now, thank you!
