### ISSUE TITLE
Increase cache timeouts for theme updates

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8510]
We are currently exposing the icons of our lightweight themes (personas) in `services/theme_update.py` both as a base64 data URL and absolute URL. That's costly.

The update data is cached for 3600 seconds (one hour). We should increase this to at least 1 day.

Also, let's investigate if we even need that data in the first place.

**Comment by AlexandraMoga** [comment]
@diox I've made a quick check around lightweight themes to make sure that everything works as before.
Is there anything more specific that could be verified?

**Comment by diox** [comment]
@AlexandraMoga check that *updates* to lightweight themes still work... with a catch: only one update per theme per day is guaranteed to work, clients might need to wait for 24 hours until the next update is served if more than one is made to the theme.

**Comment by AlexandraMoga** [comment]
@diox I haven't reached a limit for the number of updates allowed:
- submitted 4 updates on -dev - https://reviewers.addons-dev.allizom.org/en-US/reviewers/themes/queue/single/theme-updates-test
- submitted 3 updates on stage - https://reviewers.addons.allizom.org/en-US/reviewers/themes/queue/single/theme-updates-test

Is this a relevant result?

**Comment by AlexandraMoga** [comment]
In that case, since there were no other issues discovered, I'm going to mark this as verified fixed on AMO stage with FF60, Win10x64
