### ISSUE TITLE
Implement custom resolve that resolves v3/v4 api-urls based on request

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8517]
Our future testing-plan for v3/v4 APIs is that we intend to simply run V3 tests twice and test V4 with that, with custom overwrites if needed for V4 specific changes.

We will need to implement a custom resolve-helper that uses drf_resolve and force a namespace again for v3/v4 related urls.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed'?
Thanks
