### ISSUE TITLE
Static Theme Wizard - The "Name" field from the second page of the submission should be non editable

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8520]
STR:
1. Load AMO dev and submit a static theme using the theme wizard
2. Observe that the form has a Theme Name field on both pages during submission

Expected result:
Theme name* can only be edited on the first page.

Actual result:
The name of the theme can be edited on both pages during submission.

Notes:
The second name field should not be editable because when the static theme is installed the name of the theme will be the one edited on the first page of the submission. This issue is reproducible on AMO dev with FF60(Win10).

The name of the image was 4.14MB and I left it like that in the Theme name* field than I edited on the second page the Name with "Patruvirgulapaisprezece". The listed page of the theme will display it as "Patruvirgulapaisprezece" but when the static theme is installed, the name is 4.14MB (as the name field in the manifest displays it).
![static theme s second name field](https://user-images.githubusercontent.com/33448286/41418955-93659438-6ff9-11e8-9177-bbbec9ac165e.png)

**Comment by eviljeff** [comment]
@jvillalobos What are your thoughts on this? It's really the same underlying issue as #4809 - that we only use the name from the manifest on first upload; then allow the dev to change it for AMO in the detail step and don't even attempt to keep AMO's addon name and the xpi addon name in sync.

With the static theme wizard it's potentially exposing this more though, as there will be two name fields on two consecutive screens for new addons.  Plus using the wizard for a new version will present a name field that will only be used for the xpi.

There are some possible changes around the edges but how do you feel about a minimal implementation of manifest-single-source-of-truth but only for static theme names?

**Comment by jvillalobos** [comment]
> minimal implementation of manifest-single-source-of-truth but only for static theme names?

It would be nice, but have you considered what to do about localization? That was one of the trickier issues when dealing with this problem.

Wouldn't removing the name field for updates put static themes effectively on the same boat as extensions?

**Comment by eviljeff** [comment]
> > minimal implementation of manifest-single-source-of-truth but only for static theme names?

> It would be nice, but have you considered what to do about localization? That was one of the trickier issues when dealing with this problem.

There effectively wouldn't be any localisation of the name if the wizard was used.  The developer would need to craft their own xpi to do that.

> Wouldn't removing the name field for updates put static themes effectively on the same boat as extensions?

I don't follow.

**Comment by jvillalobos** [comment]
> There effectively wouldn't be any localisation of the name if the wizard was used. The developer would need to craft their own xpi to do that.

The issue with localization and tying strings to the manifest is that the manifest is localizable, so a developer can upload new versions that add/remove locales, which could affect other localizable fields that are unrelated to the manifest. It's a solvable problem, but it doesn't seem worth tackling only for themes.

> Wouldn't removing the name field for updates put static themes effectively on the same boat as extensions?

I'm suggesting that, when you upload an update using the theme wizard, we don't show the name field. So, it wouldn't be possible change the theme name via an update, which is effectively what we do for extensions.

**Comment by eviljeff** [comment]
> I'm suggesting that, when you upload an update using the theme wizard, we don't show the name field. So, it wouldn't be possible change the theme name via an update, which is effectively what we do for extensions.

Yes, that's true.  Although the difference would be they wouldn't be able to change the name in the xpi (so Firefox add-on manager) either, without crafting their own xpi.  Tbh, this is probably a very rare thing.  So just removing the field should be enough.

**Comment by ioanarusiczki** [comment]
@eviljeff 
1. For the first submission if the user mouse hovers over the tooltip the message will open. Let me know if the behaviour is as expected - see the .gif  
![namenew](https://user-images.githubusercontent.com/33448286/42561772-a3416bca-8502-11e8-970f-71b4a0578154.gif)

2. When uploading a new version go to [edit listing](url) link is not available. I verified this on AMO dev with FF61(Win10)
![go toedit listing](https://user-images.githubusercontent.com/33448286/42562107-8683ff7e-8503-11e8-9dd3-6af1deb12fd0.png)

**Comment by eviljeff** [comment]
> For the first submission if the user mouse hovers over the tooltip the message will open. Let me know if the behaviour is as expected - see the .gif

Yes.  It's the same style used in the license options below.

> When uploading a new version go to edit listing link is not available. I verified this on AMO dev with FF61(Win10)

https://github.com/mozilla/addons-server/pull/8798#issuecomment-403859427 - @jvillalobos didn't want the link so I removed it again.

**Comment by ioanarusiczki** [comment]
@eviljeff I just have the feeling that someone will file an issue that the new versions cannot be renamed. Maybe a tooltip next to Theme name* with a text such as  "To edit the listing name of this add-ongo to Edit information page. The listed name might be different to the name inside the add-on " should solve this problem? Just let me know if I should file this.

Verified fixed on AMO dev with FF61(Win10).

**Comment by eviljeff** [comment]
@ioanarusiczki that's exactly what I had, but if you see the link I mentioned, Jorge decided it was confusing rather than helpful and it's his job to make those decisions 😉
