### ISSUE TITLE
Cleanup logger names

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8527]
Our current logger names are not unified and don't even have very common prefixes. They're also quite bad to search for in Kibana, e.g "accounts" etc.

Current loggers that we have

 * accounts
 * accounts.sqs
 * accounts.verify
 * adi.downloadcounts
 * adi.themepopularitymovers
 * adi.themeupdatecount
 * adi.updatecounts
 * devhub
 * mkt.purchase
 * signing
 * test
 * z.access
 * z.accounts
 * z.addons
 * z.amo
 * z.amo.activity
 * z.amo.mail
 * z.api
 * z.api.authentication
 * z.apps.stats.views
 * z.appversions
 * z.collections
 * z.compat
 * z.cron
 * z.crypto
 * z.devhub
 * z.devhub.task
 * z.disco
 * z.elasticsearch
 * z.es
 * z.files
 * z.files.disabled
 * z.files.task
 * z.files.utils
 * z.github
 * z.jwt
 * z.mailer
 * z.monitor
 * z.ratings
 * z.redis
 * z.reviewers
 * z.reviewers.auto_approve
 * z.reviewers.award_post_review_points
 * z.reviewers.forms
 * z.reviewers.recalculate_weights
 * z.reviewers.send_info_request
 * z.search
 * z.startup
 * z.stats
 * z.task
 * z.translations
 * z.users
 * z.versions
 * z.versions.utils
 * z.zadmin

Third party loggers:
 * boto3
 * botocore

(And probably MUCH more, PIL, etc may be added).

My proposal is a little logging helper (that I copied from one of my personal projects and I use all over the place):

```python
import inspect
import logging


def get_logger(obj):
    """Return a logger object with the proper module path for ``obj``."""
    # initialize settings to configure logger.
    from django.conf import settings  # noqa

    name = None
    module = getattr(inspect.getmodule(obj), '__name__', None)
    if inspect.ismethod(obj):
        name = f'{module}.{obj.im_class.__name__}.{obj.__func__.__name__}'
    elif inspect.isfunction(obj):
        function = getattr(
            obj, 'func_name',
            getattr(obj, '__qualname__', obj.__name__))

        name = f'{module}.{function}'
    elif inspect.isclass(obj):
        name = f'{module}.{obj.__name__}'
    elif isinstance(obj, str):
        name = obj

    return logging.getLogger(name)


def logged(obj):
    """Decorator to mark a object as logged.

    This injects a ``logger`` instance into ``obj`` to make log statements
    local and correctly named.

    Example:

    .. code:: python

        >>> @logged
        ... class MyClass(object):
        ...     def foo(self):
        ...         self.logger.warning('logged')
        ...
        >>> import logging
        >>> logging.basicConfig()
        >>> obj = MyClass()
        >>> obj.foo()
        WARNING:__main__.MyClass:logged

    Supported objects:

        * Functions
        * Methods
        * Classes
        * Raw names (e.g, user at module level)

    """
    obj.logger = get_logger(obj)
    return obj
```

that automatically generates a proper logger name based on the module and path of the function, class etc which can be really easy to find in the logs later.

Opinions, objections?

**Comment by eviljeff** [comment]
I'm not sure we need that much functionality, but it _would_ be consistent if we changed everywhere to use `@logged` instead of importing `get_logger`.
