### ISSUE TITLE
Fold jingo_minify into addons-server

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8532]
In preparation and as part of our upgrade to Django 1.11 we should fold jingo_minify into addons-server to eventually get rid of it and get more control over it.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa: not needed" ?

**Comment by EnTeQuAk** [comment]
Removing the "qa: not needed" label as this kinda bit me last time.

Please make sure that we continue to see static images and icons, such as the plus before the "Add to Firefox" install button, stars at ratings etc.

I don't expect this to be broken in one place and working in others but rather it's either broken throughout the system or not.

Also, some weirdly broken styles may be worthy to report. Other than that this doesn't change any functionality but solely changes/replaces parts of the code that compiles our css/less files into minified css.

**Comment by ioanarusiczki** [comment]
I don't see any broken icons, images, ratings on the legacy site, checked the detail pages for extensions, themes. 
Verified fixed on AMO stage with FF61(Win10).
