### ISSUE TITLE
Permission to delete many-to-many relationship tables unable to be granted

### ISSUE THREAD

**Issue by MCBama** [mozilla/addons-server#8539]
I've created an "instructor" Group as a staff member and granted them the permission to add/edit/delete custom user objects called 'Student' through the admin interface. Each student is assigned to a group named "student." When attempting to delete a student through the admin interface as a logged in instructor, I get a permission error stating:

```
Deleting the selected student would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:

    student-group relationship
```

I log back in as a super user and I can see the `student-group relationship` table but going through the list of permissions available to be assigned to groups the `student-group relationship` model doesn't show up anywhere.

Is it possible this issue stems from what was supposed to be fixed in #7848 where super users couldn't see all the available tools? Or is the permissions list not supposed to include group relationship tables?

As a test I simply granted my instructor user account all permissions available and it was still unable to delete the student account for the same reason. Superusers have no problem deleting said student account due to the fact that they're assumed to have all permissions just by existing but I figured there was a way to grant essentially all permissions to a specific user if desired.

**Comment by EnTeQuAk** [comment]
Sorry, I may be missing something but I'm a bit confused here. What does this have to do with addons-server or addons.mozilla.org?

**Comment by MCBama** [comment]
Hrm. Interesting. Somehow I went to django issues and followed a link here...Misplaced issue. Sorry I didn't notice.
