### ISSUE TITLE
Consider adding a notice/warning to developers about Thunderbird submissions

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8540]
Following #8344, we might want to add a notice or similar to developers during submission of a version that is compatible to both Firefox and Thunderbird to let them know/remind them that Thunderbird versions need to be submitted to another site.

**Comment by muffinresearch** [comment]
Assigned to @jvillalobos for input.

**Comment by jvillalobos** [comment]
We need to message those developers once the move is done, so I think the warning is unnecessary.
