### ISSUE TITLE
[Reviewer Tools] Weighting Allocation Anomaly

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#8547]
I have seen a few examples that could be anomalies.

Example:
https://reviewers.addons.mozilla.org/editors/review/952494/

Version 1.5 · June 5, 2018 · Approved (Confirmed) Weight: 100
Version 1.6 · June 18, 2018 · Approved Weight: 100
Version 1.7 · June 18, 2018 · Approved Weight: 13

2 versions where uploaded and the weight went from 100 to 13.

**Comment by diox** [comment]
If the initial weight mostly came from the size of code changes that would not be an anomaly.

**Comment by erosman** [comment]
> If the initial weight mostly came from the size of code changes that would not be an anomaly

The point is that the last reviewed version was 1.5 weighted at 100
1.6 was compared with 1.5 and weighted at 100
1.7 was compared with ?? and weighted at 13

**Comment by diox** [comment]
When 1.5 was auto-approved, the size of code changes compared to the latest confirmed version was fairly high, causing a bump to 100. Same with 1.6, even though 1.5 was then confirmed, the weight stored didn't change. Finally for 1.7 the last confirmed version was 1.6 already had there wasn't a lot of code changes detected as a result, so the weight is low.

**Comment by erosman** [comment]
> Finally for 1.7 the last confirmed version was 1.6 
@diox 
That is the anomaly. Version 1.6 was NEVER confirmed.
Did you check the addon?

The point is that the last reviewed version was 1.5 weighted at 100
1.6 was compared with 1.5 and weighted at 100 **<- Not human Reviewed**
1.7 was compared with ?? and weighted at 13

If this is the case, then developer can bypass the review system easily.

**Comment by diox** [comment]
Sorry, I meant 1.5. My point still stands: it's all because of the size of code changes between the confirmed versions at the time it was auto-approved.
