### ISSUE TITLE
Remove ipython from packages on travis

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8564]
We install IPython and ipdb by default in `dev.txt` which is fine, and should potentially be run by CircleCI UI Tests (since that's the only place where we install **everything** from scratch already).

But let's maybe try to simplify our travis installation a bit and don't install ipython / ipdb there.

**Comment by AlexandraMoga** [comment]
Please add a "qa:not needed" label to this issue.
Thanks
