### ISSUE TITLE
Changing application from Thunderbird to Firefox doesn't route back to addons.mozilla.org

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8567]
STR:

1. Load AMO -dev homepage
2. From Other Applications switch to Thunderbird or Seamonkey
3. Observe the URL
4. Change back to Firefox
5. Observe the URL again

Actual result:
After changing back to Firefox, the user lands on https://addons.thunderbird.net/en-US/firefox/

Expected result:
After changing back to Firefox, the user lands on https://addons-dev.allizom.org/en-US/firefox/

Notes:
 - reproduced on AMO -dev with FF60, Win10x64
 - this is linked to #8344 which referenced to the new route created for Thunderbird and Seamonkey submissions 

![application route](https://user-images.githubusercontent.com/31961530/41598422-cdb3546c-73d8-11e8-9925-96d1ef41f16f.gif)

**Comment by diox** [comment]
This is expected since https://github.com/mozilla-services/cloudops-deployment/pull/2070 hasn't been merged yet

**Comment by diox** [comment]
Commit has landed.

**Comment by AlexandraMoga** [comment]
@diox does your last comment imply that this issue should be fixed now? I'm still seeing the same behavior on -dev.

**Comment by diox** [comment]
It should be, yes. The first part is working for me - I'm redirected to addons.thunderbird.net if I choose "Thunderbird" in AMO. The second part isn't, but that's a bug on addons.thunderbird.net side, not AMO. I'd file it over at https://github.com/thundernest/addons-server

**Comment by AlexandraMoga** [comment]
The first part is working for me as well. I've refiled the issue on the Thunderbird server - https://github.com/thundernest/addons-server/issues/3
