### ISSUE TITLE
add a static theme type to disco pane on dev only

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-server#8572]
If we can get this set up on dev we can begin some testing here

**Comment by eviljeff** [comment]
The problem is the data for discopane is hard-coded in python, so anything we change for -dev then ends up on prod in the next push.  We'd have to hide the change behind a waffle switch - that would normally switched off even on -dev, outside of whatever testing window you need.

**Comment by rebmullin** [comment]
hey @eviljeff, is that pretty easy to set up - the waffle switch? If it's normally off by default even on dev, how would I turn it on so I can test this ideally locally and then just on dev?

**Comment by eviljeff** [comment]
it would need to be switched on by someone with access to /admin.  I guess it could probably be left enabled on -dev as long as QA were aware in case they needed to test the prod-style results.

Thinking about it, the cleanest way is to add another custom edition (like `china`) but that may be more work on your end to switch the frontend to use it.

**Comment by rebmullin** [comment]
hey @eviljeff...I'll use your recommendation on this: ). Whatever way you think is best... 

Either way tho I might need a little direction/instructions on how to get it working locally/dev?

**Comment by eviljeff** [comment]
I'm going to enable the switch on dev for @rebmullin 

QA - your team might want to be aware of this waffle switch when they're testing future discopane monthly content updates.

**Comment by vcarciu** [comment]
@eviljeff : thank you

**Comment by rebmullin** [comment]
thanks @eviljeff

**Comment by AlexandraMoga** [comment]
I've checked the response for the discovery API endpoint - `https://addons-dev.allizom.org/api/v4/discovery/` -  and my results are the following:

1. with the `disco-staticthemes-dev` switch enabled: 
![image](https://user-images.githubusercontent.com/31961530/42756056-3525ad2c-8903-11e8-8494-c1160ca1354b.png)

=> two results in the response out of which the first is a static theme

2. with the `disco-staticthemes-dev` switch disabled:
![image](https://user-images.githubusercontent.com/31961530/42756092-59fa9e3c-8903-11e8-8956-b95382ddda16.png)

=> one result returned in the response, a LWT (`type=persona`)

Marking issue as verified fixed on -dev.
