### ISSUE TITLE
Legacy AMO homepage menu is showing some translation issues on -dev and stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8578]
STR:

1. Load AMO -dev homepage - https://addons-dev.allizom.org/en-US/firefox/
2. Switch to a different locale
3. Check the Menu options beneath the Logo

Actual result:
The menu items are not translated when the locale is changed

Expected result:
The menu items are translated after the locale is changed

Notes:
- For stage, - https://addons.allizom.org/en-US/firefox/ -  the menu items seem to be translated randomly after several minutes. In ~30 min interval, the menu was translated to German (de) and then to Chinese (zh-TW)
- when clicking on one of the menu options, the page the user is redirected to will be set to the locale of the menu items

![menu transl](https://user-images.githubusercontent.com/31961530/41647318-af00a06e-747e-11e8-9a12-81e02382a100.gif)

**Comment by diox** [comment]
@EnTeQuAk wild guess: is this caused by https://github.com/mozilla/addons-server/issues/8529 ?

**Comment by diox** [comment]
`side_nav()` was modified to use `make_key()`, but `site_nav()` didn't, so it's not taking the language into account when caching...

**Comment by AlexandraMoga** [comment]
Fixed on -dev

![image](https://user-images.githubusercontent.com/31961530/41669642-ee73c1fe-74ba-11e8-9305-64fae0a700b3.png)


@diox let me know when this can be verified on stage too

**Comment by AlexandraMoga** [comment]
Fixed in stage too.

Marking issue as verified fixed.
