### ISSUE TITLE
tag=firefox57 in the API URL includes legacy add-on

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#8579]
A legacy add-on, Tab Mix Plus, is included in the JSON results:
> wget "https://addons.mozilla.org/api/v3/addons/search/?platform=linux&q=Tab+Mix+Plus&sort=users&type=extension&tag=firefox57" -O tmp.json
> jq .results[] tmp.json | grep "tab-mix-plus"

**Comment by diox** [comment]
This tag is not 100% guaranteed to work, there are some known edge cases with it. We don't use it anymore, and don't link to it much, so it's wontfix.

**Comment by davidhedlund** [comment]
@diox Thank you for the information. I'll remove the tag from the URL's in my code.

**Comment by davidhedlund** [comment]
**app=firefox&appversion=60** did the trick (I really wanted version 60 compatibility): 
https://addons.mozilla.org/api/v3/addons/search/?platform=linux&q=Tab+Mix+Plus&sort=users&type=extension&app=firefox&appversion=60

**Comment by davidhedlund** [comment]
https://github.com/mozilla/addons-server/issues/6365
