### ISSUE TITLE
set all image sizes in recreate_previews task

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8583]
Some old previews don't have size data stored, so may as well backfill at the same time.

**Comment by AlexandraMoga** [comment]
@eviljeff could you please point to something more specific that should be tested here?
Thank you

**Comment by eviljeff** [comment]
We just ran the `recreate_previews` task on -dev.  There's probably not much to check but all addon API responses should have a list of two values in `previews[ ].image_size` now.  E.g. https://addons-dev.allizom.org/api/v3/addons/addon/cam/ but with all addons.

**Comment by AlexandraMoga** [comment]
I've compared the image data returned for several older add-ons and noticed that on stage there are cases with `'image_size'` not being stored while on -dev this situation is not occurring anymore (with the samples I've tested with, at least)

**stage** - missing image size
https://addons.allizom.org/api/v3/addons/addon/image-block/
https://addons.allizom.org/api/v3/addons/addon/download-statusbar/

**-dev** - image size listed
https://addons-dev.allizom.org/api/v3/addons/addon/image-block/
https://addons-dev.allizom.org/api/v3/addons/addon/download-statusbar/

I'm marking the issue as verified fixed on -dev

**Comment by eviljeff** [comment]
👍 we'll run on stage after the tag.
