### ISSUE TITLE
Detect if an upload is a dictionary and give it the correct type.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8586]
Allow upload of webextension dictionaries. In their manifest, they should have the following:
```json
"dictionaries": {
    "en-US": "/path/to/file.dic"
}
```

They should be recognized as dictionaries in AMO when uploaded. https://github.com/mozilla/addons-linter/issues/2055 will add dictionary-specific validation to the linter.

**Comment by diox** [comment]
Could be done without https://github.com/mozilla/addons-linter/issues/1984 but it'd be better with it.

**Comment by AlexandraMoga** [comment]
@diox there seems to be an issue with platform selection during dictionary uploads, which prevents the completion of the submission, i.e I am stuck at platform selection:

![image](https://user-images.githubusercontent.com/31961530/43722786-c4685dd0-999e-11e8-963a-e92cd11a3f6f.png)

**Comment by diox** [comment]
Weird, it worked for the one I tested with. Can you attach the zip to this issue?

**Comment by AlexandraMoga** [comment]
@diox. I figured out what was causing my issue: I had a `strict-min-version` declared without a corresponding `strict-max-version`. After correcting that, the platforms show up, except for Android, which, similar to lang packs, should not be supported. 

However, I'd be glad if you had a look at the .zip I've created to make sure that everything is put together correctly before I go on with more testing. 

[Webext dict en-US.zip](https://github.com/mozilla/addons-server/files/2265528/Webext.dict.en-US.zip)

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64

Webextension dictionaries can be uploaded through dev-hub and they receive the correct type after submission: 

See https://addons-dev.allizom.org/api/v3/addons/addon/webext-dictionary12/

Frontend:
![image](https://user-images.githubusercontent.com/31961530/43779432-13c2b890-9a61-11e8-93df-69d30d34eb64.png)
