### ISSUE TITLE
Migrate Dictionaries to Web Extension format

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8587]
Automatically convert all dictionaries on AMO to the new format. This can't be done until they are supported on release, and will require notifying developers as well.

**Comment by EnTeQuAk** [comment]
How is this supposed to work regarding backward compatibility for Firefox 60 LTS? Although I'm not sure if Firefox 60 already supports this, there are parts already in the schema so maybe we're already good?

**Comment by diox** [comment]
So for each dictionary:
- Extract the `current_version` file somewhere
- Add `manifest.json` inserting the path to the `.dic` file, copying over necessary fields from the `install.rdf`, increasing the version number and then removing that file
- Zip that directory into a .xpi that is then attached to a `File` instance itself added to a new `Version` on the `Addon`, re-using the version number we generated.
- Fire `Addon.update_version()` method, reindex

There is a finite number of dictionaries, we can probably download them all to make sure this will work beforehand. Maybe even have a `--dry-run` option, though I'm not sure it's necessary.

**Comment by diox** [comment]
Safest way to handle the version number increment is probably going to be this, similar to how we did it for mass-signing:
```python
if number.endswith('.1-typefix'):
    number = number.replace('.1-typefix', '.2-webext')
else:
    number = '%s.1-webext' % number
```

The `.1-typefix` is present for a number of dictionaries, I assume it's coming from an older automated mass-change (couldn't find it by grepping around the code though). It's probably safe to replace that suffix with another one.

**Comment by diox** [comment]
QA: upload some legacy dictionaries on dev if you wish, making sure to make them public + set the `target_locale` for them in add-on admin (through /admin/models/addons/addon/). Then, when you are ready to test, let me know and I'll launch the script.

**Comment by AlexandraMoga** [comment]
Dictionaries to migrate:
https://addons-dev.allizom.org/en-US/firefox/addon/dansk-for-migration/
https://addons-dev.allizom.org/en-US/firefox/addon/svenska-for-migration/
https://addons-dev.allizom.org/en-US/firefox/addon/romanian-for-migration/

**Comment by AlexandraMoga** [comment]
After migration:

- the legacy dictionary receives a new version - version number will consist of the previous version number +  `.1webext` [1] . This is also the current listed version on AMO.
- the dictionary package looks intact, and the `install.rdf` is replaced with a `manifest.json`

[1]
![image](https://user-images.githubusercontent.com/31961530/45094018-ce1fe000-b122-11e8-91ef-4ce81b441958.png)

@mat I have a few observations:

- when looking at the versions page in dev hub, I can see that the new version has not been validated. Instead, there is a `Validate now` link that will allow a manual validation. [2] Is this an issue?

[2]
![image](https://user-images.githubusercontent.com/31961530/45094555-5a7ed280-b124-11e8-9428-6802dcdbfb7f.png)

- the dictionaries can't be installed. I'm using an unbranded version of FF with the right permissions set, but I'm still receiving a "corrupt" error during installation

[3]
![image](https://user-images.githubusercontent.com/31961530/45094407-e3e1d500-b123-11e8-8f8f-2d9494757e50.png)

IIRC, there was a similar issue when some lwt were migrated to static themes and that was solved in https://github.com/mozilla/addons-server/pull/8386

**Comment by diox** [comment]
> when looking at the versions page in dev hub, I can see that the new version has not been validated. Instead, there is a Validate now link that will allow a manual validation. [2] Is this an issue?

I did that on purpose because in some cases, the original version number - and therefore the new one generated for the webext - won't be valid as far as the linter is concerned. We don't care much though.

> the dictionaries can't be installed. I'm using an unbranded version of FF with the right permissions set, but I'm still receiving a "corrupt" error during installation

Which version of Firefox are you using ? Did the legacy version install correctly? The dictionaries should definitely be signed, so it's not the same issue as #8386.

**Comment by AlexandraMoga** [comment]
@diox  the legacy version was installed correctly. I have tried with  Firefox 61, 62 and latest Nightly but the webextension version will not install.

**Comment by diox** [comment]
Anything in the Browser Console (not the devtools console) ? It installs correctly through `about:debugging`, but I'm not set up to install things from dev at the moment.

**Comment by AlexandraMoga** [comment]
@diox 

`
1536155905717	addons.xpi	WARN	Download of https://addons-dev-cdn.allizom.org/user-media/addons/496262/svenska_fria_ordlistan-1.2.1webext.xpi?filehash=sha256%3A95dc49558432fe3762bb155b0af0fc4427aa734a88d6a02a72607ffda4ff9db0 failed: Error: Cannot find id for addon C:\Users\ALEXAN~1.MOG\AppData\Local\Temp\tmp-fme.xpi (resource://gre/modules/addons/XPIInstall.jsm:1545:19) JS Stack trace: loadManifest@XPIInstall.jsm:1545:19
`

The legacy version used to have an ID defined in the instal.rdf, but the manifest of the webextension version has limited metadata, so no ID is present. Could this be the reason?

**Comment by diox** [comment]
mmm that's weird. Was the legacy version installed when you tried to install the webext one ?

**Comment by AlexandraMoga** [comment]
I have tried both ways: 

1 with legacy version installed previously
2. without legacy version previously installed

I get the same error as above

**Comment by diox** [comment]
It's weird that it works fine for me in about:debugging but not through regular install. I wonder if until now we just tested webext dictionaries with an explicit id in their manifest...

**Comment by AlexandraMoga** [comment]
It does seem that  webextension dictionaries without an ID in the manifest can't be installed. 
I've tried with a new submission  - https://addons-dev.allizom.org/en-US/firefox/addon/dictionar-webextension-no-id/?src=search

@diox I can file this as a new issue on our side, if you want to keep investigating, or I can file a Firefox bug.

**Comment by diox** [comment]
Can you do both and cc me on that Firefox bug ?

**Comment by AlexandraMoga** [comment]
I have filed https://bugzilla.mozilla.org/show_bug.cgi?id=1489106 and https://github.com/mozilla/addons-server/issues/9366 as follow ups.

Marking this issue as verified fixed on AMO -dev with FF62, Win10x64
