### ISSUE TITLE
'Groups' option from django admin pages shows 0 available groups 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8595]
STR:

1. Log in to AMO with an admin account
2. Access Admin Tool and go to Django admin pages
3. Click on the 'Groups' option from the tools list

Actual result:
User lands on https://addons-internal.dev.mozaws.net/en-US/admin/models/auth/group/ which shows 0 available groups

Expected result:
The user should be able to see all the user groups available

Notes:
- if I access groups from 'Manage users' --> 'Configure groups' tab I land on https://addons-internal.dev.mozaws.net/en-US/admin/models/access/group/ where the user groups are available
- reproduced on -dev and stage with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/41700686-ea7aea92-7531-11e8-8452-bcf7fa1b1b55.png)

**Comment by EnTeQuAk** [comment]
This is very low priority since it always has been like that. I do agree, if we extend our admin tools we should maybe hide these django internal apps in the model list but that's likely not going to be fixed anytime soon.

**Comment by AlexandraMoga** [comment]
This is working now
