### ISSUE TITLE
User with Collections:Contribute permission don't have access to 'featured-personas' collection

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8596]
Follow up for #8538 

STR:

1. Log in to AMO dev with a user with `Collections:Contribute` permission
2. Access the `featured-personas` collection - https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-personas/

Actual result:
The user doesn't have access o the collection - an internal server error is received

Expected result:
The user has access to view and edit the collection

Notes:
- reproduced on -dev and stage with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/41701808-808c4414-7536-11e8-9b05-0bcbc2770de7.png)

**Comment by EnTeQuAk** [comment]
This broke in 39ddb65aefebd0a10b97f997cac2f73b7b4ba9e7 which introduced `amo.permissions.COLLECTIONS_CONTRIBUTE` in various places but never specified it in our `constants.permissions` module.

@eviljeff imho we simply need to add that permission or is there anything else we should do? I think you have a bit more context here than I do

**Comment by diox** [comment]
I knew I forgot something in that PR :(

**Comment by vcarciu** [comment]
Verified as fixed in -dev
