### ISSUE TITLE
Commit product-detail json files into git

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8597]
We should start committing the product-details json files into our repository. It takes a significant amount of time to download them on every test-run, they're not necessarily needed for tests either but we can also just start adding them to our repository.

They don't change that much and django-product-details takes care of making sure to now download anything that hasn't changed.

Preferably this will happen automatically.

**Comment by championshuttler** [comment]
Hi @EnTeQuAk I am interested in solving this bug.
should we remove the product json files from.gitignore so that they will commit into git.
https://github.com/mozilla/addons-server/blob/master/.gitignore#L12-L18

**Comment by EnTeQuAk** [comment]
> Hi @EnTeQuAk I am interested in solving this bug.
should we remove the product json files from.gitignore so that they will commit into git.
/.gitignore@master#L12-L18

Maybe, if that's alright for you I'd rather do that myself because I need to test a few things I'm not yet certain of. Especially how to handle changing data, e.g is there a good way to automate this etc. Please have a look at a few other issues and we're happy to help there!

**Comment by EnTeQuAk** [comment]
Idea regarding this: Do you think it makes sense to simply commit these files into git and run synchronization as part of our locale extraction process?

We don't require updates very often anyway, product-details only get pulled when a new image is a build which only happens on Thursday for production. So the locale-sync should be perfectly fine since that happens only once a week too.

**Comment by diox** [comment]
I rebased one of my branches from before that commit with newest master this evening and suddenly it was throwing 502 Bad Gateway errors... Looking at the logs it was trying to update product details at startup again... and indeed, once it was done (it took at least a minute or two) and gave me my runserver back, it had made the following changes:

```
	modified:   src/olympia/lib/product_json/.all.json.last_modified
	modified:   src/olympia/lib/product_json/.devedition.json.last_modified
	modified:   src/olympia/lib/product_json/.firefox.json.last_modified
	modified:   src/olympia/lib/product_json/.firefox_history_development_releases.json.last_modified
	modified:   src/olympia/lib/product_json/.firefox_history_major_releases.json.last_modified
	modified:   src/olympia/lib/product_json/.firefox_primary_builds.json.last_modified
	modified:   src/olympia/lib/product_json/.firefox_versions.json.last_modified
	modified:   src/olympia/lib/product_json/.last_update
	modified:   src/olympia/lib/product_json/.thunderbird_history_stability_releases.json.last_modified
	modified:   src/olympia/lib/product_json/.thunderbird_primary_builds.json.last_modified
	modified:   src/olympia/lib/product_json/.thunderbird_versions.json.last_modified
	modified:   src/olympia/lib/product_json/all.json
	modified:   src/olympia/lib/product_json/devedition.json
	modified:   src/olympia/lib/product_json/firefox.json
	modified:   src/olympia/lib/product_json/firefox_history_development_releases.json
	modified:   src/olympia/lib/product_json/firefox_primary_builds.json
	modified:   src/olympia/lib/product_json/firefox_versions.json
	modified:   src/olympia/lib/product_json/regions/.hi-IN.json.last_modified
	modified:   src/olympia/lib/product_json/thunderbird_history_stability_releases.json
	modified:   src/olympia/lib/product_json/thunderbird_primary_builds.json
	modified:   src/olympia/lib/product_json/thunderbird_versions.json
```

**Comment by EnTeQuAk** [comment]
Yeah, this needs to be synced automatically much more often than I anticipated. I opened #8807  and will get the automation running asap

**Comment by vcarciu** [comment]
@EnTeQuAk : can you please add some STRs to this bug or mark it as  "qa: not needed" ?
