### ISSUE TITLE
Theme listing pages are displaying a server error on the legacy site

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8598]
STR:

1. Load AMO  Themes homepage
2. Select a theme to view its details page - i.e. https://addons-dev.allizom.org/en-US/firefox/addon/lilac-prediction/

Actual result:
An internal server error is displayed

Expected result:
Theme details page is displayed

Notes:
- reproduced on -dev and stage with FF60, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/41704268-7d2b41fa-753e-11e8-986b-935f026246de.png)

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4406389/

**Comment by vcarciu** [comment]
Verified as fixed on -dev
