### ISSUE TITLE
Period in username might cause 404

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-server#8607]
### Describe the problem and steps to reproduce it:

Go to [addons-dev.allizom.org/en-US/firefox/user/c.cheng
](http://addons-dev.allizom.org/en-US/firefox/user/c.cheng
)
### What happened?

Returns 404

### What did you expect to happen?

user page will appear

### Anything else we should know?

404 is on new site only, on legacy it's okay

I think this is b/c they have a period in their name, which no longer seems to be allowed..? When I try to update the username here, I see the following message now:

![Alt text](https://monosnap.com/image/UABZmj0WxpjQj9g7g2hJnrx2Smrzp3.png)

**Comment by willdurand** [comment]
> Describe the problem and steps to reproduce it:
> 
> Go to addons-dev.allizom.org/en-US/firefox/user/c.cheng
> What happened?
> 
> Returns 404

it is worth mentioning that the API returns a 404 (the frontend does not do anything special).

**Comment by diox** [comment]
We seem to have old 80k+ accounts with a period in the username. Ugh :( Most of them appear to be unused, but yeah, we should allow the API to fetch them...

**Comment by eviljeff** [comment]
#8302 will make this obsolete (though will be more work than fixing whatever small bug is preventing this - probably just a regex somewhere)

**Comment by eviljeff** [comment]
btw, during investigation for #8302 I'm pretty sure `.` is prevented even on the legacy account profile edit page so I guess these are super old accounts?

**Comment by jvillalobos** [comment]
The most recent modified date for those accounts is `2016-09-04`. The last login date shows many of those accounts are still active, though.

**Comment by diox** [comment]
I'm fixing this *in the API only*, so the new frontend should be fixed once this lands, not sure what the legacy one allows. Those users will be able to see their profile on the new frontend, but when editing it they'll have to change the username.

**Comment by willdurand** [comment]
Is the error message explicit enough so that users will know that periods are not allowed?

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev by requesting  the profile page for the following user:

in the api: https://addons-dev.allizom.org/api/v3/accounts/account/g.mail.test./
on the frontend: https://addons-dev.allizom.org/en-US/firefox/user/g.mail.test./

The profile details are returned in both cases.
The user will not be able to edit his profile unless the username is valid.

@willdurand with regards to the error message received for invalid usernames, currently we are telling the users what characters _are allowed_ but we are not mentioning what _is forbidden_ 
Maybe the message could provide some examples of forbidden characters that are actually popular in usernames, but I'm not sure that we should make a special case only for periods. 
What exactly do you have in mind on this subject?


![image](https://user-images.githubusercontent.com/31961530/43960654-585b5c80-9cbb-11e8-8d6d-2751307c77d7.png)
