### ISSUE TITLE
API for voting for user reviews

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8611]
[Ratings PRD](https://docs.google.com/document/d/1oUz9Ng9v159IPdW4UqHhbNspWa9m5SaicAAX5jU7OjA/edit#heading=h.z6eh8thy43a6).

Logged in users should be able to vote on a user review's helpfulness, up or down, once. They can't vote for reviews they wrote, or for add-ons they have authored. They should be able to undo or change their vote.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-161)

**Comment by eviljeff** [comment]
Size M/L maybe, but this is the one that's a new feature, needing models, API changes, etc.

**Comment by eviljeff** [comment]
stalebot would have closed this ages ago if it didn't ignore closed projects so takin' it's jub and closing it myself.
