### ISSUE TITLE
Use black for automatically formatting our source code

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8617]
I've been dreaming to do this on addons-server for a long time and now that black grows to a quite sophisticated tool to do proper source formatting in python projects we may as well try.

Their style guide: http://black.readthedocs.io/en/stable/the_black_code_style.html

Black is very opinionated and obliterates our current imports-style-guide to some extent. It doesn't touch the ordering there at all though, only the wrapping, which is nice, that means we can still combine it with pytest-isort.

Black recently gained the ability to *not* force regular quotes which means we can continue to use single-quotes which would simplify the whole diff and migration a bit.

``black --skip-string-normalization --line-length 79 src/``

The output of that can be seen in [this experimental branch](https://github.com/mozilla/addons-server/compare/black-experiment).

This obviously only works if everyone is doing it and we are enforcing it via CI so we should all be on the same page before we do this.

I do think that this will simplify code reviews and also on-boards contributors much better since no one needs to worry about how the code looks anymore.

It can be integrated into CI using ``black --check`` as part of our ``codestyle`` task. We may want to exclude existing migrations in a final run (I didn't in the experimental branch). There is an active community around it and good [integration into editors and tools ](http://black.readthedocs.io/en/stable/editor_integration.html)

Alrighty, opinions, thoughts, objections? @diox @eviljeff

**Comment by diox** [comment]
I'm not a super big fan of how black wraps long lists of things, IMHO the way it does it doesn't improve readability at all. It gets worse with long inline `if`/`else`:
```diff
 def bounce_mail(message, reason):
-    recipient = (None if not isinstance(message, dict)
-                 else message.get('From', message.get('ReplyTo')))
+    recipient = (
+        None
+        if not isinstance(message, dict)
+        else message.get('From', message.get('ReplyTo'))
+    )
```


That being said, having such a formatter, integrated into our editors, with a big community etc, seems like the right thing to do, so I dunno...

**Comment by eviljeff** [comment]
I'm not really convinced unless we can tweak the settings further.  From a look at some of the diff (it's really, really, long) it makes some changes that seem unnecessary and just increase the number of lines. 
```diff
     raw_id_fields = ('addon', 'user', 'reporter')
-    readonly_fields = ('ip_address', 'message', 'created', 'addon', 'user',
-                       'guid', 'reporter')
-    list_display = ('reporter', 'ip_address', 'type', 'target', 'message',
-                    'created')
-    list_filter = (AbuseReportTypeFilter, )
+    readonly_fields = (
+        'ip_address',
+        'message',
+        'created',
+        'addon',
+        'user',
+        'guid',
+        'reporter',
+    )
+    list_display = (
+        'reporter',
+        'ip_address',
+        'type',
+        'target',
+        'message',
+        'created',
+    )
+    list_filter = (AbuseReportTypeFilter,)
     actions = ('delete_selected',)
 ```
(wot?)

And seemingly _always_ expands the list of imports onto separate lines (unless the entire statement fits onto one line):
```diff
from olympia.abuse.serializers import (
-    AddonAbuseReportSerializer, UserAbuseReportSerializer)
+    AddonAbuseReportSerializer,
+    UserAbuseReportSerializer,
+)
```

It also knowingly ignores the line length limit sometimes which is a big no-no, imo.
```diff
        self.fxa_identify.return_value = identity
-        self.register_user.side_effect = (
-            lambda r, i: UserProfile.objects.create(
-                username='foo', email='me@yeahoo.com', fxa_id='e0b6f'))
+        self.register_user.side_effect = lambda r, i: UserProfile.objects.create(
+            username='foo', email='me@yeahoo.com', fxa_id='e0b6f'
+        )
```

Things that move us closer to current PEP8 compliance I'll grudgingly accept, like 
```diff
         def delete_locale(s):
-            return s[len(prefix):-len('_delete')]
+            return s[len(prefix) : -len('_delete')]
 ```
and
```diff
 def check_addons_reviewer(request):
     return (
-        action_allowed(request, amo.permissions.ADDONS_REVIEW) or
-        action_allowed(request, amo.permissions.ADDONS_CONTENT_REVIEW) or
-        action_allowed(request, amo.permissions.ADDONS_POST_REVIEW))
+        action_allowed(request, amo.permissions.ADDONS_REVIEW)
+        or action_allowed(request, amo.permissions.ADDONS_CONTENT_REVIEW)
+        or action_allowed(request, amo.permissions.ADDONS_POST_REVIEW)
+    )
 ```

**Comment by eviljeff** [comment]
Fwiw, I can see how in some cases it _could_ simplify code review, but those cases are infrequent from my recollection.  For on-boarding contributors I don't see the argument it's an improvement: it's at best a neutral change to different arbitrary rules, and at worse adding extra counter-intuitive rules that they won't discover until Travis spits out a list of errors.

**Comment by EnTeQuAk** [comment]
> I'm not a super big fan of how black wraps long lists of things, IMHO the way it does it doesn't improve readability at all. It gets worse with long inline if/else:

For what it's worth, I actually love it and that has been my way of formatting things since 2007 … well, until 2015 :rofl:

> I'm not really convinced unless we can tweak the settings further.

That's currently not really possible and they're quite opinionated in that regard. That said, I'm sure they accept contributions. I tried yapf as an alternative to find something that matches more our code-style but it has quite a few problems that didn't work for us. As an example, it seems to not do the formatting very consistently, I regularly ended up with different formattings for edge-case lines. That'd be a no-no for CI-based enforcing.

I also checked out https://github.com/hhatto/autopep8 but that spits out reaaaaaaly weird formatting sometimes, it regularly doesn't get the indentation level correctly.

> And seemingly always expands the list of imports onto separate lines

Yeah, that's it's preferred style. I'm aware that this is not our preferred style given our [isort discussion](https://github.com/mozilla/addons-server/pull/7118).

> It also knowingly ignores the line length limit sometimes which is a big no-no, imo.

Honestly, I'm not much of a supporter of the 79 line-length. At least not in a hard limited way, it does have it's advantages and editing a well-formatted file in a remote vim or so makes use of that but even there ~89 characters are usually perfectly fine imho.

> Fwiw, I can see how in some cases it could simplify code review, but those cases are infrequent from my recollection.

True, but they happen, although much less than some months before if I recall correctly but I'm unsure if that's because we got better at it or simply don't care that much anymore.

> For on-boarding contributors I don't see the argument it's an improvement: it's at best a neutral change to different arbitrary rules, and at worse adding extra counter-intuitive rules that they won't discover until Travis spits out a list of errors.

True, it doesn't necessarily improve the process of learning the style-guide upfront but it definitely adds proper documentation and a clear style-guide to our code which helps in my experience to onboard new people and avoids regular "How would you format this? And this?" questions. We don't have them that often but at least on addons-server we also don't really have bigger regular contributions. This change is not primarily focused on easing contributors onboarding, I personally think that this adds a good amount of documentation and process about how we structure our code.

**Comment by eviljeff** [comment]
>>  It also knowingly ignores the line length limit sometimes which is a big no-no, imo.

> Honestly, I'm not much of a supporter of the 79 line-length. At least not in a hard limited way, it does have it's advantages and editing a well-formatted file in a remote vim or so makes use of that but even there ~89 characters are usually perfectly fine imho.

I'm fine with us increasing the limit to some other amount (89 is fine) but imo a rule is a rule.  If a tool enforces xx characters most of the time, except some times it doesn't even though the code could be rewritten to fix under xx characters, then that tool is broken.

**Comment by eviljeff** [comment]
I've thought about this since and despite still not being particularly happy with some it's choices I think I'd be okay with using it in automation as long as we *also* keep the existing codelinting _after_ Black has run.  So if Black decides it can't fit with a rule we have (e.g. line length) then it's up to us (i.e. the person submitting the patch) to manually tweak the code to help Black along.

**Comment by diox** [comment]
https://pypi.org/project/flake8-black/ might be worth investigating for this.

**Comment by EnTeQuAk** [comment]
Reading this it kinda sounds like both of you are ready to give this another go? I'll try to get it setup and run through the code-base tomorrow then :)

**Comment by diox** [comment]
My position is the same as @eviljeff above: not a massive fan of some choices, but as long as we can get it set up in a way that it doesn't break pep8, then I don't mind.
