### ISSUE TITLE
Re-enable button should have a darker contrast to look as being active

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8618]
STR:
1. Load AMO dev and go to the Manage Status and Versions page of an add-on from dev hub.
2. Disable a version.
3. Observe the re-enable button.

Expected result:
Re-enable is displayed as being active - the button's colour makes it obvious.

Actual result:
Re-enable looks like is not active.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF60(Win10).

![re-enable](https://user-images.githubusercontent.com/33448286/41769329-9927bf80-7617-11e8-9e88-ff9daf641fb0.png)

**Comment by jvillalobos** [comment]
Re-enabling versions is not a common action or one we want to encourage. The link doesn't look great, but it's still relatively easy to spot. We don't think we should change this.
