### ISSUE TITLE
Invalid link in all versions page throws 500

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8622]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4410846/

**Comment by EnTeQuAk** [comment]
QA: Links like https://addons.mozilla.org/sl/firefox/addon/autoformer/versions/0.0.2%20alpha were broken and got fixed as part of this change.

**Comment by vcarciu** [comment]
Verified as fixed. The versions page will be still displayed if opening an invalid link.
