### ISSUE TITLE
Tag all existing dynamic themes using the "dynamic theme" tag

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8631]
All dynamic themes currently on AMO should be tagged as "dynamic theme".

**Comment by eviljeff** [comment]
Unfortunately we've hit the same [problem we did the last time](https://github.com/mozilla/addons-server/issues/4974#issuecomment-296161575) we tried to bulk add tags - the search indexes aren't updated.

Going to fix the task to index the changes properly.

**Comment by eviljeff** [comment]
command has been run again; looks fixed on -dev.

**Comment by vcarciu** [comment]
Verified as fixed. "Dynamic theme" tag is present for all webextensions with "theme" permission.
