### ISSUE TITLE
Update Dev Hub - signed in view 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#8632]
Here are the changes for our regularly scheduled Dev Hub (signed in view) programming updates: 

**Current view:** 
![2018 06 22 dev hub - signed in](https://user-images.githubusercontent.com/23342476/41791719-74e1872a-760b-11e8-9a27-e08701cf687e.png)

**Updates:**
- Remove content from the left hand column
- Move content from the right hand column to the left hand column
- Add new content to right hand column: 
-- Want your extension to be featured on addons.mozilla.org? Our featured extensions policies will tell you what you need to know. 
-- CTA: Learn More

**Comment by vcarciu** [comment]
Verified as fixed : 
![devhubview](https://user-images.githubusercontent.com/1583842/42575802-f2e48aa0-8529-11e8-9e5a-b7314c3733a1.png)
