### ISSUE TITLE
Update Dev Hub - signed out view

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#8633]
Here are the changes for our regularly scheduled Dev Hub (signed out view) updates. 

**Current view:** 
![2018 06 22 dev hub - signed out](https://user-images.githubusercontent.com/23342476/41792099-8f60bf3e-760c-11e8-90ef-030e6abb6152.png)

**Updates**
Remove all text from "Help us improve the developer experience" box. 

Replace with: 

- Headline: Resources for a successful launch
- Copy: You’ve built your extension and are ready to publish it. What comes next? Check out our tips for creating an appealing listing page, getting your extension featured on addons.mozilla.org, finding answers to development questions, and staying up-to-date with news and events relevant to extension developers. 
- CTA: View Resources for Publishers

**Comment by mraza007** [comment]
Oh okay that's fine maybe I can find something else @EnTeQuAk
