### ISSUE TITLE
Drop `dev_agreement` from Addon model

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8640]
`Addon.dev_agreement` is unused. The actual property checked is `read_dev_agreement`, on `UserProfile`  instead.  We should delete `dev_agreement` from Addon.

Afaik it's only referenced in `addons/admin.py` and some fixtures.

**Comment by Vimal-Raghubir** [comment]
Hi @eviljeff, I am interested in fixing this issue. Would simply removing `dev_agreement` from this `addons/admin.py` file suffice or would it need to be replaced by the `read_dev_agreement` attribute in the `Flags` list?

https://github.com/mozilla/addons-server/blob/01f4c0ccb90d3df7b7c55ed6742f93d9e7abbab8/src/olympia/addons/admin.py#L47-L51

**Comment by eviljeff** [comment]
No, we don't need to replace the reference, just remove all mentions.

**Comment by Vimal-Raghubir** [comment]
Ok so I will be removing it from all the json files as well as python files that contain it in the Addons model if thats correct?

**Comment by eviljeff** [comment]
yes

**Comment by Vimal-Raghubir** [comment]
I'm sorry for the many commits instead of one. Not sure how to do combine commits so I made them separate for each file change.

**Comment by vcarciu** [comment]
@eviljeff : Please add some STRs for this bug or mark it as "qa: not needed"

**Comment by eviljeff** [comment]
QA: if you can submission a new addon without a server error, it's okay.

**Comment by vcarciu** [comment]
No server errors encountered during submissions. Marking bug as verified.
