### ISSUE TITLE
Self-Signed Add-on not availible in Firefox Quantum

### ISSUE THREAD

**Issue by sam-malanchuk** [mozilla/addons-server#8643]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I self-sign published an add-on and it is displaying the "Not compatible with Firefox Quantum" error. You can view it at: [https://addons.mozilla.org/en-US/firefox/addon/1932612822a14a4ba6cc/](https://addons.mozilla.org/en-US/firefox/addon/1932612822a14a4ba6cc/)
### What happened?
The add-on was created in and test (using about:debugging) in Firefox Quantum and confirmed as working as intended.
### What did you expect to happen?
I expected to be able to use the add-on in Firefox Quantum as this is the browser all our computers have installed and will be using the add-on on.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/36907446/41851164-0af45936-7855-11e8-9904-6990c0669266.png)
![image](https://user-images.githubusercontent.com/36907446/41851210-28e91986-7855-11e8-8dc3-7b6aec8e6eb6.png)

**Comment by diox** [comment]
Because this add-on only has self-hosted (unlisted) versions, it should not have a public listing page. The fact that it has is a bug, it's only available to you because you're the author. 

To install it, you need to download it from devhub instead.
