### ISSUE TITLE
Unify @write and @use_master into one @use_primary_db decorator

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8644]
We have a `@write` and `@use_master` decorator which do basically the same.

Let's unify them and name that resulting decorator `@use_primary_db` or `@use_master_db` to be explicit.

**Comment by lavish205** [comment]
@EnTeQuAk I would like to work on this issue.

**Comment by lavish205** [comment]
@diox Can you please review it again?

**Comment by vcarciu** [comment]
@EnTeQuAk : can you please add some STRs to this bug or mark it as "qa: not needed" ?
