### ISSUE TITLE
Seamonkey and Thunderbird add-ons are not hidden in search suggestions on AMO

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8645]
STR:

1. Load AMO -dev legacy site
2. Search for an add-on that has only Thunderbird and Seamonkey compatibility - i.e. Lightning
3. Observe the search results

Actual result:
Thunderbird and Seamonkey add-ons are listed in search suggestions

Expected result:
Thunderbird and Seamonkey add-ons are hidden from search suggestions

Notes:
- follow up for #8476
- reproduced on AMO-dev with FF60, Win10x64

[1] Thunderbird
![image](https://user-images.githubusercontent.com/31961530/41855653-d7f34de8-789b-11e8-93b0-45a4cb74822c.png)

[2] Seamonkey
![image](https://user-images.githubusercontent.com/31961530/41855684-ea5edccc-789b-11e8-946b-cfcd5fa864d6.png)

**Comment by diox** [comment]
They will go away once we launch the command to delete them (and reindex). Assigning to me to check.

**Comment by diox** [comment]
I ran the script *on dev*.

**Comment by diox** [comment]
tasks were triggered in bulk, 1180 add-ons should have been deleted... but I can only see 869 delete calls :(

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4434554/

`addon.delete()` failed here, interrupting deletion task for the rest of that batch entirely. That happened 8 times.

I'll make deletion more robust to handle this.

**Comment by diox** [comment]
(Public) Seamonkey and Thunderbird add-on should now be gone from dev (if they were only compatible with either, or both - but not compatible with Firefox or Firefox for Android)

Let me know when it's ok, then we can proceed with stage.

**Comment by ioanarusiczki** [comment]
I verified this with FF61(Win10) and did not find any SeaMonkey or Thunderbird add-ons while making a search on AMO -dev on the legacy frontend. 
The "Seamonkey" or "Thunderbird" search will redirect the user to 
https://addons.thunderbird.net/en-US/seamonkey/
https://addons.thunderbird.net/en-US/thunderbird/

![redirect user](https://user-images.githubusercontent.com/33448286/42451081-da14b500-838e-11e8-9c1a-35560fdb5039.gif)
