### ISSUE TITLE
"Please use smaller images than 4MB" should be displayed when uploading a custom icon 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8654]
STR:
1. Load AMO dev and go to dev hub to a submitted add-on and try to upload as an icon an image with a size between 3 to 4 MB
2. Observe that it can be uploaded
3. Try to replace it with one that has more than 4 MB 
4. Observe the red message displayed after attempting to save changes

Expected result:
The message is: Please use smaller images than 4MB

Actual result:
The message is: Please use smaller images than 3MB

Notes:
This issue is reproducible on AMO dev with FF60(Win10)
This was also reproducible on user profile photo and fixed [here](https://github.com/mozilla/addons-server/issues/7731)

![smaller than 4mb](https://user-images.githubusercontent.com/33448286/41899106-46ce7e52-7934-11e8-8199-14b0ebbe3c1a.png)

**Comment by Abhi-khandelwal** [comment]
hello @ioanarusiczki  , I am a newbie to Open-Source , I want to solve this bug can you please guide me

**Comment by wagnerand** [comment]
Hi @Abhi-khandelwal please see https://wiki.mozilla.org/Add-ons/Contribute#Improve_addons.mozilla.org_.28AMO.29 for relevant information. Also, please feel free to pick a bug that we already nominated as a "good first bug". You'll find more information on the wiki page. Thanks!

**Comment by Abhi-khandelwal** [comment]
![screenshot from 2018-07-04 10-49-39](https://user-images.githubusercontent.com/25298686/42258171-0342757c-7f78-11e8-919d-eff6ad977fe8.png)

whenever I try to upload addons files it give an error...
can you please tell me how to fix this error ?

**Comment by lavish205** [comment]
@wagnerand `MAX_PHOTO_UPLOAD_SIZE` is already set to 4MB in `src/olympia/lib/settings_base.py`. 
Do I need to change somewhere else?

**Comment by wagnerand** [comment]
This is not a good first bug. Feel free to investigate yourself what the issue is, otherwise, you are very welcome to pick a confirmed good first bug where we can offer more guidance.

**Comment by Abhi-khandelwal** [comment]
@wagnerand  can you please help me with this issue .......

**Comment by wagnerand** [comment]
Please see the comments I wrote earlier.

**Comment by wagnerand** [comment]
We triaged this in our meeting and deemed it a good first bug.
Mentor: @eviljeff  (could you please add some info on what a fix involves?)

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by lavish205** [comment]
@eviljeff I would like to work on this bug.

**Comment by eviljeff** [comment]
The fix is basically the same as #7836 but in devhub for icons. Change https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/views.py#L1015 to not do `-1` and then add a test to TestEditMedia in https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/tests/test_views_edit.py#L664

**Comment by lavish205** [comment]
I'm working on it.

**Comment by vcarciu** [comment]
Verified as fixed : 
![smaller4mega](https://user-images.githubusercontent.com/1583842/43082030-b344e55e-8e9b-11e8-9c2e-7e687607e0b4.png)
