### ISSUE TITLE
Save newly uploaded versions into git repo

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8657]
* Create a repo per add-on if one doesn't exist.
* The incoming versions changes should take precedence in the case there are any conflicts.
* The revision committed to git should reflect the contents of the uploaded zip

Feel free to break this down into more issues in the same project if needed.

We will also need to consider where and how to store source files.

**Comment by EnTeQuAk** [comment]
I split this into a few more issues as part of https://github.com/orgs/mozilla/projects/23
