### ISSUE TITLE
Statistics for a LWT need to migrate to static theme too 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8662]
Follow on from #8267 

We need to migrate all the usage statistics for the lightweight theme when it becomes a static theme.  We also need to continue to count pre-migrated users (i.e. a user who has the LWT installed and doesn't update to the static theme for whatever reason).

**Comment by eviljeff** [comment]
LWT don't have a concept of "downloads" so we can't fill in weekly/total downloads.  (Thankfully we don't expose download counts in the API directly)

**Comment by ioanarusiczki** [comment]
Verification on -dev and -stage is blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1450108
Installed https://addons-dev.allizom.org/en-US/firefox/addon/lilac-prediction/?src=search by two users but the number of downloads on -dev and -stage are not updated, issue is tracked here.
Migrated LWT is an upcoming project that did not land in prod yet, for now it is still under test on -dev.

**Comment by AlexandraMoga** [comment]
@eviljeff I think we should actually be able to verify this fix if another set of lwt are migrated, right?
I have two examples in mind:
https://addons-dev.allizom.org/en-US/firefox/addon/eco-theme/?src=search
https://addons-dev.allizom.org/en-US/firefox/addon/yahoo-persona/?src=search

**Comment by eviljeff** [comment]
@AlexandraMoga done

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

**Before**
![image](https://user-images.githubusercontent.com/31961530/43062066-4827a648-8e60-11e8-8477-5ba2b1361210.png)

**After**
![image](https://user-images.githubusercontent.com/31961530/43062132-7c01b01c-8e60-11e8-882d-80a4e0d6f01e.png)


![image](https://user-images.githubusercontent.com/31961530/43062145-8262ab0a-8e60-11e8-8797-6c0f06d49815.png)
