### ISSUE TITLE
Expose FxA URL (for editing a user email) in the API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#8674]
See: https://github.com/mozilla/addons-frontend/issues/5390

---

The frontend does not know anything about FxA and we don't have a specific config for each environment. In -prod, we use `/accounts/login/start/` for authenticating a user and addons-server does the correct FxA redirect (given a `config` query parameter).

The profile edit page has a link to FxA so that a user can edit their email address. In the new user profile, this link is hardcoded and points to the -prod FxA instance.

Since addons-server has the config for FxA and knows which FxA instance to use depending on the enviroment, I would like to expose this config somewhere in the API.

I guess, it would make sense to return this URL in the user profile response.

@eviljeff wrote:

> Mention if you just want the server address (like frontend shows now) or the full url with params for email and fxa_id (like legacy shows)

It would make sense to have the full URL for editing the email on FxA, I suppose, so it could be a new property like `fxa_edit_email_url`.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:
When hitting the `/api/v4/accounts/profile/` or the `/api/v4/accounts/account/(int:user_id|string:username)/ `endpoints with an authenticated user, the new `fxa_edit_email_url` parameter is present in the response and points to the correct environment. 

![image](https://user-images.githubusercontent.com/31961530/47361995-09c73700-d6dc-11e8-868b-109e21ee1b21.png)
