### ISSUE TITLE
Update reviewer risk tier threshold

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8676]
Following the re-weighting in #8436, we also need to change the thresholds for the risk tiers.

Highest: 275
High: 175
Medium: 90

The only direct impact this has is on points, so in order to test this, just submit an add-on with the respective weight, review it and check that the right amount of points were given.

**Comment by AlexandraMoga** [comment]
@wagnerand here is an overview of the old model:

* `REVIEWED_EXTENSION_HIGHEST_RISK`: add-ons with `weight > 150` get 140 points.
* `REVIEWED_EXTENSION_HIGH_RISK`: add-ons with `150 >= weight > 100` get  120 points.
* `REVIEWED_EXTENSION_MEDIUM_RISK`: add-ons with `100 >= weight > 20` get 90 points.
* `REVIEWED_EXTENSION_LOW_RISK`: add-ons with `20 >= weight` get no points.

Is your new model something like this:
* `REVIEWED_EXTENSION_HIGHEST_RISK`: add-ons with `weight > 275` get 140 points.
* `REVIEWED_EXTENSION_HIGH_RISK`: add-ons with `275 >= weight > 175` get  120 points.
* `REVIEWED_EXTENSION_MEDIUM_RISK`: add-ons with `175 >= weight > 90` get 90 points.
* `REVIEWED_EXTENSION_LOW_RISK`: add-ons with `90 >= weight` get no points.

**Comment by AlexandraMoga** [comment]
@wagnerand  the reward system seems to be working on the old model still
After some tests on -dev, this is what I've observed:

- add-ons with weight **over 150** - receive 140p
- add-ons with weight **over 100** up to **=150** - receive 120p
- add-ons with weight **over 20** up to **=100** - receive 90p
- add-ons with weight **under =20** - receive no points

**Comment by wagnerand** [comment]
Sorry I misread your earlier comment, I thought you had verified it already. It seems like there are some issues with deploying, I'll let you know once it's resolved.

**Comment by AlexandraMoga** [comment]
@wagnerand oh, sorry for the confusion, It was a statement indeed. I wanted to make sure that the expected results were clear.

**Comment by vcarciu** [comment]
Verified as fixed on Stage
