### ISSUE TITLE
Delete obsolete access groups

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8697]
I went through the access groups and there are quite a few which are no longer in use:

- `Developers`: Looks like Marketplace cruft.
- `Developers Credits`: Credits page is gone.
- `Engagement`: An old group that allowed to export email addresses on an admin page, which was not referenced anywhere, introduced in https://bugzilla.mozilla.org/show_bug.cgi?id=797920.
- `Monolith API`: Not sure what this was about, it's not referenced anywhere. Marketplace?
- `OAuth Partner: Flightdeck`: Not sure what this was about, it's not referenced anywhere. Marketplace?
- `Other Contributors Credits`: Credits page is gone.
- `Past Developers Credits`: Credits page is gone.
- `Persona Reviewer MOTD`: The permission this group uses is not defined (and thus not used) in the code.
- `QA`: Unused group, might have been used at some point for some data dump script that seems to be lost now.
- `Revenue Stats Viewers`: Not referenced anywhere. Marketplace?
- `System Administrators`: Description says "Preserved through permissions migration for future use.". It was created in 2012, is not used in the code and is empty. Remove?

@jvillalobos, @diox, @eviljeff for feedback. Thanks!

**Comment by diox** [comment]
> Monolith API: Not sure what this was about, it's not referenced anywhere. Marketplace?
> Revenue Stats Viewers: Not referenced anywhere. Marketplace?

Yes, those are from Marketplace.

> OAuth Partner: Flightdeck: Not sure what this was about, it's not referenced anywhere. Marketplace?

Not from Marketplace (https://wiki.mozilla.org/AMO/FlightDeck) but obsolete

> Developers: Looks like Marketplace cruft.

Technically not just Marketplace but obsolete, yes.

**Comment by wagnerand** [comment]
Cool, any objections on deleting `System Administrators`?

**Comment by jvillalobos** [comment]
That group was originally going to be used for #7249, but I think we decided to go a different direction.

**Comment by wagnerand** [comment]
I'll add the "QA" group which at some point might or might not have been used for moving data dumps from prod to dev but @diox said we don't have to care about it.

**Comment by wagnerand** [comment]
QA: Check that the groups mentioned in https://github.com/mozilla/addons-server/issues/8697#issue-337004047 do no longer exist on the groups admin page.

**Comment by vcarciu** [comment]
Verified as fixed for all groups from description in AMO-dev.
