### ISSUE TITLE
Remove Limited Reviewers

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8698]
The "Limited Reviewers" group applies to legacy queues only and is no longer relevant. Let's remove it.

**Comment by wagnerand** [comment]
QA:

* Check that the "Limited Reviewers" group is gone from the groups admin page
* Check that you can approve/reject a legacy and a webextension add-on version.

**Comment by vcarciu** [comment]
Verified as fixed. "Limited Reviewers" group is not available anymore and I was able to approve\reject both legacy and webextensions versions.
