### ISSUE TITLE
Removed localizedStrings from the Collections model

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#8701]
We don't really need any localizedStrings in the Collections model, and three in particular are causing issues:

- Collection.name
- Collection.description
- CollectionAddon.notes (see #7832, which can now be considered a duplicate of this)

This issue is to convert these (and perhaps any others deemed suitable) to proper CharFields.

Once complete, https://github.com/mozilla/addons-frontend/issues/5433 should be fixed as a result.

**Comment by eviljeff** [comment]
Just to note, this would drop the ability to localise the name and description for _any_ collection - including Mozilla collections.

**Comment by eviljeff** [comment]
Fwiw, I'm working on a fix to the locale mess in the API level anyway.

**Comment by AlexandraMoga** [comment]
@eviljeff @bobsilverberg  just noticed that this issue also affects user comments in collections (i.e. leaving a comment for a specific add-on inside a collection). I suppose that section could also be taken in consideration when a fix is prepared.

**Comment by bobsilverberg** [comment]
FYI, @jvillalobos already commented about this at https://github.com/mozilla/addons-frontend/issues/5433#issuecomment-400839915, which is why I opened this issue in the first place.

**Comment by eviljeff** [comment]
@diox said:
> dropping localization for collections is not great IMHO
> they are user facing, it should be localizable

I agree, fwiw.

**Comment by jvillalobos** [comment]
Like with user reviews, I think localization in this context makes more harm than good. We don't localize Mozilla collections at the moment, and we could create localized versions as a workaround (as can other users who need localized collections).

**Comment by eviljeff** [comment]
implementation note: Collections are the only place we write to a `TranslationSerializerField` so if we want to maintain that support for future use (e.g. an API based devhub) we should be aware that when changing the tests for the collection serializers/views we will be removing the only place we have real-world integration tests for setting/changing `TranslationField` attributes via the API.

**Comment by eviljeff** [comment]
As changing the response to always return a flat string, and never a dict, would be a breaking change to the API (public facing; and available without auth) we also shouldn't do this on `/v3/`.  #8899 has ideas about how to address the v3 / v4 api problem (but no resolution as yet).

**Comment by smayer97** [comment]
(coming from #8413)

Just want to highlight that because of the use of different locales in managing collections, notes were sometimes created under more than one for the same entry in a collection. I do hope that whatever solution is implemented, it takes this into account, e.g. merging them or something.

**Comment by smayer97** [comment]
Anything further on this?
