### ISSUE TITLE
Akismet spam log admin

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8705]
[Akismet PRD](https://docs.google.com/document/d/1mx27WOSr1_NJIb3dWg6tmq6WWJMgka8ExOIMeCDbi7Y/edit#). All spam requests and responses with Akismet must be logged. They must include all the data sent in the original API request. The log should be browsable and searchable in the AMO Admin tools.

For positive spam responses, there must be an option to report the response as “Ham” (false positive). For negative spam responses, there must be an option to report the response as “Spam” (false negative). It must not be possible to report a log entry more than once.

**Comment by eviljeff** [comment]
What fields would you want to be searchable?

**Comment by jvillalobos** [comment]
Filter by type (User Reviews, Collection Name, Collection Description, Listing Name, Listing Summary, Listing Description) and resolution (Approved, Rejected).

Search should apply to the content that was approved or rejected.

**Comment by wagnerand** [comment]
Can we add filters for "Ham" and "Spam" decisions as well, please?

**Comment by jvillalobos** [comment]
Do you mean filtering out the ones that have already been reported as ham or spam via the link?

**Comment by eviljeff** [comment]
QA: same as #8702, we will have wait until next week until -dev has the API keys to test this.
