### ISSUE TITLE
Localised response for discovery api is inconsistent

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8712]
If you make straight `/api/v4/discovery/` request in the results you get all the localised `addon.name` the developer has provided, as a dict, but `heading` and `description` are only sent in `en-US`.  We don't indicate that the `heading` and `description` response may be localised in the API docs.

If you request a particular lang,  `/api/v4/discovery/?lang=fr` you sometimes get `addon.name` in the locale requested, if the developer has provided it, and sometimes get `heading` and `description` in the locale requested, if the localisation community has localised the string already.  

We also use `addon.name` _in_ the `heading`.  With an addon that has ```name = {'en-US': `foo`, 'fr': 'lé foo'}``` and `default_locale = 'fr'` if you make a request such as `/api/v4/discovery/?lang=de` and `heading` has only been localised into `fr` so far, the response would be `<en-US text><fr name><en-US text>`, even though we _could_ output a complete response in `fr` or in `en-US`.  And we don't indicate to the client that this mixed response isn't actually `de`.

**Comment by diox** [comment]
IMHO even though it looks bad, this is mostly an edge case that requires documentation, not something we can fix.

Those translations depend on gettext content and not of the database, and it's not really meant to be used to fetch translations in all languages at the same time. It would be horribly inefficient to try to do so, and mostly useless to the only consumer of that API we care about, addons-frontend.

I'd also argue that the returned data for the `heading` in the example is somewhat inconsistent but not worth fixing either. It's the best output we can give for the language that was requested.

**Comment by eviljeff** [comment]
yeah I'm not sure how much we want to fix here, I was just documenting what I found when I was implementing the localisation changes in the API response.  The discovery endpoint is one that crafts it's own response, to an extent, and it's semi-localised but not in the same way as our Translated fields.

It wouldn't be very difficult to have it expose what locale was returned if we want it to be consistent though.

**Comment by diox** [comment]
> It wouldn't be very difficult to have it expose what locale was returned if we want it to be consistent though.

We should do that for v4, yes. I vaguely remember discussing that with someone and ending up not doing it, but I think it was just that at the time we didn't really see the value in that.

**Comment by AlexandraMoga** [comment]
I've looked at the `/discovery/` api both for the `v4` and `v5` versions - with focus on the `description_text` and `addon.name` translated fields -  and this is what I've observed:

- `addon.name`:
  - _(v4)(v5)_ `lang` not specified - returns all the available translations for the add-on name
  - _(v4)(v5)_ `lang` specified and translation available - returns the add-on name in the requested locale
  - _(v4)(v5)_ `lang` specified - translation not available - returns the add-on name in the `default_locale` 
- `description_text` (_without_ a custom description set in admin): 
  - _(v4)(v5)_ `lang` specified - translation available - returns one value for the add-on summary provided by the developer for the requested translation 
  - _(v4)(v5)_ `lang` specified - translation not available - returns one value for the add-on summary provided by the developer in the `default_locale` 
  - _(v4)_ `lang` not specified -  returns one value for the add-on summary matching the client's `Accept-Language` header - i.e. if the client accepts `de` and the add-on has a translation for `de`, this value is returned; if translation not available, the `default_locale` value is returned
  - _(v5)_ `lang` not specified - returns all the summary translations provided by the developer
  - _(v4)(v5)_ `lang` not supported - returns one value for the add-on summary matching the client's `Accept-Language` header - i.e. if the client accepts `de` and the add-on has a translation for `de`, this value is returned; if translation not available, the `default_locale` value is returned
- `description_text` (_with_ a custom description set in admin) 
  -  _(v4)(v5)_ `lang` specified - translation available - returns the value of the custom description added in Discovery admin for that locale
  -  _(v4)(v5)_ `lang` specified - translation not available - returns the value of the custom description added in Discovery admin in add-on's `default_locale` 
  - _(v4)_ `lang` not specified/ not supported -  returns one value for the custom description matching the client's `Accept-Language` header - i.e. if the client accepts `de` and the custom description has a translation for `de`, this value is returned; if translation not available, the `default_locale` value is returned

@eviljeff I found an inconsistency in `v5` when a custom description is used:
  - _(v5)_ `lang` not specified - returns the custom description in `en-US`, disregarding the `Accept-Language` header (mine was `de`) or the add-ons `default_locale` (also `de` for the example given below):

```
"description_text": {
      "en-US": "They add features to Firefox to make browsing faster, safer, or just plain fun."
            },
            "addon": {
                "id": 620338
```
Discovery item for this example: https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/130/change/ - the custom description has translations for other locales than `en-US`

The same goes when the `lang` requested is not available: 

```
            "description_text": {
                "en-US": "They add features to Firefox to make browsing faster, safer, or just plain fun.",
                "fa": null,
                "_default": "en-US"
```

**Comment by eviljeff** [comment]
>  I found an inconsistency in v5 when a custom description is used:
>
> * (v5) lang not specified - returns the custom description in en-US, disregarding the Accept-Language header (mine was de) or the add-ons default_locale

The existing behaviour with `Accept-Language` is more of an accident than design but I agree it's inconsistent.  I suppose we should take into account the add-ons default locale too (it's currently returning the DiscoveryItem default instead - assumed to be `en-US` because all the editorial copy will be entered in `en-US`). Can you file a follow-up?

> * description_text (with a custom description set in admin) 
>   * (v4) lang not specified/ not supported - returns one value for the custom description matching the client's Accept-Language header - i.e. if the client accepts de and the custom description has a translation for de, this value is returned; if translation not available, the default_locale value is returned

I couldn't replicate this re: the `default_locale` being taken into account on v4.  For stage either.  Only the request language (`Accept-Language`) is used or `en-US` otherwise.

**Comment by AlexandraMoga** [comment]
> I couldn't replicate this re: the `default_locale` being taken into account on v4. For stage either. Only the request language (`Accept-Language`) is used or `en-US` otherwise.

Yes, you are right. I've modified the result to make it accurate.
