### ISSUE TITLE
July 2018 Disco Pane content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#8723]
For the **19 July** push, please adjust Disco Pane programming to reflect as follows...

**Abstract Colorful Owl** by [candelora](https://addons.mozilla.org/firefox/addon/abstract-colorful-owl/)

**Leave a clean digital trail** with [Forget Me Not by Lusito](https://addons.mozilla.org/firefox/addon/forget_me_not/) 
Make Firefox forget website data like cookies and local storage, but only for domains you choose. 

**Improve videos** with [Enhancer for YouTube by Maxime RF](https://addons.mozilla.org/firefox/addon/enhancer-for-youtube/)
Enjoy a suite of new YouTube features, like cinema mode, ad blocking, auto-play, and more. 

**Strands of Gold** by [MaDonna](https://addons.mozilla.org/firefox/addon/strands-of-gold-by-madonna/)

**Block ads** with [uBlock Origin by Raymond Hill](https://addons.mozilla.org/firefox/addon/ublock-origin/)
A lightweight and effective ad blocker. uBlock Origin enforces thousands of content filters without chewing up a lot of memory.

**Up your emoji game** with Emoji Cheatsheet](https://addons.mozilla.org/firefox/addon/emoji-cheatsheet/) by Johann Hofmann
Dozens of amazing emojis for every occasion—just a click away.

**Phoenix in the Clouds** by [a205260](https://addons.mozilla.org/firefox/addon/phoenix-in-the-clouds/)

@muffinresearch @diox @EnTeQuAk

**Comment by AlexandraMoga** [comment]
Here is the updated discopane contend (as seen on -dev) after disabling the `disco-staticthemes-dev` switch:

![image](https://user-images.githubusercontent.com/31961530/42754906-f097bde8-88fe-11e8-90d3-8e57a0f15d09.png)

Final validation will be made in prod

**Comment by devaneymoz** [comment]
Sorry for a late-breaking change, but need to re-open to adjust one bit of content programming. Please swap in Privacy Badger for uBlock Origin. The rest of the page remains the same. Here's the new material:

**Stop sneaky trackers** with [Privacy Badger by EFF](https://addons.mozilla.org/firefox/addon/privacy-badger17/)
Block invisible trackers and spying ads that follow you around the web.

**Comment by eviljeff** [comment]
good thing we didn't push this live today as planned 😉

**Comment by vcarciu** [comment]
Verified as fixed in prod
