### ISSUE TITLE
Static themes are included in Add-ons developer instead of Theme artist on user's info card

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8725]
Transferring https://github.com/mozilla/addons-frontend/issues/5458

STR:
1. Load AMO dev and using a new account submit a static theme and approve it
2.  Go to view profile and observe the category displayed at the top of the page

Expected result:
Theme artist.

Actual result:
Add-ons developer.

Notes:
This issue is reproducible with FF60(Win10). 

![42091187-f9177120-7bac-11e8-8f21-67581cf7b3e5](https://user-images.githubusercontent.com/33448286/42204935-b7e09068-7eab-11e8-83cc-d636232f505e.png)

**Comment by diox** [comment]
More important than https://github.com/mozilla/addons-server/issues/8726 IMHO. Like in that issue, need to be careful about the implications of changing those properties, but we should do it.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10)

![theme artist](https://user-images.githubusercontent.com/33448286/42946587-ec541dc2-8b73-11e8-85a2-5e53f72ab83f.png)
