### ISSUE TITLE
Use custom heading and description for disco pane recommendations (entered through an admin tool)

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8734]
In the disco pane when we serve recommended add-ons from TAAR, for each add-on the heading and description are generated automatically from the add-on name and summary, respectively.

We want to be able to use editorial content even serving recommendations. That means:
- Preparing editorial content for a big list of add-ons. The list would be stored in database, allowing the team to update them in an admin made for this (with specific dedicated permission & group).
- Generating translations for that list when we extract strings to be translated
  - This itself means having an API to fetch the strings to be translated from prod's database, that the extraction process - which runs elsewhere - will use.
- Using the editorial content, translated if necessary, when serving the disco pane API

In a way this is similar to what was needed for https://github.com/mozilla/addons-server/issues/2448 and maybe it could replace having to hardcode the disco pane strings in our code every month. The idea being that the editorial team could then check whether translations are ready, preparing the content in advance, before enabling it as part of its curated list.

**Comment by diox** [comment]
Since django doesn't let you add custom gettext domains easily, I think the implementation of the extraction part will have to be a custom command that does something like:
- Calls the API
- Builds a fake source file with all the data
- Calls the regular extraction command

**Comment by diox** [comment]
This issue should be about the last bit: "Using the editorial content, translated if necessary, when serving the disco pane API". Other issues were filed about the previous steps (#8739, #8740, #8741)

**Comment by diox** [comment]
Inside the `DiscoveryItem` model that I'll be adding soon, the beginning of an implementation would look like:

```python

    @property
    def heading(self):
        """
        Return item heading (translated, including HTML) ready to be returned
        by the disco pane API.
        """
        addon_name = unicode(self.custom_addon_name or self.addon.name)
        authors = u', '.join(
            author.name for author in self.addon.listed_authors)
        url = absolutify(self.addon.get_url_path())

        # addons-frontend will add target and rel attributes to the <a> link.
        # Note: The translated "by" in the middle of both strings is
        # unfortunate, but the full strings are too opaque/dangerous to be
        # handled by translators, since they are just HTML and parameters.
        if self.custom_heading:
            addon_link = u'<a href="{0}">{1} {2} {3}</a>'.format(
                url, addon_name, ugettext(u'by'), authors)

            value = self.custom_heading.replace(
                '{start_sub_heading}', '<span>').replace(
                '{end_sub_heading}', '</span>').replace(
                '{addon_name}', addon_link)
        else:
            value = (
                u'{0} <span>{1} <a href="{2}">{3}</a></span>'.format(
                    addon_name, ugettext(u'by'), url, authors))
        return value

    @property
    def description(self):
        """
        Return item description (translated, including HTML) ready to be
        returned by the disco pane API.
        """
        if self.custom_description:
            value = ugettext(self.custom_description)
        else:
            addon = self.addon
            if addon.type == amo.ADDON_EXTENSION and addon.summary:
                value = addon.summary
            elif addon.type == amo.ADDON_PERSONA and addon.description:
                value = addon.description
            else:
                value = u''
        return u'<blockquote>%s</blockquote>' % value if value else value
```

Then the `DiscoveryViewSet` can fetch the relevant items and the `DiscoverySerializer` can be simplified to just use those methods. To support the existing data from `data.py` we would then just need to:
1. Add a `position` field and order on it and maybe creation date as second field (creating relevant indices)
2. Add a migration adding current data from `data.py` in the database. Translations should already be there in the .po file!

**Comment by diox** [comment]
QA:
- https://github.com/mozilla/addons-server/issues/2448 is the issue for the editorial feed, you can focus on the recommendations part here. The main difference compared to before is that now, when a recommendation is returned, if the add-on had been entered in the discovery admin tool first, then it will use the text (and translations if present) from that tool instead of the default name & description of the add-on.

**Comment by AlexandraMoga** [comment]
We need assistance from the TAAR team in order to test this implementation. Currently disco pane  recommendations are not working as expected.

**Comment by AlexandraMoga** [comment]
Update form @muffinresearch 
>the release for taar shield v3 has been pushed back. There might be something to test tomorrow (which I can do) otherwise we'll just need to wait until the taar instance is back.
