### ISSUE TITLE
Build admin tool to enter custom heading and description for disco pane recommendations

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8739]
We need an admin tool to enter the custom heading and descriptions for add-ons in disco pane recommendations that will be used in https://github.com/mozilla/addons-server/issues/8734

This issue is just about building the database model and an admin tool with a special group that can only access that admin, to allow the editorial team to enter some data.

It needs to have the ability to enter and see:
- Add-on
- Custom name
- Custom heading
- Custom description

All are optional.

**Comment by diox** [comment]
The group with the permission is called `Discovery Recommendations Editors`. Once you have that permission, the `Discovery Items` section should be available in the django admin (`/admin/models/`)

**Comment by vcarciu** [comment]
Verified as fixed : 
![discoveryadmin](https://user-images.githubusercontent.com/1583842/42461554-6a8b5502-83a9-11e8-8629-2cd696a5c628.gif)
