### ISSUE TITLE
Build API to fetch custom heading/description for disco pane recommendations

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8740]
Follow-up to https://github.com/mozilla/addons-server/issues/8739

We need an API to fetch all the custom heading & descriptions for disco pane recommendations (in english!) that was built in https://github.com/mozilla/addons-server/issues/8739. It needs to make sure the add-ons are public, but should not require any specific permissions. 

The idea is to then use that API to generate a fake file that the strings extraction process will use to generate the .po file for translators.

It shouldn't be paginated, (should return everything) and only return data needed to generate the .po file. The order should be consistent across runs (maybe just order by item id)

**Comment by vcarciu** [comment]
@diox : Can you please add some STRs to this issue or mark it as "qa: not needed" ?

**Comment by vcarciu** [comment]
@diox : 
All items are displayed when hitting the API, but only "custom heading" and "custom description" fields are returned: 
![apidiscoveryresults](https://user-images.githubusercontent.com/1583842/42461857-46f5dada-83aa-11e8-9e44-dcd915a5d740.png)

Should we display the "custom addon name" and addon id too?

**Comment by vcarciu** [comment]
@diox : nevermind, I just saw that the results are correct in  http://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#editorial-content 

Thanks

**Comment by diox** [comment]
Yeah it's a little bit weird, but that's because the custom add-on name isn't meant to be translated, and this API only really exists to retrieve all content that should be translated.
