### ISSUE TITLE
Generate .pot file with custom heading/description strings for disco pane recommendations

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8741]
Once https://github.com/mozilla/addons-server/issues/8740 and https://github.com/mozilla/addons-server/issues/8739 are done, we need to modify the extraction process to integrate those strings into the extraction process.

Those strings will be entered on prod through the dedicated admin, and the script doing the extraction process should then call the prod API to fetch all strings, and add them to the .pot file. 

Since [django doesn't let you add custom gettext domains easily](https://code.djangoproject.com/ticket/6376),  I'm thinking it should just create a fake file that isn't under version control but still inside our repos, and then do the extraction as normal.

**Comment by EnTeQuAk** [comment]
> Since django doesn't let you add custom gettext domains easily, I'm thinking it should just create a fake file that isn't under version control but still inside our repos, and then do the extraction as normal.

How do you plan on using that file to actually expose these translations to the discovery pane? Or am I blind / misreading something?

**Comment by diox** [comment]
The disco pane API will fetch the english strings from the database, request a translation through `ugettext()`, which will then use the relevant `.po` file as normal. The temporary fake file will never be on our production servers, it's just to trick the extraction process into letting us have it in the `.po` files.

**Comment by diox** [comment]
Note: since the extraction process is going to need data from production but at the moment production doesn't have the database nor the API to fetch that data yet, I will add the command to the extraction processed commented out. The idea is to proceed like this:
- Before July 12th push:
  - Merge the PR for this issue, but with the extraction part commented out
  - Merge the PR #8775 for convenience
- Once July 12th push is done:
  - Uncomment the extraction changes, commit that to master.
  - Give the users that are going to need to enter the strings in english the permission they need by putting them in the `Discovery Recommendations Editors` group and giving them VPN access for the admin.
  - From that point they can start adding strings to the admin in `/admin/models/discovery/discoveryitem/`
  - Run the extraction as normal. Verify that it does pick up strings added to the admin. They should be in `src/olympia/discovery/strings.jinja2` (it's a gitignored file) and should then end up in `django.pot` and the various `.po` files with no translations yet, except if somehow the strings added match strings we already have
- Later:
  - Verify that translators are translating the strings. In the admin, a preview with translations in several key locales should be shown in each item change page. 

Not fully relevant to this issue, but might as well document that here, the last steps after all this are:
 - Make sure TAAR now returns the add-ons for which we have strings ready & translated.
 - Write and merge the code to use the strings in the Discovery Pane (#8734).
 - Enjoy translated editorial recommendations!

**Comment by vcarciu** [comment]
@diox : Can you please add some STRs to this issue or mark it as "qa: not needed" ?

**Comment by diox** [comment]
It's hard to test right now, so we'll leave QA out until it's all integrated.
