### ISSUE TITLE
Add a link to the blocking notice of Stylish to the addon page

### ISSUE THREAD

**Issue by sbraz** [mozilla/addons-server#8745]
Hi,
As discussed with @diox on IRC, it would be nice to add a link to the [blocking notice](https://blocked.cdn.mozilla.net/c635229f-7aa0-44c5-914f-80c590949071.html) of Stylish or the related bug to its former addon page.
I initially received the wrong notice which mentioned that I had to update it so my first reaction was to check https://addons.mozilla.org/en-US/firefox/addon/stylish/ which returned a 404. An informative message would have helped.

**Comment by eviljeff** [comment]
fwiw, I think the last time we did this we hard-coded the add-on id.  (I can't remember which add-on it was now; if it's still valid; or if it what we do in the API)

**Comment by diox** [comment]
Stylish is no longer entirely disabled.
