### ISSUE TITLE
Users with Addons:Edit permission will have an unusable "Reviewer Tools" option under username dropdown menu

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#8750]
Steps to reproduce:
1.In Admin pages, add an user to a group with only Addons:Edit permissions
2.Login to amo-dev using the user from step1
3.Go to Username dropdown menu and press the Reviewer Tools option

Expected results:
The user should not have the reviewer tools option or at least it should work

Actual results:
Option is available and "Oops! Not allowed." message is displayed when trying to use it

Please see a video for this bug : 
![addonsedit](https://user-images.githubusercontent.com/1583842/42289331-9110948e-7fc7-11e8-82e9-92c9e5880fc0.gif)

**Comment by eviljeff** [comment]
@vcarciu this looks like a frontend issue so can you file there?
(we can re-open if it turns out its due to a faulty API response)
