### ISSUE TITLE
Remove ability to choose different platforms for new add-ons

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8752]
We discussed this last year during our All Hands, we should remove the ability to choose different platforms for WebExtensions.

Currently, we generate a new copy of the Add-ons XPI for each selected platform or for every platform in `SUPPORTED_PLATFORMS_CHOICES` (android, linux, mac, windows). The amount of add-ons that uploaded different XPIs in a later step for one of the platforms it supports is very small.

We should start disabling generation of new platform-copies and remove the choice from the devhub flow and investigate and clean up legacy add-ons in a later step. Or, work with a workaround to support both in reviewer tools for now and just let them die out once legacy add-on support runs out.

I should note that this touches a lot of places, we even have the platform choice in the new addons-frontend search, api, legacy api. We have support for different platforms in stats but that should stay imho.

@diox @eviljeff @jvillalobos any opinions/ideas about that?

On the other hand, there are some differences between how WebExtensions work on Android and Desktop, e.g what APIs can be used etc. I'm not sure but this seems to be part of the discussion around platforms.

**Comment by wagnerand** [comment]
I think we still need *Desktop* vs *Mobile* because of differences in API/platform support.

**Comment by eviljeff** [comment]
Once legacy addons are gone I don't think there's any reason to keep multiple platforms (and so multiple `File`s per `Version`).  iirc from the All Hands (and previous discussions) there was a general consensus about that too as multiple files only being useful in extreme edge cases with webextensions.

We should keep multiple **applications** (Firefox Desktop; Firefox for Android; +currently Thunderbird and Seamonkey which will be gone very soon) though.  Having the ability to differentiate application support should cover the API/usefulness differences between Android and Desktop.

**Comment by jvillalobos** [comment]
This is pretty much the same as the last task in https://github.com/mozilla/addons-server/issues/7825. To reiterate my view on this, I think compatibility with Android should just be a checkbox that affects the listing, rather than individual versions. That frees us from having to deal with platforms/applications on upload (once we remove Tb and SM, as eviljeff pointed out).

**Comment by diox** [comment]
> compatibility with Android should just be a checkbox that affects the listing, rather than individual versions

I'm all for that (lots of opportunities to remove clunky code when doing it!), but I think we should get rid of platform first, then worry about simplifying the Android support into a single listing-level checkbox later in a separate issue.

**Comment by EnTeQuAk** [comment]
So, looking at this more closely, this is what my current plan regarding this would be:

Some stats to refresh our memories: https://sql.telemetry.mozilla.org/queries/58687/ -> There are only 43 add-ons where their `current_version` has a different hash for at least one platform, so that they uploaded for at least one platform a separate file than for others.

The number reduces drastically if you filter by webextensions only and even more if filtered by status. Some of them are approved, public and webextensions though.

So, looking at these numbers I feel like it'd be safe to simply remove the platform choosing from the addon submission dialog as a first step.

@jvillalobos does this need some developer communication? I'd be interested if the add-ons that have chosen to upload different files for different platforms did so by choice or accidentally and if we can get them to revert that and submit one file for every platform.

**Comment by jvillalobos** [comment]
We still want it to be possible to choose if an add-on supports Android or not. That shouldn't require file duplication, though.

Making those changes on submission doesn't require reaching out. Separately, if we need to make changes to existing versions, then we do need to contact the developers about it.

**Comment by EnTeQuAk** [comment]
Marked as "qa: extra" to give this a bit more testing than usual.

QA:

* https://github.com/mozilla/addons-server/pull/9362 shows how this works / looks like (see screenshots)
* During add-on submission you can't select the platform anymore but you're selecting Firefox Desktop or Firefox for Android instead
* This selection is represented in the versions detail page in developer hub
* This selection is being **extended** by compatibility information in the `manifest.json` file, e.g if the developer adds `strict_max_version` and selects Firefox for Android during submission, the `strict_max_version` is applied for Android too

**Comment by AlexandraMoga** [comment]
Verified on AMO- dev with FF62, Win10x64 and Android 8.0

Verified:
- application selection during submission of new add-ons,  add-on updates (for new and pre-existing webextensions)
- submission of all add-on types 
- Manage status and versions page in dev hub - New file upload and multiple platform selection is no longer possible -> platform is set by default to "All Platforms" and can't be modified
- there is only one file generated when both Firefox and Firefox for Android are selected
- strict compat versions on add-on listing page - corresponding incompatibility banner displayed both on desktop and android (if applicable) 

@EnTeQuAk 
Observations:
- the icons for "Firefox" and "Firefox for Android" are a bit blurred. I believe they could be made a bit smaller also

![image](https://user-images.githubusercontent.com/31961530/45696916-4055e300-bb6d-11e8-91d7-cb41a573091a.png)


- in the previous format, during language pack and dictionaries submission, the 'Android option was completely disabled by default. In the current format, the 'Firefox for Android' checkbox is indeed unmarked by default, but if the user wanted to he could manually check it during submission. 

[Example of previous Platform selection]
![image](https://user-images.githubusercontent.com/31961530/45697071-97f44e80-bb6d-11e8-8d97-5b16fb2aa438.png)

**Comment by EnTeQuAk** [comment]
> It also looks like that's an old version of the Firefox icon.

Indeed, it seems that 8f559caf19181119cb9f006c29ab093693fc83f3 only updated the actual icon in the header but left others untouched.

I'll open an issue to fix that and also fix the blurry icons.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk the same old icon version is used in the Manage versions page. This section will also require updating to the new icon:
![image](https://user-images.githubusercontent.com/31961530/45733135-24dbee00-bbe8-11e8-865c-3d59b2f7ba78.png)

What about my second comment regarding Dictionaries and Language Packs?

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk the same old icon version is used in the Manage versions page. This section will also require updating to the new icon:

Yeah, #9451 is taking care of that.

> What about my second comment regarding Dictionaries and Language Packs?
…
> in the previous format, during language pack and dictionaries submission, the 'Android option was completely disabled by default. In the current format, the 'Firefox for Android' checkbox is indeed unmarked by default, but if the user wanted to he could manually check it during submission.

I opened https://github.com/mozilla/addons-server/issues/9456 to re-implement some of these checks.

**Comment by EnTeQuAk** [comment]
#9451 (updating firefox icon, making it less blurry) should be landing shortly on -dev and later today on -stage.

**Comment by AlexandraMoga** [comment]
Marking this as verified fixed as the issues mentioned have been filed as follow ups.
