### ISSUE TITLE
[Reviewer Tools] NoSuchKey Error

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#8756]
Recently I am getting a fair amount of NoSuchKey errors
Example:
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/1006374/file/static/js/main.d614e334.js#top

```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>en-US/firefox/files/browse/1006374/file-serve/static/js/main.d614e334.js</Key>
  <RequestId>****</RequestId>
  <HostId>*****</HostId>
</Error>
```

**Comment by EnTeQuAk** [comment]
Some files in that file work perfectly fine, e.g https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/1006374/file/asset-manifest.json#top

So the flow here is this:

If you click on "Download FILENAME"

You're opening…

* `https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/1006374/file-redirect/asset-manifest.json` 
* 302 to `https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/1006374/file-serve/asset-manifest.json?token={UUID}`
* 301 to `https://addons.mozilla.org/en-US/firefox/files/browse/1006374/file-serve/asset-manifest.json?token={UUID}
* 301 to `https://addons.cdn.mozilla.net/en-US/firefox/files/browse/1006374/file-serve/asset-manifest.json?token={UUID}`
* This then get's served by CloudFront

This works for the mentioned `asset-manifest.json` (which is quite small) but doesn't work for `https://addons.cdn.mozilla.net/en-US/firefox/files/browse/1006374/file-serve/static/js/main.d614e334.js?token={UUID}` - that file is >1MB big for example.

@bqbn how does the CDN serve these files? Directly from EFS?
