### ISSUE TITLE
Not all static images can be found during compress

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8760]
![screenshot from 2018-07-05 12-02-26](https://user-images.githubusercontent.com/139033/42316926-528ad786-804b-11e8-8b4d-5d95090be8dc.png)

Currently, there are one or a few more images missing from the legacy frontend page and a call to `update-assets` with an empty `site-static` folder raises a few "Image could not be found" errors.

This is a regression from #8532

**Comment by vcarciu** [comment]
Another possible related issue is that rating stars in legacy pages are invisible : 
![rating](https://user-images.githubusercontent.com/1583842/42324991-8f409d1a-806d-11e8-950b-8f77a51100bc.png)

**Comment by EnTeQuAk** [comment]
This is heading to -dev and -stage. I'll update the issue once they're there

**Comment by EnTeQuAk** [comment]
This is on -dev and -stage now.

**Comment by vcarciu** [comment]
Verified as fixed on AMO Stage and legacy frontend in multiple places.
