### ISSUE TITLE
We should prevent file-uploads for invisible extensions.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#8763]
### Describe the problem and steps to reproduce it:
File [1005816](https://addons.mozilla.org/firefox/downloads/file/1005816/robotext-2.7.6-an+fx.xpi?src=reviewer) return a 404, which is a download link from this [review page](https://reviewers.addons.mozilla.org/en-US/reviewers/review/robot-ext)

### What happened?
It has been found that this extension is invisible. 

### What did you expect to happen?
We should prevent file-uploads for invisible add-ons.

### Anything else we should know?
@wagnerand is aware of the technical details related to this issue.

**Comment by jvillalobos** [comment]
How was the review page reached? Did it show up in the post-review list?

Was the status of the version `Approved`?

Would the same thing happen if an add-on listing is made invisible after uploading?

**Comment by spoji** [comment]
> How was the review page reached? Did it show up in the post-review list?

Via email notification.

> Was the status of the version Approved?

Version was in "Awaiting Review" mode. The auto-review system didn't run.

> Would the same thing happen if an add-on listing is made invisible after uploading?

I don't have enough knowledge of addons-server code to answer this one.

**Comment by jvillalobos** [comment]
Dupe of https://github.com/mozilla/addons-server/issues/4025
