### ISSUE TITLE
[Reviewer Tools] Does not show all the files

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#8772]
Example:
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/987953/
```
META-INF
css
fonts
img
  option.html
  shortcuts.html
  whitelist.html
```

**Comment by EnTeQuAk** [comment]
I'm going to close this as we seem to be able to produce a usable MVP for the file-viewer in the near future and porting the old file-viewer to the git-backend seems to be unnecessary work.
