### ISSUE TITLE
Add preview of the content in disco pane recommendations admin tool

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8775]
In the disco pane recommendation content admin built in #8739, add some kind of preview that would allow people with access to the change page to see what the content looks like once rendered and translated. Add something to see if a translation is present in the major languages we support.

**Comment by diox** [comment]
Should look like this when translated data is entered: 

![discoveryitems](https://user-images.githubusercontent.com/187006/42525781-4f7e8b64-8474-11e8-9794-ba2188f5ee37.png)

**Comment by vcarciu** [comment]
Verified as fixed  : 
![discoveryitem](https://user-images.githubusercontent.com/1583842/42581477-8002f164-8535-11e8-9890-3d247d168790.png)
