### ISSUE TITLE
Implement a code-search across all Add-ons

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8786]
This issue is a meta-issue to track ideas around implementing a code-search across all add-ons.

Goal: We want to allow admins (and maybe others for statistical research?) search across Add-ons and get information about malicious add-ons, find usage patterns etc.

…wip… will be completed on Monday, I just opened this to enter my shower-thoughts :eyes:

**Comment by EnTeQuAk** [comment]
Shower thought: Once #8751 and #8753 (and following issues) are implemented it may be relatively easy to implement a first step towards a more sophisticated search engine. We could run [ripgrep](https://github.com/BurntSushi/ripgrep) via celery in batches across all Add-ons (or a subset that is specified via filters) to implement a first experimental version. That may already be faster than current approaches because it can be scaled up and parallelized much more effectively.

**Comment by wagnerand** [comment]
*ripgrep* already makes use of heavy parallelization, so I am not sure whether splitting it up in batches will make it any faster. At the end of the day, the bottleneck will probably be the filesystem.

**Comment by EnTeQuAk** [comment]
I'm closing this one as we're investigating this through other channels.
