### ISSUE TITLE
API: add sorting parameter "name"

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#8789]
### Describe the problem and steps to reproduce it:
Visited the [Available sorting parameters](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-search-sort) section in the API page.

### What happened?
It lacks the **name** parameter.

### What did you expect to happen?
I need it to download add-on data alphabetically.

**Comment by diox** [comment]
Because of the second part of my sentence: we don't want to document it now because its unreliable right now. It will be documented once the issue I linked is fixed.

**Comment by davidhedlund** [comment]
> It will be documented once the issue I linked is fixed.

I was just worried that you will forget about it but I trust you know. Thank you.
