### ISSUE TITLE
Warn about clutter in Name

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#8790]
### Describe the problem and steps to reproduce it:
Downloaded JSON files and discovered that it's possible for developers to stylize their add-ons name. 
Examples:
```
- = Flash Video Downloader - YouTube HD Download [4K]
– = Ghostery – Privacy Ad Blocker
— = Ecosia — The search engine that plants trees!
: = Web of Trust, MyWOT/WOT: Website Reputation Rating
() = Full Web Page Screenshots (♥♥♥♥♥)
, = Nimbus Screen Capture: Screenshot, Edit, Annotate
```

I think name.<language> (see name.en-US at https://addons.mozilla.org/api/v4/addons/addon/fireshot/ for example) should be clean because with stylized titles we need to modify them to give them the proper page name at directory.fsf.org.

```
name=$(echo "$name" | sed '
s/ — /\n/g;
s/ – /\n/g;
s/ - /\n/g; # looks identical to the prevoius line but is unique
s/: /\n/g;
s/(/\n/g;
s/,/\n/g;
' | head -n 1 | sed 's/ $//');
```
This is of course no guarantee since we will import thousands of add-ons.

### What did you expect to happen?
Can you please add a question mark to the **Name** field at  https://addons.mozilla.org/en-US/developers/addon/ENTRY/edit and describe this issue?
![screenshot at 2018-07-09 06 59 37](https://user-images.githubusercontent.com/6416073/42431459-d0dc11d4-8345-11e8-861a-1bb3f13527e2.png)

### Anything else we should know?
Example of the API "slug" name for "Web of Trust, MyWOT/WOT: Website Reputation Rating"
> wot-safe-browsing-tool

We don't want to use slug instead of names since that will break our URL standard. Also, it's not reliable to convert slugs by replacing initial small cases with capital cases, and dashes with white spaces. For the above example that would not include all capital cases (WOT):
> Wot Safe Browsing Tool

**Comment by diox** [comment]
Developers are free to use name however they see fit, that's why the slug field exists. The fact that it breaks how add-ons should be displayed on an external website is not AMO's responsibility. I don't expect developers to suddenly start changing their names to support your use-case.

**Comment by davidhedlund** [comment]
> Developers are free to use name however they see fit, that's why the slug field exists.

The slug field is as bad in my example.

**Comment by davidhedlund** [comment]
> Developers are free to use name however they see fit

I didn't say anything against that. I suggested that you could add a question mark (that will popup an infobox).

**Comment by davidhedlund** [comment]
@diox This issue affects everyone who want to make proper MediaWiki URL's.

**Comment by EnTeQuAk** [comment]
> @diox This issue affects everyone who want to make proper MediaWiki URL's.

Which limits the number of users a lot. I may even guess that you're the only one trying to do that.

The AMO API is being used by AMO and related services, that's how the data is exposed and that's it's primary focus. The add-on name is used for display purposes and the slug is there to be normalized and used in URLs.

Add-on names can contain unicode, can be stylized, can be translated and cointain Chinese, Japanese or other characters. All of them are hard to be properly encoded in an URL - although very much possible - but that's the task of the APIs user and can't be done by us.
