### ISSUE TITLE
Notify author of why their review was flagged

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#8801]
### Describe the problem and steps to reproduce it:
* As a site user, enter a review of an add-on
* As another site user, flag that review for moderation (example: _this is spam_)
* As a moderator, delete the review

### What happened?
The author is not notified

### What did you expect to happen?
The author of the review should be notified via email, including the reason for which it was flagged for moderation, and giving the amo-admins email address as a channel to discuss the deletion.

### Anything else we should know?
[Ratings & Reviews PRD](https://docs.google.com/document/d/1oUz9Ng9v159IPdW4UqHhbNspWa9m5SaicAAX5jU7OjA/edit#heading=h.veqos3dwovg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-164)

**Comment by eviljeff** [comment]
@jvillalobos should this be an activity mail email (so it has replies, etc, and the reply would be to the email catch-all admins) or just a flat email that mentions amo-admins@org as above?

**Comment by wagnerand** [comment]
This is part of DSA now.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-164
