### ISSUE TITLE
update api v3 autocomplete endpoint to include type in results

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-server#8803]
I *think* we decided the v3 api *could* be updated to include an additional field without much trouble : ), right?

Ideally, I would like the api autocomplete v3 endpoint to return the `type` as well so static themes can be targeted.

You can see the [FE issue discussion](https://github.com/mozilla/addons-frontend/issues/5277) for additional context

I did open an issue to discuss upgrading the api but I'm thinking that will take some time..

cc @eviljeff @diox

**Comment by vcarciu** [comment]
Can you please add some STRs to this issue or mark it as "qa: not needed" ?

**Comment by eviljeff** [comment]
you can check that `type` is included in the API response for requests such as:
https://addons.allizom.org/api/v4/addons/autocomplete/?q=hello
or
https://addons.allizom.org/api/v3/addons/autocomplete/?q=hello

**Comment by vcarciu** [comment]
Verified as fixed:
![tyoe](https://user-images.githubusercontent.com/1583842/42631331-957e3884-85e2-11e8-98be-a0a336f31089.png)

**Comment by zaw103852** [comment]
> you can check that `type` is included in the API response for requests such as:
> https://addons.allizom.org/api/v4/addons/autocomplete/?q=hello
> or
> https://addons.allizom.org/api/v3/addons/autocomplete/?q=hello
Update API v3
