### ISSUE TITLE
More search results in the API than on the website

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#8821]
### Describe the problem and steps to reproduce it:
Visited a few API pages:
* https://addons.mozilla.org/api/v3/addons/search/?page=1000&platform=linux&type=extension
* https://addons.mozilla.org/api/v3/addons/search/?page=1000&platform=linux&sort=users&type=extension
* https://addons.mozilla.org/api/v4/addons/search/?page=1000&platform=linux&type=extension
* https://addons.mozilla.org/api/v4/addons/search/?page=1000&platform=linux&sort=users&type=extension

The used URI parameters are documented in https://addons-server.readthedocs.io/en/latest/topics/api/addons.html
* platform
* type
* sort

### What happened?
The links lists search results on page 1000.

### What did you expect to happen?
They should not: https://addons.mozilla.org/en-US/firefox/search/?page=1&platform=linux&sort=users&type=extension
> Page 1 of 428

### Anything else we should know?
Both the API links and the website links lists 25 entries per page.

**Comment by EnTeQuAk** [comment]
The parameters are not identical, addons-frontend does a lot more than just querying `platform`, `type` and `sort`. It also takes compatibility into account and forwards that information to the API which will most certainly explain your difference in results.

For example, if you open the link to AMO in Chromium you get 24406 entries, very close to what the API returns.

**Comment by davidhedlund** [comment]
https://addons.mozilla.org/api/v4/addons/search/?page=429&platform=linux&type=extension&app=firefox&appversion=60

-- **&app=firefox&appversion=60** reduced the page number to identical number, 429. Solved! Thank you @EnTeQuAk

**Comment by davidhedlund** [comment]
@EnTeQuAk Why is the page number limited to 1000 without these parameters?

**Comment by EnTeQuAk** [comment]
That's because of the way we do pagination in ElasticSearch. Our search is backed by ElasticSearch and we currently do not use it's scroll API for pagination but use regular limit/offset queries instead.

Doing that, we have to make sure we do not exceed the `index.max_result_window` configuration in our cluster, which is currently set to `25000` which limits the number of pages we can represent at the moment.
