### ISSUE TITLE
Stylish 3.1.3 served from addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-server#8825]
From https://blocked.cdn.mozilla.net/i1900.html and https://new.reddit.com/comments/8wd5wu/-/ I understand that 3.1.1 is blocked. 

Given the absence of https://addons.mozilla.org/addon/stylish/ I'm surprised to find 3.1.3 served from AMO: 

- the upfront blue **Install for Firefox** button at https://userstyles.org/ leads to the `.xpi` 
- source is visible at https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.mozilla.org%2Ffirefox%2Fdownloads%2Flatest%2F2108%2Faddon-2108-latest.xpi

![2018-07-11 07 58 50](https://user-images.githubusercontent.com/192271/42555486-59068c9c-84e0-11e8-9b36-f6ac34abc174.png)

Mozilla bug [1472948 - Blocklist Stylish add-on - sends full page urls to remote server](https://bugzilla.mozilla.org/show_bug.cgi?id=1472948) is RESOLVED FIXED 

- I have had no time to investigate whether 3.1.3 is comparably troublesome.

**Comment by wagnerand** [comment]
That file is not actively served to users. That external website directly links to the file, but it's not signed and thus not installable.

**Comment by grahamperrin** [comment]
Thanks. 

> - the upfront blue Install for Firefox button at userstyles.org leads to the `.xpi`

Now: 

- there's a connection failure
- https://addons.mozilla.org/firefox/downloads/latest/2108/addon-2108-latest.xpi is not (no longer) found.
