### ISSUE TITLE
Add logging for TADAR responses to enable data analysis.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#8829]
We'd like to add logging of the response from TAAR so @mlopatka can do analysis without needing GA on the frontend side. 

@mlopatka or @crankycoder to add details of what data needs to be captured in the log and any specific format requirements.

**Comment by EnTeQuAk** [comment]
Please note that our log retention is only 30 days, it's been much less in the past.

**Comment by mlopatka** [comment]
@EnTeQuAk depending on how the log data is accessible we could write a regular job that munges and archives the log data for longer retention and analysis. But this is really good to know.

**Comment by EnTeQuAk** [comment]
Oh, maybe I lied. Our log retention in Kibana is 30 days, I think our raw logs are available a bit longer. @bqbn knows for certain.

**Comment by bqbn** [comment]
Standard retention for all services across the organization is documented here: https://mana.mozilla.org/wiki/display/SVCOPS/Logging+2.0+Access+Retention+and+Delays

In AMO case, we extended the retention for rawlogs, elasticsearch/kibana, and landfill to 31 days (already on -dev and -stage, yet to be on -prod in a couple weeks).

**Comment by muffinresearch** [comment]
> Please note that our log retention is only 30 days, it's been much less in the past.

Really good point 👍
