### ISSUE TITLE
Optimize how we serialize translations in the API

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8831]
While looking at one of our views with the highest db-query count I noticed that our `TranslationSerializerField` implementation doesn't make use of our translations helpers, e.g `attach_translations` etc. That makes it's implementation much simpler but is a pain for everything using translations in the API. So, whenever one or many add-ons are requested we have as many queries to the translations table as we have add-ons. Additional to that, some other fields that may have translations etc.

This is particularly bad in `/api/v4/accounts/account/mozilla/collections/change-up-your-tabs/addons/` which goes through all sorts of serializers and ends up querying translations for every add-on separately.

Optimizing translation-querying alone will bring down our query counts massively and speed up our API as well as bring down our database load.

**Comment by diox** [comment]
Note that this is only a problem with a client requests all translations - i.e. when they are not passing the `lang` parameter, which should not happen that often - basically only when they need to edit something. This is why I didn't care about optimizing this when I first wrote it.

**Comment by EnTeQuAk** [comment]
> Note that this is only a problem with a client requests all translations - i.e. when they are not passing the lang parameter, which should not happen that often - basically only when they need to edit something. This is why I didn't care about optimizing this when I first wrote it.

True, there are some other issues though that make the API issue translation related sql queries multiple times, duplicated. But maybe that's a separate issue. I'd leave this here for a general "investigate and fix it"-task
