### ISSUE TITLE
Optimize olympia.bandwagon.views:CollectionAddonViewSet.list performance

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8832]
Looking at NewRelic this view issues way too many database queries.

Looking more closely, this view queries quite a lot of things **per add-on** in the collection. So this should get optimized somehow to make the query-count reasonable and now grow or shrink with the amount of add-ons we are querying.

![screenshot from 2018-07-11 15-51-46](https://user-images.githubusercontent.com/139033/42576313-5b1917b0-8522-11e8-902c-16a7330d50d8.png)

**Comment by AlexandraMoga** [comment]
@EnTeQuAk could you please add a "qa:not needed" label to this issue?
Thanks
