### ISSUE TITLE
Add metrics for validation process and addons-linter wrapper

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#884]
This is the olympia part to https://github.com/mozilla/addons-validator/issues/62

Add in metrics so that we get an idea of how fast the `addons-linter` is.

There is the `devhub.validator` namespace we're using in statsd to track `amo-validator` times and stats, given that I think `devhub.addons_linter` might be a good namespace.

**Comment by tofumatt** [comment]
Excellent idea! 👍

**Comment by andymckay** [comment]
Supports mozilla/addons-linter#33
