### ISSUE TITLE
[Reviewer Tools] Review lock limit no longer necessary

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#8844]
I was the one who originally brought up the issue that resulted in the introduction of "Review lock limit" in the pre-Post-Review era.

While it poses no problem, I feel that it is no longer necessary and the extra processing can be avoided.

@kewisch

**Comment by kewisch** [comment]
Can you elaborate why it is no longer needed? Is the limit blocking you (or others) in any way?

**Comment by erosman** [comment]
As mentioned, "it poses no problem".  I thought that it would improve the processing (both server and client side) since it is not as relevant as it used to be in the old days.

I haven't seen any abuse for a long time (e.g. 75+ add-ons getting locked for 24-48 hours which was the reason behind it). ;)

**Comment by kewisch** [comment]
Given the locks are in place, it is obvious that not more than a few add-ons would be locked at a time, so we really have no way to know.

If engineering thinks this feature is in the way and proves to be a maintenance burden I think we should consider. What I'd like to avoid is that we remove the code for this feature and then it becomes a problem some day in the future.

**Comment by erosman** [comment]
OK.. no problem.. It was only a suggestion, You can close it then :)

**Comment by kewisch** [comment]
Thanks for the suggestion, I appreciate that you are putting thought into how to simplify addons-server! I'm going to close this for now as you mention, but we will definitely consider this when engineering is on a cleanup spree again!
