### ISSUE TITLE
Cleanup -dev, -stage and -prod sentry

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8847]
If possible, log all errors that need to be logged. See if there's stuff in there that needs to get fixed and cleanup all the old errors.

**Comment by EnTeQuAk** [comment]
I'm closing this now.

I cleaned up -dev and -stage and removed many many old entries in the -prod entry, fixed or unfixed. This way we can try to act more or less directly when something happens, I hope.

**Comment by AlexandraMoga** [comment]
Could you please add a qa:not needed label to this?
Thanks
