### ISSUE TITLE
Thunderbird and Seamonkey applications are available in Add-on Compatibility checker

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#8857]
STR:
1. Load dev hub and go to Tools-> Add-on Compatibility Checker
2. Open the Application drop down menu and observe the available applications.

Expected result:
Applications available: Firefox and Firefox for Android 

Actual results:
Thunderbird and Seamonkey are also available.

Notes:
Reproducible with FF61(Win10) on AMO dev and AMO stage.

![menu](https://user-images.githubusercontent.com/33448286/42643066-ee2b90e4-8600-11e8-98c3-3d16f15dfb0d.png)

**Comment by EnTeQuAk** [comment]
This will probably go away with #8958 or similar work.

**Comment by EnTeQuAk** [comment]
We removed the compatibility checker as part of https://github.com/mozilla/addons-server/issues/8857, closing

**Comment by vcarciu** [comment]
Verified as fixed : 
![compatchecker](https://user-images.githubusercontent.com/1583842/47092596-02adae00-d230-11e8-8807-4035c2bdeb87.png)
