### ISSUE TITLE
Belgium eID for Script-safe version of Mozilla Firefox 

### ISSUE THREAD

**Issue by rlobet** [mozilla/addons-server#8858]
### Describe the problem and steps to reproduce it:
Using the script-safe version of Mozilla, Firefox Add-On Manager looks up for Android versions of the Add-Ons

### What happened?
It can not install https://addons.mozilla.org/en-US/firefox/addon/belgium-eid/?src=search using the search engine https://addons.mozilla.org/en-US/seamonkey/search/?q=eid&cat=1%2C0&appver=&platform=windows

### What did you expect to happen?
Install the plug-in because this will be the only way to access the Belgium eID Smartcard Login on time.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
The add-on is not compatible with Android (according to the developer), so it won't appear on search results on an Android device.

The search link you posted (https://addons.mozilla.org/en-US/seamonkey/search/?q=eid&cat=1%2C0&appver=&platform=windows) is for the SeaMonkey browser, which is also not compatible with the latest versions of the extension. If you do the same search for Firefox (https://addons.mozilla.org/en-US/firefox/search/?q=eid&cat=1%2C0&appver=&platform=windows), then you should get the right results.
