### ISSUE TITLE
Edit profile page loads with Internal Server Error (KeyError)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#8860]
### Describe the problem and steps to reproduce it:
This is how I reproduced it but I don't know if it affects others:

- Open a fresh Firefox profile (cache cleared, etc)
- Log in to the site with an existing AMO account
- Choose *view my profile*
- Choose *edit my profile* which loads https://addons.mozilla.org/en-US/firefox/users/edit

### What happened?

I see an error banner saying *Internal Server Error* at the top of the edit form

### What did you expect to happen?

No error banners

### Anything else we should know?

This API request returns a 500: `GET https://addons.mozilla.org/api/v3/accounts/account/kumar303/notifications/?lang=en-US&wrap_outgoing_links=true`

https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4459482/

```
KeyError: 13L
  File "rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "olympia/accounts/views.py", line 570, in get_queryset
    user_nfn.notification.short: user_nfn for user_nfn in queryset}
  File "olympia/accounts/views.py", line 570, in <dictcomp>
    user_nfn.notification.short: user_nfn for user_nfn in queryset}
  File "olympia/users/models.py", line 572, in notification
    return NOTIFICATIONS_BY_ID[self.notification_id]
```

**Comment by kumar303** [comment]
As soon as I updated my profile (I uploaded a photo), the error stopped happening.

**Comment by kumar303** [comment]
> As soon as I updated my profile (I uploaded a photo), the error stopped happening.

Oh, weird. I see the error again. I guess it only went away temporarily.

**Comment by kumar303** [comment]
@eviljeff says this is related to https://github.com/mozilla/addons-server/pull/5252/files and only affects user accounts created before Olympia was split (2014-ish). Because of that and since the edit form still works (besides editing notifications), I'm downgrading the priority.

**Comment by kumar303** [comment]
> only affects user accounts created before Olympia was split (2014-ish).

Actually, it may only affect accounts that had this Marketplace related permission, `app_surveys` https://github.com/mozilla/addons-server/pull/5252/files#diff-e133eb2db571bbd677259a0acb85201bL135

**Comment by eviljeff** [comment]
```
select count(id) from users_notifications where notification_id not in (3,4,5,6,7,8,9,10,11,12);
```
6152 users affect on -dev

**Comment by AlexandraMoga** [comment]
I have checked the above scenario on AMO -dev and I could not reproduce the initial error anymore.
@kumar in order to make sure that the fix is fully tested it might be useful to double check with the account that reproduced the error. Thank you!

**Comment by kumar303** [comment]
I don't have an account that was reproducing the error on dev. I only have one in production.

**Comment by eviljeff** [comment]
I did, iirc.
