### ISSUE TITLE
File viewer can't find file for invisible or disabled add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8872]
(Follow-up on #8729)

The file viewer shows 404 for add-ons that are invisible or mozilla-disabled (and the file status is not disabled).

STR:
1. Submit an add-on.
2. Wait for auto-approval to approve the file.
3. In the dev-hub set the add-on to *Invisible*
4. Go to the reviewer tools page and try to access the file viewer for that file.

Expected results:

The file viewer should display the file contents

Actual results:

404

---

Testing the mozilla-disabled case is a bit harder: As step 3, go to the admin add-on manage page (`.../admin/addon/manage/`) and just set the add-on status to "Disabled by Mozilla". Do not change the file status.

**Comment by AlexandraMoga** [comment]
Currently blocked for testing by #8885

**Comment by AlexandraMoga** [comment]
I have tried both scenarios: 
1. setting add-on status to _Invisible_ from DevHub 
2. changing the status to _Disabled by Mozilla_ from Add-on admin page

In both cases, the File viewer for the two add-ons used as example could be accessed

Marking the issue as verified fixed on AMO -dev with FF61, Win10x64
