### ISSUE TITLE
replace usage of Addon.all_previews with Addon.current_previews

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#8878]
They largely mean the same thing (`all_previews` is solely Addon previews, but `current_previews` can contain Version previews if they are appropriate for that addon type), but they are confusingly used interchangeably - and I can't always remember which to use!

**Comment by AlexandraMoga** [comment]
Please add STR or the label "qa:not needed".
Thank you

**Comment by EnTeQuAk** [comment]
Just make sure that screenshots in the add-on details page still work and show up.

**Comment by AlexandraMoga** [comment]
No regressions found on the screenshot component. 
I've verified for existing screenshots and uploaded new screenshots from dev hub. 

Marking issue as verified fixed
