### ISSUE TITLE
New admin localization strings all end in `.user`

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#8889]
The newly extracted admin strings end in `.user`. Example: https://github.com/mozilla/addons-server/commit/496194902989dc581354dc7c89b884291c2e607d#diff-e2c4d2d50716449e73812fb1d76a6fbbR6452

Is that a typo?

**Comment by EnTeQuAk** [comment]
This got introduced in 8c03d67bba1, it's only the admin tools so not really a high priority. Should be fixed though.
