### ISSUE TITLE
Set a minimum length for abuse reports

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8891]
We get lots of garbage via abuse reports. Lots of them are one-word reports or random characters. We should have a minimum length to mitigate some of it, and push users to elaborate on what they mean in their reports. On the other hand, we don't want to force users to write a novel to report a spam listing.

Something like 32 characters seems enough to write a small phrase in English.

/cc @kewisch @wagnerand for comment.

**Comment by kewisch** [comment]
Sounds good to me, this sounds like a low-effort fix that may provide a quick win. Maybe we can also require a minimum amount of words? The average English word is about 5 letters, so with 32 characters that would be about 6 words.

**Comment by wagnerand** [comment]
Sounds good.

**Comment by diox** [comment]
A minimum can be enforced by the API, but the frontend will have to know about it as well (both to warn the user before submitting and also to handle API error if necessary)

**Comment by eviljeff** [comment]
This isn't strictly part of the Ratings and Review Flow 😉

**Comment by jvillalobos** [comment]
I don't think we need this anymore, given the new abuse reports in Firefox.
