### ISSUE TITLE
Allow to retrieve add-ons by author IDs when using the Search API endpoint

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#8901]
The Search API has a query parameter named `author` that allows to retrieve add-ons given a comma-separated list of author `username`: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search.

[An issue reported on addons-frontend](https://github.com/mozilla/addons-frontend/issues/5608) highlighted the fact that usernames changed (sometimes) and that using `username` was not always ideal.

It would be more reliable to pass a list of author IDs, so can we have either a new query parameter OR allow numeric IDs in the existing `author` parameter?

**Comment by diox** [comment]
We have the ids already in ES, but not currently indexed, so it would require a full reindex. Code-wise it'll probably look like what we do for `AddonExcludeAddonsQueryParam` which similarly supports both add-on slugs and ids.

**Comment by willdurand** [comment]
This will be useful for #8302 too.
