### ISSUE TITLE
License section from Add-on submission form has layout issues

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8902]
STR:

1. Log in to AMO -dev
2. Submit a new extension via add-on distribution page
3. After your add-on is validated, click on Continue to land on the add-on submission form - 
4. Scroll down to the license section and observe the layout

Actual result:
The list with license options are not correctly aligned

Expected result:
The list with license options is properly aligned 

Notes:
- the 'Privacy policy' select box is also misplaced 
- reproduced on AMO -dev with FF61, Win10x64
- regression from https://github.com/mozilla/addons-server/issues/5271

![image](https://user-images.githubusercontent.com/31961530/42819886-75debc34-89dd-11e8-9a1a-565284c3ad6a.png)

**Comment by EnTeQuAk** [comment]
This seems like some kind of regression of our changes to jingo… apparently restyle.less styles aren't applied at the very top anymore.

I'll look into this.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/43005884-d5ac0796-8c3c-11e8-8c5a-068bd920bf46.png)

![image](https://user-images.githubusercontent.com/31961530/43005890-de1b8de8-8c3c-11e8-8e7c-b6899f1fc2c4.png)
