### ISSUE TITLE
Allow django admin changes to files without having to update `jetpack version` and `reviewed` fields

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8903]
Every once in a while, we need to update file statuses manually, because sometimes the `admin/addon/manage` page is unavailable.

When we do, django admin requires `jetpack version` and `reviewed` fields not to be empty.

We should make them `blank=True` so they are optional.

**Comment by wagnerand** [comment]
STR:
1. Go to `/admin/models/files/file/<FILE_ID>` for a webextension file.
2. Change the "Status" to something else.
3. Click "Submit" and make sure the changes go through and the form does not throw an error that "Jetpack Version" and/or "Reviewed" fields are required.

**Comment by diox** [comment]
Note: I would warn against using this admin in production. It can directly modified fields that are, well... not supposed to be modified directly. There is nothing ensuring the proper callbacks are being fired when you modify core properties.

**Comment by wagnerand** [comment]
I have used this to disable public files for deleted add-ons, because I didn't fine another way to do it; `/admin/addons/manage/` is not available for those.

**Comment by diox** [comment]
Ok, it should be fine for such edge cases. I was more worried about changing statuses of files belonging to public add-ons, or fields that are automatically set at upload/validation time.

**Comment by AlexandraMoga** [comment]
Verifed fixed on AMO -dev with FF61, Win10x64

Files can be updated from `/admin/models/files/file/<FILE_ID>` without the need to add a value in the Jetpack and/or the Review fields

I've also noticed that the mentioned fields are now grayed out, to mark them as optional sections.

![image](https://user-images.githubusercontent.com/31961530/43070284-218b04e0-8e78-11e8-83ca-a9fd56235308.png)
