### ISSUE TITLE
'This slug is already in use' error is not dismissed when a new unique slug is entered in the required field

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8904]
STR:

1. Log in to AMO -dev
2. Submit a new extension via add-on distribution page
3. After your add-on is validated, click on Continue to land on the add-on submission form 
4. Enter a duplicate slug in the Custom URL field - i.e. _personas-plus_
5. Fill in the rest of the mandatory fields and click on Submit version
6. After receiving the 'This add-on slug is already in use' error, replace the previous slug with a new unique one
7. Click on Submit version again

Actual result:
'This slug is already in use' error is not dismissed and the user is unable to submit his add-on

Expected result:
Add-on is successfully submitted after a new unique slug is introduced

Notes:
- the user is also unable to cancel his submission  by clicking on 'Cancel and disable version' button
- the same behavior will occur when trying to correct a duplicate slug from DevHub - Edit information page
- reproduced on AMO dev with FF61, Win10x64

![slug error](https://user-images.githubusercontent.com/31961530/42821538-6d39c822-89e1-11e8-8e24-6606bc3c523c.gif)

**Comment by vcarciu** [comment]
@EnTeQuAk  : please note that once you receive the message that "This field is required" for categories during submission, then you will not be able to pass this step even if you check some categories. Probably same root issue.

**Comment by eviljeff** [comment]
I've noticed the same issue @vcarciu is talking about, I think.  
STR:
- make some mistake on the first submit: e.g. not selecting both categories - but doesn't have to be that- even not correcting the slug does it
- submit the page
- on the second load correct everything and see the `Submit Version` button isn't functional

**Comment by EnTeQuAk** [comment]
Yeah, this is actually the same issue as https://github.com/mozilla/addons-server/issues/8907

We have multiple `required` attributes rendered in the form that we don't want there.

**Comment by AlexandraMoga** [comment]
I've submitted an add-on and forced the errors mentioned above. After making the necessary corrections, the add-on version can be submitted.

@EnTeQuAk I will file a separate issue for the broken slug error message so you can handle it separately after the more urgent issues are solved. 

I'm marking this issue as verified fixed on AMO -dev with FF61, WIn10x64

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk I will file a separate issue for the broken slug error message so you can handle it separately after the more urgent issues are solved.

Awesome, thanks a lot!
