### ISSUE TITLE
The Source Code section from manage version page exposes two links that lead to the  file uploaded

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8906]
STR:

1. Log in to Developer Hub
2. Open the Manage status and Version page for one of your add-ons
3. Select one add-on version that you wish to manage
4. On the version details page, go to the Source code section and upload a file 
5. Save the changes and observe the information displayed in the Source code section

Actual result:
There are two links that point to the same file uploaded as source code 

Expected result:
There should be only one link (_View current_) which gives access to the source code uploaded

Notes:
- reproduced on AMO -dev with FF61, Win10x64
- probably a regressionn from https://github.com/mozilla/addons-server/issues/5271

[1] **AMO -dev**

![image](https://user-images.githubusercontent.com/31961530/42823545-7c953856-89e6-11e8-86ed-f3fd5203ca75.png)

[2] **AMO stage**
![image](https://user-images.githubusercontent.com/31961530/42823586-9226e782-89e6-11e8-9c93-cfa10b182e24.png)

**Comment by EnTeQuAk** [comment]
I honestly don't think this is worth a p2 either, it's certainly something we should fix but this can easily be assigned to a regular milestone and not be a p2 imho.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/43082055-c440730a-8e9b-11e8-9dfe-820fbd84fd5f.png)
