### ISSUE TITLE
Confirm Approval/Approve Content actions cannot be saved

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8907]
STR:

1. Log in to AMO -dev with a reviewer account
2. Access Reviewer Tools - Auto-approved addons queue
3. Pick an add-on from the list to review
4. Select the Confirm Approval option and Save your action

Actual result:
Nothing happens when the Save button is clicked

Expected result:
Confirm Approval action is successfully saved

Notes:
- reproduced on AMO -dev, FF61, Win10x64 for the Confirm Approval and Approve Content actions 
- @EnTeQuAk  might this also be a regression from the django upgrade?

![conf approval](https://user-images.githubusercontent.com/31961530/42827001-57e98856-89ee-11e8-9e29-8262a51c72da.gif)

**Comment by EnTeQuAk** [comment]
So, things don't seem to be completely broken somehow. Many of the other actions in that form still work.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64





![conf approval](https://user-images.githubusercontent.com/31961530/42865703-29e54956-8a73-11e8-994c-e3762fdba95a.gif)
