### ISSUE TITLE
Make sure 'required' attribute rendering works properly

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#8912]
This is a follow-up issue for https://github.com/mozilla/addons-server/pull/8910/ and https://github.com/mozilla/addons-server/pull/8911 to check these forms and others and make sure things are working as expected.

We should remove that flag eventually but that may be a bit more work than we can invest right now. Marking as p3 and code quality.

**Comment by diox** [comment]
Both translation fields and reviewer tools forms have some additional javascript going on that has an effect on whether or not the HTML field is required or not:
- In reviewer tools the "comments" field is set as required in the form, but some actions do not require comments and therefore disable that property inside `is_valid()`.
- For translation fields, there are dynamic fields being created, one for each locale (+ hidden init fields for javascript to use) and it doesn't not make sense for all of them to have the required attribute

So in both cases, I believe the solution will be to add some javascript to manipulate the property depending on user interaction.

**Comment by EnTeQuAk** [comment]
> So  in both cases, I believe the solution will be to add some javascript to  manipulate the property depending on user interaction.

That's probably the best idea, especially since the new Django 1.10+ behavior pushes input validation to the client instead of relying on the backend (only doing that as a safety net).
