### ISSUE TITLE
'This slug is already in use' error message is broken

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8914]
STR:

1. Log in to AMO -dev
2. Submit a new extension via add-on distribution page
3. After your add-on is validated, click on Continue to land on the add-on submission form
4. Enter a duplicate slug in the Custom URL field - i.e. personas-plus
5. Fill in the rest of the mandatory fields and click on Submit version
6. Observe the 'This slug is already in use' error message

Actual result:
The error message is broken - contains some unnecessary characters 

Expected result:
The error message is displayed with no format issues

Notes:
- also reproduced for the message shown when an invalid slug is introduced
- reproduced on AMO -dev with FF61, Win10x64
- looks like a regression from https://github.com/mozilla/addons-server/issues/5271

![image](https://user-images.githubusercontent.com/31961530/42865155-6d9a1494-8a71-11e8-803f-9056464b6def.png)

![image](https://user-images.githubusercontent.com/31961530/42865162-71508780-8a71-11e8-87aa-b6400c5109ca.png)

**Comment by diox** [comment]
It looks like it's because the form inherits from `TranslationFormMixin`, which has a specific `error_class` for its errors. The new django-1.11 compatible implementation messes up errors display for non-translated fields. (For translated fields, it does need to be a list, and displayed accordingly, because there might be more than one field, one for each locale)

**Comment by diox** [comment]
Incidentally, you can reproduce the issue with any other non-translated field in devhub that can display errors. Single checkboxes are not an issue, but for instance editing the Contributions URL field, entering an URL from an unsupported domain, will trigger the problem as well.

**Comment by vcarciu** [comment]
Reproducible also when trying to submit a theme without any header : 
![uuuu](https://user-images.githubusercontent.com/1583842/42941135-71914b0a-8b64-11e8-8c7c-586606072f17.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64
![image](https://user-images.githubusercontent.com/31961530/43006359-2cffd95e-8c3e-11e8-8ba7-64075b214cfa.png)
![image](https://user-images.githubusercontent.com/31961530/43006377-36d9ed2a-8c3e-11e8-8c71-bbdf39683ccc.png)
![image](https://user-images.githubusercontent.com/31961530/43006385-3b4c2990-8c3e-11e8-9e46-6ba75d9bd273.png)
![image](https://user-images.githubusercontent.com/31961530/43006395-40e6ebe2-8c3e-11e8-8154-556638704221.png)
![image](https://user-images.githubusercontent.com/31961530/43006399-445e46e4-8c3e-11e8-8e51-54d92e805ab7.png)
