### ISSUE TITLE
Remove filesystem cache

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8924]
A filesystem cache backend was added in c125bf9354bc84d94e8b6570092b3b3f05a26490 to get around cache eviction issues caused by cache-machine. cache-machine [is now gone](ceae9d4fd0ad3f2cbb8233fd494bd1248fe58854) so we should try to move back to having only one memcached cache backend for everything.

**Comment by vcarciu** [comment]
@diox : Can you please add some STRs for this bug or mark it as "qa: not needed" ?
