### ISSUE TITLE
After receiving "This field is required" message for an empty name for an unlisted addon, a new name cannot be saved

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#8932]
Steps to reproduce:
1.On AMO-Stage submit an unlisted webextension
2.Go to it's edit page and delete the name
3.Press "Save changes"
4.After receiving "This field is required" message try to enter a new name and save it again

Expected results:
Once the new name is added, the warning should not appear anymore and changes should be saved

Actual results:
Warning is still present and no name changes can be saved

NOTES:
Follow up from #8919 

Please see video for this issue : 
![unlistedemptyname](https://user-images.githubusercontent.com/1583842/42938489-25945bba-8b5b-11e8-8544-7506664b4a89.gif)

**Comment by diox** [comment]
Linking to #5271 as it's gotta be a regression from the django 1.11 upgrade.

**Comment by diox** [comment]
It definitely only happens for unlisted add-ons. Something that can't be a coincidence: the "Localize for" menu is absent... since the field is a translated field it must mess up with what's being submitted...

**Comment by vcarciu** [comment]
Now, if the name field is empty, the "Save changes" action will lead to a infinite waiting page.

**Comment by vcarciu** [comment]
I probably found the scenario from above exactly during a re-deploy, because now the problem magically disappeared . 
Closing and marking issue as verified.
