### ISSUE TITLE
Cannot make changes to Compatibility section if "Need at least one compatible application." warning was displayed 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#8935]
Steps to reproduce:
1.On AMO Stage, be sure that you submitted some webextensions with multiple versions
2.Go to Edit Listing page for one of your webextensions and then select the Manage Status&Versions page
3.Select one of the versions 
4.In compatibility section , delete everything and click save
5.When "Need at least one compatible application." warning is displayed select an application and click Save again

Expected results:
Changes are saved

Actual results:
Warning is still displayed and no changes are saved

NOTES:
Possible regression from #5271 

Please see a video for this issue : 
![compatapp](https://user-images.githubusercontent.com/1583842/42940700-1514af9e-8b63-11e8-8b3a-058725a1c751.gif)

**Comment by diox** [comment]
Also happens when there is only one version.

It's *not* caused by #5271 because it's currently happening on stage, and we rolled back the django upgrade on stage. It could be caused by https://github.com/mozilla/addons-server/issues/8344

**Comment by vcarciu** [comment]
Verified as fixed : 
![savingversions](https://user-images.githubusercontent.com/1583842/43149165-79742a2c-8f6f-11e8-80c5-1b6c3059d24f.gif)
