### ISSUE TITLE
Search add-on by numeric ID

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#8939]
Broken off from #8926. The old front-end supports entering a numerical ID for an add-on in an autocomplete search field so you get that unique result, rather than the (sometimes wrong) search results. It's a handy workaround when searching for things with somewhat generic names. There are [plans to fix search](https://github.com/orgs/mozilla/projects/17), but we should have this as a fallback. 

We need the search API to accept numerical IDs so it returns the exact match. It looks like it already supports GUIDs, but that wouldn't work for ~themes or~ search engine plugins.

**Comment by Abhi-khandelwal** [comment]
Hi @jvillalobos , Can I work on this issue?

**Comment by jvillalobos** [comment]
Generally we prefer people taking issues [labeled as good first bug](https://github.com/mozilla/addons-server/labels/contrib%3A%20good%20first%20bug), which are good for getting started.

But maybe @diox can give you some pointers for this one.
