### ISSUE TITLE
Remove collection stats, downloads, votes & watchers code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8944]
I removed most of the legacy collection features that were not about to be ported to the new frontend in https://github.com/mozilla/addons-server/issues/8538 but a few remains and need to be removed too.

In particular, we're seeing sentry errors because of obsolete `collection_votes` and `collection_watchers` tasks like this one: https://sentry.prod.mozaws.net/operations/olympia-stage/issues/4407005/

**Comment by diox** [comment]
Follow-up: https://github.com/mozilla/addons-server/issues/6496 will clean up the database once the models & fields are gone.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa: not needed" ?

**Comment by diox** [comment]
QA:
- Make sure collections still work across the site.

**Comment by AlexandraMoga** [comment]
I've checked both the legacy and the new collection feature and I did not observe any new issues around it.

For the legacy site, several collection actions (voting, following) have been removed:

- collection actions removed, except for the edit button
![image](https://user-images.githubusercontent.com/31961530/43571599-0d715bbe-9646-11e8-8eb8-b18d59974580.png)

- Collections I'm following menu removed:
![image](https://user-images.githubusercontent.com/31961530/43572273-c263f99a-9647-11e8-8715-09e2dac2fec3.png)
