### ISSUE TITLE
'Finish Theme' button from the static theme submission wizard will not be automatically disabled when one of the mandatory fields is empty

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8957]
STR:

1. Log in to Developer Hub
2. Go to Submit a new Add-on - Create a Theme to access the static theme submission wizard
3. Select a header image for your theme
4. Delete the value from the Theme Name field
5. Observe the Finish theme button 

Actual result:
Finish theme button is not automatically disabled when the mandatory field is empty

Expected result:
Finish theme button is automatically disabled when a mandatory field is empty

Notes:
- the button state will change to disabled only after you click on it
- once you add a Theme Name, the button needs to be clicked again in order to change its state to enabled
- reproduced on AMO -dev with FF61, Win10x64
- this issue was first mentioned in #7506 

![finish theme button](https://user-images.githubusercontent.com/31961530/43067657-9dd931c8-8e70-11e8-9964-04fc7e88a59d.gif)

**Comment by eviljeff** [comment]
_might_ be Django 1.11 related (i can't remember it happening before)

**Comment by eviljeff** [comment]
I think this is normal - the validation only happens once you finish editing the field (the `onchange` event is fired in JS)

**Comment by AlexandraMoga** [comment]
@eviljeff  this issue has been spotted before Django 1.11 (note that it was mentioned in #7506 which is an older issue)

**Comment by eviljeff** [comment]
Yeah, it's normal behaviour. The field is only validated after you finish editing, and that only happens after the focus moves out of the field.

**Comment by diox** [comment]
Using the [`input`](https://developer.mozilla.org/en-US/docs/Web/Events/input) event instead would probably fix this. I'll look into it. In any case, I don't think it's a p2.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![finish button fix](https://user-images.githubusercontent.com/31961530/43393269-228e9c44-93ff-11e8-81c1-1052959f8d08.gif)
