### ISSUE TITLE
Remove thunderbird code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#8958]
Now that thunderbird add-ons have moved away from AMO we should remove thunderbird-specific code from addons-server, except things like redirections and notices that developers/users should be using addons.thunderbird.net.

That includes the waffle added for the transition, relevant constants, etc. We should also make sure the database is cleaned up (we soft-deleted add-ons only compatible with thunderbird, so there may still be some work to do here)

**Comment by eviljeff** [comment]
🔥 🔥 🔥 🔥

**Comment by jvillalobos** [comment]
I think the P3 makes it clear, but I just want to reiterate that we shouldn't rush to this, in case something unexpected happens and we need to roll back Tb add-ons to AMO. A few weeks should be enough to know that the migration stuck.

**Comment by jvillalobos** [comment]
At this point it's fine to break anything related to Thunderbird or SeaMonkey on AMO.

**Comment by eviljeff** [comment]
#9683 removed all the code support... I'm tempted to say we can remove the actual Addons, Versions, Files, etc, with the legacy addon database clean up?

**Comment by eviljeff** [comment]
QA: though there are some (legacy-)site wide changes to remove all mention of Thunderbird, if anything is broken it will probably be stuff to do with categories and compatibility settings for Versions.  If there any known add-ons that previously were compatible with Firefox and Thunderbird it would be useful to check those in particular.

**Comment by vcarciu** [comment]
No regressions were found while testing scenarios around add-ons that previously were compatible with Firefox and Thunderbird.

Also Categories and Versions looks fine. 

I will mark the issue as verified.
