### ISSUE TITLE
Link to the statistics page should not be available to non-admin users when an add-on is disabled

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8965]
STR:

Noticed while verifying #8936 

1. Submit a new add-on with a regular developer account and wait for it to be auto-approved
2. Open a new separate window and log in to Reviewer tools with an Admin Reviewer
3. Look for the add-on submitted at step one and Force disable it
4. Switch back to the developer account and click on View Statistics Dashboard from the Edit Information page

Actual result:
The statistics dashboard will return a 404 if the add-on is disabled

Expected result:
The link for stats dashboard should be present only for admin users or for users with `Stats:View`

Notes:
 - the links for the stats dashboard should be hidden on the add-on listing page as well
 - also reproduced when add-on status is set as Invisible

![stats 404](https://user-images.githubusercontent.com/31961530/43081031-be1064ba-8e99-11e8-96bb-b027b98f32d2.gif)

![image](https://user-images.githubusercontent.com/31961530/43081016-b62e8e7a-8e99-11e8-8ea4-2ee5c2b68abe.png)

**Comment by EnTeQuAk** [comment]
Personally, I'd rather just disable the link and grey it out somehow and have an "alt"-tooltip or so to avoid people going crazy of "why are my stats not shown????!?!?!"

**Comment by EnTeQuAk** [comment]
This sounds like we should file an issue on addons-frontend related to that too

**Comment by AlexandraMoga** [comment]
This issue is still valid.
