### ISSUE TITLE
Documentation for translated fields is inaccurate

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#8969]
The documentation about [translated fields](https://addons-server.readthedocs.io/en/latest/topics/api/overview.html#api-overview-translations) doesn't correctly explain the case when `?lang=` is passed for GET requests. In the example of `?lang=en-US` it says the field will be returned from the API like:

```js
{
    "name": {
        "en-US": "Games"
    }
}
```

...but in two APIs I just checked (add-on detail and collection detail), the response looks like:

```js
{
    "name": "Games"
}
```

**Comment by diox** [comment]
You're looking v3 behavior but comparing it to the v4 API documentation... and [we changed that in v4 for consistency](https://github.com/mozilla/addons-server/issues/8794).

The [v3 API docs](http://addons-server.readthedocs.io/en/2018.05.17/topics/api/overview.html#translated-fields) match v3 behavior.
