### ISSUE TITLE
Remove a few redis related settings and some cron

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#8970]
### Describe the problem and steps to reproduce it:
It was mentioned on #remora at some point that with cache-machine being gone, one of the two redis cluster (known as amo-redis-3 cluster) is no longer used. And as a matter of fact, we don't see any traffic being sent to it for the past few weeks.

Can someone confirm the above is true?

If it is true, can we remove the following settings:

* REDIS_BACKENDS_CACHE
* REDIS_BACKENDS_CACHE_SLAVE
* REDIS_BACKENDS_MASTER
* REDIS_BACKENDS_SLAVE

All the above are configured to talk to the now-no-longer-used redis cluster (amo-redis-3) on -prod.

Plus, I believe the `clean_redis` cron (https://github.com/mozilla/addons-server/blob/master/scripts/crontab/crontab.tpl#L26) can be removed too.

### What happened?
We'd like to stop running the above said redis cluster across all environments if possible.

And of course we'll wait till the settings are removed before we do that on -prod.

### What did you expect to happen?
1. remove the above said settings if they can be removed, and 
2. stop running the no-longer-used redist cluster upon success of step 1

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by vcarciu** [comment]
@diox : should we test something around this or can we add the "qa: not needed" label?

**Comment by diox** [comment]
Nothing to test here
