### ISSUE TITLE
Ask users to state whether source code is necessary or not during submission

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8973]
Reviewers get many submissions with source code missing or incomplete. The reviewer team has worked with @MeridelW to make the source code submission section more prominent. It also asks users to state whether source code is necessary or not.

Details are in this [PRD](https://docs.google.com/document/d/10WsKUfiuQ7-WFwSjyuPIztkoRHwLR7lUrdMoJdvZlsU/edit).

/cc @jvillalobos

**Comment by jvillalobos** [comment]
Can you please include screenshots of how the new step looks, for reference?

**Comment by jvillalobos** [comment]
And, maybe it goes without saying, but please make sure the step is only added for extensions.

**Comment by jvillalobos** [comment]
The document doesn't say it, but I was under the impression that the new source code upload was going to be a new step in the submission flow, rather than a modification of the upload step. That's why I was suggesting to do it only for extensions, since after validation it would be clear which path to take.

Adding all of that info to a step that is already overloaded with messages doesn't seem like a good idea to me. I think we need to consider separating this into its own step, so it doesn't distract from everything else going on, and it's only shown we really necessary.

**Comment by wagnerand** [comment]
> The document doesn't say it, but I was under the impression that the new source code upload was going to be a new step in the submission flow, rather than a modification of the upload step. That's why I was suggesting to do it only for extensions, since after validation it would be clear which path to take.

We did consider that but we had concerns on the scope and size of this change and the impact on its likeliness to get approved, which is why we tried to keep the changes as small as possible, also keeping in mind that there are more fundamental changes down the line.

> Adding all of that info to a step that is already overloaded with messages doesn't seem like a good idea to me. I think we need to consider separating this into its own step, so it doesn't distract from everything else going on, and it's only shown we really necessary.

I actually do think that page looks a lot more readable. The sections are clearly separated from each other and now have clear headings to identify them etc, whereas before the source code submission section was just buried on the page, between validation results and platform selection (which wasn't even properly separated from the the rest).

If you have strong feelings about that, I can add it as a separate page right after clicking "Continue" on the file upload page.

**Comment by MeridelW** [comment]
Chiming in:

-I am fine with separating this into its own step but also was operating
under assumption that we did not want to make any big changes. This is a
band-aid solution while we work on larger re-design.

-I also think the new page is more readable. It's much more scanneable and
the steps you need to take are clearer.

**Comment by MeridelW** [comment]
"band-aid" may not be the right term. Instead, I think we can consider it a
solution for now, with plans to overhaul submission process in the future
(at which point we should have a cleaner design that allows for us to
display directions in a more streamlined way).

Having source code as a stand-alone step should be even more effective in
meeting our stated goal of developers focusing on and following
instructions. Great!

**Comment by wagnerand** [comment]
I tried to move this into a separate page but now it requires modifying the existing django `AddonUploadForm` and creating new form that handles the radio buttons, the file submission field and the submit button, which is beyond my skillset.

**Comment by MeridelW** [comment]
I think the three of us should huddle up and discuss options here. I'll
send a meeting invite.

**Comment by jvillalobos** [comment]
Talked to @eviljeff about this, and it sounds like something that can be resolved as a P2 in the next couple of weeks. To sum up the discussion, this work involves:

* Remove the source code upload form from the Upload step.
* Add a new source code upload step (following the XPI upload step),which includes the new copy and the Yes / No radio buttons, as explained in the [doc](https://docs.google.com/document/d/10WsKUfiuQ7-WFwSjyuPIztkoRHwLR7lUrdMoJdvZlsU/edit).
* The step above only applies to extensions.

**Comment by MeridelW** [comment]
Great! Thanks, Jorge.

**Comment by eviljeff** [comment]
@jvillalobos just listed extensions or unlisted extensions too?

**Comment by jvillalobos** [comment]
While I learn towards only requiring it for listed add-ons, for practical reasons, I suspect @wagnerand will disagree with me :). I defer the call to him.

**Comment by wagnerand** [comment]
Since the policies apply to both listed and unlisted and source code helps us review minified but questionable code, it can allow us making a better decision on whether to block or not, and which block to set. Therefore, we should show it for unlisted as well.

**Comment by MeridelW** [comment]
@eviljeff Andreas shared the screenshot with me and I made some minor copy edits to further improve scannability and guide the user through the steps on this screen. 

**Suggested changes [highlighted in green here:](https://docs.google.com/document/d/10WsKUfiuQ7-WFwSjyuPIztkoRHwLR7lUrdMoJdvZlsU/edit#bookmark=id.oxwjwi4ym6y1)** 

I realize it is late in the process. If these changes slow things down and are not possible, please let me know and I will suggest instead just a few minor copy edits.

**Comment by MeridelW** [comment]
I also want to confirm that the user will not be able to advance if they do not select yes/no here.
![screen shot 2018-08-06 at 1 44 27 pm](https://user-images.githubusercontent.com/33848177/43735045-3d65026c-997f-11e8-954d-5ad5901af014.png)

**Comment by wagnerand** [comment]
> I also want to confirm that the user will not be able to advance if they do not select yes/no here.

I believe the server will show an error in that case when you hit submit, but you have a good point here. @eviljeff could we js-disable the button in case the form is not "valid"?

**Comment by eviljeff** [comment]
They can't advance with selecting yes or no, correct.  If the user clicks the continue button they get some UI telling them to choose yes or no (or select a file if they chose yes and didn't select a file.)  

(using standard browser/django _required_ support that we're going to re-enable elsewhere in #8912)

**Comment by eviljeff** [comment]
> There is a text in the PRD which was partially omitted in the implementation:
    PRD: "You may need to submit source code with your submission. "
    AMO: "You may need to submit source code"

I must have overlooked that copy change.  It's pretty minor imo - does it warrant a follow-up issue @wagnerand ?

> Regarding Reviewer Notes, the PRD mentions that there should be an additional message displayed for cases in which source code was provided. This was not implemented, as far as I can see.

@jvillalobos's request only mentioned the upload step in his [request](https://github.com/mozilla/addons-server/issues/8973#issuecomment-408560240) so I just referenced the PRD for that and didn't know what the status of any of the other content in the PRD was.

> do we need to see the Source code upload step for dictionaries, lang packs and search tools after all? IMO, for these type of submissions, this step should be omitted.

It should have just been extensions - that's what the request specified.  (My head was in static theme land so I only excluded those).  @AlexandraMoga could you file an issue?

> There is also a flow issue when selecting the Cancel and Disable version button, for which I filed #9139 as a follow up.

😞

**Comment by wagnerand** [comment]
> I must have overlooked that copy change. It's pretty minor imo - does it warrant a follow-up issue @wagnerand ?

I agree it's fairly minor. Maybe we can piggy-back on other follow-up work related to this?

**Comment by AlexandraMoga** [comment]
> It should have just been extensions - that's what the request specified. (My head was in static theme land so I only excluded those). @AlexandraMoga could you file an issue?

Filed https://github.com/mozilla/addons-server/issues/9142

**Comment by jvillalobos** [comment]
> @jvillalobos's request only mentioned the upload step in his request so I just referenced the PRD for that and didn't know what the status of any of the other content in the PRD was.

Yeah, forgot to include that. Please file a followup for it. Not a huge deal.
