### ISSUE TITLE
Icon previews are not always rendered after submitting a custom icon upload in DevHub

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#8977]
STR:

1. Log in to Developer Hub -> Manage my Submissions
2. Choose one of your add-ons to edit its details
3. Upload a custom icon and click Save

Actual result:
The icon previews are not always rendered after submitting a custom icon upload in DevHub

Expected result:
All three previews - 32x32, 64x64 and 128x128 - are displayed after submitting a custom icon upload in DevHub

Notes:
- the missing previews are displayed after the page is reloaded
- reproduced on AMO -dev with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/49379005-c9b19600-f716-11e8-8436-6a2811e32f55.png)

**Comment by EnTeQuAk** [comment]
This is probably related to the fact that they're scaled down/rendered asynchronously and won't finish in time the browser downloads them after they got submitted.

Not sure there's much we can do about that, maybe add a simple "in progress" image or so and inform the user to reload the page?

We could also add some JS that queries the missing image and injects it once ready, I'm not much of a fan of that though.

@diox @pwalm random ideas from a ui/ux perspective?

**Comment by AlexandraMoga** [comment]
@EnTeQuAk since you referred above to the screenshots upload component, do you think the case displayed below can be fixed when this issue is resolved, or does it look like something with a completely different root cause?

 - random thumbnail displayed during screenshot processing:

![image](https://user-images.githubusercontent.com/31961530/43394479-90f15222-9403-11e8-86e3-7356d0f3bfec.png)

**Comment by pwalm** [comment]
Try the existing stuff we have first, and if it looks like crap, I'll make a custom thing for 32x32.

**Comment by AlexandraMoga** [comment]
This issue is still valid
