### ISSUE TITLE
Spelling error: translatation -> translation

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-server#8978]
### Describe the problem and steps to reproduce it:
https://github.com/mozilla/addons-server/blob/master/locale/en_US/LC_MESSAGES/django.po#L5612

### What happened?
translatation

### What did you expect to happen?
translation

**Comment by devaneymoz** [comment]
This has been fixed in admin.

**Comment by diox** [comment]
Will be fixed during the next locales extraction.
