### ISSUE TITLE
Cannot transfer ownership for Themes

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#898]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Submit a new theme 
2.Go to theme edit listing page and try to transfer ownership

Expected results:
You can transfer ownership without problems

Actual results:
You cant transfer ownership(Button is greyed out)

Please see screencast for this bug : http://screencast.com/t/OQSPJX88wC

**Comment by andymckay** [comment]
Is there a javascript error on this page?

**Comment by vcarciu** [comment]
There is no error in console

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2(Win 7)
Postfix video: 
![transferown](https://cloud.githubusercontent.com/assets/15685960/18670150/1b985642-7f47-11e6-97cd-0789d9bfa8c9.gif)
