### ISSUE TITLE
Tests that involve FxA are failing on circleci integration-test job.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-server#8980]
Some tests using fxa are failing due to improper teardown within a plugin we use. We have found a fix and filled an issue with the plugin [here](https://github.com/mozilla/pytest-fxa/issues/15).

For now I will add a ```wget``` command that will delete all accounts matching ```uitest``` within the restmail DB.

**Comment by jrbenny35** [comment]
Temp fix merged [here](https://github.com/mozilla/addons-server/pull/9075).

**Comment by jrbenny35** [comment]
@EnTeQuAk I also think we should avoid running the UI-Tests on Pontoon commits. It seems that sometimes there could be like 3 or 4 commits back to back and since the tests need a specific email, having them run in parallel is bad.

**Comment by EnTeQuAk** [comment]
Can we randomize the email per test run? We should be able to do that
at the beginning of the test run and reuse that address throughout the
test right?
There will always be multiple tests running, not just on master but also
when there are multiple pyup PRs or simply two people opening PRs close
to another or one PR gets opened, another closed.

On Wed, Aug 8, 2018, at 12:55 AM, Benjamin Forehand Jr wrote:
> @EnTeQuAk[1] I also think we should avoid running the UI-Tests on
> Pontoon commits. It seems that sometimes there could be like 3 or 4
> commits back to back and since the tests need a specific email, having
> them run in parallel is bad.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
Links:

  1. https://github.com/EnTeQuAk
  2. https://github.com/mozilla/addons-server/issues/8980#issuecomment-411228735

**Comment by jrbenny35** [comment]
> Can we randomize the email per test run? We should be able to do that at the beginning of the test run and reuse that address throughout the test right? There will always be multiple tests running, not just on master but also when there are multiple pyup PRs or simply two people opening PRs close to another or one PR gets opened, another closed.

We have to login with the user created for the addons that get generated, and the user created with the supercreate api script.

**Comment by jrbenny35** [comment]
Trying to randomize the emails I ran into a bit of an issue.

I run ```python manage.py createsuperuser --email=$(FXA_EMAIL) --username=uitest --noinput --add-to-supercreate-group --hostname=olympia-frontend.test``` currently before generating addons to test against. It seems that this script creates a username correctly as I have no problems creating addons and assigning them to the created ```uitest``` user.

The problem arises when I try to login to the devhub. I run into this [line](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/models.py#L377). Tracing it back to [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/models.py#L96) shows that the ```username``` must be getting set to ```None``` as that is where the `Anonymous user 12345``` display name comes from. The logger under that step [here](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/models.py#L98) prints out the correct username. 

Also, if I comment out this [line](https://github.com/mozilla/addons-server/blob/master/src/olympia/users/models.py#L98) I get an ```Internal Server Error``` stating something like 'Column username cannot be null'.
