### ISSUE TITLE
EULA and Privacy policy page not available for disabled add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#8987]
Admins (and potentially reviewers) need to be able to access the EULA and Privacy policy pages for disabled add-ons, for both Mozilla-disabled und user-disabled.

Currently the page is 404.

**Comment by EnTeQuAk** [comment]
Both fields, `eula` and `privacy_policy` are available in the Add-ons Django Admin, anything else you need in that regard?

**Comment by wagnerand** [comment]
Nobody in the review or admin team has access to that except me.

**Comment by diox** [comment]
The addons admin should only require `Admin:{anything}` and `Addons:Edit`. Nobody else has this?

**Comment by diox** [comment]
I'm ok with displaying those in reviewer tools if the admin isn't sufficient, but the frontend pages should remain inaccessible regardless of the user. We're moving away from special behavior/permissions on the frontend for admins/reviewers, except for things that have no direct impact like adding buttons linking to admin/reviewer tools.

**Comment by wagnerand** [comment]
Whhen you say add-ons django admin, what page exactly do you mean?
I can't see those fields on `/admin/models/addons/addon/ID/` or `/admin/addon/manage/`.

> the frontend pages should remain inaccessible regardless of the user

Developers would still need access to their EULA and Privacy Policy for user-disabled add-ons.

**Comment by diox** [comment]
> Whhen you say add-ons django admin, what page exactly do you mean?
I can't see those fields on /admin/models/addons/addon/ID/ or /admin/addon/manage/.

The former. It should be in there... I see them on my local instance. Looks like there is a bug causing them not to be rendered with a textarea but with a single-line input, though.

> Developers would still need access to their EULA and Privacy Policy for user-disabled add-ons.

They can through devhub, no?

**Comment by wagnerand** [comment]
> The former. It should be in there... I see them on my local instance. Looks like there is a bug causing them not to be rendered with a textarea but with a single-line input, though.

Ah, I see. That page is still hard to find (it's not linked anywhere), and you need VPN for it, which not all admin reviewers have.

The review page links to the (public) EULA ad PP page, for example:
https://reviewers.addons.mozilla.org/en-US/firefox/addon/<slug>/privacy/

I am not sure how easy it is to make that page show the actual content if you're logged in as a reviewer. Alternatively, we could create a reviewer-internal page that shows the content and then change the links on the review page.

>> Developers would still need access to their EULA and Privacy Policy for user-disabled add-ons.

> They can through devhub, no?

Ah, yes, that works.

**Comment by AlexandraMoga** [comment]
After a quick check this is what I observed:
- only Admin users can access the review page for a disabled addon to view the links to the PP and EULA pages
- the PP and EULA are available only when accessed from the Rev Tools which are pointing to `https://reviewers.addons-dev.allizom.org/en-US/reviewers/privacy/<some-addon>` respectively `https://reviewers.addons-dev.allizom.org/en-US/reviewers/eula/<some-addon>`



@eviljeff I have a question:
- has the new access been given to all reviewer groups or only to Admin users? I wasn't able to access the pages with users that are only reviewers, including Reviewer Admins.

**Comment by eviljeff** [comment]
The access should be the same as the review page itself - if a reviewer can access a given review page (unlisted, or disabled or deleted) then the eula/privacy policy pages should also be accessible.

**Comment by AlexandraMoga** [comment]
In that case, as I mentioned above, it will be only Admin users who are going to have access to the review page of a disabled (not deleted) add-on, respectively to the PP and EULA pages.

@wagnerand does this work for you?

**Comment by wagnerand** [comment]
@AlexandraMoga Regular reviewers have access to disabled add-ons. Do you have an example I could check?

**Comment by AlexandraMoga** [comment]
@wagnerand  I've tried to access this add-on - https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/libs-unread-code-points - with a user that had Post Review and Admin Reviewer permissions

**Comment by wagnerand** [comment]
Ok, looks like I was wrong. I expected that regular reviewers would have access, but they don't.

Since only admins can set the status to "Disabled by Mozilla", I think the current behavior is ok.

@AlexandraMoga This can be marked as verified.

**Comment by AlexandraMoga** [comment]
Conclusion:
Only Admin users have access to view the review page, privacy policy and EULA pages for an add-on with the following statuses:
- Disabled by Mozilla
- disabled by user, i.e. Incomplete
- invisible

Marking issue as verified.
