### ISSUE TITLE
Make it possible to add a Repository link

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addons-server#8989]
> Homepage
> Support Site
> Support Email

I recommend a 4th resource:
> Repository

# Example
 This is how it would look like on the [Adblock Plus](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/) page:

> [Homepage](https://adblockplus.org/)
> [Support Site](https://adblockplus.org/forum/)
> [Repository](http://hg.adblockplus.org/)

Repositories are useful to find out more about add-ons. Adblock Plus doesn't contain a license file in the add-on installation file at this writing (the .xpi file) like the repository.

**Comment by EnTeQuAk** [comment]
Duplicate of https://github.com/mozilla/addons/issues/689

**Comment by davidhedlund** [comment]
@EnTeQuAk Thanks.
