### ISSUE TITLE
Had to add extra lines to get one each new line on AMO

### ISSUE THREAD

**Issue by marcoagpinto** [mozilla/addons-server#9007]
### Describe the problem and steps to reproduce it:
Yesterday I updated my GB speller add-on and was editing its information.

I noticed that most of the text was all together without blank lines.

So, the workaround I found was to add extra lines #CRLF$.

It solved the issue in the speller page:
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2

But, when Firefox updated the description, I get all the extra lines I added.

So, in the add-on page the lines look well (I doubled them) but in Firefox they appear doubled.

### What happened?
No blank lines in most of the description.

### What did you expect to happen?
Each #CRLF$ should have created a normal line.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2
![firefox_screenshot_20180727](https://user-images.githubusercontent.com/5192600/43319445-a844c7f6-919c-11e8-99ed-9b226aa6c6ff.png)
![addon_page_screenshot_20180727](https://user-images.githubusercontent.com/5192600/43319451-b1db613a-919c-11e8-8ff7-818f2328b6e3.png)

**Comment by eviljeff** [comment]
I don't see any extra lines in either devhub or in frontend, so looks like the problem is in Firefox.

**Comment by marcoagpinto** [comment]
@eviljeff 
While editing the details, I have like this:
"
<strong>Detailed installation/use instructions:</strong>

<a href="http://proofingtoolgui.org/en_installing.html">http://proofingtoolgui.org/en_installing.html</a>


<strong>FAQ:</strong>

<a href="http://proofingtoolgui.org/faq.html">http://proofingtoolgui.org/faq.html</a> <strong>(read point 4 for issues)</strong>
"

So that it appears correctly in the description of the add-on.

Can you enter my Developer Hub as an administrator to confirm this?

Thanks!

**Comment by eviljeff** [comment]
without the "fix" of 2 lines, we can see the difference between legacy frontend and new frontend.  New frontend doesn't convert `/n` into `<br>` when it's between html tags.  @kumar303 / @bobsilverberg to investigate.

**Comment by bobsilverberg** [comment]
It sounds like we need to use `nl2br` along with `sanitizeHTML` in this case. I'll open an issue on addons-frontend for this.

**Comment by bobsilverberg** [comment]
Hmm, actually we already use `nl2br` for this field, because we're using `sanitizeUserHTML` rather than just `sanitizeHTML`, the former of which incorporates `nl2br`, so it looks like this needs further investigation.

**Comment by bobsilverberg** [comment]
This has been replaced by https://github.com/mozilla/addons-frontend/issues/6129.
