### ISSUE TITLE
Add position/position_china fields to discovery items model

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9023]
To prepare for the switch to a database-driven discovery pane (https://github.com/mozilla/addons-server/issues/2448) we need to add the fields to the database in advance. That way curators can set the discovery pane content in the database before we make the switch, ensuring a smooth transition.

Therefore, all we need to do here is add 2 fields: `position` and `position_china`, and allow curators to edit them in the discovery items admin tool. Bonus point for adding a way to quickly filter the list of items to find which have a position set or not.

**Comment by vcarciu** [comment]
Verified as fixed : 
![positionchina](https://user-images.githubusercontent.com/1583842/43466347-ff9458f2-94e7-11e8-9ec7-4810b79782aa.gif)
