### ISSUE TITLE
EncodeError: Object of type FileValidation is not JSON serializable

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9033]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4412570/

```
EncodeError: Object of type FileValidation is not JSON serializable
(12 additional frame(s) were not displayed)
...
  File "simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "simplejson/encoder.py", line 273, in default
    o.__class__.__name__)

EncodeError: Object of type FileValidation is not JSON serializable
```

**Comment by diox** [comment]
Not sure which task does this yet but it's certainly broken. Need to investigate and fix it.

**Comment by diox** [comment]
This is coming from `<@task: olympia.devhub.tasks.handle_file_validation_result of olympia at 0x7f8ad7bfea50>`

**Comment by diox** [comment]
QA:
- Get someone with ssh access on dev to delete a validation attached to a file
- Try to access that file validation results in devhub, it should regenerate it

**Comment by vcarciu** [comment]
The validation is regenerated with an unexpected error : 
![validationerror](https://user-images.githubusercontent.com/1583842/43463491-5b1495ea-94e1-11e8-8d8a-585a7d128d43.gif)

**Comment by vcarciu** [comment]
The addon where the issue was reproducible is https://addons-dev.allizom.org/en-US/developers/addon/ramele-wharous-otteetzal/versions , the file for Mac .

**Comment by diox** [comment]
The fact that the validation did go through this time indicates that the original problem is fixed. It shouldn't fail however, so I need to investigate this.

**Comment by diox** [comment]
https://github.com/mozilla-services/puppet-config/blob/6bf40fa6dd482186cd23f1d9349526edefc9702d/amo/modules/olympia/manifests/celery.pp#L16-L17 is what makes it work in dev/stage/prod celery workers.

**Comment by vcarciu** [comment]
Verified as fixed : 
![validation](https://user-images.githubusercontent.com/1583842/43830391-d42901ae-9b09-11e8-8f9e-54a0b05dc9b4.gif)
