### ISSUE TITLE
Reviewers whiteboard is displayed in the Edit Information page for static themes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9037]
**STR:**

1. Log in to Developer Hub and submit a new static theme
2. After the submission steps are completed, click on Manage submission
3. In the add-on Edit information page, scroll down to the Technical details section and click on Edit

**Actual result:**
The section expands, showing additional options among which the review's whiteboard is also present

**Expected result:**
Since a static theme review page does not include the whiteboard, this section should be removed from the Edit information page

**Notes:**
- another solution would be to include the whiteboard in static themes review page, if theme reviewers consider it to be helpful  
- reproduced on AMO -dev with FF61, Win10x64

[1] DevHub
![image](https://user-images.githubusercontent.com/31961530/43460914-b8c310ba-94da-11e8-8aa0-afe83fa2d529.png)

[2] RevTools
![image](https://user-images.githubusercontent.com/31961530/43460920-bcc6ae9c-94da-11e8-9f94-543dc6185f0a.png)

**Comment by wagnerand** [comment]
I would rather show the whiteboard for reviewers.

**Comment by eviljeff** [comment]
@caitmuenster says "we don't need whiteboards for theme designers/reviewers"
@wagnerand  says  "just remember my words when we find a reason we need it in a couple of months after static themes launched" 😆

**Comment by caitmuenster** [comment]
Spoke too soon! Let's leave it in in case we need it for contests or promotions.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/44260133-34000280-a21c-11e8-9be8-7ee8514e0940.png)
