### ISSUE TITLE
Public listed version of an extension is not the latest approved version.

### ISSUE THREAD

**Issue by spoji** [mozilla/addons-server#9040]
### Describe the problem and steps to reproduce it:
Version 1.1.0 of [LanguageSwitch](https://addons.mozilla.org/en-US/firefox/addon/languageswitch/) have been pushed and automatically approved on AMO.

Logs of this version can be found on the [review page](https://reviewers.addons.mozilla.org/en-US/reviewers/review/languageswitch). It has been approved on July 21, 2018, 12:55PM.

### What happened?
Version 1.0.3 is the listed version.

### What did you expect to happen?
Version 1.1.0 should be the listed version.

### Anything else we should know?

This sounds a lot like issue [6962](https://github.com/mozilla/addons-server/issues/6962) that has been fixed a while ago.

We received this issue as a message in dev-addons mailing list. Subject "Addon got delisted (automatically)?"

**Comment by wagnerand** [comment]
Setting P1 until we assess the number of add-ons affected.

**Comment by diox** [comment]
I've been looking at this some more, going through all the explicit `.save()` calls, looking for something that would instantiate something with old data and re-save, overwriting fields that have changed in the meantime, but I haven't found the culprit yet. There are implicit ones all over the forms however...

**Comment by wagnerand** [comment]
For the record, the affected add-ons can be approximated with the following query:
```
SELECT a.id,
       a.slug,
       a.created,
       a.last_updated,
       a.current_version,
       vs.max_version
FROM addons a
JOIN
  (SELECT vi.addon_id,
          MAX(vi.id) AS max_version
   FROM versions vi
   JOIN files fi ON fi.version_id = vi.id
   WHERE vi.channel = 2
     AND fi.status = 4
   GROUP BY vi.addon_id) vs ON vs.addon_id = a.id
WHERE current_version <> max_version
  AND a.inactive = 0
  AND a.status = 4
  AND a.current_version IS NOT NULL;
```

Setting P2, until we have a plan on how to tackle this.

**Comment by M-Reimer** [comment]
Is there any way to get my update out? Can you manually trigger something?

I already haven an issue about this, as "advertised" functionality isn't currently available as an old version is offered for installation:

https://github.com/M-Reimer/languageswitch/issues/1

**Comment by diox** [comment]
@M-Reimer this issue is currently a high priority for us, one way or another we'll fix your add-on next week. Sorry for the inconvenience.

**Comment by M-Reimer** [comment]
I've already created a new release (1.1.1) with no changes compared to 1.1.0. Uploaded this one some hours ago and, so far, it is the "active" release. Hope it stays that way.

**Comment by eviljeff** [comment]
given how infrequently this is happening, and how difficult it is to identify the cause, we _could_ just add a hack to fix it again.  E.g. either:
* fire a celery task with a 1 minute (or whatever) delay in the auto-approve task to re-set the current_version.
* have a daily cron job that runs something like the query @wagnerand included and just fixes anything broken.

The former would be a lot more accurate, and near seamless to the developer - but assumes that the problem happened during auto-approve and no-where else;  the latter would possibly be more reliable but would be slower (because it'll check all add-ons) and will leave the add-on broken for longer.

**Comment by wagnerand** [comment]
If we do that, what's our strategy to fix that permanently. I'm thinking of the `hide_disabled_files` and `unhide_disabled_files` cronjob that were added as a quick hack but are still here years later, meanwhile have bitten us in the back more than once and have been failing for a while without anyone noticing, leading to further problems...

**Comment by eviljeff** [comment]
@diox to comment on his strategy because he's spent time investigating it.

**Comment by diox** [comment]
We don't have a strategy to fix that issue permanently, because as we both pointed out we've been unable to identify the cause. We're acutely aware that the 2 solutions proposed are hacks, we just have nothing better to offer right now.

Our of the 2, I prefer the cron job. It's ugly, takes a bit more time, but I feel like we're going to need the extra reliability. We could probably fire it hourly.

**Comment by diox** [comment]
I [made a query](https://gist.github.com/diox/12e5b3c4a41e670e9ff29f54853850cb) to find affected add-ons based on the one above, with one major difference: it properly discards versions with multiple files attached that have different statuses.

*TV presenter voice* What I found will shock you...

No discrepancy found.

Indeed, all add-ons found by the previous query had one or more extra file in disabled state to their latest version and that's what was causing those versions to not be considered for the `current_version`.

Now, the add-on in the original report had only one file, so there is still something fishy going on. But with no other add-ons affected, I don't want to rush into a workaround, so downgrading the priority for now.

**Comment by spoji** [comment]
I think this should stay open if this problem still occurs from time to time.

**Comment by eviljeff** [comment]
> I think this should stay open if this problem still occurs from time to time.

do you have any more examples?  Without more data the issue isn't going to be worked on.

**Comment by spoji** [comment]
Unfortunately I do not have more data or examples for this. I understand this issue is stuck and won't be worked on without more information. Feel free to add back the stale flag.

**Comment by wagnerand** [comment]
Could this be related to #13885?

**Comment by spoji** [comment]
Interesting! I do most of my reviews because I've received an email that a new version as been pushed to AMO. I normally perform those reviews just a few minutes after receiving the email. As such, this could be related.
