### ISSUE TITLE
Theme Links Are Broken

### ISSUE THREAD

**Issue by jefwks** [mozilla/addons-server#9045]
### Describe the problem and steps to reproduce it:
https://addons.thunderbird.net/en-US/thunderbird/themes/?sort=rating  Click on a theme and then click the add to Thunderbird button.

We're sorry, but we can't find what you're looking for.
The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

If you typed in the address, please double check the spelling.
If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.
Or you can just jump over to some of the popular pages on our website.

Are you interested in a list of featured add-ons?
Do you want to search for add-ons? You may go to the search page or just use the search field above.
If you prefer to start over, just go to the add-ons front page.

 It doesn't matter which theme is chosen, all the links are broken.

**Comment by diox** [comment]
Hi,

Please report thunderbird bugs over at https://github.com/thundernest/addons-server (AMO and addons.thunderbird.net are now split)
