### ISSUE TITLE
Advanced Admins have a link to Reviewer Tools in the user menu while they don't have permissions to access the tools

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9047]
STR:

Follow up for https://github.com/mozilla/addons-server/issues/7249

1. Log in to AMO stage with a user that has Advanced Admin permissions
2. Hover over the user menu and click on Reviewer Tools

Actual result:
A 403 error is thrown as the user doesn't have permissions to access Reviewer Tools

Expected result:
The link to Reviewer Tools should not be present for Advanced Admins

Notes:
- The Admin Tools [PRD](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit) doesn't mention if Advanced Admin need to have Reviwer Tools access by default. I suppose that they should see the link in the user menu only if an additional reviewer permission was added to their account
- wasn't sure if this needs to be handled by the frontend or the server, so I logged it here
- reproduced on -dev and stage with FF61, WIn10x64

![rev tools adv admin](https://user-images.githubusercontent.com/31961530/43521706-b137e116-959f-11e8-88bb-48fc67855563.gif)

**Comment by diox** [comment]
@AlexandraMoga can you refile this on the frontend? It's fairly minor though, most users with that permission are going to have more permissions, including reviewer tools access.
