### ISSUE TITLE
[Reviewer Tools] Display the author name in the content review list

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#9050]
https://reviewers.addons.mozilla.org/en-US/reviewers/queue/content_review#review-actions

The content review list currently only shows extension name, version, flags, and last review date.

Fairly often a single user creates several duplicate extensions or several spam extensions with minor differences. I only catch on after reviewing several.

If the author name was added to the display it would be easier to notice the new activity by a user and consider duplication before from the start of the review.

The same change might be appreciated in the extension code review list as well.

**Comment by wagnerand** [comment]
> Fairly often a single user creates several duplicate extensions or several spam extensions with minor differences. I only catch on after reviewing several.

There is no policy for duplicate add-ons, so in general, they are ok.
Can you elaborate on cases where the author name would be important to identify a spam listing? Usually, you need to look at the listing metadata to decide whether it's spam or not.

**Comment by bjherbison** [comment]
Mozilla may not have an explicit policy, but duplication is usually considered spamming (ask in keyword spamming). That's the origin of the term. Also, duplicate extensions are malicious (toward other extension writers) as they drown out similar extensions.

Other than duplicates: If I review an extension by an author and reject it, I would consider the five other extensions submitted by the same person at the same time to be suspicious and check them for the same problem. (Based on history, I would consider more than three extensions appearing at the same time from one author to be mildly suspicious.)

One example use of the author is the "free movie download" extensions. There was an individual who uploaded a bunch of free movie extensions, plus one identical with a totally different name. When they were rejected the another set would be uploaded. It would have been easy to miss the extra extension if you don't look at the author's extensions.

**Comment by wagnerand** [comment]
> Mozilla may not have an explicit policy, but duplication is usually considered spamming (ask in keyword spamming). That's the origin of the term. Also, duplicate extensions are malicious (toward other extension writers) as they drown out similar extensions.

Only Mozilla content-review policy should be applied.

> One example use of the author is the "free movie download" extensions. There was an individual who uploaded a bunch of free movie extensions, plus one identical with a totally different name. When they were rejected the another set would be uploaded. It would have been easy to miss the extra extension if you don't look at the author's extensions.

Those add-ons are often easily identifiable by looking at the listing content, which is what matters here. If not, then escalating to an admin is the best approach. In general, making developer-wide decisions should be up to admins. If you see repeated violations of our Acceptable Use Policy, feel free to email the admins with example links so they can take a look.

**Comment by caitmuenster** [comment]
@bjherbison and I chatted a little bit about this over email, and I'm going to summarize my response here. I'm not opposed to including developer names in the queue, but I am interested in seeing screenshots for some of the extensions that B.J. came across. We may want to consider expanding our criteria for 'spam.'

**Comment by bjherbison** [comment]
I found another example today. Someone created six copies of the add-on to put a red border on mozilla.org pages with different names, descriptions, and version numbers (one was 8.6.5).

Having the author name listed would have made it easier to track down and reject those extensions.

**Comment by diox** [comment]
@caitmuenster @wagnerand has a decision been reached regarding whether or not we should do this?

**Comment by bjherbison** [comment]
I would still find this useful. Much of the malware being posted comes from the same authors over and over. (And the reasons I listed previously still apply.)

**Comment by caitmuenster** [comment]
I'm a +1 for including developer names in the content review queue.

**Comment by wagnerand** [comment]
This needs proper speccing and probably also some changes to the review page itself, in order to avoid showing conflicting information. The review page shows the authors in two places (top of the page and right navigation bar), and if I remember correctly, only the sidebar shows all authors, while the top shows listed authors only.

**Comment by erosman** [comment]
I also asked for showing developer names in the review queues many years ago but was rejected at the time.

The reason was that often a developer uploads different add-ons with similar code.

- In case of spam/malware, they are easier to identify
- In case of non-spam, once one is reviewed, others can be easier to review
- In case of duplicates as well, they are easier to identify
