### ISSUE TITLE
Confirm Approval should not be visible if add-on hasn't been manually approved yet

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-server#9053]
If an add-on has the auto-approval disabled flag set, and doesn't require a admin review, the post-review approval panel should not be visible because the add-on hasn't been approved yet.
![image](https://user-images.githubusercontent.com/607379/43543150-5fb6bfd0-95cf-11e8-8362-09e3bf2d7350.png)

**Comment by wagnerand** [comment]
Right.
