### ISSUE TITLE
An Add-on cannot be rejected after it was previously approved

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#907]
Steps to reproduce:
1. Submit a listed add-on on AMO-stage https://addons.allizom.org/en-US/firefox/ 
2. Approve the submitted add-on (i.e. Addon-approved-rejected)
3. Access the review page of the add-on from Editor Tools->Logs->Add-on Review log
4. Reject the add-on

Expected results:
The add-on status from its review history page is “Disable by Mozilla”. The add-on is no longer available in AMO Public Pages.

Actual results:
The add-on status is still “Fully reviewed” and is also available in public pages.

Notes/Issues:
An add-on can be rejected if this is the first action made.
Verified on FF42(Win 7). Issue is reproducing on AMO-stage.
Screencast for this issue: http://screencast.com/t/OUUsnnLD

**Comment by wagnerand** [comment]
Does that happen as well if you put the add-on/version back into a "pending review" status on the admin page for that add-on before rejecting it?

**Comment by ValentinaPC** [comment]
Nope. 
In that case - if I put the add-on/version back into a "pending review" status on the admin page - and then reject it, the addon is rejected. (it is behaving like in the case mentioned above at "Notes/Issues:")

**Comment by wagnerand** [comment]
Ok, that's how I have been doing it since we have signing. Actually, I
think we have to come up with a bigger plan as - at least for unlisted -
rejecting a file that has been approved before would not remove the
signature, afaik.

**Comment by EnTeQuAk** [comment]
Is this something that we need to fix or requires more thinking, more whatever during revamping our tools step by step and could be closed for now?

**Comment by wagnerand** [comment]
I think this has been fixed by https://github.com/mozilla/addons-server/commit/657cadd71a6a263220c4bcf9c0833608a1ead919. You should no longer be able to review an add-on that is not pending review.

**Comment by ValentinaPC** [comment]
Yes, you are right!
Verified as fixed on AMO-dev FF47(Win 7).
Postfix screenshot: 
![reject-approve](https://cloud.githubusercontent.com/assets/15685960/16660951/4c595b7c-4479-11e6-90a7-55aa303dff38.png)
