### ISSUE TITLE
500 when hitting /extensions/format:rss

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#9074]
### Describe the problem and steps to reproduce it:
After 8/2 release, we see some 500 in access logs, and are able to reproduce using curl, for example,

```
$ curl -I https://addons.mozilla.org/en-US/firefox/extensions/format:rss?sort=created
HTTP/1.1 500 Internal Server Error
Content-Length: 21890
Content-Security-Policy: script-src https://ssl.google-analytics.com/ga.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://addons.cdn.mozilla.net; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net; object-src 'none'; default-src 'self'; frame-src 'self' https://www.google.com/recaptcha/; img-src 'self' data: blob: https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net; media-src https://videos.cdn.mozilla.net; child-src 'self' https://www.google.com/recaptcha/; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net; form-action 'self' https://developer.mozilla.org; base-uri 'self' https://addons.mozilla.org; report-uri /__cspreport__
Content-Type: text/html; charset=utf-8
Date: Thu, 02 Aug 2018 17:16:29 GMT
Server: nginx
strict-transport-security: max-age=31536000
X-AMO-Request-ID: e719e31f218f4f07b56481460afd5713
x-content-type-options: nosniff
X-Frame-Options: DENY
x-xss-protection: 1; mode=block
Connection: keep-alive
```

The Sentry issue is this one: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4514941/

### What happened?

We started to notice this error after 8/2 release, however, it was also mentioned on #remora channel that this might not be a regression,

>it could be, but it could also just fail because of the content currently present

and

> it's also possible we updated a dependency that made the loading of that content more strict than it was before

### What did you expect to happen?

For the app to not return 500, but handle it gracefully.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
As a quick and simple fix we can probably strip those characters ourselves. Filtering `[\x00-\x08\x0B-\x0C\x0E-\x1F]` should do the trick.

**Comment by diox** [comment]
It's now a 200 for me in prod, confirming that it's only dependent on content. My guess is an add-on was created with a broken description or name - perhaps because of https://github.com/mozilla/addons-server/issues/8923 ! - and it caused this issue, but as soon as other add-ons replaced it in the feed it "fixed" the problem.

**Comment by AlexandraMoga** [comment]
@diox is there anything specific that should be checked to confirm this is fixed?

**Comment by diox** [comment]
@AlexandraMoga you can try submitting add-ons with invisible unicode control characters (*) in their name or description, and then hitting https://addons-dev.allizom.org/en-US/firefox/extensions/format:rss?sort=created once they have been approved, verifying that it doesn't result in a 500 error page.

(*) One of these (hopefully Github will let me post them) : ``

**Comment by AlexandraMoga** [comment]
I've submitted several add-ons with invisible unicode characters and the https://addons-dev.allizom.org/en-US/firefox/extensions/format:rss?sort=created page is loaded without any errors:

![image](https://user-images.githubusercontent.com/31961530/44346146-f01c3000-a49d-11e8-9fa3-fb9153c989a4.png)

marking issue as verified fixed on AMO dev with FF61, Win10x64
