### ISSUE TITLE
Admin homepage user search result forwards to devhub user profile edit page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9079]
### Describe the problem and steps to reproduce it:

1. Go to `/admin/`
2. Enter an email address in the *Search Users* box
3. Wait (it's very slow)
4. Click on a result in the result dropdown.

### What happened?

You get to `/firefox/users/edit/<ID>`

### What did you expect to happen?

You get to `/admin/models/users/userprofile/<ID>`

**Comment by eviljeff** [comment]
The special search for users is going to be dropped - if the search at the top of `/admin/models/users/userprofile/` isn't a sufficient replacement please file an issue detailing what's missing.
