### ISSUE TITLE
Change local nginx to route appropriate requests to localhost:3000 (frontend)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9080]
`http://olympia.test/` is always legacy frontend right now, which is bad already because deprecated 😞 but will be extra bad once we remove all the legacy views 😨.  We should change it to do the appropriate routing for frontend pages to localhost:3000 instead, mirroring what's done on prod(+stage/dev).

~Note: potential blocker on how we'd do the reverting to legacy frontend switch - would we have to do the cookie thing too?  Can we locally?~

(Bonus if we can move all the routing logic from the ops deployment files into addons-server?)

**Comment by EnTeQuAk** [comment]
I got this working after some fiddling, the only problem I am running into right now is that at least the start page requires quite a lot of add-ons that already exist on addons-server.

The ui-tests already have some code for it, I guess we may just re-use that?

**Comment by eviljeff** [comment]
landfill has some addon generation code - is that not enough?  Otherwise I suppose it's fine to move some code from the ui-tests to `src/olympia/` to do it.

**Comment by EnTeQuAk** [comment]
> landfill has some addon generation code - is that not enough? 

No, since the startpage from addons-frontend requires a certain set of existing add-ons, similar to discopane.
