### ISSUE TITLE
There is no size limit set for static theme image uploads

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9081]
STR:

1. Log in to Developer Hub
2. Submit a new static theme via the wizard
3. Upload a large size image file

Actual result:
There is no size limit message displayed regardless of the image size

Expected result:
There should be an image size limit imposed in order to avoid possible preview generation errors and performance issues

Notes:
- if I upload an image larger than 7Mb in size, the preview won't be generated
- the size limitation should be imposed for .xpi uploads as well, to avoid preview generation errors 
- reproduced on AMO stage with FF61, WIn10x64

[preview generation error when an image >7Mb is uploaded]
![image](https://user-images.githubusercontent.com/31961530/43643047-94402692-9732-11e8-8aa0-5b8c6204dd7d.png)

**Comment by eviljeff** [comment]
We can override the 10mb limit with an additional `--unlimited` param, so it's an easy fix.

Do we _want_ a limit though to individual or total file sizes though?  If so, we should enforce it in a more explicit way via the linter, or addons-server side validation checks on upload, rather than relying on a tool failing somewhere in a task.

@jvillalobos plus anyone engineering for thoughts on limits

**Comment by EnTeQuAk** [comment]
I think we should transform this issue into a generic "limit upload size" issue. I'm sure there are some limits in nginx regarding max body size and uploads, @bqbn or @autrilla should be able to check.

But nonetheless we should add some limits on the Django side of things too. With legacy add-ons gone our file uploads will be significantly smaller too.

**Comment by autrilla** [comment]
The limit for addons-server is 200MB afaict:

https://github.com/mozilla-services/cloudops-deployment/blob/c9915038d67ccb8d82da714ba1f8d7d46f0e78f8/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L197

**Comment by jvillalobos** [comment]
I think limiting uploads to 7Mb is reasonable. We can set the same limit for the XPI and the background image in the wizard, for simplicity. With that restriction in place, setting `--unlimited` would also be good, so the only limit that is hit is the one we control.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64

- for the wizard - header image uploaded limited to 7Mb in size

![image](https://user-images.githubusercontent.com/31961530/44989449-8e2bf200-af96-11e8-8a0e-09fdc13b9435.png)

- for the package submission - maximum package size limited to  7Mb (including the manifest, not just the images)

![image](https://user-images.githubusercontent.com/31961530/44989411-72c0e700-af96-11e8-9173-854877287a59.png)
