### ISSUE TITLE
User is forced to select a Thunderbird and Seamonkey category during dictionary submission

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9096]
STR

1. Log in to Developer hub
2. Submit a new listed dictionary (webextension)
3. After your file is validated, Continue to the next submission step
4. Observe the Category selection sections 

Actual result:
There are two mandatory category fields for Thunderbird and Seamonkey

Expected result:
Thunderbird and Seamonkey category selection should be removed,

Notes:
-  ideally, the entire Category section should not be present at dictionary submission, as proposed in https://github.com/mozilla/addons-server/issues/7113
- additionally, Thunderbird and Seamonkey compatibility should be removed from the Edit information page
- reproduced on AMO -dev with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/43776613-0e80a55c-9a59-11e8-8f83-1d1ed763f6ff.png)

![image](https://user-images.githubusercontent.com/31961530/43776643-24e2d702-9a59-11e8-9c66-cc154848e937.png)

**Comment by diox** [comment]
Interestingly this is not limited to dictionaries, it's just easier to notice there because they are set to always have wide compatibility.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/44338735-93ae1600-a487-11e8-9d3c-14a6d7766018.png)
![image](https://user-images.githubusercontent.com/31961530/44338738-97da3380-a487-11e8-8373-a499b635b561.png)
