### ISSUE TITLE
Webextension dictionaries are not auto-approved 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9097]
STR

1. Log in to Developer hub
2. Submit a new listed dictionary (webextension)
3. After completing the submission, wait for ~5 mins and check if the dictionary status changes to Approved

Actual result:
The dictionary is still in Awaiting Review status, which means it is not auto-approved

Expected result:
Webextension dictionaries should be auto-approved

Notes:
- if I go to the dictionary review page from DevHub, I am redirected to a legacy review page - see https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/dictionar-webextension-switch
- if I search for the dictionary directly in the legacy queue in Rev Tools, it will not show up
- the same applies for dictionary updates 
- reproduced on AMO -dev with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/43778047-4cea43b2-9a5d-11e8-9469-5cf2767165a9.png)

**Comment by diox** [comment]
>  Webextension dictionaries should be auto-approved

@wagnerand @jvillalobos should they be? I'm assuming yes, since they don't contain code, but just in case :-)

**Comment by wagnerand** [comment]
I don't see a reason why we shouldn't auto-approve.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

- Tested with new submissions and new version uploads
- dictionaries are listed in the auto-approved and content review queues
