### ISSUE TITLE
All thunderbird themes direct to a page not found

### ISSUE THREAD

**Issue by Usalabs** [mozilla/addons-server#9101]
No matter what theme I try from the Thunderbird list of themes, by clicking on the 'Add to Thunderbird' button, I keep getting this page:-

We're sorry, but we can't find what you're looking for.
The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly.

and this is one of the themes I was trying to add:-

https://addons.thunderbird.net/en-US/thunderbird/addon/dark-fox-18066/

and this one:-

https://addons.thunderbird.net/en-US/thunderbird/addon/blue-shards1/

It seems all the comments that people are posting are experiencing the exact same thing,,,, no themes anywhere on the site.

**Comment by diox** [comment]
Hi;

Please report issues related to addons.thunderbird.net over their repos, https://github.com/thundernest/addons-server/issues
