### ISSUE TITLE
Creation date of a theme is listed in the “Date Deleted” column from Editor Tools

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#911]
Steps to reproduce:
1. Load AMO-stage Manage My Submission page https://addons.allizom.org/en-US/developers/addons
2. Click the “My Themes” tab
3. Delete a theme (i.e. 2)
4. Go to Editor Tools->Themes tab
5. Access “Deleted” option from "Logs"
6. Observe the date from “Date Deleted”

Expected results:
The date when the theme was deleted coincide with the value from “Date Deleted” column.

Actual results:
The date when a theme was created is listed in the “Date Deleted” column.

Notes/Issues:
Verified on FF42(Win 7). Issue is reproducing on AMO-stage and AMO-dev.
Screencast for this issue: http://screencast.com/t/G0qtdC4QM1gY

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

Mentor: @eviljeff 

@eviljeff could you add some details about how/where to fix the bug, please?

**Comment by eviljeff** [comment]
(copying from irc)
For themes the date deleted column is showing Addon.modified.

The modified date is set on a cron job so it won't be updated until the following day.  Some possible fixes are a) change the theme deletion log to use the same source as the addon deletion log (activity log) [hard]; 
b) set the modified property when we delete the addon, in Addon.delete() [easy].

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50.1(Win 7).
Postfix screenshots:
![created](https://cloud.githubusercontent.com/assets/15685960/21843548/15d4ac32-d7f4-11e6-8505-a6d386d65f24.png)
![datedeleted](https://cloud.githubusercontent.com/assets/15685960/21843549/15d538dc-d7f4-11e6-865a-9032671b6b21.png)
