### ISSUE TITLE
Unable to add themes to Thunderbird

### ISSUE THREAD

**Issue by ddotyjr** [mozilla/addons-server#9115]
I attempted to add several new themes to Thunderbird but after clicking "Add to Thunderbird" button I only got a page that said it couldn't find what I was looking for. An example is the Mesa Boogie theme at https://addons.thunderbird.net/en-US/thunderbird/addon/mesa-engineering/. The page displayed when I tried to add was https://addons.thunderbird.net/en-US/thunderbird/addon/10900/. All themes seemto have this error.

**Comment by EnTeQuAk** [comment]
This repository is only for addons.mozilla.org. Please report any issues with addons.thunderbird.net at https://github.com/thundernest/addons-server/

Thanks!
