### ISSUE TITLE
canot find it!

### ISSUE THREAD

**Issue by BearJean** [mozilla/addons-server#9119]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
when i chick the button on 
```
http://mozilla.com.cn/thread-30326-1-1.html
 [综合讨论] FoxTab -- 3D你的标签页，绝对酷炫 
```
I cannot find the addon
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
That add-on is ancient (the site itself says Firefox 3-11, we're currently at 61) and there doesn't seem to be an up-to-date.

You can find other add-ons related to tab management at https://addons.mozilla.org/en-US/firefox/extensions/tabs/
