### ISSUE TITLE
Flag button is missing for theme updates

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#912]
Steps to reproduce:
1. Open theme updates queue: https://addons.allizom.org/en-US/editors/themes/updates
2. Open the detail of any theme.

Expected results:
There are 5 review buttons Request More Info, Flag, Duplicate, Reject, Approve Theme.

Actual Results:
Flag button is missing.

Notes/Issues:
Verified in FF43(Win7) Issue can be reproduced in addons.allizom.org
![2015-11-12_1844_001](https://cloud.githubusercontent.com/assets/15685441/11124406/7b801142-896d-11e5-9483-6b03ba4d3fdf.png)

**Comment by EnTeQuAk** [comment]
@eviljeff @wagnerand is there a reason for this button to be missing (because themes....) or is this an actual bug?

**Comment by wagnerand** [comment]
I am  not sure. What is this button used for?

**Comment by jvillalobos** [comment]
It appears to be the equivalent of requesting Admin Review for other add-ons. I don't see why it wouldn't apply for updates. Maybe @atsay can clarify.

**Comment by EnTeQuAk** [comment]
So, according to the code the button is shown if it's not already flagged and if it's not a re-review. maybe the latter is the case here.

**Comment by atsay** [comment]
I would show it even for a re-review, but I've never heard complaints from the reviewers about this, so I would say it's not a bug.
