### ISSUE TITLE
Search displays a lot of unrelated results for term "Netatmo"

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-server#9123]
### Describe the problem and steps to reproduce it:
- Search for "Netatmo"

### What happened?
A lot of completely unrelated results to the term "Netatmo" are shown. One particular extension I was trying to look for (published by me) was only on the second page. It has netatmo all over it, too, but only has few users and no ratings.

### What did you expect to happen?
Top results at least have the term "Netatmo" somewhere in their description or tags.

### Anything else we should know?
Search: https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=Netatmo
Add-on I was looking for: https://addons.mozilla.org/en-US/firefox/addon/netatmo-co-indicator/?src=external-gh-amo-search-bug

**Comment by EnTeQuAk** [comment]
This seems to have been fixed by #8868
