### ISSUE TITLE
Some users profile page return 5xx (on new addons-frontend)

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#9137]
### Describe the problem and steps to reproduce it:
Looking at our daily access logs, I'm surprised to see that 50% of the 5xx are caused by people access users' profile pages. For instance, on 8/10/2018 we had 173 5xx on one proxy instance, and 86 of them happened when people accessing `/<locale>/users/<user_id>` endpoint.

And particularly, [1] accounted for 40% of all 5xx, or 69 of them. The `0xy9en` user seems to have a few popular addons (for example [2] and [3]) and thus its user profile page attracted many hits, but unfortunately they all ended up with 5xx.

[1] https://addons.mozilla.org/en-US/firefox/user/0xy9en/
[2] https://addons.mozilla.org/en-US/firefox/addon/hotspot-shield-free-vpn-proxy-/
[3] https://addons.mozilla.org/en-US/firefox/addon/touch-vpn/?src=search

### What happened?

Not sure. A full list of user profile endpoints that returned 5xx is following:

```
/tr/firefox/user/000mayte000/
/fr/firefox/user/00Thathy00/
/en-GB/android/user/0SuperNova0/
/en-US/firefox/user/0owesleyo0/
/bg/firefox/user/0Adrian0Avalos0/
/tr/firefox/user/0_0_HellishHeaven_In_Flesh123456/
/ru/firefox/user/0veR/
/ru/firefox/user/000MIIX/
/ru/firefox/user/0x6b/
/nl/firefox/user/00adef/
/en-GB/firefox/user/0o0rsi/
/en-US/firefox/user/0leg-cool/
/en-US/firefox/user/0xy9en/
/fa/firefox/user/0xy9en/
/hsb/firefox/user/0xy9en/
/id/firefox/user/0xy9en/
/vi/firefox/user/0xy9en/
/ar/firefox/user/0xy9en/
/es/firefox/user/0xy9en/
/ru/firefox/user/0xy9en/
/en-US/firefox/user/00crimson/
/pt-BR/firefox/user/000000000o/
/zh-CN/android/user/0l1v3r/
/ja/android/user/0langy/
/zh-TW/android/user/0xSobky/
/ru/firefox/user/0xy9en/?src=api
/zh-CN/android/user/0bruno/?src=addon-detail
/uk/firefox/user/0l1v3r/?src=addon-detail
```

### What did you expect to happen?

User's profile pages do NOT return 5xx for certain users.

 
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by AlexandraMoga** [comment]
As far as I can tell, this is caused by the fact that the username starts with a `0` (see list above). I've experimented with a few more users and each time the username begins with a `0` the profile page will return a 504.

Also, this seems to be happening only on the frontend, not in the API:

https://addons-dev.allizom.org/api/v3/accounts/account/0basket/ - returns 200
https://addons-dev.allizom.org/en-US/firefox/user/0basket/ - returns 504

**Comment by EnTeQuAk** [comment]
This looks like an addons-frontend issue to me. Accessing this page on the legacy pages works perfectly fine, the `504` feels particularly wrong, suggesting that there is some internal redirect loop or something like that happening on the server side rendering? Not sure.

cc @bobsilverberg and @kumar303 to take a look at that.

**Comment by diox** [comment]
Re-filed as https://github.com/mozilla/addons-frontend/issues/6007
