### ISSUE TITLE
thunderbird themes not working for me

### ISSUE THREAD

**Issue by mdboyd1** [mozilla/addons-server#9138]
### Describe the problem and steps to reproduce it:
No matter what theme I try to install for Thunderbird, when I click "add," it brings me to a page that says "We're sorry, but we can't find what you're looking for.  The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly."

### Anything else we should know?
link:  https://addons.thunderbird.net/en-US/thunderbird/addon/10900/
browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
computer: MacBook Air (13-inch, Early 2015); High Sierra 10.13.6 (17G65)
- as an fyi, the same thing happens with Safari.

Started during the first week of August.  I have disabled other add ons as well as tried to restart in safe mode, but the problem is clicking on "add to Thunderbird," because it just gives me a page that says we can't find what you're looking for.

other info:
![screen shot 2018-08-12 at 6 45 16 pm](https://user-images.githubusercontent.com/39451408/44007263-26b5dfec-9e60-11e8-9d96-fe9d0b5cf3f4.png)

![screen shot 2018-08-12 at 6 30 08 pm](https://user-images.githubusercontent.com/39451408/44007274-427c2772-9e60-11e8-9246-637e52d8c156.png)

I have also received this page more than once.  Reloading solves the issue:

![screen shot 2018-08-12 at 6 34 00 pm](https://user-images.githubusercontent.com/39451408/44007268-38da8ca4-9e60-11e8-9b26-ab6c468330d8.png)

**Comment by EnTeQuAk** [comment]
Please report issues about addons.thunderbird.net at https://github.com/thundernest/addons-server/issues

This repository is only for addons.mozilla.org.
