### ISSUE TITLE
The Source Code upload form appears collapsed for a short moment when the user lands on it in the add-on submission flow

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9140]
STR:

1. Log in to Developer hub on AMO -dev
2. Submit a new extension
3. After your file is validated, click on Continue to proceed to the Source code upload form

Actual result:
The Source code upload form appears collapsed shortly, when the user lands on the page

Expected result:
The Source code upload form should be displayed only in its initial state

Notes:
- reproduced on AMO -dev with FF61, Win10x64
- also reproduced if the Source code upload page is reloaded

![src collapsed form](https://user-images.githubusercontent.com/31961530/44024353-ba1e62be-9ef5-11e8-94f5-1ac74a456ad2.gif)

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by isunitha98selvan** [comment]
I would like to work on this. @caitmuenster @diox

**Comment by diox** [comment]
@isunitha98selvan it's all yours. Follow https://addons-server.readthedocs.io/en/latest/topics/install/docker.html to install addons-server locally, that's what serves the developer hub. 

My guess is you'd probably want to hide the source code part by default in CSS and then make sure it's shown when needed in js, you'll have to figure out if that's the best way of doing this. The CSS file to modify is going to be `static/css/devhub/submission.less`, the JS is `static/js/zamboni/devhub.js`.

**Comment by caitmuenster** [comment]
@isunitha98selvan Hey there! How's it going with this bug?

**Comment by LordGameleo** [comment]
@isunitha98selvan are you still working on this?

**Comment by sanu11** [comment]
Hello, I am newbie here and interested to contribute to addons-server. I have set up all the environment for addons-server and could run it in my browser.  I was trying the to reproduce the bug  posted by @AlexandraMoga locally.
I tried to uploading  2-3 existing addon xpi files but it  shows this error - "Your add-on failed validation with 1 error. Received an empty response from the server; status: 500.". How I am supposed to do check this? Some help would be appreciated :) Also is it a good bug to solve since its my first contribution?

**Comment by eviljeff** [comment]
@sanu11 it's pretty difficult to debug your setup over github issues so if you can pop into our #amo channel on irc (https://wiki.mozilla.org/IRC) we'll try to troubleshoot your problems.

**Comment by sanu11** [comment]
Sure @eviljeff . Thanks

**Comment by caitmuenster** [comment]
Hey @sanu11, were you able to troubleshoot your issue?

**Comment by sanu11** [comment]
Hey @caitmuenster, I had tried replicating the bug, but I was facing some issues. 
I have set up environment in ubuntu and tried uploading xpi file of existing addon, but wasn't able to.
In windows 10 I am getting nginx error, thus unable to replicate the bug.
I will try again  and will ask for help in irc if needed.

**Comment by LordGameleo** [comment]
Is this issue open? @caitmuenster

**Comment by wagnerand** [comment]
@LordGameleo Yes, feel free to work on it.

**Comment by diox** [comment]
Thanks @yatinmaan for the fix
