### ISSUE TITLE
Drop the column `has_editor_comment`

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-server#9144]
Drop the column `has_editor_comment` as it will be removed after #7516 . So needs a database migration so it doesn't fail when we deploy the updated code.

https://github.com/mozilla/addons-server/pull/9128#pullrequestreview-145644185

**Comment by eviljeff** [comment]
Yes, we will need this.  btw the code in #9128 doesn't drop the column, it just makes it nullable so the database doesn't raise an error when the django code no longer sets it.

**Comment by championshuttler** [comment]
@eviljeff great either i will raise PR for it or someone else ;) 
Can you please add needed labels to this bug 
Thanks
