### ISSUE TITLE
Accounts merge request to another FF account user

### ISSUE THREAD

**Issue by MagicFab** [mozilla/addons-server#9157]
I have an account (fabianrodriguez) on addons.thunderbird.net under an email tied to a Firefox Account which is not my main account. I can login to both.
How can I request a merge? Or how can I change the email so it matches my maint Firefox acount user?

**Comment by EnTeQuAk** [comment]
This repository is only for issues about addons.mozilla.org, regarding addons.thunderbird.net please open issues at https://github.com/thundernest/addons-server/issues/

Thanks! Please let us know if you have any further problems/questions about AMO.
