### ISSUE TITLE
Trigger content re-review by time last reviewed and time last modified

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9158]
Content review was set up in https://github.com/mozilla/addons-server/issues/6310. One of the initial conditions set up is that add-ons that haven't been content-reviewed in a year would be up for content re-review.  @caitmuenster is concerned this will lead to lots of content reviews showing up soon (when the first year of the program is up), so we want to update the rule to mitigate that problem.

I suggest we only resurface add-ons that haven't been content reviewed for a year AND whose listings been updated (`modified`, I think) since then.

**Comment by caitmuenster** [comment]
I'd tag this as 'works for me.' 

Ideally, listing content that has changed since last content review decision would re-enter the content review queue. That having been said, I'm ok with Jorge's proposal.

**Comment by wagnerand** [comment]
I did some quick digging and it looks like the `modified` field does not get updated when the description or summary (for example) change.

**Comment by diox** [comment]
Really ? Those fields are always updated through model forms on the add-on, and when we save the form it does save the add-on itself, triggering a `modified` update, so that'd be surprising to me - certainly a bug if you're right.

**Comment by wagnerand** [comment]
Maybe I am wrong, I read https://github.com/mozilla/addons-server/blob/e1d1ae0773c134534c79fac39379a128bb8c9d3f/src/olympia/amo/decorators.py#L113 as one would have to call that explicitly when updating a summary, for example.

**Comment by diox** [comment]
`set_modified_on` is used in tasks that modify files, precisely because those task don't save the corresponding add-on object (or save it too soon). It's rather specific.

[`modified` is a `auto_now=True` field](https://github.com/mozilla/addons-server/blob/3c7cf878468a6eff8e516d94e75fa943e0abfa67/src/olympia/amo/models.py#L369), so it gets updated every time the add-on instance is saved. Which [should happen in devhub when you edit add-on details](https://github.com/mozilla/addons-server/blob/3c7cf878468a6eff8e516d94e75fa943e0abfa67/src/olympia/devhub/views.py#L901) through the various `ModelForm`s devhub uses.

**Comment by wagnerand** [comment]
> I suggest we only resurface add-ons that haven't been content reviewed for a year AND whose listings been updated (modified, I think) since then.

I ran some quick numbers for this scenario:

By the end of January 2019, ~2,000 content reviews will be due.
By the end of February 2019, an additional ~700 content reviews will be due.
March: additional ~500
April: additional ~500
May: additional ~400
June: additional ~450
July: additional ~300

**Comment by caitmuenster** [comment]
I'd like to keep this open.

**Comment by diox** [comment]
There is a `neverstale` label for that, but it's not going to help much if nobody has time to work on it.

Why do we want to keep this opened anyway ? We removed the automatic re-review in https://github.com/mozilla/addons-server/issues/10095 and then implemented a content re-review trigger based on metadata changes in https://github.com/mozilla/addons-server/issues/13044, does that not cover the use-case for this issue ?

**Comment by caitmuenster** [comment]
Sorry, I had missed #13044! That's sufficient -- I'm closing this now. :)
