### ISSUE TITLE
Make `additional_backgrounds` alignment in preview match Firefox interpretation

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9163]
Broken off from https://github.com/mozilla/addons-server/issues/8038.

Since [bug 1443561](https://bugzilla.mozilla.org/show_bug.cgi?id=1443561) doesn't appear to be on track to be fixed soon, we will launch static themes with that bug. This means we need to change the way the preview deals with `additional_backgrounds` alignment, since the frame encompasses the whole window instead of just the toolbar.

The preview generation should assume a 4:3 width to height ratio for the virtual window.

**Comment by AlexandraMoga** [comment]
I've submitted several static themes that are using the additional background property and added both supported and unsupported `"additional_backgrounds_alignment"`

When the theme uses unsupported alignments (i.e. not one of `left top`, `top`, `right top`), the generated preview will also exclude these alignments.

Below is a representative example for a theme using `bottom` alignments submitted on dev [1] and on stage [2]:

**[1] theme with unsupported alignments submitted on - dev**
![image](https://user-images.githubusercontent.com/31961530/44404833-7dc05400-a560-11e8-8789-c49a760144a0.png)

**[2] theme with unsupported alignments submitted on - stage**
![image](https://user-images.githubusercontent.com/31961530/44404841-81ec7180-a560-11e8-95c9-222c0d52e3ee.png)

**[3] AMO with static theme enabled in the browser**

![image](https://user-images.githubusercontent.com/31961530/44405030-fa533280-a560-11e8-919f-8f8aa72936b0.png)


@eviljeff I have an example in which the preview from AMO looks different compared to Firefox:

Example: https://addons-dev.allizom.org/en-US/firefox/addon/standard-multiple-backg/

![image](https://user-images.githubusercontent.com/31961530/44405422-df34f280-a561-11e8-8e62-f003eaceda74.png)

This theme uses an `empty.png` as headerURL and one `.png` file as additional background. I haven't specified any alignments. I expected the AMO preview to display the additional background image on the right side as well.
I'm reproducing on stage too, which means this is not a regression from this patch, but is still related to the issue discussed here.

**Comment by ioanarusiczki** [comment]
@eviljeff I've noticed and filed two issues while testing additional backgrounds.
https://github.com/mozilla/addons-server/issues/9227
https://github.com/mozilla/addons-server/issues/9228

**Comment by eviljeff** [comment]
> @eviljeff I have an example in which the preview from AMO looks different compared to Firefox:
>
> Example: https://addons-dev.allizom.org/en-US/firefox/addon/standard-multiple-backg/
> 
> This theme uses an empty.png as headerURL and one .png file as additional background. I haven't specified any alignments. I expected the AMO preview to display the additional background image on the right side as well.

[MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme) said `if not specified, defaults to "left top".` so that's how I implemented it - it appears from Firefox that it's actually defaulting to "right top", the same as the `headerURL`.  

@jvillalobos fyi (another) Firefox bug.  Can you confirm what you want to happen and if we think it's likely it'll change in a future Firefox.

**Comment by mconca** [comment]
MDN is not clear on this at all.  The docs for "additional_backgrounds_alignment" say, if not specified, it defaults to "left top".  The docs for "additional_backgrounds" say "By default all images are anchored to the upper right corner."

I think we want everything to anchor to the same location, which is the top right corner.  This is current Firefox behavior, and I just changed the docs for additional_backgrounds_alignment to state that "right top" is the default.

I think that means we only need to modify the AMO preview.

**Comment by jvillalobos** [comment]
Okay, cool. I filed https://github.com/mozilla/addons-server/issues/9233 to change the preview behavior.

**Comment by AlexandraMoga** [comment]
@jvillalobos, regarding multiple background themes without alignments specified, it seems that Nightly is now displaying the background on the left corner [1], which contradicts https://github.com/mozilla/addons-server/issues/9163#issuecomment-415196961. I think we need confirmation that this is now a bug in Nightly and not a deliberate decision, before making any changes to the AMO behavior. Note that https://github.com/mozilla/addons-server/issues/9233 fixed the preview to match the current FF61 layout.

[1] **- AMO preview and theme installed in Firefox 63.0a1(build 20180823220048)**
https://addons-dev.allizom.org/en-US/firefox/addon/multi-backg-no-align/
![image](https://user-images.githubusercontent.com/31961530/44569752-0d921800-a784-11e8-9972-d698fbfdea49.png)

// adding @eviljeff in the loop

**Comment by mconca** [comment]
> I  think we need confirmation that this is now a bug in Nightly and not a deliberate decision

It is a bug in Nightly.  I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1486018 to have it corrected.  Thanks for catching this.
