### ISSUE TITLE
Add identifier if this request is an API request

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9170]
Following https://github.com/mozilla/addons-server/pull/9153 we have multiple places in our code where we check if a request is targeting the API. Some are using `.startswith('/api/')` and some are using `settings.DRF_API_REGEX`.

We should unify this and only make it once.

**Comment by vcarciu** [comment]
@eviljeff : Can you add some STRs to this issue or mark it as "qa: not needed" ?
