### ISSUE TITLE
Get add-on reviews / ratings by star number

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9173]
We would like the [rating listing API](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#get--api-v4-ratings-rating-) to return only reviews for a given star (e.g. one star reviews, five star reviews, etc). 

This will support https://github.com/mozilla/addons-frontend/issues/5923 which is a UI for clicking stars to filter reviews.

The add-on review listing now has a graph that shows a breakdown of reviews by star number. We would like to allow users to click on the star graph and see only reviews by that star number. For example, they could click on the bottom bar to see only one star reviews. This will help users make better decisions about whether to install the add-on or not.

**Comment by AlexandraMoga** [comment]
The [ratings endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#get--api-v4-ratings-rating-) accepts now a `score` parameter that filters results by review score.
Examples:
1. one score:
https://addons-dev.allizom.org/api/v4/ratings/rating/?addon=stratiform&score=3

2. multiple scores:
https://addons-dev.allizom.org/api/v4/ratings/rating/?addon=stratiform&filter=without_empty_body&score=1,2,4
