### ISSUE TITLE
Remove "update_addons_collections_downloads" cron job

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#9186]
### Describe the problem and steps to reproduce it:

The cron job is here:

https://github.com/mozilla/addons-server/blob/master/scripts/crontab/crontab.tpl#L41

But I can't find a second reference to `update_addons_collections_downloads` except the above.

### What happened?

The `crontab.tpl` file went through a round of clean up recently. I wonder if the `update_addons_collections_downloads` was meant to be removed but got missed.

### What did you expect to happen?

If `update_addons_collections_downloads` cron no longer exists, let's remove it.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@diox Could you add some STR for QA or add qa not needed label ? 
Thanks!
