### ISSUE TITLE
Remove XML rendering support from versioncheck

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9194]
We are serving XML to Thunderbird and Seamonkey in versioncheck. Firefox and Firefox for Android already get proper JSON updates.

We should remove the bits and pieces that handle Thunderbird and Seamonkey special, now that they're not hosted on AMO anymore.

**Comment by eviljeff** [comment]
Marking this QA:Extra only because it touches the addon update service.  Just make sure updates work as normal in all versions of Firefox you routinely test with.

**Comment by AlexandraMoga** [comment]
Verified on AMO dev with FF62, ESR 60 and Nightly 64.0a1, Win10x64.
I've tried to cover all add-on types to make sure that updates are working as expected.
