### ISSUE TITLE
Upper and lowercases should have same search suggestions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#9196]
Steps to reproduce:
1.Go to AMO Stage and enter a search term with lower cases
2.Enter same search term with some uppercases

Expected results:
Same search suggestion in both cases

Actual results:
Search suggestions are different

Please see a video for this issue :
![searchsuggestions](https://user-images.githubusercontent.com/1583842/44274619-49405580-a24b-11e8-9ebd-38c62bfbd302.gif)

**Comment by LordGameleo** [comment]
I would like to try working on it. Can you please explain a bit more.

**Comment by diox** [comment]
It's not a good first bug - we could work around it by using lowercase only or something, but it's best to figure out what's going exactly with the elasticsearch query first.

**Comment by diox** [comment]
We'll need a reindex with my changes from 885fb799f3625f672934220fdd4b8c4a1a25bf9f to fix this. Waiting for this to be deployed on dev to trigger it.

**Comment by vcarciu** [comment]
Verified as fixed for upper\lower cases. Exact matches are working better now too. I will mark the issue as verified: 
![uplow](https://user-images.githubusercontent.com/1583842/47362461-1c8e3b80-d6dd-11e8-95c8-d07a66c29a3b.png)
