### ISSUE TITLE
Add-on Edit information form is stuck in a loading state with several locales when an error message should be generated

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9203]
STR:

1. Log in to Developer Hub
2. Change your locale to `de`
3. Go to Mange my Submissions page
4. Select one of your submitted add-ons to view its Edit information page
5. Insert an invalid value in one of the fields that should generate an error - i.e. an unsupported domain in the Contribution URL field
6. Save the form

Actual result:
The edited section is stuck in a loading state after the form is saved

Expected result:
An error should be generated on the corresponding field

Notes:
- reproduced with other locales as well - see `ru`, `it`, `fr` and possibly more
- same issue observed also when editing other fields that generate errors (localized)
- reproduced on all AMO servers with FF61, Win10x64

![trans fields error](https://user-images.githubusercontent.com/31961530/44336067-e505d780-a47e-11e8-86b9-baca2845ee9e.gif)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4488551/

```
  File "jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/olympia/src/olympia/devhub/templates/devhub/addons/edit/basic.html", line 199, in top-level template code
    {{ form.contributions.errors }}
  File "django/utils/html.py", line 386, in <lambda>
    klass.__html__ = lambda self: unicode(self)  # NOQA: unicode undefined on PY3
  File "django/utils/html.py", line 385, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "django/forms/utils.py", line 129, in __str__
    return self.as_ul()
  File "olympia/translations/forms.py", line 88, in as_ul
    ((extra, elem) for extra, elem in li)
  File "django/utils/html.py", line 113, in format_html_join
    for args in args_generator))
  File "django/utils/html.py", line 113, in <genexpr>
    for args in args_generator))
  File "django/utils/html.py", line 94, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))

UnicodeEncodeError 'ascii' codec can't encode character u'\xf6' in position 131: ordinal not in range(128)
```

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![edit in locales](https://user-images.githubusercontent.com/31961530/44388087-e511e000-a52f-11e8-8a09-4df402926b1e.gif)
