### ISSUE TITLE
Compatibility section for dictionaries and language packs review pages needs to be updated 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9205]
STR:

1. Log in to AMO with a Reviewer account
2. Access Reviewer Tools - Auto-approved queue
3. Pick a dictionary from the pending list - see https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/dictionar-categories
4. Check the Compatibility section in the Version details

Actual results:
The dictionary appears compatible with all applications. Android, Thunderbird and Seamonkey included **[1]**

Expected result:
Dictionaries and language packs should be compatible with Firefox only

Notes:
- for language packs, besides Firefox, Android compatibility is also present **[2]**
- reproduced on AMO -dev with FF61, Win10x64

**[1]** - dictionaries
![image](https://user-images.githubusercontent.com/31961530/44343706-5cdffc00-a497-11e8-8a9e-34514b984bcf.png)

**[2]** - lang packs
![image](https://user-images.githubusercontent.com/31961530/44343725-6d907200-a497-11e8-93ba-958a0ad1c17e.png)

**Comment by diox** [comment]
Just a display issue, this will all get cleaned up when we remove thunderbird code entirely.

**Comment by eviljeff** [comment]
@AlexandraMoga is this still reproducible?

**Comment by diox** [comment]
It is still an issue but now that we only have 2 apps to care about we could tweak the CSS to avoid it.

**Comment by AlexandraMoga** [comment]
Still happening

**Comment by eviljeff** [comment]
We don't think this is worth fixing really.
