### ISSUE TITLE
The List Ratings API returns a cached GET after a PATCH

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9208]
### Describe the problem and steps to reproduce it:

See https://github.com/mozilla/addons-frontend/issues/5986 for STR. The [List Ratings API](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#list-ratings) returns a cached GET after a PATCH.

- When the page loads, it GETs `/api/v3/reviews/review/?addon=321&show_grouped_ratings=true&lang=en-US&wrap_outgoing_links=true`. This returns `ETag: abc`.
- A user edits their rating: PATCH `/api/v3/reviews/review/123/`
- The page GETs `/api/v3/reviews/review/?addon=321&show_grouped_ratings=true&lang=en-US&wrap_outgoing_links=true` again with `If-None-Match: abc`. This return a 304 with the same ETag, `Etag: abc`

### What happened?

The GET after the PATCH caused a cached version of the response to be used.

### What did you expect to happen?

The GET after the PATCH should not use a cached response.

### Anything else we should know?

- The second GET (or any others) after a PATCH returns a new ETag and doesn't trigger any caching
- If I slow down the requests by a few seconds, the caching problem goes away.
- For this specific bug, the data we're looking at comes from `show_grouped_ratings`

**Comment by diox** [comment]
Grouped ratings are not updated in real time on purpose. The query to generate them can take a short while on add-ons with lots of ratings, so it's cached, and updated asynchronously by a celery task when we save a rating instance (either a new or an existing one, doesn't matter).

Getting rid of that cache is not an option, and updating it in real time would slow down writes on add-ons with lots of ratings, so I don't think it's a good idea.

**Comment by eviljeff** [comment]
Is there anything to do here then?  Seems like from @diox's comment it's a WONTFIX

**Comment by kumar303** [comment]
Thanks for the info. I'll close it. We'll have to think of some kind of optimistic UI approach to it.
