### ISSUE TITLE
Users with Addon:PostReview permission can't see any entries in the Add-on Review Log

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9215]
STR:

1. Log in to AMO with a user that has Addon:PostReview permissions
2. Access Reviewer Tools dashboard
3. Click on Add-on Review log

Actual result:
There are no entries visible in the Add-on review Log

Expected result:
There should be entries related to webextension reviews visible in the Add-on Review log  

Notes:
- could be a regression from #9206 
- reproduced on AMO -dev with FF61, Win10x64

![no reviews post review](https://user-images.githubusercontent.com/31961530/44393804-52c50880-a53e-11e8-9c26-9a97291ced73.gif)

**Comment by eviljeff** [comment]
@jvillalobos can you confirm what permissions should be able to view addon reviews?  I (naively, it seems) just used `'Addons:Review'`

**Comment by jvillalobos** [comment]
I believe we need to include `Addons:Review`, `Addons:ContentReview`, and `Addons:PostReview`.
/cc @wagnerand to confirm.

Moving up to P2 since it's a regression that could affect reviewers.

**Comment by wagnerand** [comment]
Sounds good. We can skip `Addons:ThemeReview`for now.

**Comment by eviljeff** [comment]
> Sounds good. We can skip `Addons:ThemeReview` for now.

adding support for `Addons:ThemesReview` (#9049) was what caused this regression.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage with FF61, Win10x64
