### ISSUE TITLE
Previews are not correctly displayed for a theme with an additional background picture and centered top alignment

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#9227]
STR:
1. Load on AMO -dev and use the samples I attached to submit: I used   "additional_backgrounds": [ "morning-left.png" ] or   "additional_backgrounds": [ "dawn-left.png" ],  "additional_backgrounds_alignment": [ "center top"  ] and color picked a color "accentcolor": "pink"
2. Observe the preview displayed
3. Install the static theme
4. Compare the preview with the installed theme

Actual result:
The preview contains more the color from the picture used as additional background and less the pink (chosen for the general background). 

Expected result:
The preview looks like the theme installed meaning the blue/yellow are the colors centered and the background is pink.

Notes:
This is reproducible on AMO dev and AMO stage with FF61(Win10). 

Samples attached
[preview versus install.zip](https://github.com/mozilla/addons-server/files/2310346/preview.versus.install.zip)
[The one with preview problems.zip](https://github.com/mozilla/addons-server/files/2310347/The.one.with.preview.problems.zip)

Previews versus installed themes
![sample one](https://user-images.githubusercontent.com/33448286/44464327-2a630a00-a623-11e8-9486-ecc97205aae2.png)
![sample2](https://user-images.githubusercontent.com/33448286/44464335-2df69100-a623-11e8-9937-d5225624cfb9.png)

**Comment by eviljeff** [comment]
I'm confused about the two zips - are you saying both are broken (are they broken in different ways??).

Also, it's difficult to see the problem if the screenshot shows an extra wide browser window vs. a rendered preview at 680px wide.

**Comment by ioanarusiczki** [comment]
@eviljeff Well, both have the same problem with the previews, I only changed the .png background file to give two examples. If you install them, you should see that it's clearly a difference. 

For example - the first screenshot from the issue I filed - The preview: shows a yellow toolbar and it's pink at the middle. The Browser after installing it shows exactly the opposite and also the correct display of the theme meaning it's a pink toolbar with a yellow middle.

**Comment by ioanarusiczki** [comment]
@eviljeff 
1. I verified this with FF63(Win10) on AMO dev - the fix sure looks way better 

Before the fix - preview displayed by AMO + installed on FF on full screen windows monitor

![before the fix](https://user-images.githubusercontent.com/33448286/44785958-4aeb1100-ab9b-11e8-869d-d30d4a9ce642.png)

After the fix -  preview displayed by AMO + installed on FF on full screen windows monitor

![after the fix](https://user-images.githubusercontent.com/33448286/44785981-59392d00-ab9b-11e8-9404-1f4b7d0b8e2e.png)

Also when I resize the browser the installed theme in the browser starts to look more and more like the preview. 

2. I'm thinking of filing a new issue though. I tested with the "right top" and "left top" alignment - it is the only property changed in the samples I gave.

The "left top" is fine, I don't see any problems but for the "right top" alignment the preview is again quite different then it should be.

Left top alignment - looks good 

![left top](https://user-images.githubusercontent.com/33448286/44787063-bedae880-ab9e-11e8-9bd9-a9423f7672d9.png)

Right top alignment- the blue in the preview is way to the left - please take a look

![right top](https://user-images.githubusercontent.com/33448286/44788003-84267f80-aba1-11e8-8d58-78d01d566bfa.png)

**Comment by eviljeff** [comment]
@ioanarusiczki have you got screenshots at a similar size to the preview?   If the browser size is significantly different it could very well look different.

**Comment by ioanarusiczki** [comment]
@eviljeff 
Well resizing the browser it will look more and more like the preview indeed
Here's the above sample 
![resized to browser](https://user-images.githubusercontent.com/33448286/44794157-8e03af00-abb0-11e8-8ac8-8b13fed60123.gif)

And here's another example with a JPG non transparent sample used as background - notice that the pink background is only displayed by the browser.

 It looks like we are hitting again the known issue https://github.com/mozilla/addons-server/issues/7804 

![another example resized browser](https://user-images.githubusercontent.com/33448286/44794209-ab387d80-abb0-11e8-95eb-b1043f4b8c49.gif)

**Comment by eviljeff** [comment]
Right, so it's working as expected then.  Product made the decision in #7804 that the render is okay at this size and the fact the theme may look different at a large size is unavoidable.

**Comment by ioanarusiczki** [comment]
Yes, I can mark this verified fixed on AMO dev with FF61 (Win10), FF63 (Win10), because the previews for what I initially filed this are alright now.
