### ISSUE TITLE
Make `additional_backgrounds` align to the top right, matching Firefox behavior

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9233]
Split off from https://github.com/mozilla/addons-server/issues/9163. The preview was implemented as the documentation on MDN specified the behavior (main background is top right, additional backgrounds are top left). However, Firefox implements the expected behavior (all backgrounds are top right), so the preview should do the same.

**Comment by AlexandraMoga** [comment]
Theme previews for static themes using additional backgrounds without specified alignments are matching the current display for FF61

**- AMO preview and theme installed in Firefox 61**
https://addons-dev.allizom.org/en-US/firefox/addon/multi-backg-no-align/

![image](https://user-images.githubusercontent.com/31961530/44569498-4da4cb00-a783-11e8-8eca-01dba19061d4.png)

However, the layout changed again with the latest Nightly, where backgrounds are aligned to the left corner:

**- AMO preview and theme installed in Firefox 63.0a1(build 20180823220048)**
![image](https://user-images.githubusercontent.com/31961530/44569752-0d921800-a784-11e8-9972-d698fbfdea49.png)

I've also left a comment in https://github.com/mozilla/addons-server/issues/9163 where I raised the issue to product

**Comment by AlexandraMoga** [comment]
FF 63.0a1 was fixed to display images on the top right by default.
