### ISSUE TITLE
Don't consider the 'application' field in collection mandatory in the admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9236]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
- Edit a collection through the django admin

### What happened?
- application field is mandatory

### What did you expect to happen?
- application field should not be mandatory

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO  -dev with FF61, WIn10x64

![application null](https://user-images.githubusercontent.com/31961530/44574371-e7737480-a791-11e8-998f-eb292bc0a3b3.gif)
