### ISSUE TITLE
Use "Firefox user" instead of "Anonymous user" when user doesn't have display name

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9242]
It looks like we automatically generate names like "Anonymous user e467f3" when the user hasn't set a display name. That kind of name causes distrust when reading reviews or looking at developer names, so we want to use something a bit friendlier. So, the above generated name should be "Firefox user e467f3" instead.

**Comment by kvaluruk** [comment]
This string is returned through the `src/olympia/users/models.py`'s `UserManager` class. It also requires a test to be changed. 
Can I work on this?

**Comment by EnTeQuAk** [comment]
@kvaluruk it should be easy enough, there is also one test to change in `src/olympia/users/tests/test_models.py` that tests this functionality.

Feel free to work on it, just let us know so that we can assign the correct labels.

**Comment by kvaluruk** [comment]
@EnTeQuAk working on it!

**Comment by vcarciu** [comment]
Verified as fixed : 
![ffuser](https://user-images.githubusercontent.com/1583842/44726646-db185000-aae0-11e8-8e96-cb9c29b187d4.png)
