### ISSUE TITLE
Add better django debug toolbar support

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9247]
I'm using it more and more often and it's really nasty to set-up and install on addons-server.

We removed support for it years ago but somehow I'm not convinced it's a good idea. It provides a lot of really useful information that we should make use of much more often.

Currently, something like https://gist.github.com/EnTeQuAk/2ad62aeb384cf4425d01c36ae7c5a359 is needed. In addition you'll have to add your dockers ip addresses to `INTERNAL_IPS`. This should bring you pretty far using django debug toolbar. I keep forgetting, it then works only either if you're using `olympia.test:5000` directly or only via nginx :man_shrugging: 

We should really make this easier.

**Comment by diox** [comment]
Done a few months ago in 766ac85e1a69e820bb33c26ec26c31b0ce749c2f
