### ISSUE TITLE
Duplicate reports of flagged user ratings in moderation queue

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#9253]
In the Ratings Awaiting Moderation Queue, there are a lot of duplicates of user ratings that have been flagged for moderation, especially for user ratings that have been flagged by multiple users for moderation. 

It would be great if moderators only saw one instance of a rating that had been flagged for moderation.

**Comment by AlexandraMoga** [comment]
I suspect this is the same issue as https://github.com/mozilla/addons-server/issues/6948

**Comment by jvillalobos** [comment]
Yes, seems to be a duplicate.
