### ISSUE TITLE
Unable to submit a review with emojis on Android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#9263]
STR:
1. Load AMO dev and login then go to an add-on's detail page
2. Click on the stars to make a review and insert an emoji too into the text box
3. Observe the screen

Actual result:
Review cannot be saved, "Internal Server Error" message is displayed. 

Expected result:
Review is successfully submitted.

Notes:
Issue is reproducible on -AMO dev with FF61(Android 8.0) with developer's reply too.
It is not reproducible on AMO stage right now - could be a regression.

![android emoji problem](https://user-images.githubusercontent.com/33448286/44658781-97531700-aa0a-11e8-805b-f713e5466e97.png)

**Comment by eviljeff** [comment]
probably a dupe of #8923

**Comment by diox** [comment]
Sentry traceback : https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4623995/

The error is returned by MySQL, so this is definitely #8923. Is there a link of the resulting review on stage?

**Comment by ioanarusiczki** [comment]
@diox I logged it separately because last week verification for regressions were requested for https://github.com/mozilla/addons-frontend/issues/5998 and https://github.com/mozilla/addons-frontend/issues/6055
Also I remember this was not reproducible for reviews when I logged https://github.com/mozilla/addons-frontend/issues/5649 and https://github.com/mozilla/addons-frontend/issues/5644 previously moved on server by @muffinresearch here https://github.com/mozilla/addons-server/issues/8923
But I can't prove it because I checked it again today and it is reproducible on both servers.
I wouldn't mark as a dupe because when the server issue is fixed this can be verified by QA -  it covers the emoji testing scenario for the reviews and their replies.

**Comment by muffinresearch** [comment]
> Sentry traceback : https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4623995/

> The error is returned by MySQL, so this is definitely #8923. Is there a link of the resulting review on stage?

This is interesting. IIRC the previous issues I saw resulted in the text after the emoji being eaten by the DB but no other visual errors. I wonder if these errors are happening silently elsewhere.

**Comment by ioanarusiczki** [comment]
This issue was fixed along with https://github.com/mozilla/addons-server/issues/8923
verified on all AMO servers with FF65(Win10 &Android 8.0)
