### ISSUE TITLE
Don't allow use of "Mozilla" or "Firefox" in add-on names

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9267]
Companion issue for https://github.com/mozilla/addons-linter/issues/2158

Up until now, we've allowed add-on names to end with "for Firefox" or "for Mozilla". For SEO reasons, we don't want to allow this anymore. XPIs with add-on names containing "Firefox" or "Mozilla" should not be allowed in the submission flow.

**Comment by LordGameleo** [comment]
I can work on it. Can you tell me how to start with it?

**Comment by MeridelW** [comment]
@jvillalobos 

A submission field change: Limit submission field to the new limit (don't let user go past this initially, even before submitting).

**Comment by jvillalobos** [comment]
@MeridelW I think that comment belongs on a different issue?

**Comment by eviljeff** [comment]
@AlexandraMoga it's the same as https://github.com/mozilla/addons-server/issues/9489#issuecomment-432168096 - all the issues under https://github.com/orgs/mozilla/projects/39 that introduce new restrictions are behind that waffle so they can be announced/launched at once.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev, FF62, WIn10x64

With the  `content-optimization` waffle on, addons with "for Mozilla | Firefox" in their name can't be submitted:
![image](https://user-images.githubusercontent.com/31961530/47419703-6df20580-d785-11e8-9050-0727b1f9acee.png)

![image](https://user-images.githubusercontent.com/31961530/47419715-72b6b980-d785-11e8-9eae-215672d83348.png)

This restriction doesn't impact Mozilla users (with `@mozilla` in their email address)
