### ISSUE TITLE
Restrict @mozilla.com guids for new add-ons 

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9278]
Expanding on https://github.com/mozilla/addons-server/issues/4688, we should only allow GUIDs ending with `@mozilla.com` if the account submitting the add-on is also `@mozilla.(com|org)`. This only applies to new submissions, not updates.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF62, Win10x64

External users that are trying to submit an add-on with a guid ending in `@mozilla.com` will receive the following error message during validation:

![image](https://user-images.githubusercontent.com/31961530/45349976-6dc5ee00-b5bb-11e8-816f-e18046932934.png)

The guid restriction is not applied if the user is submitting a new add-on version.

@diox 

The restricted guids seem to be case sensitive, i.e. if an external user is submitting an add-on with a guid ending in `@Mozilla.com|org` there will be no error generated.
Should the restriction be extended to non lower case formats too?

**Comment by AlexandraMoga** [comment]
Cc @jvillalobos for his opinion on



> The restricted guids seem to be case sensitive, i.e. if an external user is submitting an add-on with a guid ending in `@Mozilla.com|org` there will be no error generated.
> Should the restriction be extended to non lower case formats too?

**Comment by jvillalobos** [comment]
Thanks, I filed a followup for it.
