### ISSUE TITLE
Update message template for "new published extension" 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#9281]
The [message template](https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/email/submission.txt) for the "new published extension" auto-email from AMO should be updated with [this text](https://docs.google.com/document/d/1msQ-vvDi7GDK04bTp8P5MJgiXoejTrSZ_EOay7HCUA0/edit#heading=h.4ln03gjbbwl3) [Google doc]. 

cc: @wagnerand

**Comment by kvaluruk** [comment]
@caitmuenster should the `submission.html` file be changed accordingly as well?

**Comment by jvillalobos** [comment]
Yes, both should be changed.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

The new notification content can be checked [here](https://addons-internal.dev.mozaws.net/en-US/admin/mail#msg-8184)
