### ISSUE TITLE
Legacy pages can't be accessed from the new frontend when navigating in some new added locales

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9290]
STR

1. Load AMO on any server
2. Change your locale to `ia` (Interlingua) - https://addons.allizom.org/ia/firefox/
3. Click on Developer Hub in the header

Actual result:
A page not found is opened (the URL redirect looks broken (https://addons.allizom.org/en-US/firefox/ia/developers/)

Expected result:
User lands on Developer Hub homepage

Notes;
- the other locale I was able to reproduce with is `az` (Azerbaycanca)
- the same issue happens when accessing any page in Developer Hub or Reviewer Tools
- we had the same issue in the past and was fixed in https://github.com/mozilla/addons-server/issues/7004
- reproduced on all AMO servers with FF61, Win10x64

![locales issue](https://user-images.githubusercontent.com/31961530/44789255-c7ceb880-aba4-11e8-9c20-c7260b816a73.gif)

**Comment by diox** [comment]
QA: I left `ia` disabled on purpose, because it's an obscure locale that isn't supported by mozilla products at the moment. I enabled `az` though.

**Comment by AlexandraMoga** [comment]
Verified fixed for `az` on AMO -dev with FF61, WIn10x64 

![locals-az](https://user-images.githubusercontent.com/31961530/44916717-1dd76380-ad3f-11e8-9f83-9373f65ab4b9.gif)
