### ISSUE TITLE
Changing FF version from dev to one below the version used won't work correctly

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#9301]
STR:
1. Load AMO stage and go to your add-ons from dev hub
2. Go to the manage version page for one of the add-ons
3. Change the Firefox compatibility to a FF version that is below FF61 (or the one you're working on), click the save changes button
4. Click the View Listing page

Expected result:
Red message "This add-on is not compatible with your version of Firefox" is visible and the install button is greyed out.

Actual result:
No message available and the install button is active.

Notes:
Issue is not reproducible for setting a higher version of FF then the actual operating one - I'm on FF61 and I choose the minimum accepted version to FF62 and save changes and go to the listed page "This add-on requires a newer version of Firefox (at least version xy.0). You are using Firefox ab.0" red message is displayed and the install button is inactive. Same for the  "This add-on is not available on your platform." if I remove the FF compatibility.

This is reproducible on AMO dev and AMO stage with FF61,63 (Win10).

FF57 compatibility as seen on FF61 - no changes available 
![message not displayed](https://user-images.githubusercontent.com/33448286/44841190-7594a280-ac4b-11e8-939c-ed7f5368516f.gif)

FF63 compatibility as seen on FF61 - works 
![it works for higher versions](https://user-images.githubusercontent.com/33448286/44841429-fa7fbc00-ac4b-11e8-86e5-c78d1ef64d0e.gif)

**Comment by diox** [comment]
> Change the Firefox compatibility to a FF version that is below FF61 (or the one you're working on), click the save changes button

Are you talking about changing the *maximum* version ? If so, that's expected behavior **unless** the add-on is using strict compatibility.

**Comment by ioanarusiczki** [comment]
@diox -
I'm working with FF61 - my add-on is compatible with FF61 but I'm changing that (I reduce the maximum to FF60) to see if I will get on the new front end the compatibility warning message. 

![this won t work](https://user-images.githubusercontent.com/33448286/44860603-50ba2280-ac7f-11e8-8434-3d660308e1c7.png)

The scenario that works  -I'm using FF61 and I am changing the compatibility (I set minimum 63) to see if I get on the new frontend the warning message.

![this works](https://user-images.githubusercontent.com/33448286/44860725-9a0a7200-ac7f-11e8-97eb-ff90c2047acd.png)

**Comment by diox** [comment]
Reducing the maximum compatibility has no effect (unless your add-on has strict compatibility set), but this is a feature, not a bug :) Has been that way for years.

**Comment by ioanarusiczki** [comment]
@diox Had no idea this is applicable only for strict compatibility set - I checked it with a language pack and got the expected result. 
![acholi language pack](https://user-images.githubusercontent.com/33448286/44903896-64649800-ad16-11e8-8523-f30510ff3661.png)

It's noted.
