### ISSUE TITLE
File archives for disabled add-ons can't be opened after download

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9302]
Follow up for #8985 

STR:
1. Log in to AMO with an Admin account
2. Go to the Admin pages and open the File management tool - `/admin/models/files/`
3. Open the details for a File of a disabled add-on - [see this example](https://addons-internal.stage.mozaws.net/en-US/admin/models/files/file/325891/change/?_changelist_filters=q%3Ddevhubrelease2308)
4. Save the file by right clicking on the 'Download File' link -> Save link as....
5. Try to open the saved archive 

Actual result:
The downloaded file looks like an `.xpi` but if you try to open it, the archiving tool will not recognize the file as an archive

Expected result:
Downloaded files can be opened and inspected

Notes:
- if you click on the Download file link you will see that it redirects to a Page not Found
- this issue can be reproduced with all the following add-on categories: Invisible, Disabled by Mozilla, Disabled by user, Unlisted add-ons
- reproduced on AMO stage with FF61, Win10x64

Step by step video:

![files for disabled add-on](https://user-images.githubusercontent.com/31961530/44843366-da063080-ac50-11e8-8771-90da2add32a2.gif)

**Comment by EnTeQuAk** [comment]
Hmm, I wonder if the file actually exists. Did you upload this add-on yourself before?

The file you're downloading is that 404 error page that you get when you click on the link. This doesn't seem to be happening with all disabled add-ons, it worked for me locally.

I'll look into it.

**Comment by AlexandraMoga** [comment]
Yes, the one I've downloaded is a file from an add-on I've submitted myself. 

I could not find any disabled add-ons with a working download link though

see other examples: 
https://addons-internal.stage.mozaws.net/en-US/admin/models/files/file/322264/change/?_changelist_filters=q%3Dwebext-trytobebeta
https://addons-internal.stage.mozaws.net/en-US/admin/models/files/file/322823/change/?_changelist_filters=q%3D%257Ba5dddade-a769-4af5-98e6-77d51e01c5f7%257D

Unlisted:
https://addons-internal.stage.mozaws.net/en-US/admin/models/files/file/325676/change/?_changelist_filters=q%3Dunlisted-09-08

**Comment by AlexandraMoga** [comment]
FYI: you can check [here](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10640485/change/?_changelist_filters=q%3Dalexandra.moga) the permissions associated to the account I'm testing with

**Comment by wagnerand** [comment]
I can't reproduce this anymore using the given example file. Please reopen if you come across this again.

**Comment by AlexandraMoga** [comment]
I could not reproduce this anymore either. I've tried with the examples from the issue and with some more recent files.
