### ISSUE TITLE
Clicking on Download File in /admin/models/files/ will trigger an installation instead of a download

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9303]
Follow up for #8985 

STR:
1. Log in to AMO with an Admin account
2. Go to the Admin pages and open the File management tool - `/admin/models/files/`
3. Open the File details for an Approved add-on - [see this example](https://addons-internal.stage.mozaws.net/en-US/admin/models/files/file/325883/change/?_changelist_filters=q%3Ddevhubrelease2308)
4. Click on the Download File link

Actual result:
An installation is triggered

Expected result:
File archive is downloaded

Notes:
- similar to #8426
- reproduced on AMO -stage with FF61, Win10x64

![file install](https://user-images.githubusercontent.com/31961530/44844240-015dfd00-ac53-11e8-9d8b-36d6b95f13eb.gif)

**Comment by LordGameleo** [comment]
I would like to know more about this issue and how can I help it.

**Comment by AlexandraMoga** [comment]
This issue is still valid

**Comment by AlexandraMoga** [comment]
Still reproducing

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

[Download file link triggers download]
![2020-10-12_17-21-40](https://user-images.githubusercontent.com/31961530/95757521-ebcfb400-0caf-11eb-8a9f-f1e0233500a3.gif)
