### ISSUE TITLE
Link to the Version file from /admin/models/files/ triggers a 504

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9304]
Follow up for #8985 

STR:
1. Log in to AMO with an Admin account
2. Go to the Admin pages and open the File management tool - `/admin/models/files/`
3. Open any File details  - [see this example](https://addons-internal.stage.mozaws.net/en-US/admin/models/files/file/325883/change/?_changelist_filters=q%3Ddevhubrelease2308)
4. Click on the link next to the Version field

Actual result:
The link is triggering a 504 when opened

Expected result:
The link should open `https://addons-internal.stage.mozaws.net/en-US/admin/models/versions/version/<number>/change/`

Notes:
- reproduced on AMO stage with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/44844530-dde78200-ac53-11e8-9e64-184da5312a79.png)

**Comment by LordGameleo** [comment]
I would like to know more about this issue. Can anyone tell me how can I help with it?

**Comment by wagnerand** [comment]
Actually, I am duplicating this against #10775. It's the same issue and has some more context on it.

**Comment by AlexandraMoga** [comment]
This was fixed in #10806 
Marking issue as verified fixed based on the results mentioned in https://github.com/mozilla/addons-server/issues/10775#issuecomment-469704578
