### ISSUE TITLE
Aucun thèemes ne fonctionnent

### ISSUE THREAD

**Issue by nancusson** [mozilla/addons-server#9310]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Depuis juillet dernier, je tente de changer le thème de mon environnement thunderbird afin de le personnaliser.

### What happened?
Malheureusement, lorsque choisit un thème sous l'onglet "Films et télévision thèmes", je choisis le thème que je désire en cliquant sur "+ ajouter a thunderbird", il y a une nouvelle page qui s'affiche et il est inscrit : Nous sommes désolés, mais nous ne pouvons pas trouver ce que vous cherchez.
La page ou le fichier que vous vouliez n’a pas été trouvé sur notre site. Il est possible que vous ayez cliqué sur un lien mort, ou que l’adresse entrée soit erronée. 
Si vous avez saisi l’adresse, vérifiez-la.
Si vous avez suivi un lien, merci de renseigner un bogue. Dites-nous d’où vous veniez et ce que vous cherchiez, nous ferons notre maximum pour faire en sorte de corriger le problème. 
Vous pouvez aussi faire un tour sur nos pages populaires.
Est-ce qu’une liste de modules en vedette vous intéresse ?
Est-ce que vous voulez rechercher des modules ? Vous pouvez aller sur la page de recherche ou simplement utiliser le champ de recherche ci-dessus. 
Si vous préférez recommencer, rendez-vous sur la page d’accueil des modules. 

### What did you expect to happen?
Je croyais pouvoir remplacer mon thème sans succès

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
est-ce moi qui ne fait pas la bonne méthode?

**Comment by diox** [comment]
Bonjour,

Le site pour signaler un problème avec les add-ons pour thunderbird est maintenant https://github.com/thundernest/addons-server/ ; les liens ne sont pas encore à jour. 

Ce problème en particulier a déjà été signalé: https://github.com/thundernest/addons-server/issues/19
