### ISSUE TITLE
Developer Hub pages do not have JS functionality (devhub-min.js is not getting generated)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9322]
### Describe the problem and steps to reproduce it:

- Open the Developer Console and go to the Network tab
- Load any developer hub page such as https://addons-dev.allizom.org/en-US/developers/addon/validate

### What happened?

The `devhub-min.js` bundle is a 404. Example: https://addons-dev-cdn.allizom.org/static/js/zamboni/devhub-min.js?build=4f4a94c0-5b8965d9

### What did you expect to happen?

It should not be a 404. This file defines JS functionality that the page relies on.

### Anything else we should know?

This is not a deploy issue. It started happening today and kept happening for each build. The `devhub-min.js` file is copied from the Docker container. When inspected, the file was not there https://irccloud.mozilla.com/pastebin/KCaMT0y8/

**Comment by AlexandraMoga** [comment]
I've navigated through various dev hub pages and the content seems to be loading correctly now:

![image](https://user-images.githubusercontent.com/31961530/44974274-ce27b080-af67-11e8-9792-a302bf57ed6f.png)

I'm marking the issue as verified fixed on AMO -dev with FF61, Win10x64
