### ISSUE TITLE
Require Admin:Advanced permission to access files admin

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9324]
The files admin from #8985 should require `Admin:Advanced` permission for now and not `Admin:Tools`. We might want to open it up later with a new permission - but for now `Admin:Tools` is too lax, that permission should only give you base access.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64

Users with `Admin:Advanced` permission can access `admin/models/files/`, can search for files by guid and slug, can download file contents*

Overview of user permissions listed [here](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10641527/change/)

* file download is possible, however, only for Approved add-ons. For other statuses i'm hitting #9302 

I'm going to mark this issue as verified fixed as all the issues found around the Files Tool functionality were reported already.
