### ISSUE TITLE
Theme categories marked as mandatory during ST submission when selecting Cancel and disable version

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9338]
STR

1. Log in to Developer Hub
2. Submit a new static theme (wizard or packed)
3. Once your upload is validated, proceed to the next submission step
4. In the submission details page, scroll down to the bottom and click on `Cancel and Disable version` button

Actual result:
Theme categories are highlighted as mandatory in order to complete the cancellation step

Expected result:
Submission is cancelled

Notes:
- similar to https://github.com/mozilla/addons-server/issues/9139
- reproduced on all AMO servers with FF61, Win10x64

![mandatory fields](https://user-images.githubusercontent.com/31961530/44989808-ba943e00-af97-11e8-96ff-f3a1c4021320.gif)

**Comment by kvaluruk** [comment]
Can I work on this? 
If yes, is it to be done in a similar way as in #9154 ?

**Comment by eviljeff** [comment]
@kvaluruk I think you're right - just adding that html attribute on buttons in those two templates should be enough.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

![categories theme](https://user-images.githubusercontent.com/31961530/45077726-98fd9880-b0f6-11e8-8ad3-6b4cfdbce3f6.gif)
