### ISSUE TITLE
replace django-cors-headers fork with upstream parent

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9341]
A few years ago we forked https://github.com/ottoyiu/django-cors-headers to add `CORS_ENDPOINT_OVERRIDES` as https://github.com/mstriemer/django-cors-headers.  Our request to merge the functionality was [denied](https://github.com/ottoyiu/django-cors-headers/issues/171) but, now we have a simpler CORS setup, we should be able to do the alternative suggested here https://github.com/ottoyiu/django-cors-headers/issues/171#issuecomment-261365499.  This way we're not stranded on an unmaintained fork that we haven't touched for 2 years.

**Comment by eviljeff** [comment]
Had a preliminary investigation: we only make use of `CORS_ENDPOINT_OVERRIDES` for local dev, and addons-dev.m.o, and it's possible we don't need the addons-dev.m.o settings.  

I think we _do_ need it for local dev using addons-frontend though, at least until #9080 allows addons-frontend to run under the same domain (http://olympia.test)

**Comment by diox** [comment]
Upstream now has [Signals](https://github.com/ottoyiu/django-cors-headers/#signals) that may be enough to re-implement our overrides.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label qa:not needed?
Thanks
