### ISSUE TITLE
Remove white and blacklist

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#935]
Because this matters to me: http://mckay.pub/2015-01-07-allowed/

**Comment by tofumatt** [comment]
Good post; good idea. :+1:  :heart:

**Comment by muffinresearch** [comment]
The whitelist change was reverted in https://github.com/mozilla/addons-server/pull/3904 since it broke -dev. The env file needs updating in tandem with this change and then the revert can be reverted.

**Comment by andymckay** [comment]
Next need to fix up a couple of external process.

**Comment by EnTeQuAk** [comment]
I'm just going to close this issue. Not saying that this isn't important and I do agree we should keep that in mind but it's nothing we'll tackle anytime soon.
