### ISSUE TITLE
Add the add-on's name and icon_url to review API responses

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#9357]
To support https://github.com/mozilla/addons-frontend/issues/6104 and https://github.com/mozilla/addons-frontend/issues/5858 we need to display the add-on name and its icon on the User Profile screen in the section where we list reviews by a particular person. The data we use for this comes from https://addons-server.readthedocs.io/en/2018.05.17/topics/api/reviews.html#list-reviews, which returns `review` objects as detailed at https://addons-server.readthedocs.io/en/2018.05.17/topics/api/reviews.html#review-detail-object. This currently only returns the `id` and `slug` of the add-on in question, but we would like to have it also return the `name` and `icon_url` of the add-on.

Note that the above mentioned issues are something we hope to land by the end of the quarter, so please let us know if adding this data in the near future is a possibility, or something that will be difficult to achieve.

**Comment by diox** [comment]
Seems doable. I've set it to p2 so that it gets done in the coming weeks.

**Comment by diox** [comment]
I assume https://github.com/mozilla/addons-frontend/issues/5527 will prevent you from using the v4 API if you want the add-on name in there. But we can have it in the v3 API IMHO, as it's a backwards-compatible change, only adding more fields that already exist elsewhere.

**Comment by bobsilverberg** [comment]
@diox I don't think that's a blocker. I interpreted that issue as simply stating that we might have to implement the upgrade piecemeal, as opposed to all in one go, so I figured we could start with the reviews API.

Having said that, having to do fewer things to land this specific feature is definitely a good thing, so if it's not a burden to you to add the fields to the v3 API, that would be helpful to us.

**Comment by diox** [comment]
Done, added to both v3 and v4.

**Comment by bobsilverberg** [comment]
Amazing! Thanks @diox!

**Comment by AlexandraMoga** [comment]
Verified fixed with the `/v3/` and `/v4/` api's:

![image](https://user-images.githubusercontent.com/31961530/45426619-68dd6900-b6a5-11e8-9c5e-c48bf463f176.png)
