### ISSUE TITLE
Compatibility Test tool from Dev Hub homepage can't be accessed

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9364]
STR:

1, Access Dev Hub homepage while being logged out - https://addons.allizom.org/en-US/developers/
2. Scroll down to the Tools section and click on Compatibility Test - https://www.extensiontest.com/

Actual result:
The page is detected as unsecured, so it won't be loaded

Expected result:
The page is successfully loaded 

Notes:
- reproduced on AMO stage with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/45153220-ed2e7880-b1db-11e8-94e1-edcc79fcdfff.png)

**Comment by diox** [comment]
@jvillalobos that site does appear to be a Mozilla property, but I'm not familiar with it. Do you know who/what team manages it so that they can update their certificate ?

**Comment by muffinresearch** [comment]
I've emailed ops and Amy about this.

**Comment by caitmuenster** [comment]
Amy asked me to pick this up. 

Let's replace "Compatibility Test" and its explanation with: 
 
### Live testing (link to: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox)
Temporarily install your extension in Firefox for live testing and debugging.

**Comment by AlexandraMoga** [comment]
@diox  I'm still seeing the Compatibility checker instead of the new Temporary installation link an -dev:

![image](https://user-images.githubusercontent.com/31961530/45284592-9ed5ee00-b4e9-11e8-8508-c8bc1815d8fe.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

![devhub loggout](https://user-images.githubusercontent.com/31961530/45345442-fbe7a780-b5ae-11e8-802a-e41b29dfaf1c.gif)

**Comment by potch** [comment]
I worked with webops and extensiontest.com is back online! apologies for the downtime.
