### ISSUE TITLE
Webextension dictionaries without an ID in their manifest can't be installed

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9366]
Prerequisites:
- open latest Nightly or an unbranded version of Firefox and set:
`xpinstall.signatures.required - false`
`xpinstall.signatures.dev-root - true`

STR:
1. Go to a webextension dictionary details page - see https://addons.allizom.org/en-US/firefox/addon/dictionar-webextension-no-id/
2. Install the dictionary

Actual result:
The dictionary is not installed because Firefox sees it as corrupt

Expected result:
The dictionary is installed 

Notes:
- Console error
`1536155905717 addons.xpi WARN Download of https://addons-dev-cdn.allizom.org/user-media/addons/496262/svenska_fria_ordlistan-1.2.1webext.xpi?filehash=sha256%3A95dc49558432fe3762bb155b0af0fc4427aa734a88d6a02a72607ffda4ff9db0 failed: Error: Cannot find id for addon C:\Users\ALEXAN~1.MOG\AppData\Local\Temp\tmp-fme.xpi (resource://gre/modules/addons/XPIInstall.jsm:1545:19) JS Stack trace: loadManifest@XPIInstall.jsm:1545:19`
- reproduced on all AMO  servers with FF62, Win10x64
- Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1489106

![webext dict install](https://user-images.githubusercontent.com/31961530/45156747-b8282300-b1e7-11e8-94bd-dde0440956ac.gif)

**Comment by AlexandraMoga** [comment]
Update: In the context of dictionaries migration to webextension format, if the user has a previous legacy version installed and tries to update to a webextension version from addons manager, there won't be any updates found.

**Comment by AlexandraMoga** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1489106 is marked as invalid from a Firefox perspective

**Comment by diox** [comment]
Does this happen with webextension dictionaries that have been properly signed ?

**Comment by AlexandraMoga** [comment]
I've uploaded a webextension dictionary (unlisted) in prod and tried to install it but I'm still seeing a 'corrupt' message

@diox not sure if this is what you mean by 'properly signed'

**Comment by diox** [comment]
It is. Can you link the add-on here ?

If it's signed (with prod to be sure it's not just an issue with dev/stage) then Firefox should be able to extract the id from the signature, and therefore it should install correctly on Firefox. I want to double-check that add-on before asking you to re-open that bugzilla issue.

**Comment by diox** [comment]
It looks ok to me. Please re-open the Firefox issue, attaching the signed XPI (as downloaded from devhub) to it. As far as I can see it should install correctly.

**Comment by diox** [comment]
So in the end, per [Andrew Swan comment in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1489106#c8), we do need ids:
> So, dictionaries require an ID in the manifest.

I"ll fix the migration script to generate ids.

That also means we should also open a linter bug to force this at validation time as well.

**Comment by diox** [comment]
I opened https://github.com/mozilla/addons-linter/issues/2188 and https://github.com/mozilla/addons-server/issues/9460 to deal with this issue. Let's close this one.
