### ISSUE TITLE
The reviews endpoint can return a deleted review with no indication it is deleted

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#9371]
STR:

1. Authenticate with an admin-level user.
2. Issue a GET request for a particular review, e.g., https://addons-dev.allizom.org/api/v3/reviews/review/563182/?lang=en-US&wrap_outgoing_links=true

Expected result:

The deleted review, which is returned because the user has admin access, has some indication that it is deleted.

Actual result:

The returned review object looks just like a normal review, with no data to indicate it has been deleted.

**Comment by diox** [comment]
We have the following options:
- Remove that feature entirely
- Force clients to pass `filter=with_deleted` even for a detail request - taking care of `PATCH`, `DELETE` as well.
- Return a `deleted` property or something similar in the rating object

**Comment by bobsilverberg** [comment]
I think keeping the "feature" is fine, but I do think we should return a `deleted` property or something similar in the rating object, so that the frontend can inform a user they are viewing a deleted rating/review.

**Comment by AlexandraMoga** [comment]
Verified on dev and stage. 

`is_deleted` property is now expposed in the `/ratings/rating` api endpoint:

https://addons.allizom.org/api/v4/ratings/rating/715875/

![image](https://user-images.githubusercontent.com/31961530/46398207-284d9a00-c6fd-11e8-8db3-d28cba137b94.png)
