### ISSUE TITLE
Error page returned after selecting 'user-review' from Akismet reports

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9381]
Follow up for https://github.com/mozilla/addons/issues/781

STR:

1. Log in to Admin Tools
2. Go to Akismet Report
3. Click on 'user-review' link for any of the listed reports

Actual result:
An error page is displayed

Expected result:
The link should open `https://addons-internal.dev.mozaws.net/en-US/admin/models/akismet/akismetreport/<number>/change/`

Notes
 - reproduced on AMO -dev with FF62, Win10x64

![user-review](https://user-images.githubusercontent.com/31961530/45222331-f2afbf80-b2bc-11e8-86ac-b8c250d5e981.gif)

**Comment by eviljeff** [comment]
seems to be https://sentry.prod.mozaws.net/operations/olympia-dev/issues/4678569/ but I don't understand the error

**Comment by diox** [comment]
The failure is django admin trying to get a Content Type instan)ce for this model, ending up having to insert one because there aren't any yet, and somehow failing... That's... interesting.

**Comment by diox** [comment]
Oh, I know what's going on. This whole content type automatic creation works fine usually, but it looks like we didn't apply the migration when we switched to Django 1.11, so our content type table still has a `name` column that the model doesn't know about.

The migration we're missing is https://github.com/django/django/blob/master/django/contrib/contenttypes/migrations/0002_remove_content_type_name.py

**Comment by AlexandraMoga** [comment]
@eviljeff regarding `https://addons-internal.dev.mozaws.net/en-US/admin/models/akismet/akismetreport/<number>/change/`,  will admins be able to delete a review by accessing this page?

**Comment by AlexandraMoga** [comment]
As expected, `product-summary`, `product-name` and `product-description` links are also affected.

**Comment by diox** [comment]
I applied the migration on dev & stage in https://github.com/mozilla/addons-server/issues/9382

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev and stage with FF62, WIn10x64

All links from Akismet reports can be opened now 

![akismet links](https://user-images.githubusercontent.com/31961530/46014922-895fe700-c0d9-11e8-8fd8-994e4b0455d4.gif)
