### ISSUE TITLE
GitHub wants me to change my password because I used that same password somewhere else!!

### ISSUE THREAD

**Issue by rAllcorn** [mozilla/addons-server#9387]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

I do not plan to change my password ... that was "ME" your system is reporting.  
I just had to replace my laptop; old one failed after 8 years.

**Comment by eviljeff** [comment]
This isn't the issue repository for github, it's for issues on addons.mozilla.org (specifically the backend django part).
