### ISSUE TITLE
Can't reach add-ons beyond 25000 (= the 1000th page with page_size 25) via the search API (/api/v3/addons/search/)

### ISSUE THREAD

**Issue by motin** [mozilla/addons-server#9392]
### Describe the problem and steps to reproduce it:

Goal: We need a full list of the add-ons published on AMO, but requesting any results set from the API beyond the 25000th add-on yields `{"detail":"Invalid page."}`

**Details:**
Requesting the first page of results from https://addons.mozilla.org/api/v3/addons/search/?app=firefox&type=extension&page=1 gives the following metadata:

     "page_size":25,"page_count":1000,"count":26556

Since the max page_count is 1000 and 25*1000, I can't list the add-ons beyond 25000. [Attempting to reach page 1001 yields](https://addons.mozilla.org/api/v3/addons/search/?app=firefox&type=extension&page=1001) `{"detail":"Invalid page."}`

### What happened?

1. page_count is 1000
2. `{"detail":"Invalid page."}` upon navigation to the pages requires to list the add-ons beyond 25000

### What did you expect to happen?

1. I expect the page_count to be equal to Math.ceil(count/page_size), in this case 1063 (Since 26556/25 = 1062,24)
2. I expect navigation to the pages requires to list the add-ons beyond 25000 to list the add-ons

### Anything else we should know?

Seems to be related to "AMO website: Navigating past page 1000 is not possible #552 ", but not directly related to the one that https://github.com/mozilla/addons/issues/552 is marked a duplicate of ([New AMO pages don't return correct number of pages after empty search #3887](https://github.com/mozilla/addons-frontend/issues/3887)), since there is no empty search involved. 

(Originally incorrectly reported against https://github.com/mozilla/addons as https://github.com/mozilla/addons/issues/788, where @willdurand suggested that there is a hard limitation on the API side)

**Comment by diox** [comment]
This is by design to relieve some pressure of our elasticsearch cluster, due to the way we paginate through the results. Originally the number was chosen to be slightly higher to the maximum number of extensions we have to give us some breathing room, but it looks like it's no longer enough.

Since we'll eventually remove all legacy add-ons I doubt we'll change this soon. To work around it you can use different sort parameters to get all add-ons.

**Comment by motin** [comment]
Using different sort parameters (and then deduplicating the result sets based on id/guid) is a rather complicated workaround and leaves no guarantee that all add-ons are indeed included. 

Reverse-sorting could be a valid workaround to effectively increase the hard limit to 50.000 by fetching the results from the other direction, but I couldn't find a way to reverse the sort order on https://addons-server.readthedocs.io/en/2018.05.17/topics/api/addons.html#search

Traversing through all different platforms, filtering on each one of them doesn't work either since the total count is over 25k in each platform.

The only viable workaround seem to be to traverse through all categories and filter on each one of them, hoping that no single category has more than 25k add-ons. Since a single add-on can be included in multiple categories, this requires deduplication on the final result set. 

Before implementing this workaround in the various studies and ETL jobs that expect a complete list of available add-ons, are you sure you won't be increasing the limit anytime soon, or is there any other data source to use to fetch information of all add-ons published via AMO? (We will be requiring information also on older add-ons so this will be of increased relevancy after all legacy add-ons are removed from these API results)

**Comment by jvillalobos** [comment]
FWIW, no category holds more that 5K extensions.

**Comment by motin** [comment]
[Added sort parameter as workaround - to at least get the 25k most popular add-ons](https://github.com/motin/fetch-amo-addons-metadata/commit/37082e605d3cd0ed45ba636b4d01b03d7ab85419)
