### ISSUE TITLE
Add a file with the current deployed python version

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9396]
From: https://github.com/mozilla/addons-server/pull/9390#issuecomment-419951143

> I thought it redundant and could be confused with prod_common. But I could see an argument for having a deploy.txt, or something similarly named, if we are going to have to specify the filename somewhere (though ideally it'd all be done via the make recipes which has python version detection).

**Comment by AlexandraMoga** [comment]
@eviljeff should this be a qa:not needed?

**Comment by AlexandraMoga** [comment]
Thanks, that's a good thing to know.

![image](https://user-images.githubusercontent.com/31961530/51965585-abe08300-2472-11e9-80da-7576c8dce616.png)

This issue is verified fixed.
