### ISSUE TITLE
update privacy policy link on Disco Pane

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#9400]
At the bottom of the "Get Add-ons" page in the Add-ons Manager (Disco Pane), the Privacy Policy links to an incorrect destination. 

Currently it links here:
https://www.mozilla.org/privacy/websites/

Per Mozilla Legal, it should link here:
https://www.mozilla.org/privacy/firefox/#addons

@muffinresearch

**Comment by devaneymoz** [comment]
@muffinresearch good point. Do we know who owns that page and perhaps we could request a polish?

**Comment by muffinresearch** [comment]
I've filed https://github.com/mozilla/bedrock/issues/6164

**Comment by eviljeff** [comment]
re-filed @ mozilla/addons-frontend#6264
