### ISSUE TITLE
Add Extension Compatibility Test back to Dev Hub Homepage 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#9401]
Related to issue #9364. :) 

Please add the Compatibility Test back to the Dev Hub Homepage in the "Tools" column above "Live Testing" . 

Copy: 

Compatibility Test (link to: https://www.extensiontest.com/) 
Check to see if your extension is compatible with Firefox.

**Comment by LordGameleo** [comment]
Can I know more about it..... I am interested to work on it.
