### ISSUE TITLE
Reviews flagged by Aksimet which are deleted from the Moderation queue do not appear in the Review Moderation log

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9413]
Follow up for https://github.com/mozilla/addons/issues/781

STR:

1. Log in to AMO stage with a user that has Review moderation permissions
2. Go to the Review moderation queue - https://reviewers.addons.allizom.org/en-US/reviewers/queue/reviews
3. Search for a review flagged as Spam by Aksimet (it should appear flagged by Mozilla)
4. Select the 'Delete review' moderation action and click on Process Reviews
5. Check the moderation log to see the event for your last action - https://reviewers.addons.allizom.org/en-US/reviewers/moderationlog

Actual result:
There is no event logged for the submitted delete action

Expected result:
Spam reviews flagged by Akismet should appear in the review moderation log when they are deleted

Notes:
- not reproduced on AMO -dev
- not reproduced with Approved reviews (by selecting action 'Keep review; remove flags'
- reproduced only on AMO stage with FF62, Win10x64

![moderate delete](https://user-images.githubusercontent.com/31961530/45475736-eeb0f100-b745-11e8-9fab-5ce608bedd24.gif)

**Comment by eviljeff** [comment]
I can't replicate this - I deleted two reviews just now that were flagged by Mozilla and they're both in the Moderated Review Log at the top.

**Comment by AlexandraMoga** [comment]
I'm not reproducing it either. It could have been something temporary after all:

![image](https://user-images.githubusercontent.com/31961530/45953605-43405000-c013-11e8-8513-920619329820.png)
