### ISSUE TITLE
Deleting an extension makes its ID unsignable forever

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9417]
### Describe the problem and steps to reproduce it:

See https://github.com/mozilla/web-ext/issues/1111 for the original bug report.

1. Create a new extension on your local machine
2. Run `web-ext sign -v` to sign it (this uses the [signing API](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html))
3. Delete the extension from DevHub
4. Create a new version of the same extension in your source code (retaining the same ID)
5. Try to run `web-ext sign -v` again.

### What happened?

It signed the extension (maybe) but the XPI cannot be downloaded. Example:

```
$ curl https://addons.mozilla.org/api/v3/file/745574/firephp_for_firefox_devtools-0.1.0pre_1508200790-fx.xpi?src=api
{"detail":"Authentication credentials were not provided."}
```

### What did you expect to happen?

It should let you download the signed XPI without errors.

### Anything else we should know?

I haven't tried to reproduce this myself but it has been reported by multiple users in https://github.com/mozilla/web-ext/issues/1111

This seems to be a commonly encountered bug, maybe because developers are experimenting with `web-ext sign` and deleting the first experiment.

**Comment by eviljeff** [comment]
> It signed the extension (maybe) but the XPI cannot be downloaded. Example:

```
$ curl https://addons.mozilla.org/api/v3/file/745574/firephp_for_firefox_devtools-0.1.0pre_1508200790-fx.xpi?src=api
{"detail":"Authentication credentials were not provided."}
```

Wouldn't you _always_ get that error message if you try to download an unlisted file without authentication?

**Comment by diox** [comment]
You definitely need authentication for the `/api/v[3-4]/file/[int:file_id]/` endpoint, yeah.

**Comment by diox** [comment]
Wouldn't be surprised if this was actually another variant of https://github.com/mozilla/addons/issues/324

**Comment by kumar303** [comment]
Ah, whoops, the curl output (above) is irrelevant but web-ext is still seeing a 404 (see https://github.com/mozilla/web-ext/issues/1111)

Yes, this does sound like a dupe of https://github.com/mozilla/addons/issues/324 but I'm not 100% sure.
