### ISSUE TITLE
Dictionaries and Language Packs page includes broken extensions

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9418]
### Describe the problem and steps to reproduce it:

- Go to https://addons.mozilla.org/en-US/firefox/language-tools/ (which is built with https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#language-tools)
- Click on Akan Spelling Dictionary which leads to https://addons.mozilla.org/en-US/firefox/addon/akan-ns%C9%9Bmfuaasekyer%C9%9B/

### What happened?

This dictionary is broken because it's non-restartless (Firefox says it is corrupt); non-restartless extensions no longer work in the latest Firefox. 

### What did you expect to happen?

Maybe this extension shouldn't have been included in the list? It was last updated three years ago.

### Anything else we should know?

This came up when QA was testing the site. I'm told that Akan isn't even a language supported by Firefox anymore. Maybe this listing needs to be a bit smarter? There are other old extensions in the list that might not work anymore.

**Comment by jvillalobos** [comment]
The list is hand-curated, and we haven't updated it since we moved to an automated release system for language packs. I'll go over the list and remove the stale ones.

**Comment by jvillalobos** [comment]
The list should be up to date now. Since the current plan is to move language packs off of AMO, I don't think we should invest in anything that is automatic. Most language packs are being automatically managed by Mozilla now anyway.

**Comment by willdurand** [comment]
I still see the non-restartless add-on in -prod.

**Comment by AlexandraMoga** [comment]
@willdurand If I remember correctly, the language tools page from the frontend is cached for 24h for performance reasons - https://github.com/mozilla/addons-server/issues/6850 . This could be the reason why the changes are not visible yet.

**Comment by jvillalobos** [comment]
Sorry, I only did the list of language packs. The dictionaries in the previous comment should be gone after the cache clears.

**Comment by AlexandraMoga** [comment]
The list looks updated now
