### ISSUE TITLE
Generate 720x97 theme preview images

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9419]
Discussing with @MeridelW and @brassy- about the future of add-on visualization, it came up that theme preview images should be 720px wide. The current ones are 680×92px. Using the same ratio, that puts the desired dimensions as 720x97px.

The new preview image size would be used in _future_ designs for add-on pages and the disco pane, which wouldn't be worked on until ~~P1~~ Q1. However, we probably want to get on top of this before there are hundreds or thousands of preview images to regenerate.

A couple of options:
* Continue generating 680×92 and add a new 720x97, which would be temporarily unused.
* Switch to generating 720x97 and just slightly scale it down for theme pages.

@eviljeff, what do you think?

**Comment by eviljeff** [comment]
> worked on until P1

I'm guessing you meant Q1 (2019 Q1) 😉

**Comment by eviljeff** [comment]
There's no technical reason why we couldn't start to generate a 3rd size.

Though, in addition to 680x92 we already generate 760x92 which is used for the search results page.  Does it make sense to have 3 different sizes, that become 2 different sizes in the future, but only 40px difference in width?  IMO we should see if we can settle on a single size if there's that little difference.  (Then have frontend also change to use it for all the pages)

Is there any logic behind 720px wide btw?  I'm not aware of any behind the current 680x92 size (perhaps it just looked "good" on getpersonas?)  Fwiw, I think the current height (92px) is ideal-ish, so if 720 is the sweet spot for width then 720x92.

**Comment by jvillalobos** [comment]
Let's get @pwalm and @brassy- to weigh in about this. Questions are:

* Is it okay to change the width without changing the height? So, stick to 92 instead of switching to 97. Since the preview is generated from an SVG, there's no distortion to worry about.
* For width, we currently use 680 on product pages and 760 on search result pages. Can we standardize on 720 across the board, or should we do 720 for future product pages and keep 760 for search results?

**Comment by pwalm** [comment]
* yep, don't see any issue to change the width slightly without changing the height (as long as there is no image distortion).
* 720 across the board sounds like a good direction to go in, barring any weird/new design constraints. And is this 720 that we can scale down to whatever we want? Or just 720?

**Comment by jvillalobos** [comment]
> And is this 720 that we can scale down to whatever we want? Or just 720?

If there is some other place where we expect to regularly show a smaller version of the preview, it's ideal that we also generate a thumbnail with those dimensions. There's one we show on the Dev Hub that is 473×64, for example. Scaling down is not a terrible thing to do, though.

**Comment by eviljeff** [comment]
@rebmullin fyi on future frontend changes needed.

**Comment by rebmullin** [comment]
@jvillalobos @pwalm the reason we had 760px for search is so the image would span the the whole width at larger desktops. Otherwise it leaves a gap on these larger sizes.  There is some discussion here about this: https://github.com/mozilla/addons-frontend/pull/5067#issuecomment-393477675.

//cc @eviljeff

**Comment by eviljeff** [comment]
(Don't take my UX advise but) can't you just center it and have a 20px gap at each end? :)

**Comment by rebmullin** [comment]
yeh we definitely can do that too :) but the alignment would be a tad off in these cases:

![Alt text](https://monosnap.com/image/Llw8zMOnTjk2rkazta66dvdLqegZXq.png)

This only happens when above ~ 1300 tho so maybe this is okay..?

**Comment by jvillalobos** [comment]
I think it should be left-aligned, like extension results. And maybe the right-aligned elements like user counts should also have a limit of how far right they can go (if they don't already). But @pwalm and @atsay should also weigh in.

**Comment by atsay** [comment]
Yea, I think it will be fine left-aligned, in @rebmullin's example.

**Comment by AlexandraMoga** [comment]
I've checked the api response for a new submitted static theme and this includes now a third theme preview:

-  image_size:720x92; thumbnail_size:501x64

![image](https://user-images.githubusercontent.com/31961530/46283271-a0408680-c57c-11e8-8512-7a49e014a197.png)

- the previews are accurate - there are no distortions

[720x92](https://addons-dev-cdn.allizom.org/user-media/version-previews/full/0/563.png?modified=1538388615)
![image](https://user-images.githubusercontent.com/31961530/46283433-10e7a300-c57d-11e8-9902-72171f831092.png)

[501x64](https://addons-dev-cdn.allizom.org/user-media/version-previews/thumbs/0/563.png?modified=1538388615)
![image](https://user-images.githubusercontent.com/31961530/46283513-3bd1f700-c57d-11e8-8b35-ead38952b39a.png)

Reviewer Tools are showing all three previews, stacked:

![image](https://user-images.githubusercontent.com/31961530/46283985-dda61380-c57e-11e8-9964-add04d0133e0.png)



In #8693 it was decided to leave all reviews visible in Rev Tools, so we might do the same in this case, considering that in the near future there will be a unique size anyway,

**Comment by rebmullin** [comment]
hey @jvillalobos, now that this new size is available, should we change this on the frontend in search and the header or are we waiting to Q1?  If yes, I'll open an issue if there's not one already..

**Comment by jvillalobos** [comment]
I think we only need to wait for https://github.com/mozilla/addons-server/issues/9519 to be resolved before making that change. It's not an urgent thing, but please file an issue so we can keep track.
