### ISSUE TITLE
Implement a more direct way of deleting a review from the site through Akismet reports

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9423]
STR:

1. Open Akismet reports from Admin Tools - https://addons-internal.dev.mozaws.net/en-US/admin/models/akismet/akismetreport/
2. Identify a false negative review report (Ham) and submit it back as Spam to Akismet
3. Try to delete the reported review from the site

Actual result:
There is no direct way for the admin to manage/delete a user review from the site through Akismet reports

Expected result:
Admins should have a more direct way of deleting a review Submitted as Spam through Akismet reports

Notes to consider:
- the new frontend doesn't currently  allow Admins to delete a review from an add-on reviews page
- when a false negative review (Ham) is submitted back as Spam to Akismet, that review will not be logged in the Moderation queue where a review moderator could pick it up an delete it from the site
- the Admin has the possibility to delete a review by using the Ratings Tool from django admin, but this method implies navigating to a different page and searching through reviews to identify the one that needs to be deleted

A possible solution would be to add a shortcut to the rating management page (i.e. https://addons-internal.dev.mozaws.net/en-US/admin/models/ratings/rating/563346/change/) next to each review report

**Comment by jvillalobos** [comment]
Akismet is gone.
