### ISSUE TITLE
Add a parameter to the ratings endpoint for exclude_review_id

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#9424]
We would like to be able to request a list of reviews, but have a particular review excluded from the list by id. This would be a new parameter for the API documented at https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#list-ratings, and will be used to address an edge-case issue introduced in https://github.com/mozilla/addons-frontend/pull/6183.

**Comment by eviljeff** [comment]
Notwithstanding "what about doing x instead" rarely being a helpful reply because you already thought about it... why can't you just hide the duplicate rating in the list of ratings client-side?  Is it because the numbers won't match up?

**Comment by bobsilverberg** [comment]
Yes, we're actually already doing the work in the front-end, but we'll have a problem with pagination where the counts returned from the API won't match the number of records that we're displaying. This issue is to address that, and once this fix lands we'll remove our code on the front-end which is currently excluding the review we don't want.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:


1. request without `exclude_ratings` parameter:

https://addons-dev.allizom.org/api/v4/ratings/rating/?addon=add-on-indexing&filter=without_empty_body
```
"page_size": 25,
"page_count": 1,
"count": 8,
```

2. request with `exclude_ratings` parameter:

https://addons-dev.allizom.org/api/v4/ratings/rating/?addon=add-on-indexing&filter=without_empty_body&exclude_ratings=563636,563482

```
"page_size": 25,
"page_count": 1,
"count": 6,
```
