### ISSUE TITLE
Make @mozilla.com|org restriction case-insensitive

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9425]
Followup of https://github.com/mozilla/addons-server/issues/9278. We restrict add-on guids ending in `@mozilla.com` or `@mozilla.org` to Mozilla accounts. It's currently an exact match, but that check should be case-insensitive.

**Comment by kvaluruk** [comment]
I'd love to tackle this one. 
I have a doubt (:sweat_smile:) though. Will the changes need to be made in the `system_addon_submission_allowed()` function in `olympia/users/utils.py`?

**Comment by diox** [comment]
(mentor: me)

@kvaluruk yep, that's the one. Please also add a test for your changes - to do this you can modify the list of guids used for testing in `/src/olympia/users/tests/test_user_utils.py`.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64
New version submissions  with a restricted guid are allowed. 

![image](https://user-images.githubusercontent.com/31961530/45620867-e844b100-ba86-11e8-9f0b-8957b195f873.png)
