### ISSUE TITLE
word-break: break-all CSS makes addon description look bad

### ISSUE THREAD

**Issue by shatgupt** [mozilla/addons-server#9429]
With `word-break: break-all` CSS on the edit addon page, the descriptions break in between words making them look bad. They look fine on the listing page.

Screenshot: 
![screenshot 8](https://user-images.githubusercontent.com/2388644/45601198-11e5d580-b9be-11e8-92d0-d177de9bb0ac.png)

The code: https://github.com/mozilla/addons-server/blob/a702dc185370ce0d7aea4becbe81cd9acee6ead5/static/css/zamboni/developers.css#L20
Was it intended to be `word-break: break-word`? I can send a PR if someone can tell me the intended value.

**Comment by diox** [comment]
That particular `work-break` was introduced in 0fa80ccb2695f23e86a92e720d654dbcc91b8199 to fix #6698. The thing is, Firefox does not support `word-break: break-word`, so I think changing this is the wrong move.

You can try to fix this locally, but make sure any fix does not regress https://github.com/mozilla/addons-server/issues/6698 - try adding an unbroken long string in the summary and see if the page layout still looks ok (look at the fixed screenshots from #6698)

**Comment by shatgupt** [comment]
I was not sure what should have been the correct value. Thanks for the clarification.
I will try to fix it without regressing #6698

**Comment by shatgupt** [comment]
I have a dirty solution right now to just add another rule: `word-break: break-word;` below the current one `word-break: break-all;`. This way Chrome will do `break-word` and Firefox won't recognize `break-word` and fall back to `break-all`.

Reading the long discussions [here](https://github.com/w3c/csswg-drafts/issues/2390) and [here](https://github.com/w3c/csswg-drafts/issues/2951), I am not able to figure out a proper solution to the problem.

**Comment by muffinresearch** [comment]
We should just remove `word-break`. See also https://github.com/mozilla/addons-server/issues/6971

**Comment by preeti98** [comment]
Hello everyone! May I please work on this bug, in case no one is already working on it? Thanks in advance!
I have previously contributed to Mozilla by Bugzilla, but am not familiar with the workflow here, at GitHub.So, it would be great if someone could please guide me on the same.Thanks again!

**Comment by ParasSharma7** [comment]
Hey! Can anyone please tell me how to reproduce this issue?

**Comment by caitmuenster** [comment]
Hey all, it looks like @shatgupt has been working on this. @shatgupt, how's it going with this issue?

**Comment by shatgupt** [comment]
Got busy in somethings else.
I can confirm the fix suggested by @muffinresearch. Removing `word-break` and setting `max-width` solves the issue without regressing https://github.com/mozilla/addons-server/issues/6698.
I will be sending a PR soon.

**Comment by shatgupt** [comment]
PR raised: https://github.com/mozilla/addons-server/pull/9587
