### ISSUE TITLE
Add a cron job to clear out 90 day + AkismetReport records

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9438]
Legal would like us to limit how long we store the AkismetReport check records for, and it's good housekeeping in any case.

**Comment by diox** [comment]
Probably goes nicely in the `amo.cron.gc` cron that is fired daily. We already delete old `FileUpload`s in there.

**Comment by eviljeff** [comment]
Good point.  I guess either wait for a few more months or close as QA not needed.

**Comment by eviljeff** [comment]
(it's pretty simple, shouldn't need any testing really)

**Comment by AlexandraMoga** [comment]
@eviljeff please add a "qa:not needed" for now and I will add a reminder for myself to check this when the time comes :)
