### ISSUE TITLE
The add-ons video is a bit old skool

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#944]
Go to about:addons, click "watch the video" or "Learn more about add-ons".

A couple of things:
* It says "You can use personas", they got renamed to themes a while ago
* Two of the add-ons that it adds in "F1 by Mozilla Labs" and "Add to Amazon Wishlist" no longer exist

If we want to keep this video around, I bet we can find replacements for those add-ons and just update that.

**Comment by andymckay** [comment]
Personally, I think the video is pretty cool.

**Comment by atsay** [comment]
I think we'd need to start over, because it would be hard to edit the voice, and also--who has the original files?

**Comment by andymckay** [comment]
Only if we wanted to edit the voice. The links to the add-ons are done in JS and can be fixed up manually without touching the video. 

This video was a fligtar production.

**Comment by atsay** [comment]
Any opposition to getting the creative team involved?

**Comment by andymckay-limited-access** [comment]
None at all. But, might want to be filed under the "what does the future of
about:addons" look like.

**Comment by atsay** [comment]
Ah, then perhaps it would be premature to do a full update on the video. I'll ask fligtar if he remembers where the original files are.

**Comment by andymckay** [comment]
Any update on this for the disco pane refresh? @atasy or @deadsquid

**Comment by jvillalobos** [comment]
@atsay ^^

**Comment by atsay** [comment]
I filed this bug with the creative team to see if they can help: https://bugzilla.mozilla.org/show_bug.cgi?id=1262350

**Comment by andymckay** [comment]
Cool, thanks Amy. Closing this bug since we've got that bugzilla one open.
