### ISSUE TITLE
Unlisted extension submission is stuck in validation mode

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9448]
STR

1. Log in to AMO -dev
2. Submit a new unlisted extension
3. Check the validation results

Actual result:
Submission is stuck in validation mode

Expected result:
Add-on is passing validation

Notes;
- reproduced on AMO -dev with FF62, Win10x64
- In my previous submissions, I was able to reproduce with listed versions as well, but in my last attempts I was able to constantly reproduce only with unlisted versions

![image](https://user-images.githubusercontent.com/31961530/45698612-18687e80-bb71-11e8-96bb-c6e918a9c938.png)

**Comment by diox** [comment]
First one to figure out the problem wins 10 internet points.

**Comment by AlexandraMoga** [comment]
This looks fixed on -dev but I'm still having the issue on stage.
Additionally, stage is now throwing server errors at listed add-on uploads:


![image](https://user-images.githubusercontent.com/31961530/45734992-0f1df700-bbef-11e8-98d5-37c0192b05ac.png)

Hasn't the fix landed on stage yet?

**Comment by AlexandraMoga** [comment]
Verified fixed in stage too,
