### ISSUE TITLE
Fix firefox icon in compat-app dialog

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9451]
https://github.com/mozilla/addons-server/issues/8224 updated the firefox icon in the header but didn't change any of the existing icons.

That's why the Firefox icon in the compatibility app dialog during submission is still the old one.

In addition to that, it's a bit blurry.

**Comment by AlexandraMoga** [comment]
Verified fixed on dev and stage with FF62, Win10x64

Looking better now:

![image](https://user-images.githubusercontent.com/31961530/45799227-6a1a2180-bcb5-11e8-9007-dc10518bc49b.png)

![image](https://user-images.githubusercontent.com/31961530/45799234-6f776c00-bcb5-11e8-8fbc-7d4f5e44c825.png)
