### ISSUE TITLE
27 Septemeber homepage content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#9453]
Please update homepage content for the **27 Sept** push as detailed in the programming [doc](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by eviljeff** [comment]
@devaneymoz have you logged this in the wrong place?

**Comment by devaneymoz** [comment]
@eviljeff damnit I did! Should I refile on the front-end?

**Comment by eviljeff** [comment]
@devaneymoz I think so from the people you pinged (though the doc didn't make much sense to me)
