### ISSUE TITLE
Deactivate "Firefox for Android" for langpacks and dictionaries

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9456]
Followup from https://github.com/mozilla/addons-server/issues/8752

In the past during submission of dictionaries and langpacks "Android" was explicitly disabled because you cannot submit them for Android. This needs to be re-implemented.

**Comment by diox** [comment]
Note that dictionaries are currently in the `NO_COMPAT` list, so any compatibility info recorded is ignored later. This was originally made to deal with the fact that they were legacy extensions but we didn't bump their compatibility as we did for extensions. It should probably go away, but maybe after we completed the switch to webextensions.

**Comment by AlexandraMoga** [comment]
As an alternative solution (and possibly a more coherent flow), couldn't the application options be displayed only after the add-on was validated, similar to the previous platform selection options? After validation, we know what add-on type is submitted, therefore the unsupported application can be disabled by default. 
This would look better especially for static themes and language tools which are Android incompatible currently.
