### ISSUE TITLE
Server error received during add-on upload

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9458]
STR:

1. Log in to AMO -dev
2. Submit a new add-on
3. Check the validation results

Actual result:
For several upload attempts, there is a server error received during validation (500 or 502)

Expected result:
No server error is received during add-on upload

Notes:
- the issue is intermittent (I was able to reproduce it in 1 to ~10 upload attempts)
- probably a regression from #9353 
- reproduced on AMO -dev and stage with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/45741764-1817c400-bc01-11e8-8371-e8dbff9d71d8.png)

**Comment by AlexandraMoga** [comment]
Now I'm getting this error with almost all submissions

**Comment by eviljeff** [comment]
fixed by #9461, looks like

**Comment by AlexandraMoga** [comment]
Confirmed that I'm not getting any server errors during add-on validation now
