### ISSUE TITLE
All addons submitted by admin users are flagged as spam

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9459]
Follow up for #8704 

STR:

1. Log in to AMO with an Admin user (check the user I've tested with [here](https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/10640485/change/?_changelist_filters=q%3Dalexandra.moga))
2. Submit a new add-on
3. Check the validation results

Actual result:
The submission content is flagged as spam

Expected result:
There is no error generated  if the submission doesn't contain spam content

Notes:
- reproduced with all add-on types, at every submission attempt 
- reproduced on AMO -dev and stage with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/45742345-72fdeb00-bc02-11e8-856d-c7bb312a72a1.png)

**Comment by EnTeQuAk** [comment]
What content did you enter? Add-on name, summary, description?

**Comment by AlexandraMoga** [comment]
For most of the cases, the manifest has a name and a description (which is added as a summary in dev hub).
I've tried to submit the same extensions with non-admin users and there was no spam flagged raised.

For example, I've tried to submit https://addons.mozilla.org/en-US/firefox/addon/facebook-container/?src=search and it was marked as spam when I was logged in with an admin account.

**Comment by eviljeff** [comment]
WFM as of this morning on -dev.   (One of the other prs fixed this too?)
@AlexandraMoga can you re-test?

**Comment by AlexandraMoga** [comment]
@eviljeff -dev works for me as well. Marking issue as verified fixed.
