### ISSUE TITLE
Add an id to migrated webextension dictionaries manifests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9460]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1489106#c8 we discovered that Firefox does not extract the `id` from the signature when dealing with webextension dictionaries. This means the script that migrates legacy dictionaries to webextension ones need to add the id to the manifest it generates.

Note that https://github.com/mozilla/addons-linter/issues/2188 will also force webextension dictionaries submissions to provide an id in the manifest.

**Comment by diox** [comment]
QA found an issue while testing this, in the logs we can see `Migrating dictionary 496321 raised Duplicate add-on ID found`. I've submitted a PR to fix that.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, WIn10x64

- the migrated manifest contains the dictionary ID

![image](https://user-images.githubusercontent.com/31961530/46002326-7daef900-c0b6-11e8-9de4-96e0a4f1ec09.png)

- migrated dictionaries can be installed

![dictionary install](https://user-images.githubusercontent.com/31961530/46002355-8bfd1500-c0b6-11e8-8cfd-63fa54dea05f.gif)
