### ISSUE TITLE
Add-on name and summary edits are not saved in dev hub Edit information page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9462]
Follow up for #8704 

STR

1, Log in to AMO dev with a developer account
2, Edit an add-on that you own
3. Change the Name and the Summary
4. Click Save Changes

Actual result:
A "Changes Saved" message is displayed but the form is not closed. When clicking on Cancel, you will notice that the updates are not saved

Expected result:
Name and Summary can be edited from dev hub Edit information page

Notes:
- not reproduced when `akismet-spam-check` is switched off
- I did not reproduce with the description field
- reproduced on dev and stage with FF62, Win10x64

![name and summary](https://user-images.githubusercontent.com/31961530/45752214-620ea300-bc1d-11e8-9d1b-f66f36d4e1da.gif)

**Comment by AlexandraMoga** [comment]
This happens actually when Akismet interprets the name or summary input as spam, but dev-bub is not displaying an appropriate error message. Shows 'Changes saved' instead.

**Comment by eviljeff** [comment]
yeah, I figured that was what was happening - the 'Changes Saved' message isn't shown when the errors are included. #9477 shows the messages.  

It also adds checking to the details step in the upload flow (you can't change the name/summary to something spammy _after_ you've uploaded the xpi).  This also covers an edge case where a spammy addon could be uploaded as unlisted (which wasn't checked), then a listed version added and the metadata wouldn't be re-checked because you didn't change it.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF62, Win10x64

- the edit information page will show an error when spam input is added in the name or summary fields
- the name and summary fields are also checked in the second submission step, after the xpi is validated, to make sure no spam content was added in this step
- new listed versions added to an unlisted add-on are checked and blocked if they contain spam content (also when the metadata remains unchanged) 

![spam in edit info](https://user-images.githubusercontent.com/31961530/45945780-4f1e1900-bff7-11e8-875e-31845f953ff5.gif)


![image](https://user-images.githubusercontent.com/31961530/45945969-fac76900-bff7-11e8-8891-654882748a12.png)



@eviljeff regarding how the error message is displayed, I think it would be helpful to highlight the field that generated the error, otherwise the user might be confused. Right now, the error appears at the top and at the bottom of the edit form. This also applies to the form in the add-on submission step. 
This can be added as a follow up issue.

**Comment by eviljeff** [comment]
@AlexandraMoga it was a deliberate choice to not show it per field tbh - I read #8704 as it should just be a single error message and not hint what was spammy.  @jvillalobos can clarify.

**Comment by jvillalobos** [comment]
If you're referring to [this comment](https://github.com/mozilla/addons-server/issues/8704#issuecomment-416754833), I just meant that all of them need to pass in order for the form data to be accepted. I wasn't talking about error messages. I think it would be good to show independent error messages, if possible.

**Comment by AlexandraMoga** [comment]
Filed #9513 as a follow up.
I'm marking this issue as verified fixed.
