### ISSUE TITLE
Pressing back during add-on submission process will still submit add-on

### ISSUE THREAD

**Issue by mcomella** [mozilla/addons-server#9465]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I reproduced this on 2018-08-28 so I don't have the exact steps and the problem may have been fixed by then. Roughly:
- Click upload a new version of an add-on
- On "submit source code back", press back in the browser (I didn't have the source code so I wanted to back out until I wrote my script to tar up the source)

### What happened?
When I returned to the dashboard, the new version I was uploading was submitted and in review, even though it didn't have the source code I said I needed to include

### What did you expect to happen?
The add-on was not submitted

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

fwiw, this happened on version 0.4.0 of the [APT GitHub Improvements add-on](https://addons.mozilla.org/en-US/firefox/addon/apt-github-improvements/).

**Comment by eviljeff** [comment]
It's not pressing back that submits the addon - the version is created in the step before so unless you choose the "cancel & disable version" button the version is there and will be approved.

**Comment by jvillalobos** [comment]
I'm going to close this as wontfix for the following reasons:
1) What @eviljeff just said.
2) A new submission flow is planned for Q1 next year, so it's probably better not to make changes at this point.
