### ISSUE TITLE
Add a temporary pre-v4 endpoint to ease frontend transition away from /v3/

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9467]
**Problem:** 
Addons-frontend uses `/api/v3/` which is frozen and stable for Firefox to use, but we would like to move it to using `/api/v4/` mozilla/addons-frontend#5527 to get new API features.  But one breaking change in particular (always dicts for localized fields #8794) is making this a challenge to do in one move as a non-goal task.

**Current practise:**
So what we are currently doing is backporting any required API change from /v4/ to /v3/ (and crossing our fingers that because they aren't breaking changes it won't cause any Firefox regressions).

This, IMO, is not an acceptable solution.

**Solutions proposed so far:**
#8899 proposes a number of possible solutions involving being able to specify api feature-gates in the request so frontend (or any other client) can control which changes they want to use.  There isn't a consensus, and all the solutions will involve an unknown amount of work on addons-server and addons-frontend.
A final suggestion in #8899 is that maybe we wont need to do anything complicated - addons-frontend can just upgrade to `/api/v4/`.  But discussion mozilla/addons-frontend#5527 indicates that isn't easy to do after all.

So both of those solutions are not viable in the short term either.

**Hacky interim workaround proposal:**
We add a `/api/v3.5/` (or `/api/v3.9/` or `/api/v4a/` etc) which _only_ disables the breaking change (localized fields being dicts) and is otherwise `/api/v4/`.  This allows us to stop backporting changes to `/v3/` and allows us to upgrade frontend almost-all-the-way to `/v4/` and make the final fix at our leisure.
Addons-server can also implement #8899 (or similar) at our leisure.

**Comment by eviljeff** [comment]
> Wild suggestion: always disable the dicts for localized fields thing in v4, for now. 

That's actually not a bad idea. Generally I don't like the idea of a feature being unusable because code-rot but effectively that's what's happening anyway with frontend not using it, so yeah, for "the greater good".

> Then, when the frontend is ready to switch (by having their code being able to handle both would be my preference), enable it back.

It's probably going to be difficult to develop against it when it's not enabled on any API endpoint though.  So we'd need a `/api/v4a/` anyway that _did_ have `l10n_flat_input_output` removed, hah.  But, idea: only this API endpoint exist* on -dev and locally (and stage?) - that way we don't have another endpoint "in the wild", but it _can_ be developed against.  *(we can do this easily because it's a setting)

**Comment by diox** [comment]
> It's probably going to be difficult to develop against it when it's not enabled on any API endpoint though. So we'd need a /api/v4a/ anyway that did have l10n_flat_input_output removed, hah. But, idea: only this API endpoint exist* on -dev and locally (and stage?) - that way we don't have another endpoint "in the wild", but it can be developed against. *(we can do this easily because it's a setting)

That seems like a reasonable option. So, to sum up:
- Add `l10n_flat_input_output` gate to `v4` config, making `v4` behave like `v3` as far as l10n is concerned
- Add a `v4a` without that gate active, making it return objects all the time for l10n like we currently do for `v4`
- Make that `v4a` only available on dev & stage

**Comment by eviljeff** [comment]
I started this and change is trivial as expected, but quite a few tests are [failing](https://travis-ci.org/eviljeff/olympia/builds/431392767) because they expect the default api (v4) output to be dicts rather than strings.  We've got a few options:
a) change the test outputs to be flat strings, as `v4` will be (for some temporary period).
b) explicitly specify `v4a` as the api_version in the `reverse_ns` calls.
c) in test_settings.py, have `DEFAULT_API_VERSION= 'v4a'`  (+ local dev env....?)
d) in test_settings.py have the drf_gates for `v4` as they are now, i.e. without `l10n_flat_input_output`

**Comment by diox** [comment]
I'd go for a) or b). Thoughts, @EnTeQuAk ?

**Comment by AlexandraMoga** [comment]
@eviljeff is this change affecting the entire site/ only the frontend? It would be good to know where to focus our testing.

**Comment by eviljeff** [comment]
@AlexandraMoga frontend doesn't use `/api/v4/` yet so it shouldn't affect it.
