### ISSUE TITLE
Remove legacy discopane and show ... something to existing users

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9468]
Legacy discopane is still used by some ancient version of Firefox (version # needed) and we are going to remove it.  Previously Thunderbird and Seamonkey users also used legacy discopane but they have been redirected as part of the addons.t.n move.

Ideally existing Firefox users of that endpoint would just be directed to the new discopane but a) it doesn't work for them (no MozAddonManager support?  some other reason?) and b) their Firefox is too old to install webextensions so it's not that useful.  Even encouraging them to go to the homepage and look for add-ons is pointless as in a few weeks there will be no legacy addons for them to install.

So... a fixed page saying "How's about you upgraded already"?

**Comment by jvillalobos** [comment]
I initially thought that showing some form of disco pane would be useful, but you have a good point that soon there will be nothing for those users to install on AMO. 

Now I'm thinking we should replace the legacy disco pane with a static page encouraging users to upgrade to the latest version. /cc @atsay

**Comment by atsay** [comment]
That sounds good to me. Let's make sure the static page makes clear what the benefits are of upgrading.

**Comment by eviljeff** [comment]
@jvillalobos can you provide/corral copy&ux for this?

**Comment by jvillalobos** [comment]
Maybe we should just redirect to something like https://www.mozilla.org/firefox/new/? Would that work?

**Comment by eviljeff** [comment]
> Maybe we should just redirect to something like https://www.mozilla.org/firefox/new/? Would that work?

It's a good idea (assuming Firefox doesn't baulk at the redirect to a different website)

**Comment by diox** [comment]
QA:
- Download an old version of Firefox (recommend you use a fresh profile for this...) that would still show the legacy disco pane in about:addons. (I used Fx 15.0)
- Test that when changing `extensions.webservice.discoverURL` to point to dev about:addons shows the mozilla.org page telling you to download the latest version of Firefox
- Just to be sure, test that a newer version gets the new disco pane as normal.

**Comment by vcarciu** [comment]
Verified as fixed with FF15 : 
![oldff](https://user-images.githubusercontent.com/1583842/47090553-d3953d80-d22b-11e8-9f0f-6d5bea055723.png)

On newer versions we get the new disco pane and the modules are seen in promo section for legacy homepage
