### ISSUE TITLE
can't edit or delete item in Disco Pane admin

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-server#9469]
### Describe the problem and steps to reproduce it:
Can't edit or delete a specific content item in the admin tool. This is the culprit:

https://addons-internal.prod.mozaws.net/admin/models/discovery/discoveryitem/179/change/?_changelist_filters=p%3D0

### What happened?
I get an "Oops" page when I tried saving changes (I wanted to remove from Disco Pane featuring but when I adjust its rank and save, I get the Oops page; I also tried deleting the item and that didn't work either). 

@diox

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4725208/

**Comment by diox** [comment]
`OperationalError: (1366, "Incorrect string value: '\\xE2\\x99\\xA5Don...' for column 'object_repr' at row 1")` when saving the log entry for that action. That's... interesting. I guess this is actually https://github.com/mozilla/addons-server/issues/8923 in disguise and we'll have to find a funky workaround...

**Comment by diox** [comment]
Ah, fun times:
```
MySQL [addons_allizom_org]> SHOW FULL COLUMNS FROM django_admin_log LIKE "object_repr";
+-------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| Field       | Type         | Collation         | Null | Key | Default | Extra | Privileges                      | Comment |
+-------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| object_repr | varchar(200) | latin1_swedish_ci | NO   |     | NULL    |       | select,insert,update,references |         |
+-------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
```

`latin1_swedish_ci` ... That's definitely wrong. Not sure how many other columns are affected, but we need to fix them...

**Comment by diox** [comment]
@autrilla applied his migration script to this table, and it seems to have fixed the problem, at least where I can verify (dev & stage). @devaneymoz does that work for you now ?

**Comment by devaneymoz** [comment]
Appears to be working, thank you!
