### ISSUE TITLE
Disable all legacy add-on files

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9472]
Following up on https://github.com/mozilla/addons-server/issues/9147 and the plan we published in the [Add-ons Blog](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/), we need to disable all legacy add-on files.

What needs to be disabled:
* All legacy files of extensions and language packs, listed and unlisted, except for those internally signed by Mozilla.
* All complete theme versions.

This should be done early in October to meet the timeline we laid out.

**Comment by jvillalobos** [comment]
Once the files are disabled, nothing about them will be visible on the site. Add-ons that have only legacy versions will also stop being visible or searchable.

**Comment by JustOff** [comment]
@jvillalobos, are you going to remove the dictionaries too?

**Comment by diox** [comment]
QA: a command needs to be run to do this. Since it will disable a bunch of add-ons, let me know when you're ready for this to be done on dev & stage.

**Comment by AlexandraMoga** [comment]
@diox I think you can run the command for dev and stage  and I'm going to make time to test around this. Do you also want to push the changes in prod this week?

**Comment by jvillalobos** [comment]
We should wait for [bug 1495440](https://bugzilla.mozilla.org/show_bug.cgi?id=1495440) to be resolved before we run this in prod. Other than being late on our timeline, there's no strong pressure to do this.

**Comment by diox** [comment]
I've launched the script on dev - it worked except for a hundred or so files that failed because of a transaction issue. I'll be pushing a follow-up commit to work around this.

**Comment by diox** [comment]
Looks good now. The query I used to verify:
```
File.objects.only('id').filter(is_webextension=False, is_mozilla_signed_extension=False, version__addon__type__in=(amo.ADDON_EXTENSION, amo.ADDON_THEME, amo.ADDON_LPAPP)).exclude(status=amo.STATUS_DISABLED).exclude(version__addon__status__in=(amo.STATUS_DELETED, amo.STATUS_DISABLED)).exclude(version__deleted=True).count()
```

The signal handlers in our code should have disabled the corresponding add-ons when necessary (when they didn't have any public versions left) and re-indexed them.

**Comment by AlexandraMoga** [comment]
Test results for AMO -dev (FF62, ESR60, Win10x64 and Android 8.0)

- there are no visible regressions on the site
- disabled legacy add-ons are not present on the homepage shelves, in collections, in user profile pages or on disco pane
- only webextension versions are available to install on the add-on versions page
- there are no complete themes available on the site
- the language tools page on the frontend is listing only webext language packs; both legacy and webext dictionaries are listed

Dev Hub:
- for developers that still had legacy add-ons (listed or unlisted) in their submissions list, these add-ons are going to appear as Incomplete and all version files are disabled; developers still have the possibility to upgrade their add-on to a webextension by submitting a new version

@diox I do have some questions:

Rev Tools:
1. The [Unlisted queue](https://reviewers.addons-dev.allizom.org/en-US/reviewers/unlisted_queue/all?sort=version_date&page=2) still includes disabled legacy add-ons. Should those records be removed?
2. The [Addon Review Log](https://reviewers.addons-dev.allizom.org/en-US/reviewers/reviewlog?start=2013-10-01&end=2014-10-01&page=141) is holding entries for disabled legacy add-ons. Should they be cleared?

Admin
1. I can still see disabled legacy add-ons, like [Complete Themes](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?status__exact=4&type__exact=2) or [Legacy Extensions](https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/?p=30&status__exact=4&type__exact=1) with "Approved" or "Awaiting Review" status, even though all their files have been disabled.
Those listed as "Approved" in Admin are actually set as "Invisible" in Dev Hub, so far as I can see.

**Comment by diox** [comment]
1. and 2. : no. We only want to disable those add-ons & files for now, and that's it.
3. I think this is because of 2 things: I forgot to include disabled add-ons when I ran the script ("invisible" add-ons are actually user-disabled) and in addition we have some stray add-ons in a weird state. I'll see what I can do to clean that up.

**Comment by diox** [comment]
(Meanwhile: I ran the command on stage)

**Comment by vcarciu** [comment]
I tested on Stage with same results as for -dev. Since the remaining issues described above will be addressed in a different bug, I will mark this one as verified.

**Comment by jvillalobos** [comment]
Bug 1495440 has been resolved, so this is now free to be run.

**Comment by grahamperrin** [comment]
Is there a notional schedule for the run? 

Not chasing, just curious. 

TIA
