### ISSUE TITLE
Product-name and summary for localized add-ons are not correctly submitted to Akismet

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9476]
STR:

1. Log in to Developer Hub
2. Submit an add-on that supports various localisations
3. With an Admin account, check the Akismet reports for the submitted add-on

Actual result:
`Product-summary` and `product-name` seem incorrectly extracted (i.e displayed as `__MSG_name__`)

Expected result:
Localized strings are correctly displayed  by Akismet reports

Notes:
- this is an example submitted on the site: https://addons-dev.allizom.org/en-US/firefox/addon/privacy_badger/
- I've submitted the same example a few days ago and this issue did not occur 
- could it be a regression from #9461 ?
- reproduced on -dev and stage with FF62, Win10x64

[1] Akismet report for a localized add-on
![image](https://user-images.githubusercontent.com/31961530/45871891-3c0d0e00-bd97-11e8-874f-24b04810feae.png)

[2] same example from a few days ago
![image](https://user-images.githubusercontent.com/31961530/45871901-46c7a300-bd97-11e8-968c-4473aaef1657.png)

**Comment by eviljeff** [comment]
I'd say this is more "not correctly submitted" to Akismet rather than "not correctly rendered" in the admin tools, unfortunately.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/46200252-d205e300-c319-11e8-896e-beb11ae3ddb0.png)
