### ISSUE TITLE
Product-summary Akismet reports are sometimes logged without a result

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9480]
STR:

1. Log in to Developer Hub
2. Edit an add-on that you own
3. Enter a name that Akismet will interpret as spam (i.e. only special characters)
4. Leave the summary unchanged
5. Save our changes
6. With an admin account check the records from Akismet reports

Actual result:
There is a product-summary report logged even if the data wasn't changed. The result is not determined.

Expected result:
There should be no product-summary report logged if the summary is not edited

Notes:
- the undefined report will not show up when results are filtered by Unknown
- this is not reproduced during an add-on submission - i.e. if the name is detected as spam but the summary looks fine, Akismet will log the product-summary as Ham
- reproduced on AMO -dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/45878163-c5790c00-bda8-11e8-81fa-27118b0fa48c.png)

**Comment by eviljeff** [comment]
This is kinda deliberate - if there are multiple reports to Akismet comment_check and one fails as `SPAM` then the remaining reports don't get checked because we've already decided to block the addon/collection creation/update.  But I'm going to have to change that behaviour anyway to implement #9513

**Comment by AlexandraMoga** [comment]
The issue is not reproducing anymore by following the above steps. 
The product-summary entry is always logged with a valid result.

![image](https://user-images.githubusercontent.com/31961530/46281242-ca8f4580-c576-11e8-9d6d-415ddafe7fe9.png)

Marking issue as verified fixed on AMO -dev with FF62, Win10x64
