### ISSUE TITLE
Restrict add-on summary length

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9486]
On first submission and editing, the summary should be restricted between 2 and 140 characters long.

**Comment by MeridelW** [comment]
@jvillalobos Note: summary for extensions is required. Summary for themes is not required but encouraged for SEO.

**Comment by jvillalobos** [comment]
@MeridelW the current submission flow for themes requires a summary, and I don't know if product pages are designed to deal with no summary. Is it important to make it optional for themes?

**Comment by jvillalobos** [comment]
Superseded by https://github.com/mozilla/addons-server/issues/9243
