### ISSUE TITLE
Restrict screenshot upload dimensions and ratio

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9487]
For add-on submission and editing, the screenshots need to meet these restrictions:
- 4x3 width to height ratio.
- PNG or JPEG, PNG recommended
- 1000x750 px minimum
- 2400x1800 px recommended _and_ maximum

**Comment by MeridelW** [comment]
@jvillalobos Should we also note the following?:

-No SVGs
-No maximum size (though we have provided a minimum and recommended sizes)

**Comment by jvillalobos** [comment]
> No SVGs

Saying that PNG or JPEG are supported should be enough. I doubt there will be many attempts to upload an SVG anyway.

> No maximum size

I think the minimum and recommended should suffice. Saying "no maximum" explicitly might encourage some people to try to break things.

**Comment by jvillalobos** [comment]
We settled on 2400x1800 for the recommended and maximum. This is now reflected in the opening comment.

**Comment by eviljeff** [comment]
note #7908 chose the existing 1280x800 size because it's the same as Chrome Store (to help developers) and the ratio is different (1.33 vs 1.6)

**Comment by eviljeff** [comment]
@jvillalobos what do we want the thumb size as?  320x240?  What size would frontend be wanting?

**Comment by jvillalobos** [comment]
> note #7908 chose the existing 1280x800 size because it's the same as Chrome Store (to help developers) and the ratio is different (1.33 vs 1.6)

Yes, we're going a different way intentionally.

> what do we want the thumb size as? 320x240? What size would frontend be wanting?

It looks like it would be 640x480. /cc @atsay @pwalm to confirm

**Comment by eviljeff** [comment]
As a follow-up normally we'd run a task to recreate any thumbnails (and bigger "full" size where original size is available) but I don't see there being many|any existing images that fit the new size and ratio requirements.  If ratio isn't important there should be _some_ that are a bit bigger though.

**Comment by AlexandraMoga** [comment]
After uploading various image sizes and types through Dev Hub Edit information page, I have the following results:

- images that don't meet the required type (PNG or JPG) are not allowed
- images that do not fulfill the 4:3 ratio will generate an error 
- images with sizes smaller than 1000x750 will generate an error 

![image](https://user-images.githubusercontent.com/31961530/49013121-5216c080-f184-11e8-8924-37d4ac7d9e30.png)
![image](https://user-images.githubusercontent.com/31961530/49013126-57740b00-f184-11e8-8a8d-1bfea2c1f8e8.png)

@eviljeff question about the max allowed size:
There is no limitation in dev hub with regards to the maximum allowed size (2400x1800), i.e. larger images can be uploaded as long as they meet the 4:3 ratio. However, it looks like the picture has been resized to the max allowed size (2400x1800) after upload.
For example, [for this addon](https://addons-dev.allizom.org/en-US/firefox/addon/same-name/), the first [screenshot](https://addons-dev-cdn.allizom.org/user-media/previews/full/129/129409.png?modified=1543233474) has a 2400x1800 size, while the picture I've uploaded in dev hub had a 3264x2448 size.

Shouldn't there be an error for uploads that exceed that max size, similar to what we show for small images?

Regarding thumbnails, they are still rendered at 320x240 as far as I can see, so I guess the new suggested size (640x480) will be implemented after you receive the final confirmation?

**Comment by eviljeff** [comment]
> There is no limitation in dev hub with regards to the maximum allowed size (2400x1800), i.e. larger images can be uploaded as long as they meet the 4:3 ratio. However, it looks like the picture has been resized to the max allowed size (2400x1800) after upload.

That was deliberate - I figured having larger images wasn't a problem as we can resize down and keep the original size for any future needs.

> Regarding thumbnails, they are still rendered at 320x240 as far as I can see, so I guess the new suggested size (640x480) will be implemented after you receive the final confirmation?

yes, lets go with that explanation rather than I forgot 😉   Could you file a follow-up?

**Comment by AlexandraMoga** [comment]
Ok, no problem. I have filed #10069 as a follow-up. 

This is now verified fixed on AMO -dev with FF63, Win10x64

**Comment by jvillalobos** [comment]
> should we run the task to get some larger sizes even though they are unlikely to be in the correct ratio?

We'll have to deal with images with different ratios anyway, so having some larger ones is still beneficial. So I think the followup issue is warranted.
