### ISSUE TITLE
Show description field for extensions in submission flow

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9489]
The field will be shown and required for extensions in the submission flow, with a minimum character length of 10 characters, and a recommended length of 250 characters.

**Comment by MeridelW** [comment]
@jvillalobos Do we need to add additional details like this? I assume most of this is only applicable to redesigning submission flow in Q1:

1. Strongly encourage but don't require description. Quality content, 300 characters across content types, good for SEO.
2. Ask developers to provide most important copy (such as user benefit and features) in first 250 characters, after which content may be hidden unless user selects to read more.
3. Communicate to devs how the summary field is distinct from the description, and should not just be repeated in the description field. 
4. Provide devs with a preview of the product page.
5. Provide a wiziwig with HTML toggle and mark-up. 
6. Include ability to add sections and suggest sections they should include.
7. Pull summary and first 250 characters of long description into SERPS (run this by Raphael)

**Comment by jvillalobos** [comment]
That's all Q1, except possibly adding a short recommendation about length and quality. Something along the lines of "Recommended length: 250 characters. If you need a longer description, make sure the first 250 characters contain the most important description points."

**Comment by jvillalobos** [comment]
Updated the opening comment to reflect what we settled on.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF62, WIn10x64
- the description field is now included as an additional - optional - step during add-on submission
- the layout of the Edit information page in dev hub was also rearranged into more structured components
- summary is kept at a 250 maximum length
- the description field is displayed only for listed extension submissions

![image](https://user-images.githubusercontent.com/31961530/47344843-159e0380-d6b2-11e8-8e14-21f160d37d91.png)

I've also filed some follow ups - #9783 and #9784 - for some issues I've noticed

**Comment by eviljeff** [comment]
@AlexandraMoga sorry I forgot to add QA notes - for description having a 10 character minimum and it being required field is behind a waffle flag (see https://github.com/orgs/mozilla/projects/39#card-13476230).  `content-optimization` needs enabling first.

**Comment by AlexandraMoga** [comment]
Update:
- with the `content-optimization` waffle on:
Description is added as a mandatory field in the submission flow with a minimum required length of 10 characters
