### ISSUE TITLE
Rewrite file-viewer to use git-backend

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9498]
Once versions are extracted into our new git backend the file-viewer should make use of those already extracted files to simplify and speed-up the whole viewer.

This will also allow us to get rid of a lot of caching code that's everywhere in there.

**Comment by muffinresearch** [comment]
@EnTeQuAk I don't think this needs to be in scope for this Q3 project unless it's a really small/easy  change.

**Comment by EnTeQuAk** [comment]
Agreed, I only put it in there to keep better track of it. Guess labels will do too

**Comment by EnTeQuAk** [comment]
Let's actually not do that, we are implementing a new file-viewer and the existing one should be replaced as soon as possible.

Rewriting the old file-viewer turned out to be super messy and it's not worth the invested time imho.
