### ISSUE TITLE
Remove user_media_path "helper"

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9514]
This helper is used throughout our code and all it does is hide the fact that it accesses a setting.

Since that helper hides the fact that a specific setting may still be used it's dangerous and can lead to accidental setting removal.

The following folders are used in our code:

* `addon_icons`
* `addons`
* `collection_icons`
* `guarded_addons`
* `previews`
* `reviewer_attachments`
* `userpics`

With that, we have the following settings that **have to be present**

* `ADDON_ICONS_PATH`
* `ADDONS_PATH`
* `COLLECTION_ICONS_PATH`
* `GUARDED_ADDONS_PATH`
* `PREVIEWS_PATH`
* `REVIEWER_ATTACHMENTS_PATH`
* `USERPICS_PATH`

We should replace all usage of `user_media_path` and respectively `user_media_url` to make settings access explicit again and grep-able. I don't see any reason why not to use these settings directly throughout the code and configure them explicitly in `settings_base.py` with the current default of `user_media_path`.

**Comment by diox** [comment]
Note that a copy of both `user_media_url` and `user_media_path` exist in `services/` as well.

**Comment by eviljeff** [comment]
I've replaced `user_media_path` usage.  I had to add a few settings but they were largely there and there was some variance in how we store the files on production vs. local dev.  

`user_media_url` use though is less straightforward - we don't appear to override _any_ of the settings in dev or prod and I'm not sure why we'd need (or want) different urls apart from the CDN prefix.  So instead I'm thinking of just rewriting `user_media_url` to always do `'%s%s/' % (settings.MEDIA_URL, what)` and not allow any per-conf setting overrides.

**Comment by EnTeQuAk** [comment]
> So instead I'm thinking of just rewriting user_media_url to always do '%s%s/' % (settings.MEDIA_URL, what) and not allow any per-conf setting overrides.

I think I like that idea. I think having a simple helper to not do that concatenation in our code is helpful, especially since joining URLs (and paths) can be very error prone.

**Comment by eviljeff** [comment]
Can't overcome these test fails https://travis-ci.org/eviljeff/olympia/builds/446687516 so dropping this for now.
