### ISSUE TITLE
Remove code related to compat-bump and compatibility-report

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9515]
As part of our legacy removal we are now able to remove code related to our compatibility bump and compatibility report. Both isn't used anymore.

The respective code is mostly present in `src/olympia/compat`

* Make sure to remove related models and database tables (will probably need a follow-up issue filed)
* Make sure to also remove related ElasticSearch content (will also need a follow-up issue filed)

**Comment by EnTeQuAk** [comment]
cc @jvillalobos and @wagnerand to get some clarity on the add-on compatibility reporter's usage, if it's really completely unused we should just get rid of it.

**Comment by wagnerand** [comment]
I don't believe QA is needed for it, since we're basically removing an API and some admin pages here. I'm setting the label, @diox please feel free to correct if you have good testing instructions (otherwise, it would just be: Make sure that a bunch of URLs are 404).

**Comment by grahamperrin** [comment]
For posterity, with around 150 captures: 

- [e10s (multi-process) compatibility reports at addons.mozilla.org (AMO)](https://gist.github.com/grahamperrin/12e03fe3d305901c093cb68bce43fe92)
