### ISSUE TITLE
Remove django-product-details dependency

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9516]
Once https://github.com/mozilla/addons-server/issues/9515 lands there is almost no use of data from product-details.

Current occurrences are:

* Fetching language-related data, mostly their translations (in featured collections admin, stats
* Access to current and historic Firefox releases (in stats, via `product_details.firefox_history_major_releases`)
* Compatibility related tools, that will be removed with #9515 

We also get all language translations from product-details.

addons-frontend specifies all languages statically in https://github.com/mozilla/addons-frontend/blob/master/src/core/languages.js and we should be able to do the same in addons-server. We can have a management command to generate that file maybe, depends on the mood of the implementor.

**Comment by EnTeQuAk** [comment]
Assigning to me and starting to tackle that. Once #10258 is done there isn't much code left to deal with.

We're going to have to replace `<app>.latest_release` usage in `Addon.incompatible_latest_apps` and in `devhub/templates/devhub/addons/ajax_compat_error.html` which seem to be the only two places left.

**Comment by EnTeQuAk** [comment]
QA: There isn't much to be tested, there's one very minor feature in devhub that you're able to test though: In theory, if you're uploading a new add-on that `strictCompatibility` and requires a max version that's lower than the most recent version of Firefox or Android (depending on what you're targeting), you should see a tooltip that's warning you and urging you to upgrade your version. It's not blocking uploads though.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  I have uploaded a language pack -  which should have strictCompatibility -  and I've looked for the tooltip you mention above.

I'm not entirely sure if you were referring to the following location: 

![image](https://user-images.githubusercontent.com/31961530/51179714-0bfdf380-18cf-11e9-8c64-8046305bac41.png)

*Note that the FF release version is not picked up correctly.

**Comment by EnTeQuAk** [comment]
This is indeed the correct tooltip. It's referring to the most recent Firefox release being mentioned on https://addons.mozilla.org/en-US/firefox/pages/appversions/ - so this is perfect!
