### ISSUE TITLE
allow static theme previews to be regenerated

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9519]
follow on from  #9419 - now we're generating 720 wide previews for new submissions we should regenerate that size for the existing static theme versions.

We can do this any time before the planned frontend changes in 2019 Q1

**Comment by eviljeff** [comment]
Refocussing this issue on the underlying functionality - a command to allow theme previews to be regenerated.

**Comment by AlexandraMoga** [comment]
@eviljeff can this command be verified just with a few themes, or do we need to wait for it to be run for all the existing themes in order to test it?

**Comment by eviljeff** [comment]
It can be run with specified addon ids or all themes (similar to the migrate lwt command itself).  If you know of a broken static theme listing on -dev we can try it on that one.

I filed #10391 to allow us to run it over all themes and just regenerate the ones missing previews.

**Comment by AlexandraMoga** [comment]
@eviljeff  
I did find some themes on -dev that do not have a preview currently.
The first one is a test static theme submitted by us and the rest are migrated lwt.

Theme IDs for preview regeneration:
494940, 495815, 500553, 495814, 500336

**Comment by eviljeff** [comment]
I found a bug in my patch - I'll fix it at the same time as #10391

**Comment by eviljeff** [comment]
done.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev

The theme previews have been recreated:

![image](https://user-images.githubusercontent.com/31961530/51241448-83db2500-1986-11e9-93ed-9603bca07861.png)


I've also checked that all sizes are rendered correctly in https://addons-dev.allizom.org/api/v4/addons/addon/earthfox/
