### ISSUE TITLE
Expose `current_version.is_strict_compatibility_enabled` in the Discovery response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9520]
I'd like `current_version.is_strict_compatibility_enabled` for each add-on in the response of the Discovery endpoint: https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#get--api-v4-discovery-

This is needed because our compatibility checks use this attribute. AMO and Disco Pane currently behave in a slightly different manner because Disco Pane add-ons do not have this attribute defined. It is a minor issue, especially because Disco Pane lists curated content, but that would be nice to fix.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

` "is_strict_compatibility_enabled"` property is now exposed in the response of the discovery api endpoint:

![image](https://user-images.githubusercontent.com/31961530/46204847-4f842000-c327-11e8-9a16-c5e5bf7a926a.png)
