### ISSUE TITLE
Automatically set `target_locale` for new webextension dictionaries uploads

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9522]
In https://github.com/mozilla/addons-server/issues/9344#issuecomment-418508929, I asked if we could automatically set the `target_locale` field on new webextension dictionaries uploads and @jvillalobos replied:
>> should we take advantage of that and fill the target_locale field automatically when a webextension dictionary is uploaded ?
> 
> I suppose that's okay. It's not something we have to deal with often and it'd be good to automate it. We could run into a problem if many dictionaries are submitted for the same locale, but that's unlikely to happen, and not a bad problem to have.

So, let's do it. The value should be in the manifest, as the key in the `dictionaries` object (the linter only allows uploads of dictionaries with a single key). The trick is to figure out if we want validation and if we want to use the value as-is.

**Comment by eviljeff** [comment]
Can/should we drop the `locale_disambiguation` field too?

**Comment by diox** [comment]
@jvillalobos can we drop `locale_disambiguation` as part of this ? The frontend does not use it. I don't think Firefox does either, though we could include a dummy one in the `v3` responses if needed...

**Comment by diox** [comment]
cc @willdurand for the frontend side of things

**Comment by jvillalobos** [comment]
I think it's okay to drop it.

**Comment by AlexandraMoga** [comment]
I've submitted a few webextension dictionaries on -dev and then checked if the target_locale was populated in admin.

For all the dictionaries submitted, the target locale was added automatically

Here is an example:
https://addons-internal.dev.mozaws.net/en-US/admin/models/addons/addon/496369/change/?_changelist_filters=q%3D%26type__exact%3D3
![image](https://user-images.githubusercontent.com/31961530/46540132-1c123a00-c8c1-11e8-88bf-a12161c53e69.png)

@diox 
- the removal of `locale_disambiguation` was supposed to land with this patch? I can still see this field in Admin tools, below the Target locale field.
- should we also test that target_locale is added automatically for migrated dictionaries?

**Comment by diox** [comment]
> the removal of locale_disambiguation was supposed to land with this patch? I can still see this field in Admin tools, below the Target locale field.

Ah yeah, I should have removed it. Re-opening to do this.

> should we also test that target_locale is added automatically for migrated dictionaries?

this has already been done and verified in https://github.com/mozilla/addons-server/issues/9344

**Comment by AlexandraMoga** [comment]
Locale Disambiguation field removed from admin/models/addons/

![image](https://user-images.githubusercontent.com/31961530/46668661-c6e26b00-cbd5-11e8-9b86-b3f150f0f9d6.png)

Marking issue as verified fixed on AMO dev with FF62, Win10X64
