### ISSUE TITLE
Update django-tables2 to 2.0+

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9532]
see #9416
django-tables2 2.0 (yay naming) is a breaking change: at the very least as it does a sanity check on `__init__` and realises the model we specify in `Meta` is not actually a django `Model`, but our own `RawSQLModel`.  (Possibly more fixes needed once the code runs).

Chosen fix is "rewrite the review queues to use standard django Model or the standard AMO ModelBase subclass."

**Comment by diox** [comment]
QA: check reviewers queues still display correctly (including sorting, displaying flags etc)

**Comment by ioanarusiczki** [comment]
@diox I checked dev. Should be alright. I've noticed that the extension queues have some new colums: Code Weight, Metadata Weight and Total Weight and `Score` became `Maliciousness Score`. - this should be expected

**Comment by diox** [comment]
Yeah those columns were added in https://github.com/mozilla/addons-server/issues/16274
