### ISSUE TITLE
remove static theme submission waffle

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9535]
static theme submissions have been enabled for a few weeks now and there's no turning back.  Remove `allow-static-theme-uploads` waffle support throughout the codebase.

`disable-lwt-uploads` is newer and should probably wait until the lwt theme migration in case we need to test something.

**Comment by AlexandraMoga** [comment]
`allow-static-theme-uploads` no longer available in https://addons-internal.dev.mozaws.net/en-US/admin/models/waffle/switch/

Static theme submissions are working as expected.
