### ISSUE TITLE
 Theme wizard should preload latest version properties when uploading new version

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9539]
STR:

1) Create a theme
2) In the Dev Hub, click on Upload New Version.
3) Click on Create a Theme button.

Expected:
The properties of the current theme version should be preloaded, so they are easy to edit. Currently, the wizard is in its default state.

This won't work very well if the previous version was uploaded as an XPI and included properties that the wizard doesn't support. It's an edge case, however, and maybe we can show a warning on the wizard page explaining that those properties will be reset (or kept?).

**Comment by jvillalobos** [comment]
To answer @eviljeff's question from a different issue, this was brought up by Madonna, our most active designer, so it is a fairly significant use case. And yeah, it would include the background image.

**Comment by jvillalobos** [comment]
Having said that, the need to tweak a design might lessen once Color is up to par.

**Comment by vcarciu** [comment]
The background image is not present when uploading a new version : 
![newvers](https://user-images.githubusercontent.com/1583842/47025775-c9f8d080-d16c-11e8-9de4-7cd3d776fd42.png)

**Comment by AlexandraMoga** [comment]
@eviljeff I'm still not seeing the background/headerURL in the preview:

![image](https://user-images.githubusercontent.com/31961530/47425447-f88d3180-d792-11e8-810a-38db5b630423.png)


There seems to be a CORS error in the Console:
```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://addons-dev-cdn.allizom.org/user-media/addons//496387/1535136/light-blue.jpeg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

- theme background/headerURL is now pre-loaded in the wizard when a new version is submitted
- supported properties are also rendered
- unsupported properties are skipped and enumerated in a message at the top of the form 
- there are no errors in the console

![image](https://user-images.githubusercontent.com/31961530/47781394-41e6ff00-dd06-11e8-8c42-dfd670332d55.png)

![image](https://user-images.githubusercontent.com/31961530/47781411-4b706700-dd06-11e8-8a48-1b81d5a514a2.png)
