### ISSUE TITLE
Investigate DOS attack that caused 504 timeouts in the API

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9540]
There was a successful DOS attack that brought down the site. See https://github.com/mozilla/addons-frontend/issues/6369

We believe that the root cause was some logging on the frontend that was using 36MB per log message. See https://github.com/mozilla/addons-frontend/issues/6370

As part of the DOS attack, the API was returning many 504 timeouts. This issue is to take a look at the logs and see what caused the 504 timeouts. Maybe there is something causing unnecessary pressure on the API? If it was just simply too much traffic then there is probably nothing to do.

**Comment by muffinresearch** [comment]
@kumar303 please re-open if there is any further action required here.

**Comment by kumar303** [comment]
Our investigation showed that the large log messages (https://github.com/mozilla/addons-frontend/issues/6370) is what caused the DOS. There was also an increase in traffic but we are now able to handle that level of traffic since the logging problem was fixed.
