### ISSUE TITLE
Port to data dog statsd client

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#955]
Prod uses data dog for statsd now. If we port to the [data dog statsd client](http://docs.datadoghq.com/guides/dogstatsd/) then we can get tags and guages and other cool things.

Tags would be nice for something like:

```
statsd.incr('some.thing.count.all')
if ...
    statsd.incr('some.thing.count.success')
else:
    statsd.incr('some.thing.count.fail')
```

which would be come:

```
tags = []
if ...
    tags.append('success')
statsd.incr('some.thing.count', tags=tags)
```

(I think)

**Comment by andymckay** [comment]
We've got some data dog going on. Something more you want to do here @kumar303 (assuming no and closing).

**Comment by kumar303** [comment]
I would really like to port to the data dog client because currently we cannot use tags or gauges. Tags would be especially nice since we could reduce the number of statsd requests we make which will reduce our network usage. It's not high priority unless @jasonthomas says we're getting close to some network limits.

**Comment by EnTeQuAk** [comment]
Short update: Still waiting for upstream to release a new version with my PR that added the new datadogpy client. Once that happens we can move forward using more advanced features.

**Comment by EnTeQuAk** [comment]
Unassigning myself from this, unfortunately upstream isn't really responsive and we're still waiting on a release. Django-statsd has datadog support in their master now.

**Comment by muffinresearch** [comment]
Closing this since we're migrating away from this.
