### ISSUE TITLE
Add debugging information to searches

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#9551]
The goal here is to make it much easier to see inside searches and to better understand why the current results are as they are. To do this we need to expose all information related to how results are weighted.

One option discussed before was optionally being able to turn on debugging information in the search API. Doing this would need to consider if this should be restricted in any way.

**Comment by AlexandraMoga** [comment]
@diox could you please add some test guidelines? 
Thanks

**Comment by diox** [comment]
Marking as `qa-` I'll check that myself - it shouldn't have an impact to end-users.
