### ISSUE TITLE
Disable rating / review throttle on dev

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9553]
### Describe the problem and steps to reproduce it:

* Rate an add-on repeatedly on dev

### What happened?

You get 'Request was throttled.'

### What did you expect to happen?

This is annoying on dev so I'd like to see it disabled. If we ever need to test it again, we could turn it back on temporarily.

### Anything else we should know?

It's really common to hit this when developing because deleting and recreating a rating is an easy way to re-enter the flow.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, WIn10x64

![no more throttle](https://user-images.githubusercontent.com/31961530/46359108-2dfd9e00-c671-11e8-8269-047465ae7754.gif)
