### ISSUE TITLE
Increased 500 errors on the website

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-server#9559]
### Describe the problem and steps to reproduce it:
We received an alert about increased 500 errors on the web site.

### What happened?
It looks like the 500 is a result of this traceback: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4763576/

A lot different URLs have caused the above 500, for example,

```
"GET /en-US/firefox/addon/affiliatemk14/ HTTP/1.1" 500
"GET /en-US/firefox/addon/alhambraa32/ HTTP/1.1" 500
"GET /en-US/firefox/addon/allimportusa853/ HTTP/1.1" 500
"GET /en-US/firefox/addon/anime-ninja/ HTTP/1.1" 500
"GET /en-US/firefox/addon/antifa1992berlin/ HTTP/1.1" 500
"GET /en-US/firefox/addon/atelis-edu/ HTTP/1.1" 500
"GET /en-US/firefox/addon/bellgardensc36/ HTTP/1.1" 500
"GET /en-US/firefox/addon/bibiblen/ HTTP/1.1" 500
"GET /en-US/firefox/addon/bridge-over-river-madonna/ HTTP/1.1" 500
"GET /en-US/firefox/addon/bridge-over-the-river-madonna/ HTTP/1.1" 500
"GET /en-US/firefox/addon/bts-all-members/ HTTP/1.1" 500
"GET /en-US/firefox/addon/burlingame1483/ HTTP/1.1" 500
"GET /en-US/firefox/addon/campbell95008/ HTTP/1.1" 500
"GET /en-US/firefox/addon/castello-di-caccamo-by-night/ HTTP/1.1" 500
"GET /en-US/firefox/addon/castle-of-caccamo/ HTTP/1.1" 500
"GET /en-US/firefox/addon/celebrate-with-champagne/ HTTP/1.1" 500
"GET /en-US/firefox/addon/dfd/ HTTP/1.1" 500
"GET /en-US/firefox/addon/edeh/ HTTP/1.1" 500
"GET /en-US/firefox/addon/edeh-pardaz/ HTTP/1.1" 500
"GET /en-US/firefox/addon/etxekandere/ HTTP/1.1" 500
"GET /en-US/firefox/addon/ff-abbensen-theme-2/ HTTP/1.1" 500
"GET /en-US/firefox/addon/filha-do-rei-cor-pink-e-branco/ HTTP/1.1" 500
"GET /en-US/firefox/addon/fractal-latcarf-xax/ HTTP/1.1" 500
"GET /en-US/firefox/addon/fractal-pap-latcarf/ HTTP/1.1" 500
"GET /en-US/firefox/addon/free-melanesia/ HTTP/1.1" 500
"GET /en-US/firefox/addon/free-west-papua-melanesia/ HTTP/1.1" 500
"GET /en-US/firefox/addon/gelbe-kelche/ HTTP/1.1" 500
"GET /en-US/firefox/addon/growtaller423/ HTTP/1.1" 500
"GET /en-US/firefox/addon/hanging-white-lights/ HTTP/1.1" 500
"GET /en-US/firefox/addon/img-src-x-onerror-prompt-1/ HTTP/1.1" 500
"GET /en-US/firefox/addon/joghatay/ HTTP/1.1" 500

... ...
```

and much more.

It also looks like once a 500 happens to a url, the subsequent access to that url returns 404 and not 500 any more.

The reason why we are seeing the increased rate of 500 seems to be that one IP is crawling the web site at the moment, and in doing so, it finds a lot URLs that may return 500.

### What did you expect to happen?

No 500 errors when accessing those urls. If the same URL returns 404 after the first 500, then it should probably just return 404 from the beginning, thus we avoid false alarms. 

### Anything else we should know?
We also noticed that while this is happening (and with the increased 500s), the # of connections to the master db doubled (from 400ish to 800ish). This seems to be strange because the 500s are caused by GET requests only, shouldn't they only cause increase of connections to the slaves (if any)? 

This could be a potential risk because it seems a single crawler (spammer) may have a way to affect the stability of our system since we only have one master (whereas we have multiple read replicas and they're load balanced). Ideally those GET requests should only use the read replica connections.

**Comment by EnTeQuAk** [comment]
This seems to be https://github.com/mozilla/addons-server/issues/1282 but I remember that there was a "simple" fix on a add-on by add-on bases but I may remember wrong, @diox I remember you did some more investigation during #1282 and related issues

**Comment by diox** [comment]
For lightweight themes with no Persona, there isn't really a good fix. IMHO they should probably be disabled - the themes are not working anyway.

> This could be a potential risk because it seems a single crawler (spammer) may have a way to affect the stability of our system since we only have one master (whereas we have multiple read replicas and they're load balanced). Ideally those GET requests should only use the read replica connections.

`GET` requests should always use the replicas **unless** they also send a special cookie forcing them on master. We use that cookie for "reads-after-write" scenarios, so that users see the changes they just made. 

That being said, we don't know if the 2 events have a *direct* link - it could be that increasing load on replicas cause all pages to slow down causing connections to master to hang around for longer, causing an increase in number of connections from new requests coming in.

**Comment by diox** [comment]
My best guess so far regarding the connections on master is that they are caused by the way addons-server deals with transactions - it opens unnecessary connections to do this on some requests that don't do writes. The PR for https://github.com/mozilla/addons-server/issues/3610 should unify and fix our behavior and will go in prod this week.

I'm also opening a PR to fix what caused the 500s in the first place, so after this week's deploy things should look much better.

**Comment by bqbn** [comment]
One additional piece of info: I wasn't aware that they sent requests with "cookie: mamo=off" header. With that header, urls in https://github.com/mozilla/addons-server/issues/9559#issue-365280299 consistently return 500. However, if without that header, the same url returns 404. 

> That being said, we don't know if the 2 events have a direct link 

That's correct.

> The PR for #3610 should unify and fix our behavior and will go in prod this week.

👍 

> I'm also opening a PR to fix what caused the 500s in the first place

That's good news too. But I thought you said `there isn't really a good fix`? Is the "fix" to disable them?

**Comment by diox** [comment]
I'll return a 404 for them in the old site when detecting this problem. It might happen elsewhere, but as a quick workaround it will be enough.

**Comment by diox** [comment]
QA: We didn't have on dev that would trigger this issue so I made one:
Once the fix lands, https://addons-dev.allizom.org/en-US/firefox/addon/new-add-on/ should return a 404 instead of a 500 "Oops" page.

**Comment by AlexandraMoga** [comment]
@diox  your add-on is returning a 200 for me:

![image](https://user-images.githubusercontent.com/31961530/46357722-225ca800-c66e-11e8-97da-6d562c76577d.png)

**Comment by diox** [comment]
@AlexandraMoga try on the *legacy* frontend.

**Comment by AlexandraMoga** [comment]
oh, sorry, I missed this comment 

>I'll return a 404 for them in the old site when detecting this problem. It might happen elsewhere, but as a quick workaround it will be enough.


This is now verified fixed on AMO -dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/46394006-4c56ae80-c6f0-11e8-8d4f-a7e2943b2536.png)
