### ISSUE TITLE
Update Django to 1.11.16 (bugfix release)

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9562]
See https://docs.djangoproject.com/en/2.1/releases/1.11.16/

* Fixed a race condition in QuerySet.update_or_create() that could result in data loss (https://code.djangoproject.com/ticket/29499).

We're using `update_or_create` so we should get that update asap (regular Thursday deployment should be fine though)

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed.
Thanks
