### ISSUE TITLE
Expose add-on's creation time in the (detail) API response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9564]
In order to add a new `meta` tag on AMO, I'd need the add-on's creation time. This date is already stored thanks to the [`UncachedModelBase`](https://github.com/mozilla/addons-server/blob/dce35f1d21380c806855ae9496dc828b190cc3a3/src/olympia/amo/models.py#L401). Yet, this date is not exposed in the [detail API response](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail).

Would it be possible to add a new field for that? Thanks!

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev

Addon detail api is now returning the creation date (UTC)

https://addons-dev.allizom.org/api/v4/addons/addon/creation-date-in-addon-api/

![image](https://user-images.githubusercontent.com/31961530/46724633-1763d200-cc83-11e8-97ff-397e5f258ec2.png)
