### ISSUE TITLE
FR: append version hint to 'Server response: Version already exists. (status: 409)'

### ISSUE THREAD

**Issue by tomquas** [mozilla/addons-server#9571]
### Is this a feature request or a bug?

FR
What is the current behavior?

Building web extension from /.../extension
Server response: Version already exists. (status: 409)
FAIL

WebExtError: The extension could not be signed
...

### What is the expected or desired behavior?
desired: give a hint on which was the latest version signed so that one can easily adapt the manifest accordingly. i know, release management – but things get out of order occasionally, we all know that. today, i have to navigate to AMO and cross fingers...

### Version information (for bug reports)

node --version && npm --version && web-ext --version
v10.11.0
6.4.1
2.9.1

### Anything else we should know?
I've been asked to ask here for assistance by @rpl.
original ticket: https://github.com/mozilla/web-ext/issues/1372

**Comment by diox** [comment]
Potential good first bug for somebody familiar with python. 

The code is in src/olympia/signing/views.py in the `handle_upload()` method:
https://github.com/mozilla/addons-server/blob/3900325b226ff380f736a2a7655ae36fc775254d/src/olympia/signing/views.py#L131-L135

We already have a method allowing you to fetch the latest version for an add-on that can be used in this scenario, and that's `addon.find_latest_version(None, exclude=())`. Using this method, you can fetch the latest version, and modify the message being returned by incorporating the `version` attribute in it to display the version number.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @diox

**Comment by shatgupt** [comment]
I would like to take this up.
To clarify what is expected, it should return a message like `Version already exists. Latest version is XX.` where `XX` can be got by `addon.find_latest_version(None, exclude=())` ?

**Comment by diox** [comment]
Yeah, that should work.

**Comment by shatgupt** [comment]
Great. I will send a PR by tomorrow.

**Comment by shatgupt** [comment]
Raised PR: https://github.com/mozilla/addons-server/pull/9593
