### ISSUE TITLE
Validate submitted source code

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9572]
https://github.com/mozilla/addons-server/blob/d71d63cc1e350ddebe495cda6ea4247edcb35414/src/olympia/versions/models.py#L42-L44 allows different file formats for uploading source code.

We rely on them being valid for doing code-search (and review of course), but we don't do any kind of validation (other than checking the file extension). The result is, that there are some files either being corrupt/incomplete or have the wrong file extension (presumably to make the upload pass), but in fact use an unsupported compression algorithm.

Therefore, we need to add some validation to uploaded source code files:
* Check the compression algorithm, for example using the file signature (magic number), instead of just the file extension and
* Verify the archive is valid.

Looking into [pyunpack](https://github.com/ponty/pyunpack) might be worthwhile.

Justification for P2: The daily code-extraction script that provides the data for code-search relies on valid files and usage of one of the supported compression algorithms above. We recently mitigated some issues, but we cannot anticipate or support every potential compression algorithm.

**Comment by EnTeQuAk** [comment]
I don't necessarily want to include a 3rd party library just for that, most of the relevant formats can be opened by Python out of the box already.

Zip obviously is already supported via `zipfile` and the rest is just tar files with different compression algorithms, python has support for gzip, bz2 and xz which covers all of the supported ones except for .7z files. I'd probably use https://github.com/fancycode/pylzma for that until we are on Python 3 which has builtin support.

`pyunpack` calls out to a command line binary which makes it harder to control and may hurt performance unnecessarily.

**Comment by EnTeQuAk** [comment]
Pushing one week back since this is turning out to be quite a bit of work, hooking into the related JavaScript code

**Comment by wagnerand** [comment]
Related to/Necessary for #9611.

**Comment by diox** [comment]
@jvillalobos to implement validation of the archive files uploaded by developers, the more exotic formats we currently support are kinda getting in the way. It's a lot more work to support them, because it's going to force us to integrate 3rd party libraries and have multiple code paths depending on the format. This also has an additional maintainability cost because of those libraries.

Can we remove `.xz` and `.7z` ? Looking at redash, roughly 1% of source code uploads are using them, and, well, surely those developers could just upload a regular zip instead.

**Comment by jvillalobos** [comment]
Yes, I think it's fine to drop support for them.

**Comment by diox** [comment]
FWIW I also dropped `.tar` because it was unused, but also because it's uncompressed. So we're left with `.zip`, `.tar.gz`, `.tar.bz2`, which will now be validated. We will now reject files that have the right extension but are not what they say they are underneath, as well as corrupt archives.

**Comment by diox** [comment]
Yes -`.xpi` are `.zip` so it shouldn't matter, but if you're trying to upload a `.tar` renamed as a `.zip` it should now fail.

**Comment by AlexandraMoga** [comment]
@diox sorry but this is still not very clear to me. Maybe I haven't explained myself very well. 

So, if I'm building a `.zip` archive in which I'm including an unsupported or invalid archive format, shouldn't it fail during validation? The example uploaded here is a `.zip` package that includes a `.tar` archive renamed as `.zip`. I was expecting this to be rejected when uploaded as source code. 

I've also noticed that there are no errors when an empty archive (with a valid extension) is uploaded. This is probably a very unlikely scenario, but I can file a separate issue if you consider it's worth fixing. 

[broken archive.zip](https://github.com/mozilla/addons-server/files/2579901/broken.archive.zip)

**Comment by diox** [comment]
Ah, no, we don't check the *contents* of the archive at all at this stage.

**Comment by AlexandraMoga** [comment]
In that case, thing seem to work as expected, so I'm marking this issue as verified fixed.
