### ISSUE TITLE
theme reviewers want to be able to access user's profile page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-server#9574]
Issue is reported by Pam, one of our awesome theme reviewers. 

Pam will frequently check profiles before approving themes to see if the designer is a spammer. She notes that from the new static theme review queue, she can't view the profile of new theme designers until one of their themes is approved. 

Is this expected behavior?

**Comment by jvillalobos** [comment]
Yes, only developer profile pages are user-visible. You're not a developer until you have a visible add-on.

**Comment by caitmuenster** [comment]
Can we give reviewers rights to view user profiles?

**Comment by jvillalobos** [comment]
> One of the reasons I brought this up with Caitlin was because I noticed that some designs were being rejected because a designer's profile page wasn't showing up.

Ah, well, please inform reviewers that they shouldn't do that.

> Can we give reviewers rights to view user profiles?

We could. I'd just like to understand how common and effective this is. How often are themes being rejected based on the user profile?

**Comment by jvillalobos** [comment]
> We could. I'd just like to understand how common and effective this is. How often are themes being rejected based on the user profile?

@caitmuenster what do you want to do here?

**Comment by caitmuenster** [comment]
It would be great if we could give theme reviewers permission to view user profiles before themes/add-ons are approved. When investigating potential spam submissions, it's super helpful to see if the profile content is spammy.
