### ISSUE TITLE
Link Version to FileUpload

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-server#958]
When creating a Version it should get linked to the FileUpload that created it. That way the signing API can access the Version for a FileUpload instead of always showing the latest version and having potentially inconsistent output.

**Comment by kumar303** [comment]
for context, see https://github.com/mozilla/olympia/issues/953

**Comment by eviljeff** [comment]
Is this still valid?  We now don't allow version number/string re-use so I can't see how an inconsistent output would happen any more.  (Even before there wouldn't have been more than one non-disabled, non-deleted version with the same version string)

**Comment by kumar303** [comment]
My recollection is hazy. Maybe @mstriemer knows?

**Comment by mstriemer** [comment]
This is still valid. Since a `FileUpload` gets created before the `Version` there can be multiple file `FileUpload`s that have an `addon_id` and `version` matching a certain `Version`.

We pull the file data from the `Version` so you can end up checking a specific `FileUpload` at `/addons/@my-addon/versions/1.1/uploads/upload-guid/` and it will say it isn't valid but it will have a signed package that is valid. If you never access the upload my guid and just hit `/addons/@my-addon/versions/1.1/uploads/` instead this makes no difference.

**Comment by eviljeff** [comment]
Okay - its an issue you'd hit with the API only?  (The reference to #953 was confusing because the traceback in that issue was on `Addon.versions` rather than any `FileUpload`s)

**Comment by eviljeff** [comment]
@mstriemer can you provide some more information on this, specifically what url would give inconsistent output under what circumstances?

**Comment by mstriemer** [comment]
I think the STR would be something like:

1. Upload an invalid add-on with version `1.1`, it is assigned guid `A` (how unique!)
2. Once that upload fails, fix the add-on and upload it again with version `1.1`, it is assigned guid `B`.
3. Wait for the `B` version to pass validation.
4. Check `/addons/@my-addon/versions/1.1/uploads/A`
    * You see that it was invalid
    * You also see that the associated `file_upload` is valid, and signed (this is because it pulls the latest `file_upload` with version `1.1` so it gets the `file_upload` from `B`).

**Comment by eviljeff** [comment]
I'm thinking the fix is to either:
*  disallow `/addons/<addon-guid>/versions/<version-num>/uploads/<upload-guid>` and only have `/addons/<addon-guid>/versions/<version-num>/uploads/` or
* do a lookup on `<upload-guid>` instead

**Comment by eviljeff** [comment]
but... https://github.com/mozilla/addons-server/blob/master/src/olympia/signing/views.py#L226 says its already filtering on guid so not sure what the root of the issue it.

**Comment by mstriemer** [comment]
Ah, I had it backwards. It's that the version is always the latest regardless of which `FileUpload` you check. Version is found in https://github.com/mozilla/addons-server/blob/8139d46431864e5cf3895f2ae216a0ef5e72cac2/src/olympia/signing/views.py#L237.

I think this means you could get the opposite results then, it looks like the validation succeeded but none of the files are signed.

**Comment by eviljeff** [comment]
Can `addon.versions.filter(version=version_string)` ever return more than one match anyway?  (We enforce a unique version string.)  I guess you can use an upload guid with the wrong version and get weird data.  Is that an edge case we should worry about?  (The correct response for a version/upload mismatch would have to be a 500 I suppose)

**Comment by mstriemer** [comment]
I don't see a unique constraint on `version` in my database. I thought it created a version that could just be invalid and would be ignored in other places.

I see that the validation is rejected if a version already exists though [1]. So maybe we just need to only set the version fields if this is the latest file upload.

Or we could ignore this since people probably aren't checking old uploads, but if they do it could be confusing.

[1] https://github.com/mozilla/addons-server/blob/38b2901df38372462c86574b06751e385e0f7688/src/olympia/signing/views.py#L154-L158

**Comment by muffinresearch** [comment]
Closing this on the basis that it doesn't seem to be a regularly recurring problem and there's no obvious action to carry out.
