### ISSUE TITLE
Expose `total_downloads` in the add-on detail API response

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9589]
In order to add [structured data to the AMO add-on detail pages](https://github.com/mozilla/addons-frontend/issues/4129), we would need the `total_downloads` of an add-on to be exposed all the time (even if the developer hides the statistics page).

**Comment by eviljeff** [comment]
@jvillalobos do we want this? Its ignoring the developers choice (I only see reference to ratings in the linked issue, fwiw)

**Comment by diox** [comment]
FWIW: we still have this field so it would be easy to expose, it's just a matter of whether or not we should, since as @eviljeff pointed out it can potentially be ignoring the developer's choice.

Note that we used to have a `average_daily_downloads` field, but we removed that in https://github.com/mozilla/addons-server/issues/8367 because it wasn't very useful information.

**Comment by willdurand** [comment]
> We still have this field so it would be easy to expose, it's just a matter of whether or not we should, since as @eviljeff pointed out it can potentially be ignoring the developer's choice.

I thought this was exposed in the metadata of the legacy website?

**Comment by EnTeQuAk** [comment]
> I thought this was exposed in the metadata of the legacy website?

Doesn't necessarily mean it was right to do so. It's just another idea to think about it again and make a clear decision about which numbers will be publicly available despite the developers decision to not share any detailed numbers.

**Comment by willdurand** [comment]
> Doesn't necessarily mean it was right to do so. It's just another idea to think about it again and make a clear decision about which numbers will be publicly available despite the developers decision to not share any detailed numbers.

Yeah, I do agree.

FWIW, @rraue wants to add rating data to the structured data because the Chrome Store exposes that too (and the idea was to expose the same data first, and see later if we can expose more/different data).

In addition, I don't think such a number (total downloads) is sensitive (it is an absolute number), but that's just my very own opinion.

**Comment by rraue** [comment]
In my understanding "interactionCount" is recommended but not necessary, so its completely up to you. I think we should then follow @jvillalobos recommendation and leave it out.

**Comment by EnTeQuAk** [comment]
Also (warning, personal opinion) "downloads" can be misleading and are much easier to fake and game.

I guess, interpreting that as a "Product-Decision" I'll just close that issue and we're leaving the downloads value out.

Thanks, everyone!
