### ISSUE TITLE
Statistics menu not centered in some localizations

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#9590]
### Steps to reproduce
1. Open statistics page for any add-on using the FR localization: https://addons.mozilla.org/fr/firefox/addon/adblock-plus/statistics/?last=30

### Expected results
No layout or display issues.

### Actual results
The menu is not centered

### Notes/Issues
Verified in FF62(Win10 x64) Issue can be reproduced in amo-prod, amo-stage and amo-dev
Issue was reproduced with the following localizations: fr, ro, de, it
Screenshot for this issue:
![stats](https://user-images.githubusercontent.com/15685441/46491055-4eb12980-c812-11e8-8704-da094f3df3f1.png)

**Comment by eviljeff** [comment]
We don't think this is worth fixing.
