### ISSUE TITLE
Auto-approval script is not running on -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9597]
STR

1. Log in to AMO -dev
2. Submit a new webextension
3. Check its approval status after a few minutes

Actual results:
The add-on status is Awaiting review. In Rev tools, in version history, it says that the auto-approval script has not run yet. 

Expected result:
Add-on is auto-approved after a few minutes.

Notes:
- reproduced on AMO -dev with FF62, Win10x64

example: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/same-name

![image](https://user-images.githubusercontent.com/31961530/46539698-e456c280-c8bf-11e8-90f8-416121b79a5e.png)

**Comment by EnTeQuAk** [comment]
The cron hasn't been running since

```python
>>> AutoApprovalSummary.objects.all().latest('created').created.isoformat()
'2018-09-28T10:45:05.866874'
```

Which is kinda suspicious…

**Comment by EnTeQuAk** [comment]
We'll wait for our -dev deployments to be unblocked and stable again before looking into this more. Currently -dev deployments are broken and the last one was only applied half-way so it may very well be related to that.

**Comment by EnTeQuAk** [comment]
![screenshot from 2018-10-09 08-47-02](https://user-images.githubusercontent.com/139033/46651324-e9f22800-cb9f-11e8-9495-260ae446bd0d.png)


Auto-approval is running fine now that @autrilla fixed the dev deployment. I'm closing this issue but please feel free to re-open at any time if you see more issues.

**Comment by AlexandraMoga** [comment]
Auto-approval seems to be working now. New submissions and versions pending for approval have all been approved.
