### ISSUE TITLE
Remove `locale_disambiguation` column from the `addons` table

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9605]
Once #9522 is merged, we can remove the `locale_disambiguation` column from the `addons` table (it will have been removed from the model).

**Comment by AlexandraMoga** [comment]
In https://github.com/mozilla/addons-server/issues/9522#issuecomment-428174522 I've checked that the 'Locale disambiguation' field has been removed from admin/models/addon/ 

On a quick check, I haven't observed any regressions around add-on localizations. 

I'm marking the issue as verified fixed.
