### ISSUE TITLE
Internal redirect on preview image and broken thumbnail on an addon

### ISSUE THREAD

**Issue by JustAnotherArchivist** [mozilla/addons-server#9608]
### Describe the problem and steps to reproduce it:
Access [addon 1002137 "Theme blaue Wellen"](https://addons.mozilla.org/en-US/firefox/addon/theme-blaue-wellen/) and look at the second preview image.

### What happened?
The second preview image of  is broken. The [thumbnail](https://addons.cdn.mozilla.net/user-media/version-previews/thumbs/2/2000.png?modified=1538668749) 404s, and the [full image](https://addons.cdn.mozilla.net/user-media/version-previews/full/2/2000.png?modified=1538668749) redirects to an internal URL http://static.addons.mozilla.net:81/... which is not publicly accessible and times out.

### What did you expect to happen?
A working preview image.

### Anything else we should know?
The API returns the same URLs for both thumbnail and full image as the site.

The new AMO site doesn't display the previews anywhere on the addon page as far as I can see, but the legacy one does. The source code of the new site does contain the broken URLs as well though (in JSON).

**Comment by bqbn** [comment]
FWIW, `2000.png` is a directory on the disk, instead of a file.

```
$ ls -ld /data/olympia/default/webroot/user-media/version-previews/full/2/2000.png
drwxr-xr-x 2 9500 9500 6144 Oct  4 15:59 /data/olympia/default/webroot/user-media/version-previews/full/2/2000.png
```

**Comment by eviljeff** [comment]
@bqbn do we have any other instances of that? Especially, for example: `user-media/version-previews/full/1/1000.png` or `user-media/version-previews/full/3/3000.png`.  I'm wondering if there's a bug in the code that ensure the parent folder exists.

**Comment by AlexandraMoga** [comment]
Since testing this on our dev or stage servers is rather impractical, I'm going to check the that this patch works against the example I provided in issue #10279
