### ISSUE TITLE
Handle all valid file extensions during git-extraction

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9609]
We currently have these file extensions in the system: `.jar`, `.xpi`, `.src`, `.xml`, `.zip`

I have no idea where `.src` comes from, `.jar` doesn't have to be handled but we should support search plugins (`.xml`) properly.

Query used: `select distinct substring_index(files.filename, '.', -1) from files;`

**Comment by wagnerand** [comment]
`.jar` and `.src` can be ignored. They are no longer supported.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  could you add STR to this issue or the label "qa: not needed" if it is not ready for QA yet?
Thanks

**Comment by EnTeQuAk** [comment]
It's not yet ready, I'll probably add a separate issue later with all the QA instructions once this is testable and can be tested by QA.
