### ISSUE TITLE
Broken file download redirect when filename contains a hash sign (#)

### ISSUE THREAD

**Issue by JustAnotherArchivist** [mozilla/addons-server#9613]
https://addons.mozilla.org/firefox/downloads/file/6850/filename redirects to https://addons.cdn.mozilla.net/user-media/addons/1607/trexy_trailbar-?filehash=sha256%3A02ec81bb40872b7098f2df1d9f94d73db463395336442b439117bcf6e8f4cfcd#genid1-fx.xpi .

It appears that the hash (`#`) in the filename causes some confusion and `#genid1-fx.xpi` is treated as a URL fragment. Instead, `#` should be encoded as `%23` and stay in the path component.

In the above example, the correct redirect target would be https://addons.cdn.mozilla.net/user-media/addons/1607/trexy_trailbar-%23genid1-fx.xpi?filehash=sha256%3A02ec81bb40872b7098f2df1d9f94d73db463395336442b439117bcf6e8f4cfcd . This URL works correctly.

As of 2018-09-14, this is the only such file in existence.

**Comment by EnTeQuAk** [comment]
I checked the database and there is indeed only one actual file that has a hash in its filename. I'm closing this since we're not able to fix this since it's the developer's responsibility.

We have proper filename validation in place for ages now so this cannot happen right now.
