### ISSUE TITLE
[static-themes] colors.tab_selected property not previewed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#9616]
Originally filed by @nt1m here https://github.com/mozilla/addons-frontend/issues/6535

### Describe the problem and steps to reproduce it:
- colors.tab_selected changes the background of the selected tab.
Example: https://addons.mozilla.org/en-US/firefox/addon/devfox/

### What happened?

Selected tab has same background as toolbar

### What did you expect to happen?

Selected tab should have blue background distinct from the toolbar

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

The `tab_selected` color property is now reflected in AMO previews:

![image](https://user-images.githubusercontent.com/31961530/48008434-5a9a4f00-e122-11e8-8b97-2018ebd3a2fc.png)
