### ISSUE TITLE
Some file downloads 404 on the CDN

### ISSUE THREAD

**Issue by JustAnotherArchivist** [mozilla/addons-server#9619]
As of 2018-09-14, there are 666 files that redirect to the CDN but produce a 404 there. For example, https://addons.mozilla.org/firefox/downloads/file/243560/chatbot-1.1.zip redirects to <https://addons.cdn.mozilla.net/user-media/addons/485504/chatbot-1.1.zip?filehash=sha256%3A27a9987dc61af834ab6d037e74968cf00d0e01370dc8852ee42d3bf5c931ae5e>, which is a 404.

The full list can be found [here](https://gist.github.com/JustAnotherArchivist/ad20a66af1cddf0239a54bf7fa9e8139). Note that it contains some files affected also by other issues I filed today (#9612, #9613, #9615, #9618).

**Comment by diox** [comment]
Closing since it's all legacy files in various weird states.
