### ISSUE TITLE
Restrict theme_experiment submissions to Experiments:Submit permission

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9630]
When the Firefox 63 schema lands via addons-linter it supports the new `theme_experiment`s which should be restricted similarly to submissions containing `experiment_apis`.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk should I understand that this is blocked for testing until Firefox 63 schema lands in addons-linter?

**Comment by EnTeQuAk** [comment]
Yes, it's unfortunately blocked by addons-linter support which won't land this week most certainly.

**Comment by AlexandraMoga** [comment]
I can see the new "Submit experiments (auto signed)" group in Admin that has the `Experiments:submit` permission.

![image](https://user-images.githubusercontent.com/31961530/46805502-de545c00-cd6d-11e8-9e98-d2631b33f834.png)


Once the linter part is ready, a full round of testing will be executed to make sure that this permission is working as expected.
