### ISSUE TITLE
Listed owners or developers cannot delete their own rating responses 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#9633]
Followup for https://github.com/mozilla/addons-frontend/issues/6491

STR:
1. Load AMO dev and go to a submitted add-on to Manage Authors & License page
2. Add user 1 as a listed owner and user 2 as a listed developer
3. Sign in AMO as user 1 and make a reply as a developer  to a given review (on the detailed review page) and then try to delete the reply 
4. Repeat step 3 for user 2 

Actual result:
Red error message "you do not have permission to perform this action" message is displayed 

Expected result:
The user can delete it's own developer reply made for a review.

Notes:
This issue is reproducible when all users are "owners" of the add-on.
Please note that the only user who can delete the replies made by listed owners and developers is the creator of the add-on.

![no permission](https://user-images.githubusercontent.com/33448286/46676506-5a716700-cbe9-11e8-848a-9feafcf1c47e.png)

**Comment by kumar303** [comment]
This is edge-case-y but seems legit
