### ISSUE TITLE
Move more path related settings to settings_base

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-server#9654]
We are currently overwriting almost all path related settings in dev/stage/prod settings because they rely on `NETAPP_STORAGE_ROOT` environment variable.

**Comment by EnTeQuAk** [comment]
QA: Just make sure that add-ons can still be installed / downloaded and that user uploaded static images (userpics, screenshots etc) in the new frontend and legacy pages are still accessible.

**Comment by vcarciu** [comment]
Verified as fixed testing around install/download and images .
