### ISSUE TITLE
Don't skip awarding points if the score is 0

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9665]
In order to have a complete picture of reviewer activity and to calculate the reviewer weekly report, let's add recording of the reviewer score even if it is 0.

**Comment by ioanarusiczki** [comment]
Users from the `Admins Group` and  `Reviewers: Add-ons` can reviews the add-ons from `Auto-Approved Add-ons` queue so I tested with a user from both groups to see if the +0 score is recorded. 
For a +90 weight and below, the score is recorded with 0 points.

![zero score](https://user-images.githubusercontent.com/33448286/47002125-ce08fc00-d134-11e8-844e-67b2ee39c56f.png)
