### ISSUE TITLE
Migrate in bulk a large* number of LWT

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9673]
We want to test out the LWT migration to static themes but ideally don't want to do them _all_.  Currently we can specify specific ids with `--ids` but listing 10,000 ids is impractical also.  Some way to say "randomly select xx LWT" to migrate is probably what I'll end up with.

**Comment by eviljeff** [comment]
logged #9725 and #9724 for some problems found.

**Comment by eviljeff** [comment]
Did some test runs on -dev.

**First run**
995 LWT; took 66 minutes from executing command till last message in Kibana.
892 "[Success]" in Kibana, which was confirmed in django shell (there were 892 more ST; 892 less LWT)
ES Index only showed 482 ST; 349,970 LWT though.  `./manage.py reindex` fixed the ES discrepancy (eventually) though to show 1,174 ST; 349,278 LWT.

**Second run**
500 LWT; took 15 minutes from executing command till last message in Kibana.
190 "[Success]" in Kibana
ES Index didn't update at all - still 1,174 ST; 349,278 LWT.  Again `./manage.py reindex` fixed the ES discrepancy to show 1,364 ST; 349,088 LWT.

**Third run**
This time I asked autrilla to suspend the auto-deploys to -dev, speculating they were causing the tasks to be aborted.
500 LWT; took 26 minutes;
338 "[Success]" in Kibana
ES Index only showed 1464 ST; 348,988 LWT  (100 more than 1,364 - could be coincidence)
(Haven't forced a reindex to see what happens, but pretty sure it will match the 338 success count)

**Comment by eviljeff** [comment]
after #9776 merged ran again:
500 LWT; took 36 minutes;
494 "[Success]" in Kibana; 1 "[Fail]" in Kibana (so 5 unaccounted for)
ES Index showed 2,298 ST; 348,154 LWT 
(1364 + 338 + 2 + 100 + 494 = 2298 so correct, assuming no other changes to public static themes on addons-dev since Friday afternoon)

Sense-checked a couple of themes and they look correct.  Filed #9799 for the one "[Fail]".  

Known unknown: why 5 LWT didn't succeed; but didn't output "[Fail]" in kibana.

**Comment by eviljeff** [comment]
Tried `./manage.py process_addons --task=migrate_lwt --ids=16794` specifically and it appears to have worked without a problem so it's quite possible these are random failures that we can overcome by repeatedly running the migration command.

https://addons-dev.allizom.org/en-GB/firefox/addon/im-wald/

**Comment by eviljeff** [comment]
#9912 for migration timing metrics

**Comment by eviljeff** [comment]
Migration is complete.
QA: file follow-up issues for any problems found.

**Comment by AlexandraMoga** [comment]
I did some exploratory on prod both on Windows and android and I haven't run into issues caused by the migration i.e. broken previews, duplicated previews.

I'm marking this issue as verified fixed,  hoping that no follow-up issues will be necessary.
