### ISSUE TITLE
Upgrade html5lib

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9690]
Now that #5182 is merged, we should finally be able to update our version of html5lib (which, unfortunately, is currently still required in AMO - bleach now vendors it for its own purposes, but we still require it in a couple places)

**Comment by diox** [comment]
QA : follow same testing protocol as https://github.com/mozilla/addons-server/issues/5182#issuecomment-428122237 - make sure our handling of newlines in descriptions etc hasn't changed either.

**Comment by vcarciu** [comment]
Verified as fixed following the steps from https://github.com/mozilla/addons-server/issues/5182#issuecomment-428122237 : 

Links wrapped: 
![wrapped](https://user-images.githubusercontent.com/1583842/47017962-459e5180-d15c-11e8-82da-1bccaa182484.png)

Links are not allowed in collection descriptions or user biography fields:
![linksnotallowed](https://user-images.githubusercontent.com/1583842/47018005-66ff3d80-d15c-11e8-9f4d-352f0877971e.png)

![userbiography](https://user-images.githubusercontent.com/1583842/47018012-6b2b5b00-d15c-11e8-8eae-837ec8640a93.png)

All allowed tags worked in description
