### ISSUE TITLE
Award the correct points to disabled auto-approval webextension files

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9692]
If a webextension file that has auto-approval disabled gets approved (or rejected) manually. we award points as if the file was a legacy file which is not what we want. The file is still a webextension and should treated as such, regardless of auto-approval being disabled or not.

**Comment by ioanarusiczki** [comment]
I tested this with 2 scenarios: 
- I went to Auto Approved add-on queue and without submitting a next version I disabled auto-approval and made a couple of confirm approvals and reject versions. Points were given to the reviewer after the new model https://github.com/mozilla/addons-server/issues/8676#issuecomment-400998624
- I went to Auto Approved add-on queue, picked an add-on with weight, disabled the auto-approval and then submitted a new version. After the disabled flag is displayed on the review page I approved/rejected the new version. The reviewer was rewarded with points such as mentioned here https://github.com/mozilla/addons-server/issues/8676#issuecomment-400998624

@wagnerand @diox  I've noticed that a lang pack reviewer receives a different score than it was mentioned for extensions  here https://github.com/mozilla/addons-server/issues/8676.  For a 120 weigh it received a +60 points 
with a New Language Pack Review  message  - is this new or it's always been counted differently for lang packs? 

![lang pack review](https://user-images.githubusercontent.com/33448286/47077631-0dede300-d20a-11e8-9ee2-a92399a9be04.gif)

**Comment by wagnerand** [comment]
> @wagnerand @diox I've noticed that a lang pack reviewer receives a different score than it was mentioned for extensions here #8676. For a 120 weigh it received a +60 points
with a New Language Pack Review message - is this new or it's always been counted differently for lang packs?

This is #9697.

**Comment by ioanarusiczki** [comment]
@wagnerand Thanks! haha I did not see that this morning. I'll check it next!
