### ISSUE TITLE
Award the correct points for language packs and dictionaries

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9697]
Award the correct points for langpacks and dicts, regardless of whether they are legacy or webextension architecture and regardless of whether auto-approval is enabled or disabled.

Language packs should be getting 60 points.
Dictionaries should be getting 60 points.

**Comment by erosman** [comment]
Just for info .... Language Packs are getting negative weighting at the moment.

**Comment by wagnerand** [comment]
> Just for info .... Language Packs are getting negative weighting at the moment.

Only the official Mozilla ones since they don't need review.

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev and AMO stage - FF62 (Win10). 
- the language packs receive +60 points (no matter of the weight received)  whether auto approval is enabled or disabled

![sample2](https://user-images.githubusercontent.com/33448286/47147218-6f7b8380-d2d6-11e8-94fa-2700389e7872.png)

- I submitted with admin override a legacy dictionary and made a manual approval/rejection of version, it received +60 points 

![sample](https://user-images.githubusercontent.com/33448286/47147229-7609fb00-d2d6-11e8-94f9-7c74ea13bc2f.png)

- the webextension dictionaries also receive +60 points but I only tested this after auto-approval.  It seems that these type of dictionaries don't display the Enable/Disable auto-approval button on the listed review page. 
Let me know if I should file an issue for this case.

Please take a look
![no enable disable button2](https://user-images.githubusercontent.com/33448286/47147027-fe3bd080-d2d5-11e8-8228-cc845c90e3b0.gif)

**Comment by wagnerand** [comment]
@ioanarusiczki thanks. Yes, please file an issue for that. Everything that auto-approved admins should be able to disable auto-approval for.
