### ISSUE TITLE
Upgrade or remove rdflib

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9701]
`rdflib` is currently pinned to an old version. We recently upgraded [`html5lib`](https://github.com/mozilla/addons-server/issues/9690) and [`bleach`](https://github.com/mozilla/addons-server/issues/5182), this is the next one on the list...

**Comment by EnTeQuAk** [comment]
with amo-validator gone, there is only very little code actually using rdflib… we still have to carry that around for some time but upgrading should be much easier now I hope.

**Comment by diox** [comment]
If we remove the code that parses legacy extensions manifests we'll be able to remove `rdflib` entirely I think...

**Comment by EnTeQuAk** [comment]
> If we remove the code that parses legacy extensions manifests we'll be able to remove rdflib entirely I think...

That depends on us actually deleting legacy add-ons though. As long as they're in the system (of some kind) we should be able to read them I think?

**Comment by AlexandraMoga** [comment]
Could you please add some STR to this issue or a qa:not needed label?
Thanks
