### ISSUE TITLE
Set add-ons with no current version as incomplete

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9707]
On dev and stage at least, some add-ons have no `current_version` set but do have their status set to public. We should set those add-ons as incomplete since they should not be public (the API already prevents them from being shown, but not the legacy API).

To do after https://github.com/mozilla/addons-server/issues/9472 is ran in case some add-ons with a weird set of files (like, a singular version with files both public and not) are found when disabling legacy files.

**Comment by wagnerand** [comment]
@diox how do you feel about manually running

`UPDATE addons SET status = 0 WHERE current_version IS NULL`

?

**Comment by diox** [comment]
WFM.

**Comment by wagnerand** [comment]
@bqbn Could you run the query above on all environments?

**Comment by bqbn** [comment]
I've run the command in -dev and -stage. Can we check everything is OK before we proceed with -prod next week?

**Comment by wagnerand** [comment]
For prod, can we run the following query that is a bit more precise:

`UPDATE addons SET status = 0 WHERE current_version IS NULL AND status = 4;`

**Comment by bqbn** [comment]
Ran the above command on -prod.
