### ISSUE TITLE
Maintenance message is not displayed after editing an add-ons details from dev hub when read-only mode get's turned on

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-server#9723]
Follow-up for https://github.com/mozilla/addons-frontend/issues/5949
Prerequisites:
read-only mode for maintenance switch is on

STR:
1. You're in dev hub trying to edit the details of an extension from edit information page
2. Try to save the changes made
3. Observe screen

Expected result:
When a `503` error is received for `POST` in the Network tab, a message that the site is being under maintenance should be displayed  on the page.

Actual result:
The page displays a continuous loading state.

Notes:
Reproducible on AMO dev with FF62 - Win10.

![edit in dev hub](https://user-images.githubusercontent.com/33448286/47083288-cd499600-d218-11e8-8808-27fa07c8f83d.png)

**Comment by diox** [comment]
Ideally we should not even let the user try to edit things while in read-only mode. But it'd be nice to also handle errors more gracefully in devhub instead of showing this loading animation forever.
