### ISSUE TITLE
LWT Migration - previews aren't in ES

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9724]
After the migration the previews section is missing from the Addon search API response (and that's data from ES).  The theme preview _is_ there, as accessing the detail page shows, so I guess there's a timing issue because the preview is generated in a celery task.

**Comment by diox** [comment]
Yeah, it it's done in a task, there is a chance it's not done in time when the add-on gets indexed... I suppose the easy way out is just to reindex the whole thing after a few minutes.

**Comment by AlexandraMoga** [comment]
@eviljeff the recently migrated static themes listed in search results - see https://addons-dev.allizom.org/en-US/firefox/search/?page=1&platform=windows&sort=hotness&type=statictheme - still don't have a visible preview.

Should this fix work only for new migrations or it should have fixed the already migrated themes as well?

**Comment by eviljeff** [comment]
It would only work for new migrations.  #9519 will cover that for existing migrations.

You're seeing a lot of missing previews due to some other problem(s) encountered with #9673 though - at scale a certain percentage of migrations fail; and some fails are stopping previews from being generated in the successful migrations too.  It's still under investigation.

It's probably going to be easier to verify this once #9673 is fixed.
