### ISSUE TITLE
Measure the amount of times we throttle rating attempts

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9730]
See [this doc](https://docs.google.com/document/d/1kWJbb_U41j_sGjYxjXe5CJXeaSUT0Jh8tTyw9x0w-_0/edit?pli=1) for more information.

Can we add some logging (if it doesn't exist) or something like that so we can easily measure how many times the throttle prevents a rating from being submitted? 

We can use this measurement to make the throttle more effective and also check if we are throttling too much.

**Comment by diox** [comment]
We should already have the info in datadog, since it's a unique HTTP code (429).

**Comment by kumar303** [comment]
@wagnerand do you think that's enough? We could make a graph of how much throttling occurs and how often but couldn't see anything like users or IPs affected.

**Comment by diox** [comment]
I've added a graph with that info to the "Addons (apps)" dashboard on datadog FWIW.

**Comment by eviljeff** [comment]
Since it's been added to the datadog dashboard I guess this issue can be closed?

**Comment by kumar303** [comment]
Works for me
