### ISSUE TITLE
Make the rating throttle more effective

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9731]
See [this doc](https://docs.google.com/document/d/1kWJbb_U41j_sGjYxjXe5CJXeaSUT0Jh8tTyw9x0w-_0/edit?pli=1) for more information.

Ratings are currently throttled by user but we should consider alternatives since we are receiving a lot fake ratings generated by fake accounts (see the doc). Maybe throttle by IP?

The measurements in https://github.com/mozilla/addons-server/issues/9730 would help guide this.

**Comment by diox** [comment]
I added a comment in the doc with my thoughts on this. That being said, we can easily add multiple throttling classes to the same view, so it'd be easy to throttle by both user and IP.
