### ISSUE TITLE
Add server flag to set Akismet in "only logging" mode

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9732]
There are concerns that Akismet will yield many false positives, causing problems for some (or many) developers and users. The system is designed to be trained and adjusted, but minimizing friction is also important. Turning it on as is in prod is a bit risky, even if we can turn it off whenever we want.

Let's add a server flag that gives us the ability to toggle Akismet enforcement. When the flag is off, we still send the metadata to Akismet and log its responses, and the admin tool can be used to looked at those responses and flag things as spam or ham. However, the Akismet response is not used to block any submissions or flag reviews for moderation. When the flag is on, blocking works as originally designed.

When this is done, we should turn on Akismet in prod with this flag off, so admins can start looking at the logs and evaluating the quality of the results.

**Comment by muffinresearch** [comment]
@jvillalobos thanks for filing this - I think this is a good call and well help us have a better picture of what's going on before jumping in at the deep end.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF62, WIn10x64

These are the new flags:
![image](https://user-images.githubusercontent.com/31961530/47369634-cd500700-d6ec-11e8-847c-747140784cc1.png)

**1. With flags turned off (as seen above):**
- user actions for any of the target sections- user review, collections and add-on metadata - is logged in Akismet reports as either spam or ham
- if spam content is detected, the user won't see any errors
- user reviews detected as spam are not sent to the Moderation queue automatically 

**2. With flags turned on:**
-  user actions for any of the target sections are logged in Akismet reports as either spam or ham
- for add-ons and collections metadata: if spam content is detected, error messages will be displayed and the user can't complete his actions
- user reviews detected as spam are sent to the Moderation queue automatically
