### ISSUE TITLE
Add-on popularity seems to be increasing search result relevancy in a disproportionate way

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9741]
We want popular add-ons (add-ons with a high `average_daily_users` value) to be higher in search results, as they tend to be better than obscure ones. So, [for the longest time](5b9a5709c3489eb58a31d856ee2d747294a80e8b) we've been applying this boost:
https://github.com/mozilla/addons-server/blob/b60ec7022aa010d92e8f2bc243d881c0a3675eff/src/olympia/addons/indexers.py#L330

[The most popular add-on, adblock-plus, has 11,236,335 users](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular) so this gives a base boost between roughly 1 and 25, which is already super high. Unfortunately, to make things worse, we have non-public add-ons in the index in order to be able to find them in reviewer tools. We still want public add-ons to come higher in the results when a reviewer does a search though, so we multiply the boost value by 4 if the add-on is public (this also makes regular public add-ons appear higher than experimental add-ons):
https://github.com/mozilla/addons-server/blob/b60ec7022aa010d92e8f2bc243d881c0a3675eff/src/olympia/addons/indexers.py#L331-L334

This is too much, it makes a small difference in popularity much bigger than it should be - unless it's an exact match, add-ons that are less popular but more relevant than another will almost always be placed lower in results, even if the difference is minimal. We need to find a better way of doing this.

**Comment by diox** [comment]
A simple potential fix:
```!diff
diff --git a/src/olympia/addons/indexers.py b/src/olympia/addons/indexers.py
index 0f2295298d..1612065807 100644
--- a/src/olympia/addons/indexers.py
+++ b/src/olympia/addons/indexers.py
@@ -327,7 +327,7 @@ class AddonIndexer(BaseSearchIndexer):
 
         data['app'] = [app.id for app in obj.compatible_apps.keys()]
         # Boost by the number of users on a logarithmic scale.
-        data['boost'] = float(data['average_daily_users'] ** .2)
+        data['boost'] = float(data['average_daily_users'] ** .1)
         # Quadruple the boost if the add-on is public.
         if (obj.status == amo.STATUS_PUBLIC and not obj.is_experimental and
                 'boost' in data):
```

This would bring back the range between 1 and 6 roughly, before the multiplier. I'll be testing this locally with data from https://github.com/mozilla/addons-server/issues/9710 to see if that's enough.

**Comment by diox** [comment]
I've been playing with this for 3 weeks locally with a copy of prod (public) data and I'm no longer sure it's a good idea to implement right now. We need more careful investigation to see if it's worth it, it can change the rankings in search results quite dramatically even when just replacing the `** .2` with a `** .15`.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/10071 will make it easier to tweak at query time and change the formula slightly. That should be enough.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/10071 will change the formula slightly and move it to a query time boost to be easier to change, but it should be close enough that there are no big differences in ranking for now.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-169
