### ISSUE TITLE
Generated Static Theme preview does not match theme

### ISSUE THREAD

**Issue by johngruen** [mozilla/addons-server#9743]
AMO generates a preview image of static themes, but the image is a mismatch of actual theme

Here's the generated theme:
![image](https://user-images.githubusercontent.com/3323249/47160917-3a305f00-d2f1-11e8-8c83-95875116760c.png)

Here's what it actually looks like: 
<img width="1589" alt="screen shot 2018-10-17 at 5 48 24 pm" src="https://user-images.githubusercontent.com/3323249/47160940-461c2100-d2f1-11e8-86b7-0c866ed51041.png">

Here's the manifest:
```
{
  "manifest_version": 2,
  "version": "1.0",
  "name": "Exported Theme",
  "theme": {
    "images": {},
    "properties": {},
    "colors": {
      "toolbar": "rgb(225, 234, 239)",
      "toolbar_text": "rgb(248, 112, 140)",
      "accentcolor": "rgb(142, 179, 201)",
      "textcolor": "rgb(255, 255, 255)",
      "toolbar_field": "rgb(255, 255, 255)",
      "toolbar_field_text": "rgb(123, 127, 204)",
      "tab_line": "rgb(248, 112, 140)",
      "popup": "rgb(255, 255, 255)",
      "popup_text": "rgb(98, 102, 183)",
      "tab_loading": "rgb(248, 112, 140)"
    }
  }
}
```

To make matters worse, this theme did not pass review in AMO due to a "Low-quality, stretched, or blank image" even though the theme is perfectly valid and (IMO) looks pretty rad. This point might be a policy issue if people start making color-only static themes.

**Comment by eviljeff** [comment]
The manifest doesn't match the screenshots you've included.  If I submit that ([9743.zip](https://github.com/mozilla/addons-server/files/2534326/9743.zip)) I get the following:

![screenshot 2018-10-31 12 41 44](https://user-images.githubusercontent.com/768592/47788698-5f1dcc80-dd0a-11e8-8c12-68bf3ecee121.png)

-temporarily installed in Firefox too to show the similarity.

If you can provide the manifest and/or a link to the addon you have screenshots of I can investigate further.  Its also possible it was due to a bug that was fixed in the meantime.

**Comment by eviljeff** [comment]
> To make matters worse, this theme did not pass review in AMO due to a "Low-quality, stretched, or blank image" even though the theme is perfectly valid and (IMO) looks pretty rad. This point might be a policy issue if people start making color-only static themes.

@caitmuenster re: theme reviewers ^

**Comment by johngruen** [comment]
@eviljeff i must have pasted in the wrong manifest, i'll try to dig up the correct one here in a sec

**Comment by johngruen** [comment]
@eviljeff could not find my original xpi so i made a new one...here's the generated preview:

![image](https://user-images.githubusercontent.com/3323249/47794041-05130c00-dcf6-11e8-8d75-60040c7697e8.png)

here's how it should look:
<img width="1376" alt="screen shot 2018-10-31 at 10 16 39 am" src="https://user-images.githubusercontent.com/3323249/47794091-1fe58080-dcf6-11e8-882e-05feda974f4b.png">


here's the manifest:
```
{
  "manifest_version": 2,
  "version": "1.0",
  "name": "Pink Static Demo",
  "theme": {
    "images": {
      "additional_backgrounds": [
        "images/bg-000-5672c42860d5b06e1058dc477397f3ef.svg"
      ]
    },
    "properties": {
      "additional_backgrounds_alignment": [
        "top"
      ],
      "additional_backgrounds_tiling": [
        "repeat"
      ]
    },
    "colors": {
      "toolbar": "rgb(255, 207, 191)",
      "toolbar_text": "rgb(72, 82, 85)",
      "accentcolor": "rgb(255, 226, 217)",
      "textcolor": "rgb(72, 82, 85)",
      "toolbar_field": "rgb(255, 226, 217)",
      "toolbar_field_text": "rgb(72, 82, 85)",
      "tab_line": "rgb(72, 82, 85)",
      "popup": "rgb(255, 226, 217)",
      "popup_text": "rgb(72, 82, 85)",
      "tab_loading": "rgb(72, 82, 85)"
    }
  }
}
```

here's the image referenced in the manifest (which is a blank SVG):

```
<svg width="1" height="1" xmlns="http://www.w3.org/2000/svg"/>
```

**Comment by johngruen** [comment]
If it matters, the UUID of the add-on i just submitted is: ` {776fc31f-ef00-433e-960b-dae4e4f3a90c} `

**Comment by eviljeff** [comment]
It's the svg being specified as an additional_background.  Does Firefox Color always insert an unnecessary empty additional background svg in it's themes?

(There seems to be a bug in the code that calculates the size which results in the background being size 0 by 0 in the template svg and the tool we use to convert the template into the png interprets that as black, for some reason)

**Comment by johngruen** [comment]
@eviljeff we use them exclusively as a workaround for the not-great-looking drop-shadow you get in firefox when you specify a `headerURL` in a theme.

That 1px x 1px image is removable, but our core flow for theme creation allows for stacking background images using additional backgrounds. You can see how this works at our dev server https://mozilla.github.io/FirefoxColor/ 

Note: only diff between prod/dev currently is the export tool, all of the image handling is the same.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64

The preview is now matching the installed version

https://addons-dev.allizom.org/en-US/firefox/addon/pink-static-demo/
![image](https://user-images.githubusercontent.com/31961530/48072576-8599a700-e1e5-11e8-9574-492e48392846.png)

**Comment by nt1m** [comment]
@johngruen : Note that additional_backgrounds has always been optional, so you can drop it if you don't use it, instead of putting a blank image.
