### ISSUE TITLE
Make logging consistent for better diagnostics

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#975]
Supposing we have a tool like Kibana or DataDog. Well we do have a tool like that. Supposing we want to be able to search in those places to find out what has happened to an addon. You can grep, but the logging is inconsistent. For example:

```
log.info('Addon "%s" status changed to: %s'
log.info('Addon "%s" file (ID:%d) status changed to: %s'
task_log.debug('Removing user [%s] from search index.'
log.info(u'User (%s: <%s>) is being restricted and '
```

Is it possible for to agree on a logging syntax and stick to it so we can easily build dashboards of and add-ons lifecycle without having to depend upon greps.

**Comment by EnTeQuAk** [comment]
I personally like the format "Addon ... status changed to ..." over "Removing user [%s] from search index." and I prefer not to have special symbols in the logs (e.g [ or ] and such). Besides that, almost normal English sentences.

Also, maybe http://docs.datadoghq.com/guides/logs/ is relevant.

**Comment by andymckay** [comment]
Im thinking mostly of Kibana where you will get a series of logs. If you look at them on prod there will be no order to them, they'll arrive overlapping and all over the place. For example:

https://dpaste.de/F8Hd

Is the logs you see when some one adds a new version and it goes through validation. Try finding those matching logs on prod with all the traffic going on.

**Comment by andymckay** [comment]
Note: here's what hekad is set to: https://github.com/mozilla-services/puppet-config/blob/master/amo/modules/olympia/files/hekad.toml#L9
