### ISSUE TITLE
Create a sitemap for AMO

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9753]
The next "big" SEO step for AMO is to have its own `sitemap.xml` so that we can feed crawlers (Google, etc.) with URLs we want to index (not for Q4 2018). This is not an easy task because we have many add-ons (and many locales), hence many add-on detail pages.

There are also limitations in a `sitemap.xml` file. For instance, we cannot add more than [50k URLs](https://support.google.com/webmasters/answer/183668?hl=en), so we need to create a main `sitemap.xml` (sitemap index) and smaller files referenced in the main one. A good example is this `sitemap` from Der Spiegel: http://www.spiegel.de/sitemap.xml.

Quoted from the SEO report:

> Sitemaps help crawlers to more easily find pages on big websites that actually changed, thus saving crawl budget. Sitemaps also make it easier for webmaster tools to find errors and opportunities. The sitemap needs for every url that is indexable exactly one entry, every entry needs a last-updated tag, and only indexable urls must be in the sitemap. We need one sitemap index and then one sitemap for every locale, and because this sitemaps will be quite huge, we need to find a way to cut them into pieces. One for /en-US/firefox/addons/, one for /en-US/android/addon/, one for the categories, and one for the users aso. Google limits for a sitemap is around 50k links. The sitemap index has no limit. The sitemaps need to be cached and basically the fastest page on the whole site.

We need to define a strategy to split all those URLs in chunks and make it future-proof. Because those files need to be generated, it probably makes sense to generate/store/cache them in addons-server.

/cc @rraue

**Comment by diox** [comment]
I haven't used it in a while, but django has https://docs.djangoproject.com/en/2.1/ref/contrib/sitemaps/ to help us. It handles sitemap index & multiple sitemaps. We'll need to be careful with the queries, but we can have a pretty agressive caching strategy here.

**Comment by EnTeQuAk** [comment]
Especially https://docs.djangoproject.com/en/2.1/ref/contrib/sitemaps/#creating-a-sitemap-index is useful and what we probably want to use.
