### ISSUE TITLE
Can the search api that uses a string of guids return the addons in the same sequence?

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-server#9765]
For the guide pages, I am using the search api with a string of about 3-5 guids:

for example:
`support@lastpass.com,{b76ed4e7-12a6-4f25-a27b-fc3f93289008},{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}`

Right now the order is coming up different than I would like:
https://addons-dev.allizom.org/api/v4/addons/search/?guid=support@lastpass.com,{b76ed4e7-12a6-4f25-a27b-fc3f93289008},{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

Is it possible to have it return the addons in the same order that the guid string shows here?

Please let me know if you need more info for this.

**Comment by diox** [comment]
Looks like the only way to do this within Elasticsearch it to use `script_score`, which I'd rather avoid... (Discussion in [this gist](https://gist.github.com/darklow/7132077) for instance)

The alternative is doing that in python, which is not ideal - not sure if it's best compared to doing this on the client side. Anyone else has thoughts on this ?

**Comment by rebmullin** [comment]
I can looking into rearranging these on the client side. Since there are only a few maybe this isn't a big deal.

I  was also thinking about maybe using just the addon detail api, where we just do 3-5 calls in parallel ([similar to Promise.all]:(https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/RunningTasksInParallel.md)). 

// cc @kumar303 @willdurand

**Comment by willdurand** [comment]
I think using the search API would be better than calling the API multiple times. I also think that reordering the add-ons in JS should be preferred. Maybe you don't even need to do that: you could build a hash map with the results, using the `guid` as key, and since you have the (presumably) ordered list of guids, then you can read each add-on by guid.

**Comment by diox** [comment]
I agreed with @willdurand, a single call is preferred. We could return the results as an object with the `guid` as the keys too, but it might be easier to do this on the frontend.

**Comment by rebmullin** [comment]
yep, that's a good idea. I'll tackle this on the frontend : )
