### ISSUE TITLE
Take advantage of Elasticsearch filter context when we can

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9770]
Currently, with the exception of the `exclude_addons` parameter, the search API uses a `bool` query with a list of several `must` clauses. Elasticsearch supports another type of context, [`filter`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html), which can be used to filter documents without applying a score.

The filter context clauses can be cached by ES automatically and should lead to better performance. There are quite a number of things where we could use it - basically all our `AddonQueryParam` classes except `AddonExcludeAddonsQueryParam` which is already a `must_not`.

Also: it could be useful in `AddonRecommendationView`, which wants only specific guids.

**Comment by diox** [comment]
Notes:
- In `SearchParameterFilter` we need to stop calling the internal classes `available_filters`... that's confusing.
- `ReviewedContentFilter` needs to call `filter` instead of doing a new `Bool` query, I think. Need to check the resulting elasticsearch query

**Comment by diox** [comment]
QA: Check that search works, again :) Also make sure things like making sure the list of add-ons by an author on the detail page works, correctly showing all other add-ons by this author than the one you're visiting, and also making sure non-public content is not returned by search.

**Comment by diox** [comment]
This seems to be causing some issues on dev - the featured extensions&themes are no longer found. It could be something else but I'm suspecting these changes, so I'll be reverting them to see if that does fix it.

**Comment by diox** [comment]
Reverted in https://github.com/mozilla/addons-server/pull/9979

**Comment by diox** [comment]
Reverted the revert since it wasn't the cause of the problem, which is trcked in #9980

**Comment by AlexandraMoga** [comment]
I've verified this on -dev and stage and I didn't find regressions around any of the search related functionalities mentioned.
