### ISSUE TITLE
Use `dfs_query_then_fetch` to make elasticsearch scoring more consistent

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9771]
By default, Elasticsearch scoring for documents is only calculated per shard for performance reasons. This means if you're unlucky and some of your shards contains more documents relevant to your query than the others, the score and therefore the position of each document in the results can be inconsistent with how relevant they are.

Elasticsearch provides an optional query type, [`dfs_query_then_fetch`](https://www.elastic.co/blog/understanding-query-then-fetch-vs-dfs-query-then-fetch) that makes the scoring consistent by using all shards to compute terms frequency and not just individual ones, at a small performance cost.

We briefly had that through a waffle but reverted it because the waffle itself had an additional performance cost, as it was executing a database/cache query in the search API. We should try enabling `dfs_query_then_fetch` unconditionally instead.

**Comment by diox** [comment]
QA: this is hard to test, but make sure search is still behaving correctly and there are no unexpected performance regressions with the search API.

**Comment by AlexandraMoga** [comment]
I didn't find regressions around search relevancy or performance on AMO -dev.
I'm marking the issue as verified fixed on AMO -dev with FF63, WIn10x64.
