### ISSUE TITLE
Add-on admin search

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#978]
The [current admin add-on search](https://addons.mozilla.org/admin/addon-search) on AMO is pretty terrible, so we need to rely on direct DB queries instead. This is a proposal of what we need for a new admin add-on search.

* Search add-on by name
  * Exact matches should appear on top (not the case currently).
  * The full list of results should be viewable, with pagination (currently crops to top 100).
  * Should be possible to select the type of add-on to search for, defaulting to all.
  * Every search result should include: add-on name (default locale), GUID, link to review page, status.

* Search add-on by GUID
  * Sometimes we don't have the whole GUID, so it should be possible to do partial GUID searches.

This tool should be usable for any user with the Addons:Review permission.

**Comment by muffinresearch** [comment]
I think we covered this with the api based admin search. If there's any missing features we should file new issues on mozilla/addons-frontend with the admin label.
