### ISSUE TITLE
In Edit Listing, error is generated if the description field includes less than 10 chars even with waffle off.

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9783]
Follow up for #9489 

STR:

1. Log in to AMO -dev
2. Submit a new extension
3. In the add-on details step, make sure that you include less than 10 characters in the description field
4. Finalize your submission

Actual result:
Submission is completed successfully, with no error regarding the description length

Expected result:
An error message should be displayed next to the description field specifying the minimum required length for that field

Notes:
- on the Edit Information page for listed addons, the description field is generating an error:

![image](https://user-images.githubusercontent.com/31961530/47345568-bb9e3d80-d6b3-11e8-9628-c085928b7ff5.png)

- no error is displayed either when editing an Unlisted add-on description

- reproduced on AMO dev with FF62, WIn10x64

**Comment by AlexandraMoga** [comment]
@eviljeff here is something I do not understand: if the minimum 10 character length for the Description filed in the upload flow is gated by the `content-optimization` waffle, why is this limitation imposed in the Edit information page when the waffle is Off?  (see Notes and screenshot above)

**Comment by eviljeff** [comment]
@AlexandraMoga _that_ seems like a bug.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

- with the `content-optimization` waffle off, there is no minimum character limitation for the description field:

![descr not mandatory](https://user-images.githubusercontent.com/31961530/47486552-482e3480-d849-11e8-997b-e2f154c0355f.gif)
