### ISSUE TITLE
remove old submission flow feature that prepopulates description field with cropped summary text in en-US

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9784]
Follow up for #9489 

STR:
1. Log in to AMO dev
2. Create a new extension package and make sure that the `"description"` in your manifest has more than 250 characters
3. Submit your add-on
4. Observe the Summary and Description fields content in the details submission step

Actual result:
A portion of the `"description"`provided is displayed in the Summary field, while the Description has the entire text, including the portion displayed as Summary. The character count in the Description field is 0.

Expected result:
Since dev hub is limiting the summary to 250 characters, maybe a check should be included in the linter (?) to make sure that the manifest `"description"` has the required length. 

Notes:
- For non-extension types, where the Description field is not present during submission, Summary will include the entire manifest `"description"` , but the field will specify by how many characters the maximum length is exceeded.
- reproduced on AMO -dev with FF62, Win10x64

![description_submission](https://user-images.githubusercontent.com/31961530/47347705-78929900-d6b8-11e8-843f-17a3a528e554.png)

**Comment by AlexandraMoga** [comment]
@eviljeff to me, this looks like a regression from #9489 The behavior described above is visible in the upload  flow (the screenshot I've posted is actually from the upload flow) and the same results will be, of course, reflected in the Edit information page after the submission is completed. 

This hasn't been the case before having the description field added in the submission flow. Previously, the entire manifest `"description"`, no matter how long, was included in the Summary field.

**Comment by eviljeff** [comment]
@AlexandraMoga can you provide a sample zip file?  I tried on addons-dev and can't replicate.

[rhinkerk-cassum-caraby.zip](https://github.com/mozilla/addons-server/files/2510549/rhinkerk-cassum-caraby.zip)

**Comment by AlexandraMoga** [comment]
@eviljeff I've tried with the extension posted by you above and I'm still reproducing :(

![image](https://user-images.githubusercontent.com/31961530/47439012-40708080-d7b4-11e8-96ee-f06311d61c60.png)

**Comment by jvillalobos** [comment]
We're reducing the size of the summary even more this quarter, so the `description` from the manifest will be cropped in more cases in the future. The limitation will also be added to the linter, so it's more likely that developers will see it before uploading.

Agree that the AMO description field shouldn't be pre-populated.

**Comment by eviljeff** [comment]
@AlexandraMoga bizarrely, this is l10n related - if I submit with https://addons-dev.allizom.org/en-US/developers then I can replicate what you see.  If I submit with https://addons-dev.allizom.org/en-GB/developers then the description isn't pre-filled.

**Comment by AlexandraMoga** [comment]
@eviljeff  yes, you are right. I've tried with several different locales, but I only reproduced with `en-US` as well.

Here is an example for `de`
![image](https://user-images.githubusercontent.com/31961530/47503153-1bdade00-d872-11e8-8369-5d146545bac3.png)

**Comment by eviljeff** [comment]
So, from poking around in git, this is actually deliberate behaviour, added 7 years ago - see https://bugzilla.mozilla.org/show_bug.cgi?id=705892 (for some reason making it en-US only was considered a good enough fix).  We just havn't seen it since description hasn't been in the upload flow for a while.  

@jvillalobos can you confirm that you want this "feature" removed?  Or you want the summary auto-cropping but don't want the description pre-populated with the full text.

**Comment by jvillalobos** [comment]
I can confirm we don't want the AMO long description to be pre-populated.
