### ISSUE TITLE
Dev Hub Edit Information page contains some sections that are no longer used

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9785]
STR:

1. Log in to Developer Hub
2. Go to Manage My submissions and select an add-on to open its Edit information page
3. Scroll down to the Technical Details section and notice the available edit options

Actual result:
Developer Comments, Required Add-ons and Add-on Flags don't seem to be used anymore in the new listing pages. The Required Add-ons search field is also returning suggestions of disabled legacy add-ons which should o longer exist on the site.

Expected result:
If there is no future plan to use these fields, they should be removed from the Edit Information page.

Cc @jvillalobos for his input

![image](https://user-images.githubusercontent.com/31961530/47349185-bcd36880-d6bb-11e8-9e50-f47d329bc60b.png)

**Comment by eviljeff** [comment]
#8668 mentions the external software flag so that can be closed too depending on Product response to this.

**Comment by wagnerand** [comment]
@jvillalobos Why would we want to drop the external software flag? That would still be relevant and useful for webextensions.

**Comment by eviljeff** [comment]
> Why would we want to drop the external software flag? That would still be relevant and useful for webextensions.

We don't expose the external software flag to anyone other than the developer, anywhere; so relevant and useful to who?

**Comment by wagnerand** [comment]
Why aren't we exposing it on the product page?

**Comment by jvillalobos** [comment]
We haven't been exposing that information at least since we moved to the new frontend. Most of those extensions use native messaging anyway, so there's some redundancy (see https://github.com/mozilla/addons-server/issues/7170). I don't think we need that flag, and it isn't something that users or devs are asking for.
