### ISSUE TITLE
Do not allow AMO links in the `homepage` field of a user profile

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9790]
See also: #9012

---

The purpose of this issue is to NOT allow AMO links in the `homepage` field of a user profile. The API should return an error if that's the case given that we can use addons-frontend to edit a user profile.

I suppose we also want to backport this change in DevHub.

**Comment by eviljeff** [comment]
> I suppose we also want to backport this change in DevHub.

You can't edit user profiles in devhub so I dropped that label.

**Comment by willdurand** [comment]
ah, ok. I think I meant the legacy frontend then?

**Comment by willdurand** [comment]
> If you think its worth fixing there, yeah.

Actually, this is already protected by the patch for #9012 🎉

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64

The 'Homepage' field from the edit profile page restricts links pointing to AMO:

new-frontend:
![image](https://user-images.githubusercontent.com/31961530/47657828-7c338d80-db9a-11e8-800e-18227f348494.png)



legacy frontend:
![image](https://user-images.githubusercontent.com/31961530/47657838-82296e80-db9a-11e8-9f4a-ba59907b96e8.png)
