### ISSUE TITLE
Lots of modified files after installation

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9796]
### Describe the problem and steps to reproduce it:

1. Follow the steps to install this project: https://addons-server.readthedocs.io/en/latest/topics/install/docker.html
2. Run `git status`

### What happened?

Many files are marked as "modified".

### What did you expect to happen?

A clean state (i.e. no files should be marked as "modified").

### Anything else we should know?

I am not sure why the `src/olympia/lib/product_json/` directory is versioned with content in it. Could we wipe it in the source tree, add a `.gitkeep` and ignore it maybe?

**Comment by EnTeQuAk** [comment]
This has been fixed by #9516
