### ISSUE TITLE
`docker-compose up -d` should not start addons-frontend and selenium/firefox

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9797]
### Describe the problem and steps to reproduce it:

See the install steps at: https://addons-server.readthedocs.io/en/latest/topics/install/docker.html

### What happened?

The addons-frontend and selenium-firefox containers are started when running `docker-compose up [-d]`.

### What did you expect to happen?

While booting addons-frontend might be a good idea, I don't expect selenium/firefox to be up by default. It fails to initialize anyway, but it is still listed in `docker-compose ps`.

I would also argue that we should not boot addons-frontend by default, given that there is a port conflict (same port is used for the `addons-frontend` container here and in the addons-frontend repo). From the addons-frontend repo, one can run `yarn amo` to use the addons-server API.

Every time I run `docker-compose up` in this project, I have to kill the addons-frontend container (or make sure I run the addons-frontend project first, so that the port is already bound and the container dies by itself).

That's my very own opinion though, with the POV of a new contributor to addons-server. I find it perfect to run the API and Dev Hub via docker and this project, but to have the addons-frontend project installed on its own.

**Comment by eviljeff** [comment]
Agree about selenium-firefox - unless you're running the UI tests locally you don't need it.  Having `addons-frontend` running is kinda useful though so you can locally use the full stack without having to setup/maintain other repos.  Can we just run it on a different port?

**Comment by EnTeQuAk** [comment]
At least regarding the selenium container, there is #9288 to work on that.

**Comment by diox** [comment]
Note that we definitely want addons-frontend now with the way addons-nginx is set up.

**Comment by eviljeff** [comment]
related: https://github.com/mozilla/addons-server/issues/11054

**Comment by eviljeff** [comment]
may as well close this as the ui-tests are being moved out of addons-server.
