### ISSUE TITLE
description for versions (version notes) only shown in default language

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#980]
I have an add-on which had its default language set to German ('de'). The version notes I provided are/were only shown if I browsed the site in German.

The [German versions page](https://addons.mozilla.org/de/firefox/addon/counter-for-mozillas-eoy-fund/versions/) contained the descriptions, the [English one](https://addons.mozilla.org/en-US/firefox/addon/counter-for-mozillas-eoy-fund/versions/) not.

**Comment by EnTeQuAk** [comment]
We are going to touch and change quite a few of these pages in the near future so I believe it will be fixed during one of these rewrites. That's why I'm closing this issue.
