### ISSUE TITLE
Search: searching for "Hide IP address" doesn't find Stealthy

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9802]
Follow up for #6838 

1. Load AMO stage
2. Do the following search: https://addons.allizom.org/en-US/firefox/search/?q=Hide%20IP%20address

Expected result:
[Stealthy](https://addons.allizom.org/en-US/firefox/addon/stealthy/?src=featured) is found highest in search results list, because it includes the "Hide your IP address" string in its description

Actual result:
[Stealthy](https://addons.allizom.org/en-US/firefox/addon/stealthy/?src=featured) is not listed at all in search results because the searched string "Hide IP address" is missing the "your" part

Notes:
- if you're searching for "Hide your IP address" , Stealthy is the only result returned

![image](https://user-images.githubusercontent.com/31961530/47481509-72c5c080-d83c-11e8-8dfc-0df104261cdf.png)

**Comment by diox** [comment]
Same problem as https://github.com/mozilla/addons-server/issues/9803 so I'm closing as duplicate.
