### ISSUE TITLE
Search: searching for "find deals" doesn't find Ciuvo price checker 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9803]
Follow up for #6838 

1. Load AMO stage
2. Do the following search: https://addons.allizom.org/en-US/firefox/search/?q=find%20deals

Expected result:
[Ciuvo price checker](https://addons.allizom.org/en-US/firefox/addon/ciuvo/?src=search) is found highest in search results list, because it includes the "finds best deals" string in its summary

Actual result:
[Ciuvo price checker](https://addons.allizom.org/en-US/firefox/addon/ciuvo/?src=search) is not listed at all in search results because the searched string "find deals" is missing the "best" part

Notes:
- if you're searching for "find best deals" , Ciuvo is found first in the list

![image](https://user-images.githubusercontent.com/31961530/47483499-16fe3600-d842-11e8-8b37-6de7986b0e60.png)

**Comment by diox** [comment]
Yeah, we're not smart enough for this query. We only try to run a `match_phrase` against the description and that's it. Maybe we should do a regular `match` with some carefully crafted options instead.

**Comment by diox** [comment]
The proposed fix for https://github.com/mozilla/addons/issues/731 or https://github.com/mozilla/addons-server/issues/9933 should fix this.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF63, Win10x64

Ciuvo price checker is now found when searching for "find deals"

![image](https://user-images.githubusercontent.com/31961530/48826352-b693e300-ed72-11e8-9cbb-fa66ce04451c.png)
