### ISSUE TITLE
The validator shows a server error when submitting an invalid add-on package

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9807]
STR:

1. Log in to AMO stage
2. Submit a new add-on package that has some invalid content - i.e `mnifest.json` instead of `manifest.json`
3. Observe the validation results

Actual result:
A server error is received:  _Received an empty response from the server; status: 500_

Expected result:
The error should be: _Add-on missing manifest._

Notes:
- reproduced only on dev and stage, though I'm not sure if this is a regression from this week or it happened before as well, but we didn't catch the error until now

![image](https://user-images.githubusercontent.com/31961530/47503580-25b11100-d873-11e8-8d38-639207156ef2.png)

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/4881640/

**Comment by diox** [comment]
Looks like it's caused by `get_addon_akismet_report()` from that stacktrace.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/47783701-136c2280-dd0c-11e8-84a7-991457c3d94d.png)
