### ISSUE TITLE
The "Theme" link from Dev Hub homepage is redirecting to a nonexistent page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9809]
STR

1. Open the developer Hub homepage - https://addons.mozilla.org/en-US/developers/
2. Scroll down to the footer section and click on Themes

Actual result:
A 404 page is received

Expected result:
A theme submission guideline page should be opened

Notes:
- until recently, this page used to have a LWT submission guideline. This should probably be replaced with the new static theme submission rules from - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme . This page doesn't have a guideline for using the wizard though, so this part should be treated separately. 
- reproduced on all AMO servers with FF63, Win10x64

![lwt guide error](https://user-images.githubusercontent.com/31961530/47505631-2d72b480-d877-11e8-8c4b-fd3a6fd70c51.gif)

**Comment by AlexandraMoga** [comment]
from @eviljeff 

>that page is linked from other MDN pages too, e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-lwtheme so it might be a bug on their side

**Comment by arshadkazmi42** [comment]
Is this issue still available? I can work on this, if its available.

**Comment by eviljeff** [comment]
@arshadkazmi42 not yet - there's no decision on what the replacement link should be

@jvillalobos / @atsay what theme link do we want here instead?

**Comment by arshadkazmi42** [comment]
@eviljeff Ok.
I will wait for an update for the link and will fix it once I get the link

**Comment by jvillalobos** [comment]
I think the appropriate replacement is https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes

**Comment by eviljeff** [comment]
@arshadkazmi42 you can take the issue now :)

**Comment by arshadkazmi42** [comment]
Thanks, @eviljeff @jvillalobos 
I will start working on it.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

![2018-11-20_11-45-07](https://user-images.githubusercontent.com/31961530/48766145-77a35600-ecbc-11e8-8f0c-aff26c6b556d.gif)
