### ISSUE TITLE
Can't change default language of add-on

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#981]
I am trying to edit the default language of [https://addons.mozilla.org/de/developers/addon/counter-for-mozillas-eoy-fund/edit](one of my addons). Changing it from German to English (US) fails even with modified description with

German error message:
Bevor Sie Ihre Standardsprache ändern, müssen Sie in dieser Sprache einen Namen, eine Zusammenfassung und eine Beschreibung haben. Es fehlt noch 'description'.

Translation:
Before changing your default language, you have to provide a name, a summary and a description for this langage. 'description' is missing.

**Comment by EnTeQuAk** [comment]
I believe the default language is configured in the install.rdf for regular add-ons and in the manifest.json for WebExtensions. Uploading a new version should already overwrite the configured default_language imho so maybe we should just remove the ability to change it in the UI? Or leave it and wait for our overhaul.

**Comment by Archaeopteryx** [comment]
> I believe the default language is configured in the install.rdf for regular add-ons
They don't know a default language.

**Comment by EnTeQuAk** [comment]
Indeed I was wrong, that's just the case now for WebExtensions and for regular add-ons it simply defaults to English.

**Comment by EnTeQuAk** [comment]
@Archaeopteryx so, you're saying that you have a proper description for en-US?

**Comment by diox** [comment]
I tested it on one of my add-ons on dev and was able to change the default locale successfully. The message might be unclear: you need to a translation to exist for those fields in the locale you're setting as the default. This means that you need to change the current locale to english using the selector on the top right corner of the devhub page, enter a translation for name, description, summary, hit save, *then* change the default locale to english.
