### ISSUE TITLE
Reindex is switching to the new alias too soon

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9811]
STR:
- Trigger a reindex

Expected results:
- While the reindex is ongoing, the old index should still be present, and be used for search - the alias we use should not point to the new index yet.

Actual results:
- While the reindex is ongoing, we seem to be switching over to the new index immediately, removing the old one. The command returns fairly quickly showing the new alias configuration.

For users this means their search results will be incomplete for a while, possibly completely empty while we reindex, which is not cool.

**Comment by diox** [comment]
We seem to be setting up the task chain correctly and then it's all for nothing because `index_data()` task just calls `get_modules()[alias].reindex(index)`. That eventually calls `reindex_addons()` which triggers the individual tasks in a group... completely independent from the rest, so `index_data()` returns almost immediately and the rest of the chain is executed before we're done with the reindexing.

We need to refactor the whole thing to integrate the index tasks into the main task chain - essentially try to return the index tasks to add them to the group instead of triggering them from the reindex function. The trick being that we need to not break statistics reindexing at the same time (it's not enabled by default, but it still needs to work if the option is passed)

**Comment by diox** [comment]
QA: to test this, ask someone with access to dev to trigger a reindex. While the reindex is taking place, search should work normally : the number of results should stay the same, you should be able to find any add-on as normal. Same thing once the reindex is complete.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

Search on -dev was tested before, during and after the reindex. Search results behaved normally.
