### ISSUE TITLE
[Reviewer Tools] Higher Weighting for WASM inclusion

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#9821]
Today, for the first time, I noticed as add-on with a WASM file.
`https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/1124242/file/webp/webp_wasm.wasm#top`

I would imagine add-ons with _.wasm_ (like _.exe_ or _.dll_) would require closer attention.

@wagnerand

**Comment by diox** [comment]
@jvillalobos @wagnerand
