### ISSUE TITLE
Door hanger error message doesn't stick up to the corresponding field when scrolling 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9823]
STR

1. Log in to AMO -dev
2. Submit a new add-on
3. In the upload flow details page, insert less than 10 character in the Description field
4. Try to finalize the submission
5. Observe the error message displayed below the Description field
6. Scroll up and own

Actual result:
The error message changes its position when scrolling [1]

Expected result:
The error message sticks to the field that generated it

Notes:
- other pages that use the same error style have the same behavior: see source code upload form [2]
- reproduced on AMO -dev with FF63, Win10x64

[1]
![srolling error](https://user-images.githubusercontent.com/31961530/47561269-813ad780-d923-11e8-82c6-f6b1863d7a63.gif)

[2]
![image](https://user-images.githubusercontent.com/31961530/47561292-8ef05d00-d923-11e8-8323-369475dd39dd.png)

**Comment by suhailsinghbains** [comment]
Hi, Can I please be assigned this issue?
Thanks

**Comment by EnTeQuAk** [comment]
Hey @suhailsinghbains, I added the `contrib: assigned` label. Please let us know if you're running into any problems or need help.

**Comment by suhailsinghbains** [comment]
I completely forgot about this, I'll try to solve this.

**Comment by suhailsinghbains** [comment]
I got the file to work on, will submit a PR today itself.

**Comment by suhailsinghbains** [comment]
I cannot find the CSS class that is being used in [this](https://github.com/suhailsinghbains/addons-server/blob/master/src/olympia/devhub/templates/devhub/addons/submit/source.html#L83)
I need help here.
Thanks

**Comment by junngo** [comment]
This `Description field` is not required.
![Screenshot from 2019-11-19 00-00-10](https://user-images.githubusercontent.com/29684524/69063392-c4507700-0a5f-11ea-8f10-62ae7c8beb00.png)

So, I think that this issue doesn't happen anymore.
