### ISSUE TITLE
Issue while deploying the addons-server on openshift

### ISSUE THREAD

**Issue by sunilk747** [mozilla/addons-server#9839]
### Description
I am trying to deploy addons-server on openshift using the docker-compose file available in the repo. 
Using this command `kompose -f docker-compose.yml --provider openshift up`. Some of the service ran without error but some didn't. I managed to bring up 9 service with some workarounds, but I am having problems in bringing up the web and worker service.
Error from logs: 
`container_linux.go:247: starting container process caused "exec: \"./scripts/start-docker.sh\": stat ./scripts/start-docker.sh: no such file or directory"
`
Any sort of help would be highly appreciated.

**Comment by diox** [comment]
Hi,

We don't support installing addons-server using anything other than the installation instructions over at https://addons-server.readthedocs.io/en/latest/topics/install/docker.html
