### ISSUE TITLE
Investigate name matching in search and analyzer used

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9844]
Separate to the language-specific analysis, we index ``name`` using a custom analyzer that does a lot of fancy stuff:
```python
            'standardPlusWordDelimiter': {
                'tokenizer': 'standard',
                'filter': [
                    'standard', 'wordDelim', 'lowercase', 'stop', 'dict',
                    'unique'
                ]
            }
```

Then, when using ``name`` in search, we do a ``Match``, a ``MatchPhrase``, a ``MatchPrefix`` and a ``Match`` with ``'fuziness': 'AUTO'`` if the search query is not too long.

However, that first ``Match`` is done with `'analyzer': 'standard'` applied. Why ? What's the impact ? Doesn't that negate the benefit of our `standardPlusWordDelimiter` in some cases ? Or is that ok because it will be used by the fuzzy one when we truly care about it ?

**Comment by kplotnik** [comment]
Closing as obsolete.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-171
