### ISSUE TITLE
Please return the version id in the current_version for add-ons returned from the discovery API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#9855]
In order to support the new way of accessing versions, which is by versionId, we need the [discovery API](https://addons-server.readthedocs.io/en/latest/topics/api/discovery.html) to return the id of the current version inside the `current_version` object for each add-on returned.

This blocks https://github.com/mozilla/addons-frontend/issues/6727, so if it could be done soon that would be greatly appreciated.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

Before:
![image](https://user-images.githubusercontent.com/31961530/47910751-742a6500-de9c-11e8-89a3-9999bb806336.png)

After:
![image](https://user-images.githubusercontent.com/31961530/47910764-81dfea80-de9c-11e8-80dd-2efbbc62c527.png)
