### ISSUE TITLE
Help test setting up the Docker environment and report back issues

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-server#9856]
We have a lot of contributors looking to contribute to addons-server issues, and we're noticing an increasing number of users with different platforms having issues with getting the docker environment setup and running at various stages.

We'd therefore appreciate help from anyone running on **Windows**, **Linux** or **OSX** who can report back any trouble they're having with getting the addons-server environment up and running.

Ideally you'll be good at problem solving and already have some familiarity of docker-based development environments and can debug any issues you come across following the documentation.

The steps are as follows:

* 📖 Follow the instructions here https://addons-server.readthedocs.io/en/latest/topics/install/docker.html using your platform.
* 👩‍🚀 Once you can view the server locally on your machine, try submitting a web extension - you can get a test extension from http://staticfil.es/webext-generator/
* 🗒 Note any problems you have along the way and anything you did to work around them.
  1. [File a new issue with the details here](https://github.com/mozilla/addons-server/issues/new)
  2. Please be sure to include what platform you're running and docker versions etc.
  3. Include details of where our instructions are unclear or wrong - please uses links to the documentation where possible. See https://github.com/mozilla/addons-server/blob/master/docs/topics/install/docker.rst for the source of the docker env install instructions.
  4. Add `refs #9856` to your issue so it points back to this issue.
  5. Draw my attention to it by mentioning me by including `@muffinresearch` in a comment 👍

*Bonus points if you can submit a patch to fix the documentation.* ✨ 🚀

If you do get completely stuck and can't finish the setup please [file a new issue](https://github.com/mozilla/addons-server/issues/new) detailing what step you got to and what error message you're seeing and we'll attempt to reproduce.

**Comment by diox** [comment]
FWIW I believe https://github.com/mozilla/addons-server/issues/9659 is the main issue people are going to run against locally - I've ran into it when resetting my env.

**Comment by wagnerand** [comment]
For me, indexation never finishes. I set up a vanilla macOS 10.14 machine and followed the instructions above. The last (descriptive) output I get is `Running all indexation tasks`. After that, it's just dots. I had it running for about an hour, then canceled it. Even after restarting the containers, I get `CommandError: Indexation already occurring - use --force to bypass` when trying to run `./manage.py reindex`. Adding the `--force` option will start the process, but again it doesn't seem to finish.

**Comment by SeanPrashad** [comment]
Hey guys ✌🏽 I hate to see other contributors getting stuck before they get a chance to touch the problem - it can be very frustrating 😞 I want to help out with this one as I think we can polish up the docs even further 📝

I'll comb through the existing docs and re-setup addons-server over the next couple of days on OSX. If I'm able to do that before Christmas, I'll give it a shot on Windows 7 & 10 and Linux via VirtualBox (_I suspect I might need to do some stuff for [Hyper-V on Windows](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/)_).

**Comment by diox** [comment]
IMHO the biggest issue we need to solve is https://github.com/mozilla/addons-server/issues/9659 as I mention above. If we get this fixed, it would help tremendously.

**Comment by SeanPrashad** [comment]
Ok - gunna take a look at that first

**Comment by EnTeQuAk** [comment]
I just merged various changes regarding our docker setup that should improve how things are working as part of working on #12366

So I'd love to get some feedback here. It also fixed #9659 but I'm pretty sure there are other gotchas in our docker setup.

**Comment by avgupt** [comment]
@muffinresearch I face the following problem : https://github.com/mozilla/addons-server/issues/13857
