### ISSUE TITLE
Use "Edit Product Page" instead of "Edit Listing" or "Edit Information"

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-server#9857]
What we used to call "listing page" is now being called "product page". To keep the terminology consistent, we need to update some references to it in the devhub.

- [ ] In the logged in view in `/developers/`, rename the `Edit Listing` link as `Edit Product Page`.
- [ ] In the logged in view in `/developers/`, next to the `Welcome back` title, replace `creating an appealing listing` for `creating an appealing product page`.
- [ ] In `/developers/addons/` and `/developers/themes/`, rename the `Edit Information` link as `Edit Product Page`.
- [ ] In the Edit view for an add-on (e.g. `/developers/addon/amo-admin-assistant/edit`), change the page title to `Edit Product Page`.
- [ ] In the Edit view for an add-on (e.g. `/developers/addon/amo-admin-assistant/edit`), rename the `Edit Information` link in the sidebar as `Edit Product Page`. This applies to all edit pages that use this sidebar.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64
> * In the logged in view in `/developers/`, rename the `Edit Listing` link as `Edit Product Page`
> * In the logged in view in `/developers/`, next to the `Welcome back` title, replace `creating an appealing listing` for `creating an appealing product page`.
![image](https://user-images.githubusercontent.com/31961530/48474752-e3407b80-e803-11e8-8a15-354d0de00465.png)

> * In `/developers/addons/` and `/developers/themes/`, rename the `Edit Information` link as `Edit Product Page`.
![image](https://user-images.githubusercontent.com/31961530/48474839-18e56480-e804-11e8-9639-fcae025bfd51.png)


> * In the Edit view for an add-on (e.g. `/developers/addon/amo-admin-assistant/edit`), change the page title to `Edit Product Page`.
> * In the Edit view for an add-on (e.g. `/developers/addon/amo-admin-assistant/edit`), rename the `Edit Information` link in the sidebar as `Edit Product Page`. This applies to all edit pages that use this sidebar.
![image](https://user-images.githubusercontent.com/31961530/48474906-3adee700-e804-11e8-801e-6320ea7d7202.png)

I think there are more sections that require this change, so I filed a follow up to address those as well.
