### ISSUE TITLE
Initial setup: Indexation never finishes

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9867]
refs #9856

For me, indexation never finishes. I set up a vanilla macOS 10.14 machine and followed the instructions above. The last (descriptive) output I get is `Running all indexation tasks`. After that, it's just dots. I had it running for about an hour, then canceled it. Even after restarting the containers, I get `CommandError: Indexation already occurring - use --force to bypass` when trying to run `./manage.py reindex`. Adding the `--force` option will start the process, but again it doesn't seem to finish.

[docker-celery.log](https://github.com/mozilla/addons-server/files/2538821/docker-celery.log)

[container_web.log](https://github.com/mozilla/addons-server/files/2538835/container_web.log)

[container_es.log](https://github.com/mozilla/addons-server/files/2538836/container_es.log)

OS: macOS 10.14.1
Docker: 18.06.1-ce-mac73 (26764)

**Comment by diox** [comment]
This should now be fixed in master @willdurand @wagnerand . Let me know if it works for you.

**Comment by diox** [comment]
Also, just in case, I'd still advise doing a `manage.py reindex --wipe` after you update to master, if you're not completely starting from scratch, just in case your index is in a weird shape because of that bug.
