### ISSUE TITLE
Change static theme preview to use zip sourced background files

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9868]
#9847 added some code to load the background files for a theme directly out of the zip file so we weren't dependant on having image files publicly accessible on the CDN.  We should change the static theme render to do a similar thing.

**Comment by AlexandraMoga** [comment]
@eviljeff should I check that static theme previews are rendered correctly - both for new submissions and new version uploads - or is there something more specific to be followed?
Thanks

**Comment by eviljeff** [comment]
@AlexandraMoga if they're rendered correctly (as before) it's working.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

No regressions found with static theme previews.
