### ISSUE TITLE
Change reviewer tools to use zip sourced background filed

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9871]
#9847 added some code to load the background files for a theme directly out of the zip file so we weren't dependant on having image files publicly accessible on the CDN. We should change the reviewer tools also so we can stop extracting the files.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

No regressions for static theme previews noticed in Rev Tools
