### ISSUE TITLE
theme wizard: If you select a file you can't submit until you make another change

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9873]
STR:
* select a background image in the static theme wizard
* see the filename is filled in and there are default colors for the required fields
Actual result:
* You can't submit (this is because the filename generated isn't reflected in the manifest)
* Changing the theme name at all (or any colors) enables the submit button though.
Desired result:
* You can submit because all required fields are filled in.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64

![2018-11-05_09-34-55](https://user-images.githubusercontent.com/31961530/47984290-dbcff280-e0de-11e8-9929-357c8eb788ec.gif)
