### ISSUE TITLE
It shouldn't be possible to upload animated GIFs in the static theme wizard file selector

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#9883]
Follow up for #9667 

1. Log in to AMO Developer Hub
2. Submit a new static theme through the wizard
3. Upload an animated GIF as header background

Actual rsult:
Animated GIFs can be uploaded in the wizard file selector. However, after submission, the theme will not render the animation. 

Expected result:
As mentioned in the [specification](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#Image_formats), it shouldn't be possible to upload animated GIFs as a static theme header background. 

Notes:
- reproduced on all AMO servers with FF63, Win10x64

![animated gif](https://user-images.githubusercontent.com/31961530/47982722-70cfed00-e0d9-11e8-8fd1-40a033ef3eda.gif)

Result:
![image](https://user-images.githubusercontent.com/31961530/47982834-d91ece80-e0d9-11e8-91d8-27e8d9e04f8e.png)

**Comment by jvillalobos** [comment]
Still valid.
