### ISSUE TITLE
move binary operators to start of the line in our python code

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9885]
Since Flake8 3.6.0 started enforcing W504 (#9795) binary operators can't be on the end of the line so we need to reformat to be compliant.  W504 is currently on the ignore list because there's 500+ places that fail otherwise.

**Comment by EnTeQuAk** [comment]
:see_no_evil: #8617 :see_no_evil:

**Comment by eviljeff** [comment]
when black stops emitting broken line lengths I'm for it 😛

**Comment by willdurand** [comment]
See also: https://www.flake8rules.com/rules/W503.html
