### ISSUE TITLE
Option to hide all but the latest add-on rating in API listing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-server#9906]
### Describe the problem and steps to reproduce it:

From https://github.com/mozilla/addons-frontend/issues/6515 

* As a developer, publish version 1 of an add-on
* As a user, sign in and rate version 1 of the add-on
* As the developer, publish version 2 of the same add-on
* As the user, sign in and rate version 2 of the add-on
* As the user, go to your user profile page and look at all the reviews listed

### What happened?

The frontend uses the API to [list all ratings](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#list-ratings) and that list includes multiple reviews per add-on, if they exist. 

### What did you expect to happen?

The rating listing should only include the latest review for each add-on.

### Anything else we should know?

I don't know if this should be the default behavior for the rating listing or it should be triggered by a query param. Either way will work for the frontend.

In https://github.com/mozilla/addons-frontend/issues/4529 we will effectively stop users from rating an add-on more than once. However, the historic data will remain.

**Comment by diox** [comment]
Worth noting that this is already the default when the `addon` param is passed (we apply `qs.filter(is_latest=True)` for this exact purpose). We could make it the default for the user list as well, though maybe it's better to just implement https://github.com/mozilla/addons-server/issues/9393 and do a migration to remove the old "duplicate" ratings, removing the need for this field entirely ?
