### ISSUE TITLE
API endpoint to "repack" an add-on

### ISSUE THREAD

**Issue by magopian** [mozilla/addons-server#991]
This endpoint will allow us to repack add-ons locally, before re-uploading them on AMO, instead of implementing custom, one-off management commands each time we need a new fix (eg: bulk add-on signing, re-signing of files, fixing the "let scope bustage"...).

Use case:
1/ download a xpi file locally (using another endpoint?)
2/ modify it locally
3/ upload the xpi file back using the "repack" endpoint

Once re-uploaded, the add-on should
1/ make sure it's for the correct add-on GUID
2/ create a backup of the current file, named something like `the-filename.xpi.backup_<suffix>`
3/ bump the version number in the manifest file (add a `.1-<suffix>`)
4/ re-sign it if `File.is_signed is True`
5/ update the `Version.version` number
6/ send an email to the add-on author explaining that his add-on was repacked, and a reason for that repack

That endpoint should only be allowed for users with the `Addons:edit` permission.

**Comment by EnTeQuAk** [comment]
I very honestly don't think we need an api endpoint for that. repacks should not occur that often. @andymckay or is there an actual need for that to be implemented?

Closing for now though...

**Comment by andymckay** [comment]
Fair enough. This was part of the "lets stop writing custom management commands and focus on writing API's" plan.
