### ISSUE TITLE
Add timing metrics to LWT migration

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9912]
We know roughly how long 500/1000 LWT take* to migrate, from watching kibana logs, but we don't know how long exactly each step in the migration takes.   Once we know how long things take we can look to optimize the slow parts.

*1000 LWT took 65 minutes on -dev last time it was run.  Though, a) there have been a number of changes since then and b) prod could|should be quicker because more resources.

**Comment by AlexandraMoga** [comment]
@eviljeff should this be a qa:not needed?

**Comment by diox** [comment]
@eviljeff can you add your findings in this issue ?

**Comment by eviljeff** [comment]
datadog screenshot:
![screenshot 2018-11-11 14 04 36](https://user-images.githubusercontent.com/768592/48314210-2c06f300-e5be-11e8-9a50-12d780f36128.png)

**Comment by diox** [comment]
It's 03:38 am and I can't sleep... can't really code either, but `utc_millesecs_from_epoch` *is* suspicious:
```python
def utc_millesecs_from_epoch(for_datetime=None):
    """
    Returns millesconds from the Unix epoch in UTC.

    If `for_datetime` is None, the current datetime will be used.
    """
    if not for_datetime:
        for_datetime = datetime.datetime.now()
    return calendar.timegm(for_datetime.utctimetuple()) * 1000
```

That's not good... 

```
>>> from olympia.amo.utils import utc_millesecs_from_epoch
>>> from datetime import datetime, timedelta
>>> now = datetime.now()
>>> later = now + timedelta(milliseconds=42)
>>> now == later
False
>>> utc_millesecs_from_epoch(now) == utc_millesecs_from_epoch(later)
True
>>> utc_millesecs_from_epoch(later)
1541989568000
>>> utc_millesecs_from_epoch(now)
1541989568000
```

Something like the following doesn't lose the precision (I don't know if there is a better way to do this - our dates are currently always UTC, so this should be fine?):
```python
def utc_millesecs_from_epoch(for_datetime=None):
    if not for_datetime:
        for_datetime = datetime.datetime.now()
return int(float(for_datetime.strftime('%s.%f')) * 1000)
```

**Comment by eviljeff** [comment]
Mmm, parsing a string to get back the seconds as a float... that seems... indirect.

I'm not sure why we need milliseconds from the epoch in UTC for _relative_ timing within the same task anyway.  `time.time()` seems enough, or according to the statsd [docs](https://statsd.readthedocs.io/en/v3.3/timing.html) we can pass a timedelta directly so may as well just do that.

**Comment by eviljeff** [comment]
Update: After merging #9960 the timings are more accurate, and the quicker steps are now correctly shown as a few milliseconds, but the summary is the same: most time in `Addon.initialize_from_upload`, specifically `Addon(**{k: v for k, v in data.items() if k in fields}).`; second most time in the signing.

However, at less than or 100 (i.e. the batch size) the delay in `Addon.initialize_from_upload` drops significantly - validating @diox's theory that it was large due to database blocking.

**Comment by eviljeff** [comment]
Current conclusion is that the signing process (at ~3.5 seconds) is the part taking the most time, and because it's within the transaction block, then causing the subsequent database blocking.  We're working with ops to see Autograph can be scaled|sped up.
