### ISSUE TITLE
Provide an option to return license.text from the add-on detail API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#9915]
This is in support of https://github.com/mozilla/addons-frontend/issues/3697. 

Currently, the only way to get the text of a custom license is to ask for version information via the [version detail API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail). For the new license view that is being implemented via https://github.com/mozilla/addons-frontend/issues/3697, we will need access to the `license.text`, but that is actually the only information we need from the version detail API. We will also need to retrieve the add-on detail in order to show the summary card on the left side of the screen, so it seems like it would be better if we could issue one API call (for add-on detail) as opposed to two (one for add-on detail and one for version detail). 

We would be able to do that if the [add-on detail API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail) had an option where we could state that we want `license.text` returned for the `current_version`. By default the API would still exclude `license.text`, but with this new option we would be able to request it when we know we need it.

**Comment by bobsilverberg** [comment]
Please note that https://github.com/mozilla/addons-frontend/issues/3697 is meant to land this quarter, so it would be appreciated if this could be prioritized accordingly.

**Comment by diox** [comment]
Is there any case currently where you use the add-on *detail* API and don't need the license text ?

**Comment by bobsilverberg** [comment]
> Is there any case currently where you use the add-on detail API and don't need the license text ?

Yes, we don't need it on the Add-on Detail Page, which is probably the most common use of the add-on detail API. We only need to know if a custom license exists on the Add-on Detail Page, which is why I opened #9914.

**Comment by diox** [comment]
Ah ok. It's currently not included in the detail API for performance reasons (it can be quite big for some custom licenses, and every byte counts), so yeah, having a parameter to trigger its inclusion sounds good.

Implementation notes: the ES serializer is already different (ES doesn't have License info at the moment), so we don't have to care about it. I don't know if we can change the serializer on the fly, it'd be kinda neat to be able to switch between `CompactLicenseSerializer` and `LicenseSerializer` depending on the parameter, but otherwise we could just change the fields dynamically inside `CompactLicenseSerializer`.

**Comment by eviljeff** [comment]
Extra flags to include or exclude stuff starts to get unwieldy - a separate license endpoint maybe?  What do data you actually need on the (I presume separate, new,) page?

**Comment by bobsilverberg** [comment]
> Extra flags to include or exclude stuff starts to get unwieldy - a separate license endpoint maybe? 

Yeah, I get that, but we do need a number of fields from the add-on detail as well, so I'm not sure it makes sense to create a license endpoint that also includes add-on details.

> What do data you actually need on the (I presume separate, new,) page?

You presume correctly. On the new page we need the following properties from the add-on:
- slug
- name
- ratings (which is an object)

but we are also calling functions/components that expect an `addon` object, so I'd need to inspect those too to see what they need. Making this object look different from an ordinary `addon` object (i.e., with fewer properties) will mean changing our code and type definitions to deal with this in multiple places. It would certainly be simpler and less work if we could just expect a regular add-on detail response, but with `license.text` included as well.

If you feel really strongly that we shouldn't overload the add-on detail endpoint like this, and we should define a license endpoint that returns the text as well as everything else we need, I can dig further to define all that data. Another downside to going that route is there is the potential for the design of this page to change, which could then necessitate a change to this new license endpoint. If we just go with providing all add-on details plus license text then we reduce the likelihood of more changes being required later even if the design changes.

**Comment by bobsilverberg** [comment]
As discussed on IRC, I will just make a separate API request for the version information at this time, but we should keep this open to revisit later.
