### ISSUE TITLE
Do not link to language tools for Android in the statistics page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-server#9925]
### Describe the problem and steps to reproduce it:

1. Got to https://addons.mozilla.org/en-US/android/addon/chrome-ua-on-google-android/statistics/downloads/?last=30
2. Click the "More..." menu item.

Note that if one browses the legacy website, this link is present on all pages (but this requires the `mamo` cookie to be set to `off`).

### What happened?

You see a "Dictionaries & Language Packs" link.

### What did you expect to happen?

This link should not exist because there is no such page for Android.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF63, Win10x64 and Android 8.0

https://addons-dev.allizom.org/en-US/android/addon/lastpass-password-manager/statistics/?last=30
![image](https://user-images.githubusercontent.com/31961530/48208738-2621cf80-e37c-11e8-8227-e4a2dc13f048.png)
