### ISSUE TITLE
Improve the description of the "Experimental" check box for add-ons

### ISSUE THREAD

**Issue by bjherbison** [mozilla/addons-server#9955]
### Describe the problem and steps to reproduce it:
Add-on developers are confused by the effect of checking the Experimental check box when creating an add-on.

### What happened?

Below is a comment from an add-on developer. This is not the first such comment I've received.

> You can just disable it now. The intended audience is not the general
> public.
> 
> Somehow the reviewers didn't catch this before so I concluded that checking
> the "experimental" check box meant that you could publish an extension not
> meant for the general public (which is what the description of this check
> box implies). I'm very said to see otherwise.

### What did you expect to happen?

Add-on developers not be confused about the intent of the Experimental check box.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by eviljeff** [comment]
Do you have a suggestion that isn't confusing to developers?
It currently says
> Check this option if your add-on is experimental or otherwise not ready for general use.  The add-on will be listed but will have reduced visibility.  You can change this setting later.

**Comment by eviljeff** [comment]
closing for now.  Can re-open if we get some improved text.
