### ISSUE TITLE
Fix featured collection admin management

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9964]
### Describe the problem and steps to reproduce it:
- Load /admin/features (accessible through the admin menu "Featured Add-ons" item)
- Click "Add a Featured Collection"
- Type a collection name or id in the corresponding cell
- Click Save Changes

### What happened?
- No autocompletion results appear. Saving fails saying that the collection field can't be empty, even if you typed its full id

### What did you expect to happen?
- autocompletion results should have presented you with a list of matching collections for you to choose from. Once a collection was selected, saving changes should have worked.

### Anything else we should know?
This is because this (poorly tested) admin page depends on collections in elasticsearch, which we removed a while ago. This is a problem for testing locally without having to manually create featured collections through the shell or add-on generation commands.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF63

Search results are appearing now, they can be selected and there is no more 'This field is required' error.

![2018-11-13_13-28-49](https://user-images.githubusercontent.com/31961530/48411255-b0d24800-e749-11e8-9097-92739d29427a.gif)


@diox 
There is however this "Invalid collection for this application." error that prevents changes from being saved, but I don't quite understand its source. I've tried to remove the collections that were causing the error, but this same error was impeding again.

**Comment by diox** [comment]
That error is not new and will happen if the collection isn't marked for the right application beforehand. It's possible to change this in the collection admin itself (I know, awkward - but I didn't want to overhaul the whole thing as it's not actively used anyway)

**Comment by AlexandraMoga** [comment]
It worked that way, indeed. 
I'm marking this as verified fixed.
