### ISSUE TITLE
Featured themes & extensions are empty on dev

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#9980]
Featured themes & extensions are empty on dev. At first I blamed my changes from https://github.com/mozilla/addons-server/issues/9770 and reverted them, but it didn't help. I think it's related to https://github.com/mozilla/addons-server/issues/9964 instead - not the changes themselves, but something else in the admin that was triggered when QA verified that issue.

**Comment by AlexandraMoga** [comment]
@diox  I've deleted some collections from the Featured Add-ons Admin page, so this could be the issue. However, I don't remember deleting the ones that were active on -dev. I will have a look.

**Comment by diox** [comment]
@AlexandraMoga I thought it could be the case but no, it appears to be a bug on our side regarding the default locale handling with featured collections.

The technical bits: `get_featured_ids()` with various combination of parameters return ids in every case. The API doesn't, however: it works when you don't pass the `lang`, but returns an empty result list when you do.

I thought it could be because somehow a reindex of those add-ons was missed when QA changed the featured collections in the admin, but now I think it's more complex than that.

The add-ons have been reindexed, but when you look in the index, they have:
```
result.to_dict()['featured_for']    
[{u'application': [1], u'locales': [u'']}]
```

An empty locale ? That's bad. It should either be a valid locale or the special `ALL` one. I think it's because the `FeaturedCollection` instance has a `locale` value of `''` (empty string) instead of `None`.

**Comment by diox** [comment]
And sure enough, doing the following fixed it:
```
>>> f = FeaturedCollection.objects.all()[0]
>>> f
<FeaturedCollection: Featured Add-ons (140) (1: )>
>>> f.locale
u''
>>> f.locale = None
>>> f.save()
```

**Comment by AlexandraMoga** [comment]
There used to be more featured Themes, though. Now is only one:

![image](https://user-images.githubusercontent.com/31961530/48421653-99a15380-e765-11e8-9b40-d162dc21de61.png)

**Comment by diox** [comment]
I just fixed it for the other featured collections as well. Keeping this opened to fix the root cause of the problem.

**Comment by diox** [comment]
(don't touch the featured admin for now :)

**Comment by AlexandraMoga** [comment]
Featured collection shelves are back on -dev

![image](https://user-images.githubusercontent.com/31961530/48468901-e3d21580-e7f5-11e8-982f-388f06186890.png)
