### ISSUE TITLE
Wrong signature if manifest uses 'browser_specific_settings'.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9989]
Firefox supports '[browser_specific_settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings)' as a synonym for `applications`, however, neither AMO nor autograph know about this. 

If an add-on uses `browser_specific_settings`, AMO will assign a new ID to the add-on, ignoring the one specified in the manifest. Autograph will then use that ID to sign the add-on (since it doesn't know about the property either). When you try to install the add-on, Firefox refuses to install the add-on because Firefox recognizes the ID in `browser_specific_settings` and the fact that it doesn't match the ID in the signature.

The keyword was added in https://bugzilla.mozilla.org/show_bug.cgi?id=1262005 and landed in Firefox 48.

**Comment by ExE-Boss** [comment]
I have added a&nbsp;warning to&nbsp;the&nbsp;top of&nbsp;[the&nbsp;MDN page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings).

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64

- addons with `"browser_specific_settings"` property in their manifest are now signed based on the guid provided in the manifest - i.e. no id override applied anymore
- extensions can be installed from their product page

![image](https://user-images.githubusercontent.com/31961530/48718712-98b86800-ec24-11e8-96f2-f4ab6f08733c.png)
