### ISSUE TITLE
Rikaichamp and Rikaichan stopped working in Thunderbird!!!!!

### ISSUE THREAD

**Issue by a4jp-com** [mozilla/addons-server#9996]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Update Thunderbird automatically.

### What happened?
Nothing works.

### What did you expect to happen?
Rikaichan to translate words on a mouseover

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
AMO no longer hosts add-ons for Thunderbird. See https://github.com/thundernest/addons-server/issues/new for the thunderbird related issue tracker.

**Comment by a4jp-com** [comment]
AMO?

**Comment by jvillalobos** [comment]
AMO = addons.mozilla.org

**Comment by a4jp-com** [comment]
Oh that sucks. I just want to translate my Japanese emails with something like Rikaichan or Rikaichamp. I can host the files if needed.
