### ISSUE TITLE
Expose the add-on GUID and AMO internal (numerical) ID on the review tools page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-server#9997]
Reviewers and admins need the GUID and internal AMO ID of an add-on for various purposes, let's show it on the review tools page. Probably at the top of the page, in the overview table that also holds status etc.

I am mentoring this good-first-bug. Andreea has volunteered to take it up.

Here are some starting points:

Read through: https://wiki.mozilla.org/Add-ons/Contribute/Code

https://github.com/mozilla/addons-server/blob/master/src/olympia/reviewers/templates/reviewers/addon_details_box.html is the file that builds the info box at the top of the review page, let's add I'd add it above the add-on status.
You basically just want to show `addon.guid`, wrap that in  {{ }} and put it in a paragraph, same for `addon.id`.

~~Bonus points if you fix the invalid syntax in line 19 :)~~

**Comment by wagnerand** [comment]
@andreeaNeamtiu

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/49093312-7cdc4400-f26c-11e8-9dfc-a38d71df3db2.png)

@wagnerand Maybe you know better, but I was just wondering why you have used "Add-on ID"  instead of "Add-on GUID" on the first row?

**Comment by wagnerand** [comment]
Oh yes, good question: The terms *GUID* and *ID* are often used interchangeably by us, while technically they don't mean exact same thing. In particular, GUID has a very [specific](https://en.wikipedia.org/wiki/Universally_unique_identifier) definition, and by that definition, the add-on ID is not a GUID.
